### ISSUE TITLE
Need help with blocking

### ISSUE THREAD

**Issue by grumpyg** [uBlockOrigin/uBlock-issues#1]
What is the proper way to make this filter: www.msn.com###trc_wrapper_72117, work for any number, not just 72117? 

Example of what I want to block:

https://www.msn.com/en-us/news/politics/ryan-trillion-dollar-deficits-were-inevitable/ar-AAvUpo2?li=BBnb7Kz

Bottom of every page under heading: More For You -- Promoted links by Taboola

Thanks.

**Comment by okiehsch** [comment]
`msn.com##[id*="trc_wrapper"]`
This is not a support forum, if you do not know how the filter syntax works, you can ask for help at
`https://www.reddit.com/r/uBlockOrigin`

**Comment by uBlock-user** [comment]
Please follow the **Prerequisities** mentioned in the template, they're there for a reason.

**Comment by WowDude** [comment]
> @okiehsch : `msn.com##[id*="trc_wrapper"]`

Proper is: `msn.com##[id^="trc_wrapper_"]`

**Comment by uBlock-user** [comment]
Or `msn.com###taboola-below-article-thumbnails-card-layout-short` and `msn.com##div[data-aop*="taboolawidgetvnext"]`

**Comment by grumpyg** [comment]
Thank you.  Sorry for posting in wrong place.
