### ISSUE TITLE
Immediate Crash

### ISSUE THREAD

**Issue by jmauss** [uBlockOrigin/uBlock-issues#10]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have just set up a new computer and did a fresh install of chrome. After I install uBlock, it crashes saying that I need to click the baloon to reload. After clicking, it immediately crashes again. 

### A specific URL where the issue occurs

Chrome web store - initial installation

### Steps to Reproduce

1. Go to chrome webstore and search for ublock
2. install app (and it crashes right after).

### Expected behavior:

For uBlock to install and run without crashing right away

### Actual behavior:

uBlock crashes immediately

### Your environment

* uBlock Origin version: 1.16.0
* Browser Name and version: Chromium 66.0.3359.117
* Operating System and version: macOS 10.13.4

**Comment by uBlock-user** [comment]
uBlock Origin can never crash the browser as it's HTML/CSS/JS only, you have a bad build of Chromium on your hands. Please report this to the Chromium project maintainers.

**Comment by gorhill** [comment]
> I performed a cursory search of the issue tracker to avoid opening a duplicate issue 

Now I wonder if the checkoxes useless in the end.

**Comment by uBlock-user** [comment]
> Now I wonder if the checkoxes are useless in the end

Everyone who has opened issues here is literally just hitting all ticks, making them abusable.

**Comment by jmauss** [comment]
Hey guys, my apologies, that one is on me. Reading your replies I realized I only checked the main tracker for uBlock, not on this one here. I’ve never used two separate areas for issues before, and like I said it’s on me for not paying closer attention.

**Comment by gorhill** [comment]
> I only checked the main tracker for uBlock, not on this one here.

I see, now I can make sense of why.
