### ISSUE TITLE
cname uncloaking fails on hostnames with port

### ISSUE THREAD

**Issue by 95440b97d** [uBlockOrigin/uBlock-issues#1001]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The cname uncloaking feature fails on hostnames with port designation.  It appears to be an issue with the regex **reHostnameFromNetworkURL** in the file **vapi-common.js** which lacks an expression for an optional port.

The problem goes away if reHostnameFromNetworkURL is set to:
  
> /^(?:http|ws|ftp)s?:\/\/([0-9a-z_][0-9a-z._-]*[0-9a-z])(?::\d+)?\//

Which includes an optional port expression.

### A specific URL where the issue occurs

I don't have a public URL at hand.  I found this problem while investigating cname tracking in a private test environment with a web server running on non-standard ports.

### Expected behavior:

cname uncloaking should work for hostnames that include a port designation.

### Actual behavior:

cname uncloaking fails for hostnames that include a port designation.

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: Firefox 75.0
* Operating System and version: ArchLinux (fully updated)

**Comment by gorhill** [comment]
> I don't have a public URL at hand. I found this problem while investigating cname tracking in a private test environment with a web server running on non-standard ports.

It's ok, I can confirm `/^(?:http|ws|ftp)s?:\/\/([0-9a-z_][0-9a-z._-]*[0-9a-z])\//` fails to match `http://www.example.org:8080/index` at <https://regex101.com/>.

**Comment by gorhill** [comment]
This will be fixed in next dev build, thanks for reporting.
