### ISSUE TITLE
Overview panel is zoomed in; not possible for me to zoom out

### ISSUE THREAD

**Issue by wallachianwarrior1918** [uBlockOrigin/uBlock-issues#1002]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock origin overview panel is zoomed in too much. Basically, if i open it i need to scroll down to see the actual domains. 

### A specific URL where the issue occurs

any url

### Steps to Reproduce

1. Open overview panel
2. Everything is zoomed in (i attached a screenshot)

### Expected behavior:
Ublock would show an overview with all the domains visible (or at least a part of them) like in the official screenshots

### Actual behavior:
Only 2-3 domains shown

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: Firefox v75
* Operating System and version: Fedora 32

![Captură de ecran de la 2020-04-29 11-17-07](https://user-images.githubusercontent.com/64523773/80574755-16cc9100-8a0b-11ea-9b2f-537c2a5b897f.png)

**Comment by gwarser** [comment]
You are aware this is how it looks when advanced mode is enabled?

Something is wrong with cells height though.

**Comment by uBlock-user** [comment]
It's not zoomed in, it's expanded.

**Comment by wallachianwarrior1918** [comment]
Yes, I know this is how it's supposed to look when advanced mode is enabled.

Cell height is what I was referring to.

**Comment by gorhill** [comment]
I can't reproduce.

Please follow these steps:
- When the popup panel is opened, press shift-ctrl and click the "all" cell in the firewall pane
    - This will cause the popup panel to open in its own tab
- Right-click the "images" cell and select "Inspect Element..."

Post a screenshot of the "Developer Tools" when the "images" cell is selected, as follow (I must be able to see all that I can see in the screenshot above):

![a](https://user-images.githubusercontent.com/585534/80588926-3baf0d00-89e7-11ea-9161-7a2f50dbb4a7.png)

**Comment by gorhill** [comment]
By the way, compared to my display, everything is bigger in your screenshot, so it appears this could be a OS setting causing this.

**Comment by wallachianwarrior1918** [comment]
I did as you suggested. Indeed I changed the layout.css.devPixelsPerPx to 1.25, but this isn't the cause. I tried deactivating it and everything scales down, but the extra empty space in the cell still persists. 

![Captură de ecran de la 2020-04-29 16-23-03](https://user-images.githubusercontent.com/64523773/80601140-1695bb00-8a36-11ea-80c9-00de89a060f2.png)

**Comment by gorhill** [comment]
> Indeed I changed the `layout.css.devPixelsPerPx` to 1.25

You checked _"using a new, unmodified browser profile"_ in your issue description. Should I understand that you actually didn't try to reproduce the issue in a new, unmodified profile?

**Comment by gorhill** [comment]
When I compare my screenshot to yours, it's not just uBO having higher line height on your side, the whole Firefox UI shows higher line height than what I get on my side.

**Comment by wallachianwarrior1918** [comment]
I did create a new profile. Anyway, I did it again. Here is a screenshot from that profile:

![Captură de ecran de la 2020-04-29 17-16-13](https://user-images.githubusercontent.com/64523773/80606874-76439480-8a3d-11ea-9018-1d39376372e3.png)

uBlock Origin didn't have this problem ever since installing it. This only appeared for some reason today.

**Comment by gorhill** [comment]
Unable to reproduce, someone else who can reproduce will have to investigate the cause.

**Comment by uBlock-user** [comment]
> using Linux

Which flavour ?

**Comment by wallachianwarrior1918** [comment]
Fedora 31 originally, now 32. I mentioned in the first comment

**Comment by gwarser** [comment]
Firefox 76 was updated recently (just now for me), maybe one of these changes is interfering on your system:
```

#1626382
#1629839 [Core:Audio/Video: cubeb]-Crash in [@ cubeb_coreaudio::backend::buffer_manager::BufferManager::push_silent_data] [mac]
#1495900 [Core:Graphics: Text]-starting Chrome makes Firefox content processes hang for about two minutes, due to FontConfig font rescanning (FcInitReinitialize) [Lin]
#1631729 [Firefox:about:logins]-The text from the Breach Website/Vulnerable password notification has a thin font-weight [All]
#1630506 [Firefox:Address Bar]-Reduce the address bar's drop shadow when it's focused but not open [All]
#1631241 [Firefox:Search]-Engines are in wrong order after restart [Uns]
#1629826 [Firefox:Security]-Re-enable probe for certificate error pages [Uns]
```

http://forums.mozillazine.org/viewtopic.php?f=23&t=3061371 (scroll to "Beta 8 -> RC 1 Changelog +7")

**Comment by wallachianwarrior1918** [comment]
No, I'm actually on firefox 75 (latest stable). For some reason I confused the version. Sorry.

I also tested it on a windows machine (firefox v75), and can't reproduce it there.

**Comment by gorhill** [comment]
Thoughts: is Firefox installed from your OS distribution? If so, the issue could be that they configured it in a way which cause the issue.

Note that `line-height` is [currently explicitly set to `1.4`](https://github.com/gorhill/uBlock/blob/647c248f154ff4185be432d88d74a75262f97300/src/css/popup.css#L240), which was [not the case in the last stable release](https://github.com/gorhill/uBlock/blob/c12f2c07ea6c6c83a19a295c6156a88e017ff152/src/css/popup.css#L241) -- I can't remember when I changed this -- so the latest dev build might make this issue resolved.

**Comment by gwarser** [comment]
In "Sixth pass" https://github.com/gorhill/uBlock/commit/e917213e81d40b00cefd7f493fcbabb450ccb10d

**Comment by wallachianwarrior1918** [comment]
Yes, it's from Fedora's repos. Although no update was done to Firefox, unless something happened when upgrading to F32 from F31.

**Comment by gorhill** [comment]
@wallachianwarrior1918 Since you are the only one reporting such issue, you are best placed to investigate it. The browser contains all the tool to find out why the line height of cell is higher on your side than what it is everywhere else.

Keeping this issue open is pointless since there is nothing anybody else can do since it's not reproducible except by you. Re-open when you have identify the cause and that the actual issue is definitely in uBO.
