### ISSUE TITLE
HOSTS file filtering also blocking subdomains

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uBlock-issues#1003]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A bug or a feature...I hope I won't become fooled (aka [rick'rolled](https://www.youtube.com/watch?v=dQw4w9WgXcQ) / [rickrolling](https://en.wikipedia.org/wiki/Rickrolling)) again by uBO's feature or [description of hosts file in uBO](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files) , but most likely it's a bug, as there was already a similar bug that was reported and repaired: https://github.com/gorhill/uBlock/issues/1468. As far I know hosts file entries should not block neither ccTLD nor subdomains as well. I checked it myself by adding `127.0.0.1 wp.pl` to my Windows's hosts file, restarted browser, and couldn't visit `wp.pl` while I still could visit `poczta.wp.pl`, also see [here](https://superuser.com/questions/85449/hosts-file-and-unblocked-subdomains). Apart from subdomains being blocked itself, blocked subdomains may lead to higher level domains breakages as well. I have a small army of `$badfilter` lines in uBO to unbreak all websites broken by hosts lists I use in uBO, wonder how many of websites are broken/inaccessible due to the bug, and not due to hosts lists's false hits.  Also from [uBO's wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files): " the interpretation must be "block network requests to the site `example.com`" " - so `xxx.example.com` site should not be blocked.

### A specific URL where the issue occurs

Example: `https://poczta.wp.pl/`

### Steps to Reproduce

1 Add example rule `wp.pl` or `127.0.0.1 wp.pl` to uBO's My filters pane and save it
2 Visit `wp.pl` (can not visit) and then `poczta.wp.pl` (can not visit)
3 uBO saying `poczta.wp.pl` is blocked by `||wp.pl^`

### Expected behavior:

The example rule `wp.pl` or `127.0.0.1 wp.pl` should not block subdomains

### Actual behavior:

The example rule `wp.pl` or `127.0.0.1 wp.pl` blocks subdomains

### Your environment

* uBlock Origin version: 1.26.3b13
* Browser Name and version: Firefox 75 64bit / Opera 68 64bit
* Operating System and version: Windows 7 SP1 64bit

**Comment by gorhill** [comment]
By design, uBO can load the hosts file and create filters from it, but as opposed to how the OS handles hosts files, uBO propagates the block rule to subdomains.

**Comment by kulfoon** [comment]
Oh, omg, lol, so I've been fooled / confused / [rick'rooled](https://www.youtube.com/watch?v=dQw4w9WgXcQ) again, like [here](https://github.com/easylist/easylistgermany/issues/70#issuecomment-619544549), also I have been fooled [here](https://github.com/abp-filters/abp-filters-anti-cv/issues/378) as well, so I got rick-rooled already 3 times in a few days, by various descriptions, it's so funny.

The [uBO's wiki about the hosts feature](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files) lacks information about such feature being an intended, different than real hosts, behaviour, what may be confusing / misleading that there is a bug in uBO... perhaps such info about that it's intended behaviour, does exist somewhere deep in some uBO's release / commit description or somewhere else, I wonder how much and deep one must read and investigate to get real and proper info about some feature, this is just funny.

Btw. may I ask why uBO propagates the block rule to subdomains? As uBO changes default hosts file behaviour it may lead websites inaccessibility / breakages.

**Comment by gorhill** [comment]
The documentation was updated to make this clear.

> may I ask why uBO propagates the block rule to subdomains

That's the way I decided it would work 6-7 years ago.

**Comment by kulfoon** [comment]
### [1] █████████████████████████████████████████████████

> gorhill : That's the way I decided it would work 6-7 years ago.

So old ago, that despite looking deeply, there is nothing in both old uBO repo nor in the current uBO repo about uBO's HOSTS support implementation, neither in ISSUES's titles, nor in RELEASES's descriptions nor in COMMITS's descriptions, the only info is in the WIKI.

> gorhill: The documentation was updated to make this clear.

It's much better, but it still may be confusing / rickrolling, coz there is not clearly mentioned about difference between uBO's HOSTS syntax and the real HOSTS file syntax, one must still know the both and then deduce/notice the difference himself, and:
1) if the one doesn't know the real HOSTS file syntax, might end up thinking the both implementations are equal
2) and even if the one knows the real HOSTS file syntax, still might simply overlook the difference, and still end up thinking the both implementations are equal
3) and if the one will notice the difference, still might end up thinking it's a bug and not an intended implementation difference, unless he notice and read the current thread on the issue tracker

Hence, it would be good to add another sentence like:

> Also, this creates another ambiguity with HOSTS file syntax as well, which given a host `example.com`, will block `example.com` only, unlike uBO's implementation, which will block `example.com` and all it's subdomains.

### [2] █████████████████████████████████████████████████

Looking at such comments:

> kulfoon : https://github.com/uBlockOrigin/uBlock-issues/issues/1003#issue-609019606 : I have a small army of `$badfilter` lines in uBO to unbreak all websites broken by hosts lists I use in uBO, wonder how many of websites are broken/inaccessible due to the bug, and not due to hosts lists's false hits.

> kulfoon : https://github.com/uBlockOrigin/uBlock-issues/issues/1003#issuecomment-621210677 : Btw. may I ask why uBO propagates the block rule to subdomains? As uBO changes default hosts file behaviour it may lead to websites inaccessibility / breakages, not intended by the real hosts filter lists. 

> @DandelionSprout : https://github.com/uBlockOrigin/uBlock-issues/issues/984#issuecomment-612095871 : Especially so since I've been advocating behind closed doors on Slack for the removal of DNS-BH Malware Domains for having too many false positives 

> @Yuki2718 : https://github.com/uBlockOrigin/uBlock-issues/issues/984#issuecomment-621264385 : Why include MDL, it should rather be excluded. We need to find at least one high-quality list. As noted, all the lists (except osint, too short; didn't test) mentioned here included some false positives and thus combining them will increase the rate of FPs.

I'm curious whether any of these breakages/false hits are due to uBO's different implementation, and not due to the HOSTS list itself, and if there are any, how many of them, as for now I conducted no investigation, but assuming there are some, people might end up unconsciously blaming HOSTS list for all breakages/false hits, by what, they might break HOSTS lists's reputation.
