### ISSUE TITLE
Randomly gets corrupted on Chrome

### ISSUE THREAD

**Issue by reflectively** [uBlockOrigin/uBlock-issues#1006]
- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After a random amount of time (usually within 20 minutes) the ublock origin extension stops gets corrupted and disappears from chrome toolbar. I already reset the extension to default settings.

### A specific URL where the issue occurs

the corruption doesn't seem to be connected to any specific URL

### Steps to Reproduce

hard te reproduce, because there is no warning or notification. I usually notice the extension got corrupted when ads suddenly reappear.

### Expected behavior:

supposed to run on constant basis

### Actual behavior:

gets corrupted. Under extensions error message appears: This extension may have been corrupted. After clicking repair button it works again. 

### Your environment

* uBlock Origin version: v1.26.0
* Browser Name and version: Chrome Version 81.0.4044.129
* Operating System and version: MacOS Catalina 10.15.3

**Comment by uBlock-user** [comment]
Are you running any AV software ?

**Comment by reflectively** [comment]
No.

**Comment by gorhill** [comment]
uBo does not have access to the file system, so if uBO's package gets corrupted, something on your system is causing this.
