### ISSUE TITLE
Add new filtering category to the Logger: popups

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1007]
**### Prerequisites**

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

**### Description**

Hi, can you add a new filtering category to the Logger that would filter popups?

**Comment by gwarser** [comment]
You can always type `|popup` in filtering input box. https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#filtering-the-logger-output

Do you see popups so often that shortcut is needed?

**Comment by gorhill** [comment]
There is also `other` as a filter option.

**Comment by peace2000** [comment]
@gwarser Not necessarily, but I thought there is no reason not to have it.

@gorhill Ok, thanks. Great.
