### ISSUE TITLE
Restore/Reset settings do not work on Yandex for Android

### ISSUE THREAD

**Issue by zhang250662772** [uBlockOrigin/uBlock-issues#1009]
yandex手机版本uBlock Origin development build v1.26.3b19可以备份设置，但是无法从从备份还原，重置为默认设置也无法使用
![Y9YJMQ.gif](https://s1.ax1x.com/2020/05/04/Y9YJMQ.gif)

**Comment by llacb47** [comment]
Translated:
```
The mobile phone version of yandex, ublock origin development build v1.26.3b19, can back up settings, but cannot be restored from backup, and cannot be reset to the default settings
```

**Comment by gwarser** [comment]
Yandex browser issue? Works fine in Fennec.

**Comment by gwarser** [comment]
I cannot save in Fenix, can someone confirm this? Restoring and resetting seems to work.

**Comment by gorhill** [comment]
> I cannot save in Fenix

It's a known issue in Fenix: <https://bugzilla.mozilla.org/show_bug.cgi?id=1626349>.

> @zhang250662772

Did this ever worked? If so, in earliest version did it stop working?

Somebody will have to investigate and find the cause of this. The restore and reset features share similarities, they both delete all storages and restart the extension, so it should be assumed that whatever break restore is also what break reset. Reset is quite simple, so somebody needs to narrow down which of [those calls](https://github.com/gorhill/uBlock/blob/f9cb23d3dff60f13d93e32564fa49d535533056e/src/js/messaging.js#L954-L963) fails.

**Comment by CrytoMiner2020** [comment]
> yandex手机版本uBlock Origin d

**Comment by zhang250662772** [comment]
> > I cannot save in Fenix
> 
> It's a known issue in Fenix: https://bugzilla.mozilla.org/show_bug.cgi?id=1626349.
> 
> > @zhang250662772
> 
> Did this ever work? If so, in which earliest version did it stop working?
> 
> Somebody will have to investigate and find the cause of this. The restore and reset features share similarities, they both delete all storages and restart the extension, so it should be assumed that whatever break restore is also what break reset. Reset is quite simple, so somebody needs to narrow down which of [those calls](https://github.com/gorhill/uBlock/blob/f9cb23d3dff60f13d93e32564fa49d535533056e/src/js/messaging.js#L954-L963) fails and what would be the fix.

From Google store uBlock Origin development build v1.26.3b16

**Comment by zhang250662772** [comment]
> Yandex browser issue? Works fine in Fennec.

There's a problem with yandex and kiwi

**Comment by gorhill** [comment]
> From Google store uBlock Origin development build v1.26.3b16

So if I get this correctly, the restore/reset features work fine with uBO 1.26.3b16, installed from the Google Chrome store. However the Google Chrome store [currently serves uBO 1.26.3b18](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).

You report that It does not work correctly with uBO 1.26.3b19. You installed uBO 1.26.3b19 from where? How did you install this version?

**Comment by zhang250662772** [comment]
> > From Google store uBlock Origin development build v1.26.3b16
> 
> So if I get this correctly, the restore/reset features work fine with uBO 1.26.3b16, installed from the Google Chrome store. However the Google Chrome store [currently serves uBO 1.26.3b18](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).
> 
> You report that It does not work correctly with uBO 1.26.3b19. You installed uBO 1.26.3b19 from where? How did you install this version?

chrome://extensions
![Screenshot_20200505_064054](https://user-images.githubusercontent.com/64761918/81020457-70194200-8e9b-11ea-85e4-ff4d531b2a6c.jpg)

**Comment by zhang250662772** [comment]
> > > From Google store uBlock Origin development build v1.26.3b16
> > 
> > 
> > So if I get this correctly, the restore/reset features work fine with uBO 1.26.3b16, installed from the Google Chrome store. However the Google Chrome store [currently serves uBO 1.26.3b18](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).
> > You report that It does not work correctly with uBO 1.26.3b19. You installed uBO 1.26.3b19 from where? How did you install this version?
> 
> chrome://extensions
> ![Screenshot_20200505_064054](https://user-images.githubusercontent.com/64761918/81020457-70194200-8e9b-11ea-85e4-ff4d531b2a6c.jpg)

![Screenshot_20200505_071128_com yandex browser beta](https://user-images.githubusercontent.com/64761918/81022272-cab49d00-8e9f-11ea-8f79-89c26f79c674.jpg)

**Comment by gorhill** [comment]
[1.26.3b20 is now available in the Chrome Web Store](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii). If you install it from there, do you still suffer the same issues?

**Comment by zhang250662772** [comment]
> [1.26.3b20 is now available in the Chrome Web Store](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii). If you install it from there, do you still suffer the same issues?

yes
![Video_20200509_053125_759](https://user-images.githubusercontent.com/64761918/81451195-833b5300-91b6-11ea-997b-1287b6d5eb96.gif)
