### ISSUE TITLE
can't update  1.26.3b18 to  1.26.3b19 or other older to newer builds

### ISSUE THREAD

**Issue by oeituw** [uBlockOrigin/uBlock-issues#1010]
New Firefox 77 profile
w10 64bit
and
ESR 68 Firefox mobile

install  1.26.3b18 

set it up

close open Firefox

open addon mangaer and update

 1.26.3b19 is updated
but not installed
close reopen Firefox
same  1.26.3b18 

manually install  1.26.3b19 from github
after asking for permissions and install
open addon manager
still  1.26.3b18 

close reopen Firefox
Again
manually install  1.26.3b19 from github
after asking for permissions and install
open addon manager
still  1.26.3b18 

@gorhill 
any help why so on different system?
sorry for bad language

**Comment by uBlock-user** [comment]
Setting `extensionUpdateForceReload` to `true` help anyway ?

**Comment by gwarser** [comment]
Something is broken in in Fennec. Even with `extensionUpdateForceReload` browser shows restart prompt.

**Comment by gorhill** [comment]
Try disable uBO, update to b19, quit Firefox, enable uBO. It's not a uBO issue, beyond this there is nothing I can do to change this.

**Comment by oeituw** [comment]
> 
> 
> Setting `extensionUpdateForceReload` to `true` help anyway ?

Yes thankyou it works now

> 
> 
> Something is broken in in Fennec. Even with `extensionUpdateForceReload` browser shows restart prompt.

Same but with above settings it's updating now


> 
> 
> Try disable uBO, update to b19, quit Firefox, enable uBO. It's not a uBO issue, beyond this there is nothing I can do to change this.
> 
> We should not tell people to change an advanced setting, there are consequences to do so and they should make that choice on their own independently of the reported issue.

can uBo do this automatically during updating?

**Comment by gorhill** [comment]
> can uBo do this automatically during updating?

No, the browser handles updating uBO, uBO cannot disable itself, only you or the browser can do this.

>  Yes thankyou it works now but it should update normally?

The description of your issue does not match advising to change `extensionUpdateForceReload` -- by design uBO defers the update to the next time it restarts, through add-ons manager or through quitting/restarting the browser. You said uBO was still not updated after restarting the browser.

**Comment by oeituw** [comment]
> 
> 
> > Setting `extensionUpdateForceReload` to `true` help anyway ?
> 
> @uBlock-user Yes thankyou it works now but it should update normally?
> 
> > Something is broken in in Fennec. Even with `extensionUpdateForceReload` browser shows restart prompt.
> 
> @gwarser Same but with above settings it's updating now so can use the new version atleast
> 
> > Try disable uBO, update to b19, quit Firefox, enable uBO. It's not a uBO issue, beyond this there is nothing I can do to change this.
> > We should not tell people to change an advanced setting, there are consequences to do so and they should make that choice on their own independently of the reported issue.
> 
> can uBo do this automatically during updating?
> 
> Disabling and enabling is not possible unless checking for updated manually
> Firefox addon manager auto update is useless then and have to visit github page to see new builds and update after disabling and restarting and enabling
> 
> sorry bad language



> 
> 
> > can uBo do this automatically during updating?
> 
> No, the browser handles updating uBO, uBO cannot disable itself, only you or the browser can do this.

Any setting to change this?
Not updating that's why reported
> 
> > Yes thankyou it works now but it should update normally?
> 
> The description of your issue does not match advising to change `extensionUpdateForceReload` -- by design uBO defers the update to the next time it restarts, through add-ons manager or through quitting/restarting the browser. You said uBO was still not updated after restarting the browser.

@gorhill  yes uBO was not updating on mac/android even after restart
try it on android version 68 stable one

@uBlock-user setting made it work on mobile
will check on mac later and reply

**Comment by gorhill** [comment]
> android version 68 stable one easy to show there evertime

Yes, I had such issue with older versions of Firefox, and the steps I described is how I fixed this on my side -- but I even had times where even after restarting uBO was still showing older versions -- this was a Firefox quirks.

I haven't seen this happens in recent versions of Firefox, updating uBO has become reliable, taking into account that uBO purposefully defers executing the new version to avoid loss of data.

This Firefox issue <https://bugzilla.mozilla.org/show_bug.cgi?id=1627495> will make things better when it comes to forcing an update of uBO.

**Comment by oeituw** [comment]
> > android version 68 stable one easy to show there evertime
> 
> Yes, I had such issues with older versions of Firefox, and the steps I described is how I fixed this on my side -- but I even had rarer instances where even after restarting uBO was still showing older versions -- I consider this was a Firefox quirk.
> 
> I haven't seen this happens in recent versions of Firefox, updating uBO has become reliable, taking into account that uBO purposefully defers executing the new version to avoid loss of data.
> 
> This Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=1627495 will make things better when it comes to forcing an update of uBO.

But facing this issue for quite a while especially on andoid 68
And on win/mac think 76 maybe

can you please try on android once

so should use @uBlock-user  settings or so no fix ?

**Comment by gorhill** [comment]
By the description of your issue, `extensionUpdateForceReload` is irrelevant.

As said I have seen the behavior you described on older version of Firefox. I do not see it anymore on recent versions of Firefox. Is it possible that you confused the by-design behavior on recent versions of Firefox with the browser glitch on older versions of Firefox? If you suffer the same issue on recent versions of Firefox, i.e. uBO not updating after a restart, then you will have to file an issue with Firefox.

**Comment by oeituw** [comment]
> 
> 
> By the description of your issue, `extensionUpdateForceReload` is irrelevant.
> 

But it fixes the issue

> As said I have seen the behavior you described on older versions of Firefox. I do not see it anymore on recent versions of Firefox. Is it possible that you confused the by-design behavior on recent versions of Firefox with the browser glitch on older versions of Firefox? If you suffer the same issue on recent versions of Firefox, i.e. uBO not updating after a restart, then you will have to file an issue with Firefox.

Yes this problem happens evetime on recent versions i.e. uBO not updating after a restart

not know how to file issue in Firefox.

**Comment by gorhill** [comment]
> But it fixes the issue

- Firefox stable 75.0
- `extensionUpdateForceReload` set to `false` (default value)
- uBO 1.26.3b18 installed

When I click "Check for Updates..." in the gear icon in `about:addons`, the browser shows that there is an update available for uBO -- there is a blue dot on uBO's three-dot icon.

When I ask uBO to be updated through the "Update" entry in the three-dot menu of uBO, the browser updates uBO. At this point uBO is still 1.26.3b18 (expected). When I quit and restart the browser, uBO is 1.26.3b19 (expected). So all is working as expected on my side.

**Comment by uBlock-user** [comment]
The setting I mentioned is a workaround for your situation in Firefox 77, the issue hasn't gone away(if it exists).

**Comment by oeituw** [comment]
> 
> 
> The setting I mentioned is a workaround for your situation in Firefox 77, the issue hasn't gone away(if it exists).

it's  there but don't have the way to prove it

@uBlock-user  Can you help?
Just install the stable android one 68.7 
https://play.google.com/store/apps/details?id=org.mozilla.firefox
and try updating uBo from b18 to b19 in a new profile
please just check before closing
you may know whats going on which missed by me

**Comment by gorhill** [comment]
> can you too try please the above

I regularly (every new dev build) update to latest version of uBO dev build on Firefox for Android (which is essentially 68 ESR) for testing purpose and I have no issue of uBO being stuck to an earlier version. I click the latest xpi in the release section, quit Firefox, launch Firefox and uBO has been properly updated.

**Comment by oeituw** [comment]
> 
> 
> > can you too try please the above
> 
> I regularly (every new dev build) update to latest version of uBO dev build on Firefox for Android (which is essentially 68 ESR) for testing purpose and I have no issue of uBO being stuck to an earlier version. I click the latest xpi in the [Releases section](https://github.com/gorhill/uBlock/releases), quit Firefox, launch Firefox and uBO has been properly updated.

Can you provide the method you use to restart firefox in android?
after updating the extension

One last request
Please update the legacy version with the recent changes(updated filters list and cdn and all)
PM/Basilisk are far better and would love to use UbOlegacy with the new updates
Thank you MR @gorhill

**Comment by gwarser** [comment]
Does not update if I swipe Firefox from applications menu, but this is more like "kill". Works if I use "Quit" which must be enabled in settings. And weird thing - I see restart prompt when downgrading .20->.19.

`extensionUpdateForceReload` is `false`.

**Comment by gorhill** [comment]
> Can you provide the method you use to restart firefox in android?

I just tap the Firefox for Android icon in the "desktop" screen (not sure how it's called).

> PM/Basilisk are far better

I disagree.

If you want uBO legacy to catch up to actual uBO, you will have to find volunteers ready to invest their free time in doing so. Probably the optimal approach would be to create a [WebExtensions layer](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) which modern uBO expect.

Legacy Firefox did not have solid, reliable extension APIs, it was just a collection of hooks into the browser itself, subject to constant changes, and it's messy and is what was holding back Firefox from improving thoroughly.

**Comment by oeituw** [comment]
> 
> 
> > Can you provide the method you use to restart firefox in android?
> 
> I just tap the Firefox for Android icon in the "desktop" screen (not sure how it's called).
> 

Open firefox
update extension
press middle button
clear recents- remove firefox
open firefox
addons
uBo

doing this but still doesn't update
only that advance pref or uninstall/reinstall helps

**Comment by gorhill** [comment]
> clear recents- remove firefox

Only explanation I can see is that this does not quit Firefox on your side.

> Also regarding PM/Basilisk it's apis are matured/fixed

Please provide link(s) to documentation supporting "apis are matured/fixed", I want to develop my own understanding of what is behind that statement.

**Comment by gorhill** [comment]
So 1.26.3rc0 is now published, I repeated the test again on Firefox for Android 68.7.0:

- Launch Firefox for Android
- Go to <https://github.com/gorhill/uBlock/releases>
- Tap `uBlock0_1.26.3rc0.firefox.signed.xpi`
- Firefox asks to either deny or allow
- Tap to allow
- Firefox downloads the package and asks to either dismiss or add
- Tap to add
- Quit Firefox
    - I swipe to the right the Firefox for Android after I tap the square at the bottom of the phone
- Launch Firefox
- Load a web page
- Bring up uBO's popup panel
- Reveal the version information in the popup panel

Result: 1.26.3rc0

Just to further confirm I can't reproduce the issue.

**Comment by llacb47** [comment]
OP deleted their GitHub account.

**Comment by gwarser** [comment]
Interesting - this time it worked fine. (except endless loading of releases page after restart, but I closed it and everything seems to be ok).

One thing I do in different way - I always swipe to the left:

>I swipe to the right the Firefox...

Will try again later.

**Comment by gwarser** [comment]
I tried around 10 times today and it failed only once. I think it's because I did this with patience - slow. My phone is very old and needs time to even close Firefox.
