### ISSUE TITLE
Strict blocked URL's hash fragment isn't parsed

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uBlock-issues#1014]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As described in `https://github.com/gorhill/uBlock/wiki/Strict-blocking#ability-to-parse-the-strict-blocked-url`, uBo offers the ability to parse the strict-blocked URL and display the query parameters. However, if the site is storing the parameters in a hash fragment, uBo doesn't parse it as a query string.

### A specific URL where the issue occurs

`https://www.greensboro.com/news/local_news/friday-covid-19-update-n-c-cases-approach-14-000-guilford-records-its-38th-death/article_44c3cb73-21f6-55b6-b0c6-c982b74191cc.html#utm_campaign=blox&utm_source=twitter&utm_medium=social` 

(follow `Steps to Reproduce`)

### Steps to Reproduce

1.  Add `&utm_*=$document,important` to `My filters`
2. Visit `https://twitter.com/NewsandRecord/status/1258796827991781378`
3. Click the link
4. Page is strict-blocked but information about the parameters located in the hash fragment is not displayed

### Expected behavior:

Information about the parameters located in the hash fragment is displayed, and the URL `without parameters` can be clicked on.

### Actual behavior:

Information about the parameters located in the hash fragment is not displayed

### Your environment

* uBlock Origin version: 1.26.0
* Browser Name and version: Google Chrome 81.0.4044.138
* Operating System and version: Windows 10 OS Version 1909

**Comment by gorhill** [comment]
The `hash` is not meant to be parse, it can be anything the server wants it to be.

If anything, it's a server-side code issue, which mistakenly appended what was meant to be a query string as a hash string.

**Comment by llacb47** [comment]
https://stackoverflow.com/questions/15238391/hash-params-vs-url-params-when-to-use-which/15400574

The site is probably checking `location.hash` and sending that data to google tag manager etc.

**Comment by gorhill** [comment]
Yes, it looks like it's on purpose, there is inline javascript in the page doing something like that.

I could enable the magnifier when there is a hash part and provide a version of the URL without the hash part.
