### ISSUE TITLE
Popup interface unusable with Firefox on Wayland

### ISSUE THREAD

**Issue by glitsj16** [uBlockOrigin/uBlock-issues#1015]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

uBO's popup interface fails to show properly when running Firefox on Wayland via MOZ_ENABLE_WAYLAND=1 (uMatrix works fine on Wayland for BTW). The whole popup looks like it has the background color only, nothing else can be seen. This is the case for both basic and advanced-user mode. On Xwayland the popup interface shows and works just fine. Is this a known issue? Can this be overcome somehow (while on Wayland, I prefer not to run FF on X11)?

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Start Firefox with MOZ_ENABLE_WAYLAND=1 in a Wayland desktop session (e.g. GNOME or Sway).
2. [Second Step]
Click the uBO toolbar button to open the popup interface.
3. [and so on...]

### Expected behavior:

[What you expected to happen]

Popup interface shows the firewall and the right-pane with info and stats.

### Actual behavior:

[What actually happened]

Popup opens, but is completely unreadable. Clicking becomes a hit & miss adventure.

### Your environment

* uBlock Origin version: 1.26.3.106
* Browser Name and version: Firefox 76.0.1
* Operating System and version: Arch Linx

**Comment by gorhill** [comment]
uBO is HTML/CSS/JS, if the HTML does not render properly, this is a browser issue.
