### ISSUE TITLE
Settings pages are broken 1.26.2 - Firefox 77.0b3 (64-bit)

### ISSUE THREAD

**Issue by eggsgent** [uBlockOrigin/uBlock-issues#1017]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ n] uBlock Origin is the only extension
    - [y ] uBlock Origin with default lists/settings
    - [y ] using a new, unmodified browser profile
- [y ] I am running the latest version of uBlock Origin
- [ y] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Settings pages are broken 1.26.2 - Firefox 77.0b3 (64-bit)

Cannot edit any Ublock any settings as of today, nothing changed in browser profile except getting beta updates from Firefox. Issue was first observed after playing back a Youtube video today and getting ads. This did not happen yesterday.

### A specific URL where the issue occurs

moz-extension://

### Steps to Reproduce

No clear steps how to reproduce as the issue does not occur with clean profile 

1. Reinstall extension
2. Open extension's settings page
3. Try changing settings and see if it works

### Expected behavior:

Able to interact with Settings, able to see my filters, able to save changes, able to import and export settings, and restore settings to default

### Actual behavior:

Import / export / restore settings buttons do not work. Some Settings check-boxes can be checked, but are not saved. 
Opening the Filter list tab, then tabbing from it straight away invokes the Not saved settings stay / ignore toolbar.
 

[What actually happened]

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: Firefox 77.0b3 (64-bit)
* Operating System and version: Win 10 Pro 1909

**Comment by uBlock-user** [comment]
https://firefox-storage-test.glitch.me/

Test there, post results here.

**Comment by eggsgent** [comment]
Thanks, I was about to close this issue as Firefox bug: "Storage is broken":

storage.estimate() threw: Internal error while estimating storage usage
Failed to create "persistent" IDB.
Failed to create "transient" IDB.

{
  "v": 1,
  "curVersion": 77,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 0
  },
  "idb": {
    "persistentCreatedIn": 0,
    "persistentLastOpenedIn": 0,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 0,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 0
  }

**Comment by uBlock-user** [comment]
Your storage is broken, that's why it works with clean profile.

**Comment by eggsgent** [comment]
d fsdf

> Your storage is broken, that's why it works with clean profile.

Do you know how to fix broken storage on Firefox?

**Comment by gwarser** [comment]
It depends what exactly is broken. Resetting/reinstalling extension may work. Cleaning browser history may work. Manually removing storage from Firefox profile will probably work, but there is also chance it will broke more. [Refreshing Firefox profile](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings), or [creating new one](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) will work for sure.
