### ISSUE TITLE
Block mode slider in the DASHBOARD

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1019]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
FEATURE REQUEST & USER INTERFACE ENHANCEMENT

A slider in the uBlockOrigin Dashboard which represents the uBlockOrigin mode's as explained in the Wiki  (https://github.com/gorhill/uBlock/wiki/Blocking-mode and https://github.com/gorhill/uBlock/wiki/Blocking-mode:-nightmare-mode) with the following six options

OFF - disable uBlockOrigin filtering (for all domains)
EASY - only the selected filterlists would apply
ENHANCED - selected filterlists would apply plus 3p-frame
MEDIUM - selected filterlists would apply plus 3p-frames and 3p-scripts blocked
HARD - selected filterlists would apply plus 3p-blocking
NIGHTMARE - selected filterlist with block all plus noop for current website

The benefit would be a quick way to change blocking modes and a more explicit visual feedback on the mode uBo is in. I know it can be done with the current user interface. Having a slider helps to promote the idea of applying those different modes more situational. 

The developer @gorhill  has explicitly mentioned these modes as different use cases, so it must have crossed his mind also that it would be a waist when such a flexible multi-purpose content blocker would only be is used in one or two modes.

**Comment by Kees1958** [comment]
@uBlock-user 

No response means this request is declined?

**Comment by gwarser** [comment]
No response means no response. 

BTW, I don't think it's something to be added. These "modes" are just propositions of usage - you can configure uBO in different ways. It's really easy to switch them - no need to even open Dashboard.

**Comment by gorhill** [comment]
> it must have crossed his mind

Yes, to make advanced mode features to be usable by less advanced users who do not want to waste time figuring rulesets has always been a preoccupation, and an easy way to toggle between documented mode has been on my mind since forever.

The relax blocking mode shortcut was a good addition toward that goal. The new redesigned popup panel is more open to adding additional widgets, but it's something that requires a lot of thoughts, I don't want to throw stuff in there that may prove to be a pain in the long run or make things more confusing for majority of users, there is such a thing as UI overloaded with too much options.

So I keep it open because I will keep thinking about how to make dynamic filtering easier to use.

**Comment by Kees1958** [comment]
@gorhill 

It would be nice to configure the blocking modes in a different manner, e.g. (just examples to correlate blocking modes to internet zones)

My bookmarked websites: very easy mode
All websites within a predifined set of TLD's (for me from Netherlands that would be: NL, COM, INF. NET, ORG) set to easy enhanced mode:
On all other websites uBO would automatically apply medium mode blocking

**Comment by Yuki2718** [comment]
I tend to agree with @gwarser , I'm almost sure that the slider won't be used by most user. The obstacle preventing people to use the advanced modes is not UI, but the initial training these modes require - I've seen numerous such claims on Wilders & MT (BTW, nice to see you here again, Kees). This is why I now share rules for the medium mode and I think something like uMatrix recipe will make much more sense, indeed there is a [need](https://www.reddit.com/r/uBlockOrigin/comments/d4w148/subscribe_to_public_lists_of_dynamic_filtering/).

**Comment by Kees1958** [comment]
Hi Yuki thanks,, but allow me to disagree.

I worked for James Martin Associates, the English IT-professor who wrote the Pulitzer Price nominated book the "Wired Society" in 1978 in which he outlined our world today, okay our current connected world is true air and not wires, but he was close.  I was a usability expert/user interface consultant in those days. Thanks to my son (he is webdesigner/UX-expert) I like to think my knowledge in this area is still relevant. 

I challenge you to add a slider (clearly visible) on any 'protection' program with a min to max scale and I guarantee you, it will be used. When a information box appears (e.g. below the slider) explaining the intended use, not the technology, more people will start to use it, e.g.  (max two lines explanations of a blocking mode):

very easy mode - for booking and banking, 
enhanced mode  - for websites you often visit for infotainment and socializing 
medium mode - for searching for deals & discounts & destinations
nightmare mode - for risky and dodgy browsing

**Comment by Yuki2718** [comment]
They may try the modes, and then almost all of them will give up soon. Remember, those security geeks who're supposedly above average in technical knowledge and well understand the benefits often give up ([the latest example](https://malwaretips.com/threads/what-browser-extensions-are-you-using-in-2020.100036/page-6#post-874884)) - UI changes doesn't free them up from the work to configure rules which is the biggest barrier. I'm not opposing - I don't care UI unless it's too crammed up. Rather I think a general discussion to encourage more people to use the modes and another discussion about this issue should be distinguished, and for the latter it sounds it will be even better if uBO can automatically revert back to easy mode (or any defined modes) for registered sites. All I know is average users are not willing to interact with programs on their browsing. But it will require quite codes to be added and I think it's not sth worth high priority.

**Comment by Kees1958** [comment]
@Yuki2718 

You gave an example, which shows that onze size fits all approach does not work (breaks to many sites), so that is a plus 1 for the contextual (slider and internet zones) approach.

The example you gave also shows that the poster found noscript easier to use than uBO. Noscript requires constant fiddling with websites (interacting during browsing). Would be interesting to contact these two users (southpark and ErzCrz) whether they use(d) noscript on demand.

When people like to use (just as example) ABP and Noscript and use the latter on demand, than the uBO should not be sold to public as ABP and Noscript, but ABP with on demand Noscript option. 

Only way to know is to contact some users and find out why they find Noscript easier to use.

**Comment by Yuki2718** [comment]
@Kees1958 Neither medium mode or NS requires constant and regular interaction at least too often, both of them require a hard work only at the first time - this is what a NS guru bo elam has been repeating and I fully agree to. I make changes on dynamic rules about 3 times a month on average, frankly I tend to find more false positives by static filters. If one feels NS is easier to use, it may be due to it doesn't distinguish 1st/3rd party and actually uBO can be used in such a way if he was not constrained by the idea of medium mode.

**Comment by gorhill** [comment]
NoScript can't possibly be easier to use than uBO's _"relax block mode"_, which can be already achieved through point-and-click: it's just a matter of noop-ing local 3rd-party cells.

There is no such ability in NoScript because there is no concept of local rules and there is no blocking mode to fall back onto when one relax the current blocking mode beside allowing too much everywhere.

The comment in the thread is the user failing to understand he could have simply noop-ed the 3rd-party frame cell in order to unbreak a site. How is this easier in NoScript?

**Comment by Yuki2718** [comment]
Yeah, and if even a member of security forum fails to understand what he should do, how average user could deal with medium mode - he may play with the slider but will have no idea about what to do for the breakage, then forget about it - or does he still keep medium mode and always slides to easy mode every time he encounters breakage which is at first quite common? This is why I said the two types of discussion should be distinguished.

**Comment by gorhill** [comment]
> how average user could deal with medium mode

To be clear, I do not intend to have a UI counterpart to _"Relax blocking mode"_ that is available to non-advanced users. I do think it's useful to have a UI counterpart to _"Relax block blocking"_ to advanced users, for various reasons:

- To make it even easier for novice users who want to give a try to dealing with default-deny approach
- To have a quick way to relax blocking mode on mobile devices where no shortcut can be used
- Assuming I go ahead with this, whatever the UI would be I can say it won't be slider, it has to be point-and-click

By default I assume uBO is used in majority by people who want an install-and-forger approach. This is why I was happy to be able to hide by default the per-site switches in the latest release, these switches were just clutter for such users -- I have such install-and-forget user in our household, and this gives me a good insight into what install-and-forget users expect.

**Comment by Kees1958** [comment]
I don't understand neither why people perceive Noscript easier to use than uBO, that is why I posted "Noscript requires constant fiddling with websites (interacting during browsing)".  

I also think that they don't understand that 3p applies to all the domains listed in the UI. It is a fact that grouping in interfaces (e.g. 1 to multiple relation) are hard to understand for people not in IT (who are used to normalizing data for relational databases) or math (or have a profession where math is required). Even though it is more work enabling third-party references one-by-one in Noscript it is easier to understands (hence percieved easier to use).

People are using uBO because other people say it is the best. This does not mean that they use it to the max. In North America nearly all cars have automatics transmission. This means that in 99% of the time only 30% of the horsepower is used (automat gears up at low revs for higher fuel economy). Still people like to own 5.7 liter pickup truck with lots of horse power (which they don't use 99% of the time).

That is why I said it is interesting to know whether those people use NoScript on demand. When that is true, the UI design of uBlock for non-advanced users might be more efficient to put in easy mode and facilitate medium level blocking on ad hoc basis for individual websites. 

So even my proposed internet zones would be to advanced when this is the prefered use case of non-advanced Noscript users.

**Comment by Yuki2718** [comment]
I had been a NS user before Https Switchboard came, and from that perspective it MAY be easier for those who don't understand 3p/1p distinction. If you allowed googleapis.com on NS it will be always allowed regardless of its origin or its type (script etc.). But it's obviously is looser, and I think it can't match the benefit of allowing 3p img/css by default. Anyway as now gorhill said this is more for advanced user, I have no reason to oppose - though I'm curious whether automatic fallback is harder to implement than point-and-click, or if it's possible to combine them i.e. "make this fallback permanent" checkbox.

**Comment by Kees1958** [comment]
Just checking (@gorhill @Yuki2718 ) is the conclusion of this request that

slider idea is rejected and normal mode (non-advanced) user interface could be improvement by adding a point and click option to apply medium mode (3p-scripts and 3p-frames blocking) for the current website?

**Comment by gorhill** [comment]
Why close it?

The idea is still a valid one even if it requires that a user opt-in to _"I am an advanced user"_.

**Comment by Kees1958** [comment]
:-) I guess it was the (old) desire as an IT-er to close down issues?

**Comment by Kees1958** [comment]
![image](https://user-images.githubusercontent.com/30925856/107382909-b8335800-6af0-11eb-9409-2c7f94765521.png)

**Comment by Kees1958** [comment]
@uBlock-user 

I totally forgot I had entered idea before. Apologize for bumping it up again.

**Comment by Kees1958** [comment]
How do I re-open this issue?

**Comment by LennyFox** [comment]
I only found out by reading that Wiki that it is possible with one click to reduce the protection one step at a time (https://malwaretips.com/threads/ublock0rigin-in-medium-mode-for-lighter-and-stronger-protection-with-less-websites-breakage-and-hassle.93311/page-6#post-951112)

But be honest, how many people do RTFM? I think the slider as proposed looks better and is more inviting to use it

**Comment by garry-ut99** [comment]
Worth to mention that the idea of slider is implemented in uBlock Lite (in both: popup UI & dashboard):
- https://github.com/uBlockOrigin/uBOL-home?tab=readme-ov-file#description
- https://chromewebstore.google.com/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh
