### ISSUE TITLE
cosmetic rules Not Logged for embedded YouTube videos

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#102]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Cosmetic rules for embedded YouTube videos are not logged. They're properly applied by uBO but not logged. (Also note that request filtering is properly logged, only cosmetics are missing.)

I recently switched from legacy uBO to WebExt, and this was not an issue on legacy. (I have a number of my own Youtube cosmetic rules and was accustomed to seeing them appear as a cluster in the logger for embedded videos.)

### A specific URL where the issue occurs

`https://developers.google.com/youtube/youtube_player_demo`

### Steps to Reproduce

1. add `youtube.com##.ytp-pause-overlay` and open the logger
2. open the link, play the video, then pause it. No "More videos" overlay should appear because it's hidden by the rule.
3. comment out the rule, reload the page, play the video again, then pause it. Now the large "More videos" overlay appears on the video.
4. In the logger, the rule will not appear.

uBlock Origin 1.16.10
same issue on Firefox 60 and Chrome 67

**Comment by uBlock-user** [comment]
Probably related to the fact that the picker cannot dig into iframes.

**Comment by joey04** [comment]
> Probably related to the fact that the picker cannot dig into iframes?

It may be related, but I just confirmed on Pale Moon 27 that logging is done for the STR scenario. (The logger has the above rule plus the others I have for youtube.com)

However, the element picker is the same problem for all browsers. Pale Moon uBO fork can't drill into the iframe either. So that confirms why I filed a separate issue (that's a duplicate of an old one I was unaware of).

**Note:** on Pale Moon I have my own legacy fork based on uBO 1.14.16. So perhaps something changed in uBO since then causing this lack of logging now.

**Comment by uBlock-user** [comment]
Not just limited to youtube either, happens on with video hosting websites wherever embedded, and `script:inject` filters are still logged too.

**Comment by gorhill** [comment]
Problem is that when uBO injects its cosmetic logging code, the `youtube.com` iframe does not yet exist, it is created afterward -- and the cosmetic logging code is [injected once at the top document level](https://github.com/gorhill/uBlock/blob/ab867dedf5a26bae8bedb8d0ca694324297624dd/src/js/messaging.js#L526) and `all_frames` is used to have the logging code injected into every child iframes. However this means future child iframes won't be injected into.

It's something I wanted to revised anyway since a while, the cosmetic logging code should be injected once on demand for every frame.
