### ISSUE TITLE
Permanent zapper fails to block images efficiently

### ISSUE THREAD

**Issue by Telmesomething** [uBlockOrigin/uBlock-issues#1020]
### URL(s) where the issue occurs

[The Guardian](https://www.theguardian.com/international)

### Describe the issue

This is not an ad issue, but rather an irritation. The newspaper is running a series of articles whereby individuals have been maimed or otherwise disfigured in some way or other. To illustrate their predicament fairly large images are published daily on the home page. While I sympathize with individuals who are afflicted in this horrible way I don't want to have to see these ghastly images of them every day and have tried to eliminate them by using UBO's permanent zapper. Unfortunately once the browser has been closed and (later) restarted, the images reappear. 

Images are sourced from guim.co.uk. Using the advanced menu to block this domain results in all images on the Guardian site being blocked so this isn't an option.

### Screenshot(s) The same images appear every day and can be seen easily enough on the Guardian site. The screenshots below illustrate that the zapper isn't functioning properly since the same events occur daily. 

![scars_1-4_May](https://user-images.githubusercontent.com/33827636/81588602-10e69080-93b9-11ea-8703-5a4b17459be1.PNG)

![scars_5-8_May](https://user-images.githubusercontent.com/33827636/81588629-19d76200-93b9-11ea-9bc9-994dcfdc15b8.PNG)

![scars_9-11_May](https://user-images.githubusercontent.com/33827636/81588659-22c83380-93b9-11ea-9720-ab9e48692d34.PNG)

### Versions

- Browser/version: Waterfox Classic 2020.4
- uBlock Origin version: 1.26.2

### Settings

- UBO is running in its default state.

![ubo_default](https://user-images.githubusercontent.com/33827636/81589748-fe208b80-93b9-11ea-9f9b-8b885b63470e.PNG)

### Notes

Tried blocking guim.co.uk using the advanced menu.

**Comment by gorhill** [comment]
Please provide the filters which you say are not working (I won't transcribe anything from screenshots), along with the exact page on which you say they don't work, along with screenshots of what on the page should have been removed by these filters.

I will test with Firefox stable only, Waterfox is not officially supported.

**Comment by gwarser** [comment]
Link is good. It's about this banner on the middle of the page:

![image](https://user-images.githubusercontent.com/886325/81595235-6e330f80-93c2-11ea-9000-3082e332cb75.png)


OP filters looks good. I suspect broken storage. Even if network filters fail (SW or something with `srcset`), cosmetic should still work.

```
||uploads.guim.co.uk/2020/04/22/Scars-A*.png$image
||uploads.guim.co.uk/2020/04/22/Scars-B*.png$image
www.theguardian.com##.scars__link
www.theguardian.com##.docs__scars.scars
```

**Comment by gorhill** [comment]
> SW or

What is "SW"?

**Comment by gwarser** [comment]
Service Worker - OP network filters have `image` type, they will be xhr with service worker evading block.

**Comment by Telmesomething** [comment]
@ gwarser, thanks for the tip. I'll install that build in a minute. 

But I note this morning that the 'scars' banner has gone now and has been replaced with a link to [documentary](https://www.theguardian.com/world/ng-interactive/2020/may/12/our-iranian-lockdown-how-coronavirus-changed-one-couples-life) about an Iranian couple's experiences with the lockdown. There's nothing in the current banner which anyone could find objectionable IMO. 

On the subject of Service Workers [this](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Storage_access_policy) article on the Mozilla site explains their current policy. I've always blocked cookies on the Guardian site since they will try to force you to subscribe if cookies are allowed. Guardian URLs don't appear in the Service Worker folder and the problem gwarser described may be the reason why. According to [ghacks.net](https://www.ghacks.net/2016/03/02/manage-service-workers-in-firefox-and-chrome/) Service Workers can be used to track users and I always delete them if I see those which I don't agree with in the appdata\storage\default folder. 

As regards Waterfox there are now [two versions](https://www.ghacks.net/2019/10/25/waterfox-development-splits-into-classic-and-current-branches/) available namely the Classic version which is legacy and Current which is the latest one. I use the legacy version because I don't like 'tabs on top' and continue to use the Classic Theme Restorer addon to customize the browser the way I like. 

Anyway, as mentioned above the scars banner has gone now and therefore this support request is no longer relevant. But thanks to everyone for taking the time to review it.
