### ISSUE TITLE
yahoo mail evil white rectangle

### ISSUE THREAD

**Issue by nojoegopotato** [uBlockOrigin/uBlock-issues#1021]
### Prerequisites

- [check] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [check] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [yup] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [it is the only extension] uBlock Origin is the only extension
    - [it already uses defaults ] uBlock Origin with default lists/settings
    - [every day is a fresh profile ] using a new, unmodified browser profile
- [ yup] I am running the latest version of uBlock Origin
- [i did not understand how what was provided could be used to address this issue ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

unable to select a new evil from yahoo

![unethical whitelist thread from yahoo webmail](https://user-images.githubusercontent.com/65205196/81630350-3758fb80-93ba-11ea-853a-62c6d2051a56.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

https://mail.yahoo.com/d/folders/1

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

- login to mail.yahoo.com
- large white rectangle appears unethically asking to whitelist mail.yahoo.com which runs evil third party ads and tracking
- click ubo shield
- activate picker

cannot continue

### Expected behavior:

non garbage results

### Actual behavior:

random everytime

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: firefox
* Operating System and version: macos

**Comment by gorhill** [comment]
I cannot reproduce a "large white rectangle" when logging in into Yahoo email.

What do you mean by "cannot continue"? The element picker user interface does not show up?

**Comment by gwarser** [comment]
Others say picker is working https://www.reddit.com/r/uBlockOrigin/comments/gbnc75/yahoo_mail_now_forcing_ad_block_disable/

Make sure [Cosmetic Filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) is enabled.

**Comment by gorhill** [comment]
Closing due to inability to reproduce and lack of feedback.
