### ISSUE TITLE
Issue with other Extensions:

### ISSUE THREAD

**Issue by LucianAndries** [uBlockOrigin/uBlock-issues#1023]
Hello.

I noticed that uBlock is filtering on-page elements of other extensions.
Extensions like buttons for scrolling or searching, etc. Basically extensions which have an overlay menu/button on the page. Don't know how to explain it. 😭

And if I disable "Cosmetic Filtering" in uBlock (the eye button thing), the other extensions start working.....together with ads and stuff. 😭😭😭

I know these kinds of extensions insert themselves into the page code, in order to work. But can't uBlock identify what part is an extension and what part is the site, so it can ignore the extension part?
It would be really hard and time consuming, to add an ignore list for each and every extension out there.............. :| 😭

Can something easier be implemented into uBlock, for such a thing?

Thank you.

**Comment by llacb47** [comment]
What extensions? What filterlists are you using?

**Comment by gwarser** [comment]
> I know these kinds of extensions insert themselves into the page code, in order to work. But can't uBlock identify what part is an extension and what part is the site, so it can ignore the extension part?

No. These are page elements as any other. But you can do this - just open [DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector) and add exceptions.

> It would be really hard and time consuming, to add an ignore list for each and every extension out there.

How many extensions you have? Is this such huge problem? Extension authors don't use blockers and don't know something is not working? Why they name parts of their extensions in a way which make them similar to ads?

**Comment by gorhill** [comment]
Without specifics, there is nothing actionable. And from your description, even if you come up with an specific extension which suffers an issue with uBO installed, it comes down to filter lists. I doubt filter lists will be modified to accommodate extensions, the only solution I see the extensions themselves making themselves more resistant to content blocker interference (other content blockers probably also interfere, it's not a uBO-specific issue).

**Comment by LucianAndries** [comment]
You closed it??? Well sorry I was away and couldn't answer instantly! Pfff.......
At least wait for the person to respond, before you do anything. Without them saying they can't/don't know how to give more info, you can't assume they don't have any or won't. :(

**Comment by gorhill** [comment]
Closed issues are re-opened if new information make the case uBO itself is the issue.

**Comment by LucianAndries** [comment]
The extension I'm talking is a very customisable search tool. Here it is:
https://chrome.google.com/webstore/detail/selection-context-search/kplgehmegmjifbhioeldcnphfkcfckjj

I had others, but I uninstalled them, thinking they don't work... :(

About DOM Inspector, @gwarser you're a genius!!!!!!! Dammit, I forgot about that, I always forget about that............ 🤦‍♂️🤦‍♂️🤦‍♂️
Also, I don't have THAT many extensions, I was talking generally...

Still, I found my extension in the DOM Inspector, it's "div#kgu316n9tie3jbddeabwy9".
Now, how can I make it be ignored on every website? Coz it works on some.
And do it for every extension I may have trouble with in the future.

**Comment by gorhill** [comment]
How do I reproduce an issue? What are the steps to see for myself how uBO is interfering with the extension?

**Comment by LucianAndries** [comment]
Go to this website, for example: https://www.wcostream.com/

The extension should show a menu with different websites to search on, once you selected a text. But to be sure, in its settings it has a checkbox with "Show the popup window when selecting text", check that...

**Comment by LucianAndries** [comment]
PS: Hope it works with different filters. If not, here's my backup file with my filters and rules.
[my-ublock-my-backup.txt](https://github.com/uBlockOrigin/uBlock-issues/files/4624748/my-ublock-my-backup.txt)

**Comment by gorhill** [comment]
> https://chrome.google.com/webstore/detail/selection-context-search/kplgehmegmjifbhioeldcnphfkcfckjj
> should show a menu with different websites to search on, once you selected a text

I see the search bar fine here, using default filter lists. Looking a bit more I find that Fanboy Enhanced Tracking List is interfering with fetching the search engine icons -- which frankly should be part of the extension itself -- every time the popup is brought up on a web page this causes network requests to be made to the various search engine servers.

I am not going to try all your filter lists, you will need to use the logger to find out which one is interfering and contact the maintainers to ask them to deal with your case. You should first contact the author of that Selection Context Search extension and tell them they need to harden themselves against interference, that is their issue, not a uBO issue.

Side note: the source code of that extension is obfuscated, this is against Chrome Web Store policy: <https://www.zdnet.com/article/google-to-no-longer-allow-chrome-extensions-that-use-obfuscated-code/>

So to confirm, not a uBO issue.

**Comment by LucianAndries** [comment]
PPS: I had a hard time finding it in the DOM Inspector............ I had to reload and restart the page/site and the Inspector, and tried using the extension a lot, until it finally showed up in the Inspector... :(
I also have a Scroll To Top extension, but the Inspector picks it up every time.

**Comment by LucianAndries** [comment]
I understand. But I have no way of contacting them. There's no website and there's no support. And google disabled reviews because they dum.

But until the, please tell me how to make the reverse/opposite of this, but for every site:
"www.wcostream.com##div#kgu316n9tie3jbddeabwy9"

**Comment by gorhill** [comment]
Use `#@#div#kgu316n9tie3jbddeabwy9`.

I removed your comment in which you posted your uBO settings, there are personal info in there and it's best to not have them published.

**Comment by LucianAndries** [comment]
Doesn't work :(

Wasn't an allow/ignore code with @@? Or || ? I dunno :(

**Comment by gorhill** [comment]
At this point I think it's preferable you ask for support on Reddit, more people than me can help you and I have run out of free time: <https://www.reddit.com/r/uBlockOrigin/>. Nest time if you do not feel like filling the new issue template, it's a good sign this is a support issue, which is best handled on Reddit sub.

**Comment by LucianAndries** [comment]
Ok. Thanks anyway!
