### ISSUE TITLE
Show uBO version in the main popup

### ISSUE THREAD

**Issue by Yaron10** [uBlockOrigin/uBlock-issues#1026]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Thank you for v1.27. :+1: 
I'd like to see the current version in the main popup without clicking "More".
[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
> I'd like to see the current version in the main popup without clicking "More".

There are other users who prefer to not see the version info without clicking less. I consider the majority of users are not very interested to have this cluttering their popop panel, so this I will decline.

For now you can set `popupPanelLockedSections` to 32 to pin the version info section, but it's officially left undocumented on purpose and as with any advanced settings:

> those settings may change or be removed in the future

**Comment by Yaron10** [comment]
OK. Thank you.

**Comment by Yaron10** [comment]
Related:
Is it possible to hide the "Blocked since installation" and "Domains you've connected to" lines *without hiding the "Blocked on this page" line*?

Thank you.

**Comment by gorhill** [comment]
Set undocument and highly subject to change advanced property `popupPanelDisabledSections` to `2` to remove "Blocked since installation". "Domains connected" can't be removed, I consider this to be an important metric.

**Comment by Yaron10** [comment]
:+1: 
Thank you for the quick reply and your great work.
