### ISSUE TITLE
uBlock blocking WebRTC DataChannel

### ISSUE THREAD

**Issue by izemize** [uBlockOrigin/uBlock-issues#1030]
Hi!

I use uBlock 1.26.0 on Windows764bit system and in Chrome 81.0.4044.138. uBlok blocked webRTC DataChannel and state always is connecting. The problem reproduced when uBlock turned off/ or on. When fully disabled the plugin in crome addons, DataChannel connected normally.

**Comment by gorhill** [comment]
> i don't understand why not turned off this, (and all others) when uBlock switched off. :)

The setting _"Prevent WebRTC from leaking local IP addresses"_ is global, it's not per-site. Turn it off if it interferes, it's off by default.

**Comment by izemize** [comment]
Sorry, last question. If this checked by default, uBlock blocking datachannel used web applications by default. Do you think this is okay? Basically, datachannel is not a thing from the devil. Simple user is unlikely to have realized, need to check mark should be removed.

**Comment by gorhill** [comment]
As said, it's not checked by default.
