### ISSUE TITLE
Logger shows names of scriptlet as different ones if short-hand is used.

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1031]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

AFAIK, the logger treats some short hands such as `3p` or `xhr` as the same entity as `third-party` or `xmlhttprequest` i.e. if list A has `||example.com^$3p,xhr` and list B `||example.com^$third-party,xmlhttprequest`, the logger regards they are equal and show as one rule which is used by two lists. But when it comes to scriptlets, it shows shorthands like `acis` as different as `abort-current-inlinescript`. Here's an example, FO server was chosen on `https://hpjav.tv/133315/ktra-217e` [NSFW] when AG Base was added to default lists:

![shorthand](https://user-images.githubusercontent.com/58900598/82036462-e445b800-96db-11ea-9f70-7c730da286b3.png)

As you see, `fileone.tv##+js(aopr, absda)` from uBlock filters and `fileone.tv##+js(abort-on-property-read, absda)` from AG Base are treated as different rules. It may be a fact and double injection is done but IDK - the page prevents me to open dev tools (will report soon).

### A specific URL where the issue occurs

`https://hpjav.tv/133315/ktra-217e`

### Steps to Reproduce

1. Enable AG Base (or add `fileone.tv##+js(abort-on-property-read, absda)` to My filters) and open the logger
2. Visit the site and choose 'FO server'
3. Play the video and see the logger

### Expected behavior:

The two rules should be shown as the same rule.

### Actual behavior:

Described

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: Firefox 76.0.1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Logger shows exactly the name of the filter as it was, when it was added. You added `abort-on-property-read` instead of `aopr`, so it shows that and doesn't show `aopr` instead.

**Comment by gorhill** [comment]
I remember this issue being raised in the past, I can't remember if an issue was filed about it.

**Comment by Yuki2718** [comment]
> Logger shows exactly the name of the filter as it was, when it was added. You added `abort-on-property-read` instead of `aopr`, so it shows that and doesn't show `aopr` instead.

But inconsistent with `$third-party` case?


> I remember this issue being raised in the past, I can't remember if an issue was filed about it.

I searched but couldn't find.

**Comment by uBlock-user** [comment]
> But inconsistent with $third-party case?

Alias matching was never implemented for scriptlets, so yes.

**Comment by gorhill** [comment]
This probably needs to be fixed, I am sure this was discussed somewhere (possibly in Teams) and I am sure I considered this an issue. The fact that there was no formal issue opened just mean I forgot about it.
