### ISSUE TITLE
The include directive does not work when loading local assets

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#1034]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When loading assets from the extension package, `!#include` directives are not resolved. 

Related code: 
https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L218

```js
let rootDirectoryURL = toParsedURL(mainlistURL);

// ...

if ( rootDirectoryURL === undefined ) { break; }
```

When the asset has a local URL, `rootDirectoryURL` is not properly computed and is `undefined`. This causes the logic that handles `!#include` directives to be skipped. 

Note that this does not require an emergency patch since the issue goes away once the filter is updated. 

### A specific URL where the issue occurs

`chrome://extensions/`

### Steps to Reproduce

1. Freshly install uBO
2. Open the dashboard
3. Go to filter lists tab

### Expected behavior:

Filters in the `filters-2020.txt` file to be loaded from the extension package. 

### Actual behavior:

Filters in the `filters-2020.txt` file are not loaded from the extension package. 

### Your environment

* uBlock Origin version: 1.27.0
* Browser Name and version: Chrome 84.0.4143.7
* Operating System and version: Windows 10.0.18363.778

**Comment by jspenguin2017** [comment]
Confirmed fixed.

**Comment by jspenguin2017** [comment]
Requests to retrieve local subfilters have cache bypass tokens, unlike the requests for the local main filters. 

This isn't really a problem, just a quick observation.

**Comment by gorhill** [comment]
> This isn't a problem, just a quick observation.

I need to modify `reIsExternalPath` to `reIsNetworkURL` (which would test for network-related schemes) to decide whether a cache-bypass parameter needs to be appended, and add a `reIsPackageURL` to detect package-related URLs, which either have no scheme/authority part or who starts with `vAPI.getURL('')`.

**Comment by gorhill** [comment]
The nested-within-nested list case is now broken with the fix, I need to address this. Test case: `https://github.com/yourduskquibbles/webannoyances/blob/db0358f96af5eae460f7e5c690ea3c93918810a2/ultralist.txt`.

The tested sublist should use the path of the nesting list.

**Comment by jspenguin2017** [comment]
Is the regression in the latest stable release? Is an emergency patch needed?

**Comment by gorhill** [comment]
An emergency release is needed, probably tomorrow.

**Comment by jspenguin2017** [comment]
Interestingly the latest change fixed https://github.com/uBlockOrigin/uBlock-issues/issues/1034#issuecomment-629580252 as well.
