### ISSUE TITLE
Dutch translation too long (is passive)

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1036]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Dutch translation in UI is to long to fit on the pop-up screen space, because passive language is used. In Dutch adjectives and nouns are concatenated, making passive language unsuitable for user interfaces (they simply take up to much space). Also for user interfaces and instructions it is better (advised) to use active language (start with a verb = informal imperative style).

### Steps to Reproduce
1. Choose Dutch as display language for the browser
2. Restart browser
3. Click on the uBO icon

### Your environment

* uBlock Origin version: 1.27
* Browser Name and version: Edge-Chromium  81.0.416.72
* Operating System and version: Windows 10

![Dutch to long](https://user-images.githubusercontent.com/30925856/82109527-f739a600-9736-11ea-8ded-ddc13260d54f.png)

### Translation suggestion:
 
Replace "Elementwissermodus openen" (element zapper mode open) to "Open element wisser" (open element zapper)
Replace "Elementkiezermodus openen" (element picker mode open) to "Open element kiezer"(open element picker)
Replace "Logger openen" (logger open) to "Open logger" (Open logger)
Replace "Dashboard openen" (Dashboard open) to "Open dashboard" (Open dashboard)

By starting with the verb Dutch verbs looks more like English and are shorter (active or imperative style) and the nouns need less adjectives, preventing these crazy long concatenated Dutch words (adjective+adjective+adjective+noun) with no spaces.

Dutch translation is fine for mouse-over-hoover explanation boxes

**Comment by uBlock-user** [comment]
Translations are done on Crowdin, not here, then the translated strings are pulled from there.

**Comment by gwarser** [comment]
https://crowdin.com/translate/ublock/13/enca-nl#q=Element

**Comment by gorhill** [comment]
@Kees1958,

Translators can use `&shy;` to insert soft hyphens (invisible) so that the browser will know where to split words.

**Comment by gorhill** [comment]
I don't see any activity for the `nl` locale at <https://crowdin.com/translate/ublock/13/enca-nl> regarding this issue. I can add the soft hyphen myself. @Kees1958 At which position do I need to insert the soft hyphen in the following strings?

    Elementwissermodus openen
    Elementkiezermodus openen

There can be more than one soft hyphen if needed, I just need to position at which to insert them.

**Comment by Kees1958** [comment]
Element&shy;wisser&shy;modus openen
Element&shy;kiezer&shy;modus openen

I signed in to crowdin, but as a newbie the changes have to be vetted, so above changes are on hold (latest activity was 3 to 4 years ago). 

Above is the 1-on-1 transaltion from English. As posted in User Interfaces and Instructions this passive language is considered bad practice (words become to long and active language is the advised style of writing).

**Comment by gorhill** [comment]
Thanks, I approved your changes. Tonnes has proofreader power and he is still active so you should be able to discuss changes with him. I leave it to current proofreaders to grant proofreading powers.

**Comment by Kees1958** [comment]
Below text as an example on how awful the Dutch translations are

Cosmetische filters dienen voor het verbergen van elementen in een webpagina die visueel storend kunnen zijn en niet door de op netwerkaanvragen gebaseerde filter-engines kunnen worden geblokkeerd.

Should be

Met cosmetische filters kan je visueel storende webpagina elementen verbergen, die je niet met netwerk filters kunt blokkeren.
