### ISSUE TITLE
Some RegExp filters are not parsed properly

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#1038]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This EasyList filter is not parsed properly. An error is logged to the background console instead: 

```
/^https:\/\/([a-z]+\.)?sythe\.org\/\[=%#@$&!^].*[\w\W]{20,}/$image
```

![image](https://user-images.githubusercontent.com/7283682/82127656-8ca65b80-9772-11ea-90d9-438ee0a2f21d.png)

The RegExp is kind of weird, but nevertheless is a valid RegExp. 
![image](https://user-images.githubusercontent.com/7283682/82127675-aba4ed80-9772-11ea-9a16-05b616821da3.png)

### A specific URL where the issue occurs

`chrome://extensions/`

### Steps to Reproduce

1. Update EasyList or add the filter above to my filters

### Expected behavior:

Filter parsed correctly. 

### Actual behavior:

Error logged to the background console. 

### Your environment

* uBlock Origin version: 1.27.2
* Browser Name and version: Chrome 84.0.4143.7
* Operating System and version: Windows 10.0.18363.778

**Comment by kulfoon** [comment]
> jspenguin2017 : The RegExp is kind of weird, but nevertheless is a valid RegExp.
> image

Yes, while it's still a valid regex I think that what you're calling "weird" is a bug (a typo) - an unwanted excape char `\` in the middle - should be `/[ ` and not `/\[`, coz I don't think that the author or anybody else wanted to escape `[` in that place, he simply wanted to pick any character between `[]` square brackets, which (the square brackets) should not be escaped in that place, so the intended regex would be: `/^https:\/\/([a-z]+\.)?sythe\.org\/[=%#@$&!^].*[\w\W]{20,}/$image`

Now, why uBO throws an error for such weird / bugged but still valid regex is another story:
- either a bug in uBO's regex parser
- or uBO don't like accepting such weird regex filters and it assumes that such network request / bugged/weird regex filter, while still being technically valid, would make completely no sense as a request, so uBO intentionally discards such weird regex filter, but that would mean uBO adds it's own restrictions for regex filters / tries to guess what were or were not intentions of author of a regex filter.

**Comment by gwarser** [comment]
It's just parser error. Swap `#@` in place and it will work. Simple example:

    /#@/$image

**Comment by gorhill** [comment]
I fixed it yesterday locally, but for the next dev cycle I had planned to rewrite and separate FilterParser from static network filtering engine  (so that it can be loaded separately in auxiliary pages for example), so it's probably going to be fixed as part of the rewrite.

**Comment by kulfoon** [comment]
> gwarser : Simple example :  `/#@/`

This won't work either, you have a typo in the example, you actually didn't swap it, you meant: `/@#/`

We got 3 bugs/typos already: Typo in the regex, a bug in uBO parser, and a typo in the comment, but hey - no offence, Human beings make mistakes..

**Comment by gwarser** [comment]
This is simplest example of filter which does not work.

**Comment by uBlock-user** [comment]
> We got 3 bugs/typos already: Typo in the regex, a bug in uBO parser, and a typo in the comment

Because of lack of installation of dev-builds to catch these bugs. Had more people installed devbuilds, this would have been caught before the stable release occurred.

**Comment by kulfoon** [comment]
> gwarser : This is simplest example of filter which does not work. 

Ok then, good to know, coz your previous comment looks confusing, it looks more like you wanted to provide the simplest example of filter which does work, especially after placing the example after previously suggesting swapping.
