### ISSUE TITLE
广告无法过滤

### ISSUE THREAD

**Issue by kjh00** [uBlockOrigin/uBlock-issues#1039]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
广告无法过滤
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
https://v.youku.com/v_show/id_XNDY2MTU3NTEzMg==.html?spm=a2hcb.12675304.m_2559_c_8263.d_1&scm=20140719.manual.2559.video_XNDY2MTU3NTEzMg%3D%3D
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:
广告
[What actually happened]

### Your environment
广告倒计时依然在计时
* uBlock Origin version:  1.27.3b2
* Browser Name and version: 360极速浏览器 12.0.1247.0
* Operating System and version: windows7 sp1
[1.txt](https://github.com/uBlockOrigin/uBlock-issues/files/4639476/1.txt)

**Comment by Yuki2718** [comment]
I don't understand what you want to say, hope it's the false positive I'm aware of but haven't reported. If so, you reported it in wrong place.

**Comment by kjh00** [comment]
对上述 ulr 视频广告无法进行过滤.

**Comment by uBlock-user** [comment]
@kjh00 https://github.com/uBlockOrigin/uAssets/issues/7424

**Comment by Yuki2718** [comment]
It looks like OP is rather reporting false negative, however, I got 404 error for the link and didn't see any ads.

**Comment by kjh00** [comment]
可能 可能这个是中国网络导致问题 外网访问404错误 已经上传截图. @Yuki2718

**Comment by uBlock-user** [comment]
post that problem in uBlockOrigin/uAssets#7424, don't open new issues about it in the uBO tracker.
