### ISSUE TITLE
The new UI is unusably oversized.

### ISSUE THREAD

**Issue by bug-re-port-er** [uBlockOrigin/uBlock-issues#1040]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The new UI is ridiculously oversized to the point its unusable.

### Steps to Reproduce

1. Use uBlock origin

### Expected behavior:

It should be at least 1.5 times smaller.

### Actual behavior:

It's too big.

### Your environment

* uBlock Origin version: 1.27
* Browser Name and version: 76.0.1
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Some people didn't like the old UI, some people do not like the new UI.

In the end and in both cases, to comes down to me making the call, trying to please everybody is impossible.

Use `popupFontSize` in advanced settings to adjust at your convenience.

**Comment by gorhill** [comment]
Also, asking for something vague such as _"make it 1.5 times smaller"_ is not going to fly here. If you want to make the case, fork and submit all the changes you think are necessary, taking into account all the issues which were solved by the current UI while insuring it work on all supported platforms. Then we will have something to discuss.

**Comment by gorhill** [comment]
ABP (342px wide) and AdGuard (322px wide) have larger panel compared to uBO's panel (296px wide) when uBO is set to be used in a comparable manner to those other blockers.

![b](https://user-images.githubusercontent.com/585534/82143482-54eef080-9812-11ea-9e0d-a7fa9fc8a770.png)

To reiterate: if you are not happy with the current UI, you will have to make more effort than _"I do not like it, re-do it to my liking"_ if you want to be listened to, even more so if you have no history of ever contributing here with testing dev builds, helping to investigate issues, helping with documentation, helping with support, and so on.

**Comment by bug-re-port-er** [comment]
Changing font size won't cut it here.
The whole thing is too big.

Add option to change sizes of the UI.
Something like 'normal', 'small' or 'bigger' for those who clearly need to see an eye doctor.

**Comment by Hiche3** [comment]
It's possible to switch back to the old interface:

Under advanced settings, set "uiFlavor" to classic.

**Comment by Hiche3** [comment]
> Some people didn't like the old UI, some people do not like the new UI.
> 
> In the end and in both cases, it comes down to me making the call with the understanding that trying to please everybody is impossible.

Would it make sense to add an option to use the old interface without having to go to advance mode?

**Comment by uBlock-user** [comment]
> without having to go to advance mode?

Legacy UI is for [limited time-span](https://www.reddit.com/r/uBlockOrigin/comments/gjyt4a/ubo_redesigned/fqqgkwm/) only.

**Comment by gorhill** [comment]
> an option to use the old interface

I rather not take on the burden for me to maintain the old panel forever.
