### ISSUE TITLE
Cannot install beta builds on Firefox nightly 78 & beta 77 on android

### ISSUE THREAD

**Issue by ybhmr4s11** [uBlockOrigin/uBlock-issues#1042]
Install V78 nightly or 77 beta (has stable version in extension list)

Try to install beta build(for testing else what the use of using test builds right?)
It download instead of installing.
Cannot manually install from addon manager page in Firefox for mobile.

UBO Beta builds should be available for testing in testing versions or in case of a bonked build when it only way is to revert to a previous version

@gorhill 
@gwarser @pgl @uBlock-user 

Can this be fixed please so can find and file issues
Regards
Jeff

**Comment by gorhill** [comment]
Browser limitation, Firefox Preview does not allow to install non-vetted extensions for now.

**Comment by ybhmr4s11** [comment]
> 
> 
> Browser limitation, Firefox Preview does not allow to install non-vetted extensions for now.

Is there any way to bypass it?
Any plans to whitelist UBO?
Is the issue being tracked?

**Comment by gorhill** [comment]
I can share what I was told by email back in February regarding how to test uBO in Firefox Preview (I didn't do this in the end because my storage is currently too close to its limit for me to install anything more):

> I’d like to share some instructions on how to test development versions of uBlock Origin with Firefox Preview on device, in case you’d like to test your builds in a real world environment:
> 
> 1. Install or update relevant software:
>     - [web-ext](https://github.com/mozilla/web-ext) version 4.1.0 or later.
>     - [adb](https://developer.android.com/studio/command-line/adb)
>     - [Firefox Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly&hl=en)
> 1. Connect your Android device via USB (via network is not yet supported)
> 1. Run web-ext run -t firefox-android and follow any instructions on screen
> 
> There are still some issues we have to work out. One very prominent issue during debugging is that when installing a temporary add-on via web-ext, the browserAction button won’t be correctly initialized. A workaround here is to make sure you first install the stock version of uBlock Origin via the add-ons manager on the device, and then use web-ext to “upgrade” to the development version. In this case the browserAction button should still be visible.

In addition these instructions in a subsequent email:

> * If you haven't already, you need to enable USB debugging:
https://developer.android.com/studio/debug/dev-options
> * On your device, open Firefox Preview Nightly, go to settings, and make
sure you have "Remote debugging via USB" enabled.
