### ISSUE TITLE
I'm gonna leave this repository due to rude behaviour of it's admin.

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uBlock-issues#1043]
He is overreacting or just behaving rude, by hidding my comments / and locking threads for no reason or for some his imaginary reasons, see [thread 1](https://github.com/uBlockOrigin/uBlock-issues/issues/1038) and [thread 2](https://github.com/uBlockOrigin/uBlock-issues/issues/1037) , also this is not the first time. I've tried to reply to [his comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1037#issuecomment-629812525) but he has managed to block the thread. He just says what he wants and what he thinks is an ultimate truth, and then blocks the possibility of responding to his sick allegations, forcing me to open an issue just to answer [his stupid comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1037#issuecomment-629812525), so this is my reply:

> Gorhill, I'm fine, so I don't need a break, perhaps you or somebody elase needs a break...and if you don't want to be notified constantly about things irrelevant to the actual issue you could just do it in a civilized way like a human, by saying it in a comment, rather than hiding comments and locking threads, which is just rude. Also the irrevelant thing you're talking about was caused by gwarser's confusing comment, if he wouldn't made a confusing comment I wouldn't need to ask/talk about his confusing comment, so why blaming me. Also coz this is not the first time on this repository where such things happens to me I need to ask you a question that you must answer for, because I'm not going to contribute to where admin doesn't want me to contribute.
> 
> ~~Do you want me to contribute to this repository?~~

Obsolete - I've decided to stop contributing to the uBO repo in the moment he locked [the previous thread](https://github.com/uBlockOrigin/uBlock-issues/issues/1037). Gorhill, you made uBO which is a great piece of software, but it also seems you have some emotional problems, which you should treat with a doctor, because your behaviour is just rude, disgusting, disrespectful and you simply lack of tact. And just don't try reply to my comment if you're gonna to leave me again with no possibility to reply and defend myself against your accusations (by hiding comments and locking the thread), because talking in such way with someone is not a civilized conversation, not on my level.

**Comment by gorhill** [comment]
Sorry about this.

I recognize I can be grumpy some days and I shouldn't have hidden your comment as "spam" (I just discovered yesterday I can hide a comment without having to give a reason).
