### ISSUE TITLE
Correct Advanced Settings value for uiFlavor on the wiki

### ISSUE THREAD

**Issue by leftl** [uBlockOrigin/uBlock-issues#1045]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
The Advanced Settings page on the wiki incorrectly states the value to revert to the "classic UI" when setting **uiFlavor**. The value stated is `-` when it should be `classic`. It would also be worth mentioning that a browser restart may be required for changes to be reflected.

### A specific URL where the issue occurs
https://github.com/gorhill/uBlock/wiki/Advanced-settings#uiflavor

### Steps to Reproduce
1. Visit https://github.com/gorhill/uBlock/wiki/Advanced-settings#uiflavor

### Expected behavior:
Correct value

### Actual behavior:
Incorrect value

### Your environment
N/A

**Comment by gwarser** [comment]
Fixed https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings/_compare/e14a03faf5ba0ab981a2696a8ab82ded7c038967
