### ISSUE TITLE
hpHosts’s Ad and tracking servers and other hosts

### ISSUE THREAD

**Issue by FellFromTheSky** [uBlockOrigin/uBlock-issues#1046]
### Description

Please add this host by default in uBlock Origin (yes, I'm crazy).
https://web.archive.org/web/20191026233644if_/http://hosts-file.net:80/ad_servers.txt

Following the same kind of link, you'll also be able to acess hosts from other offline hosts you used by the past.

**Comment by gorhill** [comment]
Declined.

**Comment by FellFromTheSky** [comment]
Any reason?

**Comment by gwarser** [comment]
It's not maintained anymore.

**Comment by gorhill** [comment]
> Any reason?

It makes no sense to encourage people to install an obsolete resources. Anyone can import it if they want, but I am not going to make it a stock list in uBO, fooling users into thinking this is a maintained resource.

**Comment by uBlock-user** [comment]
The list has been shutdown for a reason, just accept that.

**Comment by FellFromTheSky** [comment]
> The list has been shutdown for a reason, just accept that.
The list surely has been shutdown because MalwareBytes bought it.

@gorhill 
Thank you anyway for answering.
