### ISSUE TITLE
优酷广告过滤失败 解决办法

### ISSUE THREAD

**Issue by kjh00** [uBlockOrigin/uBlock-issues#1047]
**英语不好 语法不好  希望看到大佬反馈给作者 查明原因**

第一步：取消 
uBlock filters 规则 和 CHN: CJX's EasyList Lite 规则

第二步：自定义静态规则
! 2020/5/18 youku.com
@@||vali-dns.cp31.ott.cibntv.net^$media,domain=v.youku.com
||valipl.cp31.ott.cibntv.net^$domain=v.youku.com
||v4-valipl.cp31.ott.cibntv.net^$domain=v.youku.com

通过上述设置 ok 就能过滤掉优酷视频广告了！！ 
反馈： 上述2个规则默认允许优酷广告网站通过 不知道为什么。 希望作者能改进 
谢谢

**Comment by Yuki2718** [comment]
As @uBlock-user [said](https://github.com/uBlockOrigin/uBlock-issues/issues/1039#issuecomment-629933486), this issue tracker is not for filter issue. If you keep to post here you'll be marked as a spammer, unfortunately. You're instructed to comment on https://github.com/uBlockOrigin/uAssets/issues/7424, however, basically missed ads on Chinese sites should be reported to [EasyList China](http://abpchina.org/forum/forum.php) or [CJX's EasyList Lite](https://github.com/cjx82630/cjxlist).
