### ISSUE TITLE
No or better shadown for on/off button

### ISSUE THREAD

**Issue by filips123** [uBlockOrigin/uBlock-issues#1049]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since UI redesign, on/off button has square shadow around it when it is hovered. This shadow should be improved to not be just gray square or completely removed.

### A specific URL where the issue occurs

Every URL where you can toggle blocking with on/off button.

### Steps to Reproduce

1. Open website and popup
2. Hover with mouse over on/off button

### Expected behavior:

Shadow for button should be improved or removed.

### Actual behavior:

Shadow for button is just gray square.

### Your environment

* uBlock Origin version: 1.27.3b4 and 1.27.3rc0
* Browser Name and version: Firefox 76.0.1
* Operating System and version: ElementaryOS 5.1.4

**Comment by gorhill** [comment]
> Shadow for button is just gray square

This is no longer the case since a while now.
