### ISSUE TITLE
Odd sorting in popup domains list when domains have same SLD but different TLD

### ISSUE THREAD

**Issue by xofe** [uBlockOrigin/uBlock-issues#105]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When a website connects to multiple domains where the domains have the same second-level domain name but a different top-level suffix (e.g. `google.com` and `google.com.au`), it seems one of these domains is sorted alphabetically within the other. See screenshot for a visual example affecting `google.com.au`.

![Screenshot of popup domains list sorting issue](https://user-images.githubusercontent.com/22776566/42100527-fc96fa0c-7baf-11e8-8174-2bfeda3ea896.png)

### A specific URL where the issue occurs

https://www.gumtree.com.au/s-ad/peakhurst/cars-vans-utes/mazda-bravo-tipper/1188312239

### Steps to Reproduce

1. Visit site that connects to multiple domains fitting requirements above.
2. Open uBO panel and click 'domains connected' text to show domains if they are not visible.
3. Click the `all` row to show sub-domains in list.

### Expected behavior:

Order of domains is:
* `google.com`
  * `accounts.google.com`
  * `apis.google.com`
  * `plus.google.com`
  * `www.google.com`
* `google.com.au`
  * `www.google.com.au`

### Actual behavior:

Order of domains is:
* `google.com`
  * `accounts.google.com`
  * `apis.google.com`
* `google.com.au`
  * `www.google.com.au`
  * `plus.google.com`
  * `www.google.com`

### Your environment

* uBlock Origin version: 1.16.2
* Browser Name and version: Firefox 62b3, Chromium 68.0.3405

**Comment by uBlock-user** [comment]
Before browsing to `gumtree.com.au`, were you on `google.com.au` ?

**Comment by xofe** [comment]
No, the link was pasted in the address bar from a blank page. The `google.com.au` request is for `https://www.google.com.au/afs/ads?q=Mazda%20bravo%20tipper&pfcrncy=AUD& ...` (blocked by EasyList), requested in `https://www.google.com/adsense/search/ads.js` (which EasyList whitelists for `gumtree.com.au`) so it may depend on where you're connecting from.

Note the issue here is the sort order, not whether a domain was contacted or not. Unless your domain list has items with same SLD but different TLD yet it was sorted correctly, 'unable to reproduce' doesn't seem appropriate.

**Comment by uBlock-user** [comment]
`google.com.au` simply doesn't appear on my end, neither does `accounts.google.com` or `apis.google.com` so I can't reproduce the situation you were able to create.

**Comment by gwarser** [comment]
I can reproduce by manually inserting
```
<img src="https://www.google.com.au/afs/ads?q=Mazda%20bravo%20tipper&amp;pfcrncy=AUD">
```
into body.

**Comment by xofe** [comment]
Alright, I've created a test case to show this issue at http://xofe.mm.st/ubo-domain-sort-test.html. It'll load `apis.google.com`, `plus.google.com`, `www.google.com`, and `www.google.com.au` each as iframes. They may not load due to the sites using a `X-Frame-Options` header but that doesn't matter, they will still be listed in domains list.

**Comment by uBlock-user** [comment]
I can reproduce on that test case.
