### ISSUE TITLE
Anti-caching links in "Block element..." pop-up

### ISSUE THREAD

**Issue by Ro-Den** [uBlockOrigin/uBlock-issues#1050]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Image links with an anti-caching element wouldn't be blocked, because the element, which is usually a random number or an epoch timestamp, is constantly changing.

So, the anti-caching element (everything that goes after ?) of an image link (same for css, JavaScript) should be omitted by default, because such a filter doesn't make sense.

The problem in implementing such a default approach is that PHP (and maybe other that use GET method) links, like traditional YouTube youtube.com/watch?v= , would also be affected, so it is necessary to distinguish such links from image links.

### A specific URL where the issue occurs

https://www.youtube.com/live

### Steps to Reproduce

1. Click "Block element..." on any image with the "LIVE NOW" (!important) marking below.
2. Click "Create" in the pop-up window.
3. Wait at least 5 minutes or more (it may be channel dependent).
4. Reload the page.
5. Find the blocked image have reappeared.

### Expected behavior:

The anti-caching element (everything that goes after ?) of an image link (same for css, JavaScript) should be omitted by default, because such a filter doesn't make sense.

### Actual behavior:

Image links with the anti-caching element wouldn't be blocked, because the element, which is usually a random number or an epoch timestamp, is constantly changing.

### Your environment

* uBlock Origin version: 1.27
* Browser Name and version: Mozilla Firefox Quantum 68.8.0 ESR (64-bit)
* Operating System and version: Linux Kubuntu 20.04

**Comment by gorhill** [comment]
> The anti-caching element (everything that goes after ?) of an image link (same for css, JavaScript) should be omitted by default

There is no way for uBO to know whether a query string is meant to bypass the browser cache of that is is key to retrieve the proper resource from the server.

The element picker offers you the choice to pick a query string-less filter, it's up to you to select this one when you create your filter.

**Comment by Ro-Den** [comment]
> There is no way for uBO to know whether a query string is meant to bypass the browser cache or that it is key to retrieve the proper resource from the server.

True, if it's a PHP link or the like.

If it's an image link, it's either the same image from cache or a new one from the server. And both should be blocked.

Just delete the anti-caching part of an image link, type whatever you want after ?, and you'll get the same image or a new one from the server. I've never observed a different behaviour.

Try the same with the PHP link: youtube.com/watch? and you will be redirected to the main page.

> The element picker offers you the choice to pick a query string-less filter, it's up to you to select this one when you create your filter.

I know, but constantly picking the 2nd choice is consuming clicks and time.

Is it possible to at least change the order?

**Comment by gorhill** [comment]
I just don't think uBO should make any assumption about the query portion of a URL, it should just keep doing what it's currently doing: offer the choice and let user make the decision, picking the query-less version of a URL is one extra click, I don't see this as an issue. I prefer to decline.

**Comment by gorhill** [comment]
So here is a counterexample: `https://www.reuters.com/`. If you remove the query string part by default, then all images will be blocked. So to me this confirms that changing the current behavior is desirable.

**Comment by Ro-Den** [comment]
I've moved

    candidates.push(`||${pattern}`);

https://github.com/gorhill/uBlock/blob/238d31c319fae5fccf91b7ad3d1444201407fe14/src/js/scriptlets/element-picker.js#L348

from line 348 to line 355.

Now the "narrow" filter without the anti-caching element is the 1st and the more "specific" one is the 2nd. Exactly as I want.
