### ISSUE TITLE
uBlock Panel is cutoff in mobile

### ISSUE THREAD

**Issue by SS1113** [uBlockOrigin/uBlock-issues#1051]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
ublock Panel is cutoff

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open a website
2. Click uBlock Origin icon
3. Observe that the panel is cutoff

### Expected behavior:

[What you expected to happen]
The panel shouldn't be cutoff

### Actual behavior:

[What actually happened]
The panel is cutoff

### Your environment

* uBlock Origin version: 1.27.2
* Browser Name and version: Firefox beta Version 76.0.0-beta.2 and Firefox Nightly 200518 06:00
* Operating System and version: Android 10
![Screenshot_20200519-070725](https://user-images.githubusercontent.com/42088907/82275637-c645b500-9972-11ea-9afb-3b0d08ae7fc3.png)

**Comment by gorhill** [comment]
Can you confirm whether the issue is still there in 1.27.4?

**Comment by SS1113** [comment]
@gorhill Yes, it still appears like this:
![Screenshot_20200519-183908](https://user-images.githubusercontent.com/42088907/82330225-12741200-99d2-11ea-8f8e-cadf8ba6519e.png)

**Comment by gorhill** [comment]
I cannot reproduce on my side. Is the issue also present in <stable Firefox for Android>?

I have an idea what the issue might be, and if you can also reproduce in stable Firefox for Android, this means you will be able to test the fix by installing the next dev build -- and if this works I will issue an emergency fix.

**Comment by SS1113** [comment]
@gorYes, it still appears like this, to reproduce the issue; close the browser, immediately after the launch go to a website and click on the uBO icon. But I have also seen it randomly appear like this sometimes, and it remains like that unless I restart the browser:
![Screenshot_20200519-183908](https://user-images.githubusercontent.com/42088907/82330225-12741200-99d2-11ea-8f8e-cadf8ba6519e.png)

**Comment by gorhill** [comment]
> to reproduce the issue; close the browser, immediately after the launch go to a website and click on the uBO icon

I understood the panel always appeared as in your screenshots. You mean sometimes it happens sometimes it doesn't happen?

**Comment by SS1113** [comment]
@gorhill Yes, it doesn't always appear like that. And this is how it appears on Firefox for Android stable: 
![Screenshot_20200519-185802](https://user-images.githubusercontent.com/42088907/82332408-e27a3e00-99d4-11ea-93db-89dc04edfcec.png)

**Comment by gorhill** [comment]
> it doesn't always appear like that. And this is how it appears on Firefox for Android stable:

Ok let's step back and clarify, no need to post screenshots anymore. Since I cannot reproduce on my side, I need to understand exactly what is happening on your side.

I find the statement above ambiguous; when you say _"this is how it appears on Firefox for Android stable"_, is it **always** the case, or is it only with very specific steps, which steps must be followed exactly or else it doesn't happen?

**Comment by SS1113** [comment]
Sorry for the confusion caused, I should have been more clear. 

I'll explain it again: 
The issue doesn't always appear, it happens
randomly. So far I have been able to reproduce it everytime when I launch the browser and go to a site and click the uBO icon immediately after a browser restart.

This is not always the case, it happens everytime if the above mentioned steps are followed and sometimes it appears glitchy randomly.

At other times the panel is displayed correctly.

**Comment by gorhill** [comment]
> sometimes it appears glitchy randomly

In that case, I don't understand why this happens. Your screenshots show you are being served the desktop flavor of the panel, but even though, there is code in the panel to fallback into portrait mode when it detects that the viewport is not wide enough, which is clearly the case as per your screenshot. It's as if the viewport is larger than the phone display and thus uBO finds it's not necessary to fall back into portrait mode. Can you scroll horizontally to reveal the firewall pane when this happens?

**Comment by SS1113** [comment]
>Can you scroll horizontally to reveal the firewall pane when this happens?
Okay, If you are saying that in the panel then I cannot scroll horizontally, I'm only able to see what I posted in the screenshots, I cannot scroll horizontally or even vertically when this glitchy interface appears.

**Comment by gorhill** [comment]
Since I can't reproduce, I can investigate why this happens, and consequently I can't fix. I will need more of such reports and hopefully someone who can reproduce can also investigate the exact cause of the issue.

**Comment by gwarser** [comment]
@SS1113 your device screen size?

**Comment by SS1113** [comment]
@gwarser my device is Motorola One Power, which has a screen size of 6.2 Inches

**Comment by gwarser** [comment]
@SS1113 if you open this page https://bestfirms.com/what-is-my-screen-resolution/ what you see under "You are using"?

**Comment by SS1113** [comment]
@gwarser 349x749

**Comment by SS1113** [comment]
@gorhill @gwarser I want to clarify that I'm not facing this issue anymore. I have tested it on `Firefox for Android 68.9.0` and `Firefox Preview 5.1.1`. I have observed a lot but this is not reproducing with the steps I mentioned so I think it is safe to close this issue now. Thanks a lot!
