### ISSUE TITLE
Maximize and Minimize Quick links in new popup panel

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1053]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The new simplified user interface really is an improvement. I like the clean interface. On our shared PC I normally choose the most simple version with only the ON-OFF button on it. Occasionally I want to view the domains (for trouble shooting or just out of curiosity to see what happens on a new website I visit)

To switch from most simple view to the most detailed view I have to click on MORE a few times. Would it be possible to add a shortcut on the most simple display to show the most detailed display (or only the domains list) with just one click? There is room for a short cut/quick link in most simple display and most detailed display.

The same but reverse happens when I want to switch back to the most simple GUI from the most detailed GUI, again I have to click LESS a few times.

**Comment by gorhill** [comment]
The more/less buttons are meant to be used once in a while when one want to configure the panel to their liking, they are not meant to be used all the time. I consider adding yet another button down there to be overcomplicating the UI.

**Comment by Kees1958** [comment]
:-) I am not switching all the time, only occasionally as explained in the first post and believe the subsequent pressing MORE already started to irritate me.  On all display version two options are shown More and Less, except on most minimized (no details) and most maximized (all details displayed)

Maybe the terms MAXIMIZE (on the most simple display) and MINIMIZE (on the display with all details) are better (according to cycle paradigm in user interfaces, jump to last on first display and jump to first on last display).

**Comment by LennyFox** [comment]
For me the advantage of uBlockOrigin content blocker compared to Adblockers for me is the advanced mode, and the insight the domain list provides on what is happening on a webpage.  

So I see the elegance of having a minimize (normal mode of operation) /maximize (hey what is happening here) option.

**Comment by gorhill** [comment]
Again, the purpose of more/less is to configure uBO once and leave it as is. Advanced users can reveal more controls, install-and-forget users can make it even more install-and-forget by hiding more controls. I do not want an install-and-forget user to be presented with what would amount to them as a an airplane cockpit which would happen if I put in there a maximize button. As of now I prefer to keep things as is, the more/less buttons match the purpose I want them to have.
