### ISSUE TITLE
Custom keyboard shortcuts get reset on every uBO version update

### ISSUE THREAD

**Issue by setyb** [uBlockOrigin/uBlock-issues#1054]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Every time uBO gets updated, all the custom keyboard shortcuts get reset.

### A specific URL where the issue occurs

Not web-dependent.

### Steps to Reproduce

1. Set custom keyboard shortcuts for uBO in about:addons (Firefox)
2. Close Firefox
3. Launch Firefox
4. Confirm shortcuts work (they do)
5. Wait for a uBO update
6. Install the uBO update via about:addons
7. Repeat steps 2-4.  Custom keyboard shortcuts no longer work.

### Expected behavior:

Custom keyboard shortcuts to be maintained.

### Actual behavior:

Custom keyboard shortcuts lost.

### Your environment

* uBlock Origin version: 1.27.4
* Browser Name and version: Firefox 76.0.1
* Operating System and version: Windows

**Comment by gwarser** [comment]
Can you describe in more detail how you update? Is auto-update active?

> Wait for a uBO update
> Install the uBO update via about:addons

**Comment by gorhill** [comment]
The only way for uBO to modify the keyboard shortcut on its side is for Firefox to be version 73 or older -- otherwise there is no code path in uBO to modify the keyboard shortcut. So if this happens with Firefox 76, then I consider this a browser issue.

**Comment by krisu5** [comment]
> So if this happens with Firefox 76, then I consider this a browser issue.

For me, it happens on v76.

**Comment by gorhill** [comment]
What shortcut are you using? I believe some keyboard shortcuts are reserved by the browser and cannot be overridden.

**Comment by krisu5** [comment]
> What shortcut are you using? I believe some keyboard shortcuts are reserved by the browser and cannot be overridden.

Ctrl + F1, Ctrl + F2 & Ctrl + F3.

Firefox doesn't allow setting reserved keys on "Manage Extension Shortcuts" page.

**Comment by gorhill** [comment]
Does it work fine in a new profile?

**Comment by setyb** [comment]
> Can you describe in more detail how you update? Is auto-update active?

I use manual update only.

> > Wait for a uBO update
> > Install the uBO update via about:addons
> 
> Everything else works fine?

Yes.

**Comment by setyb** [comment]
> The only way for uBO to modify the keyboard shortcuts on its side is for Firefox to be version 73 or older -- otherwise there is no code path in uBO to modify the keyboard shortcuts. So if this happens with Firefox 76, then I consider this a browser issue.

All other extensions maintain their keyboard shortcuts except uBO.  I tested further with 6 other extensions that use keyboard shortcuts.  uBO is the only one with the issue.

**Comment by setyb** [comment]
I found where they are stored: `extension-settings.json`

**Comment by setyb** [comment]
The only thing I know of that makes uBO different from every other extension is that its updates don't get applied instantly when they are downloaded.  Instead you have to restart the browser or explicitly disable and then re-enable uBO (unless you modify `extensionUpdateForceReload`, which I have not).

See this commit: https://github.com/gorhill/uBlock/commit/59bdf2b4ccd1151a296af36e5536ed00eeb07fb4

**Comment by uBlock-user** [comment]
> that its updates don't get applied instantly when they are downloaded.

because of https://github.com/uBlockOrigin/uBlock-issues/issues/717

**Comment by gorhill** [comment]
> I found where they are stored: `extension-settings.json`

I just registered a shortcut for uBO and it's not being saved in there.

**Comment by gorhill** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1639705>

**Comment by sanbor** [comment]
Glad to find the issue already reported. I have been suffering from this since I started trying to use keyboard shortcuts (last two months).

A workaround could be to assign default keyboard shortcuts. This way we don't have to wait until Firefox solves the issue. Personally I just want to use uBlock from the keyboard, I'm don't care what keyboard shortcut I have to press as long as it works.

I found that some extensions (e.g. https://github.com/gildas-lormeau/SingleFile/blob/master/manifest.json#L127) suggest default keyboard shortcuts.

Here is my suggestion for uBlock `manifest.json` file:

```
"commands": {
    "_execute_browser_action": {
    },
    "launch-element-zapper": {
        "suggested_key": {
            "default": "Shift+Alt+Z"
        }
        "description": "__MSG_popupTipZapper__"
    },
    "launch-element-picker": {
        "suggested_key": {
            "default": "Shift+Alt+P"
        }
        "description": "__MSG_popupTipPicker__"
    },
    "launch-logger": {
        "suggested_key": {
            "default": "Shift+Alt+L"
        }
        "description": "__MSG_popupTipLog__"
    },
    "open-dashboard": {
        "suggested_key": {
            "default": "Shift+Alt+D"
        }
        "description": "__MSG_popupTipDashboard__"
    },
    "relax-blocking-mode": {
        "suggested_key": {
            "default": "Shift+Alt+R"
        }
        "description": "__MSG_relaxBlockingMode__"
    }
},
```

**Comment by setyb** [comment]
@sanbor wrote:
> Personally I just want to use uBlock from the keyboard, I'm don't care what keyboard shortcut I have to press as long as it works.

My experience is that you can currently use keyboard shortcuts.  You just have to reassign them each time you update uBO.

@all
I toggled `extensionUpdateForceReload`, and I'll report back after the next uBO update if that prevents the shortcuts from getting lost.

I wanted to flip that switch anyways, as I find it a little bothersome that uBO requires a restart (or extension toggle) to update.  I always update extensions with no content tabs open, so I don't think toggling `extensionUpdateForceReload` will impact me.  Does anyone disagree?

@gorhill wrote:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1639705

Thank you for filing the bugzilla report.  I could be mistaken, but I have a hunch it will get resolved faster because you reported it.  All the bugzilla bug reports I have created are still unresolved after 5+ years.  I feel a little bad about it, but I stopped reporting after spending my time writing bug reports that were never fixed.

**Comment by gwarser** [comment]
> A workaround could be to assign default keyboard shortcuts.

This was already tried and did not worked out - too many different keyboard layouts to choose sane default which will work for everyone.

**Comment by gitressa** [comment]
I also see this reset after every update. I use these shortcuts:

Function | Shortcut
--- | ---
Activate extension | Alt+U
Enter element picker mode | Alt+X
Enter element zapper mode | Alt+Z

**Comment by setyb** [comment]
@sanbor wrote:
> Glad to find the issue already reported. I have been suffering from this since I started trying to use keyboard shortcuts (last two months).

@gitressa wrote:
> I also see this reset after every update.

Thanks for the confirmations.

What is your value of `extensionUpdateForceReload` in uBO's Advanced Settings?

Do you manually or automatically perform extension updates?

Which browser (and version) are you using?  Which OS?

**Comment by gitressa** [comment]
@setyb: `extensionUpdateForceReload` is set to `false` and extensions are updated automatically in Firefox 76.0.1 (64-bit) on Ubuntu 18.04.

**Comment by setyb** [comment]
This issue was closed by "uBlock-user" without any comment. I have an update and a workaround, but I'm not sure if it's appropriate for this repo to post more info on a closed issue.

**Comment by gwarser** [comment]
>I'm not sure if it's appropriate for this repo to post more info on a closed issue.

And yet, you posted ;)

**Comment by uBlock-user** [comment]
> This issue was closed by "uBlock-user" without any comment

Firefox issue as per https://github.com/uBlockOrigin/uBlock-issues/issues/1054#issuecomment-631717995, so nothing for gorhill to address in uBO.

**Comment by gitressa** [comment]
Since [votes](https://wiki.mozilla.org/BMO/UserGuide/BugFields#votes) are supposedly not used by Mozilla developers to set priorities, leaving a comment in the [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1639705) might be one method to help move it along.

**Comment by gitressa** [comment]
Firefox 80 was released August 25, 2020, and shortcuts now stay functional after an update.
