### ISSUE TITLE
Sort dynamic filter list by destination / host components

### ISSUE THREAD

**Issue by Mathnerd314** [uBlockOrigin/uBlock-issues#1055]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I can't speak for anyone else's dynamic rule list, but in my list most rules are sub-hosts where the destination is specific to the origin, and the rest are CDN's like jsdelivr. Sorting by destination allows finding the CDN's, while the current sort (by origin) does not seem to aid anything besides erasing a site.

Also, for subdomains, the current sort is just alphanumeric. It should group domains like a.x.com and b.x.com, to aid in creating rules for the top domain.

### A specific URL where the issue occurs

Chase.com is a big site that provides an example. To allow it to work in uBlock Medium Mode (+ a global rule blocking inline/first-party scripts) I've created the following rules:
```
personal.chase.com chase.com * noop
...
secure04b.chase.com chase.com * noop
secure04b.chase.com chasecdn.com * noop
secure06b.chase.com chase.com * noop
secure06b.chase.com chasecdn.com * noop
secure07b.chase.com chase.com * noop
secure07b.chase.com chasecdn.com * noop
...
www.chase.com chase.com * noop
www.chase.com chasecdn.com * noop
```
Clearly there is a lot of duplication here. Without sorting it by the destination, or at least by hostname components in the source, these are all scattered throughout the filter list. And if I see the secure* hosts and add rules for the top domains,
```
chase.com chase.com * noop
chase.com chasecdn.com * noop
```
Then there is no warning or anything that will remove the now-useless other rules like for `personal.chase.com`.

Another case is domains like `cdn.jsdelivr.net.cdn.cloudflare.net`, because they are used on many completely unrelated websites. You wouldn't be able to find the shared CDN's for possible whitelisting without a good memory or the requested sort.

### Steps to Reproduce

1. Add a lot of dynamic filter rules
2. Try to look at them and find redundancies

### Expected behavior:

Sort by destination and source domains with an intelligent sort
**or**
Some extension of the filter tool to allow selecting a sort by destination

### Actual behavior:

Give up in frustration and import the list into a spreadsheet program just to sort it

### Your environment

* uBlock Origin version: 1.27.4
* Browser Name and version: Firefox 76
* Operating System and version: Linux (NixOS 20.09)

**Comment by gwarser** [comment]
See also https://github.com/gorhill/uBlock/issues/571

**Comment by uBlock-user** [comment]
> Try to look at them and find redundancies

You know you can filter out the rules and then look for that.

**Comment by Mathnerd314** [comment]
> You know you can filter out the rules and then look for that.

I guess, but entering in 1240 different domains into the search box would take a while, probably more time than it would for me to implement this.

**Comment by gorhill** [comment]
I still need to add localized strings for the new sort widget.
