### ISSUE TITLE
Updating uBlock on Firefox requires a browser restart

### ISSUE THREAD

**Issue by neroux** [uBlockOrigin/uBlock-issues#1056]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The closest I could find was https://github.com/gorhill/uBlock/issues/3637, but I am not sure whether it really is the same issue. I am actually somewhat surprised that I didnt find any more recent reports for that issue, as it should be quite obvious. That would usually lead me to believe it might be specific to my setup, however as I could **reproduce it also on a brand-new browser profile**, I'd tend to rule that out.

Essentially, when there is a uBlock update Firefox does not immediately update it but only after a restart of the browser. The behaviour is very similar to the old days when every extension required a restart, however that is not a requirement anymore and uBlock should update immediately and, in fact, did so for quite some time. Only "recently" (cannot tell exactly which version, a few months ago) it started to not update immediately.

**No other extension I have installed shows that behaviour.**

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Create a new Firefox profile
2. Disable automatic extension updates
3. Install any previous uBlock version
4. Restart Firefox (optional, but for the sake of it)
5. Check for updates (should offer the current version)
6. Update uBlock

### Expected behavior:

Firefox to immediately update uBlock and activate the new version.

### Actual behavior:

The existing version will remain active until the browser gets restarted, upon which the update becomes active.

### Your environment

* uBlock Origin version: uBlock 1.27.4 (the issue has been present since quite a few versions though)
* Browser Name and version: Firefox 78, Nightly (equally, the issue has been present since)
* Operating System and version: Windows 8.1 and 10

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#extensionupdateforcereload

**Comment by gwarser** [comment]
This is protection against accidental mid-session reloads: https://github.com/uBlockOrigin/uBlock-issues/issues/717

**Comment by neroux** [comment]
Fair enough, thanks @gwarser. A reasonable feature, even if I had it default the other way round that one explicitly needs to enable it.
