### ISSUE TITLE
AdminSettings for uBlock are not working anymore in Firefox

### ISSUE THREAD

**Issue by BenKu82** [uBlockOrigin/uBlock-issues#1057]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In Issue https://github.com/gorhill/uBlock/issues/2986 is a Solution documented, but it does not work anymore.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Creating File "uBlock0@raymondhill.net.json" containing:

```
{
 "name": "uBlock0@raymondhill.net",
 "description": "ignored",
 "type": "storage",
 "data": {
    "adminSettings": {"autoUpdate":true,"netWhitelist":"about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nlocalhost\nloopconversation.about-scheme\nopera-scheme\nEXAMPLE.COM"}
   
		}
		
}
```

2. Creating Registry-Entry 

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage\uBlock0@raymondhill.net]
@="C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\uBlock0@raymondhill.net.json"
```

3. Starting Firefox

### Expected behavior:

EXAMPLE.COM has to be entered in the uBlock-Whitelist

### Actual behavior:

Nothing

### Your environment

* uBlock Origin version: v1.25.0
* Browser Name and version: Mozilla Firefox 68.8.0esr
* Operating System and version: MS Windows 10 1809

**Comment by gwarser** [comment]
I'm pretty sure this must be double escaped:

    "adminSettings": {"autoUpdate":true,"netWhitelist":"

->

    "adminSettings": "{\"userFilters\":\"www.test.de##sc

**Comment by BenKu82** [comment]
I tested it withe tool, too. But it does not work, too.

**Comment by gwarser** [comment]
Works for me on Linux

![image](https://user-images.githubusercontent.com/886325/82439529-20419a00-9a9b-11ea-927d-ab65ef47755e.png)

**Comment by gorhill** [comment]
Your `uBlock0@raymondhill.net.json` worked on my side. Note that double escaping is no longer needed so the following worked for me:

    {
        "name": "uBlock0@raymondhill.net",
        "description": "_",
        "type": "storage",
        "data": {
            "adminSettings": {
                "autoUpdate": true,
                "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nlocalhost\nloopconversation.about-scheme\nopera-scheme\nEXAMPLE.COM"
            }
        }
    }

**Comment by gorhill** [comment]
There is an issue actually, I see `EXAMPLE.COM` but it's commented out.

**Comment by gorhill** [comment]
> uBlock Origin version: v1.25.0

Sorry,  don't think this version supported not double-encoding; still the double encoded JSON worked for me:

    "{\"autoUpdate\":true,\"netWhitelist\":\"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nlocalhost\\nloopconversation.about-scheme\\nopera-scheme\\nEXAMPLE.COM\"}"

**Comment by BenKu82** [comment]
I don´t know, what is wrong, but all your solutions does not work on my test systems.
@gorhill: I used your last string like this:
{
    "name": "uBlock0@raymondhill.net",
    "description": "_",
    "type": "storage",
    "data": {
        "adminSettings": {
            "autoUpdate": true,
            "netWhitelist": "{\"autoUpdate\":true,\"netWhitelist\":\"about-scheme\\nbehind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nlocalhost\\nloopconversation.about-scheme\\nopera-scheme\\npost.de\"}"
        }
    }
}

And my registry entry looks like this:
[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage]
"uBlock0@raymondhill.net"="@=C:\\temp\\uBlock0@raymondhill.net.json"

**Comment by gwarser** [comment]
Please use proper code formatting. We cannot distinguish between formatting errors and possible encoding issues.

https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by gorhill** [comment]
Your json text is invalid, see with <https://jsonlint.com/>.

**Comment by BenKu82** [comment]
Is the Syntax of the Registry-Entry correct?
```

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage]
"uBlock0@raymondhill.net"="@=C:\\temp\\uBlock0@raymondhill.net.json"
```
PS: I corrected my entry before.

**Comment by gwarser** [comment]
We both are on Linux, so we cannot test this. Looking at examples it's wrong.

`uBlock0@raymondhill.net` is a "directory" and `@` means "default" key.

**Comment by BenKu82** [comment]
Is there an other way to deploy a whitelist?
Where does uBlock save manual whitelist entries?

**Comment by gorhill** [comment]
uBO has no access to the file system, settings are saved through an API, and Firefox decides how settings are saved.

From <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Manifest_location>, shouldn't this be:

    [HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage\uBlock0@raymondhill.net]
    "path-to-the-manifest"

**Comment by BenKu82** [comment]
The solution was the key named uBlock0@raymondhill.net instead of a value. My fault.
The path to the file is simply in the default value.
Thank´s @gorhill  and @gwarser
