### ISSUE TITLE
Automatic filter creation for advanced users

### ISSUE THREAD

**Issue by Ro-Den** [uBlockOrigin/uBlock-issues#1058]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Is it possible to add automatic filter creation? Like, auto-clicking "Create' on specified domains. For advanced users only, of course. 

### A specific URL where the issue occurs

Any domain specified by the user in Advanced settings.

### Steps to Reproduce

1. Right-click
2. Click "Block element..."
3. Click "Create"

### Expected behavior:

    if ( bestCandidateFilter !== null && window.location.hostname.includes('.example.com') ) {
        onDialogClicked('create');
    }

### Actual behavior:

One has to click "Create" all the time even if the bestCandidateFilter is really the best one and always the best one in a particular domain.

### Your environment

* uBlock Origin version: 1.27
* Browser Name and version: Mozilla Firefox Quantum 68.8.0 ESR (64-bit)
* Operating System and version: Linux Kubuntu 20.04

**Comment by gorhill** [comment]
I don't see this as a good idea, the picker is a tool to **assist** filter creation, it's not to be used as a tool to make final decision on behalf of user.
