### ISSUE TITLE
New popup More and Less buttons do not always dissapear

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#1059]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When the advanced option `popupPanelLockedSections` is used, the `Less` button in the new popup do not disappear when all non-locked sections are hidden. 

Similarly, when the advanced option `popupPanelDisabledSections` is used, the `More` button in the new popup do not disappear when all non-disabled sections are shown. 

![image](https://user-images.githubusercontent.com/7283682/82520588-d039f600-9ae1-11ea-85ee-bc7d30b40222.png)

### A specific URL where the issue occurs

Advanced settings page. 

### Steps to Reproduce

1. Change `popupPanelLockedSections` to 3
2. Open the popup
3. Keep clicking `Less`

---

1. Change `popupPanelDisabledSections` to 3
2. Open the popup
3. Keep clicking `More`

### Expected behavior:

The `Less` button would disappear when all non-locked sections are hidden. 

---

The `More` button would disappear when all non-disabled sections are shown. 

### Actual behavior:

The `Less` button never disappears and stops responding to clicks when all non-locked sections are hidden. 

---

The `More` button never disappears and stops responding to clicks when all non-disabled sections are shown. 

### Your environment

* uBlock Origin version: 1.27.5b2
* Browser Name and version: Chrome 84
* Operating System and version: Windows 10

**Comment by jspenguin2017** [comment]
Also it looks like the Wiki is missing the documentation for the new advanced settings options.

**Comment by gorhill** [comment]
It's because section `b` (_blocked since install_ section) is a child of section `a` (stats section), so not disabling `b` means it's considered expandable even if not visible. Use `35` instead of `33`. Note that these advanced settings are still undocumented, so I am not going to add code to deal with the quirk you mention, I consider what I fixed to be already good enough, and the workaround is to use 0b11 (disable both `a` and `b` sections). Eventually if I make these settings official, I will probably use a more human friendly approach than bit vectors.

**Comment by gorhill** [comment]
Were there errors reported in browser console?

**Comment by gwarser** [comment]
I can reproduce. What I did:

- remove b9
- restart browser
- install 45.2
- add 
	```
	popupPanelDisabledSections 33
	popupPanelLockedSections 28
	```
    by pasting in last (42) line of advanced settings and apply (nice trick)
- open popup, click More/Less few times and then smash "More" many times (10? 20?) (not 100% sure about details in this point, I will try again)
- select above lines in advanced settings and delete them, then apply
- turn off uBO
- install b9 from releases page
- try popup again

**Comment by gorhill** [comment]
> by pasting in last (42) line of advanced settings and apply (nice trick)

I don't understand what you are saying there. You mean you paste the two lines at the end of advanced settings content?

**Comment by gwarser** [comment]
AAAnd I cannot reproduce again :(

Maybe it has something to do with number of clicks on buttons, or maybe some storage issue...

**Comment by gwarser** [comment]
Ok, I can repro again, but this time I did not reset the settings to default in 45.2 before update to b10. Popup is still broken even after resetting advanced settings to default.

**Comment by gorhill** [comment]
Weird, when I look at the popup panel content through the browser inspector, I still see CSS declaration from the previous uBO version, i.e. the one that was using `~=` to detect whether the `data-more` attribute contained specific letters. There is more such use in the latest version, so it seems to me the browser is using the wrong `popup-fenix.css` for unknown reasons.

**Comment by gwarser** [comment]
It's fine when updated without turning off uBO from add-on manager.
