### ISSUE TITLE
Minor visual glitch when the DOM Inspector scrolls horizontally

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#1060]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When the DOM Inspector scrolls horizontally, the white background stops at window width. 

![image](https://user-images.githubusercontent.com/7283682/82521241-59056180-9ae3-11ea-9673-0bbd59373e7b.png)

Also the DOM Inspector background does not go all the way to the bottom (related to https://github.com/uBlockOrigin/uBlock-issues/issues/1048 ?). Not sure if that is something that should be changed. 

### A specific URL where the issue occurs

`http://example.com/`

Note that this happens to real websites such as Twitter (log in required). 

### Steps to Reproduce

1. Add a really long cosmetic filter, for example: 
   ```
   example.com##h1:not(.looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong)
   ```
2. Open the DOM Inspector
3. Go to `http://example.com/`

### Expected behavior:

The background color of the DOM Inspector is always the same. 

### Actual behavior:

The white background of the DOM Inspector stops at window width

### Your environment

* uBlock Origin version: 1.27.5b2
* Browser Name and version: Chrome 84
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Unable to reproduce on Chromium 88.0.4324.182.
