### ISSUE TITLE
Subdomains are collapsed by default in the popup firewall

### ISSUE THREAD

**Issue by ThracianKnight1907** [uBlockOrigin/uBlock-issues#1064]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Subdomains are not collapsed by default, as in the attached picture. I tested in a new profile and it doesn't seem to happen there, but I still dont understand why it happens in this one. No settings were changed, (also no updates) and this behaviour only started today.

### A specific URL where the issue occurs

Everywhere, i tested it on github.com but it should happen on every site that has subdomains.

### Expected behavior:

Subdomains are not collapsed

### Actual behavior:

Subdomains are collapsed

### Your environment

* uBlock Origin version: 1.27.6
* Browser Name and version: firefox v 76.0.1
* Operating System and version: Fedora 32

![Captură de ecran de la 2020-05-22 09-33-00](https://user-images.githubusercontent.com/64692701/82647810-658ed480-9c1f-11ea-9f80-2062269e0a2f.jpg)

**Comment by uBlock-user** [comment]
You can manually un-collapse a manually collapsed domain, try that ?

**Comment by gorhill** [comment]
It's because you expanded all subdomains by clicking the _all_ cell, that is the only way to expand all subdomains.
