### ISSUE TITLE
[QUESTION] What's the allowed way to engage with ublockOrigin users?

### ISSUE THREAD

**Issue by MediaMaquina** [uBlockOrigin/uBlock-issues#1068]
I'm sorry the template is not related to my question.
I simply want to know what is an allowed method to display a message to ublock origin users? I understand that ublock is not supposed to block non intrusive messages.

Ideally i would like to write 2 lines on a sidebar div, not a popup. How can i do that? I don't want to learn it was added to filters later on.

https://twitter.com/gorhill/status/1072990091625328641

![Untitled](https://user-images.githubusercontent.com/8179611/82755045-6d8e7600-9dd1-11ea-9358-b485c21b8b0d.png)

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.

**Comment by gorhill** [comment]
The template which you deleted contains this line:

> - [ ] This is not a support issue or a question

This is not the place to ask question. Use <https://www.reddit.com/r/uBlockOrigin/> for this. Furthermore, your question is answer in the screenshot of the tweet you are referring to.

**Comment by MediaMaquina** [comment]
Thanks!

**Comment by MediaMaquina** [comment]
> The template which you deleted contains this line:
> 
> > * [ ]  This is not a support issue or a question
> 
> This is not the place to ask questions, use https://www.reddit.com/r/uBlockOrigin/ for this. Furthermore, your question is answered in the tweet you are referring to.

Just to be clear, ublock will not block the message based on its content? Not the technical method used to display the message?
