### ISSUE TITLE
Add example to wiki for :matches-css-before(content:"string")

### ISSUE THREAD

**Issue by stonecrusher** [uBlockOrigin/uBlock-issues#107]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using `:matches-css-before` procedural filter and targeting the `content` property, double quotes around the value are mandatory, no matter if the original css used single quotes.  
No quotes as used e.g. `:matches-css-before(position:absolute)` are *not* possible, even if the string contains no spaces.  
RegEx (wrapped in slashes) is not affected.

This should be resembled in the wiki either by adding an example for targeting `content` property or by an explanatory sentence. In my experience, `content` is one of the most targeted properties when dealing with `::before` and `::after`.

### A specific URL where the issue occurs

https://www.w3schools.com/cssref/tryit.asp?filename=trycss_sel_before

### Steps to Reproduce

1. Add  filter
```
w3schools.com##p:matches-css-before(content:Read this -)
w3schools.com##p:matches-css-before(content:'Read this -')
```
2. Drink coffee and wonder why it's not working even after reading the [docs](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-cssarg)

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.16.12
* Browser Name and version: Firefox release 61.0 x64
* Operating System and version: Win8.1 x64

**Comment by gwarser** [comment]
Testing.

**Comment by stonecrusher** [comment]
p.s.: If you're editing it anyway:  
Similar problem for `:has-text`.
The examples are only RegEx and contrary to `:matches-css` you are *not* allowed to use any quotes here, even if there are spaces in the string. Example:
`example.com##p:has-text(Lorem ipsum dolor)`

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters/_compare/03cd395a3b28dbd00c94f4723d2b4924f3f96077...00e707f69467b2aadaba976f3534caf99dd194aa

**Comment by uBlock-user** [comment]
> The given examples are only RegEx 

Added non RegEx example(https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjecthas-textneedle)

**Comment by gorhill** [comment]
> contrary to :matches-css you are not allowed to use any quotes here

These are two different operators, they should not be compared. `matches-css` looks up a CSS property, which itself may or may not contains quotes. `has-text` looks up a segment of text. uBO never requires or interprets quotes in arguments, they are always used literally.

**Comment by gorhill** [comment]
Side note: I can't make even a simple filter such as `w3schools.com##p` work inside the result area in the supplied [test URL](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_sel_before) with Chromium 66 or Chrome 69 -- while this works fine with Firefox.

**Comment by stonecrusher** [comment]
@uBlock-user Regarding `:has-text` please make it

```
example.com##body > div:last-of-type span:has-text(Promoted by)
```
to match the other examples and indicate spaces are ok?! If not... still better than before, thanks :-)


gorhill,  
Right, bad comparison.

Regarding `:matches-css-before`  
Great extra info about `getComputedStyle`. At least FF and Chrome seem both to give the result wrapped in quotes. Unfortunately I can't test Safari and Edge.

If all the big browsers have the same behaviour on `window.getComputedStyle` I still think an example under `:matches-css-before` is worth mentioning as `::before` and `::after` are the only pseudoselectors that have the `contains` css property with arbitrary string values anyway. That's the only place quotes are necessary? Although I'm not sure about html-colorcodes ([reddit issue](https://old.reddit.com/r/uBlockOrigin/comments/8v9iad/target_certain_background_color_by_matchescss/)).

Or maybe strip wrapping quotes entirely to match the uBO syntax-style?

---
hmm right, doesn't work in Chrome for me, too. But it's site-specific.
This similar filter `mv-werneck.de##.second:matches-css-before(content:"Anzeige")` for that [example page](http://root.mv-werneck.de/test.html) works both FF and Chrome.

**Comment by uBlock-user** [comment]
@stonecrusher https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters/_compare/d1ba03c3a7e4da00bbd7b9662ff53445f28e37cb...2f718c1fa9497b450ef26fd90f481ad631f1dcb6#diff-aacd202d9919e91da7a8cbce942741c8R39

**Comment by stonecrusher** [comment]
So far, so cool! I'm fine with that. Thanks guys!
uBO not working in that same-source iframe on w3schools is another [issue](https://github.com/uBlockOrigin/uBlock-issues/issues/107#issuecomment-401608189) if desired.
