### ISSUE TITLE
Element picker suggests unhelpful network rule

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uBlock-issues#1071]
### Prerequisites

- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element picker suggests unhelpful network rule

### A specific URL where the issue occurs

`https://www.historyextra.com/`

### Steps to Reproduce

1. Go to `https://www.historyextra.com/`
2. Use element picker to select the subscription banner (`https://images.immediate.co.uk/production/volatile/sites/7/2020/05/20Birthday_960x400-d33a3bd.jpg?quality=90&resize=960,400`)

### Expected behavior:

Element picker will suggest a helpful network rule

### Actual behavior:

Element picker suggests the rule `||*.*` (added to my filters as `||*.*$image`)

### Your environment

* uBlock Origin version: uBlock Origin 1.26.0
* Browser Name and version: Google Chrome 81.0.4044.138
* Operating System and version: Windows 10, version 1909

**Comment by uBlock-user** [comment]
Noticed such suggested rules after https://github.com/gorhill/uBlock/commit/bc700e691cf97b5e4d1f00e055191fbab4a1330e

**Comment by gorhill** [comment]
Looks like I am going to have to implement the parsing algorithm: <https://html.spec.whatwg.org/multipage/images.html#parsing-a-srcset-attribute>.

**Comment by peace2000** [comment]
I have seen this same issue as well.

For example:

https://www.iltalehti.fi/formulat/a/20d4830e-75e5-4329-b27e-bff57fd615fc

When using the element picker to an image, it suggests this kind of filter:
`||*.il*.fi/*`

![kuva](https://user-images.githubusercontent.com/17256841/83331378-a67d8d80-a29e-11ea-9706-8bfea762a3d4.png)

**Comment by gorhill** [comment]
Not strictly related to the issue here, but trying to test the fix I found that at the following URL:

    https://jalopnik.com/this-cassette-tape-based-navigation-system-from-1971-is-1826459978

The picker was unable to find matching elements when trying to create a filter from the first image in the article, despite the filter being valid. The issue was that the image element defines both a `src` and a `srcset` property, while the picker assumed these were mutually exclusive. This has been fixed at the same time.

**Comment by gwarser** [comment]
> The picker was unable to find matching elements when trying to create a filter from the first image in the article,

- `||*ja*.com/*` in 1.27.10 Firefox 78.0.1
- `||i.kinja-img.com/gawker-media/image/upload/c_*l_progressive,*q_80,w_*0/va8yr2vutfeosoklwfwc.png` in 1.28.1b5 Firefox 79.0b5

```
<img src="
data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" ... srcset="
https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_80,pg_1,q_80,w_80/va8yr2vutfeosoklwfwc.png 80w, 
https://i.kinja-img.com/gawker-media/image/upload/c_fit,fl_progressive,q_80,w_320/va8yr2vutfeosoklwfwc.png 320w, 
https://i.kinja-img.com/gawker-media/image/upload/c_fit,f_auto,fl_progressive,pg_1,q_80,w_470/va8yr2vutfeosoklwfwc.png 470w, 
https://i.kinja-img.com/gawker-media/image/upload/c_scale,f_auto,fl_progressive,pg_1,q_80,w_800/va8yr2vutfeosoklwfwc.png 800w, 
https://i.kinja-img.com/gawker-media/image/upload/c_scale,f_auto,fl_progressive,pg_1,q_80,w_1600/va8yr2vutfeosoklwfwc.png 1600w">
```

**Comment by Yuki2718** [comment]
A different case but will be suitable to this topic.
URL: `https://japanese.engadget.com/jp-2019-11-05-gopro-max-vlog.html`
Description: The picker suggests a meaningless network rule i.e. never-fired frame blocking rule. Adding this hides placeholder by injecting disaply: none !important but no network requests to the path ever occurs so no blocking.
Env: Firefox 80.0.1 + uBO 1.29.2 default settings
Steps to reproduce:
1. Visit the page, scroll down a bit, and you'll find the placeholder with iframe whose src="".
2. Choose it via picker and add the suggested rule. Open the logger.
3. Clear cache, reload the page and you'll see the request never occurs but the iframes are hidden as set to display: none !important.

![engadget](https://user-images.githubusercontent.com/58900598/93229671-cc796000-f7b1-11ea-8f6b-d68acf306b63.png)

**Comment by llacb47** [comment]
It happens when the `src` attribute gets removed/set to an empty string. You can see a minimal test case here: `https://llacb47.github.io/lazyloading/test.html`

**Comment by Yuki2718** [comment]
Oh, I see. So is it a known issue and won't be fixed?

**Comment by llacb47** [comment]
> Oh, I see. So is it a known issue and won't be fixed?

No, I was just trying to diagnose the issue. I think it should be fixed

**Comment by gwarser** [comment]
You may need to create new issue for this.

This looks like side effect of `about:blank` optimization - document URL is used for blank frames.

**Comment by Yuki2718** [comment]
> You may need to create new issue for this.

Okay.
 
> BTW I'm not sure it's even an issue.

Those who don't investigate enough will end up making invalid network rule(s) which may possibly cause false positive, so I think in this case the picker should suggest cosmetic rule.
