### ISSUE TITLE
Part of the menu panel hidden if display scale is set higher.

### ISSUE THREAD

**Issue by akulmehta** [uBlockOrigin/uBlock-issues#1072]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
I have multiple displays with different scales in Windows 10. I am using Firefox on the aurora channel (Developer edition). The menu appears fine on my 4k panel with 250% scaling (Windows display settings). But the menu panel appears cutoff (with the zap and other features missing from the bottom) on my 1080p panel with display scaling 150% (Windows display settings). See screenshot:

![image](https://user-images.githubusercontent.com/42812604/82940084-4e731e00-9f62-11ea-8547-cd720ec8715b.png)

 

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
https://google.com

### Steps to Reproduce

1. [First Step]
Have two monitors with different scaling preferably one with 4K display (250% display settings scale) and the second with 1080p display (150% display settings scale). 
2. [Second Step]
Open Firefox window in the 1080p display and try to access the menu options panel. It appears truncated.

### Expected behavior:

[What you expected to happen]
I expect to be able to see all the controls regardless of which display the browser is open on.

### Actual behavior:

[What actually happened]

I could not see the full options menu panel in my second display.

### Your environment

* uBlock Origin version: v1.27.6
* Browser Name and version: Firefox (77.0b9 (64-bit))
* Operating System and version: Windows 10 Pro (1809)

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435529

**Comment by gorhill** [comment]
To be clear: uBO's popup panel is just HTML/CSS/JS, and Firefox is responsible to render the HTML document, and the container in which uBO's panel is rendered is under the direct control of Firefox, and it is Firefox which set the size of that container, this is out of uBO's control.

**Comment by akulmehta** [comment]
I understand. Will post it on Firefox. Not sure to add to the bugzilla issue you pointed to or should I create a new one. Thanks.
