### ISSUE TITLE
Soft hyphens in language files

### ISSUE THREAD

**Issue by FTno** [uBlockOrigin/uBlock-issues#1074]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the thread about captions in the pop-up here: https://github.com/uBlockOrigin/uBlock-issues/issues/1036 soft hyphens were recommended for long words.
This doesn't work well in desktop browsers tooltips as seen in the screenshot below. This is from Firefox, but the same issue is in Chromium.

![ubo](https://user-images.githubusercontent.com/16176811/83004580-1de9bd80-a010-11ea-96ed-c69f0aa15064.png)

I run IcecatMobile on my android phone and the captions display correctly there.

I think it would be best to remove captions in the pop-up, and have tooltips also in mobile browsers with long tapping the icons to show them as is common in many apps (then it wouldn't be necessary to insert soft hyphens). I also think so many captions in a small place clutters the pop-up interface.
But if removing the captions is out of the question and fixing the issue as seen in the screenshot is troublesome, I would propose to have separat strings in the language files for those captions and the tooltips.

### A specific URL where the issue occurs

github.com (everywhere)

### Steps to Reproduce

1. Insert a soft hyphen in a language file
2. and look at tooltips in pop-up

### Expected behavior:

Code for soft hyphen being invisible

### Actual behavior:

Code for soft hyphen visible

### Your environment

* uBlock Origin version: 1.27.8
* Browser Name and version: Firefox ESR 68.8.0, ungoogled chromium 83.0.4103.61
* Operating System and version: Windows 7

**Comment by gorhill** [comment]
> I also think so many captions in a small place clutters the pop-up interface.

If you disable tooltips in _Settings_, the captions will not show.

**Comment by FTno** [comment]
Just tested v. 1.27.10
Screenshot of Firefox:

![ff](https://user-images.githubusercontent.com/16176811/83018487-b2124f80-a025-11ea-8eaa-2135e09662ca.png)

Screenshot ungoogled chromium:

![ch](https://user-images.githubusercontent.com/16176811/83018549-cb1b0080-a025-11ea-96b0-d875932d8a5b.png)


Firefox now displays correctly.
In ungoogled chromium the hyphens are visible, but I regard this a minor issue.

**Comment by gorhill** [comment]
> ungoogled chromium the hyphens are visible

If you think it's wrong, you will have to bring the issue to Chromium dev, soft hyphens are not supposed to be visible unless the word is broken in a new line.

**Comment by FTno** [comment]
> I do not see the issue with Chromium 81.0.4044.138 (linux)

Then the reason for visible hyphens may be some modifications they do in ungoogled chromium, and as this is not caused by uBlockOrigin I close this issue.

Thanks for fixing
