### ISSUE TITLE
ampproject_v0.js breaks dictionary.cambridge.org

### ISSUE THREAD

**Issue by nick75e** [uBlockOrigin/uBlock-issues#1078]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behaviour

### Description

`||cdn.ampproject.org/v0.js$script,redirect=ampproject.org/v0.js`
When this redirection is active, it makes the layout look weird.
It was working until recently (~a month ago).
Please update the JavaScript.

### A specific URL where the issue occurs

https://dictionary.cambridge.org/dictionary/english/reckon

### Steps to Reproduce

Just apply the aforementioned redirection

### Expected behaviour:

Normal layout

### Actual behaviour:

Wonky and difficult layout to navigate

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox 76
* Operating System and version: Linux Mint 19.3

**Comment by gorhill** [comment]
> `||cdn.ampproject.org/v0.js$script,redirect=ampproject.org/v0.js`

That filter is not part of any filter list enabled by default.

The purpose of `ampproject.org/v0.js`, as per [documentation](https://github.com/gorhill/uBlock/wiki/Resources-Library#ampproject_v0js-):

> Removes animation (artificial 8s delay) added to desktop pages supporting AMP, when ampproject.org scripts are blocked.

I confirm the animation is removed, as expected.

The site breaks when merely blocking `//cdn.ampproject.org/v0.js`, so it's not caused by the scriptlet, so this is a filter issue.
