### ISSUE TITLE
Dashboard: UI performance regression

### ISSUE THREAD

**Issue by goodgerster** [uBlockOrigin/uBlock-issues#1079]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin *(v1.27.10 – bfg)*
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After updating from uBlock₀ version 1.26 to 1.27 on Chromium, the dashboard UI paints many versions of itself in one or two seconds, both on its initial load and whenever I change tabs (dashboard UI tabs, not browser tabs). The 1.26 dashboard UI's loading was both nearly instant and nearly atomic.

### A specific URL where the issue occurs

`chrome-extension://…/dashboard.html`

### Steps to Reproduce

1. Open the uBlock₀ dashboard to the Settings tab.
2. Switch to any other dashboard tab.
3. Switch back to the Settings tab.

### Expected behavior:

On opening the dashboard in a new browser tab, the initially blank page is visibly (re)painted exactly four times:
 1. add the tab bar;
 2. add the tab content, within 50 ms;
 3. prepend the cloud sync status bar (with ellipses as content) to the tab content;
 4. replace the cloud sync status bar with real content, upon the return of an asynchronous query call.

On changing tabs within the dashboard, the same happens, except that the first change removes everything but the tab bar.

### Actual behavior:

* On opening the dashboard, the initially blank page is visibly (re)painted many (5–15) times, with a total load time of one or two seconds:
  1. add the tab bar;
  2. add nearly invisible tab content (this includes empty `<button>` elements which are rendered as grey rectangles);
  3. several times for the following in no particular order:
    * add icon (one reflow & repaint per icon?)
    * replace invisible text with webfonted copy (once each for at least two webfonts?)
  4. the same cloud sync status bar repaints from before.

* On changing tabs within the dashboard, the same happens, except that the first change removes everything but the tab bar.

My regular Chromium profile has several other extensions and its uBlock₀ installation has many dynamic-filtering rules. I tried a newly created Chromium profile wherein uBlock₀ with the default settings was the only extension. In the test environment, the uBlock₀ dashboard took around 50% less time to load, but the basic problem persists.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Chromium 83.0.4103.61, with fully hardware-accelerated rasterization ([chrome://gpu screenshot](https://user-images.githubusercontent.com/9383058/83326304-44f3f980-a273-11ea-894f-0873ac1fd2b4.png))
* Operating System and version: Arch Linux: kernel 5.6.14-arch1 (default); KDE Plasma Desktop 5.18.5
* Hardware: ThinkPad T580 (i5-8250U, 16 GiB RAM, UHD Graphics 620)

### Analysis

A few hours of research, including the best profiling interpretation I could do with the Chromium developer tools (focused on `dashboard.html` and `dyna-rules.html`), turned up several notable things.

Caveats: I am not a JavaScript expert, I could have missed something, and I do not know which (if any) of these are specific to uBlock₀ 1.27.

#### Performance: probed

Although `domcontentloaded` and ‘Load’ (`onload`?) are both far earlier, ‘Finish’ (??) on `dashboard.html#dyna-rules.html` occurs around 1.75–1.9 s with cache enabled.

`dyna-rules.html` spends only 12–18 ms painting. I infer that the slow overall performance is probably not a graphics problem with my browser. But it does spend nearly 300 ms on rendering (layout, style recalculation, update layer tree) and over 450 ms on JavaScript, including 100 ms of compilation.

#### Webfonts: weirdness

`dashboard.html` loads Metropolis SemiBold as directed in `common.css` and exhibits no ‘flash of no text’.

For the iframe (and the same pages loaded directly), the webfont files’ initiator is for some reason `codemirror.js`. The browser seems to be waiting for JavaScript to finish before it loads the webfonts, which delays font loading by half a second. I infer that this delay busts the browser’s [font block period](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#The_font_display_timeline). I have been unable to diagnose this further, but I assume none of this is intentional.

I observe that you have already added an toggle for the webfonts in the dev build (#1044), so I will not suggest you add a toggle for the webfonts. Thanks for doing that.

`fontawesome-webfont.ttf` is apparently unused but is loaded anyway, once by `dashboard.html` and again by the iframed pages.

#### Icons: loading and loading and loading and loading

The icons’ `svg` elements have no `height` and `width` attributes, which are necessary for (at least) Chromium to determine the size of their CSS layout boxes before their rasterized contents are available. Therefore, it will reflow the page once for each icon, when that icon finishes loading:
* the icons’ `svg` elements’ CSS `width` and their containing `div`s’ CSS `height` are both explicit, but this is apparently not sufficient
* the icons all come from the same SVG file, but Chromium nonetheless loads them separately (showing one HTTP request to `fontawesome-defs.svg` per icon)

I expect that setting an arbitrary `height` and an aspect-appropriate `width` on each `svg` element will prevent this excess reflowing, while not affecting the actual rendering size:
```html
<svg class="fa-icon_cloud-download" height="32px" width="32px">
  <use href="/img/fontawesome/fontawesome-defs.svg#cloud-download"></use>
</svg>
```

#### JavaScript: making it less so

Loading `dyna-rules.html` spends a lot of time compiling and executing JavaScript, of which about half seems to be spent on/in the gigantic CodeMirror library, making it a target for reduction. All the distributed JavaScript files appear to be ‘raw’ versions; specifically, the copies of CodeMirror and its addons appear to come straight from NPM.

There is obviously little point in reducing the file size or the number of HTTP requests made to the local file system by uBlock₀; but it might still benefit from an optimizing compiler. [An old compression-related page on the CodeMirror website](https://codemirror.net/1/compress.html) endorses file concatenation and compression, and suggests that CM should survive rewriting by Google Closure. Note: I cannot tell whether any substantial improvement would result, and I do not wish to impugn your build process.

#### Closing

Thanks for reading my report. I’ve tried hard to make it comprehensive, precise, accurate, and respectful.

Please let me know if this is too much stuff, in which case I'll split the report.

**Comment by uBlock-user** [comment]
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from Firefox Profiler/Chromium Profiler + fully substantiated analysis supporting the claim.

You're missing that.

**Comment by gorhill** [comment]
> the dashboard UI paints many versions of itself in one or two seconds

Unable to reproduce.

> whenever I change tabs

Each tab content is an iframe, and the iframe's `src` property is set to the new pane each time you select a new one -- this has always been the case, this is not specific to 1.27.0.

**Comment by gorhill** [comment]
I profiled selecting each pane one after another and then back, starting with the _Settings_ pane. Results:

![a](https://user-images.githubusercontent.com/585534/83332348-b8443e00-a268-11ea-9eae-b51adf6e34af.png)

- Filter lists: 375 ms
- My filters: 233 ms
- My rules: 180 ms
- Whitelist: 146 ms
- About: 80 ms
- Whitelist: 135 ms
- My rules: 149 ms
- My filters: 158 ms
- Filter lists: 291 ms
- Settings: 141 ms

> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from Firefox Profiler/Chromium Profiler + fully substantiated analysis supporting the claim.
