### ISSUE TITLE
Logger window is behaving in way that makes using it problematic.

### ISSUE THREAD

**Issue by matkoniecz** [uBlockOrigin/uBlock-issues#108]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Logger window is behaving in way that makes using it problematic.

- it opens as a blank window https://user-images.githubusercontent.com/899988/42218774-f3323702-7ec9-11e8-8bcb-ff4162f7dbb1.png
- when maximized it overlays usual browser window even after clicking on it on main browser window in window list

### A specific URL where the issue occurs

not applicable

### Steps to Reproduce

1. open logger tool

### Expected behavior:

Old behavior when it opened in a new tab was ideal.

### Actual behavior:

- it opens as a blank window https://user-images.githubusercontent.com/899988/42218774-f3323702-7ec9-11e8-8bcb-ff4162f7dbb1.png
- when maximized it overlays usual browser window even after clicking on it on main browser window in window list

### Your environment

* uBlock Origin version: 1.16.12
* Browser Name and version: Firefox 60.0.2 (64-bit)
* Operating System and version: Lubuntu 16.04.01

**Comment by gorhill** [comment]
Blank popup window is a Firefox issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1426405>. workaround: slightly resize the popup.

Always-on-top popup is a Firefox-specific behavior.

**Comment by uBlock-user** [comment]
Can't reproduce any of those on Windows 10.

**Comment by uBlock-user** [comment]
Not a workaround, that's how it's always been. The behavior was changed recently and switched to a separate Window, instead of tab, but only for new installations of the extension, existing users shouldn't be affected.

**Comment by gorhill** [comment]
> Are you considering adding workarounds for this Firefox bugs

No. The only workaround I can think for the popup window is to not ask for a "popup" type window, but this would cause the logger to become part of the session, which is something I do not want -- it really needs to open only after uBO is fully launched -- the same way dev console do not open automatically at Firefox launch time.

**Comment by matkoniecz** [comment]
In that case I will close it (feel free to reopen)

**Comment by hackel** [comment]
> The behavior was changed recently and switched to a separate Window, instead of tab, but only for new installations of the extension, existing users shouldn't be affected.

Is there a preference that can be set for new installations to revert to the old behaviour until this gets fixed upstream?  Having the logger in a modal window makes it really difficult to use.

**Comment by gwarser** [comment]
Is this issue is fixed? Nothing new on Bugzilla, but works for me on all channels.

**Comment by matkoniecz** [comment]
See comment above " There's nothing to fix, this was done on purpose by gorhill. To revert to old behaviour - https://github.com/gorhill/uBlock/wiki/The-logger#tip "

**Comment by gwarser** [comment]
I mean Firefox "blank window" and "window on top" issue.

**Comment by matkoniecz** [comment]
I would ask about Firefox bugs on a Firefox bug tracker.
