### ISSUE TITLE
Interface change for selecting zapper mode

### ISSUE THREAD

**Issue by heurbar** [uBlockOrigin/uBlock-issues#1084]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

Recently changed from v1.22 to v1.27.  Notice the UI changed in the newest version.  The new location in the UI for selecting the zapper mode option is less ergonomically convenient.

When select the uBlock icon in browser, in v1.22 the icon to select zapper mode appeared directly under under the Click to Disable button.  In v1.27 the select zapper mode icon is below the list of blocked statistics.

I use the zapper mode all (and I do me ALL) the time to remove unwanted elements before saving/printing a site to a PDF file.  Find zapper mode especially useful to remove floating elements or embedded video blocks from sites before saving to PDF. 

Placing the zapper icon near the top of the UI saved on mouse movements to select the zapper mode. 

Please consider returning the zapper mode selection icon to a position just below the disable button like it was in v1.22.  My mouse and wrists will appreciate less strain on the movement to select zapper mode.

The zapper mode is such a useful option, it is a shame to not highlight it near the top of the UI.

### A specific URL where the issue occurs
No URL problem - just a request to change the uBlock Origin UI

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Select the uBlock Origin icon in the web browser
2.The UI opens and shows the disabled button followed by some blocking statistic followed by a row of icons for tool selection
3. [and so on...]

### Expected behavior:
Return the tool selection icon row to just below the Disable Button.  Makes for easier ergonomics.
See the location in the older v1.22 UI

![version 1 22 UI](https://user-images.githubusercontent.com/54112646/83343536-62e84b00-a2c1-11ea-8032-b3d7ff3dd7b0.png)

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.27
* Browser Name and version: Vivaldi v3.0
* Operating System and version: Windows 10 bld 1909

**Comment by gorhill** [comment]
I explained the reason for the changes -- the release notes will lead you to the motivation for the change: <https://github.com/uBlockOrigin/uBlock-issues/issues/1027#issuecomment-629561754>. I decline.

Just assign a keyboard shortcut to the zapper if you use it often.

**Comment by gwarser** [comment]
If you don't care about statistics you can set `popupPanelDisabledSections 1` in advanced settings, which will move picker button up.

**Comment by heurbar** [comment]
@gwarser  Thanks for the great tip.   Tried it out.  The  zapper mode picker is back near the top where I like it for how I use it to remove elements from pages before saving as PDF.

Noticed you author the help page for the advance settings.  Thanks for providing those details.
