### ISSUE TITLE
Mouseover help texts contain HTML tags

### ISSUE THREAD

**Issue by terr72** [uBlockOrigin/uBlock-issues#1086]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This might be related to the german help texts only, but when you hover over them with your mouse, they show HTML tags.

### A specific URL where the issue occurs

dashboard.html#3p-filters.html

### Steps to Reproduce

1. Go the the dashboard filter settings.
2. Hover with your mouse above the question mark symbols for the cosmetic filter checkmarks.

### Expected behavior:

Raw text or formatted text should show up.

### Actual behavior:

HTML tags can be seen, see the attached screenshot.
![help_text_with_tags](https://user-images.githubusercontent.com/23163919/83362878-166e3f80-a395-11ea-91c6-6d860cc2775c.png)

### Your environment

* uBlock Origin version: 1.27.4
* Browser Name and version: FF 76
* Operating System and version: Ubuntu 18.04LTS

**Comment by gorhill** [comment]
Translation issues are to be handled on Crowdin, by the translators, <https://crowdin.com/translate/ublock/13/enca-de>. The original English version does not have these HTML tags.

**Comment by terr72** [comment]
@gorhill: OK, I fixed the translations at Crowdin.
