### ISSUE TITLE
uBO's network filter creator wants to add an unneeded wildcard

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1088]
###Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
    - [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO's network filter creator wants to add an unneeded wildcard when creating a rule through the network requests logger.

![2020-06-01 19_09_49-Greenshot](https://user-images.githubusercontent.com/17256841/83428903-e5951580-a43b-11ea-8309-6bfb1ad896e5.png)

![2020-06-01 19_10_00-Greenshot](https://user-images.githubusercontent.com/17256841/83428925-ec238d00-a43b-11ea-9642-9f1e22e2c8e7.png)

### A specific URL where the issue occurs

Any, sample page: https://github.com/

### Steps to Reproduce

1. [Open the network requests logger]
2. [Click a request that has a long url with many slashes on it]
3. [Shorten the rule to the previous slash by using automatic suggestions (see the pic) and uBO suggests adding a wildcard to the rule]

### Expected behavior:

Wildcard would not be suggested.

### Actual behavior:

An unnecessary wildcard was suggested.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox 76.0.1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
> Wildcard would not be suggested.

By-design. Always has been this way.

**Comment by peace2000** [comment]
Oh. How so?
