### ISSUE TITLE
Improve parsing URL from strict blocked domains

### ISSUE THREAD

**Issue by Germs2004** [uBlockOrigin/uBlock-issues#1091]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock tries to parse the URL argument from a strict-blocked URL ([source](https://github.com/gorhill/uBlock/wiki/Strict-blocking)).  However, when the URL is HTML encoded, uBlock fails to parse it, at least in this example.

To see what HTTP URL Encoding looks like, play with this tool: [](https://www.w3schools.com/tags/ref_urlencode.ASP)

### A specific URL where the issue occurs

https://rd.bizrate.com/rd2?t=https%3A%2F%2Fwww.northerntool.com%2Fshop%2Ftools%2Fproduct_200702083_200702083%3Futm_source%3DCSE%26utm_medium%3DShopzilla&mid=31891&dMid=31891&tokenId=18P&bId=314&bidType=11&rf_code=af1&oid=8746543656&af_id=678546&af_rid=ffd61189cf96c743a797f516a0a72311b73a6a6d&cobrand=1&af_placement_id=1&afCampaignId=i65n1w11v9ao0d9iph8RMkqcmPeHXW2g&af_assettype_id=14&af_creative_id=2913

### Steps to Reproduce

1. Go to this page: https://www.dealnews.com/Poly-Service-Cart-for-55-pickup-at-Northern-Tool/18413350.html
2. Click the link that says "Buy Now at Northern Tool"
3. You should then see the uBlock blocked page, which says "Found in: Peter Lowe’s Ad and tracking server list"
4. That blocked page does not show the encoded URL within the attempted URL.

Attempted URL = https://rd.bizrate.com/rd2?t=https%3A%2F%2Fwww.northerntool.com%2Fshop%2Ftools%2Fproduct_200702083_200702083%3Futm_source%3DCSE%26utm_medium%3DShopzilla&mid=31891&dMid=31891&tokenId=18P&bId=314&bidType=11&rf_code=af1&oid=8746543656&af_id=678546&af_rid=ffd61189cf96c743a797f516a0a72311b73a6a6d&cobrand=1&af_placement_id=1&afCampaignId=i65n1w11v9ao0d9iph8RMkqcmPeHXW2g&af_assettype_id=14&af_creative_id=2913

Encoded URL that uBlock should parse out: https://www.northerntool.com/shop/tools/product_200702083_200702083?utm_source=CSE&utm_medium=Shopzilla

### Expected behavior:

The uBlock page should include a link to the encoded URL that I can click to bypass the ad site.

### Actual behavior:

uBlock failed to detect the encoded URL, so I have to click "Temporarily Allow" in order to proceed to the desired page.

![image](https://user-images.githubusercontent.com/5519340/83667056-d75e0b00-a59b-11ea-871b-b1c61bf68d0a.png)

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Chrome 83.0.4103.61
* Operating System and version: Windows 10 1909

**Comment by llacb47** [comment]
Click the magnifying glass...

**Comment by Germs2004** [comment]
I never noticed that tiny magnifying glass!  I guess that solves this ticket.  Thank you
