### ISSUE TITLE
Easier to use strict-blocked page

### ISSUE THREAD

**Issue by Germs2004** [uBlockOrigin/uBlock-issues#1092]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I try to visit a strict-blocked domain, uBlock takes me to a strict-blocked warning page.  The page has a small magnifying glass, which is easy to miss.  When the glass is expanded, it's great to see the parsed URLs from the parameters, but the URL text is small and close together, it's hard to read and click on accurately.

I suggest some minor layout improvements to that page:

1) Remove the magnifying glass icon

2) Move the parameter details, which are currently collapsed and accessed with the magnifying glass, to a new div with the standard "+" symbol to expand that div.  The div could be labelled "parameters".

3) After uBlock parses all the parameters, if it detects that any of them are valid URLs, this page should add an additional div labelled "links parsed from the blocked URL" and put the parsed URLs right there for the user to immediately click on.  The URLs should follow the browser's default CSS styles so it's more obvious that they are clickable links.

### A specific URL where the issue occurs

https://rd.bizrate.com/rd2?t=https%3A%2F%2Fwww.northerntool.com%2Fshop%2Ftools%2Fproduct_200702083_200702083%3Futm_source%3DCSE%26utm_medium%3DShopzilla&mid=31891&dMid=31891&tokenId=18P&bId=314&bidType=11&rf_code=af1&oid=8746543656&af_id=678546&af_rid=ffd61189cf96c743a797f516a0a72311b73a6a6d&cobrand=1&af_placement_id=1&afCampaignId=i65n1w11v9ao0d9iph8RMkqcmPeHXW2g&af_assettype_id=14&af_creative_id=2913

### Expected behavior:

The uBlock page should display a clean, obvious link to the parsed URL that I can click to bypass the ad site.

### Actual behavior:

uBlock hides the parsed URL behind a small magnifying glass, and the link is closely surrounded by other distracting text.

Example of a faster UI where the user can immediately click a parsed URL:
![image](https://user-images.githubusercontent.com/5519340/83670712-9668f500-a5a1-11ea-9396-da94022ef177.png)

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Chrome 83.0.4103.61
* Operating System and version: Windows 10 1909

**Comment by gorhill** [comment]
I decline to redesign the document-blocked page. However I agree that the magnifier has become too small following the last redesign of the page. The fix is to ensure the size of the magnifier is set according to the page's default font size.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/88489039-0daf7980-cf92-11ea-9052-3af3cd88d166.png)
![image](https://user-images.githubusercontent.com/886325/88489045-186a0e80-cf92-11ea-9e20-4e0d9563715d.png)
