### ISSUE TITLE
The right scroll bar is redundant

### ISSUE THREAD

**Issue by xinggsf** [uBlockOrigin/uBlock-issues#1095]
UBO dash board, [as the figure shows](https://fj.kafan.cn/attachment/forum/202006/04/165204ql5yqzux24sph2py.png.thumb.jpg)
### environment

* uBlock Origin version: v1.27.10
* Browser Name and version: Chromium 80.0.3987.163
* Operating System and version: win8 x64
* DPI: 1920 * 1080

**Comment by uBlock-user** [comment]
Happening on the Chinese locale ?

**Comment by xinggsf** [comment]
No. Firefox is ok!

**Comment by xinggsf** [comment]
I guess CSS file:
```css
overflow-y: auto
````
Should be like this：
```css
overflow-y: auto
````

**Comment by gwarser** [comment]
Small screen? What is your screen resolution?

**Comment by xinggsf** [comment]
> Small screen? What is your screen resolution?
1920 * 1080

**Comment by gorhill** [comment]
> I guess CSS file:

Which line of which CSS file? On my side, I see `hidden` at line 8 of `popup-fenix.css`.

**Comment by xinggsf** [comment]
@gwarser @gorhill 
Matter was settled! thank
```
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/advanced-settings.html
uiFlavor classic
```

**Comment by gorhill** [comment]
Still, I would like to understand where that `overflow-y: auto` CSS rule comes from. Can you share?

**Comment by xinggsf** [comment]
> Still, I would like to understand where that `overflow-y: auto` CSS rule comes from. Can you share?
```css
:root.portrait body {
    overflow-y: auto;
    width: 100%;
    }
```

**Comment by gorhill** [comment]
The CSS rule you are showing occurs only when the popup is in portrait mode, which was clearly not the case in screenshot -- the firewall pane was shown on the left of the basic pane, while in portrait mode it appears _under_ the basic pane. I can't make sense of what is going on here. Did you use the browser inspector to find out where the `overflow-y: auto` comes from?

**Comment by xinggsf** [comment]
> Did you use the browser inspector to find out where the `overflow-y: auto` comes from?

It's my guess.

**Comment by gorhill** [comment]
> It's my guess

Ok but I just want to know what is actually happening. Can you share as I did above? I don't understand how you could end up with an `overflow-y: auto` rule, I want to see from where it originates.

**Comment by xinggsf** [comment]
> If it's not from the `body` element, maybe it's from the `html` element?
  @gorhill 
[console picture](https://fj.kafan.cn/attachment/forum/202006/05/002833yrevoef4o1oyztmr.png).  [dash picture](https://fj.kafan.cn/attachment/forum/202006/05/002849l0b8v6t0bpl6pnv4.png) 
Do You need popup-fenix.css file?

**Comment by xinggsf** [comment]
@gorhill 
I try add some code to popup-fenix.css file:
```css
:root { overflow-y: hidden; }
```
But it's invalid.

**Comment by gorhill** [comment]
Where did you get your Chromium 80 build? It seems to me the scrollbar might be coming from the popup window itself in which uBO's panel is embedded.

**Comment by xinggsf** [comment]
> Where did you get your Chromium 80 build? It seems to me the scrollbar might be coming from the popup window itself in which uBO's panel is embedded.

[Cent browser](https://www.centbrowser.com/history.html). [64-bit Portable](http://static.centbrowser.com/installer_64/centbrowser_4.2.10.171_x64_portable.exe) version

**Comment by gorhill** [comment]
Does it help if you set `popupPanelHeightMode` to `1` in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings)?

**Comment by xinggsf** [comment]
> Does it help if you set `popupPanelHeightMode` to `1` in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings)?

popupPanelHeightMode is invalid! Red font alert!

Are you see dash picture? Right scroll bar work on “#panes” div! "#extraTools" div is covered!

**Comment by gorhill** [comment]
> popupPanelHeightMode is invalid! Red font alert!

Yes sorry, I had forgotten it's only in the dev build: <https://github.com/gorhill/uBlock/releases/tag/1.27.11b3>.
