### ISSUE TITLE
Allow saving newlines in whitelist

### ISSUE THREAD

**Issue by stdedos** [uBlockOrigin/uBlock-issues#1097]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Allow saving newlines in whitelist

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. ![image](https://user-images.githubusercontent.com/133706/83953099-4c546d80-a846-11ea-8936-2527d34f77bb.png)
2. Apply Changes
3. ![image](https://user-images.githubusercontent.com/133706/83953106-5c6c4d00-a846-11ea-894e-0744e5f780d0.png)

### Expected behavior:

[What you expected to happen]
Be allowed to save newlines in whitelist

### Actual behavior:

[What actually happened]
Whitespace is truncated on save

### Your environment

* uBlock Origin version: v1.27.10
* Browser Name and version: 83.0.4103.97
* Operating System and version: Win10

**Comment by gorhill** [comment]
What is the reason? A new line is always there in the Whitelist pane, why would you mind the internal format uBO uses?

**Comment by stdedos** [comment]
I periodically like to review and clean up my lists (like now), and I don't like seeing all of the text clumped together like a big blob.

Maybe with few exceptions (which I cannot think any right now), I prefer all the random text blobs, wherever they may be saved, to be like my source code: Legible, good-looking, and documented.

Auto-truncating empty lines reminds me more of js minification, than nicely formatted source code.

**Comment by gorhill** [comment]
Please fill in repro steps, this way I won't have to guess what you are referring to exactly.

**Comment by stdedos** [comment]
👍 done

**Comment by gorhill** [comment]
I am going to decline this for the same reason I declined the following issue: <https://github.com/gorhill/uBlock/issues/2627#issuecomment-302283306>.
