### ISSUE TITLE
Focus can be stealed from Element Picker dialog preventing editing

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1098]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On `https://www.carrefour.pl/` cookie consent dialog seems to be stealing focus from Picker edit box. Text cannot be selected, edited.

https://streamable.com/lajxyh

### A specific URL where the issue occurs

`https://www.carrefour.pl/`

### Steps to Reproduce

1. load page
2. consent dialog should appear
3. use Picker to select it
3. try editing proposed filter text

### Expected behavior:

Editable text.

### Actual behavior:

Cursor is removed from text box.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: 83.0.4103.61
* Operating System and version: Manjaro KDE

***

`carrefour.pl##+js(nosiif, t())` filter make it work.

Noticed by @krystian3w https://github.com/MajkiIT/polish-ads-filter/issues/16404#issuecomment-638651124

**Comment by llacb47** [comment]
What can be done? Can uBo "steal" focus back?

**Comment by uBlock-user** [comment]
> Cursor is removed from text box.

Set `cursor:` CSS property for the text element ?

**Comment by gwarser** [comment]
I see certificate errors when accessing directly, going through `zakupycodzienne.carrefour.pl` works.

Interesting - in Firefox text can be selected, but it's made grey immediately.

Focus is moved to other element - even if you start typing, text will (in theory) appear in other focused element.

**Comment by krystian3w** [comment]
Strong workaround, pop-up with picker interfec instead iframe above website code.

**Comment by gwarser** [comment]
> browser pop-up with picker interface instead iframe above website code

ABP is doing this.

Above issue also affects AdGuard.

**Comment by gorhill** [comment]
> ABP is doing this.

I don't want to go this route, if I remember this leads to its own set of issues.

If the fix is to steal back the focus, then it can't be fixed in uBO, fighting with a page like is pointless -- there is already code in there to give the focus to the picker.

**Comment by gorhill** [comment]
I wanted to give a last ditch try but now the site `https://www.carrefour.pl/` says "Access denied".

**Comment by uBlock-user** [comment]
Use Polish VPN.

**Comment by llacb47** [comment]
You could also try this: `https://via.hypothes.is/https://www.carrefour.pl/`

**Comment by gorhill** [comment]
Alright, marking as wontfix -- I don't want the picker to be in a separate popup window as ABP does, being embedded as it is currently is the most convenient, not to be sacrificed because of that one site.

**Comment by gwarser** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/20600

**Comment by krystian3w** [comment]
I suppose all CMS with classes `.jssXYZ` - YXZ as compressed numbers steal event.

This is maybe framework `Next.js` due react no generate these classes on e.g. Instagram.

**Comment by krystian3w** [comment]
I suppose  native dialog pop-ups generate new troubles:

 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop

-  element picker is under that opened element (similar to stole events for textarea)
-  background by `::backdrop` is untouchable

**Comment by siriusgithub** [comment]
Having an issue with ::backdrop right now as well. Maybe block that element type entirely? Can't think of a website where it's used legitimately.
