### ISSUE TITLE
Buttons do not feel 'clicky' on blocked page

### ISSUE THREAD

**Issue by domdomegg** [uBlockOrigin/uBlock-issues#1099]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When hovering over buttons ('Go back', 'Temporarily', 'Permanently') the cursor does not change to indicate they can be clicked, which to me feels really unnatural. This is a proposed UX improvement to set the cursor to pointer on those buttons to make them feel more 'clicky'.

Yes, I know this is a tiny nitpick and I'm probably crazy for raising this, but it's been grinding on me a bit with the new design.

![image](https://user-images.githubusercontent.com/4953590/83934327-0a74ea00-a7a8-11ea-8dcd-5825c5cde565.png)

### A specific URL where the issue occurs

https://ad.doubleclick.net/ddm/clk/1

### Steps to Reproduce

1. Open warning/blocked page (see screenshot)
2. Hover the cursor over one of the buttons

### Expected behavior:

The cursor changes to a pointer, indicating the button can be clicked

### Actual behavior:

The cursor does not change

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Google Chrome 83.0.4103.61 (Official Build) (64-bit) (cohort: Stable)
* Operating System and version:Windows 10 OS Version 1909 (Build 18363.836)

### Fix

Simply adding the cursor property to the button will fix this:

https://github.com/gorhill/uBlock/compare/master...domdomegg:domdomegg-cursor-pointer-css

**Comment by uBlock-user** [comment]
I reported this in team discussion earlier and gorhill's response --

![Capture](https://user-images.githubusercontent.com/21290713/83937423-0a95d980-a7ea-11ea-9525-382edb2b90b3.PNG)
