### ISSUE TITLE
rawgit

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#110]
https://gist.github.com/KonoromiHimaries/c29db87916d0185229f40e6925953b6b
https://github.com/gorhill/uBlock/tree/master/assets
https://github.com/gorhill/uBlock/issues/3406#issuecomment-355748757

**Comment by uBlock-user** [comment]
> https://gist.github.com/KonoromiHimaries/c29db87916d0185229f40e6925953b6b
https://github.com/gorhill/uBlock/tree/master/assets
gorhill/uBlock#3406 (comment)

Put back the issue template and properly form a report or a suggestion, nobody's going to read your mind.

**Comment by KonoromiHimaries** [comment]
@uBlock-user i don't have access to pull request in gorhill ublock repo
<https://github.com/KonoromiHimaries/uBlock/commit/3dd8fc72e0cf26fd61329a774160ae077681beba>
