### ISSUE TITLE
Some uBlock Panel icons not visible in landscape

### ISSUE THREAD

**Issue by tkzv** [uBlockOrigin/uBlock-issues#1100]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In Android Firefox with large fonts and landscape screen orientation uBlock Panel does not fit the screen and cannot be scrolled.

### A specific URL where the issue occurs

Everywhere, e.g. https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. At any webpage open "uBlock Origin" from the menu.
2. Try to use "eye dropper" tool — it's unavailable, and the page cannot be scrolled to reach it.

### Expected behavior:

In the earlier versions the icon was visible at any text size and screen orientation.

### Actual behavior:

"Eye dropper" icon is unavailable, and the page cannot be scrolled to reach it.
![Screenshot_2020-06-06-16-28-32-935](https://user-images.githubusercontent.com/4944180/83946071-60cd4180-a817-11ea-9ae2-34e85bd3bea7.jpeg)

It does appear in the landscape mode, but repeated switching between portrait and landscape is inconvenient.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox 68.9.0
* Operating System and version: Android 7.1.1, for Lenovo TB-X704L pad (resolution 1920x1200, maximum text size).

**Comment by gwarser** [comment]
UI did not even switched to mobile version.

**Comment by gorhill** [comment]
You are using the desktop version of Firefox, so I don't understand that on a 1920x1200 display you get such a small viewport. I currently have 1920x1080 and I have plenty of space in the viewport to wholly show the popup panel.

**Comment by gorhill** [comment]
> In the earlier versions the icon was visible at any text size and screen orientation

With the earlier versions, were per-site switch icons truncated?

**Comment by tkzv** [comment]
> UI did not even switched to mobile version.

What do you mean? Should it look different?

> Wondering if switching `uiFlavor` to `fenix` will work - https://github.com/gorhill/uBlock/wiki/Advanced-settings#uiflavor

Switched and restarted Firefox. No changes.

> You are using the desktop version of Firefox, so I don't understand that on a 1920x1200 display you get such a small viewport. I currently have 1920x1080 and I have plenty of space in the viewport to wholly show the popup panel.

Firefox is set to use system fonts and system font is set to largest.

And what do you mean by "desktop version of Firefox"? As opposed to Fenix?

> > In the earlier versions the icon was visible at any text size and screen orientation
> 
> With the earlier versions, were per-site switch icons truncated?

No, they were visible. I don't remember exactly, maybe the icons were smaller.

**Comment by gorhill** [comment]
> Firefox is set to use system fonts and system font is set to largest

Then that is going to be an issue with more than just uBO -- so I can't consider this a uBO issue.

> No, they were visible

Can you provide a screenshot of this?

**Comment by gorhill** [comment]
I won't be providing a fix for this, I do not consider this is a uBO issue, this is a case of extreme settings which are problematic for more than just uBO. I opened your screenshot in its own tab and set it to 1:1 to have a sense of the size you are seeing and this is just way huge. If you do not want to change your setting, I suggest you modify `popupFontSize` in advanced settings.

**Comment by gwarser** [comment]
This is it?

![image](https://user-images.githubusercontent.com/886325/83951775-49e91800-a834-11ea-9f5d-fc319840e1db.png)
