### ISSUE TITLE
No longer blocking YouTube ads

### ISSUE THREAD

**Issue by Austenite2** [uBlockOrigin/uBlock-issues#1102]
### Prerequisites

- [ X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ X ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X ] I am running the latest version of uBlock Origin
- [ X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Before June 2020, uBlock Origin blocked all youTube ads.  Since early June 2020, YouTube ads no longer blocked.

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=vOROGorDG6s

### Steps to Reproduce

1. Install uBlock Origin on Chrome, Windows 10
2. Open YouTube
3. Watch a video, notice ads
4. ...
5. Profit!

### Expected behavior:

Before June 2020, all ads on YouTube were blocked

### Actual behavior:

Since early June 2020, ads on YouTube no longer blocked

### Your environment

uBlock Origin 1.27.10

Google Chrome | 83.0.4103.97 (Official Build) (64-bit) (cohort: 83_61_Win)
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 1909 (Build 18363.836)

Also

uBlock Origin 1.27.10

Google Chrome | 83.0.4103.97 (Official Build) (64-bit) (cohort: 83_61_Win)
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Windows 10 OS Version 2004 (Build 19041.264)

**Comment by llacb47** [comment]
Did you read?

```
 I verified that this is not a filter issue
Filter issues MUST be reported at filter issue tracker
```

**Comment by llacb47** [comment]
Just comment on this one: https://github.com/uBlockOrigin/uAssets/issues/7519

**Comment by Austenite2** [comment]
> Did you read?
I did read, thank you for asking.  The text says that if turning off uBlock Origin fixes the issue, then it's likely a filter issue.  Turning off uBlock Origin does not fix the issue.  

Should the text be updated to also include something along the lines of "Ads appearing on a particular site should also be reported at the filter issue tracker?"

**Comment by gorhill** [comment]
>  Turning off uBlock Origin does not fix the issue.

Common sense trumps all other guidelines -- does this really need to be spelled out? It makes no sense to expect that turning off uBO would make the ads go away.
