### ISSUE TITLE
can't block background picture from gta.fandom.com

### ISSUE THREAD

**Issue by asocial-creep** [uBlockOrigin/uBlock-issues#1107]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I tried blocking picture by using last version of ublock and chrome on windows 10 and could not block the annoying background picture of the sky.

### A specific URL where the issue occurs

https://gta.fandom.com/wiki/Main_Page

### Steps to Reproduce

1. go to that page
2. select that sky background image via ublock's element's picker or write manually similar filter using by discovering image url via chrome's element picker, like this: `||vignette.wikia.nocookie.net/gtawiki/images/5/50/Wiki-background/*
||vignette.wikia.nocookie.net/gtawiki/images/5/50/Wiki-background/revision/latest$image`
3. refresh page, watch ublock logger, watch chrome network tab logger in developer tools, clear cache, make sure my filters are really enabled in ublock's settings and that ublock is really enabled...

### Expected behavior:

I expected sky image to disappear after page refresh just like it does when I just make the filter via element picker.

### Actual behavior:

 Instead it returns, even tough it's url is same. It only disappears on first blocking via element filter (before refresh) as it would if blocked via element zapper. 

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
* Operating System and version: Windows 10 20H1 official consumer x64 edition pro (10.0.19041)

**Comment by gwarser** [comment]
EasyList has exception for images `@@||wikia.nocookie.net^*/images/$image`

Add: `||vignette.wikia.nocookie.net/gtawiki/images/5/50/Wiki-background/revision/latest$image,important`

**Comment by asocial-creep** [comment]
OK, now it works. But how did you notice it is being allowed in logger? I can't see any green line, like I would expect to see from previous experience. Otherwise I would blacklist that allowed image via ublock gui as I used to do before. Why is my logger not showing that item at all in ublock? The only way I could suspect that it is being in exception is + sign in main ublock window near domain vignette.wikia.nocookie.net

**Comment by gwarser** [comment]
This image seems to be heavily cache, so it's not displayed on normal reload.

**Comment by asocial-creep** [comment]
Well, looks like you are right. But I tried clearing cache or using incognito, and it appears then.
But it nowhere says that it is belonging to EasyList or being whitelisted, except as + sign in that main window. It only appears neutrally in logger. When I click on that log item, it shows this only:

`Context
gta.fandom.com
Partyness
(3) fandom.com ⇒ nocookie.net
Type
image
URL
https://vignette.wikia.nocookie.net/gtawiki/images/5/50/Wiki-background/revision/latest?cb=20181227145223`
