### ISSUE TITLE
Need help to create rule

### ISSUE THREAD

**Issue by OhSoGood** [uBlockOrigin/uBlock-issues#1110]
Hi,

I'm a newbie regarding ublock rules and, despite I read the doc, I can't find how to create that one. Could anybody help?

I'd like to hide a div only knowing the div id of its first child, let's say on example.com. Below is my sample code. The top div to hide (`<div class="hide-print css-1sxu5km ekv8jyj0">`) has classes which cannot be used, my only distinguishing tip is the `div id="commentsTitle" ` of the first child.
```
<div class="hide-print css-1sxu5km ekv8jyj0">
<div id="commentsTitle" class="css-bfrcvn e18p0e3h1">12 commentaires</div>
<ul>
...

```

Thank you for your help, and thank you for the Raymon for his fantastic work!

**Comment by mapx-** [comment]
For these kind of questions use uBO reddit 
https://www.reddit.com/r/uBlockOrigin/
