### ISSUE TITLE
Have an annoyances filter list enabled by default

### ISSUE THREAD

**Issue by claell** [uBlockOrigin/uBlock-issues#1111]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since some sites show hints that I am using an Adblocker and asking me to disable it, I looked how to get rid of that. Apparently there are already filter lists for that available under the "annoyances" section. Did not know about that before. Since I like having nice default settings in an application, I was thinking about enabling one or more of those lists by default.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
Declined -- too high likelihood of site breakage, in which case users end up blaming uBO rather than the filter list. See <https://github.com/uBlock-LLC/uBlock/releases/tag/0.8.2.8>:

> _"Fanboy's Social Blocking List"_ no longer selected by default for fresh installs
> 
> - It causes too many issues for users who are not accustomed to this filter list ([#458](https://github.com/uBlock-LLC/uBlock/issues/458), [#451](https://github.com/uBlock-LLC/uBlock/issues/451), [#450](https://github.com/uBlock-LLC/uBlock/issues/450), [#428](https://github.com/uBlock-LLC/uBlock/issues/428), stores' feedback, etc)
> - More experienced users can always easily select it after a fresh install

**Comment by claell** [comment]
I was rather referring to the uBlock filters - Annoyances list, but that might behave the same. Is that actually blocking social media content as well? I was just looking for blocking hints that I am using an Adblocker.

Also from my POV, even just using an Adblocker can break sites and need adjustments of Filterlists, so there is not really a reason not to enable additional lists (should not to be filtering to broadly, though) by default imho.

**Comment by llacb47** [comment]
The uBlock Annoyances list is not enabled by default because it blocks soft anti-adblock. Soft anti-adblock is that which can be dismissed by clicking "No, thanks" or similar on a prompt asking to disable adblocker. It also does not come up every time one refreshes the page.

**Comment by claell** [comment]
Really? Alright, seems somewhat understandable not to block too much away by default.

If hard anti-adblock should be blocked by default, I am ok with that. Is there a separate list for that or where does the information for that hard anti-adblocking come from? I have to (rather popular) sites which have hard anti-adblock warnings that are not blocked by default and required me to enable the uBlock Annoyances list. I'd like to report them to a default enabled list for hard anti-adblock blocking.

**Comment by llacb47** [comment]
Also, if it's just a static image or paragraph asking to turn off anti-adblock , it won't be addressed in default settings. That would go in annoyances list.

**Comment by llacb47** [comment]
You can report anti-adblock or any other filter-related concern here: https://github.com/uBlockOrigin/uAssets

**Comment by claell** [comment]
> Also, if it's just a static image or paragraph asking to turn off adblock , it won't be addressed in uBlock Origin default filterlist. That would go in the annoyances list, even if it can't be dismissed- because it doesn't block access to the site, so not "hard" anti-adblock.

Too bad. Then your definition above was a bit too vague. Seems like only complete access blocking is considered hard, everything else is considered soft.

Both are basically banners hinting that I use an Adblocker all the time.

Maybe introduce another category between hard and soft that also gets blocked by default.

**Comment by gorhill** [comment]
>  I have to (rather popular) sites which have hard anti-adblock warnings that are not blocked by default.

Just submit your specific filter issues to <https://github.com/uBlockOrigin/uAssets/issues>, these sort of issues are usually quickly fixed.

As said, I declined to add an annoyance lists by default, so it's best to report specific anti-content blocker issues to uAssets.

**Comment by claell** [comment]
Hm, problem is that those are not anti-content. I can access the content, but they are still there as panel on the side for example.

Would that be in the scope of a normal list that is shipped by default?

>As said, I declined to add an annoyance lists by default

I wrote a reply to that, basically I don't really understand why blocking things like banners that appear instead of ads is causing more problems than the actual ad blocking. However I am not really into this. This is just my impression.

**Comment by Yuki2718** [comment]
If you want more precise definition of soft- or hard- anti-adb here EasyList's, I believe uAssets' criteria is almost the same.
https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins.html

**Comment by claell** [comment]
Thanks. According to that criteria both sites actually are using "not allowed" stuff. I will create issues then!
