### ISSUE TITLE
Element picker suggest incorrect filter

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#1112]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
On Betanews there is a banner for Windows 10 Pro. If you click element picker and select the suggestion it removes the banner until a refresh

[Description of the bug or feature]
||betanews.com/wp-content/themes/betanews/images/carousel-image-960x250-win-10-PRO.png$image <---Does not block after page reload
||betanews.com/wp-content/themes/betanews/images/carousel-image-960x250-win-10-PRO.png <--- does block after page reload
### A specific URL where the issue occurs
Https://betanews.com

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Goto betanews.com see the banner
2. Utilize element picker to block, (It suggest ||betanews.com/wp-content/themes/betanews/images/carousel-image-960x250-win-10-PRO.png$image) select to block
3. image is blocked, but returns after page reload/ or clicking a article link

I had to reblock it 4 times, My filters pane showed the same 4 filter verbatim, only when I edited and removed the $image did it stay blocked.
 
### Expected behavior:
Should be blocked

### Actual behavior:
Is blocked, until page reload or article click

### Your environment

* uBlock Origin version: 1.27.11b15
* Browser Name and version: Firefox 77.0.1/ 79.0a1(Nightly)
* Operating System and version:
Windows 10 Enterprise 2004 19041.329

**Comment by uBlock-user** [comment]
> but returns after page reload/ or clicking a article link

Did you flush the cache when reloading ? Network filters require that sometimes.

**Comment by troysjanda** [comment]
Yes, and same result. There was 4 identical filters and the banner returned if reloading, and even if clicking on an article link it showed back up on the article.

**Comment by troysjanda** [comment]
Please close as invalid, not sure what happen but retest for a 3rd time and seems that 
||betanews.com/wp-content/themes/betanews/images/carousel-image-960x250-win-10-PRO.png$image

does continue to block after page reload
very sorry, I did test twice before posting the bug report

**Comment by troysjanda** [comment]
Closed as invalid
