### ISSUE TITLE
Avoid loading "!#include" filepaths that are wrapped into "!#if" tags that exclude the browser's environment

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1113]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Based on https://github.com/AdguardTeam/FiltersCompiler/issues/84#issuecomment-643830166 onwards.

uBO tries to load `!#include` filepaths, even if they're wrapped into `!#if` perimeters that specify that it's for a different platform, such as `!#if !ext_ublock` or `!#if env_mobile`. Example:

```
!#if !ext_ublock
!#include ExtensionFile.txt
!#endif
```

Normally, this actually works *very* well in most settings to the point where *Frellwit's Swedish Filters* use it very extensively (and I used it for a couple weeks this month), because after the filepath has been loaded, the content becomes treated by uBO as:

```
!#if !ext_ublock
! >>>>>>>> (...)/ExtensionFile.txt
||example.com^
||example.org^
||example.net^
! <<<<<<<< (...)/ExtensionFile.txt
!#endif
```

However, if the filepath is a prohibited or empty one, it is not a particularly good idea to try to load it, especially not when the filterlist maker clearly intended for it to not be loaded by uBO. This can become a big problem for repos where different list versions are hosted in different folders, although in my real case it was [my AdGuard list version](https://github.com/DandelionSprout/adfilt/blob/be69015d73ae609582f0acbb40ddac7b6af7f7de/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuard.txt#L920-L922) that ran into this problem, not my normal uBO version.

Moreover, reducing the amount of loaded extension files can help make the request load burden on a GitHub repo slightly smaller.

This can be tested with https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/!%23include-in-!%23if-test-uBO.txt, which shows the `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/JohnMadden.txt?_=10: 404 Not Found` error in uBO's logger despite being wrapped into `!#if !ext_ublock`.

### A specific URL where the issue occurs

`chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html`

### Steps to Reproduce

1. Open the logger and set the page to "All".
1. Load https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/!%23include-in-!%23if-test-uBO.txt as a custom filterlist.
2. Receive the `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/JohnMadden.txt?_=10: 404 Not Found` error in the logger.

### Expected behavior:

The extension file is not loaded, because it is wrapped around in `!#if`s that indicate that it should not have been loaded.

### Actual behavior:

The extension file is loaded and processed by uBO

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Vivaldi 3.0.1874.38 x64
* Operating System and version: Windows 10 May 2020 Update

**Comment by gorhill** [comment]
What is the issue exactly on your side? You are `!#include`-ing paths to non-existent resources?

**Comment by DandelionSprout** [comment]
Okay, so at the time (Early June), the situation was that I had the following paragraph in both the uBO and AdGuard list versions:

```
!#if !adguard
!#include NorwegianExperimentalList%20alternate%20versions/AntiAdblockEntries.txt
!#endif
```

The filepath was designed to work with the uBO list version only; and not the AG version, which itself was hosted in the `NorwegianExperimentalList%20alternate%20versions` folder, and thus the `!#include` link failed in AdGuard (to the point it apparently caused their filter compiler to completely fail, for some reason).

And from the looks of it, AdGuard is planning to fix this on their end (to the degree I understood https://github.com/AdguardTeam/FiltersCompiler/issues/84#issuecomment-643830640), and since I during testing found out that this was a technical problem in uBO as well, I was presuming it'd be a good idea to have it fixed in both extensions.
