### ISSUE TITLE
Remove ALL references of black/whitelist within uBlock Origin

### ISSUE THREAD

**Issue by yoasif** [uBlockOrigin/uBlock-issues#1114]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Like the similar issue in Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1642790

>It's widely accepted that black and whitelist is outdated and Edge reportedly has removed it: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/blacklist

>There are many other examples too like https://whatwg.org/style-guide#tone

**Comment by gwarser** [comment]
Should probably be duped against master/slave and he/she bugs, but I cannot find them now (different repo?).

**Comment by gorhill** [comment]
I don't remember master/slave or he/she issues ever filed. Anyways, best to keep them distinct, it's going to take before this can be closed. The UI can be easily fixed but changing all instances in the code is far more complicated, especially having to keep backward compatibility.

**Comment by David-H-1** [comment]
Yeah, I agree. Please change ASAP! Google and Microsoft are already doing this! Blacklist and whitelist implicitly say that black is bad and white is good! Please use "block list" and "allow list" instead!

**Comment by gorhill** [comment]
The first one which should be addressed since it's in the user interface is the "Whitelist" pane in the dashboard.

I am think about "Trusted sites". The exrpession really has to convey that the directives in there are to disable uBO.

**Comment by gwarser** [comment]
Can you create en_US version on Crowdin?

**Comment by gorhill** [comment]
Good idea, done.

**Comment by gorhill** [comment]
Closing as stale.
