### ISSUE TITLE
New filter parser creates unexpected network filter from malformed cosmetic filter

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1118]
<details>
<summary>Details</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

    csw.torun.pl#sidebar > .twinsbox > .widget

From "Polskie Filtry Społecznościowe" creates `.widget` network filter. Which apparently prevents some Bitchute videos from playing - https://github.com/MajkiIT/polish-ads-filter/issues/16590

![image](https://user-images.githubusercontent.com/886325/85137648-d555a680-b241-11ea-85c0-c50faf50bb66.png)

### A specific URL where the issue occurs

`https://www.bitchute.com/`

### Steps to Reproduce

1. add filter list `https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt`
2. visit Bitchute
3. logger shows `.widget` filter blocking `https://www.bitchute.com/static/v116/js/third-party/jquery.ui.widget.js`

### Expected behavior:

Will be best to drop it completely. Why it's `.widget`? If parsed as network filter, with `>` it should be dropped.

### Actual behavior:

Unexpected network filter.

### Your environment

* uBlock Origin version: 1.27.11rc2
* Browser Name and version: Firefox Nightly, beta
* Operating System and version: Linux

**Comment by krystian3w** [comment]
I once read that it's like some kind of **archaic** syntax record of ABP filters:

```
example.org#P
```

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/85138023-5dd44700-b242-11ea-8263-aa6203f8a772.JPG)

**Comment by uBlock-user** [comment]
Doesn't discarded as invalid in the presense of hostname entity, for e.g. - `com#sidebar > .twinsbox > .widget`

**Comment by uBlock-user** [comment]
Doesn't get discarded as invalid in the presense of hostname entity, for e.g. - `com#sidebar > .twinsbox > .widget`

**Comment by gorhill** [comment]
Well uBO is unable to tell what the author had in mind, it can't second guess. Any malformed filter is bound to create issue, so the better syntax highlighting will help in preventing those bad filters from being created.

In the current case the reason why `.widget` is picked as the filter is because:

- There is no static extended filter declaration, `##`
- The pattern preceded by the last space is looked-up as the filter -- this takes care of all those HOSTS lists which prefix the hostname to block with any IP address.

**Comment by gorhill** [comment]
To be clear, I don't see this as an issue in uBO, this is just a case of malformed filter which came to surface because the new parser which I consider to be more solid than before.

**Comment by gorhill** [comment]
Example of a list which was not parsed properly before the new parser, while it is now because of the last-space heuristic: https://raw.githubusercontent.com/lennylxx/ipv6-hosts/master/hosts

**Comment by gwarser** [comment]
Bad example, this is not blocking list.

**Comment by gorhill** [comment]
> Will be best to drop it completely.

Alright... Second guessing my above stance. Should we drop any pattern which is preceded by more than one space? This would have taken care of the issue here, but this would not take care of:

    csw.torun.pl#sidebar .widget

**Comment by gwarser** [comment]
First column in HOST files can contain limited set of characters

**Comment by krystian3w** [comment]
> First column in HOST files can contain limited set of characters

not allways?

---

This may need detect string with few combinations:

`.` Public Suffix + :hash: + any letter or  `[` or `.` or `\`

but it can be a very slow check.

**Comment by gorhill** [comment]
Should I cancel current release candidate and go back to normal dev build because of the issue here?

I don't like to keep delaying releasing a stable build, and it has now been more than a month since last one.

**Comment by krystian3w** [comment]
They're assuming I'm the only one dyslexic filter writer on the Earth, so I wouldn't make this a problem to delayed release.

**Comment by gorhill** [comment]
>  I wouldn't make this a problem to delayed release.

Thanks, this way I won't feel pressed for a quick fix and can take my time to put more thoughts into this.

**Comment by uBlock-user** [comment]
fix it in the next dev release after the stable ?

**Comment by Yuki2718** [comment]
> 
>  Should we drop any pattern which is preceded by more than one space? 


Valid hosts format can contain multiple spaces per line, though IDK if uBO supports it or any popular hosts does this.
`https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file`

**Comment by gwarser** [comment]
At least [one person](https://www.reddit.com/r/uBlockOrigin/comments/hckbn5/cant_get_rid_of_this/fvix1sm/) subscribed to [this list](https://github.com/brunomiguel/antinonio/blob/master/antinonio.txt) which mixed static filters and dynamic rules. 

From highlighting in My filters editor it seems to create `block` filters.

![image](https://user-images.githubusercontent.com/886325/85222956-348cf580-b3bf-11ea-9d1a-f0045c558aef.png)

`filterlists.com` allows subscribing to Dynamic rules lists. It will create true/false/allow/noop/block filters. Fortunately not many real world domains like this exists ;)

**Comment by Yuki2718** [comment]
Why the author mixes static and dynamic rules and even recommend to subscribe it.

**Comment by gorhill** [comment]
I have committed a change to at least take into account extraneous space characters and filters with more than one space character will be deemed dubious and rejected. This does not completely take care of the issue here but given the last finding I felt the extraneous space case needed to be tackled asap.

**Comment by gwarser** [comment]
> Why the author mixes static and dynamic rules and even recommend to subscribe it.

https://github.com/brunomiguel/antinonio/issues/20 hmmm. They partially don't understand and partially want to use it as universal list for uMatrix and uBO.

**Comment by krystian3w** [comment]
https://github.com/brunomiguel/antinonio/issues/20 https://github.com/brunomiguel/antinonio/issues/24

**Comment by Yuki2718** [comment]
I'm starting to feel it may not be enough to prevent malfunction of bad rules but (if it's possible) user should be warned if a filter he/she subscribed has too many bad rules beyond a possible amount of typo/human mistake. There are simply too many low quality filters on Internet and most user can't tell the quality.

**Comment by krystian3w** [comment]
New one glitch:

https://github.com/PolishFiltersTeam/KAD/commit/8bc83c9307732c38715fe9520d76a373ff24c09c

![obraz](https://user-images.githubusercontent.com/35370833/85944796-d2417100-b939-11ea-8830-de95048ec007.png) |
--- |

**Comment by gwarser** [comment]
Something was inserted between `z` and `^`?

**Comment by krystian3w** [comment]
Yes invisible character "`e2808e`" (bug in `niebezpiecznik.pl` Wordpress).

**Comment by gwarser** [comment]
How other blockers handle this?

**Comment by krystian3w** [comment]
Omitt filter and don't try block someting like: `http://getin-secure-bank.xn--xyz-7t7s`

**Comment by gwarser** [comment]
uBO and AdGuard at least highlight it in "My filters" editors. In ABP and Adblock it's invisible.

![image](https://user-images.githubusercontent.com/886325/85945434-07e85900-b93e-11ea-8620-36533372aeed.png)

**Comment by krystian3w** [comment]
but not in GitHub viewer file (`edit` tribe have centered "dot") or Visual Studio Code (need install `anti-gremlin` plugin or some better).

**Comment by gorhill** [comment]
Good catch.

So before the new parser, Mathias Bynens' [punycode](https://github.com/bestiejs/punycode.js) would still convert the hostname to ASCII, though surely a case of filter never matching anything.

The new parser uses [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), so as to avoid external dependencies (for example, I want the parser to work in a web page), but this one does not accept punycoding, and this caused an empty hostname as a result instead of a punycoded hostname.

The fix now catches this, and will highlight the hostname as invalid in the editor and asset viewer -- i.e. the filter is entirely rejected.

**Comment by krystian3w** [comment]
#1146

**Comment by krystian3w** [comment]
>> https://github.com/uBlockOrigin/uBlock-issues/issues/1134#issuecomment-663972358
>
> `randomwebsite.org/* $inline-script`
> 
> https://www.reddit.com/r/uBlockOrigin/comments/hxorev/ublock_origin_page_loading_issue/fzaguh5/
