### ISSUE TITLE
uBO feature request: add behind-the-scene as a filter option in the logger

### ISSUE THREAD

**Issue by jawz101** [uBlockOrigin/uBlock-issues#1119]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

 uBO feature request: add behind-the-scene as a filter option in the logger

### A specific URL where the issue occurs

not an issue.  not applicable

### Steps to Reproduce

1. open logger
2. see behind-the-scene requests
3. [and so on...]

### Expected behavior:

have ability to filter out behind-the-scene requests

### Actual behavior:

unable to filter out behind-the-scene requests

### Your environment

* uBlock Origin version: uBlock Origin v1.27.10
* Browser Name and version: Firefox 77.0.1
* Operating System and version: Windows 7

**Comment by gwarser** [comment]
Type `|0` into filtering input box.

**Comment by gorhill** [comment]
You can also select "Tabless".
