### ISSUE TITLE
https://www.hackintoshzone.com

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uBlock-issues#112]
![image](https://user-images.githubusercontent.com/34273204/42286214-21f3cbd0-7f80-11e8-81a2-ea71fea1df8e.png)

**Comment by xqk94524** [comment]
![image](https://user-images.githubusercontent.com/34273204/42286270-500a66d2-7f80-11e8-990c-1a7823fc410d.png)

**Comment by mapx-** [comment]
You hve to report to the correct repository
https://github.com/uBlockOrigin/uAssets/issues
