### ISSUE TITLE
Mobile users can't use `ctrl`, `tab`, etc

### ISSUE THREAD

**Issue by androidacy** [uBlockOrigin/uBlock-issues#1120]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when... (Not applicable)
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the changelog for 1.27.11rc3 it mentions adding allow rules directly is no longer allowed unless you press `ctrl`, and another place references `tab`

Which is great on desktop.

Not so much mobile as we don't standardly have said keys.

I'm not sure if you already have a plan to deal with this or not but I figured I'd open an issue.

### A specific URL where the issue occurs

Not applicable

### Steps to Reproduce

1. Not applicable

### Expected behavior:

Feature parity where possible between mobile and desktop using workarounds where necessary

### Actual behavior:

Mobile will lose this functionality

### Your environment

* uBlock Origin version: 1.27.11rc3
* Browser Name and version: Firefox or chrome (forks with extension support) mobile
* Operating System and version: Android or iOS

**Comment by uBlock-user** [comment]
If you're already an advanced user, you can set `filterAuthorMode` to `true` and the functionality will return.

**Comment by Yuki2718** [comment]
Or `popupPanelGodMode`?

**Comment by uBlock-user** [comment]
> Or popupPanelGodMode?

not anymore, removed in dev build.

**Comment by Yuki2718** [comment]
Okay, thx!

**Comment by nuenuewei** [comment]
There's no good reason why mobile users _shouldn't_ have access to this functionality, keyboard app makers just decided for you that you don't need it, a terribly frustrating attitude very common among mobile developers. Several keyboards however, for example Hacker Keyboard on android, include them- and using those keyboards could be a workaround in the short term.

**Comment by gorhill** [comment]
I use [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) and it also gives access to Ctrl and Tab keys.

**Comment by gorhill** [comment]
> mobile users shouldn't have access to this functionality

Closing, since there is an option to make the creation of allow rules possible:

> you can set `filterAuthorMode` to `true` and the functionality will return.
