### ISSUE TITLE
Multiple entries for the same resources in the logger (Firefox only)

### ISSUE THREAD

**Issue by darkred** [uBlockOrigin/uBlock-issues#1122]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

&nbsp;

### Description

The issue is that, only in Firefox (no issue in Google Chrome), there are multiple entries for the same resources in uBO logger. 

But, when I disable uBO via about:addons, 
there are no such multiple network request entries for these resources in the Network devtool.

For reference I quote the only relevant comment I found, by @gorhill , in https://github.com/gorhill/uBlock/issues/391#issuecomment-114180460 
(It's from 5 years ago, at that time Firefox was at version 38) :
> If there are multiple entries for the same resource, it's simply because Firefox's makes multiple requests for the same resource, uBlock merely shows you what is happening internally, it does not create entries out of thin air.

If the above still stands stands (I mean, with the current Firefox version 77), and it's not a uBO issue but a Firefox issue, should I report it to bugzilla.mozilla.org ? In such case, could you please help me with providing technical details to include in my report?

&nbsp;

### A specific URL where the issue occurs

Here are two example URLs (it occurs consistently/every time) :

- https://majorgeeks.com/
- https://rarbgproxy.org/torrents.php

&nbsp;

### Steps to Reproduce

1. In a fresh Firefox 77.0.1 profile with only uBO installed
2. Open uBO logger
3. Open Network devtool and tick the `Disable cache` checkbox, or presh Ctrl+F5(bypassing cache) on each page
4. Load https://majorgeeks.com/
Switch to uBO logger, for convenience filter the logger output to view only "Blocked* entries: 
notice that the following entries appear twice:

    ```
    /ad160px.​        ​         www.majorgeeks.com​ ​ image ​  https://www.majorgeeks.com/images/mg/ad160px.png
    /www/delivery/*​           ​www.majorgeeks.com​ ​ script  ​https://ra.majorgeeks.com/www/delivery/spcjs.php?id=1&target=_blank
    ||googlesyndication.com^​  ​www.majorgeeks.com  ​script  https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
    ||thisiswaldo.com^$3p     ​www.majorgeeks.com ​ script ​ https://cdn.thisiswaldo.com/static/js/4107.js
    ```
5. Load https://rarbgproxy.org/torrents.php
Notice in uBO logger that the following entry appears twice:

    ```
    |dyncdn.me/static/20/js/expla*.js$domain=ra...  ​rarbgproxy.org   ​script​  https://dyncdn.me/static/20/js/expla95.js
    ```

&nbsp;

### Expected behavior:

There should be no multiple entries in the logger 
*(for comparison there are no such entries in uBO logger with Google Chrome)*

&nbsp;

### Actual behavior:

There are several multiple entries in the logger.

&nbsp;

### Your environment

* uBlock Origin version: 1.27.11rc4 (or any other uBO version), with only default filter lists, all updated.
* Browser Name and version: Firefox 77.0.1 x64
* Operating System and version: win10 x64 version 2004

**Comment by gorhill** [comment]
From what I can see when stepping in the debugger, uBO is reporting accurately, those duplicated blocked requests were really fired twice by Firefox to uBO's onBeforeRequest() listener. They are also labelled as distinct network requests as the have different request ids.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/85231886-2d83d880-b3fb-11ea-8664-56ca94f2d098.png)

**Comment by darkred** [comment]
Thanks for the quick response.

&nbsp;

With uBO disabled, I see that in Network devtool, there's only one `expla95.js` request in Network devtool :
<details>
<summary>Firefox Network devtool screenshot</summary>

![2020-06-21_212131](https://user-images.githubusercontent.com/723651/85232083-3b3e5b80-b405-11ea-9bbc-1220568fa583.jpg)
</details>

For reference, the same occurs in Google Chrome:
<details>
<summary>Chrome Network devtool screenshot</summary>

![2020-06-21_213949](https://user-images.githubusercontent.com/723651/85232487-ce789080-b407-11ea-9404-40a2bd97885f.jpg)
</details>

So, since these requests are really fired twice by Firefox, 
maybe both the Firefox (and Chrome) Network tools don't view duplicate entries? But only every request once? 

If that's the case, I'd like to ask please consider adding an option in logger, to only display `unique network requests`, 
i.e. display each network request only once per page load (between the horizontal separators) .
*I believe it would make using the logger more convenient, visually avoiding duplicate entries, 
and because, in Google Chrome there are no such duplicate entries in uBO logger.*

**Comment by gwarser** [comment]
Even using DevTools built-in blocker creates duplicate:

![image](https://user-images.githubusercontent.com/886325/85232895-219c1480-b403-11ea-9597-661a405816bb.png)

It seems Firefox is requesting resource second time in case of error? Even if Chrome is doing this it does not send all requests to extensions. For example 301 redirects are always visible in Firefox but not in Chrome - https://github.com/gorhill/uBlock-for-firefox-legacy/issues/229#issuecomment-647120382

**Comment by uBlock-user** [comment]
Browser quirk ? I have noticed duplicates in Chrome too many times, always thought this was browser behavior or website was forcing a request until the content got loaded

**Comment by gorhill** [comment]
> If that's the case, I'd like to ask please consider adding an option in logger, to only display `unique network requests`

Decline, I rather have the logger output exactly what is happening inside uBO.

**Comment by darkred** [comment]
> Declined, I rather have the logger output exactly what is happening inside uBO.

Just to clarify, I didn't mean to drop(=ignore/not include) the duplicate entries from the logger output.
I only had in mind to be able to visually filter the duplicate entries, 
as an extra toggle expression, named `Unique`, in the expression picker *(below the "Not / CNAME" row)* :
![2020-06-22_185528](https://user-images.githubusercontent.com/723651/85308535-faece500-b4b9-11ea-8e89-4dc5e6c52828.jpg)

&nbsp;

> I have noticed duplicates in Chrome too many times

Are you sure you are not referring to Firefox?
I only get duplicate entries in uBO logger with Firefox - never, not even once, with Chrome.
