### ISSUE TITLE
Access desktop cloud rules snapshots from Firefox Preview

### ISSUE THREAD

**Issue by jsamr** [uBlockOrigin/uBlock-issues#1125]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As per the description of steps to reproduce the issue, cloud storage feature seems to be siloed to each Firefox version, Firefox Preview and Mozilla Firefox Desktop. To help with the description, lets say we have three devices:

- Desktop A, with Mozilla Firefox for GNU/Linux desktop;
- Desktop B, with Mozilla Firefox for GNU/Linux desktop;
- Mobile α , with Firefox Preview for Android.

I would be extremely handy to have access to rules snapshots uploaded from Desktop A and B to Mobile α.

### Steps to Reproduce

Prerequisites:

- All of these Firefox instances are authenticated to the same Firefox Account;
- All of these uBlock Origin extensions have the same configuration, with
  advanced functionalities and cloud storage turned on.

1. (Desktop A): within uBlock Origin extension config page, go to “dynamic filters” tab, and set a name to this device, “Desktop A”.
2. (Desktop A): press the upload button to create a new snapshot in the cloud.
3. (Desktop A): go to Firefox drop-down menu and press the Firefox Account sync button.
4. (Desktop B): go to Firefox drop-down menu and press the Firefox Account sync button.
5. (Desktop B): within uBlock Origin extension config page, go to “dynamic filters” tab. The “Desktop A” snapshot is visible. Press the import button to merge the snapshot into temporary rules buffer.
6. (Mobile α): go to parameters and perform a Firefox Account sync.
7. (Mobile α): within uBlock Origin extension config page, go to “dynamic filters” tab.

### Expected behavior:

(Mobile α): The last snapshot from Desktop A should be visible in the header of the configuration page, and the import button should be actionable.

### Actual behavior:

No snapshot is visible, and solely the upload button is actionable.

### Your environment

* uBlock Origin version:
  - Dektop A: 1.27.10
  - Dektop B: 1.27.10
  - Mobile: 1.27.10
* Browser Name and version:
  - Desktop A: Mozilla Firefox for Manjaro Linux 77.0.1 
  - Desktop B: Mozilla Firefox for Manjaro Linux 77.0.1 
  - Mobile: Firefox Preview 5.1.1, build \#21571852
* Operating System and version:
  - Desktop A: Linux 5.4.44-1-MANJARO \#1 SMP PREEMPT x86_64 GNU/Linux
  - Desktop B: Linux 5.4.44-1-MANJARO \#1 SMP PREEMPT x86_64 GNU/Linux
  - Mobile: Oxygen OS (Android) 10.3.3

**Comment by gwarser** [comment]
I'm not sure about Fenix/Preview, but old Firefox mobile (Fenec?) does not support syncing extensions.

**Comment by gwarser** [comment]
I see only bookmarks, history, logins and open tabs being an option.

Not supported by Firefox.

**Comment by jsamr** [comment]
> I'm not sure about Fenix/Preview, but old Firefox mobile (Fenec?) does not support syncing extensions.

I doubt this is true because I *can* export snapshots within Firefox Mobile app, see screenshot bellow:

![Screenshot_20200623-194909](https://user-images.githubusercontent.com/3646758/85474270-cc8b0a80-b58a-11ea-84aa-0d115a9dea49.jpg)

But as I claimed, I believe this snapshot is siloed from those in desktop version.

**Comment by gwarser** [comment]
https://support.mozilla.org/en-US/kb/how-do-i-choose-what-types-information-sync-firefox#w_what-types-of-information-can-i-share-across-my-devices

>Add-ons: select this checkbox if you want to synchronize your add-ons across your devices. **Add-ons for the desktop version of Firefox cannot be synchronized with the mobile versions of Firefox.**
