### ISSUE TITLE
Cookie-remover.js does not remove a cookie

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1126]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Cookie-remover.js does not remove a specific cookie on `www.mikrobitti.fi`. The cookie is set for `mikrobitti.fi`, which probably is the reason behind this (I did read the documentation: https://github.com/gorhill/uBlock/wiki/Resources-Library#cookie-removerjs-) The problem is that I cannot make a rule to remove it even if I have a filter for both domains.

The name of the cookie is `Bhb2CdOB3V`.

Related conversation: https://www.reddit.com/r/uBlockOrigin/comments/hem8c5/cookieremoverjs_does_not_work/

### A specific URL where the issue occurs

`https://www.mikrobitti.fi/`

### Steps to Reproduce

1. Set filters to remove a cookie called `Bhb2CdOB3V`
`mikrobitti.fi##+js(cookie-remover, Bhb2CdOB3V)`
`www.mikrobitti.fi##+js(cookie-remover, Bhb2CdOB3V)`

2. Go to `https://www.mikrobitti.fi/`

3. Check if that cookie is being removed or not.

### Expected behavior:

Tha cookie would be removed.

### Actual behavior:

The cookie wasn't removed.

### Your environment

* uBlock Origin version: v1.27.10
* Browser Name and version: Firefox 77.0.1
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
Does this count as declined? https://github.com/uBlockOrigin/uBlock-issues/issues/352

**Comment by peace2000** [comment]
After I opened this issue, I was told that this scriptlet expires cookies, doesn't remove them. That's probably ok as well. However the name is really missleading, could it be changed?

But anyway, just hoping that this scriptlet could be fixed so that it expires or removes that specific cookie. :)

**Comment by gorhill** [comment]
So it appears the domain `www.mikrobitti.fi` is allowed to set cookies for `.mikrobitti.fi`? I did not expect this. Is this because `www` is a special treated as a special subdomain?

**Comment by peace2000** [comment]
> So it appears the domain www.mikrobitti.fi is allowed to set cookies for .mikrobitti.fi?

![kuva](https://user-images.githubusercontent.com/17256841/85608693-fbbe7c00-b65d-11ea-99c8-fa24b25ec6da.png)

It seems so.

**Comment by peace2000** [comment]
Tested in RC7. Works as intended. Thanks!
