### ISSUE TITLE
Ask authentication before enabling allow temporarirly.

### ISSUE THREAD

**Issue by ambuj-codes** [uBlockOrigin/uBlock-issues#1129]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[authentication before enabling allow temporarirly]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [visit any blocked website]
2. [two options appear]
3. [allow temporarily]

### Expected behavior:

[Please add user authentication (a password)]

### Actual behavior:

[by clicking on allow temporarily we are able to visit website. ]

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox latest
* Operating System and version: Windows 10 version 2004

**Comment by Yuki2718** [comment]
Doesn't make sense, those who can access dynamic pane can also access My rules or even uBO's settings file. If you don't want others to make Allow, lockdown your PC before leaving. Even if Allow is added without your knowing, it's easy to remove all the Allow rule in My rules.

**Comment by gorhill** [comment]
Just put a password on your account.

**Comment by ambuj-codes** [comment]
Can you please tell me how to make an account on UBO extension?
I searched it everywhere, but could not find it

**Comment by ambuj-codes** [comment]
> 
> 
> Just put a password on your account.

Please tell me what account?

**Comment by gorhill** [comment]
I mean a OS account, so that nobody can modify your Firefox setup. What you ask from uBO makes no sense, whoever can just remove/reinstall uBO and configure as they wish.

What you want is not uBO-related, best you find support for OS account elsewhere.
