### ISSUE TITLE
CCleaner   BleachBit delete settings

### ISSUE THREAD

**Issue by M1Aston** [uBlockOrigin/uBlock-issues#1133]
After running a disk cleaner like CCleaner or BleachBit, lots (or all?) of the settings I changed for uBlock (using Firefox) are gone\reset to default.

Obviously something is deleted that shouldn't be. Can someone please tell me which Firefox file is used for storing uBlock settings? I have tried to figure it out myself, but I can't.

**Comment by gwarser** [comment]
You are lucky this is only deleted settings. Firefox storage is so fragile that it may cause all sort of issues.

Search in `profile/storage/default/moz-extension+++*`

**Comment by gorhill** [comment]
Best is to not use sleazy software in the first place, see <https://twitter.com/gorhill/status/1265706912571629568>. I am sure there are better alternative out there.

**Comment by M1Aston** [comment]
Alright, point taken. I think BleachBit is open source. I'll switch to that for now, see how that goes. (and look for anything better)

**Comment by M1Aston** [comment]
Yes! I managed to find the cause of the problem thanks to this info. Thank you very much for your help.
