### ISSUE TITLE
TCF global vendor list and the Google ad technology provider list.

### ISSUE THREAD

**Issue by privacy-advo** [uBlockOrigin/uBlock-issues#1137]
Hi, 
I would like to suggest the automated ingestion of TCF global vendor list and the Google ATP list.
The TCF GVL is updated weekly:
https://vendorlist.consensu.org/v2/vendor-list.json

The Google ATP can be found here:
https://storage.googleapis.com/tcfac/additional-consent-providers.csv

Would it not be beautiful to let them do the work?

Thanks ahead

**Comment by privacy-advo** [comment]
Thank you for the response.
Sadly I don't understand your reply.
Do you think it is not feasible to realize this?

**Comment by gorhill** [comment]
Declined, I don't really understand what you are asking, it seems you want uBO to be able to read some of JSON format, from which some specific hostnames would be used as filters. Just assume these are all already covered in the standard filter lists.
