### ISSUE TITLE
Enable JavaScript without page refresh

### ISSUE THREAD

**Issue by christianbundy** [uBlockOrigin/uBlock-issues#1138]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi! I'm loving uBlock Origin, and recently realized that it can block JavaScript by default. I've been allowing JavaScript on domains that I trust, which is a three-step process:

1. Select uBlock Origin
2. Toggle 'JavaScript'
3. Select 'Refresh'

Refreshing the page is slow on low-bandwidth connections, and I've written a small piece of code that takes each `<script>` and duplicates it.

1. Select uBlock Origin
2. Toggle 'JavaScript'
3. 
    ```javascript
    document.querySelectorAll('script').forEach((script) => {
      const clone = script.cloneNode();
      script.after(clone)
    });
    ```

This has the expected effect on the DOM, but it looks like uBlock Origin continues blocking JavaScript requests until you refresh the page. **Is it possible to fix this, so that we don't have to do a full HTML page load after enabling JS?** Thanks for all your work on this project!

### A specific URL where the issue occurs

This happens everywhere. Here's a random Conway's Game of Life that requires JavaScript:

http://console-of-life.glitch.me/

### Steps to Reproduce

1. Select uBlock Origin
2. Toggle 'JavaScript'
3. 
    ```javascript
    document.querySelectorAll('script').forEach((script) => {
      const clone = script.cloneNode();
      script.after(clone)
    });
    ```

### Expected behavior:

When these `<script>` nodes are copied, uBlock Origin should not block the requests (because JavaScript is disabled).

### Actual behavior:

The requests are blocked until you refresh the page.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Mozilla Firefox 78.0.1
* Operating System and version: Linux orion 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux

**Comment by gorhill** [comment]
uBO uses a content security policy directive to disable JavaScript, the refresh is necessary to ensure the page is no longer subject to the previously injected CSP. What you are asking is not possible.

**Comment by christianbundy** [comment]
Thanks for the quick response! I didn't realize that's how it worked, cheers.
