### ISSUE TITLE
Reverse lookup fails for filter of type example.com##*

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uBlock-issues#1139]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [] uBlock Origin is the only extension
    - [] uBlock Origin with default lists/settings
    - [] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Reverse lookup fails for any filter of type `example.com##*`

### A specific URL where the issue occurs

`http://example.com/`

### Steps to Reproduce

1. Add `example.com##*` to my filters
2. Visit `http://example.com/`
3. Open the logger and click on `*`

### Expected behavior:

Reverse lookup works

### Actual behavior:

Reverse lookup failed for the added filter.
![image](https://user-images.githubusercontent.com/16567977/86489770-62652900-bd33-11ea-97eb-2965092362b3.png)

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Tested in Chrome 83.0.4103.116 and Firefox 78.0.1
* Operating System and version: Windows 10 version 1909

### Notes

`RU Adlist` uses a filter like this: `https://hg.adblockplus.org/ruadlist/file/tip/advblock/specific_hide.txt#l1152`

**Comment by P0Rtvine** [comment]
@gorhill

**Comment by gorhill** [comment]
It's fixed in dev build, not in stable build.
