### ISSUE TITLE
WebRTC Network/Connectivity

### ISSUE THREAD

**Issue by FreezeHeat** [uBlockOrigin/uBlock-issues#114]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

WebRTC doesn't work properly with ublock, after getting rid of every filter, disabling the current page, disabling ublock and turning on/off the WebRTC Leaks option, I then tried to turn it off from the extension list, and then everything worked correctly.

I tested this with Discord, and with the WebRTC troubleshooter ( https://test.webrtc.org/ ), ublock causes failure with discord by pretty much failing at the signaling phase, causing a "ICE - Checking" problem, using the troubleshooter I get errors with Network (UDP + IPv6 - failed to gather candidates) and Connectivity (Relay + Host - "FAILED [TIMED OUT]").

### A specific URL where the issue occurs

https://test.webrtc.org/
https://discordapp.com/

Pretty much any website that uses WebRTC.

### Steps to Reproduce

WebRTC
1. Enable uBlock (even with default settings) in google chrome.
2. Start the WebRTC troubleshooter.
3. Wait for problems to pop up in the Network and Connectivity tabs.

Discord
1. Enable uBlock (even with default settings) in google chrome.
2. Connect to a discord server and check your connection info near the microphone mute option.
3. Check that it says "ICE-Checking" and it's stuck at that phase.

### Expected behavior:

WebRTC:
Network and Connectivity tabs should show all green in Network and Connectivity.

### Actual behavior:

Network and Connectivity tabs are red, in particular, Network has UDP and IPv6 problems and in Connectivity the Host and Relay connectivity are red.

### Your environment

* uBlock Origin version: 1.16.12
* Browser Name and version: Google Chrome, Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System and version: Lubuntu 18.04 LTS, linux kernel version 4.15.0-24-generic

**Comment by uBlock-user** [comment]
> WebRTC doesn't work properly with ublock, after getting rid of every filter, disabling the current page, disabling ublock and turning on/off the WebRTC Leaks option, I then tried to turn it off from the extension list, and then everything worked correctly.

![](https://i.gyazo.com/06d40be6c77b67d0b6176f1a822be96a.png)

Works fine after disabling `Prevent WebRTC from leaking local IP addresses` switch.

**Comment by uBlock-user** [comment]
>Enable uBlock (even with default settings) in google chrome.
Connect to a discord server and check your connection info near the microphone mute option.
Check that it says "ICE-Checking" and it's stuck at that phase.

Cannot reproduce that either, no such error or notification appears on my end either. Connects successfully via a WebSocket Connection.

**Comment by gorhill** [comment]
Unable to reproduce issue specific to uBO when _"Prevent WebRTC from leaking local IP addresses"_ is not enabled.

With regard to WebRTC, uBO is simply toggling a single browser setting when _"Prevent WebRTC from leaking local IP addresses"_ is enabled, and does nothing when it's disabled.

You need to better investigate your issue, it's not uBO-related.
