### ISSUE TITLE
Youtube ads are back

### ISSUE THREAD

**Issue by corysimmons** [uBlockOrigin/uBlock-issues#1140]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Youtube plays ads.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
https://www.youtube.com

### Steps to Reproduce

1. [First Step] go to youtube.com
2. [Second Step] watch a video
3. [and so on...] see ads

### Expected behavior:

[What you expected to happen]
To not see ads.

### Actual behavior:

[What actually happened]
I get ads on almost every video.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Chrome 83.0.4103.116
* Operating System and version: macOS Catalina 10.15.4

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7519
