### ISSUE TITLE
Transfer open issues from gorhill/uBlock

### ISSUE THREAD

**Issue by MikkCZ** [uBlockOrigin/uBlock-issues#1141]
Hi.

I was cleaning my personal list of open issues I created etc. and wanted to close https://github.com/gorhill/uBlock/issues/3203 as something I think should be closed as invalid.

I noticed the issue tracker has been moved here, and I believe it can help if you move the issues from the old repository here. It's possible quite some time since GitHub added this feature, but I learned recently it's possible. See https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository.

**Comment by gorhill** [comment]
I cannot transfer to a repo into another account, just another repo within the same account:

> You can only transfer issues between repositories owned by the same user or organization account.

uBlockOrigin repo is a different account than gohill repo.
