### ISSUE TITLE
HTML Filitering run on windows-1250 encoding page?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#1143]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I found once page with malware meta refresh tag: `http://twojanazwa.xn.pl/`

```html
<meta http-equiv="REFRESH" content="5;URL=https://padslims.com/enp70cx6n?key=e0674bb6d9953e96a9773aebdf6251c9">
```

But I have noticed that character encoding should not allow filtering:

```html
<meta http-equiv="Content-Type"
content="text/html; charset=windows-1250">
```

Nonetheless filter works and break some letters on site:

`xn.pl##^meta[content*="5;URL=https://padslims.com/"][http-equiv="REFRESH"]`

![obraz](https://user-images.githubusercontent.com/35370833/86622010-78871980-bfbf-11ea-80e4-b465fb57aa7b.png) | ![obraz](https://user-images.githubusercontent.com/35370833/86622068-8d63ad00-bfbf-11ea-85cc-458882a5f47e.png)
--- | ---
broken letters | what should be shown

_I assume that there are few such sites left and you could ignore the error and consider the site as abandoned (as if the last changes were made by administrators in 2013 and now only someone pays for the domain and hosting)._

### A specific URL where the issue occurs

```
http://twojanazwa.xn.pl/
```

`https://pastebin.com/raw/NDa4vHqi` - code source if site down.

### Steps to Reproduce

1. Open Firefox and uBO "my filters" panel
2. paste example filter `xn.pl##^meta[content*="5;URL=https://padslims.com/"][http-equiv="REFRESH"]` and save
3. open problematic page
4. the filter removed the meta tag and the character encoding was damaged

### Expected behavior:

better detection pages not written according to www standards:
 - no used DTD (`https://www.w3schools.com/tags/tag_doctype.asp`)
- `<meta>` tag charset smashed into multiple lines:

   ```
   <meta http-equiv="Content-Type"
   content="text/html; charset=windows-1250">
   ```

### Actual behavior:

uBO classifies the site as having utf-8 encoding, because the webmaster neglected to prepare his website according to WWW standards (no DTDs and `<meta>` tag charset smashed into multiple lines) 

**or**

 by accident, the person who hacked into the site slightly damaged page  404 html code.

### Your environment

* uBlock Origin version: 1.28.1b5
* Browser Name and version: Firefox 78.0.1
* Operating System and version: Windows 10 Pro 20H1

**Comment by gwarser** [comment]
Page is written in UTF-8, meta tag is wrong.

![image](https://user-images.githubusercontent.com/886325/86624032-ebde5a80-bfc2-11ea-978b-294a1c33fd5f.png)

**Comment by uBlock-user** [comment]
Issue was addressed in https://github.com/gorhill/uBlock/issues/3397, breakage shouldn't occur.

**Comment by gwarser** [comment]
This can be Firefox regression https://hsivonen.fi/chardetng/

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/commit/46c2815e6b6b7b1214e9deb6930319b74530a283
