### ISSUE TITLE
uBO could be more resilient to storage.js corruption

### ISSUE THREAD

**Issue by nuenuewei** [uBlockOrigin/uBlock-issues#1144]
### Prerequisites
- [x] I verified that this is not a filter issue
    
- [x] This is not a support issue or a question
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [n/a] uBlock Origin is the only extension
    - [n/a] uBlock Origin with default lists/settings
    - [n/a] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When a system crash happened, I lost all of my filters. While investigating I found the tail end of my old filter list, kept as storage.js.corrupt, had been reduced to NUL NUL NUL etc ad infinitum. File attached if useful: [storage.js.zip](https://github.com/uBlockOrigin/uBlock-issues/files/4895653/storage.js.zip) I don't think you can't meaningfully prevent this; however keeping a periodic backup automatically would be nice.

While attempting to reconstruct parts of my filter list, I noticed notepad++ was frequently telling me the file had changed and needed to reload. Some part of the file is being frequently updated, and that's making it way more likely for it to be corrupted. If whatever was causing those frequent writes were in a different file, the chance of the whole list getting nuked would be much lower.

### A specific URL where the issue occurs
127.0.0.1(not applicable)

### Steps to Reproduce
1. some item is frequently updated in storage.js
2. have a system crash while 1 occurs
3. lose all filter lists and settings due to file corruption

### Expected behavior:
uBO behaving in a way that's resilient to data corruption on system crash

### Actual behavior:
uBO isn't as resilient as it could be to data corruption on system crash

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: waterfox classic 2020.07 (likely platform-agnostic issue)
* Operating System and version: Windows 7 Ultimate SP1 (likely platform-agnostic issue)

**Comment by gorhill** [comment]
Closing as unactionable, too unspecific -- it's a vague issue is entirely based on assumptions ("could be"). uBO uses an API to persist stuff, and has no control of write operations beyond that API.
