### ISSUE TITLE
Whitespaces are now stripped from blocking-rule URLs, causing rules targeting whitespaces to fail and/or block extremely broadly

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1146]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (v1.28.0)
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Whitespaces, such as zero-width space and soft hyphen, are now stripped from blocking rule URLs in uBO v1.28.0, which did not occur in v1.27.10. This means that entries that specifically try to block such whitespaces (due to how they're occasionally used in malware domain obfuscations), now block potentially every domain whatsoever.

Example entries (hopefully with the whitespaces preceding the asterisks):

```
­*$document
​*$document
```

### A specific URL where the issue occurs

`https://example.org/`

### Steps to Reproduce

1. Make sure the uBO version is v1.28.0 (v1.28.1b versions would presumably also work, but I haven't tested it at the time of writing)
2. Create an entry consisting of a whitespace, an asterisk, and (optionally) `$` values.
3. See the strict warning show up when visiting pretty much every website in existence.

### Expected behavior:

Whitespaces are retained in blocking rules, so they can block URLs containing such whitespaces.

### Actual behavior:

All domains of any kind are blocked.

### Your environment

* uBlock Origin version: uBO 1.28.0
* Browser Name and version: Vivaldi 3.1.1929.45 x64 / Firefox 77.0.1 x64
* Operating System and version: Windows 10 May 2020 Update

**Comment by gorhill** [comment]
> Create an entry consisting of a whitespace, an asterisk, and (optionally) `$` values

Can you provide such a filter? I am not sure what you have in mind.

**Comment by gorhill** [comment]
Do you have an actual URL in the real world which make use of such whitespace?

**Comment by DandelionSprout** [comment]
I myself have (sadly?) not come across any such URLs first-hand, but there's a fair documentation on it out there:

* https://thehackernews.com/2019/01/phishing-zero-width-spaces.html
* https://community.broadcom.com/symantecenterprise/communities/community-home/librarydocuments/viewdocument?DocumentKey=3f86fd1d-ca17-4e5b-b75e-88dd2c6f0c2d&CommunityKey=1ecf5f55-9545-44d6-b0f4-4e4a7f5f5e68&tab=librarydocuments
* https://it.slashdot.org/story/10/10/07/2127241/Spammers-Using-Soft-Hyphen-To-Hide-Malicious-URLs
* https://en.wikipedia.org/wiki/Zero-width_space#Blacklisting_in_URLs

**Comment by gorhill** [comment]
Here is a link with a hidden space after the letter `m`:

[example.org with hidden space after `m`](https://exam​ple.org/)

Confirmation using the DOM inspector:

![c](https://user-images.githubusercontent.com/585534/87170002-c7260380-c29e-11ea-89f3-32caf0049c0f.png)

Now if I create the filter `||example.org^`, no hidden space anywhere, uBO properly block the access to `example.org`, despite the hidden space. So it looks to me uBO is doing the right thing, whoever is using hidden space is not going to fool uBO.

So it looks to me the issue in those articles you posted affected some products who were fooled into taking into account what are essentially forbidden characters in URLs -- Firefox's URL objects do not accept hostnames with hidden spaces in them, and having filters with such hidden spaces was actually [causing an issue](https://github.com/uBlockOrigin/uBlock-issues/issues/1118#issuecomment-650730158), which has been solved.

The bottomline is really that filter list authors should not use whitespaces in their network filters, they are not allowed in URLs.

**Comment by DandelionSprout** [comment]
Well, now I at least know what the cause behind the codebase change was.

To the degree it was used in [my own anti-malware list](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L340), the presumption was that if someone made a URL like (Purely theorethical example) `git​hub.com` with a zero-width space after `t`, then the chance of it being a homograph malware attack would be extremely high, even if it's been patched out in every competent web browser in existence. It was as simple as that.

**Comment by gorhill** [comment]
The way I see it is that uBO's syntax highlighter should report such leading/trailing Unicode whitespace as being ignored (dimmed), which is currently not the case.

**Comment by krystian3w** [comment]
#1118
