### ISSUE TITLE
Do not triggers strict blocking for wildcard-only patterns

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1147]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

 I was testing rules like `||ads.` used by some non-default lists and found `||ads.*^` triggers strict blocking. Then I found https://github.com/uBlockOrigin/uBlock-issues/issues/687 which explains why strict blocking is triggered only for hostname rules by default. Now I tested `||*.*^` and it also does! I guess it's not an intended behavior.

![strict](https://user-images.githubusercontent.com/58900598/87215724-505b3a00-c374-11ea-9ad5-4e8077eb081f.png)

### A specific URL where the issue occurs

Whatever, so I used `https://www.shush.se/` for example.

### Steps to Reproduce

1. Add `||*.*^` or `.*^` to My filters
2. Visit any sites

### Expected behavior:

Too generic rules like this doesn't trigger strict blocking unless `$document` or `$all` is added.

### Actual behavior:

Described

### Your environment

* uBlock Origin version: 1.28.0
* Browser Name and version: Firefox 78.0.2
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
I think this `||ads.*^` is good, `||*.*^` is acceptable, but `.*^` rather not.

**Comment by gorhill** [comment]
`.*^` is equivalent to `.`. Should we really care about such filter? I don't see this sort of filter ever happening in the real world.

**Comment by Yuki2718** [comment]
>  I don't see this sort of filter ever happening in the real world.

Neither do I, probably it doesn't need to be addressed or should be given the least priority. Just wanted to brought your attention as per https://github.com/uBlockOrigin/uBlock-issues/issues/687.

**Comment by gorhill** [comment]
Well @Yuki2718 has a point, since I did something to prevent strict blocking for `|*|`, I logically should do the same for `.*^`. I will first look whether it's a trivial fix, and if not then I doubt I will ever take the time to fix it.

**Comment by gorhill** [comment]
The fix is trivial if uBO checks if the filter starts with `||`, which is what internally happens even if the filter is `example.com`. However I am unable to determine if this will cause unforeseen false negatives, i.e. documents which should have been blocked but end up not being blocked.

**Comment by Yuki2718** [comment]
>  I am unable to determine if this will cause unforeseen false negatives, i.e. documents which should have been blocked but end up not being blocked.

You mean even if $document or $all is used? As that will be the only case strict blocking is required.

**Comment by gorhill** [comment]
The heuristic-based code is not executed when `document` or `all` is used, it's executed only when these are not used, to find out whether the full document should be blocked.

Gave more thought to this and it's best that even that strict-block is not implicit with `||ads.*^`, `||*.*^`, or `.*^`, because all of these would match `https://example.com/toto`, and the purpose of the implicit strict-block heuristic is to avoid strict-blocking document which matches beyond the hostname part, while these filters are meant to block anything up to the end of the URL.

**Comment by Yuki2718** [comment]
@gorhill https://github.com/gorhill/uBlock/commit/3b7a265ee274f82eb70e23195cbda2b510bb3476 caused strict blocing not triggered not only by `||github.` but  also by `||github.*^`. This might cause false negative against click-through tracker or bad sites. How about triggering strict blocking by `||github.`?
