### ISSUE TITLE
Version 1.28.0 in browsers Chrome, Edge, Firefox as of 07/11/2020 @1937 MDT

### ISSUE THREAD

**Issue by kevomac12** [uBlockOrigin/uBlock-issues#1148]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Users can't set options in 1.28, Two (2) options are now available GRAY or RED, in all two browsers (Edge & Firefox). There's no GREEN setting! NOTE: Chrome has not updated to 1.28.0 as of 1948 MDT.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
www.walmart.com
https://www1.swatchseries.to/
www.microsoft.com

### Steps to Reproduce

1. [First Step]
 open ublock origin, select any box
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
I expected to be able to set Gray/Green/Red in the "Local" column

### Actual behavior:

[What actually happened]
options are limited to Gray or Red

### Your environment

* uBlock Origin version: 1.28.0
* Browser Name and version: Edge (Version 83.0.478.61 (Official build) (64-bit)), Firefox - 78.0.2
* Operating System and version: Windows 10 v. 2004

**Comment by llacb47** [comment]
You should read the release notes. https://github.com/gorhill/uBlock/releases/tag/1.28.0

**Comment by kevomac12** [comment]
gooblediegupp, I have used Ublock origin for over three (3) years, and I have protected my system for the 'windows has transgressed/corrupted our server, and therefore you need to call us to fix the error...ransomware. The language used to educate newbies is abysmal and lacking in educating the non-technical...a.k.a not a programmer. From using options correctly and "JOE Bobing with this: 
It's no longer possible to point-and-click to create allow (green) rules from within the popup panel by default. This change is motivated by seeing way too many cases of improper usage of dynamic filtering in which users are creating allow (green) rules where noop (gray) rules should have been used.

Creating allow rules has serious consequences as these override blocking static filters and can potentially disable other advanced filtering ability such as HTML filtering and scriptlet injection -- often used to deal with anti-blocker mechanisms; to the point where misusing allow rules can easily cause a user to be less protected than when using uBO with default settings/lists.
You can get back temporarily the ability to create allow rules from within the popup panel by tappi
REALLY

"The only way to have experience is by having the experience"!
 

    On Saturday, July 11, 2020, 11:27:02 PM MDT, mapx- <notifications@github.com> wrote:  
 
 


Closed #1148.

**Comment by gorhill** [comment]
The purpose of advanced user mode is not to "educate newbie", it's to give power user the tools they would want to have in a content blocker in the same class as Request Policy/NoScript/uMatrix, without having to install a separate extension.

**Comment by kevomac12** [comment]
How is it that you expect all previous users of UBlock to understand the new limitations in 1.28.0 compared to 1.27.10
"The only way to have experience is by having the experience"!
 

    On Sunday, July 12, 2020, 06:56:43 AM MDT, Raymond Hill <notifications@github.com> wrote:  
 
 


The purpose of advanced user mode is not to "educate newbie", it's to give power user the tools they would want to have in a content blocker in the same class as Request Policy/NoScript/uMatrix, without having to install a separate extension.

**Comment by gorhill** [comment]
Sorry, I don't know what point you are trying to make. If you are an advanced user using dynamic filtering, the change should be a non-issue to you. If you consider it an issue, I am going to assume you were misusing dynamic filtering, and now this has been brought to your attention, which is a good thing.

**Comment by kevomac12** [comment]
Thanks!
"The only way to have experience is by having the experience"!
 

    On Sunday, July 12, 2020, 08:14:51 AM MDT, Raymond Hill <notifications@github.com> wrote:  
 
 


Sorry, I don't know what point you are trying to make. If you are an advanced user using dynamic filtering, the change should be a non-issue to you. If you consider it an issue, I am going to assume you were misusing dynamic filtering, and now this has been brought to your attention, which is a good thing.
