### ISSUE TITLE
[FEATURE SUGGESTION] Skipping YouTuber made AD video inserts.

### ISSUE THREAD

**Issue by TheAlienDrew** [uBlockOrigin/uBlock-issues#1149]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Essentially I think it would be a nice idea to include a way for people to report videos on YouTube where the YouTuber has made an advertising segment, and to allow uBlock origin to skip over that part of the video so we don't have to suffer through seeing the ad. Of course, though, it would mean that the first user (or few users), would need to do the reporting in order to get a video recorded into what I would assume would be an online database linked to each video ID.

### A specific URL where the issue occurs

This would be an example video where this link starts at where the YouTuber inserted their ad: https://youtu.be/H7gDEt0m2Wk?t=43

### Steps to Reproduce

[N/A]

### Expected behavior:

[N/A]

### Actual behavior:

[N/A]

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* Operating System and version: Windows 10 Pro Build 1909

**Comment by gwarser** [comment]
https://sponsor.ajay.app/

**Comment by gorhill** [comment]
Declined.

**Comment by Frank-wq2** [comment]
Out of scope of uBO? Too specific?

**Comment by gorhill** [comment]
Both. A dedicated extension to take care of that specific problem from a specific website is best -- even more so that in this case this also requires a dedicated server.

**Comment by Frank-wq2** [comment]
ok! thanks for your feedback!
