### ISSUE TITLE
:has() assertion not working as expected

### ISSUE THREAD

**Issue by trumpeta** [uBlockOrigin/uBlock-issues#115]
I have this in page structure

```
<div useless atributes>
  <div id="....................Start"></div>
  <div useless atributes>
    <iframe id="im-...................." ....>
```

When I need to block the topmost div element with generic class, I write this static filter

`site.com##div:has(div[id$="Start"] + div > iframe[id^="im-"])`

but apparently the filter removes all page content. Does :has assert when and only when the expression is in the first nested level and first-child, or at any nested level and/or child at any position?
How must the filter look like to block what desired?

**Comment by uBlock-user** [comment]
Put back the template and properly fill in the report.

**Comment by gwarser** [comment]
You need to specify that your `div[id$="Start"]` is a direct descendant of `div`.

`site.com##div:has(>div[id$="Start"] + div > iframe[id^="im-"])`

**Comment by trumpeta** [comment]
That was it, thanks
