### ISSUE TITLE
uBlock Origin clients DoS-ing repo.or.cz via urlhaus filter list

### ISSUE THREAD

**Issue by jast** [uBlockOrigin/uBlock-issues#1152]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] N/A uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] N/A using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] (N/A) I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I'm one of the guys who helps run repo.or.cz.

Approximately 7 days ago, the `urlhaus` filter list was added to uBlock Origin, with repo.or.cz as one of the mirror URLs (in `assets/assets.json`). We now have over a million clients regularly trying to fetch filter updates from us, but we're not prepared to deal with this level of activity. The infrastructure is not designed for this, and our server is almost unusable as a result, even though we have already started blocking all requests for these filter lists and returning a 403 error.

(We were not asked before being used as a CDN, but to be fair we didn't ever outright state that our small volunteer-run project isn't equipped to handle mass downloads. In any case, to clarify that we can't support this kind of use case, we've updated our terms of service.)

Please consider replacing the repo.or.cz mirror URL with one of the other ones provided by urlhaus. We will keep returning 403 errors either way.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Install uBlock Origin
2. Let it update its filter lists
3. Repeat a few million times on different hosts

### Expected behavior:

repo.or.cz doesn't get hammered by clients that have uBlock Origin installed

### Actual behavior:

repo.or.cz does get hammered by clients that have uBlock Origin installed

### Your environment

* uBlock Origin version: v1.27.10
* Browser Name and version: any
* Operating System and version: any

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
Sorry about this, I've removed `repo.or.cz` as CDN for urlhaus blocklist.

The resource `assets.json` which I modified is set to update every 13 days, so may take that long before all network requests for urlhaus blocklist ceases completely.

**Comment by jast** [comment]
Thanks! Hopefully we'll survive until then. :)

**Comment by curbengh** [comment]
I'm sorry for listing `repo.or.cz` as a mirror; I put it as the last, I didn't expect this would happen...
I've [removed](https://gitlab.com/curben/urlhaus-filter/-/commit/97bb1ee7fd5bf8dcfb7058e5a65930d703271c8d) it from https://gitlab.com/curben/urlhaus-filter.

> In any case, to clarify that we can't support this kind of use case, we've updated our terms of service.
Many blocklists use `repo.or.cz` as mirror in [FilterLists](https://filterlists.com/), I found 134 links. @jast you may want to raise this concern to https://github.com/collinbarrett/FilterLists.

**Comment by DandelionSprout** [comment]
I too have used repo.or.cz as an official mirror for *Dandelion Sprout's Nordic Filters* for about 2 years. If my lists too were in any way involved in the server overloading, then I was simply never told about it until 5min ago. Moreover I was not informed by anyone about how raw files in repo.or.cz now seemingly cannot be accessed directly from links.
