### ISSUE TITLE
The advanced popup seems broken -- no longer enables me to selectively filter the way I used to -- am I missing something???

### ISSUE THREAD

**Issue by hourback** [uBlockOrigin/uBlock-issues#1153]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Left click on uBlock icon in Firefox toolbar
2. Mouse-over Local Rules column(s)
3. I only see colors grey and dark-blue -- NO green, NO red -- for selective filtering as I used to do.
4. I only see two columns in the Local Rules column section, not three as I saw before.

### Expected behavior:

I expected to see green and red options for local filtering.  I also expected to see three columns in the Local Rules column area.

### Actual behavior:

1. I only see colors grey and dark-blue -- NO green, NO red -- for selective filtering as I used to do.
2. I only see two columns in the Local Rules column section, not three as I saw before.

### Your environment

* uBlock Origin version: 1.28.0
* Browser Name and version: Mozilla Firefox 78.0.1, 64-bit
* Operating System and version: Pop!_OS 20.04 LTS (GNU/Linux)

**Comment by llacb47** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.28.0

**Comment by hourback** [comment]
@llacb47 I swear to god I read that thing!!!!!!!  :-)  :-D  I somehow missed it nevertheless.  I guess I read it too quickly.

Thank you very much for your follow-up.  :-)  <3

**Comment by thany** [comment]
@uBlock-user Fine, close everything leading to this feature request. uBO *does not have* this feature, other than an obscure thing in dangerous dynamic filtering.

People seem to want an easy way to permanently or temporarily allow something. Not by digging deep into all kinds of technical stuff behind the scenes. How hard can it be?
