### ISSUE TITLE
Expired certificate for https://ping.ublock.org

### ISSUE THREAD

**Issue by cpoenaru** [uBlockOrigin/uBlock-issues#1156]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The website at https://ping.ublock.org/ uses a security certificate, that is expired since the 4th of March, 2020.

Besides the obvious problem of using an expired security certificate, having an antivirus installed on your computer will make it even worse. uBlock makes requests to that address, and the AV blocks those requests because of the certificate.

### A specific URL where the issue occurs

https://ping.ublock.org/api/stats

### Steps to Reproduce

1. Navigate to https://ping.ublock.org/api/stats, using Firefox

### Expected behavior:

The webpage should load successfully.

### Actual behavior:

Firefox blocks the webpage, since it has an expired certificate.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox 78.0.2
* Operating System and version: Win 10 x64, 19041

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org
