### ISSUE TITLE
Significant update of locales and mirrors in "assets.json"

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1159]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since I lack the rights to submit PRs to the main repo, I'll outline my intended suggested changes from https://github.com/DandelionSprout/uBlock/blob/patch-1/assets/assets.json here:

* Furthermore locale-to-list assignments for small regional languages.

I ran the `https://stackoverflow.com/a/8199791` code snippet while having set Firefox (or Vivaldi) to 10 languages (Fulah, Kabyle, Songhai, Guarani, Kaqchikel, Triqui, Romansh, Swiss German, Upper Sorbian, Lower Sorbian), one language at a time. That way I could make 100% sure that I would suggest the correct ISO codes for them.

I do presume there's one thing in the PR that warrants an explanation: Why I assigned Azerbaijani to AdGuard Base. The reason is simple enough: `moz-extension://91a5b3e7-6ae1-4749-951f-3dd0b1cf848c/asset-viewer.html?url=adguard-generic` (Lines 11821-12319), whose effort to cover Azeri websites is far beyond what e.g. I could've done.

* Assigned official mirrors to 3 lists.

* Removed a mirror for my list that no longer worked.

* Upgraded the link to Spam404's website to HTTPS.

Additionally it's now more than 12 months since "Icelandic ABP List" was updated that I know of, meaning it's become a candidate for removal from uBO. However, I chose to wait with that part for a later occasion.

### A specific URL where the issue occurs

`https://github.com/gorhill/uBlock/blob/master/assets/assets.json`

### Steps to Reproduce

For part 1 (Later parts seem to lack any need for reproduction steps):

1. Set the browser language to any one of the following 11 languages: Azerbaijani, Fulah, Kabyle, Songhai, Guarani, Kaqchikel, Triqui, Romansh, Swiss German, Upper Sorbian, or Lower Sorbian.
2. Reset uBO's settings.
3. See that no regional lists are chosen by default.

### Expected behavior:

The regional lists corresponding to the biggest languages of the languages' countries, are assigned to those languages; more first-hand-maintained mirrors of lists are put to use; and Spam404's homepage link uses HTTPS.

### Actual behavior:

No regional lists are chosen on new installations for such lists; three official mirrors are not used; and Spam404's homepage link uses HTTP (although it redirects to HTTPS once the homepage is loaded).

### Your environment

* uBlock Origin version: 1.28.2 on Firefox (1.28.0 on Vivaldi)
* Browser Name and version: Firefox 78.0.2 x64 / Vivaldi 3.1.1929.45 x64
* Operating System and version: Windows 10 May 2020 Update

**Comment by krystian3w** [comment]
Your mirror no need also change url?

`https://repo.or.cz/FilterMirrorRepo.git/blob_plain/HEAD:/NorwegianList.txt` - HTTP 200
`https://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/NorwegianList.txt` - HTTP 403

Unless you know something about server-level redirection from `/master:/` to `/HEAD:/`.

PS. I didn't check where or why there's a "/refs/heads/"

**Comment by DandelionSprout** [comment]
I was unaware that the previous mirror link had been changed, so I thank you for pointing it out to me.

As for why the new link is formatted like that, it's at least what the "Raw" button's link on https://repo.or.cz/FilterMirrorRepo.git/tree/refs/heads/master formats it as.

**Comment by DandelionSprout** [comment]
Wait, I now see that https://repo.or.cz/FilterMirrorRepo.git/blob_plain/refs/heads/master:/NorwegianList.txt was in assets.json all along, which is working on my end.

**Comment by uBlock-user** [comment]
They're sending 403 response -- https://github.com/uBlockOrigin/uBlock-issues/issues/1152, you should remove it any list hosted there.

**Comment by krystian3w** [comment]
So the "Czech Republic" 🇨🇿 banishes the Polish 🇵🇱 Internet operator 🕸️ :globe_with_meridians: and AdGuard Ukraine 🇺🇦  VPN?

**Comment by DandelionSprout** [comment]
My guess is they now simply refuse to let raw files be opened through direct links. Which is a rather heavy-handed change on their end, which I honestly would've hoped to be told about by anyone of some sort.

**Comment by krystian3w** [comment]
The question is who and how, because it's definitely not the Norwegian neighborfrom your place at the "coffee"/"tea" or shopping.

**Comment by DandelionSprout** [comment]
When it comes to URLhaus, I suppose it's that the legacy and worldwide spread of uBlock Origin must be *far* bigger than what Firefox's and Chrome's installation counters do. Wouldn't surprise me if uBO has around 200 million installations worldwide, whereas the extension stores' combined count is maybe 35mill.

**Comment by krystian3w** [comment]
Plus every weird fork that `assets.json` has updated.

**Comment by DandelionSprout** [comment]
Closing this in order to spin it off to a "Small languages"-only issue instead.
