### ISSUE TITLE
Sites using delayed ads injection + blocking page to finish (element picker and DOM structure not available)

### ISSUE THREAD

**Issue by trumpeta** [uBlockOrigin/uBlock-issues#116]
There is a dozens of servers that has begun using anti-adblock techniques that prevent page to finish loading if adblocker (even disabled) is detected, and injecting ad frames into page dynamically afterwards page is processed by script with random name. Although there's a set of cosmetic filters that applies to all of the sites, there's still the script that blocks page finishes and causing performance issues.
Can uBO do something to eliminate the adblock detection and suppress the dynamically generated script?

These domains count
novinky.cz
idnes.cz
extra.cz
zive.cz
info.cz
blesk.cz
...and more others with countrycode .cz

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/53
