### ISSUE TITLE
bug: can no longer allow a domain to bypass ublock from ublock ui

### ISSUE THREAD

**Issue by rezad1393** [uBlockOrigin/uBlock-issues#1160]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I used to be able to add a domain to allow list to bypass ublock on that , from ublock UI by clicking on the left side of the box in front of domain name. but now that is gone and I only have ingore and block (grey and red) as options. is this a bug or a feature?

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

open ublock addon from firefox button by clicking on it after opening a website.

### Expected behavior:

there was 3 option for behavior related to domains loaded on a page. bypass(Allow green), block (red) and ignore(noop grey).

### Actual behavior:

now there are two only. grey and red

### Your environment
uBlock Origin v1.28.2
* uBlock Origin version:
firefox  78.0.2 (64-bit)
* Operating System and version:
archlinux rolling release

**Comment by llacb47** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.28.0
