### ISSUE TITLE
Leave politically correct nonsense out of uBlock Origin

### ISSUE THREAD

**Issue by hawkoon** [uBlockOrigin/uBlock-issues#1163]
The whole black/whitelist and master/slave PC thing is such nonsense. They have always been neutral technical terms and they do not need to be changed just because these days it's hip to do so.

Leave politics out of uBlock Origin.

**Comment by gorhill** [comment]
I rather spend my time to keep improving/fixing uBO than to waste time arguing that kind of issue. I don't remember you contributing anything before here, so don't lecture me about how I maintain this project.
