### ISSUE TITLE
Ads showing on lmgtfy.com

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#1164]
### URL(s) where the issue occurs

`https://lmgtfy.com/?qtype=search&t=w&segment=lmgtfy2&is_ad=0&gclid=&q=test&as=0&engine=&media_type=`

Shows ads in uBO (but not in ABP)

### Describe the issue

The following elements aren't being applied `##.ads-bing-bottom`  and `##.ads-bing-top`

### Screenshot(s)

![lgtfy-top](https://user-images.githubusercontent.com/1659004/87836862-b7816d00-c8e5-11ea-9a2c-1b941461ec90.png)
![lgtfy-bottom](https://user-images.githubusercontent.com/1659004/87836873-c10ad500-c8e5-11ea-9d27-5a4fc8e01267.png)

### Versions

- Browser/version: Brave 1.11.97
- uBlock Origin version: 1.27.10

### Settings

-

### Notes

Issue doesn't occur in ABP 3.9.1

**Comment by gorhill** [comment]
Related: <https://github.com/uBlockOrigin/uBlock-issues/issues/688>.

As [per MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts), this also applies to `srcdoc`.
