### ISSUE TITLE
Auto-update should be more aggressive when all assets are seriously outdated. 

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1165]
<details>
<summary>Details</summary>

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

I've checked three of my family's computers few days ago and all three had all lists outdated. This was probably because they use phones most. They use PC maybe once or twice a week to make a bank transfer or watch a movie. I tried reducing autoUpdateDelayAfterLaunch to seconds, and it was not enough - I have seen they used these PC's and list updates were still lagging behind. As I understand lists are updated sequentially from top to bottom, this can seriously affect regional lists.

### A specific URL where the issue occurs

uBO internals.

### Steps to Reproduce

1. update filters
2. turn off PC
3. turn on PC for few minutes every few days

### Expected behavior:

Filters should be kept updated

### Actual behavior:

Filters are outdated, especially regional ones on the end of the list.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Chrome
* Operating System and version: Windows

**Comment by gorhill** [comment]
> I tried reducing autoUpdateDelayAfterLaunch to seconds

Did you try to also reduce [`autoUpdateAssetFetchPeriod`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#autoupdateassetfetchperiod)?

**Comment by gwarser** [comment]
I thought about it, but did not have time to test. It will probably work.

I think in _just after install_ case and when for example one of the lists is outdated more than 2x "Expires" time (or something similar), update should work like manually invoked.

**Comment by Yuki2718** [comment]
Despite fixed 3w before https://github.com/easylist/easylist/commit/5940d2e0589acf5394da11dc1bfa2c7e45907fad, after I removed the corresponding rule https://github.com/uBlockOrigin/uAssets/commit/d648c103f7b02cdfd1826c5c14417e1dcb26af27 I see **three** tweets complaining uBO does not hide promoted tweet. One of them replied to my question and it tunred out EL was not updated on them. How this can happen, is this related to that we now self-host EL? I temporally added to quick to prevent further cases `https://github.com/uBlockOrigin/uAssets/commit/b511598695c643392c3afce5025aaa285bf7473f`.

**Comment by gwarser** [comment]
`https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt`

>! Last modified: Tue, 29 Nov 2022 18:47:39 +0000

Broken CDN.

**Comment by gorhill** [comment]
I removed all instances of `gitcdn.link` from `assets.json`. It's going to take a little while before everybody has that updated version, it updates every ~13 days.

**Comment by Yuki2718** [comment]
BTW now all AG, Brave, and ABP update filter lists everyday (ABP's expl: `https://forum.adblockplus.org/viewtopic.php?t=80359`). This puts uBO disadvantageous position as fixes for breakage, revolving adservers, etc. all take 5d more than other major blocker to reach user. I have repeatedly asked EL maintainer to set 6d period back to 4d but was ignored.

**Comment by gorhill** [comment]
In January, Cloudflare reported the following:

> Cloudflare served 114.34 TB of data
> ▲(159%) traffic since December

Now keep in mind Cloudflare is just one of the 4 servers randomly used to update lists, this means the overall bandwidth requirements is probably 4x the figure reported above. If I was to replace `easylist.to` with `ublockorigin.pages.dev` (Cloudflare), and with an even shorter update period than the default one, this would likely cause me trouble the same way Easylist was in trouble with Cloudflare a few months ago.

**Comment by garry-ut99** [comment]
> BTW now all ...

"quicker interval of filter lists update in uBO" requests have been already declined several times in the past: 
- https://github.com/gorhill/uBlock/issues/1333#issuecomment-178706420
- https://github.com/gorhill/uBlock/issues/3117
- https://github.com/uBlockOrigin/uBlock-issues/issues/2199#issuecomment-1205490004

**Comment by stephenhawk8054** [comment]
I wonder if it's possbile to compress the final text files (the ones currently on github pages and CDNs) before delivering via github actions and uncompress at clients to save the bandwidth?

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/222945143-a09fba1a-c587-433c-97be-35b0d6be81ae.png)

**Comment by stephenhawk8054** [comment]
Oh right, I forgot about that 👍

**Comment by Yuki2718** [comment]
Found one of my Edge Profie with v1.47.2 still have `! Last modified: Tue, 29 Nov 2022 00:47:36 +0000` despite uBlock₀ filters was updated yesterday. Force-update fixed, but I guess some measure is really needed for the title of this issue.

**Comment by gorhill** [comment]
Implemented this way in last commit:

When at least one asset is past update time by more than twice it's update period, an "emergency" update cycle for all assets will be launched. The update cycle will start 15 seconds after launch, and the delay between fetches will be 2 seconds, so typically all assets should be updated within a minute of launch.

Beside addressing the described scenario, an emergency update cycle will also be triggered for people who just installed uBO.

**Comment by Yuki2718** [comment]
Does that fix https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1458106845 too? That is, the list was updated one day before yet it's actual contents was months old.

**Comment by gorhill** [comment]
I can't tell since I don't know what cause this on your side.

**Comment by gwarser** [comment]
I think it works. I had Fx beta profile with over month old filters, after few seconds they started updating ~2s intervals..

**Comment by Yuki2718** [comment]
> I can't tell since I don't know what cause this on your side.

Due to https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1364644643, I believe.

**Comment by Yuki2718** [comment]
Is cdn randomly chosen for every auto-update? If so, https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1458106845 is puzzling with the fact force-update fixed.

**Comment by gwarser** [comment]
> Is cdn randomly chosen

You can be very unlucky? On fourth try:

![image](https://user-images.githubusercontent.com/886325/228220347-06cf4f80-5441-4c26-9899-4ec7ea20a6f6.png)
