### ISSUE TITLE
White stroke on the icon - Better icon suggestion.

### ISSUE THREAD

**Issue by hazarek** [uBlockOrigin/uBlock-issues#1169]
### Description
UblockOrigin Icon is incompatible with light/dark mode backgrounds.
ugly white stroke on the ublock icon, and red tone is too dark.

<img width="552" alt="cap 14" src="https://user-images.githubusercontent.com/36481442/88107001-1299b500-cbaf-11ea-8289-61d355cbd5b5.png">

### New icon suggestion
Current red (#800000) looks too dark on dark backgrounds. I removed the white edge and I changed the color to #DF2F52

<img width="560" alt="cap 7" src="https://user-images.githubusercontent.com/36481442/88108482-9359b080-cbb1-11ea-9892-db66e0a22118.png">

New icon svg file > https://svgshare.com/i/N5z.svg
### Your environment

* uBlock Origin version: v1.28.5b5
* Browser Name and version: Firefox 78.0.2 (64 bit)
* Operating System and version: macOS Catalina 10.15.6

**Comment by hazarek** [comment]
related to dark mode support and new ui design  -> https://github.com/uBlockOrigin/uBlock-issues/issues/401, https://github.com/uBlockOrigin/uBlock-issues/issues/1027

**Comment by hazarek** [comment]
hover color bug. 
![a](https://user-images.githubusercontent.com/36481442/88116442-3e259b00-cbc1-11ea-8830-0fc35e37e37e.gif)

**Comment by gorhill** [comment]
uBO's red has been in use since the 1st day it was published in 2014, I do not intend this to change, it has since long been a distinct visual of uBO.

**Comment by hazarek** [comment]
> Everything flows and nothing stays.
-Heraclitus

![images](https://user-images.githubusercontent.com/36481442/89992040-628b0980-dc8d-11ea-8eec-73ed80777e59.png)

![Mozilla-Firefox-Logo-history](https://user-images.githubusercontent.com/36481442/89992131-84848c00-dc8d-11ea-8e3e-359640567a85.jpg)
![unnamed](https://user-images.githubusercontent.com/36481442/89992182-982ff280-dc8d-11ea-8496-cb87ed9e8ae8.png)
