### ISSUE TITLE
uBlock Origin makes Firefox crash

### ISSUE THREAD

**Issue by drfrag666** [uBlockOrigin/uBlock-issues#1171]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since yesterday night uBlock Origin makes Firefox 78.0.2 crash inmediately. The uBlock version reported is 1.28.2. When it doesn't crash instantly it says the tab has failed and upon reload most of the time uBlock fails and then it always crashes. Sometimes even the desktop turns black, i feared it was a hardware problem. I've disabled the extension.

### A specific URL where the issue occurs

Firefox Start Page

### Steps to Reproduce

Try to launch Firefox with uBlock Origin enabled

### Expected behavior:

The browser doesn't crash.
### Actual behavior:

It crashes all the time.
### Your environment

* uBlock Origin version: 1.28.2
* Browser Name and version: Firefox 78.0.2
* Operating System and version: Win10 1809 64 bit

**Comment by gorhill** [comment]
uBO is HTML/CSS/JS, it's not supposed to cause browser to crash. Report browser craches to Firefox devs: https://bugzilla.mozilla.org/

**Comment by drfrag666** [comment]
Not so quick, it's not a Firefox bug. Now Vivaldi also crashes and it's the same crash, i also have uBlock enabled there.

**Comment by drfrag666** [comment]
Now Vivaldi doesn't crash, it did yesterday. Neither uBlock nor Firefox were updated last night, what the hell happened? I even restarted the machine and it's not a windows update either.

**Comment by gorhill** [comment]
> uBO is HTML/CSS/JS, it's not supposed to cause browser to crash.

If the browser crashes rendering HTML/CSS/JS, it's a browser issue. If you have crash issues across browser, you have a bigger OS issue.

**Comment by drfrag666** [comment]
No OS issues here, only happened with uBlock. I wonder if a corrupted filter list could cause those crashes.

**Comment by mapx-** [comment]
does it happen (only) on some specific page ?

**Comment by drfrag666** [comment]
No, it happens with all pages even the start page in Firefox (no page loaded). Sometimes pages loaded and then it crashed later with another one. In Vivaldi uBlock is the only addon but now Vivaldi works well and will re-enable it in Firefox soon to see what happens.

**Comment by mapx-** [comment]
maybe you should use a clean profile in FF to see if still happens

**Comment by gorhill** [comment]
Submit crash reports to Firefox, browser crashes are not a uBO issue.

Locking thread as this is not a uBO issue and best to not have endless notifications from here.
