### ISSUE TITLE
EasyList FR

### ISSUE THREAD

**Issue by tistoubapt** [uBlockOrigin/uBlock-issues#1173]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Possible to re add EasyList FR (https://easylist-downloads.adblockplus.org/liste_fr.txt) in Region, Language ?

Since some versions of Origin, this list has been replaced by FRA: AdGuard Français

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Edge Canary 86.0.585.0 
* Operating System and version: Windows 10 Pro 2009 x64

**Comment by tistoubapt** [comment]
Hello

Possible to re add EasyList FR (https://easylist-downloads.adblockplus.org/liste_fr.txt) in Region, Language ?

Since some versions of Origin, this list has been replaced by FRA: AdGuard Français

Thanks for your great work

**Comment by uBlock-user** [comment]
Removed due to https://github.com/gorhill/uBlock/commit/3aed2497a384f770b5514b6909596931bb58ab6e

**Comment by mapx-** [comment]
as said here: https://forums.lanik.us/viewtopic.php?p=155849#p155849

**Comment by uBlock-user** [comment]
Removed due to https://github.com/uBlockOrigin/uAssets/commit/529643bdcef9fb67a79153f44c009b5f0f97dfe0

**Comment by tistoubapt** [comment]
Yes, I only saw after my post the information about this change and the response from Intense
Why I closed my post quickly

Thanks so much

**Comment by maxxyme** [comment]
Hello, just noticed this today... since when is that change active?

> as said here: https://forums.lanik.us/viewtopic.php?p=155849#p155849
Moreover this topic is no longer available (removed?).

**Comment by tistoubapt** [comment]
Hello

I didn't even know, maybe a moderator deleted the topic

Regards
________________________________
De : maxxyme <notifications@github.com>
Envoyé : jeudi 6 août 2020 11:03
À : uBlockOrigin/uBlock-issues <uBlock-issues@noreply.github.com>
Cc : tistoubapt <tistou77@live.fr>; State change <state_change@noreply.github.com>
Objet : Re: [uBlockOrigin/uBlock-issues] EasyList FR (#1173)


Hello, just noticed this today... since when is that change active?

as said here: https://forums.lanik.us/viewtopic.php?p=155849#p155849
Moreover this topic is no longer available (removed?).

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/89532307-de9ad280-d7f1-11ea-8cc2-9dffaff687f6.png)

**Comment by tistoubapt** [comment]
Ah yes indeed, thanks
I do not have access to this information, this topic was deleted because it did not follow the rules I think (no relation with a website) ?

Thanks
________________________________
De : mapx- <notifications@github.com>
Envoyé : jeudi 6 août 2020 14:34
À : uBlockOrigin/uBlock-issues <uBlock-issues@noreply.github.com>
Cc : tistoubapt <tistou77@live.fr>; State change <state_change@noreply.github.com>
Objet : Re: [uBlockOrigin/uBlock-issues] EasyList FR (#1173)


[image]<https://user-images.githubusercontent.com/10303732/89532307-de9ad280-d7f1-11ea-8cc2-9dffaff687f6.png>

**Comment by tistoubapt** [comment]
Hello

I have a problem with FRA Adguard Français and a filter I think (I had encountered this problem with [url=https://forums.lanik.us/viewtopic.php?f=91&t=43628&p=150546#p15054]EasyList FR[/url] which had been resolved)
How can I submit it?

The problem : 
![test](https://user-images.githubusercontent.com/40251110/103373695-eaa36b80-4ad5-11eb-9031-7759ffd0b38a.gif)

Thanks
