### ISSUE TITLE
Support new Chromium based Edge in pre-parsing directives

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1174]
<details>
<summary>Details</summary>

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

Sorry, I cannot test this but it looks like Chromium based Edge is now using `Edg` in user agent, and uBO is only scanning `navigator.userAgent` for `Edge` https://github.com/gorhill/uBlock/blob/5c68867b92735931a791dfedf4ef9608cc364862/platform/chromium/vapi-common.js#L89

https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string
https://user-agents.net/browsers/edge/versions/85-0

I'm asking because uBO on MS store is updated very fast and I was thinking about adding YT filters for browsers with v1.28 already released. It was not clear to me which one token should be used in Chrome based Edge, so I looked at source, and looks like it needs to be updated.

### A specific URL where the issue occurs

Filter lists parsing internals.

### Steps to Reproduce

1. Not tested. @nikrolls ?

### Expected behavior:

Ability to detect Edge and Chromium-based Edge in [pre-parsing directives](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives)

### Actual behavior:

?

### Your environment

* uBlock Origin version: 1.28
* Browser Name and version: Chromium base Edge
* Operating System and version:

**Comment by llacb47** [comment]
Not a typo.

![image](https://user-images.githubusercontent.com/16567977/88409059-6c160580-cda2-11ea-93c0-a886bf864663.png)

I can test the user agents.

In latest stable build of Edge legacy (Edge 44.18362.449.0 / EdgeHTML 18.18363):

```

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363"
```

In new Microsoft Edge canary build (Edge 86.0.586.0):

```
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4204.0 Safari/537.36 Edg/86.0.586.0"
```

**Comment by gwarser** [comment]
So all Chromium based browsers will be `chromium` now? OK. I was hoping for per-store variable, but this simplifies things for sure.

**Comment by llacb47** [comment]
EdgeHTML legacy Edge is not based on Chromium...

**Comment by gorhill** [comment]
>  I was hoping for per-store variable

I removed the token because they are unused in either the code base itself or through `!#` pre-parsing directives.
