### ISSUE TITLE
Clear searchbox in my rules and my filters pane

### ISSUE THREAD

**Issue by EdiDD** [uBlockOrigin/uBlock-issues#1176]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

ESC key should clear pattern typed in searchbox in my filters or my rules pane 

### A specific URL where the issue occurs

uBO internal.

### Steps to Reproduce

1. go to my rules (or my filters) pane
2. click on search bar and type pattern you want to find
3. hit ESC key when done

### Expected behavior:

search box will clear

### Actual behavior:

ESC key does nothing

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Firefox 78.0.2
* Operating System and version: Debian bullseye

**Comment by gwarser** [comment]
Do you see such behavior anywhere else?

**Comment by EdiDD** [comment]
Just enhancement suggestion to make searching in rules better.

**Comment by gorhill** [comment]
I am going to decline this, it's not a usual behavior of _sticky_ search field.
