### ISSUE TITLE
What's preventing dev tool integration for element hiding?

### ISSUE THREAD

**Issue by dailytabs** [uBlockOrigin/uBlock-issues#1177]
Would be nice to be able to right click on element in dev tools and use that to create a rule, instead of manually typing out what I need. (The built-in one picks the wrong element nearly everytime I have a use for manual blocking.)

So, what's preventing this? I assume it's the browsers? Has anyone probed them? Is there any current discussions going on? Or, am I alone in this?

**Comment by uBlock-user** [comment]
Support issues and questions are handled at https://old.reddit.com/r/uBlockOrigin

**Comment by dailytabs** [comment]
Fuck reddit.
