### ISSUE TITLE
Left sidebar of Chrome extension has no green fields

### ISSUE THREAD

**Issue by otakukunsan** [uBlockOrigin/uBlock-issues#1178]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I noticed two issues after the most recent update for the Chrome extension:

1. In the left sidebar of the Chrome extension there are no longer any green fields to allow anything. What's really interesting is that domains like yahoo.com that were previously allowed by me on a local level before the update, are now all yellow. The only options available to me are gray and red. It's making life miserable because without the green fields to allow things continue to break.

2. I removed UBlockOrigin from Chrome thinking that perhaps a recent power outage while Chrome was open had corripted the extension. Then I again added UBlockOrigin to Chrome. For quite a few minutes there was no left sidebar, and no way for me to obviously and easily enable it. I'm using Firefox with UBlockOrigin on an Android 6.2 phone, and there's no left sidebar, ever, on that phone. When I want to allow something my only option so far has been to disable UBlockOrigin.

[Description of the bug or feature]

There are no green fields which will allow me to give permission, either globally or locally to any domains detected by your extension. Sometimes there is no left sidebar, or at least it took a dew minutes before it finally displayed itself.
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

Try anything yahoo.com because that's where I've been testing the extension.

### Steps to Reproduce

Install the most recent version of Chrome. Take a stop watch. Add UBlockOrigin to Chrome. Visit yahoo.com. Click on the UBO's browser extension icon, which you may first need to enable and display in Chrome next to the address/omnibar. Click on the icon to open UBO's interface. If there's no left sidebar, use the stopwatch to keep track of time, and keep randomly checking the interface until the left sidebar does appear. Once you can view the left sidebar, verify for yourself that there are no green fields to allow permission either on a local or global level.
1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Without the green fields, UBO turns all manual permissions granted to yellow, which apparently isn't very much different from red. Things are breaking and I can't fix anything because a leve of user permission is no longer accessible. It looks like there is a hierarchy, and without the green fields all assigned green permissions are set to the next closest level. I'm totally expecting everything green will continue to be yellow, and will all need to be manually re-assigned even after the green fields are restored.

[What you expected to happen]

I was expecting pages to load as they had been doing before the recent update.

### Actual behavior:

[What actually happened]

Pages continue to load, but many linked content and user interaction is reduiced due to not being able to allow certain domains via a local or global level. A whole lot of minutes later what I had assigned as green, which was earlier turned yellow, has now been restored to green. Unfortunately there are still no green fields, so I'm not being allowed to grant permission for any new domains.

### Your environment

uBlockOrigin Version 1.28.4

Google Chrome Version 85.0.4183.38 (Official Build) beta (64-bit)

Windows 7 with Service Pack 1 x64

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by mapx-** [comment]
just read
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules

**Comment by uBlock-user** [comment]
Duplicate of #1153

**Comment by gwarser** [comment]
>are now all yellow

Did you changed "Color-blind friendly" preference accidentally? All previously set green/allow rules should be preserved.

**Comment by mapx-** [comment]
@otakukunsan again, did you read what indicated above ? 

![image](https://user-images.githubusercontent.com/10303732/88517385-09fe1000-cfef-11ea-8b15-92b5cfd28419.png)

**Comment by otakukunsan** [comment]
My sincerest apologies. I thought closed meant locked. I'll link the screen capture here, and as I mentioned, the green columns under global and local may appear in a screen capture, but will not be visible through UBO's interface. It may be due to the position of the cursor at the moment the screen capture is taken. Also, I had Yahoo.com set to green locally, and as you should be able to see in the capture, it is yellow. I guess I could read and re-read on dynamic filtering, but the columns are still missing.

[<img src="https://i.ibb.co/k3SVKR4/UBO-For-the-record-1.png" alt="UBO-For-the-record-1" border="0">](url)

**Comment by uBlock-user** [comment]
> but the columns are still missing.

Open advanced settings and set `filterAuthorMode` to `true`.
