### ISSUE TITLE
just read - has nothing to do with my issue

### ISSUE THREAD

**Issue by otakukunsan** [uBlockOrigin/uBlock-issues#1179]
Why would you close a thread before the original poster even has an opportunity to respond?

You want me to read about dynamic filtering? Thanks for telling me what to call the left sidebar. I have a screen grab to show that the dynamic filtering broke after the most recent update, and I'll post it if I can figure out how. 

"just read
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules

_Originally posted by @mapx- in https://github.com/uBlockOrigin/uBlock-issues/issues/1178#issuecomment-664123651_"

**Comment by uBlock-user** [comment]
Read the release notes, this question has been asked repeatedly and is now turning into a major annoyance.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1178 is not locked, so respond there instead of creating new issues for this.
