### ISSUE TITLE
Cursor jumps to next matched item when adding char to search

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#118]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Cursor jumps to next matched item when adding char to search

### A specific URL where the issue occurs

chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=easylist

### Steps to Reproduce

1. Open EasyList (Dashboard->Filter Lists->EasyList)
2. Type "subdocument" in search field (wait for the search to complete before typing next char)

### Expected behavior:
Cursor at 1st matched entry on 42nd line (&admid=$~subdocument)

### Actual behavior:
After "s" - 1st line
After "su" - 11th line
After "sub" - 42nd line
After "subd" - 562nd line
After "subdo" - 711th line
and so on...

### Your environment

* uBlock Origin version: v1.16.13b2
* Browser Name and version: [Chromium 67.0.3396.99 x64](https://github.com/henrypp/chromium/releases/tag/v67.0.3396.99-r550428-win64)
* Operating System and version: Windows 10 v1607 (14393.2339)

**Comment by uBlock-user** [comment]
If you input the whole word instead of adding individual chars in one go, then it matches the first entry - 

![](https://i.gyazo.com/8a5088b6c20dfac65b26d1274b17bb04.png)

**Comment by uBlock-user** [comment]
After performing few searches, this is what I observed -

Whenever you add/remove a character from search field, the search parameter changes and becomes the last modification of the search parameter and that triggers a new search, that is why you're seeing jumps inn highlighted results with the addition of each new chars. This is most likely a by-design behaviour rather than a bug, but I will wait for gorhill to weigh in.

**Comment by gorhill** [comment]
I consider this a valid bug. When the search expression changes, the search should start from the cursor position rather than the end of the current selection.
