### ISSUE TITLE
Screnn grab of broken dynamic filtering

### ISSUE THREAD

**Issue by otakukunsan** [uBlockOrigin/uBlock-issues#1180]
[<img src="https://i.ibb.co/k3SVKR4/UBO-For-the-record-1.png" alt="UBO-For-the-record-1" border="0">](url)

You told me to repost to show what steps I did to replicate the issue I'm having with dynamic filtering being broken, so I've re-posted my original text. I'm inckluding a screen grab so you can see exactly how the interface appears on my computer. TL; DR - The update broke the dynamic filtering. Yahoo.com is in yellow when it should be green, and the green column under both global and local is missing.

And just an FYI - sometimes when performing a screen capture, the green columns will show up in the capture, but does not appear in the UBO interface. It seems to be related to the position of the cursor when the screen capture is taken.

"!-- Do NOT delete this template or any part of it when submitting your issue -->

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I noticed two issues after the most recent update for the Chrome extension:

1. In the left sidebar of the Chrome extension there are no longer any green fields to allow anything. What's really interesting is that domains like yahoo.com that were previously allowed by me on a local level before the update, are now all yellow. The only options available to me are gray and red. It's making life miserable because without the green fields to allow things continue to break.

2. I removed UBlockOrigin from Chrome thinking that perhaps a recent power outage while Chrome was open had corripted the extension. Then I again added UBlockOrigin to Chrome. For quite a few minutes there was no left sidebar, and no way for me to obviously and easily enable it. I'm using Firefox with UBlockOrigin on an Android 6.2 phone, and there's no left sidebar, ever, on that phone. When I want to allow something my only option so far has been to disable UBlockOrigin.

[Description of the bug or feature]

There are no green fields which will allow me to give permission, either globally or locally to any domains detected by your extension. Sometimes there is no left sidebar, or at least it took a dew minutes before it finally displayed itself.
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

Try anything yahoo.com because that's where I've been testing the extension.

### Steps to Reproduce

Install the most recent version of Chrome. Take a stop watch. Add UBlockOrigin to Chrome. Visit yahoo.com. Click on the UBO's browser extension icon, which you may first need to enable and display in Chrome next to the address/omnibar. Click on the icon to open UBO's interface. If there's no left sidebar, use the stopwatch to keep track of time, and keep randomly checking the interface until the left sidebar does appear. Once you can view the left sidebar, verify for yourself that there are no green fields to allow permission either on a local or global level.
1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Without the green fields, UBO turns all manual permissions granted to yellow, which apparently isn't very much different from red. Things are breaking and I can't fix anything because a leve of user permission is no longer accessible. It looks like there is a hierarchy, and without the green fields all assigned green permissions are set to the next closest level. I'm totally expecting everything green will continue to be yellow, and will all need to be manually re-assigned even after the green fields are restored.

[What you expected to happen]

I was expecting pages to load as they had been doing before the recent update.

### Actual behavior:

[What actually happened]

Pages continue to load, but many linked content and user interaction is reduiced due to not being able to allow certain domains via a local or global level.

### Your environment

Windows 7 with Service Pack 1 x64

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:"

**Comment by uBlock-user** [comment]
> UBO turns all manual permissions granted to yellow

Run the logger and see what's being blocked, "yellow" here designates some network requests are blocked. This is a case of filterlist issue, not uBO being broken.

**Comment by uBlock-user** [comment]
> verify for yourself that there are no green fields to allow permission either on a local or global level.

Open advanced settings and set `filterAuthorMode` to `true`.

**Comment by otakukunsan** [comment]
[<img src="https://i.ibb.co/R0jmVVF/No-filter-author-mode.png" alt="No-filter-author-mode" border="0">](url)

I've been up all night trying to figure out why I no longer have green columns, so I need sleep. However, if the screen capture is the advanced settings you wanted me to access, maybe I'm too tired to see straight, but I can't find "filterAuthorMode".

As far as the yellow, it turns out yahoo is using the "geo" subdomain to try to identify my location, and "api" "beacon" something. It might be to try and send me personalized or localized ads, so I'm fine with the yellow. Both happened at the same time, so I wasn't sure if they were related or not. Now I know that they aren't. And again, the green columns in the dynamic filtering suddenly disappeared after the most recent update. I'm not claiming that the update is responsible, but I did remove the extension, and then added it again to see if it would fix the issue. It did not.

**Comment by otakukunsan** [comment]
I was up all night trying to figure out why I lost the green columns, and at first I couldn't find the flag, but eventually I did. I set it to true, and the green columns have returned. I even exited the browser and started it up again just to be safe. I'm not claiming that the update is responsible, but that the green disappeared when I tried using UBO after the update. I have no idea what the flag values indicate because I've never used the advanced settings.

The logger shows that the "geo" subdomain, and an api/beacon is being blocked? I think geo is used to identify my location, and if I remember right beacon is for someone's localized or personalized ads. So yellow was never related, which reduces my headache. I do truly appreciate all the assistance, but I'm lost as to what the flag value tells you.

**Comment by uBlock-user** [comment]
> I do truly appreciate all the assistance, but I'm lost as to what the flag value tells you.

Read the wiki for that. It details everything related to popup panel.

**Comment by otakukunsan** [comment]
I just read the Wiki, and it's worded perfectly for people who aren't tired or new to using UBO. That's not a complaint. I've been using UBO for at least 3 years, and I've always had the green columns for manually assigning permission. The Wiki says that the flag is false by default, and if I never used the advanced settings, then this would be the first update that changed that specific flag value to default. Again, my apologies for the multiple invalid threads. I did try to delete them, but I couldn't. Thank you again, and take care.

**Comment by gorhill** [comment]
Read the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.28.0) please.

**Comment by otakukunsan** [comment]
Well thank you for that. The release notes were much easier to understand than the Wiki due to how much the Wiki seems to refer to the code which I've never seen previously.

I may be implementing permissions incorrectly, but sometimes I can't view third-party embedded video with the grey option. I prefer to use the green as a kind of last resort testing method. If green works but grey doesn't, I often go back to neutral or default, and just search for the original video source.

While I still have your attention, and for future reference, what is the easiest way to display the release notes after the browser extension has been updated? I will defer to that before posting to the issue tracker going forward. Thank you.

**Comment by uBlock-user** [comment]
> what is the easiest way to display the release notes after the browser extension has been updated?

There's none.

**Comment by uBlock-user** [comment]
> what is the easiest way to display the release notes after the browser extension has been updated?

Dashboard > About pane > Changelog

**Comment by Marsfan** [comment]
After reading through this issue (as the disappearance of allow surprised me), I realized that I am apparently not using uBlock in the most efficient way.
I have all filter lists enabled to maximize blocking of known trackers, and have used the `local *Allow* (green) mode to allow through to a domain to un-break a website.

An example would be https://gis.ncdc.noaa.gov/maps/ncei/radar. A first party script that is blocked keeps the page from loading properly.
<details>
<Summary>Image from the page</Summary>

![image](https://user-images.githubusercontent.com/9311953/88952430-0f609200-d25d-11ea-9103-39934f4e9d9c.png)

</details>

By using a local *Allow* rule for the domain gis.ncdc.noaa.gov the webpage would start working again. 

In the wiki, it states that this is not the optimal way to do this, but it is not clear (at least to me) as to what the proper way of unbreaking this website should be. Now that the allow mode is hidden, the wiki should be clearer about what the better method is for letting through scripts that break the page if blocked.

**Comment by gorhill** [comment]
The idea is not to forbid _allow_ rules, the idea is to prevent people from assuming it's the way to fix broken sites when using medium/hard mode. The need to use _allow_ rules should be rare, and thus having to tap twice <kbd>Ctrl</kbd> should not be seen as a huge burden. So by all mean create an _allow_ rule to fix the above case, even better, report the breakage to filter list maintainers.

**Comment by Marsfan** [comment]
@gorhill Sounds good. I normally report issues, and use that as a temporary measure. 
What would be optimal in most cases then? Should I use the logger to track down the exact script blocked and unblock it that way?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/d45a509cc2fadde8e7d7111595bf4fea28778965
