### ISSUE TITLE
Use ISO8061 dates in user filter comments

### ISSUE THREAD

**Issue by C0rn3j** [uBlockOrigin/uBlock-issues#1182]
### Prerequisites

- [X] I verified that this is not a filter issue
- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently the extension puts dates in a format relevant to the locale. 
I propose to unify this to YYYY-MM-DD as per ISO 8061.
Many locales use MM-DD-YYYY which is confusing, ISO 8061 is standardized and YYYY-DD-MM never occurs.

The change to make this happen: https://github.com/C0rn3j/uBlock/commit/19a54ada6b28021550c88ded6e58836c2eb0fa3d

### Steps to Reproduce

1. Create a filter
2. Look at the code

### Actual and Expected behavior:

![image](https://user-images.githubusercontent.com/1641362/88543495-54e04d80-d018-11ea-9cba-0b1410e66c47.png)

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Chromium 84.0.4147.89
* Operating System: Arch Linux

**Comment by gorhill** [comment]
> Many locales use MM-DD-YYYY which is confusing

I don't see why this is an issue, those dates are to be understood by whoever is using the current locale.

**Comment by C0rn3j** [comment]
For example, I myself am Czech, but have en-US set as my locale as I prefer to have my system in English.

The date format uBlock uses on my system is nonsensical to me as an European, but the ISO standard is easily understandable by all Europeans, Americans and other nationalities.

**Comment by krystian3w** [comment]
Maybe try `en-GB`? Unless you know American English better than British and you don't understand 99% of the British word variety.

**Comment by gorhill** [comment]
Thanks, I pulled your changes in <https://github.com/gorhill/uBlock/commit/3fed25a52da5120c71d10bc94fc404ab50581764>.

**Comment by stubbornGarrett** [comment]
Just a little formal note:
Shouldn't it be [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)? Unless you mean [Alpine ski-bindings — Selection of release torques values](https://www.iso.org/standard/75609.html).

**Comment by krystian3w** [comment]
Or try use `en-GB` if have date `day-month-year`.

**Comment by C0rn3j** [comment]
Yeah I totally swapped the numbers around and I am deathly afraid of skiing.

**Comment by krystian3w** [comment]
A popular bug - it's full of it in the Internet and memos.

![obraz](https://user-images.githubusercontent.com/35370833/89827988-b1835280-db58-11ea-888d-eafd16998b75.png) |
--- |

**Comment by krystian3w** [comment]
Can you look into these bug:

https://old.reddit.com/r/uBlockOrigin/comments/1bxz6oi/ (https://github.com/gorhill/uBlock/commit/a5f6c35bb091d26693fd1f7986e499905b7b8e73)

**Comment by C0rn3j** [comment]
This issue was closed 4 years ago, please make a proper new bug report instead.

**Comment by krystian3w** [comment]
But you asked as feature request, you no longer use my filters pane with comments?
