### ISSUE TITLE
Keep saved sites where java scrip were allowed 

### ISSUE THREAD

**Issue by AndersonGI** [uBlockOrigin/uBlock-issues#1183]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Add a kind of "whitelist" for sutes where the user let java script runs
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce
1.enable java script 
2. close the browser
3. open the same site/domain
1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:
I expected that the site where java script was allowed before goes to a kind of white list, not to enable every time I open the site again when I open the browser. 
[What you expected to happen]
Not have to allow javascript to run in the same site/domain every time I opem my browser. 
### Actual behavior:
Every time I have to allow java script, mostly in the same sites I frenquently go. 
[What actually happened]

### Your environment

* uBlock Origin version: v1.28.4
* Browser Name and version: Vivaldi-snapshot 3.2.1967.30 
* Operating System and version: Ubuntu 20.04.1

**Comment by gorhill** [comment]
Click the padlock if you want your change to be permanent -- it's explained at the top of [the per-site switches documentation](https://github.com/gorhill/uBlock/wiki/Per-site-switches):

> Changes to the state of per-site switches are temporary until you make them permanent by clicking the padlock icon. Pressing <kbd>Ctrl</kbd> (<kbd>Cmd</kbd> on Mac) when toggling switches will make them permanent immediately.
