### ISSUE TITLE
Open tabs can be closed when opening a webpage from `about:newtab`, with uBlock Origin installed on Firefox

### ISSUE THREAD

**Issue by ItielMaN** [uBlockOrigin/uBlock-issues#1184]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As in the title. Full STR below.

### A specific URL where the issue occurs

```
https://www19.gogoanime.io/
https://pontoon.mozilla.org/he/amo/all-resources/?string=66616
```

### Steps to Reproduce

1. Create a new profile on the latest Nightly
2. Install uBlock Origin from AMO. Don't change any of the extension's default settings
3. Add a new top site on the New Tab page with the title being "pontoon.mozilla" and its url being "`https://pontoon.mozilla.org/he/amo/all-resources/?string=66616`"
4. In a new tab, open this url: `https://www15.gogoanime.io/`. Wait for it to load and restart Nightly
5. On a new tab, middle click the "pontoon.mozilla" top site
6. While still on the same New Tab page, focus the urlbar, start typing "gogo", use the arrow keys to focus and enter the "`https://www15.gogoanime.io/`" entry from step 4

### Expected behavior:

 The gogoanime site is opened in the first tab, and the Pontoon tab is still opened. You're left with 2 tabs.

### Actual behavior:

 The "pontoon.mozilla" tab opened in step 5 is now closed, and the gogoanime site is opened. You're left with 1 tab.

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Firefox Nightly 81.0a1 (latest)
* Operating System and version: Windows 10 build 1909

Notes:
1. I haven't checked the first checkbox above as I'm still not sure if this is a Firefox bug, a uBlock Origin bug or a filter bug.
2. I've reported this at bugzilla in [bug 1655339](https://bugzilla.mozilla.org/show_bug.cgi?id=1655339), there's a regression range there but I'm unable to bisect further to see which is the exact regressor.
3. I've filed this here just in case this has nothing to do with Firefox's implementation.

**Comment by uBlock-user** [comment]
> The "pontoon.mozilla" tab opened in step 5 is now closed, and the gogoanime site is opened. 

By-design, firefox behavior.

**Comment by ItielMaN** [comment]
> By-design, firefox behavior, because what you did in step no 4.

I'm not sure I'm following.
In step 4 I just entered this site so it'd be in the history, so in step 6 I'd be able to select it from the urlbar autocomplete, in a completely different tab.

**Comment by gorhill** [comment]
As per logger, it's a filter issue:

![f](https://user-images.githubusercontent.com/585534/88713127-cc7dad80-d0e8-11ea-849e-a8431c033eaf.png)

EasyList's `^https?:\/\/.*[&%+=]/$popup,domain=0123movies.com|...` is causing this.

**Comment by uBlock-user** [comment]
It's not just in history, you opened a tab and then you restarted Nightly(you didn't clarify how to restart Nightly, so I used `about:restartrequired`) and that tab came back after restarting Nightly, so Firefox will not open a new tab if the website is already opened in an existing tab.

**Comment by gorhill** [comment]
> As per logger, it's a filter issue:

One thing to still investigate, is why `pontoon.mozilla.org` is seen as the opener of `www19.gogoanime.io`.

**Comment by uBlock-user** [comment]
I set the logger to all and not seeing any popup entry appear.

**Comment by gorhill** [comment]
When investigating popups, it's best to set logger output to _All_ to be sure nothing is missed.

**Comment by uBlock-user** [comment]
Yes, as said in https://github.com/uBlockOrigin/uBlock-issues/issues/1184#issuecomment-665240763, I did set it to `All`, no popup entry appears in the logger.

**Comment by gorhill** [comment]
Well I just followed exactly the repro steps and I can reproduce without problem. Step 6 has to be executed before 10-second elapsed, since this is the delay after which uBO won't consider the new tab to be a popup.

**Comment by gorhill** [comment]
The issue is as follow:

- Tab A = `about:newtab`
- Open new tab B from tab A and navigate to page at `pontoon.mozilla.org`
- Tab B = page at `pontoon.mozilla.org`
- Result: uBO thinks tab B was opened through tab A (true)
- Navigate to `www15.gogoanime.io` in Tab A
- Result: uBO still thinks tab B was opened by tab A, and this time there is a matching popup filter telling uBO that if `www15.gogoanime.io` opens a new tab matching a rather broad regex, close tab B.

Normally, uBO will detect that tab B was opened willfully through user interaction, but uBO can't execute code in `about:newtab`, so it does not get the information as to whether the tab was opened through user interaction or programmatically by malicious JavaScript.

Not sure what the fix will be at this point, but it looks like uBO should mind the timing, i.e. tab A is navigated through a new destination and thus the tab previously opened through tab B should no longer matter.

**Comment by i2324561w2** [comment]
Sorry, but:

1. open https://iqdb.org/?url=https%3A%2F%2Fwww.animeclick.it%2Fprove%2Fimg_tmp%2F86689.jpg
2. middle click TinEye and let it load
3. click on Gelbooru
4. TinEye tab is closed

is this problem related to the one I just posted?

**Comment by gorhill** [comment]
@i2324561w2 What you describe is <https://github.com/uBlockOrigin/uBlock-issues/issues/250>.
