### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by Daisenki** [uBlockOrigin/uBlock-issues#1185]
With the last Firefox versions the rollout a few things for service workers, I thought developers would start to work on extensions or settings to manage the service workers?

Many wikis recommend to turn the service works off with set dom.serviceWorkers.enabled to false, but unfortunately some websites doesn't work without service workers. All I want is a blacklist or a whitelist for the service workers. The available extensions doesn't do that or I don't get it.

Can uBlockOrigin support any control for service workers? I don't want a service worker from every second trash website that I visit, only from the websites the really need one.

Or is there any way to avoid the service workers from staying? Maybe changing dom.serviceWorkers.idle_extended_timeout or dom.serviceWorkers.idle_timeout to a low number so Firefox delete them?

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.

**Comment by uBlock-user** [comment]
Support issues and questions are handled at https://old.reddit.com/r/uBlockOrigin/
