### ISSUE TITLE
Whitelist via Group Policy

### ISSUE THREAD

**Issue by TGWN** [uBlockOrigin/uBlock-issues#1186]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Group Policy settings were not being applied]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [The HKLM hive path was misspelled : HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\3rdparty\extentions ]
2. [Renamed extentions to extensions]
3. [White list via GPO now appeared in the Dashboard whitelist
### Expected behavior:

[What you expected to happen]

### Actual behavior:

[Issue resolved]

### Your environment

* uBlock Origin version:1.28.4
* Browser Name and version: Chrome 84.0.4147.105
* Operating System and version: WIndows 10 1709

**Comment by gorhill** [comment]
What is this?

**Comment by TGWN** [comment]
A bug and the workaround.  HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\3rdparty\extentions 
I renamed to last Key name in the path to extensions and the GPO now worked.  Does the Google Team create the reg path for 3rd party extensions ?

**Comment by TGWN** [comment]
Correction for my last comment:
I renamed the last Key name (extentions) in the path to extensions and the GPO now worked.

**Comment by gorhill** [comment]
uBO has nothing to do with your OS, it's just HTML/CSS/JS and can't modify anything in your OS.
