### ISSUE TITLE
Indicate to users about updates

### ISSUE THREAD

**Issue by Marsfan** [uBlockOrigin/uBlock-issues#1187]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
(I have not checked off for re-producing in a clean browser image, as this is a suggestion, rather than a bug tracking attempt)

When I was looking at #1180, I realized that certain aspects of  the user interface had undergone changes that I was unaware of. In my opnion, when something is changed that can affect the end-user's experience, there should be a way to proactively inform them of the change, instead of requiring them to look it up on the changelog, GitHub release page, or elsewhere. 

uBlock should have a (non-intrusive) way to indicate to users that it has been updated, especially if it will make changes that can effect the user experience. 

I specify non-intrusive as I believe that this is an important aspect. Extensions that open a new tab in my browser just to tell me that they received an update is an intrusive annoyance of the type that uBlock users are trying to avoid. 
I do not have a firm idea of what a non-intrusive notification should be, but I do have a few general ideas of things that could be used:
* Notification dot on toolbar icon
* Toolbar icon changes color
* Message appears in at bottom of popup user interface. 
 

### Steps to Reproduce

1. Wait for uBlock to update itself

### Expected behavior:

When uBlock origin receives an update, the user should have some sort of non-intrusive indication that it has been updated.

### Actual behavior:

No indication of update is presented

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Firefox Beta 80.0b1 (64-bit)
* Operating System and version: Windows 10 2004 (64-bit)

**Comment by esotericDisciple** [comment]
Is it listed in the updates whether or not the removal of the ability to put anything in the "green" in the toolbar drop-down menu for waterfox-current desktop users was intentional, or is that a bug (which it should be)?

**Comment by gorhill** [comment]
I am declining this. Such request could apply to all extensions, so best to ask browser devs to support such notifications.
