### ISSUE TITLE
Only red and grey options on advanced mode

### ISSUE THREAD

**Issue by dotlineX** [uBlockOrigin/uBlock-issues#1188]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
While "I am an advanced user" setting is on. I can not allow domains (the green selection) I only have gray and red. I have tried it on a clean install of firefox and a firefox profile. No difference.
![image](https://user-images.githubusercontent.com/59593757/88970718-93e1fd80-d2bb-11ea-9ef9-35259ffdb424.png)

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Install Firefox
2. Get Ublock origin
3. ????

### Expected behavior:

Have a "allow" option

### Actual behavior:

No allow option

### Your environment

* uBlock Origin version: v1.28.4
* Browser Name and version: Firefox 79 and 80 (Beta). Both don't work
* Operating System and version: Windows 10

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/88972175-6e51f580-d2b5-11ea-8086-4feb37b9e324.png)

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1153
