### ISSUE TITLE
A small list of typos in the docs

### ISSUE THREAD

**Issue by lkintact** [uBlockOrigin/uBlock-issues#1189]
### Prerequisites
- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question

### Description
1. https://github.com/gorhill/uBlock/wiki/Element-picker
_you may need to bypass the browser cache when you reload the page -- hold down the key when you click the reload button_
should probably be
_you may need to bypass the browser cache when you reload the page -- hold down the `Ctrl` key when you click the reload button_

2. https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters
_For example, an :xpath(...) operator could be use to create a new resultset_
should be
_For example, an :xpath(...) operator could be use`d` to create a new resultset_

3. https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters
_The element picker always prefix automatically with the hostname to ensure created cosmetic filters are specific_
should probably be
_The element picker always prefix`es the filter` automatically with the hostname to ensure created cosmetic filters are specific_

4. https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters
_Thus this ensure compatibility with the existing CSS :not(...) pseudo-class_
should be
_Thus this ensure`s` compatibility with the existing CSS :not(...) pseudo-class_

**Comment by gwarser** [comment]
@lkintact you can fix it here: https://github.com/uBlockOrigin/uBlock-issues/wiki

**Comment by lkintact** [comment]
@gwarser Thanks for the link, closing.
