### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by Jap2-0** [uBlockOrigin/uBlock-issues#1191]
About halfway down the Readme, in the section "Installation," there is the typo "uBO mat also be installable as a Debian package" (should be "uBO may").

**Comment by opusforlife2** [comment]
Whoops. I tried to fix the typo via a PR. Turns out I can't submit one?

**Comment by Jap2-0** [comment]
Yeah, I did the same thing.  I believe PRs are limited to previous contributors most of the time (to prevent spam or something).
