### ISSUE TITLE
uBlock reverts "allow javascript" on enabled domains

### ISSUE THREAD

**Issue by addeps3** [uBlockOrigin/uBlock-issues#1192]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have set default behavior to block java script. 
After x amount of hours, the domains I have set to "enable" are blocked once again, and I have to do more work by enabling them all over again.

### A specific URL where the issue occurs
www.twitter.com
www.youtube.com

### Steps to Reproduce

1. Change default behavior.
2. Visit new site. 
3. Enable JS.
4.Wait til the next day. 
5.Visit it again. 

### Expected behavior:
I dont want to repeat the same task more than once. 
I understand the risks of permanent setting, but I'm an adult, I'll live with the fact if my credit card gets scammed for my money in the bank. 

### Actual behavior:

uBlock reverts "allow javascript" on enabled domains

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version:  Firefox 79.0 (64-bit)
* Operating System and version: Arch, 5.7.11-arch1-1

**Comment by gorhill** [comment]
uBO does not modify your ruleset on its own, only you can do so through it's user interface. I've never had such issue, and there is no widespread report of such issue.

**Comment by addeps3** [comment]
> uBO does not modify your ruleset on its own, only you can do so through it's user interface. I've never had such issue, and there is no widespread report of such issue.

Ok. So default behaviour is **supposed** to remain permanent, correct?

**Comment by addeps3** [comment]
> To make it permanent you need to click on the **padlock** button in the popup panel, otherwise it is `temporary` by default.

Ah! Wonderful!
Resolved! I'll let you do the honors and close (for personal prestige ofcourse) :=)

**Comment by gorhill** [comment]
> Ah! Wonderful!
> Resolved!

> - [x] I checked the documentation to understand that the issue I report is not a normal behavior

[Documentation](https://github.com/gorhill/uBlock/wiki/Per-site-switches):

> Changes to the state of per-site switches are temporary until you make them permanent by clicking the padlock icon.

**Comment by uBlock-user** [comment]
I suggest you read the wiki first and foremost if you plan on using Dynamic Filtering rules.
