### ISSUE TITLE
Chrome version stopped working with Chrome Beta 85.0+

### ISSUE THREAD

**Issue by fleetcommand** [uBlockOrigin/uBlock-issues#1193]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi,

Since the latest Google Chrome Beta (85.0.4183.48 at this moment) the extension stopped working. It doesn't block ads, also, if I try to open the uBlock settings, all the pages are empty:

![image](https://user-images.githubusercontent.com/614523/89125124-79d33580-d4dc-11ea-8e2b-4897c5a143a6.png)

I tried to search the issue tracker for this report, but I could not find it (hope it's not a dupe). But I am pretty confident I am not the only one facing this, as the Chrome Web Store page is full of "not working" comments in the last couple of days.

If I can provide any info, please let me know.

Thank you,

FleetCommand

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Update to Chrome Beta
2. The extension stops working

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Google Chrome Beta 85.0.4183.48, x64 version
* Operating System and version: Windows 10 x64 en_US

**Comment by gwarser** [comment]
Go to `chrome://extensions/?id=cjpalhdlnbpafiamejdnhcphjbkeiagm`, enable Developer mode in top-right corner, click on "Inspect views" "background.html", look for errors in console tab.

**Comment by fleetcommand** [comment]
Hi @gwarser,

Thanks! It doesn't show any error for the background.html. It shows one error though for the Dashboard, but not much.. this is all what I could get out of it so far:

![image](https://user-images.githubusercontent.com/614523/89125764-067ff280-d4e1-11ea-9fe3-421a0610cd84.png)

**Comment by gorhill** [comment]
Please try in a new profile as per template.

Do other content blockers work?

**Comment by llacb47** [comment]
Can't reproduce on Chromium x64 portable 86.0.4221.0 or Chrome beta portable 85.0.4183.48. The extension dashboard and blocking work normally.

**Comment by fleetcommand** [comment]
Ah, sorry, it's my bad. I was thinking I cannot install extensions on a new profile without logging in first, otherwise I would have tried it.

It worked fine in a new profile. Then I went back to the original and wondered how to get it work again, so disabled, removed and reinstalled a few extensions (I do not have much.. just uBlock, BTTV and some Google Docs-related thing noone asked for), then re-enabled everything and now it started working again. It's a little strange though, would be good to see what causes it to break with browser update, but I guess it doesn't worth the effort.

Thanks for your time! Have a great weekend!

**Comment by vith** [comment]
This has been happening to me intermittently for a while now.

I'll notice I have ads on a page (seemingly always stackoverflow in my case). I click the uBlockOrigin icon but the popout menu won't open, and the settings dashboard is blank just like @fleetcommand's screenshot, with the same error in the console as mentioned above.

Going to the extensions list and toggling disable/enable fixes it immediately, but today it also started working again after I enabled development mode to try to check for extension errors without ever disabling the extension or restarting the browser.

Unfortunately I don't have any reliable repro steps yet.

I have a ton of other extensions but it only occurs once every few days on average; I can't practically narrow it down by disabling other extensions. I do have the BTTV extension in common with the original reporter, though.

Browser: Chromium Version 87.0.4280.141 (Official Build) Arch Linux (64-bit)

I don't expect this info is enough to go off of yet, but maybe if more users chime in later, stronger patterns will emerge.

**Comment by jason-techtailor** [comment]
Happened again today, this is what was in the browser console for the page:

(that's uBlock Origin's contentscript.js)
![image](https://user-images.githubusercontent.com/74046534/104698090-172fc800-5711-11eb-904b-3b5fecdea667.png)

**Comment by vith** [comment]
Happened again today, these errors from uBlock Origin's contentscript.js were in the browser console for the page:

```
(62) Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

Uncaught (in promise) TypeError: Cannot read property 'shutdown' of undefined
    at stop (contentscript.js:297)
    at contentscript.js:260
```

![image](https://user-images.githubusercontent.com/3265539/104698532-c79dcc00-5711-11eb-9898-349c844ea24e.png)
