### ISSUE TITLE
False positive on malwaredomains list

### ISSUE THREAD

**Issue by exadeci** [uBlockOrigin/uBlock-issues#1194]
This isn't a Ublock issue per se but http://www.malwaredomains.com/ hasn't been updated since 2018 so I wasn't sure of where to report this.

### Description

The website is the one of a legitimate business https://goo.gl/maps/1UvCTVaroK7gADA58

### A specific URL where the issue occurs

https://batterymart.com.au/

### Steps to Reproduce

1. Head to https://batterymart.com.au/
2. Ublock blocks it
3. The blocking comes from https://mirror.cedia.org.ec/malwaredomains/justdomains

### Expected behavior:

The website should load

### Actual behavior:

The website gets blocked by Ublock

**Comment by uBlock-user** [comment]
MDL has been removed from uBO's stock lists and replaced with _Online Malicious URL Blocklist_. You should remove it too from custom list section.
