### ISSUE TITLE
Performance regression in rendering of dashboard pane [Chromium 84]

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1196]
### Description

Today I was updated to Chromium 84 and I noticed a significant page load stall when loading the _"Filter lists"_ pane. Upon short investigation, the issue appears to be related to the use of SVG-based icons through:

    <svg class="fa-icon_eye-open">
        <use href="/img/fontawesome/fontawesome-defs.svg#eye-open"></use>
    </svg>

Image from @yourduskquibbles<br>![Chrome 84 vs. Chrome 85](https://user-images.githubusercontent.com/22258847/89420929-6523b700-d701-11ea-884b-9b0a784f4917.png)

The same issue seems to also cause uBO's dashboard to use an undue amount of memory.

The issue is not present in Firfefox.

### Steps to Reproduce

1. Open uBO's dashboard
2. Select the _"Filter lists"_ pane

### Expected behavior:

Pane content displays immediately.

### Actual behavior:

Pane load stalls.

### Your environment

* uBO 1.28.4
* Chromium 84.0.4147.105 (Official Build) Built on Ubuntu

**Comment by gorhill** [comment]
The Performance pane in dev tools shows a ~1-second stall caused by:

    Network request
    URL  img/fontawesome/fontawesome-defs.svg#eye-open
    Duration  938.44 ms (938.22 ms network transfer + 0.22 ms resource loading)
    Request Method  GET
    Priority  Low
    Mime Type  image/svg+xml
    Encoded Data  32.0 kB

The resource above is part of uBO's package so it should not take ~1 second to load -- this is anomalous.

![a](https://user-images.githubusercontent.com/585534/89424337-a74ef780-d705-11ea-96f5-c5d34520686d.png)

**Comment by gorhill** [comment]
I think I will publish an emergency release if the issue is confirmed fixed.

**Comment by yourduskquibbles** [comment]
Filter Lists tab loads much faster & smoother now for me on both chrome 84 stable and chrome 85 beta with `uBO 1.28.5b16`

![ubo_test02](https://user-images.githubusercontent.com/22258847/89439067-a7f08980-d717-11ea-8e32-d53e54e24538.png)

**Comment by gorhill** [comment]
I removed usage of `<svg>`/`<use>` from everywhere but one place -- the uBO icon in the logger's toolbar. So I consider this issue resolved. Since this makes page load more smooth even on Chromium 85, I no longer consider this a "workaorund", but rather the right way to render SVG-based icons.
