### ISSUE TITLE
Feature?

### ISSUE THREAD

**Issue by LucianAndries** [uBlockOrigin/uBlock-issues#1197]
Hello.

Has this been addressed before?

For example: I block an element on website, `www.sammobile.com##.a-107.g-single > .adsbygoogle`.
But after, I modify it to be blocked on every `.com` webpage, `*.com##.a-107.g-single > .adsbygoogle`...

Can I do that? Is it possible?
I want to be able to add a custom filter, that can block a certain page element on every website, if they have it. I.e. *.com,  *.net,  etc... Am I making any sense?
Why do it this way? So you don't have to do it for every website.

So this has to be codded into uBlock first, in order to accept this kind of filter.
Another example:
`! 7/6/2020 *.com
||offerimage.com^$document,domain=*.com,important`

Would you please do this? This also saves us space, as I literally filled up my filter list... Yeah, so you didn't make it unlimited. The whitelist and rules as well, please remove their limits.

Thank you for your time.

**Comment by uBlock-user** [comment]
Support issues and questions are handled at https://www.reddit.com/r/uBlockOrigin/

**Comment by LucianAndries** [comment]
Then what's this for?? Remove these pages, or redirect them to reddit, so there won't be any confusion anymore.
