### ISSUE TITLE
ubo do not auto-actualize it

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#12]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
ubo do not auto-actualize it
example. ubo 1.15 to ubo 1.16.0

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
`chrome://extensions/?id=cjpalhdlnbpafiamejdnhcphjbkeiagm`

### Steps to Reproduce

1. when the new ubo version comes out in google web store
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

2. load this backup and try it to actualize ubo
https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

3. example. click this button
![2018-04-23-rozszerzenia](https://user-images.githubusercontent.com/5884000/39117526-6a67f048-46e7-11e8-9a68-9ef4b29de6d0.png)

### Expected behavior:

[What you expected to happen]
actualize it

### Actual behavior:

[What actually happened]
do not actualize it

### Your environment

* uBlock Origin version: 1.16.0, 1.15, 1.14
* Browser Name and version: chrome 66.0.3359.117
* Operating System and version: w10

**Comment by gorhill** [comment]
uBO is always rolled out progressively. Do not open issue about uBO not updating from the Chrome store.
