### ISSUE TITLE
Page with iframe et resizer never finish to load when ubo, even if whitelist and descactived for site

### ISSUE THREAD

**Issue by renogarfield** [uBlockOrigin/uBlock-issues#1200]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi,
We (at work) have a bugzilla wich work as a plugin on a forge site (fusionforge) with a js  resizer. When ubloc is actived (as a plugin), even if the site is on whitelist, even if the site is desactived by button the iframe is **never** resised and the page go on forever.

When ubloc is not on browser the page is **alway** read and finish

i try different setting, active off, no whitelist, no cosmetic, etc but it never work. the integrated log display nothing strange.

### A specific URL where the issue occurs

no url accessible on web

### Steps to Reproduce

1. juste go on the url "http://venezia-bas.appli.dgfip/plugins/bugzilla/?group_id=6"

### Expected behavior:

page loading (and resized)

### Actual behavior:

page never finish to load

### Your environment

tested on 3 environnements, 2 PC with an archlinux up to date and one with an ubuntu

* uBlock Origin version:1.28.4
* Browser Name and version: 79.0
* Operating System and version: archlinux (tested in ubuntu too)

**Comment by gorhill** [comment]
If I can't reproduce, I can't investigate. I will have to mark this issue as invalid if you do not provide repro steps.

**Comment by renogarfield** [comment]
i understand, i will try to add a version of the site accessible over internet (will make a few days). Could you let the issue open until i do (would be easier than reopen) ?
- i tested with no list at all (all disactived)
- i tested with withlist
- i tested with button desactived
- i will now test with another content blocker

the logger said only this (txt copie, hope it's leasible)
12:33:34​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/iframe-resizer/iframeResizer.contentWindow.min.js
12:33:34​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/plugins/bugzilla/bugzilla/data/assets/f119866a68256a70f172895043aa1e11.js?1596725969
12:33:34​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/plugins/bugzilla/bugzilla/data/assets/a7c2f3a028f17a9aa60f56dc9d6e732d.js?1596725969
12:33:33​​​venezia-bas.appli.dgfip​1​frame​http://venezia-bas.appli.dgfip/plugins/bugzilla/bugzilla/buglist.cgi?product=venezia&bug_status=__open__&list_id=217
12:33:33​​​venezia-bas.appli.dgfip​1​frame​http://venezia-bas.appli.dgfip/plugins/bugzilla/bugzilla/buglist.cgi?product=venezia&bug_status=__open__
12:33:33​​​venezia-bas.appli.dgfip​1​image​http://venezia-bas.appli.dgfip/images/icon.png
12:33:33​​​venezia-bas.appli.dgfip​1​frame​http://venezia-bas.appli.dgfip/plugins/bugzilla/blank.html
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/iframe-resizer/iframeResizer.min.js?1590414015
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/jquery-ui/js/jquery-ui-1.11.2.js?1590414016
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/js/jquery-common.js?1590414015
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/coolfieldset/js/jquery.coolfieldset.js?1590414016
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/jquery-storage/jquery.Storage.js?1590414015
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/plugins/message/js/message.js?1590414015
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/scripts/jquery/jquery-1.10.2.js?1590414015
12:33:33​​​venezia-bas.appli.dgfip​1​script​http://venezia-bas.appli.dgfip/js/common.js
12:33:33​whitelisted​++​venezia-bas.appli.dgfip​1​doc​http://venezia-bas.appli.dgfip/plugins/bugzilla/?group_id=6
12:33:33​http://venezia-bas.appli.dgfip/plugins/bugzilla/?group_id=6

**Comment by gorhill** [comment]
Could you see if toggling the advanced setting [`cnameUncloak`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnameuncloak) to `false` helps?

**Comment by renogarfield** [comment]
halas,
set cnameuncloak to false does not change anything

i tested adblock ultimate, ghostery, ublock plus they have the same exact behavior, if plugin actived the page don't load...

**Comment by renogarfield** [comment]
nota: i think, not sure, that older firefox/ublock has not the issue

**Comment by gorhill** [comment]
> i tested adblock ultimate, ghostery, ublock plus they have the same exact behavior, if plugin actived the page don't load...

So this confirms the issue is beyond uBO itself. I was going to ask if you disabled e10s but since you checked _"using a new, unmodified browser profile"_, this can't be it.

So at this point I think it's best you report the issue to <https://bugzilla.mozilla.org/>, but it's not going to be different than here, they will also need to be able to reproduce.

**Comment by renogarfield** [comment]
since it only append with blocker actived i'm not sure it will be easy..

thank you for your reactvity and that plugin, most usefull ever

**Comment by renogarfield** [comment]
hi,
don't know if it make sens since the issue is closed but 
- i opened a bug in firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1659989
- it's easier to reproduce, a simple bugzilla with no mod generate the bug - ex; https://www.renogarfield.net/bugzilla/buglist.cgi?bug_status=__open__&no_redirect=1&order=Importance&query_format=specific, no frame or iframe is neaded, it's just a bugzilla with a centos-7
- the bug append with firefox 76 and after but not before
- the probleme comme with other plugin than ubloc, for exemple "simple tab group"
