### ISSUE TITLE
Add Support for AdGuard Special Case Pre-Processor Directives

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#1205]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

From AdGuard's KB Allowed [Pre-Processor Directive List ](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#what-constants-we-declare) they use additional AdGuard product specific directives in special cases that [uBO doesn't recognize.](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition)

I'd like to use the `adguard_app_ios` directive to conditionally load a sublist in [Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances) _**only**_ in the iOS AdGuard environment (Due to iOS not allowing CSS modifications and needing to remove some companion filters that make the page incorrect render when the CSS rules don't get loaded) but uBO doesn't recognize the `adguard_app_ios` directive and then loads the sublist wrapped in directive not recognized that I only want to conditionally load when it is iOS AdGuard envionment.

The same behavior is observed if when only loading the sublist directly - The filters wrapped in the unrecognized directive gets loaded because uBO just ignores the directive rather than recognize the directive as false and treat everything until the closing `!#endif` as not to be loaded.

1. If uBO encounters a directive it doesn't understand does it make more sense to throw out all content between the invalid directive and the closing `!#endif`?

2. Is it possible to add additional directives that uBO will recognize to mirror AdGuard used directives? I can elaborate more on what issue this specific sublist fixes (screenshots, video) if you'd like.

`adguard_app_mac` -- AG for Mac
`adguard_app_android` -- AG for Android
`adguard_app_ios` -- AG for iOS
`adguard_ext_safari` -- AG browser extension for Safari
`adguard_ext_android_cb` -- AG content blocker for Samsung/Yandex

Related:
https://github.com/yourduskquibbles/webannoyances/issues/241

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Add custom list `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt`
2. Observe Logger is loading sublist `filters/adguard_mobile_exclusion_filters.txt` wrapped in invalid directive `adguard_app_ios`
3. Unsubscribe from custom list `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt`
4. Add custom list `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/adguard_mobile_exclusion_filters.txt`
5. Observe logger loads the custom filters wrapped in invalid directive `adguard_app_ios`

### Expected behavior:

uBO ignores everything inside of invalid `!#if` directive until closing `!#endif`

### Actual behavior:

uBO ignores only the 1 line of the invalid directive and proceeds to load content within the invalid `!#if` statement
### Your environment

* uBlock Origin version: 1.29.1b0
* Browser Name and version: Firefox Nightly
* Operating System and version:

**Comment by gorhill** [comment]
> If uBO encounters a directive it doesn't understand does it make more sense to throw out all content between the invalid directive and the closing `!#endif`?

No, this could cripple uBO's parsing of otherwise good filters if a list makes use of an unknown directive. Throwing away filters should be done only when the intent is clear and _explicit_. Imagine ABP coming up with pre-parser support and start to ask filter list maintainers to make use of them for whatever reasons, this could cause uBO to unduly throw away perfectly compatible filters.

**Comment by bogachenko** [comment]
@gorhill The issue is not fully resolved, the combination of conditions does not work.

You can add to my filters and check it https://raw.githubusercontent.com/bogachenko/filterlist/personal/bogachenkoPF.txt

```js
!#if (adguard_ext_safari || adguard_app_ios || adguard_ext_android_cb)
||google.com^
!#endif
```
`||` or `&&` for separate
```js
!#if (adguard_app_android && adguard_app_ios)
||google.com^
!#endif
