### ISSUE TITLE
Firefox sync prefs

### ISSUE THREAD

**Issue by isuki56** [uBlockOrigin/uBlock-issues#1206]
Hi, I'm a newbie, 

about:config
services.sync.prefs.sync

services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane
services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane
services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane
services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane

Update whitelist to trusted.

**Comment by gorhill** [comment]
I don't understand what you want. Do not delete the template when filing issue, read and respect what is asked in the template carefully.

**Comment by uBlock-user** [comment]
> services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane 

That setting is created when using uBO legacy version, I suppose. The WebExtension doesn't have access to `about:config` page.

**Comment by yourduskquibbles** [comment]
FYI the request I think is probably to update the entry name `services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane`  in `about:config` to `services.sync.prefs.sync.extensions.ublock0.cloudStorage.trustedSitesPane` to be consistent with https://github.com/uBlockOrigin/uBlock-issues/issues/1114
