### ISSUE TITLE
Filter different between Chrome and Firefox

### ISSUE THREAD

**Issue by marcotini** [uBlockOrigin/uBlock-issues#121]
Why this filter works in Firefox and not in Chrome? What I am doing wrong?

`||*blockadblock*.*/*$inline-script`
`||*.*/*blockadblock*/*$inline-script`
`||*.*/*blockadblock*/*`
`||*blockadblock*.*/*`
`||*blockadblock.com##script:inject(bab-defuser.js)`

**Comment by uBlock-user** [comment]
User support is on reddit.
