### ISSUE TITLE
Asset viewer shows mixed coloring in the middle of domains in a rule

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1210]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Asset viewer uses both orange and black coloring in the middle of listed domain names in a rule.

### A specific URL where the issue occurs

?

### Steps to Reproduce

1. Open EasyList on Filter lists
2. Go to the rule of `##.ad`, currently it's L57646

![highlight](https://user-images.githubusercontent.com/58900598/90385857-ab442780-e0be-11ea-960b-784ba8552925.png)

### Expected behavior:

Domain part should be orange.

### Actual behavior:

Mixed color

### Your environment

* uBlock Origin version: 1.29.0 on Firefox, 1.28.4 on Brave
* Browser Name and version: 79.0/1.12.112
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Use `wral.com,` as the search term, so to narrow down the result to one.

**Comment by uBlock-user** [comment]
> Go to the rule of ##.ad, currently it's L57646

Use `wral.com,` as the search term, so to narrow down the result to one.

**Comment by gorhill** [comment]
It's probably a CodeMirror's normal behavior, I suspect there is a limit to the syntax coloring after which it bails out.

**Comment by gorhill** [comment]
Found the [reference](https://codemirror.net/doc/manual.html#config):

> `maxHighlightLength`: number
>    When highlighting long lines, in order to stay responsive, the editor will give up and simply style the rest of the line as plain text when it reaches a certain position. The default is 10 000. You can set this to Infinity to turn off this behavior.

**Comment by uBlock-user** [comment]
Setting it to `50000` should be fine.

**Comment by gorhill** [comment]
I am going to respect CodeMirror's default value; assuming there is a good reason to limit syntax coloring to whatever number of characters CodeMirror decides can be safely processed.
