### ISSUE TITLE
Add a way to select elements by the amount of classes they have

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1211]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (v1.29.0)
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A steadily higher amount of websites are using randomly generated class names for elements, and a slight majority of such websites also keeps changing those generated class names every month-ish. However, I think I've discovered one thing that can help select specific such elements at least a bit more easily:

On a few of the websites in question, with Twitter and Pixiv as the biggest examples that I personally know of, the *amount* of classes the elements have are different, and they seem to be fairly consistent.

My wish is that in the setting of the screenshot below, `<div class="sc-1nr368f-4 ez9z4y-0 cIk0oy">` would've been selectable with `##div:classes(3)`, or whatever else you'd want to name it (e.g. `:class-number`). Likewise it would be selectable with `##div:classes(2) > div:classes(3)`, and perhaps even `##div:classes(3):has(:scope > section:classes(2))`.

![image](https://user-images.githubusercontent.com/22780683/90432549-fc5a1880-e0ca-11ea-88c9-dc0087e9df74.png)

Currently, it seems that `##div[class*=" "]` can cover everything with 2 or more classes, but I can't find any ways to make it more narrowed-down than that.

An alternative could be to add wildcard support for id and class (e.g. `###*.*.*`), similar to what I am currently only able to do with singular elements (e.g. `##*`)

### A specific URL where the issue occurs

`https://www.pixiv.net/en/tags/princess_dress/illustrations` (If you're *not* logged in.)
`https://www.pixiv.net/en/tags/princess_dress/illustrations?mode=safe` (If you're logged in.)

### Steps to Reproduce

1. Visit whichever website, although preferably one with many different class-containing elements.
2. Open the element picker.
3. Attempt to add `##.*`, `##div:classes(1)` and/or `##div:class-number(1)`, and see that none of them are accepted.
4. Attempt to add `##div[class*=" "][class*=" "]`, and see that the amount of successive `[class*=" "]` has no narrowing-down effect on what is being selected.

### Expected behavior:

It becomes possible to select and hide elements based on the amount of classes they have.

### Actual behavior:

Currently this can only be done for elements with 0 classes (`##div:not([class])`) and 1 class (`##div[class]:not([class*=" "]`). There are currently no known way to specifically select elements by the exact amount of classes they have, if that number is 2 or higher.

### Your environment

* uBlock Origin version: 1.29.0
* Browser Name and version: Vivaldi 3.2.1967.41 x64
* Operating System and version: Windows 10 May 2020 Update

**Comment by gargul2** [comment]
> DandelionSprout: There are currently no known way to specifically select elements by the exact amount of classes they have, if that number is 2 or higher.

It is possible: `www.pixiv.net##:xpath(//div[string-length(@class) - string-length(translate(@class," ","")) = 2])`

But:
-  `:xpath` doesn't work with `:style`, while `:classes(3)` can get support if https://github.com/uBlockOrigin/uBlock-issues/issues/382 gets fixed
- nor is `:xpath` elegant / short unlike `:classes(3)`
- also not sure about `:xpath` performance compared to what performance of `:classes(3)` would be (`:classes(3)` might be faster if not internally based and converted from `:xpath`)

So the OP's request for adding support for `:classes(3)` still seems reasonable.

**Comment by krystian3w** [comment]
Also CSS lie in this example

```html
<css class=" I-a-fake-2-classes"> one class div </div>
```

**Comment by gargul2** [comment]
**1**
Interesting, theoretically, class names can't itself start / contain / end with a space char, coz a space char is reserved as a multiple class names separator ([LINK](https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors)), but in practice, looking at example provided above it seems to be somehow possible...

**2**
...moreover, using his example I noticed uBO Element Picker odd behaviour between selected / highlighted matched elements and elements number displayed in uBO Element Picker Counter, perhaps a bug or a feature? As on the picture: 
- when using `##div[class]` it highlights all `6` divs but uBO Element Picker counter shows `9` number of matched elements
- when using `##div[class]:not([class*=" "])` it highlights `1` div but Ubo Element Picker shows `4` number of matched elements
![Nagrywaj_2020_08_31_14_44_10_543](https://user-images.githubusercontent.com/63287518/91722186-34b52880-eb9a-11ea-9dea-35664d67592b.gif)

**Comment by krystian3w** [comment]
Unable reproduce: [tests.zip](https://github.com/uBlockOrigin/uBlock-issues/files/5150657/tests.zip)

```html
<!doctype html>
<div class=" I-am-a-fake-2-classes"> one class div </div>
<div class="I-am-a-fake-2-classes "> one class div </div>
<div class=" I-am-a-fake-3-classes "> one class div </div>
<div class="one"> one class div </div>
<div class="two classes"> two classes div </div>
<div class="three classes"> three classes div </div>
```

**Comment by gorhill** [comment]
I might not have been clear here: I need many actual credible not-contrived use cases of what a `class-count()` operator would solve. This to be useful to many sites and where no other reasonable solutions exist -- the last thing I want is to add technical debt to uBO by piling on operators in the code.

**Comment by uBlock-user** [comment]
> when using ##div[class] it highlights all 6 divs but uBO Element Picker counter shows 9 number of matched elements

Those divs's children are also added to the count.

**Comment by krystian3w** [comment]
> Those divs's children are also added to the count.

The demo has no children, only siblings.

---

> https://github.com/uBlockOrigin/uBlock-issues/issues/1211#issuecomment-683799217

As long as somebody does not try to make uBO a substitute for Stylus or `.user.js`, I do not see any real thoughts.

**Comment by gargul2** [comment]
> krystian3w: Unable reproduce

I checked again, and I can reproduce on Firefox, but can't on Opera, have you tried in Firefox?

**Comment by krystian3w** [comment]
Yeah, with `tiny.exe` / `python3` + uBO 1.29.2 / uBO 1.29.3b7 / Nano AdBlocker 1.0.0.151 (uBO based 1.27.10).

**Comment by gargul2** [comment]
Ok, I apologize, my fault, can't reproduce anymore, it seems I had some addons enabled which were interferring:
- [Snap Links](https://addons.mozilla.org/pl/firefox/addon/snaplinksplus/)
 - a Greasemonkey script

 which injected 3 additional `div[class]` elements to the webapge:
![11111](https://user-images.githubusercontent.com/63287518/91739223-e57af200-ebb1-11ea-9669-b11c36ceede4.gif)

**Comment by keczuppp** [comment]
What the OP requested is already possible with uBO:
`##:xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 3])`
where the expected number of classes is the number of clasess (`3`) + 1 (the example filter matches 4 classes)

The only potential issues are:
- it's not eye candy
- perhaps  uBO native implementation could be faster (performance)

Also possible to make an internal uBO alias:
- eye-candy `##div:classes(4)` would be converted internally to the example dirty xpath filter
- can't cover all possible cases with an alias but can cover at least few most simple ones, better than nothing

**Comment by DandelionSprout** [comment]
I can confirm after some quick testing that this actually works, which is amazing.

**Comment by DandelionSprout** [comment]
But there is one problem: I can't seem to figure out how to combine that with `>` and such.

In order for this to have any practical value, I'd have needed to do things like, for example: `##:xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 6]) > :xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 1]) + :xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 2])`

**Comment by krystian3w** [comment]
Still no detect this:

```html
<!doctype html>

<div class=" three classes "> 3 spaces = 3 classes?</div>

```


`##:xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 3]):not([class^=" "]):not([class$=" "])`

**Comment by gwarser** [comment]
##:xpath(//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 6]//div[string-length(@class) - string-length(translate(@class, ' ', '')) = 1]/following-sibling::div[string-length(@class) - string-length(translate(@class, ' ', '')) = 2])

https://devhints.io/xpath

**Comment by gorhill** [comment]
Prefix your `:xpath()` with `*` for those not used as first expression: `*:xpath(...)`.

**Comment by keczuppp** [comment]
> krystian3w : https://github.com/uBlockOrigin/uBlock-issues/issues/1211#issuecomment-736759831

just use `normalize-space()` to remove leading and trailing spaces from a class: 
`##:xpath(//div[string-length(normalize-space(@class)) - string-length(translate(@class, ' ', '')) = 3])`

> 3 spaces = 5 classes?

- no, 3 + 1 = 4 and not 5... just like I've already mentioned in https://github.com/uBlockOrigin/uBlock-issues/issues/1211#issuecomment-736496520 : 
 "(`3`) + 1 (the example filter matches 4 classes)"

**Comment by DandelionSprout** [comment]
Testing real quick on my usual syntax test site (`nrk.no`) with `nrk.no##div:matches-attr(class="/^[a-z-]{1,} [a-z-]{1,} [a-z-]{1,} [a-z-]{1,} [a-z-]{1,} [a-z-]{1,} [a-z-]{1,} /")` it indeed seems to work well enough, although with a need for pretty long entries.

**Comment by gwarser** [comment]
:matches-attr(class="/^([a-z-]{1,} ){7,}/")

**Comment by gorhill** [comment]
This seems like an acceptable solution using existing syntax instead of a new dedicated operator:

    ##div[class]:matches-attr(class="/([\w-]+ ){7,}/")

So for now I prefer to decline.
