### ISSUE TITLE
Add a Brave pre-processor directive

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1213]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Brave is Chromium-based, but it's different in many aspects that affect contents-blocking and also some websites treat Brave differently. See [this](https://github.com/brave/adblock-lists/pull/451), [this](https://github.com/AdguardTeam/AdguardFilters/pull/60902), and [this](https://github.com/brave/brave-browser/issues/9625). The last one was fixed in Nightly and it will come to Stable soon, but Brave still has its own protection feature which can lead to a different behavior from other Chromium browser. Those who install uBO should turn its ad-blocker off, but no reason to turn off e.g. fingerprint spoofing, tracking parameter removal etc. If uBO supports `env_brave` we can use this directive to address all these cases specifically. Of course `env_chromium` should implicitly include `env_brave` nevertheless.

Related issue: https://github.com/uBlockOrigin/uBlock-issues/issues/1205

### A specific URL where the issue occurs

See the referenced issues/PRs above.

### Steps to Reproduce

?

### Expected behavior:

Filters like this is possible:
```
!#if env_brave
archive.is,archive.today,archive.vn,archive.fo##+js(acis, navigator.brave)
!#endif
!#if !env_brave
/modal-dist/index.js$script,domain=diamond.jp|iza.ne.jp|lifehacker.jp|newsweekjapan.jp
!#endif
```
(The second rule is only for demonstration, actually no harm to block regardless of browser)

### Actual behavior:

Not possible and `env_chromium` is too broad.

### Your environment

* uBlock Origin version: 1.29.0
* Browser Name and version: Firefox 79.0/Brave 1.12.112
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
I am not sure I understand the issue here. If Brave uses its own filter lists, why should uBO supports a directive for Brave?

**Comment by Yuki2718** [comment]
> why should uBO supports a directive for Brave?

For those who use uBO on Brave. There are many features which only uBO provides such as dynamic filtering, logger, advanced picker (Brave's is currently very primitive) etc., and if you use uBO on Brave it will not be wise to enable Brave's built-in filtering. Those who install and use uBO on Brave will be minority, but sure there are. Given uBO now supports a pre-processor directive for Edge which is far less different from Chrome, it'll makes sense to support Brave too. It's another story whether these Brave-specific rules should be added to uBO's lists, although I personally support it for those uBO user on Brave.

**Comment by gorhill** [comment]
Recent versions of uBO do not distinguish Chrome, Edge, Opera, etc.; all Chromium-based browsers resolve to `env_chromium`.

The way I see it you are asking uBO to deal with cases of "other blockers installed" (it does not matter whether built-in or not), but as often mentioned, uBO should not be used with other similar-purpose blockers, so I don't see adding a conditional token to make uBO work better with another blocker is a good idea.

**Comment by Yuki2718** [comment]
@gorhill I guess my explanation was bad, what I meant was:
1. Brave has its own blocker with a list specifically address Brave-specific issues, but those who install uBO <strong>must turn off this</strong>.
2. However, this causes those uBO user who turned off Brave's blocker encounter Brave specific issues as mentioned above.
I hope this makes sense to you.

**Comment by uBlock-user** [comment]
> archive.is,btdig.com,archive.today,archive.vn,archive.fo,archive.md,archive.li,archive.ph,archiveiya74codqgiixo33q62qlrqtkgmcitqx5u2oeqnmn5bpcbiyd.onion block access if UA is Brave, it has nothing to do with filtering tho can be addressed by filters.

@ryanbr recently mentioned in slack that Brave might remove the Brave UA to stop such activities.

**Comment by Yuki2718** [comment]
> 
> @ryanbr recently mentioned in slack that Brave might remove the Brave UA to stop such activities.

Thanks, sounds good idea. But IDK if those nasty sites will just give up or take full effort for Brave harassment.

**Comment by gorhill** [comment]
> Brave might remove the Brave UA

Is there an opened issue for this?

So far what I see is [one case](https://github.com/brave/adblock-lists/pull/451) of filter; the other links do not seem related to the issue here, one is a filter issue in an AdGuard list, and the other is that Brave was not supporting `generichide`, which has been fixed since then.

**Comment by Yuki2718** [comment]
The AG cases were actually if the sites detect UA is NOT Brave they show anti-adb. Most of them could be addressed by simple network filtering but it's always possible at some point scriptlets become necessary, then it will make sense to inject them only on non-Brave browser. The last one was not sth about ghide, it's a settings issue on Brave that even if you globally turned Brave's blocker off, something triggered anti-adb unless you individually turn off their shield on each site. Anyway this was fixed.

**Comment by gorhill** [comment]
Thing is I was happy to remove a good chunk of code re. browser detection in [this commit](https://github.com/gorhill/uBlock/commit/39190ff4699da01b8feb8526fd29287a55a14a0b), so if I am going to again add code to detect specific browser rather than stick to broader browser engine, I really want to be sure it's justified in the long term.

**Comment by uBlock-user** [comment]
> Is there an opened issue for this?

None that I know, ryanbr just said that in passing, in slack chat.

**Comment by Yuki2718** [comment]
All right, I don't have a convincing reason/explanation to re-implement once-removed codes when I can still use env_chromium and the most prominent issue may be solved in near future. I wrongly assumed it can be done without affecting current code base too much. Closing, thank you for clarifying the situation.
