### ISSUE TITLE
Picker gets deformed when a cosmetic filter is added

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#1215]
### Description

Picker's buttons are lost and gets deformed when a specific cosmetic filter is added as discussed in https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/234

### A specific URL where the issue occurs

`www.google.com`

### Steps to Reproduce

 - Add `google.com##div:nth-of-type(2) > div`

- Navigate to `https://google.com`

- Invoke picker by right click and select _Block Element_

### Expected behavior:

Picker doesn't lose its buttons and get deformed.

### Actual behavior:

Picker loses its buttons and gets deformed.

![Capture](https://user-images.githubusercontent.com/21290713/90679036-35d28580-e27d-11ea-8131-d940ab142bee.PNG)

### Your environment

* uBlock Origin version: 1.29.1b8
* Browser Name and version: Firefox 81
* Operating System and version: Win 10

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1226
