### ISSUE TITLE
fenix import filed is not scrollable

### ISSUE THREAD

**Issue by 532910** [uBlockOrigin/uBlock-issues#1216]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open setgings
2. Scroll down
3. Choose Import
4. Put there something and try to scroll

### Expected behavior:

[What you expected to happen]

### Actual behavior:

![image](https://user-images.githubusercontent.com/14617699/90787799-c5c01000-e30d-11ea-933c-4bca9055f2be.png)

[What actually happened]

### Your environment

* uBlock Origin version: 1.29.0
* Browser Name and version: fenix stable and nightly
* Operating System and version: android 9

**Comment by 532910** [comment]
The same for the settings page:
![image](https://user-images.githubusercontent.com/14617699/90788495-8b0aa780-e30e-11ea-8e51-1610674599b8.png)

**Comment by 532910** [comment]
![ScreenRecord-2020-08-20-17-57-40](https://user-images.githubusercontent.com/14617699/90788806-d58c2400-e30e-11ea-8a1e-55853256e093.gif)

**Comment by gorhill** [comment]
I consider this a Firefox issue, if you set the browser toolbar to be displayed at the top, the bottom of uBO's panes shows fine.

**Comment by 532910** [comment]
Indeed: https://github.com/mozilla-mobile/fenix/issues/11858
