### ISSUE TITLE
Chrome extension taking disk space with old versions

### ISSUE THREAD

**Issue by Alex131089** [uBlockOrigin/uBlock-issues#1221]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

With long-time running browser, this extension may use 100+MB disk space with multiple versions (or copies of them), for each started browser profile.

This may be a browser issue, but it could be caused by a packaging issue (don't know) and it will still reference this behavior for other users.

This is only really a problem when you have to work on a space restricted environment, but I'm not sure it should happen though.

Also, if I manually remove the "old" copies, the browser consider the extension broken, and when I reactivate, it ends up in the same situation, with many copies ..

### A specific URL where the issue occurs

(not happening on a web page)

### Steps to Reproduce

1. Install Chrome Portable 64bit
2. Create multiple profiles 
3. Install µBlock Origin on them
4. Use the profiles and keep them opened for weeks

### Expected behavior:

Only the latest version of the extension is present on the disk : 
![image](https://user-images.githubusercontent.com/1735067/91161135-9ffa8880-e6ca-11ea-8db7-b6154304e916.png)

### Actual behavior:

Multiple copies of the extension are present, each using ~10MB of disk (for a total of ~200MB / profile today, so ~600MB with 3 profiles)

![image](https://user-images.githubusercontent.com/1735067/91152881-cebf3180-e6bf-11ea-9bfb-db02aba1b05a.png)

![image](https://user-images.githubusercontent.com/1735067/91152996-ee565a00-e6bf-11ea-9f62-82393178b3eb.png)

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: [Chrome 84.0.4147.105 (Build officiel) (64 bits)](https://portableapps.com/apps/internet/google-chrome-portable-64)
* Operating System and version: Win 10 2004

Thank you for helping keeping the web a better place :)

**Comment by gorhill** [comment]
This is a browser issue, report to browser developers. uBO does not have access to file system and does not manage its own installation.

**Comment by gwarser** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=126394

**Comment by u1735067** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=126394

Isn't this issue about versions of Chrome itself?

Anyway, the issue I created after your reply is https://bugs.chromium.org/p/chromium/issues/detail?id=1121631 (not much interest in it it seems).

Checking on a regular (not portable) installation, this also happen in other extensions (like Google Keep) but limited (3-4 versions max), not 50+ like with this extension (maybe linked to how this extension work or the release frequency?).

**Comment by auwsom** [comment]
@uBlock-user yes, thanks I was just updating the problem with some information, as it seems uBO has larger updates than other extensions and people may land here. The bug report above was helpful. So was mentioning Portable apps. Unfortunately, on Ubuntu the portable options like AppImages dont automatically update, and have to be completely replaced to update. I'll have to check if the Snap packages also have this problem (do you know?), but suspect they do as they are more similar to regular packages than portable ones.

**Comment by krystian3w** [comment]
If he have Windows or Wine on GNU/Linux.
