### ISSUE TITLE
How to block ADS in MAIL.YANDEX( web mail-client)?

### ISSUE THREAD

**Issue by papaper21** [uBlockOrigin/uBlock-issues#1223]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [+ ] I am running the latest version of uBlock Origin
- [ +] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs
https://mail.ynadex.ru

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Switched on uBlock on page
2. in configuration, i turned all RU and other (recommendation) filters preset. Didnt help.
3. I tried to use pippete tool (enter item selection mode), used on block, it hides until  page refresh (also, class names every time changes on randomly chars when uBlock is ON.
4. tried to use custom filters with class names before using uBlock on web mail page .

### Expected behavior:

Block ADS on mail.yandex.ru (see screenshot below)

### Screenshot(s)
[img]http://ipic.su/img/img7/fs/mailyandexru.1598449232.png [/img]

### Actual behavior:

uBlock dont block ADS on russian web mail-client.
I tried last version of uBlock, its not block ads on mail.yandex.ru (russian web mail-client). When i switched ON uBlock on page, class names change to randomly characters.
So how to make filter to cut all before and after 2 DIVs, there where class name keep static or how to delete watching script (i still dont know what the script is)?

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Mozilla Firefox/79
* Operating System and version: MS Windows 10

**Comment by gorhill** [comment]
> - [ ] Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
