### ISSUE TITLE
I can only see pics in Firefox standard mode but not in private mode 

### ISSUE THREAD

**Issue by lynxster** [uBlockOrigin/uBlock-issues#123]
### Prerequisites

- [ ✓ ] I verified that this is not a filter issue. 
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✓ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ X] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [✓ ] using a new, unmodified browser profile
- [ ✓] I am running the latest version of uBlock Origin
- [✓ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior: visit site as usual

[What you expected to happen] visit site 

### Actual behavior:went to site no pictures 

[What actually happened] went to yahoo.com saw zero pics while in private mode ,went back in standard mode pics where their,, just no pics in private mode only???

### Your environment android

* uBlock Origin version:1.16.12
* Browser Name and version:latest Firefox on playstore 6.0.02
* Operating System and version: marshmallow 6.01
I'm new here please forgive me if I did not do everything right ..thanks

**Comment by gorhill** [comment]
Why do you think uBO is causing this? There is nothing in your report making the case the issue is with your uBO.

**Comment by gorhill** [comment]
You provide no detailed steps to reproduce.

I went to `yahoo.com`, images were there in both normal or private mode.

You will need to make the case your issue is with uBO, the issue tracker here is only for actual issues with uBO.

**Comment by lynxster** [comment]
Sorry I tried the moab list and it blocks yimg.com. .74 different times
/types
I was able to find it in logger ...sorry..
 I did have a quick question is their an easy way to check for redundancies
or does ublock take care of it for you ???

**Comment by gorhill** [comment]
> does ublock take care of it for you ???

Wiki: [Dashboard: 3rd party filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters):

> uBlock Origin discards duplicate filters, so the number of filters used within a filter list depends on how many duplicate filters were detected within that filter list.

**Comment by lynxster** [comment]
Thank you....for your reply

.I have been hearing a lot about coin mining is their a list you approve of
???...I currently have all the one's from filterlists.com that say coin
,cryptocurrency, mining ,etc..do I need all 10 or 11 of them

Btw keep up the great work
TIA !!

**Comment by gwarser** [comment]
You already have "uBlock filters – Resource abuse​​​​​" selected by default.
