### ISSUE TITLE
Allow a blocked request

### ISSUE THREAD

**Issue by thany** [uBlockOrigin/uBlock-issues#1230]
Dude, don't close a feature request just like that. Not cool. #1228

Why can you not add a way to unblock a request? Or add a way to see by which rule in which list a request is blocked?

It's a perfectly viable request, to want to whitelist something that is normally blocked.

**Comment by gorhill** [comment]
Closing as invalid.

You were given links at which your question is answered. Support questions are to be handled at <https://www.reddit.com/r/uBlockOrigin/>.

Respect what is asked from you, and do **not** abuse the time of volunteers.

**Comment by uBlock-user** [comment]
> don't close a feature request just like that.

All duplicates are closed. I linked the issue and you still won't read it and understand what's being told. Can't help that.

**Comment by thany** [comment]
Are you deliberately misunderstanding me?
I did read the documentation. I understand this feature is no longer available.

I'm asking to reinstate it. There is NO other way to whitelist something, other than digging through the filterlists or disabling the entire addon.

**Comment by uBlock-user** [comment]
> I understand this feature is no longer available.

It's available as per the instructions posted in the release notes of v1.28(the fact that I have to spell this out is extremely discomforting). Your inability to understand that is now causing this back and forth argument which is nothing but a waste of time.
