### ISSUE TITLE
Prevent WebRTC setting leaks local IP address

### ISSUE THREAD

**Issue by ly1n** [uBlockOrigin/uBlock-issues#1231]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
The latest version in chrome, RTC function is invalid.(uBlock Origin v1.29.2)
But old version is available.

### A specific URL where the issue occurs

`https://www.expressvpn.com/webrtc-leak-test`

### Steps to Reproduce

1. Install latest version and open the privacy settings.(uBlock Origin v1.29.2)
![图片](https://user-images.githubusercontent.com/17906006/92063692-47db1a80-ed8b-11ea-8657-c4be0c4ffdea.png)

2. Access the website to check. (`https://www.expressvpn.com/webrtc-leak-test`)
Check WebRTC, is unavailable. And this IP is my real IP. 
![图片](https://user-images.githubusercontent.com/17906006/92063763-8375e480-ed8b-11ea-97a4-079bac321087.png)

3. Install the old version and open the privacy settings.(uBlock Origin development build v1.20.1b10)
I use the version of 1.20 is available. 
![图片](https://user-images.githubusercontent.com/17906006/92063830-a4d6d080-ed8b-11ea-9662-8fb849c42a99.png)
![图片](https://user-images.githubusercontent.com/17906006/92063920-d8195f80-ed8b-11ea-8c0b-171d85160a13.png)

### Expected behavior:

Disable WebRTC.

### Actual behavior:

The newest version is unavailable. (uBlock Origin v1.29.2)
The old version is available. (uBlock Origin development build v1.20.1b10)

### Your environment

* uBlock Origin version:  uBlock Origin v1.29.2
* Browser Name and version: Chrome (Version 85.0.4183.83 (Official Build) (64-bit))
* Operating System and version: Win10

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/64cfc5779d87612f87bd5f9bd5581704d5795b64

>It appears the implementation of the `disable_non_proxied_udp`
setting changed in Chromium, leading to WebRTC becoming
wholly unfunctional. Fall back to use `default_public_interface_only`
in Chromium-based browsers.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

Your public IP address is never meant to be hidden, only local IP address.

**Comment by ly1n** [comment]
Yes, I know. But this IP is my local IP.
I use a proxy to access the network. So, it can only get my proxy IP not my local real IP.
And old ublock version(v1.20) is valid.

**Comment by ly1n** [comment]
Is the implementation of "disable WebRTC " different between the two versions?
I just want to hidden my local real IP.

**Comment by uBlock-user** [comment]
> But this IP is my local IP.

Are you seeing your local IP address despite the setting been activated ?

**Comment by ly1n** [comment]
Yes. I used a proxy, but I can still see my local IP address.

**Comment by Yuki2718** [comment]
I don't see my local IP on the test; however, if I <strong>checked</strong> "Prevent WebRTC from..." option in uBO 1.29.2 running on Chrome 85.0.4183.83 (everything default except for uBO), the test shows my public IP and if <strong>not checked</strong> it says WebRTC not available.

**Comment by gorhill** [comment]
I could not reproduce with my VPN enabled, using Chromium 84.0.4147.105.

**Comment by gorhill** [comment]
> - [ ] uBlock Origin is the only extension

Other extensions (including extensions to control proxy) can prevent uBO from taking over control of the WebRTC setting. Please verify that is not the case.

**Comment by ly1n** [comment]
I used two extensions. uBlock and SwitchyOmega Proxy.
ex:
My local IP is 8.8.8.8 as A, proxy IP is 9.9.9.9 as B
A should be hidden, but acess WebRTC Leak Test Website, A was shown.
I don't know why.
And I use the v1.20 version of uBlock, acess WebRTC Leak Test Website, A will not show.

**Comment by uBlock-user** [comment]
Disable all extensions except uBO and test again.

**Comment by ly1n** [comment]
First pic is disable all extensions.
The shielded IP is my export IP.
![图片](https://user-images.githubusercontent.com/17906006/92211980-d087b280-ee80-11ea-986b-d2fc2e86c3e2.png)

This pic is disable all extensions except uBO and not open "prevent WebRTC".
![图片](https://user-images.githubusercontent.com/17906006/92212127-02991480-ee81-11ea-823d-ce844d02779f.png)

This pic is disable all extensions except uBO and open "prevent WebRTC".
![图片](https://user-images.githubusercontent.com/17906006/92212052-ebf2bd80-ee80-11ea-9360-600167750c94.png)

**Comment by ly1n** [comment]
Do you mean uBO is only used to protect local LAN IP. Like "192.168.1.1"?

**Comment by gorhill** [comment]
> Do you mean uBO is only used to protect local LAN IP. Like "192.168.1.1"?

No, as I mentioned above, the IP address from my ISP is not seen when I use a VPN.

**Comment by Yuki2718** [comment]
If I use a VPN I only see the VPN IP, not my real public IP - the same settings as above ("Prevent WebRTC from..." checked). Please test with a fresh Chrome profile.

**Comment by ly1n** [comment]
> 
> 
> If I use a VPN I only see the VPN IP, not my real public IP - the same settings as above ("Prevent WebRTC from..." checked). Please test with a fresh Chrome profile.

Yes. I tested. But my test results are different from yours. I don't know why.
