### ISSUE TITLE
Unable to update filter lists with 3rd party ressources blocked: 3pNetworkError

### ISSUE THREAD

**Issue by genodeftest** [uBlockOrigin/uBlock-issues#1232]
Note: This is an issue with a general filter being applied to internal extension functionality which is unexpected. As a result, it kinda is a filter issue and also does not happen with default settings / a fresh browser profile.

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

With specific configuration, I cannot update the filter lists.

### A specific URL where the issue occurs

moz-extension://f91ac995-8576-4aac-a570-be9656cdd1aa/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Get a fresh and clean Firefox profile
2. Install uBlock Origin from Firefox' addon center
3. Enable uBlock Origin globally
4. Go to uBlock Origin's settings, section filter lists
5. Update all filter lists. This works as expected.
6. Go to uBlock Origin's settings, section my rules
7. Add new rule: `* * 3p block` and save
8. Go to uBlock Origin's settings, section filter lists
9. Update all filter lists.

### Expected behavior:

uBlock Origin should be able to update its own filter lists.

### Actual behavior:

uBlock Origin fails to update every single filter list. In the logger, during updating ublock Origin's lists, I get "Network Error" for every single filter list. The relevant filter is `* * 3p block`.

### Workaround
If I disable this rule globally or only for the current extension or add another rule `moz-extension-scheme * 3p noop`, the issue is going away. Should this be a default (built-in) rule? This question also applies for other stuff like `3p-frame` and `3p-script`.

### Your environment

* uBlock Origin version: 1.92.2
* Browser Name and version: Firefox 80.0.1
* Operating System and version: Fedora Linux 32

**Comment by uBlock-user** [comment]
Add `moz-extension-scheme * 3p noop` to temp rules, click save -> commit.

**Comment by gorhill** [comment]
> Should this be a default (built-in) rule?

`moz-extension-scheme` is [part of trusted sites](https://github.com/gorhill/uBlock/blob/d25b9aa30f72c817b95455a41dfb80e2fecf58b2/src/js/background.js#L125) by default.

**Comment by gwarser** [comment]
When trying to reproduce I discovered, that on three Firefox channels, whitelist is not reset to default when using "Reset to default" in uBO settings.

This is on my whitelist:

	# about-scheme
	# chrome-extension-scheme
	# chrome-scheme
	# edge-scheme
	# moz-extension-scheme
	# opera-scheme
	# vivaldi-scheme
	# wyciwyg-scheme
	*youtube.com/*&disableadblock=1
	duckduckgo.com

**Comment by gorhill** [comment]
> whitelist is not reset to default when using "Reset to default" in uBO settings

I imported your directives and I am not able to reproduce, after resetting I get:

    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme

**Comment by gwarser** [comment]
Managed storage.

:facepalm: 

Something left from May when I tested something.

**Comment by genodeftest** [comment]
> > Should this be a default (built-in) rule?
> 
> `moz-extension-scheme` is [part of trusted sites](https://github.com/gorhill/uBlock/blob/d25b9aa30f72c817b95455a41dfb80e2fecf58b2/src/js/background.js#L125) by default.

This does not work at all. No matter whether `moz-extension-scheme` is there or not, the issue is still present. It seems like the list of trusted sites does not matter.

**Comment by gwarser** [comment]
> 3. Enable uBlock Origin globally

What you did in this step? Did you emptied whitelist? Enabled "I am an advanced user"? Then all is working as expected.

>No matter whether `moz-extension-scheme` is there or not, the issue is still present.

Is it `moz-extension-scheme` or `# moz-extension-scheme`?

**Comment by gorhill** [comment]
Did you use the logger to find out what is blocking the request?

**Comment by genodeftest** [comment]
> Did you use the logger to find out what is blocking the request?

I don't exactly remember.

**Comment by genodeftest** [comment]
> > 1. Enable uBlock Origin globally
> 
> What you did in this step? Did you emptied whitelist? Enabled "I am an advanced user"? Then all is working as expected.
> 
> > No matter whether `moz-extension-scheme` is there or not, the issue is still present.
> 
> Is it `moz-extension-scheme` or `# moz-extension-scheme`?

In addon preferences, dashboard.html#whitelist.html, it has been `# moz-extension-scheme`, which may be the cause of this issue. In this case, it is probably something I mis-configured years ago and forgot about.

Thanks to all of you for the support (and sorry for putting up an issue where I could have asked in the support forums)!
