### ISSUE TITLE
Unable to filter on Chrome new tab: chrome-search://local-ntp/local-ntp.html

### ISSUE THREAD

**Issue by jeremy-ade** [uBlockOrigin/uBlock-issues#1233]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On the Chrome new tab, I am unable to block elements.
I want to block the Google scare tactics they're injecting into my browser.

![image](https://user-images.githubusercontent.com/66807771/92350904-aacb0980-f11d-11ea-9103-284f7aedae16.png)

### A specific URL where the issue occurs

view-source:chrome-search://local-ntp/local-ntp.html

### Steps to Reproduce

1. Open new tab
2. Attempt to block div with ID of "Promo"
3. be unable to

### Expected behavior:

Expected behavior:
Ability to block Google scare tactics across Chrome updates.

### Actual behavior:

Actual behavior:
Unable to effect anything on this page

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
> unable to block elements.

Picker/Zapper doesn't run on `chrome://` URLs.

**Comment by jeremy-ade** [comment]
OK, so how do I block this then? 

I've tried using the rule:
! 18/08/2020 chrome-search://local-ntp/local-ntp.html
##div[id="promo"]

This does nothing.

**Comment by llacb47** [comment]
Extensions cannot run on chrome:// pages.

**Comment by jeremy-ade** [comment]
...great.

Thanks for giving an answer though, I appreciate it.

**Comment by jeremy-ade** [comment]
chrome://flags/#extensions-on-chrome-urls

**Comment by uBlock-user** [comment]
You can try `chrome-scheme * * block` in my rules and refresh the NTP page, you must be an [advanced user](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#i-am-an-advanced-user) for this to get applied.

**Comment by jeremy-ade** [comment]
Thanks, but no dice.

It's showing that things are blocked, but that banner is still there.

Apparently there was supposed to be a "dismiss" experimental option for it, but it seems to be been overridden by Google.

**Comment by friendlytherapist** [comment]
yes there was a //flag option to dismiss it but it got removed because google sucks.

**Comment by fruitofgeorge** [comment]
I'm in search of doing the same thing and this thread has left me confused. The above posted flag at "chrome://flags/#extensions-on-chrome-urls" should theoretically allow an extension to work on the new tab page. So why doesn't ublock origin actually filter the page?

**Comment by uBlock-user** [comment]
> So why doesn't ublock origin actually filter the page?

https://github.com/uBlockOrigin/uBlock-issues/issues/1233#issuecomment-688046596

**Comment by gwarser** [comment]
> So why doesn't ublock origin actually filter the page?

Because it will require additional permission to access them https://github.com/uBlockOrigin/uBlock-issues/issues/1234#issuecomment-688551374

**Comment by fruitofgeorge** [comment]
> > So why doesn't ublock origin actually filter the page?
> 
> Because it will require additional permission to access them [#1234 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/1234#issuecomment-688551374)

Ah, the classic limiting of functionality because of paranoia. Dumb.
