### ISSUE TITLE
make uBlock specifically request the permission to access chrome-urls

### ISSUE THREAD

**Issue by jeremy-ade** [uBlockOrigin/uBlock-issues#1234]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Experimental Chrome features reveals the flag: chrome://flags/#extensions-on-chrome-urls
The text for this says:
_Extensions on chrome:// URLs
Enables running extensions on chrome:// URLs, where extensions explicitly request this permission. – Mac, Windows, Linux, Chrome OS, Android_

I would like uBlock to request this permission so I can remove the Google scare tactics banner promo.

### Steps to Reproduce

To access, go to:
chrome://flags/#extensions-on-chrome-urls
and turn the flag on.

**Comment by gwarser** [comment]
Do you have any documentation for this?

**Comment by jeremy-ade** [comment]
Hi,

I'm not a developer, I can barely do copy/paste coding.
I was able to (I think) add the permission, but obviously that doesn't change anything.

So I guess my request is to add the permission as well as allow the picker to function in chrome:// tabs
There would have to be some kind of flag/permissions check, to check that the user has enabled the flag.

I don't know, like I said, I'm no coder.

**Comment by gorhill** [comment]
I prefer to decline this.

Adding a permission is just asking for trouble with both the Chrome store and users who become suspicious of uBO. Theoretically The permission could be optional but I rather not find out this still causes the above issues.

**Comment by jeremy-ade** [comment]
That makes sense. I'm leaning strongly toward getting rid of Chrome based on the banner thing anyway.
