### ISSUE TITLE
Regression the zapper ⚡in uBO 1.29.3b9-11

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#1237]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

* I new dev build don't work delete key for zapper function.

* Also I cannot delete Bing logo on one click.

### A specific URL where the issue occurs

any and some problematic e.g. `https://www.bing.com/`

#### Delete key:

1. pick up the zapper
2. hover on element
3. try remove by click delete

I suppose this is not glitch with first use delete key when help use <kbd>Shift</kbd> and **Left Mouse Button**.

*Or disabled for better compatiblity with Android?*

 <ul>
 
--- 

</ul>

#### Bing:

1. open `bing.com`

2. try delete svg logo with zapper ⚡:

   ![obraz](https://user-images.githubusercontent.com/35370833/92611930-9a4f9600-f2b9-11ea-9271-dd3074e12286.png)

3. also no help many  mouse clicks with <kbd>shift</kbd> - logo no gone from DOM.

### Expected behavior:

- works delete key;
- possible remove Bing logo like simple as in stable 1.29.2.

### Actual behavior:

- delete key no works at all;
- bing logo is zapper resistant;

### Your environment

* uBlock Origin version: 1.29.3b11
* Browser Name and version: Firefox 80.0.1 and Chrome 85.0.4183.102
* Operating System and version: Windows 10 20H1

**Comment by krystian3w** [comment]
IDK, but <kbd>delete</kbd> key still is dead?

on wiki nobody deleted sentence about <kbd>delete</kbd> key: https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-zapper

Also no added any inform about shutdown support PS/2 keyboards in modern browsers.

**Comment by gorhill** [comment]
I forgot to look at delete key issue.

**Comment by krystian3w** [comment]
No problem, It's a little pity that I can't really point out from which commit it broke even in Chromium.
