### ISSUE TITLE
A procedural cosmetic filter never gets injected until I choose the element via picker

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1238]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

My cosmetic filter never gets injected to pages and only way to force it is to launch the picker and choose the elements - no need to create rules, just choose the element and soon the rule will be applied. Sorry if it's duplicate of any known issue, couldn't find / don't know which it is if so - I think at least not due to iframe or shadow DOM.

### A specific URL where the issue occurs

E.g.
`https://allabout.co.jp/gm/gc/457399/`

### Steps to Reproduce

1. Add `allabout.co.jp##.csw-content-box:has(img[src*="/advertiser/"])` to My filters.
2. Visit the page.
3. See the promotional contents in the below SS are not hidden until you choose them on picker:

![allabout](https://user-images.githubusercontent.com/58900598/92726039-f8f33d80-f3a7-11ea-8529-9ca08d06f4e9.png)

### Expected behavior:

They should be hidden.

### Actual behavior:

Never hidden, whatever long you wait. This occurs on all the sites where this `contents-search-windows.com/advertiser/` is used.

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Firefox 80.0.1/Brave 1.13.82
* Operating System and version: Windows 10

**Comment by Yuki2718** [comment]
All right, thanks for clarification and the working solution. Sorry for creating an invalid issue by my lack of understanding.

**Comment by gargul6** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/341

**Comment by keczuppp** [comment]
Related issue: https://github.com/uBlockOrigin/uBlock-issues/issues/341
