### ISSUE TITLE
Add-on would not install on Firefox Linux beta: "appears to be corrupt"

### ISSUE THREAD

**Issue by crosser** [uBlockOrigin/uBlock-issues#124]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On Ubuntu bionic, firefox from the beta channel, uBlock stopped working a while ago. Attempting to install results in the message "The add-on downloaded from this site could not be installed because it appears to be corrupt". This happens when installing from addons.mozilla.org (uBlock 1.16.2), and from github (via downloaded uBlock0.firefox.signed.xpi, version from yesterday). Firefox version is 62.0b6.

![screenshot from 2018-07-10 09-23-35](https://user-images.githubusercontent.com/1404921/42495460-6e8172a2-8423-11e8-8423-db350dfbfae0.png)
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.16,2
* Browser Name and version: Firefox Linux 64 version 62.0b6
* Operating System and version: Ubuntu bionic

**Comment by gwarser** [comment]
This is problem with Firefox beta build on Ubuntu.

https://old.reddit.com/r/firefox/comments/8x6vv0/all_my_extensions_are_disabled/
https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1780793
