### ISSUE TITLE
`has()`  not work on `<html>`

### ISSUE THREAD

**Issue by imba-tjd** [uBlockOrigin/uBlock-issues#1240]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

```
example.com##html
```

works but none of the

```
example.com##html:has(body)
example.com##html:has(div)
example.com##html:has-text(Example)
```

work.

If this wouldn't be fixed, some info needs adding to wiki.

### A specific URL where the issue occurs

example.com

### Your environment

* uBlock Origin version: 1.29.3b12
* Browser Name and version: FF 81.0b9
* Operating System and version: Win10 20H2

**Comment by gorhill** [comment]
You can't hide the root `html` element. Your repro case is not that of a real world example, please provide real world examples of why you would want to remove `html` elements.

**Comment by gorhill** [comment]
This fails because there is this test before the node is further processed:

    if ( node.parentElement === null ) { continue; }

`html` elements do not have a parent. I will have to remember why this test is there.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/382
