### ISSUE TITLE
This extension uses 100% CPU on macos

### ISSUE THREAD

**Issue by AlexandraK** [uBlockOrigin/uBlock-issues#1244]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The extensions causes Chrome to use 100% CPU every few hours for about 1 minute.
Because of this, If the battery health is below 60% the Macbook will go into sleep mode and cannot be brought back unless you plug it in.

I've been using ublockorigin for years but it only started happening about 2 months ago

### A specific URL where the issue occurs

Everywhere

### Steps to Reproduce

1. Turn on macbook
2. Wait a while
3. CPU goes 100%

### Expected behavior:

Not to use 100% CPU

### Actual behavior:

Uses 100% CPU

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version: macOS 10.15.6

**Comment by uBlock-user** [comment]
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from Firefox Profiler/Chromium Profiler + fully substantiated analysis supporting the claim.
