### ISSUE TITLE
Pop-up interface unresponsive in incognito mode on ChromeOS

### ISSUE THREAD

**Issue by rohitsant** [uBlockOrigin/uBlock-issues#1248]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
On my Chrome OS device, the pop-up interface no longer allows any interaction in incognito mode. This happened after my device updated to Chrome OS 84, and has persisted through Chrome OS 85 (current stable release). See GIF for a demo of the same page opened **first** in a **regular window** and then in an incognito window. uBlock origin continues to work, but does not allow any changes to the filtering and does not allow turning it on/off.

![ublockOrigin](https://user-images.githubusercontent.com/5101152/93284334-49431480-f787-11ea-973d-5d23246ee552.gif)

There is a thread on reddit about this happening about two months ago, but it didn't reach a conclusion: https://www.reddit.com/r/uBlockOrigin/comments/he00oa/ublock_origins_popup_user_interface_not_working/

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Have a ChromeOS device running Chrome OS 85.0.4183.108 (and maybe some unknown set of origin trials as per that reddit thread?)
2. Open a page in Incognito mode and open up the uBlock origin pop-up
3. You should see no specific scripts/domains being listed on the left, not even any custom rules you set up for the site. Clicking on the power button does nothing and reverts to original state in a few sec.

### Expected behavior:

Popup interface allows interaction and shows info exactly as in a non-incognito window

### Actual behavior:

Popup interface does not meaningfully allow interaction, state reverts back after clicking on any buttons, specific domains and rules do not show up on the left. Some icons are missing at the bottom of the popup.

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Chrome 85
* Operating System and version: Chrome OS 85.0.4183.108

**Comment by gorhill** [comment]
I don't have Chrome OS, so I won't be able to investigate.

Can you look if there are any error reported in uBO's dev console?

**Comment by rohitsant** [comment]
The console appears entirely empty. I tried navigating to a different site as well, but didn't see anything in the console there either.
![Screenshot 2020-09-16 at 7 34 16 AM](https://user-images.githubusercontent.com/5101152/93352033-424fec80-f7ef-11ea-94a3-f9a4c653f992.png)

> I don't have Chrome OS, so I won't be able to investigate.

No worries, I'm happy to run any other steps and provide other debug info if it's helpful.

**Comment by gorhill** [comment]
The dev tools window in your screenshot is not even bound to the popup document, so even the browser itself is behaving in an anomalous way. On my side I see `Dev Tools - chrome-extension://...` as title for the dev tools window, while it's blank on your side.

**Comment by rohitsant** [comment]
I think that's just an artifact of how ChromeOS displays window titles - when I go into the Overview mode (alt-tab equivalent) I see the title show up.
![ink](https://user-images.githubusercontent.com/5101152/93359134-1b95b400-f7f7-11ea-9245-27d2ff8f64e1.png)

**Comment by gorhill** [comment]
So the issue is with uBO's popup panel only?

**Comment by rohitsant** [comment]
As far as I can tell the other extensions I have do seem to have their pop-ups working. I am able to interact with DarkReader and BitWarden.

**Comment by gorhill** [comment]
uBO uses `split` for incognito mode, maybe that is what triggers the issue.

**Comment by rohitsant** [comment]
Let me know if I can run any other tests or relay any other debug info.

**Comment by gorhill** [comment]
Can you use uBO's dev tools to put breakpoint to find out the value of the tab id uBO is using for the popup?

There is two code paths in [that function](https://github.com/gorhill/uBlock/blob/d25b9aa30f72c817b95455a41dfb80e2fecf58b2/src/js/messaging.js#L368-L380) which make use of what should be the tab id of the current active tab. Specifically, I would expect that a valid tab/tab id is available [at this line](https://github.com/gorhill/uBlock/blob/d25b9aa30f72c817b95455a41dfb80e2fecf58b2/src/js/messaging.js#L376).

**Comment by krystian3w** [comment]
https://pl.reddit.com/r/uBlockOrigin/comments/jib1h2/ubo_element_picker_mode_not_working_in_chrome/

**Comment by stbeep1** [comment]
#1248 I am having the same issue on my chrome OS laptop.

**Comment by stbeep1** [comment]
**@gorhill I am having the same issue #1248 on my chrome OS laptop.**
Also all of the uBO keyboard shortcuts is not working on chrome os incognito mode, is it a known limitations or a bug?

**Comment by stbeep1** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1248#issuecomment-693326380
@gorhill 
As you said, you don't have a Chrome os laptop, could you please consider running cloudready os in a virtual machine like "vmware"? Cloudready OS is basically the same as Chrome OS. **Also, Neverware is now part of Google in Dec 11, 2020.**

dowload link: https://cloudreadykb.neverware.com/s/article/Download-CloudReady-Image-For-VMware
ref link 02: https://www.theverge.com/2020/12/16/22179242/google-neverware-chromebook-laptops-chrome-os-software
ref link 03: https://cloudreadykb.neverware.com/s/article/Neverware-is-now-part-of-Google-FAQ

**Comment by krystian3w** [comment]
But possible reproduce with CloudReady? On version 7X I did not manage to reproduce - Now I see version 83 in `.ova` file (maybe with fast update to v87).

**Comment by stbeep1** [comment]
> But possible reproduce with CloudReady? On version 7X I did not manage to reproduce - Now I see version 83 in `.ova` file (maybe with fast update to v87).
> 
> https://cloudreadykb.neverware.com/s/article/Download-CloudReady-Image-For-VMware

It's possible to reproduce with CloudReady. Since I run Cloudready OS on my secondary desktop as well.

**Comment by stbeep1** [comment]
**Update: On Chrome OS, if I right click "block element", it's working, but the keyboard shortcuts doesn't work at all in chrome os private mode.**

**Comment by krystian3w** [comment]
I Upgraded my old machine from 78 ➡️  80.X to 85 and I can use manually definied shortcuts:

<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd> = open uBO pop-up
<kbd>Ctrl</kbd>+<kbd>T</kbd> = epicker
<kbd>Ctrl</kbd>+<kbd>R</kbd> = zapper
<kbd>Ctrl</kbd>+<kbd>L</kbd> = the logger

Only medium mode no works after use any of combination (I never used medium mode intentionally = only by accident as I remember)

**Comment by stbeep1** [comment]
> I Upgraded my old machine from 78 ➡️  80.X to 85 and I can use manually defined shortcuts:
> 
> 
> 
> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd> = open uBO pop-up
> 
> <kbd>Ctrl</kbd>+<kbd>T</kbd> = epicker
> 
> <kbd>Ctrl</kbd>+<kbd>R</kbd> = zapper
> 
> <kbd>Ctrl</kbd>+<kbd>L</kbd> = the logger
> 
> 
> 
> Only relaxed mode no works after use any of combination (I never used relaxed mode intentionally = only by accident as I remember)

Does it work in incognito mode? Mine doesn't work in incognito mode.

**Comment by krystian3w** [comment]
Yes, works on Incognito also uBO pop-up detect domain e.g. `google.com`.

**Comment by automaticmath** [comment]
Ublock WORKS to block and filter, etc. in incognito mode but you still can't do stuff like toggle Ublock using the popup window when in incognito mode. If you notice, the toggle button is not blue and clicking on it does nothing. Also, the Ublock icon shows it's working (it's not greyed out and it shows a number of elements blocked) but the popup menu shows 0 blocked.

![Screenshot 2022-10-02 13 31 34](https://user-images.githubusercontent.com/58537024/193468019-507ef098-02e6-49ec-84c4-a03181d7465b.png)


The problem is that if you encounter a website that doesn't function properly with Ublock enabled, you either have to manually whitelist the site or open the site in non-incognito mode to disable Ublock for the website.

**Comment by gorhill** [comment]
This issue is stale, closing. If the issue still exist, the investigation/fix will have to be volunteered by whoever can reproduce it.
