### ISSUE TITLE
disabling advanced features do not disable dynamic filtering

### ISSUE THREAD

**Issue by signalguest** [uBlockOrigin/uBlock-issues#125]
if you enable advanced features you get dynamic filtering
but if you disable advanced features you still have dynamic filtering

tested on firefox and chrome

**Comment by uBlock-user** [comment]
Put back the [template](https://github.com/uBlockOrigin/uBlock-issues/blob/master/.github/ISSUE_TEMPLATE.md) and edit your post accordingly.

**Comment by signalguest** [comment]
enjoy

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel

**Comment by signalguest** [comment]
it should collapse back since it was opened by advanced features

**Comment by uBlock-user** [comment]
By-design behavior, not a bug.

**Comment by gorhill** [comment]
> it was opened by advanced features

That it was opened automatically when enabling _advanced user_ mode is merely a convenience. Closing it automatically though would not be a convenience since the overview panel may still be considered useful in its read-only mode.
