### ISSUE TITLE
Entire uBlock pop-up GUI not visible

### ISSUE THREAD

**Issue by Bartolomeus-649** [uBlockOrigin/uBlock-issues#1254]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
The main POP-UP GUI is only partly visible on screen. Thelocation of the POP-UP GUI depends on where in the tool-bar the uBlock icon is displayed.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
N/A

### Steps to Reproduce

1. [First Step] Click the uBlock  icon in the tool-bar
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
To see the entire uBlock GUI on the screen.

### Actual behavior:

[What actually happened]
![image](https://user-images.githubusercontent.com/7513795/93708215-bf070180-fb34-11ea-8f49-94785abd6fef.png)
![image](https://user-images.githubusercontent.com/7513795/93708233-d7771c00-fb34-11ea-892a-b77b23c5b4a9.png)

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Google Chrome is up to date, Version 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version: Microsoft Windows [Version 10.0.18363.1016]  (Windows 10 x64, Ent. Eng.)

**Comment by gorhill** [comment]
What is the resolution of your screen?

Your browser is responsible for supplying the viewport in which the popup panel is rendered, so if the viewport set by the browser extend beyond the screen, this is a browser issue. The only workaround I see is to reduce the [text size of the popup panel](https://github.com/gorhill/uBlock/wiki/Advanced-settings#popupfontsize).

You will have to open an issue with the browser developers -- there is a similar issue somewhere which was closed as a browser issue, I can't find it at the moment.

**Comment by Bartolomeus-649** [comment]
Widows resolution is 1920 x 1080 with a scale of 150% (Recommended)

![image](https://user-images.githubusercontent.com/7513795/93718107-2e531480-fb7a-11ea-8e40-f12f6a7d8ffc.png)

I tried to change the zoom-level in chrome, but it had no effect at all.

I tried your suggestion to set font size, and with it set to 0.8rem it fits on the screen.
![image](https://user-images.githubusercontent.com/7513795/93718411-49bf1f00-fb7c-11ea-8130-177aebf44d2a.png)

Would it be possible to use any of the other advanced setting to affect this issue?

Suggestion: A "Narrow mode" would be great, where paddings and margins are set to a minimum. Alternatively, add a padding/margins setting to the advanced settings..

**Comment by gorhill** [comment]
In the latest dev build, you can adjust the minimum width of both the main and firewall panes by using the following CSS property in the [advanced setting `uiStyles`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uistyles):

    --popup-firewall-min-width:24em;

For reference, the current default minimum width for the firewall pane is `30em`.

You can also modify the minimum width for the main pane -- which default to `18em`:

    --popup-main-min-width:16em;

You can customize both:

    --popup-main-min-width:16em;--popup-firewall-min-width:24em;

I consider this should take care of the issue for now since so far you are the only person having reported such issue.

**Comment by Bartolomeus-649** [comment]
Ok, but isn't max-width what I would need in my case? I mean, min-with prevents something from getting to small, right?

**Comment by gorhill** [comment]
I don't think `max-width` is reached in your case, so it's not the property which will have an effect, and in any case `min-width` has priority over `max-width`. If you set `min-width` to `unset` you will see that the popup panel will be too narrow to be usable.
