### ISSUE TITLE
Just wanted to say: Thank you

### ISSUE THREAD

**Issue by dodmi** [uBlockOrigin/uBlock-issues#1255]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Hi @gorhill 

as you have set uMatrix's issue tracker to read only, I'm misusing this one to say thank you for all the efforts you have invested into uMatrix, which has been a valued companion for years - and still will be until a browser update will break compatibility.

Best regards

**Comment by mapx-** [comment]
for discussions / questions / other => https://www.reddit.com/r/uBlockOrigin/
