### ISSUE TITLE
HTML filtering bypassed by image lazy loading script

### ISSUE THREAD

**Issue by garmendes** [uBlockOrigin/uBlock-issues#1257]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In this website it's possible to filter HTML text tags but not image tags. I suppose this is because of a lazy loading image script.

### A specific URL where the issue occurs

`https://www.brasil247.com/mundo/china-dispara-na-frente-na-corrida-pela-vacina-contra-a-covid-19-yitgne03`

### Steps to Reproduce

1. Test `www.brasil247.com##img[src$="/siga-googlenews.png"]:upward(1)`
2. Test `www.brasil247.com##^img[src$="/siga-googlenews.png"]:upward(1)`
3. Test `www.brasil247.com##^h2`

### Expected behavior:

Google News tag removed from HTML

### Actual behavior:

Google News tag present

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Firefox 80
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
> Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
