### ISSUE TITLE
Changing Elements

### ISSUE THREAD

**Issue by VidarrKerr** [uBlockOrigin/uBlock-issues#1258]
Is there a way to deal with recurring elements that always pop-up in the same place, but change suffix IDs?

For example (from RT News site):

! 2020-09-14 https://www.rt.com
www.rt.com###recomendation-5f5f918a85f54023bb0efcc3
! 2020-09-22 https://www.rt.com
www.rt.com###recomendation-5f69cbc085f54054e04d070b

It is the suffix ID numbers (5f....) there that continue to change almost every time the page is refreshed. How can uBlockO deal with this? I tried an * and it didn't work. I don't know if that is a broken feature. 

THANKS!

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at https://www.reddit.com/r/uBlockOrigin/.
