### ISSUE TITLE
Remove mention of uMatrix in README

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1259]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since uMatrix is now archived, I think the mention of it in uBlock README is obsolete and should be removed.

### A specific URL where the issue occurs

`https://github.com/gorhill/uBlock#philosophy`

### Steps to Reproduce

1. Just visit the page and find the mention.

### Expected behavior:

NA

### Actual behavior:

NA

### Your environment

Irrelevant

**Comment by llacb47** [comment]
Why should the mention be removed? uMatrix still works.

**Comment by Yuki2718** [comment]
> Why should the mention be removed? uMatrix still works.

Works but no more available to ordinary user who haven't installed and don't know how to side-load. I leave the decision to uBO team, it's just a heads up.

**Comment by uBlock-user** [comment]
> Works but no more available to ordinary user who haven't installed and don't know how to side-load. 

It's available in the stores and will remain available. Only development and maintainence has stopped fyi.

**Comment by Yuki2718** [comment]
> > Works but no more available to ordinary user who haven't installed and don't know how to side-load.
> 
> It's available in the stores and will remain available. Only development and maintainence has stopped fyi.

Oh, sorry then. But given you added labels and didn't close, leave this as is.
