### ISSUE TITLE
Several suggestions for strengthening `element zapper mode`

### ISSUE THREAD

**Issue by dnknn** [uBlockOrigin/uBlock-issues#1260]
![209_23060927](https://user-images.githubusercontent.com/10995302/93942620-59e52300-fd63-11ea-8abe-12653d2eda0b.png)
![209_23055038](https://user-images.githubusercontent.com/10995302/93941301-ba269580-fd60-11ea-8c18-a23c76062a8a.png)`element zapper mode`

---
- ## 💥 Current issue: 
 　　　　🛇. Cannot remove elements continuously ( remov an element, it is turned off) .
 　　　　🛇. When selecting elements,  cannot use hotkeys to quickly select element levels.
 　　　　🛇. Cannot use Ctrl+Z/Ctrl+Shift+Z to undo/redo the last operation.

- ## ❥ Expected behavior / Implementation plan :
　　　　✚ Add support to easily remove multiple elements in a row (continuously)
　　　　✚ About hotkeys of selecting elements,  refer to this extension: 
　　　　`Click to Remove Element`  (`CTRE`)
 　　　　 https://chrome.google.com/webstore/detail/jcgpghgjhhahcefnfpbncdmhhddedhnk
> Very simple to use:  use `Q`/`W` to select element level 

<details>
<summary>🎬 Click to seeing gif demo: </summary>

![123456](https://user-images.githubusercontent.com/10995302/93934708-2354db80-fd56-11ea-956a-c31ca36ac920.gif)

</details>

----

### But `CTRE` is not enough, it will be perfect if can add the following 5 hotkeys 👇

> These hotkeys are the most basic standard universal hotkeys. If `uBlock Origin` can be supported, it will be very convenient for temporarily remove elements.

## `Space ` :  　　confirm ꘌ Equivalent to click
>  Use the `mouse` moving to **selecting the element**, and then press the `Space` button to **directly remove** the element.

## `Shift+Tab` :    ꘌ Equivalent to `W`

![209_23041447](https://user-images.githubusercontent.com/10995302/93932831-59dd2700-fd53-11ea-82e6-e600c27ef338.png)

**Comment by uBlock-user** [comment]
> Cannot remove elements continuously ( remov an element, it is turned off) .

Aim with the mouse and then use delete button on keyboard.

**Comment by dnknn** [comment]
> Aim with the mouse and then use delete button on keyboard.

Hmm. It’s better to add another option: ⬜ Exit immediately after removing elements by mouse-clicking (Esc exit)

**Comment by dnknn** [comment]
> Aim with the mouse and then use delete button on keyboard.

Hmm. Thanks♪(･ω･)ﾉ !
If supported,  use the `Space` button to remove continuously (will not exit), 
Because `Space` is on the left hand area of the keyboard, and `Delete` is on the right side of the keyboard.


<s>It’s better to add another option: ⬜ Exit immediately after removing elements by mouse-clicking (Esc exit)</s>

**Comment by gorhill** [comment]
I am declining this because I rather spend time on what I see as features unlikely to be useful to many -- what is there is quite enough for majority of users.

**Comment by dnknn** [comment]
> I am declining this because I rather not spend time on what I see as features unlikely to be useful to most -- what is there is quite enough for majority of users.

okay. It doesn't matter, this is not a big problem.

**Comment by gwarser** [comment]
> If supported, use the `Space` button to remove continuously (will not exit),
> Because `Space` is on the left hand area of the keyboard, and `Delete` is on the right side of the keyboard.

Hold <kbd>Shift</kbd> while clicking https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-zapper

**Comment by dnknn** [comment]
> Hold Shift while clicking

Thanks :)
