### ISSUE TITLE
Deployment of whitelist

### ISSUE THREAD

**Issue by sorentorp** [uBlockOrigin/uBlock-issues#1262]
Hi
I'm trying to deploy uBlockOrigin to my G Suite domain with a predefined list os trusted sites; whitelist. I have succes when the two sites systematic-momo.dk and alinea.dk are whitelisted for our users - the rest of the settings is just for testing :-)

We are using chromebooks and are G Suite for Education customers. We have deployed uBlock Origin as a force-installed app for our users.

But the problem occurs when I want to deploy a whitelist and other settings for our users. I have found different guides on similar issues, but with no luck - the settings don't seem to affect uBlock Origin - I hope you can help.

Pushed settings in G Suite Admin - JSON checks out fine etc.

`{ "adminSettings": { "Value": "{ \"userSettings\": {\"colorBlindFriendly\": true, \"cloudStorageEnabled\": true }, \"netWhitelist\": \"about-scheme\\chrome-extension-scheme\\chrome-schemeedge-scheme\\moz-extension-scheme\\opera-scheme\\vivaldi-scheme\\wyciwyg-scheme\\systematic-momo.dk\\alinea.dk\", \"userFilters\": \"systematic-momo.dk\" }" } }`

policies on chrome device - looks good to me

`
"cjpalhdlnbpafiamejdnhcphjbkeiagm": {
"adminSettings": {
            "level": "mandatory",
            "scope": "user",
            "source": "cloud",
            "value": "{ \"userSettings\": {\"colorBlindFriendly\": true, \"cloudStorageEnabled\": true }, \"netWhitelist\": \"about-scheme\\chrome-extension-scheme\\chrome-schemeedge-scheme\\moz-extension-scheme\\opera-scheme\\vivaldi-scheme\\wyciwyg-scheme\\systematic-momo.dk\\alinea.dk\", \"userFilters\": \"systematic-momo.dk\" }"
         }
      },
`

Some screenshots from the GUI - not affected by my settings.

![Screenshot 2020-09-23 at 23 09 48](https://user-images.githubusercontent.com/4117997/94070211-18e81f80-fdf2-11ea-9eca-33fe9bd49f48.png)
![Screenshot 2020-09-23 at 23 09 31](https://user-images.githubusercontent.com/4117997/94070217-1980b600-fdf2-11ea-8644-8ddd1796b2dc.png)
![Screenshot 2020-09-23 at 23 09 24](https://user-images.githubusercontent.com/4117997/94070218-1a194c80-fdf2-11ea-8f3d-c758e9811d8a.png)

**Comment by gwarser** [comment]
New line characters `\n` are converted to simple `\` - is this GitHub formatting error or something on your side?

**Comment by krystian3w** [comment]
> n\nn\nw\np

**Comment by krystian3w** [comment]
> 
> 
> Hi
> I'm trying to deploy uBlockOrigin to my G Suite domain with a predefined list os trusted sites; whitelist. I have succes when the two sites systematic-momo.dk and alinea.dk are whitelisted for our users - the rest of the settings is just for testing :-)
> 
> We are using chromebooks and are G Suite for Education customers. We have deployed uBlock Origin as a force-installed app for our users.
> 
> But the problem occurs when I want to deploy a whitelist and other settings for our users. I have found different guides on similar issues, but with no luck - the settings don't seem to affect uBlock Origin - I hope you can help.
> 
> Pushed settings in G Suite Admin - JSON checks out fine etc.
> 
> > { "adminSettings": { "Value": "{ "userSettings": {"colorBlindFriendly": true, "cloudStorageEnabled": true }, "netWhitelist": "about-scheme\nchrome-extension-scheme\nchrome-schemeedge-scheme\moz-extension-scheme\opera-scheme\vivaldi-scheme\wyciwyg-scheme\systematic-momo.dk\nalinea.dk", "userFilters": "systematic-momo.dk" }" } }
> 
> policies on chrome device - looks good to me
> 
> > "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
> > "adminSettings": {
> > "level": "mandatory",
> > "scope": "user",
> > "source": "cloud",
> > "value": "{ "userSettings": {"colorBlindFriendly": true, "cloudStorageEnabled": true }, "netWhitelist": "about-scheme\chrome-extension-scheme\chrome-schemeedge-scheme\moz-extension-scheme\opera-scheme\vivaldi-scheme\wyciwyg-scheme\systematic-momo.dk\alinea.dk", "userFilters": "systematic-momo.dk" }"
> > }
> > },
> 
> Some screenshots from the GUI - not affected by my settings.
> 
> ![Screenshot 2020-09-23 at 23 09 48](https://user-images.githubusercontent.com/4117997/94070211-18e81f80-fdf2-11ea-9eca-33fe9bd49f48.png)
> ![Screenshot 2020-09-23 at 23 09 31](https://user-images.githubusercontent.com/4117997/94070217-1980b600-fdf2-11ea-8644-8ddd1796b2dc.png)
> ![Screenshot 2020-09-23 at 23 09 24](https://user-images.githubusercontent.com/4117997/94070218-1a194c80-fdf2-11ea-8f3d-c758e9811d8a.png)

**Comment by krystian3w** [comment]
Is this rather a bug of his software, for example a notepad?

**Comment by gorhill** [comment]
[JSONLint](https://jsonlint.com/) fails for me with your data:

    Error: Parse error on line 3:
    ...{		"Value": "{ "		userSettings ": {"	
    ---------------------^
    Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

**Comment by sorentorp** [comment]
I think there is some formatting error on GitHub.
See pastebin link here: https://pastebin.com/AhRGEGQH

**Comment by krystian3w** [comment]
Use  \`some of code\` instead of one `>` to publish codes, 

@uBlock-user  try test change quotes into codes on first post in this issue?

**Comment by sorentorp** [comment]
I fixed the first post, so nvm the pastebin.

**Comment by gorhill** [comment]
When I paste your value string:

    "{ \"userSettings\": {\"colorBlindFriendly\": true, \"cloudStorageEnabled\": true }, \"netWhitelist\": \"about-scheme\\chrome-extension-scheme\\chrome-schemeedge-scheme\\moz-extension-scheme\\opera-scheme\\vivaldi-scheme\\wyciwyg-scheme\\systematic-momo.dk\\alinea.dk\", \"userFilters\": \"systematic-momo.dk\" }"

At <http://raymondhill.net/ublock/adminSetting.html> (last field at the bottom), I get an error:

    SyntaxError: JSON.parse: bad escaped character at line 1 column 109 of the JSON data

From what I can see, your `\\` should be `\\n` in the final string, like so (I also fixed a erroneously removed newline):

    "{ \"userSettings\": {\"colorBlindFriendly\": true, \"cloudStorageEnabled\": true }, \"netWhitelist\": \"about-scheme\\nchrome-extension-scheme\\nchrome-scheme\\nedge-scheme\\nmoz-extension-scheme\\nopera-scheme\\nvivaldi-scheme\\nwyciwyg-scheme\\nsystematic-momo.dk\\nalinea.dk\", \"userFilters\": \"systematic-momo.dk\" }"

**Comment by sorentorp** [comment]
After a lot of fiddling about, I found a config that works - flawless :-)

`{"adminSettings":{"Value":"{ \"netWhitelist\": \"alinea.dk\\nsystematic-momo.dk\\nsystematic-momo.com\" }"}}`
