### ISSUE TITLE
Can't install v1.29.3rc12 on current Fx Dev

### ISSUE THREAD

**Issue by Alpengreis** [uBlockOrigin/uBlock-issues#1265]
Can't install v1.29.3rc12 on current Fx Dev

Not over the Extension Update function and also not manually via downloaded file (says it seems defect or so) ...

**Comment by gorhill** [comment]
Oops, completely forgot to launch the publish script. It's ongoing now, so it should be there in a few minutes.

**Comment by uBlock-user** [comment]
Because it's un-signed.

**Comment by gorhill** [comment]
Publish script completed, so it should be available now.
