### ISSUE TITLE
Logger Tool-tip and usability improvements

### ISSUE THREAD

**Issue by Bartolomeus-649** [uBlockOrigin/uBlock-issues#1267]
_[Suggestion, not an issue so template deleted.]_

It would be great with something along this way for the logger.
_NOTE: The provided modified screenshoot is just an example and shouldn't be taken/seen as a finished design proposal or implementation requirement. It should be more viewed as an indication of what perhaps could be done to the logger to make it more intuitive and user friendly._

![image](https://user-images.githubusercontent.com/7513795/94362253-58489180-00ba-11eb-937b-c1a590ce4cc4.png)

Perhaps some headings for the columns would be nice as well?

Also, I have no clue if the provided explanation for a yellow row with << is correct, so don't get caught up on that, it's just there as an example.

**Comment by Yuki2718** [comment]
I hope that can be turned off or does not automatically pop up. For those who heavily use the logger everyday they're nothing less than annoyance. Frankly I wonder if that's worth effort when everything is well-explained in Wiki. Maybe better to embed href to relevant Wiki pages? IDK.

Off-topic: yellow line is either resource redirect or HTML/cosmetic filtering and resource redirect is not necessarily for a well-known one.

**Comment by Bartolomeus-649** [comment]
I agree with @Yuki2718 , there should be an easy way to opt out, or even the possibility to config the tool-tip with which info it should contain.

**Comment by gorhill** [comment]
No worry, I use the logger myself quite a lot.

The only reason I kept this issue open is for the ability to expand one specific row without to have to expand them all. This is something I wish I could have kept when I refactored the logger -- it's just not trivial to implement but I would give it a go if ever there is enough time on hand. For the rest of the suggestions, I decline them all.
