### ISSUE TITLE
Feature request: regex filter

### ISSUE THREAD

**Issue by DoganM95** [uBlockOrigin/uBlock-issues#1268]
Could you please add a regex- filter functionality?

E.g. there are sites which generate an element-name by a specific scheme ("`aeg_14`") and on each site reload this name changes, ("`ope_66`") but the scheme is obvious (`xxx_00`).

now when clicking on element picker and choosing that element, i as a user would love to conveniently change the automatically chosen element name ("`xyz_13`") to a regex pattern, in this case `/w{3}_/d{2}` to get rid of this dynamic element once and for all.

please make this possible, as many sites nowadays are using generated element names.

**Comment by gwarser** [comment]
This is the first time I hear about this. Please put back issue template and fill all fields.

**Comment by DoganM95** [comment]
> This is the first time I hear about this. Please put back issue template and fill all fields.

You mean about dynamic element names? I will put back the issue template and give more detail soon.

**Comment by gorhill** [comment]
Report your issue as a filter issue at <https://github.com/uBlockOrigin/uAssets/issues>, this is not the right place to report filter issue, as noted in the template.

**Comment by gorhill** [comment]
And to be clear, no feature request such as what you are asking here are accepted, such features are added by consensus with filter list maintainers following long discussion, and always involve actual cases.
