### ISSUE TITLE
Add button on filter list to "Clear All"

### ISSUE THREAD

**Issue by jefferysmall** [uBlockOrigin/uBlock-issues#1269]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I export my filter list and want to import it onto other devices.  On the desktop it is easy to "select all" and delete the current filters before importing the new master filter list.  However, on Firefox Mobile on my Samsung Android phone, I can find no way to select all of the existing filter content prior to importing the new filter set.

I'd like to suggest adding a "Clear All" button at the top of the filter tab that would perform this function.  

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: v1.29.5.12  (1.29.2 on Firefox Mobile)
* Browser Name and version:  Firefox 81.0 on desktop (latest mobile version)
* Operating System and version: Xubuntu 20.04 on desktop (Android 10 on phone)

**Comment by gwarser** [comment]
Importing settings overrides everything. Are you talking about "My filters"? Double tap on gutter (line numbers) to select all.

**Comment by jefferysmall** [comment]
Fantastic!  I tried everything I could think of to select all, but not that.  Thank you for the information.

Yes, I'm talking about "My Filters".

And just to be clear that I understand you properly, when I import, the button says "Import and append" so I though this was telling us that it would just add the imports to what was already there, creating many duplicate in the process.  Are you saying that all existing content will be deleted when a file is imported, or possibly you are saying that duplicates will be overridden but unique entries existing in the file will remain?  I'd appreciate understanding precisely what will happen and what the "append" label is indicating.

Regards.

**Comment by gwarser** [comment]
I was talking about "Backup" feature on the bottom of "Settings" tab. "Import and append" will append only new filters - no duplicates will be created.

**Comment by jefferysmall** [comment]
Great!  Thanks again for straightening me out on all of this.

**Comment by honvai** [comment]
Twitch ad's show up on all streams that I visit.
