### ISSUE TITLE
It's too difficult to add custom filters to block web domains or specific websites

### ISSUE THREAD

**Issue by ozmium** [uBlockOrigin/uBlock-issues#127]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It's too difficult to add custom filters to block web domains or specific websites. There is a lack of pre-written examples.

### A specific URL where the issue occurs

uBlock Origin - Settings (Dashboard) - My Filters

### Steps to Reproduce

1. Try to write a filter for a whole website. Type in `www.google.com` or `www.google.com/*`, and save with "Apply Changes"
2. Test out the filter by loading the page.
3. Notice that the filter doesn't work.
4. Try to search online for how to add a simple filter, and just keep retrying a lot.

### Expected behavior:

* We should see many example filters, pre-written (perhaps commented out), which explain how to add new ones.
* An example text should include a description or comment. Something like this:
```
# This will block the whole domain www.google.com or https://google.com
||google.com^ 

# This will block a specific page at www.google.com or https://google.com
||google.com/document1^$document 
```

### Actual behavior:

* There are no guidelines on the uBlock settings on how to write custom filter rules.
* The wiki documentation does not provide suitable example filters.
* Users normally have to experiment, and type something simple, like "www.google.com", then test it, only to realise that it doesn't work. It's a long process to figure out the correct syntax, to get it working.

### Your environment

* uBlock Origin version: v1.16.12
* Browser Name and version: Google Chrome 67 or Firefox 61
* Operating System and version: Mac or Windows, latest versions

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax

**Comment by uBlock-user** [comment]
Linked ABP's filter cheatsheet on the above wiki page.

**Comment by gwarser** [comment]
Documentation link:
![image](https://user-images.githubusercontent.com/886325/42645689-fe89273c-85fe-11e8-89a7-55479c9735b1.png)

**Comment by ozmium** [comment]
Thanks for the link. But I think the uBlock settings page needs a kind of Quick Start guide that is short and direct and simpler. The wiki page is more of a long user manual.

Also the wiki page doesn't explain how to block URLs that have a slash "/" character in them, like `https://www.iana.org/domains` or `https://www.iana.org/domains/reserved` .

And the tiny "i" icon can be easily missed. I would prefer a big text link, like "Click here for help on how to write a custom filter".

Is it possible to add these features?

**Comment by uBlock-user** [comment]
Wiki can't cover each and every question, such questions come under user support which is on [reddit](https://www.reddit.com/r/uBlockOrigin/).
