### ISSUE TITLE
My Rules setting page cloud export issue 

### ISSUE THREAD

**Issue by ctrlcmdshft** [uBlockOrigin/uBlock-issues#1270]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using cloud storage support when trying to export to cloud storage on My Rules page it does nothing 
if a remove a bunch of rules from within the My Rules it will then allow me to export to cloud storage

Note: My "My Rules" section has roughly 3000 rules in it so i don't know if its exceeding any size limits or not.

### A specific URL where the issue occurs

Within uBlock settings pane for My Rules

### Steps to Reproduce

1. Go to uBlock settings
2. Click on My Rules section
3. Click on export to cloud storage button
4. Nothing happens

### Expected behavior:

Should export to cloud storage and show time stamp of last export to cloud storage

### Actual behavior:

Nothing happens 

### Your environment

* uBlock Origin version: v1.29.2
* Browser Name and version: Firefox 81.0 (64-bit)
* Operating System and version: Windows 10 v.2004 Build 19041.508

**Comment by gwarser** [comment]
My 1150 rules when exported to file uses over 40kB - cloud limit is 100kB. In next version you will have option to compress cloud storage which will probably help.

**Comment by gorhill** [comment]
Try the [dev build](https://github.com/gorhill/uBlock/releases/tag/1.29.3rc12), it will tell you if you overshoot the cloud storage limit. That limit is out of control of uBO.
