### ISSUE TITLE
[Issue] Twitch got updated and now ad's show up.

### ISSUE THREAD

**Issue by azgoodaz** [uBlockOrigin/uBlock-issues#1271]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Twitch got updated and now ad's show up on all streams that I visit.

### Steps to Reproduce

N/A

### Expected behavior:

No ad's appear.

### Actual behavior:

Ad's appear.

Image of Ad's: https://cdn.discordapp.com/attachments/327957673507029013/760311922246811668/unknown.png

### Your environment

* uBlock Origin version: Latest
* Browser Name and version: Microsoft Edge (latest build)
* Operating System and version: Windows 10, 2004 (latest build)

**Comment by 1darklyte** [comment]
Reporting this happening as well.

Browser: Firefox 81.0 (64-bit)
OS: Windows 10, 2004 (latest build)

**Comment by GalaticRailroad** [comment]
Started happening today.

uBlock Version: 1.29.2 
Browser: Firefox 81.0 (64-bit)
OS: Windows 10, Version10.0.18362 Build 18362

**Comment by llacb47** [comment]
All of you people cannot read... there is already an issue for this.

Please go comment or thumbs-up here: https://github.com/uBlockOrigin/uAssets/issues/5184

@azgoodaz please close this one. It will be closed as a duplicate anyway.

**Comment by honvai** [comment]
Twitch ad's show up on all streams that I visit.

**Comment by honvai** [comment]
> All of you people cannot read or search GH... there is already an issue for this.
> 
> Please go comment or thumbs-up here: [uBlockOrigin/uAssets#5184](https://github.com/uBlockOrigin/uAssets/issues/5184)
> 
> @azgoodaz please close this one. It will be closed as a duplicate anyway.

that is old issue
