### ISSUE TITLE
Update timestamp on Filter list tab

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#1275]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Not an issue but a feature request. I would like a timestamp on the Filter List tab at the end of the line of total filters that indicates the last time it was updated. Reason might help those that update often know when was the last update was preformed. Also could help list maintainers with their bandwidth by reducing the amount of manual updates to keep filters updated.

### Your environment

* uBlock Origin version: 1..30.1b1
* Browser Name and version: Firefox 81.0.1
* Operating System and version: Windows 10 19042.546 Enterprise

**Comment by gwarser** [comment]
There is already a tooltip over clock icon for every list.

**Comment by troysjanda** [comment]
Yes, however people may not be aware of that. It would be much easier and user aware if it is displayed next to the total filters line, then having to mouse over each filter list to see when and if it was updated recently. As a list maintainer ( although I don't have many subscriptions to my lists ) and comments made that manually updating can cause undue strain on list maintainers bandwidth, this could be a indicator that the lists have been updated recently and a re-manual update is not necessary.

**Comment by gorhill** [comment]
> this could be a indicator that the lists have been updated recently

Well if the "Update now" button is disabled, this means all the lists have been updated recently.

**Comment by troysjanda** [comment]
> Well if the "Update now" button is disabled, this means all the lists have been updated recently.
@troysjanda

Yes, But how long ago were they updated. Not sure how much overhead this request cost, but might help those that constantly have the need to update, not be so inclined to manually update if the timestamp was there. @gorhill
