### ISSUE TITLE
Subscription issues

### ISSUE THREAD

**Issue by e-d-e** [uBlockOrigin/uBlock-issues#1276]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
      This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    

- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue

    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs
Hello,@gorhill
https://github.com/uBlockOrigin/uBlock-issues/wiki/Filter-lists-from-around-the-web
Because custom subscriptions can directly use 301 & 302 redirect URLs, especially the most common shortened URLs.
but,can you please add crawl support for frame URL forwarding?

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.30
* Browser Name and version:Fireofx
* Operating System and version:windows 10

**Comment by gwarser** [comment]
No idea what you want.

**Comment by gorhill** [comment]
It sounds to me he wanted uBO to automatically replace a redirected URL with the `200 OK` URL at the end of the chain. If so, I would decline anyway -- the safest assumption is that when a URL is explicitly subscribed to by the user in uBO, this should not be second-guessed by uBO.
