### ISSUE TITLE
No keyboard shortcut in dashboard/'My filters' to comment/comment out lines

### ISSUE THREAD

**Issue by darkred** [uBlockOrigin/uBlock-issues#1279]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There's no keyboard shortcut in dashboard/'My filters' to comment/comment out lines.
It would be very convenient to have, especially when you want to just toggle multiple lines.

I see in the source code that `comment.js`, the CodeMirror comments add-on ([link](https://codemirror.net/doc/manual.html#addons)), is already included in "My Filters": 
https://github.com/gorhill/uBlock/blob/master/src/1p-filters.html#L42

My suggestion is to make use of this addon to add quick line toggling via <kbd>Ctrl-/</kbd> (or <kbd>Cmd-/</kbd> on mac).

_For reference, if it helps, here is the commit that recently added this functionality in Greasemonkey extension:_
https://github.com/greasemonkey/greasemonkey/commit/99da550e8ad25cf5cb6bc791fe488a46771010c5

### A specific URL where the issue occurs

chrome-extension://____/dashboard.html#1p-filters.html

### Steps to Reproduce

1. have some filters (one per line) in dashboard/'My filters'
2. click on such a line
3. press <kbd>Ctrl-/</kbd> (or <kbd>Cmd-/</kbd> on mac)

### Expected behavior:

An `!` should be prefixed with/removed from the line.

### Actual behavior:

Nothing happened.

### Your environment

* uBlock Origin version: 1.30.0
* Browser Name and version: Chrome 85/Firefox 81
* Operating System and version: Win10 x64

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters>:

> <kbd>Tab</kbd>: (uBO-specific) Toggle prepending the current line or the lines in the current selection with ! (to quickly toggle the commenting out of filters).

**Comment by darkred** [comment]
Thanks a lot for the quick response. That page totally missed my attention.

By the way, I believe it would be useful to include the https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters link to the informative line in "My filters" as a second 'i' :

> One filter per line. A filter can be a plain hostname, or an EasyList-compatible filter. Lines prefixed with ! will be ignored. [[i](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax)] [[i](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)]

**Comment by gorhill** [comment]
> I believe it would be useful to include the https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters link to the informative line in "My filters"

Yes, good point. I will not add a new `i` icon, but just link directly to [Dashboard: My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) -- the [Static filter syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax) page is linked from there already.
