### ISSUE TITLE
uBO intermittently don't block scripts

### ISSUE THREAD

**Issue by cae3uax** [uBlockOrigin/uBlock-issues#128]
I want to block ANY script from executing, so I have added the following rules to "My rules", everything else is default: 

    * * 1p-script block
    * * 3p-frame block
    * * 3p-script block
    * * inline-script block

However, intermittently uBlock Origin still allow scripts to run. I notice this when 
opening Firefox and see that Google autocomplete is working, a feature that requires 
Javascript.

If I open the logger and type something in the Google search field, `xhr` is 
printed as the type of request. If the page is reloaded, scripts are blocked as 
expected.

I'm using Firefox 61.0.1 and uBlock Origin 1.16.12, but I have seen this behaviour 
across multiple versions of both Firefox and uBlock Origin.

**Comment by uBlock-user** [comment]
Put back the template and fill in all the requested info.

**Comment by gorhill** [comment]
> when opening Firefox and see that Google autocomplete is working

Probably a duplicate of <https://github.com/gorhill/uBlock/issues/1327>.

**Comment by uBlock-user** [comment]
I was just going to tag it.

**Comment by cae3uax** [comment]
Yes, this is the same issue I was experiencing.

I tried to enable `extensions.webextensions.background-delayed-startup` and after restarting Firefox first time after the change, scripts on the hompage was executed like uBO was disabled, but restarting Firefox again seemed to fix the problem and after many test with opening and closing Firefox I have not had any scripts execute.

On other machines I have tried setting `suspendTabsUntilReady` to `true` i uBO and this also fixes the problem.

I don't know what the best fix is, but both methods seems to work.

**Comment by uBlock-user** [comment]
There is no best fix, this is the default browser-behaviour. `suspendTabsUntilReady` is experimental, so it may or may not work at times.

**Comment by uBlock-user** [comment]
`suspendTabsUntilReady` is experimental, so it may or may not work at times. Firefox's fix should take care of this for itself, but there's no such fix for Chromium yet.

**Comment by gorhill** [comment]
I am pretty sure Firefox's fix does not specifically fix the issue for uBO, as uBO never tells Firefox when all its filter lists are loaded. The fix is probably that uBO is guaranteed to be launched after uBO has been launched. If so, `suspendTabsUntilReady` is the real fix -- it means now it will work as intended with Firefox.

**Comment by huubert** [comment]
This is still not fixed. I tested with:
- all combinations of these settings:
  - `suspendTabsUntilReady`
  - `extensions.webextensions.background-delayed-startup`
- left one tab open: `http://127.0.0.1:8000/icon38@2x.png` (local http server)
- added this filter: `||127.0.0.1^`
- cleared all history before reopening Firefox

When I reopen Firefox, it will load the image:
https://i.imgur.com/PLYVJPD.png
https://i.imgur.com/9oxd3hX.png
...and a few seconds later, uBlock will reload the page and block it:
https://i.imgur.com/xQznZ7D.png

**Comment by uBlock-user** [comment]
The setting is experimental, it may work and may not.

**Comment by huubert** [comment]
Yes, I understand that. I tested it myself because there's a lot of information that may lead people to think that it's fixed (including a Firefox update), when it's not.
The only workaround I know of is to just leave an open tab (blank/home/whatever) selected when closing Firefox, so that in the next session it won't load any tab with content that should have been blocked.

**Comment by uBlock-user** [comment]
> The only workaround I know of is to just leave an open tab (about:blank, about:home, about:newtab, whatever) selected when closing Firefox, so that in the next session that will be the active tab

or simply don't restore your session, restoring your session causes the race condition to trigger in all browsers and they simply don't wait for extensions to load. This behaviour, unfortunately, is by-design.

Until the browser-devs fix it as mentioned in the [wiki](https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental), do not consider it to be fixed.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/1327

**Comment by gwarser** [comment]
I just recently read about this here https://bugzilla.mozilla.org/show_bug.cgi?id=1501159#c2
Blocking should work, but listener must be registered in top level of background script (before any async operation) and "await" for settings.

**Comment by gorhill** [comment]
> listener must be registered in top level of background script (before any async operation) and "await" for settings.

This is what uBO is doing if `suspendTabsUntilReady` is `true`: <https://github.com/gorhill/uBlock/blob/6d9382a5017e0d32de27562e3c8d678365d14283/src/js/traffic.js#L1153>.

**Comment by gorhill** [comment]
The "suspend" listener is removed once uBO install the listener used for filtering. "Top level scope" means the listener is added not through an event, which is what uBO is doing. Don't modify the code and see if uBO is blocking early requests -- uBO will report early requests blocked in browser console (Firefox) or its own console (Chromium).

**Comment by gorhill** [comment]
I get a "listener not re-registered" in browser console at launch (when using `--jsconsole`).

I am going to have to read this bug entry to understand what I need to do -- I thought I had to only register a listener early...

**Comment by gorhill** [comment]
A bit clearer here: <https://bugzilla.mozilla.org/show_bug.cgi?id=1503721>.

My understanding is that uBO should not add/remove a listener which purpose is specifically to handle early requests and nothing else -- it has to be added and never removed.

**Comment by gorhill** [comment]
No matter what, I am not able to get rid of the error message -- I register a global listener at the global lexical scope and never remove it, still:

    listener not re-registered ExtensionCommon.jsm:2158
      clearPrimedListeners    resource://gre/modules/ExtensionCommon.jsm:2158:24
      onManifestEntry/<    chrome://extensions/content/parent/ext-backgroundPage.js:77:7
      InterpretGeneratorResume    self-hosted:1255:8
      next    self-hosted:1210:9

**Comment by gwarser** [comment]
This snippet blocks early requests if put inside `background.JS` or if linked in first script tag in uBO background.html

```
browser.webRequest.onBeforeRequest.addListener(
    (details) => {
        console.info('My suspend tab %d, block %s', details.tabId, details.url);
        return { cancel: true };
    },
    { urls: [ 'http://*/*', 'https://*/*' ] },
    [ 'blocking' ]
);

```

It does NOT work for URL (remote image) specified in command line (but works for subresources). Works for pages resumed from previous session.

**Comment by uBlock-user** [comment]
Back a versions ago (Chromium 55 to 60 I guess), if `suspendTabsUntilReady` was set to `true` and lets say you set a url to be opened immediately upon startup, I was met with this page illustrated below(baidu.com for example)  -

![](https://lh3.googleusercontent.com/7I91eXS0EbyBKPpZ6YlrcnDOMxrTN80UZ7cSW4GeNg5RjBDTKDEAU4ZhV8C2pfxE-C03X0F9sg=w640-h400-e365)

That behaviour was perfect and no connection was made, but for some reason went away and no longer happens, can this behaviour be brought back ?

**Comment by gorhill** [comment]
Blocking whole document was causing <https://github.com/gorhill/uBlock/issues/3130>.

**Comment by uBlock-user** [comment]
That was affecting Firefox only though..

**Comment by uBlock-user** [comment]
Could you add parameter in the setting which can be set via advanced settings so as to bring that behaviour ?
