### ISSUE TITLE
cosmetic filter `## selector` is valid in element picker only

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#1280]
> cosmetic filter `## selector` is valid in element picker only

### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

open any page e.g. Google, activate element picker interface, put in the text area:

`## body`

Filter hide something (not `<body>`), but "`my filters`" tab marked as **invalid**

![obraz](https://user-images.githubusercontent.com/35370833/95114599-7b231780-0744-11eb-8f24-06211eb2b2bf.png) | ![obraz](https://user-images.githubusercontent.com/35370833/95114664-91c96e80-0744-11eb-9638-bdaa8f22f402.png)
--- | ---

similar/related: #1118  / #1134 

### A specific URL where the issue occurs

google.com

### Steps to Reproduce

1. open google site or any other
2. try hide someting with element picker
3. change proposition to `## body`
4. element picker still hide old element (not `<body>`)
5. possible save filter

### Expected behavior:

Mark these cosmetic filters as invalid **in element picker** too

### Actual behavior:

- Filter generate FP about works in element picker

- In the past normal works in uBO / AdGuard (AdGuard still valid `## body` as `##body`)

### Your environment

* uBlock Origin version: 1.30.0
* Browser Name and version: Firefox 81.0.1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Should be rejected in the the element picker itself.

**Comment by krystian3w** [comment]
so close as invalid
