### ISSUE TITLE
Implement a version of "{{origin}}" that uses the whole URL and not just the domain

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1281]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (1.30.1b5)
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/gorhill/uBlock/wiki/Advanced-settings#autocommentfiltertemplate shows that there are 3 options for which things that are shown in a comment above entries that are made with the element picker: the date, the time, and the site domain. However, Nano Adblocker also had a 4th option called `{{nanoHref}}` that showed the page's URL; and since I've decided to switch to uBlock Origin on my PC, I'm hoping that feature would be ported upstream to uBO under whichever name.

Specifically, for example, if an entry for whatever was created while on `https://www.nrk.no/urix/politisk-kaos-i-kirgisistan-1.15188777`, the proposed function would show:
```
! https://www.nrk.no/urix/politisk-kaos-i-kirgisistan-1.15188777
nrk.no##.example-entry
```
And not:
```
! https://www.nrk.no/
nrk.no##.example-entry
```

This would be of significant importance to (and would make work faster and easier for) people who contribute to lists that mandate source pages for all new entries. *Nano Placeholder Buster* used to be the biggest example, but it would also come in handy for many other lists like EasyList, AdGuard Filters, and just about any other list that require specific URLs in user-submitted issue reports and PRs.

### A specific URL where the issue occurs

`https://www.nrk.no/urix/politisk-kaos-i-kirgisistan-1.15188777`

### Steps to Reproduce

1. Use `{{origin}}` as one of the settings for `autocommentfiltertemplate`
2. Go to any page on almost any website that isn't its frontpage.
3. Create a new entry with the element picker.
4. See that the resulting comment does not show anything after the main domain of the site.

### Expected behavior:

A way to make the auto-comment feature for element-picker entries show the full URL of the page.

### Actual behavior:

There are no ways in uBO (that I know of) to make the auto-comment feature for element-picker entries show the full URL of the page.

### Your environment

* uBlock Origin version: 1.30.1b5 + uBlock Origin Extra 2.88
* Browser Name and version: Chrome 85.0.4183.121 x64
* Operating System and version: Windows 10 May 2020 Update

**Comment by gorhill** [comment]
Trivial to fix for the element picker, but the complication with this feature is that the full URL is not available when creating the filter from the logger.

I tried to create a filter from the logger in Nano using `nanoHref` and the URL in the resulting auto-generated comment was `undefined`.

**Comment by gorhill** [comment]
`{{url}}` is the placeholder to use to receive the full URL of the document for which a filter is being created.

**Comment by gwarser** [comment]
When searching for last comment to append filter to, `lastIndexOf` is used, which means shorter URL can match in longer URL.

Don't know how much this is unexpected. I was confused for a while, because when testing template `{{date}} {{origin}} {{url}}` and adding second filter from the logger (first was from Picker), it looked like `{{url}}` was correctly expanded, but it's not.

**Comment by gorhill** [comment]
What site to use as test case?

**Comment by krystian3w** [comment]
`{{url}}` may have bug with `behind-the-scene` and extension "domain":

I can generate comment:

`! http://behind-the-scene`
`! http://55cb5ae3-9a19-456c-9531-a31688b0f257.moz-extension-scheme`

with use logger to create filters.
