### ISSUE TITLE
uBO v1.30.1b6 Problems with the "Restore from file ..." function in the settings.

### ISSUE THREAD

**Issue by JohnD78** [uBlockOrigin/uBlock-issues#1282]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After commit [f4aebc9](https://github.com/gorhill/uBlock/commit/f4aebc93904ace45675386ec18f04c7ad7b3d922) "Backup / restore only modified advanced settings", function "Restore from File ..." in the settings - does not work if some of advanced settings are modified in the backup file. Such backup file is not loaded.
In this case, error appears in DevTools console for background.html file: Uncaught (in promise) TypeError: Cannot read property 'hiddenSettingsDefault' of undefined
 at restoreUserData (messaging.js:941)
If the backup file does not contain modified advanced settings, everything is fine.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Reset to default settings.
2. Set popupFontSize 12px in advanced settings, back up settings to file.
3. Reset to default settings again, then try to restore backup settings from this file.

### Expected behavior:

The backup must be restored.

### Actual behavior:

The backup is not restored.

### Your environment

* uBlock Origin version: uBO v1.30.1b6
* Browser Name and version: Chrome 85.0.4183.121
* Operating System and version: Win 7x64

**Comment by gorhill** [comment]
Sorry about this, I didn't test the change very well.

**Comment by gorhill** [comment]
Fixed in 1.30.1b7: https://github.com/gorhill/uBlock/releases
