### ISSUE TITLE
Light theme flashes for a second before the page loads in dev build

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#1284]
### Prerequisites

Unless you have set your OS theme set to `dark`, you may not be able to reproduce it.

### Description

As per the title.

### Steps to Reproduce

- On the latest dev build, open Settings pane via the dashboard and set **_Theme_** to **_Dark_**

- Switch to different panes like My rules/My filters/Trusted sites, basically at every new page/pane, Light theme will flash again.

### Expected behavior:

The Light theme which is not set shouldn't flash before the page loads

### Actual behavior:

The Light theme which is not set flashes before the page loads

### Your environment

* uBlock Origin version: 1.40.9b8
* Browser Name and version: Firefox
* Operating System and version: Win 10

**Comment by uBlock-user** [comment]
@gorhill So can this be addressed, now that you brought dark theme out of experimental status ?

**Comment by gorhill** [comment]
Looking into this.

**Comment by uBlock-user** [comment]
> However this works only for
when prefers-color-scheme is properly set by the browser, and only
when uBO's theme selection is "auto", or when it happens to
match that of prefers-color-scheme.

So the opposite effect will still occur when I set the theme to Light with dark flashes ?

**Comment by gorhill** [comment]
If your setting in uBO is opposite of how your browser set `prefers-color-scheme`, there will be a flash, there is nothing which can be done to avoid this. If you use _Auto_, then uBO there should be no flash of background color (except on Linux, this is an open issue in Chromium).

- Browser `prefers-color-scheme: light`, uBO _Auto_ or _Light_, no flash
- Browser `prefers-color-scheme: dark`, uBO _Auto_ or _Dark_, no flash
- Browser `prefers-color-scheme: light`, uBO _Dark_, flash of black
- Browser `prefers-color-scheme: dark`, uBO _Light_, flash of white

**Comment by uBlock-user** [comment]
If you were not use deploy `prefers-color-scheme` would this issue occur ? Exameple only options would be light and dark.

**Comment by gorhill** [comment]
> to deploy `prefers-color-scheme`

uBO does not "deploy", it's a read-only value set by the browser, to give hint about the default background color. If uBO didn't read it, the flash of wrong background can still occur depending on whether uBO's default background color matches that of the browser. You get the same issue:

- Browser paint background white by default: uBO Dark, flash of white
- Browser paint background black by default: uBO Light, flash of black

The core issue is uBO does not know what is the default color used by the browser to paint the background. `prefers-color-scheme` merely helps uBO to make a good guess.
