### ISSUE TITLE
Non-Ad-Related Posts on Facebook Being Hidden

### ISSUE THREAD

**Issue by sebastianbell** [uBlockOrigin/uBlock-issues#129]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using the exact string "Suggested" (no quotes, initial cap) anywhere in the content of any Facebook post (groups, feed, etc.) "removes" the post.

### A specific URL where the issue occurs

https://www.facebook.com/

### Steps to Reproduce

1. Create a Facebook post with the string: Suggested

### Expected behavior:

Being able to view the post.

### Actual behavior:

New post flashes on screen for a moment and is "removed" from DOM.

### Your environment

* uBlock Origin version: 1.16.12
* Browser Name and version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System and version: macOS 10.13.6

**Comment by sebastianbell** [comment]
Not sure how to check if this is a "filter issue" or not.

**Comment by uBlock-user** [comment]
By running the logger 

Cause is this filter - `facebook.com##.userContentWrapper:has-text(/Suggested|Proponowany/)`
