### ISSUE TITLE
BUG in - Prevent WebRTC from leaking local IP addresses

### ISSUE THREAD

**Issue by ballios** [uBlockOrigin/uBlock-issues#1290]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Bad issue appeared!
In uBlock Origin v1.30.2 when "Prevent WebRTC from leaking local IP addresses" is On - WebRTC exposed my public IP address!
And when "Prevent WebRTC from leaking local IP addresses" is OFF - WebRTC not available.
Thus, this uBlock's privace option is working vice versa!
Please fix it!

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: uBlock Origin v1.30.2
* Browser Name and version: Google Chrome 86.0.4240.75
* Operating System and version: Windows 10 (v.2004)

**Comment by gorhill** [comment]
> when "Prevent WebRTC from leaking local IP addresses" is On - WebRTC exposed my public IP address!

Public IP address is not a local IP address: ["Prevent WebRTC from leaking local IP address"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#prevent-webrtc-from-leaking-local-ip-address).

**Comment by timeneverdie** [comment]
> > when "Prevent WebRTC from leaking local IP addresses" is On - WebRTC exposed my public IP address!
> 
> Public IP address is not a local IP address, see ["Prevent WebRTC from leaking local IP address"](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address) (literally the documentation linked to from the dashboard):
> 
> > Keep in mind that this feature is to prevent leakage of your non-internet-facing IP adresses. The purpose of this feature is not to hide your current internet-facing IP address -- so be cautious to not misinterpret the results of the tests above.

Sir, I found the same problem in latest Chrome. The option of uBlock which can prevent public IP address leak before, but now it failed. I don't know if Chrome changes its mechanism, however it works fine before. If the only method is to close webrtc in `chrome://flag`?

**Comment by gorhill** [comment]
@timeneverdie What fails? Please, read carefully the documentation about what the feature does. Claims of failure must be accompanied by actual detailed repro steps if after reading the documentation carefully you actually see the option failing from doing what it's supposed to do. This is an often misunderstood feature, be sure it's not your case. Chrome does **not** have the same setting as Opera, so it appears you ar ejust misunderstanding the setting.

**Comment by timeneverdie** [comment]
> @timeneverdie What fails? Please, read carefully the documentation about what the feature does. Claims of failure must be accompanied by actual detailed repro steps if after reading the documentation carefully you actually see the option failing from doing what it's supposed to do. This is an often misunderstood feature, be sure it's not your case. Chrome does **not** have the same setting as Opera, so it appears you are just misunderstanding the setting.

I have tested webrtc leak by some websites tools. They can find my public IP address even though I use proxy. However, they reported no IP address leak before. So I think uBlock's feature failed.

![image](https://user-images.githubusercontent.com/15784314/97562407-8b18d900-1a1c-11eb-85aa-4c95a43f19d8.png)

I just searched some information and I found above. I think maybe firefox is the only option for security. What do you think?

**Comment by gorhill** [comment]
> They can find my public IP address even though I use proxy

Can they still find your IP address when you _uncheck_ the option in uBO?

**Comment by timeneverdie** [comment]
> > They can find my public IP address even though I use proxy
> 
> Can they still find your IP address when you _uncheck_ the option in uBO?

Yes, still got my real IP address under proxy. (unchecked the option)

**Comment by gorhill** [comment]
Follow <https://github.com/uBlockOrigin/uBlock-issues/issues/1297>, I haven't decided yet but exposing the different WebRTC levels in uBO's user interface is something I am considering.

**Comment by timeneverdie** [comment]
> Follow #1297, I haven't decided yet but exposing the different WebRTC levels in uBO's user interface is something I am considering.

Thanks for your reply.

I have checked the wiki: https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

> For example, if you use a VPN, your internet-facing IP address is that of the VPN, so **your ISP-provided IP address should not be visible to outside world with this setting checked**. However, if you are not behind any VPN or proxy, your ISP-provided IP address will be visible regardless of this setting.

So here is my problem: I have hided my real IP (ISP IP) successfully before(I'm sure, but that was two or three years ago), but now it failed. (under proxy)

I am confused too.

**Comment by gorhill** [comment]
<https://developer.chrome.com/extensions/privacy#type-IPHandlingPolicy>:

> "default", "default_public_and_private_interfaces", "default_public_interface_only", or "disable_non_proxied_udp"

uBO uses `default_public_interface_only` when the option is checked.

Related: <https://bugs.chromium.org/p/chromium/issues/detail?id=874254>.
