### ISSUE TITLE
The DOM inspector fails to re-display hidden elements

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1291]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After I moved my main browser setup to uBlock Origin last week, I began noticing that uBO's DOM inspector fails to re-display hidden elements (Those that are supposed to show up with red marking), which was something that Nano Adblocker succeeded at.

https://github.com/gorhill/uBlock/wiki/DOM-inspector claims that it's still supposed to work.

A fix for this is needed for me to create a better fix for https://github.com/DandelionSprout/adfilt/issues/122.

![image](https://user-images.githubusercontent.com/22780683/95782171-97d4c780-0ccf-11eb-85dc-eb14e62bcda1.png)

### A specific URL where the issue occurs

`https://twitter.com/9_volt_`

### Steps to Reproduce

1. While on a stock uBO setup, add https://raw.githubusercontent.com/DandelionSprout/adfilt/master/TwitterPureReadingExperience.txt as a custom list.
2. Visit `https://twitter.com/9_volt_` on PC while being logged off from Twitter.
3. See that the "Trends for you", "New to Twitter?" and "You might like" boxes are removed, which is fully intentional.
4. Open the uBO logger and click the `</>` button to turn on the uBO DOM inspector.
5. None of the boxes in №3 reappear in any shape or way.

### Expected behavior:

The DOM inspector should redisplay hidden elements, as explained on the wiki page mentioned in this issue report's description; or at least there should be an option toggling whether to redisplay all, none, or all except `:style`-affected elements.

### Actual behavior:

The DOM inspector being turned on, does not redisplay hidden elements.

### Your environment

* uBlock Origin version: 1.30.2
* Browser Name and version: Vivaldi 3.3.2022.47 x64 (Its own adblocker function was turned off)
* Operating System and version: Windows 10 May 2020 Update

**Comment by gorhill** [comment]
Chromium-based browsers are missing the [tabs.removeCSS()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/removeCSS) API, which is required for the DOM inspector -- see <https://github.com/gorhill/uBlock/issues/3588#issuecomment-380812328>.

Reportedly it's being implemented in Canary, and a few days ago I made [a change to use the API in Chromium](https://github.com/gorhill/uBlock/commit/db0d200fcb507a7b06a0845a13ab53099a40ef36) in dev build.

**Comment by gorhill** [comment]
> something that Nano Adblocker succeeded at

It's because Nano Adblocker is still using preudo-user styles, while uBO has been using real user styles for years now. I consider the benefits of using real user styles vastly outweigh the disadvantages. I have [removed completely support for pseudo user styles recently](https://github.com/gorhill/uBlock/commit/5c68867b92735931a791dfedf4ef9608cc364862) as it served only very old versions of Chromium.
