### ISSUE TITLE
improve source & destination sorting in "My rules" settings pane

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uBlock-issues#1293]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When dynamic filters are sorted by source or destination, sorting begins with the TLD and then descends the hierarchy of subdomains. That's logical, but it's not intuitive for me, or for most users, I would guess. A more easily navigable sort order would start just below the public suffix / effective TLD (https://github.com/gorhill/publicsuffixlist.js might be useful here).

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

Install uB0 on a fresh browser profile, add the following dynamic filters, and sort them by source:
* `amazon.com ssl-images-amazon.com * noop`
* `bbc.co.uk bbci.co.uk * noop`
* `nzz.ch static-nzz.ch * noop`
* `twitch.tv twitchcdn.net * noop`
* `wikipedia.org wikimedia.org * noop`

### Expected behavior:

After sorting, I would expect the filters to remain in the order listed above.

### Actual behavior:

The filters appear in this order:
* `nzz.ch static-nzz.ch * noop`
* `amazon.com ssl-images-amazon.com * noop`
* `wikipedia.org wikimedia.org * noop`
* `twitch.tv twitchcdn.net * noop`
* `bbc.co.uk bbci.co.uk * noop`

### Your environment

* uBlock Origin version: 1.30.4
* Browser Name and version: Firefox 81.0.1
* Operating System and version: macOS 10.12.6

**Comment by rodhod** [comment]
could be related to [this issue #1055](https://github.com/uBlockOrigin/uBlock-issues/issues/1055) 

here are the commits that followed
[](https://github.com/gorhill/uBlock/commit/dd655473f6af7919fe5756f18c773d252f90b48e)

[](https://github.com/gorhill/uBlock/commit/d2195b42464b4ec9ba6b785bab5c5c37f35d86a4)
