### ISSUE TITLE
Ublock slows down script from appendChild(scriptNode)

### ISSUE THREAD

**Issue by jektvik-si** [uBlockOrigin/uBlock-issues#1298]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I am attaching a script like so:

```
(document.onload = function() {
		const scriptNode = document.createElement("script");
		scriptNode.src = "/static/js/2.176dfa48.chunk.js"
		document.body.appendChild(scriptNode);
		const scriptNode2 = document.createElement("script");
		scriptNode2.src = "/static/js/main.1429beb6.chunk.js"
		document.body.appendChild(scriptNode2);
	})()
```

then it runs 3x slower, than when I do it like so:
```
<script src="/static/js/2.176dfa48.chunk.js"></script>
<script src="/static/js/main.1429beb6.chunk.js"></script> 
```

### A specific URL where the issue occurs

Tested on localhost with a create-react-app application wired up to do this:
```
const list = new Array(200).fill(0).map((v, i) => i);
{list.map(v => <HighchartsReactGraph key={v} />)}
```
Where HighchartsReactGraph is a chart from the Highcharts library: (https://www.highcharts.com/)

### Steps to Reproduce

1. Prepare an web app like above or other similar setup where you may test rendering coming from a script which is either attached though appendChild(scriptNode) and to compare coming attached to the original Html also inside a <script src=...>

2. You will need some form of time logging to observe the time it takes to load all your content. In the above setup this is done by attaching a console.log() to each render event in the Chart config 
```
events: {
              render: (a) => console.log("rendering", new Date()),
},
```
3. Observe the load times with ublock and without it. 

### Expected behavior:

Ublock should not be slowing the rendering down

### Actual behavior:

With ublock on, the rendering takes 3x longer

### Your environment

* uBlock Origin version: 1.30.4
* Browser Name and version: Chrome : Version 86.0.4240.75 (Official Build) (64-bit)
* Operating System and version: Version	10.0.19041 Build 19041

**Comment by gorhill** [comment]
Provide an actual case with a link which I can load and test, I won't go through "prepare an web app".

You must gather profiling data using the browser's profiler as asked in the issue template, and this profiling data must show that uBO causes undue performance bottleneck.

**Comment by jektvik-si** [comment]
> Provide an actual case with a link which I can load and test, I won't go through "prepare an web app
I don't know how better to do it. Any suggestions ? You need to be able to toggle between two ways of loading a script to observe the performance hit.

> You must gather profiling data using the browser's profiler as asked in the issue template, and this profiling data must show that uBO causes undue performance bottleneck
Would a chrome profiler file do ? (the template isn't too specific about it )

**Comment by gorhill** [comment]
Chrome profiler file is fine, for Firefox there is <https://profiler.firefox.com/> which can be shared through URL.

**Comment by jektvik-si** [comment]
Attaching 3 profiles.
The profiler distorts the time proportions though and it seems like the difference is just a trickle. Without the profiler I'm getting a 2-3x difference factor on render times.

[profiles.zip](https://github.com/uBlockOrigin/uBlock-issues/files/5390866/profiles.zip)

**Comment by gorhill** [comment]
I don't see uBO's code contributing significantly to CPU usage compared to everything else occurring in that profiling data.

Did you try with other extensions? You need to find out whether you get the same results using any extension which inject content script(s), this is something you should do to rule out that whatever you are seeing is uBO-specific or not.

**Comment by jektvik-si** [comment]
Does it make any sense at all that the impeact is different for these 2 different ways of loading the script ?
Asking because I can't think of what other evidence I can add here. 
Also I must have burned a day or two troubleshooting our platform performance before I realized its a plugin issue (comments about testing on incognito first are partially deserved, yet unnecessary; also the failure mode is unusual for plugin related problems)

**Comment by gorhill** [comment]
> Does it make any sense at all that the impact is different for these 2 different ways of loading the script ?

Not from uBO's point of view, it seems to me that the browser for some reasons is behaving differently internally -- hence why I ask whether you see the same behavior with other extensions, especially extensions injecting content scripts. Your profiling data does show that there is anything to fix with uBO specifically. If you confirm the issue exists with other extensions injecting content script, you will have to report the issue to Chromium devs.

**Comment by jektvik-si** [comment]
Yes, that is possible. I think I may have a similar slowdown with scriptsafe. I am reporting it on chromiums bug tracker as well then:
https://bugs.chromium.org/p/chromium/issues/detail?id=1139382

**Comment by gorhill** [comment]
Did you try to see if the issue is also present with Firefox? You could also try with other sort of extensions to find out if this can also be reproduced without a content blocker specifically.

**Comment by jektvik-si** [comment]
I don't think I can provide more troubleshooting here. I've provided a fully reproducible scenario with code and instructions on how to get there and filed it both here and in chromium. I can't afford to burn another day on reinstating the test setup to toggle another extension or two while nobody else cares to investigate.

**Comment by gorhill** [comment]
I see you posted an app in the Chromium bug entry, so I went ahead and investigated with it using the browser's built-in profiler. I commented out your `console.log` code to measure performance, this is not the way to do this with code that execute in less than 50 us, you end up getting warped results.

My finding is that you get the same results just injecting a very minimal extension which instantiates a mutation observer in the content script.

[mutation-observer.zip](https://github.com/uBlockOrigin/uBlock-issues/files/5510626/mutation-observer.zip)

I tried with other blockers and they produce results as uBO, some marginally worst -- without investigating further maybe the number of mutation observers is a factor. uBO uses only one so the results are similar to the minimal extension above. Ghostery's was similar to uBO (~16ms), ABP was higher (~22ms), versus ~8ms without extension.

Mutation observers can be injected by all sort of extensions, depending on their purpose, so what you see is not specific to content blockers.

Note that we are talking about a very tiny increase here -- to keep things in perspective, consider that `appendChild` is reported as ~16 ms versus ~8 ms out of ~2,300 ms of scripting time, so less than half a percent -- so that extra 8 ms should not be where you worry about performance given everything else occurring in the JS code.

In any case, as said above, it seems the mutation observer is what makes the difference, but given added overhead is so insignificant relative to other part of script execution that I doubt the Chromium devs will see this as an issue.

**Comment by jektvik-si** [comment]
Right on good debugging.
I have one comment: the performance slowdown in my real-world use case was much more severe. I.e. I'm rendering an expensive element in a table (in this case 200 rows), and the observed slowdown was 2-3 times with appendChild(). You only need to appendChild() once to observe it. 
Also, the slowdown was proportional to the load. In the attached use case the load is simplified substantially. When testing same on my full platform (where the rendering logic was much heavier) I would get a 10 second load time (with appendChild() ) versus a 3-4 sec load time (with <script>) so the proportions are much less favorable than what you're getting.

**Comment by gorhill** [comment]
Well if you could confirm my finding that this happens with just the bare extension which just inject a very simple mutation observer, then this will be on Chromium devs to decide whether there is something to do about this. uBO can't work properly without a mutation observer, so there is not much I can do on my side -- users are always free to disable uBO for any given site in which case uBO's mutation observer shouldn't be instantiated. But then, uBO is not special with its use of a mutation observer, all sorts of extensions do this.

**Comment by jektvik-si** [comment]
Yes I observed it with a bare browser and only ublock enabled.

**Comment by gorhill** [comment]
I mean with this minimal extension: [mutation-observer.zip](https://github.com/uBlockOrigin/uBlock-issues/files/5510626/mutation-observer.zip). It does nothing else beside instantiating a mutation observer in its content script.

**Comment by jektvik-si** [comment]
Right on. Okay, downloaded your mutation-observer extension and tested several times to start seeing any discrepancies but I am not seeing any. 
The mutation-observer seems to perform consistently the same regardless whether the script is attached through appendChild or through <script>. ~3.5 secs in my case for both

Tested real quick again with full ublock extension installed, and am observing consistent differences again. ~3sec vs ~3.5 sec

Test setup is exactly the same as described in my previous posts except now I'm reporting chrome profiler timing instead of the console.log.

**Comment by gorhill** [comment]
Well, in the end the anomalous result you report is that the profiling timings change according to whether your scripts are injected declaratively or programmatically. There is no reason to expect there should be a difference, the Chromium dev failed to consider this rather and immediately went onto blame the extensions without further trying to explain that quirk. uBO has no say in what the browser do internally when scripts are loaded declaratively or programmatically, so there is nothing I can do here, it's the browser's internals which need to be looked at to explain the difference.

**Comment by gorhill** [comment]
So here are screenshots showing child methods, top is declarative loaded scripts, bottom is programmatically loaded scripts:

![declaratively loaded scripts](https://user-images.githubusercontent.com/585534/98563396-20b43400-2279-11eb-928c-3a8763128bbf.png)

![programmatically loaded scripts](https://user-images.githubusercontent.com/585534/98563376-1b56e980-2279-11eb-9227-842239110862.png)

This should be enough to make the Chromium devs curious as to why there would be a difference -- both appendChild and removeChild are native code and in both cases only the minimal extension above was used.
