### ISSUE TITLE
mumatrix with google

### ISSUE THREAD

**Issue by amoisidis** [uBlockOrigin/uBlock-issues#13]
Hello,

I am trying to use your product in connection with the mumatrix extension.  It does not work with chrome, works wonderfully with firefox.  I am trying to stop this fascist asshole called Zuckerberg with his faceshit.  Are we socializing, or blocking?  I am very frustrated.  Please help.

Best regards
Tony Moisidis

**Comment by uBlock-user** [comment]
For questions - https://www.reddit.com/r/uBlockOrigin/

**Comment by amoisidis** [comment]
Many thanks for your help.  I figured it out.  This Zuckerberg asshole has to go.  We need a democratic free-speech facebook.

 

Tony
