### ISSUE TITLE
Ublock dumps unorganized files in Home directory

### ISSUE THREAD

**Issue by 49studebaker** [uBlockOrigin/uBlock-issues#1300]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock dumps all of its files in the Home directory. Could you put all the Ublock files in a single folder? Why are they not in the Firefox directory

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Ublock files should be in a single folder. The Ublock folder should be in the Firefox directory, unless there is some reason it is placed in the Home directory.

### Actual behavior:

All the Ublock files are dumped in the Home directory.

### Your environment

* uBlock Origin version: v1.30.4
* Browser Name and version: Firefox v81.0.1 32bit
* Operating System and version: Debian 10 32bit

![ublock_home_directory](https://user-images.githubusercontent.com/18037226/96356515-49e80700-10b5-11eb-8103-5823bb9be259.png)

**Comment by gwarser** [comment]
Blame yourself, if uBO was installed from repository - blame uBO packager, blame your distro Firefox packager, your distro maintainers, then come back here.

It's impossible. uBO does not have access to your file system, does not have any way to specify where its files will be installed. On Firefox uBO extension is not even unpacked from xpi file (zip) when installed.

**Comment by 49studebaker** [comment]
I saved the .xpi file from the webpage at the link below. I dragged and dropped the file into the Firefox window. Maybe this is a Firefox bug?


https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser
