### ISSUE TITLE
Elements selected using "has-text()" are visible for a brief moment during page load before being hidden

### ISSUE THREAD

**Issue by dmattera** [uBlockOrigin/uBlock-issues#1302]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Cosmetic filter using ```has-text``` are visible for a brief moment when the page is first loaded before being hidden.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

https://github.com/gorhill/uBlock/wiki

### Steps to Reproduce

1. create the [following example filter](https://i.imgur.com/1hxjBS0.png):  ```github.com##.gh-header-title:has-text(Home)```
2. go to ```https://github.com/gorhill/uBlock/wiki``` 
3. refresh the page as needed in order to witness the issue: https://i.imgur.com/59qw9VX.mp4

### Expected behavior:

The elements selected using a ```has-text``` filter should be hidden immediately upon page load, as with elements selected using other cosmetic filter methods.

### Actual behavior:

These elements are visible for split second after the page is first loaded and then disappear (see video of example above)

### Your environment

* uBlock Origin version:  1.30.4
* Browser Name and version: Firefox 81.0b9 (Developer Edition)
* Operating System and version: MacOS 10.15.7

**Comment by uBlock-user** [comment]
By-design. Procedural cosmetic filters require javascript execution in uBO, so some flashing will occur. This is why only use procedural filters where plain CSS selectors won't work.

**Comment by dmattera** [comment]
Gotcha, thanks for the quick reply and explination. I didn't mention in the post but I've used them for quite a while now and could've swore they didn't do this until just recently. I must've just failed to notice it happening I guess. Closing issue out.

**Comment by gorhill** [comment]
I can't see the Home header disappearing on my side. The result you will have will depend on many factors, such as other filters being applied to a page, extensions injecting content scripts in the DOM, hardware performance. and so on. There is no guarantee procedural filters and even plain CSS-based cosmetic filters[1] will not cause glitch at page load time.

[1] Even the browser won't guarantee glitch-less CSS stylesheets, some people reports FOUC when loading pages.

**Comment by gorhill** [comment]
I can't see the Home header disappearing on my side -- it's removed before the page render the content as far as I can tell (uBO is the only extension enabled). The result you will have will depend on many factors, such as other filters being applied to a page, all other extensions injecting content scripts, hardware performance, and so on. There is no guarantee procedural filters and even plain CSS-based cosmetic filters[1] will not cause glitch at page load time.

[1] Even the browser won't guarantee glitch-less CSS stylesheets, some people report FOUC when loading pages.

**Comment by dmattera** [comment]
> Though I do not see the Home header glitching when opening the page in a new tab, I do see the glitchy rendering when I force a reload of the page.

Thanks for the additional info/explination here gorhill. I was actually just about to add the same comment that it only really appears to happening when doing a refresh of the page, not when it's first loaded: 

https://i.imgur.com/ybU2ytb.mp4

It also doesn't appear to be happening when using the "Reload (override cache)" (Cmd+Shift+R) as opposed to the standard Reload (Cmd+R) so maybe that has something to do with this weird, janky behavior from Firefox here.

**Comment by gorhill** [comment]
> I didn't mention in the post but I've used them for quite a while now and could've swore they didn't do this until just recently.

I'm going to reopen because of this.

In a recent version I changed how soon the user style for procedural operators is injected -- it is indeed injected a bit later now. This is something I've meant to revisit again eventually to bring back the injection to where it was originally. The change was made in order to implement support for `:style()` operator for procedural operators.

**Comment by gorhill** [comment]
Alright, I tested and this makes no difference after all, closing.
