### ISSUE TITLE
Just some design nitpicking

### ISSUE THREAD

**Issue by Vanessa1239** [uBlockOrigin/uBlock-issues#1303]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

looks good mobile and desktop in screen "Einstellungen"
the other screens could be optimized (hoizontal space/padding left) -> see screenshots

actually nothing important -> design shit )

![1](https://user-images.githubusercontent.com/73130393/96488525-6cf1f280-123e-11eb-956b-bfb0c701b4ff.png)

![2](https://user-images.githubusercontent.com/73130393/96488686-a9255300-123e-11eb-8cc9-9a4db7e16256.png)

![3](https://user-images.githubusercontent.com/73130393/96487839-77f85300-123d-11eb-92c0-e299fb699bc5.png)

![4](https://user-images.githubusercontent.com/73130393/96488283-05d43e00-123e-11eb-8dc9-c3d0b236b9a3.png)

![5](https://user-images.githubusercontent.com/73130393/96489409-b42cb300-123f-11eb-81be-5dd708bf1d1d.png)

**Comment by Vanessa1239** [comment]
![6](https://user-images.githubusercontent.com/73130393/96489977-7bd9a480-1240-11eb-95d3-9d4ca240dbf8.png)
![7](https://user-images.githubusercontent.com/73130393/96490032-8eec7480-1240-11eb-9077-8b63693f7923.png)

**Comment by gwarser** [comment]
![3](https://user-images.githubusercontent.com/73130393/96487839-77f85300-123d-11eb-92c0-e299fb699bc5.png)

These are scrollable - blame Firefox design.

![5](https://user-images.githubusercontent.com/73130393/96489409-b42cb300-123f-11eb-81be-5dd708bf1d1d.png)

Clipping the search field and "only changes" button on the right edge?

**Comment by hawkeye116477** [comment]
Yeah, for mobile, bottom menu like this would be better.
<img src="https://materializecss.com/images/menu.gif" width="200px">
