### ISSUE TITLE
uBlock Origin causes Firefox to lose logged in sessions for various websites

### ISSUE THREAD

**Issue by glenbarney** [uBlockOrigin/uBlock-issues#1305]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [ X] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox 80-82 routinely log me out of saved website sessions with uBlock Origin installed.

### A specific URL where the issue occurs

`https://www.google.com/`

### Steps to Reproduce

1. Fresh Load Firefox, latest version
2. Fresh Load uBlock Origin, through addons
3. Log into Instagram, choose to save login session
4. Log into Amazon, choose to save login session
5. Log into Google, which always saves your login session.
6. Operate normally.
7. Shut down computer, go to sleep.
8. Come back 1-2 days later.

### Expected behavior:

Expect that I would be able to open Instagram, Amazon, Google, and have my login sessions retained.

### Actual behavior:

Discover that I've been logged out of all of these websites.

This behavior occurred consistently over the past several weeks.  No Firefox or uBO settings were changed when this behavior started occurring.  A full reset of Firefox, and an uninstall/reinstall did not resolve the issue.  Only uninstalling uBO in favor of any other ad blocker resolves the issue.

### Your environment

* uBlock Origin version: 1.30.4
* Browser Name and version:  Firefox 81.0.2
* Operating System and version:  Windows 10 1909

**Comment by gorhill** [comment]
> other ad blocker resolves the issue

Did you configure them in a similar way as uBO default configuration? Notably, did you enable EasyPrivacy? Did you try to un-select filter lists not used by other blockers? uBO acts based on filter list content, so to me so far it seems as a filter issue unless other blockers configured with the exact same filter lists are not suffering the issue.

**Comment by glenbarney** [comment]
On Thu, Oct 22, 2020 at 3:04 AM Raymond Hill <notifications@github.com>
wrote:
> Did you configure them in a similar way as uBO default configuration?

No changes were made to any of ABP or Ghostery when I installed them - nor
were any changes made to uBO.  Each was just installed using the Firefox
addon system, and not otherwise changed.

> Notably, did you enable EasyPrivacy? Did you try to un-select filter
lists not used by other blockers?

No and no.... as such things would not be obvious to a user with these
issues to begin with.  I'd assume the expectation is that an add-on should
work "out of the box" in default configuration without the need to adjust
settings in order to prevent unwanted behavior.

> uBO acts based on filter list content,

The actions are not occurring immediately.  Typically it takes 1-2 days for
the behavior to manifest.  I'll open Firefox with uBO active, I'll log into
my websites.  I'll frequently close my browser throughout the day (full
quit) and reopen it, and still be logged in.  Even the next day, for a
while, I might be logged in.  Then, at some point, after many hours and
many launches of Firefox, I will suddenly be logged out again.

And the logouts don't all happen at the same time.  I might get logged out
of Amazon, but still be in Instagram.   Then, the next day, I'm suddenly
out of IG, but still in Amazon, but out of Google.

Other programs (for example my in-house applications which just push a
session token in a cookie to my browser) *never* get logged out - my
in-house applications stay logged in for weeks or more without ever
exhibiting this behavior, even while Google and IG and Amazon get logged
out at random.

> so to me so far it seems as a filter issue unless other blockers
configured with the exact same filter lists are not suffering the issue.

It may well be, and I'm happy to try tests if you want to give me specific
directions; right now, I'm using Ghostery because the logouts have become
painful.

As an aside, I'm starting to see other people reporting this online:
https://www.reddit.com/r/uBlockOrigin/comments/ia3n0j/ublock_origin_is_logging_out_sites/
etc.

Thanks.

**Comment by ImperatorStorm** [comment]
This is a firefox issue, not a ublockorigin issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1672394

**Comment by gorhill** [comment]
I will note OP said it didn't happen with other content blockers.

**Comment by glenbarney** [comment]
OP here.  It does not happen with other content blockers, and I dispute that this is a Firefox issue.  I have now been running Ghostery instead of uBO and have not been logged out of any websites since.  This only happens with uBO, and other people are reporting it, so I think you're doing yourselves a disservice by trying to lay this back on Firefox.

**Comment by uBlock-user** [comment]
> so I think you're doing yourselves a disservice by trying to lay this back on Firefox.

I haven't been able to reproduce this ever and I'm logged to google and some other sites for months. So you can't objectively say that it's a uBO issue either as it's not reproducable at will neither it's occurring to everyone.

**Comment by glenbarney** [comment]
> This is a firefox issue, not a ublockorigin issue
> https://bugzilla.mozilla.org/show_bug.cgi?id=1672394

That issue is different, and not related to this issue.  That issue is a problem with  "Clear history when Firefox closes" being activated, and Firefox incorrectly processing that option.

The problem I am reporting happens even when Firefox is set to fresh-loaded defaults,  keeping all history, and not clearing anything.  

> you can't objectively say that it's a uBO issue either as it's not reproducable at will neither it's occurring to everyone.

Yes, but you can't objectively say that it isn't.  Look, you guys are the authors here.  If you don't want to deal with it, that's fine, but just arbitrarily closing the issue without even trying sends the message that you all don't care about this.

> Something in uBO could be triggering the issue that causes Firefox to log you out, that's a possibility.

Exactly  my point.  Which would make it a uBO problem.  

You guys clearly don't want to deal with this, and you've made that clear by closing this issue.  But if this is a uBO issue - as it seems to be - then you're going to lose more and more people to competing products - because this *IS* a pain-causing problem, and as people discover it's limited to uBO, word will spread that it's being ignored, and people will just go elsewhere.

I'll just stay with Ghostery and refer others who encounter this too, since that seems to be the tone here.

I wish you all well.

**Comment by uBlock-user** [comment]
> Exactly my point. Which would make it a uBO problem.

That still makes a Firefox issue, not a uBO issue. uBO doesn't handle cookies in any manner which is the primary way you get logged out of a session.

**Comment by uBlock-user** [comment]
> That issue is different, and not related to this issue. That issue is a problem with "Clear history when Firefox closes" being activated, and Firefox incorrectly processing that option.

I thought you opened that issue, but if you didn't, I will re-open that issue then. Note that unless this issue becomes reproducable, the issue won't get addressed.

**Comment by Re4mstr** [comment]
I started having this issue as well.

I've set up two identical setups, one without uBO, the other with defaults.

Happens only on facebook/google with me as far as I have experienced so far.

**Comment by uBlock-user** [comment]
@Re4mstr try setting `privacy.purge_trackers.enabled` to `false` in `about:config` report back if you see any changes.

**Comment by gorhill** [comment]
uBO does not touch cookies, hence why my best guess at this point is that it's a filter issues. The fact that many distinct unrelated sites are affect is puzzling, so this would mean a generic filter is involved. It helps to not skimp on details. Where the logged out accounts devoid of activities during a long period and until the log out occurred? How long before the log out occurs?

The Firefox bug above is currently the best explanation, and whoever suffer the issue should be willing to try the documented workaround to rule out for sure this is not the cause.

**Comment by gorhill** [comment]
I started a Firefox session just for the sake of testing whether it will log off or not. I logged into Google and I will leave the browser idle from now on. I opened uBO's logger and configured it to keep all logged requests for 30 hours (the default is 6 hours). At this point I can see Google home page (which I leave opened) firing a network request every 30 minutes, `https://play.google.com/log?format=json&hasfast=true`, but this is not blocked when using the default filter lists. I will report tomorrow whether I am being logged off.

**Comment by gwarser** [comment]
I don't thing this happens with browser opened:

> 7. Shut down computer, go to sleep.

**Comment by r-a-y** [comment]
Doesn't seem to be a uBO issue. Lots of reports on Reddit about getting logged out on the Firefox subreddit.

One example: https://old.reddit.com/r/firefox/comments/jbrijr/firefox_consistently_logging_me_out_of_logged_in/

**Comment by gorhill** [comment]
I've not been able to reproduce no matter what, so I will close as unreproducible. If ever other users can reproduce exactly as OP (lose history with uBO specifically) then we will re-open. As already stated, the claim is extraordinary since uBO does not touch cookies and a filter issue is unlikely since distinct websites are involved. Whoever can reproduce is best placed to investigate, this issue will never get resolved if only one user can reproduce.
