### ISSUE TITLE
Filter lists > Import > URL needs File Path

### ISSUE THREAD

**Issue by sjhgvr** [uBlockOrigin/uBlock-issues#1306]
### Prerequisites

- [✔ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✔] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [✔] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [✔] uBlock Origin is the only extension
    - [✔] uBlock Origin with default lists/settings
    - [✔] using a new, unmodified browser profile
- [✔] I am running the latest version of uBlock Origin
- [✔] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Not able to add filterlist: https://abp.oisd.nl

### Steps to Reproduce

1. Open uBlock Origin Dashboard
2. Go to Filter Lists
3. At the bottom where it says Custom; check Import
4. Add the following: "https://abp.oisd.nl"
5. You now can not press the "Apply Changes" button because it remains greyed out.

### Expected behavior:

As https://abp.oisd.nl is a **valid** URL, and it actually **does** work when using [this workaround](https://www.reddit.com/r/uBlockOrigin/comments/jf576q/adding_oisd_domain_blocklist_to_ubo/g9o222x/?utm_source=reddit&utm_medium=web2x&context=3) ...
The "Apply Changes" button should become active after adding: https://abp.oisd.nl to Custom > Import

### Actual behavior:

The "Apply Changes" button doesn't become active after adding: https://abp.oisd.nl to Custom > Import

### Your environment

* uBlock Origin version: v1.30.6
* Browser Name and version: Firefox 82.0 (64-bit)
* Operating System and version: Microsoft Windows [Version 10.0.19041.572]

**Comment by uBlock-user** [comment]
Use `https://abp.oisd.nl/` to import the url.

**Comment by sjhgvr** [comment]
> 
> 
> Use `https://abp.oisd.nl/` to import the url.

Does this mean 'https://abp.oisd.nl' (without the ending slash) still doesn't work?
If so, didn't that just change the problem instead of fixing it?

**Comment by gorhill** [comment]
The trailing slash is required. When you paste `https://abp.oisd.nl` in the address bar, both Chromium and Firefox uses `https://abp.oisd.nl/` as the effective URL. Copy from the address bar and paste the URL elsewhere to see this.

**Comment by sjhgvr** [comment]
> 
> 
> The trailing slash is required. When you paste `https://abp.oisd.nl` in the address bar, both Chromium and Firefox uses `https://abp.oisd.nl/` as the effective URL. Copy from the address bar and paste the URL elsewhere to see this.

Makes sense. Thanks :)

**Comment by uBlock-user** [comment]
Path is always required.

**Comment by sjhgvr** [comment]
> 
> 
> The trailing slash is required. When you paste `https://abp.oisd.nl` in the address bar, both Chromium and Firefox uses `https://abp.oisd.nl/` as the effective URL. Copy from the address bar and paste the URL elsewhere to see this.

Makes sense, but if the URL without the trailing slash is pasted in the address bar or either of those browsers, it's automatically corrected by adding the trailing slash. I'd personally see it act the same, but that might just be me.

Thanks in any case :)

**Comment by gorhill** [comment]
Right, the issue was that uBO was mistakenly requiring at least two characters for the path, while it should have required a at least one, the unavoidable `/`.
