### ISSUE TITLE
Quick Rule editor is not working

### ISSUE THREAD

**Issue by byzod** [uBlockOrigin/uBlock-issues#1307]
Like this

![A1](https://user-images.githubusercontent.com/848607/97068383-996c8c80-15f9-11eb-9088-0c6e7566d54b.gif)

* uBlock Origin version: uBlock Origin v1.30.6
* Browser Name and version: Firefox 83.0b3 Developer Edition 
* Operating System and version: Windows 10 1703

**Comment by llacb47** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#i-am-an-advanced-user
