### ISSUE TITLE
non-specific procedural filters

### ISSUE THREAD

**Issue by eliz82** [uBlockOrigin/uBlock-issues#131]
### Description

I'm trying to make a rule that block cookie/gdpr agreement messages that have "infected" all the european sites. I have found some dedicated lists, but they are working on ~half of the sites.

So I have tried to make more smarter rules that actually search in the properties and content of the DOM elements:

`site.eu##body > *:matches-css(position: fixed):has-text(/cookie/i)`

The rule works in my tests, however the problem is that are hundreds of thousands of sites where this kind of rule should be applied.
So i have tried this kind of rule:
`##body > *:matches-css(position: fixed):has-text(/cookie/i)`

That do not work and it's normal, the docs here https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters clearly say only specific procedural filters will work. This make my task impossible.

Could you add some option in your advanced menu (advanced-settings.html) that could **enable non-specific procedural cosmetic filters** for advanced users?

### Your environment

* uBlock Origin version: 1.16.12
* Browser Name and version: Firefox
* Operating System and version: Windows 7

**Comment by uBlock-user** [comment]
It wasn't added purposefully in the first place, so I doubt it would now.

**Comment by gorhill** [comment]
I could add an advanced setting allowing this, which would be disabled by default so that filter list authors are prevented to use such syntax.

**Comment by luxoflux** [comment]
^ Yes, please.
