### ISSUE TITLE
uBlockOrigin with Firefox on Linux loses all configuration every 24 hours or so

### ISSUE THREAD

**Issue by qazwsxedcgit** [uBlockOrigin/uBlock-issues#1312]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Any configuration made in uBlockOrigin after installation (e.g. Filter lists settings and updates, custom entries in "My Filters" or in "My rules") persists only for less than 24 hours. It does persist over restarts of Firefox or reboots of entire machines for less than 24 hours. This leads me to believe that a scheduled update process causes the deletions.

### A specific URL where the issue occurs

Not applicable.

### Steps to Reproduce

1. Install uBlockOrigin v1.30.6
2. Add some entries to My filters, update filter lists, then disable auto-update of filter lists, tick "I am an advanced user" and add some site-specific rules into "My rules".
3. Back up resulting uBlockOrigin configuration. 
4. Use browser and uBlockOrigin normally for a day or so.
5. Next morning, find that all uBlockOrigin configuration is lost, i.e. all configuration options are set to defaults, and the "blocked since install" counter is reset to zero. Restoring the configuration from backup works, but it will again only persist for less than 24 hours.

### Expected behavior:

uBlockOrigin does not lose its configuration.
On the same machines on which this problem now persists, earlier versions of uBlockOrigin which stored their config in ~/.mozilla/firefox/[profile.name]/browser-extension-data and below worked just fine.
Installation into a clean browser profile makes no difference.

### Actual behavior:

uBlockOrigin does lose its configuration as described above.

### Your environment

* uBlock Origin version: v1.30.6
* Browser Name and version: Firefox 78.4.0esr
* Operating System and version: Debian 9 (Stretch) 64-bit, Mate desktop 1.16.2

**Comment by uBlock-user** [comment]
Navigate to https://firefox-storage-test.glitch.me/ and copy-paste the results here.

**Comment by gorhill** [comment]
uBO uses a browser API to persist its settings. If you keep losing them, then something on your computer is messing with the browser storage -- this is not uBO doing this.

**Comment by qazwsxedcgit** [comment]
Below are two outputs from two consecutive visits to https://firefox-storage-test.glitch.me/
@uBlock-user What does that tell us?
==========================================================
Overview:
Storage is working. This is your first visit or all storage was automatically cleared.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

Debug Info:

{
  "v": 1,
  "curVersion": 78,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 78
  },
  "idb": {
    "persistentCreatedIn": 78,
    "persistentLastOpenedIn": 78,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 78,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 78
  }
}

========================================================

Overview:
Storage is working. This is the same version (78) as the last time you loaded this page.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

Debug Info:

{
  "v": 1,
  "curVersion": 78,
  "prevVersion": 78,
  "ls": {},
  "qm": {
    "lastWorkedIn": 78
  },
  "idb": {
    "persistentCreatedIn": 0,
    "persistentLastOpenedIn": 78,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 0,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 78
  }
}

**Comment by gorhill** [comment]
@qazwsxedcgit You will have to investigate on your side what is causing your settings to be lost -- and as a starting point you should also see if this happens with other extensions.

**Comment by uBlock-user** [comment]
Seems your storage is working and not corrupted which could have been the cause of this.

**Comment by qazwsxedcgit** [comment]
@gorhill Other extensions didn't have that problem, but it did turn out that overzealous housekeeping (cron job to purge DOM storage) caused the uBlockOrigin settings (stored in DOM storage) to become lost. The zeal has been addressed. Apologies for crying wolf.
