### ISSUE TITLE
Request blocking selection is missing the allow button

### ISSUE THREAD

**Issue by bendem** [uBlockOrigin/uBlock-issues#1313]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The Popup UI used to allow disabling request filtering for a domain but that button has been disabled. It's still there and it can still be shown again if you edit the css manually as shown below.

![image](https://user-images.githubusercontent.com/2681677/97686010-7cbcd280-1a99-11eb-88ac-655ee5d75963.png)
![image](https://user-images.githubusercontent.com/2681677/97686999-c1486e00-1a99-11eb-9cac-4a30ca8eaf63.png)

### A specific URL where the issue occurs

It doesn't matter, just try github.com

### Steps to Reproduce

1. Open the popup
2. hover over any filter control

### Expected behavior:

allow, ignore other rules, deny should be available

### Actual behavior:

Only the last two buttons are available

### Your environment

* uBlock Origin version: how do I know?
* Browser Name and version: edge, chrome, firefox, all latest
* Operating System and version: windows and fedora

**Comment by bendem** [comment]
I see, digging into the code that an option was added to restore the old behavior, but I can't say I see where it's supposed to be

https://github.com/gorhill/uBlock/commit/162e53727099ccb0a088cc1399915fb23d9b4fec

**Comment by bendem** [comment]
OK, I see from the comment I can double tap ctrl to bring it back. Wish that information was more prominently shown.

**Comment by uBlock-user** [comment]
All explained in https://github.com/gorhill/uBlock/releases/tag/1.28.0, but nobody reads and this keeps happening.

**Comment by gorhill** [comment]
> - [x] I checked the documentation to understand that the issue I report is not a normal behavior

It's also explained in the documentation: <https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-quick-guide#allow-rules>.

**Comment by bendem** [comment]
> All explained in https://github.com/gorhill/uBlock/releases/tag/1.28.0, but nobody reads and this keeps happening.

I read release notes when I get an update prompt or notification, I go out of my way to check package changelogs for the distros that provide them, but I have no way of knowing when or if an extension has been updated. I blame browsers for that.

> It's also explained in the documentation: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-quick-guide#allow-rules.

I guess it's there indeed. I agree I didn't go through the 121 pages. I couldn't search for something I didn't know the name of so I skimmed through rapidly.

I hope others with the same problem will find this issue and be able to solve their problem with the information given. Thanks for linking to the relevant information.

**Comment by gorhill** [comment]
> I hope others with the same problem will find this issue

There were already issues to be found, <https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+allow+button+is%3Aclosed>:

- https://github.com/uBlockOrigin/uBlock-issues/issues/1286
- https://github.com/uBlockOrigin/uBlock-issues/issues/1160

All duplicates of #1153.
