### ISSUE TITLE
Application filters

### ISSUE THREAD

**Issue by SoniEx2** [uBlockOrigin/uBlock-issues#1315]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There should be a way to detect and block tracking based on application (e.g. Mastodon, Moodle, Gitlab, etc) in addition to websites. Many of those are self-hosted and having to get them on a list is a pain. Blocks for an application should apply to *all* instances of said application, automatically.

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 81.0
* Operating System and version: Arch Linux x86_64

**Comment by gorhill** [comment]
You issue is too vague, please open a detailed issue of what is _"tracking based on application"_ at uAssets -- don't just throw _"tracking based on application" in an issue and ask other people to do the leg works of figuring what _exactly_ you are referring to.

**Comment by SoniEx2** [comment]
"tracking, based on application" rather.

**Comment by uBlock-user** [comment]
> "tracking, based on application" rather.

uBO is a browser extension, its ability is limited to the web, anything beyond that is outside of the scope of browser extensions.

**Comment by gorhill** [comment]
There is no point providing feedback on such a vague description of what is the issue, we just don't know what is the exact issue along with reproducible steps -- it's just going to be an endless back and forth.

Good contributions are those with efforts to make a case, and when it comes to feature requests, many reproducible cases must be provided and discussed.

**Comment by SoniEx2** [comment]
those are all web-based applications. have you never heard of Mastodon or Gitlab?
