### ISSUE TITLE
I can´t block gray cookiepictures

### ISSUE THREAD

**Issue by ersteinmal** [uBlockOrigin/uBlock-issues#1316]
Dear All.
I use hopefully the newest yblock version, wicht W10 and Vivaldi.

My problem is the cosmetic filter es shown in the picture. I am only able to klick "vorschau" (sorry I am in Germany). But I can´t finish with "erzeugen" maybee proceed in english.
![Zwischenablage01](https://user-images.githubusercontent.com/24368213/97775808-d38ede80-1b63-11eb-820e-c8c029db341c.jpg)
Thanks for help

Regards Carsten

**Comment by uBlock-user** [comment]
Put back the template and fill it in completely.

**Comment by ersteinmal** [comment]
Thanks for answering, but I did not really unterstand it.
By trying to understand the "template". I used the 
![Zwischenablage02](https://user-images.githubusercontent.com/24368213/97777167-a562cc00-1b6e-11eb-8351-1e9e5ef6a735.jpg) flash. And that worked immediately. So my problem is solved.

Es there a way to explain my mistake argein?

Regards
Carsten

**Comment by uBlock-user** [comment]
You had cosmetic filtering disabled, so you weren't able to block the pictures, enabling it back made it possible ?

**Comment by gorhill** [comment]
Don't use feature you do not understand: you [disabled cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) then you are reporting an issue that cosmetic filtering isn't working while it's you who disabled it.

**Comment by ersteinmal** [comment]
> Don't use feature you do not understand: 
Your so right 
You mean this one
![Zwischenablage03](https://user-images.githubusercontent.com/24368213/97796730-08f40480-1c16-11eb-8403-72191221c9ce.jpg)
Billboards might be helpful as I go with the Mouse on it. But never mind -

I tryed it, but I have the same Problem: I am able to make a Right klick bit a Klick on "ublock Blocking" will do nothing. 
![Zwischenablage04](https://user-images.githubusercontent.com/24368213/97796817-fdeda400-1c16-11eb-8ace-007cf36128a9.jpg)

Sorry for my bad questions.

REgards 
Carsten

**Comment by gorhill** [comment]
If you think there is an issue with uBO and you confirm it's not caused by your custom settings/filters, you need to fill the template and provide detailed repro steps. I tried with default settings and all works fine on my side:

![a](https://user-images.githubusercontent.com/585534/97801014-a7c53480-1c07-11eb-995e-7ee2ad008c63.png)

**Comment by ersteinmal** [comment]
Unbeleevable your right!!!!!
I still find the "reset" button in ublock. and it works.

I down´t know how I changed anything. 

So I will say: Thankyou for all

Carsten
