### ISSUE TITLE
Please change the dashboard icon to a gear. It'll then be easier to distinguish it from the logger icon.

### ISSUE THREAD

**Issue by unforgettableid** [uBlockOrigin/uBlock-issues#1319]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [n/a] uBlock Origin is the only extension
    - [n/a] uBlock Origin with default lists/settings
    - [n/a] using a new, unmodified browser profile
- [n/a] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

At the bottom of the [pop-up user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), there are some icons. One opens the logger, and one opens the dashboard.

Unfortunately, the two icons are rather similar.  They're both black-and-white icons full of horizontal lines.  It's not so easy for me to remember which icon is which.  I've sometimes ended up having to check the tooltips in order to remind myself what each of the two icons means.

It would be good if you could please change the "Open the dashboard" icon to something more distinctive.  Perhaps a gear icon, similar to what Android uses as its "Settings" icon.

Thank you for reading this!

### My environment

uBO 1.30.4 on Chromium on Xubuntu.

### Related issue

A related issue is [#1320](https://github.com/uBlockOrigin/uBlock-issues/issues/1320): "Please provide always-visible text labels for the four icons at the bottom of the pop-up user interface".

**Comment by j-james** [comment]
I support changing this - regularly, I open the dashboard when I meant to open the logger. 

A gear to represent the dashboard is also typical of many other extensions, like [ViolentMonkey.](https://github.com/violentmonkey/violentmonkey/blob/master/src/resources/svg/cog.svg)

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/99842890-e861ff00-2b70-11eb-80f9-c44c0f69689f.png)

**Comment by Altsinn** [comment]
Hi @gorhill, would it be possible to update the dashboard icon also for the classic UI flavor?

**Comment by gorhill** [comment]
The classic UI will disappear, no point for me to spend time on this.
