### ISSUE TITLE
opening uBlock menu on Firefox android breaches private browsing

### ISSUE THREAD

**Issue by profblablabla** [uBlockOrigin/uBlock-issues#132]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When opening the uBlock origin menu from a private tab on firefox mobile the menu will open in a non-private tab, which if the history is enabled (it's default on) generates an entry in the history. The entry includes the title of the website from where the uBlock menu was opened. This breaches private browsing which goal it is to not generate any traces after the tabs are closed.

### A specific URL where the issue occurs

amazon.com

### Steps to Reproduce

1. open a new private tab on firefox android
2. open any website eg. amazon.com
3. open the uBlock menu eg. by pressing the three dots in the top right corner, scrolling down to the item in the list called "uBlock Origin(4)" (the intention might be to disable or enable uBlock for this website)
4. the most recent item in the history is now "uBlock Origin - Amazon.com Online Shopping [...]"

### Expected behavior:

opening the menu in a private tab as well

### Your environment

* uBlock Origin version:
* Browser Name and version: firefox 61.0 installed from google play store confirmed with firefox nightly 63.0a1
* Operating System and version: Android 8.0.0

**Comment by gorhill** [comment]
uBO never adds the title of the current page to its popup menu, there is no code in uBO to do that (there is also no code in uBO that access the `history` API -- it's not part of its required permissions).

The browser is doing this, please bring this to Firefox devs.

**Comment by profblablabla** [comment]
>The browser is doing this, please bring this to Firefox devs.

saw you already did, thanks
