### ISSUE TITLE
Please provide always-visible text labels for the four icons at the bottom of the pop-up user interface

### ISSUE THREAD

**Issue by unforgettableid** [uBlockOrigin/uBlock-issues#1320]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [n/a] uBlock Origin is the only extension
    - [n/a] uBlock Origin with default lists/settings
    - [n/a] using a new, unmodified browser profile
- [n/a] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Background

At the bottom of the [pop-up user interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface), there are some icons. One opens the logger, and one opens the dashboard.

Unfortunately, the logger and dashboard icons are rather similar.  They're both black-and-white icons full of horizontal lines.  It's not so easy for me to remember which icon is which.  I've sometimes ended up having to check the tooltips in order to remind myself what each of the two icons means.

### Expert advice

[This source](https://ux.stackexchange.com/questions/1795/when-to-use-icons-vs-icons-with-text-vs-just-text-links), quoting the Neilson/Norman group's UI advice, states:

"**Icons Need a Text Label**

"To help overcome the ambiguity that almost all icons face, a text label must be present alongside an icon to clarify its meaning in that particular context. ...

"**Icon labels should be visible at all times**, without any interaction from the user. For navigation icons, labels are particularly critical. **Don’t rely on hover** to reveal text labels: not only does it increase the interaction cost, but it also **fails to translate well on touch devices**."

(Emphasis mine.)

### My suggestion

It would be good if you could please add some always-visible legend text telling us what each icon does.

*  Below the zapper icon, you could show the word "Zapper".
*  Below the picker icon, you could show the word "Picker".
*  Below the logger icon, you could show the word "Logger".
*  Below the dashboard icon, you could show either the word "Dashboard".

These words would take up space.  However, computer screens are big enough, so we have lots of space.

Thank you for reading this!

### My environment

uBO 1.30.4 on Chromium on Xubuntu.

### Related issue

A related issue is [#1319](https://github.com/uBlockOrigin/uBlock-issues/issues/1319): "Please change the dashboard icon to a gear. It'll then be easier to distinguish it from the logger icon."

**Comment by gwarser** [comment]
Open [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) and set `uiPopupConfig` to `+captions`.

**Comment by gorhill** [comment]
Declined, I don't want to change the UI from what it is now. Additionally, any requests of changing the must take into account all the millions of users already familiar with the current state and who would not be happy with those changes.

**Comment by unforgettableid** [comment]
> Additionally, any request to change the UI must take into account all the millions of users already familiar with the current state and who would not be happy with those changes.

This is an interesting point that I didn't think about.  Users often dislike change.  (See [this source](https://uxdesign.cc/we-dont-hate-change-we-hate-changing-513a9db3f03c).)

Perhaps it might help to do this:

1.  Add a new option to the dashboard, called "Show text labels on user-interface icons".
1.  For upgraders, disable this option by default.
1.  For new users, enable this option by default.

If an upgrader wants text labels, they can check the box.

If a new user dislikes text labels, they can uncheck the box.

But, if they leave the checkbox alone, upgraders will never see text labels, ever.  They can keep on upgrading for decades and remain blissfully unbothered by the presence of even one single text label.  :)

**Comment by unforgettableid** [comment]
(When the box is checked, it will simply set `uiPopupConfig` to `+captions`.)
