### ISSUE TITLE
uBlock blocks less on Youtube when Firefox is launched in private mode by default. It says only around 2-3 % are blocked.

### ISSUE THREAD

**Issue by sandsero** [uBlockOrigin/uBlock-issues#1321]
However, uBlock blocks everything if you open a private window and Firefox does not start in private mode by default.

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock stops working on Youtube when the Firefox is launched in private mode. It says only around 2-3 % are blocked.

Added Settings

	https://github.com/RPiList/specials/blob/master/Blocklisten/Corona-Blocklist?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/Fake-Science?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/Phishing-Angriffe?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/crypto?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/easylist?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/gambling?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/malware?raw=true
	https://github.com/RPiList/specials/blob/master/Blocklisten/notserious?raw=true
	https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails
	https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt
	https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
	
	||localhost^$important,third-party
	||127.*^$important,third-party
	||[::1]^$important,third-party
	||192.168.*^$important,third-party
	||169.254.*^$important,third-party
	||[fe80::*]^$important,third-party
	||[fc*]^$important,third-party
	||[fd*]^$important,third-party
	||*.local^$important,third-party
	||fritz.box^$important,third-party
	||fritz.nas^$important,third-party
	||*.fritz.box^$important,third-party
	||speedport.ip^$important,third-party
	||connect.box^$important,third-party
	||easy.box^$important,third-party
	||giga.cube^$important,third-party
	
	no-csp-reports: * true
	no-large-media: behind-the-scene false
	no-remote-fonts: * true
	behind-the-scene * * noop
	behind-the-scene * 1p-script noop
	behind-the-scene * 3p noop
	behind-the-scene * 3p-frame noop
	behind-the-scene * 3p-script noop
	behind-the-scene * image noop
	behind-the-scene * inline-script noop

### A specific URL where the issue occurs
youtube.com

### Steps to Reproduce

1. Start Firefox with a new profile. Add uBlock and modify the settings using the given information above.
2. Youtube will work without showing adds.
3. Enable Firefox Private Mode under preferences.
4. Youtube will show adds.

### Expected behavior:

4. Youtube does not show any adds.

### Your environment

* uBlock Origin version:1.30.6
* Browser Name and version:82.0.2 (64-Bit)
* Operating System and version:Fedora Silverblue

**Comment by gwarser** [comment]
> [ ] uBlock Origin with default lists/settings

Export your setting on the bottom of Settings tab and reset to default, then try again.

**Comment by gwarser** [comment]
Did you allowed uBO to work in private windows?

**Comment by gwarser** [comment]
I tried your settings (uBO allowed in private windows) and unable to reproduce.

**Comment by sandsero** [comment]
![Bildschirmfoto von 2020-11-02 16-59-20](https://user-images.githubusercontent.com/73837912/97891165-ba865900-1d2e-11eb-8418-b19deb91ef53.png)
![Bildschirmfoto von 2020-11-02 17-00-19](https://user-images.githubusercontent.com/73837912/97891171-bc501c80-1d2e-11eb-8dfb-7006928506d4.png)
![Bildschirmfoto von 2020-11-02 17-05-06](https://user-images.githubusercontent.com/73837912/97891181-beb27680-1d2e-11eb-8442-273526aac49e.png)
![Bildschirmfoto von 2020-11-02 17-06-01](https://user-images.githubusercontent.com/73837912/97891184-bf4b0d00-1d2e-11eb-9826-6b348fe52427.png)
![Bildschirmfoto von 2020-11-02 17-06-24](https://user-images.githubusercontent.com/73837912/97891192-c114d080-1d2e-11eb-8bd2-f286fad87151.png)
![Bildschirmfoto von 2020-11-02 17-06-48](https://user-images.githubusercontent.com/73837912/97891193-c1ad6700-1d2e-11eb-9e9f-687865174df2.png)
![Bildschirmfoto von 2020-11-02 17-10-26](https://user-images.githubusercontent.com/73837912/97891197-c40fc100-1d2e-11eb-9458-e7be41d2c25f.png)


In the by default privat mode blocking is somewhat unreliable/broken with added filters.

**Comment by uBlock-user** [comment]
> Did you allowed uBO to work in private windows?

Did you ?

To verify, about:addons => Extension => uBlock Origin => Run in Private Windows, **Allow** should be have selected.

**Comment by uBlock-user** [comment]
> Did you allowed uBO to work in private windows?

Did you ?

To verify, about:addons => Extension => uBlock Origin => Run in Private Windows, **Allow** should have been selected.

**Comment by sandsero** [comment]
![Bildschirmfoto von 2020-11-02 17-21-04](https://user-images.githubusercontent.com/73837912/97892045-d2121180-1d2f-11eb-9b5d-f74a8c88a6fa.png)

**Comment by sandsero** [comment]
I always select that when i install it...

**Comment by uBlock-user** [comment]
Reset uBO to default settings and try again.

**Comment by sandsero** [comment]
Yea with default settings it works fine in privat mode too not only with disabled privat mode. thats a difference.
The reset buttom did not work i had to uninstall it to close firefox and install it again.
But now I always have to click this data protection box away
![Bildschirmfoto von 2020-11-02 17-27-53](https://user-images.githubusercontent.com/73837912/97893199-41d4cc00-1d31-11eb-9b23-dab4be1a8d72.png)
And the thing is that some time ago it worked in private mode with additional filters, but not anymore... ATLEAST for me its somewhat broken now :(!

**Comment by sandsero** [comment]
Fix: If i disable and enable the addon after every start it works fine.....

**Comment by sandsero** [comment]
is there a way automate the fix?

**Comment by sandsero** [comment]
the fix isnt a fix sorry my mistake! i'm out

**Comment by gwarser** [comment]
No issues anymore? Besides login and consent dialogs? This should fix them:

	youtube.com##+js(set, ytInitialPlayerResponse.auxiliaryUi.messageRenderers.upsellDialogRenderer.isVisible, false)
	youtube.com##+js(set, ytInitialData.overlay.upsellDialogRenderer.isVisible, false)
	youtube.com##+js(set, ytInitialData.topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer.forceConsent, false)
	youtube.com##+js(json-prune, [].playerResponse.auxiliaryUi.messageRenderers.upsellDialogRenderer)
	youtube.com##+js(json-prune, [].response.topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer)

**Comment by gorhill** [comment]
No issue such as this should be filed, the real question is, were there network requests which should have been blocked and were not blocked? And if so, what were those requests which should have been blocked and which filters did they escape. Otherwise it's just someone pondering why uBO blocks less and this is a question/support issue.

**Comment by sandsero** [comment]
I also activated all additional filter lists. Maybe that was it...

**Comment by gorhill** [comment]
Always use the logger when investigating filtering issue and before opening issue about this.
