### ISSUE TITLE
Have the advanced user interface function as the uMatrix interface does/did

### ISSUE THREAD

**Issue by myfirstnameispaul** [uBlockOrigin/uBlock-issues#1324]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Have the advanced user interface function as the uMatrix interface

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/

### Steps to Reproduce

1. In a browser window, open from toolbar uMatrix.
2. In a second browser window, open from toolbar uBlock Origin with advanced user mode enabled.
3. uMatrix has interface, including elements and their status on x-axis and sites, domains, subdomains in y-axis.
4. uBlock Origin has interface with everything except options in vertical axis

### Expected behavior:

It would be nice if opening the uBlock Origin with Advanced user mode enabled presented the user with the uMatrix interface

### Actual behavior:

uBlock Origin with Advanced user mode enabled is less intuitive and has fewer options (e.g., no allow/block css, media, xhr, etc.)

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Mozilla Firefox for Linux Mint 82.0.2 (64-bit)
* Operating System and version: Linux Mint 20

**Comment by seniorm0ment** [comment]
*Didn't see this issue when searching apologies.*
Why is this declined curiously?
uMatrix offers significantly more granular control with it's interface. 

Could this *please* be reconsidered, so we only need 1 extension, and don't need to use uMatrix and uBlockO side by side anymore?

It could be added in as an option, off by default, that just extends the interface of uBlockO.

**Comment by u-RraaLL** [comment]
> Why is this declined curiously?

↓
> It would be nice if

AFAIK, all "it would be nice" requests get declined. An actual case needs to be made about benefits of a change, before it will be considered.

Bear in mind that gorhill has limited time to spend on the project and this wouldn't be easy to implement. He'd likely rather focus on things to benefit everybody, not just a niche group of users.

**Comment by myfirstnameispaul** [comment]
@u-RraaLL It seems the "It would be nice if an ad-blocker just blocked ads" request has been met? (o;

(Once upon a time, all they had was ABP...)

When I made this request I knew it was more wishful thinking than anything, so it probably won't happen unless some otherwise-unoccupied developer feels like putting it together and submitting a PR (that is far beyond my skills). And who knows if it would even be accepted or just maintained as a fork.

**Comment by uBlock-user** [comment]
> It seems the "It would be nice if an ad-blocker just blocked ads" request has been met?

[uBO is not an "ad-blocker" and never has been](https://github.com/gorhill/uBlock#philosophy).

**Comment by myfirstnameispaul** [comment]
@uBlock-user Within the context of my comment, your reply is off-topic, as I was referring to the time before uBlock.

**Comment by uBlock-user** [comment]
> Within the context of my comment, your reply is off-topic,

You brought up an irrelevant argument, so you cannot call my rebuttal as off-topic, specifically when it's you going off-topic in the first place("It would be nice if an ad-blocker just blocked ads" request has been met") and further grave-digging this thread after https://github.com/uBlockOrigin/uBlock-issues/issues/1324#issuecomment-998958223

**Comment by gorhill** [comment]
> Why is this declined curiously?

I typically don't explain why I decline a feature request, because asking me to do so is akin to asking me to justify how I employ my free time and I find this unpleasant. If this is still not convincing, imagine in any another context than software development asking a volunteer to explain why they don't contribute more time volunteering.
