### ISSUE TITLE
Very small text/objects in document-blocked.html

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uBlock-issues#1326]
In uBO's new GUI; why is everything in the **document-blocked.html** window so ridiculously small?
Could you please make it larger, because it's literally only half the size of what it used to be now!

### New interface:
![ubo-blockingwindow-new](https://user-images.githubusercontent.com/9382674/98227298-7033f080-1f57-11eb-8c59-a6ec3d0e4e5b.jpg)

### Old interface:
![ubo-blockingwindow-old](https://user-images.githubusercontent.com/9382674/98227358-85a91a80-1f57-11eb-9e98-5a17f4b10ad1.jpg)

Reference:
https://github.com/gorhill/uBlock-for-firefox-legacy/pull/274#issuecomment-722238584

**Comment by gorhill** [comment]
It's not "ridiculously small", the font is the same size as all other uBO's dashboard pages.

**Comment by THEtomaso** [comment]
But look at all the empty space..
Why not utilize some of it, thereby making things easier to read?

The way it is now, this comes to mind:
`https://www.youtube.com/watch?v=QnpB3_Oknmw`
:)

**Comment by gorhill** [comment]
> look at all the empty space

Mind that not everybody uses their browser the way you do or have the screen size you have.

**Comment by THEtomaso** [comment]
No, I only have a 1080p screen.
I can only imagine how small it will look on a 4K screen!

**Comment by gorhill** [comment]
Your screenshot is 1920px-wide, you full-screened the page just so you could complain of _"all the empty space"_. You want me to dismiss everybody else's use case and configure uBO for you specific use case and display. The answer is "declined" because I mind that uBO is used on all sort of display and the current font size is consistent with all other uBO pages.

Respect that I declined and move on.

**Comment by THEtomaso** [comment]
> you full-screened the page just so you could complain of "all the empty space".

What?
Of course the screenshot is from a maximized window!
Who on earth uses a restored window when browsing?

**Comment by gorhill** [comment]
So you woke up today and decided this is a good day to be a burden to a project maintainer by arguing endlessly?

**Comment by THEtomaso** [comment]
No, I just question your claim about me deliberately trying to make the empty space look larger.
Both screenshots were taken from a maximized window (not fullscreen), with the irrelevant browser toolbars removed from the pictures.
If you think that I were trying to cause confusion, I can edit those screenshots and leave the browser toolbars.
