### ISSUE TITLE
Adblockplus filter list does not seems to work

### ISSUE THREAD

**Issue by findow** [uBlockOrigin/uBlock-issues#1331]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Adblockplus subscriptions [link](https://adblockplus.org/subscriptions) has a filter list called [Anti-circumvention ABP filters](https://subscribe.adblockplus.org/?location=https%3A//easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt&title=ABP%20filters) which does not seems to work anymore with ublockorigin.
It says, once imported, "0 used out of 0"
I remember it working when I added it months ago, but now it does not seems to work anymore.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Import [link](https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) as filter list into ublock
2. Save changes
3. See "0 used out of 0" as result of import and saving

### Expected behavior:

I expect ublockorigin to load the filters contained in the list

### Actual behavior:

It does not seem to load any filter contained in the list

### Your environment

* uBlock Origin version: v1.30.6
* Browser Name and version: Brave beta 1.17.61
* Operating System and version: W10

**Comment by uBlock-user** [comment]
That list is not supported, so restricted on-purpose.

**Comment by findow** [comment]
Oh, I did not know badlists existed, but shouldn't it be mentioned in line with the filter list once imported?
Instead of "0 used out of 0" can't we get a better error message? Maybe a "This list is part of badlist (open list of badlinkS) and has not been loaded. See more (link to wiki page or issue page explaining why)"?
Thank you.

**Comment by keczuppp** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/857#issuecomment-574158607
https://github.com/uBlockOrigin/uBlock-issues/issues/1011#issuecomment-624118303

**Comment by gorhill** [comment]
> shouldn't it be mentioned

Sure, everything could be better, I just do not have the time to work on everything to make it perfect. The current solution is what I had time to do to solve the issue of people who keep adding lists which are not meant for uBO. At least filterlists.com does show that the list is not for uBO: <https://filterlists.com/lists/abp-anti-circumvention-filter-list>.

**Comment by keczuppp** [comment]
> At least filterlists.com does show that the list is not for uBO: https://filterlists.com/lists/abp-anti-circumvention-filter-list.

- I agree, moreover, that implies the OP ignored another Prerequisition, because a link to https://filterlists.com is in uBO documentation https://github.com/uBlockOrigin/uBlock-issues/wiki/Filter-lists-from-around-the-web#resources :
>    [ ]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

- also https://github.com/uBlockOrigin/uBlock-issues/wiki/Filter-lists-from-around-the-web can be opened in uBO filter list pane as well by clicking on Import icon:

<details not-open>
<summary>screenshoot</summary>


![eeee](https://user-images.githubusercontent.com/74409207/101043295-76c97e00-357e-11eb-99d2-e9ff7286d46f.png)
</details>

- the OP just ignored all Prerequisitions, and spammed the issue tracker, despite an information about abp-circumvention list being not compatible with uBO is placed in several places already...
