### ISSUE TITLE
Add a randomly enable option for each rule

### ISSUE THREAD

**Issue by ashtasht** [uBlockOrigin/uBlock-issues#1332]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Custom rules are prone to fingerprinting by websites -- some users (i.e. Advanced Users) have their own rules special rules. Some of rules are not important, there are many domains that I disabled but I do not care too much whether they are disabled or not, yet disabling/enabling them might help fingerprinting me. Randomly enabling/disabling these websites (a special option should be added) can vastly reduce fingerprinting.

I believe I can try to help if needed, but I have never developed a Firefox extension.

Thank you

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 82.0.2 (compiled myself)
* Operating System and version: Gentoo Linux

**Comment by gorhill** [comment]
To randomly enforce rules makes no sense to me.

Those who worry about fingerprinting should just disable JS by default, and/or use the Tor browser, or just stick to default filter lists.
