### ISSUE TITLE
Firefox slowdown and possible uBlock memory leak

### ISSUE THREAD

**Issue by sesinger** [uBlockOrigin/uBlock-issues#1333]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When running Firefox with uBlock and the Roboform extension over 3 to 4 hours the browser slows down to the point if being unusable. Also, Firefox memory usage increases 3 to 4 times. I reported this to Roboform and they believe it is a uBlock issue. I have  attached an about:memory file capture.
[memory-report.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/5507343/memory-report.json.gz)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1) Disabled all extensions except Roboform with Autofill option off - No problem

2) Enabled Autofill - minor memory increase over 24 hours but Firefox ran fine

3) Disabled Roboform extension and enabled uBlock Origin extension - Firefox ran fine and no memory increase

4) Enabled Roboform without Autofill plus uBlock extension - minor memory increase over 24 hours but Firefox ran fine

5) Enabled Roboform with Autofill plus uBlock extension - Major memory increase and Firefox slowed down and became non-functional over 3-4 hours.

It appears there is some conflict between Roboform with Autofill on and uBlock Origin. 

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.30.6
* Browser Name and version:Firefox 82.0.2
* Operating System and version: Windows 10 1903

**Comment by gorhill** [comment]
Please try with another content blocker to confirm the issue requires uBO specifically to be present.

**Comment by uBlock-user** [comment]
>  I reported this to Roboform and they believe it is a uBlock issue.

How did they come to this conclusion ?

**Comment by sesinger** [comment]
> 
> 
> Please try with another content blocker to confirm the issue requires uBO specifically to be present.

I have now installed Ghostery and disabled uBO. We'll see what happens over the next 3-4 hours.

**Comment by gorhill** [comment]
Also, did you try with other password managers? For example, Bitwarden is well rated.

**Comment by sesinger** [comment]
> 
> 
> > I reported this to Roboform and they believe it is a uBlock issue.
> 
> How did they come to this conclusion ?

This is what they said which I realize is hardly definitive:
"Please be advised, RoboForm does not attempt to take control over other extensions and / or extension activities
so the problem cannot be fixed on our side."

**Comment by gorhill** [comment]
I don't understand their answer, why did you tell them to get such answer?

**Comment by sesinger** [comment]
> 
> 
> Also, did you try with other password managers? For example, Bitwarden is well rated.

I haven't. I have a subscription and been using Roboform for many years on multiple devices without problems.

**Comment by sesinger** [comment]
> 
> 
> I don't understand their answer, why did you tell them to get such answer?

I told them the same things I put in this issue. I also just sent them the about:memory file

**Comment by gorhill** [comment]
Do I need a subscription to reproduce?

**Comment by gorhill** [comment]
Your memory report is anonymized, I can't associate memory usage with anything specific. I do see however that you had other extensions enabled beside uBO and RoboForm. How did you ascertain that these other extensions are not the cause?

**Comment by sesinger** [comment]
No. The free version at roboform.com should be fine. The subscription version adds the muti-device feature. Make sure the Autofill option is set to "Offer to Autofill"

**Comment by sesinger** [comment]
When I ran the tests as indicated in my original post, I had all the other extensions turned off. 

Once the Ghostery test you requested is completed, I will rerun with just Roboform and UBo and send you a memory report without it being anonymized. It will probably be tomorrow before i do that.

**Comment by gorhill** [comment]
So far from what I see in the memory report as it is is that there seems to be something in the extensions process taking a lot of memory, but I can tell that is not uBO because it does not show ArrayBuffer or WASM module being in use. The one entry matching uBO's usage of ArrayBuffer and WASM is 10.7 MB.

**Comment by gorhill** [comment]
> The free version at roboform.com should be fine

It's asking me to create an account in the popup menu, there is no option to configure. For now I rather not have to go through that step.

I saw that I needed to accept to let the extension collect data before it can be used so now my question is: is it possible that uBO blocks network requests made by the extension in page content context?

Can you use uBO's logger to find out about this? I am wondering if uBO is blocking network requests made by the extension while the extension is not prepared to deal with its network requests being blocked.

**Comment by sesinger** [comment]
To find the Options, right click on the Roboform icon in the taskbar. Autofill should be on the list.

**Comment by gorhill** [comment]
Do you need to browser or can the browser just be idle with only a handful of tabs opened?

**Comment by sesinger** [comment]
I'm not sure, as I'm regularly using the browser.

I believe you do have to be logged in with your Master Password.

**Comment by gorhill** [comment]
I'm going to wait for a non-anonymized memory report, it does not look like anything is happening on my side and trying to reproduce this is a time sink for me given that this is taking time away from what I do usually.

**Comment by sesinger** [comment]
I've been running Ghostery since last night and this morning I started getting the same symptoms (slowdown and high memory usage) so it would appear that uBO is not the problem. 

I created a  non-anonymized memory report with Ghostery which I have attached here and will send to Roboform.

[memory-report.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/5512110/memory-report.json.gz)


Thanks for your help.

**Comment by gorhill** [comment]
Thanks, I will report my findings later. I deleted your message to your non-anonymized reports from being further downloaded.

**Comment by gorhill** [comment]
Yeah the issue seems to be with RoboForm, this is the extension holding onto memory. They will have to look into this, it's for them to fix, not other extensions; other extensions are not responsible for them holding onto memory, only them can fix this.

A few excerpts showing this:

---

    web (pid 29344)

    RoboForm
    20.02 MB (100.0%) -- explicit
    └──20.02 MB (100.0%) -- js-non-window/zones
       ├──16.96 MB (84.72%) ++ zone(0x1a84a8fd000)
       ├───2.89 MB (14.43%) ++ zone(0x1a848c30000)
       └───0.17 MB (00.85%) ++ zone(0x1a8440740

    Ghostery
    0.82 MB (100.0%) -- explicit
    └──0.82 MB (100.0%) -- js-non-window/zones
       ├──0.41 MB (50.24%) ++ zone(0x1a848c30000)
       └──0.41 MB (49.76%) ++ zone(0x1a84a8fd000)

---

    web (pid 29768)

    Roboform
    100.75 MB (100.0%) -- explicit
    ├──100.64 MB (99.89%) -- js-non-window/zones
    │  ├───77.55 MB (76.97%) ++ zone(0x21542e7b000)
    │  ├───20.07 MB (19.92%) ++ zone(0x215208c2000)
    │  ├────2.90 MB (02.88%) ++ zone(0x21537de9000)

    Ghostery
    5.44 MB (100.0%) -- explicit
    └──5.44 MB (100.0%) -- js-non-window/zones
       ├──4.33 MB (79.69%) ++ zone(0x21542e7b000)
       ├──0.62 MB (11.38%) ++ zone(0x215208c2000)
       └──0.49 MB (08.93%) ++ zone(0x21537de9000)

---

    extension (pid 21264)

    Roboform
    184.50 MB (100.0%) -- explicit
    ├──184.49 MB (100.0%) ++ window-objects
    └────0.01 MB (00.00%) ++ js-non-window

    Ghostery
    38.53 MB (100.0%) -- explicit
    ├──37.03 MB (96.11%) -- window-objects
    │  ├──20.90 MB (54.25%) ++ active
    │  └──16.13 MB (41.86%) ++ js-zone(0x19d08961000)
    └───1.50 MB (03.89%) ++ workers

---

    web (pid 14604)

    RoboForm
    72.47 MB (100.0%) -- explicit
    └──72.47 MB (100.0%) -- js-non-window/zones
       ├──69.58 MB (96.01%) ++ zone(0x1b78b688000)
       └───2.89 MB (03.99%) ++ zone(0x1b796135000)

    Ghostery
    5.68 MB (100.0%) -- explicit
    └──5.68 MB (100.0%) -- js-non-window/zones
       ├──5.19 MB (91.51%) ++ zone(0x1b78b688000)
       └──0.48 MB (08.49%) ++ zone(0x1b796135000)

---

And so on

**Comment by mkeroppi** [comment]
I have the same problem.  Ublock origin memory usage swells to over 1GB over 2-3 days of usage (from a fresh restart of <50MB).  No other extension come close (my next extension Videodownloadhelper uses 50MB).
![ublock](https://user-images.githubusercontent.com/35188272/98877333-776a6b00-243d-11eb-9b14-fcc48d5d3822.png)

**Comment by gorhill** [comment]
What you report is same as this: <https://bugzilla.mozilla.org/show_bug.cgi?id=1652925#c18>.

What version of Firefox and uBO ar eyou using?

**Comment by mkeroppi** [comment]
Firefox 82.0.3
uBlock Origin 1.30.6
No Tree Style Tabs

**Comment by gorhill** [comment]
The issue is with Firefox, I explained in the bug report that uBO does not look ever at favIcon -- it's what is show as leaking in your screenshot. Feel free to add useful information to the bugzilla entry if you have any -- the bugzilla issue has been gathering interests from Firefox devs.

Also, try in a new profile with only uBO -- no other extension.

**Comment by sesinger** [comment]
Firefox 82.0.3
uBlock 1.30.6

A new version of the Roboform extension (9.0.9.1) came out yesterday and may have solved the problem. I've been using it today and so far so good.

**Comment by gorhill** [comment]
@mkeroppi I added a workaround in uBO dev build 1.30.9b16, and this seems to get rid of the leaky favicon data URI. You can see if this makes a difference, the dev build is an in-place replacement for the stable version of uBO, so all your settings will be preserved: <https://github.com/gorhill/uBlock/releases>.

**Comment by mkeroppi** [comment]
> 
> 
> @mkeroppi I added a workaround in uBO dev build 1.30.9b16, and this seems to get rid of the leaky favicon data URI, as far as `about:memory` reports. You can see if this makes a difference, the dev build is an in-place replacement for the stable version of uBO, so all your settings will be preserved: https://github.com/gorhill/uBlock/releases.

Thanks, will try.

**Comment by mkeroppi** [comment]
I do think that fixed it (for now).  It seems a similar issue plague some other extensions (but none uses that call nearly as often as uBlock before).
