### ISSUE TITLE
uBO Enhancement: Network request protocol with info of Tab, Addon origin.

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [uBlockOrigin/uBlock-issues#1335]
Hi. uBO is a VERY important Addon! 
Enhancement: In the network request protocol : See which tab or addon does the request.
Especially for the background request from frames this would be good to detect the guilty site.
In the details this extra info would be fine.
Or did i overlook it?
thx

ps:
No donations wanted? 🙂
https://github.com/gorhill

**Comment by gwarser** [comment]
>Enhancement: In the network request protocol : See which tab or addon does the request.

In logger? You mean this: https://github.com/gorhill/uBlock/wiki/The-logger#page-selector ?

Other add-on requests are not visible to uBO.

> Especially for the background request from frames this would be good to detect the guilty site.

?? Fourth column in the logger displays "context" - domain of the page from which request was initiated.

Please do not ignore issue template. It's not easy to understand what you are requesting. Steps to reproduce and screenshots will help a lot.

**Comment by gorhill** [comment]
Sorry, I am not accepting feature requests, except from long time filter list maintainers and contributors.
