### ISSUE TITLE
Documentation Update - Whitelist > Trusted Sites

### ISSUE THREAD

**Issue by minig0d** [uBlockOrigin/uBlock-issues#1337]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Documentation needs updating to reflect the terminology/labeling change from "Whitelist" to "Trusted Sites". 
#1114 

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Whitelist
https://github.com/uBlockOrigin/uBlock-issues/wiki/How-to-whitelist-a-web-site

### Steps to Reproduce

1. Visit aforementioned urls

### Expected behavior:

See the term "Trusted Sites" utilized

### Actual behavior:

Whitelist

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
@gwarser

**Comment by gwarser** [comment]
Please review https://github.com/uBlockOrigin/uBlock-issues/wiki/_compare/6f4f85247518c70680fe2481ca2f733934dcbdbb

**Comment by gwarser** [comment]
Dashboard link must also be updated.

**Comment by minig0d** [comment]
Not sure if the terminology was used anywhere previously or was just created for this revision (obviously I see the diff, I just mean in general used anywhere), but the term "blocklist mode" or "blocklist" is probably pretty confusing/ambiguous as from a UI standpoint, both "My Filters" and "My Rules" technically seem like "block lists".

While it probably is a minor issue for more experienced users (and conceptually probably beyond the scope of this "issue"), the ambiguity in terminology and overall lack of differentiation/explanation/clarification between static and dynamic filtering seems like the largest obstacle for new users.  So if this is a new term being coined, would highly suggest ensuring it's unambiguous.

In regards to thoroughness, it looks like you got all instances. I just see 3 very minor missing words described below.

PS. Such a minor edit it's probably not worth starting a separate issue on, but on the main trusted sites page in the grey box, I think it's missing "edge-scheme" (unless it's no longer being used).

Great work!

[Behind-the-scene-network-requests.md](https://github.com/uBlockOrigin/uBlock-issues/wiki/_compare/6f4f85247518c70680fe2481ca2f733934dcbdbb#diff-6036b961a5745c1f27ac92054b0d3bbada267aa124e7ea3331472e431a949031) line 9 and 52:  
line 9 was updated to: "will no longer be on trusted sites list by default"  (needs a "the" added)
line 52 was updated to "tab is on _Trusted sites_ list by default" (also needs a "the" added)

[Cloud-storage.md](https://github.com/uBlockOrigin/uBlock-issues/wiki/_compare/6f4f85247518c70680fe2481ca2f733934dcbdbb#diff-9981deded5293616315347a102c0a09efcb89063b950319dbc7c42db39dbe7b4) 
line 39 is missing an "and" before the word trusted (in fairness it was missing it before this update too).

**Comment by gwarser** [comment]
>Not sure if the terminology was used anywhere previously

:( https://en.wikipedia.org/wiki/Blacklist_(computing) and "Controversy" section.

You can edit if you notice any problem.

**Comment by gwarser** [comment]
Some pages are really old, maybe I should not touch them at all. For example these sentences about "HTTP Switchboard" and "RequestPolicy".

**Comment by gwarser** [comment]
`edge-scheme` was added in February https://github.com/gwarser/uBlock-Origin/commit/5ccf435754b8186786e693f6bf42c8eafaf42b4d

**Comment by gwarser** [comment]
> line 39 is missing an "and" before the word trusted

I don't know why (2AM?), but I make it "or", can it be "or"?

**Comment by krystian3w** [comment]
GitHub wiki support someting like:

https://en.wikipedia.org/wiki/Wikipedia:Redirect

`#REDIRECT [[NEW_IS]]`

**Comment by gwarser** [comment]
Last time I checked (years ago) it did not.

**Comment by hawkoon** [comment]
@gorhill is a politically correct leftist cuck and should kill himself.
