### ISSUE TITLE
Ublock Origin 1.16.14 suddently stops working on Firefox 61.0.1

### ISSUE THREAD

**Issue by arderyp** [uBlockOrigin/uBlock-issues#134]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I recently updated to Firefox 61.0.1, and Ublock Origin stopped working.  It no longer shows in the toolbar, and I now see ads.  I do still see UO in the AddOns list.  I tried restoring defaults, disabling then re-enabling, uninstalling and reinstalling, and everything checked above.  The UO version is 1.16.14.

### Steps to Reproduce

1. Try to run latest Ublock Origin on latest Firefox 61.0.1

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Firefox 61.0.1
* Operating System and version: Ubuntu Linux 16.04.4

**Comment by gwarser** [comment]
So it fixed itself? How?

Works for me.

**Comment by arderyp** [comment]
Rebooting machine... should have tried that first... alas, my mistake
