### ISSUE TITLE
Youtube logout after every reload

### ISSUE THREAD

**Issue by dawidkossa** [uBlockOrigin/uBlock-issues#1340]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When i log in to youtube and i log in to google account i reloade  a page i must log in again always. Even if it's not clearing cookies.

### A specific URL where the issue occurs

www.youtube.com

### Steps to Reproduce

1. Log in to google account by youtube.
2. Reload the page.

### Expected behavior:

That the YouTube page will not log me out.

### Actual behavior:

A youtube page log me out every time when i turn on UBlock Origin

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 82.0.3 (64 bit)
* Operating System and version: Windows 10 2004

**Comment by gorhill** [comment]
I've never seen this behavior -- your problem is somewhere else, assuming you checked all boxes truthfully in the template. I will let you investigate further, you are best placed to figure this out. If you can't help but are convinced uBO is your issue, I suggest you install another content blocker.

**Comment by gorhill** [comment]
I will keep it open for a day in case someone else is interested in spending time on this.

**Comment by uBlock-user** [comment]
Is `privacy.purge_trackers.enabled` set to `false` ? If not, try that.

**Comment by gorhill** [comment]
That setting is `false` by default and he checked _"using a new, unmodified browser profile"_.

**Comment by dawidkossa** [comment]
> 
> 
> That setting is `false` by default and he checked _"using a new, unmodified browser profile"_.

i have a new firefox (changed from brave )

**Comment by uBlock-user** [comment]
Still could be https://bugzilla.mozilla.org/show_bug.cgi?id=1672394 as the behaviour he reports in description doesn't occur anywhere else recently and is neither possible to reproduce.

**Comment by dawidkossa** [comment]
but when i disable the uBlock the problem stops

**Comment by dawidkossa** [comment]
> 
> 
> Is `privacy.purge_trackers.enabled` set to `false` ? If not, try that.

where I should set this ?

**Comment by uBlock-user** [comment]
In `about:config`. Also browse to https://firefox-storage-test.glitch.me/ and copy-paste the results here.

**Comment by dawidkossa** [comment]
> 
> 
> In `about:config`. Also browse to https://firefox-storage-test.glitch.me/ and copy-paste the results here.

same :/ here's result https://pastebin.pl/view/a806b8fb
btw. i have set it by default

**Comment by gorhill** [comment]
uBO does not touch cookies, so the issue lies elsewhere and OP is best placed to investigate this issue which he is the only one to suffer.
