### ISSUE TITLE
$queryprune doesn't work if no-strict-blocking: * true is present

### ISSUE THREAD

**Issue by nobura** [uBlockOrigin/uBlock-issues#1341]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`queryprune= ` doesnt work, if `no-strict-blocking: * true` ?

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. add `||reddit.com^*^utm_*=$queryprune=|utm_`
2. goto reddit.com

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: ubo 1.30.9b16
* Browser Name and version: firefox 82 x64
* Operating System and version: windows 10 x64

**Comment by keczuppp** [comment]
We already have a queryprune thing discussion here: https://github.com/uBlockOrigin/uBlock-issues/issues/760

**Comment by gorhill** [comment]
Closing as _invalid_: the template was completely disregarded, and no st3eps to reproduce are provided, including no URL despite the clear _"A specific URL is MANDATORY"_ instruction. I still did check just to be sure and querypruning works fine with `no-strict-blocking: * true`.

**Comment by uBlock-user** [comment]
STR --

Add to my filters `||reddit.com/r/*utm_$doc,queryprune=|utm_

Add to my rules -- `no-strict-blocking: * true`, hit _Save_, followed by _Commit_.

Open, the logger in a new tab, browse to `https://www.reddit.com/r/random/` in another tab, and be sent to a random subreddit with utm parameters and as per the logger see them appear without getting pruned as below -- 

![Capture](https://user-images.githubusercontent.com/21290713/99074952-aa983000-25de-11eb-8a11-d9d116656191.PNG)

To verify, now remove the `no-strict-blocking: * true` from My rules and browse back to `https://www.reddit.com/r/random/` and switch to the logger and see prunning now working again --

![Capture](https://user-images.githubusercontent.com/21290713/99075448-82f59780-25df-11eb-8946-e75a6e61ea24.PNG)

**Comment by gorhill** [comment]
I think I had restarted uBO without realizing after I entered the `no-strict-blocking: * true` rule.
