### ISSUE TITLE
Element picker allow multiple click in yellow "create" button 

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#1342]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

For several weeks now, I have been noticing a bug in the picker element.

The bug is that I can click the "create" button many times and as a result the item on the page does not disappear, the picker element does not close, on list "My filters" I see many copies/duplicates of suggested cosmetic filter.

### A specific URL where the issue occurs

IMO any page is good to test, recently, the picker element glitch on:

```
osehero.pl
```

### Steps to Reproduce

1. Use often element picker on many pages
2. try click in "create" button
3. see if the picker element is closed, the element has been cosmetically hidden without refreshing

### Expected behavior:

- The picker element should not allow multiple clicks on the "create" button, 
- The first click in "create" should close it by forcing it to use again from scratch,
- Hide the element of page without refreshing the page.

### Actual behavior:

- The picker element allows multiple clicks on the "create" button,
- The first click in "create" does not close it, 
- The element on the page is still visible.

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 82.0.2
* Operating System and version: Windows 10 Pro 20H2

**Comment by gorhill** [comment]
I can't reproduce, the element picker exits when I create a filter. I tried with your `osehero.pl`, uBO dev build, and Firefox 82.0.3.

Does this happen in a new Firefox profile?

**Comment by krystian3w** [comment]
> Also, any error at the dev console of the page?

At I have glitch, I don't have opened any JS consoles to catch a particular bug.

---

As you can, give this application the lowest priority. Like `P7`:

![obraz](https://user-images.githubusercontent.com/35370833/99151679-2bb5fc80-269d-11eb-91e4-15279801e875.png)

**Comment by gorhill** [comment]
> give this application the lowest priority

You lost me, I don't know what you are talking about.

**Comment by krystian3w** [comment]
I mean, you wouldn't care every day that the button is glitching and nobody else.

**Comment by gwarser** [comment]
How are you accessing Element picker? From keyboard, context menu or uBO popup?

**Comment by krystian3w** [comment]
From right click menu.

**Comment by krystian3w** [comment]
OK, I updated Firefox to 83rc2, I moved only bookmarks.

The error log will be visible in devtools (`F12`) or it is better to open the browser with the native browser console (`firefox -jsconsole`) active daily.

**Comment by gorhill** [comment]
The console does not have to be pre-opened, you can just open the F12 console when the issue occurs. If nothing there, then you can open the browser ctrl-shift-J console and see if there is something in there.

**Comment by krystian3w** [comment]
On Fresh firefox profile no longer have bug with button for any new 1.31.1bXX release.
