### ISSUE TITLE
Impossible to edit My filter list

### ISSUE THREAD

**Issue by happysurf** [uBlockOrigin/uBlock-issues#1343]
### Prerequisites

- [ I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
The "My filter" or any other list are impossible to edit for delete some strings.

### A specific URL where the issue occurs
Not applicable 

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
Not applicable 

### Steps to Reproduce

1. [First Step]
Open the dashboard...
2. [Second Step]
Go to Filter lists and click on the eye of My Filter...

### Expected behavior:

[What you expected to happen]
The selected strings must be deleted.

### Actual behavior:

[What actually happened]
The list appear but if I select some string then is impossible delete it.
### Your environment

* uBlock Origin version: 1.30.9.102
* Browser Name and version: Firefox 83 final
* Operating System and version: W 10 2004

**Comment by happysurf** [comment]
Sorry, my fault.

**Comment by gorhill** [comment]
You will have to fill and thruthfully all the checkboxes in the template before I take a look at this.

**Comment by uBlock-user** [comment]
> Go to Filter lists and click on the eye of My Filter...

That's Asset viewer and read-only by-design.

**Comment by krystian3w** [comment]
Or logger reporter, when also read only, uBO no have checkmark column like ABP/AdGuard.
