### ISSUE TITLE
Question about redirection rule to local resource (... like decentraleyes)

### ISSUE THREAD

**Issue by Dormann** [uBlockOrigin/uBlock-issues#1344]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hello,

Well, this is about something that has already came up in previous (and rejected) subject : the ability to redirect some requests for resources like javascript libraries to a local version, like the decentraleyes addon does.
In AdGuard and uBlock Origin syntax, the $redirect modifier is described as a tool to redirect web requests to a local "resource".
So, does it mean that everything has already been built into filter syntax to support what decentraleyes does ?
It's just that those two addons don't really mix well together as a block request is not redirected.

If not, is it that the filter syntax lack some element ?
Otherwise, could there be a local storage for those resources, and the possibility to have another option than block, noop and accept, which would be redirect ?

Best regards,

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 78.4.1esr (64 bits)
* Operating System and version: Debian 10

**Comment by uBlock-user** [comment]
Support issues and questions are handled at https://www.reddit.com/r/uBlockOrigin/

**Comment by Dormann** [comment]
OK, my bad, I was not sure if it was a support related or not, since it is said that we can describe a feature.

**Comment by gwarser** [comment]
>like decentraleyes

https://github.com/uBlockOrigin/uBlock-issues/wiki/Experimental-features

**Comment by gorhill** [comment]
uBO's and Decentraleyes's redirections have completely different purpose, they are not meant to be compared against each other, they are different features serving different purpose.

**Comment by Dormann** [comment]
> uBO's and Decentraleyes's redirections have completely different purpose, they are not meant to be compared against each other, they are different features serving different purposes.

OK, thanks for the clarification.
