### ISSUE TITLE
"Home" button on Strict blocking page works incorrectly in some cases

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1345]
<details>
<summary>Details</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

Clicking on it seems to be looping by creating new tab with same Strict blocking page.

### A specific URL where the issue occurs

    olx.pl

### Steps to Reproduce

1. Add `||olx.pl^$document` to My filters or subscribe to `https://raw.githubusercontent.com/PolishFiltersTeam/KAD/43980361b4358e4ed7dbb795f1186195c9f6a36f/KAD.txt` (false positive, they will remove it soon from main list)
2. Open `olx.pl`
3. Click on "home" icon

### Expected behavior:

- This icon should probably not appear for custom lists - "Homepage"  is not handled
- Handle "Homepage" header in custom lists and open list home page
- What to do for "My filters"?

### Actual behavior:

Strict blocking page opens(duplicates) in new tab

### Your environment

* uBlock Origin version: 1.30.6 1.30.9rc2
* Browser Name and version: Firefox 82,84
* Operating System and version: Manjaro KDE

**Comment by gorhill** [comment]
> This icon should probably not appear for custom lists - "Homepage" is not handled

This should be its own issue -- I don't know at this point how reliable this is, I am not aware that there is any official documentation for a `Homepage` entry.
