### ISSUE TITLE
youtube ads not fully blocked as of today 

### ISSUE THREAD

**Issue by asianmusicguy** [uBlockOrigin/uBlock-issues#1347]
Not sure which list is causing it so ill report here the ad it self is blocked but i am now forced to click "skip ad" to proceed with a video perhaps you can find the cause a provide your own fix ?

**Comment by asianmusicguy** [comment]
not sure why this was closed as this is a valid issue

**Comment by uBlock-user** [comment]
Not a uBO issue, filterlist issues are to be filed on uAssets, not here.
