### ISSUE TITLE
uBlock Origin breaks Firefox Multi-Account Containers' dropdown-menu in 84.0b1

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [uBlockOrigin/uBlock-issues#1352]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This *may* be specific to ARM64 / Apple Silicon / macOS Big Sur, I am unsure as of yet. After installing a fresh FireFox Beta 84.0b1 on a new computer (M1 MacBook Air), I had issues with FireFox Containers not working properly. After some triage effort, I finally narrowed it down to the combination of uBlock Origin + FireFox Containers; I can reproduce this issue on a completely fresh profile with no changes *other* than installing uBO and FFMAC from the AMO. )=

Video included below.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps to Reproduce

1. Create a new profile
2. Install uBlock Origin from the AMO
3. Install the official Multi-Account Containers from the AMO
4. Attempt to open either the uBlock Origin or FFMAC interfaces from their hotbar buttons

### Expected behavior:

Normal dropdown for either addon to open

### Actual behavior:

uBO's dropdown is full-size, but empty white; FFMAC dropdown doesn't open at all, showing *only* the tiny disclosure triangle at the top:

10-second video: http://i.ell.io/yKd0cA

### Your environment

* uBlock Origin version: v1.30.6
* Browser Name and version: Firefox 84.0b1 (64-bit)
* Operating System and version: macOS Big Sur 11.0.1, running on an [ARM M1](https://www.apple.com/mac/m1/) MacBook

(Given that this reproduction may be ARM-specific, I am very happy to undertake any debugging steps you may need me to — if you cannot reproduce, just let me know what you need me to do to test this out. I'm a JavaScript developer as well, but with only superficial experience with WebExts; happy to run debugging tests for you.)

**Comment by uBlock-user** [comment]
Navigate to https://firefox-storage-test.glitch.me/ and report results here.

**Comment by gorhill** [comment]
I don't have MacOS, and as far as I know, the Firefox build for ARM is in development, you should report such issues to Firefox devs, not here -- I can't investigate and nothing will happen here.

**Comment by ELLIOTTCABLE** [comment]
Yeah, no errors from the storage-test!

@gorhill understood — is there any way for me to at least pull up an inspector/console specifically linked to uBlock or something like that? I'd love to see if there's any easy, low-hanging-fruit error-messages relating to this blocking bug. )=

**Comment by gorhill** [comment]
The browser console (ctrl-shift-j) should be able to show extension errors, maybe _"Show Content Messages"_ in console settings is needed, not sure.

**Comment by gwarser** [comment]
Maybe it's about WASM? 

Open `about:config` and change `javascript.options.wasm` to `false`.

**Comment by gorhill** [comment]
> Open `about:config` and change `javascript.options.wasm` to false.

This does not seem to prevent uBO from using wasm on my side. Toggling [`disableWebAssembly`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#disablewebassembly) to `true` does work reliably though.

**Comment by gwarser** [comment]
I was not sure uBO is usable enough to access advanced settings.

**Comment by ELLIOTTCABLE** [comment]
This still occurs on Firefox Beta 84.0b5 with `javascript.options.wasm` configured to false. (Thanks for continuing to offer debugging steps, even though you consider it an upstream bug! Your time as maintainers is respected and beloved. <'3)

Notably, *this* issue does not reproduce in the Nightly (85.0a1/20201126) — although it's really hard to tell, because the constant crashes described in #1354 make it almost impossible to get the dropdowns for either addon opened before the Nightly crashes, it looks like both *do* actually render in Nightly (with `javascript.options.wasm` at the default value of `true`; not that I could possibly get to `about:config` and change it before it crashes *anyway* …)

**Comment by gwarser** [comment]
@ELLIOTTCABLE try toggling `javascript.options.wasm_trustedprincipals` in `about:confi` it should disable wasm for add-ons. 

Can be also something with graphics, maybe svg or maybe requestAnimationFrame...

**Comment by LucasJanin** [comment]
I have the same issue on MAcbook Pro 13" M1 with uBlock Origin and Firefox Multi-Account Containers in 84.0b5.
For testesting, I replaced uBlock Origin with AdBlocker Ultimate, same result :-(

**Comment by gorhill** [comment]
Report to Firefox devs please, that is the best way to make resolution of the issue go forward. uBO and extensions in general are just HTML/CSS/JS, it's not supposed to crash the browser, and if it does so, it's for the browser devs to investigate. I do not have access to an Apple M1 so I can't even help Firefox devs narrow the issue.

**Comment by LucasJanin** [comment]
Thanks, @gorhill for your reply!

**Comment by gwarser** [comment]
Looks like it may really be wasm: https://bugzilla.mozilla.org/show_bug.cgi?id=1678226#c15

And switching both `javascript.options.wasm_trustedprincipals` and `javascript.options.wasm` helps.

Should be fixed soon in Nightly.

**Comment by gorhill** [comment]
The issue is reportedly fixed in beta: <https://bugzilla.mozilla.org/show_bug.cgi?id=1678443#c11>.
