### ISSUE TITLE
Pull Request Submission for JSON/XML web accessible resources

### ISSUE THREAD

**Issue by mvastola** [uBlockOrigin/uBlock-issues#1353]
### Prerequisites
Not applicable.

### Description

Hi, so I made a PR (or -- at least -- what I intended to be a PR), but am not able to submit it because I haven't contributed to the project in the past. (And I can't submit it to this repo as the code to be patched obviously isn't here.)

I am new to this project and am not sure how this is supposed to be handled. (Do I need to request access to submit PRs on the other repo?) 

FWIW, I'm also not entirely sure that this PR is complete and/or how to to test it (there doesn't seem to be a test suite, and I don't have access to Safari to test that browser).

The commit is in my fork at https://github.com/mvastola/uBlock/commit/2907658f1dbee8915bfe8c06c6db09561e9c4caa.

Any direction would be appreciated.

**Comment by gwarser** [comment]
You can strip data from JSON using `json-prune` scriptlet.

It will be best if you first provide real-world examples where your fixes will be useful.

**Comment by gorhill** [comment]
Declined. Do not submit PRs and do not open issues without actual real world cases to solve. Resources are added only when I make the decision to do so according to what they are actually solving in the real world -- _"I noticed a few ad engines" is not enough, you need to provide the actual cases to uAssets (as asked in the template which you removed) so that we can investigate solutions with what is currently in uBO.

**Comment by mvastola** [comment]
> Declined. Do not submit PRs and do not open issues without actual real world cases to solve. Resources are added only when I make the decision to do so according to what they are actually solving in the real world -- _"I noticed a few ad engines"_ is not enough, you need to provide the actual cases to uAssets (as asked in the template which you removed) so that we can investigate solutions with what is currently in uBO.

@gorhill, I'm sorry I angered you, but there's no need to be so hostile.  I'm honestly not trying to make your life harder.

I actually started filling in the template but it quickly became clear that it wasn't compatible with this kind of inquiry. For example, the template would have had me ask this question on Reddit whereas it clearly needed to be directed to the maintainers of this extension. 

Also, I went through the whole template, and it would never have occurred to me to submit this to the uAssets repo: firstly because I wouldn't have considered this an issue with filtering, but primarily because the code to be changed literally is not in that repository.

I'll go back and get the exact URLs and use cases tomorrow when I get a chance.  I guess I assumed it was self evident that many web services use JSON and XML and that there are bound to be users interested in blocking them gracefully (for whatever reason).  If it is your practice not to make any changes that aren't strictly required, then I agree this probably doesn't meet that threshold, but this seemed like the most elegant solution, as it is much less likely to result in JS errors being emitted.

Am I to understand that I should add further information on a new issue in uAssets?

**Comment by gorhill** [comment]
> I'm sorry I angered you, but there's no need to be so hostile

In addition to all that I said above, do not (mis)attribute state of mind.

**Comment by gorhill** [comment]
> I'm sorry I angered you, but there's no need to be so hostile

In addition to all that I said above, please do not (mis)attribute state of mind.

> this seemed like the most elegant solution

To what? You are completely failing to document what exactly you are trying to solve here, and for all I know uBO could be already well able to handle the cases you are not documenting.

**Comment by gorhill** [comment]
For reference, here is an example of how an idea for a new filtering capability was added: <https://github.com/uBlockOrigin/uBlock-issues/issues/760>.

Notice how there needed to be [_actual cases_](https://github.com/uBlockOrigin/uBlock-issues/issues/760#issuecomment-715926907) for which I could investigate the solution before I accepted to go ahead with the new filtering capability. This is what is missing here.
