### ISSUE TITLE
Reverse lookup partially fails for a filter redirecting to empty media resource

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1358]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Reverse lookup of filter lists on the logger fails for a filter redirecting to media resource - in the example below it succeeds for `||static.twincdn.com^$media,redirect-rule=noopmp3-0.1s` but fails for `||static.twincdn.com^$media`. No such problem for `||google-analytics.com/analytics.js` redirected to `google-analytics.com/analytics.js` on the same page ~~(EDIT: maybe not, as it shows Peter Lowe's as Filter list which has the exact blocking filter - so maybe blocking part of `$redirect` was not counted?)~~.

### A specific URL where the issue occurs

[NSFW] `https://www.pornohirsch.net/film/blonde-stiefschwester-laesst-sich-hart-ficken-45035/`

### Steps to Reproduce

1. Visit URL with default setup and open the logger
2. Close video-overlay (or add `pornohirsch.net##.vjs-overlay` from the beginning)
3. Play the video and see the logger

### Expected behavior:

It shows uBlock filters as Filter list.

### Actual behavior:

"Static filter could not be found in any of the currently enabled filter lists"

![redirect-nofilterfound](https://user-images.githubusercontent.com/58900598/99990973-cded8700-2df7-11eb-9901-40ed6635b271.png)

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Firefox 83.0
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Do I need to add `||static.twincdn.com^$media`? If so, how did you add it? Did you add it through the logger or directly in _"My filters"_?

**Comment by Yuki2718** [comment]
@gorhill uBlock filters has `||static.twincdn.com^$media,redirect=noopmp3-0.1s`. I mean, `redirect=` and not `redirect-rule=`.

**Comment by gorhill** [comment]
Ok I can reproduce -- investigating.

**Comment by gorhill** [comment]
The issue is that without a redirect option, the same block filter is compiled [at this line](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/static-net-filtering.js#L3420), while with the redirect option the block filter counterpart is compiled [at a different point, using a different internal representation](https://github.com/gorhill/uBlock/blob/b6b167671ef596dee43349efcd6bf74f96caa220/src/js/static-net-filtering.js#L3513).
