### ISSUE TITLE
uBlock Origin no translate correctly AdGuard matches-css with background

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#1359]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO need use `/url\("data` in matches-css, but AdGuard no need:

```regex
testcases.adguard.com,surge.sh#?##case10.banner:matches-css(background-image: /url\(data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)
testcases.adguard.com,surge.sh#?##case11.banner:matches-css-after(background-image: /url\(data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)
testcases.adguard.com,surge.sh#?##case12.banner:matches-css-before(background-image: /url\(data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)
```

maybe AdGuard use someting other like:

```js
let readStyle = getComputedStyle(document.querySelector(yourPath), null);
let showStyle = readStyle.getPropertyValue(yourCssProperty);
```

Optionally, we can try to fix this on the AdGuard side in `_ublock.txt` files reported to repository:

* `AdGuardTeam/FiltersCompiler` or
* `/AdguardTeam/ExtendedCss`

### A specific URL where the issue occurs

https://testcases.adguard.com/Filters/extended-css-rules/test-extended-css-rules.html - tests 10, 11 & 12

### Steps to Reproduce

1. Add demo filters for test 10-12: https://testcases.adguard.com/Filters/extended-css-rules/test-extended-css-rules.txt or from this issue
2. check result in test
3. test 10-12 fail and no match elements:

    ![obraz](https://user-images.githubusercontent.com/35370833/100026739-a1337280-2deb-11eb-91e5-931a6a566b30.png) | failed tests, watch on second numbering
    --- | ---

### Expected behavior:

Filters from AdGuard Base based on `:matches-css(background-image: /url\(` should hide elements (I found 11 filters)

### Actual behavior:

Filters from AdGuard Base based on `:matches-css(background-image: /url\(` no hide elements (I found 11 filters)

### Your environment

* uBlock Origin version: 1.31.1b2
* Browser Name and version: Firefox 83
* Operating System and version: Windows 10 Pro 20H2

**Comment by gwarser** [comment]
`getComputedStyle` returns `url("data` with `"`. Filters works with additionall `"`.

**Comment by krystian3w** [comment]
But AdGuard team never add ", so this should be added by inteligent script in `ExtendedCss`/`FiltersCompiler`?

**Comment by gwarser** [comment]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extended-css-matches-css

>For regex patterns, `"` and `\` should be escaped, because we manually escape those in extended-css-selector.js.

???

**Comment by gwarser** [comment]
testcases.adguard.com,surge.sh#?##case10.banner:matches-css(background-image: /url\("?data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)
	testcases.adguard.com,surge.sh#?##case11.banner:matches-css-after(background-image: /url\("?data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)
	testcases.adguard.com,surge.sh#?##case12.banner:matches-css-before(background-image: /url\("?data\:image\/svg\+xml;base64,[A-Za-z0-9]{100,}/)


Is working in both?

**Comment by krystian3w** [comment]
Yes:

![obraz](https://user-images.githubusercontent.com/35370833/100025270-b78bff00-2de8-11eb-88bf-9e500de09a90.png) |
--- |

**Comment by gorhill** [comment]
AdGuard removes the quotes from style properties which are URL:

https://github.com/AdguardTeam/ExtendedCss/blob/df5c7b3a2ef25c22f28c369e9ff4ea96e8aba218/lib/style-property-matcher.js#L43

I am not sure I agree with this, it's done to accommodate Safari as per comment in code.

**Comment by gwarser** [comment]
Fixed on AdGuard side?

**Comment by krystian3w** [comment]
> Fixed on AdGuard side?

Maybe need few days after pull sectret code into FiltersRegistry.

**Comment by Yuki2718** [comment]
Confirmed uBO version of AG lists doesn't include quotation: `softpedia.com#?##swipebox-overlay > #swipebox-right:matches-css-before(content: /^Advertisement$/)`
