### ISSUE TITLE
Dropdown menu is empty

### ISSUE THREAD

**Issue by sannagy90** [uBlockOrigin/uBlock-issues#1361]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock origin dropdown is buggy and displays an empty box when Firefox is running under wayland on linux. When running Firefox on Xorg, it's working as expected. Also tested running it under XWayland, and it's present there too.

### A specific URL where the issue occurs

happens everywhere, duckduckgo.com

### Steps to Reproduce

1. Run Firefox on wayland 
2. load a webpage
3. Click on the ublock icon

### Expected behavior:

ublock origin dropdown appears with all the options

### Actual behavior:

dropdown appears but it's an empty box

### Your environment

* uBlock Origin version:1.31.0
* Browser Name and version: Mozilla Firefox 83.0 (64-bit)
* Operating System and version: Fedora 33
![Screenshot from 2020-11-24 12-48-12](https://user-images.githubusercontent.com/51812249/100132421-649b6180-2e53-11eb-995f-5caa6c9816bb.png)

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1672139

**Comment by uBlock-user** [comment]
fixed in v84 as per bugzilla

**Comment by gorhill** [comment]
> when Firefox is running under wayland on linux

uBO's popup panel is HTML/CSS/JS, if rendering fails because of how your OS is configured, this is a browser issue, not a uBO issue.
