### ISSUE TITLE
Suggestion to change naming of 1P/3P to avoid confusion with 1p/3p

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#1362]
From this commit; https://github.com/gorhill/uBlock/commit/bde3164eb445a4e74acca303ec9fa07f82ba1b1c

Noticed new filter switches, which I didn't initially pick up that `p` and `P` is treated differently. 

Just to avoid confusion with currently filter switches, would it better to have different naming for them? Just to avoid potential bugs because someone used `P` instead of a `p` or vice-versa.

**Comment by gorhill** [comment]
I don't mind `strict1p`/`strict3p`. I just know filter list maintainers in general like abbreviations, so I was trying to find something concise. Another idea I had was `1p!`/`3p!` but in the end wasn't too sure about this.

**Comment by mapx-** [comment]
`s1p` / `s3p`  would be fine

**Comment by uBlock-user** [comment]
or `s1P`/`s3P` will do too..

**Comment by ryanbr** [comment]
we could do both, short form/long form?
