### ISSUE TITLE
Update hufilter subscription URL

### ISSUE THREAD

**Issue by scripthunter7** [uBlockOrigin/uBlock-issues#1364]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

If it is possible, please update the hufilter URL from 
[https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt](https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt)
to
[https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-ublock.txt](https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-ublock.txt)

It is a clean uBO compatibile version.

See our repository at [https://github.com/hufilter/hufilter](https://github.com/hufilter/hufilter)

### A specific URL where the issue occurs

[https://github.com/hufilter/hufilter](https://github.com/hufilter/hufilter)

### Steps to Reproduce
-

### Expected behavior:
-

### Actual behavior:
-

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
Done, but it may take up to at least 13 days for everybody to be fetching from the new URL.

**Comment by scripthunter7** [comment]
Thank you for your quick help and reply!
