### ISSUE TITLE
uBO should ignore `redirect=` directives with unrecognized redirect token

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#1366]
Actually I described part of this bug [here](https://github.com/MajkiIT/polish-ads-filter/issues/17839#issuecomment-734839254) but today for some reason it has changed, and what I described in the link above will no longer help

SO. add this adguard rule to uBO my filters

`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication-adsbygoogle,domain=animedigitalnetwork.fr|baddiehub.com|clockks.com|coron.tech|earn4files.com|extremereportbot.com|gatcha.org|huljjang.com|jemerik.com|moviessquad.com|scat.gold|sitarchive.com|tellynewsarticles.com|webkod.pl|youneed.win|darmowa-tv.ws|mr9soft.com`

and go to the site, for example here `https://baddiehub.com/` {NSFW}, please note that this filter is a `redirect=` and now what do you get https://user-images.githubusercontent.com/8535285/100518332-f6ed8d80-31e4-11eb-9a61-9ef8cfe94b92.png

tested on a stable release version and on the latest version for developers, of course with default settings

PS: You have a rule in your main list, add badfilter flag for a second. so that he does not bother you to check
`||googlesyndication.com^$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=baddiehub.com,badfilter`

**Comment by uBlock-user** [comment]
> redirect=googlesyndication-adsbygoogle

Invalid, use `redirect=googlesyndication_adsbygoogle.js`

**Comment by bogachenko** [comment]
>add this adguard rule to uBO my filters

>  adguard rule

**Comment by bogachenko** [comment]
there are 2 filters in my sheet, both for adguard and for ubo. read the link I posted above

**Comment by gorhill** [comment]
There is no resource token matching `googlesyndication-adsbygoogle`, the proper token is `googlesyndication_adsbygoogle.js`.

**Comment by uBlock-user** [comment]
That AdGuard rule will not work in uBO, I can reproduce what you're saying but you need to use the one I posted.

**Comment by gorhill** [comment]
Which AdGuard list(s) make use of `googlesyndication-adsbygoogle`?

**Comment by bogachenko** [comment]
@uBlock-user Fuck, I know the adguard rule won't work in uBO. I'm talking about something else.
1. it is detected incorrectly.
2. Why is it determined at all?

**Comment by bogachenko** [comment]
@gorhill english

**Comment by gorhill** [comment]
What do you mean "detected incorrectly"?

The URL I get is:

    https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

So the filter you use does match that URL. uBO tries to redirect to `googlesyndication-adsbygoogle`, but since the resource token is not found, ultimately it does not redirect, hence no yellow line in the logger for the actual redirection.

**Comment by uBlock-user** [comment]
@bogachenko Okay, I think I understand what you're saying now, that rule is invalid and hnce shouldn't be compiled, but somehow it got compiled and applied as per https://user-images.githubusercontent.com/8535285/100518332-f6ed8d80-31e4-11eb-9a61-9ef8cfe94b92.png ?

**Comment by uBlock-user** [comment]
@gorhill Seems the redirection does occur as per https://user-images.githubusercontent.com/8535285/100518332-f6ed8d80-31e4-11eb-9a61-9ef8cfe94b92.png even though the resource token name doesn't exist ?

**Comment by gorhill** [comment]
Well I made the choice in the static filtering parser to not discard redirect filters for which no token exists, the idea is that maybe someone will modify `userResourcesLocation` such that the resource token will become valid.

The redirect should not be fired, the yellow line is ultimately confirmation the redirect occurs, the other lines are just confirmation a filter is matching. No yellow line = no redirection.

**Comment by uBlock-user** [comment]
The line is light blue there as per the above picture, what does that signify ?

**Comment by gorhill** [comment]
I prefer to keep open. The is this edge case where uBO should fall back to a working redirect filter if the picked one is not ultimately taken. I can reproduce this with the provided test case if I remove the `badfilter` and add `:1` to the added `redirect=` filter.

**Comment by gorhill** [comment]
Also, unrelated but I will try to fix at the same time, adding a priority to the redirect token causes uBO to think the token is invalid.

**Comment by bogachenko** [comment]
@gorhill  explain why the speed race does not work(**although recently worked**), I have 2 filters , see

1 for ubo
`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication_adsbygoogle.js,domain=animedigitalnetwork.fr|baddiehub.com|clockks.com|coron.tech|earn4files.com|extremereportbot.com|gatcha.org|huljjang.com|jemerik.com|moviessquad.com|scat.gold|sitarchive.com|tellynewsarticles.com|webkod.pl|youneed.win|darmowa-tv.ws|mr9soft.com`

2 for adguard
`||pagead2.googlesyndication.com^$important,script,redirect=googlesyndication-adsbygoogle,domain=animedigitalnetwork.fr|baddiehub.com|clockks.com|coron.tech|earn4files.com|extremereportbot.com|gatcha.org|huljjang.com|jemerik.com|moviessquad.com|scat.gold|sitarchive.com|tellynewsarticles.com|webkod.pl|youneed.win|darmowa-tv.ws|mr9soft.com`

if you add them together in strict order (rule for ubo on 1 line, for adguard on 2), as I wrote, then the rule for adguard will still be fulfilled and the rule for ubo is ignored. is the token to blame?

**Comment by gorhill** [comment]
That it worked before is just luck, there has never been documentation stating the order of the `redirect=` filters is meaningful. It looks like before the `redirect=` directive for uBO was found first, and now since the `redirect=` code has been refactored, the AdGuard one is looked up first.

In any case, the fix proposed here is that uBO will disregard `redirect=` directives which do not match an actual resource, so this will fix your issue.

**Comment by bogachenko** [comment]
that would be wonderful

**Comment by bogachenko** [comment]
@gorhill The problem is not fixed, not completely. I added [a commit](https://github.com/bogachenko/fuckfuckadblock/commit/fc23439fad0451052b16e1f2815dd19b7b125906) to my list, pay attention to `,redirect=noopjs,` and what did I [get](https://user-images.githubusercontent.com/8535285/100540287-7c7a4780-3290-11eb-8818-c114fae501f0.png).

test link `https://swingerpornfun.com/2020/11/28/kinky-husband-lends-his-cute-submissive-wife-to-a-dominant-couple/` NSFW

latest version 1.31.1b8 opera

**Comment by uBlock-user** [comment]
@bogachenko Any change if you add `||vkcdnservice.com^$third-party,badfilter`  to my Filters ?

**Comment by bogachenko** [comment]
nope

**Comment by uBlock-user** [comment]
Nevermind, internally the `redirect` filter is split into a blocking filter and a redirecting filter which is `redirect-rule`, not related to this issue, you can verify this by filtering `vkcdn` into the filter widget into the logger.

**Comment by bogachenko** [comment]
the `redirect` filter has been transformed into a `redirect-rule` filter, and you want to say that this is normal?

**Comment by gorhill** [comment]
> the `redirect` filter has been transformed into a `redirect-rule` filter, and you want to say that this is normal?

This has always been the case, `redirect=` means "block and redirect", while `redirect-rule=` means "redirect if blocked".

**Comment by uBlock-user** [comment]
Yes, the only difference now is you will be seeing the internal representation in the logger **too**

**Comment by gorhill** [comment]
> and what did I get.

Looks fine to me. You created a `redirect=` rule and it got applied as expected.

**Comment by Yuki2718** [comment]
Isn't it better if uBO translates redirect resources of AG into uBO counterparts? If AG adds a redirect filter there must be a reason and uBO uses some AG lists including French and Japanese. In case of `googlesyndication-adsbygoogle` it's no matter as uBlock Privacy redirects it by default, but what about other resources uBO doesn't redirect by default - well, fortunately the most common one, noopjs, is compatible to uBO but wiki suggests the current formal form for uBO is `noop.js` and `noopjs` works only as alias.
Compatibility table of redirect resources is here `https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/compatibility-table.md#redirects` and apparently most of incompatible ones are what are redirected by default, just not sure if they're all. In rare occasion AG's redirect conflicts with uAssets' solution e.g. https://forums.lanik.us/viewtopic.php?f=62&t=45330 but we can address such cases by priority now.

**Comment by gorhill** [comment]
The only one not available in uBO which I see used in _AdGuard Base_ is `noopvast-2.0`, I would be willing to add support for this. Do you see anything else which would be needed beside this one?

**Comment by Yuki2718** [comment]
What about `prevent-fab-3.2.0`? Old uBO syntax was `fuckadblock.js-3.2.0`.

**Comment by gwarser** [comment]
I think https://github.com/gorhill/uBlock/commit/904aa87e2aacb5fbfbb79ea702891e5be72d4b55 broke this again. OP filter has `important` option and because of this `||googlesyndication.com^$script,redirect-rule=googlesyndication_adsbygoogle.js,domain=baddiehub.com` from uBlock filters is not applied. Or is this expected for `important`?

**Comment by gorhill** [comment]
Yes, `important` applies to `redirect-rule` too.

**Comment by gorhill** [comment]
Ok I see your point now that I can test (was on my phone when I answered yesterday), so yes, I need to fix this.

**Comment by gwarser** [comment]
Correct redirection is now applied when both filters are used, but filter with invalid token is still logged.

When only one filter, the one with invalid token is used, no redirection is logged.

**Comment by gorhill** [comment]
You think the redirect directives with invalid token should not be logged?

**Comment by gwarser** [comment]
I'm asking for opinions.
