### ISSUE TITLE
Whitelist don't work

### ISSUE THREAD

**Issue by avatartw** [uBlockOrigin/uBlock-issues#1367]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

https://imasdk.googleapis.com/js/core/bridge3.426.0_en.html

### Steps to Reproduce

1. add 
||imasdk.googleapis.com^
@@||imasdk.googleapis.com/js/core/bridge*.html
in My filters

2. open url https://imasdk.googleapis.com/js/core/bridge3.426.0_en.html

### Expected behavior:

uBlock Origin allows https://imasdk.googleapis.com/js/core/bridge3.426.0_en.html

### Actual behavior:

uBlock Origin blocks https://imasdk.googleapis.com/js/core/bridge3.426.0_en.html

### Your environment

* uBlock Origin version: 1.31.1b8
* Browser Name and version: Chrome v87
* Operating System and version: Windows 7

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6554#issuecomment-735312143
