### ISSUE TITLE
Logger window does not remember position & size anymore!!

### ISSUE THREAD

**Issue by MUFTAKiS** [uBlockOrigin/uBlock-issues#137]
i have the latest version & i wasnt experience that in v1.6.10 and may be 12

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
Fill the [template](https://github.com/uBlockOrigin/uBlock-issues/blob/master/.github/ISSUE_TEMPLATE.md#prerequisites) and edit your post accordingly.

**Comment by MUFTAKiS** [comment]
whatever the window now opening toward the left hand corner with big size, is there a chance to reposition & resize it or should i revert back to a previous v??!!

**Comment by gwarser** [comment]
If you click with shift when opening logger you will have it inside tab.

**Comment by MUFTAKiS** [comment]
i just need it as i used to was better!
