### ISSUE TITLE
Feature request for uBO

### ISSUE THREAD

**Issue by throwaway282630101** [uBlockOrigin/uBlock-issues#1370]
The reason I don't want to list the information here is because doing so might help malware/scam sites.

It's not a vulnerability in uBlock or anything like that.

If there's no possible way to direct message I might list them on here, but I STRONGLY recommend it be sent privately.
(it's also a long read too)

**Comment by mapx-** [comment]
you can try direct message here on reddit to one (or all) moderator
https://www.reddit.com/r/uBlockOrigin/

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
> It's not a vulnerability in uBlock or anything like that.

Then best is that you fill the template to detail what you think is an issue. If I consider it's really a security issue I will mark it as such.

**Comment by throwaway282630101** [comment]
Is it possible you can message me on Reddit and I'll reply the information to you?

**Comment by gorhill** [comment]
uBO is developed in full public view, you will have to details your request here, there is no secret code in uBO that is out of public view, so it makes no sense to request secret features. There is no way around this: fill the template with all the required details, and provide actual, real world cases to justify your feature request.

**Comment by gorhill** [comment]
Alright, closing as _invalid_ until actionable information is provided.

**Comment by throwaway282630101** [comment]
> 
> 
> Alright, closing as _invalid_ until actionable information is provided.

Posting it now:

Hello.

As it says in the uBlock description "uBlock Origin is not an "ad blocker", it's a wide-spectrum content blocker with CPU and memory efficiency as a primary feature."



There's not another extension like uBlock, there's not another extension that not only gives the power to the users to determine what to block, but to do so with complete privacy.

No pinging or contacting a home server.
No agreeing to a Privacy Policy or a End User License Agreement.
Completely open source with public beta tests.
And the developers don't ask for money for ANY reason. (thank you!)

The features below give more power to the users to help determine these same choices.
And while some may seem silly, please don't dismiss them so fast! I'll explain the best I can on why these can help users not only from malware, but their privacy too.


All these can be made optional, not made for out of the box in case it does effect the CPU and memory. (most safeguards do, but that's the user's decision)


----
- *Site Identification*


You're putting your trust into a website, your privacy and security.
But where is the server located? Is it a trusted known site or just created last week like most malicious sites?

There's 2 extensions that help with that, one is called "flagfox". 

It's recommended by mozilla but it's not perfect.
 
It displays a flag icon indicating the current webserver's physical location on the address bar.
But to know the more information you have you have to click that flag and that's where privacy is lost.
It will redirect you to a site "Geotool". (which also has Google ads)


According to the extension's privacy policy under Statistics: "Flagfox tracks nothing. Geotool logs basic information for the purposes of statistics and abuse resistance. Additional actions have their own privacy policies on this matter which you should refer to."

The site displays a lot helpful information about whatever site server you click on such as,

ISP
IP Address
Hostname
Continent
Country
Region
City
Country Code
Local time 
Postal Code
Latitude & Longitude

I believe we need the same integration, flag system and everything, but without contacting a server.
(more information below on how uBlock will improve on this, not just copy it)

Why?

As they state: "Flagfox can be used as a warning as to when a server isn't where it should be. If you end up at a site claiming to be an American bank, and it shows as Nigerian, then you may want to think twice."

And for legal jurisdictions.

Let's say you're in the EU which has the GDPR, but someone visited a website from Russia or a country that doesn't follow GDPR / your country's internet privacy laws, some people who care about privacy would leave that site.


Or a personal experience I had.
I visited a site and it was in complete English, everything looked okay, but I saw there were ads not being blocked, in a different language too.
I found out that site wasn't in my country, I didn't even have a filter on for that country's site so who knows if they were known malware ads I was getting?


With this flag system we should be also able to block any country we don't want to connect to, for privacy or security reasons.

That would be a game changer, not even 99% of routers can do that.
Yes, I know we can do something similar on uBlock, we can block ".ru" or ".uk" domains, but sites are not always clear like that.

This gives the user more POWER to BLOCK and better DECIDE where they should be.



https://addons.mozilla.org/en-US/firefox/addon/flagfox/
https://addons.mozilla.org/en-US/firefox/addon/flagfox/privacy/
(Anther cool feature is hovering over the flag shows the site's encryption support "HSTS HTTP/2" however, I believe this belongs in the next tool)



But what about when the site was created? There's another extension that helps a lot with "Site Identification" Called "Serpstat Website SEO Checker".

It's again not open source and has NO privacy.
If you go to their site's privacy policy under Serpstat extension:

"The information we collect is non-identifiable aggregated information. We are not aware of and cannot determine the identity of the users from whom the Non-Personal Information is collected. Non-Personal information which is collected includes the user's aggregated and technical information transmitted by the user's device as follows: 

Plugin ID (Not Identified with User ID)

Web resources that visit by plugin ID and timestamp

In this context, we notably use your information in an effort to improve our users' experience, to further develop, customize, enhance and improve the performance of our services and extension. In addition, we use Non-Personal Information, aggregated with information or statistics regarding user browsing behavior, such as overall patterns or demographic reports, which do not describe or identify any individual user."



And under Access and Disclosure to Third Parties:

"We may share your personal information with our third-party service provider"

Since it's not open source we don't know if there's a secret "feature" that might "help" send our personal information.
 


But going to the main topic,

This extension shows the date of a site's creation, alternates of the website such as it's mobile version.
Can tests the download speed for it's computer or mobile version of the site.
Can see meta tags, W3C validators, ect.

I really recommend trying this extension and seeing how you can verify a lot more information about any site. It's MUCH easier than doing it on "dev configs" on Firefox.

On the tabs only "On-page SEO parameters" works for free, the others you have to pay with a membership.

One thing I find unnecessary is the "Page analysis". On the picture from the addon's page (#3) it shows "Top-10 keywords by URL" Seems a bit of spying? I don't really know.

I believe we need the same integration, all the information this addon gives helps the users decide and verify their visited site.
And it might increase reports, malware or a bug with websites.



Also (don't know if this was included it the extension) we need to also see the site's traffic to help verify their legitimacy.

How?

When websites are for sell (dead ones) for a couple of months they'll looking for a buyer, for those months there's zero to no traffic.
If someone buys that domain, it'll still say it was created years ago, if we see traffic now just coming in, I'd rather wait a month or 2 before trusting it.


https://addons.mozilla.org/en-US/firefox/addon/serpstat-plugin/
https://serpstat.com/users/privacy-policy

This integration gives the user more POWER to better DECIDE where they should be and help verify if the site is safe.

If the flag system is integrated and this extension too, I'd like clicking the flag and it'll open up a box like this addon.




---------------------------
- *Scripts / Filters Information*



When 3rd/any party is blocked by default when looking on the logger it doesn't say if the bad script is also blocked by filters.

For example (happened to me): Lets say you go to a site with 3rd party blocked, you need to enable it for the site to work, but you see a tracking / bad script, I thought, "it's probably going to be blocked" and it wasn't. There's no information to tell me that this bad script is also flagged by a filter.
I believe this needs to be fix asap.


To test this turn on "Fanboy’s Enhanced Tracking List" and Block 3rd-party scripts, than go to https://www.reddit.com
you'll see https://accounts.google.com/gsi/client is being blocked (you might have to wait till the page fully loads)
You can see in Details it just says "Filter: *3p-script block"

Now enable 3rd party, it'll be blocked by Fanboy and show any other filters blocking it.


Unless I'm not seeing/missing something?




-------------------------
- *Improving The Pop Up Blocker*



I've personally seen a lot of malware recently spread not by clicking / viewing ads, but by redirecting. For example, clicking anywhere on a page/clicking play on a video, and a pop up shows up for a second, injects malware code, then loads it's blank site or exits its self out.

The Pop Up Blocker I think is the only thing saving people.

Malwarebytes is even talking about malvertising cases recently:
https://blog.malwarebytes.com/social-engineering/2020/09/malvertising-campaigns-come-back-in-full-swing/

Not sure what else we can add to this but you're the developer, you know the code, try to break the tool from working. That's what they're going to try to do, if not already.




---------------------------
- *More Filters*

Lastly, we need more Malware Domains filters.

Last year I believe we had 4 types to pick from, now we only have 2.

And I can personally tell you that they do not work from the sites I've been on.
The Google / Firefox safe browsing works better than the filters.

I'm not saying to delete them, I'm sure they work fine, but we more and more than last time.
We need at least 5 filters total.





---------------
- *Easy Reporting Ads / Problems*


In the About section in the uBlock dashboard, there needs to be a more user friendly way of how to report ads or problems.
Just going there I see "Issue tracker"

But I don't think the average user knows that's where you can report problems.

I've checked Wiki and Troubleshooting, but didn't see any way of how to report ads / problems I may have.




-------------------------
- *Improving*


With Flash coming to end, there will be users that decide to keep it.
I know browsers can forbid flash from running but uBlock should also give the user the power to dicde if it can run.

Even Java (not javascript) we should also be able to block it.

I know uMatrix isn't being worked on anymore, but I believe there should be an emergency update to block them
(emergency being flash) if it doesn't already.



--------
- *Q/A*


I've read reasons about this a few years ago, but can't remember or find what that reason was, can please tell us if uBlock already has these these safety features?


NoScript can also block HTML object tags, all media tags (not just images), WebGL, ajax CORS, new and not well know HTML and JS API, XSS suspicious requestes and Clearclick protection. 

I've even heard it blocks IP browser leaks.

I know uBlock blocks JavaScript now, but what the other? If not, we really need these!

I also know uBlock Origin isn't a script blocker it is a domain blocker while uMatrix and Noscript are script and other web element blockers but like it says at the begging "uBlock Origin is not an "ad blocker", it's a wide-spectrum content blocker"

I know if all of these features are made it going to takes mouths just to test on different OS's, Browsers, webextensions and legacy addons, so we really need to start as soon as possible for it to be made into the full version.




If you read this: https://www.reddit.com/r/uBlockOrigin/comments/k2yalt/why_is_facebook_and_platformtwittercomwidgetsjs/  

graph.facebook.com and platform.twitter.com/widgets.js is blocked only by filters per-site, not globally.
Facebook and Twitter are still tracking everywhere we go! mp3geek said: 

"I had twitter blocked originally, then people complained when an article reference a twitter post (and it used an embedded twiiter iframe).

Facebook has similar issues, some sites will use facebook for signin and comments. Blocking facebook by default would create many complaints because of this."

A user pointed out: "There's a reason Ghostery and Privacy badger have them as click-to-load. Would be nice if uBlockO had that as well"

Is this already in?




And that's it, thank you for reading! :)

And if any of these are made possible, as my name suggests, I'd like not to be credited.

**Comment by Yuki2718** [comment]
Quoting gorhill from `https://old.reddit.com/r/uBlockOrigin/comments/jr6szm/suggestion_scoring_performance_of_filterlists/gbxtcvp/`:

> Best is that you fork and implement your own ideas the way you see it, i.e. scratch your own itch by investing your own time/efforts -- it takes seconds to fork the project. Eventually once you implemented all this, I will consider importing the features. Here is the thing, having ideas is easy and cheap, doing the actual work to implement them is where the real value is. For me its best when people work on their own extensive ideas so that they find for themselves the huge gap between having ideas vs. realizing them.

> 
> * _Q/A_
> 

Support issues and questions are handled at https://www.reddit.com/r/uBlockOrigin/

**Comment by throwaway282630101** [comment]
> > Best is that you fork and implement your own ideas the way you see it, i.e. scratch your own itch by investing your own time/efforts 

I don't know how to make an extension / coding stuff.

**Comment by keczuppp** [comment]
As for:

> throwaway282630101 : https://github.com/uBlockOrigin/uBlock-issues/issues/1370#issuecomment-736845476 :
> 
>     More Filters
> 
> Lastly, we need more Malware Domains filters.
> 
> Last year I believe we had 4 types to pick from, now we only have 2.
> 
> And I can personally tell you that they do not work from the sites I've been on.
> The Google / Firefox safe browsing works better than the filters.
> 
> I'm not saying to delete them, I'm sure they work fine, but we more and more than last time.
> We need at least 5 filters total.

Not sure whether you already did read or not these discussions about malware lists in uBO: https://github.com/uBlockOrigin/uBlock-issues/issues/984 + https://github.com/uBlockOrigin/uBlock-issues/issues/1116

**Comment by throwaway282630101** [comment]
@gorhill Is this still invalid I've put the information 2 days ago?

**Comment by keczuppp** [comment]
- your comment with the features requests is a massive wall of text
- to read it, analyze it and reply to it, gorhill needs to spend several hours or even a whole day
- at the moment he is already extremely busy with more important issues in uBO like: fixing important bugs, addressing important features, so it seems you have to be patient and wait up to several days for his reply, he will answer when he finds time

**Comment by throwaway282630101** [comment]
@gorhill Hi, sorry I know your busy but I hoping you could comment on my request I listed above, I posted it a month ago now.

I think *Scripts / Filters Information* part is very important.

**Comment by gorhill** [comment]
I decline everything.

Do not post long laundry list of your own ideas for someone else to work on -- these are cases of fork and scratch your own itch. Here is an issue tracker, report things to be fixed in uBO, i.e. things that do not work according to the documentation.
