### ISSUE TITLE
Broken rendering on lenta.ru

### ISSUE THREAD

**Issue by CCCP-USA** [uBlockOrigin/uBlock-issues#1373]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Broken rendering on lenta.ru

### A specific URL where the issue occurs

http://lenta.ru

### Steps to Reproduce

Broken rendering, refresh page does not help

### Expected behavior:

Proper rendering

### Actual behavior:

]

### Your environment

* uBlock Origin version: uBlock Origin v1.31.0
* Browser Name and version: Firefox Browser Developer 84.0b6 (64-bit)
* Operating System and version: Windows 10 Home 20H2

**Comment by hmnd** [comment]
I'd suggest purging the cache of all block lists, updating them and then restarting your browser. I just had a similar issue that affected most sites, including lenta.ru and that fixed it.

**Comment by gorhill** [comment]
> I verified that this is not a filter issue

How did you verify it's not a filter issue?
