### ISSUE TITLE
tabs.removeCSS does not work as expected in Chromium 87

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1375]
### Description

Chromium 87 implements the [`tabs.removeCSS()`](https://developer.chrome.com/extensions/tabs#method-removeCSS) API. However, this API appears to not function in uBO as it does in Firefox.

### A specific URL where the issue occurs

    https://gorhill.github.io/uBlock/tests/css-selector-based-cosmetic-filters.html

### Steps to Reproduce

1. Visit above URL
2. Copy-paste in my filters all the filters under the *Filters* header on the page
3. Force a reload of the page
4. The page should show all the colored rectangle as green with the text _pass_
5. Open uBO's popup panel and click the no-cosmetic-filtering switch

### Expected behavior:

Without having to reload the page, all the colored rectangles should become red with the text _fail_

### Actual behavior:

The colored rectangles stay green with the text _pass_

The cause is that uBO set the propery `runAt` when calling `tabs.removeCSS()` and this property is not to be used with `tabs.removeCSS()`, which causes `tabs.removeCSS()` to fail. This works with Firefox because it just silently ignores the extraneous property.

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Chromium 87.0.4280.66
* Operating System and version: Linux

**Comment by gorhill** [comment]
I am considering an stable revision for that fix.

**Comment by gorhill** [comment]
I will create an emergency revision if the fix (which is kind of trivial) shows all is working fine with no regression.

**Comment by gwarser** [comment]
".13" custom build works for me. It does not pause on "caught exceptions" like 1.31.1.12.

**Comment by aidili** [comment]
[object DOMException]
上下文
background.html
堆叠追踪

js/is-webrtc-supported.js:42 (匿名函数)
js/is-webrtc-supported.js:52 (匿名函数)

**Comment by aidili** [comment]
![2020-12-03_012638](https://user-images.githubusercontent.com/33697131/100908758-d2582500-3506-11eb-8e95-a932022d5591.png)
![2020-12-03_012735](https://user-images.githubusercontent.com/33697131/100908766-d6844280-3506-11eb-9367-44eff8333864.png)

**Comment by gorhill** [comment]
@uBlock-user why the deleted messages?

**Comment by uBlock-user** [comment]
Messages were not related to this issue.

**Comment by gorhill** [comment]
I prefer messages to be hidden as off-topic than deleted, this way I don't have to wonder what happened.
