### ISSUE TITLE
Cosmetic filter options obscured in picker window when site has horizontal scrollbar (overflow-x)

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#1379]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When a webpage has a horizontal scrollbar (overflow-x), the cosmetic filter options in the viewport of the position picker window is being obscured by the horizontal scroll bar.

### A specific URL where the issue occurs

`https://multimedia.scmp.com/native/infographics/article/3108271/how-virtual-reality/`

### Steps to Reproduce

1. Use Element picker to select a cosmetic filter
2. Observe not possible to see the full picker box and the last row of filter options because the sites horizontal scrollbar (overflow-x) obstructs the view and overlays on top of the bottom of the picker window.

![cosmetic-hidden-picker](https://user-images.githubusercontent.com/22258847/101058326-04937200-355b-11eb-806f-cf6bd6702e1f.png)

Note, you can add `multimedia.scmp.com##html:style(overflow-x: hidden !important;)` to `My Filters` to get rid of the sites horizontal scroll bar if needed for testing.

### Expected behavior:

Picker Box is fully viewable when a horizontal scrollbar is displayed on a page with horizontal scrollbar by offsetting `###ublock0-epicker aside` from the bottom of page by 20px rather than the 4px currently.

### Actual behavior:

Can't see bottom filter options

### Your environment

* uBlock Origin version: `1.31.3b0`
* Browser Name and version: Latest Firefox nightly and Chrome Beta Version 87.0.4280.66 (Official Build) beta (64-bit)
* Operating System and version: Win 10

**Comment by uBlock-user** [comment]
> Note, you can add multimedia.scmp.com##html:style(overflow-x: hidden !important;) to My Filters to get rid of the sites horizontal scroll bar if needed for testing.

Or physically pick the picker and move to a higher place to avoid the obstuction, perhaps picker can be placed a bit higher by default.

**Comment by krystian3w** [comment]
Or implement as PR save last position after click `Create` or `Quit`.

**Comment by gorhill** [comment]
Declining, I just don't want to spend time on mitigation code work around a browser's own unexpected behavior, which mitigation code could break further something else, when it's a trivial edge issue with an easy workaround (just slightly move the picker).
