### ISSUE TITLE
add sub filters list name in the blocked domain alert

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#138]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] subscribe this filter list <https://github.com/KonoromiHimaries/PolishSubFilters/blob/master/internal-filters/wewnetrzne.txt>
2. [Second Step] try join to any random blocked site, example. `iplogger.org`
3. [and so on...] test 

### Expected behavior:

[What you expected to happen]
![2018-07-21-chrome-extension___cjpalhdlnbpafiamejdnhcphjbkeiagm_document-blocked html_detail](https://user-images.githubusercontent.com/5884000/43037094-7138f0bc-8d09-11e8-893c-c7818b859fc7.png)

### Actual behavior:

[What actually happened]
![2018-07-21-chrome-extension___cjpalhdlnbpafiamejdnhcphjbkeiagm_document-blocked html_detail kopia](https://user-images.githubusercontent.com/5884000/43037092-689fd27c-8d09-11e8-8bfd-f5bde9ba2b5e.png)

### Your environment

* uBlock Origin version: uBlock Origin 1.16.14
* Browser Name and version: chr 67.0.3396.99 
* Operating System and version: w10

**Comment by gorhill** [comment]
Sublists are loaded seamlessly to make up the main lists -- it's a convenience for filter list maintainers and being seamless means it must not be shown to end users.

Declined.
