### ISSUE TITLE
Question: anti-anti-ablock ?

### ISSUE THREAD

**Issue by Ryder17z** [uBlockOrigin/uBlock-issues#1383]
since Nano Defender is now blacklisted i don't trust the ublock + nano setup with opera.

Is there something else i can use?

**Comment by gwarser** [comment]
Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)

**Comment by Ryder17z** [comment]
usually it's the other way around.
