### ISSUE TITLE
Custom green rule with resist.Fingerprinting in FF

### ISSUE THREAD

**Issue by pit65** [uBlockOrigin/uBlock-issues#1387]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

UBlock 1.31.0
Firefox 83
Linux64 Slackware 14.2

With option in FF "privacy.resistFingerprinting"  uBlock  not enable custom  "green rule" with crtl+click .
Only available rules are grey or red.

**Comment by uBlock-user** [comment]
In some browser versions[1], double-tapping the Ctrl key does not work, in such case you can recover the ability to create allow rules by changing the advanced setting filterAuthorMode to true.

[1] Tor Browser; Firefox with `privacy.resistFingerprinting` set to `true`.

https://github.com/gorhill/uBlock/releases/tag/1.28.0
