### ISSUE TITLE
Cloud storage banner in settings appears almost completely white

### ISSUE THREAD

**Issue by polygonnedpotato** [uBlockOrigin/uBlock-issues#1389]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behaviour

### Description

[Description of the bug or feature]
The cloud storage bannershows up with white fonts in dark mode

![image](https://user-images.githubusercontent.com/73083772/101393917-a9c08a00-387c-11eb-93c2-fd295271cda0.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
open settings
2. [Second Step]
Check "I am an advanced user" and set "uitheme" to "dark" and hit apply changes
3. [and so on...]
open "Filter lists", "My filters", "My rules", or "Trusted sites".

### Expected behaviour:
the banner should show up with a dark background
[What you expected to happen]

### Actual behaviour:
the banner shows up with white font and background
[What actually happened]

### Your environment

* uBlock Origin version: 1.31.2
* Browser Name and version: Chrome 86.0.4240.199
* Operating System and version: Chrome OS (64-bit) 86.0.4240.199

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Advanced-settings#uitheme>:

> For development purposes only! DO NOT create issues about this feature!

Since asking people to not file issue does not work, I will disable the setting to prevent such invalid issue.
