### ISSUE TITLE
Blocking specific scripts

### ISSUE THREAD

**Issue by life777eternal** [uBlockOrigin/uBlock-issues#1390]
Hello, is there any way to allow specific scripts, without disabling for the whole domain? 

### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Some scripts have red beside them and some have green by default, the ones with green are the ones allowed, right? And the ones with red are blocked?  How do I make one script URL unblocked without disabling the extension for the whole site? 

### A specific URL where the issue occurs

Doesn't matter what page you're on, every page has some scripts, usually.

### Steps to Reproduce

1. Open a page like https://grid.toallchurches.net
2. Click on the Puzzle Icon, then the pin beside uBlockOrigin, click on the uBlockOrigin icon, then click on More. 
3. From here I don't see how to allow/disallow the sites shown on the left of the uBlock Origin popup.

### Expected behavior:

Something like the NoScript extension, which doesn't actually show all the URL's that uBlock Origin shows.

### Actual behavior:

Only disabling uBlock Origin for individual sites is currently possible, which allows all scripts on the site, though that's not ideal.

### Your environment

* uBlock Origin version: v1.31.0
* Browser Name and version: Chromium Version 86.0.4227.0 (Developer Build) (64-bit)
* Operating System and version: Windows Server 2008 R2

**Comment by gorhill** [comment]
This is not an issue, this is a support question, redpect the template please.

**Comment by life777eternal** [comment]
Alright, how do I delete this then?
