### ISSUE TITLE
[Firefox] Opening uBlock 'Release Notes' tab in Firefox about:addons displays incorrectly.

### ISSUE THREAD

**Issue by gettysburg** [uBlockOrigin/uBlock-issues#1391]
### Prerequisites

- [X] I verified that this is not a filter issue
- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox has the ability to display a changelog on it's about:addons page, by selecting an installed add-on, then clicking the 'Release Notes' tab.

### A specific URL where the issue occurs

about:addons

### Steps to Reproduce

1. Open about:addons.
2. Click on uBlock Origin.
3. Click the 'Release Notes' sub-tab.

### Expected behavior:
I expect a nice change-log as seen with other add-ons, for example (HTTPS Everywhere):

![example2](https://user-images.githubusercontent.com/2256003/101621287-795c2580-3a0d-11eb-8210-9cb46f97c1ad.PNG)

### Actual behavior:
GitHub's uBlock Origin /releases HTML page loads instead, forcing the user to scroll down to get any sort of valuable information's on changes.

![example1](https://user-images.githubusercontent.com/2256003/101621590-dd7ee980-3a0d-11eb-8a75-acf47e8416e6.PNG)

### Your environment

* uBlock Origin version: 1.31.3b5
* Browser Name and version: Firefox 83.0
* Operating System and version: Windows Server 2019 / LTSC Kernel 1809 17763.1613

**Comment by gorhill** [comment]
The release notes link has been removed.

**Comment by gettysburg** [comment]
Does removing the URL actually lead to displaying a correct change-log? Not familiar with Firefox addons, I'm more of a C/C++ low level programming guy, never messed with addons.

Sorry for the question. :-P

**Comment by gwarser** [comment]
Stable build still have it provided by add-on stores. For dev builds you can subscribe to GitHub releases.

**Comment by gorhill** [comment]
> not exactly a perfect solution

Sure, but if the release notes that were there are deemed to be an issue, removing them is what I can do, I will not add yet another maintenance burden to my plate.

**Comment by gettysburg** [comment]
@gwarser Ah, alright - that explains everything.
@gorhill Understandable.

Thanks everyone.
