### ISSUE TITLE
:watch-attr() stopped working

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1392]
<details>
<summary>Details</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

https://github.com/MajkiIT/polish-ads-filter/issues/18147#issuecomment-742496245

Does not work on test page: https://ameshkov.github.io/web/watchattr.html

### A specific URL where the issue occurs

https://ameshkov.github.io/web/watchattr.html

### Steps to Reproduce

1. Add `ameshkov.github.io###testdiv:watch-attr(id):has(p)`
2. Visit https://ameshkov.github.io/web/watchattr.html
3. Click on button

### Expected behavior:

Element should appear/disapper after click on button

### Actual behavior:

Element does not appear

### Your environment

* uBlock Origin version: bisected
* Browser Name and version: Firefox Nightly, Chrome 87.0.4280.88
* Operating System and version: Manjaro KDE

### Notes

Broken in 1.29.3.9

	[rdk@on uBlock-git]$ git bisect bad && ./tools/make-chromium.sh 
	35aefed92616cbfb75f12f37c7ea7fb3a3cc3369 is the first bad commit
	commit 35aefed92616cbfb75f12f37c7ea7fb3a3cc3369
	Author: Raymond Hill <rhill@raymondhill.net>
	Date:   Mon Sep 7 08:28:01 2020 -0400
	
	    Add support to chain `:style()` to procedural operators
	    
	    Related issue:
	    - https://github.com/uBlockOrigin/uBlock-issues/issues/382
	    
	    Additionally, remnant code for pseudo-user stylesheets
	    has been removed. Related commit:
	    - https://github.com/gorhill/uBlock/commit/5c68867b92735931a791dfedf4ef9608cc364862
	
	 platform/chromium/vapi-background.js     |  23 ++-
	 platform/chromium/vapi-client.js         |   8 +-
	 src/js/background.js                     |   4 +-
	 src/js/contentscript.js                  | 278 ++++++++++++-------------------
	 src/js/cosmetic-filtering.js             | 167 ++++++-------------
	 src/js/epicker-ui.js                     |  17 +-
	 src/js/scriptlets/cosmetic-logger.js     |   6 +-
	 src/js/scriptlets/dom-inspector.js       |  23 ++-
	 src/js/scriptlets/dom-survey-elements.js |   4 +-
	 src/js/scriptlets/epicker.js             | 180 ++++++--------------
	 src/js/static-filtering-parser.js        |  43 +++--
	 11 files changed, 281 insertions(+), 472 deletions(-)
	*** uBlock0.chromium: Creating web store package
	*** uBlock0.chromium: copying common files
	*** Packaging assets in dist/build/uBlock0.chromium/assets... rm: cannot remove 'dist/build/uBlock0.chromium/assets/ublock/resources.txt': No such file or directory
	done.
	*** uBlock0.chromium: Generating meta...
	*** uBlock0.chromium: Package done.
	[rdk@on uBlock-git]$

**Comment by gorhill** [comment]
This was causing a regression not only for `:watch-attr` but also for any case of elements no longer matching any procedural filters.

**Comment by gorhill** [comment]
Now the question: is it a case of emergency fix for a 1.31.4 release?

**Comment by krystian3w** [comment]
Maybe just disable for few weeks this filter: https://github.com/uBlockOrigin/uAssets/commit/6b78f437aeedcee01df6c17e3630a63ea366b84c

**Comment by gwarser** [comment]
It's surprising it was broken for so long and no one noticed.

Is it still broken for normal "elements" case? https://gwarser.github.io/web/watchattr.html

**Comment by gwarser** [comment]
What the... It works if I click on second test button and then on first test button.

**Comment by krystian3w** [comment]
Yeah, works as you wrote.

Maybe similar: uBo DOM inspector sometimes lie what element is hidden: https://github.com/MajkiIT/polish-ads-filter/issues/18146#issuecomment-742519809 - on fast PC procedural filters stock on loaded  `#body-wrapper` (visible hidding by only devtools).

**Comment by gorhill** [comment]
Yeah, I see the filterer is not informed of removed nodes, I will have to figure out why this changed. It seems the DOM watcher's code was modified and this broke reporting of removed DOM nodes.
