### ISSUE TITLE
Non-hiding (placeholding-only) cosmetic filters, and binding filters to specific websites

### ISSUE THREAD

**Issue by SoniEx2** [uBlockOrigin/uBlock-issues#1394]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [N/A] uBlock Origin is the only extension
    - [N/A] uBlock Origin with default lists/settings
    - [N/A] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [N/A] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Blocktogether is gone. It was never a good idea, anyway. We'd like to use uBlock Origin to replace Blocktogether, but one small issue with uBlock Origin is that the filter list has pretty much full control over what uBlock Origin does. It'd be appreciated to have an option that says "Use placeholder instead of hiding elements" when subscribing to a list.

The idea is to provide accountability - it's a lot easier to hold blocklist creators accountable when you can easily see that stuff is getting blocked. At the very least you'd see when your friends are replying to blocked stuff and be able to act accordingly, which was simply impossible with Blocktogether.

### A specific URL where the issue occurs

https://twitter.com/

### Steps to Reproduce

1. Make a malicious filter list
2. Get others to use it

### Expected behavior:

Being able to control how much a filter list may affect websites.

### Actual behavior:

Filter lists take that control away from the user. A filter list could go malicious at any time and the user wouldn't be able to tell.

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Firefox 83.0
* Operating System and version: Arch Linux x86_64

**Comment by gwarser** [comment]
You can disable "Hide placeholders of blocked elements" and Cosmetic Filtering.

**Comment by SoniEx2** [comment]
That's not per-list, tho.

**Comment by gwarser** [comment]
> That's not per-list, tho.

Per-list modifications are not compatible with uBO engine.
