### ISSUE TITLE
关于元素提取

### ISSUE THREAD

**Issue by yang7951** [uBlockOrigin/uBlock-issues#1395]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by yang7951** [comment]
你好作者，我一直再用你们的uBlockOrigin，他对于屏蔽广告功能来说已经很好了。我最近在找网页元素提的的软件，都不是很好，因为他们没有手动添加元素的功能，需要先学习相关计算机语言的内容才能使用，而你的插件可以手动添加元素并且把这个元素屏蔽掉，我想用的功能是手动添加元素并提取出来生成简易表格，因为我用到公司内部工作的网页，每个网页的格式基本相同但内容是有差别的，我需要复制其中的特定元素的文字用来填写邮件，每次都要反复切换网页进行查找、复制和粘贴，如果这个要求有通用性，希望你考虑一下。谢谢

**Comment by gorhill** [comment]
My understanding of Google Translate output is that what you want is way beyond uBO's scope.

**Comment by yang7951** [comment]
是的，很抱歉这个要求确实不符合他的主要功能，而且是刚好相反的功能

**Comment by Yuki2718** [comment]
Marginally related: https://github.com/AdguardTeam/AdguardFilters/pull/69608
But as AdamWr admitted, there's no actual case currently which can't be solved by existing solution.
