### ISSUE TITLE
Ubo popup displays blank on github

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#1398]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Ubo popup panel displays empty on github

### A specific URL where the issue occurs
Github.com

### Steps to Reproduce

1. Open Firefox and navigate to github, Github is is added to Trusted sites
2. open panel on the Ubo Icon
3. blank display

### Expected behavior:
Should display information and controls

### Actual behavior:
Displays blank, See image.
![Error On Github](https://i.postimg.cc/RCHLLLDB/errorubo.png)

### Your environment

* uBlock Origin version: 1.31.3b13 Default filters list plus my two personal list XPI and YahooComplete
* Browser Name and version: Firefox 84 RC
* Operating System and version: Windows 10 Enterprise 19042.685

**Comment by troysjanda** [comment]
Seems that removing it from the trusted sites restored the display. Not sure this is a bug or not. With Github listed is shows blank when removed from trusted sites is displays correctly.

**Comment by uBlock-user** [comment]
Is that a custom theme ? Did you change something with Firefox ?

**Comment by troysjanda** [comment]
It's material fox css it's hosted on github

**Comment by troysjanda** [comment]
I saw this bug on firefox as well https://bugzilla.mozilla.org/show_bug.cgi?id=1672139 might be related but supposed to be fixed in FF84.

**Comment by uBlock-user** [comment]
Disable that and try again?

**Comment by troysjanda** [comment]
If it was the material fox removing github from trusted sits would not fix
the issue

**Comment by gorhill** [comment]
I won't spent time investigating this -- because I doubt the issue is with uBO. I will let you whoever wants to spend time on this pinpoint where in uBO there faulty code causing this.

**Comment by troysjanda** [comment]
here is some debug info in console output, not sure its helpful or not
![error](https://i.postimg.cc/43Vdnn3p/uboerror.png)

**Comment by gwarser** [comment]
>1.31.3b13

Wondering if this can be related to latest tab-less changes.

**Comment by gwarser** [comment]
>Github is is added to Trusted sites

This is crucial. I can reproduce.

- have "restore previous session" pref enabled
- current page in view
- click power button in uBO popup
- close & reopen browser
    - uBO is still active on GitHub ?
- click power button again
- reload page
- close & reopen Firefox
- popup is blank


		01:01:18.837 Uncaught (in promise) TypeError: can't access property "length", hostname is undefined
		    setHostnameArg moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/lib/publicsuffixlist/publicsuffixlist.js:333
		    getDomain moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/lib/publicsuffixlist/publicsuffixlist.js:458
		    domainFromHostname moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/js/vapi-common.js:150
		    getHostnameDict moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/js/messaging.js:224
		    popupDataFromTabId moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/js/messaging.js:346
		    popupDataFromRequest moz-extension://180bc029-9c5e-4f9b-b7f5-820dbf607312/js/messaging.js:405
		publicsuffixlist.js:333:10


![image](https://user-images.githubusercontent.com/886325/102028521-f9d2ab80-3daa-11eb-850e-f578b037b584.png)

???

**Comment by gorhill** [comment]
I wasn't able to reproduce with the steps above but U can reproduce every time when I use the site given at <https://github.com/uBlockOrigin/uBlock-issues/issues/1204>:

- Navigate to `https://www.fotocasa.es/es/`
- Disable uBO for that site
- Close browser
- Open browser
- Let page load to completion
- Result: blank popup

Regression from <https://github.com/gorhill/uBlock/commit/6df32675b16b591313b40231583b4d06dda9e526>.

**Comment by gwarser** [comment]
GitHub did not had any tabless requests for me when tried in new profile. 

I tried again just few minutes ago on `https://forum.manjaro.org/` and bisected to https://github.com/gorhill/uBlock/commit/6df32675b16b591313b40231583b4d06dda9e526

Turn out I was right and deleted my previous message unnecessarily :facepalm: : 

> >1.31.3b13
> 
> Wondering if this can be related to latest tab-less changes.

**Comment by gorhill** [comment]
> Just reloading add-on from `about:debugging`

On my side, just navigating to `https://www.fotocasa.es/es/` in a new tab was enough. I didn't need to restart uBO.
