### ISSUE TITLE
When filters are removed from the list of filters included with uBO, they become stale and cannot be removed/deleted/updated

### ISSUE THREAD

**Issue by vgturtle127** [uBlockOrigin/uBlock-issues#14]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After a filter has been removed from the list by the uBLock Origin developer, it moves it to the custom part of the filter list. Once it is here, the list becomes stale. It won't update, can't be deleted or removed, and will stay on the position until a complete uninstall of the browser extension and deleting of all data related to the browser extension.

This issue also applies to Mozilla and other browsers that support uBlock Origin.

### A specific URL where the issue occurs

chrome-extension://*************************/dashboard.html

### Steps to Reproduce

1. Have a filter that has been removed from the main list by the developer after an update, and been moved to custom filters
2. Try to delete the filter
3. It crosses out the filter
4. Hit apply
5. It doesn't work
6. Try to disable the filter
7. Hit apply
8. Filter check box re-checks the box
9. Uninstall extension
10. Re-install extension
11. Still there

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3183676/39099249-f120baee-463c-11e8-8577-fe3392740d50.png)

![image](https://user-images.githubusercontent.com/3183676/39099240-c0851f24-463c-11e8-9004-89b44893a623.png)

![image](https://user-images.githubusercontent.com/3183676/39099243-daaaf61c-463c-11e8-91bb-ccc82f1825e2.png)

### Expected behavior:

The filter can be deleted, updated, or disabled at will.

### Actual behavior:

Malware filter list by Disconnect refuses to delete, update, or be disabled. The extension does not even remove the filter after uninstallation of the extension.

### Your environment

* uBlock Origin version: v1.15.24
* Browser Name and version: Chrome version 65.0.3325.181 (Official Build) (64-bit) (applies to all browsers, however, including newer versions of Chrome, Firefox, Opera, Vivaldi, etc.)
* Operating System and version: 64-bit Windows 10 version 1709 OS build 16299.309

**Comment by gorhill** [comment]
> Uninstall extension
> Re-install extension
> Still there

This makes no sense. Something is definitely wrong on your side, Chrome removes whatever storage used by an extension at removal time. There is something specific on your side causing this, this is not a uBO issue. For example, you could have set a file/directory permissions to read-only such that Chrome is unable to remove it.

You will have to investigate your issue on your side, you re best placed for this.

**Comment by vgturtle127** [comment]
@gorhill I checked permissions, that isn't the issue.

Thanks anyway.
