### ISSUE TITLE
Prevent pages from reloading/refreshing

### ISSUE THREAD

**Issue by mezysinc** [uBlockOrigin/uBlock-issues#1404]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Feature implementation

On firefox for android you can't access about:config anymore and tweak ff behavior.

Would it be possible to implement feature that prevents pages from reloading/refreshing.

### A specific URL where the issue occurs

www telesintese com br (legit website in ptbr)

### Steps to Reproduce

1. Go to the website above

2. Scroll through page 1 headlines to the end (as if you were reading it), then go to page 2, 3 ...

3. After some time (yes, I don't know exact time that have to pass to triggers it) the page will reload/refresh by itself ...

4. ... and redirect you back to the first page.

### Expected behavior:

I'd like ublock to block this behavior.

### Actual behavior:

Redirecting to the first page while you're on 2 or 3 one

### Your environment

* uBlock Origin version:1.31
* Browser Name and version:ff 84.1
* Operating System and version:9&10

**Comment by gorhill** [comment]
Just disable JavaScript by using the [no-scripting switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting) for that site.

**Comment by gwarser** [comment]
I see `<meta http-equiv="refresh" content="200" />`.

Maybe `www.telesintese.com.br##meta[http-equiv="refresh"]:remove()` will work.

**Comment by uBlock-user** [comment]
I think this issue fits in uAssets.

This is the cause behind those refreshes --

`<meta http-equiv="refresh" content="200" />`

In Firefox this can be fixed with `www.telesintese.com.br##^meta[http-equiv="refresh"]`

**Comment by gorhill** [comment]
> Maybe `www.telesintese.com.br##meta[http-equiv="refresh"]:remove()` will work.

Does not work, by the time the node is removed, the directive has already been parsed and interpreted as a header entry. Only a HTML filter will work, this is fine since OP is using Firefox.

Notice that I was not really motivated investigating this case because there was no disclosure of how long I should wait for the page to refresh, for all I know it could have been hours and there is no way I will spend hours of my time sitting here waiting for a refresh. There is no need for an exact figure, a ballpark one is fine, ~3 minutes is the information which should have been provided.

**Comment by mezysinc** [comment]
> There is no need for an exact figure, a ballpark one is fine, ~3 minutes is the information which should have been provided.

Well, so it happens approximately between 3:20min & 3:40min. Sorry for not providing that right away. Thanks
