### ISSUE TITLE
ADD ability to edit My filters for current site when clicking on uB icon in toolbar

### ISSUE THREAD

**Issue by allanlaal** [uBlockOrigin/uBlock-issues#1406]
### Prerequisites

- [+] I verified that this is not a filter issue

    
- [+] This is not a support issue or a question
 
- [+] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [+] I am running the latest version of uBlock Origin
- [+] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

there should be a way to edit site specific My filters in situ

### A specific URL where the issue occurs

any site with custom blocking (i.e. when using Pick or Zap)

### Steps to Reproduce

1. open https://github.com/uBlockOrigin/uBlock-issues
2. click on uBlock toolbar icon → Element zap mode
3. zap the issue list or github logo or whatever
4. optional: wait 1 minute/year/eon
4. see how much extra steps there are to undo that zap, especially if your My Filters rules list is mucho long

### Expected behavior:

When clicking on the uBlock icon in the toolbar, there are various buttons and stats including "Blocked on this page"
new feature: when clicking on that text (or an Edit (i.e. cogs) button next to it) uB should open a small textarea on the same window (using the same editor that "My filters" in general settings uses)
in that textarea then the user can delete their old Zaps and Blocks, or maybe even write new ones by hand 

### Actual behavior:

have to open general uB settings → go to My filters → search the rules for current site manually

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Firefox 84.0
* Operating System and version: Ubuntu Mate 20.10

**Comment by uBlock-user** [comment]
> Element zap mode

Zapper is temporary, refreshing the page reverses the zap.

**Comment by gorhill** [comment]
Declining this, I don't see myself spending ever more time on throwing ever more edge features that require a non-trivial amount of work..
