### ISSUE TITLE
GitHub dark mode makes whole page invisible when element picker is active

### ISSUE THREAD

**Issue by nyuszika7h** [uBlockOrigin/uBlock-issues#1408]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using the dark mode on GitHub, activating the element picker causes the entire page to become white.

### A specific URL where the issue occurs

https://github.com/

### Steps to Reproduce

1. Set theme to dark on https://github.com/settings/appearance
2. Open the uBlock Origin element picker
3. Move your mouse around the page

### Expected behavior:

The page's contents should remain visible.

### Actual behavior:

The whole page becomes white, although element bounds are shown when moving the mouse around.

### Your environment

* uBlock Origin version: 1.31.2
* Browser Name and version: Chrome 87.0.4280.88
* Operating System and version: Windows 10 20H2 (19042.685)

https://user-images.githubusercontent.com/482367/102782299-68aa9880-4399-11eb-8c01-402d142698df.mp4

**Comment by gorhill** [comment]
I can reproduce in Chromium 87.

**Comment by uBlock-user** [comment]
Specific to Chromium ? No issue with Firefox.

**Comment by gorhill** [comment]
The following CSS declaration is causing this:

    [data-color-mode=dark] {
        color-scheme:dark;
    }

I can't find any information about `color-scheme`, this looks like a Chromium-specific thing.

**Comment by uBlock-user** [comment]
Could this become a Firefox issue if `color-scheme` were to be implemented ?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2121
https://github.com/uBlockOrigin/uBlock-issues/issues/2062
https://github.com/uBlockOrigin/uBlock-issues/issues/1408

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2196
