### ISSUE TITLE
In the Logger, Add Column where the filter was located. Filter Source.

### ISSUE THREAD

**Issue by Nick-us** [uBlockOrigin/uBlock-issues#1409]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
In the Logger, Add Column where the filter was located. Filter Source.

This is very useful when using multiple filters or lists, and you are creating your own custom list!
If the Log quickly displayed in which list that filter was found, I will quickly know whether or not it is in My Filters, so I can decide whether to add it or not.

Using multiple lists from multiple places, we get thousands of repeated filters. That's why I like to bring to my list, only what I use in my country, making my list much smaller and faster to execute.

Allowing me to check extra lists only if I need to.
The Old one, very old, AdBlock Plus had this option, its LOG was even better, since it shared the screen with the Site.

But I'm just asking for a small inclusion of the Filter Source Column in the uBlock Origin Logger.

Currently to see which filter source it is, it is necessary to click on each blocked filter to see, which is not practical when the site has many blocks

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:
[What you expected to happen]

### Actual behavior:
[What actually happened]
Currently to see which filter source it is, it is necessary to click on each blocked filter to see, which is not practical when the site has many blocks

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> Currently to see which filter source it is, it is necessary to click on each blocked filter to see, which is not practical when the site has many blocks

By-design, to avoid any performance issues stemming from what you'r suggesting.

**Comment by gorhill** [comment]
Duolicate of #842.
