### ISSUE TITLE
Conflict with Stylus extension: when enabling DOM Inspector, the target page becomes empty if having a userstyle active 

### ISSUE THREAD

**Issue by darkred** [uBlockOrigin/uBlock-issues#1411]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The issue is that there's a conflict with Stylus extension:
on github pages, when you have installed a relevant style in Stylus, 
if you enable the DOM Inspector in uBO's logger, then the GitHub page becomes empty.

*Regarding Stylus, kindly cc'ing:  @tophf and @narcolepticinsomniac .*

### A specific URL where the issue occurs

https://github.com/

### Steps to Reproduce

1. Make a fresh Chrome 87/Firefox 84 profile, 
2. install uBO 1.32.1.0/1.32.1b0 and Stylus 1.5.14 beta/1.5.13 stable respectively
3. Follow this link to install this userstyle in Stylus [GitHub-Dark](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css) ([repo](https://github.com/StylishThemes/GitHub-Dark))
4. Open uBO's logger and load https://github.com/ in a new tab
5. Now switch to the logger and enable uBO's DOM Inspector (the DOM Inspector itself works ok: [screenshot](https://user-images.githubusercontent.com/723651/102905445-d4653200-447b-11eb-9f65-0cf2cadd4e78.jpg) ).  
Finally switch back to the github.com 

### Expected behavior:

The github page should be displayed ok.

### Actual behavior:

The github page is "empty", having only the userstyle's background:
![](https://user-images.githubusercontent.com/723651/102902578-ddec9b00-4477-11eb-8335-f60e7d4c3b02.jpg)
The issue is fixed if you disable the userstyle via Stylus toolbar menu:  
then the page is immediately displayed properly again:
![2020-12-22_172421](https://user-images.githubusercontent.com/723651/102904570-93b8e900-447a-11eb-908c-d0d8299fe57b.jpg)

### Your environment

* uBlock Origin version: 1.32.1.0 / 1.32.1b0 
* Browser Name and version: Chrome 87 / Firefox 84
* Operating System and version: win10 x64

**Comment by tophf** [comment]
The problem is that Stylus adds style elements inside the iframe as the frame's address matches the main page URL. I guess Stylus should detect and avoid styling this iframe?

**Comment by tophf** [comment]
Another solution would be for uBlock Origin: make the iframe's contents untouchable by pointing `src` to a page exposed via web_accessible_resources so that it'd be a chrome-extension:// URL that no other extension would be able to inject normally (without the user explicitly adding a special command line switch).

**Comment by gorhill** [comment]
> make the iframe's contents untouchable

Yes, it's what I did for the element picker, I need to do this also for the DOM inspector.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2196

**Comment by JobcenterTycoon** [comment]
But now every site gets blank when i use the dom inspector (tested on Firefox).

**Comment by gorhill** [comment]
That's not something I can reproduce. Please use the inspector to find out what CSS rule is causing this. The DOM inspector now uses the same mechanism as the picker, so it should work as well.

**Comment by JobcenterTycoon** [comment]
Its on all sites. Even when i do this on `http://example.com/` the site blanks out. In the browser inspector i see its caused by the uBO iframe

<img width="330" alt="css" src="https://github.com/uBlockOrigin/uBlock-issues/assets/48647394/193bc9f7-a7ce-4cfd-ae90-91349d4cb106">

<img width="554" alt="iframe" src="https://github.com/uBlockOrigin/uBlock-issues/assets/48647394/614f71f1-ddfc-454e-9b01-d50e289c92cb">

**Comment by gwarser** [comment]
Works for me in Firefox 120 on Windows and 122 on Linux. Did you change something about svg in about:config? Firefox had issues with some filters applied to svg before.

**Comment by JobcenterTycoon** [comment]
No, all default. I tried the latest dev build in chrome now, same result. A white blank page while the picker works fine.

No issues with 1.54.0.

**Comment by gwarser** [comment]
I see one issue. If I open Inspector for this page in Chrome 119.0.6045.200 and 120.0.6099.63, then navigate to `example.com`, the page selector shows the new page, but the DOM tree in inspector does not update.

**Comment by gorhill** [comment]
> in chrome now, same result

Look, trying to show as much of all I see (i.e. no cropping out other information):

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/82bfb991-facd-4a65-ab41-f07a961c76eb)

If `example.org` is all white, then the goal is to find which CSS style is causing this.

**Comment by JobcenterTycoon** [comment]
<img width="1141" alt="picture" src="https://github.com/uBlockOrigin/uBlock-issues/assets/48647394/f90a0b18-b54d-4f9d-8d38-e4799fb61345">

**Comment by gorhill** [comment]
Maybe because the `<meta name="color-scheme" content="light dark">` line is missing in `dom-inspector.html`?

**Comment by JobcenterTycoon** [comment]
It works when i insert this with firefox dev tools into the iframe HTML.
