### ISSUE TITLE
Request uShield

### ISSUE THREAD

**Issue by v00v** [uBlockOrigin/uBlock-issues#1413]
I love uBlock and uMatrix plugins, but it would be cool to see this two combined and maybe called something like uShield for those of us who like to use both at same time. This way it will allow you to create more integrated options from two plugins and make it one nice all-in-one protection for those of us who care about security. You can still do uBlock seperately for those who do not like to use uMatrix plugin, and with uShield you can combine the two :-) Anyway, just an idea... but could be very useful. Thank you for all the hard work you put into this plugins. Without uBlock/uMatrix internet is simply unusable today.

**Comment by uBlock-user** [comment]
> I love uBlock and uMatrix plugins, but it would be cool to see this two combined and maybe called something like uShield

They used to be combined before they were split up into individual projects : HTTPSwitchBoard.
