### ISSUE TITLE
Ublock settings require clipboard events to use Primary Selection

### ISSUE THREAD

**Issue by haarp** [uBlockOrigin/uBlock-issues#1417]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock's settings dialog, e.g. the `My filters` box will not use the Primary Selection when clipboard events are disabled in the browser (e.g. `dom.event.clipboardevents.enabled` set to false in Firefox). This means that using the middle mouse button to paste the selection under X11 will not work, nor will selections enter the same buffer.

Why would one disable clipboard events? on Linux X11, sites can hijack the middle mouse button to spy on selection contents. Try it out by middle-clicking on an emtpy spot on the main page of imgur.com! You'll see an "URL failed to upload" dialog.

### A specific URL where the issue occurs

moz-extension://37692a94-45d7-496b-82fe-e52f6649b801/dashboard.html#1p-filters.html

### Steps to Reproduce

1. In Firefox, go to `about:config` and set `dom.event.clipboardevents.enabled` to false.
2. Enter Ublock's settings, My filters and try to use middle-click pasting

### Expected behavior:

Primary selection should work, regardless of clipboard events being disabled. Other extension do not rely on these. And as explained above, there's a very good reason to disable them.

### Actual behavior:

No primary selection support, middle-click pasting broken.

### Your environment

* uBlock Origin version: 1.32.0
* Browser Name and version: Firefox 83
* Operating System and version: Gentoo Linux X11

Thank you!

**Comment by uBlock-user** [comment]
uBO relies on CodeMirror which relies on clipboard events.

**Comment by gorhill** [comment]
This is a CodeMirror behavior. Maybe related to <https://github.com/codemirror/CodeMirror/issues/5754>.

**Comment by haarp** [comment]
You are correct. I asked the CM maintainers, there seems to be nothing they can do about it. codemirror/CodeMirror#6538

Cheers!

**Comment by gwarser** [comment]
You can turn clipboardevents back on, and turn off `m`iddlemouse.paste`.
