### ISSUE TITLE
Firefox add-on homepage

### ISSUE THREAD

**Issue by sKopheK** [uBlockOrigin/uBlock-issues#1418]
Should not homepage in the add-on details lead to this repo instead of [uBlock](https://github.com/gorhill/uBlock) one where user is redirected to this repo in the issues section?
![image](https://user-images.githubusercontent.com/5802917/103150277-76ca3180-476a-11eb-8da9-3ca27d6fe6d9.png)

**Comment by gorhill** [comment]
No, the official homepage is really <https://github.com/gorhill/uBlock>, here is just to report issues.
