### ISSUE TITLE
Using an alias for custom scriptlet in my Filters pane is seen as invalid

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#1419]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As above.

### A specific URL where the issue occurs

myFilters pane

### Steps to Reproduce

- Set `userResourcesLocation` to `https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.js`

- Navigate to my Filters and type/add, `example.com##+js(noaif)`

- uBO sees the alias as invalid -- 
![Capture](https://user-images.githubusercontent.com/21290713/103171290-107c0680-4871-11eb-8e25-746bfb4bf4ba.PNG)

### Expected behavior:

Alias shouldn't be seen as invalid.

### Actual behavior:

Alias is seen as invalid

### Your environment

* uBlock Origin version: 1.32.3b1/1.32.0
* Browser Name and version: Firefox 84/86
* Operating System and version: Win X

**Comment by uBlock-user** [comment]
Addendum: Any scriptlet which is the `last one` in the `userResourcesLocation` URL will have its alias seen as invalid by uBO.

Regressed by https://github.com/gorhill/uBlock/commit/24755d4300f9e8f5c32a3c965c98de13ab26a6f4 ?

**Comment by gwarser** [comment]
You need to put at least two new lines at the end of the resource file, or even better some comment to be sure these lines are here. Otherwise section after last `continue` is skipped, loop is not executed one more time because this is already `eot()` (maybe `this.offset = lineEnd + 1;` is set to soon in `LineIterator`?):

https://github.com/gorhill/uBlock/blob/1d2907890bedafa39488ecc3fcb688f850374242/src/js/redirect-engine.js#L396-L419

**Comment by uBlock-user** [comment]
Is this a new change with 1.32.0 ? Not seeing this happening with 1.31.0.

**Comment by gwarser** [comment]
Ah, just after the `while` loop code is not updated after https://github.com/gorhill/uBlock/commit/24755d4300f9e8f5c32a3c965c98de13ab26a6f4 : 

https://github.com/gorhill/uBlock/blob/1d2907890bedafa39488ecc3fcb688f850374242/src/js/redirect-engine.js#L423-L435

**Comment by uBlock-user** [comment]
Added a new line and it works now..until gorhill addresses it.

**Comment by gorhill** [comment]
I just need to append two newlines to the raw text so that I can drop that redundant block outside the loop.
