### ISSUE TITLE
Unchecked "I am an advanced user" - Dynamic Filter Still Appears

### ISSUE THREAD

**Issue by 0pLuS0** [uBlockOrigin/uBlock-issues#142]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When unchecking ```I am an advanced user``` the ```Dynamic Filter``` still appears on the left side.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
I checked ```I am an advanced user``` 
2. [Second Step]
I unchecked ```I am an advanced user``` 
3. [and so on...]

### Expected behavior:

[What you expected to happen]

After unchecking ```I am an advanced user``` I expected the ```Dynamic Filter``` to be gone.

### Actual behavior:

[What actually happened]

It still appeared on the left side.

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Firefox ESR 52.9.0
* Operating System and version: Slackware 14.2 x64

Checked ```I am an advanced user```, this is how I assumed the UI looks;

![df](https://user-images.githubusercontent.com/36190223/43052945-705402a2-8e19-11e8-987e-32c60bfcd0d8.jpg)

Unchecked ```I am an advanced user```, this is how I assumed the UI now goes back to the default look;

![uc](https://user-images.githubusercontent.com/36190223/43052956-88c7de62-8e19-11e8-9f50-3632ade24dda.jpg)

**Comment by gorhill** [comment]
> - [x] I checked the documentation to understand that the issue I report is not a normal behavior

[Documentation](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel):

> To hide that panel, just click again on either the "requests blocked" or "domains connected" label.
>
> Unless you are in "advanced user" mode, this panel is read-only and available only for informational purpose.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface/_compare/ff20a49b6fefce55d89387a0945bfd3eeeae2504

**Comment by 0pLuS0** [comment]
Sorry I overlooked all this... :(
