### ISSUE TITLE
Sir, Please Add A "Video AutoPlay Blocker" Option

### ISSUE THREAD

**Issue by Mr-Snow-Skull** [uBlockOrigin/uBlock-issues#1421]
### Description

Sir, Please Add A "Video AutoPlay Blocker" Option , 
      In Chrome It Is Very Frustrated Life Without A Extra Video AutoPlay Blocker Extension So If You Kindly Add This Option We 
      All Unblockians Users Will Be Very ThankFul To You Sir.
      So We Get All Features Packed in One Place & Don't Need Use A Extra Video AutoPlay Blocker Extension.

**Comment by gorhill** [comment]
Declined, the request is completely devoid of actual cases, and the template was removed.
