### ISSUE TITLE
correctly identify base domains of CDN/cloud servers in "My Rules" pane

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uBlock-issues#1423]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Filter sorting in the "My Rules" pane is hugely improved since https://github.com/gorhill/uBlock/commit/d87a3b950f75309ddb83252bf850fbf75af2776c – thank you! However, I notice that some URLs are not sorting correctly. They all seem to be CDN/cloud servers – see examples under the STR below.

### A specific URL where the issue occurs

n/a

### Steps to Reproduce
Install uB0 on a fresh browser profile, add the following dynamic filters, and sort them by source:

* `* s3.amazonaws.com * noop`
* `* 1400385617.rsc.cdn77.org * noop`
* `* d1zokzhal29fpg.cloudfront.net * noop`
* `* pal3.us-west-2.elasticbeanstalk.com * noop`
* `* map.fastly.net * noop`
* `* ajax.googleapis.com * noop`
* `* lib.sinaapp.com * noop`

### Expected behavior:

After sorting, I would expect the filters to remain in the order listed above.

### Actual behavior:

The filters appear in this order:

* `* 1400385617.rsc.cdn77.org * noop`
* `* ajax.googleapis.com * noop`
* `* d1zokzhal29fpg.cloudfront.net * noop`
* `* lib.sinaapp.com * noop`
* `* map.fastly.net * noop`
* `* pal3.us-west-2.elasticbeanstalk.com * noop`
* `* s3.amazonaws.com * noop`

### Your environment

* uBlock Origin version: 1.32.0
* Browser Name and version: Firefox 84.0.1
* Operating System and version: macOS 10.12.6

**Comment by gothic-bum** [comment]
This issue was also reported on:
[https://old.reddit.com/r/uBlockOrigin/comments/kj9kcw/incorrect_sorting_in_the_my_rules_settings_pane/](url)

In the comments, there is a good suggestion to allow the user to choose their preferred sorting order:

_"having an option for the user to choose their preferred sorting order (e.g. TLD, eTLD, first character) would be very helpful for readability."_

_"this isn't about the pros/cons of choosing one sorting method over another, since there isn't a single sorting method that is optimal or appropriate in all cases. Rather it is about allowing the user to choose the sorting method that is most useful/readable/logical to them."_

**Comment by practik** [comment]
@gothic-bum Thanks for linking that Reddit discussion. I didn't realize that `googleapis.com` etc. were actually TLDs, but I checked https://publicsuffix.org/list/public_suffix_list.dat and I see that gwarser is indeed correct. That means this issue is technically invalid, and since it wasn't a very major issue anyway to my mind, I'm closing it now.
