### ISSUE TITLE
Add AdGuard's noopvmap-1.0 equivalent as a redirect resource

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1425]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

AdGuard Japanese addressed https://github.com/AdguardTeam/AdguardFilters/issues/70829 by redirecting XHR to noopvmap-1.0, which indeed works. uBO doesn't have a counterpart so only way to fix this is allowing the request - redirecting to other resources such as noop.txt doesn't work. To be fair, allowing the request doesn't bring actual ads and uBO version of AG Japanese doesn't include the redirect filter so it's not a serious problem but a suggestion.

### A specific URL where the issue occurs

`https://tver.jp/corner/f0064327` (geo-locked)

### Steps to Reproduce

1. Visit the site using Japanese VPN with uBO and AdGuard (Chromium extension) each.
2. If you get a modal, close by clicking upper-right X button (or "あとで" on bottom).
3. Play the video and see AG solution works on AG. No breakage on uBO too as both uBlock Unbreak and AGJPN has whitelist, but if you badfiltered them the player doesn't work. Redirecting to other resources doesn't work either.

### Expected behavior:

AG Japanese' redirect works on uBO too.

### Actual behavior:

Doesn't work.

### Your environment

* uBlock Origin version: 1.32.0
* Browser Name and version: Firefox 84.0.1/Brave 1.18.75
* Operating System and version: Windows 10

### Note

I'll remove the whitelist from Unbreak. If this suggestion is accepted and the resource is added, I can make PR on AG for them to include uBO for the target of the redirect filter.

Related:
https://github.com/uBlockOrigin/uBlock-issues/issues/1366#issuecomment-741779134
https://github.com/AdguardTeam/Scriptlets/issues/52

**Comment by gwarser** [comment]
https://github.com/AdguardTeam/Scriptlets/blob/bc5eec198903856413e3e114a1d636c34146173d/src/redirects/static-redirects.yml#L134

Basically:

    <vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0"></vmap:VMAP>

**Comment by Yuki2718** [comment]
Of note, AG Base has 2 filters redirecting to this. They excludes uBO.
```
!+ NOT_PLATFORM(ext_ff, ext_ublock)
||v.fwmrm.net/ad/g/1?resp=$xmlhttprequest,redirect=noopvmap-1.0,domain=viafree.dk,important
!+ NOT_PLATFORM(ext_ublock)
||api.jtbc.joins.com/ad/vmap/*$xmlhttprequest,redirect=noopvmap-1.0,domain=tv.jtbc.joins.com,important
```

**Comment by uBlock-user** [comment]
They also have [noopvast](https://github.com/AdguardTeam/Scriptlets/blob/bc5eec198903856413e3e114a1d636c34146173d/src/redirects/static-redirects.yml#L146), what does that help fix ?

**Comment by gorhill** [comment]
I could not test that it works, feedback about this is welcome.

**Comment by Yuki2718** [comment]
I'll test tomorrow.

**Comment by Yuki2718** [comment]
Working fine on Chrome:

<details>

![tver](https://user-images.githubusercontent.com/58900598/103341578-a9f22500-4aca-11eb-8bc0-a3b6667b5c45.png)

</details>


So there must be reason that AG guys excluded Firefox. Maybe we can add Firefox-specific whitelist in Unbreak, but then the benefit of this resource will be halved - only for Chromium.

**Comment by uBlock-user** [comment]
on `viafree.dk` CORS is preventing `data:` resources from getting loaded on Firefox.

**Comment by Yuki2718** [comment]
> They also have [noopvast](https://github.com/AdguardTeam/Scriptlets/blob/bc5eec198903856413e3e114a1d636c34146173d/src/redirects/static-redirects.yml#L146), what does that help fix ?

On `https://funny-ai.com/result_46133611` after you upload a photo and then clicked "ランキングを見る" button, I confirmed `||serving.stat-rock.com/v1/placements/$xmlhttprequest,domain=funny-ai.com,redirect=noopvast-3.0` can be used instead of an exception and media redirect I added in https://github.com/AdguardTeam/AdguardFilters/commit/04aca9708f3e04f5677e11dab5b57fc6889a201f noopvast works but shows error so I didn't added the rule even for AG just in case, but this can be used as a real case to test.

![error](https://github.com/uBlockOrigin/uBlock-issues/assets/58900598/f409d99b-d29e-499b-bbb2-b76fd523e3e4)

**Comment by Yuki2718** [comment]
Fully fixed with https://github.com/gorhill/uBlock/commit/59a9a43a83202111ef2a786e1d4c3638185f99ec
