### ISSUE TITLE
uMatrix Dead?

### ISSUE THREAD

**Issue by v00v** [uBlockOrigin/uBlock-issues#1427]
Is uMatrix still been develped? I noticed its now been Archived. [1] [2]

[1] https://github.com/gorhill/uMatrix
[2] https://github.com/uBlockOrigin/uMatrix-issues

**Comment by v00v** [comment]
Do you mind explaining why the question is invalid?

**Comment by ChiefMikeK** [comment]
Questions/discussions are valid on [Reddit](https://www.reddit.com/r/uBlockOrigin/)  not in bug/issue -reports  
  Please **search** for answers first over there 💯
