### ISSUE TITLE
Canvas Blocker - Browser Fingerprint Protection

### ISSUE THREAD

**Issue by v00v** [uBlockOrigin/uBlock-issues#1428]
Can you add some sort of browser fingerprint protection to uMatrix or uBlock?

**Comment by Yuki2718** [comment]
You ignored template, if you didn't and had searched in past issues you'd find there were many similar requests which were declined - uBO is NOT an anti-fingerprinting tool despite it blocks many fingerprint as a result of contents blocking which is what uBO is for.

**Comment by gorhill** [comment]
This is your history of filed issues: https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+author%3Av00v+is%3Aclosed

If you keep ignoring the template, I will have to take steps for this to no longer happen.

**Comment by uBlock-user** [comment]
Classic example of being oblivious and doing "drive-by" requests.
