### ISSUE TITLE
selctor unpossible on Firefox support forum

### ISSUE THREAD

**Issue by securingmom** [uBlockOrigin/uBlock-issues#1429]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

Neither the pen nor bolt invokes an element picker

### A specific URL where the issue occurs

https://support.mozilla.org/en-US/questions/firefox?show=all

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. load that site
2. click toolbar icon ubo
3. click picker

### Expected behavior:

interactive element picker

### Actual behavior:

the button clicks
no element picker

### Your environment

* uBlock Origin version: 1.32.2
* Browser Name and version: Waterfox G3.0.2. (firefox CP)
* Operating System and version: MacOS 10.15.7
* MacBook Pro 16 i9 64gigs ram

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Privileged-Pages

**Comment by securingmom** [comment]
Goodness, that is creepy of Mozilla which is not much unlike their hypocrisy on privacy or hypocrisy on transparency.

Thank you for the enlightenment 👍
