### ISSUE TITLE
Revisiting element picker and about:blank styles on Firefox

### ISSUE THREAD

**Issue by Fyren** [uBlockOrigin/uBlock-issues#143]
I ran into the same problem others did regarding having a style applied to about:blank in Firefox making the picker/zapper unusable.  Only after figuring out the cause myself was I able to actually find https://github.com/uBlock-LLC/uBlock/issues/806 (adding "about:blank" to my searches made all the difference).  

gorhill commented the following in the linked issue:
> So anyways, the issue was with about:blank customization, something out of control of uBlock. Right?

Customization of about:blank is out of uBlock's control, but using about:blank is not.  As far as I can tell, the `src`less iframe the picker creates is the reason about:blank gets used, but I don't think that's necessary.  I don't know what the best method is, but adding `rootPicker,srcdoc = "";` after creating the iframe (https://github.com/gorhill/uBlock/blob/master/src/js/scriptlets/element-picker.js#L1608) seemed to have no impact except ending up with my about:blank style not applied.  I also tried a data URI for src instead, but that appeared to break the picker, but perhaps I crafted the data URI incorrectly.  I only tested on Firefox nightly.

Can something like this be added if there's no regression caused by it?  I think having about:blank styles applied to the picker is extremely unintuitive and difficult to diagnose, so this would prevent at least a small number of users some pain.

**Comment by uBlock-user** [comment]
Is this a suggestion or a question ?

**Comment by Fyren** [comment]
It's not-a-PR since I didn't want to create one out of the blue.  Maybe that makes it a suggestion.

**Comment by Fyren** [comment]
The CSS rule suggested in the issue this is marked as a dupe of requires the user knows what the problem is in the first place.  The one-liner code change I gave does not, but I don't know if it would inadvertantly break anything.

**Comment by Fyren** [comment]
I'm on nightly, as mentioned in my original comment.  If you left click on the addon button you get something like this: https://github.com/gorhill/uBlock/blob/master/doc/img/df-qg-01.png

**Comment by uBlock-user** [comment]
> If you left click on the addon button you get something like this

Not on `about:blank`, you don't. Also that's the outdated version of uBO, no longer valid.

This is it how it is now -

![](https://i.imgur.com/LHf6NLU.png)

**Comment by Fyren** [comment]
The problem is not about using the picker on about:blank, it's that if you use the picker _anywhere_ the style you have set on about:blank applies to the picker.

**Comment by Fyren** [comment]
To try to clarify, that's why I don't think someone will realize they need to use the given CSS rule.  They probably won't realize the about:blank style has anything to do with uBlock's picker at all.  The suggested change makes it so uBlock's picker doesn't end up being considered about:blank.

**Comment by uBlock-user** [comment]
Whether to add that suggested change of yours is upto gorhill.

**Comment by gwarser** [comment]
Seems to work, but custom style is flashing for a moment.

**Comment by gorhill** [comment]
Please provide the exact user CSS you are using, and in which file, so that I can reproduce your exact issue on my side. If I remember correctly uBO uses user styles to enforce the picker styles, so I need a repro case to investigate. The duplicate issue above was probably when user styles were not used by uBO.

**Comment by Fyren** [comment]
I had `@-moz-document url-prefix(about:blank) { * { background-color: black !important; } }` in userChrome.css, resulting in the entire page looking black besides the red/yellow element overlays.

**Comment by gorhill** [comment]
I can't reproduce, I added the above CSS snippet to `chrome/userChrome.css` in the root of the profile and the picker is still transparent.

**Comment by Fyren** [comment]
Sorry, `chrome/userContent.css`.  userChrome is for the browser UI itself, userContent for rendered content.  I just verified on a new profile.  I'm unsure if restarting Firefox is required after changing the file.

**Comment by gorhill** [comment]
According to the inspector, uBO is overriding the style in userContent, but somehow this is not really the case because the iframe is no longer transparent:

![a](https://user-images.githubusercontent.com/585534/43073584-29f1c45a-8e48-11e8-91cf-ebf86941560f.png)

**Comment by Fyren** [comment]
I see the same for the HTML and body tags, but the svg that covers the entire viewable area is getting the background-color from the userContent rule.

**Comment by Fyren** [comment]
While the HTML5 spec appears to say that if there's no srcdoc and no src, then the src is considered to be about:blank, but I don't think the intent is about:blank to be a canvas for developers to use.  The only spec I can see that might apply is RFC6694 which says the following:

> The "about:blank" URI refers to a resource represented in the browser by a blank page.

If I style about:blank, I'm styling such a resource.  If you start using about:blank to display content, then that's misusing because you just want to start from a blank page rather than display about:blank.

**Comment by gorhill** [comment]
> I don't think the intent is about:blank to be a canvas for developers to use

It's actually used a lot like this. Dynamically iframes are created as `about:blank`, i.e. empty document, but nothing whatsoever prevent the created iframe to have its DOM dynamically populated, and it's actually commonly done.

I consider your issue to be your indiscriminate styling, it needs to be more focused as shown, it's not a uBO-specific issue, if you think so you will end up reporting all such cases to countless places, including on web sites.

**Comment by Fyren** [comment]
I think I've had that rule there for years without running into a problem till now with uBO.  In a pragmatic sense, there have been several users who ended up making issues about this, so there have certainly been more that haven't, and it could be prevented by intentionally avoiding using about:blank by setting an empty srcdoc (or possibly other ways).

**Comment by gorhill** [comment]
> I've had that rule there for years without running into a problem till now with uBO

But this does not really matter. What matter is that your custom CSS rule is telling the browser to override the background color of all `about:blank` iframes, regardless of whether they contains an actual DOM with a precise purpose. Your custom rule assumes wrongly that all `about:blank` frames are empty DOM, which is a false assumption -- there is spec out there which says the DOM of `about:blank` iframe must never be populated.

It does not matter that you never stumbled onto such a case, the assumption is still wrong, and your custom rule resulting from the wrong assumption needs fixing.

The purpose of `about:srcdoc` is to provide the HTML content as a value of the `srcdoc` attribute -- you are just asking me to modify uBO to make it work with your too-broad CSS rule. It's just a matter of time before someone else show up here and ask me to fix uBO for their custom CSS `about:srcdoc` rule.

The key issue is, do not override the CSS styles of non-empty documents, it's for you to fix, your rule is too indiscriminate, and as expected it created an issue.

Bottomline is that it's cool that Firefox allows such customization, but whoever uses these cool features will have to bear the burden of the consequences. It makes no sense to ask all those who uses anonymous iframes out there to mind all those potential customization which are out of their scope.

**Comment by gorhill** [comment]
Quick example, your custom CSS rules breaks the rendering of embedded tweets on this page: <https://www.watson.ch/Digital/Twitter/531665406-Das-sind-die-10-beliebtesten-Tweets-des-Jahres-%E2%80%93-Obama-ist-gleich-3-Mal-dabei#twitter-widget-2>.

However trivial is the change, I won't modify uBO's code for the principle: your overly broad CSS rule is wrong in the first place, it makes the assumption that `about:blank` is always an empty DOM (but I am just repeating myself), "fixing" uBO to accommodate your specific CSS rule which unduly interfere with extensions/pages would open the door to start accommodating all such issues external to uBO.
