### ISSUE TITLE
[Open] How to block the Clima display on the microsoft-edge-dev for Linux home page? 

### ISSUE THREAD

**Issue by serial02** [uBlockOrigin/uBlock-issues#1432]
Hello BlockOrigin Team

How to block the Clima display on the microsoft-edge-dev for Linux home page? (self.uBlockOrigin)

See the image: ( https://imgur.com/7YFBtk4 )

![7YFBtk4](https://user-images.githubusercontent.com/32621790/103484450-b4b00100-4dcd-11eb-8b2a-e3bafde81a49.png)

The "Lock element" function on this microsoft-edge-dev home page does not work. Can this be reviewed?

![Screen Capture_20210103141314](https://user-images.githubusercontent.com/32621790/103484534-4455af80-4dce-11eb-82f1-d3b9c9606273.png)

**Comment by uBlock-user** [comment]
By-design. uBO cannot run on `edge://` scheme, only `http://` and `https://`.
