### ISSUE TITLE
Will ublock Origin support more than 1 Admin policies in "chrome://policy" ?

### ISSUE THREAD

**Issue by stbeep1** [uBlockOrigin/uBlock-issues#1433]
### Prerequisites

- [x] ✔️ I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] ✔️This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] ✔️I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Just stumbled while implementing policy settings to start pushing out uBO to replace ABP across all our Chromebooks and Windows 10 laptop. With a little fiddling, was able to push multiple settings and the netWhitelist with multiple domains. One question, though, is if there's a way to push out whitelist domains that doesn't replace the user's whitelist settings? When I push out a couple domains via the netWhitelist value, it replaces the entire list rather than appending/updating existing ones. 
Also, Sometimes I want to whitelist a website for my users, but I wanted to allow them to whitelist other websites. Currently, the policies that I can config in admin consle we're extremely limited for uBO. Cloud you release more chrome://policy on uBO??

### Your environment

* uBlock Origin version: v1.31.2
* Browser Name and version: Google Chrome 85 
* Operating System and version:  both Windows 10 (2004) and Chrome OS 85.

**Comment by gorhill** [comment]
I will try to add support for this today in dev build.

**Comment by stbeep1** [comment]
> I will try to add support for this today in dev build.

Huge thanks.

**Comment by gorhill** [comment]
The new policy is `extraTrustedSiteDirectives`, an array of strings, each of which must be a valid directive as [per documentation](https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted).

These extra trusted-site directives are appended to a user's own directives at every launch, and are considered by uBO as default directives, i.e. they will be rendered as such in the editor.

**Comment by stbeep1** [comment]
Well the other problem is that even we forced installed uBO via google admin console and pushed out the settings, end users can still change them when they want. I can describe this as 08:00AM we pushed out the settings then users mess around in the settings page, *they can still change the settings unless they reboot their devices. So that, I said it's limited for us. What do you think about that? @gorhill 

Side note: uBO is still my still my favourite Chrome extensions since 2015. I am not a uBO haters or any things related to "let uBO moves into business oriented [movement] guy" that kind of thing. As I totally agree the perspective/idea of the uBO team. I enjoy and love using uBO everyday.

**Comment by stbeep1** [comment]
@gorhill @uBlock-user Cloud you comments on that please?


> Well the other problem is that even we forced installed uBO via google admin console and pushed out the settings, end users can still change them when they want. I can describe this as 08:00AM we pushed out the settings then users mess around in the settings page, *they can still change the settings unless they reboot their devices. So that, I said it's limited for us. What do you think about that? @gorhill
>

**Comment by gorhill** [comment]
Be specific. What exact settings do you want to be read-only? I can comment and/or act only on specific. I consider the issue here solved, you specifically asked for ability to add trusted-site directives to a user's own set, which is what I fixed. For more, open distinct issues for specific settings and what you want about them as admin.

**Comment by stbeep1** [comment]
Got it. I will create a new issue.

**Comment by crimsonmt** [comment]
This functionality would be great, looking forward to implement, currently on version 1.37.2 trying to deploy this via GPO but unsuccessful. Any tricks to getting this push via GPO if at all possible.

**Comment by gorhill** [comment]
You can add trusted sites already, read the wiki.
