### ISSUE TITLE
base64 scripts

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#1436]
Is it technically possible to show and block base64 scripts from the logger like normal scripts?
There are a lot of base64 scripts on the original document `https://sayrodigital.com/category/hardware/`, some of them are unwelcome.

**Comment by gwarser** [comment]
Not possible - `data:` URLs don't get through WebRequest API.

**Comment by uBlock-user** [comment]
`data:` resources are locally embedded resources, as a result they don't make any network request.
