### ISSUE TITLE
Settings cannot be reset on Beta and Nightly Firefox

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#144]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After click on "Reset to default settings..." uBO will show confirmation dialog, then restart, but when I go back to Dashboard all my settings are unchanged.

Browser console shows (probably unrelated):

An IndexedDB transaction that was not yet complete has been aborted due to page navigation. vapi-cachestorage.js:261:22

### A specific URL where the issue occurs

Dashboard

### Steps to Reproduce

1. go to Dashboard -> Filter lists and select first three regional lists (for example)
2. apply and update
3. go to Settings tab and click on "Reset to default settings..."
4. Click OK in "All your settings will be removed..." dialog
4. uBO will restart
4. wait for CPU
4. open uBO Dashboard -> Filter lists
4. three regional lists are still selected

### Expected behavior:

No regional lists selected or only one for current locale. Settings should be reset to default.

### Actual behavior:

All changes are preserved.

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Firefox 62.0b10 (20180719140244), Firefox 63.0a1 (20180723100101)
* Operating System and version: Mint 18.3 KDE

**Comment by uBlock-user** [comment]
Does this not happen on stable version ?

**Comment by gwarser** [comment]
Stable is OK.

**Comment by uBlock-user** [comment]
Should it be throwing that error if the bug was [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1147942) 3 years back?

**Comment by gwarser** [comment]
This message may be unrelated. I see it in 61.0.1 and settings are reset here.

**Comment by uBlock-user** [comment]
I can reproduce it on Nightly, but I don't see any such errors on the console though.

**Comment by gorhill** [comment]
On my side I get an exception in Nightly code, which does occur with Firefox 61:

     TypeError: extension is undefined
    receiveMessage@resource://gre/modules/ExtensionParent.jsm:351:5
    _handleMessage/</<@resource://gre/modules/MessageChannel.jsm:922:19
    _handleMessage/<@resource://gre/modules/MessageChannel.jsm:921:9
    _handleMessage@resource://gre/modules/MessageChannel.jsm:919:7
    receiveMessage/<@resource://gre/modules/MessageChannel.jsm:218:9
    receiveMessage@resource://gre/modules/MessageChannel.jsm:211:5
    enter@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/utils/event-loop.js:118:5
    _pushThreadPause@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:179:5
    onExceptionUnwind@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/thread.js:1598:7
    receiveMessage@resource://gre/modules/ExtensionParent.jsm:351:5
    _handleMessage/</<@resource://gre/modules/MessageChannel.jsm:922:19
    _handleMessage/<@resource://gre/modules/MessageChannel.jsm:921:9
    _handleMessage@resource://gre/modules/MessageChannel.jsm:919:7
    receiveMessage/<@resource://gre/modules/MessageChannel.jsm:218:9
    receiveMessage@resource://gre/modules/MessageChannel.jsm:211:5
    MessageChannel.jsm:924 

Seems like a Nightly issue?

**Comment by gwarser** [comment]
This exception also looks unrelated. I can reproduce only with uBO 1.16.14 from AMO. Latest dev looks good.

**Comment by gorhill** [comment]
I implemented a workaround. The issue is really in Firefox, as the same code worked fine in Chromium. But since this is a key feature, workaround is needed. I believe the change in behavior in Firefox might be caused by moving `browser.storage.local` from JSON-based file to indexedDB-based storage. I still see related message in the browser console, but I could reset fine at least.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1478009

**Comment by jspenguin2017** [comment]
> The issue is really in Firefox

It works on Chromium doesn't mean the code is right. Clearing extension storage is asynchronous, the behavior of restarting the extension before asynchronous actions complete is undocumented. It works correctly on Chromium, but that should be considered by chance, not by design. Although throwing an exception shouldn't something to expect. 

This never really worked, I noticed it in Feburary but didn't have time to investigate: https://github.com/NanoAdblocker/NanoCore/issues/112

**Comment by jspenguin2017** [comment]
Also I don't think the fix is right, nothing guarantees `µBlock.saveLocalSettings` will run *after* the other two calls to clear extension storage.

**Comment by gwarser** [comment]
And there is still chance `immediateHiddenSettings` will not be cleared.

Simple `setTimeout`  with long delay (not a solution obviously) fixes this for me and no messages in console.

**Comment by jspenguin2017** [comment]
@gwarser No, `localStorage` is guaranteed to be synchronous.

**Comment by jspenguin2017** [comment]
Actually restoring user data is not perfectly safe neither, clearing cache storage can have race condition. It does wait for the main storage to finish clearing, but it's still something to keep in mind.

**Comment by gorhill** [comment]
This is definitely a Firefox issue -- their call if they refuse to see it (I can name two other issues were they refused to see it and yet were later fixed), it's a matter of time before this surface elsewhere than in uBO.

Disabling an extension (which is the first step of a restart operation) is not the equivalent of crashing the extension. In a correct implementation, stopping an extension involves flushing out all pending operations, including storage write operations. That's why it works fine with Chromium.

> nothing guarantees µBlock.saveLocalSettings will run after the other two calls to clear extension storage.

This makes no sense, "asynchronous" is not "arbitrary order", even more so regarding storage write operations.

**Comment by gorhill** [comment]
> the extension is relying on undefined behavior

So I suppose [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction) needs updating, "unloading the document which fired the transaction" is not listed in the reasons for aborting a transaction.

**Comment by jspenguin2017** [comment]
> stopping an extension involves flushing out all pending operations

Agreed. In an ideal world, that would be the case. 

> callback parameter in `browser.storage.local` set/clear methods are optional

Just like pretty much every other callback parameter. 

> OS flushes out the buffered data

The kernel will `fflush` *once* for each of your open handles, should that `fflush` fail, your buffered data will disappear into the void. And your program would corrupt its files, and you'll complain that it's a kernel issue. 

> Also think of `navigator.sendBeacon`

Sure, the browser will *try* to finish sending it, it can still fail. 

> "asynchronous" is not "arbitrary order"

You got a good point here, but nowhere in the doc does it guarantee that the order of call is the same as the order of write. I think this like spinning off 3 threads that writes into a same file (with mutexes), if the data is small, the order should be pretty stable, but you can't rely on that.

**Comment by gorhill** [comment]
@gwarser I can no longer reproduce on my side using the latest Nightly and uBO 1.16.14 (the warnings regarding `vAPI.cacheStorage` are still there, but that warning is unrelated to user settings issue reported here, so you can just ignore). The settings are now properly reset on my side with latest Nightly.

**Comment by gwarser** [comment]
Firefox 62.0b14 20180802174131 still affected.

**Comment by gorhill** [comment]
From the last comment of the Firefox on bugzilla, it does appear that there was an issue in the extension API -- he confirmed that the calls to `browser.storage.local` are indeed queued as expected and as such are still valid after an extension quits. I tried to install moz-regression to figure out when the resetting of settings started to work as expected but I had no success in installing the utility.

**Comment by gwarser** [comment]
>INFO: No more inbound revisions, bisection finished.
INFO: First good revision: d7aac87e2db54dc57b951e63079f053df49a50ef
INFO: Last bad revision: f32e9ff50ebd4e63205491905087ab7dee11b506
INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=f32e9ff50ebd4e63205491905087ab7dee11b506&tochange=d7aac87e2db54dc57b951e63079f053df49a50ef

**Comment by infinity0** [comment]
This issue still exists on Debian Firefox 65, please consider re-opening. I have the same error message as in https://github.com/uBlockOrigin/uBlock-issues/issues/144#issuecomment-407178656.

**Comment by infinity0** [comment]
This issue still exists on Debian Firefox 65, please consider re-opening. I have the same error message as in https://github.com/uBlockOrigin/uBlock-issues/issues/144#issuecomment-407178656 but it seems other people have different error messages. I guess it's non-deterministic.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916594

**Comment by gorhill** [comment]
The issue in your link says it's about uMatrix, here is for uBlock Origin.

I looked at uMatrix's code and it's different that that of uBO, there is no such issue with it -- uMatrix correctly wait for the storage to be cleared before proceeded to restart. The debian issue is confusing, as the reported error messages are related to the UI, the "My rules" pane specifically.

**Comment by infinity0** [comment]
Sorry, my bad. I just tried again and it seems to be fine at least in the newest version 1.3.16. I must have gotten confused whilst dealing with multiple bugs or something. I will go and close the Debian report.
