### ISSUE TITLE
FF tab crash when using Inline script filtering (HTML filters )

### ISSUE THREAD

**Issue by nobura** [uBlockOrigin/uBlock-issues#1441]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

FF tab crash when using Inline script filtering and try to view page source

### A specific URL where the issue occurs

any site use  `##^script:has-text(...)`

### Steps to Reproduce

example use wikipedia.org

1. create filter any inline script filter  ex: `wikipedia.org##^script:has-text(patrolToken)`
2. goto https://en.wikipedia.org/wiki/UBlock_Origin
3. then `Ctrl + U ` or right click `view page source`
4. FF tab crash

### Expected behavior:

not crash

### Actual behavior:

i dont know, if this browser bug or ublock bug

### Your environment

* uBlock Origin version: 1.32.5b5
* Browser Name and version: firefox 84.02
* Operating System and version: windows 10 20H2

**Comment by gorhill** [comment]
Browser/tab crashes must be reported to Firefox devs.

**Comment by gorhill** [comment]
There is/was an issue of crash with `view-source:`, I don't have time to look it up.

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/kd0f0n/ghacksnet_tab_crash_when_trying_to_access_view/
https://bugzilla.mozilla.org/show_bug.cgi?id=1678734
