### ISSUE TITLE
feature: maybe it's time to rethink the possibility of porting to Safari

### ISSUE THREAD

**Issue by dminca** [uBlockOrigin/uBlock-issues#1444]
Just asking if it's possible to make this wonderful extension available for Safari now, given the following article published by Apple Developers in regards to converting web extensions for Safari

https://developer.apple.com/news/?id=qiz0arxc

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/hdz0bo/will_ublock_origin_back_to_macos_big_sur/fvoc7wk/

**Comment by emikaadeo-git** [comment]
Hi,
maybe we can reconsider this with new experimental [uBOLite MV3 API-based content blocker](https://github.com/gorhill/uBlock/releases/tag/uBOLite_0.1.22.9196) ?
Safari have support for MV3 extensions since version 15.4 https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/#safari-web-extensions

**Comment by gorhill** [comment]
I don't have MacOS, this would have to be undertaken by a another volunteer developer.

Anyways, the implementation of [declarativeNetRequest API on Safari](https://developer.apple.com/documentation/safariservices/safari_web_extensions/blocking_content_with_your_safari_web_extension) is missing key capabilities for the current state of uBOL, it does not support conditions such as `initiatorDomains`, `excludedInitiatorDomains`, `requestDomains`, `excludedRequestDomains`. It also does not support action types `redirect` which will be needed once uBOL starts to use this capability.

Additionally, the [Safari `scripting` API](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility) is also missing key capabilities, namely `registeredContentScript`, `getRegisteredContentScript`, `unregisterContentScripts`, `updateContentScripts`.

**Comment by emikaadeo-git** [comment]
@gorhill 
Hi,
thanks for clarification.

**Comment by henryhchchc** [comment]
Just noticed that Apple added support for `redirect` 10 months ago as mentioned in https://webkit.org/blog/12193/release-notes-for-safari-technology-preview-139/

> Added support for the `redirect` rule type in `declarativeNetRequest`, which requires host permissions to be granted for the host of the URL being redirected

I think this feature is available in Safari 16 but Apple haven't updated their documentation.

**Comment by abarisain** [comment]
It looks like safari 16.4, in beta, adds support for a lot of what is missing 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/312529/222570717-28e5582d-4905-4738-b666-bd8c84f8d91d.png">

That said, there is still this ridiculous requirement for it to be wrapped in an app, so someone will have to do that.

**Comment by wavded** [comment]
Safari 16.4 is out of beta now, not sure how close this gets us.

**Comment by dminca** [comment]
I’ve dropped a toot to Jen and Jon from the WebKit team, let’s see if they’re considering the missing capabilities from Raymond https://mastodontech.de/@dminca/110135906549832299

**Comment by helvetiica** [comment]
Any updates for Safari 17 (macOS Sonoma)?
