### ISSUE TITLE
remove-attr does not always work

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1445]
Example: `https://news.rambler.ru/conflicts/45563172-smi-politsiya-ottesnila-protestuyuschih-so-stupeney-kapitoliya/`

When scrolling down the strings, the rule `rambler.ru##+js(remove-attr, class, .j-mini-player__video)` should fix the player in a static position, but for some reason this does not happen. In version 1.31.2, this problem is absent and the rule works fine.

<details>
<summary>Config</summary>

Google Chrome 87.0.4280.88
Firefox 84.0.2
uBlock Origin v1.32.5b7 default + [RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin), [Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)
</details>

**Comment by gwarser** [comment]
Attribute is removed correctly and then new is created with `j-mini-player__video--absolute`. Some timing issue?

**Comment by gorhill** [comment]
I can't find an element matching `.j-mini-player__video` at that page. What do I need to do for such element to be present?

**Comment by gorhill** [comment]
Loos to me this work better if the goal is to prevent fixed position:

    rambler.ru##.j-mini-player__container:style(position: initial !important)

**Comment by gwarser** [comment]
> I can't find an element matching `.j-mini-player__video` at that page.

Removed by Ruadlist.

**Comment by gorhill** [comment]
> Removed by Ruadlist.

I was testing first without RU AdList. In any case, if it's removed by RuAdList, it's expected that `.j-mini-player__video` won't be found in the DOM, and shouldn't be used as selector to lookup?

**Comment by gorhill** [comment]
Duh sorry, I couldn't find it because `remove-attribute` worked on my side...

**Comment by MRSCARTER06** [comment]
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MRSCARTER06** [comment]
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by MRSCARTER06** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by uBlock-user** [comment]
> So the issue is probably because remove-attr does not listen to DOM mutations.

Yes, that's the issue, also it wouldn't work with `1.31.2` either for that matter.

**Comment by dimisa-RUAdList** [comment]
The rule `rambler.ru##+js(remove-attr, class, .j-mini-player__video)` has been working for a long time and stably: [Gif](https://imgur.com/G82JIEb)

To see the `j-mini-player__video` element, use `rambler.ru#@#+js(remove-attr, class, .j-mini-player__video)`.

Previously, `:style` type rules were used instead. But they did not always allow to keep the size of the player window. I can go back to them, but I would like to revive `remove-attr`.

**Comment by gorhill** [comment]
I will add support for mutation observer in `remove-attr` in next dev build.

**Comment by dimisa-RUAdList** [comment]
I added a temporary fix, but when using it, the player window blinks when scrolling. Bad decision, but better than nothing.

https://github.com/easylist/ruadlist/commit/5687030498c08f291af974919a782e9a6a0864a6

**Comment by gwarser** [comment]
`rambler.ru##+js(aeld, DOMContentLoaded, .j-mini-player__video)` is working for me.

**Comment by dimisa-RUAdList** [comment]
@gwarser 
It's much better than: `rambler.ru#?#.j-mini-player__container:style(position: initial !important; width: initial !important; height: initial !important)`

Changed: https://github.com/easylist/ruadlist/commit/9691055bf06bc1b0b459e40f1e4f7b3b300c73cb

But still I would like to restore the `remove-attr`.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1445#issuecomment-756165152 - maybe to in `rc`?

when should be 100% with AdGuard idea based on 20 ms delay after monitor blink someting.

**Comment by gorhill** [comment]
@dimisa-RUAdList use a third argument to indicate to the `remove-attr` scriptlet to stay and act on DOM changes, i.e.:

    rambler.ru##+js(remove-attr, class, .j-mini-player__video, stay)

**Comment by uBlock-user** [comment]
After the update, `rambler.ru##+js(remove-attr, class, .j-mini-player__video)` itself works too

**Comment by gorhill** [comment]
It was working before the update on my side -- as pointed out above, timing issue, and nothing functionally changed if the 3rd argument is not used.

**Comment by dimisa-RUAdList** [comment]
Indeed, in version 1.32.5b8, the old rule `rambler.ru##+js(remove-attr, class, .j-mini-player__video)` also works fine, without the third argument. However, I find the ability to linger for remove-attr scriplet quite helpful. But I will keep the current rule `rambler.ru##+js(addEventListener-defuser, DOMContentLoaded, .j-mini-player__video)` for now. In the current stable version 1.32.4 for Firefox, nothing else works except for it (except :style).

**Comment by dimisa-RUAdList** [comment]
I think I found another case.

Latest Google Chrome, Firefox, uBlock Origin 1.34.1rc0 default + [RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin), [Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

1. Open: https://www.lostfilm.run/series/DOTA_Dragons_Blood/season_1/episode_6/photos
2. Click on any photo: https://i.imgur.com/a1a75oy.jpg
3. Rule `lostfilm.run##+js(remove-attr, oncontextmenu)`didn't work: https://i.imgur.com/aDaXU9C.jpg

If you refresh the page, then everything works as it should.

**Comment by strict-block** [comment]
Opended gallery use "Ajax" instead reload page from "0 progress" - possible change url in address bar witout fully reload.

This may need use `, stay`:
```
lostfilm.run##+js(remove-attr, oncontextmenu, stay)
```

I you must support uBO older than 1.33.0 try:
`        userResourcesLocation https://raw.githubusercontent.com/gorhill/uBlock/master/assets/resources/scriptlets.js`

uBO legacy for Firefox maybe need build legacy file with older syntax for `userResourcesLocation`:

> ```js
> # remove attr with dom/node changes
> remove-attr.js application/javascript`
> ```

**Comment by D4niloMR** [comment]
2 cases possibly related:

https://github.com/uBlockOrigin/uAssets/pull/21422

and in the images on `https://animefire.plus/`

`animefire.plus##[oncontextmenu], [ondragstart]:remove-attr(/oncontextmenu|ondragstart/)` doesn't work, but `animefire.plus##+js(ra, oncontextmenu|ondragstart)` works.

The issue happens only in Chromium based browsers. I see that with `:remove-attr` the attribute is gone but the event listener is still there.


<details><summary>Screenshot</summary>
<p>

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/70459964/9032e960-05ac-479d-98c7-c90be2b0b5fe)


</p>
</details>

**Comment by uBlock-user** [comment]
`animefire.plus##[oncontextmenu], [ondragstart]:remove-attr(/oncontextmenu|ondragstart/):watch-attr(oncontextment,ondragstart)`

try

**Comment by D4niloMR** [comment]
> @D4niloMR `animefire.plus##[oncontextmenu], [ondragstart]:remove-attr(/oncontextmenu|ondragstart/):watch-attr(oncontextment,ondragstart)`

Didn't work

**Comment by gorhill** [comment]
> The issue happens only in Chromium based browsers

Yes, this is a known issue, discussed elsewhere I can't remember. The procedural cosmetic filters execute in the isolated world, and it seems with Chromium changing `on...` attribute will not be reflected in the main world's `on...` handler. Hence why the scriptlet `remove-attr` is still available to take care of such cases for the time being.

**Comment by garry-ut99** [comment]
> Yes, this is a known issue, discussed elsewhere I can't remember.


Discussed here : 
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2403#discussioncomment-4625517
