### ISSUE TITLE
Unable to allow a specific document domain via no-csp-reports

### ISSUE THREAD

**Issue by NyanKiyoshi** [uBlockOrigin/uBlock-issues#1446]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently it seems it is not possible to allow a specific tab's hostname via custom rules without allowing the hostname of the CSP target for the report.

For example:
1. Current tab site to allow to send CSP reports: `csp-ublock.vanille.bid`
1. `report-to` for CSP: `example.com`

This rule will not work:
```
no-csp-reports: csp-ublock.vanille.bid false
```

This rule will work:
```
no-csp-reports: example.com false
```

### A specific URL where the issue occurs

https://csp-ublock.vanille.bid

### Steps to Reproduce

1. Open the uBlock logger,
1. Load the page, it will be blank,
1. Console should confirm that a `<script>` was blocked and reported (otherwise an `alert()` will fire),
1. Try to add a new rule (`My rules`, so) with: `no-csp-reports: csp-ublock.vanille.bid false`
1. Reload the page, 
1. It should still be showing blocked in the uBlock logger instead of allowed,
1. Change the rule to `no-csp-reports: example.com false`,
1. Logger should show that it allowed it.

### Expected behavior:

I would expect to not fully allow a given CSP ingesting service, e.g. `example.com` (or a real one: `ingest.sentry.io/api/security/`), rather be allowed to allow a given domain to send CSP reports to a specific target (e.g. `csp-ublock.vanille.bid` to send to `example.com`, or as well as a rule that would allow `vanille.bid` and its sub-domains to report to `example.com`).

### Actual behavior:

Only the third-party CSP report destination can be allowed rather than the first-party itself (or both combined as a `and` condition).

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox 86.0a1
* Operating System and version: Mac OS X 10.16

**Comment by gorhill** [comment]
> I would expect to not fully allow a given CSP ingesting service, e.g. `example.com` [...] rather be allowed to allow a given domain to send CSP reports to a specific target 

Why would you expect this? Why would the the behavior you expect be unexpected as well by somebody else?

**Comment by gorhill** [comment]
Maybe what you report here could have been debated back when the feature was developed.

The problem at this point is that you are asking to change a behavior that exists ever since `no-csp-report` was first introduced, it's too late for this as such change could cause the blocking behavior of already existing installations.

**Comment by gorhill** [comment]
Well, in this commit introducing the `no-csp-report` switch, I do use the hostname of the tab to lookup the state: <https://github.com/gorhill/uBlock/commit/95b25f7d49d4987711f28b250a81ff979b204c47#diff-d88e38513efe4e855f66a53f0ba00fa16264d07f8d8fe7100cf3131a74fbe0b4R655>

I will have to further investigate when this was changed and why.

**Comment by gorhill** [comment]
This was changed in <https://github.com/gorhill/uBlock/commit/75659a3154e35274e8b6fd75c87560ffd50b37d2>, because of <https://github.com/gorhill/uBlock/issues/3260>.

**Comment by gorhill** [comment]
Given that this was a deliberate decision as per above commit/issue, I can't change back the behavior.

**Comment by NyanKiyoshi** [comment]
This was not a feature request. But a request for more information about behavior and whether or not it might be possible to extend such rules.

Currently, we have a policy behavior that goes from one extreme "Block all CSP " to another extreme "Block CSP but allow all CSP going to that third party" rather than allowing more control and a smoother transition: "Block all CSP, but trust some first-party against a specific third party".

Just as lists give users control, rather than being blocked by rules that are too strict and too permissive - for which I assumed a lack of trust in the lists, why something like this could not be done directly by a custom rule in a local list.

One could not trust a particular third party that could be used by the whole Internet except against a particular first party that the user fully trusts. That is why we have so much control over the lists, users can have control instead of being locked between two extremes.

Having such a rule wide open goes against the privacy concern that leads uBlock to put in place this CSP feature–which is good and important in itself, just as is CSP, which reporting is and was made for.

However, from what I saw when I dug into the code before opening the issue, it would be too hard to change as the configuration does not seem to be very flexible; especially for the number of people who would consider adding such exceptions and people who understand the role and implication of these policies.

**Comment by gorhill** [comment]
> too hard to change as the configuration does not seem to be very flexible

What you have in mind matches better a [dynamic filtering rule](https://github.com/gorhill/uBlock/blob/5736a6e2b6c9ac3e917a77392e0fc04eb543e38a/src/js/dynamic-net-filtering.js), to be able to craft rules with both source and destination, i.e.:

    * * report block
    csp-ublock.vanille.bid * report noop

But it's not something I see worth being added, especially given I have resisted adding other more common types than the [ones already in there](https://github.com/gorhill/uBlock/blob/5736a6e2b6c9ac3e917a77392e0fc04eb543e38a/src/js/dynamic-net-filtering.js#L39-L46).
