### ISSUE TITLE
Syntax $queryprune error in Edge Chromium

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1448]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [ X] uBlock Origin with default lists/settings
    - [ X] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
The new queryprune (removeparm) does not work in My Filters using Edge-chromium. When I enter the syntax as shown in `Github Wiki Static filer syntax' the syntax checker does not recognize it as correct syntax.

### Description
It is easier to explain with a picture, in below picture I have added a 
![image](https://user-images.githubusercontent.com/30925856/104579548-5fd97980-565c-11eb-93aa-1dbdbc0b1207.png)

[Description of the bug or feature]

### A specific URL where the issue occurs
www.google.nl
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [Open settings in uBlockOrigin]
2. [Click tab My Filters]
3. [type: "||example.org$queryprune=example1.]

### Expected behavior:
"Same coloring code syntax as with CSP (no underline for error indication)
[What you expected to happen]

### Actual behavior:
My Filters underlines $queryprune to show syntax is incorrect
[What actually happened]

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Edge  87.0.664.75
* Operating System and version: Windows 10 Home, 20H2, OS build 19042.746

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/commit/2ab11603f08583a3d60183c9b04613374f01cd25

**Comment by uBlock-user** [comment]
On current stable build, you need to set `filterAuthorMode` to `true` in advanced settings to be able to use  `$queryprune` which will no longer be a requirement when the next stable build is pushed.

**Comment by Kees1958** [comment]
Thank you very much

**Comment by gorhill** [comment]
Also, the syntax has changed to be in line with AdGuard's `removeparam`, see [documentation](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#queryprune) -- there is no need for the pipe character `|` as seen in your examples.

**Comment by Kees1958** [comment]
OK, thanks @gorhill and @uBlock-user 

On Edge when adding an end pipe, everything is stripped. Being not a native English speaker removeparam is more intuitive than queryprune (although I passed the Oxford level B1 exam this does not make sense to me "query prune" = ask for dried fruit?)
