### ISSUE TITLE
uBO breaks the display of private certificates on Firefox

### ISSUE THREAD

**Issue by bourasp** [uBlockOrigin/uBlock-issues#1449]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I try to view about:certificate on Firefox for site whose certificate is signed by a private CA the page does not display anything. When I disable uBO then everything works.
uBO is the only add on installed.

### A specific URL where the issue occurs

Any HTTPS URL whose certificate is signed by a private or un-trusted CA

### Steps to Reproduce

1. Visit website
2. Use the "Show certificate" on Padlock -> Secure connection -> More Information
3. Opens new tab at about:certificate but it's a blank page

### Expected behavior:

When uBO is disabled as add on on Firefox, the page displays as expected.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.3.2.4
* Browser Name and version: Firefox 84
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
> Any HTTPS URL whose certificate is signed by a private or un-trusted CA

Post the url here

**Comment by bourasp** [comment]
I believe manage to solve it, eventually the fix was to change Firefox theme once.
Now even if I switch back on the original theme everything seems to work.

As for URL I cannot share as all my experience is on internal / private sites.

**Comment by h1z1** [comment]
Run into this all the time.  It's because Firefox is retarded.  Rather then use a cached copy of the cert it tries to pull another one down, that connection can be blocked.
