### ISSUE TITLE
[PR Question] Implement warning for unsaved changes in dashboard

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#145]
I want to help fixing https://github.com/gorhill/uBlock/issues/3271

Since the dashboard is driven by `iframes`, I think one way to implement it is to make each `iframe` to expose a global variable, `hasUnsavedChanges`. When the dashboard is closing or the tab is changing, the main frame will check the global variable of the child frame and show a warning message if needed. 

@gorhill Do you think this is a good way to implement it? Do you want me to PR?

**Comment by gorhill** [comment]
> Do you think this is a good way to implement it? Do you want me to PR?

Sounds fine to me, I would accept a PR, thanks. I haven't thought much about this, not sure how the warning should be designed (I feel DOM-based would be better).

**Comment by gwarser** [comment]
>When the dashboard is closing

nothing can be done... ?

https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload#Notes

**Comment by gorhill** [comment]
The dashboard code is the one swapping panes, so it's just a matter of having a warning when a pane is detected as having unsaved changes, and waiting for confirmation before swapping. If the only case left is the closing of the whole dashboard itself, it's not too bad.

**Comment by jspenguin2017** [comment]
> I feel DOM-based would be better

The warning for dashboard closing will always be a `confirm`-like dialog, so I guess just a `confirm` should do.

**Comment by jspenguin2017** [comment]
Eh... I have some problem with `uDom`. It tears everything down when `beforeunload` event is fired... Eh, why? 
```js
// Cleanup

var onBeforeUnload = function() {
    var entry;
    while ( (entry = listenerEntries.pop()) ) {
        entry.dispose();
    }
    window.removeEventListener('beforeunload', onBeforeUnload);
};

window.addEventListener('beforeunload', onBeforeUnload);
```

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/43239280-d87d77c8-904e-11e8-9fd6-eb40fc02b590.png)
![image](https://user-images.githubusercontent.com/7283682/43239289-e0147a9a-904e-11e8-8075-c20957194e55.png)

**Comment by jspenguin2017** [comment]
I'll close this in favor of the PR, where we can review the changes easily.

**Comment by uBlock-user** [comment]
This needs to be extended to _My Rules_ and _Whitelist_ too as they too suffer from this.
