### ISSUE TITLE
Auto Update doesent work on any browsers

### ISSUE THREAD

**Issue by TheBlueFire94** [uBlockOrigin/uBlock-issues#1450]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [?] uBlock Origin with default lists/settings Additional Filters but otherwise default settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

No Spec. URL!

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open the Menue of Ublock
2. Filters
3. Update
4. Repeat due to the Addon not establishing Download Connection on the first time.
### Expected behavior:

In no Browser the Auto Update of the Signatures / Filters works I need to do it manually, even start the addoninterface twice to get it to work.

### Actual behavior:

In no Browser the Auto Update of the Signatures / Filters works I need to do it manually, even start the addoninterface twice to get it to work.

### Your environment

* uBlock Origin version: uBlock Origin v1.32.4
* Browser Name and version: Firefox V 84.0.2 / EDGE Chromium V 87.0.664.75 / Opera Chromium V 73.0.3856.344 / Google Chrome V 87.0.4280.141
* Operating System and version: Windows 10 Pro 20H2 Build 19042.746 XP 120.2212.551.0

**Comment by uBlock-user** [comment]
Test on default settings

**Comment by gorhill** [comment]
Describe in details how you concluded auto update does not work.

**Comment by gorhill** [comment]
Please seek support at <https://www.reddit.com/r/uBlockOrigin/>.
