### ISSUE TITLE
'Blocked since install' doesn't refresh in real time

### ISSUE THREAD

**Issue by wout-codes** [uBlockOrigin/uBlock-issues#1451]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

'Blocked since install' doesn't refresh in real time

### A specific URL where the issue occurs

No URL since this a request for a feature.

### Expected behavior:

I expected whatever is blocked in Private Window or Incognito to be updated too in the Normal mode in 'Blocked since install place'.

### Actual behavior:

Whatever is blocked in Incognito mode or private window is not updated in the normal mode in 'Blocked since install place'.

### Your environment

* uBlock Origin version: 1.32.5b11
* Browser Name and version: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
* Operating System and version: Windows 10 20H2

**Comment by gorhill** [comment]
By design, incognito and normal are two different uBO instances using the same storage.

**Comment by gorhill** [comment]
More thoughts about this, I will evaluate whether reading the stored value before writing to it is worth it.
