### ISSUE TITLE
Compatibility problem between uBlock and proxy socks5 firefox addon

### ISSUE THREAD

**Issue by Paulpatou** [uBlockOrigin/uBlock-issues#1453]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi,
To easily switch between my proxies, i use the addon "Proxy SwitchyOmega" for Firefox (https://addons.mozilla.org/fr/firefox/addon/switchyomega/).
For several weeks now, the loading of websites is very slow, as if the loading is stuck in a standby/timeout status for 30sec-1min before accessing the website normaly.
After some research, it happens when SwitchyOmega and uBlock are both activated. If one of them are deactivated, everything works as usual (no slow loading).

Then i started experimenting with different version of uBlock and found that these slowdowns start happening with the 1.31.0 version of uBlock.
I know that SwitchyOmega is no longer maintained, but I'm only trying to find what causes this issue.

I'm using SwitchyOmega because it's the only one that fullfil all my needs.

Here is a result of Profiler Firefox during one of these slowdowns.
https://share.firefox.dev/3bX5fNI (the page used for this was https://mullvad.net/servers/)

My Firefox is up to date and uBlock settings are by default. The proxies are socks5 or HTTP, both with the problem.

Thx in advance for enlighting my research :)

### A specific URL where the issue occurs

https://mullvad.net/servers/
or anything, mainly test with mullvad and https://www.thingiverse.com/

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:
No slowdowns

### Actual behavior:
Slowdowns when loading websites.

[What actually happened]

### Your environment

* uBlock Origin version: 1.32.4 (problem start at 1.31.0)
* Browser Name and version: Firefox 84.0.2
* Operating System and version: Ubuntu 20.04

**Comment by gwarser** [comment]
Not anonymized profile will be helpful. There is some huge JS downloaded and DOM Worker in parent process runs some heavy JS. Maybe PAC script??? WebExtensions process is not even included in profile.

**Comment by uBlock-user** [comment]
sounds like https://github.com/uBlockOrigin/uBlock-issues/issues/1294

**Comment by Paulpatou** [comment]
Disabling cname-uncloaking in the advanced settings solved it.
It was right in front of me, thanks !

**Comment by uBlock-user** [comment]
Shouldn't be an issue in FF84 because the bug was fixed in v80.
