### ISSUE TITLE
extension code triggers Anti-virus

### ISSUE THREAD

**Issue by htcosta** [uBlockOrigin/uBlock-issues#1454]
### Prerequisites

- [*] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [*] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [*] I am running the latest version of uBlock Origin
- [*] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Anti-virus/malware software is detecting malware on uBlock extension code.
.mozilla/firefox/jty9cjbl.default-release/extensions/uBlock0@raymondhill.net.xpi: Urlhaus.Malware.364328-9787819-0 FOUND

### A specific URL where the issue occurs

http://everywhere.com/

### Steps to Reproduce

1. Scan your `.mozilla/firefox` directory.

### Expected behavior:

Dot not trigger, anti-virus/network scanners.

### Actual behavior:

Triggers Antivirus/Network scanners in a enterprise environment.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox 84.0.2
* Operating System and version: Linux Fedora release 33 (Thirty Three)

**Comment by uBlock-user** [comment]
False positive as always. uBO comes packed with Malware lists which triggers this.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Software-known-to-have-uninstalled-uBlock-Origin
