### ISSUE TITLE
Add wildcard * or regex to no-scripting: rules

### ISSUE THREAD

**Issue by Narice** [uBlockOrigin/uBlock-issues#1456]
**This is an Enhancement request and not a bug report**

### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when... **This is an Enhancement request and not a bug report** so I ticked everything under here
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Adding a wildcard * or regex to `no-scripting:` rules.
I have javascript disabled, but want to enable it for automatic builds on netlify.
so the rule with the wildcard would look like this: `no-scripting: *--app-name.netlify.app true`
It is quite annoying in fact to enable javascript for each build as I know my application isn´t malicious.

### A specific URL where the issue occurs

My Rules page: moz-extension://d412a1f1-db5f-457a-b77f-3f0632055d36/dashboard.html#dyna-rules.html

### Steps to Reproduce

1. go to my rules page
2. add a rule with `no-scripting: *--app-name.netlify.app true`
3. the rule doesn´t work and is highlighted in red

### Expected behavior:

that all pages under `--app-name.netlify.app` have javascript allowed

### Actual behavior:

The rule does not work

### Your environment

* uBlock Origin version: v1.32.4
* Browser Name and version: Firefox 84.0.2 (64-bit)
* Operating System and version: NixOS 20.09 (Nightingale) x86_64

**Comment by gwarser** [comment]
Why not `no-scripting: netlify.app false` and what does the whole address look like?

**Comment by gorhill** [comment]
Declined.

**Comment by gorhill** [comment]
Also, duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/870>.
