### ISSUE TITLE
images from cdn.jsdelivr.net get blocked in eMail Editor

### ISSUE THREAD

**Issue by JPRuehmann** [uBlockOrigin/uBlock-issues#1457]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have installed the Emoji Add-On
But if I try to put Emojis in my eMails an Icon for broken links is displayed.
The Developer tools tell me `Blocked by uBlock0@raymondhill.net`
Why is that?

### A specific URL where the issue occurs

https://cdn.jsdelivr.net/gh/joypixels/emoji-assets@v6.0.0/png/64/1f600.png

### Steps to Reproduce

1. Open eMail Editor
2. Put Cursor in eMail Body
3. activate the Emoji (Add-On) Sidebar
4. Choose Emoji

### Expected behavior:

The choosen Emoji get displayed at the choose destination.

### Actual behavior:

An Icon for broken Links is shown.

### Your environment

* uBlock Origin version: 1,25.0
* Browser Name and version: Thunderbird 78.6.1 (32-Bit)
* Operating System and version: Kubuntu 18.04 LTE (32Bit)

I have reported it to the Developer of the Add-On.
https://github.com/mganss/EmojiAddIn/issues/41

**Comment by gorhill** [comment]
Use the logger to diagnose filtering issue.
