### ISSUE TITLE
Logger shows no events!

### ISSUE THREAD

**Issue by JPRuehmann** [uBlockOrigin/uBlock-issues#1458]
Use the logger to diagnose filtering issue.

_Originally posted by @gorhill in https://github.com/uBlockOrigin/uBlock-issues/issues/1457#issuecomment-765395094_

**Comment by JPRuehmann** [comment]
I´ve tried that but ther is no possibility to chose the corresponding window (eMail Editor) and if I choose all nothing is show up.
At least nothing that has to do with cdn.jsdelivr.net.

**Comment by uBlock-user** [comment]
This place is for reporting proven bugs, not questions., ask at https://www.reddit.com/r/uBlockOrigin/

**Comment by gorhill** [comment]
For Thunderbird, the support is experimental, if there are issues with it, I want to see a complete investigation of where exactly is the issue. If you can't do this, open a thread on Reddit so that the whoever wants to actually contribute can investigate completely where **exactly** is the issue.

**Comment by JPRuehmann** [comment]
This is no Question but a Bug!
Why shoul it only be allowed to file Bugs that others have filed before?
And I don´t have a reddit account. At least as far as I know.

**Comment by uBlock-user** [comment]
> This is no Question but a Bug!

Then don't skip the issue template like you did here. Fill it all in as asked.

**Comment by JPRuehmann** [comment]
I´ve done that as far as I could!
You have closed it without reading and at least one Question if you don´t understand what I mean.

**Comment by gorhill** [comment]
You have ignored the template here and in the other issue you opened, and merely pointed out that something is being blocked without making the case that whatever is blocked should not be blocked as per your filter lists/rules/settings. Here is not the place to ask for support, this is what <https://www.reddit.com/r/uBlockOrigin/> is for.

If you like uBO, then do not burden volunteers with invalid issues. If this keeps happening, I will close the repo to outsiders.

**Comment by JPRuehmann** [comment]
I love uBlock but I hate that MS Service Mentality.
