### ISSUE TITLE
Clicking "Apply Changes" does nothing

### ISSUE THREAD

**Issue by stdedos** [uBlockOrigin/uBlock-issues#1459]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

![image](https://user-images.githubusercontent.com/133706/105505631-dcf69580-5cd1-11eb-9296-ff976a52fc1f.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: v1.32.4
* Browser Name and version: Chrome 87.0.4280.88
* Operating System and version: Win10

**Comment by uBlock-user** [comment]
Fill in the template completely.

**Comment by gorhill** [comment]
What does the dev

**Comment by gorhill** [comment]
What does dev console show?

**Comment by stdedos** [comment]
Oops, sorry - I totally forgot to paste it:
```js
dashboard.js:87 Uncaught TypeError: Cannot read property 'localStorage' of undefined
    at loadPane (dashboard.js:87)
    at loadDashboardPanel (dashboard.js:95)
    at HTMLSpanElement.onTabClickHandler (dashboard.js:104)
```
I was searching for https://github.com/gorhill/uBlock/wiki/Resources-Library 😀 

Any navigation back and forth helps with this issue.

**Comment by gorhill** [comment]
> Cannot read property 'localStorage' of undefined

This means `vAPI` is undefined, which is never supposed to happen. How did you open the dashboard page?

**Comment by stdedos** [comment]
As "normal" I would say:
![image](https://user-images.githubusercontent.com/133706/105543299-50180000-5d02-11eb-8d39-44eef7dd3781.png)

**Comment by gorhill** [comment]
Is it possible you were updated to 1.32.4 after the dashboard was opened?

**Comment by stdedos** [comment]
I don't know how would that be possible or how would I recognise it.
I haven't restarted my browser since a month ago.

------

I killed the extension and the tabs, I restarted everything; it seems I cannot replicate it.
