### ISSUE TITLE
Ability to log and send events to an external source like elastic

### ISSUE THREAD

**Issue by micahf-rh** [uBlockOrigin/uBlock-issues#1460]
Is there a way to stream the logger info to an external device in order to log and track events from all users where this has been deployed to via Google Extensions policies?

The idea is to have a way to view the data in a tool like Elastic across all of our google domain users.

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment]
> Is there a way to stream the logger info to an external device in order to log and track events from all users where this has been deployed to via Google Extensions policies?

No. uBO avoids any connections to external services. For example it was declined to support syncing by uploading settings to google drive.

But for deployed instances.. Hmmm...

**Comment by gorhill** [comment]
Closing this as this is a feature request devoid of any actual details of what is being asked. Such feature request for what appears to be non-trivial shouldn't be made with only two sentences, this should be submitted as a design document with all the details of how it's supposed to work and all the foreseeable caveats and also assessment of maintenance burden.
