### ISSUE TITLE
In popup, the Reload button becomes immediately hidden if re-enabling the large power button too quickly

### ISSUE THREAD

**Issue by darkred** [uBlockOrigin/uBlock-issues#1461]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

If you re-enable the large power button in the popup quickly so that the `Blocked on this page` and 
`Domains connected` counters are still not populated,
then the Reload button appears momentarily, then becomes hidden.

### A specific URL where the issue occurs

Every site, e.g. `https://rarbgproxy.org/torrents.php`

### Steps to Reproduce

1. Make a fresh Chrome 88/Firefox 84 profile,
2. install uBO 1.32.5.103 beta or uBO 1.32.4 stable
3. navigate to `https://rarbgproxy.org/torrents.php`
4. open uBO popup, click the large power button to disable on the site, and then click Reload
5. Then, quickly, so that the `Blocked on this page` and `Domains connected` counters are still not populated, click the large power button to re-able.

Here is a [video capture](https://github.com/uBlockOrigin/uBlock-issues/files/5862837/Video_2021-01-24_194526.zip) (.wmv 0.3 MB, zipped)

### Expected behavior:

The Reload button shouldn't disappear.

### Actual behavior:

The Reload button appears momentarily, then disappears.

### Your environment

* uBlock Origin version: 1.32.5.103 beta or uBO 1.32.4 stable
* Browser Name and version: Chrome 88/Firefox 84
* Operating System and version: win10

**Comment by 8bit-coder** [comment]
I tried it, and I couldn't reproduce the issue no matter what I did, this needs more research done into it if it's reproducible.

**Comment by darkred** [comment]
You haven't followed the STR correctly.
The issue still occurs consistently, *exactly* as shown in my video capture.
I even reproduced it just now multiple times, using latest uBO dev 1.34.1b5 in Chrome 89/Firefox 88 .

**Comment by darkred** [comment]
I confirm the issue is fixed in the new beta.
Thank you, @gorhill .
