### ISSUE TITLE
uBlock Origin UI optimize for ungoogled-chromium Android

### ISSUE THREAD

**Issue by ungubajue90k** [uBlockOrigin/uBlock-issues#1464]
- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin dashboard is not optimized for mobile view in ungoogled-chromium android.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Install .apk file ungoogled-chromium Android
https://github.com/ungoogled-software/ungoogled-chromium-android/releases/tag/87.0.4280.141-2-extensions

2. download the latest release uBlock Origin version for chromium https://github.com/gorhill/uBlock/releases/download/1.32.4/uBlock0_1.32.4.chromium.zip

3. unzip the .zip file

4. open ungoogled-chromium android and type `chrome://extensions/` -> enable Developer Mode -> Load unpacked -> tap on the left "Files" and select the folder `uBlock0.chromium` in "Files" -> installed

![Screenshot_2021-01-25-22-06-24-855_org ungoogled chromium extensions stable](https://user-images.githubusercontent.com/77856086/105766109-9f0ba280-5f59-11eb-8613-7e9449e56db5.jpg)

5. open uBlock Origin dashboard and the UI is not optimized for mobile devices.

6. see my screenshot
![Screenshot_2021-01-25-22-04-31-496_org ungoogled chromium extensions stable](https://user-images.githubusercontent.com/77856086/105765981-75527b80-5f59-11eb-9762-d65b0444afad.jpg)
![Screenshot_2021-01-25-22-05-00-725_org ungoogled chromium extensions stable](https://user-images.githubusercontent.com/77856086/105765994-7b485c80-5f59-11eb-9d62-f8cda933311a.jpg)

### Expected behavior:

uBlock Origin dashboard is fully optimized for mobile view.

### Actual behavior:

uBlock Origin dashboard is not fully optimized for mobile view. The view looks more like a desktop view that has been zoomed.

A seamless mobile UI for Android should be created.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Ungoogled Chromium Extension Android - 87.0.4280.141 (428014110)
* Operating System and version: Android 10 and Android 11

**Comment by gwarser** [comment]
This is mobile view. Only for some reason fonts are a little bigger. Plus your screen is narrow.

**Comment by ungubajue90k** [comment]
> This is mobile view. Only for some reason fonts are a little bigger. Plus your screen is narrow.

The display size is 6.53 inches, which should be enough to show and optimize it well in this position. How does it look on your Android device?

**Comment by gorhill** [comment]
What you are reporting **is** the user interface for small screen. I absolutely do not intend to do more work than I already did on this.
