### ISSUE TITLE
[Feature Request] WebGL Toggle

### ISSUE THREAD

**Issue by msalamonski** [uBlockOrigin/uBlock-issues#1467]
Same way how there's an easily accessible enable/disable toggle+default enable/disable for JavaScript, remote fonts, cosmetic filtering, etc., it would be nice to have a WebGL toggle; for example, one important site I use needs it, but if any other site uses it then I prefer not to use that site at all. I'm not sure if this toggle would be useful or pointless, but if it's not too much work it'd be very nice to have.

**Comment by gwarser** [comment]
"Nice to have" is not a good reason. Fill the template.

Also https://github.com/gorhill/uBlock/issues/3543
