### ISSUE TITLE
Android body > :has-text doesn't work !

### ISSUE THREAD

**Issue by webglgames** [uBlockOrigin/uBlock-issues#1468]
Android 11
Firefox 85.1.0  (https://github.com/mozilla-mobile/fenix/releases/download/v85.1.0/fenix-85.1.0-arm64-v8a.apk)
uBlockOrigin 1.32.4

my filters
----------
! blockeaza siteuri pentru oameni sclerozati !
##body > :has-text(/porn/i)
##body > :has-text(/erotic/i) 
##body > :has-text(/xxx/i)

The aboves work at 100% on/in Windows 10, but not on Android 11.

Please fix this as i don't want to have over 15.000 websites added in the filters.
Thanks

**Comment by mapx-** [comment]
What about this parameter:

`Ignore generic cosmetic filters` ? it should be disabled

**Comment by webglgames** [comment]
Ignore generic cosmetic filters ? it should be disabled
It is disabled.

On Windows 10 works just beautiful, but not on Android 11.

**Comment by mapx-** [comment]
It should be:

```
*##body > :has-text(/porn/i)
*##body > :has-text(/erotic/i)
*##body > :has-text(/xxx/i)
```

**Comment by uBlock-user** [comment]
Set `allowGenericProceduralFilters` to `true` in Adavnced Settings on `Android`, then re-add so filters will get re-compiled.

**Comment by webglgames** [comment]
> It should be:
> 
> ```
> *##body > :has-text(/porn/i)
> *##body > :has-text(/erotic/i)
> *##body > :has-text(/xxx/i)
> ```

Confirmed it works now for android 11 + firefox 85.1.0, many, many thanks.

**Comment by garry-ut99** [comment]
Some fine-tuning:

- `body >` is insufficient, coz it will still leak and won't hide some parts of a website, better to use `html`

- also no need to unnecessarily create a separate filter for each word, when Regex already supports OR operator: `|`
so better to use: `*##html:has-text(/porn|erotic|xxx/i)`
unless you wanted a porn page to contain all of the words, then Regex lacks `AND` operator, so you must use a chained uBO filter: `*##html:has-text(/porn/i):has-text(/erotic/i):has-text(/xxx/i)`
- also `*` might occasionaly hide valid (non-porn) websites which contain porn related words in a non-porn related context, like some educational articles or news, in that case must to exclude such domains: `*##` ==> `~website.com,*##`

**Comment by webglgames** [comment]
> Some fine-tuning:
> 
> * `body >` is insufficient, coz it will still leak and won't hide some parts of a website, better to use `html`
> * also no need to unnecessarily create a separate filter for each word, when Regex already supports OR operator: `|`
>   so better to use: `*##html:has-text(/porn|erotic|xxx/i)`
>   unless you wanted a porn page to contain all of the words, then Regex lacks `AND` operator, so you must use a chained uBO filter: `*##html:has-text(/porn/i):has-text(/erotic/i):has-text(/xxx/i)`, unless you are able to achieve/simulate the `AND` operator in Regex by creating some crazy high-skilled regex
> * also `*` might occasionaly hide valid (non-porn) websites which contain porn related words in a non-porn related context, like some educational articles or news, in that case must to exclude such domains: `*##` ==> `~website.com,*##`

Wow amazing, thanks garry-ut99.
Now i have to apply it to my filters
Btw here is something i created

! rarbg
rarbg.to,rarbgaccessed.org,rarbgmirror.org##.lista2 > .lista > [href="/torrents.php?category=4"],important:upward(.lista2)
rarbg.to,rarbgaccessed.org,rarbgmirror.org##tr:nth-of-type(3) > .header5
rarbg.to,rarbgaccessed.org,rarbgmirror.org##div.divadvscat:nth-of-type(1) > .inputadvscat
rarbg.to,rarbgaccessed.org,rarbgmirror.org##div.divadvscat:nth-of-type(1) > [href^="/torrents.php"]

! 1337x.am
!1337x.am##.coll-1 > [href="/sub/48/0/"],important:upward(.coll-1)
1337x.am##tr:has(> [class] > [href="/sub/48/0/"])
1337x.am##tr:has(> [class] > [href="/sub/73/0/"])
1337x.am##div.list-box > ul > li > [href*="/cat/XXX"]
1337x.am##[href="/popular-xxx"]
1337x.am##[value="/category-search/xxx/XXX/1/"]
1337x.am##nav > .main-navigation > li > [href="https://www.french-stream.to"]
1337x.am##nav > .main-navigation > li > [href="https://thekickasstorrents.to"]
1337x.am##nav > .main-navigation > li > [href="https://piratebay-proxy.org"]
1337x.am##nav > .main-navigation > li > [href="https://cpasbien.to"]
1337x.am##.container > .top-bar-left > .main-navigation > li > [href="https://www.french-stream.to"]
1337x.am##.container > .top-bar-left > .main-navigation > li > [href="https://thekickasstorrents.to"]
1337x.am##.container > .top-bar-left > .main-navigation > li > [href="https://piratebay-proxy.org"]
1337x.am##.hidden-sm.list-box
1337x.am##li.green
1337x.am##.news
1337x.am##footer
