### ISSUE TITLE
More keyboard shortcuts (e.g. whole domain noop rules/whitelist site)

### ISSUE THREAD

**Issue by FelixFrog** [uBlockOrigin/uBlock-issues#1469]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It would be nice to have a dedicated keyboard shortcut to relax the blocking mode not only on the subdomain, but in the whole top-level domain, or even whitelist the websites.

### Steps to Reproduce

1. Install uBlock
2. Go to about:addons
3. Click the gear icon at the topo and then "Manage extensions shortcut"
4. Observe the lack of "Relax blocking mode on tld" or "Whitelist current site"

### Your environment

* uBlock Origin version: 1.32.5rc3
* Browser Name and version: Firefox 84.0.2
* Operating System and version: Mac os Catalina 10.15.7

**Comment by gorhill** [comment]
I prefer to decline this.

I consider disabling uBO a serious operation and I rather have people go through the popup panel so as to minimize accidental disabling.

As for relaxing blocking mode on TLD, I consider this an edge case not worth its own keyboard shortcut.
