### ISSUE TITLE
change "uBlockº:" to "uBO:"

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#147]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] open site <https://www.certyficate.it/adblock/>
2. [Second Step] click subscribe
3. [and so on...]

### Expected behavior:

[What you expected to happen]
![2018-07-27](https://user-images.githubusercontent.com/5884000/43333412-ab3a8aa8-91ca-11e8-8c29-e82806e73948.png)

### Actual behavior:

[What actually happened]
![2018-07-27](https://user-images.githubusercontent.com/5884000/43333104-1030db3e-91ca-11e8-8309-fe041a1c40a3.png)

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: chr 68.0.3440.75
* Operating System and version: w10

**Comment by gorhill** [comment]
Why?

**Comment by gorhill** [comment]
These strings are handled at <https://crowdin.com/project/ublock>, if you disagree with a translation, this needs to be brought up on Crowdin.
