### ISSUE TITLE
|https:// lockdown filter does not work

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1470]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

EasyList uses many lockdown filters like `|https://$image,script,stylesheet,subdocument,third-party,xmlhttprequest,domain=pirateproxy.live|thehiddenbay.com|thepiratebay.org|thepiratebay.vip|thepiratebay10.org` but this is not working.

### A specific URL where the issue occurs

`https://thepiratebay.org/index.html`

### Steps to Reproduce

1. Visit the site with logger opened will be enough, but optionally you can add
```
@@||torrindex.net^$image,script,stylesheet,domain=thepiratebay.org,badfilter
|https://$image,script,stylesheet,subdocument,third-party,xmlhttprequest,domain=thepiratebay.org
```
to make sure requests to `torrindex.net` for example are not blocked by the filter. If you change it to
`*$image,script,stylesheet,subdocument,third-party,xmlhttprequest,domain=thepiratebay.org`
now this blocks requests as expected.

### Expected behavior:

The filter should block any 3p requests starting with https:// with specified types.

### Actual behavior:

No blockage and these filters are useless for uBO.

### Your environment

* uBlock Origin version: 1.32.4 & 1.32.5b0
* Browser Name and version: Firefox 84.0.2 / Chrome 87.0.4280.141
* Operating System and version: Windows 10

**Comment by Yuki2718** [comment]
Hmm...working on one profile. I have to find the difference.

**Comment by gorhill** [comment]
Probably because of `badfilter` for `thepiratebay.org` in uBO unbreak filters.

**Comment by Yuki2718** [comment]
> Probably because of `badfilter` for `thepiratebay.org` in uBO unbreak filters.

Yes, indeed it's just that OMG!
