### ISSUE TITLE
Firefox 85.0 doesn't start with uBlock 1.32.4

### ISSUE THREAD

**Issue by wretchedbanana** [uBlockOrigin/uBlock-issues#1471]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox 85.0 immediately hangs at launch with uBlock 1.32.4 enabled... about half the time. The platform is Arch Linux.

In a simple experiment where I launch Firefox 10 times, 6 hangs after rendering a blank page, and the process has to be killed. 4 times everything works fine.

uBlock, Firefox 85.0, fresh profile: hangs as described 
uBlock disabled: everything's normal
uBlock, Firefox version < 85.0: everything's normal

No visible CPU, memory, I/O spikes during the issue.

I'd be happy to provide more uBlock specific information, logs, etc if you tell me where to find them.

### A specific URL where the issue occurs

Blank homepage.

### Steps to Reproduce

1. Launch Firefox

### Expected behavior:

Firefox should work.

### Actual behavior:

It hangs. Cannot interact with window. Process has to be killed.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox 85.0
* Operating System and version: Arch Linux, 5.10.10-arch1-1

**Comment by uBlock-user** [comment]
Try this-- `about:config`  >> `browser.startup.preXulSkeletonUI` = `false`

**Comment by gwarser** [comment]
>Arch Linux, 5.10.10-arch1-1

Old Nvidia GPU (old drivers) by any chance?

**Comment by wretchedbanana** [comment]
> > Arch Linux, 5.10.10-arch1-1
> 
> Old Nvidia GPU (old drivers) by any chance?

Nvidia but not old drivers. I was using 1050 Ti with nvidia-460.39-1

That being said, **the new package build of the same driver version (nvidia-460.39-2) that got promoted to the main repos today fixes the issue**. I haven't been able to find a relevant bug report in Arch / Nvidia or identify the change that fixed the issue myself, I'd appreciate pointers if you know what this was.

**Comment by gorhill** [comment]
> Cannot interact with window. Process has to be killed.

It's a browser issue, uBO is just HTML/CSS/JS and in its own process, your browser shouldn't be locked up by any extension.

**Comment by wretchedbanana** [comment]
> > Cannot interact with window. Process has to be killed.
> 
> It's a browser issue, uBO is just HTML/CSS/JS and in its own process, your browser shouldn't be locked up by any extension. You should launch from command line and see what errors are reported in there when this happens and report to browser devs.

Agreed, and just for the record, I'm also pursuing that path, but no good debug info to present at the moment. Nothing unusual in command line, no crash reports, or any other information useful for debugging. I'm only able to reproduce this with uBO so far.

**Comment by gorhill** [comment]
> I'm only able to reproduce this with uBO so far.

Well things that uBO does differently from other blockers as far as I know:

- WebAssembly: you can disable use of WebAssembly by toggling `disableWebAssembly` to `true` ([ref](https://github.com/gorhill/uBlock/wiki/Advanced-settings#disablewebassembly))
- DNS lookups: you can disable cname-uncloaking by toggling `cnameUncloak` to `false` ([ref](https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnameuncloak))

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/firefox/comments/l7xgei/firefox_85_freezes_after_start_with_solution/

**Comment by wretchedbanana** [comment]
> https://www.reddit.com/r/firefox/comments/l7xgei/firefox_85_freezes_after_start_with_solution/

Seems to be unrelated. I start testing with a fresh container and install Firefox from scratch. 

In other news, certain other extensions seem to cause the same issue according the Arch Linux bug reports: https://bugs.archlinux.org/task/69457
