### ISSUE TITLE
Popup matrix is missing green allow button / noop does not change behavior

### ISSUE THREAD

**Issue by relikd** [uBlockOrigin/uBlock-issues#1474]
### Prerequisites
- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have configured uBO to block everything by default and only allow specific domains for specific websites. However with the newest version 1.32.4 (I just updated from a half year older version) this is no longer possible. E.g., `eff.org` uses `map.fastly.net` and there is no way to mark this green (allow) in the popup matrix. I would prefer to use noop instead, but this does not change anything in the filter process.

In fact, this issue that a noop wont change the bahavior only came up one or two days ago. Github stopped showing the profile icons for all users. That is also the reason I updated to the newest version, because I thought it may fix the problem.

![screen](https://user-images.githubusercontent.com/1321720/106138131-07ca6900-616c-11eb-8b3a-de3860cfc76a.png)

### A specific URL where the issue occurs

https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better
https://github.com/

### Steps to Reproduce

1. open uBO popup
2. click more several times until the matrix shows up
3. try to allow `map.fastly.net`
4. reload page

### Expected behavior:

The page should allow requests to that domain.

### Actual behavior:

Nothing changes

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox 85.0
* Operating System and version: macOS 10.15.7

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.28.0

**Comment by relikd** [comment]
That explains the missing button, thanks. However the issue with `fastly.net` still persists and noop does not help here.

**Comment by uBlock-user** [comment]
> However the issue with fastly.net still persists and noop does not help here.

force update EasyPrivacy.
