### ISSUE TITLE
Add support for smaller compact popup window size

### ISSUE THREAD

**Issue by relikd** [uBlockOrigin/uBlock-issues#1475]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Even though this is normal behavior I'd like to open this issue because the popup (with open matrix) takes a significant portion of my small computer screen. The current font size and UI distances are gread for readability but I prefer the older compact design.

I understand that this is probably preference and assume this issue will be closed immediatelly, but I still wanted to post my concerns.

### A specific URL where the issue occurs

not applicable

### Steps to Reproduce

not applicable

### Expected behavior:

not applicable

### Actual behavior:

not applicable

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: latest Chrome and Firefox
* Operating System and version: macOS 10.15.7

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#popupfontsize
