### ISSUE TITLE
Trouble managing extension

### ISSUE THREAD

**Issue by MarjaE2** [uBlockOrigin/uBlock-issues#1477]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I tried to check whether uBlock Origin had updated, and to update it if not. Using Firefox 84 on Macbook Air 11". It's not as easy as it should be.

### A specific URL where the issue occurs

about:addons

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. In Firefox, visit about:addons. Due to Firefox bugs, this is no longer searchable. Scrolling doesn't work due to Firefox bug 1658601. Searching doesn't work due to Firefox bug 1584111, introduced by bug 1263313. Page Down isn't available on this device.
2. In Firefox, try the menu bar icon. No visible option to manage the extension from here, check for updates, etc.

### Expected behavior:

Since Firefox about:addons is broken, an option in the menu bar might help.

### Your environment

* uBlock Origin version: v1.32.4
* Browser Name and version: Firefox 84.0.2.
* Operating System and version: MacOS 10.14.6.

Screen size 11", minimum font size 20.

**Comment by gorhill** [comment]
I don't understand what you are reporting or asking.

**Comment by MarjaE2** [comment]
I tried to check whether uBlock Origin had updated, and to update it if it had not updated. I was unable to do so.

**Comment by gorhill** [comment]
What exactly is this "appropriate page" you are referring to?

**Comment by MarjaE2** [comment]
With Page Down:

![Screen Shot 2021-01-30 at 3 20 09 PM](https://user-images.githubusercontent.com/12875862/106367172-b9a19b00-630e-11eb-8f22-3062bf9969db.png)

**Comment by gorhill** [comment]
You can reach that page using right-click on the toolbar icon and pick _"Manage Extension"_.

In any case, that page is under Firefox control, uBO has no way to link to this page.
