### ISSUE TITLE
Whitelisting a site on Chromium Edge still blocks resources fetched by service worker

### ISSUE THREAD

**Issue by Lucent** [uBlockOrigin/uBlock-issues#1478]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When the service worker takes over and attempts to handle the fetch for AdSense after whitelisting, uBlock claims in its logger that the request was whitelisted but the browser console shows the request fails. This does not occur on the initial load, only after the service worker takes over.

### A specific URL where the issue occurs

https://ptable.com/

### Steps to Reproduce

1. Visit Ptable after whitelisting and clearing cache. Ads load.
2. Reload Ptable so requests pass through service worker.
3. Fetch fails: The FetchEvent for "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" resulted in a network error response: an object that was not a Response was passed to respondWith(). extra-59fbde3d.js:10 GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_FAILED

### Expected behavior:

Ads show up properly.

### Actual behavior:

Ads are still blocked.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Edge Version 88.0.705.56 (Official build) (64-bit)
* Operating System and version: Windows 10 19042.746

**Comment by gorhill** [comment]
Fixed in next dev build, I will push an emergency fix for 1.33.0 in the coming days.
