### ISSUE TITLE
Generic hiding rules don't work fast enough

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1479]
Configuration: Firefox 85.0, Google Chrome 88.0.4324.104
uBlock Origin 1.32.5.104, default + EasyList Cookie

Steps to follow to reproduce the problem:

1. Close the browser
2. Open  browser
3. Open `https://ubuntu.com/blog`

Actual result: The element .cookie-policy is displayed for a while before the `##.cookie-policy` rule is triggered.

Expected Result: The element .cookie-policy is not shown at all.

This problem is absent when using Adblock Plus and AdGuard.

**Comment by gorhill** [comment]
When you say "for a while", what's the estimate?

I see it a fraction of second, maybe 1/10 of a second only. What I see on my side is expected, that's how uBO works as per <https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters>. ABP/AdGuard injects all generic cosmetic filters as a gigantic stylsheet in every page/frames, and the price paid with this approach is <https://twitter.com/gorhill/status/1345042527171325953>, which needless to say is not going to happen in uBO.

**Comment by dimisa-RUAdList** [comment]
Thanks for the detailed answer. I am aware of this feature and specifically contain duplicates of generic rules for some sites in the RU AdList filters, for those cases when elements are in the visible part of the page at the first load. Now I will be able to provide a link to your answer to those users who ask a question regarding this delay. Thanks again.
