### ISSUE TITLE
Style injection too early.

### ISSUE THREAD

**Issue by whileloopa** [uBlockOrigin/uBlock-issues#148]
### Description

The earlier version of uBO (1.15.2) inject style sheet after the webpage load it's own style sheets, so uBO's style-injecting cosmetic rules can overwrite the style of DOM elements. But the new version of uBO inject style sheet too early, that uBO's injected styles (without !important mark) cannot override the webpage's own styles.

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Chrome 67
* Operating System and version: Win7

**Comment by uBlock-user** [comment]
> that uBO's injected styles (without !important mark) cannot override the webpage's own styles.

That's because uBO now uses user styleSheets, that's why you need to use `!important` to override webpage's styles. Not a bug.

**Comment by gorhill** [comment]
> uBO's injected styles (without !important mark) cannot override the webpage's own styles.

That is just plain false.

uBO has always injected styles as early as possible. Even better now, it does so using user stylesheets, so that now web pages can never override them. Before this uBO was modifying the style attribute of elements when needed, again preventing web page stylesheets from overriding uBO (they could try remove uBO's style though).

You failed to backup your flawed findings by providing reproducible cases as requested when filing such issues.

**Comment by gorhill** [comment]
See <https://en.wikibooks.org/wiki/Internet_Explorer/Adding_User_Styles>.

**Comment by gwarser** [comment]
This is about specificity and user vs author origin - by design https://www.w3.org/TR/css3-cascade/#cascading-origins

**Comment by gorhill** [comment]
Actually as per spec, OP is right that now styles injected without the `important` modifier have _less_ precedence than the page's own styles (as per spec), while before they had same precedence -- in which case things such as `important`, specificity, or order (unreliable), would decide which styles wins. 

However `important` has always be the way to go when injecting styles, and in case of similar importance, the trick was to come up with a higher specificity -- order of injection has _never_ been a consideration when crafting `:style()` cosmetic filters, uBO always tried to inject as soon as possible. All this is now a thing of the past with user styles in Chromium 66 and above.
