### ISSUE TITLE
Add setting to allow other WebExtensions that cannot modify response headers to replace HTTP responses with data: URLs

### ISSUE THREAD

**Issue by Jaaap** [uBlockOrigin/uBlock-issues#1481]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

FEATURE REQUEST: add a setting for allowing "data: URLs" for other WebExtensions that cannot modify the CSP (Content-Security-Policy) header as only 1 WebExtension is allowed to modify a response-header at a time.

### A specific URL where the issue occurs

https://haveibeenpwned.com/

### Steps to Reproduce

To see the problem, you need to have 2 WebExtensions installed that both try to modify HTTP response headers.
1. Install this addon: https://addons.mozilla.org/en-US/firefox/addon/jslibcache/
2. Go to JSLibCache's popup > Settings > Other addons and make sure it is **UN**checked
3. In uBlock₀ make sure that it will modify the script-src property of the CSP header (i think it will always do that but you may have to disable 3rd-pary scripts.
4. In uBlock₀, add this rule to Dashboard > My rules: `* cdnjs.cloudflare.com * noop`
5. Browse to https://haveibeenpwned.com/

### Expected behavior:

JSLibCache will replace the requests to https://cdnjs.cloudflare.com/ajax/libs/*.js with a "data:application/javascript;charset=utf-8,..." URI and this is **allowed** by the CSP header, modified by uBlock₀.

### Actual behavior:

JSLibCache will replace the requests to https://cdnjs.cloudflare.com/ajax/libs/*.js with a "data:application/javascript;charset=utf-8,..." URI and this is **dis**allowed by the CSP header, modified by uBlock₀.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox Developer Edition 86.0b3 (64-bit)
* Operating System and version: macOS 11.1

**Comment by gorhill** [comment]
I don't understand what is being reported. From what I can gather, there seems to be a misunderstanding of when uBO modifies/adds `script-src` CSP directive, it does so only when inline scripts are blocked, or when JS is wholly blocked. Beyond this I don't understand the rest of the comments.

**Comment by Jaaap** [comment]
Oh, it may be because i have fonts disabled?

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/243016/106391282-d7ddc880-63ec-11eb-9fbc-9837c8f1dd48.png">

**Comment by gorhill** [comment]
The reason the template asks for _"uBlock Origin with default lists/settings"_ is to avoid invalid issues being opened as a result of someone's custom settings causing the issue. Even with adding rules as what I see in your screenshot, I am unable to get your result, the page visually renders fine. This means something else on your side is causing `script-src` violation to be triggered -- maybe custom filters or another extension. The logger's is meant to investigate and rule this sort of filtering issues, which is merely uBO doing what it's told to do.

**Comment by Jaaap** [comment]
You're right, im sorry. That is my bad.

I can consistently reproduce the problem by toggling the "block remote fonts" button in uBlock₀ (and toggling the "Other addons" checkbox in JSLibCache).
When uBlock₀'s font block is **in**active and JSLibCache's "Other addons" is **un**checked, all works fine.
When uBlock₀'s font block is active the data URLs are blocked by the CSP, regardless of JSLibCache's "Other addons" setting (if it is installed **after** uBlock₀, installation order matters).

**Comment by gorhill** [comment]
Ok I can reproduce now when blocking fonts, somehow this was not happening before -- the only change I did was to removing/reinstalling JSLibCache.

So without investigating further yet, if I understand correctly is that JSLibCache adds a `data:` permission to the existing `script-src` CSP directive set by the server. However, uBO does not modify existing CSP directives, it just add new ones.

The issue seems to be how Firefox deals with the two extensions handling CSP headers, one modifying an existing CSP directive, and the other add a CSP directive.

**Comment by Jaaap** [comment]
Yes and Chrome does this too:
https://developer.chrome.com/docs/extensions/reference/webRequest/#types
> (only one extension may modify responseHeaders for each request)

This is rather unfortunate imho.

**Comment by gorhill** [comment]
This is where Firefox merge CSP headers from multiple extensions: https://searchfox.org/mozilla-central/rev/8d290159a6f80f5e33e2bd35c0e4b2df283a18c5/toolkit/components/extensions/webrequest/WebRequest.jsm#201-210

There is nothing uBO can do really, which modified CSP header Firefox uses in the end is out of control of uBO or any extension. The workaround is to let the user pick which extension should be allowed to modify the CSP header and to prevent other extensions from interfering.

uBO may want to modify the CSP headers when:

- Blocking all JS through no-scripting per-site switch
- Block fonts through no-remote-fonts per-site switch
- Blocking inline scripts
- Enforcing `csp=` filters

This means other extensions modifying the CSP headers could seriously undermine uBO as a content blocker if the modification to CSP headers by other extensions are picked by the browser over uBO's own modifications.

**Comment by gorhill** [comment]
So if I understand correctly, you are asking that uBO injects a `data:` permission for `script-src` because some other extension may need these.

If so, I decline. By principle, uBO has always been against relaxing a server's CSP policies, including when not relaxing was breaking uBO's own features (such as when neutered scripts were injected through `data:` URIs), so let alone doing this just for the sake of other extensions.
