### ISSUE TITLE
SSD Drive Trashing by uBlock Origin v AdGuard !

### ISSUE THREAD

**Issue by webglgames** [uBlockOrigin/uBlock-issues#1482]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
SSD Trashing by uBlock Origin v AdGuard !

As normal can be, every extension is writing his/her database(s) on your SSD.
![Clipboard](https://user-images.githubusercontent.com/61231114/106600999-ce2aa100-6563-11eb-83ef-c0097a170acb.jpg)
![ublockorigin](https://user-images.githubusercontent.com/61231114/106601021-d551af00-6563-11eb-9bf1-7711ecf4edf6.jpg)
![adguard](https://user-images.githubusercontent.com/61231114/106601036-d8e53600-6563-11eb-984e-19e95f1b64b9.jpg)

Note: Both AdGuard & uBlock Origin have all the filters enabled from within their respective options !
No take a look at the size of AdGuard databases as they show a compute of just 12.1 MB per total. More the same databases persist and don't grew in size or double or triple as uBlock Origin databases are doing.

uBlock Origin databases are starting shy at about 14.9MB then after a quick net navigation begin to double since uBlock Origin is using chrome (Split) as that means 2 processes of the same extension.
So 2 processes = 1 proccess per each mode Normal or Incognito resulting in double size of the databases since each one utilize his own database. So from the shy 14.9MB now the databases are grown all of the sudden to 30 MB.
Now that's not all, as you happy navigate the web the databases will continue to grow as now per total it shows 36.6MB..
And i quit testing further since my past experience with uBlock Origin it show a value of over 60 MB per databases !! Come on is this a joke ?!
Now to be honest uBlock Origin is trashing your SSD drive, as it continuously writes that databases that keep growing and growing like some hungry kid.

Ok, ok but how about AdGuard..well here is how AdGuard operates:
AdGuard databases stays constant at 12.1 MB (all lists enabled) and it doesn't grow like uBlock Origin or trashing your SSD drive since AdGuard it will unpack that 12.1 MB databases into your RAM..yes RAM and it is utilizing the unpacked databases from your RAM only !
That's a very bright idea from AdGuard developers !
More AdGuard is using 1 proccess per both all Normal & Incognito modes that means efficiency and just good programming !

### A specific URL where the issue occurs

Normal or Incognito mode(s)!

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: latest version 1.32.4 used before switching to AdGuard for good
* Browser Name and version: Chrome Dev/Beta/Stable 64bit
* Operating System and version: Windows 10 64bit

**Comment by gorhill** [comment]
YOu don't even mention for how long uBO's instances have been running, which the most important information. From the screenshot, the pid assigned to uBO shows that uBO has been running for much longer, and it's entirely possible uBO had to update its filter lists while AdGuard did not.

**Comment by gorhill** [comment]
You don't even mention for how long uBO's instances have been running, which the most important information. From the screenshot, the pid assigned to uBO shows that uBO has been running for much longer, and it's entirely possible uBO had to update its filter lists while AdGuard did not.

> More AdGuard is using 1 proccess per both all Normal & Incognito modes that means efficiency and just good programming !

I answered to you in [your other issue about this](https://github.com/uBlockOrigin/uBlock-issues/issues/1473) -- if ever AdGuard supports strict-blocking, then it will have no choice to use split mode for it to work. AdGuard not supporting strict-block -- a key feature in uBO -- is what allows it to avoid having to use split mode.

> before switching to AdGuard for good

Great.

---

> AdGuard databases stays constant at 12.1 MB

uBO uses disk storage to store compiled (pre-parsed) version of filter lists and a memory snapshot to ensure fast loading next time it is launched.

When I compare uBO's start time (when a memory snapshot is present) with AdGuard's start time (from its own dev console log) at browser launch, I get uBO fully ready after 1,418 ms, while AdGuard is fully ready after 2,103 ms, and that is with more filter lists enabled in uBO.

uBO is not "trashing" your storage, it's using it judiciously to ensure efficient launch time, as shown in the profiling sessions below:

uBO's launch time: 569 ms (total) - 149 ms (idle) = 420 ms
![a](https://user-images.githubusercontent.com/585534/106611433-f7ccd380-6535-11eb-8353-df385439cfe2.png)

AdGuard's launch time: 1,783 ms (total) - 186 ms (idle) = 1,597 ms
![b](https://user-images.githubusercontent.com/585534/106611620-31054380-6536-11eb-9714-2288b3b406c5.png)

**Comment by gorhill** [comment]
You don't even mention for how long uBO's instances have been running, which the most important information. From the screenshot, the pid assigned to uBO shows that uBO has been running for much longer, and it's entirely possible uBO had to update its filter lists while AdGuard did not.

> More AdGuard is using 1 proccess per both all Normal & Incognito modes that means efficiency and just good programming !

I answered to you in [your other issue about this](https://github.com/uBlockOrigin/uBlock-issues/issues/1473) -- if ever AdGuard supports strict-blocking, then it will have no choice to use split mode for it to work. AdGuard not supporting strict-block -- a key feature in uBO -- is what allows it to avoid having to use split mode.

> before switching to AdGuard for good

Great.

---

> AdGuard databases stays constant at 12.1 MB

uBO uses disk storage to store compiled (pre-parsed) version of filter lists and a memory snapshot to ensure fast loading next time it is launched.

When I compare uBO's start time (when a memory snapshot is present) with AdGuard's start time (from its own dev console log) at browser launch, I get uBO fully ready after 1,418 ms, while AdGuard is fully ready after 2,103 ms, and that is with more filter lists enabled in uBO.

uBO is not "trashing" your storage, it's using it judiciously to ensure efficient launch time, as shown in the profiling sessions below:

uBO's launch time: 569 ms (total) - 149 ms (idle) = 420 ms
![a](https://user-images.githubusercontent.com/585534/106611433-f7ccd380-6535-11eb-8353-df385439cfe2.png)

AdGuard's launch time: 1,783 ms (total) - 186 ms (idle) = 1,597 ms
![b](https://user-images.githubusercontent.com/585534/106611620-31054380-6536-11eb-9714-2288b3b406c5.png)
