### ISSUE TITLE
Filter created from logger disappears from my filters section

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#1486]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Iam creating filters for sites(usually popup producing sites) i encounter through logger...but when looked in my filters section it is not there

iam experiencing this bug from many months

### A specific URL where the issue occurs

Everywhere sites which tend to produce popup ads
eg 

1.
`http://links.worldfree4u-lol.online/?p=9357`

2.
last time i tried to add filters for my use case for `https://github.com/uBlockOrigin/uAssets/issues/8497` sites(`kat2.website`)
 
or any sites

### Steps to Reproduce

1. Go to `http://links.worldfree4u-lol.online/?p=9357`
2. popup ads starts(now fixed by https://github.com/uBlockOrigin/uAssets/commit/ed571c9a17e2c96c0b7023a92a424696ec64bd57)
3. move to logger then create filters through logger only like eg i created 
```
||bwvnmbhuuhalr.com^
||nnolljzcxzud.com^
```
or any `^$popup` filters

4. then moved to my filters section ,created filters were not there to my surprise in "_my filters_" pane
5.
this problem also with `^$popup` filters created from logger

### Expected behavior:

filters should be visible in my filters section

### Actual behavior:

filters not there in my filters section

### Your environment

* uBlock Origin version:1.33.1b1(opera) & 1.33.2(firefox nightly android) 
* Browser Name and version: opera browser 73.0.3856.344 & firefox android nightly latest
* Operating System and version: win10 & android 

### Notes
Recorded video of problem wrt firefox A nightly
`gofile.io/d/dLo7Up`
(pass- Nyui78)

Any other logs needed i will provide

**Comment by gorhill** [comment]
> when looked in my filters section it is not there

Is the _"My filters"_ pane already opened when you create the filters from the logger?

**Comment by ghajini** [comment]
yes opened but i reloaded again to take effect of filters

**Comment by gorhill** [comment]
> yes ''my filters'' pane opened but i ''reloaded'' again to take effect of filters

When I force a reload of the _"My filters"_, I do see the two filters appended at the end, so I am unable to reproduce what you report.

**Comment by gorhill** [comment]
Ok I see you posted a video, I tested on Firefox Nightly. I will test on Firefox Android when I find the time.

**Comment by ghajini** [comment]
> 
> When you say "I 'reloaded'", what did you reload?

i mean tab/window containing `ubo-dashboard` ,also swapped between my filters and filter lists

also this problem is also with dev build wrt opera browser not just firefox A ubo version

**Comment by gorhill** [comment]
By the way, in that video you attached, the issue was caused by <https://github.com/gorhill/uBlock/commit/b05347708710ed940f966cd500afb72a1ef9fba1>, which fix was part of [1.33.0](https://github.com/gorhill/uBlock/releases/tag/1.33.0).

**Comment by ghajini** [comment]
Yes iam aware of that commit (1.32.3b1) and now 1.33.*
But simply it doesn't work for me...

**Comment by gorhill** [comment]
I can't reproduce with Opera either. Somebody else will have to reproduce to confirm there is an issue -- I can't reproduce any issue beside that we have to force a reload of _"My filters"_ to see the newly added filters.

**Comment by ghajini** [comment]
Closing
