### ISSUE TITLE
Add scrollbar to the domain list inside dashboard

### ISSUE THREAD

**Issue by github-account1111** [uBlockOrigin/uBlock-issues#1488]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Scroll wheels aren't as universal as left- and right-click buttons. They malfunction on some mice and don't exist at all on others. I think whenever there's a scroll list, a scroll bar is necessary for mere accessibility.

### A specific URL where the issue occurs

https://www.reddit.com/r/uBlockOrigin/

### Steps to Reproduce

1. Click on the uBo icon.

### Expected behavior:

Scrollbar to the right of the domain list that scrolls through the listed domains. 

### Actual behavior:

No scrollbar. Forced to use scroll wheel.

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Firefox 85
* Operating System and version: Windows 10 1809 64-bit

**Comment by gwarser** [comment]
This scroolbar:

![image](https://user-images.githubusercontent.com/886325/107143836-832fd580-6937-11eb-8275-aca8040f7a76.png)

???

**Comment by gorhill** [comment]
Closing as invalid -- there are scrollbars wherever needed in uBO. If there is really an issue, it then needs better description of how to reproduce on our side along with screenshots.

**Comment by github-account1111** [comment]
> 
> 
> This scroolbar:
> 
> ???

Yes sorry, I never expected a scrollbar to be on the left, so I didn't even look there. Odd decision, if you ask me, as you have to move your mouse more.
