### ISSUE TITLE
Continue where I left off on Chromium does not remove all ads hidden/deleted when browser closed

### ISSUE THREAD

**Issue by maiux** [uBlockOrigin/uBlock-issues#1489]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using "Continue where I left off" in Chromium 88.0.4324.96 (woolyss mac-stable-sync-marmaduke) on macOS, restoring 23 tabs (I know they are quite a lot) the filters loose some element removal on the pages. Made this on 2,3 GHz Intel Core i9 8 core with 16 GB 2667 MHz DDR4
 
### A specific URL where the issue occurs

https://www.ansa.it
https://www.corriere.it

### Steps to Reproduce

1. Set Chromium with "Continue where I left off"
2. Open 23 tabs on different pages
3. Close Chromium
4. reopen Chromium and see ads appearing

### Expected behavior:

ads hidden/removed as when I left off

### Actual behavior:

ads visible

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Chromium 88.0.4324.96
* Operating System and version: macOS Catalina 10.15.7

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready
