### ISSUE TITLE
Cosmetic filter displayed incorrectly when selected in logger

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#149]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The cosmetic filter which is added in My Filters is not the one displayed when selecting the cosmetic filter at the logger.

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Add `google.com##body > div > div .jsb` to _My Filters._
2. Browse to` google.com`, open the logger and refresh to populate.
3. Select the aformentioned filter in the logger.

### Screenshot

![](https://camo.githubusercontent.com/ad3cad129e7263aa94868733f2e117c5810d8746/68747470733a2f2f692e6779617a6f2e636f6d2f38343931316561326632303331343636643139316634653131376333366433322e706e67)

### Expected behavior:

`google.com##body > div > div .jsb` is shown when selected, as that's the filter added in _My Filters_.

### Actual behavior:

`google.com##body &gt; div &gt; div .jsb` is shown when the filter is selected in _My Filters_.

### Your environment

* uBlock Origin version: 1.16.15b6
* Browser Name and version: Chromium 70/Firefox 63
* Operating System and version: Win 10

**Comment by gwarser** [comment]
d5f40b90f639bfeadaa28c811a0fefecd5c384d1 is the first bad commit
commit d5f40b90f639bfeadaa28c811a0fefecd5c384d1
Author: Raymond Hill <rhill@raymondhill.net>
Date:   Sun Jul 22 08:14:02 2018 -0400

    fix #2179

https://github.com/gorhill/uBlock/commit/d5f40b90f639bfeadaa28c811a0fefecd5c384d1
