### ISSUE TITLE
Invalid network filters suggested in element picker

### ISSUE THREAD

**Issue by eisamstiel** [uBlockOrigin/uBlock-issues#1494]
url: `https://www.elitepvpers.com/forum/`
![Screenshot_2021-02-09 elitepvpers](https://user-images.githubusercontent.com/78649417/107389727-4f9ba980-6af7-11eb-8085-eb3e5755f6e7.png)

**Comment by PIZZA90** [comment]
other example in twitch: `||s*`

![Captura3](https://user-images.githubusercontent.com/33556647/107657135-29a40f80-6c85-11eb-984d-1556b297aca6.PNG)

**Comment by PIZZA90** [comment]
is this fix for a possible next ubo update? **1.33.2+**?

**Comment by JobcenterTycoon** [comment]
@ryanbr ads are back now they use `rebrand.ly`

**Comment by gwarser** [comment]
> is this fix for a possible next ubo update? **1.33.2+**?

Fixed in beta, will be in next stable update.

**Comment by eisamstiel** [comment]
still not fixed ...

**Comment by gwarser** [comment]
Screenshot? 

Looks like this on on my side, Firefox, uBO 1.34:

![image](https://user-images.githubusercontent.com/886325/110985190-6b030a00-836c-11eb-9788-318cf79063ed.png)

**Comment by PIZZA90** [comment]
> `https://www.elitepvpers.com/forum/call-duty/4912925-anyone-got-mw-unlocker-recommendations.html`

`elitepvpers.com##[href^="https://bit.ly/"],[href^="https://aimexcheats.com/"],[href^="https://aimex.xyz/"]`

the vertical banner sometimes changes the URL, and image 😁

**Comment by JobcenterTycoon** [comment]
ads are back (they just changed `pass `to `bypass`)

**Comment by JobcenterTycoon** [comment]
Ads are back.

Whats about: `elitepvpers.com##a[target="_blank"][rel^="nofollow"]:not([href*="trello.com"])` ?

**Comment by gwarser** [comment]
Please use https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc for filter issues.

**Comment by freezer2022** [comment]
> ghost: https://github.com/uBlockOrigin/uBlock-issues/issues/1494#issuecomment-776148038 : **using uBO picker:** `||*.* `

Pardon for necroposting, but what is interesting is that it is a visual duplicate (but different internally/technically)  of:

- > https://github.com/uBlockOrigin/uBlock-issues/issues/1071: Element picker suggests the rule `||*.*`
