### ISSUE TITLE
Strict blocking page: Click button to copy URL

### ISSUE THREAD

**Issue by PaulEwe** [uBlockOrigin/uBlock-issues#1497]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, when visiting the Strict blocking page you have the option to go back and to proceed to the web page by disabling strict blocking. 
But sometimes I want to copy the blocked URL e.g. to continue in another browser.

Right now you need to select the URL and CTRL+C.

Adding a "Copy URL" button would make that a tiny bit faster.

![grafik](https://user-images.githubusercontent.com/29153708/107714304-55e37e80-6ccd-11eb-8b05-77993ab7a75a.png)

### A specific URL where the issue occurs

ublock/document-blocked.html

### Steps to Reproduce

1. Visit a blocked page

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Firefox 85.0.2
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
I prefer to decline this.

You can triple-click on the URL in order to select it all.
