### ISSUE TITLE
please allows the Ublock be available on old firefox version

### ISSUE THREAD

**Issue by piyarad27** [uBlockOrigin/uBlock-issues#1498]
- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
   
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
   
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

I am still using old Firefox version and don't want to update to the quantum version since I prefer it's UI layout and the function that allowed on the touchscreen when using the surface pro tablet So I hope that you would make the Ublock can still be use on the old Firefox legacy version form version 53 and later version

if I posted this request in the wrong page, please tell me where do I need to post the request. Since I try to find where I could submitted the request but cant find a way to contact except here in the github issue and "contact the developer" on chrome which I still doesn't get the reply yet.

###A specific URL where the issue occurs:

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Steps to Reproduce

visited the ublock site

### Expected behavior:

To be able to use the extension on the firefox legacy version

### Actual behavior:

can't download the extension on the old version of firefox (version before 57)

### Your environment

* uBlock Origin version: from ublock 1.33
* Browser Name and version: firefox 
* Operating System and version: 55.0.3

![Screenshot (957)](https://user-images.githubusercontent.com/58059329/107862590-82e57d80-6e02-11eb-8659-c80570c1b9a8.png)

**Comment by AroKol78** [comment]
maybe it will help https://github.com/gorhill/uBlock-for-firefox-legacy (Firefox 45.0 - 56.0)
