### ISSUE TITLE
[Request] please make ublock accessible for FF legacy version users (version 53 and later)

### ISSUE THREAD

**Issue by piyarad27** [uBlockOrigin/uBlock-issues#1499]
>

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I expected the Ublock extension to be able to download on the FF 53 and later version, **not** from FF 57 and later version

### A specific URL where the issue occurs
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. go to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Expected behavior:

I expect to have no warning that my FF version is out of date "This add-on requires a newer version of Firefox "

### Actual behavior:

Latest ublock can't be download on old FF (legacy) version

### Your environment

* uBlock Origin version: 1.33.0 and laterversion
* Browser Name and version: Mozilla Firefox 53.0.3
* Operating System and version: windows 10

**Comment by llacb47** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/releases

**Comment by uBlock-user** [comment]
Duplcate of https://github.com/uBlockOrigin/uBlock-issues/issues/1498
