### ISSUE TITLE
uBO 1.16.1rc2

### ISSUE THREAD

**Issue by gallieni** [uBlockOrigin/uBlock-issues#15]
@gorhill
Instead of complaining duplicate ; solve the problem oh god gorhill lord of the world.
Or Stop Ublock Origin.
Since uBo 1.16.0 craches no webrct in 67 or 68
uBO 1.16.1rc2 resolve nothing.

@uBlock-user 
 and if possible can you stop to suck the dick of gorhill

he already has enough big head.

Fucking developer.

**Comment by uBlock-user** [comment]
Here's your solution --  use a build where webRTC is NOT disabled.
