### ISSUE TITLE
Element Zapper not working on YouTube (Cosmetic Filtering NOT disabled)

### ISSUE THREAD

**Issue by perks** [uBlockOrigin/uBlock-issues#1500]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Similar issues to https://github.com/gorhill/uBlock/issues/3212 , however this occurs even with cosmetic filtering NOT disabled (default, unmodified state). Occurs on Mac OS X Catalina on Chrome

### A specific URL where the issue occurs

https://www.youtube.com
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Install stock UBO addon from chrome store
2. Go to https://youtube.com
3. Attempt do use the element zapper
4. Nothing occurs

### Expected behavior:

Filters properly loading and zapper element being able to be used on the website

### Actual behavior:

UBO refuses to work/load the element zapper on youtube.com

Below is a screenshot of the process. Fresh install with default settings, does not work on YouTube but will work on all other sites (tested with github)
![Ublock Bug](https://user-images.githubusercontent.com/1820298/108117689-2483fd80-7095-11eb-878f-968da0b14cb8.gif)

### Your environment

* uBlock Origin version: uBlock Origin v1.33.2
* Browser Name and version: Google Chrome Version 88.0.4324.150 (Official Build) (x86_64)
* Operating System and version: Mac OS X Catalina 10.15.7

**Comment by uBlock-user** [comment]
Did you give uBO permission to run in incognito mode ?

**Comment by perks** [comment]
@uBlock-user yes, you can see in the gif that it works on other sites (in incognito mode)

**Comment by llacb47** [comment]
Any messages in uBo's console?

**Comment by perks** [comment]
@llacb47 I have the logger open in the gif from start to finish in the gif recording, no messages it seems. I also have the web-developer tools console open while trying to activate the zapper and nothing. I don't know if there is any other console output I should be looking for

**Comment by gorhill** [comment]
The extension's own dev console might have something.

**Comment by perks** [comment]
@gorhill I'm not seeing anything generated in the extension-specific console output. Is there a UI action I can do to trigger a logging event there to see if I am looking at the right thing?

**Comment by gorhill** [comment]
I can't reproduce such issue. When you load the Youtube page, the logger output is anomalous in that it does not show any network requests being fired for Youtube, this is not normal, it's almost as if the browser does not notify uBO of the network events: the logger does not show any network events, the popup panel reports that nothing is being blocked.

**Comment by perks** [comment]
@gorhill yes it is very strange I noticed that as well. If you have any other ideas on how to troubleshoot this I can give it a shot on my end.

**Comment by gorhill** [comment]
I see 4 entries in the logger when you navigate to Youtube. One of them seems to be uBO fetching a filter list -- the initiator is `cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme` -- but quite coincidentally, this occurred right when you navigated to Youtube. Is this entry showing up every time or was it a coincidence?

**Comment by perks** [comment]
That was a coincidence, I tried loading it a couple more times and you just get the default filters running against youtube
![Screen Shot 2021-02-16 at 9 37 35 PM](https://user-images.githubusercontent.com/1820298/108124591-4a160480-709f-11eb-8deb-ce76ce986d26.png)

**Comment by gorhill** [comment]
When I navigate to Youtube I get the expected network events reported in the logger:

![a](https://user-images.githubusercontent.com/585534/108125026-de6b7180-7075-11eb-9209-f6dd5ec8332e.png)

On your side I just see the scriptlet injection filters being reported, these are injected on a webNavigation event. The picker/zapper not launching indicate that there are no content scripts injected, and also weird is that there is no network activity reported.

**Comment by gorhill** [comment]
Well, on my side I am testing using Chromium 87.0.4280.66, my distribution hasn't upgraded to 88.0.4324.150 yet.

**Comment by gorhill** [comment]
In your GIF, I see uBO working properly once you navigated to `github.com` from `youtube.com`. Did you try to navigate to `youtube.com` from, say, `github.com` to see if this work?

**Comment by perks** [comment]
@gorhill Interesting enough this same behavior seems to be replicated on all google-related domains. So anytime I visit a google domain it seems network request introspection by the extension is disabled. 

I tried navigating to/from regular web pages with no observed changes

I thought this might be related to issues with "hosted" apps related to websites, but I do not have anything/have removed all apps from `chrome://apps` and restarted the browser and the behavior exists

**Comment by gorhill** [comment]
If you open the dev tools of the page and bring forth the "Network" pane, does the browser's own dev tools logger report network events as would be expected for `youtube.com`?

![b](https://user-images.githubusercontent.com/585534/108127152-ce08c600-7078-11eb-953c-a69a60bd1e43.png)

**Comment by perks** [comment]
![Screen Shot 2021-02-16 at 10 04 52 PM](https://user-images.githubusercontent.com/1820298/108127354-0ae9b280-70a3-11eb-86d7-4ea2ec6cbaaf.png)

Seems devtools work fine

**Comment by gorhill** [comment]
There is a difference from my side though, I see the main document being loaded from a service worker. I don't get this on my side.

If you close all Youtube tabs and go to `chrome://serviceworker-internals/` and unregister workers related to `youtube.com`, do you still have the issue?

**Comment by perks** [comment]
Really strange, everytime I try unregistering the service both through `chrome://serviceworker-internals` anytime I navigate within or reload the page the serviceworker gets re-registered and started

**Comment by gorhill** [comment]
> the serviceworker gets re-registered and started

That's normal. I actually get similar result as yours when I navigate to `youtube.com` while there is a worker registered, but in my case uBO can see and filter all the requests.

**Comment by gorhill** [comment]
> this same behavior seems to be replicated on all google-related domains

Are other blockers similarly affected? ([AdGuard](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg), [ABP](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb))

**Comment by gorhill** [comment]
Could there be policies in your browser preventing uBO from working on Google-related domains? See `chrome://policy/`.

**Comment by perks** [comment]
I do have chrome policies it seems, this must be it. I tried the other Adblock restrictions and the behavior is almost identifical (not all requests logged, unable to use "element picker"-esque functionality). Thank you for the help, unfortunately it seems that this is probably unresolvable if it is related to a specific chrome policy.

**Comment by llacb47** [comment]
`I do have chrome policies it seems, this must be it.`

??? Just because you have a chrome policy isn't the reason, have you identified a specific policy that causes the issue or are you just speculating?

**Comment by gorhill** [comment]
Do you know which policy is causing this behavior? If ever there is report of such behavior in the future, it will be useful to know which policy to check.

**Comment by perks** [comment]
@gorhill I am pretty sure it is utilizing the [ExtensionSettings](https://cloud.google.com/docs/chrome-enterprise/policies/?policy=ExtensionSettings) policy,  `blocked_permissions` has various blacklisted permissions including `debugger`, etc which is probably responsible.

**Comment by perks** [comment]
> `I do have chrome policies it seems, this must be it.`
> 
> ??? Just because you have a chrome policy isn't the reason, have you identified a specific policy that causes the issue or are you just speculating?

@llacb47 calm down, seeing as you've been 0 percent helpful in the conversation no need to ping me

closing as it seems the policy permission mapping fits, and behaviour is only produced when visting the domains listed in the `runtime_block_hosts` which is further confirmed for the description of that field here https://support.google.com/chrome/a/answer/9867568?p=Configure_ExtensionSettings_policy&visit_id=637491196329043895-531615411&rd=1#

**Comment by llacb47** [comment]
I didn't even ping you, but OK. Glad to see you identified the issue.

**Comment by gorhill** [comment]
> behaviour is only produced when visting the domains listed in the `runtime_block_hosts`

Thanks. I might try to experiment with this to find whether uBO can detect being prevented from doing it's job, and if so then maybe figure out a way to at least inform the user.
