### ISSUE TITLE
Impossible to add explicit exception for implicit strict blocking

### ISSUE THREAD

**Issue by antonok-edm** [uBlockOrigin/uBlock-issues#1501]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Filters of the form `||example.com^` _implicitly_ enable strict blocking for `https://example.com`. Filters of the form `||example.com^$document` will likewise _explicitly_ enable strict blocking for `https://example.com`. However, it is only possible to write an exception rule for the explicit case; exceptions are ignored in the implicit case.

### A specific URL where the issue occurs

I have been using `https://example.com` for testing, along with the following custom filters:
#### Explicit Configuration
```
||example.com^$document
@@||example.com^$document
```

#### Implicit Configuration
```
||example.com^
@@||example.com^$document
```

### Steps to Reproduce

1. Add the **Explicit Configuration** from above to uBlock Origin's custom filters
2. Visit https://example.com
3. Note that the page is loaded
4. Replace the custom filters with the **Implicit Configuration** above
5. Visit https://example.com again
6. Note that the page is blocked by uBlock Origin's strict blocking.

### Expected behavior:

The behavior for the implicit configuration should match the current behavior of the explicit configuration, negating strict blocking on https://example.com.

### Actual behavior:

The implicit configuration's behavior is different from the explicit configuration, causing strict blocking to occur on https://example.com despite the presence of an exception.

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Chromium 88.0.4324.152
* Operating System and version: Arch Linux

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#document-for-entire-page-exception

**Comment by antonok-edm** [comment]
@uBlock-user that section says that strict blocking can still be negated using the `document` option, no?

**Comment by uBlock-user** [comment]
Only when `||example.com^$document` is used.

**Comment by gorhill** [comment]
The problem with `@@...$document` is that there already exists such filters in EasyList, but these have the ABP semantic, which is to wholly disable content blocking of secondary resources when the pattern matches.

**Comment by gorhill** [comment]
Ok despite the different semantic, uBO does not reject the exception filter, and should still enforce the exception, though with its own semantic (i.e. not strict-block), but it's not happening, I have to investigate why.

**Comment by gorhill** [comment]
Ok, it's because uBO checks for exception filters _only_ when it hits a block filter, so not finding the explicit form `||example.com^$document` means uBO skips trying to find an exception filter.
