### ISSUE TITLE
Clarify the purpose of uBlock Origin to those less familiar with computing

### ISSUE THREAD

**Issue by CrazyPython** [uBlockOrigin/uBlock-issues#1504]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Describing uBlock as a "wide-spectrum blocker" is potentially very confusing to those less familiar with computing. Block what? From where? They do not know how a web browser works. They may not know it's possible to "block" anything.

It is better if we use a metaphor– "uBlock Origin is a digital invisibility cloak." This will increase adoption and make uBO more popular.

### A specific URL where the issue occurs

Not fixed: https://github.com/gorhill/uBlock#ublock-origin

Fixed: https://github.com/CrazyPython/uBlock/tree/patch-1#ublock-origin

### Steps to Reproduce

1. Find a random person with normal (minimal) level of technology. Do not use a random friend, as the friends of software developers are more likely to have experience with technology.
2. Ask them to read the README
3. Ask them to describe what uBlock Origin does, and why they may consider installing it.

### Expected behavior:

1. They understand what uBlock Origin does
2. If they are privacy-minded, they will install it

### Actual behavior:

1. Many people who care about privacy use commercial extensions that cost money and do less for privacy.

### Your environment

* uBlock Origin version: N/A
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by llacb47** [comment]
That is even more confusing IMHO

**Comment by gorhill** [comment]
> It is better if we use a metaphor– "uBlock Origin is a digital invisibility cloak."

I disagree, a metaphor might be useful for an abstract concept, but here it's quite simple: uBO is a content blocker, no need for a metaphor.

**Comment by CrazyPython** [comment]
Content blocker? Blocking what? 

To a typical user, the web is like any other part of their computer: Sealed and closed, unable to access. The simple idea that they could possibly have control over their computer is foreign to them. The idea of an *open web* is foreign.

A "content blocker" sounds like it blocks content. But often uBlock Origin is used to block invisible trackers, not content.

Compared to other adblockers, uBlock Origin is just a slightly faster adblocker without a better explanation.

**Comment by uBlock-user** [comment]
> A "content blocker" sounds like it blocks content. 

Yes, uBO blocks web-content based on filters listed in various filterlists, so appropriate as it has been for years.
