### ISSUE TITLE
Popup UI empty after browser start if home page is a browser internal page

### ISSUE THREAD

**Issue by vlaszlo** [uBlockOrigin/uBlock-issues#1505]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

See title.  Right after browser startup, uBO's popup UI comes up empty if the home page is a browser internal page. I tried several "about:" as well as "chrome:" pages. Simply hitting the reload button or navigating to a different address immediately fixes the problem. The issue doesn't happen if the homepage is a URI that accesses the network, like https://github.com .

Tested on a heavily used profile with many changed browser and uBO advanced settings as well as a new, untouched profile with  a fresh uBO default install.

I first noticed the problem with 1.33.3b1, so it might be somewhere in the big commit that introduced 3rd-party script/frame plus/minus counting.

### A specific URL where the issue occurs

Any browser internal page like about:home or chrome://browser/content/places/places.xhtml .

### Steps to Reproduce

1. Make sure that "Homepage and new windows" in Options>Home is set to a browser internal page.
2. Restart the browser.
3. Right after startup, open uBO's popup UI.

### Expected behavior:

The popup UI shows its normal structure.

### Actual behavior:

The popup UI comes up empty.

### Your environment

* uBlock Origin version: 1.33.3b5
* Browser Name and version: Mozilla Firefox, Nightly, Build ID 20210220093316
* Operating System and version: Windows 10 20H2

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/108609713-089f9500-73d0-11eb-8340-668161631914.png)
