### ISSUE TITLE
The Edge Chromium version is not blocking some of Youtube Music video ads, while the Chrome version can block all of them.

### ISSUE THREAD

**Issue by cbwee** [uBlockOrigin/uBlock-issues#1506]
- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The Edge Chromium version is not blocking some of Youtube Music video ads, while the Chrome version can block all of them.
Both with the same settings.

### A specific URL where the issue occurs

https://music.youtube.com/
(Choose any playlist on the page to and play it.)

### Steps to Reproduce

1. Install the Microsoft Edge Chromium version of uBlock Origin.
2. Play songs in Youtube Music PWA in Microsoft Edge.
3. Most ads in Youtube Music are blocked, but sometimes video ads still appear.
4. Backup all settings to a file, uninstall Edge version of uBlock Origin.
5. Install the Chrome version of uBlock Origin from Chrome Web Store, and restore settings from the previous file.
6. Play Music in Youtube Music again, all ads are blocked, no video ads.

### Expected behavior:

The Microsoft Edge version should block all Youtube Music video ads with all uBlock filters and EasyList enabled.

### Actual behavior:

Video ads are not blocked in Youtube Music when I used the Microsoft Edge version of uBlock Origin, but the Chrome version does not have that issue, when the Chrome version is used (with the same settings), all ads including video ads are blocked.

### Your environment

* uBlock Origin version: 1.33.2 (Edge Chromium), 1.33.2 (Chrrome Web Store)
* Browser Name and version: Microsoft Edge Stable 88.0.705.74
* Operating System and version: Windows 10 1909, Build 18363.1411

**Comment by gwarser** [comment]
PWA only? Did you tried Chrome with PWA?

**Comment by cbwee** [comment]
PWA is the same as a website, but when installed as a PWA, it opens in a new window, now I am using the Chrome Web Store version of uBlock Origin in Edge, and the Chrome version works well, only the Edge store version of uBlock Origin has that issue.

**Comment by cbwee** [comment]
I tried both versions of uBlock Origin in the same Browser, Microsoft Edge, and both in YouTube Music PWA.

**Comment by cbwee** [comment]
I have just saw a video ad in Youtube Music, even with the Chrome version.

So I will try to add more filters, I am colsing this issue, since it's not the extension's issue.
