### ISSUE TITLE
Ads not being blocked on duckduckgo with OperaGX

### ISSUE THREAD

**Issue by LegendaryOverlord** [uBlockOrigin/uBlock-issues#1508]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When using duckduckgo on OperaGX, ads are shown. Previously I've used Chromium and never seen any ads on duckduckgo. Furthermore, I went to Edge and downloaded ublock there, and it immediately started blocking ads. But on OperaGX the ads persist despite using the same default filters as Edge.

### A specific URL where the issue occurs

https://duckduckgo.com/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Go to duckduckgo
2. [Second Step] Search various topics
3. [and so on...]

### Expected behavior: No ads are shown

[What you expected to happen]

### Actual behavior: Ads are shown

[What actually happened]

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: OperaGX core: 73.0.3856.400
* Operating System and version: Windows 10

**Comment by NickJustWont** [comment]
Add the following rules to your **user filter**:

duckduckgo.com##.js-results-ads
duckdickgo.com##.results--ads
duckduckgo.com##.links_deep.result__body:has([class^="badge--ad"])

**Comment by gwarser** [comment]
Go to Opera settings and allow add-ons to run on search pages.

**Comment by Evernow** [comment]
Stop using Opera, [it is spyware](https://old.reddit.com/r/24hoursupport/wiki/productstoavoid#wiki_opera), there is no reason to use that garbage.

**Comment by LegendaryOverlord** [comment]
> Stop using Opera, [it is spyware](https://old.reddit.com/r/24hoursupport/wiki/productstoavoid#wiki_opera), there is no reason to use that garbage.

What do you use? Seems like everything is Chromium based, so there doesn't seem to be any better alternative.
