### ISSUE TITLE
UBO interferes with Violentmonkey: breaks JS iterables(?) when "Disable JavaScript" is ticked

### ISSUE THREAD

**Issue by szc126** [uBlockOrigin/uBlock-issues#1509]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
      - not applicable
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

See violentmonkey/violentmonkey#1213.

### A specific URL where the issue occurs

https://example.com/test?key1=one&key2=two

### Steps to Reproduce

1. Tick the "Disable JavaScript" box in UBO options.
1. Create a new Violentmonkey script as in the link above.
1. Navigate to https://example.com/test?key1=one&key2=two.
1. View the browser console.

### Expected behavior:

```
1 ?key1=one&key2=two URLSearchParams {  } key1=one&key2=two
Array [ "key1", "one" ]
Array [ "key2", "two" ]
```

### Actual behavior:

```
1 ?key1=one&key2=two URLSearchParams {  } key1=one&key2=two
TypeError: temp.entries() is not iterable
```

It should be emphasized that Violentmonkey script execution appears to be completely unhindered otherwise.

### Your environment

* uBlock Origin version: v1.33.2
* Browser Name and version: Firefox 86.0
* Operating System and version: Arch Linux

**Comment by tophf** [comment]
Turns out this is not related to uBlock. When JS is disabled, Violentmonkey runs the scripts in the isolated world of a WebExtension content script so this is probably a bug in Firefox. Further investigation should be performed in the original issue in VM repo.

**Comment by szc126** [comment]
Wack. I'll close this then.
