### ISSUE TITLE
uBlock is blocking ~40K elements on Tesco webpage which makes Firefox unusable (uses 400% CPU)

### ISSUE THREAD

**Issue by stransky** [uBlockOrigin/uBlock-issues#1511]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Firefox 86.0, uBlock installed from Mozilla AMO site, default uBlock setting (no custom filters, any preference was not changed). When browse to Tesco site, Firefox is unusable.

### A specific URL where the issue occurs
https://nakup.itesco.cz/groceries/cs-CZ/shop/ovoce-a-zelenina/ovoce/jablka-a-hrusky

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open Firefox 86 with uBlock installed from Firefox addons site.
2. Go to https://nakup.itesco.cz/groceries/cs-CZ/shop/ovoce-a-zelenina/ovoce/jablka-a-hrusky
4. browse the items
5. Firefox is very slow, uses 400% CPU.

* uBlock Origin version:
uBlock Origin v1.33.2
* Browser Name and version:
Firefox 86
* Operating System and version:
Fedora 33 Linux

Firefox profiler data:
https://share.firefox.dev/37X1MvG

**Comment by stransky** [comment]
I see it's https://github.com/uBlockOrigin/uAssets/issues/8621 sorry for the noise.

**Comment by stransky** [comment]
Hm, this may be something else. I updated the EasyPrivacy list and restart browser but nothing changed, the issues is still here.

**Comment by stransky** [comment]
Hm, I see on the log the .sentry.io page at uBO log so it's uBlockOrigin/uAssets#8621 after all. I wonder why it's not blocked.

**Comment by gorhill** [comment]
Filter issue, and this was fixed yesterday, just force an update of _"uBlock filters -- Unbreak"_.

**Comment by gorhill** [comment]
Oops, ok I see this is about `itesco`, <https://github.com/uBlockOrigin/uAssets/commit/9ff3efedeb0dd8da20bbf90ba1e3d15d218e9833#commitcomment-47683605>.
