### ISSUE TITLE
Opera, Webmin page download contains easylist links

### ISSUE THREAD

**Issue by ReinerBforartists** [uBlockOrigin/uBlock-issues#1512]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Opera with just Ublock Origin installed.

I have downloaded my Webmin page by save as, and opened it up in an html editor. And it contained lots of porn page links. 

So i started to search where these links comes from. And ended in the easylist file from Ublock Origin, wich is one to one now part of my downloaded html page.

Turning off Ublock origin will fix the problem. When i turn the addon on again, then the downloaded html file will contain the easylist list content again.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
I cannot provide my Webmin URL, sorry. Webmin is the entry page to my webserver :)

### Steps to Reproduce

You need of course a Webmin installation. And Opera as the browser.

1. Log in to Webmin
2. Right Click, and choose save as to save the html file.
3. Open the downloaded html file and check if it contains bad links.

### Expected behavior:

[What you expected to happen]
The easylist links should definitely not land in a downloaded html file.

### Actual behavior:

[What actually happened]
The easylist content gets added to the downloaded html file of Webmin.

### Your environment

* uBlock Origin version: uBlock Origin v1.33.2
* Browser Name and version: Opera Version:74.0.3911.160
* Operating System and version: Windows 10 Pro 2004
* Happens with Webmin 1.970

Still curious how it is even possible that the content of the easylist text file can become part of a downloaded html file at all. But this is definitely not healthy behaviour. The download happens via Opera, so i guess the problem could also reside there.

![easylistinhtml](https://user-images.githubusercontent.com/13919702/109486331-03eb7880-7a83-11eb-88b3-be4365ba8ce8.jpg)

**Comment by gorhill** [comment]
Did you try without uBO?

**Comment by gorhill** [comment]
Can you try with other content blockers such as AdGuard or ABP?

**Comment by ReinerBforartists** [comment]
Of course. I have reinstalled Opera from scratch. All was fine. Then i reinstalled Ublock and the problem was back. As told, when i turn off Ublock then the problem is gone. 

Will install ABP now, turn off Ublock, and try if the problem persists.

**Comment by ReinerBforartists** [comment]
Thanks for the idea. Okay, happens also with ABP. But also with both off, ABP and Ublock. And just with the Opera adblocker active. The culprit seems to be that the easylist file exists.

I made the observation though that it stops when i turn off the Opera adblocker. But this adblocker does not use the easylist from what i know. The list comes definitely from Ublock, that's where i have found it in the Opera cache. So there seems to be a conflict between the two solutions. A chicken egg problem. I guess i also need to report this issue to Opera then.

**Comment by gorhill** [comment]
uBO does not prepend all injected selectors with `:root` as shown in your screenshot, and also it would not consider a selector such as `script[...] + #foo` as a highly generic one, so I don't understand where this is coming from.

**Comment by gorhill** [comment]
> But also with both off, ABP and Ublock

Opera has its own built-in blocker, most likely it's from Opera, not uBO.
