### ISSUE TITLE
Web RTC leak prevention is invalid in Firefox and Chrome.

### ISSUE THREAD

**Issue by dylanleesky** [uBlockOrigin/uBlock-issues#1517]
Use Firefox ESR v68~76 (x86) and chrome v88 (x64)

I can get my WEB RTC address in the test. 

uBlock  Version 1.33.2 

Test URL: https://ip.voidsec.com/

**Comment by dylanleesky** [comment]
Tested many times, sometimes effective, sometimes ineffective.
The test website includes https://browserleaks.com/webrtc

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

**Comment by dylanleesky** [comment]
> https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

I tested it,sometimes effective, sometimes ineffective.

**Comment by uBlock-user** [comment]
> sometimes effective, sometimes ineffective.

It hides your LAN IP address, so working as expected.

**Comment by dylanleesky** [comment]
> 
> 
> > sometimes effective, sometimes ineffective.
> 
> It hides your LAN IP address, so working as expected.

Do you mean that blocking WEB RTC can only hide the LAN IP, not the WAN IP?
I use other blocking tools,Can hide all my IP.
![1](https://user-images.githubusercontent.com/14555503/109952143-78d7e000-7d19-11eb-860c-0cb6df301389.png)
![2](https://user-images.githubusercontent.com/14555503/109952146-79707680-7d19-11eb-9446-57fd46ad9584.png)

**Comment by uBlock-user** [comment]
> Do you mean that blocking WEB RTC can only hide the LAN IP, not the WAN IP?

Yes, exactly that.

**Comment by gorhill** [comment]
> I use other blocking tools,Can hide all my IP.

The other wholly disables WebRTC.

In uBO, the goal is not to disable WebRTC, it's to prevent local IP address leakage, it's not meant to prevent your public-facing IP address from being seen. Any website can see your public-facing IP address.
