### ISSUE TITLE
Requires a scriptlet to add cookies

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1518]
Sometimes cookies need to be added to prevent unwanted advertising behavior.

Example. On rustorka.com after registration and authorization, the first page refresh leads to a redirect if there is no "opt_js" cookie. After the redirect, this cookie is installed by the site and lives for 12 hours, after which the redirect is repeated.

The need to force the installation of cookies is quite common. In [AdGuard base filter](https://filters.adtidy.org/extension/chromium/filters/2.txt), the rules setting cookies `#%#document.cookie` are used 53 times, in [AdGuard Russian filter](https://filters.adtidy.org/extension/chromium/filters/1.txt) - 10 times.

**Comment by gorhill** [comment]
I consider the open-ended ability to create new information which wasn't there before to be a security risk, not unlike the `rewrite` filter option as described at <https://armin.dev/blog/2019/04/adblock-plus-code-injection/>.

**Comment by dimisa-RUAdList** [comment]
AdGuard has been using `#%#document.cookie` for quite some time and so far no security issues have arisen.

**Comment by P0Rtvine** [comment]
**Security risk**
But, only filter authors can edit rules. Yes?

**Comment by mtxadmin** [comment]
Some malware sites prompt users to install their "lists", which, in fact, add exclusions for them. So, security concerns still exist. But I am agree with Dimisa, this functional will be useful sometimes.

**Comment by peace2000** [comment]
Another example, EU GDPR stuff related:

This site: https://www.tennisassa.fi/ sets a cookie wall that prevents an access to the site unless cookies are accepted. This could be bypassed by using a rule that adds a specific cookie there.

**Comment by mapx-** [comment]
> Circumventing a paywall is considered out of scope. GDPR messages will not be addressed in uAssets.

**Comment by peace2000** [comment]
> 
> 
> > Circumventing a paywall is considered out of scope. GDPR messages will not be addressed in uAssets.

Hi, yeah I know that uAssets won't handle GDPR stuff, I used that site just as an example for this feature request what could be done if this feature is added.

**Comment by gorhill** [comment]
I prefer to decline, for the stated reason.

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17022
There was similar case(s) set-cookie could be very useful to block popup/under I don't remember now.
