### ISSUE TITLE
Picker can't select and highlight elements in a page

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1521]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

IDK what is causing this, but as the title says - only very upper parts of the page is directly selectable while the rest parts don't grey out and not selectable (directly typing in the window works tho):

<details>
<summary>Screenshot</summary>

![takulog](https://user-images.githubusercontent.com/58900598/110132738-d69a2400-7e0e-11eb-82c6-abed3f3fca28.png)

</details>

### A specific URL where the issue occurs

`https://takulog.info/archiss-quattro-tkl-track-point/`

### Steps to Reproduce

1. Visit the page
2. Open the picker and try to select lower parts of the page

### Expected behavior:

The picker can select and highlight elements.

### Actual behavior:

Described

### Your environment

* uBlock Origin version: 1.33.2 / 1.33.3b11
* Browser Name and version: Chrome 89.0.4389.72 / Firefox 86.0
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
It's caused by the CSS property `will-change` on the `html` element -- [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change).

I will have to read about this to understand why this property is causing this.

**Comment by BangDroid** [comment]
I'm not sure if this is the same issue, but element picker will not show at all for me on YouTube home or subscriptions pages.
(There are new ads disguised as thumbnails I was trying to nix.)

uBO: 1.35.2
Chrome 91.0.4472.77 (Official Build) (64-bit)
Win10

**Comment by gorhill** [comment]
I can't reproduce with the provided case, so at this point a rare quirk not worth to spend time on.

**Comment by krystian3w** [comment]
New sample:

`https://ebooki.nowaera.pl/`

<img width="1861" height="407" alt="Image" src="https://github.com/user-attachments/assets/ff5d2c5b-288e-41a3-9889-efc0744c9118" />

IMO no possible without something similar like:

```adb
ebooki.nowaera.pl##html:has(> body + iframe:not([src])) { will-change: unset !important }
```

**Comment by u-RraaLL** [comment]
Possibly related: https://www.reddit.com/r/uBlockOrigin/comments/1tm7p3g/ublock_origin_picker_no_works_in_copilot/ (Edge browser)

**Comment by stephenhawk8054** [comment]
Looks like `copilot.microsoft.com` is a privilege page of MS Edge?

I try adding `copilot.microsoft.com##body` in My filters but it doesn't work either.

**Comment by krystian3w** [comment]
I would test hiding the lower tag to reject the error that the filter hits too high in the HTML tree or tried to add a negative outline by `body:style(outline: 9px solid blue !important; outline-offset: -15px !important)`.
