### ISSUE TITLE
uBlock Origin does not enforce the "Disable Javascript" option on SVG

### ISSUE THREAD

**Issue by hhirtz** [uBlockOrigin/uBlock-issues#1522]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
    - Link to the relevant part: https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting

### Description

uBlock Origin does not enforce the "Disable Javascript" option on Scalable Vector Graphics (SVG).

### A specific URL where the issue occurs

https://www.xul.fr/svgtetris.svg

### Steps to Reproduce

1. Go to uBlock's options, then "Settings" and make sure "Disable JavaScript" is checked,
2. Open a SVG with JavaScript in it.

### Expected behavior:

No JavaScript is executed.

### Actual behavior:

JavaScript is executed.

### Your environment

* uBlock Origin version: 1.33.2 from the mozilla addons store
* Browser Name and version: Firefox 86.0 (ArchLinux' build)
* Operating System and version: `Linux vroom 5.11.2-arch1-1 #1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000 x86_64 GNU/Linux`

**Comment by gorhill** [comment]
This was fixed earlier today: <https://github.com/gorhill/uBlock/commit/a01c03e11ae4451aed817f0fd0708b71ec8b3ccd>.
