### ISSUE TITLE
Incorrect shortcuts for CodeMirror in Edge Chromium on multi-touch supported Windows device

### ISSUE THREAD

**Issue by Fan-iX** [uBlockOrigin/uBlock-issues#1523]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

CodeMirror shortcuts work incorrectly on Edge Chromium on multi-touch Windows device.

for example, `ctrl-a` does not select all contents, instead, it moves the cursor to the beginning of the line.

[this issue](https://github.com/codemirror/CodeMirror/issues/6532) has been reported in the github page for CodeMirror

### A specific URL where the issue occurs

`extension://odfafepnkmbhccpbejgmiehpchacaeak/dashboard.html#1p-filters.html`

i.e. uBO My filters pane

### Your environment

* uBlock Origin version: 1.33.2 (latest)
* Browser Name and version: Edge Chromium 89.0.774.45
* Operating System and version: Windows 10 Professional 20H2, Touch support for 10 touchpoints

**Comment by uBlock-user** [comment]
CM was updated two weeks ago -- https://github.com/gorhill/uBlock/commit/0dfafc3bd3b9fe48fef779d68c9a9d05cb0c8362

Try the dev build.
