### ISSUE TITLE
Static filter count went down to 0(network + cosmetic) after the update to latest dev-build

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#1527]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Static filter count is 0 after updating to the latest dev-build

### A specific URL where the issue occurs

moz-extension://74e99578-6a58-4388-8858-0330686faee6/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Update or install 1.34.1b0
2. Notice uBO doesn't block anything via static filtering anymore

![Capture](https://user-images.githubusercontent.com/21290713/111033332-c5689d00-8436-11eb-82a9-3112fde7c427.PNG)
![Capture2](https://user-images.githubusercontent.com/21290713/111033335-c8fc2400-8436-11eb-980f-f571947d0620.PNG)

### Your environment

* uBlock Origin version: 1.34.1b0
* Browser Name and version: Firefox 88
* Operating System and version: Win X

**Comment by uBlock-user** [comment]
Addendum: Picker is not working either, uBO is broken.

**Comment by gorhill** [comment]
Sorry I messed up, forgot to git-add a new JS file. Should work fine with 1.34.1b1.

**Comment by gorhill** [comment]
The Chrome Web Store decided to put the emergency fix into "pending review" mode, while it published immediately all the previous versions. This means now the CWS is serving a broken uBO and there is nothing I can do to prevent this.
