### ISSUE TITLE
Advanced setting "cnameUncloak" cannot be modified

### ISSUE THREAD

**Issue by logithack** [uBlockOrigin/uBlock-issues#1529]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I've recently reported [Bug 1694404](https://bugzilla.mozilla.org/show_bug.cgi?id=1694404) on Bugzilla, in which I described how uBO (v1.33.2) slowed down loading websites in Firefox. The developer of uBO, Raymond Hill, provided me with a solution in [Comment 5](https://bugzilla.mozilla.org/show_bug.cgi?id=1694404#c5) on my issue. Setting `cnameUncloak` to `false` in uBO's advanced settings solved the problem.
Today, I was experiencing exactly the same issue as described in my Bugzilla report. I checked uBO's details to see that it has automatically been updated to v1.34.0. I thought perhaps the `cnameUnloak` parameter I had previously set to `false` had been modified in course of the update. I checked it to find that `cnameUncloak` was now set to `undefined`. The problem is that I cannot change its value from `undefined` to `false`. Whenever I try to modify it and apply the changes, it gets automatically reset to `undefined`.

### A specific URL where the issue occurs

Any will do. The slowdown as described in my Bugzilla report can be reproduced with https://www.debian.org, for example. However, the issue I'm addressing here rather refers to uBO's behaviour when trying to modify its advanced settings.

### Steps to Reproduce

1. Preparation: Launch Firefox with a new, empty profile and install uBO as the only extension from the [official Add-Ons page](https://addons.mozilla.org/de/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search).
2. Click on uBO's icon in the top right corner &rarr; click on the settings/dashboard icon &rarr; navigate to the _Settings_ tab &rarr; check the _I am an advanced user_ option &rarr; click on the settings icon to the right of the option.
3. Find the line `cnameUncloak undefined` (line 19 in my case) &rarr; double-click the value `undefined` &rarr; type `false` and click on the _Apply changes_ button at the top.

### Expected behavior:

I would expect the value `false` set via the method described above to be applied for the `cnameUncloak` option.

### Actual behavior:

Instead, after clicking the _Apply changes_ button, uBO displays the `cnameUncloak` option with the value `undefined` again.

### Your environment

* uBlock Origin version: v1.34.0
* Browser Name and version: Firefox 86.0.1 (also applies to 83.0)
* Operating System and version: Windows 10 Enterprise 1909

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

@gorhill the setting is still present in Advanced settings ?

**Comment by gwarser** [comment]
> @gorhill the setting is still present in Advanced settings ?

Transition period, this is noted in source code if I recall.

**Comment by uBlock-user** [comment]
> this is noted in source code if I recall.

Where ?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/1c3b45f75d0f84d68abb51b15bbdc043464ee3e0#diff-abfcc54cc8cd1a953760493c8afbb2669054ffd7520322e105b2e9bbca625f49R178-R188

**Comment by gwarser** [comment]
Checkbox in GUI sticks after restart. Does it work for you @logithack ?

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

**Comment by logithack** [comment]
> Checkbox in GUI sticks after restart. Does it work for you @logithack ?
> 
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

In case you mean "If you check the _I am an advanced user_ option and restart Firefox, will this option still be checked after restarting?", then yes, this does work. When I check that option and restart Firefox, the option is still checked after restart.

**Comment by gwarser** [comment]
No, this setting: https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

It was moved from advanced configuration to the "Settings" tab in Dashboard.

**Comment by logithack** [comment]
Oh wow, I didn't see that. That, of course, solved the problem! All pages are loading fast again. I'm very happy that this feature is now easily accessible by just un-/checking it. Thank you very much and keep up the great work!

**Comment by gwarser** [comment]
Setting being reset after update still requires investigation?

**Comment by gorhill** [comment]
It was supposed to transition seamlessly, but looking at the code, it seems I forgot to save the user setting after transferring the state from advanced settings.

**Comment by u-RraaLL** [comment]
It's been two years. Perhaps it's time to remove `cnameUncloak` from advanced settings?

**Comment by gorhill** [comment]
Right, I have this in the code:

     TODO: remove when current version of uBO is well past 1.34.0.
