### ISSUE TITLE
browserleaks.com is able to know that Adblock is installed and is also able to know few of the filters.

### ISSUE THREAD

**Issue by TontyTon** [uBlockOrigin/uBlock-issues#153]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The given website is able to know that 'Adblock for Google Chrome' is installed. Even it is able to know few of the filters applied.

### A specific URL where the issue occurs

[https://browserleaks.com/proxy](url)

### Steps to Reproduce

1. Go to https://browserleaks.com/proxy
2. See the results

### Expected behavior:

 A text 'Adblock not detected' in 'Adblock Detection' section.
![expec](https://user-images.githubusercontent.com/35778430/43541802-e7b6fe5e-95e8-11e8-8c34-103cd2382639.PNG)

### Actual behavior:

Personal settings-
![capture](https://user-images.githubusercontent.com/35778430/43541520-3c5d590e-95e8-11e8-8a11-d9a3f2818845.PNG)

Default settings-
![default](https://user-images.githubusercontent.com/35778430/43541673-9a9016ba-95e8-11e8-9bdb-03d29d28d178.PNG)

### Your environment

* uBlock Origin version:  1.16.14
* Browser Name and version: Google Chrome  67.0.3396.99 (Official Build) (64-bit)
* Operating System and version: Windows 10 
* Version: 1803
* OS Build: 17134.167

**Comment by gorhill** [comment]
You will have to wholly block javascript to prevent sites from executing javascript which can be used to detect the blocking of resources -- there is no other way to avoid this.

**Comment by TontyTon** [comment]
@gorhill can I discuss with you something, related to privacy.

**Comment by TontyTon** [comment]
@gorhill can I discuss with you something, about privacy. Just few short questions

**Comment by uBlock-user** [comment]
It's detecting Easylist/other filterlists's filters, not a specific extension. so there is no extension detection going out here.

**Comment by uBlock-user** [comment]
> can I discuss with you something, about privacy. Just few short questions

User support is on reddit.

**Comment by TontyTon** [comment]
@uBlock-user  But it can be used by anti adblock engines

**Comment by uBlock-user** [comment]
It already is. Report anti adblock issues on uAssets,
