### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by scrouthtv** [uBlockOrigin/uBlock-issues#1530]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since one or two weeks, uBlock is crashing randomly for me. I get this popup:
![image](https://user-images.githubusercontent.com/23227405/111504263-c60b7700-8747-11eb-90a2-d9106e234f77.png)

I am using 91.0.4449.0 (64-bit) on Windows 10.

### A specific URL where the issue occurs

I am not able to give a certain URL where it crashes. 

The last URL where it happened is https://www.google.com/search?q=to263&oq=to263&aqs=chrome..69i57j0i10j0l6j0i10j0.945j0j7&sourceid=chrome&ie=UTF-8
However, if I open this URL now, it works fine.

### Steps to Reproduce

1. Install Windows 10
2. Install Chrome 91.0.4449.0
3. Install uBlock Origin
4. Use this setup for half an hour
5. ![image](https://user-images.githubusercontent.com/23227405/111504245-c1df5980-8747-11eb-9054-b164913518aa.png)

### Expected behavior:

uBlock Origin works for longer than half an hour

### Actual behavior:

uBlock Oirigin crashes after half an hour or so

### Your environment

* uBlock Origin version: uBlock Origin v1.33.2
* Browser Name and version: Google Chrome Version 91.0.4449.0 (Official Build) canary (64-bit)
* Operating System and version: Windows 10 OS Build 19041.867

I know that this is very, very vague. I can provide a chrome_debug.log if that helps.

**Comment by uBlock-user** [comment]
Browser crashes must be reported to browser vendors. You're on Canary channel so this is to be expected.

**Comment by uBlock-user** [comment]
uBO is HTML/JS/CSS, so it cannot crash itself. The extension process in Chrome is crashing, so like I said, report to Chrome devs. This is not new.

**Comment by scrouthtv** [comment]
I'm pretty sure they're just going to tell me that it's a problem with the extension (since all other extensions don't crash) and close it too. 
> This is not new.

uBlock has been crashing for some time now?

**Comment by gorhill** [comment]
> This is not a browser crash:

This is a process crash, the process in which uBO executes has crashed. uBO is html/css/js, the browser is not supposed to crash when parsing/executing any web page or extension.
