### ISSUE TITLE
gitcdn.xyz insecure; blocked by BitDefender on Windows 10

### ISSUE THREAD

**Issue by anthonybaldwin** [uBlockOrigin/uBlock-issues#1533]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin uses gitcdn.xyz to pull in files. The site is currently causing BitDefender on Windows 10 to yell about a cert mismatch--so I am seeing constant warnings.

They also have a report on their end, but I'd like to see uBlock Origin find a different solution: https://github.com/schme16/gitcdn.xyz/issues/78

![image](https://user-images.githubusercontent.com/6219998/111889254-0dd90b00-89a1-11eb-806e-3780097f88bc.png)

![image](https://user-images.githubusercontent.com/6219998/111889140-0d8c4000-89a0-11eb-9cf5-340d70bd9aad.png)

### A specific URL where the issue occurs

https://gitcdn.xyz/*

### Steps to Reproduce

1. Install BitDefender antivirus for Windows 10
2. Launch Chrome with uBlock installed
3. See notifications from BitDefender in regard to cert mismatch
4. Visit gitcdn.xyz to confirm
(Bypassed in Chrome, so here's Firefox: 
![image](https://user-images.githubusercontent.com/6219998/111889840-758f5600-89a1-11eb-8b6b-7d4dcd0a4ed5.png))

### Expected behavior:

gitcdn.xyz is secure--or a different solution is used

### Actual behavior:

gitcdn.xyz is currently insecure--therefore uBlock Origin is insecure

### Your environment

* uBlock Origin version: v1.34.0
* Browser Name and version:  Chrome 89.0.4389.90
* Operating System and version: Windows 10 20H2

**Comment by schme16** [comment]
Hi, GitCDN creator here, looks like the main GitCDN domain was accidentally caught by CloudFlares new "no video and audio" policies. Until it's resolved the backup domain should be used: GitCDN.link

**Comment by uBlock-user** [comment]
gitcdn issue, nothing for uBO to do.

**Comment by uBlock-user** [comment]
fallback urls are present fyi

**Comment by uBlock-user** [comment]
> Until it's resolved the backup domain should be used: GitCDN.link

@gorhill

**Comment by gorhill** [comment]
Without BitDefender the connection would still fail in the browser and uBO would fallback using another URL.
