### ISSUE TITLE
Temporarily disable uBlock on all sites

### ISSUE THREAD

**Issue by Sopor** [uBlockOrigin/uBlock-issues#1537]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It is possible to disable uBlock in two different ways (single click or ctrl+click), but to temporarily disable it on all sites are something i can't find. Sometimes you need to disable uBlock on a single site, but that site will redirect you to another site for a verification or similar. If this happens i need to try to catch all the sites and disable every sites and that is not very easy. I can of course disable uBlock in my web browsers extensions but that isn't an easy way to do it.

It would be much better if there was an easy way to do it in uBlock. Maybe another key combination?

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Firefox 87
* Operating System and version: Windows 10 (1909)

**Comment by uBlock-user** [comment]
gorhill/uBlock#766
gorhill/uBlock#167
https://github.com/uBlockOrigin/uBlock-issues/issues/586#issuecomment-494021002
https://github.com/uBlockOrigin/uBlock-issues/issues/677
