### ISSUE TITLE
in Chrome when Windscribe is enabled the user agent header is changed to Firefox

### ISSUE THREAD

**Issue by Trip69** [uBlockOrigin/uBlock-issues#1539]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [? - Windscribe] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

In the latest chrome with WindScribe installed in Incognito mode with _only_ Windscibe allowed but _NOT_ enabled the user-agent header is changed to Firefox "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" - 

If in inconito mode with nothing allowed the user agent is reported as expect - blah blah Chrome

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=bug_report.md&title=

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. install windscribe
2. open dev tools, network, check request headers user-agent
3. find it is being reported as Firebox.

### Expected behavior:

user agent should be unchanged

### Actual behavior:

user agent isi being changed to firefox even with the extension not on - enabled but not active, black W icon not green

### Your environment

* uBlock Origin version: Err Windscribe - Free Proxy and Ad Blocker v3.2.4
* Browser Name and version: Chrome latest Version 89.0.4389.90 (Official Build) (64-bit)
* Operating System and version: Windows 10 x64 all updates applied
![2021-03-28 13_25_32-Home · gorhill_uBlock Wiki](https://user-images.githubusercontent.com/28258042/112749167-3ed0c580-8fc9-11eb-8c76-154c81b4ce29.jpg)

**Comment by uBlock-user** [comment]
uBO doesn't change any headers, nothing to do with uBO.

**Comment by uBlock-user** [comment]
> uBlock Origin version: Err Windscribe - Free Proxy and Ad Blocker v3.2.4

Fake version, current stable version is v1.34.0
