### ISSUE TITLE
json-prune doesn't remove all properties by full wildcard if the third parameter is satisfied

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1545]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

AdGuard often uses this form of filter: `imgsen.com##+js(json-prune, *, showTrkURL)` but apparently doesn't work on uBO.

### A specific URL where the issue occurs

`https://imgsen.com/mdaywmhb6u6d/photo-1551582045-6ec9c11d8697.jpg.html`
(https://github.com/AdguardTeam/AdguardFilters/issues/79356)

### Steps to Reproduce

1. Add `imgsen.com##+js(json-prune, *, showTrkURL)` and `imgsen.com##+js(json-prune)`
2. Add `@@||threecd.name^` (tho currently unblocked)
3. Visit the page with console opened and see results

### Expected behavior:

In this case all properties should be removed.

### Actual behavior:

No pruning occurs.

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Firefox 87.0
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
>Add `imgsen.com##+js(json-prune, *, showTrkURL)` and `imgsen.com##+js(json-prune)`

Order of filters is undefined. Logging can appear before pruning.

**Comment by gwarser** [comment]
No prunning:

![image](https://user-images.githubusercontent.com/886325/113715230-8baf4d00-96e9-11eb-81d1-3068a69d8ba5.png)

**Comment by Yuki2718** [comment]
> 
> Order of filters is undefined. Logging can happen before pruning.

Didn't know, thx.

**Comment by gwarser** [comment]
Looks like "wildcards" can only appear in "path" ("folder"?) - property must be named explicitly.

**Comment by Yuki2718** [comment]
> Looks like "wildcards" can only appear in "path" ("folder"?) - property must be named explicitly.

Yeah, that's what I suspected.

**Comment by gorhill** [comment]
> `imgsen.com##+js(json-prune, *, showTrkURL)`

If I understand correctly, the filter above means _"remove everything if the needle matches"_? If so, it's not a case I thought about.

**Comment by Yuki2718** [comment]
@slavaleleka Could you please point out anything needing attention to ensure compatibility, if any.
