### ISSUE TITLE
uBlock does not load adminSettings at first run

### ISSUE THREAD

**Issue by Fehler12** [uBlockOrigin/uBlock-issues#1547]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

when installing uBlock Origin by GPO into Chrome on Windows 10, the custom config of uBlock is not recognized at the first start. When the browser gets closed and started again the settings are there.

### A specific URL where the issue occurs

www.google.com

### Steps to Reproduce

Prerequesites:
I have two policies configured. One for automatically installing uBlock origin (it may be necessary to join the Windows 10 PC into a domain for using this) and the other one for giving uBlock a config:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist
Name of key: 1
Type: REG_SZ
Value: cjpalhdlnbpafiamejdnhcphjbkeiagm

HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\3rdparty\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy
Name of key: adminSettings
Type: REG_SZ
Value: {"timeStamp":1617739675266,"version":"1.34.0","userSettings":{"importedLaists":[],"popupPanelSections":15},"selectedFilterLists":["user-filters","assets.json","public_suffix_list.dat","ublock-badlists","ublock-filters","ublock-badware","ublock-privacy","ublock-abuse","ublock-unbreak","easylist","easyprivacy","urlhaus-1","plowe-0","DEU-0"],"hiddenSettings":{},"whitelist":["about-scheme","chrome-extension-scheme","chrome-scheme","edge-scheme","moz-extension-scheme","opera-scheme","vivaldi-scheme","wyciwyg-scheme"],"dynamicFilteringString":"behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop","urlFilteringString":"","hostnameSwitchesString":"no-large-media: behind-the-scene false","userFilters":"wikipedia.org##.nag-trigger\nwikipedia.org###centralNotice\nwikipedia.de###WMDE-Banner-Container\nwww.youtube.com###dialog\nwww.youtube.com##.opened\nwww.youtube.com##ytd-popup-container\n"}
```

In order to simulate a new install do the following:

1.) Goto %LocalAppData%\Google and delete the folder Chrome
2.) Start Chrome. The folder will be recreated and Chrome will reinstall the profile with the ublock origin but without the given config (e.g. my filter is empty)
3.) Close Chrome
3.1) Reboot the machine (optional)
4.) Start Chrome. Now the settings are there

Another way to reproduce is the following:
1.) Goto %LocalAppData%\Google and delete the folder Chrome
2.) Start Chrome. The folder will be recreated and Chrome will reinstall the profile with the ublock origin but without the given config (e.g. my filter is empty)
3.) Open the uBlock Config tab and click on "restore default settings"
Now the correct config gets loaded and applied.

### Expected behavior:

I would expect the custom config (from the second registry key) to be active at the very first start of Google Chrome, when the Plugin gets automatically installed without any further interaction.

### Actual behavior:

The config seems to be recongnized at the second start or when the default config gets manually loaded (alternative way). Maybe the Plugin checks if there is an adminConfig-Entry every time Chrome starts but not when it gets installed.

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Google Chrome 89.0.4389.114
* Operating System and version: Windows 10 Version 20H2

**Comment by gorhill** [comment]
uBO reads admin config using the [`browser.storage.managed` API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed), and consequently it shouldn't make a difference whether it's read at install time or not. I don't have Windows, I won't be able to reproduce as detailed. Also, the content of your `adminSettings` string does not look correct, i.e. there is no such setting as `importedLaists`, and `public_suffix_list.dat` should never be listed as a selected filter lists. Empty or unmodified properties should not appear in there, i.e. `hiddenSettings`, `whitelist`, etc.

**Comment by Fehler12** [comment]
Hi, at first thank you for your reply. I've resettet the uBlock settings and added the addtitional filters again. 
The importetLaists seemd to be a typo (by copy and paste) however the public_suffix_list.dat is still there so I assume that either this is a correct info or there is an bug with the default config on windows.

Is there anything I can do to further troubleshoot the problem? My assumption is that uBlock does not check the parameter adminSettings on first setup.

**Comment by gorhill** [comment]
I will try to find the time to investigate all what I can reproduce (though on linux) tomorrow, I will report my findings. Whoever else is also welcome to do so and share gheir findings.

**Comment by Ronbinn** [comment]
I can reproduce this on linux (Debian Bullseye). If I put this on 
`/etc/opt/chrome/policies/managed/policies.json`

>      "3rdparty":
>      {
>        "extensions":
>        {
>          "cjpalhdlnbpafiamejdnhcphjbkeiagm":
>          {
>            "adminSettings": "{\"timeStamp\":1618561470188,\"version\":\"1.34.0\",\"userSettings\":{\"externalLists\":\"https://www.i-dont-care-about-cookies.eu/abp/\",\"importedLists\":[\"https://www.i-dont-care-about-cookies.eu/abp/\"]},\"selectedFilterLists\":[\"user-filters\",\"ublock-filters\",\"ublock-badware\",\"ublock-privacy\",\"ublock-abuse\",\"ublock-unbreak\",\"easylist\",\"easyprivacy\",\"urlhaus-1\",\"plowe-0\",\"spa-1\",\"spa-0\",\"https://www.i-dont-care-about-cookies.eu/abp/\"],\"hiddenSettings\":{},\"whitelist\":[\"about-scheme\",\"chrome-extension-scheme\",\"chrome-scheme\",\"edge-scheme\",\"moz-extension-scheme\",\"opera-scheme\",\"vivaldi-scheme\",\"wyciwyg-scheme\"],\"dynamicFilteringString\":\"behind-the-scene * * noop\\nbehind-the-scene * inline-script noop\\nbehind-the-scene * 1p-script noop\\nbehind-the-scene * 3p-script noop\\nbehind-the-scene * 3p-frame noop\\nbehind-the-scene * image noop\\nbehind-the-scene * 3p noop\",\"urlFilteringString\":\"\",\"hostnameSwitchesString\":\"no-large-media: behind-the-scene false\",\"userFilters\":\"\"}"
>          }
>        }
>      }
First run doesn't load configuration, but second run does. If I add this option to the json file
>      "ForceEphemeralProfiles": true,
Configuration is never loaded

**Comment by anulman** [comment]
@gorhill — bad news. I have user reports that, if Chromium reloads after crashing, `lastVersion !== 0` so the extension doesn't reload itself.

It's possible—looking likely—that the crash happened on deploy. I notice [`uBlock` is setting `lastVersion` at script start](https://github.com/gorhill/uBlock/blob/32bd47f05368557044dd3441dcaa414b7b009b39/src/js/start.js#L106-L109); what if we defer setting it until after the `Promise.all`?
