### ISSUE TITLE
[Enhancement]/[Bug] Support `foo:upward(bar)element`

### ISSUE THREAD

**Issue by awebeer256** [uBlockOrigin/uBlock-issues#1548]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I ran across some HTML that looked like this:

```
<center no-useful-attributes>
    <div class="addisclaimer">ad content</div>
    <div blahblah>more ad content</div>
</center>
```
uBO's default configuration took care of the actual ads, but the `center` element had lots of padding, resulting in a weird blank space in the middle of the page's regular content, so I wanted to create a cosmetic filter that would block it, too.

### A specific URL where the issue occurs

Any article on FOSSMint. Here's one: https://www.fossmint.com/best-linux-games/.

### Steps to Reproduce

 I decided on the following strategy:

1. Select an element with the class `addisclaimer`.
2. Find its parent.
3. Verify that that element is a `center`; if so, remove it.

So I created the filter `fossmint.com##.addisclaimer:upward(1)center`. (Actually, I tried it as an HTML filter first: `fossmint.com##^.addisclaimer:upward(1)center`. But both are relevant here.)

### Expected behavior:

The filter would block the `center` element described above.

### Actual behavior:

As a regular cosmetic filter, the Element Picker treats it as a valid filter, but with 0 matches. The syntax highlighting in uBO's dashboard > My Filters also treats it as a valid filter. The filter doesn't actually block anything.

As an HTML filter, the dashboard's syntax highlighting still treats it as a valid filter, but adding it causes any page where it would take effect to apparently load with no progress for multiple minutes before giving up and displaying a blank page.

I eventually figured out that I could use `:upward(1):is(center)` or `upward(1):not(:not(center))` as a workaround, but the former isn't supported by all browsers yet and I believe both are inefficient. They certainly both look inelegant!

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Firefox 87
* Operating System and version: Linux Mint 20 (Ulyana)

**Comment by gorhill** [comment]
It's not a uBO issue, it's a support issue, you are misunderstanding how to create cosmetic filter, use <https://www.reddit.com/r/uBlockOrigin/> for support issue. I will not answer you here as this would send the message that invalid issues can be filed regardless since they will be answered.

**Comment by awebeer256** [comment]
You're (hopefully accidentally) equivocating on the word "support." The subreddit is for "customer support," i.e. asking for help with using uBO. I'm asking you to extend the functionality of the software, so that it allows for, or "supports," more things.

I know quite well how to create cosmetic filters; I've done it hundreds of times, including dozens with multiple chained procedural filters. uBO understands `foo:upward(1).class` and `foo:upward(1)[attribute]`, but not `foo:upward(1)element`, and I think it *should* understand it. Even if you decide that it shouldn't, the prevention of page loads is clearly a bug that you're now missing because, I can only assume, you didn't spend more than a few seconds looking at my post so you didn't even notice it.

And by the way, further testing has shown that `foo:upward(1)#id` works as an HTML filter but not as a regular cosmetic filter, which is also clearly a bug (either have it work both ways or neither; surely not just one). You're welcome.

**Comment by uBlock-user** [comment]
> foo:upward(1).class

That syntax itself is invalid, read https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectupwardarg

**Comment by strict-block** [comment]
Why can't move element "name" before  `:upward()`?

like `##CENTER > DIV[class*="ad"]:upward(1)`

?

Too fastly block these `foo:upward(1).class` and `foo:upward(1)[attribute]`  can break path using upward:

`##html > body p.ads:upward(2) > div`

**Comment by gorhill** [comment]
> but not `foo:upward(1)element`, and I think it should understand it

That is invalid CSS syntax even without uBO's `upward()`, i.e. `foo:nth-of-type(1)element` is not valid CSS. What you want is `element > foo:upward(1)` or `foo:upward(1):is(element)`. Please ask on <https://www.reddit.com/r/uBlockOrigin/> when you want help in crafting filter.

**Comment by strict-block** [comment]
But what mark as invalid these:

```
github.com##.js-comment-body:upward(1)[class]
```

**Comment by gorhill** [comment]
> But what mark as invalid these

Sorry I don't understand what you are saying. The filter you mention is valid, the same way a plain CSS selector like `.js-comment-body:nth-of-type(1)[class]` is valid.

**Comment by awebeer256** [comment]
> That is invalid CSS syntax even without uBO's `upward()`, i.e. `foo:nth-of-type(1)element` is not valid CSS selector.

The existence of `upward()` makes uBO filters meaningfully different than plain CSS. `foo:nth-of-type(1)element` doesn't *need* to be a valid CSS selector because with an ordinary CSS selector function like `nth-of-type()`, you could just specify the element or id before the function instead of after. You can't do that with `upward()` because after the function you've navigated to a different DOM node.

> `element > foo:upward(1)`

In my case, that's inferior to what I'm proposing because I can select `foo` more efficiently than `element`.

> `foo:upward(1):is(element)`

As I've already said, `is()` isn't yet supported by all browsers.

> Please ask on https://www.reddit.com/r/uBlockOrigin/ when you want help in crafting filter.

Again: I don't need help crafting filters. I know what uBO can and can't do; the purpose of this Issue is to argue that it should be able to do more, and to report a couple of bugs. You haven't addressed either of those topics.

**Comment by strict-block** [comment]
> Sorry I don't understand what you are saying. The filter you mention is valid

IMO better add regex to exlude other characters than:

* "spacebar",
* `+`, 
* `>`,
* `,`
*  `~`,
*  `:` 

behind :`upward(XYZ)`.

So mark as invalid:
* `[` - `:upward(XYZ)[attrib]`, 
* `.` - `:upward(xyz).class`
* `#` - `:upward(ID)#` 

this minimalize these complications.

**Comment by gorhill** [comment]
> So mark as invalid

No, these are not invalid, it's valid CSS selector syntax as per [spec](https://www.w3.org/TR/2018/REC-selectors-3-20181106/#pseudo-classes):

> Pseudo-classes are allowed anywhere in sequences of simple selectors, **after the leading type selector**

You are asking that currently valid syntax become invalid, and that currently invalid syntax become valid, for the purpose of a use-case which is _already_ solved using current existing (CSS3 selectors compliant) syntax -- i.e. **a complete non-issue**.

Locking this invalid issue thread now, @awebeer256 is free to fork and scratch his own itch.

**Comment by gorhill** [comment]
> So mark as invalid

No, these are not invalid, it's valid CSS selector syntax as per [spec](https://www.w3.org/TR/2018/REC-selectors-3-20181106/#selector-syntax):

> A sequence of simple selectors is a chain of simple selectors that are not separated by a combinator. **It always begins with a type selector or a universal selector. No other type selector or universal selector is allowed in the sequence.**

You are asking that currently valid syntax become invalid, and that currently invalid syntax become valid, for the purpose of a use-case which is _already_ solved using current existing (CSS3 selectors compliant) syntax -- i.e. **a complete non-issue**.

Locking this invalid issue thread now, @awebeer256 is free to fork and scratch his own itch.
