### ISSUE TITLE
Untouchable elements for epicker and zapper

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uBlock-issues#1549]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hi, 

I found strange page then touching elements by epicker and zapper may no works...

I tried exlude someting like `::before` in code, but I can't see these in devtools

### A specific URL where the issue occurs

`https://eschenker.dbschenker.com/app/launch-page/public`

### Steps to Reproduce

1. try block pop-up about cookie by like:
   `eschenker.dbschenker.com###es-shell-overlay-container:has(es-privacy-modal)`
   `eschenker.dbschenker.com##.es-shell-global-scrollblock:style(overflow-y: auto !important;)`
2. try block someting new by epicker or remove by zapper
3. both tools can't found clickable elements

To reproduce pop-up maybe needed is VPN with EU masking geo-localization.

### Actual behavior:

Can't use epicker / zapper when block something on page.

### Expected behavior:

Epicker and zapper should works after hide pop-ups **without** `:remove()` / html filtering / scriptlets (to abort loads pop-ups).

### Your environment

* uBlock Origin version: 1.34.1b3
* Browser Name and version: Firefox 87.0.0
* Operating System and version: Windows 10 Pro 20H2

**Comment by strict-block** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8860

**Comment by strict-block** [comment]
I found inline `style="pointer-events: none;"` 🤯 

 I was confused by the possible highlighting of text that should not have happened.

**Comment by uBlock-user** [comment]
@gorhill Picker is not able to select `eschenker.dbschenker.com###es-shell-overlay-container`

**Comment by strict-block** [comment]
Possible workaround:

`eschenker.dbschenker.com##[style*="pointer-events"][style*="none"]:style(pointer-events: auto !important;)`

or


`eschenker.dbschenker.com##+js(ra, style, [style*="pointer-events"][style*="none"], stay)`

**Comment by uBlock-user** [comment]
@strict-block Does `eschenker.dbschenker.com##+js(ra, style, es-shell-root[style^="pointer-events:"])` work for you ?
