### ISSUE TITLE
uBlock is causing pinned tab to crash after clicking a link from the pinned tab

### ISSUE THREAD

**Issue by ayuanx** [uBlockOrigin/uBlock-issues#1550]
More details:

https://bugzilla.mozilla.org/show_bug.cgi?id=1702388

I initially thought it was a bug of Firefox, but it turns out to be a bug of uBlock Origin.

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
uBlock Origin v1.34.0

**Comment by uBlock-user** [comment]
> but it turns out to be a bug of uBlock Origin.

uBO is HTML/CSS/JS, so crashing an entire tab is simply not possible.

**Comment by gwarser** [comment]
Can be popunder filter. Check the logger.

**Comment by ayuanx** [comment]
> Can be popunder filter. Check the logger.

Wow, amazing. Exactly as you said.
After removing popunder filter, the crash is gone.

But still, no filter, popunder or any other, should crash their parent tab.

**Comment by gorhill** [comment]
There was no crash, the tab was closed because of the filter.
