### ISSUE TITLE
Website performance is blocked

### ISSUE THREAD

**Issue by artemmm308** [uBlockOrigin/uBlock-issues#1552]
Hello Raymond. I understand correctly that if I installed uBlock to block ads, then I expect that it will block ads, and not the functionality of the site, right?

I know that you don’t speak Russian, and unfortunately I don’t speak English, but I’m trying to describe the problem in English as best I can, I immediately apologize for the accuracy of the translation. First, briefly the main essence of the problem -

The developer dimisa uses ad blocking plugins (filter) for his personal greedy purposes, he blocks the user functions of sites that are used by people he dislikes.

Now in more detail, although it seems to me it does not matter -

For quite a long time I have been using uBlock and there have never been any serious problems with this plugin. But not so long ago, I and many other users began to notice that with uBlock enabled, not only ads are blocked, but entire blocks, and even entire pages of sites, I am not a programmer, I am an ordinary layman who uses a ready-made product, I do not understand plugin settings , and filters installed in them, and is not obliged to understand all these things, so I just decided to change uBlock to ADBlock, deciding that the problem is in the plugin, but in the installed ADBlock, a significant part of many sites were blocked along with ads in the same way, I and other users began to find out the reason, and soon it became clear that the dimisa developer was using ad blocking plugins (filter) for their own purposes, as we understood for revenge on users, for allegedly being rude to him somewhere, and in order to take revenge he began to block the functions of the sites these people use.

I don’t care at all, and I shouldn’t care if he was rude and rude, or he came up with it in his fantasies, it’s difficult for me to judge its adequacy after specific questions asked by users, and his answers to them, which do not carry any common sense, even more so if there were definitely reasons for this ... but this is absolutely not important in this case, but what is important is that dimisa brazenly and illegally disrupts the performance of sites with the help of popular plugins that use its filter, created to block ads, not block functions of sites and clarification of personal relationships, I repeat, he does it deliberately and for his own purposes, having arrogated to himself the right to block whatever he wants, one of the moderators told me that he completely blocked the administrative part of the site, because of which the site became completely impossible, everything this is very similar to the usual extortion of money from administrators, or Internet terrorism ...

I do not have my own sites, and personally I have nothing to block him, so I am not afraid of his attacks, and I say what I see with my own eyes.

I absolutely know where on one of the sites, for example, opensharing.org began its intervention with the help of its filter into the site's performance. And everything was like this, this small site worked for years, did not interfere with anyone, did not quarrel with anyone, and at some point people began to notice that along with advertising, the functions of the site are blocked, it would seem, why suddenly such a harmless a thing like the "Thank you" button located in each topic that grateful users click, or why the "HIDE" function is suddenly blocked (hiding text or other content), or for example, there is a specially created page for exchanging buttons (links) with friends' sites, or the page has nothing to do with advertising, but dimisa blocks these buttons, and many other functions of the site have nothing to do with advertising, up to displaying the "header / logo" of the site and even a page with resource rules.

The users, including myself, decided, this is an accident, everyone can make a mistake, let us know about it and fix the problem ... well, they began to report this almost every day through the function in the plugin "report a problem on this page", they reported for a week , secondly, there was no reaction, dimisa did not fix its locks and did not fix it, well, in the end, some users seem to have already begun to be rude in messages about the problem, although this is said by "dimisa" himself, whether it is true or not, I don’t know, and even if is that so, what did he expect after ignoring messages, affectionate words and words of gratitude? In any case, this does not give him any right to use ad blocking plugins for his own personal purposes and arrogate to himself the right to establish his own rules on sites that do not belong to him.

At least four more resources, much larger than opensharing.org, he does the same thing, disrupts their performance with an ad blocking filter, blocking not ads but the functionality of sites, I don't know if he understands that this is a real crime, and he also draws developers into it plugins uBlock, ADBlock and the like, or he played so much in "Lord God" that he does not realize the possible consequences ... I'm not talking about the reputation of plugins using his filter ...

Well, in general, after a skirmish with users on the forum forums.lanik.us where, by the way, he repeatedly admitted that it makes it impossible for sites to work on purpose, he still partially unblocked the functions of the sites, but still stubbornly continues to do his little dirty tricks with the filter, blocking then one function, then another, then again removes the lock for a while, and again locks, and so it goes in a circle all the time.

When a topic was created on the forum forums.lanik.us, on which, by the way, no one is obliged, did not want and was not going to register from people I know, he insolently simply forced to register, supposedly on the forum he will answer everything (apparently this is some kind of new method of attracting users to a completely unnecessary and useless forum for them), by the way the last time on this forum he in a rude form "sent to ...." one of the users, and bluntly said that he did not intend to solve the problem, and was not going to talk , the question immediately arises, for what purpose he constantly sends to the forum, and forces them to register there, while he was not going to do anything, apparently, and is not going to do anything, but on top of that, he also edits posts after correspondence, both his own and others', what then comes out of it is not difficult to do it ...

Initially, I and all the users with whom I spoke were sure that the problem was in the uBlock, ADBlock and similar plugins, but when he himself admitted that - "No blocker by itself does anything, connected filters are responsible for this, in this case - the filter RU AdList "And then he admitted that he also deliberately spoils the performance of the sites, supposedly to attract the site moderators to the dialogue ... Everything became clear, it was not plugins that were to blame, namely the developer of the" dimisa "filter deliberately blocking the work of the site, it came to the point that he began to demand access to the site, ostensibly in order to understand where his error was ... by the way, why but decided that the moderators were rude to him? After all, he does not allow normal use of the site not only for moderators, but also for ordinary users who have been visiting the site for years without problems, until "dimisa" appeared and began to try to establish their own orders on a site that does not belong to him, for example, a topic created by users cannot pass moderation, since dimisa blocked the administrative part of the site for revenge on the moderators, I cannot give screenshots since I do not have access there, but because of this blocking, a lot does not work.

Judging by the large number of similar topics found on the Internet, in which the illegal activities of dimisa are discussed, I guess that here too there will be quite a few henchmen of the developer of the "dimisa" filter who apparently receive a percentage of extortion from him, so I will not answer anything else here, the more that he simply ignores all questions and messages about specific problems, in response to almost everything that they write to him carries some kind of crazy nonsense that is not related to the problem, the developer of "dimisa" knows perfectly well what and where he is illegally blocking, and I just remind him about this, and let the uBlock developers know what happens to the RU AdList filter that is installed in their plugin. And I want "dimisa" to know that this has already become a matter of principle, and it does not matter for small or large sites, it does not allow them to work fully, even if we and the users have to spend our own money, we will ensure that "dimisa" stops its illegal activities.

A few screenshots, some of this has already been fixed, and some has not been working for more than a year, there is no administrative part, only the management of the resource sees it, in any case, this is only a small part of its illegal actions -

With ad blocking - https://d.radikal.ru/d29/2104/cf/228e02e6b97e.png

No ad blocking - https://b.radikal.ru/b32/2104/bb/b194cde92a38.png

With ad blocking - https://b.radikal.ru/b40/2104/c0/2d562befad9d.png

No ad blocking - https://c.radikal.ru/c22/2104/ff/251f8aefdd42.png

With ad blocking - https://d.radikal.ru/d34/2104/36/6dd2b1c8b0e9.png

No ad blocking - https://c.radikal.ru/c31/2104/55/4478046731aa.png

With ad blocking - https://b.radikal.ru/b30/2104/6b/3e9adfd0601f.png

No ad blocking - https://d.radikal.ru/d33/2104/6d/12e7b77e719b.png

With ad blocking - https://d.radikal.ru/d42/2104/07/38b81c0e3c39.png

No ad blocking - https://c.radikal.ru/c11/2104/fb/34d540894679.png

With ad blocking - https://b.radikal.ru/b23/2104/da/322a4bec2ab4.png

No ad blocking - https://c.radikal.ru/c05/2104/24/ef1ab7837d0e.png

With ad blocking - https://b.radikal.ru/b42/2104/c0/24b0ca703a3a.png

PS. I myself installed uBlock in my browser again, as I like it more than others, but the developer's filter "dimisa" still does not allow to fully use many sites.

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> The developer dimisa uses ad blocking plugins (filter) for his personal greedy purposes, he blocks the user functions of sites that are used by people he dislikes.

@dimisa-RUAdList

**Comment by adranger** [comment]
You can use the AdGuard Russian list instead: https://filters.adtidy.org/extension/ublock/filters/1.txt

**Comment by dimisa-RUAdList** [comment]
I am aware of this complaint. Its author previously spewed a huge amount of shit, without specifying the data that must be used to reproduce the problem. And even here he does not give them. You cannot fix something that is not described in any way.

**Comment by gorhill** [comment]
Closing as invalid, filter issues must be filed as uAssets or Reddot as pointed out in the template. When reporting a filter issue, provide all details for other to reproduce and be specific, vaguely described issues can not be resolved.
