### ISSUE TITLE
(Firefox Nightly for Android) uBO discards large amounts of entries from some lists, especially EasyList

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1554]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (1.34.0)
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I am aware that this may be a tricky one to reproduce, but I can just as well write this issue report, and then provide whatever more info you'll be asking for along the line.

Essentially, after I a few days ago decided to upgrade from Fennec 68 to Firefox Nightly (having heard that I could run IDCAC on the latter nowadays), I noticed something was pretty amiss when browsing some Nordic newssites, i.e. `tv2.no` and `tv2.dk`, where such important entries as `##.adunit-wrapper` (EasyList) and `##.tv2-ad` (Dandelion Sprout's Nordic Filters) were not being applied.

When I first noticed the problems, I was using https://filters.adtidy.org/extension/ublock/filters/2_optimized.txt and figured out that the non-blocking was to be expected; but the problem has continuously remained after I switched to the regular list versions, turned off DNS filtering on my Android, turned off AdGuard for Android, reinstalled Firefox Nightly, reset uBO's list building, *and* reset uBO's preferences.

So I took a look in uBO's settings, and discovered that no matter what I did, no matter which lists I turned on and off, uBO discarded no less than 20,000 entries from EasyList, without any indication in the list viewer as to which ones (Most commonly shown as "41,180 of 63,772 used"; the number would fluctuate between 41,000 and 44,000).

Similarly, it discards ~150 entries from Dandelion Sprout's Nordic Filters ("1,792 of 1,945 used"), when there's normally no need for it to discard more than ~30 AdGuard-exclusive entries.

This problem is *not* present in Fennec 68 with the same uBO version.

I can provide screenshots and uBO logs on request; but not right off the bat because I have an exam today.

### A specific URL where the issue occurs

uBO's settings/dashboard.

### Steps to Reproduce

1. Install https://play.google.com/store/apps/details?id=org.mozilla.fenix
2. Install uBlock Origin
3. Go to uBO's settings to sync the lists
4. See that ~20,000 entries from EasyList are discarded by uBO

### Expected behavior:

EasyList entries, and cosmetic entries in general, are correctly recognised and applied by uBO on websites.

### Actual behavior:

A whole lot of placeholders remain on websites because cosmetic entries from some lists aren't recognised or applied by uBO.

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Firefox Nightly 210410 17:02 Build 2015803851 for Android
* Operating System and version: Android 10

**Comment by mapx-** [comment]
check again the option bellow

![image](https://user-images.githubusercontent.com/10303732/114504498-403bf800-9c2f-11eb-8049-0551c83f406f.png)

**Comment by uBlock-user** [comment]
uBO on Firefox has _Ignore generic cosmetic filters_ enabled by default, disable that.

**Comment by DandelionSprout** [comment]
I can confirm that the option is in fact turned **on**. 
![Screenshot_20210413-082827](https://user-images.githubusercontent.com/22780683/114506605-54cdbf80-9c32-11eb-85bd-4babf5b433dd.png)
![Screenshot_20210413-082840](https://user-images.githubusercontent.com/22780683/114506622-5b5c3700-9c32-11eb-825a-7690432b8cde.png)

**Comment by DandelionSprout** [comment]
Or... wait... now I see what you guys actually meant.

An odd thing in my eyes to have turned on by default, but that explains it.
