### ISSUE TITLE
How to define filter only for non-subpage?

### ISSUE THREAD

**Issue by TheOnlyRealCoder** [uBlockOrigin/uBlock-issues#1555]
I.e.
Rule active for
`www.reddit.com/`
Rule inactive for
`www.reddit.com/any-subpage`

I already tried:
`www.reddit.com/reddit the front page of the internet##div
www.reddit.com/reddit the front page of the internet.html##div`
But neither of these works.
(I got that filename from the filename when saving the page)

**Comment by uBlock-user** [comment]
Ask question at https://old.reddit.com/r/uBlockOrigin/
