### ISSUE TITLE
Youtube videos redirecting to community pages.

### ISSUE THREAD

**Issue by SacchiHikaru** [uBlockOrigin/uBlock-issues#1559]
Recently (as in, it started about a week ago), almost every time I click on a Youtube video it will redirect me to a community page instead, no matter if I'm clicking from my home page, my sub feed or a search result. Sometimes the video loads for only a moment before redirecting me. The only reason why I believe this is uBlock Origin related is because the problem vanishes pretty consistently when I turn it off and do a hard refresh of the page (CTRL+F5, specifically), and it seems to stay gone for a while even if I turn the extension on again, but it comes back eventually.

I'm using the firefox extension, with Firefox 89.0.

**Comment by uBlock-user** [comment]
Do not skip the issue template, there's nothing actionable here.
