### ISSUE TITLE
Change korean readme.md

### ISSUE THREAD

**Issue by lill74** [uBlockOrigin/uBlock-issues#1560]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Korean version of readme is outdated.

### A specific URL where the issue occurs

On readme.md,

Current korean readme
![outdated](https://user-images.githubusercontent.com/12353597/115147858-025c2b00-a098-11eb-824c-71497ed469c4.png)

The new one I translated
![new one](https://user-images.githubusercontent.com/12353597/115147956-57983c80-a098-11eb-85bc-6a2c6de1a17f.png)

### Steps to Reproduce

1. Just change url from `https://github.com/delightbot/uBlock/blob/master/README.md#ublock-origin` to `https://github.com/lill74/uBlock/blob/master/README.md#ublock-origin` on readme.md

### Expected behavior:

NA

### Actual behavior:

[What actually happened]

NA

**Comment by gorhill** [comment]
Thanks for pointing this out -- I removed links to all translated versions, they were all outdated.
