### ISSUE TITLE
uBlock + Chrome browser = In the last week uBlock started to make problems with google docs and google sheets

### ISSUE THREAD

**Issue by Dhragas** [uBlockOrigin/uBlock-issues#1561]
In the last week uBlock makes it impossible to work with google docs, google sheets and google slides.

Here follows a few comments from the support field for uBlock in Chrome web store:

**uBlock and Google Docs**
UBlock is messing with formatting and typing on Google Docs. It displays the text strangely and type symbol is always on the left, rather than following text. I had to disable my extensions 1 by 1 and it is definitely uBlock. - 3 days ago

**uBlock and Google Docs**
UBlock is messing with formatting and typing on Google Docs. It displays the text strangely and type symbol is always on the left, rather than following text. I had to disable my extensions 1 by 1 and it is definitely uBlock.  - 3 days ago

I came to this page to report the same issue. When UBlock Origins is on, all my text Google Docs are formatted shifted to the right, and all text in Google Slides are squished/jumbled.  - 3 days ago

**Google docs behaves weird with uBlock**
Formatting is all jumbled up and cursor stays stuck to the beginning of the sentence. Everything works fine with ublock disabled though. - 4 days ago

**Yup also having issues with google docs/slides**
Seems like ublock is messing with google docs making the text overlap on itself and be all in the wrong place!  - 5 days ago

**Google Docs screws up when uBlock is active**
Whenever the extension is active, Google Docs messes up severely. Text runs off page and the cursor is stuck at the beginning of the line. Highlighting also does not work and where the characters appear is very inconsistent. Others seem to be dealing with this issue as well.  - 5 days ago

**Google Docs Not Working Correctly**
Also having issues with Google Docs. Text runs completely off the page and becomes non-interactable. Images don't format properly, and overlay themselves over text. Problem disappears when I turn off UBlock Origin.
For reference, I'm using Chrome. The problem does not occur when I switch to Firefox - 6 days ago

**UBlock Origin and Google Docs**
Google Docs is really messed up when UBlock Origin is active. - 6 days ago

**Comment by uBlock-user** [comment]
force update Easylist.

**Comment by gorhill** [comment]
["uBlock causing problems with Google Docs"](https://www.reddit.com/r/uBlockOrigin/comments/mqstz2/ublock_causing_problems_with_google_docs/):

> Force an update of EasyList, there was a [fix committed 12 hours ago](https://github.com/easylist/easylist/commit/9bbd80158294f6b577d996fec46de2a3b071464e).
