### ISSUE TITLE
Service workers cannot be disabled in Canary

### ISSUE THREAD

**Issue by superpoincare** [uBlockOrigin/uBlock-issues#1562]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On Chrome Canary, service workers can't be blocked by the filter `$csp=worker-src 'none'`

### A specific URL where the issue occurs

`https://www.youtube.com/`

### Steps to Reproduce

1. On a fresh install of Chrome Canary with uBO installed, add this filter `$csp=worker-src 'none'`
2. In advanced settings, change `suspendTabsUntilReady` to `yes` (as described [here](https://bonina.eu/web/disable-service-workers-chromium-browsers/))
3. Visit YouTube. 

### Expected behavior:

Service worker is not loaded. In Chrome stable this is working fine. 
### Actual behavior:

Service worker gets loaded as can be seen in developer tools.

### Your environment

* uBlock Origin version:  v1.34.0
* Browser Name and version: Version 92.0.4483.0 (Official Build) canary (64-bit)
* Operating System and version: Windows 10 Home Single Language, 20H2, OS build: 19042.928

**Comment by uBlock-user** [comment]
Did you un-register all service-workers from `chrome://serviceworker-internals` page in Chrome ?

**Comment by superpoincare** [comment]
Oh yeah did that. And various other ways like clearing all caches, site specific data etc. too.

**Comment by gwarser** [comment]
This was problematic even before 90. `suspendTabsUntilReady` is very basic on Chrome.

**Comment by gorhill** [comment]
> In advanced settings, change `suspendTabsUntilReady` to `yes` (as described [here](https://bonina.eu/web/disable-service-workers-chromium-browsers/))

So this happens at browser launch?

[Documentation for `suspendTabsUntilReady`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready):

> Disclaimer: especially in Chromium based browsers, even with this setting enabled, it's impossible for uBO to guarantee with 100% certainty that everything will be properly blocked when the browser is launched. **This is a by-design browser issue** -- do _not_ open an issue on uBO issue tracker about this.

**Comment by superpoincare** [comment]
@gorhill 

I didn't check that. I used it with caches fully cleared and loading sites. I just mentioned "suspendTabsUntilReady" for the sake of completeness. So likely the issue is not that. 

On Chrome stable (90), I don't face this issue either with browser launch or anytime. The service worker is always blocked. 

But in Canary even with all site data cleared (ie service workers cleared too), the service worker appears at the end of the page load. 

I think it's probably because for some reason Canary prevents uBO from adding the `worker-src` csp header.

**Comment by superpoincare** [comment]
Yeah, when I open a browser without clearing caches and see `chrome://serviceworker-internals/` I see the youtube service worker registered. Both when I unregister and don't do anything, it appears again on visiting the site. 

But it seems to me that since the service worker anyway installed on a fresh load, it will load again. 

On Chrome stable I see this message in Devtools console:

> Refused to create a worker from 'https://www.youtube.com/sw.js' because it violates the following Content Security Policy directive: "worker-src 'none'".

which is absent in Canary. 

But I understand your point about Canary having its own issues which may not appear when it becomes stable. So I think you can close the issue and maybe if we see it in Beta just before Chrome release, I can open again?

**Comment by uBlock-user** [comment]
> But I understand your point about Canary having its own issues which may not appear when it becomes stable. So I think you can close the issue and maybe if we see it in Beta just before Chrome release, I can open again?

That would make it a Chromium issue, you would need to file a report on their bug tracker.
