### ISSUE TITLE
Feature request: Automatic go back on "uBlock Origin has prevented the following page from loading:" 

### ISSUE THREAD

**Issue by MorsMortium** [uBlockOrigin/uBlock-issues#1565]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As the title says. 
Additionally, in my use case, a simple settings option, that switches it on and off would be perfect.
But I don't know, if it would be better, to implement something, that is closer to the filters, so that it can be switched by site, instead of globally.

### A specific URL where the issue occurs

Any URL, that triggers moz-extension://da0d4707-22ea-4fb1-8736-c89d90e70613/document-blocked.html

### Steps to Reproduce

1. Add ||youtube.com^ to My filters
2. Open youtube.com

### Expected behavior:

An option in the settings to make uBlock Origin go back to the previos site, in case of document-blocked.html

### Actual behavior:

No such option

### Your environment

* uBlock Origin version: 1.35.0
* Browser Name and version: Firefox 88.0 (64-bit)
* Operating System and version: Manjaro Linux 21.0.2

**Comment by uBlock-user** [comment]
There's the _Go Back_ button, takes on click only.

**Comment by uBlock-user** [comment]
There's the _Go Back_ button, takes one click only.

**Comment by gorhill** [comment]
Declined, I don't see how this is a good idea, the document-blocked page is there to warn user of what is happening and thus make a decision about this.
