### ISSUE TITLE
Element Picker doesn't do anything on facebook.com

### ISSUE THREAD

**Issue by vsrawat** [uBlockOrigin/uBlock-issues#1569]
on facebook.com Home page (Timeline), clicking on element picker doesn't select anything on the page.

w8.1 (64 bit), ff 66.0.5 (64 bit), add-on updated right now.

Thanks.

**Comment by uBlock-user** [comment]
Is cosmetic filtering disabled for facebook ? If so, enable it.

**Comment by vsrawat** [comment]
whether "Disable cosmetic filtering" is ticked or unticked, nothing 
happens. No change.

Thanks.
-- 
Rawat

**Comment by uBlock-user** [comment]
Test on default settings and with all other extensions disabled.

**Comment by gorhill** [comment]
Closing as invalid, these dismissal of template are not acceptable -- there is a reason reporters are asked to narrow down using default settings etc.

**Comment by vsrawat** [comment]
Problem not solved, and developer jumps to close the complaint as it 
didn't fill the long complicated form.

You should not be a developer, you should be a petty clerk in some 
remote local government office that rejects applications if not filled 
in triplicate. Or that is what is your real life job.

There is a thumb rule that when a thousand person face a problem, one of 
them bothers to speak up. But you will silence that one person also.

If you have kids at home, why don't tame and discipline them instead of 
forcing your users to dance at your figers? May be home kids don't 
listen to you? They shouldn't if you talk such things.

The sickly format forced on users to do 90% of research themselves is a 
paranoid creation. Whatever minimal information was required that was 
provided.

If we were able do that much research, we will develop our own ublock 
also, and then you can close your shop.

Only a handful of people are using your extension, from the millions of 
ff users, what you are exactly boasting of? I can as well delete your 
extension today and my life will go on as usual.

Shameful behavior and worldview of this extension's developers and this 
forum.

Thanks.
-- 
Rawat

**Comment by gorhill** [comment]
> close the complaint as it didn't fill the long complicated form.

The purpose of the template is to ensure the typical questions that will be asked _anyways_ to rule out configuration issues in either your browser or uBO are answered upfront, thus saving time for everybody.

> you can close your shop

The project is not a business, it's all volunteer-driven, nobody is paid or otherwise derive any material benefits from investing their time in the project. It's actually a relief to volunteers here when entitled users, unwilling to invest an incredibly tiny fraction of the time invested by volunteers, uninstall uBO and find something else.
