### ISSUE TITLE
Firefox nightly 63 for Android has issue loading pages if ublock is enabled

### ISSUE THREAD

**Issue by ale82to** [uBlockOrigin/uBlock-issues#157]
I m not sure if it's ublock fault I opened a bug with Mozilla
anyway with today build of Firefox 63 for Android if ublock is enabled firefox often fails to load pages especially is pages are set to open links in new tab
reverting to yesterday build of Firefox nightly fixes every issue.

**Comment by ale82to** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1482180
bug at mozilla

**Comment by uBlock-user** [comment]
> if ublock is enabled firefox often fails to load pages

Put back the template and fill in the details, without that you're guessing and there's base for the issue you think is with uBO.

**Comment by ale82to** [comment]
there 's nothing more I can say with today build of Firefox nighlty for Android with ublock enabled pages often fails to load more often if the links have target_blank
to solve the issue I can revert to yesterday build of Firefox or stay with today build and disable ublock.
my OS is android and ublock version is latest dev 1.16.17.0

**Comment by uBlock-user** [comment]
Based on your [posting record](https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aale82to on uBO repo and here, I'm closing this. Put back and fill the template for this issue to be considered worth investigating.
