### ISSUE TITLE
Text in Manage Extension Shortcuts includes escaped &shy;

### ISSUE THREAD

**Issue by madsmtm** [uBlockOrigin/uBlock-issues#1570]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The danish translation of `Enter element picker mode` and `Enter element zapper mode` includes `&shy;` to fix https://github.com/uBlockOrigin/uBlock-issues/issues/907 - however, the same strings are also used in the Manage Extension Shortcuts section, where the `&shy;` is escaped (and thus show up verbatim instead of as soft hyphens).

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Change Firefox language to Danish/Dansk
2. Go to `about:addons`
3. Click "Manage Extension Shortcuts" in the settings wheel
4. Scroll down to uBlock Origin

### Expected behavior:

The text says `Gå til elementvælgertilstand` and `Gå til elementdræbertilstand`

### Actual behavior:

The text says `Gå til elementvælger&shy;tilstand` and `Gå til elementdræber&shy;tilstand` (with the `&shy;`).

Illustrated in the following screenshot:
<img width="978" alt="ublock-origin-danish-shy" src="https://user-images.githubusercontent.com/10577181/116409374-117b6f80-a834-11eb-86ed-7a44d4bfac90.png">

### Your environment

* uBlock Origin version: 1.35.0
* Browser Name and version: Firefox 88.0
* Operating System and version: MacOS 10.14.6 Mojave

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/7574d16509b811adacc55032736fd12f4c74e8a2>. Since the strings are used declaratively by the browser, I had to copy-paste the soft hyphen character into the `messages.json` file.
