### ISSUE TITLE
Making Easylist Cookie a default list

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#1573]
With Vivaldi blocking consent/cookie/gdpr warnings by default, should we also follow suit and block consent messages by default in uBO.

https://www.forbes.com/sites/barrycollins/2021/04/29/vivaldi-browser-kills-irritating-cookie-pop-ups/
https://www.zdnet.com/article/vivaldi-browser-tries-to-tame-website-cookie-consent-forms/
https://www.theregister.com/2021/04/29/vivaldi_3_8/

Has been discussions to make it [default in Brave,](https://github.com/brave/brave-browser/issues/15575) and whether uBO would block consent messages by default.

I've created a seperate uBO list options for https://github.com/easylist/easylist/commit/84d2370717e6a162f8bc194ff9344a22f3f838c6   (to fix sites that break scrollbars etc) Which we can bring over any consent-related filters from uBO annoyances

**Comment by uBlock-user** [comment]
Sounds like https://github.com/uBlockOrigin/uBlock-issues/issues/1111

**Comment by ryanbr** [comment]
Annoyances by default might be stretch, just consent messages here

**Comment by Yuki2718** [comment]
Frankly, cookie lists are false-positive prone, enabling it by default will keep it from being install-and-forget solution for everyone. Nevertheless nice to see you've added the sublist for uBO.

**Comment by ryanbr** [comment]
Closing, we'll let the list mature a bit more. But given Vivaldi has defaulted this, we can see how many false positives (or if they are reported)

**Comment by krystian3w** [comment]
A few pop-ups may need use `watch-attr` = so generated 1 second blinks before hide Cookies/GDRP:

`hrkgame.com##.dimmable, .dimmed:style(overflow: auto !important;)`
`hrkgame.com##.modals.dimmer > .gdpr.ui:style(visibility: hidden !important;)`
`hrkgame.com##.modals.dimmer > .gdpr.visible:upward(1):watch-attr([class])`

Or these alpine combinations if we prefere pure CSS method detection (still possible see blinks):

`hrkgame.com##.dimmable, .dimmed:style(overflow: auto !important;)`
`hrkgame.com##html > body .modals.dimmer > .gdpr.visible:upward(1):style(display: none !important;)`
`hrkgame.com##html:root > body .modals.dimmer > .gdpr.hidden:upward(1):style(display: flex !important;)`

Problem on hrkgame generate pop-up in settings about enable 2FA, simple filter don't allow enable/disable 2FA: https://github.com/AdguardTeam/AdguardFilters/issues/69498
