### ISSUE TITLE
Move Fanboy Annoyances/Easylist Cookies to uBO-compatible filters

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#1574]
To improve cookie/annoyances blocking, Annoyances and Cookies will include uBO filters. 

To improve the quality and reliability of Cookies (and also Annoyances list), we'll be accepting uBO filters
Related: https://github.com/brave/adblock-resources/pull/24

`https://secure.fanboy.co.nz/fanboy-cookiemonster.txt` -> `https://secure.fanboy.co.nz/fanboy-cookiemonster_ubo.txt` 
`https://secure.fanboy.co.nz/fanboy-annoyance.txt` -> `https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt`

Thanks

**Comment by gorhill** [comment]
Why not just use an `!#include` directive to cause uBO to load the uBO-specific sublist? That is exactly the primary purpose of the directive, to allow filter list maintainers to write filters specific to uBO while keeping their list compatible with basic EasyList syntax.

**Comment by ryanbr** [comment]
Making it compatible among all the extensions, some adblock extensions won't understand `!#include`  and will try to parse uBO filters.

**Comment by ryanbr** [comment]
Example of this, https://github.com/easylist/easylist/commit/53480e6d0045165a0be33a5593fc0bd5c782664e

It may ignore `schulze-immobilien.de##*:style(filter: none !important)` but will then process the `chulze-immobilien.de##.wrap__cookie` which will break the site on non-uBO extensions.

**Comment by gwarser** [comment]
`!#include` looks like comment in main list source. uBO compatible filters will be in separate list "include" is pointing to.

https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#include-file-name

**Comment by ryanbr** [comment]
Ah, misunderstood the usage. Closing.

**Comment by gwarser** [comment]
So, you don't have access to `easylist-downloads.adblockplus.org` and uBO fails to fetch sub-lists from there @ryanbr ?

https://listauthorschat.slack.com/archives/C010N14G4TF/p1620925632089400

@gorhill ?

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a632e29d24d3c3691e93a5125aa013204d9545a0  disabled for the timebeing

**Comment by gorhill** [comment]
uBO users should just subscribe to that list through your own `fanboy.co.nz` server -- it should be assumed the list hosted on ABP's server is strictly made for ABP and as such issues like the one here can arise when subscribing to something at `easylist-downloads.adblockplus.org`.

**Comment by gwarser** [comment]
Oh, my fault, I thought "Fanboy's Annoyance" is mirrored on `easylist-downloads.adblockplus.org` in uBO `assets.json`.

**Comment by mikhaelkh** [comment]
> RU AdList contains uBO-specific syntax such as `:style()` or `+js()`, so it does seem ABP deals properly with these instances of uBO-specific syntax.

RU AdList has different verisons for ABP and uBO: [advblock.txt](https://easylist-downloads.adblockplus.org/advblock.txt) for ABP and [advblock+cssfixes.txt](https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt) for uBO.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2222

**Comment by PhoenixIndigo** [comment]
So why add another subscription, if you just need to replace it by default?
