### ISSUE TITLE
Ublock origin not blocking Youtube Ads properly 

### ISSUE THREAD

**Issue by prorounak2005** [uBlockOrigin/uBlock-issues#1578]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature] When I am watching videos on youtube ads are not getting blocked properly and I can see the skip option and sometimes I am really getting annoyed by this .  This is the screenshot - 
![image](https://user-images.githubusercontent.com/69617708/116856096-2121fc00-ac18-11eb-88d6-8fb198115450.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
I expected that it should block the ads instantly instead of skipping it . 
### Actual behavior:

[What actually happened]
It didnt block the ad 
### Your environment

* uBlock Origin version: uBlock Origin v1.34.0
* Browser Name and version: Chrome Version 90.0.4430.93 (Official Build) (64-bit)
* Operating System and version: Windows 10 Pro

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
