### ISSUE TITLE
"Network protocol violation" error page with Uncloak CNAME + 3p blocking enabled in Firefox nightly

### ISSUE THREAD

**Issue by koobs** [uBlockOrigin/uBlock-issues#1579]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A firefox protocol violation error page is observed when Unblock CNAME option and 3p blocking is enabled in Firefox Nightly. The issue may be reproducible in earlier branches/releases, this was not tested. First reproducible build/extension versions is unknown. 

My current understanding is that uBO is correctly blocking the request(s), I may however be incorrect for this specific case. 

This report is with respect to what is probably an unexpected result/symptom/messaging/experience, or a potential indicator of upcoming issues in future Firefox releases versions for uBO. In most/normal blocking scenarios, blocking results in non-error outcomes for the user, such as empty pages, or missing functionality.

#### Error

```
The site at <domain> has experienced a network protocol violation that cannot be repaired.
```

#### Error Screenshot

![firefox_fpqLLf3uzE](https://user-images.githubusercontent.com/1011612/117387631-bfdc8000-aed8-11eb-8649-12e0ea44c251.png)

#### Additional Information

 * DevTools Network Tab in reproduction case: Request blocked (NS_INTERCEPTION_ERROR_FAILED)
 * Developer Console (Screenshot)

![explorer_dRcisqaptr](https://user-images.githubusercontent.com/1011612/117390083-0c29bf00-aedd-11eb-91ca-9127705641f5.png)

### A specific URL where the issue occurs

` https://www.gandi.net/en-US`

### Steps to Reproduce

1. Enable Uncloak CNAME option in settings
2. Enable 3rd-party blocking
3. Load URL

The minimum reproducible test case includes:

 * Default settings
 * All options **disabled**, except **advanced user**  and **CNAME uncloaking**
 * All filters/lists **disabled**
 * My filters/lists/trusted sites **empty/default**
 * Firefox caching disabled (dev tools)

**Note**: The issue is reproducible with **default** settings. The above is a minimal reproduction isolation.

The issue is **not** reproducible when:

 * Only **3rd-party frames** is blocked (no requests are blocked)
 * Only **3rd-party scripts** is blocked. However ...
   * Scripts on `www.gandi.net` and `analytics.gandi.net` are **blocked**, one with  (see screenshot below)

I am not clear on whether these blocks are expected (www and analytics subdomains show up as green), or whether symptomatically related to the issue as reported.

![firefox_bQA8MIOYLI](https://user-images.githubusercontent.com/1011612/117388977-22cf1680-aedb-11eb-8844-05cb73a6d575.png)

#### Reproduction Screenshot

![firefox_dgYyk9jbqj](https://user-images.githubusercontent.com/1011612/117389379-cddfd000-aedb-11eb-9da1-f24b3831042d.png)

### Expected behavior:

Not an internal error page or protocol error 

### Actual behavior:

Firefox network protocol violation error page

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox Nightly 90.0a1 (2021-05-06) (64-bit)
* Operating System and version: Windows 10 Pro 20H2 19042.964

**Comment by uBlock-user** [comment]
> All options disabled, except advanced user and CNAME uncloaking
All filters/lists disabled

That's not default, so why do that ?

**Comment by koobs** [comment]
> 
> 
> > All options disabled, except advanced user and CNAME uncloaking
> > All filters/lists disabled
> 
> That's not default, so why do that ?

The reduce the test case and code paths involved.

> > Enable Uncloak CNAME option in settings
> 
> Already enabled by default for everyone

Explicit > Implicit (PEP20)

**Comment by gwarser** [comment]
SW is requesting data from 3p CDN (fastly), you are blocking it. All is fine.

**Comment by koobs** [comment]
Note: report is not specifically about blocking validity (or not), but rather the result (internal Firefox protocol violation error), which may indicate a request blocking api, method incompatibility or error handling issue.

**Comment by uBlock-user** [comment]
> but rather the result (internal Firefox protocol violation error

That sounds rather a Firefox issue, given it's a NIghtly build, can you reproduce this on stable build ?

**Comment by koobs** [comment]
> > but rather the result (internal Firefox protocol violation error
> 
> 
> 
> That sounds rather a Firefox issue, given it's a Nightly build, can you reproduce this on stable build ?

Clear in the OP:

- earlier builds not tested
- potential indicator of upcoming issues in future Firefox releases versions for uBO.

I'm happy to do any additional testing that is required to further isolate root causes, and/or wait pending a definitive assessment of whether the present result is appropriate/satisfactory, or whether there is something to be addressed, improved, wherever the ultimate resolution point is, in uBO or Firefox.

**Comment by gwarser** [comment]
This error page is just very panicky. This is probably how they attempt to fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1503072

**Comment by gorhill** [comment]
The page loads fine on my side except that it looks ugly with CSS from `gandi.map.fastly.net` being blocked, I don't get a _"The site at <domain> has experienced a network protocol violation that cannot be repaired.
"_ page.

**Comment by uBlock-user** [comment]
Googling this error leads to same issues happening on other websites where uBO wasn't present, so not specific to uBO.

**Comment by gorhill** [comment]
Ok, I could reproduce after I let the page load without any blocking. Once I reproduced, clearing the cookies make the issue go away. I don't see this as a uBO issue.

**Comment by gorhill** [comment]
> This is probably how they attempt to fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1503072

You're right, seems related as a hard reload also fixes the issue. Consequently, closing as a Firefox issue.

**Comment by koobs** [comment]
Appreciate the analysis and root cause identification. Wanted to make sure it was on your radar. Thank you all.
