### ISSUE TITLE
Fanboy Ultimate list doesn't update on v1.35b3

### ISSUE THREAD

**Issue by runboy93** [uBlockOrigin/uBlock-issues#1580]
When trying to update Fanboy Ultimate list, it will give error instead "A network error prevented the resource from being updated", I can access Fanboy Ultimate list through URL link on browser, but for some reason uBO version v.135b3 doesn't want update list as now.

https://www.fanboy.co.nz/r/fanboy-ultimate.txt

v1.35b3
Lubuntu 20.04.2 (x64)
Vivaldi 3.8

**Comment by uBlock-user** [comment]
![Capture2](https://user-images.githubusercontent.com/21290713/117613122-00135b00-b184-11eb-9837-12fc2bf3666b.PNG)

Included sublists are 404, @ryanbr - sublists are not available.

**Comment by ryanbr** [comment]
Should be resolved, force an update of the list @runboy93
