### ISSUE TITLE
Feature suggestion: comments on same line as filter

### ISSUE THREAD

**Issue by RedDragonWebDesign** [uBlockOrigin/uBlock-issues#1584]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Consider adding a feature where you can add space + exclamation mark + text to the end of a line, and it will create a same line comment. Example:

`test.com##.test !fixes issue https://github.com/owner/repo/issue/1`

This has a couple of possible benefits, including:
* You can alphabetize the filter list without your comments getting separated from the filter
* This comment style reduces the number of lines compared to doing {enter, comment, filter} (by as much as x3). Example:
````
! https://github.com/owner/repo/issue/1
test1.com##.test

! https://github.com/owner/repo/issue/2
test2.com##.test
````
vs
````
test1.com##.test !https://github.com/owner/repo/issue/1
test2.com##.test !https://github.com/owner/repo/issue/2
````
* It is clearer what line a comment is associated with. For example:

````
test1.com
! comment. what filter am I associated with? the one above or below? a same line comment would make this clearer
test2.com
````

### Your environment

* uBlock Origin version: uBlock Origin development build v1.35.3b0
* Browser Name and version: Chrome 90.0.4430.212
* Operating System and version: Windows 7

**Comment by gorhill** [comment]
Declined. Cosmetic filters can have spaces in them and supporting trailing comment would complicate far too much the parsing of cosmetic filters.

**Comment by garry-ut99** [comment]
Also a duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1438
