### ISSUE TITLE
Nag dialog

### ISSUE THREAD

**Issue by infinity-computers-dot-net** [uBlockOrigin/uBlock-issues#1586]
There needs to be a way to suppress this bloody annoying dialog.

![image](https://user-images.githubusercontent.com/57754746/118126461-4bca3c80-b3f0-11eb-8ccf-2346d1855f2b.png)

**Comment by gorhill** [comment]
Please stops disrespecting the template, you are burdening volunteers here with invalid issues, as clearly explained in the template -- this is not acceptable.

**Comment by uBlock-user** [comment]
This is uBlock Origin, not AdBlock Max, post this issue on their own repository instead of spamming here.

**Comment by gorhill** [comment]
User has been blocked, there is no excuse for repeatedly ignoring the template: it's not only repeatedly reporting a filter issue in the wrong repo, it's also reporting an issue with no details (as asked in the template) whatsoever for other to reproduce on their side, so this would waste volunteers' time even if it had been reported in the proper repo (as asked in the template).

**Comment by gorhill** [comment]
> This is uBlock Origin, not AdBlock Max

I interpreted the one screenshot as a site nagging the user, but you're right, it seems this might be something from another extension blocker.

**Comment by uBlock-user** [comment]
Seems this to be this - https://chrome.google.com/webstore/detail/adblock-max-ad-blocker/ggdpplfehdighdpleoegjefnpefgpgfh?hl=en

The unfortunate part is that there is no way to **enforce** the template like Bugzilla/Chromium tracker does, this is why this abuse continues.

**Comment by uBlock-user** [comment]
Seems to be this one - https://chrome.google.com/webstore/detail/adblock-max-ad-blocker/ggdpplfehdighdpleoegjefnpefgpgfh?hl=en

The unfortunate part is that there is no way to **enforce** the template like Bugzilla/Chromium tracker does, this is why this abuse continues.

**Comment by gorhill** [comment]
They left the _About_ pane unchanged, so user ended up here as a result. Properly filling in the template would have made the resolution of the issue easy and quick: not a uBO issue, user installed one of many sleazy copycats.
