### ISSUE TITLE
youtube autoplay broken

### ISSUE THREAD

**Issue by zlice** [uBlockOrigin/uBlock-issues#1588]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=9AYl10qxc0M

### Steps to Reproduce

1. play youtube video with autoplay on
2. go to end of song
3. next song doesn't play

### Expected behavior:

autoplay works

### Actual behavior:

[What actually happened]

goes to next song and waits for manual pla

### Your environment

* uBlock Origin version: latest
* Browser Name and version: firefox nightly
* Operating System and version: void x86_64 5.12.1

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636

**Comment by zlice** [comment]
If this belongs on 'uAssets' I can move there, sorry.
I don't see anything related to autoplay in there.

**Comment by uBlock-user** [comment]
No need to move, just post at that linked issue, on default settings/lists I can't reproduce it.

**Comment by zlice** [comment]
Thanks.
