### ISSUE TITLE
logger pause doesnt pause

### ISSUE THREAD

**Issue by zlice** [uBlockOrigin/uBlock-issues#1589]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

Pressing "pause" on the logger will change the icon but the logs keep coming.

### Expected behavior:

Logs freeze so you can read them

### Actual behavior:

The pause/play icon changes but doesn't seem to pause logs.

### Your environment

* uBlock Origin version: latest
* Browser Name and version: firefox nightly
* Operating System and version: void x86_64 5.12.1

**Comment by gorhill** [comment]
All works fine on my side.

**Comment by gorhill** [comment]
If nobody else is able to reproduce, I will close after 24 hrs.
