### ISSUE TITLE
Some ads are not hidden by the cosmetic filter in Chrome

### ISSUE THREAD

**Issue by Real-John-Cheung** [uBlockOrigin/uBlock-issues#1591]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

divs that match filter item `.wafer-beacon[data-wf-beacons]` and `.stream-items[data-wf-beacons]` are not caught in Chrome (version 90.0.4430.212 on macOS Catalina 10.15.7 ) (But caught in Firefox (88.0.1))

The ad is caught in Firefox
<img width="1586" alt="螢幕截圖 2021-05-19 下午10 48 48" src="https://user-images.githubusercontent.com/61215358/118833865-61f66200-b8f4-11eb-9eab-b55dd101aa09.png">

But not in Chrome
<img width="1414" alt="螢幕截圖 2021-05-19 下午10 49 52" src="https://user-images.githubusercontent.com/61215358/118834073-894d2f00-b8f4-11eb-8584-5473d89eafa3.png">

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

`https://hk.yahoo.com/`
### Steps to Reproduce

1. [First Step] Install Ublock Origin for add-on market (actually I tried build from source too)
2. [Second Step] Go to `https://hk.yahoo.com/ `
3. [and so on...]

### Expected behavior:

[What you expected to happen]

The ad is hidden by cosmetic filter

### Actual behavior:

[What actually happened]

The ad is not caught in Chrome

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version: Chrome  90.0.4430.212
* Operating System and version: macOS Catalina 10.15.7

**Comment by uBlock-user** [comment]
Is AdGuard Chinese enabled in filter lists pane on Chrome ?
