### ISSUE TITLE
Upward hide more than closest/nearest ancestor

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uBlock-issues#1593]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Sometimes `:upward(element)` are danger if filter no have good path to match element in dom tree. Maybe first bug detector is Slava Leleka (**slavaleleka**).

![obraz](https://user-images.githubusercontent.com/79422224/118942364-ee377200-b952-11eb-94d1-4fb83f69f714.png)

For fastly checking bug was started with pre releases to stable 1.26.0 and exist in latest beta 1.35.3b5.

If this is not a bug (but webmasters of few pages fail with semantic), it would be worth adding to the warning about reckless reaching for `:upward()` on Wiki.

### A specific URL where the issue occurs

`https://www.bhaskar.com/`
`http://web.archive.org/web/20210520082705/https://www.bhaskar.com/`

### Steps to Reproduce

1. open the live page or web archive of page (no recommend use archive.today backup to tests).
2. activate element picker.
3. try use this filter:

   `##.react-share__ShareButton:upward(li)`

### Expected behavior:

Hide the closest/nearest ancestor (small share button rectangle leftover) without use ideas like:

`##li > .react-share__ShareButton:upward(li)` or `##li li .react-share__ShareButton:upward(li)`

### Actual behavior:

Demo filter hide many ancestors, so generate "loop eating" articles on page.

### Your environment

* uBlock Origin version: 1.35.2 and 1.35.3b5
* Browser Name and version: Firefox 88.0.1
* Operating System and version: Windows 10 Pro 21H1 (small update for 2004/20H1)

**Comment by gorhill** [comment]
`upward()` works as intended: there is a `button[aria-label="whatsapp"]` (search this selector using the browser's own inspector) in there which matches your filter, and this button is not in an `li`, it's in a `div`, and the closest `li` is the one which wraps the whole article.
