### ISSUE TITLE
Feature request: change icon colour when nothing is blocked

### ISSUE THREAD

**Issue by pgl** [uBlockOrigin/uBlock-issues#1594]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- I tried to reproduce the issue when...
    - [-] uBO is the only extension
    - [-] uBO with default lists/settings
    - [-] using a new, unmodified browser profile
- [-] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I think it could be useful to change the colour of the extension icon to green when nothing is blocked on a page. My suggestion for a colour would be green (eg `#32CD32`).

Right now this is *sort of* visible because no numbers are added to the icon to show how many things are blocked. But it's hard to notice, and I think a green colour would be more noticeable.

(I started off with the idea to suggest a feature where the icon colour changes to a brighter red or something when *anything* is blocked, but I figured that would mean that 99% of the time it would always be that colour so not so useful.)

A side benefit of this is that it would become more obvious if there were ever any issues with filter lists being blanked out. Seeing the green icon when you are expecting something to be blocked would be more obvious. (This is not likely, but possible.)

### A specific URL where the issue occurs

https://pgl.yoyo.org/

### Steps to Reproduce

1. Visit a site where nothing is blocked
2. Extension turns green

### Expected behavior:

Extension icon turns green.

### Actual behavior:

Extension icon doesn't change.

### Your environment

* uBlock Origin version: latest
* Browser Name and version: all browsers
* Operating System and version: everything

**Comment by uBlock-user** [comment]
Currently when nothing is blocked, there's won't be a number displayed on the icon badge.

**Comment by gorhill** [comment]
Additonally, DOM elements affected by cosmetic filtering are not reported on the badge, so no number on the badge does not mean uBO is not affecting a page. This is also true for scriptlet injection and HTML filtering.

**Comment by pgl** [comment]
@uBlock-user Yep that's the case, but I think a green icon would still be interesting to have. (Noted this in the issue description btw.)

@gorhill I didn't realise that was the case.

My feature suggestion could be rephrased to: change the icon colour when no network requests are blocked. ie, the current functionality (or non-functionality) of no numbers being displayed, just making it more visually noticeable.

I think this could be interesting and potentially useful, but it's certainly not a high priority feature and I wouldn't lose (much) sleep if it wasn't accepted.

**Comment by pgl** [comment]
Good point. AdGuard's icon is green as well, so green is probably confusing. How about another colour, like blue? #1500ff wouldn't be too jarring.

Or as an alternative: change the icon to have a green / blue border?

**Comment by ryanbr** [comment]
those colour combos would be close, also if you're colourblind

**Comment by pgl** [comment]
Let me try and separate this into two parts:

1. Is it desirable to have some sort visual indication that nothing was blocked, above the current case where no numbers are added to the shield?
2. If so, what should that be?

If 1. is "no", then fair enough and we can close the issue. But if it's yes then I have more suggestions. :)

**Comment by gorhill** [comment]
I prefer to keep things as is to avoid confusion arising from such change -- in my opinion the absence of badge is a good enough visual hint for when no network requests are blocked.

**Comment by pgl** [comment]
OK!
