### ISSUE TITLE
UI - panel issue with touchscreen

### ISSUE THREAD

**Issue by corobin** [uBlockOrigin/uBlock-issues#1595]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The uB0 expanded panel does not play very nicely with touchscreens.

Based on what i can observe, it looks like it doesn't handle touch events properly and there appears to be an invisible "cursor" floating around even when it is interacted with by touch.

The most clearly visible problem is this:

When the dynamic filtering grid is long enough to need a scroll bar, it is impossible to scroll (the whole panel closes) using touch. Unless you first use a mouse to bring the focus on to the scrolling dynamic rules grid and then you can scroll with touch as long as it keeps focus.

### A specific URL where the issue occurs

https://www.nytimes.com/ (this has enough 3rd party resources to make a long list, when expanded)

### Steps to Reproduce

1. in uB0 settings - check advanced user
2. visit NYT
3. open uB0 panel
3. click "+ all" at the top of dynamic rules grid to expand it
4. use touch to try to scroll the dynamic rules grid -> at this point you *should* be able to scroll because you just clicked an element in the list
5. close the uB0 panel
6. open uB0 panel - do not click anywhere else with mouse
7. try to use touch to scroll the dynamic rules grid

### Expected behavior:

scrolls properly

### Actual behavior:

uB0 panel closes

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox 88.0.1 x64
* Operating System and version: Win10 20H2 x64

**Comment by gwarser** [comment]
Can you check if it also closes in Chrome?

**Comment by gorhill** [comment]
I don't have a touchscreen, so it's not something I will be able to reproduce and validate.

**Comment by corobin** [comment]
> One thing to keep in mind is that uBO does not close the popup panel, the browser does this. Please try to reproduce with other extensions, and if this also happens with these, report to browser devs.

you're right this appears to be a firefox problem. should have thought of that before. thanks!
