### ISSUE TITLE
ipv6 fe80::1%lo0 localhost from hosts file is marked as error line

### ISSUE THREAD

**Issue by FadeMind** [uBlockOrigin/uBlock-issues#1596]
@gorhill please add recognize as localhost (no error line)
```
fe80::1%lo0 localhost
```
![20210521-1621614113-001](https://user-images.githubusercontent.com/9846948/119169163-fd591580-ba61-11eb-99e4-09435b082106.png)

reference https://superuser.com/a/241644

**Comment by ferrybig** [comment]
The hosts file just gives back IP addresses, it does not support interface identifiers such as lo0. This i how the hosts file ha been designed

Modern computers do not list on this address anymore, it was only something that was used 10 years ago

**Comment by gorhill** [comment]
I think he is just asking for the line to not be rendered as an error.

**Comment by FadeMind** [comment]
@gorhill exactly. Regards
