### ISSUE TITLE
'Adblock for y..t...' by 'adremover' + ublock origin = no more y..t... ads on chrome

### ISSUE THREAD

**Issue by xinorez** [uBlockOrigin/uBlock-issues#1597]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by xinorez** [comment]
'Adblock for y..t...' by 'adremover' + ublock origin = no more y..t... ads on chrome

Hi, just thought I should let you know, I've found a foolproof albeit annoying way of stopping all Y.. t... ads, including preroll ads:

Download adblock
Disable ublock origin
Restart browser or reload Y.. t... video page until you see this message appear under the video player: 'cleaned by adblock for...'
Enable ublock origin
Reload video again, and if the 'cleaned by adblock' message is still there then there should be no more ads until you have to restart the browser again.

Unfortunately you will have to do this every time you restart the browser, so I hope you can figure out why this works and come up with an under the table fix for this issue, maybe a hidden setting so g corp doesn't immediately fix it on their end.

Either way, thanks very much for contributing to the internet by writing a trio of efficient adblocking add-ons. I don't have any money to contribute so I hope you'll take my thanks and maybe think about incorporating this tip, or else just keep it on the down low so g corp doesn't fix it. Thanks!

**Comment by gorhill** [comment]
Filter issues are not to be filed here, and moreover do not use this issue tracker to advertise extensions of dubious sources.

**Comment by gwarser** [comment]
It clicks on "Skip ad" button.
