### ISSUE TITLE
Proposal: Add an ability to allowlist/deactivate "#!include" lines

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1599]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I read through https://github.com/DandelionSprout/adfilt/discussions/187, it gave me a very good idea.

Two of my filterlists include more than 15 `!#include` lines, with *Dandelion Sprout's Annoyances List* slowly picking up steam recently thanks to the whole ClearURLs Chrome affair. However, as it stands, if an end-user wish to deactivate any of the ≥15 embedded files, they currently have no easy way to do so.

I propose that it should become possible with e.g. `@@!#include ExampleFileNameHere.txt`.

This should be very easy to implement for "My Filters". I do however have no immediate ideas for if anyone wants to have `@@!#include` entries to deactivate another list's `!#include`, in their own and different filterlists.

### A specific URL where the issue occurs

`https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList`

### Steps to Reproduce

1. Go to `chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#3p-filters.html`
2. Add `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList` as a custom list.
3. Go to `chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#1p-filters.html`
4. Add the entry `@@!#include AntiAwfulCommentsList.txt`
5. Click `✓ Apply Changes`
6. Go back to `3p-filters`
7. Re-sync the lists.
8. See that `AntiAwfulCommentsList.txt` is still loaded and activated as a part of `AnnoyancesList`.

### Expected behavior:

That end-users can allowlist `!#include` sub-files to prevent them from being loaded and/or active.

### Actual behavior:

End-users currently cannot allowlist `!#include` sub-files, meaning they have to choose all or nothing of the components of modern anti-annoyances lists.

### Your environment

* uBlock Origin version: 1.35.3b5
* Browser Name and version: Chrome 90.0.4430.212 x64
* Operating System and version: Windows 10 21H1

**Comment by gorhill** [comment]
Declined. Sorry but I don't see myself to keep throwing more and more code for such edge feature at the expense of quality of life.

Lists are whole, this should be understood and accepted by users.
