### ISSUE TITLE
Ublock Default Collapsed Filter Categories

### ISSUE THREAD

**Issue by CrossbowDemon** [uBlockOrigin/uBlock-issues#16]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
     This is not a filter issue
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I do not approve of the new default collapsed filter list categories as it makes it more time consuming when installing on a new browser. For example: My occupation requires me to change which computer im using every few hours while all of the computers are set up to self wipe and completely reset after every use, this change makes reinstalling my programs and this add-on every time slightly more tedious.
I suggest changing back the way filter categories are displayed to not be collapsed by default.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open uBlock dashboard
2. Go to filter lists tab
3. Be unhappy about filter categories being collapsed by default in v1.16.0

### Expected behavior:

Filter categories being expanded by default in v1.16.0

### Actual behavior:
 Filter categories being collapsed by default in v1.16.0

### Your environment

* uBlock Origin version: v1.16.0
* Browser Name and version: Firefox Nightly 61.0a1 (2018-04-24) (64-bit)
* Operating System and version: Windows 10 (64-bit) Version 1709 (OS Build 16299.15)

**Comment by gorhill** [comment]
I am going to decline this, for many reasons:

1. I do not make such decisions based **one person's very specific** needs, I do it for all mainstream users -- I consider this a common sense default for all.
1. The decision was made because the primary assumption is that uBO is installed by non-advanced users, and having a wall of filter lists presented by default is too intimidating for new users.
    - It is pointless to show all regional filters to everybody.
    - This leads to endless "hey which filter lists should I enabled?" etc. while the filter lists selected by default are the optimal ones.
    - More techies users will have no issue understanding that there are more filter lists available, and can enable more as they wish, with the understanding that more filter lists means higher likelihood of page breakage.
1. The way it worked before was flawed, and surprisingly this had not been reported: the new way fixes this completely.
    - Clicking the top header was toggling the hiding of unused filter lists
    - Clicking a subheader was collapsing all filter lists underneath, regardless of whether they were unused or not.
    - These two different behavior were incompatible: aside the annoying inconsistency, this led to annoyances such as trying to expand a subsection with no result (because the hiding of unused filter lists was still in effect).
