### ISSUE TITLE
No way to delete element on specific website

### ISSUE THREAD

**Issue by jokaorgua** [uBlockOrigin/uBlock-issues#160]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

http://www.uniongang.net/

### Steps to Reproduce

1. Go to specified website
2. Try to select an element on website with ublock origin 

### Expected behavior:

Element window is shown

### Actual behavior:

No element window. Seems to me some code on website blocks ublock's html

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Google Chrome 68.0.3440.106 
* Operating System and version: Macos 10.13

**Comment by uBlock-user** [comment]
Is Chrome translating the page for you from Russian to English ?

**Comment by uBlock-user** [comment]
Similar issues with this behaviour have been posted before, but I can't seem to find ones mimicing this behaviour unfortunately.

**Comment by uBlock-user** [comment]
Similar issue on `https://www.softgozar.com/`  Once Google Translate kicks in, element picker is messed up and stops responding to mouse clicks and the picke iframe get stuck.

**Comment by gorhill** [comment]
Unable to reproduce. Using default settings + RU AdList + Adguard Russian. Only other extension is Decentraleyes.

**Comment by uBlock-user** [comment]
Does google translate kick in on your end ?

**Comment by gorhill** [comment]
No, I translate manually only. When I translate manually that page, the element picker still work.

**Comment by uBlock-user** [comment]
> the element picker still work.

Not on my side. Once translated(auto or manual), doesn't matter, as soon as I open picker it gets messed up.

**Comment by gorhill** [comment]
Anyways, OP said there is no translation operation involved.

**Comment by Thorin-Oakenpants** [comment]
I'm not sure if this will help, but on https://thechive.com/ (any page, not just the landing page) when you right click and select block element, the picker does not even appear (not sure if this is the same issue as OP)
![chive](https://user-images.githubusercontent.com/16656956/43988047-7b14f23e-9d1c-11e8-83b9-94ac0baef271.png)

I'm not worried about it, as I can easily look at the code and craft cosmetic filters

It used to work but recently I had to allow extra scripts (not sure which ones) or you would only get about a quarter of the images, so I suspect some anti-adblock script is the cause

**Comment by Thorin-Oakenpants** [comment]
^^ whoops .. thanks ...  what was I thinking, need more :coffee:  (just got up). Mixing my uM & uBO. Site functionality is fine, the picker isn't. **Sorry, ignore my earlier comment, it's uM related, not uBO** (for the record, I block all XHR by default, and every other site I frequent I do not have an issue using the element picker, and in fact on the landing page there is no XHR .. it's not XHR related)
