### ISSUE TITLE
uBO does not block ads when the browser is opened through an external link

### ISSUE THREAD

**Issue by cubinator** [uBlockOrigin/uBlock-issues#1602]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [X] uBO is the only extension
    - [X] uBO with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When opening a completely new browser instance through an external link (e.g. clicking on a link in Telegram or opening the browser by entering the link in Windows's run dialog) it seems that uBO does not start blocking stuff immediately. Opening a YouTube video in a completely new browser instance through an external link results in YouTube playing an advertisement (most of the time). Eventually, uBO becomes active, but the ad is already rolling. After refreshing the page the ad is gone (as expected). Closing the browser and opening the same link again to launch yet another completely new browser instance lets YouTube play an ad again.

The issue does not occur when opening an external link to an already open browser instance.

(tested with uBO 1.32.2 in Google Chrome 90.0.4430.212 on Windows 10 v2004 build 19041.985 x86_64 and uBO 1.32.2 in Firefox 86.0 on Linux Arch 5.11.4-arch1-1 x86_64)

Since this issue is about something that uBO does *not* do, I cannot actually test whether or not this issue persists when uBO is disabled/uninstalled wholly, so I am not sure whether or not to tick the unticked box above.

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=TUWMaK5xvX4

### Steps to Reproduce

1. Make sure your browser doesn't clear cookies when closed (because otherwise opening a YouTube link will lead you straight into a cookie prompt instead of to the video).
2. Make sure uBO is active when the browser starts and is configured to block YouTube ads.
3. Have the URL above (or any other YouTube video URL) in your clipboard.
4. Close all browser instances.
5. Open a browser directly with the URL, e.g. by
   1. pasting that URL into Windows's run diaglog (Win+R), or
   2. running the browser from the command line with the URL as its argument.
6. Notice the ad playing, wasting all your precious time.
7. Refresh the page.
8. Notice that no ad is playing.

### Expected behavior:

When uBO is configured to block ads, it should have blocked the ad that was playing in step 6.

### Actual behavior:

There is an ad playing after step 5.

### Your environment

* uBlock Origin version: 1.32.2
* Browser Name and version: Google Chrome 90.0.4430.212
* Operating System and version: Windows 10 v2004 build 19041.985 x86_64

**Comment by llacb47** [comment]
Browser issue.

**Comment by cubinator** [comment]
Well, probably, but can it be circumvented? Can extensions hold off loading a page until they themselves are loaded? Can uBO remove ads that are already playing?

**Comment by uBlock-user** [comment]
> Can extensions hold off loading a page until they themselves are loaded

https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#suspendtabsuntilready

**Comment by cubinator** [comment]
Ads still appear even when activating this setting.

**Comment by uBlock-user** [comment]
> Disclaimer: In Chromium based browsers, even with this setting enabled, it's impossible for uBO to guarantee with 100% certainty that everything will be properly blocked when the browser is launched. This is a by-design browser issue -- do not open an issue on uBO issue tracker about this.

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch>, Chromium-based browsers limitation.

**Comment by cubinator** [comment]
Well, just read the same thing in the docs... Thank you anyway for your time :)

**Comment by uBlock-user** [comment]
Avoid using Chromium/Chromium based browsers if this is really important to you.
