### ISSUE TITLE
Style injection does not allow escaped characters.

### ISSUE THREAD

**Issue by enzanki-ars** [uBlockOrigin/uBlock-issues#1605]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [X] uBO is the only extension
    - [X] uBO with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On a specific site where passwords are securely stored, the fonts are not great to tell the difference between zeros and Capital Os for example.  And while I could install a font and use the uBlock filtering rules to improve it, the more cross platform and colaborative way I was looking at using was the existing uBlock Cosmetic Filters.

Using the url below as an example, I can make the following work:

```
fiddle.jshell.net#$#.pw::after {display: block !important; content: "Key: 0=Zero O=Captial O 1=One l=Lower L"; font-family: monospace !important; font-weight: 500 !important; white-space: pre !important;}
fiddle.jshell.net#$#.pw {font-family: monospace !important; font-weight: 500 !important;}
```

But, if I were to clean up the display for the smaller space that the password display is normally given by including CSS character escapes like `\A` for a new line, uBlock will not parse the rule, for example the following:

```
fiddle.jshell.net#$#.pw::after {content: "\a\aKey: \a \20 0=Zero\a \20 O=Captial O\a\a \20 1=One\a \20 l=Lower L\a"; font-family: monospace !important; font-weight: 500 !important; white-space: pre !important;}
fiddle.jshell.net#$#.pw {font-family: monospace !important; font-weight: 500 !important;}
```

### A specific URL where the issue occurs

https://jsfiddle.net/enzanki_ars/ue65jpfk/

### Steps to Reproduce

1. add the following custom filter:
2. 
```
fiddle.jshell.net#$#.pw::after {content: "\a\aKey: \a \20 0=Zero\a \20 O=Captial O\a\a \20 1=One\a \20 l=Lower L\a"; font-family: monospace !important; font-weight: 500 !important; white-space: pre !important;}
fiddle.jshell.net#$#.pw {font-family: monospace !important; font-weight: 500 !important;}
```
3. Visit https://jsfiddle.net/enzanki_ars/ue65jpfk/

### Expected behavior:

The filter rule is parsed and the `.pw::after` rule is applied, allowing for new lines in the custom content.

### Actual behavior:

The filter rule is not parsed and the `.pw::after` rule is not applied displaying no custom elements.

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)
* Operating System and version: Windows 10 21H1 Build 19043.1023

**Comment by gorhill** [comment]
By design, see <https://github.com/uBlockOrigin/uBlock-issues/issues/668>. Backslashes characters are not allowed anywhere in a style value, and uBO correctly reports the filter as being invalid.
