### ISSUE TITLE
Inaccurate description of which filter lists Adblock Plus has enabled by default

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uBlock-issues#1607]
https://github.com/IThinkIAmCool/uBlock/commit/2b160b4b1c92992ed9f61aa84478b77ea8a176fb makes it more accurate in my opinion.

**Comment by gorhill** [comment]
Thanks, I pulled your change with <https://github.com/gorhill/uBlock/commit/2b160b4b1c92992ed9f61aa84478b77ea8a176fb>.
