### ISSUE TITLE
Block element no longer working with Chrome 91 & Gmail

### ISSUE THREAD

**Issue by orschiro** [uBlockOrigin/uBlock-issues#1609]
I select "Block element" from the context menu but nothing happens. 

Still works on other pages, just not Gmail.

Anyone can replicate?

**Comment by orschiro** [comment]
Can you please let me know why you closed it?

I completely reinstalled ublock but it's still not working.

**Comment by uBlock-user** [comment]
Reset to default settings and try again.

**Comment by orschiro** [comment]
It had to do with enabling the flags "Temporarily unexpire M89 flags." and "Temporarily unexpire M90 flags."

**Comment by gorhill** [comment]
> Can you please let me know why you closed it?

The template you ignored and deleted contains this text near the top:

> Do NOT delete this template or any part of it when submitting your issue -->
> [...]
> To rule out invalid issues, confirm and check each one of the checkboxes. Not doing so may result in the issue being closed as invalid with no further comment

**Comment by orschiro** [comment]
Understand thanks!

Raymond Hill ***@***.***> schrieb am Di., 1. Juni 2021, 00:26:
