### ISSUE TITLE
popup window scroll bug in Opera

### ISSUE THREAD

**Issue by RX-3200** [uBlockOrigin/uBlock-issues#161]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
**no response received: https://old.reddit.com/r/uBlockOrigin/comments/968ns6/popup_window_scroll_bug/**
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

scrollbar in popup window (onclick extension button) overlaps first column of table

### A specific URL where the issue occurs

it's UI, not URL

### Steps to Reproduce

1. install -> advancedUser
2. open some page
3. click on extension button
4. click "all"

### Expected behavior:
![38453884-0bb2ac8c-3a2b-11e8-942a-16071cc8f855](https://user-images.githubusercontent.com/2563974/44005241-20f0489a-9e79-11e8-9e79-73f90fff4b49.png)
source: https://user-images.githubusercontent.com/585534/38453884-0bb2ac8c-3a2b-11e8-942a-16071cc8f855.png

### Actual behavior:

![2018-08-10_193545](https://user-images.githubusercontent.com/2563974/44005232-db72ceaa-9e78-11e8-9e36-dba2206830db.jpg)
source: http://i63.tinypic.com/2coihl1.jpg

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Opera 54 (54.0.2952.71)
* Operating System and version: Windows 7 64-bit

**Comment by uBlock-user** [comment]
@gwarser have Opera installed ? if yes, can you reproduce ?

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/4936080e2089c584c11a057e39fd8939.png)

**Comment by gorhill** [comment]
To be clear, I do not consider this an issue with uBO. If @RX-3200 think this is a uBO issue, I will let him come up investigate on his side and come up with a solution -- I don't see this as a uBO issue.

**Comment by RX-3200** [comment]
I forgot "advancedUser" enabled !

**Comment by uBlock-user** [comment]
Did you install any custom theme on Opera ?

**Comment by RX-3200** [comment]
theme? even if it disabled - nothing changed

**Comment by uBlock-user** [comment]
Whatever customisation you made is likely the cause. Run Opera on default settings and see if it happens.

**Comment by RX-3200** [comment]
it miraculously began to work as it should
