### ISSUE TITLE
Firefox 89.0b15: Crash on Visiting Certain Websites

### ISSUE THREAD

**Issue by lyind** [uBlockOrigin/uBlock-issues#1610]
Using Firefox Developer Edition 89.0b15 (64-Bit) on Linux x86_64 (Debian bullseye):

1. Install uBlock Origin
2. Visit (just one example): https://somnomedics.de
3. Observe browser crash

If uBlock is disabled for a website, the browser won't crash loading it.

**Comment by lyind** [comment]
I considered creating an issue on bugzilla.mozilla.org but since the issue doesn't appear with uBlock disabled...

**Comment by gorhill** [comment]
uBO is HTML/CSS/JS, it's not supposed to crash the browser. Browser crashes must be brought to browser devs. Also, there is no such widespread report of uBO crashing Firefox, so something specific on your side is causing this. Send crash reports to Firefox devs and open an issue on bugzilla.

**Comment by lyind** [comment]
Created a Firefox Bugzilla issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1713797

**Comment by uBlock-user** [comment]
Works fine on Nightly.

**Comment by gorhill** [comment]
You will be asked to submit a crash report, you should do it so that the devs can start investigating right away.
