### ISSUE TITLE
Certain websites stop loading intermittently giving a number of NS_BINDING_ABORTED errors in console

### ISSUE THREAD

**Issue by gareppa** [uBlockOrigin/uBlock-issues#1614]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [X] uBO is the only extension
    - [X] uBO with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Certain websites stop loading intermittently giving a number of NS_BINDING_ABORTED errors in console

### A specific URL where the issue occurs

```
https://serializer.io
https://steamdb.info
```
[WARNING, NSFW]` https://4chan.org/g/catalog`
single threads on 4chan, especially those with lots of images

### Steps to Reproduce

1) create blank firefox profile
2) install ubo from amo with default settings
3) go to serializer.io
4) open the console, go to network sections
5) the site will not fully load about 70% of the times, and you will have NS_BINDING_ABORTED errors. It will not load certain scripts necessary to the site
6) this happens also on steamdb.info (less often) and 4chan (WARNING, NSFW, will not load images in threads/catalogs, very often)

### Observations
1) it happens when disabling all filters in ubo
2) it happens when unticking all the options from the privacy section of ubo
3) it happens also when disabling ubo
4) it happens also after uninstalling ubo
5) it does not happen with a firefox completely blank profile
Possibly related: https://help.nextcloud.com/t/nextcloud-not-loading-fotos/102524/2

### Expected behavior:

the sites load correctly

### Actual behavior:

loading resources for these websites stops, and the sites never fully load or load with missing elements (e.g. images)

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version: firefox 89.0 (64 bit)
* Operating System and version: Ubuntu 20.04.2 LTS x86_64

**Comment by gwarser** [comment]
Service worker issue? https://bugzilla.mozilla.org/show_bug.cgi?id=1673534 ?

**Comment by gareppa** [comment]
I don't think so.
I have no problem whatsoever with twitter or other websites for which I have registered serviceworkers.

**Comment by gorhill** [comment]
> it happens also after uninstalling ubo

How can that be a uBO issue?

**Comment by gorhill** [comment]
I can reproduce in a new profile on which uBO was never installed:

![b](https://user-images.githubusercontent.com/585534/120926653-cb73c000-c6ab-11eb-9995-b6be2008e62f.png)

I can reproduce when using the back button after navigating to a link and before the page was fully loaded.

Provide similar picture so that we can at least see what exactly was erroring on your side.

**Comment by gareppa** [comment]
For the first time, I had the NS_BINDING_ABORTED error on a xhr on a completely blank profile. So it seems firefox has become a little buggier lately. However, it seems this behaviour gets triggered more often with ublock origin. In my case, the problem prevents the websites to load. For example, on serializer.io I only saw the top black bar.

**Comment by gareppa** [comment]
This is the (my) problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1700703

> recent versions of Firefox Nightly have problems loading HTTPS sites hosted on/through Cloudflare; an example site that's affected for me is https://daringfireball.net/. Attempts to visit such sites either time out or proceed very slowly, often with resources such as CSS only partially loaded or not loaded at all. With mozregression, I have bisected this to changeset 76a285c237e9, "Bug 1699490 - Enable HTTP3 on Nightly and beta". Manually changing network.http.http3.enabled to 'false' on the current Nightly makes the problem go away.

This the fix: 
> Manually changing network.http.http3.enabled to 'false' on the current Nightly makes the problem go away.

A note from the bug report: 
 > uMatrix is optional but it amplifies the bug.

**Comment by gorhill** [comment]
> A note from the bug report:
> 
> > uMatrix is optional but it amplifies the bug.

Nobody in that issue confirmed this statement. The answer to that comment is:

> [Comment #5](https://bugzilla.mozilla.org/show_bug.cgi?id=1700703#c5) is probably a different issue.
> I have opened ~~[bug 1701110](https://bugzilla.mozilla.org/show_bug.cgi?id=1701110)~~.

Which is itself resolved as:

> Duplicate of bug: [1700309](https://bugzilla.mozilla.org/show_bug.cgi?id=1700309)

Which issue does not mention anywhere as being related to content blocker extensions.

**Comment by Tampa** [comment]
Using Waterfox G6.0.8 and ublock 1.56 this returned randomly on some Youtube pages. Constant reloading of the page with NS_BINDING_ABORTED in console. Tried the http3.enable false, does not help. Only way to stop page from reloading is disabling ublock on that page. Disabled all other plugins, no change.

**Comment by gorhill** [comment]
Waterfox is no officially supported. I will address issues with unsupported browsers if whoever investigate can pinpoint exactly where the issue is in uBO's source code and that the fix does not involve specific code path to accommodate only Waterfox.

**Comment by Tampa** [comment]
No idea where to start looking, I'll see if I can reproduce in Firefox, but it only started happening recently. Possible change in 1.56 perhaps? I did set more filter rules a while back, so I'll try reverting the config as well.

**Comment by gwarser** [comment]
I cannot reproduce. I see a few aborted connections, but there are no issues with the page.

**Comment by Tampa** [comment]
Couldn't reproduce in Firefox, but I did notice the filter count being different. After updating filters in Waterfox the problem went away. I have auto update enabled as it is by default, but it seems some filters didn't update themselves.
