### ISSUE TITLE
still seeing ads on YouTube videos

### ISSUE THREAD

**Issue by DialexG91** [uBlockOrigin/uBlock-issues#1619]
FIX IT

**Comment by iam-py-test** [comment]
@DialexG91 you need to report this to https://github.com/uBlockOrigin/uAssets/issues/new

**Comment by iam-py-test** [comment]
> There is already an mega-issue about youtube there, this worthless issue would not be helpful over there either. @iam-py-test

Fixed

**Comment by gorhill** [comment]
Possibly a good chunk of those Youtube issues are caused by the Chromium regression.

**Comment by iam-py-test** [comment]
> Possibly a good chunk of those Youtube issues are caused by the Chromium regression.

Maybe people should be asked to test in Firefox before reporting.
I tried visiting YouTube in Chromium & got no ads. (idk why?)
