### ISSUE TITLE
Element picker mishandles identifiers with backslashes

### ISSUE THREAD

**Issue by eyalroz** [uBlockOrigin/uBlock-issues#162]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This is an issue I'm experiencing with websites containing elements whose IDs have backslashes in them, in particular backslashes before periods (`\.`). When I try to block such an element by right-clicking it and selecting "Block Element", I get [the dialog in this partial screenshot](https://i.imgur.com/8aqtciw.png):

1. The text in the text bog is not the full ID - only up to the first backslash
2. Clicking the full ID in the list below the text box does not produce the full ID in the textbox - again, just up to the backslash

The ID in the example in the screenshot, with its rule prefix, is `###new-haaretz\.co\.il\.ghost\.inread\.2.xxvert__content--c.h-mb`.

### A specific URL where the issue occurs

As you may have guessed from the element ID, this issue manifests on the website haaretz.co.il . But - you probably won't see it, since the site has a pay-wall and this happens on the for-pay pages. Also, it's a Hebrew-language website. Still, here is a (inaccessible without being subscribed) URL in which the bug manifests: https://www.haaretz.co.il/opinions/.premium-1.6366330

### Steps to Reproduce

1. Get subscription credentials for haaretz.co.il (I can provide them temporarily)
2. Visit the specified URL
3. Try to block one of the ads that show up between consecutive paragraphs of the main text column (they have a small texual header, "--פרסומת--", which means "advertisement" in Hebrew.
4. Watch how the Element Picker dialog behaves.

### Expected behavior:

The text box will show the entire element ID, with backslashes.

### Actual behavior:

The text box will show the ID up to the first backslash.

### Your environment

* uBlock Origin version: 1.16.14
* Firefox ESR 52.9.0
* Devuan ASCII 2.0 (basically it's Debian Stretch without systemd)

PS - Once this is resolved, I hope to be able to define filters matching prefixes of such IDs; but that's beyond the scope of this issue.

**Comment by uBlock-user** [comment]
Reproducible on Chromium too.

**Comment by gwarser** [comment]
<div id="foo\.bar">test div with foo\.bar id</div>
