### ISSUE TITLE
Bizarre perf drain when ajaxing in 90,000 DOM nodes in a react component

### ISSUE THREAD

**Issue by jhudsoncedaron** [uBlockOrigin/uBlock-issues#1620]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [X] uBO is the only extension
    - [X] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile - impossible for ADA reasons
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

http://localhost:4987/

I am one of the developer of the web application in question; but I face a quandary. The web application is not public facing so direct reproduction off a URL isn't going to happen. The issue currently resists bisection; the code that ajaxes in the same 90,000 DOM nodes when running outside of the react component on its own page does not reproduce it. The time to assign to .innerHTML the string containing 90,000 DOM nodes going from less than one second to 13 seconds but only within a react component for some reason. Hoisting the assign outside of react's ability to observe it with requestAnimationFrame() didn't help.

The problem also disappears simply by checking the box that turns on Advanced Mode in UBlock origin despite me turning it on for the first time to see if there was possibly any related setting under it that might do something here.

The logger contains only the ajax request to get the content to ajax in.

What am I doing with 90,000 DOM nodes? Syntax highlighting a 1MB file.

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox 89.0 x64
* Operating System and version: Windows 10 x64

**Comment by gwarser** [comment]
Record performance profile https://profiler.firefox.com/

**Comment by gorhill** [comment]
This is in the template you filled:

**Comment by jhudsoncedaron** [comment]
Bad performance profiler (uBlock origin ON): https://share.firefox.dev/3pB1kLj
Good performance profiler (uBlock origin OFF): https://share.firefox.dev/2RDrIaG

**Comment by gorhill** [comment]
Need a profiling session that also has the extensions process and the content page process. Having the the parent process makes the profiling data useless.

**Comment by jhudsoncedaron** [comment]
Oof. Why would the profiler be that bad on the default settings? I don't know how to get what you want. I was tracing this down with the F12 profiler which showed the 13 seconds going to parsehtml.

**Comment by gorhill** [comment]
You need to use this profiler: https://profiler.firefox.com/

**Comment by jhudsoncedaron** [comment]
That is the profiler that I used to capture and upload the useless profiles already.

**Comment by gorhill** [comment]
My bad, your profiling sessions do contain the extensions and content process, I right-click the wrong place.

**Comment by gorhill** [comment]
The only uBO code I see being executed on that page represents 156 ms, out of over 21,600 ms.

It seems the call with the largest CPU usage is an access to `innerHTML` following a fetch operation it appears (uBO never access this property), and then there is a point where the content process wait for a response -- possibly as a result of the call above.

Since there is no uBO code pointing out at this undue CPU usage, did you try whether you have the same issue with other extensions?

**Comment by jhudsoncedaron** [comment]
Not sure what to look for; if I flip UBO off the problem goes away. I'll go try some dumb extension and see what happens.

**Comment by gorhill** [comment]
uBO make use of a mutation observer, I suspect this might be related to this, so I would try with another extension which also depends on installing a mutation observer -- but it's just a hunch, I might be guessing wrong. Ideally I would be able to investigate first-hand, but if I can't do this, I won't be able to be useful for this issue.

**Comment by jhudsoncedaron** [comment]
If you would like I can install an instrumented build.

**Comment by gorhill** [comment]
Since I don't see uBO's code itself being the choke point, I think Firefox developers would be interested too look at this performance issue, they are better placed than I am to understand what is going on with `innerHTML`, so I think you should open an issue with links to those profiling session at <https://bugzilla.mozilla.org/enter_bug.cgi> -- the profiling shows over 15 seconds spend in `Element.innerHTML = ...`.

**Comment by jhudsoncedaron** [comment]
I've managed to reduce the reproduction to a 5MB zip file; which is still too large and contains too much proprietary code to pass around publicly but I could in theory find a way to pass it to you privately.

**Comment by gorhill** [comment]
Best at this point is to submit the performance issue to bugzilla.

**Comment by gorhill** [comment]
We can keep it opened, but Firefox devs need to look at why so much time is spent in `innerHTML`.

**Comment by gorhill** [comment]
@jhudsoncedaron Can you see if issue is still there with [latest dev build](https://github.com/gorhill/uBlock/releases) of uBO? The change I made in uBO is to avoid the problematic code path in Firefox which has been fixed in Firefox.

**Comment by jhudsoncedaron** [comment]
Yes that fixed it thanks.
