### ISSUE TITLE
There are no element zapper or picker buttons/icons so I can't pick or zap elements

### ISSUE THREAD

**Issue by engineering1** [uBlockOrigin/uBlock-issues#1625]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [ X] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The element zapper and element picker buttons/icons are now missing from the uBO menu. The appearance of the menu also significantly changed appearance. I tried clicking everything and there are no buttons or settings that bring back the two icons. It was working just the other day. Are there any known Firefox settings that interfere with uBO element zapper and picker buttons/icons?

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Open Firefox (any version)
2. Install uBO
3. It works at first but at unpredictable times the element zapper and picker buttons/icons disappear inexplicably.

### Expected behavior:

The element zapper and picker buttons/icons should always be visible and clickable from the uBO menu.

### Actual behavior:

Nothing happened. There are no element zapper or picker buttons/icons so I can't pick or zap elements.

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version: Firefox and Firefox ESR, every version of each
* Operating System and version: Linux Mint 19 Mate 64-bit

**Comment by gorhill** [comment]
Check all the box in the template after you carefully validate the entry, you skipped:

- uBO is the only extension
- using a new, unmodified browser profile

> The appearance of the menu also significantly changed appearance

Provide a screenshot please.

**Comment by engineering1** [comment]
On Sat, 12 Jun 2021 06:34:05 -0700
Raymond Hill ***@***.***> wrote:

> Check all the box in the template after you carefully validate the
> entry, you skipped:
> 
> - uBO is the only extension
> - using a new, unmodified browser profile
> 
> > The appearance of the menu also significantly changed appearance  
> 
> Provide a screenshot please.
> 

[X] The error occurs whether or not uBO is the only extension.

[X] I'm unable to verify if a new, unmodified browser profile
fixes the problem at the moment. The Mozilla add-ons page doesn't load
so I can't install it, nor does any site load. I,e.
https://addons.mozilla.org/en-US/firefox/search/?q=ublock%20origin
results in the "Hmm. We’re having trouble finding that site." as does
https://www.google.com . I can't explain it. My modified browser
profile loads sites just fine (except for https://duckduckgo.com which
I also can't explain). I will continue trying to install uBO to a new
browser profile and let you know if I succeed.

Re-installing the plugin doesn't help at least in a modified
browser profile.

I don't have a screenshot of the original uBO menu, only the new. See
jpg attachment.

I have been experiencing this problem off and on for over a year now.
For a long time I backed up my Firefox profile because when the
buttons/icons disappeared I could get them back by restoring the
backup. Only this time, my backups didn't fix it and the change seems
to have propagated through my backup (probably accidentally when I
created a new backup not realizing the buttons/icons were missing.)

Thank you.

**Comment by llacb47** [comment]
@engineering1 there is no attachment. Use the github website and not email.

**Comment by gorhill** [comment]
> The Mozilla add-ons page doesn't load so I can't install it, nor does any site load

The add-ons page works fine for me. I am going to assume there is something wrong in your profile which is breaking your Firefox, and that the issue here is a result of this. There is no way around creating a new profile, it takes seconds using `about:profiles`.

**Comment by gorhill** [comment]
Closing as _invalid_, there are no other report of such issue and no feedback regarding using a real new profile.

**Comment by engineering1** [comment]
On Mon, 14 Jun 2021 04:46:11 -0700
Raymond Hill ***@***.***> wrote:

> Closed #1625.
> 

I wasn't able to get back to you soon enough, geez, why so impatient? I
got busy, I wasn't done troubleshooting it. Please re-open ticket. I will get back later. Thanks.

**Comment by gorhill** [comment]
I will re-open when you make the case there is an issue with uBO -- what you describe point out at a larger issue specific to you on your side.

**Comment by engineering1** [comment]
On Mon, 14 Jun 2021 06:30:58 -0700
Raymond Hill ***@***.***> wrote:

> I will re-open when you make the case there is an issue with uBO --
> what you describe point out at a larger issue specific to you on your
> side.
> 

It took an hour but I isolated the following Firefox/ESR settings
causing uBlock origin to change appearance and lose the zapper function:

user_pref("dom.reporting.delivering.maxReports", 0);
user_pref("dom.requestIdleCallback.enabled", false);

I don't know what these options do but they were configured that way for
security reasons (ghacks.js on github, which security-enhances
prefs.js). If there is a way to get uBlock to work regardless of these
ettings I'd appreciate it. Thanks.
