### ISSUE TITLE
Countering a removeparam filter causes page-redirect problem

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1626]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Making an exception for a removeparam filter which breaks redirecting causes another issue of page-redirect (apparently only on uBO).

### A specific URL where the issue occurs

`https://toptechtalk.xyz/?utm_source=socialmedia_uUod`
(visit `http://turkdebrid.site/api1/?page=create&ads=zshort.io`)

### Steps to Reproduce

1. Add AdGuard URL Tracking filter: `https://filters.adtidy.org/extension/ublock/filters/17.txt`
2. Add 
```
@@$removeparam=utm_source,domain=toptechtalk.xyz
@@||toptechtalk.xyz/?utm_source=$removeparam=utm_source,badfilter
```
 to My filters - without this you'll be moved to homepage than the intended destination.
3. Visit `http://turkdebrid.site/api1/?page=create&ads=zshort.io`

<details>
<summary>Screenshot</summary>

![toptechtalk](https://user-images.githubusercontent.com/58900598/121783415-78d55f00-cbe9-11eb-8cae-1a2e69e4006a.png)

</details>

### Expected behavior:

You'll be redirected to `https://toptechtalk.xyz/is-it-profitable-to-start-an-e-commerce-business-and-earn-money/`. This occurs if you unsubscribe AdGuard URL Tracking filter. There's no other parameter involved as far as the logs go.

### Actual behavior:

Described

### Your environment

* uBlock Origin version: v1.35.2/v1.35.3rc1
* Browser Name and version: Firefox 89.0
* Operating System and version: Windows 10

**Comment by Yuki2718** [comment]
I added exception to AdGuard URL Tracking filter so please also add `@@||toptechtalk.xyz/?utm_source=$removeparam=utm_source,badfilter`

**Comment by gwarser** [comment]
Just these two will be enough?

```
$removeparam=utm_source
@@$removeparam=utm_source,domain=toptechtalk.xyz
```

**Comment by Yuki2718** [comment]
> Just these two will be enough?
> 

Yup, reproduced.

**Comment by gorhill** [comment]
Looks like Firefox does not validate whether the returned `redirectUrl` is the same as the current URL, while Chromium does. So the fix is for uBO to do that check.

**Comment by gwarser** [comment]
Exception is not working at all now?
