### ISSUE TITLE
Ublock cause firefox UI hang on a page with very high request freqency.

### ISSUE THREAD

**Issue by mmis1000** [uBlockOrigin/uBlock-issues#1627]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using the ublock on a page with ultra high request frequency.
It cause the Firefox to randomly hang completely.
(The firefox is somewhat half broken. Even press f12 in page  to open devtool does nothing.)

The global browser debugger indicates the tab is dead completely and not respond to devtool request. 

It seems only with block count enabled.
But because this bug happened randomly at first place and I can't really isolate it, I did not put it in the title.

This is probably a webextension api bug instead of bug of extension it self because it only happens on Firefox.
But because it only happens with this extension so far, I decide to report it here.

### A specific URL where the issue occurs
`https://www.youtube.com/watch?v=ZoO6WijuXB4`
Seems only happens with live stream. 
This is already a archive, so you no longer able to reproduce the problem with it.

Mainly happened on live karaoke with chat and custom emoji enabled. (Due to a lot of glow stick emojis)

### Steps to Reproduce

1. Open a youtube live stream with a lot of message with custom emoji spammed.
2. Watch for a while (usually happens in about 10 or 20 minutes)

### Expected behavior:

Stream plays normally

### Actual behavior:

Stream stopped, tab not respond to f12 for open devtool normally
(Devtool in the image is the browser global console instead of page console)
![Tab hanged and can't even open devtool normally](https://user-images.githubusercontent.com/2993977/121783302-5ab73100-cbe0-11eb-9de8-6d44d6fef846.png)

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version: Firefox Nightly 91.0a1（2021-06-12）
* Operating System and version: Windows 10 21H1, Mac catalina

**Comment by uBlock-user** [comment]
>Even press f12 in page to open devtool does nothing

Nightly issue, uBO is HTML/CSS/JS, cannot cause a tab to get hanged or dead, try reproducing on Firefox 89.

**Comment by gorhill** [comment]
> Mainly happened on live karaoke with chat

There is an opened issue in bugzilla for Youtube's chat feature, it's not a uBO issue.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1533815 ?

**Comment by gorhill** [comment]
Yes, I tracked it back and was about to post it here.
