### ISSUE TITLE
Filters seem not to be using on Chrome extension on Brave

### ISSUE THREAD

**Issue by TheGam1ngWizard** [uBlockOrigin/uBlock-issues#1628]
### Prerequisites

- [YES] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [YES] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [YES] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [YES] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [YES] uBO is the only extension
    - [YES] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [YES] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Initially amazon prime video commercials were playing that were previously blocked. Then I went to update my filters, got the 'A network error prevented the resource from being updated.' error. I then used 'ctrl' purge to clear all of my filters list thinking it might be a cache issue. It now seems other people are reporting similar filter issues on the crome web store.
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
![image](https://user-images.githubusercontent.com/55005148/121794380-94366f00-cbd5-11eb-918e-3a47abdcadd7.png)

### A specific URL where the issue occurs
`https://www.amazon.com/The-Nigerian-Job/dp/B001N4RAEQ/`

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Brave 1.25.72, Chromium: 91.0.4472.101
* Operating System and version: Windows 10 20H2

**Comment by jensengillett** [comment]
Can confirm there are issues on Youtube as well, ads are now showing up on the homepage (though not during video playback). Had no issue refreshing my filters unlike OP. Tested both the latest development build (1.35.3rc1) and mainline (1.35.2) on mainline Chrome (91.0.4472.101) to the same effect.

**Comment by uBlock-user** [comment]
> Then I went to update my filters, got the 'A network error prevented the resource from being updated.' error.

Try updating now,

**Comment by gorhill** [comment]
@jensengillett, see <https://github.com/uBlockOrigin/uBlock-issues/issues/1612>.
