### ISSUE TITLE
Is The Release 1.16.16 from 1.16.17b2 Correct?

### ISSUE THREAD

**Issue by GuardianMajor** [uBlockOrigin/uBlock-issues#163]
Apologies, this is not really an "ISSUE" per se that I can complete the template for, just wondering if the release that was posted about 6 hours ago designated 1.16.16 is versioned correctly, or am I missing something. I assumed it would not roll back but I could be wrong. Just seeking clarification.

**Comment by gwarser** [comment]
No current release is based on 1.16.15rc0

**Comment by uBlock-user** [comment]
1.16.16 is the new stable build following its predecessor version 1.16.14, 1.16.17b2 is the new dev build release following its predecessor 1.16.17b1. Different branches, different versions, not be compared.

**Comment by GuardianMajor** [comment]
Understood, I was trying to understand it better, since usually the tag -legacy identifies the different branch and I was just wondering if the numbering got mixed up as it has happened before, thank you for clarifying.

**Comment by uBlock-user** [comment]
No problem, also as an FYI - stable builds are even numbered releases, examples - 1.16.12, 1.16.14 and now 1.16.16 and so on..

**Comment by GuardianMajor** [comment]
Thank you, excellent tip, will keep that in mind.
