### ISSUE TITLE
Youtube Ads Appearing with Ublock Now

### ISSUE THREAD

**Issue by Chibi-Usa** [uBlockOrigin/uBlock-issues#1630]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
btw i did all this just to be sure, and tried in incognito and in firefox, ^^
### Description

Ublock isnt blocking ads on youtube any more, and how to fix
ignore my image uploader https://onii-chan.life-is-pa.in/uPaLyg.png
but thats how to avoid youtube ads until its patched

### A specific URL where the issue occurs

https://youtube.com

### Steps to Reproduce

1. refresh youtube
2. play a video with ads
3. if it has ads they will play most of the time

### Expected behavior:

Ads not loading

### Actual behavior:

ads loaded and played

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version:Chrome Canary, 3.0.4541.0 (Official Build) canary (64-bit) (cohort: Clang-64)
* Operating System and version: Windows 10 OS Version 2009 (Build 21390.1010) {dev build}

### to temp fix the issue
https://onii-chan.life-is-pa.in/uPaLyg.png
follow the steps in this link above ^^

**Comment by Auster-South-Anemoi** [comment]
I also got this issue on both Firefox for Android and Firefox for Ubuntu.
I didn't notice any issues with uBlock Origin on Firefox for Windows.

**Comment by stefanos82** [comment]
I have noticed a change in YouTube the past month or so.

A new message on top left corner that says "Includes paid promotion"; no matter what you do, it forces you to watch it.

![image](https://user-images.githubusercontent.com/1777466/124472458-d1da8200-dda6-11eb-915b-20077162e7cf.png)

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
