### ISSUE TITLE
Blocking remote fonts sometimes results in not loading local fonts.

### ISSUE THREAD

**Issue by dumol** [uBlockOrigin/uBlock-issues#1631]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I block remote fonts. Then use custom FontConfig rules to have more web fonts aliased to local fonts present on my system. E.g. alongside using _Liberation Sans_ for _Arial_ from default FontConfig rules, I also use _URW Gothic_ for _Century Gothic_ or _Libre Baskerville_ for _Baskerville_. More on this at https://github.com/dumol/PixelPerfect/.

I have noticed Firefox doesn't load local fonts on some sites, e.g.
  * "URW Gothic" as an alias for "Century Gothic" on https://e.foundation/about-e/.
  * "Libre Baskerville" for https://theconversation.com/cycling-is-ten-times-more-important-than-electric-cars-for-reaching-net-zero-cities-157163.

However, they are loaded on other sites. e.g. https://www.cssfontstack.com/Baskerville and https://www.cssfontstack.com/Century-Gothic.

This seems to be caused by blocking remote fonts through uBlock Origin. Interestingly, it only affects Firefox, not Chromium, where blocking remote fonts through this extension works just fine.

### A specific URL where the issue occurs

https://e.foundation/about-e/

### Steps to Reproduce

1. Install the FontConfig rules from https://github.com/dumol/PixelPerfect/
2. Block remote fonts in uBlock Origin.
3. Visit https://e.foundation/about-e/

### Expected behavior:

Local fonts _URW Gothic_ should be loaded instead of the blocked remote font _Century Gothic_.

### Actual behavior:

The default browser font is loaded instead, in our case _Liberation Serif_ the default serif font in the PixelPerfect setup. The outlook of the site is dramatically changed.

### Your environment

* uBlock Origin version: v1.35.2
* Browser Name and version: Firefox 89.0
* Operating System and version: Devuan Linux 4 (based on Debian Linux 11).

**Comment by gorhill** [comment]
What does the logger report regarding font resources?

**Comment by dumol** [comment]
Grepping the logger report for `font` on Firefox returns:
```
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.ttf` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.woff` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.woff2` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.ttf` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.ttf` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.11.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.ttf` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.11.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.11.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.ttf` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.ttf` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | inline-font | `https://e.foundation/` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/uploads/2019/11/century_gothic.ttf` |
| +2 |  |  | e.foundation | 3 | css | `https://cdn.linearicons.com/free/1.0.0/icon-font.min.css?ver=5.7.2` |
| +2 |  |  | e.foundation | 1 | script | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/js/v4-shims.min.js?ver=3.2.4` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/brands.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/v4-shims.min.css?ver=3.2.4` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/all.min.css?ver=3.2.4` |
| +2 |  |  | e.foundation | 3 | css | `https://cdn.linearicons.com/free/1.0.0/icon-font.min.css?ver=5.7.2` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/font-awesome.min.css?ver=1.1.3` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fontawesome.css?ver=5.7.2` |
| +2 | no-remote-fonts: * true | -- | e.foundation | 1 | inline-font | `https://e.foundation/` |
```
Same thing for Chromium, where things work as expected:
```
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | inline-font | `https://e.foundation/` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.ttf` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.11.0` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.ttf` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.woff` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.11.0` |
| +4 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-brands-400.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.11.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fonts/fa-solid-900.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.ttf` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.ttf?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.ttf` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-brands-400.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/eicons/fonts/eicons.woff2?5.10.0` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff2` |
| +3 | no-remote-fonts: * true | -- | e.foundation | 1 | font | `https://e.foundation/wp-content/uploads/2019/11/century_gothic.ttf` |
| +2 |  |  | e.foundation | 1 | script | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/js/v4-shims.min.js?ver=3.2.4` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/solid.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/brands.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.1` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/v4-shims.min.css?ver=3.2.4` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/elementor/assets/lib/font-awesome/css/all.min.css?ver=3.2.4` |
| +2 |  |  | e.foundation | 3 | css | `https://cdn.linearicons.com/free/1.0.0/icon-font.min.css?ver=5.7.2` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/font-awesome.min.css?ver=1.1.3` |
| +2 |  |  | e.foundation | 1 | css | `https://e.foundation/wp-content/plugins/ak-menu-icons/css/fontawesome.css?ver=5.7.2` |
| +2 | no-remote-fonts: * true | -- | e.foundation | 1 | inline-font | `https://e.foundation/` |
```

**Comment by gorhill** [comment]
So as per logger output, I do see uBO doing what is expected from it, i.e. blocking remote fonts (did you bypass browser cache when reloading the page by pressing shift key when clicking reload button?)

**Comment by dumol** [comment]
All remote fonts should be blocked. Problem is the local aliased fonts are not loaded when uBlock Origin is active and blocking remote fonts.

Which does not happen when blocking remote fonts with `gfx.downloadable_fonts.enabled` set as `false` in `about:config`. Also does not happen when blocking remote fonts with uBlock Origin in Chromium.

Hopefully it's a bit more clear now. Thanks for the patience!

**Comment by gorhill** [comment]
I would like if you could investigate exactly which font resource(s) is not being loaded because of the no-remote-fonts switch -- the repro steps basically require that I modify my OS environment, which is something I rather not do. So far from what I see in the logger, there is nothing unexpected if using the no-remote-fonts switch.

Of course uBO being an extension can't be expected to behave just at it would when using a browser setting such as `gfx.downloadable_fonts.enabled`.

I want to see from the logger or the browser console what specifically is happening which you think is an issue in uBO's code. All I see now is a logger output which is completely expected.

**Comment by dumol** [comment]
I'm willing to work towards this, but some of the above exceeds my abilities, sorry! I can however rewrite the repro steps to only require one font and one FontConfig rule in a user's home directory. Would that help?

Anyway, installing the whole PixelPerfect setup from my repo will pollute the same sub-dirs. If you don't have custom rules in `~/.config/fontconfig` and custom fonts in `~/.local/share/fonts`, you can try it and then just remove these sub-dirs once done. Nothing else is changed in your OS environment.

As far as I can tell, it could well be that there's nothing out of the ordinary with the filtering of remote resources in this case. Also, it's possible that this is not really an uBlock Origin issue, but a Firefox bug that is triggered by your extension's blocking of remote fonts.

**Comment by uBlock-user** [comment]
Font blocking is done by passing a CSP to the browser, CSP only allows sources that are defined in the policy by uBO fyi

**Comment by gorhill** [comment]
> done by passing a CSP

Only for inline fonts, they are blocked through webRequest listener otherwise.

**Comment by gorhill** [comment]
> possible that this is not really an uBlock Origin issue

This what the logger shows. I don't know the technical details of font aliasing, but from what I see in the logger, this aliasing is beyond uBO's reach.

**Comment by uBlock-user** [comment]
OP shouldn't use the no-fonts switch but rather `*$3p,font` or `*$font`

**Comment by gorhill** [comment]
> OP shouldn't use the no-fonts switch but rather *$3p,font or *$font

Why? He said it works in Chromium but not Firefox, yet uBO does exactly the same in both browser.

It's probably a case where the _aliasing_ is beyond uBO's scope as an extension, uBO has no knowledge of file system, and thus changes in the file system.

**Comment by dumol** [comment]
Thanks @uBlock-user!  I've tried `*$3p,font` in _My filters_, but it doesn't work for me. `*$font` does, but exhibits the same problem.

**Comment by dumol** [comment]
Yes, it's very curious that it works fine with Chromium, but not with Firefox. That's why at first I thought it's a Firefox bug. Then I realized it works as expected in Firefox too if the fonts are blocked with `gfx.downloadable_fonts.enabled` set as `false`.

The aliasing is indeed beyond the scope of the extension, but this is true for both browsers. So I don't know… Is this a Firefox bug in the end? Then why things work as expected with `gfx.downloadable_fonts.enabled` set as `false`?

**Comment by uBlock-user** [comment]
> Why? 

Because it will block local fonts too ? Isn't that the issue here all along ?

**Comment by gorhill** [comment]
> Because it will block local fonts too ?

Inline fonts are not "local", they are delivered by the remote server.

**Comment by gorhill** [comment]
> Is this a Firefox bug in the end?

Or by design behavior. You will have to file an issue with Firefox devs if you want a different behavior, uBO is not in a position to honor your changes in the OS.

**Comment by dumol** [comment]
Thanks! There is nothing special in my changes, though. This would apply to upstream FontConfig rules present by default in `/etc` too, e.g. for using _Liberation Sans_ when _Arial_ is requested but not present.
