### ISSUE TITLE
uBlock Origin goes to crash when browse the web normally

### ISSUE THREAD

**Issue by leic4u** [uBlockOrigin/uBlock-issues#1632]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I logged in to my google account on Chrome on a new device and synced my account settings , then the uBlock Origin went to crash when I browsed the web .
So I logged out of my account on chrome and logged in again, and then chose not to sync my extensions , only reinstalled Proxy SwitchyOmega and uBlock Origin , uBlock Origin also started to crash when I browsed the web .

### A specific URL where the issue occurs

everywhere .
example : https://translate.google.com/

### Steps to Reproduce

1. open a website
2. browse normally
3. uBlock Origin go to crash

### Expected behavior:

dont crash

### Actual behavior:

alwasy go to crash

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Chrome 91.0.4472.106 (64bit)
* Operating System and version: Windows 10 home 20H2 19042.1055

**Comment by gorhill** [comment]
Crashes are to be reported to [browser devs](https://bugs.chromium.org/p/chromium/issues/list), uBO is HTML/CSS/JS, it's not supposed to crash the same way a web page is not supposed to crash.
