### ISSUE TITLE
devmode not being detected

### ISSUE THREAD

**Issue by OvermindDL1** [uBlockOrigin/uBlock-issues#1633]
### Prerequisites

- [-] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [-] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [-] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [-] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [-] uBO is the only extension
    - [-] uBO with default lists/settings
    - [-] using a new, unmodified browser profile
- [-] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This is an incredibly difficult 'template' to navigate on non-pc interfaces, this is not at all user friendly...

In short, on such non-pc interfaces the extension popup is extremely **white**, painfully so when nothing else on this system is.  Found an in-dev option to set the theme on the wiki to dark (though why it doesn't pick it up from the system settings is a bit wrong when firefox does just fine...) however that option doesn't work, seemingly because of https://github.com/gorhill/uBlock/commit/9aef41738b66b25028403d8e0f25f7fb4deafb0e however I am still running a development build of firefox (90.0b1 specifically at this moment) yet that does not seem to be what it's attempting to detect for (in addition that commit makes no sense, that string does not appear in firefox versions).

Trying to find a version of this extension in the firefox extension website that is marked as such a version does not seem to exist in the versions list, and I am not able to compile my own release to do so on such a non-pc device as I am unable to supply it with extensions from non-official sources.

How can I enable even the incomplete version of, a dark view mode of uBlock Origin for accessibility reasons.  When the full screen white interface (extension popups appear as full screen on this non-pc device) pops up it causes literal pain to certain users here in addition to it being too bright white for them to even be able to see it to navigate it, thus making uBlock Origin extremely accessibility hostile yet still a necessary extension due to the state of the internet as it currently is.  Preventing a necessary accessibility change for the reason of some users who are incapable of reading is extremely accessibility hostile and I'm very curious as to why that is the choice?  Going through the effort to set `uiTheme` to false after finding that and the disclaimer in the wiki should work, not make it so the accessibility users keep yelling at me...

### A specific URL where the issue occurs

moz-extension://c656b6c7-5c7c-453a-950e-ea433e7817c4/dashboard.html#settings.html
But in the popup as well.

### Steps to Reproduce

1. Install uBlock Origin.
2. Tap the extension button (or click if on a PC) on the toolbar.
3. Allow certain accessibility users to suddenly yell at you with various colourful metaphors..

### Expected behavior:

For it to not be accessibility hostile by actually obeying the systems dark mode, even if incomplete.

### Actual behavior:

I get yelled at because uBlock Origin locked the accessibility feature behind a non-release version that can't be installed on certain non-pc terminals.

### Your environment

* uBlock Origin version:1.35.2
* Browser Name and version:  Firefox 90.0b1
* Operating System and version:  ...I think some variant of linux running in a micro-client that's very locked down, think it's based on debian, but it doesn't matter, firefox *is* the only GUI on it and the CLI is inaccessible.

**Comment by uBlock-user** [comment]
> Going through the effort to set uiTheme to false after finding that and the disclaimer in the wiki should work, not make it so the accessibility users keep yelling at me...

Read -- https://github.com/gorhill/uBlock/wiki/Advanced-settings#uitheme, it's `dark` not `false`.

**Comment by gorhill** [comment]
Also, it's the [dev build of uBO](https://github.com/gorhill/uBlock/releases), not the dev build of the browser.

**Comment by gorhill** [comment]
Locking thread because given the tone in opening comment -- all there is to say has been said.
