### ISSUE TITLE
> Going through the effort to set uiTheme to false after finding that and the disclaimer in the wiki should work, not make it so the accessibility users keep yelling at me...

### ISSUE THREAD

**Issue by OvermindDL1** [uBlockOrigin/uBlock-issues#1634]
> Read -- https://github.com/gorhill/uBlock/wiki/Advanced-settings#uitheme, it's `dark` not `false`.

_Originally posted by @uBlock-user in https://github.com/uBlockOrigin/uBlock-issues/issues/1633#issuecomment-861657899_

Apologies, a mistype, it was set to `dark`, but there was still no change in the UI.

The linked dev build of uBO is unable to be installed as there is no way to download a file to that system, only able to install extensions from the official firefox locations, how else would a (partial) dark mode be able to be enabled?

**Comment by OvermindDL1** [comment]
Unsure how a new issue got created as I chose a reply?  Apologies for this, I don't seem to be able to continue replying in the original thread as my github issue interface is messing in a way I've not encountered before...  It is still working elsewhere however...

**Comment by uBlock-user** [comment]
> For development purposes only! DO NOT create issues about this feature!

It says right there ^, do not open another issue about this.

**Comment by uBlock-user** [comment]
> The linked dev build of uBO is unable to be installed as there is no way to download a file to that system

Install the file which has contains "signed" in the xpi file name. 

For questions - https://www.reddit.com/r/uBlockOrigin/
