### ISSUE TITLE
Ads on Twitch and Youtube are no longer getting blocked

### ISSUE THREAD

**Issue by Avnsx** [uBlockOrigin/uBlock-issues#1635]
Chrome version 91.0.4472.106 on windows 10, with newest version of the chrome extension.

Websites: youtube.com, twitch.tv

Issue: Ads getting displayed before and during videos & livestreams. Happens since around 2 weeks now, very bothering

**Comment by llacb47** [comment]
It's very bothering that you filed an issue in the wrong place, didn't fill the template, and made no effort to look for existing posts/issues about twitch ads.

**Comment by Avnsx** [comment]
> It's very bothering that you filed an issue in the wrong place, didn't fill the template, and made no effort to look for existing posts/issues about twitch ads.

It's very bothering that I am forced to open a issue in a community based issue tracker, that the developers of uBlock are not even going to read, which makes it basically a waste of time and for that waste of time i'm asked to fill a novel of bug report template. 

You should be pleased, that I even took the time to write a small Summary of a widely spread issue, that is bothering hundred thousands of uBlock users.

So how about you look at it from my perspective?

**Comment by Avnsx** [comment]
> It's very bothering that you filed an issue in the wrong place, didn't fill the template, and made no effort to look for existing posts/issues about twitch ads.

Here just for the sake of it, this really shows how much a waste of time this community based issue tracker is:

https://github.com/uBlockOrigin/uBlock-issues/issues/1407
https://github.com/uBlockOrigin/uBlock-issues/issues/1351
https://github.com/uBlockOrigin/uBlock-issues/issues/1360
https://github.com/uBlockOrigin/uBlock-issues/issues/469
https://github.com/uBlockOrigin/uBlock-issues/issues/465
https://github.com/uBlockOrigin/uBlock-issues/issues/320

and a fuck ton more, these people filled the novel of a bug report and still didn't get anything out of it, I just outsmarted everyone in first place by not filling it; because I was expecting no one to care in first place, until your keyboard warrior popped up on my issue ticket

**Comment by uBlock-user** [comment]
> So how about you look at it from my perspective?

This isn't about your perspective, this is about what rules have been set. You removed the template which clarifies where to post. You being unable to follow instructions is your problem.
