### ISSUE TITLE
Firefox (OSX) wont apply uBlock list until opening the logger 

### ISSUE THREAD

**Issue by lukanz** [uBlockOrigin/uBlock-issues#1636]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since Firefox 89 (macOS Catalina) ublock (1.35.2) wont apply any list till opening the logger and refresh the page from the logger this only happening on osx there are no issues on windows

### A specific URL where the issue occurs

[everywhere]

### Steps to Reproduce

1. [Watch the gif ]

### Actual behavior:

https://i.ibb.co/wW8L3qS/firefox.gif

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox 89+
* Operating System and version: macOS Catalina

**Comment by uBlock-user** [comment]
Works once and then doesn't on another refresh...sounds like race condition. Need to use different filters

**Comment by gorhill** [comment]
I don't have OSX, so I can't investigate, someone else will have to contribute investigation work.

**Comment by gorhill** [comment]
Is it really because of the logger that it works, or is it just because the content of the page is occluded and not visible -- the logger should really have no effect in whether a filter is applied or not.

**Comment by lukanz** [comment]
Ok it seems to be a bug on Firefox's side!

Same happened with Adguard : https://i.ibb.co/23svKVF/Firefox-2.gif

**Comment by gorhill** [comment]
If you open the logger, without occluding the browser window, then press the Home button, what does the logger show? I wonder whether the Home button causes the context to be wrong.

**Comment by lukanz** [comment]
ok i tried the latest Firefox 90 beta 09 and the same issue ...it seems that Firefox stops loading some filters 


https://i.ibb.co/BV50JS1/firefox-03.gif

**Comment by uBlock-user** [comment]
Is the results consistent if you don't open the logger ?

**Comment by lukanz** [comment]
yes without opening the logger and refresh the site from there i get always the same result (before you continue .... screen)

**Comment by uBlock-user** [comment]
> refreshing the site from there

You're not clicking the refresh button which is located besides the Home button, you're clicking the Home button, which is not the same as clicking the refresh button or doing CMD + F5 .

**Comment by lukanz** [comment]
this was the first video i uploaded!

https://i.ibb.co/wW8L3qS/firefox.gif

**Comment by gorhill** [comment]
Does the issue occur if you click [this link](https://www.google.com) instead of that Home button?

**Comment by lukanz** [comment]
now something weird happened if i open the link in the same tab i get the same result "before you continue..." but if i open the link in a new tab the rules will be applied


https://i.ibb.co/HY86yyF/firefox-04.gif

**Comment by uBlock-user** [comment]
Does this kinds of issue persists everywhere else or is it isolated to google only ?

**Comment by krystian3w** [comment]
This is not race condition due Google extreamly optimize search page?

Maybe for Firefox help html filtering:

```
www.google.*##^script:has-text(consentCookiePayload)
```

if nobody reported breakage (Poland users no detected breakge or don't tried report into `MajkiIT`/"`PolishFiltersTeam/PolishSocialCookiesFiltersDev/`" repos).

**Comment by lukanz** [comment]
> This is not race condition due Google extreamly optimize search page?
> 
> Maybe for Firefox help html filtering:
> 
> ```
> www.google.*##^script:has-text(consentCookiePayload)
> ```
> 
> if nobody reported breakage (Poland users no detected breakge or don't tried report into `MajkiIT`/"`PolishFiltersTeam/PolishSocialCookiesFiltersDev/`" repos).

this rules has solved the issue ...thx

**Comment by krystian3w** [comment]
Hi I have new method to reproduce this in Firefox 91.0.1 on Windows 7:

1. open `about:config` and close alert
2. Into search bar on that page put this: `dom.block_download_insecure`
3. Drag and drop wrote text from into title tab "Advanced Preferences"
4. Page open google without enforce any html filters

Bug looks like old with omit html filtering if page use HTTP 3xx redirect.
