### ISSUE TITLE
uBlock doesn't work on Verge till cookie consent is accepted

### ISSUE THREAD

**Issue by specter78** [uBlockOrigin/uBlock-issues#1639]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When opening `https://www.theverge.com`, cookie consent popup is shown. Until this popup is accepted, uBlock doesn't work.

I also noted that this consent popup **cannot be blocked** and none of the links on the webpage can be clicked.

### A specific URL where the issue occurs

`https://www.theverge.com/2021/6/15/22535123/microsoft-windows-11-leak-screenshots-start-menu`

### Steps to Reproduce

Given in description

### Expected behavior:

uBlock should work without needing to accept cookie consent.

### Actual behavior:

uBlock doesn't work on Verge till cookie consent is accepted

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firfox 89
* Operating System and version: macOS 11.4

**Comment by uBlock-user** [comment]
Disable any Annoyances list you have enabled, and test on default settings only.

`theverge.com###privacy-consent` works fine.

**Comment by uBlock-user** [comment]
> Operating System and version: macOS 11.4

Does this happen on any other environment like Windows or Linux ?

**Comment by specter78** [comment]
> Disable any Annoyances list you have enabled, and test on default settings only.
> theverge.com###privacy-consent works fine on default lists.

Tried this. Removes the consent popup. But still cannot click on any link on webpage.

 > Does this happen on any other environment like Windows or Linux ?

Don't know.

**Comment by uBlock-user** [comment]
> Have to accept it to interact with website.

Side effect of blocking GDPR notices, this is why we don't block GDPR popups in uBlock Annoyances list.

**Comment by gorhill** [comment]
> Until this popup is accepted, uBlock doesn't work.

So uBO **does** work, it's the site which does not work if you don't accept cookies.

**Comment by specter78** [comment]
> So uBO does work, it's the site which does not work if you don't accept cookies.

Fair enough. The reason why I made the said statement is because the counter on uBO icon increased only after accepting consent popup.

**Comment by gorhill** [comment]
If you go to <http://example.com/>, there is no counter, this does not mean uBO "does not work", it just means nothing had to be blocked.

**Comment by specter78** [comment]
I looked at the logger and found that none of the request that should be blocked are made until popup is accepted and so uBO did not need to block anything till then. Based on this, I don't think it's a filter issue, but rather the website blocking access till cookie is accepted. 

Having said that, is there a way to bypass consent popup and still access such websites? I'm assuming more and more websites are going to use this technique to force users to accept cookies.
