### ISSUE TITLE
Add an advanced setting to prevent default lists from collapsing 

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uBlock-issues#1642]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Default filterlists doesn't collaps anymore

### A specific URL where the issue occurs
uBlock Settings Panel (`moz-extension://2707bfd1-e7b2-4eb5-ac1c-5880da5bed96/dashboard.html#3p-filters.html`)

### Steps to Reproduce
1. [Open uBlock Filterlist Settings Panel]
2. [Dissable one or more default lists]
3. [save]
4. [try to collapse the group]
5. [see that the default one's can't collapsed]

### Expected behavior:
Maybe there should be an advanced setting so you can choose where default listsgroups can collapse or not.

### Actual behavior:
The default list not collapse

### Your environment
* uBlock Origin version: 1.36.0
* Browser Name and version: Firefox 89.0.1
* Operating System and version: Windows 10 Home 20H2

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/7508700892bfecd9578c4eefdb673817c65f2cad
https://github.com/gorhill/uBlock/issues/2303

By design.

**Comment by BPower0036** [comment]
@gwarser My point was that there is now no choice. I would liked it you you could choose it the be collapsed or not via **admin** settings.

**Comment by uBlock-user** [comment]
This move is to distinguish default lists from other lists and hence help users realise which lists are default in nature.

**Comment by BPower0036** [comment]
I would like to change this default behavoir via admin settings, because now you have no choice.

**Comment by gorhill** [comment]
Declined.
