### ISSUE TITLE
Create hotfix filters to temporarily address critical filter issues

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#1645]
### Prerequisites
<details>

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
</details>

### Motivation for the feature request

Content blockers can suddenly begin to break most popular websites due to the website renewal or bad filter updates (adding poorly tested filters ([e.g. Google Docs issue on April](https://twitter.com/fanboynz/status/1382328862168678402)) or typo ([e.g. `media` added to EasyList a few days ago](https://twitter.com/gorhill/status/1409894204390653958))). 
We have recommended to users who are having trouble with these issues to manually update their filters. But unfortunately, technologically challenged users often don't doubt content blockers. In this context, uBlock origin is not install-and-forget solution.

### Description of the solution I propose 
- Create a new filterlist in the uAssets repository.
- It is usually an empty file. Only in case of serious incidents, the uBO-team will add a minimum number of filters, which will be removed after a few days.
- uBlock Origin subscribes to it by default and checks for its updates at short intervals (e.g. every hour).
- This behavior can be disabled in the advanced settings.

**Comment by uBlock-user** [comment]
We already have such list, it's called Unbreak.

**Comment by hirorpt** [comment]
>! Title: uBlock filters – Unbreak
! Expires: 4 days

The install-and-forget user will have trouble for up to four days. For normal Unbreak issues, few people will be bothered by this delay. However, for critical breakage of top sites such as Google Docs, the situation is different.

I guess that gorhil would not agree to shorten the update interval of the Unbreak filter due to bandwidth considerations. (https://github.com/gorhill/uBlock/issues/3406#issuecomment-355748757)
Filters that address only critical issues can be updated at short intervals without significant impact on bandwidth.

**Comment by gorhill** [comment]
Even if it's an empty file, having tens of millions of requests each hour is abusing GitHub, and this would put the project in trouble.

**Comment by uBlock-user** [comment]
`jsDelivr` would work, but cache-control is set for 7 days.

**Comment by gorhill** [comment]
Declined, as I do not want uBO to be more of a burden to servers I do not own, and I do not want uBO to use a server I own to keep the privacy policy dead simple. Maintainer of EasyList has put in place [measures to minimize likelihood of such mistake happening again](https://twitter.com/fanboynz/status/1410203797167636480).

**Comment by hirorpt** [comment]
Thank you for considering.
I know their abuse of generic filters break website broadly [again](https://github.com/easylist/easylist/commit/c543fd6) and [again](https://github.com/easylist/easylist/commit/b7d89d6), so I can't trust their measures. As for the other issues, I respect your decision.

**Comment by jimaek** [comment]
Hey, I just wanted to let you know if there is anything that [jsDelivr ](https://www.jsdelivr.com/)can do to help we would love to do it.
We serve almost 4PB of traffic per month. We can serve your traffic too if that would be helpful to your project in any way.
