### ISSUE TITLE
Malvertising Script mentions disabling uBlock in obfuscated variables

### ISSUE THREAD

**Issue by sloshnmosh** [uBlockOrigin/uBlock-issues#1647]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [ ] uBO with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

While researching a malicious advertising script I found references to disabling uBlock in obfuscated variables.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

The malicious script is hosted at: 
hxxps://iclickcdn[.]com/tag.min.js

### Steps to Reproduce

The malvertising script uses simple substitution cipher to obfuscate variables by changing letters of the alphabet by jumping ahead by 14.
a=o
b=p
c=q
d=r
etc.
A=O
B=P
C=Q
D=R
etc.
and when deciphered there is a variable:
'adblockDisableUblock'

My concern is that this malvertising script is able to somehow bypass or disable uBlock.
I'm hoping a researcher with better RE skills than I can determine if this script can actually disable or bypass uBlock and if so, defend against it.

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: N/A
* Browser Name and version: N/A
* Operating System and version: N/A

**Comment by mapx-** [comment]
EasyList is already blocking `||iclickcdn.com^`

You should report the pages where you get popups / anti adblocking stuff and not here but to uAssets
https://github.com/uBlockOrigin/uAssets/issues

**Comment by sloshnmosh** [comment]
Okay, thanks. Will do. 
I wasn’t sure where to post this.
