### ISSUE TITLE
Bug 1718776 - Back/Forward navigation does not work between Ublock Origin option pages

### ISSUE THREAD

**Issue by alice0775** [uBlockOrigin/uBlock-issues#1648]
### Prerequisites

- [✔ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ✔] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [✔ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [✔ ] uBO is the only extension
    - [✔ ] uBO with default lists/settings
    - [ ✔] using a new, unmodified browser profile
- [✔ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Back/Forward navigation does not work between Ublock Origin option pages.
At first I thought this was a bug in Firefox, but the mozilla developers pointed out that it was a bug on the add-on side. See https://bugzilla.mozilla.org/show_bug.cgi?id=1718776#c2

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
Ublock Origin option pages

### Steps to Reproduce

1. install Ublock Origin https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
2. Open dashboard (Options)
3. Navigate Settings, Filter lists and My filters, etc.
4. Try Back/Forward navigation

### Expected behavior:

[What you expected to happen]
Back/Forward navigation should always be working.
And Addressbar and  dashboard should be synced.

### Actual behavior:

[What actually happened]
Back/Forward navigation is not working some times.
And Addressbar and  dashboard do not match.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1718776#c2

### Your environment

* uBlock Origin version: 1.36.0
* Browser Name and version: Firefox89.0.2
* Operating System and version: Windows10 Home 21H1 19043.1052

**Comment by gorhill** [comment]
Note that I use [`self.location.replace()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace) to change the URL in the address bar, my understanding is that this should not add an entry in the history stack, but the behavior I am seeing is that there seems to be one entry added -- this occurs in both Firefox and Chromium.

**Comment by gorhill** [comment]
Changing the `src` attribute on the embedded iframe is what causes a history entry to be created.

**Comment by gorhill** [comment]
The fix is to not allow going back and forth, so the issue was this was possible at all. The reason to not allow going back and forth through browser history is that uBO must check whether there are pending changes in the current pane, and if so the user is warned about this, and must choose whether to keep or loose the changes.
