### ISSUE TITLE
Small bug: the version's number isnt updated

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uBlock-issues#1650]
After updating to 1.36.2 the version's number doesnt change even after closing/opening the browser again, i'm using latest waterfox classic.

**Comment by gorhill** [comment]
Why are you opening such an issue when 1.36.2 is not yet available on AMO?

**Comment by Felipefpl** [comment]
Why not? It's not against the rules and the version released here is gonna be there anyway isnt it?
