### ISSUE TITLE
Adds are back on YouTube. Only at the Start of some Videos. All skippable after 3 or 4 sec

### ISSUE THREAD

**Issue by Daisaigo1988** [uBlockOrigin/uBlock-issues#1652]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

https://www.youtube.com/watch?v=wRlShGD4QwI&list=PLhyKYa0YJ_5CJoVydSko806C07I7RT9n4&index=4

Had it on this playlist.

### A specific URL where the issue occurs

https://www.youtube.com/playlist?list=PLhyKYa0YJ_5CJoVydSko806C07I7RT9n4

### Steps to Reproduce

Play playlist. I had it on videos 2 3 and 4

### Expected behavior

no adds at all. Like it has been for a long time

### Actual behavior

Add pops up at the start of the video 1of2 and a skip button will appear after about 3 or 4 seconds 

### uBlock Origin version

1.36.2

### Browser name and version

Chrome Version 91.0.4472.124 (Official Build) (64-bit)

### Operating System and version

Win 10 Pro 2004

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
