### ISSUE TITLE
Advanced settings filterOnHeaders, popupPanelDisabledSections, & popupPanelLockedSections undocumented; benchmark unclear

### ISSUE THREAD

**Issue by saizai** [uBlockOrigin/uBlock-issues#1653]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Advanced settings include:
* `filterOnHeaders`
* `popupPanelDisabledSections`
* `popupPanelLockedSections`

These are not documented at https://github.com/gorhill/uBlock/wiki/Advanced-settings. Related issues discussing the popup settings, but not the lack of documentation: #1434, #1437, #1059

Also, the section on `benchmarkDatasetURL` implies (by describing it as a definition, as it does for the dataset URL) that there's a setting `benchmark` that could be set to the listed JS functions. AFAICT, this is incorrect — it's only run in console. A change to the wording would fix the ambiguity.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/wiki/Advanced-settings

### Steps to Reproduce

Read the documentation

### Expected behavior

Documentation should list all settings

### Actual behavior

Settings not documented

### uBlock Origin version

1.36.2

### Browser name and version

Chrome 91.0.4472.124 

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
See <https://github.com/gorhill/uBlock/wiki/Advanced-settings/_compare/0f93191373f19fa009cc1a00657f24c44d149f90...fb74c139ea28842ec48c7b39369b966f73b5860f>.

**Comment by saizai** [comment]
See https://github.com/gorhill/uBlock/wiki/Static-filter-syntax/_compare/ae8d183fc7283aae4c06230431d5dbd2c2c5624c (mentioning it, though that content doesn't seem to be in current wiki page), citing https://github.com/gorhill/uBlock/commit/bde3164eb445a4e74acca303ec9fa07f82ba1b1c
