### ISSUE TITLE
yandex-android   uBlockOrigin Unable to use advanced mode

### ISSUE THREAD

**Issue by ruizone** [uBlockOrigin/uBlock-issues#1655]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

1.Open Ublockorigin(1.36) Advanced Mode 2.Click more Option  In the pop-up window，Interface freeze,Button does not respond!

### A specific URL where the issue occurs

m.baidu.com

### Steps to Reproduce

1.Open Ublockorigin Advanced Mode 
2.Click more Option  In the pop-up window，Interface freeze

### Expected behavior

1.24.4 Version includes the previous version works very well

### Actual behavior

The options that pop-up interfaces are not responded

### uBlock Origin version

1.36.3.1

### Browser name and version

yandex browser 21.5.4

### Operating System and version

android 10

**Comment by gorhill** [comment]
Yandex browser is not officially supported, on mobile, only Firefox for Android is supported. Whoever is welcome to work on working out support currently not officially supported browsers, this has to be done pro-actively, not through opening issues.

**Comment by ruizone** [comment]
Ok, thank you for your great work 1.24.4 can also use it.
