### ISSUE TITLE
There is a problem with custom rule list updates

### ISSUE THREAD

**Issue by fxqy** [uBlockOrigin/uBlock-issues#1656]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

There is a problem with custom rule list updates, not up-to-date, and the browser opens the address request to the latest。

Should be 228 item to be right, the new addition of 2 can not be updated, feel that the cache has not been cleared

![image](https://user-images.githubusercontent.com/42601163/125217643-c1b92a00-e2f3-11eb-9636-c8f6ed332a78.png)

### A specific URL where the issue occurs

There is a problem with custom rule list updates, not up-to-date,

### Steps to Reproduce

There is a problem with custom rule list updates, not up-to-date,

### Expected behavior

There is a problem with custom rule list updates, not up-to-date,

### Actual behavior

There is a problem with custom rule list updates, not up-to-date,

### uBlock Origin version

uBlock Origin v1.36.2

### Browser name and version

iron 91

### Operating System and version

win10

**Comment by gothic-bum** [comment]
Per the [wiki](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists):  

> uBlock Origin discards duplicate filters, so the number of filters used within a filter list depends on how many duplicate filters were detected within that filter list. The order in which the filter lists are loaded into memory is undefined.

**Comment by uBlock-user** [comment]
uBO also discards invalids. What's the link to that mylist filterlist ?

**Comment by gwarser** [comment]
https://raw.githubusercontent.com/fxqy/fxqy.github.io/master/txt/mylist.txt 223 used out of 228 GitHub caching?

**Comment by gorhill** [comment]
Marking as invalid, see @gwarser's comment.
