### ISSUE TITLE
Pollock's list and the Lithuanian list now supports HTTPS

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#166]
This isn't a regular sort of issue, but I just wanted to point out that in relation to the research I did on https://github.com/collinbarrett/FilterLists/pull/339, I discovered that the list links for [Dan Pollock's Hosts](https://someonewhocares.org/hosts/hosts) and [Adblock Plus Lithuania](https://margevicius.lt/easylistlithuania.txt) now supports HTTPS, which I at least suppose means that those lists' _contentURL_ values in https://github.com/gorhill/uBlock/blob/master/assets/assets.json can be updated from HTTP to HTTPS accordingly?

**Comment by gorhill** [comment]
`assets.json` is also being pulled by the legacy version.
