### ISSUE TITLE
uBlock is not loading adminSettings at first run again

### ISSUE THREAD

**Issue by anulman** [uBlockOrigin/uBlock-issues#1660]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

If Chromium reloads after crashing, uBlock may not load adminSettings during its first run (see #1547). I notice that uBO caches `lastVersion` at script start; what if we deferred setting it until after the Promise.all instead?

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Set a custom filter list in `/etc/chromium/policies/managed/ublock_policy.json`
2. Load Chromium, then `kill` it before uBO finishes initializing
3. Load Chromium again, this time letting uBO finish initiaizing
4. uBO will not load the filters until Chromium next reboots

### Expected behavior

I expected uBO to have restarted itself after it finished initializing the first time

### Actual behavior

uBO did not restart itself, presumably because `lastVersion` had been set (making `lastVersion !== '0.0.0'`)

### uBlock Origin version

1.36.2

### Browser name and version

Mighty (Chromium 91.0.4472.114)

### Operating System and version

Ubuntu 18.04.4

**Comment by gorhill** [comment]
Please file an issue with Chromium devs for the issue of managed storage content not being served properly to extensions. The restart is merely a trickery to workaround an issue which is a browser issue -- the browser should properly return the content of the managed storage when an extension ask for it. I don't see trying to push further the trickery to be a good idea, assuming anything such approach can still technically be worked on.

**Comment by anulman** [comment]
Will do; they already have a bug about this.

Do you foresee any danger in moving `vAPI.storage.set('lastVersion', foo)` to after the Promise.all though?

**Comment by gorhill** [comment]
> Do you foresee any danger 

onVersionReady() is meant to execute code once  needed sometimes when a version change, so moving out version saving would just create a potential issue affecting everybody just to address the other potential issue here.

**Comment by anulman** [comment]
Thank you!
