### ISSUE TITLE
Chrome restarts ignore any injected CSP

### ISSUE THREAD

**Issue by taviso** [uBlockOrigin/uBlock-issues#1662]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I've noticed that chrome restarts do not honor any `content-security-policy` injected by uBlockOrigin, but it's not clear to me if this is a chrome bug or a uBlockOrigin bug. An `alert()` took me by surprise when I relaunched chrome after a reboot!

I understand that uBO uses `webRequest` to inject a csp response header (seems like a smart approach to me), but then are pages reloaded on restart before extensions? If that's the case, that seems like it might be a Chrome bug, because extensions have no opportunity to filter requests.

Do you consider this a problem, and if so, do you consider it a Chrome bug? If so I'll take care of filing a chromium bug.

### A specific URL where the issue occurs

https://lock.cmpxchg8b.com/alert.html

### Steps to Reproduce

- Disable JavaScript for `lock.cmpxchg8b.com`, something like `no-scripting: lock.cmpxchg8b.com true`
- Visit [https://lock.cmpxchg8b.com/alert.html](https://lock.cmpxchg8b.com/alert.html).
- Open a new tab and type `chrome://restart` into the address bar.

Observe that a JavaScript alert appears.

### Expected behavior

Restarting chrome does not defeat any injected csp.

### Actual behavior

Restarting chrome does defeat uBO's csp.

### uBlock Origin version

v1.36.2

### Browser name and version

Chrome 91

### Operating System and version

Fedora 34

**Comment by gorhill** [comment]
Yes, I consider this an issue in Chromium, see <https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch>. Given that `webRequestBlocking` permission is to be deprecated in the not so far future, I doubt this will ever be worked on as this does not seem to be a trivial fix.

**Comment by taviso** [comment]
Yep, fair enough. I suppose injecting a http-equiv policy would survive a restart, although I suppose the site could just send `no-store` and break that?

It can't hurt to file a chromium bug anyway (unless you already know of one?)

**Comment by gorhill** [comment]
See <https://bugs.chromium.org/p/chromium/issues/detail?id=523634>.

**Comment by taviso** [comment]
Ah, yep.

I tested injecting a http-equiv policy (you probably already know this), it does seem to work, but no-store does break it. It looks like there is already an advanced session for tweaking Cache-Control though. I'll grant you it's not trivial though!

**Comment by gorhill** [comment]
I made a quick test to inject a `meta` tah with the CSP directives injected in response headers, and this does not work for the URL test on my side. How did you test? uBO's content script has to query the background page to find out what needs to be done for the page, and this means it can inject the `meta` tag only when it receives a response. I do see the `meta` tag properly injected when force refreshing the page, but it's not there at browser launch.

**Comment by taviso** [comment]
You're right, my test was incomplete. Damn!
