### ISSUE TITLE
Add an option to ignore Window id

### ISSUE THREAD

**Issue by Wector11211** [uBlockOrigin/uBlock-issues#1665]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [ ] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In Cent Browser (chromium fork https://www.centbrowser.com) there is a multi-login tab feature that opens incognito tab in **the same** window, however in those tabs uBlock doesn't work even with "allow in incognito mode" checked.

You can say that it's the browser issue, **but** I can't completely agree, because other adblockers (and most other extensions) work perfectly fine in multi-login tab.

And **I found the reason**: uBlock checks `Window id` whereas other extensions don't, that's why I don't believe this post is a [duplicate](https://github.com/uBlockOrigin/uBlock-issues/issues/369), because there is a way to make it work:
Could you please add an option to ignore window id so that the extension will work even in multi-login tabs. I don't really want to go for another adblocker, because I find uBlock the best among others?

### A specific URL where the issue occurs

https://ascopost.com/ad-test-page/

### Steps to Reproduce

1. Create a multi-login tab (Ctrl+M)
2. Open any website (ad test page: https://ascopost.com/ad-test-page)

### Expected behavior

Block ads and interact with the extension pop up.

![Alt Text](https://i.imgur.com/MGoYe9X.gif)

### Actual behavior

![Alt Text](https://i.imgur.com/Htih2x5.gif)

### uBlock Origin version

1.36.2

### Browser name and version

Cent Browser 4.3.9.248 (Chromium 86.0.4240.198)

### Operating System and version

Windows 10 Enterprise (1909) x64

**Comment by gorhill** [comment]
> You can say that it's the browser issue, but I can't completely agree, because other adblockers (and most other extensions) work perfectly fine in multi-login tab.

I can use the same argument and point out that uBO works perfectly fine in Chromium and many other Chromium forks.

> uBlock checks `Window id` whereas other extensions don't

Can you be more detailed? Which code _exactly_ is causing an issue in your browser?

**Comment by Wector11211** [comment]
> I can use the same argument and point out that uBO works perfectly fine in Chromium and many other Chromium forks.

uBlock also works in Cent Browser, but not in multi-login tabs that has no window id (according to the developer)

> Which code _exactly_ is causing an issue in your browser?

I have some experience in JS and a bit it extension development. In spite of the fact I edited some extensions manually for my needs, uBlock is way more complex than any other extension I was digging into. If I could find the line of code that prevent uBlock from working in multi-login tab, I would probably be able to edit it myself and fix the issuer without opening a ticket. But as you can see, I reported, so I can't cope with it by myself, I hope you could help, because you know exactly where the window id check happens.

**Comment by gorhill** [comment]
> If I could find the line of code that prevent uBlock from working

How did you come to the conclusion `windowId` is the issue? Your report suggested you knew exactly where there was a failure.

When I grep for `windowId`, this is what I get:

```
platform/common/vapi-background.js:288:            browser.windows.onFocusChanged.addListener(windowId => {
platform/common/vapi-background.js:289:                this.onFocusChangedHandler(windowId);
platform/common/vapi-background.js:381:                    vAPI.windows.update(tab.windowId, { focused: true });
platform/common/vapi-background.js:510:        vAPI.windows.update(tab.windowId, { focused: true });
platform/common/vapi-background.js:567:        vAPI.windows.update(tab.windowId, { focused: true });
platform/common/vapi-background.js:618:    onFocusChangedHandler(windowId) {
platform/common/vapi-background.js:619:        if ( windowId === browser.windows.WINDOW_ID_NONE ) { return; }
platform/common/vapi-background.js:620:        vAPI.tabs.query({ active: true, windowId }).then(tabs => {
platform/common/vapi-background.js:623:            this.onActivated({ tabId: tab.id, windowId: tab
```

uBO does not use `windowId` is some weird, undocumented way, it just uses the browser extensions framework [as documented](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows). If Cent browser modified that extensions framework API, is there documentation about this?

**Comment by Wector11211** [comment]
> If Cent browser modified that extensions framework API, is there documentation about this?

I don't think they modify extension framework any way.
­

Also, I've been messing around with provided lines of codes, but nothing seemed to work. However, I decided to check out `manifest.json` additionally and came across with this parameter
```
platform/chromium/manifest.json:71:    "incognito": "split",
```
Once I removed that, uBlock started to work in multi-login tabs just perfectly. I'm not sure whether it's the right solution, but as a quick patch, it works.

**Comment by uBlock-user** [comment]
Removing that setting will bring back the issue mentioned in https://github.com/uBlockOrigin/uBlock-issues/issues/399#issuecomment-457753350

**Comment by gorhill** [comment]
Removing that line breaks strict blocking in incognito mode, users are presented with a browser error page instead of <https://github.com/uBlockOrigin/uBlock-issues/wiki/Strict-blocking>.

**Comment by gorhill** [comment]
I am going to decline this given that there seem no interest from someone to look into a sane fix for this. I checked many other Chromium fork and none of these seem to suffer the issue reported here, so as a result my position is that this needs to be fixed in the Cent browser.
