### ISSUE TITLE
Matching error in a  text part of a tag

### ISSUE THREAD

**Issue by CyberMan571** [uBlockOrigin/uBlock-issues#1667]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [  ] using a new, unmodified browser profile

### Description

![Screenshot from 2021-mobile](https://user-images.githubusercontent.com/30759335/126878849-facc51e8-e472-4100-8e77-60b665a3c05f.png)

seems on the picture, it has  a Parentheses/bracket problem, and it causes 'guid\(\) **\\{**' I have to use regex because of other parentheses 

I would like you improve  Procedural cosmetic filters options! For detecting, matching, sensitivity especially, has filter

### A specific URL where the issue occurs

```
https://mobile.donanimhaber.com/
```
### Steps to Reproduce

complete  script code:
```js
 function guid() { function s4() { return Math.floor((1 + Math.random()) * 0x10000) .toString(16) .substring(1); } return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4(); } function getSessionId() { var sessionId = ""; sessionId = window.localStorage.getItem("dh-session-id"); if (sessionId == null) { sessionId = guid(); window.localStorage.setItem("dh-session-id", sessionId); } return sessionId; } function setSession(type, id) { var sessionId = getSessionId(); var href = "/globalapi/sessioninsert?type=" + type + "&id=" + id + "&sessionId=" + sessionId; executeRequest(href, function (res) { }); } 
 ```

 However, I tried this code as regex, doesn't work still 

 when short it, removes it 
 ```
  ^script:has-text(function guid\(\)) 
 ```

### Expected behavior

-

### Actual behavior

-

### uBlock Origin version

1.36.2

### Browser name and version

78.12.0esr (64-bit)

### Operating System and version

LTS linux ubuntu

**Comment by CyberMan571** [comment]
Changeable title

**Comment by gorhill** [comment]
Please paste here the filter which you say is problematic, transcribing from a screenshot is tedious.

**Comment by CyberMan571** [comment]
```
mobile.donanimhaber.com##^script:has-text(  function guid() { function s4() { return Math.floor((1 + Math.random()) * 0x10000) .toString(16) .substring(1); } return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4(); } function getSessionId() { var sessionId = ""; sessionId = window.localStorage.getItem("dh-session-id"); if (sessionId == null) { sessionId = guid(); window.localStorage.setItem("dh-session-id", sessionId); } return sessionId; } function setSession(type, id) { var sessionId = getSessionId(); var href = "/globalapi/sessioninsert?type=" + type + "&id=" + id + "&sessionId=" + sessionId; executeRequest(href, function (res) { }); }  )
```
```
mobile.donanimhaber.com/^##body>script:has-text( function guid\(\) )
```
No works  both!

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/126883142-a45a6ead-6323-471b-9ec1-ccb079fee579.png)
```
<script onlc11bzy="" zvzdb851k="">
```
it appears when it uses
```
forum.donanimhaber.com,mobile.donanimhaber.com##body>script:has-text( function guid() )
```

**Comment by gorhill** [comment]
Your first filter does not match because nowhere in the source code is there a string which match your argument. You replaced newline with whitespaces, and sequence of whitespaces with less whitespaces.

Your second filter does not work because it has syntax errors, you appended `/^` to the hostname. Once that syntax error os fixed, the script tag is correctly removed.

This works fine, non eed to overcomplicate:

    mobile.donanimhaber.com##^body>script:has-text(function guid())

**Comment by gorhill** [comment]
The way I see it, you have problem crafting proper filters, and here is not the place to get help to craft filters, I suggest you post your issues to the dedicated reddit forum: <https://old.reddit.com/r/uBlockOrigin/>.

**Comment by CyberMan571** [comment]
Wiki entries can be explained in detail, please!
 I did  by looking available filter!
 sorry!   advanced filter, I' m on middle level!
 a suggestion, when I  write to Reddit, if it is a issue, can you help for everybody?

**Comment by CyberMan571** [comment]
@gorhill 
can be advanced  syntax analyzer on my filter tab
