### ISSUE TITLE
Add NSO Group Orgasus spyeare infectiob fomain blocklist to malware domains

### ISSUE THREAD

**Issue by ccuser44** [uBlockOrigin/uBlock-issues#1668]
It would be nice if this block list would be added: https://github.com/AmnestyTech/investigations/issues/4

Here is a boocklist made by voidspacecyz: https://raw.githubusercontent.com/voidspacexyz/amnesty_nso_domain_list/main/amensty_nso_domain_list.txt
This blocklist can be used automaticly

**Comment by uBlock-user** [comment]
Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

**Comment by ccuser44** [comment]
What?

**Comment by uBlock-user** [comment]
Read https://github.com/uBlockOrigin/uBlock-issues#ublock-issues
