### ISSUE TITLE
Code exception in contentscript.js (vAPI.setTimeout) when opening Chrome last session tabs that are partly cached

### ISSUE THREAD

**Issue by laukstein** [uBlockOrigin/uBlock-issues#167]
I am running the latest uBlock Origin on latest stable Chrome, Win10.
I have noticed this issue for a while - when opening Chrome with last tabs session and some of the tabs url server is down, Chrome shows partly cached page (cached HTML, failing on all external files, JS, CSS, etc.) and console shows exception coming from chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/js/contentscript.js

    Uncaught TypeError: Cannot read property 'setTimeout' of undefined

fails in 

    this.tid = vAPI.setTimeout(this.callback, 20000);

where `vAPI` suddenly is undefined.

![grabilla g14048](https://user-images.githubusercontent.com/183966/44105809-80e9327e-9ffb-11e8-83cd-7e85aebbe0e6.png)

**Comment by gorhill** [comment]
What was the URL (as asked in the template) associated with that dev console?

**Comment by gorhill** [comment]
OK I can reproduce with @uBlock-user screenshot, which shows a page from `github.com`.

**Comment by uBlock-user** [comment]
I will just post the STR here.

1) Open `chrome://settings/onStartup` and select `Continue where you left off`

2) Open console, click on gear icon on the extreme right and tick `Preserve Log`

3) Visit github.com and once it completes loading close the browser.

4) Start Chrome again and the browser will connect to github.com and open the console as soon as you can to notice those errors being spewed.

**Comment by gorhill** [comment]
Looks like a Chromium issue to me.

The exception occurs at [this line](https://github.com/gorhill/uBlock/blob/4a57825411c8103da92d578758d2bac4027e1ab2/src/js/contentscript.js#L156). Yet this line can't possibly be reached if `vAPI` is undefined -- which is why exception -- because it is unreachable due to [this line](https://github.com/gorhill/uBlock/blob/4a57825411c8103da92d578758d2bac4027e1ab2/src/js/contentscript.js#L108) not too far above.

**Comment by uBlock-user** [comment]
Indeed, I cannot reproduce on Nightly.

**Comment by gorhill** [comment]
Actually, investigating further I find that [this line](https://github.com/gorhill/uBlock/blob/8be1aed04d641210ad5e778e17496ea097a125b5/platform/chromium/vapi-client.js#L439) is being executed when I launch the browser -- so correction, that seems to be a uBO issue. I need to keep investigating why this happens.

**Comment by gorhill** [comment]
While investigating <https://github.com/uBlockOrigin/uBlock-issues/issues/164>, I find that the issue also present with Firefox:

      NS_ERROR_NOT_INITIALIZED: contentscript.js:467

**Comment by uBlock-user** [comment]
Did it appear in the console ? I didn't see that when I tried to reproduce twice.

**Comment by gorhill** [comment]
I can't remember what I did for the error to be reported, I was really focused on investigating #164. Now I am unable to find steps to reproduce for Firefox. But given this is the same exact line, I can say that Firefox suffered the same issue.

**Comment by laukstein** [comment]
I guess this still haven't landed in stable version. The exception still happens and I see now 1 additional exception in

    var userStylesheet = vAPI.userStylesheet;

https://github.com/gorhill/uBlock/commit/dc430f1eff851a1206c30bb6fb6af5938e9df029 probably expected to fix it too.

Here the full log screenshot
![grabilla g10932](https://user-images.githubusercontent.com/183966/44189357-aa710780-a12b-11e8-8fe2-c43be439ebd1.png)

Actually seems `net::ERR_CONNECTION_REFUSED` is caused by uBlock Origin,  what means isn't related to Chrome cache at all.

**Comment by gorhill** [comment]
What version of uBO are you using?

**Comment by Mouvedia** [comment]
I am using the same Canary version as @peterschussheim and my uBO version is 1.16.18.

**Comment by peterschussheim** [comment]
uBO version 1.16.18

**Comment by gorhill** [comment]
The fix has not been released in a stable release yet, it's in the [dev build](https://github.com/gorhill/uBlock/releases/tag/1.16.21rc1).

**Comment by peterschussheim** [comment]
just did some basic tests with dev build and problem appears to be fixed.  @gorhill thank you for the prompt response and **your work on uBO** 👍

**Comment by Mouvedia** [comment]
version: 1.16.21.101
browser: Canary 71.0.3556.0

It doesn't work if the details' privacy mode switch is on.

**Comment by gorhill** [comment]
> details' privacy mode switch is on

I don't know what that means. Please opened a new issue with proper steps to reproduce if you think there is an issue.

**Comment by Mouvedia** [comment]
> Please opened a new issue

I cannot: I am not allowed.

> I don't know what that means.

https://imgur.com/a/Cws0Ltf

**Comment by gorhill** [comment]
> I cannot: I am not allowed.

Of course you are allowed, otherwise you wouldn't be able to comment like you are doing now.

As said, I need steps to reproduce, I can't reproduce error message with a private window. Please open a new issue with all the required details in the template.

**Comment by Mouvedia** [comment]
Well I wasn't yesterday. It was limited to the contributors.

**Comment by gorhill** [comment]
You are confusing <https://github.com/gorhill/uBlock/issues> with here -- here is to file issues, the other is reserved to contributors -- as explained in the top opened issue.
