### ISSUE TITLE
If a large media element originates from css, you cannot click the element to fetch the image.

### ISSUE THREAD

**Issue by pseay** [uBlockOrigin/uBlock-issues#1670]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

If the large media element is in a style attribute (e.g. style="background-image: url(https://...)" ) and the image is blocked, clicking on the image placeholder will not cause the image to be reloaded.

### A specific URL where the issue occurs

`https://www.spreadprivacy.com/one-click-preference-menu/`

### Steps to Reproduce

1. If your setting "Block media elements larger than [ ] KB" is above 62 KB, set it to something lower like 50 KB (default)
2. Go to this article: `https://www.spreadprivacy.com/one-click-preference-menu/`
3. Toggle the large media element blocking so it's on
4. Hit ⌘/Ctrl + Shift + r to reload the page ignoring the cache

### Expected behavior

I would expect the image placeholder to have a dotted red border around it and that when I click on it, it would fetch the image and display it.

### Actual behavior

The image placeholder was not recognized by uBlock and so I could not interactively reload the image by clicking on the placeholder.

### uBlock Origin version

v1.36.2

### Browser name and version

Brave: Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)

### Operating System and version

Windows 10. Version: 21H1

**Comment by gorhill** [comment]
I don't believe this can be fixed, or if it can be fixed somehow, I suspect it would take a huge amount of work, so closing as wontfix. This has to be accepted as a limitation of the feature.

**Comment by Rudxain** [comment]
I have a similar problem with Tumblr (`no-scripting`): images seem to get fetched, but not displayed.

An easy workaround (on Firefox Android) is to hold (right-click equivalent) the element, then "Open image in new tab"

**Comment by stephenhawk8054** [comment]
@Rudxain Can you give exact link?

No content is being able to load when I use `no-scripting`, and no images requests are being fetched to me either:

![image](https://github.com/user-attachments/assets/1bd84f0c-6e64-4343-8356-85a161c45696)

**Comment by Rudxain** [comment]
> @Rudxain Can you give exact link?

I meant image posts, such as [this one](https://www.tumblr.com/cileekk/655683599537995776)

**Comment by Rudxain** [comment]
Can someone please mention this issue in [the Wiki](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-large-media-elements)?

**Comment by stephenhawk8054** [comment]
Images shown normally for me with `no-scripting`

![image](https://github.com/user-attachments/assets/20949822-3f65-413d-9fbc-341db00bbe40)

**Comment by Rudxain** [comment]
Before click:
![red outlines](https://github.com/user-attachments/assets/b8563c4d-33d8-4e1f-a431-961235fd4037)

After click:
![grey outlines](https://github.com/user-attachments/assets/78275516-d05b-40b3-9264-deb8e79154e7)
