### ISSUE TITLE
Ubo 1.37 breaks at least some sites that use googletagmanager if specific filters in use

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1671]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Related topic: https://www.reddit.com/r/uBlockOrigin/comments/osht47/prisjaktnu_is_a_blank_page/h6su51o/?context=3

When these two filters are present:

`||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js`

`||googletagmanager.com/gtm.js$script`

Ubo will blank pages that use googletagmanager. I don't know how widespread this issue is, but at least one specific site cluster is affected.

This behaviour is not present if Ubo 1.36.2 is in use, but in 1.37 blanking happens.

### A specific URL where the issue occurs
```

https://hintaopas.fi
https://www.prisjakt.nu/
https://ledenicheur.fr/
https://prisjagt.dk/
https://www.prisjakt.no/
https://pricespy.co.nz/
```

### Steps to Reproduce

1. Use Ubo 1.37
2. Apply filters:

`||googletagmanager.com/gtm.js$script,redirect-rule=googletagmanager.com/gtm.js`

`||googletagmanager.com/gtm.js$script`

3. Test the same with Ubo 1.36.2

(4. Remember to disable Ubo's internal unbreak filters)

### Expected behavior

Ubo would not blank the page when these filters are in use.

### Actual behavior

Ubo blanks the page.

### uBlock Origin version

1.37

### Browser name and version

Firefox 90.0.2

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
I will publish a revision to stable channel given the number of sites found to be affected.
