### ISSUE TITLE
Windows 11 Edge Browser sites not loading when enabled

### ISSUE THREAD

**Issue by wnj85** [uBlockOrigin/uBlock-issues#1672]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Website pages do not load or only partially load when uBlock Origin Extension enabled in Edge browser on Windows 11.
Disable uBlock Origin extension and websites will load (and fully) instantly.

### A specific URL where the issue occurs

`https://www.bbc.co.uk`

### Steps to Reproduce

1. enter `https://www.bbc.co.uk` (or other site URL) in address bar
2. wait
3. website will not load

### Expected behavior

Website should load

### Actual behavior

Website does not load

### uBlock Origin version

1.36.2

### Browser name and version

Microsoft Edge Version 92.0.902.55 (Official build) (64-bit)

### Operating System and version

Microsoft Windows 11 Version 21H2 (OS Build 22000.100)

**Comment by gorhill** [comment]
> I verified that this is not a filter issue

How did you verified that this is not a filter issue?

**Comment by gorhill** [comment]
Closing as _invalid_ sue to lack of feedback.
