### ISSUE TITLE
Extension does not load on Chrome 92 on macOS 10.15

### ISSUE THREAD

**Issue by mjethani** [uBlockOrigin/uBlock-issues#1673]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I just updated my version of Chrome to 92.0.4515.107 on macOS 10.15.6 and uBlock Origin 1.37.2 stopped working.

I get this error in `background.html`:

```
CompileError: WebAssembly.instantiateStreaming(): Wasm code generation disallowed by embedder
    at publicsuffixlist.js:578
```

I see the same error when I build it locally and install it as an unpacked extension.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

Install uBlock Origin on Chrome 92 (macOS 10.15).

### Expected behavior

The extension works as usual.

### Actual behavior

The extension icon does not appear and nothing is blocked.

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.107

### Operating System and version

macOS 10.15.6

**Comment by mjethani** [comment]
Sorry about jumping the gun. It seems if I "repair" the extension then it starts working again. But I lose all my filters. Essentially it's as if all the settings are lost.

I'm closing this now but it still might be informative for someone who faces this issue.

If you wrote any of your own filters then they are gone.

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/otxz60/corrupted_after_chrome_update/
https://www.reddit.com/r/uBlockOrigin/comments/oss99f/extension_completely_broken_in_chrome_9204515107/
