### ISSUE TITLE
localhost matched with a different domain

### ISSUE THREAD

**Issue by SimonChaumet** [uBlockOrigin/uBlock-issues#1674]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The localhost domain is matched even if the filter sets a specific domain

### A specific URL where the issue occurs

http://localhost:3000

### Steps to Reproduce

1. open a html file or provide a full server
2. make a request to something with `/advertisements/` with a random domain like localhost (e.g: http://localhost:8888/api/agencies/1/clients/34/advertisements/23)
3. The request is blocked by the filter `/advertisements/*$domain=~ellefanningfan.net` from EasyList

### Expected behavior

The filter should only apply on the registered domain, not localhost

### Actual behavior

The request is blocked

### uBlock Origin version

1.37.0

### Browser name and version

Firefox Developer Edition 90.0b4 (64-bit)

### Operating System and version

Manjaro 5.10.42-1-MANJARO

**Comment by uBlock-user** [comment]
`~ellefanningfan.net` means everywhere except `ellefanningfan.net`

**Comment by gorhill** [comment]
> - [x] I checked the documentation to understand that the issue I report is not a normal behavior

[Documentation](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax):

> uBlock Origin ("uBO") supports most of EasyList filter syntax, so you can refer to existing filter syntax documentation from [Adblock Plus](https://adblockplus.org/en/filters) and [AdGuard](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).

[AdGuard documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#domain-modifier):

> If you want the rule not to be applied to certain domains, start a domain name with `~` sign.

**Comment by SimonChaumet** [comment]
Localhost isn't supposed to be whitelisted by default ?

**Comment by gorhill** [comment]
[Documentation](https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites#important-read-carefully):

> There are predefined trusted site directives when you first install uBO:
> 
>     about-scheme
>     chrome-extension-scheme
>     chrome-scheme
>     edge-scheme
>     moz-extension-scheme
>     opera-scheme
>     vivaldi-scheme
>     wyciwyg-scheme
