### ISSUE TITLE
Picker and Zapper modes

### ISSUE THREAD

**Issue by github-account1111** [uBlockOrigin/uBlock-issues#1680]
### Prerequisites

- [x] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

IMAO this is more a wording problem than a bug. Maybe I'm just dense or don't use the two modes frequently enough to memorize which ones does what, but every time I need to manually block an element I find myself googling "ublock origin picker vs zapper" to recall which one is temporary, and which one is permanent.

Why not simply label the two functionalities "Temporarily remove an element" and "Permanently remove an element"? The words "Picker" and "Zapper" just don't really mean anything to me. When I read picker, all I can think of is the Eyedropper Tool in Photoshop, and I don't even know what a zapper is.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues

### Steps to Reproduce

1. Have an element you desire to block
1. Open Dashboard

### Expected behavior

Intuitively knowing which option of the two to pick.

### Actual behavior

Cryptic mode names which I have to google to figure out which one does what every time.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 90.0.2

### Operating System and version

Windows LTSC (1809)

**Comment by uBlock-user** [comment]
That's what wiki is for --

https://github.com/gorhill/uBlock/wiki/Element-picker
https://github.com/gorhill/uBlock/wiki/Element-zapper

**Comment by uBlock-user** [comment]
> Cryptic mode names which I have to google to figure out which one does what every time.

That's what wiki is for --

https://github.com/gorhill/uBlock/wiki/Element-picker
https://github.com/gorhill/uBlock/wiki/Element-zapper

Read it untill it becomes non-cryptic to you.

**Comment by github-account1111** [comment]
It's not a matter of how many times I read it. The point is I use it infrequently enough that the next time I have to use it again I've already forgotten - something that could be entirely avoided if the wording actually made sense. Doesn't the fact that a user has to read it every time mean it could be made more intuitive?

It's akin to calling Settings "Banana" and Logger "Chewbacca" (obviously exaggerated, but that's to get the point across).

**Comment by uBlock-user** [comment]
>  Doesn't the fact that a user has to read it every time mean it could be made more intuitive?

Hover over the buttons and tooltips will appear as a reminder.

**Comment by gorhill** [comment]
> "Permanently remove an element"

The picker is the tool to create _filters_, either static network filters which purpose is to block network requests, or cosmetic filters which purpose is to hide elements. Until you pick an element with it, it's not determined whether you are interested in blocking network requests or hide DOM elements.

Now surely that the purpose of an element _picker_  is not to remove it immediately from the page, its purpose is to _pick_ something in order to further do something following the result of the _picking_. I fail to see how you can imagine it's purpose might be to remove an element immediately from the page, which is exactly what _zapping_ convey.

In any case, I decline to change anything in there should you want to argue this further.

**Comment by github-account1111** [comment]
> Hover over the buttons and tooltips will appear as a reminder.

The tooltips literally say "Enter element zapper mode" and "Enter element picker mode."

**Comment by github-account1111** [comment]
@gorhill okay not "Permanently remove an element" then. "Permanently _filter_ an element." I was just giving an example. The keywords are "permanent" and "temporary." Could also be "Enter permanent mode" and "Enter temporary mode."

>which is exactly what zapping convey

Doesn't convey that to me. Not at all.

**Comment by TravisLlado** [comment]
I completely agree. They might as well be called "blue mode" and "green mode". If users know that two buttons do two things but the names aren't descriptive enough to clearly and immediately indicate which is which, then the interface is just poorly designed. The tools should be renamed.
