### ISSUE TITLE
CPU 100% usage by uBlock on Chrome 92+

### ISSUE THREAD

**Issue by akiirui** [uBlockOrigin/uBlock-issues#1682]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock Origin let a core 100% usage, When I enable 'Prevent WebRTC from leaking local IP addresses' on Chrome 92+.

OS: Arch Linux
Chrome: Version 92.0.4515.131 (Official Build) (64-bit) (Stable channel)

Disabled this option (Default):
![Screenshot from 2021-08-09 00-46-28](https://user-images.githubusercontent.com/3736910/128639279-702bc378-fcbc-474a-8a02-c6e04dca519f.png)

Enabled this option:
![Screenshot from 2021-08-09 00-46-38](https://user-images.githubusercontent.com/3736910/128639295-f72c50fd-bb4f-4d86-9c8e-38c097c00e5b.png)

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Install Chrome 92+
2. Enable option 'Prevent WebRTC from leaking local IP addresses'

### Expected behavior

uBlock runs with normal CPU usage

### Actual behavior

uBlock runs with a single core 100% usage

### uBlock Origin version

1.37.2

### Browser name and version

Chrome Version 92.0.4515.131 (Official Build) (64-bit)

### Operating System and version

Arch Linux

**Comment by gorhill** [comment]
Unable to reproduce using Chromium 92.0.4515.107 in incognito mode on Linux Mint with the setting _"Prevent WebRTC from leaking local IP addresses"_  enabled. Someone else who can reproduce will have to investigate.

**Comment by gorhill** [comment]
When the _"Prevent WebRTC from leaking local IP addresses"_ setting is toggled, uBO merely tells the browser to toggle WebRTC mode through a browser API. Since you can reproduce, you could probably find which API call is causing the issue, by putting breakpoints at <https://github.com/gorhill/uBlock/blob/2aed123b14bf8a8f1cfa82b8bcf97aaa173377de/platform/common/vapi-background.js#L147>.

**Comment by akiirui** [comment]
@gorhill Thanks for reply, I have more steps of reproduce:

1. Install chrome 92+
2. Open Chrome task manager
3. Install uBlock Origin from store
4. Open uBlock Dashboard - Filter lists, keep selected list default, and update now.
5. Open uBlock Dashboard - Settings, enable "Prevent WebRTC from leaking local IP addresses"
6. uBlock starts 100% usage a few secs. (if selected more lists, it's longer)

The problem only happen once, such :
- Everytime startup browser
- Everytime launch new incognito (enable extension for incognito)
- First time enable option(if this option is not enable on startup)

100% on first time enable option
https://user-images.githubusercontent.com/3736910/128643482-8d0a8847-4377-4036-b9b4-652fa615098f.mp4

100% on startup (enabled this option)
https://user-images.githubusercontent.com/3736910/128643480-add30c7f-a65b-4ef7-8fcb-c59bf7ae5273.mp4

**Comment by akiirui** [comment]
And Windows 10 Chrome Version 92.0.4515.131 can reproduce this issue too.

**Comment by gorhill** [comment]
I believe you when you say you can reproduce. However I can't reproduce and so the only way to make progress from here is for you to investigate -- I can't investigate if I can reproduce. Please read again about how you can step in the code using the browser's debugger.

**Comment by uBlock-user** [comment]
The only time I see CPU going 100 or above is when I force update lots of filterslists and only stays for a second or two and goes back to normal.

**Comment by akiirui** [comment]
> I believe you when you say you can reproduce. However I can't reproduce and so the only way to make progress from here is for you to investigate -- I can't investigate if I can't reproduce. Please read again about how you can step in the code using the browser's debugger.

I try to set breakpoints at `background.html - js/vapi-background.js#L147`, And step and step to view call stack.

But I cannot found what caused this issue, Tasks manager doesn't show uBlock has high CPU usage when I view call stack in debugger until debugger not auto-pause anymore.

Maybe it's issue only for my environment. I will disable this option to prevent the issue.

Thanks.
