### ISSUE TITLE
A Feature Request:Remove ... and Add (+,-) or (︽,︾) else a best

### ISSUE THREAD

**Issue by CyberMan571** [uBlockOrigin/uBlock-issues#1684]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

 Has been added  the (...) to the new  version of  uBlock Origin, to almost all codes. 
 And the (...) is no nice, and  meaningless
 
for example, on u-block pop-up menu 
...githubapp.com
...cloudflare.com
3p 

 You can  find it  more effective symbol

### A specific URL where the issue occurs

-

### Steps to Reproduce

Actually, it on  previous version(1.36) has been no. I use because of

### Expected behavior

-

### Actual behavior

-

### uBlock Origin version

1.37.0

### Browser name and version

Firefox 78.12.0 esr

### Operating System and version

Linux and windows

**Comment by CyberMan571** [comment]
If  you want a screenshot, I send it!

**Comment by gorhill** [comment]
Declined -- whether you like the symbol or not involves a lot of subjectivity, and when subjectivity is involved, as the one who do the work, I will give priority to mine. Some of the objective reasons I used the ellipsis are:

- It's a Unicode symbol which renders well
- NoScript uses the ellipsis to denote that a rule applies to the domain and all descendants

**Comment by CyberMan571** [comment]
![kazam 2021-08-10 15 37 12 png](https://user-images.githubusercontent.com/30759335/128900139-e605eca5-0c02-487e-8418-526f077c99b8.png)
it is an idea!  or ---> , <--- from top to bottom

**Comment by CyberMan571** [comment]
@uBlock-user 
do you look this? 
I didn't come here to argue and test knowledge.

**Comment by uBlock-user** [comment]
gorhill declined your request with the stated reason, there's nothing more to say.
