### ISSUE TITLE
Ubo does not hide off-screen elements when using a procedural cosmetic filter

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1686]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When using this filter `mobiili.fi##div.fullarticle:has(img[src="https://mobiili.fi/aaa.png"])` to hide sponsored articles (they have a dark grey label that says `Sponsoroitu`), only those articles will be hid that are on screen when the page is loaded / refreshed. Off-screen sponsored articles won't be hid. Unhid articles that can be seen when scrolling the page down, will be hid if the page is refreshed once but after that, other sponsored articles that were hid, will appear again.

Picture of a sponsored article:

![kuva](https://user-images.githubusercontent.com/17256841/129635775-23ddca47-05c9-4fba-9c3d-7a3bbb1c9919.png)

### A specific URL where the issue occurs

`https://mobiili.fi/2021/08/11/`

### Steps to Reproduce

1. Apply `mobiili.fi##div.fullarticle:has(img[src="https://mobiili.fi/aaa.png"])`
2. See how the first sponsored article is hid (it's on screen)
3. Scroll down the page to see how another sponsored article is visible
4. Refresh the page - now the sponsored article that was visible, will disappear, but the first sponsored article at the top (which is now off-screen) will appear back, just scroll back to the top to see it.

(5. There are other sponsored articles as well if you scroll the page down a bit, can also test with them.)

### Expected behavior

`mobiili.fi##div.fullarticle:has(img[src="https://mobiili.fi/aaa.png"])` would hide all the sponsored articles

### Actual behavior

Only those will be hid that are on screen, off-screen articles won't be hid.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
It's a filter issue, you need to use `watch-attr()` to ensure the filtering engine become aware of changes in the `src` attribute of the `img` elements. This works:

    mobiili.fi##.categories:watch-attr(src) > img[src="https://mobiili.fi/aaa.png"]:upward(.fullarticle)

**Comment by peace2000** [comment]
Ok, thanks! Sorry didn't realize this.
