### ISSUE TITLE
Yahoo!/Oath CSP Privacy panel leaks RAM and CPU when uBlock is enabled

### ISSUE THREAD

**Issue by KNTRO** [uBlockOrigin/uBlock-issues#1689]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

You need a Yahoo! account to test this.

### A specific URL where the issue occurs

https://yahoo.mydashboard.oath.com/

### Steps to Reproduce

1. Log in with your Yahoo! account, go that URL above and check your activity in that webpage. Go to the different sections like _Your Account_, _Yahoo Mail_, _Yahoo.com_, _Finance_, _Sports_, etc.
2. You will note that the pages take a lot of time to load, the browser freezes and both RAM and CPU consume increases within a few seconds.

### Expected behavior

This should not happen at all.

### Actual behavior

This happens with uBlock enabled and only the five Built-in filters.

### uBlock Origin version

1.37.2

### Browser name and version

Waterfox G3.2.4.1 (64-bit)

### Operating System and version

Windows 10 Version 20H2 (OS build 19042.685), 64 bit

**Comment by uBlock-user** [comment]
Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.

**Comment by gorhill** [comment]
Additionally, Waterfox is not officially supported -- out of curiosity I tried with Firefox 91 and there was no issue, the page loaded fine.
