### ISSUE TITLE
Too high CPU usage (Especially on YouTube)

### ISSUE THREAD

**Issue by westor7** [uBlockOrigin/uBlock-issues#169]
### Prerequisites

- [yes] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [yes] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [yes] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [no] uBlock Origin is the only extension
    - [yes] uBlock Origin with default lists/settings
    - [yes] using a new, unmodified browser profile
- [yes] I am running the latest version of uBlock Origin
- [yes] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When i enable that add-on i got a high CPU usage especially on youtube while i am viewing videos...

### Expected behavior:

Using LESS CPU usage

### Your environment

* uBlock Origin version: Latest
* Browser Name and version: Firefox 61.0.2
* Operating System and version: Windows 10 x64 1803 17134.228
* PC Laptop Details: http://speccy.piriform.com/results/3sJoxwNN17Vbk0vR4QKewns

- Thanks!

**Comment by gorhill** [comment]
If you want to make the case the issue is with uBO, you need profile data using the Gecko profiler -- too many false reports in the past for me to go on a quest to validate your suspicion. Keep in mind I profile uBO all the time, and I found no such performance issues.

**Comment by westor7** [comment]
@gorhill 

I fully checked that by enable/disable it and via Task Manager i was able to reproduce it..

Also can you please give me more informations about what is that Gecko and how can i use it in order to decrease the CPU usage of that add-on?

- Thanks!

**Comment by gorhill** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Reporting_a_Performance_Problem

**Comment by gorhill** [comment]
Also, why did you **not** fill and deleted the section:

> ### A specific URL where the issue occurs
> 
> [A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

**Comment by westor7** [comment]
Ok it says to download and use the latest beta (unstable) build, i don't want to do that so i will uninstall this add-on, thank you.

**Comment by gorhill** [comment]
> it says to download and use the latest beta

It says this for MacOS only, you are using Windows.
