### ISSUE TITLE
On Android Popup Overlays [or Underlays] On-Screen Navigation Buttons

### ISSUE THREAD

**Issue by madranet** [uBlockOrigin/uBlock-issues#1691]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

On my Nexus 2013 tablet, which has the Android navigation buttons 'on-screen' [as opposed to below the visible screen area] and when there are a lot of domains listed, the uBlock Origin popup overlays [or underlays] the on-screen navigation buttons. This makes it impossible to interact with  any domains listed in that area.

_Here's the screen on the Nexus 2013.  Navigation buttons are 'virtual' as in part of the on-screen display:_
![photo00](https://user-images.githubusercontent.com/669658/130357529-a1210b55-d766-4568-93eb-e18d5af823f3.png)

_When uBlock Origin popup is taller than the screen, it overlays [or underlays] the navigation buttons.  So, in this instance, it's not possible to tap the column beside 'youtube.com' to add a NOOP, because tapping there will minimise the browser window instead. System navigation buttons obviously taking precedence over the content of the popup:_
![photo2](https://user-images.githubusercontent.com/669658/130357571-d1034a55-4392-49f1-9845-10c1b0120129.png)

_Same scenario, different website:_
![photo3](https://user-images.githubusercontent.com/669658/130357894-6d0e477f-9710-428f-b508-5df69384c8c1.jpg)

BTW --I don't know if it's relevant to this visual glitch, but I have set `popupFontSize` to a custom value [25px I think] in uBlock's advanced settings as, otherwise, it's literally too small to read the domain list on this 7" tablet.

### A specific URL where the issue occurs

github.com

### Steps to Reproduce

[See above]

### Expected behavior

uBlock Origin popup should not draw over Android's on-screen navigation buttons.

### Actual behavior

uBlock Origin draws over Android's on-screen navigation buttons.

### uBlock Origin version

Current

### Browser name and version

Yandex

### Operating System and version

Android

**Comment by uBlock-user** [comment]
@madranet fix addressed in dev build, try it out.
