### ISSUE TITLE
Ublock debian build issue

### ISSUE THREAD

**Issue by paledega** [uBlockOrigin/uBlock-issues#1695]
python3 script must run `python3 xxx` not `python xxx`

For debian:
python is python 2
python3 is python 3

https://github.com/paledega/uBlock/commit/32ce27cf8969645544c3cd4be19f42421b22a857

**Comment by gorhill** [comment]
Commit <https://github.com/paledega/uBlock/commit/32ce27cf8969645544c3cd4be19f42421b22a857> pulled into uBO's master branch.
