### ISSUE TITLE
Dynamic filter precedence doesn't actually follow "more specific = higher precedence"

### ISSUE THREAD

**Issue by duxovni** [uBlockOrigin/uBlock-issues#1698]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The documentation for dynamic filtering says 
> The more specific the party, the higher the precedence.
> `example.com` overrides `3rd-party scripts`

I'd expect that to mean that `example.com * * noop` overrides `* * 3p-script block`. However, in practice, `* * 3p-script block` wins.

Looking at the code in [src/js/dynamic-net-filtering.js#L277](https://github.com/gorhill/uBlock/blob/255ae00677e3e92ceef77dafe375489a0b484356/src/js/dynamic-net-filtering.js#L277), we've got
```
        // Precedence: from most specific to least specific

        // Specific-destination, any party, any type
        decomposeHostname(desHostname, decomposedDestination);
        for ( const deshn of decomposedDestination ) {
            if ( deshn === '*' ) { break; }
            this.y = deshn;
            if ( this.evaluateCellZ(srcHostname, deshn, '*') !== 0 ) {
                return this.r;
            }
        }

        const thirdParty = is3rdParty(srcHostname, desHostname);

        // Any destination
        this.y = '*';

        // Specific party
        // TODO: equate `object` as `sub_frame`
        if ( thirdParty ) {
            // 3rd-party, specific type
            if ( type === 'script' ) {
                if ( this.evaluateCellZ(srcHostname, '*', '3p-script') !== 0 ) {
                    return this.r;
                }
            } else if ( type === 'sub_frame' ) {
                if ( this.evaluateCellZ(srcHostname, '*', '3p-frame') !== 0 ) {
                    return this.r;
                }
            }
            // 3rd-party, any type
            if ( this.evaluateCellZ(srcHostname, '*', '3p') !== 0 ) {
                return this.r;
            }
        } else if ( type === 'script' ) {
            // 1st party, specific type
            if ( this.evaluateCellZ(srcHostname, '*', '1p-script') !== 0 ) {
                return this.r;
            }
        }

        // Any destination, any party, specific type
        if ( supportedDynamicTypes[type] !== undefined ) {
            if ( this.evaluateCellZ(srcHostname, '*', type) !== 0 ) {
                return this.r;
            }
        }

        // Any destination, any party, any type
        if ( this.evaluateCellZ(srcHostname, '*', '*') !== 0 ) {
            return this.r;
        }
```

Since `evaluateCellZ` checks every decomposition of the source hostname, if example.com makes a 3rd-party JS request to example.net, we check rules in the following order:

[line 281, first loop]
- `example.com example.net *`
- `com example.net *`
- `* example.net *`

[line 281, second loop]
- `example.com net *`
- `com net *`
- `* net *`

[line 299]
- `example.com * 3p-script`
- `com * 3p-script`
- `* * 3p-script`

[line 308]
- `example.com * 3p`
- `com * 3p`
- `* * 3p`

[line 326]
- `example.com * *`
- `com * *`
- `* * *`

So, we have `* * 3p-script` > `example.com * 3p` > `* * 3p` > `example.com * *`. This doesn't match my intuition of what "more specific" means at all. It seems like what we need to do is move the decomposition of the source hostname to an outer loop around the entire rule evaluation, rather than performing it in an inner loop for each rule type; or if this is the intended behavior, make that a *lot* clearer in the wiki.

My proposed change would be approximately to rewrite `evaluateCellZ` to not decompose the source hostname, and instead wrap lines 279-328 in a loop over the decompositions of the source hostname. That would give the following evaluation order:
- `example.com example.net *`
- `example.com net *`
- `example.com * 3p-script`
- `example.com * 3p`
- `example.com * *`
- `com example.net *`
- `com net *`
- `com * 3p-script`
- `com * 3p`
- `com * *`
- `* example.net *`
- `* net *`
- `* * 3p-script`
- `* * 3p`
- `* * *`
Which seems much more intuitive to me. I'm happy to draft a pull request.

### A specific URL where the issue occurs

https://github.com

### Steps to Reproduce

1. Enable dynamic filtering
2. Set up rules to block 3rd-party scripts by default: `* * 3p-script block`
3. Set up rules to noop all requests from a specific site: `github.com * * noop`

### Expected behavior

All requests on github.com should be allowed unless they're blocked by a static filter rule.

### Actual behavior

3rd-party script requests from github.com to githubassets.com are blocked by dynamic filtering.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 90.0.2

### Operating System and version

Fedora 33

**Comment by gorhill** [comment]
A rule such as `* * 3p-script block` is a convenience to automatically set a local `* 3p-script block` rule for all sites, through rule inheritance -- the UI makes this clear.

Your local rule `* * noop` is not more specific than the local (inherited) rule `* 3p-script block`, and consequently won't override it.

This is a common sense behavior, if I set a global rule to block `facebook.com`, I sure do not want this rule be overriden by any local rule other than those explicitly targeting `facebook.com`.

**Comment by duxovni** [comment]
> This is a common sense behavior, if I set a global rule to block `facebook.com`, I sure do not want this rule be overriden by any local rule other than those explicitly targeting `facebook.com`.

I completely agree with that. My opinion is that the precedence order should be specific destination > specific source > specific request type; for instance, `* facebook.com * block` should take higher precedence than `example.net * * noop`, which should take higher precedence than `* * 3p-script block`.

However, if you want to keep the current behavior, I can live with that. In that case, though, I really think the documentation page on rule precedence should be updated to explain more clearly that while specific destination domains take precedence over specific request types, specific source domains don't take precedence.

**Comment by felix-22** [comment]
duxovni, the Wiki documentation is free to edit by volunteers, you can improve it: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-precedence, also, by looking at the commit history I see that some inaccuracies / typos have already been corrected in the past: [here 1](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-precedence/_compare/14879ce61e30ae0b4fe3061b5d1157c7ee7403b4...6acab809fcd36f1d5b01f8db9510bbb268e82f63) and [here 2](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-precedence/_compare/6acab809fcd36f1d5b01f8db9510bbb268e82f63...4bf3bf9d1ec6602c586f920eb5c0a34cabddff9b), you may have found another (but I don't know because I'm not in the subject of dynamic filtering and I rarely use it). By the way, it happened to me 3 times already, that the Wiki documentation confused me, and sometimes I ended up opening reports that turned out not to be a bug in uBO, but inaccuracy or lack of information in the documentation. But it seems like nothing out of the ordinary to me, just like bugs happen in software, inaccuracies and typos happen in documentation as well.

**Comment by gorhill** [comment]
> `* * noop`, which should take higher precedence than `* * 3p-script block`

`* *` is less specific than `* 3p-script`, now **that** would cause an issue with the documentation if it worked the way you think it should work.

"3rd-party scripts requests" is a subset of "all requests", I don't see why you keep arguing that the _all_ cell is more specific, and why you think the documentation misled you into thinking it is.

**Comment by duxovni** [comment]
I think I maybe understand the issue. It sounds like in your mental model, a "rule" is `dest type policy`. Rules get attached to specific source domains, and their specificity is compared within the context of the domain they're attached to. In my mental model, a "rule" is `source dest type policy`; I'm considering the source as just another part of the rule, that can be more specific or less specific just like the other components. Am I characterizing things correctly?

**Comment by gorhill** [comment]
> Am I characterizing our disagreement correctly?

Sounds like. Global rules are merely a convenience to indicate the default local state of a cell -- through rule inheritance, where the precedence is really played out. There is no _"diagonal"_ override, this would just be unmanageable and very difficult for anyone to predict the result.

The matrix in the popup panel is constructed to convey this: global rules bleed into their local counterparts, then cells are vertically ordered from least specific to most specific.

**Comment by duxovni** [comment]
I see what you're saying. The starting point for my thinking was that there's already a diagonal override when comparing `dest * action` and `* type action`; neither of those rules is a subset of the other, but we decide that the specific destination matters more than the specific request type. It's a bit confusing to me that the source field doesn't work the same way.

To put it another way, in the cells displayed in the UI, the actual priority ordering is roughly
```
8 7
6 5
4 3
2 1
```
while I was envisioning it as
```
8 4
7 3
6 2
5 1
```
which doesn't feel inherently less reasonable to me, but now that I've talked through this, I do kinda see how the UI tries to reflect this prioritization. In any case, since felix pointed out that the uBlock-issues repo has a version of the wiki that I'm able to edit, I can try and update the rule precedence page to make this point clearer.

**Comment by duxovni** [comment]
Here's my attempt at codifying all of this: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-precedence

**Comment by gorhill** [comment]
> In general, narrower rules override broader ones

Why use "in general"? This implies it's more complicated than is actually is.

There is no exception, more specific rules do override less specific rules in all cases. I don't want the documentation to become more ambiguous for all because of one case of misunderstanding. At most clarifying that global rules propagate to local rules and that precedence is then evaluated between resulting local rules, inherited or not, is how it works.

**Comment by duxovni** [comment]
I use "in general" because there are some cases where neither rule is a subset of the other (eg, specific destination vs specific request type), and the tie needs to be broken as described in the table. I can change the phrasing if you think it's confusing.

**Comment by gorhill** [comment]
I do consider a specific destination without a type is more specific than a type without a destination -- I see this as intuitively correct, it would be a bad surprise to anyone to find out that nooping 3rd-party scripts override a block rule for `facebook.com`.

**Comment by duxovni** [comment]
I completely agree that it's intuitively correct, but in a set-theoretic sense it's not actually more specific, and I think the documentation needs to account for other people's intuition being different. I'm fine removing the "in general" though, the table lays it all out pretty unambiguously regardless.
