### ISSUE TITLE
Crash on Firefox for Android

### ISSUE THREAD

**Issue by SamuelePilleri** [uBlockOrigin/uBlock-issues#1699]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBO 1.37.2 crashes Firefox for Android 91.3.1 on pretty much every page. Tried to reset the browser and the problem happens only after reinstalling uBO.

### A specific URL where the issue occurs

https://pagellapolitica.it/blog/show/1186/da-israele-al-regno-unito-arrivano-i-primi-dati-sul-calo-dellefficacia-dei-vaccini

### Steps to Reproduce

1. Open the URL, for example from an app
2. Wait for the crash to happen

### Expected behavior

The page loads without ads

### Actual behavior

Firefox crashes

### uBlock Origin version

1.37.2

### Browser name and version

Firefox for Android 91.3.1

### Operating System and version

Android 8.1

**Comment by gwarser** [comment]
Webpages should not crash browsers. uBO is written in webpage technologies. I tried on two devices in Firefox Nightly without issues. [Report to Mozilla](https://github.com/mozilla-mobile/fenix/issues/), send crash reports to them.
