### ISSUE TITLE
Element picker find twice body on website

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#17]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock web inspector dectect double `body` on website, when block social buttons on `wpn.pl`.

### A specific URL where the issue occurs

```
http://www.wnp.pl
```

### Steps to Reproduce

1. open website

2. try block social buttons on website (in header website):

   > ![image](https://user-images.githubusercontent.com/35370833/39190875-ce9467a6-47d5-11e8-8640-5233275c6cf9.png)

3. click in propuse cosmetic  `##.social` filter (without <kbd>Ctrl</kbd>) if uBlock no create invalid filter.

4. filter does not work.

   > ![image](https://user-images.githubusercontent.com/35370833/39191633-a955bb32-47d7-11e8-8a4a-99fc84f451db.png)

### Expected behavior:

filter should by detect element and no see double body:

```
##body >  .new:nth-of-type(1) > .pageWidth > .social
```

> ![image](https://user-images.githubusercontent.com/35370833/39191677-bf561382-47d7-11e8-8047-004c098ad93a.png)

### Actual behavior:

filter have dectect double body:

   <pre><code>##body > <b>body ></b> .new:nth-of-type(1) > .pageWidth > .social`</code></pre>

### Your environment

* uBlock Origin version: **1.16.0**
* Browser Name and version: **Firefox 59.0.2**
* Operating System and version: **Windows 7 Pro x64**

PS.  I know, I can create `##.social` rule with press <kbd>Ctrl</kbd>.

**Comment by gorhill** [comment]
I can reproduce.

**Comment by krystian3w** [comment]
I tried in Arch and reproduced:

![image](https://user-images.githubusercontent.com/35370833/39192438-749c1b1e-47d9-11e8-8f70-c8e5ffca86c3.png)
