### ISSUE TITLE
Provide a way to submit custom flters to adblock list maintainers

### ISSUE THREAD

**Issue by robinpaulson** [uBlockOrigin/uBlock-issues#1700]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Firstly, apologies if this has been already submitted. I did perform a search of the issues page, but it may be too generic to find.

I use several websites which have advertising not blocked by uBlock. Now, you will say "this is not a problem with uBo, contact the maintainer of the list.". And you would be correct to say this. However, what I am proposing is a feature which provides a way to submit our own custom filters to one or more filter lists. It could be run at a predefined time, or manually. I've added a website with the worst advertising which isn't caught, but there are of course many. Thanks for reading.

### A specific URL where the issue occurs

windguru.net

### Steps to Reproduce

This issue may be too trivial for this question to be important

### Expected behavior

A way to submit custom filters to list maintainers

### Actual behavior

There is no way to submit custom filters at present.

### uBlock Origin version

1.37.2

### Browser name and version

firefox 91.0.1

### Operating System and version

ubuntu 20.04

**Comment by uBlock-user** [comment]
For English sites submit your filters at -- https://github.com/easylist/easylist/issues

**Comment by robinpaulson** [comment]
Thanks for getting back to me so quick and for considering what I wrote.

The reason I raised this here was to ask for the inclusion of the feature within ublock itself. That would be far smoother and simpler than a manual transfer of data from one page to another. Additionally, I'm sure there are plenty of ubo users who are unable or unwilling to do that.
