### ISSUE TITLE
"Enable cloud storage support" doesn't exactly convey what this setting does

### ISSUE THREAD

**Issue by gianpaj** [uBlockOrigin/uBlock-issues#1703]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

"cloud storage" doesn't exactly convey what this setting does.

I propose to rename the text to "Enable cloud sync"

![image](https://user-images.githubusercontent.com/899175/131990385-a8c33570-9f67-4f5d-985b-e459f8324cc2.png)

I tried submitting this but I can't open a PR
https://github.com/gorhill/uBlock/commit/51f7ddc096457de1475f198c68823308002115d8

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### uBlock Origin version

all

### Browser name and version

all

### Operating System and version

all

**Comment by gorhill** [comment]
It's not syncing, the user has to manually push or pull, it's really a cloud storage in my opinion, so I will decline.

**Comment by gianpaj** [comment]
makes sense. thanks
