### ISSUE TITLE
removeparam is sometimes not applied when clicking on links

### ISSUE THREAD

**Issue by rusty-snake** [uBlockOrigin/uBlock-issues#1704]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Sometime (if links are realized using JS events rather than `<a>`) `removeparam`  does not remove query params.

Originally I discovered this on AMO search (https://addons.mozilla.org/en-US/firefox/search/?q=ublock+origin) with `utm_*` params. However the STR will use youtube with a custom `removeparam` rule because AMO is special  (requires `extensions.webextensions.restrictedDomains=""` & `privacy.resistFingerprinting.block_mozAddonManager=true`) and youtube was the first site I could find where I could reproduce this behaviour.

This bug maybe relates to the "Prevents tracking injection over history API" option of ClearURLs.

> - [x] uBO with default lists/settings 

Default settings except for using Privacy>AdGuard URL Tracking Protection and `$removeparam=v`.

### A specific URL where the issue occurs

https://youtube.com/

### Steps to Reproduce

1. Add `$removeparam=v` to your filters
2. Open https://www.youtube.com/ (and agree to  help G to improve their service, manipulate you and so on)
3. Click on any video
4. Look at urlbar and see `https://www.youtube.com/watch?v=1234asdf`
5. Reload (Strg+R)
6. Look at urlbar and see `https://www.youtube.com/`
7. Look into the logger and see that only at step 5 (but not at step 3) `v` gets removed.

### Expected behavior

Query parameters get removed in step 3 and 5.

### Actual behavior

Query parameters are removed only in step 5.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Operating System and version

Fedora 34

**Comment by uBlock-user** [comment]
> Look into the logger and see that only at step 5 (but not at step 3) v gets removed.

`$removeparam` only applies if a network request is made, youtube doesn't make a network request if you click any video on the homepage.

**Comment by gorhill** [comment]
I don't see any instance of `v=` in the logger when following the repro steps. What you are looking at is Youtube replacing the URL address using [`replace()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace), it's a cosmetic change by the browser, while uBO's `removeparm` works on outgoing network requests.

**Comment by krystian3w** [comment]
Any chance to generate specific abort action to use `replace()`?
