### ISSUE TITLE
The uBO settings' list-entry counter counts 1 "$all" entry as 5 entries

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#1706]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Currently, the entry counter that is used at `chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#3p-filters.html`, count `$all` entries as being worth 5 entries. Logically they should be worth 1; or perhaps worth 3 to signify that it means `(no $ suffix)` + `$doc` + `$popup`.

This substantially affects https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt, which is shown in "Filter lists" as having 27,000 entries, when the actual number is closer to 7,000, making the list look less optimised than it actually is.

### A specific URL where the issue occurs

chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#3p-filters.html

### Steps to Reproduce

1) Open up a fresh install of uBO Developer Build in a Chromium-based browser, and go to "Filter lists".
2) Sync all the lists there that ask for it, just in case.
3) Go to "My filters", and ensure it is empty.
4) Type any kind of basic rule with `$all` into it and save, for instance `||johnmadden.berlin^$all`
5) Go back to "Filter lists".
6) *My filters* is now shown as "5 used out of 5".

### Expected behavior

`$all` entries count as some number lower than 5 in the "Filter lists" counting system.

### Actual behavior

`$all` entries count as 5 each in the "Filter lists" counting system.

### uBlock Origin version

1.37.3b21

### Browser name and version

Vivaldi 4.1.2369.21 (Stable channel) (64-bit)

### Operating System and version

Windows 10 21H1 x64

**Comment by uBlock-user** [comment]
> Logically they should be worth 1; or perhaps worth 3 to signify that it means (no $ suffix) + $doc + $popup.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#all
