### ISSUE TITLE
Element IDs starting with a number are incorrectly marked as syntax errors

### ISSUE THREAD

**Issue by d07434b2c08f** [uBlockOrigin/uBlock-issues#1707]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I'm trying to create a filter involving an element with an ID starting with a number, which has been valid HTML since HTML5, but uBlock is considering it a syntax error. The specific ID is `#2x-container` on reddit (with the redesign). Using  `reddit.com###2x-container` triggers the syntax error and disables the filter, but if I instead use `reddit.com##[id="2x-container"]` then the filter works as expected.

### A specific URL where the issue occurs

https://new.reddit.com

### Steps to Reproduce

1. Open the uBlock Origin settings page
2. Select the "My filters" tab
3. Create a filter matching the pattern `example.com###[0-9][0-9A-Za-z_-]*`
4. The filter is highlighted red despite being valid

### Expected behavior

Filters with IDs starting with 0-9 should be considered valid.

### Actual behavior

Filters with IDs starting with 0-9 are considered invalid and highlighted red.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91 / Chrome 93

### Operating System and version

Windows 10 / Ubuntu 21.04

**Comment by gorhill** [comment]
> The filter is highlighted red despite being valid

It's not valid, see [CSS character escape sequences / leading digits](https://mathiasbynens.be/notes/css-escapes):

> If the first character of an identifier is numeric, you’ll need to escape it based on its Unicode code point. For example, the code point for the character `1` is `U+0031`, so you would escape it as `\000031` or `\31` .
