### ISSUE TITLE
Item not getting added to the cart if the Plugin is enabled

### ISSUE THREAD

**Issue by Birkaransingh94** [uBlockOrigin/uBlock-issues#1708]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

It gives a Console error - 
(index):7274 crbug/1173575, non-JS module files deprecated.

### A specific URL where the issue occurs

https://plugins.matomo.org/HeatmapSessionRecording

### Steps to Reproduce

1. Select any of the check boxes
2. click "Add to Cart Button"

### Expected behavior

The item should be added to the cart

### Actual behavior

Nothing happens

### uBlock Origin version

1.37.2

### Browser name and version

chrome Version 93.0.4577.63 (Official Build) (x86_64)

### Operating System and version

MacOS 11.5.2

**Comment by gothic-bum** [comment]
It is caused by the `/heatmapsessionrecording/*` filter in EasyPrivacy.  
Per the instructions, filter issues should be reported at the [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), or you can make a post on [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

**Comment by Findus23** [comment]
I created https://github.com/easylist/easylist/pull/9005 to fix this issue.
