### ISSUE TITLE
Filters for elements with subdomain wildcard

### ISSUE THREAD

**Issue by nao20010128nao** [uBlockOrigin/uBlock-issues#1709]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Given filter lines like this:

```
*.gigafile.nu###main_panel
11.gigafile.*###main_panel
42.gigafile.*###main_panel
```

The first one is not allowed in current uBO, while latter two are allowed. uBO should support the first too. The website has a lot of subdomains, so this feature is required to cover the case.

This happens when adding lines on "My filter", not on any filters.

### A specific URL where the issue occurs

https://11.gigafile.nu/

### Steps to Reproduce

1. Open uBO settings
2. Add these rules
```
*.gigafile.nu###main_panel
11.gigafile.*###main_panel
```
3. See if it's accepted

### Expected behavior

All these filters are accepted as valid, and eliminating from DOM as well.

### Actual behavior

Not all filters are accepted, resulting in allowing ads to exist.

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Firefox 91.0.1, from official repository on Ubuntu

### Operating System and version

Ubuntu 20.04 x86_64

**Comment by uBlock-user** [comment]
> The first one is not allowed in current uBO, while latter two are allowed. uBO should support the first too. The website has a lot of subdomains, so this feature is required to cover the case.

Use `gigafile.nu###main_panel`, read the wiki if you're not familiar with the syntax.

**Comment by gorhill** [comment]
> - [x] I checked the documentation to understand that the issue I report is not a normal behavior
