### ISSUE TITLE
ajax.googleapis.com/www.google.com bypasses ubo completely 

### ISSUE THREAD

**Issue by Blu35urF** [uBlockOrigin/uBlock-issues#1710]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

UBO filters are bypassed even if specifically i blocked globally and locally requests coming from ajax.googleapis.com and `www.google.com` (even if special rule is created to block the request no matter what) . This was detected with the help of nextdns logger feature that clearly showed beyond any doubt ubo is bypassed by those 2 domains mention. What can be noted is that those 2 domains when ubo is active are not shown in firefox about:networking#dns either giving the impression they are blocked but that's not true. Other blocked requests seems to work as intended.
EDIT: also `www.googletagservices.com` gets thru ubo checked on a different site and seems to be something rather general and not specific to only one site

### A specific URL where the issue occurs

`https://www.stiripesurse.ro/`

### Steps to Reproduce

open your dns logger (i used nextdns)
block in any way global/local/or special rule ajax.googleapis.com; `www.google.com` or `www.googletagservices.com`
load a website with known google code (e.g `https://www.stiripesurse.ro/`)
requests toward those mentioned above domains will still hit DNS server

### Expected behavior

Requests toward ubo blocked domains should not reach DNS

### Actual behavior

Some blocked domains thru ubo still reach DNS. This behavior seems to be prevalent among google domains but can't have 100% accurate image of the whole "disaster" as there are probably millions of websites that can't be checked so most probable it's a bug that impact other domains.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0 64 bit

### Operating System and version

Artix 20210726; 5.13.14-hardened kernel

**Comment by gorhill** [comment]
Unable to reproduce, using Firefox's `about:networking#dns` to investigate:

- Navigate to `about:networking#dns`
- Click "Clear DNS Cache"
- Click "Refresh"
- Navigate to `https://www.stiripesurse.ro/` in a new tab
- Wait for page to load completely
- Go to `about:networking#dns` tab
- Click "Rrefresh"
- Result:

![Screenshot from 2021-09-09 09-24-52](https://user-images.githubusercontent.com/585534/132694342-29b5a225-ed04-4f85-b53a-721c2eae6b8c.png)

Do not use NextDNS to investigate, this can lead to erroneous conclusions, use the above steps, and ensure that the output of `about:networking#dns` matches that of uBO's logger.

**Comment by gorhill** [comment]
If you think the browser is bypassing uBO with regard to DNS queries, you will have to open an issue on [Bugzilla](https://bugzilla.mozilla.org/home).

**Comment by Blu35urF** [comment]
Think it's firefox 92 version fault as before updating to 92 i didn't see such a huge bombardment on my DNS logs with blocked requests (by DNS) had about half or even less requests due to the fact ubo did his job on ff 91

**Comment by gorhill** [comment]
I did setup Firefox to use NextDNS and linked my IP to it, and I can confirm that I do see DNS queries for `ajax.googleapis.com` and `google.com`.

**Comment by gorhill** [comment]
I pushed the test farther with the rule `* * 3p block`, cleared the logs, then force-reloaded with cache bypass `https://www.stiripesurse.ro/`, and refreshed the NextDNS logs, and it does show a list of 3rd parties which should not be there. Firefix 91.0.2. So it looks like Firefox is bypassing uBO.

At first I was worried that your NextDNS account might have been receiving quieries from other source than Firefox and was skeptical that the result were reliable (I never used NextDNS before), but I just went through setting it up for just Firefox and I confirm that the results are unexpected.

**Comment by gorhill** [comment]
Is it possible that NextDNS is internally inferring secondary DNS queries by looking parsing the content of `www.stiripesurse.ro`?

**Comment by uBlock-user** [comment]
Could verify if DNS queries are leaking or not via WireShark ?

**Comment by gorhill** [comment]
> Could verify if DNS queries are leaking or not via WireShark ?

Yes, I think this needs to be done to sort out the issue. I suspect NextDNS may be showing DNS queries which were not made by the browser, so as to make its blocking feature more prominent.

**Comment by uBlock-user** [comment]
Any chance this could be happening due to _uncloak-canonical-names_ setting ?

**Comment by gorhill** [comment]
No, uBO does not attempt to uncloak blocked network requests, there is no point doing so.

**Comment by Blu35urF** [comment]
I guess wireshark would help though as we can look at what ip connects and derive the domain from ip. So if we open a website full of google code that should not get thru ubo we shouldn't see in wireshark any ip related to google requests or responses

**Comment by gorhill** [comment]
I am pretty confident there is no connection to blocked remote servers. The issue here is merely that there appear to be DNS requests made to NextDNS (or by NextDNS internally) for blocked remote servers, but that is either on Firefox or NextDNS side -- I am confident Firefox definitely does not connect to those blocked sites, so this is not a serious issue, at most it's pointless DNS queries being logged.

**Comment by uBlock-user** [comment]
If I browse to `https://streamable.com/` , `about:networking#dns` shows `socket.streamable.com` even though ||socket.streamable.com^ is present in EasyPrivacy, seems DoH is prioritised.

**Comment by gorhill** [comment]
@uBlock-user That would be a different issue then the one here, since this one is reported in `about:networking#dns` (seems to involve `wss://` requests).

**Comment by Blu35urF** [comment]
Tried with wireshark and found 1 ip (142.250.186.51) which belongs to ajax.googleapis.com which has an ip range 142.250.0.0/15 uploaded print screen from link cos here couldn't upload. Will retry the test withoud DoH
[https://ibb.co/wwkg64d](url)

**Comment by Blu35urF** [comment]
Sent 6 requests and received 5 from ajax.googleapis.com

**Comment by Blu35urF** [comment]
Look guys source and destination. Sorry again for the poor images
https://ibb.co/v3dktMf
https://ibb.co/9ZJ73sm

**Comment by gorhill** [comment]
I checked with [Firefox profiler](https://profiler.firefox.com/), and I didn't see anything supporting that Firefox makes those DNS queries, so if you think you make the case this is happening, you will have to open an issue with Firefox devs, uBO is merely using the APIs available to it, there is nothing which can be done from here.

**Comment by Blu35urF** [comment]
Alright maybe is something on my end or a firefox bug. So should i close it?

**Comment by uBlock-user** [comment]
This is not a uBO issue.

**Comment by gorhill** [comment]
Just out of curiosity, I also tried with the Network browser tool for the page, and exported resulting HAR file. Searching through it I see DNS queries reported only for what was not blocked by uBO.

**Comment by Blu35urF** [comment]
Hope is not a bug affecting only Arch users that would be nasty.

**Comment by gorhill** [comment]
Another observation: I blocked all 3rd-party requests, cleared the browser DNS cache, then forced a cache bypassed-reload of the page, and `about:networking#dns` is showing DNS queries for the following hostnames despite these were blocked:

- blacknews.ro
- mediastiriv1.freenode.ro
- cdnjs.cloudflare.com

While NextDNS's logs show DNS queries for pretty much everything pulled by the page it seems. Only Firefox devs/NextDNS can enlightened was to was is going on behind-the-scene.

**Comment by Blu35urF** [comment]
Firefox it's a fox :) .But nevertheless i can for sure tell that at least on my machine those requests pass thru firefox unknown tunnels :). Tested with netstat -atupln and there it doesn't show

**Comment by Blu35urF** [comment]
Tested with wireshark without DoH and it doesn't leak also nextdns doesn't show any leaks toward any domains blocked by uBO. So it's a bug in firefox regarding DoH 98% sure

**Comment by gorhill** [comment]
> Tested with wireshark without DoH and it doesn't leak also nextdns doesn't show any leaks

Well if you disabled DoH in Firefox, the queries won't show in NextDNS. I still think it's a possibility NextDNS generate those log entries on its side so as to show what it would block if there was no blocker.

**Comment by yokoffing** [comment]
Related: `https://www.reddit.com/r/uBlockOrigin/comments/pmwrlk/blocked_requests_reaching_dns_resolver_with/`

**Comment by uBlock-user** [comment]
Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1730418

**Comment by Blu35urF** [comment]
It impacts only built in firefox DoH i believe. Disabling ff DoH will "cure" that problem. Didn't tried with encrypted dns at the os level so can't know for sure.

**Comment by Blu35urF** [comment]
Would be interesting to find out when this Firefox bug started to be present, weeks, months. If i'm getting it right it means built in ff tracking blocking feature also failed on all this period? It's ok when you know you're tracked but when you have a false sense of privacy is worse than taking no measures

**Comment by gorhill** [comment]
> It's ok when you know you're tracked but when you have a false sense of privacy is worse than taking no measures

How is this a "tracking" issue? This is merely an issue of unneeded DNS queries for blocked secondary resources.

**Comment by uBlock-user** [comment]
workaround - https://bugzilla.mozilla.org/show_bug.cgi?id=1730418#c9

**Comment by uBlock-user** [comment]
The issue I discovered in https://github.com/uBlockOrigin/uBlock-issues/issues/1710#issuecomment-916159871 is also remedied via the workaround mentioned by the devs.

**Comment by Blu35urF** [comment]
> How is this a "tracking" issue? This is merely an issue of unneeded DNS queries for blocked secondary resources.
Then it's ok if did not affect tracking/blocking features of ff and uBO. Good to know cos for me was not very clear and even now i don't quite fully understand but if it's not that bad than yeah, great news! And thank you very much for this clarifications.

**Comment by Blu35urF** [comment]
I also am a big uMatrix user. So sad that project did not make it :(. I use uMatrix even i know is not maintained anymore

**Comment by uBlock-user** [comment]
fixed in v94 - https://bugzilla.mozilla.org/show_bug.cgi?id=1730418#c17
