### ISSUE TITLE
1fichier.com wont load or sometimes break if the ublock origin is enabled in chrome.

### ISSUE THREAD

**Issue by derptroll123** [uBlockOrigin/uBlock-issues#1715]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

1fichier.com wont load or sometimes break if the ublock origin is enabled in chrome. No other extension is present except ublock origin, this issue is not present in firefox with only ublock origin installed.

### A specific URL where the issue occurs

1fichier.com 

### Steps to Reproduce

install ublock origin in chrome
open any 1fichier.com link

### Expected behavior

site should load properly 

### Actual behavior

site breakes or wont load at all

### uBlock Origin version

 1.37.2

### Browser name and version

Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 20H2 build 19042.844

**Comment by gorhill** [comment]
> - [x]  I verified that this is not a filter issue (MUST be reported at filter issue tracker)

How did you verify this is not a filter issue?

**Comment by gorhill** [comment]
Closing as invalid, reporter makes no case this is not a filter issue.
