### ISSUE TITLE
Some profile skipped using "relax blocking mode"

### ISSUE THREAD

**Issue by daniporr** [uBlockOrigin/uBlock-issues#1718]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

As reported in https://github.com/gorhill/uBlock/wiki/Advanced-settings#blockingprofiles, blocking profiles can be modified and you can switch between them using _the "Relax blocking mode" keyboard shortcut_.

In particular, I wanted to add to the default four blocking modes the additional one "Hard mode" (i.e., like the first one but with scripting).
This should be the code for it (with an orange color): "11101/#F50".

If I add it between "Hard mode +No scripting" and "Medium mode +No scripting", i.e., ` blockingProfiles: 11111/#F00 11101/#F50 11010/#C0F 11001/#00F 00001`, it works as expected.
But, if I add it between "Medium mode +No scripting" and "Medium mode", i.e., ` blockingProfiles: 11111/#F00 11010/#C0F 11101/#F50 11001/#00F 00001`, it does not work (when using the keyboard shortcut, this new profile is simply skipped).

Here the reasons why I want the second case.

- I visit a website and I do not want any tracking
  - so "Hard mode + No scripting"
- If the website "does not look good", in most cases what it needs is simply to load the images from an external website (for instance a CDN)
  - so "Medium mode + No scripting"
- In some cases, the problem is with the JS code (for instance, lazy loading content), so I want to enable JS but disable 3rd-party (I still want maximum privacy)
  - so "Hard mode" (with scripting)
- In the cases where both of the previous ones are required, I want to enable them (but only if strictly needed)
  - so "Medium mode" (with scripting)

Obviously, I do not want to enable JS if not needed, so I would like to first "try" "Medium mode + No scripting" (which works in most cases), but it seems that this is not possible with the current version of uBlock.
 

### A specific URL where the issue occurs

https://github.com (but it happens "everywhere")

### Steps to Reproduce

1. Enable "Hard mode + No scripting"
2. Change `blockingProfiles` to `11111/#F00 11010/#C0F 11101/#F50 11001/#00F 00001`
3. Enable the "Relax blocking mode" keyboard shortcut
4. Load a webpage
5. Change blocking mode using the keyboard shortcut

### Expected behavior

You should see the following blocking modes/colors:

1. Hard mode + No scripting / #F00 red
2. Medium mode + No scripting / #C0F violet
3. Hard mode / #F50 orange
4. Medium mode / #00F blue
5. Default / grey

### Actual behavior

You see the following blocking modes/colors:

1. Hard mode + No scripting / #F00 red
2. Medium mode + No scripting / #C0F violet
~3. Hard mode / #F50 orange~
4. Medium mode / #00F blue
5. Default / grey

### uBlock Origin version

1.37.2

### Browser name and version

Any browser

### Operating System and version

Any OS

**Comment by gorhill** [comment]
You can't relax to a more strict mode -- the command is called "Relax blocking mode, so you can't re-enable the no-scripting switch with this command, this is what you are trying to do and what happens internally to find out what needs relaxing:

- 1111x = 1111x (hard mode + no-scripting)
- 1111x & 1101x = 1101x (medium mode + no-scripting)
- 1101x & **1110x** = 1101x (same as before, so it is skipped)
- 1101x & 1100x = 1100x (medium mode)
- 1100x & 0000x = 0000x (easy mode)

**Comment by daniporr** [comment]
Thank you for your answer.

Probably my message was not very clear, I am sorry for that.
I understood that this is the current behaviour/implementation and I tried to provide some arguments on why I think it should behave differently.

You are right, the implementation matches the behaviour you described (and the one described in the documentation), so there is no "bugs" in it.
But, I am arguing that this behaviour is "wrong", or, better, that it should be "extended" to also consider the case I presented.

If we consider the "blocking modes" as privacy preserving methods, I argue that "Hard mode" is a "relaxation" of "Medium mode + no-scripting" for the reasons I illustrated above (and I think someone might say that "Medium mode + no-scripting" is a "relaxation" of "Hard mode", and also this would not work). I am happy to provide more details and explain them further if you are interested in this discussion.
For this reason, it should be possible to "relax" from "Medium mode + no-scripting" to "Hard mode".

I have no problem if you have a different opinion about this, and I am happy to discuss it further, but I wanted to clarify my claim because you may have misunderstood it.

Thanks again for your help!

**Comment by gorhill** [comment]
> I argue that "Hard mode" is a "relaxation" of "Medium mode + no-scripting"

I disagree, in medium mode 3rd-party tracking pixels can be fetched.

**Comment by daniporr** [comment]
Thank you for your answer.

> I disagree, in medium mode 3rd-party tracking pixels can be fetched.

Obviously your statement is right, and I respect your view on this.
Actually, it made me notice that I used the wrong word in my previous comment (I was considering both privacy and security aspects).

But, I have also noticed that I wrote something wrong in my first comment (I have fixed it now).
The `blockingProfiles` `11111/#F00 11101/#F50 11010/#C0F 11001/#00F 00001` (i.e., "Hard mode + No scripting / #F00 red", "Hard mode / #F50 orange", "Medium mode + No scripting / #C0F violet", "Medium mode / #00F blue", "Default / grey") does not work as well, for the same reason that you explained in https://github.com/uBlockOrigin/uBlock-issues/issues/1718#issuecomment-918195803
Therefore, even the "relaxation" from "Hard mode (with scripting)" to "Medium mode + No scripting" cannot be performed with the current implementation.
Obviously, you can say that even this is not a "relaxation" (even if it is just the opposite of what you disagreed with in https://github.com/uBlockOrigin/uBlock-issues/issues/1718#issuecomment-918615682), and I understand the technical difficulties to implement it.

But I think that "Hard mode (with scripting)" and "Medium mode + No scripting" are both useful blocking modes, and it is a shame that you cannot have both of them (in any way) in the `blockingProfiles`.
Ideas on why they are useful:

- "Hard mode (with scripting)"
   - You trust the JS content of a site, but you do not want to load any 3rd-party content
   - Example: virustotal.com ; it needs to use JS, and it works perfectly with this mode (it does not need any external JS), but I do not want it to load any 3rd-party content (for instance, tracking pixels)
- "Medium mode + No scripting" 
   - You do not trust the JS content of a site or you simply do not want it to run because it is not needed (or to save bandwidth), but you want to load 3rd-party images
   - Example: almost any news website or blog ; most of them do not need to load JS if you simply want to read a news/blog post, but almost all of them need to load the images they use in the post from a 3rd-party (for instance, a CDN)

Do you think it make sense to allow both of them to be used in the `blockingProfiles`?
(I am not concerned about their order at the moment, so if you think this is a different "problem", I can open a another Issue to keep it tidy)

Thanks again for your help!
