### ISSUE TITLE
Using (The return of the overlay scrollbar flags) will make the extension crash

### ISSUE THREAD

**Issue by XTsat** [uBlockOrigin/uBlock-issues#1721]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I used Microsoft Edge version 95.0.1000.0 (official internal version) dev (64 bit)

I turned on (The return of the overlay scrollbar flags!) in (https://www.microsoftedgeinsider.com/zh-cn/whats-new) in (edge://flags/#edge-overlay-scrollbars-win-style) place is turned on, once I use the shielding element after turning it on, this extension will crash

### A specific URL where the issue occurs

@all

### Steps to Reproduce

edge://flags/#edge-overlay-scrollbars-win-style was be enabled
use uBlockOrigin Element selection filter mode
Click to block anywhere
The extensions was crash

### Expected behavior

I want to block ads on any page

### Actual behavior

The extensions was crash

### uBlock Origin version

1.37.2

### Browser name and version

Microsoft Edge version 95.0.1000.0 (official internal version) dev (64 bit)

### Operating System and version

Windows 10 Home 21H1 Operating system internal version 19043.1165

**Comment by gwarser** [comment]
You are using experimental feature in alpha version of the browser - report to browser dev if ever they accept such reports. uBO is a browser add-on based on web technologies it should not crash the browser.
