### ISSUE TITLE
Filter combining inconsistency between blockers

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1725]
I have noticed that there is an inconsistency between blockers when combining filters with a comma.

Adblock Plus, Adguard and uBlock Origin treat filters like this differently:

`iltalehti.fi#?#main div[class="card "], main .half-article:-abp-contains(Kaupallinen yhteistyö)`

ABP & uBO way to interpret:

`iltalehti.fi#?#main div[class="card "]:-abp-contains(Kaupallinen yhteistyö)`
`iltalehti.fi#?#main .half-article:-abp-contains(Kaupallinen yhteistyö)`

AG way to interpret:
`iltalehti.fi#?#main div[class="card "]`
`iltalehti.fi#?#main .half-article:-abp-contains(Kaupallinen yhteistyö)`

I'm not aware of any common place to discuss stuff like this so I'm opening an issue report here, and I'll tag representatives from each "section": @gorhill @ameshkov @WebReflection

What I'm trying to say is that could you consider doing some alignment/agreeing together how rules like that should be interpret so that it's interpret in the same way in all blockers? For those who try to maintain cross-blocker compatible filterlists, inconsistencies in interpretation are not a good thing.

Page where I tested filter interpretation: `https://www.iltalehti.fi/raha`

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/382#issuecomment-703735587

**Comment by gorhill** [comment]
> I'm not aware of any common place to discuss stuff like this 

Please open a [discussion](https://github.com/uBlockOrigin/uBlock-issues/discussions) about this, I want the issue tracker to be kept for actionable items.
