### ISSUE TITLE
Weird issues with removeparam and negated types

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uBlock-issues#1730]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBo is having some weird issues with removeparam.
See https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-1364155 for details
I have also tested in Tor Browser, and MS Edge on fresh install of Windows/uBo

### A specific URL where the issue occurs

http://example.com?test=tracker

### Steps to Reproduce

1. Add `example.com$~script,~xhr,removeparam=test` to the My Filters tab (also can reproduce for filters in filter lists, i.e. legit url shortener)
2. Go to the url
3. Note that test is not removed

### Expected behavior

`test` is removed

### Actual behavior

`test` is not removed

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Firefox 92.0

### Operating System and version

WinOS, and others

**Comment by gwarser** [comment]
This is working:

    example.com$all,~script,~xhr,removeparam=test

Probably something with `doc`.

**Comment by gwarser** [comment]
Does it work for other types than `doc`?

**Comment by iam-py-test** [comment]
I think so. I think it is just with only negated modifiers

**Comment by gwarser** [comment]
I mean, it's only the `document` type which is not working. Because of special handling in uBO.

If I use `example.com$~script,removeparam=test` fetching is properly cleaned:

![image](https://user-images.githubusercontent.com/886325/134254525-6fe4c602-f420-4241-b6e5-1772a3a887cc.png)

**Comment by iam-py-test** [comment]
Let me check....

**Comment by gorhill** [comment]
I will refactor how `~[type]` are implemented.

**Comment by felix-22** [comment]
> gorhill : I will refactor how `~[type]` are implemented.

<br>

(moved from https://github.com/uBlockOrigin/uBlock-issues/issues/1732#issuecomment-927124939) to avoid off-topic):
> felix-22 :
> 
> Is it expected now in 1.38.1b1 that each of these counts as 1:
> `||msn.com^$~image` 1 out 1
> `||msn.com^$~image,~xhr` 1 out 1
> 
> as compared to 1.37.2:
> `||msn.com^$~image` 10 out of 10
> `||msn.com^$~image,~xhr` 9 out of 9

<br>

> gorhill : Yes.

<br>

I've spotted another thing in counting, hence a similiar question: 
- is it expected to `||bad-website^$all,~script` showing the same old count 14 out of 14 filters in 1.38.1b1 like in 1.37.2?

**Comment by gorhill** [comment]
> is it expected to `||bad-website^$all,~script` showing the same old count 14 out of 14 filters in 1.38.1b1 like in 1.37.2?

Not expected, it should be 4 filters off the top of my head. I think I know why this happens, I will investigate and fix.

**Comment by krystian3w** [comment]
Inline-pictures (base64-img) only by cosmetic filter?

**Comment by felix-22** [comment]
> gorhill : Fix handling of negated types in all filter option https://github.com/gorhill/uBlock/commit/a6cd954a2aa892d9de8bcde1a001ab46040806c1

Works!

> krystian3w : Inline-pictures (base64-img) only by cosmetic filter?

Inline-pictures sit in DOM, not in network requests, in Firefox can use [cosmetic-HTML filtering](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters):
```
atlassian.com##^img[src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="]
```

**Comment by peace2000** [comment]
in this link: https://fin.afterdawn.com/uutiset/ when I open any of these news articles (scroll the page down a bit to see them):

![image](https://user-images.githubusercontent.com/17256841/135412000-48ea1d11-7828-4289-8eb7-a73c509b8e91.png)

I get this error
![image](https://user-images.githubusercontent.com/17256841/135412167-31cbf06c-2a6f-44db-9577-cc0e641561c0.png)

If I have this rule active:

`*$removeparam=sid,~script,~xmlhttprequest,domain=~mail.qq.com`

This behavior started after these changes. I'm running uBO 1.38.1b2. Latest stable version can open those links without any issues. Is this intentional behavior or regression? This can be reproduced in FF, Chrome and Edge.

@gorhill

**Comment by krystian3w** [comment]
You excluded breakage due too much clear websockets/beacon/image/stylesheet?

**Comment by gorhill** [comment]
> This behavior started after these changes

The defect fixed here was preventing you from seeing that removing `sid` from those links causes the 404. Just copy-paste the links and manually remove the `sid` parameter and you get the error, i.e.:

    https://high.fi/rd.cfm?rid=951&src=widget&med=7&hsh=884D3F82F86CC6058E59C2782BCEC970

**Comment by uBlock-user** [comment]
Site-issue, using `$removeparam` to remove a param will cause some sites to break.

**Comment by peace2000** [comment]
Oh, ok. Thanks! Just wanted to check that it works as it should.
