### ISSUE TITLE
Disable sending web addresses you visit to Google (Chrome/Edge/Chromium)

### ISSUE THREAD

**Issue by corobin** [uBlockOrigin/uBlock-issues#1731]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

privacy badger is mostly redundant with uB0 but on chromium based browsers it does has this one option:

> Disable sending web addresses you visit to Google. This disables suggestions for similar pages when a page can't be found. [(?)](https://www.google.com/chrome/privacy/#how-chrome-handles-your-information) 

is it suitable/within scope to add this into uB0? uB0 already has the other options that PB has.

thanks!

### A specific URL where the issue occurs

not a webpage thing

### Steps to Reproduce

1. open first settings page in pb to see the option

### Expected behavior

setting for `Disable sending web addresses you visit to Google. `

### Actual behavior

currently no setting for `Disable sending web addresses you visit to Google. `

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
I don't see any setting in Privacy Badger for this.

Closing as _invalid_. I will reopen if more details are provided which make the issue actionable.

**Comment by uBlock-user** [comment]
> I don't see any setting in Privacy Badger for this.

Only present in Chromium extension for Privacy Badger. Unfortunately PB devs never bothered to document this setting.

**Comment by gorhill** [comment]
> Only present in Chromium extension for Privacy Badger

I checked on Firefox since OP reported using Firefox.

Looking at Chromium version, I find that the browser setting is [`chrome.privacy.services.alternateErrorPagesEnabled`](https://developer.chrome.com/docs/extensions/reference/privacy/). I have to find more details about this setting before I make a decision.

**Comment by gorhill** [comment]
I can't find much beyond the above, there is no repro case demonstrating the usefulness of the Chromium-specific setting, so I will decline -- I can't add browser-specific features for which the purpose can't be clearly explained _and_ the effect demonstrated.

**Comment by gorhill** [comment]
Actually I will keep the _invalid_ label since the reported browser is Firefox for which the setting is irrelevant.

**Comment by uBlock-user** [comment]
> chrome.privacy.services.alternateErrorPagesEnabled.


As per `https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::AlternateErrorPagesEnabled` there's no privacy value attached to it.

**Comment by mapx-** [comment]
if it's about google search tracking I'm using Rob Wu's extension:

https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg

**Comment by corobin** [comment]
> It's `Use a web service to help resolve navigation errors` only present in Google Chrome, not Chromium itself.

Thanks for digging into this. The help link provided by PB just goes to the Google help docs about how they use your information.

> Actually I will keep the _invalid_ label since the reported browser is Firefox for which the setting is irrelevant.

Yeah sorry about the confusion. I didn't think about it and just wrote what I was using when posting this since it's not a bug with uB0, but you are correct it does not apply to Firefox, this only applies to the Chrome version.
