### ISSUE TITLE
Green Gray Red

### ISSUE THREAD

**Issue by VLM-TechEd** [uBlockOrigin/uBlock-issues#1733]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

A while ago, the green "allow" option was removed. I have read that this was done, because some users were "abusing" it. I am not now and never did "abuse" it. But the reality is that selecting dark gray does NOT let through all that it should. Right now, on THIS GitHub page, uBlock Origin is blocking 4 items. Yet everything that can be marked dark gray, is marked dark gray. This happens constantly; the old green setting didn't work 100% of the time, but it did resolve most such problems, which I consider errors. 

I know this has been discussed before, but this is not how the program is advertised to function, and I am therefore choosing to treat this as a bug rather than as a support issue.

Please, either make the dark gray work all the time or bring back the green.  Thank you.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=bug_report.yml

### Steps to Reproduce

1. Tried with uBlock O set to OFF (by clicking on the blue icon). Everything gets through.
2. Tried with uBlock O set to ON and every item with a minus sign set to dark gray. 4 items blocked.
3. Tried same (1&2) on many websites. Specific items blocked vary from site to site, of course, but uBlock O behavior remains constant. 

### Expected behavior

I expected dark gray to let things through. It didn't on this GitHub page and it doesn't do so on most web pages I visit. 

### Actual behavior

Redundant item.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0.1

### Operating System and version

Windows 10 Home

**Comment by uBlock-user** [comment]
> I expected dark gray to let things through.

Read the wiki on noop - https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#noop-rules

**Comment by VLM-TechEd** [comment]
First, thank you for responding so quickly. I appreciate it!

 

I read the page (not for the first time). 

 

100% of my rules are noop rules. Four of them apply to GitHub:

 

github.com * 3p-script noop

github.com github.com * noop

github.com githubapp.com * noop

github.com githubassets.com * noop

 

When I search my filters for “github”, nothing is found; ergo, I have no known filters for GitHub.

 

I use no extra or custom filter lists. 

 

Nonetheless, when I am on GitHub, and including your GitHub page, I routinely see 4 blocked items. When we users had green (affirmative rules, I suppose), we could address noop rules that appeared to fail (regardless of whether they actually failed in a technical sense). Now, we can’t, at least not in way I can see. 

 

I’m trying to provide as much information as I can think to provide. Again, I appreciate your kind help.

 

Best regards,

**Comment by uBlock-user** [comment]
`noop` only disables dynamic filtering, static filters still apply. `allow` overrides static filtering rules. Everything is explained in the wiki. Read it completely.

**Comment by gwarser** [comment]
> 100% of my rules are noop rules. Four of them apply to GitHub:

You are doing it wrong. It seems you don't need dynamic filtering at all - just turn advanced user mode off. Instead just click big blue power button in uBO popup when on GitHub.

**Comment by VLM-TechEd** [comment]
Yes, this works for GitHub, as I said in my submission. However, this does not work for many sites that use all manner of trackers and such. One might wish, for example, to let through everything from Cloudflare but not some other things. In such cases, which are quite numerous, dynamic filtering can be helpful, even “necessary”, though that is obviously a judgment call. My point is simply this: that each user should be presumed to be fully capable of making such choices for him-/herself. Removing allow/green takes this choice away; it seems to presume that many users are incompetent, which, in general, they are not.

**Comment by gorhill** [comment]
> Removing allow/green takes this choice away;

You are not reading the documentation as [pointed out to you](https://github.com/uBlockOrigin/uBlock-issues/issues/1733#issuecomment-927015198):

> The only way to enable the ability to point-and-click to create allow rules is to either:
> 
> - Tap twice on the Ctrl key while in the popup panel
>     - This won't work in Firefox when privacy.resistFingerprinting is set to true
> -Set filterAuthorMode to true in advanced settings
> 
> Doing so will enable the allow rule creation widget in the popup panel:

Locking this thread now, there is no point to keep repeating over and over to read the documentation, and merely repeating here what the documentation says is wasting volunteers' limited time.
