### ISSUE TITLE
invalid syntax for nodejs import in readme

### ISSUE THREAD

**Issue by DetachHead** [uBlockOrigin/uBlock-issues#1734]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

the nodejs module import syntax [here](https://github.com/gorhill/uBlock/blob/master/platform/nodejs/README.md#usage) is incorrect

i removed it in my fork but i can't make a PR https://github.com/DetachHead/uBlock/commit/9887cbe429edf65a2faad4e206e8e73e21e4fc57

![image](https://user-images.githubusercontent.com/57028336/134758998-523c8792-8f98-41eb-b9d0-eaa92157caad.png)

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/platform/nodejs/README.md#usage

### Steps to Reproduce

n/a

### uBlock Origin version

n/a

### Browser name and version

n/a

### Operating System and version

n/a

**Comment by gorhill** [comment]
[Here](https://nodejs.org/api/esm.html#esm_require) it says:

> Using `require` to load an ES module is not supported because ES modules have asynchronous execution. Instead, use `import()` to load an ES module from a CommonJS module.

**Comment by gorhill** [comment]
Does the following work?

    const { StaticNetFilteringEngine } = await import('@gorhill/ubo-core');

**Comment by DetachHead** [comment]
yeah that works.

also if i may ask, how would i be able to contribute to the repository if creating PRs is limited to people who have contributed in the past?

**Comment by gorhill** [comment]
The first time I can cherry-pick a commit if I agree with the change. That would make you a contributor at that point.
