### ISSUE TITLE
Feature Request: Sync uBO settings between two (or more) browsers

### ISSUE THREAD

**Issue by aksarz** [uBlockOrigin/uBlock-issues#1744]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Hi,

I use LibreWolf and Ungoogled Chromium for daily tasks. In both I have uBO in medium blocking mode, so I constantly have to modify filtering list to unbreak sites. 

Right now there is no way that changes made on Browser1 uBO settings reflects on Browser2 uBO settings.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Open Browser1 and open a site that breaks with current uBO dynamic filtering list.
2. Unbreak the site by changing dynamic rules.
3. Open Browser2 and open the same site.
4. You must change the rules again to unbreak the site.

* Here labels 'Browser1' and 'Browser2' are used merely with an identification purpose. Real browsers (even more than 2) are interchangeable in this description.  

### Expected behavior

0. uBO comes with an opt-in setting that says, approximately: "When you click on the Lock icon, current settings are made permanent and exported to a local file. Every time the browser starts, uBO will import the settings from this file". There is also the option to create/select this file.
0.1 Both (or more) browsers in PC have this option enabled and point to the same file. 
1. Open Browser1 and open a site that breaks with current uBO dynamic filtering list.
2. Unbreak the site by changing dynamic rules.
3. After clicking the Lock icon, uBO saves the current settings and export them to a local file (ex. my-ublock-dynamic-rules-local-sync.txt)
3. Open Browser2 and open the same site.
4. The site is unbroken. 

* Why use local sync instead online sync?
– My browsers have sync feature disable by default. 
– Even if they had it enabled and I used it, Firefox and Chromium-based browsers sync to different servers. Local sync would allow universal browser compatibility. 
– It's faster.
– It saves bandwidth.
– It's better for privacy.

* Note that I suggest uBO to export settings to local file every time they are updated, but only import them when browser starts. It would be even better if there's a way that both browsers' uBO to be synced in real time, without a significant increase of resources.

### Actual behavior

Described in Steps to Reproduce.

### uBlock Origin version

1.37.2

### Browser name and version

LibreWolf 92.0.1 (64-bit) and Chromium 89.0.4389.114 (Developer Build, ungoogled-chromium) (64-bit)

### Operating System and version

Windows 10 Pro 1909

**Comment by gwarser** [comment]
Not all browsers allow add-ons to read files from disk (Firefox). Use custom filter list and host it where you like.

**Comment by gwarser** [comment]
Sync by external service was declined https://github.com/gorhill/uBlock/issues/2468

**Comment by aksarz** [comment]
So, there is no way to sync settings from Firefox and Chromium-based browsers?

**Comment by uBlock-user** [comment]
Use Back Up/Restore functionality present in settings pane.

**Comment by aksarz** [comment]
That has to be made manually every time. Non-functional.

**Comment by Write** [comment]
WebDav support would be really awesome, but I assume it's considered as an 'External' service ?
