### ISSUE TITLE
Trusted site directive `view-source-scheme` does not work

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uBlock-issues#1745]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Unable to view source code of websites which are blocked in uBO, 
adding trusted site directive `view-source-scheme` does not work.

https://en.wikipedia.org/wiki/View-source_URI_scheme

If it turns out this is a bug, consider fixing it.

If it turns out this is by design, I guess it might be due to some security bugs as described in the Wikipedia link? But in this case, maybe all the security bugs have been fixed already, and there is no risk anymore, in this case consider adding support for trusted site directive `view-source-scheme` Also consider adding it to [predefined directives ](https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites#important-read-carefully)

### A specific URL where the issue occurs

`view-source:https://example.com/`

### Steps to Reproduce

1. Visit `view-source:https://example.com/` (or alternatively visit `https://example.com/` and right click mouse button anywhere on the website and from the context menu choose "show source code")
2. Notice the source code can be viewed
3. Use uBO [the big power](https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#click-the-big-power-button) to create trusted site directive
4. Notice in uBO Dashboard > Trusted directives, that the trusted site directive `view-source-scheme` has been successfully created
5. Add filter `||example.com^$doc` or `||example.com^` to uBO My Filters
6. Visit the `view-source:https://example.com/` again
7. Notice that it gets blocked despite it's allowed in Trusted directives, in result an user is unable to view a source code of websites which are blocked in uBO.

### Expected behavior

`view-source-scheme` trusted site directive to work

### Actual behavior

`view-source-scheme` trusted site directive does not work

### uBlock Origin version

1.38.1b2

### Browser name and version

FF 92.0.1 / O 78

### Operating System and version

Windows 7 64 SP1

**Comment by gorhill** [comment]
Doesn't seem fixable, the network request for the source code of the document is indistinguishable from the network request for the document itself -- nowhere is there a hint that the network request is for the purpose of `view-source:`.
