### ISSUE TITLE
Strict-block enable button / hot-key

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uBlock-issues#1746]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In this declined issue: https://github.com/gorhill/uBlock/issues/1255 I basically agree with the reply, however, the argumentation addressed only disabling strict-blocking (we have uBO's block page for disabling strict-blocking), still there should be an easy & quick way to enable strict-block for a bad / unwanted site / page, other than:
- 1 enabling the logger, 
- 2 reloading the site, and 
- 3 creating the $doc rule via the logger

If not a small button, then what will satisfactory? 
- a simple hotkey in uBO's hotkeys pane?
![rrr](https://user-images.githubusercontent.com/75935068/135726035-37d4ebeb-90c2-42b5-aa4a-69c6724d54b9.png)

- or maybe, instead of to add a small button, just to add the strick-block feature to the already existing [big power button](https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#click-the-big-power-button) when `Shift` pressed, with a tooltip: 
   - "Shift+click to stric-block this site" ==> `||page.com^$doc` filter added to My Filters
   - "Shift+Ctrl click to strict-block this page" ==> `||page.com/subpage$doc` filter added to My Filters
(the hot-keys are just example)

Example image:

![1](https://user-images.githubusercontent.com/75935068/135724207-08459411-0b2e-4ed8-90a1-da747757b731.png)

### A specific URL where the issue occurs

https://example.com/

### Steps to Reproduce

1. Visit any website
2. Imagine it has turned out this is a bad / unwanted site and you want to never visit it anymore and you just want to easy & quickly strict-block it.
3. Realise there is no easy & quick way (a button), and the only way is cumbersome via the logger.

### Expected behavior

Possibility to easy & quickly strict-block a bad/unwanted site / page, other than the current cumbersome way via the logger.

### Actual behavior

No possibility to easy & quickly strict-block a bad/unwanted site / page, the current way via the logger is cumbersome.

### uBlock Origin version

1.38.1b2

### Browser name and version

FF 92.0.1 / O 78

### Operating System and version

Windows 7 64 SP1

**Comment by gorhill** [comment]
Declined, you are asking to complicate the code and UI for something which is quite uncommon and trivial to deal with: close the tab and don't visit the site anymore. With #1681 I will probably remove the temporary bypass when the tab is closed.

**Comment by felix-22** [comment]
> is quite uncommon and trivial to deal with: close the tab and don't visit the site anymore. 

Then why all the badware filters like: uBO Badware Risks, Online Malicious URL Blocklist and all badware hosts lists in the whole internet, and the whole strict-blocking feature in uBO? I completely don't get this part of your reply, it's like: why do you need a bike, when you can just walk.
