### ISSUE TITLE
Swap true/false colors for no-cosmetic-filtering

### ISSUE THREAD

**Issue by d07434b2c08f** [uBlockOrigin/uBlock-issues#1747]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

A minor complaint, but the highlighting for `true` and `false` for `no-cosmetic-filtering` seems inconsistent when compared to the other "no" rules:

`no-cosmetic-filtering: * true`: all DOM **allowed**
`no-csp-reports: * true`: all CSP reports **blocked**
`no-large-media: * true`: all large media **blocked**
`no-popups: * true`: all popups **blocked**
`no-remote-fonts: * true`: all remote fonts **blocked**
`no-scripting: * true`: all JavaScript **blocked**

Every `true` in the above rules will be highlighted red, despite `no-cosmetic-filtering` having "allow" behavior.

### A specific URL where the issue occurs

http://example.com

### Steps to Reproduce

1. Go to uBlock<sub>o</sub> Dashboard → My Rules
2. Add a `no-cosmetic-filtering` rule
3. `true` will be highlighted red, `false` will be highlighted green

### Expected behavior

`no-cosmetic-filtering: * true` should have `true` colored green
`no-cosmetic-filtering: * false` should have `false` colored red

### Actual behavior

`no-cosmetic-filtering: * true` has `true` colored red
`no-cosmetic-filtering: * false` has `false` colored green

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
See `no-cosmetic-filtering: * true` as "blocking cosmetic filtering".
