### ISSUE TITLE
Minor typo in each release note

### ISSUE THREAD

**Issue by Eagle3386** [uBlockOrigin/uBlock-issues#1748]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Each release's `Notable commits` section has a minor typo. I totally admit, it's a very minor issue.
Nonetheless, it's an issue that should be fixed & due to no file to be editable & in turn ready for a PR, all I can do is open this issue...

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/releases

### Steps to Reproduce

1. Go to the specific URL given.
2. Pick any (recent) release.

### Expected behavior

Each release with a `Notable commits` section states:
> Notable commits without an entry in the issue tracker

### Actual behavior

Each release with a `Notable commits` section states:
> Notable commits without en entry in the issue tracker

### uBlock Origin version

1.38.2

### Browser name and version

Firefox Dev Edition 93b9 x64

### Operating System and version

Win 10 Pro 21H1 x64

**Comment by gorhill** [comment]
Oops. Fixed in all releases.
