### ISSUE TITLE
Mixer FTL mode not working when uBlock Origin is enabled

### ISSUE THREAD

**Issue by KatouMegumi-osu** [uBlockOrigin/uBlock-issues#175]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Mixer's (Game livestreaming platform) FTL (low latency) livestream mode is not working when uBlock Origin is present at all. Disabling each filter didn't solve the issue, aswell as disabling the extension in its window for the Mixer website.

Note: It's not a filter issue, as forcefully disabling uBlock Origin in the "Extensions" menu in Google Chrome fixed the issue I was having with the website.
### A specific URL where the issue occurs
https://mixer.com - the website.
https://mixer.com/vvspaceship - 24/7 livestream with FTL mode support.
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Go to a Mixer livestream
2. [Enable the "Low latency" mode in the player settings (cog icon)](https://puu.sh/BhqVE.png)

### Expected behavior:

The livestream being displayed when "Low latency" mode is enabled
[What you expected to happen]

The livestream being displayed when "Low latency" mode is enabled
### Actual behavior:
Don't get the question.
[What actually happened]
Infinite loading when "Low latency" mode is enabled 
### Your environment

* uBlock Origin version: 1.16.16 (Google Chrome store)
* Browser Name and version: Google Chrome, 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
* Operating System and version: Windows 10 Single Language, 17134.228

**Comment by uBlock-user** [comment]
Where's the cog icon located ? That miniscule picture does not help.

**Comment by uBlock-user** [comment]
Low Latency is enabled by default, and it plays some times and then it doesn't. Looks like a connectivity issue.

**Comment by uBlock-user** [comment]
If I disable Low Latency it starts playing immediately, so not a uBlock issue, this is a server issue and out of uBO's scope.

**Comment by uBlock-user** [comment]
WebRTC issue. Toggling _Prevent WebRTC from leaking local IP addresses_  off in uBO settings, makes it work again.
