### ISSUE TITLE
Cosmetic filters not working on many websites with "Experimental Web Platform features" in `chrome://flags`

### ISSUE THREAD

**Issue by sauravyad500** [uBlockOrigin/uBlock-issues#1751]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
https://timesofindia.indiatimes.com/home/education/news/upsc-indian-forest-service-mains-interview-schedule-announced/articleshow/86091072.cms
https://www.ndtv.com/india-news/farmers-call-off-agitation-in-up-after-promises-of-compensation-2563188#pfrom=home-ndtv_topscroll
```

### Describe the issue

The cosmetic filters that I apply manually via "Element picker mode" are saved in my filter lists. When I click on preview, the selected element disappears from the page. After clicking on pick and reloading the page, those same elements appear again. There is no change in their class or id. I had checked in the filter list also, they are there.

These are some of the websites on which it is not working.

### uBlock Origin version

1.38.2

### Browser name and version

Microsoft Edge	96.0.1033.0 (Official build) canary (64-bit)

### Settings

! 2021-10-05 https://timesofindia.indiatimes.com
timesofindia.indiatimes.com##.article-content-wrapper.clearfix.wrapper > .sidebar

in the filter list and javascript is also blocked in the ublock origin for this website

### Notes

This seems to be some issue with filter lists as after every alternate update my filters break. Facing this problem since 1.37 has been launched.

**Comment by uBlock-user** [comment]
> After clicking on pick and reloading the page, those same elements appear again.

https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page

**Comment by uBlock-user** [comment]
> After clicking on pick and reloading the page, those same elements appear again.

https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page

**Comment by gorhill** [comment]
Since I can't reproduce, whoever can reproduce such issue will have to investigate the cause of it.

**Comment by gorhill** [comment]
> manual custom filters don't work when I check this option

So possibly I might be able to reproduce if I have the same custom filters? Can you share?

**Comment by gorhill** [comment]
> Facing this on two more sites https://www.coolztricks.com/

I went to `https://www.coolztricks.com/` in Microsoft Edge (dev) 95.0 for linux, created the filter `www.coolztricks.com##.inside-right-sidebar` to remove the right-hand side bar, forced a reload of the page, and the side bar was properly hidden as expected. Using default up to date filter lists and settings.

**Comment by PatchMixolydic** [comment]
After following those instructions, the Twitter trends sidebar was blocked successfully. After some trial and error, it seems like using any of these filters (alone or together) breaks custom filters (but not the default filters):
```
twitter.com##div[aria-label^="Timeline:"]:not([aria-label$="Topics"]):not([aria-label$="Explore"]) .r-qklmqi:has([aria-labelledby*="topic-not-interested-button"])
twitter.com##div[aria-label^="Timeline:"]:not([aria-label$="Topics"]):not([aria-label$="Your Lists"]) .r-1adg3ll:has(div[aria-label="Timeline: Carousel"])
twitter.com##div[aria-label^="Timeline:"]:not([aria-label$="Lists"]):not([aria-label$="List"]) div[style^="position: absolute;"]:not(:has(article)):has(a[href^="/i/lists/"])
twitter.com##div[aria-label="Timeline: Your Lists"] div[style^="position: absolute;"]:has(a[href="/i/lists/suggested"])
```

None of these seem to be related to the trends bar from a quick glance (they are intended to block various other nuisances). Should I file this as a separate issue, or is this expected behaviour given the structure of the Twitter website?

**Comment by sauravyad500** [comment]
Found the culprit. For me whenever I use filter list named "**AdGuard Base**" with "**Parse and enforce cosmetic filters**" as checked, I face the issue. And when I uncheck the "**AdGuard Base**". The issue disappears.

**Comment by felix-22** [comment]
I only mean in case he believes that uBO's filter lists are the source of the problem.

**Comment by MiaowMinx** [comment]
> **Edit:** I seem to be having a similar issue on https://old.reddit.com: promoted posts (ads) aren't filtered. The filter `reddit.com##.promotedlink` should do it, and I believe it should be in one of the filter lists, but the ads still appear. Sidebar ads, however, are blocked. This seems to be caused by the "uBlock Filters" list; disabling it and enabling the other default filters seems to remove promoted posts even without a custom filter.

I'm running into the exact same problem with the "uBlock Filters" list on old.reddit.com — I can filter out .promotedlink and .premiumbanner if any of the other 'built in' lists are active, but as soon as I load the page with uBlock Filters on, my cosmetic filters on Old Reddit fail.  (In case it matters, I'm using Vivaldi on Linux, and have tried removing/re-installing uBlockOrigin.)

**Comment by jeremywho** [comment]
> I'm running into the exact same problem with the "uBlock Filters" list on old.reddit.com ... uBO will hide .promotedlink and .premiumbanner as asked only if "uBlock Filters" is turned off; none of the other 'built-in' filter lists have that effect. (edited for clarity)

+1

Same thing happening here.

**Comment by gorhill** [comment]
@jeremywho 

Thanks. Can you provide me with an exact URL where you can reproduce the issue? If I have an exact URL, I won't worry that I am trying to reproduce an issue which could depend on something very specific on a very specific page.

**Comment by gorhill** [comment]
When the issue occurs, any errors in the dev console of Reddit or uBO itself?

**Comment by gorhill** [comment]
When I select a promoted post (which is properly hidden on my side) in the DOM, I can confirm that there is a stylesheet injected by uBO:

![Screenshot from 2021-10-21 15-52-30](https://user-images.githubusercontent.com/585534/138358539-3e849ec6-ccfe-4b82-b4c7-b2da1ce0c14f.png)

Do you see such stylesheet on your side?

**Comment by GitExploraa** [comment]
using Edge V97 here, whenever i go to goodreads.com and i hide the top banner with cosmetic filtering), upon refreshing the site it appears again, i'm only using the base filters
![image](https://user-images.githubusercontent.com/44654056/152134570-8f321277-de8e-4a66-a102-40ee165009a3.png)
![image](https://user-images.githubusercontent.com/44654056/152134654-f6007eaa-0cf7-45b1-acfe-b92827564f22.png)

**Comment by arunmeena06** [comment]
I am not proposing adding any of the exceptions in a filter list, I am just trying to understand how those exception filters are have any effect. For this I need to first know which one to investigate.

[Geeks Apk
](https://geeksapk.com/)
