### ISSUE TITLE
ublock 1.38.3b0 and beta 1 not signed for Firefox

### ISSUE THREAD

**Issue by Flauschi1981** [uBlockOrigin/uBlock-issues#1753]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

ublock 1.38.3b0 and beta 1 not signed for Firefox

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/releases/download/1.38.3b1/uBlock0_1.38.3b1.firefox.signed.xpi

### Steps to Reproduce

https://github.com/gorhill/uBlock/releases/download/1.38.3b1/uBlock0_1.38.3b1.firefox.signed.xpi

404

### Expected behavior

ublock 1.38.3b0 and beta 1 not signed for Firefox

### Actual behavior

ublock 1.38.3b1 and beta 0 not signed for Firefox

### uBlock Origin version

ublock 1.38.3b0 and beta 1

### Browser name and version

Firefox 94 beta 2

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
You did the same in the past (<https://github.com/uBlockOrigin/uBlock-issues/issues/934>), please avoid doing so again in the future.
