### ISSUE TITLE
Blank page when using logger and selecting </> button

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#1765]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

    Firefox 93.0
    Ubo 1.38.7b1/1.38.7b0
    Default lists
    Happens on both current and new profile
    Other addons, Cookie Autodelete, Bypass Paywall clean, localCDN, Flagfox

When accessing the logger and selecting the </> button leaves a blank page, no entries at all just completely blank. https://i.postimg.cc/502QjPzh/ublockerror.png
It seems o do this only on the latest Dev build Ubo 1.38.7.b0/1 did not happen on 1.38.5b2 and not sure about stable as I am not using that.

### A specific URL where the issue occurs

All

### Steps to Reproduce

go to any web site
open logger
selsect </>
blamk page

### Expected behavior

Should display content

### Actual behavior

Blankpage

### Configuration

    browserFlavor: ublock webext devbuild firefox user_stylesheet html_filtering mozilla
    browserVersion: 93,
    extensionName: uBlock Origin
    extensionVersion: 1.38.7b1
    modifiedUserSettings: 
      advancedUserEnabled: true,
      showIconBadge: false,
      webrtcIPAddressHidden: true
    modifiedHiddenSettings: 
      autoCommentFilterTemplate: none
      cacheStorageAPI: browser.storage.local
      consoleLogLevel: info
      extensionUpdateForceReload: true,
      filterAuthorMode: true,
      filterOnHeaders: true,
      manualUpdateAssetFetchPeriod: 250,
      updateAssetBypassBrowserCache: true,
      userResourcesLocation: [redacted]
    listset: 
      removed: 
        plowe-0: null
      added: 
        https://gist.githubusercontent.com/troysjanda/21dc11d85866fd3e4d7d43c38bf17add/raw/a9cbfa4c0469aba2ed320993001187ca0fe2d456/disqus%2520ctl%2520filter%2520list.txt: 
          filters used/total: 6 / 6
          updated last/next (days): -1.86 / 28.14
        https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 
          filters used/total: 441 / 448
          updated last/next (days): -1.86 / 8.14
        https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 
          filters used/total: 510 / 510
          updated last/next (days): -1.86 / 8.14
        https://www.i-dont-care-about-cookies.eu/abp/: 
          filters used/total: 23793 / 23803
          updated last/next (days): -1.86 / 1.14
        adguard-spyware-url: 
          filters used/total: 306 / 306
          updated last/next (days): -1.86 / 2.14
        block-lan: 
          filters used/total: 43 / 43
          updated last/next (days): -1.86 / 28.14
        fanboy-cookiemonster: 
          filters used/total: 11895 / 20229
          updated last/next (days): -1.86 / 7.14
        fanboy-social: 
          filters used/total: 23295 / 23310
          updated last/next (days): -1.86 / 2.14
        ublock-annoyances: 
          filters used/total: 4141 / 4266
          updated last/next (days): -1.86 / 2.14
      default: 
        ublock-filters: 
          filters used/total: 29625 / 29656
          updated last/next (days): -1.86 / 2.14
        ublock-badware: 
          filters used/total: 2961 / 2962
          updated last/next (days): -1.86 / 2.14
        ublock-privacy: 
          filters used/total: 171 / 171
          updated last/next (days): -1.86 / 2.14
        ublock-abuse: 
          filters used/total: 67 / 67
          updated last/next (days): -1.86 / 2.14
        ublock-unbreak: 
          filters used/total: 1688 / 1689
          updated last/next (days): -1.86 / 2.14
        easylist: 
          filters used/total: 59284 / 59480
          updated last/next (days): -1.86 / 2.14
        easyprivacy: 
          filters used/total: 25434 / 25491
          updated last/next (days): -1.86 / 2.14
        urlhaus-1: 
          filters used/total: 16970 / 16970
          updated last/next (days): -0.71 / 0.29
    trustedset: 
      added: [array of 35 redacted]
    filterset: [empty]
    hostRuleset: 
      added: [array of 45 redacted]

**Comment by uBlock-user** [comment]
DOM Inspector is broken, changes in DOM Inspector were last made in https://github.com/gorhill/uBlock/commit/1285f78e0597241a2d186c00227c15f4e83ed9ec

**Comment by gorhill** [comment]
Unable to reproduce. I went to `https://www.theglobeandmail.com/canada/article-most-canadians-believe-facebook-harms-their-mental-health-survey-2/`, opened the logger, click the `</>` icon, and the DOM content was properly rendered in the DOM inspector.

**Comment by troysjanda** [comment]
Happen in nightly as well with same Ubo and no other addons.  Also happens with librewolf

**Comment by gorhill** [comment]
Ok, I was testing on stable Firefox, which I use strictly to test the dev build, and I believe the dev build had not been updated when I tested the first time. I can reproduce on Firefox as well.

**Comment by peace2000** [comment]
Noticed this issue too. Downloaded the latest dev version, logger works now normally.
