### ISSUE TITLE
uBlock Origin blocking elements issuse

### ISSUE THREAD

**Issue by Alex-Mirov** [uBlockOrigin/uBlock-issues#1769]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock Origin won't let select element block properly.

### A specific URL where the issue occurs

https://www.google.com/search?q=ps5&client=firefox-b-d&tbm=shop&ved=2ahUKEwi44_DWstTzAhWTJzQIHUFODcUQ_AUoAXoECAEQAw

### Steps to Reproduce

1. Right Click
2. Select "Block element
3. Hover with mouse to select which element to block in red.

### Expected behavior

Hovering with the mouse should let select any element at the page in red.

### Actual behavior

Hovering with the mouse let only select images in red.

### uBlock Origin version

1.38.6

### Browser name and version

FIrefox: 93.0 (Windows) , 68.11.0 (Android)

### Operating System and version

Windows 10, Android 9

**Comment by gorhill** [comment]
It's because the EasyList filter `@@||www.google.*/search*tbm=shop$elementhide`, it prevents cosmetic filtering from applying on the page, and so the element picker won't let you create a filter which uBO can't enforce.
