### ISSUE TITLE
uBlock Origin Controls Inoperable in Chrome Canary (70)

### ISSUE THREAD

**Issue by liamwli** [uBlockOrigin/uBlock-issues#177]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using uBlock Origin in Chrome Canary (70.0.3528.0) on macOS Mojave, none of the controls in the extension menu will work - they're not showing as clickable elements.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Install uBlock Origin in Chrome Canary
2. Open menu by clicking uBlock Origin icon next to address bar
3. None of the usually clickable elements are clickable

### Expected behavior:

The clickable elements are clickable

### Actual behavior:

None of the clickable elements are clickable.

### Your environment

* uBlock Origin version: 1.16.16
* Browser Name and version: Chrome Canary (70.0.3528.0)
* Operating System and version: macOS Mojave (10.14 Beta)

**Comment by gorhill** [comment]
I don't support Canary. Please test in Chrome dev or stable.

**Comment by uBlock-user** [comment]
Probably a broken build of Canary on macOS, downgrade to stable or a working build, not a uBO issue.
