### ISSUE TITLE
Open the dashboard by clicking in the popup panel title bar, as uMatrix does

### ISSUE THREAD

**Issue by siebenmann** [uBlockOrigin/uBlock-issues#178]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uMatrix has a handy feature where if you click anywhere in the black title bar at the top of its popup panel, it opens its settings dashboard. This is handy because, among other things, the title bar is a nice big target that's easy to click on. uBlock also has a title bar at the top of its popup panel, which as far as I can tell currently doesn't do anything. It would be nice if clicking on this title bar opened uBlock's dashboard (in addition to the current icon for it).

### Your environment

* uBlock Origin version: 1.16.16
* Browser Name and version: Firefox 61.0.2, Chrome 68.0.3440.106
* Operating System and version: Fedora 28 (64-bit x86)

**Comment by uBlock-user** [comment]
Actually it used to be like this before, but once the settings cog icon was removed, a separate dashboard icon was added in the popup UI, the change hasn't been made into uMatrix yet.

**Comment by uBlock-user** [comment]
> his extra mode could be made available via advanced settings window.

Most likely won't happen, but if gorhill were to entertain this, I would vouch for adding an advanced settings flag.

**Comment by BilBg** [comment]
And/or add possibility to assign Shortcut for "Open the dashboard" (like the other 3 Shortcuts for zapper, picker, logger)

**Comment by ReporterX** [comment]
Why not both? There is no action attached to the title bar. It does not hurt to attach an action there.

I'm used to the uMatrix way, so I clicked on there to find out I couldn't open dashboard in this way in uBlock.

**Comment by rob-3** [comment]
I've implemented the desired behavior (though there is no option to disable) [here](https://github.com/rob-3/uBlock). What is @gorhill's merge policy?

**Comment by gwarser** [comment]
Title bar no longer exists in new design:

![new popup design](https://user-images.githubusercontent.com/886325/80711045-04785300-8af0-11ea-9141-a62ab7717541.gif)
