### ISSUE TITLE
Ublock origin not working in youtube on chromebook running Chrome OS version 94

### ISSUE THREAD

**Issue by sandymanu** [uBlockOrigin/uBlock-issues#1780]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

This is fresh HP Chromebook running Chrome OS version 94. Ublock origin works on every other site bar youtube. On youtube page it shows 0 ads blocked and ads come on every video I play.

I have not modified filters and it's the default setting. I have done all basics like clearing cookies / reinstalling the extension and other basics like those, but the ads are not disappearing.

### A specific URL where the issue occurs

`www.youtube.com`

### Steps to Reproduce

1. Just open youtube on chromebook running chrome OS
2. Ads appear in homepage and upon clicking on any video.

### Expected behavior

Ads should be blocked as normal.

### Actual behavior

Youtube ads are not getting blocked

### uBlock Origin version

1.38.6

### Browser name and version

Chrome (version 94)

### Operating System and version

Chrome OS (version 94)

**Comment by iam-py-test** [comment]
I can’t even reproduce this issue on ChromeOS with updated filters
