### ISSUE TITLE
Twitch bypass is circumvented, should now be removed to prevent repeated ads.

### ISSUE THREAD

**Issue by saucettv** [uBlockOrigin/uBlock-issues#1789]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The scriptlet that blocked Twitch ads is now circumvented by Twitch. The issue now is that because UBlock is using the same device ID when requesting the video access token, the Twitch ad rate limit is not being imposed on that whitelisted device ID. Each refresh of a page after an ad is now shown, will repeat an ad because it does not apply a rate limit on Twitch's side. 

Without UBlock enabled, once an ad is shown, a refresh of a page will not show an ad for a specified time limit.

The device ID bypass should now be removed to prevent excess ads.

https://github.com/gorhill/uBlock/commit/cc0008df57459aaeae9305a03a887a3c4c55675b
https://github.com/gorhill/uBlock/commit/0d3a1932e998c0cb3f4c5ff1d9a3fe62e12a3cf4

### A specific URL where the issue occurs

twitch.tv

### Steps to Reproduce

1. Go to a Twitch channel with a pre-roll ad.
2. Watch it fully.
3. Refresh page and notice another ad shows.
4. Disable UBlock and repeat the above steps and after a refresh of the page, an ad does not show because the rate limit is correctly applied.

### Expected behavior

The Twitch ad rate-limit should be applied, however it seems Twitch has now blocked the whitelisted device ID that was being used.

### Actual behavior

Ad rate limit is not applied because of the set device ID being different to a normal user device ID. As the old whitelisted device ID is now no longer whitelisted, is should be removed.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox (Latest Stable)

### Operating System and version

Windows 10

**Comment by uBlock-user** [comment]
Still works fine at `https://www.twitch.tv/esl_csgo`

**Comment by Nojuuu** [comment]
Still work fine for me too.

**Comment by saucettv** [comment]
https://www.twitch.tv/burkeblack has pre-roll ads. You can force it by deleting the cookies, 'unique_id_durable' and 'unique_id' and refreshing the page. It could be that this is region based and they are slowly blocking it. I can confirm though that it was blocking ads about a week ago for me and is now no longer blocking ads. I've also confirmed that the whitelisted device ID is being used in the network connections.

This was also tested on a logged in Twitch account.

Anyone affected by it is currently getting more ads with UBlock, than without it.

**Comment by saucettv** [comment]
Or cohhcarnage

**Comment by gorhill** [comment]
We should just comment out [the filter](https://github.com/uBlockOrigin/uAssets/blob/053374c10dd4b1193c6a75b91314bbe47fdc3e05/filters/filters.txt#L5209) for now.

**Comment by Nojuuu** [comment]
Wouldn't it be better to wait until more people confirm this issue?

**Comment by gorhill** [comment]
Yes, but there has been [many complaints recently about Twitch ads](https://www.reddit.com/r/uBlockOrigin/comments/qbbxjq/twitch_ads_are_back/).

**Comment by gorhill** [comment]
Personally I am not getting ads at the suggested URLs, but I might not wait long enough, or it might be that I am not logged out.

**Comment by uBlock-user** [comment]
Commented out for now...

**Comment by gorhill** [comment]
When I except the filter on my side, I now do get ads at `https://www.twitch.tv/esl_csgo`, so this makes it difficult to know what's the best move.

**Comment by uBlock-user** [comment]
> I now do get ads

Yes, I experience the same thing, so I added the filter to my filters too so atleast I won't have experience ads, lets see how users react to this change.

**Comment by saucettv** [comment]
It might be worth trying different regions. I'm EU. https://www.reddit.com/r/uBlockOrigin/comments/qbbxjq/comment/hh9mw95/?utm_source=share&utm_medium=web2x&context=3

**Comment by uBlock-user** [comment]
Tried them once that thread was posted, the problem there is some users still didn't bother to disable external twitch adblockers which could lead to issue you present here.

**Comment by gorhill** [comment]
It's just not external blockers which could interfere, people also need to be sure there is no leftover of old solutions in uBO, i.e. a lot of people were told to use `userResourcesLocation`, and now this must be undone to be sure there is no negative interference.

**Comment by saucettv** [comment]
Yeah that is a possibility for some users, personally I can say that I have disabled them all. Only using UBlock, no extra scripts installed and ads are showing. Just giving you a heads up, because the rate-limit problem is the issue here, so I'm guessing more users will report repeated ads after refreshing in the future. No need to remove it yet if you are not sure, but I am one of those users affected by it, when I use UBlock only.

**Comment by uBlock-user** [comment]
> because the rate-limit problem is the issue here, so I'm guessing more users will report repeated ads after refreshing in the future.

https://github.com/uBlockOrigin/uAssets/commit/1b1838af70fad1fd9f7d7e2aebc6016017d65f25

Filter has already been disabled.

**Comment by uBlock-user** [comment]
First case of reported ads after disabling the filter -- `https://www.reddit.com/r/uBlockOrigin/comments/qlyg5z/twitch_ads_are_back/`

**Comment by gwarser** [comment]
You mean - reported as working when filter was added back? Because https://www.reddit.com/r/uBlockOrigin/comments/pqmy4w/ublock_origin_138_announcement_thread/hiwt0o0/

**Comment by uBlock-user** [comment]
> Because

Okay I didn't count that, so that makes it the above report the second report.

**Comment by saucettv** [comment]
Thought I would try this again, but I'm still getting ads (While logged in). Here is the token response from the GQL request. Removed my IP and user ID, notice server_ads = true (SureStream).

`"{\"adblock\":false,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"cohhcarnage\",\"channel_id\":26610234,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924905785},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"twitch-web-wall-mason\",\"expires\":1635964456,\"extended_history_allowed\":false,\"game\":\"\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"web\",\"player_type\":\"site\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"role\":\"\",\"server_ads\":true,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":,\"user_ip\":\"\",\"version\":2}"`

I then enabled UBlock in private tabs, tried again in a private tab and got a response with server_ads turned off (Good). Realized it might be because I was logged out. So I logged in with my usual Twitch ID in the private tab, refreshed the page and got an ad and server_ads was turned back on. I now get an ad after every refresh.

They must be blocking the device ID bypass by user ID, maybe certain previous spade events or something add user ID's to a blacklist. I can literally log-in and log-out in the private tab and get ads off when I'm logged out and ads on when logged in. Didn't clear cookies or anything in the private tab while doing this and only had UBlock enabled in the private tab.

Here is a logged out response (No ads) and server_ads is false:

`"{\"adblock\":false,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"cohhcarnage\",\"channel_id\":26610234,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924905894},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"twitch-web-wall-mason\",\"expires\":1635965675,\"extended_history_allowed\":false,\"game\":\"\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"web\",\"player_type\":\"site\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"role\":\"\",\"server_ads\":false,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":null,\"user_ip\":\"\",\"version\":2}"`

I then created a new test Twitch account on the private tab, logged into it and still no ads. So it's somehow picking certain user ID's to fail on and can't be IP based. My normal Twitch ID must be blacklisted from using that 'twitch-web-wall-mason' device ID. I'm guessing that is also the reason for the other random cases too. Just no idea why and if it is timed based or they are detecting it somehow and slowly blacklisting ID's based on usage.

If I remove the OAuth header from the GQL request for the access token, while logged in, I get a response with ads turned off. If I leave the OAuth header in, I get a response with ads turned on, so has to be user ID based. For example, I can remove the OAuth header using the script and I get the site ad-free while logged in with my usual ID. Maybe this is the answer? To remove the OAuth header.

Removing the OAuth header, shouldn't have any negative affects and will fix the issues for the fringe cases. The only time it will have a negative affect is if they do block the twitch-web-wall-mason device ID, because then users will get ads on streams they are subbed to, but this could be addressed fairly quickly if it came to it.

Hope this helps

**Comment by uBlock-user** [comment]
> Removing the OAuth header,

Does doing that results in `server_ads` = `false` ?

**Comment by saucettv** [comment]
Yeah server_ads is false every time when I remove the OAuth token.

I added the following to the script:

`                if (typeof init.headers['Authorization'] === 'string') {
                    init.headers['Authorization'] = '';
                }`

**Comment by uBlock-user** [comment]
Also if possible removing `server_ads` variable from the `token` param in GQL POST request might help in blocking forced ads(SureStream) for good.

**Comment by saucettv** [comment]
I think the token/sig is made server-side and can't be edited as they won't match.

That test channel still shows server_ads = true, but I think it's forced to?

**Comment by uBlock-user** [comment]
> I think the token/sig is made server-side 

gql request is POST, so it should be possible ?

**Comment by saucettv** [comment]
What I pasted was the response from the POST, the actual request payload is something like:

`{"operationName":"PlaybackAccessToken_Template","query":"query PlaybackAccessToken_Template($login: String!, $isLive: Boolean!, $vodID: ID!, $isVod: Boolean!, $playerType: String!) {  streamPlaybackAccessToken(channelName: $login, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isLive) {    value    signature    __typename  }  videoPlaybackAccessToken(id: $vodID, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isVod) {    value    signature    __typename  }}","variables":{"isLive":true,"login":"channelName","isVod":false,"vodID":"","playerType":"site"}}`

**Comment by uBlock-user** [comment]
Actually, it's not gql, the request is GET and comes from `usher.ttvnw.net` --

`https://usher.ttvnw.net/api/channel/hls/twitchmedia39.m3u8?allow_source=true&fast_bread=true&p=680723&play_session_id=3a176c3713600bdf8732fc248a5b6b2c&player_backend=mediaplayer&playlist_include_framerate=true&reassignments_supported=true&sig=0d4924dba8cc524b2dd40fd4820898796544be41&supported_codecs=avc1&token={"adblock":false,"authorization":{"forbidden":false,"reason":""},"blackout_enabled":false,"channel":"twitchmedia39","channel_id":124719519,"chansub":{"restricted_bitrates":[],"view_until":1924905600},"ci_gb":false,"geoblock_reason":"","device_id":"twitch-web-wall-mason","expires":1635968650,"extended_history_allowed":false,"game":"","hide_ads":false,"https_required":true,"mature":false,"partner":false,"platform":"web","player_type":"site","private":{"allowed_to_view":true},"privileged":false,"role":"","server_ads":true,"show_ads":true,"subscriber":false,"turbo":false,"user_id":null,"user_ip":"REDACTED","version":2}&cdm=wv&player_version=1.6.0`

parameter `token`  has an array where one of the props is `server_ads`, need to remove that from that request.

@gorhill possible ?

**Comment by saucettv** [comment]
The GQL POST get's the access token and sig for the Usher GET request. It can't be removed because the token and sig won't match. Notice in the usher request it has token and sig params. These come from the GQL request and they are matched. If you edit either one, the response from the usher request will fail.

**Comment by uBlock-user** [comment]
> if (typeof init.headers['Authorization'] === 'string') { init.headers['Authorization'] = ''; }

Does it help block ads on `https://www.twitch.tv/twitchmedia39` ?

**Comment by pixeltris** [comment]
It does not help with `twitchmedia39`. But the results from the post by @saucettv sounds promising for regular channels for those who use Twitch accounts.

**Comment by saucettv** [comment]
The twitchmedia channels are all test channels, so have fixed backend params no matter the client request params. One of them always serves ads, no matter what. So it's not really a good way to test.

**Comment by uBlock-user** [comment]
Strangely pixeltris's solution worked for 12 days on that channel too, so I always first tested there.

**Comment by saucettv** [comment]
Well I do get server_ads=true on that channel, but don't actually get an ad. If that helps.

**Comment by saucettv** [comment]
Anyway, will leave it up to you guys, was just interested to find out why I was getting ads and it's the OAuth header, without a doubt. For me personally anyway.

**Comment by uBlock-user** [comment]
@gorhill We should pull the update to the existing scriptlet that was made in https://github.com/pixeltris/TwitchAdSolutions/commit/7233b5fd22844bdf47e2f14750ff8817cea60af2

**Comment by saucettv** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/qlyg5z/comment/hj779rg/?utm_source=share&utm_medium=web2x&context=3 Looks like the updated pixeltris script worked for another user also.

**Comment by u-RraaLL** [comment]
@pixeltris not sure if you're aware of this, but apparently the scriptlet breaks VODs for subscribers: https://www.reddit.com/r/uBlockOrigin/comments/q2i77a/adblock_improvements_after_twitch_leak/hjjex68/?utm_source=reddit&utm_medium=web2x&context=3

I'm just mentioning this in case it's something that can be fixed.

**Comment by pixeltris** [comment]
Yea that could be fixed by also doing `&& init.body.includes('"isLive":true')` in the gql check. Maybe the json should be parsed at this point... but that should be enough.

**Comment by saucettv** [comment]
Seems like Twitch have fully circumvented the device ID now? Anyone else confirm?

**Comment by u-RraaLL** [comment]
Two reports yesterday on reddit of the solution no longer working.

**Comment by pixeltris** [comment]
As mentioned I think this is patched and now it's causing negative issues for Twitch Turbo users:

- https://reddit.com/r/Twitch/comments/qr1y1i/twitch_turbo_running_ads
- https://github.com/pixeltris/TwitchAdSolutions/issues/52

@uBlock-user sounds like the filter should be removed?

**Comment by uBlock-user** [comment]
Still works fine for me, 

> now it's causing negative issues for Twitch Turbo users:


due to https://github.com/pixeltris/TwitchAdSolutions/commit/aad8946dab2bba951bb81c7730292fe595a7a6ae not being pulled into uBO's scriptlet solution ?

**Comment by pixeltris** [comment]
I could see Turbo being impacted by the `Authorization` change. However, the latest release (1.38.6) doesn't even have the `Authorization` change. It sounds like @ImpalaPUA [is using default uBlock Origin](https://github.com/pixeltris/TwitchAdSolutions/issues/52#issuecomment-966677513) and it's impacting their Turbo. Therefore I assume the way it's being patched server side is checking for `twitch-web-wall-mason` prior to any checks for Turbo. And as such Turbo users are impacted.

As for me I tested all versions of the `bypass` script and I get ads on all of them. Could be an A/B testing thing though.

**Comment by uBlock-user** [comment]
> is using default uBlock Origin 

default as in running on factory lists/settings ? We don't know if he made any changes to `userResourcesLocation` or if he has installed any twitch extensions or if there's interference from another blocker extension, that needs to be communicated first.

**Comment by pixeltris** [comment]
There are a lot of threads on /r/Twitch (I count 9 - including one mentioning Brave which I believe pulls in the same script) which would make me suspect it is the case, but you're right...

@ImpalaPUA can you confirm that you have `userResourcesLocation` as `unset` in your advanced settings of uBlock Origin and that you don't have any other Twitch ad blockers enabled?

**Comment by uBlock-user** [comment]
I just don't want to hastily disable the filter like I did before on a case or two, if we choose to disable it it should be done on established facts.

@ryanbr do you see video ads on twitch streams now ?

**Comment by uBlock-user** [comment]
> There are a lot of threads on /r/Twitch (I count 9 - including one mentioning Brave which I believe pulls in the same script) which would make me suspect it is the case, but you're right...

and yet not one of them has created any threads at `https://www.reddit.com/r/uBlockOrigin/` which makes me wonder if its something on their part which needs to be investigated by them, because whenever uBO users start seeing ads, they immediately report there.

**Comment by saucettv** [comment]
I can confirm the same as @pixeltris , tried the script with and without the latest commit, getting ads again and it's not applying the rate-limit so getting an ad every refresh of the page.

**Comment by saucettv** [comment]
There are topics on the Twitch reddit, with lots of users complaining about being subbed/turbo and getting ads, I'm guessing it's because they have the bypass device ID being used in UBlock. Twitch is recommending users to disable their ad-block extensions.

**Comment by uBlock-user** [comment]
> I'm guessing it's because they have the bypass device ID being used in UBlock.

Twitch device ID fix has been there for a month now, and the device ID issue only started happening now ?

**Comment by saucettv** [comment]
I think maybe they have just simply blacklisted it and it's overriding subs/turbo.

**Comment by saucettv** [comment]
The GQL request for the access token:

Without the Auth header:

"{\"adblock\":false,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"travenura\",\"channel_id\":55269602,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":1924908642},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"twitch-web-wall-mason\",\"expires\":1636726543,\"extended_history_allowed\":false,\"game\":\"\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"web\",\"player_type\":\"site\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"role\":\"\",\"server_ads\":true,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":null,\"user_ip\":\"\",\"version\":2}"

With the Auth header:

"{\"adblock\":false,\"authorization\":{\"forbidden\":false,\"reason\":\"\"},\"blackout_enabled\":false,\"channel\":\"travenura\",\"channel_id\":55269602,\"chansub\":{\"restricted_bitrates\":[],\"view_until\":19249068642},\"ci_gb\":false,\"geoblock_reason\":\"\",\"device_id\":\"twitch-web-wall-mason\",\"expires\":1636726543,\"extended_history_allowed\":false,\"game\":\"\",\"hide_ads\":false,\"https_required\":true,\"mature\":false,\"partner\":false,\"platform\":\"web\",\"player_type\":\"site\",\"private\":{\"allowed_to_view\":true},\"privileged\":false,\"role\":\"\",\"server_ads\":true,\"show_ads\":true,\"subscriber\":false,\"turbo\":false,\"user_id\":00000000,\"user_ip\":\"\",\"version\":2}"

Both came back with server_ads=true.

Same results in a private tab with the script running.

**Comment by uBlock-user** [comment]
> channel":"travenura"

`https://www.twitch.tv/travenura` ? `server_ads` is `true` there but I don't get served ads, very strange.

**Comment by saucettv** [comment]
Could be your location not having any fill, but generally server_ads = true, means SureStream(Embedded) ads is turned on. In the network tools console, if you look at the Twitch cookies, there is two device-id cookies, deleting them usually resets any rate-limits etc and sometimes forces an ad on the next refresh. Up to you if you want to test it that way though, especially if you are ad-free.

**Comment by saucettv** [comment]
I think you need to consider the rate-limit issue when using the bypass device ID, for users that it is no longer working for, it's not applying a rate-limit to the amount of ads shown. So for a non subbed stream, you would get an ad after every refresh of the page, or every stream switch (if there is fill). Normally a rate-limit would be applied once an ad has fully shown. I expect Twitch is getting the brunt of the support emails and Reddit posts about the amount of ads, because people don't realize it's due to the bypass device ID. The Brave browser seems to of applied the bypass script, but without the Auth header, which explains the Turbo issue.

I can see that the filter is still enabled by default, do you have any plans to investigate it?

**Comment by uBlock-user** [comment]
@gorhill are you going to pull https://github.com/pixeltris/TwitchAdSolutions/commit/aad8946dab2bba951bb81c7730292fe595a7a6ae ?

**Comment by ImpalaPUA** [comment]
> There are a lot of threads on /r/Twitch (I count 9 - including one mentioning Brave which I believe pulls in the same script) which would make me suspect it is the case, but you're right...
> 
> @ImpalaPUA can you confirm that you have `userResourcesLocation` as `unset` in your advanced settings of uBlock Origin (1.38.6) and that you don't have any other Twitch ad blockers enabled?

Yea, I have nothing in there and its set to unset

**Comment by pixeltris** [comment]
@ImpalaPUA Are you on 1.38.6 and don't have any other Twitch ad blocking extensions enabled?

And as follow-up; could you also tell me if you see ads in incognito (i.e. not logged into Twitch).

**Comment by uBlock-user** [comment]
Twitch Turbo issue fixed in https://github.com/gorhill/uBlock/commit/ddd31f3567128ca97be5cb12ba804be6c162087e

**Comment by pixeltris** [comment]
That isn't related to Turbo. That was a fix for sub-only VODs not working for subscribers https://github.com/uBlockOrigin/uBlock-issues/issues/1789#issuecomment-962440694

**Comment by uBlock-user** [comment]
Only issue/s reported on uBO subreddit was of Twitch Turbo which started after Authorisation was set to `''`

**Comment by pixeltris** [comment]
Yes there's a good chance the `Authorization` header being set to null is impacting Turbo. Which is why I'm trying to establish if any impacted users are on 1.38.6 as that doesn't have the `Authorization` code.

If someone is on 1.38.6 and their Turbo is broken that is a very good indication that the bypass is no longer working (for some users). Which is also why I asked @ImpalaPUA for a follow-up for whether they see ads in incognito (no Turbo).

It should be noted that pretty much single time Twitch breaks a bypass it comes in waves (either as explicit A/B testing, or just how they deploy stuff to their servers around the world).

**Comment by ImpalaPUA** [comment]
> Yes there's a good chance the `Authorization` header being set to null is impacting Turbo. Which is why I'm trying to establish if any impacted users are on 1.38.6 as that doesn't have the `Authorization` code.
> 
> If someone is on 1.38.6 and their Turbo is broken that is a very good indication that the bypass is no longer working (for some users). Which is also why I asked @ImpalaPUA for a follow-up for whether they see ads in incognito (no Turbo).
> 
> It should be noted that pretty much single time Twitch breaks a bypass it comes in waves (either as explicit A/B testing, or just how they deploy stuff to their servers around the world).

1.38.7b20 and umatrix

and ads on incognito

**Comment by uBlock-user** [comment]
> and umatrix

Disable uMatrix and all other extensions.

**Comment by ImpalaPUA** [comment]
> Great thanks. If you could do me one more favor and test 1.38.6 and let me know if you see ads there while logged in Turbo, that would be helpful.



> > and umatrix
> 
> Disable uMatrix and all other extensions.

With all addons except ublock 1.38.6 and twitch.tv#@#+js(twitch-videoad) removed from my filters

I still get ads with twitch turbo

**Comment by ImpalaPUA** [comment]
Actually when I went back to dev build and forgot to add  twitch.tv#@#+js(twitch-videoad) back

I got ads through twitch turbo again

**Comment by pixeltris** [comment]
Thanks.

To sum this up...

Based on what @ImpalaPUA has observed it sounds like the there's a new check (introduced ~3 days ago) for the `twitch-web-wall-mason` header which always returns true to server sided ads. This check seems to be prior to any check for Turbo / subscription status (which can be confirmed by seeing ads with Turbo enabled on 1.38.6 which doesn't touch the `Authorization` header).

It should be noted that anyone who is impacted by this (Turbo or not) will see ads on every single stream on every page load. Normally you're given a ~10 minute cooldown after watching an ad (as mentioned by @saucettv). It's a worse experience having the ad blocking method enabled vs disabled.

Yes, it's weird there are literally 0 reports of the method being broken to uAssets or `/r/uBlockOrigin`. But this might be due to people using alternative methods for the past year or so, or somewhat expecting to see ads. And it might also be partly due to Twitch's shitty use of A/B testing.

\*shrug\*

**Comment by ImpalaPUA** [comment]
Wasn't it reported here https://www.reddit.com/r/Twitch/comments/qr1y1i/twitch_turbo_running_ads/

**Comment by saucettv** [comment]
Twitch use the users normal Device ID to record ad impressions and to apply the rate-limit. They are not doing this with the 'twitch-web-wall-mason' device ID. So as it's not actually bypassing the ads anymore for some users, having it in the scriptlet is causing more ads than would normally be shown to users that it's affecting. It is affecting users and eventually they will block it for all users. The scriptlet needs to be removed before users start disabling UBlock to actually see less ads on Twitch.

**Comment by diglarboard** [comment]
> Based on what @ImpalaPUA has observed it sounds like the there's a new check (introduced ~3 days ago) for the `twitch-web-wall-mason` header which always returns true to server sided ads. This check seems to be prior to any check for Turbo / subscription status (which can be confirmed by seeing ads with Turbo enabled on 1.38.6 which doesn't touch the `Authorization` header).

I'm seeing different behavior. With a 1.38.6 I do not see ads on a subbed channels. With 1.38.7b27 I do get ads on a subbed channel. So I think it is the Authorization change that is breaking it and should be removed. It likely is causing Twitch to be unable to authentication that my user has a sub.

**Comment by pixeltris** [comment]
Do you see ads in incognito mode / logged out (both 1.38.6 and 1.38.7b27)?

**Comment by diglarboard** [comment]
Yes, so in incognito mode I get preroll ads for both versions.

I just double checked and it's definitely the case that the auth change is causing ads on my subbed channel. On 1.38.7b27 if I log in and watch a subbed channel, the `https://usher.ttvnw.net/api/channel/hls/formal.m3u8` network call shows my user_id set to null and subscriber set to false. If I use 1.38.6, then my user_id is set correctly and subscriber is true.

**Comment by pixeltris** [comment]
One thing I didn't ask @ImpalaPUA is if they use Brave. It pulls in the script also and might be pulling in the latest version (which is why they might be observing 1.38.6 differently).

The method is patched for you. And yes it sounds like `Authorization` is a regression in this case.

I recommend removing `Authorization` from the script to reduce the impact.

**Comment by ryanbr** [comment]
At Brave we just pulled in the latest uBO twitch update, which will roll out in the next 24/48hrs.

**Comment by pixeltris** [comment]
Thanks for the info @ryanbr unfortunately the latest update to the script wont change anything. The method is slowly being patched by Twitch. @gorhill I recommend `Authorization` is removed at minimum which will reduce the sub/Turbo issues (but non sub/Turbo users will still see way more ads than normal (ad on every page load) for those who observe the method as patched).

**Comment by ImpalaPUA** [comment]
Small update, when I upgraded to the latest development build and removed twitch.tv#@#+js(twitch-videoad) from my filters

I no longer see pre rolls with twitch turbo, so it seems to have fixed the issue

**Comment by saucettv** [comment]
> 
> 
> Twitch use the users normal Device ID to record ad impressions and to apply the rate-limit. They are not doing this with the 'twitch-web-wall-mason' device ID. So as it's not actually bypassing the ads anymore for some users, having it in the scriptlet is causing more ads than would normally be shown to users that it's affecting. It is affecting users and eventually they will block it for all users. The scriptlet needs to be removed before users start disabling UBlock to actually see less ads on Twitch.

https://www.reddit.com/r/uBlockOrigin/comments/qwr2oj/suddenly_on_twitch_im_getting_much_more_adds_why/ @gorhill 

If you really wanted to keep the bypass script, you could maybe write something to check the GQL response to see if ads are turned on or not. If not, continue, if they are, do a real request without the bypass device ID. But not sure if it's worth it if they are just slowly going to block the bypass anyway.
