### ISSUE TITLE
uBlock breaks ungoogled-chromium

### ISSUE THREAD

**Issue by new-on-github** [uBlockOrigin/uBlock-issues#1790]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Hello,

my ungoogled-chromium isn't loading any page after enabling ublock. I can load local html files but not even a local service via IP-address. After disabling ublock the page loading works again.
Sadly I'm not good enough to see useful information in the log file...

By the way thanks for your work.

### A specific URL where the issue occurs

https://ublockorigin.com/

### Steps to Reproduce

1. Install a ungoogled chromium
2. Install ublock
3. nothing is loading anymore

### Expected behavior

loading webpages 

### Actual behavior

nothing is loading

### uBlock Origin version

1.38.6

### Browser name and version

Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

### Operating System and version

Linus MInt 20.2 Cinnamon

**Comment by uBlock-user** [comment]
Ungoogled-Chromium is not officially supported.

**Comment by gorhill** [comment]
What is "ungoogled chromium", and were do I install it from?

**Comment by uBlock-user** [comment]
https://github.com/Eloston/ungoogled-chromium

**Comment by gorhill** [comment]
Well given that uBO works just fine in the official Chromium stable, crashed in custom build will have to be reported to the devs maintaining that custom built. uBO is HTML/CSS/JS, it's not supposed to crash the browser, and if it does, 'this must be reported to the browser devs.

**Comment by uBlock-user** [comment]
https://github.com/Eloston/ungoogled-chromium/issues/1699
https://github.com/Eloston/ungoogled-chromium/issues/1698

**Comment by gorhill** [comment]
Also <https://github.com/Eloston/ungoogled-chromium/issues/1703>.

**Comment by new-on-github** [comment]
Ok, sorry, for not knowing that it is browser related. But after thinking about I should have recognized it by myself...

Also thanks for the links and the work on ublock!
