### ISSUE TITLE
Rule is not saving when lacking subdomain

### ISSUE THREAD

**Issue by g-k-m** [uBlockOrigin/uBlock-issues#1791]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Hello, i have this rule in My rules:

```
* googleusercontent.com * block
```

however using the logger i saw some images were getting blocked. so using the logger i was able to make this rule (the logger made it i just clicked the gray field):

```
* https://lh3.googleusercontent.com image noop
```

this is the very rule the logger made, and it works!

however if i delete the "https://lh3." part and try to save the rule, it disappears, which makes no sense to me why it can globally exclude images coming from "https://lh3.googleusercontent.com" from being dynamically filtered but it cannot do the same for them coming from any subdomain from "googleusercontent.com"

### A specific URL where the issue occurs

google.com

### Steps to Reproduce

1. Have the rule * googleusercontent.com * block in My rules and no other relevant filters to mess with it
2. Go to google.com, observe in the top right the profile pic of the account you are signed in with is missing, this will show in ublock logger as "https://lh3.googleusercontent.com/ogw/xxxxx" blocked image request, at least it does for me, maybe the subdomain is different for you
3. Click on the row of that resource being blocked, go to URL rule, choose Context: * and type: image which should already be chosen, then choose the lowest row being "https://lh3.googleusercontent.com", now click the gray middle stripe on the left, the one responsible for noop action, and click the padlock to save it
4. Go to my rules and try to change the rule by deleting the "https://lh3." part and press save

### Expected behavior

The rule is saved and commited

### Actual behavior

The rule vanishes

### uBlock Origin version

1.38.6

### Browser name and version

Chromium 97.0.4679.0

### Operating System and version

W10 21H1 19043.1288

**Comment by gorhill** [comment]
> `* https://lh3.googleusercontent.com image noop`

That is not a valid rule, [read the documentation](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax) carefully please.

**Comment by gorhill** [comment]
> however if i delete the `https://lh3.` part and try to save the rule, it disappears

Because you end up with a dynamic filtering rule and as a result you have an invalid syntax. See [documentation](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax).
