### ISSUE TITLE
Can't make a whitelist rule for cosmetic filtering

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#1796]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

If there is a general cosmetic rule like `.after-content-ad` and I want to whitelist this on a site very specific - like `modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)`  [(an element almost ad the bottom of this site)](http://www.modekoninginmaxima.nl/mode-maxima-mode-algemeen/net-terug-uit-new-york-verschijnt-maxima-alweer-op-de-rode-loper) uBlock will not whitelist this element, because of the general rule `.after-content-ad`. 

I think that's weird, because with network rules (like `||example.com^`) you can make specific exceptions (like `@@||example.com/123/*`). 

I would like to see that this is also possible with cosmetic filtering.

### A specific URL where the issue occurs

modekoninginmaxima.nl

### Steps to Reproduce

1. Add the filter `modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)`;
2. Open your logger and you will see `.after-content-ad` blocked;
3. Open in the logger the DOM-inspector and you will see that the element `.after-content-ad` with the text "Niets van deze website..." is still blocked.

### Expected behavior

I expected to see in my logger that the element `modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)` had been whitelisted (and then also visible on the site).

### Actual behavior

The element `modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)` is blocked.

### uBlock Origin version

1.38.4

### Browser name and version

Microsoft Edge v.95

### Operating System and version

Windows 10 21H1

**Comment by uBlock-user** [comment]
modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i) will only work if there's a filter like `modekoninginmaxima.nl##.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)`

**Comment by BPower0036** [comment]
You have to do it different. This works:
`modekoninginmaxima.nl##.after-content-ad:not(:has-text(Niets van deze website mag verveelvoudigd))`

**Comment by uBlock-user** [comment]
There has to be an exact match.

**Comment by felix-22** [comment]
As already pointed out, the exception filter must be the same, more info: 
- https://help.eyeo.com/en/adblockplus/how-to-write-filters#elemhide_exceptions
- https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering

But it seems you are already aware of it, and I see your ticket being a feature request to be able to create specific exceptions for cosmetic filters, just like in network filters, well, currently it isn't possible, in any case a workaround for your request is to do the opposite way:
- add the exception: `modekoninginmaxima.nl#@#.after-content-ad`
- and then add a hiding filter with a negated regex, which will match and hide every element not containing a text: `modekoninginmaxima.nl##.after-content-ad:has-text(/^((?!Niets van deze website mag verveelvoudigd en).)*$/i)` however to element be hidden such way, must still contain any text, which means elements containing no text at all won't be hidden
- also as for your specific example subpage, there is only 1 `.after-content-ad` DOM element so `modekoninginmaxima.nl#@#.after-content-ad` won't unhide anything more except the element with the text you provided so no need for such specific exception like `modekoninginmaxima.nl#@#.after-content-ad:has-text(/Niets van deze website mag verveelvoudigd en/i)` unless you find real cases / other subpages which have more than 1 `.after-content-ad` DOM element

 I'll leave it for gorhill, but I don't think he is going to implement it.
Also label "invalid" doesn't seem to be valid as it is rather a feature request, and not OP unaware how exception filters work.

**Comment by gorhill** [comment]
Cosmetic filter exceptions must be an exact match, and cosmetic filtering is a whole different engine/syntax than that of network filtering, what works in one should not be used as an argument as what should work in the other.
