### ISSUE TITLE
blank page when going to view filters in the Dashboard: Filter lists

### ISSUE THREAD

**Issue by iibett** [uBlockOrigin/uBlock-issues#1798]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

When you got to the Dashboard: Filter lists and click on the "view content" (eye) button you get a blank page. I only get this behavior on the latest dev build.
firerfox 94.0.1
ublock origin 1.38.7b14

### A specific URL where the issue occurs

In the Filter lists pane

### Steps to Reproduce

1. go to Filter lists pane
2. click on the "view content" (eye) button
3. and ublock origin opens blank page in a new tab.

### Expected behavior

when you click on "view content"  you should get redirected to a filter list you clicked

### Actual behavior

you get a blank page

### Configuration

firerfox 94.0.1
ublock origin 1.38.7b14
windows 10

**Comment by nicolaasjan** [comment]
I had the same issue today.
Reverting to release 1.38.6 fixed it.

**Comment by felix-22** [comment]
I've updated to uBO `1.38.7b14` and I confirm the issue on both Firefox 94 and Opera 80, white & blank page.

**Comment by uBlock-user** [comment]
>  ublock origin 1.38.7b14

Does it happen in 1.38.7b12 ?

**Comment by felix-22** [comment]
Nope.

**Comment by uBlock-user** [comment]
Regressed by https://github.com/gorhill/uBlock/commit/8b8b7da8d9f10fca94f9daaf9b93a7ec6927c6d6#diff-c6419888f961730e8541ae029eec1cc56e608b734a5261da00a56a5ed36d7a7dR39
