### ISSUE TITLE
awesome tool

### ISSUE THREAD

**Issue by amoisidis** [uBlockOrigin/uBlock-issues#18]
Hi you guys,

Awesome tool.  It’s wonderful.  Unfortunately, it does not solve the problem completely.  Zuckerberg and his gang of bastards cannot block the account anymore, now they disable the account.  Is there anyway to block this action of inactivation of account?

Many thanks
Tony

**Comment by gorhill** [comment]
Stop abusing this issue tracker please.

**Comment by uBlock-user** [comment]
Just ban him from the issue tracker.
