### ISSUE TITLE
haaretz.co.il seems to circumvent uBlockOrigin / make it partially fail

### ISSUE THREAD

**Issue by eyalroz** [uBlockOrigin/uBlock-issues#180]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings <- Bug involves using non-default filters
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The haaretz.co.il website (and its individual story pages) has many ads and banners. When you try to remove the `<div>` for one of them using "block this element", formulating a rule, the element is removed - on that specific page during that specific session; but if you load another page fitting the same rule, or even perhaps the same page - you see that `<div>` again (often with the banner itself, but not always). 

The rule is indeed generated and is visible in the list of custom rules - multiple times if you've tried this repeatedly with the same kind of ad on different pages and/or at different times.

This happens specifically with the `topSectionBanners` class of `<div>`'s, rule `www.haaretz.co.il##.topSectionBanners`.

### A specific URL where the issue occurs

https://www.haaretz.co.il

### Steps to Reproduce

This is tricky, since behavior is not very consistent , and this sort of comes and goes, but

1. Visit https://www.haaretz.co.il
2. Make sure it has a `topSectionBanners` div (it might have `xx--e-xx.topSectionBanners` or other such variations)
3. Use uBlock to create a rule removing the `topSectionBanners` element
4. Reload the page or visit other another page with a `topSectionBanners` header - it will likely not be suppressed
3. [and so on...]

### Your environment

* uBlock Origin version: v1.16.17b9
* Browser Name and version: Firefox 52.9.0 ESR
* Operating System and version: Devuan GNU/Linux 2.0 ASCII

**Comment by gorhill** [comment]
User stylesheets are not supported in Firefox 52, they are supported in Firefox 53 and above. The site is bypassing uBO's injected styles.

Use uBO legacy or replace Firefox 52 ESR with Firefox 60 ESR.
