### ISSUE TITLE
In a version 1.38.6 import and export workes incorrect and broke the filter list

### ISSUE THREAD

**Issue by IRainman** [uBlockOrigin/uBlock-issues#1802]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I import settings from one Firefox in Windows to another same Firefox version on Windows with same extension version 1.38.6 and get the problem: the list of the lists is broken and mismathed after imports some new records not exist, some old records _in_internal_extension_list_ mismathed  :( The backup of a settings is attached.
[ublock-backup.txt](https://github.com/uBlockOrigin/uBlock-issues/files/7492071/ublock-backup.txt)

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. export settings from one Firefox with extension on first machine
2. import settings to second same Firefox with extension on second machine
3. 

### Expected behavior

list of subscriptions is same on both installations

### Actual behavior

list of subscriptions is mismathed

### uBlock Origin version

1.38.6

### Browser name and version

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0

### Operating System and version

Winows 10.0.19041 (2004)

**Comment by gwarser** [comment]
Which part is wrong? I see nothing obviously broken.

>list of subscriptions

Maybe some (disabled) lists are hidden -  click on section header to show them all?

Did you exported and then imported using buttons at the bottom of "Settings" tab?

**Comment by gwarser** [comment]
>the list of the lists is broken and mismathed after imports some new records not exist, some old records in_internal_extension_list mismathed

Can you attach screenshots of both, old and new?

**Comment by gwarser** [comment]
https://hg.adblockplus.org/ is down.

**Comment by gorhill** [comment]
What are the exact entries which you say no longer exist? What are the entries which are "mismatched"? (What do you mean by "mismatched"?)

**Comment by IRainman** [comment]
Now I retest it. I starting a browser again on all of 9 machines (3 with Android and 6 with Windows) list named "404" don't exist anymore and the imported selectors displayed fine. Probably it's only visual bug... from cache may be... But bug is successfully reproduced after file imported ^^" I close the issue because don't want to test it again.

**Comment by gorhill** [comment]
> list named "404" don't exist anymore

uBO is not responsible if a remote server becomes unavailable, it's for you to sort out such issues.

I see you are importing lists directly from `https://hg.adblockplus.org/ruadlist/raw-file/tip/bitblock/`, which is a development repository, you should avoid doing this and use the official mirrors instead -- the server refuses to respond, this is not a uBO issue.
