### ISSUE TITLE
not working uppercase in regular expressions.

### ISSUE THREAD

**Issue by nicekon** [uBlockOrigin/uBlock-issues#1804]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

`/\/[A-Z]{2,}/$domain=yahoo.com`

In addition to the URL of the above uppercase URL, lowercase is blocked.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. /\/[A-Z]{2,}/$domain=yahoo.com
2. add rule

### Expected behavior

All URL blocked

### Actual behavior

All URL blocked

### uBlock Origin version

1.38.6

### Browser name and version

chrome 95.0.4638.69

### Operating System and version

macOS 12.0.1

**Comment by gorhill** [comment]
Use [`match-case`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#match-case) option.

**Comment by felix-22** [comment]
Also here as well: `https://help.eyeo.com/en/adblockplus/how-to-write-filters#options`

<br>
<br>

> nicekon :
> ### Prerequisites
> [x]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

Really? How. You asked for something which is already described in the documentation of both Adblock Plus and uBlock Origin....
