### ISSUE TITLE
uBlock GA overwrites breaking _link implementation when using a named property

### ISSUE THREAD

**Issue by felipedeboni** [uBlockOrigin/uBlock-issues#1807]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock seems to overwrite GA script, which is fine. The issue is "_link" push wouldn't work if using a named property.

Example without a named property:
`js
_gaq.push(['_link', url]);
`

Example using a named property:
`js
_gaq.push(['named._link', url]);
`

Relevant code from uBlock GA:
```js
Gaq.prototype.push = function(a) {
        if ( typeof a === 'function' ) {
            a(); return;
        }
        if ( Array.isArray(a) === false ) {
            return;
        }
        // https://twitter.com/catovitch/status/776442930345218048
        // https://developers.google.com/analytics/devguides/collection/gajs/methods/gaJSApiDomainDirectory#_gat.GA_Tracker_._link
        if ( a[0] === '_link' && typeof a[1] === 'string' ) {
            window.location.assign(a[1]);
        }
        // https://github.com/gorhill/uBlock/issues/2162
        if ( a[0] === '_set' && a[1] === 'hitCallback' && typeof a[2] === 'function' ) {
            a[2]();
        }
    };
```

If using a named property, `a[0]` is going to be `{name here}._link` and nothing would have been done.

### A specific URL where the issue occurs

https://wms2demo-201.previews.funeralone.com/store/best-sellers/beautiful-in-blue

### Steps to Reproduce

1. Open the URL
2. Type anything on the "Name of Deceased"
3. Click on "Buy Now"
4. It's going to redirect after 60 seconds because the uBlock broke "_link" implementation and we have a setTimeout to ensure the redirect

### Expected behavior

Works the same way when the GA property isn't named, makes a redirect.

### Actual behavior

It does not redirect.

### uBlock Origin version

uBlock Origin 1.38.6

### Browser name and version

Chrome 95.0.4638.69

### Operating System and version

macOS 10.14.6

**Comment by gorhill** [comment]
@wisniewskit, for your interest, you may want to update [Firefox's shim](https://searchfox.org/mozilla-central/rev/267682a8f45221bf0bfe999d4a0239706a43bc56/browser/extensions/webcompat/shims/google-analytics-legacy.js#29) the same way.

**Comment by wisniewskit** [comment]
Thanks for the ping, @gorhill !  Might we also want to do the same kind of test for the `_set` case as well?

**Comment by gorhill** [comment]
>  Might we also want to do the same kind of test for the `_set` case as well?

Personally on my side I prefer to have actual concrete reproducible cases to justify such change, I don't feel comfortable to change this without knowing whether this really happens out there.

**Comment by wisniewskit** [comment]
Understood, thanks. I'm inclined to agree.
