### ISSUE TITLE
Looking for filters inside a list, No good performance

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uBlock-issues#1808]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

trying search a filter inside **EasyList** filter list 

I have written: `/product/` showing me many results that do not end and start with `/` 
I need writte two times `//`  Example: `//product//` 🙄

![Captura12](https://user-images.githubusercontent.com/33556647/141194548-76861797-668e-4fce-8d31-73cf28f5544a.PNG)

### A specific URL where the issue occurs

no URL

### Steps to Reproduce

1. Go to **EasyList** filters, in the Lists of uBO
2. In the search box
3. Writte /product/
4. does not show exact search

### Expected behavior

exact search

### Actual behavior

¿?

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 95.0

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
By design, wrapping an expression with forward slashes tells to search using literal regular expression.

**Comment by gorhill** [comment]
There is no documentation for this, so maybe I could take the opportunity to change this to something like `regex:...` for regex-based search.

**Comment by gorhill** [comment]
Not sure, the current approach allows for regex flags such as `i` and `u`, that would be difficult to support these with other syntax, so we should just document it after all.

**Comment by u-RraaLL** [comment]
Perhaps just adding an info button/tooltip next to the searchbox informing about the regex support would do.
