### ISSUE TITLE
AMO APIv3 will soon be shut down

### ISSUE THREAD

**Issue by gontazaka** [uBlockOrigin/uBlock-issues#1809]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

AMO APIv3, which is used to sign Firefox add-ons, will soon be shut down.
<https://blog.mozilla.org/addons/2021/02/01/addons-mozilla-org-api-v3-deprecation/>

In the project I forked, changing `/v3/` to `/v4/` was enough to make it work.
The applicable line is here.
https://github.com/gorhill/uBlock/blob/1.38.7b19/dist/firefox/publish-signed-beta.py#L204

v3 document
<https://addons-server.readthedocs.io/en/latest/topics/api/v3_legacy/signing.html>
v4 document
<https://addons-server.readthedocs.io/en/latest/topics/api/v4_frozen/signing.html>

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/1.38.7b19/dist/firefox/publish-signed-beta.py

### Steps to Reproduce

1. Push the tag to generate release assets
2. Run `/dist/firefox/publish-signed-beta.py`

### Expected behavior

Using the AMO APIv4

### Actual behavior

Using the AMO APIv3

### uBlock Origin version

1.38.7b19

### Browser name and version

Firefox 94.0.1 64bit

### Operating System and version

Windows10 21H1 64bit

**Comment by gorhill** [comment]
Thanks for the heads-up.
