### ISSUE TITLE
if you open a filter the last modified time is out to date

### ISSUE THREAD

**Issue by signalguest** [uBlockOrigin/uBlock-issues#181]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the 3rd party filters if i open for example EasyPrivacy i discover that the source is apparently  not up to date based on the last modified time there.
That happens only in Firefox but not in Chrome.
And of course i tried even to manual sync.
Maybe is related to the fact that i use Firefox in private mode?
But is ublock using an out to date list or is just a cache issue?

### Steps to Reproduce

1. open settings
2. move to 3rd party filters
3. open EasyPrivacy filter

### Expected behavior:

A last modified time up to date

### Actual behavior:

Last modified: 12 Jun 2018 12:47 UTC

### Your environment

* uBlock Origin version: latest
* Browser Name and version: latest firefox
* Operating System and version: latest windows

**Comment by uBlock-user** [comment]
> just a cache issue?

Probably that. Can't reproduce.

**Comment by uBlock-user** [comment]
I can reproduce on Nightly if I enable Private Browsing Mode.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3071
