### ISSUE TITLE
logger missing in fenix (android) 

### ISSUE THREAD

**Issue by ale82to** [uBlockOrigin/uBlock-issues#1817]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

in android running latest ublock beta the logger is missing because is replaced by report issue for this site new entry (which is far less useful that the logger) please bring it back

### A specific URL where the issue occurs

ww.ciao.it

### Steps to Reproduce

open fenix pop up and logger is missing 

### Expected behavior

in android running latest ublock beta the logger is missing because is replaced by report issue for this site new entry (which is far less useful that the logger) please bring it back

### Actual behavior

let user have the logger on Android 

### uBlock Origin version

1.38.7b26

### Browser name and version

Fenix 

### Operating System and version

android

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/eccf613edfe480d34cb225dac203d3213f3ef2f7

>On mobile devices, the logger icon is replaced by the "chat"
icon since it is more likely to be useful on small display
devices. The logger can always be opened from the Support
pane in the dashboard.

**Comment by gorhill** [comment]
The logger won't come back in the popup panel, there is not enough place for it on a mobile device. However you can access it through the Support pane, where it says _"The logger is the primary tool to diagnose filter-related issues."_ Once you open the logger, you can create a shortcut to access to it it more quickly next time.

**Comment by standmit** [comment]
Let users decide what's more important to them. Make this panel tweakable

**Comment by Nojuuu** [comment]
Phone screens are huge these days, why not make it depend on that whether they are displayed or not? 

Or value that you can set in advanced settings to force them to show on mobile?

**Comment by gorhill** [comment]
> Or value that you can set in advanced settings to force them to show on mobile?

Yes, with dev build 1.39.1b1 , you can add `+logger` to the [advanced setting `uiPopupConfig](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uipopupconfig)`.

**Comment by Nojuuu** [comment]
Okay, that's good to hear 👍

**Comment by peace2000** [comment]
Why not to add the logger button back for everyone but make it appear only after "More" is pressed once?

@gorhill ?

**Comment by gwarser** [comment]
> Yes, with dev build 1.39.1b1 , you can add `+logger` to the [advanced setting `uiPopupConfig`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uipopupconfig).

Should it be finally documented @gorhill ?

**Comment by gorhill** [comment]
Yeah, I think it's fine documenting this, token-based configuration seems to be a good idea after all.

**Comment by blogmangit** [comment]
logger is by default disabled in ublock origin mobile version for both chrome and Firefox base but we can enable it just do the following: 

1. ublock origin > settings
2.  tick I am an advanced user then enter its settings
3. set UiPopupConfig to +logger
4. apply restart browser
5. logger option is back in mobile

![16_12_2021_00_16_35.jpg](https://user-images.githubusercontent.com/92579403/146251266-941a3c9d-8fc6-4558-be2b-68a598b5ffd2.jpg)

![16_12_2021_00_23_15.jpg](https://user-images.githubusercontent.com/92579403/146251283-5c1d7d45-a232-4bbe-a05f-933697ffc223.jpg)

**Comment by garymoon** [comment]
Just my 2c as a user, and thus lacking the context around this thinking: I have no understanding as to why the logger is hidden by default, nor why such an elaborate and completely undiscoverable incantation is required to reach it. I would definitely advocate for reconsidering this 👍

Thank you forever for uBo 💙

**Comment by garry-ut99** [comment]
I've updated https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger  by information how to access the logger on Mobile devices (https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger/_compare/129bf76e177770a2d7f175d3d13b68d28cb09d81...4738acd640f92fe0a3e94e4b7c851c0b43d8678f) so that users don't need to spent time digging deep into release change logs, tracker issues and discussion threads to find such an important and useful info.

<hr>

By the way, related threads :
- https://github.com/uBlockOrigin/uBlock-issues/discussions/1879
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2726
