### ISSUE TITLE
建议支持通过FTP同步设置

### ISSUE THREAD

**Issue by StrollStars** [uBlockOrigin/uBlock-issues#182]
如题，希望能够通过FTP链接实现多端同步，同时增加无法同步的提示功能。

**Comment by jspenguin2017** [comment]
浏览器自带的同步功能有什么问题么？

**Comment by StrollStars** [comment]
> 浏览器自带的同步功能有什么问题么？

目前只有设置备份到文件和从文件恢复功能吧？
用浏览器同步功能需要登录Google帐号，并且不能跨浏览器。

**Comment by jspenguin2017** [comment]
你怎么需要跨浏览器同步？
不然同步也不是全自动的，手动上传设置到FTP服务器然后在其他电脑下载也不是很麻烦吧？
你要是真的认为FTP同步会很方便，你得用英文重新写你的建议，不然作者看不懂。

**Comment by gwarser** [comment]
Cloud storage will not be improved/extended. I'm also pretty sure support for ftp will be removed from browsers soon https://bugzilla.mozilla.org/show_bug.cgi?id=85464#c34

**Comment by StrollStars** [comment]
@jspenguin2017 我以为扩展的开发者为国人。
@gwarser Thank you for your answer.
