### ISSUE TITLE
YouTube issues

### ISSUE THREAD

**Issue by Gladiatorg** [uBlockOrigin/uBlock-issues#1825]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

ublock origin is removing titles/misplacing them and the category tab on YouTube are completely blank and are just a circle

### A specific URL where the issue occurs

www.youtube.com

### Steps to Reproduce

open youtube

### Expected behavior

i expect it to work as intended

### Actual behavior

youtube titles

### uBlock Origin version

1.38.6

### Browser name and version

google chrome 96.0.4664.45

### Operating System and version

windows 11

**Comment by felix-22** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
