### ISSUE TITLE
Network filter in "My filters" sometimes works incorrectly?

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uBlock-issues#1828]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Adding network filter `||piano.io^` to `My filters` sometimes do not work in the URL below.

Video of steps to reproduce:

`https://streamable.com/ceoph0`

### A specific URL where the issue occurs

https://asia.nikkei.com/Business/Technology/Japan-s-Fugaku-retains-title-as-world-s-fastest-supercomputer

### Steps to Reproduce

1. Create a new Firefox profile, install and update filters.
2. Add `||piano.io^` to `My filters`
3. Load the URL above, then check the log. All `piano.io` links do not get filtered.

Notes: If I set `||fastly.net^` (to test sub-domains) or `||buy-ap.piano.io^` (to test the whole domain), they work normally. The same situation happens in Ungoogled Chromium 95.0.4638.69.

### Expected behavior

All `piano.io` links will be blocked.

### Actual behavior

All `piano.io` links do not get blocked.

### uBlock Origin version

1.38.6

### Browser name and version

Firefox 94.0.1

### Operating System and version

Windows 10 21H2 build 19044.1266

**Comment by gwarser** [comment]
Badfiltered in unbreak:

```
! override Peter Lowe's filter
||piano.io^$badfilter
```

**Comment by stephenhawk8054** [comment]
Ah I see, sorry I forgot about `badfilter`. Thanks for your reminder.
