### ISSUE TITLE
Add button to conveniently report current site to blocklist

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uBlock-issues#1829]
As an adjunct to https://github.com/uBlockOrigin/uBlock-issues/issues/1774#issuecomment-974719410, On e.g.,
![20211120T222703](https://user-images.githubusercontent.com/1230959/142730019-f525a93a-e789-477e-b2b2-7cee9dfbbd64.jpg)
add an additional button, with icon "！" and mouseover "report site to blocklist".
Upon which a dialog could start:
```
Report www.example.com to which blocklist(s)?:
[ ] malware blocklist (uBlock badware)
...

**Comment by gothic-bum** [comment]
Already added to the beta release:  
https://github.com/gorhill/uBlock/releases  
  
> A new _"Report an issue on this website"_ icon has been added to the popup panel, to make it easier to report filter issue to volunteers maintaining filter lists. Reporting filter issues through this new feature requires a GitHub account.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1541>.

**Comment by gorhill** [comment]
Do not open such "do-this" requests as issue. If you have such idea you want to discuss, start a thread in [Discussions](https://github.com/uBlockOrigin/uBlock-issues/discussions).

**Comment by jidanni** [comment]
Thanks everybody.
But in my quest to report the entire site,
the form,
![20211122T212332](https://user-images.githubusercontent.com/1230959/142869152-607ca31b-1092-4242-869b-548ff755ad85.jpg)
only discusses "page", and has no concept of "site".
Perhaps the user is supposed to write `example.com/*` but that isn't obvious.

**Comment by jidanni** [comment]
OK, even in the final part of our journey, creating
https://github.com/uBlockOrigin/uAssets/issues/10536
along the way I didn't see any concept of 'site', only 'page'.
