### ISSUE TITLE
Preparsing directive !#if not working

### ISSUE THREAD

**Issue by grenzor** [uBlockOrigin/uBlock-issues#183]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using #if preparsing directive stopped working. For example mobile specific filters are applying on desktop. I haven't tested this for include or other preparsing directives so I don't know if they also don't work.

### Steps to Reproduce

1. Add following lines to my filters:
  ```
  !#if env_mobile
  ||github.com^
  !#endif
  ```
2. Visiting github.com on desktop still results in blocking the page

### Expected behavior:

Filter should only apply on mobile.

### Actual behavior:

Filter applies everywhere.

### Your environment

* uBlock Origin version: 1.16.20
* Browser Name and version: Firefox 62

**Comment by gorhill** [comment]
Unable to reproduce, I tried on both Firefox 61 and Nightly.

**Comment by uBlock-user** [comment]
Likewise on Chromium either.

**Comment by uBlock-user** [comment]
> Add following lines to my filters

Post your _My Filters_ count, it should be 0 used out of 0

**Comment by gorhill** [comment]
As [per source code](https://github.com/gorhill/uBlock/blob/8be1aed04d641210ad5e778e17496ea097a125b5/platform/chromium/vapi-common.js#L60), this can happen only if there is the user agent string contains the word `Mobile`.

**Comment by grenzor** [comment]
Not sure what's happening here but add these lines to my filters:

!#if env_mobile
||github.com^
!#endif

!#if !env_testmobile
||test.com^
!#endtestif

Just found out I had the 2nd #!if in my filters when I was testing some filters (with "test" string within the if directive because I thought it then wouldn't apply). Whenever I add a filter to the first if block for some reason the 2nd (invalid) if block makes it not follow the directive.

**Comment by gorhill** [comment]
I can now reproduce with all the filters above.

Unknown directives should be disregarded, but they should not prevent known directives from working.

**Comment by uBlock-user** [comment]
On adding 

```
!#if !env_testmobile
||test.com^
!#endtestif
```
domain is blocked.

**Comment by gorhill** [comment]
Actually I had wrongly assumed the issue was with the unknown token, but the issue is with `!#endtestif`.

This causes uBO to fail to find a matching `!#endif` for `!#if !env_testmobile`, and in such case uBO considers the filter list to have processing directive errors in it and cancels pre-processing as a consequence.

**Comment by grenzor** [comment]
Is it possible to disregard just `!#if !env_testmobile` if it has no matching `!#endif` and process only the known directives with proper if/endif matching instead of canceling pre-processing?

**Comment by uBlock-user** [comment]
`!#if !env_testmobile` is just one example of an invalid directive, same thing will happen if you use `!#if !env_fakemobile` which is also an invalid directive, disregarding won't cover the issue at large.

**Comment by grenzor** [comment]
@uBlock-user 

I don't mean `!#if !env_testmobile` exactly. I mean any !#if which doesn't have a matching endif.

**Comment by gorhill** [comment]
> Is it possible to disregard

Sure, I could do this. But my stance currently is to not start to be so flexible on mismatched directives in filter lists. Being strict forces list maintainers to not be sloppy with regard to directives.

**Comment by grenzor** [comment]
But it also means an accidental typo by a filter list maintainer in a single endif (e.g. `!# endif`) could make pre-processing filters in all filter lists stop working, no?

**Comment by grenzor** [comment]
>It's per list, other lists would be unaffected.

Ah ok, that makes it less of issue then. 

>uBO won't second guess authors

Just my thoughts on second guessing authors (let me know if my thinking is wrong)

In regards to if/endif (not sure if same for other directives) I don't think any filter list maintainers would purposely miss an endif, it would have to be accidental or a typo. uBO currently cancels pre-processing if it finds just one unmatched directive so filters within all directives will be applied everywhere. 

With disregarding unmatched directives, only the filters after the mismatched !#if directive until the next known/matching !#if directive should be applied everywhere and the ones found within matching directives will be applied based on the filter maintainers' matching directives which to me seems better than applying all the filters everywhere.

**Comment by gorhill** [comment]
> until the next known/matching `!#if` directive

This is second guessing, uBO is unable to make any assumption one way or another. How do you know whether the next `!#if` is meant to be adjacent or contained within the previous `!#if`? There is no way to know this.

Simplest approach is to forfeit parsing any directive if there is at least one unmatched `!#if`/`!#endif`, I do not intend to change this.

**Comment by grenzor** [comment]
>How do you know whether the next !#if was meant to be adjacent or contained within the previous !#if

Didn't realize uBO accepted ifs within ifs...that does make it impossible to guess. 

If you think it's best not to change anything then I'm fine with that. I'll close the issue.

**Comment by garry-ut99** [comment]
> As [per source code](https://github.com/gorhill/uBlock/blob/8be1aed04d641210ad5e778e17496ea097a125b5/platform/chromium/vapi-common.js#L60), this can happen only if the user agent string contains the word `Mobile`.

> So it could happen if he was spoofing his UA and his UA contained `Mobile` ?

> Maybe, I am guessing extensions' environment would also be affected by a browser-level spoofing of the user agent string. But then, that uBlock starts to behave as it is on a mobile device is the expected outcome -- it actually fulfills the users wish that the browser behaves as if on a mobile device.

In Mobile Device Simulation Mode (Reponsive Design Mode), in both Firefox & Opera, both `env_mobile` and `!env_mobile` directives don't work:

`example.com` isn't blocked in Mobile Simulation, but it should:
```
!#if env_mobile
||example.com^
!#endif
```

`example.com` is blocked in Mobile Simulation, but it shouldn't:
```
!#if !env_mobile
||example.com^
!#endif
```

Despite the both UA strings in both Firefox & Opera contain "Mobile" when using Mobile Mode
(in Opera, while in Simulation Mode, you additionally can tick Menu (...) ==> "Add Device Type" but it doesn't change much as even without it, the UA strings already contain "Mobile" anyway) :

> https://firefox-source-docs.mozilla.org/devtools-user/responsive_design_mode/#device-selection :
> Additionally, Firefox sets the [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) HTTP request header to identify itself as the default browser on the selected device. For example, if you’ve selected an iPhone, then Firefox identifies itself as Safari. The [navigator.userAgent](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgent) property is set to the same value.

What I observed is that the both UA strings contain "Mobile" but only for a single tab where the Mobile Mode is enabled. The other tabs which are opened in a normal Desktop view, don't contain modified UA therefore don;t contain "Mobile". It seems as uBO still reading UA strings from the other tabs which are opened in Desktop mode, ignoring UA strings served by Mobile Design Mode tab.

**Comment by gwarser** [comment]
Try setting: `modifyWebextFlavor +mobile`.

**Comment by garry-ut99** [comment]
I somehow missed that setting, it works.

It's better than nothing, but still not perfect either, given I have already 3 different browser profiles running at the same time: a main unclean Firefox profile for daily browsing internet + a clean Firefox for testing + a clean Opera for testing, now I will need to run 2 additional browser profiles for Mobile testing (Firefox + Opera), which in total will give 5 browser profiles running at the same time, it's getting more and more crowded and complicated here.

It seems the way uBO works is that it must decide at the launch time whether it's Desktop or Mobile, and can't dynamically switch between the platform flavours per tab basis, I'm not sure whether it's uBO's limitation or a browser's limitation.

**Comment by gorhill** [comment]
`!#if`-`!#endif` are preparser directtives, they tell uBO what filters to load/not load at filter list loading time. Having different listset for different tabs is not something supported by uBO.
