### ISSUE TITLE
[Bug] Popup stopped working in Tor Browser 11

### ISSUE THREAD

**Issue by tomas-chrastina** [uBlockOrigin/uBlock-issues#1833]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

After update of **Tor Browser** from version **10.5.10** to version **11.0** uBlocke stopped working. The problem is still present in the latest version **11.0.1**.

When I try to open uBlock popup from toolbar, it is empty, and not resized to full size of standard working popup.

![image](https://user-images.githubusercontent.com/14962885/142913966-0dd0f560-96e4-4cac-a0e2-a214efd3e22e.png)

- Other AddOns are working just fine. But some of them are temporary broken (till restart of browser) on first attempt to open uBlock.
- Sometimes uBlock opens correctly. But after few clicks = open/close it breaks. Also I can see some attempt to resize popup, but no success.
- uBlock works in clean installation of **Firefox 91.3.0esr (64-bit)**.

I'm not sure, but I guess there was similar issue in some older version with uBlock popup size or something? Can't remember what it was.

### A specific URL where the issue occurs

https://www.torproject.org

### Steps to Reproduce

1. Install Tor Browser
2. Disable all (pre-installed) extensions
3. Install uBlock
4. Try to open uBlock popup on any site

### Expected behavior

I expect to popup display controls and addon to work.

### Actual behavior

Popup is empty and uBlock doesn't work. 

### uBlock Origin version

1.38.6 / 1.38.7rc2 / 1.38.7rc4

### Browser name and version

Tor Browser 11.0.1 & 11.0 (Firefox 91.3.0esr)

### Operating System and version

Windows 10 & 7

**Comment by gwarser** [comment]
Tor Browser issue https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40698

**Comment by gorhill** [comment]
This is a browser issue, affecting extensions in general, not just uBO.

**Comment by gorhill** [comment]
Something to verify is that _"Run in Private Windows"_ is checked for uBO. I had to do this on my side.

**Comment by jurekb** [comment]
@gorhill
Restarted TB.
TB - uBO - Run in Private Windows checkd to Allow places uBO item in TB Toolbar. This makes Preferences available too.
Restarted TB.
uBO - Dashboard - Settings - Back up to file opens dialog box with "Download file", then preset "Open with" instead of "Opening ..." and "Save File" (comparison with uBO in regular Firefox).

**Comment by tomas-chrastina** [comment]
> Something to verify is that _"Run in Private Windows"_ is checked for uBO. I had to do this on my side.

Thank you for asking. Sure I have checked it, otherwise it won't be even displayed in toolbar.
Tor Browser is working in private mode by design, so there's no other way around, just to allow addon to Run in Private Windows.

For the time being I'm using ABP. But I feel like my hands are tied all the time.

**Comment by R-Adrian** [comment]
> Tor Browser issue https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40698

the weird thing is that the URL that you mentioned results in a HTTP 404 error but issues 40699 and 40697 (+1 or -1 of it) will load just fine.

Any idea why the Tor issue 40698 was nuked as if it never existed?

![image](https://user-images.githubusercontent.com/16319504/146654632-a68947b7-43cf-4af6-837b-a9e58529cea7.png)

**Comment by gwarser** [comment]
This commit mentions `tor-browser#40698` https://gitlab.torproject.org/tpo/applications/tor-browser/-/commit/1542d19fd888586801eba130a6750ab0cbd93e9e

**Comment by gwarser** [comment]
>Mozilla made the decision to restrict access in response to the severity and/or nature of the issue, I believe, and we followed suit. Like I said above, I'll clarify the status of it on the blog and forum as I appreciate there's no longer a public link you can track progress on.

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40677#note_2765525

**Comment by gwarser** [comment]
They mention WASM, so maybe toggling `https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#disablewebassembly` will help if you still have the issue.

**Comment by gorhill** [comment]
If I recall correctly WASM paths weren't working in Tor browser because it's disable in `about:config`, so uBO always fell back to JS paths.

**Comment by tomas-chrastina** [comment]
Issue 40698 existed for quite some time, and is also mentioned in changelog of the latest release:
**11.0.3 (Firefox 91.4.1esr)** -> [changelog](https://blog.torproject.org/new-release-tor-browser-1103/) (with the same non-functional link to issue)

It looks like it's working again. Tried to open about 100 tabs "at once", few open/close popup cycles, looks fine (fingers crossed).
