### ISSUE TITLE
Add mouseover explanations for left half of menu too

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uBlock-issues#1838]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Here the items on the right half all have mouseover explanations,
but the items on the left side lack them.

### A specific URL where the issue occurs

example.com

### Steps to Reproduce

1. Click more, revealing:

![20211124T081546](https://user-images.githubusercontent.com/1230959/143149161-2763ee12-786b-4c00-94ec-9aa5da816a35.jpg)

### Expected behavior

Mouseover provided for all items, even if they are documented elsewhere.

### Actual behavior

Mouseover missing.

### Configuration

```yaml
uBlock Origin: 1.38.7rc2
Chromium: 98
filterset (summary): 
  network: 77867
  cosmetic: 39213
  scriptlet: 16210
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 60949-6, 1d.11h.2m
    easyprivacy: 26278-20, 1d.11h
    plowe-0: 3698-808, 1d.10h.58m
    ublock-abuse: 67-0, 1d.10h.54m
    ublock-badware: 3420-56, 1d.10h.50m
    ublock-filters: 29740-113, 1d.10h.47m
    ublock-privacy: 186-3, 1d.10h.45m
    ublock-unbreak: 1690-38, 1d.10h.43m
    urlhaus-1: 8448-0, 9h.30m
filterset (user): [empty]
trustedset: 
  added: [array of 17 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2436
  launchFromSelfie: true

```

**Comment by jidanni** [comment]
So all four rectangles here need mouseovers! Thanks.
![20211124T082454](https://user-images.githubusercontent.com/1230959/143149431-c13a3ec8-8b49-4a9d-a9ff-13a6c5332f65.jpg)

**Comment by gothic-bum** [comment]
Did you see the following issue which includes a comment by gorhill, as well as several related issues marked as "Closed":
https://github.com/gorhill/uBlock/issues/840

**Comment by jidanni** [comment]
I didn't see them because I searched for "mouseover".
Hmm, indeed, a lot of requests mounting up.

**Comment by jidanni** [comment]
Note Advanced User Mode is **not** checked, so mouseovers should be provided
![20211124T085032](https://user-images.githubusercontent.com/1230959/143151600-3d2f2999-c657-4c8c-a7d7-0e721ff279aa.jpg)

**Comment by jidanni** [comment]
The Configuration section in comment 0 above should show if the user is using Advanced User Mode or not.
Alas, it apparently doesn't.

**Comment by uBlock-user** [comment]
Tooltips are enabled by default.

**Comment by gorhill** [comment]
Declined.
