### ISSUE TITLE
Version 1.39.0 (neither 1.38.6) is NOT in the Edge Store

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#1841]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In https://github.com/gorhill/uBlock/releases/tag/1.38.6 it says that it can also be found in the Edge Store, 
but in the Edge Store is still version 1.38.4.

### A specific URL where the issue occurs

https://microsoftedge.microsoft.com/addons/detail/odfafepnkmbhccpbejgmiehpchacaeak

### Steps to Reproduce

1. click on [this link](https://microsoftedge.microsoft.com/addons/detail/odfafepnkmbhccpbejgmiehpchacaeak)
2. see that's there still version 1.38.4

### Expected behavior

There must be version 1.39.0 in the Edge Store

### Actual behavior

uBlock extension is not updated.

### uBlock Origin version

1.38.4

### Browser name and version

Microsoft Edge v96

### Operating System and version

Windows 10, 21H1

**Comment by gorhill** [comment]
Please, don't be a burden on volunteers.
