### ISSUE TITLE
Dutch translation `Troubleshooting Information` is wrong

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uBlock-issues#1842]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The Dutch translation of `Troubleshooting Information` is currently `Probleemoplossingeninformatie`
but is should be "Probleemoplossing**s**informatie"

### A specific URL where the issue occurs

moz-extension://2707bfd1-e7b2-4eb5-ac1c-5880da5bed96/dashboard.html#support.html

### Steps to Reproduce

1. Open "Support" panel on browser with standard language Dutch
2. Scroll down and see the Dutch word `Probleemoplossingeninformatie`

### Expected behavior

Probleemoplossing**s**informatie

### Actual behavior

Is says "Probleemoplossing**en**informatie"

### Configuration

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 67268
  cosmetic: 39978
  scriptlet: 16088
  html: 596
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    NLD-0: null
  added: 
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt: 1722-0, 2d.1h.30m
  default: 
    ublock-filters: 30297-65, 2d.1h.30m
    ublock-privacy: 182-0, 2d.1h.30m
    ublock-unbreak: 1701-12, 2d.1h.30m
    easylist: 60950-489, 2d.1h.30m
    easyprivacy: 26278-474, 2d.1h.30m
    plowe-0: 3698-1, 2d.1h.30m
filterset (user): [array of 279 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 155 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  dynamicFilteringEnabled: true
  largeMediaSize: 100
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}}
  autoUpdateAssetFetchPeriod: 1
  autoUpdateDelayAfterLaunch: 3
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#000092 00001/#2A2A2A
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
  uiPopupConfig: scrollbar-width: thin !important;
supportStats: 
  launchToReadiness: 2431
  launchFromSelfie: true
```

**Comment by gorhill** [comment]
Translations are handled at <https://crowdin.com/project/ublock>, no here.

**Comment by gorhill** [comment]
Also, if you want to contribute constructively to translations, please use the dev build so that you can contribute fixing those translation issues before the stable release is published.
