### ISSUE TITLE
Security: incomplete fix for css comment blocking

### ISSUE THREAD

**Issue by taviso** [uBlockOrigin/uBlock-issues#1843]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I think I've found a variant of #1693 that still works and wasn't fixed by [a2d8545](https://github.com/gorhill/uBlock/commit/a2d85453820cd2016dc45d904870b4cdafb6bc25). You're still allowed to use comments in selectors, just not in `:style()`.

So, something like this will still work:

```
example.com##a /*
```

The tricky part is making a selector that parses with and without comments removed, but I found a solution:

```
example.com##a /*
example.com##a[href*="*/, body { background-image: url(https://google.com/favicon.ico); background-size: cover } /*"]
example.com##a /**/ 
```

### A specific URL where the issue occurs

https://www.example.com/

### Steps to Reproduce

1. Create the following filter in My filters:

```
example.com##a /* 
example.com##a[href*="*/, body { background-image: url(https://google.com/favicon.ico); background-size: cover } /*"]
example.com##a /**/ 
```

2. Visit example.com

### Expected behavior

`url()` should be either banned or removed before injection.

### Actual behavior

`url()` is not banned.

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 96

### Operating System and version

Fedora 35

**Comment by gorhill** [comment]
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1806>?

I cannot reproduce the issue with your repro steps with the [latest dev build or with version 1.39.0](https://github.com/gorhill/uBlock/releases), the first cosmetic filter is rejected by uBO:

![Screenshot from 2021-11-24 17-42-00](https://user-images.githubusercontent.com/585534/143321990-4c59cac8-3ef4-4f70-942e-5f2284d10ebe.png)

**Comment by taviso** [comment]
Ah-ha, I think you're right!
