### ISSUE TITLE
Link to filter descriptions

### ISSUE THREAD

**Issue by breyed** [uBlockOrigin/uBlock-issues#1846]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

If you click the Home button for one of the EasyList filter lists in uBlock settings, you go to a forum with no clear way to find info on a given filter. For a new user unfamiliar with the goals of the filters, the home links are not helpful.

[This patch](https://github.com/gorhill/uBlock/compare/master...breyed:patch-1) sets the Home button links for the EasyList filters to go to a page that succinctly describes what each filter does.

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Click the Home button for Fanboy’s Annoyance

### Expected behavior

Learn what Fanboy’s Annoyance does.

### Actual behavior

See a forum where you can read thousands of posts.

### uBlock Origin version

1.38.6

### Browser name and version

Chrome 96.0.4664.55

### Operating System and version

macOS 12.0.1

**Comment by gorhill** [comment]
[Patch imported](https://github.com/gorhill/uBlock/commit/95a105da1a524c65879d47e131ff0720de91cd18), thanks. This merged patch means next time you can submit a pull request directly to the uBlock repo.

**Comment by gwarser** [comment]
Does it have links to place where issues can be reported?

**Comment by gorhill** [comment]
Yes, at the bottom of the page it says:

> If you should encounter unwanted items or problems with the EasyList filter lists you should report the issues in the EasyList Forums.

And there is the _Forum_ button the top nac bar.

**Comment by felix-22** [comment]
> gwarser: Does it have links to place where issues can be reported?

Doesn't it?

**1**
![3](https://user-images.githubusercontent.com/75935068/143597917-9c294a49-1423-444b-90a6-e9bc9d7eba63.png)
**2**
![4](https://user-images.githubusercontent.com/75935068/143597920-50365675-937f-4311-a240-aa1ae0cec1a6.png)

**Comment by gwarser** [comment]
Ah, sorry, I did not noticed. On my phone this looks like another list description.

**Comment by felix-22** [comment]
> gorhill: [Patch imported](https://github.com/gorhill/uBlock/commit/95a105da1a524c65879d47e131ff0720de91cd18), 

Link to the issue ( https://github.com/uBlockOrigin/uBlock-issues/issues/1846 ) is missing in the commit description:

<hr>

![xxx - Kopia](https://user-images.githubusercontent.com/75935068/143624580-c2194627-71d2-4b92-8a67-ee2c5030338f.png)

**Comment by felix-22** [comment]
The missing link to the related issue can be still provided in the commit's comment in this case:

Before:
![1 (1)b](https://user-images.githubusercontent.com/75935068/143675050-c22a7826-01e5-4f03-ab96-dc3484693c1e.png)

After:
![1 (1)](https://user-images.githubusercontent.com/75935068/143675058-66975fd7-c525-4698-a61e-9031290a944f.png)

**Comment by felix-22** [comment]
Also, given:

- Home Page link for AdGuard filters is currently:
  - https://github.com/AdguardTeam/AdguardFilters#adguard-filters and not:
  - https://github.com/AdguardTeam/AdguardFilters/issues
- the OP's requests logic and reasoning

then Home Page link for uBlock filters:
- https://github.com/uBlockOrigin/uAssets/issues should be changed to:
- https://github.com/uBlockOrigin/uAssets#uassets

**Comment by breyed** [comment]
To take @felix-22's good observation about other filters a step further, I think a better overall user experience would use a less is more approach. Currently, there can be up to three icons, which are equivalents of 👁🏚ℹ️. It's not obvious to a new user what these icons mean until you experiment a bit. You're already confronted with a couple dozen filters to choose from. Having that many times up to three buttons each is a lot.

I think the best experience is show only a single icon, ℹ️, which links to a page with a brief overview of the filter's goals. That same page should also link to the filter's text and where to report bugs. Of course, many of the filters are outside uBlock's control; however, most of the descriptive pages (if not all) have those links already, and PRs can be submitted for any that don't.

For Adguard, I recommend linking to [Adguard filters](https://kb.adguard.com/en/general/adguard-ad-filters#adguard-filters) in their knowledge base.

For uBlock, I recommend linking to [uAssets](https://github.com/uBlockOrigin/uAssets#uassets) as @felix-22 suggested. I also recommend reorganizing the uAssets readme to highlight the lists and descriptions at the top. I can submit a PR if there's a consensus on this approach.

**Comment by gorhill** [comment]
The eye icon is to show the content using uBO's own editor, which comes with handy search tool and syntax highlighting, no outside page can replace this.

**Comment by felix-22** [comment]
> breyed : Currently, there can be up to three icons,

Four icons:
<img src="https://user-images.githubusercontent.com/75935068/143690406-259e59cc-0c97-48c3-9e6c-b2100758b908.png" width="400">

> breyed : which are equivalents of
> breyed :  I think the best experience is show only a single icon,

I disagree:
- each icon have it's own functionality, they are useful
- before jumping to conclusions you should read about their functionalities in documentation 
  https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists

> breyed : It's not obvious to a new user what these icons mean until you experiment a bit.

I disagree:
- as above it's described in the documentation
- additionally, each icon has it's tips after hovering over by mouse cursor

> breyed : For Adguard, I recommend linking to [Adguard filters](https://kb.adguard.com/en/general/adguard-ad-filters#adguard-filters) in their knowledge base.

I disagree:
- I was thinking about it before, but I discarded it, as the link to AdGuard documentation you've provided can be found in the current AdGuard Home Page in uBO: 

> https://github.com/AdguardTeam/AdguardFilters#suggest-filtering-rules :
>
> ![e](https://user-images.githubusercontent.com/75935068/143690184-6506de8d-6b6b-4573-91af-2d5d85a126d9.png)

> breyed :  For uBlock, I recommend linking to uAssets as @felix-22 suggested

I agree, I explained why, in my previous comment.

**Comment by hirorpt** [comment]
I think `https://easylist.to/`, which seems outdated, is inappropriate for the filter description. It is best to link to [their GitHub repository](https://github.com/easylist/easylist).
For example, for how to report an issue, `https://easylist.to/` doesn't mention GitHub, nor does it say that anti-adblock are basically out of scope.

**Comment by breyed** [comment]
@felix-22 Those are all good points. As you probably guessed, I didn't read the docs, or even think to see if there were any. In general, that's a good thing. The whole point of uBlock is to let you get about your business of using the web with minimal interference. The easier the uBlock UI is to use - just on its own - the better.

A good design goal is to support the casual user who just wants to block a given set of content and get about his business on the web _and_ a user who wants to read up on the intricacies of uBlock and become an expert. uBlock is very fast and powerful, but doesn't yet provide good guidance to the casual user.

Here's a quick case study. (This is what led me to post this issue in the first place.) As a long-time casual uBlock user, I was getting tired of endless sites asking me about cookies. I wondered if uBlock could be configured to block the cookie warnings. It wasn't at all clear looking at the uBlock filter lists option page whether it good. After a bunch of web searching, I figured it out, but it would be much better if the experience was quicker and easier.

In general, a valuable feature is to enable a casual user to quickly make informed decisions on the choices of blocking more relative to any performance and breakage costs. Thinking about this more, a way to help accomplish this is to provide expandable descriptions under each filter on the options page, with an option to expand all. In my sample use case above, I would click Expand All and search with Command+F for "cookie" - a huge improvement over clicking on a bunch of website links and searching each.

Expandable descriptions would avoid undesirable UI tradeoffs. For example, linking to AdGuard's [suggest-filtering-rules](https://github.com/AdguardTeam/AdguardFilters#suggest-filtering-rules) is good for quick access to making suggestions; however, the tradeoff is that the basics of what the filter does are buried more than a paragraph down and an extra click away. To get the best of both worlds (a clear description front and center _and_ clear info on how to contribute), follow the description on the filter list page by a link labeled [Contribute](https://github.com/AdguardTeam/AdguardFilters#suggest-filtering-rules). With example descriptions, you get the full clarify without overwhelming the user.

Expandable descriptions would also alleviate the tradeoffs inherent in the tooltips, too. I hadn't even noticed the tooltips, which is likely typical. Tooltips have poor discoverability these days since they are not used much any more. They're not touch friendly and they're slow; you have to wait about 3 seconds for the info to appear. As with any suboptimal UI elements, if you can design them out of the UI to eliminate their downsides, but without sacrificing their value (by providing it in an alternative way), it's a design win.

**Comment by u-RraaLL** [comment]
> I would **click Expand All** and search with Command+F for "cookie" 

Click the filter counter line (above "My filters"). Proceed.

Anyway, I'm not so sure about expansive (expendable or not) descriptions. Lists have clear section labels and most lists have a a simple description inside - you just need to click the eye icon to open them.

**Comment by breyed** [comment]
> Click the filter counter line (above "My filters").

That's a great example. I'm talking about applying to that hide/show approach beyond whether unselected lists are visible - to let the user hide/show list descriptions.

> Lists have clear section labels

Some are clear. For others (like annoyance and multipurpose), new users would benefit from a sentence or two describing what's all included (e.g. "don't tell me about cookies" filters).

> you just need to click the eye icon to open them

Some of the lists have descriptions in their comments. Others don't. Even the ones that do often have lots of boilerplate to wade through to find the description. Plus, there's no easy way to see the descriptions together at a glance. For example, some lists are supersets of others. It would be great to not have to go digging to see that.

Not having to go digging is a key point. Good UI is more than making it _possible_ to get the info you need. It's there; that's not the issue. The question is how can quickly and easily can 90% of users access the info they're most likely to need.

**Comment by felix-22** [comment]
> hirorpt : https://github.com/uBlockOrigin/uBlock-issues/issues/1846#issuecomment-980784683 : I think `https://easylist.to/`, which seems outdated, is inappropriate for the filter description. It is best to link to [their GitHub repository](https://github.com/easylist/easylist). For example, for how to report an issue, `https://easylist.to/` doesn't mention GitHub, nor does it say that anti-adblock are basically out of scope.

- while creating [my previous comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1846#issuecomment-980579180) I was about to mention the EasyList github link but I resigned somehow, most probably because I was thinking that the current link `https://easylist.to/`should stay, but after reading your  comment, I'm not sure anymore which one is the best, worth reconsidering
- I was about to mention also another one, Home Page for Fanboy's Annoyaces lists: https://fanboy.co.nz/
> hirorpt : [their GitHub repository](https://github.com/easylist/easylist)

- a technical hint: if you read [my previous comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1846#issuecomment-980579180) carefully, a proper link should include the header, should be: 
https://github.com/easylist/easylist#easylist--easyprivacy--fanboy-lists, not just https://github.com/easylist/easylist

<hr>

> breyed : 
> 
> > u-RraaLL : Click the filter counter line (above "My filters").
>
> breyed : That's a great example. I'm talking about applying to that hide/show approach beyond whether unselected lists are visible - to let the user hide/show list descriptions.

- if this is ever going to be implemented in uBO, I'm providing the implementation prototype (because I don't want to be unnecessarily spammed and overwhelmed by filter lists's descriptions like in AdGuard AdBlocker when I only want to see filter lists's names):
<img src="https://user-images.githubusercontent.com/75935068/143734977-4c252883-0616-46f3-9e1c-ee3c19c19c2b.png" width="400">

- also you're talking about what AdGuard AdBlocker almost already does, except AdGuard:
  - expands only one section of lists at a time, and not all sections at once
  - descriptions are always expanded and can't be hidden/collapsed

<details>
<summary>SPOILER SCREENSHOOT AdGuard AdBlocker </summary>

![444](https://user-images.githubusercontent.com/75935068/143733899-2a70224e-0395-463b-be66-e9444445a508.png)


I'm in favor of your proposed implementation, than AdGuard's, because I don't want to be unnecessarily spammed and overwhelmed by filter lists's descriptions when I only want to see filter lists's names:

</details>

**Comment by breyed** [comment]
Both use cases are valuable: seeing all filter lists with descriptions, so newer users know which to pick, and seeing just the filter names so that experienced users can find a desired filter at a glance.

The AdGuard descriptions are helpful, but do consume a lot of screen real estate. Without the version, dates, and hashtags, which probably aren't used much, it would be a better balance.

Since users will typically want descriptions initially and then potentially want to hide them as they become expert, descriptions should be shown by default.

The UI would be more intuitive if options related uBlock generally were checkboxes, whereas those specific to the display of the Filter Lists page used button links (+/- buttons or words). The UI settings can still be persisted, however.

The existing expand/collapse all sections link is not very discoverable. In part this is because the +/- metaphor normally only applies to the block immediately below, not the whole page. A clear control would solve this.

Putting this all together, here's a conceptual prototype:

----

87,146 network filters, 90,845 cosmetic filters
[Expand all sections]()         [Hide descriptions]()

[ ] My filters
     Personal filters, included those created using "Block element".

– Built-in (5/5)

…

----

"Expand all sections" would toggle between that and "Collapse all sections". "Hide descriptions" would toggle between that and "Show descriptions".

There should be some padding between the three option checkboxes and the filter counts, to delineate a new portion of the page. The descriptions should be gray.

**Comment by felix-22** [comment]
> breyed : Both use cases are valuable: seeing all filter lists with descriptions, so newer users know which to pick, and seeing just the filter names so that experienced users can find a desired filter at a glance.

Yes, being an advanced user of many years was the exact reason I mentioned my prototype, I don't need descriptions at this stage anymore, they would be more disturbing than useful, which is the opposite for new users.

> breyed : "Expand all sections" would toggle between that and "Collapse all sections". "Hide descriptions" would toggle between that and "Show descriptions".

So expanding a single section wouldn't be possible anymore?
