### ISSUE TITLE
Get back open-in-newtab switch by SHIFT key for the logger on mobile

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1847]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I know the logger icon on the popup was removed on mobile so now it should be opened via support pane. But now it opens in new window by default on *emulated* mobile browser. It had been possible to switch the behavior with SHIFT key, but now this is not possible. This may be a personal request but it's inconvinient as I use emulated Android for quick screening of issues and also use a dedicated profile than UA switcher, because I often check both PC and mobile (and both uBO and AG) simultenously - you'll find in my commit history at AG it's not rare both Mobile filters and Base/Japanese filters are edited at the same commit.

### A specific URL where the issue occurs

moz-extension://EXTENSION ID/dashboard.html#support.html

### Steps to Reproduce

1. Set `general.useragent.override` to any of mobile UA such as `Mozilla/5.0 (Android 11; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0` on `about:config` and restart Firefox
2. Go to Support pane
3. Open the logger with SHIFT key pushed

### Expected behavior

With SHIFT key it should be opened in new tab

### Actual behavior

Opened in new window by default if you didn't change before update to 1.39

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Would having to add the token `+logger` to `uiPopupConfig` work for you? (the same way it's possible to a;so add the no-popups switch back in the mobile version of the popup panel.)

**Comment by Yuki2718** [comment]
Yeah, if I understand correctly that should fix https://github.com/uBlockOrigin/uBlock-issues/issues/1848 as well.
