### ISSUE TITLE
Add logger icon on the issue reporter

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1848]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

TBH I often use the logger on real Android too. I understand https://github.com/uBlockOrigin/uBlock-issues/issues/1817#issuecomment-968969814 , but is it trivial to add the logger icon on the issue reporter? This means one less action than swithcing to Dashboard -> Support -> open the logger, and also is intuitive for those who had been using the logger icon. Also I often loose the logger link in the Support pane which is surrounded by two links for issue tracker. The icon will be more intuitve and salient than words.

### A specific URL where the issue occurs

moz-extension://EXTENSION ID/support.html?reportURL=CURRENT PAGE

### Steps to Reproduce

NA

### Expected behavior

NA, it's just more convinient if can be achieved by trivial code change.

### Actual behavior

It's bit bothering opening the logger on Android.

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 95.0.0-beta.6

### Operating System and version

Android 12

**Comment by gwarser** [comment]
Fixed as per https://github.com/uBlockOrigin/uBlock-issues/issues/1847#issuecomment-980665284
