### ISSUE TITLE
CNAME and font (un)blocking can't be together

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uBlock-issues#1849]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

When you block fonts via the followign rule `*$font,3p` third-party fonts loaded via CNAME's are also blocked,
which is normal behaviour.
However if you want to unblocked 3p fonts loaded via CNAME's, it isn't possible;
`*$font,3p,~cname` or `@@$font,3p,cname` will trow a error
![afbeelding](https://user-images.githubusercontent.com/80090789/143683520-34683fd1-1797-41f2-838c-1eaab67dd064.png)
So currently font and cname can't go together.
My feature request is, that font and cname go together (so that this will be possible: `*$font,3p,~cname`)

### A specific URL where the issue occurs

https://www.eset.com/; https://www.malwarebytes.com/

### Steps to Reproduce

1. Open uBo settings
2. Add `*$font,3p,~cname` to My filters
3. See that it isn't possible
4. Change the rule to `*$font,3p`
5. Open uBo Logger
6. Open `https://www.eset.com/` or `https://www.malwarebytes.com/`
7. See that 1p fonts are not blocked, but then their cnames (which are 3p) are blocked

### Expected behavior

That is would be possible to make the following rule: `*$font,3p,~cname`

### Actual behavior

`*$font,3p,~cname` isn't a valid rule

### Configuration

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 67505
  cosmetic: 40036
  scriptlet: 15988
  html: 596
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-abuse: null
    urlhaus-1: null
    NLD-0: null
  added: 
    https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/easydutch.txt: 1751-0, 1d.7h.44m
  default: 
    ublock-filters: 30185-155, 1d.7h.44m
    ublock-privacy: 182-0, 1d.7h.44m
    ublock-unbreak: 1706-12, 1d.7h.44m
    easylist: 61151-392, 1d.7h.44m
    easyprivacy: 26335-482, 1d.7h.44m
    plowe-0: 3699-1, 1d.7h.44m
filterset (user): [array of 304 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 1038 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 8 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  dynamicFilteringEnabled: true
  prefetchingDisabled: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}}
  autoUpdateAssetFetchPeriod: 1
  autoUpdateDelayAfterLaunch: 3
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#000092 00001/#2A2A2A
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 12px
  uiPopupConfig: scrollbar-width: thin !important;
supportStats: 
  launchToReadiness: 1838
  launchFromSelfie: true
```

**Comment by gorhill** [comment]
Yes, by design: <https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#cname>.

`cname` is to be used to wholly disable canonical name-uncloaking on a page, the same way `ghide` is meant to disable generic cosmetic filtering on a page.

**Comment by BPower0036** [comment]
But can change that behaviour?

**Comment by gorhill** [comment]
No, what you are asking is anything but trivial, and not worth it in my opinion.
