### ISSUE TITLE
Element Zapper denies on a specific website

### ISSUE THREAD

**Issue by KrischnaGabriel** [uBlockOrigin/uBlock-issues#1850]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The element zapper is not capable of selecting nor removing any elements from this website.

### A specific URL where the issue occurs

https://www.db.com/legal-resources/index?language_id=1

### Steps to Reproduce

1. Open a clean Chromium or Firefox profile.
2. Install uBlock.
3. Go to the mentioned website.
4. After clicking the uBlock icon in the toolbar, activate the element zapper mode.
5. Try to remove an element (like the cookie prompt) with the zapper.

### Expected behavior

Highlighting of the mouse-hovered element and when clicking, removing the selected element.

### Actual behavior

None of the elements are being highlighted, when hovering over them.
When clicking any html element on the website, nothing happens.

### uBlock Origin version

Version 1.39.0

### Browser name and version

firefox=94.0  &  chromium=96.0.4664.45

### Operating System and version

Linux Mint 20.2 Cinnamon

**Comment by gorhill** [comment]
The site is hiding its cookie overlay into the shadowroot of a div which has a height of 0. The zapper requires that the click be made on an highligthed element, while in this case it's not possible to highlight because of the height being zero.

A possible solution would be to have a minimal height/width for highligthed portion.
