### ISSUE TITLE
"Your request URL is too long": problem with too many filters and the new "problem with filter lists" button

### ISSUE THREAD

**Issue by 4DEATH** [uBlockOrigin/uBlock-issues#1852]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When you have more than "normal" amount of custom filter lists, Ublock Origin attempt to create new filter list report will fail because of GitHubs long url block.

![20211129-174958-851x345-uBlock_Origin_—_Support_—_Mozilla_Firefox-1638197398](https://user-images.githubusercontent.com/9417033/143889767-c9f0c7e4-627a-4bba-add1-c76a065560f6.png)
![20211129-175241-456x212-Bad_request_·_GitHub_—_Mozilla_Firefox-1638197561](https://user-images.githubusercontent.com/9417033/143889818-8c0d6a64-61fd-4fd4-bd9f-1684b6fee849.png)

<details><summary>Example URL that fails:</summary>

    https://github.com/uBlockOrigin/uAssets/issues/new?template=specific_report_from_ubo.yml&title=youtube.com%3A+ads&url_address_of_the_web_page=`https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DVxwx5VflRN4`&category=ads&configuration=%3Cdetails%3E%0A%0A```yaml%0AuBlock+Origin%3A+1.39.0%0AFirefox%3A+94%0Afilterset+(summary)%3A+%0A++network%3A+896753%0A++cosmetic%3A+276772%0A++scriptlet%3A+51331%0A++html%3A+638%0Alistset+(total-discarded%2C+last+updated)%3A+%0A++added%3A+%0A++++https%3A%2F%2Fabp.oisd.nl%2F%3A+307930-141337%2C+4h.48m%0A++++https%3A%2F%2Fblock.energized.pro%2Fextensions%2Fregional%2Fformats%2Ffilter%3A+31666-1979%2C+4h.48m%0A++++https%3A%2F%2Fblock.energized.pro%2Fultimate%2Fformats%2Ffilter%3A+506013-59356%2C+4h.48m%0A++++https%3A%2F%2Fdl.dropboxusercontent.com%2Fs%2F1ybzw9lb7m1qiyl%2FAAs.txt%3A+911-17%2C+4h.48m%0A++++https%3A%2F%2Feasylist-msie.adblockplus.org%2Fantiadblockfilters.txt%3A+847-70%2C+4h.49m%0A++++https%3A%2F%2Ffanboy.co.nz%2Ffanboy-problematic-sites.txt%3A+1957-14%2C+4h.49m%0A++++https%3A%2F%2Ffanboy.co.nz%2Ffanboy-turkish.txt%3A+823-0%2C+4h.48m%0A++++https%3A%2F%2Fgitcdn.xyz%2Frepo%2FNanoAdblocker%2FNanoFilters%2Fmaster%2FNanoMirror%2FNanoDefender.txt%3A+2641-32%2C+never%0A++++https%3A%2F%2Fgitlab.com%2FSorrow-San%2F9anime-adblock-filters%2Fraw%2Fmaster%2F9Anime%2520filter%2520list%3A+105-0%2C+4h.49m%0A++++https%3A%2F%2Fgitlab.com%2FZeroDot1%2FCoinBlockerLists%2Fraw%2Fmaster%2Flist_browser_UBO.txt%3A+834-0%2C+4h.48m%0A++++https%3A%2F%2Fhg.adblockplus.org%2Fantiadblockfilters%2Fraw-file%2Ftip%2Fantiadblockfilters%2Fantiadblock_english.txt%3A+65-1%2C+4h.48m%0A++++https%3A%2F%2Forca.pet%2Fnotonmyshift%2Fabp.txt%3A+1483-2%2C+4h.48m%0A++++https%3A%2F%2Fpaulgb.github.io%2FBarbBlock%2Fblacklists%2Fublock-origin.txt%3A+550-7%2C+4h.48m%0A++++https%3A%2F%2Fraw.github.com%2Fliamja%2FPrebake%2Fmaster%2Fobtrusive.txt%3A+1072-5%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FAdguardTeam%2FAdguardFilters%2Fmaster%2FAnnoyancesFilter%2Fsections%2Fantiadblock.txt%3A+5041-90%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAdRemovalListForUnusualAds.txt%3A+191-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAndroid%2520Scum%2520Class%2520%25E2%2580%2594%2520Fake%2520notification%2520counters.txt%3A+81-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiAmazonListForTwitch.txt%3A+17-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiBadCapitalismList.txt%3A+374-191%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiCartoonHipsterList.txt%3A+7012-4%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiCelebBirthList%3A+403-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiGachaAndKnockoffGamesList.txt%3A+2385-1%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FAntiNonNewsList.txt%3A+1276-403%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FBrowseWebsitesWithoutLoggingIn.txt%3A+262-1%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FGDPR%2520451%2520List.txt%3A+779-1%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FI%2520Don%27t%2520Want%2520to%2520Download%2520Your%2520Browser.txt%3A+51-1%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FRedditTrashRemovalService.txt%3A+134-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FRickrollLinkIdentifier.txt%3A+23-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FSensitive%2520lists%2FAntiAstrologyList.txt%3A+418-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FSensitive%2520lists%2FAntiPreacherList.txt%3A+1569-17%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FSensitive%2520lists%2FTabloidRemover.txt%3A+794-794%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FTwitchEvenMorePureViewingExperience.txt%3A+64-40%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FDandelionSprout%2Fadfilt%2Fmaster%2FWikiaPureBrowsingExperience.txt%3A+56-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FKCaglarCoskun%2Fenur-filter-list%2Fmaster%2Fenur-filter-list.txt%3A+31-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FKarmesinrot%2FAnifiltrs%2Fmaster%2FAnifiltrs%2520Main%2FAnifiltrs%2520extra-main.txt%3A+84-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FKarmesinrot%2FAnifiltrs%2Fmaster%2FAnifltrs.txt%3A+294-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FManu1400%2Fi-don-t-care-about-newsletters%2Fmaster%2Fadp.txt%3A+94-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FMassMove%2FAttackVectors%2Fmaster%2FLocalJournals%2Ffake-local-journals-list.txt%3A+1083-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FPoorPocketsMcNewHold%2Fsteamscamsites%2Fmaster%2Fsteamscamsite.txt%3A+1004-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FSpam404%2Flists%2Fmaster%2Fadblock-list.txt%3A+7253-103%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FYuki2718%2Fadblock%2Fmaster%2Fmedium_mode%2Fanti-allowlist.txt%3A+18-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FYuki2718%2Fadblock%2Fmaster%2Fmedium_mode%2Fstatic-rules.txt%3A+160-2%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FYuki2718%2Fadblock%2Fmaster%2Fno_gen_cosm%2Fphhider.txt%3A+570-9%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FYumire%2Fkiss-filters%2Fmaster%2Ffilters.txt%3A+24-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fbkrucarci%2Fturk-adlist%2Fmaster%2Fhosts%3A+842-38%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fbogachenko%2Ffuckfuckadblock%2Fmaster%2Ffuckfuckadblock.txt%3A+26935-321%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fcaffeinewriter%2FDontPushMe%2Fmaster%2Ffilterlist.txt%3A+47-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fdeathbybandaid%2Fpiholeparser%2Fmaster%2FSubscribable-Lists%2FCountryCodesLists%2FTurkey.txt%3A+1284-53%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fdurablenapkin%2Fscamblocklist%2Fmaster%2Fhosts.txt%3A+1000-3%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fhoshsadiq%2Fadblock-nocoin-list%2Fmaster%2Fnocoin.txt%3A+1030-79%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fhuzunluartemis%2FTurkishAdblockList%2Fmain%2Fsrc%2FElementalList.txt%3A+10799-905%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fhuzunluartemis%2FTurkishAdblockList%2Fmain%2Fsrc%2FHostsList.txt%3A+9690-2057%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Finfinitytec%2Fblocklists%2Fmaster%2Fadfilters.txt%3A+3044-14%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Finfinitytec%2Fblocklists%2Fmaster%2Fannoyances.txt%3A+301-17%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Finfinitytec%2Fblocklists%2Fmaster%2Fmedicalpseudoscience.txt%3A+27910-1544%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fjerryn70%2FGoodbyeAds%2Fmaster%2FFormats%2FGoodbyeAds-AdBlock-Filter.txt%3A+192042-157624%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fjkrejcha%2FAdmiraList%2Fmaster%2FAdmiraList.txt%3A+1025-542%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fkowith337%2FPersonalFilterListCollection%2Fmaster%2Ffilterlist%2Fspecific%2FAntiAPKMirrorCountdown.txt%3A+40-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fkowith337%2FPersonalFilterListCollection%2Fmaster%2Fhosts%2Fhosts_leftover.txt%3A+890-48%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Flassekongo83%2FFrellwits-filter-lists%2Fmaster%2Fi-dont-want-your-app.txt%3A+32-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fluigimannoni%2Fm5s-ublock-filter%2Fmaster%2Ffilter-list.txt%3A+14-0%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fmarktron%2Ffakenews%2Fmaster%2Ffakenews%3A+2197-1130%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fmitchellkrogza%2FSuspicious.Snooping.Sniffing.Hacking.IP.Addresses%2Fmaster%2Fips.list%3A+1361-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Folegwukr%2Fpolish-privacy-filters%2Fmaster%2Fanti-adblock-suplement.txt%3A+196-0%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fparseword%2Fnolovia%2Fmaster%2Fskel%2Fhosts-government-malware.txt%3A+91-1%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2FrampageX%2Ffuckfuckadblock%2Fmaster%2Fmy_antiadblock_selection.txt%3A+24472-5246%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Freek%2Fanti-adblock-killer%2Fmaster%2Fanti-adblock-killer-filters.txt%3A+2196-2043%2C+4h.49m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Frimu%2Fno-qanon%2Fmaster%2Fetc_hosts.txt%3A+5068-660%2C+4h.48m%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fxorcan%2Fhosts%2Fmaster%2Fxhosts.txt%3A+9196-9089%2C+never%0A++++https%3A%2F%2Fraw.githubusercontent.com%2Fyourduskquibbles%2Fwebannoyances%2Fmaster%2Fultralist.txt%3A+42131-1617%2C+4h.48m%0A++++https%3A%2F%2Fwww.fanboy.co.nz%2Fenhancedstats.txt%3A+2993-1973%2C+4h.48m%0A++++https%3A%2F%2Fwww.github.developerdan.com%2Fhosts%2Flists%2Famp-hosts-extended.txt%3A+13678-23%2C+4h.49m%0A++++https%3A%2F%2Fwww.i-dont-care-about-cookies.eu%2Fabp%2F%3A+24076-8312%2C+4h.48m%0A++++https%3A%2F%2Fzerodot1.gitlab.io%2FCoinBlockerLists%2Fhosts_browser%3A+3496-862%2C+4h.48m%0A++++adguard-generic%3A+61722-13300%2C+4h.50m%0A++++adguard-mobile%3A+7009-247%2C+4h.50m%0A++++adguard-spyware%3A+25167-1128%2C+4h.50m%0A++++adguard-annoyance%3A+47885-7758%2C+4h.50m%0A++++adguard-social%3A+14740-48%2C+4h.50m%0A++++fanboy-thirdparty_social%3A+68-0%2C+4h.50m%0A++++fanboy-annoyance%3A+59017-43923%2C+4h.50m%0A++++fanboy-cookiemonster%3A+20428-402%2C+4h.50m%0A++++fanboy-social%3A+23208-1121%2C+4h.49m%0A++++ublock-annoyances%3A+4326-91%2C+4h.49m%0A++++dpollock-0%3A+16967-956%2C+4h.49m%0A++++TUR-0%3A+8992-581%2C+4h.49m%0A++++adguard-spyware-url%3A+393-2%2C+4h.48m%0A++++block-lan%3A+44-11%2C+4h.48m%0A++default%3A+%0A++++ublock-filters%3A+30259-3959%2C+4h.50m%0A++++ublock-badware%3A+3478-13%2C+4h.50m%0A++++ublock-privacy%3A+184-0%2C+4h.50m%0A++++ublock-abuse%3A+74-4%2C+4h.50m%0A++++ublock-unbreak%3A+1709-4%2C+4h.50m%0A++++easylist%3A+61259-13362%2C+4h.50m%0A++++easyprivacy%3A+26385-11904%2C+4h.50m%0A++++urlhaus-1%3A+10229-0%2C+4h.50m%0A++++plowe-0%3A+3697-622%2C+4h.49m%0Afilterset+(user)%3A+[array+of+64+redacted]%0Atrustedset%3A+%0A++added%3A+[array+of+3+redacted]%0AswitchRuleset%3A+%0A++added%3A+[array+of+4+redacted]%0AhostRuleset%3A+%0A++added%3A+[array+of+43+redacted]%0AmodifiedUserSettings%3A+%0A++advancedUserEnabled%3A+true%0A++cloudStorageEnabled%3A+true%0A++firewallPaneMinimized%3A+false%0A++tooltipsDisabled%3A+true%0A++webrtcIPAddressHidden%3A+true%0AmodifiedHiddenSettings%3A+%0A++filterAuthorMode%3A+true%0AsupportStats%3A+%0A++launchToReadiness%3A+1383%0A++launchFromSelfie%3A+true%0A```%0A%3C%2Fdetails%3E
</details>

### Steps to Reproduce

1. Have all prequisites (browser, addon yada yada)
2. Use too many custom filter lists
3. Try to use new report filter issue button
4. Click create new report
5. The opened link will fail

### Expected behavior

Button to work as intended and open github page, or/and Ublock to warn/ask me to input my filter lists manually in topic instead of trying to do it with link

### Actual behavior

Github "Your request URL is too long " error

### uBlock Origin version

1.39.0

### Browser name and version

Firefox 94.0.2

### Operating System and version

Windows 10 21H1 (19043.1288)

**Comment by gorhill** [comment]
How many filter lists do you have?

**Comment by 4DEATH** [comment]
74 custom lists

**Comment by gorhill** [comment]
Ok, I will have to forbid people from creating issues for when they have an undue amount of filter lists enabled, no volunteers will test with your configuration, so there is no point allowing to create report with such configuration.

**Comment by 4DEATH** [comment]
That would be another solution indeed, but isnt logger better way to help with filter issues anyway?

**Comment by gorhill** [comment]
I say it's for you to fix, I rather not have volunteers spend their limited free time fixing personal issues arising as a result of using too many lists.

**Comment by realodix** [comment]
> not have volunteers spend their limited free time fixing personal issues arising as a result of using too many lists.

I totally agree

> Note that the template does ask:
> 
> > * [ ]  I have no custom filter lists, or I verified that the issue still occurs without custom filter lists

I don't think someone can find this (and others) if Github shows an error message.

On the other side, I think common people only know that the "report an issue on this website" button is an emergency button, a button that will save them from trouble (even if the problem is caused by a custom filters, etc..)

**Comment by krystian3w** [comment]
Pre roll ad is not leftover also uBO don't hide right leftover on homepage - you must copy RraaLL filters to My filters pane:

> https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-983565302
