### ISSUE TITLE
specific-generic cosmetic filter is not disabled by generichide

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1858]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Related issue: https://github.com/uBlockOrigin/uAssets/issues/10336#issuecomment-986253008
At the time `*##.AdSense` and `@@||uploadbank.com^$ghide` were in uBlock filters and the former triggered anti-adb.

### A specific URL where the issue occurs

`https://www.uploadbank.com/wdxx40hx9g0e`

### Steps to Reproduce

1. Add `*##.AdSense` and `uploadbank.com#@#+js(acis, decodeURIComponent, return"%")` to My filters and visit the URL
2. See anti-adb is triggered

### Expected behavior

`@@||uploadbank.com^$ghide` should disable specific-generic cosmetic filters as per [wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic). TBH otherwise specific-generic is too risky to use.

### Actual behavior

Not disabled by $ghide.

### uBlock Origin version

1.39.2

### Browser name and version

94.0.2 (UA changed to Mozilla/5.0 (Android 11; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0)

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
I cannot reproduce with this minimal steps to repro:

- To _"My filters"_, add `*##body`
- Navigate to `https://example.com/`
- Result: page is blank
- Add `@@||example.com^$ghide`
- Navigate to `https://example.com/`
- Result: page renders fine

**Comment by gorhill** [comment]
I can reproduce the issue, it seems some cached value regarding whether generic cosmetic filtering is disable or not is the issue.

**Comment by Yuki2718** [comment]
You're right, I have to check what was wrong on my side.

**Comment by Yuki2718** [comment]
@gorhill Can you check with the URL I posted? Here you see ghide and `*##.AdSense` are both applied:
![uploadbank](https://user-images.githubusercontent.com/58900598/144884698-534618e0-206e-4bbd-85fe-5c34a75f5082.png)

**Comment by gorhill** [comment]
Ok it's because the page create an `about:blank` frame and uBO checks whether generic cosmetic is disable in `about:blank`, which it is not. uBO needs to replace `about:blank` with the URL of the owner of that blank frame.

**Comment by gwarser** [comment]
Bugfix not applied to `:style()` filter?

![image](https://user-images.githubusercontent.com/886325/144896575-ed4a7a38-ceef-411a-8a31-416ade38a404.png)

**Comment by gorhill** [comment]
`ghide` prevents implicit `display: none !important`, it does not touch explicit styling.
