### ISSUE TITLE
List of domains loses colour indicator if the list can be scrolled

### ISSUE THREAD

**Issue by MrChocolatine** [uBlockOrigin/uBlock-issues#1864]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In uBO popup panel, the left colour indicator on the left of every domains disappears when the list can be scrolled.

Notes:
- I am using the hard mode, exactly as [described in your wiki](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode)
- I have the setting `I am an advanced user` enabled
- I have the setting `Block media elements larger than 25 KB` enabled
- I have the setting `Block remote fonts` enabled
- I have the setting `Disable JavaScript` enabled

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=btMCQvJXwZ4

### Steps to Reproduce

1. Enable [uBO hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode)

1. Load page https://www.youtube.com/watch?v=btMCQvJXwZ4

1. Open uBO popup panel and notice each line of the list of domains has a colour indicator ([screenshot](https://user-images.githubusercontent.com/47531779/145256890-77fb6fd4-a11a-4d58-ac2c-5a6b73e87449.png))

1. Click on cell `all` to expand all the domains and notice each line of the list of domains has a colour indicator ([screenshot](https://user-images.githubusercontent.com/47531779/145257199-44aa9601-1258-41f5-88c2-e34ab5a02168.png))

1. Click on cell `all` again to close all subdomains

1. In uBO popup panel, enable JavaScript, reload the page, and notice each line of the list of domains has a colour indicator ([screenshot](https://user-images.githubusercontent.com/47531779/145257411-7e6a7c9e-9e5d-44d6-a3f5-c04642723dc7.png))

1. Click on cell `all` to expand all the domains and notice the colour indicator has disappeared from every line of the list of domains ([screenshot](https://user-images.githubusercontent.com/47531779/145257451-66194c49-ae30-4fe5-8c5c-6487e324cdcc.png))

### Expected behavior

Every line of the list of domains should have a colour indicator.

### Actual behavior

The colour indicator disappears from every line of the list of domains when the list can be scrolled.

### uBlock Origin version

1.39.2

### Browser name and version

ungoogled-chromium, version 95.0.4638.69

### Operating System and version

macOS Catalina, version 10.15.7

**Comment by MrChocolatine** [comment]
Another example, recorded a few minutes ago.

On the page https://arstechnica.com/gadgets/2021/12/razers-rgb-smartphone-cooler-attaches-to-iphones-with-magsafe/

https://user-images.githubusercontent.com/47531779/145259165-782c4c61-284e-4187-9157-6c9faf1b893f.mov

**Comment by gwarser** [comment]
System specific?

**Comment by uBlock-user** [comment]
> ungoogled-chromium

Does this happen on Chrome ?

**Comment by gorhill** [comment]
Unable to reproduce using the plain Chromium. Please try with plain Chromium, your browser behavior as seen in the video seems to be rather specific, for example I do not have scrollbar as overlay.

**Comment by gorhill** [comment]
If you are familiar with browser dev tools, you can right-click on an entry in the popup panel to get the inspector for the popup panel, and from there you can find out why the indicators are disappearing, they are implemented using `::before`, see:

![Screenshot from 2021-12-08 13-20-18](https://user-images.githubusercontent.com/585534/145262623-10294a22-c61c-419e-a978-bd0ade2b8952.png)

**Comment by MrChocolatine** [comment]
1. The issue does not appear when using Chrome version 96.0.4664.55 (x86_64):

https://user-images.githubusercontent.com/47531779/145264012-1d377930-a1f0-416d-b685-d8dd1c21ed8f.mov

1. I tried to inspect as you recommended @gorhill and... It is still confusing, I can't manage to upload a video as the resulting file is too big.

But sometimes, when an indicator is displayed on a domain X and I expand a domain Y, the indicator of X is hidden while the code for its row does not change (only the code related to domain Y).
When toggling all the domains, all the code changes.

**Comment by MrChocolatine** [comment]
> If you are familiar with browser dev tools, you can right-click on an entry in the popup panel to get the inspector for the popup panel, and from there you can find out why the indicators are disappearing, they are implemented using `::before`, see:

I tried @gorhill and... It is still confusing, I can't manage to upload a video as the resulting file is too big.

But sometimes, when an indicator is displayed on a domain X and I expand a domain Y, the indicator of X is hidden while the code for its row does not change (only the code related to domain Y).
When toggling all the domains, all the code changes.

**Comment by gorhill** [comment]
Just a screenshot of the inspector with the indicator selector so that we can see the styling is enough, no need for a video.

**Comment by MrChocolatine** [comment]
@gorhill 

![ubo inspector before](https://user-images.githubusercontent.com/47531779/145268820-0c05d85f-b6b2-4de6-835c-0ab9e9df822d.png)

**Comment by gorhill** [comment]
Well you are showing me the style when it works fine. I want to see the style when it does not show properly.

**Comment by MrChocolatine** [comment]
Indeed, and I actually just forgot to drag the second image... Sorry about that.

The thing is, the `::before` completely disappears so I can't keep it selected and show you the styling when the issue appears. I can only select the whole cell or the `<span>` that contains the domain's name and the `...`.

![ubo inspector after](https://user-images.githubusercontent.com/47531779/145270652-1bda5edf-cc1c-41e7-8bbb-4796c4a0edcc.png)

**Comment by gorhill** [comment]
You need to look at the row below, there was no network request for `doubleclick.net` itself, so it is expected it won't have the indicator. The one below, `googleads.g.doubleclick.net`, which has class `blocked` should have the `::before`, as per CSS file.

**Comment by MrChocolatine** [comment]
Here you go @gorhill  .

![ubo inspector indicator](https://user-images.githubusercontent.com/47531779/145274038-4f0f6748-1c74-4a44-af2e-d8e2ec872bb7.png)

**Comment by gorhill** [comment]
The inspector shows that all is as expected, so it's the browser not rendering properly the element, you will have to find why this happens, whether it's the browser itself, or your OS or graphic card.

**Comment by MrChocolatine** [comment]
It might be related to Ungoogled-Chromium, but not sure at all, I remember it used to work perfectly like ~2 months ago.
I will try to downgrade/upgrade and see if and when something changes.

If there is no apparent fix possible on your side then feel free to close the issue and I will comment on it whenever I get more information :v: .
