### ISSUE TITLE
Investigate unduly high time-to-readiness as reported in uAssets issue tracker

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1865]
Instances of unduly high time-to-readiness (will add more as more come into view), mobile browsers will be left out for now:

### Chromium

- <https://github.com/uBlockOrigin/uAssets/issues/11300>
    -  `launchToReadiness: 13678 ms (selfie)`
- <https://github.com/uBlockOrigin/uAssets/issues/10892>
    - `launchToReadiness: 5979`, `launchFromSelfie: true`
- <https://github.com/uBlockOrigin/uAssets/issues/10824>
    - `launchToReadiness: 31115`, `launchFromSelfie: true`
- <https://github.com/uBlockOrigin/uAssets/issues/10803>
    - `launchToReadiness: 27090`, `launchFromSelfie: true`
- <https://github.com/uBlockOrigin/uAssets/issues/10794>
    - `launchToReadiness: 18609`, `launchFromSelfie: true`
- <https://github.com/uBlockOrigin/uAssets/issues/10758>
    - `launchToReadiness: 8248`, `launchFromSelfie: true`

### Firefox

- <https://github.com/uBlockOrigin/uAssets/issues/10754>
    - `launchToReadiness: 5510`, `launchFromSelfie: true`

**Comment by garry-ut99** [comment]
### Chromium
 * https://github.com/uBlockOrigin/uAssets/issues/11640
   * `launchToReadiness: 22285 ms (selfie)`

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/16939

**Comment by garry-ut99** [comment]
I've updated my previous comment https://github.com/uBlockOrigin/uBlock-issues/issues/1865#issuecomment-1427103640

I took the 30 biggest cases for each browser: Firefox and Chromium and it seems that the root issue affected the both browsers equally.

Regardless of the other separate issue: https://github.com/uBlockOrigin/uAssets/discussions/16939  which further affected additionally Chromium 110 (and above) only. 

Which means it's another rare case with two same issues visually (incerased time-to-readiness), but have different roots, like this one previoulsly: `https://github.com/uBlockOrigin/uBlock-issues/issues/2507#issuecomment-1440243246`

**Comment by garry-ut99** [comment]
**UPDATE 4 (05-12-2023):**
- I've updated the list again, see entries labeled: " ![#FFA500](https://placehold.co/15x15/FFA500/FFA500.png) **NEW 3** " 
   - including 7 very big cases, one of them being a new record and incerasing the previous record almost a half ! :  
   `Firefox 119: allReadyAfter: 717534 ms` 
- the other thread has been updated too:
   - https://github.com/uBlockOrigin/uAssets/discussions/16939#discussioncomment-5180192
   - including 3 big cases, 2 of them being new records

**Comment by stephenhawk8054** [comment]
@voidlyvidevoid Can you go to `chrome://extensions` page (type in URL bar) and screenshot it here?

**Comment by stephenhawk8054** [comment]
@voidlyvidevoid Can you turn off all other extensions and compare the numbers again?

**Comment by stephenhawk8054** [comment]
@voidlyvidevoid Just restart the browser is enough

**Comment by stephenhawk8054** [comment]
The `allReadyAfter: 5432 ms` with default settings is strange, mine is just < 400ms even without selfie

```yml
uBlock Origin: 1.57.2
Chromium: 124
filterset (summary):
 network: 134680
 cosmetic: 46211
 scriptlet: 20526
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 86177-559, 1m
  easyprivacy: 50790-813, 1m
  plowe-0: 3759-0, 12d.6h.2m
  ublock-badware: 8315-0, 1m
  ublock-filters: 37581-290, 1m
  ublock-privacy: 832-0, 1m
  ublock-quick-fixes: 274-1, 1m
  ublock-unbreak: 2256-20, 1m
  urlhaus-1: 13265-0, 1m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 391 ms
 maxAssetCacheWait: 106 ms
 cacheBackend: indexedDB
```

**Comment by garry-ut99** [comment]
Most likely _voidlyvidevoid_ didn't additionally restart browser after reinstalling/resetting uBO to Deafult, before reading the result on Default. He should do so because after reinstalling / resetting uBO to Default / importing backup it always takes longer for uBO to load for the first time (recompilation) - for ex. it takes 1,5s or 2s or even several seconds (on Default without selfie), until browser is restarted - then it's 300-600ms (on Default without selfie). (Of course with selfie it's even faster.)

**Comment by garry-ut99** [comment]
**UPDATE 5 (26-04-2024):** https://github.com/uBlockOrigin/uBlock-issues/issues/1865#issuecomment-1427103640
- the list has been updated again, see entries labeled green color : " ![#32CD32](https://placehold.co/15x15/32CD32/32CD32.png) **NEW 4** ",  including several big cases: 
      - one of them is a new Firefox record `952936 ms` beating by 33% the previous record `717534 ms` 
      - other Firefox big cases : `66099 ms`, `60221 ms`, `59008 ms`
      - another big cases are two old Chrome big cases:`164077 ms` and `115026 ms`
- the other thread has been updated too, 9 cases including 5 big cases within range `69000 ms - 91000 ms` :
   - https://github.com/uBlockOrigin/uAssets/discussions/16939#discussioncomment-5180192
