### ISSUE TITLE
elwood.io low FPS issue

### ISSUE THREAD

**Issue by 1aTa** [uBlockOrigin/uBlock-issues#1874]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/143316083-5dd9bf87-ee9a-4ac2-a5a0-131c56c65551.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png)
- [X] I have no custom filter lists, or I verified that the issue still occurs without custom filter lists
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)

### URL address of the web page

`https://www.elwood.io/`

### Category

breakage

### Describe the issue

Scrolling has a very low FPS.

If you disable cosmetic filtering the issue is resolved and page scrolling has the expected high fps.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.39.2
Chromium: 97
filterset (summary): 
  network: 95444
  cosmetic: 98512
  scriptlet: 19028
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 48365-143, now
    adguard-spyware: 23845-539, now
    fanboy-cookiemonster: 20465-2235, now
  default: 
    easylist: 61638-75, now
    easyprivacy: 26484-10204, now
    plowe-0: 3687-861, now
    ublock-abuse: 72-0, now
    ublock-badware: 3565-61, now
    ublock-filters: 29884-414, now
    ublock-privacy: 189-24, now
    ublock-unbreak: 1712-52, now
    urlhaus-1: 7830-0, now
filterset (user): [array of 1 redacted]
trustedset: 
  added: [array of 29 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 586
  launchFromSelfie: true
popupPanel: 
  blocked: 34
```
</details>

**Comment by mapx-** [comment]
does this work ?

`@@||elwood.io^$ehide`

**Comment by 1aTa** [comment]
> does this work ?
> 
> `@@||elwood.io^$ehide`

Yes that fixed it. What's the cause as I'm seeing the same behaviour on other ad blockers too?

**Comment by uBlock-user** [comment]
> What's the cause as I'm seeing the same behaviour on other ad blockers too?

Site issue then. Thought this was specific to uBO.

**Comment by uBlock-user** [comment]
`@@||elwood.io^$ehide`  is same as disabling cosmetic filtering.

**Comment by gorhill** [comment]
This page has high CPU usage with or without uBO.

**Comment by gwarser** [comment]
@gorhill it's very slow with cosmetic filtering enabled when logger script is injected.

**Comment by gorhill** [comment]
The performance profile shows the site's own code contribute to CPU usage, followed by the browser code itself ("Recalculate Style", "Update Layer Tree", "Paint"). Then following I see uBO's call to `querySelectorAll()` to be also slow, so there appear to be a generic filter on which the browser chokes, it would be tedious to try to narrow down this while not sure it's worth, the site is causing the browser to hog the CPU anyways regardless of uBO.

**Comment by gwarser** [comment]
Not much difference between https://share.firefox.dev/33pdRuc and https://share.firefox.dev/3pNoApP (with and without no-cosmetic-filtering), but this is huge: https://share.firefox.dev/3ynLxUy (with logger).

What I want to say: if someone is testing - he should be sure logger is disabled.

**Comment by gorhill** [comment]
Maybe worth finding which selector(s) are involved in causing this.

**Comment by gwarser** [comment]
```
nsINode::QuerySelector [href*=".hit.gemius.pl"],
A[href*="k.tradedoubler.com/click"],
[href^="http://www.FriendlyDuck.com/"],
foxfield-xmas,
a[href*="techmaniak.pl/www/gact/ckk.php"],
A[href*="/emisja.contentstream.pl/_/ctr/"],
IMG[src^="http://www.audiostereo.pl/banery/"],
IMG[title^="Sponsorowan"],
TopTextAd,
[class^="ADbox"],
[class^="adSrodek"],
[class^="sponsorowany"],
[href*=".novem.pl/"],
[href*="://clickserve.dartsearch.net/link/click"],
[href^="http://adserwer."],
[href^="https://aff.sendhub.pl/"],
[id$="reklamy"],
[...
```

Attribute selectors.

**Comment by gorhill** [comment]
I'm going to add being able to dump generic selectors in new devtools page, so we can run binary search of which highly generic selector(s) is involved (it can't be lowly generic since I didn't see any reported for that page).

**Comment by gorhill** [comment]
There is something about that website... The same set of highly generic selectors does not result in same poor `querySelectorAll()` performance on `cnn.com` even though it has a bit more elements in its DOM tree.
