### ISSUE TITLE
Hope to add support to redirect google's caf.js

### ISSUE THREAD

**Issue by AnnAngela** [uBlockOrigin/uBlock-issues#1875]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

_**IDK if I use the correct template**_, but I really hope to add support to redirect google's caf.js ( https://www.google.com/adsense/domains/caf.js ) to sanitized resources like google's [ga.js](https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/google-analytics_analytics.js).

This will help to prevent websites like http://ww1.hack-store.com/ to against adb.

### A specific URL where the issue occurs

http://ww1.hack-store.com/

### Steps to Reproduce

1. Enable the `EasyList` filter list.
2. Open http://ww1.hack-store.com/

### Expected behavior

Nomal page showing a store list.

### Actual behavior

Showing `ww1.hack-store.com currently does not have any sponsors for you.`

### uBlock Origin version

1.39.2

### Browser name and version

Microsoft Edge Dev 98.0.1093.6

### Operating System and version

Windows 10 Pro 21H2 19044.1320

**Comment by uBlock-user** [comment]
Domain is parked.

**Comment by gwarser** [comment]
Someone tried blocking `/js/parking.2.73.3.js`?
