### ISSUE TITLE
Block media files larger than X kB not always working

### ISSUE THREAD

**Issue by tonecas** [uBlockOrigin/uBlock-issues#188]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I'm using uBlock Origin  v1.16.20 with Firefox 61.0.2 on OnePlus 3 with Android 8.0.0

Block media elements larger than: 20KB

However, the behavior is inconsistent, with lot of images bigger than 20 kB being loaded and shown.

### A specific URL where the issue occurs

https://mbworld.org/forums/c63-c63s-amg/578473-official-w205-c63-c63-s-photo-thread.html

### Steps to Reproduce

just visit the example URL on an Android phone with Firefox.
keep browsing the page to the bottom as this page dynamically loads more content

### Expected behavior:

all images bigger than 20 kB should not be shown and a small square should appear instead

### Actual behavior:

many images bigger than 20 kB are shown

### Your environment

* uBlock Origin version: 1.16.20
* Browser Name and version: Firefox 61.0.2
* Operating System and version: Android 8.0.0

**Comment by uBlock-user** [comment]
I can reproduce on Chromium, some images do get blocked, some simply remain unaffected, for example the very first image of the car, it's `143 KB` in size and even with `no-large-media: * true`, it doesn't get blocked.

**Comment by gwarser** [comment]
Only three on my side - no size in response header.

**Comment by gorhill** [comment]
The images which are loaded do not have a `Content-Length` header, hence they can't be blocked by size.
