### ISSUE TITLE
Cannot apply custom filters after uBlock has been running for a while

### ISSUE THREAD

**Issue by mistertheloaf** [uBlockOrigin/uBlock-issues#1881]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When Firefox is first started, I can import filters into uBlock,  Works as expected.  

After Firefox has been running for a while (exact amount of time has not been determined)  if I try to import filters the "Apply Changes" button does not work.

### A specific URL where the issue occurs

This bug involves uBlock, not a web page

### Steps to Reproduce

1.  Run Firefox with uBlock enabled
2. Use Firefox for a while (exact amount of time has not been determined)
3. Go to uBlock Dashboard and import filters that I have previously created and saved
4. Attempt to click on the "Apply Changes" button

### Expected behavior

Filters are imported and applied.

### Actual behavior

Nothing.  "Apply Changes" button does not work.

### uBlock Origin version

1.39.2

### Browser name and version

Firefox 78.15.0 ESR

### Operating System and version

Windows 10 Pro for Workstations

**Comment by gwarser** [comment]
Does this need to be ESR 78? My copy just updated to 91.

**Comment by gwarser** [comment]
Maybe you are trying to apply the same filters twice? 

Any errors in `about:devtools-toolbox?id=uBlock0%40raymondhill.net&type=extension` console?

**Comment by gorhill** [comment]
Closing due to lack of feedback.

**Comment by Flashwalker** [comment]
Can't apply custom filter ane more too

**Comment by Flashwalker** [comment]
@gorhill you can do one thing: auto-apply custom filters exactly after importing them

**Comment by u-RraaLL** [comment]
> Can't apply custom filter ane more too

Provide more details please. Your browser + version and uBO version. Preferably also copy/paste your "Troubleshooting Information" from the "Support" pane in uBO's Dashboard.

Are you using the [Import] button or [Import and Append]? Are you Importing from a local file or the cloud?

**Comment by Flashwalker** [comment]
> Provide more details please...

I'm using **97.0.4692.71** (Developer Build, **ungoogled-chromium**) on **Win 7**.
It worked ok, before I recently updated **ungoogled-chromium** from old version **89.0.4389.114**, and updated **uBO** to **1.40.8**

I'm using [Import and Append] from local file and not able to apply imported rules. Apply button do nothing.

```
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 73155
  cosmetic: 62611
  scriptlet: 18144
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2994-10, 28d.22h.27m
  default: 
    RUS-0: 40809-21, 26d.16h.57m
    easylist: 63179-41, 24d.56m
    easyprivacy: 26870-156, 24d.43m
    plowe-0: 3684-378, 35d.21h.33m
    ublock-abuse: 76-1, 28d.22h.19m
    ublock-badware: 3724-67, 28d.22h.17m
    ublock-filters: 30179-219, 28d.22h.15m
    ublock-privacy: 190-2, 28d.22h.13m
    ublock-unbreak: 1723-14, 28d.22h.10m
    urlhaus-1: 8099-0, 25d.11h.52m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 18 redacted]
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 701 ms

```

**Comment by gothic-bum** [comment]
> I'm using 97.0.4692.71 (Developer Build, ungoogled-chromium)

There have been issues reported with ungoogled-chromium:  
https://github.com/uBlockOrigin/uBlock-issues/issues/1790  
  
Try testing using another browser, e.g. Firefox.

**Comment by Flashwalker** [comment]
looks like uninstall an install UBo solves my case

**Comment by dascratch** [comment]
Reinstallation does not help, some tails interfere. Old filters are not applied even if they are added again with a pipette, while new filters are added and work properly. The problem appears after using the settings import function. In my opinion, but this is not accurate, before importing, I cleared the list of my filters, and immediately returned it after importing. After some time, they stopped working, but in my opinion not immediately. I'll try restarting my computer..

**Comment by gorhill** [comment]
What's your browser/version?

**Comment by dascratch** [comment]
It's Windows 11 + Centbrowser 4.3.9.248 (x64 бит) (Portable) (Chromium 86.0.4240.198)
 --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Atom/26.0.0.0 Safari/537.36"
