### ISSUE TITLE
Wrong description in Trusted site pane

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#1882]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The description `Invalid directives will be silently ignored and commented out.` in "Whitelist/Trusted sites" pane introduced by https://github.com/gorhill/uBlock/commit/4d0eaf3 has been wrong since [uBlock Origin v1.11.0](https://github.com/gorhill/uBlock/releases/tag/1.11.0).

### A specific URL where the issue occurs

moz-extension://MY_EXTENSION_ID/dashboard.html#whitelist.html

### Steps to Reproduce

Type `Invalid directives` as trusted site directives.

### Expected behavior

The directive will be silently ignored and commented out according to the description.

### Actual behavior

The directive will be marked as invalid and cannot be saved. 

### Configuration

<details>

```yaml
uBlock Origin: 1.39.3b13
Firefox: 95
filterset (summary): 
  network: 77641
  cosmetic: 39254
  scriptlet: 16228
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30358-107, never
    ublock-badware: 3569-1, never
    ublock-privacy: 177-0, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1694-0, never
    easylist: 60746-79, never
    easyprivacy: 25518-27, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-560, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 858 ms
```
</details>

**Comment by gwarser** [comment]
Still not pushed to crowdin?

**Comment by gorhill** [comment]
Oops, had this in mind then forgot about it.
