### ISSUE TITLE
Ublock failed to remove placeholder after block ad

### ISSUE THREAD

**Issue by codafi21** [uBlockOrigin/uBlock-issues#1885]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

![image](https://user-images.githubusercontent.com/93474348/146645445-79cd123b-ebc6-4f10-a22c-02879ce5d834.png)

### A specific URL where the issue occurs

https://www.windowscentral.com/msedgeredirect-can-work-around-microsofts-block-forces-you-use-edge

### Steps to Reproduce

1.open it
2.and it occurs

### Expected behavior

placeholder is removed

### Actual behavior

it aint being removed

### uBlock Origin version

latest

### Browser name and version

ms edge 96.0.1054.62 

### Operating System and version

win11 22000.348

**Comment by codafi21** [comment]
i had to manually block the element

**Comment by gwarser** [comment]
Ad is _blocked_ by generic filter (not specific to this page). Parent element has huge margin, and this margin keeps this space. Something specific to this page - should be reported to filter authors so they can apply specific filter.
