### ISSUE TITLE
Inconsistent line-break in the support pane for Japanese environment

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#1886]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Probably the same is true for Korean.
![Screenshot](https://user-images.githubusercontent.com/82331005/146662159-4abac67b-9738-4035-bdc0-c1f2ff576609.png)

As a conclusion from a cursory look at other translations, I think `white-space: nowrap;` is safe.
~~~
find src/ -name messages.json | xargs sed -n '/supportOpenButton/{n;p;}' | awk '{ print length, $0 }' | sort -n
~~~

### A specific URL where the issue occurs

moz-extension://MY_EXTENSION_ID/dashboard.html#support.html

### Steps to Reproduce

1. Change Firefox language to Japanese
2. Open Support Pane

### Expected behavior

All [開く (Open)] buttons will be not wrapped.

### Actual behavior

Two [開く (Open)] buttons are not wrapped, but the other buttons are wrapped.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.3rc0
Firefox: 95
filterset (summary): 
  network: 78531
  cosmetic: 43685
  scriptlet: 16310
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30358-107, never
    ublock-badware: 3569-1, never
    ublock-privacy: 177-0, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1694-0, never
    easylist: 60746-79, never
    easyprivacy: 25518-27, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-560, never
    JPN-1: 5524-121, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1438 ms
```
</details>

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/146673951-1dbc400e-1c86-4b71-9aa0-56371b5f925a.png)

**Comment by gorhill** [comment]
I assigned a minimum width to the button, so this should solve the issue here while allowing for line break should the text be too long.

**Comment by hirorpt** [comment]
> Can be patched in Crowding by word joiner >⁠< (U+2060).

I've looked for something like that before and this is the first I've heard of it. Thanks!
However, it's not widespread, so there may be accessibility issues, such as non-compatibility with screen readers.
In this case, gorhill's patch seems to have solved the issue.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/146676789-85518d5d-ac29-4389-9616-ebca41a7bf2e.png)
