### ISSUE TITLE
Fails to preview CNAME images in the logger

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#1887]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Similar issue: https://github.com/uBlockOrigin/uBlock-issues/issues/1455

### A specific URL where the issue occurs

https://old.reddit.com/r/uBlockOrigin/

### Steps to Reproduce

1. Open the logger.
2. Open `https://old.reddit.com/r/uBlockOrigin/`
3. Filter logger content by image and CNAME
4. Click a logger entry

### Expected behavior

The click to preview and picker will use original URL, or at least will be hidden.

### Actual behavior

The click to preview and picker will appear, but clicking on them will fail.

### Configuration

<details>

```yaml
uBlock Origin: 1.39.3rc0
Firefox: 95
filterset (summary): 
  network: 77641
  cosmetic: 39254
  scriptlet: 16228
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30358-107, never
    ublock-badware: 3569-1, never
    ublock-privacy: 177-0, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1694-0, never
    easylist: 60746-79, never
    easyprivacy: 25518-27, never
    urlhaus-1: 8813-0, never
    plowe-0: 3689-560, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1071 ms
```
</details>

**Comment by gorhill** [comment]
The server refuses to serve the image, I get:

> Fastly error: unknown domain: dualstack.reddit.map.fastly.net. Please check that this domain has been added to a service.
> 
> Details: cache-lga21970-LGA

So probably the fetch needs to be done in a way that please the server and I rather not throw a lot of time/code/complication at this for really little benefit, assuming this can be reliable fixed at all.
