### ISSUE TITLE
Element Picker Not Working. 

### ISSUE THREAD

**Issue by blogmangit** [uBlockOrigin/uBlock-issues#1890]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

On visiting this site and opening ublock element picker, it doesn't select anything as if the element picker is disabled.

### A specific URL where the issue occurs

https://www.msn.com/en-in/news/politics/aapke-bure-din-bohot-jaldi-aane-vale-hai-i-curse-you-why-jaya-bachchan-lost-temper-in-rajya-sabha/ar-AARZbPk?ocid=smtlch

### Steps to Reproduce

1. go to https://www.msn.com/en-in/news/politics/aapke-bure-din-bohot-jaldi-aane-vale-hai-i-curse-you-why-jaya-bachchan-lost-temper-in-rajya-sabha/ar-AARZbPk?ocid=smtlch
2. open ublock element picker .
3. nothing can be selected.

### Expected behavior

should select elements. 

### Actual behavior

nothing can be selected.

### uBlock Origin version

1.39.2

### Browser name and version

kiwi browser 96.0.4664.46

### Operating System and version

android 11 arm64

**Comment by blogmangit** [comment]
supporting video attached
https://www.dropbox.com/s/fdq1m2x797pu3ba/20_12_2021_21_29_55.mp4?dl=0

**Comment by gorhill** [comment]
Kiwi browser is not officially supported and is known to have issues. Please test with Firefox for Android, which is officially supported.

**Comment by blogmangit** [comment]
> Kiwi browser is not officially supported and is known to have issues. Please test with Firefox for Android, which is officially supported.

OK thank man I have already started to do that will close it if there's no problems with firefox

**Comment by blogmangit** [comment]
> Kiwi browser is not officially supported and is known to have issues. Please test with Firefox for Android, which is officially supported.

No problem with firefox android it's indeed a kiwi browser issue with ublock origin.

Thanks.

**Comment by gwarser** [comment]
MSN domains are whitelisted in Kiwi Browser: https://github.com/kiwibrowser/src/blob/ad4fdb6d6e87d5587e4d9b54c6f159ffa055b67d/extensions/renderer/extension_injection_host.cc#L94

**Comment by kiwibrowser** [comment]
Yes, it's intended for now, this may change in the future if we can pressure Microsoft to change their terms.
A workaround is to import uBlock Origin from the .zip.
