### ISSUE TITLE
Regression on 1.40 - Ads' spaces not removed

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uBlock-issues#1896]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The ads' spaces in the site https://www.myabandonware.com/browse/name/ located in right side and also in middle/botton sides of the page arent removed as they were before. I'm using latest waterfox classic.

This problem didnt happen before the version 1.39, all spaces were removed then.

### A specific URL where the issue occurs

https://www.myabandonware.com/

### Steps to Reproduce

1 - go here https://www.myabandonware.com/ and check the ads' spaces.

### Expected behavior

Not spaces where the ads were.

### Actual behavior

Now there are spaces in the places where the ads were before, the ads luckly are blocked.

### Configuration

uBlock Origin: 1.40.0
Firefox: 56
filterset (summary): 
  network: 74665
  cosmetic: 91852
  scriptlet: 16422
  html: 608
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    fanboy-annoyance: 59137-174, 1m
  default: 
    ublock-filters: 30595-29, 1m
    ublock-badware: 3626-1, 1m
    ublock-privacy: 180-0, 1m
    ublock-abuse: 81-0, 1m
    ublock-unbreak: 1711-0, 1m
    easylist: 62180-184, 1m
    easyprivacy: 26545-46, 1m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 6647 ms

**Comment by gorhill** [comment]
Firefox 56 is not a supported browser, minimum supported version is 60, this is in the manifest and your browser should have warned you it's not supported.
