### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Volker-Weissmann** [uBlockOrigin/uBlock-issues#1897]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In the [Readme](https://github.com/gorhill/uBlock/blob/master/README.md) you link to the [section "blocking"](https://github.com/gorhill/uBlock/blob/master/README.md#blocking), but this section does not exist.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/README.md

### Steps to Reproduce

Go to the https://github.com/gorhill/uBlock/blob/master/README.md and click on the "as well or better" link.

### Expected behavior

The link target (https://github.com/gorhill/uBlock/blob/master/README.md#blocking) should exist.

### Actual behavior

The link target (https://github.com/gorhill/uBlock/blob/master/README.md#blocking) does not exists.

### uBlock Origin version

Any

### Browser name and version

Any

### Operating System and version

Any

**Comment by Volker-Weissmann** [comment]
Slightly OT, but a free form bug report would be better in this case than the formula.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/1f721459a678e0a48a33531fc69d3c2294eee77c

Should be removed.

**Comment by gwarser** [comment]
Or maybe link something like https://www.debugbear.com/blog/chrome-extension-performance-2021#how-do-ad-blockers-and-privacy-tools-affect-browser-performance

**Comment by Volker-Weissmann** [comment]
That was fast, Thank you

**Comment by u-RraaLL** [comment]
> Slightly OT, but a free form bug report would be better in this case than the formula.

This is an issue tracker for the extension. For wiki, etc. you can use the Discussions tab instead.
I used it to report a wiki ToC problem last month.

@gorhill Perhaps a new entry in the template chooser that redirects to the Discussions tab would be helpful? Something like:

> **Other issues**
> Use Discussions to report wiki or other non-extension/non-filter issues. Use *Ideas* category to file well-researched feature requests.

to be placed after the uAssets link?
