### ISSUE TITLE
commit comment

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#190]
Regarding https://github.com/gorhill/uBlock/commit/aeb19c952b782eec31e5de8da676b89edd08efdb

Is the concatenation comment still valid -- are tabId's still strings or now ints?

**Comment by gorhill** [comment]
I forgot to remove the comment, thanks.

Please just comment in the commit next time, opening an issue for this is over the top.

**Comment by joey04** [comment]
I tried to comment on the commit, but nothing happened when I clicked the button. (No error message or any visual change, and it obviously didn't add the comment. So I pasted it here.)

**Comment by uBlock-user** [comment]
You could change the setting of Moderation Limits from **Limit to prior contributors** to **Limit to repository collaborators**, add @joey04 and selected you want to be able to interact with the repo like a whitelist mode per se.

**Comment by gorhill** [comment]
The problem with adding people as collaborator is that they get commit right, which I prefer to not do -- this is why I created the repos here, to be able to give commit rights for everything else except the core code.

I will open the repo and let @joey04 submit a pull request to remove the now invalid comment in the code, and once I merge the pull request, he will be deemed a prior contributor and able to comment freely in the repo.

**Comment by joey04** [comment]
No need to do anything special for me. Truth is, I don't know git and don't have a git client installed. So I'd have at least a several hour learning curve just to open a simple PR.

I understand and respect the dual-repo setup and restrictions in the main repo. Not a problem for me. If I spot anything I'll just open an issue like this one. (Should be rare; I've been following this project closely for almost 2 years and haven't posted that much.)

(and thanks for the screenshot @uBlock-user -- I only have JS errors and console messages enabled in my console so missed that)
