### ISSUE TITLE
Scrollbars appear in `click2load.html`

### ISSUE THREAD

**Issue by ghcsd** [uBlockOrigin/uBlock-issues#1901]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In Firefox, scrollbars always appear in `click2load.html`

### A specific URL where the issue occurs

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation#video_and_webgl

### Steps to Reproduce

1. Add `*$frame,redirect=click2load.html` to `My filters`
2. Open `https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation#video_and_webgl`.

### Expected behavior

Scrollbars should not appear in the placeholder document.

### Actual behavior

![image](https://user-images.githubusercontent.com/32384764/147380334-f6de32d8-1621-479b-afee-ee269c73f9f7.png)

### uBlock Origin version

uBlock Origin 1.39.3rc1

### Browser name and version

Firefox 95.0.2

### Operating System and version

Windows 10

**Comment by ghcsd** [comment]
Using
```css
body {
  width: 100vw;
  height: 100vh;
}
``` 
instead of the inline style can solve this issue.
https://github.com/ghcsd/uBlock/commit/e344b64649c2da3267577808d4ecda9f78438623

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/147383868-8fe0402d-b504-46c4-aa8e-bd9f95c38805.png)

**Comment by gwarser** [comment]
High DPI monitor? System/browser scaling?

**Comment by ghcsd** [comment]
> High DPI monitor? System/browser scaling?

Yes, It is easier to reproduce when Firefox browser is not the default zoom level (eg. 110%).
You can zoom in/out (`Ctrl` - `+/-`) and refresh the page to reproduce the issue.

**Comment by ghcsd** [comment]
Adding the following CSS code to `userContent.css` can temporarily fix this issue. 
```CSS
@-moz-document regexp("moz-extension://[^/]+/web_accessible_resources/click2load\.html.+"){
  #ublock0-clicktoload > body{
    width: 100vw !important;
    height: 100vh !important;
  }
}
```
