### ISSUE TITLE
Firefox extension bug (mobile version)

### ISSUE THREAD

**Issue by Mr-Mohammed1** [uBlockOrigin/uBlock-issues#1907]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

It's a simple bug. I can't exit "smart selection mode".
I tried to remove a "div" from a webpage, so I entered smart selection mode, and after removing the element I couldn't exit this mode :(

### A specific URL where the issue occurs

https://www.google.com.sa

### Steps to Reproduce

1. Opening a webpage
2. Entering selection mode to remove some elements.
3. Get stuck in selection mode

### Expected behavior

Being able to exit smart selection mode

### Actual behavior

Unable to exit smart selection mode

### Configuration

<details>

```yaml
uBlock Origin: 1.40.0
Firefox Mobile: 95
filterset (summary): 
  network: 97674
  cosmetic: 28369
  scriptlet: 16462
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30741-433, 3h.40m
    ublock-badware: 3633-1, 2d.4h.57m
    ublock-privacy: 180-1, 1d.14h.8m
    ublock-abuse: 81-0, 2d.4h.52m
    ublock-unbreak: 1695-0, 2d.4h.55m
    adguard-mobile: 7014-172, 3h.41m
    easylist: 62254-24260, 1d.14h.6m
    easyprivacy: 26549-496, 1d.14h.7m
    urlhaus-1: 8264-0, 9m
    plowe-0: 3715-3, 2d.4h.58m
    ara-0: 2329-244, 2d.3h.50m
    FRA-0: 26037-3585, 3h.44m
filterset (user): [array of 15 redacted]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 1819 ms (selfie)
```
</details>

**Comment by gwarser** [comment]
Swipe right.

Read "On touch screen devices:": https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-picker
