### ISSUE TITLE
UBO Fails to block ads and Settings will not open on Tor Browser Android

### ISSUE THREAD

**Issue by Pasbiengrav** [uBlockOrigin/uBlock-issues#1910]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Although activated, UBO do not block any adds in Tor Browser and Settings page cannot open properly on Samsung S9. Settings page will open for other add-ons.
Problem was unchanged after restarting phone, re-installing browser and UBO.

The problem was not reproduced on my previous Samsung S7 with same UBO & Tor Browser versions and running on Android 7.1.2 and /e/ OS 0.19.20211023142428.
But it did reproduce there after uninstalling Tor Browser and installing it again with UBO.

### A specific URL where the issue occurs

moz-extension://4372e290-0ad2-4c0b-a601-3f42846683ce/dashboard.html

### Steps to Reproduce

1. Open TorBrowser on Android
2. Tor settings
3. Add-ons (not sure translation, I am in french)
4. UBO being activated, click on uBlock add-on
5. Click on Settings

### Expected behavior

The adds should be blocked and the Settings page should open.

### Actual behavior

All ads are shown on websites.
UBO Settings his will open the url given above serving an all white page with just the UBO logo at top left. No buttons nor links

### uBlock Origin version

1.40.2

### Browser name and version

Tor Browser 10.5.10 (release 91.2.0)

### Operating System and version

Android 8.1.0 with /e/ OS 0.19-o-20211023142277-stable-startlte

**Comment by gwarser** [comment]
> Tor Browser 10.5.10 (release 91.2.0)

How long ago it was updated? 

Can this be related: https://github.com/uBlockOrigin/uBlock-issues/issues/1833 ?

**Comment by gorhill** [comment]
I suspect it's because uBO has to be set to work in private mode, but I can't find any setting in the browser to allow uBO to work in private mode.

**Comment by gorhill** [comment]
It appears to be a Tor browser for Android issue, not specific to uBO: <https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40606>.

**Comment by gwarser** [comment]
```
12:54:41.560 Uncaught TypeError: browser is undefined
    <anonymous> moz-extension://3864ccb6-b912-4b15-9824-bd51d5a68fbb/js/vapi-common.js:55
    <anonymous> moz-extension://3864ccb6-b912-4b15-9824-bd51d5a68fbb/js/vapi-common.js:96
vapi-common.js:55:10
12:54:41.574 Uncaught TypeError: vAPI.i18n is undefined
    <anonymous> moz-extension://3864ccb6-b912-4b15-9824-bd51d5a68fbb/js/i18n.js:144
i18n.js:144:1
12:54:41.651 Uncaught (in promise) TypeError: vAPI.localStorage is undefined
    <anonymous> moz-extension://3864ccb6-b912-4b15-9824-bd51d5a68fbb/js/dashboard.js:117
    <anonymous> moz-extension://3864ccb6-b912-4b15-9824-bd51d5a68fbb/js/dashboard.js:150
dashboard.js:117:9
```
