### ISSUE TITLE
Minor issue: inconsistent casing in the "Block element..." menuitem in Firefox

### ISSUE THREAD

**Issue by aminomancer** [uBlockOrigin/uBlock-issues#1918]
### Prerequisites

- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Hi, this is a pretty small nitpick but still worth fixing. Firefox uses title case for all menus/menuitems, and sentence case for toolbar buttons. But uBlock Origin makes [a menuitem](https://github.com/gorhill/uBlock/blob/6e807974bc7d0d5ad353536726f224286c9e05cd/src/_locales/en/messages.json#L315) with a sentence case label, so there's a mild sense of jank when using the context menu.

### A specific URL where the issue occurs

https://github.com

### Steps to Reproduce

1. Right click an element on any page not excluded by UBO's documentUrlPatterns or your own blacklist (or included in your whitelist)

### Expected behavior

menuitem should say `Block Element...`

### Actual behavior

it says `Block element...`

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox: 97
filterset (summary): 
  network: 81560
  cosmetic: 93353
  scriptlet: 48598
  html: 638
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
  added: 
    https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock/fuckfuckadblock.txt: 27096-77, 7h.40m
    https://openphish.com/feed.txt: 500-0, 4d.17h.18m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1034-0, 7h.42m
    https://raw.githubusercontent.com/magicoflolis/PornList/master/PornList.txt: 1670-0, 3h.36m
    https://secure.fanboy.co.nz/fanboy-problematic-sites.txt: 1957-7, 18h.23m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-4, 18h.25m
    adguard-generic: 61489-5291, 2d.19h.42m
    fanboy-cookiemonster: 21265-129, 1d.3h.55m
    ublock-annoyances: 4357-44, 2d.19h.44m
  default: 
    ublock-filters: 30655-3287, 3d.8h.15m
    ublock-badware: 3564-1, 3d.12h.21m
    ublock-privacy: 183-0, 2d.19h.40m
    ublock-abuse: 81-4, 3d.12h.23m
    ublock-unbreak: 1717-1, 3d.12h.25m
    easylist: 62535-232, 1d.17h.42m
    urlhaus-1: 7938-0, 7h.38m
filterset (user): [array of 11 redacted]
trustedset: 
  added: [array of 173 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 180
  uiTheme: dark
  userResourcesLocation: [redacted]
supportStats: 
  launchToReadiness: 611 ms (selfie)
```
</details>

**Comment by aminomancer** [comment]
Actually I forgot another thing — in menuitems, Firefox uses the ellipsis _character_ `…` instead of three periods `...`, which look different for most fonts. [See these](https://searchfox.org/mozilla-central/rev/fbf1e796ecead9484deced4d99f199f327ba25ab/browser/locales/en-US/browser/appmenu.ftl#117-118) for example. This is much more subtle, but if you end up revising the translations, might as well fix the ellipsis too

**Comment by gorhill** [comment]
uBO is available on more than just Firefox, and other browsers do not necessarily follow this style. I will keep the style as is as this is how it's everywhere else in uBO.

I will change `...` for `…`.

**Comment by aminomancer** [comment]
Great! Yeah I'm aware the major browsers are inconsistent in casing, but still worth investigating. In addition to Firefox, the last time I checked Chrome on macOS used title case, presumably since that's how all of macOS' context menus are cased, but the last Windows build of Chrome I used had sentence case. Could make different strings for chrome vs. firefox but idk how well that works into your build system

**Comment by hirorpt** [comment]
Ellipsis `…` has been marked as "Do not translate special symbols" on crowdin, but I have to ignore the notice and keep using 3-dots `...` in Japanese translation.

- Ellipsis `…` in Japanese fonts looks different from in western fonts.
- The Mozilla editorial guideline for Japanese specify the use of 3-dots `...` for ellipsis.
