### ISSUE TITLE
Cookie-remover.js not working for Instagram embeds (Firefox)

### ISSUE THREAD

**Issue by yokoffing** [uBlockOrigin/uBlock-issues#1919]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

**Goal:** I am trying to prevent or delete Instagram and Twitter cookies third-party sites that stem from embedded posts. I still want the embeds but then either 1) prevent them altogether or 2) delete the third-party cookies immediately upon load or when site is closed.

**Background:** I'm using `Strict` tracking protection in Firefox; however, unlike Brave, Firefox does not give end users a GUI to allow embedded Instagram posts and tweets. So, to allow these embedded post, I have to [modify](https://github.com/yokoffing/Better-Fox/blob/ca4d13fe2cdad8731e4993d6482fd0f58b9de214/SecureFox.js#L39-L43) Firefox's tracking protection:

`pref("urlclassifier.trackingSkipURLs", "*.twitter.com, *.twimg.com");`
`pref("urlclassifier.features.socialtracking.skipURLs", "*.instagram.com, *.twitter.com, *.twimg.com");`

(These prefs are hidden; you have to add them manually to Firefox or with a user.js.)

All examples below are in Firefox normal browsing windows with cookies and site data deleted.

### Embedded tweets
Using `platform.twitter.com##+js(cookie-remover)`: The cookie appears but then no information is given. I'm assuming that uBlock removed the cookie, and the embedded tweet loads normally.

**Example page:** `https://www.thelineofbestfit.com/news/latest-news/cher-and-saweetie-unite-for-new-mac-cosmetics-campaign`

![twit cookie 2](https://user-images.githubusercontent.com/11689349/148275825-8f1d1a29-473a-4c2e-8178-5ace60270efd.jpg)

All good here.

### Embedded Instagram posts

**Example page:** `https://www.ndtv.com/entertainment/bharti-singh-and-husband-haarsh-limbachiyaa-announce-pregnancy-see-trending-post-2646359`

With embedded Instagram posts, here's what I see in `Dev Tools > Storage`. (With lazy loading enabled, you have to scroll down for the cookie to populate.)

![insta](https://user-images.githubusercontent.com/11689349/148277001-6f9adb3b-d4a5-46f2-b4b1-a02228f01934.jpg)

I have tried:

`instagram.com##+js(cookie-remover)`
`www.instagram.com##+js(cookie-remover)`

and:

```
instagram.com##+js(cookie-remover, csrftoken)
instagram.com##+js(cookie-remover, ds_user_id)
instagram.com##+js(cookie-remover, ig_did)
instagram.com##+js(cookie-remover, mid)
instagram.com##+js(cookie-remover, rur)
instagram.com##+js(cookie-remover, sessionid)
instagram.com##+js(cookie-remover, shbid)
instagram.com##+js(cookie-remover, shbts)
```

None of these seem to work entirely.

### A specific URL where the issue occurs

`https://www.ndtv.com/entertainment/bharti-singh-and-husband-haarsh-limbachiyaa-announce-pregnancy-see-trending-post-2646359`

### Steps to Reproduce

See above

### Expected behavior

No third-party Instagram cookies.

### Actual behavior

Cookies! 😱

### uBlock Origin version

1.40.3b3 Dev

### Browser name and version

Firefox 96

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
I've set ETP to custom and disabled everythig.

Neither instagram or twitter set any cookies.

**Comment by gwarser** [comment]
If I enter Instagram and allow cookies, then three are set. If I then enable the filter and reload ndtv, two cookie lines are logged and only one cookie is left - the one with `HttpOnly` option (not possible to remove by page scripts / uBO scriptlet).

**Comment by yokoffing** [comment]
> I've set ETP to custom and disabled everythig.

Can you set ETP to `Strict`, then create these preferences to Firefox in `about:config`? Otherwise, embeds won't load. I still want all the benefits of ETP `Strict`, but you have to make the following allowances for embedded Instagram posts and Twitter tweets to load:
```
pref("urlclassifier.trackingSkipURLs", "*.twitter.com, *.twimg.com");
pref("urlclassifier.features.socialtracking.skipURLs", "*.instagram.com, *.twitter.com, *.twimg.com");
```

**Comment by yokoffing** [comment]
**Update:** Removing Instagram cookies is working for me now. I'm getting the same result with `instagram.com##+js(cookie-remover)` as I am with `platform.twitter.com##+js(cookie-remover)` in Dev Tools: `No data present for selected host`. So, that's good!

I haven't determined why it wasn't working before, but it is working!

**Feature request:** If uBO could distinguish between 1st- and 3rd-party cookies, I could specify Instagram 3rd-party cookies to be removed only, and this would prevent breakage from when the user wants to use `instagram.com`. @gorhill 👀

Thank you for your time!

**Comment by gwarser** [comment]
Your custom settings don't work in stable Firefox - widgets don't load, but they work in beta. I don't think these frames set cookies by themselves. If you used twitter or instagram then cookie will appear in Storage inspector, but I don't see any cookie being set or received in network connections. I think strict tracking protection may use separate cookie jars for widgets in frames and for pages alone (cookie isolation) despite your config.

**Comment by yokoffing** [comment]
> If you used Twitter or Instagram then cookie will appear in Storage inspector, but I don't see any cookie being set or received in network connections.

Fascinating! If I change my configuration to
```
pref("browser.contentblocking.category", "custom");
pref("privacy.trackingprotection.enabled", true);
pref("privacy.trackingprotection.socialtracking.enabled", false);
pref("network.cookie.cookieBehavior", 5); 
```
then Twitter cookie doesn't set at all (even in Dev tools) and the Instagram one seems to be cleared:

![insta post](https://user-images.githubusercontent.com/11689349/148449115-aa67dee2-fff5-4f88-b62c-3bed85efe5f6.jpg)

However, for embedded tweets to load (`https://www.thelineofbestfit.com/news/latest-news/cher-and-saweetie-unite-for-new-mac-cosmetics-campaign`) and, more rarely, embedded reddit posts (`https://www.pcgamer.com/amazing-halo-infinite-bugs-are-already-rolling-in/`), I must create the pref:
```
pref("urlclassifier.trackingSkipURLs", "*.reddit.com, *.twitter.com, *.twimg.com"); 
```
Granted, when I have `Allow Twitter embedded tweets` on Brave, they allow cookies from `platform.twitter.com` for embedded tweets, but they [partition and delete third-party storage on site close](https://brave.com/privacy-updates/14-partitioning-network-state/).

> You should know `cookie-remover` is very weak in removing cookies, rather a trick than reliable solution.

Thank you for the heads up, and helping me process all this.

**Comment by gwarser** [comment]
My test from today was with strict setting.

**Comment by gwarser** [comment]
https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/
