### ISSUE TITLE
uBlock Origin hides "Follow" buttons on GETTR!

### ISSUE THREAD

**Issue by PELock** [uBlockOrigin/uBlock-issues#1920]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Well, with uBlock Origin enabled I cannot see Follow buttons on the new social media site GETTR

https://twitter.com/PELock/status/1479464156474531840

### A specific URL where the issue occurs

https://gettr.com/

### Steps to Reproduce

Go to any profile, all Follow buttons are hidden

### Expected behavior

Follow buttons be visible

### Actual behavior

Follow buttons hidden

### Configuration

Default settings

**Comment by gorhill** [comment]
This is a filter issue, report to uAssets as asked:

> ### Filter issues/website is broken
> 
> Report filter issues with specific websites to the [`uBlockOrigin/uAssets`](https://github.com/uBlockOrigin/uAssets) issue tracker.

Also, do not remove configuration information, filter issues can be properly diagnosed only when configuration information is provided as asked.

**Comment by gorhill** [comment]
Nobody volunteers earns anything working on this project, so "lose users" is the least of our worries, especially entitled ones.

**Comment by gorhill** [comment]
> Does not happen with default lists/settings

So on top of all else, this was misleading with false information since Fanboy Social or Fanboy Annoyance are not enabled by default, wasting volunteers time.

> ### Configuration
> 
> Default settings

**Comment by uBlock-user** [comment]
As usual, low quality and misleading reports..

**Comment by gorhill** [comment]
cc @ryanbr, this should be added to Fanboy Social:

    gettr.com#@#.follow-button

As per Reddit thread.
