### ISSUE TITLE
Update mirrors of curben's filters

### ISSUE THREAD

**Issue by curbengh** [uBlockOrigin/uBlock-issues#1921]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I made a major change to the mirrors.
Changes required on uBO is available at https://github.com/curbengh/uBlock/commit/417d6c99f96b3b48f7e2093c874743963d4b3652

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBlock Origin version

d1d9fab603d660e15fe9804f925422109273d55e

### Browser name and version

N/A

### Operating System and version

N/A

**Comment by gorhill** [comment]
I pulled your changes in <https://github.com/gorhill/uBlock/commit/417d6c99f96b3b48f7e2093c874743963d4b3652>.

I wonder:

    https://malware-filter.pages.dev/urlhaus-filter-online.txt
    https://urlhaus-filter.pages.dev/urlhaus-filter-online.txt

Is it worth to have two entries for the same provider -- does it make a difference on your side?

**Comment by gorhill** [comment]
[Remove redundant mirrors](https://github.com/gorhill/uBlock/commit/82ad7bd4fba2f0fd8de4d08489cf81ed9d7ae0e0)
