### ISSUE TITLE
[Feature Request] Add advanced setting to allow overwriting the expire-time of filter lists.

### ISSUE THREAD

**Issue by gettysburg** [uBlockOrigin/uBlock-issues#1922]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I would like to overwrite the expiration-time of filter lists I am subscribed to, possibly through advanced settings.

You can already adjust how often uBlock Origin checks for list updates, how long it waits between compilation of filter lists, and how long to wait after extension start before checking for list updates, however, ultimately you are still limited by the lists expire-time, which is 5 days for most lists.

One variable in advanced settings, which overrides the expire-time for ALL lists would be good enough, however a more fine-grained control over every single list would obviously be better - maybe even embedded into the "Filter lists" page.

If such a feature was to be implemented, uBlock Origin should enforce a lower boundary so that users could not just overwrite the expire-time to extremely low settings, causing more load on the servers distributing the lists.

I tried to find a more appropriate way to submit my feature request, but didn't find one - if this is the wrong way to do it, please tell me what would be the correct one.

Many thanks for reading.

### A specific URL where the issue occurs

/advanced-settings.html OR /dashboard.html#3p-filters.html

### Steps to Reproduce

1.) Open /advanced-settings.html or /dashboard.html#3p-filters.html
2.) There is no way to overwrite expire-time of filter lists.

### Expected behavior

I would expect a way to overwrite the expire-time of lists, the 5 days used by many lists is too long in my opinion.

This could either be a new variable in the advanced-settings, or a per list setting on the /dashboard.html#3p-filters.html site.

### Actual behavior

Currently, there is no way to overwrite expire-time of filter lists, so I have to manually purge all caches, and then force an update of all filter lists.

### uBlock Origin version

1.40.5b1

### Browser name and version

Firefox 91.4.1esr

### Operating System and version

Windows Server 2019 LTSC 1809.17763.2366

**Comment by gwarser** [comment]
What is the actual issue? Why you wan to alter expire time? "Just because"?

**Comment by gorhill** [comment]
Declined with no further comment.

**Comment by gettysburg** [comment]
@gwarser In order to make uBlock Origin more customizable for advanced users, not everyone agrees with the expire-times set by list maintainers, and would like to receive updates earlier.

This should be pretty easy to implement, so I have no idea why the request gets "declined with no further comment" - sure, I can achieve the same effect by dropping caches and force-reloading all lists, but a variable to overwrite the expire-time set by third-party list maintainers would still be nice.

**Comment by gettysburg** [comment]
@gorhill

Their lists are mirrored (and cached) by a bunch of CDN's through which uBlock Origin ultimately fetches them, to both decrease latency and increase throughput - I can't imagine much traffic actually hitting their back-end servers to which the CDN's connect to (only once per list update, mind you, otherwise the CDN will just serve cached data), but even I thought of that before you mentioned it above, quote from my first post:

"If such a feature was to be implemented, uBlock Origin should enforce a lower boundary so that users could not just overwrite the expire-time to extremely low settings, causing more load on the servers distributing the lists."

And after all, by making this an advanced feature and not adding it as a GUI option, most users wouldn't even know about / use it - so the argument of "excessive bandwidth usage" is a pretty weak one, in my opinion, especially in 2022 where bandwidth has become incredibly cheap - for example, my CDN provider does not charge for static content at all, I just pay a monthly fee which is reasonable as well, still connections to my back-end servers have dropped by around 74%.

Please reconsider adding this feature, and if your answer is still no, then I will just stick to emptying caches and force-reloading all lists every 24 hours. 👍
