### ISSUE TITLE
Picker is broken by quotation mark in attribute

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#1923]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Selecting some cosmetic candidates does not have any effect.  (all pointing to or inside the element with malformed attribute)

Picker throws exception when trying to `querySelectorAll` on attribute with quotation mark in value.

### A specific URL where the issue occurs

https://cinewoodlinkfinder.blogspot.com/2022/01/sarkar-2021-south-movie-hindi-dubbed.html?m=1

### Steps to Reproduce

1. open webpage
2. pick green download button
3. try selecting first two cosmetic candidates

Code sample:

```html
<a href="src=&quot;https://propu.sh/pfe/current/tag.min.js?z=3453923&quot;">

<img data-original-height="640" data-original-width="240" src="https://1.bp.blogspot.com/-XRZH0MdSnK4/XxQfrtsDfjI/AAAAAAAAAKU/M9GUnb6IyBkeGXuvjFztmWeuZZn4Gts2wCLcBGAsYHQ/s320/download%2Bbuttons%2Bcolors.png" title="" style="" height="120" border="0">

</a>
```

### Expected behavior

Selected filter should be chosen, visible in picker textarea.

### Actual behavior

Previously selected filter is visible in textarea. (Network filter chosen automatically when picker is opened.)

### Configuration

<details>

```yaml
uBlock Origin: 1.40.5b1
Firefox: 97
filterset (summary): 
  network: 93429
  cosmetic: 109993
  scriptlet: 19428
  html: 840
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 1660-28, 1d.1h.23m
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt: 9182-16, 2h.25m
    https://raw.githubusercontent.com/dns-test/iploggerfilter/master/filterlist: 2454-35, 2d.2h.38m
    https://raw.githubusercontent.com/gwarser/filter-lists/master/my-filters.txt: 77-0, 2d.2h.38m
    https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt: 142-0, 2h.24m
    https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4584-2464, 2d.2h.38m
    adguard-spyware-url: 433-74, 2d.2h.38m
    block-lan: 44-0, 2d.2h.38m
    fanboy-annoyance: 62911-3630, 2d.2h.38m
    ublock-annoyances: 4367-6, 2d.2h.38m
    POL-0: 7759-30, 1d.1h.24m
    POL-2: 1265-9, 2h.26m
  default: 
    ublock-filters: 30657-73, 2d.2h.38m
    ublock-badware: 3652-2, 2d.2h.38m
    ublock-privacy: 183-2, 2d.2h.38m
    ublock-abuse: 76-0, 2d.2h.38m
    ublock-unbreak: 1723-2, 2d.2h.38m
    easylist: 62804-602, 1d.5h.25m
    easyprivacy: 26605-483, 2d.2h.38m
    urlhaus-1: 6904-0, 1d.1h.25m
    plowe-0: 3685-13, 2d.2h.38m
filterset (user): [array of 140 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 15 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 744 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
urlRuleset: 
  added: [array of 19 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}} {{url}}
  blockingProfiles: 11111/#E00 11010/#C0F 11001/#00F 10001/#00F 00001
  cacheControlForFirefox1376932: unset
  filterAuthorMode: true
  filterOnHeaders: true
  popupPanelDisabledSections: 1
  popupPanelLockedSections: 32
supportStats: 
  allReadyAfter: 251 ms (selfie)
```
</details>

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/148849084-86847565-761d-411d-a407-84809fb2fa2f.png)

**Comment by ghajini** [comment]
@gwarser ,it doesn't solved the problem i described in slack channel
iam on ubo 1.40.8, firefox android

**Comment by gwarser** [comment]
This is not yet in 1.40.8. Dev version only.

**Comment by gwarser** [comment]
![Screenshot_20220116-211323](https://user-images.githubusercontent.com/886325/149676400-b74491c6-7dcf-469d-be31-6461ece63706.png)
