### ISSUE TITLE
[feature request] build instructions

### ISSUE THREAD

**Issue by eladkarako** [uBlockOrigin/uBlock-issues#1931]
<details>
<summary></summary>

### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

any chance of getting a wiki page on how to build locally, 
(for developers wanting to contribute pulls of fixes and tests and such).
I can tell its npm based, but the makefile there is kind of putting me off.. :|

### A specific URL where the issue occurs

https://whatever.

### Steps to Reproduce

1. this template is annoying.

### Expected behavior

2. too much to fill in.

### Actual behavior

3. I've got nothing.

### uBlock Origin version

oh god more boxes to fill

### Browser name and version

is this maintainer is a former DMV employ?

### Operating System and version

so.. many.. questions.. must press submit...

</details>

any chance of getting a wiki page on how to build locally, 
(for developers wanting to contribute pulls of fixes and tests and such).
I can tell its npm based, but the makefile there is kind of putting me off.. :|

**Comment by gorhill** [comment]
I updated the build instructions, see <https://github.com/gorhill/uBlock/tree/master/dist#build-instructions-for-developers>.

**Comment by eladkarako** [comment]
thanks. 
I wasn't aware there is anything useful / another readme inside 'dist' folder. it is usually a name preserved for build results and often its content is ignored, part from being a placehold,   
and the link in main readme said install, and links the word 'manually'.

that's a really good way to hide a section in plain sight! ;)

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Home/_compare/25c7ea0d7f262c70fab3d200de608d4c279107b4

**Comment by u-RraaLL** [comment]
> This expression does not feel right "Tagged release package".

Here: https://github.com/uBlockOrigin/uBlock-issues/wiki/Home/_compare/8ab1622929083c2560bd5d0f71c4a076e621c240
