### ISSUE TITLE
aepos.ap.gov.in: ads

### ISSUE THREAD

**Issue by ravikumarjujare** [uBlockOrigin/uBlock-issues#1933]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://aepos.ap.gov.in/ePos/SRC_Trans_Int.jsp`

### Category

Banner

### Describe the issue

I used to remove banners (yellow background) for compacting UI of the page. Now it doesn't work anymore.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 88
filterset (summary): 
  network: 78145
  cosmetic: 40536
  scriptlet: 16417
  html: 617
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30734-30, 1d.7h.31m
    ublock-badware: 3728-1, 1d.7h.30m
    ublock-privacy: 187-0, 1d.7h.29m
    ublock-abuse: 76-0, 1d.7h.28m
    ublock-unbreak: 1732-0, 1d.7h.27m
    easylist: 63046-586, 1d.7h.26m
    easyprivacy: 26627-480, 1d.7h.25m
    urlhaus-1: 7135-0, 9h.42m
    plowe-0: 3685-2, 9d.12h.40m
filterset (user): [array of 14 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 639 ms (selfie)
popupPanel: 
  blocked: 3
```
</details>

**Comment by gorhill** [comment]
Why was this transferred to uBlock-issues?

**Comment by gwarser** [comment]
Because OP claims that Picker does not work?

**Comment by uBlock-user** [comment]
OP reports he can't hide a header banner with uBO.

**Comment by uBlock-user** [comment]
> Due to lack of screen space while working with big reports, we used to remove the big yellow banner using "element picker mode". It used to create some rule internally (when we pick it). I had seen the rule, but don't remember the exact rule.

Recently (last two months), something seem to have changed. Either the website changed the syntax of it's html or the way javascript works OR the newer version of uBlock Origin has changed something internally while picking the element, we are not able to pick the banner anymore (I lean towards the former, that, something in the website has changed).

**Comment by gwarser** [comment]
It's probably the issue with default selection in proposed filters in the picker.

**Comment by gwarser** [comment]
It picks the background image as the default proposed filter in 1.40.8 - fixed in dev.

**Comment by gorhill** [comment]
> Either the website changed the syntax of it's html or the way javascript works OR the newer version of uBlock Origin has changed something internally while picking the element, we are not able to pick the banner anymore (I lean towards the former, that, something in the website has changed).

If we can't reproduce, it's an issue with OP failing to select the proper filters from the list of suggested ones -- there are no detailed repro steps, we have no idea what OP tried to do which is reportedly failing. I select the header, the default suggested filter is `##.clear.full_width`, and that works. All of this sounds like a support issue, not even a filter or code issue.

**Comment by gorhill** [comment]
> It picks the background image as the default proposed filter in 1.40.8

Alright I see. People have to realize that regardless of this, the picker is a tool that will at most pick a best guess filter, ultimately it's for the user to fine tune to pick the best filter acording to what they want to accomplish, while using the Preview button to help with this. There is never a guarantee the picker will select the optimal filter out of all the possible candidates offered, it's for the user to decide.

**Comment by ravikumarjujare** [comment]
Agree that we could pick from one of the suggestions while using element picker mode. I had not realized that the suggestions feature was there.
