### ISSUE TITLE
Element Picker disappears when opened on nytimes.com

### ISSUE THREAD

**Issue by noogeu** [uBlockOrigin/uBlock-issues#1934]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

This link renders ublock inoperable. There is only a brief moment where ublock seems to allow to pick an item, but this ephemeral.

### A specific URL where the issue occurs

`https://www.nytimes.com/interactive/2019/01/17/world/asia/china-population-crisis.html`

### Steps to Reproduce

1. open link
2. try to use ublock
3. see it doesn't

### Expected behavior

use ublock

### Actual behavior

can't use it.

### uBlock Origin version

uBlock Origin: 1.40.8

### Browser name and version

Chromium: 95

### Operating System and version

opensuse 15.2

**Comment by gwarser** [comment]
Something inline and can be defused by both nostif and nosiif.

**Comment by gwarser** [comment]
`www.nytimes.com##+js(nosiif,stopScrolling)`?
