### ISSUE TITLE
Persist Elements

### ISSUE THREAD

**Issue by FuckingToasters** [uBlockOrigin/uBlock-issues#1935]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When finding Advertisements, Images that you want to be removed or any other Element that should be removed by uBlock orgin the Elementselector works just fine. However after reloading the Website the Elements are back.
In another Adblocker i used before (Adblock Plus) The Elements i removed stayed removed even after a reload of the Page.
I use the Standard Configuration and changed nothing within the Settings nor did i blocked Javascript.

### A specific URL where the issue occurs

https://www.wirtschaftswissen.de/unternehmensgruendung-und-fuehrung/arbeitsorganisation/sekretariat/5-grundregeln-so-erstellen-sie-ein-professionelles-protokoll/

### Steps to Reproduce

1. Installing the Addon
2. Visiting the Website
3. Trying to remove Elements manually
4. Elements are present even after reloading the page

### Expected behavior

Elements shoud not be kept removed

### Actual behavior

It only remove the ELements once and after visiting the PAge again or reloading it the Elements are still there.

### uBlock Origin version

1.40.8

### Browser name and version

Microsoft Edge  97.0.1072.62

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> Trying to remove Elements manually

Describe in details how you did this.

**Comment by uBlock-user** [comment]
That's Zapper, it doesn't create any filters, use the Picker.

**Comment by gorhill** [comment]
> - [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

[Documentation](https://github.com/gorhill/uBlock/wiki/Element-zapper):

> The purpose of the element zapper is to quickly deal with the removal of nuisance elements on a page **without** having to create one or more filters. [...] Of course, since no filters are created, all the elements you removed will be back once you reload the page.

Use [Element picker](https://github.com/gorhill/uBlock/wiki/Element-picker) to create filters.

**Comment by FuckingToasters** [comment]
Oh okay well this was a issue on my side then. It now works as it should. Thank u for your help :)

**Comment by gwarser** [comment]
@FuckingToasters can I ask how you choose _zapper_ button? Did you looked at tooltips?

**Comment by FuckingToasters** [comment]
> @FuckingToasters can I ask how did you choose _zapper_ button? Did you looked at tooltips?

I tried some of the buttons and after using the zapper button i thought, it removes elements so that is what i need. 
After reloading the Webpage all Elements, i just removed where shown again.
Even now, when i use the correct Tool i dont know, for what the zapperbutton is useful for.

**Comment by uBlock-user** [comment]
You still haven't read the wiki - https://github.com/gorhill/uBlock/wiki/Element-zapper

**Comment by gorhill** [comment]
> Even now, when i use the correct Tool i dont know, for what the zapperbutton is useful for.

I presented you an excerpt, and a link to that excerpt where the purpose is explained.

**Comment by FuckingToasters** [comment]
> You still haven't read the wiki - https://github.com/gorhill/uBlock/wiki/Element-zapper

Well thank you for this. I not saw the that the issue was addressed in the Wiki. Sorry to brother you.
