### ISSUE TITLE
Element removal window covers Website

### ISSUE THREAD

**Issue by firefoxlover** [uBlockOrigin/uBlock-issues#1936]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When removing elements using the context menu/ element picker or anything, the Popup on the bottom right covers an often important part of the website, mostly where the Facebook/Instagram Links are. 

### A specific URL where the issue occurs

github.com

### Steps to Reproduce

1. right click on an element on the bottom right corner of the website
2. select "block Element"
3. when trying to accurately block it using the sliders, you cant see if you block the right things

### Expected behavior

Could you add a function to move the element removal popup to a new window or to the bottom left/top right of the screen?. Default could stay like that or maybe better on the top right.

### Actual behavior

The Popup stays there, even in the Preview mode.

### uBlock Origin version

1.40.8

### Browser name and version

Firefox Desktop 96.0.0

### Operating System and version

Ubuntu newest

**Comment by gorhill** [comment]
> - [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

[Documentation](https://github.com/gorhill/uBlock/wiki/Element-picker#once-in-element-picker-mode):

> You can easily move the element picker dialog out of the way, using the mouse by clicking and dragging the empty space between the _Preview_ and _Create_ buttons.
