### ISSUE TITLE
Chromium overwrites uBO's `click-to-load.html` resource

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1938]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

First [reported on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/s8ewj9/).

At this point this does look like a browser issue, the browser should not overwrite the purposefully redirected resource by the extension.

### A specific URL where the issue occurs

`https://www.theverge.com/2022/1/19/22891046/google-play-games-android-games-windows-pc-beta-launch`

### Steps to Reproduce

- Add the following filter to _"My filters"_: `||youtube.com/embed/$3p,frame,redirect=click2load.html`
- Navigate to `https://www.theverge.com/2022/1/19/22891046/google-play-games-android-games-windows-pc-beta-launch`
- Result: the click-to-load widget appears but is quickly replaced by Chromium's own _"This page has been blocked by an extension"_ widget.

### uBlock Origin version

1.40.9b2

### Browser name and version

Chromium 97.0.4692.71

### Operating System and version

Linux

**Comment by Nojuuu** [comment]
If you block `cdn.vox-cdn.com/packs/js/chorus-edf49eb13a6c77a4c3a4.js` it works, so the issue is somewhere there.

**Comment by dportvine** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/19732

**Comment by dportvine** [comment]
https://github.com/uBlockOrigin/uAssets/discussions/19732
