### ISSUE TITLE
Visual Studio 2019/2022 debugging site remains at about:blank

### ISSUE THREAD

**Issue by iprak** [uBlockOrigin/uBlock-issues#1939]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When debugging a sing page web application using Visual Studio with Chrome or Edge as browse target, VS launches the browser as something like this

`"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=55961 --no-first-run --no-default-browser-check --user-data-dir=C:\Users\_____\AppData\Local\Microsoft\VisualStudio\17.0_ca437560\WebTools\45106691_34FBCA4 about:blank`.

The debug url actually is define as `http://localhost:1979/HSWeb/` in the project and is somehow passed to the browser during debugging.

But the browser window continues to remain at `about:blank`
![image](https://user-images.githubusercontent.com/6459774/150410540-cf62075a-4d5f-4247-85e5-21c5d6629195.png)

This was noticed just around Dec 26 which coincides with 1.40.2 where a related [localhost issue](https://github.com/uBlockOrigin/uBlock-issues/issues/1902) was reported.

Upgrading to 1.40.8 did not help.

### A specific URL where the issue occurs

about:blank

### Steps to Reproduce

Start debugging (F5) the web application against using Chrome or Edge.

### Expected behavior

The browser should continue navigating to the debug url as before.

### Actual behavior

Browser remains at about:blank

### uBlock Origin version

1.40.8

### Browser name and version

Chrome 97.0.4692.71, Edge 97.0.1072.62

### Operating System and version

Win10 20H2 OS build 19042.1415

**Comment by uBlock-user** [comment]
Disable _Suspend network activity until all filter lists are loaded_ setting and try again.

**Comment by iprak** [comment]
I am unable to find this setting on `Filters lists` tab or Settings tab
![image](https://user-images.githubusercontent.com/6459774/150417167-b8ea29e5-6f20-4cd8-80fa-feb94726079a.png)

Is it `suspendTabsUntilReady` in advanced setting?

**Comment by gorhill** [comment]
Did you try without uBO?

**Comment by iprak** [comment]
@gorhill Yes.

**Comment by iprak** [comment]
Setting `suspendTabsUntilReady=false` in Advanced settings restored the previous behavior.

**Comment by gorhill** [comment]
I fail to see how uBO is causing the issue.

**Comment by gorhill** [comment]
Somebody else able to investigate code will have to look into this one, I do not have Visual Studio and your local configuration.

**Comment by iprak** [comment]
The issue only surfaces when uBO is installed.

**Comment by iprak** [comment]
The issue does not seem to happen in the dev build 1.40.9.1

I think this might have something to with tab reloading which now has been removed.

VS launches Chrome/Edge in a separate user-data folder with about:blank e.g. `"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=58562 --no-first-run --no-default-browser-check --disable-extensions --user-data-dir=C:\Users\iprakash\AppData\Local\Microsoft\VisualStudio\16.0_51656dfe\WebTools\10B84E65_1F1847B8 about:blank`.  

After that VS debugger communicated with Chrome over websockets and then eventually asks it to navigate to the actual debug url. This initial handshake navigation errors out/aborts.

```
[12:24:28.889 UTC] To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
[12:24:28.889 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/configurationDone","data":{"Versions.DebugAdapterCore":"6.8.9","Versions.DebugAdapter":"4.13.0","Versions.Target.CRDPVersion":"1.3","Versions.Target.Revision":"@adefa7837d02a07a604c1e6eff0b3a09422ab88d","Versions.Target.UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","Versions.Target.V8":"9.7.106.18","Versions.Target.Project":"Chrome","Versions.Target.Version":"97.0.4692.71","successful":"true","timeTakenInMilliseconds":"0.9906","requestType":"request"}}}
[12:24:29.586 UTC] ← From target: {"id":18,"result":{"frameId":"4E2F4DED425A8E8DAEE0463A7EAEBDB6","loaderId":"19240E00E58E3F49D0BB118B6167B77D","errorText":"net::ERR_ABORTED"}}
[12:24:29.588 UTC] ← From target: {"method":"Page.frameStartedLoading","params":{"frameId":"4E2F4DED425A8E8DAEE0463A7EAEBDB6"}}
[12:24:29.592 UTC] ← From target: {"method":"Runtime.executionContextsCleared","params":{}}
[12:24:29.593 UTC] To client: {"seq":0,"type":"event","event":"loadedSource","body":{"reason":"removed","source":{"name":"VM5","path":"<eval>/VM5","sourceReference":1000}}}
[12:24:29.593 UTC] ← From target: 
```

**Comment by gorhill** [comment]
uBO can't block navigating to a URL, but can block the network request for the main document. This means that even if the network request is blocked, the tab should have started navigating to the target URL, and it should show in the address bar -- at which point if uBO force a reload of the tab, it would force a reload of that URL. Can you reproduce the issue in 1.40.8 if you disable all the filter lists such that there are zero filters to enforce?

**Comment by iprak** [comment]
Unselecting all filters still gives the same problem.

![image](https://user-images.githubusercontent.com/6459774/150604803-5011adc0-192f-4e5f-be73-0c52c4141ad0.png)

Funny thing is that setting either true or false for suspendTabsUntilReady fixes the issue.

**Comment by gwarser** [comment]
> Funny thing is that setting either true or false for suspendTabsUntilReady fixes the issue.

Valid values are `yes`, `no` and `unset` strings. Setting it to something else will probably skip reloading here: https://github.com/gorhill/uBlock/blob/554241be46891c12a0d23ba1799856aba1822b64/src/js/traffic.js#L1154

**Comment by gorhill** [comment]
> Unselecting all filters still gives the same problem

Just to be sure, you have no block rules either in _"My rules"_?

**Comment by iprak** [comment]
There were no rules. This was in a new machine which did not have uBlock installed.

**Comment by gorhill** [comment]
So after all it does appear that forcing a reload of the currently active tab at launch is causing the issue -- this unconditional reload of the currently active tab at launch has been removed in the current dev build, in favor of reloading only if network requests were seen for a given tab before all lists were loaded.

Additionally, there is a new setting which can be toggled by the user if ever the maybe-reload-tab-at-launch is causing unforeseen issues in some edge cases.

**Comment by kolyanet** [comment]
To solve the issue of launching debugging through the browser in Visual Studio/Rider/Visual Studio Core on Windows 11, I checked the value of a parameter in the registry at:

`HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome`
The RemoteDebuggingAllowed parameter must be set to `1`

Here are the steps to open the registry editor and check/update this parameter:
1. Open the Run dialog by pressing `Win + R`.
2. Type `regedit` in the box and hit Enter to open the Registry Editor.
3. Navigate to the path:  
   `HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome`.
4. Look for the parameter named RemoteDebuggingAllowed.  
   - If it doesn't exist, create it:  
     - Right-click in the right panel, select `New -> DWORD (32-bit) Value`.  
     - Name it `RemoteDebuggingAllowed` and set its value to `1`.  
   - If it already exists, ensure its value is set to `1`.
