### ISSUE TITLE
[Feature request] Implement filter for class removing from element

### ISSUE THREAD

**Issue by anthoniussk** [uBlockOrigin/uBlock-issues#1943]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Hi,

some sites uses anti-ablockers, which removes all content if you block ads or remove ad element. So I suggest to you new feature - new type of filter, which will remove specified class or id from specified element. Syntax may be like this:(based on actual filter syntax):

--website.com##div.ad-blocked (will remove "ad-blocked" class from all divs)
--websice.com##div[class^='-blocked'] (will remove "-blocked" class from all divs)

Some website enable antiadblock after some timeout, so timeout extension will be superb, something like this:

--5--websice.com##div[class^='-blocked'] (will remove "-blocked" class from all divs 5 seconds after onready occurs)

And killer feature - maybe it exists and I haven't found it yet, but - filter to remove script element with specified pattern inside code, so something like regular expression on text property of script element.

All this features will fix lot of "antiadblock" features on sites. Thank you.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

There is example of page which needs to remove class from div to properly "unblock" uBO.

https://plus.noviny.sk/656468-komentar-arpada-soltesza-sulik-sa-postavil-do-radu-za-fica-a-mazureka

1. enable uBO
2. open https://plus.noviny.sk/656468-komentar-arpada-soltesza-sulik-sa-postavil-do-radu-za-fica-a-mazureka
3. open inspector, find header element with "-blocked" class and remove "-blocked" from class
4. find div with class "js-adchecker-screen" inside header element and remove div (it is not necessary, but it will unblock header image)

### Expected behavior

Remove class or id from element.

### Actual behavior

Site is partially blocked because of uBO enabled 

### uBlock Origin version

1.40.8

### Browser name and version

Vivaldi 5.0

### Operating System and version

Windows 10

**Comment by uBlock-user** [comment]
remove-class scriptlet exists.

**Comment by gwarser** [comment]
- https://github.com/gorhill/uBlock/wiki/Resources-Library#rcjs-
- https://github.com/gorhill/uBlock/wiki/Resources-Library#rajs-

**Comment by krystian3w** [comment]
Some also fix allow first party xhr https://github.com/uBlockOrigin/uAssets/commit/28c81fd7b0f1fcf606fa11c51563bb7519c4232b

**Comment by iam-py-test** [comment]
> - [X]  I checked the documentation to understand that the issue I report is not a normal behavior

Please read the wiki _before_ asking for a new feature
