### ISSUE TITLE
Feature Request: highlighting of domains affected by dynamic block rule in medium mode 

### ISSUE THREAD

**Issue by donestefan** [uBlockOrigin/uBlock-issues#1948]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I noticed ublock in [hard mode](https://github.com/uBlockOrigin/uBlock-issues/wiki/Blocking-mode:-hard-mode) will highlight all 3rd party domains affected by the global `3rd-party` block rule. The background color of the "local" column of all affected domains turns light red.
Since I'm a user of the [medium mode](https://github.com/uBlockOrigin/uBlock-issues/wiki/Blocking-mode:-medium-mode) I'd love to have the same highlighting for domains affected by my global `3rd party frames` and `3rd party scripts` block rules. This would make it much easier trying to narrow down which noop rules I might need.
I am aware that i could use the request log to find the same information - but it would be soooo much more convenient to have some domain highlighting in the main window. Especially for websites with high amounts of 3rd party requests.

For [static filters](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-My-filters) something similar exists twice already (color indicator to the left of every domain AND `+/-` Symbols in the "local" column). But for [dynamic filters](https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering) there no such indication yet :( 
I was hoping the [3rd party mini widget](https://github.com/gorhill/uBlock/commit/58505cfddcabf216fdfdd1150eedfc2f28f36435) would provide this information. But it just indicates which domain is embedding 3rd party content - lacking information whether this content ends up being blocked by a dynamic rule. 

### A specific URL where the issue occurs

https://www.paypal.com/login

### Steps to Reproduce

1. visit https://www.paypal.com/login and provide a username
2. you will be forwarded to https://www.paypal.com/auth/validatecaptcha, which is embedding multiple 3rd party contents (analytics, static content from cdn, multiple captcha providers, etc,) 
3. Open ublock connection log and filter for "3rd party" and "block"
4. Try to get an overview which domains where involved in dozens of blocked requests. Try to find which of these where caused by dynamic filters. Try to deduplicate domains when they serve multiple scrips/frames (you really only need each domain once). 
5. Try to create noop rules allowing you to continue your login and have fun repeating step 3,4,5 over and over again

### Expected behavior

You should not need to manually filter out mandatory information needed for creation of sane noop rules. If possible, this information be should present automatically where needed. A color indicator would be sufficient to provide this information in the main window.

### Actual behavior

Reading through log data and time consuming manual filtering is necessary to find information needed for creating sane noop rules.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 91050
  cosmetic: 60154
  scriptlet: 19209
  html: 623
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 6823-0, 2h.28m
    ublock-annoyances: 4374-4, 2h.37m
    adguard-social: 15614-14, 2d.3h.16m
    curben-phishing: 8890-4, 2h.27m
  default: 
    ublock-filters: 30817-41, 2h.36m
    ublock-badware: 3805-1, 2h.35m
    ublock-privacy: 191-0, 2h.34m
    ublock-abuse: 76-0, 2h.33m
    ublock-unbreak: 1699-0, 2h.32m
    easylist: 63316-599, 2h.31m
    easyprivacy: 26659-494, 2h.38m
    plowe-0: 3681-2, 5d.3h.11m
    DEU-0: 5280-2, 2h.30m
    urlhaus-1: 6585-5460, 2h.29m
filterset (user): [empty]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  cnameUncloakEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2804 ms (selfie)
```
</details>

**Comment by gwarser** [comment]
Try these buttons near the left edge: 
![obraz](https://user-images.githubusercontent.com/886325/150862791-426aec85-b424-4d49-9e40-b40a2f316b07.png)

**Comment by donestefan** [comment]
@gwarser thanks for the hint, but the `...` buttons "emphasize rows which have 3rd-party scripts and/or frames" (see [here](https://github.com/gorhill/uBlock/commit/58505cfddcabf216fdfdd1150eedfc2f28f36435))

This means for example, that it will show which site is outside of a frame (most likely an allowed 1st-party domain). But it will _not_ show which site is _inside_ of a frame (most likely a blocked 3rd party domain). The latter is the information I usually need for noop rule creation.

**Comment by gothic-bum** [comment]
@donestefan:  
  
When using Medium Mode, 1st-party resources (frames or otherwise) aren't blocked. So a *noop* isn't needed in that case.
  
For 3rd-party frames, clicking on the `...` will emphasize those domains, which will display dashes  `-` if any resources are blocked. In other words, you'll know which rows have 3rd-party frames (since they are emphasized), and which of those have resources are being blocked (indicated by dashes `-`).

**Comment by donestefan** [comment]
I see my mistake now. In hard mode cells _with_ changing background are the ones affected. But when using "`...`", cells _without_ changing background are the ones affected 🤦‍♂️. I guess you're trying to gray out cells that are already gray. Sorry, it took me so long to understand that...
