### ISSUE TITLE
UI Themes are Not Working

### ISSUE THREAD

**Issue by LucianAndries** [uBlockOrigin/uBlock-issues#1952]
### Prerequisites

- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Hello.

I am now using a fresh install of uBlock, with default settings on everything.

The issue is that I cannot set the ui theme to dark mode, even if it kills it.... I wrote "dark" in there and nothing.
Disabled the extension, restarted Chrome, nothing. It's always white.
In the documentation it says that if it's by default "unset", then it uses Chrome's built-in themes. And my Chrome's theme is set to "Black".....

I really don't know what to do.

Also, I would like the Classic theme, but in dark mode. I love that better because the drop-menu is smaller, and the button arrangement is better. I'd pay for that. :(
Also, dark modes should be a combination of dark gray nuances, not complete black...

I dunno what data to provide, so ask me and I will provide it. Thank you.

PS: Too many OBLIGATORY unrelated and unnecessary stuff to check and write on this form!

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/advanced-settings.html

### Steps to Reproduce

1. Enable advanced mode.
2. Set ui to dark.
3. Restart chrome.
Dunno what else to say...

### Expected behavior

A dark theme to be enabled.

### Actual behavior

White theme no matter what.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.8
Chromium: 97
filterset (summary): 
  network: 78435
  cosmetic: 40801
  scriptlet: 16487
  html: 0
listset (total-discarded, last updated): 
  default: 
    easylist: 63545-9, 8h.55m
    easyprivacy: 26677-17, 8h.55m
    plowe-0: 3679-817, 8h.55m
    ublock-abuse: 77-0, 8h.55m
    ublock-badware: 3816-69, 8h.55m
    ublock-filters: 30285-155, 8h.55m
    ublock-privacy: 194-2, 8h.55m
    ublock-unbreak: 1686-39, 8h.55m
    urlhaus-1: 6993-0, 8h.55m
filterset (user): [array of 30 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: 
  uiTheme: dark
supportStats: 
  launchToReadiness: 180 ms (selfie)
```
</details>

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#uitheme

>For development purposes only! DO NOT create issues about this feature!
Locked to dev build only in 1.31.3b5.

**Comment by LucianAndries** [comment]
Oh....... So is there any way to change the theme? Even the Classic/Old theme? Because that doesn't work either.

**Comment by gorhill** [comment]
> - [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

I don't find this acceptable that you checked the documentation and dismissed the warning about not opening issue.
