### ISSUE TITLE
uBlock Origin doesn't work with Dark Reader!

### ISSUE THREAD

**Issue by ExpertMen** [uBlockOrigin/uBlock-issues#1953]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I am student, and I have issues on official school website, Abeka.
So, I have problems with their custom scrollbars on their website.
Here is why do I think that I have this bug:
1. That bug started happens when I installed Dark Reader extension.
2. The bug is that the scrollbar sometimes appears and then 1 second later it's disappearing even if I am not touching it.
3. Before I started to use Dark Reader, I didn't have this bug.
4. All these bugs are happens in Firefox.
Yep, so see, that on any website which have their own custom scrollbars.

Next bug happens on Discord at canary.discord.com/app.

1. uBlock is blocking any custom stickers/emojis on Discord ( I mean Nitro Stickers and Nitro Emojis).
2. Avatars/usernames of users not loading – I have red line of user's avatars. Same thing happens to gif-avatars of Discord servers. Images is ok, but GIFs isn't.
3. Font on Discord&Abeka changed when I started using uBlock's new version. I didn't have this problem with old version.
Just now I see the default font of it. No more any custom/special fonts.
4. If I turn on uBlock's feature to block JavaScript, then I can say goodbye to YouTube, Facebook, and other social medias: they will not work.

### A specific URL where the issue occurs

https://academy.abeka.com/Video2/streaming/

### Steps to Reproduce

1. You need to have uBlock and Dark Reader extensions in Firefox web browser (the latest version!).
2. Now find any website (for example Discord Canary web version) that have custom scrollbars or in Canary Discord emojis/stickers.
3. Discord Canary's emojis/stickers (nitro) will start appearing and disappearing at the same time!
You will see that font is different.
4. If you're Abeka student, you will have issue with custom scrollbar on that link - https://academy.abeka.com/Video2/streaming/.
Just log in to your account and visit this link - that's it to have this issue!

### Expected behavior

I expected that I will not have these problems and uBlock will not block any icons and gifs.

### Actual behavior

I have these problems.

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0

### Operating System and version

Debian Linux (I have no idea which version of it am I using!).

**Comment by gorhill** [comment]
> - [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))

How did you verify this?

**Comment by ExpertMen** [comment]
> > * [x]  I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
> 
> How did you verify this?
 I checked this box because it's required to check it :)))

**Comment by gorhill** [comment]
> Before I started to use Dark Reader, I didn't have this bug.

Did you try to see if the issue occurs without uBO?

> I checked this box because it's required to check it :)))

Given this, I will close as invalid. Those checkboxes are there for a reason, to prevent burdening volunteers with invalid issues. Feel free to report back that the issue is indeed in uBO after you truthfully fulfill the required steps.

**Comment by uBlock-user** [comment]
> [X] uBO is the only extension

and yet you contradict yourself by saying

> That bug started happens when I installed Dark Reader extension.

**Comment by u-RraaLL** [comment]
There is only one issue with Dark Reader I know of:

When using one of the "Filter" themes, the picker window will scroll with the page / will stick to the top of the website, making it impossible to deal with lower items. I forgot what the issue about a website causing the same effect was called, so I can't mention it.

I haven't encountered any other problems using uBO and DR both.
