### ISSUE TITLE
On the document-blocked page, have uBO reflects the blocked page

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1954]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Related feedback: <https://www.reddit.com/r/uBlockOrigin/comments/rpd61s/cratering_a_whitelisted_filter/>

When on a document-blocked page, uBO's browser icon and popup panel reflect the state of uBO's own pages, not that of the blocked page. It would be more useful and expected that uBO reflects the state of the blocked page.

### A specific URL where the issue occurs

`https://doubleclick.net/`

### Steps to Reproduce

1. Navigate to `https://doubleclick.net/`in a new tab
1. Open the popup panel for the new tab
1. Try to disable uBO for `https://doubleclick.net/`

### Expected behavior

Having the popup panel fill with details related to `doubleclick.net`, and thus being able to disable uBO for that site straight from the panel.

### Actual behavior

The popup panel is filled with details related to uBO's own pages -- this is not useful.

### uBlock Origin version

1.40.8

### Browser name and version

Irrelevant

### Operating System and version

Irrelevant

**Comment by zozo2247800** [comment]
``
