### ISSUE TITLE
Update README.md to correct issues

### ISSUE THREAD

**Issue by q1800** [uBlockOrigin/uBlock-issues#1955]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I have a [patch](https://github.com/gorhill/uBlock/compare/master...q1800:patch-1) to update the uBlock Origin README.md file.

I have updated and corrected several URL issues and also updated the publisher's information for the Microsoft Edge version.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/README.md

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBlock Origin version

N/A

### Browser name and version

N/A

### Operating System and version

N/A

**Comment by gwarser** [comment]
Looks good.

**Comment by gwarser** [comment]
https://decentsecurity.com/ublock-for-firefox-deployment/ is marked as deprecated.

**Comment by gorhill** [comment]
Thanks, imported with <https://github.com/gorhill/uBlock/commit/95f5546672247beca127152892954c8029bcb064>. This means you are now a contributor and next time you can submit a pull request directly at <https://github.com/gorhill/uBlock>.

**Comment by q1800** [comment]
You're very welcome. I am glad to be able to contribute back to uBlock Origin. I have been using it for many years and absolutely love it. uBlock Origin is by far one of the best pieces of software I have ever used. It is the indispensable companion extension to Firefox. Both programs complement each other perfectly.
