### ISSUE TITLE
Backup file extension is wrong.

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#1956]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Currently, the extension of the backup file is txt.
Since it is actually JSON, we need to change the extension to .json.

### A specific URL where the issue occurs

none

### Steps to Reproduce

none

### Expected behavior

none

### Actual behavior

none

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.3

### Operating System and version

macOS 10.15.7

**Comment by gwarser** [comment]
Why it matter for you? `.txt` can be opened for preview in Notepad in any Windows. `.json` is unknown file.

**Comment by MoonlightCapital** [comment]
Can reproduce myself (`1.41.8`).

Seeing that the content of the backup file is in JSON format, I changed the file extention myself. Upon importing the backup file as JSON, it didn't seem to work at all until I renamed the file to have a .txt extention again and then I could import the settings.

@gwarser I think it's important for the file extention to be coherent with its content to help syntax highlighting recognition, and to decide which program should open the file, for example notepad++ or VScode (or even a simple browser like Firefox) are equipped with proper JSON formatting/parsing tools.

**Comment by gorhill** [comment]
> `.json` is unknown file.

Then that is a problem, I can't just make this change if the consequence is that this breaks opening the file through double-click for people who did not associate `json` with an application.

**Comment by krystian3w** [comment]
Also this drop support with older uBO and Legacy:

> Upon importing the backup file as JSON, it didn't seem to work at all until I renamed the file to have a .txt extention again and then I could import the settings.

**Comment by gwarser** [comment]
You can now select JSON files in file open dialog.
