### ISSUE TITLE
uBlock does not terminate/quit when profile in Edge is closed 

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1959]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When using two browser profiles in Edge closing the profile with uBlockOrigin completely (browser close) still shows uBlockOrigin active when opening Edge with another profile using the --profile-directory  switch in a shortcut. Both Edge profiles start with the New Tab Page.  Edge runs on Windows 10 21H2 (64 bits) with Edge option "Preload the new tab page for a faster experience" (meaning Edge is preloaded at Windows startup for faster program launch).

### A specific URL where the issue occurs

No

### Steps to Reproduce

Steps to reproduce issue

1. Start Edge with default profile (called blue for clarity sake) in which uBlockOrigin is the ONLY installed extension
2. Close that blue profile completely by closing the browser
3. Now no browser session is opened
4. Start Edge with another profile (called red for clarity sake) which has NO extensions through shortcut
5. Press Shift Esc to show the task manager
6. uBlockOrigin still shows in the Browser Task Bar as shown in picture
![image](https://user-images.githubusercontent.com/30925856/152292547-a291e667-2626-4134-9dd8-0d71f03caad0.png)

### Expected behavior

When closing the browser completely, I would have expected uBlockOrigin to close also

### Actual behavior

After closing a browser session with profile blue (which has uBO as only extension) and few seconds later opening another browser session with profile red (without uBlockOrigin), uBlockOrigin still shows in the Browser Task manager

### uBlock Origin version

1.40.8

### Browser name and version

Edge Version 97.0.1072.76 (Official build) (64-bit)

### Operating System and version

Windows 10 21H2

**Comment by uBlock-user** [comment]
_Continue running background apps when Chromium is closed_ is enabled or disabled ?

**Comment by Kees1958** [comment]
Switched off
![image](https://user-images.githubusercontent.com/30925856/152309263-58cdc093-be54-4865-bea9-fe6a66c38751.png)

**Comment by Yuki2718** [comment]
It's not an uBO issue nor Edge-specific, happens on all Chromium and no need to first launch the blue profile. Just have an extension installed on one profile is enouth to see it on browser task manager on another profile.

**Comment by Kees1958** [comment]
Checked
