### ISSUE TITLE
Preconfigure uBlock Origin when bundled with browser

### ISSUE THREAD

**Issue by probonopd** [uBlockOrigin/uBlock-issues#196]
Hello, I am bundling uBlock Origin with Firefox and with Chrome (in AppImage format for Linux):

* https://github.com/AppImage/AppImages/blob/master/recipes/Google_Chrome.yml
* https://github.com/AppImage/AppImages/blob/master/recipes/Firefox.yml

The result is that Linux users can download just one file, make it executable, and run a browser that has uBlock Origin preinstalled and preconfigured.

Now I would like to preconfigure uBlock Origin bundled with the browser to:
* Not show the sidebar by default
* Add and enable https://secure.fanboy.co.nz/fanboy-cookiemonster.txt by default

Is this possible, how?

**Comment by probonopd** [comment]
Looks like I'd have to use `/etc/chromium/policies/managed` which is a system-wide location where normal users don't have write access to. I am looking for something that doesn't need access to system-wide locations and instead loads the defaults from a location relative to the plugin or browser.

**Comment by probonopd** [comment]
If nothing else works, I could write the following to `$HOME/.config/google-chrome/Default/Extensions/cgbcahbpdhpcegmbfconppldiemgcoii/1.16.21.2_0/assets/assets.json`:

```
        "fanboy-cookiemonster": {
                "content": "filters",
                "group": "social",
                "off": true,
                "title": "Fanboy’s Cookiemonster List",
                "contentURL": "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt",
                "supportURL": "https://github.com/ryanbr/fanboy-adblock/issues"
        },
```

**Comment by gorhill** [comment]
You could configure uBO the way you want it, then quit Firefox and copy the resulting storage.js file (or whatever Firefox is using on your side) to the image?

**Comment by gorhill** [comment]
Firefox is opening the sidebar, not uBO: https://bugzilla.mozilla.org/show_bug.cgi?id=1460910

The stable release of uBO does not declare the `sidebar_action` persmission, so it won't open with the stable release you can find on AMO. The dev build does declare the `sidebar_action` permissions and because of a now reportedly fixed issue is should no longer opened with Firefox 62.

**Comment by probonopd** [comment]
> should no longer opened with Firefox 62

Great, thanks! :+1:

**Comment by gorhill** [comment]
No, it's causes too much changes in an unexpected ways for mainstream users. Fanboy Social (part of Fanboy Annoyances) used to be enabled by default a long time ago but I had to disable it, too many complaints of broken behavior.

**Comment by probonopd** [comment]
Thanks for your response. I am interested in disabling all those really annoying "this site uses cookies, do you accept" messages.

**Comment by gwarser** [comment]
Then maybe one more extension https://www.i-dont-care-about-cookies.eu/

**Comment by gorhill** [comment]
uBO could support something like `adminSettings`, but for first install purpose only, like `installSettings`.

**Comment by uBlock-user** [comment]
Has your question been answered ?

**Comment by probonopd** [comment]
Yes, thank you.

**Comment by gorhill** [comment]
The final answer is that you will have to copy the parts of the profile where uBO's settings are saved, just like you are already copying parts of the profile anyways.
