### ISSUE TITLE
Redirect to the blank page occurs when opening new incognito page and navigating by the link

### ISSUE THREAD

**Issue by 7dyuhejg7xm0** [uBlockOrigin/uBlock-issues#1969]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Browser doesn't load the page when opening new incognito page, quickly pasting some link and hitting enter. Please see the screencast:

https://user-images.githubusercontent.com/39586412/152975657-e836bb34-2e36-471d-895e-ab1c9fc8e698.mp4

### A specific URL where the issue occurs

none

### Steps to Reproduce

1. Make sure uBlock Origin is allowed to work in incognito mode
2. Make sure you don't have any incognito window open (for some reason this bug occurs only on first incognito load)
3. Prepare some link in your clipboard, e.g. `https://www.reddit.com/r/uBlockOrigin/`
4. Now quickly open incognito window (cmd+shift+n in mac os), quickly paste the link (cmd+v) and hit enter

### Expected behavior

Requested page should open

### Actual behavior

Blank page is opening

### uBlock Origin version

1.40.8

### Browser name and version

Chrome Version 98.0.4758.80 (Official Build) (x86_64), also latest Canary and Dev

### Operating System and version

macOS 10.15.6

**Comment by 7dyuhejg7xm0** [comment]
Started to notice this bug from the January, probably was introduced by the latest one or two updates

**Comment by uBlock-user** [comment]
Disable _Suspend network activity until all filter lists are loaded_ in Settings pane and try again.

**Comment by 7dyuhejg7xm0** [comment]
Interesting, bug disappears when I set `suspendTabsUntilReady` to some value (either `true` or `false`) except `unset`
