### ISSUE TITLE
Textarea focus border is slightly cut off from the sides in the static filter pane in the logger

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uBlock-issues#1970]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Textarea focus border is slightly cut off from the sides in the static filter pane in the logger

### A specific URL where the issue occurs

Logger

### Steps to Reproduce

-

### Expected behavior

![image](https://user-images.githubusercontent.com/84513173/153273379-1e83834a-01b2-4fe2-b156-0f723e212ac0.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/84513173/153272383-2426ea57-517b-452b-afaa-c7ebd84b877d.png)

### uBlock Origin version

1.40.9rc4

### Browser name and version

Brave 1.35.100 Chromium: 98.0.4758.87

### Operating System and version

Windows 10 21H2

**Comment by Nojuuu** [comment]
Possible fix adding some padding here:
https://github.com/gorhill/uBlock/blob/ad7eb5d1da95598d68f6f67438e99d46ab484e4b/src/css/logger-ui.css#L610-L615

**Comment by gwarser** [comment]
![obraz](https://user-images.githubusercontent.com/886325/153279896-fd491144-4184-4df8-a72f-79945aca16c1.png)

**Comment by gorhill** [comment]
I don't understand what is the reported issue. uBO does not modify the padding, it's a user agent picked one and I don't intend to override the user agent for this.

**Comment by gorhill** [comment]
Does adding `color-scheme: dark` solve your issue? This will be added at some point in the next dev cycle.

**Comment by Nojuuu** [comment]
It does not override the user agent, just gives room for it to be properly displayed inside the element in which it is placed?

**Comment by Nojuuu** [comment]
Firefox needs `calc(100% - 7px)`

**Comment by Nojuuu** [comment]
No worries, such a small thing anyway. 

I tested that fix and it seems to do the job so I guess this can be closed?
