### ISSUE TITLE
Info icon on the "Import..." part of the "Filter Lists" tab leads to non-existant wiki page

### ISSUE THREAD

**Issue by Adrthegamedev** [uBlockOrigin/uBlock-issues#1971]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Exactly what the title says. When you click on the "info" button next to the "Import..." button, it leads to the now non-existant wiki page of "Filter-lists-from-around-the-web".

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web

### Steps to Reproduce

1. Go to the "Filter Lists" tab in the Ublock Origin dashboard.
2. Scroll all the way down to the bottom until you find the "Import..." button.
3. Click the "Info" icon next to it.
4. You get sent to the main page of the wiki with a "You do not have permission to update this wiki." popup.

### Expected behavior

The wiki page should, indeed, exist, and not be deleted.

### Actual behavior

The wiki page somehow seems to be deleted, as it sends me back to the main page of it with a "You do not have permission to update this wiki." popup.

### uBlock Origin version

1.40.8

### Browser name and version

Google Chrome, Version 98.0.4758.80 (Official Build) (arm64)

### Operating System and version

macOS Big Sur, Version 11.5.2

**Comment by gwarser** [comment]
Restored in draft: https://github.com/uBlockOrigin/uBlock-issues/wiki/Filter-lists-from-around-the-web

**Comment by gorhill** [comment]
I pushed draft to master.
