### ISSUE TITLE
Unblocking websites that are blocked with a certain filter type doesn't work properly

### ISSUE THREAD

**Issue by S0dV** [uBlockOrigin/uBlock-issues#1976]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

**(While testing recently, I did use AdGuard VPN) and uBO was in Dark Mode)**
Unblocking `https://www.youtube.com/` (for example) did not work how someone may expect.

### A specific URL where the issue occurs

`https://www.youtube.com/`

### Steps to Reproduce

1. To test on `https://www.youtube.com/`, you can add `||youtube.com^`
2. Visit `https://www.youtube.com/`
3. Unblock `https://www.youtube.com/` via uBO
4. After being reloaded, the webpage will not have all the necessary resources in order to load properly, I think.

### Expected behavior

After unblocking, I would've expected it to be unblocked.
Related: https://github.com/tcptomato/ROad-Block/issues/114

### Actual behavior

Not enough resources for proper displaying, I think.

### uBlock Origin version

1.41.2

### Browser name and version

100.0.4871.0 (Dev build, 64 bit)

### Operating System and version

W10

**Comment by uBlock-user** [comment]
> Unblock https://www.youtube.com/ via uBO

How exactly did you do that ? Elaborate.

**Comment by gwarser** [comment]
Strict blocking will only unblock `doc` request.

**Comment by gorhill** [comment]
> add  `||youtube.com^`

Of course that is the expected behavior, you are yourself asking to block everything from `youtube.com`. If you want to block only the main document, use `||youtube.com^$doc`.

**Comment by S0dV** [comment]
> How exactly did you do that ? Elaborate.

by clicking a button that was present on the panel uBO directs users to when accessing a page blocked by it

**Comment by gorhill** [comment]
> clicking a button that was present on the panel uBO directs users to when accessing a page blocked by it

That just bypass [strict-blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking) which is the blocking of the main document only -- the button you click is labelled:

> Disable strict blocking for `youtube.com` [Temporarily] [Permanently]
