### ISSUE TITLE
[Enhancement] Add regional filter list for Luxembourg

### ISSUE THREAD

**Issue by grischard** [uBlockOrigin/uBlock-issues#1985]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

List at https://raw.githubusercontent.com/grischard/lux-blocklist/main/Luxembourg-blocklist.txt"

Example sites affected:

https://rtl.lu
https://wort.lu

### Describe the issue

I have published my list of small local annoyances. This is my first published list and first contribution to uBlock Origin; any feedback is welcome.

A bit like in uBlockOrigin/uAssets#11286, I don't expect the updates to be frequent, and doubt that Chromium will ever support the `lb` locale.

I'm a long-time uBlock Origin fan, and would be delighted if my list could help make it even a little bit better.

The entry in `assets/assets.json` would be:

```json
	"LUX-0": {
		"content": "filters",
		"group": "regions",
		"off": true,
		"title": "LUX: Luxembourg List",
		"lang": "lb fr de",
		"contentURL": "https://raw.githubusercontent.com/grischard/lux-blocklist/main/Luxembourg-blocklist.txt",
		"supportURL": "https://github.com/grischard/lux-blocklist"
	},
``` 

### uBlock Origin version

1.41.2

### Browser name and version

Chrome 98

### Settings

-

**Comment by uBlock-user** [comment]
Closing as per https://github.com/uBlockOrigin/uBlock-issues#ublock-issues:

> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

**Comment by grischard** [comment]
@uBlock-user sorry, https://github.com/uBlockOrigin/uAssets/issues/11286 led me to believe that that repo was the right place to open an issue.

What's the right way of doing this instead? Open individual issues for the sites my list fixes, then mention my list?

**Comment by uBlock-user** [comment]
@grischard Whether to add a regional list or not is decided internally with uBO Team. Please don't open issues for that.

**Comment by gorhill** [comment]
What could be done is to add `lb` to both already existing _"FRA: AdGuard Français"_ and _"DEU: EasyList Germany"_.
