### ISSUE TITLE
YouTube videos randomly pausing

### ISSUE THREAD

**Issue by MrMuffin16** [uBlockOrigin/uBlock-issues#1986]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Occasionally when watching any YouTube video, it will pause. This happens almost completely at random with intervals between these pauses lasting anywhere from 5 seconds to several minutes, sometimes not happening at all during a video but usually occurring about once per video.

### A specific URL where the issue occurs

https://www.youtube.com/

### Steps to Reproduce

1. Log onto youtube
2. Open any video and start watching

### Expected behavior

Video does not pause at all

### Actual behavior

Video pauses occasionally, at random, and sometimes when another tab is being viewed entirely at the time.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 77429
  cosmetic: 41343
  scriptlet: 16414
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63633-9, 3h.40m
    easyprivacy: 26560-120, 3h.39m
    plowe-0: 3679-807, 8d.1h.46m
    ublock-abuse: 77-0, 3h.38m
    ublock-badware: 3940-76, 3h.36m
    ublock-filters: 30227-138, 3h.35m
    ublock-privacy: 200-2, 3h.34m
    ublock-unbreak: 1716-39, 3h.16m
    urlhaus-1: 6498-0, 1h.33m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 436 ms (selfie)
  maxAssetCacheWait: 314 ms
```
</details>

**Comment by gwarser** [comment]
Hmmm, I cannot transfer to uAssets.

I think someone already asked something like this. It's not solved if I recall.

Do you have any other add-on for YT? I have similar issue with SponsorBlock. Also, Chrome can be pausing background tabs. Also, YT itself sometimes pauses long playing videos.

You can try if this changes anything:

	  youtube.com#@#+js(json-prune, [].playerResponse.adPlacements [].playerResponse.playerAds playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds)
	  youtube.com##+js(json-prune, [].playerResponse.adPlacements playerResponse.adPlacements adPlacements)
