### ISSUE TITLE
No option to block element in Edge on Windows 11

### ISSUE THREAD

**Issue by YesTrustMe** [uBlockOrigin/uBlock-issues#1988]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Normally you can hover over an element such as an ad on a webpage. You right click to open the context menu to select **Block Element** but with latest Edge on Windows 11, the option to right click doesn't do anything.

### A specific URL where the issue occurs

https://www.msn.com/en-ca/video/news/ford-says-world-is-done-with-covid-19/vi-AATUGKK?ocid=msedgdhp&pc=U531

### Steps to Reproduce

Right click on any ad or element

### Expected behavior

Various options to block element

### Actual behavior

Nothing happens

### uBlock Origin version

 1.41.2

### Browser name and version

Edge 98.0.1108.55 (Official build) (64-bit)

### Operating System and version

Windows 11 21H2

**Comment by gwarser** [comment]
Still working in Win10.

**Comment by gorhill** [comment]
Please use _"Report an issue on this website"_ button in popup panel while on that site, and in the _"Report a filter issue"_ page, click _"Troubleshooting information"_, and paste here. the content of the revealed technical information.

**Comment by gwarser** [comment]
If I right-click in this Dailymotion iframe and select Block element instead of Block element in frame, then nothing happens.

![image](https://user-images.githubusercontent.com/886325/154366168-be305a1b-bdc4-441e-b9dc-28181aac861d.png)

If I recall correctly, previously the whole iframe was selected?

**Comment by gorhill** [comment]
The `iframe` is into a shadow root, with the top-most reachable element above the shadow root being `fluent-card`. I can select that element with the picker from the popup panel, but not from the contextual menu.
