### ISSUE TITLE
"popupTipNoScripting1" & "popupTipNoScripting2"

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#199]
@gorhill this is just a suggestion, to change the following texts:
Current:
```
"popupTipNoScripting1":{
    "message":"Click to wholly disable JavaScript on this site",
```
```
"popupTipNoScripting2":{
    "message":"Click to no longer wholly disable JavaScript on this site",
```

Changed:
```
"popupTipNoScripting1":{
    "message":"Click to disable JavaScript on this site",
```
```
"popupTipNoScripting2":{
    "message":"Click to no longer disable JavaScript on this site",
```
I think the word "wholly" is over, and with the text that I propose would also be understood. It is only a suggestion, since with only "disable" it is already understood.

**Comment by gwarser** [comment]
This has been discussed in Crowdin comments.

>javasctipt can be blocked by static or dynamic filters on the site, and with this toggle you don't affect these filters (you just undoing the whole blocking to the previous state of the partial blocking)...

**Comment by uBlock-user** [comment]
Adding adverbs only enhances the statement author is trying to make and as a side effect can lead to people questioning how wholly it blocks amoung other questions, so it's better to keep it simple and not have arousing questions amoung users with such adverbs. So I agree with the removal.
