### ISSUE TITLE
uBlock issue 3708: "uBlock Origin translation"

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#2]
Continuation of <https://github.com/gorhill/uBlock/issues/3708>.

**Comment by joey04** [comment]
In response to your concern there about "uAssets" not being translatable, I don't see why that would be a concern. Consider that filter-syntax is essentially English-based to begin with and if they find a filter issue they'll need to report it in English on the tracker here. So why would the "uAssets" label be a problem?

**Comment by overdodactyl** [comment]
>But keep in mind that the list names themselves are still predominantly English words. So it's practically unavoidable for a user to select lists without some understanding of English.

Unless I'm mistaken, I believe the list names have translations.  For example:

https://github.com/gorhill/uBlock/blob/daf762d56a92459776a3b5a1e09bd213785a44dc/src/_locales/ja/messages.json#L358-L369

**Comment by overdodactyl** [comment]
>The idea is more like "Homegrown" filter lists -- as in "these lists are maintained by uBO", and I ended up using "Local" because that's what seemed least worse in listed synonyms.

Maybe something like "uBO Affiliated"?

**Comment by BilBg** [comment]
Some icons after the name with appropriate info/link (e.g. Who makes these lists / Where these lists come from / What every list is for...) may also help.

    uBlock Origin's set of lists (?) (i)

**Comment by joey04** [comment]
> Unless I'm mistaken, I believe the list names have translations.

I was unaware of that. But it only applies to uAssets lists, right? EasyList and many others will still be English-only names. So my point still mainly applies.

**Comment by overdodactyl** [comment]
@joey04, on second look, I may have been mistaken.  The code I linked to was the translations for headers, not the actual lists themselves.

**Comment by vlaszlo** [comment]
How about "Internal" or "Built-In" with a tooltip or an information icon that explains (or links to an explanation) that these lists are maintained by the author of uBlock Origin, but can be updated independently from the extension for efficiency?
