### ISSUE TITLE
[popup.html] add tooltips

### ISSUE THREAD

**Issue by guraga** [uBlockOrigin/uBlock-issues#20]
### Prerequisites

- [+] I verified that this is not a filter issue
- [+] This is not a support issue or a question
- [+] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [-] uBlock Origin is the only extension
    - [-] uBlock Origin with default lists/settings
    - [-] using a new, unmodified browser profile
- [+] I am running the latest version of uBlock Origin
- [-] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

User can't understand purpose of clickable elements.
What difference between red, green and brown?
What meaning of "+" and "-"?
What function of second column?
Add helpful descriptions as tool tips (attribute "title") to elements of "popup.html".

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/

### Steps to reproduce:

1. Click on extension icon to open "popup.html".
2. Move mouse pointer to any clickable element.

### Expected behavior:

Show tool tip with helpful description.

### Actual behavior:

No tool tip shown.

### Your environment

* uBlock Origin version: 1.16.0.
* Browser name and version: official build of 64-bit of "google chrome" version 66.0.3359.117.
* Operating System and version: ubuntu 16.04.

**Comment by gwarser** [comment]
I see one problem. When "I am an advanced user (required reading)" is disabled, tooltip in popup looks like when "advanced user" is enabled. Beside of this - issue is invalid.

**Comment by jawz101** [comment]
This might have merit for the vision impaired users.  Usually screen readers need to be able to read text in a gui interface to know what to say to the user.

**Comment by vanowm** [comment]
Was this issue declined because it would make the extensions user friendly and that's is clearly goes against developer's goal? We have to read the entire manual with hundred of pages in order to find what the fk is left column does vs right column? I read the manual 3 years ago do you expect me remember everything from it?

**Comment by uBlock-user** [comment]
This was declined more than a year ago, so why bother to grave-dig it now?

**Comment by gwarser** [comment]
Tooltip is already here:

![image](https://user-images.githubusercontent.com/886325/62421915-1e445100-b6aa-11e9-9c53-6d837cd2a7ec.png)
![image](https://user-images.githubusercontent.com/886325/62421918-28fee600-b6aa-11e9-9a65-82df6a2e527e.png)
