### ISSUE TITLE
missing regex test

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#200]
I'm patching some recent changes and noticed that a regex test is missing [at this line](https://github.com/gorhill/uBlock/commit/8f1b4b52fde58c60210bdd404c2c68211a66457f#diff-3c9018f7821de34a861d8bee5bbc48f7R448).

It should be `reIPv4VeryCoarse.test(hostname)` like the prior line, otherwise the if will always be true.

(I don't have any IP rules to test with; just an observation.)

**Comment by gorhill** [comment]
Ugh, thanks for spotting this, this might warrant an emergency fix.
