### ISSUE TITLE
primewire.vc - redirect issue for chromecast full screen only

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uBlock-issues#2001]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The way to report issues has changed. I tried to answer all of the questions throughly, clearly, and to the best of my ability.
If I am reporting this incorrectly, I beg your pardon.

I did confirm that the issues does not exist when ubo is turned off.
ubo ver: 1.41.2
Chrome ver: 98.0.4758.102
osx ver: El Capitan 10.11.2

**EXAMPLE:**
Visit `https://www.primewire.vc/tv/1406668/watch-judy-justice-season-1-episode-53`
Choose VERSION 1 hyperlink on the page which opens up the link you want to show
Cast this page via chromecast to a TV
When the FULLSCREEN or double arrow option is selected after casting, website is redirected to GOOGLE home page.

Can anyone help me with this issue?

Thank you.
AD

### A specific URL where the issue occurs

`https://www.primewire.vc/tv/1406668/watch-judy-justice-season-1-episode-53`

### Steps to Reproduce

**EXAMPLE:**
Visit `https://www.primewire.vc/tv/1406668/watch-judy-justice-season-1-episode-53`
Choose VERSION 1 hyperlink on the page which opens up the link you want to show
Cast this page via chromecast to a TV

### Expected behavior

The screen should cast to the TV screen selected via Chromecast menu

### Actual behavior

When the FULLSCREEN or double arrow option is selected after casting, website is redirected to GOOGLE home page.

### uBlock Origin version

ubo ver: 1.41.2

### Browser name and version

Chrome ver: 98.0.4758.102

### Operating System and version

osx el capitan version 10.11.2

**Comment by gorhill** [comment]
> - [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))

> the issues does not exist when ubo is turned off

How did you verify it's not a filter issue?

**Comment by gorhill** [comment]
Use the _"Report an issue on this website"_ button in the popup panel. If you can't tell an issue is not a filter issue, then assume it is a filter issue.

**Comment by aldiener58** [comment]
Dear Mr. Hill,
Thank you for responding to my issue.

Can you provide a link to where to report it? The website reporting has
changed dramatically and I am so confused about
how and where exactly to report an issue.

Thank you,
AD

**Comment by gorhill** [comment]
> Use the _"Report an issue on this website"_ button in the popup panel of uBO.

**Comment by gorhill** [comment]
> Use the _"Report an issue on this website"_ button in the popup panel

<https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website>

**Comment by aldiener58** [comment]
Well I just submitted it again and I hope it is in the right place. I
wasn't sure if you would see my response given that the issue was
closed. I am doing my best to follow the rules, Mr. Hill.

**Comment by aldiener58** [comment]
Dear Mr. Hill,
I just looked at the link you provided. It doesn't take me to a form that I
can fill out. It is very confusing.
Would you be willing to provide me with a screenshot of what you expect me
to see when I follow that link?

Thank you for your time and consideration of this request.

Sincerely,
AD

**Comment by gothic-bum** [comment]
1. Click the uBO icon in your browser toolbar to open the [pop-up interface](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website).  
2. Click the "chat" icon located in the middle of the [tools row](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools).  
3. A tab/window will open with the ["Report a filter issue"](https://github.com/gorhill/uBlock/wiki/The-%22Report-a-filter-issue%22-form) page.
4. Follow the instructions on the page to submit an issue.

**Comment by aldiener58** [comment]
Thank you, Mr. Gothic Bum, for responding to my post.

I did post the same issue again online. Can you confirm if it is in the
wrong place?
If it is still in the wrong place, I will follow your instructions :-)

Thank you for your time and support.

Sincerely,
AD

**Comment by gorhill** [comment]
> I did post the same issue again online.

You did it without using the _"Report an issue on this website"_ button in uBO's popup panel, and as a result the report is missing all the troubleshooting information, making it more difficult for volunteers to address the issue you report.
