### ISSUE TITLE
Do you support these two versions?

### ISSUE THREAD

**Issue by edentw** [uBlockOrigin/uBlock-issues#201]
Hello!

Do you support these two versions?

firefox dev for android +uBlock Origin
firefox nightly for android +uBlock Origin

In the process of "Clear private Data", it will cause the crash problem.

In the process of "Clear private Data", the problem that the machine does not react will be raised.

So I would like to confirm that these two versions are supported?

Thank you!

**Comment by gorhill** [comment]
Please respect the template if you want to report an issue. If you experience a browser crash, report to Firefox devs, uBO is HTML/CSS/JS, it's not supposed to crash the browser, and if it does, this is a browser issue.
