### ISSUE TITLE
Youtube pre-roll ads

### ISSUE THREAD

**Issue by pritkr** [uBlockOrigin/uBlock-issues#2016]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Youtube pre-roll ads coming
Although I could not reproduce it when tried with new browser profile
I am sorry if I am wasting your time
This happened for the first time today
![image](https://user-images.githubusercontent.com/81620727/155880669-a3d5649a-fca7-4d1a-aba4-c7ec9dbdf8ca.png)

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=ykzkIMMMVXw

### Steps to Reproduce

I couldn't but just notifying if anyone else faces this issue

### Expected behavior

No pre-roll ads on youtube

### Actual behavior

Pre-roll ads on youtube

### uBlock Origin version

1.41.4

### Browser name and version

Chrome 98.0.4758.102

### Operating System and version

Windows 7

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1051971696
