### ISSUE TITLE
suggestion & question for HTML filtering code

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#203]
I was curious to learn how HTML filtering worked, so I read some of the code. Now I have a suggestion and a question.

The suggestion: only call `filterDocument` when possible. This way no function call in Chrome.
Can change [these lines](https://github.com/gorhill/uBlock/blob/6d34a52179aaa8fdf701b3bc7ab80f02ed5f0f23/src/js/traffic.js#L595-L596) to
```
    let filteredHTML = false;
    if ( µb.canFilterResponseBody ) {
        filteredHTML = filterDocument(pageStore, details) === true;
    }
```

The question: what's the purpose of [this line](https://github.com/gorhill/uBlock/blob/138e1bf55866e4a97c2ef192ffb4d6489ff7e498/src/js/html-filtering.js#L291)? Is the blank hash for generic rules?

**Comment by adisib** [comment]
That is a purely cosmetic change. The expression doesn't have to finish evaluating if canFilterResponseBody is false (though I don't know if this is mandated or merely true for any reasonable javascript engine).

**Comment by gorhill** [comment]
What @adisib said, and for the blank hash, that is where all the hostnames for which a domain can't be extracted are stored.

**Comment by joey04** [comment]
Thanks guys for the helpful responses. Good to know nothing needs to change.
