### ISSUE TITLE
The logger doesn't show matched results if search string includes ! followed by a character

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2040]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

On [NSFW] `https://upornia.com/videos/4434949/mia-melano-in-vixen-4689/` a filter `upornia.*##.jwplayer > .afs_ads + div[style="display:flex !important"]` in uBlock filters hits if you pause the player and correctly shown in the logger; however, if you enter search string of `##.jwplayer > .afs_ads + div[style="display:flex !important"]`, it's somehow filtered out. It seems as long as the string contains `!` + character, in this case `!i`, the matched results are not shown.

### A specific URL where the issue occurs

https://upornia.com/videos/4434949/mia-melano-in-vixen-4689/

### Steps to Reproduce

1. Visit the site, play and pause the player with the logger opened.
2. Search for `##.jwplayer > .afs_ads + div[style="display:flex !important"]` in the logger, see no results.

![logger1](https://user-images.githubusercontent.com/58900598/157720285-6ac18823-c29e-493a-a76f-070d1b14dd74.png)

3. If you edit the string so that it no more contains `!i`, the results will appear.

![logger2](https://user-images.githubusercontent.com/58900598/157720303-8e2eea30-1d66-46b6-a4fa-8d847a17039c.png)

### Expected behavior

The matched results should be shown.

### Actual behavior

Not shown 

### uBlock Origin version

1.41.8 and 1.41.9b0

### Browser name and version

Firefox 98.0

### Operating System and version

Windows 10

**Comment by u-RraaLL** [comment]
Interesting. 

`.jwplayer > .afs_ads + div[style="display:flex !` and `.jwplayer > .afs_ads + div[style="display:flex "]` works.
Looks like the search ignores exclamation marks entirely.

@Yuki2718 Why search for the full string btw?

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#filtering-the-logger-output

**Comment by Yuki2718** [comment]
@gwarser The document says
> Prefix any expression with

But it's inside the string.

**Comment by Yuki2718** [comment]
> 
>  Why search for the full string btw?

Just was checking if the filter is still in use without noticing the issue.
