### ISSUE TITLE
uBO misses a very specific script that should be caught by a regex filter

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2041]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

See 

![log](https://user-images.githubusercontent.com/58900598/157903204-99c46d1c-8d85-44c9-aad2-98286702ce52.png)

Not a filter issue, saved regex101 as an evidence: `https://regex101.com/r/ULnFgs/1` Also checked AG blocks this, but even with AG Base (slightly different regex) enabled the same result on uBO so not a filter issue.

The responsible filter is `/^https?:\/\/(?:www\.|[a-z0-9]{7,10}\.)?[-a-z0-9]{5,}\.(?:com?|bid|cl(?:ick|ub)|li(?:nk|ve)|net|online|top)\/(?:[a-z0-9]{2}\/){2,3}[a-f0-9]{32}\.js/$script,xhr,3p` in uBlock filters.

### A specific URL where the issue occurs

`https://porn-images-xxx.com/` [NSFW]

### Steps to Reproduce

Visit the site with the logger opened.

### Expected behavior

The request should be blocked

### Actual behavior

Not

### uBlock Origin version

1.41.8 and 1.41.9b0

### Browser name and version

Firefox 98.0

### Operating System and version

Windows 10

**Comment by ghajini** [comment]
Can't reproduce
![Screenshot (300)_105411~2](https://user-images.githubusercontent.com/20338483/157917056-52391798-c777-4d88-a700-55daf9a76303.png)

Firefox 98.0
ublock origin 1.41.8

**Comment by Yuki2718** [comment]
I can still reproduce but only on Firefox, not on Chromium.

**Comment by gorhill** [comment]
Can't reproduce either:

![Screenshot from 2022-03-11 12-32-31](https://user-images.githubusercontent.com/585534/157918501-3c5743ee-390d-4554-82bc-9a48d394049c.png)

**Comment by Yuki2718** [comment]
Okay, happens only if Chinese filters is enabled.

**Comment by gorhill** [comment]
Investigating.

On my side I have a scenario where in the same page load `https://knifecontributionproposition.com/68/ec/f0/68ecf07f7970259df17debfe5a1b1bfb.js` is properly blocked, but `https://knifecontributionproposition.com/94/eb/0e/94eb0eb8f3e78d5bb507ff6561a953e0.js` is not.

**Comment by gorhill** [comment]
I what no clue what is going on. Looking at the internals of the static filtering engine, there is no reason for `.../knifecontributionproposition.com/94/...` to go through, while `.../knifecontributionproposition.com/68/...` is properly blocked by the filter. Not sure if related, in Chromium I am unable to see a network request to `.../knifecontributionproposition.com/94/...`, the one not being blocked in Firefox.

**Comment by gorhill** [comment]
Found the issue: the hash of the token `0e` in the URL is `0`, which is the value used internally to mark the end of token sequence.

**Comment by gorhill** [comment]
I consider this fix to be a candidate for a revision to current stable.

**Comment by Yuki2718** [comment]
Something that should not happen has happened on 1.49.3rc16/Chrome 114.0.5735.110 only once:

![invoke](https://github.com/uBlockOrigin/uBlock-issues/assets/58900598/3511b756-aa2d-4bba-9133-1572364d3e18)

As you see, invoke script that should be caught by a regex escaped blocking. I'd have not noticed if not redirected to a malickous site. Once I refreshed tha page, it gets blocked without changing anything - no way to reproduce. If anything, I opened 10 tabs via middle-click at the time, but doing so does not reproduce issue any more.

**Comment by gorhill** [comment]
When at least one filter list updates, uBO will reload all the filter lists, so there is a small time window for which there could be no filtering applied. This might be what happened.

**Comment by Yuki2718** [comment]
I put the window in bad position, but the missed script was at 22:54:14 just below the `mc.yandex.ru` where other scripts are blocked.

**Comment by gorhill** [comment]
I've added logging to inform when loading all filter lists starts/ends So if ever it happens again, you will be able to tell whether this is what happens. The entry in the logger is informative so you need to select _All_ to see these. Will bein next dev build.

**Comment by Yuki2718** [comment]
Thinking twice, that's unlikely as I force-updated all filter lists before the job. No idea what was that as no more able to reproduce.
