### ISSUE TITLE
Consider making `peel.js` scriptlet

### ISSUE THREAD

**Issue by PerfectSalad** [uBlockOrigin/uBlock-issues#2044]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

`peel.js` could be used for `/peel.js$redirect-rule=peel.js` -- similar to `prebid-ads.js`

Example: https://github.com/PerfectSalad/for-scriptlet/blob/main/peel.js

I didn't get it to work since I didn't modify the redirect engine locally.

### A specific URL where the issue occurs

`https://cryptofun.space/`

### Steps to Reproduce

It's a concept

### Expected behavior

.

### Actual behavior

`peel.js` isn't a redirectable scriptlet

### uBlock Origin version

1.41.8

### Browser name and version

Tor

### Operating System and version

Windows 10

**Comment by mapx-** [comment]
use

`@@||cryptofun.space^$script,1p`

it's not possible adding scriptlets for all the baits in easylist

**Comment by PerfectSalad** [comment]
@Yuki2718 what do you think

similar anti-adb on `https://bigbtc.win/` & `https://getfree.co.in/litecoin/`

**Comment by PerfectSalad** [comment]
@ryanbr

**Comment by PerfectSalad** [comment]
@gorhill What do you think?

**Comment by gorhill** [comment]
We are not going to add local resources for just three obscure sites, there are already solutions using existing filter syntax.

**Comment by PerfectSalad** [comment]
> We are not going to add local resources for just three obscure sites

A `megaurl. in`-probably-related page used the same, or similar, bait I think

> there are already solutions using existing filter syntax.

Well, not generic, and with the current scriptlets, I think that currently, only adding an exemption for the bait/allowing the bait would make the website not detect it blocking of the bait
