### ISSUE TITLE
Can't contribute typofix

### ISSUE THREAD

**Issue by myersg86** [uBlockOrigin/uBlock-issues#2047]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I fixed 14 typographical errors across the docs and codebase but I'm unable to contribute because I'm blocked from opening a PR on the source repository.

Typofixes can be found here: https://github.com/myersg86/uBlock

### A specific URL where the issue occurs

https://github.com/myersg86/uBlock

### Steps to Reproduce

1. Fix a bunch of typos in `gorhill/uBlock`
2. Attempt to contribute the fix by making a pull request when you've not contributed to this project before.

### Expected behavior

1. Fix a bunch of typos in `gorhill/uBlock`
2. Contribute the fix upstream

### Actual behavior

1. Fix a bunch of typos in `gorhill/uBlock`
2. Attempt to contribute the fix by making a pull request.
3. Pull request blocked because I've not previously opened a PR on the project.

### uBlock Origin version

1.41.6

### Browser name and version

Chrome 99.0.4844.51

### Operating System and version

Ubuntu 21.04

**Comment by krystian3w** [comment]
This is not addon bug.

https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

**Comment by gorhill** [comment]
Thanks, I pulled your commit into uBO's repo: <https://github.com/gorhill/uBlock/commit/6573a59a596207d574e62f87c11cf579e93e4942>.
