### ISSUE TITLE
Search of a rule in all the lists

### ISSUE THREAD

**Issue by KOLANICH** [uBlockOrigin/uBlock-issues#205]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
It may be needed to find which filter contains a specific rule. I suggest to add a search in all filters, because for now I had to open each filter separately and search for a rule in it.

**Comment by uBlock-user** [comment]
It already exists, just open any filter list - 

![](https://i.gyazo.com/6e1e0177452b79c43b4bc22c7ab63dfe.png)

**Comment by KOLANICH** [comment]
>just open any filter list 

I don't want to iterate over filter lists and insert the rule into search field of each. This should be automated.

**Comment by gorhill** [comment]
> I had to open each filter separately and search for a rule in it.

And why did you need to do this?

**Comment by KOLANICH** [comment]
@gorhill, if a rule is/has an issue one may want to know which filter list has this rule in order to take action.

**Comment by mapx-** [comment]
In the logger you can click the filter and see where is placed

**Comment by gorhill** [comment]
> one may want to know which filter list

Click on the filter, it will show you which lists contain that filter.

**Comment by KOLANICH** [comment]
@gorhill, thanks, that works (on Android), ... if I used a stilus (I usually use fingers and the most of phones don't have a hover-sensing stilus causing mouse cursor appearrance). Taps don't open that, it would be nice to open this popup with taps too.

**Comment by verhovsky** [comment]
Please add a way to jump to the definition of a cosmetic filter from the DOM inspector, just as you can from the logger.

I am debugging a cosmetic filter (see https://github.com/compiler-explorer/compiler-explorer/issues/3174 ). The logger just says the filter that is blocking the modal window containing important information is "`#alert`" but doesn't say where the rule comes from

<img width="1252" alt="Screenshot 2024-02-16 at 17 04 21" src="https://github.com/uBlockOrigin/uBlock-issues/assets/5687998/698be8fa-45b1-4815-bdcb-7f18566af7aa">

Clicking on "#alert" just disables the filter. I have 15 filter lists enabled + my custom filters. I have to cmd+click 15 times to open each one in a new tab then I have to ctrl-tab through them press "cmd-f" "cmd+v" 16 times and when I see a match I have to think about each one and decide if it looks like the filter or if I should keep searching. It's tedious and I wasn't able to find the filter.
