### ISSUE TITLE
Remove netlify mirror from malware filters

### ISSUE THREAD

**Issue by curbengh** [uBlockOrigin/uBlock-issues#2050]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Unfortunately, my netlify account has been suspended due to bandwidth limit. Please remove its link from urlhaus-filter, phishing-filter and pup-filter.

https://github.com/curbengh/uBlock/commit/67996f4c1d3e83f786378ddd643822886d896ad9

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97

### Operating System and version

Manjaro

**Comment by gorhill** [comment]
I imported your commit: <https://github.com/gorhill/uBlock/commit/b4fe22c7b6b47b4a2630c3024f582edab4495e4c>.
