### ISSUE TITLE
The quick-fixes is not prevented from being visually collapsed

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#2056]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

If you updated assets.json when quick-fixes was disabled by default, uBlock Origin doesn't seem to regard quick-fixes as one of the default lists, even if you update to the latest assets.json. 

Related: 
https://github.com/gorhill/uBlock/commit/7508700

### A specific URL where the issue occurs

`moz-extension://<extension_id>/dashboard.html#3p-filters.html`

### Steps to Reproduce

1. `git clone https://github.com/gorhill/uBlock.git`
2. `cd uBlock`
3. `git checkout 2dbbe0f`
4. `make firefox`
5. `firefox 'about:debugging#/runtime/this-firefox'`
6. Click Load Temporary Add-on... and open `/path/to/uBlock/dist/build/uBlock0.firefox.xpi`
7. Open uBlock Origin Filter lists pane and click Update now.

### Expected behavior

When you collapsed the built-in filter list, unchecked quick-fixes will remain visible.

### Actual behavior

When you collapsed the built-in filter list, unchecked quick-fixes will be hidden.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.9b1
Firefox: 98
filterset (summary): 
  network: 79333
  cosmetic: 41621
  scriptlet: 16533
  html: 627
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30942-29, now
    ublock-badware: 3926-3, now
    ublock-privacy: 204-0, now
    ublock-abuse: 72-0, now
    ublock-unbreak: 1751-0, now
    easylist: 64273-595, now
    easyprivacy: 26702-572, now
    urlhaus-1: 7933-1, now
    plowe-0: 3671-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2507 ms
  maxAssetCacheWait: 316 ms
```
</details>

**Comment by u-RraaLL** [comment]
Well, yes. It's an experimental filter list, not a default one. It uses `.obsolete` instead of `.isDefault` (which is required for the collapse-prevention).

**Comment by hirorpt** [comment]
> not a default one.

You must see the latest commit. https://github.com/gorhill/uBlock/commit/4c2bfbe
We do not have access to the internal discussion, but there is no doubt that the conclusion is defaulting.

**Comment by gwarser** [comment]
It was not set as default but it is now.
