### ISSUE TITLE
[Performance] uBO causes lag on certain pages

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uBlock-issues#2057]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In that page, if uBO is open, even if no rules are enabled and no filtering rules are applied, it will cause a dramatic slowdown in the response time of the page. 
Please see the motion picture I recorded. When a notification pops up in the upper right corner of the page, it means the page has been fully loaded. Otherwise, some functions do not work properly.
![image](https://user-images.githubusercontent.com/66902050/158957201-735e1fdd-b6e8-4f59-9771-769c9ca3e205.png)
![2022-03-18_15-59-06.gif](https://s2.loli.net/2022/03/18/xkbmOh2cID3fMTE.gif)
(You may need to use a Chinese VPN to open this page, which is a mirror site of Wikipedia and therefore restricts access to non-mainland Chinese IPs.)

### A specific URL where the issue occurs

`https://zh.wikipedia.wikimirror.org/wiki/%E5%A4%AA%E9%99%BD%E8%8A%B1%E5%AD%B8%E9%81%8B`

### Steps to Reproduce

Open this page

### Expected behavior

Web page lag

### Actual behavior

Web page should not lag

### uBlock Origin version

v1.41.8

### Browser name and version

Microsoft Edge 99.0.1150.39 (64-bit)

### Operating System and version

Windows 11 21H2

**Comment by gorhill** [comment]
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data + analysis supporting the claim.

Beside, I get _"site can’t be reached"_ at the provided URL.

**Comment by shenzhiming88** [comment]
@gorhill You may need to use a Chinese VPN to open this page, which is a mirror site of Wikipedia and therefore restricts access to non-mainland Chinese IPs.
By the way, how can I get actual profiling data + analysis? Thanks!

**Comment by gorhill** [comment]
I don't have a Chinese server in my VPN.

Use the Performance pane in dev tools, use the reload button to gather profiling data from page load -- and ensure that uBO itself is the issue when looking at the profiling data.

**Comment by shenzhiming88** [comment]
> I don't have a Chinese server in my VPN.
> 
> Use the Performance pane in dev tools, use the reload button to gather profiling data from page load -- and ensure that uBO itself is the issue when looking at the profiling data.

I'm sorry, I can't read the parameters. Should I send you the configuration file for analysis?

**Comment by gorhill** [comment]
You can zip the file and drop it here in a comment.

**Comment by shenzhiming88** [comment]
[Profile.zip](https://github.com/uBlockOrigin/uBlock-issues/files/8305407/Profile.zip)

**Comment by gorhill** [comment]
Please provide here the content of troubleshooting information at the bottom of the Support pane.

**Comment by gorhill** [comment]
The site's own code is causing the issue. I can't access the code since I can't access the site, but the browser performance tool points at JS code at `zh.wikipedia.wikimirror.org/wikimirror.js:380:16` -- this is the hot spot. The fact that it's worst with uBO is probably because the highly generic filters being injected, and the issue should be there as well with other blockers such as ABP or AdGuard, i.e. it's not specific to uBO. You can [disable cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) to avoid the issue.

**Comment by shenzhiming88** [comment]
> Please provide here the content of troubleshooting information at the bottom of the Support pane.

Fine.
```
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 106667
  cosmetic: 108534
  scriptlet: 19908
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://gitlab.com/DandelionSprout/adfilt/-/raw/master/LegitimateURLShortener.txt: 1779-0, 8h.21m
    block-lan: 44-0, 10d.4h.53m
    fanboy-annoyance: 63542-173, 6d.14m
    ublock-annoyances: 4360-123, 1d.23h.35m
  default: 
    user-filters: 0-0, never
    CHN-0: 28347-87, 1d.23h.46m
    easylist: 64209-15, 1d.23h.41m
    easyprivacy: 26684-147, 1d.23h.39m
    plowe-0: 3674-807, 10d.4h.54m
    ublock-abuse: 72-0, 1d.23h.42m
    ublock-badware: 3950-84, 1d.23h.43m
    ublock-filters: 30354-178, 1d.23h.36m
    ublock-privacy: 200-12, 1d.23h.38m
    ublock-unbreak: 1739-45, 1d.23h.34m
    urlhaus-1: 7983-0, 8h.20m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 536 ms (selfie)
  maxAssetCacheWait: 218 ms
```

**Comment by shenzhiming88** [comment]
> I can't access the code since I can't access the site, but the browser performance tool points at JS code at `zh.wikipedia.wikimirror.org/wikimirror.js:380:16`
I can get it and I have uploaded it here.
[wikimirror.zip](https://github.com/uBlockOrigin/uBlock-issues/files/8305783/wikimirror.zip)

**Comment by gorhill** [comment]
That is the code causing the issue:

    const fn = () => {
        d.html.style.height = 'auto';
        d.html.style.height = `${d.html.scrollHeight}px`
    }

Obviously uBO can't fix web pages out there, so you will have to mitigate the web page issue by partially or wholly disabling cosmetic filtering. For example, try:

    ||wikipedia.wikimirror.org^$ghide

**Comment by shenzhiming88** [comment]
Ok, I will go and contact the owner of the page. Thank you!
Also, I don't seem to see any filtering rules applied by uBO, so why is it still causing lag?

**Comment by gorhill** [comment]
Highly generic cosmetic filters are always injected, the logger will report only those which match something on the page. Related <https://github.com/uBlockOrigin/uBlock-issues/discussions/1998>.

**Comment by gwarser** [comment]
In some cases, the logger can also slow thing down.
