### ISSUE TITLE
uBlock Origin blocks all requests when hanging

### ISSUE THREAD

**Issue by hello-smile6** [uBlockOrigin/uBlock-issues#2061]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When uBlock Origin is unresponsive, every HTTP request hangs until the extension process is killed or the browser is restarted.

### A specific URL where the issue occurs

Extension options page (open `chrome://hang` from URL bar, open any website including https://github.com/)

### Steps to Reproduce

1. Start a new instance of Chromium with a new profile.
2. Install uBlock Origin.
3. Open the uBO options page.
4. Open `chrome://hang` on the extension page using the URL bar.
5. Attempt to open any website.

### Expected behavior

I was expecting that it would be as if uBO was disabled.

### Actual behavior

I had to restart my browser. When testing on Chrome OS, I had to restart my device.

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

### Operating System and version

Windows 10, Chrome OS 99.0.4844.57

**Comment by gorhill** [comment]
I could reproduce same issue with Adblock Plus, AdGuard, Privacy Badger, NoScript. There are no exceptions thrown in uBO and no errors reported. Disabling the extension solves the issue. So it's not a uBO-specific issue, looks like you stumbled onto a browser/extension option page issue, which can be avoided by *not* pasting `chrome://hang` in the URL address.

**Comment by hello-smile6** [comment]
@gorhill Could you report the bug on the Chromium bug tracker? If an extension is unresponsive for more than 10 seconds, the browser should probably just give up on waiting. I'd create an issue, but I don't want to share my email address.
