### ISSUE TITLE
Yandex Browser blocks the extension from working on some pages of its service

### ISSUE THREAD

**Issue by lzrdblzzrd** [uBlockOrigin/uBlock-issues#2065]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

It looks like Yandex Browser is blocking the extension on some pages of its service. For example, on https://yandex.ru/internet the extension is disabled by default and you will not be able to enable it. 
![image](https://user-images.githubusercontent.com/32615368/159929204-117ef783-ded1-4414-ad5c-277363a64c91.png)
This button simply does not work, because of this, the page is filled with ads.

### A specific URL where the issue occurs

https://yandex.ru/internet

### Steps to Reproduce

1. Open any page in Yandex Browser and you will be able to enable/disable the extension on this site
2. Open the page https://yandex.ru/internet / in Yandex Browser and you will not be able to enable uBlock on this page

### Expected behavior

uBlock should work on all sites

### Actual behavior

Yandex Browser has blocked the work of the extension, while Chrome does not block its work on the same page

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Yandex Browsder 22.3.0.2434

### Operating System and version

Windows 10  21H2

**Comment by gorhill** [comment]
> Yandex Browser has blocked the work of the extension

There is nothing the extension can do if it's disabled by the browser, you need to file an issue with Yandex.

**Comment by krystian3w** [comment]
uBO Lite should network filtering protected domains.

**Comment by gwarser** [comment]
Do Yandex browser even allow to install uBO?

**Comment by lzrdblzzrd** [comment]
> Do Yandex browser even allow to install uBO?

Yes, but block the work of the extension on their domains.

**Comment by gwarser** [comment]
@lzrdblzzrd https://www.reddit.com/r/uBlockOrigin/comments/xva1jl/yandex_browser_does_not_support_ublock_origin/

**Comment by krystian3w** [comment]
In the past Yandex uses Opera Store:

https://addons.opera.com/extensions/details/ublock/

Based on User Agent Opera change layout to Blueish and I guess use diffrent logo in header.
