### ISSUE TITLE
Filter list `Quick Fixes` automatic re-enables itself

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#2066]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The filterlist `Quick Fixes` re-enables itself after closing and opening your browser if you disable it. 

---
### A specific URL where the issue occurs

uBlock dashboard -> filterlists

### Steps to Reproduce

1. Disable the filterlist `Quick Fixes`
2. Remove browser history, cookies and cache.
3. Close browser (Microsoft Edge)
4. Wait a minute and open Edge again
5. Wait a minute
6. Go to uBlock Dashboard and then to filterlists
7. See that `Quick Fixes` is enabled

### Expected behavior

If I disable a list it must be disabled and not enable itself

### Actual behavior

The filterlist `Quick Fixes` re-enables itself after closing and opening the webbrowser.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 67819
  cosmetic: 43924
  scriptlet: 16612
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
    ublock-quick-fixes: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2995-10, 5m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 1996-0, 5m
  default: 
    user-filters: 213-0, never
    ublock-filters: 30479-90, 4m
    ublock-unbreak: 1742-10, 4m
    easylist: 64685-91, 4m
    easyprivacy: 26718-193, 4m
filterset (user): [array of 161 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  uiAccentCustom0: #f0b924
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  blockingProfiles: 11111/#F00 11010/#C0F 11001/#4242CA 00001
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  uiFlavor: classic
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 14145 ms
  maxAssetCacheWait: 1255 ms
```
</details>

**Comment by gorhill** [comment]
> 1. Disable the filterlist Quick Fixes
> 1. Remove browser history, cookies and cache.

After you disabled _Quick fixes_, did you click _Apply_ button?

**Comment by gorhill** [comment]
I am going to assume this is related to <https://github.com/gorhill/uBlock/commit/6fcc278c59f2921ae668528253d1bf5fa52697c8>, which I just reverted, Try next dev build, but you will have to shift-purge-all-caches to see if this fixes the issue.

**Comment by JohnyP36** [comment]
> I am going to assume this is related to [gorhill/uBlock@6fcc278](https://github.com/gorhill/uBlock/commit/6fcc278c59f2921ae668528253d1bf5fa52697c8), which I just reverted, Try next dev build, but you will have to shift-purge-all-caches to see if this fixes the issue.

The issue doesn't occur anymore. So I also assume it had to do with https://github.com/gorhill/uBlock/commit/6fcc278c59f2921ae668528253d1bf5fa52697c8, which you reverted.

**Comment by JohnyP36** [comment]
> > 1. Disable the filterlist Quick Fixes
> > 2. Remove browser history, cookies and cache.
> 
> After you disabled _Quick fixes_, did you click _Apply_ button?

Sorry, I overlooked this comment. But the answer is YES
