### ISSUE TITLE
Firefox managed storage properties other than adminSettings not applying

### ISSUE THREAD

**Issue by theaquamarine** [uBlockOrigin/uBlock-issues#2067]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When configuring uBlock's managed storage properties for Firefox, properties other than `adminSettings` aren't being applied, but they're applied properly in Chrome and Edge. I'm using the Windows registry, but have tested quickly using a json and I _think_ the same thing is happening.

I believe the issue is Firefox is escaping the properties and causing them to be read as strings rather than objects, as `typeof (await vAPI.adminStorage.get(['toOverwrite'])).toOverwrite` is `string` in Firefox but `object` in Chrome and Edge. `adminSettings` works as `JSON.parse()` is used on it, but not on the other properties, so the fix is probably more `if ( typeof json === 'string' && json !== '' ) {data = JSON.parse(json);}` like https://github.com/gorhill/uBlock/blob/ab6a59daf8bd183cbaf9f07d22f9d432d4adfc44/src/js/storage.js#L1392

The properties are also shown escaped on `about:policies` in Firefox even if they are not escaped in the registry (but not escaped on `chrome://policy` or `edge://policy`) suggesting Firefox is escaping them, but I've not been able to find anything saying this if this is expected.

### A specific URL where the issue occurs

https://github.com

### Steps to Reproduce

1. Configure an admin policy other than `adminSettings`, eg `toOverwrite` ```[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\3rdparty\Extensions\uBlock0@raymondhill.net]
"toOverwrite"="{\"trustedSiteDirectives\": [\"example.com\",\"example.org\"]}"```

1. Start Firefox

### Expected behavior

Settings are applied, in this example trusted sites are set to example.com and example.org

### Actual behavior

Settings are applied, in this example trusted sites are not set

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.2

### Operating System and version

Windows Server 2019 17763.737

**Comment by theaquamarine** [comment]
Same using `browser.storage.managed.get()` - `string` in Firefox but `object` in Chrome & Edge.
```javascript
browser.storage.managed.get(['toOverwrite'], function(result) {
  console.log(typeof result.toOverwrite)})
```

**Comment by gorhill** [comment]
> Configure an admin policy other than `adminSettings`, eg `toOverwrite` `[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\3rdparty\Extensions\uBlock0@raymondhill.net] "toOverwrite"="{\"trustedSiteDirectives\": [\"example.com\",\"example.org\"]}"`

I don't have Windows but what you are doing does not match the [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location).

**Comment by gorhill** [comment]
The other thing I observe is that you set `toOverwrite` to a string `"{\"trustedSiteDirectives\": [\"example.com\",\"example.org\"]}"`.

It's supposed to be an object, so should it be:

    {"trustedSiteDirectives": ["example.com","example.org"]}

?

**Comment by theaquamarine** [comment]
Ah sorry, I should've flagged that- no, that's just the export tool, it's not escaped in the registry.

So the registry ends up looking like this 
![image](https://user-images.githubusercontent.com/111144/160890384-0b230f98-de6b-43d8-91e3-ed558b2537e4.png)
which is shown on Firefox's `about:policies` like this
![image](https://user-images.githubusercontent.com/111144/160890643-dcd052d0-075b-4051-9439-0ce99dcd5986.png)
and then that's presented to the extension as a string, rather than an array
![image](https://user-images.githubusercontent.com/111144/160890772-f54fa057-d426-44f1-9bcc-c956e7cda339.png)


vs the same setting in Chrome, on chrome://policy, and inspecting the extension in Chrome
![image](https://user-images.githubusercontent.com/111144/160890897-5326952b-5c8e-4e68-90e5-46e129c2cd23.png)
![image](https://user-images.githubusercontent.com/111144/160890953-ede12c4e-3612-45bc-a802-dd728f73e367.png)
![image](https://user-images.githubusercontent.com/111144/160890967-8925440f-dde9-4031-8ecf-bb843cbd91a2.png)

**Comment by theaquamarine** [comment]
Mozilla say this is expected, and I've now got configuring Firefox via the registry working properly by changing the settings to `REG_MULTI_SZ` instead of `REG_SZ` as those are treated as json instead https://bugzilla.mozilla.org/show_bug.cgi?id=1762253
