### ISSUE TITLE
Feature Request: Addition of "Absolute Right Click & Copy" in ubo scriptlets

### ISSUE THREAD

**Issue by vishupal4185** [uBlockOrigin/uBlock-issues#2068]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Integration of "Absolute Right Click & Copy" or similar that enables right click context menus and copying text  in ubo scriptlets.

### A specific URL where the issue occurs

https://greasyfork.org/en/scripts/23772-absolute-enable-right-click-copy

### Steps to Reproduce

Mandatory Field.

### Expected behavior

Mandatory Field.

### Actual behavior

Mandatory Field.

### uBlock Origin version

1.41.8

### Browser name and version

Brave Browser Version 1.36.122

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
What is the issue and where?
