### ISSUE TITLE
Wrong element is picked because other element is shown

### ISSUE THREAD

**Issue by Wizard13** [uBlockOrigin/uBlock-issues#2069]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

See the following source code:
```
<a style="margin: 0 auto;text-align: center;border:none;line-height:1;display: block;text-decoration:none" href="https://www.ot.gr/2022/03/27/ot-forum/ot-forum-o-kosmos-pou-allazei-2/"  target="_blank" id="ot-forum">
	<picture>
	<source media="(min-width:800px)" srcset="/wp-content/themes/ingr_v2/common/imgs/ot640x100.jpg">
		<img src="/wp-content/themes/ingr_v2/common/imgs/ot330x100.jpg" alt="ingr" style="width:auto;">
	</picture>
</a>
```
I want to pick the banner. uBlock Origin sets the custom filter like this:
||www.in.gr/wp-content/themes/ingr_v2/common/imgs/ot330x100.jpg$image
However, image is not blocked because Firefox displays the ot640x100.jpg image

### A specific URL where the issue occurs

https://www.in.gr/2022/03/27/english-edition/real-estate-market-significant-increase-9-8-recorded-prices-new-apartments/

### Steps to Reproduce

1. Go to https://www.in.gr/2022/03/27/english-edition/real-estate-market-significant-increase-9-8-recorded-prices-new-apartments/
2. Find the image banner that has the words OT FORUM
3. Try to choose it with uBlock Origin in order to remove it.
4. Reload the page

### Expected behavior

Image is blocked.

### Actual behavior

Image is not blocked.

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0.2 (64 bit)

### Operating System and version

Windows 10 Pro x64 21H2

**Comment by gorhill** [comment]
The image is rendered using a `<picture> > <source>` layout, and uBO does not specifically handle `picture` elements.
