### ISSUE TITLE
Rule in a logger should be clickable and provide the link to the search

### ISSUE THREAD

**Issue by KOLANICH** [uBlockOrigin/uBlock-issues#207]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Rule in the logger should be clickable, the link should point to the line rule is defined.

**Comment by gorhill** [comment]
> However I believe I could link to the line in each filter lists found to contain the filter, such that clicking on it will cause the asset viewer to move to the line.

I will decline implementing this for the time being, this would require to save an offset into the compile filter lists for each filter, meaning a larger compiled filter lists, and I don't think it's worth it at this point where I have done work to actually shrink size of data saved in cache storage.
