### ISSUE TITLE
Invalid file name characters in wiki page titles prevent cloning

### ISSUE THREAD

**Issue by Skibicki** [uBlockOrigin/uBlock-issues#2071]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Cloning the Wiki will not finish on Windows due to invalid characters in page titles.
To see all pages, click the Pages button and then the 'show more pages' at the bottom of the list

Invalid characters: < > : " / \ | ? *

The characters and page titles containing them are below.

:
2014 07 22: uBlock and others: Blocking ads, trackers, malwares
Blocking mode: easy mode
Blocking mode: hard mode
Blocking mode: medium mode
Blocking mode: nightmare mode
Blocking mode: very easy mode
Compare: Memory footprint: what happens inside µBlock after installation
Contributed memory usage: benchmarks over time
Cosmetic filtering in uBlock: version 0.4.0.0 update
Cosmetic filtering in µBlock: version 0.4.0.0 update
Dashboard: 3rd party filters
Dashboard: Filter lists
Dashboard: My filters
Dashboard: My rules
Dashboard: Settings
Dashboard: Support
Dashboard: Trusted sites
Dashboard: Whitelist
Deploying uBlock Origin: configuration
Dynamic filtering: Benefits of blocking 3rd party iframe tags
Dynamic filtering: Benefits of blocking 3rd party script and iframe tags
Dynamic filtering: default deny
Dynamic filtering: default deny: useful rulesets
Dynamic filtering: Examples of usefulness of blocking 3rd party iframe tags
Dynamic filtering: precedence
Dynamic filtering: quick guide
Dynamic filtering: rule syntax
Dynamic filtering: to easily reduce privacy exposure
Dynamic filtering: Usefulness of blocking 1st party script tags
Dynamic filtering: Usefulness of blocking inline script tags
Firefox version: benchmarking memory footprint
Firefox version: benchmarking memory footprint (2015 03 07)
Maintainership transfer of uBlock: post mortem
Memory footprint: what happens inside uBlock after installation
Memory footprint: what happens inside µBlock after installation
Myth: uBlock consumes over 80MB
Myth: uBlock is just slightly less resource intensive than Adblock Plus
Myth: µBlock consumes over 80MB
Myth: µBlock is just slightly less resource intensive than Adblock Plus
Overview of uBlock's network filtering engine: details
Own memory usage: benchmarks over time
Quick guide: popup user interface
Tutorial: how to unbreak a site using the dynamic filtering pane
uBlock and others: Blocking ads, trackers, malwares
uBlock version 0.8.5: many changes
uBlock vs. ABP: efficiency compared
µBlock and others: Blocking ads, trackers, malwares
µBlock version 0.8.5: many changes
µBlock vs. ABP: efficiency compared

"
About "This other extension reports more stuff blocked!"
About "uBlock is inferior in capabilities as a result of being lighter on the browser"
About "uBlock is inferior in capabilities as a result of being lighter on the browser"...
About "Why uBlock Origin works so much better than Pi‑hole does?"
About this "your software" mindset
Debunking "uBlock Origin is less efficient than Adguard" claims
The "Report a filter issue" form

/
Easy mode + enhanced security/privacy

|
Who care about efficiency, I have 8 GB and|or a quad core CPU
Who cares about efficiency, I have 8 GB and|or a quad core CPU
Who cares about efficiency, I have 8 GB RAM and|or a quad core CPU

?
About "Why uBlock Origin works so much better than Pi-hole does?"
Can you trust uBlock Origin?
Can you trust uBlock?
Does uBlock block ads or just hide them?
Does uBlock Origin block ads or just hide them?
Doesn't uBlock Origin add overhead to page load?
Why don't you accept donations?

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/wiki

### Steps to Reproduce

Run git clone https://github.com/gorhill/uBlock.wiki.git

### Expected behavior

Cloning should finish.

### Actual behavior

Git clone does not copy any pages.

### uBlock Origin version

1.41.9rc3

### Browser name and version

Brave 1.36.122 Chromium: 99.0.4844.88

### Operating System and version

Windows 8.1

**Comment by gorhill** [comment]
You will have to file an issue with GitHub, we can't limit the wiki according to Windows's restrictions for file names, and we certainly can't re-title all the pages with the consequence of breaking all the links to these pages.

**Comment by gwarser** [comment]
Isn't Windows git (msys-git?) replacing these characters on-the-fly?
