### ISSUE TITLE
Firefox: uBO logger does not report all the scriptlets

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#2072]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

1. logger doesn't report following filters
```
vidbam.org##+js(abort-current-script, JSON.parse, break;case $.)
vidshar.org##+js(acis, JSON.parse, break;case $.)
```
when going here `https://4hdmovie.com/movies/valimai-2022-tamil/` in firefox stable

2.
iam not able to see `#@#` in logger to except the scriptlet filter ,this is how it looks in firefox 
![firefox_2obNjN4MEA](https://user-images.githubusercontent.com/20338483/161016216-293bad63-ca3a-454a-9c33-8f2acad4a7fd.png)

this is in opera browser 
![opera_wwZTfTqawz](https://user-images.githubusercontent.com/20338483/161016306-fdc38469-f2bd-4485-ab52-9c74442c20a5.png)

3.
❌ doesn't appear in filter logger content area in firefox
![firefox_XWH6TxoJNN](https://user-images.githubusercontent.com/20338483/161017636-f2063815-c174-4bc0-81d1-2f6be4b5a719.png)

opera looks like this 
![opera_csNjoHYWD4](https://user-images.githubusercontent.com/20338483/161017834-a6dacfab-f0d0-43f2-bb10-c6434674b5b8.png)

### A specific URL where the issue occurs

`https://4hdmovie.com/movies/valimai-2022-tamil/`

### Steps to Reproduce

Going `https://4hdmovie.com/movies/valimai-2022-tamil/` and observing logger for above mentioned steps in description

### Expected behavior

1. logger should report 
```
vidbam.org##+js(abort-current-script, JSON.parse, break;case $.)
vidshar.org##+js(acis, JSON.parse, break;case $.)
```

2. show `#@#` next to scriptlet filter when visualized and `X` in filter logger content area

these are all behaviours reported in chromium based ublock origin

### Actual behavior

Doesn't logged scriptlet filters and not shown `#@#` , `X`

### Configuration

uBlock Origin: 1.41.8
Firefox: 98
filterset (summary): 
  network: 81322
  cosmetic: 42192
  scriptlet: 16444
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31066-40, 40m
    ublock-badware: 3993-3, 40m
    ublock-privacy: 210-0, 40m
    ublock-abuse: 72-0, 40m
    ublock-unbreak: 1753-0, 40m
    easylist: 65075-589, 40m
    easyprivacy: 26738-577, 40m
    urlhaus-1: 9225-0, 40m
    plowe-0: 3690-2, 40m
    ublock-quick-fixes: 138-4, 40m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 861 ms (selfie)
  maxAssetCacheWait: 353 ms

**Comment by gorhill** [comment]
> logger doesn't report following filters

Because there are no iframes for either `vidbam.org` or `vidshar.org`. Scriptlets are injected in documents.

> iam not able to see `#@#` in logger to except the scriptlet filter

> modifiedHiddenSettings: [none]

[`filterAuthorMode`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#filterauthormode)

> doesn't appear in filter logger content area in firefox

Browser behavior -- Firefox does not render a `x` in its `input type="search"` element.

**Comment by ghajini** [comment]
> 
> Because there are no iframes for either `vidbam.org` or `vidshar.org`. Scriptlets are injected in documents.
> 
i don't understand this ,there are iframes for `vidshar.org/vidbam.org` 
![firefox_bYiNQ96NhS](https://user-images.githubusercontent.com/20338483/161055160-d3086cb8-6c2f-4c28-8e4d-3e1326a8c424.png)

**Comment by ghajini** [comment]
Going here `https://4hdmovie.com/movies/valimai-2022-tamil/`
click under **video sources**  `fast stream` & `fast stream2` ,logger report frame request 
![firefox_1YPDaj4vqn](https://user-images.githubusercontent.com/20338483/161057246-bc2c981b-47fa-41c7-9585-24ff2bf459a5.png)
but not scriptlet filter logging...

i think iam pretty much clearer

**Comment by gorhill** [comment]
> click under video sources `fast stream` & `fast stream2`

Nothing happens when I click those links -- using new Firefox profile with only uBO installed with default settings and up to date lists.

**Comment by mapx-** [comment]
> Nothing happens when I click those links -- using new Firefox profile with only uBO installed with default settings and up to date lists.

- `fast stream & fast stream2` are frozen using my european ip, thyen I tried a vpn us ip and are working
- using us ip fast stream  will directly open its embed stream (frame): `https://vidshar.org/embed-gwtmm2hrazuv.html`
- fast stream2 => `https://vidbam.org/embed-cltmyxvbt4hd.html`

 - even without running / play the stream:
 
chrome => **the filter is present in the logger**
![image](https://user-images.githubusercontent.com/10303732/161068224-7e7f5914-1cb9-4f35-a761-24d205bea1df.png)

firefox => **no such filter in the logger**

**Comment by gorhill** [comment]
I tried 2 US VPN and still can't reproduce and links are unresponsive. Might require Windows OS? I don't have this.

**Comment by mapx-** [comment]
It's working using a Vancouver ip too

**Comment by gorhill** [comment]
Scriptlets are injected in a different way in Firefox, declarative content script needs to be injected first in the frames, and when they execute, uBO's content script will ask the main process to inject the scriptlets. If declarative content script is not injected by Firefox, scriptlets won't be injected. In Chromium, uBO might report the scriptlet as injected, but it's not guaranteed it is happening.

I modified how scriptlet injection is reported in the logger in the next dev build: uBO will report scriptlet being injected **only** if it receives confirmation that the content script code injecting the scriptlets has been executed.

The links are also not functioning when using Chromium, so at this point I suspect the page's code depends on the OS, to be confirmed by someone else who can also test on linux.

**Comment by ghajini** [comment]
just an observation i can see `evoload.io##+js(abort-on-property-write, _pop)` in logger being reported on this link `https://4hdmovie.com/movies/hey-sinamika-2022-hindi-hd/`

but logger fails to report `vidbam.org##+js(abort-current-script, JSON.parse, break;case $.)`
`vidshar.org##+js(acis, JSON.parse, break;case $.)` 
here link `https://4hdmovie.com/movies/valimai-2022-tamil/`

hope iam not offtopic

**Comment by mapx-** [comment]
I installed ubuntu in hyper-v in windows, FF 75, uBO 1.42.1b0, canadian ip, I can get the same behaviour (scriptlet not reported for those 2 players above)

**Comment by ghajini** [comment]
@gwarser in case not received notifications

**Comment by ghajini** [comment]
another website where scriptlets not logged for iframes are

 `https://x.yesmovies.ws/attack-2021-hd-720p-tamil-movie-watch-online-tamilyogi-net/`

these scriptlet(s)
`vidshar.org##+js(abort-current-script, JSON.parse, break;case $.)`

**Comment by stephenhawk8054** [comment]
> another website where scriptlets not logged for iframes are
> 
> `https://x.yesmovies.ws/attack-2021-hd-720p-tamil-movie-watch-online-tamilyogi-net/`
> 
> these scriptlet(s)
> 
> ```
> vidshar.org##+js(acis, JSON.parse, break;case $.)
> vadbom.com##+js(acis, JSON.parse, break;case $.)
> ```

Yes, I can confirm with this site

<details><summary>Screenshot</summary>

![7](https://user-images.githubusercontent.com/66517106/161458726-f24a6701-59d5-45c9-86b2-815243b29b0e.png)

</details>

**Comment by gorhill** [comment]
Yes, I can reproduce this with `https://x.yesmovies.ws/attack-2021-hd-720p-tamil-movie-watch-online-tamilyogi-net/` -- no interaction needed. It's difficult to investigate but at first glance it appears uBO's content scripts are not injected in those two frames, maybe because they have `sandbox` attribute set on them. I would have to dig into bugzilla to find out if this is a known issues/normal behavior from Firefox's point of view. If that is the issue, then we will have to resort to HTML filtering if that is possible, otherwise if content scripts can't be injected, then it's not something I can fix in uBO. This requires more investigation though, as I said it's at first glance, it's not easy to investigate through the debugger, I need a custom version of uBO to confirm through `console.log` messages.

**Comment by gorhill** [comment]
I confirm that uBO's content scripts are not injected by Firefox, this is why the scriptlets are not injected as a consequence.

Top is Chroimum console, bottom is Firefox console:
![a](https://user-images.githubusercontent.com/585534/161580066-46fbe584-32f8-4d2b-930d-18b265f73b96.png)

**Comment by ghajini** [comment]
does this need to be reported to firefox or there's bugzilla issue about it?
@gwarser

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411641
