### ISSUE TITLE
Sentry.io gives a blank page because amplitude is blocked, even by disabling ublock origin

### ISSUE THREAD

**Issue by Nek-** [uBlockOrigin/uBlock-issues#2073]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [ ] uBO is the only extension
- [ ] using a new, unmodified browser profile

### Description

Hello,

I'm using sentry. They are using https://api.amplitude.com/ . The page is blank, even with ublock disabled for the page.

<img width="1440" alt="Capture d’écran 2022-03-31 à 12 31 41" src="https://user-images.githubusercontent.com/972456/161036410-c24d1ff4-11dd-4b82-87e8-81db3d7cddf2.png">

### A specific URL where the issue occurs

https://sentry.io/organizations/{your-organization}/issues/

### Steps to Reproduce

1. Go on sentry.io (logged in)
2. Blank page is here already

### Expected behavior

Nothing blocked if ublock is not activated.

### Actual behavior

https://api.amplitude.com/ blocked while ublock inactive

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 97893
  cosmetic: 51098
  scriptlet: 16540
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    FRA-0: 26798-25, 3d.3h.21m
    easylist: 64886-150, 3d.3h.20m
    easyprivacy: 26726-438, 3d.3h.19m
    plowe-0: 3687-817, 3d.3h.22m
    ublock-abuse: 72-1, 11d.20h.16m
    ublock-badware: 3953-93, 3d.3h.18m
    ublock-filters: 30448-231, 3d.3h.16m
    ublock-privacy: 200-2, 11d.19h.56m
    ublock-quick-fixes: 139-15, 18h.42m
    ublock-unbreak: 1741-41, 3d.3h.15m
    urlhaus-1: 8896-0, 18h.43m
filterset (user): [empty]
trustedset: 
  added: [array of 9 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5270 ms (selfie)
  maxAssetCacheWait: 1098 ms
```
</details>

**Comment by gorhill** [comment]
How did you confirm it's uBO causing this? Did you look at the logger to find out what uBO is blocking?

**Comment by Nek-** [comment]
Sentry seems to have an issue, it's not related to amplitude (but still, ublock cancel amplitude requests even being disabled on the current page).

**Comment by gorhill** [comment]
> ublock cancel amplitude requests even being disabled on the current page).

Please provide evidence it's the case, i.e. show logger output where it is shown that uBO is disabled on the page and network requests to amplitude are blocked.

**Comment by Nek-** [comment]
It seems I have something else blocking amplitude. I just tested in private browsing and I do not have the problem.
