### ISSUE TITLE
uBlock crashes latest Opera 85.0.4341.39 on Linux

### ISSUE THREAD

**Issue by stefan-i** [uBlockOrigin/uBlock-issues#2074]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Just today Opera was updated on MX Linux KDE to 85.0.4341.39 and immediately crashed after opening. I could trace the problem back to uBlock origin ad blocker. I am using the latest offical version 1.41.8 from the Opera extensions page. As soon as it gets enabled Opera crashes. I tried rebooting the computer and reinstalling uBlock via the Opera extensions page, but Opera crashes immediately when I click on "add to Opera". I tried this with two separate installations on two computers, both show the same crash when enabling or adding uBlock to Opera.

### A specific URL where the issue occurs

www.google.com

### Steps to Reproduce

Add uBlock to Opera via official Opera extensions page

### Expected behavior

Opera does not crash

### Actual behavior

Opera crashes immediately

### uBlock Origin version

1.41.8

### Browser name and version

Opera 85.0.4341.39

### Operating System and version

MX KDE 21, Kernel: 5.16.0-5mx-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1             Desktop: KDE Plasma 5.20.5 wm: kwin_x11 vt: 7 dm: SDDM             Distro: MX-21_KDE_x64 Wildflower October 20  2021 base: Debian GNU/Linux 11 (bullseye)

**Comment by gorhill** [comment]
uBO is HTML/CSS/JS, it's not supposed to crash the browser, and if the browser crashes, it's a browser issue, not an extension issue. Report to Opera devs.
