### ISSUE TITLE
:upward() does not work if the URL has a slash in it (path)

### ISSUE THREAD

**Issue by eladkarako** [uBlockOrigin/uBlock-issues#2080]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I've tried this DOM transcending goodness in-order to get rid of the garbage that is quora answers:  
`google.co.uk/search##a[href*="quora.com"]:upward(div.ZINbbc)`  
it didn't seems to work so I've simplified it to (for testing purposes):  
`google.com##a[href*="quora.com"]:upward(div.ZINbbc)`  
and it worked just fine.  
so I've assumed it is a bug.

here is good testing page (limits to `www.quora.com`)
https://www.google.co.uk/search?num=20&gbv=1&tbs=qdr%3Am&q=site%3Awww.quora.com+stuff&oq=&aqs=

note: if you test stuff, note that `google.com` has a different structure.

### A specific URL where the issue occurs

https://www.google.co.uk/search?num=20&gbv=1&tbs=qdr%3Am&q=site%3Awww.quora.com+stuff&oq=&aqs=

### Steps to Reproduce

1. add rule provided in the description (with `/search`).
2. browse provided URL.
3. note the `:upward` not working.
4. remove `/search` from rule
5. refresh.
6. note it works now.

### Expected behavior

allow URLs with paths.

### Actual behavior

URLs with paths will not work.

### uBlock Origin version

1.41.9b0

### Browser name and version

Chromium 99.0.4844.51 (https://github.com/Hibbiki/chromium-win64/releases/download/v99.0.4844.51-r961656/chrome.sync.7z)

### Operating System and version

Windows 10

**Comment by NoMeansNowastaken** [comment]
It only supports hostnames, not paths

**Comment by mapx-** [comment]
use `matches-path`
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-patharg

working on my side:
`google.co.uk##:matches-path(/search) a[href*="quora.com"]:upward([data-hveid])`

**Comment by eladkarako** [comment]
that's a good answer.  
the wiki page https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters  should probably include explicitly that 'hostname only thing' as well.

**Comment by gorhill** [comment]
That page is a subpage of <https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-extended-filtering>, where it is mentioned:

> Static extended filters are all of the form:
> 
> `[hostname(s)]##[expression]`
> `[hostname(s)]#@#[expression]`

**Comment by gorhill** [comment]
Actually I was expecting that in `google.co.uk/search##a`, `google.co.uk/search` would be highlighted as an error, but it's not. I need to fix this.

**Comment by eladkarako** [comment]
that CodeMirror syntax-checking feature is amazing,  
<details><summary><sub>(I wish there was status line with text of the reason though, <br/>the red background is slightly ambiguous <br/>and in any case the custom syntax-checking rule already walk through the reason programmatically)</sub></summary>

<img width="300" src="https://user-images.githubusercontent.com/415238/162236853-8269ec65-b8f4-4992-8d7c-2fab96ac7af5.png" />

</details>
