### ISSUE TITLE
Disable auto reload / auto refresh of some websites.

### ISSUE THREAD

**Issue by blap** [uBlockOrigin/uBlock-issues#2082]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Websites reload automatically sometimes when it is not desired by the user as; doing so can be highly disruptive. 
It is possible to disable auto-refresh on all the major browsers, but it is a hidden configuration and for all websites, not only for some.

### A specific URL where the issue occurs

https://www.correiobraziliense.com.br/

### Steps to Reproduce

Here a guide to do on various browsers, but it is for all pages:
https://www.maketecheasier.com/disable-web-page-auto-refresh-for-various-browsers/

### Expected behavior

The idea is to disable auto reload / auto refresh of only some websites.

### Actual behavior

You can not disable auto reload / auto refresh of some websites.

### uBlock Origin version

All

### Browser name and version

All

### Operating System and version

All

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Resources-Library#refresh-defuserjs-

**Comment by gwarser** [comment]
The correiobraziliense home page is reloading? I don't see it happen.

**Comment by mapx-** [comment]
me neither

**Comment by blap** [comment]
4 or 5 minutes here...

**Comment by gorhill** [comment]
Please do not open feature request before going through support for filtering issues.
