### ISSUE TITLE
cosmetic shortcoming

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uBlock-issues#2083]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

does not hide the filter despite unchecking it and pressing `-` /` + `
(e.g. with "Quick fixes" no such problem)
![Screenshot_2022-04-09-14-45-16](https://user-images.githubusercontent.com/70756447/162575447-3540b058-3545-40e8-9f8c-e192d931a4fa.png)

### A specific URL where the issue occurs

-

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBlock Origin version

1.42.4

### Browser name and version

fenix 99.1.1 (mobile firefox)

### Operating System and version

android

**Comment by gorhill** [comment]
AdGuard Mobile is a default list on mobile, default lists are not hidden because disabling them is not recommended, and this also acts as a way to identify default lists from optional ones.

**Comment by hirorpt** [comment]
@gorhill
> (e.g. with "Quick fixes" no such problem)

Maybe we should reopen https://github.com/uBlockOrigin/uBlock-issues/issues/2056? The fix seemed to revert due to https://github.com/uBlockOrigin/uBlock-issues/issues/2066

**Comment by gorhill** [comment]
> Maybe we should reopen <https://github.com/uBlockOrigin/uBlock-issues/issues/2056>?

There is no possible fix for this. This should no longer happens once you hard purge all caches with version of uBO 1.42.0+.
