### ISSUE TITLE
Adblock List for Finland cannot be obtained

### ISSUE THREAD

**Issue by smarek** [uBlockOrigin/uBlock-issues#2086]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Finnish blocklist from URL https://adb.juvander.net/Finland_adb.txt cannot be properly obtained, since the domain has more than 4 months expired SSL certificate, i've contacted juvander.net and i'm waiting for their response, but it should be known and decided, whether the SSL/TLS will be corrected and list can remain, or whether it should be deleted and not used anymore

I found in chrome xsession-errors log this snippet
```
[712825:712899:0412/092241.901254:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for adb.juvander.net failed:
----- Certificate i=0 (CN=www.juvander.fi,OU=Domain Control Validated) -----
ERROR: Time is after notAfter
```

Issue is not specific for url, it happens everywhere

Also seems like there are no filter rules on the URL, so it might be actually 

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues

### Steps to Reproduce

1. Install uBlock Origin 
2. Enable "Adblock List for Finland" in uBlock dashboard/options, tab Filter lists
3. Observe in error log when launching chrome from console, or in collected xsession-errors log, if you have it configured

### Expected behavior

List should be downloaded correctly

### Actual behavior

List is not downloaded or updated because of SSL/TLS verification error

### uBlock Origin version

1.42.4

### Browser name and version

Google Chrome, 102.0.4987.0 (Official Build) dev (64-bit) - should not matter

### Operating System and version

Debian Linux 11 Bullseye

**Comment by gorhill** [comment]
> Enable "Adblock List for Finland" in uBlock dashboard/options, tab Filter lists

Work fine here: <https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/Finland_adb.txt>.

I don't know where you got `https://adb.juvander.net/Finland_adb.txt`, that URL is not used anywhere in uBO.

**Comment by smarek** [comment]
Well, sorry about that, have it in section "Custom", completely missed me, means i added this list manually long time ago probably. Closing as invalid.
