### ISSUE TITLE
Blocked by the Firefox add-on store.

### ISSUE THREAD

**Issue by PencilNavigator** [uBlockOrigin/uBlock-issues#2088]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

as the title said, ublock origin is region-blocked in china. i've checked that firefox china (北京谋智网络技术有限公司) was sued by various Ads provider/Video Platform in china. causing it to be blocked.

### A specific URL where the issue occurs

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

### Steps to Reproduce

Steps to reproduce:
1.make sure the ip address is a china locally one.
2.download the china special edition from https://www.firefox.com.cn/
3.go to https://addons.mozilla.org/zh-CN/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
4. the page simply saids: The page you are trying to access is not available in your region. You can find what you're looking for in the extensions or topics below, or go to our community forum for help.

### Expected behavior

The add-on to be unblocked.

### Actual behavior

The add-on is blocked

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 99.0.1

### Operating System and version

Windows 10 21H2

**Comment by PencilNavigator** [comment]
![screenshot 22 4 14 1305](https://user-images.githubusercontent.com/85282140/163317299-93ee04d1-87c0-4b28-a69d-62f2bb9c88df.png)

**Comment by krystian3w** [comment]
I suppose bug in Great China Firewall.

On my localisation out of Asia 🌏 works:

**Comment by hirorpt** [comment]
This issue has already reported and probably there is nothing the uBO community can do.
https://old.reddit.com/r/uBlockOrigin/comments/tie7un/ublock_origin_is_blocked_by_mozilla_in_china/

**Comment by PencilNavigator** [comment]
> I suppose bug in Great China Firewall.
> 
> On my localisation (out of Asia 🌏) works:
> ![Screenshot_20220414-095818_Firefox](https://user-images.githubusercontent.com/35370833/163341034-f59c06d7-ae80-4764-ad5a-b5acb66d2edb.jpg) 	![Screenshot_20220414-095921_Firefox](https://user-images.githubusercontent.com/35370833/163341167-cd9259f3-9b1c-4fc7-b32c-176acbc6f80b.jpg)
> zh-CN** 	en* US
> 
> ** - I checked with Polish IP from ISP T-Mobile (oldie Era)
> 
> * - I suppose all English translation is same in web stories - so no respect difference grammar/words

not an GFW problem. it's mozllia blocking it due to its been sued multiple times by ads provider in china. according to my search.  mozllia has 7 cases related to ublock.

**Comment by krystian3w** [comment]
Daily someone may have publish 1+ scam content blocker based on uBo/AG/ABP engine - these also fastly add to Geo lock list (instead mark as spam and revert publish)?


Also enough is cite 1 line instead all text with malform table - now generated uneded job for mapx- (hide most uneded photos as links).

**Comment by gorhill** [comment]
> The add-on to be unblocked

I don't have that sort of power.

**Comment by fxbrit** [comment]
I've been told by [a Chinese user of LibreWolf](https://gitlab.com/librewolf-community/browser/source/-/issues/80#note_1156210871) that the Great China Firewall blocks Github from time to time, so they cannot install uBO in any way during these periods. would it be possible to set up some kind of mirror? he mentioned Gitlab (he asked if we could do it at LibreWolf's so I guess Gitlab is fine).

**Comment by rxliuli** [comment]
Oh, fuck Firefox indeed, can't use uBlock Origin in Japan either, still showing `The page you tried to access is not available in your region.`

<img width="1280" height="800" alt="Image" src="https://github.com/user-attachments/assets/e4b5f78f-f66c-4aa5-aa49-e1d81d6b8664" />

**Comment by stephenhawk8054** [comment]
@Yuki2718 Hmm... Can you access from JP?

**Comment by Yuki2718** [comment]
I can but don't have the issue

<img width="1454" height="937" alt="Image" src="https://github.com/user-attachments/assets/723e2097-3a00-4afb-a682-91998254c7eb" />

**Comment by uBlock-user** [comment]
@Yuki2718 The url he visited is the american one, not yours.

**Comment by rxliuli** [comment]
> [@Yuki2718](https://github.com/Yuki2718) The url he visited is the american one, not yours.

No problem, it seems Addons blocks certain Japanese VPN addresses. I can install it if I switch to a US connection. Also, is there transparent information about regional blocking that records which regions have blocked which extensions?

<img width="1280" height="800" alt="Image" src="https://github.com/user-attachments/assets/b11f3255-b6f1-4d2f-84a1-6055b4b41909" />

**Comment by krystian3w** [comment]
I doubt this is public information.

It would be possible to check whether this final IP is shared with China and Mozilla simply used too weak a detection of China (unless the history for this IP has been lost from public databases).

**Comment by Yuki2718** [comment]
> is there transparent information about regional blocking that records which regions have blocked which extensions?

No idea

**Comment by asystech-chen** [comment]
I have found the root of the problem. During Mozzhì's agency of Firefox in China, they were sued by advertisers for unfair competition (providing ad-blocking plugins), and Mozzhì ultimately lost the case. The Mozilla add-on added geolocation locking for users with Chinese IPs.

https://bgme.me/@bgme/107986773834355287
