### ISSUE TITLE
uBO stops video playback in Opera

### ISSUE THREAD

**Issue by Yakinikuu** [uBlockOrigin/uBlock-issues#2089]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Video playback on any website stops after 1-3 minutes when uBO is enabled. It only happens for the first playback on the site in the web browsers sessions. It also happens for embedded videos on sites like online newspapers etc. I have tried to reinstall uBO, clean reinstall Opera etc but it happens every time for the first playback on the site regardless. This does not happen in Chrome so its related to uBO and Opera. It started around 4 weeks ago and was working perfectly fine before that. I have tried every single video site I know of to try to isolate the issues but it happens everywhere. I have also tried in both normal mode and incognito mode with no difference. 
When it happens it works again after clicking on the play button and then it will work with no more bug on that site until you close the browser. Changing video works fin as it only happens on the first video playback for each site. 

### A specific URL where the issue occurs

www.youtube.com

### Steps to Reproduce

1. open browser
2. go to youtube or any site with a video
3. play the video (should be longer than 3 min)
4. video should stop after 1-3 minutes

### Expected behavior

Video not to stop after 1-3 min for every site with a video after opening the browser

### Actual behavior

video stops after 1-3 minute for every site after opening the browser the first time.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 99
filterset (summary): 
  network: 80421
  cosmetic: 42388
  scriptlet: 16448
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 65818-51, 15m
    easyprivacy: 26783-121, 3m
    plowe-0: 3687-808, 13m
    ublock-abuse: 74-0, 10m
    ublock-badware: 4052-93, 8m
    ublock-filters: 30477-98, 7m
    ublock-privacy: 209-2, 7m
    ublock-quick-fixes: 151-0, 7m
    ublock-unbreak: 1757-42, 7m
    urlhaus-1: 7619-0, 7m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 201 ms (selfie)
  maxAssetCacheWait: 74 ms
```
</details>

**Comment by gorhill** [comment]
Content blockers have issues in Chromium-based browsers at launch. See if checking the setting _"Suspend network activity until all filter lists are loaded"_ in _"Filter lists"_ pane helps.

**Comment by Yakinikuu** [comment]
Tested with youtube and unfortunately it didnt work. :( Still stops within the 3 minute mark. 

btw this isnt tied to launch of the browser. Its tied to whether its the first time in this browser session playing a video on that streaming service for the first time after opening the browser. Meaning if I just browse around on youtube without clicking play on any video for 2 hours before I click play on a video, it will stop the first video I click play on as it is the first video I started to play in that browser session on that site. Note, just using youtube as example. happens on every streaming provider.

**Comment by gorhill** [comment]
I cant reproduce such issue, someone else who can rrproduce will have to investigate cause and solution.

**Comment by Yakinikuu** [comment]
I did a test on a second computer to see if its isolated to just one computer and its happening on that computer as well. 
I have everything on default in uBO and in Opera I have only disabled their adblock. re-enabling the built in adblock in Opera doesnt change anything.
I'm running newest version of Opera: 85.0.4341.60 and manually updated uBO filters yesterday on both computers. Older version of Opera may not have this bug as this started to happen around 4 weeks ago which may have been the same time as an Opera update.

**Comment by gwarser** [comment]
Win10? Does it matter if it plays on foreground or background?

**Comment by Yakinikuu** [comment]
Yes, windows 10. Happens on background, foreground, minimized, pop out mini player etc.
Have also had this behavior confirmed on a third computer (on another network and user) now running win10 and the same Opera version. 
I'm starting to think its something with Opera, html5 player and uBO since it happens on every video regardless of where its hosted as long as it is the first playback on the site having the video.

**Comment by gwarser** [comment]
I tried in Linux KDE and Win10 inside VM, and it works fine.

**Comment by Yakinikuu** [comment]
I dont know why it works for you guys. I have already asked 4 others to install Opera + uBO and play any video on youtube. they all say playback stopped between 2 and 3 minutes in. Did you guys let the video play for at least 3 minutes?
I will try a different adblock to see if its just when uBO is running.

**Comment by DwarfFighterCleric** [comment]
This started happening here around 2 weeks ago (around August 20th)  
But behavior is slightly different:  
No youtube video will ever start playback until I disable uBlock and refresh the page. Then, I can enable uBlock again and refresh the page in order for youtube to work normally. Have to repeat the procedure for every new page reload.
