### ISSUE TITLE
Doesn't work on android firefox 99.2.0

### ISSUE THREAD

**Issue by vantu5z** [uBlockOrigin/uBlock-issues#2091]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Adds is not blocked.
If try to open ublock settings it shows only tabs without content.

### A specific URL where the issue occurs

any

### Steps to Reproduce

Open sites with adds.
Open ublock settings.

### Expected behavior

Block adds and show settings.

### Actual behavior

Doesn't block adds and doesn't show settings.

### uBlock Origin version

1.42.4

### Browser name and version

firefox 99.2.0

### Operating System and version

android 11

**Comment by gwarser** [comment]
Likely broken installation or storage. Try reinstalling.

**Comment by vantu5z** [comment]
Reinstall, also reboot phone and have no effect.

**Comment by vantu5z** [comment]
Try to reinstall firefox and can't run it now :(

**Comment by gorhill** [comment]
Closing as invalid, your issue seems to be beyond uBO -- there are no reports of uBO being broken that way in Firefox for Android.
