### ISSUE TITLE
Configure uMatrix by default 1st-party YES, everybody else NO

### ISSUE THREAD

**Issue by metadings** [uBlockOrigin/uBlock-issues#2093]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

HEY Raymond Gorhill, YOU are one of my BEST HIDDEN FRIENDS! 👍💪👻

1. you have archived both https://github.com/uBlockOrigin/uMatrix-issues/issues AND https://github.com/gorhill/uMatrix/issues/ so I can't write an issue there

2. Configure uMatrix by default 1st-party YES, everybody else NO, in particular no cookies and no frames: like

```
noscript-spoof: * true
referrer-spoof: * true

* * * block
* * cookie block
* * frame block
* 1st-party * allow
* 1st-party cookie allow
* 1st-party frame allow
```

Look, I've just allowed then

```
* ajax.aspnetcdn.com script allow
* ajax.googleapis.com script allow
* bootstrapcdn.com * allow
* gravatar.com * allow
* imgur.com * allow
* jquery.com script allow
* jsdelivr.net * allow
* jwpcdn.com * allow
* jwplayer.com * allow
* jwpsrv.com * allow
* openstreetmap.org * allow
* openstreetmap.org cookie allow
* sstatic.net * allow
* sstatic.net cookie allow
* stackexchange.com * allow
* stackexchange.com cookie allow
* stackoverflow.com * allow
* wp.com * allow
* yimg.com * allow
* ytimg.com * allow 
```

And my Internet looks quite good! I am just block'ing things like

```
spiegel.de 1st-party script block
faz.net 1st-party xhr block
```

3. Takes 2 minutes, and is burning for up to 6 hours: Use the burning hairs of a Great Stinging Nettle, for an innate immune response, as this is a possible free-to-go #Analog #AntiVirus-#disinfection

### A specific URL where the issue occurs

https://www.spiegel.de/schlagzeilen/

### Steps to Reproduce

TRY THIS

### Expected behavior

NO cookies, NO frames everywhere

### Actual behavior

I don't know anymore

### uBlock Origin version

42

### Browser name and version

Mozilla Firefox 98

### Operating System and version

debian ubuntu Linux Mint 20.n

**Comment by metadings** [comment]
Hey what's wrong? I just wanted to say uMatrix is AWESOME +1 without 3rd-parties, cookies and frames.

**Comment by gorhill** [comment]
I appreciate that you like it, but here is for issues with uBO, so your post can't be closed any other way than as _invalid_, meaning it's not something to fix in uBO.

**Comment by metadings** [comment]
Look, GitHub says "This repository has been archived by the owner. It is now read-only. " so I can't write a message, there's no "New Issue" button.
