### ISSUE TITLE
uBO stops working on a youtube tab that got spawned on a new chrome instance

### ISSUE THREAD

**Issue by pc00per** [uBlockOrigin/uBlock-issues#2095]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I donno if this issue is specific to chromium based or on firefox browsers too. But it's been happening on my chromium browser with the startup setting "Continue where you left off" enabled.
When I close the browser completely with a youtube video running, on the next chromium instance, the same youtube video tab spawns, but with an intro rolled ad. 
But when I refresh the same tab, uBO starts kickin & ads stop.

### A specific URL where the issue occurs

https://youtu.be/LXb3EKWsInQ

### Steps to Reproduce

1. Use these settings > Startup > Continue where you left off
2. Run a youtube video on a tab
3. Close the browser with that running youtube tab
4. Reopen chromium, which should spawn the youtube video which was closed before

### Expected behavior

uBO should work on youtube even on a reopened youtube tab

### Actual behavior

uBO doesn't work on the reopened youtube video & we instantly see an intro rolled ad.

### uBlock Origin version

1.42.4

### Browser name and version

Chromium 100.0.4896.127

### Operating System and version

Arch Linux 5.17.3-arch1-1

**Comment by gorhill** [comment]
Known issue with Chromium-based browsers: <https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch>.

**Comment by pc00per** [comment]
Okay. I didn't found that wiki page so didn't knew about chromium browser launch issue.
