### ISSUE TITLE
Experimental procedural cosmetic operator `:others()` prevents Firefox Screenshots

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#2099]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Cosmetic filters using`:others()` introduced by https://github.com/gorhill/uBlock/commit/152120bd9ec7a2ccea907e015fb195484ef7bc8e crafted without the countermeasures interfere with Firefox Screenshots.
It may be by design, and the workaround is easy for the filter authors. However, Firefox Screenshots is a built-in add-on enabled by default, so it might be more user-friendly to handle Firefox Screenshots iframes by uBlock Origin itself in advance.

### A specific URL where the issue occurs

`https://www.nature.com/articles/d41586-022-00567-9`

### Steps to Reproduce

1. Add `nature.com##:matches-path(/^/articles//) :is(.c-breadcrumbs,.c-article-main-column):others()` to My filters
2. Open `https://www.nature.com/articles/d41586-022-00567-9`
3. Right-click and select Take Screenshot

### Expected behavior

Firefox Screenshot starts.

### Actual behavior

Nothing happens.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.5b2
Firefox: 99
filterset (summary): 
  network: 80946
  cosmetic: 42180
  scriptlet: 16440
  html: 631
listset (total-discarded, last updated): 
  default: 
    user-filters: 1-0, never
    ublock-filters: 31060-40, never
    ublock-badware: 3993-3, never
    ublock-privacy: 210-0, never
    ublock-abuse: 72-0, never
    ublock-unbreak: 1753-0, never
    ublock-quick-fixes: 138-4, never
    easylist: 65018-585, never
    easyprivacy: 26734-577, never
    urlhaus-1: 8896-0, never
    plowe-0: 3690-2, never
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1179 ms
  maxAssetCacheWait: 129 ms
```
</details>

**Comment by hirorpt** [comment]
There is possibly related a Mozilla Bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1696573, but according to https://bugzilla.mozilla.org/show_bug.cgi?id=1763548#c4
> That is making progress but we don't have any roadmap for shipping it and deprecating the extension yet.

**Comment by krystian3w** [comment]
You forgot about selection and preview iframes.

Also I don't recommend repair this by `:style()` - Firefox uses JavaScript to change display between 3 frames.

**Comment by hirorpt** [comment]
> You forgot about selection and preview iframes.

Thanks.

> Also I don't recommend repair this by `:style()`

My intended workaround is the following filter.
`nature.com##:matches-path(/^/articles//) :is(.c-breadcrumbs,.c-article-main-column,iframe[id^="firefox-screenshots-"]):others()`

**Comment by gorhill** [comment]
The only way to "fix" this is by removing the operator. Is this what people want?

**Comment by hirorpt** [comment]
>  Is this what people want?

At least I don't want that since I use it on Twitter.
This issue was intended to ask if some sort of workaround could be incorporated into uBlock Origin itself.

**Comment by gorhill** [comment]
> some sort of workaround could be incorporated into uBlock Origin itself

Not possible, the DOM is shared by all: Firefox's own tools, other extensions, the site itself. It's just not possible for uBO to make hard-coded guesses about what should not be removed based only on DOM information. In the current case, adding `iframe` to the list of DOM nodes to not hide works:

    nature.com##:matches-path(/^/articles//) :is(.c-breadcrumbs,.c-article-main-column,iframe[id^="firefox-screenshots-"],iframe):others()

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/ExtendedCss/issues/164
