### ISSUE TITLE
Insufficient escaping in patchScriptlet if streamScriptInjectFilters is enabled

### ISSUE THREAD

**Issue by thejh** [uBlockOrigin/uBlock-issues#21]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In modern Firefox, when the hidden setting `streamScriptInjectFilters` is enabled (currently defaults to off), the following filter will cause JavaScript code controlled by the filter author to be executed in the context of `https://www.wikipedia.org/`:

```
www.wikipedia.org##script:inject(set-constant.js,</script><img src=x onerror=eval(atob(`YWxlcnQoImNvZGUgZXhlY3V0aW9uIG9uICIrbG9jYXRpb24p`))>)
```

The problem is that `patchScriptlet` only escapes quotes and backslashes, but the stream injection mechanism inserts the generated JS code as an inline script, where `</script>` inside a string can terminate the script. It probably makes sense to add `/` to `reEscapeScriptArg` to fix this.

### A specific URL where the issue occurs

https://www.wikipedia.org/

### Steps to Reproduce

1. Open the "My filters" tab of the uBlock settings.
2. Add the following line:
```
www.wikipedia.org##script:inject(set-constant.js,</script><img src=x onerror=eval(atob(`YWxlcnQoImNvZGUgZXhlY3V0aW9uIG9uICIrbG9jYXRpb24p`))>)
```
3. Press "Apply changes"
4. Navigate to https://www.wikipedia.org/

### Expected behavior:

uBlock Origin should escape the string to ensure that the provider of a filter list can't execute arbitrary JavaScript in the context of any website.

### Actual behavior:

An alert window appears with "code execution on https://www.wikipedia.org/".

### Your environment

* uBlock Origin version: 1.16.0
* Browser Name and version: Firefox 59.0.2
* Operating System and version: Debian Linux

**Comment by gorhill** [comment]
Thanks for finding/reporting this.

I removed entirely the ability to inject scriptlets through response data filtering.

**Comment by sebast889** [comment]
Will the ability to inject scriptlets through response data filtering come back in the future?

**Comment by gorhill** [comment]
Only if really, really needed (as in no other solution to a concrete issue). Currently it was disabled by default because of other issues.

**Comment by sebast889** [comment]
Wish there will be a way in future to have that ability and not have it cause any major problems. It was a good feature to guarantee scriptlets didn't suffer from race conditions.

**Comment by gorhill** [comment]
A possible solution for the race condition problem is <https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts>. I need to investigate more in details that potential solution. For example, finding out how many distinct content scripts are derived from typically enabled filter lists to understand the overhead. Also, finding out if registering lazily is possible. Etc.
