### ISSUE TITLE
Use +/- in the popup to indicate whether 3-p frames were blocked

### ISSUE THREAD

**Issue by FatOrangutan** [uBlockOrigin/uBlock-issues#210]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The firewall section of the popup currently uses [`+` and `-`](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) to gives users a rough idea of how many requests were blocked/allowed. This makes it easy to create new rules.
I recently started using `* * 3p-frame block` but have found it a bit more time-consuming to unbreak websites because the popup doesn't tell me if any frames were blocked. The full logger needs to be opened and the page reloaded to determine if any frames were blocked.

### A specific URL where the issue occurs

Any url with an iframe would do, such as this one: https://patrickhlauke.github.io/recaptcha/.

### Steps to Reproduce

1. Add `* * 3p-frame block` 
2. Visit page with an iframe
3. Try to use popup's firewall to determine if frame was allowed/blocked

### Expected behavior:
Use +/- in the `3rd-party frames` row to give a quick overview.

### Actual behavior:
No +/- in the `3rd-party frames` row.

### Your environment

* uBlock Origin version: 1.16.21b4
* Browser Name and version: Nightly
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Are you posting this as a suggestion ?

**Comment by FatOrangutan** [comment]
Yes.

**Comment by joey04** [comment]
This suggestion is not valid for how the firewall panel has always worked. The first 7 rows -- `all` to 3rd-party frames -- are indicators of the dynamic blocking rules in effect. Only the following rows for each domain has the +/- counts.

**Comment by joey04** [comment]
Thought about this a bit more today, and if this suggestion were to be added it should be a new Advanced setting to enable it (default off).

If enabled, it should add +/- counts to all 5 request type rules: image, inline-script, 1p-script, 3p-script, and 3p-frame.  It would be silly to just show 3p-frame count.

But I still don't think it's a good idea to add this at all. Advanced users _need_ to learn how to use the Logger effectively. It's an essential aspect of a default-deny rule strategy.

**Comment by gorhill** [comment]
I meant to have this originally. The only reason I did not implement it was to avoid overhead and making the code more complicated (because of <https://github.com/gorhill/uBlock/issues/2053>).
