### ISSUE TITLE
[feature request] '@media print{ .... }' in ':style( )'

### ISSUE THREAD

**Issue by eladkarako** [uBlockOrigin/uBlock-issues#2100]
<details><summary>Prerequisites</summary>

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

</details>

### Description

I'm trying to limit CSS-injection,  
so it would only be injected <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@media#print">in a specific case</a>.

this <sub>(w/ or w/o wrapping in various `"` or `'`)</sub>  
does not seems to work for me:

```css
github.com##pre:style(@media print{white-space:pre-line !important;})
```

<details><summary>reasoning</summary>

trying to utilize uBlock CSS injection to help me print a PDF  
of a page that has a wider than screen textual content,  
in a container.

<img id="reasoning" name="reasoning" src="https://user-images.githubusercontent.com/415238/166079628-f04805fd-2e36-4b56-87e6-b4a6257ca565.gif"/>  

if the website does not handle content specifically it will be printed "as is",  
in this case cutting the text.  

<img src="https://user-images.githubusercontent.com/415238/166079672-6b07a49b-aee9-402a-b660-8e9dca5c96ba.png"/>

raw injecting something like:  

```css
@media print{
  pre {
    white-space:pre-line !important;
  }
}
```

would be sufficient to work around this,  
but I'm not sure if the `:style()` is even capable of that  
(selectors are in the `@media print` code-block).

</details>

### A specific URL where the issue occurs

https://gist.github.com/eladkarako/6910526bf5d4986c7aa27ed97cdedb64#file-make-an-apk-offline-using-apktool-md

### Steps to Reproduce

testing page provided.
trying to apply `@media print` in various ways.

### Expected behavior

using `@media print{}` (a.k.a. <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule">at-rule</a>, or media queries).  

workaround solutions might be a "raw stylesheet injection mode",  
as "as-is" text, or even a BASE64 encoded content (probably easier to extract from the rule due to lack of `{` and `'` and other "regexp pars!ng he11"..).

edit:  
found an <a href="https://old.reddit.com/r/uBlockOrigin/comments/inu2in/need_help_setting_up_a_filter_for_media_query/">old thread</a>.

<details><summary>uB version</summary>

### Actual behavior

``

### uBlock Origin version

1.41.9b0

### Browser name and version

chromium 101

### Operating System and version

w10

</details>

**Comment by gorhill** [comment]
You could just use [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne), what you are asking for is its primary purpose.

**Comment by eladkarako** [comment]
> You could just use Stylus

yep,  
although I've considered (the excellent) uBlock0 as a one stop shop for everything.  

thought a raw injection (workaround) would be super useful considering media queries v4 and recent features in CSS 

(including ability to control dark mode, depending on OS state, but also pretty "old stuff" such as overriding rules that will be applied for screen-size or orientation), 

current injection only apply to the "normal state",  
and vendors can pretty easily add banners/ads/watermarks in "other states" depending on media-queries,  
that uB0 has no control on..  
(brrr.... hopefully no one will read this and figure it out..).

<details><summary>;]</summary>
stylus (and userscript) are useful, yes, but that's "another thing" to maintain,  
and scraps of code that are not synced and easy to loose (at least in my case..).  
I would rather write a slim web-extension just for that ;)
</details>

anyway you can always mark this as "work fix" and close it

**Comment by Lairub** [comment]
AdGuard sometimes use media to fix problematic layout after hide e.g. ads - maybe the most possible rewrite to scriptlet, but AdGuard decided use CSS.

Also to compatibility with AdGuard I recommended outside on `:style`:

```css
github.com##@media print{pre:style(white-space:pre-line !important;)}
```

Then AdGuard translate to:

`github.com#$#@media print { pre { white-space:pre-line !important; }}`

**Without update in own repositories** like https://github.com/AdguardTeam/tsurlfilter and https://github.com/AdguardTeam/FiltersCompiler


---

For uBo latest issue where media will be better than if conditions (uBo can't detect Tablets as different hardware than smartphone, media on PC fix issue if window will be resized to smaller (e.g half on desktop work place).


https://github.com/uBlockOrigin/uAssets/issues/12688#issuecomment-1095581092

---

> hopefully no one will read this and figure it out

uBo will inject css on print pages as long use `tabs.insertCSS()` api. So page have troubles to remove restyleet elements.

A few pages use parameter "?print" or catalog "/print", then help use `:matches-path`.
Rare possible found added class/ID to dom tree where help use `##:is(.print, #print) pre:style(...)`.

**Comment by eladkarako** [comment]
Lairub I didn't got what you are describing here, a theory or an actual working solution?

**Comment by eladkarako** [comment]
I'm not sure if it is worth mentioning it or not,  
but Chrome totally ignores `@media print{ }` anyway!  

`(┛ಠ_ಠ)┛彡┻━┻`  

it does however respect (to some level)
`<link rel="stylesheet" type="text/css" media="print"             href="just_for_printing_but_no_actual_media_print_block_being_used_here.css" />`

<code title="putting table back">┳━┳ ヽ(ಠل͜ಠ)ﾉ</code>  

so workarounds would need to inject a 'non in-line' style.

✺ funky! ✺

anyway I'm closing this..

**Comment by pftreply** [comment]
In the past you asked my https://github.com/uBlockOrigin/uBlock-issues/issues/2100#issuecomment-1114688020  about "opinion" is pasted in correct place - yes pasted to correct issue.

Additionally, you need to rethink creating unanswered questions due to user banning - the bug reporting system has additional filtering for fresh accounts, so we can't write back from a second account which you would probably also block until 24 hours after publishing an unwanted comment.

---

The first and thrid remark that AdGuard uses media form CSS was to support that it is occasionally helpful if someone has not mastered e.g. scripts or is probably lighter than scripts as **ameshkov** sometimes confirms.

The secon remark to use an AdGuard compliant syntax is rather purely for compatibility with older applications. Once your build is added, those willing will probably ask AdGuard to run a translator, or this problem will be considered irrelevant for about 13 filters (On AdGuard Team side).

The fourth remark about the possibility of adverts appearing on prints was that you should document the problem privately:  https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=security_report.yml for gorhill to give an opinion within 90 days as to whether it can be fixed and that large corporations cannot easily use it by reading a github submission. IMO uBo no have problem, no allow print ads with enabled filtering content (ads, tracking, annoyances).

Last remark with workaround possible mark as offtopic due too many pages don't use `?print` or `/print` in URL-s.

---

> but Chrome totally ignores `@media print{ }` anyway!

Empty CSS rule can be ignored, worse if filled also: `@media print{pre{white-space:pre-line !important;}}`

**Comment by eladkarako** [comment]
please mark https://github.com/uBlockOrigin/uBlock-issues/issues/2100#issuecomment-1128128769 as an unrelated/incoherent gibberish.

**Comment by eladkarako** [comment]
newly added `:matches-media(print)` does not seems to be working for `print`..

<hr/>

```css
@media print{
  pre {
    white-space:pre-line !important;
  }
}
```

`github.com##pre:matches-media(print):style(white-space:pre-line !important;)`

(also tried `github.com##pre,textarea,[contentEditable]:matches-media(print):style(white-space:pre-line !important; word-break:normal !important; -webkit-line-break:normal !important; line-break:normal !important; font-family:monospace !important;)` )

both firefox and chromium.  

https://github.com/gorhill/uBlock/releases/tag/1.43.1rc0  
https://github.com/gorhill/uBlock/commit/40c315a107257f5b1ac0c7fc92377934b23f6ed6

**Comment by uBlock-user** [comment]
> pre

Does "pre" exist on GitHub ? uBO can only manipulate styles of elements that exist, it cannot create new elements.

**Comment by gorhill** [comment]
The following works:

    github.com##pre:matches-media(print):style(color: red !important)

Which means you haven't provided the proper CSS properties for the result you want. Here is not the place for this sort of support.
