### ISSUE TITLE
Contributing To Documentation?

### ISSUE THREAD

**Issue by ElectronicsArchiver** [uBlockOrigin/uBlock-issues#2101]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Just wanted to do some generic documentation cleanup,
which I can't? Blocked PRs and no documentation issue
template?

### What I Changed
- Converted raw links into link references

See [my repo].

[my repo]: https://github.com/ElectronicsArchiver/uBlock

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock

### Steps to Reproduce

> Fix a bunch of typos in gorhill/uBlock

Randomly stumble upon someone with a similar experience.

> Attempt to contribute the fix by making a pull request when you've not contributed to this project before.

Cite that persons steps.

### Expected behavior

Contribute refactorings to upstream,
improve the situation in the future.

### Actual behavior

- Forked the repo
- Worked on local clone
- Tried opening a PR
- Got denied

### uBlock Origin version

1.42.4

### Browser name and version

101.0.4951.41 (Official Build, ungoogled-chromium) (64-bit)

### Operating System and version

Kubuntu 22.04

**Comment by u-RraaLL** [comment]
You can't make a PR until you've at least contributes once. You should make a patch instead and ask for it to be added.

As for the documentation issue template - you can just use Discussions instead. Issues is meant for actual extension issues.

**Comment by ElectronicsArchiver** [comment]
> You can't make a PR until you've at least contributes once.
I know ^^

> You should make a patch instead and ask for it to be added.
Where to ask, where to place the patch

> As for the documentation issue template - you can just use Discussions instead. Issues is meant for actual extension issues.
Maybe someone should like write that somewhere easy to find..

**Comment by u-RraaLL** [comment]
> Where to ask, where to place the patch

Now that this issue exists, you can simply link the patch here.

>  Maybe someone should like write that somewhere easy to find..

I agree. https://github.com/uBlockOrigin/uBlock-issues/issues/1897#issuecomment-1000524846

**Comment by ElectronicsArchiver** [comment]
https://raw.githubusercontent.com/ElectronicsArchiver/uBlock/PatchFile/Raw-Links-Link-References.patch

**Comment by gorhill** [comment]
This needs fixing.

> uBlock Origin's [own filter lists](https://github.com/uBlockOrigin/uAssets/tree/master/filters).

has become:

> uBlock Origin's [own filter lists][UBlock Filters].

Also I spotted a stray `)` in the "Firefox / Firefox for Android" section.

**Comment by ElectronicsArchiver** [comment]
@gorhill 
https://raw.githubusercontent.com/ElectronicsArchiver/uBlock/PatchFile/0001-Raw-Links-Link-References.patch

**Comment by gorhill** [comment]
I can just cherry-pick from your repo. Can you squash both commits into one?

**Comment by ElectronicsArchiver** [comment]
Already did~
https://github.com/ElectronicsArchiver/uBlock

**Comment by gorhill** [comment]
Thanks, imported: <https://github.com/gorhill/uBlock/commit/deb5fea0babca8e357dff3bc2347290d79614309>
