### ISSUE TITLE
Logger is not logging every blocked element on `reddit.com`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#2103]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

See https://github.com/uBlockOrigin/uAssets/issues/13072#issuecomment-1117113181 

The point is: on reddit.com the logger doesn't log every blocked element 
<details><summary>Screenshot</summary> 

![image](https://user-images.githubusercontent.com/81161435/166658519-2f119cec-5abd-4d85-8420-685d27eea613.png)

</details>

It only log the element from other domains (3p). 
But if I turn on the `DOM-inspector` tada! you see there are elements blocked 
<details><summary>Screenshot</summary> 

![image](https://user-images.githubusercontent.com/81161435/166659000-c01b336c-a97e-4d21-8103-63705d8a79b5.png)

</details>

### A specific URL where the issue occurs

`reddit.com`

### Steps to Reproduce

1. Open the uBlock Logger
2. Go to the homepage of reddit.com - just `https://www.reddit.com/`
3. Scroll down the page for a while on reddit; *don't click on posts; just scroll slowly down.*
4. Go back to the logger and notice that from the block element only `###ad-overlay` from `streamable.com` is blocked. 
5. Switch in the logger to `DOM-inspector` 
6. See that multiple elements are blocked *and not only the one stated in point 3*.

### Expected behavior

The Logger has to lock **all** blocked elements on the page.

### Actual behavior

The Logger only logs blocked elements from an in the webpage inserted third party element, 
but not the 1p elements.

### uBlock Origin version

1.42.2

### Browser name and version

MS Edge v101

### Operating System and version

Windows 10, 21H2

**Comment by stephenhawk8054** [comment]
Not sure if I understand correctly or not, but I can see the first party logs as normal.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/166667724-8791f23f-b05e-47c0-80ea-2366027b0838.png)

</details>

**Comment by JohnyP36** [comment]
I double checked it. It seems there occurred an one time error, because now the Logger logs everything. 

However, it's strange that this happens.
