### ISSUE TITLE
Blocking external fonts also blocks "local" fonts

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [uBlockOrigin/uBlock-issues#2104]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I activated "blocking external fonts" (Externe Schriftarten blockieren).

But it seems to me that "local" fonts (from the same server) are blocked also.

Please try https://refhunter.org. That side load its own fonts from its own server as you can see in the logs.

![image](https://user-images.githubusercontent.com/11861496/167163850-9393c7c3-4498-46b1-a99b-c5125c989b0a.png)

### A specific URL where the issue occurs

https://refhunter.org

### Steps to Reproduce

1. see description

### Expected behavior

Fonts from the sites server should be loaded.

### Actual behavior

They are not loaded.

### uBlock Origin version

current release

### Browser name and version

Edge & Firefox

### Operating System and version

Debian 10, Debian 11, Windows 10

**Comment by gorhill** [comment]
`https://refhunter.org/` is not "local", so fonts downloaded from it are remote, hence properly filtered out when enabling the no-remote-fonts switch.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
But you got my point?

Maybe not local but not foreign. So what is the security Issue here when a server loads fonts from itself?

When the fonts are loaded from google it is a problem.

**Comment by gorhill** [comment]
Just block 3rd-party resources if you want to prevent these from being pulled on any given site.
