### ISSUE TITLE
Crunchyroll video stuck on loading loop

### ISSUE THREAD

**Issue by xDestructionPvP** [uBlockOrigin/uBlock-issues#2108]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

While uBO is active, crunchyroll videos wont play. They'll be stuck with the loading circle indefinetly and once the extension is turned off, the video will begin to play after the site is refreshed.

### A specific URL where the issue occurs

cunchyroll.com

### Steps to Reproduce

1. Activate uBO
2.Try to play a crunyroll video
3.Indefinite loading loop
4.Turn off uBO and use the built in refresh button to refresh page
5.Video starts playing
6.Turn uBO back on and error occurs again

### Expected behavior

The video plays without any issue

### Actual behavior

Crunchyroll is stuck on a loading loop.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 81728
  cosmetic: 42937
  scriptlet: 16784
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 66510-51, 23h.56m
    easyprivacy: 26944-121, 23h.55m
    plowe-0: 3676-805, 7d.23h.39m
    ublock-abuse: 75-0, 10d.22h.1m
    ublock-badware: 4154-92, 23h.54m
    ublock-filters: 30961-91, 23h.53m
    ublock-privacy: 213-3, 10d.22h
    ublock-quick-fixes: 214-0, 23h.51m
    ublock-unbreak: 1780-40, 23h.52m
    urlhaus-1: 8281-0, 23h.50m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 302 ms (selfie)
  maxAssetCacheWait: 144 ms
```
</details>

**Comment by gorhill** [comment]
Unable to reproduce, and anyways, filter issues are to be handled at uAssets.
