### ISSUE TITLE
when uBlock is enabled a bunch of spam links appeared in my css

### ISSUE THREAD

**Issue by BlackRob** [uBlockOrigin/uBlock-issues#2111]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I don't know if this is a uBlock issue or not, but it goes away when uBlock is disabled, and it seems to be spam links injected into my page, so I thought you might want to know. I'm working on a personal programming project in React, nothing fancy. There's a repo here https://github.com/BlackRob/details_sentence_maker . In the root of the repo I added a screenshot, "weird_issue_screenshot.png". Basically, in just one component, a button, when uBlockOrigin is enabled, a long list of spam links (part of the list is visible in the screenshot) appears in the CSS. This is when it is run locally, I never plan on running it anywhere else. I wouldn't have noticed except the last part of the spam list is "Display: none! important", so that makes the entire button disappear. This doesn't happen with the other identical buttons (instances of the component), just the one "adv" one (for "adverbs", it's a grammar game). It also doesn't happen in Safari or Chrome.

### A specific URL where the issue occurs

localhost:3000

### Steps to Reproduce

1. download repo, enter and run "npm start"
2. in the page that opens up at localhost:3000
3. toggle ublock on and off. The "adv" button disappears when ublock is enabled, and the spammy links show up in the css

### Expected behavior

Nothing should happen (it should work the same whether uBlock is enabled or not)

### Actual behavior

uBlock seems to be inadvertenly adding text to the "advText" css. "advText" stands for 'adverb text', not "advertising text". The added links include a "display:none! important" rule that causes the button to disappear.

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 100.0

### Operating System and version

macos, 12.3.1

**Comment by u-RraaLL** [comment]
Does the css say `display: none !important`?

**Comment by BlackRob** [comment]
I changed .advText to .adverbText, so I don't have a problem anymore. But still something you all should look into. It isn't just blocking a class name, it's actively inserting a bunch of other links. I don't know much about how uBlock works, so I don't know where this list comes from. But I just copied it and pasted it into a text file and added it to my Github repo. Maybe one of you will recognize the list of links. 

Accidentally put it in the src folder, https://github.com/BlackRob/details_sentence_maker/blob/master/src/stuff_inserted.txt

**Comment by BlackRob** [comment]
> Uhm, how exactly do you think cosmetic filtering works? uBO needs to insert CSS selectors to use display: none !important on them.

I'm not actually an IT guy. I assumed that filters _removed_ unwanted content, beacuse that's what the word "filter" means, that they didn't just hide it. 

If you only want to hide a particular class, why not just add display:none to that class, why add a whole long list of extra links to the CSS?

So then this is normal behavior? If anyone uses a class name like "advText" it will get flagged and blocked? I'll happily close the issue if it isn't an issue. 

Not trying to be snarky, I'm genuinely curious. Is there a list somewhere of class names that developers should avoid?

**Comment by gwarser** [comment]
Elements cannot be removed (by default) because it will change the DOM and other filters/selectors based on these elements will stop working. 

This huge list of selectors is how blocking in most of the ad blockers work. It's more efficient to feed the list of selectors to the browser styling engine to do the job natively, instead of doing it in extension JavaScript code. However, this consumes more memory, so in uBO only the most generic filters are injected "blindly" - for more generic filters page DOM is scanned, and they are injected only when needed.

**Comment by BlackRob** [comment]
@gwarser Thank you for the explanation. Learn something new every day.

**Comment by krystian3w** [comment]
Lists for webmasters may no exists but possible rewrite EasyList to create bad generic classes/ID-s/attributes:

`/^(com|##)/`

![obraz](https://user-images.githubusercontent.com/35370833/169669427-687ff919-cc7c-4e08-8f78-99f10f74996e.png)


match 24 K filters.

**Comment by u-RraaLL** [comment]
> `/^(com##|##)/`

I think you meant `/^##|com##/`.

**Comment by krystian3w** [comment]
I like use brackets (IMO ns delay) and EL may not use "tld" to override `ghide`.

**Comment by u-RraaLL** [comment]
> I like use brackets (IMO ns delay) and EL may not use "tld" to override `ghide`.

Yea, but `/^(com##)/` is invalid.

**Comment by krystian3w** [comment]
so uBo input remove itself brackets?

**Comment by krystian3w** [comment]
I suppose somebody tommorow lock this topic and recommend move to reddit or continue via "e-mails".

**Comment by u-RraaLL** [comment]
Oh, you mentioned EL so I searched it and there were no `com##` filters so I thought you meant to select `domain.com##`, etc.

Yeah. went pretty much OT. Would've been better if this were a discussion not an issue. Conclusion reached on my end, though - a misunderstanding. No need to continue.
