### ISSUE TITLE
Removal of the classic popup broke middle-clicking uBO's icon

### ISSUE THREAD

**Issue by u-RraaLL** [uBlockOrigin/uBlock-issues#2116]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Removal of the classic popup broke middle-clicking the uBO icon.

Here's a patch: https://github.com/gorhill/uBlock/compare/master...u-RraaLL:u-RraaLL-popup-fix

### A specific URL where the issue occurs

github.com

### Steps to Reproduce

1. Install uBO 1.42.5rc0.
2. Middle-click the icon.
3. See "File not found".

### Expected behavior

Open popup-fenix.html

### Actual behavior

Failing to open the removed popup.html

### uBlock Origin version

1.42.5rc0

### Browser name and version

FF 99.0.1

### Operating System and version

MX Linux 19.4

**Comment by uBlock-user** [comment]
Need an address update from `/popup.html` to `/popup-fenix.html`

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/compare/51983afb0e...1c090f0fae

**Comment by krystian3w** [comment]
Responsive still is not exists in commit mass:

https://github.com/gorhill/uBlock/commit/1c090f0faecdc8ba49f3109d78bf27d1f847ff9f
https://github.com/gorhill/uBlock/commit/59d296f8a3e1429a17439706f84f027524604480

**Comment by gorhill** [comment]
@krystian3w Are you saying I should remove `responsive` since it's not used? If so, you are right. If not, I don't understand what you are saying with _"write function form zero"_.

**Comment by krystian3w** [comment]
From 0 - recover center if are opened panel as tab instead to right in LTR or to left in RTL.
