### ISSUE TITLE
WASM sources fail to compile with wabt 1.0.25 or later

### ISSUE THREAD

**Issue by rathann** [uBlockOrigin/uBlock-issues#2119]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

WASM sources in uBlock-1.42.4 fail to compile with wabt-1.0.25 or later.

wabt 1.0.25 dropped support for pre-1.0 names. These functions were renamed in 2018, before the WebAssembly 1.0 spec
was finalized.

Here's a fix: https://github.com/rathann/uBlock/commit/798338e7fadc69fe6bd75428c9a8588840cbbe52 . I would've opened a pull request, but I'm not allowed due to not being previous contributor, apparently.

### A specific URL where the issue occurs

https://github.com/WebAssembly/wabt/issues/1820

### Steps to Reproduce

1. `git clone https://github.com/gorhill/uBlock.git`
2. `rm src/lib/lz4/lz4-block-codec.wasm`
3. `wat2wasm src/lib/lz4/lz4-block-codec.wat`

### Expected behavior

Successful compilation of WASM sources with `wat2wasm` version 1.0.25 or later.

### Actual behavior

The sources fail to compile with errors like:

```
$ wat2wasm src/lib/lz4/lz4-block-codec.wat
src/lib/lz4/lz4-block-codec.wat:71:5: error: unexpected token get_local, expected ).
    get_local $ilen
    ^^^^^^^^^
src/lib/lz4/lz4-block-codec.wat:78:5: error: unexpected token get_local.
    get_local $ilen
    ^^^^^^^^^
```

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 100.0.1

### Operating System and version

Fedora Linux 36

**Comment by apoleon** [comment]
I can confirm this bug report. Debian has applied the following patch to fix this issue:

https://sources.debian.org/src/ublock-origin/1.42.0%2Bdfsg-1/debian/patches/lz4-block-codec.wat.patch/

**Comment by gorhill** [comment]
Thanks @rathann for your patch, imported to uBO's repo: <https://github.com/gorhill/uBlock/commit/798338e7fadc69fe6bd75428c9a8588840cbbe52>

**Comment by rathann** [comment]
You're welcome! Thanks for accepting the patch.
