### ISSUE TITLE
Does "no-scripting" need upgrade rule? 

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#212]
I see a [new default dynamic rule](https://github.com/gorhill/uBlock/blob/master/src/js/start.js#L258): `no-scripting: behind-the-scene false`. Does it need upgrade rule in [`onVersionReady`](https://github.com/gorhill/uBlock/blob/master/src/js/start.js#L120)? If I recall right, previous changes all had an upgrade rule. 

Also, I see that [`compiledMagic`](https://github.com/gorhill/uBlock/blob/master/src/js/start.js#L247) and [`selfieMagic`](https://github.com/gorhill/uBlock/blob/master/src/js/start.js#L267) are defined as string in default values in `onSelectedFilterListsLoaded`, shouldn't they be integers?

**Comment by jspenguin2017** [comment]
@gorhill Also, I just noticed that the Edge port by nikrolls is still on 1.15.24, maybe (re-)implement the upgrade rule for `manualUpdateAssetFetchPeriod` as a normal upgrade rule instead of putting it in the settings load routine? 

![image](https://user-images.githubusercontent.com/7283682/45268398-cb7dfd00-b438-11e8-9882-e727b40910c4.png)

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/commit/b5ef2d0105d6e5fa34cbac90bf1c19a0d3b18fe7
