### ISSUE TITLE
Device Name Not Being Saved when Cloud Storage is Enabled

### ISSUE THREAD

**Issue by jsmorada** [uBlockOrigin/uBlock-issues#2120]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

When cloud storage is enabled the default device name is Win32. I can click the gear icon to change the device name and hit the Submit button, but the device name is still Win32.

### A specific URL where the issue occurs

https://www.google.com

### Steps to Reproduce

Click the gear icon on the right side of the screen,
Change the device name.
Click the submit button.

### Expected behavior

I expect the device name to change.

### Actual behavior

The device name doesn't change.

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 100
filterset (summary): 
  network: 94400
  cosmetic: 165701
  scriptlet: 23682
  html: 664
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 53446-4361, 13m
    adguard-social: 17379-1108, 13m
    fanboy-thirdparty_social: 69-0, 13m
    fanboy-annoyance: 71348-158, 13m
    fanboy-cookiemonster: 32253-32253, 13m
    fanboy-social: 23407-23407, 13m
    ublock-annoyances: 4434-4, 13m
  default: 
    user-filters: 22-1, never
    ublock-filters: 32057-61, 1d.12h.31m
    ublock-badware: 4132-3, 1d.12h.30m
    ublock-privacy: 220-0, 5d.1h.52m
    ublock-abuse: 75-0, 5d.1h.51m
    ublock-unbreak: 1801-4, 23h.56m
    ublock-quick-fixes: 187-0, 9h.42m
    easylist: 67366-669, 23h.55m
    easyprivacy: 27061-677, 23h.54m
    urlhaus-1: 8387-0, 9h.41m
    plowe-0: 3673-3, 5d.1h.53m
filterset (user): [array of 22 redacted]
trustedset: 
  added: [array of 7 redacted]
switchRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1405 ms (selfie)
  maxAssetCacheWait: 1148 ms
```
</details>

**Comment by jsmorada** [comment]
Clicking the “Export” button didn’t fix the issue.

**Comment by gwarser** [comment]
Device name under the gear button is saved on my side. The name and date on the left side shows what is on the server, so you need to "Export to cloud" for it to change.

**Comment by jsmorada** [comment]
That did it…You’re amazing!

 

Thanks so much and have a great rest of the week.
