### ISSUE TITLE
Element picker makes whole website invisible on dark color scheme websites

### ISSUE THREAD

**Issue by emilio** [uBlockOrigin/uBlock-issues#2121]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

This is basically https://github.com/uBlockOrigin/uBlock-issues/issues/1408 again.

The fix for that issue wasn't quite correct (was relying on a Chrome bug) and Firefox Nightly and Chrome Canary (at least) show the issue again.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1771047

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Go to a dark mode website with a dark color-scheme preference (like this one).
2. Right click, Block element..

### Expected behavior

Page is visible

### Actual behavior

Page is invisible because iframe is opaque, because of a color-scheme mismatch.

I had written a patch, see https://github.com/emilio/uBlock/commit/1cfbebe23449443a6d0f3e28ea559572a45b06cc, but I can't open a PR in @gorhill's repo so I opened an issue here instead.

Thanks!

### uBlock Origin version

trunk

### Browser name and version

Firefox Nightly / Chrome Canary

### Operating System and version

All

**Comment by gwarser** [comment]
It's not the page theme, but browser theme what need to be set to dark.

**Comment by emilio** [comment]
https://github.com/emilio/uBlock/commit/51983afb0e6713c5b1a3a5995b6881bcabeda9c3 is a better fix. @gwarser do you know what I'd need to get it merged?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/51983afb0e6713c5b1a3a5995b6881bcabeda9c3

**Comment by gwarser** [comment]
Seems to be fine now.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2196

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2240
