### ISSUE TITLE
Block element and filter picker do not work

### ISSUE THREAD

**Issue by NickVolt77** [uBlockOrigin/uBlock-issues#2125]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Settings/filters seems to do not work - are not saved or ignored.

In my filters i have:
! 2022-05-26 https://www.terazkrosno.pl
||www.terazkrosno.pl/images/rek/*$image
||www.terazkrosno.pl/images/rek/zps2-01-2022.webp$image

But none of them works.

The same behavior on:
Opera with uBlock
Brave with uBlock
clean Vivalid installation with uBlock only

### A specific URL where the issue occurs

https://www.terazkrosno.pl/galerie/40-iwonicz-zdroj/5873-dachowanie-renault-w-iwoniczu/0

### Steps to Reproduce

1. Go to specific url.
2. Block top baner with "block element" on right mouse button's menu or with "select element to block".
3. Reload page.

### Expected behavior

Banner should not be visible.

### Actual behavior

Banner is still visible.

### uBlock Origin version

1.42.4

### Browser name and version

Opera 86.0.4363.50

### Operating System and version

Manjaro Cinnamon (system is up to date)

**Comment by mapx-** [comment]
I got the same filter
`||www.terazkrosno.pl/images/rek/zps2-01-2022.webp$image`

however after bypassing the cache (ctrl-F5) the ad is blocked

**Comment by gwarser** [comment]
It loads from service worker, so it's `xhr` too. Filter created by picker has `image` option.

**Comment by NickVolt77** [comment]
I did not change anything and now it works.

**Comment by gwarser** [comment]
> I did not change anything and now it works.

Service worker expired / was cleaned/removed.
