### ISSUE TITLE
Feature request: add word as a kill filter on websites

### ISSUE THREAD

**Issue by YesTrustMe** [uBlockOrigin/uBlock-issues#2126]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When visiting forums or private sites (cannot post them here) I want to filter out threads with certain posters. Element picker does not work, For example, poster name is Bobert69. adding has-text to doesn't do anything. 

### A specific URL where the issue occurs

google.com

### Steps to Reproduce

1. Open up Ublock
2. tag the username via element picker
3. manually write the name of username or keyword
4. Curse out loud because sophists and trolls are on reddit or other sites providing misleading or incomplete info. 

### Expected behavior

Pick and block.

### Actual behavior

Nothing happens

### uBlock Origin version

1.42.4

### Browser name and version

Chrome Version 102.0.5005.63 (Official Build) (64-bit)

### Operating System and version

Windows 11 Version	10.0.22000 Build 22000

**Comment by mapx-** [comment]
The place for such specific requests is: 
https://www.reddit.com/r/uBlockOrigin/new/

but you have to provide (real) example pages
