### ISSUE TITLE
[Feature Request] Will UBlock Origin implement Global Privacy Sec-GPC header

### ISSUE THREAD

**Issue by m0lz** [uBlockOrigin/uBlock-issues#2127]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Request for a new feature ..

Global Privacy setting it seems is going to take off, unlike Do Not Track (DNT)

The setting Sec-GPC header is already included in other plugins and Firefox Browser, see link below (none of which do I use), so I for one am hoping UBlock Origin will also include it for us Chrome / Edge users.

https://globalprivacycontrol.org/orgs

Apparently legally in the EU GDPR will be backing it up, and recently a few USA States have also confirmed they will be supporting it legally

Could we please have a setting in UBlock Origin to set Sec-GPC: 1

### A specific URL where the issue occurs

[none]

### Steps to Reproduce

[none]

### Expected behavior

A Global Privacy setting which registers my preference to not have third parties sell on my data

### Actual behavior

UBlock Origin currently does not have this setting

### uBlock Origin version

1.42.4

### Browser name and version

Chromium 102.0.5005.63

### Operating System and version

Windows 11 21H2

**Comment by m0lz** [comment]
Apologies if this is in the wrong place, but I could not find where a feature request should go.

**Comment by gwarser** [comment]
"Probably not"

https://www.reddit.com/r/uBlockOrigin/comments/qlj2kl/will_ublock_origin_send_the_gpc_donotsell_signal/
