### ISSUE TITLE
[Feature request] Default allow certain things should be dropped when expert mode is enabled

### ISSUE THREAD

**Issue by B1u3l1ght** [uBlockOrigin/uBlock-issues#2128]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

For example when trying to import no-google/no-facebook/no-amazon custom block lists those will be bypassed as many things are default allowed (appear green in logger and green-listed by various list providers including default ones. Things like recaptcha few other youtube/facebook elements. While i can understand why they are green (@@||) however some may expect when checking that 'i'm an expert' box to have those default allow rules dropped.

### A specific URL where the issue occurs

https://www.virustotal.com/gui/home/upload

### Steps to Reproduce

1) Have no-google blacklist imported  https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains
2) Visit www.virustotal.com/gui/home/upload
3) Despite having no-google list enabled certain things belonging to google will get thru (recaptcha/gstatic)

### Expected behavior

When expert mode is checked i suggest dropping all allow rules (@@||) so custom imported lists should not be in conflict with those that are already active

### Actual behavior

When 'i'm an expert' mode is on still too many things get thru. That doesn't align at least in my book with the word 'expert' so either should not be called 'expert mode' or dropp those default allow rules.
Screen capture shows 2332 allow rules
![Screenshot_2022-05-30_11-01-47](https://user-images.githubusercontent.com/103362263/170949793-62623b85-a5aa-4466-bf00-dae86d677040.png)
.

### uBlock Origin version

1.42.5rc0

### Browser name and version

Firefox version 100.0.2

### Operating System and version

Arch based, Artix Linux

**Comment by B1u3l1ght** [comment]
Yeah i know not all allows network requests however still a fair amount of requests 'slip under the door' and that may not correspond to 'advance user mode' either. I mean i don't wanna be insistent but not everybody wants recaptcha or gstatic slip under while using lists like no-google. Hunting with the help of dynamic filters still is post-factum method and i don't think is feasible against this default allows rules. So wouldn't be better if we can have a checkbox to deactivate those default allows kind of network requests
![Screenshot_2022-05-30_19-00-18](https://user-images.githubusercontent.com/103362263/171028372-ad62b53f-a92c-41fe-8c08-6f2a4e8f3de9.png)
?
Tnx for the corrections

**Comment by u-RraaLL** [comment]
> Hunting with the help of dynamic filters still is post-factum method and i don't think is feasible against this default allows rules.

The point is to use one of the "blocking modes" - in your case [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode), which will block every 3p domain until you explicitly "no-op" it to use a filter list instead or "allow" it to always let it through.

And the 2nd one is an actual "allow rule", what you're referring to is an "exception filter".

> not everybody wants recaptcha or gstatic slip under while using lists like no-google

That's a simple HOSTS list, so you could actually put it into your HOSTS file.
Yes, uBO does support it, but like you noticed, the list will be limited by exception filters. If the list maintainer used uBO syntax, they could've used `important` to override exception filters.

**Comment by B1u3l1ght** [comment]
The way i see it is that uBO and no-google list were built having flexibility in mind. However currently this is true for the medium advanced users and this flexibility becomes pretty rigid when you wanna filter out something like Big Bro Google . Using hard mode is an overkill and is not a pinpoint solution as it will basically block everything 3rd party and not only those greedy companies (while CNAME's can still sneak in as 1st party so you're back to square 1) Also there are domains that are not even detected as google (eg: ghs-svc-https-c46.ghs-ssl.googlehosted.com) leaking requests that probably can only be denied with dynamic rules. Also don't know if there are 'important' exceptions allowed cos i can't review 300k+ entries to really know what's in there.

![Screenshot_2022-05-31_00-17-52](https://user-images.githubusercontent.com/103362263/171060089-89ff6b27-ab88-40cb-ac40-e8f1af49c56b.png)
![Screenshot_2022-05-31_00-24-36](https://user-images.githubusercontent.com/103362263/171060623-cf89190f-d7d2-4058-a6c5-963c96101915.png)

**Comment by uBlock-user** [comment]
> Also don't know if there are 'important' exceptions allowed

Present but not supported by uBO, AdGuard only.
