### ISSUE TITLE
List-KR filter link broken

### ISSUE THREAD

**Issue by nforestcat** [uBlockOrigin/uBlock-issues#2129]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

'moz-extension://eae39a16-aaaa-433f-ad81-6f6d40240e56/dashboard.html#3p-filters.html'

### Describe the issue

ublock basic given filter for korean is list-kr, but link to filter.txt is broken and cannot be replaced by uBO filter described from followed link

https://github.com/List-KR/List-KR/issues/277

### Screenshot(s)

![1](https://user-images.githubusercontent.com/88011689/171178138-c55640b2-40c7-4809-99c3-eae646c1ddcd.PNG)
![2](https://user-images.githubusercontent.com/88011689/171178142-4b9d9eaf-b95d-49bb-ae4a-0b4c73e01bc5.PNG)

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 100.0.2

### Settings

![3](https://user-images.githubusercontent.com/88011689/171178596-71dbe18d-77ca-48f3-91e5-c07e5f1cd943.png)

**Comment by gwarser** [comment]
That list is just empty. All lines are commented-out.

**Comment by gwarser** [comment]
"contentURL": "https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt",

Should be `https://raw.githubusercontent.com/List-KR/List-KR/master/filter-uBO.txt`.

**Comment by Yuki2718** [comment]
> Also:
> 

You know I commented about this before on Slack but I don't understand why it happens (on some profiles).
@Piquark6046

**Comment by piquark6046** [comment]
Hmm... I can rename them.
However, It affects [AdGuard DNS service](https://github.com/AdguardTeam/HostlistsRegistry)[^1].

[^1]: https://github.com/AdguardTeam/HostlistsRegistry/issues/11

**Comment by gwarser** [comment]
Is it better now in rc1?

https://github.com/gorhill/uBlock/releases/tag/1.42.5rc1
