### ISSUE TITLE
Where to post if not here?

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uBlock-issues#213]
https://github.com/uBlockOrigin/uBlock-issues/issues/211

Sorry, but I still don't know where to post if not here. The cosmetic filter is built-in to µBlock. I couldn't find any specific "cosmetic" filterlist where I could report my problem.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues

**Comment by SEXXES** [comment]
oh, OK
thanks, but whats the difference between µAssets and µBlock-issues?

**Comment by uBlock-user** [comment]
Users are expected to have read the [readme](https://github.com/uBlockOrigin/uBlock-issues#ublock-issues) atleast once before opening any issue here.

**Comment by gorhill** [comment]
> but I still don't know where to post if not here

![a](https://user-images.githubusercontent.com/585534/45258424-353ccf00-b385-11e8-90e1-dce38b0b04f4.png)

:thinking:
