### ISSUE TITLE
It is very confusing to have ublock issues be in a different repo from ublock

### ISSUE THREAD

**Issue by julie777** [uBlockOrigin/uBlock-issues#2132]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Why aren't ublock issues all in the same place in the ublock repo? 
Having some issues in a separate github repo from the ublock repo makes no sense, is confusing, and causes problems with searching. The wiki is in the ublock repo!

Why are discussions not in github discussions? Instead questions and support redirects to an old.reddit.com site which doesn't seem very functional.

Why isn't there an issue category for enhancements?

Help the users. Put all user interaction in one place. Please.

My original intent was to request support for stripping ad links from a url instead of just blocking it. I got sidetracked because of all the different locations used for ublock. 
I just had a URL blocked because it was http://doubleclick.***********forever*****/website.com/thepageIwantedtoread which was easy to manually copy the good URL and use it. I was hoping that ublock could do this for me.

### A specific URL where the issue occurs

http://doubleclick.***********forever*****/website.com/thepageIwantedtoread 

### Steps to Reproduce

click on a link that gets blocked because it redirects through doubleclick

### Expected behavior

just rip of the doubleclick part and try again

### Actual behavior

blocked

### uBlock Origin version

1.42.4

### Browser name and version

firefox 100

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> Why aren't ublock issues all in the same place in the ublock repo?

Because this allows to have more contributors volunteering to handle issues here along with commit rights, while limiting commit rights to only myself for the actual uBO code base.

**Comment by gorhill** [comment]
Marking as _invalid_, such question should be made in [Discussions](https://github.com/uBlockOrigin/uBlock-issues/discussions).
