### ISSUE TITLE
Cannot install on PC FireFox v 100+

### ISSUE THREAD

**Issue by Emiliorth** [uBlockOrigin/uBlock-issues#2133]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Fresh installation of PC, FireFox, tested on few PC's, cannot install uBlock Origin on FireFox from FireFox addons repository. Getting error that this addon seems to be corrupted. Problem occurs since few months

### A specific URL where the issue occurs

about:addons

### Steps to Reproduce

1. Open about:addons
2. Try to install addon

### Expected behavior

Addon installation completed successfully

### Actual behavior

Addons seems to be corrupted error

### uBlock Origin version

newest

### Browser name and version

FireFox 101.0 64bit

### Operating System and version

Windows 10 21H2

**Comment by gorhill** [comment]
Can't help you, the message you mention is issued by Firefox, and Firefox only has the ability to sign and validate extensions. You will have to seek help with Firefox support.

**Comment by gwarser** [comment]
Clearing browser cache may help in this situation.

**Comment by krystian3w** [comment]
Maybe ISP or AntiVirus break download, save manually to xpi/zip and drop into `about:addons`.

Also no report here bugs after use custom `.uc.js` scripts in Firefox to add function out of scope for WebExtension or marked as won't implemented on bugzil.la.

**Comment by Lestrad** [comment]
Okay, I updated to version 115.12.0esr and was able to install. Hope this helps.
