### ISSUE TITLE
Youtube Lags When On

### ISSUE THREAD

**Issue by MInecrafterPictures** [uBlockOrigin/uBlock-issues#2139]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Everytime I turn on the ad blocker, Youtube lags for absolutely no reason.

### A specific URL where the issue occurs

www.youtube.com

### Steps to Reproduce

Use Youtube on a video

### Expected behavior

Lack of ads, no lagging

### Actual behavior

Lack of ads + lagging

### uBlock Origin version

Chrome Webstore Version

### Browser name and version

Chrome Canary (latest version)

### Operating System and version

Windows 10

**Comment by DwarfFighterCleric** [comment]
same issue using Ungoogled Chromium 86.0.xx with uBlock from a few months ago... Will try updating uBlock.  
Behavior goes like this:  
No video will start playback unless I actually disable uBlock, reload the page, then all videos play immediately. After that, I can enable uBlock back again and reload the page, this time around it will play immediately too. If I go back browser history a few pages or if I happen to reload the page for whatever reason, I have to do the same procedure again.
