### ISSUE TITLE
Bring back the classic UI, Add a rollback, or unthicken the right-hand popup panel

### ISSUE THREAD

**Issue by TsukiZero** [uBlockOrigin/uBlock-issues#2141]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Bring back the classic UI, Add a rollback, or unthicken the right-hand popup panel. It was stupid to make it EXTRA LARGE because "mobile".

Or at least have the decency of properly documenting how to stylize it!

### A specific URL where the issue occurs

the popup

### Steps to Reproduce

No detail

### Expected behavior

no detail

### Actual behavior

no detail

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 101
filterset (summary): 
  network: 83189
  cosmetic: 44373
  scriptlet: 17323
  html: 678
listset (total-discarded, last updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 416-0, 22h.51m
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt: 0-0, 22h.50m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 22h.49m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-0, 6d.9h.42m
  default: 
    user-filters: 418-8, never
    ublock-filters: 32453-47, 2d.9h.29m
    ublock-badware: 4195-3, 2d.9h.28m
    ublock-privacy: 228-0, 2d.9h.27m
    ublock-abuse: 75-4, 2d.9h.26m
    ublock-unbreak: 1811-0, 2d.9h.25m
    easylist: 68191-574, 2d.9h.24m
    easyprivacy: 27193-908, 2d.9h.23m
    urlhaus-1: 7433-0, 22h.52m
    plowe-0: 3639-5, 6d.9h.42m
    ublock-quick-fixes: 196-0, 22h.48m
filterset (user): [array of 418 redacted]
trustedset: 
  added: [array of 11 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 1 redacted]
urlRuleset: 
  added: [array of 10 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 604 ms (selfie)
  maxAssetCacheWait: 264 ms
```
</details>

**Comment by TsukiZero** [comment]
And I mean it. Look at this, this is compact, this is good design, compared to Fenix.
![image](https://user-images.githubusercontent.com/78157224/173724280-d22ae52c-e185-4f9a-804c-d98081130385.png)

**Comment by hello-smile6** [comment]
@TsukiZero Reopen your issue, people might care.

**Comment by TsukiZero** [comment]
> @TsukiZero Reopen your issue, people might care.
Alright, although I'm not very hopeful the developer actually cares... And that's the main issue: I've seen many devs go into the dark side, cast aside the compact and simple for the larger and convoluted.

**Comment by hello-smile6** [comment]
> > @TsukiZero Reopen your issue, people might care.
> 
> Alright, although I'm not very hopeful the developer actually cares... And that's the main issue: I've seen many devs go into the dark side, cast aside the compact and simple for the larger and convoluted.

It's the ones that use Discord, mainly.
