### ISSUE TITLE
Selecting "element zapper mode" is broken on Facebook

### ISSUE THREAD

**Issue by mpoirier101** [uBlockOrigin/uBlock-issues#2143]

**Comment by MasterKia** [comment]
Oh, had no idea it was transferred (no notification).

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2121

?

**Comment by MasterKia** [comment]
> Duplicate of #2121
> 
> ?


> ### Steps to Reproduce
> 1. Go to a dark mode website with a dark color-scheme preference (like this one).

> It's not the page theme, but _**browser theme**_ what need to be set to dark.
_Originally posted by @gwarser in https://github.com/uBlockOrigin/uBlock-issues/issues/2121#issuecomment-1137120553_

Yeah, now that I've set Windows on light mode (therefore causing Chrome to be on light mode), I can't reproduce.
Fortunately the fix is in the next release.
