### ISSUE TITLE
Thunderbird - Toolbar button doesn't work

### ISSUE THREAD

**Issue by Hackerpcs** [uBlockOrigin/uBlock-issues#2144]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Addon button from toolbar doesn't work, URL seems to be missing. Settings from Addons list can be opened

![Untitled](https://user-images.githubusercontent.com/17467335/174417742-ac692fbd-2518-4658-9ac3-3cad0e7b45ca.png)

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Install Thunderbird on clean profile
2. Install latest 1.43.0 https://github.com/gorhill/uBlock/releases/tag/1.43.0
3. Open toolbar tooltip

### Expected behavior

Tooltip working

### Actual behavior

Tooltip is missing, missing URL

### uBlock Origin version

1.43.0

### Browser name and version

Thunderbird 91.10.0

### Operating System and version

Windows 10 Enterprise 21h2

**Comment by gwarser** [comment]
Must be changed to

    popup-fenix.html

because old popup UI was removed.
