### ISSUE TITLE
Pressing and holding Ctrl causes a ui error in 'godmode'

### ISSUE THREAD

**Issue by shc0743** [uBlockOrigin/uBlock-issues#2145]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] uBO with default lists/settings
- [x] using a new, unmodified browser profile

### Description

If **I am advanced user** (Important!) and I open uBlock popup panel in any page,
then press Ctrl for more than 1 second,
the green allow box will twinkle:
![image](https://user-images.githubusercontent.com/60457042/174427547-de042895-b54a-4fd9-872d-f13aeb9235a2.png)
![image](https://user-images.githubusercontent.com/60457042/174427561-7198f228-8b00-4f48-b2b7-14087e20053b.png)
I tried to find out why this appear,
and (maybe) I found the problem source:

/js/popup-fenix.js , Line 1256
```
/*******************************************************************************

    Double tap ctrl key: toggle god mode

*/

{
    let eventCount = 0;
    let eventTime = 0;

    document.addEventListener('keydown', ev => {
        if ( ev.key !== 'Control' ) {
            eventCount = 0;
            return;
        }
        const now = Date.now();
        if ( (now - eventTime) >= 500 ) {
            eventCount = 0;
        }
        eventCount += 1;
        eventTime = now;
        if ( eventCount < 2 ) { return; }
        eventCount = 0;
        document.body.classList.toggle('godMode');
    });
}
```

It cause the 'godMode' class toggles very quickly, so the box twinkle.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Check "I am advanced user" in uBlock settings
2. Open a webpage
3. open uBlock origin popup page
4. Move the mouse to any box
![屏幕截图 2022-06-18 151300](https://user-images.githubusercontent.com/60457042/174427202-853678db-6563-474e-a949-c3c22dc81e61.png)
5. press Ctrl key for more than 1 seconds

### Expected behavior

godMode open and a green allow box appear
![image](https://user-images.githubusercontent.com/60457042/174427265-14f95d14-c7cd-4606-9d97-c2b3eb378ba4.png)

### Actual behavior

The green allow box twinkle very quickly.
'godMode' is always toggling.
if I open DevTools, there is a 'godMode' twinkle in body's class:
![image](https://user-images.githubusercontent.com/60457042/174427434-da8df718-a874-4d48-b809-beb75cb63bee.png)
![image](https://user-images.githubusercontent.com/60457042/174427447-0705189c-024d-41f8-b09f-1a1f68705920.png)

### uBlock Origin version

1.42.4

### Browser name and version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

### Operating System and version

Windows 10 21H2 19044.1766

**Comment by gorhill** [comment]
Unable to reproduce. It seems your ctrl key may be auto-repeating, I don't think it should.

**Comment by shc0743** [comment]
> Unable to reproduce. It seems your ctrl key may be auto-repeating, I don't think it should.

Yes, this is caused by auto repeating.
Maybe it is hardware related. I tested with my physics keyboard, it repeats and `ev.repeat`==true .
Open this test url and open DevTools to test `data:text/html,<script src="data:text/javascript,document.addEventListener('keydown',function(ev){console.dir(ev)})"></script>Press any key to test`
It repeats in my computer
![屏幕截图 2022-06-19 133610](https://user-images.githubusercontent.com/60457042/174467484-88755ff5-f69a-42ee-bb9d-96d6d12a868e.png)

But when I test with osk.exe (Windows Screen Keyboard), I can't reproduce.
I think you could add `if (ev.repeat) return;` and this will be solved.

**Comment by gwarser** [comment]
I can reproduce in VM Win10 in Firefox, Edge, Chrome and Opera - Windows thing?

**Comment by gorhill** [comment]
>  think you could add `if (ev.repeat) return;` and this will be solved.

Good idea, will do: <https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat>.

**Comment by shc0743** [comment]
It looks like solved.

**Comment by shc0743** [comment]
It looks like solved.

**Comment by krystian3w** [comment]
Fix works too on Windows 7.

To check Windows XP then needed is use MyPal 68 if is in good work latest stable and dev builds of uBo
