### ISSUE TITLE
New filter list "FMSF" for Vietnamese users

### ISSUE THREAD

**Issue by nguyen-trung-mulodo** [uBlockOrigin/uBlock-issues#215]
Hi,

Can you include FMSF - a Vietnamese filter list? This filter list is used by many people in Vietnam for more than 3 years and updated weekly.

Forum homepage: https://forums.voz.vn/showthread.php?t=4083932
Filter list homepage: http://nmtrung.com/fmsf-2
Github: https://github.com/nmtrung/FMSF-2.0

Thank you

**Comment by gorhill** [comment]
I will declined, there is too many generic filters in there with shouldn't be in a regional list.
