### ISSUE TITLE
UBlock not synchronising down only Up on Edge even when it shows syncing is on.

### ISSUE THREAD

**Issue by thorrrr** [uBlockOrigin/uBlock-issues#2150]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I have tried for weeks to find an answer on your Reddit support channel and got no useful help to remedy this issue.
I use several Pcs daily and use UB on all. I use Edge with same profile, and everything synchronises fine accept UBlock

I can spend several hours adding rules in UB then uploading which i think works as it shows a new time stame when i hit the up.
But when i go on my next Pc and press to merge it does nothing.

I have tried removing readding northing works on UB re sycing

### A specific URL where the issue occurs

extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.htmlextension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### Steps to Reproduce

see above 

### Expected behavior

It merges new rules onto current pc via edge syync

### Actual behavior

does nothing only allows upload

### Configuration

No idea

![image](https://user-images.githubusercontent.com/8170673/175281719-484cbf8b-a5d0-45dc-8b4a-77358b75f22e.png)

![image](https://user-images.githubusercontent.com/8170673/175281775-5d6d95d1-1baf-4315-95a1-4827414c7ae4.png)

uBlock Origin: 1.43.0
Chromium: 104
filterset (summary): 
  network: 78825
  cosmetic: 44172
  scriptlet: 17337
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 67867-50, 13m
    easyprivacy: 27257-122, 13m
    plowe-0: 3647-783, 13m
    ublock-abuse: 75-0, 13m
    ublock-badware: 4211-93, 13m
    ublock-filters: 31869-105, 13m
    ublock-privacy: 224-3, 13m
    ublock-quick-fixes: 226-2, 13m
    ublock-unbreak: 1813-42, 13m
    urlhaus-1: 4509-0, 13m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 219 ms
  maxAssetCacheWait: 110 ms

**Comment by gwarser** [comment]
What you see in the cloud storage widget on second PC?

The "Storage used: 19MB" is unrelated - browsers cloud storage will not allow for such huge amount of data to be synced.

**Comment by thorrrr** [comment]
> What you see in the cloud storage widget on second PC?
> 
> The "Storage used: 19MB" is unrelated - browsers cloud storage will not allow for such huge amount of data to be synced.

**Comment by thorrrr** [comment]
See here https://1drv.ms/u/s!Ao6WCX2miTCJjq5d9uDWa4eD3o8fOQ?e=nBLIxs  from laptop

**Comment by gwarser** [comment]
But the timestamp looks recent.

**Comment by thorrrr** [comment]
> But the timestamp looks recent.

I used it this morning and left it on !!

**Comment by thorrrr** [comment]
On my My Filters tab i removed some from my main desktop. I applied changes and then uploaded to cloud manually.
When i check on my laptop nothing has changed the new settings are not coming over and i have my old filters still showing!!

**Comment by thorrrr** [comment]
cheers sorted now
