### ISSUE TITLE
Cosmetic filter rules are ignored

### ISSUE THREAD

**Issue by RenaKunisaki** [uBlockOrigin/uBlock-issues#2152]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Clicking an element in picker/zapper modes and creating a cosmetic filter removes the element, and adds it to the filter list, but it still comes back next time you visit the page.

### A specific URL where the issue occurs

https://stackoverflow.com/questions/56303648/webgl-rendering-buffers

### Steps to Reproduce

1. Open element picker
2. Click the massive cookie popup in the lower left corner
3. Shorten the rule to just `##.js-consent-banner`
4. Click Apply

### Expected behavior

1. The rule `stackoverflow.com##.js-consent-banner` is added to my filters list
2. The popup doesn't appear next time I visit the site

### Actual behavior

1. The rule `stackoverflow.com##.js-consent-banner` is added to my filters list
2. The popup *does* appear next time I visit the site

The rule is now in my filter list several times, and still has no effect.

Full filter list:
```
! 2021-10-23 https://reverseengineering.stackexchange.com
reverseengineering.stackexchange.com##.js-consent-banner

! 2021-10-24 https://blender.stackexchange.com
blender.stackexchange.com##.js-consent-banner

! 2021-11-03 https://sound.stackexchange.com
sound.stackexchange.com##.js-consent-banner

! 2021-11-03 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

! 2021-11-03 https://unix.stackexchange.com
unix.stackexchange.com##.js-consent-banner

! 2021-11-06 https://askubuntu.com
askubuntu.com##.js-consent-banner

! 2021-11-07 https://superuser.com
superuser.com##.js-consent-banner

! 2021-11-08 https://serverfault.com
serverfault.com##.js-consent-banner

! 2022-03-27 https://www.aliexpress.com
www.aliexpress.com##.lottieContainer
www.aliexpress.com##body > div > div > div > .container
www.aliexpress.com##.pop-picture

! 2022-04-14 https://hub.packtpub.com
hub.packtpub.com##.td-slider
hub.packtpub.com##.td_block_template_1.tdi_1_85a.td-a-rec-id-content_inline.td-a-rec > [href]
hub.packtpub.com##.widget_custom_html.widget.td_block_template_1.widget_text

! 2022-04-23 https://math.stackexchange.com
math.stackexchange.com##.js-consent-banner

! 2022-04-24 https://gamedev.stackexchange.com
gamedev.stackexchange.com##.js-consent-banner

! 2022-06-15 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

! 2022-06-16 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

! 2022-06-16 https://askubuntu.com
askubuntu.com##.js-consent-banner

! 2022-06-18 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

! 2022-06-20 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

! 2022-06-23 https://stackoverflow.com
stackoverflow.com##.js-consent-banner

```

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 78950
  cosmetic: 44170
  scriptlet: 17333
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
  default: 
    easylist: 67870-50, 8h.2m
    easyprivacy: 27257-122, 8h.1m
    plowe-0: 3648-782, 7d.8h.23m
    ublock-abuse: 75-0, 8d.8h.31m
    ublock-badware: 4211-93, 8h
    ublock-filters: 31863-105, 7h.59m
    ublock-privacy: 224-3, 8d.8h.28m
    ublock-quick-fixes: 204-2, 7h.57m
    ublock-unbreak: 1813-42, 7h.58m
    urlhaus-1: 4651-0, 7h.56m
filterset (user): [array of 22 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 421 ms (selfie)
  maxAssetCacheWait: 856 ms
```
</details>

**Comment by mapx-** [comment]
`user-filters: null`

Did you disable `my filters` ? Enable it back

**Comment by RenaKunisaki** [comment]
Either I managed to disable a setting I didn't know existed on two different machines without realizing it, or it was never enabled to begin with, which doesn't seem to make much sense after having created filters.
