### ISSUE TITLE
MY FILTERS list scroll unresponsive

### ISSUE THREAD

**Issue by mikeyhodl** [uBlockOrigin/uBlock-issues#2153]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When scrolling the dashboard.html#1p-filters.html page the list is unresponsive.

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html

### Steps to Reproduce

1.Open the dashboard
2.click MY FILTERS
3. Scroll through the list

### Expected behavior

The scroll to be smooth all through the list

### Actual behavior

The scroll functionality stops after some seconds (roughly 2 seconds)

### uBlock Origin version

uBlock Origin 1.43.0

### Browser name and version

Version 102.0.5005.115 (Official Build) (64-bit)

### Operating System and version

Windows 11 Pro 21H2 22000.739

**Comment by gwarser** [comment]
Can be related https://github.com/uBlockOrigin/uBlock-issues/issues/2124

Check in Chrome 103.
