### ISSUE TITLE
crichd.tv: breakage

### ISSUE THREAD

**Issue by rusegithub** [uBlockOrigin/uBlock-issues#2154]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://crichd.tv/england-vs-new-zealand-test-live-streaming`

### Category

breakage

### Describe the issue

It's a popular sports streaming site.

It works fine when uBlock is disabled. 

But even if I "allow" [green] everything that shows up when uBlock is turned off, and then turn uBlock back on again and refresh, the stream won't play.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Firefox: 101
filterset (summary): 
  network: 117010
  cosmetic: 167207
  scriptlet: 36868
  html: 695
listset (total-discarded, last updated): 
  removed: 
    easylist: null
  added: 
    https://www.fanboy.co.nz/enhancedstats.txt: 2996-10, 3d.22h.41m
    adguard-generic: 65058-4462, 1d.22h.28m
    adguard-spyware: 25786-912, 1d.22h.30m
    adguard-spyware-url: 634-14, 1d.22h.32m
    block-lan: 43-0, 14d.3h.19m
    curben-phishing: 22631-2, 22h.13m
    curben-pup: 231-0, 22h.12m
    adguard-annoyance: 54273-4525, 1d.22h.27m
    adguard-social: 17677-45, 1d.22h.29m
    fanboy-annoyance: 73602-35859, 5d.2h.47m
    fanboy-cookiemonster: 34580-104, 5d.2h.48m
    ublock-annoyances: 4475-8, 1d.22h.31m
    THA-0: 1028-3, 1d.22h.22m
  default: 
    user-filters: 8-0, never
    ublock-filters: 32474-91, 1d.22h.26m
    ublock-badware: 4199-3, 1d.22h.25m
    ublock-privacy: 230-0, 1d.2h.16m
    ublock-abuse: 75-0, 1d.2h.15m
    ublock-unbreak: 1824-4, 1d.22h.24m
    ublock-quick-fixes: 205-0, 22h.11m
    easyprivacy: 27244-10410, 1d.22h.23m
    urlhaus-1: 5435-0, 22h.10m
    plowe-0: 3647-4, 1d.2h.14m
filterset (user): [array of 8 redacted]
trustedset: 
  added: [array of 4 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
hostRuleset: 
  added: [array of 4226 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 28763 ms (selfie)
  maxAssetCacheWait: 10241 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by gorhill** [comment]
The issue is caused by the page using [legacy static properties of RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n):

> The legacy RegExp $1, $2, $3, $4, $5, $6, $7, $8, $9 properties are static and read-only properties of regular expressions that contain parenthesized substring matches.

uBO itself uses RegExp internally to match against the argument to `abort-current-script`, so this ends up overwriting the previous value of `RegExp.$1`.

**Comment by mapx-** [comment]
@gorhill @gwarser 

`acis` seems still "broken"

- go to `leakite.com`
- we already have a filter for this page: `leakite.com##+js(acis, jQuery, ai_adb)` which is not necessary anymore
- check the page code to see there is no `ai_adb` anymore
- in chrome for example you'll see in console:

```
Uncaught (in promise) TypeError: Cannot redefine property: jQuery
    at Function.defineProperty (<anonymous>)
    at RocketLazyLoadScripts._delayJQueryReady ((index):1:7007)
    at RocketLazyLoadScripts._loadEverythingNow ((index):1:4256)
    at RocketLazyLoadScripts._triggerListener ((index):1:3763)
```
error in firefox: `TypeError: can't redefine non-configurable property "jQuery"`

- whitelisting the filter => no such error anymore
- broken functionality (due to jquery breakage) => click any article title => nothing happens
- conclusion => `acis` is wrongly matching an inline script

**Comment by gorhill** [comment]
> `acis` is wrongly matching an inline script

It's not wrongly matching, it's a limitation of JS that you can't use `defineProperty` on a property already defined through `defineProperty`. `acis` needs to use `defineProperty` to trap accesses to `jQuery`. The exception is thrown when the site's own code tries to redefine already redefined `jQuery`:

    Object.defineProperty(window, "jQuery", {

**Comment by mapx-** [comment]
Oh, now I got it. I guess nothing can be done in these cases.

**Comment by mapx-** [comment]
> acis needs to use defineProperty to trap accesses to jQuery

@gorhill could the scriptlet first search for the second parameter and only if finds it use `defineProperty` on the first one ?

**Comment by gorhill** [comment]
The search is triggered when the first parameter is accessed. There can be no search being triggered if no access is detected -- the second parameter is just a pattern to search for, no a specific property to trap.

**Comment by Yuki2718** [comment]
IDK if related, but on `https://spigotunlocked.org/` while `spigotunlocked.org##+js(acis, document.createElement)` or `spigotunlocked.org##+js(acis, document.createElement, /.*/)` works, almost any words within the same inline script such as `spigotunlocked.org##+js(acis, document.createElement, ad)` fails.

**Comment by gorhill** [comment]
> However is working fine if I add Configurable attribute: true in the acis scriptlet

Consequence of doing this is to prevent uBO's injected code from working if the property is redefined by the page, equivalent of removing the filter.

**Comment by rusegithub** [comment]
Thank you, everyone, very much. I did not expect so may answers. 

Truthfully, I don't understand a word of most of what you've all written but the answer given in the first reply by @Procyon-b (quoted below) seems to work. So thank you especially to Procyon-b.

> It's caused by a filter in "AdGuard Base" Add this filter:
> 
> ```
> noob4cast.com#@#+js(abort-current-script, document.createElement, delete window)
> ```
