### ISSUE TITLE
uBlock extension causes no webpages to load

### ISSUE THREAD

**Issue by KayTwenty** [uBlockOrigin/uBlock-issues#2155]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock Origin doesn't load any webpages on Google Chrome when having the extension on.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Turn on the extension
2. Navigate or search any webpage. 

### Expected behavior

Loads the website normally.

### Actual behavior

Constantly loads forever. 

### uBlock Origin version

1.43.0

### Browser name and version

Google Chrome Version 103.0.5060.53 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 21H2

**Comment by gwarser** [comment]
Can you access uBO dashboard? Do you have "Suspend network activity until all filter lists are loaded" option selected in "Filter lists" tab? Can you share troubleshooting information (popup -> chat icon -> click on "Troubleshooting Information")?

**Comment by KayTwenty** [comment]
Yep, the "Suspend network activity until all filter lists are loaded" option was selected. Thanks for the help!

**Comment by J2TEAM** [comment]
I have the same issue and I can't even go to uBlock Dashboard.

![image](https://user-images.githubusercontent.com/5250117/176063726-70d5ccef-67c1-4e87-80ea-1df0147538c8.png)

**Comment by gwarser** [comment]
Reinstall uBO.

**Comment by J2TEAM** [comment]
> Reinstall uBO.

I reinstalled and everything worked. However, is it due to some recent update? Because I have been using uBlock for many years and this is the first time it encountered this error.

**Comment by gwarser** [comment]
Likely Chrome storage issue.

**Comment by gorhill** [comment]
The dashboard page is not even loaded by the browser as per your screenshot, so this suggests a browser issue.
