### ISSUE TITLE
[Feature Request] $removeheader

### ISSUE THREAD

**Issue by mtxadmin** [uBlockOrigin/uBlock-issues#2156]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Is it possible to implement $removeheader parameter?

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeheader-modifier

Related issues, discussions and docs:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1663
- https://github.com/gorhill/uBlock/issues/3604
- https://github.com/uBlockOrigin/uAssets/issues/8542
- https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#header (experimental)
- https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#response-header-filtering (seems to be new $queryprune -> [$removeparam](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam) ? And there are only four headers can be removed)

### A specific URL where the issue occurs

*

### Steps to Reproduce

*

### Expected behavior

HTTP headers removed
(or even replaced?)

### Actual behavior

HTTP headers stay as is

### uBlock Origin version

*

### Browser name and version

*

### Operating System and version

*

**Comment by krystian3w** [comment]
> https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#response-header-filtering (seems to be new $queryprune -> [$removeparam](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam) ? And there are only four headers can be removed)

No, response header is rare used without(/ not as) removeparam:

https://github.com/uBlockOrigin/uAssets/blob/aad4b9bce0dc0a9505176b65d92ba371905dad82/filters/filters-2021.txt#L1742-L1743

https://github.com/uBlockOrigin/uAssets/blob/aad4b9bce0dc0a9505176b65d92ba371905dad82/filters/filters-2021.txt#L4237-L4238

https://github.com/uBlockOrigin/uAssets/blob/aad4b9bce0dc0a9505176b65d92ba371905dad82/filters/filters-2021.txt#L4360-L4361

**Comment by gwarser** [comment]
What is YOUR issue, and how it can be reproduced?

**Comment by HardenedSteel** [comment]
why this issue is closed? the issue is ublock origin doesn't have `$removeheader`
