### ISSUE TITLE
webrtc does not blocked with ublock in firefox and chromium

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uBlock-issues#2162]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

i have tried https://mullvad.net/en/check/
and it is leaking webrtc requests i have tried with adguard extension which can block webrtc i have checked already hence i think it is a bug or so.

### A specific URL where the issue occurs

https://mullvad.net/en/check/

### Steps to Reproduce

1. enable ublock after download and check block webrtc
2. go this site https://mullvad.net/en/check/ tried with other sites and confirm the leak
3. disable ublock and enable adguard extension and enable block webrtc (disable webrtc requests)
4. go this site and check https://mullvad.net/en/check/

### Expected behavior

in both case webrtc should be blocked for those use vpn it is important to block webrtc request which can technically reveal your ip.

### Actual behavior

it does not block webrtc.

### uBlock Origin version

1.43

### Browser name and version

firefox-android-102.2  ungoogled-chromium_103.0.5060

### Operating System and version

android-11/12 fedora36/arch/ubuntu22.04/21.10 macos-12.4

**Comment by holequantum** [comment]
i was using vpn and without vpn in both case it was leaking.
ISP provided ip.
i have tried with brave and bromite turning off webrtc it blocks that ip leak.
with firefox and chromium using adguard it blocks the webrtc requests but with ublock it does not you can check it yourself.

**Comment by krystian3w** [comment]
Mobile Chromium forks still isn't supported.

You must reproduce this into Firefox DayLight 79+.

**Comment by krystian3w** [comment]
Also uBo have only:

https://github.com/gorhill/uBlock/wiki/Resources-Library#nowebrtcjs-

**Comment by krystian3w** [comment]
Also uBo have only:

https://github.com/gorhill/uBlock/wiki/Resources-Library#nowebrtcjs-

AdGuard also reccomend scriptlet instead network filtering:

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#webrtc-modifier

**Comment by holequantum** [comment]
> 

i was not talking about mobile chromium it was in my linux system.
and for firefox it was both android and linux both

**Comment by holequantum** [comment]
> 

checked webrtc is leaking but not with adguard.

**Comment by gorhill** [comment]
>  was using vpn and without vpn in both case it was leaking.
> ISP provided ip.

You are using an extension-based VPN, which have their limitations. This does not occur with a real, system-wide VPN solution. If you still want to use an unreliable extension-based VPN which does not include its own webrtc-leak prevention (a competent extension-based VPN should have one such option), you can use the following filter in uBO:

    *##+js(nowebrtc)

I suggest you use a more comptent extension-based VPN if you do not want to use a system-wide VPN.

**Comment by holequantum** [comment]
> > was using vpn and without vpn in both case it was leaking.
> > ISP provided ip.
> 
> You are using an extension-based VPN, which have their limitations. This does not occur with a real, system-wide VPN solution. If you still want to use an unreliable extension-based VPN which does not include its own webrtc-leak prevention (a competent extension-based VPN should have one such option), you can use the following filter in uBO:
> 
> ```
> *##+js(nowebrtc)
> ```
> 
> I suggest you use a more comptent extension-based VPN if you do not want to use a system-wide VPN.

no i am using proton vpn with paid plus plan.
i have checked with ivpn also when i was abroad.
so please don't make it invalid i can provide you more info about this

**Comment by gorhill** [comment]
> so please don't make it invalid i can provide you more info about this

That sort of issue has always misdiagnosis by the reporter, I am no longer going to waste my time on these, especially that you fail to provide the troubleshooting information, and your GitHub account is days old, suggesting yet another invalid drive-by issue.

First, uBO on Firefox for Android has a setting to disable WebRTC. Second, "ungoogled-chromium" is is personal build and not officially supported by uBO, I can't vouch that such build is devoid of issues.

**Comment by gorhill** [comment]
Actually, there has to be a definitive stop to all these invalid drive-by webrtc issues with poor repro steps, so here is the new rule in place:

Do no open issues with WebRTC, uBO is not a VPN/proxy tool, and your WebRTC issues with regard to VPN/proxy tools need to be reported to your VPN/proxy software.
