### ISSUE TITLE
Generic 3rd-party switch does not indicate 3rd-party scripts and frames are blocked

### ISSUE THREAD

**Issue by lhindir** [uBlockOrigin/uBlock-issues#2171]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

According to https://github.com/gorhill/uBlock/issues/484#issuecomment-120689070, using the dynamic filtering matrix to block generic 3rd-party requests includes 3rd-party scripts and frames on the backend, but the UI does not reflect this by having the scripts and frames rows inherit the red or gray fills.

### Steps to Reproduce

1. Block 3rd-party requests locally or globally using the matrix UI
2. Note the 3rd-party scripts and frames rows do not inherit the red fill

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 102.0

**Comment by gorhill** [comment]
> Note the 3rd-party scripts and frames rows do not inherit the red fill

Yes by design: filling in red would suggest all is being blocked when it's only 3rd-party frames and/or 3rd-party scripts. Other types of resources are not being blocked.

I do agree that the block rules should be conveyed somehow, and that is <https://github.com/gorhill/uBlock/issues/544>. I did some work on this months ago (using partially filled cells), but I was not satisfied with the results, so still an open issue.

**Comment by lhindir** [comment]
> > Note the 3rd-party scripts and frames rows do not inherit the red fill
> 
> Yes by design: filling in red would suggest all is being blocked when it's only 3rd-party frames and/or 3rd-party scripts. Other types of resources are not being blocked.

I’m confused. I’m referring to using the row simply labeled “3rd-party” to block or no-op all 3rd-party requests. Based on the comment I linked, it looks like that action includes blocking 3rd-party frames and scripts, but the UI does not reflect it.
![Screenshot from 2022-07-14 11-36-14](https://user-images.githubusercontent.com/20233645/179034369-b8cf748d-b42e-49de-9ca0-6b3283665d65.png)

Shouldn’t the rows labeled “3rd-party scripts” and “3rd-party frames” have the same translucent red fill indicating inheritance that the bottom rows do?

**Comment by gorhill** [comment]
Ok I see what you mean, I misunderstood.

**Comment by lhindir** [comment]
Maybe it goes without saying, but thank you for your work!
