### ISSUE TITLE
[enhancement] Adding table headers to dynamic filter panels

### ISSUE THREAD

**Issue by chaosky** [uBlockOrigin/uBlock-issues#2173]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I don't use 'Dynamic filtering pane' very often, the frequency is about once a week. Every time I open 'Dynamic filtering pane' to create a rule, I'm not sure what the second and third columns, which one is a global rule and which one is a local rule, the "-" sign and the "+" sign mean? This time I will open the [wiki](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) to check the definition of UI.

So, I suggest adding table headers to the second and third columns to show the simple meaning of each column, so that there is no need to check the wiki every time.

Something like the following:

```
+----------------+-----------------+-----------------+
|                |     global      |       local     |
|                | allow  | block  | allow  | block  |
-----------------------------------------------------+
|         all    |                 |                 |
|         images |                 |                 |
|      3rd-party |                 |                 |
|      ...       |++         --    |++        -      |
+----------------+-----------------+-----------------+
```

### A specific URL where the issue occurs

https://github.com

### Steps to Reproduce

irrelevant

### Expected behavior

irrelevant

### Actual behavior

irrelevant

### uBlock Origin version

1.43.0

### Browser name and version

irrelevant

### Operating System and version

irrelevant

**Comment by gothic-bum** [comment]
> ### Prerequisites
> 
>     * [x]  I performed a cursory search of the issue tracker to avoid opening a duplicate issue

https://github.com/uBlockOrigin/uBlock-issues/issues/1296

**Comment by chaosky** [comment]
Addendum: There are tooltips on the cell  gorhill/uBlock#840
