### ISSUE TITLE
Latvian List has changed its subscription URL

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#2176]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

(*Not* to be confused with https://github.com/gorhill/uBlock/pull/3868, since this time around it's the list's maintainer himself, @anonymous74100, that has changed his hosting site.)

Latvian List's maintainer has announced at https://forums.lanik.us/viewtopic.php?t=47717-latvian-list-moved-to-github that Latvian List's new official main link is https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt, which replaces their old NotABug link, a change that should be reflected by replacing https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L564-L565. He seems unsure in his announcement how to reach out to non-ABP adblockers about it, so I'll do it for him.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/assets/assets.json

### Steps to Reproduce

None that I'm aware of.

### Expected behavior

`assets.json` uses the new GitHub links for Latvian List.

### Actual behavior

As of the 17th of July 2022 10:44 UTC, `assets.json` uses the NotABug links for Latvian List, which were deprecated a couple days ago.

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 103.0.5060.114 x64

### Operating System and version

Windows 11 21H1 x64

**Comment by anonymous74100** [comment]
Thanks for creating this issue for me!
