### ISSUE TITLE
cloud sync settings does not work for the  brave browser

### ISSUE THREAD

**Issue by baaannnaaannn** [uBlockOrigin/uBlock-issues#2177]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

cant sync ublock origin settings from cloud

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#about.html

### Steps to Reproduce

install browser
install ublock origin
try to sync settings

### Expected behavior

the settings are synchronized

### Actual behavior

cant sync ublock origin settings from cloud

### uBlock Origin version

1.43.0

### Browser name and version

brave 103.0.5060.114

### Operating System and version

windows 8.1

**Comment by gorhill** [comment]
Given that sync works fine with Chromium and Firefox, how exactly did you come to the conclusion that the issue is within uBO? Please, provide all the details of your investigation.

**Comment by CaledoniaProject** [comment]
@gorhill How does sync between multiple devices work? I'm using chrome and the new computer won't load the settings from previous computer.

**Comment by gothic-bum** [comment]
> How does sync between multiple devices work? I'm using chrome and the new computer won't load the settings from previous computer.
  
It is explained in the wiki:  
https://github.com/gorhill/uBlock/wiki/Cloud-storage
