### ISSUE TITLE
Ublock origin crashes on firefox nightly(104)

### ISSUE THREAD

**Issue by xiaozixun** [uBlockOrigin/uBlock-issues#2178]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

As long as UBO is installed, firefox nightly(104) will definitely quit.
（I don't know how to use Firefox Profiler on my phone.）

### A specific URL where the issue occurs

anywhere

### Steps to Reproduce

1.Install firefox nightly(104)
2. Add custom add-ons
3.Install UBO
4.firefox nightly(104) exit

### Expected behavior

UBO can be used normally

### Actual behavior

firefox nightly(104) exit

### uBlock Origin version

1.43.0

### Browser name and version

firefox nightly 104.0a1

### Operating System and version

maybe android 10？ (Huawei NOH-AN01 HarmonyOS 2.0.0 )

**Comment by Nojuuu** [comment]
https://github.com/mozilla-mobile/fenix/issues/26062

**Comment by gwarser** [comment]
Good to know. Report back if it isn't fixed in Firefox beta.
