### ISSUE TITLE
`uiStyles` in Advanced Settings don't work for popup

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#2182]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Under Advanced Settings you can add `uiStyles`, which I did. 
 
But for some reason my adjustment of the popup didn't work 

I put in 
```
#main{width: fit-content; min-width: 0px;} .fa-icon{padding: 0 0.01em;} #hostname{display: none; line-height: 120%;} #switch{font-size: 700%;} .toolRibbon{background-color: var(--surface-2); margin: 10px 0 0 0;} .toolRibbon .tool{font-size: 1.1em; min-width: 25px; fill: var(--ink-4);} :root:not(.mobile) .toolRibbon .tool, :root.mobile body.no-tooltips .toolRibbon .tool, :root.mobile body[data-ui~="-captions"] .toolRibbon .tool {padding: 0.5em 0;} #basicStats{margin: 10px 10px -10px 10px;} .itemRibbon{column-gap: 5px; display: flex; background-color: #444; color: #bbb; font-size: smaller; margin: 0; justify-content: center;}
```

In issue #2106 I was told the following: (https://github.com/uBlockOrigin/uBlock-issues/issues/2106#issuecomment-1135994223)
> > @gorhill Without repeating the thinks you and the people above stated in the conversation I personal like the old UI, but as it will removed i would like to change the new UI. In the wiki it says that in your advanced settings you can change the popup menu by changing styles under the option uiStyles. However, it didn't work for me to change the size of the power button. Is that possible to change yourself or not?
> 
> The wiki doesn't explain, but you NEED to know the source for that. You can access it by bringing up the UI, right clicking in it and clicking "View Page Source". In there you can CTRL + Left Click the Stylesheet links (CSS) to get to the real meat on the bone for the uiStyles. That's how I found how to fix the tooltip myself.

As said above, my adjustments didn't work. 

| Expected behavior | Actual behavior| 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/81161435/180380831-5509d510-6d1d-486e-b3e2-6a8ed94a36b3.png) | ![image](https://user-images.githubusercontent.com/81161435/180380977-5b885716-f08f-47d2-b7a5-e758a79e4dd2.png) | 

<details><summary> uBlock info </summary>

```
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 70732
  cosmetic: 46908
  scriptlet: 17497
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2996-10, 23m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal%20List%20(uBo).txt: 2223-0, 23m
  default: 
    user-filters: 225-0, never
    ublock-filters: 32266-94, 23m
    ublock-unbreak: 1835-10, 23m
    easylist: 68713-157, 23m
    easyprivacy: 27432-196, 23m
filterset (user): [array of 170 redacted]
trustedset: 
  added: [array of 12 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 7 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  popupPanelLockedSections: 35
  popupPanelHeightMode: 1
  uiStyles: #main{width: fit-content; min-width: 0px;} .fa-icon{padding: 0 0.01em;} #hostname{display: none; line-height: 120%;} #switch{font-size: 700%;} .toolRibbon{background-color: var(--surface-2); margin: 10px 0 0 0;} .toolRibbon .tool{font-size: 1.1em; min-width: 25px; fill: var(--ink-4);} :root:not(.mobile) .toolRibbon .tool, :root.mobile body.no-tooltips .toolRibbon .tool, :root.mobile body[data-ui~=\"-captions\"] .toolRibbon .tool {padding: 0.5em 0;} #basicStats{margin: 10px 10px -10px 10px;} .itemRibbon{column-gap: 5px; display: flex; background-color: #444; color: #bbb; font-size: smaller; margin: 0; justify-content: center;}
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 9253 ms
  maxAssetCacheWait: 835 ms

```

</details>

### A specific URL where the issue occurs

popup menu

### Steps to Reproduce

1. Go to Advanced Settings
2. Put after `uiStyles` 
```
#main{width: fit-content; min-width: 0px;} .fa-icon{padding: 0 0.01em;} #hostname{display: none; line-height: 120%;} #switch{font-size: 700%;} .toolRibbon{background-color: var(--surface-2); margin: 10px 0 0 0;} .toolRibbon .tool{font-size: 1.1em; min-width: 25px; fill: var(--ink-4);} :root:not(.mobile) .toolRibbon .tool, :root.mobile body.no-tooltips .toolRibbon .tool, :root.mobile body[data-ui~="-captions"] .toolRibbon .tool {padding: 0.5em 0;} #basicStats{margin: 10px 10px -10px 10px;} .itemRibbon{column-gap: 5px; display: flex; background-color: #444; color: #bbb; font-size: smaller; margin: 0; justify-content: center;}
```
3. Click on uBlock extension button
4. See nothing has changed with the original popup

### Expected behavior

The popup to change
<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/81161435/180380367-1ce50b0f-f65c-4bc7-9726-4702923fb436.png)

</details>

### Actual behavior

Popup didn't change
<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/81161435/180380474-419a9b5d-8d64-4f92-8748-659aa14e9bed.png)

</details>

### uBlock Origin version

1.43.0

### Browser name and version

MS Edge 103

### Operating System and version

Windows 10 22H1

**Comment by krystian3w** [comment]
That isn't css declaration(s) but full-fledged css stylesheet.

IMO for now not all can by converted into declarations.

**Comment by gorhill** [comment]
You are trying to assign a stylesheet where only [CSS declarations](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/CSS_Declaration) are allowed. [The documentation](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uistyles):

> It is the responsibility of the user to ensure the value of `uiStyles` contains valid CSS property declarations. uBO will assign the value to `document.body.style.cssText`.
