### ISSUE TITLE
Protect uiStyles before hide main `<body>`?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2186]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

- fail by write own css declaration or
- malware infection in shared uBo config on the Internet (e.g. own private http(s) server and user use Firefox and Chromium so no possible use share to addon store cloud)

### A specific URL where the issue occurs

uBo interface

### Steps to Reproduce

`uiStyles display: none`

 or many other options like:
 `opacity`, `visibility`, `position`, `transform`, firefox [`scale`](https://developer.mozilla.org/en-US/docs/Web/CSS/scale) and maybe many other like `user-select`, `pointer-events`.

Maybe possible use same/similar mechanism to protect picker/zapper.

### Expected behavior

body still visible

### Actual behavior

body are hidden

### uBlock Origin version

1.43.1b8

### Browser name and version

Firefox 103

### Operating System and version

Windows 10

**Comment by u-RraaLL** [comment]
Users aren't supposed to use shared configs. And it's up to them to test the declarations they include in `uiStyles`.

> I make no guarantee regarding `uiStyles` (or any advanced setting -- "those settings may change or be removed in the future"), if some customizations in there are found to interfere negatively, it's for the user to address, I can't test all combinations of potentially existing advanced customizations every time I change something in uBO. <= [gorhill on reddit](https://www.reddit.com/r/uBlockOrigin/comments/suskqp/comment/hxgo8wc/)

**Comment by krystian3w** [comment]
so copy to draf of wiki

**Comment by krystian3w** [comment]
So copy to draft of wiki.
