### ISSUE TITLE
Add $strict-blocking alias for $document option

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#219]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This is a suggestion to add a `$strict` alias for the `$document` static option. As an alias, it does the exact same thing as the existing behavior.

The reason is clarity of communicating what the option does for users, like in #216 . As stated in that issue, strict blocking is unique to uBO so there's no reason to just limit ourselves to a different interpretation of the inherited ABP syntax. (Of course $document would still be supported as-is.)

**Comment by joey04** [comment]
Just a follow-up thought: perhaps $strict looks too similar to $script. So the alias could be `$strictblocking` to be very visually distinct. This would also be the same name as the per-site switch (minus the dash).

**Comment by joey04** [comment]
I like the longer, much more distinct name better so changing the issue title.

**Comment by uBlock-user** [comment]
It can't be helped if users don't ever read up the wiki, no amount of adding directives will help take care of that. Also, you don't even need to use `$document` to enforce strict-blocking. Just add `example.com` in _My Filters_ and strict-blocking will come into effect. 

At the end of the day, even after adding `$strict-blocking`, there's no gurantee that the user will no have issue like mentioned in #216. All you would be doing by adding this directive would be to facilitate one more way of enforcing strict-blocking which I don't think is necessary given how easy it is to that currently.

**Comment by gorhill** [comment]
> It can't be helped if users don't ever read up the wiki, no amount of adding directives will help take care of that.

Yeah, we are not going to keep making uBO's code base ever complicated in the name of mitigating every single issue opened by people because of unclear documentation or failing to read the documentation. For that other issue, a bit of extra documentation is sufficient.

**Comment by joey04** [comment]
I must admit, I never made a $document rule until a few minutes ago, just to see what it does. For the way I use the tool it's completely useless, given that the strict blocking heuristic for plain hostname rules is what matters. If anything, it would only be a nuisance, because I sometimes paste blocked URLs in a new tab to view them (scripts or frames). But $document inhibits that.

So, anyways, I should've played with it a bit myself before making this suggestion. I was honestly just trying to be helpful based on what I read in #216. (But clearly that guy doesn't know rule syntax that well, so the counterarguments you guys made here are definitely the most important considerations. I agree with declining this.)

**Comment by joey04** [comment]
Now I realize this issue is actually fundamentally invalid. $document is for the main frame, which is a request type akin to $subdocument, $image, etc. So aliasing an HTML document type to $strict-blocking is actually a misnomer.

It's already internally consistent in uBO. (But like you guys said, this could be documented a little better.) At least I now have clarity on this particular matter.

**Comment by joey04** [comment]
As for documentation, here's how I would rewrite the Static Syntax wiki page. Basically, the explanation of `$document` needs to be much simpler and should consolidate the 2 places it's mentioned into a single one, like this:

> $document targets the main frame (a.k.a. the root document) of a web page. For blocking rules, it is usually unnecessary because uBO has a unique [strict blocking feature](https://github.com/gorhill/uBlock/wiki/Strict-blocking) for plain hostname rules (like the ones in Peter Lowe or the Malware lists) when applied to the main frame of a web page. For example, the rule `example.com` when applied to a main frame will prevent any connection to that website and display the strict blocking warning page instead.

> Note that `$document` cannot be used with an allow rule (`@@`). <Then insert the existing text about acceptable ads, whitelisting, etc.>
