### ISSUE TITLE
uBO doesn't load Fanboy's Social uBO section

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#2191]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When using Fanboy's Social list in uBO, it's uBO section won't be loaded. Fanboy's Social does have `!#include` so it should load properly.

Here's Fanboy's Social list specific hide list `https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_social_specific_hide.txt` at the end of the list, there's the pre-parsing directive:

![kuva](https://user-images.githubusercontent.com/17256841/181994572-c921fe37-5d53-4620-aa8c-633d7619f62d.png)

Direct link to the uBO-specific list: 
`https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_social_specific_uBO.txt`

When viewing Fanboy's Social in uBO's asset viewer, there's a strange space between `!` and `#include`... maybe that's part of the issue?

![kuva](https://user-images.githubusercontent.com/17256841/181994655-02a47de9-b8b2-4f5a-bca7-8c4d25b4682a.png)

But there's no space in the actual list...

### A specific URL where the issue occurs

`govtrack.us`

### Steps to Reproduce

1. Activate Fanboy's Social list in uBO (disable the main Annoyance list if you're using it, just use the Social list).
2. Go to `govtrack.us`

### Expected behavior

uBO would load `govtrack.us` specific rules:

`govtrack.us##.modal-backdrop`
`govtrack.us##body:style(overflow: auto !important;)`

### Actual behavior

They are not loaded

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> there's a strange space between `!` and `#include`... maybe that's part of the issue?

Yes, there should be no space, [the documentation](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#include-file-name) does say:

> The `!#include` directive allows to import another filter list ...

Nowhere is it said that it's allowed to have a space after `!`.

**Comment by peace2000** [comment]
I tried older and very old versions of uBO as well and they too generate that extra space in Fanboy's Social.

**Comment by gorhill** [comment]
> I tried older and very old versions of uBO

To be clear, the issue is not with uBO, the issue is with the list itself: <https://easylist.to/easylist/fanboy-social.txt>.

**Comment by peace2000** [comment]
> > I tried older and very old versions of uBO
> 
> To be clear, the issue is not with uBO, the issue is with the list itself: https://easylist.to/easylist/fanboy-social.txt.

But in Github (isn't the GIthub file the source link?) There isn't a space:

`https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_social_specific_hide.txt`

?

**Comment by peace2000** [comment]
@ryanbr ?

**Comment by krystian3w** [comment]
Bug in `FOP.py` maybe?

Also supplement existing in easylist domain?

**Comment by peace2000** [comment]
Yeah apparently not uBO bug after all. Sorry!
