### ISSUE TITLE
Shortcuts are now missing in the newer versions, where did they go ?

### ISSUE THREAD

**Issue by leet0rz** [uBlockOrigin/uBlock-issues#2192]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Shortcuts/hotkeys missing, tab gone.

### A specific URL where the issue occurs

in options

### Steps to Reproduce

Open settings
its gone.

### Expected behavior

to see the shortcut tab

### Actual behavior

Not seeing the shortcut tab anymore

### uBlock Origin version

1.43.0

### Browser name and version

firefox 103.0

### Operating System and version

windows 10

**Comment by gothic-bum** [comment]
https://github.com/gorhill/uBlock/commit/6836809aad965cdf0f923558df95d263dd48ed02

> By default uBO assumed the Shortcut pane was needed,
> unless it found the current version of FF was higher
> than 73. This commit reverses the test, it assumes
> the Shortcut pane is not needed, unless the current
> version is lower than 74.

**Comment by krystian3w** [comment]
Also don't try enforce visible TAB or found HTML by malform moz-extension URL (browser don't save changes).

**Comment by leet0rz** [comment]
> This is normal behavior per: [gorhill/uBlock@6836809](https://github.com/gorhill/uBlock/commit/6836809aad965cdf0f923558df95d263dd48ed02)
> 
> > By default uBO assumed the Shortcut pane was needed,
> > unless it found the current version of FF was higher
> > than 73. This commit reverses the test, it assumes
> > the Shortcut pane is not needed, unless the current
> > version is lower than 74.
> 
> Keyboard shortcuts are configured as described in the wiki: https://github.com/gorhill/uBlock/wiki/Keyboard-shortcuts

If you look at the firefox gif in the link you've sent to me you can see that it is not the case anymore:
Right clicking it:
![N8djSnR](https://user-images.githubusercontent.com/29175192/182251171-e6d38f77-c323-475c-8f39-3625013ff0d3.png)
Opening manage:
![V3tJiyI 1](https://user-images.githubusercontent.com/29175192/182251220-f1717420-36ee-4f6a-9ccf-4bba78e4514f.png)

**Comment by krystian3w** [comment]
You should click higher, (so don't bannish gif's) on ⚙️ (gear):

https://user-images.githubusercontent.com/886325/83352569-a9cf5280-a34c-11ea-9e84-9d24c40430ec.gif

![animation](https://user-images.githubusercontent.com/35370833/182258333-b0baae4b-7e4f-452d-a803-630cdd283159.png)


https://user-images.githubusercontent.com/35370833/182259013-5009fd61-befd-4110-a453-64f8b03dfe5b.mp4

**Comment by leet0rz** [comment]
> [#2192 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/2192#issuecomment-1201752830): You should click higher, (so don't bannish gif's) on ⚙️ (gear):
> 
> https://user-images.githubusercontent.com/886325/83352569-a9cf5280-a34c-11ea-9e84-9d24c40430ec.gif
> 
> ![animation](https://user-images.githubusercontent.com/35370833/182258333-b0baae4b-7e4f-452d-a803-630cdd283159.png)
> 	
> 
> apng animation with normal `*.png`. https://caniuse.com/apng
> ezgif-1-05da2a721c.mp4
> 	mp4 form converter

Found it. Thanks. Honestly what a terrible place to move it to, it was perfect where it was lol.
