### ISSUE TITLE
Breakdown during filter assembly RU AdList

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2193]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Today I discovered that the RU AdList filter: `https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt` stopped building properly. When building on the `adblockplus.org` domain, the `js-fixes-experimental.txt` file with rules specific to uBlock Origin was no longer pulled into it: `https://github.com/easylist/ruadlist/blob/master/advblock%2Bcssfixes.txt`

For a while I thought it was some kind of bug on the `adblockplus.org` server, but then I got a response from them that it was not a bug. Eyeo has launched a new system for delivering filter lists, while those that are not recommended for Adblock Plus are not pulled into builds.

As the `css-fixes-experimental.txt` file continued to be pulled into the build, I figured it was because it was originally intended to be used in Adblock Plus (in the future) and has syntax compatible with it `#?#`. Therefore, I remade `js-fixes-experimental.txt` similarly, in the hope that this will be enough: https://github.com/easylist/ruadlist/commit/4c512dbeca560c2a7546c29025fb09e3c2cea8c7

But none of this happened, the file still did not pull up. Then I tried to add the `!#include` directive to the `css-fixes-experimental.txt` file, both in short form: https://github.com/easylist/ruadlist/commit/e2694369160e9b0b9ba22be1c0b160828ec69806 and with the full path: https://github.com/easylist/ruadlist/commit/476247867a655b39f66879c5b204e34d14f87728. In both cases, there was no success.

**I am currently looking for a way to return the** `js-fixes-experimental.txt` **file to the RU AdList filter for uBlock Origin**

As far as I understand, a similar issue has already been discussed here: https://github.com/uBlockOrigin/uBlock-issues/issues/2191

### A specific URL where the issue occurs

mail.ru

### Steps to Reproduce

unknown

### Expected behavior

unknown

### Actual behavior

unknown

### uBlock Origin version

uBlock Origin development build 1.43.1b10

### Browser name and version

Google Chrome 103.0.5060.134

### Operating System and version

Windows 7

**Comment by dimisa-RUAdList** [comment]
@gorhill

**Comment by gothic-bum** [comment]
Per:
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#include-file-name

> The sub-list **must** be in the same directory as the main one, i.e. it is not allowed to load a sub-list which is located outside where the current one resides.

**Comment by dimisa-RUAdList** [comment]
I can create a new RU AdList file on github, like this:
```
[Adblock Plus 2.0]
! Title: RU AdList for uBO only
! Last modified: %timestamp%
! Expires: 2 days (фильтр обновляется автоматически каждые 2 дня)
! Homepage: https://forums.lanik.us/viewforum.php?f=102
!
! Комбинированная версия списков фильтров RU AdList против рекламы
! и экспериментальных списков RU AdList CSS Fixes и RU AdList JS Fixes
! На данный момент нормально работает только в uBlock Origin
!
! --- RU AdList Classic ---
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/adservers.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/first_level.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/general_block.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/general_hide.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/popup.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/specific_antisocial.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/specific_block.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/specific_hide.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/specific_special.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/thirdparty.txt
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/advblock/whitelist.txt
!
! --- RU AdList CSS Fixes---
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/css-fixes-experimental.txt
!
! --- RU AdList JS Fixes---
!#include https://raw.githubusercontent.com/easylist/ruadlist/master/js-fixes-experimental.txt
```
But there are two problems. I need to add AWRL there: `https://github.com/easylist/antiadblockfilters/tree/master/antiadblockfilters`

And the address of this new file must be added to uBlock Origin.

**Comment by gorhill** [comment]
Can you ask EasyList people to host your list?

**Comment by dimisa-RUAdList** [comment]
I can put this file myself here: `https://github.com/easylist/ruadlist`

**Comment by gorhill** [comment]
I am thinking about you create a GitHub worker to stitches the lists and import at the same time `https://github.com/easylist/antiadblockfilters/tree/master/antiadblockfilters`, something like I did to copy content of uAssets to uAssetsCDN ([example](https://github.com/uBlockOrigin/uAssetsCDN/runs/7617991206?check_suite_focus=true)) -- it's just mostly [shell script commands](https://github.com/uBlockOrigin/uAssetsCDN/blob/main/.github/workflows/main.yml) in the end so stitching should be straightforward.

**Comment by gorhill** [comment]
> Is this how it will work?

This won't work, some of the sublists are outside `https://github.com/easylist/ruadlist`.

**Comment by dimisa-RUAdList** [comment]
To be honest, I've never done anything like this. But if I have clear step-by-step instructions, then I'm ready.

**Comment by gorhill** [comment]
Ok, I will try to gather all the steps, not sure I can do that today though. I will list the steps here and add more steps as I identify them:

**Comment by dimisa-RUAdList** [comment]
Maybe I should place the file without AWRL for now, but so that users have scriptlets? Without them, a lot of ads are unblocked, especially on problem sites.

**Comment by gorhill** [comment]
What would be the URL of the list for now?

**Comment by gorhill** [comment]
I get `404: Not Found` with `https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt`.

**Comment by dimisa-RUAdList** [comment]
I didn't know it would be needed right now. Uploaded: https://github.com/easylist/ruadlist/commit/9dabf304fa9b0a3df305505c5a0a606422b42461

**Comment by gorhill** [comment]
You need to use relative URLs:

```
! --- RU AdList Classic ---
!#include advblock/adservers.txt
!#include advblock/first_level.txt
!#include advblock/general_block.txt
!#include advblock/general_hide.txt
!#include advblock/popup.txt
!#include advblock/specific_antisocial.txt
!#include advblock/specific_block.txt
!#include advblock/specific_hide.txt
!#include advblock/specific_special.txt
!#include advblock/thirdparty.txt
!#include advblock/whitelist.txt
!
! --- RU AdList CSS Fixes---
!#include css-fixes-experimental.txt
!
! --- RU AdList JS Fixes---
!#include js-fixes-experimental.txt
```

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/227d01502069410cfa0106c103e370c7ff815283

**Comment by gorhill** [comment]
`assets.json` updates every ~13 days, so it will take a while before everybody is set to the new location.

**Comment by dimisa-RUAdList** [comment]
So that users do not suffer, I have added an unsynchronized AWRL for now.
https://github.com/easylist/ruadlist/commit/a3efea986784caf63869efff4b67beb90a6b8428
https://github.com/easylist/ruadlist/commit/5889e6b97bb651255c552a2b54161f73e819ee10

**Comment by krystian3w** [comment]
IMO not similar due fanboy social at:

easylist-downloads.adblockplus.org/fanboy-social.txt has don't touched `#!include` #1574

**Comment by gorhill** [comment]
Ok here is what I have, but since I can't test these steps, I can only hope I didn't overlook anything and that this will work as intended. I am assuming you are updating your repo through command line using linux.

In `easylist/ruadlist` repo...

Create a new branch, named `gh-pages` (this branch will be empty, this is not a fork of `master`):
- `git switch --orphan gh-pages`
- `touch RuAdList-uBO.txt`
- `git add RuAdList-uBO.txt`
- `git commit -m "Initial commit on gh-pages branch"`
- `git push origin gh-pages`

A GitHub action in `master` will update the list in the `gh-pages` branch each time something changes in `master`
- `git checkout master`
- `mkdir -p .github/workflows`
- `touch .github/workflows/main.yml`
- Paste content of <https://gist.github.com/gorhill/fc3b83502b7ac759af53be7d631510ff> into `.github/workflows/main.yml`
- `git add .github/workflows/main.yml`
- `git commit -m "Add a github action to publish official RuAdList-uBO.txt on gh-pages branch"`
- `git push origin master`

This should cause the following URL to become the official RUADList after the the first time action execute: <https://raw.githubusercontent.com/easylist/ruadlist/gh-pages/RuAdList-uBO.txt>.

You can see the history of workflows at <https://github.com/easylist/ruadlist/actions>.

When all is confirmed working well, I will update the official URL in `assets.json`.

One limitation of this workflow is that it won't trigger when something change in <https://github.com/easylist/antiadblockfilters>, which content is pulled in only at list stitching time, which occurs only when something changes in <https://github.com/easylist/ruadlist>.

**Comment by krystian3w** [comment]
FilterHeroes "Actions" can watch on `easylist/antiadblockfilters` on every day to found diffrences: https://github.com/FiltersHeroes/ScriptsPlayground/blob/master/Readme_VICHS.md (based on cron in CI actions)

But hard use this on local Windows (no have fixes to run in cygwin, Git Bash, WSL/WSL2), recommended is real GNU/Linux environment.

Also this is hawkeye handwritten ecosystem - so he know better how fix bugs if fail install in repo.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14218

**Comment by dimisa-RUAdList** [comment]
@gorhill 
My thanks for creating the guide. I have a busy schedule right now and I can't seem to find a free interval to follow your instructions. I'm going to do this as soon as I can.

But I would like to solve one problem right now. In uBlock Origin Legacy, a new filter location is not pulled up even after multiple filter updates. I think for him this location should be specified separately. Have a look, please.

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/319 https://github.com/gorhill/uBlock-for-firefox-legacy/issues/332

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2200

**Comment by lsh1215225** [comment]
> `https://github.com/easylist/ruadlist/RuAdList-uBO.txt` Or: `https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt`

awesome, https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt is useful

**Comment by gorhill** [comment]
Issue is obsolete, RUAdList now supports differential updates at https://github.com/dimisa-RUAdList/RUAdListCDN
