### ISSUE TITLE
Redirect resource `googlesyndication_adsbygoogle.js` is doing useless operations

### ISSUE THREAD

**Issue by ab-c-d** [uBlockOrigin/uBlock-issues#2198]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

On certain websites the redirect resource `googlesyndication_adsbygoogle.js` takes unexpectedly long time to evaluate.

### A specific URL where the issue occurs

https://fmkorea.com

### Steps to Reproduce

 1. Visit the linked site while using Chrome's performance capturing
 1. Observe the time spent to evaluate `adsbygoogle.js`.

Below is a ubo settings that I've used to reproduce the issue.
```
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98131
  cosmetic: 60102
  scriptlet: 20222
  html: 0
listset (total-discarded, last updated): 
  added: 
    RUS-0: 39670-9, 282d.12h.52m
    ublock-annoyances: 4267-10, 282d.12h.39m
  default: 
    user-filters: 3-0, never
    easylist: 59759-20, 282d.12h.48m
    easyprivacy: 25401-107, 282d.12h.46m
    plowe-0: 3673-549, 282d.12h.44m
    ublock-abuse: 67-1, 282d.12h.42m
    ublock-badware: 3064-56, 282d.12h.35m
    ublock-filters: 29276-137, 282d.12h.33m
    ublock-privacy: 172-5, 282d.12h.31m
    ublock-unbreak: 1661-45, 282d.12h.29m
    urlhaus-1: 12566-0, 282d.12h.26m
filterset (user): [array of 14 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 675 ms
  maxAssetCacheWait: 311 ms
```

### Expected behavior

Given what the script does, it shouldn't take this long.

### Actual behavior

![321](https://user-images.githubusercontent.com/80957138/182743348-c0353857-c7e1-4d9c-a8a3-d377e0db7f86.png)

Excessive time is spent to evaluate the redirected resource. 

I noticed one possible culprit - a weird operation in https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/googlesyndication_adsbygoogle.js#L40.

An `iframe` is appended as a child of an `iframe`, but appending a node to an `iframe` node is no-op AFAIK.
What is the purpose of this line? If there was a valid intention, since it is likely that it has provided no real-world effect, it can be safely removed.

### uBlock Origin version

1.43.0

### Browser name and version

Chromium: 103

### Operating System and version

Windows 11 build 22000.795

**Comment by gorhill** [comment]
The purpose is to make webpages believe ads were actually loaded so as to not trigger anti-adblocker mechanisms.  Given the benefit of not triggering anti-adblockers, I argue that 32 ms is not _"excessive time"_ -- while keeping in mind that this measurement is specific to the site you documented.

If this still bothers you, you can customize your configuration to prevent the redirection with the following filter (with the likelihood of having anti-blockers being triggered on websites):

    @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule

If you choose to use that counter-filter, then if ever you stumble on site with anti-blockers, it will be your duty to solve this on your own, we do not accept filter issues arising as a result of custom filters.

For the future, note that if you want to claim performance issues, you have to share the profiling results, screenshots is not the way to make the case of a performance issue.

Closing as _invalid_.

**Comment by ab-c-d** [comment]
I know that's about anti-adblocker reasons. If you didn't notice, I'm asking why you are appending `iframe` to `iframe`.
I doubt that you have ever tested what this code does in the wild. `iframe`'s content is replaced as soon as it is appended to the body, so it's one's naive daydreaming to expect that iframe appended to an iframe will produce a nested iframe structure. The appendChild call causes CPU cycles for _nothing_.
It's quite surprising to see such a rudimentary error in ubo, and to see it being unnoticed when directly pointed out.

**Comment by gorhill** [comment]
That code was committed in <https://github.com/uBlockOrigin/uAssets/commit/a980cc8240c71d59149237a8b91d0b188b6b320a>, and is purpose was to solve <https://github.com/uBlockOrigin/uAssets/issues/282>. The problematic page in wayback machine is <https://web.archive.org/web/20170129004343/https://www.cpu-world.com/index.html>, and if you inspect the DOM, you will see that back then there was a `googleads.g.doubleclick.net` inside an anonymous iframe (meaning its content could be peeked at by the page's own code):

![Screenshot from 2022-08-04 13-12-39](https://user-images.githubusercontent.com/585534/182911442-a64bc21d-20c9-495b-944f-c9510db969a7.png)

I have no way of knowing whether this sort of layout no longer occurs anywhere on the whole www.
