### ISSUE TITLE
Filter auto-update issue

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uBlock-issues#2199]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Filters except malicious domain lists seem to be up to date, although their version and date of release are old.

### A specific URL where the issue occurs

https://www.google.gr/

### Steps to Reproduce

1. Load my filter subscription settings.
2. Update filters.

### Expected behavior

All filters auto-updating regularly.

### Actual behavior

It seems that no updates are available, although installed filters (except malicious domain lists) remain frozen to their firstly downloaded version, as both clock icon hovering and “show content” option demonstrate. I regularly have to manually clear the cache and then hit the “Update now” button in order to keep them up to date.

### Configuration

[το-ublock-αντίγραφο-ασφαλείας-μου_2022-08-04_10.23.35.txt](https://github.com/uBlockOrigin/uBlock-issues/files/9258030/-ublock-.-.-._2022-08-04_10.23.35.txt)

**Comment by gorhill** [comment]
> seem to be up to date, although their version and date of release are old

How did you determined the "version and date of release"?

**Comment by DimitrisKalaboukas** [comment]
By comparing the version number and release date provided in the “show content” page with those of the txt file stored on the filter URL.

**Comment by DimitrisKalaboukas** [comment]
For instance, this is the installed (supposedly up to date) version of EasyList:
![Show content](https://user-images.githubusercontent.com/101707608/182896167-efe3d5fb-1392-4596-a5f6-ddecb4926ea8.jpeg)
and this is the online one on https://easylist.to/easylist/easylist.txt:
![Online version](https://user-images.githubusercontent.com/101707608/182896355-062e4c3d-e5c9-4a1c-a405-44e91c0f71b5.png)

**Comment by gorhill** [comment]
Yes, the list updates every four days, so of course it's unlikely you will have the absolute latest version. If you do not have any filter issues, then there is no point worrying that you do not have the absolute latest version. If you have filter issues on a given site, than just force a manual update.
