### ISSUE TITLE
UI Zoom In/Out bug

### ISSUE THREAD

**Issue by ialexsilva** [uBlockOrigin/uBlock-issues#220]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When you Zoom In/Out the page of uBlock panel, pop-up UI broken.

### Steps to Reproduce

**1. Go to panel in uBlock and Zoom In/Out page like this:**

![capturar](https://user-images.githubusercontent.com/6363160/45461589-4e71b280-b6da-11e8-8185-2221f81dc09a.PNG)
**2. Open uBlock Pop-Up**

### Expected behavior:

![expected](https://user-images.githubusercontent.com/6363160/45460647-419e9000-b6d5-11e8-81a3-6da1e46ca99d.PNG)

### Actual behavior:

![bug](https://user-images.githubusercontent.com/6363160/45460651-495e3480-b6d5-11e8-9b8f-5db271c81d0e.PNG)

### Your environment

* uBlock Origin version: uBlock Origin 1.16.18
* Browser Name and version: Chrome  v69.0.3497.92
* Operating System and version: Windows 10 x64 1803

**Comment by ialexsilva** [comment]
@gorhill I don't know this is a real bug or is expected.

**Comment by uBlock-user** [comment]
> Go to panel in uBlock and Zoom In/Out page

How to do that ? I can zoom In/Out in Chrome and not in the extension

**Comment by uBlock-user** [comment]
I can reproduce now, you should add those steps in the STR for clarification.

**Comment by uBlock-user** [comment]
The zoom in/out is **enforced** by the browser on the extension, so I doubt if extension can do override or do anything about it, lets see what gorhill thinks though.

**Comment by uBlock-user** [comment]
Same issue with uMatrix too, Chromium specific, not affected on Firefox.

**Comment by uBlock-user** [comment]
Likely to be a duplcaite of https://github.com/gorhill/uBlock/issues/497

**Comment by ialexsilva** [comment]
maybe fix this with popup.css file

`zoom: 100%;`

**Comment by uBlock-user** [comment]
Did you try that ? If that works, it could be used as a workaround.

**Comment by gorhill** [comment]
The browser is doing this not uBO.

**Comment by gorhill** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=849821
