### ISSUE TITLE
Ublock Skips Ads

### ISSUE THREAD

**Issue by lolafur** [uBlockOrigin/uBlock-issues#2200]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Ads started to appear on the site, although I have an active ad blocker and all filters are updated.

### A specific URL where the issue occurs

https://censor.net/en/news/3358462/powerful_explosions_rang_out_in_mykolaiv_occupiers_hit_two_districts_of_the_city_senkevych

### Steps to Reproduce

1. Go to https://censor.net/en
2. Choose a news item and open it
3. Ads appear on the top and sides

### Expected behavior

Expected ad blocking to happen

### Actual behavior

Actual behavior
What actually happened

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 98400
  cosmetic: 67167
  scriptlet: 17565
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 40324-9, 3m
    easylist: 69158-66, 2m
    easyprivacy: 27481-223, 2m
    plowe-0: 3640-782, 2m
    ublock-abuse: 76-1, 2m
    ublock-badware: 4171-92, 2m
    ublock-filters: 32427-146, 2m
    ublock-privacy: 230-3, 2m
    ublock-quick-fixes: 363-62, 2m
    ublock-unbreak: 1851-42, 2m
    urlhaus-1: 5003-0, 2m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1722 ms
  maxAssetCacheWait: 330 ms
```
</details>

**Comment by gorhill** [comment]
Do not report filtering issue here, this is not the place. Use the _"Report an issue on this website"_ button in the popup panel to report filter issues.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2193
