### ISSUE TITLE
Filter List Titles are Misleading

### ISSUE THREAD

**Issue by Robert941** [uBlockOrigin/uBlock-issues#2201]
### Location Referenced

Settings > Filter Lists tab

### Description

"AdGuard Annoyances" is actually AdGuard Annoynaces minus Fanboy Annoyance.

"Adguard Base" is actually AdGuard Base minus EasyList.

These titles can mislead the user into thinking that these are complete AdGuard lists.

### Potential Solutions
1. Update the title to reflect this.
2. Use the complete AdGuard lists since UBO is able to handle filter list overlap.

### Thoughts

I think solution 2 is best since it will simplify the user experience.

Are you aware of any other filter lists that also have this issue?

**Comment by krystian3w** [comment]
AdGuard Annoyances is independent, have own generic rules (rule in AG syntax mean filter line).

**Comment by Robert941** [comment]
@gorhill Could we add a tooltip that instructs the user to enable EasyList with AdGuard Base?

**Comment by krystian3w** [comment]
Maybe unneded cost if somebody see useagek 40/40k filters instead 100+/100+ K.

If you see useful English specific solutions then they can be copied into uAssets (e.g. no covered anti-adblock/ad reinsertion due not reported to anybody from uAssets team).
