### ISSUE TITLE
uBlock Origin inserts #shadow-root with ads to some web pages

### ISSUE THREAD

**Issue by neimovirne** [uBlockOrigin/uBlock-issues#2202]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock Origin inserts #shadow-root with ads to some web pages
dev build from chrome web store fixes this issue
![Screenshot1_1](https://user-images.githubusercontent.com/2023595/183259012-13cc9706-311e-4fc8-910c-2830db3b2d55.png)

### A specific URL where the issue occurs

https://www.epravda.com.ua/news/2022/08/6/690106/

### Steps to Reproduce

1. go to https://www.epravda.com.ua/news/2022/08/6/690106/
2. scroll down a bit to facebook comments plugin and u will see inserted ads above it

### Expected behavior

I expected all ads are deleted from the page by the uBlock

### Actual behavior

Instead of delete the ads on page uBlock inserted more ads

### uBlock Origin version

1.43.0

### Browser name and version

Google Chrome	103.0.5060.134 (Official Build) (64-bit)

### Operating System and version

Windows 11 build 25169.1000

**Comment by gorhill** [comment]
Closing as _invalid_: no, uBO does not insert _"#shadow-root with ads"_. This is a filter list issue, report to the proper filter list maintainers.

**Comment by neimovirne** [comment]
but i installed dev version from google web store and seated up the same filters and this ver doesn't insert any ads

**Comment by gorhill** [comment]
> this ver doesn't insert any ads

You keep saying this, so I will repeat: uBO does not insert ads. This is a filter issue, you likely have an obsolete version of RUAdList, force an update.
