### ISSUE TITLE
remove-class "stay" doesn't prevent re-injection

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2203]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Maybe related: https://github.com/uBlockOrigin/uBlock-issues/issues/1445

> remove-class "stay": This tells the scriplet to stay and act on DOM changes, while the default behavior is to act only once when the document becomes interactive.

### A specific URL where the issue occurs

`soft98.ir`

### Steps to Reproduce

0- Preferably disable uBO Quick-Fixes to prevent interference
1- Go to `soft98.ir`
2- Open inspect element
3- Add `soft98.ir##+js(rc, clean, *, stay)` to My filters.
4- Refresh the page.
5- The "clean" class gets removed by uBO but is instantly injected again by site.

### Expected behavior

uBO should **_abort attempts_** to re-inject classes.
Also it's preferable if uBO could pretend that the re-injection was successful.
### Actual behavior

If the site can re-inject classes then the purpose of remove-class "stay" is defeated entirely.
See:

https://user-images.githubusercontent.com/17685483/183411504-22ac04d2-8aae-40e4-a4c9-f1b6d175f57f.mp4

### uBlock Origin version

1.43.0

### Browser name and version

Firefox 103.0.1

### Operating System and version

Fedora 36 KDE

**Comment by krystian3w** [comment]
File.io no longer host demo/image/video.

Form Polish demo you can also try kill pop-up to select radio station by `rc` instead `aeld`: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2667#issuecomment-1186604538


Also in the past I found war with readd class/attributes so page blink/jumps to delete filter.

**Comment by MasterKia** [comment]
> File.io no longer host demo/image/video (GitHub like MP4 with any codecs).

What do you mean?
GitHub doesn't allow mkv so I used file.io.

**Comment by gwarser** [comment]
Video does not exists. I cannot find `.clean` on the page. Did you tried without the `*` selector? It finds nearly 1k nodes to filter - slow.

**Comment by MasterKia** [comment]
Because they changed "clean" to "cleaner".
Look for "cleaner".
`soft98.ir##+js(rc, cleaner, *, stay)`

I'll reupload the video in an hour.

**Comment by krystian3w** [comment]
Can you check how works this in AdGuard, his scriptlet support loop/ObservedMutator without parameters.

**Comment by MasterKia** [comment]
Video added.

**Comment by MasterKia** [comment]
@krystian3w I tested that filter in AdGuard on Ungoogled Chrmoium, same behavior as the video.
`soft98.ir##+js(rc, clean, , stay)`

**Comment by krystian3w** [comment]
So also no implemented abort injection.

**Comment by MasterKia** [comment]
And?

**Comment by gwarser** [comment]
There is no feature to prevent reinjection. You will need to find the code responsible for this and block it some other way.

**Comment by MasterKia** [comment]
> Find the code responsible for this and block it some other way.

Any help is appreciated.

**Comment by gwarser** [comment]
I'm talking about the `rc` scriptlet itself. It was designed that way to remove classes added after delay, after page was loaded, not to fight against page script reinserting it back.

**Comment by MasterKia** [comment]
What's the fundamental back-end difference between `:remove()` and `remove-class.js` other than "to remove classes added after delay, after page was loaded"?

**Comment by gwarser** [comment]
It's just coincidence. Probably, page script fails when it cannot find the element on which it want to work.

**Comment by gorhill** [comment]
Whatever piles of code I would throw at uBO (while having to keep maintaining it forever) would be pointless given that the site you are giving as an example is bent on working around whatever uBO does. So I prefer to decline given that the feature is meant to address one specific anti-blocker feature at that one specific site; all work which would become pointless as soon as the site works around it.
