### ISSUE TITLE
Restoring settings from backup doesn't update filter lists

### ISSUE THREAD

**Issue by GPery** [uBlockOrigin/uBlock-issues#2204]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] using a new, unmodified browser profile

### Description

I'm also having to deal with #2136, and I figured I'd try to back up settings to a file and restore them next time it happens. As mentioned in passing in https://github.com/uBlockOrigin/uBlock-issues/issues/2136#issuecomment-1158109720, it seems like restoring from a backup file doesn't work for filter lists (even though the `selectedFilterLists` field contains the lists).

Below, under configuration, uBO filled `listset: removed:` with some lists with value `null`, anyone know if this is of significance?

### A specific URL where the issue occurs

moz-extension://*/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Enable some filter lists
2. Back up settings to file
3. Change filter lists
4. Restore settings from file

### Expected behavior

Previous filter lists should override changes.

### Actual behavior

Changes to filter lists remain.

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 102
filterset (summary): 
  network: 0
  cosmetic: 0
  scriptlet: 0
  html: 0
listset (total-discarded, last updated): 
  removed: 
    user-filters: null
    ublock-filters: null
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-unbreak: null
    easylist: null
    easyprivacy: null
    urlhaus-1: null
    plowe-0: null
    ublock-quick-fixes: null
filterset (user): [array of 4 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1730 ms (selfie)
  maxAssetCacheWait: 716 ms
```
</details>

**Comment by gwarser** [comment]
Must be related to #2136 because it works fine on properly working profile.

**Comment by krystian3w** [comment]
Backup profile and copy to Firefox portable.

If reporduce breakege then delete private data (local storage, cookies, passwords, forms history, viewing history).

Maybe this help fix bug.

**Comment by GPery** [comment]
I couldn't reproduce the issue with a new profile. Something interesting I noticed is that uBO doesn't actually restart in the "contaminated" profile. This seems like a much easier debugging starting point.
In the new profile, restoring from file closes the tab, in the dysfunctional profile the tab stays open.
This I can easily reproduce consistently.
Are there any internal uBO logs I can check to see what's going on there specifically?

**Comment by krystian3w** [comment]
Can be used browser console (not devtools):

`firefox.exe -jsconsole`

(Modify manually if you are using GNU/Linux and maOS)

Devtools best use if browser "JavaScript" show nothing.

**Comment by GPery** [comment]
Nothing appears in the console when attempting to reload, I'm afraid.

**Comment by gorhill** [comment]
I can't investigate if I can't reproduce, so this will have to be investigated by someone who has understanding of JS and the tools to debug JS.

**Comment by krystian3w** [comment]
see https://github.com/uBlockOrigin/uBlock-issues/issues/2204, https://github.com/uBlockOrigin/uBlock-issues/issues/2136 https://github.com/uBlockOrigin/uBlock-issues/issues/2221

**Comment by GPery** [comment]
Retrying with uBO in about:debugging inspect + jsconsole open might have some insight - in restoring from file an error occurs:

In uBO console:
```
Uncaught (in promise) Error: An unexpected error occurred undefined  
    restoreUserData moz-extension://2c1d8fb5-a8e2-4184-a283-3c1d4528c1ca/js/messaging.js:1182  
    AsyncFunctionThrow self-hosted:814  
    (Async: async)  
    onMessage moz-extension://2c1d8fb5-a8e2-4184-a283-3c1d4528c1ca/js/messaging.js:1562  
    onPortMessage moz-extension://2c1d8fb5-a8e2-4184-a283-3c1d4528c1ca/js/vapi-background.js:1075  
    onPortConnect moz-extension://2c1d8fb5-a8e2-4184-a283-3c1d4528c1ca/js/vapi-background.js:861  
    apply self-hosted:2733  
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:627  
    asyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:2544  
```

In jsconsole:
```
IndexedDB UnknownErr: ActorsParent.cpp:563 
```
In addition, at some point beforehand is the relevant error:
```
UnknownError: IndexedDB: main/partitioning-exempt-urls list() IndexedDB:  execute() The operation failed for reasons unrelated to the database itself and not covered by any other error code.
```

Unfortunately the line in the IndexedDB source isn't very helpful - https://hg.mozilla.org/mozilla-central/file/tip/dom/indexedDB/ActorsParent.cpp#l563
Seems to be a generic unknown error.
Does this help at all with either this issue or #2136 @gorhill ?
It's looking more like a Firefox issue now, but you're definitely more experienced around that area, so let me know if there's still some hope of debugging this :)

**Comment by gorhill** [comment]
> Uncaught (in promise) Error: An unexpected error occurred undefined

In 1.49.2 I added code to properly handle exceptions, somehow I had never realized exceptions were not caught. The unexpected error will probably still occur (out of control of uBO), but at least uBO should gracefully recover as a result, and in worse case it should at least load the default lists.

**Comment by GPery** [comment]
In that case, do you think I should just open an issue in the Firefox tracker with this information? Or rather wait for 1.49.2 to reach the addon store to easily be able to tell which uBO line triggered the error?
I don't think I ever encountered a Firefox bug before :sweat_smile:

**Comment by stephenhawk8054** [comment]
Can you test with dev build?
