### ISSUE TITLE
Suspend network activity until all filter lists are loaded does not currently seem to work on startup in youtube.

### ISSUE THREAD

**Issue by Iaotle** [uBlockOrigin/uBlock-issues#2205]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I thought the "Suspend network activity until all filter lists are loaded" tick would force Chrome to wait until the extension is loaded to play the video. But when I launch chrome I am unfortunately assaulted immediately by a video ad.

I know this has already been asked before but it wasn't really answered to my satisfaction previously before being closed. Is this issue being worked on? Because the current proposed fix isn't functional.

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=YBUqBk17tAI

### Steps to Reproduce

1. Launch Chrome and have it reopen a saved youtube video
2. Get ad

### Expected behavior

Wait until the filters load before showing the page, and no ads

### Actual behavior

Got ad, had to refresh the page

### uBlock Origin version

1.43.0

### Browser name and version

Google Chrome 104.0.5112.81

### Operating System and version

Windows 11 21H2 22000.832

**Comment by gorhill** [comment]
As said, there is no guarantee this will work, uBO as an extension can't make up for the lack of browser capability.

**Comment by gorhill** [comment]
Additionally, Google Chrome will deprecate MV2 in a few months, so I have no motivation to invest my personal time on issues specific to Chrome.

**Comment by dportvine** [comment]
@gorhill 
> Additionally, Google Chrome will deprecate MV2 in a few months, so I have no motivation to invest my personal time on issues specific to Chrome.

Does your comment mean that uBO won't work on Google Chrome from January 2023?

**Comment by MasterKia** [comment]
@dportvine Yes, it affects every Chromium-based browser.

Microsoft Edge is also going the same route as Google Chrome.

Brave and Vivaldi have their own built-in blocker so they don't/shouldn't care.

Firefox isn't gonna be affected by this change.

More info:
https://github.com/uBlockOrigin/uBlock-issues/issues/338
