### ISSUE TITLE
Adding a CSS selector-based rule using element picker uses the randomly generated attribute system

### ISSUE THREAD

**Issue by 0x416c69** [uBlockOrigin/uBlock-issues#2208]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I just want to clarify that this bug is not only important since randomly generated attributes can be used to detect uBO since it leaves a more obvious footprint but it's an inconsistency in uBO since when you refresh the page with the rule added to your custom list you don't get a randomly generated attribute.

I know that this is necessary for xpath since you don't want/it's not trivial to translate xpath to css selector(s), but in the case of the css selector, it should be using the selector itself in the injected stylesheet.

### A specific URL where the issue occurs

http://www.example.com/

### Steps to Reproduce

1. Enter example.com
2. Open element picker mode
3. Enter this on the text box and create: `##body:style(color:red)`
4. Open inspect element and you can see a randomly generated attribute has been added to body.
5. Refresh the page, the attribute is gone and the injected stylesheet is using the CSS selector directly now.

### Expected behavior

To not use a randomly generated attribute and use the css selector for stylesheet injection when you add a rule in the element picker.

### Actual behavior

Randomly generated attribute is being used for a CSS selector-based filter rule when adding the rule using the element picker tool while when you refresh the page, the injected stylesheet contains the CSS selector instead.

### uBlock Origin version

1.43.0

### Browser name and version

Chrome 103.0.5060.134

### Operating System and version

Proprietary private OS

**Comment by gorhill** [comment]
> To not use a randomly generated attribute

Thatś just how it works -- this occurs only with the element picker. I do not intend to change this.
