### ISSUE TITLE
contentLastModified is buggy

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#221]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The `contentLastModified` var is used by the Panel to only poll for fresh data when it's actually needed. But Pagestore doesn't always update it correctly, so the Panel +/- counts for domain entries will go stale.

This code has been the same for years, though the addition of journaling may be the culprit. (Just a hunch.) For me, a quick fix was simply disable these checks in `hasPopupContentChanged` and callback(true) to get fresh data each time.

This bug only is noticable in the case of keeping the Panel open for long times, which is common for me since I always open it in a new tab. Thus it's really only a niche thing and probably why it's gone unnoticed.

### STR

For regular popup panel, play a long Youtube video.
Click the badge to open the popup right after playing and leave it open. (That means no browser interraction.)
You'll see that `googlevideo.com` connect count won't hit ++ after 10 requests. (Depending on timing of other domains it may hit ++ but it won't hit +++ after 100.)

**Comment by uBlock-user** [comment]
> and leave it open. (That means no browser interraction.)

Didn't take that into account, I can reproduce, if I keep it open.
