### ISSUE TITLE
Disabling Popup for blocked pages

### ISSUE THREAD

**Issue by tardisman833** [uBlockOrigin/uBlock-issues#2214]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

None of the options to modify the behaviour of the popup notifications appears to work. Specifically there doesn't appear to be a working method to disable the ability to add a site to trusted sites when the blocked site notification appears.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

add site to the filters (e.g., youtube.com, www.youtube.com, youtube.com##ytd-app and www.youtube.com##ytd-app).
save changes
modified a number of the advanced settings that are related to notifications and/or popups
save changes
popup notification saying site is block still allows user to add the site to the trusted sites, which circumnavigates the point of blocking the site.

### Expected behavior

When a site is blocked it isn't expected that the user be given the choice to circumnavigate the blocking with 1 or 2 clicks of the mouse. 

### Actual behavior

all sites and/or apps in the my filters list to be blocked, notification that they are blocked can be optional, but it shouldn't allow the user to add the site to the trusted sites to circumnavigate the configuration.

### uBlock Origin version

unknown

### Browser name and version

Chromebook

### Operating System and version

ChromeOS

**Comment by gothic-bum** [comment]
> * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue  

https://github.com/uBlockOrigin/uBlock-issues/issues/243
https://github.com/uBlockOrigin/uBlock-issues/issues/1435
https://github.com/uBlockOrigin/uBlock-issues/issues/1243
  
----
  
> * [x]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior  

https://github.com/gorhill/uBlock/wiki/Strict-blocking

**Comment by gwarser** [comment]
> None of the options to modify the behaviour of the popup notifications appears to work. 

What are you talking about? There are not any popup notifications. If you think about strict blocking page, then it's an independent feature.

>Specifically there doesn't appear to be a working method to disable the ability to add a site to trusted sites when the blocked site notification appears.

There is not any way to add page to trusted sites from strict blocking page, but you can always use big blue power button in uBO popup. There will be no way to block this - you are the user - there will always be a way to disable blocking. You should look for different software if you want to block access to particular pages.

> When a site is blocked it isn't expected that the user be given the choice to circumnavigate the blocking with 1 or 2 clicks of the mouse.

From uBO POW, this is a requirement to give user a choice.

**Comment by pc00per** [comment]
As for #1243 being locked as soon as I mention this feature's importance, gorhill locked the conversation, which shows the disinterest btw. Disagreeing with something is helpful, but censoring the issues by locking them isn't.

**Comment by gorhill** [comment]
I am going to ask to stop commenting all over the place and bringing back to life long resolved issues.
