### ISSUE TITLE
msn.com: ads

### ISSUE THREAD

**Issue by grfxwzdesigner** [uBlockOrigin/uBlock-issues#2215]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.msn.com/`

### Category

ads - 

### Describe the issue

areas I have blocked are now appearing and the elemnt picker and element zapper are no tworking.  When I try to use them the entire page is highlighted.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Firefox: 103
filterset (summary): 
  network: 80464
  cosmetic: 45315
  scriptlet: 17620
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 27-3, never
    ublock-filters: 33157-38, 22m
    ublock-badware: 4180-0, 4d.6m
    ublock-privacy: 247-0, 2d.16h.2m
    ublock-abuse: 76-0, 2d.16h.3m
    ublock-unbreak: 1867-0, 20m
    easylist: 69419-591, 21m
    easyprivacy: 27333-581, 23m
    urlhaus-1: 5190-0, 1d.4m
    plowe-0: 3639-3, 12d.18h.27m
    ublock-quick-fixes: 376-1, 21h.23m
filterset (user): [array of 27 redacted]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 688 ms (selfie)
  maxAssetCacheWait: 427 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    msn.com: 14
    azure.com: 2
    btloader.com: 3
    microsoft.com: 7
    scorecardresearch.com: 1
    yahoo.com: 2
```
</details>

**Comment by gorhill** [comment]
> areas I have blocked

Your description is too vague, there is nothing for me to investigate. Be very specific, provide details about which filter is not working on which exact page (provide URL address) which you say should be working, otherwise I will close as invalid.

**Comment by gothic-bum** [comment]
> * [x]  I did not answer truthfully to **all** the above checkpoints  
  
> PLEASE help!

If you want help – and out of respect for people who are volunteering their time to help with your issue – you should perform all the required steps and provide truthful answers. You should also provide specific examples with the steps necessary to reproduce the issue.  
  
I just tested and was unable to reproduce the issue using the default settings/lists.  
  
Try testing again after you do ALL of the following steps:  
  
Step 1: Create a new browser profile. Do not sync data from a previous profile. Do not make any changes to the default browser settings.
  
Step 2: Install uBO. Do not make any changes to the default uBO settings (no custom filters, no added filter lists, no dynamic filtering, no cloud sync, etc). Do not install any other browser extensions.
  
Step 3: Force an update of all of the default uBO filter lists (click the [*"Purge all caches"*](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button and then click the [*"Update now"*](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now]) button).  
  
Step 4: Do not enable any other network/content blocking (for example: ad/content-blocking software or DNS provider, Pi-hole, local hosts file).

**Comment by JohnyP36** [comment]
I think it has to do with the fact that MSN uses `#shadow-root` to display recommended articles below an articles. Between the blocks with articles are blocks with ads. But because the network requests are blocked those blocks will appear as black.

`https://www.msn.com/nl-nl/gezondheid/medisch/rutte-wil-een-euro-op-de-melkprijs/ar-AA110hNP`

<details> <summary> screenshot </summary>

![image](https://user-images.githubusercontent.com/81161435/186344536-f834af04-cafe-4996-b4f4-6001cfa44ace.png)

</details>  

There are issues in uAssets, but they got declined or closed. See https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+msn

### Also see https://github.com/uBlockOrigin/uBlock-issues/issues/803
*uBlock doesn't support blocking elements within `#shadow-root`*

**Comment by Yuki2718** [comment]
Specific or specific-generic cosmetic filters should work for shatow-root.

**Comment by gorhill** [comment]
This works on my side:

    msn.com##msft-article-card:not(.contentCard)

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2252
