### ISSUE TITLE
AdGuard divvied up annoyance filters

### ISSUE THREAD

**Issue by wavygecko** [uBlockOrigin/uBlock-issues#2217]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

AdGuard [recently divvied up their **Annoyances** list](https://adguard.com/en/blog/new-annoyance-filters.html) into five new lists:

1. **Cookie Notices** — blocks cookie notices on web pages
2. **Popups** — blocks all kinds of pop-ups that are not necessary for websites' operation
3. **Mobile App Banners** — blocks banners that promote mobile apps of websites
4. **Widgets** — blocks third-party widgets: online assistants, live support chats, etc.
5. **Other Annoyances** — blocks elements that do not fall under the popular categories of annoyances

Would it make sense to include these in uBlock Origin in the same way that **EasyList Cookie** and **Fanboy's Social** are included alongside **Fanboy's Annoyance**?

### A specific URL where the issue occurs

https://adguard.com/en/blog/new-annoyance-filters.html

### Steps to Reproduce

N/A

### Expected behavior

Here's what it could look like in `assets.json`:

<details><summary>assets.json</summary>

```json
	"adguard-cookie-notices": {
		"content": "filters",
		"group": "social",
		"off": true,
		"title": "AdGuard Cookie Notices",
		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/18.txt",
		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
	},
	"adguard-popups": {
		"content": "filters",
		"group": "social",
		"off": true,
		"title": "AdGuard Popups",
		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/19.txt",
		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
	},
	"adguard-mobile-app-banners": {
		"content": "filters",
		"group": "social",
		"off": true,
		"title": "AdGuard Mobile App Banners",
		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/20.txt",
		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
	},
	"adguard-widgets": {
		"content": "filters",
		"group": "social",
		"off": true,
		"title": "AdGuard Widgets",
		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/22.txt",
		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
	},
	"adguard-other-annoyances": {
		"content": "filters",
		"group": "social",
		"off": true,
		"title": "AdGuard Other Annoyances",
		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/21.txt",
		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
	},
```

</details>

### Actual behavior

N/A

### uBlock Origin version

1.43

### Browser name and version

Firefox 103

### Operating System and version

Windows 10

**Comment by krystian3w** [comment]
Maybe possible add margin left for list embedded in bigger:

- [ ] AG Annoyances
   - [ ] Cookie Notices
   - [ ] Popups
   - [ ] Mobile app banners
   - [ ] Others Annoyances (undefined in other categories)
- [ ] Fanboy Annoyances
   - [ ] Fanboy Social
   - [ ] Easylist Cookies

**Comment by krystian3w** [comment]
uBo generate classes "checked", so this can be used to disable click on smaller part of list (and stylize input) by only CSS, but don't generate pop-up with information for newbies why selection are disabled (this works better after use JS).

**Comment by gwarser** [comment]
Wasn't this declined few days ago? Déjà vu?

**Comment by krystian3w** [comment]
> Wasn't this declined few days ago? Déjà vu?

On Reddit? We don't have access to slack and uBlock-volunteer team.

**Comment by Yuki2718** [comment]
I proposed the same on internal discussion https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/421 but not declined.

**Comment by krystian3w** [comment]
So maybe missed as weird.

**Comment by krystian3w** [comment]
As public possible read opinion about consideration disable joining files into big one: https://github.com/AdguardTeam/FiltersRegistry/issues/718

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2441

**Comment by krystian3w** [comment]
But can by reverted any time or newer copied to stable.

**Comment by Yuki2718** [comment]
Fanboy added a new [Agegate List](https://secure.fanboy.co.nz/fanboy-agegate.txt).
