### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by yazaman** [uBlockOrigin/uBlock-issues#2218]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Youtube does not work with uBlock, especially with British youtubers. I do not know why.

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=onHF8sLmY9Y

### Steps to Reproduce

I am using uBlock with firefox. 

### Expected behavior

just play the video

### Actual behavior

the video does not play, only seeing the circle rotating

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 81881
  cosmetic: 51813
  scriptlet: 18055
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33215-81, 24m
    ublock-badware: 4237-0, 24m
    ublock-privacy: 247-0, 24m
    ublock-abuse: 76-0, 24m
    ublock-unbreak: 1852-0, 24m
    ublock-quick-fixes: 407-0, 24m
    easylist: 69577-612, 24m
    easyprivacy: 27358-584, 24m
    urlhaus-1: 4669-0, 24m
    plowe-0: 3635-3, 24m
    TUR-0: 8717-67, 24m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 855 ms
  maxAssetCacheWait: 118 ms
```
</details>

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-1194770076
