### ISSUE TITLE
404 Not Found for Firefox Beta uBlock Origin

### ISSUE THREAD

**Issue by UnboltedWork** [uBlockOrigin/uBlock-issues#2219]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Clicking on the link simply says 404 Not Found.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/releases/download/1.44.1b0/uBlock0_1.44.1b0.firefox.signed.xpi

### Steps to Reproduce

1. Go to the releases page
2. Click on the Firefox Beta Release or https://github.com/gorhill/uBlock/releases/download/1.44.1b0/uBlock0_1.44.1b0.firefox.signed.xpi
3. Doesn't work

### Expected behavior

To get a download to the beta XPI

### Actual behavior

It didn't happen

### uBlock Origin version

1.44.1b0

### Browser name and version

Firefox Nightly 105.0a1

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
AMO-signing did not working yesterday.

**Comment by krystian3w** [comment]
See too: https://github.com/uBlockOrigin/uBlock-issues/discussions/2216
