### ISSUE TITLE
Please add three filtering rules.

### ISSUE THREAD

**Issue by edenct** [uBlockOrigin/uBlock-issues#222]
Hello!

About Ads option:

I hope you can turn him into an internal build list!

01:Reek
AakList (Anti-Adblock Killer)
https://reek.github.io/anti-adblock-killer
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

02:280
280blocker for japanese mobile site
https://280blocker.net/download/
https://280blocker.net/files/280blocker_adblock.txt

03: Adblock Plus
ABP Anti-Circumvention Filter List
https://github.com/abp-filters/abp-filters-anti-cv
http://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

Thank you!

**Comment by mapx-** [comment]
- first one is outdated (it was in uBo), the project is dead
- last 1 is still a joke: tons of whitelisting filters, let's wait to see what other snippets ABP will add

**Comment by mapx-** [comment]
However, it's not here where to ask suck things, but here:
https://github.com/uBlockOrigin/uBlock-issues/issues

... however, new lists will not be added without in-depth analysis

**Comment by edenct** [comment]
> * 第一個是過時的（它在uBo），項目已經死了
> * 最後1仍然是一個笑話：大量的白名單過濾器，讓我們等待看看ABP將添加的其他片段

Sorry! Allow me to ask where the first one was replaced by UBO?
The third is not working?

**Comment by mapx-** [comment]
First 1 - no need to be replaced. What - years ago - AAK was doing can be simply done using only uBo specific filters.

I said third 1 is - for the moment - just another very normal list (full of exceptions). When ABP will enrich with new snippets (like the injecting filters in uBo) maybe uBo staff will reconsider the facts.

**Comment by gwarser** [comment]
I'm sorry, request for new filter lists are now disallowed here. If we find out about good filter list we'll add it ourselves.

If you have problems with anti-adblock ask here https://github.com/uBlockOrigin/uAssets/issues
