### ISSUE TITLE
Imported subscriptions disappear after disconnecting and leaving the filter lists page

### ISSUE THREAD

**Issue by PhoenixIndigo** [uBlockOrigin/uBlock-issues#2221]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Imported subscriptions after removing the checkmark and leaving the UBO settings tab, or the page reloading, subscriptions disappear (they are removed).

### A specific URL where the issue occurs

moz-extension://7d4c3759-8669-45bb-b7f8-250eb5401a14/dashboard.html#3p-filters.html

### Steps to Reproduce

1. import subscription, apply changes
2. Disconnect the subscription, apply changes
3. Leave the tab (lists of filters), or restart page

### Expected behavior

The subscription should not remain active in the list of user subscriptions

### Actual behavior

Subscription disappears from the list of user subscriptions

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 156456
  cosmetic: 265466
  scriptlet: 39780
  html: 751
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31282-76, 3h.57m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1492-402, never
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30412-389, 3h.57m
    https://secure.fanboy.co.nz/enhancedstats.txt: 2996-10, 3h.57m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91342-36555, 3h.57m
    https://shorturl.at/cfqKV: 12-0, 3h.57m
    adguard-generic: 67063-5704, 3h.57m
    adguard-mobile: 8154-150, 3h.57m
    adguard-spyware: 26476-1118, 3h.57m
    adguard-annoyance: 56503-1871, 3h.57m
    adguard-social: 18234-2208, never
    ublock-annoyances: 4537-8, 3h.57m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33225-236, 3h.57m
    ublock-badware: 4247-0, 3h.57m
    ublock-privacy: 247-0, 3h.57m
    ublock-abuse: 76-0, 3h.57m
    ublock-unbreak: 1842-1, 3h.57m
    ublock-quick-fixes: 417-0, 3h.57m
    easylist: 69596-650, 3h.57m
    easyprivacy: 27390-9898, 3h.57m
    urlhaus-1: 4622-0, 3h.57m
    plowe-0: 3632-4, 3h.57m
    RUS-0: 42062-3896, 3h.57m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3155 ms
  maxAssetCacheWait: 2046 ms
```
</details>

**Comment by krystian3w** [comment]
see https://github.com/uBlockOrigin/uBlock-issues/issues/2204

**Comment by gwarser** [comment]
Isn't it just minimized? Did you clicked on "+ Custom" header?

**Comment by PhoenixIndigo** [comment]
Yes, that is right. Did not know. Thanks to gwarser
