### ISSUE TITLE
Logger doesn't scroll using touchpad gesture (but mouse wheel works)

### ISSUE THREAD

**Issue by opusforlife2** [uBlockOrigin/uBlock-issues#2223]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The uBO logger doesn't scroll when using the touchpad scrolling gesture. But scrolling using a mouse wheel works just fine. And scrolling in Firefox otherwise works fine as well. It's only the logger that seems to have this bug.

Also, notably, the mouse pointer icon changes to a _different_ scrolling icon compared to when scrolling in Firefox apart from the logger. I tried to take screenshots but the logger pointer doesn't show up in them (and scrolling with the mouse wheel doesn't change the mouse pointer icon at all).

### A specific URL where the issue occurs

uBO Logger

### Steps to Reproduce

1. Open the logger.
2. Open any website which creates enough entries in the logger for the scrollbar to appear.
3. Try using the touchpad scrolling gesture.

### Expected behavior

The logger should scroll.

### Actual behavior

It doesn't.

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 103

### Operating System and version

Windows 7

**Comment by gwarser** [comment]
Is the table focused? Did you clicked on it?

**Comment by opusforlife2** [comment]
I tried clicking on all the columns that don't open further details just now. No dice.

**Comment by opusforlife2** [comment]
In case someone knows what it means, the regular scrolling icon is a tiny scrollbar with an upright mouse pointer _next_ to it.

The logger-specific icon is the same tiny scrollbar , but it has a _tilted_ mouse pointer with its tip at the centre of the scrollbar.

**Comment by gorhill** [comment]
The logger content is event-driven, for performance purpose -- the content of the logger is dynamically updated according to the `scroll` event, so as to avoid having a gigantic DOM if ever the content would grow to tens of thousands of entries. If your trackpad is not sending `scroll` event, then the logger won't update the content according to the new scroll position as a result.

This is the code that deals with `scroll` events: <https://github.com/gorhill/uBlock/blob/a24bc50e407b6be4168dcf49036a3ea0ec26c4e8/src/js/logger-ui.js#L479-L507>. Whoever is welcome to investigate what needs to done to address the issue here.

**Comment by opusforlife2** [comment]
I searched around and found this: https://support.mozilla.org/en-US/questions/895816

The problem seemed similar, so I tried the solution and it worked. Scrolling in the logger is now possible. So it was a Synaptics driver bug after all.

Maybe Firefox implemented a workaround at some point after version 8(!), which didn't work in the logger for some reason.

Do you want to close this or leave it open for someone to try adding a workaround?

**Comment by gorhill** [comment]
Closing as _external_ issue.
