### ISSUE TITLE
Nested procedural filtering into `:has()` did not works

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2228]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Nested has like: 

```adb
example.*##div:has(h1:has-text(Example))
```
will no longer works with Chrome 105 after stable release if Google community no implement better native `has` in CSS.

So I reccomend mediation with Big "corporations" after bugs form console no looks to fix in Addons. I leave it free to throw this into the chromium and Firefox bugtrackers.

https://github.com/AdguardTeam/ExtendedCss/issues/149

---

This can be too regresion after implement mix `has` with `style` #382 or fix Yuki issue #2170

---

AdGuard Base sometimes use `domain.tld##foo:has(bar:has-text(word))`; I don't checked this in uBo stock list or Regional.

### A specific URL where the issue occurs

`example.org` / `example.com`

### Steps to Reproduce

1. Install Chromium Browser 105+ or Opera 91+

 * `layout.css.has-selector.enabled` in Firefox have same troubles - so can break filters in 2023/2024 after publish function as stable (for now have some glitches, so maybe Moz://a implement something to change nothing in uBo code)

2. Paste filter from description to My Filters (or elmenet picker (with omit domain) - as later step).

3. Open one of two demo Internet pages.

### Expected behavior

Website should be "blank".

### Actual behavior

Website isn't "blank".

### uBlock Origin version

1.44.1b1

### Browser name and version

Firefox 103, Opera 91+, Chrome 105+

### Operating System and version

Windows 7/10

**Comment by gwarser** [comment]
@krystian3w this should be detected. Probably new implementation does not throw errors when fed with syntax which is not valid natively. Y:

![image](https://user-images.githubusercontent.com/886325/186217781-f11ef492-01c3-4588-bd4d-19b2efc97a29.png)

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/186218945-084257ad-9635-46f5-86f6-b8d7f4cbf655.png)

**Comment by krystian3w** [comment]
https://github.com/DandelionSprout/adfilt/issues/63

**Comment by gorhill** [comment]
Why close? This needs fixing.

**Comment by krystian3w** [comment]
I meant no possible fix on addon level.

**Comment by krystian3w** [comment]
If I correct checked latest stable 105 release of Chrome has landed with enabled `has` for CSS - so can back e.g. Instagram sponsored posts.

So Google community tries test of implementation on whole people (not on only beta, dev and canary level).

**Comment by gwarser** [comment]
`##body:has(div:has(h1:has-text(Example)))` does not work? Nightly with `layout.css.has-selector.enabled`, uBO 1.44.1b2

**Comment by krystian3w** [comment]
Also both no implement read `:scope` and Firefox also no implemented:

`(>` (maybe too `+` and `~`)

Chrome ignore:

`body:has(body >` as fallback to ":scope".

**Comment by Yuki2718** [comment]
Will uBO uses native :has if possible?

**Comment by gorhill** [comment]
Yes, that's the goal, it's already the case and it's actually why the issue exist here given that `:has(...)` has been spec'ed as a "forgiving" operator -- this makes sorting out prrocedural vs. declarative very difficult for uBO.

**Comment by gorhill** [comment]
I didn't expect Chrome 105 to reach stable already. I will have to do something to fix this and publish a 1.44.2 revision.

**Comment by gorhill** [comment]
The chosen solution is for filter authors to force the parsing of a filter as procedural by using `#?#` instead of `##`.

**Comment by gothic-bum** [comment]
> The chosen solution is for filter authors to force the parsing of a filter as procedural by using #?# instead of ##.  
  
Will `#?#` also apply to other procedural filters that have native browser support (e.g. `:not(...)` ), or is it just for `:has(...)`?

**Comment by gorhill** [comment]
Any potentially procedural operator, so also `:not(...)`. Normally uBO would try to compile them as declarative, `#?#` will prevent that.

**Comment by gorhill** [comment]
I do expect the need to use `#?#` to be rare, but we will see.

**Comment by MasterKia** [comment]
What about older rules? Do they all need to be tested again?

Can uBO warn in the syntax highlighter that this rule _**might**_ need `#?#` instead of `##?

**Comment by MasterKia** [comment]
What about older rules? Do they all need to be tested again?

Can uBO warn in the syntax highlighter that this rule _**might**_ need `#?#` instead of `##`?

**Comment by krystian3w** [comment]
Simple nested filtering may enough first fallback commit.

Mix with `:style(` in Chrome and/or Moz://a may works on to low level aka w3school placeholder.


Moz://a implementation don't support now unhide after node disappeared form dom tree http://ameshkov.github.io/web/watchattr.html (second test) [attr demo works fine in CSS], to recover element needed is rebuild CSS or opens element picker (also refresh CSS without touching).

**Comment by Yuki2718** [comment]
`#?#:has()` is currently AG aliase converted to `##:has()`, how this will become? Will all `#?#:has()` in AG lists be treated as explicit procedural filter? The same goes for `#?#:-abp-has()`?

**Comment by Yuki2718** [comment]
> 
> Firefox also no implemented:
> 
> `(>` (maybe too `+` and `~`)
> 
> Chrome ignore/no implemented:
> 

Often (particularly in AG lists) `>` is used in arguments, so I guess `#?#` use will not be rare.

**Comment by krystian3w** [comment]
Fast count with possible bugs:

`:has(>` have 1084 filter lines in **AG Base** as 1086 all uses (so few have twice or triple).

Also count 12 `#$?#` (CSS).

6 have ## without `?`: `shoppe.*, fast-down.com, freeshib.biz, emulatorgames.net, inc.com, movie-19.com`.
Need fixes for only uBo.
 

After count domains = 1751 and more if count public suffix (75 times used).

**Comment by HashLiver** [comment]
change`has`to`-abp-has`, problem solved temporarily.

**Comment by gorhill** [comment]
> Will all `#?#:has()` in AG lists be treated as explicit procedural filter?

Yes.

**Comment by Yuki2718** [comment]
> What about older rules? Do they all need to be tested again?

Maybe those with :has-text inside :has and `:has(> selector)` should be rewritten with `#?#`?
@krystian3w I guess you mean `:has(> selector)` is not supported while `:has(selector1 > selector2)` is fine, right?

**Comment by gothic-bum** [comment]
@Yuki2718:

Per Moziila, `:has(> selector)` is valid:
https://developer.mozilla.org/en-US/docs/Web/CSS/:has#matching_a_elements_that_directly_contain_an_img

**Comment by Yuki2718** [comment]
> 
> In addition, I read on bugzilla that they have a problem with implementing it and waiting for reasonable solution...
> 

https://bugzilla.mozilla.org/show_bug.cgi?id=1771896

**Comment by Nojuuu** [comment]
@peace2000  @:ing you since all `:has()` filters have `#?#` currently in Finnish list.

**Comment by peace2000** [comment]
So just changing `:has()` to `:-abp-has()` fixes the issue?

**Comment by krystian3w** [comment]
More is workaround, if someone implement better rewrite other syntaxes to `:has`, then back bug for exotic filters without `?`.

**Comment by peace2000** [comment]
Reverted all `:has()` to `:-abp-has()` temporarily. Fyi @DandelionSprout as well.

**Comment by DandelionSprout** [comment]
I've noticed that only **some** `:has` entries have caused problems on my end in Chrome 105. Primarily those that used `##.element1,element2:has()` __and__ `[parameter=""]` at the same time, for which I've fixed the major instances I've come across in my smaller filterlists.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/14662

**Comment by krystian3w** [comment]
So your `:scope` works fine as Vanilla filter into `:has`?

**Comment by krystian3w** [comment]
I detected teach browser be add-on how read child's:


https://user-images.githubusercontent.com/35370833/188596501-48313b5e-6a19-41c3-9c32-b64e673d4ce2.mp4

```css
! https://codepen.io/bramus/pen/MWEvKEg
cdpn.io##figure:-abp-has(figcaption) img:style(outline: 10px dashed red;)
```

Without these teach, Mozilla fail don't stylize second image.

**Comment by gorhill** [comment]
I can reproduce the issue with Firefox with your filter once `layout.css.has-selector.enabled` is set to `true` -- not sure why as I stepped in the code once and all seemed to execute as expected -- this needs more investigation.

> Without these teach

I don't understand that sentence, what is _teach_?

**Comment by krystian3w** [comment]
Mozilla based on devtools ignored has selector and matches second image without figcaption parent.

So uBo temporary teach demo how don't match false positives.

**Comment by Yuki2718** [comment]
So `##selector1:has(something) selecotor2` can cause FP on Firefox with `layout.css.has-selector.enabled: true`.

**Comment by krystian3w** [comment]
But hopefully not enabled for any groups:

- stable
- beta and oldie Aurora renamed to developer
- nightly


We can still fight for this piece of bread. But I don't see light to implement error for nesting.

**Comment by krystian3w** [comment]
I detected new regression in works `:not()` after enforce filter as procedural or in AdGuard style syntax in uBo 1.44.2:

```adb
! works simple negation
private-company-webapp.org##table td:has-text(employee1) ~td:not([class*="day off"]):style(border-top: 5px solid green)
!
! Both have broken `:not()`
private-company-webapp.org#?#table td:has-text(employee1) ~td:not([class*="day off"]):style(border-top: 5px solid green)
private-company-webapp.org#$?#table td:has-text(employee1) ~td:not([class*="day off"]) { border-top: 5px solid green) }
```

The negation in enforced procerdual and AdGuard syntax are cleared to empty brackets in use (possible see this in uBo logger). Also then no works disable broken filter by Author mode form advance settings.

**Comment by BPower0036** [comment]
> I do expect the need to use `#?#` to be rare, but we will see.

I'm on FireFox 104.0.1 (`layout.css.has-selector.enabled` enabled) and with the latest stable uBo update and I only had to change one rule (procedural operator) of all rules I have, namely:
`github.com##div.push > .body > :has([href="/apps/github-actions"])` to `github.com#?#div.push > .body > :has([href="/apps/github-actions"])`, but strangely `github.com##div.push > [class="body"] > :has([href="/apps/github-actions"])` also worked.

**Comment by krystian3w** [comment]
I see breakage in uBo dev with `>`, `~` and `+` in html filtering:

```yml
! Uncaught DOMException: Element.querySelectorAll: ' > a' is not a valid selector html-filtering.js:201
```
```js
return Array.from(root.querySelectorAll(this.selector));
```adb
gorhill.github.io##^#phf #a2 .fail:has(> a > b)
gorhill.github.io##^#phf #a12 .fail:has(+ a)
gorhill.github.io##^#phf #a13 .fail:has(~ a:has(b))
```

Workaround can be use `upward`.

IMO not related with experimental `layout.css.has-selector.enabled` - Those willing can check whether CSS tree and in the future browser can be used in html filtering. the implementation of hashes

**Comment by krystian3w** [comment]
Latest uBo dev have if condition when found:

```adb
foo.who##a, b:has(c)
```

Because simple CSS hide any `a` without test exist `c` inside (only `b` are checked and no possible check elements above like `b:has(body c)`) - for joining recommended will be use: `:is(a, b):has(a)` as the shortest.

In short I mean CSS didn't followed content blockers decision.

**Comment by gorhill** [comment]
uBO should follow the expected result in CSS. with the previous parser there was not much motivation to do so because of all the added code complications, but this comes free with the new parser.

At this point I think I prefer to leave this to another dev build cycle.

**Comment by krystian3w** [comment]
I think this can be regression in deprecated syntax:

1. Open on PC https://github.com/gorhill/uBlock/commit/2f646dbdb0c297d25a7300804f305df3f87b3cee
2. Into picker paste `##.pl-s:if-not(*)`
3. Filter matches ≈24 elements but only ≈four (4) are without childs, may works fine in `##.pl-s:not(:has(*))`

If page don't have `.pl-s` maybe needed is enable sidebar with catalogs for commits.

In real cases regression will break pages like `kobieta.wp.pl` with MajkiIT oldie filter line.

**Comment by gorhill** [comment]
> Into picker paste `##.pl-s:if-not(*)`

`if-not` is no longer documented as being valid, it should not be used as a case to fix.

**Comment by krystian3w** [comment]
So somebody must virtual kicked / prodded MajkiIT to update filter before new parser are stable.

Similar case like #2316 to remember update in filter file.
