### ISSUE TITLE
WebExt manifest was not updated

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#223]
I'm not sure if @gorhill is still maintaining the Debian WebExt build, but the manifest file was not updated: https://github.com/gorhill/uBlock/blob/master/platform/webext/manifest.json#L69

It's 51 in the other file: https://github.com/gorhill/uBlock/blob/master/platform/chromium/manifest.json#L61

I apologize in advance if this is a false alarm.

**Comment by uBlock-user** [comment]
WebExt. manifest comes with `strict_min_version: 52.0`, so don't think `minimum_chrome_version` is enforced or required to be updated.

Actually, it's purposefully ignored according to [bug 1282978](https://bugzilla.mozilla.org/show_bug.cgi?id=1282978)
