### ISSUE TITLE
We can enable adblock in page where we shouldn't (for example new tab page, settings, page extension page)

### ISSUE THREAD

**Issue by LoryPelli** [uBlockOrigin/uBlock-issues#2230]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

We can enable adblock in page where we shouldn't (for example new tab page, settings, page extension page)
You should make that we can't click the button to enable the extension and the extension will be disabled by default

### A specific URL where the issue occurs

chrome://newtab

### Steps to Reproduce

1. Go for example on chrome://newtab
2. Click the extension and enable it

### Expected behavior

You shouldn't be able to enable it

### Actual behavior

You can enable it but it's unuseful

### uBlock Origin version

1.44.0

### Browser name and version

Chrome (version not required)

### Operating System and version

Windows (version not required)

**Comment by gwarser** [comment]
It may be useful when browser devs decide so. There seems to exist some hidden switches to allow add-ons to run on these pages. From what I know, it should not do any harm on browser pages, except on uBO add-on page itself where it can block list updates.

**Comment by krystian3w** [comment]
IMO unlock form browser was removed (e.g. in Chromium 58 or 61 <sup>https://userstyles.org/styles/111526/new-tab-chrome-without-history-thumbnail</sup>).
