### ISSUE TITLE
i find ads in flipkart.com

### ISSUE THREAD

**Issue by holequantum** [uBlockOrigin/uBlock-issues#2231]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In flipkart.com i find ads i have tried in 2devices and pc also this was same after surfing for a while you will find ads in product page above the product page bellow suggested products you will find ads

### A specific URL where the issue occurs

https://www.flipkart.com/

### Steps to Reproduce

Open flipkart.com and log in and surf for a whilee and you will find ads banner above the page and below the product

### Expected behavior

It should have blocked like amazon.com but i find this is not the case here

## screenshots
![gg](https://user-images.githubusercontent.com/108695843/187023456-76a4e752-7369-4ae0-a5fa-656997230c85.png)
![kk](https://user-images.githubusercontent.com/108695843/187023464-2e9c493c-5563-4f2a-9da5-9cbf98f8dd0d.jpeg)
![dd](https://user-images.githubusercontent.com/108695843/187023469-4034c7da-fe57-407a-840c-62668fadad0e.jpeg)
![Screenshot a](https://user-images.githubusercontent.com/108695843/187023752-4e435025-b61a-4edc-9da4-d2daf921600f.png)
![Screenshot b](https://user-images.githubusercontent.com/108695843/187023759-e3f67b1a-7c43-4bdc-8107-cf32c87a560a.png)
![Screenshot c](https://user-images.githubusercontent.com/108695843/187023762-c90a1fbe-f300-4180-8990-9244d3eba025.png)

It is not blocking all ads.

### uBlock Origin version
1.44.0

### my blocklist
![Screenshot from 2022-08-27 14-47-07](https://user-images.githubusercontent.com/108695843/187035326-0cf450c2-64a2-445d-8ce1-3e28a07b0781.png)

### Browser name and version

firefox 

### Operating System and version

android-12 / android 11/ fedora 36

**Comment by holequantum** [comment]
why you closed it can you explain how to solve this issue?

**Comment by gorhill** [comment]
> [x] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))

This **is** a filter issue.

> [x] uBO with default lists/settings

You are reporting screenshots of the site on Firefox for Android while you AdGuard Mobile is disabled -- it's enabled by default on mobile.

Please do not be a burden for _volunteers_ here and report truthfully your issues, after having truthfully respected the required steps.

**Comment by gorhill** [comment]
Also, always provide exact URLs as requested, asking volunteers with limited free time to "surf for a whilee" is not going to work.
