### ISSUE TITLE
main.yml gorhill/uBlock is running with full permissions

### ISSUE THREAD

**Issue by sashashura** [uBlockOrigin/uBlock-issues#2235]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I have patch for the workflow which narrows permissions only to contents write: https://github.com/gorhill/uBlock/compare/master...sashashura:patch-1?expand=1

Context: GitHub Workflows security hardening
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

### A specific URL where the issue occurs

https://google.com

### Steps to Reproduce

See description

### Expected behavior

The workflow runs with least privileges.

### Actual behavior

The workflow runs with read/write access to issues, pull requests, security events, contents, projects, etc.

### uBlock Origin version

master branch

### Browser name and version

all

### Operating System and version

all

**Comment by gorhill** [comment]
Thanks.

Patch imported in <https://github.com/gorhill/uBlock/commit/b9aa791901183783cb8710e3bc3a703e177cbadc>.

Since with this patch you are a contributor, you can make a merge request directly to the repo next time.

**Comment by BlazeFTL** [comment]
Did not want to open a issue
But everytime i sync uasset i get this workflow run failed
![Image](https://github.com/user-attachments/assets/1924c2cd-4245-44b9-9538-e1a91e97a4c0)
