### ISSUE TITLE
enhancement: freeze page while element picker is opened

### ISSUE THREAD

**Issue by lvmm** [uBlockOrigin/uBlock-issues#2236]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Some pages change by itself and do it too rapidly for me to be able to pick elements with the element picker (1). Some pages change in response to mouse movement or keypresses and make it impossible to invoke the picker with the offending element still displayed (2). I'd like an option to freeze the page while element picker is invoked. The first part can be done - there are extensions out there capable of pausing/resuming javascript on the page, not sure about the second one though.

Consider https://www.linuxquestions.org/questions/linux-newbie-8/ - no ads there, but a good illustration: on first invocation, it displays cloudflare DDOS protection page for a short while, and if you want to block some element there - e.g. useless facts, you have to be really fast. Then on the forum page when mouse pointer is moved over a topic title, a pop-up appears, but when either the right-click context menu or the element picker directly via a hotkey is opened, it disappears and cannot be picked.

### A specific URL where the issue occurs

https://www.linuxquestions.org/questions/linux-newbie-8/

### Steps to Reproduce

prerequisites: https://www.linuxquestions.org/ shouldn't be accesses for a while for DDOS protection to time out

1. open https://www.linuxquestions.org/questions/linux-newbie-8/
2. try picking an element on the DDOS protection page
3. when forum page opens hover mouse pointer over a topic title
4. open the element picker

### Expected behavior

In step 2  I'd ike to have ample, preferably unlimited time for picking elements, in step 4 the popup shouldn't disappear when picker is opened.

### Actual behavior

Not enough time to pick anything in step 2, cannot pick the element in step 4 if it is not there any more.

### uBlock Origin version

1.44.0

### Browser name and version

firefox 104.0, chromium 104.0.5112.101

### Operating System and version

linux 5.4.0-122, windows 10

**Comment by gorhill** [comment]
Declined.

**Comment by 30to50feral** [comment]
why?
