### ISSUE TITLE
Add option to prevent overriding user configuration with deployed admin settings

### ISSUE THREAD

**Issue by boocov** [uBlockOrigin/uBlock-issues#2237]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

My corporation deployed uBlock Origin with adminSettings (https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin) and configured it very badly for my perspective. They don't use all blocklists, which I want to use and whitelisted many trackers. Also they override my filters and rules.
Sadly, the registry entry and the configuration file is not writable for me. So far, I have not been able to convince anyone responsible to adjust this so that the values are changeable for users.
My current workflow is to change the settings to my preferred configuration every time Firefox starts. But this is really annoying and time consuming.

According to the manifesto (https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md), the user should be able to decide eg which blocklist to use and which sites to whitelist, not the corporation's admin team. :)

Can you add an advanced option that prevents overwriting user configuration with the admin settings?

### A specific URL where the issue occurs

-

### Steps to Reproduce

1. Create the file `C:\Program Files\Mozilla Firefox\uBlock0@raymondhill.net.json` with content: 
```
{
    "name": "uBlock0@raymondhill.net",
    "description": "Admin bad config",
    "type": "storage",
    "data": {
        "adminSettings": {
            "userSettings": {
                "cnameUncloakEnabled": false,
                "hyperlinkAuditingDisabled": false,
                "importedLists": [],
                "prefetchingDisabled": false
            },
            "selectedFilterLists": [
                "user-filters",
                "ublock-filters",
                "urlhaus-1"
            ],
            "hiddenSettings": {},
            "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
            "urlFilteringString": "",
            "hostnameSwitchesString": "no-large-media: behind-the-scene false",
            "userFilters": "!\n",
            "whitelist": [
                "evil-tracker.com",
                "google-analytics.com",
                "mycorporation-website.com"
            ]
        }
    }
}
```
3. Add the registry entry `HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\ManagedStorage\uBlock0@raymondhill.net` with the value `C:\Program Files\Mozilla Firefox\uBlock0@raymondhill.net.json`
4. Start Firefox with installed uBlock Origin again

### Expected behavior

As an advanced user, I would like to have the ability to persistent my user configuration and to override admin settings.

### Actual behavior

The admin settings override my user configuration, eg. user settings, filter lists, rules. In my case, the enforced admin settings are considerably worse than the default uBlock Origin configuration. The consequence is that I must change the settings of uBlock Origin every time Firefox starts.

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 104.0.1

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Declined.

**Comment by boocov** [comment]
Why is it directly declined? Is this not a legitimate feature?

**Comment by MasterKia** [comment]
> Is this not a legitimate feature?

It is.

> directly declined?

Gorhill is a volunteer and has limited free time.

**Comment by gorhill** [comment]
I declined because it makes no sense to implement this, managed settings are meant to override local settings. If this was not the case, admins would install another blocker which respects their managed settings. Also, as a side note, invoking my words in the manifesto as an argument for whatever feature request is a sure way to start me with a negative view of any request.

**Comment by boocov** [comment]
I understand that this doesn't make much sense, at least from the administrator's point of view. But since I can manually override the settings, I thought this would be a suitable feature.

I searched everywhere for a solution and also found the manifesto. That was not meant quite seriously. It was supposed to be a bit funny and ironic, but that didn't work. I didn't mean to offend you. I'm sorry for that.

Should I switch over to reddit for discussion?
Is there maybe another solution to quickly override the admin settings? The import doesn't seem to work.
Maybe I can think of something else. Maybe a script which changes uBlock Origin settings at runtime.
