### ISSUE TITLE
uBO prevents certain web-sites or parts of them from loading

### ISSUE THREAD

**Issue by AlexCzar** [uBlockOrigin/uBlock-issues#2238]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

The problem started several days ago.
Some websites are extremely slow to open (minutes), others never complete loading at all.
To be sure that none of my other settings/configs are at fault, I've tried disabling everything else in my existing profile first, the issue only goes away after I completely disable or uninstall uBO, disabling it for the affected websites doesn't solve the issue.

https://trakt.tv - doesn't load at all
gmail - loads slowly, parts of the page are missing or not working
github - loads slowly, some stuff is missing, or doesn't load at all
Messenger - loads slowly, some media is missing

Note regarding reproduction, I asked my friend to try, they have the same version of Firefox, the same version of uBO, but on their machine it works without issue.
I'm not sure what could be the culprit and how to debug this further.
I tried installing several other ad blocking extensions, none of them have any problems, I'm temporarily using Ghostery due to this issue, but I'd love to go back to uBO.

### A specific URL where the issue occurs

https://trakt.tv

### Steps to Reproduce

1. create completely fresh profile,
2. opene firefox with that profile,
3. go to addons.mozilla.org,
4. install uBO
5. Try to open https://trakt.tv (the site that is affected the worst of all, it's a fully legit TV Shows/Movies status tracker)

### Expected behavior

Website loads

### Actual behavior

I only see the loading animation in the tab bar along with the website title, the page never finishes loading

### Configuration

*Environment*
```sh
; uname -r
5.19.2-1-default
; zif MozillaFirefox | rg Version
Version        : 104.0.1-1.1
# the issue was also present on 104.0
; rg -o '"name":"uBlock Origin","version":"([\d.]+)"' -r '$1' ~/.mozilla/firefox/b5hydvj1.uBO\ only/addons.json
1:1.44.0
```
*uBO config*
Default, no changes to uBO configuration were made.

**Comment by gorhill** [comment]
What happens if you disable _"Uncloak canonical names"_ in uBO settings?

**Comment by AlexCzar** [comment]
O_O it works with that setting disabled!

**Comment by AlexCzar** [comment]
Read the docs on that settings. Weird.
I do not have a proxy, I connect directly to the internet.
What I do have is a chaching DNS server (dnsmasq) running on 127.0.0.1:
```sh
; rg nameserver /etc/resolv.conf
17:nameserver 127.0.0.1
```
Its upstream are in order: 1.1.1.1, 8.8.8.8
I just tried switching my connection to use 1.1.1.1 dircectly without the caching done by dnsmasq 127.0.0.1.
With such a setup and "Uncloac canonical names" enabled uBlock works normally.
What could be the issue uBlock has with dnsmasq?
```sh
; nslookup trakt.tv 127.0.0.1        
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	trakt.tv
Address: 172.67.3.215
Name:	trakt.tv
Address: 104.20.81.229
Name:	trakt.tv
Address: 104.20.82.229
Name:	trakt.tv
Address: 2606:4700:10::ac43:3d7
Name:	trakt.tv
Address: 2606:4700:10::6814:52e5
Name:	trakt.tv
Address: 2606:4700:10::6814:51e5
```

**Comment by gorhill** [comment]
uBO just uses the Firefox API [browser.dns.resolve()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve), what happens beyond this is out of control of uBO.

**Comment by AlexCzar** [comment]
That is what's weird, FF works fine on its own with the dnsmasq as DNS server, only uBO triggers the problem, all other ad blocking extensions also work fine.
Moreover, uBO also worked fine for years with this setup, the issue only started several days ago.

**Comment by ciencia** [comment]
Since a few days, I'm also experiencing the same issue as the op. Firefox 104.0.1 on OpenSUSE Tumbleweed. I was waiting to see any report here to add my experience in case there were no fix for that.

Several random websites never finish loading, but always the same ones. Opening the browser's developer tools shows that the request for the document finishes loading, but no other related asset is even attempted to download (images, css, javascript...). I can view the source code of the page, and even open individual assets of the page itself. When this happens, the entire domain is affected (any page of the affected domain gets the same behavior). Clearing cookies and the cache didn't help. But opening the browser with a different browser profile, and importing the same UBO settings from the session where the problem occurs allows to visit those same webpages just fine. Disabling UBO cause all those pages to load fine.

Disabling the "Uncloak canonical names" option as suggested, and restarting the browser, fixed the issue.

**Comment by gorhill** [comment]
Those having issues with _"Uncloak canonical names"_ will have to investigate on their site why calling Firefox API `browser.dns.resolve()` causes an issue for them. Look beyond uBO for the point of failure.

**Comment by palm93** [comment]
Just stumbled across this thread hoping someone had gotten further than me with this. 

I'm also running OpenSUSE Tumbleweed, and have been experiencing this problem for a few days.

I discovered that stopping the nscd service or reloading it to invalidate it's caches, then restarting firefox allows "uncloak canonical names" to work without issue.

**Comment by AlexCzar** [comment]
Looks like something could be up with dns stuff on OpenSuse TW, that's my OS, too.

**Comment by pws1453** [comment]
Same issue here, OpenSuse TW, Firefox 104.0.2. Have we found a way to remediate the issue? If not, has an issue been filed elsewhere? It seems like this issue may not lie within ublock, but perhaps within firefox or opensuse. Let me know how best to proceed.

**Comment by palm93** [comment]
if you don't need nscd (i.e you have another cacheing resolver on your local network), you can disable it. if you do, maybe have a poke around with it's config.

**Comment by pws1453** [comment]
I reloaded nscd, and Firefox seems to work with uncloaking enabled. If I have issues in the future - I'll poke around with it's config and report back. Thanks!
