### ISSUE TITLE
Very slow to apply rules like ":style"

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2239]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

In the RU AdList filter, I sometimes use `:not(#id)` to increase the priority, in cases where webmasters apply "important" styles. I also use the `#?#` syntax for rules like `:style` to ensure compatibility with Adblock Plus in the future.

Example: `rezka.ag#?#body:not(#id):style(padding-top: 0 !important)`

In uBlock Origin: 1.44.1b3, all such rules no longer work.

In uBlock Origin: 1.44.1b4 the rules worked, but very slowly. 

### A specific URL where the issue occurs

https://rezka.ag/

### Steps to Reproduce

1. Activate filter **RUS: RU AdList**
2. Open: `https://rezka.ag/`

### Expected behavior

The page opens without an indent at the top.

### Actual behavior

The page opens with an indent at the top, which disappears only after a while.

<details>
<summary>Gif</summary>

![rezka](https://user-images.githubusercontent.com/20126984/187965074-cf8d2d05-a583-46cd-b987-c0097383af85.gif)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.1b4
Chromium: 105
filterset (summary): 
  network: 101104
  cosmetic: 64733
  scriptlet: 18943
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    RUS-0: 42056-9, now
    easylist: 66435-68, now
    easyprivacy: 27449-225, now
    plowe-0: 3634-782, now
    ublock-abuse: 76-1, now
    ublock-badware: 4202-99, now
    ublock-filters: 32458-141, now
    ublock-privacy: 241-1, now
    ublock-quick-fixes: 414-4, now
    ublock-unbreak: 1847-41, now
    urlhaus-1: 7511-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 277 ms (selfie)
  maxAssetCacheWait: 435 ms
```
</details>

**Comment by krystian3w** [comment]
Because we enforced this as procedural filter:

https://github.com/gorhill/uBlock/commit/79451e5899a83682548147b08e7e51004962650c

This may recover works injection CSS too:

https://github.com/gorhill/uBlock/commit/bcede6f938f729276fce2baaf58515b77ef6121c

**Comment by gorhill** [comment]
You will have to remove the `?` is you want uBO to try to enforce the rule declaratively. For now there is no other way to deal with the newly browser-supported `:has()` operator.

**Comment by krystian3w** [comment]
Also rule is bad word in uBo syntax.

Rule is for firewall mode.

**Comment by gorhill** [comment]
> in cases where webmasters apply "important" styles

This shouldn't be an issue since uBO uses user styles, which always trump page styles.

**Comment by krystian3w** [comment]
> in cases where webmasters apply "important" styles

What page made own addon with Enabled:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/insertCSS

aka

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/insertCSS

**Comment by dimisa-RUAdList** [comment]
> This shouldn't be an issue since uBO uses user styles, which always trump page styles.

The fact is that RU AdList CSS Fixes is also used as a [styles for the Stylus](https://github.com/easylist/ruadlist/blob/master/ruadlist-fixes.user.css), and there "important" matters.

I will remove "#?#" in the next commits.

**Comment by krystian3w** [comment]
I don't think so, Stylus inject `<style>` at after </body>, so page must inject own `<style>` under Stylus `<style>`.

![obraz](https://user-images.githubusercontent.com/35370833/187974247-149d3c3e-f193-4268-a561-88c627af9ab2.png)


Also have protection to avoid ~100 deletions of injected nodes.

I don't used Stylish, xStyle or FireMonkey to check where inject styles or was converted to use `tabs.insertCSS()` / `scripting.insertCSS()` - Also I don't prefere inject user.css by Violentmonkey/Tampermonkey/Greasemonkey (may fail on blured (not focused) tabs).

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/7e426229cb064cb8bbf03d4b2e864ea61830aee3
