### ISSUE TITLE
Multi Resources under Advance Settings

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#224]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
This is more of a question than an issue. Is there a way to use multiple sources for userResourcesLocation? I tried to add another line with a different Resource location, but it just replaced it I then added a comma between both and it seemed to save just not sure this method works or not.

Reason: I want to use the nano defender scriptlets as well as uBlock-user's scriptlets  at the same time since his filterlist requires this for some filters to work properly. 

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment]
This is explained in Nano Defender installation guide:

>Note: If you have another User Resources in use, then you would need to either switch to Nano Adblocker or manually merge resources...

**Comment by uBlock-user** [comment]
Currently, not possible.

**Comment by troysjanda** [comment]
ok thanks

**Comment by troysjanda** [comment]
possible to add to custom filter list on the filterlist tab toward bottom?

**Comment by gwarser** [comment]
You need to copy both files and paste to new [gist](https://gist.github.com/) (for example) and then use this gist raw URL in `userResourcesLocation`

**Comment by uBlock-user** [comment]
Merge the contents of both into one and use that one at `userResourcesLocation`

**Comment by troysjanda** [comment]
> 
> 
> You need to copy both files and paste to new [gist](https://gist.github.com/) (for example) and then use this gist raw URL in `userResourcesLocation`

I did this in gist, what about duplicates? I suppose it will do like the filters and create a single list filtering out dups.

**Comment by uBlock-user** [comment]
You will have to filter duplicates yourself.

**Comment by jspenguin2017** [comment]
When two resources have the same name, the one defined later will override previous ones, and the user resource will override built-in resource.

**Comment by troysjanda** [comment]
> 
> 
> Do **NOT** attempt to load resource file as filters, or you will run into all sort of troubles.
> See: [NanoAdblocker/NanoFilters#170 (comment)](https://github.com/NanoAdblocker/NanoFilters/issues/170#issuecomment-414481847)

Good Advise, What is  the issue with allowing users to add or use multi Resources under advance settings? Dup problems? Something else. 

Could  it be possible as with adding other lists to a single list. What I mean is for example uBlock-user filterlist can call his scriptlet Resources from within the filterlist, for use with that and only that filterlist. would this be possible? like an include statement 

include resource "https://<resourcescriptlets>"

Again very sorry if not explaining this better.

**Comment by uBlock-user** [comment]
> What is the issue with allowing users to add or use multi Resources under advance settings? 

No reason, functionality for a custom scriptlet was added like this by-design after a [suggestion](https://github.com/gorhill/uBlock/issues/2267) was made for it. You're the first one to ask/use multiple resources list.

**Comment by troysjanda** [comment]
Possible to consider the ability to use multiple scriptlets list. if the demand is not there I understand. 

Would be nice feature instead of combining both and having to hand remove dups. Maybe limit to 2-3 as not to get too bizarre with it. 
 
I tried to sort and remove dups by line/case but ran into a lot of issues with broken scriptlets and endless number of missing braces, I ended up just combining and using it as a single file.

**Comment by uBlock-user** [comment]
Open a new issue and a make a suggestion about it.

**Comment by jspenguin2017** [comment]
One resource can have more than 1 line, and the order may not be changed. If you sort the lines of a resource file, you will corrupt it. 

You need to parse it into a hashmap to check for duplicates. See here for my parsing function (you may want the map to be `content -> { name, mime }` instead. 
https://github.com/NanoAdblocker/NanoCore2/blob/fe293cb9ba7770a7111af971830f14366b961001/term/build.js#L236

**Comment by jspenguin2017** [comment]
> What is the issue with allowing users to add or use multi Resources under advance settings? 

The code that loads user resource is poorly done and needs to be redesigned. And no one feels like doing that. 

> call his scriptlet Resources from within the filterlist

I would assume you mean the filter can declare scriptlets it uses in the same file. This is not acceptable because it is very dangerous, a malicious filter can steal your passwords and credit card information.

**Comment by troysjanda** [comment]
> 
> 
> One resource can have more than 1 line, and the order may not be changed. If you sort the lines of a resource file, you will corrupt it.
> 
> You need to parse it into a hashmap to check for duplicates. See here for my parsing function (you may want the map to be `content -> { name, mime }` instead).
> https://github.com/NanoAdblocker/NanoCore2/blob/fe293cb9ba7770a7111af971830f14366b961001/term/build.js#L236
> 
> You shouldn't try to remove duplicate contents though, because it can break name reference.

I reverted to just combining and using the single file for now as you suggested with gist

"I would assume you mean the filter can declare scriptlets it uses in the same file. This is not acceptable because it is very dangerous, a malicious filter can steal your passwords and credit card information."

I meant from within his filter-list set a parameter which loads the his resource file for use with that list. So if a filter calls for a resource it correctly uses his instead of the one in the advance settings. does this make since? I am sure there can be checks  to make sure its from same orgin, not entirely sure I am explaining it correctly  Sort of like the feature that one filter-list can also include another on the same orgin.

**Comment by jspenguin2017** [comment]
> So if a filter calls for a resource it correctly uses his instead of the one in the advance settings. 
> Sort of like the feature that one filter-list can also include another on the same orgin.

No, this is not acceptable. 

A filter must not be able to execute untrusted code. When you subscribe to a filter list, you shouldn't need to worry about whether the filter list you just subscribed to will steal your passwords. 

Also, this is not allowed on Firefox extension store.
