### ISSUE TITLE
Element picker is light themed when uBO theme is set to auto in Firefox Nightly

### ISSUE THREAD

**Issue by bbhtt** [uBlockOrigin/uBlock-issues#2240]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

GNOME 42.4 using system dark mode (Freedesktop colour scheme preference ie. Dark is set in Gnome control center>Appearance>Style), Firefox theme set to System - Auto, uBo theme set to auto.

Open the element picker in any page, it is light themed but uBO itself is dark themed (the settings page and the extension popup).

### A specific URL where the issue occurs

https://hg.mozilla.org

### Steps to Reproduce

1. Open the element picker in any page

### Expected behavior

It should be dark themed

### Actual behavior

See that it is light themed

### uBlock Origin version

1.44.0

### Browser name and version

Firefox Nightly 106.0a1 (2022-09-01) (64-bit)

### Operating System and version

Archlinux

**Comment by bbhtt** [comment]
I bisected this down to 

```
$ mozregression --good 2022-08-10 --bad 2022-08-25

27:02.53 INFO: No more integration revisions, bisection finished.
27:02.53 INFO: Last good revision: 7c1e795e3c0750d5dcd99dab73be28e871c38979
27:02.53 INFO: First bad revision: 495ffb27c683fe2219b559708d3eb415847faa10
27:02.53 INFO: Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=7c1e795e3c0750d5dcd99dab73be28e871c38979&tochange=495ffb27c683fe2219b559708d3eb415847faa10
```

which means https://bugzilla.mozilla.org/show_bug.cgi?id=1782596 is responsible. It looks like this is the same issue as this one reported as a regression of the previous one https://bugzilla.mozilla.org/show_bug.cgi?id=1787127

Let me know if this is a separate issue, I can open a bug in BMO.

Thanks!

**Comment by gorhill** [comment]
It works fine with Firefox 104.0.1, hence it appears to be a regression in Nightly.

**Comment by bbhtt** [comment]
> It works fine with Firefox 104.0.1, hence it appears to be a regression in Nightly.

Yes this happens only in Nightly at the moment.

**Comment by krystian3w** [comment]
Works fine too in 105.0b6.

**Comment by bbhtt** [comment]
> I think it is the same issue as this one reported as a regression from the previous one https://bugzilla.mozilla.org/show_bug.cgi?id=1787127

Wasn't fixed on today's nightly, which seems to include it as far as I can tell. So I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1789338

**Comment by emilio** [comment]
Yeah, this seems kind of an unfortunate side-effect of the fix for https://github.com/uBlockOrigin/uBlock-issues/issues/1408. The relevant `<iframe>` that uBlock injects has `color-scheme: light`, so as per https://github.com/w3c/csswg-drafts/issues/7493, it now matches `prefers-color-scheme: light`.

Removing that, and just having the inherited color-scheme go through, would just work, and allow the iframe to remain transparent. But in Chromium which hasn't implemented this yet it'd regress that issue... So it's a bit tricky...

**Comment by krystian3w** [comment]
#2062 #2196 #2121

**Comment by gorhill** [comment]
> But in Chromium which hasn't implemented this yet it'd regress that issue... So it's a bit tricky...

I can inject `color-scheme: light` conditionally only when browser is Firefox version 106+. @emilio This works?

**Comment by uBlock-user** [comment]
with github dark theme -- 

![Capture](https://user-images.githubusercontent.com/21290713/189512221-ea5bd3f5-9958-459c-82c2-77ff7b103f1c.PNG)

**Comment by emilio** [comment]
@gorhill that doesn't quite work, I can write a patch that works everywhere. In fact I thought I replied to your comment and sent it already, but I must've dreamed it, sorry :-(

**Comment by emilio** [comment]
@gorhill https://github.com/gorhill/uBlock/pull/3872

**Comment by rishiraj88** [comment]
Great!

**Comment by bbhtt** [comment]
This seems to be broken again in Nightly 107.0a1 (2022-10-08)
