### ISSUE TITLE
uBo prevents Mouse Gesture Events extension from functioning on links that were opened as new tab

### ISSUE THREAD

**Issue by smartfonreddit** [uBlockOrigin/uBlock-issues#2241]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Hello and thanks for the wonderful extension.

The issue began this morning while using Brave browser, including after creating a new profile and reconfiguring it. When I navigate to a website then open one of its link in a new tab, the mouse gesture extension does not function on that new tab. I have tried using uBo with barebones. The issue appears to be the extension itself. 

To reproduce the bug faster, you can use the profile that I have for the Mouse Gesture Events extension. Just create a text file "MouseGestureSettings.txt" and insert this, including square brackets:
_[0,1,2,3,8,4,9,4,5,9]_

... and use the extension's restore button to point to the file and load it. Afterward, you should be able to close a tab by holding down the mouse's right button and swiping down, as an example. 

### A specific URL where the issue occurs

https://www.dailymail.co.uk/ushome/index.html

### Steps to Reproduce

Open any article in a new background tab on these sites, and use a swipe-down gesture to attempt to close the tab: washingtonpost.com, dailymail.co.uk.

No problem on news.yahoo.com.

### Expected behavior

The gesture extension should close the tab.

### Actual behavior

A context menu popup opens, as if the browser recognized the mouse gesture as a simple right click.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Chromium: 105
filterset (summary): 
  network: 80432
  cosmetic: 45243
  scriptlet: 17653
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    easylist: 69310-51, never
    easyprivacy: 27312-123, never
    plowe-0: 3634-776, never
    ublock-abuse: 76-0, never
    ublock-badware: 4233-92, never
    ublock-filters: 32512-100, never
    ublock-privacy: 231-3, never
    ublock-quick-fixes: 389-37, never
    ublock-unbreak: 1858-43, never
    urlhaus-1: 5164-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1027 ms
  maxAssetCacheWait: 173 ms
```
</details>

**Comment by gothic-bum** [comment]
> When I navigate to a website then open one of its link in a new tab, the mouse gesture extension does not function on that new tab.
  
> The issue appears to be the extension itself.

Just to be clear:
Are you saying that the issue *only* occurs with the "mouse gesture" extension?
And if so, how is this a uBO issue?

**Comment by smartfonreddit** [comment]
>Are you saying that the issue _only_ occurs with the "mouse gesture" extension? 

Yes. I just tried the CrxMouse gesture extension and there was no conflict with that one. 

>And if so, how is this a uBO issue?

Just an assumption. The mouse gesture extension has not been updated since 2019, while uBo receives regular updates with the latest one being last week, so I assumed it might be a uBo bug.

**Comment by gothic-bum** [comment]
> The mouse gesture extension has not been updated since 2019, while uBo receives regular updates with the latest one being last week, so I assumed it might be a uBo bug.

In that case, I'd strongly suggest that you raise this issue with the developer(s) of the "mouse gesture extension" who may need to provide an update to an extension that is several years old.
  
There is a *single* developer for uBO, which is an extension used by millions of users. Out of respect for all of his efforts and his personal life/time, perhaps he shouldn't be burdened with issues that aren't directly related to uBO.

**Comment by gwarser** [comment]
Does not work with uBO disabled.
