### ISSUE TITLE
Disable prefetching option breaks site functionality

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2246]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Screenshots won't open

The only way to solve the problem is to open `about:config` and set `network.prefetch-next` to `true`.

### A specific URL where the issue occurs

`https://www.softportal.com/software-48911-microsoft-outlook-lite.html`

### Steps to Reproduce

Click on screenshot

<details>
<summary>Screenshot(s)</summary>

![softportal](https://user-images.githubusercontent.com/20126984/188714697-3a6d6491-4901-4432-b495-8db4c148a581.JPG)

</details>

### Expected behavior

A screenshot will open

### Actual behavior

Screenshots won't open

### uBlock Origin version

uBlock Origin: 1.44.2

### Browser name and version

Firefox: 104

### Operating System and version

Windows 7

**Comment by gorhill** [comment]
uBO just toggles `networkPredictionEnabled` through [browser.privacy.network()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/network#properties) API. When the image is clicked, there is a network request for a script resource, and uBO does not interfere with this. Looks like a Firefox issue.

**Comment by dimisa-RUAdList** [comment]
If you remove uBlock Origin and set the default about:config values, the screenshots open. However, a new installation of uBlock Origin causes the screenshots to stop opening.

**Comment by gorhill** [comment]
As said, it's just a toggle of a browser setting. I can't fix this any other way than **not** toggling the browser setting. You will have to report to Firefox.

**Comment by gwarser** [comment]
I have "Disable pre-fetching (to prevent any connection for blocked network requests)" turned off and image does not open.

**Comment by dimisa-RUAdList** [comment]
@gwarser 
And what is the value of `network.prefetch-next` in `about:config`?

**Comment by gwarser** [comment]
`true`

**Comment by dimisa-RUAdList** [comment]
Perhaps geospecificity also plays a role. For Russian users with this setting, screenshots open.

**Comment by gorhill** [comment]
I could reproduce the issue.

**Comment by gwarser** [comment]
For me, image open only after a refresh. Even in clean profile (Fx 103.0.2, first time I open this page, image will not load on click.

**Comment by dimisa-RUAdList** [comment]
Added a rule to open screenshots individually: https://github.com/easylist/ruadlist/commit/ebc9ed0a045e36f2773f2e65598c2554311d1805
