### ISSUE TITLE
Generic cosmetic filter apply only to first tab from set of same domain tabs opened in a row

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#2248]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

After opening articles from my RSS reader, I often notice that cookie dialogs are not hidden. Turns out they are hidden in only one tab for pages from one domain. Often happens on `olx.pl` and I also noticed it in `inpost.pl` delivery tracking pages. Cannot be immediately reproduced again in the same session.

Looks like uBO refuses to fetch the same generic filters in quick succession from "cold" state, but it works fine when is "warm".

I cannot reproduce on `example.com` when trying simple `##h1`, maybe it happens only for elements which appear after delay?

Maybe cannot be reproduced in the same session because generic filters are cached?

Also see (internal) https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/300  
and maybe https://github.com/uBlockOrigin/uBlock-issues/discussions/1998#discussioncomment-3581812

### A specific URL where the issue occurs

https://inpost.pl/sledzenie-przesylek?number=632700559222470116889740

### Steps to Reproduce

1. subscribe to EasyList Cookie
1. add bookmarks:
	  ```
	  https://inpost.pl/sledzenie-przesylek?number=632700559222470326886740
	  https://inpost.pl/sledzenie-przesylek?number=685744659222470321776342
	  https://inpost.pl/sledzenie-przesylek?number=616002559222470324181833
	  ```
1. start fresh session
1. open above bookmarks one by one quickly

### Expected behavior

After switching to opened tabs no cookie dialog will be visible.

### Actual behavior

Cookie dialog flashes and disappears in first tab, stays visible in two other.

Side note - logger show only one set of cosmetic filters.

### Configuration

Seems to be very old behavior, when I tested it earlier, I was able to track it back to Firefox 80 and uBO 1.20.

Can be reproduced both in Chrome and Firefox.

<details>

```yaml
uBlock Origin: 1.44.2
Chromium: 105
filterset (summary): 
  network: 83513
  cosmetic: 79136
  scriptlet: 19487
  html: 0
listset (total-discarded, last updated): 
  added: 
    fanboy-cookiemonster: 40880-102, now
  default: 
    user-filters: 0-0, never
    easylist: 64873-51, now
    easyprivacy: 27492-126, now
    plowe-0: 3671-814, now
    ublock-abuse: 76-0, now
    ublock-badware: 4222-101, now
    ublock-filters: 32565-123, now
    ublock-privacy: 251-1, now
    ublock-quick-fixes: 430-2, now
    ublock-unbreak: 1850-42, now
    urlhaus-1: 7346-0, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 801 ms
  maxAssetCacheWait: 222 ms
popupPanel: 
  blocked: 1
  blockedDetails: 
    inpost.pl: 1

```
</details>

**Comment by krystian3w** [comment]
On my side many cookie bar/pop-ups now blinks, maybe needed is reduce old generic filter in ELC and IDCAC.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/13443

**Comment by dportvine** [comment]
When I open many new tabs, the hide rule ##.ya-share2 doesn't work everywhere. But if I add *##.ya-share2 to my filters, hiding works on all tabs.
You need to add BitBlock https://easylist-downloads.adblockplus.org/bitblock.txt
Example: `https://nnmclub.to/`
[Gif](https://imgur.com/NaMwnw7)

There is no such thing in ABP.

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 100373
  cosmetic: 125747
  scriptlet: 22799
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31530-27, now
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1534-24, now
    fanboy-cookiemonster: 42500-284, now
    ublock-annoyances: 4732-52, now
  default: 
    user-filters: 7-0, never
    RUS-0: 39907-147, now
    easylist: 62747-83, now
    easyprivacy: 30841-1590, now
    ublock-abuse: 76-1, now
    ublock-badware: 3953-103, now
    ublock-filters: 31143-184, now
    ublock-privacy: 260-8, now
    ublock-quick-fixes: 462-20, now
    ublock-unbreak: 1890-45, now
filterset (user): [array of 5 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 414 ms (selfie)
  maxAssetCacheWait: 653 ms
```
</details>

**Comment by gwarser** [comment]
Cannot reproduce on this page because of Cloudflare check, but symptoms looks similar.

**Comment by krystian3w** [comment]
Maybe disqus iframes with social button also worth (as long have real src attribute) - but in test does not help inject with domain specified.

**Comment by gorhill** [comment]
Problem is probably [there](https://github.com/gorhill/uBlock/blob/2204451514f1a894a7627793a253a89ebbc6d845/src/js/cosmetic-filtering.js#L863).

The code there assumes that the cached generic filters have been injected, but there is no guarantee it's the case given the asynchronicity. I will try to fix over the weekend.

**Comment by gwarser** [comment]
I can reproduce on `nnmclub` now, and fix seems to work for it and for `inpost` on Chrome

**Comment by gorhill** [comment]
> 2. add bookmarks

For reference, instead of having to click quickly, I just added the bookmarks to a bookmark folder and used right-click => "Open all", this was easier to reproduce.

**Comment by dportvine** [comment]
Works great! Tnx.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/26594fb902b1042843ebda1ab3b3aa6304ed3ae9#commitcomment-92413254

**Comment by Yuki2718** [comment]
Not directly related, but on Chrome with 1.46 I have very occasionally seen generic cosmetic filters not applied to sites. Once this happens, refreshing many times does not help. manually applying cosmetic filter such as `##ins.adsbygoogle` via picker somehow solves this as if now uBO "remembered" applying generic cosmetic filters.

**Comment by krystian3w** [comment]
On mobile with changed settings (enabled forced hide by generic) I saw again share buttons ("links") on disqus plugin.
