### ISSUE TITLE
`#?#selector:not(selector)` was malformed to empty `...:not()`

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2262]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-1242981211

or

https://github.com/uBlockOrigin/uBlock-issues/issues/2228#issuecomment-1238957269

plus

https://github.com/AdguardTeam/AdguardFilters/issues/112718#issuecomment-1244037242 + https://github.com/AdguardTeam/AdguardFilters/issues/112718#issuecomment-1244145195

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/discussions/2262

### Steps to Reproduce

1. open example page
2. try in block `<a>` in Element Picker with exclude `uBlock-issues` links: 
  `#?#a[href]:not([href*="uBlock-issues"])`

### Expected behavior

* Excluded links shoudn't be hidden (only 57 instead almost all 79) - e.g. AdGuard can not share list with removed almost all `?` and `$?` so Twitter can by broken with his list https://github.com/AdguardTeam/AdguardFilters/issues/112718#issuecomment-1243423178.

   Also Reporter said AdGuard filter no works in vanilla syntax:
     https://github.com/AdguardTeam/AdguardFilters/issues/112718#issuecomment-1244037242 + https://github.com/AdguardTeam/AdguardFilters/issues/112718#issuecomment-1244145195

* In logger filter shouldn't malformed.

### Actual behavior

* As see excluded links can be visible (no more than ~57 matches).

* In Logger filter is "malformed" to `##a[href]:not()`

### uBlock Origin version

1.44.2

### Browser name and version

Firefox 104, Chrome 105

### Operating System and version

Windows 7/10

**Comment by peace2000** [comment]
The reason why this is especially bad is that the rule won't just stop working... The `:not()` part is ignored totally, causing incorrect blocking.

Another sample: `https://www.iltalehti.fi/ulkomaat/a/b250ecc0-4f6d-4084-b712-50668d37a227`

![kuva](https://user-images.githubusercontent.com/17256841/189750833-ed655563-3c92-442b-960c-dcb6bf9d46bf.png)

Now I'll add `?` between `##` and the `:not()` part will be ignored totally:

![kuva](https://user-images.githubusercontent.com/17256841/189751006-7860f95d-e504-440a-8a66-7e77ce6204ac.png)

**Comment by gorhill** [comment]
Why add `?` when there is no need to? The guideline for when to use `?` is when a `:has()` filter does not work as expected on Chromium 105+. Not using `?` is the preferred way because the filter can end up declarative with `:has()`.

**Comment by krystian3w** [comment]
But then needed is ask AdGuard team to change this at FilterRegistry repository level if still write own fix for support vanilla CSS `:has()` in library ExtendedCSS 2.0.

IMO his team don't delete almost all `?` in origin files before new ExtendedCSS library was be published to own environment.

I do not know if anyone share bad works vanilla `:has` if Twitter example is bad (and work for you after delete `?`) and bad is `#?#a:not(a)` who match all `<a>`.

**Comment by krystian3w** [comment]
I can only recommend keeping a cool mind.

As someone who grasps JS can try to do an investigation into why `:not(...)` with selectors is malformed at logger level to an empty `"not()` and acts as if it doesn't exist in the filter.

**Comment by gorhill** [comment]
If people can confirm the fix works without regression, I will publish a emergency revision.

**Comment by Yuki2718** [comment]
I can't say I have thorougly tested, but it looks v1.44.3b5 is working properly.

**Comment by stephenhawk8054** [comment]
I'm at v1.44.3b8 and looks like it works too.

**Comment by Yuki2718** [comment]
1.44.3b7 on Chrome filter update never ends.

**Comment by krystian3w** [comment]
IMO I can not check 0 (does not exists) childs in parent if fail `:empty` (and still don't works `:only-white-space`):

```adb
forum.dobreprogramy.pl##.loading-container:not(:has(> *))
forum.dobreprogramy.pl#?#.loading-container:not(:has(> *))
```

(match elements with childs)

but works (but no compatible with AdGuard env.):

```adb
forum.dobreprogramy.pl##.loading-container:not(> *)
```

Loading is active after change topic on example forum.

due https://github.com/uBlockOrigin/uBlock-issues/issues/612 https://github.com/uBlockOrigin/uBlock-issues/discussions/2109

**Comment by gorhill** [comment]
I am currently rewriting the procedural cosmetic filter parser using [css-tree](https://github.com/csstree/csstree), that fix all issues with parsing incorrectly.
