### ISSUE TITLE
uBlock Origin

### ISSUE THREAD

**Issue by Bolteko** [uBlockOrigin/uBlock-issues#227]
L'extension uBlock Origin installe un cookie mouchard dans le navigateur internet ( Mozilla Firefox et peut être dans d'autres navigateurs internet ), détectable et effaçable seulement avec le logiciel de nettoyage CCleaner.

**Comment by gorhill** [comment]
Nonsense.

If you want to make such extraordinary claim, provide evidence.

**Comment by Bolteko** [comment]
Installez et ouvrez le logiciel CCleaner, ensuite allez dans option puis Cookies, vous verrez qu'il y a bien un cookie mouchard qui vient de uBlock Origin qui est détectable et effaçable seulement avec CCleaner.

**Comment by uBlock-user** [comment]
> there is a cookie cookie that comes from uBlock Origin

![](https://i.gyazo.com/b5cb598da6520e7903f739b0626d386e.png)

None, whatsoever.

**Comment by Bolteko** [comment]
Avez-vous fait ce test avec un profil Firefox que vous utilisez tous les jours et en paramétrant bien comme il faut uBlock Origin ?

Je suis sur Windows 8.1 64Bit, Firefox 62 64Bit et CCleaner détecte bien ce cookie mouchard qui vient de uBlock Origin...

**Comment by Bolteko** [comment]
Je suis sûr que vous voyez de quoi je parle, ne me prenez pas pour un con, c'est dans votre habitude de le faire et aussi vous refusez pratiquement toutes les demandes de nouvelles fonctionnalités.
Vous faite la sourde oreille pour ne pas lancer de doutes à vos utilisateurs, vous et votre équipe êtes des menteurs et des espions ! Vous êtes démasqués...

Je vais désinstaller votre bloqueur de pub et à la place, je vais réinstaller Adguard Adblocker qui est bien plus puissant en terme de blocage de pubs et n'installe pas de cookie mouchard dans le navigateur.

**Comment by uBlock-user** [comment]
Should have locked sooner, no gain in entertaining trolls like him.
