### ISSUE TITLE
Can't view ubo list content

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#2271]
### Discussed in https://github.com/uBlockOrigin/uBlock-issues/discussions/2189

<div type='discussions-op-text'>

<sup>Originally posted by **ghajini** July 28, 2022</sup>
With Firefox android nightly 105.01a1 & stable 103
when i want to view ublock filters content by going into ubo dashboard=> filter lists => ublock filters => click eye menu to see contents=> results in blank page

![Screenshot_20220728-233221~2](https://user-images.githubusercontent.com/20338483/181606861-09c132ea-2ba3-46de-8e24-3d654ffa1eec.png)

is this firefox side bug ?
any thoughts @gorhill </div>

**Comment by RicoHeat** [comment]
I am also having the same issue using Fennec Browser (F-Droid) 
I'm having to first copy the link and then pasting it in a new tab for asset viewer. 👁

**Comment by gorhill** [comment]
I couldn't find anything wrong when the tab loads. There is no error occurring. Strangely, the tab is finally rendered when I select the Inspector pane in dev tools. I don't know what is blocking the rendering, and since this all used to work it does appear so far to be something not happening on Firefox's side.

**Comment by Rob--W** [comment]
I've reported this issue along with more details from debugging at https://bugzilla.mozilla.org/show_bug.cgi?id=1797558

**Comment by gorhill** [comment]
Another workaround is to close the tab than immediately tab Undo.

**Comment by krystian3w** [comment]
Looks fixed on Nightly 119, so possible close on October 2023.

**Comment by Rob--W** [comment]
We have started the experiment to enable the extension process, on Nightly, and a part of Beta. That fixes this bug as mentioned at https://bugzilla.mozilla.org/show_bug.cgi?id=1797558#c29

If the experiment is successful, the extension process will also roll out to release eventually.

**Comment by gorhill** [comment]
Confirmed fixed in Nightly.
