### ISSUE TITLE
Extension Policy does not work on Mac

### ISSUE THREAD

**Issue by crazt0n** [uBlockOrigin/uBlock-issues#2277]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I've been trying to add local policies for uBlock on Mac. However, when browsing to chrome://policies there are no imported policies. I've tried using mcximport as described on the documentation and creating the .plist file on the ~/Library/Preferences folder.

I've tried the same method with other extensions and it appears to be something specific to uBlock on Mac.

### A specific URL where the issue occurs

chrome://policies

### Steps to Reproduce

1. create the following .plist file on ~/Library/Preferences
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>userSettings</key>
        <dict><key>userSettings</key><false/></dict>
</dict>
</plist>
```
2. run ```defaults read com.google.Chrome.extensions.cjpalhdlnbpafiamejdnhcphjbkeiagm.plist```
3. Restart chrome
4. Check applied policies on chrome://policies

### Expected behavior

uBlock policy to be added on chrome.

### Actual behavior

No policy was added.

### uBlock Origin version

1.44.4

### Browser name and version

Chrome 105.0.5195.125 

### Operating System and version

macOS Monterey 12.5

**Comment by gwarser** [comment]
Isn't this before even uBO can touch it? System or browser issue? Or maybe your syntax is just wrong?

**Comment by crazt0n** [comment]
I’ve tried it on other Macs as well, but so far I haven’t had much success.. Also, I’ve tried using same syntax for other extensions and it worked fine. (Changing the extension id on the plist filename and the policy key in the xml file).

**Comment by gwarser** [comment]
Maybe these other add-ons have more relaxed schema and your keys don't exists in uBO schema?

**Comment by gorhill** [comment]
I won't be able to help with that sort of issue, this has to be investigated by someone who does that sort of policy work on MacOS. Given as far as I know policies work in Chromium and Firefox, the issue is likely not in uBO, and if it is, someone will have to pinpoint exactly where in the code.

**Comment by crazt0n** [comment]
Interesting, the extension I've tried to setup was this one: https://github.com/pixiebrix/pixiebrix-extension. Their managed storage JSON file does not appear to be so different https://github.com/pixiebrix/pixiebrix-extension/blob/main/static/managedStorageSchema.json. I wonder if any of the differences might be causing this?

I wonder if anyone managed to make it work on Mac with any policy for uBO. If there was an example (from someone who managed to make it work) I believe I could follow from it.

**Comment by gorhill** [comment]
In uBO's managed storage scheme, `userSettings` is an array. Each item in that array are a pair of strings representing the name of the setting and the value. Each pair is in an array, i.e. `[ 'settingname', 'value' ]`. How how this translate into your policy tool, I wouldn't know. I see in your opening comment:

        <key>userSettings</key>
        <dict><key>userSettings</key><false/></dict>

What is this meant to do?

**Comment by crazt0n** [comment]
That is correct. My bad, it was my formatting that was incorrect. I'm sharing my plist as example here for further reference:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>userSettings</key>
            <array>
                <array>
	            <string>colorBlindFriendly</string>
                    <string>true</string>
                </array>
            </array>
</dict>
</plist>```

**Comment by crazt0n** [comment]
Not sure if this is related. But for some reason even after having the policy added to chrome (adminSettings) and restarted the browser, it doesn't get loaded. uBO continues with the same settings, am I missing something?

I've tried all the available policies, but none of them seem to have any effect. I've tried both these .plists here (escaped and unescaped version):

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>adminSettings</key>
<string>{"timeStamp":1618561470188,"version":"1.34.0","userSettings":{"externalLists":"https://www.i-dont-care-about-cookies.eu/abp/","importedLists":["https://www.i-dont-care-about-cookies.eu/abp/"]},"selectedFilterLists":["user-filters","ublock-filters","ublock-badware","ublock-privacy","ublock-abuse","ublock-unbreak","easylist","easyprivacy","urlhaus-1","plowe-0","spa-1","spa-0","https://www.i-dont-care-about-cookies.eu/abp/"],"hiddenSettings":{},"whitelist":["about-scheme","chrome-extension-scheme","chrome-scheme","edge-scheme","moz-extension-scheme","opera-scheme","vivaldi-scheme","wyciwyg-scheme"],"dynamicFilteringString":"behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop","urlFilteringString":"","hostnameSwitchesString":"no-large-media: behind-the-scene false","userFilters":""}</string>
</dict>
</plist>`

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>adminSettings</key>
<string>{\"timeStamp\":1618561470188,\"version\":\"1.34.0\",\"userSettings\":{\"externalLists\":\"https://www.i-dont-care-about-cookies.eu/abp/\",\"importedLists\":[\"https://www.i-dont-care-about-cookies.eu/abp/\"]},\"selectedFilterLists\":[\"user-filters\",\"ublock-filters\",\"ublock-badware\",\"ublock-privacy\",\"ublock-abuse\",\"ublock-unbreak\",\"easylist\",\"easyprivacy\",\"urlhaus-1\",\"plowe-0\",\"spa-1\",\"spa-0\",\"https://www.i-dont-care-about-cookies.eu/abp/\"],\"hiddenSettings\":{},\"whitelist\":[\"about-scheme\",\"chrome-extension-scheme\",\"chrome-scheme\",\"edge-scheme\",\"moz-extension-scheme\",\"opera-scheme\",\"vivaldi-scheme\",\"wyciwyg-scheme\"],\"dynamicFilteringString\":\"behind-the-scene * * noop\\nbehind-the-scene * inline-script noop\\nbehind-the-scene * 1p-script noop\\nbehind-the-scene * 3p-script noop\\nbehind-the-scene * 3p-frame noop\\nbehind-the-scene * image noop\\nbehind-the-scene * 3p noop\",\"urlFilteringString\":\"\",\"hostnameSwitchesString\":\"no-large-media: behind-the-scene false\",\"userFilters\":\"\"}</string>
</dict>
</plist>`

**Comment by gwarser** [comment]
Sometimes two restarts can be needed.

**Comment by gorhill** [comment]
Your first value fails in JSON Lint, you need to fix this. You shouldn't need to escape from what I understand of your template usage.

**Comment by crazt0n** [comment]
I've tried putting the unescaped version on JSON Lint and apparently worked:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/106328617/192044557-e479ab2b-03e1-48ba-b204-8867046624cb.png">

I've also tried restarting the browser/computer, reloading the extension, but it doesn't seem to reflect the policy. I tried with another simpler policy (advancedSettings), it gets added to chrome://policy but doesn't reflect on the extension settings:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>advancedSettings</key><array><array><string>disableWebAssembly</string><string>true</string></array></array>
</dict>
</plist>`

**Comment by crazt0n** [comment]
Does anyone have a policy example of how to make it work on Mac and Chrome? So far I've tried different machines and multiple restarts without success...

**Comment by gorhill** [comment]
Stale issue, and nothing actionable for uBO: policies work fine in Firefox/Chrome?Windows/Linux, so issue has to be outside uBO.
