### ISSUE TITLE
uBlock Origin 1.44.4 - Firefox 105.0 (64 bit) - MacOS 12.6 - after a while, "your filters" stop working. After restarting Firefox, they work again for a while.

### ISSUE THREAD

**Issue by Howking007** [uBlockOrigin/uBlock-issues#2279]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

uBlock Origin 1.44.4 - Firefox 105.0 (64 bit) - MacOS 12.6 - after a while, "your filters" stop working. After restarting Firefox, they work again for a while.

### A specific URL where the issue occurs

facebook.com

### Steps to Reproduce

browsing.... Block facebook advertising

```
hofyland.cz##form > div.okno:has-text(/ANDERUSO/)

! Návrhy
facebook.com##div[role="feed"] > div div[data-0]:remove()
facebook.com##div[role="feed"] > span div[data-0]:remove()
facebook.com##[role="feed"]>div, [role="feed"]>span:has-text(/^(Koho možná znáte|Návrhy pro vás|Sekvence a krátká videa)/)
!:style(border:1px solid yellow)

! Reklamy
facebook.com##[role="feed"] span[id] a[href="#"] :matches-css(display: none):remove()
facebook.com##[role="feed"] span[id] a[href="#"] :matches-css(position: absolute):remove()
facebook.com##[role="feed"] span[id] a[href="#"]:not(:has-text(/(\s|\d|^$)/)):upward([role="feed"]>div, [role="feed"]>span)
!:style(border: 1px dotted yellow !important)

! Nevyžádaná funkcionalita
facebook.com##.cbwvpmhb.o2nd8wht.gvxzyvdx

!https://nyx.cz
!nyx.cz##.wr-1.w > .wh > .d.actions > .rating
!nyx.cz##.wr-2.w > .wh > .d.actions > .rating
!nyx.cz##.wr-3.w > .wh > .d.actions > .rating
!nyx.cz##.wr-4.w > .wh > .d.actions > .rating
!nyx.cz##.wr-5.w > .wh > .d.actions > .rating
!nyx.cz##.wr-6.w > .wh > .d.actions > .rating
!nyx.cz##.wr-7.w > .wh > .d.actions > .rating
!nyx.cz##.wr-8.w > .wh > .d.actions > .rating
!nyx.cz##.wr-9.w > .wh > .d.actions > .rating
!nyx.cz##.wr-10.w > .wh > .d.actions > .rating
!nyx.cz##.negative

runkeeper.com###onetrust-consent-sdk
```

### Expected behavior

uBlock Origin 1.44.4 - Firefox 105.0 (64 bit) - MacOS 12.6 - after a while, "your filters" stop working. After restarting Firefox, they work again for a while.

### Actual behavior

uBlock Origin 1.44.4 - Firefox 105.0 (64 bit) - MacOS 12.6 - after a while, "your filters" stop working. After restarting Firefox, they work again for a while.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 230643
  cosmetic: 170894
  scriptlet: 36241
  html: 771
listset (total-discarded, last updated): 
  added: 
    adguard-generic: 70016-5163, 1h.30m
    adguard-mobile: 8132-189, 1h.30m
    adguard-spyware: 27414-1952, 1h.30m
    adguard-spyware-url: 763-3, 1h.30m
    block-lan: 44-0, 1h.30m
    curben-phishing: 96121-8, 1h.29m
    curben-pup: 192-0, 1h.29m
    adguard-social: 18616-1066, 1h.29m
    fanboy-thirdparty_social: 69-0, 1h.29m
    fanboy-annoyance: 80602-64652, 1h.29m
    fanboy-cookiemonster: 41090-136, 1h.29m
    fanboy-social: 23360-28, 1h.28m
    ublock-annoyances: 4847-4, 1h.28m
    dpollock-0: 11389-484, 1h.28m
  default: 
    user-filters: 9-0, never
    ublock-filters: 33580-81, 1h.30m
    ublock-badware: 4209-0, 1h.30m
    ublock-privacy: 268-0, 1h.30m
    ublock-abuse: 76-0, 1h.30m
    ublock-unbreak: 1872-1, 1h.30m
    ublock-quick-fixes: 237-0, 1h.30m
    easylist: 62950-977, 1h.30m
    easyprivacy: 30630-14456, 1h.29m
    urlhaus-1: 7076-0, 1h.29m
    plowe-0: 3673-3, 1h.28m
    CZE-0: 725-0, 1h.28m
filterset (user): [array of 9 redacted]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 252 ms (selfie)
  maxAssetCacheWait: 176 ms
```
</details>

**Comment by gorhill** [comment]
Investigate more on your side please, I never had such issue. It could be that your WebExtensions process dies for some reasons, and if so, it's for you to investigate.

**Comment by gorhill** [comment]
Also, _"your filters" stop working_ is too vague, your are not pointing out **exactly** which filters stop working, so definitely not something we can even try to reproduce assuming we had huge amount of free time to spend. For all we know, your procedural cosmetic filters might be too expensive to execute, in which case uBO will disable them. Investigate more on your side please to narrow down whether it's all your filters or some very specific ones on a specific site.

**Comment by Howking007** [comment]
I'm sorry for the unnecessary panic. Facebook apparently changed the format of the ad posts and it didn't change all at once, but it went old school for a while and new for a while. I thought uBlock might be crashing. It wasn't.
