### ISSUE TITLE
Picker icons toggle on/off in one second interval

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#228]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Picker and Zapper icons in uBO popup appear and disappear constantly when popup opened for first "New Tab" page after browser startup.

### A specific URL where the issue occurs

First "New tab" page after browser startup.
With "Restore previous session" turned on, may also happen for about:addons and about:about, cannot reproduce on about:memory or about:preferences

### Steps to Reproduce

1. Start Firefox
2. Click uBO icon
3. Look for Picker and Zapper icon

### Expected behavior:

On "New Tab" page Picker icon should not be visible
Also uBO icon should be grey.

### Actual behavior:

uBO icon is red.

Picker icons will be visible for one second then start alternating between visible / invisible state

![gif](https://user-images.githubusercontent.com/886325/45707710-f0cce280-bb7f-11e8-8e4d-a2f1d08fbeaa.gif)

### Your environment

* uBlock Origin version: 1.16.21rc0
* Browser Name and version: Firefox stable, beta, nightly
* Operating System and version: Mint 18.3

**Comment by uBlock-user** [comment]
> Picker icons will be visible for one second then start alternating between visible / invisible state

I can reproduce only that.

**Comment by gwarser** [comment]
Blinking icons fixed. Icon color was last-minute observation and is probably unrelated.
