### ISSUE TITLE
Edge stop loading pages because of uBlock

### ISSUE THREAD

**Issue by Tabajara77** [uBlockOrigin/uBlock-issues#2282]
![edgeblockissue](https://user-images.githubusercontent.com/4042019/191983622-f743f1b7-1229-45e7-b741-2db1cb93d2f5.png)
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Current all up to dated Edge and Windows 10, Microsoft Edge doesn't load any pages with uBlock enabled (I have previously restarted both my PC and modem, changed some firewall stuff, rolled back some Windows Update I installed recently and no dice).

I had to disable the extension entirely to make it all work again. This seemed to happen during midnight when I was playing a Steam game and probably Windows Update checking for updates I assume (which is why I tried to uninstall it, restarted but didn't do much.)

### A specific URL where the issue occurs.

Everywhere

### Steps to Reproduce

1. Have the latest Edge running.
2. Open Edge with uBlock enabled.
3. Doesn't load any pages. But you can STILL see some stuff loading like your home news and your Microsoft account rewards, sync, etc.
4. The moment you disable uBlock, all the pages load normally again.

### Expected behavior

Normal working web browser.

### Actual behavior

Seems like I'm not connected to the Internet but I'm. No loading pages (infinite loading). Home/news seems to load some stuff tho.

### uBO version

1.44.4

### Browser name and version

Microsoft Edge latest build 105.0.1343.50

### Operating System and version

Windows 10 Pro - 21H2 build 19044.2075

**Comment by btcoolboy** [comment]
I get log for the issue.
![20220924005953](https://user-images.githubusercontent.com/61384451/192013779-1705ea9f-1ca2-4d07-a7f4-7c745923a4aa.png)

**Comment by btcoolboy** [comment]
Fixed by cleaning up filter cache then update again.

**Comment by Tabajara77** [comment]
UPDATE: I think it was disabled already. I removed and reinstalled uBlock (reseted every setting) and seems to be working again. I don't know what was causing the problem. Sorry for any inconvenience.
