### ISSUE TITLE
突然拦截京东

### ISSUE THREAD

**Issue by flzt-aox** [uBlockOrigin/uBlock-issues#2286]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

打开京东网站，闪一上就没了，禁用此插件正常！

### A specific URL where the issue occurs.

www.jd.com

### Steps to Reproduce

1.打开京东
2.闪一下就没了

### Expected behavior

希望能修复

### Actual behavior

打不开京东

### uBO version

uBlock Origin 1.44.4

### Browser name and version

谷歌 版本 105.0.5195.102（正式版本） （64 位）

### Operating System and version

win11,22H2

**Comment by gothic-bum** [comment]
Fixed 2 days ago:
https://github.com/uBlockOrigin/uAssets/commit/3768a04a2e19c59b724b775f4cc1046e1c74b37d

Force an update of your filter lists:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now
