### ISSUE TITLE
hiding/unhiding problems with matches-path operator (GIF included)

### ISSUE THREAD

**Issue by SublimeAnanas** [uBlockOrigin/uBlock-issues#2290]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I created a one line filter for youtube.com which hides all the recommended videos only on `youtube.com` and nowhere else:

`www.youtube.com##:matches-path(/^/$/) #primary .ytd-two-column-browse-results-renderer.style-scope`

I couldn't find a youtube homepage specific recommended videos section element, so I had to go with the `matches path` operator.

This works perfectly, apart from one issue: the elements are **unhidden** for a split second when navigating away from the specified URL, **even when the page is still visible** in the browser. Please see the screen recording GIF to see precisely what I mean. 

This issue is present with any `matches path` condition I tested.

This behavior of the `matches path ` operator makes it cumbersome to use, and in some instances you are completely forced to use a different operator even though `matches path `would be the best solution.

_Another, more subtle problem closely related to this one is that elements are loaded before ublock executes the matches path filter line, therefore the elements are shown for a split second during page load too. This issue is shown in the GIF as well._

https://user-images.githubusercontent.com/100245457/192305314-50e90b58-6d2e-4ba8-a515-cf4ba449f1cf.mp4

### A specific URL where the issue occurs.

youtube.com

### Steps to Reproduce

1. use `matches-path `in a filter code line
2. refresh or navigate away from the URL specified in `matches path`

### Expected behavior

elements specified in the filter line remain hidden

### Actual behavior

elements are unhid the moment a link is clicked, therefore showing for the entire duration that is between clicking a link and loading a new page

https://user-images.githubusercontent.com/100245457/192305249-255ce292-de9c-45ba-aed9-04e04a743174.mp4

### uBO version

1.44.4

### Browser name and version

Firefox: 105

### Operating System and version

Windows 10

**Comment by SublimeAnanas** [comment]
@MasterKia Thank you, it's actually quite relevant I believe, as their solution of hiding the homepage recommended videos does not present any of the issues that my matches path solution does.

Adding their solution here for convenience for anyone that wants to compare:
`www.youtube.com##ytd-browse[page-subtype="home"]`

Here's a GIF using this filter instead of the one in the OP:

https://user-images.githubusercontent.com/100245457/192314208-06ae0876-e211-46fc-9974-fa421359bb63.mp4

I believe this perfectly highlights the difference in behavior of any operator and the `matches-path` one.

**Comment by gorhill** [comment]
Once you clicked the magnifier, notice that the URL in the address bar changed, and as a result your `:matches-path`-based filters no longer matched, and those it sopped hiding the elements. The issue is more Youtube taking a bit of time to refresh the DOM as a result of you searching something.

**Comment by gorhill** [comment]
If you do not want you `:matches-path()` based filter to cause targeted elements to be brought back once the URL in the address bar changed (and as a result no longer matches), just use `:remove()` at the end of the filter:

    www.youtube.com##:matches-path(/^/$/) #primary .ytd-two-column-browse-results-renderer.style-scope:remove()

**Comment by SublimeAnanas** [comment]
@gorhill Should I make a new Issue for the other mentioned problem? I believe your explanation doesn't apply to it:

"Another, more subtle problem closely related to this one is that elements are loaded before ublock executes the matches path filter line, therefore the elements are shown for a split second during page load too. This issue is shown in the GIF as well."

You can see this at 3-4 seconds of the first GIF, and seems to be specific to `matches-path`. Notice how in the second GIF, the video title/thumbnail/views/etc does not show at all.

**Comment by gorhill** [comment]
Procedural cosmetic filters require JS code to find and hide elements, and this code execute when uBO is told the DOM has changed, so it's not possible to expect procedural cosmetic filtering to be completely devoid of visual glitches.

**Comment by gorhill** [comment]
uBO is already watching the DOM for changes, `watch-attr` is useless if a procedural filter does not depend on an attribute, the purpose of `watch-attr` is to just observer attribute changes, which is also an asynchronous operation, all changes are processed through a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). Those visual glitches are intrinsic to procedural operators, and they depend also a lot on how a web page is designed, and the performance of one's computer. For example, on my side I don't see visual glitch here: <https://gorhill.github.io/uBlock/tests/procedural-cosmetic-filters.html>.

**Comment by SublimeAnanas** [comment]
Gorhill apologies for bumping this two weeks later, I just wanted to let you know I appreciate your willingness to explain the reasons for this particular behaviour. It helps in understanding the nuances of your extension which in turn allows me to more effectively contribute to filter lists and help people out in the subreddit.
Keep being awesome!
