### ISSUE TITLE
1.44.5 beta 4 - Site www.abandonware.com now is blocked

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uBlock-issues#2291]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I cant see teh content of the site after the update, before i could see it.

### A specific URL where the issue occurs.

https://www.myabandonware.com/browse/name/

### Steps to Reproduce

Just go to the link

### Expected behavior

I wanted to see everything.

### Actual behavior

Only images shown.

### uBO version

1.44.5 beta 4

### Browser name and version

Waterfox

### Operating System and version

Win7

**Comment by gorhill** [comment]
You are not new here, why are you opening a filter issue in the repo which asks you _"I verified that this is not a filter list issue [...]"_?

**Comment by gorhill** [comment]
One more [such invalid issues](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+author%3AFelipefpl+is%3Aclosed), and there will be a block, there is no excuse to disregard rules which purpose is to avoid burdening volunteers.

**Comment by mapx-** [comment]
@gorhill I guess it's cssTree

**Comment by gorhill** [comment]
Sorry, my bad -- issue with `:matches-css-...()`.

**Comment by gorhill** [comment]
@Felipefpl Sorry for having been rude, this was actually a real issue in uBO.

**Comment by Felipefpl** [comment]
gorhill - it's ok, you were right, i should have checked if someone had posted about abandonware before me. I could have done it but didnt want to.
