### ISSUE TITLE
HMTL filtering with procedural filters broken in dev releases past 1.44.5b0

### ISSUE THREAD

**Issue by u-RraaLL** [uBlockOrigin/uBlock-issues#2294]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I updated to 1.44.5b3 yesterday I noticed some of my filters stopped working. In the end I narrowed it down to HTML filters.

After some trial and error it seems that filters such as `example.com##^element:not(:has-text(example))` won't work if compiled on 1.44.5b3+.
The filters do work if compiled on 1.44.5b0, after update to a higher version. But they stop working after recompiling. So on any change to My filters.

### A specific URL where the issue occurs.

https://old.reddit.com/r/uBlockOrigin/

### Steps to Reproduce

1. Install uBO 1.44.5b3-b5.
2. Visit `https://old.reddit.com/r/uBlockOrigin/`
3. Add this filter `old.reddit.com##^.link:not(:has-text(Solved))` and Apply.
4. Refresh uBO's sub.
5. See the filter fail.
6. Drop down to uBO 1.44.5b0.
7. Recompile filters by making any change in My filters and hitting apply.
8. Visit uBO's sub again and see the filter work as expected.

### Expected behavior

HTML filters using procedurals working normally.

### Actual behavior

They don't work past 1.44.5b0.

### uBO version

1.44.5b3-b5

### Browser name and version

Firefox 104.0.2

### Operating System and version

MX Linux 21.2

**Comment by shrekisallah** [comment]
I think its because of this https://github.com/gorhill/uBlock/commit/a71b71e4c8a2037fc68970bc8912a76732edaade

**Comment by gorhill** [comment]
I committed unrelated changes by accident.
