### ISSUE TITLE
Csstree issue? Previewing :style() filter doesn't work properly

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#2296]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When previewing a `:style()` filter, previewing through the element picker shows wrongly how to rule will actually affect the page. Will have to reload the page to see the proper result. This issue is not present with the latest stable uBO.

### A specific URL where the issue occurs.

`https://kssenergia.fi/etusivu`

### Steps to Reproduce

1. Open the page `https://kssenergia.fi/etusivu`
2. Preview rule `##.main-navigation-wrapper:style(position: unset !important)` in the element picker
3. Apply the rule
4. Reload the page

### Expected behavior

Previewing the filter in the element picker would show how to the rule is actually applied to the page.

### Actual behavior

Previewing the rule in the element picker shows wrongly how the rule would affect the page after it's applied. Previewing shows that the rule will make element `.main-navigation-wrapper` to completely disappear. After the page reload, the element will appear as static, as it should, and it won't disappear.

Preview in action:
![kuva](https://user-images.githubusercontent.com/17256841/192628082-786a0c06-7742-401e-8ce6-0a35f3faf5ca.png)

After the page reload, the result of the filter looks different (`.main-navigation-wrapper` is visible):
![kuva](https://user-images.githubusercontent.com/17256841/192628227-cf5b2385-40c3-40f6-ab18-3d4dc0a48760.png)

### uBO version

1.44.5b6

### Browser name and version

Firefox 105.0.1

### Operating System and version

Win 10

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/commit/0cd019ec7d12524931234bde2c769f113795ef92

**Comment by peace2000** [comment]
Oh.. didn't notice that commit. That fix isn't included in test builds yet. Maybe better to leave this open so that no one else will file an issue about this.
