### ISSUE TITLE
Advanced settings Wiki page is slightly out of date

### ISSUE THREAD

**Issue by roastchicken** [uBlockOrigin/uBlock-issues#23]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

# Very Low Priority

### Description

The [Advanced Settings Wiki page](https://github.com/gorhill/uBlock/wiki/Advanced-settings) is slightly out of date; the default value for `manualUpdateAssetFetchPeriod` [has been reduced to 500](https://github.com/gorhill/uBlock/commit/8071321e9104). I opened my advanced settings for the first time today, and wondered why my settings different from the default listed on the Wiki. Additionally, `streamScriptInjectFilters` [has been removed](https://github.com/gorhill/uBlock/commit/427d0fd0fff4b98903b3a90bac0a26cedc506302).

Again, very low priority, but I thought I'd bring it up. Someone might be confused by the contradictions.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/wiki/Advanced-settings

### Steps to Reproduce

1. Open the advanced settings page and the Wiki page.
2. Notice the default `manualUpdateAssetFetchPeriod` is different and `streamScriptInjectFilters` is missing.

### Expected behavior:

The default advanced settings match those listed in the Wiki page.

### Actual behavior:

The default advanced settings don't match those listed in the Wiki page.

### Your environment

* uBlock Origin version: 1.16.2
* Browser Name and version: Chrome 66.0.3359.139 (64-bit)
* Operating System and version: Windows 10, version 1709

**Comment by uBlock-user** [comment]
Yes,  the wiki hasn't been updated to the recent changes. `manualUpdateAssetFetchPeriod` was changed and `streamScriptInjectFilters` because of https://github.com/uBlockOrigin/uBlock-issues/issues/21.

**Comment by uBlock-user** [comment]
@gorhill It appears only contributors can edit wiki, FYI

**Comment by gwarser** [comment]
Not even contributors.

**Comment by gorhill** [comment]
I lifted the restriction, does it work now?

**Comment by gwarser** [comment]
Working, updated just now.

**Comment by roastchicken** [comment]
Thanks!
