### ISSUE TITLE
Opening the logger doesn't work on Firefox for Android (fennec)

### ISSUE THREAD

**Issue by iamsix** [uBlockOrigin/uBlock-issues#230]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Clicking the "Open the logger" button from within the dashboard produces no result. This is somewhat recent as it was working at least a few months ago (sorry I'm not sure of the exact regression window)

### A specific URL where the issue occurs

Any page such as http://github.com

### Steps to Reproduce

1. Within Firefox open the menu - click the 'uBlock Origin' menu Item
2. Within the tab click the 'list' icon to open the logger

### Expected behavior:

The logger should open in a new tab

### Actual behavior:

No logger is produced, re-clicking it will sometimes give you the "Open the logger" tooltip.

### Your environment

* uBlock Origin version: 1.16.20
* Browser Name and version: Fennec 63.0b7
* Operating System and version: Android 8.1.0 on Google Pixel C tablet.

**Comment by gwarser** [comment]
Try latest version from GitHub Releases page - should be fixed.

**Comment by iamsix** [comment]
Ah you're correct. I see one of the fixed issues is is #168 which I didn't find on my search as I was looking for mobile in the topic. Thanks.

**Comment by uBlock-user** [comment]
Duplicate of #168
