### ISSUE TITLE
Filter List sections not collapsing

### ISSUE THREAD

**Issue by bubbajonez** [uBlockOrigin/uBlock-issues#2304]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Some filter sections (but not all, strangely!) in the Filter Lists window fail to collapse when using the +/- controls, leaving unselected filters visible in the list instead of hiding them. On these cases, the +/- controls effectively do nothing.

![ubobug](https://user-images.githubusercontent.com/114867814/193460481-0d55bce2-e4df-4e90-9d7b-7349e6596f05.jpg)

### A specific URL where the issue occurs.

moz-extension://e9157111-2241-4f67-b160-b90233fcdae2/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Just go the uB dashboard, Filter Lists section, and try to collapse and un-collapse the various filter sections.

### Expected behavior

The unselected filters should be hidden when collapsing their section.

### Actual behavior

The unselected filters are not being hidden when collapsing their section.

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Firefox: 91
filterset (summary): 
  network: 133440
  cosmetic: 95627
  scriptlet: 24799
  html: 785
listset (total-discarded, last updated): 
  removed: 
    ublock-badware: null
    easylist: null
    easyprivacy: null
    ublock-quick-fixes: null
  added: 
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-1, 22m
    https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt: 0-0, 22m
    https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4589-45, 22m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-1, 22m
    https://winhelp2002.mvps.org/hosts.txt: 8730-387, 22m
    https://www.fanboy.co.nz/r/fanboy-complete.txt: 95964-15561, 22m
    adguard-spyware: 26701-1715, 22m
    adguard-annoyance: 59746-243, 22m
    ublock-annoyances: 4866-4, 22m
    dpollock-0: 11389-1721, 10d.23h.21m
    spa-1: 4690-20, 22m
    adguard-spyware-url: 766-3, 22m
    block-lan: 44-0, 10d.23h.21m
  default: 
    user-filters: 108-0, never
    ublock-filters: 33769-460, 22m
    ublock-privacy: 273-0, 22m
    ublock-abuse: 76-0, 22m
    ublock-unbreak: 1876-1, 22m
    urlhaus-1: 9454-0, 22m
    plowe-0: 3673-1727, 10d.23h.21m
filterset (user): [array of 108 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    about-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
modifiedUserSettings: 
  autoUpdate: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 409 ms (selfie)
  maxAssetCacheWait: 241 ms
```
</details>

**Comment by gwarser** [comment]
Lists from default selection will not collapse.
