### ISSUE TITLE
Bug Report Form Issue

### ISSUE THREAD

**Issue by jwm-cadre** [uBlockOrigin/uBlock-issues#2306]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Reporting UI issues that may be interaction issue with browser is more difficult now.

Important: Please note I was required to check " The issue is not present after disabling uBO in the browser. *" for a UI issue

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=bug_report.yml

### Steps to Reproduce

Try to report a UI issue with other browser extensions and browser conditions occurring.

### Expected behavior

Expected to be able to send a UI screen shot of desktop and relevant information.

### Actual behavior

Bug Report beta form does not allow for UI interaction issues.

### uBO version

1.44.4

### Browser name and version

Firefox 105.0.1

### Operating System and version

WIN10 Version	10.0.19044 Build 19044

**Comment by gorhill** [comment]
> Try to report a UI issue with other browser extensions and browser conditions occurring

Which other browser extensions you want us to check? Time is precious and I rather have a specific step for this, asking to look at "other browser extensions" is too unspecific and we don't have the time to go on a chase to figure out exactly what you have in mind.

**Comment by krystian3w** [comment]
Maybe bug with EasyList: https://github.com/easylist/easylist/issues/13447

**Comment by gorhill** [comment]
Closing as invalid for now as it's unclear what actual issue is being reported and lack of feedback.
