### ISSUE TITLE
Escaping quotes in a cosmetic filter invalidates the rule and even breaks whole cosmetic filtering - CSSTree?

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2309]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Rules with escaped quotes like `##div[style^="z-index: 999999; background-image: url(\"data:image/gif;base64,"][style$="position: absolute;"]` is not applied on 1.44.5b10. Furthermore, just having such a filter seems to break whole cosmetic filtering.

### A specific URL where the issue occurs.

`https://nozomi.la/post/31048158.html` (the site has nsfw contents), `www.washingtonpost.com`

### Steps to Reproduce

1. Add `nozomi.la#@#+js(set, D4zz, noopFunc)`, `@@||newir3ltyug79aiman.com^`, (these brings the target element) and `##div[style^="z-index: 999999; background-image: url(\"data:image/gif;base64,"][style$="position: absolute;"]` to My filters and open the logger

2. Visit `https://nozomi.la/post/31048158.html`

3. Open the picker and check `##div[style^="z-index: 999999; background-image: url(\"data:image/gif;base64,"][style$="position: absolute;"]` can not be applied (neither on the logger), while `##div[style^="z-index: 999999; background-image: url("][style*="data:image/gif;base64,"][style$="position: absolute;"]` can be. Sometimes ad script is not loaded, in that case refresh the page many times.

4. Then visit `www.washingtonpost.com` and you'll see the whole cosmetic filtering is disabled. If you remove `##div[style^="z-index: 999999; background-image: url(\"data:image/gif;base64,"][style$="position: absolute;"]` it will be enabled again.

### Expected behavior

Escaping quotes works correctly and doing so doesn't break anything

### Actual behavior

Described

### uBO version

1.44.5b10 (doesn't happen on 1.44.4)

### Browser name and version

Firefox 105.0.1

### Operating System and version

Windows 10

**Comment by Yuki2718** [comment]
Yeah, confirmed all fixed in .11

**Comment by gorhill** [comment]
There is no need to put "CSSTree" in the title, this is just a library and if there is an issue, it's most likely the usage of the library which might need to be fixed, and in any case only investigating will tell where the issue is, there is no point to speculate in the title.

The reason I wanted to rely on an external library is to avoid to have to write a full CSS selector parser since I can no longer rely on the browser to properly validate selectors, but in the end I might have to do just that and this will bog development down for quite a while.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2284#issuecomment-1265417399
