### ISSUE TITLE
New cosmetic filter parser seems to cannot parse case-insensitive attribute selector

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uBlock-issues#2310]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [x] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The new cosmetic filter parser doesn't seem to work when given a filter in the form of `site##[attribute operator value i]`. I suspect the problem is caused by the new cosmetic filter parser because such filter form still worked when the new parser hasn't been introduced (around version 1.44.5b0 if I recall correctly). A Reddit user seemed to have also reported the issue implicitly [here](https://old.reddit.com/r/uBlockOrigin/comments/xpfipy/twitter_is_broken/iq58jg3/).

I wasn't able to report this issue earlier due to lack of testing time.

### A specific URL where the issue occurs.

https://twitter.com/gorhill

### Steps to Reproduce

1. Open https://twitter.com/gorhill. Notice the page layout.
2. Add `twitter.com##[aria-label$="trending now" i]` to `My Filters` list (filter recommendation on Reddit wiki).
3. Refresh the opened Twitter site. Notice the change (if any).
4. Repeat step 2 and 3 with filters `twitter.com##[aria-label$="Trending now" i]` and `twitter.com##[aria-label$="Trending now"]`.
5. Repeat step 2 - 4 using filters `twitter.com##[role="Banner" i]`, `twitter.com##[role="banner" i]`, and `twitter.com##[role="banner"]` respectively.

### Expected behavior

The first three filters should hide the "Trending Now" section; The other three should hide the left-hand banner.

### Actual behavior

"Trending Now" section isn't hidden with filter `twitter.com##[aria-label$="trending now" i]`; left-hand banner isn't hidden with filter `twitter.com##[role="Banner" i]`.

### uBO version

1.44.5b11 (does not happen on 1.44.4)

### Browser name and version

Firefox 105.0.1

### Operating System and version

Windows 10

**Comment by partingscientist** [comment]
Updating to uBO 1.44.5b12 seems to have fixed the issue when tested on a clean profile.

Note: For some reason, doing the same on my usual profile didn't fix the issue, even after ensuring the only active filter lists are the default ones. The aforementioned filters caught the appropriate elements when entered into the element picker (unlike previously), yet they still didn't show up in the Logger.

**Comment by krystian3w** [comment]
Works on dirty profiles:

![obraz](https://user-images.githubusercontent.com/35370833/194167878-684b28b3-6b9c-4d85-8b8b-ad3b5bd107de.png)

**Comment by gorhill** [comment]
> don't delete space

I meant to normalize with a space but lost this with few changes before commit. Exceptions should still work though since it will also be normalized to no space version.

**Comment by partingscientist** [comment]
> Can you share troubleshooting information for the site?

I'm currently away from my device for some time. Will do as soon as possible. Meanwhile, do you want me to also activate the usual filter lists that I use? Or just keep the default ones only as I did previously to test?

**Comment by gorhill** [comment]
Just keep the default ones so that it's easier for me to mimic your configuration.

**Comment by partingscientist** [comment]
Hope this helps.
```uBlock Origin: 1.44.5b12  
Firefox: 105  
filterset (summary):   
  network: 86027  
  cosmetic: 38995  
  scriptlet: 18031  
  html: 784  
listset (total-discarded, last-updated):   
  default:  
    user-filters: 31-0, never  
    ublock-filters: 33811-45, 10h.18m  
    ublock-badware: 4345-0, 10h.18m  
    ublock-privacy: 273-0, 10h.18m  
    ublock-abuse: 76-0, 10h.18m  
    ublock-unbreak: 1878-1, 10h.18m  
    easylist: 62366-644, 10h.18m  
    easyprivacy: 30689-1706, 10h.18m  
    urlhaus-1: 8947-0, 10h.18m  
    plowe-0: 3672-3, 10h.18m  
    ublock-quick-fixes: 306-0, 10h.18m  
filterset (user): [array of 30 redacted]  
hostRuleset:  
  added: [array of 72 redacted]  
modifiedUserSettings:  
  advancedUserEnabled: true  
  colorBlindFriendly: true  
  contextMenuEnabled: false  
modifiedHiddenSettings: [none]  
supportStats:  
  allReadyAfter: 183 ms (selfie)  
  maxAssetCacheWait: 83 ms  
```

**Comment by gorhill** [comment]
> I'm not sure how, but commenting all of the filters in "My Filters" list and uncommenting them fixed the issue

Ok, this is because the defective filter needed to be recompiled by uBO to be fixed, and changing something in your filters forced a recompilation.

**Comment by partingscientist** [comment]
Do you think doing such recompilation automatically whenever the extension updates would be better? I don't think forcing it manually is intuitive for everyone, myself included.

**Comment by gorhill** [comment]
This was only necessary because of a bug had been fixed, there no point otherwise while significantly affecting launch time to readiness.

**Comment by partingscientist** [comment]
It goes without saying, but thank you for helping making the internet better for everyone.
