### ISSUE TITLE
`##x:has-text({)` and `##x:has-text([)` no support backslash

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2316]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I detected one uBo Annoyances filter no longer works in uBo dev 1.44.5b12: https://github.com/uBlockOrigin/uAssets/blob/7246847cc17438dc7a2ad5c494667574f5627daf/filters/annoyances.txt#L4483

```adb
world4.eu##style:has-text(body:after{content:):remove()
```

### A specific URL where the issue occurs.

N/A - filter can by outdated

### Steps to Reproduce

1. open uBo Annoyances preview
2. found line `world4.eu##style:has-text(body:after{content:):remove()`
3. line is reddish

### Expected behavior

Support backslash instead rewrite to to regex: `/body:after\{content:/`

IMO no need improve https://github.com/gorhill/uBlock/commit/a71b71e4c8a2037fc68970bc8912a76732edaade - I mean support legacy version without edit filter file.

### Actual behavior

Filter marked as invalid and no remove "node".

### uBO version

1.44.5b12

### Browser name and version

Firefox 106b8

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Use quotes when there are characters tripping the parser:

    world4.eu##style:has-text("body:after{content:"):remove()

**Comment by krystian3w** [comment]
OK, maybe someone remember create PR with second line after stable CSSTree Parser.

**Comment by gorhill** [comment]
This works too to prevent the parser to trip:

    ##style:has-text(body\:after\{content\:):remove()

However uBO would have to remove the backslashes. Currently in 1.44.4 it does it only for parentheses `(` and `)`.

**Comment by gorhill** [comment]
> I mean support legacy version without edit filter file

It's just not possible, the parser refuses to parse when it encounters weird characters sequences sometimes found in `has-text` or `xpath` -- it's not the parser's fault, it works according to CSS parsing specs. The real issue is technical debt from how this was implemented in uBO. In the big picture, there is only a handful of filters affected, which filters could very well be obsolete, and if not the simple fix is to use quotes. Throwing more code to avoid this is just not realistic, the best move is to not keep carrying on the technical debt.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/commit/160ecd20d8cf4b9d9eb2f22c1ce9c9ed48588ba4

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8451
