### ISSUE TITLE
Password-protect changes to My Rules, etc.

### ISSUE THREAD

**Issue by simurq** [uBlockOrigin/uBlock-issues#232]
Hello. It's not an issue per se, hence the title of this post - suggestion.
There is a bunch of real good anti-porn host rules like Chad Mayfield's lists etc. In an attempt to use uBlock Origin to block porn sites (not only ads), I've imported some rules to uBlock, which effectively prevents the sites from background loading and opening. I know that uBlock is not a parental-control tool but it's really effective in comparison with other apps out there.
My major concern is that it still makes it possible for users to bypass rules by temporarily "lifting" the URL from scan.
I've tried adding the hosts to windows hosts file but this freezes my computer and often disables Internet connection. Besides, no one prohibited occasional visits to "nasty" sites, if you know what I mean...
So, can I suggest adding password protection to uBlock at least to My Rules page so that users couldn't disable strict blocking of certain hosts?

Thanks!

**Comment by gorhill** [comment]
Declined, out of uBO scope.
