### ISSUE TITLE
Element picker is light themed when uBO theme is set to auto in Firefox Nightly

### ISSUE THREAD

**Issue by bbhtt** [uBlockOrigin/uBlock-issues#2321]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

GNOME 42.4 using system dark mode (Freedesktop colour scheme preference ie. Dark is set in Gnome control center>Appearance>Style), Firefox theme set to System - Auto, uBo theme set to auto.

Open the element picker in any page, it is light themed but uBO itself is dark themed (the settings page and the extension popup).

### A specific URL where the issue occurs.

https://hg.mozilla.org/

### Steps to Reproduce

Open the element picker in any page

### Expected behavior

It should be dark themed

### Actual behavior

See that it is light themed

### uBO version

1.44.4

### Browser name and version

Firefox Nightly 107.0a1 (2022-10-11)

### Operating System and version

Archlinux

**Comment by bbhtt** [comment]
> working as expected on 107.0a1 (2022-10-13) (64-bit), nightly issue, uBO issue was fixed in last commit.

Not for me, on 2022-10-15: 

![image](https://user-images.githubusercontent.com/62639087/196018984-8867ca4e-7e28-4b96-ab10-07c0e4358875.png)

**Comment by gwarser** [comment]
You are using 1.44.4 and this was fixed in dev.

**Comment by bbhtt** [comment]
> My Firefox theme is not custom and is set to "Dark", if I set to "Auto", I still get the same results.

That's not a custom theme, it's the default system theme. The issue only happens in that case, if FF is dark or uBO is dark it works as expected. This was the same with the previous issue See:

> GNOME 42.4 using system dark mode (Freedesktop colour scheme preference ie. Dark is set in Gnome control center>Appearance>Style), *Firefox theme set to System* - Auto, *uBo theme set to auto*.

**Comment by bbhtt** [comment]
> You are using 1.44.4 and this was fixed in dev.

Ah yes. I thought the fix was in 1.44.4 because it was released after the original issue is closed. Indeed it if fixed with 1.44.5b12.

Thanks!
