### ISSUE TITLE
Cosmetic filter got case-insensitive

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2322]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The site has only `#adbanner`, but the picker allows creating e.g. `###adbanneR` and it's actually applied:

![adbanneR](https://user-images.githubusercontent.com/58900598/195655359-21727962-d526-41a5-9d7d-0ef6220ceeca.png)

### A specific URL where the issue occurs.

http://www.quotationspage.com/

### Steps to Reproduce

1. Visit the site and create `###adbanneR` or even `###aDBanNeR`.

### Expected behavior

Cosmetic filters should be case sensitive.

### Actual behavior

Not

### uBO version

1.44.4

### Browser name and version

Google Chrome 106.0.5249.119

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
This is not a uBO issue -- if the page is not rendered in HTML5 mode (which is the case for this webpage), then [CSS selectors are case insensitive](https://w3c.github.io/csswg-drafts/selectors-4/#id-selectors):

> When matching against a document which is in [quirks mode](https://dom.spec.whatwg.org/#concept-document-quirks), IDs must be matched [ASCII case-insensitively](https://infra.spec.whatwg.org/#ascii-case-insensitive); ID selectors are otherwise case-sensitive, only matching IDs they are [identical to](https://infra.spec.whatwg.org/#string-is).

**Comment by krystian3w** [comment]
Only way be use on list:

```adb
##div[id="adbanner"]
```
