### ISSUE TITLE
Filter-lists updating

### ISSUE THREAD

**Issue by PedEchsing** [uBlockOrigin/uBlock-issues#2323]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Firefox
My filters are 115 days out-of-date.
Clicking on Update Now does nothing.
Triangle-click just says Network Error.
UBO working fine in G-Chrome.

Mac High Sierra. Latest Firefox. Latest UBO (autoupdate).

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

nothing to do except click
Update Now

### Expected behavior

Expected UBO to update filters

### Actual behavior

Network Error

### Configuration

Mac High Sierra. Latest Firefox. Latest UBO (autoupdate 1.44.4).

**Comment by gwarser** [comment]
Did you remove (commented by `#`) the default lines in "Trusted sites"? Can you share troubleshooting information (on the bottom of the uBO dashboard, Support tab)?

**Comment by PedEchsing** [comment]
I did not change anything on trusted sites. Left it in default.

/Trouble Shooting Information/
(cut-copy-paste) (too much newbie to know any other way to do this)

uBlock Origin: 1.44.4
Firefox: 105
filterset (summary): 
  network: 93165
  cosmetic: 154247
  scriptlet: 21399
  html: 688
listset (total-discarded, last updated): 
  added: 
    https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt: 2625-1, 116d.3h.1m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 114d.20h.49m
    adguard-annoyance: 54317-627, 114d.20h.51m
    fanboy-thirdparty_social: 0-0, never
    fanboy-annoyance: 73535-3114, 119d.18h.52m
  default: 
    user-filters: 4-1, never
    ublock-filters: 32474-57, 116d.2h.59m
    ublock-badware: 4215-3, 114d.20h.55m
    ublock-privacy: 230-0, 114d.20h.56m
    ublock-abuse: 75-0, 114d.2h.16m
    ublock-unbreak: 1823-4, 114d.20h.54m
    easylist: 68820-594, 114d.20h.53m
    easyprivacy: 27251-586, 114d.20h.52m
    plowe-0: 3647-3, 116d.3h.2m
    urlhaus-1: 5435-0, 114d.20h.50m
    ublock-quick-fixes: 205-0, 114d.20h.48m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 48 redacted]
  removed: 
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 1257 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3444 ms (selfie)
  maxAssetCacheWait: 876 ms

**Comment by gorhill** [comment]
> I did not change anything on trusted sites

You did:

```
trustedset:
  added: [array of 48 redacted]
  removed:
    about-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
```

Put back `about-scheme`, `edge-scheme`, `moz-extension-scheme`, `wyciwyg-scheme` by uncommenting those entries.

**Comment by PedEchsing** [comment]
THANKS!! Mr Gorhill.
Must argue... did not go into trusted and change.
MIGHT have clicked something in GUI to change.

WILL make recommended changes!

By default, installed addon. Clicked Advanced User to have little more control over
adds on most-visit sites (Prefer not Advance User, breaks my sites).
Have only used color-boxes to allow/deny various annoyances.
When doing detail allow/deny, try to only use  Tampermonkey.
Too much newbie/stupid to add/edit/change settings NOT in GUI.
Which is why 115 days out-of-date.
(If I can't click-change color-box, then I can't change it.)

**Comment by krystian3w** [comment]
Enough is click on power button if add-on page are opened then Firefox scheme are commented and break update requests.
