### ISSUE TITLE
Change dynamic rule permanently in logger is not always possible.

### ISSUE THREAD

**Issue by ericzwo** [uBlockOrigin/uBlock-issues#2330]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'm using uBO in advanced mode.
When changing an existing rule in the logger (URL Rule Tab of log entry) from i.e. block to allow, the rule can't be committed permanently. This happens because the lock icon is not shown.
As a workaround one can
 * remove the block rule. 
 * commit permanently with the lock icon. 
 * add the allow rule. 
 * commit permanently with the lock icon

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin

### Steps to Reproduce

1. Add the following dynamic rules:
```
* * 3p block
* * 3p-frame block
github.com https://github.githubassets.com script noop
```
2. Open the logger and open details of a log entry, which is affected by the 3rd rule.
3. Go to "URL rule" Tab and switch from noop to allow

### Expected behavior

The lock icon is displayed and allows to commit the rule permanently.

### Actual behavior

The lock icon is not displayed and the rule can't be committed permanently. The change is showed in "My Rules" Tab in Settings and can be committed.

### uBO version

1.44.4

### Browser name and version

Mozilla Firefox 105.0.3

### Operating System and version

Linux wayland sway

**Comment by gwarser** [comment]
Not fixed. Button is displayed, but clicking does nothing.
