### ISSUE TITLE
Can't import settings on Chromium based portable browsers

### ISSUE THREAD

**Issue by nollinvoyd** [uBlockOrigin/uBlock-issues#2331]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Rather than going thru a lengthy explanation, please see this detailed Reddit thread where I first reported the problem.

Restore from file fails => 
https://www.reddit.com/r/uBlockOrigin/comments/y1idax/restore_from_file_fails/

Normally, when you "restore from file", this notification appears

![ublock](https://user-images.githubusercontent.com/20844322/196820394-c996a26f-a6a3-42bb-8b0a-00d09b717ee0.png)

However, when I try to "restore", nothing happens.  No import, no response of any kind  from Ublock.

As you will read, I've tried everything, we could think of without success.

I'll be glad to answer any questions.

Note;  in order to post this thread, I had to use the url of the thread I referred to earlier.

Thanks

### A specific URL where the issue occurs.

https://www.reddit.com/r/uBlockOrigin/comments/y1idax/restore_from_file_fails/

### Steps to Reproduce

Attempt to restore from file

Restore from file fails

### Expected behavior

"Restore From File" is successful

### Actual behavior

Settinga fail to import

### uBO version

1.44.4

### Browser name and version

Firefox 106

### Operating System and version

Microsoft Windows 10 Professional (x64) Build 19044.2130 (21H2)

**Comment by gorhill** [comment]
I don't have Windows, so somebody else will have to investigate whether there is really an issue with uBO, and if so where in uBO it's failing.

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/y1idax/restore_from_file_fails/

**Comment by Rudxain** [comment]
In my case it's Fenix (Firefox for Android) v119.1

uBO 1.53.0

**Comment by gorhill** [comment]
Stale issue, closing.
