### ISSUE TITLE
Added Filter always Deleted

### ISSUE THREAD

**Issue by ChowMein47** [uBlockOrigin/uBlock-issues#2335]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

After i closed browser, the filter i added (AdblockID) Always Deleted, and i have to update it everytime

### A specific URL where the issue occurs.

moz-extension://005c17ab-a69a-49d7-abbf-22339cac90df/dashboard.html#3p-filters.html

### Steps to Reproduce

1. I opened my browser
2. I closed the browser
3. When i opened it again the filter already deleted

### Expected behavior

The filter shouldn't be gone after i closed the browser 

### Actual behavior

![Screenshot_2022-10-21-12-15-53-91_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/98148960/197124043-e24add64-3970-4b58-81f6-227d724a2119.jpg)

### Configuration

Firefox mobile 106
Ublock Origin 1.44.4

**Comment by gwarser** [comment]
What is the link of this list? Your screenshot shows there are no filters in this list.

**Comment by YellowStar11** [comment]
> What is the link of this list? Your screenshot shows there are no filters in this list.
> 
> Works fine when subscribed from https://filterlists.com/lists/adblockid

Yes it works when i subscribe it. But when i closed my browser the filter disappear and need to update again

**Comment by gwarser** [comment]
Is your browser managed by organisation?

**Comment by YellowStar11** [comment]
> Is your browser managed by organisation?

I think no. I downloaded original Firefox from Play Store

**Comment by gorhill** [comment]
Add troubleshooting information to your report please: Dashboard => Support => Select All, then paste here and wrap with triple-backticks.

**Comment by YellowStar11** [comment]
> Add troubleshooting information to your report please: Dashboard => Support => Select All, then paste here and wrap with triple-backticks.

uBlock Origin: 1.44.4
Firefox Mobile: 106
filterset (summary): 
  network: 97778
  cosmetic: 97818
  scriptlet: 25203
  html: 812
listset (total-discarded, last updated): 
  removed: 
    IDN-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 8155-1988, never
    adguard-spyware-url: 792-4, 19h.31m
    adguard-annoyance: 59976-3165, 19h.30m
    adguard-social: 18554-1136, 19h.30m
    ublock-annoyances: 4898-7, 19h.30m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33994-330, 19h.31m
    ublock-badware: 4397-0, 19h.31m
    ublock-privacy: 282-1, 19h.31m
    ublock-abuse: 76-0, 19h.31m
    ublock-unbreak: 1894-0, 19h.31m
    ublock-quick-fixes: 422-0, 19h.31m
    adguard-mobile: 8156-168, 19h.31m
    easylist: 62008-17942, 19h.31m
    easyprivacy: 30781-1719, 19h.31m
    urlhaus-1: 10176-0, 19h.31m
    plowe-0: 3675-3, 19h.30m
filterset (user): [empty]
modifiedUserSettings: 
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2002 ms
  maxAssetCacheWait: 710 ms

**Comment by gorhill** [comment]
AdblockId is in there, properly loaded.

**Comment by YellowStar11** [comment]
> AdBlockID is in there, properly loaded.

Every single time i closed my browser and i opened my browser again the filters i subscribed like AdblockID asks me to update it
![IMG_20221022_101934](https://user-images.githubusercontent.com/98148960/197316952-789db85a-6058-441c-98e9-0716f1138bb0.jpg)

**Comment by gorhill** [comment]
Maybe the browser is not opened long enough for the update cycle to complete?

**Comment by Yuki2718** [comment]
Not always but I have experienced deletion of all custom lists a few times, and more chances of all of them unselected. These are one-time event and happens very occasionally so no idea about the cause.

**Comment by gorhill** [comment]
So possibly related to <https://github.com/uBlockOrigin/uBlock-issues/issues/2136>.

**Comment by Yuki2718** [comment]
> Every single time i closed my browser and i opened my browser again the filters i subscribed like AdblockID asks me to update it.This problem does not occur for Default filters

Here are repro steps of the opposite (wonder if worth a new issue):
1. Set you Firefox "Open previous windows and tabs", subscribe any custom list(s), enable any of Annoyances and regional lists, open Filter lists tab and choose the tab so that the initial launch tab will be Filter lists.

2-A. Update all the lists. Close and relaunch browser.
2-B. Purge cache to make all lists are out-of-date. Close and relaunch browser.

3-A. You'll see default lists are outdated. This doesn't happen on Choromium (you may need to refresh the page for the page to be visible).
3-B. Custom lists are automatically updated soon after relaunch (it takes a second for custom lists being shown). On Firefox lists under Annoyances and Regions, languages will be auto-updated too while on Chrome only custom lists are auto-updated. 

All this happen only if the initial tab is Filter lists.

**Comment by Yuki2718** [comment]
I'm starting to guess the list deletion has something to do with launch page being Filter lists (but not with 100% reproducibility). @gorhill @gwarser Can you test setting launch page Filter lists for a while?

**Comment by gorhill** [comment]
Session restore with an extension page as the active tab is know to be an issue, there is a good risk of the page being loaded before uBO's background process is ready, which will cause the page to be in an undefined state. But none of this is ever mentioned in the repro steps, so I am assuming it's not the case.

**Comment by YellowStar11** [comment]
Still facing facing the issue on Firefox mobile 107 & uBO latest version :(
![Screenshot_2022-11-20-17-04-41-63_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/98148960/202896213-2cbf34fb-718c-46b0-b226-48d1565a6249.jpg)

**Comment by gorhill** [comment]
Issue is stale, closing.
