### ISSUE TITLE
Fix invalid copyright symbol

### ISSUE THREAD

**Issue by Matr1x-101** [uBlockOrigin/uBlock-issues#2336]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

You'll understand what I mean if you see https://github.com/Matr1x-101/uBlock/commit/93b9f0593b1659f725ca4d79072441f768efe53d. 

There should be an actual copyright symbol (©), instead of the generic letter "c"

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#about.html

### Steps to Reproduce

1. Open uBlock settings
2. Click "About" at the top
3. The copyright symbol is a generic letter "c", not the standard "©"

### Expected behavior

Text should say "Copyright (©) Raymond Hill 2014-present"

### Actual behavior

Text says "Copyright (c) Raymond Hill 2014-present"

### uBO version

1.44.4

### Browser name and version

Vivaldi snapshot (5.6.2829.3 (Official Build) snapshot (64-bit))

### Operating System and version

Arch Linux (rolling release)

**Comment by gorhill** [comment]
[Copyright symbol / Typing the character](https://en.wikipedia.org/wiki/Copyright_symbol#Typing_the_character):

> it has long been common to approximate this symbol with the characters (c) (c in parentheses), a practice that has been accepted by the [U.S. Copyright Office](https://en.wikipedia.org/wiki/U.S._Copyright_Office)

**Comment by krystian3w** [comment]
Also if we convert then nice omit brackets.
