### ISSUE TITLE
Enhancement for corporate govanance/protection.

### ISSUE THREAD

**Issue by Hardcore-fs** [uBlockOrigin/uBlock-issues#2337]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Have a system where if a specific link is triggered, you can submit the link to an external engine for further processing.(allow/block)  or redirect the users browser to a site with the link as a parameter.

For example if they trigger a site "bob.com?peram=xxxx"
be able to send the details  to another site "gateway.jake.com?site=bob.com?peram=xxxx"
possibly with a return code to allow or block or re-direct.

Specifically to allow internal monitoring systems to be triggered, by a users browsing or "content" links.
there may be cases where users receive email attachments with links to malware sites not discovered or tagged yet.

### A specific URL where the issue occurs.

none

### Steps to Reproduce

none

### Expected behavior

none

### Actual behavior

none

### uBO version

none

### Browser name and version

none

### Operating System and version

none

**Comment by krystian3w** [comment]
You can try made own filter list with strict block mechanism based of `$doc` and use policies in own Company/Corporation computers (IMO policies can't work on Android).
