### ISSUE TITLE
Slow loading speen on Firefox

### ISSUE THREAD

**Issue by fbaguem2021** [uBlockOrigin/uBlock-issues#2338]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

¨The problem is that when I have activated uBO, firefox gets very slow when loading any web page, but after turning it off, the speed turns back to normal, and stops being slow

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Turn on uBO
2. Load ani web page

### Expected behavior

Fast web loading speed

### Actual behavior

Slow web loading speed

### Configuration

[ublock-mi-respaldo_2022-10-25_10.19.15.txt](https://github.com/uBlockOrigin/uBlock-issues/files/9858454/ublock-mi-respaldo_2022-10-25_10.19.15.txt)

**Comment by gwarser** [comment]
>Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/) + fully substantiated analysis supporting the claim.

At least record performance profiles with uBO on and off.
