### ISSUE TITLE
Element picker is affected by the page zoom level

### ISSUE THREAD

**Issue by BrunaPitanga** [uBlockOrigin/uBlock-issues#2339]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Zooming out while editing an element picker rule is useful to see the effects of your filter on the whole page. This is also useful to take screenshots and report issues to filter list maintainers.

Currently, the dialog box is affected by the zoom level too, which makes your filter unreadable, so you have to keep zooming in and out to edit your rules and see the effects of each change.

It's possible to prevent this with `window.devicePixelRatio` or `resolution` in `@media`.

<img src="https://user-images.githubusercontent.com/115604365/197889371-f95d4742-283f-4a02-a3b8-7d24a9f8a903.png" width="300"/>

### A specific URL where the issue occurs.

https://ru.wikipedia.org/

### Steps to Reproduce

1. Open the element picker
2. Select an element
3. Zoom out

### Expected behavior

The dialog box shouldn't be affected by the zoom level.

### Actual behavior

The filter becomes unreadable.

### uBO version

1.44.4

### Browser name and version

Firefox 106

### Operating System and version

Windows 10

**Comment by Yuki2718** [comment]
But if user zoom in too make letters bigger, the dialog box should also be zoomed in. So maybe the best is add an option to sync or not the zoom level.

**Comment by gorhill** [comment]
> It's possible to prevent this with `window.devicePixelRatio` or resolution in `@media`.

Firefox does not support CSS `zoom` property, so much easier said than done.

**Comment by krystian3w** [comment]
IMO `zoom: calc(x / y)` also break move picker inside iframe - maybe author tested smaller fonts only.

**Comment by gorhill** [comment]
Decision: wont fix.

Just zoom in back to 100% once you are satisfied with the result. I don t see an easy solution for this, if any -- speculative fixes in the comment do not count. Whoeever is free to come up with actual code if they really want this to be fixed.
