### ISSUE TITLE
Pages doesn't load on Chromium 107.0.5304.68

### ISSUE THREAD

**Issue by Danct12** [uBlockOrigin/uBlock-issues#2341]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

After upgrading Chromium from 106.0.5249.119 to 107.0.5304.68, Chromium no longer loads any page (where uBlock is able to interact with) and instead stuck at loading forever.

Downgrading back to 106.0.5249.119 makes uBlock and websites works again.

### A specific URL where the issue occurs.

https://example.com

### Steps to Reproduce

1. Upgrade your browser to 107.0.5304.68
2. Install uBlock Origin
3. Pages no longer loads

### Expected behavior

Page should be completely loaded.

### Actual behavior

Stuck with a loading throbber, nothing is being delivered to the user.

### Configuration

The config should be default.

This is the troubleshooting information on 106.

```
uBlock Origin: 1.44.4
Chromium: 106
filterset (summary): 
  network: 88752
  cosmetic: 39516
  scriptlet: 17814
  html: 0
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2027-0, 9m
  default: 
    user-filters: 0-0, never
    easylist: 62370-72, 9m
    easyprivacy: 30818-1175, 9m
    plowe-0: 3671-865, 9m
    ublock-abuse: 76-0, 9m
    ublock-badware: 4352-110, 9m
    ublock-filters: 32277-140, 9m
    ublock-privacy: 260-1, 9m
    ublock-quick-fixes: 419-21, 9m
    ublock-unbreak: 1872-42, 9m
    urlhaus-1: 10523-0, 9m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 426 ms (selfie)
  maxAssetCacheWait: 326 ms
```

**Comment by gorhill** [comment]
> Downgrading back to 106.0.5249.119 makes uBlock and websites works again

Did you disable uBO from `chrome://extensions/` to verify that it's really uBO causing the issue and not another extension?

**Comment by Danct12** [comment]
Yes, I have tried that before filing this bug report.

**Comment by gorhill** [comment]
It's not explicitly stated in the report but beside pages not loading, were you able to access uBO's popup panel and/or dashboard?

**Comment by Danct12** [comment]
Nope, not at all.

But I can access it if I reload the plugin and go to the settings through right clicking on the extension icon.

**Comment by Danct12** [comment]
> Being on Linux I won't be able to test this until my distro push an update to 107.

Are you on Debian by any chance? Debian [sid](https://packages.debian.org/sid/chromium) and [Arch Linux](https://archlinux.org/packages/extra/x86_64/chromium/) already had 107 in their repo.

**Comment by gwarser** [comment]
No issue on Manjaro KDE, no issue on Win10 in VM.

**Comment by Danct12** [comment]
That's weird, I just upgraded to 107 again and now it seemed to have worked again (I wasn't able to load any website since midnight)

No idea what happened, sorry for the noise.

**Comment by ptrkc** [comment]
Same just happened to me on Fedora 36, Chrome 107.0.5304.87.

I use FF and only open Chrome occasionally to test front-ends. Opened Chrome today, pages were not loading and high CPU activity. Disabled uBO and pages loaded. After reinstalling uBO, everything normal.

**Comment by gwarser** [comment]
Do you have "Suspend network activity until all filter lists are loaded" option enabled?

**Comment by ptrkc** [comment]
No, after new installs I only activate the "AdGuard Spanish/Portuguese" list, but other than that, all defaults.

**Comment by gwarser** [comment]
> edit: I assumed it was off because, after the reinstall, it is off, but I see [from the docs](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded) the default should be on, so maybe it was on and I cant guarantee, sorry.

It should be disabled on Chrome, becuse of issues like this (default value was changed few times). I need to fix the doc.

**Comment by Danct12** [comment]
This issue is now happening again, I was able to produce it in every new Chromium instances. If you have any direction for me then feel free.

```
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 91300
  cosmetic: 39625
  scriptlet: 16756
  html: 0
listset (total-discarded, last updated): 
  added: 
    VIE-1: 1946-0, 16m
  default: 
    user-filters: 0-0, never
    easylist: 64364-71, 2d.11h.5m
    easyprivacy: 30830-1175, 2d.11h.4m
    plowe-0: 3668-867, 8d.11h.30m
    ublock-abuse: 76-0, 1h.56m
    ublock-badware: 4003-109, 1d.1h.54m
    ublock-filters: 31258-115, 1d.1h.47m
    ublock-privacy: 258-1, 1h.55m
    ublock-quick-fixes: 452-21, 15m
    ublock-unbreak: 1895-42, 12h.59m
    urlhaus-1: 11492-0, 14m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 126 ms (selfie)
  maxAssetCacheWait: 81 ms
```

**Comment by Danct12** [comment]
Strangely, the issue fixed itself.. I have no idea what was happening. Sorry for the noise, again.
