### ISSUE TITLE
Add GitLab to approved external websites

### ISSUE THREAD

**Issue by lunalucadou** [uBlockOrigin/uBlock-issues#2342]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

For filter lists hosted on GitLab, it would be nice if they could be easily added, but since `gitlab.com` and `*.gitlab.io` (domain for GitLab pages) are not approved external websites, you have to copy and paste URLs into the import box manually.

### A specific URL where the issue occurs.

https://lucadou.gitlab.io/compact-youtube/lists/2df48896ca6551b7746891e97c01948a.txt

### Steps to Reproduce

1. Attempt to auto-add filter list
2. DNS fails
3. Have to add it manually

### Expected behavior

Filter should be auto-added. Since GitHub Pages host is allowed to auto-add, GitLab Pages should as well.

### Actual behavior

It cannot be auto-added.

### uBO version

1.44.4

### Browser name and version

Google Chrome Version 107.0.5304.68 (Official Build) (64-bit)

### Operating System and version

Ubuntu Linux 22.04

**Comment by krystian3w** [comment]
But your generator have invalid link (compatible only with manually paste into dashboard or "geek" into backup file).

"Recommended" are 1 of 3 in href attribute:

`abp:subscribe?location=encoded-url&title=optional-encoded-title`

`ubo:subscribe?location=encoded-url&title=optional-encoded-title`

`https://subscribe.adblockplus.org/? location=encoded-url&title=optional-encoded-title`

Then as fallback works on any page "right" click on link, select form list uBlock Origin and form second drop-down menu "subscribe" - uBo 1.36.0+.

**Comment by gorhill** [comment]
Use right-click on the link to access the _"Subscribe to filter list"_ entry. This is the preferred way to do this, rather than keep adding entries in the manifest.

**Comment by gorhill** [comment]
The right click on the link is the proper solution. For an example of how this work, right-click on the following link:

https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Fgorhill%2FuBlock%2Fmaster%2Fdocs%2Ftests%2Fstatic-filtering-parser-checklist.txt

There will be an item in the contextual menu to _"Subscribe to list..."_, this will work regardless of the site on which the link is hosted, it's just a matter of url-encoding the link as a value of the query parameter `location`.

**Comment by lunalucadou** [comment]
@krystian3w I was hoping to have a link to `https://subscribe.adblockplus.org/?location=https://lucadou.gitlab.io/compact-youtube/lists/2df48896ca6551b7746891e97c01948a.txt&title=CompactYouTube` that the user could click to add, rather than having to right click.

Considering `*.github.io` is on the [approved external websites list](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#adding-via-approved-external-websites), I don't see why GitLab shouldn't be, either.

@gorhill 

> This is the preferred way to do this, rather than keep adding entries in the manifest.

I feel like adding the second-largest git hosting service on the internet isn't that big an ask. If it's a matter of it being low priority for the team, I'm willing to create a PR for it so you don't have to do any extra work.

**Comment by gorhill** [comment]
Ideally I would want this special list to not exist at all and have the right-click method the official way to subscribe to a list. If I keep adding sites to that list, this keep making that goal more and more difficult to attain. The right-click approach is also the best programmatically, it does not require a content script to be injected in pages -- I wish I had thought of doing it this way since the beginning.

**Comment by lunalucadou** [comment]
Ok, that makes sense. Perhaps you should put a deprecation notice on the wiki page so nobody else comes along requesting more additions to the whitelist.
