### ISSUE TITLE
[Feature Request] Allows users to unblock elements via context menu

### ISSUE THREAD

**Issue by yuis-ice** [uBlockOrigin/uBlock-issues#2348]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In the context menu (right clicking on a webpage) you see "Block element" item from uBlock. I believe it'd be quite useful for many users if you could "Unblock element" or something on a webpage on the fly. I know you can simply turn off blocking on the extension popup interface, or through editing the "my filters" txt, but it requires reloading the page and it takes much more time. So an on the fly way to not only "block" but "unblock" element(s) would be cool I believe. Thanks.

### A specific URL where the issue occurs.

none

### Steps to Reproduce

none

### Expected behavior

none

### Actual behavior

none

### uBO version

the latest on the webstore

### Browser name and version

Version 107.0.5304.88 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 2009

**Comment by gwarser** [comment]
How this can be usefull? You cannot right click on blocked element, because it's hidden. Maybe configure keyboard shortcut for the logger, and you also have DOM inspector here which is more or less point-and-click.

**Comment by gorhill** [comment]
For cosmetic filtering, there is the [no-cosmetic-filtering switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering), which does not require to reload the page. For network filtering, the resources are not downloaded, and they are not just "element(s)", i.e. JS resources have no visible counterparts, are not downloaded, are not executed, and executing JS may cause more resources to be downloaded which would be blocked, and so on, so this sort of feature request makes no sense in that case.

**Comment by gitressa** [comment]
I agree with @yuis-ice that being able to right-click on an image element, and allow it to load by adding local rules for the relevant domains would be a great feature. Maybe something like this?

1. Go to a URL like https://www.decathlon.nl/p/fietsponcho-zichtbaar-s-nachts-560-zwart-fluogeel/_/R-p-343167
1. Right click on the alt image element ("Fietsponcho zichtbaar 's nachts 560 zwart/fluogeel")
1. Select "Allow this element for current site" **<<< Add this option**
1. These two site should then get enabled as local rules, and the image allowed to be loaded for the current site:
    ```
    mediadecathlon.com
      contents.mediadecathlon.com
    
    d.akamai.net
      a1813.d.akamai.net
      contents.mediadecathlon.com
    ```

Even if there is no alt text (`alt="Fietsponcho zichtbaar 's nachts 560 zwart/fluogeel"`), you can usually make an educated guess where an element such as an image should be shown, and thereby the source, and right-click there.
