### ISSUE TITLE
Abort event listener / current inline script

### ISSUE THREAD

**Issue by scripthunter7** [uBlockOrigin/uBlock-issues#2350]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`addEventListener` logging and aborting do not work in all cases. For example, [port.hu](https://port.hu/tv) "masks" event listener this way:

```js
const addEListener = window.addEventListener;

// ...

// IIFE:
(function () {
    addEListener(...)
)();
```

and uBO's `port.hu##+js(aell)` doesn't list this event listener, while ADG's `port.hu#%#//scriptlet('log-addEventListener')` works well.

**Aborting the inline script** also doesn't work: `port.hu##+js(acis, window.ado, ADBnrArea)`

On the demo page below, one time `aell` works, another time it doesn't. I think it's because of the loading times (I tried in Opera and Chrome):

<details>

<summary>Show demo page HTML code</summary>

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>uBO test page</title>
</head>
<body>
    uBO test page

    <script>
        window.addEventListener("DOMContentLoaded", function () {
            console.log("DOMContentLoaded ok");
        })

        window.addEventListener("load", function () {
            console.log("load ok");
        })
    </script>
</body>
</html>
```

</details>

ADG browser extension works fine and logs them in all cases.

Maybe both are due to the load times, to be honest, I didn't look deeper into it.

Related: https://github.com/hufilter/hufilter/issues/15

### A specific URL where the issue occurs.

Not relevant

### Steps to Reproduce

See description

### Expected behavior

-

### Actual behavior

See description

### uBO version

latest

### Browser name and version

latest Opera, latest Google Chrome

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
I looked at AdGuard, and I found that it also tries to inject scriptlets at `webRequest.onResponseStarted()`. When I do the same thing in uBO, this seems to fix the issue. The issue is still present in Firefox however when reloading the page, but then this is also true for AdGuard.

**Comment by scripthunter7** [comment]
> but then this is also true for AdGuard

@slavaleleka fyi.

**Comment by gorhill** [comment]
Not the same thing, Chromium-based browser do not support response body filtering, which is what #21 was about. [`onResponseStarted`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onResponseStarted) is just an (non blocking) event.
