### ISSUE TITLE
Fails to install on clean Firefox Quantum 62.0

### ISSUE THREAD

**Issue by casper** [uBlockOrigin/uBlock-issues#236]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A completely brand new installation of FF 62.0 on Ubuntu 18.04. Neither the manual installation method (with `xpinstall.signatures.required` as `false`) nor through the Add-Ons store works. I get the security popup, I click confirm/add, and then nothing. No icon, and nothing in about:addons.

Is 62.0 not supported, or am I missing some trick for proper installation?

### Steps to Reproduce

1. Install Ubuntu 18.04
2. sudo apt install firefox
3. Try to install uBlock Origin

### Expected behavior:

uBlock Origin is installed.

### Actual behavior:

Nothing happened.

### Your environment

* uBlock Origin version: latest from the FF store or stable 1.16.20 xpi from Github
* Browser Name and version: Firefox Quantum 62.0
* Operating System and version: Ubuntu 18.04

**Comment by gorhill** [comment]
You will have to investigate more on your side please -- I never had any issue installing uBO.

**Comment by casper** [comment]
Here's an update: I cannot install ANY addons. Seems possible related to this bug:   
https://bugzilla.mozilla.org/show_bug.cgi?id=1474255

I cannot find anyone else reporting this and they say it's resolved in a 62.0 beta release. 
Apparently not.

You may close this. I'm installing Chrome instead.
