### ISSUE TITLE
Element picker generate no match suggestion of filter to dom tree

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2360]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Element picker suggest no working filter (e.g. omit `<a>` from dom tree) on cosmetic list, also by sliders.

### A specific URL where the issue occurs.

`https://pl.wikipedia.org/wiki/Plik:Flag_of_Poland_(normative).svg`

(this is HTML5 not real SVG direct url)

### Steps to Reproduce

1. open page
2. try block Polish flag
3. form suggested list click on someting very similar to "`##[src="//upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Flag_of_Poland_%28normative%29.svg/800px-Flag_of_Poland_%28normative%29.svg.png"]`"
4. filter no works due have invalid relations:

   ```adb
   ! invalid
   ###file > [src]
   !
   ! correct should be:
   ###file > a > [src]
   ! or
   ###file [src]
   ```

### Expected behavior

Generated filter compatible to save by "Create"

### Actual behavior

Generated filter incompatible to save by "Create"

<details> <summary> screenshot </summary>

![obraz](https://user-images.githubusercontent.com/35370833/201530231-2a290e2b-4803-4e78-b0b5-0ce8781ad97d.png) |
--- |

</details>

### uBO version

1.45.3b0

### Browser name and version

Firefox 107b9

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
Regression from <https://github.com/gorhill/uBlock/commit/feaa338678ab64e334d33d5b5fb06749877454e7#diff-1d458db50255dc41294f582831b2dd40eb14ac9e636ba1a8e94b7163982a1e18>.

There were so many changes in that commit that I accidentally committed at the same time changes which were not meant to be part of that commit.
