### ISSUE TITLE
(js-based) hyperlink auditing pollutes the overview panel

### ISSUE THREAD

**Issue by Shamar** [uBlockOrigin/uBlock-issues#2363]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Left-mouse click on a "link" among the results of a search engine monitoring the user (tested on Google and DuckDuckGo) might trigger several requests that the uBO's overview panel shows as originating by the target website while infact originated by the search engine.

It has been reported as an issue to the website of an Italian anti-surveillance project: https://monitora-pa.it

If you search Monitora PA [for example in DDG](https://duckduckgo.com/?q=monitora+pa&t=h_&ia=web) and you left click the first link, you'll visit our website and uBO will show requests sent to improving.duckduckgo.com. 

![image](https://user-images.githubusercontent.com/299880/201777294-0bd01349-4db0-4623-b270-a0d5e501e42d.png)
![image](https://user-images.githubusercontent.com/299880/201777567-04f1bfbb-e741-4434-abd6-8b7d2865eb9b.png)

NOTE: I'm not entirely sure this can be fixed. I cannot image a way to distinguish the hyperlink surveillance from the proper destination as both requests begin roughly at the same time.

Yet this looked as something to report, even just because such weird behavior might confuse users and could be properly documented somewhere.

### A specific URL where the issue occurs.

https://duckduckgo.com/?q=monitora+pa&t=h_&ia=web

### Steps to Reproduce

1. Open DuckDuckGo
2. Search a professional website (aka one that doesn't send third party requests ;-)
3. Click on the link
4. Look at the overview panel in uBO

### Expected behavior

uBO should only list hosts connected from the current page. 

### Actual behavior

uBO lists hosts connected from the previous page.

### uBO version

1.45.0

### Browser name and version

Firefox 106.0.5 and LibreWolf 106.0.5-1

### Operating System and version

Windows 10 (but reproduced on Firefox/Android too)

**Comment by gorhill** [comment]
The webRequest listener receives the ping request after the browser navigated to the new webpage.

![Screenshot from 2022-11-15 14-39-28](https://user-images.githubusercontent.com/585534/202010785-1ca6e872-1c4b-4d4a-8e49-7a1bdc9ba02b.png)

There is no trivial fix for this, and I rather not make the code used to attribute hostnames to a given scope even more complicated than it is.
