### ISSUE TITLE
Display numbers are not correct in popup menu (NL)

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#2364]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I am using Firefox version 107.0 

In the settings of FF I set the language of my browser to *Dutch*.
Also I downloaded the Dutch version of uBlock. 

As you can see in the screenshot below, the text of the popup is in Dutch.   
**However**, the number counting (blocked since installation) does not follow the Dutch system, but the English/American.  
This should not be the case. 

<details> <summary> Screenshots </summary> 

![afbeelding](https://user-images.githubusercontent.com/81161435/202100117-446c14a8-391b-4729-9468-6c130f827bd6.png)

![afbeelding](https://user-images.githubusercontent.com/81161435/202100162-4ad47db1-66f7-4017-a0cd-466b7bd16a1e.png)

![afbeelding](https://user-images.githubusercontent.com/81161435/202109929-310ee8c2-02be-4969-81a2-9122551880c6.png)

</details>

### A specific URL where the issue occurs.

popup menu

### Steps to Reproduce

1. Install Firefox and set the language in `about:preferences` to Dutch -- remove alternatives if there are any. 
2. Click on *`Choosing your preferred languages to display web pages`* and  
check the box *Request English-language versions of web pages for enhanced privacy / Engelstalige versies van webpagina’s opvragen voor verbeterde privacy*.
3. Go to `https://addons.mozilla.org/nl/firefox/addon/ublock-origin/`  (the Dutch version of FF Add-ons)  
and download uBlock. 
4. Make sure you have more than a million blocked applications. For example, 1,234,000 (1.234 million). 
5. You will notice that uBlock displays this number as **1.234M** instead of **1,234 milj.**

### Expected behavior

I expect the counting and display of numbers in the popup follows the language of the downloaded uBlock version. 
So, if I install the uBlock from the Dutch version of Firefox Add-ons / AMO not only the language should be Dutch but also the way numbers are displayed in the popup. 

### Actual behavior

Language of popup is Dutch, but the way the numbers are displayed is in the English/American style (and not the Dutch system).

### Configuration

<details>

```yaml
uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 76573
  cosmetic: 40477
  scriptlet: 16535
  html: 785
listset (total-discarded, last-updated): 
  removed: 
    ublock-badware: null
    ublock-privacy: null
    ublock-abuse: null
    ublock-quick-fixes: null
    urlhaus-1: null
    plowe-0: null
    NLD-0: null
  added: 
    https://fanboy.co.nz/enhancedstats.txt: 2989-10, 4m
    https://raw.githubusercontent.com/JohnyP36/Personal-List/main/Personal List (uBo).txt: 2271-0, 4m
  default: 
    user-filters: 1229-0, never
    ublock-filters: 32020-79, 4m
    ublock-unbreak: 1909-9, 4m
    easylist: 64686-188, 4m
    easyprivacy: 30848-1219, 4m
filterset (user): [array of 1173 redacted]
trustedset: 
  added: [array of 5 redacted]
  removed: 
    about-scheme
hostRuleset: 
  added: [array of 7 redacted]
urlRuleset: 
  added: [array of 9 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: 
  autoCommentFilterTemplate: -
  cacheStorageAPI: indexedDB
  filterAuthorMode: true
  popupFontSize: 11px
  popupPanelLockedSections: 35
  popupPanelHeightMode: 1
  uiStyles: --popup-main-min-width: 168px; --popup-gap: 0.5em; --popup-gap-thin: calc(var(--popup-gap)/9); --popup-power-ink: rgb(0,110,254); --popup-ruleset-tool-surface: rgb(240,190,64); --popup-ruleset-tool-surface-hover: rgb(240,190,64); --popup-toolbar-surface: rgb(226,226,229); --popup-toolbar-surface-hover: rgb(32 18 58 / 40%); --popup-icon-x-ink: rgb(226,40,80);
  updateAssetBypassBrowserCache: true
supportStats: 
  allReadyAfter: 4183 ms (selfie)
  maxAssetCacheWait: 1517 ms
  unsuspendAfter: 2000 ms
```

</details>

**Comment by gwarser** [comment]
https://en.wikipedia.org/wiki/Mega-

**Comment by JohnyP36** [comment]
In Microsoft Edge browser this is not a problem. 

---

### I found the problem. 

In the issue tracker I wrote that you have to check the box `Request English-language versions of web pages for enhanced privacy / Engelstalige versies van webpagina’s opvragen voor verbeterde privacy.` in `about:preferences`. 

I unchecked this box and added "Nederlands" (Dutch) to the list. 
<details> 

![afbeelding](https://user-images.githubusercontent.com/81161435/202128868-c3f89587-c20b-427d-b447-df78c247cf9f.png)

</details>

After I did this the handling of the number was correct (3,592 milj. *instead of the 3.592M*)

For me this is really strange as uBlock should not look for the language set at `Choosing your preferred languages to display web pages` but for the language FF uses to display menu's, notifications, etc. 

Although it would be better if it did not look at the browser language, but at the language version one installed of uBlock. This, as other text (such as "blocked since installation") do not change - to another language - even if I changed the browser language.

**Comment by krystian3w** [comment]
This will require "you" to generate several XPI files and generate several new URLs due addons store no offer division due to language, but only a separate XPI for Android.


Maybe exist short JavaScript workaround to update read preferences from only browser instead from webpages.

**Comment by gwarser** [comment]
Can be related: https://github.com/w3c/webextensions/issues/258

**Comment by gorhill** [comment]
> remove alternatives if there are any

I am unable to remove the _English US_ entry, the browser does not allow me to do so.

> check the box Request English-language versions of web pages for enhanced privacy / Engelstalige versies van webpagina’s opvragen voor verbeterde privacy.

I don't see a checkbox got this.

**Comment by JohnyP36** [comment]
> > check the box Request English-language versions of web pages for enhanced privacy / Engelstalige versies van webpagina’s opvragen voor verbeterde privacy.
> 
> I don't see a checkbox got this.

Maybe because your browser language is already set to English this checkbox does not appear.

> 
> Ok I can now reproduce, I replaced the step _"check the box ..."_ with just promoting (moving up) _English_ as the language to use to download webpages. Now I have Dutch text but English number format.

👍

**Comment by gorhill** [comment]
Actually I can't reproduce. It looks like I would have to download and install the Dutch package of Firefox.

**Comment by JohnyP36** [comment]
> Actually I can't reproduce. It looks like I would have to download and install the Dutch package of Firefox.

I have the Dutch package. 

1. Go to `about:preferences` 
2. Add *Nederlands* as `Language to display menu's, etc.` by clicking on `search for more language` 
 <details>

![afbeelding](https://user-images.githubusercontent.com/81161435/202226797-a42a56bf-6ef8-45ac-b6b6-a86518a37421.png)

</details>
 
4. Make sure *Nederlands* is on top of the list if you click on `Set Alternatives...` 
5. After done this add *Dutch* to the list - and move it to the top - by clicking on `Choose your preferred language for displaying pages` (or: as it will be in Dutch `Talen van uw voorkeur kiezen voor het weergeven van webpagina’s`) 
 <details> 

![afbeelding](https://user-images.githubusercontent.com/81161435/202227480-820958fc-bba6-4ff9-92de-ba71b534eb2a.png)

</details> 

7. When you open the popup menu of uBlock it will show you something like `3,602 milj.`
8. Then repeat step 4. **But** instead of moving *Dutch* to the top promote (move up) *English*
9. If you open the popup again you will notice that is shows you something like `3.602M`

**Comment by gorhill** [comment]
Is it still an issue? I tried reproducing as described above and I can't.

**Comment by JohnyP36** [comment]
> Is it still an issue? I tried reproducing as described above and I can't.

Yes, but it has to do with the fact that have my Firefox browser language in Dutch, but also enabled the function that Firefox should sent to every page that my language is English.

**Comment by gorhill** [comment]
After I set Firefox to receive English pages, my popup panel was still respecting the language set for Firefox UI, so I guess I just don't get what is the issue.

**Comment by JohnyP36** [comment]
> After I set Firefox to receive English pages, my popup panel was still respecting the language set for Firefox UI (French), so I guess I just don't get what is the issue.

That's correct. 

- Set your browser language to French and also the language how Firefox should receive pages. 
   You will see that the way the numbers are shown in the popup are according to french number notation. 
- Next, go to `about:config` in FF and change `privacy.spoof_english` to `2`. 
   Now you will see that the language in the popup is still French, but the numbers are according to English notation.

Make sure will doing each step to disable and then enable uBlock again to activate the changes in the popup. 
Maybe this will help you

**Comment by krystian3w** [comment]
As far as French/Canadian notation differs from English.

**Comment by JohnyP36** [comment]
In French the notation is `4,533 M` and in English `4.533M`. So, when you set the `about:config => privacy.spoof_english to 2` it does not stick to French notation.
In Dutch the notation is `4,533 milj.` but with the `privacy.spoof` set to 2 it also will adapt the english notation.

Thus, for me, it will become this:
![afbeelding](https://user-images.githubusercontent.com/81161435/227958141-ba7e581a-c126-4973-ac52-10386bd6a0a4.png)
Instead of: 
![afbeelding](https://user-images.githubusercontent.com/81161435/227959081-6e60a397-5715-46dd-9601-150a387a2276.png)

**Comment by gorhill** [comment]
> So, when you set the about:config => privacy.spoof_english to 2 it does not stick to French notation.

It does on my side:

![Screenshot from 2023-03-27 10-06-01](https://user-images.githubusercontent.com/585534/227963893-7e05cab7-795f-4ac1-8892-f13c0d10137b.png)

**Comment by JohnyP36** [comment]
Did you also disable and then re-enable ublock?

**Comment by JohnyP36** [comment]
> > Did you also disable and then re-enable ublock?
> 
> Yes. Tested on Firefox 111.0. Your Firefox looks very different than mine, what version are you using? Maybe try in a new profile, if you modified stuff in `about:config`.

I did change a lot. But that has to do with the looks. 
The problem is with the `privacy.spoof_english` set to `2` even in a new profile.

**Comment by JohnyP36** [comment]
Although closed as invalid. I can report now that due to changes in Firefox this problem is solved.
