### ISSUE TITLE
A false negative case for regex rule

### ISSUE THREAD

**Issue by danny0838** [uBlockOrigin/uBlock-issues#2367]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A case that a regex rule fails to match. Probably due to bad token extraction around `(?:ter\.)?`.

### A specific URL where the issue occurs.

https://example.com/foobar

### Steps to Reproduce

1. Add a user rule `/^https?://(?:example\.com|ex\.com)/foo(?:ter\.)?bar(?=[/?#]|$)/$document`
2. Visit `https://example.com/foobar`

### Expected behavior

The page should be blocked.

### Actual behavior

The page is not blocked.

### uBO version

1.44.4

### Browser name and version

Google Chrome 107.0.5304.107

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Problem is [here](https://github.com/gorhill/uBlock/blob/2204451514f1a894a7627793a253a89ebbc6d845/src/js/static-filtering-parser.js#L3053-L3056), this needs fixing:

>    if ( node.flags.min === 0 && first === 0 && last === 0 ) {
>         return '';
>    }
>    return String.fromCharCode(first, last);

**Comment by gwarser** [comment]
My filters need to be modified after update for filter to work correctly.

**Comment by danny0838** [comment]
@gorhill Thank you for the quick fixing.

About the part of processing optional sequences, I wonder repeated execution is flawed if length of middle is not exactly 2 (e.g. `foo\x02\x02\x02\x02bar`), as `s` is changing inside the loop.

**Comment by gorhill** [comment]
You're right, thanks for catching this. Will fix asap.

**Comment by gorhill** [comment]
Your regex shows as non-tokenizable on my side -- which is what we want:

![Screenshot from 2022-11-17 13-43-50](https://user-images.githubusercontent.com/585534/202531555-e0020561-04a0-4513-a4b7-c271cfe85c15.png)

**Comment by danny0838** [comment]
SGTM. Thank you.
