### ISSUE TITLE
matches-path doesn't work with Persian characters

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2369]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I want to hide reportages on this website which can be seen on:
`https://www.downloadsoftware.ir/page/90`
Title: _آموزش ساخت آهنربای دائمی در خانه_ with the magnet photo.

But I don't want to hide reportages on the dedicated "example.com/reportage" page.

### A specific URL where the issue occurs.

`https://www.downloadsoftware.ir/%d8%b1%d9%be%d9%88%d8%b1%d8%aa%d8%a7%da%98`

### Steps to Reproduce

1. Go to:
`downloadsoftware.ir`

2. On the right sidebar click on the green button "رپورتاژ" (meaning _Reportage_) which will redirect to `https://www.downloadsoftware.ir/%d8%b1%d9%be%d9%88%d8%b1%d8%aa%d8%a7%da%98` for a brief moment then to `https://www.downloadsoftware.ir/رپورتاژ`

3. Try in the element picker:
`##:not(:matches-path(/رپورتاژ)) .art-post > .head-post > .cat-post:has-text(رپورتاژ):upward(.art-post)`

4. Then try:
`##:not(:matches-path(/%d8%b1%d9%be%d9%88%d8%b1%d8%aa%d8%a7%da%98)) .art-post > .head-post > .cat-post:has-text(رپورتاژ):upward(.art-post)`

### Expected behavior

The filter in number 3 should not work on that page.

### Actual behavior

The filter in number 3 wrongly applies to that page, only the filter in number 4 doesn't.

### uBO version

1.45.2

### Browser name and version

Firefox 106.0.4

### Operating System and version

‌

**Comment by krystian3w** [comment]
Maybe recommenation will by code only in ASCII:

https://github.com/uBlockOrigin/uBlock-issues/issues/1246#issuecomment-701683998

Worse if AdGuard added both methods - if not then no need really asap implement as https://github.com/uBlockOrigin/uBlock-issues/labels/enhancement.
