### ISSUE TITLE
Filters are blocking "The White House" on Facebook.

### ISSUE THREAD

**Issue by Daniel-USA** [uBlockOrigin/uBlock-issues#237]
One of the filters you use is now blocking "The White House" on Facebook.

I reported this to NanoAdBlocker and they were rude about it but they also pointed out it would happen to you.

Originally I was using their adblocker but due to their callous rudeness I switched to Ublock, well a day has passed and it has now happened to Ublock Origin.

provided is the information they managed to gather. 

They originally blamed it on "Ublock filters"
facebook.com#@#div[id^="hyperfeed_story_id_"]:has(a[href*="utm_campaign"])

but then

the same filter is in easylist too
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href*="utm_campaign"])

So easylist and ublock filters are censoring the President's cabinet. Not cool.

**Comment by mapx-** [comment]
Nobody is censoring whatever stuff. It was about a false positive and it was fixed. 
Just update your lists and refrain commenting on things you obviously don't understand.

**Comment by Daniel-USA** [comment]
It got fixed because I reported it. You should be grateful that people troubleshoot your apps instead of trying to insult their intelligence.

**Comment by uBlock-user** [comment]
> facebook.com#@#div[id^="hyperfeed_story_id_"]:has(a[href*="utm_campaign"])

That's a disabling cosmetic filter, so not possible. 

> people troubleshoot your apps

Filters are not apps, hence there's nothing to troubleshoot, filters are maintained by filterlist maintainers, nothing to do with uBO.
