### ISSUE TITLE
> https://github.com/uBlockOrigin/uAssets/issues/15609#issuecomment-1310749200

### ISSUE THREAD

**Issue by swiezaczek** [uBlockOrigin/uBlock-issues#2370]
> https://github.com/uBlockOrigin/uAssets/issues/15609#issuecomment-1310749200
>
>  I think this site does not contain free material anymore

Still exist free content like:

`https://player.pl/seriale-online/skazana-odcinki,31908` with section ads in 1/5 and 4/5 of time:

![obraz](https://user-images.githubusercontent.com/35370833/202563961-86454187-efdd-423c-8b93-1f32ec835ecf.png)

Maybe this is long teaser to consider buy subscription.

_Originally posted by @krystian3w in https://github.com/uBlockOrigin/uAssets/issues/15609#issuecomment-1319230812_

Yes, it stops playing where the skipped ads are located

**Comment by swiezaczek** [comment]
Opened in wrong place

**Comment by krystian3w** [comment]
I wasn't meant mainly stopped (but I don't have idea how disable load ad sections).
