### ISSUE TITLE
Ignore max-0 quantifiers

### ISSUE THREAD

**Issue by danny0838** [uBlockOrigin/uBlock-issues#2371]
A max-0 quantifier should be ignored, and thus

    case 16: /* T_QUANTIFIER, 'Quantifier' */ {
        const s = this.tokenizableStrFromNode(node.val);
        const first = this.firstCharCodeClass(s);
        const last = this.lastCharCodeClass(s);
        if ( node.flags.min !== 0 ) {
            return String.fromCharCode(first, last);
        }
        return String.fromCharCode(first+2, last+2);
    }

can be improved as

    case 16: /* T_QUANTIFIER, 'Quantifier' */ {
        const s = this.tokenizableStrFromNode(node.val);
        const first = this.firstCharCodeClass(s);
        const last = this.lastCharCodeClass(s);
        if ( node.flags.max === 0 ) {
            return '';
        }
        if ( node.flags.min !== 0 ) {
            return String.fromCharCode(first, last);
        }
        return String.fromCharCode(first+2, last+2);
    }

This is for completeness. Although it is probably uncommon in real-world regexes, maybe some code-generated ones?

About: [f48c03e5316b3546c8c9772c276abd72d9af0b2e](https://github.com/gorhill/uBlock/commit/f48c03e5316b3546c8c9772c276abd72d9af0b2e)

**Comment by krystian3w** [comment]
You are blocked on uBlock-Issues / uBlock-Lite-issues?

**Comment by gorhill** [comment]
Can you show me an example of such regexes?

**Comment by danny0838** [comment]
I can be something like `/\bfoo(whatever){0,0}bar\b/`, and a token `foobar` should be extractable from it.

**Comment by gorhill** [comment]
I will add it because it's very trivial but in general keep in mind I prefer to not change code when there are no real world reasons to do so.

**Comment by danny0838** [comment]
Thank you.
