### ISSUE TITLE
Support UnicodeChar/HexChar

### ISSUE THREAD

**Issue by danny0838** [uBlockOrigin/uBlock-issues#2372]
Add support for UnicodeChar and improve support for HexChar:

      case 32: /* T_UNICODECHAR, 'UnicodeChar' */
      case 64: /* T_HEXCHAR, 'HexChar' */ {
          return node.flags.Char;
      }

About: [f48c03e5316b3546c8c9772c276abd72d9af0b2e](https://github.com/gorhill/uBlock/commit/f48c03e5316b3546c8c9772c276abd72d9af0b2e)

**Comment by danny0838** [comment]
Additionally, as the token extractor uses `\x00`, `\x01`, etc., internally, replacing control chars into `\x00` to prevent misusing may be considered.

**Comment by gorhill** [comment]
We have to keep in mind that the code is for a very specific purpose of tokenizing network filters, which are meant to be ASCII (Unicode characters are converted beforehand if any), and the goal is not make that very specific code to be absolutely foolproof for all cases outside its current purpose. Is there an actual case static network filter case which could fail with the current code? If not, I rather not change it just for the sake of making it foolproof outside its current purpose.

**Comment by danny0838** [comment]
I know that a URL is ASCII only, and the use case of `\xXX` or `\uXXXX` in a regex are probably equally very rare. Since you have decided to implement support for the vary rare case of `\xXX`, an optimization and a simple improvement (only one line code addition) shouldn't be too bother, though.

**Comment by gorhill** [comment]
Any thought on using `return encodeURIComponent(node.flags.Char);` instead?

**Comment by danny0838** [comment]
I don't think we should do it. For example, a regex `/\x23/` is matching `#` rather then matching `%23`.

**Comment by danny0838** [comment]
As URLs are ASCII only, no actual URL will include `-µBlock-`. If some wants to filter `https://example.com/-%C2%B5Block-`, he should write `/-%C2%B5Block-/` instead of `/-µBlock-/` or `/-\u00b5Block-/`, which won't match any actual URL.

**Comment by gorhill** [comment]
So we are coming back to my initial comment, filters with the form `\uxxxx` will not occur and we should not care about these. The default for unhandled cases is to assume no word boundary (`return '\x01'`). I will change `T_HEXCHAR` as I didn't realize `node.flags.Char` was readily available.

**Comment by danny0838** [comment]
For https://github.com/gorhill/uBlock/commit/42a7cfced3844f3384caa3189c548ba2102b469a, I wonder if we should specially handle all control chars, or at least `\x01` and `\x03`?

**Comment by danny0838** [comment]
`\u00XX` is equivalent to `\xXX` for ASCII ranges, and that's why I think the former should be supported if the latter is supported.

**Comment by gorhill** [comment]
I am going to decline modifying further the code in there unless there are actual cases of failure. There are still a lot of pending issues to be fixed, and spending time in that part of the code not for the purpose of solving actual issue is not a good use of finite time resources.

**Comment by danny0838** [comment]
Wouldn't int comparison more performant and extensible?

```javascript
// prevent confusion with internally used chars
// (note: control chars are invalid in a normal URL)
const code = parseInt(node.flags.Code, 16);
if (0x00 <= code && code <= 0x03) { return '\x00'; }
```

Again, this is trivial enough, and whether to implement it is all up to you.
