### ISSUE TITLE
`[x-]` is not correctly handled

### ISSUE THREAD

**Issue by danny0838** [uBlockOrigin/uBlock-issues#2374]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [x] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The revised regex analyzer does not correctly handle `[x-]`, which is treated as `[\-]` and thus `x` is not calculated during token extraction.

I have raised an issue to the library developer: https://github.com/foo123/RegexAnalyzer/issues/5. Before the library is fixed, we can preprocess the regex string to escape problem-making "-"s in a character group before sending it to the analyzer:

```javascript
const REGEX_RE_STR_FIXER = /\\[\s\S]|\[([^\\\]]*(?:\\[\S\s][^\\\]]*)*)\]/g;
const REGEX_RE_STR_FIXER_FUNC = (m, cg) => (cg ? '[' + cg.replace(REGEX_RE_STR_FIXER_CG, REGEX_RE_STR_FIXER_CG_FUNC) + ']' : m);
const REGEX_RE_STR_FIXER_CG = /^\^|(?:[^\\\]]|\\(?:x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|[^dDsSwW]))-(?:[^\\\]]|\\(?:x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|[^dDsSwW]))|\\[\s\S]|(-)/g;
const REGEX_RE_STR_FIXER_CG_FUNC = (m, h) => (h ? '\\-' : m);

// fix analyzer bug for e.g. [x-], [-x], [\d-x], [x-\d]
// https://github.com/foo123/RegexAnalyzer/issues/5
reStr = reStr.replace(REGEX_RE_STR_FIXER, REGEX_RE_STR_FIXER_FUNC);
```

This is somehow ugly and imperformant, but it may be the only way if we're not going to implement a full fix of the library.

Also note that this does not fix the bug in 5th case yet. Fortunately the case should not exist in a real-world URL filter.

### A specific URL where the issue occurs.

https://example.com/xfoo

### Steps to Reproduce

1. Add a user rule `/^https?://(?:example\.com|ex\.com)/[x-]foo\b/$doc`
2. Visit the URL

### Expected behavior

The page should be blocked.

### Actual behavior

The page is not blocked.

### uBO version

1.45.3b4

### Browser name and version

Independant

### Operating System and version

Independant

**Comment by gwarser** [comment]
Maybe this is why regex was reported as invalid when `-` was last in the group?

**Comment by danny0838** [comment]
@gwarser Where is it reported?

ECMAscript spec seems to allow such use case.

**Comment by gwarser** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/134630

**Comment by danny0838** [comment]
@gwarser I have read the thread but I don't think there is a consensus that trailing `-` is invalid.

**Comment by gwarser** [comment]
I mean, it's this library limitation.

**Comment by gorhill** [comment]
> if we're not going to implement a full fix of the library

No, we are not.

Regex-based filters are a minority in filter lists. Untokenizable regex-based filters are a fraction of that minority, and ultimately, there is a workaround, which is to escape the `-`.

If you want to keep opening issues about the tokenizer because you want it to be perfect (I don't), please just add to the one issue here. For now it's unlikely I will address these only if I find they actually are worth working on according to real world occurrences.

**Comment by gorhill** [comment]
Any more of these cases with regex tokenizer, please add here instead of opening new issue.

**Comment by danny0838** [comment]
The developer of Regex.js is fixing the issues and it seems that this issue is mostly resolved by the latest release (with a bug that may happen in a very rare case). Maybe we can simply wait for a while for his working.

**Comment by danny0838** [comment]
Issues in https://github.com/foo123/RegexAnalyzer/issues/5 seems resolved in 1.2.0

**Comment by gorhill** [comment]
Version of 1.2.0 was imported.

**Comment by micsthepick** [comment]
Regexes with many options in a capture group seemingly don't pass validation?

practical example: ```/^.*r[oO0]uter[i1lt][oO0]g[i1ltoO0]n\..*$/```

minimum example: ```//[i1ltoO0]//```

**Comment by micsthepick** [comment]
actually, there seems to be something stranger happening... investigating futher.

**Comment by micsthepick** [comment]
a couple things are going on here: 1. I visited a page and it didn't get blocked when it should have matched the above: `routerlogon.com`, although if that does not reproduce I'll not worry about it, however... 
2. ```/^.*n[i1lt]gh[i1lt]hawk-app\..*$/``` does not seem to have appropriate syntax highlighting...?

**Comment by micsthepick** [comment]
ah! minimum example of the second one `/a-z/` should be highlighted orange, but is not, presumably because of the `-` character OUTSIDE an alternation group.

**Comment by garry-ut99** [comment]
>  `/a-z/` should be highlighted orange, but is not

Why, since it matches 3 characters literally, like any others: `---` or `abc`.
You mean `/a-z/` or `/[a-z]/`? Didn't you miss `[` and `]` in your example?
Also since `/[a-z]/` means a single letter, then logically your request would also include making organe other single-char expressions like: w `\w` or `\W` and similiar.

**Comment by micsthepick** [comment]
> > `/a-z/` should be highlighted orange, but is not
> 
> Why

Becuase that's what happens to regexes as a general rule, even simple ones

> You mean /a-z/ or /[a-z]/? Didn't you miss [ and ] in your example?

I meant what I said, and said what I meant.

> A note: the whole discussion is regarding a fact that a single char filters in uBO are invalid (orange): for example: `a` or `/a/`, so a point I see in his request is to unify the syntax highlighting behavior towards single-char filters, so that also regexes which match only a single-char, are considered to be invalid (orange) as well.

That's a minsomer - to be explicitly clear - if you tried putting a regex in that IS valid, and doesn't happen to contain an ungrouped a-z, etc. it WILL be marked orange, error or not.

**Comment by micsthepick** [comment]
what did I mean when I wrote:

> presumably because of the - character OUTSIDE an alternation group
?

**Comment by garry-ut99** [comment]
> > > `/a-z/` should be highlighted orange, but is not
> > 
> > 
> > Why
> 
> Becuase that's what happens to regexes as a general rule, even simple ones


What happens is:
- that they have yellow color, not orange
- not always they have yellow or any color

<img src="https://github.com/user-attachments/assets/753e8bb9-c03a-44ee-ab08-3b101cf992dd" width=700)>

Also do we perceive colors differently?
<img src="https://github.com/user-attachments/assets/ea70d6ab-522a-4915-9229-163ab28146d9" width=400)>

Orange color means an invalid filter, why do you want `/a-z/` become invalid?:
<img src="https://github.com/user-attachments/assets/21866de2-318b-4601-be92-bef29c71bdc1" width=400)>

> That's a misconception - to be explicitly clear - if you tried putting a regex in that IS valid, and doesn't happen to contain an ungrouped a-z, etc. it WILL be marked orange, error or not.

You didn't provide an exact regex example to reproduce, you only provided `/a-z/`, which is yellow, not orange, and isn't invalid, which one do you exacty mean:
<img src="https://github.com/user-attachments/assets/eaf5e64e-be38-4d22-94aa-f2dce454c5a3" width=700)>

**Comment by micsthepick** [comment]
this color (in dark mode) is the orange I have seen. Not sure if there IS any other orange.
![image](https://github.com/user-attachments/assets/2a24a107-cc72-4bbb-bd96-63e52bca415f)

**Comment by micsthepick** [comment]
> not always they have yellow or any colour
why?

**Comment by micsthepick** [comment]
re. the provided example:
why is ````/a-z/`` yellow, but ```/z-a/``` not?

**Comment by micsthepick** [comment]
my bad, ack! the problematic regex is ```/\./```

**Comment by micsthepick** [comment]
it seems like it needs two "problems" to confuse the parser, if that makes any sense.

**Comment by micsthepick** [comment]
a less crude example: `/ex-ample\.com/`

**Comment by garry-ut99** [comment]
> micsthepick : should be highlighted orange

That sounded more like you meant font background color, and not an underline, that's where all the misunderstanding came from, especially given a fact, that on Light Theme these underlines are barely visible on fon't yellow/red background color.

> micsthepick : a less crude example:
`/ex-ample\.com/` has no "error"
`/example\.com/` has 1 "error"

One detail: these are warnings, not errors, and such filters still work, just like in browser dev console there are warnings and errors.

**Comment by garry-ut99** [comment]
> micsthepick : https://github.com/uBlockOrigin/uBlock-issues/issues/3362#issuecomment-2324385100 :  It's also a bit ironic that you link to a post where you call someone a clown and yet continue to call me aggressive.

What is ironic is that I called him a clown because he was aggressive towards me for no reason, just like you.
Don't turn facts upside down and stop trolling.

What is also ironic, is that you've banned me in your thread `#3362` silently, without informing anyone that I can't reply and defend anymore against your trolling and personal attacks, hence I'm forced to defend in other threads.

**Comment by gorhill** [comment]
> `/ex-ample\.com/` has no "error"
> `/example\.com/` has 1 "error"

Orange is not an error, it just means no token can be extracted from the regex.

A token can be extracted from the first one, `ample`. No token can be extracted from the second one.

**Comment by garry-ut99** [comment]
Also very helpful threads related to regex tokenization:
- https://github.com/gorhill/uBlock/issues/2781
- https://github.com/uBlockOrigin/uBlock-issues/issues/2368
- https://github.com/gorhill/uBlock/wiki/Filter-Performance#narrowing-options-for-network-filters

Some similiar examples from old version of uBO tokenizer:

Revision A: https://github.com/gorhill/uBlock/issues/2781#issuecomment-314523937:
```
token: konto, regex: /moje-konto\/inzeraty/
token: *, regex: /moje-inzeraty/
token: *, regex: /prime-ads/
```

Revision B: https://github.com/gorhill/uBlock/issues/2781#issuecomment-314541651:
```
token: konto, regex: /moje-konto\/inzeraty/
token: *, regex: /moje-inzeraty/
token: konto, regex: /moje-konto\/inzeraty/
token: *, regex: /ad-pay/
token: bin, regex: /cgi-bin\/conad.fcgi/
token: *, regex: /prime-ads/
```

**Comment by gorhill** [comment]
The ultimate revision is the one based on a regex analyzer, introduced in <https://github.com/gorhill/uBlock/commit/426395aa0373249cda1f2ca4bb69b4f7a5f33722>.

**Comment by garry-ut99** [comment]
> https://github.com/uBlockOrigin/uBlock-issues/issues/2374#issuecomment-2324214344 : micsthepick :
> # Syntax highlighting is confusing:
> 
> `/ex-ample\.com/` has no coloration 
> `/example\.com/` has coloration 
> and yet no message to explain why.

Like on the 3rd screenshoot from https://github.com/uBlockOrigin/uBlock-issues/issues/2374#issuecomment-2324125132 - there is a message (tool tip) displayed when an error is highlighted, but not when a warning is highlighted. I don't know whether it's an inconsistency or intentionally by design. Besides, another related thread (in case u didn't see):
- https://github.com/uBlockOrigin/uBlock-issues/issues/1134
