### ISSUE TITLE
Why isn't the green toggle on the filter panel showing up anymore?

### ISSUE THREAD

**Issue by throwaway2342** [uBlockOrigin/uBlock-issues#2375]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I can't really find the green toggle thing anymore on the filter panel...not the list...the exterior panel

on chrome as well on windows 11

### A specific URL where the issue occurs.

everywhere.com

### Steps to Reproduce

1.Click the icon 
2.Find a link to toggle on the filter panel
3. look for the green toggle thing on the panel
4. not there

### Expected behavior

Green toggle should show up 

### Actual behavior

doesn't 

### uBO version

1.45.2

### Browser name and version

Google Chrome Version 107.0.5304.107 (Official Build) (64-bit)

### Operating System and version

Windows 11

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#filterauthormode

in the advanced settings panel switch it to `true`

![image](https://user-images.githubusercontent.com/10303732/202975917-8622cf31-137c-4c78-9347-481a040938ab.png)

**Comment by throwaway2342** [comment]
thank you---solved
