### ISSUE TITLE
Restore :if-not() support as an alias of :not(:has())

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2376]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

No support of `:if-not`, though rarely used, can cause problems.
https://github.com/AdguardTeam/AdguardFilters/issues/135390

### A specific URL where the issue occurs.

https://www.colordic.org/gradation

### Steps to Reproduce

1. Visit the site with Japanese filters enabled and Unbreak disabled, you'll see nearly all contents hidden due to `colordic.org#?#footer > div.container > div.row:if-not(.text-muted)`.

### Expected behavior

`:if-not()` should be converted to `:not(:has())`

### Actual behavior

`:if-not()` is ignored, causing false positive.

### uBO version

1.45.2

### Browser name and version

Chrome 107.0.5304.107

### Operating System and version

Windows 10

**Comment by Yuki2718** [comment]
Will add temp fix to Unbreak.

**Comment by Yuki2718** [comment]
Oh, forgot uBO once supported if-not.

**Comment by gorhill** [comment]
`:if-not()` is not in uBO's own documentation, and AdGuard discourages its use, so the AdGuard filter list person surely should not be using it? I don't want to keep piling on deprecated code just for the sake of someone somewhere might use it. The AdGuard person who used `:if-not(...)` should be told to use `:not(:has(...)))` instead, that would easily solve the issue for all.

**Comment by gorhill** [comment]
I am thinking of removing AdGuard Base from uBO's stock list. The main reason it was added a long time ago was because unlike EasyList, it was using special `style(...)` syntax which was beneficial to uBO, at a time when uBO did not have its own solid well maintained lists. This is no longer the case, and seeing that now exception filters are added in _Unbreak_ just for the sake of excepting a filter which is not part of default lists, it's probably time to drop AdGuard Base to reduce the burden of having to mind incompatibility.

**Comment by Yuki2718** [comment]
My exception is for Japanese filters, a default regional list.

**Comment by Yuki2718** [comment]
I contacted @zloyden but he's currently away. I'll change the rule and remove from Unbreak.

**Comment by gorhill** [comment]
By the way, `div.row:if-not(.text-muted)` can't be enforced declaratively by the browser, while `div.row:not(:has(.text-muted))` is enforced declaratively by the browser (at least in uBO) -- i.e. it's part of the injected stylsheet and the browser does the filtering.

**Comment by krystian3w** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2228#issuecomment-1291586324

Also removed from support is `:if(...)` / `[-ext-has]`:


```adb
! both "0 match" nodes/elements
##.TimelineItem:if(#issue-1458171112)
#?#.TimelineItem[-ext-has="#issue-1458171112"]
```

`[-ext-has]` usage:
 * AG Base: 123 lines, with domains +347 uses (15 disabled by comment for `quora.com` and 1 for `wp.pl`)
 * AG Mobile Ads: 23 lines, with domains 24 uses (0 disabled)
 * AG French: 6 lines/uses (0 disabled)
 * AG Spa/Por: 5 lines/uses (0 disabled)
 * AG Turkey: 36 lines/uses (0 disabled)

`:if(...)` don't exist thankfully in AG files after convertion for uBO
