### ISSUE TITLE
Unable to import custom lists on 1.45.2

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2380]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Title, happens on both Firefox and Chromium

### A specific URL where the issue occurs.

/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Copy and paste whatever list URL into Import e.g. `​https://filters.adtidy.org/extension/ublock/filters/18.txt`
2. Now Apply can't be clicked and thus you can't import custom lists.

### Expected behavior

Apply turns to be clickable when URL is pasted

### Actual behavior

Not

### uBO version

1.45.2

### Browser name and version

Firefox 107.0/Chrome 107.0.5304.107

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
There is an invisible Unicode character in your URL at the beginning:

    \u200Bhttps://filters.adtidy.org/extension/ublock/filters/18.txt

Remove this Unicode character and it works fine.

**Comment by gorhill** [comment]
I am going to add a `trim()`, it seems this removes that one invisible zero-width space.

**Comment by gwarser** [comment]
Maybe should be rendered by Codemirror with highlighted control characters?

**Comment by Yuki2718** [comment]
> There is an invisible Unicode character in your URL at the beginning:

Sorry, didn't notice that.
