### ISSUE TITLE
NS_ERROR_DOM_BAD_URI on $empty filter rules

### ISSUE THREAD

**Issue by Alcaro** [uBlockOrigin/uBlock-issues#2381]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

$empty, $redirect and $redirect-rule don't work - they throw a NS_ERROR_DOM_BAD_URI error (which is converted to a generic NetworkError on the JS side).

Originally found while investigating a memory leak involving Discord's /science endpoint, but this issue is not specific to Discord and is not related to any filter list.

### A specific URL where the issue occurs.

https://floating.muncher.se/temp/ubo.html

### Steps to Reproduce

1. Add filter rule for `||floating.muncher.se/temp/test.json$empty`
2. Go to https://floating.muncher.se/temp/ubo.html

The page simply contains
```js
<script>
try {
	var xmlhttp = new XMLHttpRequest();
	xmlhttp.open("GET", "test.json", false);
	xmlhttp.send();
	alert(xmlhttp.responseText);
} catch (e) {
	alert(e);
}
</script>
```

### Expected behavior

The xmlhttprequest should successfully return a blank string

### Actual behavior

The XHR throws a "NetworkError: A network error occurred." Checking the network dev tools reveals a NS_ERROR_DOM_BAD_URI, though neither dev tools nor uBO's logger tell me which exact URI is invalid.

### uBO version

uBlock Origin 1.45.2

### Browser name and version

Firefox 102.5.0esr x86-64; Firefox 107.0 x86-64

### Operating System and version

Debian testing x86-64; Lubuntu 22.04 x86-64

**Comment by gorhill** [comment]
uBO redirects to a `data:`, and it seems Firefox does not like this.

MDN's own documentation [points out](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest#examples) that we can redirect to `data:` URI, however there is [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=707624) regarding redirecting to `data:` URI.
