### ISSUE TITLE
$popup doesn't work when redirection from http to https

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2382]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/uBlockOrigin/uBlock-issues/discussions/2270

`$popup` strange behavior in uBO

Preferably disable the main uBlock Filters list.

Add:
```adb
||asiatech.ir^$popup,domain=soft98.ir
||hostdl.com^$popup,domain=soft98.ir
```

Go to the footer of `soft98.ir`:
Click on "آسیاتک" => It closes
Click on "هاست دی ال" => It won't close

Both links have `target=_blank`. 

Reproduced using Firefox.

### A specific URL where the issue occurs.

`https://soft98.ir`

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

.

### Browser name and version

.

### Operating System and version

.

**Comment by gorhill** [comment]
Why open an issue about this? I explained why the observed behavior.
