### ISSUE TITLE
Slow browser startup and load on Firefox for Android when a lot of filter lists are enabled

### ISSUE THREAD

**Issue by filips123** [uBlockOrigin/uBlock-issues#2386]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When many filter lists are enabled, the initial (after browser startup) page loading on Firefox Nightly for Android will be slowed down significantly. This is especially noticeable when opening installed web apps, which will show a blank screen for around 5 seconds and continue loading slowly for another 10 seconds.

This happens even when prefetching is enabled, "suspend network activity until all filter lists are loaded" is disabled and uBlock Origin is disabled for that site. When the whole uBlock Origin extension is disabled or all filter lists are disabled, the web app startup is quite faster.

The issue still happens with default filter lists, but it's noticeable, because fewer of them are enabled. I also tested this on a fresh install some time ago (but current performance profiles are from existing browser profile).

### A specific URL where the issue occurs.

https://twitter.com/

### Steps to Reproduce

1. Enable a lot of filters on uBlock Origin (I enabled most of them so the issue is more noticeable)
2. Install any PWA (I used Twitter but it happens also with others)
3. Completely close Firefox (stop the app from Android's open apps view)
4. Open installed PWA
5. Observe slow startup

Do the same thing but with disabled uBlock Origin. The startup should be faster.

### Expected behavior

Web app startup shouldn't be slowed down significantly.

### Actual behavior

Web app startup is slowed down significantly.

I collected a few startup performance profiles:

* uBO disabled: https://share.firefox.dev/3Oy6qnM
  The load seems to work file. The first network request is around 3.5s, the website starts loading at around 4s and is loaded at 10.5s.
  Timings for other websites are a bit different (faster on not-so-heavy sites like Twitter), but in general, it is similar.
  (It also appears startup is a bit slower when running a profiler but I cannot confirm this.)

* uBO enabled, filter lists disabled: https://share.firefox.dev/3gyQkxO
  Timings are still similar, but it seems everything happens about 1 second later.

* uBO Enabled, many filter lists enabled: https://share.firefox.dev/3tY01sL
  The load is a lot slower. The first network request happens at around 5s, but other, previously quite fast requests take more than 7s. The Twitter logo appears at 6s but then takes more than 15s to fully load the site.
  In the call stack, I can see a lot of UBlock-related calls that take a long time. For example, `onFilterListsReady` has a "traced running time" of more than 5s and `loadFilterLists` more than 2s. During this time, the profiler also detects jank (event processing delay).

### uBO version

1.45.2

### Browser name and version

Firefox Nightly 109.0a1

### Operating System and version

Android 10

**Comment by gwarser** [comment]
This happens on fresh install or if you tinker with filter lists.  Update your lists and wait [two minutes](https://github.com/gorhill/uBlock/wiki/Advanced-settings#selfieafter) and then test again how it starts with _selfie_.

**Comment by gorhill** [comment]
You can check the setting [_"Suspend network activity until all filter lists are loaded"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded) if you do not want uBO to hold back page loading at browser launch.

Ar some point it's almost as asking for miracle, or if you are convince this can be reasonably improved, please submit a pull request.

**Comment by filips123** [comment]
Thanks for quick responses.

> You can uncheck the setting ["Suspend network activity until all filter lists are loaded"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded) if you do not want uBO to hold back page loading at browser launch.

I have that option disabled. It looks like uBO still loads filters in background, but that extra work slowed down website loading. I guess that might be a problem with Firefox, so unless there is some way to deprioritize filter loading, I don't know what could fix this. With *selfie*, some delay still happens but it's less noticeable, so it's mostly fine.

In case this is useful, here are some additional profiles, now on fresh Firefox stable 107:
* [Without uBO](https://share.firefox.dev/3OAGecm)
* [With uBO with selfie](https://share.firefox.dev/3VH564H)
* [With uBO without selfie](https://share.firefox.dev/3Xt2id0)

> So not a uBO issue.

I think uBO still loads filters in the background even if it's disabled for a specific site. For example, in [this profile](https://share.firefox.dev/3tVdYHZ), uBO is disabled for Twitter. I intentionally switched some filter lists so *selfie* has to be regenerated. Then, I quit Firefox and opened it again. Twitter still took a long time to load and the profiler showed uBO-related activity.

> As far as PWA is concerned, Mozilla will not be supporting it ever

Firefox on Android has basic support for PWAs, but this slowdown also happens when the browser just loads previous tab on startup.

**Comment by krystian3w** [comment]
Maybe kill app from android settings is bad, how work this after restart android or update browser?

**Comment by gorhill** [comment]
> lot of filter lists
> many filter lists

Please be specific.

**Comment by filips123** [comment]
For example, with these settings:

```json
{
  "timeStamp": 1669387590477,
  "version": "1.45.2",
  "userSettings": {
    "importedLists": [],
    "suspendUntilListsAreLoaded": false
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "easyprivacy",
    "urlhaus-1",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "plowe-0",
    "SVN-0"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-csp-reports: * true",
  "userFilters": ""
}
```

Loading is a few seconds (1-2s) slower than without uBlock. It's the same when "twitter.com" is whitelisted.

**Comment by krystian3w** [comment]
> ```yml
>     "adguard-social",
>     "fanboy-cookiemonster",
>     "fanboy-annoyance",
>     "fanboy-social",
> ```

posible reduce to only `fanboy-annoyance` if this something change other than network bandwidth of downloaded uneeded files.

**Comment by gorhill** [comment]
I rather you provide the troubleshooting information, it's easier to see which lists were added on top of default ones. It's not realistic to enable too many lists on underpower devices, so I do not want to spent time analyzing unrealistic scenarios. I already see that you enable AdGuard Spyware and AdGuard Base, which I believe is pointless especially for an underpowered devices.

The only scenario I can entertain for now is default lists, which _may_ contain a regional list, loaded from a selfie.

**Comment by filips123** [comment]
I've now reduced the amount of list, and the slowdown has been reduced to around 1s. Here are troubleshooting info:

```
uBlock Origin: 1.45.2
Firefox Mobile: 109
filterset (summary):
  network: 63045
  cosmetic: 68941
  scriptlet: 22721
  html: 883
listset (total-discarded, last-updated):
  removed:
    easylist: null
  added:
    adguard-annoyance: 61306-1834, 6m
    ublock-annoyances: 4876-7, 6m
  default:
    user-filters: 9-0, never
    ublock-filters: 32379-824, 6m
    ublock-badware: 4038-1, 6m
    ublock-privacy: 305-1, 6m
    ublock-abuse: 77-0, 6m
    ublock-unbreak: 1921-1, 6m
    ublock-quick-fixes: 612-0, 6m
    adguard-mobile: 8248-166, 6m
    easyprivacy: 30881-1813, 6m
    urlhaus-1: 11476-0, 6m
    plowe-0: 3667-3, 6m
    SVN-0: 571-10, 6m
filterset (user): [array of 9 redacted]
trustedset:
  added: [array of 1 redacted]
modifiedUserSettings:
  prefetchingDisabled: false
  suspendUntilListsAreLoaded: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats:
  allReadyAfter: 1635 ms (selfie)
  maxAssetCacheWait: 630 ms
  unsuspendAfter: 726 ms
```

Maybe both adguard-annoyance and ublock-annoyances are redundant, but I think I encountered some annoying popups in the past without some of them. Otherwise, there are basically just default filter lists.

1s slowdown is mostly acceptable for me, so if you think it's not worth optimizing this further, this issue can be closed.

**Comment by gorhill** [comment]
You shouldn't remove EasyList, it's a default filter list which is core to accomplish uBO's main job.

**Comment by gorhill** [comment]
What you could try is profile with AdGuard AdBlocker, which is available on Firefox for Android, configure the filter lists in a similar way and see what results you get compared to uBO.

Another thing to try to to disable storage compression in advanced setting. If you try this, you will have to purge all cache and force an update to be sure nothing is compressed anymore (including the selfie). The profiling data you gathered shows that decompression takes some chunk of CPU, but then it's not clear that not compressing will help since this will lead to a larger chunk of data being read from the storage.

**Comment by ghajini** [comment]
@Rob--W, will you see this issue?

**Comment by filips123** [comment]
Sorry for the delay. I've tested startup with uBlock (both with and without compression), AdGuard (with AdGuard Mobile, AdGuard Base, EasyList, EasyPrivacy, and AdGuard Annoyance), and without any blocker addon.

1. No blocker addon

	Profile: https://share.firefox.dev/3EHX30t

2. uBlock Origin (selfie + compression)

	Profile 1: https://share.firefox.dev/3u83lBO
    Profile 2: https://share.firefox.dev/3EO5eYW

	```
	uBlock Origin: 1.45.2
	Firefox Mobile: 109
	filterset (summary):
	  network: 97086
	  cosmetic: 81074
	  scriptlet: 22692
	  html: 883
	listset (total-discarded, last-updated):
	  added:
	    adguard-annoyance: 61306-2284, 3d.1h.57m
	    ublock-annoyances: 4877-7, 1d.21h.23m
	  default:
	    user-filters: 9-0, never
	    ublock-filters: 32379-278, 3d.1h.57m
	    ublock-badware: 4038-1, 3d.1h.57m
	    ublock-privacy: 305-1, 3d.1h.57m
	    ublock-abuse: 77-0, 3d.1h.57m
	    ublock-unbreak: 1921-1, 3d.1h.57m
	    ublock-quick-fixes: 373-0, 21h.27m
	    adguard-mobile: 8248-166, 3d.1h.57m
	    easylist: 64848-17844, 1d.21h.23m
	    easyprivacy: 30881-1725, 3d.1h.57m
	    urlhaus-1: 10720-0, 21h.26m
	    plowe-0: 3667-3, 3d.1h.57m
	    SVN-0: 571-10, 1h.12m
	filterset (user): [array of 9 redacted]
	trustedset:
	  added: [array of 1 redacted]
	modifiedUserSettings:
	  prefetchingDisabled: false
	  suspendUntilListsAreLoaded: false
	  webrtcIPAddressHidden: true
	modifiedHiddenSettings: [none]
	supportStats:
	  allReadyAfter: 1445 ms (selfie)
	  maxAssetCacheWait: 720 ms
	  unsuspendAfter: 379 ms
	```

3. uBlock Origin (no compression)

	Profile 1: https://share.firefox.dev/3EDgzLm
	Profile 2: https://share.firefox.dev/3gLdJMD

	```
	uBlock Origin: 1.45.2
	Firefox Mobile: 109
	filterset (summary):
	  network: 96705
	  cosmetic: 81174
	  scriptlet: 22709
	  html: 883
	listset (total-discarded, last-updated):
	  added:
	    adguard-annoyance: 61364-2179, 4m
	    ublock-annoyances: 4875-167, 4m
	  default:
	    user-filters: 9-0, never
	    ublock-filters: 32406-249, 4m
	    ublock-badware: 4043-1, 4m
	    ublock-privacy: 307-1, 4m
	    ublock-abuse: 77-0, 4m
	    ublock-unbreak: 1928-1, 4m
	    ublock-quick-fixes: 389-28, 4m
	    adguard-mobile: 8264-44, 4m
	    easylist: 64957-17479, 4m
	    easyprivacy: 30904-1215, 4m
	    urlhaus-1: 10206-0, 4m
	    plowe-0: 3677-961, 4m
	    SVN-0: 571-16, 4m
	filterset (user): [array of 9 redacted]
	trustedset:
	  added: [array of 1 redacted]
	modifiedUserSettings:
	  advancedUserEnabled: true
	  prefetchingDisabled: false
	  suspendUntilListsAreLoaded: false
	  webrtcIPAddressHidden: true
	modifiedHiddenSettings:
	  cacheStorageCompression: false
	supportStats:
	  allReadyAfter: 3405 ms
	  maxAssetCacheWait: 2119 ms
	  unsuspendAfter: 568 ms
	```

4. AdGuard

	Profile: https://share.firefox.dev/3F8kq4x

For these examples, I started Twitter PWA, collected performance profiles, and quickly, without closing it, opened the main Firefox app and gathered uBlock Origin troubleshooting info.

There is one other thing I observed. In the setup when compression was enabled, it the loading was very long, as if a selfie wasn't used, despite waiting more than 2min after updating lists and troubleshooting info displaying those times next to lists as around 20min. Here's the profile: 
https://share.firefox.dev/3UcR61m

**Comment by gorhill** [comment]
Looks to me uBO is doing well performance-wise considering you enabled two annoyances on top of default listset, which itself also contains reional SWE list.

|  | No blocker | uBO: selfie+compression | AdGuard |
| --- | --- | --- | --- |
| DOMContentLoaded | 5.511s | 7.630s | 10.810s
|  |  | 6.664s |

Loading of filter lists has already been optimized since long, so there is not much which can be done to improve further. Bottom line, do not enable "lot of filter lists" and expect Firefox for Android (FfA) to perform as if no extension is installed.

Whomever is convinced load performance can be markedly improved without wholly destabilizing uBO is welcome to submit a pull request.
