### ISSUE TITLE
Greek text incompatibility in filter lists

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uBlock-issues#2393]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Although filters that contain Greek text, e.g.:

tools.otenet.gr##div.ui-dialog:has-text(Καταχώρηση τηλεφωνικού αριθμού)
tools.otenet.gr##div.ui-dialog:has-text(Σημαντική Ενημέρωση)

are correctly read and applied when copied and pasted into “My filters” section, Greek characters can’t be recognized, if corresponding filters are loaded from an external custom list txt file: https://bit.ly/3H4ZRYq

![Screenshot at 07-06-01](https://user-images.githubusercontent.com/101707608/205223337-29786cf6-3bb1-440b-aa31-26437dd411ea.png)

### A specific URL where the issue occurs.

https://tools.otenet.gr/

### Steps to Reproduce

1. Add custom filter list from mentioned URL. Filters that contain Greek text can’t be fully recognized and so they don’t work.
2. Add corresponding filters manually to “My filters” section. Now they are read and applied correctly.

### Expected behavior

Filters containing Greek characters are properly recognized and applied regardless their source.

### Actual behavior

Filters with Greek text are correctly recognized only if they’re copied-pasted in “My filters” section.

### Configuration

[το-ublock-αντίγραφο-ασφαλείας-μου_2022-12-02_08.00.37.txt](https://github.com/uBlockOrigin/uBlock-issues/files/10138484/-ublock-.-.-._2022-12-02_08.00.37.txt)

**Comment by gwarser** [comment]
Save your list with utf-8 encoding.

**Comment by DimitrisKalaboukas** [comment]
@gwarser Thank you very much for the immediate response. I did so and it works fine now. Please, delete the list from githubusercontent.com. I’m sorry for the inconvenience.
