### ISSUE TITLE
"Suspend network activity until all filter lists are loaded" resets back to "on", after I turn it off

### ISSUE THREAD

**Issue by sillik7** [uBlockOrigin/uBlock-issues#2394]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'm using Firefox 107.0.1 (64-bit).
I had the following issue for a while: when starting by browser after a computer restart, loading the first page would take sometimes between 5-15 minutes, with a constant HDD activity during the time. 
Took me a while to diagnose that the uBlock setting "Suspend network activity until all filter lists are loaded" was responsible for this. So I disabled it, but then after the next computer restart, it was reset back to ON. After disabling it again it remained OFF for a while (several restarts), but then suddenly reset again to ON. Could be related to updates to the add-on/lists or something...

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

1. Turn "Suspend network activity until all filter lists are loaded" OFF
2. Restart computer (not just the browser). 
3. "Suspend network activity until all filter lists are loaded" is back ON
The time that needs to pass between setting it off and restarting the PC varies (between a few minutes and a few days).
For example, my latest case was:
2022-12-01 8:00 - I set the setting to OFF.
2022-12-01 22:00 - I turn off the computer. Before that it's still OFF.
2022-12-02 8:00 - It's set to ON again.

### Expected behavior

The value of "Suspend network activity until all filter lists are loaded" should not be reset.

### Actual behavior

The value of "Suspend network activity until all filter lists are loaded" is being randomly reset back to ON.

### uBO version

1.45.2

### Browser name and version

Firefox 107.0.1 (64-bit)

### Operating System and version

Windows 8.1

**Comment by gothic-bum** [comment]
It would be helpful if you post the troubleshooting information from:  
[Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> Support -> Troubleshooting Information

**Comment by sillik7** [comment]
`uBlock Origin: 1.45.2
Firefox: 107
filterset (summary): 
  network: 97000
  cosmetic: 38964
  scriptlet: 16750
  html: 863
listset (total-discarded, last-updated): 
  added: 
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-online.txt: 8425-0, 1h.6m
    https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.5m
    https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt: 0-0, 1h.4m
    https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-list-ubo.txt: 0-0, never
    BGR-0: 1091-11, 1d.37m
  default: 
    user-filters: 12-3, never
    ublock-filters: 32312-40, 1d.47m
    ublock-badware: 4045-2, 1d.46m
    ublock-privacy: 307-0, 1d.45m
    ublock-abuse: 77-0, 1d.44m
    ublock-unbreak: 1922-1, 1d.43m
    ublock-quick-fixes: 431-31, 1d.42m
    easylist: 65025-628, 1d.41m
    easyprivacy: 30908-1177, 1d.40m
    urlhaus-1: 10022-2084, 1d.39m
    plowe-0: 3679-537, 1d.38m
filterset (user): [array of 12 redacted]
trustedset: 
  added: [array of 15 redacted]
  removed: 
    about-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 435 ms (selfie)
  maxAssetCacheWait: 712 ms
  unsuspendAfter: 328 ms
`

**Comment by krystian3w** [comment]
Works fine in latest dev release.

**Comment by gwarser** [comment]
> loading the first page would take sometimes between 5-15 minutes, with a constant HDD activity during the time.
Took me a while to diagnose that the uBlock setting "Suspend network activity until all filter lists are loaded" was responsible for this. So I disabled it, but then after the next computer restart, it was reset back to ON.

It's the other way around. It's the Firefox storage being erroneous because of being for some reason slow (too large / littered / not cleaned up from unneeded files / fragmented / not managed properly by Firefox) or even corrupted, that causes slow startup and problems with uBO settings. It's a coincidence that uBO requires all settings to be read from storage to start working and allow pages to load. Other add-ons or even webpages that extensively rely on storage will also malfunction because of this.

Clean your Firefox site data, check disk for errors.

**Comment by sillik7** [comment]
> It's the other way around. It's the Firefox storage being erroneous because of being for some reason slow (too large / littered / not cleaned up from unneeded files / fragmented / not managed properly by Firefox) or even corrupted, that causes slow startup and problems with uBO settings. It's a coincidence that uBO requires all settings to be read from storage to start working and allow pages to load. Other add-ons or even webpages that extensively rely on storage will also malfunction because of this.
> 
> Clean your Firefox site data, check disk for errors.

This is probably it then. Sorry for putting the blame on uBlock so quickly.
I'm pretty sure cleaning up the site data didn't fix the slowdown problem when I tried it months ago, but I'll try again and see if it takes care of both problems.
Thanks!
