### ISSUE TITLE
Location Services blocking

### ISSUE THREAD

**Issue by SoniEx2** [uBlockOrigin/uBlock-issues#2396]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock Origin should have direct support for blocking (including exceptions) location services instead of requiring workarounds with blocking specific scripts and hoping for the best.

### A specific URL where the issue occurs.

maps.google.com

### Steps to Reproduce

1. Visit maps.google.com
2. Get redirected to google.com/maps

### Expected behavior

Should be able to just write a filter that blocks location services unless it's a subpage of google.com/maps

### Actual behavior

Unable to properly block location services without somehow enumerating all javascript used by other pages on the website, which is effectively impossible.

### uBO version

1.45.2

### Browser name and version

Firefox 107.0

### Operating System and version

Arch Linux x86_64

**Comment by gorhill** [comment]
What's "location service"?

**Comment by gothic-bum** [comment]
You can control location services in your browser. Since you indicated you are using Firefox, see:  
https://support.mozilla.org/en-US/kb/does-firefox-share-my-location-websites

Note that sites can perform a reverse DNS lookup of your IP address to obtain a rough estimate of your location.

**Comment by gwarser** [comment]
Just turn it off in your browser by default, and then allow on pages you want it to work.

![image](https://user-images.githubusercontent.com/886325/205476432-08ae78e0-8985-4d32-837f-d4f65bdf845d.png)

**Comment by krystian3w** [comment]
Possible write filter to disable most of notifications:

```adb
maps.google.com##+js(set, navigator.geolocation.getCurrentPosition, noopFunc)
```

For me only `doz.pl` (long JS to check) use something else to enforce asking on specific medicamente available
in local pharmacy.

`https://www.doz.pl/apteka/p127262-Mysimba_8_mg90_mg_tabletki_o_przedluzonym_uwalnianiu_112_szt.`

https://user-images.githubusercontent.com/35370833/205599017-9c520b20-1183-4c79-85dc-7fced691d8e0.png
