### ISSUE TITLE
chrome: remove old versions after updating

### ISSUE THREAD

**Issue by warichnict** [uBlockOrigin/uBlock-issues#2399]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

most of the checks do not apply for my case.

i was freeing up some space on my disk when i found out that 

%LOCALAPPDATA%/Chromium/User Data/Default/Extensions
more then 800 M (compressed to 460M) of space is used by old versions

![image](https://user-images.githubusercontent.com/57467778/206136967-2ffe4504-c950-4969-894e-72e974a1ef36.png)

please delete old versions after updatating by yourself

### A specific URL where the issue occurs.

not aplayable 

### Steps to Reproduce

check %LOCALAPPDATA%\Chromium\User Data\Default\Extensions after it updated itself

### Expected behavior

one or maybe two versions

### Actual behavior

a very lot of shit

### uBO version

1.43.0

### Browser name and version

chromium

### Operating System and version

win server 2012R2

**Comment by nanderer** [comment]
so is there any workaround, some chrome/chromium setting or a script that i can run regually or as a planned task?
