### ISSUE TITLE
Regression with -abp- and :has rules

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uBlock-issues#2400]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBO doesn't support certain characters, like apostrophes (**'**) in `:-abp-` and `:has` rules anymore.
This regression happened somewhere between **v1.44.4** and **v1.45.5**.

### A specific URL where the issue occurs.

https://anyataylorjoy.org/

### Steps to Reproduce

Add the following rule, to block the twitter widget in the site's sidebar:
`anyataylorjoy.org###sidebar > div.side-content:has-text(Adoring Anya's twitter)`
(uBO flags this as an invalid rule)

### Expected behavior

The widget should be blocked (like with uBO v1.44.4).

### Actual behavior

The widget isn't blocked!

### uBO version

v1.45.3b11

### Browser name and version

LibreWolf v107.0.1-1

### Operating System and version

Windows 10 Pro 21H2

**Comment by THEtomaso** [comment]
No.
uBO doesn't flag the rule as invalid anymore, but it doesn't work.

**Comment by THEtomaso** [comment]
This works (removing the apostrophe):
`anyataylorjoy.org###sidebar > div.side-content:has-text(s twitter)`

**Comment by gorhill** [comment]
You need to use quotes when an argument is causing issue in a procedural cosmetic operators. The way quoting is interpreted now is closer to how AdGuard documents using quotes, except that for uBO:

- Quotes are still optional if the argument does trip the parser
- One can use either `"` or `'`
- When using quotes, instances of the same quote inside the argument must be escaped, i.e. `'this is a single quote: \''`, or `"this is a double quote: \""`, and instances of `\` must be escaped (as per AdGuard's documentation.

A change from the commit message in the dev build is that escaping without quoting no longer does anything, so `##sidebar > div.side-content:has-text(Adoring Anya\'s twitter)` does not work in dev build.

**Comment by DandelionSprout** [comment]
I've confirmed on my end that `anyataylorjoy.org###sidebar > div.side-content:has-text(/Adoring Anya\'s twitter/)` would work, at least; even if it requires turning the entry into RegEx.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/discussions/2328 - maybe help after mergerd in CSSTree, but can break HTML Filtering.

**Comment by krystian3w** [comment]
@gorhill / @gwarser I have strange regression with some CSS in uBO 1.45.3b14+:

`#3388cc` `#774444`

```adb
github.com,miroslawzelent.pl##table td:has-text(4) ~ td:style(border-top: 4px solid #38c !important;)
github.com,miroslawzelent.pl##table td:has-text(7) ~ td:style(border-top: 4px solid #744 !important;)
````

demo page can be: https://miroslawzelent.pl/kurs-html/tabele-tr-td-th-table/ and at Github:

<table>
   <tr>
      <td>1</td> <td>2</td> <td>3</td>
   </tr>
   <tr>
      <td>4</td> <td>5</td> <td>6</td>
   </tr>
   <tr>
      <td>7</td> <td>8</td> <td>9</td>
   </tr>
</table>

cell with 5, 6, 8 and 9 are hidden instead restyled.

**Comment by gwarser** [comment]
It's fine in new profile. ???

**Comment by krystian3w** [comment]
But fail in Edge/Chrome 108 and Firefox 108.

Also I loaded this from localhost instead my filters tab/pane.

If both profiles are broken then maybe HDD dying...

**Comment by gwarser** [comment]
Caused by "Polskie Filtry Elementów Irytujących" and "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda".

**Comment by krystian3w** [comment]
I fixed once issue: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues/2974

I don't think so same time to found unknown glitch in blocker99/MajkiIT projects if possible catch glitch in devtools console only (not in logger on mv3 filter converter to rules).

**Comment by gorhill** [comment]
I am getting lost in the comments. So is there a regression?

**Comment by gwarser** [comment]
On `miroslawzelent.pl` adding `pl##li > div[id*="taboola"]:upward(li)` to My filters causes the issue. Here, on GitHub it's something in uBlock filters (bisecting now).

**Comment by gwarser** [comment]
Broken by https://github.com/gorhill/uBlock/commit/992255e9937f81b5dd58524caa2ceeaeb29efb14

**Comment by gorhill** [comment]
Ok, it's a silly mistake -- kind of discouraging that I would introduce such a regression.
