### ISSUE TITLE
Cause memory leak on Firefox 107

### ISSUE THREAD

**Issue by psydvl** [uBlockOrigin/uBlock-issues#2401]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlockOrigin cause memory leak on Firefox

Related data:

Firefox Profiler
https://share.firefox.dev/3W1GKDj

Shell comands output
```shell
$ free # about 8gb ram + 8gb swap
               total        used        free      shared  buff/cache   available
Mem:         7861296     4533736      386624      856640     4105312     3327560
Swap:        8388604      461056     7927548
$  # before 610 MB or 2,4 GB virtual
$ PD=10931 && ps -O sz,vsz -wwp $PD && echo && ps -Fwwp $PD
  PID    SZ    VSZ S TTY          TIME COMMAND
10931 609796 2439184 S pts/3  00:00:00 /usr/lib64/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 31103 -prefMapSize 226290 -jsInitLen 246704 -parentBuildID 20221128144904 -appDir /usr/lib64/firefox/browser {ad28b4ac-3710-4f6f-8cc1-2d0ac79aafbf} 10768 true tab

UID        PID  PPID  C    SZ   RSS PSR STIME TTY          TIME CMD
nixi     10931 10768  0 609796 122804 2 04:35 pts/3    00:00:00 /usr/lib64/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 31103 -prefMapSize 226290 -jsInitLen 246704 -parentBuildID 20221128144904 -appDir /usr/lib64/firefox/browser {ad28b4ac-3710-4f6f-8cc1-2d0ac79aafbf} 10768 true tab

$  # after: 4,8GB or 19GB virtual
$ PD=10931 && ps -O sz,vsz -wwp $PD && echo && ps -Fwwp $PD
  PID    SZ    VSZ S TTY          TIME COMMAND
10931 4868825 19475300 S pts/3 00:00:03 /usr/lib64/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 31103 -prefMapSize 226290 -jsInitLen 246704 -parentBuildID 20221128144904 -appDir /usr/lib64/firefox/browser {ad28b4ac-3710-4f6f-8cc1-2d0ac79aafbf} 10768 true tab

UID        PID  PPID  C    SZ   RSS PSR STIME TTY          TIME CMD
nixi     10931 10768  0 4868825 171276 3 04:35 pts/3   00:00:03 /usr/lib64/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 31103 -prefMapSize 226290 -jsInitLen 246704 -parentBuildID 20221128144904 -appDir /usr/lib64/firefox/browser {ad28b4ac-3710-4f6f-8cc1-2d0ac79aafbf} 10768 true tab
```

### A specific URL where the issue occurs.

http://x.com

### Steps to Reproduce

1. Open fresh Firefox profile
2. Install uBlockOrigin
3. Watch memory usage

### Expected behavior

About few more MB requested

### Actual behavior

15(?) GB memory requested, more than I even have

### uBO version

1.45.2

### Browser name and version

Firefox 107.0.1 (64-bit)

### Operating System and version

openSUSE Tumbleweed 20221208-0

**Comment by psydvl** [comment]
Memory reports (from `about:memory`)
Use `verbose` check with `Load and diff` button
[memory-report_before.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/10198998/memory-report_before.json.gz)
[memory-report_after.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/10198999/memory-report_after.json.gz)

**Comment by gorhill** [comment]
I don't see any undue memory usage in your memory-report_after, and certainly not "15(?) GB requested".

Maybe your are confusing memory usage with memory addressing usage, which is virtual memory, not physical memory. Using WASM causes higher virtual memory usage, which is not memory leak.

**Comment by krystian3w** [comment]
In addition, tomorrow is expected to be the release of stable version 108, maybe by Friday also in the repository of openSUSE.
