### ISSUE TITLE
Font Awesome gets around "no web fonts" setting

### ISSUE THREAD

**Issue by TheRealCuran** [uBlockOrigin/uBlock-issues#2405]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When opening a website like [ESAs website on its meteosat mission](https://www.esa.int/Applications/Observing_the_Earth/Meteorological_missions/meteosat_third_generation), I noticed, that they include eg. https://ka-p.fontawesome.com/releases/v5.15.4/js/pro.min.js (token stripped) and that means getting around the general "no web fonts setting" in uBlock Origin. One look at the network tab of Firefox' web developer tools shows:
![image](https://user-images.githubusercontent.com/3419202/207458419-08f3c818-73c1-433e-8b88-bffc25e70d4e.png)

I am not entirely sure if this is uBlock Origin or a filter list issue, but I do think it is more of a uBlock Origin issue.

### A specific URL where the issue occurs.

https://www.esa.int/Applications/Observing_the_Earth/Meteorological_missions/meteosat_third_generation

### Steps to Reproduce

1. Open https://www.esa.int/Applications/Observing_the_Earth/Meteorological_missions/meteosat_third_generation with JS enabled in uBlock Origin, but fonts blocked
2. Observe the requests to fontawesome.com

### Expected behavior

If fonts are disabled (globally or for the web site), JS should not be able to get around loading those.

### Actual behavior

Font Awesome's JS circumvents the font blocking setting in uBlock Origin.

### uBO version

1.45.2

### Browser name and version

Firefox 107.0.1

### Operating System and version

Debian GNU/Linux (testing/Sid)

**Comment by gorhill** [comment]
The font resources are properly blocked. Your screenshot shows image resources, not fonts.
