### ISSUE TITLE
 Unknown error causing blocking of all third-party resources

### ISSUE THREAD

**Issue by hacamer** [uBlockOrigin/uBlock-issues#2406]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When I subscribe to `https://adrules.top/adblock.txt`
Many sites do not load properly
The blocking log shows the blocking rule as `*$3p`
But I checked the rules and found that there is no such rule

Others are experiencing the same problem https://github.com/Cats-Team/AdRules/issues/100 https://github.com/Cats-Team/AdRules/issues/102

### A specific URL where the issue occurs.

https://github.com/

### Steps to Reproduce

1. Subscribe to https://adrules.top/adblock.txt
2. open https://github.com/
3. Resources from third parties are blocked

![图片](https://user-images.githubusercontent.com/73057402/207468449-9493b968-94c1-4e0d-ae3e-dca679142155.png)

### Expected behavior

Page loads normally

### Actual behavior

Resources from third parties are blocked

### Configuration

```
uBlock Origin: 1.44.4
Chromium: 108
filterset (summary): 
  network: 107591
  cosmetic: 53262
  scriptlet: 55
  html: 0
listset (total-discarded, last updated): 
  removed: 
    CHN-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  added: 
    https://adrules.top/adblock.txt: 161663-587, 34m
  default: 
    user-filters: 0-0, never
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5579 ms (selfie)
  maxAssetCacheWait: 3456 ms

```

**Comment by gorhill** [comment]
> When I subscribe to `https://adrules.top/adblock.txt`

uBO is not responsible for bad list, bring the issue to the list maintainer(s).

**Comment by hacamer** [comment]
thank you for your reply
I will detect and delete bad rules
By the way, does uBO ignore unsupported rules?

**Comment by hacamer** [comment]
> I would advise uBO users against using your list(s)  

My list is mainly for AdGuard users

**Comment by krystian3w** [comment]
So include:

```adb
!#if !env_ublock`
!... whole adguard rules
!#endif

**Comment by hacamer** [comment]
> So include:
> 
> ```
> !#if !ext_ublock
> !... whole adguard rules
> !#endif
> ```

![](https://user-images.githubusercontent.com/73057402/207805026-e236d520-a8b5-49ea-ad55-0f1743bae5b5.png)

It doesn't look ignored, am I mistaken?

**Comment by krystian3w** [comment]
Is correct, `if` don't disable global hightlighting or similar to comment.

**Comment by krystian3w** [comment]
Also AdGuard will disable pure JS filters in favor trusted scritplets arsenal.

**Comment by hacamer** [comment]
> @hacamer Adding javascript as a filter is not supported currently. Write a scriptlet.

I just test if this rule is ignored

**Comment by hacamer** [comment]
> Also AdGuard will disable pure JS filters in favor trusted scritplets arsenal.

Do you mean that AdGuard needs to enable trusted filters?

**Comment by krystian3w** [comment]
Using trusted scriptlets, requires marking the subscribed file as trusted.

> https://github.com/AdguardTeam/Scriptlets#trusted-scriptlets-restriction

Also now is not huge:

https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#trusted-scriptlets

So crazy JS filters may need to create requests for new AdGuard scripts in a few years.

I don't know anything that AdGuard has already implemented something like uBo `userResourcesLocation` - in most of his apps possible subscribe `.user.js` scripts.
