### ISSUE TITLE
Cookie spy detected by CCleaner

### ISSUE THREAD

**Issue by Luc-69** [uBlockOrigin/uBlock-issues#241]
UBlock Origin installs a cookie spy impossible to erase without using CCleaner, in the sailor and made so that we cannot use the private navigation to be able to update filters, filters are put back to zero in private navigation. Gorhill and his team are unmasked.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/227
