### ISSUE TITLE
Support AdGuard set-constant value aliases 'emptyArr' and 'emptyObj'

### ISSUE THREAD

**Issue by CuervoCarlos** [uBlockOrigin/uBlock-issues#2411]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

AdGuard scriptlets implement different literal value using 'emptyArr' and 'emptyObj' instead of  '[]' and '{}' in uBO. Please consider implementing those aliases since uBO is the only out-of-the-box privacy filter featuring scriptlets (and the other being EasyPrivacy which does not manipulate Javascript). 

References:
[AdG set-constant](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-constant)
[uBO set-constant](https://github.com/gorhill/uBlock/wiki/Resources-Library#set-constantjs-)

### A specific URL where the issue occurs.

mirrormedia.mg

### Steps to Reproduce

Rule `*##+js(set, window.test, emptyArr)` is not resolved. 
Rule `*##+js(set, window.test, emptyObj)` is not resolved. 

### Expected behavior

Example AdG grammar: 
`mirrormedia.mg##+js(set-constant, dataLayer, emptyArr)`

should work the same as uBO grammar:
`mirrormedia.mg##+js(set-constant, dataLayer, [])`

### Actual behavior

Rule `mirrormedia.mg##+js(set-constant, dataLayer, emptyArr)` is not resolved; nothing happens in the logger. 

### uBO version

1.45.2

### Browser name and version

Firefox 102.0

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
The filter in original _"AdGuard Tracking Protection"_ list is:

    mirrormedia.mg#%#//scriptlet("set-constant", "dataLayer", "emptyArr")

This means it's improperly converted to uBO's syntax. The conversion should be fixed [in AdGuard's converter](https://github.com/AdguardTeam/Scriptlets/blob/v1.7.13/src/helpers/converter.js#L250), it's already done for empty string ([ref](https://github.com/AdguardTeam/Scriptlets/blob/v1.7.13/src/helpers/converter.js#L250)).

**Comment by superlex** [comment]
@gorhill 
I assume the same goes for `set-local-storage-item`.

This is the result of
```
example.org#%#//scriptlet('set-local-storage-item', 'ag_obj', 'emptyObj')
example.org#%#//scriptlet('set-local-storage-item', 'ag_arr', 'emptyArr')
example.org#%#//scriptlet('set-local-storage-item', 'ag_str', '')
example.org##+js(set-local-storage-item, u_obj, {})
example.org##+js(set-local-storage-item, u_arr, [])
example.org##+js(set-local-storage-item, u_str, '')
```
<img width="866" alt="dd" src="https://github.com/uBlockOrigin/uBlock-issues/assets/1375223/ee6d9dc4-35d8-4e5c-a7df-ad7efca0bf1b">

PS:
Let me know if you prefer I open a new issue and/or you need additional information.
