### ISSUE TITLE
Firefox crashes when only the sub domain is enabled instead of the main domain

### ISSUE THREAD

**Issue by kimariterikishi** [uBlockOrigin/uBlock-issues#2413]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The browser crashes if I enable the subdomain instead of the main domain.

### A specific URL where the issue occurs.

https://www.tiktok.com/@karacsonygergely_/video/7177663711862148358?is_from_webapp=v1&item_id=7177663711862148358

### Steps to Reproduce

I use the advanced settings and only the default JavaScript blocking.

In addition to turning on JavaScript blocking, I also turned on Advanced settings, but I didn't edit anything there! Here's an older screenshot of this (turned on):
https://postimg.cc/jwDNBrgm

When accessing a website, I enable as few domains as possible..., after unblocking the JavaScript (</> element). I do not apply any custom rules.

Nowadays I no longer allow the main domain, but the sub domain. An example of this is in the screenshot:
https://postimg.cc/YjkCdYfG

So far I have not had any problems using the Firefox browser, however I strongly suspect that the new uBlock Origin version has a factor that could cause the browser to crash. Of course, I can't rule out a bug in Firefox or the system (Debian 11) or the graphics driver (Intel)..., these are under testing.

I found a URL where Firefox crashes almost immediately after enabling one or two sub domains. This is it:
https://www.tiktok.com/@karacsonygergely_/video/7177663711862148358?is_from_webapp=v1&item_id=7177663711862148358

Honestly, I was driven by habit regarding JS permissions, so for example on the YouTube page I noted that youtube.com and google.com should be enabled..., then I also noticed that google.com is sufficient nowadays, and that's how I finally came to the realization that it's sufficient to enable the sub domain (to play the YT video).
____

Update (pictures and +)

-- uBlock Origin
https://i.postimg.cc/rwxv87Tk/u-Block-Origin-be-ll-t-sok-2022-01.png
https://i.postimg.cc/d3hxgx6g/u-Block-Origin-be-ll-t-sok-2022-02.png
https://i.postimg.cc/7L4jbXPT/u-Block-Origin-be-ll-t-sok-2022-03.png
https://i.postimg.cc/KzqWq2Pn/u-Block-Origin-be-ll-t-sok-2022-04.png
https://i.postimg.cc/pdB4j8yc/u-Block-Origin-be-ll-t-sok-2022-05.png
https://i.postimg.cc/L5GbS305/u-Block-Origin-be-ll-t-sok-2022-06.png
https://i.postimg.cc/ZRKgxRdb/u-Block-Origin-be-ll-t-sok-2022-07.png

Addons
https://i.postimg.cc/wxrPD9Tz/Firefox-Kieg-sz-t-k.png

Firefox
https://i.postimg.cc/dtTfBgLy/Firefox-Fokozott-k-vet-s-elleni-v-delem.png

The latter can cause problems. I will test by turning this off.

```
uBlock Origin: 1.45.2
Firefox: 102
filterset (summary): 
  network: 87621
  cosmetic: 40703
  scriptlet: 16736
  html: 881
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32289-60, 2d.19h.58m
    ublock-badware: 4191-0, 2d.19h.58m
    ublock-privacy: 301-0, 2d.19h.58m
    ublock-abuse: 77-0, 2d.19h.58m
    ublock-unbreak: 1928-2, 2d.19h.58m
    ublock-quick-fixes: 488-0, 14h.56m
    easylist: 63024-608, 2d.19h.58m
    easyprivacy: 30983-1748, 2d.19h.58m
    urlhaus-1: 9370-0, 14h.55m
    plowe-0: 3678-3, 2d.19h.58m
    HUN-0: 2202-5, 14h.54m
filterset (user): [empty]
switchRuleset: 
  added: [array of 5 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1095 ms (selfie)
  maxAssetCacheWait: 508 ms
```

### Expected behavior

I would like the browser not to crash.

### Actual behavior

Now it crashes quite often (see note on this).

### uBO version

1.45.2

### Browser name and version

102.6.0 ESR (64 bit), Firefox portable (firefox-108.0.1.tar.bz2)

### Operating System and version

Debian 11 Bullseye

**Comment by gwarser** [comment]
Post specific verions of Firefox and uBO you are using. Post the actual steps to reproduce, in points, what you do step by step. Post "Troubleshooting information" from uBO "Support" tab if you see it in your uBO version.

**Comment by kimariterikishi** [comment]
@gwarser I just described what I did step by step.
I have extended my post with the information you requested: pictures of the settings, and the requested Troubleshooting information.

**Comment by gorhill** [comment]
Report browser crashes to browser devs, this is an issue in the browser, beyond uBO.

**Comment by kimariterikishi** [comment]
> Also, be sure your browser crashes are submitted to Mozilla, see about:crashes.

@gorhill I will try.

**Comment by gorhill** [comment]
> I found a URL where Firefox crashes almost immediately after enabling one or two sub domains.

Did you try without uBO?

**Comment by kimariterikishi** [comment]
> Did you try without uBO?

Yes, a moment (UBO is only off) but no crash. Hm.

**Comment by gorhill** [comment]
Well as said crashes are issues beyond uBO, that's not supposed to happen and we can't reproduce anyway, so just send crash reports to Mozilla, and maybe copy instances of crash IDs here so we can look at them [from there](https://crash-stats.mozilla.org/).

**Comment by kimariterikishi** [comment]
> that's not supposed to happen and we can't reproduce anyway, so just send crash reports to Mozilla, and maybe copy instances of crash IDs here so we can look at them [from there](https://crash-stats.mozilla.org/).

I will try. But I disable the „Advanced settings” in uBlock Origin settings no problem..., although this way I cannot control the restrictions in the way I want.

If I turn on Advanced settings, the browser crashes. I'm looking around here, but I don't know which setting is causing the crash.

```
allowGenericProceduralFilters false
            assetFetchTimeout 30
    autoCommentFilterTemplate {{date}} {{origin}}
   autoUpdateAssetFetchPeriod 60
   autoUpdateDelayAfterLaunch 105
             autoUpdatePeriod 4
          benchmarkDatasetURL unset
             blockingProfiles 11111/#F00 11010/#C0F 11001/#00F 00001
              cacheStorageAPI unset
      cacheStorageCompression true
cacheControlForFirefox1376932 no-cache, no-store, must-revalidate
      cloudStorageCompression true
              cnameIgnoreList unset
          cnameIgnore1stParty true
        cnameIgnoreExceptions true
      cnameIgnoreRootDocument true
                  cnameMaxTTL 120
           cnameReplayFullURL false
                 cnameUncloak undefined
          cnameUncloakProxied false
              consoleLogLevel unset
              debugScriptlets false
       debugScriptletInjector false
           disableWebAssembly false
   extensionUpdateForceReload false
             filterAuthorMode false
              filterOnHeaders false
              loggerPopupType popup
 manualUpdateAssetFetchPeriod 500
           modifyWebextFlavor unset
                popupFontSize unset
   popupPanelDisabledSections 0
     popupPanelLockedSections 0
         popupPanelHeightMode 0
  requestJournalProcessPeriod 1000
                  selfieAfter 2
 strictBlockingBypassDuration 120
                uiPopupConfig unset
                     uiStyles unset
updateAssetBypassBrowserCache false
        userResourcesLocation unset
```

**Comment by gorhill** [comment]
There is no point to keep posting details about uBO, what matters is browser crash reports.

**Comment by kimariterikishi** [comment]
> what matters is browser crash reports.

Obviously it is. But in my opinion, turning off or on a setting in the add-on is also related to the crash. Best regards.
