### ISSUE TITLE
Logger doesn't always open first time.

### ISSUE THREAD

**Issue by TesterMan247** [uBlockOrigin/uBlock-issues#2415]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When I first start up the browser, I quickly open up the uBlock Origin Logger. As you can see from my video of the issue, the first time I clock on the logger, it does not open up. I have to go in again and click on the logger for it to then open up properly.
I am using Windows 11 Pro with Google Chrome 108.0.5359.125 (x64).

Please find a zipped file (Issue.zip) which contains a video of the issue.

[Issue.zip](https://github.com/uBlockOrigin/uBlock-issues/files/10265593/Issue.zip)

https://user-images.githubusercontent.com/886325/208598756-1b00f049-341f-473d-8104-99fba9e916be.mp4

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Start up the browser.
2. Now quickly open the uBlock Origin Logger.
3. It doesn't open.
4. Repeat step 2 and the Logger will now open properly.

### Expected behavior

The logger should open the first time.

### Actual behavior

The logger does not open the first time. I have to repeat the steps for the logger to then open correctly.

### Configuration

```
uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 154726
  cosmetic: 215202
  scriptlet: 37770
  html: 0
listset (total-discarded, last-updated): 
  added: 
    adguard-annoyance: 62319-96, 8h.3m
    adguard-generic: 66487-513, 8h.3m
    adguard-social: 19501-823, 8h.3m
    adguard-spyware: 35779-4441, 8h.3m
    block-lan: 44-0, 8h.3m
    curben-phishing: 22340-0, 8h.3m
    curben-pup: 187-0, 8h.3m
    fanboy-annoyance: 83946-5117, 8h.3m
    fanboy-social: 23473-23473, 8h.3m
    fanboy-thirdparty_social: 68-21, 8h.3m
    ublock-annoyances: 4797-235, 8h.3m
  default: 
    user-filters: 2-0, never
    easylist: 61548-933, 8h.3m
    easyprivacy: 31006-12401, 8h.3m
    plowe-0: 3671-986, 8h.3m
    ublock-abuse: 77-0, 8h.3m
    ublock-badware: 4207-267, 8h.3m
    ublock-filters: 31534-3738, 8h.3m
    ublock-privacy: 254-51, 8h.3m
    ublock-quick-fixes: 476-48, 8h.3m
    ublock-unbreak: 1918-106, 8h.3m
    urlhaus-1: 7644-1, 8h.3m
filterset (user): [array of 2 redacted]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 438 ms (selfie)
  maxAssetCacheWait: 337 ms
```

**Comment by gwarser** [comment]
On video, it's at least 2 seconds, `allReadyAfter` is 438 ms.

I cannot reproduce.

**Comment by TesterMan247** [comment]
The issue just happened again.
it has been happening 100% of the time for me and continues to happen.
I even made a video and it shows the issue, how can you guys not see the issue?

The issue happens when i click on the "Open the Logger" button to open the logger. The extension popup always works when I click on uBlock Origin button. The issue just happens when I click on the "Open the Logger" button.

All this is shown in the video.
Watch the video again and look at what I do.
I click on the "Open the Logger" button and nothing happens the first time.
I then do the same again, and then you can see the logger window open.

Can you guys see the issue now?

**Comment by gorhill** [comment]
`allReadyAfter` is mostly for filters/rules stuff, [tab structures initialization](https://github.com/gorhill/uBlock/blob/1.45.2/src/js/start.js#L93-L134) is not included in this figure. I suspect it might just be because uBO hasn't completed it's scanning of currently opened tabs (uBO is competing with other extensions for CPU usage since they are all in the same process).

Can you try to reproduce with other extensions disabled?

Maybe we could have an advanced setting to open the logger on startup as soon as possible, this can be useful.

**Comment by gwarser** [comment]
> Does it include the extension popup menu ? I don't think so.

But it's relatively low compared to interactions in video, where browser runs for at least 2s.

I just tried in VM on HDD, `allReadyAfter` is `5125 ms (selfie)` and I cannot reproduce. There was a such lag I must wait for uBO popup to open and yet logger launched on first try nearly immediately.

**Comment by gorhill** [comment]
I can't reproduce either, I was just guessing.

@TesterMan247 Unless we can reproduce on our side, this issue will go nowhere since we can't investigate issues which we can't reproduce.

**Comment by TesterMan247** [comment]
> `allReadyAfter` is mostly for filters/rules stuff, [tab structures initialization](https://github.com/gorhill/uBlock/blob/1.45.2/src/js/start.js#L93-L134) is not included in this figure. I suspect it might just be because uBO hasn't completed it's scanning of currently opened tabs (uBO is competing with other extensions in the same event loop since they are all in the same process).
> 
> Can you try to reproduce with other extensions disabled?
> 
> Maybe we could have an advanced setting to open the logger on startup as soon as possible, this can be useful.

That would be a great option to have.
Also, please make the defaults sticky so that if I have set it to a particular view, when it opens automatically next time during start, it keeps those options and I don't have to set those options each and every time the logger starts automatically.
For example, I like to have these options set: 
![Options](https://user-images.githubusercontent.com/20948631/208769655-61ee1a5d-ea27-4e60-9a64-7d2fee284b45.png)
