### ISSUE TITLE
Safari auto disables Ublock Origin with error: "This extension will slow down your web browsing"

### ISSUE THREAD

**Issue by ReagentX** [uBlockOrigin/uBlock-issues#242]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

![](https://i.imgur.com/NeSOsC1.png)

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Use uBlock Origin in Safari

### Expected behavior:

No error occurs

### Actual behavior:

Safari says "This extension will slow down your web browsing" and disables the extension

### Your environment

* uBlock Origin version: 1.16.0
* Browser Name and version: Safari 12.0 (13606.2.11)
* Operating System and version: High Sierra 10.13.6 (17G65)

**Comment by ZaphodBeebblebrox** [comment]
Wrong place, uBlock-Safari is at https://github.com/el1t/uBlock-Safari

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock#safari-macos
