### ISSUE TITLE
out of date cdn

### ISSUE THREAD

**Issue by iibett** [uBlockOrigin/uBlock-issues#2420]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

One of the easylist Lithuania cdn's is out of date for some reason.
Specifically this one `https://cdn.statically.io/gl/DandelionSprout/easylist_lithuania/raw/master/easylistlithuania.txt` 
It is from September, could you replace the link with this newer version.
`https://cdn.statically.io/gh/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt`

### A specific URL where the issue occurs.

https://cdn.statically.io/gl/DandelionSprout/easylist_lithuania/raw/master/easylistlithuania.txt

### Steps to Reproduce

ubo filters sometimes updates to an older version.

### Expected behavior

Filters should update to the version from december

### Actual behavior

but sometimes the update to the September version

### uBO version

1.45.3rc6

### Browser name and version

Firefox

### Operating System and version

Windows

**Comment by DandelionSprout** [comment]
GitLab did not at any point notify me that they claimed my EasyList Lithuania repo there was affected by vague changes in their paid plans that affected the ability to mirror from GitHub to GitLab.

I think I may or may not be able to re-sync that mirror tonight.

**Comment by gorhill** [comment]
> [my EasyList Lithuania mirror there](https://gitlab.com/DandelionSprout/easylist_lithuania)

I get a 404 at that URL.

**Comment by DandelionSprout** [comment]
That was because I deleted that mirror again, after I realised that GitLab for some reason instantly turned off mirroring even when I used GitLab's "New project → CI/CD mirroring" functionality.

**Comment by krystian3w** [comment]
Maybe you have run out of gitlab virtual machines (400 minutes per month only for free).

https://about.gitlab.com/solutions/open-source/ - You might consider joining this project as you have actually exceeded the December limits.

**Comment by DandelionSprout** [comment]
Pretty good point. I'll see if I have spare energy to attempt to join that project this week.
