### ISSUE TITLE
Hiding rules stop working

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2421]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hiding rules stop working. I'm not sure if the extension is the problem. Perhaps a particular rule is to blame for everything. But since this rule is not listed as "invalid" in the logger when updating filters, I'm posting it here.

### A specific URL where the issue occurs.

https://www.comss.ru/disqus/page.php?id=2949

### Steps to Reproduce

1. Install [Firefox ESR 78.15.0](https://dl.comss.org/download/FirefoxPortableLegacy78_78.15.0_Russian.paf.exe) and uBlock Origin 1.45.2
2. Activate the filter RU AdList
3. Open: https://www.comss.ru/disqus/page.php?id=2949
4. Refresh the page several times

### Expected behavior

Hiding rules work stably

### Actual behavior

Hiding rules stop working, example: `comss.ru##.container-fluid > div[class="container uphead"]`

If you add `comss.ru#@#.adBanner:not(:empty):not(.testAd):not(#wrapfabtest > .adBanner)` to "My filters", then everything will work correctly.

In earlier versions uBlock Origin, when filters were updated, this rule `##.adBanner:not(:empty):not(.testAd):not(#wrapfabtest > .adBanner)` (uBlock filters) was marked as "invalid".

P.S. I used this particular version of the browser, since the problem repeats in it most stably.

### uBO version

uBlock Origin: 1.45.2

### Browser name and version

Firefox ESR 78.15.0

### Operating System and version

Windows 7

**Comment by gorhill** [comment]
> Firefox ESR 78.15.0

That's why, FF78 does not support `:not()` with complex selector such as `#wrapfabtest > .adBanner`.

I am going to have to raise the minimum browser versions.

**Comment by dimisa-RUAdList** [comment]
uBlock Origin 1.44.4 does not have this problem.

**Comment by u-RraaLL** [comment]
> uBlock Origin 1.44.4 does not have this problem.

`:not()` was probably used there procedurally, not declaratively

**Comment by gorhill** [comment]
In 1.44.4 invalid selectors were detected using the browser's `querySelector()` or `matches()` method, while this is no longer the case since 1.45.0, since filter lists can be compiled outside a browser environment, in which case there is no API to test the validity of a selector. This is why uBO now relies on CSSTree library to parse selectors, and `:not(#wrapfabtest > .adBanner)` is a valid selector, except for older browser. Once a selector has been first validated through CSSTree, uBO must perform more work to further validate, and this is done for example for `:has()`. Adding extra validation steps for `:not()` is more work which I am not sure is worth it given that it's an issue only for browser versions which were released about 2 years ago.

**Comment by dimisa-RUAdList** [comment]
Indeed, this version of the browser was released in august last year, and it cannot be called fresh. But I try to support the widest possible number of browsers, including those for which uBlock Origin Legacy is intended. Most likely, the above rule creates problems not only on `comss.ru`, but also on other sites. To be honest, I don't know what to do in this case.

**Comment by gorhill** [comment]
Where is `##.adBanner:not(:empty):not(.testAd):not(#wrapfabtest > .adBanner)` supposed to apply?

**Comment by dimisa-RUAdList** [comment]
Rule in uBlock filters. It probably has something to do with this: https://github.com/uBlockOrigin/uAssets/issues/14191

**Comment by u-RraaLL** [comment]
> Rule in uBlock filters. It probably has something to do with this: [uBlockOrigin/uAssets#14191](https://github.com/uBlockOrigin/uAssets/issues/14191)

Yup, wasn't referenced in the update commit and blame breaks for me when I try to open it https://github.com/uBlockOrigin/uAssets/blame/d9582c71019139dacdcd189f9a70556b96c30b59/filters/filters-2021.txt#L6716

**Comment by gorhill** [comment]
It was added because of <https://github.com/uBlockOrigin/uAssets/issues/14630>.

**Comment by dimisa-RUAdList** [comment]
I don't see the need for this rule either.

**Comment by Yuki2718** [comment]
The rule is obsolete as EL removed the bait rule and switched to sepcific block. I forgot to remove.

**Comment by gorhill** [comment]
If ever similar filter is needed, it could for example probably be rewritten as:

    ##.adBanner:not(:empty):not(.testAd):not(:has(#wrapfabtest > .adBanner))

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Since which version of Firefox did stop having problems with such selectors?

**Comment by gothic-bum** [comment]
> Since which version of Firefox did stop having problems with such selectors?

Firefox 84+ has full support for using a selector list argument with `:not()`.

**Comment by dimisa-RUAdList** [comment]
Ok, I will periodically run a filter update in Firefox ESR 78.15.0 + uBlock Origin 1.44 to make sure that no invalid rules appear in the logger.

**Comment by krystian3w** [comment]
If only EL was `##.adBanner` then possible remove too this line:

https://github.com/uBlockOrigin/uAssets/commit/d4522d692c9703db4c09ebc516c18ed5eac9512b#diff-4c4f42122f8aa0b951dfae2559543e589a1cb85689c53cd93601d7fafb67b321L6714

![image](https://user-images.githubusercontent.com/35370833/209635646-ae02e918-4f6e-487b-ba71-e040e12d3358.png)

**Comment by krystian3w** [comment]
As I understand it correctly, this closes the solution implemented in Firefox 79+ and Chrome 88+ and will require the list makers to apply some regex changing the comma to `:not(` and closing the brackets correctly.

In pure Firefox 66-78, it's unlikely that anyone will mess around with a script that allows uBo to run from an unsigned XPI/folder (this one can crash every so often and you'll have to bail out with a configuration backup).

Rather, the uBo fork for Firefox versions 67-78 in the mozilla store will not be warmly received.

**Comment by Yuki2718** [comment]
Yes, that was noted by https://github.com/uBlockOrigin/uAssets/commit/a8fd986e22b13790d11a3344bc3f1c7982abd4f2#r107931214 As a workaround I will change to simple class rules.

**Comment by krystian3w** [comment]
New nightmare arrived to Firefox 113+ and Chrome 111+:

https://caniuse.com/css-nth-child-of

Demo: https://codepen.io/css4-selectors-com/pen/BZgEMg
