### ISSUE TITLE
Can't block ad on this site

### ISSUE THREAD

**Issue by sweetyoru** [uBlockOrigin/uBlock-issues#2426]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The ad is still showing up on this site: `https://luotphimtv.vip`. Even after creating filter using pick tool.

### A specific URL where the issue occurs.

`https://luotphimtv.vip/phim-le/o-nha-mot-minh-1/`

### Steps to Reproduce

1. Access the site.
2. Pick the ad to close it.
3. The ad shows up again.

### Expected behavior

The ad doesn't exist, or disappear after picking it.

### Actual behavior

Can't make the ad disappear.

### Configuration

uBlock Origin: 1.45.2
Chromium: 108
filterset (summary): 
  network: 84790
  cosmetic: 38954
  scriptlet: 16756
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 10-1, never
    easylist: 61243-52, 5d.17h.20m
    easyprivacy: 31006-1171, 5d.17h.19m
    plowe-0: 3678-903, 10d.22h.11m
    ublock-abuse: 77-0, 11d.2h.14m
    ublock-badware: 4227-106, 1d.22h.57m
    ublock-filters: 31553-109, 1d.22h.55m
    ublock-privacy: 260-1, 11d.2h.13m
    ublock-quick-fixes: 459-23, 15h.20m
    ublock-unbreak: 1922-45, 1d.22h.54m
    urlhaus-1: 8642-0, 15h.19m
filterset (user): [array of 10 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 194 ms (selfie)
  maxAssetCacheWait: 1480 ms

**Comment by mapx-** [comment]
Enable `VIE: ABPVN List`
