### ISSUE TITLE
Is this a bug? (ublock window opening in a vertical cropped way)

### ISSUE THREAD

**Issue by masterofobzene** [uBlockOrigin/uBlock-issues#2427]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Recently for no reason, no changes on the firefox browser, ublock started to open the main window like this when clicking the extension:
![1](https://user-images.githubusercontent.com/94469116/209474283-4bef301e-38d9-4059-a374-c6c821ee6198.png)

clicking a second time usually makes the menu open as supposed (with the blocked elements on the side)

Firefox 108.0.1 (64-bit). Windows 10 x64. 

### A specific URL where the issue occurs.

-----------

### Steps to Reproduce

Click the extension button.

### Expected behavior

open in the normal way

### Actual behavior

opens with the blocked elements details below menu instead of in the left side.

### uBO version

1.45.2

### Browser name and version

Firefox 108.0.1 (64-bit)

### Operating System and version

Windows 10 x64.

**Comment by gorhill** [comment]
Can you reproduce with latest release 1.46.0?

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/discussions/2385
