### ISSUE TITLE
Option to surpress strict-blocking warnings

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#243]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Strict blocking is around for some time now. uBlock0riging still throws a warning when a domain is blocked due to strict blocking. For continuity I would suggest to keep that the default behavior but add an option simular to no-strict-blocking syntax:

**silent-strict-blocking: * true** 

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
e.g. 101com.com (I just took the first domain blackisted in Peter's Low list)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

The rule (silent-strict-blocking: * true) would silently block domains listed in one of the blocklist filters 

### Actual behavior:

Currently a pop-up screen is displayed when a domain is blocked due to strict-blocking 
(which is OK, I am just asking for an extra option to suppress this popup-screen_. 

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox 62.0.2
* Operating System and version: Windows7 Enterprise 32 bits

**Comment by gorhill** [comment]
Why would you want a blank page?

**Comment by Kees1958** [comment]
**What?**
With the silent-strict-blocking rule the blocking will be done completely silent. Domain is blocked without connecting out, no window, no pup-up, completely silent (like Windows Software Restriction Policies block execution of a progra without warning the user). 

**Why?**
When strict blocking was introduced (0.9.3.0), blocking the root page in stead of secondary was a change in behavior, Now it is the default behavior for a few years. As a user I should know by now that it is the default behavior and the "uBlock has prevented the following page from loading" popup is redundant and starts to annoy. 

That is why I requested an option to block the root-page silently without any browsing disturbance.  After all silencing (advertisement) noise is one of the great benefits of a blocker like uBlock0). Informing me that uBlock has done its work, has little added value IMO (to me). Since nobody asked before, I suggested an extra option, so others still can enjoy the "uBlock has done its work" pop-up  (maybe to feel good about chosing uBlock as extension?)

**Comment by gorhill** [comment]
If I don't show the warning, you will get a browser error page resembling this:

![](https://i.redd.it/6pp7qyq8dnnz.png)

I don't see how ending up with that is better than the informative uBO page.

**Comment by kekkc** [comment]
Still see a need for this setting. Use case are the common pop-unders:
1. you're on site A and click on link Z
--> site A is redirected to AdWebsite 
--> a new tab is opened and focused, loading the initial site A again (instead of opening Z)
2. you have to click on Z again (this time it is opened in the same tab)
3. you have to close AdWebsite tab (the original site A)

With uBlock the AdWebsite tab would show the strict blocking message. With "silent-strict-blocking: * true" it would show no message, but it would simply stay on site A (not performing any redirect). 

Probably this can be enhanced with "strict-blocking-useMessagebar: * true" and display a bar at top, like the original FF popup blocked messagebar.

**Comment by gorhill** [comment]
We have `popup` and `popunder` option for such cases, just report them.
