### ISSUE TITLE
Error after updating to 1.46.00 

### ISSUE THREAD

**Issue by Imna1975** [uBlockOrigin/uBlock-issues#2436]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Cannot load extension with file or directory name _metadata. Filenames starting with `_` are reserved for use by the system.

### A specific URL where the issue occurs.

no

### Steps to Reproduce

uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 4576068
  cosmetic: 232409
  scriptlet: 38375
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://adaway.org/hosts.txt: 7355-0, 1m
    https://adguard.com/en/filter-rules.html?id=2: 112156-1455, 23h
    https://dbl.oisd.nl/: 1023094-26728, 22h.53m
    https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt: 67933-61874, 22h.53m
    https://filters.adtidy.org/extension/ublock/filters/6.txt: 12320-6283, now
    https://hostfiles.frogeye.fr/firstparty-only-trackers-hosts.txt: 11893-340, 3d.22h.9m
    https://malware-filter.gitlab.io/malware-filter/phishing-filter-domains.txt: 7164-3172, 22h.53m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist: 427182-890, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science: 2465-14, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe: 400932-41775, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming: 4186-17, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection: 414051-102691, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto: 98112-68791, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist: 401974-185266, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling: 1185494-115353, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware: 183106-120320, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious: 106870-98525, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/proxies: 202266-356, 1m
    https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails: 350763-15296, 1m
    https://raw.githubusercontent.com/SoftCreatR/fakerando-domains/main/all.txt: 57579-39, 1m
    [24 lists not shown]: [too many]
  default: 
    user-filters: 4-0, never
    DEU-0: 6073-6073, 22h.53m
    easylist: 64996-64491, 3d.22h.13m
    easyprivacy: 30908-18980, 3d.22h.11m
    plowe-0: 3671-3652, 11d.21h.36m
    ublock-abuse: 77-3, 1m
    ublock-badware: 4268-599, 22h.57m
    ublock-filters: 31593-4051, 22h.56m
    ublock-privacy: 257-71, 1m
    ublock-quick-fixes: 454-57, 22h.53m
    ublock-unbreak: 1915-114, 22h.55m
    urlhaus-1: 7363-634, 22h.53m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 71 redacted]
switchRuleset: 
  added: [array of 4 redacted]
modifiedUserSettings: 
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 29711 ms
  maxAssetCacheWait: 18704 ms

### Expected behavior

nothing

### Actual behavior

![UBlock](https://user-images.githubusercontent.com/45740014/210092364-5462f57a-48d8-456f-88c8-566aadbfa26a.jpg)

### Configuration

.

**Comment by gorhill** [comment]
It's an issue with the browser, there is no file name starting with `_` in the submitted uBO package beside `_locales` is officially required for translated strings.

**Comment by gorhill** [comment]
Possibly related: <https://bugs.chromium.org/p/chromium/issues/detail?id=879386>.
