### ISSUE TITLE
Add a scriptlet to honor noscript tag

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2437]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/AdguardTeam/Scriptlets/issues/274
I emphasize currently there's no fix for Firefox with ETP enabled. If the scriptlet is made available, we can fix the issues without current exception in uBlock filters and Japanese filter (see https://github.com/AdguardTeam/AdguardFilters/issues/137213#issuecomment-1367789168). I guess it's not too much work as uBO already has noscript-spoof.js

### A specific URL where the issue occurs.

https://soranews24.com/

### Steps to Reproduce

1. Visit the site with Firefox ETP enabled
2. See images are not loaded.
3. If you turn No-scripting switch on, images will be loaded because now noscript is honored

### Expected behavior

Filter maintainer should have a way to honor noscript for such a case

### Actual behavior

No way

### uBO version

1.46.1b3

### Browser name and version

Firefox 108.0.1

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Images are loaded on my side with ETP enabled (default).

**Comment by Yuki2718** [comment]
@gorhill Really? Test on Private tab.

**Comment by gorhill** [comment]
On Private tab, the first top two images are loaded, but the others are placeholders with text _"Please allow ads on our site..."_.

**Comment by Yuki2718** [comment]
> isabling ETP solves the issue, so shouldn't this be reported to Firefox devs?

Do they address anti-adb? The blocking is legit.

**Comment by gorhill** [comment]
It's kind of the realm of using other blockers beside uBO can cause such issues, in which case disabling the other blocker(s) is the right solution, rather than trying to fix in uBO something caused by another blocker.

**Comment by Yuki2718** [comment]
Except that this is a browser's built-in feature which we had not been recommending to turn it off.

**Comment by gorhill** [comment]
It also happens without uBO.

**Comment by Yuki2718** [comment]
Yes, because currently exception is mandatory to fix. If noscript tag can be honored, no exception will be needed.

**Comment by gorhill** [comment]
Note that ETP icon has a _"Site not working?"_ link from which we can send a report. To me this seems the more sensible option, rather than burdening uBO with handling an issue caused by an external blocker.

**Comment by Yuki2718** [comment]
Okay sent a report. But I wonder, can't it be mostly copy-and-paste of noscript-spoof.js except for an argument I suggested? Sure, I don't know the fact.

**Comment by gorhill** [comment]
What are the chance such scriptlet would be useful elsewhere than on those two related sites? (rocket and sora news24)

**Comment by Yuki2718** [comment]
> What are the chance such scriptlet would be useful elsewhere than on those two related sites? 

I have to admit I'm not aware of. Though it will be another issue with different fix, as uMatrix is now archived, https://github.com/gorhill/uMatrix/issues/319 is to some extent relevant - but probably better to add noscript-spoof option/switch to uBO than filter scriptlet in terms of usability.

**Comment by Yuki2718** [comment]
> I don't have ETP enable and it does not load the images either except the 1st two. using FF 108, Ubo 1.46.1b4, windows 10

Unable to reproduce, and such issues should first be reported to https://github.com/uBlockOrigin/uAssets/issues/15705 with all the required details.

**Comment by troysjanda** [comment]
>Unable to reproduce, and such issues should first be reported to https://github.com/uBlockOrigin/uAssets/issues/15705 with all the required details.

Updated this and #15705 as requested

**Comment by Yuki2718** [comment]
Cause: Xpi uBo Personal Filters

**Comment by krystian3w** [comment]
This look as trust level needed #2229.

**Comment by gwarser** [comment]
> How about a renaming-attribute scriptlet ?

"Override `src`" hardcoded to `img` tags, `src` as a hardcoded target and one of this element attributes as a source value for `src`?

**Comment by gwarser** [comment]
This was only a joke, because of many "source" words in one sentence :)

**Comment by Yuki2718** [comment]
Closing for https://github.com/uBlockOrigin/uBlock-issues/issues/2347 which has better general jutility than this suggestion.
