### ISSUE TITLE
$popup rule not worked

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#2444]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

the rule 
`||rotf.lol^$popup,3p`
or 
`||rotf.lol^$popup` does not work

### A specific URL where the issue occurs.

`https://atishmkv.help/`

### Steps to Reproduce

1. add this `||rotf.lol^$popup,3p` 
or `||rotf.lol^$popup` in my filters
2. Go to `https://atishmkv.help/`
3. click on this banner that says **watch movies online** 
![image](https://user-images.githubusercontent.com/20338483/210584582-6f8c8b10-d112-42a1-9698-1c1a88673444.png)

### Expected behavior

`||rotf.lol^$popup,3p` 
or `||rotf.lol^$popup` works

### Actual behavior

`||rotf.lol^$popup,3p` 
or `||rotf.lol^$popup` not worked

### uBO version

1.46.1b4

### Browser name and version

firefox 108.0.1

### Operating System and version

win10

**Comment by gorhill** [comment]
The clicked link matches the URL of the tab being opened, so it's not considered a popup, it's considered an expected user-initiated navigation. If the URL of the tab didn't match the clicked link, then it would be considered an unexpected user-initiated navigation.

**Comment by gorhill** [comment]
The newly opened tab was closed by `||bemobtrcks.com^$popup` on my side, no need to add `||rotf.lol^$popup,3p`.

**Comment by ghajini** [comment]
yeah i know ,but it should work? even with `||rotf.lol^$popup,important`

**Comment by gorhill** [comment]
> even with `||rotf.lol^$popup,important`

If the URL of the new tab opened matches the clicked linked, it's not a popup, it's an intentional navigation by the user.

**Comment by ghajini** [comment]
okay i see https://github.com/uBlockOrigin/uBlock-issues/issues/1785 being opened

**Comment by Yuki2718** [comment]
As I can't comment in the linked issue, I write here. Not only `https://hapticswasher.com/ikSyEZFPCPkNG/59570` popup on `https://0gomoviz.com/theru-2023-malayalam-full-movie-watch-online-hd-free-download/ ` I discussed with @ghajini , I now see there's no way to block malware download by `$popup` or by `$all` on [malware site/blocked by JPF] `http://xjejfilqws\.duckdns\.org/?t=5175b37bd8e7ce0c4a2b77d090c10c63&rand=f664744741b96ed733881578954d0d8d` with simple href + target=_blank:

![malware](https://user-images.githubusercontent.com/58900598/211348980-68a0a4bc-9cb9-49c5-af54-36d67692a677.png)

Isn't this way too permissive? We need some sort of `strong` $popup for this kind.

**Comment by gorhill** [comment]
[Window.close()](https://developer.mozilla.org/en-US/docs/Web/API/Window/close):

> This method can only be called on windows that were opened by a script using the [`Window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) method. If the window was not opened by a script, an error similar to this one appears in the console: `Scripts may not close windows that were not opened by script.`

**Comment by gorhill** [comment]
`https://rotf.lol/ybwnpvrh` returns response headers with a `Location` header, so the browser never loads a document from this location, hence uBO can't inject extended filters if there is no document fetched by the browser.

**Comment by gorhill** [comment]
So your filter works when removing `Location`:

    rotf.lol##^responseheader(location)
    rotf.lol##+js(window-close-if, /^/)

**Comment by gorhill** [comment]
> and you will still see the `<meta>` tag even though it should've been HTML-filtered

HTML filtering bails out if the status code is not in the 200, but in the current case the status code is [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) which means "Moved permanently".

**Comment by gorhill** [comment]
Use `rotf.lol##+js(refresh-defuser)` instead of `rotf.lol##^meta` seems to work on my side.

**Comment by gorhill** [comment]
I will revise the doc.

**Comment by garry-ut99** [comment]
> MasterKia : https://github.com/uBlockOrigin/uBlock-issues/issues/2444#issuecomment-1376069725



https://github.com/uBlockOrigin/uBlock-issues/issues/942
