### ISSUE TITLE
Ublock not active on new TAB Brave browser

### ISSUE THREAD

**Issue by eldijomo** [uBlockOrigin/uBlock-issues#2447]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When starting \ opening my Brave browser with pinned tabs, the UblockO does not activate. I need to manually reload all tabs to get the extension active.

```
uBlock Origin: 1.46.0
Chromium: 108
filterset (summary): 
  network: 84754
  cosmetic: 40438
  scriptlet: 16781
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    NLD-0: 2513-12, 1d.20h.53m
    easylist: 61836-47, 4d.48m
    easyprivacy: 30850-1173, 4d.49m
    plowe-0: 3671-891, 90d.19h.34m
    ublock-abuse: 77-0, 1d.16h.6m
    ublock-badware: 4224-112, 1d.20h.54m
    ublock-filters: 31567-146, 1d.20h.57m
    ublock-privacy: 258-1, 1d.16h.5m
    ublock-quick-fixes: 447-18, 50m
    ublock-unbreak: 1909-58, 1d.20h.55m
    urlhaus-1: 7241-0, 49m
filterset (user): [empty]
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1046 ms (selfie)
  maxAssetCacheWait: 1511 ms
```

### A specific URL where the issue occurs.

https://mastodon.nl/public/local

### Steps to Reproduce

Open browser
Pin Tabs
Close browser
Open browser.

### Expected behavior

Open browser UblockO works.

### Actual behavior

Open browser UblockO does not works.

### Configuration

Chuwi laptop
Windows 11 last updates
Brave browser

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded

I'm afraid that nothing can be done.
