### ISSUE TITLE
element zapper & picker have no effect

### ISSUE THREAD

**Issue by AdKiller** [uBlockOrigin/uBlock-issues#245]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There is an overlay with the text "Access denied" in this page, that element picker or zapper can not filter for some reason. I selected the box and the area around it many times, using zapper and picker, but the box stays right there.

### A specific URL where the issue occurs
jobs.sgs.com/jobs/materials-engineer-lab-tech-lead-calgary-33355

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
select the Access Denied element using zapper or picker

### Expected behavior:
The element should be removed

[What you expected to happen]

### Actual behavior:
It stays in the page

[What actually happened]

### Your environment

* uBlock Origin version: uBlock Origin v1.17.0
* Browser Name and version:  Firefox 62.0.2 x64
* Operating System and version:  Windows 10 1803 x64

**Comment by gorhill** [comment]
I cannot reproduce an "Access denied" overlay at the provided URL.

**Comment by naxi1234** [comment]
This happen on all sites if "Disable cosmetic filtering" is enabled. (you must restart to see the effects)

This is not optimal if you want to disable cosmetic filtering for most sites but then want to use the zapper on a site.

**Comment by yourduskquibbles** [comment]
@naxi1234 that issue is a duplicate of https://github.com/gorhill/uBlock/issues/3212 & #25 (My own reported duplicate...)

**Comment by gwarser** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3212
