### ISSUE TITLE
uBO list showing out of date even after forced update

### ISSUE THREAD

**Issue by alanjacobmathew** [uBlockOrigin/uBlock-issues#2454]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

All the list are updated using the update now button. After that going to the individual list, for example `uBlock filters – Privacy`, clicking on the force update icon for that list, it shows that the lists are out of date. 

Though all the files seems updated when comparing with the github source files. It's just that options page showing files are out of date.

![ff uBo](https://user-images.githubusercontent.com/33965848/212464979-f4b51584-d5cf-4abf-956e-3ce9ed499a03.gif)

While on the topic, when the Update button is clicked, without purging cache, are all files updated at that moment or only those that are outdated?
If the former last updated time should be same for all. When I tested the updated time are all different. Some got `1 min ago` and other has `54 min ago`.  
![update time](https://user-images.githubusercontent.com/33965848/212465602-59881dae-ea93-49b5-b3f0-74780e1d34ae.gif)

### A specific URL where the issue occurs.

https://duckduckgo.com

### Steps to Reproduce

1. Update all the list in uBO
2. Choose an individual list and click on force update button next to the list

### Expected behavior

No `out of date` error

### Actual behavior

Lists are all updated

### uBO version

1.46.0

### Browser name and version

Firefox 108.0.2 , Brave Version 1.47.171 Chromium: 109.0.5414.87 

### Operating System and version

Win 10

**Comment by gwarser** [comment]
Only these marked by yellow triangle will be updated after you click on "Update now".

Clicking the clock icon resets the time stamp, making them marked ready for update.

**Comment by alanjacobmathew** [comment]
@uBlock-user 
That was my mistake. The writing on hovering the clock was `click to force an update`, which made me think it was force update button. The above link cleared all my issues

**Comment by u-RraaLL** [comment]
Should it perhaps say:
1. `Click to then force an update.`
2. `Click to then force an update above.`
3. `Click to purge this list, then update above.`

Third one seems the clearest to me.
