### ISSUE TITLE
Youtube player/screen stutters when moving the mouse across the edge of the video player.

### ISSUE THREAD

**Issue by That-Ski-Freak** [uBlockOrigin/uBlock-issues#2459]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have noticed this issue where if I move my mouse over my youtube tab/window and out of it again, the moment it crosses into the video player (from any area on my screen outside the player, or from within to outside), the video / my screen will stutter. I disabled all browser extensions, and the issue was not present, and I have isolated the problem to ublock origin (and yes, it does occur on a fresh chrome profile).

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=FhHM9MT41IE

### Steps to Reproduce

1. Watch a video on youtube.
2. Wave the mouse around across the border of the video player.
3. See the screen/video stutter and become slightly annoyed.

### Expected behavior

My screen to continue to display frames at a constant rate.

### Actual behavior

Display/video stutters.

### uBO version

1.46.0

### Browser name and version

Chrome Version 109.0.5414.74 (Official Build) (64-bit)

### Operating System and version

Windows 10

**Comment by gothic-bum** [comment]
>  [x]  I verified that this is not a filter list issue.

How did you verify that it is not a filter list issue?

**Comment by garry-ut99** [comment]
Recently similiar reports, where users comlpaining they have performance issues with uBO enabled, they might be related or not:
- https://github.com/uBlockOrigin/uAssets/discussions/16363
- https://github.com/uBlockOrigin/uAssets/issues/16361

Also try to get [profiling data](https://github.com/uBlockOrigin/uBlock-issues#performance-issues)

**Comment by stephenhawk8054** [comment]
`loadout.tf` case is not related to this issue, as the site constantly changes the DOM when hiding ads elements and the issue had been fixed. OP in that thread has not updated the filter list yet.

**Comment by krystian3w** [comment]
Also: All = All

uBlockOrigin/uAssets/issues/7636

**Comment by garry-ut99** [comment]
> Also: All = All

But perhaps it applies only to uAssets tracker, I dunno.

**Comment by gwarser** [comment]
"Troubleshooting Information"?

**Comment by gorhill** [comment]
Closing as invalid since no profiling data + analysis supporting that uBO is the issue was provided.

**Comment by krystian3w** [comment]
For me old videos laggy scroll and other interface elements:

`https://www.youtube.com/watch?v=PJ-JBFXh2IU`

helps disable cosmetic filtering.

**Comment by gorhill** [comment]
<https://profiler.firefox.com/>
