### ISSUE TITLE
[Feature Request] element picker in collaboration with element zapper

### ISSUE THREAD

**Issue by gabri25ele** [uBlockOrigin/uBlock-issues#2460]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

since in some cases the zapper works and the picker fails, couldn't you have an option to save the work that the zapper does and/or convert it for the picker?

### Steps to Reproduce

using zapper
works
using picker
not work

### Expected behavior

work both of them

### Actual behavior

not work both of them

### uBO version

1.46

### Browser name and version

Firefox 109

### Operating System and version

Windows 11

**Comment by gothic-bum** [comment]
Per gorhill:  
https://old.reddit.com/r/uBlockOrigin/comments/qpojmt/need_zapper_to_be_permanent_because_its_stronger/hxp1lna/
  
> Zapper removes an element you select directly. Picker creates a filter to be able find the elements to hide when a page loads. It's easy to remove an element. The difficult part is to derive a filter from it so that it can be targeted automatically after a reload. That's what the picker does, *assist* you in creating filters. If you can't create a filter which works reliably, then submit your issue to experienced filter authors, they will look at other ways to arrive at reliable filters -- and for this they need to be able to reproduce what you want on their side.

**Comment by krystian3w** [comment]
Experimentally you can add at end `:remove()`.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#subjectremove
