### ISSUE TITLE
Refresh button disappears if you click off after a change and did not apply

### ISSUE THREAD

**Issue by ghtesting2020** [uBlockOrigin/uBlock-issues#2464]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After making a change with the ubo widget in firefox if you do not click the refresh button that appears but click off to the site and  then back the refresh button is gone.This requires the user either undo the change, refresh with the button and redo the change and this  time pressing the refresh button. Or refreshing as you normally would with the browsers button. Notice the lock and eraser stay, only the refresh is gone.

### A specific URL where the issue occurs.

reddit.com

### Steps to Reproduce

1. open firefox
2. go to a non privileged site like reddit
3. make a change
4. click off of the ubo widget, like on to the reddit page
5. click back on the ubo widget which reopens it
6. the lock and eraser stay but the refresh button is  gone

### Expected behavior

Ideally ubo should keep the refresh button in the widget if there are changes and you clicked off the widget and back. ubo should be able to tell if a change has been applied or not, this could be a flag that shows the refresh button. 

### Actual behavior

If you made a change and click off the widget, then back to it the refresh button is gone.

### uBO version

1.46.0

### Browser name and version

firefox flatpak 109.0

### Operating System and version

arch linux everything latest

**Comment by gwarser** [comment]
I think this is deliberate. I recall discussion about this, but cannot find it.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2201#issuecomment-264074801 

"By design"?

**Comment by u-RraaLL** [comment]
Since you can still use your browser's refresh button/shortcut, it's actually more work to reopen uBO's popup to want to refresh from there.

**Comment by garry-ut99** [comment]
Exactly, I think that's exactly the reason why uBO's Refresh button disappears by design after leaving uBO's popup UI. ghtesting2020 - what's the problem using a browser's Refresh button.

> ghtesting2020 : Description: (...) refresh with the button (...)

No need, clicking uBO icon is enought (or clicking off to the site)

> lasers : https://github.com/gorhill/uBlock/issues/2201#issuecomment-264060910 : (With this time, I copied some input forms with clipboard manager because I don't want to lose them... Just in case.)

I don't see a reason to not do so before step 1, if forgotten, then it's an user's fault, and happens rarely.

**Comment by gorhill** [comment]
> Is it still intentional?

Yes.
