### ISSUE TITLE
AG scriptlet bad conversion 

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uBlock-issues#2465]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

from slack channel:

@jellizaveta

Rule from AdGuard Annoyances
`[$path=/images/]yandex.*#%#//scriptlet('abort-on-property-read', 'Object.prototype.renderDirect')`

in uBlock is converted to

`yandex.*##+js(abort-on-property-read, 'Object.prototype.renderDirect):matches-path(/images/)`

and the website: `https://eda.yandex.ru/moscow?shippingType=delivery` doesn’t work
Could you please take a look ?

L.E.
same for this filter:
`[$path=/pogoda]yandex.*#%#//scriptlet('prevent-eval-if', 'advPosNames')`

converted as:
`yandex.*##+js(noeval-if, advPosNames):matches-path(/pogoda)`

### A specific URL where the issue occurs.

https://eda.yandex.ru/moscow?shippingType=delivery

### Steps to Reproduce

Enable AdGuard Annoyances

### Expected behavior

no breaking, no filter conversion => uBO does not support `matches-path` with scriptlets

### Actual behavior

page broken

### uBO version

last version

### Browser name and version

chrome / other

### Operating System and version

windows 10, does not matter

**Comment by mapx-** [comment]
temporary whitelisted in quick fixes

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/tsurlfilter/issues/65

**Comment by gorhill** [comment]
I don't see how this can be fixed in uBO by parsing the filter as invalid, because the end result is valid syntactically, as the property chain is seen by uBO as:

    Object.prototype.renderDirect):matches-path(/\/(?:weather\/|pogoda\/|hava\/)/

Sure it looks nonsensical for a human, but is still is perfectly valid programmatically wise, as this is allowed in JS since property names can be any valid string:

    Object.prototype["renderDirect):matches-path(/\/(?:weather\/|pogoda\/|hava\/)/"]

I could make the scriptlet code bailout if it detects a "weird" character, but it's possible in the future that a site would use that character used to bail out to work around uBO. Best is to just fix this in AdGuard's compiler. I looked into it a few days ago and frankly I am not sure at all where fixes for uBO conversion are to be made.

**Comment by krystian3w** [comment]
Maybe you can use the exclusion section in the file: https://github.com/AdguardTeam/FiltersRegistry/blob/43e52eee5b6f2e5142ae949d906e0dc477c051ec/custom_platforms.js#L346

Their `[path]` "switch" implies on all the listed domains, so they can't combine two identical filters into one line.

**Comment by gorhill** [comment]
Fixed in <https://github.com/AdguardTeam/FiltersCompiler/commit/3af492c441135e029e3480c1fdb36f8fb09173a5>.
