### ISSUE TITLE
Discord slows down by ublock unless whitelisted.

### ISSUE THREAD

**Issue by rredford** [uBlockOrigin/uBlock-issues#2468]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Apparently ublock leaks something when discord website is being browsed, because it slows down discord till its unusable or refreshed or reloaded (which is different from simply visiting other page at same site)

Solved by simply adding discord.com to whitelist, but probably want to find root cause.

Note url is just random channel since specific channel is apparently required, but really you just click various channels and servers.

### A specific URL where the issue occurs.

https://discord.com/channels/610531541889581066/610531541889581068

### Steps to Reproduce

1. Have browser with ublock.
2. Load discord website chat. (Not app but website)
3. Just keep browsing servers and channels.
4. Notice that website have slowed down.
5. Refresh website in order to make it fast again.
6. Add discord.com to whitelist and notice it doesnt do it again

### Expected behavior

Keep browsing discord servers and channels forever without slowdown

### Actual behavior

It slows down, unless whitelisted.

### uBO version

1.46.0

### Browser name and version

firefox 109

### Operating System and version

xfce mint 21.1

**Comment by gothic-bum** [comment]
> **Prerequisites**
> I verified that this is not a filter list issue. 

How did you verify that this is not a filter list issue?  
  
----  

And from the [README](https://github.com/uBlockOrigin/uBlock-issues#readme):  
  
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from the Firefox Profiler/Chromium Profiler and a fully substantiated analysis supporting the claim.

**Comment by rredford** [comment]
Slowdown happens when discord is NOT in whitelist or any list. Basically default.

**Comment by mapx-** [comment]
try & test adding 

`||discord.com/api/*/science$xhr,1p,redirect=nooptext`

or

`||discord.com/api/*/science$badfilter`

**Comment by garry-ut99** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/vn86k7/degrading_performance_overtime_in_private_discord/
https://www.reddit.com/r/discordapp/comments/vetzqo/browser_firefox_windows_10_discord_slow/

**Comment by gorhill** [comment]
> or any list

Discord doesn't need to be in any list for blocking to occur, it just take one filter to cause undue filtering to occur. Use the logger to find out what is being blocked.

**Comment by rredford** [comment]
It is purely stock filters. I have not added or removed anything besides discord.com

**Comment by gothic-bum** [comment]
> I'm not sure how to access log

Documentation:  
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by rredford** [comment]
While I was at list checking things over, I spotted that I still have ublock addon. The old one. I disabled ublock origins and clicking around discord. It slowed down. When I tried same but with ublock disabled and ubo enabled, it does not happen. I thought I tested it properly and all that but apparently I was wrong. Sorry all. It must have been quite old bug indeed.

**Comment by u-RraaLL** [comment]
> I still have ublock addon. The old one.

Do yourself a favor and uninstall that. Also, don't use uBO with other similar extensions for maximum performance.

**Comment by rredford** [comment]
> > I still have ublock addon. The old one.
> 
> Do yourself a favor and uninstall that. Also, don't use uBO with other similar extensions for maximum performance.

Indeed. I feel silly. I somehow missed that thing for quite a while lol
