### ISSUE TITLE
uBlock Origin 1.46.0 crashing Firefox 108.0.2 endlessly

### ISSUE THREAD

**Issue by Dibrom2** [uBlockOrigin/uBlock-issues#2471]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

After auto-update of uBlock Origin to v1.46, Firefox 108.0.2 now crashes endlessly. Everytime I come back to my computer after leaving it with the browser open for more than 10mins, it has crashed and wants to restart. Behaviour is completely new from a perfectly stable setup prior to v1.46.0 of uBlock.

Firstly before crashing the entire browser, just the uBlock Origin extension crashes letting through all ads on every website, then eventually the browser obviously can't handle the uBlock misbehaviour anymore and the whole thing crashes.

### A specific URL where the issue occurs.

https://www.news.com.au/

### Steps to Reproduce

1. Firefox 108.0.2 in Windows 7
2. Install uBlock Origin 1.46.0
3. Browse to some websites with ads
4. uBlock crashes
5. Entire browser crashes

### Expected behavior

.

### Actual behavior

.

### Configuration

.

**Comment by krystian3w** [comment]
https://profiler.firefox.com/

Also consider manually update to 109 version:

https://www.mozilla.org/pl/firefox/all/#product-desktop-release

**Comment by gwarser** [comment]
Does it crash in new profile? (create new in `about:profiles`)  
Can you backup your uBO settings and reset to default? (in uBO dashboard, Settings tab)  


Can you share related crash info from `about:crashes`? uBO is not supposed to crash the browser, it's written in HTML/CSS/JS like any other web page. Crashing is a browser issue, you should report to browser devs. You should easily create new bug report if you follow the links on `about:crashes` ("bugzilla" tab on crash report web page).

**Comment by gorhill** [comment]
Browser crashes are a browser issue, and "uBlock misbehaviour" is just that you decided uBO is the issue. uBO is HTML/JS/CSS and is executed in a browser process (along with other extensions), so if that process also crashes, you will have the symptom you describes, i.e. uBO stops working. Report browser crashes to browser devs.
