### ISSUE TITLE
uBlock Origin icon looks blurry on extension panel

### ISSUE THREAD

**Issue by quackerex** [uBlockOrigin/uBlock-issues#2477]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

<img width="523" alt="screenshot" src="https://user-images.githubusercontent.com/41659980/216876892-90fbdb4d-d4a3-47cb-9f3c-186ae27f82d5.png">

<img width="505" alt="screenshot" src="https://user-images.githubusercontent.com/41659980/216876960-dde678dc-40f9-4850-ad27-3845fcbad5a7.png">

### A specific URL where the issue occurs.

moz-extension://f4f6dfb5-34e3-40d6-8605-b4af062a637d/dashboard.html#settings.html

### Steps to Reproduce

1. Open Firefox
2. Click on the extention icon

### Expected behavior

The uBlock Origin icon to be not blurry.

### Actual behavior

Blurry uBlock Origin icon

### uBO version

1.46.0

### Browser name and version

Firefox 109.0.1

### Operating System and version

macOS Ventura 13.2

**Comment by gwarser** [comment]
style='
	        
	        --webextension-menupanel-image: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-menupanel-image-light: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-menupanel-image-dark: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	      
	        
	        --webextension-menupanel-image-2x: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-menupanel-image-2x-light: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-menupanel-image-2x-dark: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	      
	        
	        --webextension-toolbar-image: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_16.png");
	        --webextension-toolbar-image-light: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_16.png");
	        --webextension-toolbar-image-dark: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_16.png");
	      
	        
	        --webextension-toolbar-image-2x: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-toolbar-image-2x-light: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	        --webextension-toolbar-image-2x-dark: url("moz-extension://xxxxxxxxxxxxxxxxxxxxxxxx/img/icon_32.png");
	      
	      '

**Comment by gwarser** [comment]
OK, they now want 2x 64px icon or svg for browser_action

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#choosing_icon_sizes

**Comment by tophf** [comment]
I've reported it in https://bugzil.la/1811128 and AFAICT they decided to revert to the old behavior starting with FF 111.
