### ISSUE TITLE
Overview Panel opened below despite screen space available

### ISSUE THREAD

**Issue by ljrk0** [uBlockOrigin/uBlock-issues#2478]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When using fractional scaling (on GNOME Wayland) and using 125% or 150% scaling, the uBO Overview Panel will open below instead of to the left, when the Chrome (on Ozone/Wayland) is in full size on a non-scaled monitor.

### A specific URL where the issue occurs.

example.org

### Steps to Reproduce

1. Attach a second monitor
2. Activate fractional scaling in GNOME: `gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
3. Navigate to *Settings > Devices > Displays* and select 125% or 150% for one display (in my case built-in)
4. Start Chromium with `--enable-features=UseOzonePlatform --ozone-platform-hint=auto`
5. Move the window to the unscaled monitor
6. Open uBO (with Advanced Mode set)

Note that

 * this doesn't occur with non-fractional scaling or scalings above 150%, i.e. not with 100%, 175%, 200% or 225%
 * it doesn't occur on the scaled monitor
 * it doesn't occur when the window is smaller, e.g., halved
 * it doesn't occur when the scaled monitor is disabled (laptop lid closed)

### Expected behavior

uBO (or Chrome?) correctly calculates the remaining screen space and opens the overview panel to the left.

### Actual behavior

It opens below, as can be seen in this 
[Screencast.webm](https://user-images.githubusercontent.com/7831843/217276528-6aac95eb-0abc-41ed-842e-92df3ff47cd1.webm)

### Configuration

```
uBlock Origin: 1.46.0
Chromium: 109
filterset (summary): 
  network: 143479
  cosmetic: 229025
  scriptlet: 38336
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 40565-4511, 3d.16h.51m
    DEU-0: 6173-3, 4h.53m
    adguard-annoyance: 63481-241, 13h.5m
    adguard-generic: 68364-1142, 13h.4m
    adguard-mobile: 8781-66, 13h.3m
    adguard-social: 19851-839, 13h.2m
    adguard-spyware: 40565-40565, 3d.21h.22m
    adguard-spyware-url: 898-2, 13h.1m
    fanboy-annoyance: 85949-6471, 8d.18h.5m
    fanboy-cookiemonster: 45296-45296, 8d.18h.4m
    fanboy-social: 23086-23081, 5d.21h.12m
    fanboy-thirdparty_social: 68-21, 8d.18h.3m
    ublock-annoyances: 4815-243, 13h
  default: 
    user-filters: 9-0, never
    easylist: 64996-1026, 1d.5h.11m
    easyprivacy: 30925-12703, 1d.5h.10m
    plowe-0: 3667-1065, 11d.23h.30m
    ublock-abuse: 77-0, 52m
    ublock-badware: 4247-308, 12h.59m
    ublock-filters: 31925-3894, 12h.58m
    ublock-privacy: 263-57, 17m
    ublock-quick-fixes: 543-160, 4h.55m
    ublock-unbreak: 1911-109, 12h.56m
    urlhaus-1: 6520-0, 4h.54m
filterset (user): [array of 9 redacted]
trustedset: 
  added: [array of 35 redacted]
switchRuleset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 392 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 576 ms (selfie)
  maxAssetCacheWait: 592 ms
```

**Comment by gorhill** [comment]
I am not going to be able to go through report steps, but keep in mind browser limits the width of popup panel regardless of available screen size.

**Comment by ljrk0** [comment]
Hm, this sounds like it's more of a Chromium bug then?

I've enabled `info` logging but it doesn't seem to log any UI events, otherwise I'd gladly do some debugging.  Is there anything else that I could do in that regard?

For now the issue is workaround-able for me, but ideally it can be fixed properly.  If I knew how/where I'd spend some time debugging further.  For now I'm at loss at "where to look".

**Comment by ljrk0** [comment]
Another data point: Closing the laptop lid (thus disabling the scaled monitor) fixes the problem.
