### ISSUE TITLE
Procedural `:has` applies to multiple selectors; native `:has` only applies to the last one

### ISSUE THREAD

**Issue by antonok-edm** [uBlockOrigin/uBlock-issues#2480]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cosmetic filters with multiple selectors and `:has` are interpreted differently depending on whether the browser has native `:has` support.

### A specific URL where the issue occurs.

docs.rs

### Steps to Reproduce

Add this custom filter:
```
docs.rs##form, .recent-releases-container:has(invalid)
```

### Expected behavior

The filter should ideally be interpreted the same way on Chromium and Firefox.

Intuitively, `form` (which appears in the page's top navbar) should be hidden. As far as I can tell, the propagation of procedural operators to previously listed selectors is not documented in the wiki.

### Actual behavior

The filter causes `form` to be hidden on Chromium browsers, but nothing is hidden in Firefox.

### uBO version

1.46.0

### Browser name and version

Firefox 109.0.1, Chromium 109.0.5414.87

### Operating System and version

Arch Linux

**Comment by antonok-edm** [comment]
@uBlock-user it's caused by the semantics uBO applies to procedural selectors vs. native selectors. uBO doesn't seem to be aware of the state of the `about:config` flag, so even with `layout.css.has-selector.enabled` set to `true`, the behavior is different.

In other words, _without_ native `:has`, uBO treats the rule as equivalent to:
```adblock
docs.rs##form
docs.rs##.recent-releases-container:has(invalid)
```

versus on platforms _with_ native `:has`, uBO treats it as equivalent to:
```adblock
docs.rs##form:has(invalid)
docs.rs##.recent-releases-container:has(invalid)
```

**Comment by antonok-edm** [comment]
To be clear, I'm not sure if it's actually worth fixing this case specifically if Firefox is likely to catch up soon. But I'd definitely like to see the distinction between how native vs. non-native pseudoselectors are applied to multiple selectors:
- either documented somewhere official
- or changed to _always_ work like the native CSS pseudoselectors

because it's quite subtle and unexpected.

**Comment by gwarser** [comment]
>3. Concatenating multiple procedural selectors in one filter is not supported. example.com##p:has(img),div:has-text(advert) will not work as expected ([#453](https://github.com/uBlockOrigin/uBlock-issues/issues/453)).

https://github.com/uBlockOrigin/uBlock-issues/wiki/Procedural-cosmetic-filters#important

**Comment by antonok-edm** [comment]
If it is truly undefined/unintended behavior, I'll just note there are a handful of filters in `uAssets` using this kind of pattern and it'd be worth updating them accordingly:
- https://github.com/uBlockOrigin/uAssets/blob/efeb13604285b5636571f81c06771805dd889ab8/filters/filters.txt#L11793
- https://github.com/uBlockOrigin/uAssets/blob/efeb13604285b5636571f81c06771805dd889ab8/filters/filters.txt#L3069
- https://github.com/uBlockOrigin/uAssets/blob/efeb13604285b5636571f81c06771805dd889ab8/filters/filters.txt#L14093
- https://github.com/uBlockOrigin/uAssets/blob/bfa24f393982928298bd499034281a23f7db78f2/filters/filters-2021.txt#L2586

_(not an exhaustive list)_

**Comment by garry-ut99** [comment]
> To be clear, I'm not sure if it's actually worth fixing this case specifically if Firefox is likely to catch up soon.

It might take several months until Firefox will catch up: https://bugzilla.mozilla.org/show_bug.cgi?id=418039
Most of browsers support it already: https://caniuse.com/css-has

> If it is truly undefined/unintended behavior, I'll just note there are a handful of filters in `uAssets` using this kind of pattern and it'd be worth updating them accordingly:

I agree, they need either to be fixed in filter lists or fixed in uBO until `:has` becomes enabled by default for Firefox

> (not an exhaustive list)

Full list just from "uBlock filters" (61 filters):


```adb
pussyspace.com,pussyspace.net###alphabet, #channels, #divx-container, #hmenu, #inform, #nowlooking, #playerCamBox, #playerMenu, #qcat, #showPlayer, #tabel_tagslist, #video_content, #web_cam, .BaseRoomContents, .buttons, .carouselTopScroll, .carusel-keys-box-ps, .footerdesc, .in_top, .load_more_rel, .mainBoxTitle, .pagIno, .playerContent100pr, .relatedVideo, .right-160px, .videos-related, footer, header, [href^="/webcams.php"]:others()
googledrivelinks.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
djxmaza.in,proviralhost.com###wait1button.disabled, #wait2button.disabled:remove-class(disabled)
proviralhost.com###wait1button ~ *:not(#wait2button, center:has(#wait2button))
watchfreexxx.net##.happy-player-beside, .happy-section, .widget_execphp:has-text(/Advertisement|ExoLoader/)
pandamovie.*,pandamovies.me,pornkino.cc,speedporn.*,xxxscenes.net,youwatchporn.com##.happy-player-beside, .happy-section, .widget_execphp:has-text(/Advertisement|ExoLoader/)
games.dailymail.co.uk##display-ad-component, [class^="DisplayAd"], .ark-ad-message:style(visibility: collapse !important)
ufacw.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
ufacw.com###wpsafe-generate, #wpsafe-link:others()
ff14angler.com##ins.adsbygoogle,iframe[id^="aswift_"]:style(opacity:0 !important; pointer-events: none !important;)
makemoneywithurl.com###scroll.hidden, .footerLink.hidden:style(display: block!important)
toolss.net###wpsafe-generate, #wpsafe-link:style(display: block !important;)
informaxonline.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
informaxonline.com###wpsafe-generate, #wpsafe-link:others()
zap.in###verifyAd,#flexContentAdFrame:style(position:absolute !important; height:500px !important; display:block !important; left:-30000px !important)
techjunkie.com##.home-page.main-section, html > body:style(margin-top: 0px !important;)
dbsmanga.com,demonslayermanga.com,read7deadlysins.com,readdrstone.com,readfairytail.com,readhxh.com,readjujutsukaisen.com,readkaguyasama.com,readkingdom.com,readmha.com,readnaruto.com,readnoblesse.com,readonepiece.com,readopm.com,readsnk.com,readtowerofgod.com,readvinlandsaga.com,watchgoblinslayer.com,watchoverlord2.com,watchsao.tv##.justify-center > div > b:first-child, .justify-center > div > br:nth-of-type(-n+5), .justify-center > div > center
sitecuatui.xyz###gtelinkbtn, #wpsafe-generate, #wpsafe-link:style(display: block !important;)
gaminplay.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
gaminplay.com###yuidea-generate, #yuidea-snp:style(display: block !important;)
gaminplay.com##.g-recaptcha, iframe[src*="google.com/recaptcha"], #yuidea-btn-before, #yuidea-btn-after:others()
gifans.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
liveschauen.com##pjsdiv[style="position: absolute; top: -7px; left: -111px; pointer-events: none; opacity: 1; transition: opacity 0.1s linear 0s, transform 0.1s linear 0s; color: rgb(255, 255, 255); font-size: 15px; font-family: Tahoma; letter-spacing: 0.5px; padding: 0px 3px; white-space: nowrap; font-weight: bold; transform: scale(1);"]:upward(1)
techymedies.com###wpsafe-generate,#wpsafe-link,.bt-success:style(display: block !important;)
coinsearns.com,mcrypto.club,blog-forall.com,luckydice.net,adarima.org###wpsafe-generate, #wpsafe-link:style(display: block !important;)
coin-free.com,kienthucrangmieng.com,thuocdangian.net,fanclup.info###wpsafe-generate, #wpsafe-link:style(display: block !important)
askpaccosi.com,crypto4tun.com###wpsafe-generate, #wpsafe-link:style(display: block !important)
1apple.xyz###wpsafe-generate, #wpsafe-link:style(display: block !important;)
masterduelmeta.com##html,body:style(overflow: auto !important;)
financeflix.in,technoflip.in###wpsafe-generate, #wpsafe-link, #getlinkbtn:style(display: block !important;)
financeflix.in,technoflip.in###wpsafe-generate, #wpsafe-link, #getlinkbtn:others()
veganal.co,veganho.co,veganac.co,veganab.co###wpsafe-generate, #wpsafe-link:style(display: block !important;)
themorningtribune.com###yuidea-generate, #yuidea-snp:style(display: block !important;)
iptvjournal.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
nawahi1.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
7apple.net###wpsafe-generate, #wpsafe-link:style(display: block !important;)
theblockcrypto.com##body,html:style(height: auto !important; overflow: auto !important)
claimfey.com###tp-generate,#getlinkbtn:style(display: block !important;)
cgchotbox.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
tudaydeals.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
technicalatg.*###wpsafe-generate, #wpsafe-link:style(display: block !important;)
choiceappstore.xyz###wpsafe-generate, #wpsafe-link:style(display: block !important;)
inbbotlist.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
apkmaven.*###wpsafe-generate, #wpsafe-link:style(display: block !important;)
cryptoblog24.info###wpsafe-generate, #wpsafe-link:style(display: block !important;)
allcryptoz.net,crewbase.net,crewus.net,shinbhu.net,shinchu.net,thumb8.net,thumb9.net,topcryptoz.net,uniqueten.net,ultraten.net###wpsafe-generate, #wpsafe-link:style(display: block !important;)
itstillworks.com##.logo,.blinker:style(animation: none !important;)
koushoku.org##.exo-native-widget,div[style*="250px"],div[style*="728px"],img[width="300px"],img[width="728px"],video,img[height="250px"]:style(height: 1px!important;)
wa.de##.id-Page-layoutWrap, .id-SiteWrap, .id-SiteHeader-wrap:style(width: 100% !important; max-width: 100% !important;)
bloggertheme.xyz###getlink, #pop-button:style(display: block !important;)
techus.website,ptjobsz.xyz###download-button, #generate-link, .button, #main-download:others()
edunc.xyz,newstvhindi.in###myBtn, #nxBtn, #nxInfo:others()
adzz.in##button#getlink, button#gotolink:style(display: block !important;)
tech24us.com###download-button, #generate-link, .button, #main-download:others()
theusaposts.com###wpsafe-generate, #wpsafe-link:style(display: block !important;)
afly.pro##.g-recaptcha, iframe[src*="google.com/recaptcha"], .btn-captcha, .btn-black-outline:others()
blog.onroid.com##.countdown, .get-link:others()
itscybertech.com###my_captcha_form > #shbtn2, #gtbtn2:style(display: block !important;)
itscybertech.com###tlink, .g-recaptcha, iframe[src*="google.com/recaptcha"], #postlink, #postfooterOk:others()
takez.co###toshowtrlink, #gtbtn2:style(display: block !important;)
takez.co###toshowtrlink, #gtbtn2, .divTableCell, #postfooterOk:others()

```

**Comment by krystian3w** [comment]
A few is simple CSS like:

`###a, #b:style(display: block !important;)`

So can be removed from cite due rare chance to break by new commit to Parser/CSSTree.

**Comment by krystian3w** [comment]
Fix maybe need wait due is not easy:

https://github.com/uBlockOrigin/uBlock-issues/issues/2228#issuecomment-1284265726 https://github.com/uBlockOrigin/uBlock-issues/issues/2228#issuecomment-1284271396

**Comment by krystian3w** [comment]
> `:others()` is not implemented by AdGuard so it should be dropped.

Rather, it is useful - someone can do tests on how its presence affects a non-updated add-on (all line should be ignored).

In part, it is worth watching to see if it begins to require use:

```adb
public.suffix###:is(a,b):others()
! or
public.suffix###:where(a,b):others()
```

When uBo copies the "CSS4" logic for all except vanilla selectors w/w `:style` only.

**Comment by garry-ut99** [comment]
I've updated my https://github.com/uBlockOrigin/uBlock-issues/issues/2480#issuecomment-1422890205, issue is only with inconsistent behaviour of `:has()` between browsers, there is no point in mixing other operators to this problem, as they just follow CSS standard to apply the same style for all comma separated elements https://www.w3schools.com/cssref/sel_element_comma.php.

**Comment by krystian3w** [comment]
To check also needed by use Orion:

https://browser.kagi.com/

Here vanilla CSS implementant should be unlocked if use same engine like Safari 15.4+.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2480

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/ExtendedCss/issues/164https://github.com/AdguardTeam/ExtendedCss/issues/164

**Comment by krystian3w** [comment]
Apparently they want to allow in Firefox 116 the use of `has` without burying in `about:config`.


So July must be spent testing the 116 compilation on the beta channel.

**Comment by garry-ut99** [comment]
Implemented in Firefox 121 Beta : https://www.mozilla.org/en-US/firefox/121.0beta/releasenotes/ :

> The [:has()](https://developer.mozilla.org/docs/Web/CSS/:has) selector is now supported. This allows authors to match elements that has, or "anchors", at least one element matching its relative selector.

**Comment by u-RraaLL** [comment]
@gorhill I'm on FF121 since a few hours ago, but it doesn't seem to work correctly with the `:has()` selector.

E.g. In this issue, before submitting this comment:

`##p>code:first-of-type, div>pre` 20 matches
`##p>code:first-of-type, div:has(>pre)` 5 matches - only selects `div:has(>pre)`
`##p:has(>code:first-of-type), div>pre` 0 matches
`##p:has(>code:first-of-type), div:has(>pre)` 0 matches

On Chrome it matched 20 for each of these. Correct elements/highlights.

Tested on a new browser profile for both.

**Comment by garry-ut99** [comment]
Maybe for the same reason it doesn't work with the flag : https://github.com/uBlockOrigin/uBlock-issues/issues/2480#issuecomment-1422050754

**Comment by u-RraaLL** [comment]
Maybe, but I thought this would fix it: https://github.com/gorhill/uBlock/commit/c5724c1cce

**Comment by gorhill** [comment]
> Maybe, but I thought this would fix it: https://github.com/gorhill/uBlock/commit/c5724c1cce

This is supposed to fix it, but for unknown reasons, [runtime.getBrowserInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo) is not defined in the element picker context, this causes `native_css_has` to never be set.

**Comment by garry-ut99** [comment]
Yes, good thing, works now even on Firefox 115 with flag enabled.

**Comment by krystian3w** [comment]
IMO 116+ are needed to safe hide elements, so ESR should be blocked untill released new 128 ESR at 9 june 2024.

**Comment by krystian3w** [comment]
One could still add a warning in the linter that the filter can move in CSS 4 and will hide the element even if it has no children or siblings (e.g. lists from Nordic project https://github.com/DandelionSprout/adfilt if wasn't converted at all to use `:is(..., ...):has(...)`).

**Comment by garry-ut99** [comment]
> IMO 116+ are needed to safe hide elements,

It seems you are right, this filter https://github.com/uBlockOrigin/uAssets/commit/49ddeaf205366230d8f81b258b81ecb935c4d05f (line 1838) causes a glitch on FF 115 ESR with `has` flag enabled, described here https://github.com/uBlockOrigin/uAssets/issues/12214#issuecomment-1902257825, but there is no breakage, except a fact that the filter doesn't work (until an user manually interacts with a page).
