### ISSUE TITLE
"My Filters" tab doesn't seem to have proper documentation

### ISSUE THREAD

**Issue by sdasda7777** [uBlockOrigin/uBlock-issues#2481]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The syntax on the "My filters" tab doesn't seem to have proper documentation. Clicking the "i" icon leads to [here](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), but that only explains editing shortcuts, nothing about the actual syntax.

### A specific URL where the issue occurs.

everywhere?

### Steps to Reproduce

1. Visit "My filters" tab
2. See the syntax
3. Click the "i" button
4. Be confused

### Expected behavior

I would expect the page to contain description of the syntax, or link to it if it's described elsewhere.

### Actual behavior

The syntax is not explained in any way.

### Configuration

Can't leave blank

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/217743206-d569d525-0a07-4cbc-9505-eef586402fae.png)

**Comment by sdasda7777** [comment]
I see, sorry, I assumed those would be the pages above in the hierarchy and ignored it, for some reason: Still might be beneficial to mention it in the text.
