### ISSUE TITLE
:after and :before filters getting rejected

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2483]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://developer.mozilla.org/en-US/docs/Web/CSS/::after:

> Note: CSS introduced the `::after` notation (with two colons) to distinguish [pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) from [pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements). For backward compatibility, browsers also accept `:after`, introduced earlier.

FYI @DandelionSprout.

### A specific URL where the issue occurs.

https://example.com

### Steps to Reproduce

1. Add: `example.com##h1:after:style(content: 'TEST' !important;)`
2. The filter gets highlighted as red (rejected).
3. Add: `example.com##h1::after:style(content: 'TEST' !important;)`
4. Go to `example.com` and see "TEST" next to "Example Domain".

### Expected behavior

`example.com##h1:after:style(content: 'TEST' !important;)` should work.

### Actual behavior

`example.com##h1:after:style(content: 'TEST' !important;)` doesn't work.

### uBO version

1.46.1b18

### Browser name and version

Firefox 109.0

### Operating System and version

-

**Comment by gwarser** [comment]
Use double colon.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2442

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/464
