### ISSUE TITLE
Set background-color hide elements with elements zapper & picker

### ISSUE THREAD

**Issue by pierretom** [uBlockOrigin/uBlock-issues#2487]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Set `background-color` in userContent.css hide elements with elements zapper & picker.

Example with https://github.com:
![no_elements](https://user-images.githubusercontent.com/16454332/218311707-ec1575f5-bc2c-4446-94ea-e2b9484346ed.png)

### A specific URL where the issue occurs.

https://github.com

### Steps to Reproduce

1. Create userContent.css.
2. Add:
```
body {
  background-color: SkyBlue !important;
}
```
3. Use elements zapper & picker.

### Expected behavior

When using elements zapper & picker should show elements.

### Actual behavior

When using elements zapper & picker it only show the selection of elements.

### uBO version

1.46.0

### Browser name and version

Firefox 109.0

### Operating System and version

Debian Sid

**Comment by gorhill** [comment]
This is a self-inflicted issue, you are forcing the background color to be a specific color, overriding the document's own color, which for the picker/zapper is set to `transparent`. Don't override the document's own color, either drop `!important` or exclude uBO's own element from your overriding (i.e. use `body:not(#ublock0-epicker) { ... }`).

**Comment by pierretom** [comment]
Ok, thanks [gorhill](https://github.com/gorhill)!
