### ISSUE TITLE
Migrate icons to FontAwesome svg files (from the font file)

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#249]
Latest FontAwesome version make available a package[1] where each individual icon is defined in a plain svg file. Given this I want to import only the needed svg files into a single svg `defs` files and use inline svg.

I started such conversion work in uMatrix (<https://github.com/gorhill/uMatrix/commit/c6e29be792df116a9b328b74a4b15455ccbe2138#diff-4de122c13cf2cc4e2364626b0acdb2c9>).

[1] https://use.fontawesome.com/releases/v5.3.1/fontawesome-free-5.3.1-web.zip

**Comment by gorhill** [comment]
It looks like Fontawesome 5 is no longer developed by the original author. I don't like what they have done with some of the icons. It's going to be tedious work but I will be importing/converting manually the Fontawesome 4 (original author) icons as proper svg entities through Inkscape (converting [as proposed here](https://stackoverflow.com/questions/18113478/extracting-svg-from-font-awesome/18113524#18113524) does not work -- for example the `code` icon is _really_ 1830 units wide, but that information is nowhere to be found in the svg font file + other issues).

**Comment by gorhill** [comment]
Well I had no idea, thanks for the tip.

When I dug more into Fontawesome 5 yesterday I became uneasy about using it as it seemed the original author is no longer part of the project and some changes in the icons were dubious, for example the `double-angle-up` and `code` are now bold-looking while they used to be regular in v4 (the regular versions are no longer free...)

Looking at Forkawesome, I will still have to import manually, the svgs files in the repo still have the issues I am fixing with Fontawesome 4.7. For example, [this icon](https://github.com/ForkAwesome/Fork-Awesome/blob/master/src/icons/svg/angle-double-up.svg) is not centered in its viewbox, and this causes issues: can't transform cleanly, and width is not representative of the width of the icon.

**Comment by uBlock-user** [comment]
The fonts used in the latest dev build are thicker and bigger, is that because of the new dev ?
