### ISSUE TITLE
Script loaded as `object` bypasses dynamic filtering

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#2496]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This Instagram script bypasses dynamic filtering rules.

### A specific URL where the issue occurs.

`https://veja.abril.com.br/mundo/cadela-brasileira-encontra-vitimas-soterradas-por-terremoto-na-turquia/`

### Steps to Reproduce

* Block third-party scripts with the extension panel
* Go to `https://veja.abril.com.br/mundo/cadela-brasileira-encontra-vitimas-soterradas-por-terremoto-na-turquia/`

### Expected behavior

No connections to third-party scripts.

### Actual behavior

`https://www.instagram.com/embed.js?ver=2.4.4` is loaded as an `object`.

### uBO version

1.47.0

### Browser name and version

Firefox 110

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
Wasn't `<object>` linked to `frame` type? It does not seem to be blocked when blocking 3p frames now.

**Comment by gwarser** [comment]
There are many more scripts like this

![image](https://user-images.githubusercontent.com/886325/219071310-a80da084-ce4c-4598-b91f-17768546a3f6.png)


>The [content type](https://developer.mozilla.org/en-US/docs/Glossary/MIME_type) of the resource specified by data. **At least one of data and type must be defined.**

But it's not here. ???

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object

**Comment by garry-ut99** [comment]
> Script loaded as `object`

Not only scripts, many other things can be smuggled as object:

> The `<object>` tag defines a container for an external resource.
> The external resource can be a web page, a picture, a media player, or a plug-in application.

<hr>

> Will need a new category rule such as `* * 3p-object` block to address this.

If several different things will be smuggled as `object`, all of them will be blocked then, which might be not always expected result by an user, actually the same risk applies for network filtering, but in network filtering a blocking rule can include path/name thus narrowing/lowering the risk.

<hr>

> **At least one of data and type must be defined.**  But it's not here. ???

Such requirement is present only in Mozilla's documentation, not in other documentations:

> https://html.spec.whatwg.org/#attr-object-type : The `type` attribute, **if present**, specifies the type of the resource.
> https://www.w3schools.com/tags/tag_object.asp : examples provided are without `type`

So either the requirement:
- is not longer valid and Mozilla just forgot to remove it from the documentation
- or it's a bug as Firefox allows something what shouldn't be allowed as per their doc

<hr>

Also might be helpful:
- https://github.com/gorhill/uBlock/issues/2747
- https://github.com/gorhill/uBlock/issues/3187

**Comment by garry-ut99** [comment]
> Block third-party scripts with the extension panel

Not clear whether locally (only on `veja.abril.com.br`) or globally (and `veja.abril.com.br` was just an example)
Not clear whether only `instagram.com` 3p scripts or `all` 3p scripts (and `instagram.com` was just an example)

Can use:
- locally only `instagram.com`: `veja.abril.com.br https://www.instagram.com object block`
- locally for all 3p domains, then can add additional domains
- globally only `instagram.com`: `* https://www.instagram.com object block`
- globally for all 3p domains, then need to implement `* * 3p-object block `

**Comment by krystian3w** [comment]
I can load image by `<embed>` and `<object>`.
