### ISSUE TITLE
Closing tab if form is sended before 10.9 seconds

### ISSUE THREAD

**Issue by einsteinsfool** [uBlockOrigin/uBlock-issues#250]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock closes tab if a form is sended before ~10.9s passes.

### A specific URL where the issue occurs

    https://eztv.ag

### Steps to Reproduce

1. Go to `https://eztv.ag`.
2. Open in a new tab one of the torrents in from the big table either by clicking a middle button on the title or right clicking on the title and choosing "open in a new tab".
3. The body of the page will be blank (which is ok because of a static filter) and you'll only see a small search frame.
4. Search something (e.g. "a").

### Expected behavior:

It should display search results without closing the tab.

### Actual behavior:

After searching (sending the form) the tab closes immediately.

If you wait ~10.9s and then search the tab won't close.
You can do anything you want during these ~10.9s: switch tab, open a new one, open devtools, even do ctrl+f5 3 times. If you do all that and search before 10.9s the tab will still close.
To fix this you can go to uBlock settings -> filter lists and disable EasyList.

I know it might seem like a filter bug but if you wait the mentioned time, the tab doesn't close.

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox Nightly 64, Chromium 69
* Operating System and version: openSUSE Tumbleweed, windows 10, MacOS 10.12

**Comment by gorhill** [comment]
The popup is closed because of the EasyList filter `/http*.:\/\/.*[?|=|&|%|#|+].*/$popup,domain=eztv.ag`.

uBO does have code to mitigate such false positives where the navigation occurred legitimately as a result of user interaction. Such false positives were fixed for when clicking links in <https://github.com/gorhill/uBlock/issues/2919>.

However, the navigation here occurs when submitting a form. I have to investigate if there is a way for uBO to detect sych false positives without compromising the reliability of detecting actual unwanted popups.

**Comment by gorhill** [comment]
Closing as a filter issue.
