### ISSUE TITLE
uBo does not work on Fennec with the latest version

### ISSUE THREAD

**Issue by AndrewRyanChama** [uBlockOrigin/uBlock-issues#2502]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock origin does not work on the legacy Firefox Fennec release.  (Firefox version 68)
After updating to 1.47.0 ublock stopped working completely, and rolling back to the previous version fixed the problem.

I don't expect the older version of Firefox to be fully supported by Ubo but the manifest should be updated to reflect this.

### A specific URL where the issue occurs.

https://youtube.com

### Steps to Reproduce

 download https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi
install ubo version 47
visit any page

### Expected behavior

ads should be blocked

### Actual behavior

ads are not blocked

### uBO version

47

### Browser name and version

Firefox Fennec 68

### Operating System and version

Android 11

**Comment by gorhill** [comment]
Minimum supported version is now 79, see <https://github.com/gorhill/uBlock/commit/e23f0bd7d5d97c2b7fbcca96e77b26cb78b834d6>.

**Comment by iam-py-test** [comment]
Can you install the latest version of Firefox for Android?

**Comment by krystian3w** [comment]
I do not see any contraindications (it does not have Android 4.X where Firefox Daylight 79+ will not officially run).

> https://www.mozilla.org/en-US/firefox/android/79.0/releasenotes/

**Comment by mzso** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [Feb 17, 2023, 7:21 PM GMT+1](https://github.com/uBlockOrigin/uBlock-issues/issues/2502#issuecomment-1435064974 "2023-02-17T18:21:03Z - Replied by Github Reply Comments"):
> Minimum supported version is now 79, see <https://github.com/gorhill/uBlock/commit/e23f0bd7d5d97c2b7fbcca96e77b26cb78b834d6>.
> 
> _Originally posted by @gorhill in https://github.com/uBlockOrigin/uBlock-issues/issues/2502#issuecomment-1435064974_

Well, the version in question is set to ff68 and above. So FF happily updated the addon.

**Comment by krystian3w** [comment]
Webpage have fallback compatibility filters but maybe incompatible with Firefox 68.x aka outdated:

![220658264-f92efa11-77c9-4f78-86b8-0827edcc780d](https://user-images.githubusercontent.com/35370833/220851288-f9fdbb3e-ab63-43cf-bf11-150c387a5d0d.png) |
---- |

If still fail maybe needed is consider deep hide that version in Moz://a addon store (last column of addon list version "off/delete" and in pop-up "off/disable") or delete from history at store (and backup only at github releases).
