### ISSUE TITLE
m3u-prune.js can't hook fetch api!

### ISSUE THREAD

**Issue by xinggsf** [uBlockOrigin/uBlock-issues#2508]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description
rule:
```
dandanzan.cf,nunuyingyuan.com##+js(m3u-prune, /^http/, /^https:\/\/vip\.lz-?cdn\d*\./)
dandanzan.cf,nunuyingyuan.com,ddys.buzz##+js(m3u-prune, /^http/, /^https:\/\/vip\.ffzy-(?:play|online)\d*\./)
```

fix m3u-prune.js (add ".clone()") :
```
realResponse.clone().text().then(text =>
```

### URL(s) where the issue occurs.
`https://dandanzan.cf/movie/16348`

select "量子资源" or "非凡资源" line

### Configuration

<details>

```yaml
uBlock Origin: 1.46.0
Chromium: 110
filterset (summary): 
  network: 10259
  cosmetic: 664
  scriptlet: 352
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    CHN-0: null
    easylist: null
    easyprivacy: null
    plowe-0: null
    ublock-badware: null
    ublock-filters: null
  added: 
    https://ghproxy.com/https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt: 231-0, 18h.8m
    https://github.com/hoshsadiq/adblock-nocoin-list/raw/master/nocoin-ublock.txt: 18-0, 1d.21h.9m
    https://raw.fastgit.org/xinggsf/Adblock-Plus-Rule/master/rule.txt: 1215-1, 1d.21h.9m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-18, 7d.16m
    https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/minority-mv.txt: 117-0, 18h.7m
  default: 
    user-filters: 158-0, never
    ublock-abuse: 79-5, 7d.23m
    ublock-privacy: 276-0, 7d.22m
    ublock-quick-fixes: 305-0, 22h.10m
    ublock-unbreak: 1905-0, 2d.21m
    urlhaus-1: 5937-0, 22h.9m
filterset (user): [array of 148 redacted]
trustedset: 
  added: [array of 18 redacted]
  removed: 
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 1 redacted]
  removed: 
    no-large-media: behind-the-scene false
hostRuleset: 
  added: [array of 74 redacted]
  removed: 
    behind-the-scene * * noop
    behind-the-scene * image noop
    behind-the-scene * 3p noop
    behind-the-scene * inline-script noop
    behind-the-scene * 1p-script noop
    behind-the-scene * 3p-script noop
    behind-the-scene * 3p-frame noop
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  allowGenericProceduralFilters: true
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 1083 ms (selfie)
  maxAssetCacheWait: 12 ms
```
</details>

**Comment by gorhill** [comment]
I don't understand what is the issue. The movie plays fine at `https://dandanzan.cf/movie/16348`, and there it doesn't play fine at `https://www.dandanzan10.top/dianying/379.html`, including without uBO. There is a suggestion to use `.clone()`, but I don't see the point since the scriptlet returns a new Response objects anyway.

**Comment by xinggsf** [comment]
> I don't understand what is the issue. The movie plays fine at `https://dandanzan.cf/movie/16348`, while it doesn't play fine at `https://www.dandanzan10.top/dianying/379.html`, including without uBO. There is a suggestion to use `.clone()`, but I don't see the point since the scriptlet returns a new Response object anyway.

`dandanzan.cf,nunuyingyuan.com,ddys.buzz##+js(m3u-prune, /^http/, /^https:\/\/vip\.ffzy-(?:play|online)\d*.+\.m3u8$/)`
m3u-prune.js handle .ts file, so much so that the video screen is stuck! The rule above are just fine

**Comment by xinggsf** [comment]
>  it doesn't play fine at https://www.dandanzan10.top/dianying/379.html

select "量子资源" line!
```
#EXT-X-DISCONTINUITY
#EXTINF:5.700,
0e70b5fb97a1o2926.ts
#EXTINF:3.333,
0e70b5fb97a1o2927.ts
#EXTINF:3.333,
0e70b5fb97a1o2928.ts
#EXTINF:6.667,
0e70b5fb97a1o2929.ts
#EXTINF:1.233,
0e70b5fb97a1o2930.ts
#EXT-X-DISCONTINUITY
```
Ad file（ts） names change frequently and do not start with an http address! How the rules should be written?

**Comment by ngoclong19** [comment]
It seems that some sites has changed their tactic.

Instead of one ad video hosted externally for the whole site, like below:
```
#EXTINF:4.167,
5ca71ab1b34000365.ts
#EXTINF:3.167,
5ca71ab1b34000366.ts
#EXT-X-DISCONTINUITY
#EXTINF:8.333,
https://aa.nguonphimmoi.com/ads/702_downtime/index0.ts
#EXTINF:7.033,
https://aa.nguonphimmoi.com/ads/702_downtime/index1.ts
#EXT-X-DISCONTINUITY
#EXTINF:6.000,
5ca71ab1b34000367.ts
```

Now they host ad video internally for each video, like below:
```
#EXTINF:2.458333,
78fe0440609000212.ts
#EXTINF:3.458333,
78fe0440609000213.ts
#EXT-X-DISCONTINUITY
#EXTINF:8.333333,
78fe044060901o636.ts
#EXTINF:7.033333,
78fe044060901o637.ts
#EXT-X-DISCONTINUITY
#EXTINF:4.166667,
78fe0440609000214.ts
```

The ad videos are between `#EXT-X-DISCONTINUITY` tag.
The former is easy to block, why the latter is hard if not impossible.

It may cost them a bit more storage, about extra 1 MB for each video.
But this is cheap to defeat an ad blocker.

**Comment by stephenhawk8054** [comment]
@ngoclong19 Can you give example link?

**Comment by gorhill** [comment]
The browser dev tools report `Status Code: 526` for the `m3u8` fetches at `https://www.dandanzan10.top/dianying/379.html`.

**Comment by ngoclong19** [comment]
> Can you give example link?

@stephenhawk8054, There is an ad video at 10:50, at this link https://mephimtv.cc/xem-phim/phong-chat-quy-am.
The video playlist is here https://aa.nguonphimmoi.com/20220319/4343_785b2fdf/1000k/hls/mixed.m3u8.

Before, I could block this ad video with the rule `mephimtv.cc##+js(m3u-prune, /ads, mixed.m3u8)`.
Now, for each video, the ad video file name will be different.
I currently have no idea to block these ads practically.

**Comment by gorhill** [comment]
I could reproduce the ad around 10-11. The ad is contained in `cc519865fce1o1019.ts` and above (`...1020.ts`, etc). The m3u8 file ends with `cc519865fce001018.ts`, so I am guessing the player code somewhere identify that the last segment in the list is _x_, and then assume that the ad to load is at _x_ + 1 and above, and loads a player with that information. I suspect the movie player is paused, then a new video widget is created with an code-assembled m3u file based on the movie. If we can find that specific code, maybe it can be defused, but this I need to confirm with more investigations, sort of tedious though.

**Comment by gorhill** [comment]
The following filter should work in 1.47.5b10+:

    mephimtv.cc##+js(m3u-prune, /#EXT-X-DISCONTINUITY.{1\,100}#EXT-X-DISCONTINUITY/gm, mixed.m3u8)
