### ISSUE TITLE
Whitelist websites for WebRTC on Firefox

### ISSUE THREAD

**Issue by amitkot** [uBlockOrigin/uBlock-issues#251]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When disabling WebRTC via uBlock Origin, when whitelisting a website the WebRTC remains blocked.
This makes is hard to use websites that require WebRTC, e.g. Google Hangout.

### A specific URL where the issue occurs
e.g. https://meet.google.com

### Steps to Reproduce
1. Install uBlock Origin
2. Configure > Settings > enable "Prevent WebRTC"
3. Browse to Google Hangout.
4. Whitelist the website.
5. Try to open a session

### Expected behavior:
Hangout session opens successfully.

### Actual behavior:
Session does not open, due to blocked WebRTC. To verify, you can alternatively whitelist https://www.privacytools.io/webrtc.html and see that WebRTC stays blocked.

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox Developer Edition 63.0b10
* Operating System and version: macOS 10.13.6

**Comment by gorhill** [comment]
"Prevent WebRTC" is a global setting, not a per-site setting, so what you ask is not possible.

See <https://github.com/gorhill/uBlock/issues/3225>.
