### ISSUE TITLE
Uncloak canonical names problem

### ISSUE THREAD

**Issue by iPriceless** [uBlockOrigin/uBlock-issues#2510]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ublock origin  settings - Uncloak canonical names ( it is not readable), this function is not visible and I cannot access it, as you can see in that image capture uploaded by me.

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#settings.html

### Steps to Reproduce

Hello, what should I do to have this option active in ublock origin and more precisely settings- "Uncloak canonical names", from what I have noticed in others on the browser they have this option active and I don't understand what the steps would be or the cause well said, which is why it is not active for me, I hope you can help me in this problem, thank you.

### Expected behavior

to be active, so that I can check it

### Actual behavior

ublock origin  settings - Uncloak canonical names not work.
![Capture](https://user-images.githubusercontent.com/126254755/221184952-fe70f55d-2e0a-4250-b495-1328cdab005d.PNG)

### uBO version

uBlock Origin 1.47.2

### Browser name and version

Chrome  Version 110.0.5481.178 (Official Build) (64-bit)

### Operating System and version

Windows 10 pro 64 bit

**Comment by gwarser** [comment]
Use Firefox.

**Comment by iPriceless** [comment]
I understand, thank you very much for the answer, have a nice day.
