### ISSUE TITLE
slow browser startup on Firefox (Ubuntu)

### ISSUE THREAD

**Issue by dev-stupid-codes** [uBlockOrigin/uBlock-issues#2513]
I have tried disabling [_"Suspend network activity until all filter lists are loaded"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded), but it doesn't help anyways...

```
uBlock Origin: 1.47.0
Firefox: 110
filterset (summary): 
  network: 84595
  cosmetic: 39079
  scriptlet: 17313
  html: 894
listset (total-discarded, last-updated): 
  default: 
    user-filters: 4-0, never
    ublock-filters: 33697-165, 6m
    ublock-badware: 4612-5, 6m
    ublock-privacy: 323-0, 6m
    ublock-abuse: 79-0, 6m
    ublock-unbreak: 1937-4, 6m
    ublock-quick-fixes: 322-0, 6m
    easylist: 63067-620, 6m
    easyprivacy: 30980-1769, 6m
    urlhaus-1: 5856-0, 6m
    plowe-0: 3749-2, 6m
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  autoUpdate: false
  suspendUntilListsAreLoaded: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 223 ms (selfie)
  maxAssetCacheWait: 133 ms
  unsuspendAfter: 67 ms

```

**Comment by dev-stupid-codes** [comment]
I'm sure it's an uBlock issue, since I can only reproduce the issue when uBlock is enabled.

After the very first successful startup (pages loading successfully), if I'd go and open Firefox: the issue won't show up (even after system reboot).

**Comment by iam-py-test** [comment]
Sorry, but this probably falls under:
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from the [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/) and a fully substantiated analysis supporting the claim.

**Comment by gwarser** [comment]
Do you have any other add-ons which can interfere? Because uBO is ready in fifth of a second:

      allReadyAfter: 223 ms (selfie)

>Sorry, but this probably falls under:

¯\\\_(ツ)\_/¯

**Comment by dev-stupid-codes** [comment]
@gwarser I do have another addons, but the issue only ever goes away if I disable ublock origin?

**Comment by gwarser** [comment]
> @gwarser I do have another addons, but the issue only ever goes away if I disable ublock origin?

As I recall, it was a common issue with a crypto wallet(?) add-on with fox face on the icon(?)

**Comment by dev-stupid-codes** [comment]
[Firefox 2023-03-01 12.48 profile.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/10863658/Firefox.2023-03-01.12.48.profile.json.gz)
I do have Metamask, but the issue is something that dates from before I started using Metamask. Also, I've got the same issue with Firefox for Windows and there's no Metamask installed on that browser.

**Comment by gorhill** [comment]
Metamask extension is your issue.

**Comment by gwarser** [comment]
https://github.com/MetaMask/metamask-extension/issues/13163

**Comment by dev-stupid-codes** [comment]
Why would you ask for the profile if you won't event look at it? You didn't even read what I've said about having another OS with uBlock being the only extension installed (and facing the same issue).

**I know it's uBlock** since it got to the point where toggling to enable or disable it (repeatedly and quickly) will get web pages loading/stuck.

**Comment by gwarser** [comment]
> Why would you ask for the profile if you won't event look at it?

I'm pretty sure we both looked at the profile, it's just what it shows after opening is that Metamask is using 33% of the processor time.

**Comment by gwarser** [comment]
***

Looking at the "jank" part (red line from the start to the middle of the screen), Metamask is using 59% of resources and uBO is not doing anything here (no samples). uBO is visible only in the other part of the timeline. 

>You didn't even read what I've said about having another OS with uBlock being the only extension installed (and facing the same issue).

Maybe it's a different issue? Can you share profiling from this system?

>I know it's uBlock since it got to the point where toggling to enable or disable it (repeatedly and quickly) will get web pages loaded/stuck.

Yes, uBO instruct the browser to not allow any connection until uBO is running and have all filters loaded and ready. Sadly, something is preventing filter list to be loaded from storage.

**Comment by gorhill** [comment]
> Why would you ask for the profile if you won't event look at it?

How did you come to the conclusion I didn't look at it? At this point, it seems you prefer to rely on what you believe is the issue rather than our fiding, so I suggest you find another blocker if you do not trust our findings.
