### ISSUE TITLE
Classification of behind-the-scene requests in 1.47.0+?

### ISSUE THREAD

**Issue by Jee-Hex** [uBlockOrigin/uBlock-issues#2515]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Requests previously classified as behind-the-scene in the logger are now (potentially) classified as first-party requests and have a partyness of `0,1`.

### A specific URL where the issue occurs.

_N/A_

### Steps to Reproduce

This is just an example because I don't have a way to reliably trigger behind-the-scene requests other than closing a tab at the right moment since uBO became a WebExtension.

1. uBO in hard mode.
2. Install [CSS Exfil Protection](https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/) from AMO.
3. Open the uBO logger.
4. Visit `https://www.theguardian.com/`.

### Expected behavior

Two css requests to `https://assets.guim.co.uk/stylesheets/...` that were blocked by the rule `* * 3p block`, and subsequent matching xhr requests to the same urls via behind-the-scene (https://github.com/mlgualtieri/CSS-Exfil-Protection/issues/29#issuecomment-696126963). The partyness of the latter should be `(0,3) behind-the-scene ⇒ guim.co.uk` according to the logger in 1.46.0.

### Actual behavior

Two css requests to `https://assets.guim.co.uk/stylesheets/...` were blocked by the rule `* * 3p block`, but `assets.guim.co.uk` became the context for subsequent matching xhr requests. The partyness of the latter is also reported as `(0,1) guim.co.uk ⇒ guim.co.uk` in the logger in 1.47.0.

Meanwhile the context and partyness filter updates (which used to be considered behind-the-scene) are correctly 
identified as `[uBO-uuid].moz-extension-scheme` and `0,3` respectively.

### uBO version

1.47.0

### Browser name and version

Firefox 110

### Operating System and version

Windows 10

**Comment by Jee-Hex** [comment]
Apologies. I forgot to mention that you will need to select _All_ in the drop-down page selector.

**Comment by gorhill** [comment]
Selecting _All_ changes nothing, and anyways tabless network requests are always reported in the logger regardless of the drop down selector.

**Comment by Jee-Hex** [comment]
I have no idea why it's not reproducing on your end. For some reason it didn't happen on first try, but I can clearly reproduce this with the STR provided on a vanilla Nightly profile.

**Comment by gorhill** [comment]
Ok I was filtering the logger output to see `css/font`. The problematic requests are `xhr` though, hence they were filtered out from being reported in the logger.

**Comment by gorhill** [comment]
Should be fixed in the [latest dev build](https://github.com/gorhill/uBlock/releases), and I will include the fix in the next stable revision if all work as expected.

**Comment by gwarser** [comment]
It seems this was also related: https://github.com/uBlockOrigin/uAssets/issues/11128#issuecomment-1432865039
