### ISSUE TITLE
1.47.2 seems to be working with new profile on Firefox 110.0.1

### ISSUE THREAD

**Issue by klint** [uBlockOrigin/uBlock-issues#2519]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have created a new profile in Firefox 110.0.1, installed uBlockO 1.47.2
But whether I activate UBO or not, ads are always being displayed.

For instance on www.liberation.fr.

It's ok on my old existing profile though.

### A specific URL where the issue occurs.

www.liberation.fr

### Steps to Reproduce

1. Create a new profile in Firefox 110.0.1
2. Install uBlockO 1.47.2 (activated)
3. Go to www.liberation.fr

### Expected behavior

ads should not display

### Actual behavior

Ads are being displayed

### uBO version

1.47.2

### Browser name and version

Firefox 110.0.1

### Operating System and version

Windows 10

**Comment by garry-ut99** [comment]
That is a french website, do you have  `FRA: AdGuard Français ` filter list enabled, otherwise ads appear, for french users that filter list is enabled by default, but for non-french users need to be enabled manually.

**Comment by gwarser** [comment]
Even without FRA filter, I see ads placeholders at most.

**Comment by garry-ut99** [comment]
Yes, only ad placeholders, but some users refer to ad placeholders as ads, additionally given that there are no ads here, only placeholders, thus in such case I assumed that maybe ad placeholders is what the OP meant, thus for simplicity's sake I adopted his semantics when I wrote him back, but of course the other possibility is still possible: that he meant ads and not ad placeholders.

**Comment by klint** [comment]
The French filter is activated actually. And while my old profile shows no placeholder at all on that page with ubo activated, the new one displays an empty placeholder.

**Comment by klint** [comment]
Ok, I can see what is going wrong. I said that I have subscribed to the French list, and that is true.
Problem is, the link to this list seems to be broken for 37 days now. As well as other languages. So it is likely an issue with my corporate proxy, because on my Android phone, the link is reachable seemlessly.
I will double check on a private PC next week to confirm my doubts.
Thanks

**Comment by gorhill** [comment]
> Share troubleshooting information

**Comment by klint** [comment]
> > Share troubleshooting information

Sorry, here it is, with the link to FRA still unreachable for me:
uBlock Origin: 1.47.2
Firefox: 110
filterset (summary): 
  network: 104954
  cosmetic: 47695
  scriptlet: 17146
  html: 889
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 32898-57, 1m
    ublock-badware: 4622-5, 1m
    ublock-privacy: 332-0, 1m
    ublock-abuse: 79-0, 1m
    ublock-unbreak: 1945-18, 1m
    easylist: 63278-789, 1m
    easyprivacy: 31000-1769, 1m
    urlhaus-1: 6250-0, 1m
    plowe-0: 3750-2, 1m
    FRA-0: 30039-503, never
    ublock-quick-fixes: 341-0, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 9412 ms (selfie)
  maxAssetCacheWait: 1828 ms


THanks

**Comment by krystian3w** [comment]
29536 filters was detected but when corporation proxy allowed download file from `adtidy.org`? On fresh profile you are:

> `FRA-0: 0-0, never`


?

---


Maybe needed is hide AdGuard links under [Cloudflare Pages](https://pages.cloudflare.com/), [GitHub Pages](https://pages.github.com/), [jsDelivr](https://www.jsdelivr.com/), [Statically](https://statically.io/)?

Also risk is use raw link from FiltersRegistry (like "https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_16_French/filter.txt") as long have only AdGuard syntax (like `#%#//scriptlet`, incompatible redirect resources names, `!+ PLATFORM(`/` !+ NOT_PLATFORM(` inline condition to disable filter for e.g `env_ublock`).

**Comment by garry-ut99** [comment]
> Sorry, here it is, with the link to FRA still unreachable for me:

This is the link to FRA list I've copy & pasted from uBO:
`https://filters.adtidy.org/extension/ublock/filters/16.txt?_=46761`
If the link still doesn't load for you in your browser with uBO disabled, it's an issue not caused by uBO.

**Comment by krystian3w** [comment]
He can get other numbers in fake parameter `_`. 

Then it would be nice to know the mechanism by which the proxy rejects URLs with digits.

**Comment by garry-ut99** [comment]
It depends of what his corporation proxy is:
- if a host file, then can be blocked only by a domain part, for example:
`filters.adtidy.org` or `adtidy.org` or `*.adtidy.org` (if supporting wildards `*`)
even with `regex` support, most likely still limited to a domain part
- if his corpo proxy is so advanced that can filter the whole URL / path, 
then it might be any part of the path, for example:
  - anything in  `/extension/ublock/filters/`
  - if not, then something in `16.txt?_=46761` 
  where the number at the end is randomly generated by uBO

**Comment by gorhill** [comment]
> here it is, with the link to FRA still unreachable for me

You will have to figure out why. Also, provide the troubleshooting information for the page for which you have issue. See <https://www.youtube.com/watch?v=5z0rQa1Q1yc>.
