### ISSUE TITLE
None of the test in ABP popup test page is working for cached page

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#252]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

We have link to it in wiki https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

>No popups for the current site: [Try it](http://jessehakanen.net/adblockpluspopupaddon/test.html)

No "No popups" switch or `||google.com^$popup` is working

### A specific URL where the issue occurs

http://jessehakanen.net/adblockpluspopupaddon/test.html

### Steps to Reproduce

~~1. add `||google.com^$popup` or enable "No popups" switch
2. open http://jessehakanen.net/adblockpluspopupaddon/test.html
3. click on popup tests~~ Edit: see comments.

### Expected behavior:

- At least some popups should be closed. ABP closes most of them, only 6 and 7 does not work.

or

- wiki should be fixed

### Actual behavior:

Nothing is blocked.

### Your environment

* uBlock Origin version: 1.17.0, 1.17.1b1
* Browser Name and version: Firefox Nightly (with uBO dev), Firefox 62.0.2 with ABP and uBO stable
* Operating System and version: Mint 18.3

### Notes

~~I think this may be related https://old.reddit.com/r/firefox/comments/9koeic/addon_that_blocks_popups_that_open_in_new_window/
(caused me to check)~~

**Comment by gwarser** [comment]
One moment - I just tried again and it's working fine - WTF? Will test and reopen eventually.

**Comment by gwarser** [comment]
:man_facepalming: cache!


1. open http://jessehakanen.net/adblockpluspopupaddon/test.html
1. click on popup tests to load google into cache
1. add ||google.com^$popup or enable "No popups" switch
1. click on popup tests again
1. popups not blocked because loaded from cache

**Comment by gorhill** [comment]
All the links have their `href` set to `http://www.google.com/`, hence uBO considers them to be legitimate -- I suppose I cared about the test before I added false positive mitigation to uBO.

For instance, disable javascript for the page, and try the test with ABP: you won't be able to right-click-open a page for none of the link, and this is the kind of issue which I had to solve for uBO, which is the false positive mitigation.

**Comment by gorhill** [comment]
> I think this may be related https://old.reddit.com/r/firefox/comments/9koeic/addon_that_blocks_popups_that_open_in_new_window/

The poster didn't provide any specific cases, so it can't be taken seriously.

**Comment by gwarser** [comment]
Yeah, only STR from comment is worth checking (blocking not work for cached pages)

**Comment by gorhill** [comment]
The cache is irrelevant on my side -- the new tab is not closed because of false positive mitigation in uBO.

**Comment by gorhill** [comment]
I can reproduce the popup closing right after launching Chromium. The popup stops closing if I load `https://www.google.com/` in a separate tab and close it. I will step into the code to find out why, it's as if uBO is not being notified that the final URL is `https://www.google.com/`.

**Comment by gorhill** [comment]
Ok, uBO leaves out the scheme part when testing for legitimate URLs -- so it should never close that new tab in the current case.

I investigated why this happens when the cache is cleared, and uBO in that case sees that the new tab is navigated to `https://www.google.com/?gws_rd=ssl`, which does not happen when the page is loaded from the cache. I suspect it's the browser loading from memory cache, and in such case uBO's listeners are probably bypassed, I don't see that URL when the Google page is present in the cache.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Per-site-switches/_compare/039ef392bbf9be48c9fbb874e32a4ef2fb4369c5

**Comment by gwarser** [comment]
We have our own test page http://raymondhill.net/ublock/popup.html
