### ISSUE TITLE
ProtonVPN Extension Does Not Work With uBlock Origin Enabled. Leaks DNS Requests

### ISSUE THREAD

**Issue by TheNightRider12** [uBlockOrigin/uBlock-issues#2520]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ProtonVPN today released their VPN Extension. I installed it. Went to ipleak[.].et and tested things. My IP address was the one of my ISP so I restarted my browser and tried it again. That issue was fixed. My IP address was now one of the VPN's. I then noticed another problem. My DNS Addresses were the one of my ISP and not one of the VPN's. I played around. I made a new browser profile and JUST installed ProtonVPN. Everything worked fine. So then I installed uBO, and did not change anything other than to update the filter lists, then that is when I noticed that my DNS addressed on ipleak[.]net were the ones of my ISP. I disabled uBO, then went and tried IPLeak again. When I did that, my DNS addresses were the ones to the VPN. 

### A specific URL where the issue occurs.

https://ipleak.net/

### Steps to Reproduce

1. Install the ProtonVPN extension
2. Install uBO.
3. Restart your browser (that is due to ProtonVPN Extension not uBO)
4. Go to ipleak[.]net
5. Observe the DNS addresses. 
6. 

### Expected behavior

With uBO installed, my DNS Addresses shown on ipleak[.]net should be ones of my VPN provider. Not my ISPs

### Actual behavior

When I went to ipleak[.]net with uBO Installed, the DNS Addresses that got detected were the ones of my ISP, not my VPN. 

### uBO version

1.47.2

### Browser name and version

Firefox Nightly. 112.0a1

### Operating System and version

Windows 11. 22H2

**Comment by garry-ut99** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+in%3Atitle+dns+

**Comment by iam-py-test** [comment]
Maybe a duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1743.

**Comment by TheNightRider12** [comment]
Yes. This comment fixed the issue for me:
https://github.com/uBlockOrigin/uBlock-issues/issues/1743#issuecomment-932255521
Disabling "Uncloak canonical names"
Thank you.

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1743
