### ISSUE TITLE
Outlook/Hotmail Inbox Ads Now Showing, only in Chrome so far

### ISSUE THREAD

**Issue by FroobTubeLIVE** [uBlockOrigin/uBlock-issues#2525]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

(Browser: Google Chrome)
Microsoft ads promoting nothing more than a premium subscription service to go "ad-free" now appears in my Hotmail inbox. In addition to this, sidebar ads also show up when opening Hotmail for the first time in a day. The inbox ad is also something different initially (some other product or service), but when refreshing a few times or going back to open my emails at some point again, the inbox ad is changed to the aforementioned Microsoft ad, but the sidebar is gone.
![chrome - inbox ad](https://user-images.githubusercontent.com/121452612/222916598-4e7aceae-6a51-4e49-b5e8-55394c8f5238.png)

Unfortunately it would seem that this is Google Chrome-specific, as I have uBlock on 2 other browsers—LibreWolf, and Waterfox—all 3 browsers with default settings for the extension, and Chrome is the only one of these 3 that still lets these ads slip through.

### A specific URL where the issue occurs.

https://outlook.live.com/mail/0/

### Steps to Reproduce

1. Turn on computer.
2. Open Hotmail on Google Chrome after desktop has loaded.
3.  If sidebar and inbox ad are both present, refresh page
     a) If both ads are still present, refresh again
     b) If both ads are STILL present, close tab, wait 5 seconds, then open a new tab (not recovering the tab with Ctrl + Shift + T), 
         and open Hotmail again
     c) If ads are still present, close the window completely, wait 10 seconds, and open a new window, then open Hotmail once more
4. By this point, the sidebar ad should be gone, but the inbox ad still persists.

### Expected behavior

The ad within my inbox should not be shown at all from the very beginning, and should also not take up any space as some sort of "blank"/deleted element. The sidebar ad should also not show at all, and should always look like the first image attached.

### Actual behavior

Inbox ad and sidebar both load from the beginning, and the inbox ad persists no matter what. And time doesn't do anything; waiting multiple hours on end for the system to "load completely" does nothing.

With uBlock disabled, or with Hotmail opened for the first time in a day, as mentioned before, the inbox ad is something else. But when using uBlock, it changes to Microsoft shoving their crap down my throat.
![chrome ad - ublock disabled](https://user-images.githubusercontent.com/121452612/222917223-d0db4dcf-6f9d-4a82-85cf-9ca7aa8e81d6.png)

### uBO version

1.47.2

### Browser name and version

Google Chrome, 110.0.5481.178, 64-Bit

### Operating System and version

Windows 10 Pro, 20H2, 19042.1466, 64-Bit

**Comment by gorhill** [comment]
This is an issue with Chromium-based browsers, see <https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch>. The delay before uBO is ready at launch has gotten worst with version 110, this is out of control of uBO, it's a browser issue.

**Comment by FroobTubeLIVE** [comment]
Damn alright well thanks for getting back to me so quick

**Comment by FroobTubeLIVE** [comment]
> This is an issue with Chromium-based browsers, see https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch. The delay before uBO is ready at launch has gotten worst with version 110, this is out of control of uBO, it's a browser issue.
> 
> Go to _Support_ pane in uBO's dashboard and see the following troubleshooting information:
> 
> ```
> supportStats: 
>   allReadyAfter: 3290 ms
>   maxAssetCacheWait: 167 ms
> ```
> 
> So on my side it took over 3s for uBO to be ready at browser launch. Your numbers might be higher.
> 
> See [uBlockOrigin/uAssets#16939](https://github.com/uBlockOrigin/uAssets/discussions/16939).

So I checked those settings you mentioned and these are my numbers:
supportStats: 
  allReadyAfter: 2810 ms (selfie)
  maxAssetCacheWait: 383 ms

**Comment by stephenhawk8054** [comment]
The sidebar ads/anti-adb is hidden in ublock filters - annoyances list. Can you enable it and test again?

**Comment by FroobTubeLIVE** [comment]
> 

I've had "uBlock filters - Annoyances" enabled since yesterday I believe, but even before, when it takes up space in the way that it does in the first image, I really don't mind. The only thing I mind is the forced inbox ads.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/17058 https://github.com/uBlockOrigin/uAssets/issues/17056

**Comment by d9j** [comment]
issue not resolved . happens again. unlcear why it's been closed

**Comment by FroobTubeLIVE** [comment]
IMPORTANT UPDATE (and also we may all feel like idiots after you read this):

I've switched browsers to LibreWolf for a few reasons, and the inbox ad became an issue recently. However the solution was easier than I had ever dreamed; just right-click the element, click uBlock's "Block Element" option, then make sure you're covering the whole area of what it is you're trying to block, and click the "Create" button in the small window that appears.

EZ CLAP BOIZ

**Comment by krystian3w** [comment]
The problem as the filter has no constancy between browsers/devices/accounts - rather 100 million users will be disappointed to click that every 2 weeks or so as the filter dies.
