### ISSUE TITLE
Outdated doc about managed storage for Firefox

### ISSUE THREAD

**Issue by linsui** [uBlockOrigin/uBlock-issues#2527]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

According to https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin,

> Now, the value for adminSettings must be a plain string which means we need to encode the above text into a string using JSON.stringify.

However, I found that it does work with a json object, no matter in the policy.json or the managed-storage. The policy example in https://github.com/mozilla/policy-templates#3rdparty uses an object. And in your code https://github.com/gorhill/uBlock/blob/2e6cc8a36a35c1893cf2151340216c4920995028/src/js/storage.js#L1318 it's also read as an object. I tested both cases and it works well for me.

### A specific URL where the issue occurs.

https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

### Steps to Reproduce

For policy, test with the example in https://github.com/mozilla/policy-templates#3rdparty. Add this policy and restart Firefox.

For managed-storage, something like this can be used

```json
{
    "name": "uBlock0@raymondhill.net",
    "description": "This is ignored but must exist",
    "type": "storage",
    "data": {
        "adminSettings": {
            "userSettings": {
                "colorBlindFriendly": true
            }
        }
    }
}
```

Add this and re-enable uBlock.

### Expected behavior

The doc is updated and point out the setting doesn't need to be a json string.

### Actual behavior

The doc is outdated.

### uBO version

1.47.3.6

### Browser name and version

Firefox 110

### Operating System and version

NixOS unstable

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/4687c60bf9cec5b68e5a007d740af93f4119a79e#diff-bb0a23b7c8c08b99549300d4571ee50f0fcbb877eb8b84fb2d4c4c3ec1ffc1c4R1147-R1148 ? Hmmm...

If you have idea what you are doing - fix it here: https://github.com/uBlockOrigin/uBlock-issues/wiki/Deploying-uBlock-Origin

**Comment by gorhill** [comment]
> Hmmm...

Yeah, long time ago, forgot about this.

**Comment by linsui** [comment]
I'd like to fix it, but I'm not sure what I should do. Since the json object is supported, the doc about the string setting should be removed. Since I can set everything in the adminSettings easily, other settings become useless. It's much easier to set the userSettings with a json object instead of a list of key/value pairs. I'm not sure if this works on other browsers though.

**Comment by gorhill** [comment]
> other settings become useless

Not really, you can't get `toAdd` functionality with `adminSettings`. `adminSettings` was introduced to have a quick way for administrators to deploy uBO, there was not much back-and-forth going on about the real world needs, so I had to go with a blunt way to set any setting. `toAdd`/`toOverwrite` are more granular and these should be the preferred way forward. If there is something missing with these, I would like to know what.

**Comment by linsui** [comment]
Ah, then I thought I should simply replace the json string part.

**Comment by linsui** [comment]
I updated the wiki. I only updated the firefox part.
