### ISSUE TITLE
uBlock Origin no longer works

### ISSUE THREAD

**Issue by Giampy61** [uBlockOrigin/uBlock-issues#253]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Everything worked perfectly until yesterday morning. Since yesterday evening uBlock Origin no longer works.
First, if I click the icon the usual window appears but its left side is empty and white.
Second, uBlock Origin no longer updates the filters automatically. They are all marked as "obsolete". If I delete the cache and I try a manually update, near every item I see a little gray wheel that continuously turns but nothing happens.

### A specific URL where the issue occurs

All

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Opera 34
* Operating System and version: Windows XP sp.3

**Comment by gorhill** [comment]
I forgot to update the `minimum_opera_version` in the manifest, uBO is compatible with Opera 38 ([June 2016](https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser#Opera_2016)) or above.
