### ISSUE TITLE
[Logger] Source code viewer button is hidden behind scrollbar in Firefox

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2530]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In the recent versions, Firefox hides the scrollbar by default until you hover over it.
The previous behavior where the scrollbar is visible all the time can be enabled using `about:config`.

https://askvg.com/tip-restore-full-classic-scrollbars-in-mozilla-firefox-on-windows-11/

### A specific URL where the issue occurs.

The logger

### Steps to Reproduce

1. Go to `about:config`.
2. Set `widget.non-native-theme.scrollbar.style` to `1`.
3. Open the logger.
4. Go to `reddit.com` and wait until the list of requests become large enough to be scroll-able.

### Expected behavior

The "Source code viewer" button is hidden under the scrollbar.
![image](https://user-images.githubusercontent.com/17685483/223804289-7883fb27-9a24-42fc-9403-f5818fb36fb5.png)

### Actual behavior

The "Source code viewer" button shouldn't be hidden under the scrollbar.

### uBO version

1.47.5.1 dev version

### Browser name and version

Firefox 110

### Operating System and version

Fedora KDE 37

**Comment by gorhill** [comment]
I am going to make the link button wider, not much else I can do since scrollbar width is highly dependent on OS/browser and it's not info available without using some JS tricks, and as far as I know not available at all with overlayed scrollbars.

**Comment by krystian3w** [comment]
Maybe force `scrollbar-gutter: stable;` cover Firefox 97+ and Chromium 94+ (84+ if we enable "experimentall support platform").

But Firefox 79-96 may need disable gtk scrollbars.
