### ISSUE TITLE
why not let them play games for at home if they do online?

### ISSUE THREAD

**Issue by hacckerrj** [uBlockOrigin/uBlock-issues#2532]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

d

### A specific URL where the issue occurs.

d

### Steps to Reproduce

d

### Expected behavior

d

### Actual behavior

d

### Configuration

d

**Comment by gorhill** [comment]
I blocked this user.
