### ISSUE TITLE
disable adblock on tr.motorsport.com

### ISSUE THREAD

**Issue by sanigerson** [uBlockOrigin/uBlock-issues#2535]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Dedects ublock and site doesn't contunie.

### A specific URL where the issue occurs.

https://tr.motorsport.com/f1/news/horner-aston-martin-hakkinda-eski-aracimizin-hala-iyi-calistigini-gormek-guzel/10442140/

### Steps to Reproduce

1. Enter site.
2. See "disable adblock"

### Expected behavior

See site with ublock enabled.

### Actual behavior

can't proceed, saw "disable adblock"

### Configuration

[ublock-yedeğim_2023-03-11_02.24.34.txt](https://github.com/uBlockOrigin/uBlock-issues/files/10946834/ublock-yedegim_2023-03-11_02.24.34.txt)

**Comment by gorhill** [comment]
Use the [report button in the popup panel](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website) to report website issues.
