### ISSUE TITLE
Filter list boxes all unchecked in chrome at startup in windows 10 pro

### ISSUE THREAD

**Issue by fire01234** [uBlockOrigin/uBlock-issues#2536]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This only happened recently and only in chrome in windows 10.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1)boot up desktop
2)open chrome and search
3) ads everywhere
4) open ublock origin and find out all filter list boxes unchecked

### Expected behavior

filter list boxes settings should be saved.

### Actual behavior

all filter list boxes unchecked every time i boot up PC.

### uBO version

1.47.4

### Browser name and version

chrome

### Operating System and version

windows 10 pro

**Comment by ghajini** [comment]
essentially https://github.com/uBlockOrigin/uBlock-issues/issues/2136
but now it happens with **_chrome_** also

**Comment by gwarser** [comment]
Likely this: https://github.com/uBlockOrigin/uAssets/discussions/16939

@fire01234 can you share Troubleshooting information from uBO settings "Support" tab? Or even just the `allReadyAfter` value.

**Comment by u-RraaLL** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/11mnu5y/my_filter_lists_gets_reset_after_restart/

**Comment by fire01234** [comment]
@gwarser
uBlock Origin: 1.47.4
Chromium: 110
filterset (summary): 
  network: 144407
  cosmetic: 121931
  scriptlet: 19145
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    user-filters: null
    easyprivacy: null
  added: 
    CHN-0: 27744-104, 7h.10m
    adguard-spyware-url: 939-2, 7h.9m
    block-lan: 44-0, 3d.1h.29m
    curben-phishing: 51868-0, 7h.5m
    curben-pup: 196-0, 7h.4m
    dpollock-0: 11336-10, 9d.25m
    fanboy-annoyance: 81905-197, 3m
    fanboy-cookiemonster: 46078-46078, 3m
    fanboy-social: 22236-22236, 1d.21h.39m
    fanboy-thirdparty_social: 68-19, 3d.1h.29m
  default: 
    easylist: 63558-329, 2d.21h.11m
    plowe-0: 3751-754, 9d.24m
    ublock-abuse: 78-0, 9d.24m
    ublock-badware: 4681-132, 7h.8m
    ublock-filters: 31967-112, 7h.7m
    ublock-privacy: 287-10, 9d.24m
    ublock-quick-fixes: 363-19, 7h.3m
    ublock-unbreak: 1920-15, 7h.6m
    urlhaus-1: 6629-2, 7h.2m
filterset (user): [empty]
trustedset: 
  removed: 
    chrome-scheme
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5816 ms (selfie)
  maxAssetCacheWait: 681 ms

**Comment by fire01234** [comment]
@u-RraaLL maybe I should let it load before searching but why is this happening ? this has never been a proiblem begore.

**Comment by gwarser** [comment]
You can try "Suspend network activity until all filter lists are loaded" on Filter lists tab - it should reload active page when uBO is fully loaded.

I can simulate this in VM. When disk is busy, I can easily see unchecked lists after opening uBO or restoring session with it. I can even launch YT, see ads, and then launch uBO Dashboard and see the issue. Interestingly, it fixed itself automatically (when uBO is ready) for a ~dozen restarts (even for slow ones, like 30s slow!), but eventually stopped, and manual refresh of the Dashboard is now needed to see checkboxes correctly selected.

**Comment by ghajini** [comment]
hi @gwarser it happened with me now on firefox android & i inspected ubo via usb debugging found errors & also recorded firefox profile,should i share here?

**Comment by gwarser** [comment]
@ghajini your issue is #2136, so share it there.

**Comment by gorhill** [comment]
> maybe I should let it load before searching but why is this happening

Because something changed in Chromium 110, see <https://github.com/uBlockOrigin/uAssets/discussions/16939>. It's definitely Chromium, because if you start the browser without uBO, then after a few seconds you enable uBO, it takes a fraction of seconds for uBO to be ready, while it takes multiple seconds when uBO is already enabled at launch.

**Comment by JohnPlanetary** [comment]
Same problem here.
I need to wait for the uo icon to go from "red" to "gray" when I first start the Google Chrome browser after I start a fresh Windows session from the computer completely turn off. Only then it will be ok.
These never happen before these recent 110 version (now on 111 version at the time of these writing).

**Comment by gorhill** [comment]
I don't even know if it's worth reporting to Chromium given that eventually this will be all pointless given MV2 is deprecated. The current issue could even be a side effect of Chromium code being refactored for MV3. Maybe someone will find time to bisect the to find the specific code change between 109-110 which is causing this issue. For now the best I can do is to make it more visually obvious that uBO is not ready at launch -- hence the yellowish toolbar icon.

**Comment by gorhill** [comment]
I will assume it's fixed in 1.48.0.

**Comment by Yuki2718** [comment]
Not all, but I noticed My filters was unchecked after updating to 1.58.1b11 in one of my Firefox profiles using dev build. I remember I saw such complaints somewhere.
