### ISSUE TITLE
Toggle filter groups by domain/site

### ISSUE THREAD

**Issue by Madis0** [uBlockOrigin/uBlock-issues#254]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin has several toggles to adjust domain or site-based behaviour, such as "disable everything", "disable cosmetic filtering", "disable JavaScript". 
When a user decides they want to disable uBlock Origin for the site completely, it is usually due to one small issue, like lacking a specific anti-anti-adblock filter or wanting to support the site by showing ads. 

However, that also means they instantly give up their privacy for the scope, and let all external requests in. Surely there are more specific options available in uBlock Origin, such as zapping/picking an annoying element (anti-adblock), reporting an issue to uAssets or filter maintainers or writing an exclusion filter (allow ads), but with the wide range of users you have, you can't expect everyone to do that.

Here's where my idea comes in: what if uBlock Origin also had a way to disable filters by category? To keep things simple, there would only be the default categories available:

- Built-in
- Ads
- Privacy
- Malware domains
- Annoyances
- Multipurpose
- Regions, languages
- Custom

They could be represented by icons and have a badge according to how many filters are enabled for the site. However, they might need some kind of descriptive header to prevent confusing the icons with the feature toggles (as noted in the first sentence).

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior:

N/A

### Actual behavior:

N/A

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: irrelevant
* Operating System and version: irrelevant

**Comment by Madis0** [comment]
Apparently it was suggested already after all: #91

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/91
