### ISSUE TITLE
Filter editor error when trying to toggle filter with spaces on/off

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlockOrigin/uBlock-issues#2540]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The filter editor exhibits serious problems when trying to toggle some filter lines.

### A specific URL where the issue occurs.

https://www.example.com

### Steps to Reproduce

1. Go to the `My Filters` pane.
2. Add the following filter, which includes 6 spaces before the exclamation point:
```
      ! ||example.com^$image
```
3. Press the `Tab` key on your keyboard.

### Expected behavior

The filter to enable/disable.

### Actual behavior

Cursor disappears.  Focus goes elsewhere.

In this test environment, recovery is pretty simple.  In a real world environment, the user will naturally start using all the arrow keys.  This can make it look like all custom filters have been deleted.  They haven't actually been deleted, but they do disappear from the screen.

### uBO version

1.47.4

### Browser name and version

Firefox 110.0.1

### Operating System and version

Linux

**Comment by u-RraaLL** [comment]
5 spaces, `     example.com^$image` shows. Adding 6th space doesn't work (6th space doesn't display). Adding 7th space jumps to 7 spaces. Works in both directions - can't backspace to 6th space, only 7th and 5th.

**Comment by gorhill** [comment]
Just pasting `      ||example.com^$image` in the editor cause an issue, there is an exception being thrown.

**Comment by gorhill** [comment]
I am trying to find out whether it's an emergency fix or not.

Basically, when the number of characters after the option anchor `$` is less than the number of leading whitespaces, the parsing would break, and the filter will be parsed as just a pattern without option, i.e. `      ||example.com^$image` would be parsed `||example.com^` (and the editor would break), causing a filter to block more than intended.

I feel like this is unlikely to happen and for now I will consider this not an emergency fix, since so far I am not aware of any reports of filters blocking more than they should.

**Comment by Gitoffthelawn** [comment]
@gorhill
I can appreciate your conundrum in trying to decide whether or not to make this an emergency fix.  It's a tough choice.

Thank you for your explanation of the exact situation that will cause the bug.  I have since tested that uBO does not correctly handle `    ||example.com^$xhr` (4 leading spaces), which matches your explanation perfectly.  The filter editor has issues allowing the user to even enter the filter.

**Comment by krystian3w** [comment]
AlleBlock uses "these" spaces:

https://github.com/maciejtarmas/AlleBlock/blob/147a0cb1605ccfcdbfb4041ab5666d67847ddda8/alleblock.txt#L121-L152

AdGuard trim in post production (as long list is in FiltersRegistry - supposedly in April or May, the developer will try check what filters no longer work or add new ones).

**Comment by krystian3w** [comment]
I have better example from my home PC:

```adb
       partnerid=$removeparam=|partnerid,domain=al.to|combat|x-kom.pl
            sm12=$removeparam=|sm12,domain=al.to|combat|x-kom.pl
             MTc=$removeparam=|MTc,domain=al.to|combat|x-kom.pl
              ts=$removeparam=|ts,domain=al.to|combat|x-kom.pl
           token=$removeparam=|token,domain=al.to|combat|x-kom.pl
```

the longest have 14 spaces.
