### ISSUE TITLE
Element picker does not cancel element zapper (and vice versa)

### ISSUE THREAD

**Issue by umbralOptimatum** [uBlockOrigin/uBlock-issues#2550]
### Prerequisites

- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Entering element picker mode and then pressing the button for element zapper mode does not switch to element zapper mode, and vice versa.

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps to Reproduce

1. Open the extension menu
2. Click the element zapper button, entering element zapper mode
3. Without clicking anywhere on the webpage to zap an element, open the extension menu again and click the element picker button

### Expected behavior

I expect clicking on the element picker or zapper to enter the respective mode, even if in the other mode already.

### Actual behavior

If already in element picker or zapper mode, attempting to enter the other mode does not cancel the first mode.

### Configuration

uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 85473
  cosmetic: 39246
  scriptlet: 17355
  html: 902
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 33640-89, never
    ublock-badware: 4615-0, never
    ublock-privacy: 336-0, never
    ublock-abuse: 78-0, never
    ublock-unbreak: 1933-0, never
    ublock-quick-fixes: 339-16, never
    easylist: 63372-169, never
    easyprivacy: 31007-1205, never
    urlhaus-1: 6492-0, never
    plowe-0: 3751-930, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1399 ms
  maxAssetCacheWait: 7 ms

**Comment by gorhill** [comment]
Just press Escape key to exit either mode.

**Comment by gorhill** [comment]
I don't see this as a simple fix, so I prefer to decline.
