### ISSUE TITLE
Element picker glitches using invalid selectors inside upward

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2554]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

- Open the element picker on any page
- Type: `##div:upward()`
- Inside the `()` type any wrong selector like `##.x` or `x2..s`
- Notice the whole element picker glitches (can't type anything)
- Errors in the console:
```js
Uncaught TypeError: args is undefined
    astSelectorsFromSelectorList moz-extension://[...]/js/static-filtering-parser.js:3351
    astIsValidSelectorList moz-extension://[...]/js/static-filtering-parser.js:3390
    compileUpwardArgument moz-extension://[...]/js/static-filtering-parser.js:3606
    compileArgumentAst moz-extension://[...]/js/static-filtering-parser.js:3472
    astCompile moz-extension://[...]/js/static-filtering-parser.js:3295
    compileSelector moz-extension://[...]/js/static-filtering-parser.js:2975
    compile moz-extension://[...]/js/static-filtering-parser.js:2954
    parseExtPatternCosmetic moz-extension://[...]/js/static-filtering-parser.js:2264
    parseExtPattern moz-extension://[...]/js/static-filtering-parser.js:2083
    parseExt moz-extension://[...]/js/static-filtering-parser.js:2011
    parseFilter moz-extension://[...]/js/static-filtering-parser.js:1003
    parseRaw moz-extension://[...]/js/static-filtering-parser.js:969
    parse moz-extension://[...]/js/static-filtering-parser.js:864
    token moz-extension://[...]/js/codemirror/ubo-static-filtering.js:216
    readToken moz-extension://[...]/lib/codemirror/lib/codemirror.js:1168
    runMode moz-extension://[...]/lib/codemirror/lib/codemirror.js:1225
    highlightLine moz-extension://[...]/lib/codemirror/lib/codemirror.js:1071
    getLineStyles moz-extension://[...]/lib/codemirror/lib/codemirror.js:1115
    buildLineContent moz-extension://[...]/lib/codemirror/lib/codemirror.js:1748
    getLineContent moz-extension://[...]/lib/codemirror/lib/codemirror.js:2138
    updateLineText moz-extension://[...]/lib/codemirror/lib/codemirror.js:2146
    updateLineForChanges moz-extension://[...]/lib/codemirror/lib/codemirror.js:2095
    prepareMeasureForLine moz-extension://[...]/lib/codemirror/lib/codemirror.js:2392
    coordsCharInner moz-extension://[...]/lib/codemirror/lib/codemirror.js:2745
    coordsChar moz-extension://[...]/lib/codemirror/lib/codemirror.js:2713
    posFromMouse moz-extension://[...]/lib/codemirror/lib/codemirror.js:2964
    onMouseDown moz-extension://[...]/lib/codemirror/lib/codemirror.js:7307
    operation moz-extension://[...]/lib/codemirror/lib/codemirror.js:3929
```

This doesn't happen with `:has()`.

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

uBO 1.47.5rc7 dev

### Browser name and version

Firefox 110.0

### Operating System and version

.

**Comment by u-RraaLL** [comment]
For me it glitches on any special character until directly followed by a character that turns the selector valid. Glitch looks quite similar to #2540.

**Comment by krystian3w** [comment]
IMO old regression, due I can reproduce on oldie verisons.
