### ISSUE TITLE
Creates backup files in uBlock Origin is problematic if the "block insecure downloads" flag is enabled in Edge

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uBlock-issues#2556]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Creates backup files in uBlock Origin is problematic if the block insecure downloads flag is enabled in Edge:
![1](https://user-images.githubusercontent.com/44166263/227596174-1a64e1fb-9ef8-469f-beeb-93a989f40603.jpg)

### A specific URL where the issue occurs.

unnecessary

### Steps to Reproduce

1) Open Edge + UBO 1.48.0
2) The "block insecure downloads" flag must be enabled.
3) Edge shows problematic download pop-up

### Expected behavior

A download of the regular backup.

### Actual behavior

It is shown in the attached image

### uBO version

1.48.0

### Browser name and version

Edge 111.0.1661.51

### Operating System and version

Windows 10 Home x64

**Comment by gorhill** [comment]
Surely uBO can't override the browser's security settings?
