### ISSUE TITLE
contribution: add link to syntax docs on static filter page

### ISSUE THREAD

**Issue by asnelling** [uBlockOrigin/uBlock-issues#2558]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi, new contributor here! :cowboy_hat_face:

I want to open a PR for asnelling/uBlock@055acf3d86e4ec3bb86c2a659628b464a0d296c6, which adds a link in the static filters page to the filter syntax [wiki page](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax).

![screenshot: add link to static filter syntax wiki page](https://i.imgur.com/Woy3T3s.png)

If I have any more contributions, is this ([issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues)) the place to send them?

### A specific URL where the issue occurs.

moz-extension://ce784ba1-b732-49f0-a4da-b0a29385b6ba/dashboard.html#1p-filters.html

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.48.1b0

### Browser name and version

Firefox

### Operating System and version

.

**Comment by gorhill** [comment]
There is already a link (the `(?)` icon), which lead to useful information, including link to syntax documentation.

![Screenshot from 2023-03-24 16-37-20](https://user-images.githubusercontent.com/585534/227634294-62ca8065-5b50-47d7-b37c-cb374107ed38.png)

**Comment by asnelling** [comment]
I see. If there must only be one link, then IMO the clear choice is the syntax page, as it [originally was](https://github.com/gorhill/uBlock/commit/371670802bc2917fd2946063eb5a7393205b7b54).

If you agree, here's https://github.com/asnelling/uBlock/commit/fc0b5e4ef1ff017a6fe0f266451743cfc340fea2 which changes the link target.

**Comment by gwarser** [comment]
Does not feel right, only support tab has links like this, but the sentence can be rephrased to something like "A filter can be in a HOSTs, or an EasyList-compatible syntax. " with "syntax" linked to the syntax page.

**Comment by gwarser** [comment]
Also, "My filters" has grey "?", "My rules" grey "i" and "Trusted sites" brown(?) "i".

**Comment by gorhill** [comment]
> "Trusted sites" brown(?) "i"

It's orange, because it's important to understand this is about wholly disabling uBO's filtering.
