### ISSUE TITLE
websites will not load with ubo enabled after yesterdays update. 

### ISSUE THREAD

**Issue by kirt231** [uBlockOrigin/uBlock-issues#2561]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

i dont know what the problem is, nor do i really care. it took me uninstalling and reinstalling your extension to get my shit to work after pulling my hair for a god damn hour. 

i went one by one, disabling all of my extensions. until i got to ubo. disabled it and it worked like fucking magic. enabled it again, websites stop loading. 

i try to open your extension settings, but i cant because everything is being blocked. i disable ubo, but then extension settings is now greyed out. i enable ubo, open extension settings in another tab, then disable ubo go back to the extension settings but what do you know you cant access that page without ubo being enabled, wow what a dumb cluster fuck of a conundrum that could have esily been saved if you just tested your shit before sending out the update. 

thank you for the waste of time and added stress to my life. where can i donate?

### A specific URL where the issue occurs.

DOESNOTMATTER.COM

### Steps to Reproduce

AGAIN DOES NOT MATTER

### Expected behavior

WEBSITES TO LOAD

### Actual behavior

DID NOT LOAD, STAYED STUCK ON HOME PAGE. FOREVER. 

### uBO version

1.48.0

### Browser name and version

CHROME 111

### Operating System and version

WINDOWS 10.

**Comment by gorhill** [comment]
> dumb cluster fuck of a conundrum that could have esily been saved if you just tested your shit before sending out the update

[uBO development built](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) has been tested for weeks before make a stable release out of it.

Nobody encountered the issue you describe. When Chrome update extensions, there is always a handful of people who report uBO being broken, I am guessing something is getting corrupted in the browser's internal as a result of an update (out of uBO's control). Usually reinstalling uBO solves the issue, otherwise try in a new browser profile to find out whether your browser profile is broken.
