### ISSUE TITLE
Yellow exclamation mark when open opera and load twitch.tv

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uBlock-issues#2562]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Since yesterday I am seeing that when opening opera, a yellow exclamation mark appears on the uBO icon, when load a twitch stream

### A specific URL where the issue occurs.

uBO icon

### Steps to Reproduce

1. When I open Opera,  The last websites.. are saved, and they load again
2. Happens on Twitch.tv streams
3. I need refresh page, to make it work normally

UPDATE also here in `github.com` maybe in all sites

![a](https://user-images.githubusercontent.com/33556647/227812802-d2718aee-adcc-4d2f-bce6-09d01794a13b.png)

### Expected behavior

--

### Actual behavior

 Yellow exclamation mark

### Configuration

uBlock Origin **1.48.0**

**Comment by gorhill** [comment]
Read release notes.
