### ISSUE TITLE
not working on site

### ISSUE THREAD

**Issue by TTomford** [uBlockOrigin/uBlock-issues#2563]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

it doesn't work on this site

### A specific URL where the issue occurs.

https://www.mediaite.com/politics/tennessee-rep-who-sent-christmas-card-with-children-holding-guns-says-hes-heartbroken-over-nashville-school-shooting/

### Steps to Reproduce

broke

### Expected behavior

ads not blocked

### Actual behavior

ads not blocked

### Configuration

ads not blocked

**Comment by TTomford** [comment]
@gorhill just wondering why this is invalid for the future.

**Comment by iam-py-test** [comment]
> @gorhill just wondering why this is invalid for the future.

Filterlist issues (site breakage, ads, etc) should be reported to https://github.com/uBlockOrigin/uAssets. This issue tracker is only for feature requests/bugs directly relating to the extension. 

Follow these steps (steps created by @mapx- ):

- clear cookies / localStorage/ cache for the tested page
- reset uBO, don't modify any uBO setting, update all the filter lists, don't add any other list (other than your regional list)
- disable any custom filter for that site
- disable any other extension / addon in your browser, disable builtin blockers /shields/ tracking protection in brave/ opera/ vivaldi/ edge/ firefox etc
- if Opera browser: open opera://extensions/ and check the "allow access to search page results" option
- disable (if any) the web shields in your antivirus / antimalware software / other blocking software
- are you using a DNS which features adblocking (like AdGuard DNS)?=> test using another DNS (google for example => IP addresses 8.8.8.8 & 8.8.4.4)
- restart the system, reopen the browser, test again.
If the issue persists, click the "report issue on this website" option, and follow the steps to fill out the form.
![image](https://user-images.githubusercontent.com/84232764/228705855-56480390-e017-461f-a0d7-ec1e5b0f35a5.png)
