### ISSUE TITLE
mediaite ad block not working

### ISSUE THREAD

**Issue by TTomford** [uBlockOrigin/uBlock-issues#2565]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

ad block not working. the video is not showing up on the site.

### A specific URL where the issue occurs.

https://www.mediaite.com/politics/trump-is-enormously-popular-far-more-so-than-desantis-fox-news-panel-reacts-to-new-republican-primary-poll

### Steps to Reproduce

1. log into the site
2. the video does not show up when ad block on
3. if adblock is off the video appears.

### Expected behavior

video shows up on page.

### Actual behavior

video does not show up on page.

### Configuration

IDK

**Comment by gorhill** [comment]
<https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+author%3ATTomford>
