### ISSUE TITLE
`sriptletGlobals` is misspelled

### ISSUE THREAD

**Issue by antonok-edm** [uBlockOrigin/uBlock-issues#2570]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/gorhill/uBlock/commit/5c9c87e485308cb2dc6da102a0e20d8fce84124e#diff-30b28769623e5478a0f68519eda037164484cfb444cb5a8e48518fa7bb32e658R26 introduced a global map for scriptlets to share data. There is a typo in that object's name; it's spelled as `sriptletGlobals` instead of (supposedly) `scriptletGlobals`.

I'm hesitant to nitpick about such a small thing, but that variable is now essentially part of the scriptlet API and should be defined by any other blocker compatible with uBO filter lists (like Brave). I figured it's best to get it sorted out earlier rather than have it change unexpectedly later.

I made a quick fix in https://github.com/antonok-edm/uBlock/tree/sriptletGlobals-scriptletGlobals, although I can't open a PR.

### A specific URL where the issue occurs.

https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js

### uBO version

latest `master`

**Comment by gorhill** [comment]
I made a typo in the commit message, oh well

**Comment by antonok-edm** [comment]
Awesome, thanks!

**Comment by krystian3w** [comment]
Still in the code we still have the ISO number for the skis and not the date record:

https://github.com/uBlockOrigin/uBlock-issues/issues/1182#issuecomment-671098740

![image](https://user-images.githubusercontent.com/35370833/229080381-ecf131ac-860a-4f51-a02b-2f9dc787de2d.png)

https://github.com/gorhill/uBlock/blob/b5d78a07bfac8cc9812bb9f0947175e831317997/src/js/storage.js#L523
https://github.com/gorhill/uBlock/blob/b5d78a07bfac8cc9812bb9f0947175e831317997/src/js/storage.js#L529
