### ISSUE TITLE
EasyList Cookie and Fanboy's Social filter not working

### ISSUE THREAD

**Issue by arnoldnicholson** [uBlockOrigin/uBlock-issues#2572]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [x] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

hi
I have noticed the following today in uBlock Origin on the Filter Lists pane:

**EasyList Cookie 0 used out of 46,451
Fanboy’s Social 0 used out of 21,989**

Normally. I use all of the lists provided in uBlock Origin in the following categories:

Built-in (6/6)
Ads (3/3)
Privacy (3/3)
Malware domains (3/3)
Annoyances (7/7)
Multipurpose (2/2)
Regions, languages (36/36)

Selected all of the lists that I normally use as mentioned above.

Hit the Apply changes button.

Hit the Update now button.

Waited for all of the lists to updated.

bserved the total numbers listed at the top of the pane
290,691 network filters ＋ 336,741 cosmetic filters from:

![chrome_screenshot_cjpalhdlnbpafiamejdnhcphjbkeiagm](https://user-images.githubusercontent.com/129572104/229265277-4a86e9f0-7b21-4e61-84a8-8ffd25dbd279.png)

Nothing has changed I tried on Firefox the same thing

> uBlock Origin: 1.48.0
filterset (summary): 
  network: 290691
  cosmetic: 336741
  scriptlet: 43167
  html: 0
listset (total-discarded, last-updated): 
  added: 
    ALB-0: 301-4, 1h.27m
    BGR-0: 1091-11, 8h.5m
    CHN-0: 28052-105, 1d.2h.45m
    CZE-0: 737-0, 1h.26m
    DEU-0: 6707-0, 1h.27m
    EST-0: 459-2, 1h.26m
    FIN-0: 2242-0, 1d.2h.44m
    FRA-0: 29240-86, 1d.2h.45m
    GRC-0: 995-0, 1d.2h.44m
    HRV-0: 295-1, 4d.22h.32m
    HUN-0: 2164-2, 1h.26m
    IDN-0: 5473-20, 1d.2h.45m
    IND-0: 12580-0, 1h.26m
    IRN-0: 2976-37, 1d.2h.44m
    ISL-0: 194-1, 8h.5m
    ISR-0: 1694-2, 1h.26m
    ITA-0: 13507-77, 1h.26m
    JPN-1: 10480-17, 1d.2h.44m
    KOR-1: 4175-18, 1h.26m
    LTU-0: 1225-7, 5d.21h.24m
    [30 lists not shown]: [too many]
  default: 
    user-filters: 0-0, never
    easylist: 65218-1599, 1d.2h.44m
    easyprivacy: 30755-1973, 1d.2h.44m
    plowe-0: 3751-1437, 5d.21h.18m
    ublock-abuse: 78-2, 5d.21h.16m
    ublock-badware: 5831-372, 1d.2h.44m
    ublock-filters: 33140-4345, 1d.2h.44m
    ublock-privacy: 293-12, 5d.21h.12m
    ublock-quick-fixes: 458-37, 1h.26m
    ublock-unbreak: 1942-114, 1d.2h.44m
    urlhaus-1: 7324-2, 1h.26m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
switchRuleset: 
  added: [array of 2 redacted]
hostRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: 
  filterAuthorMode: true
supportStats: 
  allReadyAfter: 2904 ms (selfie)
  maxAssetCacheWait: 2563 ms

### A specific URL where the issue occurs.

chrome-extension://

### Steps to Reproduce

...

### Expected behavior

...

### Actual behavior

...

### uBO version

1.48.0

### Browser name and version

chorme

### Operating System and version

windows

**Comment by gorhill** [comment]
> - [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

[Dashboard: Filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists):

> uBO discards duplicate filters, so the number of filters used within a filter list depends on how many duplicate filters were detected within that filter list. The order in which the filter lists are loaded into memory is undefined.

**Comment by krystian3w** [comment]
But sometimes is diffrent sorted like:

- EL Cookies 46 K of 46 K
- Fanboy Social 21 K of 21 K
- Fanoby Annoyances 14 K of 81 K - Then the user may find that Fanboy Annoyances is broken.
