### ISSUE TITLE
uBO should not parse filters inside an invaild `!#if` directive

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2577]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Similar but unrelated:
https://github.com/uBlockOrigin/uBlock-issues/issues/1712#issuecomment-916838623

As per uBO docs:
> [_For the time being, only a single token is supported in a `!#if directive uBO supports only the following, and **anything else gets ignored**_](https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#pre-parsing-directives)

> [_**gorhill**: Unknown directives should be disregarded_](https://github.com/uBlockOrigin/uBlock-issues/issues/183#issuecomment-416210772)

[As per AdGuard docs:](https://adguard.com/kb/general/ad-filtering/create-own-filters/#conditions-directive)
 ```adb
!#if (conditions)
rules_list
!#endif

!#if (adguard_app_android)
||example.org^$third-party
!#endif

! for all AdGuard products except AdGuard for Safari
!#if (adguard && !adguard_ext_safari)
||example.org^$third-party
domain.com##div.ad
!#endif
```

***

I use uBO's `!#if !cap_html_filtering` and `!#if env_mobile` directives in my list.
AdGuard doesn't have an equivalent as of now, they're planning on adding them:

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2146

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2259

So as a workaround for AdGuard I use:
`!#if (!adguard_app_windows && !adguard_app_mac && !adguard_app_android && !adguard_ext_firefox)` and `!#if (adguard_app_android || adguard_app_ios)`

I had expected uBO to ignore filters inside those, but apparently it doesn't.

### A specific URL where the issue occurs.

`github.com`

### Steps to Reproduce

1. Add:
```adb
!#if (adguard_app_android || adguard_app_ios)
github.com##html
!#endif
```
Or
```adb
!#if (something_fake)
github.com##html
!#endif
```
2. Go to: `github.com`

### Expected behavior

The page shouldn't be hidden because the directive is invalid and uBO should just ignore filters inside an invalid directives (well, valid according to AdGuard).

### Actual behavior

The page is hidden.

### uBO version

1.48.3b3 dev

### Browser name and version

Firefox 111

### Operating System and version

.

**Comment by gorhill** [comment]
It's by design, unknown `!#if ...` expressions always evaluate to true, as if the line is just a comment. If you do not want uBO to parse the block, use `!#if !ext_ublock` or `!#if adguard`:

    !#if adguard
    !#if (adguard_app_android || adguard_app_ios)
    github.com##html
    !#endif
    !#endif

**Comment by gorhill** [comment]
You want me to have the syntax highlighter render it as a comment?

The bottom line is that unparseable directives should have a default which is to not filter out, otherwise uBO is just guessing, and you want that guessing to be `false` by default because it happens to match your filters, but there is absolutely no way that the guessing will please someone else's filters, it's just luck at the end. Because of this, the default is to do _nothing_, and nothing means not skipping lines in the filter list.

**Comment by gorhill** [comment]
> giving the impression that it's not a comment.

It is not a comment from uBO's point of view. It is a comment from any other blocker which do not parse `!#if` directives, and not enforcing unknown directives is consistent with not enforcing when directives are not supported.

Solution is simple, just wrap the block around a directive uBO understand.

**Comment by gorhill** [comment]
You are missing that what you ask is essentially that you want uBO to be tailored to your state of mind when you craft your filters. You want uBO to guess `false`, then it's just a matter of time before somebody come here and ask to reverse the guess to `true`:

    !#if (!adguard_app_android && !adguard_app_ios)
    github.com##html
    !#endif

Common sense dictate to not make a decision when not knowing what to do with a directive, and not making a decision means behaving as if the directive does not exist.

**Comment by gorhill** [comment]
Wy not just use `!#include ..` inside `!#if adguard`? uBO recognizes so it will not parse the `!#include` and all AdGuard-specific filters will be grouped in one file.

**Comment by gorhill** [comment]
> I've been using those directives for a such long time

It means they unknown directives are ignored and uBO did not remove the filters inside the `!#if`-`!#endif`, i.e. it parsed them.

**Comment by gorhill** [comment]
> [Side note] Will that trigger this behavior?:

This means unbalanced `!#if`-`!#endif` will cancel pre-parsing. I explain in that thread why. Surely unbalanced `!#if`-`!#endif` is a rare occurrence and I don't see how this was affecting you.

**Comment by krystian3w** [comment]
Please do not spoil the operation of this method: https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/96d5f4c721f28688e1c1473a9400f9dc28178fe9/templates/PPB.template#L107-L110

```adb
! Adding a supplement list to uBlock Origin and AdGuard MV2/App for Windows&macOS&Android so users don't have to subscribe to it
!#if (!adguard_ext_android_cb && !adguard_app_ios)
!#include PAF_supp.txt
!#endif
```

I use it to exclude the list on the iPhone and iPad (AdGuard has not added an option to detect if someone has an active extension for Safari - Unfortunately they rely on `{ display: none !important }` to make the filter incompatible when someone does not activate advanced filtering: https://adguard.com/en/blog/adguard-4-3-for-ios.html), and prospectively in the too-simple "Android Content Blocker for Samsung Internet and Ynadex Browser" 'plugin'.
