### ISSUE TITLE
redirect target cut at apostrophe when no-scripting

### ISSUE THREAD

**Issue by amonakov** [uBlockOrigin/uBlock-issues#2586]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I found that uBlock breaks some redirect targets if they contain an apostrophe symbol.

Consider this URL: https://t.co/H8u1HuiL78  . It redirects to https://en.wikipedia.org/wiki/Sorcerer's_Apprentice_Syndrome

When scripting is disabled in uBlock for t.co, it redirects to https://en.wikipedia.org/wiki/Sorcerer instead, cutting off the redirect target at the apostrophe symbol.

For posterity, t.co responds differently based on User-Agent. Here's the appropriate curl command:

```
curl https://t.co/H8u1HuiL78 -A 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0'
```
and the response body:
```
<head><noscript><META http-equiv="refresh" content="0;URL=https://en.wikipedia.org/wiki/Sorcerer's_Apprentice_Syndrome"></noscript><title>https://en.wikipedia.org/wiki/Sorcerer's_Apprentice_Syndrome</title></head><script>window.opener = null; location.replace("https:\/\/en.wikipedia.org\/wiki\/Sorcerer\'s_Apprentice_Syndrome")</script>
```

### A specific URL where the issue occurs.

https://t.co/H8u1HuiL78

### Steps to Reproduce

1. Check 'Disable Javascript' in uBlock settings.
2. Navigate to https://t.co/H8u1HuiL78
3. Observe that you are redirected to wikipedia page "Sorcerer" rather than "Sorcerer's Apprentice Syndrome".

### Expected behavior

The redirect target should not be cut at the apostrophe, redirecting you to "Sorcerer's Apprentice Syndrome".

### Actual behavior

Somehow the redirect target is cut at the apostrophe symbol. I suspect it may be an issue in noscript-spoof.js.

### uBO version

1.48.4

### Browser name and version

Firefox 111

### Operating System and version

Linux

**Comment by gorhill** [comment]
>  I suspect it may be an issue in noscript-spoof.js.

Yes: <https://regex101.com/r/Dh1VPh/1>
