### ISSUE TITLE
µBlock doesn't work after renaming the firefox profile

### ISSUE THREAD

**Issue by z0rti** [uBlockOrigin/uBlock-issues#2587]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

µBlock icon is gone and settings not showing

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

- create a new Firefox profile:  mkdir "~/firefox/fresh/"
- start: firefox --profile  "~/firefox/fresh/"
- install µblock
- quit Firefox
- rename the profile's dir: mv "~/firefox/fresh/" "~/firefox/foobar/"
- start: firefox --profile  "~/firefox/foobar/"

### Expected behavior

µBlock should work no matter what's the dir name of the profile

### Actual behavior

µBlock icon is gone
in Extensions icon (Puzzle) when clicking the settings wheel besides "µBlock" a new tab opens
moz-extension://4958a8d2-9939-47d4-aa68-8a0190b42a60/dashboard.html
and is completely empty
mv the dir back to fresh, then it works again.
so there seem to be absolute paths somewhere?

### uBO version

1.48.4

### Browser name and version

firefox 111.0.1 (64-Bit)

### Operating System and version

ubuntu + debian

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429838

**Comment by forthrin** [comment]
+1.

The only places here that refer to absolute user paths or the default `abcd1234.default-release` profile name are:

```
pkcs11.txt:
parameters=configdir='sql:/Users/$USER/Library/Application Support/Firefox/Profiles/abcd1234’ …
extensions.json:
json.addons[n].path = "/Users/$USER/Library/Application Support/Firefox/Profiles/abcd1234/extensions/uBlock0@raymondhill.net.xpi";
json.addons[n].rootURI = "jar:file:///Users/$USER/Library/Application%20Support/Firefox/Profiles/abcd1234/extensions/uBlock0@raymondhill.net.xpi!/";
```

Updating all these references in accordance with the renamed profile on disk, uBlock Origin is not found. `cd ~/Library/"Application Support"/Firefox/profiles && ln -s new-profile abcd1234.default-release` fixes it instantly.

But how can this be when `abcd1234` doesn't even reside on the hard drive.

`find ~/Library -type f -exec grep -a abcd1234 {} +` finds nothing.

Does anyone know where the reference is stored?
