### ISSUE TITLE
Blank uBO Thunderbird for macOS pane in versions after uBlock0_1.48.5b5.thunderbird.xpi

### ISSUE THREAD

**Issue by onePW** [uBlockOrigin/uBlock-issues#2591]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Updating the Thunderbird extension to any version beyond uBlock0_1.48.5b5.thunderbird.xpi results in a blank uBO GUI.

MacBookPro18,1 (Apple M1 Pro) 
macOS Ventura 13.3.1
Mozilla Thunderbird 102.9.1

### A specific URL where the issue occurs.

https://github.com/gorhill/uBlock/releases/download/1.48.5b7/uBlock0_1.48.5b7.thunderbird.xpi

### Steps to Reproduce

1. Mozilla's Thunderbird extension uBlock0_1.48.5b9.thunderbird.xpi has been installed from the official repository. 
2. Thunderbird has been quitted, followed by a normal relaunch.
3. uBlock Origin has just been clicked in the attached .png file.

### Expected behavior

uBO's GUI should open as in the attached:
<img width="367" alt="Screenshot 2023-04-10 at 18 46 20" src="https://user-images.githubusercontent.com/94264573/231034278-0e2180f2-1c4e-4701-803d-49137aa6735d.png">

### Actual behavior

Extension uBlock0_1.48.5b5.thunderbird.xpi has been removed and extension uBlock0_1.48.5b9.thunderbird.xpi has been installed:
<img width="407" alt="Screenshot 2023-04-10 at 19 07 42" src="https://user-images.githubusercontent.com/94264573/231037543-e9d2a283-e0ab-41a5-9dbb-06f6436a8d69.png">

### Configuration

macOS Ventura 13.3.1 has been started normally. Thunderbird 102.9.1 has been launched normally.

**Comment by onePW** [comment]
Question: If an EtreCheckPro 6.8.1 report file is attached, will the public have access?

**Comment by gorhill** [comment]
Yes, this a public issue tracker.

**Comment by gorhill** [comment]
I don't have Thunderbird 102 or MacOS, but I can't reproduce with Thunderbird 91 / Linux / uBO 1.48.5b9.

**Comment by krystian3w** [comment]
You can try manually update to 7 or 9:

https://github.com/gorhill/uBlock/releases/download/1.48.5b7/uBlock0_1.48.5b7.thunderbird.xpi
https://github.com/gorhill/uBlock/releases/download/1.48.5b9/uBlock0_1.48.5b9.thunderbird.xpi

on both I reproduced blank pop-up on Windows 7 with TB 102:

![image](https://user-images.githubusercontent.com/35370833/231150808-82eacdcd-af74-483c-8450-2be9553e942c.png)

TB 91 IMO lost emergency support at all, TB 102 will lose it around the release of 117 Firefox.

**Comment by krystian3w** [comment]
Apparently, the bug console complains about the alarms API (perhaps there is none for TB):

https://github.com/gorhill/uBlock/commit/bec6cad2c029ef59de40043dcc998bb3c861cc69

**Comment by gwarser** [comment]
Why it works fine on Linux???

**Comment by gorhill** [comment]
I upgraded my Thunderbird to latest 102.9.1 (with some pain points), and I can't reproduce an issue on my side. I do see that `alarms` does not appear to be supported as per <https://webextension-api.thunderbird.net/en/latest/#firefox-webextension-apis-supported-by-thunderbird>, but then I see no issue so far on my side.

**Comment by gwarser** [comment]
Yes, b9 works in debug mode if I put alarms in permissions.

**Comment by gorhill** [comment]
I wasn't able to test using _"Load Temporary Add-on..."_, loading the result of `./tools/make-thunderbird` fails for some reasons, Any idea?

**Comment by onePW** [comment]
Good news! Between today's release of Mozilla's Thunderbird 102.10.0 stable and uBlock0_1.48.5b10.thunderbird.xpi, uBO's GUI opens with normal behavior!

I am thankful to who or what has resolved this issue.

**Comment by gwarser** [comment]
@gorhill I did use the xpi, because I already had it in VM. Will try the source in a moment...
It works on Linux. Did you select the manifest when loading? Chrome requires folder, Firefox the manifest file.
In Win11 works too. 
Build from master https://github.com/gorhill/ublock/commit/464119af61c1fffa567167407681fcac5f932b9c

**Comment by krystian3w** [comment]
The solution is not the 102.10.0 update, a snapshot from 102.9.1:

![image](https://user-images.githubusercontent.com/35370833/231366727-67e8d0d0-1e83-4ccc-af64-fe9832734e50.png)

Web filtering was not working during the outage.



In the test, I suggest you rename the iframe to detect cosmetic filtering (it looks like EasyList has removed the deprecated filters/baits).
