### ISSUE TITLE
Syntax mistake when using extraneous rule modifier marker is not highlighted by the code editor

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uBlock-issues#2593]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Per [filter syntax documentation by Adguard](https://adguard.com/kb/general/ad-filtering/create-own-filters/#basic-rules-syntax), a valid filter is represented by the following form.
```
     rule = ["@@"] pattern [ "$" modifiers ]
modifiers = [modifier0, modifier1[, ...[, modifierN]]]
```

Filters that use extraneous rule modifier marker (`$`) are not highlighted as mistakes by uBlock Origin, even though they are invalid filters and discarded internally (at least this is what I presumed happening behind the scene) when parsed.

### A specific URL where the issue occurs.

https://example.com
https://www.youtube.com/watch?v=fJ9rUzIMcZQ

### Steps to Reproduce

1. Add the following to `My Filters` list.
   ```
   ||example.com^$doc
   ||example.com^$doc,badfilter
   ```
2. Open https://example.com. Notice the page's behaviour.
3. Replace the second filter added in step 1 with the following.
   ```
   ||example.com^$doc,$badfilter
   ```
   Notice the code editor's behaviour.
4. Repeat step 2.
5. Add the following to `My Filters` list.
   ```
   fJ9rUzIMcZQ$doc,xhr,domain=youtube.com
   ```
6. Open https://www.youtube.com/watch?v=fJ9rUzIMcZQ. Notice the page's behaviour.
7. Replace the filter added in step 5 with the following.
   ```
   fJ9rUzIMcZQ$doc,xhr,$domain=youtube.com
   ```
   Notice the code editor's behaviour.
8. Repeat step 6.
9. Repeat step 7 and 8 with filters 
   ```
   fJ9rUzIMcZQ$doc,$xhr,domain=youtube.com
   ``` 
   and 
   ```
   fJ9rUzIMcZQ$doc,$xhr,$domain=youtube.com
   ```

### Expected behavior

The code editor highlights the syntax mistakes in step 3, 7, and 9, consistent with the fact that those filters are discarded as seen in step 4, 8, and 9.

### Actual behavior

The code editor does not highlight the syntax mistakes in step 3, 7, and 9, even though those filters are discarded as seen in step 4, 8, and 9.

### uBO version

1.48.5b7

### Browser name and version

Firefox 111.0.1

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> fJ9rUzIMcZQ$doc,$xhr,$domain=youtube.com

uBO considers this a valid filter, it's possible to use `$` in the pattern. I am pretty sure I have stumbled in the past in patterns using `$`. At least the syntax highlighter makes it clear how the filter is interpreted.

**Comment by gorhill** [comment]
If an extraneous `$` was considered an error, the following filter:

    ||example.com/$/$all

Would not work to block:

    https://example.com/$/tracker

**Comment by gorhill** [comment]
Yes valid, it will cause the filter `||example.com^$doc,$all` to be discarded, which filter was meant to block URLs like `https://example.com/$doc,/resource`.
