### ISSUE TITLE
My rules dashboard unusable on Firefox 112.0

### ISSUE THREAD

**Issue by manfred-h** [uBlockOrigin/uBlock-issues#2602]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When clicking on the "My rules" button, I don't see any rules defined. However, I can move the cursor down a lot of lines. As the "Support" page is also not actually usable due to links being written in the same color as the background, I guess there exists a problem with the colors used on the uBO pages.

### A specific URL where the issue occurs.

moz-extension://565c78b5-cadc-4364-a820-cf8c8d238464/dashboard.html#dyna-rules.html

### Steps to Reproduce

1. Open the uBO settings page
2. Select the "My rules" page
3. Select the "Support" page

### Expected behavior

For 2. I would expect the rules to be shown, at least the predefined ones.
For 3. the various links should be visible.

### Actual behavior

It appears that the text is written in the same color as the background.

### Configuration

openSUSE Tumbleweed Linux using Firefox 112.0 from
https://build.opensuse.org/package/show/home:manfred-h:mozilla/firefox112

**Comment by gorhill** [comment]
Probably caused by customizations you made to Firefox. See if the issue occurs in a new profile.

Do you have a `userContent.css` file which content is overriding uBO's styles?

**Comment by gorhill** [comment]
> openSUSE Tumbleweed Linux using Firefox 112.0 from
> https://build.opensuse.org/package/show/home:manfred-h:mozilla/firefox112

Is this a custom build of Firefox? If so, I will close the issue as _invalid_.

**Comment by manfred-h** [comment]
I found the reason: I had the following line in my ~/.mozilla/firefox/<profile>/user.js:

user_pref("font.name.monospace.x-western", "Misc Fixed");

This used to work with older versions, but doesn't work with Firefox 112.0 anymore.

I removed the line from both user.js and prefs.js, now uBO works as expected. Sorry for bothering you!
