### ISSUE TITLE
Extention icon inside address/url bar 

### ISSUE THREAD

**Issue by avriota01** [uBlockOrigin/uBlock-issues#2605]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

It's there any way to put the Ublock Origin extension icon inside address/url bar of Firefox (on the right side, e.g the star icon for the "bookmark this page" )? 

I checked the documentation at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction

The page action's properties can be made with the page_action key in the manifest.json

I would like to vote for a future, where we can see for full support for the extension icons to be inside the address/url bar and that icons to follow the loading behavior, which we have since version 1.48.

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### Configuration

Firefox 110 64 bit.
Ublock Origin 1.49.
Windows 10 64 bit.

**Comment by gorhill** [comment]
I prefer to decline, not something I would want to work on, and also there is no support for text badge.
