### ISSUE TITLE
uBO picker no works after using "visual search" in Microsoft edge

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#2607]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The Ads appears using **visual search** in "Microsoft Edge" browser .. following the next steps the uBO picker stop work, needing refresh the page

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Go to `https://www.decathlon.es/es/landing/tienda-deporte-mujer/_/R-a-Tienda-deporte-mujer`
2. Right click in any image and select "visual search"
3. In the right sidebar I can see the ( bing ads ) 
4. Press the Blue button "open in new window" ( in this moment  uBO picker no works)
5. Tipe any search in the **search bar** ( Example _Tablets_ )
6. uBO picker no works, and showing **Ads**

### Expected behavior

no ads and the adblocker picker-selector works

### Actual behavior

ads

### uBO version

1.49

### Browser name and version

Microsoft edge

### Operating System and version

windows 11

**Comment by iam-py-test** [comment]
This is a known issue. uBlock Origin (and other similar blockers) can not access the sidebar

**Comment by gwarser** [comment]
This looks like bug in Edge, or maybe it's intended. The tab created from sidebar view don't have content scripts injected, it can be "cloned" somehow, or the sidebar content is moved into the tab. If you duplicate it (Ctrl + click on reload button) it will work fine in new tab, but it will load a completely different style.

**Comment by iam-py-test** [comment]
Opera disables browser extensions on search pages.
