### ISSUE TITLE
Dynamic filtering rule is invalid

### ISSUE THREAD

**Issue by xinggsf** [uBlockOrigin/uBlock-issues#2609]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.

### Description

When I click on the download icon in the download item on that site, the resulting download frame request is blocked!

Dynamic filtering rule:
```
* * 3p-frame block
* * 3p-script block
www.123pan.com * 3p-frame noop
www.123pan.com * 3p-script noop
```

### A specific URL where the issue occurs.
`https://www.123pan.com/s/vwsRVv-xnoxh`

### Expected behavior
<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +11 | * * 3p-frame block | -- | web-pro2.cjjd18.com | 3 | get | frame | `https://download-pro-b.cjjd20.com/123-544/7795f8cc/1811655563-0/7795f8cc7c503a5c1f91d82e982c2220/c-m2?v=2&t=1682322452&s=270993cdc8b3e571a44e1691d5e44fa2&filename=portable_x64_beta_113_3_4_5_5.zip` |
| +0 | \|\|hm.baidu.com/ | -- | `www.123pan.com` | 3 | get | script | `https://hm.baidu.com/hm.js?d815f2e1f682c86565c1063aafaef292` |
| +0 | \|\|cnzz. | -- | `www.123pan.com` | 3 | get | script | `https://s4.cnzz.com/z_stat.php?id=1280304515` |
| +0 | \|\|statics.123pan.com/static-by-custom/app-banner$image | -- | `www.123pan.com` | 1 | get | image | `https://statics.123pan.com/static-by-custom/app-banner@3x.png` |
| +0 | \|\|statics.123pan.com/static-by-custom/web-banner$image | -- | `www.123pan.com` | 1 | get | image | `https://statics.123pan.com/static-by-custom/web-banner@2x.png` |
</details>

### Configuration

uBlock Origin: 1.49.0
Chromium: 112

**Comment by xinggsf** [comment]
add rule `cjjd18.com * 3p-frame noop`, it work

**Comment by gorhill** [comment]
Don't open invalid issue like this here, go to [reddit](https://www.reddit.com/r/uBlockOrigin/) for support with such questions.
