### ISSUE TITLE
[Feature Request] View number of domains connected on the extension's badge

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#2611]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [ ] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

Would it be possible to add an option (in the "Settings" tab) to display the number of domains connected to (as shown in the extension's popup) instead of the number of domains blocked, on the extension badge?

I am aware that this is not a bug report, however I didn't find an issue template for feature requests, so I'm using the bug report template.

### A specific URL where the issue occurs.

N/A

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBO version

1.48.4

### Browser name and version

Firefox 96.0.3

### Operating System and version

Microsoft Windows 10 Pro 64-bit

**Comment by garry-ut99** [comment]
> instead of the number of domains blocked

Just to clarify: currently it shows requests blocked, not domains.

**Comment by blox814123** [comment]
Fwiw, I think it would generally be good to show "numbre/percentage of domains blocked since install" somewhere in the aggregated statistics, as the numbers of requests blocked does not really provide a meaningful context.

**Comment by gorhill** [comment]
A single domain can have both blocked and allowed network requests.

**Comment by gorhill** [comment]
Given time is a limited resource, I will decline this.
