### ISSUE TITLE
Cosmetic filters are slow in Firefox

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBlock-issues#2613]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Cosmetic filters are slow in my Firefox, i have no problems with another browser (Google Chrome)

### A specific URL where the issue occurs.

`https://root-nation.com/` & `https://ukrfootball.ua/`

### Steps to Reproduce

uBO default lists + RUS: RU AdList 
Go to `https://root-nation.com/` & `https://ukrfootball.ua/` then refresh the pages.
Every time I refresh the site or scroll through the news. I see the ads flashing, but it's blocked. Also, ads background flashes on another site. I can't see all this in google chrome. See `https://imgur.com/a/cIRQjfL`

### Expected behavior

uBO works best on Firefox not for me. :(

### Actual behavior

uBO works slower in Firefox than in Google Chrome. We are talking about cosmetic filtering

### uBO version

1.49.0/1.49.2

### Browser name and version

Firefox 112.0.2/Google Chrome 112.0.5615.138

### Operating System and version

Windows 10 Pro 22H2

**Comment by dportvine** [comment]
But if I plug in Stylus and add [RU AdList CSS Fixes](https://raw.githubusercontent.com/easylist/ruadlist/master/ruadlist-fixes.user.css) the problem will disappear, see - `https://imgur.com/bKFR73I`

**Comment by stephenhawk8054** [comment]
Maybe it's because Stylus injects a `style` tag to the DOM tree?

https://user-images.githubusercontent.com/66517106/235832020-c7f294ee-ded8-48f2-9633-13a6f20e0bb4.png

**Comment by dportvine** [comment]
For `https://root-nation.com/` @dimisa-RUAdList added 

```adb
root-nation.com##+js(remove-node-text, style, /body[\s]{1}{[\s][\t][\t]*background-color:|body{background-color:/)
```

But I have a different case `https://mezha.media/`  [gif](https://imgur.com/AhpfhxS) rule `mezha.media###wrapper > a[href][target="_blank"]` What is the problem? Maybe the rules need to be cached?

**Comment by dimisa-RUAdList** [comment]
Removing the entire style sometimes leads to a breakdown of the layout. And deleting the target part of the style code works safely.

**Comment by mailing12** [comment]
No, is invalid.

You meant:

```adb
root-nation.com##style:has-text(/body[\s]{1}\{[\s][\t][\t]*background-color:|body\{background-color:/):remove()
```

Latest parser without hotfix waiting for `)` after `:remove()` but text should be changed to something like:

В has-text обнаружены открытые скобки — закройте их или закрепите Обратная косая черта ("\"). 

Open parentheses are detected in has-text - close them or backslash them.

**Comment by stephenhawk8054** [comment]
> Removing the entire style sometimes leads to a breakdown of the layout. And deleting the target part of the style code works safely.

Doesn't `rmnt` remove that whole style as well?

**Comment by dportvine** [comment]
> Doesn't this work?
> 
> ```
> root-nation.com##style:has-text(/body[\s]{1}{[\s][\t][\t]*background-color:|body{background-color:/):remove()
> ```

Your rule is broken, by the way `:remove()` works slow. [gif](https://imgur.com/qPBl8OZ)

**Comment by mailing12** [comment]
Someone can assess the quality of English and Spanish, as it is translated by a human it may be worth addressing the problem with the background as it occurs in other languages globally:

`https://root-nation.com/en/`
`https://root-nation.com/es/`

By the looks of the language change plugin, however, I fear that everything flies through the Bing, Google or Yandex API.

**Comment by garry-ut99** [comment]
> dportvine : `ukrfootball.ua` ==> `https://imgur.com/a/cIRQjfL`
> dportvine : But if I plug in Stylus and add [RU AdList CSS Fixes](https://raw.githubusercontent.com/easylist/ruadlist/master/ruadlist-fixes.user.css) the problem will disappear, see - `https://imgur.com/bKFR73I`

I can reproduce (even with `ukrfootball.ua##body`), another workaround is to add either of these, which reduces the flickering signfically on all adblockers : `||ukrfootball.ua/templates/ukrfootball/fonts/RobotoSlab/stylesheet.css$stylesheet,1p` or `ukrfootball.ua##+js(rpnt, style, Roboto Slab, xxx)`
(still occasionally flickers, but not so often, also, after adding, it's recommended to clear browser cache and Ctrl + F5 a single time, to avoid the styleseet file being fetched from browser cache).

It seems to be a some browsers/css/webpages issue, which happens on some websites in some browsers and most likely is unrelated to adblockers.
