### ISSUE TITLE
Scriptlet to spoof CSS property value

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2618]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

What about a scriptlet that will return a different CSS property value to counter `getComputedStyle()` (maybe by proxying `CSSStyleDeclaration.prototype.getPropertyValue`) to foil sophisticated anti-blockers that check all CSS properties of an element (like `megaup`, `aternos`, `ylilauta.org`)?

```adb
example.com##+js(spoof-css, a[href*="ads/redirect/"] > img, clip-path, none)
example.com##a[href*="ads/redirect/"] > img:style(clip-path: circle(0) !important;)
```

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

.

### Browser name and version

.

### Operating System and version

.

**Comment by krystian3w** [comment]
Why not:

```adb
example.com##a[href*="ads/redirect/"] > img:spoof(clip-path: none !important;)
example.com##a[href*="ads/redirect/"] > img:style(clip-path: circle(0) !important;)
```

Based on migration `ra`, `rc` to pseudo-classes syntax.

**Comment by krystian3w** [comment]
I suppose this trouble can only apply to javascript written with html attributes.

https://www.w3schools.com/tags/ref_eventattributes.asp

which is not recommended - actions should be created in the file or "`<script> </script>`" section (https://kornel-ski.translate.goog/pl/onclick?_x_tr_sl=pl&_x_tr_tl=en&_x_tr_hl=pl&_x_tr_pto=wapp).

**Comment by krystian3w** [comment]
This solove trouble with blocked right click on 99% of pages?

https://github.com/uBlockOrigin/uBlock-issues/discussions/2403#discussioncomment-4638987

**Comment by gorhill** [comment]
> Based on migration `ra`, `rc` to pseudo-classes syntax.

Spoofing requires to patch JavaScript calls, which can only be done in the page world. Code for procedural cosmetic filters execute in content script world.

**Comment by krystian3w** [comment]
And are there any plans to e.g. on `musixmatch.com` to replace `+js(ra, oncontextmenu, body, complete)` to  `+js(nowoif, something)`?

> https://github.com/uBlockOrigin/uAssets/blob/ee4ce452e50fccf8253a6014db44122f4faf5e38/filters/annoyances.txt#L2007

**Comment by gorhill** [comment]
Can I get real world examples (preferably not requiring account) for which I can test such scriptlet?

**Comment by peace2000** [comment]
> Can I get real world examples (preferably not requiring account) for which I can test such scriptlet?

`https://ylilauta.org/jorma/131700539`

To spoof that `##iframe.a` is `display: block` even if it's truly hidden?

**Comment by gorhill** [comment]
When I use `##iframe.a`, the frame is not hidden, is there an exception filter? If so I am not seeing it in the logger.

**Comment by gorhill** [comment]
> But if I use this userscript:

I tried with ViolentMonkey and I still get detection with your script.

**Comment by gorhill** [comment]
Note that has an issue but it accidentally works because of truthiness. Should be:

    if (args[0] === "clip-path" || args[0] === "clipPath") {

**Comment by gorhill** [comment]
Ok the page is doing something else than just checking the properties. For `spoof-css` to work on that site, I had to wholly remove the proxying of `getComputedStyle()`, so it does something with that call that triggers the detection.

**Comment by Yuki2718** [comment]
Is it possible to specify not a static value but value obtainable from elements or scripts?
On `https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-6960192` an excerpt of detection code `https://www.btcbitco.in/myassets/aOW9dugd31nhaaOW9dugd31nhd.js?ver=` (direct access forbidden even with parameter)
```
function aOW9dugd31nhests() {
            
                var done = 20;
                
                if (done === 0) {
                    setTimeout(function() {
                        if ($('.l-button').length > 0) {
                            $('.l-button').hide();
                        }
                        var aOW9dugd31nhe2 = document.getElementById('aOW9dugd31nhedz');
                        var aOW9dugd31nhe4 = aOW9dugd31nhe2.clientHeight;
                        if (!aOW9dugd31nhe2 || aOW9dugd31nhe4 != 97) {
                            if (typeof gtag === "function") {
                                gtag('event', 'session_ends');
                            }
                            alert("Session ends, thanks for using GainLink.");
                            window.location.href = 'https://www.btcbitco.in/page/endsessions';
                        }else{
                        aOW9dugd31nhest();
                        }
                    }, 4000);
                } else {
                    if ($('.l-button').length > 0) {
                        $('.l-button').hide();
                    }
                    setTimeout(function() {
                            var aOW9dugd31nhek = document.getElementById('aOW9dugd31nhedz');
                            var aOW9dugd31nheh = aOW9dugd31nhek.clientHeight;
                            if (!aOW9dugd31nhek || aOW9dugd31nheh != 97) {
                                if (typeof gtag === "function") {
                                    gtag('event', 'ads_blocker_detected');
                                }
                                  var aOW9dugd31nhec = confirm("Go ahead and turn off your adblocker? Click 'OK' if you agree to turn off your adblocker or 'Cancel' to stop here.");
                                  if (aOW9dugd31nhec === false) {
                                    alert("Session ends, thanks for using GainLink.");
                                    if (typeof gtag === "function") {
                                        gtag('event', 'session_ends');
                                    }
                                    window.location.href = 'https://www.btcbitco.in/page/endsessions';
                                  } else {
                                    alert("Please disable your adblocker and reload");
                                  }
                            }else{
                                $.ajax({
                                    url: "https://www.btcbitco.in/page/validate?ver=1d75b01ce9033fe7764904b77212315e25779b17a25e77d79aafc9500edbd20e",
                                    type: "GET",
                                    success: function(response) {
                                        if (response === "valid") {
                                            aOW9dugd31nhest();
                                        } else {
                                            alert("Invalid response received!");
                                        }
                                    },
                                    error: function() {
                                        alert("An error occurred, please reload!");
                                        location.reload();
                                    }
                                });
                            }
                    }, 1000);
                }
            }
            window.onload = function() {
              var aOW9dugd31nhevd = document.createElement("iframe");
              aOW9dugd31nhevd.src = "https://cryptocoinsad.com/ads/show.php?a=256522&b=397269";
              aOW9dugd31nhevd.style = "width: 100%; height: 97px; overflow: hidden; border: 0px; padding: 0px; background-color: transparent;";
              aOW9dugd31nhevd.id = "aOW9dugd31nhedz";
                        
              var aOW9dugd31nhezd = document.getElementsByClassName("entry-content")[0];
              var aOW9dugd31nheparent = aOW9dugd31nhezd.parentNode;
              aOW9dugd31nheparent.replaceChild(aOW9dugd31nhevd, aOW9dugd31nhezd);
  
              function aOW9dugd31nhemm() {
                var aOW9dugd31nheca = document.getElementById("aOW9dugd31nhedz");
            
                if (aOW9dugd31nheca) {
                  clearInterval(aOW9dugd31nheid);
                  aOW9dugd31nhests();
                }
              }
            
              var aOW9dugd31nheid = setInterval(aOW9dugd31nhemm, 1000);
            }
```
They create a bait element with random height (here 97px, but varies on each load) and checks it. It's not inline so rpnt can't be used. As this is iframe, I just removed cosmetic filter and redirect=noop.html is enough, but the suggested capability may be useful.

**Comment by JobcenterTycoon** [comment]
`kiktu.com` doing the same now. A bait element getting added but with `visiblity: hidden` while the real element has `visiblity: visible`. Now the site checks if the bait has `visiblity: visible` or the real element `visiblity: hidden` and if yes -> Anti adblock.

**Comment by BlazeFTL** [comment]
Another issue `terabox.fun/sl/3lsTuo98O3`

script Location is 3p 
[Screenshot_20231124-115033_Firefox Nightly](https://github.com/uBlockOrigin/uBlock-issues/assets/139938337/a9631c73-8df8-4b1b-bc6a-1e931f41b9cc)

Is there any way to modify script values which arent inline ?... ideally what i do is replace the element they check with a element that wouldnt be blocked with rpnt

Would something like Replace work for such cases ?

**Comment by stephenhawk8054** [comment]
`$replace` could work, but only Firefox

**Comment by krystian3w** [comment]
Own replace need bumping uBo to 1.54.1+ or works like `trusted-` scriptlets and we should share own idea to AdGuard (So that their add-on would not require bumping in the Moz://a store)?

**Comment by gorhill** [comment]
> Own replace need bumping uBo to 1.54.1+ or works like trusted- scriptlets

I don't understand what is being said here.

**Comment by krystian3w** [comment]
>>> Would something like Replace work for such cases ?
>
>> $replace could work, but only Firefox
>
> Own replace need bumping uBo to 1.54.1+ or works like trusted- scriptlets


So I ask, if s adds a filter, will it start in uBo 1.54.0 with a differential update or a full filter list alone, because if AdGuard would add it I would have to wait for the next version of the add-on in December 2023 or January 2024.

**Comment by gorhill** [comment]
I still don't understand. `replace=` is available in 1.54.0 as a trusted-source filter option.

Differential update has nothing to do with this, I don't know why you mention this, and I also don't understand why you mention AdGuard.

**Comment by krystian3w** [comment]
I ask here because that's what BlazeFTL did.


My question is whether the `$replace=` filter added today to filters-2023 requires an update of stable ubo 1.54.0 to 1.54.1 to not break the Moz://a store.

**Comment by gorhill** [comment]
> AdGuard `$replace=` has to wait for a new version of the add-on

You have a source for this? I used the debugger in Firefox and I can see AdGuard parse `replace=` filters when updating AdGuard Base.
