### ISSUE TITLE
Custom filter list subscription sorting is inconsistent

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#262]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - I searched for "sort"
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
    - Nothing about display order

### Description

When a filter list doesn't have title, it should be sorted based on its URL, which is also used as the fallback title. 

### A specific URL where the issue occurs

N/A (`chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html`)

### Steps to Reproduce

Enter the dashboard, 3p tab, then add these custom subscriptions: 
```
http://localhost/test2.txt
http://localhost/test.txt​​​​​
http://localhost/a.txt
```
Save the change and observe the order they appear. 

### Expected behavior:

The lists should be sorted like this: 
```
http://localhost/a.txt
http://localhost/test.txt
http://localhost/test2.txt
```

### Actual behavior:

![image](https://user-images.githubusercontent.com/7283682/46622309-59f0a780-cae7-11e8-9b76-4c2a9142f964.png)

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Chrome 71
* Operating System and version: Win10

### Cause of issue

This snippet in `js/3p-filters.js` is responsible for sorting the entries, and it should fallback to URL instead of an empty string: 
![image](https://user-images.githubusercontent.com/7283682/46622354-81e00b00-cae7-11e8-9660-b52888fdd3ef.png)

**Comment by jspenguin2017** [comment]
Recommended fix: 
```js
let keyA = listDetails.available[a].title || listDetails.available[a].contentURL[0];
let keyB = listDetails.available[b].title || listDetails.available[b].contentURL[0];
return (keyA || '').localeCompare(keyB || '');
```

**Comment by gorhill** [comment]
Can no longer reproduce with latest stable, closing.
