### ISSUE TITLE
Error counter and sourceUrl button has visibility issues on mobile

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uBlock-issues#2621]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The error counter is half visible and sourceUrl button in asset viewer is completely hidden now.

### A specific URL where the issue occurs.

1p-filters.html & asset-viewer.html

### Steps to Reproduce

Add bad filters to your filters or open filter list with errors in asset viewer.

### Expected behavior

Elements to be visible.

### Actual behavior

<details>
<summary>Image 1 - My filters</summary>

![image](https://user-images.githubusercontent.com/84513173/235199004-669027e3-aeea-4eb6-93b0-771eafbe2ca7.png)

</details>
<details>
<summary>Image 2 - Asset viewer</summary>

![image](https://user-images.githubusercontent.com/84513173/235197324-6d16ca2c-6669-4fb1-8801-e5169b086c54.png)
</details>

### uBO version

1.49.0

### Browser name and version

Firefox Nightly 114.0a1

### Operating System and version

Android 11

**Comment by gorhill** [comment]
Why did you crop the screenshot so much? What is out there on the right that I should not see?

**Comment by Nojuuu** [comment]
I cropped it to save screen space, I can provide larger images if necessary.

**Comment by gwarser** [comment]
The error count does not fit on screen in portrait mode. It's fine in landscape.

<details>
<summary>Details</summary>


![image](https://user-images.githubusercontent.com/886325/235214612-184406c8-5a14-4cd9-8adb-53284c98fc6c.png)
![image](https://user-images.githubusercontent.com/886325/235214666-62c0cd45-71c8-4aa4-a97b-f869b7c6cf67.png)


</details>

**Comment by Nojuuu** [comment]
@gorhill 
Noticed that the bar now gets huge even when there is supposed to be nothing:

![image](https://user-images.githubusercontent.com/84513173/235357681-8149d1f6-625a-423e-a465-187840554039.png)

Seems to be caused by:

```css
.cm-search-widget .sourceURL[href=""] {
    visibility: hidden;
}
```

Maybe `display: none;` would be better?

**Comment by gorhill** [comment]
I used `visibility: hidden` because I do not want the "Errors: x ^ v" widget to change position horizontally when there is no source. I will use `display: none` for mobile layout only.
