### ISSUE TITLE
Expired cookies not removed

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#2622]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`youtube.com##+js(cookie-remover, /^ST/)` doesn't work. According to #1126, I believe it should.

### A specific URL where the issue occurs.

https://www.youtube.com/results?search_query=test

### Steps to Reproduce

* Add `youtube.com##+js(cookie-remover, /^ST/)` to your filters
* Search for different things on Youtube and observe how it sets a new cookie for every search
* Reload the page

### Expected behavior

All cookies that start with `ST` to be removed when the page is reloaded.

### Actual behavior

No cookie is removed.

### uBO version

1.49.0

### Browser name and version

Firefox stable

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
YT does not set any cookie starting with ST on my side - what type of cookie you want to remove?

![image](https://user-images.githubusercontent.com/886325/235289616-85fc9e86-6b23-4066-9ae7-2b3bdc17090b.png)

**Comment by gwarser** [comment]
I tried `^SO` and it's removed, `^PR` - `PREF` is recreated by JS.

**Comment by gorhill** [comment]
I see lot of `ST-...` cookie in Firefox at the provided URL (not logged in), but all of them are expired, so I guess that is why they are not reported when reading `document.cookie`.

How did you come to the conclusion "no cookie is removed"? Is it from `document.cookie` in dev console?
