### ISSUE TITLE
Ublock Origin not working on Yandex browser correctly anymore

### ISSUE THREAD

**Issue by akontsevich** [uBlockOrigin/uBlock-issues#2627]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Problem described [on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/1164b3s/comment/ji84scw/?utm_source=share&utm_medium=web2x&context=3). 

1. Several weeks ago problem appeared: browser was unable to load sites contents completely: CSS, scripts, images, etc. **_All_** sites did not work for me at all. Today I discovered the problem was in the uBlock Origin extension. After I removed it sites started to work for me.  
2. After I reinstalled the extension completely and  - it started to work for me again, however I see many filters are not loaded completely so some sites still show some ads.

### A specific URL where the issue occurs.

-

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### Configuration

-

**Comment by gorhill** [comment]
> some sites

You are going to provide more information, otherwise there is nothing we can do. You willfully skipped all the information asked from you.

First, go on a site which you say is showing ads, then lick the chat icon in the popup panel, then click _Troubleshooting information_, then copy-paste the content here.

Also, be sure you do not have other software on your system interfering with uBO, such as anti-virus or "cleaner¨, some of them are known to mess with uBO.

**Comment by Lawnless** [comment]
I have same problem about it, pages are not loading correctly, sometimes it stucks on loading. I disabled uBlock Origin and now Chrome works without any problem.

**Comment by akontsevich** [comment]
> > some sites
> 
> You are going to provide more information, otherwise there is nothing we can do. You willfully skipped all the information asked from you.

If You read attentively: I can't do this just because uBlock Origin blocks **everything**! So Github does not work at all! No scripts, no images, no styles - nothing, only text. Pages and buttons on them do not work. And person above has the same problem.

> First, go on a site which you say is showing ads, then click the chat icon in the popup panel, then click _Troubleshooting information_, then copy-paste the content here.

This I probably can do. Just a moment...
 
> Also, be sure you do not have other software on your system interfering with uBO, such as anti-virus or "cleaner¨, some of them are known to mess with uBO.

I'm on Linux so do not have such stuff.

**Comment by gorhill** [comment]
> If You read attentively

Then go to uBO's dashboard => _Support_ => Troubleshooting information is at the bottom.

**Comment by akontsevich** [comment]
Diagnostic info:

```
uBlock Origin: 1.49.2
Chromium: 110
filterset (summary): 
 network: 107906
 cosmetic: 61179
 scriptlet: 18896
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 0-0, never
  RUS-0: 39694-174, never
  easylist: 65879-213, never
  easyprivacy: 30899-1146, never
  plowe-0: 3746-944, never
  ublock-abuse: 70-0, never
  ublock-badware: 6952-0, never
  ublock-filters: 33716-129, never
  ublock-privacy: 323-1, never
  ublock-quick-fixes: 216-1, never
  ublock-unbreak: 1999-23, never
  urlhaus-1: 7286-1, never
filterset (user): [empty]
modifiedUserSettings: 
 suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: ?
 maxAssetCacheWait: 10 ms
```

Also filters do not load (can't  attach settings screenshot here) - I see exclamation marks on all filters and can't update them. - infinite progress on all of them.

**Comment by gorhill** [comment]
> `allReadyAfter: ?`

This means uBO was not yet ready, the filter lists were not yet fully loaded.

> `suspendUntilListsAreLoaded: true`

By default this is disabled on Chromium-based browser, so you checked this setting. It means to wait for uBO to be fully ready before allowing network requests.

So essentially, wait for uBO to be fully ready. If it takes very long, then you need to investigate the reason for this, typically uBO loads all the filter lists in less than a second.

**Comment by akontsevich** [comment]
> > `allReadyAfter: ?`
> 
> This means uBO was not yet ready, the filter lists were not yet fully loaded.

Yes, and seems the problem started few weeks ago.

> > `suspendUntilListsAreLoaded: true`
> 
> By default this is disabled on Chromium-based browsers, so you checked this setting. It means to wait for uBO to be fully ready before allowing network requests.

I know, but without this option the problem does exists as well. Also UBO shows warning some content was not blocked, so need to reload a page. After reloading yellow warning is still there.

> So essentially, wait for uBO to be fully ready. If it takes very long, then you need to investigate the reason for this, typically uBO loads all the filter lists in less than a second.

Yes, that was true month ago, now they loaded for ages without any luck.

**Comment by akontsevich** [comment]
> Which Chromium-based browser is this?

Yandex-browser.

**Comment by gorhill** [comment]
> without this option the problem does exists as well

If so, this is not a uBO issue, uBO won't block network requests if there is no filter to tell it to do so.

> Yandex-browser

Not officially supported, I can't vouch for it as we do no test it. Maybe @dimisa-RUAdList can say something about this. It's possible the browser has modified Chromium in a way that renders it incompatible with uBO.

**Comment by akontsevich** [comment]
It worked fine for years, problem started about month ago. @Lawnless has the same problem with Chrome and same reported here: https://www.reddit.com/r/uBlockOrigin/comments/1164b3s/ublock_origin_not_working_on_chrome_anymore/?utm_source=share&utm_medium=web2x&context=3

**Comment by gorhill** [comment]
>  @Lawnless has the same problem

You don't know this, he didn't provide any information.

> worked fine for years, problem started about month ago

Yes, and maybe the changes in the browser caused this.

**Comment by gorhill** [comment]
Here it says Yandex browser forbids uBO: <https://www.reddit.com/r/uBlockOrigin/comments/xva1jl/yandex_browser_does_not_support_ublock_origin/>.

How did you get around installing uBO for it?

**Comment by akontsevich** [comment]
From here: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm/related?utm_source=uvpn.me%5C  - it allows to install any Chrome extension.

**Comment by gorhill** [comment]
Since you are using linux, I would be curious to know if you have the same issue with Chromium.

**Comment by dimisa-RUAdList** [comment]
@akontsevich 
The Yandex browser was created for the purpose of displaying ads, this is its main task. It prevents blockers from working on its own and partner domains, and this feature is constantly being improved. The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

**Comment by akontsevich** [comment]
> Since you are using linux, I would be curious to know if you have the same issue with Chromium.

@gorhill works fine in Chromium.

> The Yandex browser was created for the purpose of displaying ads, this is its main task. It prevents blockers from working on its own and partner domains, and this feature is constantly being improved. The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

I see. Thanks for the link.

**Comment by akontsevich** [comment]
> The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).

Yes, this works, thanks @dimisa-RUAdList! Today [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) in ADblock stopped to work for me for some reason. In UBO-dev works fine!

**Comment by krystian3w** [comment]
On  partner sites, ads cut out MV3 add-ons by network  DNR rules like uBO Lite, but even there they can add a limit per month/year/years.

**Comment by akontsevich** [comment]
> > The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
> 
> Yes, this works, thanks @dimisa-RUAdList! Today [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) in ADblock stopped to work for me for some reason. In UBO-dev works fine!

Now, dev version stopped to work again. And can't update filters again.

**Comment by akontsevich** [comment]
> Now, dev version stopped to work again. And can't update filters again.

Works again, weird!

**Comment by krystian3w** [comment]
Maybe list was updated on every hour.

**Comment by akontsevich** [comment]
> Maybe list was updated on every hour.

No, I was unable to update lists yesterday, today they updated quickly.

**Comment by saber716rus** [comment]
> > Since you are using linux, I would be curious to know if you have the same issue with Chromium.
> 
> @gorhill works fine in Chromium.
> 
> > The Yandex browser was created for the purpose of displaying ads, this is its main task. It prevents blockers from working on its own and partner domains, and this feature is constantly being improved. The [dev-version of uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) is the least affected by this effect. Install it instead of the usual uBlock Origin and use the [recommended settings file](https://github.com/easylist/ruadlist/wiki/RU-Adlist-links).
> 
> @dimisa-RUAdList I see. Thanks for the link. For now switched to [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb/reviews?ref=store-rating) - works fine.

Thanks! Yes, the development version works perfectly.
