### ISSUE TITLE
New format https://adblockplus.org/en/subscriptions

### ISSUE THREAD

**Issue by PhoenixIndigo** [uBlockOrigin/uBlock-issues#2628]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

uBlock Does not open subscriptions https://subscribe.adblockplus.org/?location=https%3A//easylist-downloads.adblockplus.org/easylist.txt&title=EasyList on https://adblockplus.org/en/subscriptions

### A specific URL where the issue occurs.

https://adblockplus.org/en/subscriptions

### Steps to Reproduce

I press subscription: https://subscribe.adblockplus.org/?location=https%3A//easylist-downloads.adblockplus.org/easylist.txt&title=EasyList
And the subscription does not come off

### Expected behavior

Subscription should open: moz-extension://df8a06e0-df8b-495f-97cf-d78d48140c4b/asset-viewer.html?url=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt%3Fa%3D0&title=Easylist&subscribe=1
https://subscribe.adblockplus.org/?location=https%3A//easylist-downloads.adblockplus.org/easylist.txt&title=EasyList

### Actual behavior

Link gives an error: the server was not found

### Configuration

[ublock-backup](https://pastebin.com/u/GodIndigo)
```
uBlock Origin: 1.49.0
Firefox: 112
filterset (summary): 
 network: 174954
 cosmetic: 268987
 scriptlet: 41585
 html: 1135
listset (total-discarded, last-updated): 
 added: 
  https://easylist-downloads.adblockplus.org/bitblock.txt: 27675-862, 9m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1618-0, 9m
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 27464-220, 9m
  https://filters.adtidy.org/extension/ublock/filters/3.txt: 43377-17745, 9m
  https://secure.fanboy.co.nz/enhancedstats.txt: 2988-12, 9m
  https://shorturl.at/cfqKV: 9-0, 8m
  adguard-generic: 70435-6461, 9m
  adguard-mobile: 8711-101, 9m
  adguard-annoyance: 67783-7811, 9m
  adguard-social: 20380-55, 9m
  fanboy-annoyance: 90425-32626, 9m
  ublock-annoyances: 4927-9, 9m
 default: 
  user-filters: 2-0, never
  ublock-filters: 34406-154, 9m
  ublock-badware: 7002-1, 9m
  ublock-privacy: 443-2, 9m
  ublock-abuse: 70-70, 9m
  ublock-unbreak: 2009-9, 9m
  ublock-quick-fixes: 214-1, 9m
  easylist: 66182-884, 9m
  easyprivacy: 32298-964, 9m
  urlhaus-1: 6796-1, 9m
  plowe-0: 3741-9, 9m
  RUS-0: 39710-3660, 9m
filterset (user): [array of 2 redacted]
switchRuleset: 
 removed: 
  no-csp-reports: * true
modifiedUserSettings: 
 advancedUserEnabled: true
 cloudStorageEnabled: true
modifiedHiddenSettings: 
 userResourcesLocation: [redacted]
supportStats: 
 allReadyAfter: 1139 ms (selfie)
 maxAssetCacheWait: 558 ms
```

**Comment by gwarser** [comment]
To which filter list you would like to subscribe? This looks like a huge list of resources, but pretty much all are ABP-specific or already in "Filter lists" tab in uBO. If you rally like, right-click on the link -> uBlock Origin -> Subscribe to filter list.

**Comment by PhoenixIndigo** [comment]
I have the necessary subscriptions already added. Nevertheless, I want to open subscriptions that I do not know through the context menu about which no one knows for example: https://raw.githubusercontent.com/easylist/master/raadlist-ubo.txt And not only through the outdated format:  abp:subscribe?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt not supported by forums and github, but through links built by the designer (https://adblockplus.org/abp_linkfactory) link https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Feasylist%2Fruadlist%2Fmaster%2FRuAdList-uBO.txt!

<details><summary>Orig:</summary>

Нужные подписки у меня уже добавлены. Тем не менее мне хочеться открывать подписки отсутствующие у меня не через контекстное меню о котором никто не знает например: https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt и не только через устаревший формат abp:subscribe?location=https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt не поддерживаемый форумами и github, а через построенный конструктором ссылок (https://adblockplus.org/abp_linkfactory) ссылку https://subscribe.adblockplus.org/?location=https%3A%2F%2Fraw.githubusercontent.com%2Feasylist%2Fruadlist%2Fmaster%2FRuAdList-uBO.txt!
</details>

**Comment by PhoenixIndigo** [comment]
And why doesn’t it work on https://adblockplus.org/abp_linkfactory , but works on https://easylist.to/ and https://forums.lanik.us/viewtopic.php?f=102&t=22512-%D0%BE-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B5-ru-adlist-%D0%B8-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%D1%85?

**Comment by PhoenixIndigo** [comment]
And why doesn’t it work on https://adblockplus.org/abp_linkfactory, but works on https://easylist.to/ and opening the subscription with an empty tab on https://forums.lanik.us/viewtopic.php?f=102&t=22512-%D0%BE-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B5-ru-adlist-%D0%B8-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%D1%85 ?

**Comment by gorhill** [comment]
`adblockplus.org` is not on the list of sites for which a simple click can be used to subscribe. It's not recommended to use lists at that site in uBO -- uBO has its own set of lists optimized for uBO.

In any case if you really want to subscribe to a list there, you can always right-click on the subscription link and select _"Subscribe to filter list..."_ entry.

**Comment by PhoenixIndigo** [comment]
Why are these difficulties with the menu of the right button? I just want to see a list with detailed inserts in https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt

**Comment by gorhill** [comment]
That is a stock uBO list, just click the _eye_ icon beside the list in _Filter lists_ pane.

**Comment by PhoenixIndigo** [comment]
I would like to open such subscriptions without [Open in Browser](https://addons.mozilla.org/firefox/addon/open-in-browser/) as https://subscribe.adblockplus.org/?location=https://pastebin.com/dl/wLGhx18c

**Comment by PhoenixIndigo** [comment]
I would like to directly discover such subscriptions without [Open in Browser](https://addons.mozilla.org/firefox/addon/open-in-browser/), like https://subscribe.adblockplus.org/?location=https://pastebin.com/dl/wLGhx18c

**Comment by gorhill** [comment]
Sorry I don't understand what you are asking. I can right-click on your second link and select _"Subscribe to filter lists..."_, which will load the list in uBO's asset viewer. Just don't click the _Subscribe_ button if you just want to see the list content without subscribing.

**Comment by PhoenixIndigo** [comment]
Yes supposedly hemorial. But why is it blocked by https://pastebin.com/dl/wLGhx18c если [Open in Browser](https://addons.mozilla.org/firefox/addon/open-in-browser/) it opens it
![изображение](https://user-images.githubusercontent.com/107413021/235361450-f56e9365-0c8c-45a9-a812-852453846f09.png)
![изображение](https://user-images.githubusercontent.com/107413021/235361459-8fd1550a-bdbe-48b9-b912-5658e6185fdb.png)
![изображение](https://user-images.githubusercontent.com/107413021/235361497-2a212339-d383-45d0-b7d4-9c86620c0278.png)

**Comment by gorhill** [comment]
> why is it blocked

That's just a server behavior, out of control of uBO. You would probably get the same result if you removed the `Referer` header from the HTTP request headers. The serve message says to use `/raw/wLGhx18c` instead, so this works:

 https://subscribe.adblockplus.org/?location=https://pastebin.com/raw/wLGhx18c
