### ISSUE TITLE
Element zapper just stopped working on https://www.rawstory.com

### ISSUE THREAD

**Issue by photonboy** [uBlockOrigin/uBlock-issues#263]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Just as the subject line says.  Works fine on all other sites I use.  Only have this problem on rawstory and it was working on that site fine yesterday.
]

### A specific URL where the issue occurs

[https://www.rawstory.com]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[Element zapper working]

### Actual behavior:

[Element zapper not working.  Does nothing]

### Your environment

* uBlock Origin version:  1.17.0
* Browser Name and version:  Firefox 62.0.3
* Operating System and version:  macOS 10.13.6 (17G65)

**Comment by gwarser** [comment]
Enable cosmetic filtering - eye icon in uBO popup.

**Comment by photonboy** [comment]
Doing that killed the site.  Only see header and footer now, all content gone.

**Comment by gwarser** [comment]
Zapper is working now?

**Comment by gwarser** [comment]
Fire up [logger](https://github.com/gorhill/uBlock/wiki/The-logger) and [DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector) to find out which filter causes this.

**Comment by gwarser** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3212
