### ISSUE TITLE
Adblock-Blocker showing up

### ISSUE THREAD

**Issue by manuallypure** [uBlockOrigin/uBlock-issues#2633]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

click the link and open RTL. The following window will show the adblock blocker as you can see in the screenshot.

### A specific URL where the issue occurs.

https://nydus.org/stream/

### Steps to Reproduce

1. click the link
2. click RTL
3. wait a few seconds until the anti adblock message shows up.
<img width="1012" alt="Screenshot 2023-05-04 at 18 25 05" src="https://user-images.githubusercontent.com/13890764/236269526-f629e229-db58-4339-af25-51cc4b962d1b.png">

### Expected behavior

anti adblock alert comes up

### Actual behavior

it just shows up and stays there

### uBO version

1.49.2

### Browser name and version

Firefox 112.0.2

### Operating System and version

macOS Ventura 13.3

**Comment by gorhill** [comment]
cc @Khrin
