### ISSUE TITLE
Feature Request: one-click toolbar icon/tool for element zapper

### ISSUE THREAD

**Issue by zesty** [uBlockOrigin/uBlock-issues#2635]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Element zapper is the most frequent reason to interact with the extension at all. It should be maximally convenient to do so. A toolbar icon to activate element zapper would be great for this (or possibly a keyboard shortcut).

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

1. try to customize the toolbar

### Expected behavior

add element zapper to toolbar

### Actual behavior

no option to add element zapper to toolbar

### uBO version

1.49.2

### Browser name and version

firfox 112.0.2 

### Operating System and version

ubuntu linux  5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gorhill** [comment]
What you are asking is not possible, extensions are not free to add toolbar icons as they see fit.

> or possibly a keyboard shortcut

See <https://github.com/gorhill/uBlock/wiki/Keyboard-shortcuts>.
