### ISSUE TITLE
Generic blocking filter doesn't work

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#2639]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBO doesn't block network requests that match to a certain generic blocking filter.

If I make the same rule as domain specific or add slash at the beginning of the rule, it works.

Doesn't work:
`-gravito-cmp$script`

Works:
`-gravito-cmp$script,domain=tekniikanmaailma.fi`

Also works:
`/om-gravito-cmp$script`

### A specific URL where the issue occurs.

`https://tekniikanmaailma.fi/star-wars-jedi-survivor-on-vuoden-toistaiseksi-huonoin-pc-kaannos-kehitystiimi-pyysi-jo-pelaajilta-anteeksi/`

### Steps to Reproduce

1. Add filter: `-gravito-cmp$script` to own filters
2. Open the page: `https://tekniikanmaailma.fi/star-wars-jedi-survivor-on-vuoden-toistaiseksi-huonoin-pc-kaannos-kehitystiimi-pyysi-jo-pelaajilta-anteeksi/`
3. Check the logger. It doesn't block matching network requests.

### Expected behavior

uBO would block matching network requests.

### Actual behavior

uBO didn't block matching network requests.

### uBO version

1.49.2

### Browser name and version

Firefox 112.0.2 (issue also present on Chrome)

### Operating System and version

Windows 10

**Comment by peace2000** [comment]
This issue seems to begin in uBO version of 1.47.0. No issues in 1.46.0.

I consider this serious enough so I'll tag @gorhill

**Comment by gwarser** [comment]
Starting with `*` does not help, but ending with `/` or removing the `cmp` at the end works.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/8ea3b0f64c7a13c32cae1650c6b5768d9618031c

**Comment by peace2000** [comment]
Running the new test version.

`-gravito-cmp$script` works properly now. However, these forms don't work:

`gravito-cmp$script`
`gravito$script`

The latter might not be a common pattern in network requests but shouldn't they still work?

**Comment by gorhill** [comment]
> these forms don't work

Yes, as per documentation: <https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#hosts-files>
