### ISSUE TITLE
UI Search field and it's search counter interfere with each other / unreadable

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uBlock-issues#264]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - I searched for "search" and "search field" both old and new uBO issues tracker
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Search field and it's search counter interfere with each other making the search count unreadable if the search phrase is longer.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

- 3rd-party filters pane (after clicking at a list name and then it gets opened in a new tab)
`moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/asset-viewer.html?url=ublock-filters`

- My filters pane
`moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/dashboard.html#1p-filters.html`

- Whitelist pane
`moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/dashboard.html#whitelist.html`

### Steps to Reproduce

1. Go to any Pane listed above
2. Enter a longer search phrase for. ex. `##+js(abort-on-property-write.js, Fingerprint2)`
3. Notice that the search count number and a part of the search phrase are unreadable

Firefox
![ff_long](https://user-images.githubusercontent.com/43844449/46675333-77ed0380-cbde-11e8-8de8-be729eba5c52.png)

Opera
![o_long](https://user-images.githubusercontent.com/43844449/46675340-7c192100-cbde-11e8-912f-7a37a0901d83.png)

4. Shorten the search phrase to like `##+js(abort-on-` (on Firefox) or to `##+js(abort-on-prope` (on Opera)
5. Notice the issue is gone.

Firefox
![ff_short](https://user-images.githubusercontent.com/43844449/46675520-e5009900-cbde-11e8-915e-0e1d862f453a.png)

Opera
![o_short](https://user-images.githubusercontent.com/43844449/46675412-98b55900-cbde-11e8-8748-048001a4353d.png)

### Expected behavior:

[What you expected to happen]

Search field and it's search counter shouldn't interfere with each other and shuld be readable when entering a longer search phrase. Either move the search counter outside the search field and put it in it's own field, or make some kind of separation in the search field between the search phrase and the search count number which will remove the collision, if not possible then maybe just make the search field longer.

### Actual behavior:

[What actually happened]

Search field and it's search counter interfere with each other making the search count unreadable if the search phrase is longer. 

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox 62.0.3 & Opera 56.0.3051.36
* Operating System and version: Win 7 U SP1 64

Also I have a secondary similiar derivative issue / enhancement ( I think it's not worth to open a separate issue just for it so I put it there) : I noticed a lack of the search count in search fields of:

- My rules pane
`moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/dashboard.html#dyna-rules.html`

(Screenshoot from Firefox)
![ff_my_rules](https://user-images.githubusercontent.com/43844449/46675603-124d4700-cbdf-11e8-96aa-a0047bf23ca1.png)

- The Logger
`moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/logger-ui.html`

(Screenshoot from Firefox)
![ff_logger](https://user-images.githubusercontent.com/43844449/46675615-18dbbe80-cbdf-11e8-959e-0e4b428e3cc7.png)

Maybe it would be good to add it there to.

**Comment by gorhill** [comment]
> I noticed a lack of the search count in search fields of:

That is not a search field, that is a filter field. The number of line in the editor is the number of hits.

**Comment by krystian3w** [comment]
```css
@-moz-document url-prefix("moz-extension://4e42f46c-7391-4300-81d4-54a4d5e25d6e/") {
    .cm-search-widget > span > input[type="text"], #ruleFilter > input[type="text"] {
        width: 80vw;
    }
    @media screen and (max-width: 463px) {
        .cm-search-widget > span > input[type="text"], #ruleFilter > input[type="text"] {
            width: auto;
        }
    }
}
```

in `userContent.css` ([UserContent.css](http://kb.mozillazine.org/UserContent.css "http://kb.mozillazine.org/UserContent.css") <sup>(en)</sup>, [Zastosowanie_userChrome.css_i_userContent.css](https://mozillapl.org/wiki/Zastosowanie_userChrome.css_i_userContent.css "https://mozillapl.org/wiki/Zastosowanie_userChrome.css_i_userContent.css") <sup>(pl)</sup>)?

[chrome.zip](https://github.com/uBlockOrigin/uBlock-issues/files/2477841/chrome.zip) - created for `4e42f46c-7391-4300-81d4-54a4d5e25d6e` installation uBO addon.



Chrome / Opera does not have simililar workaround method.
