### ISSUE TITLE
New widget added on 1.49 used to filter rows on popup panel has "layering" problems on Android Firefox.

### ISSUE THREAD

**Issue by Exploding-Joysticks** [uBlockOrigin/uBlock-issues#2640]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://user-images.githubusercontent.com/132830739/236683221-e75556cc-daab-45cd-9a56-a6a846b26192.mp4

The Filter icon doesn't disappear when scrolling down, it also overlaps with the "Make changes permanent" and "Revert changes" buttons and can be clicked when over those buttons, but i forgot to record that.

### A specific URL where the issue occurs.

https://www.reddit.com

### Steps to Reproduce

1. Using mobile uBO, go to a webpage with tons of entries on the firewall (like Reddit);
2. Open uBO's popup and scroll down on the firewall section;

### Expected behavior

The filter widget should "slide under" the power button's "box", just like everything else that scrolls.

### Actual behavior

The filter widget stays on top of the power button's "box" and overlaps with other buttons.

### uBO version

1.49.2

### Browser name and version

Firefox 112

### Operating System and version

Android 10

**Comment by gwarser** [comment]
Fixed.

Side note: clicking a second time should hide the widget - not sure where to click to hide it now.
