### ISSUE TITLE
"a network error prevented the resource from being updated" when extension permissions set to "specific sites"

### ISSUE THREAD

**Issue by atifhussain18** [uBlockOrigin/uBlock-issues#2641]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Some of the filters give the a network error prevented the resource from being updated error when the permissions are set to "specific sites" instead of "all sites". 

These are the filters causing error - 
![image](https://user-images.githubusercontent.com/47064709/236816279-dd2535ad-8400-43b0-9763-0fe9bebed3b6.png)

This is the logger status-
![image](https://user-images.githubusercontent.com/47064709/236819644-f6a05e86-c6c2-4276-af8a-00a98e77b6e1.png)

After I rever the permission back to "all sites" the issue goes away thus signifying that the permissions are what are causing the issue-
![image](https://user-images.githubusercontent.com/47064709/236817364-acfd3d49-fe30-4dd9-9020-2e1dcd4e7fd2.png)

### A specific URL where the issue occurs.

https://github.com/

### Steps to Reproduce

1. Have a new ublock origin extension installation.
2. Set the extension permission to "specific sites".
3. Enable the following filters 
![image](https://user-images.githubusercontent.com/47064709/236816909-f6db406b-e5bb-42f6-b07f-8bcb8682e5c1.png)
4.  Update them and the error a network error prevented the resource from being updated will pop up

### Expected behavior

Filters get updated without issues

### Actual behavior

Some filters don't update

### Configuration

Default settings.

**Comment by gorhill** [comment]
You picked the issue template which says:

> File a bug report from uBlock Origin (uBO)'s "Support" pane, which auto-fills essential information.

As a result, there is no key information provided with your report, it's not actionable. Provide the troubleshooting information from _Support_ pane.

**Comment by gwarser** [comment]
Happens for hosters without CORS. This was discussed not to long ago(?).

**Comment by gwarser** [comment]
Not in our repo? https://github.com/uBlockOrigin/uBlock-discussions/discussions/729#discussioncomment-5464546

**Comment by gorhill** [comment]
So a server issue? Since we do not own those servers, it's an issue outside our control.

**Comment by gwarser** [comment]
I don't think using uBO with permission only to some domain is supported at all.

**Comment by gorhill** [comment]
Be careful to keep adding notes for edge cases in the wiki. The primary purpose of the wiki is as a reference to quickly find answer to questions, not to document every single egde cases out there, which in the end will sabotage the primary purpose -- nobody wants to be faced with a lot of wall of text with a lot of irrelevant when searching for the most common topics. As a dev, I appreciate when I can get to an answer to my question in a reference documentation with having to go through only the essential information.

**Comment by atifhussain18** [comment]
> So a server issue? Since we do not own those servers, it's an issue outside our control.

This same issue is present on adguard extension too. But it is easily fixed with that extension by providing site access to the particular website from where the filter is from. For e.g. if a filter list is hosted on gitlab, allowing site access on gitlab.com will allow the filters to be updated. Unfortunately this doesn't work on ublock origin.

**Comment by iam-py-test** [comment]
Try allowing access to all these domains (the github.io ones shouldn't be needed):
```
ublockorigin.github.io
curbengh.github.io
raw.githubusercontent.com
cdn.jsdelivr.net
cdn.statically.io
publicsuffix.org
```
Not sure they are all needed
