### ISSUE TITLE
Per-site JavaScript blocking breaks page DOM that results in CSS issues (affected: Gatsby JS framework websites)

### ISSUE THREAD

**Issue by yaroslav** [uBlockOrigin/uBlock-issues#2642]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Detailed issue: https://github.com/gatsbyjs/gatsby/issues/38065

Gatsby is a web framework for building websites. It includes a very convenient component called GatsbyImage for resizing and placing images. The component also includes all types of image placeholder support: this way, initially the user seems some kind of placeholder, the browser loads the desired image, and when the image is loaded, the framework uses JavaScript to switch it.
For years now, it supported a way to do so without JavaScript, using `<noscript>` tags. One tag goes into the `<head>` and enables the styles that should only apply when nice, placeholder-y way of loading images is not available. Then, for every image that has a placeholder, we have both tags for JavaScript-enabled way of loading and a `<noscript>` tag in case JavaScript is disabled.

If we disable JavaScript using Firefox native `about:config` ways, everything works as intended.

When we use a uBO site-specific JavaScript disable for a Gatsby-powered site, the following happens:

1. The `<noscript>` in head is replaced with a `<span>` tag. A `<span>` should not be in the header, so that probably breaks things—or at least the validation. Can be fixed with changing the selector here https://github.com/gorhill/uBlock/blob/master/src/js/scriptlets/noscript-spoof.js#L33 to only affect `body noscript`.
2. It also replaces all other `<noscript>` elements with `<span style="display: inline !important">`. Because of that, rules with selectors like `.gatsby-image-wrapper noscript [data-main-image]` (an actual selector Gatsby uses) no longer work, because there is no `noscript` tag anymore.

I'm not sure of the reasoning behind actually replacing `<noscript>` tags with `span`s (obviously you had good reasons), but in the end it may (and it does) break header styles and selectors quite easily. Not sure what the solution might be here.

### A specific URL where the issue occurs.

gatsbyjs.com

### Steps to Reproduce

1. Install the latest uBO and Firefox Stable or Developer Edition.
2. Visit gatsbyjs.com.
3. Notice a graphic banner at the right side of the page.
4. Install uBO, activate site-specific JS blocking, reload the page.
5. Notice that the image disappeared.

### Expected behavior

The image works using `noscript` tags and selectors exactly as in Firefox `javascript.enable=false` mode.

### Actual behavior

The image disappears.

### uBO version

1.49.0

### Browser name and version

Firefox Stable 112.0.2 (64-bit)

### Operating System and version

macOS 13.3.1

**Comment by gorhill** [comment]
> I'm not sure of the reasoning behind actually replacing `<noscript>` tags with spans

Because the browser does not activate `noscript` tags when blocking JS using CSP, we have to change them to `<span>` tags to ensure their content is activated.

Not converting to `<span>` would still lead to the same issue described, on top of breaking all the sites where conversion does accomplish something useful.

There is no browser API allowing us to force the browser to parse `<noscript>` tags.

**Comment by gorhill** [comment]
I've updated the documentation to be more clear that when using no-scripting switch, activation of `noscript` tags may not lead to perfectly mimicking real, browser-activated `noscript` tags: <https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting>.

**Comment by gorhill** [comment]
Labelling as _wonfix_, but this should be more accurately _cantfix_.

**Comment by yaroslav** [comment]
@gorhill thanks for the explanation.

However, what bugs me is still the fact that uBO does `span`s (with inlined styles!) in the `<head>`. Using them in `body` is at least valid. What other options are there, maybe use some other tag, ignore `head` (very easy to do), or just replace `<noscript>` with nil?

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, if I understand correctly, current uBO's "no-scripting" is setting CSP `script-src`? What is the difference of it versus using CSP `sandbox`:

```
sandbox allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-storage-access-by-user-activation allow-top-navigation allow-top-navigation-by-user-activation allow-top-navigation-to-custom-protocols
```

?

If I'm not wrong, using `sandbox` without `allow-scripts` will activate websites' `noscript` status and it won't cause side effects like current?

---

For example, using the website `https://www.gatsbyjs.com/`

- If I use `no-scripting: gatsbyjs.com true`, the image on the right side does not appear

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/b6f38ebb-ca7a-41ea-beb7-1d97843cad8c)

</details>

- If I use

```adb
||gatsbyjs.com^$csp=sandbox allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-storage-access-by-user-activation allow-top-navigation allow-top-navigation-by-user-activation allow-top-navigation-to-custom-protocols
```

I can see the image appears normally

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/746943a8-d1e6-4092-87d6-d17440376f60)

</details>

**Comment by gorhill** [comment]
The image which does not appear is supposed to show up because of the following CSS declaration:

    .gatsby-image-wrapper noscript [data-main-image]{opacity:1!important}

Since `noscript` is replaced by `span` in the DOM, the declaration does not take effect.

**Comment by stephenhawk8054** [comment]
> uBO to still be able to list all the external script resources

Oh I see. I didn't know you wanted this. Yeah then I think it's not possible to both honor browser's native `noscript` and list external scripts since browser's fixed behavior of `noscript` is ignoring all of the scripts from the get go.

Could it be possible to have a way of honoring `noscript` tags by `sandbox` approach with toggles? I think being more compatible with websites that follow the designs of `noscript` would be quite good, as I also met some websites with the same breakages like above. I mean I can use `csp` filters but it's inconvenient when excluding the sites.

**Comment by gorhill** [comment]
I could add an advanced setting for the CSP directive to use for no-scripting. Is it what you are asking?

**Comment by stephenhawk8054** [comment]
Yes, that would be good.

**Comment by stephenhawk8054** [comment]
Confirm it works for `https://www.gatsbyjs.com/` in the new dev build 👍 I'll use it for a while to see how it goes.

**Comment by stephenhawk8054** [comment]
@gorhill There's some issues:

1. Add

```
sandbox allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-storage-access-by-user-activation allow-top-navigation allow-top-navigation-by-user-activation allow-top-navigation-to-custom-protocols
```

to `noScriptingCSP` and tick on `Disable JavaScript`

2. Add the filter

```adb
||youtube-nocookie.com/embed/$frame,redirect=click2load.html
```

3. Go to

```yml
https://meteofrance.com/le-changement-climatique/climadiag-chaleur-en-ville
```

The youtube iframes only show `external-link` instead of youtube's iframe link

![image](https://github.com/user-attachments/assets/42a5f46d-ed0c-4d16-91b8-575f675d9315)

**Comment by gorhill** [comment]
Right, it was reported in the past that `sandbox` was causing an issue for embedded uBO frame: <https://github.com/uBlockOrigin/uBlock-issues/issues/1420>

![image](https://github.com/user-attachments/assets/b4b7044f-90c0-44e1-8bff-5fc6c7d70e14)

**Comment by stephenhawk8054** [comment]
Hovering on the link still shows the destination URL

```
moz-extension://[id]/web_accessible_resources/click2load.html?secret=ll8myc&url=https%3A%2F%2Fwww.youtube-nocookie.com%2Fembed%2F6pmKNZ8Ma2o
```

**Comment by gorhill** [comment]
The `href` is untouched from its default value in `click2load.html`, the empty string. Firefox just decided the URL of the frame would be used for blank links.

It can be argued this is a browser issue -- `sandbox` should not interfere with extensions and prevent their JS from executing, as they act on behalf of the user.

**Comment by stephenhawk8054** [comment]
Hmm... Looks like using `sandbox` breaks element picker/zapper as well. Scriptlets still work though.

**Comment by gorhill** [comment]
I revisited the implementation after some more thoughts about it and taking into account the comment above re. `head`.
