### ISSUE TITLE
Bug: country flags are not displayed in the filter lines

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2645]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Country flags are not displayed in the filter lines

### A specific URL where the issue occurs.

`/dashboard.html#1p-filters.html`

### Steps to Reproduce

Open: `/dashboard.html#1p-filters.html`

### Expected behavior

Country flags will be shown

### Actual behavior

Dash icons are displayed instead of flag icons

<details>
<summary>Screenshot(s)</summary>

![uboflag](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/29f0d5d1-067e-497d-a3ff-993822a7f5ad)

</details>

### Configuration

I get complaints from users mostly using this configuration:
uBO 1.49.2 
Google Chrome 113

**Comment by krystian3w** [comment]
Maybe needed is use small emoji flag font?

On Windows 7 with Chrome 109:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/df30c12a-0f9e-47e3-beef-2da764536b4c)

**Comment by gorhill** [comment]
Fixed with <https://github.com/gorhill/uBlock/commit/39a8aaa39be752e285506ec8dd766e917748fa13>.

I thought the browser themselves would guarantee these unicode-based pictograms would work.

**Comment by dimisa-RUAdList** [comment]
By the way, there is no flag of Belarus in the RU AdList line.

**Comment by krystian3w** [comment]
The Flag of Egypt could be given.

:egypt:

**Comment by gorhill** [comment]
> Arabic list has been dropped to the last

Yes, saw this yesterday after I committed -- will fix.

**Comment by gorhill** [comment]
> The Flag of Egypt could be given

I have considered the [Arab League flag](https://flagpedia.net/organization/al) yesterday, just not sure about this. It's also ok to not have a flag.

**Comment by gorhill** [comment]
The title of stock lists is taken from `assets.json`, not the list themselves. Only for imported lists is the title taken from the list.

**Comment by gorhill** [comment]
The asset viewer shows the list as it was fetched, uBO does not modify its content -- this has always been the case, the title of stock lists shown in _"Filter lists"_ never matched the `Title:` field in the list.

**Comment by gorhill** [comment]
There is, it's a hair space

**Comment by gorhill** [comment]
I was originally using thin space, but since I got rid of commas to save horizontal space, I got worried the ccTLD label would be too far to make it obvious it's related to the flag, hence I went with hair space. But in the end if people are customizing the rendering (such as zoom 90%), it would be unreasonably burdening to try to accommodate all these personal customizations.

**Comment by krystian3w** [comment]
Certainly, as an aside, flags also work with manually added lists.


As I checked quite OK it works when the flag is the first character, the middle or even the last.

**Comment by gorhill** [comment]
> flags also work with manually added non-stock lists

The code just convert Unicode flags to `img`, so if a Unicode flag appears in the title, it should work. Only problem is that I didn't create a table with conversion for all flags, just the one currently in stock list -- it would just take time to go through all the flags.
