### ISSUE TITLE
cdnURLs for the PersianBlocker list

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2647]
As it currently stands, the PersianBlocker list has no cdnURLs:
https://github.com/gorhill/uBlock/blob/42106cf5ff390304e0bebc63f03a7c109bd84106/assets/assets.json#L493

So I propose:

contentURL:
`https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlocker.txt`

cdnURLs:
`https://cdn.statically.io/gh/MasterKia/PersianBlocker/main/PersianBlocker.txt`

`https://cdn.jsdelivr.net/gh/MasterKia/PersianBlocker@main/PersianBlocker.txt`

https://github.com/uBlockOrigin/uAssets/discussions/17921

**Comment by krystian3w** [comment]
For now unpopular: https://www.jsdelivr.com/package/gh/MasterKia/PersianBlocker?tab=stats

**Comment by gorhill** [comment]
Wasn't `statically.io` added to `contentURL` because `github.com` would be blocked in Iran sometimes?

**Comment by gorhill** [comment]
I think one fallback is fine, until there are reports it's not enough. Most update will go through `cdnULs` anyways, `contentURL` is for forced updated.
