### ISSUE TITLE
Youtube detects adblocker

### ISSUE THREAD

**Issue by mbcz123** [uBlockOrigin/uBlock-issues#2648]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/23220039/814f49fd-8eb6-4f12-baaa-c0d27175eb1d)

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=Tpbs-J6Aihk

### Steps to Reproduce

randomly occurs when opening youtube videos

### Expected behavior

Do not show up the warning

### Actual behavior

randomly occurs when opening youtube videos

### Configuration

```

**Comment by mbcz123** [comment]
So there's nothing I can do about it?

**Comment by mbcz123** [comment]
> https://www.reddit.com/r/youtube/comments/13cfdbi/comment/jjh5kkk/

So there's nothing I can do about it?

**Comment by krystian3w** [comment]
If the screenshot isn't a fake then you can expect Eyeo to force the EasyList project to no longer address ads there, or at worst remove filters strongly associated with YouTube.

**Comment by Yuki2718** [comment]
> 
> So there's nothing I can do about it?

There's a lot, rather we need cooperation by those who see the popup as none of us can reproduce. Please comment on the right place which is [here](https://github.com/uBlockOrigin/uAssets/issues/7636). Please respect the template and do not edit/remove items, this repository is strictly for bugs in uBO itself and not for filter issues as written in
> * []  I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

**Comment by seedoils** [comment]
Do we know whether the anti-adblock is US-specific?

**Comment by catfromplan9** [comment]
Suppose we will have to wait for this "feature" to roll out to the general public...
