### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by UnFranco-Canadien** [uBlockOrigin/uBlock-issues#265]
Bonjour Gorhill,

uBlock Origin installe un cookie dans le navigateur Firefox qui est détectable et effaçable seulement avec CCleaner. Je ne sais pas si c'est à cause de la navigation privée dans Firefox ?

Voici une capture d'écran : https://www.casimages.com/i/181009074639468148.png.html

Windows 8.1 64 Bit et Windows 10 64Bit, Firefox 62 64Bit.

Merci pour votre travaille.

**Comment by gwarser** [comment]
Can this be uBO IndexedDB? If you open uBlock Origin Dashboard and look in address bar will it show `moz-extension:// string from screenshot /dashboard.html`?

**Comment by gorhill** [comment]
@gwarser It's the troll spammer again.

See <https://github.com/uBlockOrigin/uBlock-issues/issues/227>.
