### ISSUE TITLE
HTML filtering not working on `codingdeft.com`

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uBlock-issues#2656]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I use

```adb
codingdeft.com##^script
```

in Firefox, it does not remove the inline script in the HTML source code.

---

Actually I cannot remove any tag in the source code using HTML filtering on this site.

### A specific URL where the issue occurs.

https://www.codingdeft.com/posts/typescript-convert-enum-to-array/

### Steps to Reproduce

1. Add `codingdeft.com##^script`
2. Go to `https://www.codingdeft.com/posts/typescript-convert-enum-to-array/`
3. Check the source code in `view-source:https://www.codingdeft.com/posts/typescript-convert-enum-to-array/`

### Expected behavior

Inline scripts are removed

### Actual behavior

Inline scripts are not removed

### uBO version

1.49.2

### Browser name and version

Firefox 113.0.1

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
Is this because page explicitly specifies `content-disposition: inline`?

        }
        // https://bugzilla.mozilla.org/show_bug.cgi?id=1426789
        if ( headerValueFromName('content-disposition', headers) ) { return; }

        const stream = request.stream =
            browser.webRequest.filterResponseData(extras.requestId);

**Comment by stephenhawk8054** [comment]
Somehow HTML filtering does not work on this link: `https://www.elahmad.com/tv/radiant_player.php?id=aljazeer_ar1`

Can anyone else reproduce?

**Comment by peace2000** [comment]
I can. E.g. this doesn't remove anything:

`elahmad.com##^[content]`

But works on a different page:
`iltalehti.fi##^[content]`

**Comment by mapx-** [comment]
at least in chrome => `elahmad.com##+js(rmnt, script, fetch)`

does it work for you for FF ?

**Comment by gorhill** [comment]
> likely due to blob: urls beings executed

`rmnt` scriptlet is not injected as `blob:`, it's injected directly as a content script.  `blob:` is for page script.

**Comment by gorhill** [comment]
Still possible to have race condition. Use `log, 1` to find out how many nodes were found already in the DOM when the scriptlet execution started.

**Comment by gorhill** [comment]
I need to confirm, I can't do this right now, later today maybe.

**Comment by gorhill** [comment]
When uBO doesn't detect a `charset` in response headers, it falls back to extracting a charset in DOM. In the current case, the extracted charset is [windows-1256](https://en.wikipedia.org/wiki/Windows-1256), which is not supported in uBO.

**Comment by stephenhawk8054** [comment]
Can anyone use HTML filtering on this site: `https://qtoptens.com/` ?

**Comment by peace2000** [comment]
I  can. What are you trying to remove?

**Comment by stephenhawk8054** [comment]
I was trying to remove admiral scripts inside while disabling current admiral domain blocking:

```adb
||muteknife.com^$badfilter
qtoptens.com##^script:has-text(engaged)
```

It works at first time for me, but when refreshing without bypassing cache (F5) a few times, it doesn't remove the script any more.

---

I figured out the cause, it's due to the service workers. When unregistering the service workers and use `||qtoptens.com^$csp=worker-src 'none'`, it works normally even when refreshing by F5.

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, looks like HTML filtering is not working on `https://missyusa.com/mainpage/content/index.asp`. I think it's because this site is using `text/html; charset=euc-kr` ?

The source looks like this

```html
<!DOCTYPE html>

<meta http-equiv="content-type" content="text/html; charset=euc-kr">

<html>
<head>
```

**Comment by gorhill** [comment]
> I think it's because this site is using `charset=euc-kr` ?

Yes, that is not something uBO can handle. At [0.1% usage](https://w3techs.com/technologies/overview/character_encoding), not something I would work on -- I already declined work for Shift JIS (can't find issue anymore in tracker).
