### ISSUE TITLE
Extension buttons are not visible in interface and nothing is blocked

### ISSUE THREAD

**Issue by amritabithi** [uBlockOrigin/uBlock-issues#2657]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ads are no longer blocked, and my interface looks like this so I cannot view any settings to try and fix it.
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/48937881/8b5d9036-079d-4cfb-8b2f-b9d2fef5eb01)

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

1. Open browser
2. Click extension icon
3. No controls are visible, just an empty pane.

### Expected behavior

I expect to see the buttons in the extension pane but it is just blank.

### Actual behavior

I do not see any controls in my extension pane.

### uBO version

1.49.2

### Browser name and version

LibreWolf 112.0.2-1

### Operating System and version

Ubuntu 20.04.5 LTS

**Comment by gwarser** [comment]
Was uBO included in installation, or did you install it by yourself?

It was not included for me and works fine after installation.

**Comment by gorhill** [comment]
I don't support LibreWolf explicitly, I support Firefox and I can't reproduce this behavior. Report to LibreWold project.

**Comment by gorhill** [comment]
@gwarser LibreWolf uses its own version of [assets.json](https://gitlab.com/librewolf-community/browser/source/-/blob/main/assets/uBOAssets.json), wouldn't re-installing uBO bypass this customization?

**Comment by amritabithi** [comment]
Thank you for the responses.  I did a thorough uninstall of the uBlock extension and LibreWolf and reinstalled both but still had the same issue.  ( LibreWolf comes with uBlock installed so I tried uninstalling and reinstalling just the extension also. )  I have to assume LibreWolf saves settings somewhere on my system that I can't find, and after searching the filesystem for a while I gave up trying to find them.

In the end I just switched to the regular Firefox and imported my bookmarks etc. to it and now things are working properly with uBlock again, and this is just fine.  I initially used LibreWolf because of high RAM usage with Firefox but have since resolved that by disabling "turboboost" on my system.

We can close this issue or I will close it if I can as the problem really came down to LibreWolf not fully uninstalling it's user settings which prevented testing a new install properly, so the problem is just with LibreWolf and not uBlock.

Thank you again for the fast response!

**Comment by gwarser** [comment]
I tried again. Win11 in VM, LW113.0-3, uBO installed by default 1.49.2 - no issues.
Manjaro, two packages from AUR, librewolf-bin 112.0.2-1 and librewolf-ublock-origin 1.44.4 (!!! uBO cannot be updated or removed using add-on manager) - still no issues.
