### ISSUE TITLE
remove() won't work properly on video elements in background tabs

### ISSUE THREAD

**Issue by ATechnocratis** [uBlockOrigin/uBlock-issues#2658]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Using :remove() to complete remove a video element from DOM will work fine when a tab loads while selected.
But when a tab loads in background the audio will keep playing even if the element is not found in DOM, meaning that the media element was not actually removed.

### A specific URL where the issue occurs.

https://www.twitch.tv/

### Steps to Reproduce

1. Add filter to remove front page video on twitch  `www.twitch.tv##.front-page-carousel:remove()`
2. Open a [www.twitch.tv ](https://www.twitch.tv/)  tab in background using middle click

 

### Expected behavior

The frontage video should be complete removed and no video or audio should be playing

### Actual behavior

The video element will be hidden/(removed?) but audio stream will continue playing

### uBO version

1.49.2.

### Browser name and version

Firefox v113

### Operating System and version

Windows 10 22H2

**Comment by ATechnocratis** [comment]
I am sorry if I am wrong, but I think the issue was misunderstood. 

It has nothing to do with filterlists, the issue is with the core functionality of :remove() function when used in my filters, which fails ( only hiding not removing the media element ) if a tabs loads in the background. 

It is relevant in any site or video, an example was given for twitch. For example removing every youtube video using a rule like:

> www.youtube.com###primary:remove() 

Will work fine when the tab is selected but will fail if it loads in the background ( audio will keep playing ).

**Comment by gorhill** [comment]
No _exact_ steps to reproduce, so you are essentially asking me to spend my time fumbling around to figure out exactly what I need to do at every steps to reproduce _your_ reported issue. I do know that some players have split video/audio (and that is the case for Youtube), and that removing video element won't make the audio go away.

I suggest you ask for help in on reddit before opening unconfirmed issues, here is for confirmed issues which always come with exact, detailed steps to reproduce, I just do not have the time to guess what I need to do to reproduce someone else's assumed issue.
