### ISSUE TITLE
Bootstrap button CSS classes blocked

### ISSUE THREAD

**Issue by benjavalero** [uBlockOrigin/uBlock-issues#266]
Some CSS classes for Bootstrap buttons are blocked, e. g. in the very same Bootstrap site:

https://getbootstrap.com/docs/4.1/components/buttons/

For instance, the classes "btn-danger", "btn-primary" and "btn-info".

In fact, the very "Submit" button for new issues in GitHub is blocked. I have had to unblock it to be able to submit the issue.

**Comment by mapx-** [comment]
force update` ublock filters`, it was fixed days ago
