### ISSUE TITLE
SOLVED - "My Rules" Save button enabled, but does nothing.

### ISSUE THREAD

**Issue by Entreprenerdz** [uBlockOrigin/uBlock-issues#2660]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've had this issue come up multiple times, unable to resolve it, and unable to find anything mentioning it on github or the web (Reddit, etc).

I decided to try to post here to see if there was a resolution or get help in resolving it.  Luckily, I was able to figure it out so I thought I would finish my post in hopes that it helps others.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Open uBlock Origin's dashboard, go to My Rules.
2.  Add a new rule, the Save button becomes enabled.
3.  Click Save, nothing happens, even though it appears as if it is being activated.

### Expected behavior

The new entry is either rejected and removed, or accepted, adding a new rule in the right pane, with the Commit button becoming enabled.

### Actual behavior

No change.  Clicking Save does nothing.

### uBO version

1.49.2 but I would imagine it affects multiple versions.

### Browser name and version

Tor Browser

### Operating System and version

MacOS Big Sur 11.6

**Comment by gorhill** [comment]
I don't understand this report. You say you "solved" it? 

> Add a new rule, the Save button becomes enabled

What exact rule are you trying to add?

**Comment by Entreprenerdz** [comment]
SOLUTION:  
So I noticed this as being weird, specifically the ... ... at the top.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/17835969/b5b9f649-9373-40e2-ac2d-aa0ffe765885)

I thought, that looks like cloud related stuff, which I don't use.  I found that "Enable cloud storage support" was checked (must've happened after an update or something) so I unchecked it.  It then appears as:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/17835969/0cfce869-9d4b-4d67-8a92-bd451ad3d449)

Now Save works.  I hope this helps someone else as I've experienced it multiple times over the past 2 years and the only way I could add rules manually was to export, add them, then import it.

**Comment by Entreprenerdz** [comment]
> I don't understand this report. You say you "solved" it?
> 
> > Add a new rule, the Save button becomes enabled
> 
> What exact rule are you trying to add?

I could not find a means of uploading my images in the New Issue so I did a follow up comment that I knew would allow me to add the photos.

Thanks for the quick response!

**Comment by gorhill** [comment]
I can reproduce, probably the JS on the page is breaking as a result of cloud storage not being available in Tor browser.

**Comment by gwarser** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/98146ba0-d561-418d-b77d-24c76c403bca)

Huh?
