### ISSUE TITLE
Scriptlet not working on this site

### ISSUE THREAD

**Issue by memories169** [uBlockOrigin/uBlock-issues#2661]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I tried to disable devtoolsDetector on 
`https://api.funhub.net/fhredirect/ktxb_LjkghPXmsmm-cMvCjhqlyKv1dUv3fBCH1EEWDw` 

but scriptlet seems to be not working
here is the devtoolsDetector code 

[code](https://pastebin.com/QNg1qvPj)

and here is my scriptlet
```
idoitmyself.xyz##+js(set, devtoolsDetector.addListener, false)
idoitmyself.xyz##+js(set, devtoolsDetector.launch, false)
```

### A specific URL where the issue occurs.

`https://api.funhub.net/fhredirect/ktxb_LjkghPXmsmm-cMvCjhqlyKv1dUv3fBCH1EEWDw`

### Steps to Reproduce

open devtools

### Expected behavior

the web should not be redirected

### Actual behavior

the web was redirected to other page when open devtools

### uBO version

1.49.2

### Browser name and version

FireFox 113

### Operating System and version

Windows 11

**Comment by mapx-** [comment]
The video is not available anymore (`Phiên bản của bạn đã cũ, vui lòng tải lại trang để cập nhât`)

However, something like this
`idoitmyself.xyz##+js(acs, $, devtoolsDetector)`

is working partiaally => the video is opened small-size but you could use full screen button
This is because there is mixed code in that inline script (devtools code + embedAutoHeight code etc)

This is a good example @gorhill for the replace scriptlet for inline scripts
`idoitmyself.xyz##+js(rpx, /\$.*devtoolsDetector/, /devtoolsDetector\.launch\(\)\;/,)`

**Comment by gorhill** [comment]
Closing with <https://github.com/gorhill/uBlock/commit/41876336db48292de06707adfa5e97dab74297d2>.

**Comment by gunir** [comment]
@gorhill Hi! Awesome new feature, but I think we should consider simplizing the syntax to something like this:

`domain##+js(sed, nodeName, pattern, replacement, sedCount, tryCount, log)`

It looks like this:

`example.com##+js(sed, script, /test/, , 1, 1, 1)`

Imo it's easier to read and write.

**Comment by gorhill** [comment]
The current syntax is not position-based, which is far more usable and maintainable.
