### ISSUE TITLE
expanding or contractong not working

### ISSUE THREAD

**Issue by JPluess** [uBlockOrigin/uBlock-issues#2663]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi, after enabling or disabling some filters, updating lists, the list no longer contracts or expands. You can see the issue in the video.

Browser: Firefox 113.1.0 (Build #2015950739), 52a200d213+
Gecko Version: 113.0.1-20230511191846
Addon Script Version: 97.4.1

https://github.com/uBlockOrigin/uBlock-issues/assets/7995240/89326259-d289-4f09-bada-ab8c7e048f73

### A specific URL where the issue occurs.

Settings

### Steps to Reproduce

Repetitive Error on Android 10

### Expected behavior

Work, Normal Expand, Retraction

### Actual behavior

Pressing + or - does not show/hide list

### uBO version

1.49.2

### Browser name and version

FF 

### Operating System and version

android 10

**Comment by krystian3w** [comment]
Works Fine on Android 12, Firefox 114.

**Comment by JPluess** [comment]
After enabling or disabling some filters, updating lists, the list no longer contracts or expands. 


https://github.com/uBlockOrigin/uBlock-issues/assets/7995240/a11cb836-edc3-45de-8a4c-fe1f4ca60dad

**Comment by gorhill** [comment]
> clearly differentiate between enabled and disabled lists

Surely the state of the checkbox is a good way to differentiate.
