### ISSUE TITLE
CNN Top Nav bar scrolls when UBlock on

### ISSUE THREAD

**Issue by artisansdjj** [uBlockOrigin/uBlock-issues#2664]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When I start cnn.com or refresh the screen, or go to a new page (article), the top navigation bar stays in place, blocking the content. At some point, something makes the bar lock to the top of the screen and then it's OK, but until that happens, it overwrites the portion of the screen that it occupies.

ONLY on Microsoft Edge browser.

### A specific URL where the issue occurs.

https://www.cnn.com/

### Steps to Reproduce

1. Go to CNN.com
2. Notice that the very top of the page is blank - where Ublock is blocking an add.
3. Scroll down on the page - the nav bar stays in place while the page scrolls behind it.
4. If SOMETHING brings that nav bar back to the top of the page, it then stays there until you either change the page or refresh the page you were on.

https://github.com/uBlockOrigin/uBlock-issues/assets/69018231/bd0c7357-42c0-4769-bf7e-27fcf669eeb8

I had to cut the video to show just the first instance, otherwise it was too large to upload.

### Expected behavior

That, even if the blank box shows at the top (where the ad would be), the nav bar locks in place and doesn't display OVER the scrolled content of the page.

Ideally, the blank box (where an ad would be) doesn't even appear.

### Actual behavior

Shown in the video.

### Configuration

Windows 11 (up to date on all patches/updates)
Microsoft Edge browser: Version 113.0.1774.42 (Official build) (64-bit)

**Comment by iam-py-test** [comment]
This is a filterlist issue, which should be reported at https://github.com/uBlockOrigin/uAssets.

**Comment by gorhill** [comment]
Report filter issues by using the _chat_ icon in the popup panel.
