### ISSUE TITLE
MDM/Chrome Policy not applying custom lists

### ISSUE THREAD

**Issue by BogDrakonov** [uBlockOrigin/uBlock-issues#2667]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'm using Jamf Pro to deploy uBlock Origin configuration to Google Chrome. Settings apply as expected except for a custom list. The custom list is technically publicly accessible however it does not appear in uBlock Origin after the policy has been applied.

Custom Policy with redacted URL of custom list
```json
{
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": true,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "https://REDACTED.com/uBlock.txt",
    "importedLists": [
      "https://REDACTED.com/uBlock.txt"
    ],
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "plowe-0",
    "fanboy-annoyance",
    "fanboy-thirdparty_social",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "easylist",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "user-filters",
    "https://REDACTED.com/uBlock.txt"
  ],
  "hiddenSettings": {
    "assetFetchTimeout": 30,
    "autoCommentFilterTemplate": "{{date}} {{origin}}",
    "autoUpdateAssetFetchPeriod": 120,
    "autoUpdatePeriod": 7,
    "cacheStorageAPI": "unset",
    "cacheStorageCompression": true,
    "cacheControlForFirefox1376932": "no-cache, no-store, must-revalidate",
    "consoleLogLevel": "unset",
    "debugScriptlets": false,
    "disableWebAssembly": false,
    "ignoreRedirectFilters": false,
    "ignoreScriptInjectFilters": false,
    "manualUpdateAssetFetchPeriod": 500,
    "popupFontSize": "unset",
    "requestJournalProcessPeriod": 1000,
    "selfieAfter": 11,
    "strictBlockingBypassDuration": 120,
    "suspendTabsUntilReady": "unset",
    "userResourcesLocation": "unset"
  },
  "netWhitelist": "about-scheme\nchrome-extension-scheme\nchrome-scheme\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme\nwyciwyg-scheme",
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-scripting: behind-the-scene false",
  "userFilters": ""
}
```

Contents of the `uBlock.txt` file that makes up the custom list
```txt
[Adblock Plus 2.0]
! Version: 202305231841
! Title: BogDrakonov Custom
! Last modified: 23 May 2023 18:41 UTC
! Expires: 10 days (update frequency)
!
! Homepage: https://www.REDACTED.com/
! 
! -----------------------Custom filters-----------------------!
dcounter.space##+js(nostif, ai_adb)
```

Manually adding this list works however that's not useful for deployment.

### A specific URL where the issue occurs.

dcounter.space

### Steps to Reproduce

1. Deploy the custom policy via MDM to Google Chrome.
2. Verify in `chrome://policy` that it shows up as mandatory
3. Verify other parts of the configured policy apply
4. Verify the custom list appears

### Expected behavior

1. The custom list should appear in the [Filter lists](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html) page
2. The custom list's functionality should work

### Actual behavior

1. The custom list does not appear
2. The custom list's functionality does not work

### uBO version

uBlock Origin 1.49.2

### Browser name and version

Google Chrome Version 113.0.5672.126 (Official Build) (arm64)

### Operating System and version

macOS Ventura 13.3.1 (a)

**Comment by gwarser** [comment]
Restart Chrome and check again.

**Comment by BogDrakonov** [comment]
It looks like it takes a while to correctly load. Additionally had to remove a lot of the parameters I had set. New config is
```
{
  "timeStamp": 1684869212388,
  "version": "1.49.2",
  "userSettings": {
    "externalLists": "https://REDACTED/uBlock.txt",
    "importedLists": [
      "https://REDACTED/uBlock.txt"
    ],
    "popupPanelSections": 63
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-thirdparty_social",
    "plowe-0",
    "https://REDACTED/uBlock.txt"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "dynamicFilteringString": "",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": ""
}

```
