### ISSUE TITLE
`set-constant` not working in uBlock Origin 1.49.3b20

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2668]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

`set-constant` not working

### A specific URL where the issue occurs.

`https://www.blick.ch/ausland/putins-perfider-plan-kreml-chef-will-offenbar-eigene-staedte-bombardieren-id17349557.html`

### Steps to Reproduce

Open: `https://www.blick.ch/ausland/putins-perfider-plan-kreml-chef-will-offenbar-eigene-staedte-bombardieren-id17349557.html`

Or: `https://news.mail.ru/society/56322747/`

### Expected behavior

Rules should work:
`blick.ch##+js(set-constant, Object.prototype.isAdDisabled, true)`
`news.mail.ru##+js(set-constant, Object.prototype.useMimic, noopFunc)`
`mail.ru##+js(set-constant, Object.prototype.mimic, undefined)`

### Actual behavior

The rules don't work

### Configuration

Firefox 113.0.1, Google Chrome 113
uBlock Origin 1.49.3b20 default + RU AdList

**Comment by mapx-** [comment]
What do you want to achieve on `blick` using that filter ?

**Comment by dimisa-RUAdList** [comment]
In earlier versions of uBlock Origin, when the above rules work fine, these blocks are missing ~>
<details>
<summary>Screenshot(s)</summary>

![blick](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/1e4f21b6-ee22-454d-a5a2-5e2604fbcf54)
![mail](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/1e022192-a22d-4d47-8c0c-4a3bbae5980d)

</details>

**Comment by mapx-** [comment]
for blick, EL Germany already has a filter `blick.ch##aside[id^="appnexus-placement"]` which works fine

in console `Object.prototype.isAdDisabled` => undefined

**Comment by gorhill** [comment]
I can reproduce 1.49.3b17 not having those placeholders, without adding any filters. @uBlock-user also reported issues with Youtube with latest build.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Google Chrome is fine now. But in Firefox `set-constant` is unstable. Try to open `https://news.mail.ru/incident/56333257/` and refresh the page several times.

**Comment by gorhill** [comment]
Beside the fix here, `set-constant` should behave just the same as it always had. Are you sure the behavior is different than b19?

**Comment by dimisa-RUAdList** [comment]
Every few refreshes of the page results in this ~>
<details>
<summary>Screenshot(s)</summary>

![mail news](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/47b732da-38c4-4bea-913e-d0ad13d94f62)

</details>

In b19, the problem is also present, in b16 everything is completely stable.

**Comment by gorhill** [comment]
I reloaded more than 20 times with Firefox stabe + uBO rc0 _ default lists and I can't see that placeholder.

**Comment by dimisa-RUAdList** [comment]
[Gif](https://imgur.com/sjpNjgF)

**Comment by gorhill** [comment]
Do you have anything else than default lists + RUS? It's really important that I try to reproduce using exact same config.

**Comment by dimisa-RUAdList** [comment]
The configuration is completely default + RU AdList.  And by the way, I observe the same instability here: `https://www.blick.ch/ausland/putins-perfider-plan-kreml-chef-will-offenbar-eigene-staedte-bombardieren-id17349557.html`

True, this does not happen as often as on `mail.ru`.

**Comment by gorhill** [comment]
I would like to see if someone else can reproduce, I just can't. I was suspecting a specific scriptlet which is injected on your side but not on my side could be the culprit but you confirm you are using only default lists. This is most likely related to the change I pointed above, but I would like to keep it if possible and rather try to find the root cause of the issue.

**Comment by dimisa-RUAdList** [comment]
I found an example where instability is much more common: `https://www.drive2.ru/cars/bmw/`

<details>
<summary>Screenshot(s)</summary>

![drive](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/3163983d-336f-4683-96fd-e54d0b874971)

</details>

**Comment by gorhill** [comment]
I can reproduce this one.
