### ISSUE TITLE
HBO Max/Max ad block not working.

### ISSUE THREAD

**Issue by NickyTheCat** [uBlockOrigin/uBlock-issues#2669]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Ads are appearing on HBO Max after they rebranded the site. This is with the "With Ads" subscription.

### A specific URL where the issue occurs.

https://play.max.com/

### Steps to Reproduce

Watch something on HBO Max (now called Max) with the lower cost subscription that has ads.
Hit an ad break

### Expected behavior

No interruptions from ad breaks

### Actual behavior

Interruptions from ad breaks

### Configuration

no altered settings for the website

**Comment by gorhill** [comment]
This is not the place for filter issue, read the repo carefully please.
