### ISSUE TITLE
Add intermediate state to checkbox groups

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uBlock-issues#2687]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The checkboxes next to the names of the new filter list groups should have the regular "check" icon only when all of their child items are selected.

The current behavior is especially confusing when the groups are collapsed, as it isn't clear for users if all items are selected or not.

### A specific URL where the issue occurs.

dashboard

### Steps to Reproduce

1. Open the **Filter lists** pane
2. Check **uBlock filters**
3. Uncheck one of its child items

### Expected behavior

![example](https://github.com/uBlockOrigin/uBlock-issues/assets/6733770/a9ed65b0-463b-4292-86e1-8bd9222e2620)

Example: https://jsfiddle.net/revive/57gm26y8/

### Actual behavior

![uBlock Origin 1.50.0](https://github.com/uBlockOrigin/uBlock-issues/assets/6733770/3fda4a6d-2a46-4a58-bc3e-a123ec619b7a)

### uBO version

1.50.0

### Browser name and version

Edge stable

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
I went with a different visual than the suggested one. The suggested one would require much more changes to the checkbox-related code as it would require to toggle between to different SVG `path` elements. The chosen solution is just color-based and does not require to change the DOM make up of the checkbox widget.

**Comment by anewuser** [comment]
Thank you. Your solution looks great.
