### ISSUE TITLE
Element Zapper unexpectedly closes when it shouldn't

### ISSUE THREAD

**Issue by RustoMCSpit** [uBlockOrigin/uBlock-issues#2688]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Element Zapper should not be a one click by default, it should be a left click everything you want to zap and then right click to escape. Say an annoying cookie comes up, I left click 14 times and get rid of everything and then right click

### A specific URL where the issue occurs.

https://github.com

### Steps to Reproduce

1. Open zapper
2. Zap something
3. It closes

### Expected behavior

Not one use zap

### Actual behavior

One use zap

### uBO version

1.49.2

### Browser name and version

Firefox, newest

### Operating System and version

LM Cinnamon, newest LTS

**Comment by RustoMCSpit** [comment]
Pretty sure this is a bug and not a feature so that's why it's here

**Comment by gorhill** [comment]
As explained in [Element zapper documentation](https://github.com/gorhill/uBlock/wiki/Element-zapper#once-you-enter-the-element-zapper-mode):

> ### Once you enter the "element-zapper mode":
> 
> - Highlighting and clicking an element will remove it from the web page and exit element zapper mode.
>     - Press the <kbd>Shift</kbd> key while clicking if you do not want to exit element zapper mode.
> - Highlighting an element and then pressing the <kbd>Delete</kbd> key will remove it from the web page without quitting the element zapper mode.
> - Pressing the <kbd>Esc</kbd> key will exit element zapper mode.

**Comment by RustoMCSpit** [comment]
I apologise

**Comment by krystian3w** [comment]
Sometimes don't work press shift / delete at first load zapper.
