### ISSUE TITLE
I cannot subscribe to filter lists, with ublock origin legacy 1.16.4.4

### ISSUE THREAD

**Issue by FrostKnight** [uBlockOrigin/uBlock-issues#269]
When I got to subscribe with ublock origin, legacy, 1.16.4.4, it says this:

The address wasn’t understood

Iceweasel-UXP doesn’t know how to open this address, because one of the following protocols (abp) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.

PS, Iceweasel-uxp is based off of basilisk browser.    
The operating system I use is Hyperbola GNU/Linux.

This is more of a problem related to ublock origin legacy I believe.

**Comment by uBlock-user** [comment]
FYI, IceWeasel is not officially supported, so could be a browser issue.

**Comment by krystian3w** [comment]
You are activate JavaScript in browser?


it may be required for simplified links where the protocol `abp://` / `abp:` / `ubo:` is no allowed.

**Comment by krystian3w** [comment]
You are activate JavaScript in browser?


This it may be required for simplified links where the protocol `abp://` / `abp:` / `ubo:` is no allowed.


---


#### Simplifed demo link subscribe <sup>(with no exsist subdomain `https://subscribe.adblockplus.org/`)</sup>:

[uBO annoyance - Subscribe][uBO annoyance - Subscribe] <sup>(Please <ins>**refresh**</ins> ISSUE before test link)</sup>

<ul> 

[uBO annoyance - Subscribe]: https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt&title=annoyances%20uBO

</ul>

**Comment by FrostKnight** [comment]
I have javascript activated in my browser.  and its a fork of Basilisk Browser only without webextensions.  Like Palemoon, it has no webextensions.

**Comment by gwarser** [comment]
Did you tried to open subscription link in new tab? Only left click is catched.

**Comment by krystian3w** [comment]
Or try use middle and now left - this is works on `old.reddit.com`.

**Comment by FrostKnight** [comment]
@gwarser, yes I did actually, same thing happened.  But I did find a workaround,  https://filterlists.com/ 

then I looked for the filter I was looking for,  Then I went to click details on the script I wanted, which is this and I used import to load this script and other ones I wanted.
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt

PS, This was the only way I could find to import the scripts I wanted.   The usual way of automatically installing it by clicking on the link didn't work.   I am not sure how to explain it any further other than to say: try palemoon + ublockorigin legacy 1.16.4.4.  This Basilisk fork runs more like palemoon anyways... aka webext is stripped clean out.

If it works for you, great then close the issue, if not then this is an issue to look at. :/

**Comment by FrostKnight** [comment]
@krystian3w, I am not sure I understand what you meant though. but okay.

**Comment by krystian3w** [comment]
1. click on link with middle button mouse (scroll)
2. click left and link generate pop-up accept subscribe.

**Comment by FrostKnight** [comment]
@krystian3w
@gwarser

Yeah, you are correct, your link works, but the link I was looking for, didn't. Nevertheless, you may close this. I am fully okay with that. matter of fact, I will. If you want to reopen it feel free, but, I think nothing else needs to be said at this time.
