### ISSUE TITLE
Dashboard no longer functions in Firefox 114.0.1

### ISSUE THREAD

**Issue by VersloB** [uBlockOrigin/uBlock-issues#2690]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Click on icon, Click on Open the dashboard.
None of the tabs on the uBlock Origin task bar are responsive.

### A specific URL where the issue occurs.

moz-extension://47bac081-bf4d-4301-a27f-85e0d0a44c16/dashboard.html

### Steps to Reproduce

1. Click on uBlock Origin icon, 
2. Click on Open the dashboard.
3. None of the tabs on the uBlock Origin task bar are responsive.

### Expected behavior

Responsive dashboard

### Actual behavior

Unresponsive dashboard

### uBO version

1.50.0

### Browser name and version

Firefox 114.0.1 64bit

### Operating System and version

Win10Pro 21H2 19044.2965

**Comment by gwarser** [comment]
Works fine here. More info needed. Errors in browser console?

**Comment by gorhill** [comment]
OP has issues with other extensions as well: <https://github.com/gildas-lormeau/SingleFile/issues/1181>.

I suspect some of the checkboxes were not carefully checked:

> - [x] using a new, unmodified browser profile.
