### ISSUE TITLE
U block origin blocks power apps editing option

### ISSUE THREAD

**Issue by Gopi1991R** [uBlockOrigin/uBlock-issues#2699]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The U Block extension on Firefox blocks power apps editing options. The editing functionality at the power apps is not working. Every time we should re-load the webpage, only then will it start working. By default, it is not working.

### A specific URL where the issue occurs.

https://apps.powerapps.com/play/*

### Steps to Reproduce

1. Create a canvas app "A" on the first page.
2. Create a button (called Apple) to navigate another app, "B."
3. App "B" should have an input field,
4. Then play the app "A."
5. On the first page, click the apple button.
6. It navigates to another app, "B."
7. No input field allows editing; only after reloading the page does it start to allow editing.

### Expected behavior

1. It should allow you to edit App "B"'s input fields immediately after opening app "B.".
2. We had a one-week conversation with the Microsoft product development and support team. They said U-block should only allow editing options.

### Actual behavior

At app "B.". does not allow editing after lauching the page from App A

### uBO version

1.50.0

### Browser name and version

FireFox 115

### Operating System and version

Windows 10

**Comment by iam-py-test** [comment]
This is a filter list issue

**Comment by Gopi1991R** [comment]
can i share through teams screen share and discuss
