### ISSUE TITLE
"Revert" button needs improvement ("Ctrl+Z" even reverts more.)

### ISSUE THREAD

**Issue by D4n2021** [uBlockOrigin/uBlock-issues#2705]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On the "My filters" page, there is a "Revert" button that turns grey the instant you Apply changes.

### A specific URL where the issue occurs.

moz-extension://[UUID]/dashboard.html#1p-filters.html

### Steps to Reproduce

1. visit "My filters"
2. make a change
3. click "Apply changes"

### Expected behavior

Please either make "Revert" **stay** clickable after "Apply changes" is clicked, or even consider only making "Revert" clickable after "Apply changes" is clicked, to highlight its' useful functionality after observing the last change (as the last filter-change obviously only **can** be observed if changes are applied and if conclusive the user reloads a website, where the filter applies).

### Actual behavior

Even after "Revert" turns grey, Ctrl+Z still works to revert the last change after that.

### uBO version

1.50.0

### Browser name and version

Firefox 114.0.2

### Operating System and version

Win 10 22H2

**Comment by gothic-bum** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/367

**Comment by gorhill** [comment]
Reverting is to replace the content of the editor with the last saved content, so consequently if the content of the editor is exactly the same as the last saved content, the Revert button won't accomplish anything, hence it is disabled.

**Comment by gorhill** [comment]
Undoing text edit operations is quite different from reverting to last saved version. Looks like you are asking to add a button to perform the equivalent of Ctrl-Z (undo), and which would be labelled _Undo_. Anyway, as said, I decline to make changes in there.
