### ISSUE TITLE
Ublock on Android Firefox doesn't block certain elements.

### ISSUE THREAD

**Issue by ehrhardt06** [uBlockOrigin/uBlock-issues#2707]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock on Android Firefox does not block certain elements on pages, whereas desktop ublock on Firefox does. The rule that desktop ubo uses to block a cookie banner is the following: `###cookie-banner` on [lakmusz.hu](lakmusz.hu). **I noticed the issue on an other site as well**, but I cannot reproduce the issue there for some reason.

`###cookie-banner` is in the adguard list and in easylist too, but the android version fails to block it. With the filters disabled, the element picker and the logger both show that the site has this cookie notice under `###cookie-banner`, and the issue is still there, even if I switch to desktop view on mobile, or if I switch to responsive design mode on desktop.

first picture shows the correct behaviour, the banner is blocked thanks to filters. second and third pic shows the banner id on desktop and mobile, and the third pic shows that the banner is not being filtered. 

![filters enabled desktop](https://github.com/uBlockOrigin/uBlock-issues/assets/137706181/2d208716-4e13-4dd1-93dd-8419e0a4bf52)
![desktop rule](https://github.com/uBlockOrigin/uBlock-issues/assets/137706181/a9d3f577-025e-431d-9936-2d9303b97f04)
![filters enabled mobile](https://github.com/uBlockOrigin/uBlock-issues/assets/137706181/73317f63-a46d-4270-ba0c-2f706051609e)

ps. Ubo on desktop seems to recognize `###cookie-banner` in the My filters panel, but firefox on android can't. android ubo blocks the cookie notice ONLY if put the rule `lakmusz.hu###cookie-banner` in the my filters panel, which is strange, considering desktop ubo can handle the rule without the domain part.

### A specific URL where the issue occurs.

lakmusz.hu

### Steps to Reproduce

1. Enable Adguard annoyances and easylist cookie list.
2. Go to lakmusz.hu on mobile and desktop.
3. See that cookie banner is not blocked on android.

### Expected behavior

`###cookie-banner` should be filtered on Android Firefox, not just desktop.

### Actual behavior

`###cookie-banner` is not filtered on mobile (my filters panel, adguard list and easylist don't work). android ubo can't handle `###cookie-banner` in the my filters panel.

### uBO version

1.50.0 - desktop | 1.50.0 - mobile

### Configuration

```
uBlock Origin 1.50.0:
 since: 2d.5h.59m
Firefox: 114
filterset (summary):
 network: 123285
 cosmetic: 224805
 scriptlet: 37254
 html: 981
listset (total-discarded, last-updated):
 added:
  adguard-generic: 72009-5295, 1h.24m
  adguard-mobile: 8300-98, 1h.24m
  adguard-social: 20721-49, never
  adguard-cookies: 26107-3581, never
  adguard-popup-overlays: 22768-1473, never
  adguard-mobile-app-banners: 4365-1059, never
  adguard-other-annoyances: 12999-701, never
  adguard-widgets: 2187-35, never
  fanboy-thirdparty_social: 68-0, never
  easylist-annoyances: 3874-181, never
  easylist-chat: 126-0, never
  fanboy-cookiemonster: 47642-235, never
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 34510-100, 1h.25m
  ublock-badware: 7631-1, 1h.25m
  ublock-privacy: 457-0, 1h.25m
  ublock-unbreak: 2079-0, 1h.25m
  ublock-quick-fixes: 283-0, 1h.25m
  easylist: 67575-752, 1h.25m
  easyprivacy: 30615-628, 1h.25m
  urlhaus-1: 6511-0, 1h.25m
  plowe-0: 3739-1, 1h.25m
filterset (user): [array of 1 redacted]
hostRuleset:
 added: [array of 21 redacted]
urlRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 280 ms (selfie)
 maxAssetCacheWait: 95 ms
```

```
`uBlock Origin 1.50.0:
 since: 1h.10m
Firefox Mobile: 114
filterset (summary):
 network: 105133
 cosmetic: 139039
 scriptlet: 22834
 html: 964
listset (total-discarded, last-updated):
 added:
  adguard-social: 20729-1503, 1h.10m
  adguard-cookies: 26110-1604, 1h.10m
  adguard-popup-overlays: 22768-1351, 1h.10m
  adguard-mobile-app-banners: 4365-1052, 1h.10m
  adguard-other-annoyances: 13000-246, 1h.10m
  adguard-widgets: 2187-35, 1h.10m
  easylist-annoyances: 3874-973, 1h.10m
  easylist-chat: 126-17, 1h.10m
  fanboy-cookiemonster: 47642-19676, 1h.10m
  easylist-newsletters: 6137-1849, 1h.10m
  easylist-notifications: 2633-260, 1h.10m
  fanboy-social: 16097-11845, 1h.10m
 default:
  user-filters: 1-1, never
  ublock-filters: 34779-743, 1h.1m
  ublock-badware: 7625-1, 1h.1m
  ublock-privacy: 457-1, 1h.1m
  ublock-unbreak: 2084-1, 1h.1m
  ublock-quick-fixes: 283-0, 1h.1m
  adguard-mobile: 8300-133, 1h.10m
  easylist: 67575-17500, 1h.10m
  easyprivacy: 30615-717, 1h.10m
  urlhaus-1: 6511-0, 1h.10m
  plowe-0: 3739-1, 1h.10m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2660 ms
 maxAssetCacheWait: 12 ms`

```
### Browser name and version

Firefox stable (desktop) 114.0.2 (64-bit) | Firefox for Android 114.2.0

### Operating System and version

Microsoft Windows 11 Home - version 10.0.22621. build 22621

**Comment by stephenhawk8054** [comment]
Go to "Filter lists" pane and turn off "Ignore generic cosmetic filters"
