### ISSUE TITLE
Loger dissabled, Android

### ISSUE THREAD

**Issue by noko00** [uBlockOrigin/uBlock-issues#2713]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

You disabled loger for Android users. Reason? 
I em tired to search hacks to enable loger for android. I am sory, for uninstalling good "ublock origin". Moving to AdGuard. Sory :(.

### A specific URL where the issue occurs.

All urls.

### Steps to Reproduce

Open brovser
Open ublock
No LOGER!!!

### Expected behavior

Loger is important.

### Actual behavior

I told you.

### uBO version

I dont care

### Browser name and version

Firefox

### Operating System and version

Android 13

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-settings#uipopupconfig

**Comment by noko00** [comment]
I dont want adwanced ui config, hidden. I want loger enabled by default on
android. I am now using AdGuard. Thank you wery much for not nothing. BY.

**Comment by noko00** [comment]
And NetGuard. Wery good app, dooing 90,% ublock origin doo.
