### ISSUE TITLE
First-time setup sequence

### ISSUE THREAD

**Issue by somename-123** [uBlockOrigin/uBlock-issues#2717]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Add a **very simple** page that shows up after installation and allows to enable additional filters in a user friendly way.

Or (I think this won't be annoying) a banner when user clicks on the extension icon for the first time, this amount of text can fit into extension popup.

For example (text in the brackets will be hidden behind the **(i)** icon, sorry English isn't my native):

# uBlock Origin First Time Setup

- \[x\] Block ads (enables `uBlock — Ads` and `AdGuard — Ads` filer lists)
- \[x\] Block trackers (enables `uBlock — Privacy`, `AdGuard — Tracking Protection`, `AdGuard — URL Tracking Protection`, `EasyPrivacy` and `fanboy — anti facebook` filter lists)
- \[x\] Block malware (enables `Online Malicious URL Blocklist` filter list)
- \[ \] Block annoyances, like cookie popups, social media widgets, etc.  (enables `AdGuard — Annoyances`, `EasyList — Annoyances` and `uBlock filters — Annoyances` filter lists)
- \[ \] Enable regional filters ||_will show `<select>` with the list of countries_|| (enables region specific filters)

Finish setup (*you can change your choices anytime in settings*)

---

Motivation: Many users don't know about annoyances filters.

### A specific URL where the issue occurs.

_

### Steps to Reproduce

_

### Expected behavior

_

### Actual behavior

_

### uBO version

_

### Browser name and version

_

### Operating System and version

_

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/labels/declined in e.g. https://github.com/uBlockOrigin/uBlock-issues/issues/2180

**Comment by krystian3w** [comment]
Activation of the AdGuard list when activating uBo lists is not recommended even as a DandelionSprout on a daily basis testing sites from the south and north of Europe (still left to test are sites from Western and Eastern Europe, Africa, Asia, Oceania-Australia and the United States and maybe whole Tor pages).

**Comment by krystian3w** [comment]
![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/d940e72c-ed2b-423d-9c09-a63ad5ee0dd4)

**Comment by iam-py-test** [comment]
> fanboy — anti facebook filter lists

Those don't completely block Meta, just connections to Facebook from third-party sites

**Comment by krystian3w** [comment]
But only AdGuard collect who enabled anti Facebook list with enabled telemetry in his apps and often recommend disable list due reports about broken Facebook or widgets.

**Comment by gwarser** [comment]
The goal for uBO basic usage is to be "install and forget", so any "first time" configurators are not desirable.
