### ISSUE TITLE
[Win], Palemoon, uBlockOrigin Blocked requests on the icon

### ISSUE THREAD

**Issue by ribatamu** [uBlockOrigin/uBlock-issues#272]
I have Windows 64, Palemoon 28.1.0 32 bit and uBlock Origin 1.16.4.5.

The blocked requests, showed on the icon have wrong location.
![ublockpalemoon](https://user-images.githubusercontent.com/33899653/47088501-8f4b7280-d216-11e8-99bc-8f522891b3e2.jpg)

**Comment by uBlock-user** [comment]
Do not remove the template, and fill it in for a proper bug report.

**Comment by gorhill** [comment]
You have outlined toolbar buttons in your screenshot, not present in @gwarser's screenshot.

**Comment by ribatamu** [comment]
@gorhill Yeap I see the difference in the toolbar.

What I did is to install Palemoon 28.1.0 on Windows 10 64 bit. I start Palemoon and every option is by default with the default theme. I install uBlockOrigin 1.16.4.5 and I have the view like is in the provided screenshot. 

Maybe this issue is with Palemoon and Windows? I was able to reproduce the issue in VMWare Windows machine with new Palemoon profile.

**Comment by gorhill** [comment]
I installed latest Pale Moon 32-bit/Linux, and all was fine.

Whoever can reproduce the issue please further investigate to find the cause and ensure that the issue is really with uBO. Try with other extensions with badge too, if they also suffer the same issue, then the issue is not in uBO.
