### ISSUE TITLE
`''` value is no longer supported for `set` / `set-attr`?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2729]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I detected today bug in Dev cycle about support empty "value" (I mean `''`) in scriptlets.

example scriptlets groups:

```adb
! cusor should be changed, but didn't.

! valid in AdGuard for some reason:
example.*#%#//scriptlet("set-attr", "body, body  *", "disabled", "")
! standard css:
example.*##[disabled]:style(cursor: not-allowed !important;)
example.*##[disabled] [disabled]:style(color: gray !important; cursor: grab !important; user-select: none !important;)
```

```adb
! https://testcases.agrd.dev/Filters/scriptlet-rules/test-scriptlet-rules.html?testId=07a35257
! /\+js\(set,.*, ?''\)/ - 94+ uBo ads, ~3  uBo privacy, ~1 uBo unbreak
!
! most to pass tests other than one specific set-constant:
testcases.agrd.dev,surge.sh###subscribe-to-test-scriptlet-rules-filter
testcases.agrd.dev,surge.sh##+js(set, setConstantAGSyntax, true)
testcases.agrd.dev,surge.sh##+js(set, setConstantUBOSyntax, true)
testcases.agrd.dev,surge.sh##+js(set, trueProp, true)
testcases.agrd.dev,surge.sh##+js(set, falseProp, false)
testcases.agrd.dev,surge.sh##+js(set, undefinedProp, undefined)
testcases.agrd.dev,surge.sh##+js(set, nullProp, null)
testcases.agrd.dev,surge.sh##+js(set, noopFuncProp, noopFunc)
testcases.agrd.dev,surge.sh##+js(set, trueFuncProp, trueFunc)
testcases.agrd.dev,surge.sh##+js(set, falseFuncProp, falseFunc)
testcases.agrd.dev,surge.sh##+js(set, numberProp, 111)
! failed:
testcases.agrd.dev,surge.sh##+js(set, emptyStringProp, '')
! invalid:
testcases.agrd.dev,surge.sh##+js(set, emptyStringProp, "")
! reset of test to mark as passed
testcases.agrd.dev,surge.sh##+js(set, illegalNumberProp, 32768)
```

I guess from commit about extend support AG syntax.

---

By dumb regex:

```regex
/\+js\(set,.*, ?''\)/
```

I found 96+ usefull situations where are needed support to avoid rewrite to other scriptlet or network filtering.

### A specific URL where the issue occurs.

https://testcases.agrd.dev/Filters/scriptlet-rules/test-scriptlet-rules.html?testId=07a35257

https://example.com/
https://example.org/

### Steps to Reproduce

1. copy filters from description
2. paste to "My filters" and save
3. open AdGuard test page (or `example.org`)

### Expected behavior

- Pass all AdGuard tests from scriplet part

- override cursor at `example.org`

### Actual behavior

- Fail one check in part of test for scriptlets:
  ![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/99966f5e-3995-4467-9acb-3d127ef3bedf)
 *still allowed in ABP syntax:*
  ```adb
  testcases.agrd.dev,surge.sh#$#override-property-read emptyStringProp '';
  ```

- cursor is still default at `example.org`

---

Both without new quoting:

```adb
! invalid in AdGuard now for MV2 WebExtension:
example.*#%#//scriptlet("set-attr", "body, body  *", "disabled", "''")
testcases.agrd.dev,surge.sh##+js(set, emptyStringProp, "''")
testcases.agrd.dev,surge.sh##+js(trusted-set, emptyStringProp, "''")
```

### uBO version

1.50.1b16

### Browser name and version

Chrome 109

### Operating System and version

Windows 7 Pro

**Comment by krystian3w** [comment]
Also funny is correlation:

`<link href="foo.css" disabled>`

In that method possible disable run css form file at all in Firefox/Chrome by:

```adb
foo.bar##+js(set-attr, link, disabled, true)
```

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/commit/6e78ee096a8c035f5819325d5b6465b915008c60

**Comment by gorhill** [comment]
> `testcases.agrd.dev`

Cool stuff. Do you know if there is a filter list somewhere to test all filters?

**Comment by krystian3w** [comment]
Maybe missed in aliases:

```adb
foo#%#//scriptlet("prevent-bab")
```

Or test are outdated after bab preventing logic was changed to use two different surrogates.
