### ISSUE TITLE
Indicator badge not showing numbers

### ISSUE THREAD

**Issue by peterschussheim** [uBlockOrigin/uBlock-issues#273]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The indicator badge on the extension is showing a solid gray block, rather than showing the number of requests blocked

### A specific URL where the issue occurs

https://github.com/uBlockOrigin

### Steps to Reproduce

1. load a site
2. check if extension reports the number of requests blocked

### Expected behavior:

I expect the badge to display the correct number.

### Actual behavior:

Indicator is solid, no numbers

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: chrome Version 72.0.3583.0 (Official Build) canary (64-bit)
* Operating System and version: macos 10.14 (18A391)

<img width="482" alt="google chrome041" src="https://user-images.githubusercontent.com/3654683/47104848-61fbc600-d210-11e8-9940-93fc82c4ab1c.png">

**Comment by uBlock-user** [comment]
Cannot reproduce, likely a browser build issue.

**Comment by gorhill** [comment]
I don't support Chrome Canary, too many false positive issues. Re-open if the issue also exist with Chrome stable.

**Comment by peterschussheim** [comment]
👍🏻
