### ISSUE TITLE
Photopea GUI gets messed up 

### ISSUE THREAD

**Issue by Laurennial** [uBlockOrigin/uBlock-issues#2731]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When uBlock is active on photopea.com, the UI is janky. See screenshots below.

![photopea 100 zoom](https://github.com/uBlockOrigin/uBlock-issues/assets/54823524/b7c25f10-b4f0-4228-a093-5a9e95fb32c1)
the above is what happens when the site is at normal, 100% zoom. You can see the word "about" is cut off on the right.

![photopea gui zoomed out](https://github.com/uBlockOrigin/uBlock-issues/assets/54823524/a2bdd6f8-824c-4eea-99f2-152069ec1163)
This is what I see when I zoom the page out. As you can see it's still not entirely visible there, but if I continue to zoom out, I can see the entirety of it. 

I first reported it to Photopea of course, but the dev said that this is a problem with uBlock that I guess he's seen before, and I did see other users reporting GUI issues although it wasn't clear on those posts if uBlock was causing their issues as well.

I have uBlock disabled on Photopea now and it works perfectly, but I'm sure there's a lot of other people who will be very confused and harass the poor Photopea dev over it. 

### A specific URL where the issue occurs.

https://www.photopea.com/

### Steps to Reproduce

All you need to do is open photopea.com in chrome when uBlock is active on photopea.com. You'll see that part of the UI is entirely missing from the right side unless you zoom the page out about 65-90%, depending. 

### Expected behavior

I expected to be able to see the entire right half of the site.

### Actual behavior

The right half was cut off.

### Configuration

Honestly not sure what this is for.

**Comment by iam-py-test** [comment]
This issue tracker is for bugs in uBlock Origin. This appears to be an issue with it's filterlists (rules), which should be reported at https://github.com/uBlockOrigin/uAssets.
Please:
- go to the broken website and reproduce the issue
- click the uBlock Origin icon
- click the chat icon
- follow the steps to report an issue
