### ISSUE TITLE
Fix typos (PR)

### ISSUE THREAD

**Issue by szepeviktor** [uBlockOrigin/uBlock-issues#2736]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've found some misspellings with `typos`.
Couldn't open a PR :(
Here is the commit: https://github.com/szepeviktor/uBlock/commit/1875a264bb77fc896eefa55ec0a3878f33693d38

### A specific URL where the issue occurs.

https://github.com/szepeviktor/uBlock/commit/1875a264bb77fc896eefa55ec0a3878f33693d38

### Steps to Reproduce

Please merge my commit.

### Expected behavior

-

### Actual behavior

-

### uBO version

-

### Browser name and version

-

### Operating System and version

-

**Comment by gorhill** [comment]
Thanks.

I have merged your changes in [`typos` branch](https://github.com/gorhill/uBlock/commit/1875a264bb77fc896eefa55ec0a3878f33693d38), but given changes in many files, I will merge your changes to main branch in next dev cycle as currently the main branch in release candidate mode.

**Comment by szepeviktor** [comment]
Glad to contribute.
