### ISSUE TITLE
Firefox addon popup settings for uBlock are blank

### ISSUE THREAD

**Issue by VaelophisNyx** [uBlockOrigin/uBlock-issues#2738]
### Prerequisites

- [ ] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock Origin (as well as most other addons) for Firefox has nothing on its settings popup. The last instance of this I can find was closed for inactivity, but was related to a different OS than the one I use.

I can't get into the settings to check if it's a filter issue at all, nor can I access my lists or settings to see if defaulting them works.

### A specific URL where the issue occurs.

This is not a page-specific issue

### Steps to Reproduce

1. attempt to open the addon's popup settings
2. it's blank?

that's all I have

### Expected behavior

Expected: settings to be there when clicked

### Actual behavior

No settings present when clicked

### uBO version

1.50.0

### Browser name and version

Firefox 115.0.2 (64-bit)

### Operating System and version

Windows 10, version difficult to determine

**Comment by VaelophisNyx** [comment]
to further clarify, this started *today*, with no update to firefox, ublock, or any other addons for it that I have. Additionally I have not received any windows updates in the last 4 years (due to manual disabling of it). Until I started my computer today, all was behaving fine.

**Comment by VaelophisNyx** [comment]
So looking into this, it seems to be a recurring bug from a much older version of firefox (FF 83) where this exact issue was present. Probably that again

**Comment by gorhill** [comment]
<https://github.com/uBlockOrigin/uBlock-issues/issues/1374#issuecomment-1636886748>:

> affects ALL firefox addons that had popup settings on click
