### ISSUE TITLE
uBlock Origin crosshair goes behind the element while blocking

### ISSUE THREAD

**Issue by PizzaBox2010** [uBlockOrigin/uBlock-issues#2739]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

So I found an issue with the uBlock Origin crosshair. When I drag my crosshair to the element, it goes behind it. Read Steps to Reproduce.

Video: 
`https://mega.nz/file/MPsgQTyR#FW_uBcMu4I4l4tGH-lmyF4n5qt_vTM21z-6hX5X8jJc`

### A specific URL where the issue occurs.

Everywhere

### Steps to Reproduce

1. The crosshair goes behind the element.
2. Screen recorders, like OBS can't record this issue.
3. Mouse highlighter software, like PenAttention, does show my crosshair.
4. I can't click on the element that the crosshair was going behind at.
5. When I delete one of the elements that make my crosshair go behind, it shows the crosshair.
6. Refreshing does not fix that issue.

### Expected behavior

It was going to be at the top of the element.

### Actual behavior

The element was going behind the element.

### uBO version

1.50.0

### Browser name and version

Google Chrome 114.0.5735.199

### Operating System and version

Windows 10 22H2

**Comment by krystian3w** [comment]
Same with legacy PenAttention 1.4 (instaad latest 1.11)? Also check on opened Firefox Window.

**Comment by gorhill** [comment]
I can't reproduce, and I don't understand what the video is showing, it's heavily shaking and the whole context is cropped out. What site was this? uBO just use HTML/CSS/JS, it's not responsible to render the mouse, your browser is.

**Comment by gwarser** [comment]
Pointer style set to inverted?
