### ISSUE TITLE
Youtube Playlist  long delay playing Youtube videos. 

### ISSUE THREAD

**Issue by A0R-R0CKS** [uBlockOrigin/uBlock-issues#2740]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I am watching Youtube Videos in a playlist it causes a long delay between videos, both in Chrome and Firefox. 
when I disable it then the problem goes away. Directly on youtube or also on a 2nd site that is for playing Youtube videos in a auto playlist.

https://playvj.com/music-video-station/cxmPCiu19ggi03SNtPtsgZOMBxJ2

### A specific URL where the issue occurs.

https://playvj.com/music-video-station/cxmPCiu19ggi03SNtPtsgZOMBxJ2

### Steps to Reproduce

Just open the site link and watch the videos 
Same with direct Youtube Playlist. 

### Expected behavior

The videos should auto load and play they do not unless you disable ublock. 

### Actual behavior

The videos should auto play unless you turn off ublock they do not auto load. 

### uBO version

1.50.0

### Browser name and version

Firefox 102.13.0esr (64-bit) that just came out. 

### Operating System and version

Windows 7 64bit Extended Life

**Comment by iam-py-test** [comment]
This issue tracker is just for issues with uBlock Origin, not issues with it's filters.
Also, all YouTube issues should be reported at https://github.com/uBlockOrigin/uAssets/issues/7636
Thank you.
