### ISSUE TITLE
[Feature request] Move filters' scrollbar a little to the left

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uBlock-issues#2746]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I would like to request a change of the location of the filters' scrollbar when uBO's pop-up is open to be moved a little to the left, so it does not overlap with the website status indicator.

By "website status indicator" I mean the colors (green, yellow and red).

### A specific URL where the issue occurs.

`https://yeonmipark.locals.com/` (example)

### Steps to Reproduce

1. Go to any site that connects to various other websites in the background.
2. Open uBO's pop-up and see the scrollbar overlapping the website status indicator.

### Expected behavior

Scrollbar should not overlap the website status indicator.

Here's a screenshot from another user that demonstrates what I'm requesting:
https://github.com/uBlockOrigin/uBlock-issues/issues/1488#issuecomment-774649740

### Actual behavior

Scrollbar overlaps the website status indicator.

Here's a screenshot:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/30274161/5fa5c0fb-57e7-4ca5-8f04-a3cdd0eb0778)

### uBO version

1.50.0

### Browser name and version

Firefox 115.0.2 (64-bit)

### Operating System and version

Windows 11 Pro 22H2

**Comment by gorhill** [comment]
The scrollbars are styled by the browser, they render differently in other browsers. I prefer to not touch these. You can use userChrome.css if you want to customize them. Those color indicators could be removed and you would still have all the information you need on hands, the pluses/minuses are convey the same information.

**Comment by gwarser** [comment]
There should be "Always show scrollbars" setting in Firefox preferences.
