### ISSUE TITLE
Create a Python preprocessor for uBlock Origin to scrapping sites in Firefox with IPFS and undetected-chromedriver because Google want to make ad-blocking (near) impossible

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#2747]
https://stackdiary.com/web-environment-integrity/
https://github.com/ultrafunkamsterdam/undetected-chromedriver
https://github.com/ipfs/helia

**Comment by iam-py-test** [comment]
Maybe I am misunderstanding you, but uBlock Origin doesn't scrape any websites.

**Comment by KonoromiHimaries** [comment]
@iam-py-test It's must be done somehow to uBlock work properly in the future.

**Comment by iam-py-test** [comment]
This proposal (while bad) doesn't seem to effect uBo.
They state that browser extensions don't effect the assertion<sup>[[1]](https://github.com/RupertBenWiser/Web-Environment-Integrity/blob/main/explainer.md#how-does-this-affect-browser-modifications-and-extensions)</sup>
