### ISSUE TITLE
Compress images (PR)

### ISSUE THREAD

**Issue by Positron832Alt** [uBlockOrigin/uBlock-issues#2748]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I forked your repository and updated some images to have a smaller file size, but I can't open a PR in your repository :/
Here are the changes I made and hope to be merged: https://github.com/gorhill/uBlock/compare/master...Positron832Alt:uBlock:Positron832Alt-patch-1
Sorry if this is the wrong place for this

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

.

### Browser name and version

.

### Operating System and version

.

**Comment by gorhill** [comment]
![Screenshot from 2023-07-23 09-50-17](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/da3f2c11-660d-4467-b25d-c7f69a92866c)

Sorry, I prefer to decline, this doesn't really accomplish anything for uBO while this would require me to spend a lot of time scrutinizing all images to find out all is fine, and anyway, all these changes could be easily undone in some future if I rework the images.

**Comment by gorhill** [comment]
![Screenshot from 2023-07-23 09-50-17](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/d01545cd-c2a7-4062-b203-cf4d8eb2385f)

Sorry, I prefer to decline, this doesn't really accomplish anything for uBO while this would require me to spend a lot of time scrutinizing all images to find out all is fine, and anyway, all these changes could be easily undone in some future if I rework the images.

**Comment by krystian3w** [comment]
To compress images inside uBo code possible use: https://github.com/apps/imgbot

The compression is lossless, so quaility of the images will not deteriorate.

The bot up to 72 hours should compress the image you upload in the git, so then the argument about editing does not make sense (I assume that there is rarely a failure of this robot).

However, the bot will not compress images on its own, e.g. on Wiki or outside the repository, e.g.:



"`user-images.githubusercontent.com/585534/`".
