### ISSUE TITLE
Settings are not synchronized

### ISSUE THREAD

**Issue by Drovosek01** [uBlockOrigin/uBlock-issues#275]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I tried to check if the settings synchronization really works in this plugin. I downloaded Google Chrome portable version from the team PortableAppZ, installed the portable version on disk D, opened, in the browser settings logged in to your Google account, waited 40 minutes until you download and install all synchronized plug-ins for the browser.
Then I opened the settings uBlock Origin and saw that there is no tick in the "Enable cloud storage" and there is no my white list.
Unfortunately, I don't have an opportunity to check it on a non-portable version of the browser yet, but I really want not to export/import the whitelist manually.

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#settings.html

### Steps to Reproduce

1. Download and install the portable version of Google Chrome
2. Go to the settings of the portable version of the browser and log in to Google account
3. Wait until all plugins are automatically downloaded and installed
4. Go to uBlock Origin settings

### Expected behavior:

before in the" old "browser and also see those checkboxes that I placed in the plugin settings on the" old " browser.

### Actual behavior:

I went into the plugin settings and saw that all the settings were reset to the default state.

### Your environment

* uBlock Origin version: uBlock Origin v1.17.0
* Browser Name and version: Google Chrome 69.0.3497.100 
* Operating System and version: Windows 10 build 17134

**Comment by gorhill** [comment]
You said you read the documentation. The [documentation says](https://github.com/gorhill/uBlock/wiki/Cloud-storage):

> Once you enable cloud storage support, a new UI widget will be available in the dashboard for panes which support the export/import of settings to/from cloud storage [...] the sync feature in uBlock is implemented as a global clipboard (through cloud storage) to where settings are copied to/pasted from, and only you decide when to export/import.
