### ISSUE TITLE
Fresh builds fails to work in IceCat 52 on android

### ISSUE THREAD

**Issue by Flashwalker** [uBlockOrigin/uBlock-issues#276]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

**1.13.8** (addons.mozilla.org) Works in IceCat 52 (f-droid) after toggle disable/enable on addon page.

**1.17.1b2** (github) Doesn't work at all in IceCat 52 (f-droid). No menu, no options after toggling or restart.

**1.17.1b2** (github) Works fine on Waterfox 60.

### A specific URL where the issue occurs

http://127.0.0.1

### Steps to Reproduce

1. install icecat on android
2. disable addons
3. install ublock from github
3. toggle disable/enable ublock

### Expected behavior:

open dashboard page

### Actual behavior:

no button for dashboard page

### Your environment

* uBlock Origin version: 1.17.1b2
* Browser Name and version: IceCat 52
* Operating System and version: Android 7.0

**Comment by uBlock-user** [comment]
IceCat is not officially supported FYI...

**Comment by gorhill** [comment]
Not supported -- Firefox 52 ESR is no longer supported, the new ESR is Firefox 60.
