### ISSUE TITLE
After enabling the "I am an advanced user",  when clicking on Chrome uBlockOrigin extension icon, the UI interface does not fully open up and is unuseable

### ISSUE THREAD

**Issue by douglasconrath** [uBlockOrigin/uBlock-issues#2762]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I am using an ASUS Chromebook.  When using the normal Chrome browser (Version 114.0.5735.84 (Official Build) beta (64-bit)) the issues does not exist.

When using the Lacros Chrome browser (Version 116.0.5845.50 (Official Build) beta-lacros (64-bit)) when clicking on the uBlockOrigin extension icon, the UI interface does not fully open up and is unusable.

After reinstalling and testing with the extension several times, 

I can see that the issue occurs the moment I enable the "I am an advanced user" setting under the extension's "Settings" menu item.

![Screenshot 2023-08-03 8 35 19 AM](https://github.com/uBlockOrigin/uBlock-issues/assets/141331479/a268139b-f8a3-4060-9aa7-96ca5300fb02)

![Screenshot 2023-08-03 8 02 59 AM](https://github.com/uBlockOrigin/uBlock-issues/assets/141331479/19e15249-9e22-4c9e-baee-bcb7062e3896)

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/

### Steps to Reproduce

1. Open the Lacros version of the Chrome browser
2. Install uBlockOrigin extension
3. At this point the issue does not exist
4. Access the options settings for the extension
5. Go to the "Settings" menu item and enable the "I am an advanced user" setting 
6. Access any URL
7. Click On the uBlockOrigin extension icon in the toolbar and the UI interface does not fully open up and is unusable.  The extension UI interface is very narrow and all words are wrapped and no icons are viewable.

### Expected behavior

After enabling the "I am an advanced user" setting being able to use the extension UI. 

### Actual behavior

Click On the uBlockOrigin extension icon in the toolbar and the UI interface does not fully open up and is unusable.  The extension UI interface is very narrow and all words are wrapped and no icons are viewable.

### Configuration

uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 96930
 cosmetic: 39437
 scriptlet: 18003
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 68211-283, never
  easyprivacy: 33352-3, never
  plowe-0: 3723-1071, never
  ublock-badware: 7560-1, never
  ublock-filters: 33909-182, never
  ublock-privacy: 431-3, never
  ublock-quick-fixes: 401-0, never
  ublock-unbreak: 2085-23, never
  urlhaus-1: 6413-0, never
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2625 ms
 maxAssetCacheWait: 77 ms

**Comment by gwarser** [comment]
How long ago it was installed? Because filter lists are not updated yet, so maybe it's some corrupted installation?

**Comment by gorhill** [comment]
> unique to the lacros Chrome browser

You should report to the Lacros project. The popup panel dimension is controlled by the browser, uBO just provides the HTML document to put into the popup panel, and the browser is supposed to adjust the panel size according to the provided document.

**Comment by gorhill** [comment]
Related Chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1282790

**Comment by oltodosel** [comment]
I have the same issue.

uBlock Origin 1.51.0
Linux 6.4.12-arch1-1
Chromium 116.0.5845.110

**Comment by gorhill** [comment]
The issue is a Chromium one as pointed above, no point adding "me too" comment here. Just follow progress on the Chromium issue itself.
