### ISSUE TITLE
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'

### ISSUE THREAD

**Issue by AndrewPixel** [uBlockOrigin/uBlock-issues#2763]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've been using uBO with Chrome on Windows 10 for several years now. On my computer I have IIS installed and use it for development

Recently, within the last few weeks, the Chrome Console has been throwing this warning:

`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.`

I tried many things to address this and the only thing that works is disabling uBO. To me it looks like Chrome broke something.

### A specific URL where the issue occurs.

https://localhost/index.htm

### Steps to Reproduce

Launched web page via local IIS
https://localhost

### Expected behavior

No error to appear in console.

### Actual behavior

Error appears in console.

### uBO version

1.51.0

### Browser name and version

Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 22H2

**Comment by iam-py-test** [comment]
That is not a problem. It just means that Google's privacy-invasive topics API is already unavailable, so uBo can't turn it off.
[It seems they may not yet have shipped any Chrome versions with it enabled](https://developer.chrome.com/docs/privacy-sandbox/topics/)

**Comment by AndrewPixel** [comment]
I checked and Privacy Sandbox is enabled.  The repeated errors while I'm working is just too much so I've disabled uBO.

**Comment by stephenhawk8054** [comment]
@AndrewPixel Can you test if adding this filter turns off the error for you?

```adb
@@||localhost^$permissions=browsing-topics=()
```

**Comment by AndrewPixel** [comment]
Thanks, that did it. I can have uBO on and none of the errors appear.

**Comment by gorhill** [comment]
I can reproduce when loading a document from `localhost`, so maybe we should exclude it in the filter.

**Comment by krystian3w** [comment]
Maybe possible copy more lan based on: https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt

`|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local`

As long as such a list does not then become an anti-privacy attack vector.

**Comment by gwarser** [comment]
Probably @krystian3w solution should be implemented - https://www.reddit.com/r/uBlockOrigin/comments/18mv93p/console_throws_errors_when_using_localhost_with/
