### ISSUE TITLE
Firefox wont let me download this. Says "Reserved Filename Found"

### ISSUE THREAD

**Issue by Archiver736** [uBlockOrigin/uBlock-issues#2767]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

FireFox won't let me download this add-on. Says "Reserved Filename Found"

### A specific URL where the issue occurs.

https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

### Steps to Reproduce

1. Go to github.
2. Download UBlock Origin.
3. Go to FireFox homepage 
4. Insert Add-On
5. This error page shows

### Expected behavior

For the add-on to start.

### Actual behavior

Error page showed up on FireFox homepage. "Reserved File Name Found".

### uBO version

1.51.0

### Browser name and version

FireFox 

### Operating System and version

iOS: 16.5.1

**Comment by gorhill** [comment]
> https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

That's not the URL for uBO.

> iOS: 16.5.1

As pointed out by @MasterKia

**Comment by krystian3w** [comment]
Maybe bot:

https://github.com/search?q=repo%3Amozilla%2Faddons-linter%20Reserved%20Filename%20Found&type=code

https://pontoon.mozilla.org/fr/amo-linter/all-resources/?string=200587
https://pontoon.mozilla.org/ca/amo-linter/all-resources/?string=200587
https://pontoon.mozilla.org/fa/amo-linter/all-resources/?string=200587
