### ISSUE TITLE
Popup filter auto closes link that is explicitely clicked by user

### ISSUE THREAD

**Issue by NotaInutilis** [uBlockOrigin/uBlock-issues#2770]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have a recurring issue with uB0 which is that when I click a link shat should open a new window/tab, it auto-closes immediately. I found out this is caused by a filter using the `$popup` rule, and am going to report it to the list maintainer.

However, this is a link that I clicked directly, I believe it should not be treated as a popup. Or have popup windows changed a lot since popup blocking became a staple of web browsers? Firefox's popup blocker does not treat those links as popups so I'm quite confused.

The incriminated links are all the `fanatical.com` links on `gg.deals`. They are all redirected via `jdoqocy.com`, which is strictly blocked by Peter Lowe's and EasyList. This domain has `$popup,third-party` blocked on the French Adguard list.
On the `https://gg.deals/game/yakuza-like-a-dragon/` page, clicking on the first link `https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle` redirects to `https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon`.

![Capture d’écran 2023-08-09 225437](https://github.com/uBlockOrigin/uBlock-issues/assets/9675966/065f753d-63a0-44ea-92ac-28b83f86f2bf)

Moreover, this shows us 2 usability issues with uB0, at least in my experience. I am not quite sure you will find them relevant enough to fix but still, allow me to express the frustration of my debugging journey here, in a (kinda?) useful manner.

1. Even when right-clicking the auto-closed link to explicitly open it in a new tab/window, it is still treated as a popup and auto-closes. It's very confusing to the user, as even an explicit command is denied with no clear explanation.

2. A strict blocking page displays when copy-pasting the link in the URL bar, it only shows the list that block the domain with no rule, and does not show the `$popup,third-party` one. This made the whole investigation on what caused my issue so very confusing and frustrating, as I reread the prerequisites and clicked the logger link only after typing all of this issue report (and thus retyped nearly all of it) (it is actually a little bit funny, yes).

![Capture d’écran 2023-08-09 221143](https://github.com/uBlockOrigin/uBlock-issues/assets/9675966/7ac1cfdf-b732-4a82-a2da-1a662e1a28ee)

Please make the preprequisite paragraph of the issue report BIGGER and not smaller like it is now, I'm sure I'm not the only one missing such crucial info about THE LOGGER!

![Capture d’écran 2023-08-09 231219](https://github.com/uBlockOrigin/uBlock-issues/assets/9675966/4059df31-219b-4586-bdc8-158b85b2ce01)

### A specific URL where the issue occurs.

`https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon`

### Steps to Reproduce

1. Click link
2. See it close itself, with no other information given to the user
3. Try to open it explicitely by clicking open to new window
4. Again, it closes

### Expected behavior

1. Better communication to the user about what is a popup.
2. Don't auto close when the user specifically asks to open in a new window/tab.
3. Show all lists that filter a domain in the strict blocking page.

### Actual behavior

It auto closes.

### uBO version

1.51.0

### Browser name and version

Firefox 116.0.1 / Chrome 115.0.5790.171

### Operating System and version

Windows 11 64bits

**Comment by gorhill** [comment]
> incriminated links are all the fanatical.com links on deals.gg

Please provide an exact URL, I do not have the time to go on a fishing expedition to find _"links on deals.gg"_ at _"fanatical.com"_.

**Comment by NotaInutilis** [comment]
> > incriminated links are all the fanatical.com links on deals.gg
> 
> Please provide an exact URL, I do not have the time to go on a fishing expedition to find _"links on deals.gg"_ at _"fanatical.com"_.

There's already an exact URL in the rest of the paragraph (although I messed up when pasting the first link! sorry!).

You'll find 3 `deals.gg` to `fanatical.com` links on this page `https://gg.deals/game/yakuza-like-a-dragon/`
- `https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle` redirects to https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon
- `https://gg.deals/fr/redirect/ed05880177106cfab8413cf4a47db83521176aa5/?utm_source=games%2Fsingle` to https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon-hero-edition
- `https://gg.deals/fr/redirect/ed05880177106cfab8413cf4a47db83521176aa5/?utm_source=games%2Fsingle` to `https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon-legendary-hero-edition`

**Comment by gorhill** [comment]
> There's already an exact URL in the rest of the paragraph

You said:

> at "fanatical.com"

Those URLs are not at `fanatical.com`, I get a strict-blocked page, meaning I can't reproduce the issue you are describing. Given this, I will consider the issue as a filter issue.

**Comment by NotaInutilis** [comment]
I think there's a misanderstanding. I'm talking about links from deals.gg to fanatical.com. Meaning navigating on deals.gg and clicking on a link that redirects to fanatical.com (via a jdoqocy.com redirection that triggers the filter).

I genuinely don't understand you are asking from me here: there is no mention of "at fanatical.com" and I've provided you with a deals.gg url which contains 3 links (the 3 fanatical.com links) triggering the popup  French Adguard filter incorrectly.

![Capture d’écran 2023-08-10 020822](https://github.com/uBlockOrigin/uBlock-issues/assets/9675966/5153be41-35d1-4ccf-b07e-26084f6b0436)

Please, tell me what information is missing there, I'm genuinely quite lost.

**Comment by gorhill** [comment]
> The incriminated links are all the `fanatical.com` links on `gg.deals`

Sorry I got this the other way around.

> Even when right-clicking the auto-closed link to explicitly open it in a new tab/window

uBO doesn't know how the link was clicked, just that there is a new tab created with a specific URL.

> A strict blocking page displays when copy-pasting the link in the URL bar, it only shows the list that block the domain with no rule, and does not show the `$popup,third-party` one

Strict-blocking is completely unrelated to `popup` filter option. The filter which caused the strict blocking is really the one shown on the page, `||jdoqocy.com^`. Strict blocking can occur without a new tab being created, it's unrelated to tab creation.

> This made the whole investigation on what caused my issue so very confusing and frustrating

Use the logger, this shows you everything, why things are blocked, and by what. In cases of new tabs created from another webpage, select the _All_ entry in the list at the top of the logger.

**Comment by NotaInutilis** [comment]
Issue resolved with Adguard filters! https://github.com/AdguardTeam/AdguardFilters/issues/158749

What got me confused regarding if that was a uB0 or a filter issue is how the `popup` option behaves. The uB0 doc links to the ABP doc which is not super clear regarding this option. However, the Adguard doc explains it way better https://adguard.com/kb/fr/general/ad-filtering/create-own-filters/#popup-modifier

> ||domain.com^$popup — if you try to go to http://domain.com/ from any page in the browser, a new tab in which specified site has to be opened will be closed by this rule.

It treats the whole domain as a popup to be auto-closed instead of only blocking popup windows from the domain as I wrongly believed. What got me even more lost is the appearance of a strict blocking page at the same time as the anti-popup behavior was triggered which made me think these were linked and/or could give me more info about the issue.
