### ISSUE TITLE
Cloud storage option enabled on Thunderbird

### ISSUE THREAD

**Issue by NotaInutilis** [uBlockOrigin/uBlock-issues#2771]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The "Enable cloud storage" option is available when installing uB0 on Thunderbird, although TB does not support cloud storage.
When checked, it allows uploading to an unknown destination.

![Capture d’écran 2023-08-10 000408](https://github.com/uBlockOrigin/uBlock-issues/assets/9675966/92be0dca-4a31-4e63-b8f6-9ef60516346d)

The debug info seems to wrongly identify Thunderbird as Firefox.

> uBlock Origin: 1.49.2
> Firefox: 115

As per the documentation https://github.com/gorhill/uBlock/wiki/Cloud-storage

> If your browser/environment does not support cloud storage, the feature will be disabled.

### A specific URL where the issue occurs.

moz-extension://22875c00-6504-4e31-a8a1-30b88c347778/dashboard.html#settings.html

### Steps to Reproduce

Open uB0 options, check enable cloud storage.

### Expected behavior

No option to enable cloud storage.

### Actual behavior

It is possible to enable cloud storage and sync with an unknown destination

### uBO version

1.49.2

### Browser name and version

Thunderbird 115.1.0

### Operating System and version

Windows 11 64bits

**Comment by gorhill** [comment]
If the `browser.storage.sync` API is available, [uBO will use it](https://github.com/gorhill/uBlock/blob/1.51.0/platform/common/vapi-background.js#L1569). Whether the API is doing what it's supposed to do is something out of view of uBO.

**Comment by gwarser** [comment]
>If you do not have a syncing account with your browser vendor, I have observed that the cloud storage feature can still be used as a local clipboard to save a pane's settings. 

https://github.com/uBlockOrigin/uBlock-issues/wiki/Cloud-storage
