### ISSUE TITLE
Cosmetic filter is not logged on certain pages

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2778]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`medium.com##div[role="dialog"] ~ div > div[style="bottom: 0px;"]` in AdGuard - Popup Overlays, or virtually any cosmetic filter on the page, is not logged on `https://medium.com/@vincy57/simplification-of-the-french-language-that-both-integrates-international-cultures-and-facilitates-829916782747` with 1.51.1b15 while logged with 1.51.0. It's the same both on Chrome and on Firefox. The same trouble was observed on `https://www.wp.pl/` and it turned out to be caused by `money.pl,wp.pl##div[class]:has(>div[class]:first-child:has-text(REKLAMA):not(:has(>*)))` in regional list.

### A specific URL where the issue occurs.

https://medium.com/@vincy57/simplification-of-the-french-language-that-both-integrates-international-cultures-and-facilitates-829916782747

### Steps to Reproduce

1. Enable AdGuard – Annoyances
2. Visit the site with the logger opened

### Expected behavior

Cosmetic filters logged

### Actual behavior

Not

### uBO version

1.51.1b15

### Browser name and version

Chrome  115.0.5790.171/Firefox 116.0.2

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
It's broken only when "AdGuard – Other Annoyances" sublist is enabled.

**Comment by gwarser** [comment]
This one is causing it:

    medium.com#?#div[class*=" "]:has(> div[class*=" "] > h2[class*=" "]:contains(/^Get unlimited access/))

**Comment by JobcenterTycoon** [comment]
@gwarser @gorhill

The filter
```
o2.pl##div[class][style="width:100%"] > div[class*=" "]:has(:scope > img[role="presentation"]:not([src]))
```

still causing the issue. Test page: `https://www.o2.pl/informacje/myslalam-ze-takich-knajp-juz-nie-ma-cena-za-zupe-i-schabowego-to-hit-6934082025515968a`.

Filter found in the filterlist `pl: Oficjalne Polskie Filtry do uBlocka Origin`

**Comment by krystian3w** [comment]
`:scope` don't works in CSS4 for `:has`.

**Comment by gwarser** [comment]
Regression: https://www.reddit.com/r/uBlockOrigin/comments/16ijmci/do_some_filters_need_to_be_changed_to_work_with/

**Comment by gwarser** [comment]
And now also https://github.com/uBlockOrigin/uBlock-issues/issues/2818

**Comment by JobcenterTycoon** [comment]
`money.pl,wp.pl##div[class]:has(>div[class]:first-child:has-text(REKLAMA):not(:has(>*)))` breaks uBlock Origin again in the latest dev version `uBlock Origin 1.52.1b2`

**Comment by gorhill** [comment]
Feedback dried out, assuming it's fixed.
