### ISSUE TITLE
Cannot mail contact@ublockorigin.com

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uBlock-issues#2784]
### Description
The only way I can reach you is from GitHub since the email is unreachable.

"If you're interested in contributing to this project, please get in touch[contact@ublockorigin.com]." - https://ublockorigin.com/

### A specific URL where the issue occurs.

https://ublockorigin.com/

### Steps to Reproduce

* Send an email to contact@ublockorigin.com

### Expected behavior

The email to contact@ublockorigin.com should be delivered.

### Actual behavior

Returned email response:
```
The response from the remote server was:

550 5.1.1 <contact@ublockorigin.com>: Recipient address rejected: User unknown in virtual mailbox table 
```

**Comment by mapx-** [comment]
There is no such official site managed by uBO team.
The site above was created by some uBO user - not related to the team.

**Comment by stephenhawk8054** [comment]
> This website is maintained by [Uros Gazvoda](https://www.linkedin.com/in/urosgazvoda/), founder of [Futuristica](https://futuristica.com/), to help spread uBlock Origin - free, open-source ad blocker.

**Comment by stanlane** [comment]
> > This website is maintained by [Uros Gazvoda](https://www.linkedin.com/in/urosgazvoda/), founder of [Futuristica](https://futuristica.com/), to help spread uBlock Origin - free, open-source ad blocker.

Oh, I just noticed this at https://github.com/gorhill/uBlock:
> BEWARE! uBO is (and has always been) COMPLETELY UNRELATED to the website ublock.org.

**Comment by stephenhawk8054** [comment]
> `ublock.org`

It's actually another website. The website you mentioned above is `ublockorigin.com`

**Comment by krystian3w** [comment]
We feather the addon bugs publicly on the forum as they are not 0-day vulnerabilities that are better patched and disclosed 30-90 days after the release: https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&projects=&template=security_report.yml

If you send some garbage (such as vulgarities) to that email, you will be regularly banned however gorhill's private domain allows.
