### ISSUE TITLE
Addy.io still called Anonaddy in Forward email alias service drowdown

### ISSUE THREAD

**Issue by Snowpop** [uBlockOrigin/uBlock-issues#2787]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On **every** uBlock Origin client I use (extension, web, mobile), Forward email alias service Addy.io still shows as Anonaddy in the 'Service' dropdown menu on the 'Generator' tool page when preparing to generate a forwarding email alias.

Anonaddy recently rebranded to Addy.io

_PS: Had to tick off some of the prerequisites while they are actually not necessary for this issue. Hope it's still valid, as I was not able to find a better place to report this._

### A specific URL where the issue occurs.

https://vault.bitwarden.com/#/tools/generator

### Steps to Reproduce

1. Open any uBlock Origin client (in this case I will be using web)
2. Go to 'Tools'
3. Select 'Generator'
4. Under 'What would you like to generate?' select 'Username'
5. Select username-type 'Forwarded email alias'
6. Click on the dropdown menu under 'Service'

### Expected behavior

It will list Addy.io among other services

### Actual behavior

It lists Anonaddy, instead of Addy.io to which Anonaddy rebranded to about 2 weeks ago

[source](https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/)

### uBO version

1.51.0

### Browser name and version

Google Chrome, Version 115.0.5790.182 (Official Build) (32-bit)

### Operating System and version

ChromeOS, Version 115.0.5790.182 (Official Build) (32-bit)

**Comment by iam-py-test** [comment]
This is an issue with uBlock Origin's filterlists, not uBo it's self. Therefore, it should be reported at uAssets: https://github.com/uBlockOrigin/uAssets/issues
This was one of the prerequisites you ignored.
Please:
- click the uBlock origin icon on the problematic website
- click the chat icon
- follow the instructions on the screen to report this issue to the proper place.
Thank you.

**Comment by stephenhawk8054** [comment]
These steps are not for uBO, it's for Bitwarden


> 1. Open any uBlock Origin client (in this case I will be using web)
> 2. Go to 'Tools'
> 3. Select 'Generator'

**Comment by iam-py-test** [comment]
Re-reading the issue, it seems the entire issue is about Bitwarden, with the OP weirdly calling it 'uBlock Origin'.

**Comment by krystian3w** [comment]
Add domain their:

https://vault.bitwarden.com/#/settings/domain-rules

As an alias to avoid edit pool "match URL-s".
