### ISSUE TITLE
Whitelist From Logger Should Go To My Filters

### ISSUE THREAD

**Issue by BlazeFTL** [uBlockOrigin/uBlock-issues#2789]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I Think It Used To Go To My Filters Before But Now It Doesn't ?
Or Atleast A Option To Do So ?

### A specific URL where the issue occurs.

*

### Steps to Reproduce

*

### Expected behavior

*

### Actual behavior

*

### uBO version

*

### Browser name and version

*

### Operating System and version

*

**Comment by iam-py-test** [comment]
What are you trying to do?
This button does not create a permanent allowlist filter. Instead, it disables the filter while the logger is open:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/84232764/10524212-15f3-419d-83a2-7e00e54dcdd6)

**Comment by garry-ut99** [comment]
> What are you trying to do?

He made it clear: "Or Atleast A Option To Do So " = that he requests to restore the permanent exception possibility.

By looking at this description: [LINK](https://github.com/gorhill/uBlock/commit/a91781a4959c0381c8ab3230545e4e0f579d4a2c) it says: 

> The "exceptor" feature has been rewritten, with the following changes as a result:
> The excepted filters cease to exist when closing the logger

doing a logical deduction, it seems that previously the exception was permanently saved and now is not anymore.

**Comment by gwarser** [comment]
There is a way to create exceptions for network filters from the logger https://github.com/gorhill/uBlock/wiki/The-logger#static-network-filters and for cosmetic filters from DOM Inspector https://github.com/gorhill/uBlock/wiki/DOM-inspector#creating-cosmetic-filter-exception

One thing missing is support for the scriptlet filters. Right?
