### ISSUE TITLE
support kiwi browser

### ISSUE THREAD

**Issue by idontveapc** [uBlockOrigin/uBlock-issues#2791]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

###### [no caps]

on the recent version(s) ubo seems buggy or likely taking a bit longer time to start filtering. im on kiwi browser which is, like FIREFOX, [open source](https://github.com/kiwibrowser/src.next/).

##### kiwi browser users tell that ubo is not officially supported as they're said to use only firefox.

if kiwi browser wasn't supported, so ubo worked just for supporting webstore extensions(as chrome on pc is supported, right?!)?

### A specific URL where the issue occurs.

1. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/popup-fenix.html 2. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html 3. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=easylist

###### [steps aren't serial/in order]

in my experience ubo seemed unsupported to me when i was to add a filter or see/search in filter lists(like easylist). it just not fits the display and takes options to the roof.

some domains, that are connected via/to a website, aren't showed on the main pane(with im an advanced user enabled). like ``geo.yahoo.com`` and neither adding a rule in my rules block it.

on the recent version(s) either hiding elements or adblock is slow or takes more time now.

### Expected behavior

if ubo can be checked on kiwi for; like, adding filters, searching for a domain in the filter list(s), and how connected domains are visualised then accepted behavior will be apparent.

i feel the support i dont see is; it doesn't fit the display.(especially in filter lists and also in my filters with a lot of filters. adding filters in my filters gets impossible because of the glitch.)

### Actual behavior

not fitting the display, slow blocked elements hiding, takes longer to activate on the browser start up, and, not all domains are visible.

### uBO version

1.51.0

### Browser name and version

Kiwi Browser 116.0.5845.72

### Operating System and version

android ...

**Comment by gwarser** [comment]
> some domains, that are connected via/to a website, aren't showed on the main pane(with im an advanced user enabled). like `geo.yahoo.com` and neither adding a rule in my rules block it.

Kiwi source code:

https://github.com/kiwibrowser/src/blob/86afd150b847c9dd6f9ad3faddee1a28b8c9b23b/extensions/browser/api/web_request/web_request_permissions.cc#L189

**Comment by stephenhawk8054** [comment]
@idontveapc You can easily verify by visiting

```
https://kiwisearchservice.googlesyndication.com/
```

and

```
https://kiwisearchservices.googlesyndication.com/
```

The difference is `s` at the sub-domain. One is blocked by uBO as expected. One is not.

**Comment by gwarser** [comment]
It's not uBO issue. It's already explained, Kiwi is deliberately breaking ad blockers.

**Comment by ravilov** [comment]
> Kiwi source code:
> 
> https://github.com/kiwibrowser/src/blob/86afd150b847c9dd6f9ad3faddee1a28b8c9b23b/extensions/browser/api/web_request/web_request_permissions.cc#L189

Just a quick update, this is still mentioned in the latest (and last ever) `src.next`, but in a much different capacity:

<https://github.com/search?type=code&q=repo:kiwibrowser/src.next+kiwisearchservices>
