### ISSUE TITLE
[Bug Report] uBlock Origin in Brave will cause script loading inside sandbox iframe

### ISSUE THREAD

**Issue by cyfung1031** [uBlockOrigin/uBlock-issues#2793]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This happens in some sites but not all sites.
This does not happen in other browsers like Chrome or Firefox.
I am sure it is related to Brave's built-in script injection.
**It only appears when uBlock origin is enabled.**
It appears no matter Brave's built-in trackers & ads blockers are ON/OFF.
(as the script injected by Brave cannot be turned on/off)

### Example Websites

All webpages (including robots.txt) https://www.youtube.com
All webpages (including robots.txt) https://www.google.com
All webpages (including robots.txt) https://m.youtube.com

### A specific URL where the issue occurs.

* https://www.google.com/robots.txt
* https://www.youtube.com/robots.txt
* https://www.google.com/
* https://www.youtube.com/
* https://m.youtube.com/robots.txt

### Steps to Reproduce

1. Go to the robots.txt url.
2. open DevTools and execute the following
```js
let frame =  document.createElement('iframe');
frame.sandbox = 'allow-same-origin';
document.documentElement.appendChild(frame);
```

### Expected behavior

No error or any message

### Actual behavior

`Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.` is shown.

<img width="845" alt="Screen Shot 2023-09-01 at 19 21 07" src="https://github.com/uBlockOrigin/uBlock-issues/assets/44498510/07ac2fbd-644e-4c5d-bd8f-70a04f9cb973">

### uBO version

1.51.0

### Browser name and version

Brave 1.57.53 Chromium: 116.0.5845.114 (Official Build) (arm64) 

### Operating System and version

MacOS 12.6.1

**Comment by stephenhawk8054** [comment]
It's caused by

```adb
www.google.*##+js(set-constant, rwt, noopFunc)
```

**Comment by cyfung1031** [comment]
Update. Caused by the following built-in rules

## uBlock filters – Ads

```
youtube.com,youtubekids.com,youtube-nocookie.com##+js(json-prune, playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds, playerConfig.audioConfig)
youtube.com,youtubekids.com,youtube-nocookie.com##+js(json-prune, playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds, playerResponse.playerConfig)

youtube.com,youtubekids.com,youtube-nocookie.com##+js(set, ytInitialPlayerResponse.adPlacements, undefined)
youtube.com,youtubekids.com,youtube-nocookie.com##+js(set, playerResponse.adPlacements, undefined)
```


## uBlock filters – Quick fixes
```
youtube.com,youtubekids.com,youtube-nocookie.com##+js(json-prune, playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds, playerConfig.audioConfig)
```

**Comment by stephenhawk8054** [comment]
As I said, it's caused by any scriptlets. Brave uses scriptlets same as uBO so I'm not if they would cause conflicts here.

**Comment by gorhill** [comment]
uBO doesn't have knowledge about whether the context is sandboxed when scriptlets are injected. Worst that can happen is that the scriptlets do not execute.

**Comment by cyfung1031** [comment]
> uBO doesn't have knowledge about whether the context is sandboxed when scriptlets are injected. Worst that can happen is that the scriptlets do not execute.

But can you fix that,

if the page is inside the sandbox iframe, 
```
.....##+js(...)
```
shall not be executed to avoid error log?
