### ISSUE TITLE
YouTube won't load anymore

### ISSUE THREAD

**Issue by harshsingh0930** [uBlockOrigin/uBlock-issues#2794]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am using this extension from time being, but now it won't work on YouTube anymore, I tried disabling all YouTube extensions and also others ad blockers except uBO but problem still persist. YouTube website is not loading at all 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/143863521/ed71328e-37ee-4979-ba90-015bebbaf494)

### A specific URL where the issue occurs.

https://www.youtube.com/

### Steps to Reproduce

Disable all other YouTube related extensions and all ad blockers
Only enable uBO and then run YouTube on Firefox on latest version till dated today

### Expected behavior

What I expected?.........sorry am not so good with questions but i expected that problem is in my pc or web browser but it is in extension

### Actual behavior

Youtube website won't even load and stucked on no network like interface more precisely blank page

### uBO version

1.51.0

### Browser name and version

Firefox 1.51.0

### Operating System and version

Windows 10 22H2

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/7636
