### ISSUE TITLE
I cannot force uBO to accept my config by `adminSettings`/`hiddenSettings` policy

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#2795]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

File `$HOME/.mozilla/managed-storage/uBlock0@raymondhill.net.json`

Config is copied from backup file.

This does not work:

```JSON
{
    "name": "uBlock0@raymondhill.net",
    "description": "ignored",
    "type": "storage",
    "data":
    {
        "adminSettings":
        {
            "hiddenSettings":
            {
                "benchmarkDatasetURL": "http://localhost:8080/requests.json"
            }
        }
    }
}
```
```JSON
{
    "name": "uBlock0@raymondhill.net",
    "description": "ignored",
    "type": "storage",
    "data":
    {
        "adminSettings": "{\"hiddenSettings\":{\"benchmarkDatasetURL\":\"http://localhost:8080/requests.json\"}}"
    }
}
```

This works:

```JSON
{
    "name": "uBlock0@raymondhill.net",
    "description": "ignored",
    "type": "storage",
    "data":
    {
        "advancedSettings":
        [
            ["benchmarkDatasetURL", "http://localhost:8080/requests.json"]
        ]
    }
}
```

This applies only the whitelist entry:

```JSON
{
    "name": "uBlock0@raymondhill.net",
    "description": "ignored",
    "type": "storage",
    "data":
    {
        "adminSettings":
        {
            "hiddenSettings":
            {
                "benchmarkDatasetURL": "http://localhost:8080/requests.json"
            }
        },
        "toAdd": {
            "trustedSiteDirectives": ["canary.test"]
        }
    }
}
```

### A specific URL where the issue occurs.

moz-extension://

### Steps to Reproduce

1. save the file with a sample data
2. reload uBO from debug or add-ons page twice

### Expected behavior

Advanced settings applied.

### Actual behavior

Nothing changes.

### Configuration

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 98371
 cosmetic: 39466
 scriptlet: 18301
 html: 1027
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35374-89, 1h.29m
  ublock-badware: 7908-0, 1h.29m
  ublock-privacy: 569-0, 1h.29m
  ublock-unbreak: 2168-1, 1h.29m
  ublock-quick-fixes: 226-3, 1h.29m
  easylist: 69791-706, 1h.29m
  easyprivacy: 33261-718, 1h.29m
  urlhaus-1: 5817-0, 1h.29m
  plowe-0: 3724-2, 1h.29m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 141 ms (selfie)
 maxAssetCacheWait: 65 ms
```

**Comment by gorhill** [comment]
`hiddenSettings` is ignored when using `adminSettings`. Should be not too complicated to fix. Is this something which should be fixed before releasing current release candidate as stable release?

**Comment by gwarser** [comment]
> Is this something which should be fixed before releasing current release candidate as stable release?

I don't think so. I came across this when testing if the "new way" of applying settings is working, and this was my randomly chosen test sample for "old way".

**Comment by gorhill** [comment]
Actually, I don't think I will fix this. `adminSettings` was added a long time ago as a quick way to offer administrators a way to pre-configure uBO.

The real way to customize advanced settings is through the dedicated `advancedSettings` property: <https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin:-configuration#advancedsettings>.

Ultimately people should avoid using `adminSettings`, and in case there is no choice to use it, this should be reported so I can keep working on the better approach to set admin settings.
