### ISSUE TITLE
youtube not open

### ISSUE THREAD

**Issue by UriF** [uBlockOrigin/uBlock-issues#2796]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

UblockOrigin for Chrome -  blank page if you try to open YouTube.   I found this issue in Chrome Browser only.  When I disable UblockOrigin I am able to watch YouTube again.   I tried YouTube in Mozilla or other Chrome clones and it works OK.  Therefore it is a problem with a new Google Chrome version

### A specific URL where the issue occurs.

https://www.youtube.com/@kontinentusa/videos

### Steps to Reproduce

Go to YouTube at Google Chrome (Windows 10 x64 - desktop)- blank page
disable UblockOrigin  - works
enable UblockOrigin - blank page

### Expected behavior

Open YouTube normally

### Actual behavior

YouTube at Google chrome blank screen

### uBO version

1.51.0

### Browser name and version

Google Chrome 116.0.5845.141

### Operating System and version

Windows 10 x 64 OS build 19045.3324

**Comment by mapx-** [comment]
YT issues => https://github.com/uBlockOrigin/uAssets/issues/7636
