### ISSUE TITLE
Feature: button to export all cached filter lists

### ISSUE THREAD

**Issue by polu73** [uBlockOrigin/uBlock-issues#2797]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I suggest adding a button to export the currently-cached versions of all the filter lists to text files.

It's useful if you want to make a backup of the cached versions before fetching any updates, especially in case there's something in the new versions of the lists that messes with your own filters etc and you want to be able to easily revert back whilst checking what the issue is.

It also allows for easily importing your current setup to other adblockers, or for any other application where you could do with a list of the filters you currently use (for various analysis etc).

For the above reasons I specifically suggest the export feature be for the currently-cached versions of the filter lists. If someone wants to export the newest available versions, they can just fetch the updates to their local cache and then export.

Even for exporting the newest available versions, it's just quicker and more convenient to be able to export them all (including the custom ones you've imported) through the click of a button from the dashboard rather than clone https://github.com/uBlockOrigin/uAssets for the default and have to download your custom lists from their respective URLs individually.

Bonus options would be to be able to choose to export to each filter list to a separate flle or all of them combined into a single file, and export only the checked filter lists that you are using or all of them, or to be able to select specifically which ones you want to export.

Similar suggestions made in the past:
https://www.reddit.com/r/uBlockOrigin/comments/hsyrsj/export_filter_lists_contents_to_a_single_text_file/
https://www.reddit.com/r/uBlockOrigin/comments/8qhv14/request_add_importexport_for_filter_lists_section/
https://www.reddit.com/r/uBlockOrigin/comments/klpclp/how_to_export_default_adblocking_lists_to_android/
https://www.reddit.com/r/uBlockOrigin/comments/tc8pst/where_are_my_filters_stored_on_my_computer/

### A specific URL where the issue occurs.

NA

### Steps to Reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### uBO version

NA

### Browser name and version

NA

### Operating System and version

NA

**Comment by gwarser** [comment]
Just click the eye icon next to list name and then arrow in top right.

**Comment by polu73** [comment]
> Just click the eye icon next to list name and then arrow in top right.

I'm aware that's currently what seems to be the closest option available, but the suggestion is precisely in order to avoid this one-by-one approach and instead do it for all lists or multiple lists in one go. Doing it one-by-one is no fun when you have a large number lists.

> use list in different software, which will not work

How so? I'm aware uBlock Origin has some unique syntax, but isn't it mostly a common standard shared by e.g. Adblock Plus and AdGuard?

**Comment by polu73** [comment]
> use list in different software, which will not work
And even so, that would only be for lists that use UBO-specific syntax, not general filter lists around the web that only use syntax common with other adblockers. The choice of which exported lists to use can be decided after actually exporting them all, unless as suggested above there's an option to select which ones you want to export.

**Comment by gwarser** [comment]
Then what's the point to export them from uBO, when you can use the source? https://filterlists.com/

**Comment by polu73** [comment]
> Then what's the point to export them from uBO, when you can use the source? https://filterlists.com/

To get the **cached** versions you are currently using, not the latest available versions.
