### ISSUE TITLE
uBlock origin isn't effective at blocking YouTube Ads anymore

### ISSUE THREAD

**Issue by alexceltare2** [uBlockOrigin/uBlock-issues#2799]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I keep "seeing" ads (more like hear them and has to wait to skip them) even with updated lists and on Chrome 109.

### A specific URL where the issue occurs.

youtube.com

### Steps to Reproduce

1. Go to youtube.com
2. Play any video

### Expected behavior

Ads should not appear

### Actual behavior

Plays ad but no video of the ad.

### uBO version

Latest

### Browser name and version

Chrome 109

### Operating System and version

Windows 7

**Comment by iam-py-test** [comment]
ALL issues with YouTube should be reported at https://github.com/uBlockOrigin/uAssets/issues/7636.
Thanks
