### ISSUE TITLE
many issue on Firefox for android

### ISSUE THREAD

**Issue by ale82to** [uBlockOrigin/uBlock-issues#28]
on Android and latest version of Firefox element picker to create custom cosmetic filters doesn't seem to work anymore I can select the element I want to hide but I cannot see the ok button to make changes permanent.
also the refresh button isnt working anymore since a couple of last beta
also today version 1.15.5b0 completely messed the layout of the popup.

**Comment by ale82to** [comment]
thanks for the reply I made a screen cast of the issue
http://linkstore.ru/mfile/data/668138253.jsp
supposing u want to hide the bottom part of the APKMirror.com page

**Comment by gorhill** [comment]
I couldn't play your video, unknown mime format.

Anyway, I went to `apkmirror.com` and I could remove the footer element with no issue with uBO 1.16.5b0 on Firefox for Android.

**Comment by ale82to** [comment]
did u reloaded the page the removed element reappears for me

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Element-picker#the-removed-element-reappears-when-you-reload-the-page

**Comment by ale82to** [comment]
thanks for tooking the time to assist anyway I factory resetted ublock and disabled both stylus and tampermonkey (just in case...) could not solve the issue

**Comment by uBlock-user** [comment]
Nothing here makes sense, put some effort and provide all the information asked in the template.

**Comment by gwarser** [comment]
>I can select the element I want to hide but I cannot see the ok button to make changes permanent.

May be tiny, hidden in bottom right corner.

>also the refresh button isnt working anymore since a couple of last beta

Cannot reproduce.

>also today version 1.1**6**.5b0 completely messed the layout of the popup.

This was intended to fix this https://github.com/gorhill/uBlock/issues/2809

----------------

Can someone try:

 - Firefox Beta Android
 - add http://forums.mozillazine.org/viewtopic.php?f=23&t=3040067 to bookmarks
 - kill Firefox, remove from recent apps
 - Open Firefox
 - open above link from bookmark
 - go to menu, select UBO
 - tap on Picker icon

What happens:

 - Poppup does NOT close
 - tooltip appears
 - when I manually switch to mozillazine tab, all works as intended

**Comment by ale82to** [comment]
just in case I wiped all Firefox data to have a fresh start issue is all the same I simply cannot see the ok button to permanently save the selected element I intend to remove

**Comment by ale82to** [comment]
cool in my system as suspected I miss all the preview create pick box

**Comment by ale82to** [comment]
here s the screenshot
https://ibb.co/eDhFzS

**Comment by uBlock-user** [comment]
That's the Element Zapper, not the Picker, changes made by Zapper stick till you refresh.

**Comment by gorhill** [comment]
@gwarser I can reproduce your observation, I believe this is <https://bugzilla.mozilla.org/show_bug.cgi?id=1410749>.

**Comment by gorhill** [comment]
> here s the screenshot

As pointed out by @uBlock-user, you are using the [element zapper](here s the screenshot).

Given this and the fact that I could not reproduce any of your other reported issues, I am confident the all of them are invalid. If you really think there is an issue, respect the template and always, _always_ provide clear, detailed steps to reproduce.

**Comment by gorhill** [comment]
> if it can help I have same issue with yandex Browser based on Chromium which support extensions on Android.

I don't officially support Yandex browser, if uBO is expected to work seamelssly by someone but ends up not working as expected, someone else will have to work on fixes for this, and I am open to import them if I feel there is no risk to stability for the officially supported platforms.

**Comment by ale82to** [comment]
ok so stupid question how can I have the box with preview edit pick on right bottom appear ?

**Comment by gorhill** [comment]
[Popup panel / The tools](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools):

> Click the eye-dropper icon to enter [element picker mode](https://github.com/gorhill/uBlock/wiki/Element-picker)

**Comment by ale82to** [comment]
OMG I m really sorry I fell so stupid everything s ok thank very much for helping
thank you

**Comment by uBlock-user** [comment]
FYI - Keep any questions to https://www.reddit.com/r/uBlockOrigin/
