### ISSUE TITLE
Add X to close overlay box

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uBlock-issues#280]
Please add an [X] to close the white overlay box here.
The user may not understand that clicking outside of it will close it.

![0](https://user-images.githubusercontent.com/1230959/47262242-983d8c00-d515-11e8-86eb-20f8d515224d.jpg)

The user has already clicked the create button.

**Comment by uBlock-user** [comment]
Fixed in [dev build](https://github.com/gorhill/uBlock/releases/tag/1.17.7b3)
