### ISSUE TITLE
Domains ending in . are rejected, despite being valid FQDNs

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uBlock-issues#2800]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The filter from https://github.com/AdguardTeam/tsurlfilter/issues/106 does not work and shows an error in the My Filters tab:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/84232764/e685dac7-3e07-4231-ac4d-ead3b1401aeb)
`||rarbgto.org.^` works fine

### A specific URL where the issue occurs.

N/A

### Steps to Reproduce

- add `$domain=example.com` to the My Filters tab
- Notice it is valid and blocks example.com
- Add `$domain=example.com.` and remove the previous filter
- Notice it is invalid and blocks neither example.com nor example.com., despite both being valid domains
Thanks

### Expected behavior

`$domain=example.com.` is treated as valid and blocks `example.com` and `example.com.`

### Actual behavior

It is treated as invalid

### uBO version

uBlock Origin 1.51.1rc2

### Browser name and version

Firefox 117.0 (64-bit)

### Operating System and version

Windows 10 Home 22H2, build 19045.3393

**Comment by gorhill** [comment]
There is no need to use a trailing `.`, all hostname-based values are normalized to remove trailing dot internally.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7619#issuecomment-652970806

**Comment by iam-py-test** [comment]
Ok. I did not expand my search for duplicate issues into the uAssets issue tracker, so I did not see that comment.
Sorry.

**Comment by gorhill** [comment]
The question is why was `domain=rarbgto.org.` crafted this way when it can just be `domain=rarbgto.org`. What was the reason?

**Comment by iam-py-test** [comment]
I saw https://github.com/AdguardTeam/tsurlfilter/issues/106, and noticed uBo acted the same way.
So there was not a real usecase.
Sorry
