### ISSUE TITLE
Unlock Origin has stopped blocking ads on Twitch as of a few days ago.

### ISSUE THREAD

**Issue by CJStyles123** [uBlockOrigin/uBlock-issues#2804]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As of a few days ago Ublock Origin has stopped blocking Twitch Ads! I’ve also tried using the other as block extensions on the Chrome webstore and they also have the same result. I’ve not modified any filter lists and simple just go on my laptop to watch streams and then head off.

### A specific URL where the issue occurs.

https://twitch.tv/caseoh_

### Steps to Reproduce

1. Watch a stream
2. Wait until an ad pops up and you have to wait a few seconds/minutes. 

### Expected behavior

I expected it to block ads like it did a couple of days ago. Multiple users have said on the last week of August that the ad blocker stopped working, assuming Twitch released something to block these Ad Blockers.

### Actual behavior

Twitch streamer had an ad break and the ads have came up. Before, it wasn’t the case and it would block all the ads with the same streamer.

### uBO version

1.51.0

### Browser name and version

Microsoft Edge Version 116.0.1938.69

### Operating System and version

Windows 11 Canary build, Build 25941

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
