### ISSUE TITLE
Support 0.001 multiplier for nano-sib and nano-stb

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2808]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The current minimum is 0.002, but AG now supports 0.001 and actually used in Other Annoyances list.

### A specific URL where the issue occurs.

https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#adjust-setinterval

### Steps to Reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### uBO version

1.51.0

### Browser name and version

Chrome 116.0.5845.179

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
@Yuki2718 do you have a way to test it?

**Comment by Yuki2718** [comment]
> do you have a way to test it?

No, but maybe creating a test page with very slow countdown?
