### ISSUE TITLE
Increase length of 'googlesyndication_adsbygoogle.js' redirection resource

### ISSUE THREAD

**Issue by piquark6046** [uBlockOrigin/uBlock-issues#2809]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

![Screenshot from 2023-09-08 19-47-36](https://github.com/uBlockOrigin/uBlock-issues/assets/98787049/1db424b1-17c3-4709-afca-40f4de29d7d8)

The anti-adblock script on aagag.com checks factors mentioned in https://github.com/uBlockOrigin/uBlock-issues/issues/2772 and its length.

- https://piquark6046.github.io/testpage/XMLResponse-aagag/20230908/
- https://github.com/AdguardTeam/AdguardFilters/issues/161141
- https://github.com/List-KR/List-KR/issues/769#issuecomment-1711403255

### A specific URL where the issue occurs.

https://aagag.com/issue/?idx=1287083

### Steps to Reproduce

Pleas visit the website.
If you use List-KR filters list or uAssets filters lists, please apply the following filters:
```adblock
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,from=aagag.com,badfilter
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule=googlesyndication_adsbygoogle.js:5,from=~zipextractor.app,badfilter
||pagead2.googlesyndication.com^$xhr,redirect-rule=noop.js,badfilter
```

### Expected behavior

`XMLHttpRequest.prototype.responseText.length` (`jQuery.ajax.done`) returns higher than `100000`.

### Actual behavior

`XMLHttpRequest.prototype.responseText.length` (`jQuery.ajax.done`) returns lower than `100000`.

### uBO version

1.51.0

### Browser name and version

Mozilla Firefox Developer Edition 118.0b6

### Operating System and version

Ubuntu 23.04

**Comment by gorhill** [comment]
From <https://github.com/AdguardTeam/Scriptlets/issues/357>:

> If they want to detect that they're dealing with a stub, they will be able to do that, script size is just one of the factors, we cannot remove all of these signals.
