### ISSUE TITLE
Isolated Web Co segfault with Firefox version 117

### ISSUE THREAD

**Issue by awilum8** [uBlockOrigin/uBlock-issues#2812]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Go to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1852441

Could you signed the firefox xpi for the version 1.52.0, so I could test it, if the problem is still there.

Best regards

### A specific URL where the issue occurs.

youtube.com

### Steps to Reproduce

1. Only uBlock Origin enable;
2. Restart Firefox;
3. Go to youtube
4. Play a video;

### Expected behavior

Go to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1852441

### Actual behavior

Go to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1852441

### uBO version

1.51.0

### Browser name and version

Firefox version 117

### Operating System and version

Distribution Gentoo

**Comment by mapx-** [comment]
install 1.52 from 
https://github.com/gorhill/uBlock/releases

**Comment by gorhill** [comment]
Such process crashes are not a uBO issue, it's a browser issue, which you properly reported.

**Comment by gorhill** [comment]
> gorill has forgotten to signed the xpi for the 1.52.0

I didn't forget anything, the extension will be signed by AMO once it pass review.

**Comment by awilum8** [comment]
> I didn't forget anything, the extension will be signed by AMO once it pass review.

I was hasty and didn't read the Firefox: Review pending line. My bad, sorry.

> Such process crashes are not a uBO issue, it's a browser issue, which you properly reported.

Is it Firefox or uBlock Origin, I don't know but the only thing I am sure is when the extension is enable this problem arise.

> install 1.52 from
https://github.com/gorhill/uBlock/releases

I have already try to install the version 1.52 from this link, but firefox refuses to install because it's not signed.
Firefox Xpi available:   uBlock0_1.52.0.firefox.xpi 

Like gorhill said:

> the extension will be signed by AMO once it pass review.

So, I will have to wait the signed xpi version 1.52.0

Best regards.

**Comment by gorhill** [comment]
> Is it Firefox or uBlock Origin

A process crash is Firefox. uBO is entirely written in JS, using browser APIs, and as such it's not supposed to crash the browser. If your browser crashes, then this must be investigated by browser devs using crash report.

**Comment by awilum8** [comment]
Tested on the latest Nightly (119.0a1/20230911154121 and Release (117.0/20230824132758) under Windows 10 x64 and Ubuntu 22.04 LTS with uBlock Origin 1.51.0.
There is no crashes while having uBlock Origin installed and enabled, while on YouTube playing a video.

Even with the official Firefox-117 from  https://ftp.mozilla.org/pub/firefox/releases => firefox-117.0.tar.bz2 for x86_64

Mine is a locally compiled firefox-117_x86_64, from Gentoo Distribution. So maybe a patch is the culprit.

I have filing a bug report to Gentoo: https://bugs.gentoo.org/914049

https://bugzilla.mozilla.org/show_bug.cgi?id=1852441 (Updated: Status: UNCONFIRMED → RESOLVED, Resolution: → INVALID)
