### ISSUE TITLE
[1.52.0] Squished lines in panel

### ISSUE THREAD

**Issue by yokoffing** [uBlockOrigin/uBlock-issues#2817]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The panel squeezes a bunch of lines together when trying to filter by request type. This seems to be a bug when compared to previous builds.

Not website related. Happens regardless of site.

Before
![before filter](https://github.com/uBlockOrigin/uBlock-issues/assets/11689349/fd2fbc0a-5ca7-4098-ba5b-abd858d6228e)

After
![after filter](https://github.com/uBlockOrigin/uBlock-issues/assets/11689349/0c0ef7dd-5a44-4c6a-8af7-111512b4d006)

### A specific URL where the issue occurs.

cnn.com

### Steps to Reproduce

With `filterAuthorMode` = `true`, I cannot filter by script, frame, etc.

### Expected behavior

No squished lines.

### Actual behavior

Squished lines.

### uBO version

1.52.0

### Browser name and version

Firefox/Chrome

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
> No squished lines.

Just remove the filter -- rows which do not match your filter are minimized.

**Comment by yokoffing** [comment]
I think I understand:

- Before, when a filter was enabled, we hid all the other lines and only showed what was relevant.
- In 1.52, when a filter is enabled, we show the squished lines and still only show relevant requests.

I can see a rationale for this kind of change. Sometimes I would forget that I enabled `frame` filter and would only see three requests in the UI on sites. Squished lines are a reminder that I have a filter enabled.

**Comment by gorhill** [comment]
> I didn't see this change in the release notes, so the UI jarred me.

It's the ["Add visual hint for filtered out rows in firewall pane"](https://github.com/gorhill/uBlock/commit/c74fc6460e) entry, which leads to <https://github.com/uBlockOrigin/uBlock-issues/discussions/2632>.

**Comment by yokoffing** [comment]
Thank you for the links!
