### ISSUE TITLE
:is() ceased working in 1.52.0

### ISSUE THREAD

**Issue by TheChief5055** [uBlockOrigin/uBlock-issues#2818]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Code that worked in older uBO versions:
`livejournal.com##:is(.b-leaf-username, .comment-poster-info, .recent-comments__user > .i-ljuser-type-P, [id^="ljcmt"] .i-ljuser-username, .contextualhover__title):has-text(/username1|username2|username3/):upward(:is(.b-leaf-full, .b-leaf-collapsed, .comment-wrap, .comment-wrap.partial, .contextualhover, .recent-comments__item)) :is(.b-leaf-controls, .b-leaf-article, .b-leaf-userpic, .b-leaf-subject, .b-leaf-meta, .b-leaf-actions, .comment-metadata, .comment-controls, .comment-text, .comment-menu, .comment-upic, .comment-head-in > h3, .contextualhover__userpic, [href*="thread"], .emdash, .recent-comments__meta, .recent-comments__subject, .recent-comments__text):remove()`

In 1.52.0 last :is() part does not work at all.

### A specific URL where the issue occurs.

https://bmpd.livejournal.com/4750767.html

### Steps to Reproduce

1. Fill desired usernames in regexp (/username1|username2|username3/)
2. Open any LJournal journal.

### Expected behavior

Rule must purge user post completely, leaving only username.

### Actual behavior

It does not work. Seems that `:is(.b-leaf-controls, .b-leaf-article, .b-leaf-userpic, .b-leaf-subject, .b-leaf-meta, .b-leaf-actions, .comment-metadata, .comment-controls, .comment-text, .comment-menu, .comment-upic, .comment-head-in > h3, .contextualhover__userpic, [href*="thread"], .emdash, .recent-comments__meta, .recent-comments__subject, .recent-comments__text)` part does not select anything.

### uBO version

1.52.0

### Browser name and version

Chrome x64 117.0.5938.63

### Operating System and version

Windows 10 x64

**Comment by gwarser** [comment]
Regressing bug: https://github.com/uBlockOrigin/uBlock-issues/issues/2778#issuecomment-1720024028

**Comment by gorhill** [comment]
> Seems that `:is(.b-leaf-controls, .b-leaf-article, .b-leaf-userpic, .b-leaf-subject, .b-leaf-meta, .b-leaf-actions, .comment-metadata, .comment-controls, .comment-text, .comment-menu, .comment-upic, .comment-head-in > h3, .contextualhover__userpic, [href*="thread"], .emdash, .recent-comments__meta, .recent-comments__subject, .recent-comments__text)` part does not select anything.

Works for me. The regression affects other cases, not this one.

**Comment by TheChief5055** [comment]
> Works for me. The regression affects other cases, not this one.

This code part itself works, but in the whole rule it does not.

PS: *:is fixes it! So it is the same regression.

**Comment by gorhill** [comment]
Even with `*:is` in the original filter:

    ##:is(.b-leaf-username, .comment-poster-info, .recent-comments__user > .i-ljuser-type-P, [id^="ljcmt"] .i-ljuser-username, .contextualhover__title):has-text(/username1|username2|username3/):upward(:is(.b-leaf-full, .b-leaf-collapsed, .comment-wrap, .comment-wrap.partial, .contextualhover, .recent-comments__item)) :is(.b-leaf-controls, .b-leaf-article, .b-leaf-userpic, .b-leaf-subject, .b-leaf-meta, .b-leaf-actions, .comment-metadata, .comment-controls, .comment-text, .comment-menu, .comment-upic, .comment-head-in > h3, .contextualhover__userpic, [href*="thread"], .emdash, .recent-comments__meta, .recent-comments__subject, .recent-comments__text)

I don't see any match in the picker.

**Comment by TheChief5055** [comment]
> I don't see any match in the picker.

Fill :has-text(/username1|username2|username3/) with any username from page. For ex;  :has-text(/antisemit_ru/)
