### ISSUE TITLE
Please bring back support for Chromium 49

### ISSUE THREAD

**Issue by palikacska** [uBlockOrigin/uBlock-issues#282]
I recently noticed that uBlock Origin minimum browser version has been raised up to 51.0.

A lot of Windows XP users (including me) rely on your malware block lists. Now they are unable to install your extension from Chrome Web Store because Chromium 49 is the last version available for Windows XP.

Please lower the compatibility version to allow Windows XP users to continue surfing the web safe and secure by using your extensions to block abusive websies.

**Comment by uBlock-user** [comment]
Not possible see - https://github.com/uBlockOrigin/uBlock-issues/issues/84#issuecomment-416002317

**Comment by palikacska** [comment]
There are bunch of alternative ways in javascript to implement that for loop.

Why exactly do you need that syntax?

And why didn't you need it before? Why could uBlock Origin work like a charm under Chromium 49 for years without it?

@gorhill Please don't tell me that you are going to leave alone millions of XP users just because you want to use a different JS syntax.

**Comment by uBlock-user** [comment]
> Why are you marking this as an invalid issue?

Not an issue with the uBlock, this is more a of question of why did gorhil do this and that. Issues with uBlock are considered "issues", asking questions for a move made by the dev is not an issue but rather an inquiry at best.

**Comment by palikacska** [comment]
@uBlock-user Is there an official place of these inquiries?

**Comment by uBlock-user** [comment]
Not exactly. I closed this issue as I already answered the why part. If gorhill feels like opening it and addressing he may.

**Comment by palikacska** [comment]
@uBlock-user Great. Thanks.

As follows.

Dear @gorhill ,

There are two problems with raising compatibility levels to above Chromium 49.

1. The last version of Chrome available for Windows XP is Chrome/Chromium 49.
2. Windows XP is still used by millions of people. At least twice as much than of Linux, according to NetMarketShare.

So that's not just a simple version number. It affects **millions of people**. And especially that kind of people who need the capabilities of your great blocking extension the most.

On Windows XP there are a limited set of browsers available. One of these is the Firefox branch, more exactly the forks that have been created from older versions of Firefox and the last versions of Firefox ESR that used to support XP. These are [Centaury](https://github.com/Feodor2/Mypal/releases/tag/Centaury) (built from Basilisk), [Mypal](https://github.com/Feodor2/Mypal) (built from Pale Moon) and [New Moon](https://msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/) (built from Pale Moon). On these browsers you must use an older version of uBlock, around version **1.13**. Since this is Firefox codebase, all of them are really slow because the unoptimized and bloated engine Firefox codebase generally comes with. So you know it's not that good on an old computer running XP.

There is [Advanced Chrome](http://browser.taokaizen.com/) that has a build above version 51.0 but does not support hardware acceleration (yes it's possible under XP) and is not a real stable alternative because it crashes sometimes. I had the chance to try it and I wouldn't rely on it for everyday use.

There is Chromium 49 which is full-featured, supports all video codecs but doesn't support GPU hardware acceleration under XP. It's much faster than any Firefox fork mentioned above. It's preferred because it's more easily obtainable than official Chrome 49 which needs a little more Googling among broken links and archives of older Chrome versions. It also doesn't display the annoying notification of Google's hypocritical warning message for upgrading to a different OS (billion dollar Google would have the resources to support XP but they decided not to and left alone millions of people). Chromium 49 is **affected** by your version number change.

There is Chrome 49 which is full-featured, supports all video codecs and GPU hardware acceleration under XP. It's the **fastest alternative**. Way faster than any version of Firefox, a bit faster and much more stable than Advanced Chrome, even if it's an older version. Chrome 49 is **affected** by your version number change.

Speed, efficiency, the key principles uBlock Origin has been built upon are the **most needed by users of older computers with less resources**. People stick to XP because they would need a new computer for Windows 7 or 10 due to the absence of drivers. Even 2nd generation Intels are unsupported on Windows 10, even though the i5s are nearly as powerful as today's Intel i3s. Desktop Linuxes wouldn't mean a real alternative either as as GTK3 and Qt5 are heavy weight frameworks and all applications are built around them. So the least bad alternative is to keep XP which is still good for most of the tasks performed on a computer. There are two critical aspects out there why XP users need uBlock Origin the most.

1. To filter out all unnecessary advertising content
2. To block all malicious sites XP computers are more vulnerable to.

That's why it would be important to keep up the support for Chromium 49 somehow. Either by using a syntax different from for node of nodes, or creating a legacy branch of the old code. It would be great if XP users could install uBlock Origin from the Chrome Web Store again. Please help us make that possible.

**Comment by gorhill** [comment]
Please find the last version which is compatible with Chromium 49 and I will document it for those who keeps wanting to use Chromium 49. Keep in mind that to keep uBO compatible with old versions of any browsers is a burden requiring time and efforts, which are limited resources.

**Comment by ArchangeGabriel** [comment]
@palikacska Have you actually tried running a Linux desktop? GTK3 and QT5 are definitively not as heavy as you seem to think, and what is generally resources consuming is Desktop Environment. But they are lightweight ones (LXQT, XFCE, etc.).

**Comment by palikacska** [comment]
Thanks.

For Chrome 49 it won't update after uBlock Origin **v1.16.18**. For Chromium 49 it's the same.

It would be good if Chrome 49 users could install it from the Web Store. I don't know how Google handles compatibility at this level or if it's possible from Web Store's side to send an older version to those who visit it with an older browser. If it's not possible, it would be great if they could click to a different extension called **uBlock Legacy** (or something like that) instead of **uBlock Origin**. If I go to the Web Store using a Chrome 49 and search for uBlock, all I see is uBlock Origin Extra. So Google filters out incompatible extensions. That's why it would be good to have an extension specifically for legacy Chromes. Wouldn't a reimplementation of that for loop help (using a classic for loop instead of the one with the "of" operator)?

**Comment by ArchangeGabriel** [comment]
I’m really surprised that you have Arch slower than Windows XP… Anyway.

You are free to maintain a fork of uBlock where you would keep compatibility with Chromium 49 (btw, Chrome 49 is mostly the same thing, I doubt any extension not relying on Google or DRM specifics would work on one but not the other). As you said yourself, Firefox still exists on XP thanks to forks. You’re welcome to do the same thing for uBlock I guess.

**Comment by palikacska** [comment]
> I’m really surprised that you have Arch slower than Windows XP… Anyway.
It's not Arch that is slower. It's all the new desktop environments and applications written in bloated GTK3 and bloated Qt5. I'm also talking about LXQt. You have to wait 3-4 seconds for a configuration window to appear. Which is < 1 sec on Windows XP for the Control Panel to launch. Xfce is being ported to GTK3 for some idiotic reason but half of it is still GTK2 so you have one half of your DE in a different framework if you use Xfce. Linux command line is fine. Until you launch a desktop environment. Yes, I have configured my graphics driver accordingly. It's not the problem. The problem is that developers of GTK3 and Qt5 and the apps based on them all have high-end computers with the latest generation Intel and 32 GB RAM. So they will not feel at all if they write something that's bloated. I have an old Core 2 Duo laptop which is not that performant so you will feel it more when you're facing bloated applications.

**Comment by jspenguin2017** [comment]
> using a classic for loop instead of the one with the "of" operator

I guess that would work. You want to fork? I would imagine that the maintenance work wouldn't be too bad in the near future. You can also just use v1.16.18, or wait for someone else to fork. 

> The problem is that developers of GTK3 and Qt5 and the apps based on them all have high-end computers with the latest generation Intel and 32 GB RAM. 

If you are talking about Qt Creator then yes, I have 6th gen i5 and 16 GB RAM and it takes forever to compile. But if you are talking about apps that are built in release mode, then no. Qt5 is blazing fast, I have a 4 GB RAM tablet and my Qt5 app launches in ~0.1 second. 

> I have an old Core 2 Duo laptop which is not that performant

I guess it's time to upgrade? Your laptop is around 10 years old now, right? You can get a decent Chromebook for under $300.

**Comment by uBlock-user** [comment]
> It would be good if Chrome 49 users could install it from the Web Store. 

Not possible Web Store only serves the latest version of the extension. Download the version you mentioned from github and install the extension by unpacking it and loading it via developer mode.

**Comment by gorhill** [comment]
I am using Linux Mint 18.3/Mate on a 12+ year-old laptop and I can use the latest Chromium fine (on top of not having to worry about serious security issues) -- I just need to keep the number of apps and tabs in the browser down according to how much of the 1GB of memory is filled (I keep a mem monitor in task bar to deal with this).

Bottom line is, if people want to burden themselves with using an OS from another era, then they should also bear the burden of dealing with the consequences.
