### ISSUE TITLE
XHR hook with json-prune-xhr-response breaks if accessed early.

### ISSUE THREAD

**Issue by ephemeralViolette** [uBlockOrigin/uBlock-issues#2822]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The new `json-prune-xhr-response` scriptlet (in uBO v1.52.0) caches the response data of the XHR object upon the first access of that data, which optimises access of the data, especially if it is modified. 

It does not account for a change in the original data after the initial access, which can occur if the data is still loading. Some legitimate users of this behaviour in XHR (such as [youtube/spfjs](//github.com/youtube/spfjs)) may access the data while it is still downloading, which breaks the XHR hook used by this scriptlet; if an early version is accessed, then even when the download is complete, page scripts will still read the early version as given by the scriptlet.

As an example, I will discuss YouTube's old SPF.js single-page-application navigation framework, which attempts to parse JSON while the data is still downloading (i.e. `readyState == 3`, "LOADING"). In the case of SPF, it attempts to parse the complete data once the `readyState` changes to 4 ("DONE"), but since the XHR hook caches the first accessed value, which is most likely incomplete, the JSON data will be incomplete, JSON.parse() will throw an exception, and the script will refresh the page as a result.

[I have fixed this issue in a personal fork by invalidating the cache if the size of the original data changes, which you can see here.](https://github.com/ephemeralViolette/uBlock-fix-json-prune-xhr-response/commit/ce959164bb3571dd7f9c8a40236c20dae3775153)

### A specific URL where the issue occurs.

https://youtube.github.io/spfjs/

### Steps to Reproduce

1. Before visiting the example URL, add a filter to inject the scriptlet, such as `youtube.github.io##+js(json-prune-xhr-response)`.
2. Visit the example URL.
3. Click on any link of the page to begin navigation.
4. Pay attention to the site's favicon in the browser bar; it should not change to the browser's loading icon. Alternatively, pay attention to network tab of the developer tools; as a JSON parse error will occur due to the accessed data being incomplete, SPF will hard-refresh the page, and the developer tools should reset.
5. Rinse and repeat; you may get lucky and encounter a rare chance it works correctly.

### Expected behavior

In the example site, the page should smoothly update contents without causing a browser refresh. Incomplete responses should be accounted for in the XHR hook of the scriptlet in order to avoid similar issues.

### Actual behavior

The example site will most likely encounter an error in most cases and cause a hard refresh, rather than a smooth transition. Responses will be cached on their first access, regardless of being incomplete, and subsequent access will refer to the incomplete cached version rather than the complete version which exists in the parent XHR object.

### uBO version

uBlock Origin 1.52.0

### Browser name and version

Firefox 115.1.0esr

### Operating System and version

Windows NT 10.0.19042.2364

**Comment by gorhill** [comment]
I merged in your fix: <https://github.com/gorhill/uBlock/commit/ce959164bb3571dd7f9c8a40236c20dae3775153>, thanks.
