### ISSUE TITLE
Maybe dont Push every minor/development version to chrome store

### ISSUE THREAD

**Issue by nanderer** [uBlockOrigin/uBlock-issues#2827]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

once upon a time there was a post originating from our kingdom about wasted space because of tons of old ublock addons on the disk in the data of chromium, it still looks like this:

![grafik](https://github.com/uBlockOrigin/uBlock-issues/assets/45161625/872dd76c-5e5c-4d04-aa33-e6f29ef7d1a7)

in fact right now a heavy cleaning operation is on the go:

![grafik](https://github.com/uBlockOrigin/uBlock-issues/assets/45161625/2c7116cf-29e9-44f3-9007-374134f73bad)

its taking its time and it needs a archmage to operate this deep in such a system.

high priest of faith of ublock origin that a higher might. the all mighty but non-servile google is responsible for cleaning up.

So this is a humble request to mitigate this until google may will be fixing this in aeons to come by not pushing any minor version to the store, only push them after 30days or so or if it is a major version, we would really appreciate it

the eternal gratitude of our adepts and disciples will be sure for you!

maybe another branch for those who need all the latest stuff asap, but the regular user would prefer a stable and clean system i guess

### A specific URL where the issue occurs.

all

### Steps to Reproduce

1. install the addon
2. use the system 
3. check the space requiered after updates
4. see it is getting more and more and more

### Expected behavior

dont wasting of space but its googles doing

### Actual behavior

google is unable to clean up and doing it on our own is tiresome 

### uBO version

all

### Browser name and version

chrome/chromium/iron/other chromium forks

### Operating System and version

windows nt based systems

Edit: typo

**Comment by nanderer** [comment]
(related issue: https://github.com/uBlockOrigin/uBlock-issues/issues/2399 )

**Comment by stephenhawk8054** [comment]
Did you install developer build of uBO?

**Comment by gorhill** [comment]
Your browser is supposed to remove old versions, this is not a uBO issue. You will have to investigate on your side why this is happening. Asking that I do not published a dev build of uBO is not a solution to your issue.
