### ISSUE TITLE
No context menu entry for data:* iframes (banners)

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#283]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

"Block element" right click menu entry is missing for iframe banners created from `data:*` URL

![screenshot_20181023_032452](https://user-images.githubusercontent.com/886325/47329477-2d0acb80-d675-11e8-9586-e98f6fb3c8d9.png)

### A specific URL where the issue occurs

http://funfunfun.se/2018/10/74317_Mat_En_lunch_av_det_dyrare_slaget_i_Tokyo.woff?play=1

### Steps to Reproduce

1. Open page
2. Right click banner on top

### Expected behavior:

Visible "Block element" entry

### Actual behavior:

"Block element" menu entry is missing

### Your environment

* uBlock Origin version: 1.17.0, 1.17.1b2
* Browser Name and version: Firefox stable, Nightly, Chromium 69.0.3497.81
* Operating System and version: Mint 18.3

### Notes

Can be fixed by adding `, 'data:*'` to this array: https://github.com/gorhill/uBlock/blob/8b1c39507e138e7a3d4f960923f194f7e730a9c6/src/js/contextmenu.js#L90

Doc:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#Parameters
https://developer.chrome.com/extensions/contextMenus

**Comment by uBlock-user** [comment]
Is it applicable to `blob:` urls too ?

**Comment by gwarser** [comment]
`about:blank` must be fixed too. `documentUrlPatterns` can be set to `['<all_urls>']` or omitted.

Hmmm looks like only http/https is safe - `data:*` throws in Firefox 62, but works in 63. `about:blank` throws in all channels. Even if I manage to add entry to `about:blank` frames by commenting out `documentUrlPatterns`, clicking in menu does nothing or select previous element.

**Comment by gwarser** [comment]
Good test page https://canvasblocker.kkapsner.de/test/dataUrlTest.php

**Comment by gorhill** [comment]
> `about:blank` throws in all channels

You have a URL with an `about:blank` iframe?

**Comment by uBlock-user** [comment]
https://jsfiddle.net/VovanR/5Lmc2b5w/

**Comment by uBlock-user** [comment]
I see that's an example of nested iframes.

How about https://jsfiddle.net/5Lmc2b5w/43/ ?

**Comment by uBlock-user** [comment]
So this [jsfiddle](https://jsfiddle.net/5Lmc2b5w/53/) wouldn't work either right ?

**Comment by gwarser** [comment]
https://fiddle.jshell.net/5Lmc2b5w/53/show/

**Comment by gorhill** [comment]
@gwarser same issue, the `about:blank` frame sites in another iframe. What I am trying to reproduce here is your "`about:blank` throws in all channels". I ended up having to create a local case for this and I do not experience a throw.

**Comment by gwarser** [comment]
Adding `about:blank` to `documentUrlPatterns` in `contextmenu.js` throws when addon is started.

>[Exception... "Illegal value" nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)" location: "JS frame :: chrome://browser/content/parent/ext-menus.js :: setProps :: line 563" data: no]

**Comment by gorhill** [comment]
> Adding `about:blank` to `documentUrlPatterns`

Ok that won't be an issue then, I had just removed the filtering of URLs to let uBO deal with whatever is thrown at it. I still needed to adjust the code to deal with `about:blank`, as `src=""` will also be reported as `about:blank`.

**Comment by uBlock-user** [comment]
> About blank iframe - when I go to https://jsfiddle.net/5Lmc2b5w/53/ then right click in bottom-right "frame", This Frame, Show Only This Frame - I get document with only one iframe.

Yes, I removed the nested frame and created that jsfiddle in https://github.com/uBlockOrigin/uBlock-issues/issues/283#issuecomment-436257797

**Comment by gwarser** [comment]
Small glitch: 
- load https://jsfiddle.net/5Lmc2b5w/53/
- click in top-left "HTML" frame
- right click in bottom-right frame
- select "Block element"

Top-left frame is selected by picker.

**Comment by uBlock-user** [comment]
Right clicking directly on bottom right frame doesn't trigger the picker to open, another glitch ?

**Comment by gwarser** [comment]
iframe inside iframe :/


Selector for `blob` iframes does not include tag name, but includes randomly changing URL.
Test https://canvasblocker.kkapsner.de/test/dataUrlTest.php
`kkapsner.de##+js(remove-attr.js, id)` is needed to get rid of IDs.
Example: `##[src="blob:https://canvasblocker.kkapsner.de/67eb44cc-1177-450b-b7b4-550226849b1d"]`

**Comment by gorhill** [comment]
Good point, uBO should remove the (by design) ariable part from blob URLs.
