### ISSUE TITLE
Redirecting doesn't work when script has integrity and crossorigin attributes

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2830]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A real world case for: https://github.com/gorhill/uBlock/issues/1643#issuecomment-220587224

`<script src="https://cdnjs.cloudflare.com/ajax/libs/fingerprintjs2/2.1.0/fingerprint2.js" integrity="sha256-RBGR32F9JdIr/VzBmTp/iQ73Ibl6woprrQ4xj5Rr+mM=" crossorigin="anonymous"></script>`

1) Add this to counter `/fingerprint2.js` in EP:
```adb
/fingerprint2.js$script,3p,redirect-rule=fingerprint2.js
```

2) Open the console and go to:
`https://sproutgigs.com/login.php`

3) See in console:
`None of the “sha256” hashes in the integrity attribute match the content of the subresource. The computed hash is “[...]”.`

And if you try to login (random email and password):
`Uncaught ReferenceError: Fingerprint2 is not defined`

But these work:
```adb
||hotjar.com/c/hotjar-$script,3p,domain=sproutgigs.com,redirect-rule=fingerprint2.js

sproutgigs.com##+js(fingerprint2)
```

### A specific URL where the issue occurs.

`https://sproutgigs.com/login.php`

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.52.3b0 dev

### Browser name and version

Firefox

### Operating System and version

.

**Comment by krystian3w** [comment]
maybe name is too short test with `*`:

```adb
*/fingerprint2.js$script,3p,redirect-rule=fingerprint2.js
```

or

```adb
/fingerprint2.js*$script,3p,redirect-rule=fingerprint2.js
```

For the time being, I would pour over marking both stars as meaningless by the linter.

A very long time ago, short names were problematic and files were not network-locked.
```

**Comment by gorhill** [comment]
Not something that can be fixed.
