### ISSUE TITLE
HTML Filter doesn't work on service worker requests

### ISSUE THREAD

**Issue by gunir** [uBlockOrigin/uBlock-issues#2833]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

HTML Filter is not working as expected, I used a fresh profile, fresh uBlock install, check my reproduce steps.

### A specific URL where the issue occurs.

https://voz.vn/

### Steps to Reproduce

- Add this `voz.vn##^.p-body-sidebar` to My Filter
- Go to https://voz.vn/
- Check the right sidebar
- F5 again
- The sidebar appear again even if you keep pressing F5:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/e8007b76-d091-4173-be92-30228c18d61f)
- Now press Ctrl+F5, it disappears again:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/bfddec04-3643-4f0c-825f-140e08a26ce9)

I've recorded a video, please check it: https://streamable.com/ek1var

### Expected behavior

The right sidebar should always get cleaned.

The right sidebar contains many iframes, that's why it's better to remove with HTML Filter `##^` than hiding with Element Hiding `##`

I've recorded a video, please check it: https://streamable.com/ek1var

### Actual behavior

The right sidebar only disappear if I Ctrl+F5, which is pointless because it's a hard refresh, but it shows up again if I use F5.

I've recorded a video, please check it: https://streamable.com/ek1var

### uBO version

1.52.0

### Browser name and version

Firefox ESR 115

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
Try:

```
||voz.vn$csp=worker-src 'none'
```

and unregister service worker from `about:serviceworkers`.

**Comment by gunir** [comment]
> Try:
> 
> ```
> ||voz.vn$csp=worker-src 'none'
> ```
> 
> and unregister service worker from `about:serviceworkers`.

Thank you, it worked! 

Test video: https://streamable.com/o3ly9l

Should we have a workaround for this issue ? 

Header Editor also has this HTML Filtering capability but it doesn't have this issue, it can still modify above webpage even with that serviceworker running.

**Comment by stephenhawk8054** [comment]
@gwarser I think we need this https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData#permissions ?

```
From Firefox 95, to use this API to intercept requests related to the loading of service worker scripts, the "webRequestFilterResponse.serviceWorkerScript" permission is also required.
```

**Comment by gwarser** [comment]
@stephenhawk8054 uBO filters only main HTML document, does not touch any script or service worker.

**Comment by gwarser** [comment]
Adding these permissions does not help. Something more need to be done to filter these requests.

**Comment by gunir** [comment]
> Adding these permissions [to manifest] does not help. Something more need to be done to filter these requests.

I have a working code for Header Editor addon, I don't know why but it DOES work without manually changing CSP "worker-src", this enhancement will make using HTML Filter more bearable.

This is my code:

Name: VozClean
Modify response body
Regular Expression
`^.*?voz.vn/$`
Custom function: `return val.replace(/<div class="p-body-sidebar">[\s\S]*?<\/footer>/, '<!-- CLEANED -->');`

Screenshot:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/a4448edc-ae43-4375-8986-75b5156db9f2)

**Comment by gunir** [comment]
Should we mark this as enhancement and reopen ? It's no longer an issue but improvement is nice.

**Comment by krystian3w** [comment]
A little looks as AdGuard replace, then filter will works only after publish new add-on.

https://adguard.com/kb/general/ad-filtering/create-own-filters/#replace-modifier

I haven't checked if the free AdGuard add-on can handle it and how old Firefox is then supported.

**Comment by gunir** [comment]
> _Unfortunately, AdGuard and their HTML Filtering cannot remove the element without damaging the entire DOM of the website._

This is very bad imo, but they will fix for sure, they're professional after all.

But well, talking about uBO's HTML Filtering, I don't mind removing worker src manually but it's such a hassle for end-users, HTML Filtering is very beneficial, its actually improve page loading speed by skipping network connections of removed contents entirely.

In this tested, you can see removing vs hiding that sidebar saved a lot of bandwidth:
Removing (116 total requests):
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/c6a74e75-414b-4c99-956d-beea71fe2aeb)

Hiding (141 total requests):
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/e1181921-f564-4d4d-b9e6-10df04f3d431)

HTML Filtering is a bit advanced, but I believe it worth our cares to enhance it further to make it more user-friendly.

My 2 cents.

**Comment by gunir** [comment]
> I would suggest checking if the add-on "Header Editor" is actually working with action "VozClean" before browser parse HTML.

It does, if you want proof, take this filter: https://github.com/uBlockOrigin/uBlock-issues/issues/2833#issuecomment-1732592498

Look at this result pic and check in view-source:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/134402102/c2374213-eb98-4ab5-94c9-b2af90d4c1a8)

Source: https://voz.vn/t/tong-hop-nhung-addon-chat-cho-firefox-pc-mobile.682181/post-27877026

**Comment by krystian3w** [comment]
It looks uBo replace https://github.com/gorhill/uBlock/commit/7c3e060c01 have same problem. In AdGuard replace worked fine 2 monts ago without kill service worker.

**Comment by gorhill** [comment]
I think this is fixable by giving precedence to `content-type` when evaluating whether to html-filter a response.

**Comment by gunir** [comment]
> I think this is fixable by giving precedence to `content-type` when evaluating whether to html-filter a response.

Beautiful and thank you, the recent `replace` filter loves this fix!
