### ISSUE TITLE
Greek AdBlock Filter mirror issue

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [uBlockOrigin/uBlock-issues#2837]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Current Greek AdBlock Filter mirror:

https://www.void.gr/kargig/void-gr-filters.txt

is out of date. Please, replace it with:

https://raw.githubusercontent.com/kargig/greek-adblockplus-filter/master/void-gr-filters.txt

### A specific URL where the issue occurs.

https://www.enikos.gr/society/peiraias-tsantistika-itan-stigmiaio-ta-prota-logia-tou-68chronou-pou-dolofonise-ypallilo-parkingk-vinteo-ntokoumento/2028873/

### Steps to Reproduce

1. Enable Greek AdBlock Filter
2. Compare the installed mirror content with the above suggested one.

### Expected behavior

Greek AdBlock Filter remains up to date.

### Actual behavior

Greek AdBlock Filter doesn’t update regularly.

### Configuration

[το-ublock-αντίγραφο-ασφαλείας-μου_2023-09-25_16.07.35.txt](https://github.com/uBlockOrigin/uBlock-issues/files/12715375/-ublock-.-.-._2023-09-25_16.07.35.txt)

**Comment by gwarser** [comment]
Two last commits are not synced.

@kargig ?

**Comment by kargig** [comment]
It's in sync now, thanks

**Comment by gwarser** [comment]
Ah, it's probably a cache issue. It's fine now.
