### ISSUE TITLE
When installing under firefox (selenium) the logs say incorrectly signed

### ISSUE THREAD

**Issue by AndreSteenbergen** [uBlockOrigin/uBlock-issues#284]
### Description

Following warnings are found in the marionette logs:

1540289717290   addons.xpi-utils        WARN    Add-on uBlock0@raymondhill.net is not correctly signed.
1540289717290   addons.xpi-utils        WARN    Add-on uBlock0@raymondhill.net is not correctly signed.
1540289717290   addons.xpi-utils        WARN    Add-on uBlock0@raymondhill.net is not correctly signed.

### Your environment

* uBlock Origin version: 3.17.2
* Browser Name and version: Firefox 61
* Operating System and version: Linux Ubuntu 18.04

**Comment by uBlock-user** [comment]
Someone with selenium will need to reproduce.

**Comment by gorhill** [comment]
You installed from where?

**Comment by AndreSteenbergen** [comment]
From the releases page: https://github.com/gorhill/uBlock/releases I downloaded the https://github.com/gorhill/uBlock/releases/download/1.17.2/uBlock0.firefox.xpi XPI file. When I download https://github.com/gorhill/uBlock/releases/download/1.17.1b2/uBlock0.firefox.signed.xpi the warning is not in the logs.

**Comment by uBlock-user** [comment]
That's because firefox.xpi is not signed. Use the signed one as instructed on the releases page.

**Comment by AndreSteenbergen** [comment]
> Use the signed one as instructed on the releases page.

And where can that signed xpi be found (as a download)

**Comment by gorhill** [comment]
The signed release versions are all hosted on AMO, it's not possible to signed versions on both AMO and self-hosted, it has to be one or the other. Download from AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/>.

**Comment by AndreSteenbergen** [comment]
Thanks found it: https://addons.mozilla.org/firefox/downloads/file/1114441/ublock_origin-1.17.2-an+fx.xpi

**Comment by uBlock-user** [comment]
Stable signed builds are only available on AMO, while the dev signed are only on Github, so choose one.
