### ISSUE TITLE
Another Reporting form request.

### ISSUE THREAD

**Issue by Green-Leaves500** [uBlockOrigin/uBlock-issues#2847]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Sir, introduce another reporting form for an individual who does not want to create/login a github account for reporting a web clutter. Another well known content blocker extension also has a secondary form for reporting and I also notice that an individual using that form more cause it is good for privacy of an individual.

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

uBO latest

### Browser name and version

Brave Browser

### Operating System and version

Windows 10

**Comment by stephenhawk8054** [comment]
> another reporting form

Where?

**Comment by stephenhawk8054** [comment]
Where do you want the issue to be reported?

**Comment by stephenhawk8054** [comment]
The form does not matter. They are just texts. The question is, where would those forms be transferred to.

**Comment by stephenhawk8054** [comment]
> on github of ublock page

And what will transfer those to github?

**Comment by mapx-** [comment]
you would want to report your issue generically (using some uBO account) but we have to interact with the user (without an account), so it does not add any value to the reporting process

**Comment by stephenhawk8054** [comment]
@Green-Leaves500 They are a company, and they have their servers to send your information to github. uBO is a FOSS project, it does not have any home server not it sends any data from your machine to outside.

**Comment by stephenhawk8054** [comment]
> It would be great if you introduce it. i think will be good for reporter privacy.

And who will pay for the server, and who will be responsible for your data.

**Comment by stephenhawk8054** [comment]
Just FYI that all those above are always uBO Privacy Policy: https://github.com/gorhill/uBlock/wiki/Privacy-policy including finance and server/analytics aspects.

**Comment by garry-ut99** [comment]
- what the OP requests is such a form: 
   - > https://github.com/AdguardTeam/AdguardFilters#report-issues : To submit a report, please use this [reporting tool](https://agrd.io/report).

- also no need to create a separate issue for another request related to the same feature, can continue discussion in already existing thread :
   - https://github.com/uBlockOrigin/uBlock-issues/issues/1541

**Comment by gorhill** [comment]
> what the OP requested is such a form:
> 
> https://github.com/AdguardTeam/AdguardFilters#report-issues : To submit a report, please use this [reporting tool](https://agrd.io/report).

If so, it should be possible to create such form in `ublockorigin/github.io`.

**Comment by iam-py-test** [comment]
I _think_ AdGuard sends all the data to their servers and then has the bot open the issue, right?
Thanks

**Comment by garry-ut99** [comment]
I can add that such forms already exist not only for AdGuard repo, but also for:

_Official Polish Filters for AdBlock, uBlock Origin & AdGuard :_
- (tracker) https://github.com/MajkiIT/polish-ads-filter/issues ==>
(www) https://www.certyficate.it/  ==>
(**form**) https://www.certyficate.it/zglos-reklame/

_Polish Annoyance Filters :_
- (tracker) https://github.com/FiltersHeroes/PolishAnnoyanceFilters/issues ==>
(www) https://polishannoyancefilters.netlify.app/  ==>
(**form**) https://polishannoyancefilters.netlify.app/issues/

_Polish KAD Filters (Badware)_
- (tracker) https://github.com/FiltersHeroes/KAD/issues ==>
   (www + **form**) https://kadantiscam.netlify.app/

<hr>

Some links about www & bots on github :
- https://docs.github.com/en/pages
- https://github.com/features/actions 
- https://docs.github.com/en/rest
- https://www.geeksforgeeks.org/making-a-github-bot/

**Comment by krystian3w** [comment]
These no longer works `https://www.certyficate.it/zglos-reklame/` and MajkiIT disabled/break purposely/knowingly/specially/deliberately.

**Comment by gorhill** [comment]
We can't, this would require to setup a server to proxy the form to github.

I erred above when I said:

> If so, it should be possible to create such form in `ublockorigin.github.io`

If course, if the goal is to proxy to avoid logging into github, what I said doesn't work, this would require to share a secret token on a public site at `ublockorigin.github.io`.
