### ISSUE TITLE
Consider removing "FIN: Finnish Addition to Easylist" -filterlist from uBo assets.json

### ISSUE THREAD

**Issue by msrn** [uBlockOrigin/uBlock-issues#285]
Was redirected to here from https://github.com/uBlockOrigin/uAssets/issues/3780

### URL(s) where the issue occurs

superliitto.fi, sak.fi, akt.fi, selry.fi, akava.fi, oaj.fi, stthl.fi, proliitto.fi, pam.fi, sahkoliitto.fi
### Describe the issue

There are currently happening several political strikes in Finland, where unions are taking their stance against the goverment. 
https://yle.fi/uutiset/osasto/news/security_guard_3-day_strike_to_start_on_wednesday/10469154

Few days ago the maintainer of FIN: Finnish Addition to Easylist -list, called Adblocker for Finland. Decided to block several union websites to make political statement about these strikes. 

Direct link to the list - https://adb.juvander.net/Finland_adb.txt
Archive.is -version - https://archive.is/1WYkz

I really think filter lists aren't suitable enviroment to make political statements and the maintainer is clearly abusing his power with actions like these. Thus please consider removing this filterlist from uBo's assets.json

### Screenshot(s)

[Screenshot of blocking the website pam.fi](https://i.imgur.com/aK37Vh9.png)
[Screenshot of the filters](https://i.imgur.com/9zHcfPB.png)
Rough ranslation: Statement about the union strikes. Will be removed after the strikes.
[Screenshot of FB post made by the maintainer](https://i.imgur.com/XCMwkm2.png)
Rough translation: As an objection to actions of trade unions.The finnish adblocking list now block sites of those unions which are joining the strike. Not all sites are there, but more are coming. They will removed after the unions start to respect the goverment again by ending these political strikes.

### Versions

- Browser/version: Firefox 63
- uBlock Origin version: uBlock Origin v1.17.2

### Notes
[Wikipedia page about the Central Organisation of Finnish Trade Unions](https://en.wikipedia.org/wiki/Central_Organisation_of_Finnish_Trade_Unions)

[Strike in the security guarding sector to go ahead – mediation ended without any settlement proposal . PAM.fi](https://www.pam.fi/en/news/notice/2018/10/strike-in-the-security-guarding-sector-to-go-ahead-mediation-ended-without-any-settlement-proposal.html)

**Comment by TheNikomo** [comment]
I was just about to submit an issue for this, but decided to recheck issues before hitting submit.

If the filter isn't at least removed from assets.json, there should at the very least be a disclaimer next to it, warning users that not only will it block advertisements, but it will cause issues with visiting the websites of various worker's unions.

**Comment by gorhill** [comment]
Found in the FIN filter list:

    ! Kannanotto liittojen lakkoiluun
    ! Nämä poistuvat kun lakot loppuu
    tehy.fi
    ##a[href*="tehy.fi"]
    superliitto.fi
    ##a[href*="superliitto.fi"]
    sak.fi
    ##a[href*="sak.fi"]
    akt.fi
    ##a[href*="akt.fi"]
    selry.fi
    ##a[href*="selry.fi"]
    akava.fi
    ##a[href*="akava.fi"]
    oaj.fi
    ##a[href*="oaj.fi"]
    stthl.fi
    ##a[href*="stthl.fi"]
    proliitto.fi
    ##a[href*="proliitto.fi"]
    pam.fi
    ##a[href*="pam.fi"]
    sahkoliitto.fi
    ##a[href*="sahkoliitto.fi"]

Google Translate:

> A stance on alliance strikes
> These will disappear as the strikes run out

A filter list is not to be used to express a political stance, unless it is made explicit and obvious in the list s primary purpose. Otherwise I consider this a breach of trust.

**Comment by LemonAndroid** [comment]
I will never use ublock again, fuck you.

**Comment by LemonAndroid** [comment]
Whose fault is it then?

**Comment by TheNikomo** [comment]
@LemonAndroid The original maintainer of the filter is Ilpo Juvander - there was no way for maintainers of uBlock Origin and other software to know that he would end up doing this.

**Comment by uBlock-user** [comment]
Continue your verbal wrestle over reddit.
