### ISSUE TITLE
Setting uBO policies in Chrome on Linux doesn't appear to work as described in the documentation

### ISSUE THREAD

**Issue by jbillingredhat** [uBlockOrigin/uBlock-issues#2850]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am attempting to set up a default extension policy for Google Chrome on Linux, so that it installs uBlock Origin and configures some settings, but I'm having issues getting it to even set the basic settings. I've managed to use the "adminSettings" for a Firefox policy file, and it works. Here's a very slimmed down policy file:

```
{
  "ExtensionSettings": {
    "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
      "installation_mode": "normal_installed",
      "update_url": "https://clients2.google.com/service/update2/crx"
    }
  },
  "3rdparty": {
    "extensions": {
    "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
      "adminSettings": "{\"userSettings\":{\"colorBlindFriendly\":true}}"
      }
    }
  }
}
```
If I launch a fresh Chrome browser, I don't see the Color-Blind friendly setting checked.  But if I go to chrome://policy, I see that the Policy name and value are set.
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/95879506/a705e588-3fb2-4a22-ab19-be433eee26ac)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/95879506/50002e77-352c-430b-8c38-23aecc300fb3)

### A specific URL where the issue occurs.

http://people.redhat.com/jbilling/

### Steps to Reproduce

1. Copy the policy file above into /etc/opt/chrome/policies/managed/policy.json
2. Create a new user or a fresh new profile
3. Launch chrome

### Expected behavior

The setting should be read from the policy

### Actual behavior

There is no change to the settings.

### uBO version

uBlock Origin 1.52.2

### Browser name and version

Google Chrome Version 117.0.5938.132 (Official Build) (64-bit)

### Operating System and version

Fedora 38

**Comment by gorhill** [comment]
The policy should take effect after you restart uBO a second time after a policy is set or modified.

**Comment by gwarser** [comment]
Works for me on first launch.

- install Chrome
- launch 
- close
- save policy file
- launch - it works
- create new profile - all fine here too

**Comment by jbillingredhat** [comment]
So, it appears that if I have the policy file in place before a user has ever launched Google Chrome, the policy only affects the user's uBO settings on the third launch of Chrome.  It might be worth putting that in the documentation.
