### ISSUE TITLE
Broken after Microsoft Edge crashed and lost cloud storage after reinstall

### ISSUE THREAD

**Issue by namniav** [uBlockOrigin/uBlock-issues#2851]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Microsoft Edge had a crash and uBO extension was broken after restarted browswer. There was a repair option for uBO in edge://extensions/, however uBO was deleted when I clicked the repaire option.

 Then I reinstalled uBO from Microsoft Edge's extension store and enabled cloud storage, but uBO didn't find my custom static rules from cloud storage. There was a lot of rules. I had synced rules between this macbook and a windows desktop by cloud storage.  Can I recover them with only this macbook at hand?

I have tried re-sync from edge://settings/profiles/sync. I didn't change the Microsoft Edge's login account nor sync settings.

Since I have reinstalled uBO, there's not much information I can provide. I don't know why nor how Microsoft Edge crahed and uBO was broken, they just happened while normal browsing. I'm not sure whether this is a uBO issue or Microsoft issue. If you guys think this is more a Microsoft issue, just let me know.

### A specific URL where the issue occurs.

It's not relevant to any URL.

### Steps to Reproduce

Sorry I can't reproduce, and logs are lost after reinstallation.

### Expected behavior

Recover from cloud storage.

### Actual behavior

There's no download option for custom static rules.

### uBO version

uBlock Origin 1.52.2 (after reinstall)

### Browser name and version

Microsoft Edge 117.0.2045.55 (arm64)

### Operating System and version

macOS 12.6.8

**Comment by gwarser** [comment]
Export your rules on MacBook and then try importing on Windows.

Do backups.

Report bug to Edge devs.

**Comment by garry-ut99** [comment]
> **namniav** : I don't know why nor how Microsoft Edge crahed and uBO was broken, they just happened while normal browsing. I'm not sure whether this is a uBO issue or Microsoft issue. If you guys think this is more a Microsoft issue, just let me know.

Browser crashes are a browser's issue : https://github.com/uBlockOrigin/uAssets/issues/16613#issuecomment-1415835892

**Comment by namniav** [comment]
@gwarser Finally and fortunately, I reach my Windows PC and find my rules there. 

However, while the uBO on macOS still cannot find my cloud data, the one on Windows showed my cloud data available for download that was uploaded from MacBook about two months ago.

Right after I exported settings from Windows to a file, the tab of uBO's settings page was force-closed by Edge. Then uBO was auto upgraded from 1.51.0 to 1.52.2 which is same as uBO on my MacBook, and my cloud data is gone again. I think that might be Edge's auto-sync process that synced extensions from macOS to Windows.

I tried to reproduce by sideloading uBO 1.51.0 downloaded from Github's release page. But it failed to find my cloud data, probably because extension ID is different when uBO is sideloaded from local filesystem. Can you provide a signed and packed uBO 1.51.0 crx file for Edge's extension store?

**Comment by gwarser** [comment]
[extension_1_51_0_0.crx.zip](https://github.com/uBlockOrigin/uBlock-issues/files/13176849/extension_1_51_0_0.crx.zip)

**Comment by namniav** [comment]
Never mind, I think I have figured out what was going on and it is not related to uBO.

Cloud storage isn't real cloud storage. It is essentially local storage but can be synced with extension to remote server and then to other clients(browsers).

Synchronization of extensions (and their "cloud storage") starts by browser's internal schedule (or clicking resync button in browser's setting). It may or may not start right after clicking the upload/download button in uBO. Those buttons just copy data between two local storages.

If an extension is removed from any client (only tested with Edge), then its cloud data is also deleted from remote sever no matter how many clients having this extension nor which client uploaded the data.

When an extension happens to be "corrupted" by any reason, Edge refuses to load it and shows a repair button in edge://extensions/. The repair button may **REMOVE** the extension which cause deletion of local data and cloud data.

Conclusion: **THE REPAIR BUTTON IS DANGEROUS.**

What in fact happened to me days ago:

1. Edge crashed and corrupted uBO for unknown reason.
2. I clicked the repair button thinking that it will just repair uBO. However, it removed uBO and its data. This unintended remove was synchronized to MS's server.
3. After some days I reach my Windows PC which had been synced from my MacBook. Before Edge starting synchronization, so fortunately, I exported uBO's setting to a file and saw this uBO still have available cloud data to "download" that in fact is local cache.
4. Edge started synchronization so uBO on Windows PC also lost its cloud data.

To confirm:

1. Install fresh uBO to Edge on two clients and enable cloud storage.
5. On client A's uBO: 
   * Add a static rule.
   * Upload to cloud storage.
   * Wait some seconds for synchronization.
6. On client B: 
   * Resync in Edge's setting, see synced cloud storage in uBO's setting(extension://odfafepnkmbhccpbejgmiehpchacaeak/dashboard.html#1p-filters.html).
   * Quit Edge.
   * Append a space to uBO's `js/start.js` (On windows, it's at C:/Users/<username>/AppData/Local/Microsoft/Edge/User Data/Default/Extensions/odfafepnkmbhccpbejgmiehpchacaeak/1.52.2_0/js/start.js).
   * Open Edge. Now uBO on client B is corrupted and a repair button is showed in edge://extensions/.
   * Click repair. Now Edge REMOVEs uBO and downloads a new one (glimpse that because download-popup is showed for a second) without installing it, however.
   * Wait some seconds for synchronization.
7. On client A:
   * Resync in Edge's setting if needed.
   * Open uBO's static rules setting, now it shows no available cloud data.

**Comment by gwarser** [comment]
In general, vendors warn that sync is not a backup feature.
