### ISSUE TITLE
Back button skips previous page with ublock origin enabled in Firefox mobile

### ISSUE THREAD

**Issue by edmomot** [uBlockOrigin/uBlock-issues#2861]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Pressing the phone's back button causes the browser to move back two pages instead of one. 

### A specific URL where the issue occurs.

http://lemmy.world

### Steps to Reproduce

1. In Firefox mobile on Android, install ublock origin
2. Disable all filter lists in ublock origin
3. Navigate to http://lemmy.world
4. Note the content at the top of page 1
5. Scroll to the bottom of the page
6. Hit the Next button to go to page 2
7. Click the comments icon on the first post on page 2 to view the comments page.
8. Press the phone's back button

### Expected behavior

Expect to see the top of page 2

### Actual behavior

Actually see content on page 1.

Refreshing the browser causes page 2 to be displayed. 

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox Mobile: 118
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  adguard-mobile: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1375 ms
 maxAssetCacheWait: 17 ms
```
</details>

**Comment by iam-py-test** [comment]
Can you try disabling uBo and seeing if this persists? I suspect this is just how the website works.
Thanks

**Comment by edmomot** [comment]
The configuration likely looks funny because I disabled all lists to see if the issue was with a tracking list or the plugin itself. 

Earlier, disabling the plugin fixed the issue.

However, after removing the plugin entirely, the issue persists.

So not an issue with ublock origin after all.

Thanks for trying to reproduce
