### ISSUE TITLE
Yoitube

### ISSUE THREAD

**Issue by monark1234567894** [uBlockOrigin/uBlock-issues#2862]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Youtube can detect this adblocker

### A specific URL where the issue occurs.

https://www.youtube.com/

### Steps to Reproduce

Click a video and message pops up that ad blocker detected

### Expected behavior

Like before youtube cant detect it

### Actual behavior

Suddenly today it was able to detect

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 105399
 cosmetic: 39902
 scriptlet: 18740
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 71567-13, 4d.17h.16m
  easyprivacy: 33209-64, 4d.15h.15m
  plowe-0: 3717-1064, 4d.23h.38m
  ublock-badware: 7186-133, 4d.11h.58m
  ublock-filters: 34984-143, 4d.11h.57m
  ublock-privacy: 556-6, 5d.17h.14m
  ublock-quick-fixes: 195-20, 20m
  ublock-unbreak: 2132-30, 4d.11h.56m
  urlhaus-1: 12110-0, 15h.26m
filterset (user): [empty]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 605 ms (selfie)
 maxAssetCacheWait: 259 ms
```
</details>

**Comment by mapx-** [comment]
read / report here https://github.com/uBlockOrigin/uAssets/issues/19976
