### ISSUE TITLE
uBlock not working on my browser (Recent Youtube Update)

### ISSUE THREAD

**Issue by Shiroo77** [uBlockOrigin/uBlock-issues#2864]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Today I got a prompt on Youtube (Ad Blocker aren't allowed), uBlock isn't working since then. I'm able to view ads while using uBlock.

This happened today 13th Oct.

Browser : Chrome 
Version : 118.0.5993.70

uBlock Version : 1.52.2

The URL I've provided isn't specific (I saw ads on a different video, I can't remember which one was that) 

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/141759574/7dba8551-5672-45dd-b6ad-fecef4e44f28)

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=xUjzhjipK_k

### Steps to Reproduce

1. Open Youtube, Maybe you'll get a prompt just like mine 
2. Start watching a video & check if ads are visible or not 
3. Has I've mentioned earlier that it's not happening to every single video, But some videos 

### Expected behavior

I expected now to see ads ! 

### Actual behavior

I saw ads on videos while using uBlock 

### uBO version

1.52.2

### Browser name and version

Chrome &  118.0.5993.70

### Operating System and version

Windows 10

**Comment by mapx-** [comment]
for YT only here => https://github.com/uBlockOrigin/uAssets/issues/19976
