### ISSUE TITLE
`replace-node-text` scriptlet nodeName argument not working correctly.

### ISSUE THREAD

**Issue by BraveUser-HGhost88-TEMP** [uBlockOrigin/uBlock-issues#2868]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Making some tests with the scriptlet, I found that the nodeName argument is failing to work as expected in many nodes.
There are two problems about it.

1. It is not using the exact node being added as argument.
   Example: `th` can get `thread` or if you use `a` it will grab anything that has the letter a in the nodeName, which is bad since it will break most things.
2. If the node has attribute and it is more than just `<node>`, then sometimes it won't work.
   Example: if the th is `<th scope="col">` it will not work by adding `th` as the argument, and only `<thread>` will be used (going to problem 1), which will cause issues anyway because thread is not the one with the text.
3. I have notice sometimes it will work, like using span, even if it has attributes it will work but sometimes it doesn't, like using button for a button node like: `< button id="button-read-values".....>` doesn't work.

Anyway, this site can show problems I am talking about: https://dev-pages.bravesoftware.com/storage/ephemeral-storage.html

If you want to change `Storage API` to `Clown World`

If you use `dev-pages.bravesoftware.com##+js(rpnt, th, Storage API, Clown World)` it will look messy 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/147880969/cac720ed-c86c-4ed0-ab58-c09eb0be6c3b)

If you check Devtools, it is because it is somehow the scriptlet removed the `<tr>` and  `<th scope="col">Storage API</th>` and added the text to the `<thread>` node since it started with `th` as added to the argument.

The only solution is to make the rule `dev-pages.bravesoftware.com##+js(rpnt, /th$/, Storage API, Clown World)` to force it to only use the th, and then that way it will use the proper node making th a valid argument for the scriptlet to be used.

Then same problem with button node, the rule has to be `dev-pages.bravesoftware.com##+js(rpnt, /button$/, Start test,  Clown World)` to make the button text be replaced.

using `a`  as argument will break pages, but also I noticed that using a rule like `cgchannel.com##+js(rpnt, /^a$/, , Testing)`, this will replace the text as expected, but also it will replace the <img> nodes inside the <a> with Testing name, which I don't know if it is an expected behavior. Logger doesn't even say anything about it, it just does it.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/147880969/72a1ee20-2ce7-4721-9f7d-935141e5085a)

But overall it seems the scriptlet has easier job with simple nodes like `<h1>`, but when it is more than that, it is random when it will work or not.

It is the same behavior on both Brave and uBlock, I currently don't use uBlock much, and only enabled it to fix any incompatibilities. So my uBlock version is pretty much the out of the box experience with nothing but the custom rules mentioned in this post and the Author mode on. And I properly tested it on uBlock before submitting this.

Of course, since I know the workaround for this issue, it doesn't really affect my rules or anything, but since it is used more and more in uBlock filter lists, I better report it in case, it is an unexpected behavior/bug and needs to be fixed.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Add `dev-pages.bravesoftware.com##+js(rpnt, a, , Clown World)` to My filters
2. go to https://dev-pages.bravesoftware.com/storage/ephemeral-storage.html
4. website is completely broken
5. add /a$/ to the nameNode argument to restrict what the argument is 'searching for' for the node = `dev-pages.bravesoftware.com##+js(rpnt, /a$/, , Clown World)` 
6. Refresh page
7. Now any  `<a href="">TEXT</a>` now are replaced correctly with the words 'Clown World'.

### Expected behavior

Being able to use any node like <a class="class" etc>Text</span> properly without using regex to 'restrict' the argument, and and only use regex for anything advanced, like selecting h1-6 all at once.

### Actual behavior

1. Using any node that has attributes seems to need regex to make it work properly in many cases.
2. using a simple `a` will break pages or using anything like
3. using invalid and unexciting nodeNames like `1` will select h1 and any node with a 1 and so on, which shouldn't be correct.

### uBO version

1.52.2

### Browser name and version

brave Nightly v1.61.22

### Operating System and version

Windows 11 22H2

**Comment by krystian3w** [comment]
Looks similar too:

https://github.com/uBlockOrigin/uAssets/discussions/18185#discussioncomment-6068996

> 
> ```adb
> example.com##+js(rpnt, , Example Domain, Changed)
> example.com##+js(rpnt,, Example Domain, Changed)
> ```

**Comment by gorhill** [comment]
Agreed, `nodeName` should be an exact match if not a regex.

**Comment by BraveUser-HGhost88-TEMP** [comment]
I tested this and while it works great, with most rules, I still noticed that using `dev-pages.bravesoftware.com##+js(rpnt, th, , TESTING)` doesn't work correctly with the whole `th` vs `thread`

I want to confirm it, do you see it like:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/147880969/2cfa10c0-4588-4cdc-b6ed-c107d586b1dc)

or 

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/147880969/4011f79b-90f8-49c8-a679-39bcc66b0beb)

if the first, that means the text is still being placed in `<thread` while removing all the THs. in that case, to get the second image would still need `/th$/`.

I just want to confirm.

Also, @gorhill is it a good behavior for the replace text to also replace the `img` nodes inside the `A` like it happens if you use `cgchannel.com##+js(rpnt, a, , Testing)` in [cgchannel,com](https://www.cgchannel.com/)? 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/147880969/45b0c918-0d7d-4e28-a85c-146ad1ef2265)

Even log will not show why it is replacing the img node, since it displays blank because textContent in those As will result in `'\n                \n            '`

Anyway, it is working better so thanks for the quick fix!

**Comment by gorhill** [comment]
> Also, @gorhill, would it be an expected behavior for the replace text to also replace the `img` nodes inside the `A` like it happens if you use `cgchannel.com##+js(rpnt, a, , Testing)` in [cgchannel,com](https://www.cgchannel.com/)?

Yes, it's the expected behavior since you are targeting an Element node (`a`) rather than a `#text` node. The scriptlet assign through [`Node.textContent`](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent).

**Comment by BraveUser-HGhost88-TEMP** [comment]
@gorhill
Ok! I guess when something weird happens, regexp will be the fix, which is good enough for me in the rare situational cases this might happen.
Thanks captain, take care.
