### ISSUE TITLE
Can't open links in a new tab if blocked in "My filters"

### ISSUE THREAD

**Issue by m3thm4th** [uBlockOrigin/uBlock-issues#2869]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Adding a filter in "My filters" and an exclusion for a domain, results in the link not being able to be opened from a link in a new tab

### A specific URL where the issue occurs.

https://tracker.debian.org/linux

### Steps to Reproduce

1. Add `||tracker.*$all` to "My filters"
2. Add `no-strict-blocking: tracker.debian.org true` and `tracker.debian.org tracker.debian.org * allow` to "My rules"
3. Search any search engine for a package in the Debian tracker (e.g. debian tracker linux)
4. Open the link https://tracker.debian.org/linux in a new tab

### Expected behavior

The page should open normally

### Actual behavior

The page gets immediately closed. This doesn't happen if the url is opened in the same page of the web search or it's pasted in the url bar of another page.

### uBO version

1.52.2

### Browser name and version

Firefox 115.3.0esr

### Operating System and version

Debian 12

**Comment by iam-py-test** [comment]
I think this is because `$all` also implies [`$popup`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#all)(the popup blocker), which isn't overridden by overriding strict blocking.
In my opinion, that is intended.
Thanks.

**Comment by gorhill** [comment]
> `$all` also implies [`$popup`](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#all)

That is the right answer, and the logger shows this:

![Screenshot from 2023-10-14 08-11-29](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/585c5b6e-a455-40e7-be68-0f9f0c43ae82)

**Comment by gorhill** [comment]
Use `||tracker.*$all,~popup` to exclude `popup` from `all`.
