### ISSUE TITLE
Strange behavior `no-xhr-if` when specifying headers

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2871]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

If add any arbitrary header value to the rule, then all requests of this type are blocked.

### A specific URL where the issue occurs.

`https://pikabu.ru/`

### Steps to Reproduce

Add: `pikabu.ru##+js(no-xhr-if, headers:blabla)`

### Expected behavior

There are no such values in the headers, so the rule shouldn't do anything.

### Actual behavior

All xhr requests are blocked.

This issue was also discussed here: https://github.com/uBlockOrigin/uAssets/commit/ca9898d42a2c2c1ac9cc44d02bfe77d4d5fb6da0#commitcomment-129975750

### uBO version

uBlock Origin 1.52.3b9

### Browser name and version

Firefox 118.0.2 

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
`headers` is not an argument to [XMLHttpRequest.open()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open), it can't be used as a matching target in (`no-xhr-if` scriptlet](https://github.com/gorhill/uBlock/wiki/Resources-Library#no-xhr-ifjs-).

**Comment by dimisa-RUAdList** [comment]
Oh, I'm sorry. Obviously, I was misled.

**Comment by gorhill** [comment]
If you have actual cases where this would be useful, I could look to extend the scriptlet through [XMLHttpRequest.setRequestHeader()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader), but if not I rather not spend time on this.

**Comment by dimisa-RUAdList** [comment]
Sometimes network requests are so confusing that it becomes difficult to distinguish between advertising and functional ones. But their headers may differ. In the case of Adblock Plus, I use [option $header](https://gitlab.com/adblockinc/ext/adblockplus/adblockplusui/-/issues/898). 

Here is one such example: https://github.com/abp-filters/abp-filters-anti-cv/issues/699#issuecomment-1721739966

And here are other similar use cases: https://github.com/abp-filters/abp-filters-anti-cv/issues?q=header%3D

**Comment by gorhill** [comment]
> In the case of Adblock Plus, I use [option $header](https://gitlab.com/adblockinc/ext/adblockplus/adblockplusui/-/issues/898).

Unfortunately not compatible with MV3.

> Here is one such example: https://github.com/abp-filters/abp-filters-anti-cv/issues/699#issuecomment-1721739966

I am not able to reproduce a blocked network request through a header filter with ABP. Is this on a specific webpage?

**Comment by dimisa-RUAdList** [comment]
<details>
<summary>Screenshot(s)</summary>

![cq-ru](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/c5dd531b-61f7-4d86-b6cb-742f54d3e8cc)


</details>

**Comment by gorhill** [comment]
Ok, so this about *response* headers, not request headers. This mean the request is made to the server, but matched and blocked once the response headers arrive. Now if I use uBO + RUAdList instead, I see you are blocking the request by pattern, which is more efficient, so why go with the `header` solution for ABP?

**Comment by dimisa-RUAdList** [comment]
The fact is that the path of the advertising network request `https://cq.ru/cq67er` changes periodically. The frequency of rotation is from once a week to several times a day.

Therefore, as an effective rule for uBlock Origin (Google Chrome), I use:
`cq.ru##+js(addEventListener-defuser, DOMContentLoaded, banners)`

For Adblock Plus (Google Chrome) this is: `cq.ru#$#prevent-listener DOMContentLoaded 'banners'`

However, in Firefox these rules are unstable, so a rule has been added for uBlock Origin:
`cq.ru##^script:has-text(window.initBanners)`

And for Adblock Plus: `||cq.ru^$xmlhttprequest,header=cq-cache-bypassed`

**Comment by dimisa-RUAdList** [comment]
@uBlock-user 
The rule `||cq.ru^$xmlhttprequest,header=cq-cache-bypassed` works fine, but by default this option (filterOnHeaders) is disabled, so adding it to RU AdList is useless.

**Comment by gorhill** [comment]
`header=` available in 1.52.3b10 as a non-experimental option: https://github.com/gorhill/uBlock/commit/c96a673338

**Comment by gorhill** [comment]
I will just label the issue here as _invalid_ because the request was to support matching against response headers, while the purpose of `no-xhr-if` is to prevent a network request from being made, and as such response headers would never be available to the scriptlet, so it's not possible to implement.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
I noticed that in some cases responseheader rules (formerly "header") they don't work in uBOL.

**Example**

1. Disable the RU AdList filters.
2. Open it: `https://pikabu.ru/story/konets_sveta_10647011`
3. Refresh the page a couple of times to get xhr requests like: `https://pikabu.ru/ajax//dQkk3mIdfkW199maqb3x.q?pg3Pu=dd25fb178c1afb7cef9faa7bc86d6175_217085634`

When added to uBO: `||pikabu.ru/ajax/$responseheader=llasalbbubrrl` or `||pikabu.ru/ajax/$xmlhttprequest,responseheader=llasalbbubrrl` - these requests will be blocked. However, these rules do not work in uBOL.

Is this a consequence of mv3 limitations, or can it be fixed?

**Comment by gorhill** [comment]
Looking at the rules in RUS-0 using the _Develop_ pane, I see this rule that seems to match the one you are talking about:

```yaml
action:
  type: block
condition:
  resourceTypes:
    - xmlhttprequest
  responseHeaders:
    - header: llasalbbubrrl
  urlFilter: ||pikabu.ru/ajax/*_*?*=
id: 5978
priority: 10
```

The `urlFilter` in that rule does not the match requests like `https://pikabu.ru/ajax//dQkk3mIdfkW199maqb3x.q?pg3Pu=dd25fb178c1afb7cef9faa7bc86d6175_217085634`, there is no `_` character before the `?`.

**Comment by dimisa-RUAdList** [comment]
Everything is right. This rule became outdated about a week ago. I just didn’t change it because I hadn’t yet decided on the further strategy. As soon as the prospects for the rule in MV3 become clear, I’ll settle on one of the options.

**Comment by gorhill** [comment]
I gave it a try but after reloading many times I cannot reproduce something like `pikabu.ru/ajax//dQkk3mIdfkW199maqb3x`.

Please provide the details of that request from network pane in dev tools, and also see how the rule looks like in _Develop_ pane in uBOL, should be at the bottom of `Dynamic rules`.

**Comment by dimisa-RUAdList** [comment]
Most likely, certain conditions must be met.

1. Disable the RU AdList filters.
2. The filtering mode is “complete”.
3. Add: `pikabu.ru##.sidebar-block_placeholder` to the sandbox.
4. Use a Russian IP (I’m not sure about this).

<details>
<summary>Screenshot(s)</summary>

<img width="1919" height="1032" alt="Image" src="https://github.com/user-attachments/assets/4f04e81c-1046-436f-81c4-b1a7050f8f75" />

</details>

**Comment by gorhill** [comment]
That worked, I reproduced after 2nd reload (no Russian IP required). The `llasalbbubrrl` header is in request headers, not response headers. Your filter would have to be `||pikabu.ru/ajax/$xmlhttprequest,requestheader=llasalbbubrrl`, but DNR rules do not support to filter according to request headers, see <https://github.com/w3c/webextensions/issues/964>.

<img width="766" height="95" alt="Image" src="https://github.com/user-attachments/assets/56a8c11c-ff6d-4771-8c55-eb12e9b42db2" />

**Comment by dimisa-RUAdList** [comment]
Thanks! I suspected that the rule wasn’t working due to the limitations of mv3, but I wasn’t sure.
