### ISSUE TITLE
Flickering with JavaScript disabled

### ISSUE THREAD

**Issue by oifj34f34f** [uBlockOrigin/uBlock-issues#2875]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Brief flickering occurs when JavaScript is disabled. When JavaScript is enabled, there is no flickering.

### A specific URL where the issue occurs.

https://www.gov.uk/

### Steps to Reproduce

1. Add `www.gov.uk###global-cookie-message` filter or simply add `AdGuard/uBO – Cookie Notices` filter list.
2. Disable JavaScript (`about:config` - `javascript.enabled` -> `false`).
3. Go to https://www.gov.uk/
4. See brief flickering.

### Demo

https://github.com/uBlockOrigin/uBlock-issues/assets/128177553/8f2ccef0-101c-488d-9154-6842927f107a

### Expected behavior

No flickering.

### Actual behavior

Brief flickering.

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Operating System and version

Arch Linux 6.5.7

**Comment by gorhill** [comment]
Same behavior with AdGuard or ABP, so I consider this a normal behavior, or one you will have to accept. It looks better if you [disable JS in uBO](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting) instead of `about:config`.

**Comment by gorhill** [comment]
Another solution is to use HTML filtering filter: `www.gov.uk##^#global-cookie-message`.

The reason the "flickering" is occurring is simply because the page loads much faster when JS is disabled and it's just not possible to programmatically apply cosmetic filtering before the browser loads a good portion of the page. HTML filters remove elements from the HTTP response before it's processed by the browser.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ALL%20FOUC&list_id=16757847
