### ISSUE TITLE
YouTube Requests Disabling uBlock Origin for Ads

### ISSUE THREAD

**Issue by preston176** [uBlockOrigin/uBlock-issues#2876]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

## Issue Overview:
I am experiencing a problem on YouTube where the platform prompts me to disable uBlock Origin in order to continue watching videos. This seems to be a recent development, and I believe it's affecting other users as well.

## Screenshots/Console Logs: 

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/49411983/2e74d44e-a3f6-4604-92af-dcc2666c32d0)

### A specific URL where the issue occurs.

https

### Steps to Reproduce

1. Open YouTube with uBlock Origin enabled.
2. Attempt to watch a video.
3. Observe the prompt asking to disable uBlock Origin for ads.

### Expected behavior

Users should be able to use uBlock Origin to block ads on YouTube without being prompted to disable the extension for video playback.

### Actual behavior

Users are prompted to disable AdBlocker to continue watching. Sometimes refreshing the window will temporarily allow playbacks until the pop up appears

### uBO version

1.52.2

### Browser name and version

Google Chrome Version 117.0.5938.152 (Official Build) (64-bit)

### Operating System and version

Operating System: Windows 11 22H2 build 22621.2134

**Comment by mapx-** [comment]
read / report here: https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by ssm2130** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/89034783/c306477c-d5bf-4d16-beaa-1581313801d4)
