### ISSUE TITLE
YouTube letting me know i am using an AD blocker

### ISSUE THREAD

**Issue by WarsunGames** [uBlockOrigin/uBlock-issues#2878]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

NO SHIT I am using an AD blocker. Can you please block them sending me this fucking message. Please. Did anyone figure there is a fucking reason why i AM using an AD Blocker? Because it Interrupts me watching Videos I FUCKING PAYED FOR INTNERNET TO USE! I didn't come here to see adds. WHICH is why they ARE BLOCKED! Can you please block or reroute the message to it does not interrupt my videos.

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=4R99K6BVqYs

### Steps to Reproduce

When you are AFK or you refresh a window.

### Expected behavior

interrupts the video. Then puts a big window in front an has you to click X after a few seconds or click on other Bull shit to start questioning you as of WHO's Ad blocker you are using. Which is NONE OF THEIR FUCKING BUSINESS!

### Actual behavior

It just pops up on screen telling you you are using an AD blocker. As if i didn't know. Not that its against their terms of service. An even if it was. That is evasive due to you have no right to interfere with the clients use of the product. Which would be against the law. The law does not say you are required to watch ads.

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 105368
 cosmetic: 39926
 scriptlet: 18603
 html: 1066
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35797-73, 4d.15h.14m
  ublock-badware: 7240-0, 4d.15h.13m
  ublock-privacy: 589-0, 2d.17h.4m
  ublock-unbreak: 2187-1, 4d.15h.12m
  ublock-quick-fixes: 220-0, 6h.26m
  easylist: 71651-693, 3d.17h.8m
  easyprivacy: 33231-717, 1d.15h.19m
  urlhaus-1: 11950-0, 14h.27m
  plowe-0: 3729-1, 2d.7h
filterset (user): [empty]
trustedset:
 added: [array of 11 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 240 ms (selfie)
 maxAssetCacheWait: 81 ms
```
</details>

**Comment by mapx-** [comment]
duplicate 
go to https://github.com/uBlockOrigin/uAssets/issues/19976
