### ISSUE TITLE
Blocking popups won't work on secondary click (mac only)

### ISSUE THREAD

**Issue by fayedwho** [uBlockOrigin/uBlock-issues#288]
### Prerequisites

- [✔️] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✔️] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [✔️] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [✔️] uBlock Origin is the only extension
    - [ ✔️] uBlock Origin with default lists/settings
    - [ ✔️] using a new, unmodified browser profile
- [ ✔️] I am running the latest version of uBlock Origin
- [ ✔️] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When I choose to block all popups for a specific site, all popups are blocked on the primary click, but not the secondary click (mac only).

### A specific URL where the issue occurs
https://mac-torrent-download.net/

### Steps to Reproduce

1. primary click on uBO icon.
2. click on "block all popups on this site" icon.
3. go to the mentioned site and secondary click on any link, there will be a popup.
4. if you didn't get a popup from the first time, try a few times and you will get one.

### Expected behavior:
No popups on secondary click

### Actual behavior:
Popups on secondary click

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Chrome 70.0.3538.77
* Operating System and version: macOS Sierra 10.12.6

**Comment by uBlock-user** [comment]
Can't reproduce, regardless of click, they're closed immediately.

**Comment by fayedwho** [comment]
@uBlock-user this issue occurs on mac only. On Windows, everything is fine.

**Comment by uBlock-user** [comment]
Someone with macOS will have to reproduce.

**Comment by gorhill** [comment]
Consider this a filter issue until proven otherwise. Whoever has MacOS will have to investigate the cause -- so this issue will probably never be resolved.

**Comment by fayedwho** [comment]
@gorhill I was not able reproduce the issue on Windows with the exact same filters and settings that I have on macOS. So I am pretty sure the issue is specific for macOS.

**Comment by gorhill** [comment]
Did you try to reproduce with other popup cases on other sites? This could be specific to this one site, as a result of the site's JS behaving in a specific way according to the OS platform. There is no macOS-specific code in uBO.

**Comment by fayedwho** [comment]
I could reproduce it on that site only (so far). As you said, that could be specific to this site. Since there is no macOS-specific code in uBO, I believe this issue is over.

**Comment by uBlock-user** [comment]
`mac-torrent-download.net##+js(abort-current-inline-script.js, decodeURIComponent, zfgloadedpopup) ` fixes the popup issue..

**Comment by fayedwho** [comment]
@uBlock-user Thanks a lot!
