### ISSUE TITLE
AdGuard aliases for set-cookie-reload and trusted-set-cookie-reload are wrong

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uBlock-issues#2881]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Correct AdGuard syntax to set a cookie and reload:
`example.org#%#//scriptlet('set-cookie-reload', 'cookie-set1', '1')`
See https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-cookie-reload

Correct uBlock0 syntax to set a cookie and reload:
`example.org##+js(set-cookie, cookie-set3, 3, , reload, 1)`
See https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-

The same thing applies to trusted-set-cookie
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#trusted-set-cookie-reload
https://github.com/gorhill/uBlock/wiki/Resources-Library#trusted-set-cookiejs-

So, 
- uBlock0 should recognize both of them as correct
- uBlock0 should  convert correct AG syntax into uBlock0 correct syntax 

### A specific URL where the issue occurs.

example.org

### Steps to Reproduce

Add these filters to User Filters List:
```
example.org#%#//scriptlet('set-cookie-reload', 'cookie-set1', '1')
example.org#%#//scriptlet('set-cookie', 'cookie-set2', '2', '', 'reload', '1')
example.org##+js(set-cookie, cookie-set3, 3, , reload, 1)
!
example.org#%#//scriptlet('trusted-set-cookie-reload', 'cookie-tset1', 'tset1')
example.org#%#//scriptlet('trusted-set-cookie', 'cookie-tset2', 'tset2', '', '', 'reload', '1')
example.org##+js(trusted-set-cookie, cookie-tset3, tset3, , , reload, 1)
```

### Expected behavior

```
example.org#%#//scriptlet('set-cookie-reload', 'cookie-set1', '1')
example.org##+js(set-cookie, cookie-set3, 3, , reload, 1)
example.org#%#//scriptlet('trusted-set-cookie-reload', 'cookie-tset1', 'tset1')
example.org##+js(trusted-set-cookie, cookie-tset3, tset3, , , reload, 1)
```

are recognized as correct and applied.

### Actual behavior

```
example.org#%#//scriptlet('set-cookie', 'cookie-set2', '2', '', 'reload', '1')
example.org##+js(set-cookie, cookie-set3, 3, , reload, 1)
example.org#%#//scriptlet('trusted-set-cookie', 'cookie-tset2', 'tset2', '', '', 'reload', '1')
example.org##+js(trusted-set-cookie, cookie-tset3, tset3, , , reload, 1)
```
are recognized as correct and applied.

### uBO version

1.52.2

### Browser name and version

Firefox 118

### Operating System and version

macOS 11

### Screenshot
<img width="885" alt="cookie-reload" src="https://github.com/uBlockOrigin/uBlock-issues/assets/1375223/4ea1f1fb-9772-4f53-8503-7dc42e777b1b">

**Comment by gwarser** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/7894dfe3-697a-4f7c-b5f3-07bfba1b4c8d)

**Comment by Yuki2718** [comment]
Has something changed about position of the reload token? For https://github.com/AdguardTeam/AdguardFilters/issues/180011 `portal.payment.eltax.lta.go.jp##+js(set-cookie, xn_cookieconsent, false, , , reload, 1)` never works but `portal.payment.eltax.lta.go.jp##+js(set-cookie, xn_cookieconsent, false, , reload, 1)` does.

**Comment by stephenhawk8054** [comment]
`set-cookie` has 3 arguments (expire time is only session) => `false, , reload, 1`

`trusted-set-cookie` has 4 arguments (custom expire time) => `false, , , reload, 1`
