### ISSUE TITLE
Some long-standing bugs

### ISSUE THREAD

**Issue by samsungheavy** [uBlockOrigin/uBlock-issues#2883]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

1. Open the logger, view network requests and DOM elements, when you left-click the record, the record temporarily changes color, but the record will not be selected. When you close the pop-up window, you won't find the last record entry you viewed. This is inconvenient.
2. In the pop-up window just mentioned, if the record has an associated filter rule, when you click on the filter rule, you will be taken to (moz-extension://de304deb-7698-490b-89a2-94cbfdfe631d/asset-viewer.html?url=user-filters)， not (moz-extension://de304deb-7698-490b-89a2-94cbfdfe631d/dashboard.html#1p-filters.html), so you can't easily edit this filter rule or delete it. This is inconvenient.
3. In the Custom static filter rules tab, there is no checkbox in front of each rule, which can make the rule temporarily disable, and there is also no The number of requests blocked after each rule.  it is not convenient to debug, you can only temporarily cut these rules into Notepad to disable it temporarily.
4. (Firefox 56.0.2 + adblock_plus-2.9.1-an+fx+sm+tb.xpi + element_hiding_helper_for_adblock_plus-1.4-fx+sm+tb.xpi) is perfect, but this is outdated, and now ABP is not as good as it used to be. Please refer to the program interface and operation logic above.

### A specific URL where the issue occurs.

https://cn.bing.com/translator

### Steps to Reproduce

just as above.

### Expected behavior

just as above.

### Actual behavior

just as above.

### Configuration

<details>

```yaml
uBlock Origin: 1.47.0
Firefox: 118
filterset (summary): 
  network: 121160
  cosmetic: 50793
  scriptlet: 18789
  html: 1066
listset (total-discarded, last-updated): 
  added: 
    https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt: 75-0, 1d.4h.14m
  default: 
    user-filters: 1615-3, never
    ublock-filters: 35828-48, 5d.1h.39m
    ublock-badware: 7270-0, 5d.1h.38m
    ublock-privacy: 591-76, 1d.4h.15m
    ublock-unbreak: 2185-21, 5d.1h.37m
    ublock-quick-fixes: 223-49, 3h.39m
    easylist: 71726-713, 4d.2h.57m
    easyprivacy: 33206-17, 1d.4h.12m
    urlhaus-1: 12175-0, 3h.40m
    plowe-0: 3718-718, 8d.21h.30m
    CHN-0: 25172-181, 1d.4h.10m
filterset (user): [array of 1617 redacted]
modifiedUserSettings: 
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1716 ms (selfie)
  maxAssetCacheWait: 874 ms
```
</details>

**Comment by garry-ut99** [comment]
As for the 3, from the manual : https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-My-filters , press Tab key to comment / uncomment a filter :
![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/867fb052-4ea0-48cc-b2f7-e12c23da9393)

**Comment by gorhill** [comment]
See <https://github.com/uBlockOrigin/uBlock-issues/issues/381>.

**Comment by samsungheavy** [comment]
> > samsungheavy : 3. In the Custom static filter rules tab, there is no checkbox in front of each rule, which can make the rule temporarily disable, (...) you can only temporarily cut these rules into Notepad to disable it temporarily.
> 
> from the manual : https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-My-filters , press Tab key to comment / uncomment a filter : ![obraz](https://user-images.githubusercontent.com/72945564/275744554-867fb052-4ea0-48cc-b2f7-e12c23da9393.png)
> 
> By the way your uBO version is 1.47 which is outdated, the newest is 1.52.

thank you.

**Comment by samsungheavy** [comment]
> See #381.

thank you. It is hoped that the #1  #2 issue will be improved
