### ISSUE TITLE
No way to disable the extension on all sites, but some

### ISSUE THREAD

**Issue by Martinligabue** [uBlockOrigin/uBlock-issues#2887]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On Firefox the whitelist doesn't accept any wildcard, only addresses, this means that there is no way to whitelist everything except few websites.
On chrome the extension can be enabled only on certain websites, and that's a workaround (assuming you also make the extension work in the lists websites).

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

1. Open settings
2. Go to Whitelist
3. Insert * or any other wildcard

### Expected behavior

It should accept wildcards/regex/something, also an external option would work

### Actual behavior

It gives an error and doesn't allow me to set to whitelist a certain range of websites, so I need to specify thousands of them by hand

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.1

### Operating System and version

Ubuntu 23.10

**Comment by gwarser** [comment]
Not supported.

>That is not a feature supported by uBO. uBO is for people who share the view that the net is hostile by default and consequently uBO being disabled everywhere by default is incompatible with this view -- it would make no sense to have a malware list enabled by default just to have uBO disabled everywhere by default. AdGuard supports this mode, so you may want to use this instead.

But if you read the wiki, you will find a way.

**Comment by Martinligabue** [comment]
I see
