### ISSUE TITLE
Type rule to concisely override 1p/3p/inline scripts?

### ISSUE THREAD

**Issue by craigbarnes** [uBlockOrigin/uBlock-issues#289]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] ~~I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior~~

### Description

Currently, when using uBlock in "default deny" mode for the 3 script types (1p, 3p and inline) and 3p-frame, the per-site rules typically required to override this is:

```
github.com * 1p-script allow
github.com * 3p-script allow
github.com * inline-script allow
```

It would really improve the conciseness and readability of long lists of rules, if it were possible to override all 3 script types in a single line.

For allowing _everything_ it can be done as:

```
example.com * * allow
```

...but to allow all scripts whilst keeping third-party frames blocked, there's no similar convenience, and 99% of rules end up following the same 3-line pattern as above.

### A specific URL where the issue occurs

N/A.

### Steps to Reproduce

1. Add `github.com * *-script allow` or `github.com * 1p-script,3p-script,inline-script allow` to rules list.

### Expected behavior:

Not really "expected", but the _desired_ behaviour would be for all 3 script permissions to be set to `allow`.

### Actual behavior:

When clicking "save" the rule just disappears, presumably because the syntax is invalid.

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Chromium 70
* Operating System and version: Arch Linux

**Comment by gorhill** [comment]
Why not just use the no-scripting switch?

Rules are implemented with fast lookup, what you propose will cause added overhead, I prefer to decline.

**Comment by craigbarnes** [comment]
> Why not just use the no-scripting switch to wholly block JS?

Yeah, that does seem like a better solution. Thanks for the suggestion.

Just one other question: can `no-scripting: example.com false` rules be set via a Chromium `adminSettings` policy? I can set such rules via the dashboard fine, but they seem to be ignored if set via policy.

**Comment by gorhill** [comment]
> can `no-scripting: example.com false` be set via a Chromium `adminSettings` policy?

I expect this should work, I did not exclude them specifically from `adminSettings` and I just checked the code, they are taken into account.
