### ISSUE TITLE
Not blocking youtube ads

### ISSUE THREAD

**Issue by euniek1** [uBlockOrigin/uBlock-issues#2894]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I had all the proper filters and codes in place to block youtube advertisements, yet they didn't work
<img width="1276" alt="Screenshot 2023-10-20 at 7 05 54 PM" src="https://github.com/uBlockOrigin/uBlock-issues/assets/148594562/85559450-84c5-4ab8-baec-f734a67f5ec5">

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=AuIV0bWMEy8&ab_channel=WayV

### Steps to Reproduce

1. Click on youtube video with blocker on
2. Pop up appears

### Expected behavior

I expected the video to play like how it normally was, I saw that the filters weren't updated to I updated them and the same thing happend

### Actual behavior

My video was blocked

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104466
 cosmetic: 39961
 scriptlet: 18723
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  easylist: 71776-11, 5d.23h.35m
  easyprivacy: 33186-64, 1d.20h.4m
  plowe-0: 3729-1069, 5d.23h.35m
  ublock-badware: 7275-132, 21h.28m
  ublock-filters: 34957-144, 21h.27m
  ublock-privacy: 561-6, 5d.23h.34m
  ublock-quick-fixes: 236-77, now
  ublock-unbreak: 2125-32, 21h.26m
  urlhaus-1: 10980-0, 12h.27m
filterset (user): [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 476 ms (selfie)
 maxAssetCacheWait: 226 ms
```
</details>

**Comment by iam-py-test** [comment]
Please follow these instructions and report the issue here: https://github.com/uBlockOrigin/uAssets/issues/19976
Thanks

**Comment by gorhill** [comment]
> - [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.

You didn't.

Go to <https://github.com/uBlockOrigin/uAssets/issues/19976>.
