### ISSUE TITLE
Sidebar support on Firefox

### ISSUE THREAD

**Issue by Exploding-Joysticks** [uBlockOrigin/uBlock-issues#2898]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Support to open the logger in the sidebar has been worked on in the past [1](https://github.com/gorhill/uBlock/issues/2854), and sidebar support for Opera too [2](https://github.com/gorhill/uBlock/commit/295cf563ee809af144afea9c3ce94037a927eab3), but I don't know if anything ever came off that, the wiki has no mention of opening either uBO nor the logger on the sidebar, so I'm assuming it is not currently possible (at least not on Firefox).

Why?
1. The sidebar is a convenient way to access the toolbar, logger, or dashboard while keeping the user on the same tab/site instead of opening and sending them to a new window (logger) or a new tab (dashboard);
2. UserChrome.css users can change and remove whatever they want on Firefox's UI while still keeping uBO easily accessible (although that can also be done by just setting up a shortcut to open the toolbar);
3. Extensions like Bitwarden do it and it is really convenient to click back and forth on the page and on the sidebar and not have the extension lose focus and disappear like it does when accessed from the toolbar;
4. https://www.youtube.com/watch?v=5X3TXa8TMgo

### A specific URL where the issue occurs.

https://support.mozilla.org/en-US/kb/use-firefox-sidebar-access-bookmarks-history-synced

### Steps to Reproduce

Using Firefox, press Ctrl + B;
Click the dropdown on top of the sidebar (it probably says "Bookmarks");
No uBO option :(

### Expected behavior

uBlock Origin should be accessible through the sidebar.

### Actual behavior

uBlock Origin is not accessible through the sidebar.

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Operating System and version

Fedora Linux 38

**Comment by gorhill** [comment]
The dev build version of uBO supports opening the logger in the sidebar. Unfortunately it's not ideal because the sidebar width is limited by Firefox. There used to be an issue of the browser with the sidebar opening with uBO's logger in it, hence why it's just in dev build: <https://bugzilla.mozilla.org/show_bug.cgi?id=1459007>.

**Comment by Exploding-Joysticks** [comment]
I see, maybe opening uBO's pages using the mobile version of them on the sidebar (if that's even possible), could be a solution to the width problem?

**Comment by gorhill** [comment]
I prefer to decline this.
