### ISSUE TITLE
ADS won't show when a website is whitelisted

### ISSUE THREAD

**Issue by MisterTeeXD** [uBlockOrigin/uBlock-issues#290]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When a website has been whitelisted in UBlock, ads refuse to show

### A specific URL where the issue occurs

https://www.roblox.com/home

### Steps to Reproduce

1. Go to the UBlock Dashboard
2. Go to "Whitelist"
3. Add www.roblox.com to the filters
4. See the problem by going to the website with the whitelisted website

### Expected behavior:

The ads will show when the site  has been whitelisted

### Actual behavior:

The ads did not show at all

### Your environment

* uBlock Origin version: v1.17.2
* Browser Name and version: FireFox 62.0.3
* Operating System and version: Windows 10 Home Edition

**Comment by uBlock-user** [comment]
Ads don't show up if I disable uBO entirely either, so not a uBO issue.
