### ISSUE TITLE
关闭所有标签页的情况下使用edge浏览器打开pdf文件会导致浏览器闪退。

### ISSUE THREAD

**Issue by vmp65l3** [uBlockOrigin/uBlock-issues#2902]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

关闭所有标签页的情况下使用edge浏览器打开pdf文件会导致浏览器闪退。

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. edge浏览器安装ublock插件
2. 关闭浏览器
3. 使用edge浏览器打开任意pdf文件
4. 浏览器闪退

### Expected behavior

不要影响正常使用啊。

### Actual behavior

edge浏览器闪退

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 118
filterset (summary):
 network: 119744
 cosmetic: 50415
 scriptlet: 18932
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 4-0, never
  CHN-0: 25267-134, 1d.19h.17m
  easylist: 71987-25, 3d.22h.24m
  easyprivacy: 33148-77, 3d.22h.23m
  plowe-0: 3727-1075, 1d.19h.19m
  ublock-badware: 7255-132, 3d.22h.26m
  ublock-filters: 34994-161, 3d.22h.26m
  ublock-privacy: 589-6, 6h.51m
  ublock-quick-fixes: 222-69, 6h.50m
  ublock-unbreak: 2125-32, 3d.22h.25m
  urlhaus-1: 11630-0, 18h.53m
filterset (user): [array of 4 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 399 ms (selfie)
 maxAssetCacheWait: 159 ms
```
</details>

**Comment by gorhill** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2882

**Comment by garry-ut99** [comment]
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.

You didn't.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2925>.
