### ISSUE TITLE
[Feature Request] Add a simple to use button in the popout panel UI to purge & refresh Quick Fix list

### ISSUE THREAD

**Issue by 29039** [uBlockOrigin/uBlock-issues#2909]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Similar to the on/off button to quickly add an exception to a particular website without having to go through the settings and put the URL into the trusted sites yourself, why not add a button to quickly purge+refresh the 'Quick Fixes' list.

With this war with YouTube, a user can simply press this button to get uBO to work when a change comes through, rather than having to navigate the settings to do it manually.

### A specific URL where the issue occurs.

https://www.youtube.com

### Steps to Reproduce

Similar to the on/off button to quickly add an exception to a particular website without having to go through the settings and put the URL into the trusted sites yourself, why not add a button to quickly purge+refresh the 'Quick Fixes' list.

With this war with YouTube, a user can simply press this button to get uBO to work when a change comes through, rather than having to navigate the settings to do it manually.

### Expected behavior

1. User finds Adblock detection while using YouTube
2. User presses uBlock Origin browser extension icon
3. Press button to purge/refresh 'Quick Fixes' list
4. Quick Fix list of purged and refreshed, and the page is reloaded automatically once the updated list is in effect
5. The YouTube page works again right away, with the ads blocked.

### Actual behavior

Go through settings to do manual steps

### uBO version

1.52.2

### Browser name and version

Edge 118.0.2088.69

### Operating System and version

Windows 10 22H2

**Comment by gorhill** [comment]
There will be improvements in how filter lists update in next dev cycle. Last thing we want is to lose free CDN hosting because people abuse a too-easy-to-use button, turning uBO into a client to DDoS servers hosting the lists.

**Comment by 29039** [comment]
> There will be improvements in how filter lists update in next dev cycle. Last thing we want is to lose free CDN hosting because people abuse a too-easy-to-use button, turning uBO into a client to DDoS servers hosting the lists.

But the lists are just hosted on GitHub right? Should be able to hit about 5000 per hour from each IP address which should be plenty

https://stackoverflow.com/questions/66522261/does-github-rate-limit-access-to-public-raw-files

**Comment by gorhill** [comment]
https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits

> GitHub Pages sites have a soft bandwidth limit of 100 GB per month

**Comment by 29039** [comment]
> https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits
> 
> > GitHub Pages sites have a soft bandwidth limit of 100 GB per month

Instead of using GitHub pages URL to host the filters, you could use the raw.githubusercontent.com URL instead.

For example, instead of using:
`https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt`

Use:
`https://raw.githubusercontent.com/uBlockOrigin/uAssets/gh-pages/filters/quick-fixes.txt`

Which is in fact the exact same file.

**Comment by gorhill** [comment]
The filter lists need to be served with the fields at the top of the list properly filled.

**Comment by iam-py-test** [comment]
> The filter lists need to be served with the fields at the top of the list properly filled.

That appears to be the case:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/84232764/f803efdd-a263-4acf-94d6-354d5d6a2a65)
Thanks

**Comment by gorhill** [comment]
`filters.min.txt` does not exist at:
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.min.txt

`filters.min.txt` at
https://ublockorigin.github.io/uAssets/filters/filters.min.txt
is missing fields at the top which are going to be key in the next dev cycle to probably save significant bandwidth (that's the hope) while allowing shorter update periods.

`filters.min.txt` at
https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/main/filters/filters.min.txt
has all that is needed but it updates once per 6-hour

**Comment by 29039** [comment]
> is missing fields at the top

You are using:
`https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/`

The correct base URL is:
`https://raw.githubusercontent.com/uBlockOrigin/uAssets/gh-pages/filters/`

This is because of the way you have it set up is to have it push out to the GitHub pages branch

For example:
`https://ublockorigin.github.io/uAssets/filters/filters.min.txt`

Is the same as:
`https://raw.githubusercontent.com/uBlockOrigin/uAssets/gh-pages/filters/filters.min.txt`

I was assuming GitHub pages was being used, because this is what you said is the problem with rate limiting.

If it's actually using https://raw.githubusercontent.com/uBlockOrigin/uAssetsCDN/ and being updated every 6 hours, well then it's already on githubusercontact.com which allows 5k/hr per IP address and you just need to increase the update frequency. Perhaps on schedule if you can predict when the update will be pushed out.

**Comment by gwarser** [comment]
Of course, we use `raw` links. "5000 request / hour", but how about the bandwidth? We estimate uBO is fetching over 10TB of data daily from four CDN mirrors. You are speculating "maybe it will work" based on "some forum" posts. We cannot risk breaking the source of filter list, because CDNs will be useless when source is missing. We are 12 project on jsDelivr based on bandwidth, forty based on requests count.

**Comment by 29039** [comment]
Fair enough. But at the same time, perhaps it is worth testing. Maybe there is a way to configure which mirror to use, between github and jsDelivr, and allow the user to configure (with jsDelivr stay as the default), and see how it goes in testing 😇
