### ISSUE TITLE
Dynamic filtering: add option for strict partyness

### ISSUE THREAD

**Issue by user31415192** [uBlockOrigin/uBlock-issues#2912]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I want it so that uBO has an option for a dynamic filter to not propagate to subdomains.
My proposed dynamic filter syntax:
```
source dest ssp sdp type action
```
Where:
`source` and `dest`: Source and destination hostname, respectively. Subpaths are also supported, for example: `example.com/rsrc/foo`.
`ssp`: **S**trict **S**ource **P**artyness: Whether to prevent dynamic filter from propagating to subdomains of the source hostname.
Possible values:

> `0` (default value): dynamic filter will propagate to subdomains of the source hostname as usual.
> `1`: dynamic filter _**shall not**_ propagate to subdomains of the source hostname.
> > Please note that this value matters **_not_** when the value of the `source` component is `*`. In such a case, a value of `0` for `ssp` is preferred.

`sdp`: **S**trict **D**estination **P**artyness: Whether to prevent dynamic filter from propagating to subdomains of the destination hostname. Same as above.
`type`: Type of resource to filter. Use values supported in Dynamic URL filtering.
`action`: What to do with requests matching all the above conditions. Such requests can be `block`-ed, `allow`-ed, or let static filtering make the decision instead (`noop`).

As usual, more specific rules override less specific ones.

Examples:
`deviantart.com * 0 0 script block`
Meaning: disable all scripting on `deviantart.com` and all its subdomains.

`www.msn.com/en-us acdn.adnxs.com 1 1 * noop`
Meaning: requests whose origin matches `www.msn.com/en-us` and whose intended recipient is `acdn.adnxs.com` (subdomains not included) shall not be subject to any dynamic filtering rule.

You may expand on this system to allow for more granularity.
As this system is more advanced than the traditional four-component system, a warning must be included that this one is only for those that have mastered the old four-component system. 

### A specific URL where the issue occurs.

-

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBO version

1.52.2

### Browser name and version

*

### Operating System and version

*

**Comment by gwarser** [comment]
@user31415192 how will you delight the UI for this?

**Comment by gorhill** [comment]
Declining this, I don't see any value for the vast majority of users for me to completely rework code that has been stable since 2015. Best left to a specialized blocker to support that kind of finer-grained control, so whoever really wants this is welcome to invest their own time to scratch their own itch.

**Comment by Rudxain** [comment]
@gorhill please close as "Not Planned". The current state is misleading
