### ISSUE TITLE
High generic scriptlets can stop hiding elements by generic cosmetic filters

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2915]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Looked at #2904 I detected bug with skiping hiding elements by ID and class.

```adb
*##+js('set-attr', 'a[href*=".pdf"]', 'download')
*##+js('set-attr', 'img[width][height]:not([loading])', 'loading')
```

On a demo:

```html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="description" content="[add page description]">
    <meta name="keywords" content="[add content keywords]">
    <title>[add page title]</title>
  </head>
  
  <body>
  <p id="Ad-Top">
  visible?
  </p>
  <p id="Ad-Container">
  visible?
  </p>
  <p class="zox-post-ad-wrap yahooads">
  visible?
  <p>
  <AD-TRIPLE-BOX>
  hidden!
  </AD-TRIPLE-BOX>
  </body>
  
</html>
```

By two filters I "killed" 15'498 generic filters from EL (survived only 462 based on Firefox devtools).

https://pastebin.pl/view/de619c53
https://pastebin.pl/view/raw/de619c53

### A specific URL where the issue occurs.

file:///

### Steps to Reproduce

1. Save demo HTML as file and open in Gecko/Servo based browser with MV2 API
2. To uBo put these two scriptlets in my filters panel and save
3. Refresh page many times

### Expected behavior

4 elements are hidden (as long as the repair is trivial).

### Actual behavior

Only last is hidden

### uBO version

1.53.3rc12

### Browser name and version

Firefox 115.4.0 ESR

### Operating System and version

Windows 7 Pro

**Comment by gorhill** [comment]
I get this error in console of uBO:

`
Uncaught (in promise) Error: Type error for parameter contentScriptOptions (Error processing matches.0: Value "*://*./*" must either: be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/) for contentScripts.register.
`

**Comment by krystian3w** [comment]
Works on my side too.

**Comment by gorhill** [comment]
Thanks for catching this before it reached stable.
