### ISSUE TITLE
urlhaus-ag-filter-online.txt - add ^ before $all if filter does not include any slashes

### ISSUE THREAD

**Issue by Hebrew-uBO-User** [uBlockOrigin/uBlock-issues#2922]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/gorhill/uBlock/commit/402e2ebf57

Can the script generating this filter list (`urlhaus-ag-filter-online.txt`) be adjusted:
If a filter does NOT include any `/`s, add `^$all` at the end; else, add `$all`.
This will prevent potential false positives.

Thank you very much for all of your great work!

### A specific URL where the issue occurs.

-

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBO version

-

### Browser name and version

-

### Operating System and version

-

**Comment by stephenhawk8054** [comment]
uBO just fetches the list from `urlhaus`. Better to report to https://gitlab.com/malware-filter/urlhaus-filter ?

**Comment by krystian3w** [comment]
I doubt, https://gitlab.com/malware-filter/urlhaus-filter/-/commit/5821143af1961fbcea59eabaae8ce7e765331f22 = this looks as can't be changed built method in any file.

**Comment by Hebrew-uBO-User** [comment]
@curbengh

@krystian3w 
I doubt.
