### ISSUE TITLE
Logger don't work

### ISSUE THREAD

**Issue by nopnop8** [uBlockOrigin/uBlock-issues#293]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When open the ublock logger you can see nothing
![u](https://user-images.githubusercontent.com/44613459/47728243-dd6c6700-dc55-11e8-9eb2-ba80b54bf932.jpg)

### A specific URL where the issue occurs

https://github.com/
but it happens "everywhere"

### Steps to Reproduce

Open the logger

### Expected behavior:

See in the logger all connection

### Actual behavior:

Yon can't see nothing

### Your environment

* uBlock Origin version: 1.17.2
* Browser Name and version: Tor browser 8.0.3 (based on firefox 60.3.0esr)
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1416505>.

Just slightly resize the logger window.
