### ISSUE TITLE
HTML filtering doesn't work on error page (404)

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2931]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/uBlockOrigin/uAssets/commit/08d2aa20f8da51107551dc6f23d406119335590e#commitcomment-131702236 :

A large number of sites use the  WPCP "copy/select" protection script, so we use HTML filtering on Firefox to address those:

```adb
wikiofcelebs.com##^script[id^="wpcp_"]
```

But HTML filters don't work on pages with `404` status code, example:
`https://wikiofcelebs.com/2022/05/ratedepicz.html`

> [HTML filters will apply only for document fetched successfully, i.e. when HTTP response status code is in the 200 realm.](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters:)

Could you change this intended behavior to cover some other status codes too?

I remember another site which served a `403`(?) code and HTML filters didn't work.

### A specific URL where the issue occurs.

`https://wikiofcelebs.com/2022/05/ratedepicz.html`

**Comment by gwarser** [comment]
I already hit this once when testing some other filters. When you go to `http://example.com/foo` there will be nothing obvious that the page returned `404`, but some filters don't work.

**Comment by gorhill** [comment]
I am pretty there was another issue out there with the same cause: HTML filtering applies only to response status between 200 and 300. 404 is out of the allowed range.

**Comment by krystian3w** [comment]
#942 - 301, 302 & 307 - maybe again browser issue.

**Comment by gorhill** [comment]
Forgot to mention in recent commit that I removed the requirement for the response status. Should work now.

**Comment by gwarser** [comment]
This and original case now works in 1.53.1b7

	! 2023-11-05 http://example.com/foo
	example.com##^[href="https://www.iana.org/domains/example"]
