### ISSUE TITLE
[Enhancement] List applied cosmetic filters and rules

### ISSUE THREAD

**Issue by Marco-Sulla** [uBlockOrigin/uBlock-issues#2933]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I'd like to have a section that lists the name of cosmetic filters applied to the page and the rules applied, in the verbose display

### A specific URL where the issue occurs.

https://www.google.com

### Steps to Reproduce

1. click on uBlock
2. see the modal

### Expected behavior

In the modal could be a list of cosmetic rules applied

### Actual behavior

No rule is displayed

### uBO version

1.52.2

### Browser name and version

Firefox 117.0.1

### Operating System and version

Lubuntu 22.04.3

**Comment by mapx-** [comment]
uBO has already the logger, just use it => https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by iam-py-test** [comment]
The logger will show all comedic filters applied: https://github.com/gorhill/uBlock/wiki/The-logger
Additionally, you can click the chat icon, then expand _Troubleshooting information_ to see such as list.
In my opinion, adding such information to the popup would take up a lot of space, though I suppose it could be hidden by default and then expanded (like the dynamic filtering)

**Comment by Marco-Sulla** [comment]
@mapx- Thank you, but it will be easier to see in the pane.
