### ISSUE TITLE
[Enhancement] Possibility to add a rule to exclude a single cosmetic filter for a site

### ISSUE THREAD

**Issue by Marco-Sulla** [uBlockOrigin/uBlock-issues#2934]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

It could be useful to have a way to disable a single cosmetic filter for a site, and not all the cosmetic filters

### A specific URL where the issue occurs.

https://www.google.com

### Steps to Reproduce

1. open the pane

### Expected behavior

See in advanced view a way to exclude a single cosmetic filter

### Actual behavior

You have to exclude all cosmetic filters

### Configuration

{
  "timeStamp": 1699118903170,
  "version": "1.52.2",
  "userSettings": {
    "advancedUserEnabled": true,
    "collapseBlocked": false,
    "externalLists": "https://easylist-downloads.adblockplus.org/exceptionrules.txt\nhttps://filters.adtidy.org/extension/ublock/filters/14.txt\nhttps://malware-filter.gitlab.io/pup-filter/pup-filter.txt\nhttps://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt\nhttps://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt\nhttps://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt\nhttps://winhelp2002.mvps.org/hosts.txt",
    "firewallPaneMinimized": false,
    "importedLists": [
      "https://easylist-downloads.adblockplus.org/exceptionrules.txt",
      "https://filters.adtidy.org/extension/ublock/filters/14.txt",
      "https://malware-filter.gitlab.io/pup-filter/pup-filter.txt",
      "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
      "https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt",
      "https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt",
      "https://winhelp2002.mvps.org/hosts.txt"
    ],
    "popupPanelSections": 31,
    "prefetchingDisabled": false,
    "webrtcIPAddressHidden": true
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-unbreak",
    "adguard-generic",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "block-lan",
    "easyprivacy",
    "urlhaus-1",
    "curben-phishing",
    "dpollock-0",
    "plowe-0",
    "adguard-other-annoyances",
    "adguard-popup-overlays",
    "adguard-social",
    "adguard-widgets",
    "adguard-cookies",
    "ublock-cookies-adguard",
    "easylist-chat",
    "easylist-newsletters",
    "easylist-notifications",
    "easylist-annoyances",
    "fanboy-social",
    "fanboy-cookiemonster",
    "ublock-cookies-easylist",
    "fanboy-thirdparty_social",
    "ITA-0",
    "https://malware-filter.gitlab.io/pup-filter/pup-filter.txt"
  ],
  "hiddenSettings": {},
  "whitelist": [
    *** censored ***
  ],
  "dynamicFilteringString": *** censored ***,
  "urlFilteringString": "",
  "hostnameSwitchesString": *** censored ***,
  "userFilters": ""
}

**Comment by iam-py-test** [comment]
This can be done in the logger

**Comment by u-RraaLL** [comment]
https://github.com/gorhill/uBlock/wiki/DOM-inspector

Please don't spam new issues.

**Comment by Marco-Sulla** [comment]
@iam-py-test Thank you, but anyway it's quite more difficult to do. An helper in the pane will be easier.
