### ISSUE TITLE
Inconsistent searching behaviour in the Code Viewer

### ISSUE THREAD

**Issue by partingscientist** [uBlockOrigin/uBlock-issues#2935]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The search functionality in the Code Viewer will show the number of lines that match the searched word, yet the arrow button will iterate through each matching word in the source code instead of line.

### A specific URL where the issue occurs.

https://github.com

### Steps to Reproduce

1. On advanced settings, set `filterAuthorMode` to `true`.
2. Open https://github.com.
3. Right click on the background `>` hover over `uBlock Origin` `>` click on `View source code..`.
4. Using the search functionality, search for the word `flex`. Notice the number of matches shown.
5. Iterate through the matched words using the arrow button. Notice the behaviour.

### Expected behavior

Either
- the search returns the number of words matching the search word and the arrow button iterates through each matching word, or
- the search returns the number of lines in which the word is found and the arrow button iterates through each matching line.

### Actual behavior

The search returns the number of lines that match the searched word, yet the arrow button will iterate through each matching word in the source code instead of line.

### uBO version

1.53.1b3

### Browser name and version

Firefox 119.0

### Operating System and version

Windows 10

**Comment by gwarser** [comment]
- My filters
- type 
```
foo foo
foo
```
- search for `foo`

Two results reported, clicking the arrows cycles through all three results.

This is the implementation https://github.com/gorhill/ublock/commit/23332400f5f16de1a54265dd7bb110ea7e1da57c ?

It's good when looking at very long lines, IMO. Can be said it returns number of filters.

**Comment by gorhill** [comment]
It's not a given that other people would agree with the behavior of skipping other occurrence on the same line, so I prefer to decline changing the current behavior.

**Comment by gorhill** [comment]
I am open to suggestion to improve the visual of currently selected text, it must work in both light and dark theme.
