### ISSUE TITLE
Please include the release notes before publishing

### ISSUE THREAD

**Issue by williamdes** [uBlockOrigin/uBlock-issues#2937]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

![Screenshot_2023-11-05-19-04-37-592_com fsck k9](https://github.com/uBlockOrigin/uBlock-issues/assets/7784660/488c034d-5d21-4217-b4d9-fda08c69fc62)

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

Have the release notes in my email instead of having to open them to read the contents 

### Actual behavior

No contents because it was published before adding the notes

### uBO version

x

### Browser name and version

x

### Operating System and version

Debian

**Comment by gorhill** [comment]
The release is created through GitHub actions, I add the release notes manually, so it's not possible for me to do what you are asking.

**Comment by gorhill** [comment]
Alright, I am going to try something -- add the release notes into a separate text-based file, and have the github actions bot pull them from that file.

**Comment by williamdes** [comment]
> Alright, I am going to try something -- add the release notes into a separate text-based file, and have the github actions bot pull them from that file.

Thanks

Yeah that's probably one way

https://github.com/gorhill/uBlock/blob/1.53.1b6/.github/workflows/mv3.yml#L40

With the `bodyFile` option of https://github.com/ncipollo/release-action
Another easier is to use `draft: true` and continue what I assume you did: manually edit
And then hit publish

**Comment by gorhill** [comment]
I had to create a new dev build release, and from here it looks like this worked?

**Comment by williamdes** [comment]
Lovely, thank you so much!!!! 
Some delicious tech news directly in the inbox 

![Screenshot_2023-11-05-21-18-18-405_com fsck k9](https://github.com/uBlockOrigin/uBlock-issues/assets/7784660/cb9b9bb0-8b8f-4720-986b-7ce3ef1a7e27)

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/17olpld/1531b7_new_dev_build_500_error/

Version variable is not expanded in the link to Firefox build 

     https://github.com/gorhill/uBlock/releases/download/%version%/uBlock0_%version%.firefox.signed.xpi

**Comment by gwarser** [comment]
The `g` flag is missing?

**Comment by gorhill** [comment]
Yes, found out about this: https://github.com/gorhill/uBlock/commit/6027abfe123758ef01ba674e701a3adc2051ac9c
