### ISSUE TITLE
Frequent random extension crashes after updating to Chrome Version 72.0.3595.2

### ISSUE THREAD

**Issue by CollinChaffin** [uBlockOrigin/uBlock-issues#294]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I've been using ublock for many years and always run DEV ver of Chrome (I am a DEV myself) and since the update to `Version 72.0.3595.2 (Official Build) dev (64-bit)` a few days ago, ublock origin is the only extension to very frequently and apparently randomly (even sitting idle with Chrome in background) pop open this notification:

![snag_11-1-2018_01-29-25](https://user-images.githubusercontent.com/9301483/47836731-3268c400-dda1-11e8-89a3-a13b0d52ccc0.png)

Which then requires clicking or manually reloading the extension.  I will be happy to help debug but uncertain which/if any specific crash logs exist.

### A specific URL where the issue occurs

Unknown even happens idle I believe it last happened with only a google search page open, but note this is happening suddenly on multiple machines (all only after they updated to this specific Chrome DEV version) that all obviously have different configs/profiles/etc.  Only the Chrome version appears to be common.

### Steps to Reproduce

1. Open Chrome
2. Wait a random amount of time until receiving the extension crash message

### Expected behavior:

No crash.

### Actual behavior:

![snag_11-1-2018_01-29-25](https://user-images.githubusercontent.com/9301483/47836890-cb97da80-dda1-11e8-9965-d6cd4d106a48.png)

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version:  Chrome Version 72.0.3595.2 (Official Build) dev (64-bit)
* Operating System and version:  Windows 7 x64

**Comment by uBlock-user** [comment]
Dev and Canary builds have regressions that are causing the crash, happens with uMatrix too. Downgrade to Stable or Beta builds.

**Comment by CollinChaffin** [comment]
Unfortunately that is not an option for me and probably many others that require at least DEV builds.  Any idea/word on the cause and do you know (I'm searching now again as well but did not see it) if there is a specific open Chromium issue on this I can join?

Thanks!

**Comment by gorhill** [comment]
If you start Chrome from the command line, does it leave information in the shell after uBO crashes?

**Comment by rprimus** [comment]
Thu Nov  1 13:39:54 GMT 2018

Environment:
OS:  macOS 10.14.1 18B75
Chrome: Version 72.0.3595.2 (Official Build) dev (64-bit)
<hr>

I've also experienced the random crashes when using the dev version (`1.17.3.4`).
I then started using the stable version (`1.17.0`) - which also randomly crashes.

Here's the output from the command line:
```
#
# Fatal error in , line 0
# Check failed: size <= kMaxRegularHeapObjectSize.
#
#
#
#FailureMessage Object: 0x7ffeee43cca00   Google Chrome Framework             0x00000001049d99bf ChromeMain + 41792447
1   Google Chrome Framework             0x00000001079c891b ChromeMain + 92054299
2   Google Chrome Framework             0x00000001079b8ef5 ChromeMain + 91990261
3   Google Chrome Framework             0x0000000103e04258 ChromeMain + 29383768
4   Google Chrome Framework             0x0000000104089eeb ChromeMain + 32028907
5   Google Chrome Framework             0x000000010405de7c ChromeMain + 31848572
```

**Comment by gorhill** [comment]
Best is to report to Chromium devs, along with a crash report. uBO is HTML/CSS/JS, and since it works fine on stable version of Chromium, this suggest a regression in dev build of Chromium, which only Chromium devs can address.

**Comment by CollinChaffin** [comment]
Yes but I reported it here knowing it most likely is Chromium related and hoping you either had a workaround or already were or might want to help get involved as your report/involvement as author of such a major extension.

Let's remember that if we all just ignore it, it's not like the DEV version now crashing is just a pipe-dream "maybe"......it's an already-implemented reality that somehow has already survived through CANARY and WILL become the stable very soon and if we all wait until then.....well then we're scrambling to get a Chromium DEV even assigned let alone tracing and implementing the fix and in my experience that itself may become the real pipe dream.  And while all that is happening, the "appearance" right or wrong to most of the masses seeing that cute little "uBlock has crashed" will leave them not knowing any better than to wrongfully complain about uBlock or worse yet all come here to open issues on it. :)

And you are absolutely correct I have now begun to see similar crashing with a few other extensions.  I am baffled how as bad as it is that this issue made it this far past CANARY and that there is not an active open issue on it....unless my search skills are just off today which is why I asked if you happened to have the issue # and hoping you had already complained. :wink:

**Comment by uBlock-user** [comment]
Just an FYI - Canary builds are not auto-tested by Google build bots, neither manually tested via simulations, so browser crashes and extensions breakage should be expected and Google does [warn](http://www.chromium.org/getting-involved/dev-channel/) about this on their chromium page too. Dev builds on the other hand do get tested, but google warns to expect bugs. The reason I don't report these things because they always have get patched in the next versions of dev and canary. 

So just beware, these kind of things **will** occur in the future builds too as these builds are only meant for testing and not meant to be used for everyday browsing. You could report it, but in the long game it's a pain in the ass and crashes occurr every few new builds in Canary and dev. Sometimes it takes time and goes on for few builds and sometimes it gets quickly patched in the next build.

**Comment by CollinChaffin** [comment]
Thanks for replying so quickly.  FYI, I opened this issue and would urge anyone else experiencing this to comment and star the issue as well:

https://bugs.chromium.org/p/chromium/issues/detail?id=901010

**Comment by uBlock-user** [comment]
Btw, I don't experience this issue on 32 bit build of `72.0.3594.0` so you use 32 bit builds until this gets fixed.

**Comment by CollinChaffin** [comment]
FYI, not sure if you looked but others already also chimed in to provide detail and looks like it just made it into a revert canary commit has to do with fastpath array they were able to see ublock crashing here is the revert commit:

https://chromium.googlesource.com/v8/v8/+/f88a1d87d681adfb80be22c2f2af54852df7f92c

**Comment by gorhill** [comment]
From their findings, most likely the crash was occurring when uBO was trying to save a selfie -- as this causes `Array.from` to be called with large `Set` (the more filter lists, the larger). A selfie is generated after a few minutes the filter lists have reloaded (due to update, changes, etc.)
