### ISSUE TITLE
[Feature Request] Allow admins to hide power button to prevent its use

### ISSUE THREAD

**Issue by Skinflint** [uBlockOrigin/uBlock-issues#2940]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Would it be possible to add an option in the disabledPopupPanelParts settings pushed by Chrome Management to disable/hide the stickyTools Div in the popup like you do with the 4 other options/divs in that setting? 

### A specific URL where the issue occurs.

popup panel

### Steps to Reproduce

Open the popup panel. See the big power button to enabled and disable the extension. Set the CSS to hidden for the stickyTools div to hide it. Remove the CSS to show the button again.

### Expected behavior

With the addition of the setting, set the CSS to hide that div. Without that setting, keep the div as visible.

### Actual behavior

No current option to hide the button.

### uBO version

1.52.2

### Browser name and version

Chrome 118

### Operating System and version

ChromeOS 118

**Comment by Skinflint** [comment]
We are using the JSON file in Google Workspace Admin Console to set some adminSettings as well as the disabledPopupPanelParts. Here is a snippet of the current JSON:
`{
	"adminSettings": { "Value": "{\"userSettings\":{\"advancedUserEnabled\":false,\"autoUpdate\":true,\"contextMenuEnabled\":false,\"dynamicFilteringEnabled\":false,\"popupPanelSections\":0}}" },
	"disabledPopupPanelParts": { "Value": ["basicTools","extraTools","overviewPane"] }
}`

**Comment by gorhill** [comment]
I don't understand the issue being reported. When I add the following as a policy:

```json
{
  "3rdparty": {
    "extensions": {
      "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
        "disabledPopupPanelParts": [
          "basicTools",
          "extraTools",
          "overviewPane"
        ]
      }
    }
  }
}
```

I don't see anything unexpected in the popup panel:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/404ee340-b1d2-4c22-b3b7-0a7f1b7b1c40)

If I toggle the power button:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/65eae1d3-30e6-4f07-a737-91d5160275ad)

**Comment by gorhill** [comment]
Ok you want the reload button to **not** show up?

**Comment by Skinflint** [comment]
My apologies for not being more clear. This isn't a bug that needs to be fixed, but a feature request. I apologize if there was a different way to submit a feature request over a bug, but I was hoping to add something like the following to hide the button.

<img width="188" alt="ublockOrigin" src="https://github.com/uBlockOrigin/uBlock-issues/assets/12315962/48cf9740-2f51-4022-b7b9-04af097af6e6">

`{
  "3rdparty": {
    "extensions": {
      "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
        "disabledPopupPanelParts": [
          "basicTools",
          "extraTools",
          "overviewPane",
          "stickyTools" 
        ]
      }
    }
  }
}`

**Comment by gorhill** [comment]
If the power button area is hidden, this would cause issues if `extraTools` is left visible, as these need the padlock/eraser/reload tools as part of their functionality, and these tools sit in the power button area.

**Comment by Skinflint** [comment]
That makes sense. In my use case I wasn't looking at the extraTools and it's dependencies since I hid them. In order to get this to work without requiring extraTools be hidden, the option couldn't hide the entire div with ID "stickyTools" just like you mentioned. It could set the div with ID "switch" to "display: none", as well as possibly changing the CSS for the class "rulesetTools" from "flex-direction: column" to "flex-direction: row" to remove some of the negative space. However, that last change isn't a requirement as the column view still looks okay when the buttons are shown.

You could also change the CSS for [id] under the class "rulesetTools" from "visibility: hidden" to "display: none" in order to completely remove the negative space. Though, I assume that change would require areas of the code to start using "display: none" and "display: inline-flex" instead of "visibility: hidden" and "visibility: visible" for those buttons.

All that said, thank you for a great extension and for being responsive on the issue tracker.

**Comment by iam-py-test** [comment]
Dumb idea (and maybe someone already suggested this, sorry if that's the case), but what if the power button was present and correctly displayed if uBo was enabled/disabled, but could not be interacted with. I know that would be extra work for little benefit, though.
Thanks

**Comment by gwarser** [comment]
uiStyles pointer-events:none;

**Comment by u-RraaLL** [comment]
Can probably be broken by opening popup in a new window and using inspect element. But most people won't know about that.

**Comment by gorhill** [comment]
> The whole popup should not respond to mouse cursor.

Good idea. I am going to go with this, this free me from working on something I am not convinced is worth it.

**Comment by gwarser** [comment]
This affect dashboard too.

**Comment by SaumayTyagi** [comment]
![Screenshot (735)](https://github.com/user-attachments/assets/caebacf7-a7d6-49e4-a063-8387868df264)

how to do this please help.

**Comment by gwarser** [comment]
@SaumayTyagi follow the links in my post above, or explain more your situation.

**Comment by SaumayTyagi** [comment]
like where to write this code(in registry)(pointer-events:none) this code .please can you tell detailed steps)

**Comment by SaumayTyagi** [comment]
![Screenshot (736)](https://github.com/user-attachments/assets/d48b2316-c4f5-46f8-9624-80125a9d992f)
in this.

**Comment by SaumayTyagi** [comment]
we have to write here ? if yes how and what to write?

**Comment by gwarser** [comment]
If you have access to this computer, then just go to uBO advanced settings and copy-paste it there.

https://github.com/gorhill/uBlock/wiki/Advanced-settings

**Comment by SaumayTyagi** [comment]
thanks . done. thank you very much .

**Comment by SaumayTyagi** [comment]
but how to revert it
i am not able to revert

**Comment by SaumayTyagi** [comment]
@gwarser please tell how to revert it .

**Comment by gorhill** [comment]
Please just read the documentation carefully, we gave you the link:

> If you want to reset a specific setting to its default value, just delete the value, uBO will fill the missing value with the default one.

**Comment by gorhill** [comment]
Seven notifications in less than an hour for a question that was already answer here and in the documentation, locking the issue.

**Comment by gwarser** [comment]
@SaumayTyagi you will need to use developer tools to remove the pointer events style from body or just reinstall uBO.
