### ISSUE TITLE
i'm getting twitch ads now

### ISSUE THREAD

**Issue by hxsggsz** [uBlockOrigin/uBlock-issues#2941]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

since last day i start to get twitch ads, did this extension stop to work on twitch? 

### A specific URL where the issue occurs.

https://www.twitch.tv/

### Steps to Reproduce

open twitch
click on a streamer 
get a ad in the face

### Expected behavior

see a twitch live stream with no ads

### Actual behavior

see a twitch live stream with ads

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105844
 cosmetic: 44055
 scriptlet: 19224
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 72196-15, 5d.23h.43m
  easyprivacy: 32853-64, 3d.20h.44m
  plowe-0: 3727-1073, 12d.37m
  spa-1: 5690-66, 3d.20h.45m
  ublock-badware: 7421-138, 1d.21h.36m
  ublock-filters: 35144-168, 1d.21h.35m
  ublock-privacy: 659-6, 5d.10m
  ublock-quick-fixes: 139-58, 5h.36m
  ublock-unbreak: 2131-33, 1d.21h.34m
  urlhaus-1: 10940-0, now
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 685 ms (selfie)
 maxAssetCacheWait: 172 ms
```
</details>

**Comment by mapx-** [comment]
duplicate https://github.com/uBlockOrigin/uAssets/issues/5184
