### ISSUE TITLE
Add additional flag to the Persian list

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2946]
Since @DandelionSprout had used his "special privilege" of being a past-contributor, I couldn't reply on [this pull request](https://github.com/gorhill/uBlock/pull/3904).

I think it's best to make an issue under `uBlockOrigin/uBlock-issues` to allow for an open discussion.

That PR completely ignores that the Persian list also supports Pashto sites from Afghanistan, so I propose this change:
https://github.com/gorhill/uBlock/commit/2b9af08fd7916cd58e61f69f8917095a6f2cc905
https://github.com/gorhill/uBlock/commit/63f94bfe1a9e73789f12bf87155d8108260fd740

**Comment by gorhill** [comment]
I am going to revert the `.tj` one. There are no `.af` in your list, and only 8 instances of `.tj` in the list, not enough to justify the change. I set a rule of at least 5% TLD before considering adding a flag [in another discussion](https://github.com/EasyDutch-uBO/EasyDutch/issues/92#issuecomment-1799538277).

**Comment by DandelionSprout** [comment]
I honest-to-gods didn't know that non-contributors weren't allowed to reply to PRs there. If it's needed for me to apologise for that, I give my apologies.

**Comment by gorhill** [comment]
You are you apologizing for something that's not your doing.

It takes only one accepted PR to become [contributor](https://github.com/gorhill/uBlock/graphs/contributors), it's not me specifically picking people, I just limit the repo "to prior contributors" in moderation settings to avoid [that sort of interaction](https://github.com/gorhill/uBlock/pull/3903).

**Comment by DandelionSprout** [comment]
Slack has scared me in the past month, and I've been *terrified* of going back there. Far too much gatekeeping of channels.
