### ISSUE TITLE
Ublock origin and youtube script doesnt match

### ISSUE THREAD

**Issue by Runningshuh** [uBlockOrigin/uBlock-issues#2949]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Youtube is catching my ublock origin adblocker. And the logo on https://drhyperion451.github.io/does-uBO-bypass-yt/ is red.
the ublock origin code is "10234ela" and the youtube code is "ac9e22c0"

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=1FQvRZg3bcg

### Steps to Reproduce

I cannot open any youtube video with ublock origin ad blocker enabled. 

### Expected behavior

Being able to watch videos without ads

### Actual behavior

The stage 4 youtube blocker

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104289
 cosmetic: 43444
 scriptlet: 18871
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 75175-16, 29m
  easyprivacy: 32854-64, 29m
  plowe-0: 3722-1074, 29m
  ublock-badware: 7435-135, 5m
  ublock-filters: 35231-151, 5m
  ublock-privacy: 663-5, 5m
  ublock-quick-fixes: 153-90, now
  ublock-unbreak: 2135-32, 5m
  urlhaus-1: 10950-0, 28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 729 ms
 maxAssetCacheWait: 342 ms
```
</details>

**Comment by Runningshuh** [comment]
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 104289
 cosmetic: 43444
 scriptlet: 18871
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 75175-16, 29m
  easyprivacy: 32854-64, 29m
  plowe-0: 3722-1074, 29m
  ublock-badware: 7435-135, 5m
  ublock-filters: 35231-151, 5m
  ublock-privacy: 663-5, 5m
  ublock-quick-fixes: 153-90, now
  ublock-unbreak: 2135-32, 5m
  urlhaus-1: 10950-0, 28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 729 ms
 maxAssetCacheWait: 342 ms

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/19976
