### ISSUE TITLE
Block Element doesn't work on minds.com

### ISSUE THREAD

**Issue by Betsy25** [uBlockOrigin/uBlock-issues#295]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
"Block Element" does not work on minds.com, neither using the Element picker from the main menu, nor from the context menu.
### A specific URL where the issue occurs
[https://www.minds.com/newsfeed/subscribed](https://www.minds.com/newsfeed/subscribed)

### Steps to Reproduce
1. Have an account on minds.com, and go to the link above.
2. Try to block an element

### Expected behavior:
Element picker should kick in when requested & Block Element is requested from context menu.
### Actual behavior:
Nothing happens.

### Your environment
* uBlock Origin version: 1.17.3b4
* Browser Name and version: Firefox Stable v63 & Firefox Nightly v65
* Operating System and version: Win7 x64

**Comment by uBlock-user** [comment]
> Nothing happens.

did you disable cosmetic filtering ? check my rules tab.

**Comment by Betsy25** [comment]
Ouch, yep for some reason I had disabled it :/
Thanks for pointing out @uBlock-user.

**Comment by uBlock-user** [comment]
Duplicate of gorhill/uBlock#3212
