### ISSUE TITLE
Ublock Origin interfering with Bitwarden in Opera and Firefox

### ISSUE THREAD

**Issue by excelsior3dart** [uBlockOrigin/uBlock-issues#2951]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have been in touch with Bitwarden for a few days now. We tried everything to solve the problem with Ublock Origin switched on. But nothing has worked until I disabled Ublock. I can't remember exactly when it started but maybe a week or 10 days. 

When I wanted to log in into any page using Bitwarden, the window will pop up, I enter the master password and I just couldn't click on the word "Unlock". Hovering with the cursor over the word the cursor was an arrow and when I slowly moved the cursor further down I found a small space where it turned into a hand and I was able to click. Also autofill wasn't working despite being enabled in Bitwarden.

I then tried it in Chrome, that worked fine,

I also tried it in Firefox, and there it worked one time and the not the next. Very temperamental. But because this is my last resort browser I wasn't that bothered.
I was told to uninstall Bitwarden, clean all the remaining files and reinstall it. No change.

I was told to try a clean install of Opera, which I did and again nothing changed. Same issues.

I then whitelisted everything I could find about Bitwarden in Ublock Origin. Which didn't help either.
I then switched Ublock Origin off on trusted sites and finally autofill was working again. But not the Unlock. I still had to click some 2mm below the word.
Last thing I tried was disabling Ublock Origin and everything was back to normal in Opera.

I tried the same in Firefox and there it works again fine too.

I don't know what have caused it, but I have the latest version of Ublock Origin installed. I am running the latest versions of all my browsers and that of Bitwarden.
I really don't know why Ublock Origin has to interfere with Bitwarden at all. It's the best password manager out there. 

I have explained it the best I could. I am autistic and may sound complicated.

PS: Because Opera is my main browser I haven't looked too much into the issues with Firefox, but I noticed that I had to click several times on the Unlock button to get a reaction. So something is interfering. When I switch Ublock Origin off it works fine.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

Open any website to log in

Click on Bitwarden in the toolbar or right click on username or password space to autofill login 

Enter master password

Click on Unlock and login details should fill in automatically

### Expected behavior

Should be able click on the word Unlock to unlock vault and login details should fill automatically

### Actual behavior

Can't click on the word Unlock to login in and autofill not working unless Ublock is turned off on a website.
I marked in the picture the space I am actually able click on to unlock the vault. This weird behaviour only stops if I disable Ublock Origin fully

https://github.com/uBlockOrigin/uBlock-issues/assets/150437190/fb7afeeb-761d-466b-b7a7-c469d7c868da

### uBO version

1.53.0

### Browser name and version

Opera One(version: 104.0.4944.36)  Firefox 119.0.1

### Operating System and version

Windows 10 Pro 22H2 OS build 19045.3636

**Comment by gorhill** [comment]
The browser doesn't allow extensions to interfere with each others unless they are in a context which not an extension. From the description, it sound like a filter issue, you will need to disclose your issue as if it was a filter issue, i.e. all the troubleshooting information. Also, use the logger to find out what uBO is doing when you reproduce the issue.

**Comment by excelsior3dart** [comment]
OK, when it started I have not added any filters to uBO. There were just those that were added originally.
I only added afterwards Bitwarden to the whitelist hoping it would leave it alone.

So it CAN'T be a filter issue.

On 10/11/2023 14:56:27, Raymond Hill ***@***.***> wrote:
The browser doesn't allow extensions to interfere with each others unless they are in a context which not an extension. From the description, it sound like a filter issue, you will need to disclose your issue as if it was a filter issue, i.e. all the troubleshooting information. Also, use the logger to find out what uBO is doing when you reproduce the issue.

**Comment by stephenhawk8054** [comment]
`filter issue` can be somewhere in other lists. Use uBO logger to check what's blocked there.

**Comment by excelsior3dart** [comment]
Is it this?
<details><summary>Logger output</summary>

```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/shop.applegreencottage.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/ao.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.animicausa.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/amigurumi.today/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.amazon.co.uk/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.alwaysknittingandsewing.co.uk/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.allfreesewing.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.allfreeknitting.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.allfreecrochetafghanpatterns.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.aldi.co.uk/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.adobe.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/accounts.google.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/account.samsung.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.abakhan.co.uk/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/192.168.1.1/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/www.8seasons.com/icon.png
```
```
+21
vault.bitwarden.com
3
get
image
https://icons.bitwarden.net/3dshards.com/icon.png
```
```
+20
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/407.3965054f91d870070000.js
```
```
+20
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/encrypt-worker.31384e9d7a58fe8edb87.js
```
```
+20
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/config
```
```
+20
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/sync?excludeDomains=true
```
```
+19
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/config
```
```
+19
vault.bitwarden.com
1
get
websocket
wss://notifications.bitwarden.com/hub?access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkJDMzZDMjE0REI0OEYyMzVCNzdEQTNGMTcyMEMxQTM1QTk2MkVBNDNSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6InZEYkNGTnRJOGpXM2ZhUHhjZ3dhTmFsaTZrTSJ9.eyJuYmYiOjE2OTk2MzI1MjEsImV4cCI6MTY5OTYzNjEyMSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5iaXR3YXJkZW4uY29tIiwiY2xpZW50X2lkIjoid2ViIiwic3ViIjoiNDA2YzdlMjAtYmVhNi00MzMxLTkwZDItYWY5NjAxMzk4ZGUyIiwiYXV0aF90aW1lIjoxNjk5NjMyNTIxLCJpZHAiOiJiaXR3YXJkZW4iLCJwcmVtaXVtIjp0cnVlLCJlbWFpbCI6ImFubmllZ3JpZmZpdGhzOTQzQGJ0aW50ZXJuZXQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInNzdGFtcCI6IjAzN2I2NjYzLTU0MGMtNDgxYi1iMTQ4LTM0MzMxNjNkMWNkNyIsIm5hbWUiOiJBbm5ldHRlIiwiZGV2aWNlIjoiOGQ2Mjc0NWEtYzFkMC00ZThjLWE0OTAtMWNiODdjNmEwZDA5IiwianRpIjoiOTM5NUM3NTEwMjE3OEQ1NzY5OTJDQ0FEQ0RFRjczM0YiLCJpYXQiOjE2OTk2MzI1MjEsInNjb3BlIjpbImFwaSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJBcHBsaWNhdGlvbiJdfQ.UckkY1CA5r4SEiBNVPfgnE3cmd6t7xZod2EPAztKOg9TdbQSTh3yD08Kpk_i5btdiEHHP6vGPEME6mDGYq1Q69vtZvTJDgHHVAwcxDog4AgiWV6fYr-LDtUfweVHI8JJyEmV3XXk2qYHSzyGCUxt-bkTuQJvzslNHCCgZfjRhqJiGGDyGZlMjcuAOiZk2dLfE9WcKqCcqyuy9ee_WNynYTc5DPO0C6k2aS725fqxZkiFKv16AD6TCpZjWxYMRKKEdZRjzXVrSCRkOIcAAIsEwtAmJzRaJ6-tO-NbqcnBkuvlvZrF-nk2qFXQ2RqV4SzT9otIBiTjB9OL-9Fu_d8CHr2JYSGdRIpu4usJzfYeh9ijifn4F9SHWnLIW-jfPckydaK6y4jHbhjV6eISmGM3AlCWvn6tRzWsVMDlt12Bt2q0EBnnoF_tx1nFI8N-eTHRQbvsYGH4Ej85ALCBnELZ7Oq9YKplTDVSdqZuKHfNFxPfP9u4YfhuTPashaiNCOrvR3BVffLkxlD0p0Tsa8xTQUxZ9bCZdWAV-bAKyAoqt1SapnH5_Iav9pwNBW8gcGfOdDgn0PBDdy-4BAM6mQ00gVhk9YAnPx9BuKEOL4auh-ZBPDNiQalbPWWpQbJ6SXjouTAvO3HG5q9eo69fuG0pj42RxNSYEYF1fRGjK0b7Sak
```
```
+19
vault.bitwarden.com
1
post
xhr
https://vault.bitwarden.com/identity/connect/token
```
```
+19
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/config
```
```
+17
vault.bitwarden.com
1
post
xhr
https://vault.bitwarden.com/identity/connect/token
```
```
+17
vault.bitwarden.com
1
post
xhr
https://vault.bitwarden.com/identity/accounts/prelogin
```
```
+16
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/devices/knowndevice
```
```
+14
vault.bitwarden.com
1
get
font
https://vault.bitwarden.com/fonts/Open_Sans-normal-700.a39de6b1b80c7f21cf88.woff
```
```
+14
vault.bitwarden.com
1
get
font
https://vault.bitwarden.com/fonts/Open_Sans-normal-600.7f2861051b34a8ecd9f2.woff
```
```
+14
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/api/config
```
```
+14
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/locales/en/messages.json?cache=u29og
```
```
+14
vault.bitwarden.com
1
get
other
https://vault.bitwarden.com/70501c97b33df95adb32.json
```
```
+14
vault.bitwarden.com
1
get
xhr
https://vault.bitwarden.com/locales/en_GB/messages.json?cache=u29og
```
```
+14
vault.bitwarden.com
1
get
image
***@***.***
```
```
+14
vault.bitwarden.com
1
get
font
https://vault.bitwarden.com/fonts/Open_Sans-normal-400.8465030b62273715c99d.woff
```
```
+14
vault.bitwarden.com
1
get
font
https://vault.bitwarden.com/fonts/bwi-font.f7a43f81d823e54532d4.ttf
```
```
+14
vault.bitwarden.com
1
get
image
***@***.***
```
```
+14
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/app/main.70ecfbb8880b442de563.js
```
```
+14
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/app/vendor.765af52ce95db061173c.js
```
```
+14
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/app/polyfills.4275a7f2798b637a6613.js
```
```
+14
vault.bitwarden.com
1
get
css
https://vault.bitwarden.com/app/main.d66bd5b758b5070db480.css
```
```
+14
vault.bitwarden.com
1
get
script
https://vault.bitwarden.com/theme_head.1df11f603fda400762b7.js
```
```
+13
whitelisted
++
vault.bitwarden.com
1
get
doc
https://vault.bitwarden.com/#/vault
```
```
+13
https://vault.bitwarden.com/#/vault
```
```
+0
kccohkcpppjjkkjppopfnflnebibpida.chrome-extension-scheme
0,3
get
xhr
https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt
```
</details>


On 10/11/2023 16:03:01, stephenhawk8054 ***@***.***> wrote:
filter issue can be somewhere in other lists. Use uBO logger to check what's blocked there.

**Comment by gorhill** [comment]
> So it CAN'T be a filter issue.

We are going to be the one making that determination. Hence why you need to come forward with troubleshooting information when you reproduce the issue:

Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by gorhill** [comment]
I looked at that Bitwarden floating window as seen in your screenshot, and it's an extension context, and the browser forbid extensions to interfere which each other, uBO is not allowed to be injected into Bitwarden's context, and vice versa.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/65a2a337-4806-4fdf-8858-0b96c28c257b)

I happened to have a Bitwarden account which I forgot I had. Once I tried to log in, I was presented with hcaptcha to solve, and once I solved this, I could access without issue. So I suspect you modified uBOś default configuration in such a way that hCaptcha is being interfered with -- it works fine with default lists/settings.

**Comment by umut-nb0** [comment]
@excelsior3dart 

> Also autofill wasn't working despite being enabled in Bitwarden.

Autofill is a known Bitwarden issue. Bitwarden team is aware of this issue and they will fix it.
https://github.com/bitwarden/clients/issues/6832

**Comment by excelsior3dart** [comment]
I have whitelisted hcaptcha and since I am opening bitwarden from the toolbar it works again. 
But it shouldn't interfere when I right-click on the login and get a popup either. Because it never used to interfere before. I don't know what has changed. I didn't change anything from my side.
Anyway, it works

On 10/11/2023 16:12:22, MasterKia ***@***.***> wrote:
Logger output
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/shop.applegreencottage.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/ao.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.animicausa.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/amigurumi.today/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.amazon.co.uk/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.alwaysknittingandsewing.co.uk/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.allfreesewing.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.allfreeknitting.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.allfreecrochetafghanpatterns.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.aldi.co.uk/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.adobe.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/accounts.google.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/account.samsung.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.abakhan.co.uk/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/192.168.1.1/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/www.8seasons.com/icon.png
+21 vault.bitwarden.com 3 get image https://icons.bitwarden.net/3dshards.com/icon.png
+20 vault.bitwarden.com 1 get script https://vault.bitwarden.com/407.3965054f91d870070000.js
+20 vault.bitwarden.com 1 get script https://vault.bitwarden.com/encrypt-worker.31384e9d7a58fe8edb87.js
+20 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/config
+20 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/sync?excludeDomains=true
+19 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/config
+19 vault.bitwarden.com 1 get websocket wss://notifications.bitwarden.com/hub?access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkJDMzZDMjE0REI0OEYyMzVCNzdEQTNGMTcyMEMxQTM1QTk2MkVBNDNSUzI1NiIsInR5cCI6ImF0K2p3dCIsIng1dCI6InZEYkNGTnRJOGpXM2ZhUHhjZ3dhTmFsaTZrTSJ9.eyJuYmYiOjE2OTk2MzI1MjEsImV4cCI6MTY5OTYzNjEyMSwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5iaXR3YXJkZW4uY29tIiwiY2xpZW50X2lkIjoid2ViIiwic3ViIjoiNDA2YzdlMjAtYmVhNi00MzMxLTkwZDItYWY5NjAxMzk4ZGUyIiwiYXV0aF90aW1lIjoxNjk5NjMyNTIxLCJpZHAiOiJiaXR3YXJkZW4iLCJwcmVtaXVtIjp0cnVlLCJlbWFpbCI6ImFubmllZ3JpZmZpdGhzOTQzQGJ0aW50ZXJuZXQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInNzdGFtcCI6IjAzN2I2NjYzLTU0MGMtNDgxYi1iMTQ4LTM0MzMxNjNkMWNkNyIsIm5hbWUiOiJBbm5ldHRlIiwiZGV2aWNlIjoiOGQ2Mjc0NWEtYzFkMC00ZThjLWE0OTAtMWNiODdjNmEwZDA5IiwianRpIjoiOTM5NUM3NTEwMjE3OEQ1NzY5OTJDQ0FEQ0RFRjczM0YiLCJpYXQiOjE2OTk2MzI1MjEsInNjb3BlIjpbImFwaSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJBcHBsaWNhdGlvbiJdfQ.UckkY1CA5r4SEiBNVPfgnE3cmd6t7xZod2EPAztKOg9TdbQSTh3yD08Kpk_i5btdiEHHP6vGPEME6mDGYq1Q69vtZvTJDgHHVAwcxDog4AgiWV6fYr-LDtUfweVHI8JJyEmV3XXk2qYHSzyGCUxt-bkTuQJvzslNHCCgZfjRhqJiGGDyGZlMjcuAOiZk2dLfE9WcKqCcqyuy9ee_WNynYTc5DPO0C6k2aS725fqxZkiFKv16AD6TCpZjWxYMRKKEdZRjzXVrSCRkOIcAAIsEwtAmJzRaJ6-tO-NbqcnBkuvlvZrF-nk2qFXQ2RqV4SzT9otIBiTjB9OL-9Fu_d8CHr2JYSGdRIpu4usJzfYeh9ijifn4F9SHWnLIW-jfPckydaK6y4jHbhjV6eISmGM3AlCWvn6tRzWsVMDlt12Bt2q0EBnnoF_tx1nFI8N-eTHRQbvsYGH4Ej85ALCBnELZ7Oq9YKplTDVSdqZuKHfNFxPfP9u4YfhuTPashaiNCOrvR3BVffLkxlD0p0Tsa8xTQUxZ9bCZdWAV-bAKyAoqt1SapnH5_Iav9pwNBW8gcGfOdDgn0PBDdy-4BAM6mQ00gVhk9YAnPx9BuKEOL4auh-ZBPDNiQalbPWWpQbJ6SXjouTAvO3HG5q9eo69fuG0pj42RxNSYEYF1fRGjK0b7Sak
+19 vault.bitwarden.com 1 post xhr https://vault.bitwarden.com/identity/connect/token
+19 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/config
+17 vault.bitwarden.com 1 post xhr https://vault.bitwarden.com/identity/connect/token
+17 vault.bitwarden.com 1 post xhr https://vault.bitwarden.com/identity/accounts/prelogin
+16 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/devices/knowndevice
+14 vault.bitwarden.com 1 get font https://vault.bitwarden.com/fonts/Open_Sans-normal-700.a39de6b1b80c7f21cf88.woff
+14 vault.bitwarden.com 1 get font https://vault.bitwarden.com/fonts/Open_Sans-normal-600.7f2861051b34a8ecd9f2.woff
+14 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/api/config
+14 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/locales/en/messages.json?cache=u29og
+14 vault.bitwarden.com 1 get other https://vault.bitwarden.com/70501c97b33df95adb32.json
+14 vault.bitwarden.com 1 get xhr https://vault.bitwarden.com/locales/en_GB/messages.json?cache=u29og
+14 vault.bitwarden.com 1 get image ***@***.***
+14 vault.bitwarden.com 1 get font https://vault.bitwarden.com/fonts/Open_Sans-normal-400.8465030b62273715c99d.woff
+14 vault.bitwarden.com 1 get font https://vault.bitwarden.com/fonts/bwi-font.f7a43f81d823e54532d4.ttf
+14 vault.bitwarden.com 1 get image ***@***.***
+14 vault.bitwarden.com 1 get script https://vault.bitwarden.com/app/main.70ecfbb8880b442de563.js
+14 vault.bitwarden.com 1 get script https://vault.bitwarden.com/app/vendor.765af52ce95db061173c.js
+14 vault.bitwarden.com 1 get script https://vault.bitwarden.com/app/polyfills.4275a7f2798b637a6613.js
+14 vault.bitwarden.com 1 get css https://vault.bitwarden.com/app/main.d66bd5b758b5070db480.css
+14 vault.bitwarden.com 1 get script https://vault.bitwarden.com/theme_head.1df11f603fda400762b7.js
+13 whitelisted ++ vault.bitwarden.com 1 get doc https://vault.bitwarden.com/#/vault
+13 https://vault.bitwarden.com/#/vault
+0 kccohkcpppjjkkjppopfnflnebibpida.chrome-extension-scheme 0,3 get xhr https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt

**Comment by gorhill** [comment]
> whitelisted hcaptcha

Since hCaptcha is not blocked with default lists/settings, it means you did modify uBO's configuration to cause this. If you want to customize uBO to the point where widespread utilities such as hCaptcha are blocked, you will need to investigate on your side more thoroughly filtering issues before reporting here -- uBO offers you all the tools you need to do so.

**Comment by excelsior3dart** [comment]
I haven't changed anything after installation apart from whitelisting ucaptcha and bitwarden.
You can stop trying to help.
IT WORKS AGAIN!

On 11/11/2023 14:07:48, MasterKia ***@***.***> wrote:
Please actually verify what you tick on:
* uBO uses default lists and settings.
