### ISSUE TITLE
Suspend network activity Gets Unticked

### ISSUE THREAD

**Issue by BlazeFTL** [uBlockOrigin/uBlock-issues#2959]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Whenever I Restore ubo backup file `Suspend network activity until all filter lists are loaded`
Gets Unticked

### A specific URL where the issue occurs.

Filter List Page

### Steps to Reproduce

*

### Expected behavior

*

### Actual behavior

*

### uBO version

Latest Dev

### Browser name and version

Misses Browser(Chrome Based) 116.0***

### Operating System and version

Android 13

**Comment by gwarser** [comment]
Default values are not saved in backup. Was it saved in Firefox?

**Comment by BlazeFTL** [comment]
You Mean - Backup Was Created From FireFox Then Restored In Chrome?

**Comment by gorhill** [comment]
By design, as @gwarser pointed out.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Settings/_compare/617a51a2ba50cc014ba73e7ff45337354fafc404...9e48724fddbba58e32b9f917ef431daa928cc3f4
