### ISSUE TITLE
Background filters break dom inspector usage?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#2965]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I see background filters with enabled dom inspector now/again break visibility elements at page.

Elements in body now are under backround ("greyed out"):

<details>

![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/4a22ab9e-9ae0-4035-b704-2486e8a71c69)

</details>

### A specific URL where the issue occurs.

`http://example.org`

### Steps to Reproduce

Check these filters in "My Filters" and open `example.*` page:

```adb
example.*##html > body:style(background: #d5d5d5 !important;)
example.*##html > body:style(background-image: none!important; background-color: #d5d5d5!important;)
```

### Expected behavior

Visibile other elements.

### Actual behavior

Invisibile other elements.

### uBO version

1.53.5rc11

### Browser name and version

Firefox 119.0.1, darkmode

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
Solution to this is same as with <https://github.com/uBlockOrigin/uBlock-issues/issues/1411>.

**Comment by krystian3w** [comment]
But now have confilct with Stock Moz://a addons?

![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/93485575-75ea-4f70-8472-dcaa083b2672)
