### ISSUE TITLE
“云存储”犹如虚设

### ISSUE THREAD

**Issue by Kumiri** [uBlockOrigin/uBlock-issues#297]
每次重装系统后，相对需要重装N多软件。其中“火狐”变数最多！！偶尔掉几个插件（被下架），而uBlock内部有云功能，以为可以省心……可是有些失望，每次火狐的重装，插件的自动重下，uBlock自定义规则也不能幸免的被重置！！

可以先让uBlock 与 火狐ID，绑定后再让使用云存储吗？

我觉的没有一个账号的辅助，“云存储”的实现是非常困难与虚设。
希望uBlock可以真真的战胜老牌，没有云功能的广告拦截插件。
如果同样本地自行备份，还是那些老牌的用的顺手。

最后，还是要谢谢你们。提供一种可能，未来一定会更好的。

**Comment by jspenguin2017** [comment]
插件好像没办法知道你有没有登陆吧？
