### ISSUE TITLE
My rules firefox cloud qutoa exceeded

### ISSUE THREAD

**Issue by JustCauseWhyNot** [uBlockOrigin/uBlock-issues#2970]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When exporting My rules, and Trusted sites to cloud storage I get an output of `Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.`

### A specific URL where the issue occurs.

moz-extension://b1d08ca6-2f00-4677-84a8-d2de7b20d6b8/dashboard.html#dyna-rules.html

### Steps to Reproduce

First I open up ublocks config page. Then I navigate to the my rules panel. Lastly I click upload to cloud storage, and then I get the error.

<details>
<summary> advanced-settings </summary>

```
allowGenericProceduralFilters false
            assetFetchTimeout 30
    autoCommentFilterTemplate {{date}} {{origin}}
   autoUpdateAssetFetchPeriod 60
   autoUpdateDelayAfterLaunch 105
             autoUpdatePeriod 2
          benchmarkDatasetURL unset
             blockingProfiles 11111/#F00 11010/#C0F 11001/#00F 00001
              cacheStorageAPI indexedDB
      cacheStorageCompression true
cacheControlForFirefox1376932 no-cache, no-store, must-revalidate
      cloudStorageCompression true
              cnameIgnoreList unset
          cnameIgnore1stParty true
        cnameIgnoreExceptions true
      cnameIgnoreRootDocument true
                  cnameMaxTTL 120
           cnameReplayFullURL false
          cnameUncloakProxied false
              consoleLogLevel unset
              debugAssetsJson false
              debugScriptlets false
       debugScriptletInjector false
           disableWebAssembly false
   extensionUpdateForceReload false
             filterAuthorMode false
              loggerPopupType popup
 manualUpdateAssetFetchPeriod 500
           modifyWebextFlavor unset
                popupFontSize unset
   popupPanelDisabledSections 0
     popupPanelLockedSections 0
         popupPanelHeightMode 0
  requestJournalProcessPeriod 1000
                  selfieAfter 2
 strictBlockingBypassDuration 120
        toolbarWarningTimeout 60
          trustedListPrefixes ublock-
                uiPopupConfig unset
                     uiStyles unset
updateAssetBypassBrowserCache false
        userResourcesLocation unset
```

</details>

Not sure if that's relevant, but figured it'd be a good idea to include.

### Expected behavior

For there to not be an error, and for the sync to cloud to work. Cloud syncing on Filter lists, and My Filters works as intended. It's just My rules, and Trusted site that don't sync. It works on my mobile browser mull when I sync.

### Actual behavior

It did not succeed.

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 188294
 cosmetic: 45430
 scriptlet: 22800
 html: 1297
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5829-9, 3m
 default:
  user-filters: 230-4, never
  ublock-filters: 36531-89, 4m
  ublock-badware: 7427-10, 4m
  ublock-privacy: 674-0, 3m
  ublock-unbreak: 2201-2, 3m
  ublock-quick-fixes: 128-12, 3m
  easylist: 75517-702, 3m
  adguard-spyware-url: 1327-88, 3m
  easyprivacy: 32900-728, 3m
  urlhaus-1: 9970-0, 3m
  curben-phishing: 80869-29, 3m
  plowe-0: 3717-1, 3m
  LegitimateURLShortener: 2481-157, 3m
filterset (user): [array of 229 redacted]
trustedset:
 added: [array of 147 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 804 redacted]
hostRuleset:
 added: [array of 6557 redacted]
urlRuleset:
 added: [array of 16 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
 largeMediaSize: 1000
hiddenSettings:
 cacheStorageAPI: indexedDB
supportStats:
 allReadyAfter: 940 ms (selfie)
 maxAssetCacheWait: 154 ms
```
</details>

**Comment by JustCauseWhyNot** [comment]
Is dynamic rules not supposed to look like this on each site?
![2023-11-20_10-02](https://github.com/uBlockOrigin/uBlock-issues/assets/58643844/44f52760-fae8-4a18-b774-cc179923a926),

**Comment by gorhill** [comment]
Why do you have global block rules for `github.com`, `avatars.githubusercontent.com`, `githubassets.com` and who knows what else? Your single global block rule for `3rd-party` are all inherited by all 3rd-party domains.

**Comment by JustCauseWhyNot** [comment]
I see my error now. I apologize for the frivolous issue. Thank you so much for this tool.

**Comment by gorhill** [comment]
Yes, looks better. Doing things this way should massively reduce your ruleset.

**Comment by JustCauseWhyNot** [comment]
Thank you.

**Comment by JustCauseWhyNot** [comment]
I'm sorry, but I do have one question. With [hard mode](https://github.com/uBlockOrigin/uBlock-issues/wiki/Blocking-mode:-hard-mode) it shows 3p scripts/frames also having a rule created for them. But they inherit `* * 3p block` it appears. Is there a reason you would wanna create a specific rule for `3p-frames`, and `3p-scripts`?

**Comment by gorhill** [comment]
It's up to you, but the benefit of creating block rules for _3rd-party scripts_/_3rd-party frames_ is explained in <https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode>:

> With a single click, it is possible to toggle the hard mode into the [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode): it's just a matter of assigning a local noop rule to the 3rd-party cell. You can accomplish the same with a keyboard shortcut through the [command "Relax blocking mode"](https://github.com/uBlockOrigin/uBlock-issues/wiki/Keyboard-shortcuts).

If you wanted to go from hard mode to medium mode without block rules already present for _3rd-party scripts_/_3rd-party frames_, you would have to add block rules to _3rd party scripts_/_3rd party frames_ every time.

**Comment by JustCauseWhyNot** [comment]
Thank you for taking the time to explain.

**Comment by gorhill** [comment]
I just want to add what I should have mentioned above: it's ok to have global block rules for specific domains if you want these domains to stay blocked if ever you noop any of the _3rd-party_, _3rd-party scripts_, _3rd-party frames_ cell.

For example, I specifically block some of these ubiquitous domains so that I can easily fall into a lesser blocking mode while still specifically blocking these undesirable domains:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/b2610106-9cc0-44ae-8393-266f7cb6ec40)

**Comment by JustCauseWhyNot** [comment]
Appreciate the information :pray:.
