### ISSUE TITLE
Trusted-click-element cannot click shadow dom elements

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#2971]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`Trusted-click-element` cannot click shadow dom elements.

### A specific URL where the issue occurs.

`https://racingnews365.com/watch-nascar-driver-ryan-preece-survives-daytona-barrel-roll-accident`

### Steps to Reproduce

1. Add filter `racingnews365.com##+js(trusted-click-element, .cmpboxbtnyes)`
2. Open `https://racingnews365.com/watch-nascar-driver-ryan-preece-survives-daytona-barrel-roll-accident`

### Expected behavior

The button would be clicked.

### Actual behavior

It can't be clicked.

### uBO version

1.53.5rc11

### Browser name and version

FF 119.0.1

### Operating System and version

Win 10

**Comment by garry-ut99** [comment]
Related AdGuard request: 
- https://github.com/AdguardTeam/Scriptlets/issues/323

**Comment by gorhill** [comment]
Works: `racingnews365.com##+js(trusted-click-element, #cmpwrapper >>> .cmpboxbtnyes)`

**Comment by dportvine** [comment]
>`racingnews365.com##+js(trusted-click-element, '#cmpwrapper >>> .cmptxt_btn_settings, #cmpwrapper >>> [data-cmp-purpose="1"][aria-checked="false"], #cmpwrapper >>> .cmptxt_btn_save')`

In the logger this rule looks different, but it works.

```adb
racingnews365.com##+js(trusted-click-element, #cmpwrapper >>> .cmptxt_btn_settings\, #cmpwrapper >>> [data-cmp-purpose="1"][aria-checked="false"]\, #cmpwrapper >>> .cmptxt_btn_save)
```

**Comment by peace2000** [comment]
@gorhill Shadow-piercing doesn't work well on this page: `https://myprivacy.dpgmediagroup.net`

It takes many seconds for uBO to click the first button. The following buttons are never clicked.

To access that page, must open this page: `dpgmedia.nl`

Filter used:

`myprivacy.dpgmediagroup.net##+js(trusted-click-element, '#pg-shadow-host >>> #pg-configure-btn, #pg-shadow-host >>> #purpose-row-SOCIAL_MEDIA input[type="checkbox"], #pg-shadow-host >>> button#pg-save-preferences-btn', , , log, 1)`

Buttons that are supposed to click:
1. Instellen
2. Sociale media
3. Voorkeuren opslaan

Console:

![kuva](https://github.com/uBlockOrigin/uBlock-issues/assets/17256841/20831db3-3bf6-4bcc-af6a-2769a36828be)

**Comment by gwarser** [comment]
@peace2000 I'm landing on `https://www.dpgmediagroup.com/nl-NL`.

**Comment by peace2000** [comment]
> but I cannot find the second selector in the source.

You don't have it?

![kuva](https://github.com/uBlockOrigin/uBlock-issues/assets/17256841/cccf52dc-66b5-4401-a822-896360719ff3)

**Comment by gorhill** [comment]
When I paste `` in the address bar, I end up at `https://www.dpgmediagroup.com/nl-NL`, and your filter seems to work if I use `dpgmediagroup.com` instead of `myprivacy.dpgmediagroup.net`.

**Comment by gwarser** [comment]
> You don't have this?

This was missing yesterday:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/5eeabddb-443f-4830-a0b8-b668492d718b)

**Comment by peace2000** [comment]
In the first page load (cache is cleared) I end up in `myprivacy.dpgmediagroup.net` where clicking the shadow dom GDPR dialog doesn't work properly no matter what I do. However, if I reload the page once, I'll be redirected to `dpgmediagroup.com` where the clicking works.

I decided to take advantage of `set-cookie`'s reload function that creates a page reload which allows me to get to the page where everything works properly.

`myprivacy.dpgmediagroup.net##+js(set-cookie, dummy, 1, , reload, 1)`
