### ISSUE TITLE
CNAME-uncloak loses path info / cannot be permitted at the same granularity

### ISSUE THREAD

**Issue by jimbobmcgee** [uBlockOrigin/uBlock-issues#2979]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When CNAME-uncloaking is enabled, `* * 3p-script block` correctly triggers for websites that use CNAMEs to front their domains.  This is expected, normal, correct, etc.

However, I have noticed that, when trying to craft a suitable override, I can no longer use URL *paths* in my rule, as only the uncloaked *domain* is tested against.

*(Please bear with me --  I know I'm about to talk about Youtube, but I don't believe this to be YouTube-specific...)*

For instance, to allow embedded YouTube videos to play on any site, I had the fairly generic rules:

```
* https://www.youtube.com/embed/     inline-script  noop
* https://www.youtube.com/s/player/  script         noop
* https://www.youtube.com/embed/     sub_frame      noop
```

Recently, either Youtube has changed its DNS such that `www.youtube.com == youtube-ui.l.google.com` or the CNAME-uncloak has become more sensitive to this (or I have just enabled CNAME uncloaking, where before I didn't), but&mdash;essentially&mdash;what worked yesterday, no longer works, and is now blocked by `3p-script`:

```
Filter			* * 3p-script block
Root context		feedly.com
Context			www.youtube.com
Partyness		(3,3) feedly.com ? youtube.com ? google.com
Type			script
URL			https://youtube-ui.l.google.com/
CNAME			www.youtube.com => youtube-ui.l.google.com
Original URL		https://www.youtube.com/s/player/63e90c30/player_ias.vflset/en_US/base.js
```

I updated my generic rules to:

```
* https://youtube-ui.l.google.com/embed/     inline-script  noop
* https://youtube-ui.l.google.com/s/player/  script         noop
* https://youtube-ui.l.google.com/embed/     sub_frame      noop
```

...but the `3p-script` block still occurs.

The only patterns that now seem to avoid the `3p-script` block are:

```
* https://youtube-ui.l.google.com/  inline-script  noop
* https://youtube-ui.l.google.com/  script         noop
* https://youtube-ui.l.google.com/  sub_frame      noop
```

...(i.e. without the path) but that is wider in scope that the original ruleset.  I don't *want* to `noop` *all* `inline-script`, `script` or `sub_frame` elements at `www.youtube.com` or `youtube-ui.l.google.com` -- just the ones specific to the embedded player, i.e. under `/s/player` and `/embed`.

It *appears* (at least to me) that, once the domain has been resolved to its canonical domain, the path is no longer applied to the URL that is matched.  In the example above, surely the tested URL should be:

```
https://youtube-ui.l.google.com/s/player/63e90c30/player_ias.vflset/en_US/base.js
```

...which would match the pattern, as it did before.

Incidentally, in the logger, I do see the `noop` happening for `https://www.youtube.com/s/player/63e90c30/player_ias.vflset/en_US/base.js` -- it is just immediately followed by a `block` for `https://youtube-ui.l.google.com/`.

If it is *intentional* that the path is stripped from the tested string, then perhaps the available *types* could be extended to include a new `cname` type.  That way, we could add a (theoretical) new...

```
youtube.com   youtube-ui.l.google.com   cname   noop
```

...rule, so that this specific cloak is acknowledged.  That way, we would have granular control over both the path-based scripts *and* the redirection of the domain.

I'm just trying to avoid having to noop the whole domain for scripts, just because it has been cloaked.

### A specific URL where the issue occurs.

https://www.youtube.com/s/player/63e90c30/player_ias.vflset/en_US/base.js

### Steps to Reproduce

1. Confirm DNS resolution of `www.youtube.com` for you is `youtube-ui.l.google.com` (or similar)
2. Configure uBO with `*  *  3p-script block` and `*  *  3p-frame block` and *Uncloak canonical names*
4. Add `* https://www.youtube.com/s/player/  sub_frame  noop` rule
5. Navigate to a page with a standard embedded video, e.g. https://www.engr.colostate.edu/~dga/youtube-embed-test-page/
6. Observe the `noop` match against `https://www.youtube.com/embed/mmUG2qGZeLg?feature=oembed`
7. Observe the subsequent `block` against `https://youtube-ui.l.google.com/` (or as per resolution in 1)
8. Observe the only overrides offered by the logger target the broad `https://youtube-ui.l.google.com/` URL, not the most-targeted `https://youtube-ui.l.google.com/embed/mmUG2qGZeLg?feature=oembed` (or any of the path options in between).

#### Either...

uBO should allow matching the second CNAME-uncloaked URL inclusive of all path components, as it does for non-cloaked resources.  The combination of `* original_url/including/path script noop` and `* uncloaked_url/including/path script noop` should then both override the `3p-script` block.

#### Or...

uBO should classify the second CNAME-uncloaked block as a specific *type*, e.g. `cname`, so that action can be explicitly allowed / nooped.  The combination of `* original_url script noop` and `original_domain uncloaked_domain cname noop` could then override the `3p-script` block.

### Actual behavior

A specific third-party script cannot be precisely identified *by path* if the domain is cloaked.  Only a rule permitting the entire *domain* actually overrides `3p-script`.

The wider-scoped...

```
* https://www.youtube.com/embed/     sub_frame      noop
* https://youtube-ui.l.google.com/   sub_frame      noop
```

...is required, where the narrower-scoped...

```
* https://www.youtube.com/embed/           sub_frame      noop
* https://youtube-ui.l.google.com/embed/   sub_frame      noop
```

...should be permissable.

### Configuration

<details>

```yaml
uBlock Origin: 1.53.0
Firefox: 119
filterset (summary):
 network: 104702
 cosmetic: 58902
 scriptlet: 18964
 html: 1106
listset (total-discarded, last-updated):
 added:
  fanboy-thirdparty_social: 69-0, 1d.21h.43m
  fanboy-social: 16210-17, 1d.21h.43m
 default:
  user-filters: 2-0, never
  ublock-filters: 36546-121, 1d.21h.44m
  ublock-badware: 7442-10, 1d.21h.44m
  ublock-privacy: 682-0, 1d.21h.44m
  ublock-unbreak: 2200-0, 1d.21h.44m
  ublock-quick-fixes: 195-3, 9h.40m
  easylist: 75608-703, 1d.21h.43m
  easyprivacy: 32903-734, 1d.21h.43m
  urlhaus-1: 9840-0, 21h.42m
  plowe-0: 3718-1, 1d.21h.43m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 2 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 82 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 16 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 515 ms
 maxAssetCacheWait: 167 ms
```
</details>

**Comment by gorhill** [comment]
It's by design.

Set advanced setting [`cnameReplayFullURL`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnamereplayfullurl) to `true` if you do not mind the added overhead of having to scan the full URL for uncloaked cnames.

**Comment by jimbobmcgee** [comment]
@gorhill - thanks, and sorry for the noise.
