### ISSUE TITLE
Scripts still run from file:/// urls, even with `no-scripting: file-scheme true`

### ISSUE THREAD

**Issue by jimbobmcgee** [uBlockOrigin/uBlock-issues#2988]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Given a set of dynamic filtering rules:

```
no-remote-fonts: * true
no-scripting: file-scheme true
* * 1p-script block
* * 3p-frame block
* * 3p-script block
* * inline-script block
```

...and a local rudimentary HTML file, which uses script to inject some content...

```
<!DOCTYPE html>
<html>
    <body>
        <p>Hello</p>
        <p id="target">Nothing here</p>
        <script type="text/javascript">
            document.getElementById('target').textContent = "This got added...?";
        </script>
    </body>
</html>
```

I am seeing the script execute and inject the new content, when run from a local file:/// URL:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/12205864/863e6d3a-28ff-4354-bbf3-db5ea3613d5f)

I have been through the loaded filters and cannot see anything else relating to `file-scheme` or `file:///` that might be specifically allowing it, and I cannot see an advanced setting that would apply. `file-scheme` is not in the Trusted Sites list.  The Logger windows does not indicate an explicit `noop` or `allow` action.

I would have thought that the `* * inline-script block` would have been enough on its own.  I added `no-scripting: file-scheme true` to try and force the issue, but it doesn't seem to apply.  The GUI updates correctly (i.e. the red/pink matrix seems to apply, as does the general no-script icon), but the script still runs.

As a test, I added a wide-reaching filter to My Filters -- `*##+js(noop)` -- and can see this being fired in the Logger, so I assume that UBO is able to run against local files...

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/12205864/a73c11fa-4386-4476-8059-e4c78fc121c9)

...or is this a case of there being no *network* traffic, so nothing for UBO to intercept?

### A specific URL where the issue occurs.

file:///a-local-file.html

### Steps to Reproduce

1. Configure with at least `* * inline-script block` and optionally `no-scripting: file-scheme true`
2. Save the above HTML to a local file
3. Open the local file
4. Observe the second paragraph contains `This got added...?`

### Expected behavior

The inline script should not have run where `* * inline-script block` or `no-scripting: file-scheme true` applied.

### Actual behavior

The inline script was able to update content.

### uBO version

1.54.0

### Browser name and version

Firefox 120.0 64-bit

### Operating System and version

Windows 10 Pro 22H2 / 19045.3570

**Comment by gorhill** [comment]
Blocking JS is accomplished through injection of a `Content-Security-Policy` header with a value of `script-src http: https:`. There are no HTTP response headers when loading a `file:///` URI in the browser, so scripting cannot be blocked with `file-scheme`.

**Comment by gwarser** [comment]
Wasn't there a workaround by injecting CSP in `<head>`?

**Comment by iam-py-test** [comment]
Via meta tags, yes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv

**Comment by gwarser** [comment]
It was in uMatrix https://github.com/gorhill/uMatrix/blob/59d918356b8e9aed3281d62d9bac3129f64e013d/src/js/contentscript-no-workers.js#L24

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/2603#issuecomment-301094348
