### ISSUE TITLE
Redirect Loop after clicking a download button

### ISSUE THREAD

**Issue by chipsoftwaretest** [uBlockOrigin/uBlock-issues#2991]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

On chip.de there is a download button called "manual installation". Clicking it will sometimes loop back to the previous page.

### A specific URL where the issue occurs.

https://www.chip.de/events/adventskalender

### Steps to Reproduce

1. go to https://www.chip.de/events/adventskalender
2. open any door on the advent calendar
3. click the button "manuelle Installation"
4. it loops back to the advent calendar

It has to do with the referrer that is added automatically to the URL, e.g.
This URL loops back to the previous page
https://www.chip.de/downloads/Vollversion-Fotopaket-3-in-1_185008719.html?ref=adventskalender
but this URL does not and works as intended
https://www.chip.de/downloads/Vollversion-Fotopaket-3-in-1_185008719.html

### Expected behavior

The expected behavior is that the user is forwarded to a getfile page where he can receive his download.

### Actual behavior

Instead, the user is sent back to the previous page.

### uBO version

1.54.0

### Browser name and version

Firefox 115.4.0 ESR as well as Chrome 119.0.6045.106

### Operating System and version

Windows 10 Pro 64 Bit

**Comment by iam-py-test** [comment]
Filterlist issue, should be reported at https://github.com/uBlockOrigin/uAssets.
Thanks

**Comment by iam-py-test** [comment]
Please add `@@||chip.de^$removeparam=ref` to the My Filters tab of the dashboards and see if it fixes the issue.
If it does not, remove that filter. Then, click the uBo icon on the broken website, click the chat icon, scroll down to and expand _Troubleshooting information_ and post that here.
Thanks

**Comment by gorhill** [comment]
> I verified that this is not a filter list issue.

How?

The issue template that you filled says:

> See what [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) reports when you reproduce the issue, this will help you determine whether this is a filter issue.
