### ISSUE TITLE
Google Publisher Tag script error on serverfault.com

### ISSUE THREAD

**Issue by spazmodius** [uBlockOrigin/uBlock-issues#2992]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

`https://serverfault.com/questions/1085172/how-to-clear-windows-server-2019-dns-suffix-search-list`

### Description

```
Uncaught (in promise) TypeError: googletag.pubads().enableLazyLoad is not a function
```

because `googletagservices_gpt.js` [does not include a `enableLazyLoad` function.](https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/googletagservices_gpt.js#L70-L71)

https://developers.google.com/publisher-tag/reference#googletag.PubAdsService_enableLazyLoad

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/259818/ce65139f-9c44-47e6-9c4a-55ef6b47262e)
</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 127102
 cosmetic: 91375
 scriptlet: 27846
 html: 1319
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt: 406-22, 3h.53m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2498-3, 3h.31m
  https://raw.githubusercontent.com/stephenhawk8054/PrivacyExtended/main/privacy_extended.txt: 17431-56, 3h.19m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/annoyance_list.txt: 1105-25, 3h.53m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/block_third_party_fonts.txt: 72-0, 3h.56m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/click2load.txt: 94-0, 3h.50m
  https://raw.githubusercontent.com/yokoffing/filterlists/main/youtube_clear_view.txt: 27-1, 3h.53m
  ublock-annoyances: 5845-637, 6d.13h.42m
  fanboy-cookiemonster: 49056-17611, 4h.1m
  fanboy-social: 16022-11697, 1d.11h.17m
  block-lan: 55-0, 4h.2m
  adguard-popup-overlays: 26479-831, 3h.30m
  [5 lists not shown]: [too many]
 default:
  user-filters: 23-1, never
  ublock-filters: 36632-374, 4d.5h.31m
  ublock-badware: 7513-10, 4d.3h.30m
  ublock-privacy: 925-53, 11m
  ublock-unbreak: 2200-2, 1d.7h.16m
  easylist: 75775-16797, 3d.17h.28m
  easyprivacy: 32968-3895, 5d.15h.39m
  plowe-0: 3716-1, 12d.12h.16m
  urlhaus-1: 9355-0, 15h.12m
  ublock-quick-fixes: 242-63, 3h.11m
filterset (user): [array of 23 redacted]
trustedset:
 added: [array of 4 redacted]
 removed:
  edge-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 499 ms (selfie)
 maxAssetCacheWait: 267 ms
popupPanel:
 blocked: 2
 network:
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##.js-dismissable-hero
  ##.js-freemium-cta
  ###onetrust-consent-sdk
  ##.js-dismissable-hero:has-text(Sign up)
```
</details>

**Comment by gorhill** [comment]
Pulled your commit into master, <https://github.com/gorhill/uBlock/commit/a8cf08325dc2fa9cd39cbf97735ca7911d841224>, thank for contributing.
