### ISSUE TITLE
uBlock blocking PDF preview on gmail.com

### ISSUE THREAD

**Issue by neuronix** [uBlockOrigin/uBlock-issues#3]
### Description

PDF preview appears, then disappears after about 1second. Disabling uBlock solves the issue.

### A specific URL where the issue occurs

gmail.com

### Steps to Reproduce

1. Open email with pdf attachment
2. Open pdf preview
3. PDF preview disappears after 1s or so

### Expected behavior:

PDF preview displays permanently like previously.

### Actual behavior:

PDF preview disappears after 1s or so

### Your environment

* uBlock Origin version: 1.15.24
* Browser Name and version: Chrome   65.0.3325.181
* Operating System and version: Win 8.1

**Comment by uBlock-user** [comment]
> Disabling uBlock solves the issue.

Filterlist issues go here - https://github.com/uBlockOrigin/uAssets/issues

**Comment by neuronix** [comment]
Sorry, will post there.
