### ISSUE TITLE
Option to allow remote fonts from 1st party only

### ISSUE THREAD

**Issue by IzzySoft** [uBlockOrigin/uBlock-issues#300]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, one can only enable/disable *all* remote fonts for a site. It would be good to have the option of enabling remote fonts if they are hosted on the first party site itself – globally ("initially enabled/disabled") and/or per site.

### A specific URL where the issue occurs

https://android.stackexchange.com/

### Steps to Reproduce

1. visit a site using remote fonts
2. toggle remote fonts

It's an all-or-nothing.

### Expected behavior:

Have the option to only enable 1st-party remote fonts

### Actual behavior:

Only can toggle remote fonts in general

### Your environment

* uBlock Origin version: 1.17.2
* Browser Name and version: Misc Firefox/Waterfox
* Operating System and version: Linux, Windows

**Comment by uBlock-user** [comment]
You can uncheck no remote fonts option and add `$font,third-party` to _My filters_

**Comment by gwarser** [comment]
How about base64 encoded fonts embedded in css files?

**Comment by IzzySoft** [comment]
@Saitama thanks for the hint! But then, would the "remote font icon" toggle the 3rd parties only? If so, that would mostly solve my issue (though it's a bit hard to find for not so tech savvy users; a "split" of the "no remote fonts" option in 1st/3rd party (uh, what's the 2nd party then?) would be much clearer.

As for the embedded fonts @gwarser mentions: if the CSS comes from 1st party, they should fall into that category – otherwise into the other. In all cases, if CSP forbids them they should be ignored – but for that I'd expect the browser itself to take care.

**Comment by uBlock-user** [comment]
> "remote font icon" toggle the 3rd parties only?

Once you uncheck, that option is disabled and static filtering kicks in.

**Comment by IzzySoft** [comment]
OK, then it doesn't fit. I want to enable 3rd party for selected sites (and on demand), and 1st party for all.

**Comment by IzzySoft** [comment]
Ah, wait: `*$font,third-party,domain=~example.com|~example2.net` (taken from [here](https://github.com/gorhill/uBlock/issues/1787) and [here](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts)) – but that wouldn't be a real user-friendly way. A second "button" would be much easier to deal with.

(sorry for the extra comment, but Github seems to be broken currently: neither preview nor edit buttons are working).

**Comment by uBlock-user** [comment]
You're mixing up Dynamic and Static Filtering, don't use both, only deply one of them as dynamic filtering takes precendence over static filtering, so those filters won't work with dynamic rules.

**Comment by gorhill** [comment]
> A second "button" would be much easier to deal with.

I will declined this, I don't see bloating the UI with more and more buttons appealling to only an ever smaller group of users to be a good thing for usability. That kind of very specific need is best handled with specific approach, which is already in there as suggested above..

**Comment by uBlock-user** [comment]
> A second "button" would be much easier to deal with

![](https://i.gyazo.com/e5d92f27b0841a53495e029f3be0ad44.png)

Something like that you mean ?

**Comment by IzzySoft** [comment]
@Saitama Yes! That would do very fine and cover most of what I was after (especially if the "A" button then would toggle the 3rd party ones as it now does for all). Fiddling with the rules is a bit much for the average user – as you just proved by my "mixing rules" (which I still don't get, my apologies for not having dug into that) :wink:

I understand what @gorhill means by not wanting to bloat the UI, so I'd be content with that :innocent:

**Comment by uBlock-user** [comment]
If the main switch is checked, then sub switch will also be checked automatically, however if the main is not checked and only sub switch is checked, then only third-party fonts would be blocked.

**Comment by IzzySoft** [comment]
Uh? Now I'm confused. I'd expect: If both are checked, only 3rd party fonts are blocked. If sub is not checked, all remote fonts are blocked. If main is unchecked, sub gets grayed out an no remote fonts are blocked – it's a sub, after all, and one wouldn't expect it having effect when its main is not active.

What you describe sounds like both toggles are on the same level, and one is for 1st and the other for 3rd party. Would be fine with me as well, but shouldn't be shown as "master and servant" then. Though I don't see why one would want to block 1st party only while allowing 3rd party :wink:

**Comment by uBlock-user** [comment]
The behaviour I mentioned is the one taken from uMatrix for collapsing blocked/blacklisted elements. That's where I created the above switch option in the picture, may be gorhill knows better.

**Comment by IzzySoft** [comment]
I'm still confused. What would it mean then if both are checked (which is your initial state)? Optically it looks like the same what you describe with only the sub checked. If the master were labeled "block first-party remote fonts", and the sub "block third-party remote fonts" (no "only") – then I could follow you. And yes, then that would be fine and clear – and even match my above "why one would want to block 1st party only while allowing 3rd party" (i.e. that would be "ruled out" by the master-slave combination as it makes no sense).

**Comment by IzzySoft** [comment]
OK, thanks for at least considering it. Now it leaves the risk that, if one enables remote fonts for a site that (at that time) ships them from first-party only, and the site admin later decides to include 3rd-party fonts at a later time, those'd be allowed automatically without the user getting aware of it. I had preferred to see @uBlock-user's suggestion implemented…

**Comment by TFWol** [comment]
Well, this explains the confusion I had with the button when I tried to allow 1st party fonts only.
Something more intuitive that doesn't require hitting up the docs would be nice.

I wish there was a "fonts" section like there is for "images" in the main UI.
