### ISSUE TITLE
Use quoted values in the logger instead of escaped commas

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#3001]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Currently, uBO reports quoted values in scriptlets (E.G. in `trusted-set-cookie`, `trusted-click-element`) as if the commas have been escaped by `\` even if they aren't.

https://github.com/uBlockOrigin/uBlock-issues/issues/2971#issuecomment-1840113223

As using quoted values has become more widespread at uAssets (maybe even the preferred method), I think the logger should report values as if they are having quotes, instead of backslash escaped commas.

### A specific URL where the issue occurs.

`racingnews365.com`

### Steps to Reproduce

Copy this filter into custom filters:

`racingnews365.com##+js(trusted-click-element, '#cmpwrapper >>> .cmptxt_btn_settings, #cmpwrapper >>> [data-cmp-purpose="1"][aria-checked="false"], #cmpwrapper >>> .cmptxt_btn_save')
`

### Expected behavior

The logger would report it as the value would have been quoted

`racingnews365.com##+js(trusted-click-element, '#cmpwrapper >>> .cmptxt_btn_settings, #cmpwrapper >>> [data-cmp-purpose="1"][aria-checked="false"], #cmpwrapper >>> .cmptxt_btn_save')`

### Actual behavior

It's being reported as if the commas have been escaped by backlash

`racingnews365.com##+js(trusted-click-element, #cmpwrapper >>> .cmptxt_btn_settings\, #cmpwrapper >>> [data-cmp-purpose="1"][aria-checked="false"]\, #cmpwrapper >>> .cmptxt_btn_save)`

### uBO version

1.54.1b3

### Browser name and version

FF 120

### Operating System and version

Win 10

**Comment by gwarser** [comment]
This idea can be used to restore the original form of the filter https://github.com/uBlockOrigin/uBlock-discussions/discussions/771#discussioncomment-5551268
