### ISSUE TITLE
Tumblr - sideblog pages within Tumblr that have pinned posts sometimes have posts hidden by uBlock Origin

### ISSUE THREAD

**Issue by Cassolotl** [uBlockOrigin/uBlock-issues#3002]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

So, on Tumblr, I have a sideblog with a pinned post. There is a dashboard-style view of that blog. For the sideblog gendercensus, the URL is https://www.tumblr.com/blog/gendercensus

On that sideblog URL, one of my more recent posts (and not always the same one) is invisible if I navigate to the page through the sidebar menu, like so: https://www.tumblr.com/dashboard > Account > gendercensus

![Screenshot_2023-12-05_at_23_23_35](https://github.com/uBlockOrigin/uBlock-issues/assets/6607512/4d14460f-8509-4c03-9912-f43b233958ef)
![Screenshot_2023-12-05_at_23_19_58](https://github.com/uBlockOrigin/uBlock-issues/assets/6607512/ad8219cd-7fce-4c25-a075-8a399437d4b4)

The bug exists only on Chrome, not Firefox (which also has uBlock Origin installed). I do typically use the New X-kit extension, but the bug exists even with New X-kit deactivated. I'm running the latest version of Chrome on Mac Version 14.1.2 (23B92), Sonoma.

Sometimes reloading the page fixes it, and sometimes it doesn't, I think?

### A specific URL where the issue occurs.

https://www.tumblr.com/blog/gendercensus (You won't be able to access my view of this page without logging into my Tumblr account.)

### Steps to Reproduce

1. Join Tumblr.
2. Make sideblog.
3. Make a few posts.
4. Pin one post, which is one of the oldest posts.
5. In Chrome on Mac, navigate to the sideblog's page within Tumblr via the sidebar menu: tumblr.com > Account > [sideblog name]
6. Hopefully my bug is replicated and one of the more recent posts under the pinned post is missing.

### Expected behavior

All posts to be visible, in timestamp-descending order.

### Actual behavior

Most recent post, or sometimes not the most recent post but the one from right before it, is missing.

### Configuration

I do not know what any of this means and I have not edited it.

<details>

```yaml
uBlock Origin: 1.53.0
Chromium: 119
filterset (summary):
 network: 103305
 cosmetic: 44335
 scriptlet: 19481
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 302-5, never
  easylist: 75635-16, 2d.8h.34m
  easyprivacy: 33020-64, 5d.13h.13m
  plowe-0: 3779-1127, 3d.1h.43m
  ublock-badware: 7535-138, 5h.24m
  ublock-filters: 35965-157, 5h.25m
  ublock-privacy: 937-11, 2d.3h.47m
  ublock-quick-fixes: 281-119, 5h.22m
  ublock-unbreak: 2158-32, 5h.23m
  urlhaus-1: 9325-0, 22h.54m
filterset (user): [array of 302 redacted]
trustedset:
 added: [array of 9 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 990 ms (selfie)
 maxAssetCacheWait: 182 ms
```
</details>

**Comment by krystian3w** [comment]
> - [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

Really?

**Comment by Cassolotl** [comment]
> > * [x]  I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
> 
> Really?

I deleted everything containing the word Tumblr from "My filters", but I don't know what to do beyond that, and at the time of checking that checkbox I thought that's what it meant.

If you think that this is a filter list issue, I can just copy and paste this whole report over to [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues)? Or if this counts as broken website functionality? I'm very new to this so I don't know what any of it means, I'm just trying to help out.

**Comment by krystian3w** [comment]
As a bare uBo without lists does not damage the order (hiding something) on Tumblr, the error is more likely to be in the default subscription or those you have added.

**Comment by gorhill** [comment]
The template you filled says:

> If [disabling uBO](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) makes the issue go away, then it is a filter issue.
> See what [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) reports when you reproduce the issue, this will help you determine whether this is a filter issue.

**Comment by Cassolotl** [comment]
> The template you filled says:
> 
> > If [disabling uBO](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) makes the issue go away, then it is a filter issue.

Ahh that's the one! Thank you for the help, and I'm sorry for not reading thoroughly enough, I'll copy my issue over to the filter issues issue list and close this issue when I've done it.

**Comment by Cassolotl** [comment]
I followed the instructions for forcing an update of my filter lists and now I can't reproduce the bug so I think it's all fine and fixed now, apparently! Thanks again. :)
