### ISSUE TITLE
Latest Dev build reset all settings and removed all custom filers lists

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#3003]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I updated from 1.54.1b3 to 1.54.1b4 and my Ubo reset to factory all settings and custom filer lists are gone. Tried to restore from a back up and it does not restore 

### A specific URL where the issue occurs.

all

### Steps to Reproduce

1. update to the lastest dev build restart ff
2. all settings and user changes are removed

### Expected behavior

should update and not change

### Actual behavior

Ubo wiped clean and cant restore backup

### Configuration

<details>

```yaml
uBlock Origin: 1.54.1b4
Firefox: 120
filterset (summary):
 network: 105041
 cosmetic: 116967
 scriptlet: 26482
 html: 1326
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  easylist-annoyances: 4233-97, 1m
  fanboy-cookiemonster: 49118-281, 1m
  ublock-cookies-easylist: 639-0, 1m
  easylist-newsletters: 6684-13, 1m
  easylist-notifications: 2886-4, 1m
  fanboy-social: 15962-7, 1m
  ublock-annoyances: 6060-671, 1m
 default:
  user-filters: 1-0, never
  ublock-filters: 36867-115, 1m
  ublock-badware: 7540-11, 1m
  ublock-privacy: 931-4, 1m
  ublock-unbreak: 2204-1, 1m
  ublock-quick-fixes: 284-67, now
  easylist: 75826-354, now
  easyprivacy: 33048-115, now
  urlhaus-1: 9355-0, now
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings:
 autoCommentFilterTemplate: none
 extensionUpdateForceReload: true
 filterAuthorMode: true
 updateAssetBypassBrowserCache: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 593 ms
 maxAssetCacheWait: 306 ms
```
</details>

**Comment by troysjanda** [comment]
I have reverted to the last dev build uBlock Origin 1.54.1b3 and it is now working correctly

**Comment by krystian3w** [comment]
Me too, possible bug in #2969

**Comment by troysjanda** [comment]
> Me too, possible bug in #2969.
> 
> And this is not all true:
> 
> > Ubo wiped clean and cant restore backup
> 
> I lost only custom lists, advanced settings and my filters/rules/trusted pages was imported fine.

It was wiped as if just installing fresh for me

**Comment by krystian3w** [comment]
If someone reproduce on Chromium then more guilty is: https://github.com/gorhill/uBlock/commit/ea7d411bc2

**Comment by troysjanda** [comment]
Don't have Chrome so unable to test. I don't use Chrome based browsers.

**Comment by troysjanda** [comment]
1.54.1b5 seems to not have this issue just updated without issue.

**Comment by krystian3w** [comment]
For me too, no longer lost custom lists.

**Comment by troysjanda** [comment]
I don't think it was fixed yet just reverted something. He might want it kept open for reference.

**Comment by gorhill** [comment]
I know why the issue happened, I know how to fix it.

**Comment by troysjanda** [comment]
I just was not sure that it was a fix and not a  temporary revert of a previous build. Sorry was not trying to be rude. You do great work and would never be intentionally disrespectful.
