### ISSUE TITLE
YouTube is detecting it again on Firefox

### ISSUE THREAD

**Issue by Squirrelznut** [uBlockOrigin/uBlock-issues#3007]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

As title says, YouTube just now started detecting UbO again.
It wasn't detecting it earlier today.

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=z9gogi0MKuU

### Steps to Reproduce

1. Open youtube.com
2. Select a video to watch

### Expected behavior

Expected being able to watch the video.

### Actual behavior

Got the "Ad blockers violate YouTube's Terms of Service" message instead of a video.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 97754
 cosmetic: 43848
 scriptlet: 19006
 html: 1107
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 36576-123, never
  ublock-badware: 7477-10, never
  ublock-privacy: 729-0, never
  ublock-unbreak: 2200-0, never
  ublock-quick-fixes: 196-3, never
  easylist: 75607-701, never
  easyprivacy: 32908-23, never
  urlhaus-1: 4020-0, never
  plowe-0: 3718-708, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1309 ms
 maxAssetCacheWait: 2 ms
```
</details>

**Comment by mapx-** [comment]
go here https://github.com/uBlockOrigin/uAssets/issues/20586
