### ISSUE TITLE
cold start firefox, first load delays a lot

### ISSUE THREAD

**Issue by zygarte** [uBlockOrigin/uBlock-issues#3008]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

cold start on firefox, it delays first load some time, but addons web load properly

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. open firefox after pc off, cold start
2. test any web url, wait
3. in a private window, test the same web

### Expected behavior

first load, normal load time, some seconds

### Actual behavior

first load, some minutes delayed

### uBO version

1.54.0

### Browser name and version

mozilla 120.0.0.1

### Operating System and version

windows 11, latest upgrade

**Comment by gorhill** [comment]
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from the [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/docs/devtools/evaluate-performance/reference/) and a fully substantiated analysis supporting the claim.

If you want anything actionable, you will have to provide [profiling data](https://profiler.firefox.com/):

- Disable uBO
- Quit Firefox
- Launch Firefox
- Launch profiler, wait 2 seconds
- Enable uBO
- Wait for uBO to be ready
- Capture profile data and share here

**Comment by Rhkqt** [comment]
I have the same issue, Heres a profile link: https://share.firefox.dev/3GvUUWY

**Comment by gorhill** [comment]
@Rhkqt You have many other extensions which all show CPU usage way above uBO. If you want to report a performance issue, you will have to reproduce it with only uBO enabled, no other extensions, and profile while the performance issue is ongoing. There is nothing showing uBO being a performance issue in your profiling data, many other extensions are showing high CPU usage, especially Malwarebytes Browser Guard and many others but not uBO.

**Comment by Rhkqt** [comment]
@gorhill Disabling only uBlock lets youtube load, It is not an issue with other extensions. If you need screenshots in it i can reupload it with screenshots enabled.

**Comment by gorhill** [comment]
> Disabling only uBlock lets youtube load, It is not an issue with other extensions

This means nothing. **Try with only uBO**, all other extensions disabled, that is the first step to narrow down such issue.

**Comment by gorhill** [comment]
@Rhkqt 

> Here is with only uBlock enabled and it failing

I can uBO just doing mostly nothing and waiting. See if disabling _"Uncloak canonical names"_ in _Settings_ pane makes a difference -- there has been cases in which people with special proxy settings would cause undue delay to resolve calls to `browser.dns` API.

**Comment by Rhkqt** [comment]
Didn't work on either a new profile, However, Resetting to Factory Default seems to have fixed it (I haven't done any setting changes from base install other than a filter that i removed aswell)
