### ISSUE TITLE
Add Easylist Polish filter list

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uBlock-issues#301]
https://easylist-downloads.adblockplus.org/easylistpolish.txt
https://forums.lanik.us/viewforum.php?f=107
https://github.com/easylistpolish

Seeing that several of regional lists have 2 entires, consider adding Easylist Polish too:

<details not-open>
<summary>Combos</summary>

```
CHN: CJX's EasyList Lite​ ​​ ​​​​​​ 
CHN: EasyList China (中文)

ITA: ABP X Files
ITA: EasyList Italy

JPN: ABP Japanese filters (日本用フィルタ)
JPN: Adguard Japan Filter​ ​​ ​​​​​​ 

KOR: Korean Adblock List
KOR: YousList

POL: polskie filtry do Adblocka i uBlocka
POL: Easylist Polish <======================== will go here

RUS: Adguard Russian Filter​ ​​ ​​​​​​ 
RUS: RU AdList​ ​​ ​​​​​​ 

spa, por: Adguard Spanish/Portuguese​ ​​ ​​​​​​ 
spa: EasyList Spanish
```

</details>

**Comment by gorhill** [comment]
Declining -- this list does not have much activity and the current one is really where the action is, it receives numerous updates per day. Please do not make the argument "several of regional lists have 2 entires", it's not what matters, what matters is that the stock lists (which are there strictly for convenience) are not to be use as a bloated repository for all lists in existence. If anything, some entries should be reassessed for removal: CHN: EasyList Lite, ITA: ABP X, etc.

**Comment by uBlock-user** [comment]
Requests for adding new filter lists will be declined as per the instructions in README.
