### ISSUE TITLE
popup panel in logger ui has dynamic filtering options hidden

### ISSUE THREAD

**Issue by pedrohgmacedo** [uBlockOrigin/uBlock-issues#3015]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When the popup panel is toggled, all the dynamic filtering options are hidden in the logger UI.
See the screenshot:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/118010672/f343cb6a-4778-4b9b-a0a1-789662a26847)

### A specific URL where the issue occurs.

moz-extension://e36b955d-8d0b-4fee-88b6-4ea0576bde93/logger-ui.html?popup=1#97

### Steps to Reproduce

1. Open the logger UI
2. Toggle on the popup panel
3. Expand more 

### Expected behavior

Dynamic filtering options should not be hidden when window dimension is smaller than full height. 

### Actual behavior

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/118010672/f343cb6a-4778-4b9b-a0a1-789662a26847)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 190281
 cosmetic: 162430
 scriptlet: 43068
 html: 1325
listset (total-discarded, last-updated):
 added:
  https://pedromacedo.org/filters.txt: 195-0, 3d.7h.28m
  https://pedromacedo.org/rules.txt: 183-1, 3d.7h.28m
  adguard-generic: 80528-4734, 3d.7h.34m
  adguard-mobile: 8788-102, 3d.7h.34m
  adguard-spyware-url: 1352-93, 3d.7h.40m
  adguard-spyware: 76708-17963, 3d.7h.40m
  adguard-social: 22066-872, 3d.7h.40m
  adguard-mobile-app-banners: 4817-1069, 3d.7h.40m
  adguard-other-annoyances: 14016-324, 3d.7h.40m
  adguard-widgets: 2354-1, 3d.7h.40m
  easylist-annoyances: 4227-131, 3d.7h.40m
  easylist-chat: 168-12, 3d.7h.40m
  [6 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 36826-382, 3d.7h.41m
  ublock-badware: 7544-12, 3d.7h.41m
  ublock-privacy: 921-4, 3d.7h.41m
  ublock-unbreak: 2204-0, 3d.7h.41m
  ublock-quick-fixes: 172-2, 2h.6m
  easylist: 75825-2473, 3d.7h.41m
  easyprivacy: 33040-910, 3d.7h.41m
  urlhaus-1: 9915-0, 2h.6m
  plowe-0: 3779-21, 3d.7h.41m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 951 ms (selfie)
 maxAssetCacheWait: 381 ms
```
</details>

**Comment by u-RraaLL** [comment]
The main problem is fixed. Just two questions:

1. Does the popup needs to force the vertical UI here? I don't believe it used to in the past.
2. It is supposed to cover part of the top bar like shown in the screenshot below?

<details><summary>screenshot</summary>

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/92610420/0d0e1960-e705-454f-b192-151a7ee1a993)
</details>

**Comment by gwarser** [comment]
At 1. - I believe, this was a design decision when the new popup UI was implemented in the logger.

**Comment by gorhill** [comment]
1. Yes, I want to omit the number of issues arising as a result of being too flexible -- the issue here is an example of this.
2. Yes, I wanted the minimum height which still allow for turning off popup panel, hence `100vh` minus just enough to reveal icons.
