### ISSUE TITLE
[Feature Request] Sort MyFilters / Options for grouping & date removals

### ISSUE THREAD

**Issue by Apocalypse612** [uBlockOrigin/uBlock-issues#3019]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello,

I'm not sure if this belongs here, but if it does not, please inform me of where to post it.

The options for the "MyFilters" settings tab is severely lacking. I would like to see the following options implemented, if possible:
1) Option to disable date-stamping from this page. I personally have no use of this feature.
2) Option to enable domain GROUPING on this page. Tied into the above.
    E.g. I don't want all of my Facebook.com blocks to be separated into various sections. 
    
Thanks!

### A specific URL where the issue occurs.

moz-extension://

### Steps to Reproduce

Just look at the settings page. 

### Expected behavior

Just look at the settings page. 

### Actual behavior

Just look at the settings page. 

### uBO version

1.54.0

### Browser name and version

Firefox 120.0.1 (64-bit)

### Operating System and version

Windows 11 22H2

**Comment by Apocalypse612** [comment]
> For (1), you can set the advanced setting `autoCommentFilterTemplate` to `none` as specified in the [wiki](https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#autocommentfiltertemplate).
> 
> I will let the maintainers respond to (2).

Oh wow, I didn't even see that little cog wheel icon for the advanced settings page. I had it enabled, but I though the additional options were reflected inside of the tabs at the top of the settings page. Go figure!

Thanks for bringing this to my attention.

God bless.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/647

**Comment by garry-ut99** [comment]
> Apocalypse612 : 1. Option to disable date-stamping from this page. I personally have no use of this feature.

Already implemented, like others already said, but it's also a duplicate request of #372 which is a duplicate request of gorhill/uBlock#93.

**Comment by gorhill** [comment]
If someone comes up with modular code that does what is requested, I am willing to use it, as long as issues arising from it are also taken care of by volunteers.

**Comment by u-RraaLL** [comment]
What about adding an option to select lines highlighted by the search box? E.g.:

1. Search for: `/^example\.com.+/`
2. Click [Select (highlighted)].
3. Cut then paste where you want them.


Also, if it gave options to copy/cut/remove directly, this could probably vastly improve the management of "my filters" on mobile.

**Comment by gwarser** [comment]
Text in active line is already selected.

**Comment by gorhill** [comment]
CodeMirror supports disjointed selections, so theoretically this seems possible. Still, some comments could be left out dangling, uBO can't know which comment is meant for which filter(s). Also, no need for a regex, the [Select (highlighted)] would just select the whole line where there is a match.

Anyway I see this as having to spend a lot of time on something which results might not be convincing, considering everything else I have to take care of. Hence why I decline.

**Comment by u-RraaLL** [comment]
Right. I was thinking of the newer picker-crafted lines that I occasionally move to groups of previous filters, in which case I just remove the comments anyways. I had not considered the custom comments I already have elsewhere. So instead of selecting everything, it'd be better if it selected current and forward.

Anyway, since you don't want to spend time on this, it's a moot point.
