### ISSUE TITLE
upward does not work in the latest Chrome version

### ISSUE THREAD

**Issue by qo4on** [uBlockOrigin/uBlock-issues#3024]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`upward()` does not work in the latest Chrome version.
The same thing works in Tor Browser 13.0.6 (based on Mozilla Firefox 115.5.0esr).

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps to Reproduce

Go to https://github.com/uBlockOrigin/uBlock-issues/issues
Click on uBlockOrigin icon
Enter element picker mode of uBlockOrigin
Select any element
replace the search line with `##.selected.js-selected-navigation-item.js-responsive-underlinenav-item.no-wrap.UnderlineNav-item:upward(1)` and see 0 elements found
remove `:upward(1)` from the search line and see 1 elements found

### Expected behavior

`##.selected.js-selected-navigation-item.js-responsive-underlinenav-item.no-wrap.UnderlineNav-item:upward(1)`
must find 1 element on the page
`https://github.com/uBlockOrigin/uBlock-issues/issues`

### Actual behavior

`##.selected.js-selected-navigation-item.js-responsive-underlinenav-item.no-wrap.UnderlineNav-item:upward(1)`
found 0 elements on the page
`https://github.com/uBlockOrigin/uBlock-issues/issues`

### uBO version

uBlock Origin 1.54.0

### Browser name and version

Chrome 120.0.6099.109 (Official Build) (64-bit) (cohort: M120 Rollout)

### Operating System and version

Windows 10 Pro for Workstations 22H2 19045.3803 Windows Feature Experience Pack 1000.19053.1000.0

**Comment by gwarser** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/c2e1b14c-f59b-43f5-a02f-ec7061458d25)

**Comment by gwarser** [comment]
Share troubleshooting info 🛡️ uBO's icon > 💬 Report > Click "Troubleshooting information" > Select all > Copy > Share it

**Comment by gorhill** [comment]
Works fine here:

![Screenshot from 2023-12-15 15-49-45](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/a52b4720-09e5-4d51-bf61-35e72fa04193)

**Comment by gorhill** [comment]
Are you sure it was `:upward(1)` and not typo-ed like `:upward(l)`?

**Comment by gwarser** [comment]
When no-cosmetic-filtering is toggled, I see that plain CSS works and upward does not. But I need to enter the element picker from the popup and manually paste the cosmetic filter.

**Comment by gorhill** [comment]
> I need to enter the element picker from the popup

I can't easily find an image on the mentioned page to even opened the picker dialog.

**Comment by gorhill** [comment]
> updating the browser to the new look

What's "new look"?
