### ISSUE TITLE
Illegal Rootkit Analysis

### ISSUE THREAD

**Issue by IndigoBlue9898** [uBlockOrigin/uBlock-issues#3025]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

indigoblue9898@protonmail.com

Prevented from accessing this site by thuglike filth against my 4th amendment rights:     https://sublime.security/demo/

### A specific URL where the issue occurs.

 https://sublime.security/demo/

### Steps to Reproduce

1)    Went to the site entered required information and submitted. Information was received and confirmed that received.
2)   Confirmation received : Request Demo
Thank you! Your submission has been received!

### Expected behavior

Something in my email box, but it was not there.   Also signed up for a Github account IndigoBlue9898

### Actual behavior

Zero nothing received.   Tampered with by Illegal Rootkit at Wellesley , Ma Library.  Might seem a minor problem but the filth doing this are putting themselves at personal risk by breaking the law this is the USA not Myanmar or China.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 106052
 cosmetic: 44056
 scriptlet: 19436
 html: 1135
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37043-190, now
  ublock-badware: 7620-11, now
  ublock-privacy: 945-4, now
  ublock-unbreak: 2214-0, now
  ublock-quick-fixes: 110-2, 1m
  easylist: 75626-547, 1m
  easyprivacy: 33130-851, 1m
  urlhaus-1: 11965-0, 1m
  plowe-0: 3781-1, 1m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1286 ms
 maxAssetCacheWait: 5 ms
```
</details>

**Comment by IndigoBlue9898** [comment]
It seems we now live in Myanmar or China.   Illegal warantless rape of peoples personal information without due cause or legal documentation.

**Comment by IndigoBlue9898** [comment]
It seems we now live in Myanmar or China. Illegal warantless rape of peoples personal information without due cause or legal documentation.

**Comment by IndigoBlue9898** [comment]
Please advise what was done ? Thanks !

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by gwarser** [comment]
Check your email spam folder? No idea why you think uBO is the issue.

**Comment by IndigoBlue9898** [comment]
Its not doing its job, there is a RAT Remote access Trojan on this computer, my Protonmail emails are being controlled remotely.

Maybe you should look at some log files, rather than just closing the case for metrics reasons.

Gary

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by IndigoBlue9898** [comment]
My password is also visible (to my tormentors) and I am being subjected to Illegal Unwarranted search against Massachusetts and Federal laws.

Rgds Gary

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by iam-py-test** [comment]
>  there is a RAT Remote access Trojan on this computer, my Protonmail emails are being controlled remotely

This is not a malware removal support forum.
If your device is infected with malware, then please ask for help on one, i.e. forums.malwarebytes.com
Thank you.
