### ISSUE TITLE
Diff-update not working for manually added filter lists

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#3028]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Since the last stable update uBo is supporting differential updates. 
I added my own list with differential updates available in the header, but it doesn't update after the diff-expires. 

### A specific URL where the issue occurs.

manually added filter lists

### Steps to Reproduce

1. Make your own list and add in the header
```adblock
! Title: Example Filter List
! Last modified: Fri, 15 Dec 2023 09:35:24
! Expires: 14 days (update frequency)
! Diff-Path: patches/2023.12.15.575.patch#list3
! Diff-Expires: 12 hours
! Description:  
!     A text
!    which is nonses
! Homepage: https://github.com//Personal-List
! License: https://github.com//main/LICENSE
```
2. Add this list to uBlock
3. see that it doesn't update after 12 hours, also not if you restart your browser.

### Expected behavior

Manually added filter list should also update on `diff-expires`

### Actual behavior

uBlock is not using differential updates for manually added filter lists (???)

### uBO version

1.54.0

### Browser name and version

Firefox 120

### Operating System and version

Windows 10, 22H2

**Comment by gorhill** [comment]
It's in the `cdn-page` branch: https://github.com/JohnyP36/Personal-List/tree/cdn-page/patches

**Comment by u-RraaLL** [comment]
The dev version is there exactly so you could get your fix quicker and make sure any bugs are caught before making it into stable.

Do you really want to wait (possibly) months between each fix to issues you might be reporting? Considering you're on FF, the dev version would just replace your stable install, keeping your config intact. It's not a separate extension, like on Chromium.

**Comment by JohnyP36** [comment]
> The dev version is there exactly so you could get your fix quicker and make sure any bugs are caught before making it into stable.

Installed it. So, you will hear back from me within a week.

**Comment by JohnyP36** [comment]
@gorhill After a week of testing I can confirm your changes works.
Also, I made the following discovery: if `diff-expires` expires but there is no new diff-patch it will not update, but as soon as a new diff-patch is available it will update the list.

**Comment by JohnyP36** [comment]
> File will be requested every filter list "update session" (after uBO start and then every hour). This is what you see?

That must indeed be what I see. I didn't know UBo did every hour an "update session." 
Conclusion: just normal behavior.

**Comment by garry-ut99** [comment]
> JohnyP36 : I didn't know UBo did every hour an "update session."

You missed it, it's in the manual : https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#auto-update-filter-lists

**Comment by JohnyP36** [comment]
For some reason uBlock is not consistent in updating imported lists in accordance with the diff-expires set. 

Also, on browser start-up it will only directly update the standard lists (if the 5 hours is past), but not the imported lists, even though 12 hours has been past and a new diff-update is available.

**Comment by gorhill** [comment]
The last patch I see for your list is 4-day old: <https://github.com/JohnyP36/Personal-List/tree/cdn-page/patches>.

What's the URL of your imported list?

**Comment by JohnyP36** [comment]
> The last patch I see for your list is 4-day old: https://github.com/JohnyP36/Personal-List/tree/cdn-page/patches.
> 
> What's the URL of your imported list?

I saw this issue last week when I did a lot of updates almost every day - I just made a new patch today.

The URL I'm using is: `https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/Dutch-Filter-List.txt`

**Comment by gorhill** [comment]
> The URL I'm using is: `https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/Dutch-Filter-List.txt`

When I try to navigate to [your patch](https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/patches/2024.1.15.795.patch#dutchfilterlist) as per the `Diff-Path: patches/2024.1.15.795.patch#dutchfilterlist` field, I get `404: Not Found`

**Comment by JohnyP36** [comment]
> When I try to navigate to [your patch](https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/patches/2024.1.15.795.patch#dutchfilterlist) as per the `Diff-Path: patches/2024.1.15.795.patch#dutchfilterlist` field, I get `404: Not Found`


But the file is there in my repo: `https://github.com/JohnyP36/Personal-List/blob/cdn-page/patches/2024.1.15.795.patch`
Both when logged in to Github and logged out, both on Firefox and MS Edge that patch is available for me.

Maybe the fact that uBlock can also not find a new patch is the problem here.

**Comment by gorhill** [comment]
See for yourself, load `https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/Dutch-Filter-List.txt` in a new tab.

`Diff-Path:` field is `patches/2024.1.15.818.patch#dutchfilterlist`.

Now replace `Dutch-Filter-List.txt` in list URL with patch string `patches/2024.1.15.818.patch#dutchfilterlist`, result:

    https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/patches/2024.1.15.818.patch#dutchfilterlist

Navigate to that URL: `404: Not Found`

**Comment by JohnyP36** [comment]
@gorhill Yes, I came to that conclusion to. 

When I updated my list the workflow action created a new patch file named `2024.1.15.795.patch`, **but** in that file it says `! Diff-Path: patches/2024.1.15.818.patch#dutchfilterlist`. The diff-patch is says is not the same as the file it's placed in.

**Comment by gorhill** [comment]
Well people using your list will have a version of the list version which points at `patches/2024.1.15.795.patch` and since now this resource exists, the list will properly update using that patch. That patch didn't exist earlier when I checked your list.

**Comment by gorhill** [comment]
Maybe you could look what I did for RUAdList, it imports the shell scripts from uAssets, so this way whenever I fix or make improvements to the shell scripts, it benefits immediately the changes: <https://github.com/dimisa-RUAdList/RUAdListCDN/blob/main/.github/workflows/main.yml>. You would need to replace a few things in the workflow for it to work in your repo.

**Comment by JohnyP36** [comment]
> Well people using your list will have a version of the list version which points at `patches/2024.1.15.795.patch` and since now this resource exists, the list will properly update using that patch. That patch didn't exist earlier when I checked your list.

That's correct. I made another update; so, that's why it now exist.

But it occurs that sometimes that "future patch" never comes as sometimes the list is only update after 2 days.

---
> Maybe you could look what I did for RUAdList, it imports the shell scripts from uAssets, so this way whenever I fix or make improvements to the shell scripts, it benefits immediately the changes: https://github.com/dimisa-RUAdList/RUAdListCDN/blob/main/.github/workflows/main.yml. You would need to replace a few things in the workflow for it to work in your repo.

I already took a look, but will improve. 
Thanks. 

I'm almost sure this solves my problem.
