### ISSUE TITLE
Malware Domain List site down but still updating in uBlock?

### ISSUE THREAD

**Issue by BlohoJo** [uBlockOrigin/uBlock-issues#303]
### URL(s) where the issue occurs

[https://www.malwaredomainlist.com/hostslist/hosts.txt](https://www.malwaredomainlist.com/hostslist/hosts.txt)
[https://www.malwaredomainlist.com](https://www.malwaredomainlist.com)
[http://www.malwaredomainlist.com/hostslist/hosts.txt](http://www.malwaredomainlist.com/hostslist/hosts.txt)
[http://www.malwaredomainlist.com](http://www.malwaredomainlist.com)

### Describe the issue

Malwaredomainlist.com appears to be down, however, uBlock does not error out when updating it. It appears to use some different URL or cached source. I can see the total number of filters is different than the last known current list, so I know it is not updating from malwaredomainlist.com.

[https://downforeveryoneorjustme.com/malwaredomainlist.com](https://downforeveryoneorjustme.com/malwaredomainlist.com)

There is a Github which tries to keep an up to date as possible version of this list at [https://github.com/NanoMeow/MDLMirror](https://github.com/NanoMeow/MDLMirror). I tried using the "Import Custom" to import the raw text of this list, but uBlock "silently ignores" and does not add the link. (Tried both [https://github.com/NanoMeow/MDLMirror/raw/master/filter.txt](https://github.com/NanoMeow/MDLMirror/raw/master/filter.txt) and [https://github.com/NanoMeow/MDLMirror/raw/master/hosts.txt](https://github.com/NanoMeow/MDLMirror/raw/master/hosts.txt). Also tried the subscribe links: [plain hosts](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fgitcdn.xyz%2Frepo%2FNanoMeow%2FMDLMirror%2Fmaster%2Fhosts.txt&title=Malware%20Domain%20List) and [Adblock Plus](https://subscribe.adblockplus.org/?location=https%3A%2F%2Fgitcdn.xyz%2Frepo%2FNanoMeow%2FMDLMirror%2Fmaster%2Ffilter.txt&title=Malware%20Domain%20List). Despite getting a subscription confirm message, neither was added.)

Does uBlock's built in Malware Domain List filter needs updating / changed / removed? Why does uBlock not allow the user to add an alternate source for this list?

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 54.0.1 / Chromium 70.0.3538.77
- uBlock Origin version: 1.17.2 / 1.17.0

### Settings

- n/a

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by jspenguin2017** [comment]
NanoMeow will continue to try to update the mirror every hour. But honestly I highly doubt this filter is still useful today. 

Also transfer breaks issues reference, that's weird.

**Comment by gwarser** [comment]
>~~Also transfer breaks issues reference, that's weird.~~ Huh, it just fixed itself...

By me. It's enough to enter editing mode and click "Update comment"

**Comment by uBlock-user** [comment]
MDL is back up and running..

**Comment by uBlock-user** [comment]
> I tried using the "Import Custom" to import the raw text of this list, but uBlock "silently ignores" and does not add the link. (Tried both https://github.com/NanoMeow/MDLMirror/raw/master/filter.txt and https://github.com/NanoMeow/MDLMirror/raw/master/hosts.txt. Also tried the subscribe links: plain hosts and Adblock Plus. Despite getting a subscription confirm message, neither was added.)

Because that link gets redirected to https://raw.githubusercontent.com/NanoMeow/MDLMirror/master/hosts.txt which already exists as an alternative source, so uBO won't let you install a duplicate.
