### ISSUE TITLE
Translation error:Romanian (in menu)

### ISSUE THREAD

**Issue by epicfloppadev** [uBlockOrigin/uBlock-issues#3031]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

sprjini--->sprijină
situri---->site-uri (English word so separation is needed)

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#support.html

### Steps to Reproduce

Enter the menu in Romanian Language

### Expected behavior

A correct writing

### Actual behavior

bad writing

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 105787
 cosmetic: 44983
 scriptlet: 19725
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ROU-1: 1337-1, 1d.22h.18m
  easylist: 75885-36, 1h.50m
  easyprivacy: 33116-77, 1h.50m
  plowe-0: 3781-1153, 1d.22h.17m
  ublock-badware: 7633-138, 1h.50m
  ublock-filters: 36427-351, 1h.50m
  ublock-privacy: 949-12, 1h.50m
  ublock-quick-fixes: 116-5, 1h.50m
  ublock-unbreak: 2176-32, 1h.50m
  urlhaus-1: 11025-0, 21h.28m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 973 ms (selfie)
 maxAssetCacheWait: 303 ms
```
</details>

**Comment by gorhill** [comment]
Translation work is done at <https://crowdin.com/project/ublock>, and imported into uBO, so any changes need to be made there.

**Comment by epicfloppadev** [comment]
Ok.
