### ISSUE TITLE
Please adjust colors to something color-blind people can see

### ISSUE THREAD

**Issue by davimack** [uBlockOrigin/uBlock-issues#3033]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When you click the uBlock icon you get a dashboard popup.  This has a list of domains & how they're treated.  The indicators are red and green.  Wikipedia tells me I'm not alone in not being able to see those colors.  Red–green color blindness affects up to 1 in 12 males (8%) and 1 in 200 females (0.5%).

### A specific URL where the issue occurs.

https://www.google.com/

### Steps to Reproduce

1. Click the plugin from the browser bar.
2. Look at the red and green things.
3. Imagine that one of those looks sort of puke colored, and the other you can only see if you zoom in.
4. Wonder whether the feature would be useful if I could see it.

### Expected behavior

I'm asking to pretty please pick some different colors.  Probably not yellow/blue either, as there's a type of color blindness for those colors as well.
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/12926523/328d9b7e-9633-4c81-b056-90eaf8f8be0b)

### Actual behavior

It was colors I can't see.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 107534
 cosmetic: 88165
 scriptlet: 22898
 html: 0
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 49101-163, 1d.35m
 default:
  user-filters: 34-0, never
  easylist: 75913-16, 3h.51m
  easyprivacy: 33118-65, 3h.51m
  plowe-0: 3777-1148, 9d.3h.43m
  ublock-badware: 7633-138, 3h.51m
  ublock-filters: 36435-358, 3h.51m
  ublock-privacy: 949-12, 3h.51m
  ublock-quick-fixes: 100-5, 3h.51m
  ublock-unbreak: 2176-33, 3h.51m
  urlhaus-1: 11445-0, 1h.51m
filterset (user): [array of 34 redacted]
trustedset:
 added: [array of 22 redacted]
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1594 ms (selfie)
 maxAssetCacheWait: 397 ms
```
</details>

**Comment by gwarser** [comment]
Is this better?

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/91162f2c-5840-4fb5-a4d6-73f6f33d3bc1)

https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Settings#color-blind-friendly

**Comment by davimack** [comment]
I see what you're showing me, in the colors with + and - in them?  I don't think that's out yet, though, or it's a setting?  It's entirely possible that this solves it, yes, once I've learned what the colors mean. 😄  I'll poke through settings & see if I can find this in there.  Thank you!

(funny for you: I created a spreadsheet with tons of the "green" codes, so I could flag the ones I can't see & never use them on applications.)

**Comment by u-RraaLL** [comment]
> or it's a setting?

uBO's popup > Dashboard > Settings > Appearance > [x] Color-blind friendly

**Comment by gorhill** [comment]
This was implemented in April 2015: <https://github.com/uBlock-LLC/uBlock/issues/467#issuecomment-95177219>.

**Comment by garry-ut99** [comment]
Also :
- https://github.com/uBlockOrigin/uBlock-issues/issues/1299
