### ISSUE TITLE
Clicking on a domain in the widget, should open the logger with a filter to show that specific domain and everything retrieved from there.

### ISSUE THREAD

**Issue by NastyFlytrap** [uBlockOrigin/uBlock-issues#3036]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There wasnt a suggestion option amongst the issues, sorry.

Anyway, as i said, there's the extension's badge, i click on it, a drop down box appears with all the quick settings, and clicking on a domain on the left half should open the logger and show everything that domain sent to the user, and preferably nothing else, or atleast highlight the domain in question, maybe come up with a new colour for the currently highlighted domain?

Love your work regardless, thank you

### A specific URL where the issue occurs.

Manjaro.org i used as an example

### Steps to Reproduce

Click on widget
Click on domain

### Expected behavior

Logger should open with a filter set for that domain

### Actual behavior

Nothing happens

### uBO version

1.54.0

### Browser name and version

Librewolf 120.0.1-1

### Operating System and version

Win10 64Bit winver 21H2

**Comment by gorhill** [comment]
The logger is forward looking, it doesn't know what happened in the past before it was opened.

**Comment by NastyFlytrap** [comment]
> The logger is forward looking, it doesn't know what happened in the past before it was opened.

Okay but then it could just reload the site, and therefore get things going in the log

**Comment by u-RraaLL** [comment]
I don't think most people would want logger launched every time they clicked a domain by mistake.
Reloading a page could be even worse as it could remove their progress if they were writing something. And a normal reload doesn't account for things already cached by the browser, so these wouldn't show in logger.

What you want is quite easily achieved on your own by opening uBO's popup _inside_ the logger and selecting and dragging the particular domain to the filter box.

**Comment by gorhill** [comment]
> just

As said, I prefer to decline -- I am sure everything looks trivial from outside but it's not and it's not something I want to spend time on.

**Comment by NastyFlytrap** [comment]
> > just
> 
> As said, I prefer to decline -- I am sure everything looks trivial from outside but it's not and it's not something I want to spend time on.

Fair enough.

> I don't think most people would want logger launched every time they clicked a domain by mistake. Reloading a page could be even worse as it could remove their progress if they were writing something. And a normal reload doesn't account for things already cached by the browser, so these wouldn't show in logger.
> 
> What you want is quite easily achieved on your own by opening uBO's popup _inside_ the logger and selecting and dragging the particular domain to the filter box.

How do i drag and drop there? It just selects text.

**Comment by garry-ut99** [comment]
> u-RraaLL: Selecting the particular domain
> NastyFlytrap : How do i drag and drop there? It just selects text.

It seems you read "selecting" as "clicking", in such case, indeed, simply clicking and draging domain won't work. It seems that the steps that were provided to you, weren't clear enought. What "Selecting" was supposed to mean, was:  highlighting (selecting text), and then drag & drop the selected text. ( it's a basic html5 feature, the same can be done on every webpage, for example :  drag & drop the selected text to browser address bar or to other text fields. )

However, there is one issue with drag  & drop, it _appends_ the selected text, to the already existing text, which in case of uBO logger, is rather cumbesome than helpful, because an user needs to manually clear content of filter box each time he wants to drag & drop a new domain from uBO popup, would be good to _replace_ instead of _append_, like here requested : https://stackoverflow.com/questions/17947692/drag-a-div-with-text-and-drop-on-another-to-replace-text, or make it as alternative : Atrl or Shift or Alt + drag = _replace_ content of filter box instead of _append_, but this is still not a perfect solution, because in such case an user needs two hands instead of one, unless he has a mouse with additional buttons and can write macro to one of it's button.

**Comment by NastyFlytrap** [comment]
> > u-RraaLL: Selecting the particular domain
> > NastyFlytrap : How do i drag and drop there? It just selects text.
> 
> It seems you read "selecting" as "clicking", in such case, indeed, simply clicking and draging domain won't work. It seems that the steps that were provided to you, weren't clear enought, and have misguided you. What "Selecting" was supposed to mean, was: highlighting (selecting text), and then drag & drop the selected text. ( it's a basic html5 feature, the same can be done on every webpage, for example : drag & drop the selected text to browser address bar or to other text fields. ). Also there is an easy way to select domain text automatically: double click will select a part of domain, while triple click will select the whole domain automatically.
> 
> However, there is one issue with drag & drop, it _appends_ the selected text, to the already existing text, instead of _replace_, which in case of uBO logger, is rather cumbesome than helpful, because an user needs to manually clear content of filter box each time he wants to drag & drop a new domain from uBO popup, maybe would be good to _replace_ instead of _append_, like here requested : https://stackoverflow.com/questions/17947692/drag-a-div-with-text-and-drop-on-another-to-replace-text, or to make it as alternative : Ctrl or Shift or Alt + drag = _replace_ content of filter box instead of _append_, but this is still not a perfect solution, because in such case an user needs two hands instead of one, which is cumbersome as well, unless he has a mouse with additional buttons and can make one of his mouse buttons to serve as Ctrl/Shift/Alt key.

Right. I didnt know i was supposed to drag and drop the text and not the field, since thats what the difference is. When you drag and drop you are moving an entity, but when you highlight you are specifically moving text and text only.

Alright, next problem. The popup inside the logger doesnt have a scrollbar, and i cant scroll it downards at all.
Second issue, trying to drag the highlighted text into it shows a blocked cursor all over it.

**Comment by u-RraaLL** [comment]
What's your browser? Check its settings to see if you're not auto-hiding the scrollbar. Also, aren't you using a mouse with a scroll wheel? And if you're using a touchpad, doesn't it have a touch function for scrolling? Another option: after opening the popup, click on it to make it "active" and you'll be able to use arrow keys to navigate.

Blocked cursor? I'm not sure I understand - I don't see anything like that. Can you make a screen recording? Also, please install latest dev version and test there: https://github.com/gorhill/uBlock/releases/tag/1.54.1b21 (though if you're not on FF, it's gonna be a while before the version catches up).

**Comment by gwarser** [comment]
> The popup inside the logger doesnt have a scrollbar

Can be https://github.com/uBlockOrigin/uBlock-issues/issues/3015

**Comment by NastyFlytrap** [comment]
> What's your browser? Check its settings to see if you're not auto-hiding the scrollbar. Also, aren't you using a mouse with a scroll wheel? And if you're using a touchpad, doesn't it have a touch function for scrolling? Another option: after opening the popup, click on it to make it "active" and you'll be able to use arrow keys to navigate.
> 
> Blocked cursor? I'm not sure I understand - I don't see anything like that. Can you make a screen recording? Also, please install latest dev version and test there: https://github.com/gorhill/uBlock/releases/tag/1.54.1b21 (though if you're not on FF, it's gonna be a while before the version catches up).

The scrollwheel doesnt scroll it. Neither do the arrow keys or page up page down. Holding down the scroll wheel and using that directional scroller does work however. Not sure why the rest doesnt.

Its librewolf 120 btw, and i dont believe im auto hiding it because its available literally everywhere else. Clicking on the popup didnt help. 

By the blocked cursor i meant the circle with a line going through it which is universally recognized as a 'forbidden' 'no' 'dont' sign. Hence stop signs.
![IMG_20231223_085406_393](https://github.com/uBlockOrigin/uBlock-issues/assets/43176063/f8253b13-a5ca-4aeb-be4b-37c47c6947e6)

**Comment by u-RraaLL** [comment]
Please install the dev version, like I asked. Based on your screenshot it's the fixed issue that gwarser linked to.

For the forbidden symbol, it not showing on my side (maybe limited to your browser). Does it prevent you from actually drag&dropping though? But again, please first install the latest dev build.

**Comment by garry-ut99** [comment]
u-RraaLL : What's your browser? 

He already provided it in his inintial post.

> NastyFlytrap : By the blocked cursor i meant the circle with a line going through it which is universally recognized as a 'forbidden' 'no' 'dont' sign. Hence stop signs.

It's normal behaviour, it's because you can't drop at the current place, selected text can be dropped only on text input areas, like uBO filter box input field or browser address bar etc. the icon will change/disappear at such text input field then and you will able to drop it (unless you want to say that you still can't drop it at text input areas).

**Comment by NastyFlytrap** [comment]
> Please install the dev version, like I asked. Based on your screenshot it's the fixed issue that gwarser linked to.
> 
> For the forbidden symbol, it's not showing on my side (maybe limited to your browser). Does it prevent you from actually drag&dropping though? But again, please first install the latest dev build.

In the mainstream version, yes, it does. As for the dev version i clicked on this link in the github repo, it asked if i wanted to install it, i allowed it, and nothing happened. https://github.com/gorhill/uBlock/releases/download/1.54.1b21/uBlock0_1.54.1b21.firefox.signed.xpi

> > u-RraaLL : What's your browser?
> 
> He already provided it in his initial post.
> 
> > NastyFlytrap : By the blocked cursor i meant the circle with a line going through it which is universally recognized as a 'forbidden' 'no' 'dont' sign. Hence stop signs.
> 
> It's normal behaviour (at least on Firefox & Opera), it's because you can't drop at the current place, selected text can be dropped only on text input areas, like uBO filter box input field or browser address bar or github comments etc. the icon will change/disappear at such text input field then and you'll be able to drop it (unless you want to say that you still can't drop it at text input areas). 

I am not sure what text dropping areas are there in the ublock popup. Also, yes, i am aware of this, i was just stating it for u-RraaLL

**Comment by garry-ut99** [comment]
> NastyFlytrap: I am not sure what text dropping areas are there in the ublock popup.

None in uBO popup, uBO popup and uBO logger are different things, you have to drag & drop from **uBO popup** to **uBo logger text input field** : https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#filtering-the-logger-output

> NastyFlytrap: Also, yes, i am aware of this, i was just stating it for u-RraaLL

Me too was stating it for u-RraaLL.

**Comment by u-RraaLL** [comment]
> As for the dev version i clicked on this link in the github repo, it asked if i wanted to install it, i allowed it, it downloaded, asked for permissions, and nothing happened. My ublock origin is still version 1.5.4 mainline. 

Either restart your browser to finish the install or click on uBO in `about:addons` and then "Update now". If that doesn't work. Disable uBO, install dev, enable uBO.
