### ISSUE TITLE
Add Finnish Easylist Addition

### ISSUE THREAD

**Issue by Ollifi** [uBlockOrigin/uBlock-issues#304]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Add Finnish Easylist Addition list. This is maintained by other person than the old one which was removed. https://finnish-easylist-addition.github.io/

**Comment by uBlock-user** [comment]
Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.
