### ISSUE TITLE
CNAME uncloaking does not work on Firefox

### ISSUE THREAD

**Issue by enoki45654** [uBlockOrigin/uBlock-issues#3041]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [x] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Domains that use CNAME to redirect to hide trackers/ad domains can be navigated to in Firefox. This is despite uBlock Origin on Firefox supporting CNAME uncloaking.

I have tested with the domain `vrzmfy.fool.com`, which is included in the [AdGuard CNAME tracker list](https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt). It also redirects to `dnsdelegation.io`, which is blocked by Peter Lowe’s Ad and tracking server list.

I have tested this bug on both Windows and Linux and can confirm it to be consistent across both platforms.

### A specific URL where the issue occurs.

vrzmfy.fool.com

### Steps to Reproduce

Navigate to `vrzmfy.fool.com`.

### Expected behavior

Domain would be blocked due to having a CNAME entry redirecting to `dnsdelegation.io`.

### Actual behavior

Domain remains unblocked and can be accessed.

### uBO version

1.54.0

### Browser name and version

Firefox 120.0.1

### Operating System and version

Windows 10 19044.3803 and Ubuntu 20.04 LTS

**Comment by gothic-bum** [comment]
By default, uBO will skip CNAME-lookup for the root document.  
  
Documentation:  
https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnameignorerootdocument
  
You need to set `cnameIgnoreRootDocument` to `false` if you do not want uBO to skip CNAME-lookup for root document.
