### ISSUE TITLE
Ublock origin HSTS security error android

### ISSUE THREAD

**Issue by RealRobertBrownieJr** [uBlockOrigin/uBlock-issues#3042]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When the ublock origin extension is installed in the latest version of firefox for android multiple pages are unable to load and give a HSTS error that is not present with other browsers that do not have ublock installed or even the same browse lr with no ublock installed

Third party CA Certificate options are already enabled but it makes 0 difference 

### A specific URL where the issue occurs.

1337x.to

### Steps to Reproduce

Install ublock on android firefox and try to load a site such as 1337x.to and it does not load at all just gives the above error but works fine without ublock and with other browsers completely fine 

### Expected behavior

Web page to load up with no problem and blocking ads as per desktop version

### Actual behavior

Pages unable to load 

### uBO version

dunno

### Browser name and version

firefox 

### Operating System and version

android 13

**Comment by gorhill** [comment]
`1337x.to` loads fine in Firefox for Android with default settings/lists.

> dunno
> firefox

I don't understand what you are reporting, and given your unwillingness to provide more information, the issue here will be closed as invalid nuless you clarify exactly what is your issue with more useful data and better investigation on your side.

**Comment by RealRobertBrownieJr** [comment]
I don't get what you mean?
I downloaded the latest version of firefox from Google play and unlock from the add-on page when I try to load any pages it gives me that error 😕 I'm not sure what else you want

**Comment by RealRobertBrownieJr** [comment]
![Screenshot_2023-12-23-16-15-47-607_org mozilla firefox](https://github.com/uBlockOrigin/uBlock-issues/assets/108153010/3358e0c5-c6ab-4e7f-bc1b-c6390481bfd9)
![Screenshot_2023-12-23-16-12-17-088_org mozilla firefox](https://github.com/uBlockOrigin/uBlock-issues/assets/108153010/d4a50d21-f044-4538-97a8-4b33cc4acc99)
![Screenshot_2023-12-23-16-12-21-323_org mozilla firefox](https://github.com/uBlockOrigin/uBlock-issues/assets/108153010/cbe7cee7-29ad-418d-87b1-33af0efa1cb0)
![Screenshot_2023-12-23-16-15-43-766_org mozilla firefox](https://github.com/uBlockOrigin/uBlock-issues/assets/108153010/5e9195a1-37c8-4a5b-9b95-1557e5276324)


Here's a few screenshots too it's not just 1337x but others like torrent galaxy here for example 

 Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to because this website requires a secure connection.

What can you do about it?

has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

**Comment by gorhill** [comment]
> that was needed with adguard to get it working

That is an important piece of information. So you are proxying everything through AdGuard. Try disabling "Uncloak canonical names" in Settings. If this doesn't work, you will have to investigate more on your side, I can't reproduce the issue  you are describing and  given that you customized your internet with proxy settings it's likely caused by it. For instance you didn't investigate what happens when you wholly disable AdGuard proxy.

**Comment by RealRobertBrownieJr** [comment]
Ah my bad I mean it like I've not done that with this device but on a previous device I had to enable the CA thing when I used adguard so I thought it was worth a go here when i was having trouble but no joy
