### ISSUE TITLE
100% confirmed bug - ublock origin blocks ability to add comments in YouTube on Chrome

### ISSUE THREAD

**Issue by alowe76** [uBlockOrigin/uBlock-issues#3043]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This issue appeared, for me, the first time today. I noticed that comments posted on YouTube weren't there after I refreshed the page. By default, YouTube sorts for comments first.

Tested this on several channels. Couldn't post a comment anywhere. Not even comments like, "test" and "!". I have received no warning from YouTube that I am restricted so tested whether commenting on the YouTube app worked, and it does.

Deleted my Chrome account and cleared all cache (including password etc), total overkill to make sure I started with a brand new browser profile. Installed uBO again and the problem was still there. Couldn't post any comments - will, they would seem to post but upon refreshing the page they were gone. My Google account has Restricted Mode OFF.

So, on a hunch disabled uBO and the problem is immediately fixed. So, I'm guessing YouTube has changed something that's blocking comment functionality for people who use uBO. If this doesn't affect other people using uBO and YouTube I'll be as confused as hell, but that's why I'm passing it over to you guys who know better. At least it's easily reproducable.

This is my first time ever report of a bug on GitHub, so please be kind - I'm just trying to help.

### A specific URL where the issue occurs.

www.youtube.com

### Steps to Reproduce

1. Install fresh Chrome or wipe all cache completely.
2. With fresh new Chrome account, install uBO.
3. Navigate to www.youtube.com.
4. Attempt to comment on any video. Confirm that it "seems" to post. (it will be visible in the comments section). Keep the comment clean, like "test" so that there's no chance of it being auto-moderated.
5. Refresh the page.
6. If the comment is gone then you have reproduced the issue.
7. You can confirm that the issue is browser based by going to the same video on YouTube app, commenting, and then refreshing the page on your browser. It should now show the comment is posted.

### Expected behavior

1. When posting a comment on the browser version of YouTube it should show as posted even after the page is refreshed.
2. What complicates matters is if your comment gets automatically moderated. That's why the test comment should literally be something simple, like "test".

### Actual behavior

Actual behaviour is exactly as described in the Steps to Reproduce from step 2. onwards, except that step 6. the comment disappears after refresh of the page.

### uBO version

1.54.0

### Browser name and version

Version 120.0.6099.111 (Official Build) (64-bit)

### Operating System and version

Windows 10 Pro 21H2

**Comment by gwarser** [comment]
* [x]  This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).

**Comment by alowe76** [comment]
Argh! It's a false flag. Sorry.

While I was submitting this bug Chrome updated, in the middle of it!
New version is: Version 120.0.6099.130 (Official Build) (64-bit)

So, of course I had to test it all again. And discovered that it takes about 20 to 30 seconds from posting the comment for it to appear after refreshing the page, but it WILL appear with uBO enabled and disabled. It just seems to not appear because it's so very slow.

This fooled me because I've been using YouTube for 2 decades now and it has ALWAYS posted comments instantly. Sooo, perhaps it's something YouTube has introduced to stop spamming, mess up bots, or... I don't know. But it's not uBO that's causing it at all. Sorry for the mixup. I'm working in the blind here with YouTube who DO NOT communicate or help anyone.

What makes it annoying is, if your comment does get moderated, you're refreshing the page for about a minute before you can "maybe" be sure it actually didn't post.

**Comment by gorhill** [comment]
> how [gwarser](https://github.com/gwarser) knew it wasn't an issue faster than I could test it.

You didn't make the case it was not a filter issue, you didn't use any of the built-in tools in uBO and browser dev tools to do so:

> - [x] I verified that this is not a filter list issue

uBO blocks what it's told to block according to filter lists, rules, and your custom filters. If you un-select all filter lists, and remove all rules and the browser's network pane is telling you that uBO is blocking something, then you made the case there is an issue in uBO itself. Otherwise, it's a filter issue, or as in the current case and a common occurrence, it's misdiagnosis.

**Comment by alowe76** [comment]
> [gwarser](https://github.com/gwarser) You didn't make the case it was not a filter issue, you didn't use any of the built-in tools in uBO and browser dev tools to do so:

I said I just used the default settings of uBO in a fresh install. Therefore, if it was a filter issue, it'd be an issue with the default filters, not custom filters. The prerequisite was therefore correctly declared. I verified it wasn't a filter issue already in my submission. And why would a first time user have detailed knowledge of uBO filter mechanism anyway? That's not being realistic. We can't all be experts.

**Comment by gorhill** [comment]
> if it was a filter issue, it'd be an issue with the default filters, not custom filters. The prerequisite was therefore correctly

No it was not, nowhere does it say it's only about custom filters:

> - [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

If you want to keep being argumentative about all this, I invite you to remove uBO and install another blocker.
