### ISSUE TITLE
Keeps disabling instantly on this page. https://stackoverflow.com/questions/27595679/how-to-efficiently-retrieve-expiration-date-for-facebook-photo-url-and-renew-it

### ISSUE THREAD

**Issue by Gawd21** [uBlockOrigin/uBlock-issues#3044]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When going to this page https://stackoverflow.com/questions/27595679/how-to-efficiently-retrieve-expiration-date-for-facebook-photo-url-and-renew-it uBO disables and will not re-enable. I click the "power" button to enable it and it lights up and then dims down right away, leaving uBO disabled/grey.

### A specific URL where the issue occurs.

https://stackoverflow.com/questions/27595679/how-to-efficiently-retrieve-expiration-date-for-facebook-photo-url-and-renew-it

### Steps to Reproduce

Visit https://stackoverflow.com/questions/27595679/how-to-efficiently-retrieve-expiration-date-for-facebook-photo-url-and-renew-it
Notice uBO is grey, click on it to bring up option to enable/disable and click on it to enable
Notice that it has quickly disabled it's self.

### Expected behavior

to enable and allow me to reload the page without the ads and the cookie popup.

### Actual behavior

will not enable and forced to deal with the ads and the cookie popup.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 416499
 cosmetic: 307058
 scriptlet: 54568
 html: 1451
listset (total-discarded, last-updated):
 added:
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 4h.43m
  https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt: 42535-1455, 4h.42m
  adguard-generic: 81416-8226, 1d.23h.23m
  adguard-mobile: 8922-220, 1d.23h.23m
  adguard-spyware-url: 1366-92, 1d.23h.23m
  adguard-spyware: 81717-17457, 1d.23h.23m
  block-lan: 55-0, 19d.59m
  curben-phishing: 79574-31, 4h.42m
  adguard-social: 22113-1577, 1d.23h.23m
  adguard-cookies: 28232-1635, 1d.23h.23m
  ublock-cookies-adguard: 819-0, 1d.23h.23m
  adguard-popup-overlays: 26668-1671, 1d.23h.23m
  [49 lists not shown]: [too many]
 default:
  user-filters: 9-0, never
  ublock-filters: 37357-1027, 4h.43m
  ublock-badware: 7698-11, 4h.43m
  ublock-privacy: 948-5, 4h.43m
  ublock-unbreak: 2223-11, 4h.43m
  ublock-quick-fixes: 136-0, 4h.43m
  easylist: 76289-17392, 4h.43m
  easyprivacy: 33152-1312, 4h.43m
  urlhaus-1: 11135-0, 4h.43m
  plowe-0: 3781-1, 6d.5h.34m
filterset (user): [array of 9 redacted]
trustedset:
 added: [array of 20 redacted]
 removed:
  chrome-extension-scheme
  chrome-scheme
  edge-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 colorBlindFriendly: true
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 890 ms (selfie)
 maxAssetCacheWait: 218 ms
```
</details>

**Comment by Gawd21** [comment]
Now uBO has completely crashed and won't even load on any page.

**Comment by Gawd21** [comment]
Reinstall fixed the issue. I believe the problem came from the [grc.com ](https://www.grc.com/dns/dns.htm) DNS Spoof Test on the bottom of that page. It was shortly after that I was on the stackoverflow page and discovered uBO not working.

**Comment by krystian3w** [comment]
For me regex in trusted list (of domains don't) disable `trusted-click-element` (rest scriptlets may disabled to run), but I can't create minimal online demo without share company app with private data.

**Comment by gwarser** [comment]
@krystian3w please create issue or discussion with steps to reproduce.

**Comment by krystian3w** [comment]
I can't cleanup webpage to share, I guess gorhill reject screenshot with dynamic added blur on private data/logo+URL.

Also I don't want itself found bug in Browser or addon code.
