### ISSUE TITLE
tab bar and search bar while viewing a fliterlist

### ISSUE THREAD

**Issue by idontveapc** [uBlockOrigin/uBlock-issues#3047]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

it might be again but it's not the same as before, though the issue is the same. and it's still instant.

### A specific URL where the issue occurs.

/ublock origin/

### Steps to Reproduce

- while in a filterlist, input a letter or a domain
- as soon as you'll press enter...
  - ...the search bar and tabbar above it go up on kiwi/(other chromium browser for Android with extension support) making navigation inaccessible and going back would mess everything. *(and you'll loose your edit.)*

### Expected behavior

> [!NOTE] 
> it's not possible to get the tabbar again onscreen after it's gone*(up)* and you have to refresh and (in a filterlist or my filters) choose a different tab very swiftly.

it must be either...
- [ ] onscreen (so you don't have to anything to make it appear)
or...
- [ ] make them bar appear when when scrolling down.

### Actual behavior

tab bar and search bar going up and hide in filterlist *(on kiwi)* and in tab bar in my filters

### uBO version

1.54.0

### Browser name and version

Kiwi Browser 120.0.6099.116

### Operating System and version

* *

**Comment by gorhill** [comment]
Kiwi browser is not supported. If you want something in uBO is broken specifically on it, please investigate the cause and the fix, then I will consider whether it's something I would want to import in uBO.

**Comment by gorhill** [comment]
Actually it's the third time you open an issue for kiwi browser while you were told in the first one it's not supported: <https://github.com/uBlockOrigin/uBlock-issues/issues/2791>.

Do not do this again please.
