### ISSUE TITLE
Option `Disable hyperlink auditing` has no effect in android

### ISSUE THREAD

**Issue by bAH7JgbXrMsXEhggm4** [uBlockOrigin/uBlock-issues#3049]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I have enabled the option:

![Screenshot from 2023-12-30 23-50-21](https://github.com/uBlockOrigin/uBlock-issues/assets/152476894/a6e9512e-b933-41ea-b3b8-12e7d2d151e7)

However, long pressing a link in the Google search results, the link are not processed and look like this:

![Screenshot from 2023-12-30 23-50-52](https://github.com/uBlockOrigin/uBlock-issues/assets/152476894/c502321e-4de3-4160-876c-3ddf48eb38cc)

On Firefox desktop this option works, however, on Android it doesn't work,So I think this is not a filter problem

### A specific URL where the issue occurs.

https://www.google.com/search?q=good+afternoon

### Steps to Reproduce

1. install mull browser from f-droid market
2. Install ublock from firefox official store
3. Enable all filter lists and add the custom filter [https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt transition list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt)
4. Disable `Uncloak canonical names` and keep other defaults

### Expected behavior

Shows the site's own links, just like in firefox desktop

### Actual behavior

![Screenshot from 2023-12-30 23-50-52](https://github.com/uBlockOrigin/uBlock-issues/assets/152476894/15d86e61-eeab-4581-bd6b-b98c259cb07f)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox Mobile: 121
filterset (summary):
 network: 308639
 cosmetic: 204165
 scriptlet: 49863
 html: 1330
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2542-157, never
  adguard-generic: 81575-5980, never
  adguard-spyware-url: 1378-93, never
  adguard-spyware: 82406-17915, never
  block-lan: 55-0, never
  curben-phishing: 79823-28, never
  adguard-social: 22154-1197, never
  adguard-cookies: 28253-1627, never
  ublock-cookies-adguard: 873-0, never
  adguard-popup-overlays: 26728-1011, never
  adguard-mobile-app-banners: 4868-1103, never
  adguard-other-annoyances: 13992-784, never
  [12 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37580-396, 11m
  ublock-badware: 7563-11, 11m
  ublock-privacy: 948-5, 11m
  ublock-unbreak: 2227-2, 11m
  ublock-quick-fixes: 162-0, 11m
  adguard-mobile: 8949-132, 12m
  easylist: 76515-16728, 11m
  easyprivacy: 33168-820, 11m
  urlhaus-1: 9965-0, 11m
  plowe-0: 3784-1, 11m
filterset (user): [empty]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 31 redacted]
userSettings:
 advancedUserEnabled: true
 cnameUncloakEnabled: false
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5545 ms
 maxAssetCacheWait: 17 ms
```
</details>

**Comment by iam-py-test** [comment]
Neither the "Disable hyperlink auditing" setting nor the *Actually Legitimate URL Shortener Tool* filterlist are designed to clean those Google links.
However, *uBlock - Annoyances* filterlist does.
Thanks

**Comment by u-RraaLL** [comment]
That option has nothing to do with redirects.

It is a filter issue, because if you use logger to temporarily disable the `set-constant` scriptlet on desktop, the behavior will be the same.

**Comment by gorhill** [comment]
Hyperlink autditing prevent `ping` request upon clicking a link, nothing more.
