### ISSUE TITLE
Firefox Stack Protection does not work with uBO

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [uBlockOrigin/uBlock-issues#3052]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Firefox Security Sandbox Content Shadow Stack enablement in about:config prevents uBO, NoScript, and some other extensions (not all), from loading and working.

### A specific URL where the issue occurs.

Any

### Steps to Reproduce

Enable Firefox Security Sandbox Content Shadow Stack in about:config and restart Firefox.

### Expected behavior

uBO works

### Actual behavior

uBO does not work

### uBO version

Any

### Browser name and version

Firefox 121

### Operating System and version

Windows 11 with Hardware Mode Kernel Stack Protection enabled

**Comment by gwarser** [comment]
- what this is?
- why you think it should be enabled
- why you think it's uBO issue

**Comment by GY8VSdYYzvL8-K6T** [comment]
Its for kernel protection and is one of security features Microsoft groups together with DEP (Data Execution Prevention), CFG (Control Flow Guard), ASLR, memory isolation, but they have different functions, not necessarily related to kernel space. More information can be found here - https://techcommunity.microsoft.com/t5/windows-os-platform-blog/understanding-hardware-enforced-stack-protection/ba-p/1247815 .

If you enable stack protection option in Mozilla Firefox in about:config and inspect a running firefox.exe process with a task manager (such as System Informer) that shows details, then you will find a new flag labeled "stack protection" is added to firefox.exe process.

It is a relatively new feature and developers slowly integrate it into their software. I don't know if extensions are going to require any special coding to be fully compatible with stack protection enablement in Mozilla Firefox. I just know that uBO does not work when stack protection is enabled within Mozilla Firefox settings, but some extensions work with it without issues.

**Comment by gorhill** [comment]
uBO is just HTML/CSS/JS, it doesn't know about low-level stuff below this.
