### ISSUE TITLE
Strange bug in the "show more" button in some Youtube comments.

### ISSUE THREAD

**Issue by Dektsuki** [uBlockOrigin/uBlock-issues#3054]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

For a while now I've noticed that some comments on YouTube (on any channel) tend to be "incomplete". That is to say, normally when a message is long the “show more” button usually appears, but in this case that button does not usually appear and is only left at three points. I thought maybe this was due to some extension other than UB, since I have other extensions that affect YouTube, so I removed them all and left only UB, but that error persisted. The workaround I found for when this happens is to toggle between "remote sources" filtering by turning it on and off, then reloading the tab, but despite this, other comments further down the list still suffer from that bug. I would like to know if I am doing something wrong or if it is a normal effect of UB. Note: UB has 1 custom filter, but that shouldn't be the cause, but even weeks ago before adding said filter, the comments error was already happening.

Image 1 - Bug : < https://ibb.co/94yBBnf >
Image 2 - Bug : < https://ibb.co/LxPwRHk >
Imagen 3 - Buton no hiden : < https://ibb.co/b5PXWv2  > 

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=L0W5ATha6FI

### Steps to Reproduce

Step 1: Open the link I sent (a music video).

Step 2: Scroll down the comments and check for "incomplete" comments.

Step 3: Try to find the same comments as the images.

### Expected behavior

I was expecting the "show more" button to appear on long comments.

### Actual behavior

The button is hidden/does not appear in some comments (not all), only in a few comments.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 118
filterset (summary):
 network: 107665
 cosmetic: 50510
 scriptlet: 20232
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  easylist: 76530-15, 1h.26m
  easyprivacy: 33212-65, 1h.26m
  plowe-0: 3785-1155, 11d.25m
  spa-0: 3774-20, 8h.27m
  spa-1: 5692-209, 2d.23h.47m
  ublock-badware: 7725-137, 1h.26m
  ublock-filters: 36437-238, 1h.26m
  ublock-privacy: 955-8, 1h.26m
  ublock-quick-fixes: 157-49, 1h.26m
  ublock-unbreak: 2173-34, 1h.26m
  urlhaus-1: 10045-0, 8h.27m
filterset (user): [array of 1 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 1294 ms (selfie)
 maxAssetCacheWait: 144 ms
```
</details>

**Comment by gorhill** [comment]
> - [x] I verified that this is not a filter list issue.

I don't see any details supporting that you verified this is not a filter issue. Closing as invalid.
