### ISSUE TITLE
[feature] having a timeout setting to automatically close a "blocked sheet" ?

### ISSUE THREAD

**Issue by fredmo** [uBlockOrigin/uBlock-issues#3056]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello,
Well, when there is an advert that opens a new tab Firefox, there is the ublock message 
"
uBlock₀ a empêché le chargement de la page suivante :
https://nabauxou.net/4/6097334
À cause du filtre suivant :
/^https?:\/\/(?:ak\.)?[a-z]{6,12}\.(?:com|net)\/4\/\d{7}/$document
Trouvé dans :
    [uBlock filters – Ads](moz-extension://f7707908-4fe5-41aa-ac21-6ecc912329e7/asset-viewer.html?url=ublock-filters)     
Ne plus m'avertir à propos de ce site
"

Fine, thanks, but would it be possible to close, this new tab with a timeout setting automatically? 

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

I need to close it manually.

and if I check the open "Ne plus m'avertir à propos de ce site" , I can't press on "Fermer cette fenetre" , I would have only the option "Poursuivre" .

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 123
filterset (summary):
 network: 124373
 cosmetic: 53377
 scriptlet: 18661
 html: 1980
listset (total-discarded, last-updated):
 default:
  user-filters: 102-16, never
  ublock-filters: 37044-361, 1h.48m
  ublock-badware: 7729-11, 1h.48m
  ublock-privacy: 951-0, 1h.48m
  ublock-unbreak: 2219-0, 1h.48m
  ublock-quick-fixes: 171-0, 1h.48m
  easylist: 76533-546, 1h.48m
  easyprivacy: 33212-854, 1h.48m
  urlhaus-1: 10065-0, 1h.48m
  plowe-0: 3787-1, 6d.1h.8m
  FRA-0: 28985-402, 2d.19m
filterset (user): [array of 102 redacted]
trustedset:
 added: [array of 1 redacted]
switchRuleset:
 added: [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6419 ms (selfie)
 maxAssetCacheWait: 3515 ms
```
</details>

**Comment by gorhill** [comment]
> would it be possible to close, this new tab with a timeout setting automatically?

That's what the `popup` filter option is for, so you need to report where you get those popup tab to uAssets, it's a filter list issue.

**Comment by fredmo** [comment]
uBlock₀ a empêché le chargement de la page suivante :

https://nabauxou.net/4/6097334

À cause du filtre suivant :

/^https?:\/\/(?:ak\.)?[a-z]{6,12}\.(?:com|net)\/4\/\d{7}/$document
Trouvé dans :

    **[uBlock filters – Ads]**(moz-extension://f7707908-4fe5-41aa-ac21-6ecc912329e7/asset-viewer.html?url=ublock-filters)


It is an ublock filters
