### ISSUE TITLE
[src*="google.com/recaptcha"] Causes Blank Website

### ISSUE THREAD

**Issue by BlazeFTL** [uBlockOrigin/uBlock-issues#3060]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Blank Page If `gigody.com##.soractrl, [src*="google.com/recaptcha"]:others()`
Is Used

### A specific URL where the issue occurs.

`https://mkvcinemas.foo/?a78422d8da=QnlxV2hJRGpZNzNqQXR1Rkg2NkZmTkpNSUFuelF3c2tRUHhDSStxRm00YUx1S2ErWUJZYUFOVHA1WFBaQzlGYXFDclF1cjdzNkMzdEI1WlhlSWJVUG9HYlpxZjdHN3A4eURHL1l1YnlhSjA9`

Using ^ With Starting URL Will Fix It
`[src^="https://www.google.com/recaptcha/api2/"]`
IDK If This Should Be Reported Or Not

### uBO version

Latest Dev

### Browser name and version

FF Nightly Android

### Operating System and version

*

**Comment by gwarser** [comment]
Seems to happen when element from header and body are selected. Even here `##script,p:others()` will hide everything.

**Comment by gorhill** [comment]
Right, the code checks to not hide `body` but it doesn't check to not hide `html`, I didn't take into account a match could be found in `head`.
