### ISSUE TITLE
Extend addEventListenerDefuser to support defusing based on the element

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#3061]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Go to:
`https://subkade.ir/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D8%B2%DB%8C%D8%B1%D9%86%D9%88%DB%8C%D8%B3-%D8%B3%D8%B1%DB%8C%D8%A7%D9%84-prison-break/`

Click on "دانلود زیرنویس" (`##a.indirect`), you'll get another page where you have to click on "برای ادامه اینجا کلیک کنید" (`##a.sk-dl`), then you'll get a 6 seconds timer to download the subtitles.

The main download link looks like this:
```html
<a data-get="https://dl1.subkade.ir/wp-content/uploads/2019/07/Prison-Break-S01-Complete.zip" target="_self" oncontextmenu="return false;" class="indirect">دانلود</a>
```

Add this to fix the link:
```adb
subkade.ir##+js(set-attr, a.indirect[data-get], href, [data-get])
```

The download link is still not working, because of the following "click" event listener:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/17685483/c3d5890a-0124-4cb8-9007-c701096b8023)

Add this to fix it:
```adb
subkade.ir##+js(aeld, click, return"undefined")
```

The download link is working, but now the "زیرنویس انگلیسی" (`##.lock.sk-download-list`) section is broken because it used the same "click" event listener.

Solution:
```js
// ==UserScript==
// @name        Subkade.ir
// @namespace   Violentmonkey Scripts
// @match       http://*.subkade.ir/*
// @match       https://*.subkade.ir/*
// @grant       none
// @author      PersianBlocker
// @run-at      document-start
// ==/UserScript==


(function() {
  'use strict';

  self.EventTarget.prototype.addEventListener = new Proxy(self.EventTarget.prototype.addEventListener, {
    apply(target, thisArg, args) {
      const node = thisArg;
      if (args[0] === 'click' && node.nodeName === 'A' && node.className && node.className === 'indirect') {
        if (args[1].toString().includes('return"undefined"') === true) {
          return;
        }
      };
      return Reflect.apply(target, thisArg, args);
    }
  })

}) ();
```

Maybe add a forth optional positional argument?
```adb
subkade.ir##+js(aeld, click, return"undefined", a.indirect)
```

**Comment by D4niloMR** [comment]
Doesn't defuse the event listener here: `https://comikey.com/read/that-inferior-knight-level-999-manga/DQYlaD/chapter-1-1/`

`comikey.com##+js(aeld, contextmenu, , elements, #br-book)` doesn't work while manually disabling the event listener works.

Add to test:

```adb
comikey.com#@#+js(aeld, contextmenu, undefined)
comikey.com##+js(aeld, contextmenu, undefined, elements, #br-book)
```

**Comment by gorhill** [comment]
> Can uBO report the respective element when using the `log` vararg?

`log` vararg doesn't exist anymore. In the next dev build, selector information for the element on which `addEventListener` is called will be output in the logger, after the function text.

> Doesn't defuse the event listener here

Many quirks which should be fixed in next dev build:

- The handler can be an interface with a `handleEvent` property -- the scriptlet was not taking this into account
- The element may not have been added to the DOM yet, this needs to be taken into account
- Use the now logged selector to find out how to target a specific element -- in the current instance the target element's `id` was not set when `addEventListener` is called.

**Comment by D4niloMR** [comment]
Can `japscan.lol##+js(aeld, load, _0x, elements, window)` be supported? I want to defuse load events of obfuscated code, but this also defuses the load event of a bunch of images.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/commit/91ee5bdeae6981cc20038b6610ab5c16b58623cf

**Comment by garry-ut99** [comment]
Worth to add, that when the scriptlet gets broken by an invalid selector, the whole page gets broken, empty and black, at least with this example filter: `lenz.ir##+js(aeld, click, a, elements, ##.signup-button.clickable)`: [SCREENSHOOT](https://github.com/user-attachments/assets/a954b472-b418-4926-b67a-165ccbd65100).
