### ISSUE TITLE
utm_content parameter is not being removed

### ISSUE THREAD

**Issue by fenopa** [uBlockOrigin/uBlock-issues#3064]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This doesn't look like a filter issue, utm_content parameter is already in the "AdGuard URL Tracking Protection" filter but it's not being removed and I can't find any exception filter that would prevent it from being removed.
It also doesn't look like it's about the "Cosmetically added params" like mentioned in a few similiar issues like https://github.com/uBlockOrigin/uBlock-issues/issues/2498
because just try to directly open the link and that's a network request and the parameter is not removed.
so that's why I'm opening a new issue.

### A specific URL where the issue occurs.

https://www.deezer.com/en/track/143032368?utm_content=track-143032368&deferredFl=1

### Steps to Reproduce

Open the URL

### Expected behavior

utm_content parameter is removed

### Actual behavior

utm_content parameter is not removed

### uBO version

1.55.0

### Browser name and version

Firefox

### Operating System and version

Windows

**Comment by gwarser** [comment]
> utm_content parameter is already in the "AdGuard URL Tracking Protection"

Where? I don't see it. Param is correctly removed by "➗ Actually Legitimate URL Shortener Tool" list.

**Comment by gwarser** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/dcc77b6d-c4f7-4794-96ae-86a1bc9bd090)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/33ea8202-8941-4edd-8664-49da8d4639c3)

**Comment by gwarser** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/170206#issuecomment-1883802508

**Comment by gorhill** [comment]
> `utm_content` parameter is already in the "AdGuard URL Tracking Protection"

It's not:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/01b3411f-96e3-4f39-9e1a-801daf6d964c)
