### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by Tarkur** [uBlockOrigin/uBlock-issues#3068]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

it detect adblocker

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=STOvRjKMtKk

### Steps to Reproduce

1. go to youtube
2. click the video

### Expected behavior

It playing the video without ads

### Actual behavior

it detects my adblocker

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 117635
 cosmetic: 46866
 scriptlet: 20365
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  SWE-1: 4585-4, 6h.58m
  easylist: 76982-18, 1h.27m
  easyprivacy: 43408-38, 1h.27m
  plowe-0: 3784-1163, 9d.7h.50m
  ublock-badware: 7774-137, 1h.27m
  ublock-filters: 36396-128, 1h.27m
  ublock-privacy: 962-7, 1h.27m
  ublock-quick-fixes: 186-50, 1h.27m
  ublock-unbreak: 2187-31, 1h.27m
  urlhaus-1: 10325-0, 1h.27m
filterset (user): [empty]
trustedset:
 removed:
  chrome-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 364 ms (selfie)
 maxAssetCacheWait: 168 ms
```
</details>

**Comment by mapx-** [comment]
go to https://github.com/uBlockOrigin/uAssets/issues/20586
