### ISSUE TITLE
The "requests blocked" menu do not reacts, do not allow me to whitelist certain element

### ISSUE THREAD

**Issue by slrslr** [uBlockOrigin/uBlock-issues#307]
### Description

Hello, when i was using uBlock on WIndows 10 like 3 months back i remember when i was on some website where uBlock blocked some element inappropriately (this time on https://billing.buycpanel.com/bill1/clientarea.php?action=invoices it blocks cdn.livechatinc.com), then i was able to click uBLock icon, then click "requests blocked" then i was able to click + or - to allow blocked request and make changes permanent. Now when i click something in that "requests blocked" menu, it does nothing. Is there any error? That feature to unblock some element this way was very handy..

### Your environment

* uBlock Origin version: uBlock Origin 1.17.2
* Browser Name and version: Firefox 63.0.1 64bit
* Operating System and version: Linux Debian

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Advanced-user-features

Disabling Dynamic Filtering will disable firewalle popup pane too.

**Comment by slrslr** [comment]
Thank you, ok so for others with same problem, You have to open uBlock Settings panel and enable "I am an advanced user (required reading)".

It can be handy if uBlock shows a tooltip when i hover mouse over the + and - section of the "requests blocked" menu saying:
To enable dynamic filtering, you have to tick "I am an advanced user" option in Settings.

**Comment by uBlock-user** [comment]
`requests blocked` nothing to do with Dynamic Filtering, it only expands and contracts the firewall popup filter pane. You're expected to go through all settings atleast once after installing the extension.

**Comment by slrslr** [comment]
> You're expected to go through all settings atleast once after installing the extension.

Developers and geeks does this, but regular user who just want to block ads, is not there to study what each configuration option like "I am an advanced user (required reading)" does. You should be more user friendly like showing a tooltips when i move mouse cursor over the dynamic firewall area. When these are there, the firewall area can be enabled by default.

**Comment by uBlock-user** [comment]
> You should be more user friendly like showing a tooltips when i move mouse cursor over the dynamic firewall area.

This is not a user-support forum, post on reddit for that if you expect that kind of service.
