### ISSUE TITLE
Third party requests stopping subdomains to load when redirected

### ISSUE THREAD

**Issue by abdullahdevrel** [uBlockOrigin/uBlock-issues#3072]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

*Please note that the reproducibility of this bug is difficult.*

### Context

`community.ipinfo.io` points to a [Discourse](https://discourse.org)-based platform hosted through a subdomain of `ipinfo.io`. `ipinfo.io` itself is listed in a third-party blacklist under easylist ([Easylist 3p](https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers_mining.txt#L113)). However, third party (3p) listings does not affect direct access to the site, subURL or any subdomain. This only affects when third-party websites call the API endpoint of `ipinfo.io`.

But in some instances, especially when redirected through a shortened link, the subdomain gets caught under the 3p ruleset, even though it shouldn't be. 

After discussing this issue in Easylist, I noticed that uBlock sometimes misidentifies `document` request (according to browser dev tools) with `xhr` request. This impacts subdomain-level requests with third-party API requests. 

### Summary details

This issue is difficult to reproduce; however, I have noted a few points:

- This usually happens when the link is wrapped in a shortened URL (such as t.co or lnkd.in), notably when the link is coming from a social media site like Twitter, LinkedIn, or Facebook.
- The behavior is different between incognito sessions and normal sessions. The issue happens more frequently in normal session mode.
- If you disable uBlock on the community.ipinfo.io site but still want to visit the site through a shortened URL, it will sometimes still block the site under the 3p rule.

In the following sections I will provide details.

### Due diligence

To figure out the issue, I reached out to Discourse. They said it was a problem with the adblocker extension.

I also opened an issue with Easylist, and one of the maintainers could not reproduce the issue. They also mentioned that 3p listings should not impact subdomain-level access. https://github.com/easylist/easylist/issues/18194

There was a similar issue with Adguard. However, they did not mention the impact of redirection. https://github.com/AdguardTeam/CoreLibs/issues/1637

I have also reviewed the issues here.

I can demonstrate that this issue exists, and we have received many user reports regarding this.

### The challenge

This issue might not be just related to uBlock but many other adblocking services, however, as this is rather a difficult bug reproduce, I am essentially working with a black box, and nothing to work with beyond it doesn't work. 

### A specific URL where the issue occurs.

https://t.co/JJ0ETzNHSu

### Steps to Reproduce

1. Visit `https://t.co/JJ0ETzNHSu`
2. `https://t.co/JJ0ETzNHSu` is a shortened link that points to `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201`
3. If you can access the Twitter shortened link (`https://t.co/JJ0ETzNHSu`) through incognito mode try it through the normal session
4. If you still can access the site, please, see my video and see if you find anything of interesting. 
5. If you can't access the site, note the uBlock logger and dev tools 

https://github.com/uBlockOrigin/uBlock-issues/assets/111275753/8c411a93-2378-432f-b33c-faa06fbf2951

---

https://github.com/uBlockOrigin/uBlock-issues/assets/111275753/df3541c7-2691-43f5-9f1f-52d82d65ba52

On the left, I have a standard browser session. On the right, I have incognito mode session. In both instances, the uBlock origin is activated. In the standard browsing session, the request gets blocked, but in incognito, the request passes through.

Log output from the standard browsing operation (latest to oldest up to 4 events):

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | community.ipinfo.io | 0,3 | get | script | `https://global.discourse-cdn.com/standard17/assets/workbox-9b5674ca0ecb89bae1fa6f4b09a18f12/workbox-cacheable-response.prod.js` |
| +2 |  |  | community.ipinfo.io | 0,1 | get | script | `https://community.ipinfo.io/service-worker.js` |
| +1 | \|\|ipinfo.io^$3p | -- | t.co | 0,3 | get | xhr | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 | \|\|ipinfo.io^$3p | -- | t.co | 0,3 | get | xhr | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 |  |  | t.co | 1 | get | doc | `https://t.co/JJ0ETzNHSu` |
</details>

Log output from the incognito browsing operation (latest to oldest up to 4 events):

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | community.ipinfo.io | 1 | get | script | `https://community.ipinfo.io/plugins/discourse-client-performance/javascripts/discourse-client-performance.js?v=a5516f42f069cc08ed87ab2eb67fdc84e564d687a11b22972a24b0911180c320` |
| +2 |  |  | community.ipinfo.io | 3 | get | script | `https://global.discourse-cdn.com/standard17/assets/start-discourse-7c0f5f4daf3c942b7b6ecfe8e62e2e5a0f6555924859cf055314c0df3d617353.br.js` |
| +0 |  |  | community.ipinfo.io | 1 | get | doc | `https://community.ipinfo.io/t/preventing-credential-stuffing-attacks-with-ipinfo/1201` |
| +0 |  |  | t.co | 1 | get | doc | `https://t.co/JJ0ETzNHSu` |
</details>

![UPVWxyu0yR](https://github.com/uBlockOrigin/uBlock-issues/assets/111275753/9971b3ac-f963-411c-a277-122f918163a3)

Comparing this two browsing traffic, in the incognito session, the second request is labeled as `doc`, while in the standard session, the first request is labeled as `xhr`. 

However, in the standard browsing sessions, according to the network information in devtools the request are not `xhr` but rather `doc`. But considering the parameters between normal and incognito sessions are identical, uBO seemingly appears different to me.

### Expected behavior

The expected behavior should be a shortened link (`https://t.co/JJ0ETzNHSu`) completing its redirection and being able to access the full link, thus allowing the user to visit the site.

https://github.com/uBlockOrigin/uBlock-issues/assets/111275753/752ac12f-419e-4fcf-aec2-4e80a34a8745

### Actual behavior

The actual behavior is that the shortened link (`https://t.co/JJ0ETzNHSu`) actually gets blocked through 3p ruleset.

Please note the following behavior. The right side is a normal session and left is an incognito session.

https://github.com/uBlockOrigin/uBlock-issues/assets/111275753/df3541c7-2691-43f5-9f1f-52d82d65ba52

The right side demonstrate the actual behavior, while the left is the expected behavior.

### uBO version

uBlock Origin 1.54.0

### Browser name and version

Microsoft Edge Version 120.0.2210.91

### Operating System and version

Windows 11

**Comment by gwarser** [comment]
The "standard browser session" uses cached service worker?

**Comment by gorhill** [comment]
> I noticed that uBlock sometimes misidentifies document request (according to browser dev tools) with xhr request.

Problem is that uBO is being given that information by the browser:

![Screenshot from 2024-01-13 09-23-03](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/a50d9e7c-1746-4712-8e20-91af43403636)

I am pretty sure the initiator is the service worker, in which case this means chromium is giving the extension erroneous information, and I don't see how uBO would be able to "fix" that erroneous information.

"AdGuard Tracking Protection filter" does not have that `||ipinfo.io^$3p`, that is the reason AdGuard does not suffer the issue. It instead has `||pixel.ipinfo.io^`. It also suffers the issue if you add the filter:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/1b1470d2-fcb6-433f-9ff6-157687053e0d)

Since ABP/AdBlock uses EasyPrivacy, they also suffer the issue.

I do not get the issue with Firefox, the source `xhr` request is properly set to `community.ipinfo.io`.

A workaround for this will have to be filter-based.

Either we create a filter to prevent the site from using a service worker:

    ||community.ipinfo.io^$csp=worker-src 'none'

Or we ask EasyPrivacy to do what AdGuard did and replace `||ipinfo.io^$3p` with `||pixel.ipinfo.io^`.

**Comment by gorhill** [comment]
For now I added `||community.ipinfo.io^$csp=worker-src 'none'` to "uBlock filters -- Unbreak" so that the issue gets fixed immediately. If ever EasyPrivacy revise `||ipinfo.io^$3p`, we can remove that filter.

**Comment by stephenhawk8054** [comment]
Should we narrow it down to chromium only?

**Comment by gorhill** [comment]
Yes, you're right, I didn't think about this.

**Comment by Yuki2718** [comment]
> If ever EasyPrivacy revises ||ipinfo.io^$3p, we can remove that filter.

I doubt @ryanbr to agree. Will close the issue.

**Comment by abdullahdevrel** [comment]
Thank you very much for the help. I will reach out to other adblock extensions to add the ruleset you added. I appreciate the help.

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/1ageuc4/overclockerscouk_blocking_pages_due_to_ublock/kogkhzl/

1. visit forum from search page https://www.google.com/search?q=site%3Aforums.overclockers.co.uk
2. make sure SW is active (second load)
3. there is no doc request
4. navigation from Google is blocked as 3p
5. soft refresh is also stuck as 3p to Google and blocked

**Comment by gorhill** [comment]
If I use `||overclockers.co.uk^$3p` with AdGuard or ABP, same issue.

Filter was added [in this commit](https://github.com/uBlockOrigin/uAssets/commit/bcec146e383), I removed it.
