### ISSUE TITLE
uBlock ignores source set in advanced setting `userResourcesLocation`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#3075]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Since uBlock version 1.55.0 it doesn't recognize the script code in imported via `userResourcesLocation` in the advanced settings pane.

This issue both occurs in Firefox and Microsoft Edge. 

### A specific URL where the issue occurs.

```yaml
My filters pane
```

### Steps to Reproduce

1. Add a remote script resource in the advanced settings pane at `userResourcesLocation` (e.g. `https://raw.githubusercontent.com/JohnyP36/Personal-List/main/other%20lists/my-scriptlets.js`)
2. Add `marktplaats.nl##+js(ceo, .message-container > #notice button[class*="sp_choice_type_"][title="Accepteren"], , 20000)` to your own filter rules in the "My filter" pane
3. See that uBlock marked `ceo` red/orange *and that there is no indication of a wrong rule*
4. If you set your VPN to a city in the Netherlands/Belgium, you would also see that the cookie consent banner is not clicked

### Expected behavior

Imported script files at `userResourcesLocation` should be recognized by uBlock and the rules in the My Rules pane should just work. 

### Actual behavior

uBlock doesn't recognize the code in the file and thus rules based on it don't work.

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 121
filterset (summary):
 network: 98465
 cosmetic: 46790
 scriptlet: 18436
 html: 1936
listset (total-discarded, last-updated):
 removed:
  ublock-badware: null
  ublock-privacy: null
  urlhaus-1: null
  plowe-0: null
  NLD-0: null
 added:
  https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/Dutch-Filter-List.txt: 2762-0, 2d.22h.6m
  https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/enhancedstats-addon.txt-old: 2771-7, 2d.5h.50m
 default:
  user-filters: 343-0, never
  ublock-filters: 36969-135, 5h.18m Δ
  ublock-unbreak: 2234-2, 5h.18m Δ
  ublock-quick-fixes: 232-0, 5h.18m Δ
  easylist: 77310-136, 5h.18m Δ
  easyprivacy: 43423-60, 5h.18m Δ
filterset (user): [array of 251 redacted]
trustedset:
 added: [array of 5 redacted]
 removed:
  about-scheme
hostRuleset:
 added: [array of 8 redacted]
urlRuleset:
 added: [array of 9 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 suspendUntilListsAreLoaded: false
hiddenSettings:
 autoCommentFilterTemplate: -
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupFontSize: 11px
 popupPanelLockedSections: 35
 popupPanelHeightMode: 1
 trustedListPrefixes: ublock- user- https://raw.githubusercontent.com/JohnyP36/Personal-List/cdn-page/Dutch-Filter-List.txt
 uiStyles: --popup-main-min-width: 168px; --popup-gap: 7.5px; --popup-gap-thin: calc(var(--popup-gap)/9); --popup-power-ink: rgb(0,110,254); --popup-ruleset-tool-surface: rgb(240,190,64); --popup-ruleset-tool-surface-hover: rgb(240,190,64); --popup-toolbar-surface: rgb(226,226,229); --popup-toolbar-surface-hover: rgb(32 18 58 / 40%); --popup-icon-x-ink: rgb(226,40,80);
 updateAssetBypassBrowserCache: true
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 673 ms (selfie)
 maxAssetCacheWait: 498 ms
 cacheBackend: indexedDB
 unsuspendAfter: 114 ms
```
</details>

**Comment by gorhill** [comment]
> does uBlock not recognize the redirect source `addthis.com/addthis_widget.js`

`addthis.com/addthis_widget.js` was removed, it no longer exists since `addthis.com` service has been terminated.

**Comment by gorhill** [comment]
Did you force an update of at list one filter list when you added your `ceo` scriptlet to your `my-scriptlets.js` file?

**Comment by JohnyP36** [comment]
> @JohnyP36 Did you force an update of at list one filter list when you added your `ceo` scriptlet to your `my-scriptlets.js` file?

Yes, I already had in uBlock for a long time. 
But now, the problem has disappeared. 
Somehow there was a delay in uBlock fetching my file.

**Comment by Bb016718063** [comment]
my-scriptlets.js
