### ISSUE TITLE
Blocked elements reappear

### ISSUE THREAD

**Issue by UnitedMarsupials** [uBlockOrigin/uBlock-issues#3076]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [ ] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

While browsing news on this site, I added a bunch of cosmetic filters hiding away the cruft I don't like seeing on any news-page (invitations to sign up for a newsletter, "related items", etcætera):
```
offthepress.com##.modal
offthepress.com##.main-header
offthepress.com##.date-bar
offthepress.com##.hidden-xs
offthepress.com##.spiny-ai-br-blocked
offthepress.com##.gform_wrapper
offthepress.com##.main-footer
offthepress.com##.endless-scroll
offthepress.com##.column-break-desktop
offthepress.com##.rel-art-wrap
offthepress.com##.rel-art-header
offthepress.com##.next
offthepress.com##.additional-content
offthepress.com##.btn-black
offthepress.com##p:empty
offthepress.com##p:has-text(/^\s*$/)
offthepress.com##.post-tag
offthepress.com##.slant-style:xpath(../..)
offthepress.com##.header-wrap:has-text(Newsletter)
offthepress.com##.share-widget
```
While I was doing this, the elements were disappearing -- as they are supposed to. I then opened another article on the [same site](https://offthepress.com), and saw the same cruft appear...

Wondering, if somehow my filters weren't saved, I opened the "Own Filters" tab in the settings, and, sure enough, here they are (the above list is a copy-paste from the tab).

If I add the same filter _again_, the element will disappear -- and the duplicate filter will appear under the "Own Filters". But reloading the page will show the already-blocked element(s) once more... I even tried disabling all JavaScript for the site -- to no avail.

Note, the actual ads are properly disabled -- the "3rd-party filters" must be doing their job(s). But the blacklisted elements keep appearing after a page-reload.

I've been a user of uBO for years -- my current version is 1.5.4.0, inside Firefox-121.0 -- and I haven't run into this until recently :(

Another troublesome site is Reddit -- I have _three_ identical entries already:
```
www.reddit.com###credential_picker_container
```
and yet, the silly widget keeps appearing, when I open the site.

### A specific URL where the issue occurs.

```yaml
https://www.offthepress.com/iowa-principal-who-put-self-in-harms-way-to-protect-students-from-mass-shooter-has-died/
```

### Steps to Reproduce

See description

### Expected behavior

Blacklisted elements remain hidden.

### Actual behavior

Blacklisted elements reappear.

### uBO version

1.5.4.0

### Browser name and version

Firefox-121.0

### Operating System and version

FreeBSD-14

**Comment by gwarser** [comment]
Do you have "My filters" lists enabled?

Please share troubleshooting information. Go to the site, click the uBO toolbar icon -> the "chat" icon -> "Troubleshooting Information" text on the bottom -> select all, copy and attach here.

**Comment by gwarser** [comment]
@gorhill there is an issue in dev build (1.54 seems fine) - even with "My filters" list disabled, filters are applied. They are cached somehow - editing the content of "My filters" purges them.

**Comment by gorhill** [comment]
> in dev build

This happens in 1.55.0 too. Toggling on then off "My filters" fix the issue. Pretty sure this is related to the MRU cache code I modified for cosmetic filter in last release.

As for @UnitedMarsupials, the most likely explanation is that their "My filters" is not enabled, will need to wait for troubleshooting information.

**Comment by UnitedMarsupials** [comment]
> Please share troubleshooting information. Go to the site, click the uBO toolbar icon -> the "chat" icon -> "Troubleshooting Information" text on the bottom -> select all, copy and attach here.

```
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 143884
 cosmetic: 218420
 scriptlet: 32326
 html: 2239
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-quick-fixes: null
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76422-7581, 1d.5h
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95055-80619, 9h.59m
  ublock-annoyances: 6505-11, 3h.59m
  fanboy-thirdparty_social: 68-0, 8d.11h.10m
  fanboy-cookiemonster: 49205-218, 5d.10h.2m
  fanboy-social: 16057-17, 5d.18h.2m
  adguard-social: 22343-738, 3d.23h.1m
 default:
  ublock-filters: 37035-75, 3h.59m
  ublock-badware: 7746-11, 3h.59m
  ublock-privacy: 957-0, 3h.59m
  ublock-unbreak: 2234-0, 3h.59m
  easylist: 77393-650, 3h.59m
  easyprivacy: 43439-832, 3h.59m
  plowe-0: 3784-1, 8d.15h.10m
  RUS-0: 40258-167, 3h.59m
  urlhaus-1: 9445-0, 4h.59m
filterset (user): [array of 1943 redacted]
trustedset:
 added: [array of 62 redacted]
switchRuleset:
 added: [array of 115 redacted]
hostRuleset:
 added: [array of 112 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1775 ms (selfie)
 maxAssetCacheWait: 290 ms
popupPanel:
 blocked: 56
 no-scripting: true
 network:
  offthepress.com: 38
  amazon-adsystem.com: 2
  decide.dev: 1
  doubleclick.net: 2
  facebook.com: 1
  fonts.googleapis.com: 1
  google.com: 2
  googlesyndication.com: 1
  googletagmanager.com: 2
  sharethis.com: 1
  spiny.ai: 5
 extended:
  ##.social-nav
  ##.social-widget
  ##.share-widget
  ##.sharethis-inline-share-buttons
  ###taboola-below-article-thumbnails
  ###stickyAd
  ##.sidebar-ad:not(.adsbygoogle)
  #@#.sidebar-ad
  ```

**Comment by gorhill** [comment]
@UnitedMarsupials 

>     user-filters: null

As suspected, your "My filters" is un-checked in "Filter lists" pane,  you just need to check it:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/d30069ff-ef5f-4a26-ae41-4a6f011d3ddf)

**Comment by UnitedMarsupials** [comment]
> As suspected, your "My filters" is un-checked in "Filter lists" pane, you just need to check it

Oh... No idea, how that came about. Thank you. But shouldn't have there been a _warning_ of some sort?

> [Prevent access to picker when "My filters" is not enabled](https://github.com/gorhill/uBlock/commit/bc641fc02445058617b7d3a7df1542681281bc9c)

Ah, great! Yes, this makes sense -- assuming, the blocking provides an explanation of some sort, unless you want to deal with tickets like "The picker-button is disabled for some reason" :-)

**Comment by BlazeFTL** [comment]
I Once Again Ask For A Way To Use Element Picker While My Filter Is Disabled
Would Be A Life Saver In A Situation When I Know The Style Rules In My Filters In Causing The Issue

My Suggestion Disable Only The Create Button In My Filter

**Comment by garry-ut99** [comment]
A current workaround/alternative is:

_On Desktop_: in My filters: press Ctrl+A & Tab (will select and comment out everything), then press Save. (repeat the procedure to uncommment all again)

_On Mobile_: instead of Ctrl+A, can tap and hold then select "Select all", but there is no Tab key on Android in most  default virtual keyboards, as Android doesn't support it by default, but you can install alternatie keyboards with Tab support: https://www.reddit.com/r/androidapps/comments/lxe8a5/looking_for_a_good_alternative_keyboard_with_a/

**Comment by garry-ut99** [comment]
> gwarser: https://github.com/uBlockOrigin/uBlock-issues/issues/3076#issuecomment-1893240639: there is an issue in dev build (1.54 seems fine) - even with "My filters" list disabled, filters are applied. 

> gorhill: https://github.com/uBlockOrigin/uBlock-issues/issues/3076#issuecomment-1893655396: This happens in 1.55.0 too. Toggling on then off "My filters" fix the issue. Pretty sure this is related to the MRU cache code I modified for cosmetic filters in last release.

Network filters created via logger are applied too, even with "My Filters" disabled.
