### ISSUE TITLE
New CDN URLs for the Swedish list

### ISSUE THREAD

**Issue by lassekongo83** [uBlockOrigin/uBlock-issues#3079]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I've implemented Diff-path to the Swedish list. So there are now some new CDNs that can be added to assets.json.

1. https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/swefilter/swefilter.min.txt
2. https://cdn.jsdelivr.net/gh/lassekongo83/Frellwits-filter-lists@swefilter/swefilter.min.txt

### A specific URL where the issue occurs.
In case someone can see if something's wrong with my implementation:
```yaml
https://github.com/lassekongo83/Frellwits-filter-lists/tree/swefilter
https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/.github/workflows/deploy.yml
```

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBO version

1.55.0

### Browser name and version

Firefox 121.0.1

### Operating System and version

Ubuntu 22.04

**Comment by gorhill** [comment]
I looked at the list and patches and `version` file, and all seem to be fine. If I understand correctly you set differential update up to update once a day.
