### ISSUE TITLE
EasyList and EasyPrivacy won't update

### ISSUE THREAD

**Issue by allanf181** [uBlockOrigin/uBlock-issues#308]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

EasyList and EasyPrivacy won't update.

### Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/14101716/48519039-a64fa580-e852-11e8-8bee-723d8a755237.png)

2. 
![image](https://user-images.githubusercontent.com/14101716/48519046-b23b6780-e852-11e8-8d8d-e4ac73a6a010.png)

### Expected behavior:

A update.

### Actual behavior:

![image](https://user-images.githubusercontent.com/14101716/48519138-ff1f3e00-e852-11e8-9ca2-4c34b7688b2d.png)

### Your environment

* uBlock Origin version: v1.17.2
* Browser Name and version: Firefox 63.0.1 (64-bits)
* Operating System and version: Windows 7 Ultimate (64-bits)

**Comment by gwarser** [comment]
>Private browsing mode? "Firefox will never remember history"? Disabled IndexedDB?

Also check uBO logger, moz-extension-scheme should be whitelisted, but who knows.

**Comment by allanf181** [comment]
Private browsing mode?  No.
"Firefox will never remember history"? No.
Disabled IndexedDB? No.

**Comment by allanf181** [comment]
logger shows the list url, but does not update.

**Comment by uBlock-user** [comment]
You haven't received any new update since 5th Sep, 2018 as per EasyPrivacy, did you modify any Firefox setting after installing it ?

**Comment by kulfoon** [comment]
I had the same problem in the past, it turned out that I reached browser storage limit (gorhill's suggestion):
`https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits`
So I just released some space on my disk and the problem disappeared.
So the question is how much does he have free space on his disk.

**Comment by allanf181** [comment]
I have 471gb free.

**Comment by uBlock-user** [comment]
Undo any changes you made in `about:config` regarding storage or extension storage. That's most likely the culprit. If that doesn't help, you will have to reset all your Firefox settings.

**Comment by allanf181** [comment]
I just changed the xpinstall.signatures.required

**Comment by allanf181** [comment]
forcing the update does not show errors in the console
![image](https://user-images.githubusercontent.com/14101716/48552056-805fea80-e8be-11e8-80bc-efa9b6c99fe8.png)

**Comment by allanf181** [comment]
but I found this
![image](https://user-images.githubusercontent.com/14101716/48552121-bd2be180-e8be-11e8-8997-e111522c2b97.png)

**Comment by allanf181** [comment]
https://firefox-storage-test.glitch.me/ says my IndexedDB is broken

**Comment by kulfoon** [comment]
> allanf181:
> 
> I tried to reproduce the issue when...
> 
>    [ ] uBlock Origin is the only extension
>    [x] uBlock Origin with default lists/settings
>    [ ] using a new, unmodified browser profile

**Comment by uBlock-user** [comment]
@allanf181 Did you, by any chance, downgrade back in the month of September ?

**Comment by allanf181** [comment]
must have been the update for firefox 62, I updated September 7

**Comment by allanf181** [comment]
I solved reinstalling firefox

**Comment by uBlock-user** [comment]
ofcourse, no other way to fix the broken IndexedDB.

**Comment by kulfoon** [comment]
> allanf181 : I solved reinstalling firefox

Should have been done before reporting an issue....
