### ISSUE TITLE
Unable to create pull request

### ISSUE THREAD

**Issue by 0x21D8** [uBlockOrigin/uBlock-issues#3080]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I tried to create a pull request to the main [repository](https://github.com/gorhill/uBlock/) but it failed because "An owner of this repository has limited the ability to open a pull request to users that have contributed to this repository in the past.". Can you fix this? Thanks in advance.

### A specific URL where the issue occurs.

```yaml
-
```

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBO version

-

### Browser name and version

-

### Operating System and version

-

**Comment by gorhill** [comment]
I don't accept PR. If you want to submit a PR, link to your local repo of uBO and explain why I should merge the changes.

I looked in your local uBO repo, and you want to merge "optimized" PNG images. I prefer to decline this sort of change.
