### ISSUE TITLE
Dead image files

### ISSUE THREAD

**Issue by 0x21D8** [uBlockOrigin/uBlock-issues#3082]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

@gorhill You have literally [dead](https://github.com/gorhill/uBlock/blob/master/src/img/ublock-defs.svg) [svg](https://github.com/gorhill/uBlock/blob/master/src/img/photon.svg) [files](https://github.com/gorhill/uBlock/blob/master/src/img/material-design.svg) that don't even render and may not even be used in the code, otherwise I can't even think why they still exist. I don't want to talk about your questionable decisions on this #3080, but it's kind of funny that you rejected rather harmless lossless compression with an updated version of the data order in the Zopfli algorithm, especially this decision makes no sense if we look right [here](https://github.com/gorhill/uBlock/pull/3458). I hope for your awareness and reason. Thank you.

### A specific URL where the issue occurs.

```yaml
-
```

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBO version

-

### Browser name and version

-

### Operating System and version

-

**Comment by gwarser** [comment]
These are svg symbols/templates. They are used as icons in UI. 

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/e34adb27-2cee-476f-9998-01a71c984911)

Checkmark on the bottom seems broken in InkScape, but it's correctly rendered in uBO Dashboard.

**Comment by gwarser** [comment]
About png's - https://github.com/gorhill/uBlock/pull/1637

Compressing them again will only increase repository size. They will be better without compression - extension package is zipped anyway.
