### ISSUE TITLE
`uritransform` not work if the url contains `#`

### ISSUE THREAD

**Issue by MkQtS** [uBlockOrigin/uBlock-issues#3084]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I want to transfer `https://jandan.net/top-ooxx#comment-5611920` into `https://jandan.net/t/5611920`

I have set 1p-filters as trusted, and added this rule:

```adblock
||jandan.net/top$uritransform=/top-\w+#comment-/t\//
```

but it does not work for `https://jandan.net/top-ooxx#comment-5611920`

I tried to change it to `||jandan.net/top$uritransform=/top-\w+-comment-/t\//` (`#` to `-`) and open `https://jandan.net/top-ooxx-comment-5611920` (an invalid url), then it works.

The problem seems to be related to `#`. It would be nice if `uritransform` matches URL hash.

### A specific URL where the issue occurs.

```yaml
https://jandan.net/top-ooxx#comment-5611920
```

### Steps to Reproduce

1. Add this rule: `||jandan.net/top$uritransform=/top-\w+#comment-/t\//`
2. Open `https://jandan.net/top-ooxx#comment-5611920`

### Expected behavior

The url turns into `https://jandan.net/t/5611920`

### Actual behavior

The url remains `https://jandan.net/top-ooxx#comment-5611920`

### uBO version

1.55.0

### Browser name and version

Chrome 120.0

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
`uritransform` currently ignores the hash part of a URL -- I didn't think there would be cases like the one you bring.

I suppose the behavior could be extended to mind the `#` part.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
Can you do the same for `removeparam`?

Example: `https://www.rambler.ru/`

<details>
<summary>Screenshot(s)</summary>

![rambler](https://github.com/uBlockOrigin/uBlock-issues/assets/20126984/546ad913-ad2d-4907-9fe4-03023d54a2ea)

</details>

**Comment by gorhill** [comment]
`removeparam` is too different, it is specifically optimized for query parameters, extending it would undermine efficiency. This was not an issue for `uritransform` because it doesn't really parse the parts to remove/replace, it's just a string operation. `removeparam` requires properly parsing and `hash` is never parsed and decomposed into search parameters.

I suppose a scriptlet could do the job for the hash component, since this information never travels to the server, it's just used client-side.

**Comment by dimisa-RUAdList** [comment]
Maybe create a reverse version `href-sanitizer`? Where the question mark will be responsible for searching and removing the end of the link.

Example: `www.rambler.ru##+js(href-sanitizer-rev, a[href^="https://"][href*="#rcmrclid"], ?#rcmrclid)`

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/3084#issuecomment-1899737983 - I don't think so, due privilege system?

RU AdList then need addition `RUS-0-` or own URL-s in advanced settings for list "RU AdList: Counter" per user:

https://github.com/gorhill/uBlock/wiki/Advanced-settings#trustedlistprefixes

If will be rejected addition to uBo uAssets Privacy list.

---

`$removehash` maybe should work form any file or my filters tab in stable version 1.56.0+

**Comment by stephenhawk8054** [comment]
@MkQtS They mean `uritransform` is a trusted filter, it won't work if adding it to `RuAdlist`

**Comment by dimisa-RUAdList** [comment]
That's right, I was looking for an opportunity to use those rules that would work from RU AdList, RU AdList: BitBlock, RU AdList: Counters.
