### ISSUE TITLE
Can't copy&paste text from logger's filter expressions field (Firefox)

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uBlock-issues#3097]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Can't copy&paste text from logger's filter expressions field in Firefox 
(cut&paste text from logger works fine, also copy&paste from notepad into logger works fine)
https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#filtering-the-logger-output
In Opera (Chromium) works fine.
In Firefox works fine in 1.55, broken in 1.55.1b14 and higher, 
which means introduced between [1.55 - 1.55.1b14].
I'm not sure whether it's a Firefox's issue or a uBO's issue.

### A specific URL where the issue occurs.

```yaml
moz-extension://64536790-5643-65b8-cd24-7g90b357642a/logger-ui.html#_
```

### Steps to Reproduce

1. Type some text into logger's filter expressions field
2. Select text or part of text 
3. Copy either via keyboard (Ctrl+C) or via mouse (right click ==> context menu ==> copy)
4. Paste anywhere, either into notepad or into logger's filter expressions field
 either via keyboard (Ctrl+V) or via mouse (right click ==> context menu ==> paste)
5. Notice that nothing (visually) is pasted
6. By looking into Clipboard viewer it seems that what actually has been copied into Clipboard is not the selected text but rather some strange visually invisible null/empty string

### Expected behavior

Selected text should be properly copied & pasted.

### Actual behavior

Selected text is copied altered/distorted/malformed/invisible into clipboard, 
hence what is pasted from clipboard is also altered/distorted/malformed/invisible.

### uBO version

1.55.1b22

### Browser name and version

Firefox 115.7.0 ESR

### Operating System and version

Win 7 SP1

**Comment by gwarser** [comment]
It's only "copy", "cut" works fine for me.

**Comment by garry-ut99** [comment]
I know, nothing new,  because I already informed about it in the description :
> garry-ut99 : (cut&paste text from logger works fine, also copy&paste from notepad into logger works fine)

Unless your point was to confirm this fact on your side.

**Comment by gwarser** [comment]
Ah, misunderstanding then. You said "from the logger" so I thought about general copy/paste from the UI not from this particular input field.

**Comment by gwarser** [comment]
Copying from static filter editor in details popup also does not work.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/a9eb9630cf88a9bfe4643a2e52d9fa2e37ba0b8b#diff-6009b040271a03f6407b77e90535f2cc94aa6518b144e51061d4ee38231b174aR3023

**Comment by garry-ut99** [comment]
> gwarser : Ah, misunderstanding then. You said "from the logger" so I thought about general copy/paste from the UI not from this particular input field.

I intentionally used the short form "from the logger" because I already used the full form "from logger's filter expressions field" in the previous line and in the title of the issue, hence since the context was already known, the next line was just supplementary to the previous line's context, and it seemed to me that there is no need to repeat the full long cumbersome form everytime, hence "from the logger" was just a shorcut of "from logger's filter expressions field" :

> Title : (the context) : Can't copy&paste text from logger's filter expressions field
> Description Line 1 (the context) :Can't copy&paste text from logger's filter expressions field in Firefox
> Description Line 2 (supplement) (cut&paste text from logger works fine, also copy&paste from notepad into logger works fine)

I wonder whose fault it is, and whether I should to always use full form every time to avoid being misunderstood in technical issues or maybe it's a fault of those users who misunderstand the context, this is something which everybody can discuss and think about.

<hr>

> gwarser : Copying from static filter editor in details popup also does not work.

This time indeed you have found somethign I missed, despite I was doing some copy&paste testing in the details popup, but it seems I didn't check all the tabs carefully enought, and I actually stopped after I tested the first tab "Details" thinking that the whole details popups and all the tabs are fine.

<hr>

_This comment has been written without bad intentions, the point was only technical/explanatory, and it has been only a reply to gwarser's comments, if this comment will be hidden (alone), like previous cases : https://github.com/uBlockOrigin/uBlock-issues/issues/3090 I won't contribute anymore to this repository, and will not fill any bug anymore, (unless gwarser's comment will be hidden along with my comments), this is because I don't want to contribute to repositories where I'm rudely disrespected by moderators who are overreacting or even are rude/disrespectful to long-time useful contributors._
