### ISSUE TITLE
MalwareDomainList offline/out of date

### ISSUE THREAD

**Issue by Daisenki** [uBlockOrigin/uBlock-issues#31]
### Description

MalwareDomainList.com hosts list most of the time offline and now out of date (last update 03 Apr 18)

http://www.malwaredomainlist.com/hostslist/hosts.txt

That happens with the server from MalwareDomainList?  The Website is not loading and the filter shows out of date and broken URL most of the time.

* uBlock Origin version:
uBlock Origin v1.16.4

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/3182#issuecomment-340718969

**Comment by uBlock-user** [comment]
Made a mirror - https://github.com/uBlock-user/MalwareDomainsList-Mirror
