### ISSUE TITLE
Add Chinese browser scheme to default whitelist

### ISSUE THREAD

**Issue by cherinyy** [uBlockOrigin/uBlock-issues#3101]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I noticed the following warning in [the documentation](https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites#important-read-carefully):

> Removing the predefined trusted site directives without understanding the consequences could cause your browser to malfunction.

So I found that three browsers that are common in the Chinese mainland don't exist in the list: 360 Security Browser, QQ Browser and Sogou Browser.

They are based on Chromium, but use their own scheme.

I tried to submit a PR, but the repository limits who can submit PRs.

### A specific URL where the issue occurs.

```yaml
https://github.com/cherinyy/uBlock/commit/4fa6b765fb3ae2176f8ab0be582de28382d346b9
```

### Steps to Reproduce

N/A

### Expected behavior

Browser Scheme in predefined trusted sites.

### Actual behavior

Browser Scheme is not in the predefined trusted sites.

### uBO version

1.55.0

### Browser name and version

360 Security Browser 15, QQ Browser 12 and Sogou Browser 12

### Operating System and version

Windows 11, version 23H2

**Comment by gorhill** [comment]
Do you see these schemes reported in the logger when filter lists update?

**Comment by cherinyy** [comment]
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/9050713/7d29d1b3-f990-4527-b107-c14aaa7b8b25)

Is this consistent? I can't use the interceptor because the interceptor page will be redirected to the browser homepage after refreshing.

It seems that Sogou Browser is based on QQ Browser, which is no surprise since Sogou was acquired by Tencent. They use `qqbrowser-scheme`.

360 Security Browser uses `chrome-scheme`, so don't worry about it.

**Comment by gorhill** [comment]
I am wonder the context in which lists are fetched, for example in Chromium:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/aa850b73-2d80-439f-87f2-bf5c1e3a346e)

With Firefox:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/790a7503-f98f-4498-8feb-2081c6a08a85)

Here is my thinking: instead to keep adding schemes which at this point appear inconsequential, maybe just stick to the ones which are consequential, i.e. the ones which are the context in which filter lists are fetched. This means the real change in the end would be to remove a bunch of schemes.

**Comment by uBlock-user** [comment]
> This means the real change in the end would be to remove a bunch of schemes.

Example - `wyciwyg-scheme`

**Comment by cherinyy** [comment]
Okay, I think I understand.

They all show up as `cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme` (Chrome Web Store version), so that means it doesn't matter?

**Comment by gorhill** [comment]
If they use `cjpalhdlnbpafiamejdnhcphjbkeiagm.chrome-extension-scheme` internally then there is no need to add more schemes, `chrome-extension-scheme` is already trusted.

**Comment by cherinyy** [comment]
ok, thank you for your answers.

**Comment by gwarser** [comment]
Opera, Vivaldi, Edge, all use `chrome-extension-scheme`.


(side note - the whole toolbar with page selector does not react to mouse click and does not react to hover correctly on Opera 106.0.4998.70/uBO 1.55.0)

**Comment by uBlock-user** [comment]
> Opera, Vivaldi, Edge,

Include Brave too

**Comment by u-RraaLL** [comment]
I see that the obsolete directives are now marked as my custom trusted sites. Sure, I can delete them and leaving them in won't really cause problems, but the troubleshooting info for all previous users will now contain 7 additional trusted sites. Is it not possible to actually remove them from trusted sites when updating?

**Comment by gorhill** [comment]
I looked at the code and it's not saving the removals, that is the issue. Too late to fix this though because in the meantime people might have added those.
