### ISSUE TITLE
Element Picker/Zapper - permit leaving these modes using their keyboard shortcuts

### ISSUE THREAD

**Issue by leothorp** [uBlockOrigin/uBlock-issues#3102]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [x] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

(My apologies if this is the wrong issue template to use- I didn't notice one for feature requests.)

Currently it looks like the only way to exit Element Picker/Zapper modes is to hit `Esc`- seemed like it might be useful (and a bit more intuitive) to also let the user exit them with the same keyboard shortcut they used to enter them.

I saw [this comment](https://github.com/uBlockOrigin/uBlock-issues/issues/2462#issuecomment-1399000922) from @garry-ut99 mentioning this functionality exists for some other features. If you feel that this would be a useful addition for these two features, I'm happy to implement this.

Thanks!

### A specific URL where the issue occurs.

```yaml
https://github.com would be one example (occurs everywhere).
```

### Steps to Reproduce

1. Configure a keyboard shortcut for either Element Picker or Element Zapper.
2. Hit your shortcut to activate the mode. 
3. Attempt to hit it again to deactivate; nothing happens.

### Expected behavior

I expected that hitting the same keyboard shortcut would toggle either feature "off" if currently in the "on" state.

### Actual behavior

Nothing happens when hitting the same shortcut while in "on" state.

### uBO version

1.55.0

### Browser name and version

Chrome 120.0.6099.234

### Operating System and version

MacOS Ventura 13.4.1

**Comment by u-RraaLL** [comment]
https://github.com/gorhill/uBlock/wiki/Keyboard-shortcuts

**Comment by leothorp** [comment]
@u-RraaLL would it make sense for me to go ahead and start implementing this?

**Comment by leothorp** [comment]
@u-RraaLL would it make sense for me to go ahead with implementing this?

**Comment by u-RraaLL** [comment]
Hm, you asked this before but the comment was gone when I opened the issue.

Gorhill hasn't replied, so if you want to make a PR/patch before that, that's okay, but it might not get accepted. The end decision remains his.

In case you're not a previous contributor to the main repo, you'll need to make a patch and link it here, because PRs are locked to only previous contributors.

**Comment by leothorp** [comment]
Good to know, thank you for the info. (and sorry about the confusion with the earlier comment, deleted it due to lack of bandwidth at the time).

I'll take an initial look- depending on how involved it seems, I may hold off on finishing the patch until Gorhill weighs in on the idea. Thanks again.

**Comment by leothorp** [comment]
👍 Thanks for the info on how it could be done. Makes sense that it might not be worth the extra code. Will likely still take a crack out of curiosity if nothing else, but understandable if it ends up not getting merged.

**Comment by gorhill** [comment]
I prefer to decline, I know I won't spend time on this, no point to keep the issue opened.
