### ISSUE TITLE
Ublock Origin cannot block popup windows on mobile browser(s)

### ISSUE THREAD

**Issue by lychichem** [uBlockOrigin/uBlock-issues#3103]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Ublock Origin on mobile devices seems not using `^popup` filter or `no-popup` filters. Tested with Firefox for Android and Edge canary on Android (with edge extension flag enabled)

### A specific URL where the issue occurs.

```yaml
https://supjav.com/zh/254443.html (NSFW)
```
There are many other links, but such NSFW sites are the best to reproduce this issue as they use many popup windows.

### Steps to Reproduce

1. Write `no-popups: supjav.com true` into `dyna-rules` of ublock origin or use filters here: https://github.com/lychichem/list/releases/latest/download/ad-pc.txt ,
2. Visit link above and select server `FST`,
3. Click play button.

### Expected behavior

No popup window should be shown

### Actual behavior

The popup window will show twice

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium Mobile: 123
filterset (summary):
 network: 104039
 cosmetic: 27106
 scriptlet: 30
 html: 0
listset (total-discarded, last-updated):
 removed:
  CHN-0: null
  adguard-mobile: null
  easylist: null
  easyprivacy: null
  plowe-0: null
  ublock-badware: null
  ublock-filters: null
  ublock-privacy: null
  ublock-quick-fixes: null
  ublock-unbreak: null
  urlhaus-1: null
 added:
  https://github.com/lychichem/list/releases/latest/download/ad-pc.txt: 148446-17281, 16m
 default:
  user-filters: 10-0, never
filterset (user): [array of 6 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1273 ms (selfie)
 maxAssetCacheWait: 265 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by gwarser** [comment]
![Screenshot_2024-02-03-09-03-49-469_org mozilla fenix](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/3be41e2c-2639-46b3-be91-740ad4c27882)

**Comment by lychichem** [comment]
> No lists:
> 
> Details
> ![Screenshot_2024-02-03-09-03-49-469_org mozilla fenix](https://private-user-images.githubusercontent.com/886325/302022522-3be41e2c-2639-46b3-be91-740ad4c27882.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjExMTcsIm5iZiI6MTcwNjk2MDgxNywicGF0aCI6Ii84ODYzMjUvMzAyMDIyNTIyLTNiZTQxZTJjLTI2MzktNDZiMy1iZTkxLTc0MGFkNGMyNzg4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDUwZTFjNmRkNDhmYTE1ZWU3ODIyZjZiMjE4NWQwMjBmOWUwOWYwNzYxOTc0YTFkY2U1YTA2YThmY2I3YWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EW5-SI_QPMmCuuCemgdwAMTtBSPOLgisRpuW7c0xqLw)
> 
> With your list:
> 
> Details
> ![Screenshot_2024-02-03-09-07-13-988_org mozilla fenix](https://private-user-images.githubusercontent.com/886325/302022694-2909cc7f-b8e0-4341-9a73-f8e886440c6e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjExMTcsIm5iZiI6MTcwNjk2MDgxNywicGF0aCI6Ii84ODYzMjUvMzAyMDIyNjk0LTI5MDljYzdmLWI4ZTAtNDM0MS05YTczLWY4ZTg4NjQ0MGM2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjVhMGYwOGE4OWUxZjBmNWE1NThkY2Q0OTY1MTg1MjkxZmQyNDE0M2U4ZDJiN2RmZGYwZjFlMDhiZDNlOGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l8FSe6mGlgfF69-FNFU1YjxcDqmiMoBgIfTPxOknbtY)
> 
> List only:
> 
> Details
> ![Screenshot_2024-02-03-10-53-07-475_org mozilla fenix](https://private-user-images.githubusercontent.com/886325/302027708-90007af7-f2d9-4f9d-b9ee-fd835ce7efa5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjExMTcsIm5iZiI6MTcwNjk2MDgxNywicGF0aCI6Ii84ODYzMjUvMzAyMDI3NzA4LTkwMDA3YWY3LWYyZDktNGY5ZC1iOWVlLWZkODM1Y2U3ZWZhNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yM2ZhYzRmZGJjODVhYjQ2ZWVmYTI1ODg1YmM0ZjQ5ZTFiOGJjNzM5MmY4NTkwNGUwMDIzZTU4YjY2N2RkZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S8pjt1pkCNyVmoOcwU1X5pkfUGCW8gfbElca9z1eJOo)

How did you open the logger? I can not open it on my android Phone (Oneplus 9)

**Comment by gwarser** [comment]
uBO Dashboard -> Support tab -> Tip in "Filter issues/website is broken"
