### ISSUE TITLE
self.requestIdleCallback

### ISSUE THREAD

**Issue by espretto** [uBlockOrigin/uBlock-issues#3105]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The global function `requestIdleCallback` is [not well supported in safari](https://caniuse.com/?search=requestidlecallback). The following error is thrown:
```
TypeError: self.requestIdleCallback is not a function. (In 'self.requestIdleCallback(c,{timeout:67})', 'self.requestIdleCallback' is undefined)
```

### A specific URL where the issue occurs.

```yaml
https://flug.idealo.de/flugroute/Muenchen-MUC/Mumbai-BOM/
```

### Steps to Reproduce

1. Setup fresh Safari <= v17.4 w/ uBlock Origin
2. Goto aforementioned site
3. The error should be visible in the console

### Expected behavior

There should be no error in the console.

### Actual behavior

There is an error in the console.

### uBO version

1.55.0

### Browser name and version

Safari 17.2.1

### Operating System and version

Mac OS X 10.15.7

**Comment by krystian3w** [comment]
Supported well in official supported Chromium and Firefox.

You should provide how you ran uBo 1.55 in Safari 17.2 if it is not a fork of the Orion Browser type (https://kagi.com/orion/) - then it is an error that the browser allows installation from the Google and Mozilla store.

**Comment by krystian3w** [comment]
#3237
