### ISSUE TITLE
Feature: Update filter lists from local files

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#3106]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In Firefox (hence also Tor Browser) [it is not possible](https://github.com/uBlockOrigin/uBlock-issues/discussions/1754#discussioncomment-1449018) to update filter lists from `file://` URI scheme:

https://discourse.mozilla.org/t/how-to-access-local-files-from-an-extension/92190/7

https://bugzilla.mozilla.org/show_bug.cgi?id=1266960#c10

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Extension/isAllowedFileSchemeAccess#return_value

> Firefox will always return `false`.

This makes it impossible for one use filter lists in local files. Even if one runs a local HTTP server (so that `http://` scheme is used), that is still problematic in the case of Tor Browser which explicitly disables local connections for security reasons, as explained [here](https://www.whonix.org/wiki/Tor_Browser/Advanced_Users#Local_Connections_Exception_Threat_Analysis) (see the references, especially the link to 18-year old bug in Firefox). This makes using a local HTTP server problematic too.

The final result is that it is impossible to optimize filter list retrieval, which can be particularly useful in the case of multiple and volatile browser profiles, in which uBO is installed and configured through policy.json.

### The feature request

If possible, please kindly provide a way to use locally stored filter list files.

If it is possible to use a simple shell script which simply parses the list files and updates the IDB the same way in which the extension does it, that would also work.

#### Potential benefits for the user

- Optimized traffic usage: not necessary to download the same data for each browser profile, which is particularly useful when using volatile profiles

- Reduce fingerprinting by using local files: no background connections to various hosts

- Possibility to use uBO efficiently behind firewall.

Example: A restricted VM which connects only to hostA.com and hostB.com cannot possibly update its filter lists directly. However, it would be able, if it has a filter list downloaded in another VM and cached locally, which would allow proper request blocking for hostA.com and hostB.com.

- Speed: Download once, update once, done. Locally cached filter lists can be updated periodically by a custom shell script (I already created one and I can share it if considered interesting, as part of the solution).

### A specific URL where the issue occurs.

```yaml
irrelevant
```

### Steps to Reproduce

1. Install uBO in Tor Browser
2. Configure it to use only one single custom list: `file:///tmp/download/list`
3. Download a filter list and store it locally in `/tmp/download/list`
4. In Filter Lists menu, click Update Lists

### Expected behavior

Successful update.

### Actual behavior

uBO's log shows:

​Reloading all filter lists: done​​​​​​
​Network error: file:///tmp/download/lists?_=1​​​​​​
​Reloading all filter lists: start​​​​​​
​Network error: file:///tmp/download/lists

### uBO version

1.55.0

### Browser name and version

Tor Browser 13.0.9

### Operating System and version

Whonix-Qubes 17

**Comment by krystian3w** [comment]
Firefox added official API?

 If nope then may needed by local server with TLS (to force secure `https://localhost/filters-list.txt`).

**Comment by gwarser** [comment]
uBO has no knowledge about disk storage at all. AFAIK browser databases used to store add-ons/web pages settings are in custom format. They can be locked when browser is running, so you will need to make sure browser is turned off when hacking these files.

Maybe just create your custom uBO build with all filter lists you need stored in add-on package?

**Comment by krystian3w** [comment]
> Unnecessary.

Required as the script will be written for years and Mozilla will implement the switch in `about:addons` in similar slow time.

**Comment by gwarser** [comment]
>If possible, please kindly provide a way to use locally stored filter list files.

Didn't you just prove this is impossible, because browser is blocking it?

>If it is possible to use a simple shell script which simply parses the list files and updates the IDB __the same way in which the extension does it__, that would also work.

[emphasis mine]
Extension is doing this by WebExtensions API. There is no API outside the browser. Extension does not have access to file system (does not see these files). This is not possible. Storage file format is custom (by browser). Best you can do is to reverse-engineer some external tool to _hack_ these files. This is outside the goals of this project.

**Comment by iam-py-test** [comment]
That pretty much already exists; you can import/export the _my filters_ tab. The Filesystem API would not enable anything beyond that. It **only** enables extensions/websites to request the user select a file to be "uploaded"; that access is only temporary. Additionally, neither Chromium nor Firefox fully supports that API.
My one cent
