### ISSUE TITLE
Element Picker not available on New Tab page

### ISSUE THREAD

**Issue by T-700** [uBlockOrigin/uBlock-issues#3108]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

On the page opens for my New Tab, there are elements I would like to block, as I do successfully on other pages, however, the element picker does not show up as an option on this page, regardless of the cosmetic filtering setting.

### A specific URL where the issue occurs.

```yaml
FVD Speed Dial
```

### Steps to Reproduce

1. Use FVD Speed Dial for New Tab
2. Try to hide elements

### Expected behavior

The element picker to show up so that I can pick or at least zap the element.

### Actual behavior

The bar in uBO is missing 3 of the 5 buttons.

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 115450
 cosmetic: 45502
 scriptlet: 20414
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80303-14, 3d.54m
  easyprivacy: 43336-48, 3d.54m
  plowe-0: 3786-1177, 10d.21h.4m
  ublock-badware: 7849-140, 24m Δ
  ublock-filters: 37150-210, 29m Δ
  ublock-privacy: 998-6, 3d.54m
  ublock-quick-fixes: 197-4, 29m
  ublock-unbreak: 2206-32, 29m Δ
  urlhaus-1: 7320-0, 29m
filterset (user): [empty]
trustedset:
 removed:
  edge-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 888 ms
 maxAssetCacheWait: 425 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by gwarser** [comment]
>FVD Speed Dial

Extensions do not work on other extensions pages. Also https://github.com/gorhill/uBlock/wiki/Privileged-Pages

**Comment by garry-ut99** [comment]
Duplicate of : https://github.com/uBlockOrigin/uBlock-issues/issues/512

<hr>

> T-700 : 2. Try to hide elements

From Wiki :
> https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-picker#element-picker-does-not-work-removed-element-reappears-when-you-reload-the-page
> 
> - The site you are trying to use the element picker or element zapper on is unsupported:
>    - Unsupported pages: [Privileged Pages](https://github.com/gorhill/uBlock/wiki/Privileged-Pages). Also, see this [related issue](https://github.com/uBlockOrigin/uBlock-issues/issues/512).

<hr>

> T-700 : On the page opens for my New Tab, there are elements I would like to block

In the addon's options, much appearance & theme fine-tuning is possible, maybe you missed something, and if not then you need to report to the creator.
