### ISSUE TITLE
Changing the button for the NOR list

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#311]
Hello again.

As I've decided to expand my Norwegian list into one that covers multiple Nordic countries, I request that the `NOR: Dandelion Sprouts norske filtre` listing in the uBO extension setting shall be changed to `NOR, DNK, ISL: Dandelion Sprouts nordiske filtre`.

The source link to the list [remains the same](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt) as before, as far as I can tell.

**Comment by okiehsch** [comment]
@gorhill 
If you decide to add this list  to the default setup for users with a danish locale you should consider removing the existing danish list, which has been last updated 5 months ago.

**Comment by DandelionSprout** [comment]
I originally planned to give Schack the benefit of the doubt until ca. the 13th of December, but I'd be massively impressed if he were to resume active work on his list before then.

• Roughly a quarter of the domains on his list, were owned by big media corps who've since decommisioned them and turned them into redirects. Example: `spn.dk` now redirects to `jyllands-posten.dk/sport`.
• He had previously worked on his list [for some 10 years](https://henrik.schack.dk/2008/01/13/adblock-opdateringer/), but now seems to me to have placed most (if not all) of his focus on https://dmarc.dk/, where he tries to promote E-mail anti-spoofing standards to Danish corps, with varying luck.
• His list was made to `[Adblock Plus 1.1]` standards, and didn't make use of multi-domain entries or `:-abp-has`/`:has`.

**Comment by gorhill** [comment]
I am going to leave the danish list in there for now. I usually consider that a list is roughly obsolete after many month of inactivity -- removal can still wait a bit longer than the current 6 months.
