### ISSUE TITLE
Feature: wildcard for Public Suffixes in network filters

### ISSUE THREAD

**Issue by cinver3** [uBlockOrigin/uBlock-issues#3110]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I suggest adding a wildcard to network filters that covers Public Suffixes, so filters can be applied to entire 'entities' [like with cosmetic filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity).

The idea has been brought up before elsewhere: https://forum.adblockplus.org/viewtopic.php?t=48304

### A specific URL where the issue occurs.

```yaml
NA
```

### Steps to Reproduce

NA

### Expected behavior

AN

### Actual behavior

NA

### uBO version

NA

### Browser name and version

NA

### Operating System and version

NA

**Comment by gwarser** [comment]
Already implemented in domain/from/to options.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#to  
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#domain

**Comment by krystian3w** [comment]
Also domain/from support regex:
```adb
malware$domain=/agency[\d]\.[a-z]{2,18}(\.[a-z]{2,18})?/
```

**Comment by cinver3** [comment]
> Already implemented in domain/from/to options.
> 
> https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#to https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#domain
> 
> I will close, but you can comment if you have questions.

Am I correct in thinking this would pertain to the domain on which the filter is active, not the domains which are blocked etc by the filter, i.e. this:
```
*$script,domain=google.*
```
blocks all scripts originating from all domains when you are on a page belonging to google.com, google.co.uk, google.ca, etc, but how would you block all scripts originating from those google domains when you are on any page of any domain, i.e. something like:
```
google.*$script
```
but for the google entity specifically without dragging in other tlds (`google.evil.biz` etc in the example).

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#to
