### ISSUE TITLE
ublock detected and website blocked by pop up

### ISSUE THREAD

**Issue by elhuiro** [uBlockOrigin/uBlock-issues#3117]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

biobio its a newspapper website. when you start scrolling appears a pop up message that says "if you want that the page remains a free website, please don't block the advises" the pop up block the navegation on the website. I'm already check the filters and remove any other blocker. If you use the "enter element zapper mode" you can select 3 things of the pop up message 
1.- a shadow that use all the screen and that actually block the scrolling
2.- a big box pop up with the message of the website related to adblockers
3.- a small banner with the logo of the newspapper

Selecting those 3 things with zapper mode remove the problem and you can scroll like always, but if you click on any news the pop up banner and the shadow pop again. if you go back to the main page, the pop up appears again.

### A specific URL where the issue occurs.

```yaml
https://www.biobiochile.cl/
```

### Steps to Reproduce

1. Scroll on the website or just wait for 5 to 10 seconds
<img width="960" alt="Screenshot 2024-02-13 08 22 09" src="https://github.com/uBlockOrigin/uBlock-issues/assets/159853043/2ee99aee-5470-4ec4-abd4-5fb53ff27c85">

### Expected behavior

avoid the recognition of the website and/or the blocking of the website

### Actual behavior

ublock get recognized and the website block scrolling ussing a pop up

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 129893
 cosmetic: 112939
 scriptlet: 24371
 html: 2099
listset (total-discarded, last-updated):
 added:
  adguard-social: 22141-2040, never
  adguard-cookies: 28623-1628, never
  ublock-cookies-adguard: 935-0, never
  adguard-popup-overlays: 26939-278, never
  adguard-mobile-app-banners: 5019-17, never
  adguard-other-annoyances: 14182-302, never
  adguard-widgets: 2433-42, never
 default:
  user-filters: 0-0, never
  ublock-filters: 37898-405, 12h.16m
  ublock-badware: 7849-14, 12h.16m
  ublock-privacy: 995-1, 12h.16m
  ublock-unbreak: 2261-1, 12h.16m
  ublock-quick-fixes: 219-0, 1h.42m
  easylist: 80811-16570, 12h.16m
  easyprivacy: 50199-834, 12h.16m
  urlhaus-1: 7300-0, 12h.16m
  plowe-0: 3782-1, 12h.16m
filterset (user): [empty]
trustedset:
 added: [array of 3 redacted]
switchRuleset:
 added: [array of 2 redacted]
userSettings:
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 16273 ms (selfie)
 maxAssetCacheWait: 223 ms
 cacheBackend: indexedDB
```
</details>

**Comment by krystian3w** [comment]
> - [X] verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

This is bugtracker for bug in addon not in filters.

Anti Adblock should be reported from addon interface:

https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/22465

**Comment by elhuiro** [comment]
AdGuard Spanish/Portuguese list

problem solved thanks
