### ISSUE TITLE
建议临时移除元素模式支持连续操作

### ISSUE THREAD

**Issue by StrollStars** [uBlockOrigin/uBlock-issues#3118]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

希望临时移除元素模式能够支持连续操作，能够连续点击消除元素，同时支持撤销和提供退出按钮以退出临时移除元素模式。

### A specific URL where the issue occurs.

```yaml
与URL无关，和扩展功能有关。
```

### Steps to Reproduce

功能性建议。

### Expected behavior

希望进入临时移除元素模式，可以连续点击消除元素，直到退出这个模式，同时支持撤销。

### Actual behavior

每次消除都需要点击临时移除元素模式按钮。

### uBO version

1.55.0

### Browser name and version

Chrome 109

### Operating System and version

Window 7 64bit

**Comment by krystian3w** [comment]
Hold shift or use in your loop delete button.

**Comment by StrollStars** [comment]
@krystian3w 再请问下，是不是点错了只能重来，不能撤销？

**Comment by krystian3w** [comment]
Yes, Zapper ⚡  does not allow you to undelete an item without clicking F5.
