### ISSUE TITLE
Strict blocking does not work on Youtube (History.pushState)

### ISSUE THREAD

**Issue by gqqnbig** [uBlockOrigin/uBlock-issues#3119]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I add this rule to ublock origin

`||youtube.com/@MrBeast/shorts^$all`

If I click this link https://www.youtube.com/@MrBeast/shorts, ublock successfully block the web page, which is good.

However, if I click on https://www.youtube.com/@MrBeast/videos, then click the shorts tab, while the URL switches to /shorts, ublock fails to block the page.

The same appies to many pages on Youtube. If you click a direct link outside of Youtube, ublock can block it. If you click a link on Youtube, I guess Youtube uses History.pushState() that dynamically reloads the page and changes URL, and bypasses ublock.

Please fix this.

### uBO version

1.55

### Browser name and version

Chrome 121

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
Strict-blocking works only on navigation events. Youtube is a long-lived, dynamically modified webpage with no real navigation events, the website manually changes the URL in the address bar.

This is by design.

**Comment by gorhill** [comment]
Well for sites which update dynamically the DOM is already fully loaded when the fake navigation occurs. You could "block" using cosmetic filtering:

    youtube.com##body:matches-path(/@MrBeast/shorts)
