### ISSUE TITLE
Change "IDN: ABPindo" to "IDN, MYS: ABPindo"

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#312]
Kind-of related to #311 except not really.

As a result of https://github.com/ABPindo/indonesianadblockrules/pull/60, ABPindo is now mostly-officially covering Malaysian-language websites as well as Indonesian ones. Thus I think that the list is worthy of becoming a default list for Malaysian-locale users as well.

Currently the Malaysian coverage is mostly limited to major newssites, which admittedly weren't heavily plagued with all that many non-EasyList-covered ads. But there doesn't seem to be any obstacles against submitting entries from other Malaysian websites to that list now.

Citing verbatim from https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-441449908:

>Outside of the Europe map, I've also attempted to broaden (Either officially or de facto) ABPindo's range to also cover Malay-language sites. The general case seems to be that the Indonesian and Malay languages are highly similar (having been based on the same 1800's formal language, or so Wikipedia says), and that the list already had 20~25 entries that was directly about .my sites.
>
>The thing is, there actually wasn't a tonne of ads all over the place on newssites from Malaysia, Singapore, or Brunei, in contrast to how it is like on European newssites, thus I could only find 8 new entries among their major Malay-language newssites. Therefore I understand it if some eyebrows are raised among you guys by the notion of having a regional list be counted as covering a language for which it has ≤40 entries, but if that pull was accepted, I would propose that IDN: ABPindo be changed to IDN, MYS: ABPindo and be turned on by default for Malay-language users.

**Comment by heradhis** [comment]
ABPindo author here
Malay language and Indonesian are very similar. ABPindo has supported Malay language sites that can be seen from it's filter. 

> The thing is, there actually wasn't a tonne of ads all over the place on newssites from Malaysia, Singapore, or Brunei, in contrast to how it is like on European newssites

Yes because Malaysia, Singapore and Brunei Official language is [Malay language](https://en.wikipedia.org/wiki/Malay_language).
