### ISSUE TITLE
Mp3 website problem

### ISSUE THREAD

**Issue by TMan-21** [uBlockOrigin/uBlock-issues#3120]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Freezes a particular website

### A specific URL where the issue occurs.

```yaml
https://free-mp3-download.net/
```

### Steps to Reproduce

1. Install ublock origin from edge addons
![Screenshot 2024-02-13 203551](https://github.com/uBlockOrigin/uBlock-issues/assets/140910112/12b57df3-2c09-40d1-947e-3d9d2fe6d0e4)
![Screenshot 2024-02-13 195619](https://github.com/uBlockOrigin/uBlock-issues/assets/140910112/763c3886-e6d2-4b4e-a42f-8c0d4ef99305)

2. Enter the website from url provided (https://free-mp3-download.net/)
3. The website does not work. Search button, home button. The only thing that works is the text box but what's the point if I can't proceed from there

### Expected behavior

I expected the site to work properly but 1 of 2 things happen: 1. The website simply does not work when the adblock is not on. 2. The website asks me to turn off the ad block when ublock is deleted/ The website asks me to turn off my adblock when the website is on the filter list 

### Actual behavior

1. The website simply does not work when the adblock is not on. 2. The website asks me to turn off the ad block even when ublock is deleted or removed/ The website asks me to turn off my AdBlock even when the website is on the filter list 

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 121
filterset (summary):
 network: 122135
 cosmetic: 45515
 scriptlet: 20506
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 80824-14, now
  easyprivacy: 50199-39, now
  plowe-0: 3782-1184, now
  ublock-badware: 7845-141, now
  ublock-filters: 37405-349, now
  ublock-privacy: 999-6, now
  ublock-quick-fixes: 134-26, now
  ublock-unbreak: 2213-32, now
  urlhaus-1: 6695-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3283 ms
 maxAssetCacheWait: 24 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by TMan-21** [comment]
Plz help

**Comment by mapx-** [comment]
continue here: https://github.com/uBlockOrigin/uAssets/issues/22067
