### ISSUE TITLE
Make check for on... attributes case-insensitive

### ISSUE THREAD

**Issue by bcaller** [uBlockOrigin/uBlock-issues#3121]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Attribute names are case-insensitive, so a filter list could include `oNcLiCk`.

However, `'oNcLiCk' in elem` is false whereas `'onclick' in elem` is true.

Related commit:
https://github.com/gorhill/uBlock/commit/068b625bef25b330bd9e611648ece3362dba8ab2

My PR attempt: https://github.com/gorhill/uBlock/compare/master...bcaller:uBlock:master

### A specific URL where the issue occurs.

```yaml
N/A
```

### Steps to Reproduce

N/A

### Expected behavior

`example.com##+js(set-attr, a, oNcLiCk, [href])` should be treated the same way as `example.com##+js(set-attr, a, onclick, [href])`

### Actual behavior

`oNcLiCk` is allowed.

### uBO version

@

### Browser name and version

N/A

### Operating System and version

N/A

**Comment by krystian3w** [comment]
Seems in wrong place or too late? Filter run at my side.

Also nice will be mark this hack with size of letters as duplicate in my filters (something like remove white characters in diff).
