### ISSUE TITLE
Improve the user experience for manual filter list updates

### ISSUE THREAD

**Issue by Sworddragon** [uBlockOrigin/uBlock-issues#3124]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

For over 2 decades now I'm updating all system components manually in a regular interval and this worked out very well and avoids some downsides and other specific issues. Due to this policy when I switched to uBlock Origin a few weeks ago I also disabled automatic filter list updates and update them once in a week.

But this doesn't appear to be a good experience. On the first day I thought the button in the dashboard to update the filter lists does update all filter lists at once as this seemed self-explanatory. But this wasn't the case and I figured out later that it just updates all outdated filter lists and it is also documented this way. But even after a week not all filter lists were outdated so unfortunately this button wasn't too helpful here.

So what I do now is simply clicking all clocks which isn't that great and which has also exposed some issues:

- When a clock for a filter list is clicked it might update filter lists of another group which makes updating a bit unpredictable. For example clicking the clock symbol for Easy List also just caused the uBlock filters and some others to be updated - but not all. I did check https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists in general to learn more about the update behavior but the documentation reads as it didn't kept manual updates in mind as for such an user the documention reads incomplete on some parts.
- [*1] I can update entire groups or single lists by clicking the clock symbol. But if a list becomes outdated I can update the list but not the group anymore (clicking the yellow warning triangle on the group does nothing). I suspect this might be just a bug.

So now I have to click through every clock of each filter list to get it updated. And due to testing I noticed 2 issues here:

- [*2] The loading animation is very short as sometimes a click does visually nothing. So it is hard to tell if a filter list got updated e.g. if it wasn't too old. If the loading animation would guarantee a minimum time visually (e.g. 200ms-300ms) it would provide better feeback (and avoid the user thinking their mouse might be defect or such).
- [*3] Updating via a group a few times in a row causes some lists in the group to become outdated. I suspect this might be just a bug as well.

### A specific URL where the issue occurs.

```yaml
moz-extension://*/dashboard.html#3p-filters.html
```

### Steps to Reproduce

- Disable automatic filter list updates.
- Try to update all filter lists manually.

### Expected behavior

What can be improved depends what is specifically wanted as this issue could be divided in tasks of which any or none could be done:

- While being in the dashboard holding CTRL or SHIFT could force to hightlight the update button - clicking it that way would update all filter lists in the same way is if the user would click the clock symbol for each filter list. This would be a main improvement to this issue.
- Fixing [*1] will be already a significant improvement as well and while being less relevant fixing [*3] would not hurt as well if it should turn out to be really a bug.
- Better feedback via [*2] would be nice as well but it would be only a minor improvement.

### Actual behavior

Updating filter lists manually feels actually like a workaround where things are sometimes glitching out here and there.

### uBO version

1.55.0

### Browser name and version

Firefox 122.0.1

### Operating System and version

Windows 10 22H2 64 bit

**Comment by gorhill** [comment]
> But even after a week not all filter lists were outdated so unfortunately this button wasn't too helpful here.

Not all lists need to be updated after a week, some have longer update period. There is no need to bypass this period, it's set up on a per-list basis according to how often each list is updated by their respective authors.

> So what I do now is simply clicking all clocks which isn't that great

This is self imposed, there is no need to do this.

You have very specific self-imposed requirements which are irrelevant for that vast majority of people, I decline designing uBO for very specific personal requests. In such case, best is to fork and adapt uBO to your very specific personal requirements.

**Comment by Sworddragon** [comment]
I mean, if I update all system components after a week (or even after any arbitrary amount of time) I also update the filter lists independet of any expiration as this is just natural in such a case. I have to disagree that this is a self-imposed issue unless the claim extends that disabling automatic filter lists update is such an issue and I would be even kind of fine with that.

Nonetheless, what about the specific bugs I discovered? @gorhill
If you click the uBlock filters clock symbol to cause a few updates in a row it causes some lists to be outdated which seems not correct. And the clock symbol isn't even clickable anymore when any list in the group becomes outdated. Are those something that need to be addressed?

**Comment by gorhill** [comment]
> what about the specific bugs I discovered

> So it is hard to tell if a filter list got updated e.g. if it wasn't too old.

If a filter list is fetched quickly, the animation will be quick. Just hover over the clock icon to see when the list updated last. If an update was just triggered, it will say "a minute ago".

> Updating via a group a few times in a row causes some lists in the group to become outdated

I don't see repro steps for this one. What is a "group"? What exactly "a few times on a row" mean in practice?

**Comment by Sworddragon** [comment]
The STR would be:

1. Go to the filter list dashboard.
2. Navigate to the uBlock filters clock symbol.
3. Click it to cause all filter lists in the group to be updated.
4. Once done repeat step 3 a few times (on all my attempts around much less than 10 tries were sufficient to trigger the issue, maybe try it a bit more to be safe as it might be just a race).

Now filter lists randomly in the uBlock filters group become outdated while they should be up-to-date.


And the STR for the other issue:

1. Go to the filter list dashboard.
2. Navigate to the uBlock filters clock symbol.
3. Click it once it appears as a yellow warning triangle (you can actually utilize the bug above to force this).

Nothing happens while one would expect that all filter lists in the uBlock filters group will be updated.
