### ISSUE TITLE
`$uritransform` sometimes not working.

### ISSUE THREAD

**Issue by Iz-zzzzz** [uBlockOrigin/uBlock-issues#3125]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

From this https://github.com/uBlockOrigin/uBlock-issues/issues/3084
Its seem like I can replace or remove any parts of url with `$uritransform`, so I create this rule
```
||pantip.com^$doc,uritransform=/#lead:.*//
```
to remove tracking part of 
```
https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369
```
(example url) but it works when there is only this uritransform rule enable. When I enable another uritransform rule:
```
*$uritransform=/\?fbclid=//
```
Both uritransform rules stop working, and uBO doesn't mark any rules as invalid too. If the second rule is invalid, the first rule should still working. 

### A specific URL where the issue occurs.

```yaml
`https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369`
```

### Steps to Reproduce

1. Create test.txt file in Desktop
2. Allow uBO to access to file URLs
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/dd44d855-649c-4b18-b3ff-1238110a1789)
3. Import test.txt to uBO custom filters and add `file:///` in `trustedListPrefixes` to make sure this filter have enough permission. 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/8e5a9ec5-3238-4dc7-bf40-21fabbb57512)
3. Disable all filters beside `test.txt` to make sure `test.txt` rules don't conflict with other rules.
3. Add `||pantip.com^$doc,uritransform=/#lead:.*//` rule to `test.txt`
4. Add `*$uritransform=/\?fbclid=//` rule to `test.txt`
5. Save `test.txt`
6. Click update filter 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/34dd89f0-472a-4521-b334-fec1fcf0353c)
7. go to `https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369` site
8. see `||pantip.com^$doc,uritransform=/#lead:.*//` doesn't work

### Expected behavior

1. `||pantip.com^$doc,uritransform=/#lead:.*//` should work even there is `*$uritransform=/\?fbclid=//` rule.
2. tracking part of url should be removed and remain only `https://pantip.com/topic/41624586`.

### Actual behavior

`||pantip.com^$doc,uritransform=/#lead:.*//` doesn't work and browser go to `https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369` when there is `*$uritransform=/\?fbclid=//` rule.

### uBO version

1.55.1rc4

### Browser name and version

Brave Browser Version 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)

### Operating System and version

Windows 11 Education 22H2

**Comment by gwarser** [comment]
Works with `//:$uritransform=/\?fbclid=//`.

**Comment by Iz-zzzzz** [comment]
Thank you (●'◡'●)
