### ISSUE TITLE
Logger doesn't display `uritransform` when filtering only `uritransform`

### ISSUE THREAD

**Issue by Iz-zzzzz** [uBlockOrigin/uBlock-issues#3126]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

From https://github.com/uBlockOrigin/uBlock-issues/issues/3125 but I enable only `||pantip.com^$doc,uritransform=/#lead:.*//` rule.

### A specific URL where the issue occurs.

```yaml
`https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369`
```

### Steps to Reproduce

1. Create test.txt file in Desktop
2. Allow uBO to access to file URLs
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/dd44d855-649c-4b18-b3ff-1238110a1789)
3. Import test.txt to uBO custom filters and add `file:///` in `trustedListPrefixes` to make sure this filter have enough permission. 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/8e5a9ec5-3238-4dc7-bf40-21fabbb57512)
4. Add `||pantip.com^$doc,uritransform=/#lead:.*//` rule to `test.txt`
5. Save `test.txt`
6. Click update filter 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/34dd89f0-472a-4521-b334-fec1fcf0353c)
7. Open Logger
8. go to `https://pantip.com/topic/41624586#lead:related:6B9mGrzkxFdzAeuBEWJhXs:6:https://pantip.com/topic/42521369` site
9. filter only `uritransform` in Logger

### Expected behavior

There is `uritransform` list when filtering only `uritransform` type .

### Actual behavior

Logger doesn't display uritransform list when filtering only "uritransform"
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/b72eabff-3241-421d-8e81-e97066f35668)

I need to search the word "uritransform" (when not filter type to display) to see the actual logs. (image below)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/9a09f49e-7408-4996-b6a9-b1cc13681d9a)

### uBO version

1.55.1rc4

### Browser name and version

Brave Browser Version 1.62.162 Chromium: 121.0.6167.164 (Official Build) (64-bit)

### Operating System and version

Windows 11 Education 22H2

**Comment by gorhill** [comment]
Thanks for reporting. Side question: why use an external list for repro steps? Point 1 to 6 could just be:

1. Add `||pantip.com^$doc,uritransform=/#lead:.*// rule` to "My filters"

**Comment by Iz-zzzzz** [comment]
Thank you (●'◡'●)

**Comment by krystian3w** [comment]
> forget whether

uri needs load from trusted resource.

> not sure whether MyFilter was

Untrusted at stable, trusted in dev by `user-` (can be copied to uBo stable at own risk until someone made nice pr with text area in support tab with mechanic disable running pasted filters ~30 minutes after save).
