### ISSUE TITLE
uBlock Origin does not filter properly at Yandex browser launch

### ISSUE THREAD

**Issue by DRCLEMENTAKATENG** [uBlockOrigin/uBlock-issues#3129]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello Github.com

This  is  error I get when I lauch Yandex browser : "Could not filter properly at browser launch. Reload the page to ensure proper filtering."

Regards.

DR CLEMENT AKATENG MD

### A specific URL where the issue occurs.

```yaml
Hello Github.com

An exact URL for the issue affecting a web page, even though it happens everywhere is: "https://2x2.su/news/spetsoperatsiya/raskryta-novaya-tsel-rossiyskoy-armii-posle-vzyatiya-avdeevki.html".

Indeed everywhere "Blocked since install is 0"

I do not think I have any more information for you to resolve this issue.

Regards


DR CLEMENT AKATENG MD
```

### Steps to Reproduce

Just download and install uBlock origin on Yandex browser and investigate

### Expected behavior

I expected uBlock Origin to block all adds for that is what it claims.

### Actual behavior

This is the actual behaviour:

Blocked on this page
0
Domains connected
0 out of 1
Blocked since install
0

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 99072
 cosmetic: 44196
 scriptlet: 19877
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76608-543, never
  easyprivacy: 33101-3, never
  plowe-0: 3787-770, never
  ublock-badware: 7725-11, never
  ublock-filters: 36373-250, never
  ublock-privacy: 949-2, never
  ublock-quick-fixes: 156-0, never
  ublock-unbreak: 2176-19, never
  urlhaus-1: 4014-0, never
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: 8 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by gwarser** [comment]
You can try this: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded
