### ISSUE TITLE
##.ad.super from EasyList is causing ##.ad to not be applied.

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#313]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

"ANNONSE" ad placeholder is not hidden by `##.ad` on `https://itavisen.no/2018/11/25/bitcoin-verdien-raser`
After bisecting by copying `##.ad` + EasyList into My filters and cut ~half every refresh I found that `##.ad.super` is causing this.

I think this was first discovered in this megathread https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-441400305

### A specific URL where the issue occurs

`https://itavisen.no/2018/11/25/bitcoin-verdien-raser`

### Steps to Reproduce

1. Open page
2. add `##.ad` to my filters
2. refresh page
3. ad placeholder is not blocked

### Expected behavior:

Filter should be applied to element.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.17.2
* Browser Name and version: Fx 63.0.3
* Operating System and version: Manjaro

**Comment by THEtomaso** [comment]
@gorhill:
Could you please apply this fix to the Legacy branch as well?

We've been discussing some issues here (which I discovered was because of this bug):
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-444092274
