### ISSUE TITLE
Websites don't load at all on brave

### ISSUE THREAD

**Issue by ravsil** [uBlockOrigin/uBlock-issues#3130]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when trying to open *any* website the page keeps loading indefinitely, if I disable uBlock Origin it finishes loading instantaneously

### A specific URL where the issue occurs.

```yaml
https://github.com
```

### Steps to Reproduce

1. [open Brave]
2. [enable Ublock Origin]
3. [go to any website]

### Expected behavior

page loads normally

### Actual behavior

page keeps loading

### uBO version

1.55.0

### Browser name and version

Brave Browser 121.1.62.165 

### Operating System and version

Ubuntu 22.04.4 LTS jammy

**Comment by gorhill** [comment]
Provide troubleshooting information as follow:

Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by ravsil** [comment]
I can't do this because the page won't open, so when I click the toolbar icon nothing happens

**Comment by ruslanbay** [comment]
Hi @ravsil 
Can you please try the following steps:

1. Navigate to `edge://extensions/`
2. Click on `Details`
3. Click on `Extension options`
4. Open the `Filter list` tab
5. Add a new filter in the `Regions, languages` section
6. Click on `Apply changes` and `Update now`

**Comment by ravsil** [comment]
Hello @ruslanbay
No I couldn't, after I clicked on `Extension options` it opened a page that wouldn't load as well

**Comment by gwarser** [comment]
Reinstall uBlock.

**Comment by gorhill** [comment]
> I can't do this because the page won't open, so when I click the toolbar icon nothing happens

Looks like your uBO installation is broken, or something else in the browser is broken. You will need to investigate more on your side -- there are no widespread report of what you are describing, the issue here is currently unactionable.

**Comment by gorhill** [comment]
> I can't do this because the page won't open, so when I click the toolbar icon nothing happens

Looks like your uBO installation is broken, or something else in the browser is broken. You will need to investigate more on your side -- there are no widespread reports of what you are describing, the issue here is currently unactionable.
