### ISSUE TITLE
Youtube and firefox issues

### ISSUE THREAD

**Issue by Gradius2** [uBlockOrigin/uBlock-issues#3133]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi,

I'm using the last version, tried beta including, and today by using youtube (firefox browser) the video in desktop mode, is wrong.  This happened today.

![1](https://github.com/uBlockOrigin/uBlock-issues/assets/11011463/0ee80e62-c4f4-4320-bcf0-5675a2e09184)

### A specific URL where the issue occurs.

```yaml
ANY video on youtube.
```

### Steps to Reproduce

Just start last firefox (v123 x64), enter youtube, and play any video.

### Expected behavior

Back to normal video size.

### Actual behavior

Desktop video size isn't correct.  Any other mode works ok.

### uBO version

uBlock Origin 1.56.1b0

### Browser name and version

Firefox v123 (64-bit)

### Operating System and version

Windows 11 x64 with all updates installed.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586#issuecomment-1954877845

**Comment by Corran006** [comment]
I am also having this issue on Firefox 123.0
