### ISSUE TITLE
no-popups: * true auto closes links opened in new tabs

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#3135]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`no-popups: * true` makes links explicitly opened in new tab to close instantly.

### A specific URL where the issue occurs.

```yaml
https://superuser.com/a/1128905
```

### Steps to Reproduce

1. Use the following settings:

```
{
  "version": "1.55.0",
  "userSettings": {
    "externalLists": "",
    "firewallPaneMinimized": false,
    "importedLists": []
  },
  "selectedFilterLists": [
    "user-filters"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "moz-extension-scheme"
  ],
  "dynamicFilteringString": "* * * block\n* * inline-script block\n* * 1p-script block\n* * 3p-script block\n* * 3p-frame block\n* * image block\n* * 3p block\nbehind-the-scene * * block",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-popups: * true\nno-remote-fonts: * true\nno-large-media: * true\nno-csp-reports: * true\nno-scripting: * true",
  "userFilters": "*$stylesheet\n*$document,csp=style-src\n"
}
```

2. Visit e.g. https://superuser.com/a/1128905

3. Click on the "Systemd/User" link inside the answer using middle mouse button or right mouse button and "Open Link in New Tab"

### Expected behavior

The URL should open normally in a new tab and the tab should remain open.

### Actual behavior

The URL opens in new tab but the tab instantly closes.

The above URL is just one example. This happens on many other websites too. Some links work fine, others don't.

Removing the `no-popups: * true` rule makes all links work as expected.

### uBO version

1.55

### Browser name and version

Tor Browser 3.0.9

### Operating System and version

Whonix 17

**Comment by gwarser** [comment]
Works as expected. The link is redirecting to different URL.

**Comment by gorhill** [comment]
Related: https://github.com/gorhill/uBlock/issues/2919

**Comment by gorhill** [comment]
> What do you mean it works? It doesn't work for me. The tab closes.

You activated the `no-popup` switch for everywhere, `* true`. You clicked on a link to open in a new tab. The URL address in the new tab does not match the clicked link, hence uBO sees it as an unwanted popup. If you do not want that behavior, override `no-popups: * true` rule with a more specific `no-popups: superuser.com false`.

**Comment by gwarser** [comment]
Searching for `house`, first link `https://nl.wikipedia.org/wiki/House_(televisieserie)`, resulted page `https://nl.wikipedia.org/wiki/House_(televisieserie)` - works as expected.

**Comment by gorhill** [comment]
`no-popups` switch is useful if you do not want to wait for or rely on filter lists to block unwanted popups on a site.

**Comment by gorhill** [comment]
Because bad sites typically do this. ANyway, Personally I think enough time has been spent on this, so I'm out.

**Comment by Rudxain** [comment]
> But why is a redirecting URL considered a popup when there is nothing really popping up?

popunders aren't popups, yet they're also undesirable.

See also (by `@LiveOverflow`):
- ["Reverse Engineering PopUnder Trick for Chrome"](https://youtu.be/PPzRcZLNCPY)
- ["Reverse Engineering Obfuscated JavaScript"](https://youtu.be/8UqHCrGdxOM)
