### ISSUE TITLE
Trusted network filter options should be `badfilter`-able in non-trusted sources

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#3136]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

From @stephenhawk8054:
 
> @gorhill I think `badfilter` doesn't work with trusted filter (for example `uritransform`) if `My filters` is not marked as trusted source?
> 
> Tested filter: `||rambler.ru/*#rcmrclid=$uritransform=/#rcmrclid=.*//` in uBO privacy list
> 
> ![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/359fb5e4-297a-4ee5-8a72-da084ff95004)

### A specific URL where the issue occurs.

```yaml
Irrelevant
```

### Steps to Reproduce

1. Add `||rambler.ru/*#rcmrclid=$uritransform=/#rcmrclid=.*//` to _"My filters"_ (which is a non-trusted source by default)

### Expected behavior

Ability to `badfilter` filters requiring trust.

### Actual behavior

Inability to `badfilter` filters requiring trust.

### uBO version

1.56.0

### Browser name and version

Any

### Operating System and version

Any

**Comment by stephenhawk8054** [comment]
I think it's fixed in dev build now.
