### ISSUE TITLE
`!#include` failing on 3rd party lists

### ISSUE THREAD

**Issue by Adolar0042** [uBlockOrigin/uBlock-issues#3137]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

using `!#include` to include filters from a filer list that is not in the same github repo fails (fetched list is entirely empty, leading to not even local filters being used)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/39769465/4a1b1d01-4121-43be-aa8b-da85f37a4f06)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/39769465/26be52bb-db7e-44d1-b0fd-30f7fe25320c)

### A specific URL where the issue occurs.

```yaml
https://raw.githubusercontent.com/Adolar0042/misc/main/no-doxxing.txt
```

### Steps to Reproduce

1. Add an `!#include` to a filter list not on the same repository
2. Try to add the filter list to uBO

### Expected behavior

Filter list is added, loaded and filters are used

### Actual behavior

Filter list is added, but fails to load.

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 373712
 cosmetic: 265380
 scriptlet: 50597
 html: 2051
listset (total-discarded, last-updated):
 added:
  https://gist.githubusercontent.com/M-rcus/9af3207273bf5d30b28c2e3892f1a412/raw/fa69c2cec0a58c0b5d10f7addf5ec90c962b5eff/Grabify_Domains.txt: 41-0, 1h
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1h.10m
  https://raw.githubusercontent.com/Adolar0042/misc/main/no-doxxing.txt: 0-0, never
  https://raw.githubusercontent.com/Adolar0042/misc/main/test.txt: 11-1, never
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2587-1, 1h.10m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifiltrs Extra.txt: 67-0, 1h.10m
  https://raw.githubusercontent.com/Karmesinrot/Anifiltrs/master/Anifltrs.txt: 404-1, 1h.10m
  https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt: 1939-0, 1h.10m
  https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist: 4837-115, 1h.10m
  adguard-generic: 79827-4153, 1h.9m
  adguard-mobile: 9117-103, 1h.9m
  adguard-spyware-url: 1463-226, 1h.9m
  [21 lists not shown]: [too many]
 default:
  user-filters: 49-0, never
  ublock-filters: 37586-431, 1h.7m Δ
  ublock-badware: 8000-14, 1h.7m Δ
  ublock-privacy: 740-51, 1h.9m
  ublock-unbreak: 2278-3, 1h.7m Δ
  ublock-quick-fixes: 121-1, 1h.7m Δ
  easylist: 81686-2269, 1h.7m Δ
  easyprivacy: 50264-1148, 1h Δ
  urlhaus-1: 8725-0, 1h.9m
  plowe-0: 3782-2, 1h.10m
filterset (user): [array of 49 redacted]
trustedset:
 added: [array of 12 redacted]
 removed:
  moz-extension-scheme
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 727 ms (selfie)
 maxAssetCacheWait: 484 ms
 cacheBackend: indexedDB
```
</details>

**Comment by Adolar0042** [comment]
through some testing I have found that the following prevents the specified url to not work
```
!#include filterlist
! >>>>>>>> https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist
!#include Grabify_Domains.txt
! >>>>>>>> https://gist.githubusercontent.com/M-rcus/9af3207273bf5d30b28c2e3892f1a412/raw/fa69c2cec0a58c0b5d10f7addf5ec90c962b5eff/Grabify_Domains.txt
```
however using a url that is from the same repository works

**Comment by gwarser** [comment]
By design. https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#include-file-name

>The sub-list must be in the same directory as the main one. It is not allowed to load a sub-list located outside where the current one resides.
