### ISSUE TITLE
$generichide is still applied even when website is whitelisted

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#314]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`$generichide` is still applied even when website is whitelisted

### A specific URL where the issue occurs

`https://www.google.com`

### Steps to Reproduce

1. Add `@@||google.com^$generichide` and browse to `google.com`, open the logger. 
2. Open the popup UI by the clicking on the extension and click on the big blue power button to whitelist `google.com`
3. Refresh the page and notice the logger

### Expected behavior:

`$generichide` doesn't get applied when whitelisted

### Actual behavior:

`$generichide` gets applied even when whitelisted

### Your environment

* uBlock Origin version: 1.17.3rc4
* Browser Name and version: Chrome 72/Firefox 65
* Operating System and version: Win 10

**Comment by gorhill** [comment]
To be clear, this was a logger output issue, the whistelisted behavior was not affected.
