### ISSUE TITLE
Prioritize "My filters" over external filter lists

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#3141]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"My filters" can be overridden by external filters.

To allow better user control "My filters" should have priority over other (external) static filters, because they are direct and explicit user settings (what the user actually wants) and filter lists are more like a general framework (which is the user enables/disables and cannot control first hand or verify line by line).

Related:

https://github.com/uBlockOrigin/uAssets/issues/22673

### A specific URL where the issue occurs.

```yaml
https://github.com/404
```

### Steps to Reproduce

1. Use the following settings:

```
{
  "version": "1.56.0",
  "userSettings": {
    "firewallPaneMinimized": false,
    "importedLists": []
  },
  "selectedFilterLists": [
    "user-filters"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "moz-extension-scheme"
  ],
  "dynamicFilteringString": "* * * block\n* * inline-script block\n* * 1p-script block\n* * 3p-script block\n* * 3p-frame block\n* * image block\n* * 3p block\nbehind-the-scene * * block",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-popups: * true\nno-remote-fonts: * true\nno-large-media: * true\nno-csp-reports: * true\nno-scripting: * true",
  "userFilters": "*$stylesheet\n*$document,csp=style-src\n*##[src^=\"data:\"]\n"
}
```

2. Navigate to https://github.com/404

**Expected:** The `*##[src^="data:"]` in My Fiilters should hide the base64 images.

**Actual:** As expected.

3. Enable EasyList (easylist) or EasyList – Social Widgets (fanboy-social) filter lists. (or both)

4. Refresh the page (with disabled cache in web console).

**Result:** `*##[src^="data:"]` has no effect. base64 images are displayed.

Tested each and every other list (with all other lists disabled). Only the 2 lists mentioned above cause this effect.

### Expected behavior

"My filters" should have priority above external static filters.

### Actual behavior

As per the example, certain rules in "My filters" can be overridden by external filters.

### uBO version

1.56

### Browser name and version

Tor Browser 13.0.10

### Operating System and version

Whonix 17

**Comment by stephenhawk8054** [comment]
It's because of `@@||github.com^$ghide`

**Comment by uBlock-user** [comment]
Sounds like https://github.com/gorhill/uBlock/issues/2904 with generic cosmetic filter being the subject here

**Comment by uBlock-user** [comment]
Sounds like https://github.com/gorhill/uBlock/issues/2904

**Comment by gorhill** [comment]
> Please kindly reconsider

No chance. This is a hobby, not a day job, and if it starts to feel like a day job, I'm out.

**Comment by gorhill** [comment]
> Does that mean you don't accept suggestions to improve the software?

Look at [the commit history](https://github.com/gorhill/uBlock/commits/master/), and look at the link in most of those commits. Does it look like I _"don't accept suggestions to improve the software"_?

I just disagree that many of [_your_ requests](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+author%3Aemanruse) are suggestions to improve to the software -- so we have diverging opinions.

And specifically, what you are asking here is not only a huge amount of work for no benefit (in my opinion), but worse, this would make the work of filter list authors very difficult because when they test filter(s), uBO would behave differently than when these tested filters are moved to a list.

**Comment by garry-ut99** [comment]
> uBO would behave differently than when these tested filters are moved to a list.

A good observation, unless the feature would be implemented as an on/off option in https://github.com/gorhill/uBlock/wiki/Advanced-settings for advanced users. (I am not saying to implement it or not, this is not a context of my comment, as the feature request might be too much ammout of work).
