### ISSUE TITLE
Pasting `*##...` filter, breaks Element Picker and causes glitches, freezes, errors, warnings and creates strange invalid filter

### ISSUE THREAD

**Issue by garry-ut99** [uBlockOrigin/uBlock-issues#3142]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Element Picker glitches / freezes for several seconds when pasting https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic `*##...` filter (for example `*##[src^="data:"]` or even `*123` can reproduce it) :
   - Element Picker glitches / freezes for several seconds (profiler shows 7,5s spent)
   - browser throws a message :  "uBO slows down the browser, continue or terminate"
   - dev and browser console throws an error: "InternalError: too much recursion" see:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion
   - after waiting and clicking further Create, a strange invalid filter is produced in My Filters which throws as invalid

Most visible on Firefox, similiar happens also on Opera but 2x faster (but still long enough to be noticeable)
Firefox : [ANIMATION](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/75703d2e-d74d-4c6c-94ce-fa4aa743b20b) + [SCREENSHOOT](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/0778768d-ddcd-47b7-bb24-3693cf9d38e7) + [PROFILER](https://profiler.firefox.com/public/5dx9s9z00vh3zg4w2efp5t18e4vk71ag2exhsyg/calltree/?globalTrackOrder=0w2&thread=3&v=10)

<details>
<summary>CONSOLE</summary>

```
InternalError: too much recursion epicker.js:688:30
    test self-hosted:3574
    fromNetworkFilter moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:688
    queryAll moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:793
    onDialogMessage moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1174
    onmessage moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1313
    (asynchroniczny: EventHandlerNonNull)
    bootstrap moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1312
    (asynchroniczny: EventListener.handleEvent)
    bootstrap moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1308
    bootstrap moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1304
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (asynchroniczny: async)
    <anonimowa> moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1329
    <anonimowa> moz-extension://xxxxxxxx-yyyy-zzzz-xxxx-yyyyyyyyyyyy/js/scriptlets/epicker.js:1336
    inject resource://gre/modules/ExtensionContent.sys.mjs:581
    AsyncFunctionNext self-hosted:852
```

</details>

Also if wait and when glitch is gone, click _Create_ button and visit _My Filters_ and notice a strange filter created with another error throwed : [SCREENSHOOT](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/23e073b7-1d1e-4873-8d07-72df5b82fb7a)

<hr>

I've discovered it when investigating the other issue :
`https://github.com/uBlockOrigin/uAssets/issues/22673`
`https://github.com/uBlockOrigin/uBlock-issues/issues/3141`

The workaround is to paste `##...` instead of `*##...`  into Element Picker since visual effect they produce is the same, and then after pressing Create, edit "My Filters" and prepend the filter by `*`, a little cumersome, but on the other side such filters are not created very often, only occasionally, I'm not sure whether Create button should be active when put anything before `##` in Picker.

Given the issue can be reproduced even with `*123` I'm not sure whether it's related to https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic and the way they are injected or is just a random coincidence.

### A specific URL where the issue occurs.

```yaml
https://github.com/404
```

### Steps to Reproduce

1. visit the page
2. open Element Picker
3. paste a https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic filter 
(for example `*##[src^="data:"]` or even a `*123` can reproduce as well)
4. notice glitch/freeze/errors like in Description
5. wait and when glitch is gone, click _Create_ button
6. visit _My Filters_ and notice a strange filter created with an error throwed :
![12](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/23e073b7-1d1e-4873-8d07-72df5b82fb7a)

### Expected behavior

No glitches / freezes / unresponsive warnings / console errors.

### Actual behavior

Glitches / freezes / unresponsive warnings / console errors.

### uBO version

1.56.1b0

### Browser name and version

Firefox 115.8.0esr / Opera 95

### Operating System and version

Win 7 SP1

**Comment by gorhill** [comment]
There is a `data:` URI on that page, which is causing issue with the filter-derived regex, I can reproduce [at regex101](https://regex101.com/r/1lFA4P/1).
