### ISSUE TITLE
Youtube não carrega video

### ISSUE THREAD

**Issue by omerocoti** [uBlockOrigin/uBlock-issues#3144]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Olá, eu falo português. A extensão começou a causar problemas no youtube há algumas semanas, porém eu só entendi que era o Ublock esses dias. Os vídeos no youtube ficam com a tela preta, todo o player fica preto, não aparece Pausar, nem volume, nem aumentar a tela. Quando eu desabilito a extensão e atualizo a página, o vídeo volta a funcionar

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com/
```

### Steps to Reproduce

1. Abra um vídeo no youtube
2. espere carregar
3. ele não carrega

### Expected behavior

ok

### Actual behavior

ok

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 122
filterset (summary):
 network: 126560
 cosmetic: 49245
 scriptlet: 20697
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81757-13, 1h.13m Δ
  easyprivacy: 50285-6, 1h.13m Δ
  plowe-0: 3782-1186, 5d.17h.47m
  spa-1: 5416-72, 4d.12h.25m
  ublock-badware: 8005-142, 1h.13m Δ
  ublock-filters: 37400-376, 1h.13m Δ
  ublock-privacy: 746-6, 1h.13m Δ
  ublock-quick-fixes: 109-5, 1h.13m Δ
  ublock-unbreak: 2223-33, 1h.13m Δ
  urlhaus-1: 8770-0, 2h.13m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 851 ms (selfie)
 maxAssetCacheWait: 210 ms
 cacheBackend: browser.storage.local
```
</details>idk

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586
