### ISSUE TITLE
ads in yhmgo.com not being blocked

### ISSUE THREAD

**Issue by ShunAn1231** [uBlockOrigin/uBlock-issues#3148]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ads between videos not being blocked

### A specific URL where the issue occurs.

```yaml
https://www.yhmgo.com/vp/23237-2-5.html
```

### Steps to Reproduce

always happens on the middle of the video

### Expected behavior

no ads

### Actual behavior

have ads

### uBO version

1.54.0

### Browser name and version

chrome 120.0.6099.216

### Operating System and version

macOS Monterey 12.7.2

**Comment by stephenhawk8054** [comment]
Your issue is already here: https://github.com/uBlockOrigin/uAssets/issues/22705 . Don't open duplicated issue in the wrong repo

**Comment by ShunAn1231** [comment]
whats wrong with my filter?

**Comment by stephenhawk8054** [comment]
Which filter? Just continue in the thread linked above
