### ISSUE TITLE
Chrome freezes on specific pages

### ISSUE THREAD

**Issue by karlhedins** [uBlockOrigin/uBlock-issues#315]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Chrome freezes when visiting specific page.

### A specific URL where the issue occurs

https://gleerupsportal.se/laromedel/publik-artikel/fa028bdd-e669-48df-8542-a7e0bc2ca030

### Steps to Reproduce

1. Visit the specific URL mentioned above
2. Page crashes

### Expected behavior:

The page works.

### Actual behavior:

Chrome freezes, forcing you to force quit the Google Chrome process.

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Google Chrome, Version 70.0.3538.110 (Official Build) (64-bit)
* Operating System and version: OSX Sierra, 10.12.6

We, the dev team of gleerupsportal.se, and many of our customers have experienced the same freeze bug on multiple platforms, including Chromebooks. Each time we have narrowed it down to the bug occurring with Google Chrome and the only activated extension being uBlock Origin. Without uBlock Origin everything works fine.
Another Chrome Extension team, Wizkids App Writer has also experienced the same problem on gleerupsportal, and found a temporary workaround by altering the onHeadersReceived listener.
They have reported the issue to the Chromium team here:
https://bugs.chromium.org/p/chromium/issues/detail?id=908067

As you can see in the in the Chromium issue above they seem to have identified the problem to be on onHeadersReceived. Could one potential source in uBlock be:
https://github.com/gorhill/uBlock/blob/138e1bf55866e4a97c2ef192ffb4d6489ff7e498/src/js/traffic.js#L1132

**Comment by gwarser** [comment]
Unable to reproduce in

Chromium
Version 70.0.3538.110 (Official Build) Manjaro Linux (64-bit)

**Comment by uBlock-user** [comment]
Neither on Chromium 72 on Win 10, looks like Mac specific.

**Comment by gorhill** [comment]
I reproduced, whole system lock as a result.

**Comment by gorhill** [comment]
Once I got out of the system lock by killing Chromium, I can no longer reproduce.

**Comment by uBlock-user** [comment]
So it only happens for the first time ?

**Comment by gorhill** [comment]
The fact that another extension is causing the same issue suggest a browser issue. Now if only there was a 100% way to reproduce at will.

**Comment by karlhedins** [comment]
Thanks for looking in to this so fast! It a little tricky reproduce on that page, which is a publicly available resource. The freeze bug occurs more frequently on that specific page for logged in users, I could look into if I may send you credentials if that would help you reproduce it?

**Comment by karlhedins** [comment]
> Can you see if you can reproduce with [Adguard](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg)? It also uses a onHeadersReceived listener in a blocking way.

I just tried and can confirm that the freeze bug also occurs with Adguard being the only extension. I think the bug has been reported with Adblock Plus as well by some of our customers

**Comment by gorhill** [comment]
Ok found a way to reproduce every time on my side. Need to explicitly clear cache first. Bypassing teh cache at reload time is not sufficient.

**Comment by uBlock-user** [comment]
@karlhedins I can reproduce on those links but only for the `first visit`. Visiting again and the crash doesn't occur.

**Comment by uBlock-user** [comment]
> Need to explicitly clear cache first (ctrl-shift-delete). 

Or visit links that you haven't visited before, so the cache doesn't exist.

**Comment by gorhill** [comment]
Narrowing: if I block all media on that site using `*$media,domain=gleerupsportal.se`, issue does not occur.

**Comment by gorhill** [comment]
Specifically, if I block `https://gleerupsportal.se/uploads/1891/happy6_2_1a.mp3`, issue does not occur. As soon as I unblock that resource, issue occurs.

**Comment by karlhedins** [comment]
I can also confirm that I am unable to reproduce the bug if I block media files like you mentioned @gorhill 

We do have redirects for media files like so:
/uploads/1891/happy6_2_1a.mp3
to
https://gleerups-new-prod-uploads.s3.amazonaws.com/1891/happy6_2_1a.mp3

Could that matter?

**Comment by gorhill** [comment]
> Could that matter?

uBO does not care really, the issue is the browser locking up for some reasons (one CPU core @ 100%). It seems to be some edge cases being hit. Best is to report further details to the Chromium issue <https://bugs.chromium.org/p/chromium/issues/detail?id=908067>.

Given that's it's 100% reproducible after clearing cache should make it easy for Chromium devs to figure out the core issue.

On thing maybe to try just to maybe narrow further, is that I notice that redirected media is being requested twice on that page. Could you try to see what happens if you modify the page such that only one request is made for it?

**Comment by gorhill** [comment]
Here is a minimalist extension to reproduce the issue:

`manifest.json`:

    {
        "manifest_version": 2,
        "name": "Chromium issue 908067",
        "version": "1.0",
        "background": {
            "scripts": ["background.js"]
        },
        "permissions": [
            "webRequest",
            "webRequestBlocking",
            "<all_urls>"
        ]
    }

`background.js`:

    chrome.webRequest.onHeadersReceived.addListener(
        function(details) {
        },
        {
            urls: [ '<all_urls>' ],
            types: [ 'media' ]
        },
        [
            'responseHeaders',
            'blocking'
        ]
    );

Note that the listener does absolutely nothing.

**Comment by karlhedins** [comment]
@gorhill Thank you for looking into this and zooming in on the problem so fast. I saw you posted in the Chromium thread as well, great! Fingers crossed that the Chromium team will look into this soon.

The other Chrome extension team, Wizkids App Writer, also being used by gleerupsportal users having experienced the freeze bug mentioned that they managed to find a temporary patch that would not trigger the Chrome bug with the onHeadersReceived setup. I don't have any more details on it than that - but could a temporary workaround also be an option for uBO?

**Comment by YePpHa** [comment]
I highly doubt that you would be able to use our workaround. We limited our scope to only `main_content`, `sub_content` and `xmlhttprequest`. Below I've also written the diffs of our change to fix the issue on our end:

```diff
    return { "responseHeaders": details.responseHeaders };
- }, { "urls": ["<all_urls>"] }, ["blocking", "responseHeaders"]); 
+ }, {
+   "urls": ["<all_urls>"],
+   "types": [
+     "main_frame",
+     "sub_frame"
+   ]
+ }, ["blocking", "responseHeaders"]); 
```

```diff
    return { responseHeaders: details.responseHeaders };
  }, {
-   urls: ['<all_urls>']
+   urls: ['<all_urls>'],
+   types: ["xmlhttprequest"]
+ }, ["blocking", "responseHeaders"]);
```

**Comment by gorhill** [comment]
Unfortunately, uBO needs to listen to network of types `media` in its onHeadersReceived to implement the feature "Block media elements larger than [...] kB".

**Comment by gorhill** [comment]
I was not able to reproduce with Google Chrome 72.0.3610.2 dev (64-bit) by the way.

**Comment by YePpHa** [comment]
@gorhill same here. I just replied to phanindra on https://bugs.chromium.org/p/chromium/issues/detail?id=908067 with that information. Hopefully they can include that patch in the next version of Chrome instead of having to wait for two "major" updates.

**Comment by uBlock-user** [comment]
I was able to reproduce on `72.0.3617.0`, not gone yet.

**Comment by YePpHa** [comment]
@uBlock-user if you were able to reproduce it on `72.0.3617.0` please report it on https://bugs.chromium.org/p/chromium/issues/detail?id=908067 as the discussion here wont really do anything towards fixing this (other than being informative to other users).

**Comment by uBlock-user** [comment]
Posted, and what I meant by reproducible was the same I said which I said on https://github.com/uBlockOrigin/uBlock-issues/issues/315#issuecomment-441705048

**Comment by YePpHa** [comment]
@uBlock-user what about if you go to settings and clear browser data?

![2018-11-27_15-43-54](https://user-images.githubusercontent.com/2348303/49089205-4ea23880-f25b-11e8-8873-579d8ed8d888.gif)

**Comment by uBlock-user** [comment]
Yes, I did affirm that in https://github.com/uBlockOrigin/uBlock-issues/issues/315#issuecomment-441705544 and on the bug tracker. 

To summarise-- if the page is not cached, it will happen and by gorhill repro too.

**Comment by YePpHa** [comment]
Thank you. Seems like I'm not that good at reading. I definitely remember I read your comment, but I didn't link it that it was you who wrote it. Sorry about that.

**Comment by karlhedins** [comment]
We have deployed a fix to our production environment and cannot reproduce the freeze bug there anymore. The fix consisted of changing relative URLs for mp3-files. Before mp3-files would have the following format:
`/uploads/1891/happy6_2_1a.mp3`
that would get a redirect to:
`https://gleerups-new-prod-uploads.s3.amazonaws.com/1891/happy6_2_1a.mp3`

We have moved the old version of gleerupsportal that still uses relative mp3-links and can cause the freeze bug to our test environment.
Here are new links that you can try that can reproduce the bug:

https://test.gleerupsportal.se/laromedel/publik-artikel/96d21a87-a8f7-40b5-a555-f6551ec1940d

https://test.gleerupsportal.se/laromedel/publik-artikel/fa028bdd-e669-48df-8542-a7e0bc2ca030

https://test.gleerupsportal.se/laromedel/publik-artikel/9ad573ea-4052-4093-b6cd-b4047f4c95be

https://test.gleerupsportal.se/laromedel/publik-artikel/d30bee4d-31a9-4faa-b9d1-b8deb0edd82d
