### ISSUE TITLE
Option to ignore all Whitelist filters (Feautre request)

### ISSUE THREAD

**Issue by JackMauro** [uBlockOrigin/uBlock-issues#3150]
### Description

Is it possible to add an option to ignore all whitelist filters (@@ and @#@ in lists) even if that could break some sites?
It may be placed in Options page, near "Ignore generic cosmetic filters".

The request is because many lists uses whitelist for shared components and this may be a privacy issue in some cases, let's say a list blockes all CDNs requests and another (in this case "AdGuard – Mobile Ads") whitelists @@||maxcdn.bootstrapcdn.com/font-awesome^

The ""Ignore all whitelist filters." would solve this problem.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/3353
