### ISSUE TITLE
Yandex browser

### ISSUE THREAD

**Issue by DRCLEMENTAKATENG** [uBlockOrigin/uBlock-issues#3152]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

UBlock not blocking ads on Yandex browser

### A specific URL where the issue occurs.

```yaml
Yandex.ru/Yandex.com
```

### Steps to Reproduce

1. Download Yandex browser.
2. Install UBlock as an 

### Expected behavior

UBlock to block ads.

### Actual behavior

UBlock is not blocking ads on Yandex browser.

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Chromium: 120
filterset (summary):
 network: 124821
 cosmetic: 45582
 scriptlet: 20132
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 81908-13, 20h.24m Δ
  easyprivacy: 50320-6, 20h.24m Δ
  plowe-0: 3782-1186, 5d.4h.1m
  ublock-badware: 7717-142, 20h.24m Δ
  ublock-filters: 37127-353, 20h.24m Δ
  ublock-privacy: 745-6, 20h.24m Δ
  ublock-quick-fixes: 131-6, 20h.24m Δ
  ublock-unbreak: 2230-33, 20h.24m Δ
  urlhaus-1: 8470-0, 1d.3h.24m
filterset (user): [empty]
trustedset:
 removed:
  chrome-extension-scheme
  chrome-scheme
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: 516 ms
 cacheBackend: browser.storage.local
```
</details>

**Comment by iam-py-test** [comment]
Yandex browser used to (and maybe continues to?) intentionally break uBlock Origin: https://github.com/uBlockOrigin/uBlock-issues/issues/2627#issuecomment-1528883618
It is not supported by uBlock Origin.
Thank you.
