### ISSUE TITLE
Cloudflare Captcha removal with uBlockOrigin possible ?

### ISSUE THREAD

**Issue by Akossimon** [uBlockOrigin/uBlock-issues#3153]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

is Cloudflare Captcha removal with uBlockOrigin possible ?

### A specific URL where the issue occurs.

```yaml
its pretty much on all login pages this cloudflare captcha...google seaarches dont show any results on how to remove this virus behavior of this captcha.... is it possible to have it blocked or removed with your plugin ?
```

### Steps to Reproduce

on firefox login to discord 

### Expected behavior

login to discord interface

### Actual behavior

cloudflare captcha asking to confirm before login is possible 

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 228798
 cosmetic: 45622
 scriptlet: 18815
 html: 1736
listset (total-discarded, last-updated):
 added:
  https://go.cbro.win/dtc: 0-0, never
  https://magnificent-listen.com/b-3MVM0-P.3Bpvvcb_mcVvJQZHDS0E0/OhDYQq5cOPDWcu1sL/TeQz4xNEDNkm4/NazcYM: 0-0, never
  curben-phishing: 104290-43, 5m
 default:
  user-filters: 45-8, never
  ublock-filters: 37345-111, 5m Δ
  ublock-badware: 7721-14, 5m Δ
  ublock-privacy: 739-0, 5m Δ
  ublock-unbreak: 2291-0, 5m Δ
  easylist: 81975-623, 5m Δ
  easyprivacy: 50320-864, 5m Δ
  urlhaus-1: 8150-0, 5m
  plowe-0: 3782-1, 8d.22h.59m
  ublock-quick-fixes: 130-1, 5m Δ
filterset (user): [array of 47 redacted]
trustedset:
 added: [array of 177 redacted]
 removed:
  about-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 26 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 708 ms (selfie)
 maxAssetCacheWait: 453 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gwarser** [comment]
Not possible. Scan your PC for viruses or malware. Change your IP.

**Comment by gorhill** [comment]
> `https://go.cbro.win/dtc: 0-0, never`
> `https://magnificent-listen.com/b-3MVM0-P.3Bpvvcb_mcVvJQZHDS0E0/OhDYQq5cOPDWcu1sL/TeQz4xNEDNkm4/NazcYM: 0-0, never`

These are not filter lists, these are links to porn websites, remove this from custom lists.

Given this and what else I see in your troubleshooting information, it seems you might be misconfiguring uBO, I suggest you reset and stick to defaults.
