### ISSUE TITLE
Add a scriptlet to intercept atob call and prune its text output

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#3157]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

https://github.com/AdguardTeam/Scriptlets/issues/410

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com/watch?v=35kwlY_RR08
```

### Steps to Reproduce

Not trivial if you don't have an account reached the 3-strikes warning count but see the link

### Expected behavior

NA

### Actual behavior

NA

### uBO version

1.56.0

### Browser name and version

Google Chrome 122.0.6261.95

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
A generic approach of what you are asking is `trusted-replace-outbound-text`.

**Comment by stephenhawk8054** [comment]
Looks like recently youtube is using the same method for their new type of ads so I think it's good to have `trusted-replace-outbound-text` in this dev cycle.

**Comment by Yuki2718** [comment]
Yes, now this issue should be given higher priority than before, as it is used for SSAP ads too.

**Comment by troysjanda** [comment]
what would be an example filter look like?

**Comment by iam-py-test** [comment]
As I understand it:
```adblock
##+js(trusted-replace-outbound-text, [function to target], [string to replace/pattern], [replacement])
```
Example:
![atob(btoa("foo Hello world")) returning "bar Hello world"](https://github.com/uBlockOrigin/uBlock-issues/assets/84232764/6f31e050-7f86-4c36-badb-6d33cc06b445)

```adblock
example.com##+js(trusted-replace-outbound-text, atob, foo, bar)
```
Thanks

**Comment by Yuki2718** [comment]
I replicated `282054944` error with
```
||www.youtube.com/watch?v=$doc,xhr,1p,replace=/"trackingParam":"kx_fmPxhoPZR[-_0-9A-Za-z]+?[-_0-9A-Za-z]{45}lLKPQ-SS"\}/"trackingParam":"kx_fmPxhoPZRS0Wj9ol2lYijBzUieMcOF7P3Jfc8Boa8uj6tqwJxJcpJN3DxUP9Xk_c5292Mcn9BZ9ZQoa0PoLk8Q6kBWQKla3TeAwsdgE-iFUM4YAbzRgkuMsNLBwOcCE59TDtslLKPQ-SS"}/
||www.youtube.com/youtubei/v1/player?$xhr,1p,replace=/"trackingParam":"kx_fmPxhoPZR[-_0-9A-Za-z]+?[-_0-9A-Za-z]{45}lLKPQ-SS"\}/"trackingParam":"kx_fmPxhoPZRS0Wj9ol2lYijBzUieMcOF7P3Jfc8Boa8uj6tqwJxJcpJN3DxUP9Xk_c5292Mcn9BZ9ZQoa0PoLk8Q6kBWQKla3TeAwsdgE-iFUM4YAbzRgkuMsNLBwOcCE59TDtslLKPQ-SS"}/
```
but `www.youtube.com##+js(trusted-replace-outbound-text, atob, /\n.\n.playerConfig\.ssapConfig\.ssapPrerollEnabled.{2}(?:tru|fals)e/, )` doesn't work.

**Comment by ryanbr** [comment]
Maybe add an log option, so if its succesful or not in replacing a function.

**Comment by stephenhawk8054** [comment]
I haven't found how to log it when successful yet, but you can log the outbound text in general by

```adb
example.com##+js(trusted-replace-outbound-text, atob)
```

**Comment by gorhill** [comment]
> do you know `safe.logLevel` works?

It's the speaker in the logger.

**Comment by stephenhawk8054** [comment]
Oh... This is the first time I hear about it. Don't know why I haven't wondered myself about what that button is 😄 

---

Yeah, confirm I can see the outbound text now
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/66517106/9ffccb75-ae11-454e-adbf-bd80c8c5d2ea)

**Comment by uBlock-user** [comment]
> trusted-replace-outbound-text

They can be used to address reddit's data collection and tracking I think.

**Comment by Yuki2718** [comment]
We now need an option or a new scriptlet to decode/encode text. See https://github.com/AdguardTeam/Scriptlets/issues/410#issuecomment-2079711098
