### ISSUE TITLE
System fonts are not used when remote fonts are blocked

### ISSUE THREAD

**Issue by WhyNotHugo** [uBlockOrigin/uBlock-issues#3158]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have `font awesome` installed on my system (installed via `apk add font-awesome`).

If I enable `Block remote fonts` on uBlock origin, when I visit a website which uses `FontAwesome`, the remote font is blocked. However, the font available on my local system is not used either (the expectation is that it should).

On the other hand, if I visit a page which specifies this same font in a `font-family` without trying to load the font from a remote server, it is not blocked. E.g.: If I put this on an empty HTML page that doesn't load any custom fonts, it renders fine:

```html
<div style="font-family: 'FontAwesome'"></div>
```

This can be generalised to all fonts; if remote fonts are blocked, system fonts that are available are not used either.

It would seem that "block remote fonts" also blocks _system_ fonts with a matching name.

### A specific URL where the issue occurs.

```yaml
https://vdirsyncer.pimutils.org/en/stable/
https://rust-lang.github.io/mdBook/
```

### Steps to Reproduce

0. Install FontAwesome font on your system.
1. Block remote fonts on uBlock origin
2. Visit https://rust-lang.github.io/mdBook/

You can really use any other font to reproduce, you just have to install it first, and then visit a website using that font.

### Expected behavior

Blocking remote fonts should not block system fonts.

### Actual behavior

Blocking remote fonts blocks system fonts with the same name.

### uBO version

1.56.0

### Browser name and version

firefox-123.0-r3

### Operating System and version

Alpine Linux Edge

**Comment by gorhill** [comment]
This is not a uBO issue, the browser is the one picking which fallback fonts to use when webfonts are blocked.

**Comment by WhyNotHugo** [comment]
The browser picks the font correctly when uBlock is not involved.  
The browser picks the wrong font when uBlock is involved.

It sounds to me like the problematic factor is uBlock; what am I missing in this picture?

**Comment by WhyNotHugo** [comment]
If the remote site _does not_ try to load the webfont, the browser will use the system one normally. Only when uBlock origin blocks the font does Firefox fail to load it.

**Comment by gorhill** [comment]
> If the remote site _does not_ try to load the webfont

What do you mean by "_not_ try"? If the font resource is in your browser cache, the _browser_ won't try to fetch the resource and will use the cached instance.

**Comment by gorhill** [comment]
Looks to me you are looking for the browser to use your system fonts if their name matches the webfonts. You have to file an issue with browser developers. uBO has no knowledge of system fonts or anything outside it's browser-assigned sandbox. Whatever happens when a webfont is blocked is dictated by the browser.

**Comment by WhyNotHugo** [comment]
I'll rephrase: If the remote site does not include any reference to a remote font, the browser will use the system one normally. Example page:

```html
<html>
<head></head>
<body>
  <div style="font-family: 'FontAwesome'"></div>
</body>
</html>
```

On a page which loads a remote font (e.g.: https://vdirsyncer.pimutils.org/en/stable/), uBlock origin blocks `FontAwesome`, and the system font is not used.

> Looks to me you are looking for the browser to use your system fonts if their name matches the webfonts of a site.

Yes, this is what I want, and the browser does this by default. Try out the above HTML.

**Comment by garry-ut99** [comment]
Maybe because the site actually smuggles js files as fonts:

![ss_01](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/9840b650-411a-4a10-8044-fcf305d3a1b2)

**Comment by gorhill** [comment]
The issue is that the webpage defines a `FontAwesome` as a webfont, and when that webfont is blocked, your browser won't try to fallback to a local font because it doesn't know that any of your local font is a match -- only you know this. Maybe asks the browser devs about this.

uBO doesn't know better either, it has no access to your system.

The only workaround I can think of for uBO is that whenever remote fonts are blocked for a given website:

Inject a CSS declaration to redefine `@font-face` declaration for `FontAwesome` to a packaged `web_accessible_resources` FontAwesome font file. Of course this is not a fallback to whatever system font you have installed, this is just not possible for uBO, no matter how you insist uBO should do it.

But doing the above is just for one specific font, this would open the door to having to endlessly fulfill requests to keep adding this font or that font. etc.

You might be able to solve this issue on your side by using user styles:

```css
@font-face {
    font-family: 'FontAwesome';
    src: url('file:///path.to.your.fontawesome.file');
}
```

Or from what I've read, maybe simpler:

```css
@font-face {
    font-family: 'FontAwesome';
    src: local('FontAwesome');
}
```

**Comment by WhyNotHugo** [comment]
> your browser won't try to fallback to a local font because it doesn't know that any of your local font is a match

The browser resolves the webfont fine for the following example:

```html
<html>
<head></head>
<body>
  <div style="font-family: 'FontAwesome'"></div>
</body>
</html>
```

Firefox normally the browser tries fallback fonts. What you're saying is that **if and only if** uBO blocks a webfont with a matching name, then Firefox will not try fallback fonts?

**Comment by garry-ut99** [comment]
To OP: does it happen on Chromium too or not, maybe I'm wrong but maybe a duplicate of :
- https://github.com/uBlockOrigin/uBlock-issues/issues/1631

**Comment by WhyNotHugo** [comment]
Thanks, I think l that I understand enough details to open an issue on the Firefox side.

**Comment by dumol** [comment]
> Thanks, I think l that I understand enough details to open an issue on the Firefox side.

Have you found the time to report this? Thanks! (Having similar issues, as reported at https://github.com/uBlockOrigin/uBlock-issues/issues/1631)
