### ISSUE TITLE
Improve Troubleshooting information

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#3159]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Two issues:
1. Show modification rules such as `$replace`, `$redirect`, `$removeparam` applied on the page too
2. Do not redact if entries are a few (ex. < 4)

For 2. I often find `switchRuleset: added: [array of 1 redacted]` or `[array of 2 redacted]`. The issue may be user simply disabled cosmetic filtering on the page so do not redact for very small numbers of entries

### A specific URL where the issue occurs.

```yaml
chrome-extension://extensionID/support.html
```

### Steps to Reproduce

Click the report button on any youtube video with any sigle change of switch rule

### Expected behavior

uBO should show all these

### Actual behavior

Not

### uBO version

1.56.0

### Browser name and version

Chrome 122.0.6261.95

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> `$replace`, `$redirect`, `$removeparam`

These are network filtering engine-related, this would require to enable logging in the background, and thus a severe downgrade in CPU- and memory-efficiency, as if the logger was enabled.

> For 2. I often find `switchRuleset: added: [array of 1 redacted]` or `[array of 2 redacted]`. The issue may be user simply disabled cosmetic filtering on the page so do not redact for very small numbers of entries

The state of per-site switches is reported in the `popupPanel` section, for example [see this report](https://github.com/uBlockOrigin/uAssets/issues/22757). The purpose of the redaction is to avoid leaking personal data.

**Comment by Yuki2718** [comment]
> The state of per-site switches is reported in the `popupPanel` section,

Oh, missed that. Understood.

**Comment by Yuki2718** [comment]
> These are network filtering engine-related, this would require to enable logging in the background, and thus a severe downgrade in CPU- and memory-efficiency, as if the logger was enabled.

Just an idea, but maybe add a button to enable this and reload the page in `/support.html`? But user have to check the issue persist after the reload.
