### ISSUE TITLE
In the "My Filters" tab, no information is shown when the list is disabled

### ISSUE THREAD

**Issue by ruihildt** [uBlockOrigin/uBlock-issues#3161]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When "My filters" list is deactivated in the "Filters list", users are confused that adding custom filters in the "My filters" tab doesn't work, because they don't notice the whole thing is disabled.

I would like to suggest showing a message on the "My filters" tab page when the "My filters" list isn't enabled.

This is especially an issue for Mullvad Browser users, since the "My filters" list is disabled by default, for browser fingerprinting concerns (custom filters could make you more uniquely identifiable).

(FYI, I'm working for Mullvad on the Mullvad Browser)

### A specific URL where the issue occurs.

```yaml
https://mullvad.net
```

### Steps to Reproduce

- Start Firefox with uBlock Origin
- Click on the 
- Disable the "My filters" list in the "Filters list" tab
- Go to the "My filters" tab

### Expected behavior

When the "My filters" list is disabled, an information message is displayed in the "My filters" tab.

### Actual behavior

When the "My filters" list is disabled, there is no way to know in the "My filters" tab that the list is currently disabled.

### uBO version

1.56.0

### Browser name and version

Firefox 123

### Operating System and version

Fedora KDE Spin 39

**Comment by garry-ut99** [comment]
Also a related comment wherein someone already asked same: 
> UnitedMarsupials : https://github.com/uBlockOrigin/uBlock-issues/issues/3076#issuecomment-1894915410 : But shouldn't there have been a _warning_ of some sort?

**Comment by gorhill** [comment]
How about a checkbox to enable/disable "My filters" directly in the pane?

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/eccd2b0b-5385-4079-b9bf-b31b20e87e1a)

**Comment by ruihildt** [comment]
@gorhill That would be even clearer.

**Comment by garry-ut99** [comment]
I definately agree to the above comment, these tickboxes take precious space in My filters tab on Mobile, as a result it's now more hard/cumbersome to edit/type and maintentain user filters.

> (...) add a button to collapse the checkbox section?

Maybe also to collapse "Do not add filters from untrusted sources." message as well.

**Comment by u-RraaLL** [comment]
Nice changes. The search input placeholder which is meant to replace the outside magnifying glass icon kinda looks like a pin/location icon to me though. Why not go the same route as in the `Filter lists` pane where the svg is simply inside the input?

If you want to keep the placeholder method instead, probably best to change it in that pane too. For unity.

But I think a better choice for a placeholder might be the `telephone recorder` which looks like the right-facing magnifying glass: `&#2315;`.

**Comment by gorhill** [comment]
> better choice for a placeholder might be the `telephone recorder`

That's how it looks on my side, in both Chromium and Firefox:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/4fe85b6c-ce6c-487c-aa91-43936fbbd8c6)

I had forgotten about what I did for "Filter lists", but the idea was that I wanted to keep it simple. There is an emoji for magnifier -- 🔍 -- but support is not guaranteed.

**Comment by krystian3w** [comment]
Old character in attr is not compatible with Chrome on Windows 7.

I think possible use:

```css
::placeholder { font-size: larger }
```

**Comment by garry-ut99** [comment]
There is an issue related to the new _Support maximizing editor to viewport size_ functionality on Mobile, sometimes after changing/editing, and then pressing _minimize editor_  icon-button to return to normal view, another button - _Apply_ button is accidentaly/randomly being pressed altogether because _Apply_ button is perfectly behind the  _minimize editor_  icon-button, the issue happens when the press/tap is a long enough (but still visually short), it happens only on Mobile, it doesn't happen on Desktop when clicking using mouse, so it seems that on Mobile longer pressings/taps are considered as double/multi "clicks", hence if there is a second button hidden behind the first button, they sometimes are pressed/triggered both at the same time, which is not an expected behaviour, at last not when triggered randomly/accidentaly.

**Comment by gorhill** [comment]
The event handler for the search bar is hooked onto `mousedown`, I can't remember why I implemented that way. Using  `mousedown` instead of `click` is probably what is causing this issue.

**Comment by u-RraaLL** [comment]
Weird,  I've been able to reproduce this on my 3rd and 4th try, but not any of the latter dozens of tries I've made.

**Comment by garry-ut99** [comment]
Another issue is that Undo / Redo doesn't work in "My filters" and "Trusted sites", for a comparision - it works fine in "Filter lists" and "My rules".

**Comment by gorhill** [comment]
it works on my side when the search field has focus, i.e. when the caret is visible in the search field.

**Comment by garry-ut99** [comment]
I forgot to check in Chromium - yes indeed it does work in Chromium, but not in Firefox.

**Comment by gorhill** [comment]
Works the same in Firefox on my side.

**Comment by garry-ut99** [comment]
The issue occurs in Firefox 115 ESR only, I apologize I just forgot to check on Chromium/Firefox 124, I won't bother you with a repair on the FF 115 ESR, unless you decide to do it yourself.

**Comment by gorhill** [comment]
When you reproduce the issue, is the undo applied to the content of the CodeMirror editor?

**Comment by garry-ut99** [comment]
No, undo/redo is broken in CodeEditor as well.

By the way also when I wrote "in Firefox 115 ESR only" I didn't actually test on FF 116-123, 
so it might happens also somewhere in between FF 116-123 as well.

**Comment by gwarser** [comment]
In code viewer - how to bring back the search toolbar after using the maximize button? The whole toolbar disappears. 

See https://github.com/MasterInQuestion/talk/discussions/46

**Comment by gorhill** [comment]
I don't understand what's being discussed. Search toolbar is still there after maximizing.

![Image](https://github.com/user-attachments/assets/5b33f04d-6522-4187-a51b-d7b1532d7ff0)
