### ISSUE TITLE
Add a flag image for Belgium + a better flag image for Nepal

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#3172]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

(*De facto* moving https://github.com/gorhill/uBlock/pull/3910 to this issue report:)

Chromium browsers on Windows 10/11 currently have some minor issues with the Belgian and Nepali flags, where
* The Belgian flag isn't showing a flag (but instead shows one ofMicrosoft's 2-letter flag replacements) due to missing country codes in `unicodeFlagToImageSrc` in https://github.com/gorhill/uBlock/blob/master/src/js/i18n.js.
* The Nepali flag is not transparent, considering the flag's shape.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/22780683/3fe35e39-5f4e-43fb-8812-8fe41b32b051)

As the main uBO repo already has a full set of *[Flags of the World](https://github.com/gorhill/uBlock/tree/master/src/img/flags-of-the-world)* images, adding `[ '🇧🇪', 'be' ],` to i18n.js would on paper fix the missing Belgian flag. Similar emote-to-imagename matches can be done for dozens of other flags just to be sure, though I apparently managed to botch many of the ones in my original PR.

For Nepal, replacing https://github.com/gorhill/uBlock/blob/master/src/img/flags-of-the-world/np.png with the below flag, should work pretty well:

![np](https://github.com/uBlockOrigin/uBlock-issues/assets/22780683/90503501-ced7-4d34-8686-05fb2ac730bc)

Having thought about and kept an eye on the original PR for a while, I feel now that the best option for me is to move the report here, to allow better discussion and emote votes.

### A specific URL where the issue occurs.

```yaml
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html
```

### Steps to Reproduce

1) Install a Chromium-based browser in Windows 11, e.g. Vivaldi or Chrome.
2) Install uBlock Origin stable, which is 1.56.0 at the time of writing.
3) Open uBO's settings' "Filterlists" page.
4) See that there's minor oddities with the Belgian and Nepali flags in the EasyDutch and IndianList rows.

### Expected behavior

That the Belgian flag shows up as an image in Windows+Chromium environments, and that the Nepali flag is properly transparent on uBO's grey background instead of being inside a white square.

### Actual behavior

The 2 flags in question aren't optimally rendered.

### uBO version

1.56.0

### Browser name and version

Vivaldi 6.6.3271.50 x64

### Operating System and version

Windows 11 23H2 x64, with all monthly 23H2 updates installed since

**Comment by gorhill** [comment]
If you can submit a pull request with only the changes required to fix the issue here, I will merge it immediately.

**Comment by DandelionSprout** [comment]
Okay, sure thing. Give me 10min.
