### ISSUE TITLE
about "my filter" section on ublock.

### ISSUE THREAD

**Issue by NessunoIM** [uBlockOrigin/uBlock-issues#318]
Is possible to add a button in "my filters" page to view my filters in anticronological order?
Or simply set this anticronological order by default.
I see first old filters and in the bottom the newer.
Is not an important feature, but for me that I have so many filters could be useful and more logical.

**Comment by gorhill** [comment]
Declining, the time stamp added by uBO is not guarantee to be there, is a separate comment not guaranteed to always stay associated with the added filter. Overall, too complicated, I have no interest to work on this.

**Comment by garry-ut99** [comment]
Also similiar/related : https://github.com/gorhill/uBlock/issues/647 (the both issues speak about _ordering_, even if the proposed orderings are different). (I try to not necropost, but maybe it's useful to mention given we're already discussing `#3019`.)
