### ISSUE TITLE
My filters are not synced between different browsers connected to my Firefox account

### ISSUE THREAD

**Issue by diogoeichert** [uBlockOrigin/uBlock-issues#3180]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

When I sync a new Firefox browser to my account, I need to add the custom filters under My filter again. They are not being automatically synced.

### A specific URL where the issue occurs.

```yaml
https://www.reddit.com/
```

### Steps to Reproduce

1. Go to a website that supports login with Google;
2. See that the "login with Google" popup appears;
3. Add the filter to avoid the annoyance manually: `accounts.google.com/gsi/*` (because they were not automatically synced from Firefox account);
4. Reload the website to see that the filter now works again.

### Expected behavior

I'd like my filters to be automatically synced between all Firefox browsers that are connected to my account.

### Actual behavior

I have to re-apply the filters under My filters for every new browser instance.

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 124
filterset (summary):
 network: 126833
 cosmetic: 45766
 scriptlet: 19009
 html: 1725
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37608-163, 38m Δ
  ublock-badware: 8086-15, 38m Δ
  ublock-privacy: 782-0, 38m Δ
  ublock-unbreak: 2305-0, 38m Δ
  ublock-quick-fixes: 239-0, 38m Δ
  easylist: 83106-642, 38m Δ
  easyprivacy: 50406-832, 38m Δ
  urlhaus-1: 8840-0, 10h.13m
  plowe-0: 3763-0, 10h.13m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 952 ms (selfie)
 maxAssetCacheWait: 248 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gwarser** [comment]
Enable "Cloud storage" https://github.com/gorhill/uBlock/wiki/Cloud-storage

Filters will not be synced automatically - you will need to click a button.

**Comment by gwarser** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/783 ?

**Comment by garry-ut99** [comment]
Yes.
