### ISSUE TITLE
`no-large-media` can cause a large volume of repeated requests for audio file

### ISSUE THREAD

**Issue by filip-hejsek** [uBlockOrigin/uBlock-issues#3184]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When `no-large-media` is enabled and a large audio file is opened (as the top level document), Firefox makes repeated attempts to stream the audio, downloading hundreds of megabytes of data very quickly.

### A specific URL where the issue occurs.

```yaml
https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451
```

### Steps to Reproduce

1. In uBlock Origin settings, enable blocking of large media elements
2. Open a large audio file in a new tab (for example [this one](https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451))
3. Open the uBlock Origin request log or the network tab in browser console and observe an excessive amount of requests

### Expected behavior

Either the audio file should be blocked in such a way that the browser doesn't attempt to download it again, or alternatively the file should play without interference from uBlock Origin

### Actual behavior

The browser makes a large number of requests, downloading hundreds of megabytes in a short time.

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +6 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +6 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +5 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +4 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +3 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +3 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +3 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +3 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +2 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +1 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 |  |  | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
| +0 | no-large-media: * true | -- | static.wikia.nocookie.net | 1 | get | media | `https://static.wikia.nocookie.net/undertale/images/e/ee/MEGALOVANIA_music.ogg/revision/latest?cb=20160401053451` |
</details>

### uBO version

1.56.0

### Browser name and version

Firefox 124.0

### Operating System and version

Manjaro Linux

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1201

**Comment by garry-ut99** [comment]
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.

Curious, you are advanced enought to use uBO logger and put `code tags` in your title, how is that at the same time you failed to use "in:title" operator to find the already existing old issue, as it shows only 5 results: https://github.com/uBlockOrigin/uBlock-issues/issues?q=in%3Atitle+no-large-media, then realising that such issue already exists takes 1 min, or if you found it but still weren't sure whether it's a duplicate or not, given a fact how much similiar the both issues are, you could post a comment and ask in the old issue, or maybe you were convinced that they were not duplicates because one speaks about "video" and the other about "audio" , or maybe you lied us and didn't do any search despite ticking the checkbox, or maybe some other explanation, need to know the truth.

**Comment by gorhill** [comment]
> downloading hundreds of megabytes of data very quickly

Seems to be an exaggerated claim. The response headers are downloaded since they are needed for uBO to make a decision, but using Network pane in browser dev tools, I do not see _"hundreds of megabytes of data very quickly"_. After two minutes of broken playback, I see ~800KB.

**Comment by garry-ut99** [comment]
I think OP is right, while I do agree that Firefox network pane doesn't show much data downloaded, Windows Task manager actually does show constant internet download speed at almost 80 Mb/s which doesn't stop until a tab is closed.

**Comment by gorhill** [comment]
Right, my bad, `about:networking#sockets` does show a lot of data received.

**Comment by garry-ut99** [comment]
Occurs also on Firefox Mobile 124 and is even worse: drains almost 2x as much as on desktop: 144 Mb/s, this might quickly drain mobile battery and exhaust the limits of payed $ mobile internet packets, and what is even worse, it all happens invisibly in the background for a typical novice user.

**Comment by gorhill** [comment]
I will squeeze in a lightweight fix in the release candidate to address both the case here and the original issue at <https://github.com/uBlockOrigin/uBlock-issues/issues/1201>.

The intended behavior is for uBO to not block the media since the media itself is a top level document rather than a secondary resource.

There are two code paths to address:

First one is that the mime type for the media here is `application/ogg`, which uBO does not detect as a media type.

The other issue is probably Firefox-specific, is that when uBO starts to act on the document being loaded, the context is seen as `about:newtab`, which eventually become the hostname of the media URL. This prevents uBO from remembering the state of the `no-large-media-elements` switch.

The changes will address those two quirks.

**Comment by garry-ut99** [comment]
> First one is that the mime type for the media here is `application/ogg`, which uBO does not detect as a media type.

Maybe this could be fixed by the way, I mean it's not perfectly same, but  somehow close/similiar:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1984#issuecomment-1060633754

**Comment by garry-ut99** [comment]
I've checked and the bug in the both issues (`#1201` + `#3184`)  has been fixed, but only partially:

Scenario 1 where the bug is fixed:
**1]** Open a new tab
**2]** Paste the media link into the same tab

Scenario 2 where the bug still does occur:
**1]** Open a new tab
**2]** Visit any site in the same tab - for example `facebook.com`
**3]** Paste the media link in the same tab

A seen, the difference which still triggers the bug is the point **2]** (in Scenario 2): 
- to visit any site in the same tab before visiting the media link in the same tab - required only once, since then the tab is "compromised" and there is no need to repeat point **2]** anymore to trigger the bug, the bug will be tiggered always when pasting any media link in the compromised tab: regardless whether from `#1201` or from `#3184`, until a tab is closed

**Comment by gorhill** [comment]
A better fix would require more changes, I wanted to keep changes to a minimum to avoid delaying release candidate for to long.
