### ISSUE TITLE
uBlock Origin no works on search results in Opera 57

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#319]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Opera 57 added option for addons/extensions "`Allow access to search page results`".

![image](https://user-images.githubusercontent.com/35370833/49220612-f55f1400-f3d6-11e8-8a6c-7df5bf69ebcd.png) |
--- |

`chrome://startpage/extensions`
`chrome://startpage/extensions?id=kccohkcpppjjkkjppopfnflnebibpida`

### A specific URL where the issue occurs

* Google Search (Default)
   `https://www.google.*/search?client=opera&q=%s&sourceid=opera&ie={inputEncoding}&oe={outputEncoding}`

* DuckDuckGo
   `https://duckduckgo.com/?q=%s&t=opera`

* Bing
   `https://www.bing.com/search?q=%s&form=OPRTSD&pc=OPER`

---

* Other search engines
   `...`

### Steps to Reproduce

1. Install Opera 57
2. Install latest uBO for Opera
3. Try find someting in default search and try block someting or you should see ads

### Expected behavior:

auto check option "`Allow access to search page results`"

### Actual behavior:

unchecked option "`Allow access to search page results`"

### Your environment

* uBlock Origin version: `1.17.0`
* Browser Name and version:  `Opera 57.0.3098.76 (stable)`
* Operating System and version: `Windows 7 Pro x64`

**Comment by uBlock-user** [comment]
apparently new browser behaviour - https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/

**Comment by uBlock-user** [comment]
Looks like new permission setting in Opera specifically.

**Comment by krystian3w** [comment]
Yahoo and Wikipedia they do not match the permission scheme and start without the additional option selected for the addon. So I removed them from `specific URL` section.

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/

**Comment by uBlock-user** [comment]
This granularity option in Opera is same as **Allow access to file URLs** and **Allow in incognito** in Chromium and they both are required to enable manually once when you install the extension first time or in this case after a browser update to a version where this setting was first added. I doubt extension itself can turn this on by default.

**Comment by gorhill** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/

Nothing uBO can do.

**Comment by romanshein** [comment]
Can you add a note for Opera users at the main extention pop-up or within settings that they have to tick the relevant option themselves.
Personally I was very frustrated when Google Ads suddenly reappeared out of thin air. I was able to find this page, but 99% will just stay frustrated.

**Comment by krystian3w** [comment]
>  extention pop-up

Or in Opera Store description if pop-up is bad idea?
