### ISSUE TITLE
Support trusted-replace-xhr-response scriptlet of AdGuard

### ISSUE THREAD

**Issue by piquark6046** [uBlockOrigin/uBlock-issues#3193]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Please support `trusted-replace-xhr-response` scriptlet to resolve chzzk.naver.com anti-adblock issue (https://github.com/List-KR/List-KR/commit/2062fc3357077a33cb5a115205c55faa66c7de90).
https://github.com/AdguardTeam/FiltersRegistry/pull/923

### A specific URL where the issue occurs.

```yaml
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-replace-xhr-response
```

### Steps to Reproduce

None.

### Expected behavior

uBO supports the scriptlet.

### Actual behavior

uBO does not support the scriptlet.

### uBO version

1.57.0

### Browser name and version

Firefox 124.0.2

### Operating System and version

Ubuntu 23.10

**Comment by stephenhawk8054** [comment]
It does have?

https://github.com/gorhill/uBlock/blob/8dc0e885b5652bba2c7e183252f7f4c1bedea617/assets/resources/scriptlets.js#L4304-L4377

**Comment by piquark6046** [comment]
Thanks. Closing the issue.
But, I think that it should be documented.

**Comment by garry-ut99** [comment]
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue+sort%3Aupdated-desc) to avoid opening a duplicate issue.

How, a duplicate of your previous same request :
- https://github.com/uBlockOrigin/uBlock-issues/issues/2743

also in the old thread there is a commit saying that the scriptlet is implemented and also a `fixed` label is appended which means that you were effectively informed about the scriptlet (also via a github / email notification most likely), then it seems you forgot about it.
