### ISSUE TITLE
Kiwi browser

### ISSUE THREAD

**Issue by MusicaFM** [uBlockOrigin/uBlock-issues#3198]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

A veces se bloquea en Kiwi Browser y no me carga ninguna web se queda cargando, abro para configurar Ublock y de queda en blanco tengo que deshabilitar para poder entrar en páginas webs y si lo activo de nuevo puede que valla bien o no

### A specific URL where the issue occurs.

```yaml
None
```

### Steps to Reproduce

Se bloquea en Kiwi browser al inicia el navegador, la primera vez funciona vien, pero cargas de nuevo u otra web y se bloquea

### Expected behavior

Deberia ir como siempre

### Actual behavior

Se bloquea en Kiwi browser, las demás extensiones funcionan correctamente

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium Mobile: 124
filterset (summary):
 network: 334928
 cosmetic: 373266
 scriptlet: 56698
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80490-7589, 16h.18m
  adguard-spyware-url: 1492-107, 16h.17m
  adguard-spyware: 102336-32419, 16h.18m
  block-lan: 61-0, 5d.17h.20m
  curben-phishing: 14193-4, 3h.58m
  adguard-cookies: 29175-80, 16h.18m
  ublock-cookies-adguard: 1106-0, 5d.17h.20m
  fanboy-cookiemonster: 50759-3950, 5d.16h.33m
  ublock-cookies-easylist: 1106-1106, 5d.17h.20m
  adguard-social: 22753-874, 16h.18m
  fanboy-social: 15849-29, 5d.16h.33m
  fanboy-thirdparty_social: 68-0, 5d.16h.33m
  [44 lists not shown]: [too many]
 default:
  user-filters: 2-1, never
  ublock-filters: 37741-812, 13m Δ
  ublock-badware: 8341-15, 13m Δ
  ublock-privacy: 785-0, 13m Δ
  ublock-unbreak: 2245-5, 13m Δ
  ublock-quick-fixes: 224-0, 13m Δ
  adguard-mobile: 9234-171, 16h.16m
  easylist: 84380-1307, 13m Δ
  easyprivacy: 50455-1141, 13m Δ
  urlhaus-1: 8795-0, 13h.56m
  plowe-0: 3763-13, 5d.17h.21m
  spa-0: 4023-7, 13h.56m
  spa-1: 5447-187, 16h.17m
filterset (user): [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4628 ms
 maxAssetCacheWait: 1787 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gwarser** [comment]
Try reducing number of filters (subscribed lists) - it's possible your device does not have enough memory when uBO parses and compiles all lists. What device is this?

Kiwi is not supported https://github.com/uBlockOrigin/uBlock-issues/issues/2791#issuecomment-1699419516

**Comment by MusicaFM** [comment]
Xiaomi redmi note 11s

**Comment by stephenhawk8054** [comment]
You enabled all regional filter lists?

**Comment by MusicaFM** [comment]
Yes

**Comment by stephenhawk8054** [comment]
Why? How many times do you visit Vietnamese and Thailand sites?

**Comment by MusicaFM** [comment]
Never, but I activate it just in case

**Comment by stephenhawk8054** [comment]
Don't do that. Just enable the lists of the languages you usually visit. The more lists you enable, worse performance and potential breakages can occur without any benefits.

**Comment by garry-ut99** [comment]
To OP: check whether:
-- the issue occurs with default settings with default lists only 
--  occurs on Firefox Mobile

Al OP: compruebe si:
-- el problema se produce sólo con la configuración predeterminada con listas predeterminadas
-- ocurre en Firefox Mobile

<hr>

> On my 6GB phone, Nightly, uBO dev, 140k network + 180k cosmetic filters, WebExtension process can take 3GB as per profiling. 1.5GB with default settings.  With 330k network + 370k cosmetic, maybe some stuff in background, out of memory situation is possible.

A joke or what, the values (1.5GB and 3GB) you've provided are insane, maybe you've confused real memory usage with virtual memory: 
- https://github.com/uBlockOrigin/uBlock-issues/issues/994
- https://github.com/uBlockOrigin/uBlock-issues/issues/1532
- https://github.com/uBlockOrigin/uBlock-issues/issues/2401

I've checked on Firefox Nightly Mobile and Kiwi Browser: uninstalled Firefox Nightly Mobile, then installed it again, then installed uBO, then loaded 900k filters config, all while monitoring RAM usage, and RAM usage has incerased by only additional 300 MB for a while, then later has decreased much.

**Comment by garry-ut99** [comment]
These gigabytes in FF profiler are bogus / virtual, I get similiar result to yours in FF profiler, but Android built-in system RAM monitor + built-in app RAM monitor + also  2 different 3rd party system RAM monitor apps show only 300-400 MB real RAM usage incerase for a while when loading high number of filter lists.

**Comment by gwarser** [comment]
Good news then. I recall seeing such high numbers before on desktop, I will need to check if it was discussed, check my test method and try it again to make sure.

**Comment by gorhill** [comment]
> These gigabytes in FF profiler are bogus / virtual

On desktop, wasm causes increased virtual memory usage, maybe it's the same thing in android.

**Comment by gwarser** [comment]
Profiler has a "Native Allocations" feature, which should report more real data. But still only sampling. https://profiler.firefox.com/docs/#/./memory-allocations Sadly crashes for me on Linux and I cannot allocate enough memory to VM to not see swapping.

**Comment by garry-ut99** [comment]
With "Native Allocations" ticked, it freezes/crashes for me as well in native Windows, it seems it's unrelated neither to OS (whether Windows or Linux) nor to nativness (whether native OS or VM), it just crashes everywhere, it freezes/crashes whole browser to the point I'm unable to stop Profiler, I need to kill the browser.

**Comment by gwarser** [comment]
Most of the allocations are from `JSON.stringify` and `Array.prototype.join`. It seems to me that there are a lot of calls to these functions, so this can explain both, the memory usage - if GC is not catching up, and the profiler being wrong - by capturing more samples with allocation than with deallocation.

**Comment by garry-ut99** [comment]
Do any external RAM monitoring apps _outside browser_ confirm your _FF Profiler_ or _about:memory_ results like 1,5GB or 3GB, I tried several of them, including setting 100ms or even 50ms sampling interval, and none of them have confirmed values reported by FF.

**Comment by gorhill** [comment]
> Most of the allocations are from `JSON.stringify` and `Array.prototype.join`

This is from compiling filter lists, not unexpected. Lists are compiled once in a while.

**Comment by alexandreraufast** [comment]
I had same problem on latest Kiwi Browser. Uninstalling-reinstalling uBO extension did work.
I also had a lot of custom filters, copied from my computer.
