### ISSUE TITLE
Chromium browsers are not be able to add custom filter by a file from storage.

### ISSUE THREAD

**Issue by Iz-zzzzz** [uBlockOrigin/uBlock-issues#3199]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Chromium browsers are not be able to add custom filter by a file from storage. I "think" this issue has been occurred since ~~https://github.com/gorhill/uBlock/commit/086766a924~~ https://github.com/gorhill/uBlock/commit/2b16a10b82.

### A specific URL where the issue occurs.

```yaml
None
```

### Steps to Reproduce

1. Create new Chromium Browsers (Brave, Chrome, .etc) profile
2. Add uBO from Chrome Web Store
3. Allow file URIs access
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/0e19b146-cf3b-43be-b9ab-bdf5e77b31f9)
4. Go to "Filter lists"
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/8444fe70-4f4c-49a8-85af-9cc004d6f0a3)
5. Add my filter `file:///D:/AdBlock/My-Filter/FinaleFilter.txt`
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/57972212/dba29174-3113-4027-abf5-fb07a3bac2d3)
6. See nothing happens

### Expected behavior

Filter add to uBO as before (like https://github.com/uBlockOrigin/uBlock-issues/issues/3126, https://github.com/uBlockOrigin/uBlock-issues/issues/3125).

### Actual behavior

Nothing happen.

### uBO version

1.57.0 (Chrome Web Store)

### Browser name and version

Brave 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit), Google Chrome 123.0.6312.106 (Official Build) (64-bit)

### Operating System and version

Windows 11 Education

**Comment by gorhill** [comment]
Regression from <https://github.com/gorhill/uBlock/commit/2b16a10b82>.

**Comment by Iz-zzzzz** [comment]
Fixed Thank you 😊
