### ISSUE TITLE
Twitch URL change not detected

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#320]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On clips.twitch.tv pages, transitioning to a clip made by a different user causes a URL change including appending very noticable tracking tags. This is a "single page app" type of transition that uBO doesn't detect (or at least there's nothing in the logger to indicate uBO is aware of it).

### A specific URL where the issue occurs

`https://clips.twitch.tv/SpineyAgitatedFriesBIRB`

### Steps to Reproduce

1. Open logger then go to above URL and watch the brief clip
2. Click on another clip in the lists below it.[1]  (For example, I just clicked the one titled "Perfect Timing")
3. The URL will change to `https://clips.twitch.tv/CuteTriangularClipsdadM4xHeh?tt_medium=clips&tt_content=recommendation` (or similar for a different video)
4. No indication of the URL change in the logger.
5. Will see a repeat of steps 3&4 for ensuing clips.

[1] Step 3 can reproduced by any other video so long as it was clipped by a different user than SpineyAgitatedFriesBIRB.

### Your environment

* uBlock Origin 1.17.3rc5
* Firefox 60.3

**Comment by gorhill** [comment]
> No indication of the URL change in the logger

Because no document was loaded? It's possible to change the URL in the address bar without causing a document to be loaded -- so there is nothing to report in the logger: <https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_pushState()_method>.

**Comment by joey04** [comment]
Thanks for responding.

I made the report matter-of-fact, but the reason I reported is it raises questions I don't know enough to answer:

Given that Twitch is appending the tracking tags, is that a sneaky way for them to get around the extension API?

Is there anything uBO can do about it?

**Comment by gorhill** [comment]
Please investigate that there are network requests shown in the Network tab that are not shown in the logger -- now *that* would be an issue. You opened an issue here based on an assumption that there was a network request fired for the URL appearing in the address bar -- I see no such network request with the URL of the address bar in the Network pane of the browser dev tools.

**Comment by joey04** [comment]
Good suggestion about dev tools, I didn't think of that. (I rarely use them so tend to forget about them.)

I can confirm that uBO is indeed logging every non-blocked request the same as the browser console.

What's interesting is that there is a document request in the middle of the screenshots below, which uBO does log properly.

So I guess there's nothing else uBO can do.

<hr>

For completeness, here are the first 39 non-blocked requests from the moment I do Step 2 above. (I cleared the logger and browser console first to make it easier to see what was happening.)

![log](https://user-images.githubusercontent.com/14959062/49322470-ec0c9f00-f4dd-11e8-9c3d-4f492061d09c.png)

![bc](https://user-images.githubusercontent.com/14959062/49322471-ec0c9f00-f4dd-11e8-885d-ab7a4d414ae7.png)

**Comment by joey04** [comment]
That makes sense, must be an efficiency thing as part of the "single page app" way of doing things. (As you can tell, I'm not a web dev so I don't know the intricate details.)

Thanks, guys, for the helpful info and resolving this non-issue quickly.
