### ISSUE TITLE
Thunderbird 102.13.0 with uBO 1.57.0+

### ISSUE THREAD

**Issue by rcalixte** [uBlockOrigin/uBlock-issues#3200]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

After updating to 1.57.0 and then 1.57.2, the uBO icons turns yellow and seems to be in some kind of cycle. The same issue prevents extension options and feed message bodies from rendering (HTML web pages, not summaries). There is just a constant "Loading" message without the page loading. There are no errors or outputs I can see. Reverting to 1.56.0 fixes the issue. It is repeatable but I haven't had a chance to dig through the release notes to see what changed quite yet.

### A specific URL where the issue occurs.

```yaml
Any RSS account e.g. Slashdot's RSS feed - http://slashdot.org/rss/slashdot.rss
```

### Steps to Reproduce

* Install 1.57.0 or 1.57.2 from the Release assets.
* Try to open the extension options or any feed item with the web view.
* Thunderbird restarts are optional.

### Expected behavior

Extension options are accessible along with feed contents.

### Actual behavior

No content loads for feed items (other than the text summary) and the extension options are also inaccessible. The uBO icon in the toolbar also remains yellow. Duration has no impact on this.

### uBO version

1.57.x

### Browser name and version

Thunderbird 102.13.0 (Flatpak)

### Operating System and version

Ubuntu 22.04

**Comment by gorhill** [comment]
Maybe related to <https://github.com/gorhill/uBlock/commit/f9408415a57432b0efef9c3fb64c20b275704450>. If so, this is fixed in dev build.

**Comment by rcalixte** [comment]
I can test it if you'd like?
