### ISSUE TITLE
The link on the filter list update page does not work with Tap To Tab

### ISSUE THREAD

**Issue by PhoenixIndigo** [uBlockOrigin/uBlock-issues#3201]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The update filter lists link [uBlock Origin - Update lists](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=all) does not work with [Tap To Tab](https://addons.mozilla.org/firefox/addon/tap-to-tab/)

### A specific URL where the issue occurs.

```yaml
https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=all
```

### Steps to Reproduce

1. Install extension in Firefox [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) & [Tap To Tab](https://addons.mozilla.org/firefox/addon/tap-to-tab/)
2. Click [Click to update your filter lists](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=all#) on [uBlock Origin - Update lists](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=all)

### Expected behavior

Opening [uBlock₀ — Control Panel](moz-extension://f95a24bd-977d-4251-b70c-a0c18d4885ab/dashboard.html#3p-filters.html) with updating filter lists

### Actual behavior

Follow the link (#) without opening the uBlock control panel with update

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Firefox: 124
filterset (summary):
 network: 244256
 cosmetic: 292337
 scriptlet: 52153
 html: 2030
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 25433-20, 3m
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1715-24, 3m
  https://filters.adtidy.org/extension/ublock/filters/1.txt: 23084-128, 3m
  https://shorturl.at/cfqKV: 8-0, 3m
  adguard-generic: 80672-3936, 2m
  adguard-mobile: 9237-79, 2m
  adguard-spyware-url: 1492-119, 2m
  adguard-spyware: 104202-1683, 2m
  adguard-cookies: 29221-257, 2m
  ublock-cookies-adguard: 1071-12, 2m
  fanboy-cookiemonster: 50849-3963, 2m
  ublock-cookies-easylist: 1071-1071, 2m
  [11 lists not shown]: [too many]
 default:
  user-filters: 0-0, never
  ublock-filters: 37583-123, 2m
  ublock-badware: 8347-15, 3m Δ
  ublock-privacy: 782-11, 2m
  ublock-unbreak: 2298-8, 2m
  ublock-quick-fixes: 129-28, 2m
  easylist: 84642-1925, 3m Δ
  easyprivacy: 50470-32037, 3m Δ
  RUS-0: 39490-3345, now Δ
filterset (user): [empty]
trustedset:
 added: [array of 5 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 760 ms (selfie)
 maxAssetCacheWait: 364 ms
 cacheBackend: indexedDB
```
</details>

**Comment by PhoenixIndigo** [comment]
Adding to the blacklist has helped so far ublockorigin.github.io

**Comment by gwarser** [comment]
Tap To Tab is defusing the click event.

**Comment by gorhill** [comment]
That Tap to Tab extension is dispatching a synhtetic `click` event:

    pending = setTimeout(() => {
      pending = null;
      skipOver = n;
      n.dispatchEvent(new MouseEvent("click", props));
    }, delay);

uBO's handler for the `click` event bails out when the `event.isTrusted` is false, by design:

    document.addEventListener('click', ev => {
        if ( ev.button !== 0 || ev.isTrusted === false ) { return; }
        const target = ev.target.closest('a');
