### ISSUE TITLE
perf: (rc, stay behavior) uBO scriptlet infinitely spamming MutationObserver `attributes` events triggered by itself

### ISSUE THREAD

**Issue by seia-soto** [uBlockOrigin/uBlock-issues#3215]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In uBlock Origin scriptlets involving DOM attribute modifications (calling `DOMTokenList` or `Element.prototype.(set|remove)Attribute`) may cause an infinite loop issue when it's used with `MutationObserver`. In this case, I'm handling `remove-class` scriptlet with `stay` behavior.

This is happening because the attribute modification event in mutation observer does contain cases the actual value haven't changed. However, uBO scriptlet does call attribute modifier methods even there's no class name in the element. Thus the handle of the `MutationObserver` in the script is called again and the same process happens infinitely.

**Suggested solution**

I suggest adding a simple check to avoid calling attribute modification methods meaninglessly. We also need to check if a similar problem happens in other scriptlets involving attribute modification.

```js
    const rmclass = function() {
        timer = undefined;
        try {
            const nodes = document.querySelectorAll(selector);
            for ( const node of nodes ) {
                for ( const token of classTokens ) {
                    if (node.classList.contains(token)) { // Check if a node contains actual class name
                        node.classList.remove(...classTokens);

                        break;
                    }
                }
            }
        } catch(ex) {
        }
        if ( mustStay ) { return; }
        if ( document.readyState !== 'complete' ) { return; }
        observer.disconnect();
    };
```

Credits to @philipp-classen who found the point of performance issue is happening at `MutationObserver`.

refs https://github.com/ghostery/adblocker/pull/3913
refs https://github.com/ghostery/ghostery-extension/issues/757#issuecomment-2059003276

### A specific URL where the issue occurs.

```yaml
https://www.reddit.com/
```

### Steps to Reproduce

1. Enable the following filter in `My Filters` tab.

```adb
reddit.com##+js(remove-class, scroll-disabled, body, stay)
```

2. Open `reddit.com` and set breakpoint to attribute modification on `body` element.

In case of Chrome, you can do this by right clicking body element -> Break on -> attribute modifications.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/30369714/980be32e-fee0-4b42-8440-8340553e9cf5)

Otherwise, you may put a simple logger in the scriptlet content to see if it actually does infinite loop.

### Expected behavior

uBO does stop catching the classes in element if there's nothing to catch.

### Actual behavior

1. Once `MutationObserver` gets `MutationRecords`, it calls `rmclass` function.

https://github.com/gorhill/uBlock/blob/5de19ace916d940c19cfbdfd792e001f174b2085/assets/resources/scriptlets.js#L2287

```js
    const mutationHandler = mutations => {
        ...
        timer = self.requestIdleCallback(rmclass, { timeout: 67 });
    };
    const observer = new MutationObserver(mutationHandler);
```

2. In `rmclass` function, it calls `DOMTokenList.prototype.remove` function without checking explicitly.

https://github.com/gorhill/uBlock/blob/5de19ace916d940c19cfbdfd792e001f174b2085/assets/resources/scriptlets.js#L2265

```js
    const rmclass = function() {
        timer = undefined;
        try {
            const nodes = document.querySelectorAll(selector);
            for ( const node of nodes ) {
                node.classList.remove(...classTokens);
            }
        } catch(ex) {
        }
        if ( mustStay ) { return; }
        if ( document.readyState !== 'complete' ) { return; }
        observer.disconnect();
    };
```

However, the behavior argument orders the observer to `stay` on the page. In this case, the handler of the living `MutationObserver` is called again and the infinite process starts.

### uBO version

1.56.0

### Browser name and version

Version 118.0.5993.117 (Official Build, ungoogled-chromium) (arm64)

### Operating System and version

macOS arm 14.4.1 (23E224)

**Comment by gorhill** [comment]
Thanks for the report/investigation. I didn't expect the browser to generate mutation events when no actual change occurs.

By the way, with uBO we wouldn't use a filter such as:

    reddit.com##+js(remove-class, scroll-disabled, body, stay)

We would use:

    reddit.com##body.scroll-disabled:remove-class(scroll-disabled)

Which doesn't suffer the issue.

**Comment by seia-soto** [comment]
Thanks for fast response. I also agree that 'stay' behavior should not happen in common.

**Comment by u-RraaLL** [comment]
It starts [here](https://github.com/gorhill/uBlock/commit/91dfcbef2a9d1a6557b65eedec8b7f11e87adc8e#diff-30b28769623e5478a0f68519eda037164484cfb444cb5a8e48518fa7bb32e658R2253)?

**Comment by gorhill** [comment]
The classes are removed [all at once](https://github.com/gorhill/uBlock/commit/91dfcbef2a9d1a6557b65eedec8b7f11e87adc8e#diff-30b28769623e5478a0f68519eda037164484cfb444cb5a8e48518fa7bb32e658R2279) for `rc` since there is an API to do this.
