### ISSUE TITLE
Integrate old ublock for sse version browser

### ISSUE THREAD

**Issue by Feodor2** [uBlockOrigin/uBlock-issues#3218]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This is not a bug.
I would like to integrate the old version of the ublock (1.16.20) to my browser sse version
https://github.com/Feodor2/Mypal68/
I can do it myself, i ask only how to do it right, for example may i keep the name or must change it. Is it something else to do what i do not know.

### A specific URL where the issue occurs.

```yaml
http://gegsgsegeg.com
```

### Steps to Reproduce

skip wegsaegsegase

### Expected behavior

skip gsegsgseg

### Actual behavior

skip  segsegsge

### uBO version

111111

### Browser name and version

mypal11111

### Operating System and version

windows111

**Comment by gorhill** [comment]
> may i keep the name or must change it

I have no opinion, do as you wish.

**Comment by garry-ut99** [comment]
By the way, also 2 related privacy stuff threads:
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2581
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2650

( Also interesting for uBO community:
`https://github.com/Feodor2/Mypal/issues/3` )
