### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by axolotl2836** [uBlockOrigin/uBlock-issues#3219]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I cant use control (')

### A specific URL where the issue occurs.

```yaml
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html
```

### Steps to Reproduce

what

### Expected behavior

that it would work

### Actual behavior

it didnt work

### Configuration

<details>

```yaml
uBlock Origin: 1.57.0
Chromium: 123
filterset (summary):
 network: 133871
 cosmetic: 46190
 scriptlet: 20509
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 37562-302, 6m
  ublock-badware: 8298-0, 6m
  ublock-privacy: 832-0, 6m
  ublock-unbreak: 2252-2, 6m
  ublock-quick-fixes: 324-1, 6m
  easylist: 86089-554, 6m
  easyprivacy: 50791-810, 6m
  urlhaus-1: 12505-0, 6m
  plowe-0: 3735-0, 6m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 4052 ms
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
> I cant use control (')

What does that mean?
