### ISSUE TITLE
Enhancing uBlock Origin's Picker Mode

### ISSUE THREAD

**Issue by shavitshelli** [uBlockOrigin/uBlock-issues#3224]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

My name is shavit, and I'm currently a final-year computer science student, along with two of my peers. As part of our degree program, we're engaged in a project to enhance existing open-source software.

Our focus lies on improving the Picker Mode by introducing the following features:

-Hovering Over Items in "My Filters" Tab: We propose implementing a feature where hovering over an item in the "My Filters" tab displays a screenshot of the removed item. This addition aims to offer users valuable visual context, enhancing their understanding of the content being blocked and fostering greater transparency in their browsing experience.

-Toggle Buttons for "My Filters" Tab: Additionally, we suggest implementing toggle buttons for each item in the "My Filters" tab. This addition will grant users more control over their browsing preferences.

We would love to hear your thoughts on these proposed enhancements and if you would be able to provide any assistance in implementing them.

### A specific URL where the issue occurs.

```yaml
chrome-extension://bkfhipcppphlkddamjbpcjckebcohhbp/dashboard.html#1p-filters.html
```

### Steps to Reproduce

feature proposition 

### Expected behavior

feature proposition 

### Actual behavior

feature proposition 

### Configuration

feature proposition

**Comment by garry-ut99** [comment]
Your requests are kinda confusing as it's unclear whether you mean your requests to be implemented in [Element Picker](https://github.com/gorhill/uBlock/wiki/Element-picker) or in [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) pane, as you are speaking about both.

**1**

> -Toggle Buttons for "My Filters" Tab: Additionally, we suggest implementing toggle buttons for each item in the "My Filters" tab. This addition will grant users more control over their browsing preferences.

If you mean in [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) pane then it's a duplicate request of :
- https://github.com/gorhill/uBlock/issues/972

Currently it's possible to comment/uncomment particular filters by pressing <kbd>Tab</kbd> like mentioned in:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1279

**2**

> -Hovering Over Items in "My Filters" Tab: We propose implementing a feature where hovering over an item in the "My Filters" tab displays a screenshot of the removed item. This addition aims to offer users valuable visual context, enhancing their understanding of the content being blocked and fostering greater transparency in their browsing experience.

I see it more applicable in [Element Picker](https://github.com/gorhill/uBlock/wiki/Element-picker) than in [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters), still it's unclear which one you mean.

**Comment by smordarski** [comment]
Not to be rude but this looks like this issue was created by AI generated text. I could be wrong. I agree with @garry-ut99 that it is unclear what you want to be added.

**Comment by shavitshelli** [comment]
Sorry for any confusion caused. English is not my native language, and I'm indeed using AI to articulate myself better.

1) Regarding the toggle buttons, we tried to come up with a solution that would be more intuitive for the average end user. Even for us as CS students, it was not intuitive to understand how to enable and disable a certain filter in the "My filters" tab. We approached this by thinking as new end users who may not understand how uBlock Origin works. Therefore, instead of relying on the tab, we aim to implement the same functionality with toggle buttons or something that will be more user-friendly than pressing the tab.

2) Concerning the element picker, the functionality we aim to achieve is as follows: Whenever you remove an element with the element picker, a small screenshot of the element will be saved somehow. This picture will be used in the "My filters" tab. For instance, if this is the YouTube logo in my filters: "www.youtube.com###logo-icon > .yt-icon.style-scope > .yt-spec-icon-shape > div", whenever I hover over this text, the screenshot will be presented. 
The rationale behind this is that:
 Two weeks ago, I decided to remove a lot of things from the YouTube page, so I have a lot of filters in the "My filters" tab. Now, I want to specifically return the YouTube logo. Currently, it's pretty hard to tell which one is the YouTube logo. The hover functionality is a possible solution for this.

I want to mention that we are not asking you to implement all of this. Our job as part of our final project is to contribute to your open source, and we would like to get your assistance if possible in certain areas. I hope I made things easier to understand now.

**Comment by uBlock-user** [comment]
> Two weeks ago, I decided to remove a lot of things from the YouTube page, so I have a lot of filters in the "My filters" tab. Now, I want to specifically return the YouTube logo. Currently, it's pretty hard to tell which one is the YouTube logo. The hover functionality is a possible solution for this.

Add a comment before the filter when you create the filter to remove it, like below.
![Capture](https://github.com/uBlockOrigin/uBlock-issues/assets/21290713/54eff7b8-1a8a-42b1-8a6a-756b7db2f20f)

**Comment by garry-ut99** [comment]
> 1. 
Documentation does explain how to enable/disable filters, like mentioned: https://github.com/uBlockOrigin/uBlock-issues/issues/1279#issuecomment-703693710, unless your point is that enabling/disabling filters should be easy to know even without reading documentation.

> 2.
I was going to say the same what has been mentioned above, before that comment even has appeared: that you can describe your filters by comments, for. ex. : `! logo`.

Having visual preview would be comfortable, but I'm not sure if it's so much needed, also it depends how much average screenshoot of DOM element would take place on disk, let's say 100KB, means 100 cosmetic filters = 10MB, 1000 cosmetic filters = 100 MB, there would have to be some limit of max number or size of screenshoots kept, you will need to investigate the matter to make sure how much space is available for extensions:
- https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

**Comment by gothic-bum** [comment]
> I've rethinked it and I think that saving screenshoots is wrong way to solve the issue, the proper way would be to add to Element Picker a "Reverse load" button which would load the current domain related cosmetic filters from My filters" back into "Cosmetic filters" suggestion area, so that they can be previewed in Picker and reconsidered just like when an user usually creates filters.
  
I agree that saving screenshots is not a proper solution, from both an implementation and a privacy perspective. 
  
Why not use the [DOM inspector](https://github.com/gorhill/uBlock/wiki/DOM-inspector) to visually determine which cosmetic filter(s) are being applied?

**Comment by gorhill** [comment]
> We would love to hear your thoughts on these proposed enhancements and if you would be able to provide any assistance in implementing them.

I don't want to spend more time than I already do on this project, and my priority as of now is to provide what filter list authors need and to fix reported bugs.

If you feel that what you proposed is very important for end users, best is that you fork the project and implement your ideas. Once you have a full implementation of these ideas, than you can see how well they work and how well they are received by users, and accordingly I may reassess whether this should be part of uBO if ever you decide to a pull request here.

I will close this issue since I essentially decline to work on this in any capacity, but feel free to open a pull request in the future.
