### ISSUE TITLE
Github repository of lists should be added.

### ISSUE THREAD

**Issue by DogancanYr** [uBlockOrigin/uBlock-issues#3225]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

 ru ua uz kz: RU AdList , EasyList Italy ,es ar mx co: EasyList Spanish , eg sa ma dz: List AR , de ch at: EasyList Germany
Github links of the lists should be added to the extension.

### A specific URL where the issue occurs.

```yaml
..
```

### Steps to Reproduce

..

### Expected behavior

..

### Actual behavior

..

### uBO version

..

### Browser name and version

..

### Operating System and version

..

**Comment by gorhill** [comment]
There are already official link to the support page of those lists.

**Comment by garry-ut99** [comment]
Related thread, OP should study it first:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1846

**Comment by DogancanYr** [comment]
They may be official, but they are very difficult, easier to edit through Github .
