### ISSUE TITLE
(Fenix) (Minor visual bug) 'Page blocked' page remains after tapping 'Close this window"

### ISSUE THREAD

**Issue by opusforlife2** [uBlockOrigin/uBlock-issues#3232]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When it is the only tab open, closing the 'page blocked' tab causes the actual tab to be closed (the tab number goes from 1 to 0), but the visual contents remain stuck there until the user dismisses it by opening the tab list (maybe other actions work as well).

If any other tab is also open, the bug doesn't occur.

### A specific URL where the issue occurs.

```yaml
None.
```

### Steps to Reproduce

1. Block a page.
2. Open that page.
3. Tap on 'Close this window".

### Expected behavior

Should go back to Fenix home screen, like expected when last tab closed.

### Actual behavior

Visual contents remain there until manual step taken.

### uBO version

1.57.2

### Browser name and version

Fenix 124.2.0

### Operating System and version

Android 14

**Comment by gwarser** [comment]
Firefox bug.
