### ISSUE TITLE
requestIdleCallback not supported on ios

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#3237]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Not a uBO specific issue, but reaching out;

Filters including remove-class, href-sanitizer,remove-attr are ignored due to the lack of requestIdleCallback .  See: https://caniuse.com/requestidlecallback

### A specific URL where the issue occurs.

```yaml
No url attached
```

### Steps to Reproduce

- Any filters using remove-class.js, remove-attr.js, remove-class.js being ignored due to lack of requestIdleCallback (see: https://caniuse.com/requestidlecallback )
- Just a general query if there is work around, not a specific uBO issue. 

### Expected behavior

If its possible to timeout or fallback if requestIdleCallback isn't used/detected/available.

### Actual behavior

the 3 scriptlets are being ignored on ios currently.

### uBO version

Brave IOS

### Browser name and version

Brave IOS

### Operating System and version

IOS

**Comment by uBlock-user** [comment]
[requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) can be used in its place.

**Comment by uBlock-user** [comment]
`remove-attr` and `remove-class` scriptlets are deprecated as per wiki, already, so you should start using procedural operator in its place - https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#subjectremove-attrarg-subjectremove-classarg

**Comment by ryanbr** [comment]
Okay, stand corrected. was under the impression it was MV3

**Comment by krystian3w** [comment]
Looks duplicate of #3105
