### ISSUE TITLE
A breakage occurs at chzzk.naver.com if nano-stb scriptlet is appiled

### ISSUE THREAD

**Issue by piquark6046** [uBlockOrigin/uBlock-issues#3243]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A breakage in the chatting element occurs [^1] if the following filter is applied [^2].
```adblock
 chzzk.naver.com##+js(nano-stb, noPingPong||(e.sendPing, *, 0.001)
```

[^1]: https://github.com/List-KR/List-KR/issues/928#issuecomment-2122457903
[^2]: https://github.com/List-KR/List-KR/issues/928#issuecomment-2123804360

 - https://github.com/List-KR/List-KR/issues/928
 - https://github.com/uBlockOrigin/uAssets/issues/23782

### A specific URL where the issue occurs.

```yaml
Play any live streaming at https://chzzk.naver.com.
```

### Steps to Reproduce

1. Apply the following filter.
    ```adblock
     chzzk.naver.com##+js(nano-stb, noPingPong||(e.sendPing, *, 0.001)
    ```
2. Visit https://chzzk.naver.com.
3. Click any live streaming.

Login an account may be required unless you can reproduce many times.

### Expected behavior

It works correctly with AdGuard Browser Extension or app even if the the following rule is applied:
```adblock
chzzk.naver.com#%#//scriptlet('adjust-setTimeout', 'noPingPong||(e.sendPing', '', '0.001')
```

### Actual behavior

A breakage occurs if you add the filter into uBlock Origin.

### uBO version

1.57.0

### Browser name and version

Chromium 125.0.6422.60 (Official Build) snap (64-bit) 

### Operating System and version

Ubuntu 24.04 LTS

**Comment by stephenhawk8054** [comment]
I don't really understand what happened in the video recording in the comment. I clicked on a video but I don't know where the breakage occurs?

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/66517106/2d8b1ad3-8e00-4c23-983c-afae2b56f7c4)

**Comment by piquark6046** [comment]
The breakage often occurred on my side. By the way, it seems that it is literally caused by the filter. Not uBO.

Closing.

**Comment by gorhill** [comment]
> By the way, it seems that it is literally caused by the filter. Not uBO.

Do you mean the same filter also causes breakage with AdGuard?

**Comment by piquark6046** [comment]
> Do you mean the same filter also causes breakage with AdGuard?

Maybe. However, I cannot verify that.
