### ISSUE TITLE
Suggestion - Better backup button

### ISSUE THREAD

**Issue by OshidaBCF** [uBlockOrigin/uBlock-issues#3245]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I pressed a wrong button somewhere in the chrome extension menus and it redownloaded the app, wiping all my custom filters.

I though that my settings and ect were saved as i tuned on the backup feature

Turns out i didn't understood that i was supposed to click the button to actually make a backup

So i lost all my filters but it's no big deal, albeit slightly annoying

So i suggest making buttons that say "save backup to cloud" and "import backup from cloud" for people that have some brain issues like me

### A specific URL where the issue occurs.

```yaml
Feature Suggestion
```

### Steps to Reproduce

Feature Suggestion

### Expected behavior

Feature Suggestion

### Actual behavior

Feature Suggestion

### uBO version

1.57.0

### Browser name and version

Chrome 124.0.6367.208

### Operating System and version

Windows 10 22H2

**Comment by krystian3w** [comment]
There is already a mechanism for saving to the cloud:

https://github.com/gorhill/uBlock/wiki/Cloud-storage

But I don't guarantee recover settings after reinstall addon by misclick in Chromium interface.

At daily usage I prefer backup to file:

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section

**Comment by OshidaBCF** [comment]
I know there is a cloud system, what i'm suggesting is making new buttons for it, because i only understood yesterday that you had to press a button to backup

**Comment by gorhill** [comment]
What's not clear?

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/9372dd7c-2702-4456-9a2d-5511cc6cd439)

**Comment by garry-ut99** [comment]
As OP mentioned word "cloud" it seems OP is speaking about "Export/import to/from cloud storage" buttons and not about "Back up/restore to/from file" buttons, the former don't have names, only cloud icons: 
https://github.com/gorhill/uBlock/wiki/Cloud-storage

![img](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/91f451bc-3bbb-4b6f-8409-5ce020f4f93a)

**Comment by OshidaBCF** [comment]
As Garry said

I only understood yesterday that i had to click on the cloud icon to actually make a backup, i just though it was an icon to show the current "status" of my cloud backup, not that it was interactible

**Comment by garry-ut99** [comment]
Documentation clearly says:
> https://github.com/gorhill/uBlock/wiki/Cloud-storage:
>
> Your uBO settings are precious. To prevent any automated browser syncing task from overwriting your local or cloud data, **you must expressly ask uBO to export to/import from cloud storage.**
> 
> uBO's implemented sync feature is a global clipboard where settings are copied and pasted. Only you decide when to export/import.

But it seems some users might not read the documentation or might do read but still be confused and misled by cloud export/import buttons being not text-labeled and looking like auto-sync, hence it seems what OP wants is cloud export/import buttons to be more self-explanatory that they need to be pressed.

**Comment by gorhill** [comment]
> that you had to press a button to backup

Cloud storage is not meant for backup, you would still have lost your settings, unless your browser was logged in into Google account and you have other installations of uBO on other devices linked to the same account.

**Comment by garry-ut99** [comment]
> Cloud storage is not meant for backup, you would still have lost your settings, unless your browser was logged in into Google account and you had other installations of uBO on other devices linked to the same account.

Also mentioned in the documentation as well:

> https://github.com/gorhill/uBlock/wiki/Cloud-storage :
>
> If you do not have a syncing account with your browser vendor, I have observed that the cloud storage feature can still be used as a local clipboard to save a pane's settings. It might be convenient sometimes, but please do not use cloud storage to replace uBO's [backup feature](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section). Regularly backing up your settings is recommended, especially for those having extensive custom static filters, custom rules, or trusted site directives.

Either OP didn't read the documentation at all or did read but still was confused, I'm not sure which one was the reason, but statistically it's usually the former.

**Comment by OshidaBCF** [comment]
i did read part of it explaining that there was a cloud option so i turned it on a few month ago after i lost all my filter (again)

i'm always logged in my google account so i should be able to download the backup even if i uninstall or "repair" the extension no ?

Sorry if it's just because of my stupidity that this happen
