### ISSUE TITLE
Not saving settings

### ISSUE THREAD

**Issue by ZIMOTEK** [uBlockOrigin/uBlock-issues#3251]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Customized settings for websites are not being saved. Sites revert to default uBlock settings when site is reopened.

### A specific URL where the issue occurs.

```yaml
https://www.theepochtimes.com/
```

### Steps to Reproduce

Make custom settings for site.
Open site the next day.
Custom setting are gone.

### Expected behavior

Settings to be saved

### Actual behavior

Customized settings for websites are not being saved

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 123
filterset (summary):
 network: 213687
 cosmetic: 9
 scriptlet: 47492
 html: 1818
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81749-45397, 3d.18h.44m
  adguard-mobile: 9386-7830, 3d.18h.44m
  adguard-spyware-url: 1514-123, 3d.18h.44m
  adguard-spyware: 80726-1622, 3d.18h.44m
  block-lan: 66-0, 6d.21h.18m
  curben-phishing: 544-0, 12h.47m
  adguard-social: 22958-22323, 3d.18h.44m
  adguard-cookies: 29709-26412, 3d.18h.44m
  ublock-cookies-adguard: 1153-196, 2d.17h.40m
  adguard-popup-overlays: 27445-22940, 3d.18h.44m
  adguard-mobile-app-banners: 5226-4974, 3d.18h.45m
  adguard-other-annoyances: 14264-11723, 3d.18h.44m
  [3 lists not shown]: [too many]
 default:
  user-filters: 10-0, never
  ublock-filters: 38424-10796, 2h.46m Δ
  ublock-badware: 8835-680, 2h.46m Δ
  ublock-privacy: 920-13, 2h.46m Δ
  ublock-unbreak: 2343-332, 2h.46m Δ
  ublock-quick-fixes: 166-72, 2h.46m Δ
  easylist: 87310-35462, 2h.46m Δ
  easyprivacy: 50971-31145, 2h.46m Δ
  urlhaus-1: 12865-1, 17h.47m
  plowe-0: 3726-1316, 2d.20h.40m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 10 redacted]
switchRuleset:
 added: [array of 8 redacted]
hostRuleset:
 added: [array of 13 redacted]
userSettings:
 advancedUserEnabled: true
 ignoreGenericCosmeticFilters: true
 parseAllABPHideFilters: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 10799 ms
 maxAssetCacheWait: 360 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
> Make custom settings for site

What do you call "custom settings"?

**Comment by ZIMOTEK** [comment]
Custom settings...

[image: uBlock Custom Settings.jpg]

**Comment by iam-py-test** [comment]
Your image did not upload.
You need to upload it via GitHub; it will not work if you reply to the email.
Thanks

**Comment by gwarser** [comment]
Click the padlock button? https://github.com/gorhill/uBlock/wiki/Per-site-switches

**Comment by dimyself** [comment]
> Click the padlock button? https://github.com/gorhill/uBlock/wiki/Per-site-switches

this doesn't work for me. i have ublock and site settings are not being saved when i click the lock.

i allow or disallow a script for a site, click the lock. Many sites are not saving correctly.

I have many sites i visit regularly, that are changed backed to default settings, even when i click the lock on them many times.

I'm using Brave on linux, ublock 1.69.0

**Comment by stephenhawk8054** [comment]
@dimyself Can you record videos how the issue looks like?
