### ISSUE TITLE
Make Firefox beta builds have version parity with stable

### ISSUE THREAD

**Issue by pointydev** [uBlockOrigin/uBlock-issues#3254]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Currently (as far as I can tell), the Firefox beta builds [only update to the next beta version available](https://github.com/gorhill/uBlock/commits/master/dist/firefox/updates.json), and never install stable versions. While I understand that the majority of the time, the last beta available before a stable release is usually the same, it would be nice to have version parity with stable so users can be assured they have the "latest" version installed.

### A specific URL where the issue occurs.

```yaml
N/A
```

### Steps to Reproduce

1) Install the uBO Firefox beta build from GitHub releases when a later stable version is available
2) Attempt to update the extension in about:addons

### Expected behavior

The extension updates to the next stable version while still being in the beta channel (even if the build is technically not the same).

### Actual behavior

No update occurs, meaning the installed version is technically behind the current stable release.

### uBO version

1.57.3rc1

### Browser name and version

Firefox Dev 127.0b3

### Operating System and version

Fedora Linux 40

**Comment by gorhill** [comment]
There is essentially no difference [between 1.57.3rc1 and 1.58.0](https://github.com/gorhill/uBlock/compare/1.57.3rc1...1.58.0).

I will decline because what you ask is just a pointless burden on my side, and anyway what you ask is not possible, there is no way for uBO to go from stable release to beta release.
