### ISSUE TITLE
[Mobile Firefox] Can’t side scroll the text editor of “my filter”

### ISSUE THREAD

**Issue by Palloxin** [uBlockOrigin/uBlock-issues#3255]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Impossible to scroll horizontally the text editor.

### A specific URL where the issue occurs.

```yaml
no url, it is the settings of the plugin
```

### Steps to Reproduce

https://github.com/uBlockOrigin/uBlock-issues/assets/75091899/ab1e41df-0a7a-4dd4-bb71-1e002dac9af7

No idea. Maybe it is the device and OS

### Expected behavior

I can side scroll.

### Actual behavior

I cant side scroll the text editor of “my filters” section of settings

### uBO version

1.58

### Browser name and version

Firefox Mobile 125.3

### Operating System and version

A8 miui 8. Huawei p8 lite 2017.

**Comment by gorhill** [comment]
There is no horizontal scrolling because the lines are wrapped, there is no content to scroll to on the right.
