### ISSUE TITLE
A low-generic cosmetic filter is not applied

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#3257]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`##.mailpoet_form_popup_overlay` in AdGuard – Popup Overlays doesn't work.

![reinforz](https://github.com/uBlockOrigin/uBlock-issues/assets/58900598/93daaacf-6aee-4f7c-a1c5-ab06ab66875f)

### A specific URL where the issue occurs.

```yaml
https://reinforz.co.jp/bizmedia/41631/
```

### Steps to Reproduce

1. Enable AdGuard – Popup Overlays and check it includes
```
##.mailpoet_form_popup_overlay
##.mailpoet_form
```

2. Visit the page and scroll down, see only `##.mailpoet_form` is applied.

### Expected behavior

Both rules should be applied

### Actual behavior

Not 

### uBO version

1.58.0

### Browser name and version

Chrome 125.0.6422.112/Firefox 126.0

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> It was reported 1 year ago

That was a different cause even though the symptom was similar.

**Comment by gorhill** [comment]
(Never mind, answered too fast.)
