### ISSUE TITLE
3rd-gen HNTrie

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#326]
A placeholder reference issue to document the code change related to 3rd-generation HNTrie -- will flesh out as time allow.

The main goal of 3rd-generation HNTrie is to be usable as a replacement of `Set()` for _large_ collection of hostnames -- the 1st- and 2nd-gen versions of HNTrie were not designed to replace the use of `Set()` in [`FilterHostnameDict`](https://github.com/gorhill/uBlock/blob/c3b0fd31f64bd7ffecdd282fb1208fe07aac3eb0/src/js/static-net-filtering.js#L1063).

Pure-hostname filters -- stored in `FilterHostnameDict` -- are the most common static network filters. For instance, all filters in a hosts file are pure hostname ones. With default filter lists, there are many instances of `FilterHostnameDict`, with the largest holding over 34,000 distinct hostnames.

**Comment by gorhill** [comment]
New benchmark page for the 3rd-gen hntrie which is suitable to be used for large set of hostnames -- thus can be used in place of a `Set()`: <https://raw.githack.com/gorhill/uBlock/master/docs/tests/hnbigset-benchmark.html>.

Transcribing results from my side, the dictionary creation benchmark:

    Create dictionaries
    
    Firefox 65.0 on Linux 64-bit:
      -                         Set-based x 209 ops/sec ±5.17% (57 runs sampled)
      -           Trie-based JS (3rd-gen) x 32.71 ops/sec ±0.46% (44 runs sampled)
      -         Trie-based WASM (3rd-gen) x 40.64 ops/sec ±0.71% (43 runs sampled)
      - Trie-based unserialized (3rd-gen) x 1,955 ops/sec ±0.24% (66 runs sampled)
    
    Chrome 70.0.3538.77 on Ubuntu Chromium 64-bit.
      -                         Set-based x 187 ops/sec ±3.35% (56 runs sampled)
      -           Trie-based JS (3rd-gen) x 37.14 ops/sec ±0.69% (49 runs sampled)
      -         Trie-based WASM (3rd-gen) x 42.01 ops/sec ±0.55% (45 runs sampled)
      - Trie-based unserialized (3rd-gen) x 2,320 ops/sec ±0.73% (16 runs sampled)
    
    Firefox Mobile 65.0 on Mobile (Android 8.0.0):
      -                         Set-based x 27.61 ops/sec ±13.22% (30 runs sampled)
      -           Trie-based JS (3rd-gen) x 11.87 ops/sec ±1.16% (30 runs sampled)
      -         Trie-based WASM (3rd-gen) x 13.03 ops/sec ±0.38% (32 runs sampled)
      - Trie-based unserialized (3rd-gen) x 1,425 ops/sec ±2.50% (50 runs sampled)

Reminder: creation occurs at filter list load time, thus a one-time sort of event. Look-up operations (below) occur multiple time for every single network request being inspected.

Regarding "Trie-based unserialized": it is meant to be used in the selfie-loading code, which will be a big improvement compared to the current use of a `Set()` object to hold all the hostnames.    

The "look-up" benchmark:

    Test 100 needles against 8 dictionaries with size between 2 and 45752 hostnames
    
    Firefox 65.0 on Linux 64-bit:
     -                     Set-based x 3,468 ops/sec ±1.57% (61 runs sampled)
     -       Trie-based JS (3rd-gen) x 8,709 ops/sec ±1.06% (64 runs sampled)
     -     Trie-based WASM (3rd-gen) x 11,929 ops/sec ±1.10% (64 runs sampled)
    
    Chrome 70.0.3538.77 on Ubuntu Chromium 64-bit.
      -                     Set-based x 6,972 ops/sec ±1.83% (63 runs sampled)
      -       Trie-based JS (3rd-gen) x 8,829 ops/sec ±2.87% (55 runs sampled)
      -     Trie-based WASM (3rd-gen) x 10,899 ops/sec ±1.60% (65 runs sampled)
    
    Firefox Mobile 65.0 on Mobile (Android 8.0.0):
      -                     Set-based x 1,122 ops/sec ±19.63% (31 runs sampled)
      -       Trie-based JS (3rd-gen) x 3,581 ops/sec ±0.42% (54 runs sampled)
      -     Trie-based WASM (3rd-gen) x 4,446 ops/sec ±0.45% (54 runs sampled)

I expect memory usage benefits as well, I will look into this below as time allow.

**Comment by joey04** [comment]
https://raw.githack.com/gorhill/uBlock/master/docs/tests/hnbigset-benchmark.html

```
Benchmarking, the higher ops/sec the better.
Firefox 60.0 on Windows 8.1 64-bit.

Test 100 needles against 8 dictionaries with size between 2 and 45752 hostnames
  -                     Set-based x 2,766 ops/sec ±2.03% (62 runs sampled)
  -       Trie-based JS (3rd-gen) x 7,721 ops/sec ±0.63% (65 runs sampled)
  -     Trie-based WASM (3rd-gen) x 10,261 ops/sec ±2.14% (56 runs sampled)
Done.
```

<hr>

https://raw.githack.com/gorhill/uBlock/master/docs/tests/hnset-benchmark.html

```
Benchmarking, the higher ops/sec the better.
Firefox 60.0 on Windows 8.1 64-bit.

Test 100 needles against 16 dictionaries of hostnames
  -                 Set-based x 1,419 ops/sec ±1.91% (61 runs sampled)
  -               Regex-based x 3,252 ops/sec ±0.53% (64 runs sampled)
  -      Trie-based (1st-gen) x 7,926 ops/sec ±0.83% (67 runs sampled)
  -   Trie-based JS (2nd-gen) x 6,081 ops/sec ±0.51% (66 runs sampled)
  - Trie-based WASM (2nd-gen) x 6,649 ops/sec ±0.83% (64 runs sampled)
  -   Trie-based JS (3rd-gen) x 5,621 ops/sec ±0.21% (67 runs sampled)
  - Trie-based WASM (3rd-gen) x 6,130 ops/sec ±0.15% (35 runs sampled)
Done.
```

<hr>

Interesting that the original 1st-gen hntrie performed best in the second test. Since the first test has the same proportions, it may be the best there too.

**Comment by joey04** [comment]
Ran it several more times and got quite a variance of results. In one run 3rd-gen Wasm narrowly won. Then 2nd-gen Wasm narrowly won. Then 1st-gen won again with similar numbers to the above results.

Seems like the only takeaway from it is that in all four runs the numbers are pretty closely clustered together.

**Comment by gwarser** [comment]
![screenshot_20181205-022709](https://user-images.githubusercontent.com/886325/49511555-c55ab980-f88b-11e8-8502-b6de2679713d.png)
![screenshot_20181205-022804](https://user-images.githubusercontent.com/886325/49511556-c5f35000-f88b-11e8-9734-d6433e2b5143.png)
![screenshot_20181205-023211](https://user-images.githubusercontent.com/886325/49511557-c5f35000-f88b-11e8-81be-25aca2514f9c.png)
![screenshot_20181205-023300](https://user-images.githubusercontent.com/886325/49511559-c5f35000-f88b-11e8-83d7-6fbfe014fc03.png)

**Comment by gorhill** [comment]
I would like to keep the comments section for developer notes focused on noteworthy information. Unless the _relative_ results in your benchmarks differ significantly from my posted _relative_ results, there is no point posting your results, this will just end up drowning key information for whoever come here from the release notes to inquire about the details of the issue.

**Comment by joey04** [comment]
This looks to be a very good change, expanding the use of Hntrie from just `$domain=` fields to a large collection of pure hostname rules.

Are you also planning on using 3rd-gen tries for the many hostname rules of EasyList and EasyPrivacy? Almost all of them have some sort of field, including the large collection of `$third-party` hostnames.

(And sorry for my off-topic posts last night. I now realize that the other benchmark test is not that relevant here, since it's only for buckets up to 1000 hostnames.)

**Comment by gorhill** [comment]
Baseline memory usage improvements after launch (waited 3 minutes with browser idle) -- I used Chromium (linux 64-bit) as it makes it easy to measure.

No selfie, default filter lists -- uBO 1.17.4 vs. uBO 1.17.5b2 ("dev" in pic):
![No selfie](https://user-images.githubusercontent.com/585534/49686781-8b75f700-fac7-11e8-9f7b-96b3099a1207.png)

Selfie, default filter lists -- uBO 1.17.4 vs. uBO 1.17.5b2 ("dev" in pic):
![With selfie](https://user-images.githubusercontent.com/585534/49686783-9cbf0380-fac7-11e8-8696-285067f94708.png)

So roughly more than 4MB saved with the new FilterHostnameDict.

The peak memory at launch (transient) appears higher with the new HNTrie. However this settles quickly (within seconds) to the baseline memory usage seen in pics. uBO will remember the size of the HNTrie from the last session and will re-allocate that size for the next session, so as to avoid costly numerous re-allocation as the HNTrie buffer grows.

Expect larger memory saving with larger FilterHostnameDict instances, i.e. with more filter lists, especially the ones which are solely list of hostnames (like hosts files) -- but probably also higher transient peak usage at launch due to larger HNTrie buffer.

There is still place for performance improvement in 3rd-gen HNTrie (ordering of cells in the OR branch), but that is for the future.
