### ISSUE TITLE
Documentation: update website to mention the Chrome change

### ISSUE THREAD

**Issue by fulldecent** [uBlockOrigin/uBlock-issues#3264]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

# Background

Everybody knows that Google is an ad company and likes ads.

Everybody knows that Google makes Chrome.

Basically everybody knows that Chrome is [changing how extensions work this year](https://developer.chrome.com/docs/extensions/develop/migrate/known-issues).

And many [news sources](https://developer.chrome.com/docs/extensions/develop/migrate/known-issues) [have reported](https://www.msn.com/en-us/money/other/google-will-roll-out-chrome-s-new-extension-spec-next-week/ar-BB1nlPBP) [on the impact](https://arstechnica.com/gadgets/2024/05/google-starts-deprecating-older-more-capable-chrome-extensions-next-week/) of this change to ad blockers.

**OF COURSE we are already working on Manifest V3 changes, this issue is not about those changes**

# The issue

There is a public perception that "Google is breaking ad blocking".

There is a risk that new customers will come to our website and think "that's cool, it's a shame ad block doesn't work on Chome any more" and then they LEAVE OUR WEB PAGE.

We can directly address this by adding a "news" section to our home page and our extension description to say like:

> June 2024 update: uBlock Origin will continue to work with the Chrome Manifest V3 update. Click here to learn more.

And then it has a "[NEW]" badge in the front of it. And that badge is prominently colored.

### A specific URL where the issue occurs.

```yaml
https://ublockorigin.com/
```

### Steps to Reproduce

Visit.
Be scared.

### Expected behavior

Reassurance

### Actual behavior

Unclear feeling

### uBO version

All

### Browser name and version

Chrome, all

### Operating System and version

Mac, all

**Comment by stephenhawk8054** [comment]
uBO has no official websites except github projects. That website is developed by other users. Please contact them

> This website is maintained by [Uros Gazvoda](https://uros.com/), founder of [Futuristica](https://futuristica.com/), to help spread uBlock Origin - free, open-source ad blocker.
> If you're interested in contributing to this project, please [get in touch](https://ublockorigin.com/cdn-cgi/l/email-protection#cdaea2a3b9acaeb98db8afa1a2aea6a2bfa4aaa4a3e3aea2a0).

**Comment by fulldecent** [comment]
@ugzv please
