### ISSUE TITLE
Tell me...

### ISSUE THREAD

**Issue by AlexIs387** [uBlockOrigin/uBlock-issues#3266]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

when uBlock can really hide elements

### A specific URL where the issue occurs.

```yaml
anywebpage.com
```

### Steps to Reproduce

1. This
2. is
3. unnecessary
4. BTW

### Expected behavior

Also unnecessary, I though you could know which is the expected behavior reading the description

### Actual behavior

You can also know this too reading the description so this is a wasting time

### Configuration

<details>

```yaml
uBlock Origin: 1.57.2
Chromium: 125
filterset (summary):
 network: 207543
 cosmetic: 154961
 scriptlet: 47312
 html: 0
listset (total-discarded, last-updated):
 added:
  adguard-generic: 80939-670, 18h.32m
  adguard-mobile: 9427-58, 18h.32m
  adguard-spyware-url: 1522-120, 18h.32m
  adguard-spyware: 70354-1517, 18h.32m
  block-lan: 66-0, 25d.20h.45m
  curben-phishing: 571-1, 18h.32m
  adguard-popup-overlays: 27116-238, 18h.32m
  adguard-mobile-app-banners: 5271-21, 18h.32m
  adguard-other-annoyances: 14411-296, 18h.32m
  adguard-widgets: 2528-28, 18h.32m
  easylist-annoyances: 4651-334, 4d.18h.18m
  easylist-chat: 196-0, 7d.18h.17m
  [3 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 38345-3435, 11m Δ
  ublock-badware: 9189-1, 11m Δ
  ublock-privacy: 928-0, 11m Δ
  ublock-unbreak: 2334-0, 11m Δ
  ublock-quick-fixes: 87-0, 11m Δ
  easylist: 86589-2246, 11m Δ
  easyprivacy: 51012-28612, 11m Δ
  urlhaus-1: 16140-0, 18h.32m
  plowe-0: 3726-1325, 12d.20h.11m
  spa-0: 4064-48, 18h.33m
  spa-1: 5715-257, 18h.32m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 2 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 5579 ms (selfie)
 maxAssetCacheWait: 3971 ms
 cacheBackend: indexedDB
```
</details>

**Comment by krystian3w** [comment]
> when uBlock can really hide elements

I think ASAP.
