### ISSUE TITLE
Ublock Origin Error

### ISSUE THREAD

**Issue by ckddn5673** [uBlockOrigin/uBlock-issues#3270]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Ublock Origin seems to having malfunction and Youtube Ads easly break through it, please fix this issues.

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com/
```

### Steps to Reproduce

Fix the issue so Youtube Ads never appears even when Ublock is on.

### Expected behavior

Randomly occur when playing video.

### Actual behavior

About June 7th, this error appear on first time.

### Configuration

<details>
[image](https://github.com/uBlockOrigin/uBlock-issues/assets/172247942/3f3c0be7-50a7-446b-8cc9-e22d203c4e48)
```yaml
uBlock Origin: 1.58.0
Chromium: 124
filterset (summary):
 network: 138891
 cosmetic: 49856
 scriptlet: 21249
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38390-313, 2h.12m Δ
  ublock-badware: 9226-0, 2h.12m Δ
  ublock-privacy: 929-0, 2h.12m Δ
  ublock-unbreak: 2337-0, now
  ublock-quick-fixes: 141-0, now
  easylist: 86725-599, 2h.12m Δ
  easyprivacy: 51032-639, 2h.12m Δ
  urlhaus-1: 14440-0, 23h.53m
  plowe-0: 3555-0, 2d.11m
  KOR-1: 4980-56, 3h.21m
filterset (user): [empty]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 668 ms (selfie)
 maxAssetCacheWait: 130 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586
