### ISSUE TITLE
endcard problem

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [uBlockOrigin/uBlock-issues#3272]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Ublock wasnt working on youtube for a while and now it got fixed but endcards play too early at a length of what appears to be an ad. Your appears to have broken endcards based on this observation.

### A specific URL where the issue occurs.

```yaml
youtube.com
```

### Steps to Reproduce

watch video with encard

### Expected behavior

endcard play at correct time

### Actual behavior

n/a

### uBO version

n/a

### Browser name and version

n/a

### Operating System and version

n/a

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/20586
