### ISSUE TITLE
uBlock Origin automatically disabled at firefox start (firefox 127.0.1 64 bits)

### ISSUE THREAD

**Issue by candelrg** [uBlockOrigin/uBlock-issues#3276]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello.
I have a strange bug with uBlock Origin and Firefox 127.0.1 (64 bits).
I don't know whether it is a Firefox bug or a uBlock Origin bug.
Context :
I have the following extensions :
- Google Browse by Name search engine
- NoScript
- Video DownloadHelper

I used to have, on that firefox, the AdBlocker Ultimate extension, which I removed as I was not really satisfied.
Instead, I decided to install uBlock Origin (which does work really great when activated).

My firefox is configured to (privacy and security tab in firefox parameters)
- Delete cookies and data at firefox closing (option checked in "Cookies" section)
- Empty historic at firefox exit (all options checked in parameters popup)

Behavior :
When I close firefox, and open it again, uBlock Origin in disabled and firefox says a new extension was installed (this extension being uBlock Origin). So, I have to activate uBlock Origin and confirm its rights everytime I start firefox.

To be sure, I tried to remove all extensions, quit and restart firefox, and then install uBlock Origin. The bug remains the same.
This extension is the only one having such an issue.

Any idea about what could be the origin of that bug?
Thanks by advance for your help.

### A specific URL where the issue occurs.

```yaml
No URL: it happens at firefox exit and/or start
```

### Steps to Reproduce

1. Configure firefox to remove cookies and site data at exit, and to empty historic at exit (all options checked in parameters popup)
2. Install uBlock Origin extension and activate it.
3. Exit firefox
4. Start firefox: the extension is disabled and appears as if you just installed it (you have to enabled it and to confirm its authorizations)

### Expected behavior

When I quit and start firefox, I expect this extension to remain enabled and configured just like it was before I exited firefox.

### Actual behavior

The extension is disabled every time I start firefox 127.0.1

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 155357
 cosmetic: 53134
 scriptlet: 19962
 html: 1843
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 38757-112, 3m Δ
  ublock-badware: 9142-0, 3m Δ
  ublock-privacy: 924-2, 5m
  ublock-unbreak: 2403-2, 3m Δ
  ublock-quick-fixes: 84-3, 3m Δ
  easylist: 87025-179, 3m Δ
  easyprivacy: 51064-64, now Δ
  urlhaus-1: 14655-0, 5m
  plowe-0: 3552-988, 5m
  FRA-0: 24679-403, 5m
filterset (user): [empty]
trustedset:
 added: [array of 6 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 144 ms (selfie)
 maxAssetCacheWait: 50 ms
 cacheBackend: indexedDB
```
</details>

OS is Windows 10 pro.

**Comment by candelrg** [comment]
Just in case: my OS is Windows 10 pro.

**Comment by gwarser** [comment]
Isn't this a permanent private browsing mode?

**Comment by candelrg** [comment]
Not exactly, but close to.
However, this is not supposed to have any effect on uBlock Origin extension (and it does have no effect on other extensions).

**Comment by stephenhawk8054** [comment]
Does it happen in a new profile?

**Comment by candelrg** [comment]
I did not know how to check that,  so I had to search on the net (this is why I did not answer immediately), and it seems to be profile specific (thank you for your remark).
If I create a new profile, open firefox on that profile, then the extension seems to keep beeing activated after firefox ext and restart.
I'm not a firefox expert, so do you have any idea about what could result in such a behavior only for uBlock Origin extension (once again, other extensions don't seem to encounter this issue).

**Comment by gwarser** [comment]
I cannot reproduce with this config:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/d0ba3517-70a4-44bc-99ce-ace58aec35e9)

**Comment by garry-ut99** [comment]
> candelrg :
> ### I tried to reproduce the issue when...
>  * [x]  using a new, unmodified browser profile.

You didn't:

> stephenhawk8054: Does it happen in a new profile?
> candelrg :  it seems to be profile specific (thank you for your remark).

**Comment by candelrg** [comment]
Yes, sorry for that on.
As a non expert, I thought removing all extensions was equivalent but it definitly was not.
The remark of stephenhawk8054 made me aware of that.

For those who encounter the same issue as I did, here is the way to solve it:
**Step 1: Preparation**
- In your firefox parameters, keep note of your configuration (home page, proxy, privacy, etc.).
- In your firefox extensions, export your configuration when possible (for uBlock Origin, at least copy/paste your white list in a text file).
- Keep trace of your firefox themes (their name) if you installed some.
- Just in case, export your bookmarks and passwords (if you stored your passwords in firefox).

**Step 2: Repair profile**
- Go to "about:profiles".
- You should see 2 restart buttons. One to restart normally, the other one to restart with disabled modules. Click on the button to restart with disabled modules.
- This will launch the firefox repair tool. In that tool, say you want to repair and reset to default.
- Firefox will then start as a brand new one. Normally, it will automatically restore your bookmarks and passwords.

**Step 3: Restore configuration**
- Now, restore your parameters like they were configured in step 1.
- Install your extensions and restore their configuration.
- Install your desired theme.
- If, for some reason, firefox failed to restore your bookmarks or passwords, import them (from the files you created at the end of step 1).

Normally, this will fix the issue (it did for me).
