### ISSUE TITLE
distance calculation in cosmetic filter picker for touch gestures ignores Y translation

### ISSUE THREAD

**Issue by GrocerPublishAgent** [uBlockOrigin/uBlock-issues#3279]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I was looking at https://github.com/gorhill/uBlock/blob/master/src/js/epicker-ui.js#L388-L391
```javascript
       const distance = Math.sqrt(
           Math.pow(stopX - startX, 2),
           Math.pow(stopY - startY, 2)
       );
```
Should this distance calculation be instead?
```javascript
       const distance = Math.sqrt(
           Math.pow(stopX - startX, 2) + Math.pow(stopY - startY, 2)
       );
```

### A specific URL where the issue occurs.

```yaml
https://example.com
```

### Steps to Reproduce

1. Open the epicker-ui.js on github https://github.com/gorhill/uBlock/blob/master/src/js/epicker-ui.js#L388-L391
2. Read the distance calculation logic
3. Open devtools in a browser
3. Evaluate the following expression `console.log(Math.sqrt(Math.pow(3, 2), Math.pow(4,2)))`

### Expected behavior

I expect the distance to be 5

### Actual behavior

Console log shows 3

Math.sqrt ignores the second argument. The specification indicates that Math.sqrt only takes a single argument. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt

What this means for the picker's behavior is that touch moves in the Y direction are ignored when determining if it was a tap or not.

No one notices because the code only looks for touch movement in the X direction to detect left or right gestures.

### uBO version

1.58.0

### Browser name and version

Any

### Operating System and version

All

**Comment by gorhill** [comment]
> Should this distance calculation be instead?

Right, this is meant to be an addition, not sure what happened in my brain to use a comma instead.
