### ISSUE TITLE
wiki: `uritransform` filter wiki section (empty as of now) should feature a link to its "cousin" AdGuard filter `urltransform` documentation

### ISSUE THREAD

**Issue by kirisakow** [uBlockOrigin/uBlock-issues#3280]
### Description

`uritransform` filter [wiki section][1] is empty as of now (it reads "Documentation to be completed"), while it should feature at least a link to its "cousin" AdGuard filter `urltransform` [documentation][2].

[1]: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#uritransform
[2]: https://adguard.com/kb/general/ad-filtering/create-own-filters/#urltransform-modifier

**Comment by garry-ut99** [comment]
Updated: https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#uritransform

By the way, Wiki related issues should be opened in Discussions:
- https://github.com/uBlockOrigin/uBlock-issues/issues/3207#issuecomment-2054224112
