### ISSUE TITLE
Proceed button should not be allowed

### ISSUE THREAD

**Issue by AIBappa** [uBlockOrigin/uBlock-issues#3281]
![image](https://github.com/uBlockOrigin/uBOL-home/assets/70745640/03c658f3-53b5-4ae8-badd-ff482467d967)

**Issue:**
After user1 has added an URL to 'My Filters' those URLs are expected to be blocked in Firefox.
However, if another user (user2) comes along and tries that URL, a proceed button appears. This button is further highlighted in blue.
It is very easy for user2 to click on proceed and unblock that URL. The proceed button and the blue highlighting defeats the purpose of having a URL blocker and acts as a mere warning if the user cares to read about it.

**Potential solution(s):**
1) The proceed button should not be allowed if URL is in the'My Filters' list. If user needs to allow the URL, it should be removed from 'My Filters'.
2) The blue highlighting for the Proceed button should be atleast removed. If at all, that Proceed button is necessary, it should be made as inconspicous as possible, probably kept somewhere in the lower left corner in grey and that too another warning sign should appear, if proceed button is clicked.

**Potential Improvement(s)**
1) The 'My Filters' list can be password protected if at all solution 1 above is agreed upon.
2) It is not necessary to tell the user why the URL is blocked i.e. because it is in the 'My Filters' list. User1 knows it and user2 does not need to know it. Rather this information should be provided inside the uBlock Origin settings that URLs inside the 'My Filters' list will be blocked.

**Comment by gothic-bum** [comment]
> It is very easy for user2 to click on proceed and unblock that URL. The proceed button and the blue highlighting defeats the purpose of having a URL blocker and acts as a mere warning if the user cares to read about it.  
  
It is even easier for them to simply click the [big power button](https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#click-the-big-power-button) and disable uBO entirely on a site. Or they can simply disable the uBO extension in the browser. Either of these would allow the user to easily access the URL.  
  
If you are trying to use uBO for parental control, then that is not what it is designed for. You would be better served by using another product that is specifically designed for this purpose.

**Comment by gwarser** [comment]
Possible duplicates:

- https://github.com/uBlockOrigin/uBlock-issues/issues/232
- https://github.com/uBlockOrigin/uBlock-issues/issues/2576

For multi-user setup, use system accounts. You can make uBO setup bit more strict by administrative policies https://github.com/uBlockOrigin/uBlock-issues/wiki/Deploying-uBlock-Origin:-configuration

**Comment by garry-ut99** [comment]
> AIBappa : It is very easy for user2 to click on proceed and unblock that URL. The proceed button and the blue highlighting defeats the purpose of having a URL blocker and acts as a mere warning if the user cares to read about it.

I do realise that your request is related to "My filters", but since your statement sounds very generic, my reply will be as much generic too: as far I remember, since the beginning, purpose of strict blocking was to serve as a warning message, not as a parental control:

> - From https://github.com/gorhill/uBlock/wiki/Strict-blocking :
> **Important note**: Keep in mind that when the above warning occurs, it doesn't necessarily mean the site is harmful, it just means that there is a matching filter in the selected filter lists. You decide whether the site is safe, and whether disabling strict blocking permanently for the site is appropriate.

> - From https://github.com/gorhill/uBlock/issues/1581#issuecomment-213719081 :
> ghost : BTW: Strict blocking **is** the warning message.

<hr>

> AIBappa : The 'My Filters' list can be password protected if at all solution 1 above is agreed upon.

Like already mentioned in the earlier comment, as far I remember, uBO doesn't serve as a parental control extension, there are many declined requests:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1434
- https://github.com/uBlockOrigin/uBlock-issues/issues/232
- https://github.com/uBlockOrigin/uBlock-issues/issues/355
- https://github.com/gorhill/uBlock/issues/3576
