### ISSUE TITLE
No local icon in Firefox at about:addons after 170% zoom

### ISSUE THREAD

**Issue by leoheitmannruiz** [uBlockOrigin/uBlock-issues#3285]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

As in #939

128 is not specified at https://github.com/gorhill/uBlock/blob/master/platform/firefox/manifest.json#L97, so after a certain zoom level, there's no local icon Firefox can display and https://addons.mozilla.org/user-media/addon_icons/607/607454-128.png?modified=mcrushed is fetched.

I can image 128 being the final "missing" size. At least, it's the only one Firefox fetches on my 2022 MacBook Air.

Also, the image being fetched is not an SVG, which is kinda sad :(

### A specific URL where the issue occurs.

```yaml
about:addons
```

### Steps to Reproduce

1. Go to about:addons
2. Zoom in (a bunch, perhaps)
3. Open the uBO icon in new tab and see it's addons.mozilla.org

### Expected behavior

Have the icon be an SVG for all zoom levels and Firefox not connecting to addons.mozilla.org for the icon.

### Actual behavior

Icon is fetched from addons.mozilla.org.

### uBO version

1.58.0

### Browser name and version

LibreWolf (127.0.2-2)

### Operating System and version

macOS Sonoma 14.5

**Comment by gwarser** [comment]
I see SVG in Firefox. Fetched directly from xpi package. Ask LibreWolf why they don't use SVG.

**Comment by gwarser** [comment]
I cannot reproduce your issue on Win11 with uBO 1.58.0:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/417ae8b1-9c99-4c64-a1fe-f4c9bdf6a96a)

Also, no issue in Manjaro with Firefox Nightly and uBO dev build.

**Comment by gwarser** [comment]
@leoheitmannruiz yes. With `layout.css.devPixelsPerPx` set to `2`, I can reproduce when zoomed to 170%
