### ISSUE TITLE
parameters still do not work with directive

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#329]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt#L27

https://github.com/gorhill/uBlock/issues/3638
https://github.com/olegwukr/polish-privacy-filters/pull/14

### Steps to Reproduce

1. add this test list to your ubo
https://raw.githubusercontent.com/KonoromiHimaries/test-repo/master/test.txt
2. test it

### Expected behavior:

work

```
!#if !ext_ublock
!#include test-inc.txt
!#endif
```

### Actual behavior:

not work

```
!#if !ext_ublock
!#include test-inc.txt
!#endif

! >>>>>>>> https://raw.githubusercontent.com/KonoromiHimaries/test-repo/master/test-inc.txt
test
test
test
! <<<<<<<< https://raw.githubusercontent.com/KonoromiHimaries/test-repo/master/test-inc.txt
```

### Your environment

* uBlock Origin version: latest stable
* Browser Name and version: chrome latest stable
* Operating System and version: w10

**Comment by gwarser** [comment]
Two different features? I think, list is scanned for inclusions first https://github.com/gorhill/uBlock/blob/5e08d083e05e8147ed91806da213365488db38fd/src/js/assets.js#L182 and after that scanned for conditions https://github.com/gorhill/uBlock/blob/2189f020dfb5d2d8728c17ead85e6f7905e3e984/src/js/storage.js#L872

**Comment by uBlock-user** [comment]
What doesn't work ? List is fetched succesfully and Github logo is blocked in Chromium. I don't see any issue here.

**Comment by uBlock-user** [comment]
```
!#if !ext_ublock
!#include test-inc.txt
!#endif

! >>>>>>>> https://raw.githubusercontent.com/KonoromiHimaries/test-repo/master/test-inc.txt
test
! <<<<<<<< https://raw.githubusercontent.com/KonoromiHimaries/test-repo/master/test-inc.txt
```

That would only work when you browse to test.com, org or all other domains.

**Comment by KonoromiHimaries** [comment]
@uBlock-user https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition

>Tip: since ext_ublock is always true in uBO, you can use a !#if directive to disable a large block of your filters without having to remove them:
>```
>!#if !ext_ublock
>...
>!#endif
>```

**Comment by uBlock-user** [comment]
!ext_ublock condition will return false because` ext_ublock` is always true in uBO

**Comment by gwarser** [comment]
List is always included, no mater in what `if` directive is placed. I tried in local http server<sup>*</sup> yesterday with `!ext_ublock` and `ext_ublock` and just now with `!env_firefox`/`env_firefox`


\* `python3 -m http.server 8080`

**Comment by gorhill** [comment]
From what I see reported in "Actual behavior", looks like a bug to me. I would expected the included list to be inserted at the `#!include` directive point.

**Comment by gwarser** [comment]
Heh, I thought inclusion will be skipped for false conditions. With in-place insertion works for me now.

**Comment by gorhill** [comment]
Processing `!#include` directives is done in filter list-fetch code, while the conditional directives are processed in the filter-compile code.

The reason is that `!#include` directives are meaningless for user filters, so I did not want these directives to be processed when processing user filters. The `!#include` directive are meaningless for user filters because the directives are supposed to load a URL which origin is the same as the main list -- and user filters have no origin (they are just save locally in a browser-controlled storage).
