### ISSUE TITLE
Hiding rules are unable to specify to only block on the core domain and none of the subdomains (e.g. `~*.example.org` doesn't work)

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#3291]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Essentially, a syntax like `~*.example.org` is listed in uBO's resource viewer as being an incorrect syntax, although there are cases where such a syntax would've made sense to support. In particular, if I want to only cover a main domain and not any of its subdomains at all, I presumed `example.org,~*.example.org##(...)` would work, but at the time of writing it doesn't.

While not all sites out there would benefit from that syntax because they always prefix `www.` to their regular domain, there are a fair few major sites that don't prefix such. Major examples I know of at the time of writing are `imgur.com` and `wolt.com`

Screenshot of the resource viewer:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/22780683/5c7f43b1-cf15-472c-95b2-38fac962ddaf)

### A specific URL where the issue occurs.

```yaml
Unfortunately it'd be a bit self-incriminating for me to list an exact URL, but since I've got no other viable choice, testers can add https://raw.githubusercontent.com/DandelionSprout/adfilt/b862f695ce847da6faf1a2f69231b5edca9227e4/a.txt as a custom list, use the "Error: n" counter on top of the resource viewer to scroll down, and ignore virtually everything else about that list.
```

### Steps to Reproduce

1. Add `example.org,~*.example.org##.JohnMadden` to "My Filters"
2. See that "My Filters" mark `~*.example.org` in red with the hover note "Invalid filter: Bad domain name"

### Expected behavior

That a method would exist to only have a hiding rule apply to a core domain and none of its subdomains. My ideas are either:

1. `example.org,~*.example.org##(...)`
2. `|example.org##(...)`

### Actual behavior

The error situations listed and screenshot above.

### uBO version

1.58.1b11

### Browser name and version

Chrome 126.0.6478.127 x64

### Operating System and version

Windows 11 23H2 x64, with all monthly 23H2 updates installed since

**Comment by garry-ut99** [comment]
> https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#cosmetic-filters : Starting with [1.46.1b15](https://github.com/gorhill/uBlock/commit/81498474d6d440b032681aa9952d593749b39efb), you can use regex-based values as target domain for static extended filters. Example of usage: `/img[a-z]{3,5}\.buzz/##+js(nowoif)`. Use sparingly, when no other solution is practical from a maintenance point of view -- keeping in mind that uBO has to iterate through all the regex-based values, unlike plain hostname or entity-based values which are mere lookups.

`example.org,~*.example.org##.JohnMadden` = `/^example\.org$/##.JohnMadden`

Your proposition would still have a performance benefit over regex, but it depends on how often such cases are really needed, if only occasionally then already existing solution is sufficient, unless amount of such cases is enought
