### ISSUE TITLE
'remove-cookie' scriptlet sometimes does not work

### ISSUE THREAD

**Issue by andris86** [uBlockOrigin/uBlock-issues#3293]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`remove-cookie` scriptlet does not sometimes remove a cookie. At discovermagazine.com rule `discovermagazine.com##+js(remove-cookie,kserv-session)` does not work. Logger shows the scriptlet but it does not have any effect on the cookie kserv-session.

But on nautil.us this scriptlet works as expected. Rule `nautil.us##+js(remove-cookie,arc)` succesfully removes cookie called arc.

I checked on Brave, Edge and Firefox Nightly. Can reproduce this issue on all three browsers.

### A specific URL where the issue occurs.

```yaml
https://www.discovermagazine.com/mind/what-does-it-mean-to-be-an-ambivert
```

### Steps to Reproduce

1. Add `discovermagazine.com##+js(remove-cookie,kserv-session)`  rule to custom filter and add that filter to filter list or to user filters.
2. Open cookie list in browser devtools and put 'kserv-session' in filter so you can easily see what is happening with it.
3. Open discovermagazine.com. You can use article I linked or open any other article.
4. Logger shows that this scriptlet is correct and working but actually cookie called `kserv-session` was not removed. You can see in devtools that this cookie is still there.
5. Open other articles. This cookie still isn't removed.

### Expected behavior

Cookie is removed.

### Actual behavior

Cookie didn't get removed.

### uBO version

1.58.0

### Browser name and version

Brave Version 1.67.123 Chromium: 126.0.6478.126

### Operating System and version

Windows 11 10.0.22631

**Comment by uBlock-user** [comment]
Despite the name, cookies are expired, not removed.

**Comment by stephenhawk8054** [comment]
`kserv-session` is an [`HttpOnly` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#block_access_to_your_cookies) which cannot be removed by javascript

> A cookie with the `HttpOnly` attribute can't be modified by JavaScript, for example using [Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie); it can only be modified when it reaches the server.

If you type `document.cookie` in the browser console, there's no `kserv-session` value.

**Comment by stephenhawk8054** [comment]
It depends on whether the site sets the cookie again after uBO removing it or not.

**Comment by D4niloMR** [comment]
When the modification of request headers is implemented, we should be able to remove `kserv-session` from the request header. 

For `AWSALBTG` cookie, you can add `discovermagazine.com##+js(remove-cookie, AWSALBTG, when, scroll)`

**Comment by gorhill** [comment]
There is no guarantee the cookie is still removed after the scriptlet execute when the site keeps setting it -- there is no cookie-blocking API in the DOM. There is an experimental [CookieChangeEvent](https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent) but currently not available in Firefox -- so this may be used in the future when support is present for all browsers.

**Comment by allendema** [comment]
There is now wide browser compatibility.
https://developer.mozilla.org/en-US/docs/Web/API/CookieChangeEvent#browser_compatibility
