### ISSUE TITLE
"Cannot filter correctly when launching the browser." 

### ISSUE THREAD

**Issue by AlexIs387** [uBlockOrigin/uBlock-issues#3294]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"Reload the page to ensure correct filtering." 

### A specific URL where the issue occurs.

```yaml
any.com
```

### Steps to Reproduce

1. Now
2. I got this
3. When opening
4. The browser

### Expected behavior

I'm sick, this extension is dead to me

### Actual behavior

 I'll use Adguard from now

### uBO version

Latest

### Browser name and version

Any

### Operating System and version

Windows, Android, no matter which

**Comment by iam-py-test** [comment]
This is not a problem with uBlock Origin; in Chromium browsers, websites load before extensions are ready. As this is cause by a design issue in Chromium, all browser-based content filters are affected to some extent.
[This is less of an issue in Firefox-based browsers](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch).
Thank you

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded

**Comment by AlexIs387** [comment]
> This is not a problem with uBlock Origin; in Chromium browsers, websites load before extensions are ready. As this is cause by a design issue in Chromium, all browser-based content filters are affected to some extent. Moreover, there is little more gorhill and the uBlock Origin team can do to address this issue. [This is less of an issue in Firefox-based browsers](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch). Please be respectful. Thank you

I'm respectful with those who deserve it, you're welcome
