### ISSUE TITLE
Cosmetic filter "##" or "##tag," same as "##*" in element picker only

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#331]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

# In element picker:

- https://i.imgur.com/SyTc5EF.png - `##` / `##tag,` invalid in uBO 1.17.0
 
- https://i.imgur.com/a46YSle.png - `##` / `##tag,` valid in uBO 1.17.4 as `##*`, IMO.

Fortunately, after refreshing the page, the filter does nothing
 (invalid on `filter lists` > `My filters` "0 used out of 0").

### A specific URL where the issue occurs

`example.com`

### Steps to Reproduce

1. Install/Use Firefox Quantum <sup>(optionally Opera / Chrome)</sup>
2. Install uBO 1.17.4 <sup>(required)</sup> <sup><sup>/ Nano Adblocker 1.0.0.81 (optionally on Opera / very optionally on Chrome)</sup></sup>
3. Open example `https://example.com/`
4. Try block element
5. Change filter to only `##` or add on end character comma (`##tag,`)
6.  Whole page is reddening with frames without reason.

### Expected behavior:

![](https://i.imgur.com/SyTc5EF.png)

`##` / `##tag,` as invalid

### Actual behavior:

![](https://i.imgur.com/a46YSle.png)

`##` / `##tag,` as valid

### Your environment

* uBlock Origin version: uBO 1.17.4
* Browser Name and version: Firefox 63.0.3 x64
* Operating System and version: Windows 7 Pro x64

**Comment by krystian3w** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/a3acbo/cosmetic_filter_same_as/eb4s0ug/

**Comment by gwarser** [comment]
Regression after https://github.com/uBlockOrigin/uBlock-issues/issues/283

Probably because of this line: https://github.com/gorhill/uBlock/blob/b548fa43188c2d0532d171fb70e7cdd887b01349/src/js/scriptlets/element-picker.js#L764

Changed here: https://github.com/gorhill/uBlock/commit/7d100f7b21a97c2f54389cce3b9022bbec2d3070?diff=unified#diff-a65f6e6abc235a14e93548d8bf53b81eR760

**Comment by gwarser** [comment]
`':not(#' + pickerRoot.id + ')'`

Why this was added? Should be possible to hide picker even now by `##frame,*`, `:not` part will only apply to `*`, but picker is still visible.

**Comment by gorhill** [comment]
> Why this was added?

Well at some point there is a balance to be had about how far I will go in the code to prevent crafty people from going around the original intent. The original motivation is that anybody could end up with `iframe` as a choice in the list of suggested cosmetic filter, so I had to prevent the picker from highlighting itself. Beyond that, it's not worth over-complicating the code to deal with `##iframe,*` and likes, it's not something uBO would ever offer as a suggested cosmetic filter.

**Comment by gorhill** [comment]
Well looking at it now I could try a different approach than the `:not` one.

**Comment by gorhill** [comment]
Turned out there was a simpler solution I should have thought about in the first place.

**Comment by krystian3w** [comment]
I found similar bug **works in element picker <ins>only</ins>**:

```
##body:not(bodzio
```

colorize body when try block element by element picker.

![image](https://user-images.githubusercontent.com/35370833/51479218-ecaf0c80-1d8d-11e9-91e9-1db61ee6b6a2.png) |
---- |

Tested in uBO v1.17.7rc2 (Firefox 64.0.2) + uBO 1.17.0 (Opera 57)


---

_Maybe reported long time ago...._

**Comment by gorhill** [comment]
I don't consider this a bug -- if the selector is considered valid by the browser, than it's valid for uBO.

**Comment by gorhill** [comment]
You're right, it's rejected by uBO after clicking "Create". I suspect it's because uBO test the validity of the filter by appending more stuff to it. In any case, this is unrelated to the original issue here, something needs to be fixed elsewhere.

**Comment by krystian3w** [comment]
OK.
