### ISSUE TITLE
Save button is not available after deleting Temporary rules

### ISSUE THREAD

**Issue by Sopor** [uBlockOrigin/uBlock-issues#333]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    -  [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the settings of uBlock Origin i have `My rules`. On the right side i have `Temporary rules`. If i select all the text and i use Delete in the context menu instead of delete on my keyboard the Save button will not be available. So if i want to save it i need to type any char and then delete it again and now i can use the Save button.

I have tested it on several computers running Firefox and it is the same behavior.
In Chrome it is working as expected.

### A specific URL where the issue occurs

My rules / Temporary rules

### Steps to Reproduce

1. Select all text with the mouse (or use Select all).
2. Right click to open context menu.
3. Use delete in the context menu.

### Expected behavior:

Save button should be available.

### Actual behavior:

Save button is not available (grayed out).

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox 63.0.3 (64-bit)
* Operating System and version: Windows 8.1

**Comment by uBlock-user** [comment]
> In Chrome it is working as expected.

Chromium/Chrome doesn't have delete option in the context menu.

**Comment by gorhill** [comment]
I can reproduce.

I see CodeMirror errors in the console:

    TypeError: node is null[Learn More] codemirror.js:9086:5
    walk /lib/codemirror/lib/codemirror.js:9086:5
    domTextBetween /lib/codemirror/lib/codemirror.js:9114:5
    ContentEditableInput.prototype.pollContent /lib/codemirror/lib/codemirror.js:8952:35
    ContentEditableInput.prototype.updateFromDOM /lib/codemirror/lib/codemirror.js:9021:32
    ContentEditableInput.prototype.readFromDOMSoon/this.readDOMTimeout< /lib/codemirror/lib/codemirror.js:9014:5

Clicking again in the editor and the deleted content all reappear.

**Comment by uBlock-user** [comment]
@gorhill In firefox? which version ?

**Comment by gorhill** [comment]
Version mentioned by OP: Firefox 63.0.3 (64-bit) (except Linux one instead of Windows)

**Comment by gorhill** [comment]
The issue is not present if using Cut instead of Delete.

**Comment by uBlock-user** [comment]
and doesn't happen on Windows build of Firefox 63 either..

**Comment by Sopor-** [comment]
> > In Chrome it is working as expected.
> 
> Chromium/Chrome doesn't have delete option in the context menu.

@uBlock-user I know but i can use Cut

**Comment by gorhill** [comment]
> doesn't happen on Windows build of Firefox 63

OP says its OS is "Windows 8.1".

**Comment by okiehsch** [comment]
I can reproduce with Windows 10 and Firefox 63.

**Comment by uBlock-user** [comment]
Doesn't happen on Nighly, version specific to 63 then.

**Comment by gorhill** [comment]
If I remove the setting `inputStyle: 'contenteditable'` from the CodeMirror editor, the issue disappears.

I added this setting when I added the ability to filter out rules [in this commit](https://github.com/gorhill/uBlock/commit/6871d9aed43273e1bd1714641539d403508ec0c9#diff-cfcc760342eba31dee2fefe5101448f5R39).

I can't remember exactly why I added this setting, but I am sure there was a reason for this.

**Comment by gwarser** [comment]
because was removed here https://github.com/gorhill/uBlock/commit/96d4f987ac382b500b7b01ecc314d6532a953a13

and first used here https://github.com/gorhill/uBlock/commit/34efe9d6f2bef3b0c37e48dc9c290085d08aa33c

doc https://codemirror.net/doc/manual.html#option_inputStyle

**Comment by gorhill** [comment]
Such edge issues arising from using external library CodeMirror won't be addressed here when there is a workaround.
