### ISSUE TITLE
ublock doesn't work on Tor

### ISSUE THREAD

**Issue by pbzinwindows** [uBlockOrigin/uBlock-issues#3330]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

ublock doesn't work on Tor

### A specific URL where the issue occurs.

```yaml
all
```

### Steps to Reproduce

install ublock and open all websites

### Expected behavior

ublock block ads tor

### Actual behavior

ublock doesn't work on Tor

### uBO version

 1.59.0

### Browser name and version

13.5.2 (baseado no Mozilla Firefox 115.14.0esr)

### Operating System and version

windows11

**Comment by gwarser** [comment]
Did you allow uBO to work in private browsing mode?

**Comment by pbzinwindows** [comment]
> Did you allow uBO to work in private browsing mode?

No, allow it now and it worked, thanks friend
