### ISSUE TITLE
Not allowing videos to run in hulu

### ISSUE THREAD

**Issue by dustyashes65** [uBlockOrigin/uBlock-issues#3333]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When pulling up in the FireFox app and only for Hulu it will not allow videos to play. Only when Ublock is turned off will it allow videos to play. It will work on other sites and it seems only for myself so far. My friend is using it the same way and it will work. It has also worked for me before today, but now it has stopped. Again, it is only doing it while using firefox and trying to watch videos on Hulu. Also spoke with hulu support, tried clearing the cache, and redownloading browser. 

### A specific URL where the issue occurs.

```yaml
www.hulu.com
```

### Steps to Reproduce

1. open firefox 2. open hulu 3. click on hulu video to play 

### Expected behavior

video to play

### Actual behavior

only will show black screen

### uBO version

Ublock Origin standard

### Browser name and version

Firefox

### Operating System and version

Hulu

**Comment by iam-py-test** [comment]
> - [X] I verified that this is not a filter list issue. Report any issues with filter lists or **broken website functionality** in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).

I am sorry, but this issue tracker is only for issues with uBlock Origin as an extension, not the rules it enforces.
Thank you

**Comment by chkbm** [comment]
I am having the same issue:

uBlock Origin: 1.61.2
Chromium: 132
filterset (summary):
 network: 141712
 cosmetic: 49783
 scriptlet: 23263
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 2-0, never
  easylist: 78525-424, 21m Δ
  easyprivacy: 53301-741, 21m Δ
  plowe-0: 3542-0, 9d.7h.38m
  ublock-badware: 12406-20, 21m Δ
  ublock-filters: 40918-289, 21m Δ
  ublock-privacy: 1648-22, 21m Δ
  ublock-quick-fixes: 201-1, 21m Δ
  ublock-unbreak: 2541-32, 21m Δ
  urlhaus-1: 23345-0, 21m
filterset (user): [array of 2 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 318 ms
 maxAssetCacheWait: 68 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 7
 network:
  hulu.com: 5
  sc-static.net: 1
  yimg.com: 1
 extended:
  ##+js(set-constant, Object.prototype._parseVAST, noopFunc)
  ##+js(set-constant, Object.prototype.createAdBlocker, noopFunc)
  ##+js(set-constant, Object.prototype.isAdPeriod, falseFunc)
  ##+js(json-prune-fetch-response, breaks pause_ads video_metadata…
  ##+js(json-prune, breaks pause_ads video_metadata.end_credits_ti…
  ##+js(xml-prune, `xpath(//*[name()="MPD"]/@mediaPresentationDura…
