### ISSUE TITLE
commercials on you tube

### ISSUE THREAD

**Issue by mxpinke** [uBlockOrigin/uBlock-issues#3336]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello:  I'm having great success with UORIGIN.  However, for the past week I now have ads appearing on YouTube using my PC.  I have researched several resources but unable to fix the issue.  I've looked at the status for UORIGIN on YouTube and it says they have blocked 17% of ads

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com/watch?v=hbyFKD52pek&list=FL5Nsn0J7q9O4hksLDKFyo9g&index=16
```

### Steps to Reproduce

1.  updated Google Chome
2. .consulted MSN help but could not find any anwers for this specific problem.
3. rebooted PC

### Expected behavior

Deletion of ads on YouTube.

### Actual behavior

several ads appear when watching yoube whereas before there were none

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 155816
 cosmetic: 47851
 scriptlet: 22033
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 87999-558, 1h.11m Δ
  easyprivacy: 53103-22, 1h.11m Δ
  plowe-0: 3555-628, 1d.2h.42m
  ublock-badware: 10173-6, 1h.11m Δ
  ublock-filters: 39634-286, 1h.11m Δ
  ublock-privacy: 1046-2, 1h.11m Δ
  ublock-quick-fixes: 134-0, 1h.11m Δ
  ublock-unbreak: 2476-0, 1h.11m Δ
  urlhaus-1: 29235-0, 23h.41m
filterset (user): [empty]
trustedset:
 added: [array of 13 redacted]
switchRuleset:
 added: [array of 36 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 11275 ms (selfie)
 maxAssetCacheWait: 3152 ms
 cacheBackend: indexedDB
```
</details>

**Comment by iam-py-test** [comment]
> This is NOT a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. These sites MUST be reported by clicking their respective links.

This is an issue with YouTube. Please follow the instructions at https://github.com/uBlockOrigin/uAssets/issues/20586.
> it says they have blocked 17% of ads

I am sorry, but you are incorrect. This indicates 17% of the requests made by YouTube while loaded in that tab matched a rule and were blocked. These requests may have been ads, trackers, false positives, or something else.
Thank you
