### ISSUE TITLE
Implement AdGuard's hide-in-shadow-dom scriptlet

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#3340]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

    * @scriptlet hide-in-shadow-dom
    *
    * @description
    * Hides elements inside open shadow DOM elements.

https://github.com/AdguardTeam/Scriptlets/blob/master/src/scriptlets/hide-in-shadow-dom.js

### A specific URL where the issue occurs.

The AdGuard lists now use this scriptlet to hide elements on major websites, including Reddit's app banner:

https://github.com/AdguardTeam/AdguardFilters/issues/186152#issuecomment-2285991989

https://github.com/search?q=repo%3AAdguardTeam%2FAdguardFilters%20hide-in-shadow-dom&type=code

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.59.0

### Browser name and version

Brave stable

### Operating System and version

Debian 12.6

**Comment by stephenhawk8054** [comment]
uBO has [`:shadow()`](https://github.com/gorhill/uBlock/commit/52b46eb98bedfa746206e89ac016734cbbed092a).

Can you give an example where you want to use it?

**Comment by garry-ut99** [comment]
>   * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=sort%3Aupdated-desc+is%3Aissue) to avoid opening a duplicate issue.

Duplicated request/discussion of :
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2980

You should have been posting in the already exising thread.
By the way the last comment https://github.com/uBlockOrigin/uBlock-issues/discussions/2980#discussioncomment-7678858 contains links to useful related discussions, in case you didn't see them before and are interested.
