### ISSUE TITLE
https://donghuaworld.com pop up for x3 time 

### ISSUE THREAD

**Issue by Reny125** [uBlockOrigin/uBlock-issues#3341]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

i have reported this problem 3 times, save me and you some time and check the reports 

### A specific URL where the issue occurs.

```yaml
i have reported this problem 3 times, save me and you some time and check the reports
```

### Steps to Reproduce

i have reported this problem 3 times, save me and you some time and check the reports 

i have reported this problem 3 times, save me and you some time and check the reports 

i have reported this problem 3 times, save me and you some time and check the reports 

### Expected behavior

i have reported this problem 3 times, save me and you some time and check the reports 

### Actual behavior

i have reported this problem 3 times, save me and you some time and check the reports 

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 127
filterset (summary):
 network: 152227
 cosmetic: 47875
 scriptlet: 22044
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 84920-49, 5h.10m Δ
  easyprivacy: 53119-21, 5h.10m Δ
  plowe-0: 3547-988, 9d.33m
  ublock-badware: 10211-26, 5h.10m Δ
  ublock-filters: 39632-370, 5h.10m Δ
  ublock-privacy: 1055-5, 5h.10m Δ
  ublock-quick-fixes: 132-9, 5h.10m Δ
  ublock-unbreak: 2481-35, 5h.10m Δ
  urlhaus-1: 28705-0, 15h.37m
filterset (user): [empty]
trustedset:
 added: [array of 8 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 6711 ms (selfie)
 maxAssetCacheWait: 1750 ms
 cacheBackend: indexedDB
```
</details> i have reported this problem 3 times, save me and you some time and check the reports

**Comment by stephenhawk8054** [comment]
Just continue commenting in your old thread: https://github.com/uBlockOrigin/uAssets/issues/21875 . All volunteers are notified with new comments.

Don't spam.
