### ISSUE TITLE
Failed to execute 'clone' on 'Request': Request body is already used

### ISSUE THREAD

**Issue by JackMauro** [uBlockOrigin/uBlock-issues#3343]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [ ] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I don't know if this is a youtube filter issue or uBlock itself issue.

Watching youtube videos, the logger window show a lot of these errors:

--------------------
[www.youtube.com][json-prune-fetch-response ⁝ reelWatchSequenceResponse.entries.[-].command.reelWatchEndpoint.adClientParams.isAd entries.[-].command.reelWatchEndpoint.adClientParams.isAd ⁝ ] Error: TypeError: Failed to execute 'clone' on 'Request': Request body is already used

[www.youtube.com][json-prune-fetch-response ⁝ playerAds adPlacements adSlots playerResponse.playerAds playerResponse.adPlacements playerResponse.adSlots [].playerResponse.adPlacements [].playerResponse.playerAds [].playerResponse.adSlots ⁝ ] Error: TypeError: Failed to execute 'clone' on 'Request': Request body is already used

[www.youtube.com][json-prune-fetch-response ⁝ playerAds adPlacements adSlots playerResponse.playerAds playerResponse.adPlacements playerResponse.adSlots ⁝ ] Error: TypeError: Failed to execute 'clone' on 'Request': Request body is already used

[www.youtube.com][replace-fetch-response ⁝ /"adSlots.*?\}\}\],"adBreakHeartbeatParams/ ⁝ "adBreakHeartbeatParams ⁝ player?] TypeError: Failed to execute 'clone' on 'Request': Request body is already used

[www.youtube.com][replace-fetch-response ⁝ /"adPlacements.*?([A-Z]"\}|"\}{2,4})\}\],/ ⁝ ⁝ player?] TypeError: Failed to execute 'clone' on 'Request': Request body is already used
--------------------

### A specific URL where the issue occurs.

```yaml
https://www.youtube.com/watch?v=R-aRpWUNILg
```

### Steps to Reproduce

1: create new profile
2: installa ublock origin with default lists selected
3: open logger window
4: visit the page

### Expected behavior

no errors

### Actual behavior

errors displayed

### uBO version

1.59

### Browser name and version

Ungoogled Chromium 109

### Operating System and version

Windows 7

**Comment by garry-ut99** [comment]
>  * [x]  I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen).

> I don't know if this is a youtube filter issue or uBlock itself issue.



What you pasted from Logger are entries related to uBlock filters/scriptlets, see:
https://github.com/gorhill/uBlock/wiki/Resources-Library#json-prune-fetch-responsejs-
in such cases, you should always report and ask in filters tracker: 
- https://github.com/uBlockOrigin/uAssets/issues/20586

**Comment by gorhill** [comment]
> Expected behavior
> no errors

Why? Errors in scriptlets are not unexpected, the logger merely reports them.
