### ISSUE TITLE
homepage on chrome store shows the plugin will soon no longer be supported 

### ISSUE THREAD

**Issue by me-zo** [uBlockOrigin/uBlock-issues#3346]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

the home screen of the plugin shows an info box underneath the install button saying this plugin will soon stop functioning or more precisely "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.". i looked through the learn more link and it seems to do something with new requirements from chrome.

### A specific URL where the issue occurs.

```yaml
https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
```

### Steps to Reproduce

open the ublock origin web chrome extensions site and see the warning.

### Expected behavior

the info box should not show while the plugin is still being actively maintained. and chrome shouldn't move the plugin to a to-be-removed plugin list 

### Actual behavior

it does.

### uBO version

latest version on chrome for windows

### Browser name and version

Chrome, latest

### Operating System and version

Windows 11

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/3309
