### ISSUE TITLE
exception filters created does not work

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#3347]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

iam creating an exception filters with website from ubo logger but it is still blocked

### A specific URL where the issue occurs.

```yaml
https://veev.to/d/4vz566d3awg0
```

### Steps to Reproduce

- add `veev.to#@#+js()`
- go to `https://veev.to/d/4vz566d3awg0`
- filter content a/c to 3p => xhr
- allow request coninciding with regex rule blocking `/^https?:\/\/[a-z]{8,15}\.xyz\/$/$xhr,3p,method=head,header=x-traceid,to=xyz` (as these ad xhr's are random)
- observe requests are still blocked

### Expected behavior

should honor exception filters if rule is not $important modifier

### Actual behavior

xhr requests are still blocked 

https://github.com/user-attachments/assets/8a881268-a139-4bc5-b5c5-23b860a38ce6

### uBO version

1.59.1b2

### Browser name and version

opera stable

### Operating System and version

win 10

**Comment by gorhill** [comment]
I cannot reproduce. When I except `@@/^https?:\/\/[a-z]{8,15}\.xyz\/(?!api|available|team)[a-z]{4,}\.json$/$xhr,3p,match-case` from logger, I see the matching `xhr` requests no longer being blocked.

![image](https://github.com/user-attachments/assets/2c3b3002-7697-4d8c-8196-b7a2c447f8f3)

**Comment by gorhill** [comment]
Sorry, first time I understood exception from logger's _exception_ button.

I can reproduce when using a plain exception in _My filters_. Issue is that the filtering engine only look up exceptions filters using `header=`, not plain ones.
