### ISSUE TITLE
Is it make sense to insert user stylesheet at a lower priority level?

### ISSUE THREAD

**Issue by whileloopa** [uBlockOrigin/uBlock-issues#335]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The purpose of inserting user stylesheet is to override the styles of web pages. Is it make sense to insert user stylesheet at a lower priority level, the "user" level, instead of the "author" level?
I think it is better to use { cssOrigin: 'author' }, which is the default value, instead of { cssOrigin: 'user' }.

### A specific URL where the issue occurs

https://github.com/

### Steps to Reproduce

1. Open option page and create a cosmetic filter for github.com
2. github.com##body[class]:style( background-color:yellow )
3. Open/reload github.com

### Expected behavior:

The cosmetic filter style rule is more specific than the author rule and should has higher priority. The background color should become yellow.

### Actual behavior:

The background color remain unchanged.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Chrome
* Operating System and version: Windows 7

**Comment by uBlock-user** [comment]
`github.com##body[class]:style(background-color:yellow !important)` works.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/148
