### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Pwtaiwan** [uBlockOrigin/uBlock-issues#3354]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

The sites' ads are no longer blocked

### A specific URL where the issue occurs.

```yaml
https://www.wcofun.net/seitokai-yakuindomo-season-1-episode-10-english-subbed

https://jpnja.dokkaninfo.com/cards/1013121#google_vignette


https://jpn.dokkan.wiki/cards/1013121
```

### Steps to Reproduce

1firefox wasn't working so I restart

2..reeopen and all the ads are not blocked

### Expected behavior

There are no ads showing

### Actual behavior

All of the ads are showing. I can't get rid of them

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Firefox: 129
filterset (summary):
 network: 10943
 cosmetic: 3138
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39709-126, 1h.19m Δ
  ublock-badware: 10622-6, 1h.19m Δ
  ublock-privacy: 1061-4, 1h.19m Δ
  ublock-unbreak: 2565-1, 1h.19m Δ
  ublock-quick-fixes: 170-4, 1h.19m Δ
  easylist: 85422-182, 1h.19m Δ
  easyprivacy: 53060-65, 1h.19m Δ
  urlhaus-1: 29400-0, 5h.20m
  plowe-0: 3547-0, 2d.7h.54m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 45298 ms (selfie)
 maxAssetCacheWait: 3191 ms
 cacheBackend: indexedDB
```
</details>

**Comment by stephenhawk8054** [comment]
```yml
filterset (summary):
 network: 10943
 cosmetic: 3138
 scriptlet: 0
 html: 0
```

Hmm... This looks weird

**Comment by Pwtaiwan** [comment]
Its not working

**Comment by stephenhawk8054** [comment]
Get the troubleshooting information after reinstall like above.

**Comment by Pwtaiwan** [comment]
It works now! thanks

**Comment by garry-ut99** [comment]
> Stephen: Hmm... This looks weird

This too:  `allReadyAfter: 45298 ms (selfie)`

**Comment by stephenhawk8054** [comment]
In Firefox case, it could be some other extensions are hogging too much resources and uBO has to wait for available resources.

**Comment by garry-ut99** [comment]
That implies an assumption he did not answer truthfully:
>   * [x]  (Pwtaiwan) : uBO is the only extension.

But given many of them are being caught red-handed on ticking checkboxes untruthfully, that's possible and not surprising.
