### ISSUE TITLE
[Firefox] Can't use some combinations of modifiers for the shortcuts

### ISSUE THREAD

**Issue by FatOrangutan** [uBlockOrigin/uBlock-issues#336]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/uBlockOrigin/uBlock-issues/issues/106 was fixed around the Firefox 61 time-frame, back when certain combinations of modifiers (e.g. ctrl+alt) were not allowed by Firefox. [Starting with 63, however](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations):
>secondary modifier (optional). If supplied, this must be either "Shift" or (for Firefox ≥ 63) any one of "Ctrl", "Alt", "Command" and "MacCtrl", which has not been used as the main modifier.

### Steps to Reproduce

1. Switch to the Shortcuts tab
2. Try setting something to say ctrl+alt+`key`, or alt+ctrl+`key` or shift+alt+`key` etc.

### Expected behavior:

The typed combination to show up.

### Actual behavior:

The combination is reduced to ctrl+`key`, alt+`key`, alt+`key` respectively.

### Your environment

* uBlock Origin version: 1.17.5b3
* Browser Name and version: Nightly 65
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
> Starting with 63, however

I want uBO to still work fine with Firefox 60 ESR.

Beside, it looks like [Firefox UI will support assigning shortcuts in the near future](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384), so I won't do any more work uBO-side regarding this.
