### ISSUE TITLE
[UI suggestion] Move nested filter list expansion toggle to the left

### ISSUE THREAD

**Issue by ThinkChaos** [uBlockOrigin/uBlock-issues#3364]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi,

I'm a long time uBO user (thanks for all the work!) and am writing a tiny guide to install and configure it, so I was looking at the settings, doing my best to think like I've never seen it (and using a fresh browser profile).  

I think the nested filter list expansion toggle is easy to miss on the right, and not consistent with the top level ones:
![image](https://github.com/user-attachments/assets/d1fbdea3-5ca9-406c-9596-d346f2c4ac3b)

So I wanted to suggest moving it to the left of the checkbox.  
And potentially styling it closer to the top level ones since I assume the color was chosen to make it more noticeable, which moving would address.

### A specific URL where the issue occurs.

```yaml
moz-extension://caba6d4c-ca82-4730-9a3d-e848de56b77f/dashboard.html#3p-filters.html
```

### Steps to Reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### uBO version

uBlock Origin 1.59.0

### Browser name and version

N/A

### Operating System and version

N/A

**Comment by gorhill** [comment]
Declined. I did try this originally before release the sublists feature, and this causes the checkboxes to not be vertically aligned, hence why the current choice. Adding a space to prevent misalignment is also not a good solution as this waste horizontal space, especially an issue in mobile version of uBO.

**Comment by garry-ut99** [comment]
I agree that it would cause a horizontal space losage.
Red vertical bar shows how much currently horizonal space is saved:

<img src="https://github.com/user-attachments/assets/3db9441c-7c6b-4366-b7ca-dd5408b8582f" width=70%>

**Comment by ThinkChaos** [comment]
I guess the indent could be reduced on smaller screens; and a vertical line added help show the hierarchy, like indent guides in text editors.  
But yeah do as you feel is best, not trying to debate this to death, just spitballing :)
