### ISSUE TITLE
aost logging breaks video on website

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#3365]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

using 
`deltabit.co##+js(aost, document.createElement)` breaks video on website

### A specific URL where the issue occurs.

```yaml
https://deltabit.co/52tiyuhsq52y
```

### Steps to Reproduce

 1. add `deltabit.co##+js(aost, document.createElement)` to my filters
 2. visit website

### Expected behavior

video on website not broken
![image](https://github.com/user-attachments/assets/6556a297-1dc5-4520-b17a-ffbb1d18a4f9)

### Actual behavior

video on website is blank
![image](https://github.com/user-attachments/assets/fb88470b-29c0-4849-aab5-29ffc046e1d5)

### uBO version

1.59.1b11

### Browser name and version

opera stable

### Operating System and version

win 10

**Comment by gorhill** [comment]
Issue is caused by the site's code using [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n) `RegExp.$1`. Scriptlet's use of regex overwrite the `$1` static property. Possible solution is for the scriptlet to save/restore these deprecated properties.
