### ISSUE TITLE
it do not block ads aternos site

### ISSUE THREAD

**Issue by T099X** [uBlockOrigin/uBlock-issues#3372]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

i do not block aternos ads site

### A specific URL where the issue occurs.

```yaml
https://aternos.org/server/
```

### Steps to Reproduce

idk

### Expected behavior

idk

### Actual behavior

idk

### Configuration

<details>

```yaml
uBlock Origin: 1.59.0
Chromium: 128
filterset (summary):
 network: 150685
 cosmetic: 48187
 scriptlet: 22266
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 39894-376, 3h.49m Δ
  ublock-badware: 11153-6, 3h.49m Δ
  ublock-privacy: 1112-2, 3h.49m Δ
  ublock-unbreak: 2469-0, 3h.49m Δ
  ublock-quick-fixes: 101-0, 3h.49m Δ
  easylist: 85988-467, 3h.49m Δ
  easyprivacy: 53053-648, 3h.49m Δ
  urlhaus-1: 25475-0, 4h.49m
  plowe-0: 3543-0, 1h.49m
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2540 ms (selfie)
 maxAssetCacheWait: 81 ms
 cacheBackend: indexedDB
```
</details>

**Comment by gorhill** [comment]
> [x]  I verified that this is not a filter list issue

https://github.com/uBlockOrigin/uAssets/issues/13144
