### ISSUE TITLE
update now disabled

### ISSUE THREAD

**Issue by 3052** [uBlockOrigin/uBlock-issues#3373]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

under filter lists, an "update now" button is visible, but you can no longer click it

### A specific URL where the issue occurs.

```yaml
dashboard.html
```

### Steps to Reproduce

1. open the dashboard
2. filter lists

### Expected behavior

button should be clickable or removed

### Actual behavior

button is displayed but cannot be clicked

### uBO version

1.59.0

### Browser name and version

Firefox

### Operating System and version

Windows

**Comment by gorhill** [comment]
> you can no longer click it

It has always been like this, it's disabled if no filter lists are out of date.

**Comment by garry-ut99** [comment]
Moreover:

>   * [x]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

it's even already mentioned in documentation:

> https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now : 
> This button is available only if there is at least one filter list that is out of date. 

<hr>

By the way, as for:

> 3052: https://github.com/uBlockOrigin/uBlock-issues/issues/3448#issuecomment-2466962134: 
>
> 5. user has no idea why website is still broken, why issue was closed, and they can do nothing to fix it because the "fix" button was removed from the UI. see a problem? if you must remove the button so be it, but at least add a note to `dashboard.html`, an explanation, SOMETHING, because the current situation is just causing frustration and confusion for both the maintainers and end users.

It's already mentioned in documentation:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#auto-update-filter-lists

and also in top-right corner in uBO dashboard, there is a book icon which is a link to documentation:
![](https://github.com/user-attachments/assets/e4c41f50-53ef-4289-9d77-02f489283683)

unless you still think it's insufficient and that it should be more obvious/visible.

(In case the current thread will be locked, you can continue the discussion in one of already existing threads as advised in: https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches)
