### ISSUE TITLE
Some rules may break websites that use socks proxy in Firefox

### ISSUE THREAD

**Issue by ghcsd** [uBlockOrigin/uBlock-issues#3379]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some rules may break websites that use socks proxy in Firefox

### A specific URL where the issue occurs.

```yaml
https://github.com/gorhill/uBlock
```

### Steps to Reproduce

1. Enable Socks5 proxy in Firefox.
<details>
<summary>Screenshots</summary>
<img src="https://github.com/user-attachments/assets/f88bd301-ffa3-4420-9aac-3fb44fbdfef8">
</details>

2. Ensure to enable `Uncloak canonical names` in uBlock.
3. Ensure that `uBlock filters - Privacy` is enabled in the uBlock Filter lists, or add the following rules to `My filters`.
`*$all,ipaddress=0.0.0.0,domain=~0.0.0.0|~127.0.0.1|~[::1]|~[::]|~local|~localhost`

4. load `https://github.com/gorhill/uBlock`.

<details>
<summary>Screenshots</summary>
<img src="https://github.com/user-attachments/assets/6dba644f-acb1-45f9-bb7d-1289ca2b67bb">
</details>

## Possible related bug:
Developer tools always shows 0.0.0.0 as remote address when proxy is used
`https://bugzilla.mozilla.org/show_bug.cgi?id=1445279`

---
Sorry for my bad English.

### Expected behavior

...

### Actual behavior

The page is not fully loaded 

### uBO version

uBlock Origin 1.59.1.22

### Browser name and version

Firefox Nightly 132.0a1 (2024-09-16)

### Operating System and version

Windows 10

**Comment by gorhill** [comment]
> Enable Socks5 proxy in Firefox

I can reproduce when using Tor browser as proxy:

- Launch Tor browser
- Proxy settings:
  ![image](https://github.com/user-attachments/assets/aca09d90-6307-4412-b6a7-33d8b9450068)

Especially, _Proxy DNS when using SOCKS v5_ must be check -- the issue is not reproducible without that setting.

Unfortunately, the [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1445279) related to this is stale, so no workaround possible.

For now uBO will have to discard the browser-framework provided IP address when it's `0.0.0.0`.

**Comment by HyperSoop** [comment]
Same here, using uBO in LibreWolf on Linux with a Tor SOCKS5 proxy, the `uBlock filters - Privacy` list breaks pretty much all websites catastrophically

**Comment by stephenhawk8054** [comment]
> For now uBO will have to discard the browser-framework provided IP address when it's 0.0.0.0.

So, is it the `dns.resolce()` or `onHeadersReceived()`?

**Comment by gorhill** [comment]
> So, is it the `dns.resolve()` or `onHeadersReceived()`?

It's browser-provided ip address to webRequest listeners, so `onHeadersReceived()`.

1.59.1rc1 contains a tentative fix, to be confirmed by those suffering the issue.

**Comment by gorhill** [comment]
I don't understand your comment. Yes, `null` can be returned, in which case uBO will consider the `ipaddr` property to not be usable, in which case it will try to extract the IP address from the URL.

**Comment by gorhill** [comment]
> mistakenly blocking legitimate requests

Mistaken how? Surely the IP address used by uBO comes from _somewhere_? Your screenshot shows it's set to `undefined` when IP address is `null`, hence there should be no match. You need to find where the IP address causing the match comes from. Here is another place to put a breakpoint:

https://github.com/gorhill/uBlock/blob/47bdec422a683815c8594d71e8b7c97ea4ecfa99/platform/firefox/vapi-background-ext.js#L172
