### ISSUE TITLE
Restore from file isn't working on Firefox Android 

### ISSUE THREAD

**Issue by IRainman** [uBlockOrigin/uBlock-issues#3392]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Function of import configuration isn't working at all

### A specific URL where the issue occurs.

```yaml
moz-extension://2ece2cdd-c1ac-4ab6-bdb1-4aa852affa62/dashboard.html#settings.html
```

### Steps to Reproduce

1. Open extension settings
2. Tap "Restore from file..." button

### Expected behavior

Dialog for file selection is opened. 

### Actual behavior

Nothing happened. 

### uBO version

1.59.0

### Browser name and version

Firefox Android 130.0.1

### Operating System and version

Android 13

**Comment by gorhill** [comment]
Unable to reproduce using Nightly 132.0a1.

**Comment by gorhill** [comment]
Likely duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2378>.

**Comment by IRainman** [comment]
Yes, sorry, this isn't a bug. It's my mistake: I disabled default file manager in Android and this was a problem.
