### ISSUE TITLE
[fr] button to enable ALL filters at once

### ISSUE THREAD

**Issue by POMATu** [uBlockOrigin/uBlock-issues#3398]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I am getting pretty much tired enabling every filter possible on every new firefox/chrome profile on every new pc or vm that i setup. And YES I DO need all filters enabled, for every language, in every variation that is present in default list, nd all those cookie warning removers too. And uno what? it works perfectly my machines are fast enuf to process all that. But i have to play that clicking game each time i setup new profile, i would like to have a button in UI that just sets all ticks there at once

U can probably argue that normies would abuse that button and blindly press it when they dont need all filters, but why not? if it works perfectly. I am not asking to have em enabled by default im just asking to have a button that does that
Thanks

### A specific URL where the issue occurs.

```yaml
moz-extension://extension-id/dashboard.html#3p-filters.html
```

### Steps to Reproduce

1) Create new profile in chrome or firefox that you gonna use for new context/location or maybe you just setup fresh PC for someone (after 1253th windows reinstall)
2) Visit any website and feel the pain
3) Install ublock origin
4) Click on extension icon, go to settings, go to second tab and play that clicking game

### Expected behavior

Go to addon settings and press one single button to enable em all

### Actual behavior

Had to unwrap and click every single one of em

### uBO version

1.59.0

### Browser name and version

firefox-esr

### Operating System and version

debian 12

**Comment by stephenhawk8054** [comment]
I oppose. That just makes more users enabling all the filter lists carelessly without knowing the consequences of breakages and the purposes of each list, then just report irresponsibly to uBO team and burden other volunteers like this case: https://github.com/uBlockOrigin/uAssets/issues/25499

**Comment by krystian3w** [comment]
You can try bookmark lets injection or occasionally import old config file and update if will be added new list to assets.json

**Comment by POMATu** [comment]
> You can try bookmarklets injection or occasionally import old config file and update backup if will be added new list to assets.json.
> 
> https://en.wikipedia.org/wiki/Bookmarklet

thanks will try that. I guess then zukenberg hater gotta click em all with rage. But im pretty sure cookie notices annoy everyone and not enabled by default

**Comment by garry-ut99** [comment]
Here also the previous duplicate:
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2029

and here two another old similiar issues:
- https://github.com/gorhill/uBlock/issues/419
- https://github.com/gorhill/uBlock/issues/1458
