### ISSUE TITLE
Since few days, Youtube is unusable

### ISSUE THREAD

**Issue by stromcon** [uBlockOrigin/uBlock-issues#340]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hello,

Since few days youtube is unusable with ublock origin. The left sidebar is now empty :

![img](http://image.noelshack.com/fichiers/2018/50/5/1544783805-capture-d-ecran-2018-12-14-a-11-36-35.png)

### A specific URL where the issue occurs

https://www.youtube.com/

### Steps to Reproduce

1. Go on youtube
2. Check the left sidebar

### Expected behavior:

Sidebar should not be empty

### Actual behavior:

Sidebar is empty

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: firefox last version
* Operating System and version: macOS 10.14.1

**Comment by FatOrangutan** [comment]
YouTube issue, not uBO - https://www.reddit.com/r/youtube/comments/a5tseh/sidebar_not_showing/

**Comment by stromcon** [comment]
Thanks for reply, but it is showing when I disable ublock origin.

**Comment by gorhill** [comment]
How did you ascertain this is not a filter issue?

**Comment by gorhill** [comment]
Ok I could reproduce finally.

**Comment by gorhill** [comment]
Well now I am unable to reproduce again when I wanted to start investigate.

**Comment by FatOrangutan** [comment]
>Thanks for reply, but it is showing when I disable ublock origin.  
  
Multiple people in the linked reddit thread say they can reproduce the issue on Firefox and Edge without any adblockers.

Does [this](https://www.reddit.com/r/youtube/comments/a5tseh/sidebar_not_showing/ebpz7gy/) work for you?

**Comment by gorhill** [comment]
I can reproduce with signing out and in, this allowed me to verify that the issue exists without uBO, so this is a site or browser issue.
