### ISSUE TITLE
Return Youtube Dislike

### ISSUE THREAD

**Issue by Hubcap-1** [uBlockOrigin/uBlock-issues#3408]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Return Youtube Dislike is being blocked by uBlock in Opera

### A specific URL where the issue occurs.

```yaml
YouTube.com
```

### Steps to Reproduce

Open opera browser with return youtube dislike extension installed.
Open any youtube viseo
The dislike count ( or addition with you dislike) is gone

### Expected behavior

Dislike count to appear

### Actual behavior

No more dislike count

### uBO version

uBlock Origin: 1.59.0

### Browser name and version

latest Opera for windows 

### Operating System and version

Windows 11 Latest version

**Comment by Hubcap-1** [comment]
Really miss the return dislikes

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?

**Comment by Hubcap-1** [comment]
Well it doesn't change. Interesting though cuz last time they were able to
do something that allowed the return YouTube dislike to function. I'm
guessing that's not the case this time thank you for your response

**Comment by stephenhawk8054** [comment]
Please respect the prerequisites

> - [X] The issue is not present after disabling uBO in the browser.
