### ISSUE TITLE
firefox nightly android 134.0a1 ads are showing up

### ISSUE THREAD

**Issue by david79111** [uBlockOrigin/uBlock-issues#3441]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

So since firefox updated its nightly android build from 133.0 to 134.0 ads are showing up and pop up websites just open up where they wouldnt before as long as ublock was installed.
 I think some are blocked and some are not, I'm not 100% sure.
I have no idea if this is on firefoxes behalf or on ublockorigins behalf
(because of the new firefox version a lot of sites are not working properly so I think that could be related to the ublockorigin extension not working properly but who knows)

### A specific URL where the issue occurs.

```yaml
for example
youtube
IMDB
https://genius.com/Lil-nas-x-star-walkin-lyrics
```

### Steps to Reproduce

1. install firefox nightly for android
2. open [random site] (https://genius.com/Lil-nas-x-star-walkin-lyrics)
3. see adds show up when they shouldnt as long as ublock is installed

### Expected behavior

all ads and popupsites should be blocked just like it always did

### Actual behavior

ads and popupsites showed up

### uBO version

1.60

### Browser name and version

firefox nightly 134.01a (2016053503)

### Operating system and version

android 15/lineage 22

**Comment by gorhill** [comment]
Provide an _exact_ URL of a webpage where you see ads.

Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by david79111** [comment]
so ive done what u said and therefor opened this new issue https://github.com/uBlockOrigin/uAssets/issues/25898 but I just wanted to make this clear that ads appear on every site I tried so far and not just the one I used as example

**Comment by david79111** [comment]
Nevermind, I deleted all app data from firefox nightly and reinstalled ublock and now everything works.
Thanks for your effort.
