### ISSUE TITLE
element blocked with element picker reappears after page refresh

### ISSUE THREAD

**Issue by D4n2021** [uBlockOrigin/uBlock-issues#3444]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Blocking the Google account login window in top right corner only is temporary. Not working persistent anymore. Possibly due to changing IDs of Google login window code or so? Is Google really trying to make it _even_ harder to not make them collect data?

![grafik](https://github.com/user-attachments/assets/62294933-aae8-43d6-bffc-1b1e29b51975)

### A specific URL where the issue occurs.

```yaml
https://www.reddit.com
```

### Steps to Reproduce

right click anywhere on page, then "element picker", click on the awkwardly bright white google login window and click "create". Wait a few seconds and press F5 / refresh page.

### Expected behavior

Should always block that window once selected

### Actual behavior

This Google login window reappears after every page refresh:

![grafik](https://github.com/user-attachments/assets/15e77534-e816-4eed-be88-6d7d4075ffe4)

### uBO version

1.60.0

### Browser name and version

Firefox 132.0.1

### Operating System and version

Win10 22H2 (latest build)

**Comment by garry-ut99** [comment]
> Possibly due to changing IDs of Google login window code or so?

Yes, this is exactly what is the reason.

>   * [x]  I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

It's already mentioned in the documentation:

> https://github.com/gorhill/uBlock/wiki/Element-picker#element-picker-does-not-work-removed-element-reappears-when-you-reload-the-page: The URL or selector for the blocked element contains variable parts that change each time a page is loaded.
> - If this is a network filter, you may need to manually edit the filter to use wildcards for the parts of the URL which are variable.
> -  If this is a cosmetic filter, you may have to manually craft a better [CSS selector](https://www.w3.org/TR/selectors/#overview). Sometimes this requires observing the surrounding DOM data.

Besides:
- it's already fixed in _EasyList – Annoyances ==> EasyList – Other Annoyances_ so you can just enable this list.
- or if you don't want to enable the whole list, and want to only block this single element in "My Filters", then just use the same filter from the list: `reddit.com###credential_picker_container`.

>   * [x]  I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen).

It's a filter issue, not uBO's issue.

**Comment by krystian3w** [comment]
Still, there may be an error along the way writing to the panel my filters, that the filter will not go there.


On my side this has been occurring for a while -- once out of 200 DOM element I tried hide.
