### ISSUE TITLE
Settings page is causing browser to freeze

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [uBlockOrigin/uBlock-issues#3446]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Browser freezes and has to be killed by task manager.

### A specific URL where the issue occurs.

```yaml
extension://odfafepnkmbhccpbejgmiehpchacaeak/dashboard.html#1p-filters.html
```

### Steps to Reproduce

Open the extension's settings page

### Expected behavior

Shouldn't freeze

### Actual behavior

It froze my entire browser and all its windows.

### uBO version

1.61.0

### Browser name and version

up to date Microsoft Edge

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
> up to date Microsoft Edge

Provide exact version please.

**Comment by UsernamesAreNotMyThing** [comment]
> > up to date Microsoft Edge
> 
> Provide exact version please.

130.0.2849.68

**Comment by gorhill** [comment]
I am not seeing any other report of such issue. If you suffer a whole browser freeze, this suggests the issue is outside uBO since uBO is not supposed to freeze the whole browser, the same way a web page is not supposed to freeze the whole browser. I suggest you report the issue to browser devs.

**Comment by UsernamesAreNotMyThing** [comment]
I think what's happening is it's taking an abnormally long time to load the My Filters section, because the text field appeared blank, froze for a while, and then correctly populated with my filters.

**Comment by gorhill** [comment]
> don't know why it's taking the whole browser down while doing that

Is there something important you are not telling us about your setup?

**Comment by UsernamesAreNotMyThing** [comment]
What kinds of factors do you have in mind?

**Comment by garry-ut99** [comment]
> UsernamesAreNotMyThing : It froze my entire browser and all its windows.
> gorhill : https://github.com/uBlockOrigin/uBlock-issues/issues/3446#issuecomment-2462536730

Like also mentioned in Wiki: https://github.com/gorhill/uBlock/wiki/Can-uBO-crash-a-browser%3F

<hr>

> UsernamesAreNotMyThing : What kinds of factors do you have in mind?

That you ticked this:

>   * [x]  uBO uses default lists and settings.

but then you said you still have some filters in "My filters". 

But "My filters" is empty on default uBO configuration. This would suggest that you did not answer truthfully to the checkbox and that you didn't check on default uBO configuration and that your issue might be caused by your custom modifications of uBO. And given this, we also have no guarantee that you ticked the other checkboxes truthfully either.

**Comment by UsernamesAreNotMyThing** [comment]
I wasn't sure it would let me submit without ticking them all.

**Comment by garry-ut99** [comment]
Strange and cheap excuse...Then why didn't you just try. And and in case it stops you, it means that is the purpose of the checkboxes - to not let submit issues without fulfiling all the steps, to prevent invalid issues that might be caused by 3-rd party factors on users's side.

**Comment by UsernamesAreNotMyThing** [comment]
I just reproduced it with the "Enable my custom filters" checkbox disabled.

**Comment by gorhill** [comment]
I can't reproduce such issue, so will need someone who can reproduce to investigate the issue.
