### ISSUE TITLE
 update now disabled 

### ISSUE THREAD

**Issue by 3052** [uBlockOrigin/uBlock-issues#3448]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I had an issue "fixed"

https://github.com/uBlockOrigin/uAssets/issues/25989

but its still broken for me - and the "update now" is grayed out - so it seems I have no way to get the fix

### A specific URL where the issue occurs.

```yaml
https://www.apkmirror.com/
```

### Steps to Reproduce

visit the page

### Expected behavior

no blocking

### Actual behavior

browsing is blocked

### uBO version

uBlock Origin: 1.60.0

### Browser name and version

Firefox 121

### Operating System and version

Windows 10

**Comment by 3052** [comment]
responding to this:

https://github.com/uBlockOrigin/uAssets/issues/25989#issuecomment-2466921720

since both issues are now locked

> Because GitHub must not be used as a CDN, it's in their terms of use. It's ok to pull once in a while so we provide a link for those who can't wait. The link will stop working in a few hours, it will do nothing when you click it.

@gorhill here is the situation that you have created:

1. some website is broken
2. user post issue
3. issue is "fixed" and closed
4. website still broken for 5 hours
5. user has no idea why website is still broken, why issue was closed, and they can do nothing to fix it because the "fix" button was removed from the UI

see a problem? if you must remove the button so be it, but at least add a note to `dashboard.html`, an explanation, SOMETHING, because the current situation is just causing frustration and confusion for both the maintainers and end users.

**Comment by gorhill** [comment]
> see a problem?

Just uninstall uBO and find something else that suits your expectations.
