### ISSUE TITLE
Does not block JavaScript in embedded YouTube video on specific webpage

### ISSUE THREAD

**Issue by grizzlyuser** [uBlockOrigin/uBlock-issues#345]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When all the JavaScript is disabled using the options in the Dashboard, some JS still runs nevertheless on the web page specified below.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

https://camp.wonderhowto.com/how-to/tie-basic-lanyard-knot-294313/

### Steps to Reproduce

1. [First Step] Open the Dashboard, and disable JavaScript everywhere either by checking "Disable JavaScript" box, or by editing "My rules" and adding `no-scripting: * true`, or 
```
    * * 1p-script block
    * * 3p-script block
    * * inline-script block
```
2. [Second Step] Open the URL specified above.
3. [and so on...] Open Developer Tools -> Debugger in Firefox

### Expected behavior:

[What you expected to happen] No JS code should be executed from that URL, and so Debugger should reflect that.

### Actual behavior:

[What actually happened] Debugger shows some JS code from www.youtube.com, and if you put breakpoints, then it's obvious the JS is executed. Also, even without breakpoints, the following error is seen in the Console:
    ReferenceError: yt is not defined

### Your environment

* uBlock Origin version: 1.17.5b9, 1.17.4
* Browser Name and version: Firefox 64.0
* Operating System and version: Ubuntu 18.10, Arch Linux (both updated today)

### Notes

It seems the issue is related to [rewriting of the old-style YouTube Flash embed](https://bugzilla.mozilla.org/show_bug.cgi?id=769117) by Firefox (and probably other web browsers).

**Comment by gorhill** [comment]
I can reproduce.

Interesting case, I will have to find out whether injecting the CSP directive in the headers of the `object` does work -- currently this is done only for `main_frame` and `sub_frame`.

**Comment by gorhill** [comment]
Observation: with Chromium, the object is loaded as a `sub_frame` as per logger.

**Comment by uBlock-user** [comment]
Can't reproduce with Chromium 73, dev tools show any script execution or error related to that.
