### ISSUE TITLE
nosiif in firefox browser

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#3452]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when i use `goflix.sbs##+js(nosiif)` on firefox android, it does not log **setInterval** call
```
 <script>
        setInterval(function(){
            $("form").submit();
        }, 2000);
    </script>
```
when i set breakpoint at setInterval , i see the script 
![Unt](https://github.com/user-attachments/assets/7885ce8a-ae24-47f6-8e2d-e09876552957)

### A specific URL where the issue occurs.

```yaml
https://goflix.sbs/en/mirror/96e887fdaeb95099124dfdae16748ef0
```

### Steps to Reproduce

1. Add in my filters 
```
goflix.sbs##+js(nosiif)
||goflix.sbs^$document,csp=sandbox allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation allow-popups,badfilter
```
2. navigate to https://goflix.sbs/en/mirror/96e887fdaeb95099124dfdae16748ef0
3. ad redirect is seen

### Expected behavior

i could see logging in ublock logger & thus foil ad redirect with `goflix.sbs##+js(nosiif, /\.submit/, 2000)`

### Actual behavior

can't see setInterval call being logged

### uBO version

1.61

### Browser name and version

firefox android 132.0

### Operating System and version

android 12

**Comment by gorhill** [comment]
DO you see it when forcing a reload of the page?

**Comment by gorhill** [comment]
With Firefox 128, it became possible to inject the scriptlets directly into the `MAIN` world, so the solution is probably to avoid going [through a `blob`](https://github.com/gorhill/uBlock/blob/1.61.0/platform/firefox/vapi-background-ext.js#L357-L365) for Firefox 128+.

**Comment by gorhill** [comment]
I could reproduce on Firefox desktop.

**Comment by gorhill** [comment]
See if <https://github.com/gorhill/uBlock/commit/b1a00145bd> helps in latest dev build.

**Comment by stephenhawk8054** [comment]
I think the update works more reliably for [some cases where I needed HTML filtering](https://github.com/uBlockOrigin/uAssets/blob/2ee12a58264c923666c26ad203b6dc06ec5ba076/filters/filters-2023.txt#L1680).

**Comment by gorhill** [comment]
Nothing has changed in the code paths for HTML filtering. The change is essentially that scriptlets are directly injected as in Chromium, and to fallback to blob-based injection if direct injection fails.

**Comment by stephenhawk8054** [comment]
Yeah, I mean I was testing scriptlet solution for those domains, however they didn't work if I refresh multiple times (or click on "Duplicate" the tab) so I resorted to HTML filtering.

The new update makes the scriptlet solution works more stable for me.

**Comment by stephenhawk8054** [comment]
@ghajini Which android version are you using? From android 10 you can install xpi file as extensions. I'm using uBO dev version on my Firefox android right now.
