### ISSUE TITLE
When I updated to Google Chrome:131.0.6778.70 , uBlock Origin:1.61.0 stopped working.

### ISSUE THREAD

**Issue by suzumiyabi** [uBlockOrigin/uBlock-issues#3456]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

All sites no longer ad-blocked.

### A specific URL where the issue occurs.

```yaml
https://www.pixiv.net/
```

### Steps to Reproduce

1. install Google Chrome:131.0.6778.70 for Windows 11
2. Access to suitably advertised websites. (https://www.pixiv.net/)
3. see adds show up when they shouldnt as long as ublock is installed

### Expected behavior

all ads and popupsites should be blocked just like it always did

### Actual behavior

ads and popupsites showed up

### uBO version

1.61.0

### Browser name and version

Google Chrome:131.0.6778.70

### Operating System and version

Windows 11 Home 23H2

**Comment by gorhill** [comment]
First, need the contents of the uBO troubleshooting information: Go to the webpage with the issue > Click the [uBO toolbar icon](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface) > Click the [chat icon 💬](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Click "Troubleshooting Information" > Report content here (https://www.reddit.com/link/173jmog/video/bogwf92af9tb1/player)

**Comment by gwarser** [comment]
Plenty of connections blocked. Turn cosmetic filtering back on?

**Comment by gorhill** [comment]
> `ignoreGenericCosmeticFilters: true`
> `no-cosmetic-filtering: true`

Too much customization, you will have to diagnose this on your side -- the idea is that if you are willing to heavily customize uBO, then you have to be willing to deal with the consequences.

Here is for issues with uBO itself, filtering issues have to be reported as <https://github.com/uBlockOrigin/uAssets> through the chat icon in the popup panel, and only for issues which are not the result of customizations.

**Comment by gorhill** [comment]
And please mind what is asked from you in the prerequisite steps next time:

> - [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues)

**Comment by gorhill** [comment]
There are 10 cosmetic filters for `pixiv.net` in "EasyList", and 15 cosmetic filters for `pixiv.net` in "uBlock filters – Ads".

You disabled cosmetic filtering.
