### ISSUE TITLE
Show zapped elements in My Filters

### ISSUE THREAD

**Issue by wavepack3t** [uBlockOrigin/uBlock-issues#346]
## Feature Request

What if, at the flick of a switch in the settings panel, the element zapper integrated with cosmetic filtering? Elements I've zapped could appear in My Filters as "Temporary filters" for the domain I did the zapping on, and I would be able to persist these filters as Permanent filters. This would be a direct parallel to the Temporary rules -> Permanent rules flow in uMatrix.

For example my uBlock filter `askubuntu.com##^.s-hero` excludes an annoying banner which appears on askubuntu. To get this rule working I had to manually inspect the HTML, find a suitable element `id` or `class` (in this case `.s-hero`), and write the rule to exclude it.

What if the zapper did that work for me?

The trouble is that there is no obvious way to programmatically identify a zapped element. For example the askubuntu banner had no `id` and several `class`es. Some of these classes were for visual styling, and others identified the banner for first-party JS. I chose a class which appeared to be unique to the element I wanted to get rid of. Sometimes there will be no unique identifier.

Perhaps the zapper filter creator could degrade gracefully. For example, if you zap an element with an `id`, then we can unambiguously write the domain-wide rule for that element.

If no id is available but the element has classes, then perhaps a "filter candidate" would show up instead of a filter. The filter candidate would not be a real filter, but rather, a commented out stand-in for a filter would appear, with various selector targets: `askubuntu.com##^.s-hero|.s-hero-container` for example. It would then be up to the user to edit the filter and uncomment it.

This feature would greatly enhance the utility of `uBlock` not only as an ad blocker but also as an optimizer of site experience for junky sites.

**Comment by uBlock-user** [comment]
Or you could just use Picker instead. Zapper was designed like this on purpose to remove elements temporary.

**Comment by wavepack3t** [comment]
You know, embarrasing as it is, up til this point I had no idea what the Picker was for. I think the icon threw me off, I kept thinking it was a hex color picker.

Thanks for the tip. You just made my day.
