### ISSUE TITLE
missing: uBlock filters - Resource abuse

### ISSUE THREAD

**Issue by honx4amiga** [uBlockOrigin/uBlock-issues#3465]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

in my understanding this is not exactly a "filterlist issue" because i'm missing one complete filter list: in uBlock origin own filterlists there used to be a "uBlock filters - Resource abuse" filterlist. today i noticed this filterlist is not longer there.

only remaining filterlists in uBlock own filterlists:
uBlock filters - Ads
uBlock filters - Badware Risks
uBlock filters - Privacy
uBlock filters - Quick fixes
uBlock filters - Unbreak

there is NO "Resource abuse" anymore. is this a bug or has this filterlist been removed?

i'm running latest stable version 1.61.2

on both google chrome (version 108, last version working on windows 7 AND on [Supermium 126.0.6478.254 R4](https://github.com/win32ss/supermium/releases/tag/v126-r4) browser (chromium fork which will NOT remove manifest v2) "Resource abuse" is missing.

### A specific URL where the issue occurs.

```yaml
not a website issue, filterlist missing.
```

### Steps to Reproduce

i don't know if others can reproduce this or if "Resource abuse" filterlist is missing only for me...

### Expected behavior

"Resource abuse" filterlist still should be availabile in uBlock own filterlists.

### Actual behavior

"Resouce abuse" filterlist is missing.

### uBO version

1.61.2

### Browser name and version

Supermium 126.0.6478.254 R4, Chrome 108

### Operating System and version

Windows 7 Ultimate 64bit

**Comment by gorhill** [comment]
It's included in "uBlock filters -- Privacy". Open the list and search for `! Merge in resource-abuse.txt`.

**Comment by freezer2022** [comment]
A duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/issues/2629#issuecomment-1529015956
