### ISSUE TITLE
"uBlock filters – Cookie Notices" should be separated out just like "uBlock filters – Annoyances"

### ISSUE THREAD

**Issue by opusforlife2** [uBlockOrigin/uBlock-issues#3467]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

"uBlock filters – Annoyances" used to be a sub-filter under both the Easylist and Adguard dropdowns. One had to take care to enable it only once. Then it was separated out as its own main filter, solving the problem entirely.

"uBlock filters – Cookie Notices" is similarly bundled with both Easylist and Adguard and should be separated out as well. It seems even stranger here because without it, there would be no need for a sub-filter section for the other two either. They can just exist as three separate filters.

### A specific URL where the issue occurs.

```yaml
N/A
```

### Steps to Reproduce

View the "Cookie notices" section in the "Filter lists" pane in uBO settings.

### Expected behavior

"uBlock filters – Cookie Notices" as a separate top-level filter just like "uBlock filters – Annoyances".

### Actual behavior

It's a sub-filter under both Easylist and Adguard.

### uBO version

1.61.2

### Browser name and version

FF133

### Operating System and version

W10

**Comment by gorhill** [comment]
Declined.

"uBlock filters -- Cookie Notices" is meant to be a complement to other Cookie lists, not to be used alone.

**Comment by stephenhawk8054** [comment]
> it doesn't get selected again? Because right now you can select it twice and never realise it, if you don't expand the filter groups.

Are there any issues with both of them checked?

**Comment by stephenhawk8054** [comment]
> out of a total of 1913 filters, one of them had 1893, and the other had 23.

They are not updated at different times. Duplicated filters are automatically discarded, and duplicated filters are not statically marked, i.e the filters can be marked as duplicated at any lists for performance.

![image](https://github.com/user-attachments/assets/66eed357-d201-404f-819a-d9e7a36bbb68)

Both have 1913 filters, the number `1,893 used` are just for non-duplicated filters. All filters are compiled as one list at the end, so there's no issue of both being checked at the same time.

**Comment by stephenhawk8054** [comment]
Because there are other filters in other lists that can be duplicated with "uBlock filters – Cookie Notices" list also.
