### ISSUE TITLE
UBlock Origin reserves way too much virtual memory

### ISSUE THREAD

**Issue by ThermostellarDevice** [uBlockOrigin/uBlock-issues#3469]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When active, the virtual memory requirement for Firefox (128.0) immediately jumps to 17 GB, irrespective of any
setting of cache on/off, logger entry numbers etc. . Although resident memory is still low, this causes a couple of
subtle issues  (OS openindiana hipster 2024/10) due to excessive paging, sloppy behaviour of the desktop etc. 
When off, virtual size drops to "firefox-normal" 830 MB. This happens regardless of other extensions present or not,
webpage not relevant.

Memory: 12G phys mem, 5514M free mem, 32G total swap, 32G free swap

PID USERNAME NLWP PRI NICE  SIZE   RES STATE    TIME    CPU COMMAND
nnn    xxxxx       26     10    0      17G      135M        cpu/0   2:00  8.64% firefox
 

### A specific URL where the issue occurs.

```yaml
https://anywhere
```

### Steps to Reproduce

Install and activate uBlock Origin, restart.

### Expected behavior

Shouldn't immediately reserve *that* much virtual memory (what should that be needed for?).

### Actual behavior

vm immediately raised to 17 GB.

### uBO version

1.61.2

### Browser name and version

firefox 128.0 64bit

### Operating System and version

Openindiana Hipster 2024/10

**Comment by gorhill** [comment]
It's Firefox reserving the virtual memory, not uBO, and it's only 26 GB out of 128 TB, so less than 0.02% of addressable space. Worrying about this is pointless. Also, any site which uses WASM is also going to cause this "issue".
