### ISSUE TITLE
uBlock breaks DNSSEC Good signature

### ISSUE THREAD

**Issue by dKenGuru** [uBlockOrigin/uBlock-issues#3474]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock breaks DNSSEC Good signature validation on https://www.dnscheck.tools/
If uBlock turned off - all is fine. In Edge browser with uBlock problem not present.

### A specific URL where the issue occurs.

```yaml
https://www.dnscheck.tools/
```

### Steps to Reproduce

1. Open Firefox
2. Install uBlock with default settings
3. Go to www.dnscheck.tools

### Expected behavior

Green checks at Good signature DNSSEC

### Actual behavior

Red marks at Good signature DNSSEC

### uBO version

1.61.3b2 and 1.61.2

### Browser name and version

Firefox 135.0a1 and Edge 131.0.2903.70 

### Operating System and version

Windows 24H2

**Comment by dKenGuru** [comment]
For me is not. If I turn off uBlock - it works. If turn on - is not.

**Comment by stephenhawk8054** [comment]
Can you open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by dKenGuru** [comment]
uBlock Origin: 1.61.3b2
Firefox: 135
filterset (summary):
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
  ublock-filters: null
  ublock-badware: null
  ublock-privacy: null
  ublock-unbreak: null
  ublock-quick-fixes: null
  easylist: null
  easyprivacy: null
  urlhaus-1: null
  plowe-0: null
  RUS-0: null
filterset (user): [array of 8 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 prefetchingDisabled: false
 showIconBadge: false
 tooltipsDisabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 876 ms
 maxAssetCacheWait: 657 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 0

**Comment by stephenhawk8054** [comment]
Your uBO is broken. Test again in a new Firefox profile with only uBO and its default settings.

**Comment by dKenGuru** [comment]
I turned off all lists before test.

**Comment by dKenGuru** [comment]
Will try to dig into it and find which Firefox Nightly setting cause conflict.

**Comment by stephenhawk8054** [comment]
Did you test in a new profile yet?

**Comment by dKenGuru** [comment]
Yep, same. But I found problem. VPN software automatically change/add network.proxy.type - 5. Instead of 0. But system proxy was not set, it's empty. Why test works without uBlock and don't work with, don't know.

**Comment by stephenhawk8054** [comment]
Mine is 5 as well, but I still can't reproduce it

![image](https://github.com/user-attachments/assets/9c2d1433-9fdf-4188-8f09-677ade1bcff9)

**Comment by krystian3w** [comment]
Watch for the issue to appear in January for Firefox Beta version 135, uBo does not support Nightly and Canary channels for browsers.

**Comment by dKenGuru** [comment]
Looks like this problem will be in release of FF 134 or 135.

**Comment by dKenGuru** [comment]
dnsResolveEnabled option in uBlock cause problem.

**Comment by gorhill** [comment]
> dnsResolveEnabled option in uBlock cause problem

You are just disable calls to browser API `dns.resolve()`, that doesn't mean something else on your side is causing this. Nobody can reproduce it here, so there has to be something specific on your side which is triggering the issue.
