### ISSUE TITLE
firefox android 133.0.2 blank out when installed ublock origin

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#3475]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

firefox android blanks out or even ublock when extension installed

### A specific URL where the issue occurs.

```yaml
everywhere
```

### Steps to Reproduce

on fresh firefox android 133.0.2
STR=
1)install ublock origin
2)tick next to prevent leaking webrtc from leaking local ip addresses
3)click iam advanced user => change value of filter author mode to true=> close that tab
4)toggle between ublock settings
5) now access firefox android, in my case i accessed firefox synchronise & save data.even without this menu when i access ublock origin popup menu, it still blank out
[Firefox 2024-12-06 23.47 profile.json.gz](https://github.com/user-attachments/files/18042275/Firefox.2024-12-06.23.47.profile.json.gz)

6) firefox blank out
7) minimize firefox app then come back, its working again with all menus visible

[Firefox 2024-12-06 23.41 profile.json.gz](https://github.com/user-attachments/files/18042291/Firefox.2024-12-06.23.41.profile.json.gz)

### Expected behavior

firefox android menu or ublock popup interface remain accessible

### Actual behavior

firefox android menu or ublock popup interface remain accessible

### uBO version

1.61.2

### Browser name and version

firefox android 133.0.2

### Operating System and version

android 12

### Notes
- i made sure that i reinstalled firefox for android to rule out possibility of corrupt browser profile

**Comment by gorhill** [comment]
Since this is a new installation, uBO needs to load all the default filter lists, parsing/compiling them, saving their raw & compiled version locally, then loading them into memory; _then_ launching an update session immediately for a full update of all lists given that they are considered severely out of date, parsing/compiling them, saving their raw & compiled version locally, then loading them into memory. In short uBO is always very busy the first time it is launched after installation, this is expected.

**Comment by gorhill** [comment]
I am just describing what is happening in the profiling sessions you shared.

I have an older 2017 4-core SD821 phone and I don't see unexpected performance issues when using the logger + loading pages, uBO settings, etc., so I would expect your 2021 8-core SD730 to [perform even better](https://nanoreview.net/en/soc-compare/qualcomm-snapdragon-820-vs-qualcomm-snapdragon-730).

Maybe check if you have enough free storage on your phone -- if uBO is unable to persist the result of parsing/compilation, it would need to repeat these every time it want to reload the filter lists.

**Comment by gwarser** [comment]
I have Redmi Note 10 Pro (6GB RAM, Android 13) which appears to have the same specification as Motorola Moto G40 Fusion and I don't see any issue.

**Comment by gwarser** [comment]
Maybe create issue on Firefox Bugzilla and ask them what can be the issue? They should be better in deciphering the profiling data.

**Comment by gorhill** [comment]
> still i'll try to inform bugzilla

Why? You say you do not have any issue with other blockers, no point bothering them with a uBO-specific issue.

I just don't know why this happens on your side. Whoever is welcome to contribute investigation.

**Comment by gorhill** [comment]
In your second profiling session, you installed uBO, _un-installed it_, then re-install again. As already pointed out, there is a lot of work to do at install time, and doing this repeatedly is not a realistic scenario.

The work done at install time is for the sake of loading fast all the subsequent times uBO will be launched -- so it's not something that will change, the priority is for uBO to load efficiently every time it will be launched once its installed.

This is how profiling looks like when launching AdGuard:
![a png](https://github.com/user-attachments/assets/9f35c5e7-7c89-4fa6-bb27-715fc74113ea)

This is how profiling looks like when launching uBO, using same scale as above:
![b](https://github.com/user-attachments/assets/fa894502-dfbf-4542-968d-2e4c4266e72d)

I didn't test the scenario of installing and trying to immediately access the logger etc. I tested doing those things with an already installed uBO.

If for you install time performance has priority over everything else, then your only solution is to use a blocker which you say perform better at install time if it's what matters the most to you.

**Comment by gwarser** [comment]
https://share.firefox.dev/3VsCSNl

The blank page you see in the first row of the screenshots actually has a loading bar on top. Even if it looks like resources are used even more than in OP profiling, I have no issue accessing any menus or uBO popups - they may load progressively, but it's fast. The first time I tried to open uBO popup for opened Carrefour page, the uBO icon was yellow.

The `SHMEM_` IPC is shorter on my side - no idea what it means.  
GPU Process Renderer is pretty much empty on my side.

**Comment by stephenhawk8054** [comment]
My uBO dev build on android recently got blank settings page quite frequently. It goes away if I clear Firefox' cache via android's app settings, although the cache is usually quite small (300-400 KB).

Not sure how to debug it.

**Comment by gorhill** [comment]
Did you wait to see if the blank setting page eventually get filled? When such page opens, it queries for data from uBO's background page, and maybe sometimes it may have to wait longer than usual before the background page sends the data to be used to fill the page.

**Comment by stephenhawk8054** [comment]
> Did you wait to see if the blank setting page eventually get filled?

I did see that after clearing the cache, but I remembered I waited quite long time before clearing the cache but nothing happens. I'll check if I encounter it again. I'm setting Firefox to "Delete browsing data on quit" btw so I can only reproduced it when opening the browser from start.

**Comment by gorhill** [comment]
> I can only reproduced it when opening the browser from start.

Is it with a uBO's dashboard page already opened as part of the session? I suppose it's possible the dashboard page is loaded way before the uBO's background page is launched, in which case the query is lost and no answer is ever received.

**Comment by stephenhawk8054** [comment]
> Is it with a uBO's dashboard page already opened as part of the session?

No it's not. Actually I just remember that it happened when the page opening is private mode, aka I browsed websites using private mode then quit Firefox and later when I opened Firefox again, it opened as private mode page first.

I rarely used normal mode so I haven't reproduced with normal mode yet. The 2 times I saw the blank page, it's when Firefox being in private mode.

**Comment by gorhill** [comment]
The particularity with private mode is that uBO will be unable to fetch data from its indexedDB storage, and should fall back to using its extension storage -- everything persisted into the indexedDB is also mirrored into the extension storage to accound for such cases. I supposed the fallback code is not a code path often tested, maybe there is something unforseen with it, though I am pretty sure I tested all this with Chromium in a private window.

**Comment by stephenhawk8054** [comment]
I'm setting Firefox to delete all data when quitting. Not sure if it affects extensions' storages (I doubt that though)? These are what I checked when deleting the data

<details>

![image](https://github.com/user-attachments/assets/3f77b22e-be18-472b-9ba0-8aa2c3d211b0)

</details>

**Comment by gorhill** [comment]
Extension storage is excluded from this.
