### ISSUE TITLE
Specific filter list has no rules loaded unless its URL is changed to be the same when parsed but different when in plaintext

### ISSUE THREAD

**Issue by npxl32** [uBlockOrigin/uBlock-issues#3476]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

[This specific filterlist](https://easylist-downloads.adblockplus.org/exceptionrules.txt) - a.k.a., this specific filter list (the problem 
only happens with this one) - will not be loaded at all in uBO. it will get added as a custom filter list but 0 filters will be recognized. However, it WILL load if I change the URL to be the same when parsed but different in plaintext (e.g. Doing weird path name trickery tricks [https://easylist-downloads.adblockplus.org/.%2E/exceptionrules.txt](https://easylist-downloads.adblockplus.org/.%2E/exceptionrules.txt), including the port number [https://easylist-downloads.adblockplus.org:443/exceptionrules.txt](https://easylist-downloads.adblockplus.org:443/exceptionrules.txt))

### A specific URL where the issue occurs.

```yaml
extension://odfafepnkmbhccpbejgmiehpchacaeak/dashboard.html#3p-filters.html
```

### Steps to Reproduce

1. Add [this filter list](https://easylist-downloads.adblockplus.org/exceptionrules.txt) into uBO
2. Watch 0 out of 0 filters be recognized 

### Expected behavior

1. Add [this filter list](https://easylist-downloads.adblockplus.org/exceptionrules.txt)
2. Watch the full ~600k filters be recognized

### Actual behavior

1. Add [this filter list](https://easylist-downloads.adblockplus.org/exceptionrules.txt)
2. 0 out of 0 filters were recognized

Workaround: 
1. Add the filter list, but do something to make the parsed URL same but plaintext URL different (e.g. including the 443 port number)
2. It works

### uBO version

1.61.2

### Browser name and version

Microsoft Edge Dev 133.0.2992.0

### Operating System and version

Microsoft Windows Version 23H2 (OS Build 22631.4541) © Microsoft Corporation. All rights reserved.

**Comment by stephenhawk8054** [comment]
Because it's in badlists: https://github.com/uBlockOrigin/uAssets/blob/master/filters%2Fbadlists.txt#L25

**Comment by npxl32** [comment]
Thanks for the clarification, this should really be in the wiki or something

**Comment by stephenhawk8054** [comment]
From that list's description, it's for ["Acceptable Ads" program](https://acceptableads.com/) and [uBO does not support "Acceptable Ads" program](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md)

**Comment by npxl32** [comment]
`        // Ignore really bad lists.
        if ( this.badLists.get(url) === true ) { continue; }
`
This line of code clearly isn't doing its job if I'm able to bypass it like this (see workaround)

In such a high quality program such as uBO, if only that snippet of code which is clearly an afterthought would actually parse the URL like so, that would be nice.

`        // Ignore really bad lists.
        if ( this.badLists.get(new URL(url).href) === true ) { continue; }
`

**Comment by stephenhawk8054** [comment]
Yes, we don't lock users to not use those lists 100%. Any users who want to use those lists at all costs can find a way themselves. We'll just lock specific workaround-URL if the URL appears on the reports from users and cause issues.

**Comment by freezer2022** [comment]
> npxl32: or something

It is mentioned in several places. Duplicate of:
- (an issue) https://github.com/uBlockOrigin/uBlock-issues/issues/1331 
- (a discussion) https://github.com/uBlockOrigin/uBlock-issues/discussions/2528#discussioncomment-5223264
- (a release notes) https://github.com/gorhill/uBlock/releases/tag/1.30.0: 

>    - The concept of "bad list" has been introduced, to prevent users from unwittingly end up using what are deemed ["bad lists" by the uBO team](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt). Some "bad lists" will be completely ignored and importing them will be forbidden by uBO. This restriction can be bypassed by users by simply appending a dummy query parameter to the URL of the list.
>    - [Add support for blocklist of filter lists](https://github.com/gorhill/uBlock/commit/23f08f027460b5d0c0436357f866d6c48b8df701)
>    - [Add concept of "really bad list" to badlists infrastructure](https://github.com/gorhill/uBlock/commit/4150c17f4a6e1b3bd0c68b91da74c358a92c03ad)

<hr>

> npxl32: "0 out of 0"

When searching for: "0 out of 0" it finds `#1331`: [LINK](https://github.com/uBlockOrigin/uBlock-issues/issues?q=sort%3Aupdated-desc+is%3Aissue+%220+out+of+0%22).

> npxl32: [This specific filterlist](https://easylist-downloads.adblockplus.org/exceptionrules.txt)

When searching for `https://easylist-downloads.adblockplus.org/exceptionrules.txt` it finds it in badlists: [LINK](
https://github.com/search?q=org%3AuBlockOrigin%20https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fexceptionrules.txt&type=code).
Then when searching for `badlists`, it finds `#2582`: [LINK](https://github.com/search?q=repo%3AuBlockOrigin%2FuBlock-issues+badlists&type=discussions)


> npxl32:  this should really be in the wiki 

The previous user asked the same: https://github.com/uBlockOrigin/uBlock-issues/issues/1331#issuecomment-723500789. 

Yes, it seems it should be in Wiki, because:
- some users can't handle github search feature
  - and even for those who can handle it, it might be too much time consuming / impractical
- for some other users it might be too complicated to understand all the technical details, becase they might be unfamiliar with uBO (especially new users)

Hence Wiki has been updated: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#unsupported-filter-lists-bad-lists

**Comment by npxl32** [comment]
> It is mentioned in several places. Duplicate of:
 > * (an issue) [Adblockplus filter list does not seems to work #1331](https://github.com/uBlockOrigin/uBlock-issues/issues/1331)

It didn't occur to me at the time of this issue that there may have been several "nonworking" filterlists beyond exceptionrules, so it didn't occur to me when searching for duplicates to keep that in mind, this is a bad on my part
> * (a discussion) [Why do main filters go into the custom list? #2528 (comment)](https://github.com/uBlockOrigin/uBlock-issues/discussions/2528#discussioncomment-5223264)

I didn't look in discussions, this is also a bad on my part, however doing a very rudimentary search of the discussions right now does not give results
> * (a release notes) https://github.com/gorhill/uBlock/releases/tag/1.30.0:
> > * The concept of "bad list" has been introduced, to prevent users from unwittingly end up using what are deemed ["bad lists" by the uBO team](https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt). Some "bad lists" will be completely ignored and importing them will be forbidden by uBO. This restriction can be bypassed by users by simply appending a dummy query parameter to the URL of the list.

Again, same problem 2 spots above, my bad
> > * [Add support for blocklist of filter lists](https://github.com/gorhill/uBlock/commit/23f08f027460b5d0c0436357f866d6c48b8df701)
> > * [Add concept of "really bad list" to badlists infrastructure](https://github.com/gorhill/uBlock/commit/4150c17f4a6e1b3bd0c68b91da74c358a92c03ad)

It wasn't obvious to search for "bad lists" for the same reason that it didn't occur to me that there may have been multiple "nulled-out" filterlists although that is probably a bad on my part
> 
> > npxl32: "0 out of 0"
> 
> When searching for: "0 out of 0" it finds `#1331`: [LINK](https://github.com/uBlockOrigin/uBlock-issues/issues?q=sort%3Aupdated-desc+is%3Aissue+%220+out+of+0%22).

Me being stupid
> 
> > npxl32: [This specific filterlist](https://easylist-downloads.adblockplus.org/exceptionrules.txt)
> 
> When searching for `https://easylist-downloads.adblockplus.org/exceptionrules.txt` it finds it in badlists: [LINK](https://github.com/search?q=org%3AuBlockOrigin%20https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fexceptionrules.txt&type=code).

I searched in gorhill/uBlock because I thought that that one specific list was hardcoded to not work, again, this is probably a bad on my part

Also, I believe I did search for that in the issue tracker but it just didn't yield actual answers other than "uBO doesn't support Acceptable Ads", and I mainly opened this issue not because the filter list wouldn't work but was mainly about how I thought the fact that I could work around it was unintended behavior, I may not have made that clear enough, again a bad on my part


> npxl32:  this should really be in the wiki

That's usually where I go for an unseen behavior/problem and advice
> Yes, it seems it should be in Wiki, because:
> 
> * some users can't handle github search feature
>   
>   * and even for those who can handle it, it might be too much time consuming / impractical
If you're implying I can't you're probably right

> * for some other users it might be too complicated to understand all the technical details, becase they might be unfamiliar with uBO (especially new users)

If you're implying that I'm a new user, I'm not, I'm decently familiar with how to use uBO, I've read through the entire wiki and I use dynamic filtering with uBO on hard mode
I'm just not familiar with uBO's backend

> Hence Wiki has been updated: https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#unsupported-filter-lists-bad-lists
