### ISSUE TITLE
manage firefox account : for commun device setting/ "My filters" 

### ISSUE THREAD

**Issue by fredmo** [uBlockOrigin/uBlock-issues#3477]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Hello,

I am a firefox user, I use the selector to remove element of web sites.
By doing it on my device 1, my selector filters are not applied to my others devices with the same firefox account.

Could you please manage the commun setting between all devices with the same account firefox ?

I guess, there is a option/path firefox to allow you to save setting on the firefox account / cloud .

Thank you

### A specific URL where the issue occurs.

```yaml
any
```

### Steps to Reproduce

.

### Expected behavior

By blocking 1 element on device1
If I run device2 and refresh the same web page, I should not see the element selected on the device1 , 

### Actual behavior

"My filters" are local to a device, not common to an account 

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 135
filterset (summary):
 network: 157860
 cosmetic: 55982
 scriptlet: 21632
 html: 2208
listset (total-discarded, last-updated):
 default:
  user-filters: 43-3, never
  ublock-filters: 41121-134, 1h.15m
  ublock-badware: 12379-1, 1h.15m Δ
  ublock-privacy: 1606-22, 1h.15m Δ
  ublock-unbreak: 2589-1, 1h.15m Δ
  ublock-quick-fixes: 210-6, 1h.15m Δ
  easylist: 77697-202, 5d.1h.27m
  easyprivacy: 53283-69, 5d.1h.27m
  urlhaus-1: 21535-0, 23h.6m
  plowe-0: 3538-991, 12h.33m
  FRA-0: 25734-397, 3d.11h.31m
filterset (user): [array of 43 redacted]
trustedset:
 removed:
  chrome-extension-scheme
  moz-extension-scheme
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1866 ms (selfie)
 maxAssetCacheWait: 61 ms
 cacheBackend: indexedDB
```
</details>

**Comment by u-RraaLL** [comment]
https://github.com/gorhill/uBlock/wiki/Cloud-storage though it's mostly manual (read inside for reasoning).

It will now work on mobile because mobile FF doesn't sync extensions settings yet.
