### ISSUE TITLE
Extension Unload after app switch for some time for Microsoft Edge Canary on ANDROID

### ISSUE THREAD

**Issue by trcrsired** [uBlockOrigin/uBlock-issues#3478]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I guess Android does background process killing that killed the ublock origin's process, but ublock origin does not reload

### A specific URL where the issue occurs.

```yaml
everywhere
```

### Steps to Reproduce

install extension

### Expected behavior

reload after app switch

### Actual behavior

extension disappears, needs to reload manually

### uBO version

latest

### Browser name and version

Microsoft Edge Canary Android

### Operating System and version

All android versions

**Comment by stephenhawk8054** [comment]
Edge android is not officially supported.

**Comment by gorhill** [comment]
Right, Edge Android is not officially supported -- and as far as I know, Edge itself does not officially support uBO.

Additionally, Canary channel of Chrome/Edge is not supported here, too unstable.

**Comment by trcrsired** [comment]
https://www.youtube.com/live/6lYi5HbmcbE?si=YCytpl0w5LvpHMxT

**Comment by trcrsired** [comment]
> Right, Edge Android is not officially supported -- and as far as I know, Edge for Android itself does not officially support uBO.
> 
> Additionally, Canary channel of Chrome/Edge is not supported here, too unstable.
> 
> How did you install uBO on Edge Canary on Android? I just installed it and there is no choice to install uBO.

you need to enter developer mode by clicking the version number of edge in the setting for 5 times

**Comment by trcrsired** [comment]
> Right, Edge Android is not officially supported -- and as far as I know, Edge for Android itself does not officially support uBO.
> 
> Additionally, Canary channel of Chrome/Edge is not supported here, too unstable.
> 
> How did you install uBO on Edge Canary on Android? I just installed it and there is no choice to install uBO.

Google Chrome on Android does not support extensions. Microsoft Edge supports it

**Comment by freezer2022** [comment]
https://github.com/gorhill/uBlock/wiki/About-Safari-and-Canary-support#canary 

Also the extension support in Edge Mobile is still somewhat experimental (that's why it's still hidden behind a flag), which means it can be unstable either.

**Comment by gwarser** [comment]
What device do you have? On this list https://dontkillmyapp.com/ ?

**Comment by gorhill** [comment]
Anyways, Chromium-based browsers should be assumed to be less and less compatible with MV2 extensions, and especially content blockers. Best is that you try uBO Lite. Firefox foes not suffer issues because it was designed to properly suspend/wake up extensions (<see https://github.com/uBlockOrigin/uBlock-issues/issues/2969>), while Chromium-based browsers have never been compatible with this. uBO Lite is MV3 and as such compatible with suspend/wake up.
