### ISSUE TITLE
Layout problem in the strict blocking warning page on Firefox for Android

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uBlock-issues#348]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

For some (long?) links, the layout of strict blocking warning page messes up in a way that buttons become too small and their text overflows or gets hidden, font size becomes large, filter homepage icon size becomes tiny, etc.

If `Settings` > `Accessibility` > `Use system font size` is disabled in Firefox, the problem goes away. But this particular setting has absolutely no effect on the layout of any other page / tab / interface of uBO. There is proper consistent behavior all across uBO *regardless of this setting* except for the warning page.

### A specific URL where the issue occurs

`https://en.softonic.com/articles/robot-revolts-on-the-international-space-station`

### Steps to Reproduce

1. Enable Dan Pollock's hosts file filter.
2. Disable `Settings` > `Accessibility` > `Use system font size` in Firefox.
3. Open `softonic.com` and see there's no layout problem.
4. Open `https://en.softonic.com/articles/robot-revolts-on-the-international-space-station` and see there's no layout problem.
5. Enable `Settings` > `Accessibility` > `Use system font size` in Firefox.
6. Open `softonic.com` and see there's no layout problem.
7. Open `https://en.softonic.com/articles/robot-revolts-on-the-international-space-station` and see there's a layout problem.

### Expected behavior:

![sse](https://user-images.githubusercontent.com/43062185/50247519-14f9c300-03fe-11e9-8aa1-f62839aa5b46.png)

### Actual behavior:

![ssa](https://user-images.githubusercontent.com/43062185/50247537-1e832b00-03fe-11e9-86ad-0cc96b89da18.png)

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox for Android 64.0.1
* Operating System and version: Android 8.1

**Comment by gorhill** [comment]
> on my phone page must be scrolled to access buttons

My phone is not old and I also have to scroll a bit to reveal completely the buttons. I read a bit about `<meta viewport>` and I will try using `height=device-height`, if I understand correctly this should fix this.

**Comment by gwarser** [comment]
Maybe you should make warning sign image smaller?

**Comment by gorhill** [comment]
I reduced the size of the font when height is constrained, seems to work fine using the device emulator in the browser dev tools.
