### ISSUE TITLE
I see no difference when "[x]Hide placeholders of blocked elements" is checked or not.

### ISSUE THREAD

**Issue by user0022** [uBlockOrigin/uBlock-issues#3485]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hello!
I use uBO with Firefox 128.5 ESR and Snap 133, under Lubuntu 22.04 OS.

And in Settings tab I use the **[x] Block media elements larger than [5  ] KB** feature.
So when an image is blocked, I see a placeholder (a square of small red dots, or a "no image" icon...).
When I also have **[x]Hide placeholders of blocked elements** checked (on top of the page of the Settings tab), I imagine these placeholders would totally disappear, but on any page, they are still here.
This is not how I would personnally want to use it, as I prefer to have a placeholder to click on to load missing images sometimes, but it looks like a bug to me?

Remark:
**I checked  "[x] I verified that this is not a filter list issue (...)" because otherwise it seemed that I couldn't post the issue, but in fact didn't do the thing as I didn't really understand it but didn't have the impression that the problem came from here.**
But I made all other verifications, in 128 ESR, and in Snap 133 when creating a new profile was needed.

### A specific URL where the issue occurs.

```yaml
Seen everywhere, just a random example:
https://en.wikipedia.org/wiki/Pythagoras
```

### Steps to Reproduce

1. In Settings tab, check **[x] Block media elements larger than [...] KB**, and choose a small limit, like 5KB.
2. In the same tab, have unchecked **[ ]Hide placeholders of blocked elements**
3. Go to a random URL, where the page contains images, and see that there are placeholders for blocked images.
4. Check **[x]Hide placeholders of blocked elements**
5. Go to another random page with images, and see that placeholders are still here, so not hidden. 

### Expected behavior

When **[x]Hide placeholders of blocked elements** is checked, placeholders should disappear, and their space collapsed.

### Actual behavior

Placeholders are still here.

### uBO version

1.61.2

### Browser name and version

Firefox 128.5 ESR and Snap 133.

### Operating System and version

Lubuntu 22.04.

**Comment by gwarser** [comment]
If an item is hidden, you won't be able to click on it to unlock it, as you noticed. This works as expected.

**Comment by gorhill** [comment]
> but it looks like a bug to me?

No, it's how it works. This won't change.
