### ISSUE TITLE
v1.61.2 is not available in the git repository

### ISSUE THREAD

**Issue by AlexanderS** [uBlockOrigin/uBlock-issues#3486]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [ ] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [ ] using a new, unmodified browser profile.

### Description

The current version (v.1.61.2) is not part of any branch of the git repository.

### A specific URL where the issue occurs.

https://github.com/gorhill/uBlock/tree/1.61.2 (Please look at the notification of github at top of the page)

### Steps to Reproduce

```
$ git clone https://github.com/gorhill/uBlock.git
$ git checkout 1.61.2
error: pathspec '1.61.2' did not match any file(s) known to git
```

### Expected behavior

The version should be available via git clone.

### Actual behavior

The commit and tag is not available.

### uBO version

1.61.2

### Operating System and version

Debian GNU/Linux 11

**Comment by gorhill** [comment]
I have no problem checking it out. Be sure you got all the tag references: `git fetch --tags`.

**Comment by gwarser** [comment]
Or clone + switch in one command:

     git clone --branch <tag_name> <repo_url>
