### ISSUE TITLE
Improvement on selection of Logger filters eventful/blocked/allowed

### ISSUE THREAD

**Issue by iology** [uBlockOrigin/uBlock-issues#349]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

![logger](https://user-images.githubusercontent.com/585534/50184153-34033280-02e2-11e9-9700-5079dbda00f0.png)

It is nice to gray out "blocked" and "allowed" when "eventful" is selected, so the application scope of "eventful" will be clearer.

### Your environment

* uBlock Origin version: 1.17.5b13
* Browser Name and version: Chrome 73.0.3642.0
* Operating System and version: MacOS 10.11.6

**Comment by gorhill** [comment]
When I added "eventful", I had in mind that the logger showed eventful entries other than "blocked" and "allowed" (for example invalid filter warnings). In practice though, not so sure it is really needed -- I am considering removing it to keep it simpler.

**Comment by gorhill** [comment]
The "eventful" button has been removed, rendering this issue obsolete.
