### ISSUE TITLE
youtube ad blocker blocker not going away

### ISSUE THREAD

**Issue by neuromator** [uBlockOrigin/uBlock-issues#3493]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

youtube ad blocker filter is no longer working

### A specific URL where the issue occurs.

```yaml
youtube.com
```

### Steps to Reproduce

go to youtube .com with an ad blocker

### Expected behavior

block the ad blocker

### Actual behavior

youtubes ad blocker keeps coming up, purge all cache does not work, neither does updating filters

### Configuration

<details>

```yaml
uBlock Origin: 1.61.2
Firefox: 115
filterset (summary):
 network: 153332
 cosmetic: 169784
 scriptlet: 36282
 html: 2505
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 32835-1682, 2m
  ublock-cookies-adguard: 1985-21, 2m
  fanboy-cookiemonster: 51647-19364, 2m
  ublock-cookies-easylist: 1985-1984, 2m
  adguard-social: 23273-1234, 2m
  fanboy-social: 16505-10108, 2m
  fanboy-thirdparty_social: 68-19, 2m
  adguard-popup-overlays: 28114-2178, 2m
  adguard-mobile-app-banners: 5600-46, 2m
  adguard-other-annoyances: 14421-392, 2m
  adguard-widgets: 2811-56, 2m
  easylist-annoyances: 4732-1118, 2m
  [4 lists not shown]: [too many]
 default:
  user-filters: 1-0, never
  ublock-filters: 41014-327, 3m
  ublock-badware: 12530-13, 2m Δ
  ublock-privacy: 1662-24, 3m
  ublock-unbreak: 2603-2, 3m
  ublock-quick-fixes: 179-8, 3m
  easylist: 78083-14258, 2m Δ
  easyprivacy: 53328-75, 3m
  urlhaus-1: 24920-0, 3m
  plowe-0: 3548-995, 3m
filterset (user): [array of 1 redacted]
userSettings:
 autoUpdate: false
 ignoreGenericCosmeticFilters: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 83464 ms
 maxAssetCacheWait: 1343 ms
 cacheBackend: indexedDB
```
![2021-08-17 (1)](https://github.com/user-attachments/assets/127d65b2-15ca-4c09-9a12-d13b663d2683)

![2021-08-17 (1)](https://github.com/user-attachments/assets/85119626-63c9-4458-b86f-c8c7b105c9e0)

</details>/?

**Comment by poolenius** [comment]
same  problem

**Comment by Marakai** [comment]
same here, as of this morning my local time. looks like the war has flared up again?

**Comment by neuromator** [comment]
Yea its pissing me off. Theres another youtube ad blocker blocker, but its not the same. Opens up a secondary window. Not sure what is going on. But seems yutube, didnt learn from the last time we kicked their asses.

**Comment by Darby-Green** [comment]
same problem :(

**Comment by boykokanev** [comment]
Same, as of a few minutes ago.

**Comment by SenaDevGH** [comment]
idem, here.

**Comment by chuimoi** [comment]
adguard actually don't have this problem

**Comment by neuromator** [comment]
seems youtube is detecting it Ill try out adguard yo
