### ISSUE TITLE
why "AdGuard English filter" isn't treated as a regional filter?

### ISSUE THREAD

**Issue by xqk94524** [uBlockOrigin/uBlock-issues#35]
The filter list AdGuard English filter, was named as Adguard Base Filters on the UBO, but the description of this list is.

'Filter list that specifically removes adverts on English language websites. English filter is supposed to work along with EasyList.'

why not use the original name and catalogue this list like a regional filter, instance of a 'base' list, because this can take the user to mistake the usage of this as a necessary list

**Comment by uBlock-user** [comment]
Because English is not limited to one region or a country and can be used around the world.

**Comment by gorhill** [comment]
<https://github.com/AdguardTeam/AdguardFilters/issues/5138#issuecomment-309683940>:

> Yes, it is generic. We are actually considering renaming it into "Adguard Base filter + EasyList" just to make it clear.
