### ISSUE TITLE
Element picker does not work on quotenmeter.de

### ISSUE THREAD

**Issue by Gittyblue** [uBlockOrigin/uBlock-issues#3501]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hey, I want to remove certain parts on quotenmeter with the element removal feature. But on that website it does not work.
The element picker only wants to remove "||www.quotenmeter.de/cms/www/css/img/bg_pageborder.png" which does not work.
Actually the element picker works on the mobile website (m.quotenmeter.de), but not on the desktop version.

### A specific URL where the issue occurs.

```yaml
www.quotenmeter.de
```

### Steps to Reproduce

1. Use the element picker
2. click anywhere on quotenmeter.de
3. the tool wants to remove "||www.quotenmeter.de/cms/www/css/img/bg_pageborder.png"
4. click on create
5. nothing happens

### Expected behavior

It should remove the selected parts of the website

### Actual behavior

it does not remove anything

### uBO version

1.61.2

### Browser name and version

Chrome 131.0.6778.205

### Operating System and version

Windows 10 Pro 22H2

**Comment by gorhill** [comment]
> nothing happens

> It should remove the selected parts of the website

The element picker offers you a choice of things to select, and by default selected the image resource used as background image, as shown in the logger after reloading the page:

![image](https://github.com/user-attachments/assets/35a52c0f-6465-4615-a6e5-ca11ce92b9aa)

The element picker can't read mind and know exactly what you intend to remove, it just collects a set of potential candidates and let you further pick or narrow down by clicking on the actual entries offered as choice.

> click anywhere on quotenmeter.de

Clicking anywhere makes it impossible to know exactly what you actually wanted to remove.

Documentation about element picker: https://github.com/gorhill/uBlock/wiki/Element-picker

Small video showing how to pick different candidates according to what you want to accomplish: https://www.youtube.com/watch?v=8TvCGWwQr5o

**Comment by Gittyblue** [comment]
I know how to use the element picker. I used it in for a lot of website. Just on this website it does not work.

You did not understand my request, you didn't wait for my reply and that's why you immediatly set the whole request to "invalid"?

**Comment by gorhill** [comment]
I tried the step to repro, a filter was created and the logger output I screenshot is the proof. You said "nothing happened", I just provided a proof that something happened. Provide more exact details, don't use "click anywhere" and "nothing happened", or "parts of the website". Click where exactly? What exactly did you expect to happen according to where you clicked? Which exact part of the website? (use screenshots to make things more clear if needed).

**Comment by Gittyblue** [comment]
I wanted everything with the pink colored selection to be removed. Usually it works this way with the element picker.
For example the "XMAS24" word on the top left side. When selecting "XMAS24" Ublock only wants to remove "www.quotenmeter.de/cms/www/css/img/bg_pageborder.png" which does not work. Nothing is removed after creating a filter for "bg_pageborder.png".

Actually it works as I wanted when selecting one of the other options in the "cosmetic filters". Doing that extra step was not necessary for other websites.

**Comment by gorhill** [comment]
> Ublock only wants to remove `www.quotenmeter.de/cms/www/css/img/bg_pageborder.png`

uBlock does not want to remove anything, it just suggests a choice among many. If you are not happy with the default choice, click another one among the list shown in the picker, these extra entries are there exactly for this reason, to let you tell uBO exactly what you want to remove -- as pointed out in the first comment above:

![image](https://github.com/user-attachments/assets/f959cc81-09bc-4f58-b0d7-1e661e8bebd7)

**Comment by Gittyblue** [comment]
okay. Mission accomplished, same as for other websites which want to much attention.

![2](https://github.com/user-attachments/assets/70756679-9092-4100-823c-7104d984604d)
![1](https://github.com/user-attachments/assets/dde499d6-76b1-46b0-83fd-2a2dc895dabe)
![3](https://github.com/user-attachments/assets/4b745625-fa5d-45d2-adc3-1ec0e9e8b344)
![4](https://github.com/user-attachments/assets/133701ed-c955-42e9-b334-5afb0409dde8)
![5](https://github.com/user-attachments/assets/145bb15b-70a5-4b56-8782-a87bcc5f261a)
