### ISSUE TITLE
blocking cookies files

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#352]
When visiting questionable sites there is an urgent need to block (install) cookies. ESPECIALLY when you CONSIDER THAT MANY SITES USE COOKIES FOR ADVERTISING (for example twitch.tv or facebook.com). It would be just wonderful to see the variable $cookie (or something like that) + line on the Dashboard.

Right now, the AutoDelete Cookie extension saves me, but I would refuse it if you added This feature.
uMatrix has it a great feature, how about move it and ublock0?
ps: I gave up Umatrix because it is very difficult to open EACH domain + you do not often update this extension, all free time goes to ublock0, so that

what do you think?

**Comment by uBlock-user** [comment]
That guy was asking for selectively disabling the cookies, I don't see that here, otherwise I would have closed on the account of being a duplicate.

**Comment by gorhill** [comment]
"Cookies" can be created through HTTP response's `Set-Cookie` header, or through JavaScript.

You can block "cookies" from a given domain by outright blocking everything from that domain.

If created through JavaScript, "blocking cookies" is pointless, because the code can as well use any of the local storage to store whatever it wants to store, so focusing on cookies is not going to be useful.

If you want to block only certain cookies without blocking all from a given domain, than that is what cookie manager extensions are for.

Arguing that you want the feature because it would make one less extension to install will never be accepted, these are invalid arguments.

Cookies managers specialize in what they do and thus it's best to stick with them to do that job.

**Comment by bogachenko** [comment]
@gorhill 
> If created through JavaScript, "blocking cookies" is pointless, because the code can as well use any of the local storage to store whatever it wants to store, so focusing on cookies is not going to be useful.

_sorry for the stupid question, but can't you disable local storage for sites, if I do not have Alzheimer's, then in umatix you disabled it ALONG with cookies?_

Well, for some reason it uses cookies. I debated with ur friend @gwarser on reddit, when the twitch advertising began to depend on the cookie files, everyone shouted that they had an advertisement. And they watched her lol. and could not block it (well, then you still beat her). However, I made it easier, I installed umatrix and blocked the cookie, and at the same time I was still logged in, which is strange. advertising was not. it was fucking **great**.

a bunch of Slovak sites, for example this https://novinky.cz where advertising also depends on cookies. And the Slovaks, too, are yelling that they cannot defeat her. and to defeat it you only need to block cookies on this site

***
> "Cookies" can be created through HTTP response's Set-Cookie header, or through JavaScript.

More often the second. but when blocking js, many sites distort and break the presentation. You can get by with the exception rules and the divine file https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resources.txt
but here are two but.
1. Large companies with advertising often fix the holes you found.
2. Awesome large number of rules affect the processor.

But you can also do a little blood, like `advertising.site$cookie`

***

> You can block "cookies" from a given domain by outright blocking everything from that domain.

> everything from that domain

not what I was looking for

***
> If you want to block only certain cookies without blocking all from a given domain, than that is what cookie manager extensions are for.

again, it's not. it clutters up the browser and slows down

***

### Anyway, thanks for the reply.

**Comment by gorhill** [comment]
> MANY SITES USE COOKIES FOR ADVERTISING

Those who are genuinely concerned about this will set their browser to...

- block all 3rd-party cookies; and
- delete all cookies when quitting the browser.

Since these are browser settings, this also apply to other site storages. For what is left, 1st-party cookies, I think a cookie manager is best placed to deal with this, their UI is optimized to deal with cookies on a per-site per-cookie basis, and they allow you to block them in various ways.

**Comment by uBlock-user** [comment]
Specific first-party cookies can be expired with `cookie-remover.js` scriptlet.

**Comment by gwarser** [comment]
Will be implemented in AdGuard https://github.com/gorhill/uBlock/issues/1930#issuecomment-370276156

**Comment by bogachenko** [comment]
@gwarser I will not move from the divine ublock to the blasphemous adguard. no no no

**Comment by uBlock-user** [comment]
Well it's not a exact replacement, but it might help you out once you weed out all 3rd-party cookies by disabling them and when all is left the first party cookies to sort through.

**Comment by bogachenko** [comment]
@uBlock-user well yes. I wrote, "almost what I was looking for". it was nice to see strip on dashpanel + functional without (prior) setting userResourcesLocation will not work.
but still, at least something. I just offered and they refused me, this is not my extension, I cannot dictate terms. so that

**Comment by bogachenko** [comment]
@uBlock-user question 
by the way the question is a little distracted from my theme/
you have a repository https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt there are new / other scriptlets why you do not combine the project with @gorhill  what's the catch? I'm just curious. I visited your profile a long time ago and saw them, I wanted to write - and ask, but did not find the mail

**Comment by uBlock-user** [comment]
I just don't think he would want them, I mostly add(sometimes remove some which I fail to make some work) for myself and not for the community specifically as my scriptlets can only be used if someone adds the txt to their userResourcesLocation parameter.

**Comment by bogachenko** [comment]
@uBlock-user 

>don't think
you can just ask :relaxed:
***
and then a question (maybe stupid) how to understand what scriplet need for the problematic site?

**Comment by uBlock-user** [comment]
Start learning javascript and you will start to get ideas. Anyways, please don't ask anymore questions here as we're have gone offtopic now.
