### ISSUE TITLE
Google Project Stream detects uBlock, even if whitelisted/disabled.

### ISSUE THREAD

**Issue by Revenge282** [uBlockOrigin/uBlock-issues#353]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When performing the play test on Project Stream (does connection speed/firewall/latency/etc tests), the test will fail with general terminology.  However, this failure only occurs when uBlock is enabled in the browser (whitelisting projectstream.google.com doesn't have an effect).  Disabling uBlock through the extensions menu allows the test to pass successfully.

I have checked the log while the site was performing a test and uBlock was set to off/whitelist on the site, and all requests were allowed.

### A specific URL where the issue occurs

`https://projectstream.google.com/aco/playtest`

### Steps to Reproduce

1. Visit above site with uBlock enabled/defaults
2. Perform play test on site, which will fail.
3. Whitelist/disable site through uBlock options.
4. Repeat play test, failing again.
5. Disable uBlock through Chrome's extensions menu.
6. Repeat play test, successfully completing.

### Expected behavior:

Play test should succeed if site is whitelisted, as uBlock should, ideally, be transparent.

### Actual behavior:

Play test fails, unless uBlock is completely disabled via extension menu.

### Your environment

* uBlock Origin version: v1.17.4
* Browser Name and version: Google Chrome x64 71.0.3578.98
* Operating System and version: Windows 10 Pro build 17763

**Comment by gorhill** [comment]
@uBlock-user You verified it was a filter issue?

**Comment by uBlock-user** [comment]
Using a VPN extension with US IP, it asks for setup code and with no setup code you need to request and invite and it basically sends you on a goose chase.

**Comment by uBlock-user** [comment]
Also https://projectstream.google.com/aco/playtest redirects you to https://projectstream.google.com/aco/invite if you don't have an account.

**Comment by gorhill** [comment]
Typical filter list issues usually don't think of using the logger, while he mentioned he did. So this needs further investigation, though this will be difficult without being able to reproduce on our side.

We can narrow though. A first test would be to find out whether this happens with other blockers as well.

**Comment by uBlock-user** [comment]
Before you need an account, do you have one ?

**Comment by gorhill** [comment]
A Google account? In any case, I am still geo-blocked, and I just don't trust free VPN extensions from the store. I should be able to access a VPN later today.

**Comment by uBlock-user** [comment]
A US one perhaps, it asks for US pin code..

**Comment by uBlock-user** [comment]
Can't signup, all invites are gone -- 

![](https://i.gyazo.com/d06b2527ee92ed730246c8848dee5216.png)

**Comment by uBlock-user** [comment]
You need to provide a working existing account to actually be able to reproduce this case.

**Comment by Revenge282** [comment]
I would think this goes without saying, but I won't be providing my Google account for testing. But I'll be more than happy to follow up and test any leads or hunches that the devs may have.

**Comment by uBlock-user** [comment]
Run the logger and populate it with a refresh of the aformentioned URL page, putt --  in the filter box which will show list fo requests that are beig blocked.

**Comment by Revenge282** [comment]
WebRTC was the issue.  I apologize for not catching that at the start.  This was a fresh install of uBlock, so I guess I had it from backed up settings on my past machine and forgot to think of it.

I'm not sure on how granular the control of WebRTC can be, but could it be made to obey the whitelist settings?

**Comment by uBlock-user** [comment]
> I'm not sure on how granular the control of WebRTC can be, but could it be made to obey the whitelist settings?

Not for WebRTC, either you disable or you enable it, site specific setting is not possible.
