### ISSUE TITLE
how to restrict changing config?

### ISSUE THREAD

**Issue by vtolstov** [uBlockOrigin/uBlock-issues#355]
i want to use uBlock to disable some sites from my children notebook. How can i disable ability to change settings without some password or something like this?

**Comment by gwarser** [comment]
- Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)

>How can i disable ability to change settings without some password or something like this?

You cannot.

You can use group policies to enforce some setting on startup https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

**Comment by gwarser** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/9gf966/how_can_i_passwordprotect_ublock_origin_settings/

Removed comment proposed to use system HOSTS file.

**Comment by vtolstov** [comment]
thanks, but this is not so useful. why you don't want to create simple locking feature?
pin/pass can be synced ...

**Comment by mapx-** [comment]
You need something else, see:
https://gadgets.ndtv.com/internet/features/how-to-block-any-website-on-your-computer-phone-or-network-588357

**Comment by vtolstov** [comment]
firstly i have in all my computers linux. Next think i'm prefer to use chrome in kios mode.
Provide some proxy and other blocking features - overhead.

**Comment by gwarser** [comment]
> why you don't want to create simple locking feature?

Add-ons can be removed. Other browser profiles or even other browsers can be used. Locking settings is useless.

**Comment by gwarser** [comment]
> firstly i have in all my computers linux.

`/etc/hosts`

**Comment by uBlock-user** [comment]
A similar suggestion for locking the popup config was denied - https://github.com/gorhill/uBlock/issues/3576
