### ISSUE TITLE
Placeholders not hidden in 1.17.5rc1

### ISSUE THREAD

**Issue by quilloss** [uBlockOrigin/uBlock-issues#356]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In version 1.17.5rc1 blocked image placeholders are not hidden. Placeholders are hidden in the previous release.

### A specific URL where the issue occurs

https://mpv.io/

### Steps to Reproduce

1. Block an image
2. Reload page

### Expected behavior:

Blocked image placeholder hidden

### Actual behavior:

Blocked image placeholder not hidden

### Your environment

* uBlock Origin version: 1.17.5rc1
* Browser Name and version: Firefox 65.0b6
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Unable to reproduce, image was removed and the placeholder collapsed:

![a](https://user-images.githubusercontent.com/585534/50484322-dd6eb600-09bd-11e9-9321-2271a554a488.png)

Tested using Firefox 64 and uBO 1.17.5rc1.

**Comment by gorhill** [comment]
However, I can reproduce on Nightly.

**Comment by gorhill** [comment]
I understand why this happens, a regression. I don't understand how I could not reproduce with Firefox stable.
