### ISSUE TITLE
Network filtering instability

### ISSUE THREAD

**Issue by TheMather1** [uBlockOrigin/uBlock-issues#357]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Sometimes network filters fail to fully block requests, even when the logger notes the request as blocked.

It appears this issue may be related to the priority of uBlock Origin's extension process, as disabling and reenabling my other extensions made the issue go away.
However as the issue occurred identically (failing to block the exact same requests) on two different computers running the same environment, it appears the symptoms are determined by uBlock's position in the load order.

### A specific URL where the issue occurs

    https://9anime.ru/

### Steps to Reproduce

1. Make a network filter, e.g: `*$script,domain=9anime.ru`
2. Watch as sometimes, requests still complete despite being shown as blocked in the logger. Evidenced by them not showing as blocked in the developer tools.

### Expected behavior:

uBlock Origin actually blocks all network requests it says it blocks.

### Actual behavior:

Network requests sometimes complete despite the logger claiming they were blocked.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Google Chrome 71.0.3578.98 (Official Build) (64-bit)
* Operating System and version: Windows 10 Pro, 64-bit

**Comment by gwarser** [comment]
I see only ReCaptcha because is whitelisted:

> 
> Static filter @@||gstatic.com/recaptcha/$script found in:
> EasyList 


and uBO war snippets.

**Comment by TheMather1** [comment]
I do have that setting enabled.

As for a screenshots, I only have one of the dev tools that I took before disabling other extensions pushed uBlock Origin to the top of the priority order, and I have not been able to force the issue to reoccur.

The issue is not caused by an allow filter, as it occured even with all lists disabled (except [one I'm authoring](https://raw.githubusercontent.com/TheMather1/9animeFilters/master/filters), hence why I'm not doing it with dynamic rules).
One specific request that it occured with was addthis_widget.js, which should have been blocked both by `$script,domain=9anime.ru` and experimentation with various variations of `addthis.com$domain=9anime.ru,important`, and which did show as red in the logger, but resulted in what you can see here in the dev tools:
![image](https://user-images.githubusercontent.com/31667042/50498529-0a64ac80-0a42-11e9-8b03-9abc2f65421c.png)

**Comment by gwarser** [comment]
> I do have that setting enabled.

Then enable this option: https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental

**Comment by TheMather1** [comment]
As nice as that setting is, I don't see how it's relevant to this issue. It's not something that only happened on browser startup, it's something that reoccurred every time the page was reloaded until disabling other extensions shifted the priority order.

**Comment by uBlock-user** [comment]
> Watch as sometimes, requests still complete despite being shown as blocked in the logger. Evidenced by them not showing as blocked in the developer tools.

![](https://i.gyazo.com/8e30c607b90ee243201c46eb4db65808.png)

**Comment by uBlock-user** [comment]
As per the image of dev-tools you posted you must have some exception filters overiding the block filter.

**Comment by uBlock-user** [comment]
> except one I'm authoring, hence why I'm not doing it with dynamic rules).

and I see it has lots of third-party exception filters, without `$important` or `$badfilter`, exception filters take priority.

**Comment by gwarser** [comment]
> One specific request that it occured with was addthis_widget.js, which should have been blocked both by `$script,domain=9anime.ru` and experimentation with various variations of `addthis.com$domain=9anime.ru,important`, and which did show as red in the logger, but resulted in what you can see here in the dev tools:

Look closely - it's loaded from cache. On the bottom, in console, you see `net::ERR_BLOCKED_BY_CLIENT`. It downloaded once, on startup, because uBO did not start soon enough, this one file slipped through, and now is loaded from cache.

Set `suspendTabsUntilReady` to true, clear your cache, and all should be OK.

**Comment by gorhill** [comment]
> One specific request that it occured with was addthis_widget.js, which should have been blocked

It is blocked. It appears not blocked in dev tools because uBO redirects it to a local neutered scripts -- pay also attention to the status code and headers if you want to really see whether a network request is blocked.

**Comment by gorhill** [comment]
> still, "size" column shows "from ..." (disk cache)]

The browser will bypass webRequest listener for the 'from memory cache" items, not disk cache ones. I see 4 "memory cache" entries in his screenshot. He should be reloading with shift-click reload.

**Comment by gorhill** [comment]
I don't see any discrepancy between the logger and dev tools. Using only OP's list in <https://github.com/uBlockOrigin/uBlock-issues/issues/357#issuecomment-450263902>, this is what I get:

![a](https://user-images.githubusercontent.com/585534/50513716-80c7d580-0a67-11e9-9145-186d245c6a93.png)

![b](https://user-images.githubusercontent.com/585534/50513717-82919900-0a67-11e9-829c-6c34a03083be.png)

There is problem with this issue:

- Speculating on top of incorrect assumptions: order of extensions is irrelevant when blocking network requests. Blocking has priority over redirecting, redirecting has priority over doing nothing.

- Not forcing a reload with a cache bypass. This is why the feature "shift-click reload" exists in uBO, to ensure the memory cache is bypassed for such cases. I see 4 entries in OP's screenshot showing they were loaded from memory cache, and this includes `addthis_widget.js`.

- Not paying attention to whether a network request appearing as not blocked while it should have was actually a redirection to a local resource.

Summary, I can't reproduce "Network filtering instability".

**Comment by uBlock-user** [comment]
The requests not blocking comes from his own list which is the cause of this issue on his end.

**Comment by gorhill** [comment]
`addthis_widget.js` was shown as not blocked in his screenshot, and his list is supposed to block it. However that item is shown as being loaded from the memory cache, that is why it was loaded, the browser bypassed uBO and loaded it. The proper solution is that when uBO's filtering profile changes, a bypass of cache when reloading the currently opened page might be necessary.

**Comment by gwarser** [comment]
> The browser will bypass webRequest listeners for the 'from memory cache" items, not disk cache ones.

OK. On screenshot this column is cut to only "from ...". For `addthis_widget.js` "Time" shows 0ms - I will assume this is "from memory cache".

**Comment by gorhill** [comment]
Yes, "m" is larger than "d", hence "from memory cache" got truncated earlier.
