### ISSUE TITLE
Domain names aren't centered vertically in the extension's browserAction popup

### ISSUE THREAD

**Issue by tophf** [uBlockOrigin/uBlock-issues#358]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Domain names aren't centered vertically in the extension's browserAction popup.

### A specific URL where the issue occurs

`https://stackoverflow.com/`

### Steps to Reproduce

1. click the extension icon
2. expand the domains panel if needed by clicking the `domains connected` label

### Expected behavior:

The domain names should be vertically centered.
![image](https://user-images.githubusercontent.com/1310400/50520454-8d811380-0ad1-11e9-901d-6f309329d664.png)

### Actual behavior:

The domain names are not vertically centered.
![image](https://user-images.githubusercontent.com/1310400/50520416-3a0ec580-0ad1-11e9-8c8a-69ba8ea9dfc5.png)

### Your environment

* uBlock Origin version: v1.17.5rc2 (all versions affected AFAIK)
* Browser Name and version: Chrome 71
* Operating System and version: Windows 7

---

FWIW, hiding `<sup>` or forcing it to be centered via CSS in devtools inspector fixes the issue:

```css
sup {
  vertical-align: middle;
}
```

**Comment by uBlock-user** [comment]
Don't see the difference, and this has always been the case, so not a bug. I will put it under suggestion.

**Comment by tophf** [comment]
FWIW the difference in the attached images is pretty obvious.

**Comment by uBlock-user** [comment]
> difference in the attached images is pretty obvious.

Not to me. I don't see the domains centred or change position vertically.. Post a bigger screenshot.

**Comment by uBlock-user** [comment]
Ah, I see now. You mean in the centre of line-height ?

**Comment by gwarser** [comment]
It's the `<sup>` element pushing it down. Probably IDN indicator.

**Comment by gorhill** [comment]
With `vertical-align: middle` you end up with this though:

![a](https://user-images.githubusercontent.com/585534/50522491-33fcf280-0a99-11e9-8784-03f8e4704c09.png)

**Comment by gorhill** [comment]
Is this a Windows-specific quirk? On my side it makes no difference whether the `sup` is in there or not.

**Comment by gorhill** [comment]
Can you try `https://www.аррӏе.com/` and post a screenshot of how it looks on your side? I suspect your `sup` is larger than what I get on my side.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/50523272-7a6d4400-0acf-11e9-957a-f3604337933f.png)

Manjaro KDE Chromium 71.0.3578.98

**Comment by gorhill** [comment]
I get this on my side:

![a](https://user-images.githubusercontent.com/585534/50523337-90621100-0a9d-11e9-9e18-e582c8e464bb.png)

**Comment by gorhill** [comment]
Ugh, never mind, the whole time I was testing on Nightly... Yes, on Chromium I get the off-centered issue.

**Comment by gorhill** [comment]
Assigning `line-height: 1;` to the `sup` solves the issue.

**Comment by gorhill** [comment]
The reason the issue does not exist on Firefox is because in Firefox there is a user agent style to reset the `line-height` property.
