### ISSUE TITLE
Cleanup few titles in assets.json

### ISSUE THREAD

**Issue by MindTooth** [uBlockOrigin/uBlock-issues#359]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Just wanted to submit some title changes for the built-in asset list, but were unable to submit the PR.  Therefore I'm opening this.  Regarding the AdGuard names in the `assets.json` file.

And having three places to get to the project is just weird.  Even not sure of this is the right place..

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/assets/assets.json

### Steps to Reproduce

1. Open settings
2. Navigate to Filter lists
3. Find the names to be wrong

### Expected behavior:

Correct spelling, or at least be of the same style.

### Actual behavior:

They are not.

### Your environment

* uBlock Origin version:  v1.17.4
* Browser Name and version: Firefox 64
* Operating System and version: macOS Mojave

Patch:
```
diff --git a/assets/assets.json b/assets/assets.json
index abda9179..05e90665 100644
--- a/assets/assets.json
+++ b/assets/assets.json
@@ -103,7 +103,7 @@
 		"content": "filters",
 		"group": "ads",
 		"off": true,
-		"title": "Adguard Base Filters",
+		"title": "AdGuard's Base Filter",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
 		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
@@ -112,7 +112,7 @@
 		"content": "filters",
 		"group": "ads",
 		"off": true,
-		"title": "Adguard Mobile Filters",
+		"title": "AdGuard's Mobile Filter",
 		"ua": "mobile",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/11.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
@@ -135,7 +135,7 @@
 		"content": "filters",
 		"group": "privacy",
 		"off": true,
-		"title": "Adguard Spyware Filters",
+		"title": "AdGuard's Spyware Filter",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/3.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
 		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
@@ -205,7 +205,7 @@
 		"content": "filters",
 		"group": "social",
 		"off": true,
-		"title": "Adguard’s Annoyance List",
+		"title": "AdGuard’s Annoyance Filter",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/14.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
 		"instructionURL": "https://kb.adguard.com/en/general/adguard-ad-filters"
@@ -474,7 +474,7 @@
 		"content": "filters",
 		"group": "regions",
 		"off": true,
-		"title": "JPN: Adguard Japan Filter",
+		"title": "JPN: AdGuard's Japan Filter",
 		"lang": "ja",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/7.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
@@ -582,7 +582,7 @@
 		"content": "filters",
 		"group": "regions",
 		"off": true,
-		"title": "RUS: Adguard Russian Filter",
+		"title": "RUS: AdGuard's Russian Filter",
 		"lang": "be ru uk",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/1.txt",
 		"supportURL": "https://forum.adguard.com/forumdisplay.php?69-%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D1%8B-Adguard",
@@ -592,7 +592,7 @@
 		"content": "filters",
 		"group": "regions",
 		"off": true,
-		"title": "spa: EasyList Spanish",
+		"title": "SPA: EasyList Spanish",
 		"lang": "es",
 		"contentURL": "https://easylist-downloads.adblockplus.org/easylistspanish.txt",
 		"supportURL": "https://forums.lanik.us/viewforum.php?f=103"
@@ -601,7 +601,7 @@
 		"content": "filters",
 		"group": "regions",
 		"off": true,
-		"title": "spa, por: Adguard Spanish/Portuguese",
+		"title": "SPA, POR: AdGuard's Spanish/Portuguese Filter",
 		"lang": "es pt",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/9.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
@@ -638,7 +638,7 @@
 		"content": "filters",
 		"group": "regions",
 		"off": true,
-		"title": "TUR: Adguard Turkish Filter",
+		"title": "TUR: AdGuard's Turkish Filter",
 		"lang": "tr",
 		"contentURL": "https://filters.adtidy.org/extension/ublock/filters/13.txt",
 		"supportURL": "https://github.com/AdguardTeam/AdguardFilters#adguard-filters",
```

**Comment by uBlock-user** [comment]
Any other list name changes ?

**Comment by MindTooth** [comment]
Guess there are some.  Should I address/submit those?

Having `Filter` in the names, when they are in fact all filters, etc.

**Comment by gorhill** [comment]
`spa`, `por` are lower-cased because they are languages, not countries.

**Comment by gorhill** [comment]
Also, expect for the convenient country- or language-based prefixes, I use the title as it appears in the filter list, I do not want to second-guess the list's name, hence why I used `TUR: Adguard Turkish Filter` and not `TUR: Adguard's Turkish Filter`.

**Comment by MindTooth** [comment]
Oh well then.  At least I fought for cleanliness.

Thanks for replying.
