### ISSUE TITLE
whitelist and rules for one SPECIFIC page

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#361]
Hi everyone

How to disable uBlock0 on a particular page? Let's say I don't like the guy on YouTube (or Twitch?) and I want to thank him, but not with money, but with watching ads. How do I disable only this page and not any other? And in General, is it possible to add the function(s) of adding rules(filters) for only one page?
For example: on `site.domain/page` there is bullshit that I want hide (often this cosmetic filters!), I press "eyedropper" to select items. Choose. Is obtained, that the type `site.domain##div`. But this is the rule for the entire domain, and when you go to the home page of the site and there will be a hidden `div`. But it's wrong, it's not right.

What about:
`site.domain/page##div`
it looks funny, but it's something like that

so you say @gorhill 

![default](https://user-images.githubusercontent.com/8535285/50620768-8c2e6b80-0f55-11e9-8995-062afee68c59.png)

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

> Support issues and questions are handled at /r/uBlockOrigin.
