### ISSUE TITLE
Android/mobile compatibility

### ISSUE THREAD

**Issue by colbycdev** [uBlockOrigin/uBlock-issues#363]
I know, I know. I deleted the template. Didn't fit my issue, though.
I've noticed that on Android Firefox, ublock mobile doesn't work as well, and ublock origin isn't particularly mobile friendly. For instance, I can't select an element to block.
How I know it's not a filter issue? Both extension had same filters applied(obviously not at the same time),only origin was able to block the apkmirror cat

**Comment by uBlock-user** [comment]
> ublock mobile doesn't work as well

uBlock Mobile is not an official app/extension and not related to uBO in any way.

**Comment by gorhill** [comment]
Sounds like he got fooled into installing something else than uBO on Android. In any case, no repro steps = nothing actionable.

**Comment by uBlock-user** [comment]
He installed this [fork](https://addons.mozilla.org/en-US/firefox/addon/ublock-mobile/) which instead of "optimising" something, broke something instead 😞

**Comment by gwarser** [comment]
>and ublock origin isn't particularly mobile friendly. For instance, I can't select an element to block.

He is right. I cannot use Picker because picker dialog toggles hidden/visible when I try to tap on it. It is very small too.

**Comment by colbycdev** [comment]
I'm not using the mobile extension. And steps to reproduce? Use it on Firefox on Android.

**Comment by gwarser** [comment]
>And steps to reproduce? Use it on Firefox on Android.

Can be "first tab" again - picker does not switch back to page after selecting from "popup" icon. But this is known.

**Comment by colbycdev** [comment]
No, I mean generally. It switches back... And never let's me select.
It also insists that the lists have been updating for about two days now.
And the extension web page doesn't render well on a 480x854 phone
