### ISSUE TITLE
Optional permission 'file:///*' is redundant

### ISSUE THREAD

**Issue by 9652301** [uBlockOrigin/uBlock-issues#364]
Hello, my ublock origin reports an error, the error message is: Optional permission 'file:///*' is redundant with the required permissions; this permission will be omitted.
Please solve this problem, thank you very much!

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/commit/5c33a571581f4c77778036b03d274c3b54d87b71

Fixed is in the dev build.
