### ISSUE TITLE
Ublock can't show control panel after update

### ISSUE THREAD

**Issue by tuanden0** [uBlockOrigin/uBlock-issues#365]
After update Ublock Origin to lastest version, I can't open the panel when click on ublock icon.
I tried to remove and re-install but didn't work.

Here's image:
https://i.imgur.com/HMRGrVE.png

**Comment by gwarser** [comment]
Put back the [template](https://github.com/uBlockOrigin/uBlock-issues/blob/master/.github/ISSUE_TEMPLATE.md) and properly fill in the report.

**Comment by uBlock-user** [comment]
Will re-open when you do as gwarser instructed.
