### ISSUE TITLE
Subscribing to an existing list should activate the existing list in Filter lists tab

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#366]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`https://easylist-downloads.adblockplus.org/fanboy-cookie.txt`

https://github.com/ryanbr/fanboy-adblock/commit/f048f590f685115b7bb81071038665f812ddeb97

https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/fanboy-cookie.txt&title=Fanboy's%20Cookie%20List

> **Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.**

IMO, is not new list - obviously mirror.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior:

Subscribe links activate in `"Annoyances"` section no in "`Custom`".

### Actual behavior:

Subscribe links activate in "`Custom`" section no in `"Annoyances"`.

### Your environment

* uBlock Origin version: uBO 1.17.4
* Browser Name and version: Firefox 57
* Operating System and version: Windows 7

**Comment by uBlock-user** [comment]
> Subscribe links activate in "Custom" section no in "Annoyances".

List is duplicate, so no, the existing behaviour is by-design.

**Comment by gorhill** [comment]
From now on, mirrors will be added only if there is a very good reason to do so. Is the primary location failing regularly? `assets.json` is not to be used as a database of all the locations a specific list can be fetched -- if anything entries need to be remove for reason of pointlessness.

**Comment by uBlock-user** [comment]
@gorhill I think he's suggesting that if you add a list that is duplicate then it should activate the existing list instead of getting added in the Custom ?

**Comment by krystian3w** [comment]
> I think he's suggesting that if you add a list that is duplicate then it should activate the existing list instead of getting added in the Custom.

Yes, but I have no evidence for instability of `fanboy.co.nz` server:

> `assets.json` is not to be used as a database of all the locations a specific list can be fetched

**Comment by uBlock-user** [comment]
Are you asking to add another mirror or are you suggesting what I said ? Clarify that first.

**Comment by krystian3w** [comment]
The more second scenario, if we can bypass the without editions of the `assets.json` file.

**Comment by gorhill** [comment]
uBO can't know that external URL correspond to the same list as one of the stock lists -- that is just impossible.

**Comment by gwarser** [comment]
Looks like this list changed its home. `supportURL` should be changed to `https://forums.lanik.us/`

**Comment by gorhill** [comment]
To me it looks like issues are also taken care at <https://github.com/ryanbr/fanboy-adblock/issues>. I will let @ryanbr and @Khrin decide where they want cookie list issues to be reported.

**Comment by ryanbr** [comment]
Either Easylist github issues or my github issues would be fine. Though there is a higher chance I'll see it in mine.

**Comment by ryanbr** [comment]
btw, the old list was just a manual mirror of cookies file. Once we seperated off the cookies/annoyances in the main repo, the need to manually update the list wasn't needed. I guess the other option was to just redirect too https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
