### ISSUE TITLE
##+js(addEventListener-logger.js) breaks page

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uBlock-issues#368]
- add `wsj.com##+js(addEventListener-logger.js)`
- go to `https://www.wsj.com/articles/wall-streets-big-landlords-are-so-hungry-for-houses-theyre-building-them-11546511401`
- the sliding strip at the top is broken (does not appear anymore)

chrome beta uBo last dev build
FF stable uBo last dev build

Notes (@gwarser)

https://github.com/uBlockOrigin/uAssets/blob/1b8ac96f9842d21c995adcbf1f6dd06e49964b10/filters/resources.txt#L1875

.toString() should be removed in addEventListener-logger.js (or callback checked for valid value)

@gorhill

**Comment by jspenguin2017** [comment]
To convert a value to a string, `String(value)` should always be used, it works for any value, unlike `value.toString()`.

**Comment by gwarser** [comment]
This should work just fine: https://developer.mozilla.org/en-US/docs/Web/API/Console#Using_string_substitutions

**Comment by mapx-** [comment]
Another case:

`https://www.bzbasel.ch/basel/basel-stadt/beat-oberlin-fordert-mehr-austausch-zwischen-den-fakultaeten-rduit-denken-hat-keinen-platz-134305206`

I added today a filter to defeat the anti adb stuff
`@@||az-cdn.ch/*ads.js$script,domain=bzbasel.ch`

However, I noted again the logger scriptlet breaking the page (see the infinite loading widget on the right side under the menu)
`bzbasel.ch##+js(addEventListener-logger.js)`
