### ISSUE TITLE
ublock origin not working in offline tab 

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uBlock-issues#369]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

using cent browsers(`https://www.centbrowser.com/`) press ctrl+m, visit any site and the ublock origin will not work
### A specific URL where the issue occurs

any site for example  `http://rutracker.org/forum/index.php`

### Steps to Reproduce

1.press crtl+m
2. open any site

### Expected behavior:

advertising must be blocked
### Actual behavior:

but the blocker just doesn't work
### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: cent browser 3.7.2.33 
* Operating System and version: windows 10 x64

**Comment by uBlock-user** [comment]
Likely a browser issue. It's not officially supported btw.

**Comment by electrifying** [comment]
> Likely a browser issue. It's not officially supported btw.

Hello. Thanks for the answer. But this is not a browser problem, if you go to the offline tab, and then turn on and off the box in the extension control settings, it will work on the offline tab.

**Comment by electrifying** [comment]
or you can also turn on the disable option to use in incognito mode and the extension will also start working in a stand-alone tab

**Comment by gorhill** [comment]
I support Chromium, Google Chrome, Opera, Firefox, Nightly, Firefox for Android. If you can reproduce the issue in one of those browsers, than please update your repro steps on how I can reproduce in these browsers. For any other fork on one of the above browsers, the user experiencing the issue will have to investigate and diagnose the issue, and pull request to fix the issue will be considered if they are made with care -- including ensuring the PR does not break in any way other supported browsers.

**Comment by gwarser** [comment]
What is this feature about?

https://www.centbrowser.com/features.html describes ctrl + M as "New multilogin tab"

**Comment by electrifying** [comment]
> What is this feature about?
> 
> https://www.centbrowser.com/features.html describes ctrl + M as "New multilogin tab"
Login multiple accounts at the same time and use it just like in incognito window.

**Comment by uBlock-user** [comment]
> But this is not a browser problem, if you go to the offline tab, and then turn on and off the box in the extension control settings, it will work on the offline tab.

Offline tab is not a feature of Chromium/Firefox and this issue cannot be reproduced on Chromium/Firefox, so the issue is specific to the Fork you're using.

**Comment by Wector11211** [comment]
If you are still interested, I found a quick [solution](https://github.com/uBlockOrigin/uBlock-issues/issues/1665#issuecomment-884705999).
