### ISSUE TITLE
Feature Request: Reset Count, Change/Set the Cycle of Filters Update

### ISSUE THREAD

**Issue by byyxx128** [uBlockOrigin/uBlock-issues#37]
1. uBlock now can record how many ads have been blocked since installation.
　But I'm not able to reset this number.
2. There is a "! Expires:" mark in traditional ABP filters. I'm not sure if uBlock can read it.
　Usually, ABP use this mark to decide how often to update a filter.
　If uBlock doesn't use this mark, that's all right, but I don't find a option to change the update cycle. So maybe this is required.
　Furthermore, I suggest that it is necessary to give the information of version and update time for filters. Then I can confirm if uBlock is using the newest filter.

**Comment by jspenguin2017** [comment]
1. It's pretty easy to reset, why not add a button to the dashboard? 
```
µBlock.localSettings.blockedRequestCount = 0;
µBlock.localSettings.allowedRequestCount = 0;
µBlock.saveLocalSettings();
```
2. Expires header is used. Mouse-over the clock icon tells you when it was updated.

**Comment by uBlock-user** [comment]
> uBlock now can record how many ads have been blocked since installation.

Nope, it displays number of network requests blocked, not ads.

> There is a "! Expires:" mark in traditional ABP filters. I'm not sure if uBlock can read it.
　Usually, ABP use this mark to decide how often to update a filter.
　If uBlock doesn't use this mark, that's all right, but I don't find a option to change the update cycle. 

Already exists and is being used to mark the filterlists for updates.

**Comment by u-RraaLL** [comment]
@uBlock-user can you restore the title again and maybe lock the issue if that'll prevent the author from changing it afterwards?
