### ISSUE TITLE
Incompatibility with Mojave dark mode

### ISSUE THREAD

**Issue by easyaspi314** [uBlockOrigin/uBlock-issues#370]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When dark mode is enabled on macOS Mojave, uBlock doesn't adapt properly.

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

1. Install uBlock from the App Store
2. Enable Dark Mode in Mojave
3. Open the popup in Safari
4. Open the configuration app

### Expected behavior:

A readable dialog, and a dark config dialog.

Something like this mockup I made:
![ublock mockup](https://user-images.githubusercontent.com/6258309/50785396-7636e880-127e-11e9-9f84-d33e91cece73.png)
![ublock mockup 2](https://user-images.githubusercontent.com/6258309/50785767-a337cb00-127f-11e9-8941-a18c3e247d47.png)

### Actual behavior:

This. Note how the popup is completely unreadable.
![screen shot 2019-01-07 at 12 43 05 pm](https://user-images.githubusercontent.com/6258309/50783779-ccedf380-1279-11e9-8861-aad187df3fd3.png)
![screen shot 2019-01-07 at 12 46 44 pm](https://user-images.githubusercontent.com/6258309/50783980-556c9400-127a-11e9-8846-bf9a11282a39.png)

### Your environment

* uBlock Origin version: 1.3 (App Store)
* Browser Name and version: Safari 12.0.2
* Operating System and version: macOS Mojave 10.14.2

**Comment by uBlock-user** [comment]
That's uBlock, not uBlock Origin, scammy version.

**Comment by easyaspi314** [comment]
Oops, sorry.
