### ISSUE TITLE
uBlock for other browsers

### ISSUE THREAD

**Issue by Yournished** [uBlockOrigin/uBlock-issues#374]
Currently uBlock is supported on 4 browsers. I would argue neither of these offer a very good experience or privacy features. Luckily, one of these is Firefox, which has some forks like Waterfox and Icecat that are pretty good, and uBlock works with those. Still, I would say that there are many other browsers that potentially offer a superior experience, and in any case everyone should be free to choose whatever browser they want without being stuck using a bad browser simply because of a good extension. Yet for many interesting browser projects, trying them has a huge cost because uBlock is not available, and you would have to go back to the godawful browsing with ads, tracking, script bloat, unwanted cookies and obtrusive warnings if you want to try a browser that is not the big 4.

I don't think it's practical to try and write ports for every major browser out there, since there are many browsers and there is a problem of diminishing returns. It would be nice to have a common extension interface, but unfortunately the common interfaces we currently support are bulky and impractical for smaller projects to support.

Is there an easy solution to this problem? For example, could uBlock be turned into a library, which allows browser developers to integrate it into their browser with minimal effort? At worst, the interface would be the browser developer's problem, but at least the blocking/element hiding functionality and compatibility with uBlock's block lists would be there.

**Comment by uBlock-user** [comment]
Browser extensions cannot be turned into libraries.

**Comment by gorhill** [comment]
uBO is written using HTML/CSS/JS/WebExtensions, all standard tech with APIs plenty documented, so it's up to other browsers to support these.

I would like the issue trackers to be kept only for _specific_ issues which are actionable.

**Comment by Yournished** [comment]
@gorhill, I respect you as a developer and I obviously think uBlock/uMatrix is great software. I'm sorry if you feel like my question was off-topic. But I have to say it's a bit ironic that [the story with chromium](https://www.reddit.com/r/programming/comments/aiswpe/google_proposes_changes_to_chromium_which_would/) developed soon after I made this post.

That said, fair enough. I hope it all works out.
