### ISSUE TITLE
Stream is being blocked when live (black screen) works fine without uBlock enabled, VODs also work

### ISSUE THREAD

**Issue by exoXd** [uBlockOrigin/uBlock-issues#376]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

My stream is being blocked, I tried using a separate twitch account with only ublock and it worked fine, only https://twitch.tv/exo_na is being blocked (the stream itself, not the page).

### A specific URL where the issue occurs

https://twitch.tv/exo_na

### Steps to Reproduce

1. Open my stream when it's live streaming
2. View a black screen with no sound

### Expected behavior:

Be able to see the stream.

### Actual behavior:

Black screen every time. (also happens with other adblockers)

I've tried to contact twitch, they refused to troubleshoot as it involves third party software/addons.

### Your environment

* uBlock Origin version: uBlock Origin1.17.4
* Browser Name and version: Chrome Version 71.0.3578.98
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Bad filter from easylist..
