### ISSUE TITLE
Mullvad's WebRTC check fails with "Prevent WebRTC from leaking local IP addresses" checked

### ISSUE THREAD

**Issue by tony971** [uBlockOrigin/uBlock-issues#377]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Mullvad is a highly regarded VPN with an online security check. Firefox fails the site's WebRTC leak check, even when "Prevent WebRTC from leaking local IP addresses" is checked in uBlock Origin settings. Disabling WebRTC entirely passes the check.

https://am.i.mullvad.net/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Go to the website.
2. Allow the check to run.

### Expected behavior:

WebRTC not to be able to leak my real IP address.

### Actual behavior:

WebRTC is able to leak my real IP address.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox 65.0b9
* Operating System and version: Windows 10 Pro 1809

**Comment by uBlock-user** [comment]
![image](https://user-images.githubusercontent.com/21290713/51015981-814a8b00-1594-11e9-9700-e001a541d3ae.png)

**Comment by gwarser** [comment]
Requires external application or account?

If you mean: test does not work at all because WebRTC is completely disabled, then it's Firefox bug ~ https://github.com/gorhill/uBlock/issues/3009

**Comment by tony971** [comment]
@uBlock-user it will hang on that for a minute or two and then give the result. The check takes a while.

**Comment by tony971** [comment]
@gwarser No, just requires patience to allow it to finish. There is no progress bar.

**Comment by uBlock-user** [comment]
> it will hang on that for a minute or two and then give the result

Not on my end. post what result is shown to you.

**Comment by tony971** [comment]
> As expected, no leakage of IP address.

That's the failure result. This is the pass (when I disable WebRTC entirely)

![capture](https://user-images.githubusercontent.com/7101253/51028640-1190cc00-15a5-11e9-8673-c3fe6886ecca.JPG)

**Comment by uBlock-user** [comment]
The issue is about WebRTC leaking IP address, not DNS Leaks test failing which appears to be a side-effect for this website given it must be using WebRTC for checking DNS leaks.

**Comment by tony971** [comment]
@uBlock-user you caught my un-edited reply. I fixed the screenshot. I also get the passing message using Microsoft Edge's “Hide my local IP address over WebRTC connections” option.

**Comment by uBlock-user** [comment]
> Posted the wrong capture

Yes, I get that too when I disable WebRTC from about:config, which is not what uBlock does, see - https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

**Comment by tony971** [comment]
@uBlock-user Microsoft Edge's “Hide my local IP address over WebRTC connections” option produces a pass without totally disabling WebRTC, either.

**Comment by uBlock-user** [comment]
> Microsoft Edge's “Hide my local IP address over WebRTC connections” option

You mean browser option in Edge or uBlock Origin on Edge ?

**Comment by tony971** [comment]
The browser option

**Comment by uBlock-user** [comment]
Then they're not doing what uBO does as I said before in https://github.com/uBlockOrigin/uBlock-issues/issues/377#issuecomment-453474792 

The important part is not message on the website, but whether the IP address is leaked or not. Different websites behave differently when uBO's setting is active.

**Comment by tony971** [comment]
This issue was created because whatever Microsoft Edge is doing works, but uBO does not. They're obviously doing something different because they get two different results. The failure shouldn't be dismissed as "expected behavior"

**Comment by gorhill** [comment]
To fix <https://github.com/gorhill/uBlock/issues/3009> I intend to expose the different WebRTC options to the user.

**Comment by uBlock-user** [comment]
> This issue was created because whatever Microsoft Edge is doing works, but uBO does not.

That's not the title said or the Actual Behavior you mentioned. If you want file a suggestion, you didn't file a suggestion, instead you opened this as an issue.

**Comment by tony971** [comment]
An example of a pass is needed to show why a fail is an issue?

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3009

**Comment by uBlock-user** [comment]
> An example of a pass is needed to show why a fail is an issue?

Yes, when your Steps To Reproduce, Expected Behavior & Actual Behavior in the first post do not mention that.

**Comment by tony971** [comment]
Failing the check is an issue in an of itself, without showing that Microsoft Edge's approach passes the check.
