### ISSUE TITLE
Adguard Annoyances is supposed to be used along Adguard Social

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uBlock-issues#378]
I'm aware that new requests for lists aren't accepted anymore, but the original request for this list was never closed: https://github.com/gorhill/uBlock/issues/3214. This also involves a list already present in the extension.

Unlike Fanboy's, Adguard Annoyances doesn't include social filters. It's supposed to be always used along with Adguard Social.

Currently, people who want to replace Fanboy's lists with the ones by Adguard need to figure that out by themselves and look the link up.

@ameshkov Please check this to host a copy of the social list under `https://filters.adtidy.org/extension/ublock/filters/`.

**Comment by patrickdrd** [comment]
they might not be able to be hosted as a copy though,
e.g. if they include script injects,
I'm having similar problem with ublock annoyances,
almost none of them work in adguard,
they need conversion,
so, there should be a similar list, converted to be able to run by AG,
or, alternatively, AG team could change the code in order to 
parse ublock filters

**Comment by ameshkov** [comment]
> @ameshkov Please check this to host a copy of the social list under 
> https://filters.adtidy.org/extension/ublock/filters/.

https://filters.adtidy.org/extension/ublock/filters/4.txt

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
> It's supposed to be always used along with Adguard Social.

Why are there two lists if they have to be used together? Why not make it one single list?

**Comment by patrickdrd** [comment]
because AG is using a different engine/format maybe?

**Comment by ameshkov** [comment]
I am not sure what's this all about, but these are different filter lists, and they can be used without each other.

**Comment by ameshkov** [comment]
Maybe the point is that people might not realize that AG Annoyances on its own won't remove social widgets (unlike Fanboys Annoyances)?

**Comment by adranger** [comment]
Thank you for taking the time to read this and adding the list.

>Maybe the point is that people might not realize that AG Annoyances on its own won't remove social widgets (unlike Fanboys Annoyances)?

Yes, that's what I meant. I'm using Adguard Annoyances alone (without Fanboy's).

I've replaced Fanboy's Annoyances with the  Adguard  version  because the Adguard Team fixes all the issues I report or at least give me the reason why they aren't going to be dealt with,  unlike Fanboy.
