### ISSUE TITLE
Some logger suggestions

### ISSUE THREAD

**Issue by Kusresa** [uBlockOrigin/uBlock-issues#381]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

I've been using the logger in the dev build for a little while and I'm liking the new additions/changes @gorhill. I have some suggestions which I think could be helpful.

1. Can there be a way to see which specific filter and filter list a redirect filter is coming from? Right now it's the only filter type showing in the logger where it is not easy to see which filter is causing it or which filter list it originates from.

2. I see that there is new "Click to preview" option for image requests unless they are blocked where there is no option to view them. Do you think it's better to allow all allowed/unblocked image requests to automatically preview like before and have the new "Click to preview" option for blocked images? That way people with 3rd party or images blocked can easily see from the logger if they want certain blocked image/set of images requests to be allowed/unblocked.

3. When a filter originates from "My Filters" clicking on logger link to it goes to asset viewer but can it instead go to the "My Filters" dashboard page (possibly showing the exact line the filter is)? That page does searching like asset viewer and additionally the user can also modify/delete the filter straight from that page if needed unlike the asset viewer.

4. For all 1st party requests the logger shows request partyness for example as "(1) github.com => github.com". Would showing just "(1) github.com" be enough? It's a minor thing but seems a little redundant.

**Comment by gorhill** [comment]
This is a laundry list of requests -- please open specific issues that are actionable.
