### ISSUE TITLE
Comma as the thousands separator

### ISSUE THREAD

**Issue by Matthaiks** [uBlockOrigin/uBlock-issues#383]
For certain locales, a comma shoudn't be used as the thousands separator. In many countries the comma is used as the decimal separator.

uBlock Origin 1.17.7rc0

**Comment by gorhill** [comment]
No repro steps, I have no clue what OP is referring to. Closing as _invalid_. Respect the template please.

**Comment by uBlock-user** [comment]
I thought he meant the numbers in filter count in external lists.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/51398657-71a6e580-1b44-11e9-9f54-268016baad1c.png)


Top en_US, bottom pl_PL
