### ISSUE TITLE
Drop hot key customization options

### ISSUE THREAD

**Issue by rugk** [uBlockOrigin/uBlock-issues#386]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when... N/A
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

You currently provide a custom way to adjust hot keys of your extension.

Starting with Firefox 66 [Firefox will provide a built-in way of doing so](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384) ([German article](https://www.soeren-hentzschel.at/firefox/tastatur-kommandos-von-erweiterungen-koennen-ab-firefox-66-geaendert-werden/)) and thus you can IMHO drop your own customization options.

AFAIK other browsers like Chrome/ium already support that customization as a built-in feature too, so there is no need to reimplement that in your extension anymore.

### A specific URL where the issue occurs

N/A 
### Steps to Reproduce

N/A

### Expected behavior:

no built-in hotkey customization tab

**New in Firefox 66:**
![image](https://user-images.githubusercontent.com/11966684/51429994-f6f9cb00-1c14-11e9-90fd-9e158f59efc6.png)

### Actual behavior:

this tab is there

**Old:**
![image](https://user-images.githubusercontent.com/11966684/51430001-0ed14f00-1c15-11e9-934a-9a588c2d5f00.png)

### Your environment

* uBlock Origin version: v1.17.4
* Browser Name and version: Firefox 66.0a1 (Nightly, 2019-01-19)
* Operating System and version: Linux/Fedora 29

**Comment by gorhill** [comment]
I am aware of this, this will have to wait that the kinks have been fixed before I drop support in FF66.

**Comment by uBlock-user** [comment]
You could drop support in the nextdev build untill then..

**Comment by gorhill** [comment]
I am using Nightly and I still do not see a way to remove a shortcut. Am I missing something?

**Comment by rugk** [comment]
Trying it, I also see no way. I mean, just don't use it, if it is taken…

But yes, found the open issue about that now: https://bugzilla.mozilla.org/show_bug.cgi?id=1520119

**Comment by gwarser** [comment]
I noticed twice already, shortcuts reset to blank after some time.

**Comment by gorhill** [comment]
I guess this might be caused by the launch code where shortcuts are loaded and set based on state of `µBlock.canUseShortcuts`, while the state of `µBlock.canUseShortcuts` depends on an asynchronous call. I just need to move the shortcut-assigning code to where `µBlock.canUseShortcuts`'s final state is set.

**Comment by gwarser** [comment]
No issues anymore. I also tried ESR and was fine.

**Comment by gitressa** [comment]
I seemed to remember that shortcuts were defined under uBlock Origin settings, but couldn't find it. It took me a bit of digging to realize that add-on shortcuts have been moved from the individual extension to a centralized settings page, which can be accessed like this: https://github.com/gorhill/uBlock/wiki/Keyboard-shortcuts

**Comment by gitressa** [comment]
I have been using the development build for a week or so (currently `1.26.3rc6`) and the shortcuts keep getting deleted, after I restart the browser. Should I create a new issue for this, or is this still expected behavior?
