### ISSUE TITLE
Cosmetic filter does not work if exception for this filter or filter with negated domain exist in other list

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#388]
<details><summary>Prerequisites
</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

Element cannot be hidden by cosmetic filter if one of third party filter lists contains exception for this element. 
This can be cosmetic exception filter (`#@#...`), or hiding filter with negated domain (`~...##...`) which will not apply to our test page.

### A specific URL where the issue occurs

https://www.telepolis.pl/

Facebook icon in top right corner (`.icon-facebook`) cannot be hidden in "My filters"/"Polish Social Filters", because "AdGuard Social Media" list contains filter similar to this: `~ozracing.com,~telepolis.pl,~deezer.com##.icon-facebook`

### Steps to Reproduce

1. select "AdGuard Social Media" list
2. add `telepolis.pl##.icon-facebook` to "My filters"
2. visit https://www.telepolis.pl/

### Expected behavior:

Facebook icon in top right corner should be hidden

### Actual behavior:

Icon is not hidden

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox 64, Chromium 71
* Operating System and version: Linux

**Comment by gwarser** [comment]
This is by design behavior.

Workaround - use different selector. 
In this example, one of:

- `telepolis.pl##a.icon-facebook`
- `telepolis.pl##.icon-facebook,.icon-facebook`
- `telepolis.pl##.icon-facebook,invaild_selector`

**Comment by krystian3w** [comment]
network filters use same mechanism? https://github.com/uBlockOrigin/uBlock-issues/issues/620

**Comment by gwarser** [comment]
> `||domain.com^$~image`
> 
> this is also translated into:
> 
> `@@||domain.com^$image`? https://github.com/uBlockOrigin/uBlock-issues/issues/388

***

`||domain.com^$~image`

Block all connections, except `image`

`@@||domain.com^$image`

If something is blocked and it is `image` then allow it.

For network filters you have `important` option to override exceptions from other filter lists.
