### ISSUE TITLE
CSS filters with unclosed pseudo classes works in preview mode

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#389]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element picker possible can add filters without closed pseudo classes (/considers them to be correct):

```
! 1 - 4 filter
##body:not(bodzio
##body:not(.bodzio
##body:not(#bodzio
##body:not([bodzio]

!old 5 filter
##body:nth-of-type(1

!old 7, 8 filter
##html:nth-child(1
##body:nth-child(2

!old 6 filter
##html:lang(en
```

![image](https://user-images.githubusercontent.com/35370833/51481814-115ab280-1d95-11e9-96a6-9ebcb28af235.png) |
--- |

### A specific URL where the issue occurs

`https://github.com/uBlockOrigin/uBlock-issues/issues/389` https://github.com/uBlockOrigin/uBlock-issues/issues/389

### Steps to Reproduce

1. open site and activate element picker
2. try paste to element picker 1 of 8 demo filters
3. body/html colorized without closed bracket

### Expected behavior:

Element picker require closing of CSS3 pseudo classes, that have brackets.

### Actual behavior:

Element picker no require closing of CSS3 pseudo classes, that have brackets.

###### Opera
* uBlock Origin version: 1.17.0
* Browser Name and version: Opera 57
* Operating System and version: Windows 7

###### Firefox
* uBlock Origin version: 1.18.2
* Browser Name and version: Opera 64.0.2
* Operating System and version: Windows 7
---

Possible affected vesions:

* `1.0.0` to `1.17.2` (no test on all possible published versions),
* `1.17.7rc2`, 
* latest stable `1.18.0`

 no affected know version:

* `1.17.4`

**Comment by kulfoon** [comment]
> * [x]  I am running the latest version of uBlock Origin

> - uBlock Origin version: 1.17.0

Definately not the latest version:
- can't reproduce the issue on 1.17.4 neither on Firefox 64.0.2 64bit nor on Opera 57 64bit
- however I can reproduce on 1.17.0 and 1.17.7rc2; but with the cases 1-6 only, can't reproduce the cases with `##html:nth-child(1` nor with  `##body:nth-child(2`

**Comment by krystian3w** [comment]
I can reproduce in 1.0.0 version on Firefox 42:

![obraz](https://user-images.githubusercontent.com/35370833/51495816-e5075c00-1dbd-11e9-9fad-42f29e5cd9c7.png) |
--- |

Some pseudo classes may no works becuse element is on first or second or github lang in attrib you have other than `en`.

**Comment by krystian3w** [comment]
Bug comeback in `1.18.0` and I can reproduce with all 8 demo pseudo class filters.

**Comment by krystian3w** [comment]
Hello I found another disaster glitch.

`https://www.mgsm.pl/pl/katalog/lg/q9/LG-Q9.html`
`https://www.gsmchoice.com/en/catalogue/lg/q9/`

with use no closed "[attrib]":

```
##div.columns > small[style*="color: #c0c0c0; font-s
```

![image](https://user-images.githubusercontent.com/35370833/52272516-552dea00-2947-11e9-92d0-2b5ffdff0d39.png) |
--- |

![image](https://user-images.githubusercontent.com/35370833/52272565-7d1d4d80-2947-11e9-8c2e-d420f71bd066.png) |
--- |

Filter is also invalid after save, maybe I try install `1.17.4`, maybe still unafected.

**Comment by kulfoon** [comment]
OK - as [uBO 1.18.4](https://github.com/gorhill/uBlock/releases/tag/1.18.4) has already appeared about an hour ago, I've tried to check the both issues:
- 1_ the issue from the OP 1st comment is still here and what is interesting, as opposed to what I wrote in my previous https://github.com/uBlockOrigin/uBlock-issues/issues/389#issuecomment-456137196, now I can reproduce all the cases (1-8), not sure if this behaviour is because the cases were perhaps modified meantime by the OP, as it says that comment edit history is deleted.
- 2_ as for the second issue above - I confirm, also I can add that if add `]` to the end of the filter: 
`##div.columns > small[style*="color: #c0c0c0; font-s` cannot add the filter anymore:
 
![anim 003](https://user-images.githubusercontent.com/43844449/52275444-ddb08880-294f-11e9-999c-aa06410ad4e1.gif)

**Comment by gorhill** [comment]
> the issue from the OP 1st comment is still here

Because nowhere in here is it said that it was fixed.

All the reported issue are just flavor of the same underlying one, no need to pile on, this will get fixed eventually.

**Comment by kulfoon** [comment]
> Because nowhere in here is it said that it was fixed.

Yes, but it also could get fixed accidentaly, as issues not only can appear accidentaly, but also can dissappear accidentaly.

**Comment by krystian3w** [comment]
I suppose found "regression" with experiment `:is(...)` pseudo-class selector:

Try use in element picker:
```
##body :-moz-any(h1
```
```
##body :-webkit-any(h1
```

https://developer.mozilla.org/en-US/docs/Web/CSS/:is

Also afected with "`Experimental Web Platform features`" in Chrome 75:

```
##body :is(h1
```

**Comment by gorhill** [comment]
When the browser consides this a valid CSS selector, so does uBO.

**Comment by gorhill** [comment]
When I try `document.querySelector('body :is(h1');` in the dev console, the browser does not throw an exception, meaning it's a valid selector. When the browser considers a selector is valid, so does uBO.

**Comment by krystian3w** [comment]
OK, so bug is in chrome / firefox engine (I cannot test any latest Safari (12/13)).
