### ISSUE TITLE
Regarding filter editor improvement on Firefox android

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#39]
@gorhill 

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Editing custom filters in my filters area in Android is cumbersome because if I want to delete 1 specific filter from bunch of filters, I have to for specific filter- select all>then delete filter ......Sometimes all area is not selected.....
Instead can you give feature like this present in adguard which is useful for Android

![img_20180512_234423](https://user-images.githubusercontent.com/20338483/39960331-79ea966e-5610-11e8-88c8-c92f33d1e1c5.png)

### Your environment

* uBlock Origin version:1.16.4
* Browser Name and version: Firefox android
* Operating System and version: Android 7.1

**Comment by ghajini** [comment]
Ohh, that sounds good😊👍, I wasn't aware of that., Thank you....Sorry for opening invalid issue

**Comment by gorhill** [comment]
Note that uBO's _"My filters"_ pane is equivalent of editing your own filter list, and thus the behavior is that of editing a text file.

Adguard chose the line-by-line approach (like ABP used to do and I chose to not mimic), which I have no intention of adopting. My opinion is that being able to freely edit the text with no constraint is best -- one can select entire block of filters and delete them, or add filter list directives, comment out, etc. just like any filter list maintainer would do.

**Comment by yourduskquibbles** [comment]
Is there an Android keyboard you recommend @gorhill? When I do the suggested clearing using the gutter click method it doesn't _ever_ work with [Swiftkey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) keyboard.

Oddly enough, using Swiftkey keyboard deleting a line using the gutter method will actually do the exact opposite of what you describe and ADD lines instead of removing them.

**Comment by gwarser** [comment]
gorhill uses AnySoftKeyboard https://github.com/uBlockOrigin/uBlock-issues/issues/7#issuecomment-383235504 AOSP and Google should be good. This may be Swiftkey related if you reproduce here https://codemirror.net/demo/activeline.html (no gutter-tap select here) https://github.com/codemirror/CodeMirror/issues/4500
