### ISSUE TITLE
Element Picker Appearance Delayed

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#393]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The element picker takes about 5-10 seconds before appearing on `https://newstorycharity.org/careers/pm/`

I'm not sure if this is a bug with uBO or the site intentionally crippling the element picker somehow but I think it is a bug since I tried disabling JS on the site via uBO (Step 2 below) and picker still doesn't appear immediately.

### A specific URL where the issue occurs

`https://newstorycharity.org/careers/pm/`

### Steps to Reproduce

1. Navigate to `https://newstorycharity.org/careers/pm/`
2. (Optional step) Disable site javascript in uBO and reload `https://newstorycharity.org/careers/pm/`
3. Enter element picker mode
4. Notice background screen turns gray like element picker should be possible but can't choose any elements on page for ~10 seconds.
### Expected behavior:

Element picker appears immediately

### Actual behavior:

Element picker doesn't appear for a few seconds. The behavior happens in both firefox and chrome for me, but below gif is taken in chrome with only uBO with default filter lists & uBlock Origin Extra installed.

![elementpicker](https://user-images.githubusercontent.com/22258847/51629488-b3090d80-1f15-11e9-8a8e-8f2540038c83.gif)

### Your environment

* uBlock Origin version: uBlock Origin 1.17.7rc3 with default settings & filter lists
* Browser Name and version: Chrome Version 72.0.3626.64 (Official Build) beta (64-bit) & Firefox 64.0.2 (64-bit)
* Operating System and version: Windows 10 64 bit

**Comment by gorhill** [comment]
I also can't reproduce.

**Comment by gorhill** [comment]
Sorry, I can reproduce, using the picker from the popup panel. I originally tried with the context menu.

**Comment by gorhill** [comment]
The site modifies uBO's own `pointer-events` style:

![a](https://user-images.githubusercontent.com/585534/51639510-16536980-1f2f-11e9-93cf-dd9d67e74a88.png)

**Comment by uBlock-user** [comment]
>  site modifies uBO's own pointer-events style:

Wasn't that fixed recently when another side made changes to pointer-events ?

**Comment by gorhill** [comment]
Similar but not exactly the same: <https://github.com/uBlockOrigin/uBlock-issues/issues/380>

**Comment by krystian3w** [comment]
Another - site with filter grayscale on html element.

```css
html {
   filter: grayscale(1)
}
```

When bugs all fixed position elements and also element picker after indicated element and try again point the item down after scrolling through one screen of text.
