### ISSUE TITLE
Implementation and update of translations

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#394]
- Copyright (c) Raymond Hill 2014-2019 | Change the Copyright year only in about.html so that it appears in extension and is more graceful.
- Translation of: "by" and "An implementation of Myers' diff algorithm" in about.html.
- Translation of: "click to preview" in the logger.
- Also of the translation "off" that is not implemented.
- [x] Update translations in uBlock Origin Legacy. | Many translations of the Spanish language were corrected/changed.
- Remove/delete "uBlock filters - Experimental" from the uBlock filters and also from "uAssets", which has not been updated for a long time.

Only small suggestions, it's up to you.

**Comment by uBlock-user** [comment]
> Remove/delete "uBlock filters - Experimental" from the uBlock filters and also from "uAssets", which has not been updated for a long time.

The list cannot be removed unless those filters are merged in the default filters list.

**Comment by MS-PC** [comment]
Decline my suggestion to delete/remove "uBlock filters - Experimental". Before I did not understand very well the operation of "uBlock filters - Experimental", I examined it more exhaustively to understand. Sorry for any inconvenience.

**Comment by uBlock-user** [comment]
> Translation of the words "by" and "An implementation of Myers' diff algorithm" in about.html.
Also of the translation "off" that is not implemented.

Actually translations are handled at Crowdin. They're imported here from there. So best is to suggest that there.

> Update translations in uBlock Origin Legacy. | Many translations of the Spanish language were corrected/changed, and also from other languages.

Legacy isn't actively maintained/developed, neither is on Crowdin.

**Comment by gorhill** [comment]
> Declined my suggestion to delete/remove "uBlock filters - Experimental".

Why? I have actually seriously entertained the idea of removing it lately because in the end, there is not much point of an "experimental" list as there is no proper way for me to gather whether any of the filters in there work well or not, I don't have access to any stats.

Removing it from the stock lists should be no problem, any removed list which is selected is (supposed to be) moved to the "Custom" category.

**Comment by gorhill** [comment]
> Update translations in uBlock Origin Legacy

I decline this, this is a far from trivial task, not worth the amount of work.

**Comment by uBlock-user** [comment]
> Removing it from the stock lists should be no problem

What about the `$redirect` filters ?

**Comment by MS-PC** [comment]
It does not let me create the PR. Message: `An owner of this repository has limited the ability to open a pull request to users that have contributed to this repository in the past.`
https://github.com/MS-PC/uBlock/commit/ca81c45c7eac887a08005e7ca8e42b4d0c1eec78

For after "merge pull request" I will delete my uBlock fork/repository.

**Comment by gwarser** [comment]
New translations will be pulled directly from Crowdin.

**Comment by gorhill** [comment]
@MS-PC I removed the restriction you should be able to create the PR now.

@gwarser This is the legacy version, the master one, as seen on Crowdin, has diverged quite a lot.

**Comment by Jap2-0** [comment]
@gorhill Is there anything keeping you from merging it into uBlock privacy?  I see some of the filters are there already.

**Comment by gorhill** [comment]
> anything keeping you from merging it into uBlock privacy?

I don't want higher level of web page breakage due to these filters.

**Comment by Jap2-0** [comment]
> I don't want higher level of web page breakage due to these filters. As said, the list will still be in use for those who enabled it.
I take it you don't have any numbers on how many people use the experimental list?

**Comment by gorhill** [comment]
I have nothing, uBO has no telemetry or anything of that sort, so an experimental list is pointless really, it was a bad idea. The only way to get feedback for sure about whether a filter is causing issue is to force it's use by adding it to one of the default lists, but of course adding doubtful filters to any of the default list is out of question.

**Comment by gwarser** [comment]
Can be enabled by default in development version.

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.
