### ISSUE TITLE
Blocking remote fonts should not block PUA fonts.

### ISSUE THREAD

**Issue by Martin-Furter** [uBlockOrigin/uBlock-issues#395]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Many websites use PUA (Private Use Area) fonts to display some icons. But when blocking of remote fonts is enabled these icons do not appear and I see only the symbol for an unknown unicode character.

### A specific URL where the issue occurs

https://www.telstra.com.au/my-account/prepaid-recharge
see these images:
![remote-font-disabled](https://user-images.githubusercontent.com/25500683/51666767-840d9d00-1fe4-11e9-9f74-ec2301428e05.jpg)
![remote-font-enabled](https://user-images.githubusercontent.com/25500683/51666821-8b34ab00-1fe4-11e9-95aa-02de173566d2.jpg)

https://www.mobikwik.com/
below the text "Recharge and Bill Payment" is a set of icons which disappear

https://www.airtel.in/service-provider/global-voice-messaging-solutions
top right the icon with a link to https://www.airtel.in/s/selfcare/

### Steps to Reproduce

1. in ublock config block loading of remote fonts per default
2. go to one of the mentioned sites
3. now you should see these "unicode character missing" symbols
4. allow loading of remote fonts
5. now you see the icons instead of the error symbols

### Expected behavior:

I wish it would load and display remote fonts which use PUA unicodes.

### Actual behavior:

I know I told ublock to not load remote fonts and that is what it did.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: firefox 64.0.2
* Operating System and version: debian sid

**Comment by uBlock-user** [comment]
> I wish it would load and display remote fonts

That's not how it works, when you block remote fonts, all fonts, including _inline_ ones get blocked. This is by-design.

**Comment by Martin-Furter** [comment]
Thanks for the filter list. It works in maybe 98% of the cases. but there are webpages where it does not work out of the box, for example this one:
https://www.dmax.de/programme/mega-shippers/video/episode-1/DCB417460001100
The design of the font blocker is flawed, it should be improved. The way it works now is becoming more and more useless.

**Comment by uBlock-user** [comment]
> but there are webpages where it does not work 

report where it doesn't work on their issue tracker, so the maintainer will apply the required fix.

**Comment by gorhill** [comment]
> The design of the font blocker is flawed, it should be improved

How would uBO know the content of a font resource without first downloading it? (That is assuming adding a font resource parser to uBO would not be a bad idea and not overkill in the first place).

**Comment by Martin-Furter** [comment]
Check each text on the webpage if it uses a font that has not been loaded and contains PUA codes in the text. If both are true load the font.

**Comment by gorhill** [comment]
I will let you submit a patch.
