### ISSUE TITLE
hot keys for selecting an element

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#396]
The pipette doesn't always get to the right element (**there are small elements on the html page that are difficult to get into with the mouse**), so why not add hot keys to select an element, as in old versions of adblock
![default](https://user-images.githubusercontent.com/8535285/51746708-f0e56d80-209e-11e9-9613-b79719124002.png)

**Comment by gorhill** [comment]
You can use the list of suggested cosmetic filters to select the parent elements -- they are all shown in the list up to the `body` element.

**Comment by bogachenko** [comment]
Yes. Now I use it, but not everything is selected there. In addition, in the old adblockplus there everything was controlled by hot keys. It was cool.

**Comment by gorhill** [comment]
How did you select that `iframe` element with AdGuard? I tried and I didn't find any `iframe` in that top-left corner of the page.

**Comment by bogachenko** [comment]
>  I tried and I didn't find any iframe in that top-left corner of the page.

like that ?
![Безымянный](https://user-images.githubusercontent.com/8535285/58362769-f042d380-7ee6-11e9-9ef9-00569aa5492c.png)

**Comment by gwarser** [comment]
How you did this:

![image](https://user-images.githubusercontent.com/886325/58366018-97664180-7ecc-11e9-9b90-3e29661cd062.png)

**Comment by gwarser** [comment]
Ah, I see this, but only in Firefox private window.

In normal browsing mode I see iframe in top left corner using dev tools, but it's 0x0px

**Comment by bogachenko** [comment]
>sometimes it have 0x0 dimensions and sometimes 4x4

I always have a 4x4. in private mod and normal

oddly shorter... anyway it is unlikely the average user will get into the guts of the site.. and here I hope that there will be hot keys
