### ISSUE TITLE
Bring popupFontSize into the main Settings pane

### ISSUE THREAD

**Issue by sebast889** [uBlockOrigin/uBlock-issues#397]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On some machines the text size of the popup panel is too small. Please add a way to increase/decrease the text size like there is in uMatrix.

**Comment by gorhill** [comment]
There is an advanced setting to do this, [popupFontSize](https://github.com/gorhill/uBlock/wiki/Advanced-settings#popupfontsize). Alternatively you can use the zoom feature of your browser, though this will change the text size for all uBO pages.

**Comment by sebast889** [comment]
Thank you @gorhill. I forgot I actually tried that setting months back but it didn't work. Reading the wiki again the mistake I made was I just put a number in without px at the end (which uBO accepts?). 

Bringing it to the main settings page could be good for users who wouldn't otherwise think to use or look at advanced settings (and a solution to the dumb mistake I made above).

**Comment by gorhill** [comment]
> just put a number in without px

Yes, `px` is necessary if you use a number, otherwise this will be an invalid CSS value. Any number used to represent a length must be followed by a unit -- `px`, `em`, `rem`, etc. (see CSS3 doc).

**Comment by krystian3w** [comment]
For me zoom no works property in pop-up from uBO icon, also no save to always.
