### ISSUE TITLE
1.18.2 can't be installed because it is unsigned (firefox)

### ISSUE THREAD

**Issue by Nicholas-Steel** [uBlockOrigin/uBlock-issues#398]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/gorhill/uBlock/releases/tag/1.18.2 can't be installed in Firefox, because it is not signed.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/releases/tag/1.18.2

### Steps to Reproduce

1. Visit https://github.com/gorhill/uBlock/releases/tag/1.18.2
2. Left Click https://github.com/gorhill/uBlock/releases/download/1.18.2/uBlock0_1.18.2.firefox.xpi
3. Click "Allow"

### Expected behavior:

Extension to be signed so that it can be installed.

### Actual behavior:

Extension installation is blocked by Firefox because it is unsigned.

### Your environment

* uBlock Origin version:
* Browser Name and version: Firefox 64.0.2
* Operating System and version: Windows 10 1809

**Comment by Nicholas-Steel** [comment]
I'm not familiar with how to "tick" the boxes at the start of the template.

**Comment by gorhill** [comment]
Install [from AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/). The version here cannot be signed.

**Comment by Nicholas-Steel** [comment]
Other add-ons can be installed direct from Github though like for example Bypass Paywalls (was removed from AMO arbitrarily):

Website: https://github.com/iamadamdev/bypass-paywalls-firefox

Issue report where a solution was derived: https://github.com/iamadamdev/bypass-paywalls-firefox/issues/82

**Comment by uBlock-user** [comment]
> Other add-ons can be installed direct from Github though like for example Bypass Paywalls (was removed from AMO arbitrarily):

You cannot stable builds of uBO from github, but you can install dev builds which are signed.

**Comment by Nicholas-Steel** [comment]
But... why release it on Github if it can't be installed? https://github.com/gorhill/uBlock/releases/tag/1.18.2

**Comment by gorhill** [comment]
It can still be side loaded with dev builds of Firefox.

**Comment by colbycdev** [comment]
Set xpinstall signature required in about:config to false

Tuesday, 29 January 2019, 10:10AM -05:00 from Nicholas-Steel notifications@github.com<mailto:notifications@github.com>:


But... why release it on Github if it can't be installed? https://github.com/gorhill/uBlock/releases/tag/1.18.2

**Comment by Nicholas-Steel** [comment]
I guess I'm overlooking the existence of the Firefox ESR releases which may still be able to install unsigned web extensions.
