### ISSUE TITLE
Element picker text area has unreadable text

### ISSUE THREAD

**Issue by Sesshu** [uBlockOrigin/uBlock-issues#4]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When using a system theme that uses a bright text color (e.g. white) the text inside the element pickers text area becomes illegible because the background-color of the text area is set to white by this addon's CSS.

### A specific URL where the issue occurs

https://www.mozilla.org

### Steps to Reproduce

1. Install a system theme that changes text color to white (e.g. Adwaita-dark from Gnome and start Firefox with MOZ_ALLOW_GTK_DARK_THEME=true firefox )
2. Use uBlock to enter element picker mode and click on somewhere on a web page to open up the element picker dialog.

### Expected behavior:

The text inside the text area with the rule that the user is about to create is readable.

### Actual behavior:

The text is not readable.

### Your environment

* uBlock Origin version: uBlock Origin v1.15.24
* Browser Name and version: Firefox 59.0.2
* Operating System and version: ArchLinux (No version numbering)

### Possible fix

Either remove the background-color CSS rule to have the text area use the system default background color or add a color rule. I've attached a patch that does the latter and fixes this issue.

[epicker.patch](https://github.com/uBlockOrigin/uBlock-issues/files/1921105/epicker.txt)

**Comment by gwarser** [comment]
![screenshot_20180418_001225](https://user-images.githubusercontent.com/886325/38902085-3e128068-429f-11e8-9dce-3fc20bc1aba4.png)

Mint KDE, GTK3 Theme Breeze-Dark, Firefox Nightly, UBO dev,
`MOZ_ALLOW_GTK_DARK_THEME=true` not required.
