### ISSUE TITLE
Filter lists are considered out of date on latest dev build (not using incognito mode)

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#400]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin(dev build)
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Filter lists are considered out of date after updating to latest Dev build
[Description of the bug or feature]

### A specific URL where the issue occurs
Not an URL Issue
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]Update to the latest Dev Build
2. [Second Step]Goto ubo select filter list, update filters
3rd close FF and reopen and open Filter lists and there are updates pending repete
3. [and so on...]

### Expected behavior:
Filters should update and when restarting FF should remain updated 
[What you expected to happen]
filters would update
### Actual behavior:
simulated updating and then closing and reopening there are update (open and closing just a few seconds to complete
[What actually happened]

### Your environment
Windows 10 Enterprise 1809, FF 64.0.2 
* uBlock Origin version: 1.18.1.rc1
* Browser Name and version: Firefox 64.0.2
* Operating System and version: Windows 10 Enterprise 1809

**Comment by gorhill** [comment]
He might have undisclosed Firefox settings which causes this, for example the known private mode by default issue.

Nothing has changed in cache storage for Firefox relative to 1.17.4.

**Comment by uBlock-user** [comment]
...or removal of History on when Firefox closes.

**Comment by uBlock-user** [comment]
Okay he mentions it was fixed when he uninstalled Firefox and reinstalled it -- https://github.com/uBlockOrigin/uBlock-issues/issues/399#issuecomment-457800408

So yes he customised the above mentioned which must have caused this to happen.
