### ISSUE TITLE
Fix partyness evaluation for cases of base domain-less hostnames

### ISSUE THREAD

**Issue by ettavolt** [uBlockOrigin/uBlock-issues#402]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

inline-script,first-party condition isn't fulfilled when accessing sites on http://localhost:XXXX/ or http://localhost/ or http://machine-name/

### A specific URL where the issue occurs

http://localhost:8080/
http://localhost/

### Steps to Reproduce

1. Enter static rules
```
*$script,inline-script
@@*$script,inline-script,first-party,domain=localhost
```
2. Launch something serving a page with inline script on localhost or localhost:8080.
3. Open http://localhost/ or http://localhost:8080/.

### Expected behavior:

Logger shows ``@@*$first-party,inline-script,domain=localhost`` in effect.

### Actual behavior:

Logger shows ``*$inline-script`` in effect.

### Your environment

* uBlock Origin version: 1.18.0
* Browser Name and version: Firefox 64.0.2 amd64
* Operating System and version: Arch Linux updated 2018-12-24.

**Comment by gorhill** [comment]
Use `inline-script` on its own only, like so:

    *$inline-script
    @@*$inline-script,domain=localhost

`inline-script` is a special option, it can't be used along with other types, and using `first-party` is pointless, it always apply to the document itself.

**Comment by uBlock-user** [comment]
Works if you remove `$first-party`...

**Comment by gorhill** [comment]
Not sure I agree that there is something to addres (beside the documentation maybe), `inline-script` is meant to be used like `generichide`, on its own:

    ||example.com^$inline-script

The reason is that it's a behavior-modifying filter, not a resource-blocking filter. When someone use `||example.com^` as filter, this does not block inline scripts, so the `inline-script` option is not to be used as with other types.

**Comment by ettavolt** [comment]
> `inline-script` is a special option, it can't be used along with other types, and using `first-party` is pointless, it always apply to the document itself.

Then why `first-party` affects it? And only on 'pointless' domains. I suspect this may indicate a problem in uBlockContext refactoring.

**Comment by gorhill** [comment]
Did it work before 1.18.0?

`localhost` is special in that no base domain name can be derived from it, and uBO uses base domain name to decide whether network request is 1st- or 3rd-party.

**Comment by ettavolt** [comment]
Yes, it did work on 1.17.4.

**Comment by gorhill** [comment]
> Yes, it was working since 1.15

Ok I will look into this then. You are probably correct that this is related to the context code rework.

**Comment by ettavolt** [comment]
I've traced this to:
1. filtering-context.js#is3rdPartyToDoc is comparing docDomain ('localhost') and domain ('').
2. filtering-context.js#getDomain uses domainFromHostname(hostname) that is actually uritools.js#domainFromHostname.
3. uritools.js#domainFromHostname delegates non-IPs to publicsuffixlist.js#getDomain.
4. publicsuffixlist.js#getDomain returns '' if it finds entire name being a 'public suffix'.

I think that filtering-context.js#is3rdPartyToDoc should only compare docDomain with domain only if that one is not empty, not just defined. At least, this fixes the issue for me.

**Comment by gorhill** [comment]
I probably used to do `domain = domainFromHostname(hostname) || hostname`, which should fix the issue.

**Comment by ettavolt** [comment]
Well, from μBlock's point of view, what's the difference between domain and hostname then?

**Comment by gorhill** [comment]
I use "domain" for "base domain", "hostname" for whatever is extracted from URL.
