### ISSUE TITLE
All page loads hang with uBlock 1.18.x on Firefox debug builds

### ISSUE THREAD

**Issue by buttercookie42** [uBlockOrigin/uBlock-issues#405]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Starting with uBlock 1.18.0, all page loads on debug builds of Firefox (both Android and Desktop) are simply hanging. With uBlock 1.17.4, everything is still working fine.

### A specific URL where the issue occurs

All pages except those special few pages where Webextensions aren't enabled by default (about:... pages, addons.mozilla.org, etc.).
Example page: http://www.buttercookie.de

### Steps to Reproduce

1. Visit [Treeherder](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&searchStr=debug%2C%28b%29), click on any of the green B's for the platform of your choice, select the *Job Details* tab, download and install *target.apk* for Android, respectively download and unzip *target.zip* for desktop Firefox. Alternatively, this is [the Android build](https://queue.taskcluster.net/v1/task/GUUXz1waSmSSvpIIMGd3aQ/runs/0/artifacts/public/build/target.apk) and [this the Win x64 build](https://queue.taskcluster.net/v1/task/bCp4PUKhQVKjxCd20aF20A/runs/0/artifacts/public/build/target.zip) I've used right now for testing. For Android, if you've got the regular Firefox Nightly installed, you might have to uninstall it first, though.
2. Install uBlock Origin (either 1.18.0, or 1.18.2, doesn't matter).
3. Visit any page, e.g. http://www.buttercookie.de

### Expected behavior:

The page loads.

### Actual behavior:

The page load just hangs.
If I open uBlock's logger before opening the page, nothing appears in it.

### Your environment

* uBlock Origin version: 1.18.2
* Browser Name and version: Firefox, [current mozilla-central debug build](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&searchStr=debug%2C%28b%29&revision=2013099b2c13997ffe1362e6e1e9cf09cd4cd4ac)
* Operating System and version: Android 6.0.1, respectively Windows 7 (64-bit)

**Comment by uBlock-user** [comment]
broken debug build from mozilla then.

Can't reproduce on Nightly.

**Comment by gorhill** [comment]
There has to be a limit to the number of browsers I test. If it works fine on Nightly, why should we assume the issue is with uBO with a debug build? This should first be investigated on OP's side rather than asking us to do the investigation as to whether the issue is uBO or the debug build itself.

**Comment by uBlock-user** [comment]
debug builds are like the bleeding edge builds of Chromium, they're not tested for stability or anything, so they can be broken completely.

**Comment by gorhill** [comment]
Not supported then, that is entirely unreasonable to dump such issue here. As mentioned somewhere I am sure, Chromium, Google Chrome, Opera, Firefox, Firefox for Android, or any beta version of these and Nightly are supported.
