### ISSUE TITLE
platform/webext/vapi-webrequest.js breaks uBo functionality

### ISSUE THREAD

**Issue by apoleon** [uBlockOrigin/uBlock-issues#407]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I am the Debian maintainer of ublock-origin. In Debian we build the platform/webext version with  tools/make-webext.sh. The resulting package of version 1.18.2 is broken because ublock does not block any request. After comparing the official Firefox version with the webext version, I have found out that platform/webext/vapi-webrequest.js is the root cause of the problem. If I just replace vapi-webrequest.js with the platform/firefox version, everything works fine again.

In debugging mode I can also see this error message which might be related.

Unchecked lastError value Error: Could not establish
connection. Receiving end does not exist. webrequest.js:115
 
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. In Debian: Build ublock-origin from source by using the make-webext.sh script.
2. Install the resulting Debian package with dpkg -i *.deb
3. Start Firefox.
4. The addon shows up, everything looks normal but it does not block any requests.

### Expected behavior:

Bad requests are blocked.

### Actual behavior:

No requests are blocked. Only the original hostname is displayed when I toggle "All"

### Your environment

* uBlock Origin version: 1.18.2
* Firefox 63.0.1
* Debian/GNU Linux (amd64), Debian 10 "Buster".

**Comment by gorhill** [comment]
> In Debian we build the platform/webext version with tools/make-webext.sh

Is there a way in Debian to install both the Firefox and Chromium versions of uBO when someone install the package?

The thing is this is quite complicated to maintain a webext version which is a version that must dynamically switch on/off different code paths depending on whichever browser from which uBO is being executed. Ideally, the switch would be at install time rather than at runtime.

**Comment by gorhill** [comment]
Never mind, I figured I can stitch together both webext flavors of `vapi-webrequest.js` so that I won't have to maintain a 3rd version -- which is the cause of the issue here, I just forgot about the webext version, as it exists strictly for Debian install.
