### ISSUE TITLE
Unable to whitelist blocked domains directly from toolbar button

### ISSUE THREAD

**Issue by colbycdev** [uBlockOrigin/uBlock-issues#408]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Click on ublock icon in toolbar
2. Don;t see the connected domains

### Expected behavior: Click on the button in the toolbar, and see the domains that attempted to connect, and whitelist/blacklist as necessary

[What you expected to happen]

### Actual behavior: I have to dig through settings, and manually whitelist all sites. I can no longer troubleshoot if a blocked domain is causing issues on a site

[What actually happened]

### Your environment

* uBlock Origin version: 1.18.2
* Browser Name and version: Firefox 64.0
* Operating System and version: Ubuntu 18.04

**Comment by uBlock-user** [comment]
Click on the _domains connected/requests blocked_ to expand the dashboard.

**Comment by colbycdev** [comment]
That seems to do nothing on mobile
However, on desktop, thanks for the tip. Did not see that. Now I feel like/am a total moron

**Comment by uBlock-user** [comment]
Are you an [advanced user](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) ?

**Comment by colbycdev** [comment]
Yes. I know Firefox mobile sometimes handles extensions oddly though, so it might just be that
Still kicking myself about that on desktop. Didn't even think to click there

Tuesday, 29 January 2019, 09:02AM -05:00 from Saitama notifications@github.com<mailto:notifications@github.com>:


Are you an advanced user<https://github.com/gorhill/uBlock/wiki/Advanced-user-features> ?

**Comment by gorhill** [comment]
>  know Firefox mobile sometimes handles extensions oddly though, so it might just be that

It works fine on Firefox mobile. The panel may appears below that of the main pane, because of horizontal space constraints -- so scroll down if you do not see it on the left.

**Comment by colbycdev** [comment]
Uninstall and reinstall on mobile and now it worked. Sorry for all the trouble

Tuesday, 29 January 2019, 10:39AM -05:00 from Raymond Hill notifications@github.com<mailto:notifications@github.com>:


know Firefox mobile sometimes handles extensions oddly though, so it might just be that

It works fine on Firefox mobile. The panel may appears below that of the main pane, because of horizontal space constraints -- so scroll down if you do not see it on the left.

**Comment by colbycdev** [comment]
It appears to the left
Just shrinks the main pane
The reinstall probably has to do with my setup-I have Firefox on external storage, when it's supposed to be internal. I have only about 7gb usable storage, and Firefox uses ~400mb before any cache or data. I installed UBlock before I moved Firefox

Tuesday, 29 January 2019, 10:53AM -05:00 from Raymond Hill notifications@github.com<mailto:notifications@github.com>:


Uninstalling/installing is bad advice, this had nothing to do with making it work -- as said the pane may appear below that of the main pane.

**Comment by gorhill** [comment]
> It appears to the left 

In landscape mode. In portrait mode it's below on my side.

**Comment by colbycdev** [comment]
It's on the left in portrait mode.

Tuesday, 29 January 2019, 11:56AM -05:00 from Raymond Hill notifications@github.com<mailto:notifications@github.com>:


It appears to the left

In landscape mode. In portrait mode it's below on my side.

**Comment by gorhill** [comment]
Can I see a screenshot of this? I am not able to get this behavior on my side in portrait mode.

**Comment by colbycdev** [comment]
I believe I replied with an attachment of a screen shot last timem
I did by email, though. Here is a link
https://photos.app.goo.gl/AtW2Gxv1rivHjCaX6

Tuesday, 29 January 2019, 00:11PM -05:00 from Raymond Hill notifications@github.com<mailto:notifications@github.com>:


Can I see a screenshot of this? I am not able to get this behavior on my side in portrait mode.
