### ISSUE TITLE
The Norwegian list has a new URL now

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#41]
Hello again. I decided to change the URL of _Dandelion Sprouts norske filtre_ from https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ExperimentalNorwegianList.txt to https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt, since the list has definitely progressed beyond merely being experimental.

Would it possible to update its URL in uBO's default lists accordingly, or?

**Comment by uBlock-user** [comment]
Wait till gorhill decides.

**Comment by DandelionSprout** [comment]
Ah, okay. The old link will still work in the meantime, but will be less frequently updated.

**Comment by gorhill** [comment]
`assets.json` is updated after 13 days, so keep your older list for at least 13 days to be sure no subscribers to your list are going to lose their subscription.

**Comment by DandelionSprout** [comment]
Ah, okay. I'll make sure to keep the old list around for at least another two weeks, then.

**Comment by gorhill** [comment]
Correction, I was confused: they would not loose their subscription, it's just that the attempt at downloading an up to date version would fail, with no other consequence than an out of date list.

**Comment by jspenguin2017** [comment]
@gorhill uBO doesn't recognize `hour` as unit of time, and will default to 5 days instead, do you want a PR to fix it? 
(The behavior in Nano is `hour` is rounded up to nearest day)

**Comment by jspenguin2017** [comment]
@DandelionSprout Yes, uBO's doc/wiki is known to be pretty horrible, a lot of details are buried in release notes which are not indexed. The code itself does have some useful comments embedded, and I use `grep` a *lot* to find what I'm looking for. 

I am trying to write some docs for both uBO and my fork. I have some deep implementation details available [here](https://github.com/NanoAdblocker/NanoCore/blob/master/notes/filter-list-authoring.MD#-expires-time-or--expires-time) about the expire header parsing logic. 

Note that uBO will take the first valid expire header, so if you have:
```
! Expires: 12 hours
! Expires: 1 day
```
uBO will take the 1 day. I'm not sure how ABP will act when there are duplicate headers though. 

---

uBO is very tolerant when it comes to filters syntax and have no problem throwing out part of your filter if it doesn't like it. I patched the filter parser to expose all these quirks, this is one of the major feature of my fork and I find it a *lot* easier to write correct filters on the first shot. It does slow down filter parsing for all filter lists though. 
![image](https://user-images.githubusercontent.com/7283682/40095926-ab871e40-588b-11e8-907b-eb18d5ff1e61.png)

**Comment by DandelionSprout** [comment]
The linked-to documentation does look pretty good to me, but it'd be even better if it also covered uses in Adblock Plus and Adguard, since although I estimate through a user survey that more than 90% of the users of my Norwegian list are using uBlock Origin, I wouldn't want to break compatibility with other blocker tools.

As for the expire header, I decided to try with a
`! Expires: 12 hours (Adblock Plus)`
`! Expires: 1 day (uBlock Origin)`
setup now to alleviate potential confusion, in the hopes that paranthesises are allowed in the expire tag.

And as for keeping the old list around, I suddenly realised an hour ago that _"Wait a minute. Why don't I just make use of the !#include tag to link the old list to the new list?"_, and it seems to me to have worked out splendidly.

**Comment by jspenguin2017** [comment]
@DandelionSprout I'm not familiar with internal working of ABP and Adguard, I can link to their documentation but I can't be 100% sure unless I investigate the code. There could be more than one way to interpret the documentation but there is only one way to interpret the code. Also documentation could contains simplifications, for example, I said you need to have subscribe links present in the document when `load` event is fired, but actually, it is 997 milliseconds after `load` event is fired. This also means those links won't work until 997 milliseconds after `load`. 

And yes, `!#include` pre-processing directive will work, it is not ideal for long term as it does create two requests.

**Comment by DandelionSprout** [comment]
> As an effort to document uBO, you can ask me any implementation details and I'll document them.

Now that you mention it, there are a few things about list syntaxes that I've always been curious about:

• Does the expire header have to use UTC, or does it support other timezones as well, e.g. CEST (Central European Summer Time)?
• If a header also contains other words, does it become invalidated or not? E.g. using `! Sist endret / Last Modified:` as the Last Modified header, since "Sist endret" is the term's Norwegian translation.
• Is there any way in which it'd be possible to add filters for a browser's default startpage, e.g. for Edge's not particularly good MSN-based startpage?

**Comment by jspenguin2017** [comment]
@DandelionSprout 
- Expire header is a time *interval*, has nothing to do with UTC, I think it is clear enough in my doc. 
- As stated in my doc, only title and expires are parsed. 
- No, protected origins are protected. I have noted this down, I'll write a detailed doc later. As a side note, installing apps can add protected origins, for example, the YouTube app will turn `youtube.com` into a protected origin. 

---

As for the expires header in hour, I think the low cap being 1 day is healthy, it prevents abuse; but for things like 30 hours, I don't think having a float in the data object would break stuff, I haven't tested it though. I have a 60 day upper cap in Nano because if the length overflows to `Infinity`, it could break manual update (actually 49 years should be enough to break it... until 2019).

**Comment by DandelionSprout** [comment]
Ah, okay. My first question was meant to be about the Last Modified header instead of the Expires header, but now that I know that it's not an actually important header anyway, I now know that the wording of Last Modified doesn't really matter anyway, which is kind-of why I asked all these questions so that I could learn about them properly. Thanks for teaching me about it.

**Comment by jspenguin2017** [comment]
Anyway, back to the semi-original topic, I propose the following behavior for expires header parsing: 
- If the header is present:
  - If it uses hour, device it by 24 and turn it into a float, which should work just fine
  - If the interval is less than 1 day, bump it up to 1 day; if the interval is more than 365 days, cap it at 365 days
- If the header is not present: 
  - If there is already a value (from `assets.json` or previous expires header), keep it as-is unless it is less than 3 days, in which case it is bump up to 3 days (or 5 days? This is to prevent mistake from filter maintainer making filter update more frequently than they should, as I think most people would believe removing the header will reset it)
  - Otherwise, default to 5 days

**Comment by gorhill** [comment]
> do you want a PR to fix it (make hour round up to nearest day)?

Sure. Thanks.

**Comment by jspenguin2017** [comment]
@DandelionSprout I have investigated ABP's code, it will take the *last* header, even if it is invalid, and validate it later. So if you have: 
```
! Expires: 3 days
! Expires: three days
```
ABP will take the second header, and realize later that it is not good, and fallback to default expire time. 

So you want: 
```
! Expires: 1 day (uBO)
! Expires: 12h (ABP)
```

uBO will support `! Expires: 1d` on the next release, but not yet. ABP accepts `1d`, `12h`, etc. 

---

As a side note, Nano on Edge behaves differently than uBlock Edge, some filters won't be compatible. uBlock Edge treats `fetch` as different than `xhr` but Nano doesn't.

**Comment by gorhill** [comment]
@nikrolls fyi

> uBlock Edge treats fetch as different than xhr but Nano doesn't.
