### ISSUE TITLE
Blocking Scripts Despite Scripts Enabled

### ISSUE THREAD

**Issue by AndroidKitKat** [uBlockOrigin/uBlock-issues#412]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Scripts are disabled which causes many websites to not function as intended

### A specific URL where the issue occurs

https://www.chegg.com/search/tes/federated?trackid=504991e9eaba&strackid=0aaa533b8c9f&event=enter_submit#p=1

### Steps to Reproduce

1. Cycle scripts being  disabled and then enabled
2. Visit a webpage that uses scripts
3. Check browser console log and see Scripts being blocked by client
4. Confirm uBlock Origin is the issue by disabling and uninstalling the extension and confirming those webpages work

### Expected behavior:

Scripts are enabled

### Actual behavior:

Scripts are disabled. This is found by checking the browser console and seeing "Script was blocked by client" as error

### Your environment

* uBlock Origin version: uBlock Origin 1.18.2
* Browser Name and version: Google Chrome Beta 72.0.3626.81
* Operating System and version: macOS 10.13.6

**Comment by uBlock-user** [comment]
> Check browser console log and see Scripts being blocked by client

> Scripts are disabled. This is found by checking the browser console and seeing "Script was blocked by client" as error

![](https://i.gyazo.com/2835a9d4d38bc276a5547e98cc81a13c.png)

There are filters from various filterlists activated which are blocking some javascripts and some xhrs as per logger. You didn't check the logger. Relying solely on the console will not give you the reason for the  blockage.

**Comment by gwarser** [comment]
>     1. Cycle scripts being  disabled and then enabled


You are talking about this button <https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting>?

This button disables scripts. It does not enable them. All other blocking filters/rules still apply.
