### ISSUE TITLE
Peoblem when open a link in Gmail or Twitter app.

### ISSUE THREAD

**Issue by thelastfantasy** [uBlockOrigin/uBlock-issues#417]
![screenshot_20190210-083645](https://user-images.githubusercontent.com/6077584/52527646-97707600-2d0f-11e9-988d-42018ccf2dc6.jpg)
![screenshot_20190210-083649](https://user-images.githubusercontent.com/6077584/52527647-9d665700-2d0f-11e9-93ec-0cdcba44d6a3.jpg)
![screenshot_20190210-083808](https://user-images.githubusercontent.com/6077584/52527651-aa834600-2d0f-11e9-8f54-46bad4a707f0.jpg)
![screenshot_20190210-083815](https://user-images.githubusercontent.com/6077584/52527656-b53ddb00-2d0f-11e9-8b31-e0f01fd98030.jpg)
I know the reason is Gmail and Twitter addes redirect link to the URL, but if I opening this url with firefox, no problems will happen. How can I get this solved?

**Comment by uBlock-user** [comment]
Put back the template and fill it as requested.

**Comment by gorhill** [comment]
Probably <https://bugzilla.mozilla.org/show_bug.cgi?id=1496684>.
