### ISSUE TITLE
Logger filter dropdown arrow inconsistent

### ISSUE THREAD

**Issue by stonecrusher** [uBlockOrigin/uBlock-issues#418]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Very small UI issue. In logger, filter dropdown arrow behaviour is inconsistent.

### A specific URL where the issue occurs
/logger-ui.html

### Steps to Reproduce
1. Click on the filter dropdown (`#filterExprButton`) to show `#filterExprPicker`.
2. Move mouse pointer out of `#filterExprPicker` so it disappears.

### Expected behavior:
Remove class `expanded` from `#filterExprButton` on closing `#filterExprPicker`.

### Actual behavior:
The class `expanded` is added/removed to `#filterExprButton` only on click. So it often happens that the arrow points up without having the filterExprPicker visible.

### Your environment
* uBlock Origin version: 1.18.4
* Browser Name and version: FF 65.0x64
* Operating System and version: Win8.1x64

**Comment by gwarser** [comment]
This button toggles between "visible on hover" and "not visible"

**Comment by stonecrusher** [comment]
Hmm ok I had in mind the dropdown behaviour, thererfore the confusion.
Maybe change the tooltip to a more explaining "Toggle visibility of logger filtering options".
I'll make a note for uBO wiki on my "do this if you're bored"-list.
Thanks!
