### ISSUE TITLE
HTML filters occasionally lost effectiveness

### ISSUE THREAD

**Issue by Crystal-RainSlide** [uBlockOrigin/uBlock-issues#42]
### Prerequisites

- [ ] I verified that this is not a filter issue
    
- [ ] This is not a support issue or a question
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
An ad script in `https://www.baidu.com/s?wd=%E7%9A%AE%E9%9E%8B`

```
<script id="ecomScript">
...
<script>
```

I tried to remove it with `www.baidu.com##^script#ecomScript`, but I found that only `script:contains()` is supported.

Then I took some time with the code and got 'setAdsHeight' in the js outline from Firefox's dev tools, then everything works fine, but the time has gone.

Certainly CSS Selector don't support this, but adblocks may support it for simplifing the rules&filtering.

### A specific URL where the issue occurs

All website equipped with `<script foo="bar">`

### Steps to Reproduce

Descripted↑

### Expected behavior:

example.com##script#id

### Actual behavior:

Nothing happens & desired filter don't work

### Your environment

* uBlock Origin version: Newest
* Browser Name and version: Firefox Developer Edition 61.0
* Operating System and version: Windows 7 Customed.

**Comment by Crystal-RainSlide** [comment]
One other thing...

I mistaked the outdated fork source of fang5566/uBlock , which is the offical Chinese (中文) introduction&wiki , and posted https://github.com/uBlockAdmin/uBlock/issues/1767 . 

Then I got a ban at https://github.com/gorhill/uBlock/issues/new for that misposted issue.

WHY???

**Comment by gorhill** [comment]
There is no ban on `https://github.com/gorhill/uBlock/issues/new`, it's just reserved to former contributors. Here is the proper issue tracker.

**Comment by gwarser** [comment]
`ecomScript` is already gone. I tested on `script id="head_script"` and cannot reproduce.

**Comment by gorhill** [comment]
@Crystal-RainSlide HTML filtering will only match what is in seen in `view-source:`, not what is dynamically added afterward.

**Comment by gorhill** [comment]
@gwarser Yes, cofirmed it works fine with `www.baidu.com##^script#head_script`, the script element is present in `view-source:`, and I confirmed it was properly removed by the above filter, so the syntax works, it's just a matter of filtering what is present the source data as per `view-source:`.

**Comment by gwarser** [comment]
When I tested this earlier `ecomScript` was present, but disappeared after refresh or two. This and my assumption that content of `view-source` should be filtered, misleaded me to think that something is not working. But now I'm pretty sure all is working.

@Crystal-RainSlide why you think that only `script:contains()` is supported? Plese, provide detailed steps to reproduce.

**Comment by uBlock-user** [comment]
> When I tested this earlier ecomScript was present, but disappeared after refresh or two. 


Still there on my end - https://i.imgur.com/xZr5QIe.jpg

**Comment by uBlock-user** [comment]
`script:contains()` is only supported on Firefox-legacy branch, you must have installed that build instead of WebExtension build.

**Comment by gorhill** [comment]
`script:contains()` is deprecated syntax, it internally is converted to `script:has-text()` -- true for either Firefox legacy or webext.

**Comment by Crystal-RainSlide** [comment]
Sorry for my half day long offline.

#### About `script#ecomScript` 's disappearing

Whether _things like business ads, ecomScript_ will appear depends on Baidu's advertising strategy. 皮鞋 means leather shoes, a kind of commodity, so this search word would cause ecomScript appearing in my test. But Baidu's ad market is mainly in China, so do the advertisers. So ecomScript may disappear in your tests for oversea customers are less likely to click ads.

#### About reproduction

 I also failed to reproduce it after Firefox update automatically. But I got some other results:

![content_right](https://user-images.githubusercontent.com/16851802/40088906-ca58c896-58db-11e8-810f-98e29c741f95.png)

↑ I've stayed with `www.baidu.com##^#content_right` for a long time, but it lost effectiveness when I'm reproducing.

So it seems like a stability problem but not an unsupported syntax... I'll go on with more tests.

**Comment by Crystal-RainSlide** [comment]
DONE, reproduced on my 

> Firefox Developer Edition 61.0

#### Steps

(0. Open the The logger to verify whether HTML filters work?)
1. Pick an element which will definitely appear (but not body) and block it with ^. Pick an element is for obviousness. I used `www.baidu.com##^#head` this time.
2. Open https://www.baidu.com/s?wd=%E7%9A%AE%E9%9E%8B in a tab. That element should be removed aright.
3. Right click on that tab and duplicate it.
4. Check the duplicated tab. That element should appear again.

Then, Chrome... Note that I'm using Cent Browser, not offical Chrome.

**Comment by gwarser** [comment]
I can reproduce once out of 10 attempts. This happens when page is loaded from cache:

![screenshot_20180516_103847](https://user-images.githubusercontent.com/886325/40106213-72231fd6-58f5-11e8-85c2-d8cc11d94dfc.png)

**Comment by uBlock-user** [comment]
`www.baidu.com##^#head` doesn't work on my end, I can reproduce every time and #head appears in the view-source of both tabs -- original and duplicate.

**Comment by gwarser** [comment]
Weird thing - I can easily reproduce on https://github.com/ with `github.com##^#user\[login\]`, but it's very hard with `github.com##^form`

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/3618

**Comment by gorhill** [comment]
> I can reproduce every time and #head appears in the `view-source` of both tabs -- original and duplicate.

`view-source:` is to be use to find out what can be filtered, not what has been filtered. Firefox bypass uBO when requesting a page via `view-source:`.

**Comment by uBlock-user** [comment]
You're right, I just tested `##.cr-content`  with `baidu.com##^.cr-content` and it works as expected.

**Comment by gorhill** [comment]
> Then, Chrome... Note that I'm using Cent Browser, not offical Chrome.

HTML filtering is not supported on Chromium-based browsers, it's missing the proper API.

**Comment by gorhill** [comment]
I can reproduce sporadically when using the "duplicate tab" trick. When the issue occurs, the HTML filter is not reported in the logger. I will keep investigating.

**Comment by gwarser** [comment]
Actually `Cache-Control: no-cache, must-revalidate` (set by https://addons.mozilla.org/firefox/addon/header-editor/) may help, but only after browser restart.

**Comment by gorhill** [comment]
Yes, I was looking at this: <https://bugzilla.mozilla.org/show_bug.cgi?id=1376932>.

I confirm that when the issue occurs, uBO's onHeadersReceived listener is not being called at all, Firefox bypasses uBO, hence uBO can't do its job.

**Comment by uBlock-user** [comment]
So this is a browser bug ?

**Comment by gorhill** [comment]
Yes, but I need to provide a workaround given the seriousness of it: one main use of HTML filtering is to remove unwanted specific inline script tag, and the issue here means this could lead to unwanted inline script code being executed. Beside, this should also solve the issue described in <https://bugzilla.mozilla.org/show_bug.cgi?id=1376932> -- NoScript is being mentioned but uBO does also suffers from it (also uMatrix: <https://github.com/gorhill/uMatrix/issues/893>).
