### ISSUE TITLE
uBlock & uMatrix Lists Mirror

### ISSUE THREAD

**Issue by v00v** [uBlockOrigin/uBlock-issues#421]
I've been a uBlock/uMatrix user for many years now and love it. I personally think that this projects are the most important in internet history. Because it the only thing that helps regular users to project against giant corporations. I'm actually surprised that its not more popular, maybe because its not advertised much. I always had an issue with lists updating too slow or even links broken. For a long time I was thinking about dedicated mirror for this lists. So I would like to ask for your permission to possibly run a mirror for this lists on cloud vps server. I can sign this lists with MD5/SHA/PGP for security. I have a good short domain name (I can reveal it here if you ask) and I was thinking doing something like (https://mirror.domain.ext/lists/ublock/<list-file-name>(lst|md5|sha|pgp) easy to remember names like that. Then you can use it in your extensions for others to update. I know that this may require a lot of traffic, but I'm willing to do this experiment to see how it goes. Starting one small hetzner cloud vps with 20tb/month traffic. I can code a script to automate the process of grabbing this lists from other sites when they are updated and then signing them.

**Comment by uBlock-user** [comment]
uMatrix has HOSTS list, not filter lists btw..

**Comment by v00v** [comment]
I don't really care what it is HOSTS or LSTs I was offering to do a mirror.

**Comment by uBlock-user** [comment]
This isn't a uBO bug, hence invalid as this tracker is for bugs related to uBO.

**Comment by v00v** [comment]
Thank you for the tag and please don't close this post. I'm serious about this offer, just did not know were to post =( Thanks for your help!

**Comment by uBlock-user** [comment]
reopened as FR..

**Comment by v00v** [comment]
Can I just change my title with "FR" ? or How do you want me to name this properly?

**Comment by uBlock-user** [comment]
No change needed, I added the enhancement tag.

**Comment by v00v** [comment]
Oh okay, thank you for your help again!

**Comment by gorhill** [comment]
> dedicated mirror for this lists

This would mean the statement "uBO has no home server" wouldn't hold anymore, hence I prefer to decline. Add to this that I do not know you, you have no track record with this project, it would be bad judgment on my part to have all uBO users rely on a single server for lists hosting which is maintained by an unknown party.

**Comment by v00v** [comment]
@gorhill and simply signing this lists wont' work? Okay, just thought I would offer. No worries. Keep up the good work!

**Comment by gorhill** [comment]
> dedicated mirror for this lists?

That's not the only issue, centralizing list hosting also causes whoever maintain the server to have access to server logs, from which information can be gathered: IP+UA of whoever using uBO, which lists are fetched, time of fetch. I am sure this kind of information would be useful to advertisers, data miners, so I rather keep uBO server-less.
