### ISSUE TITLE
$inline-script,domain tests for top-level domain, not the inline-script document's

### ISSUE THREAD

**Issue by ettavolt** [uBlockOrigin/uBlock-issues#422]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

``@@*$inline-script,domain=domain2`` doesn't enable inline scripts in a frame from domain2 (child) on a domain (parent).
not enough to enable youtube videos in a frame.

### A specific URL where the issue occurs

https://youtubevideoembed.com/

### Steps to Reproduce

1. Configure
```
*$script,inline-script
@@s.ytimg.com$script
@@*$script,inline-script,first-party,domain=youtube.com
```
2. Visit https://youtubevideoembed.com/
3. Observe no video poster.
4. Add ``@@||youtube.com^$inline-script``.
5. Refresh https://youtubevideoembed.com/
6. Observe video poster.

### Expected behavior:

``$inline-script,domain=domain2`` checks domain of the iframe, not the parent.

### Actual behavior:

It seems to check parent's domain.

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Mozilla Firefox 65.0.0
* Operating System and version: Arch Linux for amd64

**Comment by ettavolt** [comment]
The interesting thing, that ``@@*$script,first-party,domain=domain2`` works as expected: blocks domain2 scripts if injected into a page on domain, but allows if it's in a domain's frame from domain2.

**Comment by uBlock-user** [comment]
Wasn't this fixed already ?  -- https://github.com/uBlockOrigin/uBlock-issues/issues/402

**Comment by gorhill** [comment]
It's a regression introduced with 9b27a98f901d.

**Comment by gorhill** [comment]
#402 was an issue related to base domain-less hostnames.  Here is an issue with evaluating in wrong context -- `inline-script` are a special case.
