### ISSUE TITLE
Add additional annoyances filter list against cookie notifications

### ISSUE THREAD

**Issue by xolyu** [uBlockOrigin/uBlock-issues#426]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It would be nice, if the cookie filter list "I don't care about cookies" would be added to annoyance lists.

It is a really huge filter list with more than 15 thousand rules. For me in Germany it does a really good job.

- List title: `I don't care about cookies`
- List URL: <https://www.i-dont-care-about-cookies.eu/abp/>
- Project homepage: <https://www.i-dont-care-about-cookies.eu/>

### A specific URL where the issue occurs

-none-

### Steps to Reproduce

1. Open uBlock Settings
2. Check filter lists

### Expected behavior:

Expand annoyance lists part, find _I don't care about cookies_ and select to activate that filter list.

### Actual behavior:

Filterlist is not present. You have to add them manually as custom list by copying or typing URL.

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Vivaldi 2.3.1440.48
* Operating System and version: Windows 7 x64

**Comment by uBlock-user** [comment]
> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

https://github.com/uBlockOrigin/uBlock-issues#ublock-issues

**Comment by gorhill** [comment]
The author of that list recommends people uses his extension. I don't want to undermine his recommendation.
