### ISSUE TITLE
russian companies bought you?

### ISSUE THREAD

**Issue by Nikolay-Kha** [uBlockOrigin/uBlock-issues#428]
Just created an issue here. Number 427. And it was closed in 1 minute... there were even no time to read this issue. Looks like issue was blocked automatically by bot. And most probably keywords of sitenames was a reason.
Consider this automated blocking and ads on that website appears with no reason, I guess that they paid to be not blocked... okay, will move to another software. Hope people will read this closed issue and will move to another ad blocking software too.

**Comment by mapx-** [comment]
You have to report in the right place:
https://github.com/uBlockOrigin/uAssets/issues

More - you should use js fixes (in tampermokey) which fixes a lot of russian sites.

**Comment by uBlock-user** [comment]
> Just created an issue here. Number 427. And it was closed in 1 minute

Filter list issues will get closed.

**Comment by Nikolay-Kha** [comment]
Thank you for explanation and sorry for creating duplicates.
But still, is it really filter issue? Looks like there is no way to express in filter rules how to block such ads. Such ads can be blocked using injected js only. May be there is a point to create some additional mechanism inside uBlock origin to stop such ads? If that possible on russian web sites, that soon such ads can appear in other places.

@mapx- thank you very much. Exactly that user script finally removed ads.

**Comment by gorhill** [comment]
> is it really filter issue?

Such issues will always be first looked at as a filter list issues. If ever we realize nothing can be done, then it may become a uBO issue if we decide that adding features to uBO would help address the specific issue and generally help everywhere else too.
