### ISSUE TITLE
regexp for domain

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#429]
How do you look at adding regexp for a domain?

exp:
`||site.domain$domain=site.*`

You are currently blocking only a specific domain, for example `com`
`||site.domain$domain=site.com`

but this is not always convenient, when there are many domains. What do you think?

and yea
If suddenly the idea is good, then for the "My Rules" tab it would be wonderful to see regexp
![default](https://user-images.githubusercontent.com/8535285/52921844-7e9b3c80-336f-11e9-8d42-b4faae400e86.png)

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.
