### ISSUE TITLE
Cosmetic Filters Should Not Be Created in Element Picker When Cosmetic Filters Are Disabled

### ISSUE THREAD

**Issue by Rictusempra** [uBlockOrigin/uBlock-issues#43]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A.T.

### A specific URL where the issue occurs

e.g., this page, https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. install UBO and disable cosmetic filters
2. enter element picker mode
3. create a rule

### Expected behavior:

Cosmetic filters should not be created

### Actual behavior:

Cosmetic filters are created

### Your environment

* uBlock Origin version: 1.16.6
* Browser Name and version: Firefox 60 64-bit
* Operating System and version: Windows 10 1803 latest

**Comment by gorhill** [comment]
Unable to reproduce: I can't enter the element picker when cosmetic filters are disabled (https://github.com/gorhill/uBlock/issues/3212).
