### ISSUE TITLE
Implement machine-learning based adblocking

### ISSUE THREAD

**Issue by KOLANICH** [uBlockOrigin/uBlock-issues#430]
### Prerequisites
- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Today I have opened `e.mail.ru` and saw ads, lot of them. Looked into the source - it was full of countermeasures (somehow resembling obfuscation by adding random junk, like randomizing nesting and using random ids) to cheat adblockers. 

I guess we may need to apply machine learning.
Fortunately there is a [preprint](https://arxiv.org/pdf/1805.09155.pdf) , though I have found no impls. So we need a feature extraction framework in μBO and some way to apply serialized XGBoost models to evading websites. I guess filterlists are to be distributed in CBOR format, cosisting of an array of records, each record consists of a website, and an XGBoost model in binary format. XGBoost model is to be transpiled into JS or WASM if-else code and run against the feature vector. We would also need a way to collect feature vectors from users.

BTW, @too4words , have you tried features extracted from geometry and CSS (bounding boxes and other styles), attrs and count of descendants of each type?

**Comment by uBlock-user** [comment]
> Today I have opened `e.mail.ru` and saw ads, lot of them. Looked into the source - it was full of countermeasures (somehow resembling obfuscation by adding random junk, like randomizing nesting and using random ids) to cheat adblockers.

So report it on https://github.com/uBlockOrigin/uAssets/issues, that's hardly any valid reason to suggest machine learning which is not something that can be done to Extensions.

**Comment by gorhill** [comment]
Whoever is free to work on a working prototype and I will be happy to look at it.

**Comment by KOLANICH** [comment]
>So report it on https://github.com/uBlockOrigin/uAssets/issues

I'm afraid it may be impossible to write a good enough filter using the current rules language. CSS selectors gonna fail - layout changes on every page reload. So the solution here is either a custom JavaScript heuristically finding the ads by their `boundingClientRect`s, or a machine-learning model.

**Comment by jawz101** [comment]
An example of an old add-on that was more heuristic-based was https://github.com/arantius/karma-blocker.  Another example is Privacy Badger's heuristics.

Aside from that you might be able to look at any university research project whitepapers to see if there is any merit to the idea.

**Comment by vrobolab** [comment]
New mail.ru interface generates random element names, including the main panel with email messages list and embedded ads panel, thus making element picker useless, as every refresh of the mail.ru page generates new name for the ads panel.

This is what the interface looks like, ads on the right panel: https://i.imgur.com/2BkDBN0.png

uBlock element picker window: https://i.imgur.com/xCPX1YA.png
"dRI8TSu" div is still the main content, and ads are inside "dRI8T4v_dRI8T4C.dRI8T4v" div. And these names are randomly generated on every page load.

Firefox element inspector window: https://i.imgur.com/T8BpEKL.png

As far as I understand there is no way to block such ads currently, right?

**Comment by KOLANICH** [comment]
I guess the first thing we can do is geometry-based blocking. I mean if we can detect elements purpose based on their location on a page. I mean store boxes in the base and their purpose, then match the boxes on a page to boxes in the base,

**Comment by ZaphodBeebblebrox** [comment]
These ads are blocked by RU Adlist, which you can enable under regional filters.
