### ISSUE TITLE
undefined in uBo logger

### ISSUE THREAD

**Issue by setyb** [uBlockOrigin/uBlock-issues#432]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I may have accidentally discovered a bug in the uBo logger.

The symptom is getting a request line in the logger that says:

`[URL]/undefined`

See also: https://github.com/bitwarden/web/issues/351

### A specific URL where the issue occurs

`https://vault.bitwarden.com/`

### Steps to Reproduce

Here are steps to reproduce. It's a little effort, but doing this, I get 100% reproducibility.

1. Test box: Firefox v65.0.1 64-bit with bitwarden v1.38.0, uBo v1.18.4 extensions.
2. Turn off all third-party cookies in FF (that's how test box was configured).
3. Create a test bitwarden account (free).
4. Open the bitwarden web vault at https://vault.bitwarden.com/
5. Open the uBo logger.
6. Go back to the bitwarden web vault tab.
7. Log in to the bitwarden web vault; don't select the option to remember the email address.
8. Wait for the bitwarden web vault to load.
9. Switch to the uBo logger tab.
10. Find the entry `https://vault.bitwarden.com/undefined` in the log.

Firefox devtools do not report that actual request, so it points to an issue in the uBo logger.

If I take a quick guess, uBo logger is possibly picking up a request that it doesn't know how to categorize, and therefore the `undefined`.  But that's just a quick first guess.

### Expected behavior:

No `undefined` entries in the uBo log.

### Actual behavior:

`undefined` entry in the uBo log.

### Your environment

1. Test box: w7, Firefox v65.0.1 64-bit with bitwarden v1.38.0, uBo v1.18.4 extensions.

**Comment by uBlock-user** [comment]
Can't reproduce this on Chromium.

**Comment by uBlock-user** [comment]
> If I take a quick guess, uBo logger is possibly picking up a request that it doesn't know how to categorize,

It's categorised as image, so that's not the issue.

**Comment by setyb** [comment]
@uBlock-user 

> It's categorised as image as per the logger, so that's not the issue.

Unless, of course, it is miscategorized.  I don't know.

I take it you were able to reproduce this issue on Firefox?

**Comment by uBlock-user** [comment]
> Unless, of course, it is miscategorized. I don't know.

That's unlikely as uBO listens to all the requests seen by webRequest API of Firefox, so it's not making anything of its own.

> I take it you were able to reproduce this issue on Firefox?

Yes.

**Comment by gorhill** [comment]
Does that `https://vault.bitwarden.com/undefined` URL also appear in the Network pane in the page's dev tools?

**Comment by uBlock-user** [comment]
No, that doesn't happen.

**Comment by gorhill** [comment]
Appears to be a Firefox issue. I put in code to log what uBO receives in its onBeforeRequest handler and what it sends to the logger, and this is the result:

![b](https://user-images.githubusercontent.com/585534/53018866-700d5d80-3421-11e9-99cf-3911fdda2720.png)

The first line is what uBO is given by the webRequest API:

    {
        "requestId":"237",
        "url":"https://vault.bitwarden.com/undefined",
        "originUrl":"https://vault.bitwarden.com/#/vault",
        "documentUrl":"https://vault.bitwarden.com/#/vault",
        "method":"GET",
        "type":"image",
        "timeStamp":1550583136220,
        "frameId":0,"parentFrameId":-1,
        "proxyInfo":null,
        "ip":null,
        "frameAncestors":[],
        "tabId":7
    }

**Comment by setyb** [comment]
Thanks @gorhill 

Can you submit a bug report to Mozilla?  I think if it comes from you, with your excellent reputation, it will get handled more efficiently than if it comes from someone else.

Plus, you'll be able to explain the details better than anyone else.

**Comment by setyb** [comment]
@gorhill Do you think you could file a bug report with Mozilla, sir?

**Comment by gorhill** [comment]
It could very well be a bitwarden site issue, I don't want to open an invalid issue in bugzilla -- this would need to be investigated this first. I don't have the time, it does not have to be me.

**Comment by gavin20** [comment]
Identified similar issue in Chrome - logger continually displays undefined entries (**https://undefined** ) until the website is closed. Is it possible to ignore logging for this entry or identify root cause?

`||undefined^$script,domain=hevcbay.com`

`Filter
hevcbay.com https://undefined script block
Context
hevcbay.com
Partyness
(3) hevcbay.com ⇒ undefined
Type
script
URL
https://undefined/`

**Comment by llacb47** [comment]
An adnetwork (popads) is probably doing that on purpose to try to serve ads. However, I don't see that in my logger.
