### ISSUE TITLE
Provide a reliable way to detect not needed filter lists

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#433]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
There's currently no reliable way to determine whether enabled filter list contains no unique filters and can be disabled.

Sometimes number of "used out of" filters can help, if it is zero or very small then the filter list is not needed and can be removed. But it is unreliable and depends on order in which filter lists are being processed. If unneeded fiter lists is processed early, then it still shows significant number of "used out of" filters and there is no way to tell that it can be disabled.

For example, Fanboy Annoyance includes Fanboy Cookie and Fanboy Social. But if Fanboy Cookie and Fanboy Social are processed before Fanboy Annoyance, all 3 of them shows significant number of "used out of" filters. With only these 3 filters enabled I can get [this](https://user-images.githubusercontent.com/8005688/53093067-7128b280-3527-11e9-9620-f25e5e507fb0.png) or [this](https://user-images.githubusercontent.com/8005688/53093068-7128b280-3527-11e9-888c-c9ded92defd5.png).

One way to address the issue is to show number of "unique" filters for each enabled filter list — the number of filters that are present in one filter list only. It is zero if and only if the filter has no unique filters and can be disabled. It also doesn't depend on order in which filter lists are being processed.

### Your environment

* uBlock Origin version: v1.18.5b6
* Browser Name and version: Chromium 72.0.3626.109 (64-bit)
* Operating System and version: Windows 10 v1607 x64

**Comment by gorhill** [comment]
> in that one filter list only

How would uBO decides which filter list is "the one"?

In any case, what you seem to ask here will result in adding a significant overhead at filter list load time, not something I want to happen. Feel free to demonstrate a code patch which implement what you want with no added overhead.

**Comment by mikhaelkh** [comment]
> How would uBO decides which filter list is "the one"?

I meant for each enabled filter list show the number of "unique" filters, something that is currently done for "used out of" filters.

> what you seem to ask here will result in adding a significant overhead at filter list load time, not something I want to happen

But that is one way to solve the issue, maybe somebody can think of the way that doesn't require significant overhead.

**Comment by gorhill** [comment]
I will decline this.

However feel free to provide a patch to demonstrate that your idea is feasible in practice.

**Comment by jawz101** [comment]
fwiw, Sometimes what I do is disable>apply and reenable>apply a list to see what is unique.  It seems it might then process that list last so if anything was caught by the other lists lowers the applied count to the last list added.
