### ISSUE TITLE
Add a tooltip for selecting multiple elements in zapper

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uBlock-issues#434]
Currently the element zapper mode only allows zapping one element at a time. Please consider adding an ability to zap multiple elements in a single go.

Perhaps the best way is to include a `Done` button in the overlay interface which could be clicked after zapping the elements.

Another (less preferable) option could be to make it such that the first click on zapper icon enters zapper mode while the second click on it leaves zapper mode.

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Element-zapper>:

> Press the <kbd>Shift</kbd> key while clicking if you do not want to exit element-zapper mode

**Comment by in4u** [comment]
Sorry, my bad! Wasn't aware of this feature. I suggest including a tip for selecting multiple elements (or at least an indication that this is possible) in the zapper's tooltip itself.

**Comment by in4u** [comment]
I am unable to zap multiple elements on mobile. Unfortunately, the wiki isn't too helpful in this case and only mentions:

>On touch screen devices, swipe to exit element-zapper (or element-picker) mode.

The first tap selects an element and second tap zaps that element while simultaneously exiting the zapper mode. Now what am I missing? How to select/zap more elements without exiting zapper mode?

**Comment by krystian3w** [comment]
Buy USB or Bluetooth keyboard? But I no tested this yet (maybe Android no read property pressed <kbd>⬆ Shift</kbd>.

Opptionaly try using firefox remote debug via USB or Wi-Fi?

https://developer.mozilla.org/pl/docs/Tools/Remote_Debugging

**Comment by in4u** [comment]
I was under the impression that the feature I initially requested was natively available on mobile as well, perhaps using some undocumented trick. If it's not then I guess my original post still stands.

Anyway, regardless of my request being considered or denied, external hardware or remote debug is not a practical solution for me. Neither do I intend to carry a mobile keyboard nor do I use mobile for surfing when immediate access to a computer is already available.

**Comment by keenla** [comment]
Double click on `zap` menuicon to enter multizap-thunderstorm mode?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/434#issuecomment-470117136 - Long time ago at mobile was added:

>  On touch screen devices:
> 
> - Tap once to select the element.
> - Tap the highlighted element to remove it.
> - Swipe right to remove the incorrect highlighting.
> - Swipe right to exit element zapper mode.
> 
> Reloading the web page will cause all removed elements to return.

"Recommended" is switch form Firefox 68 Mobile to Firefox 116.

---

https://github.com/uBlockOrigin/uBlock-issues/issues/434#issuecomment-1685216488 - buy a bigger desk, To be able to put down the pint.

If you have a disability, perhaps a mouse is better what has more than 5 buttons and one programmed to act as shift.

**Comment by keenla** [comment]
> [#434 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/434#issuecomment-1685216488) - buy a bigger desk, To be able to put down the pint (Optional small table for pints).
> 
> If you have a disability, perhaps a mouse is better what has more than 5 buttons and one programmed to act as pressing/holding shift e.g. until second click to reset pressing (if these are annoying https://help.gnome.org/users/gnome-help/stable/a11y-stickykeys.html.en).

I am 100% sure, that huge majority of users would prefer "double click option" to that "hold shift key"-version, maybe exept for some people from "shift-key fan club".
And bigger desk would mean more beer, resulting to much more unrestrained comments, probably to level, that becomes demotivating to programmers. So - big no.

**Comment by keenla** [comment]
Try to understand, that people are lazy, but laziness of a programmer will be paid by his creation users, by having more pita and more wasted lifetime on help forums.
in math: 
one hour of programming is one hour
million users trying to find an nonintuitive answer (lets say 1/10 of hour, 6 minutes avg) is hundred thousand wasted hours.

**Comment by gwarser** [comment]
Zapper does not exit after removing elements anymore. Swipe right to exit.
