### ISSUE TITLE
Requests on mousedown aren’t made in Firefox

### ISSUE THREAD

**Issue by dieulot** [uBlockOrigin/uBlock-issues#435]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`instant.page` allows to preload pages on mouseover, but the requests aren’t made on Firefox when hovering over links.

It works normally in Chrome.

### A specific URL where the issue occurs

    https://instant.page/

### Steps to Reproduce

1. Go to `https://instant.page/` with uBlock Origin
2. Open DevTools and its network tab
3. Hover over items in the menu (at the bottom of the site, or on the right for large displays)
4. See that no requests are made. If uBlock Origin is removed these requests are made

### Expected behavior:

No requests are made.

### Actual behavior:

Requests are made.

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Firefox 65.0.1 (64 bits)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
Happens with other content blocking extensions like uMatrix too..

**Comment by gorhill** [comment]
This happens because of the setting "Disable pre-fetching". This works fine when disabling this setting.

It works with Chromium regardless of the setting because with Chromium web sites have higher priority than a user's own setting.

**Comment by dieulot** [comment]
Thanks for the info. Would it make sense (and would it be possible) to allow prefetching on the same origin? I believe there’s no privacy implication to this.

**Comment by gorhill** [comment]
uBO just toggles [a Firefox setting](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/network#Properties), Firefox does the work internally to enforce that setting, so if you want this behavior you have to open an issue with Firefox.

**Comment by dieulot** [comment]
From someone working on Chrome:

> Browsers are increasingly moving to a secure caching model similar to Safari's called double-keyed caching. This is going to break cross-origin prefetch

If cross-origin prefetch ends up not working anymore, would you re-enable prefetching in uBlock Origin by default?
