### ISSUE TITLE
Shortened Links in Element Picker Window

### ISSUE THREAD

**Issue by john7200** [uBlockOrigin/uBlock-issues#436]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In 1.18.4, certain parts, usually long ones, in links shown in element picker window are shortened with asterisks. In 1.17.4, all links are shown in full (not shortened with asterisks).

### A specific URL where the issue occurs

https://instagram.com

### Steps to Reproduce

1. Visit this link: https://www.instagram.com/p/BtSWmIOAleZ/ (this is only an example link, it doesn't have to be this specific link)
2. Right click on the Alita image and click "Block element".
3. Look at the element window:
In 1.17.4, links are shown in full (not shortened with asterisks).
![1 17 4](https://user-images.githubusercontent.com/47649262/53221410-94309f00-36ac-11e9-9309-2e0ecb45ebb0.jpg)
Highlighting the link and dragging it into a new tab to open it will open the link in that tab

In 1.18.4, certain parts of the links are shortened with asterisks.
![1 18 4](https://user-images.githubusercontent.com/47649262/53221450-c17d4d00-36ac-11e9-99ea-7c1ee6561466.jpg)
Highlighting the link and dragging it into a new tab to open it will result in the tab displaying a message "Bad URL timestamp".

### Expected behavior:

All links should be shown in full, or at least there is an option to toggle the setting so the links can be shown in full instead of being shortened with asterisks.

### Actual behavior:

In 1.17.4 all links in element window are shown in full and are not shortened with asterisks.
In 1.18.4 certain parts of all links in element window are shortened with asterisks.

### Your environment

* uBlock Origin version: 1.17.4 and 1.18.4 (tested on both versions)
* Browser Name and version: Firefox 65 (not browser specific)
* Operating System and version: Windows 10 (not OS specific)

**Comment by gorhill** [comment]
> Highlighting the link and dragging it into a new tab to open it will result in the tab displaying a message "Bad URL timestamp".

Of course, these are filters, not URL.

**Comment by john7200** [comment]
I'm not a native English speaker so I might chose the poor words. What I wanted to ask was if it is possible to reveal the full link in 1.18.4's element window similar to what's shown in 1.17.4's one, not shortened with asterisks. I could not find any option to disable those asterisks or shortened links. I always use element window to inspect elements such as links before deciding if I want to block it or not. I actually went back to 1.17.4 because of it.

**Comment by gwarser** [comment]
```html
<img alt="Image may contain: 1 person" class="FFVAD" decoding="auto" style="object-fit: cover;" sizes="598px" 
srcset="https://instagram.fwaw7-1.fna.fbcdn.net/vp/437ca168682a4280197e0fd013a16eba/5D0252EA/t51.2885-15/sh0.08/e35/s640x640/50015889_244421189779268_1315324217494103167_n.jpg?_nc_ht=instagram.fwaw7-1.fna.fbcdn.net 640w,
https://instagram.fwaw7-1.fna.fbcdn.net/vp/a4a983513e58d31ca24316ce892b1bbc/5D1E78EA/t51.2885-15/sh0.08/e35/s750x750/50015889_244421189779268_1315324217494103167_n.jpg?_nc_ht=instagram.fwaw7-1.fna.fbcdn.net 750w,
https://instagram.fwaw7-1.fna.fbcdn.net/vp/9baa5844bb63a324f3d0882fd66465fe/5D23F50F/t51.2885-15/e35/50015889_244421189779268_1315324217494103167_n.jpg?_nc_ht=instagram.fwaw7-1.fna.fbcdn.net 1080w" 
src="https://instagram.fwaw7-1.fna.fbcdn.net/vp/9baa5844bb63a324f3d0882fd66465fe/5D23F50F/t51.2885-15/e35/50015889_244421189779268_1315324217494103167_n.jpg?_nc_ht=instagram.fwaw7-1.fna.fbcdn.net">
```

This particular image element can download image from four sources. UBO tries to be smart and create one filter for all of them, because that is expected. If you want to preview sources, use browser inspector tool.

**Comment by gorhill** [comment]
> reveal the full link

The first filter is always the full link.

**Comment by gorhill** [comment]
>  always use element window to inspect elements such as links before deciding if I want to block it or not. 

The element picker highlights what will be filtered out.
