### ISSUE TITLE
In Chromium, Ublock is no longer able to filter some advertisements by Google and Yahoo.

### ISSUE THREAD

**Issue by peterwilli** [uBlockOrigin/uBlock-issues#437]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Well-known ad-vendors seem to have gotten around ad-blockers.

### A specific URL where the issue occurs

- https://minecraft.gamepedia.com/Minecart_with_Spawner
- https://www.webmd.com/mental-health/addiction/news/20160919/what-is-kratom-dea-ban#1
- https://www.popsci.com/technology/article/2009-12/pirate-exchange-lets-investors-bet-hitting-ransom-jackpot

### Steps to Reproduce

1. Go to one of the URLs
2. See ads.

### Expected behavior:

No ads

### Actual behavior:

Ads are shown everywhere

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Chromium 72 
* Operating System and version: Linux (NixOS)

**Comment by uBlock-user** [comment]
> Go to one of the URLs

Instart Logic. Install https://github.com/gorhill/uBO-Extra

**Comment by peterwilli** [comment]
@uBlock-user thanks for the reply. I'm sorry if I posted an invalid issue. I tried to Google it before posting but I couldn't find any result.
