### ISSUE TITLE
|blob: conversion code to CSP rules is not obsolete

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#438]
This is a comment on https://github.com/gorhill/uBlock/commit/d63592b11ee4d0ac61eb644bea0642b1983a0b28

There still are a few `|blob:` filters in EasyList that are convertable into CSP rules.

I still have this code in my fork and verified it on `merriam-webster.com`.

Whether or not you still want this code is a separate question.

**Comment by gorhill** [comment]
You fail to explain its "not obsolete". That a flter is in EasyList is irrelevant here, I don't maintain EasyList.

**Comment by joey04** [comment]
Your commit message reads: "These filters are to be considered obsolete since they can't be matched against network requests in the webRequest API. They were probably meant to work when ABP was pre-webext, which means they are quite probably obsolete and there is no longer a point for uBO to conveniently translate them into CSP directives."

I filed this issue to confirm your assumption that these rules are obsolete. The commit message doesn't really justify removing it. (I'm not insisting that they should still be supported, but it would be better to give solid reasons for making this change.)

**Comment by gorhill** [comment]
You opened an issue asking me to repeat what I said?

**Comment by joey04** [comment]
What you said was not a solid justification. These EasyList rules can still be converted. Why stop doing that now?

**Comment by okiehsch** [comment]
> I filed this issue to confirm your assumption that these rules are obsolete. The commit message doesn't really justify removing it.

Read https://github.com/uBlockOrigin/uAssets/issues/2073
Converting the `EasyList` blob-filters only leads to site breakage which we have to fix in `uBO-unbreak`.
The filters are pointless, keep in mind that they were added to `EasyList` fixing "some" issue using Adblock/Plus.

**Comment by gorhill** [comment]
Respect and fill the template, and especially provide steps to reproduce _with_ a URL where there is an issue to be seen.
