### ISSUE TITLE
Add basic hostname wildcards to dynamic filtering rules

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uBlock-issues#439]
About half of my dynamic filtering `noop` rules have hostnames that end with the strings `assets|cdn|static` followed by their TLDs.  Most of the time I find a broken page, those are also the strings I look for to unblock the right domain with the extension popup.  I believe that's the case with all users who block third-party scripts and/or frames by default.

Back in 2014, when uBlock Origin was created by @gorhill, these weren't so common, but now all kinds of websites use secondary "CDN" domains with such patterns, and require them to work properly. 

`noop`'ing them has become a tedious time-taking process that could be simplified if it was possible to add basic wildcards to rules.  This would allow one could keep blocking the majority of third-party scripts and frames by default, but also write filters with simple wildcards like this (or any other more appropriate syntax): 

    * *cdn.com * noop

These wildcards, like all dynamic rules, would still have to be entered manually by the user, who's always responsible for his/her own rules and blocking options. 

Using static filters isn't an option because we still want all regular filters to apply to these domains, and not to whitelist them altogether. The point is to reduce user fatigue and make the use of dynamic filters and the "medium mode" more convenient and attractive.

**Comment by gorhill** [comment]
Declining, this would requiring rewriting completely the dynamic filtering engine from scratch into something else with more overhead.

**Comment by gorhill** [comment]
> The point is to reduce user fatigue and make the use of dynamic filters and the "medium mode" more convenient and attractive.

The primary UI is point-and-click, so I don't think that is a valid argument.

**Comment by anewuser** [comment]
>The primary UI is point-and-click, so I don't think that is a valid argument.

What I meant is that not having to play with the popup so frequently would be more convenient, and more users would be willing to use that setup.
