### ISSUE TITLE
Support `same-origin` filter option

### ISSUE THREAD

**Issue by neilvandyke** [uBlockOrigin/uBlock-issues#44]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the filter language,  the "third-party" qualifier/condition has long seemed to consider subdomains to be same-party.

For example, if you have a blocking filter for "*$third-party" in effect, and visit a URL of origin "www.example.com", then "example.foo" will be blocked, but "sneaky.example.com" will *not* be blocked.

I'd like to propose that either the "third-party" qualifier be changed to mean non-same-origin, *or* that a qualifier called "non-same-origin" be added.  The reason is that non-same-origin is important and much more useful than "third-party" in contemporary third-party Web snooping practices.  Today, we have little reason to believe that a shared parent organizational domain says much about whether a non-same-origin domain should be considered same-party.

(Thank you for considering this.  I am a big fan of uBlock Origin specifically.)

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues

### Steps to Reproduce

1. Configure uBlock0 to use only the filter "*$third-party" (by having that the only user filter, and disabling all other filters).
2. Load a Web page such as "https://github.com/uBlockOrigin/uBlock-issues/issues" while having the uBlock0 Logger open for it.
3. See which requests were blocked by "*$third-party" and not.

### Expected behavior:

What I'd *like* to happen is for subdomain URLs from, e.g., domain "live.github.com" to be blocked.

### Actual behavior:

"live.github.com" is *not* blocked.

### Your environment

* uBlock Origin version: 1.16.4
* Browser Name and version: Firefox ESR 52.8.0
* Operating System and version: Debian GNU/Linux 9.4

**Comment by uBlock-user** [comment]
> "live.github.com" is not blocked.

That's NOT a third-party domain, bur rather a sub-domain of the root domain.

**Comment by gorhill** [comment]
> What I'd like to happen is for subdomain URLs from, e.g., domain "live.github.com" to be blocked.

Declined. You are asking to change the semantic of widely used filter syntax.

**Comment by gorhill** [comment]
I shouldn't have said "declined", it's not even close to a good idea, it's asking to break uBO for everybody else.

**Comment by neilvandyke** [comment]
Excellent point.  I shouldn't have suggested changing the meaning of "third-party".

Could you please consider this a feature request, for a qualifier meaning "non-same-origin"?

"non-same-origin" is what I, as a filter developer, usually want when I use the "third-party" qualifier.  I suspect that this is the case for other filter developers.

**Comment by gorhill** [comment]
It's unlikely I will

**Comment by neilvandyke** [comment]
What I think is an important use case is a rule, "*$non-same-origin".  Which would then be combined with whitelisting of permissible non-same-origin URL patterns for given domains.

This is a different approach than URL blacklisting.  Whitelisting has its own pros and cons, and it's a reasonable use of uBlock0, and I think it's consistent with the apparent goals of uBlock0.)

Thank you for considering this.

**Comment by gwarser** [comment]
One moment, does not `*$domain=github.com` with `no-strict-blocking: * true` works like you want?

**Comment by neilvandyke** [comment]
> One moment, does not *$domain=github.com with no-strict-blocking: * true works like you want?

Partially, but not fully.  I believe that a whitelist-oriented approach, a Filter of "*" with a user Rule of "no-strict-blocking: * true" would have at least two drawbacks (relative to a Filter of "*$non-same-origin"):

1. Strict filtering would be lost.  Strict filtering is useful both for blocking known malware sites, and for possibly defeating possible current or future adversarial snooping tricks (e.g., various ways to use JS and new windows to visit a tracking site as first-party).

2. IIUC, an whitelist-oriented Filter list used by many users would require each user to separately add and retain the "no-strict-blocking: * true" Rule, or that important assumption of the whitelist Filter list would be defeated.

**Comment by joey04** [comment]
Just saw this thread and it's interesting that same origin differs in some details from the [eTLD](https://en.wikipedia.org/wiki/Public_Suffix_List) that determines $third-party in uBO.

I had never thought about this before, but I would've assumed they were the same. After all, Mozilla is the keeper of the eTLD list for the purposes of security and proper cookie scoping.

Anybody know why that is?

**Comment by neilvandyke** [comment]
I wonder the same thing, @joey04.  I'll just speculate, for a moment...  In the early days of the Web, we were very cavalier and trusting, and there was a lot of domain-name-based ad hoc "security" by universities and such, sites were often `.edu` altruistic, and most of `.com` wasn't yet concerned with monetizing.  Early proxy-based blocking of ads started during that period, before we were concerned about tracking or adversaries.  Since uBlock Origin inherits rule formats from Adblock, and I suspect (don't recall) that Adblock was at least influenced by rule sets from Junkbuster and Privoxy... the current `$third-party` thinking might date back to that earlier era, even though we were in an adversarial era by the time Adblock started.

One practical thing I can tell you, from a current `*$third-party` whitelisting exercise (~8,600 positive&negative rules, so far), is that I see a lot of trackers sneaking in that wouldn't with `*$same-origin`.  Perhaps hundreds of the negative rules are for trackers hiding as subdomains of the first-party domain (or of its parent domain of the `www.`), I'm always finding more, and more can be added at any time (and let through by `*$third-party`).

**Comment by joey04** [comment]
Interesting thoughts, Neil. I'd never heard of Junkbuster or Privoxy before. Adblocking for me began 14 years ago with the original Adblock, my very first extension after trying Firefox. It was a memorable moment indeed. All of my blocking has been via extensions since.

But my question was really just why eTLD and same origin policy aren't fully in sync within the browser itself, regardless of blocker extensions. I find that odd.

**Comment by gwarser** [comment]
Interesting. 

[Writing Adblock Plus filters documentation](https://adblockplus.org/en/filters)
>Restriction to third-party/first-party requests: If the third-party option is specified, the filter is only applied to requests from a different origin than the currently viewed page. Similarly, ~third-party restricts the filter to requests from the same origin as the currently viewed page.

[The Web Origin Concept rfc](https://tools.ietf.org/html/rfc6454#section-3.2)
>Q: Why use the fully qualified host name instead of just the "top-
   level" domain?

>A: Although the DNS has hierarchical delegation, the trust
   relationships between host names vary by deployment.  For example, at
   many educational institutions, students can host content at
   https://example.edu/~student/, but that does not mean a document
   authored by a student should be part of the same origin (i.e.,
   inhabit the same protection domain) as a web application for managing
   grades hosted at https://grades.example.edu/.

**Comment by joey04** [comment]
Didn't see @gwarser's post while editing my own above, with the same RFC link. (We ended up quoting different parts of the same section.)

From his ABP quote, it's funny they mention "origin" as the determining factor of party-ness. But they must be using eTLD for it, which as we now know isn't exactly the same in all cases.

(It's interesting, but I don't consider it a problem. For me, uBO works great as-is.)

**Comment by h1z1** [comment]
Never noticed this thread before, never considered third party WOULDN'T apply to subdomains.  It certainly explains some workarounds I've had to add.  A request that crosses server boundries IS untrusted unless proven otherwise.  It's the entire point of why you don't want development applications under the same domain as production.   foo.dev.bar.com could read cookies for bar.com.

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by Aybee** [comment]
I like to push this issue.

I also need this possibility that if I set `example.com` globally to `NOOP`, then **only** `example.com` is affected, but not
- adds.example.com
- span.example.com
- xxx..example.com

It could look like this or something different and would be backwards compatible (note the caret "^").
```
* * 3p block
* ^example.com * noop
```
Then it would be useful to make a setting when a domain is set to `block|noop|allow`, that the subdomain should or should not be included automatically. If the default value is "Include Subdomains" (without caret), it would also be backwards compatible.

Also `example.com` always should include `www.example.com` and vice versa. AFAIK it's not possible to serve different content on both domains.

**Comment by gwarser** [comment]
@joey04 

> From his ABP quote, it's funny they mention "origin" as the determining factor of party-ness. But they must be using eTLD for it, which as we now know isn't exactly the same in all cases.

WHATWG calls this a "site" https://html.spec.whatwg.org/#sites

**Comment by gwarser** [comment]
>Is there any way to make a rule like this: ?.example.com $1.example.com * noop?

>Specifically, the problem I'm trying to solve is that each google subdomain (i.e. drive.google.com, contacts.google.com, productforums.google.com, etc, requires itself to be unblocked to work). I don't want to say "google.com google.com * noop" because this would encompass everything, including stuff I don't want. And there's far too many possibilities to want to sit down and make a list. Of course, they can just be fixed individually as I go, but that's an inefficient way of doing it. I doubt google is the only site this would apply to, though it's likely the worst. Or am I going about it the wrong way, and should I just noop all google and rely on the static filters at that point?

https://www.reddit.com/r/uBlockOrigin/comments/8tgjfl/dynamic_rules_wildcards_with_references/

**Comment by gorhill** [comment]
The issue here is for a static filter option, for dynamic filtering this is <https://github.com/uBlockOrigin/uBlock-issues/issues/957>.

**Comment by gwarser** [comment]
Fixed by https://github.com/gorhill/uBlock/commit/bde3164eb445a4e74acca303ec9fa07f82ba1b1c, https://github.com/gorhill/uBlock/commit/60d5b85e41c03133c01779304cb5fe90c294bc40, https://github.com/gorhill/uBlock/commit/80413dff830cd9e29accc5c5ee29a70a8046cf9c
