### ISSUE TITLE
Technique Bypasses User or List Blocks on Ads and Trackers Using a Proxy

### ISSUE THREAD

**Issue by ilikenwf** [uBlockOrigin/uBlock-issues#441]
This person has found a way to inject google tags and basically anything else using a proxy. While his method on this demo page is obvious, others could in the future be less so.

https://analytics-bypassing-adblockers.netlify.com

How possible would js heuristic comparison be? Yes, we can look at URL's and see if they contain a blocked domain, but I'm sure that would quickly be worked around somehow...

This is all an arms race but this method seems especially nasty to me...all that said, considering future Firefox updates, and that one can block tracking domains at their router, I suppose that what this person doesn't consider is that the tags will only apply on his site, and not be able to cross talk with Google and actually gain much insight on the person browsing, unless everyone starts proxying their ad and tracker requests.

**Comment by ilikenwf** [comment]
And yes, I realize uMatrix negates most of this, but for common average users it is a threat.

**Comment by gorhill** [comment]
Consider this a filter issue. All sites can already just "change URL name" of resources, so it's no different in current case.

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.
