### ISSUE TITLE
golem.de.js crashes angular app

### ISSUE THREAD

**Issue by 4P-Reinhard** [uBlockOrigin/uBlock-issues#444]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock does break the angular app, because of this injected script:
\# https://github.com/uBlockOrigin/uAssets/issues/88
golem.de.js application/javascript
(function() {
	var rael = window.addEventListener;
	window.addEventListener = function(a, b, c) {
		rael(a, b, c);
		if ( /^\s*function\s*\(\)\s*{\s*window\.clearTimeout\(r\)\s*\}\s*$/.test(b.toString()) ) {
			b();
		}
	}.bind(window);
})();

### A specific URL where the issue occurs

https://app.netplay-config.4players.de/

### Steps to Reproduce

1. Load URL with uBlock enabled

### Expected behavior:

Only ads & tracking are blocked

### Actual behavior:

Angular app crashes because of injected javascript producing an error in the overwritten function addEventListener :

TypeError: b is null dashboard:29:3
    addEventListener (index):29
    <anonym> (index):978
     supportsPassiveEventListeners Angular
    Bootstrap Webpack

### Your environment

* uBlock Origin version: uBlock Origin v1.18.4
* Browser Name and version: Firefox 65.0.1 (64-Bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
same as https://github.com/uBlockOrigin/uBlock-issues/issues/368

**Comment by gwarser** [comment]
Scriptlet ID/name was removed?

    golem.de.js application/javascript

**Comment by gorhill** [comment]
Oops, thanks for catching that.
