### ISSUE TITLE
svg.disabled = 'true' (default in Tor Browser) hides the the UI icons

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#446]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`svg.disabled` is set to `true` in Tor Browser for increased security ([more info](https://bugzilla.mozilla.org/show_bug.cgi?id=1216893)). This causes the UI icons in the latest versions of uBO to disappear.

### A specific URL where the issue occurs

Everywhere.

### Steps to Reproduce

1. Download Tor Browser
2. Run it
3. Install uBO
4. Click the icon of the extension in the toolbar

### Expected behavior:

UI icons should show (as in previous versions).

### Actual behavior:

Icons don't show.

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: 8.0.6 (based on Mozilla Firefox 60.5.1esr) (64-bit)
* Operating System and version: openSUSE Leap 15.0

**Comment by emanruse** [comment]
The same happens in uMatrix too. Please let me know if you want me to duplicate this same issue in its tracker.

**Comment by gorhill** [comment]
What can be done?

**Comment by uBlock-user** [comment]
because ubo and umatrix makes use of svg icons and you're disabling svg ?

**Comment by uBlock-user** [comment]
> What can be done?

load png icons or of  some other different type when svg is not available if you really to facilitate this issue

**Comment by gorhill** [comment]
Sure. I was really asking what can be _trivially_ done. Maybe the spirit of `svg.disabled` is to really disable remote SVG images, not local ones as used in extensions.

**Comment by uBlock-user** [comment]
It breaks youtube/github and elementpicker' s selector functionality(https://github.com/pyllyukko/user.js/issues/305) looks like trivial solution won't address every breakage.

**Comment by emanruse** [comment]
> because ubo and umatrix makes use of svg icons and you're disabling svg ?

The guys from the Tor project seem to do it for some additional security. Check the "more info" link.

> What can be done?

I don't know. Options which I can think of:

* Perhaps the simplest thing would be: do as in previous versions :)
* Or if SVG is so important to use - perhaps have some kind of fallback to non-SVG (if that is possible)
* Or an option in "I am an advanced user" to use PNG (or some text symbols) instead
* Ideally an intelligent solution would be to have separate settings for blocking remote and local SVG images. However that would mean discussing upstream with Mozilla which may be very time consuming and with unknown outcome.

**Comment by gorhill** [comment]
> do as in previous versions

Previous versions was also SVG -- indirectly through fonts. If this was working before than this does give arguments that `svg.disabled` is meant for remote images.

**Comment by emanruse** [comment]
It's been quite a few months.
Any hope to have this fixed in the next release please? It is really difficult to use the extensions without UI icons.

**Comment by gorhill** [comment]
I don't have a solution for this. The real solution in my opinion is for Firefox to ensure the setting does not affect extensions, the same way it does not affect its own icons in the browser UI.

**Comment by gorhill** [comment]
I consider this a browser issue, to be reported to Firefox issue tracker. Extensions extend a browser abilities, they should not be subjected to restrictions which are meant to be imposed on web pages.

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1564208

**Comment by emanruse** [comment]
Thanks for the feedback.
Yes, I reported it upstream to TBB and they have upstreamed it to Firefox.
