### ISSUE TITLE
[Legacy] The button does not retain its position when it's placed before a 'spring', 'spacer' or 'separator'

### ISSUE THREAD

**Issue by JustOff** [uBlockOrigin/uBlock-issues#447]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The button does not retain its position when it's placed before a 'spring', 'spacer' or 'separator'.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Add 'spring', 'spacer' or 'separator' to the browser toolbar
2. Place the uBlock button right in front of one of these special elements
3. Restart the browser or open a new window

### Expected behavior:

The button should retain its position

### Actual behavior:

The button jumps to the right of the special element

### Your environment

* uBlock Origin version: firefox-legacy-1.16.4.8
* Browser Name and version: Pale Moon 28.4.0
* Operating System and version: Windows 7

**Comment by JustOff** [comment]
Here is the fix I propose to apply to resolve this issue: https://github.com/JustOff/uBlock/commit/c9b38b70694cc70b1b08876ae9e4624563d3afba.

**Comment by gorhill** [comment]
Thanks.

I removed the restriction in uBlock repo, you can submit a pull request.

**Comment by JustOff** [comment]
Thanks you  for ongoing support of the XUL-based applications, and especially Pale Moon.
