### ISSUE TITLE
parsing #@# not works

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uBlock-issues#448]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [] using a new, unmodified browser profile
- [] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

#@# does not work

### A specific URL where the issue occurs

youtube.com

### Steps to Reproduce

1. add rule youtube.com#@##masthead-ad
2. go to the website
3. premium banner is not visible

### Actual behavior:

add rule youtube.com#@?##masthead-ad
go to the website
premium banner visible

### Your environment

* uBlock Origin version: 1.18.5rc1
* Browser Name and version: Opera|Beta
* Operating System and version: Windows 7x64

**Comment by uBlock-user** [comment]
broken by https://github.com/gorhill/uBlock/commit/388c1c98eca1c14f45a3b3bcfe322460fac15997

**Comment by gorhill** [comment]
Thought I tested well but could be, I will look ASAP.

**Comment by gorhill** [comment]
Yes, regression confirmed. I had tested all flavor of `#@...#` **except** for `#@#`...
