### ISSUE TITLE
Rebrand uBlock Origin 

### ISSUE THREAD

**Issue by dannycolin** [uBlockOrigin/uBlock-issues#45]
Recently, uBlock (not uBlock Origin) introduced code that tracks their users [[1][1]][[2][2]]. I believe that the similarity between the names of the two projects is confusing and can potentially endanger the safety of users who inadvertently or by lack of knowledge install the wrong version of uBlock.

It also seems to us that this event and all other events of the same nature are detrimental to the image and reputation of uBlock Origin.

Given that, I think it would be better to rebrand uBlock Origin to avoid further confusion and / or problems similar to the one cited above.

Sincerely,

1: https://soylentnews.org/article.pl?sid=18/05/17/028245
2: https://github.com/uBlockAdmin/uBlock/commit/76b89c0a22d20f3a66d7feab14e024f56ca65539
3: https://www.reddit.com/r/firefox/comments/8k4fu7/privacy_tool_ublock_not_ublock_origin_adds_user/

[1]: https://soylentnews.org/article.pl?sid=18/05/17/028245
[2]: https://github.com/uBlockAdmin/uBlock/commit/76b89c0a22d20f3a66d7feab14e024f56ca65539
[3]: https://www.reddit.com/r/firefox/comments/8k4fu7/privacy_tool_ublock_not_ublock_origin_adds_user/

**Comment by uBlock-user** [comment]
Maybe rename repository from `uBlock` to `uBlock Origin`, that's it. I don't see anything else needed to be changed.

**Comment by gorhill** [comment]
Changing name will be detrimental to uBO, it's already widely mentioned everywhere, if I change the name, even more people will go install "uBlock". Just see the other "uBlock" as a scammy version, just like many others found in the Chrome store with "uBlock" in their name.

**Comment by smed79** [comment]
https://github.com/uBlockOrigin/uAssets/commit/82067d1ef33702fd1abd12fd31a0336bac28c41d
