### ISSUE TITLE
[Question] How can i disable by default ?

### ISSUE THREAD

**Issue by AndRoMarian** [uBlockOrigin/uBlock-issues#451]
I want to let me enable on what websites i want to enable.
Not to be enabled by default.
It is possible.
Thanks.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#disabling-filtering-temporarily-or-by-default-blacklist-mode

**Comment by AndRoMarian** [comment]
Already found that> Not helping.

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.

Keep questions on reddit.
