### ISSUE TITLE
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#disabling-filtering-temporarily-or-by-default-blacklist-mode

### ISSUE THREAD

**Issue by AndRoMarian** [uBlockOrigin/uBlock-issues#452]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#disabling-filtering-temporarily-or-by-default-blacklist-mode

_Originally posted by @gwarser in https://github.com/uBlockOrigin/uBlock-issues/issues/451#issuecomment-470510447_

Already found that> Not helping.

And don't close before to respond.

**Comment by gorhill** [comment]
be respectful of what is asked from you. You are opening issue and dismissing the template. The feature you want does not exists and there is no plan to add it -- it's contrary to the primary purpose of uBO.

**Comment by uBlock-user** [comment]
Duplicate of #451
