### ISSUE TITLE
Work at chrome://newtab

### ISSUE THREAD

**Issue by joaoppp** [uBlockOrigin/uBlock-issues#455]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I will like to request if possible that ublock could work at chrome://newtab that is nothing more than a google webpage https://www.google.com/_/chrome/newtab?ie=UTF-8

### A specific URL where the issue occurs
chrome://newtab

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Chromium 72.0.3626.121
* Operating System and version: Linux

**Comment by uBlock-user** [comment]
`chrome://` is not a valid  math pattern according to https://developer.chrome.com/extensions/match_patterns so not possible.

**Comment by krystian3w** [comment]
You need Chrome 60 or older, in newest is blocked this.
