### ISSUE TITLE
uBlock Origin conflicts with Alexa Tool

### ISSUE THREAD

**Issue by xmoer** [uBlockOrigin/uBlock-issues#459]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin conflicts with Alexa Tool extensions.
Causes Alexa's requests to the server have been blocked by an extension.

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock
https://chrome.google.com/webstore/detail/alexa-traffic-rank/cknebhggccemgcnbidipinkifmmegdel

### Steps to Reproduce

1. Installation Alexa Traffic Rank
2. Installation uBlock Origin
3. Failure occurs after clicking the Alexa's icon

### Expected behavior:

Fix conflicts between extensions.

### Actual behavior:

I can't use Alexa extension with uBlock Origin installed.

### Your environment

* uBlock Origin version: 1.18.6
* Browser Name and version: Chrome 73.0.3683.75
* Operating System and version: Windows10 - 1803

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/6e5641bfd02af31d68cd56cf0305256a.png)

Filter from EasyPrivacy, blocking a bts iframe.

**Comment by gorhill** [comment]
It does not fail on my side, the context is `www.alexa.com`, and thus not blocked as a result:

![a](https://user-images.githubusercontent.com/585534/54310371-9d74a380-45a8-11e9-97b3-8d3451295de1.png)

**Comment by gorhill** [comment]
I would like to go to the bottom of why it's (improperly) `behind-the-scene` on your side while it is properly `www.alexa.com` on my side.

**Comment by xmoer** [comment]
I tried to add alexa.com to the whitelist, but it didn't work.

**Comment by gorhill** [comment]
If you want a filter solution, use `@@||alexa.com/minisiteinfo/$third-party,domain=behind-the-scene`.

Meanwhile I will keep this issue open, any help is welcome to find out why Chrome is not properly setting the `initiator` property properly, there has been other instances of this.

**Comment by xmoer** [comment]
Thank you. This problem has happened in recent hours and did not exist before. I'm not sure if the reason for the problem is Chrome 73 or the new version of uBlock Origin.

**Comment by gorhill** [comment]
I was using the latest version of uBO. Chromium devs are refactoring a lot of network stuff lately, I am more inclined to think this is Chrome 73-related, but more feedback is needed before drawing conclusions.

**Comment by gorhill** [comment]
I can reproduce with Chrome 74.0.3729.6.

Disabling "Enable network service" does not help. Using uBO 1.18.4 does not help.

Upon investigation, I can see that the `initiator` property is not set as expected by Chrome in `webRequest.onBeforeRequest` -- hence uBO can't tell from which context the network request is fired, and thus fall back onto the generic contextless `behind-the-scene`.

So this confirm this is a regression in Chrome 73 vs. Chrome 72.

**Comment by xmoer** [comment]
Yes, disabling "Enable network service" does not help. Chrome recent updates have been surprisingly fast.

**Comment by uBlock-user** [comment]
My result is from Chromium 75 so it seems the regression has carried on in Canary.

**Comment by gorhill** [comment]
I am going to add a workaround, which I believe is reasonable anyways regardless of the issue here.

The request being blocked is of type `sub_frame`, and in such case, since there is no parent document, it just makes sense to assume the context is the same as the frame itself. I verified that this solves the issue here.

**Comment by gorhill** [comment]
I will consider this an emergency fix and publish 1.18.8 immediately.

**Comment by gorhill** [comment]
Note that once the frame request is allowed, the following `image` requests have their `initiator` properly set.
