### ISSUE TITLE
uBlock not auto-closing blocked pop up ads tab window in firefox android

### ISSUE THREAD

**Issue by fightthepower** [uBlockOrigin/uBlock-issues#460]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I have been using uBlock in my firefox in android for may months and this problem started recently. Certain websites open multiple (more than 7) pop up new tab ad windows which uBlock used to close automatically. But recently uBlock is not auto closing these blocked pop ad windows and ask for conformation. This is what I am seeing 
`uBlock Origin has prevented the following page from loading https://websilte.com/ads/ads Because of the following filter /popad found in Easy list "Close this window"`

Now every time I have to manually click  "Close this window" to close this tab. The problem is in certain webpages when we click on it muliple popup ads opens as we click on the pages. I want uBlock to auto close these windows without asking for my permission every time.

### A specific URL where the issue occurs

http://vev.io

### Steps to Reproduce

1. Open any videos in http://vev.io
2. Start playing the videos
3. Try to close the message in the top right corner of the video player

### Expected behavior:

Should auto- close blocked pop up ad  windows

### Actual behavior:

Prompting users  to close the blocked pop up ads windown

### Your environment

Android
Firefox latest
uBlock latest

**Comment by uBlock-user** [comment]
> Open any videos in http://vev.io

Where are the videos ?

**Comment by gorhill** [comment]
No feedback from OP, most certainly a case of confusing strict-blocking with `popup` filter option, hence a filter issue, not to be handled here.
