### ISSUE TITLE
1.18.6 weird update

### ISSUE THREAD

**Issue by ISSUES999** [uBlockOrigin/uBlock-issues#462]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by ISSUES999** [comment]
after the new update 1.18.6 i noticed several issues
-element picker box down right missing 
-placeholders all over the place
-at least one video server still trying to load
-when unchecking the three boxes in settings the private browsing cannot load any page , the allow in private mode is selected
-the +all list at the left of the power button cannot show anything extra
-the filter lists update once then aftre u leave the page they dissappear and the checked boxes become unchecked
-all letters in boxes or next to them are missing
-ublock window is big (original design?)
-explanations in starting window removed?
-even though disgus in site is allowed all comments are looking like the page didnt load well
-the whole page looks weird regarding remote fonds?
-might have the issue with csp and webrtc boxes appear unchecked when starting ublock but if u go to another page and return the boxes are checked , it happens from time to time in 1.17.0
-i was using 1.17.0 aand besides the csp/webrtc problem one placeholder was always there that belonged to madads
-win vista 32 bit
-opera 36
-1.18.6

**Comment by mapx-** [comment]
- opera 36 is too old, the last version of uBo requests at least opera 40.
- if you cannot install other opera version you should use an old uBo version, see here:
https://www.reddit.com/r/uBlockOrigin/comments/b104vc/opera_stops_loading_pages_with_ubo_switched_on/eiimyee/

**Comment by uBlock-user** [comment]
> opera 36

Not supported, so not an issue. Minimum version bumped to 40 for Opera for some time.
