### ISSUE TITLE
v1.18.8 breaks Chrome Browser

### ISSUE THREAD

**Issue by shaft17** [uBlockOrigin/uBlock-issues#463]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

With uBlock enabled since update to 1.18.8, no sites won't load, even the extension page of uBlock doesn't appear. Chrome v52, can't update it for reasons.
I reverted to 1.18.4 and this works with no issues.

### Expected behavior:

A working uBlock as before the update to 1.18.8

### Your environment

* uBlock Origin version: 1.18.8
* Browser Name and version: Chrome 52
* Operating System and version: Win 7 64bit

**Comment by uBlock-user** [comment]
sounds like https://github.com/uBlockOrigin/uBlock-issues/issues/461 ?
