### ISSUE TITLE
Better support Yandex browser (especially on Android)

### ISSUE THREAD

**Issue by colbycdev** [uBlockOrigin/uBlock-issues#466]
Recently, I installed Yandex browser on my phone because it's the only Android chromium browser with extension support (that I know of)

However, uBlock origin is "incompatible with Yandex", according to the chrome webstore.

Although Firefox is competent on Android, I find that browsers using chromium/blink engine tend to load and display pages way faster

As any Russian users especially (Yandex=Google Russia, pretty much), and Yandex users in general, would surely appreciate being able to use uBlock, I ask that you look into compatibility with this browser

I would like to note that at alpha version 19 (I think) of Yandex it works fine. Other version don't

_Sent from my moto g(6) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by uBlock-user** [comment]
Yandex always had issues from the beggining --  

https://github.com/gorhill/uBlock/issues/2071
https://github.com/NanoAdblocker/NanoCore/issues/169
