### ISSUE TITLE
Keep element picker active after filter is created

### ISSUE THREAD

**Issue by ltsalvatore** [uBlockOrigin/uBlock-issues#467]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Hi Guys, 
hope thats the correct way of posting an issue / request!?

i was just wondering if it would be possible to extend ublock with the ablility of using/assigning shortcuts. 

sometimes (more frequently) I have to remove more than one objects on a website with the element picker / pipette. 

it would come handy if either you have the option to re-enable the element picker with a shortcut, or keep the element picker active untily you decide to turn it off. 

### A specific URL where the issue occurs
ie.: flashscore.com

### Steps to Reproduce
1. turn on element picker
2. select and create an entry for this element to block/remove

### Expected behavior:
element picker remains activated of after selection was done or shortcut is implemented to easily turn this feature on

### Actual behavior: 
element picker turns of after selection was done

### Your environment
* uBlock Origin version: 1.18.8
* Browser Name and version: Google Chrome 72.0.3626.121
* Operating System and version: Windows 10 Enterprise

**Comment by gwarser** [comment]
>or shortcut is implemented to easily turn this feature on

Kebab Menu -> More tools -> Extensions -> Hamburger menu in top left -> Keyboard shortcuts

**Comment by ltsalvatore** [comment]
> > or shortcut is implemented to easily turn this feature on
> 
> Kebab Menu -> More tools -> Extensions -> Hamburger menu in top left -> Keyboard shortcuts

honestly i cant follow?
dont undertand what you are meaning with this

**Comment by uBlock-user** [comment]
He means you can set shortcuts for element zapper via `chrome://extensions/shortcuts`

**Comment by ltsalvatore** [comment]
damn, you saved my day... :-D

thank you a lot.. 

but why is he talking about kebab and hamburgers.. 
now im getting hungry :-P

**Comment by uBlock-user** [comment]
Does that work for you ? You can set shortucts for entering element picker mode so once it closes after creating the filter, you can do something like CTRL + B and element picker will appear again.

**Comment by ltsalvatore** [comment]
yes.. it worked perfectly. 

i set ALT+E, and whenever i press that key combination the requested element picker starts. 

thats exactly what i wanted. 
thank you again

**Comment by gwarser** [comment]
@ltsalvatore 

![mystery meat of mobile navigation](https://user-images.githubusercontent.com/886325/54496772-6a594980-48f3-11e9-871d-e87ce97a7bb8.png)
