### ISSUE TITLE
Dashboard tabs are unresponsive after a while

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#468]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Steps to Reproduce

1. Open `Dashboard->Filter lists`
2. Leave it in the background for some time (about 10-15 minutes) and actively browse the web in the same window
3. Switch to `Dashboard` and try to go from `Filter lists` to `Settings`.

### Actual behavior:
The URL changes correctly from `chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#3p-filters.html` to `chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#settings.html`, but `Filter lists` tab is still being displayed, visually nothing changes. Checkboxes within `Dashboard->Filter lists` itself are working. Pressing F5 displays last clicked Dashboard tab.

### Your environment

* uBlock Origin version: v1.18.9rc1
* Browser Name and version: Chromium 73.0.3683.75 (64-bit)
* Operating System and version: Windows 10 v1607 x64

**Comment by uBlock-user** [comment]
Did you try this on any other tab ? I think Chrome discards inactive tabs from memory after a while.

Keeping that tab open, check chrome://discards for more information.

**Comment by mikhaelkh** [comment]
@uBlock-user, yes, that seems to be the case. When I "Freeze" Dashboard in `chrome://flags/`, I get the mentioned behavior.

**Comment by uBlock-user** [comment]
Reset all flags to narrow down the cause. This has happened to me before on tabs that I keep them open for a longer periods of time in background.

**Comment by uBlock-user** [comment]
Tried to reproduce by waiting for 20ish minutes and I can browse to settings from filterlists tab just fine.

**Comment by mikhaelkh** [comment]
There's a simpler way to reproduce, just click `Freeze` in `chrome://discards`. One of the flags causes Dashboard to freeze the after a while and breaks it.

**Comment by uBlock-user** [comment]
> just click Freeze in chrome://discards. One of the flags causes Dashboard to freeze the after a while and breaks it.

Browser behavior or bug in Chromium itself.

**Comment by gorhill** [comment]
> just click `Freeze`

I can not find any developer information regarding this "freeze" feature -- so assuming it's not a feature to be minded by extension developers.

**Comment by mikhaelkh** [comment]
Here's a [Blog Post](https://blog.chromium.org/2018/06/chrome-68-beta-add-to-home-screen.html) (Page Lifecycle)

**Comment by mikhaelkh** [comment]
Here's a [Blog Post](https://blog.chromium.org/2018/06/chrome-68-beta-add-to-home-screen.html)

**Comment by gorhill** [comment]
I need to read this: <https://github.com/WICG/page-lifecycle>.

**Comment by gorhill** [comment]
Symptom is the same was the one observed in <https://github.com/gorhill/uBlock/issues/3665>.

**Comment by uBlock-user** [comment]
> the document.wasDiscarded property is now available so developers can restore view state (saved in the freeze event) when the user refocuses the tab and the page is reloaded. 

That can used to unfreeze the freeze state..

**Comment by jspenguin2017** [comment]
Why not just remove this: https://github.com/gorhill/uBlock/blob/master/src/js/udom.js#L677

Does that cleanup code actually do anything useful?

**Comment by gorhill** [comment]
I remember you asking the same thing and me agreeing to remove this... Do you remember where this was? I can't remember if I tried to remove it and something regressed.

**Comment by jspenguin2017** [comment]
I have it removed for 3 months now, I see no issue: https://github.com/NanoAdblocker/NanoCore2/blob/master/patches/20_6_warn_unsaved.patch

Your fix is not complete, although switching tabs are working now, the tabs themselves are not working.
