### ISSUE TITLE
No Scripting - not storing filter/rule

### ISSUE THREAD

**Issue by Chaython** [uBlockOrigin/uBlock-issues#470]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When no-scripting is enabled, allowing scripts on an individual page is not stored for next visit...

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.18.8
* Browser Name and version: Chrome Version 74.0.3729.6 (Official Build) dev (64-bit)
* Operating System and version: Windows 10 Enterprise 1809 17763.316

**Comment by gwarser** [comment]
> New in 1.17.0:
> 
> Changes to the state of per-site switches will be deemed temporary if and only if the [overview panel](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel) is visible.
> 
> When the overview panel is not visible, toggling a per-site switch will cause the change to be permanent (i.e. same behavior as before).
> 
> However, when the overview panel is visible, toggling a per-site switch will cause the change to be temporary. In such case, there will be an eraser and a padlock icon in the overview pane, which can be used to revert or persist the current state of all the per-site switches.
