### ISSUE TITLE
The ability to stop certain websites from continuously loading content

### ISSUE THREAD

**Issue by Zig-03** [uBlockOrigin/uBlock-issues#471]
Some websites just keep exchanging data with their servers in the background while I read stuff or scroll through their website, others just load a bunch of unnecessary stuff while I browse their website, so it'd be great to have the ability of:
- making a website stop loading any more content when a button was clicked
- making a website stop loading any more content after a certain amount of seconds (from the moment I open the link)
- _'same as the second point'_ but as a general rule that would apply to all websites by default

Thank you very much.

**Comment by uBlock-user** [comment]
> Some websites just keep exchanging data with their servers in the background while I read stuff or scroll through their website,

That can be blocked by blocking the XHRs which are used for continuous communication to the server. Check the logger and make the rule.

**Comment by gorhill** [comment]
Closing as invalid, not actual **cases** was provided to allow for at least evaluating such requests.
