### ISSUE TITLE
integration to pi-hole suggestion 

### ISSUE THREAD

**Issue by mattiasghodsian** [uBlockOrigin/uBlock-issues#474]
I would love to see some kind of integration to [pi-hole](ttps://pi-hole.net/) where ublock finds the ads to block and then send it to the pi-hole machine on the network to block that to all devices connected to the router (DNS).

**Comment by DandelionSprout** [comment]
While I am not affiliated with uBlock Origin (although I am on speaking terms with many of its devs), I would be surprised if they found it to be within the scope of the uBO project.

My best bet would've been to find someone (Presumably a *really* good coder) who could make an independent fork of uBO to incorporate such an extensive feature; and if it becomes a success, the incorporation code could've been merged with uBO upstream.
