### ISSUE TITLE
Include the entry's "!" info note(s) in the blocked-page warning

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#475]
After I thought a bit better through https://github.com/uBlockOrigin/uAssets/pull/5180 today, after I had pretty much entirely cooled down about it, I've thought of a much better solution that could benefit almost all blocked sites from most lists.

At the current point in time, the block message only shows the matching filter, and the list(s) that the filter was found in, as demonstrated in the image below:
![image](https://user-images.githubusercontent.com/22780683/54684526-dbc41280-4b14-11e9-8250-1cb7eb2294bc.png)

This may oftentimes be insufficient information to determine why the site was blocked, both for laymen and for professional-scale enthusiasts alike, and usually requires looking around in the source list's content to try to determine a reason behind it, which it's assumable that a fair percentage of non-professionals may not know that they're expected to do.

I therefore hereby request that the block message also include the `! ` or `# ` info notes for the entry. That way, users of *uBlock Filters - Badware Risks* who try to access `inkscape.fr` would be shown these notes as part of the block message:

```
! https://github.com/uBlockOrigin/uAssets/issues/3060
! https://www.bleepingcomputer.com/news/security/fake-websites-for-keepass-7zip-audacity-others-found-pushing-adware/
! https://www.virustotal.com/#/file/a5616985e92ca7c1df3b132d2da2ef33c64f38ba2dca40445017037473d7d014/detection
```

While a user of *Dandelion Sprouts nordiske filtre* who tries to access `godeskonettbutikk.com` would be shown these notes as part of the block message:

```
! 🇳🇴: Falske nett-"butikker" som er så dårlige, at de står oppført på Forbrukertilsynet egen svarteliste.
! 🇩🇰: Falske web-"butikker" der er så dårlige, at de er opført på svartelisten til Forbrukertilsynet (Norges svar på Forbrugerombudsmanden).
! 🇬🇧: Fake and fraudulent web-"stores" that are so bad, that they're listed on the blacklist of the Norwegian state-sponsored Consumer Authority.
! Source: https://www.forbrukertilsynet.no/netthandel/falske-nettbutikker.
```

As for how to detect which notes to include, my personal idea is to include the notes at the top of the paragraph that the entry is in, *except* if there's another note immediately above the entry. If you have any better detection ideas, you're more than welcome to implement them instead.

If you guys have any questions about this idea of mine, don't hesitate to ask me about them.

### Your environment

* uBlock Origin version: Nano Adblocker 1.0.0.96
* Browser Name and version: Google Chrome 73.0.3683.75 64-bit
* Operating System and version: Windows 10 October 2018 Update (Last installed system update: KB4489899)

**Comment by gwarser** [comment]
Related: https://github.com/gorhill/uBlock/issues/1445

**Comment by gwarser** [comment]
Duplicate(?) https://github.com/gorhill/uBlock/issues/352

**Comment by DandelionSprout** [comment]
I think that given that both of those issue reports are ≥3 years old, I hope they wouldn't be particularly big obstacles for this thread.

Although the following example is not about a blocked-page warning, I had to look into the source file for *uBlock Filters - Unbreak* after Jspenguin [seemed to me to be unsure why a particular whitelist entry was in it](https://github.com/NanoAdblockerLab/NanoContrib/pull/17#discussion_r267152153); thus tangentially showing that even the top-tier biggest pros in the adblocking circus needs easy access to explanations sometimes, let alone regular users.

**Comment by DandelionSprout** [comment]
>Searching for list name is already noticeable, searching back for comments will be slooow.

If that turns out to be a problem, one possibility that I'm thinking of in a hurry could've been to have the warning message display instantly, while the grey boxes become filled with info as they're found and loaded. Sort of like how how many websites and blogs (Especially on phone) load the text first and then the images.

**Comment by Jap2-0** [comment]
> have the warning message display instantly, while the grey boxes (e.g. those for list names and info comments) become filled with info as they're found and loaded.

That's already how it does it for the list name.

**Comment by gorhill** [comment]
I prefer to  decline this, this is far from trivial to add such capability and so far the strict block page is doing the job as is.
