### ISSUE TITLE
Suggestion: Combining multiple included lists into their official combinations

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#476]
In order to reduce the amount of loading requests that list-hosting servers receive, and to marginally slim down the list settings of very cleanliness-minded users, I propose to add a possibility that when an end-user has multiple uBO-included lists turned on for which there exists an official combination list, then they can try to load the combination list instead of the two separate lists.

In particular, FilterLists.com mentions the following existing combinations for EasyList:
![image](https://user-images.githubusercontent.com/22780683/54688168-6872ce80-4b1d-11e9-8e6d-8f47cb8800dc.png)

So whenever someone e.g. has both EasyList and RU AdList turned on, they could be combined into [ABP's official list that combines the two](https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt).

Here's a mockup example setting:
![image](https://user-images.githubusercontent.com/22780683/54687729-8e4ba380-4b1c-11e9-9e29-e9644c7c42d8.png)

Within that mockup example, there would still be the possibility to view the two lists individually; as well as to turn off only one of them, so that if e.g. the EasyPrivacy button was turned off, then the combination entry would be gone and would fall back to turning on the normal EasyList setting. 
![image](https://user-images.githubusercontent.com/22780683/54687846-dcf93d80-4b1c-11e9-9670-6997001fa6d9.png)

Additionally, this results in yet another protection against list sync errors; since if a combination file fails to load, then uBO would try to load the individual lists instead.

I am not sure whether the best option would be to either automatically combine lists, or to show the end-user a prompt in the list settings about whether to do so (and which lists (s)he'd want to combine).

The logger and the block-warning pages would possibly need to be updated to show both the combination and the individual list that an entry can be found in, for the sake of e.g. filter issue reports.

All of this may sound like a lot of ado for little use, but I for one think it'd be a nifty feature with technically decent benefits.

### Your environment

* uBlock Origin version: Nano Adblocker 1.0.0.96
* Browser Name and version: Google Chrome 73.0.3683.75 64-bit
* Operating System and version: Windows 10 October 2018 Update (Last installed system update: KB4489899)

**Comment by gorhill** [comment]
> may sound like a lot of ado for little use

I agree. Declining.
