### ISSUE TITLE
"Cross-Origin Request Blocked" is stil shown in the FF console even after the blocked url is in the "Whitelist". Normal?

### ISSUE THREAD

**Issue by photonxp** [uBlockOrigin/uBlock-issues#478]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### Bug
"Blocked" warnings are still shown when the blocked url is already in the Whitelist. Actually, the url could be ACCESSED even though they were shown "Blocked" in the console msg. (I'm not quite sure if this is the normal behavior.)
- The effect is not limited to specific urls, but probably all urls that can be caught by uBlock. 
- The underlying message layers might be one of the possible culprits. 

I got two types of warnings, when urls are already in the Whitelist, based on the FF console msg:
- Type 1: **Cross-Origin Request Blocked**. (When I put urls belonging to the "Built-in"/"Privacy" list into the Whitelist)
- Type 2: **Loading failed**. (When I put urls belonging to the "My filters" list into the Whitelist)

#### For Type 1:
On Firefox the warning msg is:

> **Cross-Origin Request Blocked**: The Same Origin Policy disallows reading the remote resource at https://api.amplitude.com/. (Reason: CORS request did not succeed).

On Google-Chrome the warning msg is:

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT    https://api.amplitude.com/

#### For Type 2:
On Firefox the warning msg is:

> **Loading failed** for the <script> with source “https://try.alexa.com/wp-includes/js/wp-emoji-release.min.js?ver=5.1.1”.

On Google-Chrome the warning msg is:

> GET https://try.alexa.com/wp-includes/css/dist/block-library/style.min.css?ver=5.1.1 net::ERR_BLOCKED_BY_CLIENT

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
#### For type 1:
https://imgur.com/gallery/EvrRDXb
- When api.amplitude.com is in both the "Built-in" and "Whitelist"
- Err msg is shown for api.amplitude.com in the console

#### For type 2:
www.alexa.com
- When try.alexa.com is in both the "My filters" and "Whitelist"
- Err msg is shown for try.alexa.com in the console

#### For type 1:
1. All Buit-in filters are checked and loaded
2. Add api.amplitude.com to the Whitelist
3. Open console in the FF or Chrome
4. Visit https://imgur.com/gallery/EvrRDXb
5. Check console msg for api.amplitude.com

#### For type 2:
1. Add try.alexa.com to the "My filters" list
2. Add try.alexa.com to the "Whitelist"
3. Open console in the FF or Chrome
4. Visit www.alexa.com
5. Check console msg for try.alexa.com

### Expected behavior:

[What you expected to happen]

#### For type 1:
- In the console, the error msg for api.amplitude.com shouldn't suggest "Request Blocked" or anything similar, because api.amplitude.com is in the Whitelist and could actually be ACCESSEED by the browser.
- The err msg shouldn't appear at all, perhaps.

#### For type 2:
- In the console, the error msg for try.alexa.com shouldn't suggest "Loading failed" or anything similar, because try.alexa.com is in the Whitelist and could actually be ACCESSEED by the browser.
- The err msg shouldn't appear at all, perhaps.

### Actual behavior:

[What actually happened]

#### For type 1:
In the console, the error msg for api.amplitude.com were shown and they suggested "Request Blocked", in both FF and Chrome.

#### For type 2:
In the console, the error msg for try.alexa.com were shown and they suggested "Loading failed", in both FF and Chrome.

### Your environment

* uBlock Origin version: v1.18.6
* Browser Name and version: FF and Google-Chrome, both latest
* Operating System and version: All

**Comment by gorhill** [comment]
> Add api.amplitude.com to the Whitelist

[Documentation](https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist):

> The purpose of a whitelist directive is to tell on which page uBlock Origin ("uBO") should disable itself completely.

_Whitelist_ pane is to tell where uBO should be disabled. You are trying to create an **exception filter**, and filters go into _"My filters"_. Works fine with:

    @@||api.amplitude.com^
