### ISSUE TITLE
uBlock Origin breaks Chrome flag #enable-framebusting-needs-sameorigin-or-usergesture

### ISSUE THREAD

**Issue by vodzl** [uBlockOrigin/uBlock-issues#479]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hello,
This is my first ever GitHub report so i apologize if something is incorrect in my issue.
Since last Chrome 72 release and higher there is no 3rd party redirect blocking anymore when
uBlock Origin or Tampermonkey are enabled and flag #enable-framebusting-needs-sameorigin-or-usergesture is set to enabled (those extensions i found there could be others as well).
I have filled a bug issue using Chrome bug report link and was advised to ask extensions developers for support. I also have sent an email to TM developer. 
https://bugs.chromium.org/p/chromium/issues/detail?id=940820

Url below is a public test. It happens at other sites as well.
If it is a Chrome bug could you help me filling correct ticket since i am not a developer and
do not know how to explain it correct to them.
### A specific URL where the issue occurs

http://ndossougbe.github.io/web-sandbox/interventions/3p-redirect

### Steps to Reproduce

Set #enable-framebusting-needs-sameorigin-or-usergesture to enabled
1. Enable uBlock Origin
2. Go to specified url above
3. See 3rd party redirect
4. Disable uBlock Origin
5. Go to specified url above
6. See blocked redirect message

### Expected behavior:

Block 3rd party redirect message in url bar.

### Actual behavior:

3rd party redirect happens.

### Your environment

* uBlock Origin version: 1.18.8
* Browser Name and version: Google Chrome 73.0.3683.86 x64
* Operating System and version: Windows 10 x64

**Comment by uBlock-user** [comment]
> was advised to ask extensions developers for support.

They never said anything like that. They said "Over to the extensions team perhaps they know something", they are refering to their extensions team, not uBO devs. You misunderstood that part. 

Anyways, I tested with that flag on and it does block the redirect most of the time, but when it fails it's not because of uBO, I ran the logger and uBO is not blokcing anything. sometime those frames are escaping the sandbox itself and executing the unsafe js code, basically Chromium issue itself. uBO is not breaking anything.
