### ISSUE TITLE
There is an admission of intrusive advertising

### ISSUE THREAD

**Issue by cg1cz** [uBlockOrigin/uBlock-issues#48]
### Description

uBlockOrigin partially stopped blocking advertising on this resource.

### A specific URL where the issue occurs

http://kino-hd1080.ru/9266-zhazhda-smerti-2018-smotret-onlayn.html

### Screenshot in which the issue can be seen

http://s01.geekpic.net/di-CEMVWE.jpeg

### Your environment

* uBlock Origin version: 1.16.6
* Browser Name and version: Opera 47.0.2631.55 
* Operating System and version: Windows 7 64-bit build 6.1.7601 OEM License

##### Your filter lists

uBlock filters 5 845
uBlock filters – Badware risks 11
uBlock filters – Privacy ​​​​​96
uBlock filters – Resource abuse​​​​​ 256
uBlock filters – Unbreak​​​​​ 407
EasyList ​​​​​81 952
Adguard Spyware Filters​​​​​ 2 536
EasyPrivacy​​​​​ 14 818
Fanboy’s Enhanced Tracking List​​​​​ 2 344
Malware Domain List​​​​​ 1 116
Malware domains​​​​​ 21 693
Adguard’s Annoyance List​​​​​ 10 115
Fanboy’s Annoyance List​​​​​ 9 711
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​ 68
Fanboy’s Cookiemonster List​​​​​ 8 833
Fanboy’s Social Blocking List​​​​​ 19 201
Peter Lowe’s Ad and tracking server list​​​​​ 2 640
RUS: Adguard Russian Filter​​​​​ 16 529
RUS: RU AdList ​​​​​22 782

**Comment by uBlock-user** [comment]
FilterList issues =>> https://github.com/uBlockOrigin/uAssets/issues

**Comment by mapx-** [comment]
@uBlock-user  could you test
```
||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=kino-hd1080.ru
||kino-hd1080.ru^$csp=style-src 'self'
```

(Your filter does not work for me)

**Comment by mapx-** [comment]
I tested both FF / chrome. My filters still working.

However, your last filter is ok for me too.

**Comment by uBlock-user** [comment]
Your filters are valid, but somehow they're not working on my end.

**Comment by cg1cz** [comment]
**Saitama**, I'm very grateful for your help.

**Comment by uBlock-user** [comment]
You can return the favour by posting filter related issues in uAssets repo with appropriate title next time.
