### ISSUE TITLE
Disabling advanced options produces large visual glitch: Windows; Linux

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [uBlockOrigin/uBlock-issues#480]
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ X] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When I enable advanced features and then disable them I see the following, even after restarting Firefox:

![image](https://user-images.githubusercontent.com/47056543/54794735-e7145c80-4c40-11e9-8fce-ad3d872fca59.png)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

N.A - it's a UI problem.

### Steps to Reproduce

1. Run FF, with UBO installed.
2. Enable advanced settings (UBO iconbar icon -> settings icon -> 'I am an advanced user'.
3. Disable that setting.
4. Click UBO iconbar icon

### Expected behavior:

[What you expected to happen]

The settings window should return to the size it was when advanced settings were disabled.

### Actual behavior:

It doesn't - the window is the same size, only now, when the advanced settings are disabled, much of the window is blank.
[What actually happened]

### Your environment

* uBlock Origin version: v1.18.11b0
* Browser Name and version: Firefox 66.0
* Operating System and version: Windows 8.1; Mint 19 Cinnamon

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel

**Comment by LinuxOnTheDesktop** [comment]
Sorry, but your link shows me a large window filled with options. As you can see from the image that I posted, toggling advanced mode shows a large but _mostly empty_ window.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Comment by gorhill** [comment]
> filled with options

These are not "options", they are the domains for which a network connection was attempted or made on the current web page. If the page does not make any connections, then there is nothing to report and the list will be empty.

**Comment by LinuxOnTheDesktop** [comment]
Yet, it seems that (1) there is a malfunction, (2) the intended working is confusing.

1: there swathe of emptiness is to be seen only when UBO is set to 'advanced' mode, no? Yet, I see when I have disabled advanced mode.

2: you had to explain the swathe of emptiness of me; I suspect you will have to explain it to others.

**Comment by uBlock-user** [comment]
> there swathe of emptiness is to be seen only when UBO is set to 'advanced' mode, no? Yet, I see when I have disabled advanced mode.

If there's no connection to be made to any domain the "swathe of emptiness" will appear, if you don't like the `swathe of emptiness`, you can hide that via clicking on domains connected in the popup panel.
