### ISSUE TITLE
Blocked request to yolo.org due to blacklist

### ISSUE THREAD

**Issue by moerkey** [uBlockOrigin/uBlock-issues#481]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hello, uBlock origin is doing a request to https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext.

Our Advanced Threat Protection is blocking these requests.

The domain yolo.org is currently blacklisted: https://mxtoolbox.com/domain/pgl.yoyo.org/

The server seam to be sloppy configured because it is running an old Ubuntu and has an open MySQL database running.

### A specific URL where the issue occurs

https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext.

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Start FF with uBlock origin installed.
2. [Second Step]
Check your ATP.
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.18.6
* Browser Name and version: FF 66.0
* Operating System and version: Ubuntu 18.04

**Comment by uBlock-user** [comment]
> Our Advanced Threat Protection is blocking these requests.

False postive, tell your antivirus to whitelist that url, it's for updating Peter lowe's ads and tracker filterlist.

**Comment by moerkey** [comment]
Then please tell Peter lowe's ads and tracker filterlist that his server is blacklisted. Otherwise your reputation will be affected too.

**Comment by uBlock-user** [comment]
@pgl

**Comment by pgl** [comment]
Actually, in this case, it's because of an issue with a mail server (`mx1.yoyo.org`) being blacklisted. My site isn't blacklisted at all, fortunately.

It's running Ubuntu 16.04 LTS, ie, Long Term Support. This will be supported [until 2021](https://www.ubuntu.com/about/release-cycle).

The Barracuda and Backscatterer blacklists are shit, IMO, but I'll let the admins know.

And, as far as I know, it doesn't have an open MySQL server. I just tested and wasn't able to connect from a remote host.

**Comment by pgl** [comment]
Wait, am I reading this issue wrong? What ATP is the OP using? `mxtoolbox.com` doesn't show anything useful other than the mail server blocks. Apologies if I misread this.

**Comment by moerkey** [comment]
What is OP?

To be honest. It is really weird.

The ATP is annoyed by a request from my client (uBlock) to aucklandstreets.com. But I guess this is a wrong lookup from the ATP.

aucklandstreets.com uses the IP 213.230.210.230 (dig aucklandstreets.com).

But why then yoyo.org? 
The dns ptr for 213.230.210.230 is pointing to boo.yoyo.org (dig -x 213.230.210.230).
pgl.yoyo.org is pointing to 213.230.210.230 (dig pgl.yoyo.org).

And a netcat to this IP 213.230.210.230 on port 3306 is successful (nc -vz 213.230.210.230 3306).

It looks like a shared system.

Anyway, it shouldn´t be the case that a blocking for mx1.yolo.org (193.110.180.11) also affects another IP and the services behind that.

Thx for the support.

**Comment by pgl** [comment]
OP = Original Poster, I meant the person who submitted this issue in the first place. So, you @moerkey. :)

What ATP are you using?

You can connect to port `3306` on `boo.yoyo.org`, but you won't be able to access anything.

**Comment by moerkey** [comment]
A firewall is recommended. Just one patch not installed immediately and the scanner have success faster then someone wants to.

We are using Sophos ATP.

**Comment by pgl** [comment]
Thanks for the advice.

I would suggest contacting Sophos to ask them where someone can contact them regarding their blocklist. I'd be happy to get in touch with them.

**Comment by pgl** [comment]
OK, I found their "website reassessment" page.

Which of these products are you using:

![image](https://user-images.githubusercontent.com/1181139/54818021-94ff2580-4c98-11e9-9128-962e8fd38f45.png)

?

**Comment by pgl** [comment]
Sophos [responded to me on Twitter](https://twitter.com/Sophos/status/1109115714726580224), and their support account asked for details, which I've provided. Hopefully they'll be able to tell me more.

**Comment by pgl** [comment]
They asked what software is being used exactly. Apparently the IP is blocked in the category of "Entertainment", whatever that means.

**Comment by pgl** [comment]
OK, I've been in touch with them, and apparently the IP isn't listed as malicious at all - it's just *categorised* as Entertainment. Whoever configured the Sophos app has chosen to block sites in this category.

**Comment by pgl** [comment]
I've just heard from someone else, who reported the same issue privately, that their admins didn't configure anything - so the "Entertainment" category might've been blocked by default. Also, they said that they're now able to get to https://pgl.yoyo.org/as/ fine and don't see warnings anymore, so it may have been unblocked.

Weird.

**Comment by moerkey** [comment]
I can approve that it works now.

JFYI: In our appliance we can not deal with a category entertainment.
I guess Sophos did some magic. 

Anyhow, thx for the support.
