### ISSUE TITLE
element picker mode not activating in video pages

### ISSUE THREAD

**Issue by ISSUES999** [uBlockOrigin/uBlock-issues#482]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.18.6
* Browser Name and version:opera 58
* Operating System and version:win 7   32 bit

so besides the obvious ad-block detection
and the ads bypassing u-block origin 
and of course the video servers keep refusing to play the rest of the video when u block their ads
now we have the element picker mode not activating in video pages only , in the rest of the site its just fine , any way to counter that?

**Comment by uBlock-user** [comment]
Fill the template as asked, until then marking it as invalid.
