### ISSUE TITLE
Windows defender classify the uBlock Firefox add-in as malware

### ISSUE THREAD

**Issue by Bartolomeus-649** [uBlockOrigin/uBlock-issues#483]
Just now Windows defender popped up claiming the uBlock Add-on for Firefox is/contains a trojan called: `Trojan:Script/ForeType.A!ml`

![image](https://user-images.githubusercontent.com/7513795/54860360-244c1d80-4d19-11e9-9c18-9958938d1bbc.png)

**Comment by colbycdev** [comment]
It's all part of @gorhill/uBlock<mailto:uBlock@noreply.github.com> plan. Mwahaha

Really, it's probably a false positive.
If you feel paranoid, run an antivirus scan
________________________________

**Comment by gorhill** [comment]
False positive.
