### ISSUE TITLE
uBo disabled in Firefox 66 because of obsolete key-value pair in manifest.json

### ISSUE THREAD

**Issue by apoleon** [uBlockOrigin/uBlock-issues#486]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The webext version of ublock-origin does not work with Firefox 66. The reason is an obsolete entry in platforms/webext/manifest.json. Firefox 66 will deactivate the addon if the key-value pair: "incognito": "split" is present. This works only for Firefox < 66 and in Chromium. 

### A specific URL where the issue occurs

https://tracker.debian.org/pkg/ublock-origin

### Steps to Reproduce

1. Install Debian's webext version.
2. Start Firefox 66. The addon is disabled.
3. Start Firefox < 66 and the addon works as expected.

### Expected behavior:

Addon is enabled

### Actual behavior:

Addon is disabled

### Your environment

* uBlock Origin version: 1.18.4 and 1.18.10
* Firefox 66
* Debian GNU/Linux 10 "Buster" (amd64)

**Comment by gorhill** [comment]
Sounds like an unsolvable issue.

I was asked by Debian people to create a single package for both Chromium and Firefox, hence why the manifest contains keys which are invalid on one or the other platform. So far these invalid entries have only caused warnings. But now if you tell me this prevents uBO from functioning properly, the only solution I see is to have two packages -- `"incognito": "split"` is required for Chromium, or else uBO will malfunction in incognito mode.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1380812 Support incognito permission "split"

**Comment by apoleon** [comment]
The "spanning" value is supported by both web browsers. Maybe the webext manifest file could be changed to this one.

**Comment by gorhill** [comment]
Using `spanning` break Chromium in incognito mode, see <https://github.com/uBlock-LLC/uBlock/issues/1225>.

**Comment by gorhill** [comment]
@apoleon Isn't there a way to install two versions from the same package? One with the key and another without the key? Maybe have the two versions link to the same files except where files must differ? I know nothing about Debian package installation, sorry if I spout nonsense.

**Comment by apoleon** [comment]
Hi,
the current rationale for using just one version of ublock-origin is because we need only one package per addon for firefox and chromium. Users just install webext-ublock-origin or webext-https-everywhere and it works for both browsers. Nowadays every webextension package works this way in Debian and so far there were no major issues. On the one hand this is convenient for users and maintainers and on the other hand we can avoid code duplication because both packages would only differ slightly. I don't know a good way to tell Firefox or Chromium to load certain values or files. They just have a search path and then load the addon in /usr/share/webext. I can't install two different versions of a package into the same directory or I have to add a Conflicts relation which means users can only install the Firefox version or the Chromium version of uBo at the same time. Personally I wouldn't mind to make an exception and revert to the previous state in Debian when we shipped separate packages for Chromium and Firefox but currently I don't know how to avoid the earlier mentioned issues. I will discuss this with the previous maintainers of uBo and see if we can come up with a solution.

**Comment by TheHiddenGamer23** [comment]
This issue seems to be fixed as of Firefox 66.0.4

**Comment by gorhill** [comment]
@apoleon 

I came upon this [discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926586#20).

Truth is the webext platform is not optimal for either Chromium or Firefox.

Beside the `manifest.json` file, there are two other specialized files which benefit Firefox version, see <https://github.com/gorhill/uBlock/tree/master/platform/firefox>.

For example, without these specialized files, uBO won't be able to properly block early network request at launch time, which is a (key) Firefox-only feature (Chromium is not properly equipped to do this).

So far, there have been only these two files for quite a while now, so I do not expect changes about this for the foreseeable future.

**Comment by apoleon** [comment]
We decided to change our packaging to avoid such problems in the future. We use symlinks and install both manifest files now, Chromium and Firefox. I will take care of the other Firefox specific files too. It would be easier for us if we could keep the make-webext.sh script, so that we could just call that to install the files and then we would make our changes for those files that are different between Chromium and Firefox. At least some indication what is different between those two browser would help too. I will upload the latest release of uBO to Debian experimental this weekend, everyone who is interested in it, can give it a try and report back if it works correctly. Thanks for all your feedback, I guess we can close this issue now
