### ISSUE TITLE
uBlock Origin Icons missing.

### ISSUE THREAD

**Issue by mattyams** [uBlockOrigin/uBlock-issues#487]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In Chrome 73.0.3683.86 icons do not show on the uBlock Origin popup. I noticed after inspecting the popup in Chrome that it can not find a file specified. After searching all over this tracker, the old tracker, reddit and the web I can not find an answer.  Tried Incognito, no profile, no other extensions installed, remove and installing extension all with no luck.  Attached are 2 screenshots. 1 of the issue and the other of the Chrome Inspect window. 

### A specific URL where the issue occurs

Everywhere, but here is an example: https://mightytext.net/web8

### Steps to Reproduce

1. Open Chrome
2. Click on uBlock Origin icon.
3. Popup shows no icons.

### Expected behavior:

Power Button icon and per site icons to appear.

### Actual behavior:

No icons appear

### Your environment

* uBlock Origin version: 1.18.10
* Browser Name and version: Chrome 73.0.3683.86
* Operating System and version: Windows 10 Pro 1809

![2019-03-25_12-46-02](https://user-images.githubusercontent.com/16708009/54940595-620b9a80-4f01-11e9-8bd6-c279c2154e83.jpg)
![2019-03-25_13-00-58](https://user-images.githubusercontent.com/16708009/54940598-62a43100-4f01-11e9-88a7-bc40ea295430.jpg)

**Comment by mattyams** [comment]
Mark this as solved. The one thing I didn't try worked. 

I found that my User Data folder at C:/Users/%username%/AppData/Local/Google/Chrome was corrupt. 

I renamed it to User Data.bak and restarted Chrome.  All issues went away.

**Comment by mattyams** [comment]
Ok, this happened again after 2 day of no issues. Any ideas where to start looking for the issue?

**Comment by uBlock-user** [comment]
@mattyams Take a backup of uBO all uBO settings and reinstall uBlock Origin

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/gny5zt/some_of_ubos_art_assets_disappeared_and_i_dont/

>A new profile didn't fix the problem sadly, reinstalling Chrome/Edge didn't either. I noticed that right clicking the empty assets and choosing 'Open image in new tab' started downloading the file instead of showing it. After messing around some more it turns out that Windows' registry entries for svg (`HKEY_CLASSES_ROOT\.svg, HKEY_CURRENT_USER\Software\Classes\.svg`) must've gotten messed up - deleting those 2 keys fixed it for me!

**Comment by rushglen** [comment]
Using Chrome 92.0.4515.159 icon doesn't show so extension is unusable, never had this problem with any other extension.
