### ISSUE TITLE
Add list-specific donation buttons in the 'Filter lists' tab

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#489]
Following the years-old uBO mantra of *"If ever you really do want to contribute something, think about the people working hard to maintain the filter lists you are using, which were made available to use by all for free."*, which is shown both on the browser extension store pages and GitHub readme page of uBO, I hereby propose adding a donation button for filterlists right next to their home and/or info buttons.

Of the lists that are included in uBO, I am at the time of writing aware of 6 lists that have donation options:

* Fanboy (https://www.paypal.com/donate/?token=QBPWIOSwJsLCg43JrpFV3rsYb58NNzZu-az6pM5yRWKHyi5Ao6FIslRjZgD2uHLMNAImOm&country.x=NZ&locale.x=NZ)
* Peter Lowe (https://www.patreon.com/blocklist)
* X Files (https://www.patreon.com/gioxx)
* Dandelion Sprouts nordiske filtre (https://sproutsluckycorner.wordpress.com/2017/11/14/my-work-and-contact-resume/#donations)
* ABPVN (https://www.facebook.com/notes/b%E1%BB%99-l%E1%BB%8Dc-qu%E1%BA%A3ng-c%C3%A1o-cho-ng%C6%B0%E1%BB%9Di-vi%E1%BB%87t/ki%E1%BA%BFm-ch%C3%BAt-ti%E1%BB%81n-l%C3%BAc-r%E1%BA%A3nh-r%E1%BB%97i/1663248030564655)
* MVPS Hosts (http://winhelp2002.mvps.org/hosts.htm#donation)

Of additional note is that henrik.schack.dk, which is the homepages of *Schack's Adblock Plus Liste*, supports Flattr. However, since Flattr broke the last remnants of its manual Flattr donation button two months ago, I'm unsure how/if a donation button for it in uBO would've worked.

**Comment by gorhill** [comment]
There is a home page link, this is amply sufficient.

**Comment by DandelionSprout** [comment]
Duly noted. 🙂
