### ISSUE TITLE
UBlock Not Working on 9Anime

### ISSUE THREAD

**Issue by Asian-Rabbit** [uBlockOrigin/uBlock-issues#49]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[ What I see [ https://drive.google.com/file/d/1bepxRaZX40OQ9Ycp_dopqnlaOqGmV08h/view?usp=sharing ](url)]
[ My settings [ https://drive.google.com/file/d/1Mmg-Z0xdolm0C5wIkHSt_-0eWYs6aLtq/view?usp=sharing ](url)]
[ Filter List [ https://drive.google.com/file/d/1Mmg-Z0xdolm0C5wIkHSt_-0eWYs6aLtq/view?usp=sharing ](url)]
[ My Filter [ List https://drive.google.com/file/d/1KdE3ncJZ_eAofzLL7ZLIza3LSwChp2HG/view?usp=sharing ](url)]
[ My Rules [ https://drive.google.com/file/d/1KdE3ncJZ_eAofzLL7ZLIza3LSwChp2HG/view?usp=sharing ](url)]
[ Whitelist [ https://drive.google.com/file/d/1Fh1g4HGKsKgNEzH3SUPCwV10KEtSMn8d/view?usp=sharing ](url)]

### Steps to Reproduce

1. [Open 9anime]
2. [Click an anime]
3. [Play It]

### Expected behavior:

[Able to watch without ads]

### Actual behavior:

[Cant watch with out ads]

### Your environment

* uBlock Origin version: 1.16.6
* Browser Name and version: FireFox Quantum 60.0.1 (64-bit)
* Operating System and version: Window 10 Home

**Comment by mapx-** [comment]
filter issue, use the correct repository
https://github.com/uBlockOrigin/uAssets/issues/2333

update your lists
