### ISSUE TITLE
uBlock use a MAX_DISK_USE setting not request "Unlimited storage" under Firefox 

### ISSUE THREAD

**Issue by aplatypus** [uBlockOrigin/uBlock-issues#490]
### Prerequisites

- [X] I verified that this is not a filter issue
- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [x] I am running the latest version of uBlock Origin

### Description

With the new firefox 67.0b5 (64-bit) the uBlock plugins asks for "Unlimited Storage" now that we have these NEW Permissions.

While it is good that apps check -- I feel strongly that this query should be a prompt for a finite number as the answer to this sort of question.  

I have checked this PC's use of the disk = almost 8MB

It also should be something the plugin must put on an options page so that the number can be changed.  And then you or firefox can ask if 10MB is OK for blocking storage.

This can be similar to the size of the cache firefox uses.  I do  not feel comfortable giving a blank cheque to any plugin.  Thee can be bugs and discovering that a plugin has eaten up a disk-drive would be extremely difficult to identify.  Plugins should decide how much disk they might/should allocate or allow for.  And that can be changed by the customer.

### A specific URL where the issue occurs

https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct

### Steps to Reproduce

1. Install uBlock in latest Firefox Developer build

### Expected behavior:

Prompt for an actual number to store as an option MAX_DISK_USE

### Actual behavior:

Requests unlimited storage

### Your environment

* uBlock Origin version:  uBlock Origin v1.18.6
* Browser Name and version:  firefox 67.0b5 (64-bit)
* Operating System and version: Ubuntu 18.10 64-bit

**Comment by gorhill** [comment]
You control the disk usage of uBO through the number of filter lists you select. uBO informs you of the amount of storage in use in its _Settings_ page in its dashboard --- use the information to make decision about filter lists, custom filters, rules.

**Comment by gorhill** [comment]
By the way, if you really want Firefox to let you pick the maximum amount of storage an extension is allowed to use, you will have to open an issue for this with Firefox developers. Currently all extensions are free to use as much storage as they wish, even without declaring `unlimitedStorage`.

Even with the new permission, in its default state uBO is not allowed to use as much storage as it wishes, it's limited by the [browser heuristic for indexedDB's](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria) which if I remember correctly is roughly 10% of available disk storage. This limit has caused [issue in the past](https://github.com/uBlockOrigin/uBlock-issues/issues/141) hence why [LZ4 compression was integrated](https://github.com/uBlockOrigin/uBlock-issues/issues/141#issuecomment-407745246) into uBO.

**Comment by uBlock-user** [comment]
>  I do not feel comfortable giving a blank cheque to any plugin

Yet you feel comfortable using uBO on Chromium where this permission has existed since the beggining, this is the problem with today's users. Add one new permission that rectify another potential and everybody goes up in arms.

**Comment by fifthgearonline** [comment]
> 
> 
> You control the disk usage of uBO through the number of filter lists you select. uBO informs you of the amount of storage in use in its _Settings_ page in its dashboard --- use the information to make decision about your choice of filter lists, custom filters, rules.

What is the purpose of this new permissions request? What issue mandated its inclusion?
