### ISSUE TITLE
filter editor search enhancements

### ISSUE THREAD

**Issue by filbo** [uBlockOrigin/uBlock-issues#493]
Hi,

(mistakenly posted this as https://github.com/uBlockOrigin/uAssets/issues/5241, sorry...)

Within uBO options, when looking at / editing a specific filter list, I was looking for filter lines which would affect github.io.  I searched for `github` and was dismayed to see '1000+' hits in the main 'uBlock filters' list.

Now, there is a trivial workaround for my use case (actually enter `github.io`); but suppose I were truly looking for an issue with github.com?  The 1000+ mentions of `https://github.com/uBlockOrigin/uAssets/issues/%d` would block me completely.

... which led me to wish for two (and a half) things:

1. search-within-list which is comment-sensitive; that is, ignore lines which are comments
  a. suboption which includes comments which are valid rule syntax, ignoring only human-readable comments; obviously, not the default...

2. search-within-list which is domain-sensitive; that is, find rules which match the given domain or domain-wildcard.  This would do wildcard matching in both directions: I enter `github.io`, it matches rules looking for `github.io` and `github.*`; I enter `github.*`, it matches both of those + `github.com`.  Possibly 'domain' is the wrong concept; searching for `*.github.io/*.css` ought to be able to match rules with that specificity.

The UI could look something like:
![uBO-filter-search](https://user-images.githubusercontent.com/3022180/55194168-1c9bd700-5166-11e9-8c09-f5c32fd34ecc.png)

**Comment by filbo** [comment]
Or possibly like this (except probably a pulldown menu rather than radio buttons):
![uBO-filter-search2](https://user-images.githubusercontent.com/3022180/55204221-64812500-518b-11e9-9f97-a79590eb4233.png)

**Comment by uBlock-user** [comment]
You mean to suggest "Don't count results from commented lines" right ?

**Comment by gwarser** [comment]
This field supports regex (`/.../`), assertions should work, but they don't :(

Maybe because multiline is enabled by default?

**Comment by filbo** [comment]
I mean to suggest multiple things.

Sometimes a comment is exactly what I'm looking for.  Other times it's something about a rule.  Therefore, it would be helpful to have a control in the widget, telling it whether or not to consider comments.

Then I additionally thought of a sub-control which would have it search rules + commented-out rules, but not 'real' comments.  This would search all rule lines, plus all commented-out lines which parse successfully as rules.  I particularly imagine using this when I had commented out some rule, thinking it was no longer needed, then realized it was still needed.  The likely search string I remember for that rule is something that would hit in a lot of 'real' comments, so omitting those would help.

...

and, _domain match_ would help quickly ask a particular list: which of these rules apply to this site I am scrutinizing right now?

**Comment by gorhill** [comment]
So far, what I am reading is a request to add a lot of effort, code, development time and future maintenance for _"what if I want to search for `github.com`"_. @gwarser provided a solution for this one case.

**Comment by gorhill** [comment]
> Maybe because multiline is enabled by default?
> 
> `/^[^!\n][^\n]+github/` ???

Yes, I switched `multiline` to `false` [here](https://github.com/gorhill/uBlock/blob/4e01e2672a40bcc654f165449508be5ae3f5f703/src/js/codemirror/search.js#L173), and that fixes the search. However, there seem to be a CodeMirror bug, because after this, the search itself works as expected, but the scrollbar annotations are still reporting 1000+ hits. I created a fix locally, I will have to create a pull request to CodeMirror.

**Comment by gwarser** [comment]
@gorhill, if you are looking at CodeMirror regex, maybe you will also take a look at this https://github.com/codemirror/CodeMirror/issues/5428

**Comment by gorhill** [comment]
I consider the issue addressed here with commit <https://github.com/gorhill/uBlock/commit/72bbcdd93c653ebd57667dc6f32a645c67161a1c>. That commit prevent multiline matches when using a regular expression. Using a regular expression is the way to address fancy search behavior -- I decline to work on modifying the current UI as suggested.
