### ISSUE TITLE
Ublock break Chrome inbuild pop-up blocker

### ISSUE THREAD

**Issue by TheownerCZ** [uBlockOrigin/uBlock-issues#497]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Chrome no longer block pop-ups with Ublock Origin installed
[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:
Chrome should block pop-ups same way as without Ublock Origin
[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.18.14
* Browser Name and version:Chrome 73.0.3683.86
* Operating System and version:Win 7 64bit

**Comment by gwarser** [comment]
@TheownerCZ no need to create new issues with one sentence of description. You need to fill template completely. If you have something more to say - just add new comment.

All is working fine here: http://raymondhill.net/ublock/popup.html

uBO is even too aggressive (test descriptions needs update?)

**Comment by gorhill** [comment]
He has been blocked. There is no excuse to open twice the same issue with absolutely no effort to fill the template and otherwise no details at for anybody to have a clue of what is the issue. Volunteers invest their free time into all this, there is no tolerance for time-wasting negative contributions.

**Comment by gwarser** [comment]
Looks like OP really found something https://old.reddit.com/r/uBlockOrigin/comments/ba9ety/ublock_origin_break_popup_blocker_in_chrome/

But I don't think it's in uBO - more like Chrome issue.

**Comment by uBlock-user** [comment]
Chrome's popup blocker doesn't kick in when uBO's installed, known about this since a long time, thought this was by-design.

**Comment by gorhill** [comment]
It's always popup5 on my side which makes it through the browser's built-in popup blocker (beside popup7 which always opens with or without uBO).

**Comment by gorhill** [comment]
Repro steps:

1. Go to http://www.popuptest.com/
2. Click "Multi-PopUp Test" link

Works all fine with Firefox Nightly on my side, while with Chromium I get popup5 at step 2, and popup7 when clicking the "Back" button once step 2 completes.

**Comment by gorhill** [comment]
I found that if you open the dev console, popup5 is not blocked whenever the browser reports the following in the console:

> [Violation] 'load' handler took 254ms    popuptest1.html:formatted:26

This is the page's own popup opening code.

If the console does not report the above warning, there is no popups. When I use back and forth button, there is no warning and thus no popups.

**Comment by gorhill** [comment]
At `http://www.popuptest.com/popuptest4.html`, you can easily trigger the popup without uBO enabled:

1. Navigate to `http://www.popuptest.com/popuptest4.html`
1. Mouse over link named "Mouseover PopUp"
1. Popup blocked by the browser
1. Click anywhere in the background
1. Mouse over again

Result: Chromium fails to block the popup.

Definitely a browser issue.

**Comment by gorhill** [comment]
Spend a great deal of time of trying to figure if I could craft a workaround, and it's not possible.

JavaScript event handlers on a page preceding the opening of a popup seem to have an effect on whether the popup is properly blocked by Chromium, and this is also true without uBO -- as explained above. Thus, closing as a browser issue, this should be reported to Chromium devs.
