### ISSUE TITLE
Logger for specific tabs

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#499]
@gorhill How about writing logs for specific tabs only?
**how about sorting?**

Suppose I have 3-4 tabs open.

1 twitch (in the background)
2 ublock network request log
3 some site that I track in the log (However, this site redirects or, for example, opens a popup window to another site.)
4 some other site
And I want to track ONLY what happens on the 3 tab, but how can I be with twitch.tv?
Twitch.tv (or another site) clog the log:
`https:///video-edge-1234567890.abs.hls.ttvnw.net/text`

how do i pause the log in tab number 1?

**Comment by gwarser** [comment]
Switch to page 3 using page selector https://github.com/gorhill/uBlock/wiki/The-logger#page-selector

**Comment by bogachenko** [comment]
I apparently gave you the crappy example. then easier. how to write only those tabs that I need?

**Comment by bogachenko** [comment]
@uBlock-user okay

**Comment by uBlock-user** [comment]
Didn't you question get answered ?

**Comment by bogachenko** [comment]
It's not a question. And no. Logging specific tabs are not here

> 
> 
> Switch to page 3 using page selector https://github.com/gorhill/uBlock/wiki/The-logger#page-selector

**Comment by gwarser** [comment]
By default "Current tab" entry is selected, switching tabs updates logger content. But if you switch to "Page 3" it will stick to this page.

**Comment by bogachenko** [comment]
OK, but if We increase the rates. and let's say I open not 3-4, but 5-10? And let's say I need the 7 tab not to be recorded, its garbage, i only need 5, 6, 8, 9, 10, how?

**Comment by gwarser** [comment]
>I need the 7 tab not to be recorded, its garbage, I need to 5, 6, 8, 9, 10,

All this at once? Impressive ;)

Close these 7 not needed? Filter them out? (regex is spported) Open in new, clean browser profile?

**Comment by bogachenko** [comment]
okay. forget. not about that
