### ISSUE TITLE
uBlock Origin makes address field sluggish on startup

### ISSUE THREAD

**Issue by forthrin** [uBlockOrigin/uBlock-issues#5]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

See Reproduction

### A specific URL where the issue occurs

N/A. Happens on startup before you have gone to any page.

### Steps to Reproduce

- In System Preferences, set Keyboard Repeat to maximum and Keyboard Delay to minimum.
- Close Firefox.
1. Start Firefox
2. Immediately start typing an address in the address field
3. After a second, typing is sluggish for a second, inhibiting your typing, before it catches up.

The bug becomes immediately clear if you simply hold down a key, eg. "F" in the address field. The adding of F's is clearly held back by performance issues before it eventually catches up.

### Expected behavior:

With uBlock Origin disabled or uninstalled, typing in the address field is fast and uninhibited.

### Actual behavior:

Sluggish performance in Address field. Suspect due to uBlock Origin is doing heavy initialisation.

### Your environment

* uBlock Origin version: 1.15.24
* Browser Name and version: Firefox 59.0.2
* Operating System and version: macOS 10.12.6

**Comment by gorhill** [comment]
- Disable uBO.
- Start Gecko profiler.
- Enable uBO. Wait 10 second.
- Share profiling results.

Only proven performance issue will be taken seriously, not "suspected" ones. Your browser has all the tools to make prove performance issues.

**Comment by gorhill** [comment]
I won't do this every time, the rule regarding "performance issue" should apply here as well, or else it's a pass for whoever to waste the time of volunteers. The rule:

**Purported performance issue MUST be accompanied by profiling data making the case.**

Now this is what I get with uBO in its non-optimized state (i.e. no selfie), with default lists + EasyList Germany -- less than half a second to full load:

![a](https://user-images.githubusercontent.com/585534/38951352-61802ee8-4316-11e8-8800-7ef0930ff29c.png)

**Comment by gorhill** [comment]
And this is the profiling result with a valid selfie -- what I consider the typical case for most people -- ~150ms to fill load:

![a](https://user-images.githubusercontent.com/585534/38953754-bbfe7904-431d-11e8-8ea3-a26b22969d80.png)

**Comment by forthrin** [comment]
@gorhill: Were you able to reproduce the sluggishness in the address field?

Do you need more information from me?

**Comment by forthrin** [comment]
Absolutely. A clean install of the latest Firefox with the latest uBlock Origin. Maybe it's an issue with my Mac (Late 2014 Air), but I think this happens on my other Mac too. I will double-check and write back.

**Comment by gwarser** [comment]
UBO is highly optimized for startup performance. I will close this issue, until you provide hard evidence (profiling data, or exact code that's failing) for your claims. Gorhill show you example, how this should look like here https://github.com/uBlockOrigin/uBlock-issues/issues/5#issuecomment-382485294

Also: 

I don't think these are normal settings for daily use:

>System Preferences, set Keyboard Repeat to maximum and Keyboard Delay to minimum.

and with these settings, what you describe:

>After a second, typing is sluggish **for a second**, inhibiting your typing, before it catches up.

is not unexpected. 

I can reproduce very small "hiccup" (10+ year old pc with Linux), but I cannot describe this as "sluggish", and surely I will not worry about this.

UBO must load couple of megabytes of filters from database on startup (using browser API, so nothing can be improved on UBO side). You can try to reproduce with all filters disabled.

**Comment by gwarser** [comment]
You may experience Firefox problems, look at this https://www.reddit.com/r/firefox/comments/8dgb5g/i_would_love_to_use_firefox_but_spoiler_its_not/
I also remember, that Firefox has problems with very high memory usage on Mac.
