### ISSUE TITLE
Make the names of included filterlists translatable

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#503]
While I'm getting translation-related ideas anyway, it struck me tonight that it'd be convenient both for a fair few end-users to better understand what a list is about, and for list makers to reach out better to fellow countrymen and to English-dependent foreigners alike.

Therefore I hereby propose to make it possible to add (carefully curated) translations for the titles of uBO's included filterlists. Just to make sure, this wouldn't be something that could've been handled willy-nilly on Crowdin, and the list maintainers would have the final say and/or override on which translations that would've been used for their own lists. Here's a quick list of theorethical examples:

| English | Norwegian | Other relevant language |
| - | - | - |
| uBlock filters - Badware risks | uBlock-filtre - Skadevarerisikoer | |
| uBlock filters - Privacy | uBlock-filtre - Privatliv | (German) uBlock-Filter - Privatleben |
| uBlock filters - Resource abuse | uBlock-filtre - Ressursmisbruk | |
| AdGuard Annoyances filter | AdGuards forstyrrelser-filter (which is AdGuard's official translation for it) | |
| Dandelion Sprout's Nordic Filters | Dandelion Sprouts nordiske filtre | (Icelandic) Dandelion Sprouts norrænir síur |
| Estonian Custom Sites Filter | *Tilpasset filter for estiske nettsteder* | (Estonian) Eesti saitidele kohandatud filter |
| EasyList China | *EasyList Kina* | (Simplified Chinese) EasyList 中文 |
| Adblock List for Finland | *Adblockliste for Finland* | (Swedish) Adblocklista för Finland |
| Official Polish Filters for AdBlock, uBlock Origin, and AdGuard | *Offisielle polske filtre for AdBlock, uBlock Origin, og AdGuard* | (Polish) Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda |
| Frellwit's Swedish Filter | Frellwits svenske filter | (Swedish) Frellwits svenska filter |

(*Italics* are cases where the Norwegian translation isn't particularly relevant to the list in question.)

This would've resolved a decent amount of thoughts one may have about various lists. Someone from e.g. the United States would've had zero idea what `EST: Eesti saitidele kohandatud filter` meant, but would've quite easily understood `EST: Estonian Custom Sites Filter`.

Conversely, a non-tech-savvy layman from Germany may have an easier time relating to the purpose of `uBlock-Filter - Privatleben` rather than `uBlock filters - Privacy`.

Some words should essentially never be translated, such as *EasyList*, seeing how much of a sort-of world-famous staple that name has become.

Thoughts?

**Comment by gorhill** [comment]
The filter lists can be changed without having to update uBO. There should be no dependency of these lists onto uBO package, where the translation resides. Declined.

I plan to increase my free time away from this project, and such request is akin to asking me to devote all my free time for the foreseeable future in ever increasingly marginal issues.
