### ISSUE TITLE
wrong Map method used

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#504]
The method in [this line](https://github.com/gorhill/uBlock/blob/1.18.14/src/js/static-net-filtering.js#L2274) should be `.size` because it's a Map. (Surely you don't want the [default length method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) here.)

Very minor because the default lists contain many $csp rules, so the vast majority of users won't see a difference. (But still worth a simple fix for correctness sake.)

**Comment by gorhill** [comment]
Can you open a pull request for this? Pull requests are fine for fixes like this.

**Comment by joey04** [comment]
Sorry, no, I'm not setup with git and such. Plus you have to decide to either replace the method or just remove the line (for the reason I mentioned above).

**Comment by n-leigh** [comment]
Made a PR for this: https://github.com/gorhill/uBlock/pull/3755
