### ISSUE TITLE
Picker doesn't include element name for suggested attribute rules

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#505]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The element picker doesn't include the target's element name when suggesting CSS attribute rules.

If these attribute rules are created by a user, the browser will have to check all elements.

It would be better if the picker prepends the element name. For the example below, the suggestions would become:
`##img[src="<>"]`
`##a[href="<>"]`

### A specific URL where the issue occurs

`https://github.com/gorhill/uBlock/issues/1890`

### Steps to Reproduce

1. Go to the URL.
2. Open the picker.
3. Select the first screenshot in the initial post.

 The picker suggests two attribute rules:
`##[src="<url>"]`
`##[href="<url>"]`

### Your environment

* uBlock Origin version: 1.18.14

<hr>

**Update:**
I got to the bottom of this issue. It's a regression that's easy to fix. See below for details.

**Comment by uBlock-user** [comment]
uBO treats `##img[src="<>"]` as `##[src="<>"]` just like it does for `##div.example` as `##.example`. I don't consider this a bug.

**Comment by joey04** [comment]
I don't agree with your comparison. A class list selector is almost no overhead compared to a single class. Plus uBO leverages the power of user stylesheets nowadays; so, yes, it "treats" them the same by simply passing valid selectors to the browser. Then the layout engine does all the work.

I'm not sure if this is a bug or enhancement. Depends on how much extra processing is required (on average) for the layout engine to query every single element on a page versus just the appropriate subset. (I don't know the answer, though one mitigating factor is that layout engines are optimized C++ code.)

**Comment by uBlock-user** [comment]
What I'm saying is this is by-design and has been there since the beginning.

**Comment by gwarser** [comment]
> the browser will have to check all elements.

>It would be better if the picker prepends the element name. 

Any source for this or just a guess?

**Comment by joey04** [comment]
I got to the bottom of this tonight, and it is a regression. (See [this screenshot](https://github.com/gorhill/uBlock/issues/1901) for proof.)

When gorhill fixed #17 last year he removed [this line](https://github.com/gorhill/uBlock/commit/674c3c60796d90213a451b5b94c1107f26683def#diff-a65f6e6abc235a14e93548d8bf53b81eL503), which was what ensured the element name appeared.

<hr>

The fix is easy. Just insert this:

`if ( selector !== '' ) { selector = tagName + selector; }`

after [this line](https://github.com/gorhill/uBlock/blob/1.18.14/src/js/scriptlets/element-picker.js#L575) in the current code.

**Comment by gorhill** [comment]
> it is a regression

A regression is a code change leading to a bug. You are dismissing that I may have done that one purpose. That [line](https://github.com/gorhill/uBlock/commit/674c3c60796d90213a451b5b94c1107f26683def#diff-a65f6e6abc235a14e93548d8bf53b81eR548) clearly shows the change was on purpose.

**Comment by gwarser** [comment]
Not really comparable to uBO, but for general perspecive:

https://jsperf.com/jquery-attribute-selector-with-tag-name-vs-without-tag-

[test-html.zip](https://github.com/uBlockOrigin/uBlock-issues/files/3044559/test-html.zip)

**Comment by joey04** [comment]
> I may have done that one on purpose.

You stripped away the element name on purpose? That means less info presented for rule creation and overall slower performance (10-15% slower across 3 runs of gwarser's benchmark). On top of that, there's no documentation of this change, which was bundled in a commit for an unrelated bug (double body tag). So, yes, of course I thought it was a regression.

Now I see `¯\_(ツ)_/¯` in the commit. Kinda sums that one up.

Anyways, I've resolved this on my end and spent some time learning other parts of the Picker code. That gave me a fresh appreciation for all the hard work that you've put in to this wonderful tool. The picker has been a great feature, and I've created many cosmetics with it. Thank you for providing this to us. (And thank you to uBlock-user, gwarser, and others for helping out the project.)

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/55627776-4761dd00-57af-11e9-8604-e3e7d71cd5ad.png)

**Comment by kulfoon** [comment]
> joey04: overall slower performance (10-15% slower across 3 runs of gwarser's benchmark).

What browser(s)? 

Also I've run benchmarks on Firefox and Opera today (6 runs each browser), so you can view the updated results at the link gwarser posted, couting the both browser's results together, the final result is:
153 591 with tag 88.9%
172 849 without tags 100%
diff = 11.1% in favour of "without tags"

(I don't use Chrome and I don't even intend to install it on my pc, also the current Chrome results seems too weak, thus I guess they are old and outdated so someone needs to run recent benchmarks on Chrome, so I don't include the current Chrome results).

**Comment by joey04** [comment]
I'm on 60 ESR. I see the opposite results:

![res](https://user-images.githubusercontent.com/14959062/55673623-61b3bd80-5878-11e9-9853-10a5f29573b3.png)

**Comment by joey04** [comment]
> the browser will have to check all elements

I need to correct my original assertion. It's not every single element in the DOM, but every element that can have that particular attribute. Not having the element name is still a _larger_ subset of DOM nodes the browser engine will have to check.

So the benchmark results I get make perfect sense to me.

**Comment by joey04** [comment]
> someone needs to run recent benchmarks on Chrome

I forgot about Chrome. Just ran it twice. Completely different results

![res](https://user-images.githubusercontent.com/14959062/55673712-75135880-5879-11e9-8966-6d5e33fdda51.png)

The inner workings of Blink are a mystery to me :)

**Comment by kulfoon** [comment]
> joey04: https://github.com/uBlockOrigin/uBlock-issues/issues/505#issuecomment-480526808: I'm on 60 ESR. I see the opposite results: ...

Not true, coz your Firefox results (+15%) are even more in favor of "with tag names" than my Firefox results (+5%), no kind of opposite result. It seems you wrongly compared your Firefox only results to my Firefox + Opera **combined** results, that's why you got opposite results...

The final verdict is that Chrome-like browsers / "without tag names" is a clear winner here in all-browsers competition,  the combined benchmarks:

Combined your Firefox + my Firefox benchmarks:  (15% + 5%) : 2 =  10% (in favor of "with tag names")
Combined your Chrome + my Opera benchmarks: (34% + 29.3%) : 2 = 31.7% (in favor of "without tag names")
The final result: 31.7% - 10% = 21.7% (in favor of Chrome-like browsers / "without tag names").
Also to the final result one might inlude Chrome-like browers popularity as another wining factor.
