### ISSUE TITLE
Restore from file doesn't work on firestick

### ISSUE THREAD

**Issue by Thomas499** [uBlockOrigin/uBlock-issues#506]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Platform: Firestick 4k

### A specific URL where the issue occurs
moz-extension://a4f235ce-729a-422e-a1c6-3790f0df6b7d/dashboard.html#settings.html

### Steps to Reproduce

1. [First Step]
transfer firefox from phone to firestick using ES File Explorer (don't use firefox that comes in the amazon store it doesn't support ad ons
2. [Second Step]
Download virtual mouse - I can paste a file for this that will work if anyone wants
3. Download UBlock orgin as a firefox add on
4. On computer, enter the custom filter list (using firestick remote takes way to long and copying and pasting isn't an option)
5. On computer click (back up to file) to transfer custom list to file. 
6. transfer the custom file from computer to firestick (using ES File explorer, put the file in downloads folder
7. Open firefox on firestick, go to Ublock settings, click restore from file

### Expected behavior:

[What you expected to happen]
I expect to either be able to choose the file, or ublock automatically be able to find the file. Even if I was required to put the file in a specific folder that would be doable. I expect to be able to load the custom settings onto the firestick for ublock so I do not have to type in the custom filters URL's by hand.
### Actual behavior:

[What actually happened]
8. This is what comes up. But there is no option to select the file. You can't even click on anything and the virtual mouse won't even show up. You can not select file, therefor transferring custom list from computer to firestick isn't an option. The only way to get custom list is to use to firestick remote virtual keyboard and type in each url by hand. 
![image](https://user-images.githubusercontent.com/38442058/55418186-fb9d0280-5526-11e9-823e-3538fdf8c20a.png)

### Your environment

* uBlock Origin version: 1.18.14
* Browser Name and version: Firefox 59.0.2
* Operating System and version: Fire OS 6.2.6.3(NS6263/2349)

**Comment by gwarser** [comment]
This looks like Android without file explorer.

Did you tried to select ES File Explorer and using it navigate to folder where you put your backup?

**Comment by uBlock-user** [comment]
He's on Fire OS which is a fork of Android, use the default File Explorer that comes with the OS..

**Comment by Thomas499** [comment]
> Question is why ES does not work.
ES does work if you open it directly. When you click "restore from file" ES does not come up. Only the picture that I referenced above. If I can move the restore file to a folder using ES, if Ublock will automatically recognize it without having to select the file when you click "restore from file" that would work. 

> use the default File Explorer that comes with the OS..

I wasn't aware Fire OS came with a default File Explorer. Unless that's what is shown in the picture that I referenced where it wouldn't let me click on anything or activate the virtual mouse. Is there a setting in Ublock where you can select which file explorer opens when you click "restore from file"?

**Comment by gorhill** [comment]
> if Ublock will automatically recognize it without having to select the file

uBO is using browser API to load the file, and the browser's file picker requires that the user explicitly select a file. Your issue is not with uBO, it's with the browser's file picker it seems.

**Comment by Thomas499** [comment]
> Your issue is not with uBO, it's with the browser's file picker it seems, or whatever gets in the way of the browser's file picker.

1. There is an app that was easily able to overcome this issue. When the user clicked "Import from external storage" the app searched for a specific labeled file within a specific labeled folder that was itself within a specifically labeled folder. In this particular apps case it looked for blokada->io.paperdb->filters2.pt 

In this way, the user didn't have to manually locate the file, the app found it automatically when "upload from external memory" was selected. I personally put the folder in the downloads folder. **Question is:** would Ublock consider implementing this so not only will it work with firesticks but also make it easier for user on all systems? I can make a walkthrough video of the app that has this functionality if you want. The app is open source so I'd think copying the way it works wouldn't take a lot of effort (assuming Ublock is written in kotlin). 

2. If this is not something that Ublock would consider implimenting, shall we close the issue as it is identified the issue at hand is not a Ublock issue, even though a work around solution for Ublock has been identified?

**Comment by gwarser** [comment]
>On computer, enter the custom filter list (using firestick remote takes way to long and copying and pasting isn't an option)

Why not hosting this custom list somewhere -> navigate to this page in browser -> click on link to subscribe?

**Comment by gorhill** [comment]
> There is an app that was easily able to overcome this issue

uBlock Origin is not an "app", it's an extension, sandboxed by the browser such that it does not have access to the file system.

**Comment by Thomas499** [comment]
> Why not hosting this custom list somewhere -> navigate to this page in browser -> click on link to subscribe?

I didn't want to type in the URL for each of the custom list using the firestick remotes digital keyboard. I was hoping to transfer all the custom list and settings from computer to firestick very quickly.

> uBlock Origin is not an "app", it's an extension, sandboxed by the browser such that it does not have access to the file system.

Valid point. Issue is closed. Thanks for taking the time to explain that.
