### ISSUE TITLE
Firefox download appears to be corrupt

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uBlock-issues#509]
### Prerequisites

- ✔️ I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- ✔️ This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- ✔️ I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ N/A ] uBlock Origin is the only extension
    - [ N/A ] uBlock Origin with default lists/settings
    - ✔️ using a new, unmodified browser profile
- [ N/A ] I am running the latest version of uBlock Origin
- ✔️ I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When attempting to download the uBlock Origin extension from the Firefox AddOns, it intermittently gives a `Download failed. Please check your connection.` error or `The addon downloaded from this site could not be installed because it appears to be corrupt`. 

### A specific URL where the issue occurs

[Here's the addon page.](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)

### Steps to Reproduce

1. Try to download the uBlock Origin extension from [the addon page.](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
2. The download fails.
3. Troubleshoot for a bit, check GitHub, and cry a little.

### Expected behavior:

Addon downloads successfully.

### Actual behavior:

Addon does not download successfully.

### Your environment

* uBlock Origin version: None installed
* Browser Name and version: Firefox [66.0.1] (Stable!! different than #124)
* Operating System and version: Manjaro Linux, 18.0.4 Illyria

I've restarted my browser a couple of times, and deleted extensions.json. Other extensions appear to download correctly.

**Comment by uBlock-user** [comment]
Disable all other extensions and try again.

**Comment by gwarser** [comment]
This sometimes happens on AMO. Just try again later.

>The addon downloaded from this site could not be installed because it appears to be corrupt

Clear browser cache.

**Comment by kulfoon** [comment]
Not uBO's issue, it's a browser or connection issue: https://github.com/gorhill/uBlock/issues/1413 + https://github.com/uBlockOrigin/uBlock-issues/issues/124

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/1413

**Comment by j-james** [comment]
Looks like Mozilla fixed the issue.

**Comment by A0R-R0CKS** [comment]
<img width="1311" height="596" alt="Image" src="https://github.com/user-attachments/assets/a1a4cb26-7269-40af-89dc-b5d10738925a" />

**Comment by gorhill** [comment]
<img width="575" height="302" alt="Image" src="https://github.com/user-attachments/assets/d7a7ac17-b310-43f2-b164-d2e15ebee530" />

**Comment by A0R-R0CKS** [comment]
Nope it will not install, try removing the add-on then reinstall its corrupted from the Firefox addons when you click on it. 
what I posted is what you get. After I tried to install the update it would not install then I removed the Add-on tried a re-install in Firefox for Windows and its saying that the Add-On is corrupted.

**Comment by gorhill** [comment]
> try removing the add-on

I installed in a fresh profile with no extension. Is the clock in your OS set to the correct time?

**Comment by A0R-R0CKS** [comment]
I uninstalled and tried to re=install it the Firefox Add on Page indicates
the Add-On is Corrupted
is there [image: image.png]
a Firefox Compatibility Issue then with 115.30.0esr (64-bit)

**Comment by freezer2022** [comment]
> A0R-R0CKS: is there a Firefox Compatibility Issue then with 115.30.0esr (64-bit)

Yes, see: https://github.com/uBlockOrigin/uBlock-issues/discussions/3890#discussioncomment-15185404
