### ISSUE TITLE
Information about configuring Firefox Sync

### ISSUE THREAD

**Issue by dud225** [uBlockOrigin/uBlock-issues#51]
Hello

I noticed multiple GH issues about cloud export through Firefox Sync but there is little information about how to configure it properly.

Here is what I grasped : 

- for the legacy version : 
   - Firefox Sync needs to be configured to manage at lest _preferences_ data
- for the webext version : 
   - Firefox Sync needs to be configured to manage at least _addons_ data (_preferences_ aren't required)
   - make sure the Firefox setting _webextensions.storage.sync.enabled_ is enabled

Note that Firefox Sync is not triggered when you export uBlock settings, it seems to be executed regularly however if you want to force the cloud export you've to launch Firefox Sync manually.

I think these additional information may be useful in the [wiki](https://github.com/gorhill/uBlock/wiki/Cloud-storage).

Regards
dud

**Comment by uBlock-user** [comment]
@gwarser Can you look into this ?

**Comment by gwarser** [comment]
About enabling sync in browser, his is from wiki "Important" box:

>Important: Even if cloud storage support is enabled, it will work if and only if you actually enable sync support in your browser...

We can link to documentation:
https://support.mozilla.org/kb/how-do-i-set-sync-my-computer
https://support.google.com/chrome/answer/165139

Not sure we need details here (syncing preferences only or digging inside about:config)

About forcing synchronization - no such thing in Chrome?

I can add this later.

**Comment by gwarser** [comment]
`webextensions.storage.sync.enabled` was changed to true in 53 [1331467](https://bugzilla.mozilla.org/show_bug.cgi?id=1331467) so it's needed for webext on ESR, in this case, using legacy UBO will be prefered.

**Comment by gwarser** [comment]
I see links are already here, Firefox one needs update. Maybe mention about Firefox "Force sync" in "Caveats"

**Comment by dud225** [comment]
Hello

> Not sure we need details here (syncing preferences only or digging inside about:config)

It depends on your use of FF Sync. For now I'm only using it for Ublock Origin so I'd like to sync the minimum needed only.

> webextensions.storage.sync.enabled was changed to true in 53

Right, thanks for the precision.

I think additional information may be worhwhile, when looking at [GH issues](https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue+firefox+sync) users are left out because "issues with Firefox Sync [are] out of uBlock's control".
I think the wiki should also mention `about:sync-log`.

**Comment by gwarser** [comment]
@dud225 about forcing synchronization - I quoted you.
