### ISSUE TITLE
support arguments in redirects

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uBlock-issues#511]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, when using `+js` rules, the injected script can receive arguments such as `{{{1}}}`. I'd like for `redirect` rules to be able to do the same with the redirect target. For example, you should be able to redirect to `remove-attr.js` and somehow pass an attribute name to be removed.

### A specific URL where the issue occurs

`https://www.reviewjournal.com/local/the-strip/woman-injured-after-falling-from-roller-coaster-on-las-vegas-strip-1626858/amp/`

### Steps to Reproduce

1. Load an AMP Access page with `cdn.ampproject.org/v0/amp-access` and `www.reviewjournal.com##+js(remove-attr.js, amp-access-hide)` as rules.
2. Load an AMP Access page with `||cdn.ampproject.org/v0/amp-access$script,redirect=remove-attr.js(amp-access-hide)` as a rule.

### Expected behavior:

Both case 1 and case 2 should prevent running AMP Access and show all elements. 

### Actual behavior:

Only case 1 prevents running AMP Access and showing all elements. Case 2 prevents running AMP Access, but the parameter isn't substituted into `remove-attr.js` (since this syntax doesn't exist yet, and I just made up what I think it should be), and thus, any elements marked as `amp-access-hide` continue to be hidden by pure CSS.

### Your environment

* uBlock Origin version: v1.18.16
* Browser Name and version: Firefox 66.0.2
* Operating System and version: Windows 10 v1809

**Comment by uBlock-user** [comment]
> you should be able to redirect to remove-attr.js and somehow pass an attribute name to be removed.

That's not the purpose of redirection, when you redirect, you redirect to a local extension resource, passing an attrrtibute name there would mean your injecting values when redirecting, if you want to injects values, do the injection, not the redirection, doesn't make sense logically.

**Comment by gorhill** [comment]
> Only case 1 prevents running AMP Access and showing all elements

If case 1 works fine, why invest should I invest time/effort/code maintenance burden for case 2?

**Comment by josephcsible** [comment]
> If case 1 works fine, why should I invest time/effort/code maintenance burden for case 2?

Because case 1 needs a rule per domain, whereas case 2 would cover every domain that uses AMP Access with just the one rule.

**Comment by gorhill** [comment]
There is already a scriptlet to be used for AMP:

    ||cdn.ampproject.org/v0.js$script,redirect=ampproject.org/v0.js

**Comment by josephcsible** [comment]
AMP Access is just for making paywalls. It's not the same as AMP.

**Comment by gorhill** [comment]
I am going to decline this for now, the required development efforts far outsize the benefits of the stated use case.
