### ISSUE TITLE
Element picker not working on support.mozilla.org

### ISSUE THREAD

**Issue by ExDomino** [uBlockOrigin/uBlock-issues#512]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The element picker doesn't work on Mozilla's support website.

### A specific URL where the issue occurs

On some rare websites, but the only one I have in head at this moment is the Mozilla's support website.
https://support.mozilla.org/
You can reproduce the bug on every page of this domain as well.

### Steps to Reproduce

1. Go to "https://support.mozilla.org/".
2. Left click to the "uBlock Origin" icon to open its menu.
3. Click to the element picker icon in order to hide, for example, the black sticky header.
3. See that you are not entered in picker mode. The element zapper is not working either.

### Expected behavior:

The element picker should works on this site as it works everywhere else.

### Actual behavior:

The element picker doesn't work at all on this site, nor the element zapper.

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Firefox 66.0.2 (64 bits)
* Operating System and version: Issue occuring on both Windows 7 and 10 (both in 64 bits)

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Privileged-Pages

**Comment by ExDomino** [comment]
Sorry if my bug report is "invalid" but an non effective button without any error message can be assimiled as a bug. Maybe you can gray out the button and say in the tooltip why you disabled it.

**Comment by gorhill** [comment]
uBO doesn't even know it is disabled, the browser bypasses uBO without telling the extension it does so.

**Comment by ExDomino** [comment]
A solution for that case would be trying to read the « extensions.webextensions.restrictedDomains » and gray out these buttons on these pages, provided that reading a config value is allowed for addons.

**Comment by gorhill** [comment]
> trying to read the « extensions.webextensions.restrictedDomains »

Not possible.

If you think you know how to solve this, a pull request is welcome, otherwise this is going to be an endless thread asking someone else to spend time/effort on your ideas of what to do.

**Comment by gorhill** [comment]
The browser is best placed to know when it bypasses extensions, so it makes sense to file an issue with at https://bugzilla.mozilla.org/home to ask that they provide a hint when extensions are bypassed, that would be one solution for all extensions, rather than asking each extensions to deal with this.

**Comment by uBlock-user** [comment]
> Sorry if my bug report is "invalid" but an non effective button without any error message can be assimiled as a bug. Maybe you can gray out the button and say in the tooltip why you disabled it.

This is by-design extension behaviour, so either the use the hack listed in [Privileged-Pages](https://github.com/gorhill/uBlock/wiki/Privileged-Pages) or file an issue on bugzilla.
