### ISSUE TITLE
Opera: req from www.google.com not show up in domains connected/logger

### ISSUE THREAD

**Issue by ChickenDuck** [uBlockOrigin/uBlock-issues#513]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

- ~~Frame~~ (update: img also affected) request from www.google.com not showing up in the domains connected list or logger, 
- Frame request from google.com, www.google.com.[CCTLD], www.example.com not affected
- Blocking and allowing ability in dynamic filtering rules for www.google.com not affected
- Happens in Opera, not in Chrome

### A specific URL where the issue occurs

Demo site: https://jsfiddle.net/a1mtkqz5/

### Actual behavior:

Screenshots
[Opera](https://user-images.githubusercontent.com/8293704/55668900-d69bed00-58a2-11e9-855f-9e3e7190d886.png)
[Logger](https://user-images.githubusercontent.com/8293704/55668906-e74c6300-58a2-11e9-95ff-5ac859da0a7b.png)

### Your environment

* uBlock Origin version: 1.18.10
* Browser Name and version: Opera Stable 58.0.3135.127
* Operating System and version: Windows 7

**Comment by gorhill** [comment]
I am not in a position to test Opera for the time being, can you verify whether this is related to this Opera behavior: <https://www.reddit.com/r/uBlockOrigin/comments/a147uc/psa_if_youre_using_opera_and_wondering_why_the/>?

**Comment by ChickenDuck** [comment]
Yes, checking "Allow access to search page results" solves this issue.

**Comment by ChickenDuck** [comment]
Just add a note here.
If you have issue with embedded Google services (eg. recaptcha, maps) which use the same domain (www.google.com), you may need to apply the mentioned solution.

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/319
