### ISSUE TITLE
New reddit night mode ads.

### ISSUE THREAD

**Issue by ogotbanned** [uBlockOrigin/uBlock-issues#515]
### Prerequisites

- [✓ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✓] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [✓ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [✓ ] uBlock Origin is the only extension
    - [✓ ] uBlock Origin with default lists/settings
    - [✓ ] using a new, unmodified browser profile
- [✓ ] I am running the latest version of uBlock Origin
- [✓ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Its been several days and the filters have not been updated to stop the so called "new" night mode ads.]

### A specific URL where the issue occurs
https://www.reddit.com/ 

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [login into any reddit account ]
2. [go to old reddit ]
3. [feast  your eyes on the cancer of the new "night mode ads"]

### Expected behavior:

see above

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: uBlock Origin v1.18.16
* Browser Name and version: tested on chrome/firefox for android and desktop. and fennc firefox
* Operating System and version: windows 10 android os 7.0 
![ad cancer 4216234 - Copy](https://user-images.githubusercontent.com/49357984/55679270-749cb100-58bd-11e9-98dc-311d394febde.png)

Reddit sauces:
https://old.reddit.com/r/uBlockOrigin/comments/b9wz8m/reddit_night_mode_infinite_scroll_redesign_bars/ 
http://archive.is/jU2X4

**Comment by gorhill** [comment]
Also, using uBO with another similar purposed blocker as seen in the screenshot is [not supported](https://twitter.com/gorhill/status/1033706103782170625) -- pick one or another, you're just totally wasting resources and proper filtering, and whatever perceived benefits you might feel is just placebo-based.
