### ISSUE TITLE
can't add some network filters via element picker, create button grayed out

### ISSUE THREAD

**Issue by AsocialSurvival** [uBlockOrigin/uBlock-issues#517]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element picker does not allow creating rules for blocking some network filters.

### A specific URL where the issue occurs
https://www.wikihow.com/Get-Used-to-Waking-up-Early-for-School

### Steps to Reproduce

1. go to website
2. use element picker mode
3. pick via element picker that image in sidebar, to the right of article, just below "more success stories" text at top right corner of page
4. choose network filter that appears as suggestion which mentions specific png file

### Expected behavior:

I am supposed to be able to crate filter by pressing Create

### Actual behavior:

button Create is grayed out aka disabled

### Your environment

* uBlock Origin version: 1.18.14
* Browser Name and version: Comodo IceDragon 64.0.4.15
* Operating System and version: Windows 7 x64 Enterprise

**Comment by gwarser** [comment]
No space after comma in `scrcset`. Regex does not match.
