### ISSUE TITLE
Several Major Browsers to Prevent Disabling of Click-Tracking 'Hyperlink Auditing'

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#518]
Something to address I guess:

https://news.slashdot.org/story/19/04/07/2338244/several-major-browsers-to-prevent-disabling-of-click-tracking-hyperlink-auditing

**Comment by uBlock-user** [comment]
Not several just Chromium devs removed the flag, in chrome://flags, still uBO's setting works.

**Comment by uBlock-user** [comment]
uBO relies on [hyperlinkauditingswitch](https://developer.chrome.com/extensions/privacy#property-websites) so nothing to address here until it gets removed.

**Comment by emanruse** [comment]
Good to know.
Hopefully there will always be a way to block it.

Thanks.
