### ISSUE TITLE
Incorrect value for applications.gecko.id in platform/webext/manifest.json

### ISSUE THREAD

**Issue by spwhitton** [uBlockOrigin/uBlock-issues#52]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[The value of applications.gecko.id in `platform/webext/manifest.json` is wrong.](https://bugs.debian.org/899990)

It is trivial to fix: change the e-mail address per the reporter of the Debian bug linked above.

### Steps to Reproduce

1. Install `webext-ublock-origin` on Debian testing/sid
2. Open Firefox
3. Visit about:addons

### Expected behavior:

ublock-origin in the list of extensions

### Actual behavior:

ublock-origin not in the list of extensions

### Your environment

* uBlock Origin version: 1.16.6
* Browser Name and version: Firefox 60.0.1
* Operating System and version: Debian testing/sid

**Comment by gorhill** [comment]
I was told that the version of uBO shipped in Debian shouldn't be updatable, hence why I picked a different extension id from the one in AMO:

> On 2018-04-10 06:24 AM, Michael Meskes wrote:
> The auto-update is fortunately the only issue that does not need
> solving because it is not supposed to be used in Debian at all.

Does that mean I need to not worry about the extension id because Firefox will be configured in such way that auto-updating extensions will be disabled?

**Comment by spwhitton** [comment]
Hrm.  I don't know whether or not autoupdating is enabled.  But I have never seen Firefox autoupdate my Debian uBlock origin package to a new version from addons.mozzila.org.  Possibly unpatched upstream Firefox does not automatically update system-installed addons.

I'm not sure how the autoupdating issue should be resolved because I am not sure what Firefox's precise behaviour is, but clearly the right solution to this bug, in the interim, is to change the id to one that Firefox accepts.  Thank you for your time!

**Comment by spwhitton** [comment]
Hello,

On Tue, Jun 05 2018, joe04 wrote:

>> Hrm. I don't know whether or not autoupdating is enabled.
>
> It's controlled by `extensions.update.autoUpdateDefault` which is true
> by default in official Mozilla builds.

True on Debian.

Thanks.

-- 
Sean Whitton
