### ISSUE TITLE
iframe with src="javascript:false;" defies filters

### ISSUE THREAD

**Issue by jchook** [uBlockOrigin/uBlock-issues#522]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

A specific iframe with `src="javascript:false;"` will not go away!

![unstoppable iframe](https://user-images.githubusercontent.com/193530/55963649-3b5b9c80-5c41-11e9-8282-5438c481e3e3.png)

I have tried many combinations of filters and posted a [support request](https://www.reddit.com/r/uBlockOrigin/comments/bbsfi8/iframe_defies_my_filters/) on Reddit with no luck.

Examples of filters I have tried:

```
my.freshbooks.com##iframe
my.freshbooks.com##^iframe
my.freshbooks.com##^#zendesk-widget-iframe
my.freshbooks.com###zendesk-widget-iframe
my.freshbooks.com##.zendesk-widget-iframe
my.freshbooks.com##iframe#zendesk-widget-iframe
my.freshbooks.com##^iframe#zendesk-widget-iframe
my.freshbooks.com##iframe#zendesk-widget-iframe[src="javascript:false;"]
my.freshbooks.com##^iframe#zendesk-widget-iframe[src="javascript:false;"]
javascript:false;##iframe
```

The log appears to claim that uBO blocks the iframe.

I also tried enabling "Block 3rd party frames" with no success.

### A specific URL where the issue occurs

https://my.freshbooks.com/#/login

### Steps to Reproduce

1. Visit [Freshbooks Login](https://my.freshbooks.com/#/login)
2. Add a filter(s) for the `iframe#zendesk-widget-iframe` element
3. Visit same page in a new window.
4. See that iframe still exists in both source html and DOM.

### Expected behavior:

I expect uBlockOrigin to remove the iframe from the HTML and from the DOM via various filters.

### Actual behavior:

The iframe remains in both the HTML and the DOM.

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Version 73.0.3683.75 (Official Build)
* Operating System and version: Ubuntu 18.04 (64-bit)

**Comment by gorhill** [comment]
> See that iframe still exists in both source html and DOM.

As expected. Cosmetic filters do not remove elements from the DOM, they are simply hidden using a CSS style `display: none !important;`.

**Comment by gorhill** [comment]
Works as expected, see documentation regarding cosmetic filtering, known as "element **hiding**" in ABP: <https://adblockplus.org/en/filters#elemhide>.

**Comment by jchook** [comment]
I have attempted [HTML filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters), e.g.:

```
my.freshbooks.com##^#zendesk-widget-iframe
```

Quoting from the documentation:

> These HTML filters will cause the elements matching the selectors to be removed from the streamed response data, such that the browser will never know of their existence once it parses the modified response data. This makes it a powerful tool in uBO's arsenal.

Did I use the html filter syntax incorrectly?

**Comment by jchook** [comment]
@gorhill Oh I see, it's only supported in Firefox?

Is there no way to remove the element in Chromium?

**Comment by gorhill** [comment]
There is no way to remove elements -- see <https://github.com/gorhill/uBlock/issues/2252>.

**Comment by uBlock-user** [comment]
> Is there no way to remove the element in Chromium?

You can use a scriptlet for element-removal.

**Comment by jchook** [comment]
@uBlock-user Thanks for the suggestion. I started looking into that but ended up using TamperMonkey to solve the problem:

```js
// ==UserScript==
// @name         Remove ZenDesk iframe
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Solves a problem with 1Password + Freshbooks
// @author       You
// @match        https://my.freshbooks.com/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    var iframe = document.querySelector('#zendesk-widget-iframe');
    if (iframe) {
        iframe.parentNode.removeChild(iframe);
    }

})();
```

**Comment by uBlock-user** [comment]
@jchook no need, just use https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L45

**Comment by jchook** [comment]
@uBlock-user kind of difficult to figure out how to apply this. 

With TM, it's "Just Javascript", takes 5 seconds, and boom it works first try.

With uBlock, I get [half-examples](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection) for an obscure DSL, I get your link to a .txt file containing several javascript chunks in a different repository... I have to read code to even understand [how to pass arguments](https://github.com/gorhill/uBlock/blob/c83b6776daa20d3d864be2e037d613ef37960caf/src/js/scriptlet-filtering.js#L280) to scriplets.

Then the docs state:

>  Keep in mind the resource library is completely under control of the uBO project, hence only javascript code vouched by uBO can be inserted into web pages, through the use of a valid resource token.

Yet `eremove.js` doesn't appear in the [controlled list of resources](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt), and I don't see any mention of loading from uBlock-user repository unless I do a lot of ["required reading"](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) and eventually load some file into an [advanced setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings#userresourceslocation) that "probably will behave in ways unexpected to you".

**Comment by uBlock-user** [comment]
> kind of difficult to figure out how to apply this. 

https://github.com/uBlock-user/uBO-Scriptlets#installation (Only to be done once)

Add filter in My Filters -- 

`my.freshbooks.com##+js(eremove.js, #zendesk-widget-iframe)`

**Comment by krystian3w** [comment]
`my.freshbooks.com###zendesk-widget-iframe:remove()`

or

`my.freshbooks.com#$?##zendesk-widget-iframe { remove: true }`
