### ISSUE TITLE
Inject Javascript to disable "ping" attribute on links

### ISSUE THREAD

**Issue by nsuchy** [uBlockOrigin/uBlock-issues#523]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Inject Javascript to iterate through the DOM and remove the ping attribute from all links.

### A specific URL where the issue occurs

Any search on Google will use the ping attribute as you click on links.

### Steps to Reproduce

1. Open browser inspector
2. Go to Google
3. Make a search
4. Click a link
5. Watch the magical pings
0. You may need to use Chrome Canary

### Expected behavior:

The a ping attribute is blocked

### Actual behavior:

The hidden setting flag is disabled and the a ping attribute works as normal. Context: https://www.theregister.co.uk/2019/04/06/apple_safari_changes/

### Your environment

* uBlock Origin version: latest
* Browser Name and version: Apple Safari 12.1 and Google Chrome Canary
* Operating System and version: macOS Sierra

**Comment by nsuchy** [comment]
Just one note, I'm aware Safari's uBlock Origin is a community fork, this also affects the upcoming version of Google Chrome which is why I'm bringing it up in the main repo rather than the Safari specific one (which will have to backport the commit with this feature)

**Comment by gorhill** [comment]
Hyperlink auditing is disabled by default in uBO, see <https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditing>.
