### ISSUE TITLE
3rd party Filter lists customization

### ISSUE THREAD

**Issue by 360up** [uBlockOrigin/uBlock-issues#525]
I'm looking for a way to modify 3rd party filter lists or load a customized version of it locally. Unfortunately Mozillas security model does not allow direct file system access and thus no custom list can be included with `file:///`. Neither was I able to add a local custom list with the `!#include` directive.
Currently the only way to do so would be copying the lists into "My filters", but this would of course clog up My filters.

Solution:
1) make the Asset Viewer r/w (of course you should back up the changes made before updating lists)
2) allow multiple "My filters" dynamic filter lists

**Comment by uBlock-user** [comment]
> I'm looking for a way to modify 3rd party filter lists

They can't be modified, they're 3rd party for a reason. They are always read-only.
