### ISSUE TITLE
"My filters" are ignored when there is a 3rd party "Filter lists" exception rule

### ISSUE THREAD

**Issue by 360up** [uBlockOrigin/uBlock-issues#526]
If you e.g. have a filter `||example.org/$script` in My filters and there is an exception filter in any of the active filter lists e.g. `@@||example.org/example.js$script` this exception takes precedence over your own filter.
Yes you could add the `$important` flag to your filter, but then you are not able to write own exceptions for that filter anymore.

Regardless, exception rules in 3rd party filter lists should be limited to their very own list only and not take precedence over any filter specified outside that list.

Alternatively add a filter lists setting: "Ignore 3rd party Exception Filters"

**Comment by okiehsch** [comment]
> Regardless, exception rules in 3rd party filter lists should be limited to their very own list only and not take precedence over any filter specified outside that list.

How would you then deal with site breakage caused by a 3rd party filter or with bait requests that if you don't allow them will result in the site beeing blocked if one uses an adblocker.

**Comment by uBlock-user** [comment]
> If you e.g. have a filter ||example.org/$script in My filters and there is an exception filter in any of the active filter lists e.g. @@||example.org/example.js$script this exception takes precedence over your own filter.

Use `@@||example.org/example.js$script,badfilter` to disable that exception filter.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3353

**Comment by gorhill** [comment]
Related: https://issues.adblockplus.org/ticket/7248

**Comment by uBlock-user** [comment]
@gorhill would you be implementing that priority feature in uBO ?

**Comment by gorhill** [comment]
As pointed out in the ABP issue, it is something I would consider for the sake of filter list maintainers. I could possibly provide an incomplete version (network filters only at first) of this behind a hidden settings, I need to think more about this.

**Comment by gwarser** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/1520

**Comment by gorhill** [comment]
> I could possibly provide an incomplete version

Since this was brought up, I will say I had a change of mind.

User filters should never behave differently than if they were 3rd-party filters, otherwise this will make the work of filter list maintainers more difficult since the filters they craft locally may end up behaving differently once moved to a filter lists. This also applies for users who decide to move their custom filters into a custom list.

So in the end, it's not a good idea to have user filters behave differently than 3rd-party filters.

**Comment by uBlock-user** [comment]
Besides, users already have options such as `$important/$badfilter` to deal with rogue filters.
