### ISSUE TITLE
Integrate mechanism protection Ublock Origin on blocks by sites?

### ISSUE THREAD

**Issue by seba2282** [uBlockOrigin/uBlock-issues#527]
System Windows/Android
Browser Firefox/others where can install ubo extension. 

It is possible Integrate mechanism protection Ublock Origin on blocks by sites? 
I asked bc must sites detect ubo and blocks media. Only turn off help. Example player.pl please look. Sometimes help Defuser Penguin but I don't trust to much forks projects. Please look on my suggest. 
Best Regards
seba2282

**Comment by gorhill** [comment]
I don't understand your issue. I will close as _invalid_ filter issue (not to be handled here). Respect what is asked from you in the template if you re-open a better detailed issue related to this one.
