### ISSUE TITLE
Coalesce common plain filters in a bucket into a single trie

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#528]
This issue is opened somewhat a posteriori, as work for this has already been committed in <https://github.com/gorhill/uBlock/commit/c229003d31e04e96c1f3c4daabd5f5ee9722e5d0> (the new [`STrieContainer` code](https://github.com/gorhill/uBlock/blob/a594b3f3d19a40c1d4244c013101c456a801e10f/src/js/strie.js) was just a matter of reusing [existing `HNTrieContainer` code](https://github.com/gorhill/uBlock/blob/a594b3f3d19a40c1d4244c013101c456a801e10f/src/js/hntrie.js) and modifying it to deal with plain string rather than hostname, i.e. simplifying really).

However I want to document and further investigate pushing the trie usage farther, hence this issue.

### Done

In the static network filtering engine, filter buckets are used to hold collections of filters which share the same token. Tokens are used to store/lookup filters or collections of filters so as to minimize the number of filters visited each time a network request needs to be matched against the content of the filter lists.

With <https://github.com/gorhill/uBlock/commit/a594b3f3d19a40c1d4244c013101c456a801e10f>, I introduced a method to help investigate the content of all filter buckets. To do so, call the method from uBO's dev console as follow:

    µBlock.staticNetFilteringEngine.bucketHistogram()

This will output a list of all filter buckets in the static network filtering engine, from largest to smallest. Before the work on trie usage was committed, `bucketHistogram()` would show the content of the largest buckets as follow (top ten):

    bits: 0, token: "ad", 926 entries
    bits: 0, token: "ads", 636 entries
    bits: 65, token: "phncdn", 253 entries
    bits: 0, token: "analytic", 174 entries
    bits: 0, token: "tracking", 155 entries
    bits: 72, token: "http", 146 entries
    bits: 72, token: "https", 139 entries
    bits: 88, token: "http", 122 entries
    bits: 0, token: "adv", 121 entries
    bits: 88, token: "https", 118 entries
    bits: 0, token: "advertis", 102 entries

As can be seen the `ad` and `ads` bucket are quite large, and anytime uBO encounter a URL with the token `ad` or `ads`, it must potentially visit all or a large number of the entries in these buckets to find out whether there is a matching filter.

Oftentimes, a majority of filters in these buckets are plain filters which can be coalesced into a single trie entity, and a _single_ scan of the trie will tell whether any of the filter has been matched.

After the work to coalesce _trieable_ filters from the same bucket into a single trie was committed, the buckets looked like this:

    bits: 0, token: "ad", 57 entries + 2 tries coalescing 869 strings
    bits: 0, token: "ads", 78 entries + 1 trie coalescing 558 strings
    bits: 65, token: "phncdn", 22 entries + 1 trie coalescing 231 strings
    bits: 0, token: "analytic", 35 entries + 1 trie coalescing 139 strings
    bits: 0, token: "tracking", 17 entries + 1 trie coalescing 138 strings
    bits: 72, token: "http", 146 entries
    bits: 72, token: "https", 139 entries
    bits: 88, token: "http", 122 entries
    bits: 0, token: "adv", 26 entries + 1 trie coalescing 95 strings
    bits: 88, token: "https", 118 entries
    bits: 0, token: "advertis", 18 entries + 1 trie coalescing 84 strings

Sometimes, buckets end up with 0 entries and 1 trie as all the filters in the bucket can be coalesced into a single trie, for example:

    bits: 0, token: "adserver", 0 entries + 1 trie coalescing 29 strings

The result as per `µBlock.staticNetFilteringEngine.benchmark()` method was a measurable performance and memory usage gain. I do not expect the performance gain to be noticeable from a user's point of view, although the memory efficiency can be noticed, especially when uBO loads from a selfie (typically well under 40 MB at launch with default settings/lists).

### To do

Investigate pushing the coalecing-into-tries idea farther in the context of filter buckets. There are still many entries left in some filter buckets which can theoretically be coalesced into a trie. 

However this would require a "bidi" trie, i.e. a trie which can scan left and right of the token position in the URL -- current implementation scans just to the right.

The ability to scan both directions would open the door to also coalesce FitlerPlain-based filters into the same trie currently used by the FilterPlainPrefix1-based filters (a specialized version of FitlerPlain).

For examples, this would further reduce the number of entries to scan to 19 entries in the `ad` bucket (from 57 entries with current trie, or 926 entries with no trie), and to just 8 entries in the `ads` bucket (from 78 entries with current trie, or 636 entries with no trie).

**Comment by mapx-** [comment]
@mjethani

> There are a lot of filter pairs in Easylist of the form:
> 
> ```
> |http://$script,subdocument,third-party,domain=onhax.me
> |https://$script,subdocument,third-party,domain=onhax.me
> ```
> I don't know why they do not simply use:
> 
> `*$script,subdocument,third-party,domain=onhax.me`
> All URLs essentially will match one or the other form, might as well merge them together, there is no gain to split them in two lines.

**Comment by krystian3w** [comment]
Maybe to no block ftp in Firefox lower than  Firefox 60 

https://www.ghacks.net/2018/02/20/firefox-60-with-new-preference-to-disable-ftp/

**Comment by uBlock-user** [comment]
@gorhill A filter like `@@||$elemhide,domain=animehub.ac|myanimelist.net|fmovies.to|screenrant.com|kimcartoon.to|ghacks.net|animenewsnetwork.com` is now shown as `@@*$generichide` in the logger, so I'm no longer told about the domain part, how will I be able to badfilter it on a domain from the list say for example, `screenrant.com` now ?

**Comment by gorhill** [comment]
> it will be nice if the logger shows the complete filter

Yes my bad, it's a regression, I overlooked that case. It's an easy fix, I will post an update asap.

**Comment by uBlock-user** [comment]
Shouldn't a filter like `@@/advert3.js|$first-party,domain=oload.life|oload.services|oladblock.me|oladblock.xyz|oladblock.services|oload.space|oload.live|openload.co|openload.pw|oload.fun|oload.icu|oload.cloud|oload.download|oload.stream|oload.info|oload.club` appear as `@@/advert3.js$first-party,domain=openload.co` on `https://openload.co/embed/RrbAKOiRGdY/?autostart=true` in the logger ?

**Comment by gorhill** [comment]
No, there was no change for such filters.

**Comment by uBlock-user** [comment]
But it does have domain directive in it, so how come it doesn't ?

**Comment by gorhill** [comment]
Where did I say these filters would be reported differently?

**Comment by uBlock-user** [comment]
Nevermind, I apparently misunderstood that it will do it for any filter if domain directive is present in the filter.

**Comment by gorhill** [comment]
With the above commit, the number of discrete filters in the array went from 57 to 19 for the "ad" bucket, and 77 to 7 in the "ads" bucket (the two largest buckets).

**Comment by mapx-** [comment]
> @mjethani
> 
> > There are a lot of filter pairs in Easylist of the form:
> > ```
> > |http://$script,subdocument,third-party,domain=onhax.me
> > |https://$script,subdocument,third-party,domain=onhax.me
> > ```
> > 
> > 
> > I don't know why they do not simply use:
> > `*$script,subdocument,third-party,domain=onhax.me`
> > All URLs essentially will match one or the other form, might as well merge them together, there is no gain to split them in two lines.
> 
> Is there some special reason ABP needs such double filters ?
> 
> @monzta @ryanbr

@mjethani @monzta @ryanbr

Could you please reply ?

**Comment by mapx-** [comment]
@hfiguiere @smed79

**Comment by gorhill** [comment]
@mapx In the end, it does not really matter anymore, I [added code in 1.19.0](https://github.com/gorhill/uBlock/commit/3f3a1543ea7fa51d700157a7f6bf0da08dd7a32b)<sup>[1]</sup> to deal with these efficiently, so they are no longer a concern to me.

***

<sub>[1] Incidentally, sleazy uBlock has a [commit with a resembling commit message](https://github.com/uBlock-LLC/uBlock/commit/847bab7e421656043010ccb401a830def69b775b).</sub>

**Comment by mjethani** [comment]
> Could you please reply ?

I don't believe there is any specific reason that Adblock Plus should require these, but if filter list authors are trying to distinguish between HTTP(S) and other protocols, I can understand. Now we could address this with a regular expression filter (i.e. `/https?:\/\//$script,subdocument,third-party,domain=onhax.me`). My point is that there should be ways around this.

Historically it has been that "regular expression filters are inefficient" because Adblock Plus developers say so. This is now rubbish. Please let us know what works for you, we will optimize Adblock Plus for it (as long as I am around).
