### ISSUE TITLE
script:inject not effective for some websites

### ISSUE THREAD

**Issue by haneestea** [uBlockOrigin/uBlock-issues#53]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

script:inject not effective for some websites

### A specific URL where the issue occurs

`aktualne.cz`, `centrum.cz`, `novinky.cz`

### Steps to Reproduce

1. Add these rules to uBlock 
```
aktualne.cz##script:inject(abort-on-property-read.js, SASIA)
centrum.cz##script:inject(abort-on-property-read.js, SASIA)
novinky.cz##script:inject(abort-on-property-read.js, sssp)
```
2. Visit these websites

### Expected behavior:

Property SASIA/sssp should not be readable, ads will not display.

### Actual behavior:

Property SASIA/sssp is readable most of the times, blocking does not work. Website is showing ads.

### Your environment

* uBlock Origin version: v1.16.8 (also tested with latest beta)
* Browser Name and version: Chromium 67.0.3396.62, Firefox 60.0.1
* Operating System and version: Linux (also tested on Windows)

**Comment by haneestea** [comment]
Well I dont think so. You can verify in console that properties are still readable. It has nothing to do with filterlist.

**Comment by gorhill** [comment]
Crucial information missing: where is the variable `SASIA` being created and read from?

**Comment by uBlock-user** [comment]
SASIA is read from - `https://www.aktualne.cz/VKStyXONxh9jnOnUSd4503R_g9zOly5l/cm33wARY-e-wJAwdFs-aAm6GgVK?v=70735` and created at the home page or at any article.

**Comment by gorhill** [comment]
Probably just the known race condition issue: sometimes when the site loads fast from cached resources, uBO loses the race. Add to this the page seems to generate a different source once in a while: somtimes there is a inline script tag at the top of the document, sometimes not.

I consider this a filter issue, it's a reality to take into account when creating filters.

**Comment by uBlock-user** [comment]
> Probably just the known race condition issue

That's exactly what I thought after loading some webpages.

**Comment by okiehsch** [comment]
@haneestea For issues involving czech sites it is best to open filter issue at https://github.com/tomasko126/easylistczechandslovak

**Comment by gorhill** [comment]
The purpose of the inline script tag at the top seems to be to deal with uBO specifically. A quick glance at it and it seems it tries to detect when uBO injects it's scriplets.

**Comment by uBlock-user** [comment]
They do have anti adblock detection inline script at the bottom too.

**Comment by okiehsch** [comment]
Hm, I never get such an inline script on my end.

<Details>
![unbenannt](https://user-images.githubusercontent.com/16838044/40865469-aac2eb9a-65f8-11e8-8b84-f3ab4fd3004e.PNG)

**Comment by uBlock-user** [comment]
Probably because of GDPR ?? Sources do change on my end inbetween loads.

**Comment by gorhill** [comment]
I am going to make a small change given what I have observed on `aktualne.cz`. Now, the race condition issue can't be avoided. However, I see that the code at the top of the HTML document specifically look for uBO scriptlet injection, examples:

    return b("var magic = String.fromCharCode", "var"), e.apply(n, arguments)
    ...
    return b("needle1 = new RegExp(needle1);", "event"), e.apply(this, arguments)

    These are javascript from scriptlets. I am not sure what happens when scriptlets injection is detected (this kind of investigation is time consuming and browser dev tools often breaks down with such case of js from blob, etc.) But I will make uBO clear the scriptlet text right after scriptlet execution, such that the code I see shouldn't be able to detect scriptlet injection.

For `aktualne.cz`, it does seem to help -- I can't reproduce the ads when clearing the text in the script tag. I still consider this a filter issue, there is no guarantee that whatever fall back code they were executing as a result of the detection won't be executed unconditionally in the future.

**Comment by okiehsch** [comment]
Ok, using a proxy I can reproduce, I doubt that it has anything to with GDPR, probably some glitch with my current IP, who knows.
Enabling the czech list gets rid of most of the ads on my end.
If I add `aktualne.cz###kulublu-mulu` the only thing left is a non-clickable background pic.

![unbenannt](https://user-images.githubusercontent.com/16838044/40865985-9de4b95a-65fb-11e8-964f-782313a5f65a.JPG)

**Comment by jspenguin2017** [comment]
> I am not sure what happens when scriptlets injection is detected

It simply throws an error to abort the scriptlet.

**Comment by lunboks** [comment]
I have an idea how to to prevent this sort of tomfoolery at the uBO level. You could wrap the scriptlets in a closed shadow DOM before injecting - this makes them completely inaccessible to page code.

- `document.currentScript` won't point to it
- MutationObservers won't be able to see it
- beforescriptexecute won't fire

Looks like I can't send a PR, but here's what I had in mind.

```javascript
vAPI.injectScriptlet = function(doc, text) {
    if ( !doc ) { return; }
    let script, host, shadow;
    try {
        script = doc.createElement('script');
        script.appendChild(doc.createTextNode(text));

        // Wrap script in a closed shadow DOM to avoid interference
        if ( Element.prototype.attachShadow ) {
            host = doc.createElement('span');
            host.hidden = true;

            shadow = host.attachShadow({ mode: 'closed' });
            shadow.appendChild(script);
        } else {
            // Shadow DOM unsupported - insert script directly
            host = script;
        }
        (doc.head || doc.documentElement).appendChild(host);
    } catch (ex) {
    }
    if ( host ) {
        if ( host.parentNode ) {
            host.parentNode.removeChild(host);
        }
        script.textContent = '';
    }
};
```

**Comment by gwarser** [comment]
I think `idnes.cz` also uses this script https://github.com/uBlockOrigin/uAssets/issues/462

**Comment by jspenguin2017** [comment]
@lunboks That does circumvent the specific trick this website is using, but if the website watches for mutation and inspects shadow root, the script injection can still be known. 

There are so many other ways to block scriptlets, they can just rename `RegExp` to `MyRegExp` and the scriptlets will crash.

**Comment by jspenguin2017** [comment]
@gwarser Probably not, if I understood right, that API isn't meant to be called often. I think we'll have performance issue if we use that to register scriptlets.

**Comment by zzanek** [comment]
who has a scriptlet injector console
