### ISSUE TITLE
Firefox Refresh On Startup Automatically

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [uBlockOrigin/uBlock-issues#530]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Whenever I open firefox , Firefox Automatically reloads the current tab,I don't know what is going on ,first I thought it was due to cookie autodelete extension but after removing it I realised uBlock Origin is the real problem.
After disabling ublock origin the issue goes away
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Open Firefox
2. [Second Step] Install ublock 
3. [and so on...] Restart firefox

### Expected behavior:

[What you expected to happen]
Nothing
### Actual behavior:
Firefox Reload
[What actually happened]

### Your environment

* uBlock Origin version:1.18.16
* Browser Name and version:Mozilla Firefox v66.0.3
* Operating System and version:Windows 10 version 1803

**Comment by uBlock-user** [comment]
Do you have Restore Previous session activated along with `suspendTabsUntilready` set to `yes` ?

**Comment by gwarser** [comment]
Missing URL, and what "nothing" means in Expected?

UBO sometimes disables caching for main-document (html and csp filters) - this may be the cause.

**Comment by gorhill** [comment]
No repro steps for us to investigate anything, this is not going to go anywhere.

**Comment by Ashutosh-Kukreti** [comment]
> 
> 
> Do you have Restore Previous session activated along with `suspendTabsUntilready` set to `yes` ?

It is set to unset

**Comment by Ashutosh-Kukreti** [comment]
> 
> 
> Missing URL, and what "nothing" means in Expected?
> 
> UBO sometimes disables caching for main-document (html and csp filters) - this may be the cause.

By Nothing I meant that it should not reload or refresh firefox on startup

How can I fix it?

**Comment by Ashutosh-Kukreti** [comment]
I cleaned install firefox and removed windscribe vpn from my pc ,which fixed the issue.
