### ISSUE TITLE
Please rename AdGuard Spyware filter to AdGuard Tracking Protection filter.

### ISSUE THREAD

**Issue by lancelot-moon** [uBlockOrigin/uBlock-issues#531]
https://kb.adguard.com/en/general/adguard-ad-filters

Please rename AdGuard Spyware filter to AdGuard Tracking Protection filter.
https://github.com/AdguardTeam/FiltersRegistry/issues/159

**Comment by lancelot-moon** [comment]
@gorhill 
Why did you delete "filter" from filters' names?

**Comment by mapx-** [comment]
Maybe because is confusing => a filter is part of a list and not the list itself

**Comment by lancelot-moon** [comment]
They're named as uBlock filters in the filtering rules lists.
Well, it's up to you...
