### ISSUE TITLE
Ublock Detect by player.pl

### ISSUE THREAD

**Issue by seba2282** [uBlockOrigin/uBlock-issues#532]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

Ublock Origin verion: newest
Browser Name and Version: Firefox newest
Operting System and version: Windows 7 SP1 x64

My problem is detecting Ublock Origin detection by player.pl 

Example link to video wher Ublock Origin is detected: 
https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114

Screenshoot: 
![player](https://user-images.githubusercontent.com/16944478/56271857-b3bad580-60f9-11e9-938c-52258194de0f.png)

Options in Ublock Origin, what I turned are in screenshoots:
![ublockoriginopcje](https://user-images.githubusercontent.com/16944478/56271905-d3ea9480-60f9-11e9-827c-68404622edd8.png)
![ublockoriginopcje1](https://user-images.githubusercontent.com/16944478/56271913-da790c00-60f9-11e9-8a09-63887fa71a86.png)
![ublockoriginopcje2](https://user-images.githubusercontent.com/16944478/56271921-dfd65680-60f9-11e9-914b-300e4e08a9c2.png)
![ublockoriginopcje3](https://user-images.githubusercontent.com/16944478/56271930-e369dd80-60f9-11e9-9513-32ed23a67447.png)

Sorry if I bad write that issue but is easier for me show details in screenshoots.

Can I please help and future fix? Because not only on player.pl Ublock Origin is detected. Is more sites. 

Best Regards

**Comment by uBlock-user** [comment]
Post this at https://github.com/uBlockOrigin/uAssets/issues
