### ISSUE TITLE
Failed to load resource after factory reset

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#534]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Steps to Reproduce

1. Click `Reset to default settings...`

### Actual behavior:
![ubo-console](https://user-images.githubusercontent.com/8005688/56465379-d18f7f80-6404-11e9-9cfa-943f3c10a5b8.png)

### Your environment

* uBlock Origin version: v1.18.17b7
* Browser Name and version: Chromium 73.0.3683.103 (64-bit) 
* Operating System and version: Windows 10 v1607 x64

**Comment by uBlock-user** [comment]
Specific to Chromium, not seeing this in Firefox's extension console.

**Comment by gwarser** [comment]
`*.txt` files are requested, but these files don't have extension at all.

**Comment by uBlock-user** [comment]
Yes, [here](https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L295) and [here](https://github.com/gorhill/uBlock/blob/master/assets/assets.json#L189) in assets.json, though this only affects Chromium.

**Comment by gorhill** [comment]
uBO tries to fetch the extension version because MS Edge was not able to fetch when a local resource had no extension; these no-extension files had to be renamed in MS Edge version to add `.txt` as extension.

**Comment by uBlock-user** [comment]
I still see _File Not Found_ in 1.18.17b9 is that to be expected on Chromium as per your above comment ?

![](https://i.gyazo.com/b6620017041829f450d67a73fb962657.png)

**Comment by gorhill** [comment]
Yes, expected, this was always like this since MS Edge issue was fixed long ago.
