### ISSUE TITLE
Regression in strict blocking in dev

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#536]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`https://martinfowler.com/articles/asyncJS.html` is strict blocked by `/asyncjs.$domain=~asyncjs.com`

Possible regression after https://github.com/gorhill/uBlock/commit/fa83744b589e3328f70ba8a24662be1725b17221 
Bisection showed this, but I have problems trusting it lately.

### A specific URL where the issue occurs

https://martinfowler.com/articles/asyncJS.html

### Steps to Reproduce

1. open link

### Expected behavior:

page opens

### Actual behavior:
strict block

### Your environment

* uBlock Origin version: 1.18.17b7
* Browser Name and version: Nighlty
* Operating System and version: Linux

**Comment by gorhill** [comment]
Oops, bad cut & paste.
