### ISSUE TITLE
UI: "Advanced" (point & click) unusable when over-riding colours in FF.

### ISSUE THREAD

**Issue by happyublockoriginuser** [uBlockOrigin/uBlock-issues#537]
**Issue.**

_Affects all versions of Firefox on all OS._

Firefox allows users to "always" over-ride bg/fg colours with user-specified defaults.

`chrome://browser/content/preferences/colors.xul`

uBlockOrigin's "I am an advanced user" interface relies _heavily_ on (seemingly bg) colour: it is impossible for the user to tell in the UI what is being blocked if FF is over-riding colours.

**Suggestion.**

There are a number of ways to fix this. I strongly advocate for one that doesn't use colour, but good-old-fashioned symbols: e.g. Y/N or +/- or something.

~~If getting a character button to change is too hard, you could keep the buttons, have them not change, and add another box that does change, showing which button is in effect.~~

**Edit:** Scratch that. Make it a traditional table: add a header/label row up top (e.g. [Y|O|N]) and use an asterisk * to mark which columns apply to each host.

**Winging.**

The "color-blind friendly" option is a gross misnomer and provides false-hope.

This is a very annoying bug as I neither want to be over-whelmed with hard-to-read crud nor do I want to stop using uBlockOrigin's nice pointy-clicky interface.

This is a cruddy way of reporting bugs.

**Comment by uBlock-user** [comment]
> Firefox allows users to "always" over-ride bg/fg colours with user-specified defaults.

uBO is not here to fix every side-effect caused by settings which are not meant to be over-ridden or change in the first place, also fill the template instead of removing and posting a wall of paragraph like this when reporting a uBO bug.

**Comment by happyublockoriginuser** [comment]
"Settings which are not meant to be over-ridden"
You seem to misunderstand: these are not settings being over-ridden: these are settings that are over-riding shitty web-design. There is something very wrong with your attitude if you think users shouldn't use the settings FF provides.  What next? Blocking cookies / not sending referrers is "over-riding settings?"

Sorry I didn't fill out your form that was completely irrelevant to the bug I was reporting.

This is very bad support for the vision impaired.

**Comment by uBlock-user** [comment]
Duplicate of gorhill/uBlock#1850.
