### ISSUE TITLE
"Advanced" (point & click) unusable when over-riding colours in FF

### ISSUE THREAD

**Issue by happyublockoriginuser** [uBlockOrigin/uBlock-issues#538]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This is the same as the more straight-forward no-messin' #537 

*Affects all version of UO on all version of FF on all OS everywhere.*

Firefox allows users to "always" over-ride bg/fg colours with user-specified defaults.

`chrome://browser/content/preferences/colors.xul`

uBlockOrigin's "I am an advanced user" interface relies _heavily_ on (seemingly bg) colour: it is impossible for the user to tell in the UI what is being blocked if FF is over-riding colours.

### A specific URL where the issue occurs

Whatever is the URL for the uBlockOrigin interface.

### Steps to Reproduce

1. Ensure you have selected "I am an advanced user".
2. Navigate to `chrome://browser/content/preferences/colors.xul`
3. Select "always" in the drop-down-menu "Override the colors..."
4. Select the "OK" button.
5. Navigate to a webpage.
6. Open the UO interface (by clicking on the icon).

### Expected behavior:

Should be able to set text and background to black-on-white / white-on-black for *web-pages* w/o any change in uBlock.

### Actual behavior:

uBlock interface was affected just like any other page: it was only in two colours and I couldn't see what was being blocked, only the hostnames. Totally unusable.

**Suggestion.**

There are a number of ways to fix this. I strongly advocate for one that doesn't use colour, but good-old-fashioned symbols: e.g. Y/N or +/- or something.

~~If getting a character button to change is too hard, you could keep the buttons, have them not change, and add another box that does change, showing which button is in effect.~~

**Edit:** Scratch that. Make it a traditional table: add a header/label row up top (e.g. [Y|O|N]) and use an asterisk * to mark which columns apply to each host.\

E.g.

Host|A|X|B
-------|---|---|---
social.media||S|G

would block social.media globally excepting this site.

**Winging.**

The "color-blind friendly" option is a gross misnomer and provides false-hope.

This is a very annoying bug as I neither want to be over-whelmed with hard-to-read crud nor do I want to stop using uBlockOrigin's nice pointy-clicky interface.

This is a cruddy way of reporting bugs.

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Firefox 62.0.3 (64-bit) (Mozilla/5.0 (X11; OpenBSD amd64; rv:62.0) Gecko/20100101 Firefox/62.0)
* Operating System and version: OpenBSD 6.4 (amd64)

**Comment by uBlock-user** [comment]
> Should be able to set text and background to black-on-white / white-on-black for web-pages w/o any change in uBlock.

Firefox bug or a by-design behaviour in Firefox where these changes are also affecting WebExtensions.

**Comment by happyublockoriginuser** [comment]
It is a bug in UO: changing a browser setting in about:preferences renders a large part of UO unusable due to a UO design consideration. The fault lies entirely with UO.

**Comment by uBlock-user** [comment]
> The fault lies entirely with UO.

and how did you come to that conclusion ?

**Comment by happyublockoriginuser** [comment]
UO is an extension to FF, not the other way round. If UO breaks when the user changes a setting in FF, then it is not properly integrated with FF: hence the fault lies with UO. FF can do no wrong :P

**Comment by happyublockoriginuser** [comment]
You can't expect FF to be designed around UO: you would rather expect UO to be designed around FF though.

**Comment by happyublockoriginuser** [comment]
Consider the null programme: "Well, it is FF fault for not supporting the null programme to block ads for me."  No: it is the programmers fault for not programming.

**Comment by uBlock-user** [comment]
I installed Adblock Plus, NoScript and uMatrix and it happens there too, so it's not a uBO bug, like I said before. All extensions are affected. You can test this by yourself.

**Comment by happyublockoriginuser** [comment]
No! This only proves it not *specific* to uBlockOrigin. You have not shown uBlockOrigin is w/o blame: you have only shown all these other extensions *are similarly buggy.*

**Comment by gorhill** [comment]
Declined.

Please do not use the manifesto as a wildcard argument for everything, and certainly not as an argument for me to work endlessly to fulfill everybody demands. Surely you understood the argument is meant to emphasize to block/not block is your choice.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/gorhill/uBlock/issues/1850>.

**Comment by happyublockoriginuser** [comment]
"Not to the point of making web pages unusable -- rather the opposite. And when a web page is broken to the point of being unusable due to false positives, it's the job of filter lists maintainers to fix it, not the site owners."

For some, people, changing the colour is making it usable.

This is ludicrous. I always though mublock was a bit rubbishy; now I'm binning it for sure (on my own system, at least).

**Comment by happyublockoriginuser** [comment]
"The real flaw here is to assume that the only purpose of background-color is to be a canvas for text -- this oversimplification of background-color purpose is bound to create issues in a lot more places than just uBO. I am going to decline adding ugly hacks to uBO's CSS just for the sake of fixing issues with those overriding uBO's CSS"

Using colour as your main and only interface is an ugly hack. If a user can't read ugly coloured crap; they can't read it any more on some extension than they can on a web-page.

**Comment by gorhill** [comment]
Feel free to fork or find something else that works better for you.

**Comment by uBlock-user** [comment]
Making such irrelevant, invalid arguments and acting in a childish manner since you're not getting "your way" is sure fire way to get your thread locked and closed, do yourself a favour and don't bother opening issues here anymore.

**Comment by gorhill** [comment]
That setting breaks many things in uBO (for example selection in all CodeMirror fields) and outside of uBO (other extensions, sites). I consider I would be greatly wasting the limited time I dedicate for this project for a setting that is at worst an extremely marginal issue -- as per millions of users over many years have shown -- best addressed by the efforts of whoever makes the choice to use that setting.

**Comment by uBlock-user** [comment]
https://support.mozilla.org/en-US/questions/1193062

The Firefox support forum community themselves acknowledge that the colour setting to be relict of the past and advice to not to use that, instead make use of user style dedicated extensions like Stylus/TM/VM/GM etc...
