### ISSUE TITLE
logger hotkey not focusing tab its launched from

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#54]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Until https://github.com/gorhill/uBlock/commit/c6cab029996249a38b109517190cb154f0d6b32d the logger would be focused on the tab it was launched from when using the hotkey. Now the changes to `logger-ui.js` cause it to not have tab focus, but open as "All" instead.

I tried changing [this line](https://github.com/gorhill/uBlock/blob/master/src/js/commands.js#L46) to be the same `#tab_active` as [the commit](https://github.com/gorhill/uBlock/commit/c6cab029996249a38b109517190cb154f0d6b32d#diff-12862b0ce0e68078c4b592cfaf7b69d1). The hotkey then focuses the tab but with a generic "Current tab" label. Thus the refresh button doesn't work. So it's still a problem.

This is on Firefox 60 with 1.16.9b4. (The hotkey is not defined in the uBO manifest, so I use my own unsigned version to define it.)

I don't have Chrome setup to test with it, but presumably it's the same issue there (where the logger hotkey can be defined normally in the browser).

### Workaround
I just kept the `logger-ui.js` from 1.16.6 and the hotkey works fine.

**Comment by uBlock-user** [comment]
I can reproduce it on Chromium. Have atleast one tab opened and open  the logger via a hotkey assigned to the browser for uBO. The logger opens in 'All' instead of current tab.

**Comment by joey04** [comment]
@gorhill - thanks for making the fix. I just verified that 1.16.9b5 does restore the proper hotkey behavior.

However, there are now 2 drawbacks to the logger changes of  https://github.com/gorhill/uBlock/commit/c6cab029996249a38b109517190cb154f0d6b32d

1) There's now an extra "Current tab / " label pre-pended to the drop-down titlebar when its focused with the hotkey. I prefer the former look of just the tab title.

2) Pressing the hotkey while on the logger tab no longer changes the view to "All". Now it's just a generic "Current tab" label with only BTS items. 

So I'll be sticking with `logger-ui.js` from 1.16.6.

**Comment by gorhill** [comment]
The behavior you describe in point 2. was entirely accidental, I don't remember ever making that choice. Given that it is trivial, I restored this accidental behavior in <https://github.com/gorhill/uBlock/commit/b838e22024bb>.

**Comment by joey04** [comment]
That's good, thanks for restoring that.

As for my other point, it was easy to change `updateCurrentTabTitle` to remove the prepended i18n message. (But now the current tab is a duplicate entry in the drop-down, whereas before it was just "Current tab" that serves as a useful visual separator. So I'm going to stick with the old way.)

**Comment by joey04** [comment]
Because I'm looking at this change from a different perspective than you. I'm a hotkey guy and don't use the drop-down much. So, for me and my usage, The recent change did indeed prepend the "Current tab / " stuff that I don't need.

(I understand that for other people's use case of keeping a browser open 24/7 with a million tabs, the Current tab label in the drop-down could be helpful. But not for me.)

**Comment by joey04** [comment]
I use regular uBO on Chrome for a few things. Doing so today auto-updated uBO to 1.16.10 which has these changes. So I tested it out a bit.

Unfortunately there's a regression with the logger hotkey. Pressing it when focused on the logger tab does change it to "All" view, as was added in https://github.com/gorhill/uBlock/commit/b838e22024bb, but at the same time it clears all logger entries.

(If this would be a pain to fix, I suggest backing out the "All" view hotkey convenience. Unwanted clearing of logged data is definitely a worse problem.)

**Comment by joey04** [comment]
Just FYI - after reporting the regression I decided to port my mods to the Chrome version as well (which was easy to do since it's almost entirely identical to my modded Firefox version). So I'm no longer setup to repro anything related to this issue.
