### ISSUE TITLE
Problem with DOM-inspector

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#542]
**In general, I caught a bug.**
_Although it may not be a bug, it's a feature._

DOM inspector freezes and does **not** display/works

I filmed something, look

firefox
https://user-images.githubusercontent.com/8535285/56632788-2b16d900-66a7-11e9-9f08-8052f9b8b335.gif

opera
https://user-images.githubusercontent.com/8535285/56632798-3b2eb880-66a7-11e9-80a2-acaffcd76caf.gif

PS: Firefox 66.0.3 x64
PSS2: Opera 60.0.3255.56 x64
PSS3: OS Windows 10 LTSC 1809 x64
PSS4 uBlock Origin 1.18.16

**Comment by bogachenko** [comment]
And by the way there is another problem that I have not yet been able to shoot, but it periodically reminds itself. On volumetric sites hangs logger (open in tab) at all
Hangs only the logger, I stress, no browser, no other tabs, namely the logger. And until you reload the tab with the logger, it will not display anything at all.
**But this problem is only on firefox, not opera**

**Comment by bogachenko** [comment]
If there is any alive here, then let me know

**Comment by uBlock-user** [comment]
I can only reproduce this if I click on DOM Inspector button **5 to 6** times in succession

**Comment by bogachenko** [comment]
I sometimes get it right away with 1 click. However, also should not be at all?
By the way, where did you check? Chromium?

**Comment by uBlock-user** [comment]
Yes, Chromium. I do not think this is a bug. DOM inspector can only show DOM tree after the DOM is fully loaded in Firefox so while DOM Inspector took its time, Firefox is still unloading the page, so that's to be expected.

**Comment by bogachenko** [comment]
well. okay

**Comment by uBlock-user** [comment]
I'm seeing what could be an issue. STR provided below.

1) Open chrome://newtab and open uBO logger, active DOM inspector

2) Switch back to chrome://newtab tab and browse to google.com, now switch to uBO logger where DOM inspector is already enabled, notice DOM tree is not displayed.

3) Deactivate DOM Inspector and Activate DOM Inspector, this time DOM tree is displayed.

**Comment by bogachenko** [comment]
Just done your guide. Right. I have the same.

However, returning to 



> 
> 
> Yes, Chromium. I do not think this is a bug. DOM inspector can only show DOM tree after the DOM is fully loaded in Firefox so while DOM Inspector took its time, Firefox is still unloading the page, so that's to be expected.

> DOM inspector can only show DOM tree after the DOM is fully loaded in Firefox

Well, I even when the entire page is loaded, it happens that the DOM inspector hangs.
I almost never use Opera browser, only firefox, there I have this problem is relevant.

**Comment by bogachenko** [comment]
when you create filters in the DOM Inspector, it also freezes
look 
https://user-images.githubusercontent.com/8535285/56640157-0712c200-66be-11e9-9be9-af929faf43ae.gif
***
![Безымянный](https://user-images.githubusercontent.com/8535285/56640279-5a851000-66be-11e9-9967-f6a899c262c7.png)

and speaking of which, since we're talking about the Dom inspector, can I have him automatically close this window?

**Comment by gwarser** [comment]
>the body turns white as below

Chrome only? https://github.com/uBlockOrigin/uBlock-issues/issues/1411#issuecomment-1841718621
