### ISSUE TITLE
Most websites load broken when temporarily disabling strict blocking.

### ISSUE THREAD

**Issue by mzso** [uBlockOrigin/uBlock-issues#544]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Most website seems to load broken, without images and CSS, some few work.

### A specific URL where the issue occurs

https://www.motorsport.com/
https://www.formula1.com/
https://www.inoreader.com/

### Steps to Reproduce

1. block the website like this, in personal filters:
(I'm unaware of a non manual method of blocking a website. Can't see such feature in the ublock doorhanger)

inoreader.com
motorsport.com
formula1.com

2. Visit website.
3. Click temporarily

### Expected behavior:

Load the website normally.

### Actual behavior:

Broken website loaded.

### Your environment

* uBlock Origin version: Just upgraded to latest (1.18.16) otherwise it was happening with latest XUL version as well.
* Browser Name and version: Waterfox 56.2.3 (64 bites)
* Operating System and version: Win 8.1 x64
(Doubt any of this makes a difference)

**Comment by gorhill** [comment]
Disabling strict-blocking prevents a filter from blocking the top level document, the purpose is not to prevent a filter from blocking secondary resources -- what you report is a filter issue.

**Comment by gwarser** [comment]
If you want to see strict block warning on some pages (for whatever reasons), and then make them work without issues after allowing, use `$document` option: `||inoreader.com^$document`. It will only block main document.

**Comment by mzso** [comment]
[**@gwarser**](https://github.com/gwarser) commented on [2019. ápr. 24. 19:16 CEST](https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-486339113 "2019-04-24T17:16:06Z - Replied by Github Reply Comments"):
> If you want to see strict block warning on some pages (for whatever reasons), and then make them work without issues after allowing, use `$document` option: `||inoreader.com^$document`. It will only block main document.

Thanks.

@gorhill 
Well, what's happening was far from clear to me. I only wanted to block a website and expected it to be unblocked, when I clicked temporarily.

**Comment by mzso** [comment]
[**@gwarser**](https://github.com/gwarser) commented on [2019. ápr. 24. 19:16 CEST](https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-486339113 "2019-04-24T17:16:06Z - Replied by Github Reply Comments"):
> If you want to see strict block warning on some pages (for whatever reasons), and then make them work without issues after allowing, use `$document` option: `||inoreader.com^$document`. It will only block main document.

One curious thing:
I made a filter like this: `westeros.org^$document`
But not all subdomains are blocked.
This is blocked: https://asoiaf.westeros.org/index.php
This loads as normal: https://awoiaf.westeros.org/index.php/Main_Page

Weird.

**Comment by uBlock-user** [comment]
> This loads as normal: https://awoiaf.westeros.org/index.php/Main_Page

![](https://i.gyazo.com/50780d60ff163ec6cdb8863bff82556e.png)

Not possible, you must have visited that domain and temp disabled strict blocking which will result in being able to visit that domain for 120 secs until it gets blocked again.

**Comment by wesinator** [comment]
This is also an issue on Gmail:

My filters -> `mail.google.com`
<img width="526" alt="image" src="https://user-images.githubusercontent.com/5124946/57992583-f23e0a00-7a82-11e9-966c-a6926c89e550.png">

Gets stuck on loading page. Refresh causes Corrupted Content Error
```
Corrupted Content Error

The site at https://mail.google.com/mail/u/0/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the website owners to inform them of this problem.


```

Firefox 66.0.4
macOS

**Comment by uBlock-user** [comment]
@wesinator Not an issue. Read https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-486339113

**Comment by mzso** [comment]
[**@uBlock-user**](https://github.com/uBlock-user) commented on [2019. máj. 20. 07:39 CEST](https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-493845408 "2019-05-20T05:39:49Z - Replied by Github Reply Comments"):
> [@wesinator](https://github.com/wesinator) Not an issue. Read [#544 (comment)](https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-486339113)

I'd say it's an issue of incomprehensibility and impracticality for the user.

**Comment by gorhill** [comment]
I think the [documentation on strict-blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking) is good. Feel free to point out how the documentation can be improved.

**Comment by mzso** [comment]
[**@gorhill**](https://github.com/gorhill) commented on [2019. máj. 20. 12:45 CEST](https://github.com/uBlockOrigin/uBlock-issues/issues/544#issuecomment-493934500 "2019-05-20T10:45:05Z - Replied by Github Reply Comments"):
> I think the [documentation on strict-blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking) is good. Feel free to point out how the documentation can be improved.

I don't think many would reach the documentation, or even think that they need to. People just expect the pages to load properly when you click to temporarily disable blocking. And the addon seems bugged when it doesn't.

As for impracticality, there's no way without searching and editing filters to properly enable a page, even temporarily. (And then you have to not forget to disable it again if the page if the user thinks the block is deserved)

**Comment by gwarser** [comment]
@gorhill this: "Corrupted Content Error" is because of https://github.com/uBlockOrigin/uMatrix-issues/issues/72

I have 3p dynamically blocked on gmail, and sometimes see it too.

**Comment by gorhill** [comment]
> I don't think many would reach the documentation ... when you click to temporarily disable blocking

The documentation is linked from the strict-blocking page. The strict-blocking page does not say _"temporarily disable blocking"_, it says _"temporarily disable **strict** blocking"_.

And as for speaking on behalf of what _"People just expect"_: the feature has been in effect since years now, and there is no reason to think that it's an issue for the vast majority of people.

As per your logic, uBO should disable filtering on badware/malware/tracking sites when someone decides to bypass strict-blocking. Just to be clear in case you feel like arguing this over and over: this is not going to happen. Just use the `document` as stated above for the behavior you want.

**Comment by mzso** [comment]
@gorhill 
I just pointed out the issues I see with it.

**Comment by uBlock-user** [comment]
> I'd say it's an issue of incomprehensibility and impracticality for the user.

That's your opinion, not a fact. This has been addressed over and over. Closing.
