### ISSUE TITLE
Logger does not display all

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#545]
Hi, I have a question.
Why doesn't the logger display everything that it finds?

In my filters there is a `darckrepacks.com##.adsbygoogle` rule that triggers the antiadblock on the mentioned site, but this rule is not displayed in the logger. It also does not appear if you add it to exclude `#@#.adsbygoogle`

Look at this `*.gif`,
https://user-images.githubusercontent.com/8535285/56717630-d77cbc00-6788-11e9-9dde-b855efc19c49.gif

This is Opera browser. Ver.60.0.3255.56, but on Firefox 66.0.3 also does not show

PS: on uBlock Origin 1.18.16 too

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.

**Comment by bogachenko** [comment]
Is this not a bug?

**Comment by uBlock-user** [comment]
No, it's a question, don't post questions on the issue tracker, this tracker is only reporting bugs and maybe suggestions by filling the template.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/521>.

Do not remove the template and check the boxes as asked, you would have found the other issue and not opened a duplicate.
