### ISSUE TITLE
Handle speculative connections

### ISSUE THREAD

**Issue by sebast889** [uBlockOrigin/uBlock-issues#546]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There was a resource request type added to Firefox in version 63 called "speculative". I don't know if this is handled by uBO automatically or whether it needs to be tweaked manually so it can be filtered and shown in the logger. If uBO can deal with new request types automatically without manual tweaking then feel free to close the issue.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479565

**Comment by uBlock-user** [comment]
Doc -- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType

**Comment by gorhill** [comment]
So this should not be happening if pre-fetching is disabled (default in uBO)? As always, I need a reproducible case if you think uBO is not doing its work.

**Comment by sebast889** [comment]
If it doesn't happen when pre-fetching is disabled then this isn't an issue but I couldn't find any information in relation to that specific resource type and pre-fetching. Is it safe to assume it's covered?

Also two related questions I have to this is that from what I see there are some resource types like `ping` and `beacon` that are grouped into `other` in the logger and some resource types like `web_manifest` that don't seem to be filtered by uBO at all. Is there any reason for that? Wouldn't it better to just use their original names and also to filter all the resource types that can be seen through the webRequest API? That would make it easier see every possible request in the logger and find cases where websites are using requests for speculative, web_manifest etc. and to allow/block if needed (and in this case to try see if a speculative request shows up in logger when pre-fetching is disabled)?

**Comment by gorhill** [comment]
> `web_manifest` that don't seem to be filtered by uBO

Anything that is not a known type as per filter syntax will be converted to `other`.

**Comment by uBlock-user** [comment]
This was never an issue, OP only posted here because Firefox added a new filter request type, so he wants to get it added in uBO too, that way such requests don't get bypassed in uBO, but like you said, all unknown requests type are seen by uBO as other type.

**Comment by sebast889** [comment]
@gorhill
There is a web app manifest on Github https://github.com/manifest.json which you can see is loaded in the source of this page. However in the logger for uBO there is no `other` requests showing for it. I'm confused why `web_manifest` is given as a resource type that can be filtered by webRequest API but is not showing up separately in the logger unless it's considered under `main_frame`/`document` for some reason?

**Comment by uBlock-user** [comment]
![ff68c225d0f9b5a3d941d2af5f834518](https://user-images.githubusercontent.com/21290713/56756828-48839a00-67b0-11e9-9555-d7bb880a978d.png)

@sebast889

**Comment by sebast889** [comment]
I still can't see it in logger after full reload. Did you get that on Firefox?

**Comment by uBlock-user** [comment]
Neither do I on Firefox, so I decided to see if it appears in the Network tab in dev tools of Firefox when done a full reload and it doesn't there either, so it appears Firefox itself doesn't receive that request, so ofcourse uBO won't be able to see it either.

**Comment by gwarser** [comment]
It is visible in mobile Firefox.

**Comment by sebast889** [comment]
I tested on Chrome and I see `manifest.json` and `opensearch.xml` as `other` requests in the logger but neither show up in Firefox desktop's uBO logger or Network tab in dev tools. I'm guessing there could be more resource types like that not showing up in either logger or Network tab.

**Comment by gorhill** [comment]
uBO reports everything in the logger that goes through its onBeforeRequest listener -- regardless of whether uBO knows about the type. If it's not in its logger, it was not told by the browser. A common reason is that the request is in the browser's short term memory cache, which can be bypassed with a hard reload.

**Comment by uBlock-user** [comment]
> It is visible as web_manifest in the logger

I don't see any such type in uBO on Firefox desktop version.

**Comment by sebast889** [comment]
Does that mean this is a Firefox Desktop bug? I've tried hard reload and clearing all cache but no `other` requests show the requests in logger or dev tools.

**Comment by gorhill** [comment]
You are assuming Firefox should pull the `link` resource you see in `view-source:`. Why such assumption? Is GitHub broken on your side?

**Comment by sebast889** [comment]
I don't think GitHub is broken on my side as @uBlock-user faced the same issue.  

My assumption is because both manifest.json and opensearch.xml are showing up in Chrome but not Firefox's dev tools. I could be wrong and maybe Firefox on desktop doesn't pull it for some reason (but both opensearch and the manifest not showing up?) 

It also seems odd that @gwarser saw the request as `web_manifest` in mobile uBO's logger whereas the manifest shows up as `other` in Chrome desktop for me.

**Comment by gorhill** [comment]
See <https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest>, this explains the differences. I will unsubscribe from this thread, if there any issue after all, just mention me so that I am notified.
