### ISSUE TITLE
DNS Prefetching on HTTP sites

### ISSUE THREAD

**Issue by TestPolygon** [uBlockOrigin/uBlock-issues#548]
### Description

_This issue is on bugs.chromium.org: https://bugs.chromium.org/p/chromium/issues/detail?id=955588_

Visiting of HTTP hosted sites causes [DNS Prefetching](https://www.chromium.org/developers/design-documents/dns-prefetching) of all links inside the HTML document: all `href` of `<a>` and `<link>`  tags.

Though HTTP is non-encrypted connection, I would prefer do not have such behavior of the browser.
In case, if you use HTTPS proxy for connection to a HTTP hosted site (and block downloading of all third party elements) you can have the private channal between you and the proxy:
`[You - ISP - Internet - Proxy] - Internet - Host`

But behavior of the browser performs DNS Prefetching of all links inside the document even you does not connect to them. And it breaks privacy of this channel.

But: In incognito mode this does not happens, except `<link rel="prerender" href="...">`

I (and you) can disable DNS Prefetching of `<a>` tags by inserting HTTP Response Header `"x-dns-prefetch-control": "off"`. **It works. Can you add this functional?** I have tested it via ModHeader extension.

uBO allow to block DNS Prefetchinf of the next:
`<link rel="preload" as="..." href="...">`
`<link rel="prefetch" href="...">`
when `"href"` of `<link>` is domain that blocks by uBO.

But these:
`<link rel="preconnect" href="...">`
`<link rel="dns-prefetch" href="...">`
`<link rel="prerender" href="...">` (this "works" even in incognito mode)
cause DNS Prefetching even uBO blocks the domain containing in `"href"` attribute of these `<link>`.
**Is it possible to work around it?**

The useful userscript for testing:
```
const suffix = Math.floor(Math.random()*1000);    
function insertHTML(html) {
    document.querySelector("head").insertAdjacentHTML("afterBegin", html);
}

insertHTML(`<a                              href="https://0-just-anchor--${suffix}-test.org/">`);          // OK, disables by HTTP Header
insertHTML(`<link rel="preload" as="script" href="https://1-preload------${suffix}-test.org/script.js">`); // OK, net::ERR_BLOCKED_BY_CLIENT
insertHTML(`<link rel="prefetch"            href="https://2-prefetch-----${suffix}-test.org/">`);          // OK, net::ERR_BLOCKED_BY_CLIENT
insertHTML(`<link rel="preconnect"          href="https://3-preconnect---${suffix}-test.org/">`); // BAD, but does not work in incognito mode
insertHTML(`<link rel="dns-prefetch"        href="https://4-dns-prefetch-${suffix}-test.org/">`); // BAD, but does not work in incognito mode
insertHTML(`<link rel="prerender"           href="https://5-prerender----${suffix}-test.org/">`); // VERY BAD, works even in incognito mode

```

### A specific URLs where the issue occurs
`http://*/*`
For example: http://example.com

### Steps to Reproduce
0. Enable `Disable pre-fetching (to prevent any connection for blocked network requests)` in uBO
1. Open DNSQuerySniffer
2. Open any HTTP site (not HTTPS), for example: http://joyre{}actor.cc/tag/котэ/best (remove `{}`)
3. See, that the browser prefetched all links in the page. Links (`href`) in `<a>`, `<link>` tags was DNS resolved.

### Expected behavior:
DNS resolving should happen only for domains of resources that were downloaded.

### Actual behavior:
All `href` in `<a>`, `<link>` tags was DNS resolved.

### Your environment
* uBlock Origin version: v1.18.16
* Browser: Chromium 73 based browser.
* Operating System: Windows 10

**Comment by gwarser** [comment]
Click on "i" icon at the end of "Disable pre-fetching (to prevent any connection for blocked network requests)" option.

Only "Prediction service" can be disabled in Chrome, prefetching and preloading is still working.

**Comment by gorhill** [comment]
> by inserting HTTP Response Header "x-dns-prefetch-control": "off"

Sounds like a good idea to me.

**Comment by gwarser** [comment]
Weird. In Chrome Version 74.0.3729.108 in my system this option does not exist in `chrome://flags` even with different name as in https://www.ghacks.net/2019/04/23/missing-chromes-use-a-prediction-service-setting/

Changing uBO setting does nothing, http/https does not matter.

**Comment by gorhill** [comment]
It does help, but this does not address `rel="preconnect"` and `rel="preload"` as far as I can tell (using Chromium's `chrome://net-export/`) -- which is also used on the web page given in repro steps.

| without header | with header | blocked
| --- | --- | --- |
| ad.mail.ru | ad.mail.ru | |
| anime.reactor.cc | | ? |
| avatars.mds.yandex.net | avatars.mds.yandex.net | ? |
| coub.com | coub.com | |
| fonts.w.tools | fonts.w.tools | |
| img0.joyreactor.cc | img0.joyreactor.cc | |
| img1.joyreactor.cc | img1.joyreactor.cc | |
| joyreactor.cc | joyreactor.cc | |
| joyreactor.com | | ? |
| lol.reactor.cc | | ? |
| marketgid.com | | yes |
| polit.reactor.cc | | ? |
| show.ctrmanager.com | show.ctrmanager.com | yes |
| storage.mds.yandex.net | storage.mds.yandex.net | ? |
| sw.reactor.cc | | ? |
| tes.reactor.cc | | ? |
| twitter.com | | ? |
| vkontakte.ru | | ? |
| www .facebook.com | | ? |
| www .liveinternet.ru | | ? |
| ya.ru | | ? |
| yastatic.net | yastatic.net | yes |
| ysa-static.passport.yandex.ru | ysa-static.passport.yandex.ru | ? |

Observations from above:
- the header `X-DNS-Prefetch-Control` will be disregarded whenever a `rel="preconnect"`/`rel="preload"` is used
- when `rel="preconnect"`/`rel="preload"` is not used, Chromium still ignores the _"Disable prefetch"_ setting -- and this is when the header `X-DNS-Prefetch-Control` is most useful.

**Comment by gorhill** [comment]
It does help, but this does not address `rel="preconnect"` and `rel="preload"` as far as I can tell (using Chromium's `chrome://net-export/`) -- which is also used on the web page given in repro steps.

I blocked all 3rd-party scripts/frames for the test, to minimize variability across page loads. This is the results with uBO's _"Disable prefetch"_ enabled:

| without header | with header | blocked
| --- | --- | --- |
| anime.reactor.cc | | ? |
| avatars.mds.yandex.net | avatars.mds.yandex.net | ? |
| fonts.w.tools | fonts.w.tools | |
| img0.joyreactor.cc | img0.joyreactor.cc | |
| img1.joyreactor.cc | img1.joyreactor.cc | |
| joyreactor.cc | joyreactor.cc | |
| joyreactor.com | | ? |
| marketgid.com | | yes |
| polit.reactor.cc | | ? |
| show.ctrmanager.com | show.ctrmanager.com | yes |
| storage.mds.yandex.net | storage.mds.yandex.net | ? |
| twitter.com | | ? |
| vkontakte.ru | | ? |
| www .facebook.com | | ? |
| www .liveinternet.ru | | ? |
| ya.ru | | ? |
| yastatic.net | yastatic.net | ? |
| ysa-static.passport.yandex.ru | ysa-static.passport.yandex.ru | ? |

The `?` in the "blocked" column means that the entry does not appear in uBO's popup panel, while "yes" means it is shown as blocked in the panel.

Observations from above:
- the header `X-DNS-Prefetch-Control` will be disregarded whenever a `rel="preconnect"`/`rel="preload"` is used
- when `rel="preconnect"`/`rel="preload"` is not used, Chromium still ignores the _"Disable prefetch"_ setting -- and this is when the header `X-DNS-Prefetch-Control` is most useful.

**Comment by uBlock-user** [comment]
For preconnect/prerender -- https://bugs.chromium.org/p/chromium/issues/detail?id=786038

**Comment by gwarser** [comment]
Easier to watch on linux by: `script -q -c "sudo tcpdump -l port 53 2>/dev/null | grep --line-buffered ' A? ' | cut -d' ' -f8" | tee dns.log` from https://unix.stackexchange.com/questions/43716/how-to-log-all-my-dns-queries

using OP scriptlet on example.com Chrome 74.0.3729.108

In uBO from master only "0-just-anchor" does not appear in both http and https

In 1.18.16, I see "0-just-anchor" only on http: page.

**Comment by uBlock-user** [comment]
So this is limited to http sites only ? I use CloudFlare D-O-H instead of normal unencrypted DNS services.

**Comment by gorhill** [comment]
@gwarser Not sur eI understand what you are reporting. Is the fix good or bad?

Note that I was using `chrome://net-internals/#dns` to clear the resolver cache before each test.

**Comment by gorhill** [comment]
I tried to use CSP's [`prefetch-src 'none'`](https://w3c.github.io/webappsec-csp/#directive-prefetch-src) to disable prefetching but this does not work, I get the following message in the console:

> The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

I couldn't spot any obvious flag related to this.

**Comment by gwarser** [comment]
It works. DNS prefetching for `<a>` no longer appears.

OP script uses random domains - no need to clear DNS cache.

DNS requests for preload, prefetch, preconnect, dns-prefetch, prerender happen no mater what.

**Comment by uBlock-user** [comment]
> I couldn't spot any obvious flag related to this.

chrome://flags/#enable-experimental-web-platform-features

**Comment by TestPolygon** [comment]
> So this is limited to http sites only ?

https://www.chromium.org/developers/design-documents/dns-prefetching
`DNS Prefetch Control` section

> OP script uses random domains - no need to clear DNS cache.

Yes, with this script you can easy test the behavior on http://example.com without problem related to DNS caching. Just inject it like a usercript|contenscript (I use `User JavaScript and CSS` extension for it). Check the comments at the end of lines (`insertHTML(...)`) too. 

Cases to test:
- Normal mode
- Add "x-dns-prefetch-control": "off" header
- Add blocking of all third party content
- In incognito mode

**Comment by h1z1** [comment]
How does this not have more public coverage?  What a nasty little "bug" (in chrome).

**Comment by atelosotaar** [comment]
works for `https` too, try https://www.pcmag.com/
I'm not using any DNS servers, so I'm unsure if it will only DNS-lookup or also load content, but it tries these:
```
product.pcmag.com
product.pcmag.com
product.pcmag.com
product.pcmag.com
zdbb.net
www.googleadservices.com
www.googleadservices.com
api.bounceexchange.com
www.google-analytics.com
www.google-analytics.com
static.pcmag.com
assets.pcmag.com
pagead2.googlesyndication.com
api.bounceexchange.com
partner.googleadservices.com
pagead2.googlesyndication.com
a.zdbb.net
partner.googleadservices.com
assets.pcmag.com
a.zdbb.net
```
