### ISSUE TITLE
Show requests blocked in the logger as a result of `csp=` option

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#552]
See <https://github.com/uBlockOrigin/uAssets/issues/5492>:

> That is the  big issue I see with csp filters, I have to use the dev console to see what is blocked and then debug and  because of that sometimes even experienced filter list maintainers don't know that their csp filter is actually breaking site functionality. https://github.com/uBlockOrigin/uAssets/issues/2073#issuecomment-384157988
> 
> Seeing the blocked requests in the logger would make debugging more straightforward for everybody.

**Comment by gwarser** [comment]
Any plans for creating CSP exceptions from the logger? Current dialogs for static and dynamic filtering does not work.

**Comment by gorhill** [comment]
I have plans to create temporary exception/badfilter from the logger with one click to make life of filter list maintainers easier.

**Comment by sebast889** [comment]
@gorhill
Do you think it makes sense to add `csp` in the logger's filter expression picker for easy hiding/showing of CSP affected requests?

**Comment by uBlock-user** [comment]
Experiencing this on Firefox stable/nightly currently --

STR -- 

- Add ||movieweb.com^$csp=img-src 'none' to my filters.

- Open the logger and go to `https://movieweb.com/ `, notice no images blocked via CSP filter are reported in the logger.
