### ISSUE TITLE
The wrong homepage is used for Energized Blu Go Protection

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#553]
As of https://github.com/gorhill/uBlock/commit/0991a1138ea87afa101c990041ed1949aa8e90aa, the supportURL uses the address of an older GitHub repo for which AdroitAdorKhan has mostly stopped providing service, if https://github.com/AdroitAdorKhan/EnergizedProtection/issues/44 is any indicator.

I believe that the current correct support address is https://github.com/EnergizedProtection/block.

**Comment by gorhill** [comment]
I removed the list in <https://github.com/gorhill/uBlock/commit/b654d883dfe58e279e62b9aadd0f1a203f200e9f> due to the unresolved license issue.

**Comment by DandelionSprout** [comment]
Even in the event that the licences does get sorted out one day, my personal opinion (which is not representative of anyone else) is that Energized Blu Go is underqualified for uBO inclusion. Of its 141,000 entries, [only ~20,550 are original work](https://github.com/AdroitAdorKhan/EnergizedProtection/blob/master/core/hosts), with the remaining 120,000 being [taken from 32 other lists](https://github.com/EnergizedProtection/block#packs-2) with automation, many of whom are already included in uBO in superior formats. 
![image](https://user-images.githubusercontent.com/22780683/57076595-4eb2d280-6cea-11e9-8b2a-e342501f617e.png)

I'd have favoured looking for includable lists that are based on original work instead, if possible.
