### ISSUE TITLE
No consistent design on "shortcuts.html"

### ISSUE THREAD

**Issue by YoKoGFX** [uBlockOrigin/uBlock-issues#555]
Every other page is using a `text-align:left`, this page is using `text-align: end;`
I think we should make this page like all other, with same `margin`, `padding` and `text-align`.

* uBlock Origin version: v1.18.16
* Browser Name and version: Firefox 66.0.3 (64-Bit)
* Operating System and version: Windows 10.0.18362 Build 18362

**Comment by uBlock-user** [comment]
The page is going to get [removed soon](https://github.com/uBlockOrigin/uBlock-issues/issues/386), so why even bother ?
