### ISSUE TITLE
uBlock Origin could not be verified for use in Firefox and has been disabled

### ISSUE THREAD

**Issue by dehghani-mehdi** [uBlockOrigin/uBlock-issues#558]
I can not (I don't want to) use Firefox without uBlock, so when this error will be fixed?

![Screenshot_1](https://user-images.githubusercontent.com/9152330/57174094-3a87e600-6e4e-11e9-9cb2-a240dec38a4f.png)

**Comment by temelj** [comment]
I can confirm that this as an issue on Firefox on Android.  (66.0.2)
In fact, a few add-ons have stopped working properly.

**Comment by krab** [comment]
https://i.imgur.com/eHbHaFU.png

Can't be verified and disabled. 66.0.3 Windows.

**Comment by tarzanek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

**Comment by temelj** [comment]
@tarzanek Cheers,  forgot to check FF issue register.  That's a bit of a "oops" :)  
@krab your screenshot - as much as most could make sense of it, is useless in Cyrillic.

**Comment by rafaelsimonmaia** [comment]
I found a way to work around the problem by adding the extension manually via about:addons then `debug add on`, `add a temporary add on` and finally checking `Enable add-on debugging`. This on firefox 66 on a mac.

**Comment by linermgn** [comment]
Ubuntu 19.04, Firefox 66.0.3, confirmed

**Comment by 0xh3LL0** [comment]
can confirm as well,

**Comment by war456** [comment]
Hello
I have a problem
I can not use Firefox v 66.0.3 without uBlock, so when will this error be fixed?

  there is a solution or not?

thank you

![Capture](https://user-images.githubusercontent.com/50258347/57174530-c2ff8a00-6e40-11e9-8bad-dc3ade7ef6b4.PNG)

**Comment by okiehsch** [comment]
https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by war456** [comment]
when will the problem be solved?

thank

**Comment by uBlock-user** [comment]
Firefox issue,  not a uBO issue, disable the signing thing or install the dev build of uBO of from github releases section.

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/firefox/comments/bkfg4f/is_there_no_way_to_force_the_disabled_plugins_to/emgaxhf/

**Comment by uBlock-user** [comment]
Firefox update fix -- https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/
