### ISSUE TITLE
Missing entries in dropdown list when logger opened second time

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#56]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Open logger, close, open again - you will see only three entries in dropdown list All, Behind the scene and Current tab

### A specific URL where the issue occurs

Home page or for example https://www.mozilla.org/en-US/privacy/firefox/ (opened automatically on first start in clean profile)

### Steps to Reproduce

1. install UBO on clean profile 
2. open logger by clicking icon in popup
3. notice dropdown list will have entries with all opened tabs<sup>*</sup>
4. close logger tab/window
5. open logger again 

### Expected behavior:

All tabs should be listed in dropdown list (Welcome in Firefox, Privacy notice)

### Actual behavior:

Dropdown list have only three entries All, Behind the scene and Current tab

[*] In builds with auto-opening sidebar list will have missing entries in point 3.

### Your environment

* uBlock Origin version: 1.16.8, 1.16.9b5
* Browser Name and version: Firefox stable, beta, nightly
* Operating System and version: Mint 18.3

### Note:
```
689d18c54f65c2df29f412fad960473fee6dc888 is the first bad commit
commit 689d18c54f65c2df29f412fad960473fee6dc888
Author: Raymond Hill <rhill@raymondhill.net>
Date:   Mon Jan 8 14:29:39 2018 -0500

    fix #2854
```
https://github.com/gorhill/uBlock/commit/689d18c54f65c2df29f412fad960473fee6dc888
https://github.com/gorhill/uBlock/issues/2854

**Comment by uBlock-user** [comment]
Is this specific to Firefox ?

**Comment by gwarser** [comment]
Yes.

**Comment by gorhill** [comment]
Issue is that `beforeunload` does not fire with Firefox:

https://github.com/gorhill/uBlock/blob/c6cab029996249a38b109517190cb154f0d6b32d/src/js/logger-ui.js#L1729-L1730

**Comment by gorhill** [comment]
By the way, the workaround until fix (when I can figure a sane one) is to just wait ~20 seconds, until uBO determines that the closed logger window is no longer alive and thus pass the ownership of the logger to the new one.

**Comment by gwarser** [comment]
I cannot reproduce in Nightly anymore (with uBO 1.16.14). Firefox Beta still affected.

`beforeunload` bug is untouched ?

**Comment by gwarser** [comment]
I cannot reproduce anymore.
