### ISSUE TITLE
Ads fake-blocked or ads reload after blocking

### ISSUE THREAD

**Issue by AMDphreak** [uBlockOrigin/uBlock-issues#562]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ads on WebMD website are getting through uBlock even though uBlock says they are blocked. They are blocked and then show up afterward.

### A specific URL where the issue occurs

https://www.webmd.com/a-to-z-guides/adrenal-fatigue-is-it-real#1

### Steps to Reproduce

1. Go to website

### Expected behavior:

Ads blocked

### Actual behavior:

Ads either are blocked but then reloaded without uBlock noticing, or uBlock says it blocked them but fails to block them.

### Your environment

* uBlock Origin version: uBlock Origin 1.18.16
* Browser Name and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Operating System and version: Windows 10 Pro Version	10.0.17134 Build 17134

**Comment by dashed** [comment]
I'm noticing this in https://www.addic7ed.com

**Comment by kpcee** [comment]
What a terrible website, it slows down the browser considerably. To fix the problem it is enough to disable inline scripts. If this is too strong, you can further refine it with a scriptlet from the Resources Library e.g. [abort-current-inline-script](https://github.com/gorhill/uBlock/wiki/Resources-Library#abort-current-inline-scriptjs-).

**Comment by injust** [comment]
@AMDphreak See https://github.com/gorhill/uBO-Extra

**Comment by gorhill** [comment]
Filter issues are not to be handled here, as clearly spelled out in the template:

> Filter issues MUST be reported at filter issue tracker

The site use Instart Logic, use install [uBO-Extra](https://github.com/gorhill/uBO-Extra#ubo-extra) or use Firefox + uBlock Origin.
