### ISSUE TITLE
uBlock still blocking actions that should be used

### ISSUE THREAD

**Issue by Power2All** [uBlockOrigin/uBlock-issues#563]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock is still actively affecting JavaScript, even when disabled with the big button. The issue goes away when you completely disable uBlock through the extensions menu. First thought this was a Opera only issue, but it also happens on Chrome when uBlock is enabled. But the big button doesn't do anything.

### A specific URL where the issue occurs

[http://windows.power2all.com:8000/](http://windows.power2all.com:8000/)

I've made a gif how it's suppose to work:
![alt text](https://i.imgur.com/j0e5QJH.gif)

If you open the URL as given above is opened with uBlock, you will notice it won't work the way it is shown in the GIF. The error is with the "hidden.bs.collapse" and all other events seem to be affected to it as well.

### Steps to Reproduce

1. Open the URL as given above.
2. Click on the Category & Search link
3. Collapse a category by using the arrow behind the name.
4. Click again on Category & Search to close the list.
5. Re-open the Category & Search, it should have closed down all the collapses, but it doesn't.

### Expected behavior:

It should collapse all category sub options. In Mobile view, when you have category open and you close the whole menu, it should close all.

### Actual behavior:

It does not execute the event hidden.bs.collapse as it's suppose to.
See [https://getbootstrap.com/docs/4.0/components/collapse/](https://getbootstrap.com/docs/4.0/components/collapse/)
We figured out it was uBlock after discussing with the developers of Opera, and we could do the same on a normal clean Chrome setup, both locally and on BrowserStack.

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Chrome 73 and Chrome 74, Opera 60.0.3255.70, also confirmed on Firefox 66.0.3 and 66.0.4
* Operating System and version: Windows 10 Pro

**Comment by gorhill** [comment]
Unable to reproduce: when I disable uBO using the large blue button and force a reload of the page, the issue disappear. This points to a filter issue, not to be handled here.

**Comment by Power2All** [comment]
Not a filterlist issue.
Here a gif of the disabled ublock and showing the issue:

![alt text](https://i.imgur.com/MgiVIll.gif)

If it is a filterlist issue, uBlock should be enabled.
Filterlist shouldn't be affecting the javascript of a website when uBlock is off.

**Comment by gorhill** [comment]
@uBlock-user Did you reproduce? I can't reproduce on Chromium 73.

**Comment by uBlock-user** [comment]
I cannot reproduce on Firefox Nightly with uBO enabled but I can reproduce on Chromium though.

**Comment by gorhill** [comment]
Ok I can reproduce on Google Chrome 74.

**Comment by gorhill** [comment]
@Power2All You have other extensions enabled? What is that padlock icon beside uBO?

**Comment by Power2All** [comment]
Was some addon for adding stuff apart from what Google hides. Disabled it too to make sure it still did same problem.

**Comment by Power2All** [comment]
I enabled default filter of ublock.

**Comment by gorhill** [comment]
I can reproduce with ABP 3.5.2 and Adguard 3.0.14.

**Comment by Power2All** [comment]
> I can reproduce with ABP 3.5.2 and Adguard 3.0.14.

Question is, why does it happen when uBlock or any block is disabled ?
It shouldn't be affecting the website at all if the blockers are disabled, or am I wrong ?
This means, that in order to use the javascript functions of Bootstrap properly, is by disabling completely the extensions ? I don't think that's suppose to be the only way to make the site work, other then figuring out which filter lists are blocking these events.

**Comment by Power2All** [comment]
I tried a work-around, but it looks like uBlock and adBlock block all listeners and events.
For example
```        $('#navigation-options').bind('attrchange csschange', function(event) {
            if (!$('#navigation-options').hasClass('show')) {
                console.log("Triggered 2");
                $(this).find('.collapse').collapse('hide');
            }
        });
```
This code will NOT work on uBlock and adBlock, however, it works fine when using all browser without any of these extensions loaded.
The console.log() won't be triggered at all.

**Comment by gorhill** [comment]
So far it's what I have:

As soon as a blocker is enabled, your event listener for `show.bs.collapse` is not called. Somewhere in the large callstack of calls to jQuery and Bootstrap, the event stopped being triggered.

Between the `click` event and your handler, it's all jQuery and Bootstrap code, there is no blocker code in between.

**Comment by Power2All** [comment]
Problem found !
I looked deeper, and found the problem.

```
window.onload = function () {
}
```

When using this, it seems adblock and ublock disable this function way.

Changing it to:

```
$(document).ready(function() {
});
```

Made it work.
So it looks like the former way is a issue for blocking extensions.

**Comment by gorhill** [comment]
`window.onload` is not used by uBO. I was suspecting this was related to MutationObserver but now I can't test my prototype since you changed your code. Can you make a copy for me of the non-working version?

**Comment by Power2All** [comment]
Will do.

**Comment by Power2All** [comment]
Okay I'm confused now.
I reverted the change, but it still works now....

**Comment by gorhill** [comment]
Yeah, I also can't reproduce. Surely there must be a difference.

**Comment by Power2All** [comment]
> Yeah, I also can't reproduce. Surely there must be a difference.

Yah, I thought so too....
Oh well, I will stick with document ready now, at least it got solved now.
If I come across the same problem again, I will let you know immediately.
For now we can close it.
