### ISSUE TITLE
Add list without RAW

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#564]
@uBlock-user  _yes, that is the question. And no, I don't want to go to the reddit._
_please do not block the oxygen immediately and do not block the possibility of commenting_

How to add a filter list that does not have RAW 
eg `http://ideone.com/plain/K452p` this is Adblock-Persian list - see `https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/ApiSampleExtension/sample-extension/adguard/filters.json#L882`
And by the way there are many such lists. They do not open in the browser, but immediately download this shit to my computer

![Безымянный](https://user-images.githubusercontent.com/8535285/57221524-52788900-704b-11e9-84c3-b481a3ed56f1.png)

**Is it possible to add the ability to add such links?**

PS/ I searched this question in this repository and did not find. I badly searched?

**Comment by mapx-** [comment]
click import, add the link and uBo read it. No issue here FF / chrome.

**Comment by bogachenko** [comment]
@mapx- look at the picture above

**Comment by bogachenko** [comment]
lol. in firefox it does not. and in opera reads normally. what the fuck?

**Comment by gorhill** [comment]
I could import fine with Firefox, your issue is elsewhere.

**Comment by uBlock-user** [comment]
> @uBlock-user yes, that is the question. And no, I don't want to go to the reddit.
please do not block the oxygen immediately and do not block the possibility of commenting

I'm not obligated to entertain your "demands", this isn't the place for this question, period.
