### ISSUE TITLE
Feature requests for ":matches-css"

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#567]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I'm combining two feature requests into one, as I wish to become able to write entries to modify specific pre-existing CSS element values, à la `fandom.com##body:matches-css(cursor: url*):style(cursor: auto)`. This would make it possible to write very good CSS-editing entries that'd make uBO's `:style` feature even more superior to the functionalities of privacy-scandal-struck CSS-editor-specific extensions like *Stylish*.

Request 1: Supporting wildcards in the `:matches-css` text selection, as it'd (among many other things) make it possible to target all uses of custom URL values, instead of one and one custom image at a time.

Request 2: Making it possible to combine `:matches-css` with `:style`.

### A specific URL where the issue occurs

`https://winx.fandom.com/wiki/Tecna`.

### Steps to Reproduce

1) Open the element picker.
2) Write `##body:matches-css(background-size: cover)`, and see that the picker does recognise such an element.
3) (In request 1) Write e.g. `##body:matches-css(background-size: *)`, `##body:matches-css(background-size: cov*)` `##body:matches-css(/background-size:.*/)`, `##body:matches-css(/[background-size: ]*/)` or `##body:matches-css(background-size:)` (among others), and see that the picker doesn't recognise any of them.
3) (In request 2) Write `##body:matches-css(background-size: cover):style(background-size: unset)`, and see that the picker doesn't recognise it.

### Expected behavior:

That the elements would've been hideable by uBO under such criteria.

### Actual behavior:

(Covered by the reproduction steps.)

### Your environment

* uBlock Origin version: uBO 1.18.16
* Browser Name and version: Vivaldi 2.3.1440.61 64-bit
* Operating System and version: Windows 10 October 2018 Update (Recentmost installed update: KB4495667)

**Comment by gwarser** [comment]
1. use regular expression 
2. https://github.com/uBlockOrigin/uBlock-issues/issues/382

**Comment by DandelionSprout** [comment]
I suppose both of those links explains it. My fault.

**Comment by uBlock-user** [comment]
Duplicate https://github.com/uBlockOrigin/uBlock-issues/issues/382
