### ISSUE TITLE
Untokenizable filters with one wilcard no longer work

### ISSUE THREAD

**Issue by hundreAd100** [uBlockOrigin/uBlock-issues#568]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

filters starting with ``/`` no longer work
e.g. ``/almoni*$font`` is NOT blocked (was on previous versions)
now only ``/*almoni*$font`` works

### A specific URL where the issue occurs

https://www.walla.co.il/

### Steps to Reproduce

1. open url
2. see in logger that ``/almoni*$font`` no longer blocks:
https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-400.ttf
https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-800.ttf
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-700.ttf
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-500.ttf
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-600.ttf
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-400.woff
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-800.woff
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-700.woff
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-500.woff
​https://www.walla.co.il/fonts/almoni/almoni-neue-aaa-600.woff

### Expected behavior:

should block

### Actual behavior:

does not block

### Your environment

* uBlock Origin version: 1.19.0
* Browser Name and version: firefox 58.0.2
* Operating System and version: windows 10 v10.0.17134.706

**Comment by uBlock-user** [comment]
Addendum : `/almoni$font` works, however `/almoni*$font` doesn't.

**Comment by sebast889** [comment]
Filter `website*.*` is showing up as block caused by filter `website*.` (no 2nd wildcard) on strict blocking page when visiting `website.com`. Is this normal?

**Comment by gorhill** [comment]
Yes, normal, the trailing wildcard is not needed, so the filter is normalized to `website*.`.

**Comment by jspenguin2017** [comment]
Sorry if it's false alarm but do you need to update compile / selfie magic for the change?

**Comment by gorhill** [comment]
The issue is highly unlikely to affect any of the filter lists, it's an inefficient filter I doubt filter list maintainers would use -- not worth trashing all the compiled lists.
