### ISSUE TITLE
Black Box

### ISSUE THREAD

**Issue by thatsprettygood** [uBlockOrigin/uBlock-issues#57]
### Prerequisites

- [✔️] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✔️] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [ ✔️ I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [] uBlock Origin is the only extension
    - [] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [✔️ ] I am running the latest version of uBlock Origin
- [✔️ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Expected behavior: to see the menu

[What you expected to happen]

### Actual behavior: get a black box
![bug](https://user-images.githubusercontent.com/36249601/40938666-77b0bfc4-6810-11e8-9b04-13049659cc42.PNG)

### Your environment

* uBlock Origin version: v1.16.9b5
* Browser Name and version: chrome canary  
* Operating System and version: win 10

**Comment by uBlock-user** [comment]
> chrome canary

Bad Build of Canary, go back to previous version or find a stable version.
