### ISSUE TITLE
Firefox for Android hanging everytime uBlock Origin because of hntrie.js:187

### ISSUE THREAD

**Issue by Granddao** [uBlockOrigin/uBlock-issues#570]
### Prerequisites
- [X] I verified that this is not a filter issue
- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [-] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Getting [this error](https://imgur.com/7H1jGIY) every time when opening Firefox for Android, have to manually close and reopen the browser to make it work again.

### A specific URL where the issue occurs

See image

### Steps to Reproduce

There's none actually since I only experience it on my Android.

### Expected behavior:

Browser to open and operate normally

### Actual behavior:

Hanging, force close and reopen to make it work again

### Your environment

* uBlock Origin version: 1.19.2
* Browser Name and version: Firefox for Android 66.0.5
* Operating System and version: Android 7.1.1

**Comment by uBlock-user** [comment]
Close those two tabs that are opened, then close the browser manually and open it again.

**Comment by gorhill** [comment]
What is your browser locale?

**Comment by gorhill** [comment]
@uBlock-user You labelled the issue "something to address": you are able to reproduce.

I am not able to reproduce.

**Comment by uBlock-user** [comment]
No, I added that label because I don't use FF on Android, so someone from the team will need to investigate and try to reproduce.

**Comment by Granddao** [comment]
@gorhill Sorry yea, I wasn't able to use a new profile as I am not sure how to backup my current profile without root as I am a non-root user. 

My browser locale is EN 

I feel like this issue was solved automatically? Since I don't experience it after reporting this. Thanks!
