### ISSUE TITLE
Redirection fails for filters having `*` in the host part 

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uBlock-issues#572]
Orginal polish issue: https://github.com/olegwukr/polish-privacy-filters/issues/67
Orginal uassets issue: https://github.com/uBlockOrigin/uAssets/issues/5360
The current issue perhaps somehow related to https://github.com/uBlockOrigin/uBlock-issues/issues/568  and  https://github.com/gorhill/uBlock/issues/1597 and https://github.com/gorhill/uBlock/issues/3590 not sure.

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

We were just trying to find a pure uBO solution (that doesn't need external solutions: (https://github.com/uBlockOrigin/uAssets/issues/5360#issuecomment-490782224) for anti-adblock for player.pl: https://github.com/olegwukr/polish-privacy-filters/issues/67 and we succeeded (for Chrome-based browsers) but by the way discovered that some redirection filters with `*` does not work. We're not sure whether it's a bug in uBO or just a filter bug in domain syntax of the filter - perhaps only `*.` works and no other characters are allowed in the domain of the filter if `*` is used, like entity in static extended filters: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#entity

### A specific URL where the issue occurs

Example url: `https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114`

### Steps to Reproduce

Filter 1: `||n-*-*.dcs.redcdn.pl/*/TVN-Adserver/*.mp4$media,redirect=noopmp3-0.1s,domain=player.pl `
Filter 2: `||n-*.dcs.redcdn.pl/*/TVN-Adserver/*.mp4$media,redirect=noopmp3-0.1s,domain=player.pl `
Filter 3: `||*.dcs.redcdn.pl/*/TVN-Adserver/*.mp4$media,redirect=noopmp3-0.1s,domain=player.pl`
Filter 4: `||dcs.redcdn.pl/*/TVN-Adserver/*.mp4$media,redirect=noopmp3-0.1s,domain=player.pl`

0. make sure you have also both regional PL filter lists enabled
1. add the Filter 1 and Filter 2 to My Filters
2. open the logger
3. visit the website
4. on the website notice the spinning wheel - the video won't load, and then an error is showing up instead because the redirection Filters 1 and 2 don't work
5. go back to the logger and notice a lack of the redirection filter in the logger
6. add the Filter 3 or Filter 4
7. visit the website again
8. on the website notice the ads are being skipped / redirected and then the video is playing fine
9. go back to the logger and notice a presence of the redirection filter in the logger

### Expected behavior:

Filters 1 and 2 should work just like Filter 3 and 4.

### Actual behavior:

Filters 1 and 2 not working, the part `n-*-*.` or  `n-*.`  breaks the redirection.

### Your environment

* uBlock Origin version: 1.19.3b0
* Browser Name and version: Opera 60 64bit
* Operating System and version: Windows 7 Pro SP1 PL

### Screenshoots:

<details not-open>
<summary>Filters 1 and 2 (video not playing - an error showing up)</summary>

![1](https://user-images.githubusercontent.com/43844449/57652739-823a0a80-75d0-11e9-9c07-d84a97a4928d.png)

</details>

<details not-open>
<summary>Filters 3 and 4 (video playing fine)</summary>

![2](https://user-images.githubusercontent.com/43844449/57652575-296a7200-75d0-11e9-81e7-419a7f0f235a.png)

</details>

**Comment by gwarser** [comment]
>Specifically, notice that the filter must start with || or *, otherwise no redirection directive will be created, although a blocking filter will be created. Essentially, a redirection filter must always have a destination hostname specified, or * if the filter is to apply to all destinations*.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect

Domain with wildcard is not explicit enough.

**Comment by gorhill** [comment]
As pointed out in the documentation excerpted by @gwarser, not supported.

**Comment by gorhill** [comment]
Let's say I take `https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114` as a typical case why uBO should support wildcard inside hostname for redirection purpose... I am unable to see network requests matching `n-*-*.dcs.redcdn.pl`, I rather see `r-scale-*.dcs.redcdn.pl` on my side. What do I need to do to reproduce the `n-*-*.dcs.redcdn.pl` ones?

**Comment by gorhill** [comment]
Sorry for my quick dismissal, giving more thoughts to this, uBO should still be able to extract a wildcard-less hostname from `||n-*-*.dcs.redcdn.pl^...` and use this for the quick lookup of redirection directives.

**Comment by kulfoon** [comment]
I'm unable to verify whether the fix works or not at given specific case, as no `TVN-Adserver` requests in the logger anymore in Opera (however they are still present in Firefox), and even Filters 3 and 4 won't unblock the video now, perhaps something changed at the website's side, exactly at this time, a strange coincidence, 

so I've tried to redirect another request: `https://s1-player5.cdntvn.pl/video/test.mp4` with a filter:
`||s*-player*.cdntvn.pl/video/test.mp4$media,redirect=noopmp3-0.1s,domain=player.pl` 
but a redirection hasn't occured, and the request has been blocked.

when I've tried: `||cdntvn.pl/video/test.mp4$media,redirect=noopmp3-0.1s,domain=player.pl` a redirection is working.

Could you verify whether the fix works.

**Comment by gorhill** [comment]
> Could you verify whether the fix works.

I made a mistake and tested only the one-wildcard case. This should work in the next dev build.

**Comment by kulfoon** [comment]
It fixed the two-wildcard case : https://github.com/uBlockOrigin/uBlock-issues/issues/572#issuecomment-492147440

But now I've noticed another broken case, a one-wildcard case - which was already present even before the last fix, only that I didn't check it before:
`||s*-player5.cdntvn.pl/video/test.mp4$media,redirect=noopmp3-0.1s,domain=player.pl`

**Comment by gorhill** [comment]
> `||s*-player5.cdntvn.pl/video/test.mp4$media,redirect=noopmp3-0.1s,domain=player.pl`

Ok, I overlooked that a wildcard could be position at another position than hostname label boundary. I will also fix for next dev build.

**Comment by kulfoon** [comment]
Fixed, all filters works now, even those from the 1st comment (as `TVN-Adserver` request is back, so I've been able to test them too).
