### ISSUE TITLE
Firefox refusing to load pages.

### ISSUE THREAD

**Issue by Nedlinin** [uBlockOrigin/uBlock-issues#574]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
uBlock Origin being enabled renders browsing to any site impossible.  Refreshing the browser/new profile appears to work but only for a short time (I've had to reset 3 times in 8 days now). 

Disabling uBlock causes every pages to load almost instantly.

Logger shows *zero* activity.

Sounds like #571  though I suspect it was closed for massive lack of info.

### A specific URL where the issue occurs

www.google.com
www.amazon.com
www.reddit.com
www.anythingintheworld.com

### Steps to Reproduce

1. Have uBlock enabled.
2. Navigate to website.

### Expected behavior:

Website loads.

### Actual behavior:

Website doesn't load.

### Your environment

* uBlock Origin version: 1.19.2 and 1.19.3.2 tested
* Browser Name and version: Firefox Quantum 66.0.5
* Operating System and version: Win10 x64 1803

**Comment by Nedlinin** [comment]
Video with example: https://www.youtube.com/watch?v=X_x-PCQUPkU&feature=youtu.be  

Chrome on the left with uBlock working fine.  Firefox on the right showing the issue.

**Comment by uBlock-user** [comment]
> Sounds like #571

Reminds me of https://github.com/uBlockOrigin/uBlock-issues/issues/416 to me..

**Comment by gorhill** [comment]
Any error at the browser console (ctrl-shift-j)?

**Comment by Nedlinin** [comment]
@gorhill : Unfortunately cannot replicate after the upgrade of Firefox to 67.0b19.  If it happens again (as it has a few times in the last week) I'll make sure to check console for any info.

**Comment by gorhill** [comment]
Do you know whether the CPU usage of Firefox was high when this occurred?

**Comment by Nedlinin** [comment]
I did not check Task Manager at that specific point in time but it wasn't high enough to cause the fans on my machine to spin up.  (Not super scientific, I know).
