### ISSUE TITLE
Cosmetic Filter Exception Filters Not Being Applied in latest dev build

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#575]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Cosmetic Filter Exception filters appear to no longer work with latest dev build (1.19.3b2)

Could be related to the code update of [src/js/html-filtering.js](https://github.com/gorhill/uBlock/commit/93f80eedfa4ef5e127d2679378b1c78cae3c3d4b#diff-14236105c73933a7b56e6ae82c6ff0e0R210)? 

### A specific URL where the issue occurs

`https://apnews.com/9aa77864e6754a5e9624c6f864691f28`

### Steps to Reproduce

1. Add the following filters
```
##.SocialShare
apnews.com#@#.SocialShare
```
2. Navigate to `https://apnews.com/9aa77864e6754a5e9624c6f864691f28`
3. Observe the `##.SocialShare` generic filter is still removing the cosmetic element that should be overruled by `apnews.com#@#.SocialShare` domain specific exception filter.

### Expected behavior:

Social box should be allowed on sidebar with the exception filter
![image](https://user-images.githubusercontent.com/22258847/57798137-0c41ba80-771a-11e9-8c8d-3284bb18ba3b.png)
### Actual behavior:

Exception filter not being applied.

* uBlock Origin version: 1.19.3b2
* Browser Name and version: Chrome 75.0.3770.27 (Official Build) beta (64-bit) & Firefox 66.0.5 (64-bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
`#@#.SocialShare` doesn't get applied either..

**Comment by uBlock-user** [comment]
Adding `#@#.SocialShare` to My Filters results in this -- 

![](https://i.gyazo.com/ddba202a1e81035598025ade7b831864.png)

**Comment by gwarser** [comment]
> Could be related to the code update of [src/js/html-filtering.js](https://github.com/gorhill/uBlock/commit/93f80eedfa4ef5e127d2679378b1c78cae3c3d4b#diff-14236105c73933a7b56e6ae82c6ff0e0R210)?

Not this type of filter. More like https://github.com/gorhill/uBlock/commit/93f80eedfa4ef5e127d2679378b1c78cae3c3d4b
