### ISSUE TITLE
Specific website content not loading 

### ISSUE THREAD

**Issue by MiStateForever** [uBlockOrigin/uBlock-issues#578]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
No content is loaded from this page (lots of images).  I do not see this on other sites where lots of images are loaded.  This just started with the latest update of Firefox

[Description of the bug or feature]

### A specific URL where the issue occurs
https://www.detroitnews.com/picture-gallery/sports/2017/08/13/sports-sightings-a-humorous-look-at-the-days-notable-photos/104571970/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Turned off all filters one at a time
2. [Second Step] Tried on Chrome--works in Chrome w/ uBlock
3. [and so on...] Tried new profile
4. Purged cashe, updated filters
5. Tried other ad blockers (AdBlocker Ultimate, AdGuard AdBlocker), and page content loaded

### Expected behavior:

[What you expected to happen]  Website content to load

### Actual behavior:  

[What actually happened] Just the header loads: "Sports Sightings: A humorous look at the day's notable photos
100 PHOTOS"

### Your environment 

* uBlock Origin version: uBlock Origin v1.19.2
* Browser Name and version: Firefox Quantum 66.0.5
* Operating System and version: Win10 (1809 build 17763.503), x64, 16gb,

**Comment by mapx-** [comment]
- filter issue, update your lists
- you have to report (in the future - now it's fixed) here:
https://github.com/uBlockOrigin/uAssets/issues
