### ISSUE TITLE
You can update the version of the program for Opera

### ISSUE THREAD

**Issue by OmlineEditor** [uBlockOrigin/uBlock-issues#579]
https://addons.opera.com/ru/extensions/details/ublock/ - now only 1.18.10
you have a newer one.
if it cannot be updated, is it possible to use the chrome version without problems or not?

**Comment by mapx-** [comment]
https://www.technobezz.com/install-google-chrome-extensions-opera-browser/

**Comment by gorhill** [comment]
Coincidentally I uploaded 1.19.2 a few hours ago to Opera Addon site. It needs to be accepted by Opera's reviewers.

**Comment by gorhill** [comment]
I received an email that 1.19.2 is now available in Opera Addon store.
