### ISSUE TITLE
Firefox uBlock Origin No network does not save Chinese rules

### ISSUE THREAD

**Issue by pongfcnkl** [uBlockOrigin/uBlock-issues#58]
![qq 20180605185655](https://user-images.githubusercontent.com/24273319/40972116-4cdffd7c-68f2-11e8-905b-f27a44df7be7.jpg)

**Comment by uBlock-user** [comment]
Follow the [template](https://github.com/uBlockOrigin/uBlock-issues/blob/master/.github/ISSUE_TEMPLATE.md#prerequisites) and edit your post accordingly
