### ISSUE TITLE
uBlock blocks everything http:// after today update

### ISSUE THREAD

**Issue by trumpeta** [uBlockOrigin/uBlock-issues#580]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [NO] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After today's update to latest version, all http activity in my firefox being blocked (no pages load).
Happily I have daily backups so restored my FF profile from yesterday, and the http channel was open again, until...the uBO auto-updated. By simply comparing things against backup state I see that uBO is the only addon that has newer timestamp since yesterday, so t can't be anything other. Now I disabled auto updates for uBO till the issue resolves.

Additional info not related to this bug: the recent versions of uBO don't activate on some webs at all, like turbobit.net (ie. though I have set filtering rules for these webs, uBO is completely inactive there, and even doesn't work some java functionality (eg. element picker).

Please let me know when uBO gets consolidated again so that I could peacefully update.

### A specific URL where the issue occurs

any

### Steps to Reproduce

update & browse 

### Expected behavior:

pages load

### Actual behavior:

not load

### Your environment

1.19.3.3 + ff54.0.1

**Comment by gwarser** [comment]
**ff54.0.1**

Use legacy builds.

**Comment by trumpeta** [comment]
Can you tell me where do I find legacy builds?

Thank you
