### ISSUE TITLE
Blocking the Detection of enabled Filterlists

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#581]
Feature Request not a bug.

I was over at https://browserleaks.com/ and they have a script/function that can detect which filter lists are installed/enabled.  It did not detect which ad-blocker was being used however it did detect all lists that were in use. Since this can potentially disclose which blocker is being used by the filter lists enabled, as an added security measure would make sense to block the detection of filter lists that are in use.

Not sure this is even possible but as an added feature would make ad-blocking detection a bit more difficult. 

* uBlock Origin version:  v1.19.3b6
* Browser Name and version: FF 66.0.5
* Operating System and version: Windows 10 Enterprise (1903) 18362.113

**Comment by kpcee** [comment]
That can't be fixed imho. The website tries to recognize the filter lists by checking whether certain contents are blocked, these contents are unique only in corresponding filter list. In the log window you can see how this works. If the respective element is blocked, it is assumed that the filter list XYZ is activated. 
The website cannot directly read which lists you are using.

**Comment by troysjanda** [comment]
I see your point they look for a specific filter unique to that filter list. Then there needs to be a blocking method to prevent the exposure of filters that are not actively being used to serve ads/annoyance. 

Should not be able to just detect if a specific filter, this still exposes the use of an adblocker. 

I can see this detection method being deployed to trigger the antiablock redirect or banner asking/demanding for you to disable your adblocker.  

Thinking about it seem to be a daunting task to implement or manage.  please close this bug report. should have put more though into it before submitting.

**Comment by gorhill** [comment]
Declining, not possible.

**Comment by uBlock-user** [comment]
> I was over at https://browserleaks.com/ and they have a script/function that can detect which filter lists are installed/enabled. 

Block the javascript that does the detection. Works everytime.

**Comment by gwarser** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/153
