### ISSUE TITLE
Adding csp to logger's filter expression picker 

### ISSUE THREAD

**Issue by sebast889** [uBlockOrigin/uBlock-issues#584]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Now that CSP affected requests are shown in the logger it can be a good idea to add `csp` in the logger's filter expression picker for easy hiding/showing of CSP affected requests.

**Comment by gorhill** [comment]
The `csp` type will be shown when selecting "other" -- I don't think it's worth to have a specific entry for something as rare as `csp`, there is typically only one such entry per document load, if any.
