### ISSUE TITLE
Feature Request: ublock is off by default and only the sites you specify will be blocked.

### ISSUE THREAD

**Issue by cuckoojohn** [uBlockOrigin/uBlock-issues#586]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#disabling-filtering-temporarily-or-by-default-blacklist-mode

**Comment by gorhill** [comment]
I will just quote [what I just answered on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/bqvuq2/wish_there_was_a_feature_like_adblocks_whitelist/eo8cqrs/):

> With uBO the default and sane assumption is that the internet is hostile and given this, disabling content blocking everywhere by default would be incompatible with uBO.

**Comment by Usv3re** [comment]
Damn I found it while searching for such option 😁

I want it turned off by default and to turn it on just on select few webpages
