### ISSUE TITLE
Add filter explanation/description from filter list comments

### ISSUE THREAD

**Issue by goon37** [uBlockOrigin/uBlock-issues#589]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
[Feature Request]

Some filters are confusing, for example, Fanboy's enhanced tracking list contains _exceptions_ for doubleclick.net
`@@||doubleclick.net/instream/ad_status.js`
In the logger's details about a filter (from clicking on a filter in the logger), I suggest an explanation for the filter be included. The explanation could come from **the first previous comment** in the filter list. For the above example, this would be:
`! These filters are for websites tracking and monitoring adblock users`

Explanations would also benefit filters that block websites entirely, especially from the Badware list. For example, to understand why I was blocked from www.audacity.de, the warning page could include the explanation:
`! https://github.com/uBlockOrigin/uAssets/issues/1738`
(The first previous comment in the filter list)

Obviously, not all explanations are going to make sense, but I think it would generally work. Plus, filter list authors could add/rearrange comments so that the first prior comment is a matching explanation for each filter.

**Comment by gwarser** [comment]
Also: https://github.com/uBlockOrigin/uBlock-issues/issues/475

**Comment by uBlock-user** [comment]
That's different, he's asking to add that comment in the reverse-lookup of the logger.

**Comment by gorhill** [comment]
Declined.
