### ISSUE TITLE
Permissions (Chrome)

### ISSUE THREAD

**Issue by a-ladanov** [uBlockOrigin/uBlock-issues#590]
Sorry, I don't know English. I'm new user of uBlock Origin.
uBlock has strange permissions for the browser. Why?
![ublock](https://user-images.githubusercontent.com/18179397/58234918-24888980-7d59-11e9-9472-0d19126d8ebe.png)
For example, Adguard permissions (seem logical):
![ADG](https://user-images.githubusercontent.com/18179397/58234920-281c1080-7d59-11e9-80cb-4c1d7b1ac4df.png)
Adblock Plus (seem logical):
![ABP](https://user-images.githubusercontent.com/18179397/58234927-2baf9780-7d59-11e9-9c19-36a50a5826a6.png)

**Comment by uBlock-user** [comment]
Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).
