### ISSUE TITLE
`Dashboard` open from uBO popup triggers unsaved changes dialog

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#592]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
If `Dashboard` is opened the second time by right-click uBO icon and `Options`, it is not refreshed.
If it is opened the second time from uBO popup menu, it is reloaded and unsaved changes dialog is triggered with vague message `Leave site?`.

### Steps to Reproduce

1. Open `Dashboard`
1. Make some changes in `My filters` or `My rules` panes in `Dashboard`, do not save them
1. Open `Dashboard` from uBO popup

### Your environment

* uBlock Origin version: v1.19.5b1
* Browser Name and version: 74.0.3729.169 (64-bit) 
* Operating System and version: Windows 10 v1607 x64

**Comment by uBlock-user** [comment]
I can't reproduce this on Chromium 76.

**Comment by uBlock-user** [comment]
> If Dashboard is opened the second time by right-click uBO icon and Options, it is not refreshed.

I can reproduce that.

> unsaved changes dialog is triggered with vague message Leave site?.

I cannot reproduce that.

**Comment by mikhaelkh** [comment]
@uBlock-user 
Do you have uBO dev build with unsaved changes warning? Does dashboard gets reloaded when you open it again from uBO popup, there's no need to even switch tabs, just do not close it?

**Comment by uBlock-user** [comment]
> Do you have uBO dev build with unsaved changes warning? 

Not sure I understand, I'm on the latest dev build I cannot reproduce the unsaved changes dialog.

> Does dashboard gets reloaded when you open it again from uBO popup?

Yes, but I cannot reproduce the unsaved changes dialog whatsoever.

**Comment by mikhaelkh** [comment]
@uBlock-user, make some unsaved changes that would trigger the dialog in `My rules` or `My filters` panes. Then it appears.

**Comment by uBlock-user** [comment]
> make some unsaved changes that would trigger the dialog in My rules or My filters panes. Then it appears.

Okay now I can reproduce th unsaved dialog, so what's wrong with that ? You didn't save the changes so the unsaved dialog appears when you open another instance of Dashboard. It's to be expected.

**Comment by gorhill** [comment]
>  It's to be expected.

Ideally the dashboard should just be brought up without a reload being forced.

**Comment by mikhaelkh** [comment]
Also can vague `Leave site?` message be changed to something more specific or Chrome is enforcing it?

**Comment by gorhill** [comment]
It's enforced.

**Comment by gwarser** [comment]
Edge case: opening options from Firefox `about:addons` opens new tab.

**Comment by gorhill** [comment]
Also I couldn't use `browser.runtime.openOptionsPage()` on Firefox, it kept creating new tab. Sort of related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1418617>.
