### ISSUE TITLE
Disabling push notifications on Android Firefox with uBO installed causes "clear private data" to fail on Site Settings.

### ISSUE THREAD

**Issue by dildoswaggins** [uBlockOrigin/uBlock-issues#595]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When clearing private data on Android Firefox via Settings > Clear private data, you're given various tick boxes to select/deselect as to what aspects of your data you want to clear, one of these options is for 'Site Settings'. Under normal operation when you tap on clear data with any or all of these options checked  a small pop up at the bottom says "private data cleared".

If you have uBlock Origin installed, and have disabled push notifications manually by going to about:config, searching for dom.push.enabled and toggling it to false, after a short period of time (usually less than a couple of minutes), the clear private data function starts to fail with a notice "some private data could not be cleared". I have found this only occurs if the 'Site settings' option is one of or the only ones checked in the list of options for clearing private data. If it is unchecked, private data will still clear OK.

Once this issue starts to occur, it cannot be undone without clearing the browser data from the Android settings > apps > firefox section. Even completely uninstalling uBlock Origin and turning dom.push.enabled back on do not fix the issue.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

This is not specific to any website.

### Steps to Reproduce

1. Install Firefox for Android (current latest is v67)
2. Install uBlock Origin from addons.mozzilla.org
3. Type "about:config" in the address bar to access advanced setting strings for firefox.
4. Type in dom.push.enabled to locate the string
5. Toggle it to false.
6. Try and clear private data with site settings checked. It should say "private data cleared"
6. Wait for around 2-5 minutes.
7. Try to clear private data again with site settings checked. It should now say "some private data could not be cleared."

### Expected behavior:

[What you expected to happen]
Private data should always be cleared without an error even with the site settings option checked.

### Actual behavior:

[What actually happened]
With site settings checked, private data is apparently not fully being cleared.

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox v67
* Operating System and version: Android 9.0 "Pi"

**Comment by uBlock-user** [comment]
> Even completely uninstalling uBlock Origin and turning dom.push.enabled back on do not fix the issue.

So uBO is not the cause as per that statement.

**Comment by dildoswaggins** [comment]
My bet would be something's being corrupted that isn't correctable simply by removing uBO or changing the setting back.

The fact it only occurs if uBO is installed and enabled suggests to me uBO is responsible.

**Comment by uBlock-user** [comment]
Have you tried reproducing without uBO being enabled ?

**Comment by gorhill** [comment]
Unable to reproduce, and frankly it does not make much sense to think uBO is your issue here, it's a Firefox operation for which uBO is not involved at all, there is no API for uBO to interfere with Firefox's "Clear private data".

**Comment by gorhill** [comment]
By the way, I didn't have to wait "2-5 minutes" before the operation completed, I had to wait less than a second. uBO uses indexedDB to save remote resources locally, maybe the "Clear private data" is trying to remove uBO's indexedDB but it's having a problem to do so? Even if so, your issue wouldn't be a uBO issue.

**Comment by gwarser** [comment]
There's an issue where Firefox hang on exit when clearing private data (different feature - clear on exit). May also affect manual clearing.

https://bugzilla.mozilla.org/show_bug.cgi?id=1540051

**Comment by dildoswaggins** [comment]
So, this is a fault with firefox you think? 
> 
> 
> Have you tried reproducing without uBO being enabled ?

No, had not thought of that. I tried the same steps but after installing uBO I disabled it. Problem still occurs? Odd. So perhaps it is firefox then.

> 
> 
> Unable to reproduce, and frankly it does not make much sense to think uBO is your issue here, it's a Firefox operation for which uBO is not involved at all, there is no API for uBO to interfere with Firefox's "Clear private data".

Fair enough, I don't know how any of this works as I'm not a programmer. It made sense to me from the point of view as an end-user though. Firefox completely fresh default install works fine with uBO origin also completely fresh default install. Second I change one advanced setting to false the problem occurs, if uBO isn't installed however the problem doesn't occur. Can't blame me for thinking it was uBO that caused it.

> 
> 
> By the way, I didn't have to wait "2-5 minutes" before the operation completed, I had to wait less than a second. uBO uses indexedDB to save remote resources locally, maybe the "Clear private data" is trying to remove uBO's indexedDB but it's having a problem to do so? Even if so, your issue wouldn't be a uBO issue.

I think you may have misunderstood me. I don't mean tap on clear private data and THEN wait 2 - 3 minutes, I mean you have to wait 2-3 minutes before the issue starts to occur, not after tapping on clear private data. Which is probably why you are unable to reproduce the issue.

1.install firefox leave at defaults
2.install ublock Origin also leaving at defaults.
3.When you now clear private data you get the "private data cleared" notice.
4.Now go into about:config and change dom.push.enabled to false.

If you immediately go and try clear private data it will still seem to work which is what I think you did. Instead close firefox and go do something else for 2 - 3 minutes, then when you come back and try to clear private data it will tell you that "some private data could not be cleared". Or at least that's what it does to me. If you still can't reproduce it I don't know what's going on, perhaps device specific in that case.

Either way I will open a bug with mozilla and see what they say.

**Comment by gorhill** [comment]
> have to wait 2-3 minutes before the issue starts to occur, not after tapping on clear private data.

Ok I could reproduce this way.

I removed uBO, quit the browser, and then repeated the steps and I could also reproduce the issue without uBO.
