### ISSUE TITLE
uBlock Logger - ESC key to close a subwindow with details

### ISSUE THREAD

**Issue by Conder000** [uBlockOrigin/uBlock-issues#596]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Please make the ESC key to close the subwindow with details of an entry in the uBlock Logger. Currently, its possible to close the subwindow only by mouse.

### A specific URL where the issue occurs

uBlock Logger

### Steps to Reproduce

1. Open uBlock Logger
2. Click on an entry to show details
3. Press the ESC key

### Expected behavior:

The subwindow would close after pressing the ESC key

### Actual behavior:

Nothing happens

### Your environment

* uBlock Origin version: v1.19.6
* Browser Name and version: Firefox 67.0
* Operating System and version: Windows 10

**Comment by vnctdj** [comment]
Mouse is not required: the logger window can be closed with `Ctrl + W`, the same way you close a tab.
