### ISSUE TITLE
Add option to prevent requests to localhost from remote website

### ISSUE THREAD

**Issue by ealgase** [uBlockOrigin/uBlock-issues#597]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile (all of these are irrelevant)
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There's a security issue that currently exists: websites can make requests (with Javascript) to 127.0.0.1, allowing them to scan the local computer.  There should be an option to prevent this.

### A specific URL where the issue occurs

https://wybiral.github.io/localscan/

### Steps to Reproduce

1. Have an open webserver on localhost
2. Go to https://wybiral.github.io/localscan/

### Expected behavior:

The webserver is not found because the request is blocked.

### Actual behavior:

The webserver is found.

### Your environment

* uBlock Origin version: v1.19.6
* Browser Name and version: Google Chrome 75.0.3770.42
* Operating System and version: Chrome OS

**Comment by uBlock-user** [comment]
> There should be an option to prevent this.

Just add `||127.0.0.1^$third-party`

**Comment by ealgase** [comment]
Oops, didn't realize that.  Thanks for the info.  Maybe that should be a default in uAssets?

**Comment by uBlock-user** [comment]
@ealgase https://github.com/uBlockOrigin/uAssets/issues/4318

**Comment by allo-** [comment]
The filter looks good (when the RegEx is correct, what is hard to tell for such a RegEx), but I think it misses a few things.

But it seems not to match ...

- ``0:0:0:0:0:0:0:1``
- ``2130706433`` (127.0.0.1 as integer. [Try it](http://2130706433) when running a local webserver)
- ``0.0.0.0``
- ``0``
- The Integer notation for all RFC1918 networks

It does not seem that (#4318)

> And hope for browsers to normalize to https://en.wikipedia.org/wiki/Dot-decimal_notation and not binary/octa/hexa.

holds.
