### ISSUE TITLE
ClamAV/Immunet flagging uBlock0@raymondhill.net.xpi as infected

### ISSUE THREAD

**Issue by Wakizashimaster** [uBlockOrigin/uBlock-issues#599]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://www.virustotal.com/#/file/42cc200785c6c644a557a8439e4c94e835e83ff7a7dcbf0d2b2d7a7e8a0efa88/detection

### A specific URL where the issue occurs

n/a

### Steps to Reproduce

Run Immunet with ClamAV enabled.

### Expected behavior:

Not expecting AV to identify as a virus

### Actual behavior:

AV identifies but fails to quarantine

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox Quantum 67.0  64bit
* Operating System and version: Windows 10 v 
[uBlock0@raymondhill.net.xpi.zip](https://github.com/uBlockOrigin/uBlock-issues/files/3220156/uBlock0%40raymondhill.net.xpi.zip)

1809

**Comment by mapx-** [comment]
false positive

report here:
https://www.immunet.com/false_positive

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/2315

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Software-known-to-have-uninstalled-uBlock-Origin
