### ISSUE TITLE
HTML filter exception doesn't work.

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#6]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`google.*,~www.google.com##^*` exception doesn't work for any subdomain too.

### A specific URL where the issue occurs

www.google.com

### Steps to Reproduce

1. Add a filter `google.*,~www.google.com##^*` 

### Expected behavior:

Working exceptions.

### Actual behavior:

Not working exceptions.

### Your environment

* uBlock Origin version: 1.16
* Browser Name and version: Firefox 59.0,2
* Operating System and version: Windows 10 1709

**Comment by gorhill** [comment]
Exceptions are still TODO: <https://github.com/gorhill/uBlock/blob/ec29c9a127342f6d250c41572017329c45aca0e5/src/js/html-filtering.js#L236>.

**Comment by isowhe** [comment]
@gorhill OK then. It's just that exceptions are working with mozilla.org, not quite right though, i need to refresh one time to access it.

**Comment by uBlock-user** [comment]
Closing this until actual use case are brought up as per gorhill's request.

**Comment by gorhill** [comment]
It can be kept opened, as it is definitely a TODO, I even wrote it in the code. It's just not a priority to fix for now.

**Comment by in4u** [comment]
@gorhill I was going to post new issue but a quick search turned this up showing it as fixed. Is the syntax for HTML filter exceptions same as that for cosmetic ones, like `#@#`? I tried but it's not working for me.

**Comment by gwarser** [comment]
Fixed in beta

![image](https://user-images.githubusercontent.com/886325/48619702-a27c6a00-e99d-11e8-9002-ce875af077da.png)

>Is the syntax for HTML filter exceptions same as that for cosmetic ones, like #@#?

Yes

**Comment by in4u** [comment]
Ah, alright. Thanks @gwarser for pointing that out! I have one more question. Going by the wiki, HTML filters sound conceptually awesome. But what's the catch? How do they compare against regular cosmetic filters in terms of speed, performance and efficiency? Is there any reason to prefer non-HTML filters over HTML ones if the browser supports them?

**Comment by uBlock-user** [comment]
> How do they compare against regular cosmetic filters in terms of speed, performance and efficiency?

It relies on Response data API which is only available in Firefox 57+ atm.

**Comment by in4u** [comment]
Yes @uBlock-user, that's why my question was only for the case when browser supports both.

**Comment by in4u** [comment]
@gorhill Does the removal cause any performance hit or delay or some other problem except breaking things? If I have a list of cosmetic rules which don't break anything (and have the exact same blocking result) by converting them into HTML filters, which should I prefer - HTML or non-HTML filters?

**Comment by gorhill** [comment]
Frankly, only profiling would provide an evidence-based answer to this (or at least to the one scenario your are profiling). My intuition for the specific case you bring is that cosmetic filtering would be better -- but as said, it's my intuition, profiling could prove me wrong.

**Comment by in4u** [comment]
Hmmm... okay thanks @gorhill, for the time being I'll stick to non-HTML filters as per your recommendation for my use case. But please do update the wiki as and when new information / profiling result is available.

**Comment by garry-ut99** [comment]
It doesn't work again.

**Comment by gorhill** [comment]
It's just the browser which seems to be waiting for more data after it receives a response with just `<DOCTYPE html>`, as would be expected when removing all elements. `google.*,~www.google.com##^body` preserves the `head` tag and this way the browser is not fooled into waiting forever.

Regarding the issue filed here, as per comment in code, I never implemented negated domain names (what was fixed above was exception filters `#@#^`):

https://github.com/gorhill/uBlock/blob/cdc566cc32268d7669f6b3fb4f8be95912f777e2/src/js/html-filtering.js#L337-L339
