### ISSUE TITLE
Dropdown is not rendering properly , Cannot click any button of dropdown and myfilter is also not working

### ISSUE THREAD

**Issue by iamsauravsharma** [uBlockOrigin/uBlock-issues#60]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

ublock is not rendering properly as well as my filter is not working at all. It works for only one time and render properly when i disable and enable ublock and again click to open dropdown. When i totally close my Firefox nightly browser and reopen browser than same problem re arrives and my filter stops to work and they do not render properly at all. as well as i cannot click any button of dropdown as shown in image below

![screenshot 4](https://user-images.githubusercontent.com/38726015/41089503-ac0843e8-6a61-11e8-9aca-bfe41698759b.png)

### A specific URL where the issue occurs

Actually this is problem of ublock dashboard but incase of my filter. My filter is not working for youtube.com as well as facebook.com

### Steps to Reproduce

1. Close browser which has uBlock installed
2. Open browser with same profile
3. Open dropdown
4. Click any button in dropdown as well as see rendering of dropdown

### Expected behavior:

Dropdown is rendering properly and my filter is working as well as able to click dropdown button

### Actual behavior:

Dropdown not rendering properly and my filter not working as well as cannot click any button

### Your environment

* uBlock Origin version:1.16.8
* Browser Name and version: Firefox nightly 62.0.a1 (2018-06-06) 
* Operating System and version: Windows 10 Home 1803 (17134.48)

**Comment by uBlock-user** [comment]
You mean that popup UI ? I cannot reproduce, renders fully on my end on Nightly.

**Comment by uBlock-user** [comment]
Firefox nightly `62.0.a1 (2018-06-05)` is the last working build, get that if you can.

**Comment by gorhill** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1467136

**Comment by uBlock-user** [comment]
Workaround -- Disabled the extensions and enable it back and it will render normally.

**Comment by gwarser** [comment]
Workaround, set about:config `extensions.webextensions.background-delayed-startup` to false

**Comment by gorhill** [comment]
It's fixed on my side with latest Nightly -- 62.0a1 (2018-06-07)

**Comment by uBlock-user** [comment]
@iamsauravsharma Force update Nightly to the latest update.

**Comment by nc-lee** [comment]
This is happening for me on FireFox 75 for Mac. @iamsauravsharma are you still getting this?

**Comment by gorhill** [comment]
I use Nightly and uBO works fine. Try with uBO only, disable other extensions, restart Nightly. If that does not work, reinstall uBO after optionally creating a backup of your settings).
