### ISSUE TITLE
Show punycode more clearly

### ISSUE THREAD

**Issue by lowven** [uBlockOrigin/uBlock-issues#601]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

When I test on http://raymondhill.net/ublock/idn-tricks.html and look in advanced pane the international root domains correctly have the IDN symbols. But if you click +all to show subdomains it is not that clear. Unlike jquery.com (mimicry) api.jquery.com (mimicry) shows as api.jquery.com under jquery.com (mimicry) but with no IDN symbol or hover text showing the real IDN domain name (api.xn-qur-sdd5e5f.com). It should show these for subdomains too to avoid confusion.

Also, try creating some dynamic filters from advanced pane for both api.jquery.com (real) and api.jquery.com (mimicry) and then go to My Rules. There are 2 rules that are almost visually identical as api.jquery.com but they are different rules. It should instead create 2 rules that should be visually different, 1 as api.query.com (real) and the other api.xn-qur-sdd5e5f.com (mimicry).

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox 69
* Operating System and version: Mac

**Comment by gorhill** [comment]
I don't see the point of redundantly showing an IDN issue for subdomains when it's clearly shown for the base domain.

**Comment by lowven** [comment]
My opinion punycode should show for subdomains because when clicking new rules from popup not every time people are paying attention to the base domain especially when there are many subdomains and +all is toggled. But oky it's your choice.

They should be visually different in dynamic rules. There it is not clear at all.

**Comment by gorhill** [comment]
I am going to give more thoughts to this before I decide.
