### ISSUE TITLE
Logger doesn't show DOM entries when `:style()` exceptions added

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#602]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### A specific URL where the issue occurs
https://en.myshows.me/search/all/

### Steps to Reproduce

1. Add `Ru AdList` Filter list
1. Open logger, toggle dom filtering
1. Go to https://en.myshows.me/search/all/
    * `.adsbygoogle` is present in logger
1. Add to My Filters
`myshows.me#@#body:not(#id):style(background-image: none !important)`
`myshows.me#@#html:not(#id):style(background-image: none !important)`
1. Go to https://en.myshows.me/search/all/
    * dom entries are absent in logger

### Expected behavior:

At step 5 there should be all 3 mentioned filters in logger

### Actual behavior:

At step 5 there are 0 mentioned filters in logger

### Your environment

* uBlock Origin version: uBlock Origin development build v1.19.7b2
* Browser Name and version: Chromium 74.0.3729.169 (64-bit)
* Operating System and version: Windows 10 v1607 x64

**Comment by gwarser** [comment]
>.adsbygoogle in present in logger

Not always:

![image](https://user-images.githubusercontent.com/886325/58431162-d226d000-80ac-11e9-89ce-46fe369b3737.png)

**Comment by mikhaelkh** [comment]
@gwarser, enable all non-regional + `Ru AdList` + `AdGuard Russian`, there should be a lot more dom entries in logger. Some of them are from EasyList and probably should've been present before.

**Comment by gorhill** [comment]
`.adsbygoogle` is probably a bait element, as the site uses fuckadblock script -- and so quite probably related to <https://github.com/uBlockOrigin/uBlock-issues/issues/521>, short-lived DOM elements matching cosmetic filters may not be reported in the logger.

As for the `:style(...)` exceptions, I need to investigate -- not sure there is code to report exception `:style(...)` filters.

**Comment by gwarser** [comment]
I don't think it's bait because I see it in the DOM in dev tools all the time.

**Comment by gorhill** [comment]
Ok, I see errors in the dev console from cosmetic logger scriptlet.

**Comment by gwarser** [comment]
"dom" entries are completely missing when when looking on the logger which is opened in tab or just when page tab is not visible. Looks like Chrome optimization, because page is re-rendered after switching to its tab and then all "dom" entries appear in logger at once.

**Comment by uBlock-user** [comment]
> "dom" entries are completely missing when when looking on the logger which is opened in tab or just when page tab is not visible. 

When the website page is in background and when you're looking at the logger ? I think that's by-design. If the page is in background, then cosmetic filters won't get applied until the page is no longer in background and gets unloaded.

**Comment by gorhill** [comment]
> Looks like Chrome optimization

Couldn't this be related to the new Chromium feature about suspended tabs?

**Comment by uBlock-user** [comment]
It's not a new behaviour if that's what you're suggesting, I have known and reproduced that behaviour since the beggining. If the page is in background, the cosmetic filters won't appear in the logger.

**Comment by gorhill** [comment]
Ok it's a side-effect of uBO using `requestAnimationCallback` -- which will throttle itself according to whether a web page is visible or not. I consider this to be a virtuous side-effect in uBO, as this will throttle make uBO's content scripts. Imagine someone loading many tabs at once (a common scenario when launching the browser), and thus it's best that uBO does not perform work which is not going to be useful unless the page is visible. Note that ultimately there is a 20 seconds timeout if the callback has not been fired by the browser, to prevent huge built-up of tasks. So if you wait 20 seconds, eventually the logger will start to report the cosmetic filters.

**Comment by uBlock-user** [comment]
But why doesn't this happen in Firefox then ?

> Note that ultimately there is a 20 seconds timeout if the callback has not been fired by the browser, to prevent huge built-up of tasks. So if you wait 20 seconds, eventually the logger will start to report the cosmetic filters.

It did. I just tested your logic on `https://screenrant.com/` and it reported exactly at the 20th second.

**Comment by gorhill** [comment]
> why doesn't this happen in Firefox then ?

Probably implementation-dependent.

**Comment by gwarser** [comment]
> Note that ultimately there is a 20 seconds timeout if the callback has not been fired by the browser, to prevent huge built-up of tasks. So if you wait 20 seconds, eventually the logger will start to report the cosmetic filters.

Not always happens. Sometimes it starts working after 20-30 seconds, but most of the time nothing happens for minutes.

**Comment by gorhill** [comment]
> most of the time nothing happens for minutes.

Well the thing is uBO does request a callback. If the browser honors it later than sooner, it's a browser by-design behavior. There is the `requestAnimationFrame` behavior, there is also the suspended tabs behavior and whatever else we may not know. For me what matters is that uBO is considerate and does not try to bypass the browser's throttling behavior to selfishly hog CPU cycles when not dealing with critical work.
