### ISSUE TITLE
A subdomain of our site is being blocked but never serves ads

### ISSUE THREAD

**Issue by jerclarke** [uBlockOrigin/uBlock-issues#603]
I'm sorry to put this here but couldn't find any info about this on your website or in the wiki.

It would be great if there was an up-front indication of what we should do if your extension is blocking (in my case breaking) parts of our websites. If the answer is there's nothing to be done, then still please have an FAQ somewhere that helps us get to that conclusion. 

I'm still diagnosing exactly what is going wrong, but it seems that my users who run uBlock have fatal JS errors on the site, but there's never any advertising on the site. 

Right now it seems to be a JS library called Riveted: https://riveted.parsnip.io/

Is that blocked by uBlock?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues
