### ISSUE TITLE
uBlock Origin for Microsoft Edge Chromium

### ISSUE THREAD

**Issue by gdata1** [uBlockOrigin/uBlock-issues#605]
Hello. Since yesterday I do not see uBlock Origin in the store extensions for edge. Whether further development is planned under the new edge. It is already in open testing and works well. I use it.

**Comment by gwarser** [comment]
I still see it here: https://microsoftedge.microsoft.com/insider-addons/detail/odfafepnkmbhccpbejgmiehpchacaeak

And AFAIK Chrome version should work just fine: https://github.com/nikrolls/uBlock-Edge/issues/130#issuecomment-491547388

**Comment by gdata1** [comment]
For some reason I didn't see it on the Edge Insider page

**Comment by kowith337** [comment]
If you want to use early, you may need to sideload with same method as you can install via dev mode or via command line arguments.

And yes, chrome version are directly compatible with new chromium edge.
