### ISSUE TITLE
Allow disabling of hosts blocking

### ISSUE THREAD

**Issue by r-salvaterra** [uBlockOrigin/uBlock-issues#606]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Just a suggestion, it would be nice if it would be possible to disable blocking of hosts, in addition to cosmetic filters (something like "Parse and enforce host filters"). Some people might do DNS-based hosts blocking (Pi-hole, OpenWrt adblock, AdGuard DNS), and this would reduce the number of network filters quite a bit.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

N/A

### Expected behavior:

N/A

### Actual behavior:

N/A

### Your environment

* uBlock Origin version: 1.19.7rc0
* Browser Name and version: Firefox 67
* Operating System and version: Ubuntu MATE 19.04

**Comment by gorhill** [comment]
Just unselect the lists in the "Filter lists" pane.

**Comment by r-salvaterra** [comment]
Well, obviously, but that doesn't disable host filters inside other lists, if present (i.e. ||example.com^), does it?

**Comment by gorhill** [comment]
> disable host filters inside other lists, if present (i.e. ||example.com^)

If this is your feature request, I prefer to decline.

**Comment by kulfoon** [comment]
Considering there is [a bug](https://github.com/uBlockOrigin/uBlock-issues/issues/1003) in uBO , I wanted to ask what is difference between `example.com` and `||example.com^` rules.
