### ISSUE TITLE
please clarify in #338 how you interpret "enterprise deployments"

### ISSUE THREAD

**Issue by bughit** [uBlockOrigin/uBlock-issues#607]
@gorhill 

> [though blocking will still be available to enterprise deployments](https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/veJy9uAwS00/9iKaX5giAQAJ)

The [enterprise chrome bundle](https://cloud.google.com/chrome-enterprise/browser/download/) is just the the normal chrome offline installer wrapped in an msi, bundled with group policy templates.

Which suggests there will be a [policy](https://www.chromium.org/administrators/policy-list-3) that enables webRequest blocking. Although they do have an ability to limit policies to domain joined machines (on windows).

Is that how you see it? If not, what is your interpretation?

**Comment by jspenguin2017** [comment]
Chrome Enterprise is normal Chrome but logged in with a G Suite account.

**Comment by phiresky** [comment]
@gorhill In general, it would be great if you could publish a statement about what you think of this (that comment is nice, but it requires some context and it seems like this change will impact pretty much everyone)

**Comment by Tatsh** [comment]
>I'm not sure if you can apply policies without a G Suite account though, I never tried.

All policies are located under `chrome://policy/` (click on *Show policies with no value set*). These can be set locally. On macOS they can be set using the `defaults` command so that the browser will say that it is 'managed by your organisation' (Windows: registry, Linux: some JSON file).

This doesn't mean we have a solution for the future.

**Comment by uBlock-user** [comment]
I have re-opened #338 so you can post that question there, but stay on topic, offtopic arguments and questions is what led to have that issue locked in the first place.
