### ISSUE TITLE
Prompt Google Chrome users to switch to another browser

### ISSUE THREAD

**Issue by nsuchy** [uBlockOrigin/uBlock-issues#609]
As many of you are aware, uBlock Origin will be breaking in the near future on Google Chrome based browsers unless significant breaking changes (specifically to the privacy enhancing features) are made to the extensions. On Google Chrome it's time to start prompting users with an explanation that uBlock Origin is going to stop working for them due to changes outside of our control by Google and that they should switch away from Google Chrome to a another browser (I believe we should recommend Brave and Firefox, that's something that'll need more discussion). Unless we're going to make uBlock Origin less useful to Google Chrome users, we have no option but asking them to switch and to forgive us for being unable to serve them while they use Google Chrome.

I don't want this to become yet another a political thread discussing Google's motives or how they're evil, we've seen it already, and there's already plenty of that in https://github.com/uBlockOrigin/uBlock-issues/issues/338. This thread is for discussing implementing a feature that's necessary in uBlock Origin, please keep it on topic!

**Comment by uBlock-user** [comment]
Gorhill already spoke his mind -- https://github.com/uBlockOrigin/uBlock-issues/issues/338#issuecomment-456179825

Please don't open any such issues regarding #338
