### ISSUE TITLE
"The data could not be read or is invalid" upon restore of backup filed

### ISSUE THREAD

**Issue by trumpzombiecult** [uBlockOrigin/uBlock-issues#61]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

uBO v1.16.8 on Chrome v66.0.3359.139 on Win7

Files that will not restore:

https://drive.google.com/open?id=1JNrgr_DmrsylBqNZKuOqNddDmkwG70AA

https://drive.google.com/open?id=1d9Zg5qeBxZrgMu-zFYDKAMyKnwZuWWqE

**Comment by trumpzombiecult** [comment]
uBO v1.16.8 on Chrome v66.0.3359.139 on Win7

Files that will not restore:

https://drive.google.com/open?id=1JNrgr_DmrsylBqNZKuOqNddDmkwG70AA

https://drive.google.com/open?id=1d9Zg5qeBxZrgMu-zFYDKAMyKnwZuWWqE

**Comment by uBlock-user** [comment]
Static Filters are to be imported via the _Import and Append_ button located at _My Filters_ page.

**Comment by trumpzombiecult** [comment]
oh

thanks

cheers
