### ISSUE TITLE
Does not block large media fetched over Fetch API

### ISSUE THREAD

**Issue by Scrxtchy** [uBlockOrigin/uBlock-issues#610]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The foilLargeMediaElement function is only tracking [media and image](https://github.com/gorhill/uBlock/blob/f103cc6aa727a9e9e0d64cabc3b29e119257d2a1/src/js/traffic.js#L443) requests, but some pesky programmers are putting these behind Fetch requests.
![image](https://user-images.githubusercontent.com/12771982/58683775-1a016c00-83b9-11e9-91ff-334f2a92ee24.png)

Fortunately, these can also return Mime Types, which may be acceptable for filtering out content. But I am not sure how this can impact overall performance 

### A specific URL where the issue occurs

https://dev.to/wunk/fast-base2-decoding-on-the-upcoming-intel-icelake-1mk1

### Steps to Reproduce

1. Enable Large Content Filtering (I use 5000kb)
2. Navigate to URL
3. Watch Content be downloaded via network or on page

### Expected behavior:

Large media should not be loaded by ublock foiling it

### Actual behavior:

Large media element is not detected by ublock

### Your environment

* uBlock Origin version: uBlock Origin 1.19.7rc0
* Browser Name and version: Firefox 68.0b5 (64-bit)
* Operating System and version: Win10 1903

**Comment by uBlock-user** [comment]
Did you look at the logger ? 

![](https://i.gyazo.com/89dcdb0bc7e30d9bd201dfd590c884d9.png)

![](https://i.gyazo.com/f402bb44edc3cb0a77409a5e6e6ad0d5.png)

**Comment by Scrxtchy** [comment]
I did and nothing interesting showed up.

Restarted my browser since you were getting a different result than I was. 
Seems to have done the job... somehow

![image](https://user-images.githubusercontent.com/12771982/58685551-7cf60180-83bf-11e9-918d-30dc3469d2c8.png)

**Comment by uBlock-user** [comment]
@Scrxtchy A connection is made to the server to receive `Content-Length` response header to match the length(5000 kB in your case set by you) and then blocked, this is why it appears that the image in Network tab of devtools, but the image is never download in reality.

**Comment by Scrxtchy** [comment]
Hold on.
As soon as I clicked the close button I thought, maybe if I refresh it, something weird would happen.
And it did

I disabled the media filter to put the image request back into cache.
Enabled it again, refreshed so that ublock will affect the request.
Then Refreshed the page, of when the image did load
![image](https://user-images.githubusercontent.com/12771982/58685693-eaa22d80-83bf-11e9-9e9d-7e63b1003aff.png)

**Comment by uBlock-user** [comment]
> I disabled the media filter to put the image request back into cache.
Enabled it again, refreshed so that ublock will affect the request.
Then Refreshed the page, of when the image did load

Yes, now the image is loading from the cache, for which uBlock cannot block, so do a cache-free reload again and the it will not appear.

**Comment by Scrxtchy** [comment]
The image is loaded externally when loading through a regular refresh as it's requested through an XHR, bypassing ublock.
But the cache refresh clears all this, as the item is then loaded back without javascript using the <img> element, which ublock will indeed block
![image](https://user-images.githubusercontent.com/12771982/58686083-1c67c400-83c1-11e9-8aa2-383f7d970929.png)

**Comment by uBlock-user** [comment]
> as it's requested through an XHR, bypassing ublock.

Does the XHR have `Content-Length` response header ? If not, this will happen.

**Comment by Scrxtchy** [comment]
It does
![image](https://user-images.githubusercontent.com/12771982/58686218-8f713a80-83c1-11e9-874b-2e2f29635880.png)

**Comment by uBlock-user** [comment]
I have updated my comment as only `image` and `media` type requests are affected by the size setting

**Comment by Scrxtchy** [comment]
> 
> 
> I have updated my comment as only `image` and `media` type requests are affected by the size setting

Yeah, github hadn't sent me the updated comment by the time I read it. I did also have a reference to this in the opening post

**Comment by uBlock-user** [comment]
> The image is loaded externally when loading through a regular refresh as it's requested through an XHR, bypassing ublock.

I cannot reproduce that though, only end, it's always seen as `image` type.

**Comment by gwarser** [comment]
Probably service worker.

**Comment by uBlock-user** [comment]
@gwarser Can you reproduce images getting fetched via XHRs ?

**Comment by gwarser** [comment]
Yes, service worker is doing this. Even if you block them by `.gif$image`, on next load they return as `xhr`. Weird thing is: images disappear after being fully(?) downloaded (I see transfer in network monitor).

**Comment by gorhill** [comment]
> images disappear after being fully(?) downloaded

I don't see it being fully downloaded on my side the first time -- when it's fetched as a `ìmage` resource. I do see it fully downloaded when it's fetched as a `xhr` through the service worker.

**Comment by gorhill** [comment]
For the fix to take effect, be sure to unregister the appropriate service worker from `about:serviceworkers`. Once the service worker is gone, uBO will properly filter large media elements. However, if you allow large media elements on the page, temporarily or not, toggling back the setting won't block the large media elements that have been successfully downloaded. I suspect they are cached somewhere by the service worker, and won't be filtered until the service worker is terminated.

**Comment by gwarser** [comment]
Does it work for all of you? Does not for me. And even looks bit insane.

- Firefox 68.0b6
- Large media limit set to 500kB
- on first load all seems to be ok except this 'doc' request appearing out of nowhere after some delay:

![image](https://user-images.githubusercontent.com/886325/58728479-459b4b00-83e7-11e9-8cfd-2398b9827957.png)

- on second load:

![image](https://user-images.githubusercontent.com/886325/58728583-84310580-83e7-11e9-9fb3-36c95c42829e.png)

(Sorting is inverted, fetch should be first:)
![image](https://user-images.githubusercontent.com/886325/58728666-a9be0f00-83e7-11e9-87d6-0ebc30445c38.png)
Images load for few dozens seconds (0.5Mbit), I see them on the screen, and then they disappear, and:
![image](https://user-images.githubusercontent.com/886325/58728682-b6dafe00-83e7-11e9-9db9-696f7babf5cd.png)

**Comment by gorhill** [comment]
From your second logger screenshot, I gather that the `xhr` requests were not tabless? The fix applies only to tabless requests of type `xhr`.

**Comment by gorhill** [comment]
I can reproduce with Nightly, I had tested with Firefox 67. I see a `xhr` request in the logger which is not tabless, I will need to investigate more.

**Comment by gorhill** [comment]
Not sure about these changes, I will keep them here until I make a decision and after further code review (instead of stashing the changes locally and loosing track of them):

<details><summary>Patch</summary>

```diff
diff --git a/src/js/pagestore.js b/src/js/pagestore.js
index 57b899bec..49aff4b4c 100644
--- a/src/js/pagestore.js
+++ b/src/js/pagestore.js
@@ -904,11 +904,16 @@ const PageStore = class {
         if ( this.allowLargeMediaElementsUntil === 0 ) {
             return 0;
         }
+        // https://github.com/uBlockOrigin/uBlock-issues/issues/1624
+        //   We normalize to `blob:` for xhr-based media requests
+        const mediaURL = fctxt.itype !== fctxt.XMLHTTPREQUEST
+            ? fctxt.url
+            : 'blob:';
         // Disregard large media elements previously allowed: for example, to
         // seek inside a previously allowed audio/video.
         if (
             this.allowLargeMediaElementsRegex instanceof RegExp &&
-            this.allowLargeMediaElementsRegex.test(fctxt.url)
+            this.allowLargeMediaElementsRegex.test(mediaURL)
         ) {
             return 0;
         }
@@ -916,7 +921,7 @@ const PageStore = class {
             const sources = this.allowLargeMediaElementsRegex instanceof RegExp
                 ? [ this.allowLargeMediaElementsRegex.source ]
                 : [];
-            sources.push('^' + µb.escapeRegex(fctxt.url));
+            sources.push('^' + µb.escapeRegex(mediaURL));
             this.allowLargeMediaElementsRegex = new RegExp(sources.join('|'));
             return 0;
         }
diff --git a/src/js/scriptlets/load-large-media-interactive.js b/src/js/scriptlets/load-large-media-interactive.js
index 12fa3432b..953e5fd3a 100644
--- a/src/js/scriptlets/load-large-media-interactive.js
+++ b/src/js/scriptlets/load-large-media-interactive.js
@@ -132,16 +132,26 @@ if ( vAPI.largeMediaElementStyleSheet === undefined ) {
 
 const loadMedia = async function(elem) {
     const src = elem.getAttribute('src') || '';
-    elem.removeAttribute('src');
+    const isBlob = src.startsWith('blob:');
+
+    if ( isBlob === false ) {
+        elem.removeAttribute('src');
+    }
 
     await vAPI.messaging.send('scriptlets', {
         what: 'temporarilyAllowLargeMediaElement',
     });
 
-    if ( src !== '' ) {
-        elem.setAttribute('src', src);
+    if ( isBlob === false ) {
+        if ( src !== '' ) {
+            elem.setAttribute('src', src);
+        }
+        elem.load();
+    }
+
+    if ( isBlob ) {
+        elem.play();
     }
-    elem.load();
 };
 
 /******************************************************************************/
diff --git a/src/js/traffic.js b/src/js/traffic.js
index 0f383aa0d..11bb3a76f 100644
--- a/src/js/traffic.js
+++ b/src/js/traffic.js
@@ -503,17 +503,21 @@ const onHeadersReceived = function(details) {
     }
     if ( pageStore.getNetFilteringSwitch(fctxt) === false ) { return; }
 
-    if ( fctxt.itype === fctxt.IMAGE || fctxt.itype === fctxt.MEDIA ) {
-        const result = foilLargeMediaElement(details, fctxt, pageStore);
-        if ( result !== undefined ) { return result; }
-    }
-
     // Keep in mind response headers will be modified in-place if needed, so
     // `details.responseHeaders` will always point to the modified response
     // headers.
     const { responseHeaders } = details;
     if ( Array.isArray(responseHeaders) === false ) { return; }
 
+    // https://github.com/gorhill/uBlock/issues/1390#issuecomment-187310719
+    //   Do not foil when the media element is fetched from the browser
+    //   cache. This works only when the webext API supports the `fromCache`
+    //   property (Firefox).
+    if ( details.fromCache !== true && isMediaElement(fctxt, responseHeaders) ) {
+        const result = foilLargeMediaElement(fctxt, responseHeaders, pageStore);
+        if ( result !== undefined ) { return result; }
+    }
+
     if ( isRootDoc === false && µb.hiddenSettings.filterOnHeaders === true ) {
         const result = pageStore.filterOnHeaders(fctxt, responseHeaders);
         if ( result !== 0 ) {
@@ -1037,42 +1041,40 @@ const foilFloc = function(fctxt, responseHeaders) {
 
 // https://github.com/gorhill/uBlock/issues/1163
 //   "Block elements by size".
-// https://github.com/gorhill/uBlock/issues/1390#issuecomment-187310719
-//   Do not foil when the media element is fetched from the browser
-//   cache. This works only when the webext API supports the `fromCache`
-//   property (Firefox).
-
-const foilLargeMediaElement = function(details, fctxt, pageStore) {
-    if ( details.fromCache === true ) { return; }
 
+const foilLargeMediaElement = function(fctxt, headers, pageStore) {
     let size = 0;
     if ( µBlock.userSettings.largeMediaSize !== 0 ) {
-        const headers = details.responseHeaders;
         const i = headerIndexFromName('content-length', headers);
         if ( i === -1 ) { return; }
         size = parseInt(headers[i].value, 10) || 0;
     }
-
     const result = pageStore.filterLargeMediaElement(fctxt, size);
     if ( result === 0 ) { return; }
 
     if ( µBlock.logger.enabled ) {
         fctxt.setRealm('network').toLogger();
     }
-
     return { cancel: true };
 };
 
+const isMediaElement = function(fctxt, headers) {
+    if ( fctxt.itype === fctxt.IMAGE ) { return true; }
+    if ( fctxt.itype === fctxt.MEDIA ) { return true; }
+    if ( fctxt.itype !== fctxt.XMLHTTPREQUEST ) { return false; }
+    return /^(?:audio|image|video)\//.test(
+        headerValueFromName('content-type', headers)
+    );
+};
+
 /******************************************************************************/
 
 // Caller must ensure headerName is normalized to lower case.
 
 const headerIndexFromName = function(headerName, headers) {
-    let i = headers.length;
-    while ( i-- ) {
-        if ( headers[i].name.toLowerCase() === headerName ) {
-            return i;
-        }
+    const n = headers.length;
+    for ( let i = 0; i < n; i++ ) {
+        if ( headers[i].name.toLowerCase() === headerName ) { return i; }
     }
     return -1;
 };
```
</details>

**Comment by gorhill** [comment]
Assuming fixed since commits were made above. Anything else, open a new issue.
