### ISSUE TITLE
uBo translate pre:not(> span) to pre:not(:has(> span))?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#612]
> uBo translate `##pre:not(> span`)  to `##pre:not(:has(> span))` / `##pre:if-not(> span)`?

### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This is new feature? 

Now in CSS no possible use in `:not(...)`:
* "path"
* ~~selectors~~ combinators
* mixed "name" element selector (e.g. nightmare `SPAN#id.class[attrib]`)

_I exclude progress in webkit Safari (Apple). <br> Where now in dev version possible use ~~selectors~~ combinators for `not`?_

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/612

###### Demo tester:

> <table> <tr><td>
> 
> ```css
> form input {
>     filter: none
> }
> ```
> 
> </td><td>
> 
> ```
> form input {
>     filter: none
> }
> ```
> 
> </td></tr></table>

###### test with element picker:

`##blockquote > table pre:not(> span)` 
`##blockquote > table pre:not(:has(> span))`
`##blockquote > table pre:if-not(> span)`
`##blockquote > table pre:has(:not(> span))`

### Steps to Reproduce

1. Open this issue on PC
2. try block second pre (embedded in the table) with 4 demo filters with element picker
3. first and fourth maybe is invalid (or too feautre now)

### Expected behavior:

marked as invalid first and fourth consturction?

### Actual behavior:

marked as ivalid first and fourth consturction.

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox 67
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
All appear valid for me.

**Comment by krystian3w** [comment]
I apologize in advance for typos, English is not my good side and it is not time for logical thinking (it's time to go to sleep for my brain / mind).

**Comment by gorhill** [comment]
That is normal behavior. If the `:not` operator is used with a valid CSS argument, it will be used as is, if not, `:not()` will be parsed as a procedural filter.

**Comment by krystian3w** [comment]
so this why not translated to JavaScript:

`##blockquote > table pre:not(span[class])` to:

 `##blockquote > table pre:if-not(span[class])` 
`##blockquote > table pre:not(:has(span[class]))`

**Comment by gorhill** [comment]
uBO won't interfere with your filter editing -- it can't read your mind to find out exactly what you intend.

Internally it will ensure that your filter works as intended by normalizing to a working form.

**Comment by gwarser** [comment]
> > if not, `:not()` will be parsed as a procedural filter.
> 
> so why this `##blockquote > table pre:not(span[class])` is not translated **now** to JavaScript (procedural filtering):


Picker tells it's invalid, but `##blockquote > table pre:not(span)` is ok.

I don't get it, `pre` cannot be `span`, but it's valid, yet `pre:not(span[class])` is not.
![image](https://user-images.githubusercontent.com/886325/58747099-a4ec7000-8466-11e9-963a-c78b752de351.png)

It's because:

>Useless selectors can be written using this pseudo-class. For example, :not(*) 
https://developer.mozilla.org/en-US/docs/Web/CSS/:not


And! 

> Note: In Selectors Level 3, only a single [simple selector](https://drafts.csswg.org/selectors-4/#simple) was allowed as the argument to [:not()](https://drafts.csswg.org/selectors-4/#negation-pseudo).

>A simple selector is a single condition on an element.

But why is not uBO falling back to procedural selector in this case?

Because when compiling, parameter to `:not` is checked for validity, and `span[class]` is valid (by https://github.com/gorhill/uBlock/commit/d3a3505a54678413b6975cd87c63c59336447677#diff-1c951eedcd0be2e11c02da8fabcc46b5R221). 

Hmmm cannot full `:not` be checked for validity in this case? In `compileNotSelector`?

**Comment by gorhill** [comment]
Hmm I didn't understand well the answer yesterday, I had assumed `##blockquote > table pre:not(span[class])` but @krystian3w wanted uBO to present in the text area the final form. Now I just tried it and it does indeed return an error. I will have to investigate.

**Comment by gwarser** [comment]
This particular selector does not look very useful, but maybe `##blockquote > table *:not(span[class])`?

Also logger does not report this filters as invalid.

**Comment by gorhill** [comment]
> But why is not uBO falling back to procedural selector in this case?

Isn't a case where the proper way to write the filter is:

    pre:not(:has(span[class]))

I don't think it would be right to assume `pre:not(span[class])` should be interpreted as `pre:not(:has(span[class]))`.

**Comment by gorhill** [comment]
I am going to decline doing anything here. If the argument to `:not()` is a valid CSS selector, the `:not()` will be deemed part of a valid CSS selector, otherwise uBO will take over the `:not()`. In the current case, it's just a matter of writing `##blockquote > table *:not(span):not([class])`.

**Comment by krystian3w** [comment]
I just wanted to know why simplification with combinators works:

`##blockquote > table pre:not(> span)`
`##blockquote > table pre:not(~ span)`
`##blockquote > table pre:not(+ span)`

AdGuard ommit this and still recommend add `:has()` into brackets.

**Comment by gorhill** [comment]
Because internally `> span`, `~ span` and `+ span` are converted into a procedural `:spath()` operators internally, they are invalid CSS selector on their own **and** establish a relation with the context (`pre` in the current case) element. On the other hand, `span[class]` is a valid CSS selector and no relation is being established relative to the context element.

**Comment by gorhill** [comment]
Note that although `pre:not(> span)` works, `pre:not(:scope > span)` does not, but `pre:not(:has(:scope > span))` does work.

The difficulty here is to be able to guess what the user wants really. uBO first just try to find out whether the argument is a valid CSS selector according to the browser, and if not it will try to create a procedural operator from it.

- `> span`: not a valid CSS selector and the picker tries to create a procedural operator our of it.
- `:scope > span`: valid CSS selector, so uBO does not try to create a procedural operator out of it.
- `:has(:scope > span)`: not a valid CSS selector and the picker tries to create a procedural operator our of it.

In the end, filter authors just have to avoid ambiguity by explicitly using `:has()`, this way this result in using native `:not()` for present and future as much as possible.
