### ISSUE TITLE
Chrome extension was corrupt, clicked `repair` and lost everything =[

### ISSUE THREAD

**Issue by roblav96** [uBlockOrigin/uBlock-issues#613]
## `Tldr;` The import from cloud storage buttons are gone 😭
Chrome said: `corrupted extension`, I clicked blue `repair` button, now all my settings are gone, can't import from cloud storage, boo, maybe I'll go outside or something? 🤣

Any thoughts on exporting the settings manually from IndexedDB or LocalStorage or FileSystem? I'm desperate lol

----

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I noticed the uBlock Origin shield was missing right of the address bar, so I went to chrome extensions and in bold red text in the uBlock Origin card said something like:
> this extension has been corrupted, click repair to fix this problem
and there was a solid blue `repair` button in place where the toggle switch would be. I clicked it after checking the address bar for `chrome://extensions/` like a billion times lol

uBlock Origin card disappears, then reappears shortly after with all my settings completely wiped. I wasn't worried though because weekly I export each tab settings to the cloud storage.

Except now the import from cloud storage button are no longer there for each tab.

How can I recover my lost settings?

### A specific URL where the issue occurs
[chrome://extensions/](chrome://extensions/)

### Steps to Reproduce
Completely random, I've been using uBlock Origin for countless years, never had this occur.

### Expected behavior:
Be able to import my settings from the cloud storage option.

### Actual behavior:
The import from cloud storage buttons are no longer there.

### Your environment
* uBlock Origin version: `uBlock Origin v1.19.6 `
* Browser Name and version: `Version 76.0.3806.1 (Official Build) dev (64-bit)`
* Operating System and version: `MacOS High Sierra 10.13.6`

**Comment by Jap2-0** [comment]
After you clicked repair, did you look to see if the "enable cloud storage support" box is enabled in the settings/dashboard pane?

**Comment by uBlock-user** [comment]
> How can I recover my lost settings?

Via Back up to File located in settings.html.

This is not a uBO bug as extension corruption can happen via a variety of factors. If you didn't take backups, uninstall and reinstall the extension via the Chrome Store.

**Comment by gorhill** [comment]
Maybe related: <https://bugs.chromium.org/p/chromium/issues/detail?id=977805>.
