### ISSUE TITLE
Block element preview window overlays object to be blocked.

### ISSUE THREAD

**Issue by truthsword** [uBlockOrigin/uBlock-issues#615]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Many websites have popup video window that locates itself in the lower right corner of the web page. When "Block element" is called to remove it the "Block element" windows also locates to the lower right corner, obscuring the video element I want to block, and I am unable to see the effect when choosing blocking elements to preview.
There needs to be a means to drag the Block element window to another part of the screen, so that Preview effect may be seen.

### A specific URL where the issue occurs
There are many... here is one...
<https://www.jpost.com>

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open web page, scroll down to cause video pop-out window to jump to lower right corner of browser.
2. Open uBlock's "Block element"
3. "Block element" window sits on top of undesired video pop-out window.

### Expected behavior:

Relocate "Block element" window to another part of the screen to reveal undesired video pop-out window.

### Actual behavior:

Can't detect uBlock Preview action.

### Your environment

* uBlock Origin version: 1.19.6
* Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* Operating System and version: Win10 x64

**Comment by uBlock-user** [comment]
>  scroll down to cause video pop-out window to jump to lower right corner of browser

That doesn't happen on my end.

**Comment by gorhill** [comment]
I can also not reproduce.

When I move the mouse pointer outside the picker dialog, the dialog fades which may give the impression that it's being overlapped, but bringing the mouse back inside and the dialog returns and render properly.

**Comment by uBlock-user** [comment]
Element picker iframe is always placed at the top of all other frames and never under so this would never occur in the first place.

**Comment by truthsword** [comment]
Page loads with pop-out video
![video before picker](https://i.imgur.com/d80gXTJ.jpg)

Picker selected/video obscured
![video after picker](https://i.imgur.com/Vjv0up5.png)

**Comment by gorhill** [comment]
Oh I understand now, I misunderstood, I thought you meant the picker was underneath the video widget.

Just move the mouse outside the picker dialog, it will fade away revealing what is under.

**Comment by gorhill** [comment]
Ok, being able to drag the dialog out of the way would help when trying different suggested choices.

**Comment by truthsword** [comment]
>Ok, being able to drag the dialog out of the way would help when trying different suggested choices.

Yes... So I cannot tell which filter has an affect as when I click preview the effect on the video window is unknown.

**Comment by gorhill** [comment]
I'm reading the steps-to-reprodce and expected behavior again and I have no clue how I ended up misunderstanding the issue. Sorry about this.

**Comment by truthsword** [comment]
No problem. A workaround is to narrow the browser window. Apparently the picker window and video resize differently, so I managed for force the video to extend enough beyond the picker window to select a filter.  I'm not sure that is doable on other sites, but it may help.

**Comment by kulfoon** [comment]
Me too encountered the issue x times while trying to block something which was placed at bottom-right corner.

> gorhill : Ok, being able to drag the dialog out of the way would help when trying different suggested choices.

Yes, or another solution is an 9 directional pad button in Element Picker's window - an user clicks a desired direction/arrow and the window is moved there:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Sega_master_system_d-pad.jpg/220px-Sega_master_system_d-pad.jpg)

**Comment by krystian3w** [comment]
Try this:

https://userstyles.org/styles/168306/move-ublock-origin-element-picker, no possible better without CSS only.

**Comment by hazarek** [comment]
Does anyone interested in this problem. Using Stylish is not a real solution.  

![bug](https://user-images.githubusercontent.com/36481442/67686222-6de3a180-f9a7-11e9-86e4-995318e94085.gif)

**Comment by krystian3w** [comment]
Better add moveable (ABP / AdBlock / AdGuard have...).

**Comment by hazarek** [comment]
> Better add moveable (ABP / AdBlock / AdGuard have...).
@krystian3w 

I'm happy with ublock. This Title has been opened to report ublock issues. not for advertise your third party plugin. Behave yourself!

**Comment by uBlock-user** [comment]
Available with [1.23.1b17](https://github.com/gorhill/uBlock/releases/tag/1.23.1b17)

**Comment by gwarser** [comment]
Dialog can be dragged by empty space between buttons. Something worth mentioning in wiki.
