### ISSUE TITLE
firefox-legacy-1.16.4.11 actually has version 1.16.4.10 in the install.rdf

### ISSUE THREAD

**Issue by JustOff** [uBlockOrigin/uBlock-issues#616]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It seems that [uBlock0.firefox-legacy.xpi - 1.16.4.**11**](https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.11) still has 1.16.4.**10** in the `install.rdf`.

This causes an endless cycle of updates when using [uBlock Origin Updater](https://github.com/JustOff/ublock0-updater).

### A specific URL where the issue occurs

None

### Steps to Reproduce

1. Install [uBlock0.firefox-legacy.xpi - 1.16.4.**11**](https://github.com/gorhill/uBlock/releases/download/firefox-legacy-1.16.4.11/uBlock0.firefox-legacy.xpi) 
2. Check the version

### Expected behavior:

1.16.4.**11**

### Actual behavior:

1.16.4.**10**

### Your environment

* uBlock Origin version: 1.16.4.11
* Browser Name and version: Pale Moon 28.5.0
* Operating System and version: Windows 7 x64

**Comment by gorhill** [comment]
Oops.. I re-uploaded the package, hopefully it's fine now.

**Comment by JustOff** [comment]
Thank you, now everything is fine!
