### ISSUE TITLE
Interested in getting more help triaging issues?

### ISSUE THREAD

**Issue by schneems** [uBlockOrigin/uBlock-issues#617]
Would you be interested in a PR that adds a section on triaging issues to your `contributing.md` for the main repo?

```
## Issue Triage [![Open Source Helpers](https://www.codetriage.com/gorhill/ublock/badges/users.svg)](https://www.codetriage.com/gorhill/ublock)

You can triage issues which may include reproducing bug reports or asking for vital information, such as version numbers or reproduction instructions. If you would like to start triaging issues, one easy way to get started is to [subscribe to ublock on CodeTriage](https://www.codetriage.com/gorhill/ublock).
```

Will look like this 👇

## Issue Triage [![Open Source Helpers](https://www.codetriage.com/gorhill/ublock/badges/users.svg)](https://www.codetriage.com/gorhill/ublock)

You can triage issues which may include reproducing bug reports or asking for vital information, such as version numbers or reproduction instructions. If you would like to start triaging issues, one easy way to get started is to [subscribe to ublock on CodeTriage](https://www.codetriage.com/gorhill/ublock).

**Comment by gwarser** [comment]
How this can be useful here?

**Comment by gorhill** [comment]
I think triaging is well under control, new issues are quickly triaged, there is no build of of issues occurring.

**Comment by schneems** [comment]
Thanks for the review and for maintaining ublock
