### ISSUE TITLE
Version confusion: which is the latest for Firefox 52 ESR?

### ISSUE THREAD

**Issue by Wizard13** [uBlockOrigin/uBlock-issues#618]
I am confused as to which version is best for Firefox 52.9.0 ESR. Up till now, I've used v1.17.4 (Dec 1, 2018) which was the last that worked for this Firefox version. However, I saw that a new legacy version has just been updated (firefox-legacy-1.16.4.11). Which of these 2 version should I use?

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.
