### ISSUE TITLE
Allow "inverse" option for Zapper mode

### ISSUE THREAD

**Issue by GlassGruber** [uBlockOrigin/uBlock-issues#619]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Is it possible to add an "inverse" mode for the Zapper tool? This mode would allow to remove *any* other element that is not currently selected (preserving child elements ofc).  
Could be enabled with keyboard combo like <kbd>alt</kbd>. 

This would be very useful as a quick way to "declutter" a page for ex. printing or enhanced reading focus, etc...

Thank you for your time and this awesome project!

**Comment by krystian3w** [comment]
What happend if delete `<body>` or `<html>`?

**Comment by uBlock-user** [comment]
> What happend if delete <body> or <html>?

Press F12, switch to console and then write -- `document.body.innerhtml=""` hit Enter.

**Comment by uBlock-user** [comment]
> What happend if delete <body> or <html>?

Press F12, switch to console and then write -- `document.body.innerHTML=""` hit Enter.

**Comment by gorhill** [comment]
I prefer to decline after all, it's entirely not clear what the detailed sought behavior.

**Comment by GlassGruber** [comment]
I see thank you anyway for taking it in consideration!
