### ISSUE TITLE
Start page not loading in firefox 67.0.1 at startup.

### ISSUE THREAD

**Issue by rwssmacos** [uBlockOrigin/uBlock-issues#621]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When starting up firefox 67.0.1 with uBlock Origin (latest version) firefox will refuse to load the start page at startup - if I click the home button the start page loads and if uBlock Origin is disable at startup - the start page loads as normal at startup.

I have also Adblock plus and noscript installed.

I've tryed te folowing - New browser profile (starting fresh), only uBlock Origin installed with
standard settings (unmodified settings)

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox Quantum 67.0.1 (64-bit) 
* Operating System and version: MacOS 10.14.6 bèta (18G29g)

**Comment by gorhill** [comment]
Unable to reproduce.

> firefox will refuse to load the start page at startup

What is the URL of your start page?

**Comment by uBlock-user** [comment]
Sounds like https://github.com/uBlockOrigin/uBlock-issues/issues/416

**Comment by gorhill** [comment]
That issue has become too large with various issues to be used as reference. If OP really did try in a brand new profile with only uBO installed, I would say this is likely related to <https://bugzilla.mozilla.org/show_bug.cgi?id=1543880>. Note that another extension author is reporting the same sort of issue.

**Comment by uBlock-user** [comment]
The symptons mentioned in description match #416, hence the assumption. Also that bug itself is difficult to reproduce.

**Comment by hobel66** [comment]
Had the same issue. Found out that I had set "dom.requestIdleCallback.enabled" to "false". Reverting it to default "true" solved the endless loading.

Just registered here for posting this. Maybe it helps somebody...

**Comment by gorhill** [comment]
What is the reason for disabling `dom.requestIdleCallback.enabled`?

**Comment by gorhill** [comment]
@uBlock-user I think the labels were fine, OP said he had the same problem with a new profile.

**Comment by uBlock-user** [comment]
I removed unable to reproduce because I can reproduce the issue `dom.requestIdleCallback.enabled` set to false, assuming did the same, I removed the label. I will put them back if you disagree.

**Comment by hobel66** [comment]
> 
> 
> What is the reason for disabling `dom.requestIdleCallback.enabled`?

I hardened FF using this guide (in german): [https://wiki.kairaven.de/open/app/firefox](url)

**Comment by gorhill** [comment]
English translation:

> Disables IdleDeadline API feedback on how long the browser is idle to use the time to run tasks in the background

That makes no sense to me, they make it sound as if "tasks" is something bad and should be disabled. The purpose of requestIdleCallback is for JavaScript code to be considerate by deferring the execution of code until the browser is done doing more important stuff -- it's actually beneficial in the big picture.

**Comment by uBlock-user** [comment]
Don't ever disable any `dom.*` properties. They will always break the browser somehow, somewhere.

**Comment by hobel66** [comment]
Maybe the writer of the a/m wiki was referring to `dom.idle-observers-api.enabled` and mixed up both settings?
