### ISSUE TITLE
selfieAfter Default Value Appears Incorrect

### ISSUE THREAD

**Issue by BobsGear** [uBlockOrigin/uBlock-issues#623]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The selfAfter value was recently changed from 11 minutes to 3 minutes.  However in Advanced Settings, the default value still appears as 11 minutes.

### A specific URL where the issue occurs

Settings tab, Advanced Settings

### Steps to Reproduce

1. Enable Advanced Settings button
2. Access said settings

### Expected behavior:

selfieAfter value should display 3 minutes

### Actual behavior:

selfieAfter value displays 11 minutes

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Chromium 74.0.3729.157
* Operating System and version: Windows 7 64-bit

**Comment by uBlock-user** [comment]
> 1.19.6

3 mins is the default since **_1.19.7rc1_**. I will update the wiki regarding this information.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#selfieafter

**Comment by sebast889** [comment]
Why are there 2 wikis now?
