### ISSUE TITLE
Keep only 1 wiki

### ISSUE THREAD

**Issue by sebast889** [uBlockOrigin/uBlock-issues#624]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/uBlockOrigin/uBlock-issues/wiki
https://github.com/gorhill/uBlock/wiki

What's the point of having 2 almost identical wikis? It just causes confusion on which is the up to date one. It's better to just have a single one. The other could just have a link pointing to the main wiki.

**Comment by gwarser** [comment]
This is official: https://github.com/gorhill/uBlock/wiki

Other one is just draft for everyone to edit.
Original was closed because _vandalism_. People started changing unimportant things again and again.

**Comment by uBlock-user** [comment]
Could you please not post a new issue for every question you have ? This tracker is for only issues with uBlock only. Use reddit for questions like these.
