### ISSUE TITLE
Disable Update in Private Browsing Mode

### ISSUE THREAD

**Issue by ilikenwf** [uBlockOrigin/uBlock-issues#625]
In Waterfox 68 I notice that even in private browsing mode, ubo attempts to update lists. I request this be adjusted to be an option to enable/disable as the functionality uBlock provides is important, but provides a fingerprintable series of connections to men in the middle, including government ones, making it an issue in repressive regimes where a user may be using a VPN and in cases where someone is privacy concerned.

**Comment by ilikenwf** [comment]
Fresh private session (no other instances of firefox running), the connections being made by UBO:

![image](https://user-images.githubusercontent.com/414778/59153839-51c08180-8a53-11e9-915b-e373e52ef36f.png)

**Comment by uBlock-user** [comment]
So why not just disable _Auto-update filter lists_ itself ?

**Comment by gwarser** [comment]
Some people use Private Browsing by default. Completely disabling updates will make uBO not effective for them.

**Comment by uBlock-user** [comment]
> making it an issue in repressive regimes where a user may be using a VPN and in cases where someone is privacy concerned.

It suits his concerns for privacy, That option only disables auto-updates, he can always do a manual update by himself.

**Comment by gorhill** [comment]
Private mode is to avoid creating persistent data locally (cookies, local storage, etc.), not to increase online anonymity. To disable auto update accomplishes nothing toward the primary goal of private mode.

**Comment by uBlock-user** [comment]
Private/Incognito mode is nothing more than a placebo, doesn't matter whether you use it or not, everytime you connect to a server on the Internet some information is always sent and that helps the server to fingerprint you.

**Comment by ilikenwf** [comment]
Yes, however taking measures using built in facilities and various addons, and the ghacks user.js file one is much more likely to blend in with the rest of the crowd.

**Comment by gorhill** [comment]
I am declining this, I think the case for such feature is contrived.
