### ISSUE TITLE
Some cosmetic changes

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#626]
_Not sought, and created. Ha-ha... classic_

2 requests.

1. On a laptop with a large number of subscriptions have to scroll very long to get to the button "Update now\Reset cache", how about floating buttons? You have already done 1 floating button "Apply changes", can you do 2 more?
2. The ability to collapse groups subscriptions.

have a nice day!

**Comment by gorhill** [comment]
Floating buttons: ok.

Collapse groups: already in there, just toggle by clicking the group header.

**Comment by bogachenko** [comment]
>Collapse groups: already in there, just toggle by clicking the group header.

Not this not that. Collapse everything.

**Comment by bogachenko** [comment]
For example, the "Languages ​​and Regions" block (if you subscribe to everything) cannot be minimized now. It shows which subscriptions there

**Comment by mozkan007** [comment]
Maybe it is added a sorting feature for custom filters section like newly added, last updated, alphabetical sorting, etc. Thanks.

**Comment by bogachenko** [comment]
By the way, how about adding the `update userResourcesLocation` button (And of course, disable the update scripts by default add a parameter)? m?

**Comment by sergeevabc** [comment]
@gorhill, consider providing examples next to scriptlet options. it’s hard to proceed without them.
For example, the manual [says][1] about ```rc.js``` scriptlet as follows
```
required, class name or list of class names joined by |
optional, CSS selector, specifies nodes from which classes will be removed
```
The first part is somehow obvious: ```bigHeader``` or ```bigHeader|bigFooter```.
But the second part is so confusing: should it be ```#myID.bigHeader``` or… Cosmetic change of a kind.

[1]: https://github.com/gorhill/uBlock/wiki/Resources-Library#rcjs-

**Comment by llacb47** [comment]
Very off topic, and that is basic knowledge of what a CSS selector is.

**Comment by gorhill** [comment]
The Apply/Update/Purge buttons have been floating since the redesign of the UI in [1.27.0](https://github.com/gorhill/uBlock/releases/tag/1.27.0).

Regarding the collapsing, I decline -- selecting all Region lists is not a scenario which should ever happens, and thus having to scroll down a bit to see other selected lists is not really an issue.
