### ISSUE TITLE
Add Mac OSX's "Command" key as a valid modifier for shortcuts

### ISSUE THREAD

**Issue by danmattera** [uBlockOrigin/uBlock-issues#628]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The Command (a.k.a. Meta) key on Mac OSX does not appear to be a valid modifier key for shortcuts in Firefox. Control and Alt shortcuts work as expected per documentation.During my search for a past issue specific to using this key on shortcuts, the only result I found was when gorhill asks for someone give him the output of Mozilla's KeyboardEvent tool using the key on issue 106 https://github.com/uBlockOrigin/uBlock-issues/issues/106#issuecomment-406571656 but no one ever responded to him and so it appears it was never addressed. Here is the requested output I receive from the tool when pressing the left and right  Command keys:

- `KeyboardEvent: key='Meta' | code='OSLeft'`

- `KeyboardEvent: key='Meta' | code='OSRight'`

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Try to use Command key on Mac OSX as the modifier key for a shortcut using any other secondary key 

### Expected behavior:

Use Command key as you would with other valid modifiers (Ctrl and Alt)

### Actual behavior:

Shortcut panel ignores it

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Firefox 67.0
* Operating System and version: Mac OS X 10.14.5

**Comment by gwarser** [comment]
Does it work in Firefox native interface? 

![image](https://user-images.githubusercontent.com/886325/59181305-54ac9680-8b67-11e9-8650-aa3fb22acd39.png)

**Comment by danmattera** [comment]
Hmm, so it does... kind of.

FF's native interface does allow the binding to be set and the uBO dashboard acknowledges it:

![Screen Shot 2019-06-10 at 7 26 56 AM](https://user-images.githubusercontent.com/13613522/59192715-5cf9d700-8b51-11e9-9104-13d1c2cc7b5b.png)

once set, the bindings activate each action but for element and zapper mode, there's a blank overlay over the whole page and for the logger, just a blank window comes up:

element/zapper mode:

![Screen Shot 2019-06-10 at 7 29 52 AM](https://user-images.githubusercontent.com/13613522/59193180-da721700-8b52-11e9-9ed9-946c3206cdab.png)

![Screen Shot 2019-06-10 at 7 29 18 AM](https://user-images.githubusercontent.com/13613522/59193190-dd6d0780-8b52-11e9-8b12-6a29dbfa7dd0.png)

logger:

![Screen Shot 2019-06-10 at 7 32 37 AM](https://user-images.githubusercontent.com/13613522/59193723-9ed84c80-8b54-11e9-8a5a-da77ad841c9d.png)

Confirmed this occurs:

- on numerous sites (github, netflix and reddit to name a few i tried)
- regardless of the modifier used in the key binding. Ctrl and Alt bindings do the same thing.
- after relaunching FF with all other add-ons disabled
- after reinstalling uBO

**Comment by danmattera** [comment]
Nevermind-- just tried creating a fresh FF profile and this problem goes away. Must be something to do with the set up on my normal profile. will play around with things and see if can narrow it down.

**Comment by gwarser** [comment]
This tab will be removed from uBO interface soon https://github.com/uBlockOrigin/uBlock-issues/issues/386

**Comment by danmattera** [comment]
Gotcha, thanks that resolves things here then!
