### ISSUE TITLE
Add a logger setting to toggle between in-popup/in-tab presentation

### ISSUE THREAD

**Issue by darkred** [uBlockOrigin/uBlock-issues#629]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Currently, in new uBO installations, in both Chrome 75/Firefox 67, 
the logger is opened in a new window by default.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
all pages, e.g. https://www.google.com/

### Steps to Reproduce

1. In a fresh profile of Chrome 75/Firefox 67, with only uBO installed, click on its toolbar button and open the logger
2. Notice that the logger opens in a new window by default

### Expected behavior:

[What you expected to happen]
I was expecting the logger to open in a tab, for the following reasons:
- Currently, by opening it in a new window, you can't manually drag and drop the logger window (as a tab) to the initial browser window where the e.g. https://www.google.com/ tab is.
- Also, in Firefox the Option "Open links in tabs instead of new windows" is enabled by default. 
In Chrome, there's a similar default behavior. 
So I thought that opening uBO's logger would work the same.
- Finally, the instructions to do otherwise (i.e. that *you may hold the "Shift" key while clicking the "Open the logger" icon to toggle opening it in a new tab*) is not available in the logger window itself, and you must visit the wiki (following the "i" icon link) to find it. 
If the logger opened in a new tab by default instead, this would not be necessary.

### Actual behavior:

[What actually happened]
The logger opens in a window.

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Chrome 75/Firefox 67
* Operating System and version: Windows 10

---

I'd like to also make a PR in order to facilitate you.
So, by looking the code, the user setting that seems to be the relevant one is 
[alwaysDetachLogger](https://github.com/gorhill/uBlock/search?q=alwaysDetachLogger&unscoped_q=alwaysDetachLogger)
so I think that in my PR I should change its default value to `false` in: https://github.com/gorhill/uBlock/blob/master/src/js/background.js#L67

If you agree with my suggestion and the above line is the relevant one,
please confirm so that I may open a new PR in https://github.com/gorhill/uBlock.

Thank you

**Comment by uBlock-user** [comment]
> Currently, in new uBO installations, in both Chrome 75/Firefox 67,
the logger is opened in a new window by default.

By-design, not a bug.

**Comment by darkred** [comment]
> By-design, not a bug.
> 
> [uBlockOrigin/uBlock-issues/wiki/The-logger#tip](https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#tip)

I have included that wiki section in my OP.
And I didn't say that it's a bug - I just find that the current default behavior is not the expected one.

**Comment by gwarser** [comment]
@darkred check this: https://github.com/uBlockOrigin/uBlock-issues/issues/602#issuecomment-496560075

Logger may not work as expected when page is not visible.

**Comment by uBlock-user** [comment]
Reopened for @gorhill to address this.

**Comment by gorhill** [comment]
I won't change the default. It comes down to personal preference, and I prefer to have a detached logger by default. I will add an option to the logger's settings to easily toggle between in-popup/in-tab presentation.
