### ISSUE TITLE
uBO tooltips conflicts with browser tooltips (Legacy issue)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uBlock-issues#63]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
In Firefox Legacy browsers (e.g. Pale Moon and SeaMonkey), uBO tooltips are placed beneath browser tooltips

### Screenshot:
![ublockorigin-bug-tooltips](https://user-images.githubusercontent.com/9382674/39240428-41a5e0d8-4873-11e8-90fa-88bdc4beb2b5.jpg)

### Possible fix?:
If possible, perhaps browser tooltips should be disabled for uBO?
Since all of the browser tooltips only say "uBlock Origin", the only place where it makes sense to keep it is on the toolbar icon itself.

### Reference:
`https://github.com/uBlockOrigin/uBlock-issues/issues/22/#issuecomment-384240402`
I've tried referencing to the post above before, but I think it has gone by unnoticed.

### Your environment
* uBlock Origin version: 1.16.4.1 (XUL)
* Browser Name and version: Pale Moon v27.9.2,x64
* Operating System and version: Win8.1Pro,x64

**Comment by uBlock-user** [comment]
> perhaps browser tooltips should be disabled for uBO?

That setting exists already, open the Settings page and put a tick on Disable tooltips.

**Comment by THEtomaso** [comment]
> That setting exists already, open the Settings page and put a tick on Disable tooltips.

No, that disables uBO's tooltips, not browser tooltips.
Of course, there is this setting under the browsers about:config:
`browser.chrome.toolbar_tips`
..but changing its value will disable all browser tooltips in general.

**Comment by gorhill** [comment]
It's a browser issue.

And more generally, I won't spend time on the legacy version except for issues which are worth it the time -- serious malfunctions or performance issues.

**Comment by janekptacijarabaci** [comment]
@gorhill 
I suggest adding to:
https://github.com/gorhill/uBlock/blob/firefox-legacy-1.16.4.1/platform/firefox/vapi-background.js#L2697
this line:
`toolbarButtonPanel.setAttribute('tooltiptext', '');`

If I do not miss something...

**Comment by gorhill** [comment]
@janekptacijarabaci Thanks, this worked.

**Comment by janekptacijarabaci** [comment]
Thank you also, @gorhill
