### ISSUE TITLE
2 small picker bugs

### ISSUE THREAD

**Issue by joey04** [uBlockOrigin/uBlock-issues#632]
1. [This line](https://github.com/gorhill/uBlock/blob/1.20.0/src/js/scriptlets/element-picker.js#L648) should have a `.slice(2)` at the end.

2. [This section](https://github.com/gorhill/uBlock/blob/1.20.0/src/js/scriptlets/element-picker.js#L827-L829) should have a `if ( elem === pickerRoot ) { continue; }` check, just like the function directly above it.

**Comment by uBlock-user** [comment]
why not just PR this ?

**Comment by gorhill** [comment]
I want steps-to-reproduce to illustrate the issues arising with the pointed out code.
