### ISSUE TITLE
Blocking remote fonts causes erroneous icon display

### ISSUE THREAD

**Issue by nick-s-b** [uBlockOrigin/uBlock-issues#633]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When remote fonts are disabled by default in Settings by checking the "Block remote fonts", uBO is missing a bunch of icons in main options panel:

![Screenshot from 2019-06-16 17-40-03](https://user-images.githubusercontent.com/7957590/59569928-4c1ff880-905e-11e9-982d-d7fd9bd9ee26.jpg)

Notice how the JS icon is missing completely and "Remote fonts" icon is showing that fonts are enabled (when they're not):

![Screenshot from 2019-06-16 17-41-45](https://user-images.githubusercontent.com/7957590/59569968-c94b6d80-905e-11e9-81c3-6648b82ac99f.jpg)

JS and Remote fonts icons should show red cross across them since they're disabled.

### Steps to Reproduce

1. Disable remote fonts and JS in Settings
2. Go to any site
3. Notice the JS icon is missing and there's no red cross across Remote font & JS icons.

### Expected behavior:

Icons should be shown with their proper state.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.19.6
* Browser Name and version: Chromium 75.0.3770.80
* Operating System and version: Linux

**Comment by uBlock-user** [comment]
> Go to any site

Post a specific URL, can't reproduce if I do to any URL.

**Comment by gorhill** [comment]
Most likely explanation is a graphic driver issue on OP's side. The icons are just plain SVG resources, uBO is not involved in rendering them, the browser is.
