### ISSUE TITLE
Thunderbird's 1.20.0 xpi contains version 1.9.15.101

### ISSUE THREAD

**Issue by tobiasweibel** [uBlockOrigin/uBlock-issues#636]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The XPI 1.20.0 for Thunderbird actually contains version 1.9.15.101 (manifest.json or Thunderbird 67.0b3 UI).

### A specific URL where the issue occurs

Download URL: https://github.com/gorhill/uBlock/releases/download/1.20.0/uBlock0_1.20.0.thunderbird.xpi

### Steps to Reproduce

1. Download 1.20.0 xpi for Thunderbird
2. Install it and verify the version
3. Verify the version of the addon

### Expected behavior:

The version should be 1.20.0

### Actual behavior:

The version is 1.9.15.101. Also the manifest.json within the xpi file is set to this version.

### Your environment

* uBlock Origin version: 1.20.0 or 1.9.15.101
* Browser Name and version: Thunderbird 67.0b3
* Operating System and version: Win 10 1903

**Comment by gorhill** [comment]
I don't understand why this happens, I can't see anything wrong with the shell scripts.

- This happens only for release builds
- This happens only in Travis
- This does not happen when I run the shell script `./toosl/make-thunderbird.sh` locally

**Comment by tobiasweibel** [comment]
Verified with 1.20.1.3
