### ISSUE TITLE
Mac Safari helper app dialog shows on every boot.

### ISSUE THREAD

**Issue by OneOfMany07** [uBlockOrigin/uBlock-issues#637]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Just installed for the first time on my Mac for Safari, and the helper app is annoying.  It shows a dialog for settings every time I boot my system.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Install on Mac
2. Boot

### Expected behavior:

App to run, but be hidden (minimized or not actually run).  Icon to show along top so it'll work.

### Actual behavior:

Get window showing settings as if I'll want to change them.

### Your environment

* uBlock Origin version: 1.3
* Browser Name and version: Safari 12.1.1
* Operating System and version: macOS Mojave 10.14.5

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock#safari-macos
