### ISSUE TITLE
Ubuntu package xul-ext-ublock-origin not showing up in Firefox

### ISSUE THREAD

**Issue by schildbach** [uBlockOrigin/uBlock-issues#638]
As per [README.md](https://github.com/gorhill/uBlock/blob/master/README.md#firefox--firefox-for-android), I installed the package `xul-ext-ublock-origin` on Ubuntu 18.04 LTS. I'm also using Firefox from the `firefox` Ubuntu package. All packages are fully updated.

The issue: **UBlock doesn't show up in the Firefox addons** list and therefore I assume it is not operational.

**Comment by gwarser** [comment]
I think it's "readme" issue. I cannot find `xul-ext-ublock-origin` [package on repology.org](https://repology.org/projects/?search=xul-ext-ublock-origin&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=), only [ublock origin](https://repology.org/projects/?search=ublock-origin&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=)

<sub>Don't we had "debian" label?</sub>

**Comment by gwarser** [comment]
I also don't think Sean Whitton is still responsible for it: https://qa.debian.org/developer.php?login=spwhitton&comaint=yes

**Comment by gorhill** [comment]
See https://packages.debian.org/stable/source/ublock-origin

**Comment by gwarser** [comment]
Yes, just got to it too.

**Comment by gorhill** [comment]
Does `apt-get install webext-ublock-origin` work?

**Comment by schildbach** [comment]
@gorhill I'm afraid no. That package is not available in 18.04, only [from 18.10 onwards](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=webext-ublock-origin&searchon=names).

**Comment by gorhill** [comment]
What is your version of Firefox?

**Comment by schildbach** [comment]
@gorhill 

```
firefox                                     67.0.2+build2-0ubuntu0.18.04.1      amd64
xul-ext-ublock-origin                       1.13.8+dfsg-1                       all
```

**Comment by gorhill** [comment]
`xul-ext-ublock-origin` won't work with Firefox 57 and above. You will have to install from AMO. I will update the README with that information.

**Comment by gorhill** [comment]
This is for Ubuntu maintainers to address, I am not involved in creating packages for Debian/uBuntu/etc.

**Comment by schildbach** [comment]
Ok I'll file an issue against Ubuntu then. Thanks for your clarifications!
