### ISSUE TITLE
Immediate crash on reload

### ISSUE THREAD

**Issue by sorenbug** [uBlockOrigin/uBlock-issues#639]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Loading uBlock causes it to instantly crash

### A specific URL where the issue occurs

chrome://extensions (reload the extension)

### Steps to Reproduce

1. Load the extension

### Expected behavior:

uBlock appears in my bar and works properly

### Actual behavior:

I get the oops balloon described in issues #9 and #10

### Your environment

* uBlock Origin version: 1.20.0 (latest stable) and 1.19.7.102 (latest development)
* Browser Name and version: Chromium 72.0.3626.121 (Developer Build da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883} Linux) (latest in xbps, Void's package manager)
* Operating System and version: Void Linux 4.19.51_1 (musl)

**Comment by uBlock-user** [comment]
> Chromium 72.0.3626.121 (Developer Build da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883} Linu

Broken dev build of version 72, use the latest stable version of Chromium.

**Comment by sorenbug** [comment]
Awesome, that's what I assumed. I don't know how to get a more updated version of Chromium though.

**Comment by uBlock-user** [comment]
https://chromium.woolyss.com/#linux

Maybe that can help you.
