### ISSUE TITLE
Let's make uBlock great again: filter lists for dynamic filtering (whitelist)

### ISSUE THREAD

**Issue by sevospl** [uBlockOrigin/uBlock-issues#64]
### Description

For some reason, dynamic filtering isn't widespread enough, even if it's a great idea. Why?

Blocked scripts and frames from external domains mean:

- No any ads, regardless of static filter lists,
- Significantly higher security level when browsing the Internet,
- Significantly faster rendering of pages.

The problem is that there's a little too much blocking at the start, and not everyone wants to set everything up on their own. The idea is to make a separate section in the filter lists and to be able to provide a full set of ready-made rules (whitelist) for good domains, such as CDN or multimedia content (pics, videos etc.).

Yes, I know, there is uMatrix, but unfortunately it requires a lot more work and each time you have to download and activate a set of rules to a particular page, which isn't convenient.

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1207#issuecomment-170608860
