### ISSUE TITLE
v1.16.4.9 is blocking Google Maps search listing (items show on map)

### ISSUE THREAD

**Issue by rodndtube** [uBlockOrigin/uBlock-issues#640]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature] after performing a google maps search, e.g., hotels in Boston, items appear on the map but not in a listing on the left.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"] https://www.google.com/maps/search/espresso/@37.255555,-108.5963641,10z/data=!4m2!2m1!6e5

### Steps to Reproduce

1. [First Step] Search for a place in google maps
2. [Second Step] Select Nearby and hotels or enter something else in the search box
3. [and so on...] search items appear on map, but no listing in the fly-out settings/search panel

### Expected behavior:

[What you expected to happen] See a listing

### Actual behavior: 

[What actually happened] List might flash and then goes blank. After testing another browser, testing a couple of Themes, I disabled uBlock and the list reappeared.

### Your environment

* uBlock Origin version:  1.16.4.9
* Browser Name and version:  Basilisk 2019.06.08 (64-bit)
* Operating System and version: Window 10 Pro 1809 Version 10.0.17763.557

![2019-06-20 NoListing on Google Maps - Basilisk](https://user-images.githubusercontent.com/52054257/59886485-1e53f000-938d-11e9-88fd-a7bb8d03a82a.png)

**Comment by rodndtube** [comment]
I tried another blocker and everything worked as uBlock Origin did until a few days ago.

**Comment by mapx-** [comment]
Did you update all your lists ? (purge all caches + update now)

**Comment by uBlock-user** [comment]
Bad filter - `google.*##:xpath(//span[(text()='Ad')]/../../../..)`

**Comment by mapx-** [comment]
> google.*##:xpath(//span[(text()='Ad')]/../../../..)

it was fixed days ago

@rodndtube update your lists before reporting

**Comment by uBlock-user** [comment]
> it was fixed days ago

commit ? I update my lists every 72 hours and it was there, so posted here to let you know.

**Comment by mapx-** [comment]
4 days ago
https://github.com/uBlockOrigin/uAssets/commit/c8aaccff78489849a88d331d550595fda016b50d

**Comment by gorhill** [comment]
That revised filter is still causing issues. The whole info box at the following link is removed:

    https://www.google.com/search?q=helldivers

I whitelisted it and reload the page at issue <https://github.com/uBlockOrigin/uAssets/issues/5830> and I didn't see anything which should be blocked.

**Comment by mapx-** [comment]
Did you test on mobile ?

**Comment by mapx-** [comment]
visiting `https://www.google.com/search?q=helldivers` => the filter is not triggered on my side

**Comment by mapx-** [comment]
- mobile device or user agent switcher
- US IP

see Ad 

![image](https://user-images.githubusercontent.com/10303732/59923650-36327f00-9434-11e9-9b09-d6cddda11cae.png)

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/59923737-1bdfad80-9402-11e9-95ca-7eaa18cdc372.png)

**Comment by gorhill** [comment]
![a](https://user-images.githubusercontent.com/585534/59923803-50536980-9402-11e9-884c-cbae727c6544.png)

**Comment by mapx-** [comment]
hmm, I see why I cannot reproduce, I get Ads on my side

![image](https://user-images.githubusercontent.com/10303732/59923908-da1c2a80-9434-11e9-808d-feb7c117ca0b.png)

**Comment by mapx-** [comment]
I'll comment for now the filter ..

**Comment by gorhill** [comment]
I think we should redirect mobile-specific issues to Adguard Mobile, or at least use `!#if env_mobile`?

**Comment by mapx-** [comment]
yes, even if we cannot be sure the mobile pages wont be broken in this case

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a3d9a8f64b8324cb1eb27173354c9b93bea76b4e
