### ISSUE TITLE
Custom Filter List url's not saved

### ISSUE THREAD

**Issue by jsEveryDay** [uBlockOrigin/uBlock-issues#644]
Whenever you disable a Custom List it disappears permanently when page is reloaded. So if one is doing testing to see if certain behavior is caused by a list and want to temporarily disable it, you will likely lose it. So why not save the custom list references? It's just a title and url string.

This issue has always been there. Pretty annoying when you lose URLs.
There's a Checkbox to the left and a Trashcan on the right side, what is the difference?
If you uncheck the checkbox you'd expect to be able to go back and enable it if you want.

![image](https://user-images.githubusercontent.com/16431055/59968367-c93be980-9506-11e9-9ab1-8894b84472c7.png)

**Comment by gwarser** [comment]
Click on "Custom (2/3)"

**Comment by jsEveryDay** [comment]
Ashamed

**Comment by uBlock-user** [comment]
Keep it expanded.
