### ISSUE TITLE
Allow generic HTML filters

### ISSUE THREAD

**Issue by Jtasiu** [uBlockOrigin/uBlock-issues#645]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I would really like to write HTML filters to remove some junk and common elements everywhere. I enabled `allowGenericProceduralFilters` but it doesn't cover HTML filters. Is it possible to add a similar advanced setting to be able to use generic HTML filters?

**Comment by gorhill** [comment]
Provide actual cases if you want to convince me of why such features is needed.

**Comment by Jtasiu** [comment]
Use cases are to remove common elements, inline-scripts etc completely from source than just hide them using normal cosmetic filters

Some examples:
Very common banner and image annoyances. Cosmetic hiding filter won't stop loading image if there is no matching network filter for specific URL or domain. If the common element is matched and tries to load image the HTML filters will prevent loading those images in the first place. 
##^[class^="banner"]
##^[id^="ads"]
##^.sidebar_advert
##^.avatar

Instart and other common adverts,tracking
##^script:has-text(/i10C|IXC_|Instart/) ..there's more junk here but just example
##^script:has-text(3f87b0eaddd)
##^script:has-text(adblock)

It would be a advanced setting so advanced users can deal with breakage if there's any and create filters for their own needs themselves.

**Comment by gorhill** [comment]
> It would be a advanced setting so advanced users can deal with breakage if there's any and create filters for their own needs themselves.

Ok.

**Comment by keczuppp** [comment]
The issue to be closed? Because it seems to be fixed, because now can be used in uBO filters like:
- `com##^.avatar`
- `*##^.avatar` (https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#specific-generic)

**Comment by rowaasr13** [comment]
I don't see anything at that link that causes filter to completely remove element and stop loading sub-resources within it as requested in issues's opener.
