### ISSUE TITLE
Redirect after 401 not followed

### ISSUE THREAD

**Issue by Agrv** [uBlockOrigin/uBlock-issues#647]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
On Chromium 62.0.3202.94, with latest version uBlock Origin 1.20.0, when a page sends an HTTP/401 unauthorized, and then an HTTP/302 after you entered correct login and password, the redirect is not followed. The last version of uBlock Origin in which it worked is the 1.18.16 (the bug appears on 1.19.0). Problem does not occur on Chrome 75; unfortunately we cannot upgrade to this version yet for compatiblity reasons with some web applications.
### A specific URL where the issue occurs
https://snolli.fr/testublock/
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Go to https://snolli.fr/testublock/
2. [Second Step] Enter login "test" and password "test"
3. [and so on...] 

### Expected behavior:
Normal behavior without uBlock Origin 1.20.0 or with uBlock Origin 1.18.16 : redirection to https://snolli.fr/testublock/redir/
[What you expected to happen]

### Actual behavior:
White page ; requires F5 to actually make the redirection.
[What actually happened]

### Your environment

* uBlock Origin version: 1.20.0
* Browser Name and version: Chromium 62.0.3202.94
* Operating System and version: Windows 10 (1803)

**Comment by gorhill** [comment]
What does uBO's logger say?

**Comment by Agrv** [comment]
The logger gives the following output, which does not seem very useful:
+0
snolli.fr
1
doc
https://snolli.fr/testublock/

+0
https://snolli.fr/testublock/


However I forget to attach the chrome://net-intervals output in the three following cases:
1) net-internals-direct.txt : without uBO extension
2) net-internals-ublock1.18.16.txt : with uBO 1.18.16
3) net-internals-ublock1.20.0.txt : with uBO 1.20.0

In cases 1, 2 and 3 you see:
GET /testublock/ HTTP/1.1 Host: snolli.fr
HTTP/1.1 401 Unauthorized
GET /testublock/ HTTP/1.1 Host: snolli.fr Authorization: Basic [12 bytes were stripped]
HTTP/1.1 302 Found Location: redir/

In cases 1 and 2, but not in 3, you finally see:
GET /testublock/redir/ HTTP/1.1 Host: snolli.fr
HTTP/1.1 200 OK

**Comment by uBlock-user** [comment]
uBO is not blocking anything that's the logger shows.

**Comment by Agrv** [comment]
Yes, that proves that it is not a filter issue. However, the presence of the extension makes the bug occur. Without the extension or with uBO 1.18.16, the bug is not present, with uBO 1.20.0 (in fact with uBO >=1.19.0), the bug is present.

**Comment by uBlock-user** [comment]
Open the web page console and posta any warnings/errors here, do the same for uBO console too which is located in chrome://extensions > uBlock Origin tile > background.html

**Comment by gorhill** [comment]
Most likely similar to <https://github.com/gorhill/uMatrix/issues/912#issuecomment-357019507>: this is a browser bug which has been fixed since Chromium 66, see <https://bugs.chromium.org/p/chromium/issues/detail?id=801237>.

**Comment by Agrv** [comment]
Indeed, when unchecking "Disable pre-fetching" in uBO, the issue disappears. Thank you gorhill for pointing this workaround. It will help us for now, until we are finally ready to update Chromium to a more recent version.
