### ISSUE TITLE
logger.js add link to open urls in a new tab

### ISSUE THREAD

**Issue by kkkkzk** [uBlockOrigin/uBlock-issues#648]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Can we have links after urls in logger to open them in a new tab?

### A specific URL where the issue occurs

moz-extension://

### Steps to Reproduce

1. Open uBlock logger
2. Log some traffic
3. Urls are in plain text

### Expected behavior:

Maybe we could have a link after each url to open it in a new tab?

### Actual behavior:

Urls are in plain text only

### Your environment

* uBlock Origin version: 1.20
* Browser Name and version: FF 67
* Operating System and version: Win10

**Comment by gwarser** [comment]
In Firefox if you double-click, all URL should be selected. You can then move it to tab bar to open in new tab.

**Comment by kkkkzk** [comment]
> 
> 
> In Firefox if you double-click, all URL should be selected. You can then move it to tab bar to open in new tab.

That's exactly what I am doing. Which is 3 clicks and a drag to a certain area per URL. And I usually need to open >5 URLs, so all I think about while doing it is how nice it would be if they had some clickable links.

I thought I would just edit the addon for myself and add 1 line of code to get what I want, but I am kinda new to these Firefox extensions, so after modyfing the code I've learned about extension signing, then I thought "what about hacking it with an user script", only to learn that they are not allowed to interact with browser's extensions... and here I am now.
