### ISSUE TITLE
How can I allow to these dom filter rules?

### ISSUE THREAD

**Issue by mozkan007** [uBlockOrigin/uBlock-issues#649]
Hi, I am a basic pc user and I have a problem about these 2 dom filter rules; 

##div[id*="ScriptRootC"]

##[id*="ScriptRoot"] 

Ublock blocks them but I also added them to my filters section, to allow the filters, by converting the format into #@#[id*="ScriptRoot"] ,  #@#div[id*="ScriptRootC"] but it does not work. Can you help me, please? Thanks.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues#ublock-issues

>Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).
