### ISSUE TITLE
[Suggestion] Night Mode, I just give an idea.

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#65]
### Description

[I was wondering if the developers could add a night mode and also "activate it automatically after a certain time of night". I'm not a developer, I just give an idea.]

If you are not interested in my idea, just close this Issue.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/1869

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/1869
