### ISSUE TITLE
Specific network filtering rules become invalid if it have `~document` exception

### ISSUE THREAD

**Issue by kowith337** [uBlockOrigin/uBlock-issues#650]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
      > I'm not sure about this, probably internal filter read, not external filters.
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When I added some network filter that include `~document` exception, uBlock logger reported the filter that I've putted in is invalid

### A specific URL where the issue occurs
No URL, just internal uBlock (maybe only logger?)

### Steps to Reproduce

1. Open uBlock Dashboard
2. Go to **My Filters**
3. Try add some network blocking and include `~document` exception, e.g.
   `||example.com/page$~document`
   `||example.com/page$important,~document`

### Expected behavior:
uBlock Logger doesn't reported as invalid, probably the network filter is usable.

### Actual behavior:
uBlock Logger reported the filter is invalid

### Your environment
* uBlock Origin version: 1.20.0 onward
* Browser Name and version:
  * Chromium NoSync: 77.0.3814.0 (64-bit)
  * Firefox 67.0.4 (64-bit) + uBlock 1.20.0
  * Cent Browser: 4.0.9.112 (Official Build) (32-bit) (portable) (Chromium 74.0.3729.169) + NanoAdblocker 1.0.0.117
  * ~~Pale Moon 28.5.2 (64-bit) + uBlock Legacy 1.16.4.11~~
* Operating System and version: Windows 10 x64 Update 1903 (rs5)

### Screenshots
Firefox
  ![image](https://user-images.githubusercontent.com/16535467/60444071-a74d1000-9c46-11e9-8a04-a8330e2b0321.png)

Chromium
  ![image](https://user-images.githubusercontent.com/16535467/60444467-7e794a80-9c47-11e9-84ff-4706795447ca.png)

CentBrowser + Nano
  ![image](https://user-images.githubusercontent.com/16535467/60444014-8ab0d800-9c46-11e9-845d-6adc9f6faf06.png)

Pale Moon + uBO Legacy
![image](https://user-images.githubusercontent.com/16535467/60444611-c26c4f80-9c47-11e9-901b-da69cddb70ac.png)

**Comment by gwarser** [comment]
>     3\. Try add some network blocking and include `~document` exception, e.g.
>         `||example.com/page$~document`
>         `||example.com/page$important,~document`
> 
> 
> ### Expected behavior:
> 
> uBlock Logger doesn't reported as invalid, probably the network filter is usable.

What you think this filter should do?

**Comment by gwarser** [comment]
You should read about `all` option and linked issue https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#all

**Comment by kowith337** [comment]
> What you think this filter should do?

To block everything except document

**Comment by gorhill** [comment]
Using `||facebook.com/ads/` will block all matching network requests and will not block document.
