### ISSUE TITLE
Whitelisting behind-the-scene causes uBO to disregard the moz-extension-scheme rule

### ISSUE THREAD

**Issue by Hifexar** [uBlockOrigin/uBlock-issues#651]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
moz-extension-scheme * * block  - does not work

In white list:
"# about-scheme"
"# chrome-extension-scheme"
"# chrome-scheme"
"# moz-extension-scheme"
"# opera-scheme"
"# vivaldi-scheme"
"# wyciwyg-scheme"

But the lock does not work. How to reproduce bug: 
1. Disable white lists. 
2. Update the filter lists.
3. See, that they are updated, although must be blocked.

uBlock Origin v1.20.3b0
firefox 67.0.4 x64

behind-the-scene * * block  - does not work as well.
I don't know how to fake it. But I saw in the log that the request was not blocked.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Disable white lists. 
2. Update the filter lists. 
3. See, that they are updated, although must be blocked.

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by Hifexar** [comment]
And for some reason time in a log not local.

**Comment by gorhill** [comment]
Fill in the information properly as requested please. I could not reproduce with the information you provided.

**Comment by Hifexar** [comment]
screenshots:
1. https://gyazo.com/aa8feda34a568fb69a4e4d45bf40e2c6
2. https://gyazo.com/e83861ab2a70568b4388f4f44e816692
3. https://gyazo.com/27d59052ae13f6c3f46991dd265ae989
4. https://gyazo.com/76183b17fb17e80307ac6a88edf49417
And plus even more precise blocking:
https://gyazo.com/e7526cb850a9f18d9a834d32d5cc3e91
https://gyazo.com/11ed985067aedda47c220aee42fee912

OS: Win7pro Sp1 x64
uBlock Origin v1.20.3b0
firefox 67.0.4 x64

I'm sorry, I don't understand, but what other information do you need?

**Comment by Hifexar** [comment]
I'm sorry, it's my mistake. I found out. It turns out that if you whitelist behind-the-scene, the Moz-extension-scheme lock is ignored.

**Comment by Hifexar** [comment]
And yet, here is an example when behind-the-scene is not blocked.
https://gyazo.com/b68c6e0de5e8047e3e654e7aef868f0e

**Comment by gorhill** [comment]
I need to investigate why whitelisting `behind-the-scene` causes uBO to disregard the `moz-extension-scheme` rule -- I was not expecting this.

**Comment by Hifexar** [comment]
Another example of when not locked behind-the-scene:
https://gyazo.com/55124362315ae46122df3f0b0ded440c

**Comment by Hifexar** [comment]
Or maybe these queries are not behind the scene, but then why are they displayed in the log in behind-the-scenes queries?

**Comment by Hifexar** [comment]
Umatrix correctly identifies these requests as behind-the-scenes requests and blocks them. But ublock does not block.
https://gyazo.com/bc62c889e0f4610317e655b331231426

**Comment by Hifexar** [comment]
To simulate such a non-blocking request, you need to hold an open tab with one of the screenshots from my previous messages.
https://gyazo.com/d9cb964dce42239c07e551d952620f9f

in umatrix log:
https://gyazo.com/702f782aab7b3597aca137d24c3175ef

**Comment by Hifexar** [comment]
Where to read about what a side means?
What is it?
https://gyazo.com/0194bcb143c4a7edc927a8d4d4638a4b

**Comment by uBlock-user** [comment]
Read the wiki for the partyness information and please stop adding questions after questions inturn adding noise to this bug.

**Comment by gorhill** [comment]
> how to make local time in umatrix, ublock logs?

It is local time. Verify that any `about:config` setting is interfering, for example `privacy.resistFingerprinting`.

**Comment by gorhill** [comment]
> Read the wiki for the partyness information

To be fair, the wiki has not been updated to account for that new row in the logger. Something else to fix. Some information in the release notes: <https://github.com/gorhill/uBlock/releases/tag/1.18.0>.
