### ISSUE TITLE
Open Panel on Hover Over uBlock Icon

### ISSUE THREAD

**Issue by jacktully** [uBlockOrigin/uBlock-issues#652]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I would like the uBlock panel to open when I hover over the uBlock icon and the panel would close and the page would refresh after I move the cursor out of the panel.  I suffer from RSI and this feature would be extremely helpful.

**Comment by gorhill** [comment]
The browser is responsible for bringing up the popup panel, you will have to open an issue with browser developers.
