### ISSUE TITLE
UBO making sites run slowly even when blocking is turned off

### ISSUE THREAD

**Issue by elijahtlang** [uBlockOrigin/uBlock-issues#653]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox briefly but repeatedly displays a yellow warning banner saying that the UBO extension is causing firefox to run slowly. This persists even when I have turned off filtering on that site. 

### A specific URL where the issue occurs

`https://play.google.com/`

### Steps to Reproduce

1. Install UBlock Origin extension on firefox
2. Navigate to play.google.com
3. Give it a few seconds, click on some apps if need be; the warning banner will pop up
4. Turn off filtering for that site
5. Refresh page
6. Give it a few more seconds, it will still occur

### Expected behavior:

The webpage runs normally with no warnings

### Actual behavior:

Webpage runs/loads slowly, and a yellow Firefox warning banner pops up briefly (see screenshot)

![Untitled](https://user-images.githubusercontent.com/40775958/60684928-33348700-9e55-11e9-8e84-b80622f2d107.png)

### Your environment

* uBlock Origin version: 1.20.0
* Browser Name and version: Mozilla Firefox 67.0.4 (issue also occurred w/ previous versions)
* Operating System and version: Windows 10 Home 64-bit, v1903, build # 18362

**Comment by uBlock-user** [comment]
What other extensions do you have alongside ?

**Comment by gorhill** [comment]
Unable to reproduce.

Please provide a performance profile: https://profiler.firefox.com/

**Comment by gorhill** [comment]
Closing due to lack of feedback by OP, and keeping in mind OP had already disregarded the request for profiling data in the issue template. The report is essentially unactionable.
