### ISSUE TITLE
Local User scriptlets

### ISSUE THREAD

**Issue by Huahwyis** [uBlockOrigin/uBlock-issues#654]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Can there be a tab in dashboard called User Scriptlets where users can add their own scriptlets? I searched and it is possible with advanced setting but it requires external hosted file...please can it have local tab like User Filters so it won't need to be hosted with third party or external server? Can even be hidden but only show tab when advanced user setting is on.

Thank you much

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment]
Just use a user script extension, they are specialized for this.

**Comment by Huahwyis** [comment]
uBlock Origin has already good and easy syntax for scriptlets! I just wish for local way to use them.
But Ok...I will search for user script extension

**Comment by uBlock-user** [comment]
No need to search, go with [ViolentMonkey](https://github.com/violentmonkey/violentmonkey) -- free, open source and no analytics embedded,
