### ISSUE TITLE
Performance comparison: web assembly version

### ISSUE THREAD

**Issue by erotavlas85** [uBlockOrigin/uBlock-issues#655]
Hi,
I recently read about [performance comparison among various adblocker](https://whotracks.me/blog/adblockers_performance_study.html). I just wonder to know if the comparison is fair and what to expect from web assembly version of ublock origin.
Thank you

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues#ublock-issues

> Support issues and questions are handled at /r/uBlockOrigin.
