### ISSUE TITLE
Request: Allow subscribing / auto-import of dynamic rules

### ISSUE THREAD

**Issue by Luzifer** [uBlockOrigin/uBlock-issues#66]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As someone using different browser profiles for different purposes (private, work, messengers, …) I do have a custom static filters list all of them are subscribed to: Enter a rule once, all profiles are complying my rules.

Using dynamic rules I'm left with an "export to file" button: I do need to build the rule, export it, re-import it 3+ times. Here it would be great to have the chance to "subscribe" to a central source (my own list) which is automatically updated just like the static filters.

### A specific URL where the issue occurs

n/a - feature request

### Steps to Reproduce

n/a - feature request

### Expected behavior:

see description

### Actual behavior:

n/a - feature request

### Your environment

* uBlock Origin version: `v1.16.8`
* Browser Name and version: `Google Chrome Version 68.0.3440.17 (Official Build) beta (64-bit)`
* Operating System and version: `Mac OS 10.13.5 (17F77)`

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/issues/1207#issuecomment-170608860
https://github.com/uBlockOrigin/uBlock-issues/issues/64

https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by gwarser** [comment]
You can rewrite your dynamic filters to static https://github.com/gorhill/uBlock/issues/1063
