### ISSUE TITLE
Domain connection notification color strip doesn't appear intermittently/first-load on text document pages

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#660]
### Description

Domain connection notification color strip in the dynamic filtering pane doesn't appear intermittently on text document pages.

### A specific URL where the issue occurs

`https://github.com/uBlockOrigin/uAssets/blob/master/tools/update-3rdparties.sh`

### Steps to Reproduce

1. Browse to `https://github.com/uBlockOrigin/uAssets/blob/master/tools/update-3rdparties.sh` or any github page which has RAW version of the document.
2. Click on Raw and once the page loads completely click on the uBO popup and notice on the extreme left of the domain, there's no domain connection notification color strip for `raw.githubusercontent.com`, but it will appear if you refresh the document.

As discussed in https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/96

### Expected behavior:

![](https://i.gyazo.com/9dcfe7679b3820646f204fadd25f91b7.png)

### Actual behavior:

![](https://i.gyazo.com/70d306256e920f29cdf96d734ff05698.png)

### Your environment

* uBlock Origin version: 1.20.3b8 
* Browser Name and version: Chromium 77/Firefox 69
* Operating System and version: Win 10

**Comment by gorhill** [comment]
There is no pluses/minuses, meaning no network requests were processed by uBO, hence no color strip. I got the color strip when trying to reproduce the first time, but not the second time -- that is because quite probably the browser pulled the page from its memory cache, hence uBO's onBeforeRequest is bypassed. This is the expected behavior when uBO's listener is bypassed.

**Comment by uBlock-user** [comment]
so this is to be expected and this is not a bug ? It doesn't make sense to me as it happens on first load sometimes, when it shouldn't.

**Comment by uBlock-user** [comment]
Clear the cache regarding `github.com` domain if you still cannot reproduce.

**Comment by gorhill** [comment]
> It doesn't make sense to me

The pluses/minuses and color strip are reported according to how network requests were handled by uBO. No network request = nothing was handled = no pluses/mimuses, color strip. Asking uBO to artificially report something is asking to uBO to lie to users. If there is no pluses/minuses/color strip, you know the resource was pull from the short-term browser cache.

**Comment by uBlock-user** [comment]
Why does it happen on first-load ? That doesn't make sense to me. That's what I meant by not making sense in my response.

**Comment by uBlock-user** [comment]
> It does not matter which load you reproduced it, what matters is that uBO's listener is bypassed by the browser because of short-term browser cache.

Well, okay if you say so.

**Comment by gorhill** [comment]
> Why does it happen on first-load ?

uBO does not manage the browser's internal behavior of its short term memory cache, the browser decides.

**Comment by uBlock-user** [comment]
Thanks, needed to file it here for clarification.
