### ISSUE TITLE
Adverts are showing on bing.com and msn.com

### ISSUE THREAD

**Issue by knightmeister** [uBlockOrigin/uBlock-issues#661]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have recently switched to Bing and note that ads are loaded in Bing results along with MSN.com. I'm using Chrome 75 and uBlock Origin 1.20

I note #186 reported this and was closed as a dupe of #180. I'm running the latest of Chrome and uBlock Origin so I figure this is a bug.

### A specific URL where the issue occurs

https://www.bing.com/search?q=nintendo+switch&go=Search&qs=ds&form=QBRE

### Steps to Reproduce

1. Go to bing.com
2. Enter a phrase which has keywords likely to be targetted
3. Perform the search

### Expected behavior:

Ads are blocked

### Actual behavior:

Ads are loaded and are not blocked

### Your environment

* uBlock Origin version: 1.20
* Browser Name and version: Chrome 75
* Operating System and version: Windows 10 1903/19H1

**Comment by uBlock-user** [comment]
> Do not post any filter list issues or issues where website's functionality is broken. We have uAssets issue tracker for that, post there instead.

**Comment by uBlock-user** [comment]
@mapx-
