### ISSUE TITLE
the logger window does not open full screen

### ISSUE THREAD

**Issue by Hifexar** [uBlockOrigin/uBlock-issues#663]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The logger window does not open full screen.

You can see it here:
https://gyazo.com/0967199bdb5511e6e29a14c0d77dfb91

Steps to Reproduce:
1. Open the logger.

Is it possible as an option to leave the ability to work the logger to work in the tab? The pop-up window is very inconvenient.

Firefox 67.0.4 x64
Windows 7 SP1 x64
uBlock Origin v1.20.3b8

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open the logger.

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

Firefox 67.0.4 x64
Windows 7 SP1 x64
uBlock Origin v1.20.3b8

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
> Is it possible as an option to leave the ability to work the logger to work in the tab? The pop-up window is very inconvenient.

https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#tip

**Comment by uBlock-user** [comment]
> The logger window does not open full screen.

Can you not maximise manually ?

**Comment by Hifexar** [comment]
No, I can't maximize it manually. It's not working. Maximization is not active. This can be seen in the screenshot. This is a separate window, with which nothing can be done except as collapse. Or resize the width and height manually. This is not a tab but a window without controls.

**Comment by Hifexar** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/The-logger#tip

What should I see at this link?

**Comment by uBlock-user** [comment]
> What should I see at this link?

Hold the Shift key while clicking the "Open the logger" icon to toggle between opening the logger in a separate window or in a separate tab. uBO will remember that setting when you open the logger next time, without having to hold the Shift key.

> No, I can't maximize it manually. It's not working. Maximization is not active. This can be seen in the screenshot. This is a separate window, with which nothing can be done except as collapse. Or resize the width and height manually. This is not a tab but a window without controls.

Not sure why it's like that for you., on my device, I can minimise/maximise and change the size of it as I want.

**Comment by Hifexar** [comment]
"Hold the Shift key while clicking the "Open the logger""

Ооо! Thanks!

**Comment by Hifexar** [comment]
"Not sure why it's like that for you., on my device, I can minimise/maximise and change the size of it as I want."

Homes in Windows 10, too, like works. But it is necessary to specify this. And in office in Windows 7 at me doesn't work.

**Comment by uBlock-user** [comment]
I edited my last reply, I can't maximise it either on Firefox, I can still re-size it though.

**Comment by Hifexar** [comment]
OK, well there is a workaround when using shift. That's enough for now.

**Comment by uBlock-user** [comment]
Regarding the maximising window, that's a Firefox behavior unnfortunately.

**Comment by gorhill** [comment]
I could add an advanced setting to allow the popup window to be just a normal window instead a popup panel.

**Comment by Hifexar** [comment]
"I could add an advanced setting to allow the popup window to be just a normal window instead a popup panel."

That would be nice.

**Comment by Shail-Shouryya** [comment]
Also using Firefox (Mac OS X 10.14.5), can confirm that the uBlock Origin opens in a new window without any ability to close or minimize it. Tried force quitting Firefox, opening it up again, and the logger window also opened up as Firefox restored my previous session. It would be nice if there was a feature to close/minimize the popup window so we could close it after we finish working with it, as of now I need to resize it and move it away to get it out of the way of what I'm working on.

Application info:
Name 	Firefox
Version 	68.0.1
Build ID 	20190717172542

uBlock Origin v1.21.2

**Comment by gwarser** [comment]
> uBlock Origin opens in a new window without any ability to close or minimize it.

This is Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1516819

**Comment by uBlock-user** [comment]
Set `loggerPopupType` to `normal` to enable maximisation. Setting available in the dev build as an advance setting.
