### ISSUE TITLE
Disallow a website from removing the scrollbar and greying out the background, while displaying a pop-up ad

### ISSUE THREAD

**Issue by rubyFeedback** [uBlockOrigin/uBlock-issues#664]
This is purely a suggestion.

I have noticed in the last ~2 weeks or so that there is an increasing
amount of websites that:

a) detect content blockers such as ublock origin

and

b) pester users via pop-ups and state "disable adblocker".

Now - I can use ublock origin's "pick" functionality to block this
partially, but upon re-visiting, the pop-up appears again.

Not only that but there are two main things that happen a lot:

1) The scroll bar disappears; I can no longer scroll.
2) The background is greyed out so that I can no longer read it.

Since that is so common, I would like to suggest two changes.

(Of course the best would be to not allow websites to pester people
via pop-ups, but this may be harder to code.)

I suggestion that:

1) ublock origin has an option to always display the scrollbar.

This may require some behaviour change to javascript. I do not know
why remote websites can control my browser anyway; and I may understand
that this is not ublock origin's primary goal, but I think it is 
associated indirectly since websites that show ads often use this.

This option could be in some preferences websites or something.

and

2) To disallow websites to grey out the background.

You may say that this is up to the browser, which may be true; but
ublock origin already is able to block content that the end user
deemds irrelevant, and this also is a change compared to what the
upstream developer tried to do.

Unfortunately with Google deciding that chrome users will have to
see ads, I do not expect Google's Chromium project to allow for
much flexibility here in the future.

Not sure how much work this would be but please feel free to close
this issue if it is considered too much work or unwanted.

**Comment by uBlock-user** [comment]
Have you reported these websites at https://github.com/uBlockOrigin/uAssets/issues ?

**Comment by uBlock-user** [comment]
For the scrollbar issue, set `allowGenericProceduralFilters` to `true`

Then add  these two filters in my Filters -- 

```
##body:style(overflow: auto !important)
##html:style(overflow: auto !important)
```

**Comment by gorhill** [comment]
Closing as invalid because it's (unspecific) filter list issues.
