### ISSUE TITLE
`* https://www.google.com/recaptcha/ * noop` is coloured in red and uBlock won't let me save it.

### ISSUE THREAD

**Issue by FatOrangutan** [uBlockOrigin/uBlock-issues#665]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

See title.
![Capture](https://user-images.githubusercontent.com/8336638/61002506-4bd5fd00-a37f-11e9-8371-444ff9e2c1e3.PNG)

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Add `* https://www.google.com/recaptcha/ * noop`. Notice that `* noop` is in red and uBlock won't let you commit it
2. Replace request type wildcard with something else so e.g. `* https://www.google.com/recaptcha/ sub_frame noop`. It works.

### Expected behavior:

This should be permissible as per the syntax on https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax.

### Actual behavior:

See STR.

### Your environment

* uBlock Origin version: 1.20.3rc2
* Browser Name and version: Nightly and Chrome stable
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
I just added `* https://github.githubassets.com/images/icons/emoji/unicode/1f440.png * noop` from the logger on current page, and cannot remove it in My rules. Commit button does nothing. Even "Save" reverts back to unmodified state.

1.20.3rc2 Firefox 70.0a1 20190709095414

**Comment by uBlock-user** [comment]
It doesnt get added on the Nightly, it just disappears.
