### ISSUE TITLE
uBlock does not appear to honor overriding default assets.json via Chrome policy

### ISSUE THREAD

**Issue by mikelagasse** [uBlockOrigin/uBlock-issues#666]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Attempting to designate our own default assets.json via Chrome policy (per https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin#modifying-the-list-of-stock-assets) doesn't seem to function as expected.
In my debugging, I see that the URL we designated for the location of our default assets.json is parsed by `storage.js` but I don't actually see our assets.json attempt to get pulled from the webserver as I believe it's designed to in `assets.js`. Instead, it uses the bundled assets.json.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Set Chrome extension policy via registry
Key: HKLM\Software\Policies\Google\Chrome\3rdparty\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\policy 
adminSettings with value {"timeStamp":1562713627423,"version":"1.20.0","assetsBootstrapLocation":"https://my-url-here.com/assets.json"}
2. Install uBlock Origin
3. View settings and see only default assets.json is loaded

### Expected behavior:

We expect the our designated custom `assets.json` to be loaded from the URL we specify.

### Actual behavior:

The extension's bundled `assets/assets.json` is loaded.

### Your environment

* uBlock Origin version: 1.20.0
* Browser Name and version: Chrome 75.0.3770.100
* Operating System and version: Window 10

**Comment by gorhill** [comment]
I never really completed usage of `assetsBootstrapLocation` through admin settings. I have fixed this locally, but I do not want to hold back the current release candidate -- the change needs to be tested through a beta build, so I will have to publish it once current release candidate reached stable release.

**Comment by mikelagasse** [comment]
Thanks, we'd be very interested in helping test the beta build when it's available!

**Comment by gorhill** [comment]
You can try the fix in the latest dev build: https://github.com/gorhill/uBlock/releases

**Comment by mikelagasse** [comment]
Can confirm this build works as expected, thanks!
