### ISSUE TITLE
uBlock stops all pages from loading

### ISSUE THREAD

**Issue by rossng** [uBlockOrigin/uBlock-issues#667]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Suddenly this morning I found that no pages were loading in Firefox. Disabling uBlock Origin makes things start working again.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Enable uBlock Origin
2. Go to [http://example.org/](http://example.org/).

### Expected behavior:

Page loads.

### Actual behavior:

Page does not load until uBlock Origin is disabled.

I get the following two errors in the browser console:

```
IndexedDB UnknownErr: ActorsParent.cpp:581
TypeError: setting is undefined ExtensionPreferencesManager.jsm:99:15
```

The first one happens repeatedly even when uBlock Origin is disabled, and doesn't seem to affect anything. The second only seems to happen when I enable the addon.

### Other notes

I could not reproduce this with a fresh profile, so I guess that makes it harder to debug 😞.

### Your environment

* uBlock Origin version: 1.20.2
* Browser Name and version: Firefox Developer Edition 69.0b3 (64-bit)
* Operating System and version: Windows 10 1903

**Comment by uBlock-user** [comment]
Did you toggle `dom.requestIdleCallback.enabled` in `about:config` ?

**Comment by uBlock-user** [comment]
>  could not reproduce this with a fresh profile, so I guess that makes it harder to debug

Likely a change in `about:config` setting is the cause.

**Comment by uBlock-user** [comment]
> IndexedDB UnknownErr: ActorsParent.cpp:581

Reproduced by @gwarser at https://bugzilla.mozilla.org/show_bug.cgi?id=1543880#c6
