### ISSUE TITLE
Image and CSS controls

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#669]
Please add to uBlock origin, the CSS block feature, so no need uMatrix just for Image and CSS, too add more control to image block, like Ctrl + Right Click to load an blocked image, so no need unblock all, and please add an setting to auto close panel popup when click in Reload and when click in Save, Auto Reload and Auto close popup, this can be optional, another good thing maybe use the context menu, for instance when click in uBlock with Righ Click, show Temp Allow Script 'n Reload, or Temp Allow Css 'n Reload or Temp Allow Images 'n Reload, etc is an good use of this menu

Thanks

**Comment by uBlock-user** [comment]
Images can already be blocked by the popup panel.

**Comment by gwarser** [comment]
@mrochaaa adding few dots in your post will help a lot.

**Comment by mrochaaa** [comment]
Image can be blocked, but today to UNblock you need to unblock  all images, is good an feature to unblock selectively, like with an ctrl + click etc, to unblock only one image.  And some times the popup can close automatically, if I have javascript off by default, I open the popup uncheck the Javascript and Reload, to allow temporally, why popup still open? Keep open in this case is useless to almost all users...
