### ISSUE TITLE
Fake replies instead of blocking

### ISSUE THREAD

**Issue by Bartolomeus-649** [uBlockOrigin/uBlock-issues#670]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Instead of blocking a request it would be great if it was possible to return a fake response. Possible responses could be:
1. An http "error"
   1. Like...
    204 (No Content),
    404 (Not Found),
    408 (Request Timeout), 
    410 (Gone), 
    418 (I'm a teapot), 
    426 (Upgrade Required), 
    429 (Too Many Requests), 
    451 (Unavailable For Legal Reasons),
    503 (Service Unavailable)
    . . . and so on.
    2. When selecting to return an error instead of blocking the request, the error returned should be, if possible, randomized and look "genuine" (correct times, sizes, context and so on).

2. A fake empty or striped down response
    A http result code 200 is returned, but the response is "empty". What empty means would depend on the request.

3. Get a real response once, castrate it, and then use it for this and all future request to that resource. It should be possible to manually modify this captured response.
   Perhaps a central repository of castrated responses could be established in a similar way that filters work today?

4. For fonts, there should be a local copy of the most used fonts on the web (or a central repository of fonts on GitHub, which would be checked when no local font match the requested font)
   There should also be a mapping between specific fonts to generic local replacement fonts.

### A specific URL where the issue occurs
N/A

### Steps to Reproduce
N/A

### Expected behavior:
N/A

### Actual behavior:
N/A

* uBlock Origin version: vNext
* Browser Name and version: All
* Operating System and version: All

**Comment by uBlock-user** [comment]
> An http "error"

A client can't return those, those are web-server responses. 

> For fonts, there should be a local copy of the most used fonts on the web (or a central repository of fonts on GitHub, which would be checked when no local font match the requested font)
There should also be a mapping between specific fonts to generic local replacement fonts.

Something like Decentraleyes would do.

**Comment by gwarser** [comment]
>     2\. A fake empty or striped down response

This is already possible:

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect

For other features you will need to provide real case where it will help.

**Comment by uBlock-user** [comment]
> It should be possible to manually modify this captured response.

Possible in Firefox only atm.
