### ISSUE TITLE
[feature request] Block CSS @media queries

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#675]
Running the the test on http://ip-check.info shows that it is possible to detect (and fingerprint) browser window size using CSS @media queries - even with JS blocked, and even when all CSS is blocked with uMatrix.

I think this makes it possible for a web site to do the following:

1. Display a page with @media queries and have elements (link/buttons) which show or hide based on what the @media has detected

2. The user navigating through the site can click such (displayed and not hidden) link thus confirming back to the site "Yes, this is my browser size, so fingerprint me".

Can uBO help to avoid that by a feature blocking @media queries?
[Yes, I know it may affect how the UI of a website is supposed to look]

**Comment by gorhill** [comment]
You were already given this answer in the past regarding fingerprinting: <https://github.com/uBlockOrigin/uBlock-issues/issues/104#issuecomment-401402399>. That answer still applies.

**Comment by emanruse** [comment]
I understand.
Sorry.
