### ISSUE TITLE
Can uBlock "unwrap" or prevent this kind of selection wrapping?

### ISSUE THREAD

**Issue by AnthonyMastrean** [uBlockOrigin/uBlock-issues#676]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On Atlassian's developer blog, they have this horrible Tweet selection thing. It actually wraps whatever text is selected in a new anchor tag.

![image](https://user-images.githubusercontent.com/217842/61549506-336c7f00-aa1e-11e9-83ea-7bf115105e02.png)

```html
<a class="inline-tweet-link" href="https://twitter.com/intent/tweet?source=webclient&amp;amp;via=atlassian&amp;amp;text=Git subtree is a great alternative&amp;amp;url=https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree" target="_blank">it solves lots of the problems</a>
```

### A specific URL where the issue occurs

https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

### Steps to Reproduce

1. Go to the site mentioned
2. Select some text
3. Notice the Twitter layover link thing
4. Inspect the element, if you wish (the actual effect appears to be achieved through CSS, can uBlock suppress CSS selectors/rules?)

### Expected behavior:

I'm inexperienced with custom rules. So, I'm not sure how to write it, if it is even supported. It would be neat if uBlock could unwrap the text or prevent it from being wrapped, at all, by removing the behavior from the CSS.

### Actual behavior:

The naive solution doesn't unwrap, it disappears the entire selected text!

```
atlassian.com##.inline-tweet-link
```

### Your environment

* uBlock Origin version: 1.20.0
* Browser Name and version: Microsoft Edge | 77.0.218.4 (Official build) dev (64-bit)
* Operating System and version: Windows 10 Pro 64-bit 1903

**Comment by AnthonyMastrean** [comment]
Well, now that I've written it all out and looked over the checklist, this question is a "support issue or a question". Go ahead and close it. If I find out that uBlock _cannot_ unwrap elements like this, maybe I'll reopen as an "enhancement" request?

**Comment by gwarser** [comment]
For example: `www.atlassian.com##+js(addEventListener-defuser.js, mouseup)`

**Comment by uBlock-user** [comment]
comes from `https://3kllhk1ibq34qk6sp3bhtox1-wpengine.netdna-ssl.com/wp-content/cache/autoptimize/js/autoptimize_767ceeb9abcdfbeced64e97f2d426d19.js` blocking that script will do it too.
