### ISSUE TITLE
Custom Command

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#678]
I'm using Foxy Gestures addon, which have an feature to use an custom script, I'm use uBlock Origin with javascripts and images ever disabled for all sites, because my net is very bad, what script I can use in Foxy Gestures to do it: 

Script 1 : "Enable javascript on this site" (Per site switch) and reload page

Script 2: "Enable Images (Noop Local Rule)  and reload page

someone can help me please!

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uBlock-issues#ublock-issues

> Support issues and questions are handled at /r/uBlockOrigin.
