### ISSUE TITLE
Dead code in `assets.js` and trailing whitespaces in `scriptlets.js`

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uBlock-issues#679]
The code here is no longer useful, because the built-in resource is now immutable: 
https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L981

The variable `noRemoteResources` can also be removed.

**Comment by gorhill** [comment]
Not everybody may have downloaded the modified `assets.json`, so I have to wait until I am confident everybody has the latest version in which there is no remote URL for `ublock-resources`.

**Comment by jspenguin2017** [comment]
@gorhill Another minor issue, trailing whitespace on these lines: 
https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L118
https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js#L710
