### ISSUE TITLE
Use 2 digit ISO codes for language filters

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uBlock-issues#68]
uBO currently uses 3 letter ISO codes to identify languages/countries for supplementary regional filters. I don't see any apparent benefit and think it would be better if 2 letter ISO codes were used instead as they are more ubiquitous and omnipresent (appearing on most documents and websites).

For example uBO uses **DEU** to identify German/Germany; in the  2 letter scheme it would be represented simply as **DE** which I believe is more familiar to users.

I too was a bit confused when seeing the 3 letter scheme on uBO as I am mostly familiar with the 2 letter one.

_**Note:** Using uBO 1.16.8 on Chrome 66 with the default filters and settings._

**Comment by gwarser** [comment]
First introduced in https://github.com/gorhill/uBlock/commit/4bb07f1a5bf7ce2936fea1ba32657e9c7bc74439 original issue https://github.com/uBlockAdmin/uBlock/issues/30

**Comment by gorhill** [comment]
I don't see the point of changing what as been standing for years -- I find 3-letter is better. For example, Ukraine is `UKR` vs `UA` for 2-letter -- I think it's obvious which one is more evocative.
