### ISSUE TITLE
Automatic update of the extension to new versions

### ISSUE THREAD

**Issue by NDABBRU** [uBlockOrigin/uBlock-issues#683]
I suggest implementing the automatic version update feature. 
When a new version is released in Chrome the version I have is not updated. 
I have to uninstall and reinstall it every time.

Thank you!

**Comment by uBlock-user** [comment]
> Q: Why Chrome/Chromium is not updating uBlock Origin:

> A: When I publish a new version of uBO, I deploy gradually, starting with 5% of users then increasing every day: 12%, 25%, 50%, 100%. Deploying in stages lowers the negative impact of potential severe regressions: it limits the number of affected users (with the assumption that a severe regression would be quickly caught/reported by the early waves of users).

> Q: When should i expect uBO to auto update itself?

> A: After a week you should have been updated. I might not increase the percentage during the weekend because I assume there are less uBO users of Chromium/Chrome, meaning lower likelihood of severe regression being spotted/reported.

src -- `https://old.reddit.com/r/uBlockOrigin/comments/cextv8/ublock_origin_1210_is_out/`
