### ISSUE TITLE
Crashes on start  chromium 76.0.3809.87-1

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uBlock-issues#686]
Crashes on start upon updating Debian chromium to 76.0.3809.87-1, as does LINE, etc.

**Comment by jidanni** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=983675

**Comment by llacb47** [comment]
If the bug has resolved itself as per the chromium issue tracker shouldn't the issue be closed? Also, isn't this a Chromium issue and not a uBO issue?

**Comment by jidanni** [comment]
It resolved itself for only that one user.
Maybe it is a bug in newer chromium.
Maybe older packages are using something not allowed in newer chromium and need to be fixed.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933598

**Comment by gorhill** [comment]
Process crashes need to be reported to Chromium devs, uBO/uMatrix are written in HTML/CSS/JS, they are not supposed to cause a browser crash.

**Comment by jidanni** [comment]
(An extension crash, not a browser crash.)

**Comment by gorhill** [comment]
Extension crash is a process crash.
