### ISSUE TITLE
Using |*| to strict block everything no longer works.

### ISSUE THREAD

**Issue by tod222** [uBlockOrigin/uBlock-issues#687]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using |*| to strict block everything no longer works.

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Start a new FF profile.
2. Install uBlock Origin.
3. Open the uBO dashboard.
4. Click "I am an advanced user."
5. Click the "My Filters" tab.
6. Enter the following wildcard filter: "|*|" (vertical bar, asterisk, vertical bar).
7. Click the "Apply Changes" button.
8. Open a new tab.
9. Enter any URL (e.g., "https://www.google.com/") into the address bar.
10. Hit "Enter" or click the right arrow in the address bar to navigate to the URL.

### Expected behavior:

uBO will block the web page and display the strict blocking warning allowing you to disable strict blocking for the domain temporarily or permanently.

### Actual behavior:

The page is displayed without its other assets loading. For www.google.com it means the Google logo is not shown.

### Your environment

* uBlock Origin version: v1.21.2
* Browser Name and version: Firefox 68.0.1
* Operating System and version: Ubuntu 18.04.2 LTS

Originally [reported to reddit](https://old.reddit.com/r/uBlockOrigin/comments/ckjz8v/strict_blocking_broken_on_ff_6801/). A commenter there indicates that this issue could be caused by commit [41636c59fb4208544b4bb23a5ac6273399cab625](https://github.com/gorhill/uBlock/commit/41636c59fb4208544b4bb23a5ac6273399cab625).

**Comment by llacb47** [comment]
`|*|$all` or `|*|$document` will do what you want.

**Comment by uBlock-user** [comment]
`|*|` translates to `*` in uBO, so it's indeed a regression from the aformentioned commit.

**Comment by gorhill** [comment]
By design, related commit: <https://github.com/gorhill/uBlock/commit/41636c59fb4208544b4bb23a5ac6273399cab625>.

**Comment by gorhill** [comment]
The feedback was <https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/110>:

> if we have a filter like (lots of false positive - treated by unbreak list):
://ads.$domain=~ads.ac.uk|~ads.adstream.com.ro|...
> 
> I propose not to block the whole domain if:
> 
> - first party and not intended to totally block that domain (filters like ||example.com^ )
> 
> Now a site like https://ads.buscaempresas.co will be broken and a badfilter + excluding the domain for that sort of filter is necessary
