### ISSUE TITLE
cosmetic filters in about:blank iframe

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#688]
> ## Apester - Interactive content 

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

How block social in iframes now?

![obraz](https://user-images.githubusercontent.com/35370833/62144984-fc864b00-b2f2-11e9-9bda-af80232f6f90.png) |
--- |

### A specific URL where the issue occurs

`https://itsfoss.com/end-of-floppy-disk-in-linux/`

old metods down...:

```
apester.com,itsfoss.com##[class^="StyledShareProviderButtons"].ProviderIcons, [class^="StyledShareProviderButtons"].ProvidersText
```

I no prefere AdGuard Annoyance filter:

`||apester.com^$third-party`

### Steps to reproduce

> 
>    - open https://itsfoss.com/end-of-floppy-disk-in-linux/
>  -   scroll to the end of article
>  -   finish quiz or click on the arrow in frame top right corner
>   -  try hiding social icons and subtitle

**Comment by mapx-** [comment]
@gorhill 
`how to cosmetically hide elements in about:blank iframe` moved here (uBlock issues)

**Comment by gwarser** [comment]
This still does not work in quiz frame on `https://itsfoss.com/end-of-floppy-disk-in-linux/`,


- open https://itsfoss.com/end-of-floppy-disk-in-linux/
- scroll to the end of article
- click on the arrow in frame top right corner
- try hiding social icons and subtitle

**Comment by gorhill** [comment]
But that is just <https://github.com/gorhill/uBlock/issues/1744>?

**Comment by gwarser** [comment]
I tried manually adding:

itsfoss.com##.shareProviderButton
##.shareProviderButton
itsfoss.com##.share-providers-button
##.share-providers-button
itsfoss.com##.shareOverlay
##.shareOverlay

**Comment by gorhill** [comment]
There is still an issue which I need to investigate, the mutation observer does not work the in test case above. This means generic cosmetic filters and logging cosmetic filters does not work in the above test case. I don't know the reason for why the mutation observer does not work.

I found AdGuard seems to suffer the same issue as well -- it does not report the cosmetic filters in its logger for the test case above.

**Comment by krystian3w** [comment]
I recently tried to hide a loaded Google bar in the background with generics filters and no possible hide by:

* a "ABP" generic `###goog-gt-tt, .goog-te-banner-frame, #google_translate_element2`
* generic under the shadow-dom `*###goog-gt-tt, .goog-te-banner-frame, #google_translate_element2`


But these hide elements:

`*###goog-gt-tt, .goog-te-banner-frame, #google_translate_element2:style(display: none !important;)`

I haven't checked the in AdGuard or uBO beta version yet.

As  I see a "shadow-dom" filter with CSS in the logger for this precedent.

**Comment by gorhill** [comment]
> `*###goog-gt-tt, .goog-te-banner-frame, #google_translate_element2:style(display: none !important;)`

You shouldn't need to use `:style()`, this should work: `*###goog-gt-tt, .goog-te-banner-frame, #google_translate_element2`

**Comment by gorhill** [comment]
>  I don't know the reason for why the mutation observer does not work.

The page uses [document.open()](https://developer.mozilla.org/en-US/docs/Web/API/Document/open#Two-argument_document.open) to create a new document in the iframe -- that would be the reason for the mutation observer ceasing to work.

**Comment by krystian3w** [comment]
> https://github.com/uBlockOrigin/uBlock-issues/issues/688#issuecomment-663777917

but for some reason Google bar need CSS  - This could be another threat that someone would do a similar advertising mechanism and you would have to start using more scriptlets.

**Comment by gorhill** [comment]
> but for some reason Google bar need CSS

Please open a distinct issue for this with repro steps (I don't know what is "Google bar"), the issue here is for `about:blank`.

**Comment by krystian3w** [comment]
I've tracked the problem, I'm doing it myself by deactivating the entire CSP mechanism in the browser.

Then such a pressed item can bypass generic filters and requires a "shadow-dom" CSS or making a filter for a group of domains.

**Comment by gwarser** [comment]
It seems to be fixed by https://github.com/gorhill/uBlock/commit/8d3c4916b0a0a32a91a0f5bfd596ee58062c6c2b

Can you check?

**Comment by raszpl** [comment]
I was reading https://palant.info/2020/12/10/how-anti-fingerprinting-extensions-tend-to-make-fingerprinting-easier/ and came upon an example 

```
console.log(screen.width);
Object.defineProperty(Screen.prototype, "width", {value: 1280});
console.log(screen.width);
var frame = document.createElement("iframe");
document.body.appendChild(frame);
console.log(screen.width, frame.contentWindow.screen.width);
```
producing:
```
1920
1280
1280 1920
```

in https://github.com/gorhill/uBlock/issues/1740 I found @gorhill
":[1] It's a solution I have considered in the past: to make the content scripts able to inject themselves into source-less iframes. This is _already sort-of done by injected scriptlets, they will propagate to source-less child frames_."

Does this mean scriptlets should be injecting into _about:blank_ **iFrames**? Has this worked in the past? I cant get this to work. I can see in Chrome devtools  _about:blank_ iFrame context has uBO listed as injected, but my scriptlet is not executed. 
```
/// myscriptlet.js 
Object.defineProperty(Screen.prototype, "width", {value: 1280});
```
defined at userResourcesLocation, My filters: "*##+js(myscriptlet)".

```
console.log(screen.width);
var frame = document.createElement("iframe");
document.body.appendChild(frame);
console.log(screen.width, frame.contentWindow.screen.width);
```
produces:
```
1280
1280 1920
```
suggesting myscriptlet is injected into the main page, but not the _about:blank_ iFrame

**Comment by gorhill** [comment]
Your scriptlet can't be injected at `document_start`, so there will always be a delay before your scriptlet code execute. You will have to check the value later, not immediately after inserting the iframe.

**Comment by raszpl** [comment]
I watched a movie, came back and results are still the same. I tested old chrome 77 with uBO v1.30.6 just to be sure, still same result. I tried something different

```
var frame = document.createElement("iframe");
var html = '<body><script>alert(1)</script>Content</body>';
frame.src = 'data:text/html;charset=utf-8,' + encodeURI(html);
document.body.appendChild(frame)
```
uBlock didnt inject in this iframe at all (going by Chrome devtools console "javascript context" dropdown), not sure if its meant to since I googled up https://github.com/whatwg/html/issues/1753. It did inject into srcdoc variant
```
var frame = document.createElement("iframe");
frame.srcdoc = '<body><script>alert(1)</script>Content</body>'
document.body.appendChild(frame)
```
still no scriptlet injections.

One of the scriptlets I use for a long time starts with
`console.log("something here ",location.href)`
and I have a vague recollection of seeing it report about:blank as the source while debugging some popup happy websites, but I cant find/replicate it now. My question is - is my assumption that scriptlets are meant to be injected into same origin iframes correct?

**Comment by gwarser** [comment]
@raszpl are you using this filter with wildcard (specific-generic) `*##+js(myscriptlet)`? 

Does not work on `localhost:8080` for some reason.

I also tried with following filters and injecting is not reported in logger on `localhost:8080`, but works on `example.com`. Version with `localhost` instead of `*` works fine.

```
*##+js(test)
*##+js(nobab)
```
`test` -> `https://gist.githubusercontent.com/gwarser/63ab7869174bb2f0880361bf9719bd0b/raw/6bd71b1feba0498221a7abd3c4a17e39febbc42d/test.js`

```
<!DOCTYPE html>
<html>
        <head> 
        </head>
        <body>
        <script>
            var frame = document.createElement("iframe");
            frame.srcdoc = "<body><script>alert(1)</scr"+"ipt>Content</body>";
            document.body.appendChild(frame);
        </script>
        </body>
</html>
```

**Comment by gorhill** [comment]
Can't inject in `data:` or `srcdoc` iframe, this is a known extension API  limitation.

**Comment by gwarser** [comment]
Specific-generic scriptlets do not work on "TLD domain only" websites, `localhost` for example, but there are few in the wild - `http://pn/`? I'm sure there are more. `scriptletDB.retrieve` fails to retrieve any scriptlet? `hostnameToSlotIdMap.get()` called with empty string instead of `*`?

**Comment by raszpl** [comment]
@gwarser 
> but works on `example.com`

are you saying your `*##+js(test)` reports `"about:blank"` after 
```
var frame = document.createElement("iframe");
document.body.appendChild(frame);
```
?

**Comment by gwarser** [comment]
I did not checked embedded contexts. `*##+js...` scriptlet was not injected at all in my test on `localhost`.

**Comment by gwarser** [comment]
This does not work at all in Chrome? (Is this about this Chrome bug I cannot find now?)

Testing [`*##+js(test)`](https://gist.githubusercontent.com/gwarser/63ab7869174bb2f0880361bf9719bd0b/raw/6bd71b1feba0498221a7abd3c4a17e39febbc42d/test.js) on https://gistcdn.rawgit.org/gwarser/dcea28c77bf2f6cb1c77229a92509b33/be97d8483cb0fdbb69af87b4295b905722685b98/frames.html

Firefox 86: uBO rc2 logger shows three injections and console logs page, blank and srcdoc.

Chrome 87.0.4280.88: only one injection, only page address logged.

**Comment by gorhill** [comment]
> Is this about this Chrome bug I cannot find now?

No, scriptlets are injected differently in Chromium, at [webNavigation.onCommitted](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCommitted) time ([code](https://github.com/gorhill/uBlock/blob/2ffd3afb2d688067a14e126efcde3953613c5ee3/src/js/tab.js#L883-L886)), and the information received in such case is not the effective URL, it's just `about:blank`, in which case [uBO bails out](https://github.com/gorhill/uBlock/blob/2ffd3afb2d688067a14e126efcde3953613c5ee3/src/js/scriptlet-filtering.js#L384).

**Comment by gwarser** [comment]
Ok, now only `rawgit.org##+js(test)` is not injected into `srcdoc` but specific-generic works fine.

It's after https://github.com/gorhill/uBlock/commit/8d3c4916b0a0a32a91a0f5bfd596ee58062c6c2b, so rather expected.

**Comment by raszpl** [comment]
@gwarser
>This does not work at all in Chrome?

Thank you for confirmation, I was beginning to think I was going crazy.

and https://github.com/gorhill/uBlock/commit/990cff576de131488734050331348714050d1ff8 thank you @gorhill for quick fix :o 
I didnt even know about the test builds :( checking v1.31.3rc3 now:
https://gistcdn.rawgit.org/gwarser/dcea28c77bf2f6cb1c77229a92509b33/be97d8483cb0fdbb69af87b4295b905722685b98/frames.html

```
myscriptlet  https://gistcdn.rawgit.org/gwars...05722685b98/frames.html
myscriptlet  about:blank
myscriptlet  about:srcdoc
```

Works great now.

**Comment by gorhill** [comment]
> not injected into `srcdoc` but specific-generic works fine

Maybe I can come up with a fix for this in next dev cycle.

**Comment by raszpl** [comment]
srcdoc did work for me

**Comment by gorhill** [comment]
Closing as _obsolete_. Fixes were made and it's unclear if and what are the other issues left if any -- too many comments about various other stuff. Open clearly detailed and well narrow issues if there is still something to fix, and these have to be issues with real world implications.
