### ISSUE TITLE
Ublock Origen not blocking ads on Crunchyroll on Google Chrome 76

### ISSUE THREAD

**Issue by Rihcus** [uBlockOrigin/uBlock-issues#689]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Ublock Origen doesn't to seem to be working on sites like Crunchyroll  on Chrome 76. I had the same issue on on older versions of chrome but fixed it by disabling feature under chrome://flags called "Enable Network service" now on chrome 76 this option has been removed.

More info about "Enable Network service"
https://www.quora.com/What-does-enable-network-service-do-in-Google-Chrome-flags-Are-there-repercussions-for-disabling-it

[Description of the bug or feature]

### A specific URL where the issue occurs
http://crunchyroll.com

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [Open http://crunchyroll.com on Chrome 76]
2. [Play a video and ads apear]
3. [and so on...]

### Expected behavior:
I expected for block to block the ads and it didn't due to the Chrome 76 forces "Enable Network Service"
[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment
I run Chrome 76 both on windows and Mac with ublock Origen. Both where blocking perfectly on chrome 75 but upon update to chrome 76 blocking on Crunchyroll failed.

* uBlock Origin version: v1.21.6
* Browser Name and version:  Google Chrome Version 76.0.3809.87 (Official Build) (64-bit)
* Operating System and version: Mac OS Mojave and Windows 10

**Comment by gwarser** [comment]
`crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)` does not work for you? https://github.com/uBlockOrigin/uAssets/issues/1279#issuecomment-517348623

Are you /u/NeverForgetChainRule? https://www.reddit.com/r/uBlockOrigin/comments/ckgp74/crunchyroll_ads_getting_through_again/

@uBlock-user ?

**Comment by uBlock-user** [comment]
Tested on https://www.crunchyroll.com/boruto-naruto-next-generations/episode-117-remons-secret-786485

no ads appear!

**Comment by Rihcus** [comment]
> Tested on `https://www.crunchyroll.com/boruto-naruto-next-generations/episode-117-remons-secret-786485`
> 
> no ads appear!

Did you update to chrome 76? I did it manually It was working on 75. I tested it on stock settings and reset my entire browser still ads are coming through

**Comment by uBlock-user** [comment]
> Did you update to chrome 76?

tested on 76 and the current canary version 78, no ads, if I disable the filter, then only I see the video ad.

**Comment by uBlock-user** [comment]
Will need somebody else to report for feedback here -- @okiehsch

**Comment by gwarser** [comment]
At first I had problems with playing at all with this one `https://www.crunchyroll.com/gegege-no-kitaro/episode-66-the-shinigami-and-sakaiminatos-hidden-village-786498` (does not start?) and "start a free trial today!" `https://www.crunchyroll.com/to-the-abandoned-sacred-beasts/episode-6-the-king-of-the-beasts-786831`, but I tried few other videos, and all seems to work exactly the same on 75 and 77 without any ad.

So... Maybe it's something with your config @Rihcus ? Or problem on 76 only?

**Comment by gorhill** [comment]
Unless there is actual evidences that something is wrong in uBO, this has to be assumed a filter issue.

**Comment by okiehsch** [comment]
I can't reproduce any pre-roll ads.

> At first I had problems with playing at all with this one https://www.crunchyroll.com/gegege-no-kitaro/episode-66-the-shinigami-and-sakaiminatos-hidden-village-786498 (does not start?)

That video will not start even if I disable `uBO`.

**Comment by gwarser** [comment]
@Rihcus more data? Link to video? Maybe regional list?

**Comment by Rihcus** [comment]
So the weird thing I find with the crunchy roll ads are they are all "xxx anime streaming on Crunchyroll now".  Anyhow I completely uninstalled (deleted all app data) and reinstalled chrome and installed Ublock Origen with stock filters and am still getting ads. 

I then tried to run chrome canary Version 78.0.3874.3 (Official Build) canary (64-bit) stock no sync and I still get ads from any Crunchyroll video.

I tried to run the same stock setting on Ublock Origen on safari and didn't have any ads. (I know the safari is a fork). 

Idk if this helps but this the logs I got from  Version 76.0.3809.87 (Official Build) (64-bit)
when running this video https://www.crunchyroll.com/dr-stone/episode-4-fire-the-smoke-signal-786944

https://pastebin.com/raw/SXYwVUym

The safari version of Ublock Origen was uBlock Origin v1.16.0

All I know is so far when chrome://flags/#network-service was disabled Cr's ads stopped when the option to disable the feature was removed the ads came back.

**Comment by okiehsch** [comment]
Your log does not show the filter
`crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)`
There are some known issues with script-injections using `MacOS`, do you have the same issue with Windows 10?
I have no issues at `Crunchyroll` using Windows 10 or Linux.

**Comment by gorhill** [comment]
I went through the various video links published above and this is what I get with Chromium 76:

- Playback fails, without ads:
  - `https://www.crunchyroll.com/en-gb/boruto-naruto-next-generations/episode-117-remons-secret-786485`
  - `https://www.crunchyroll.com/en-gb/gegege-no-kitaro/episode-66-the-shinigami-and-sakaiminatos-hidden-village-786498`
  - `https://www.crunchyroll.com/en-gb/dr-stone/episode-4-fire-the-smoke-signal-786944`
- Playback works, without ads:
  - `https://www.crunchyroll.com/en-gb/to-the-abandoned-sacred-beasts/episode-6-the-king-of-the-beasts-786831`

After I disabled uBO in `chrome://extensions/`:

- Playback still fails, with a preroll ad:
  - `https://www.crunchyroll.com/en-gb/boruto-naruto-next-generations/episode-117-remons-secret-786485`
  - `https://www.crunchyroll.com/en-gb/gegege-no-kitaro/episode-66-the-shinigami-and-sakaiminatos-hidden-village-786498`
- Playback works, without ads:
  - `https://www.crunchyroll.com/en-gb/to-the-abandoned-sacred-beasts/episode-6-the-king-of-the-beasts-786831`

So it seems the site has an issue in the first place, it fails to play some videos, those which appears to require a pre-roll ads, even when uBO is wholly disabled (in which case the ad plays).

I tried with both AdGuard and ABP, and the broken playback issue is also occurring, except that this time the pre-roll ads are played.

**Comment by gorhill** [comment]
By the way, all the videos above played fine with no pre-roll ads in Firefox 68.

**Comment by Rihcus** [comment]
> Your log does not show the filter
> `crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)`
> There are some known issues with script-injections using `MacOS`, do you have the same issue with Windows 10?
> I have no issues at Crunchyroll using Windows 10 or Linux.

I tested ublock origin on a clean install of chrome Version 76.0.3809.87 (Official Build) (64-bit) with stock settings and still get preroll ads. Here are the logs:
https://pastebin.com/raw/m79UR4iG

I tried running Firefox version 68.0.1 on windows 10 with uBlock Origin v1.21.2 (just downloaded from the Firefox store today) and I get no ads. Here are the logs Firefox uBlock Origin.
https://pastebin.com/raw/kWMn3UwU

**Comment by gwarser** [comment]
Updated to Version 76.0.3809.100 (Official Build) (64-bit) and cannot reproduce.

**Comment by dumbusernameidk** [comment]
I get an ad on this video `https://www.crunchyroll.com/isekai-cheat-magician/episode-1-lost-ones-from-another-world-787185` using Chrome V76 and default filter lists. The filter `crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)` doesn't seem to work. Maybe the ads or only specific to region? I'm in the US if that helps.

**Comment by kamilion** [comment]
I just restarted chrome to get on 76, and hit this just now. US/Silicon Valley.
Logged in to an account that had previously been premium.
Tried to watch:
https://www.crunchyroll.com/if-its-for-my-daughter-id-even-defeat-a-demon-lord/episode-4-the-little-girl-and-the-incident-786961

ublock nor umatrix sees any request to static.vrv.co/houseads/
If I launch the inspector and turn on request blocking of static.vrv.co from there, I get a couple console log entries.
Console Log:
[www.crunchyroll.com-1565240378415.log](https://github.com/uBlockOrigin/uBlock-issues/files/3479912/www.crunchyroll.com-1565240378415.log)
uBlock Origin Logger:
[www.crunchyroll.com-1565240378415-ublock.log](https://github.com/uBlockOrigin/uBlock-issues/files/3479922/www.crunchyroll.com-1565240378415-ublock.log)

Somehow their requests are bypassing the filter hooks, as I don't see any references to vrv.co at all in umatrix or ublock origin's advanced view.

Happened before around aprilish, I added `https://static.vrv.co/houseads/*` to the devtools blocker around then, but it's only active while the inspector is open. Somehow it catches and kills the request though.

**Comment by uBlock-user** [comment]
> Somehow their requests are bypassing the filter hooks, as I don't see any references to vrv.co at all in umatrix or ublock origin's advanced view.

CR does make use of Application Cache, so probably related to that.

**Comment by Rihcus** [comment]
> 
> 
> I get an ad on this video `https://www.crunchyroll.com/isekai-cheat-magician/episode-1-lost-ones-from-another-world-787185` using Chrome V76 and default filter lists. The filter `crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)` doesn't seem to work. Maybe the ads are only specific to certain regions? I'm in the US if that helps.

I don't think so I only seem to get the ads on chrome. One firefox and safari using stock filters I don't get ads. I'm also located in the US.

This issue came up before chrome 76 to however under chrome's flag settings their was an option called enable network settings. With that feature, disabled crunchy roll ads seemed to be blocked. However, on 76 googles removed the flag and subsequently the option to disable it. Ads then came back.

**Comment by rushilmehra** [comment]
Why does this issue only happen on chrome? On safari and firefox I get no ads, but on Chrome I get ads. Is there a solution here? I've already tried to add the filter listed in this thread

**Comment by rushilmehra** [comment]
BTW - check my issue that was closed for being a duplicate above - it has steps to reproduce this issue 100% of the time.

**Comment by gwarser** [comment]
@rushilmehra I tried your steps and cannot reproduce.

**Comment by gwarser** [comment]
Wondering if `json-prune` may help here.

Shothing blindly:

     crunchyroll.com##+js(json-prune, setup, description setup ts)

uBO-dev required.

**Comment by rushilmehra** [comment]
Lol I've just been using Brave as my main browser. Works flawlessly.

**Comment by uBlock-user** [comment]
Brave is another Chromium clone, so that's not the case.

**Comment by rushilmehra** [comment]
Uh, brave is based off of chromium yes. There was a chrome flag that was removed by GOOGLE, that was at the core of blocking ads on certain sites, one of them being Chromium. If my proof as to ublock origin failing is "not the case", then what is the case? Why does it work on Brave and not Google chrome? Which by the way differs in many ways other than underlying functionality.

**Comment by uBlock-user** [comment]
>  There was a GOOGLE chrome flag that was removed by GOOGLE, that was at the core of blocking ads on certain sites, one of them being Chromium. 

There isn't a google flag that blocks ads, please avoid using this false statement as an argument, on the contrary that flag was causing network requests to bypass uBO and ads were seen when that flag was enabled, disabling the flag took care of that but since that flag was only experimental in nature it was removed by Google like it does with all things it tests. If it work on Chromium, it will work on all the forks/clones based off it and not the other way around.

**Comment by rushilmehra** [comment]
I said it was at the CORE of blocking ads - which it was, for many people. I have tested it on every device in my house with chrome 76, and all of them fail even with the filter mentioned above.

**Comment by rushilmehra** [comment]
Btw, I don't know if this makes a difference, but no ads show up when I use incognito mode - on every device. However, as soon as you use crunchyroll outside of incognito mode, ads will appear.

**Comment by uBlock-user** [comment]
> I said it was at the CORE of blocking ads

The experimental flag is called “Enable network service,” tells Chrome to launch a separate process for “service workers,” or background tasks for web pages. A few bugs in service workers, combined with the network service experiment, was inadvertently bypassing Chrome extensions. Google identified and [reportedly fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=891872) one of the bugs in time for Chrome 73 while the other was [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=933138) just in time for the stable release of Chrome 73.
