### ISSUE TITLE
sometimes i do not can click "create" button in "picker mode popup"

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#69]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

![2018-06-13-ciagle zapchany nos i to nie katar - forum sfd](https://user-images.githubusercontent.com/5884000/41338038-389a9994-6ef1-11e8-96f2-6e9f752defdd.png)
http://www.sfd.pl/ciagle_zapchany_nos_i_to_nie_katar_-t162290.html

example rule
`##.sticky.page-top:style(position: absolute!important;)`

if i refresh the site and scroll in down, them i now can click create button with the same rule
![2018-06-13-ciagle zapchany nos i to nie katar - forum sfd](https://user-images.githubusercontent.com/5884000/41338752-56f09540-6ef3-11e8-8894-9aec62e21902.png)

please fix it, because people may think that the rule is incorrect

### Expected behavior:

fix create button

### Actual behavior:

if i do not scroll down, them i do not can click "create" button in "picker mode popup"

### Your environment

* uBlock Origin version: 1.16.8
* Browser Name and version: chr 67.0.3396.79
* Operating System and version: w10

my settings
https://gist.github.com/KonoromiHimaries/afab54402a6cc37a168c2e55a0ef6896

**Comment by uBlock-user** [comment]
Because the sticky scroll down top menu header, for which the CSS selector you're applying, only appears after you scroll down a bit, not a bug with uBO in any way, that's how the website is built.

**Comment by gorhill** [comment]
By design, uBO won't let you create a filter for which there is no matching elements on a page.
