### ISSUE TITLE
support to receiving messages

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#690]
Need add support for receiving messages from other addons, messages to toggle global javascript, global images, cosmetic filter etc.  For instance to use Foxy Gestures or Shorkeys addons with custom scripts.

**Comment by uBlock-user** [comment]
Other addons can't detect what uBO is doing and neither can uBO see what other addons did, not possible.

**Comment by mrochaaa** [comment]
The other addon no need see what ublock is doing, the other addon need just toogle "Javascript on this site" or toggle "cosmetic filter on this site" this is quite possible just need an little ublock api. Sorry but uBO admins is closing very fast valid suggestions.

**Comment by gwarser** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3352
