### ISSUE TITLE
New Advanced Settings

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#693]
add new advanced settings:

Auto Reload = true
Keep popup (panel) open = false

Auto Reload when making some change in panel, block, unblock, site toggles etc, to reduce the number of clicks

**Comment by uBlock-user** [comment]
First stop removing the issue template like you have doing with every FR till now, secondly justify your FR with a use-case, don't just post a FR with "Add this, add that" category.
