### ISSUE TITLE
uBlock Origin's Bus Factor

### ISSUE THREAD

**Issue by medavox** [uBlockOrigin/uBlock-issues#694]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand 
that the issue I report is not a normal behavior

This is a non-technical issue.

### Description

Bus Factor of uBlock Origin
======

For those who don't know,
the bus factor of a codebase is how many developers have to be hit by a bus (or otherwise suddenly disappear) in order to kill the project.

If @gorhill was hit by a bus tomorrow, who -- if anyone -- knows enough about developing uBlock0 to continue the project?

[This page at GitTrends](http://gittrends.io/#/repos/gorhill/uBlock) shows that the Bus Factor of this project is 1: that is, it would only take @gorhil to disappear (or even quit!) for uBlock to be 'incapacitated'.

Who else has the "keys" to access core technical assets, 
such as the ability to make official releases?  
Are those backups secure?

The bus factor has nothing to do with a person's perceived reliability.
The best intentions and the greatest determination in the world cannot prevent:

* being literally hit by a bus,
* debilitating illness for oneself, 
    - or needing to care for a family member with same
* a sudden change in financial circumstances
* a war in or near your country disrupting infrastructure, or worse
    - For instance: Spanish oranges will be a lot more expensive for me after Brexit.
    If this was true of all food, would I have to work more hours in order to put food on the table
    (and have less time to contribute to open source)?

The list of reasons a person may no longer be able to keep up with their online commitments is endless.

And call me paranoid, but with the war against ad blocking in general getting worse,
the likelihood that some shady organisation will attempt to 'remove' @gorhill in some way also grows.

These are uncomfortable issues to think about. But in order to ensure the long-term survivability of
this project, there need to be contingency plans in place to handle likely scenarios.

No-Warning GitHub Takedown
------

### (with some silly legal argument or another)

- would the code survive?
    * obviously git is designed to be distributed, but who here can actually *pull* from @gorhill's dev machine or otherwise?
- where/how else can the core dev team communicate?
- are there public mirrors of the codebase?
    * are they up-to-date?

I recommend starting by mirroring the code on GitLab and BitBucket,
if this hasn't been done already.

@gorhill Disappearing
-----

In the event Raymond Hill disappears, 

* is there a way to take control of official releases?
    - Is that even desirable?
    - Would this project be better served by a fork releasing as a new addon?
    - But what about existing users who don't keep up with project news?
    - are there any other, project-specific assets that require access privileges?
    - Are their old installations secure?
* is anyone designated to takeover in this event?
    - are *they* reliable/safe/unbribable?

You might be able to rely on some other altruistic developer stepping forwards, coming out of nowhere and taking over the project smoothly.

But you can't guarantee or rely on the kindness of strangers. 
And the likelihood of this happening is strongly affected by the quality and nature of the codebase.

Is there sufficient developer documentation that *any* experienced JS developer could pick up this project and maintain it? 

Because that's what needs to be able to happen.
The next most experienced team member might be more of a community manager than a coder;
or the most willing may prove unreliable or have unethical motives (see 'uBlock')...

The goal should be to maximise the possible number of future maintainers.

Is the code written to be readable? or is it very idiomatic to @gorhill?

Even if there **is** a 'designated survivor',
the more people that can understand it, the better.
Many eyes make bugs shallow, and all that.

If this has all already been taken care of, then I apologise for barging in and wasting time.
I just woke up this morning and thought,
"What if the mafia gets to Raymond Hill? or worse, Google?"

Google could probably afford to pay Raymond $1,000,000 a year NOT to work on uBlock.

Just sayin'.

--------

This is about as fun to do or talk about as writing a will.

But, like writing a will, it needs doing.

Open source projects sometimes have difficulty getting 'non-fun' stuff done --
speaking from personal experience.

They also have a tendency to be run by 'lone wolves' -- 
people who are unrivalled in their particular combination of expertises, 
and their ability to contribute their time. 
It can be very difficult to delegate to volunteers over the internet,
when you have invested some much of yourself into a project.

Conversely, finding quality volunteers can be tricky.

So I think it's worth checking this, now I've insulted everyone a little bit!

### A specific URL where the issue occurs

Not Applicable - non-technical issue

### Steps to Reproduce

Not Applicable - non-technical issue

### Expected behavior:

Code Mirrors, publically-designated takeover devs

### Actual behavior:

?

### Your environment

Not applicable

**Comment by medavox** [comment]
[Here's an interesting talk](https://www.infoq.com/presentations/open-source-troubles-help) by a Scala developer about Bus Factor in Open Source that I couldn't find when writing the above issue. Note: It's an hour long.

**Comment by uBlock-user** [comment]
Closing this as this is not uBO bug. You can continue the discussion on uBO's Reddit.

**Comment by pipboy96** [comment]
@medavox FYI, GitTrends.io is not updated since 2017.

**Comment by gorhill** [comment]
Should I go away (however this happens), the project here should be considered archived, and whoever is free to fork and continue with a new name.

There is no designated person or group of persons to take over for the simple reason that it is not possible to transfer the trust earned over many years. Whoever would be interested in keeping the project alive will have to fork and earn the trust of the users, it's not something I can magically transfer to somebody else.

**Comment by medavox** [comment]
For posterity, [here](https://www.reddit.com/r/uBlockOrigin/comments/cmsu50/reply_on_issueublock_origins_bus_factor_probably/) is a link to my reply on the reddit.

I don't believe in rewriting history for reasons of vanity

@gorhill I do largely agree with what you said, but it shouldn't come to that. Continuation of the original project should be more desirable than some fork of unknown quality, long after the project becomes abandoned.

It's the responsibility technical users like us (all of us who use GitHub & uBlock0) to attempt to provide a contingency in case of unforeseen circumstances. Or if @gorhill chooses it, development support.

@gorhill you don't sound like you want help, and that is fine, obviously. Ultimately the bottom line is you don't owe anything to anyone, just because you published something on the internet.

You don't have to do anything, and you don't have to accept strangers on the internet sticking their noses where they're not wanted.

But if you feel that this project deserves to survive beyond you, it might be worth thinking about this in the future.

**Comment by pipboy96** [comment]
@medavox I wanted to same something to this effect, but you phrased it much better than I ever could.

**Comment by pipboy96** [comment]
@medavox The editing was just adding this text: `[...] and it's not clear how it actually computes the bus factor and how legitimate such estimates are.`

**Comment by gorhill** [comment]
> @gorhill you don't sound like you want help

I don't know what you want me to do -- I consider I am volunteering my time as much as I am willing to do. The way I see it is worrying about an issue created out of thin air -- I rather not spend time on this and rather keep spending time on fixing (and enjoying fixing) real, actual issues for the next releases.

The code base is all GPLv3, so if it has any value it will still exist and be used if I go away, developers will be free to fork and make it whatever they want, and users will be free to like and trust those forks according to their own judgment.

**Comment by pipboy96** [comment]
@gorhill I'm mostly concerned about ensuring this code will not be lost in the event the current repos will become unavailable for some reason.

**Comment by gorhill** [comment]
There is already over 1,400 forks as per GitHub, and it's also on GitLab: <https://gitlab.com/gorhill/uBlock> (I just need to remember to push more often).

**Comment by pipboy96** [comment]
@gorhill Is a guide on creating an auto-updated mirror going to be of any help?

**Comment by gorhill** [comment]
I see GitLab has this feature to mirror, I will need to read more about it -- not sure if such automated mirroring is frown upon by GitHub.

**Comment by pipboy96** [comment]
@gorhill Test with a non-important repo what happens if you force-push. If a mirror blindly overwrites existing data with new version, it could be made to delete entire history, which is against the point (see https://github.com/shadowsocks/shadowsocks for example).

**Comment by jspenguin2017** [comment]
> I'm mostly concerned about ensuring this code will not be lost in the event the current repos will become unavailable for some reason. 

I have a script running on AWS that backs up ~40 repos every week. The backup is archived to a ZIP file and pushed to a versioned S3 bucket. I also download the archive every week just in case. I'm sure I'm not alone in doing something like this, so there is no reason to panic. 

---

> Is a guide on creating an auto-updated mirror going to be of any help? 

Try Gitea. I think it supports that natively. 

> If a mirror blindly overwrites existing data with new version

That's a good question, I'm not sure what Gitea does when the mirrored repo receives a force push. Gitea is open source, so it shouldn't be too bad to find out and contribute if needed. 

---

> I see GitLab has this feature to automatically mirror

I'm afraid that feature is not free anymore. 
There were some discussions about mirroring before, but when it comes to mirroring entire repos, we couldn't find any cheap and easy off-the-shelf solutions: https://github.com/uBlockOrigin/uBlock-issues/issues/278

**Comment by pipboy96** [comment]
@jspenguin2017 

> I have a script running on AWS that backs up about 40 important repos every week. The backup directory is archived to a ZIP file and pushed to a versioned S3 bucket. I also download the archive every week just in case. I'm sure I'm not alone in doing something like this, so there is no reason to panic.

That's a good idea, but I am not sure if there is someone else actually doing the same thing, whose backup would be available at the moment of hypothetical GitHub repo shutdown.

> I tried Gitea, although it supports repo mirroring out of the box, there are a few other issues with Gitea. So I ended up writing a custom Bash script to backup the repos. Unfortunately this isn't something that a non-developer can easily do.

Git itself is not something very non-developer friendly. It makese sense to expect most people who try set up a mirror have at least some dev knowledge (at least basic understanding of command line).

**Comment by medavox** [comment]
> I have a script running on AWS that backs up about 40 important repos every week. The backup directory is archived to a ZIP file and pushed to a versioned S3 bucket. I also download the archive every week just in case. I'm sure I'm not alone in doing something like this, so there is no reason to panic.

This is exactly what I was hoping for, thank you. I know I couldn't have been the only one to think about this.

In the interests of improving onboarding, and increasing the chances of new developers picking this up, may I also suggest writing a sourcefiles map -- just a one-line description of every JS file: 

* what it does
* why it exists (what problem does it solve)

This saves future newbie devs time from having to laboriously open every file to read the top doc comment, or work their way through the network of references by hand to find what they want.
