### ISSUE TITLE
Blank window bug

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#696]
Using the last ublock, win 7, and FF 67.0.4, with e10s disabled, I need single process because I have low memory, the logger window open with an blank page, show any content, this is an bug related with single process.

**Comment by gorhill** [comment]
Fill the template accurately as asked. By ignoring it you are sending the message that the template is pointless and can be dismissed by anybody.

**Comment by mrochaaa** [comment]
@gorhill, revised issue:



### Prerequisites





- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using the last ublock, win 7, and FF 67.0.4, with e10s disabled, I need single process because I have low memory, the logger window open with an blank page, show any content, this is an bug related with single process.

### A specific URL where the issue occurs

any url

### Steps to Reproduce

disable e10s in about:config (browser.tabs.remote.autostart;false), then click on ublock icon, when the panel open, click on logger icon, and done! Blank Window!

### Expected behavior:

Show the logger


### Actual behavior:

blank window!

### Your environment

* uBlock Origin version: Last
* Browser Name and version: FF 67
* Operating System and version: Win  7

**Comment by uBlock-user** [comment]
Can't reproduce that on FF 70, logger works even with `browser.tabs.remote.autostart` is set to false. Isolated to 67 ?

**Comment by gwarser** [comment]
I'm pretty sure `browser.tabs.remote.autostart` does nothing in Firefox 70.

**Comment by gwarser** [comment]
???

![image](https://user-images.githubusercontent.com/886325/62578034-7349b800-b8a0-11e9-8064-45cc8f83430f.png)

**Comment by gwarser** [comment]
:man_facepalming:  "known" issue. Resize window a bit - content will repaint.

**Comment by uBlock-user** [comment]
> "known" issue. Resize window a bit

Fixed in 68 -- https://bugzilla.mozilla.org/show_bug.cgi?id=1416505#c30

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/293

**Comment by gorhill** [comment]
This was also reported in <https://github.com/uBlockOrigin/uBlock-issues/issues/108>.
