### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by ediowar** [uBlockOrigin/uBlock-issues#697]
"The add-on could not be updated because of connection failure". Windows 8, Firefox  68.0.1 (64-bit), Pre-releases 1.21.7b4 and 1.21.7b3
![Connection failure](https://user-images.githubusercontent.com/44164186/62698269-6a163380-b9e5-11e9-8493-bebebae87f04.png)

**Comment by uBlock-user** [comment]
Something is blocking a tabless request from mozilla's CDN. Investigate on your end.

**Comment by ediowar** [comment]
When protection shield is off, the extension is installed.
![infected web resource](https://user-images.githubusercontent.com/44164186/62700022-8320e380-b9e9-11e9-844f-619eaadbd23d.png)

**Comment by ediowar** [comment]
Is it because of the addresses of gizmo in the file hostname-pool.js?

**Comment by uBlock-user** [comment]
BitDefender Antivirus is blocking the download on your side. So not a uBO issue.

**Comment by gwarser** [comment]
`http://surveygizmobeacon.s3.amazonaws.com/beaconconfigs/MjgwNDktQUYyRDQ3ODk0MjY1NEVFNUIwNTI3MjhFMDk2QTE3RDU%3D.json` Mozilla survey?

**Comment by ediowar** [comment]
Why doesn’t it block the download of the  Latest release 1.21.6?

**Comment by uBlock-user** [comment]
You also removed the issue template, so there's nothing to investigate.

**Comment by gwarser** [comment]
And all clean on Virustotal https://www.virustotal.com/gui/url/d88b3a8f81de52cebc16502cc08e9ed90a3751fd7ec84b6b5b913939251b8f17/detection

**Comment by ediowar** [comment]
When I deleted the antivirus, the browser page opened, and there was 1.19b in the extensions.
