### ISSUE TITLE
Stuck on strict blocking page

### ISSUE THREAD

**Issue by ialexsilva** [uBlockOrigin/uBlock-issues#699]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The strict blocking warning get stuck on try to load a specific url

### A specific URL where the issue occurs

http://altfarm.mediaplex.com/ad/ck/27725-213840-24755-85?kw=ondecomprar&mpre=http%3A//www.redbug.com.br/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Go to http://altfarm.mediaplex.com/ad/ck/27725-213840-24755-85?kw=ondecomprar&mpre=http%3A//www.redbug.com.br/
2. The strict blocking page appers
3. Click on **Temporary** or **Permanent** and nothing happens

Note: On firefox load a blank page

### Expected behavior:

Load page https://www.redbug.com.br/

### Actual behavior:

Pops up a blank page/stuck on strict blocking page

### Your environment

* uBlock Origin version: 1.21.6
* Browser Name and version: Chrome 76.0.3809.100
* Operating System and version: Win 10 Build 1903

**Comment by kowith337** [comment]
Why the need of going to `https://www.redbug.com.br` while `http://altfarm.mediaplex.com` get blocked?

1. It seems like the host `altfarm.mediaplex.com` strictly blocked due to ads or tracking server?
2. You may need to click :mag: and expand all parameter, then straight clicking to `https://www.redbug.com.br`, this is a better way to avoid going through the ads and/or tracking server before you landing to the real destination.

**Comment by gorhill** [comment]
That is a server-side error, the browser does fetch the document (as shown by the logger) but the server return status 204 ("No Content") and consequently the browser aborts navigation. You can click the destination link directly in that one instance (click the magnifier to expand the URL).
