### ISSUE TITLE
Adguard Base Filters should be renamed AdGuard English filter

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uBlock-issues#70]
Hi,
Adguard Base Filters is now titled AdGuard English filter:

> ! Title: AdGuard English filter
> ! Description: Filter list that specifically removes adverts on English language websites. English filter is supposed to work along with EasyList.

https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt

On the contrary, old AdGuard English filter is now titled AdGuard Base filter:

> ! Title: AdGuard Base filter
> ! Description: EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.

https://filters.adtidy.org/extension/ublock/filters/2.txt

**Comment by gorhill** [comment]
Duplicate of #35.

**Comment by uBlock-user** [comment]
@gorhill He's suggesting to rename Adguard Base Filters to Adguard English Filters in the 3p-filters.html page, as the mainatainer has done it so.

**Comment by gorhill** [comment]
The list was not renamed to "English", it always have been named this way. The other issue shows the statement by @ameshkov that this filter list is really intended as a generic one, just like EasyList is a generic one.

**Comment by uBlock-user** [comment]
If you say so, I felt a bit confusing how the `! Title` of  the filterlist Adguard Base Filter was changed to Adguard English Filter, so I avoided tagging it duplicate on the first glance.

**Comment by ameshkov** [comment]
Seems to be our mistake, the filter was renamed to `AdGuard Base filter` everywhere except the `_without_easylist` version. We'll fix it, thanks for notifying me.

**Comment by superlex** [comment]
Thanks :)
