### ISSUE TITLE
uBlockOrigin My Filters not working

### ISSUE THREAD

**Issue by AliWarren** [uBlockOrigin/uBlock-issues#704]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs
https://www.msn.com/en-us/news/us/new-york-plane-crash-airplane-crashes-into-house-faa-says/ar-AAFWTBM?OCID=ansmsnnews11
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:
I have www.msn.com & msn.com in My Filter list, but this page opened with no problem. It should have been blocked.
[What you expected to happen]

### Actual behavior:
The page was opened. So was https://www.msn.com.
[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by AliWarren** [comment]
This is a really difficult way for someone who is having a problem with an extension to report an issue. I AM NOT A DEVELOPER!!! Isn't there an easier way to this?

**Comment by kowith337** [comment]
As I remember, `MSN` also use ~~`retard logic`~~ oops, `instart logic`.

If you're use Chromium-based browser, did you've installed [uBO Extra](https://github.com/gorhill/ubo-extra) along with?

**Comment by kowith337** [comment]
Try add `$document` for strict blocking?

**Comment by uBlock-user** [comment]
```
www.msn.com
msn.com

```

I added those filters in My filters and those filters will be translated to `||msn.com^` -- 

![image](https://user-images.githubusercontent.com/21290713/63236738-8bd0af80-c25c-11e9-89a2-f933ec348952.png)

**Comment by gwarser** [comment]
> This is a really difficult way for someone who is having a problem with an extension to report an issue. I AM NOT A DEVELOPER!!! Isn't there an easier way to this?

Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
