### ISSUE TITLE
Procedural HTML filters does not work on Chrome and on Firefox

### ISSUE THREAD

**Issue by mozkan007** [uBlockOrigin/uBlock-issues#706]
I made a test by adding the specific filters on [this link](https://gorhill.github.io/uBlock/tests/procedural-html-filters.html) both on Chrome and Firefox with the latest Ublock Origin and all indicators on the page seem red. So what is wrong?

**Comment by mozkan007** [comment]
I tried this code ; gorhill.github.io##^#phf #a1 .fail:has(b) insted of this ; gorhill.github.io###phf #a1 .fail:has(b) and all indicators were green. So is there a punctuation mistake on the filters?

**Comment by uBlock-user** [comment]
You removed the template, fill all the details when you file a bug report instead of skipping it like this.

**Comment by mozkan007** [comment]
@uBlock-user  Apologize, you are right. I just wanted the report the bug briefly but I will be more attentive next time. Sorry again.

**Comment by uBlock-user** [comment]
>  just wanted the report the bug briefly

Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

**Comment by mozkan007** [comment]
> > just wanted the report the bug briefly
> 
> Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

Thank you.
