### ISSUE TITLE
Change addon's icon color when certain domain are found and blocked

### ISSUE THREAD

**Issue by jasomdotnet** [uBlockOrigin/uBlock-issues#707]
Hi, this is not an issue report but a feature request.

**The problem:**

I block most of the popular third party scripts. Especially all scripts (I found) from **Alphabet** (Google, Youtube), **Facebook**, **Jquery** to avoid tracking.

Unfortunately, it comes with a price in form of reduced functionality (mostly apis.google.com and jquery.com) or hidden content (I don't see that article has iframed Youtube video or Facebook post).

**The solution:**

There should be some configuration option "_set domains on which you wish to be notified they are present on the current page_". 

By "somehow" I suggest to change colour of the extension's icon to blue or what. I know that I can see all blocked domains when I click on the extension's icon, but this is not a way how to it. It takes a long time to get information (move mouse to the browser corner and read through all the blocked domains).

**Comment by gorhill** [comment]
Declined.

Colors are already being used in the current dev build to reflect current blocking mode.

**Comment by gorhill** [comment]
One thing you do not detail is in how would that color be useful beside just knowing some of the parties are being seen on the page?

**Comment by gorhill** [comment]
I am going to keep it open, this needs more discussion about the purpose with real life examples of why it's useful to a large set of users. The visual though would most likely need to be something else than the badge icon.

**Comment by jasomdotnet** [comment]
Basically, uBlock is missing convenient workflow when external tracker is content or feature (here you have problem hitting "large set of users").

**What I want is to be informed, in convenient way, that I may miss something on the website, since I block trackers which are content** (e.g.  Youtube iframed videos, Facebook iframed posts) **and trackers which are feature** (e.g.  scripts loaded from Jquery.com or Ajax.googleapis.com)

**Example on "trackers which are content":**

I block iframed Youtube videos (among other things, it comes bundled with Doubleclick.com code #DoubleTracker). Last week I searched for "unlock Android phone when you forgot your pattern". 

I visited various tech blogs and some of them had video from Youtube embeded in the post. I didn't saw this, because of the block. It isn't effective to check everytime uBlockOrigin pop-up and investigate if Youtube.com is on blocked domains list. 

Similar for Facebook post vs. the news sites I read. Twitter is fine, they use `blockquote` instead of `iframe`.

**Example on "tracker which are feature":**

For example Flixbus (something like Greyhound in Europe) use on their website ajax.googleapis.com which I block by default because it's another Alphanet tracker. I open the page and "search connection" doesn't work. So usually I go to uBlock pop-up, see the list of blocked domains and if I found familiar script I will create exception from the block.

-- 

> The visual though would most likely need to be something else than the badge icon.

Change icon's color was just a suggestion how to display the information. Another example is a small bubble with a number of extra scripts found in bottom-left corner of the icon with different background color.

--

> One thing you do not detail is in how would that color be useful beside just knowing some of the parties are being seen on the page?

I read this as follows: _"..and what to do when you have an information about such a script?"_

I do 2 things:

1. Temporarily disable the add-on (on all the junky scripts loads too)
2. In the case I plan to return to the site, I create an exception in "My filters". This is how my "My filters" looks now for Jquery.com and Ajax.googleapis.com:

```
||code.jquery.com^$third-party,domain=~hrvatska.sk|~lineageos.org|~ubuntu-touch.io|~beautifier.io|~jaspravim.sk
||ajax.googleapis.com^$third-party,domain=~gingersoftware.com|~croat.com|~flixbus.com|~google.com|~rome2rio.com|~flixtrain.com|~jaspravim.sk|~flightradar24.com|~active24.com
```
So this, when-you-know-what-to-do, is space for other "feature". I would welcome something like "_temporally allow this tracker_", "_allow this particular script for this session_". 

Something like NoScript has ([NoScript](https://noscript.net/) comes with Tor Browser). 

BTW, based on my previous experiences with NoScript, when I enabled uBlock first time, I thought that this "[plus / minus](https://i.imgur.com/aZiwfD3.png)" in pop-up was for this (but as I realized, it wasn't clickable).

![minus / plus in pop-up](https://i.imgur.com/aZiwfD3.png)
