### ISSUE TITLE
Add ":has-no-text" filter

### ISSUE THREAD

**Issue by sofutru** [uBlockOrigin/uBlock-issues#709]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ x I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

For example, i want to block youtube comments without timecodes in it, so i want to have this filter - "*:has-no-text(:)".
Or to block all news entries without my keyword. 

I couldn't find if this currently possible in uBlock, so i ask you to implement this.

**Comment by gwarser** [comment]
`:not(:has-text(foo))`

`:has-text(/[^:]/)`
