### ISSUE TITLE
i do not can paste text with right click

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#71]
the same bug at the
https://github.com/gorhill/uBlock/issues/3614

`chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html`

ubo 1.16.8
chr 67.0.3396.87
w10

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Disable all other extensions you're running and try again.

**Comment by KonoromiHimaries** [comment]
@uBlock-user i tried on firefox with ubo is only extension and still i do not have "paste" option i right click panel

![2018-06-13-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/41375736-3f548004-6f57-11e8-92bb-12e904f6fac5.png)

**Comment by KonoromiHimaries** [comment]
on the opera I have default configurations and the same bug
![2018-06-13-ublock panel sterowania opera](https://user-images.githubusercontent.com/5884000/41376447-8c778726-6f59-11e8-8f96-bea83dbb7f10.png)

**Comment by KonoromiHimaries** [comment]
example in this same settings on firefox  > ubo > "my filters" section, option "paste" normal works
![2018-06-13-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/41376854-b871eb2c-6f5a-11e8-9c4c-04590fd8583f.png)

**Comment by gwarser** [comment]
Left click to activate textbox element - then right click.

**Comment by gwarser** [comment]
Why rules list is empty?

**Comment by gwarser** [comment]
When rules list is empty I can paste only when I first click in first line (marked blue)

**Comment by gwarser** [comment]
CodeMirror quirk. On this demo https://codemirror.net/demo/theme.html I can paste only in active line.

**Comment by uBlock-user** [comment]
@gwarser So is it a bug ?

**Comment by uBlock-user** [comment]
So it's by-design.

**Comment by gwarser** [comment]
https://github.com/codemirror/CodeMirror/issues/3238

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by gorhill** [comment]
CodeMirror quirk, workaround is trivial: right-click on active line.
