### ISSUE TITLE
Add requires directive for filterlists

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uBlock-issues#711]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the past I could create one link to subscribe filterlist and some another one list required for good working. I think that would be good if you will add `requires` directive for requiring only uBO's inbuilt filterlists (for example I add to filterlist **!#requires fanboy-social** and that should activate Fanboy's Social list) or something another similar to previous behavior.

### A specific URL where the issue occurs
`https://adblockplus.org/abp_linkfactory`

### Your environment

* uBlock Origin version: 1.21.2
* Browser Name and version: Vivaldi 2.7.1628.30
* Operating System and version: Manjaro 18.0.4 Illyria

**Comment by gwarser** [comment]
<a href="https://subscribe.adblockplus.org?location=https%3A%2F%2Fraw.githubusercontent.com%2FMajkiIT%2Fpolish-ads-filter%2Fmaster%2Fpolish-adblock-filters%2Fadblock.txt&amp;title=polish-adblock-filters&amp;requiresLocation=https%3A%2F%2Feasylist.to%2Feasylist%2Feasylist.txt&amp;requiresTitle=easylist">Subscribe</a>

Decoded:

	https://subscribe.adblockplus.org?
    location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
    &amp;title=polish-adblock-filters
    &amp;requiresLocation=https://easylist.to/easylist/easylist.txt
    &amp;requiresTitle=easylist


`requiresLocation` and `requiresTitle`

**Comment by KonoromiHimaries** [comment]
https://github.com/gorhill/uBlock/issues/3651

**Comment by ediowar** [comment]
Raymond Hill, why https://github.com/gorhill/uBlock/releases/download/1.22.3b2/uBlock0_1.22.3b2.firefox.signed.xpi in 1.22.3b3 section?

**Comment by gorhill** [comment]
I just forgot to properly update the release notes -- thanks for pointing this out, it's fixed now.

**Comment by gwarser** [comment]
@gorhill what happened here?

**Comment by gorhill** [comment]
Someone remarked that I had forgotten to rename the links to `b3` in the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.22.3b3), they were still `b2` (I copy-paste from earlier release notes).

**Comment by ediowar** [comment]
You again had forgotten to rename the links to rc0 in the release notes.

**Comment by gorhill** [comment]
Declining this, I feel this is way too much work and code for what I am ready to spend time on.
