### ISSUE TITLE
Ads not appearing on Yahoo Mail when uBlock origin is set to OFF

### ISSUE THREAD

**Issue by waterreedshimmer** [uBlockOrigin/uBlock-issues#713]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Greetings. In Firefox, in Yahoo mail the Ads are not showing up when I deactivate uBlock origin and HTTPS everywhere and refresh website. I believe it is due to unsuccessful installation of Mozilla Firefox on Windows 10 May 2019 Update due to folder access blocked during install. Because setup.exe creates random install folder that can't be added before setup to Allow an app exception through Controlled Folder Access in Windows Security example: C:\Users\franc\Appdata\Local\Temp\7zS83D2BABO. And as I have a double boot, no idea what was being not blocked as nothing happens on Windows side so I uninstalled Firefox from Windows side only. Thank you very much =)

### A specific URL where the issue occurs

https://mail.yahoo.com/d/folders/1

### Steps to Reproduce

1. Enter Yahoo Mail
2. Click on OFF button in uBlock origin
3. Refresh Yahoo Mail

### Expected behavior:

The ads should have got back.

### Actual behavior:

The ads didn't get back. Still a blank space. There was no other Ad blocking system.

### Your environment

* uBlock Origin version: 1.21.2
* Browser Name and version: 
Name: Firefox
Version: 68.0.2
Build ID: 20190813150448
Update channel: release
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Os: Windows_NT 10.0
Launcher Process: Disabled due to failure
Multiprocess Windows: 1/1 Enabled by default
Remote processes: 6
Enterprise policies: Inactive
Google location service key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe mode: false

* Operating System and version:
Microsoft Windows 10 Home 10.0.18362 Build 18362 installed in empty computer as May 2019 Update in double boot with Ubuntu Linux 18.04 LTS, issue occurred on Windows side.

*  Security software
Antivirus: Windows Defender Antivirus
Antispyware: not detected !
Firewall: Windows Firewall
Actually I installed Spybot as side anti-virus anti-spyware to be able to use the option of adding an App exception through Controlled Folder Access, so I did rip out: Security Center Service - Integration into the Systems - and told them about issue. Because if I don't do this I can't install my paid and free software that aren't in Windows Store.

**Comment by gorhill** [comment]
What does uBO's logger report?

**Comment by gorhill** [comment]
You will need to go through all the steps and check all the boxes in the template, their purpose is to be sure something else is not causing your issue.

**Comment by gorhill** [comment]
> There was no other Ad blocking system

Mind that Firefox has tracking protection enabled by default.

**Comment by waterreedshimmer** [comment]
Hello, I can install again Firefox so to check the boxes.
I just don't want to sync a virus again on my Linux. Because I got all folders empty everywhere you can imagine...
Ok let's go =)

**Comment by waterreedshimmer** [comment]
It's not the add on as there are no ads at all in my Yahoo Mail with sync out, no profile and no add-ons. So issue doesn't come from you. What is uBO's logger ?

**Comment by waterreedshimmer** [comment]
For the moment UBO's logger tells ads but I don't see them.

**Comment by waterreedshimmer** [comment]
Yahoo did disconnect me and the ads did appear finally. I'm not with sync neither with extensions. There weren't ads without you. After installing you I could see ads back. No idea what it was ? So I think it's not you. But I can't tell what was blocking the Yahoo Mail ads ? As Firefox had no settings to block them.

**Comment by waterreedshimmer** [comment]
I'll keep Opera to be safe anyway. And thank you very much. You can close or continue topic. There is no answer to that and it is not me that did control block - put back - the ads on Yahoo Mail.

**Comment by gorhill** [comment]
Next time, if you do not want to go through all pre-check steps and check all the checkboxes, please report your issue to <https://www.reddit.com/r/uBlockOrigin/> instead of here.
