### ISSUE TITLE
Reduce brightness of blockingProfile badge

### ISSUE THREAD

**Issue by kramred** [uBlockOrigin/uBlock-issues#714]
Hi there,

thanks for the great work on uBlock and uMatrix and such!

The new uBlock badge colors draw a lot of attention to the icon, in my opinion.

This is a suggestion to reduce the brightness of the badge color indicating the blocking profile, in order not to strain the eyes too much.

As I cannot submit a PR directly, I'll post a link [here](https://github.com/kramred/uBlock/pull/1) ([changes](https://github.com/gorhill/uBlock/compare/master...kramred:kramred-patch-1))

~
Mark

![current_medium_mode_00F_64](https://user-images.githubusercontent.com/16719551/64057545-323e7e00-cb96-11e9-9728-5a0c460a00a0.png)
&darr;  
![new_medium_mode_008_64](https://user-images.githubusercontent.com/16719551/64057543-323e7e00-cb96-11e9-8483-c00bce802266.png)
---
![current_hard_mode_F00_64](https://user-images.githubusercontent.com/16719551/64057546-323e7e00-cb96-11e9-88b7-f3feb9ff47ee.png)
&darr;  
![new_hard_mode_800_64](https://user-images.githubusercontent.com/16719551/64057544-323e7e00-cb96-11e9-8d48-291743f45fc5.png)

**Comment by gwarser** [comment]
You don't need to submit pull request for your configuration changes :smiley: 

For me only red is too bright, so I changed it to #E70000. This did not helped much, because I have other extension with badge changing color to #F00 :(

**Comment by gorhill** [comment]
Too subjective, I do not want to get into that sort of never ending changes. It's why I made it configurable, everyone can change it to their taste.

**Comment by uBlock-user** [comment]
Find the colour that suites you -- `https://www.color-hex.com/`
