### ISSUE TITLE
uBlock 1.22.1b0 labels :style() filters as error in Picker

### ISSUE THREAD

**Issue by Grossdm** [uBlockOrigin/uBlock-issues#715]
![Screenshot_20190901-221800](https://user-images.githubusercontent.com/836787/64088403-435eca80-cd0f-11e9-96dc-87f8da95dc15.jpg)
![Screenshot_20190901-221900](https://user-images.githubusercontent.com/836787/64088410-507bb980-cd0f-11e9-8bbd-fc15bf23509a.jpg)

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After using the DOM selector, adding a simple `:style()` operator causes the DOM selector to label the selector as an error.

### A specific URL where the issue occurs

`https://www.usatoday.com/story/opinion/2019/08/30/james-comey-fbi-memo-leaks-trump-inspector-general-report-column/2157705001/`

### Steps to Reproduce

1. Use Firefox's menu to bring up the uBlock popup, then select the DOM selector.
2. On the page, select an element.
3. Append a valid `:style()` operator/modifier to the selector created by the DOM selector. I tried `:style(width: 100% !important;)` to be confident that it was valid CSS  syntax.

### Expected behavior:

I expect uBlock to accept the valid `:style()` expression.

### Actual behavior:

The DOM selector displays error as soon as the expression is added. As such, "Preview" was not available.

### Your environment

* uBlock Origin version:
1.22.1b0
* Browser Name and version:
Fennec 68.1 Build ID: 20190829134413
* Operating System and version:
Manufacturer=OnePlus
Model=ONEPLUS A6013
Device=OnePlus6T
Android=9: P (28)
OS=Linux
width=1080
height=2135
pixelFormat=1
refreshRate=60.000004fps
metrics.density=x2.625 xhdpi
metrics.scaledDensity=x2.625
metrics.widthPixels=1080
metrics.heightPixels=2135
metrics.xdpi=403.411
metrics.ydpi=409.903
RAM=7637MB
App Free=250MB/256MB

**Comment by gwarser** [comment]
Regressed by https://github.com/gorhill/uBlock/commit/ca9b29c7ececf7a45cfc6076c6e323f18dbbb04d

**Comment by Grossdm** [comment]
I opened another issue as noted above.
The behavior has not changed with the update for me.
