### ISSUE TITLE
uBlock crashes certain Chrome tabs on reload (F5)

### ISSUE THREAD

**Issue by valynor** [uBlockOrigin/uBlock-issues#719]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Clicking reload / pressing F5 or ctrl+shift+reload crashes the Chrome tab ("Aw, Snap!") on the URLs listed below.

### A specific URL where the issue occurs
https://mail.google.com/mail/u/0/#inbox
https://drive.google.com/drive/my-drive

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Navigate to the URLs above
2. reload tab
3. Aw, Snap! - tab crashes every time

### Expected behavior:

Tab should not crash on reload

### Actual behavior:

Tab crashes. Reload from the "Aw, Snap!" screen works. Next reload crashes the tab again. 
Switching off uBlock on those 2 URLs stops the crashes. So while this might be (in part) a filter issue I'm reporting this because whatever filter issue might exist this should never actually *crash* the browser tab, right?

### Your environment

* uBlock Origin version: 1.22.0
* Browser Name and version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* Operating System and version: Linux Mint 19.2 64bit

**Comment by gorhill** [comment]
Report to Google Chrome developers -- you tabs are not supposed to crash regardless of whether uBO is present.

You could try to launch Chrome from the command line, reproduce the crash and see what is reported at the terminal. In any case, a crash is something to be fixed by the browser developer, both web pages and uBO are plain HTML/CSS/JS, they are not supposed to end up causing process crashes.
