### ISSUE TITLE
Dynamic filter rules are not clickable on Linux platform - Manjaro 18.0.4

### ISSUE THREAD

**Issue by Locheed** [uBlockOrigin/uBlock-issues#721]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origins UI not working correctly. Dynamic filter rules are not clickable and global rules column is also missing. Local column is visible, but none of the +, - buttons are clickable and no hover effect. Tested this with different versions 1.16 to 1.22. With newest Chrome and newest Firefox Developer Edition. uMatrix fields work correctly, but not with uBlock.

### Expected behavior:

Should be clickable with red and green hover effects.

### Actual behavior:

All dynamic filter rules are not clickable. +All dropdown works.

### Your environment

* uBlock Origin version: 1.16 - 1.22
* Browser Name and version: FF DE 69.0b16 (64-bit) & Chrome 76.0.3809.100
* Operating System and version: Manjaro 18.0.4 illrya / KDE 5.16.4 / Kernel 4.19.69-1-MANJARO

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#i-am-an-advanced-user

Are you an advanced user ?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel

**Comment by Locheed** [comment]
> https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#i-am-an-advanced-user
> 
> @Locheed Are you an advanced user ?
> 
> > Should be clickable with red and green hover effects.
> 
> Not out of the box after installation, only available for advanced users.

Oh man. Spend hours debugging this and couldn't find it on google. In Windows, I've always been an advanced mode, but now with the change to Linux wasn't thinking that. Thanks!
