### ISSUE TITLE
v1.22.2 directly downloaded from AMO installs 1.22.0 on Firefox

### ISSUE THREAD

**Issue by rathann** [uBlockOrigin/uBlock-issues#723]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

1.22.2 downloaded from [AMO](https://addons.mozilla.org/firefox/downloads/file/3398284/ublock_origin-1.22.2-an+fx.xpi) still has 1.22.0 in the `manifest.json` file.

### A specific URL where the issue occurs

about:addons

### Steps to Reproduce

1. Install 1.22.2 from AMO (URL above)
2. go to about:addons and open uBlock Origin subpage
3. scroll all the way down and check the Version field

### Expected behavior:

Version field shows 1.22.2

### Actual behavior:

Version field shows 1.22.0

### Your environment

* uBlock Origin version: 1.22.2
* Browser Name and version: Firefox 69.0
* Operating System and version: Fedora 30

**Comment by uBlock-user** [comment]
manifest.json has the latest one  -- 

![image](https://user-images.githubusercontent.com/21290713/64682019-58b9be80-d49e-11e9-938d-2c64b99e1762.png)

So it should show the latest one in the Version field too on your end.

**Comment by uBlock-user** [comment]
![image](https://user-images.githubusercontent.com/21290713/64682420-0d53e000-d49f-11e9-9244-a8a80fdc8caa.png)

**Comment by rathann** [comment]
Sorry, I can't confirm that. I've just redownloaded the file from AMO (https://addons.mozilla.org/firefox/downloads/file/3392439/ublock_origin-1.22.2-an+fx.xpi) and it's still showing 1.22.0:
```
$ mkdir ublock && cd ublock
$ wget https://addons.mozilla.org/firefox/downloads/file/3392439/ublock_origin-1.22.2-an+fx.xpi
$ sha256sum ublock_origin-1.22.2-an+fx.xpi
843c7368534b21be741285172b1a19c4e75f5e188a46231dd02d3d831e014121  ublock_origin-1.22.2-an+fx.xpi
$ unzip ublock_origin-1.22.2-an+fx.xpi
$ grep \"version\" manifest.json 
  "version": "1.22.0",
```
If I'm downloading the wrong XPI file, then please point me to the right one.

**Comment by uBlock-user** [comment]
Why are you directly downloading the XPI instead of going to AMO and clicking on Add to Firefox ?

**Comment by uBlock-user** [comment]
Browse to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
Click on Add to Firefox and let it install.
Check the Version field which will show 1.22.2 as expected.

Try to reproduce that.

**Comment by gwarser** [comment]
File name at the end of URL does not seem to be meaningful. This part `...file/3392439/` however is.

**Comment by rathann** [comment]
@uBlock-user indeed, when installing via "Add to Firefox" button, it does show up as 1.22.2. The reason I'm installing from downloaded XPI is that I want to install it system-wide for all users.

And it appears I got the wrong link, thanks @gwarser . I was aware of the fileid being the meaningful part of the URL, but somehow ended up with the wrong one. Sorry for the noise.

**Comment by gwarser** [comment]
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/

- Version 1.22.2 -> `/file/3398284/`
- Version 1.22.0 -> `/file/3392439/`
