### ISSUE TITLE
Wrong context menu word choice on toolbar button

### ISSUE THREAD

**Issue by duncan-SF** [uBlockOrigin/uBlock-issues#725]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[wrong context menu word choice on toolbar button:

Opera has a toolbar up by the address bar where extensions may show their icons and a separate extensions bar which appears as a huge vertical strip to the left of the page.  On the extensions bar a uBO icon opens the logger.  While trying to hide that, to keep the extension bar from opening at all, I tried "Hide from sidebar" from both icons.  The one on the sidebar didn't appear to do anything but choosing "Hide from sidebar" from the one on the toolbar made uBO disappear from the toolbar (at the top) while the one in sidebar (at the side) stayed visible.

The least confusing fix would be to change the text of that menu item from "sidebar" to "toolbar".

It would also help to inform the user before he clicks that visibility can be restored through the developer mode of the Opera://extensions page.

Appologies if version 1.22.2 already covers this.  That version is not available to me on the Opera extensions list.]

### A specific URL where the issue occurs

[https://www.fiverr.com/]  

### Steps to Reproduce

1. [open the URL.]
2. [right-click the uBO icon in the toolbar.]
3. [read the context menu.]

### Expected behavior:

[an option "Hide from toolbar" is shown, among others.]

### Actual behavior:

[an option "Hide from sidebar" is shown, among others.
choosing that removes uBO from the toolbar and not from the sidebar.]

### Your environment

* uBlock Origin version: v1.21.8  (1.22.2 is not available on the Opera extensions page for me)
* Browser Name and version: Opera Version: 63.0.3368.88
* Operating System and version: Windows 8.1

**Comment by duncan-SF** [comment]
Curious: I don't see that message string anywhere in the code.  Perhaps it's a bug in Opera.

**Comment by uBlock-user** [comment]
Hide from sidebar is an Opera option, not from uBO.

**Comment by gorhill** [comment]
On my side it says "Hide from toolbar" in Opera 58. In any case, this is a browser issue, uBO does not control the contextual menu when right-clicking on its icon.
