### ISSUE TITLE
New tab/middle click on Filterlists tab doesn't open Filterlists tab in a new tab

### ISSUE THREAD

**Issue by Jap2-0** [uBlockOrigin/uBlock-issues#727]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the dashboard, right- or middle-clicking to open a different page of the dashboard in a new tab will open a new tab but on the same page as the original.

### A specific URL where the issue occurs

`chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/dashboard.html#settings.html`

### Steps to Reproduce

1. Open the dashboard to the "settings" page
2. Right click on "filter lists" at the top
3. In the context menu, select "open link in new tab"
(alternatively to steps 2 & 3, you can middle-click on "filter lists")

### Expected behavior:

The new tab would be on the "filter lists" page

### Actual behavior:

The new tab was on the "settings" page

### Your environment

* uBlock Origin version: 1.22.3b7
* Browser Name and version: Chrome 76
* Operating System and version: Chrome OS 76

**Comment by gorhill** [comment]
Well ideally it's not supposed to have more than one dashboard open at any given time. The fix if possible will be to avoid this in the first place.

**Comment by Jap2-0** [comment]
Agreed - and that does work, but I do find having multiple tabs of the dashboard open to be useful at times.  Being able to check the version of uBlock for a report to a filter list, quick toggling a list to see if that fixes a website, or searching through the contents of a list while writing some filters to test are all things that I do somewhat regularly.  Opening a new tab of the dashboard and then switching which page I'm on in that tab does work, so that's what I end up doing most the the time.

**Comment by Jap2-0** [comment]
Quick update:

You can no longer directly perform an action on the tabs (right/middle click) to open them in a new tab (I'm guessing because they're <span> elements instead of <a>), so if that's the intended fix (as you seemed to imply), we can consider this closed.  I can still cause the same thing to happen by manually putting a url into the address bar set to a different tab from the one I was last on (both with and without the dashboard open in another tab), but I'm assuming that that's intentional behavior and won't be changed.

(I still think that being able to have multiple tabs of the dashboard open at once is nice, but I won't fight on that front as it's still kind of technically possible.)

**Comment by gorhill** [comment]
I changed them to `span` in the re-designed dashboard because I received feedback screenshots of how the dashboard rendered on Firefox Preview and I saw that the navigation tabs were improperly rendered as un-visited links, I decided to avoid this sort of issue by simply using `span` elements -- I had forgotten about the current issue.

A workaround would be to create bookmarks directly to the panes which you visit often. For example, this is the URL for when the _"My filters"_ pane is selected in the dashboard:

    moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/dashboard.html#1p-filters.html

After removing the `dashboard.html#` portion from the URL, you get a direct URL to the _"My filters"_ pane:

    moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/1p-filters.html

Now you have a direct access to the _"My filters"_ pane which you could bookmark for one-click access.

**Comment by Jap2-0** [comment]
I didn't realize that was possible, but it works very nicely.  Thanks!
