### ISSUE TITLE
webext package does not work in Firefox

### ISSUE THREAD

**Issue by bigon** [uBlockOrigin/uBlock-issues#73]
Hi,

The following bug has been opened in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=899365:

===8<===
Firefox does not support the value `split` for `incognito` in `manifest.json`, see
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito
===>8===

**Comment by bigon** [comment]
@gorhill I'm not the initial reporter of this bug, but on my machine (debian unstable with ff 60) the extension is not even showing up in the extension list.

The cause of this might be somewhere else though

**Comment by gorhill** [comment]
What is reported in the browser console? On my side I just get the following uBO-related warnings when dropping the webext version into `about:addons` of FF60:

   addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing incognito: Invalid enumeration value "split"
    addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.
    addons.xpi	WARN	Please specify whether you want browser_style or not in your options_ui options.
    addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing incognito: Invalid enumeration value "split"
    addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.
    addons.webextension.uBlock0@raymondhill.net	WARN	Loading extension 'uBlock0@raymondhill.net': Reading manifest: Error processing incognito: Invalid enumeration value "split"
    addons.webextension.uBlock0@raymondhill.net	WARN	Loading extension 'uBlock0@raymondhill.net': Reading manifest: Error processing storage: An unexpected property was found in the WebExtension manifest.

**Comment by bigon** [comment]
This seems to be a duplicate for the bug https://github.com/uBlockOrigin/uBlock-issues/issues/52
