### ISSUE TITLE
Allow to set dynamic rules to the subdomain or domain in uBO panel

### ISSUE THREAD

**Issue by Diego-BF** [uBlockOrigin/uBlock-issues#730]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Some sites have multiple subdomains where the same dynamic rules are necessary. But, in these cases, actually the user need to go to "my rules" in settings to set a rule to a domain, or set the same rules each time he visits another subdomain.

I suggest that uBlock Origin allow the user to choose, in the panel, if he wants to set the changes made to the subdomain or domain visited, like uMatrix do.

### A specific URL where the issue occurs

- [calendar/maps/mail/*].google.com
- [www/music].youtube.com
- [www/clips].twitch.tv
- [*].slack.com

### Steps to Reproduce

1. access a subdomain of a site;
2. set dynamic rules to 1st/3rd party domains/subdomains;
3. access another subdomain from the first site, where it's necessary to set the same dynamic rules to the same domains/subdomains from step 2.

### Expected behavior:

Have a way to the user choose if he wants to set the dynamic rules to the subdomain or the domain visited.

### Actual behavior:

The user need to set the same dynamic rules at each subdomain he access, or edit the rules for a subdomain to the domain in the settings tab of uBlock Origin.

### Your environment

* uBlock Origin version: 1.22.2
* Browser Name and version: Firefox 69.0.1
* Operating System and version: Arch Linux

**Comment by uBlock-user** [comment]
Already possible through the panel. just expand the panel by clicking on the +all cell at the top.

**Comment by gwarser** [comment]
I think OP means something like scope selector in uMatrix - will be duplicate most likely.

**Comment by uBlock-user** [comment]
>  suggest that uBlock Origin allow the user to choose, in the panel, if he wants to set the changes made to the subdomain or domain visited, like uMatrix do.

There's no mention of scope selector in his suggestion.

**Comment by gorhill** [comment]
Duplicate of <https://github.com/gorhill/uBlock/issues/3297> as @gwarser pointed out.

**Comment by Remu-rin** [comment]
Can't comment on main repo, so I'm posting it here.
Just wanted to switch from uBO+uMatrix to uBO-only, tried `relax blocking mode` shortcut and it seemed to be even more convenient. But then I realized that both shortcut and manual clicks in dynamic filtering pane create rules for current subdomain and there is no equivalent of uMatrix `default scope level` setting (e.g. to create rules for `chromium.org` when I'm on `blog.chromium.org` page), so I need to edit some rules manually in dashboard.
Advanced setting would be great.

**Comment by baack** [comment]
> Duplicate of [gorhill/uBlock#3297](https://github.com/gorhill/uBlock/issues/3297) as @gwarser pointed out.

I think it's not a duplicate, because it's not about applying rules to the upper domain only.

Look, @gorhill, there are sites that have structure like that:

- hello.site.com
- basket.site.com
- aux.site.com
- countryname.site.com
- wallet.site.com
...
and so on.

And these sites change the sub-domain back and forth during browsing.
There are a lot of sites that work like that, including online shops and etc.

**How the person should use uBlock Origin in advanced whitelist mode on web sites like that?** 

P.S. In uMatrix this was possible but I don't understand how to use these sites with uBlock Origin the same way, please help.

**Comment by gorhill** [comment]
How is this not a duplicate? You want to set rules for `site.com`, and this is what <https://github.com/gorhill/uBlock/issues/3297> is about.
