### ISSUE TITLE
"Relax blocking mode + make permanent change" option in one shortcut

### ISSUE THREAD

**Issue by mitogoni** [uBlockOrigin/uBlock-issues#733]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[feature: "Relax blocking mode + make permanent change" option in one shortcut]

### A specific URL where the issue occurs

[https://www.flickr.com/explore]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[Relaxing blocking mode and making change permanent]

### Actual behavior:

[After applying "relax blocking mode" from keyboard shortcut you have to make it permanent by verifying in popup panel]

### Your environment

* uBlock Origin version: 1.22.3b15
* Browser Name and version: Firefox 69.0.1 (64-bit)
* Operating System and version: Linux 5.1.21-1-MANJARO x86_64 18.1.0 Juhraya

**Comment by gorhill** [comment]
> This is not needed when overview panel is hidden

Since the padlock button is now visible in the main panel, this is needed. It was needed only because the padlock was not visible in the old popup panel.

**Comment by gwarser** [comment]
> Since the padlock button is now visible in the main panel, this is needed. It was not needed only because the padlock was not visible in the old popup panel.

I said not needed because with hidden panel padlock button is not displayed. But I see now in My rules, that this is only temporary rule.

**Comment by gorhill** [comment]
> with hidden panel padlock button is not displayed

I need to fix this.

**Comment by gorhill** [comment]
I prefer to decline this. It makes sense to have to open the popup panel in order to review the current ruleset before persisting it, this ensures this is done in a conscious way instead of blindly.

**Comment by chilliger** [comment]
I miss a workflow where I'am able to permanently enable JS for a new site without beeing forced to use a mouse. This is currently what I do:

- Relaxe blocking mode with shortcut

- Open extension popup with shortcut

I'am not able to navigate in the popup with the keyboard to select the permanent change button.
@gorhill Any idea?
