### ISSUE TITLE
Relax mode enhancement 

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#734]
Add an option to "unRelax", for instance user use JS blocked for all sites ever, the new behavior:

when I "relax" this enable JS, if I use the shortcut again it re-enable JS and reload page, as an toggle!

**Comment by gwarser** [comment]
This https://github.com/uBlockOrigin/uBlock-issues/issues/692 will be to toggle no-scripting on/off.

Current one may be about "unRelax" or reset relaxing queue to beginning.

**Comment by uBlock-user** [comment]
@gwarser so a duplicate ?

**Comment by gwarser** [comment]
Of #371 ? 371 is closed, this one can be kept opened to remind about possible enhancement.

**Comment by mrochaaa** [comment]
how unRelax with current one?

**Comment by gwarser** [comment]
It's not possible yet.

**Comment by mrochaaa** [comment]
all right! I just want do add an last suggestion, in the other post the user suggest another shortcut (shift + etc) to unRelax, I think this is not ideal, I think ideal an "queue loop" using the same shortcut, this unique shortcut also is better to use with gestures programs like Strokes Plus etc, just  one gesture or "rocker" can toogle JS. Just an opnion. Thanks

**Comment by gorhill** [comment]
I am going to decline this.
