### ISSUE TITLE
Requests blocked by CSP are not counted as "requests blocked"

### ISSUE THREAD

**Issue by liamengland1** [uBlockOrigin/uBlock-issues#735]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Requests blocked by `$csp` network filters are not counted in the extension icon or popup user interface as "requests blocked on this page".

### A specific URL where the issue occurs

`https://oload.vip/f/mzovkEHLb8I`

### Steps to Reproduce

1. Add `||oload.vip^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' data: openload.co *.openload.co oload.vip *.oload.vip *.cloudflare.com *.oloadcdn.net;` to `My filters`
2. Visit `https://oload.vip/f/mzovkEHLb8I`

### Expected behavior:

Requests blocked by CSP are counted in the icon and extension popup UI.

### Actual behavior:

Requests blocked by CSP are not counted in the icon and extension popup UI.

### Your environment

* uBlock Origin version:  uBlock Origin 1.22.2
* Browser Name and version: Google Chrome 77.0.3865.90 
* Operating System and version: Windows 10

Note: I'm not sure if this is a bug report or an enhancement request, this might be intended behavior but I could not find any documentation stating so.

I reproduced this behavior in Nano Adblocker as well.

**Comment by uBlock-user** [comment]
Because uBO only sets the CSP header. Network requests are blocked natively by the browser, not by uBO.

**Comment by ediowar** [comment]
**gorhill**, you again had forgotten to rename the links to rc0 in the release notes.

**Comment by ediowar** [comment]
In order not to duplicate the links in the release notes better change
"Firefox: Click uBlock0_1.22.5rc1.firefox.signed.xpi... Thunderbird: Download uBlock0_1.22.5rc1.thunderbird.xpi..."
to
"Firefox: Click uBlock0_XX.firefox.signed.xpi below in Assets... Thunderbird: Download uBlock0_XX.thunderbird.xpi below in Assets..."

**Comment by gwarser** [comment]
@ediowar, does not work in release builds.

**Comment by ediowar** [comment]
Why not use a permalink in release builds? https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by gorhill** [comment]
Please move off-topic discussion to <https://www.reddit.com/r/uBlockOrigin/>.
