### ISSUE TITLE
Filter List with subfilter lists throwing out valid filter on last line of sublist

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#736]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Filter lists that have sublists are having the last entry of each sublist mangled with uBO description text when uBO recombines the sublist.

### A specific URL where the issue occurs
When subscribing/refreshing filters from main filter list `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt`

### Steps to Reproduce

1. Subscribe to list with sublists [[example list with sublists]](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)
2. observe logger is saying invalid filter for entries and referencing sublists
3. observe filter as parsed is combining last line and first line of ubo generated merged list
3. [and so on...]

### Expected behavior:
Filters all loaded properly

### Actual behavior:
![logger](https://user-images.githubusercontent.com/22258847/65635924-42882400-dfaf-11e9-8125-6af2c81aafea.png)

![combining filters](https://user-images.githubusercontent.com/22258847/65635931-46b44180-dfaf-11e9-8a38-182e138cdda9.png)

### Your environment

* uBlock Origin version: uBlock Origin 1.22.3b17
* Browser Name and version: Chrome & Firefox
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
Does it also happens if you put new line character (`\n`) at the end of file?

On linux text files without `\n` at the end are invalid :)

**Comment by gwarser** [comment]
Missing `\n` before `! <<<<<<<< ${subURL.href}\n`

https://github.com/gorhill/uBlock/blob/978f04219a1f41f3fab7ad5c38ec2a1a021920fe/src/js/assets.js#L262

**Comment by yourduskquibbles** [comment]
I think this is Fixed now in [1.22.5b0](https://github.com/gorhill/uBlock/releases/tag/1.22.5b0) from my test
