### ISSUE TITLE
uBlock Origin broken by latest update on FF

### ISSUE THREAD

**Issue by djh42** [uBlockOrigin/uBlock-issues#739]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Since uBlock Origin updated itself today it is no longer visible in my FF toolbar (FF 60.8.0esr on openSUSE Leap 15.0)

Deleteing and reinstalling the add-on made no difference. It is still listed as installed but does not show up in the toolbar nor on context menus.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Open brower
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
Look for uBlock icon on toolbar, or open context menu and look for it there

it is there

### Actual behavior:

[What actually happened]
Look for uBlock icon

it's not there

### Your environment

* uBlock Origin version: 1.22.4
* Browser Name and version: FF 60.8.0esr
* Operating System and version: openSUSE Leap 15.0

**Comment by gorhill** [comment]
Can't reproduce.

I downloaded Firefox 60.8.0ESR from <https://ftp.mozilla.org/pub/firefox/releases/60.8.0esr/linux-x86_64/en-US/>, installed latest uBO from <https://addons.mozilla.org/firefox/addon/ublock-origin/>, and all went well, no issue.

See what the browser console (ctrl-shift-j) reports.

**Comment by djh42** [comment]
Thanks for looking. I restarted FF and uBO has come back. Sorry for the noise.

(I leave FF running for as long as possible because I have to set up column-widths etc on a particular page every time I start it)
