### ISSUE TITLE
Privacy and Microsoft's acquisition of GitHub

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#74]
Now that Microsoft has acquired GitHub it means that each and every time a user downloads built-in filter list (GithHub hosted) the user reports to Microsoft "I am online at this time of the day, here is my IP address, my browser info - profile me please".

Considering that:

"uBlock Origin's main goal is to help users neutralize such privacy-invading apparatus"

please move filter lists out of GitHub. Microsoft (a PRISM participating company) doesn't have a history of respecting user privacy.

**Comment by Irbidan** [comment]
Do you think you're 'safe' using this platform or similiar? Microsoft, Google, Facebook (or WhatsApp), Twitter... These companies always collect some information from you to improve their services but this doesn't mean that they are going to sell your data. Even I would think that Github does the same.

I think there is a certain fear that a company that has hated Linux and other open source platforms or open source software goes forward.

**Comment by uBlock-user** [comment]
All platforms that store information can and do collect whatever information they can. There's no safe harbour from that.

**Comment by gorhill** [comment]
One can use [rawgit.com](https://rawgit.com/) if wanting to avoid pulling directly from `github.com`, example, import this URL into filter lists:

    https://cdn.rawgit.com/uBlockOrigin/uAssets/master/filters/filters.txt

More generally (given many other filter lists are pulled from GitHub as well:

    https://cdn.rawgit.com/[owner]/[repo name]/master/[path to list]

However as a result, the side effects described on rawgit's home page.

**Comment by emanruse** [comment]
> Do you think you're 'safe' using this platform or similiar? Microsoft, Google, Facebook (or WhatsApp), Twitter...

I don't use any of these. I access GitHub through TOR (and not quite actively).

> These companies always collect some information from you to improve their services but this doesn't mean that they are going to sell your data.

As per GDPR that requires separate consent because one may not be willing his persona to be used for "improving services" (really meaning: optimizing the business of the tech giants so they can become more and more reach, and more advanced in mass surveillance). And yeah... Google a is a charity organization :)

> I think there is a certain fear that a company that has hated Linux and other open source platforms or open source software goes forward or simply is trying to remove fears.

Unless I see all the software that this company creates released as FOSS and all back doors removed - I prefer to stay with the "fear".

> All platforms that store information can and do collect whatever information they can. There's no safe harbour from that.

GDPR is an attempt to stop this. Unfortunately almost all the GDPR related emails we all received are just meant to make us give consent to really non-GDPR compliant policies. Check https://noyb.eu/ - the situation is not much different with others.

Speaking of which: the privacy policy of the extension would need to inform the user about that the extension connects to 3rd parties and in this way shares personal data + to ask for consent before doing it (as per GDPR).

@gorhill - Thanks for the info. Which particular side effect do you mean? Also: would you recommend downloading one's selected lists on one's own server and then updating all clients directly from it? Considering you already have the code logic for this: Would you be willing to share in the repo a bash or other console script for this? Or at least point me to the code which does the downloading so I can tailor a script myself?

Thanks.

**Comment by jspenguin2017** [comment]
> I don't use any of these. 

Every server that is not ran by an extremist records access log, you are better off to stay away from the Internet. 

> I prefer to stay with the "fear". 

What is telling you that open source software are just magically safe? Have you verified those 50+ million lines of source code yourself? Do you compile every software you use from source? 

Before you say there are *other* people watching it, why did it take like 2 years for Heartbleed to be "discovered"? Who committed that vulnerability in the first place? 

> the privacy policy of the extension would need to inform the user about that the extension connects to 3rd parties

It does, you just didn't bother to read: https://github.com/gorhill/uBlock/wiki/Privacy-policy

> Which particular side effect do you mean?

RawGit only sync updates once a day. 

> would you recommend downloading one's selected lists on one's own server

If you got a server, you should do this. This also lifts loads off the filter servers.

**Comment by gwarser** [comment]
I have one proposition - cleanup xhr to not send cookies when updating filters. Looks like they are send when 3p cookies are allowed.

(Does anyone know where I was reading about this?)

**Comment by emanruse** [comment]
@jspenguin2017

I am aware of how logs work and of the inability to check every line of code. And yes - I do stay offline as much as I can. Of course I understand there is no magic bullet and all the rest of it but lets not derail into something off-topic, although it might be related. (sorry if my previous post sounded like an attempt to do so)

> It does, you just didn't bother to read: https://github.com/gorhill/uBlock/wiki/Privacy-policy

I have read it but it lacks the explicit clarity that "a remote server" actually means a company and in this way the extension becomes a tool for sending personal data. Also it seems that policy doesn't reflect the current situation as it says:

> The project is currently hosted on github.com, which is owned by GitHub, Inc.

> GDPR does not apply to non-profit personal projects.

I think you are wrong about that. GDPR is about data protection in general regardless of profit. Otherwise you may set a "non-profit personal project" and sell huge amounts of personal data which is surely a contradiction with GDPR. Check paragraph (15) and the definitions in [Article 4](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN#d1e1489-1-1)

Is the extension an automated means? - Yes.
Is there a filing system? - Yes (server logs -> DBs)
Does the extension process personal data as per GDPR definitions - Yes, as it receives it and transmits it to a filing system.

So considering that in this case @gorhill is a controller and a processor (using subprocessors) the extension needs to add transparency about all that and ask for explicit consent before making any connection whatsoever.

> RawGit only sync updates once a day.

Thanks for explaining. I didn't know that.

BTW I see rawgit.com uses Cloudflare = all traffic is decrypted by CF before it is communicated back and forth to the origin server + CF knows who visits, when etc. Also it is not immediately transparent how RawGit handles personal data - there is no privacy policy, nothing. Technically it is possible to profile and track user activity with a pattern of static IP address and user agent based on repeated connections for downloading the same filter files.

> If you got a server, you should host filters for your clients. This also lifts loads off the filter servers.

Thanks for the feedback. I agree with you. Ideally lists should be decentralized somehow but I have no idea how exactly.

@gwarser - Thanks for the advice. I always have JS and cookies blocked by default and when I enabled them it is temporarily (in a "private/incognito" window), so I don't think what you mention applies to my particular setup.

**Comment by uBlock-user** [comment]
Alright, this has gone far enough and converted to an offtopic discussion of another matter. Continue this discussion if you want to, at reddit.
