### ISSUE TITLE
Ublock has Delayed Response in Firefox

### ISSUE THREAD

**Issue by markko9** [uBlockOrigin/uBlock-issues#744]
In every version of Firefox I have dalayed response from uBlock Origin on some pages, specially at Google. It's not a filter issue and I don't know how to report in the community. More likely is something to do with Firefox itself.

Currently I have uBlockOrigin 1.22.4 and Firefox ESR 68.1.0

I create a specific entrys in uBlock by using the element picker for google.com but sometimes I am able to see the actual element before to be blocked by uBlock after the rule created in the extension. This is random issue.

When I check the logger, this element are marked like "dom".

It's there any way in which we force the blocking in Firefox?

**Comment by gorhill** [comment]
Closing as invalid, you removed the template asking you to provide steps-to-reproduce. I will re-open if you fill the template properly as asked so that the issue you report can be reproduced by volunteers here without having to speculate any part of the repro steps.
