### ISSUE TITLE
Dev build 1.22.5rc1 "REJECTED" from Chrome Web Store

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#745]
Here is the email I received today at 8h33:

> Dear Developer, We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users. Your Google Chrome item, "uBlock Origin development build", with ID: cgbcahbpdhpcegmbfconppldiemgcoii did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy: An extension should have a single purpose that is clear to users. Do not create an extension that requires users to accept bundles of unrelated functionality, such as an email notifier and a news headline aggregator. If two pieces of functionality are clearly separate, they should be put into two different extensions, and users should have the ability to install and uninstall them separately. For example, an extension that provides a broad array of functionalities on the New Tab Page/ Start-up Page but also changes the default search are better delivered as separate extensions, so that users can select the services they want. For more information on the new Chrome extensions quality policy, please refer to the FAQ: https://developer.chrome.com/extensions/single_purpose If you’d like to re-submit it, please modify the item so that it complies with the policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal. *Please keep in mind that after you resubmit your item, it will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published only if the item passes that review. *Important Note Repeated or egregious violations of the policies may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to the Chrome Web store program policies and terms of service. Thank you for your cooperation, Chrome Web Store Team --------------------------- Developer Terms of Service: https://developers.google.com/chrome/web-store/terms Program Policies: https://developers.google.com/chrome/web-store/program_policies Branding Guidelines: https://developers.google.com/chrome/web-store/branding 

Screenshots:

![b](https://user-images.githubusercontent.com/585534/66320911-b13d7980-e8ed-11e9-8067-b7d3a2083cec.png)

![a](https://user-images.githubusercontent.com/585534/66320898-ad115c00-e8ed-11e9-884b-f25cd827b4f7.png)

[Dev build 1.22.5rc0 is still available](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) -- here is the [difference between rc0 and rc1](https://github.com/gorhill/uBlock/compare/806364f2dad2...0733f6c4769b).

**Comment by gorhill** [comment]
I won't re-submit to try to have the dev build restored in the CWS, uBO does not "bundle unrelated functionality" as implied in the email, thus closing as wontfix.

**Comment by uBlock-user** [comment]
Sounds like a false positive on their part. So dev builds users are stuck on rc0 build now ?

**Comment by gorhill** [comment]
> Sounds like a false positive on their part

No point speculating one way or another, my experience with the CWS in the past is that we will never know why it was labelled "REJECTED", they never disclose the exact "why".

**Comment by uBlock-user** [comment]
But in the past, re-sbummint worked, didn't it ?

**Comment by gorhill** [comment]
Also, keep in mind that the next stable release is essentially what 1.22.5rc1+ is.

**Comment by gorhill** [comment]
> But in the past, re-submitting worked, didn't it ?

Your point? I should spam re-submissions with no changes until I am banned from the CWS? Let's leave it at this: wontfix, and I do not want a thread filled with speculations, this accomplishes absolutely nothing productive in the end.

**Comment by uBlock-user** [comment]
My point: try once again, or look into https://github.com/jspenguin2017/uBlockProtector/issues/312 as this suggested to you before.  

If none of those work then give up. 

> until I am banned from the CWS?

Trying it once more is not going to cost you anything. Anyways, your choice in the end.

**Comment by gorhill** [comment]
> look into <https://github.com/jspenguin2017/uBlockProtector/issues/312> as this was suggested to you before too

This post is more than two years old. Submissions of uBO dev build to the CWS is already and has been [automated for long while now](https://github.com/gorhill/uBlock/commits/master/dist/chromium/publish-beta.py).

**Comment by gorhill** [comment]
Just for the sake of having tried, I submitted 1.22.5rc2, and I received the same exact answer as above.

I also sent the following reply:

> There is no "bundles of unrelated functionality" in uBlock Origin.
> 
> Could you please be more specific about which part of uBlock Origin you
consider to be a "bundle"?

This was the answer:

> Subject  Re: Chrome Web Store: Removal notification for uBlock Origin development build
> 
> Dear Developer,
> 
> Your Google Chrome item, " uBlock Origin development build ", with ID: cgbcahbpdhpcegmbfconppldiemgcoii did not comply with our policies and was removed from the Google Chrome Web Store.
> 
> Your item did not comply with the following section of our policy:
> 
> An extension should have a single purpose that is clear to users. Do not create an extension that requires users to accept bundles of unrelated functionality, such as an email notifier and a news headline aggregator. If two pieces of functionality are clearly separate, they should be put into two different extensions, and users should have the ability to install and uninstall them separately.
> 
> For example, an extension that provides a broad array of functionalities on the New Tab Page/ Start-up Page but also changes the default search are better delivered as separate extensions, so that users can select the services they want.
> 
> For more information on the new Chrome extensions quality policy, please refer to the FAQ:
> 
> https://developer.chrome.com/extensions/single_purpose
> 
> ---------------------------
> 
> Developer Terms of Service:
> 
> https://developers.google.com/chrome/web-store/terms
> 
> Program Policies:
> 
> https://developers.google.com/chrome/web-store/program_policies
> 
> Branding Guidelines:
> 
> https://developers.google.com/chrome/web-store/branding

In other words, stonewalling.

Since the next uBO release will essentially be what 1.22.5rc2 is, consider that uBO is probably coming to an end of life in the Chrome Web Store -- there is no good reason to believe uBO 1.22.5rc2 would no longer be rejected with only changing the version number to 1.23.0.

Those who still want to use uBO will have to find another browser for which uBO will still be available.

**Comment by uBlock-user** [comment]
Given this stance of theirs, would you try to update/upload the stable version to the store or not ?

**Comment by gorhill** [comment]
I will upload stable to the Chrome Web Store, but given 1.22.5rc2 is rejected, logic dictates that 1.23.0 will be rejected. Actually, logic dictates that 1.22.5rc0 should also be rejected and yet [it's still available in the Chrome Web Store](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii). But as you can see, logic is not at work here, it's arbitrariness conveniently hiding behind _vague_, _unspecific_ accusations of "policy violations".

**Comment by uBlock-user** [comment]
They're going with their same "bundled" BS rethoric, I have sent some feedback and some strong words on their web-store page, I doubt that would do anything to change the situation, though this is not how I was expecting to end :(

**Comment by mapx-** [comment]
I've reacted too on twitter and google web store.

**Comment by mapx-** [comment]
It would be nice if other chromium browsers allowed the installation of extensions from github repositories or at least only some specific (trusted) extensions

@BrendanEich @brave-browser

**Comment by mapx-** [comment]
https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/

> pkasting
> I sent an escalation mail to a team internally. Hopefully someone can look at this.

**Comment by gorhill** [comment]
Other cases supporting that there is no way to resolve this sort of issues by having an email exchange about the actual _specific_ reasons why a submission is rejected or an extension is outright removed:

- https://github.com/openstyles/stylus/issues/194
- https://github.com/dessant/search-by-image/issues/57

**Comment by uBlock-user** [comment]
Approved -- `https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3fwlto/`

New dev build version should reflect within 24 hours or by Monday.

**Comment by gorhill** [comment]
To clarify to those who think I should have been more persistent:

My own past experiences:
- [dev build was also previously suspended with no reasons ever given, can't find the issue for now]
- https://github.com/gorhill/uBlock/issues/880
- https://github.com/gorhill/uBlock/issues/50

So this was the fourth time in my case. This is why I marked and will mark as `wontfix` any more occurrences of such issue in the CWS: it's essentially disrespectful to reply with bot-like emails which contains no specifics, forcing developers to waste time and efforts trying to figure what could possibly fix a supposed issue which may or may _not_ exist; I just choose to no longer accept this as if this was normal.

**Comment by uBlock-user** [comment]
> can't find the issue for now

https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/11

Back in May 2018, they took it down for no reason.

**Comment by gorhill** [comment]
Thanks, I couldn't remember where this was discussed. So for the record, cutting & pasting my comments from there:

***

gorhill on May 17, 2018

Sorry nothing I can do -- it's removed and unless I am being told by a human being *exactly* why, I can't fix this.

https://twitter.com/gorhill/status/997162260199075840

https://twitter.com/gorhill/status/997206089132400641

![a](https://user-images.githubusercontent.com/585534/40210200-97a63410-5a11-11e8-9073-b9974b8ee5fa.png)

***

gorhill on May 19, 2018

It's back. It ended up being re-published after I changed "uBlock Origin Dev Build" to "uBlock Origin Development Build".

**Comment by uBlock-user** [comment]
Since then, dev build has become "unlisted" in Store.

**Comment by gorhill** [comment]
> dev build has become "unlisted" in Store

I set it to be unlisted since when it got banned back in May 2018 -- I don't want people to install it by merely stumbling on it, I want people to install if they want when visiting the release notes.

**Comment by dotproto** [comment]
Apologies for the delay in getting back to you all on this rejection. [I said][0] I'd share an update shortly after the work week started but, regrettably, I lost track of this task. I was reminded on Oct. 22 when a Reddit user tagged me asking for an update. 

Following up on this, the development build was rejected for violating the single purpose policy because the "block element" feature isn't described in the extension's listing.  IMO this was an overly-strict interpretation of the single purpose policy and I'm talking to the review team about this specific issue. In the short term, I'd encourage developers to mention all of their extension's functionality in their web store listing.

But that brings us to what I believe is the core issue at hand: our current developer communications have … room for improvement. As @gorhill said in https://github.com/uBlockOrigin/uBlock-issues/issues/745#issuecomment-539061850,

> my experience with the CWS in the past is that we will never know why it was labelled "REJECTED", they never disclose the exact "why". 

I get where he's coming from. The rejection emails developers receive are very high-level, describing only the policy that was violated rather than the observed violation. As I understand it, this format was adopted in order to avoid providing malicious actors with information that would help them game the review process. But this also has the effect of not providing developers with enough guidance to address the violation or to clarify a misunderstanding with the reviewer.

As I [mentioned][1] [on][2] [Reddit][3], we're working to strike a better balance in our communications and improve the developer experience. While we started this effort before this rejection took place, we're still pretty early in the process. Look forward to more on this front in the coming months.

Apologies again for the delay in getting back to you with this. 

Simeon - @dotproto
Extensions Developer Advocate

[0]: https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3fwlto/
[1]: https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3h66fl/
[2]: https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3gkjlx/
[3]: https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3g3jlq/

**Comment by uBlock-user** [comment]
>  the development build was rejected for violating the single purpose policy because the "block element" feature isn't described in the extension's listing.

and yet only the dev build was targeted, and it happened specifically after all this time, the description hasn't been present since the beggining, that's puzzling

**Comment by mikhaelkh** [comment]
> the development build was rejected for violating the single purpose policy because the "block element" feature isn't described in the extension's listing

What is meant by "extension's listing"? If that is the "Overview" in CWS then it has this paragraph:
> uBlock Origin is NOT an "ad blocker": it is a wide-spectrum blocker -- which happens to be able to function as a mere "ad blocker". The default behavior of uBlock Origin when newly installed is to block ads, trackers and malware sites -- through EasyList, EasyPrivacy, Peter Lowe’s ad/tracking/malware servers, various lists of malware sites, and uBlock Origin's own filter lists.

**Comment by dessant** [comment]
> As I understand it, this format was adopted in order to avoid providing malicious actors with information that would help them game the review process.

"We won't disclose which specific action you took that resulted in you breaking the law, because you may be able to find a legal loophole next time. Here is your sentence, our decision is final, and we will not provide you any new information."

@dotproto, that's very odd reasoning, and it obviously results in a system that operates without oversight and which makes due process impossible. This position makes the assumption that your reviewers are infallible and fair, which they are not.

Consider my experience with CWS reviewers: https://github.com/dessant/search-by-image/issues/57

It starts with the extension getting a 7 day deadline to change something in the description, and it ends with the extension being taken down for nonsense policy violations 3 days before the deadline. Those policy violations were apparently retracted after I've made things public, and the extension was reinstated.

During these exchanges I honestly felt bullied by reviewers.

@dotproto, my experience is a common one among developers. What changes do you plan to introduce which will ensure that developers receive due process on the Chrome Web Store during reviews?

**Comment by dotproto** [comment]
I'm happy to answer questions to the best of my ability but I also don't want to hijack this without the project's permission. @gorhill & contributors, do you mind having this discussion here or would you prefer if we moved it elsewhere? The [chromium-extensions](https://groups.google.com/a/chromium.org/forum/#!forum/chromium-extensions) list the questions folks have asked so far would be relevant to the broader development community.

**Comment by dessant** [comment]
@dotproto, it would be constructive if your team would compile a list of complaints and pin it to the top of the mailing list. That would signal that the damage the current system is causing is acknowledged and well understood.

You must understand that unless there is an official acknowledgement of these issues, your recent interactions here and on Reddit look just like damage control. This is not an acute issue, so it's best to show that your team truly understands the gravity of this problem.

**Comment by gorhill** [comment]
> Following up on this, the development build was rejected for violating the single purpose policy because the "block element" feature isn't described in the extension's listing.

Other more popular content blockers such as AdBlock and Adblock Plus -- which have existed in the Chrome Web Store before uBO was first published -- also have this feature. This is a key feature for any top tier blocker, so I fail to make sense why uBlock Origin Development Build would be singled out for this.

**Comment by uBlock-user** [comment]
@dotproto uBO dev build is stuck again in Pending Review on CWS and the last update was 1.22.5.106 on Oct 17th fyi

**Comment by mikhaelkh** [comment]
@uBlock-user, [the preferable way to reach him is Twitter](https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3g3jlq/).

**Comment by mikhaelkh** [comment]
@uBlock-user, [the preferable way to reach out to him is Twitter](https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/f3g3jlq/).

**Comment by uBlock-user** [comment]
@mikhaelkh I don't use Twitter.

**Comment by mikhaelkh** [comment]
Still 1.23.1b0 in CWS. No one tweeted or otherwise reached @dotproto like he suggested?
Should a new, more general issue be opened or this issue will be renamed and reopened indicating not one specific version was affected?

**Comment by dessant** [comment]
The latest version of [Search By Image](https://github.com/dessant/search-by-image) has been repeatedly rejected from the Chrome Web Store. I'm releasing reviewer messages again to bring awareness about how disfunctional and unjust Google's review process is.

https://github.com/dessant/search-by-image/issues/63

**Comment by GKid94** [comment]
So there won't be any more uBlock Origin updates on the Chrome Store
