### ISSUE TITLE
Please warn that Safari won't work anymore.

### ISSUE THREAD

**Issue by dsharhon** [uBlockOrigin/uBlock-issues#747]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin won't work on Safari anymore (macOS Catalina was released today.) It would be nice to have a little warning in the README so that people don't accidentally install uBlock! ;)

<https://github.com/gorhill/uBlock/commit/1f0d2ecb8e34cb503b5caaea2a2a6dd38e8d8530>

<img width="532" alt="Screen Shot 2019-10-07 at 2 35 20 PM" src="https://user-images.githubusercontent.com/8261196/66350262-b7445200-e90f-11e9-81fc-08d442463997.png">

### A specific URL where the issue occurs

NA

### Steps to Reproduce

NA

### Expected behavior:

NA

### Actual behavior:

NA

### Your environment

* uBlock Origin version: Any
* Browser Name and version: Safari 13+
* Operating System and version: macOS 10.13.6+

**Comment by uBlock-user** [comment]
Beggining with Safari 13, extensions support itself is removed --  `https://adguard.com/en/blog/adguard-safari-1-5.html`

**Comment by dsharhon** [comment]
I know - I'm just suggesting to add a warning to that effect in the README.

**Comment by dsharhon** [comment]
Pull request (just copy-pasted gorhill and el1t's own words): <https://github.com/gorhill/uBlock/commit/1f0d2ecb8e34cb503b5caaea2a2a6dd38e8d8530>

**Comment by gorhill** [comment]
I don't think the first sentence is necessary, I [wrote this](https://github.com/gorhill/uBlock/tree/master/platform/safari) just to explain why I was removing the platform entry for Safari from the repo here -- the removed code dates from before @el1t's uBO. So the following should be enough:

> It will not possible for uBlock Origin to work with the upcoming Safari 13 / macOS Catalina release. See <https://github.com/el1t/uBlock-Safari/issues/158>.

**Comment by gorhill** [comment]
I lifted restrictions for pull request, you can make one if you want.

**Comment by dsharhon** [comment]
Cool, and thanks for all your work on this extension!

**Comment by MysticalOS** [comment]
So eh, Safari 14 is getting WebExtension API support. Does this change things for uBlock Origin?

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1123
