### ISSUE TITLE
Openning a saved html file by Save Page WE, causes ublock crashing

### ISSUE THREAD

**Issue by 1zizi1** [uBlockOrigin/uBlock-issues#748]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Openning a saved html file by Save Page WE with a long name created an empty folder with the same name in `profiles/~/storage/default`, caused ublock Filter list to not load, and when I deletd the folder the settings are reset. 
The name of empty folder was something like this (o replaced with some other charecters):
file++++C++Users+oooooooo+oooooooo+ooooo%20ooooooo+ooooooooooo+ooo%20oooo+MRAM%20vs%20SRAM%20vs%20DRAM-Difference%20between%20MRAM,SRAM%20and%20DRAM.html
 

### A specific URL where the issue occurs
https://www.rfwireless-world.com/Terminology/MRAM-vs-SRAM-vs-DRAM.html

### Steps to Reproduce

1. Go to https://www.rfwireless-world.com/Terminology/MRAM-vs-SRAM-vs-DRAM.html
2. Save webpage using Save Page WE
3. Open the saved webpage
4. The empty folder is created in profiles/~/storage/default
5. This folder make Firefox nonfunctional, crashing Ublock, etc
6. Removing the folder fixes the issue!

### Your environment

* uBlock Origin version:  v1.22.4
* Browser Name and version: Firefox Nightly 71.0a1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
uBO is HTML/JAVASCRIPT/CSS. Browser/extension crashes should be reported to the respective browser vendors.

**Comment by gorhill** [comment]
> This folder make Firefox nonfunctional

uBO didn't create this folder. Why report here?

**Comment by 1zizi1** [comment]
Disabling Ublock fixes the issue too! I searched among many extensions and folders to find that the problem is caused by Ublock crashing

**Comment by gorhill** [comment]
You said:

> This folder make Firefox nonfunctional, crashing Ublock, etc

What does "Firefox nonfunctional" and "etc" mean exactly?

**Comment by gwarser** [comment]
Probably related to https://bugzilla.mozilla.org/show_bug.cgi?id=1423917 

(I cannot reproduce)

**Comment by 1zizi1** [comment]
> You said:
> 
> > This folder make Firefox nonfunctional, crashing Ublock, etc
> 
> What does "Firefox nonfunctional" and "etc" mean exactly?

The crashing of Ublock causes Firefox not to be able to connect to the internet.

> Probably related to https://bugzilla.mozilla.org/show_bug.cgi?id=1423917 (I think this is the bug where they decide to record more telemetry about unknown files in storage folder https://bugzilla.mozilla.org/show_bug.cgi?id=1529016 )
> 
> (I cannot reproduce)
> 
> Depending of how many "ooooo" OP skipped, this may be 250 chars in path (path component?) limit (unbelievable).

The number of characters of the name I gave is the same as the real thing, I just used `o` instead of my folder names.

**Comment by gwarser** [comment]
I think this is the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1536796 "Getting NS_ERROR_FILE_NOT_FOUND error while the file path exceeds the path limit on Windows"

**Comment by gorhill** [comment]
For sure it's related to the issue raised here, last comment:

> The issue appeared again in my profile, I deleted the directory "/storage/default/file++++E++T%C3%A9l%C3%A9chargements+El%20intercooler_%20qu%C3%A9%20es%20y%20c%C3%B3mo%20funciona%20(2019-06-28%201_38_09%20AM).html" and it fixed it immediately.

For the sake of understanding the Firefox issue I would have to read more in details because I am not understanding why there is a `file:///...` created into `.../storage/default/`.

Anyways as said, a Firefox issue but no need to open a new issue for it since it's already filed.

**Comment by gwarser** [comment]
All folders in `/storage/default` are "origins", for local file "origin" seems to be full file path. Storing something in `localStorage` or `IDB` will create these folders...

@1zizi1 you can ask for progress on this bug and present your case. You can login to Bugzilla using GitHub account.

**Comment by gwarser** [comment]
@1zizi1 can you reproduce by saving this page by browser as "Web Page, complete"? Or is this only reproducible with "Save Page WE" extension?

**Comment by 1zizi1** [comment]
I don't have that situation anymore. But I can try to reproduce it

> @1zizi1 can you reproduce by saving this page by browser as "Web Page, complete"? Or is this only reproducible with "Save Page WE" extension?

**Comment by gwarser** [comment]
@1zizi1 no need. This was confirmed in few scenarios in https://bugzilla.mozilla.org/show_bug.cgi?id=1536796
