### ISSUE TITLE
Default filter list for RU locale

### ISSUE THREAD

**Issue by ameshkov** [uBlockOrigin/uBlock-issues#749]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, uBlock Origin enables two different filter lists for users with "RU" locale: `AdGuard Russian filter` and `RU AdList`.

The problem is that these are two independent and not really compatible filter lists. Having both of them enabled leads to random issues. For instance, it often happens on websites that do heavy circumvention, and the reason is different incompatible approaches to handle such issues.

**Proposed solution:** there should be just one **default** "RU" filter list in uBlock Origin. IMO, it should be RU AdList, @dimisa-RUAdList does a great job of making it compatible with uBlock Origin.

I was asked to report this issue by the maintainers of these filter lists (@dimisa-RUAdList and @Alex-302), and they both agree on the proposed solution.

### Your environment

* uBlock Origin version: v1.22.4
* Browser Name and version: any
* Operating System and version: any

**Comment by dimisa-RUAdList** [comment]
I would also add a warning about possible conflicts, for those cases when users activate these two filters manually.

**Comment by gorhill** [comment]
> Proposed solution: there should be just one default "RU" filter list in uBlock Origin. IMO, it should be RU AdList, @dimisa-RUAdList does a great job of making it compatible with uBlock Origin.

Ok, but then I guess this means I will remove AdGuard Russian from the stock filter lists since enabling it is likely to cause issue -- there is no infrastructure in uBO to warn users that a specific filter list is incompatible with a currently selected one. (AdGuard was added at a time when RU AdList wasn't using uBO-specific syntax).

**Comment by gorhill** [comment]
@dimisa-RUAdList 
Is RU AdList still hosted only at `https://easylist-downloads.adblockplus.org/advblock+cssfixes.txt` or is there a more independent server from where it can be downloaded? If the list contains uBO-specific filters, this means ABP could decide to no longer host it at any time.

**Comment by dimisa-RUAdList** [comment]
@gorhill 
I do not think that this will ever happen. RU AdList Fixes is officially recommended by ABP/AB for those cases when the capabilities of these extensions are not enough. The current state of affairs is extremely beneficial for ABP/AB. As the functionality of these extensions expands, they get relevant solutions that have been created over the years. Actually, this is already happening, for example with rules like abp-has and abort- *. And the use of RU AdList Fixes in uBlock Origin allows you to maintain relevance in the best way.

**Comment by okiehsch** [comment]
Well, your list does circumvent anti-adblock warnings, which they consider a no-no.
`https://adblockplus.org/filter-lists-requirements`
"Must block only ads
...... it **must not work around anti-ad block warnings** and messages or technological measures that effectively control access to websites"

**Comment by lainverse** [comment]
@gorhill 
Technicaly we can make a mirror right here on github, but I don't know would github keep serving it in case of hundreds of thousands requests a day. Do you host any subscriptions here or use some different server?

**Comment by gorhill** [comment]
Filters are served from here, I have no idea whether this is close to be considered an issue by GitHub. I think I need to prepare something in case it does become an issue. I am fine to keep downloading RUAdList from `easylist-downloads.adblockplus.org` if it's RUAdList's home server.

**Comment by gwarser** [comment]
Updated after Shift-Purge.
