### ISSUE TITLE
/metrics/metrics$domain=~spatineo.com firing on other domains

### ISSUE THREAD

**Issue by pmeisel123** [uBlockOrigin/uBlock-issues#752]
### Prerequisites

- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - [X ] I also searched the existing issues at <https://github.com/gorhill/uMatrix/issues>
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uMatrix](https://old.reddit.com/r/uMatrix/)
- I tried to reproduce the issue when...
    - [X ] uMatrix is the only extension
    - [X ] uMatrix with default lists/settings
    - [ X] using a new, unmodified browser profile
- [ X] I am running the latest version of uMatrix
- [ X] I checked the [documentation](https://github.com/gorhill/uMatrix/wiki) to understand that the issue I report is not a normal behavior
- [ X ] I used the logger to rule out that the issue is caused by my ruleset

### Description
Our js lib is being blocked, by a misfiring rule.   
https://admin1.sitespect.com/Common/metrics/metrics.js?9.6.4.93878
is being blocked by
/metrics/metrics$domain=~spatineo.com
It appears that the domain part of the rule is being ignored.
We are going to rename the file/path so this isn't an issue on our end.  However I am still reporting this bug, because that is how we all get a better product

### A specific URL where the issue occurs
This isn't going to help since you need a log in to hit the site
https://admin1.sitespect.com/Responsepoint_One?Site_ID=336

### Steps to Reproduce

Create a js file with the path of /Common/metrics/metrics.js
Insert into into a page.

### Ruleset

/metrics/metrics$domain=~spatineo.com

### Supporting evidence

![screen](https://user-images.githubusercontent.com/34077916/66656704-819fb180-ec0c-11e9-8da3-3181e2abcba7.png)

### Your environment

* uMatrix version: 1.22.4
* Browser Name and version: Chrome 77.0.3865.90
* Operating System and version: Windows 7 Professional

**Comment by uBlock-user** [comment]
Report to EasyPrivacy, the filter is present in that list.

**Comment by pmeisel123** [comment]
Does the $domain part of the filter mean anything?   It appears to be ignored

**Comment by gorhill** [comment]
`~domain` means the filter will apply everywhere except on `domain`.

**Comment by pmeisel123** [comment]
I'm a perl programmer so =~ made me assume that it was a matching regex
