### ISSUE TITLE
Thunderbird 68.1.2 regression in uBlock 1.22.5.102

### ISSUE THREAD

**Issue by alta88** [uBlockOrigin/uBlock-issues#753]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using Thunderbird 68.1.2 (release) and uBlock 1.22.1.1 things work to the partial degree expected.

Installing uBlock 1.22.5.102 results in

13:06:54.812 TypeError: chrome.contextMenus is undefined
webext.js:74:9
    webext moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/webext.js:74
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/webext.js:167
13:06:54.821
ReferenceError: can't access lexical declaration `webext' before initialization vapi-background.js:93:1
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/vapi-background.js:93
13:06:54.821
TypeError: class heritage vAPI.Net is not an object or null vapi-webrequest.js:59:16
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/vapi-webrequest.js:59
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/vapi-webrequest.js:135
13:06:54.823
TypeError: vAPI.storage is undefined
background.js:171:9
    Block moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/background.js:171
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/background.js:200
13:06:54.824
ReferenceError: can't access lexical declaration `µBlock' before initialization traffic.js:28:1
    <anonymous> moz-extension://0d376baf-0a17-4657-8b37-623e82ad3013/js/traffic.js:28
13:06:54.825

**Comment by uBlock-user** [comment]
Try installing the latest update from the dev builds.

**Comment by alta88** [comment]
Yes, that version works, thank you.

I wonder, are there any specific things that you know are missing in the Tb web extension implementation that prevent full uBlock functionality?

I know of these:
https://bugzilla.mozilla.org/show_bug.cgi?id=1504475
https://bugzilla.mozilla.org/show_bug.cgi?id=1574545
And of course tabs in Tb are quite different though the web api is intended to follow firefox.

Sorry for the OT.
