### ISSUE TITLE
Your best extension

### ISSUE THREAD

**Issue by Phil995511** [uBlockOrigin/uBlock-issues#754]
Hello, I read the article below which shocked me a lot : 

https://www.developpez.net/forums/d2012535/logiciels/autres-logiciels/internet/google-chrome/google-chrome-vers-fin-l-extension-blocage-publicites-ublock-origin/#post11175178

This may be the beginning of the end of Google's monopoly on internet browsers. IE, Netscape, Firefox, had their hour of glory too before being "neglected" from the public.

Ublock origin is the only extension I use and since I find it absolutely essential, if Google continues to persecute his developer, I will drop their browser!

Regarding the free version of Chrome ie Chromium, it would be fear-be desirable to create an alternative shop to that of Google in view of their incorrect behavior of them to us.

Excellent weekend end to all of you.

Best regards.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/745#issuecomment-541356836

> Latest build is now available in CWS
