### ISSUE TITLE
uBO extension icon appears grey and power button appears in white when clicked on startup on Firefox/Nightly 

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#757]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO extension icon and power fade to grey on startup on Nightly. 

### Steps to Reproduce

Under _General section_ of `about:preferences`, make sure _Restore previous session_ is not activated, under _Home section_, `Homepage and new windows` is set to `Firefox Home(Default)`, `New tabs` is set to Firefox Home(Default)

1) Start Firefox and new tab page will appear.

2) Click on uBO extension icon and watch as it fades to grey and the blue power switch going white.

3) Refreshing the new tab page turns them both back to normal.

https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/123

### Expected behavior:

The uBO icon shouldn't appear grey when clicked on start.

### Actual behavior:

The uBO icon appears grey when clicked on start.

### Your environment

* uBlock Origin version: 1.22.5rc4
* Browser Name and version: Firefox 71
* Operating System and version: Win 10

**Comment by u-RraaLL** [comment]
Tested on Linux FF 93, uBO 1.38.7b4, 1.38.7b3, 1.38.6 and 1.37.2 (both stables on separate profiles).

The icon does load red on launch and fades into grey on click only (or after switching tabs <- it opens grey in a new tab and switching back forces the fade on the first one), but I wasn't able to repro the blue>white switch of the power button there.

Then I tried on Win7 WM FF93 uBO 1.38.4 - I was able to reproduce it (icon and power button)  **only** on the first browser launch right after WM's launch while FF was slow to load (the Homepage Shortcuts haven't fully loaded yet). The power button didn't show up blue again on browser relaunches, even after logging off or restarting. Not even after shutting off the WM and relaunching it again after a few mins.
I did, however, see the popup load in its default size (I have it expanded to the max) a few times, some of which still had the "more" button visible, some of them not (just lacking the domain expansion on the left). And two or three times I actually saw the "all" line load on the bottom of the popup. Of course, this all only happens on the (slow) WM, when the popup is opened too quickly after browser's launch. On subsequent icon clicks, the popup always renders properly. Related to #1759 ?


> PS -- Remove all entries from _**Trusted sites**_ pane and Apply changes if you can't repro or can't differentiate.

Tried that too on all browsers, including latest FF Dev and Nightly on the WM with uBO 1.38.7b4 on both,, and still couldn't repro the blue power button fading (other than the single time mentioned above).

**Comment by u-RraaLL** [comment]
> Click on the grey extension icon and then you will see, like this --

Oh, I see. I thought the issue was about a visible change from blue to grey.

You're right, on 1.38.7b4 FF's new tab isn't detected in uBO's popup (no domain/page and the button stays white/icon grey) until a page refresh.

On pre-1.38.7b4 this only happens on FF's Homepage. Fixed by a refresh or a tab switch.
