### ISSUE TITLE
Whale browser support

### ISSUE THREAD

**Issue by alexkoala** [uBlockOrigin/uBlock-issues#758]
Have a plan to support [Whale browser](https://whale.naver.com/en/)?
 * [Whale English forum](https://forum.whale.naver.com/forum/25/)
 * [Whale Store](https://store.whale.naver.com/extensions/new)
 * [Whale Developers (Korean)](https://developers.whale.naver.com/)

**Comment by uBlock-user** [comment]
Uses Blink, so a fork of Chromium

**Comment by alexkoala** [comment]
> ^^ You already uploaded uBO on Whale Store
Will delete after official release by gorhill.

**Comment by gorhill** [comment]
I can't take on more duties publishing in different stores. What would work is that sombody from the Whale browser store ask me permission to download from the Chrome store and publish as is the copy of uBO from the Chrome store.

**Comment by alexkoala** [comment]
> What would work is that sombody from the Whale browser store ask me permission to download from the Chrome store and publish as is the copy of uBO from the Chrome store.

May I ask you a permission about publish uBO on Whale Store?

**Comment by krystian3w** [comment]
I suppose this no support send CRX with bot API + script.

**Comment by krystian3w** [comment]
I suppose this no support send CRX with "bot" API + bash script in CI machine e.g.:

 `circleCI` with `wext/shipit`

so need manually login into addon developer panel:

 `https://store.whale.naver.com/developers/dashboard`.

---

Manual upload may cause you to forget about this store of add-ons.
