### ISSUE TITLE
Inline

### ISSUE THREAD

**Issue by airbee7337** [uBlockOrigin/uBlock-issues#765]
### Description

[Description of the bug or feature]
Is it possible when inline scripts & 1st-party-scripts are disabled everywhere, to fully interoperate some code so all crapware scripts slowing down the browser erm, TO disable sockets.

Full Feature Request: Sockets/Websockets Disable 

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
ecosia.org
duckduckgo.com
crazy.com

### Steps to Reproduce

1. Set 1st-party scripts & inline scripts to be disabled everywhere
2. Go the usual poware websites 
3. open the networking feature and check the sockets out (not websockets) 

### Expected behavior:

[What you expected to happen]
It would be nice when applying the option of disabling 1st-party scripts and inline scripts, to fully disable any script activity on that website. As these can be done for power-users who always have this option on to save bandwidth and to 

This feature is not technically broken, in my unprofessional opinion it could be improved? 
### Actual behavior:

[What actually happened]
Even with the JS option as OFF, (inline & 1st-party scripts), there are still SOCKETS being connected to cdn & cache random servers or the IP of that site. 
### Your environment

uBlock Origin v1.23.0
* Browser Name and version: FF 70
* Operating System and version: WInny 10

**Comment by uBlock-user** [comment]
> there are still SOCKETS being connected to cdn & cache random servers or the IP of that site.

What do this mean ? Expand on this.

**Comment by gorhill** [comment]
I fail to understand what is reported.

> It would be nice when applying the option of disabling 1st-party scripts and inline scripts, to fully disable any script activity on that website

You are still allowing in 3rd-party scripts. Just use the master javaScript switch if you want to completely disable JavaScript?

> Go the usual poware websites

What is "usual poware websites"?

**Comment by uBlock-user** [comment]
He wants to close lingering socket connections in `about:networking#sockets` by lingering I mean the ones that stay even after the tab is closed.

**Comment by gorhill** [comment]
He didn't say anything about `about:networking#sockets` -- we shouldn't speculate, reporters need to be explicit otherwise we are just guessing on their behalf.

**Comment by uBlock-user** [comment]
> open the networking feature and check the sockets out (not websockets)

That's where he implied though. That's the only place where "networking" is available in Firefox and makes sense, so I speciulated.

**Comment by gorhill** [comment]
If it's really `about:networking#sockets`, then I still can't make sense of the report. Disabling JavaScript does not disable connecting to a remote web site -- there is the main document to fetch and all secondary non-script resources. I can't make sense of the report here.
