### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by kfur** [uBlockOrigin/uBlock-issues#769]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open [https://iky1e.tumblr.com/post/9561218739/jailbroken-development-starter-pack](https://iky1e.tumblr.com/post/9561218739/jailbroken-development-starter-pack)

### Expected behavior:

Low cpu usage 

### Actual behavior:

99 % cpu usage

[What actually happened]

### Your environment

* uBlock Origin version: 1.23
* Browser Name and version: Chromium 76
* Operating System and version: macOS 10.14.6

**Comment by gorhill** [comment]
Unable to reproduce.

You barely provide any details. How did you measure CPU usage? Where is the profiling data showing that uBO specifically is responsible for the high CPU usage?

**Comment by kfur** [comment]
My bad it's filter issue
Sorry

**Comment by uBlock-user** [comment]
> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from Firefox Profiler/Chromium Profiler + analysis supporting the claim.
