### ISSUE TITLE
High-light domains containing cdn in domain list

### ISSUE THREAD

**Issue by gitressa** [uBlockOrigin/uBlock-issues#770]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Many web sites use a CDN, which is often needed to make the page render correctly. For example https://knowyourmeme.com/ which has a long list of third-party scripts:
- amazon-adsystem.com
- b2c.com
- chartbeat.com
- clarium.global.ssl.fastly.net
- complex.com
- connatix.com
- consensu.org
- facebook.net
- google-analytics.com
- google.com
- gstatic.com
- hotjar.com
- kym-cdn.com
- msecnd.net
- newrelic.com
- ntv.io
- pinterest.com
- quantserve.com
- scorecardresearch.com
- shopifycdn.com
- twitter.com
- videoplayerhub.com
- zergnet.com

From the list, it is only necessary to unblock kym-cdn.com to make the page work.

It would be a great feature if the domains in the list which contains the string `cdn` stand out, maybe by making them bold?

### A specific URL where the issue occurs
https://knowyourmeme.com/

### Steps to Reproduce
1. Go to https://knowyourmeme.com/
2. See that it doesn't look great
3. Unblock kym-cdn.com to make it look better

### Your environment
* uBlock Origin version: 1.23.0
* Browser Name and version: Firefox 70.0
* Operating System and version: Ubuntu 18.04

**Comment by uBlock-user** [comment]
>  unblock kym-cdn.com to make the page work.

It's not blocked in the first place by any filterlist, are you blocking it yourself ?

**Comment by uBlock-user** [comment]
FYI -- You have `* * 3p block` which makes the other two rules redundant.

**Comment by uBlock-user** [comment]
FYI -- You have `* * 3p block` which makes the other two rules redundant.

**Comment by gitressa** [comment]
swiftype.com is another example, where allowing their cdn domain swiftype**cdn**.com does the trick.

**Comment by gitressa** [comment]
Thanks for getting back about this. I should of course have mentioned it, but I have these under "My Rules" > "Permanent rules":
```
* * 3p block
* * 3p-frame block
* * 3p-script block
```
So in my list of domains above ("... which has a long list of third-party scripts") everything is blocked, except knowyourmeme.com.

But I really do want to block third-party scripts and choose myself which to allow ...

**Comment by gitressa** [comment]
Something odd is happening with Github ... My two previous comments are in reverse order. Also, I got an e-mail alert that someone posted this in https://github.com/uBlockOrigin/uBlock-issues/issues/770#issuecomment-549119732 ... A comment which is nowhere to be seen:
> FYI -- You have * * 3p block which makes the other two rules redundant.

**Comment by uBlock-user** [comment]
> FYI -- You have * * 3p block which makes the other two rules redundant.

I posted that, but for some reason, it doesn't appear. GitHub issue.

**Comment by gitressa** [comment]
Thanks, I think Github might have had some challenges at the time ...

But I use **hard mode**, and this is what the [excellent documentation](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) tells me to add:

> My rules pane:<ul>
> <li>Add <code>* * 3p block</code>
> </li>
> <li>Add <code>* * 3p-script block</code>
> </li>
> <li>Add <code>* * 3p-frame block</code>
> </li>
> </ul>

Or is the documentation wrong?

**Comment by gorhill** [comment]
> Or is the documentation wrong?

No, it's good. The point of also having `3p-script block` and `3p-frame` block is to easily downgrade to a lesser blocking mode -- which is even easier now with the "Relax blocking mode" shortcut.

**Comment by gitressa** [comment]
Thanks for explaining the thoughts behind, but also for working on uBlock Origin.

"Relax blocking mode" is an interesting concept. Is it documented how it works yet? From what I can tell, the first time the shortcut is pressed, it disables
`* * 3p block`

Second time shortcut is pressed disables
```
* * 3p-script block
* * 3p-frame block
```
Site likes adform.net ares still blocked, probably because they are on a Filter list, whereas consensu.org is now unblocked (third-party script, not on a Filter list).

Anyway, we are getting side tracked, this issue is about cdn's. Thinking about it, would a shortcut which enables domains with cdn in them make sense?

**Comment by gorhill** [comment]
> Thinking about it, would a shortcut which enables domains with cdn in them make sense?

I've had thoughts about implementing a heuristic to guess-noop some domains before downgrading to 3p-script/3p-frame -- your issue here relate to this.

Such heuristic extends beyond `cdn` occurrences however. For instance uBO should also report that `arstechnica.net` is likely related to `arstechnica.com`. Another idea which I saw in a script blocker a long long time ago (mentioned somewhere on Wilders Security when I was working on HTTP Switchboard) is a sort of [Levenstein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to guess related 3rd-party domains. Another variable that I have noticed is often correlated is the number of network requests, often 3rd-party domains used as CDN have a high count of blocked requests (images, css, scripts, etc).

So mainly the way I read your issue is not to literally deal with `cdn` in a specific way, but more generically to come up with a heuristic to single out 3rd-party domains which are seen as highly likely to be needed on the current site. The heuristic could be used to visually filter out unrelated domains so that it becomes easier for the user to focus and assess what is left, or to actively noop what is being assessed as being needed.

**Comment by gitressa** [comment]
I understand, trying to guess relevant domains can get complicated very fast.

> So mainly the way I read your issue is not to literally deal with cdn in a specific way, but more generically to come up with a heuristic to single out 3rd-party domains which are seen as highly likely to be needed on the current site. The heuristic could be used to visually filter out unrelated domains so that it becomes easier for the user to focus and assess what is left, or to actively noop what is being assessed as being needed.

That's exactly what I ask for, since it is not unusual for a web site to have +25 third-party scripts yet only one unblocked `cdn` will make most elements render fine. How to single these domains out in a user friendly way is another question ... perhaps changing the background color to a slightly darker/lighter nuance might do it?

As a start it could be something as simple as check for the presence of a string like `cdn` in the domain.

Another thing, and I don't want to side track the issue, but is it possible to make the uBlock window taller, to be able to see all scripts without having to scroll?

**Comment by ahydronous** [comment]
@gorhill 
Perhaps upgrading the filter syntax so one can write `* *cdn* * noop` and introducing that as an example/standard rule in advanced mode? That would allow anything with cdn in the name to be loaded.

**Comment by Shoggomo** [comment]
Is this issue still being addressed?
I think @ahydronous's idea of using wildcards in filters would be very useful.
