### ISSUE TITLE
A problem with cyrillic characters

### ISSUE THREAD

**Issue by 17721** [uBlockOrigin/uBlock-issues#772]
I want to make a stop-word list for google searches and for some reason, the command doesn't work with **cyrillic characters**, but it does work OK with _english_. Any idea why?

    /www.google.com/search\?.*?q=.*?(?:_abcdef_|**абвгде**)/$document

**Comment by gorhill** [comment]
This does not work in ABP and AdGuard either. You need to use the encoded-to-ASCII version of non-ASCII characters, i.e. `/www.google.com/search\?.*?q=(?:abcdef|%D0%B0%D0%B1%D0%B2%D0%B3%D0%B4%D0%B5)/$document` in the current case (I also had to fix to regex).

**Comment by gwarser** [comment]
This filter should block google searches containing any of included words in any position, yes @17721 ? (<https://www.reddit.com/r/uBlockOrigin/comments/dq2vwh/how_to_make_a_stopword_list_for_google_search/>)


Markdown broke it, `...q=.*?(...` part should be kept. And should probably start with `/https://...` to be more efficient.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/68139557-9715ac00-ff2a-11e9-9c51-a2a808f7e751.png)

And after adding encoded word to the filter:

![image](https://user-images.githubusercontent.com/886325/68139742-f378cb80-ff2a-11e9-9cb7-39d9dba033cc.png)

**Comment by gwarser** [comment]
Ouch! This is unexpected:

![image](https://user-images.githubusercontent.com/886325/68140110-86196a80-ff2b-11e9-8e30-0969434160ae.png)

Log reports matching filter, but doc is not blocked.

uBO: 1.23.0
Chrome: 77.0.3865.120

**Comment by gwarser** [comment]
It works after removing `|абвгде` from the filter.

**Comment by gorhill** [comment]
Problem is `btoa`, it does not work with `абвгде`:

    btoa('абвгде');
    InvalidCharacterError: String contains an invalid character

[Documentation](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa):

> Since this function treats each character as a byte of binary data, regardless of the number of bytes which actually make up the character, an InvalidCharacterError exception is thrown if any character's code point is outside the range 0x00 to 0xFF

Easy to fix by switching to `encodeURIComponent` instead, but then using non-ASCII character in network filters elsewhere than in the hostname part is not going to work anyway, the browser internally only work with ASCII, this is what uBO sees only with the webRequest API.

**Comment by gorhill** [comment]
ABP/AdGuard are no different to uBO, try:

    @@/www.google.com/search\?.*?q=(?:abcdef|абвгде)/$document

The page won't be whitelisted when searching for `абвгде`, it will be whitelisted when searching for `abcdef`.

**Comment by gorhill** [comment]
I don't know about "fixed", OP's issue is still there. The fix could be to reject network filters with non-ASCII characters unless they are in the hostname part, but this will add yet another overhead to filter parsing. Filter list maintainers know to avoid such issue, so maybe it's should just be documented and no code change.

**Comment by gwarser** [comment]
I assumed filter issue.

I have found only these in uBO compatible filters from filterlists.com:

```
Shalla List Gamble Urls:1352.txt:
113:it.wikipedia.org/wiki/casinò_online
Shalla List Ringtones Urls:
1416.txt:41:digitones.fr/de/Ein-Colt-für-alle-Fälle-Klingeltöne.html
1416.txt:42:digitones.fr/de/kostenlos-nokia-3361-klingeltöne.html
Shalla List Sex Lingerie Urls:
1426.txt:5:alivianate.org/moda-femenina/lenceria-sexy-¡-atrevete/
1426.txt:23:dark-fashion-shop.de/bestellen:Reizwäsche
1426.txt:135:wikipedia.org/wiki/Reizwäsche
Shalla List Shopping Urls:
1428.txt:250:academon.co.il/category_page.asp?subj=131&name=×× ×ª
1428.txt:2958:dbook2.co.il/found_items.asp?mode=&category_id=131&name=×× ×ª
Cybercrime List:
1500.txt:1054:dsdfgdfshfgh.ru/p♠anel™sœ¸/admin.php
Spyware Filter Scrip:
1532.txt:3607:/dados.php?mensagem=&lt;b&gt;CARTÃO&lt;
Confirmed Phishing Domains:
496.txt:337:http://a2plcpnl0617.prod.iad2.secureserver.net/~n6spszjef0nq/cc/dados.php?mensagem=&lt;b&gt;CARTÃO&lt;/b&gt;:%20&lt;br&gt;&lt;b&gt;SENHA&lt;/b&gt;:%20&lt;br&gt;
```

**Comment by 17721** [comment]
I still don't get it... How do I block quires with cyrillic chars?

**Comment by gwarser** [comment]
Copy address from browser address bar - it should be properly encoded.

**Comment by Remu-rin** [comment]
@17721 Use something like this to encode `абвгде` into `%D0%B0%D0%B1%D0%B2%D0%B3%D0%B4%D0%B5`: https://meyerweb.com/eric/tools/dencoder/
