### ISSUE TITLE
Regression: tabs created by user are closed by popup filter

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#774]
<details>
<summary>Details</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

Original discussion here: https://www.reddit.com/r/uBlockOrigin/comments/dpnpk8/ublock_possible_automatically_closing_tabs_when/

New tab is closed by matching popup filter when opened by middle click or Ctrl + click.

uBO had protection to not close tabs when opened directly by user: https://github.com/gorhill/uBlock/commit/7713597e3e3ecf5c03c70f56bdb989e7d78956e8

This stopped working after https://github.com/gorhill/uBlock/commit/f204d24bf4a7a5f70419bd8b0c7a87595f0a4181

```
$ git bisect good && ./tools/make-chromium.sh
f204d24bf4a7a5f70419bd8b0c7a87595f0a4181 is the first bad commit
commit f204d24bf4a7a5f70419bd8b0c7a87595f0a4181
Author: Raymond Hill <rhill@raymondhill.net>
Date:   Mon Sep 23 08:25:23 2019 -0400

    Match static popup filter against local context...
```

### A specific URL where the issue occurs

https://www.reddit.com/r/uBlockOrigin/comments/dpnpk8/ublock_possible_automatically_closing_tabs_when/f695dan/

### Steps to Reproduce

1. add `||netdna-ssl.com^$popup,third-party` to My filters
2. middle click on http://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/opendesign/files/2019/06/FX_Design_Blog_Logos_Family.jpg

Original STR: https://www.reddit.com/r/uBlockOrigin/comments/dpnpk8/ublock_possible_automatically_closing_tabs_when/f695dan/

### Expected behavior:

New tab should open as requested by user.

### Actual behavior:

Tab is closed by filter.

### Your environment

* uBlock Origin version: bisection
* Browser Name and version: Nightly 72 20191104094118, Chrome Version 77.0.3865.120 (Official Build) (64-bit)
* Operating System and version: Manjaro

**Comment by gorhill** [comment]
I added a test, #14, to detect this kind of regression: <http://raymondhill.net/ublock/popup.html>.

**Comment by uBlock-user** [comment]
> 
    add ||netdna-ssl.com^$popup,third-party to My filters
    middle click on http://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/opendesign/files/2019/06/FX_Design_Blog_Logos_Family.jpg


Can't reproduce on my Nightly, it's a week old version.

**Comment by gwarser** [comment]
> Can't reproduce on my Nightly, it's a week old version.

uBO version? Tested on Firefox beta Version 71.0b6 Build ID 20191031113544

**Comment by uBlock-user** [comment]
> uBO version?

1.23.1b15

**Comment by gwarser** [comment]
Also with test 14 on http://raymondhill.net/ublock/popup.html ?

**Comment by uBlock-user** [comment]
> Also with test 14

Yes, with `||example.com^$popup,third-party`

logger never shows popup entry..

**Comment by gwarser** [comment]
Maybe somehow related with this `about:blank` entry?

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 | /adhandler.aspx?$popup | -- |  | 3,3 | popup | `http://example.com/AdHandler.aspx?` |
| +0 |  |  |  |  | popup | about:blank |

**Comment by uBlock-user** [comment]
It rather show example.com/adhandler.aspx, as new navigational entry in dark grey border.

It's okay, it's one of those times where something is working as expecting without a fix, it's rare but it's good and the fix is already implemented, not worth investing time in mozregression...

**Comment by garry-ut99** [comment]
The issue is back, on both Firefox and Chromium, can be reproduced on many sites, for example: `https://example.com/`: middle-clicking "More information" link gets always closed by `$popup` filter or `per site no-popups` swtich. The issue doesn't happen on all sites & links, but occurs on many sites & links. Also on some sites it happens that when middle-clicking on links multiple times, they are sometimes closed, and sometimes not (random).

(Unless I'm missing something, due to 5 years have passed, and the issue is not considered a bug anymore.)

**Comment by gorhill** [comment]
The link at `example.com` is `https://www.iana.org/domains/example`, the URL of the final page in the new tab is `https://www.iana.org/help/example-domains`, so there is a mismatch between the link and page URL in new tab, thus it will be considered a candidate for popup filtering.
