### ISSUE TITLE
Update Filter Lists More Often

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uBlock-issues#776]
Make uBlock Origin so that it updates filter lists more often, I have filter lists that haven't been updated for a day

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6526#issuecomment-551524711

**Comment by uBlock-user** [comment]
> I have filter lists that haven't been updated for a day

So force update it yourself, 24 hours is a normal delay.
