### ISSUE TITLE
Ads in hentai2read [NSFW Site]

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uBlock-issues#779]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I went to hentai2read.com to read a doujinshi and I'm seeing ads.

### A specific URL where the issue occurs

https://hentai2read.com/my_brothers_funeral/1/

### Steps to Reproduce

1. Visit the page
2. Enjoy the views

### Expected behavior:

Not to see ads.

### Actual behavior:

I'm seeing ads.

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Mozilla Firefox v70.0.1 x64
* Operating System and version: Windows 8.1 Professional x64

This is my current set of filters: https://i.imgur.com/9n9q0WA.png

I tried to Purge All Caches, update the filters and reload the page, but it didn't work.

![Ads1](https://user-images.githubusercontent.com/54429803/68532295-47ecc400-02fa-11ea-8df9-3eff4019d52b.png)
![Ads2](https://user-images.githubusercontent.com/54429803/68532296-47ecc400-02fa-11ea-96f1-eb2e41cddef3.png)

**Comment by uBlock-user** [comment]
> Do not post any filter list issues or issues where website's functionality is broken. We have uAssets issue tracker for that, post there instead.
