### ISSUE TITLE
ublock-origin defender (discussion)

### ISSUE THREAD

**Issue by Francois-dag** [uBlockOrigin/uBlock-issues#78]
Hello all,

sorry to disturb, but I'm wondering wether or not a defender (like nano defender) is strongly
recommended to prevent sites from saying "disable your ADblocker" ??

Cheers !

François

**Comment by uBlock-user** [comment]
It's optional.

**Comment by kowith337** [comment]
Have [uBO-Extra]https://github.com/gorhill/ubo-extra) already?
