### ISSUE TITLE
Add window height as an option under Settings

### ISSUE THREAD

**Issue by gitressa** [uBlockOrigin/uBlock-issues#785]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Sometimes there are quite a few third-party scripts from many domains on a web site. After clicking the uBlock Origin icon It would be great to be able to see the entire list of domains, without having to scroll.

**Possible solutions**

1. Make the window taller directly in the code
2. Allow the window to auto-grow to a certain height
3. Add window height as an option under Settings

### A specific URL where the issue occurs

https://www.nbc.com/

![nbc-ublock-window](https://user-images.githubusercontent.com/3491208/69057509-503bb200-0a12-11ea-946d-730a2ce7dd7d.png)

### Steps to Reproduce

1. Go to https://www.nbc.com/
2. Click the uBlock Origin icon
3. See that the list of domains extends below the window

### Expected behavior:

All domains should be visible.

### Actual behavior:

Only the first ten domains are visible.

### Your environment

* uBlock Origin version: uBlock Origin 1.23.0
* Browser Name and version: Firefox 70
* Operating System and version: Ubuntu 18.04

**Comment by gorhill** [comment]
> All domains should be visible.

This is unrealistic to expect that all domains should be visible -- the list could very well extend offscreen, something uBO wouldn't know about and which would cripple uBO usage.

Declined.

**Comment by gitressa** [comment]
Sure, but what about adding window height as an option under Settings? Would that be complicated?

**Comment by gorhill** [comment]
I vaguely remember sombody asking for an advanced setting for this -- is there an open issue about this? If not I will reopen this one.

**Comment by gitressa** [comment]
Thanks. I mentioned it in https://github.com/uBlockOrigin/uBlock-issues/issues/770#issuecomment-549161951, perhaps that's where?

**Comment by gwarser** [comment]
@gitressa check development build:

![image](https://user-images.githubusercontent.com/886325/80711552-d0516200-8af0-11ea-93a7-c7f56738b76f.png)

**Comment by gitressa** [comment]
It works perfectly, thanks @gorhill and @gwarser!

It would have been extra nice if the user could define max. window height in pixels as an option under /dashboard.html#settings.html, but this is in itself a great improvement.

**Comment by gwarser** [comment]
This isn't perfect:

![image](https://user-images.githubusercontent.com/886325/80797708-d43dbc80-8ba2-11ea-98cf-c17b1a9badc5.png)

This happens when window is near the bottom of the screen. It opens to the top when place is very limited, but if there is just enough place it's only "trimmed".

**Comment by gwarser** [comment]
@gorhill this clipping of the overview panel is a problem after all https://www.reddit.com/r/uBlockOrigin/comments/gk56f9/ublock_origin_1270_with_interface_redesign_is_out/fqswhq2/

**Comment by gorhill** [comment]
Unfortunately that is the browser doing this, I would expect the browser to respect its _own_ limited viewport and ensure the viewport set for the extension panel is properly resized to the restricted size.

**Comment by gorhill** [comment]
I am going to experiment to see if I can detect and adjust programmatically, maybe something like what is already being done to detect restricted width.

**Comment by gorhill** [comment]
The only solution I see now is to provide a new advanced setting to limit the height of the firewall pane to that of the basic pane. Currently as of 1.27.4, the firewall is unconstrained, i.e. it will expand beyond the height the the basic pane when there are lots of rows.

So while testing the new advanced setting `popupPanelLimitHeight`, this got me second guessing: should the height be constrained by default as it was prior to 1.27.0? Advanced users can always unconstrained the height by toggling the `popupPanelLimitHeight`.

I can't go through all the feedback regarding the changes in 1.27.0 -- has there been specific feedback regarding the unconstrained height of the firewall pane and if so how is the general reception? Do people in general prefer the constrained height?

**Comment by gitressa** [comment]
I would prefer the option of maximizing the pane to the max, utilizing as much as possible of the browser window. See for example [NBC](https://www.nbc.com/), where the complete list spans three scrolls:

1. The arrow denotes potential, but unused space 
![NBC-1](https://user-images.githubusercontent.com/3491208/82475072-387ddd00-9acc-11ea-8139-31b72c006019.png)
2. Second scroll
![NBC-2](https://user-images.githubusercontent.com/3491208/82475074-3a47a080-9acc-11ea-982f-2f432f7db31d.png)
3. Third and final scroll
![NBC-3](https://user-images.githubusercontent.com/3491208/82475089-40d61800-9acc-11ea-965d-b40a5f6f0291.png)

**Comment by Bookmarques** [comment]
What about making the blocked elements collapse like in uMatrix?

**Comment by Aybee** [comment]
I'm an HTML-Developer. With websites you can use CSS:
```css
.popup {
  height: 100vh; /* Viewport Height */
}
```
or:
```css
.popup {
  height: calc(100vh - 50px); /* calculated height */
}
```
You also can try to stretch the `.popup` so that all domains are visible but restrict it to a max height:
```css
.popup {
  height: 100%;
  max-height: calc(100vh - 50px); /* restricted to full height minus some pixels */
}
```
Don't know if this also workes with the browser engine.

I also would like to have the popup all the way to the bottom of the window.

**Comment by Aybee** [comment]
Fixed? Thank you.
