### ISSUE TITLE
uBlock icon not restored when customized in tabs-toolbar or menubar in Thunderbird

### ISSUE THREAD

**Issue by alta88** [uBlockOrigin/uBlock-issues#787]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
The uBlock 1.24.0 icon in Thunderbird is not being restored to a tabs-toolbar or menubar location on restart. This may be https://bugzilla.mozilla.org/show_bug.cgi?id=1584160 or it may be that, due to Tb's different toolbar code, the problem is in uBlock.

**Comment by gorhill** [comment]
The toolbar icon is entirely managed by the webext API `browserAction`, uBO has no knowledge of where and how the icon appears in the toolbar.

**Comment by alta88** [comment]
Yes, it's a fault in Tb and the icon would be restored if there were at least one other addon that was not restartless.
