### ISSUE TITLE
1.24 does not alow the user to add new functions/advanced options, and cnameAliasList is not automagically added to version 1.24 by the developer.

### ISSUE THREAD

**Issue by jabbberjaw** [uBlockOrigin/uBlock-issues#793]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[1.24 does not apply/save new functions/advanced options and cnameAliasList is not automatically added to version 1.24 by the developer.]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [I went to the add-ons section of firefox 70]
2. [Clicked on the ublock origin preferences]
3. [Clicked settings]
4. [Check marked I am a advanced user]
5. [Clicked on the advanced settings option]
6. [I typed in cnameAliasList * because its missing and when I clicked apply, ublock origin removed the new function/advanced option]

### Expected behaviour:

[I didn't know what to expect.]

### Actual behavior:

[Ublock origin 1.24 does not apply/save new functions/advanced options and cnameAliasList is not automatically added to version 1.24]

### Your environment

* uBlock Origin version: 1.24
* Browser Name and version: Firefox 70
* Operating System and version: Ubuntu 18.04 LTS

**Comment by uBlock-user** [comment]
It's in development currently. This is not an issue, this is how it's always been. Install dev build instead if you want to use cnameAliasList.
