### ISSUE TITLE
uBlock menu is broken on Firefox with apz.allow_zooming set to true

### ISSUE THREAD

**Issue by ahydronous** [uBlockOrigin/uBlock-issues#794]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On Firefox, setting `apz.allow_zooming` to `true` opens an [empty uBlock origin menu](https://user-images.githubusercontent.com/57762816/69502707-92815980-0f12-11ea-9069-1308cca6431b.png)

### A specific URL where the issue occurs

No

### Steps to Reproduce

1. Go to about:config
2. set apz.allow_zooming to true
3. Close Firefox completely
4. Launch Firefox and click on uBlock icon
5. The menu will not open properly

### Expected behavior:

Menu should open properly

### Actual behavior:

Menu didn't open properly

### Your environment

* uBlock Origin version: 1.24.0
* Browser Name and version: Firefox 70.0.1
* Operating System and version: macOS Catalina 10.15.1 (19B88)

**Comment by gwarser** [comment]
Firefox issue, fixed in Nightly(?) - https://bugzilla.mozilla.org/show_bug.cgi?id=1560770

**Comment by uBlock-user** [comment]
Fix landed in Nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1560770#c24
