### ISSUE TITLE
no-setInterval-if.js typo

### ISSUE THREAD

**Issue by eEIi0A5L** [uBlockOrigin/uBlock-issues#796]
wrong: setInterval-if.js
correct: no-setInterval-if.js
https://github.com/gorhill/uBlock/wiki/Resources-Library#setinterval-defuserjs-

**Comment by uBlock-user** [comment]
You fixed it in https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library/_compare/ed1447c%5E...ed1447c

So the change will merge by gorhill in that wiki later on.
