### ISSUE TITLE
Static filter is applied on domains not listed in domain option

### ISSUE THREAD

**Issue by goodness-from-me** [uBlockOrigin/uBlock-issues#797]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Given the following static filter rule (taken from `Fanboy’s Enhanced Tracking List`):
```
/favicon.ico$image,3p,domain=~winfuture.de|~bt.com|~ebay.com.au|~ebay.com|~ebay.co.uk|~go.com|~github.com|~stackexchange.com|~stackoverflow.com|~askubuntu.com|~reddit.com|~4chan.org|~twitter.com|~live.com|~espn.com|~yahoo.com
```
I see this rule applied when I visit not related domains, the logger shows it is triggered and favicon request is blocked.

### A specific URL where the issue occurs
https://ru.autoplius.lt/
### Steps to Reproduce

1. Add the following static filter:
```
/favicon.ico$image,3p,domain=~winfuture.de|~bt.com|~ebay.com.au|~ebay.com|~ebay.co.uk|~go.com|~github.com|~stackexchange.com|~stackoverflow.com|~askubuntu.com|~reddit.com|~4chan.org|~twitter.com|~live.com|~espn.com|~yahoo.com
```
2. Open the logger.
3. Go to https://ru.autoplius.lt/
4. Check out the logger.
5. See favicon request is blocked because of this filter rule.

### Expected behavior:
Filter not to be applied on domains that don't match `domain=` option.

### Actual behavior:
Filter is applied on random domains that don't match `domain=` option.

### Your environment

* uBlock Origin version: uBlock Origin 1.24.3b1
* Browser Name and version: Firefox Developer Edition 71.0b12 (64-bit)
* Operating System and version: Windows 10 1909

**Comment by uBlock-user** [comment]
`~` stands for exception, add `~ru.autoplius.lt` to the domain list if you don't want a match.
