### ISSUE TITLE
Doc of popup adv mode UI: semantics of row/col 3 color selections (green, gray, red)

### ISSUE THREAD

**Issue by BloomingAzaleas** [uBlockOrigin/uBlock-issues#798]
### Prerequisites

- [X ] I verified that this is not a filter issue **Not Applicable**
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question **Not Applicable**
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.  **Searched back to Sep 2017**
- I tried to reproduce the issue when... **Not Applicable**
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin **UBO 1.24.2**
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior **Not Applicable**

### Description

This is a UBO wiki documentation update request, NOT a functional issue.  The popup UI for UBO v1.24.2 with Dashboard Advanced User checked shows 2 columns to select settings for global and local (per site) behaviors (as gleaned from the displayed tooltips on the top row) for the displayed horizontal list.  For a row with no apparent active entry (non-white color entry) in one of these columns, a mouseover dynamically presents 3 blocks of color left-to-right (green, gray, red) presumably for a settings selection for the chosen row/column. The wiki doc as of 28 Nov 2019 shows the popup UI for UBO v1.17.0 which does not appear to have the 2 columns referenced.  No tooltips show for mouseover of the individual color blocks.  The result is that the behavioral change or functional parameter(s) change to be expected from selecting one of green, gray or red for a given row, or perhaps "type" of row, does not appear to be documented in the popup UI sections of the wiki.

Guessing: green means explicitly allowed or active (probably with corresponding new rule showing in the Rules dashboard), red means explicityly dis-allowed or inactive  (probably with corresponding new rule showing in the Rules dashboard), and gray means Revert To No Choice (possibly with an explicit NOOP in the Rules list).   I request updating the doc of the popup UI to UBO v1.24.2+ to reduce guesswork.

### A specific URL where the issue occurs
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel

### Steps to Reproduce

1.  Open UBO Dashboard, Setting tab -> check I am an advanced user
2.  In browser, go to any Web page, say a UBO wiki page on github.com.
3.  Open UBO popup UI. Should show rows/columns matrix to the left of the ON/OFF big blue icon.
4.  In either of the 2 narrower columns, mouseover the cells. Should show green, gray, red color blocks.

### Expected behavior:

**Maybe** tooltips on the semantics of the green, gray, red color block selection choices in other than top row especially if the semantics of each choice option are not identical for all rows.  

### Actual behavior:

Well, no tooltips but a wiki doc updated for current versions of UBO is the requested start.

### Your environment

* uBlock Origin version: UBO v1.24.2
* Browser Name and version: Firefox v70.0.1 64-bit
* Operating System and version: Win10 Pro 1803 (10.0.17134)

**Comment by uBlock-user** [comment]
@gwarser

**Comment by gwarser** [comment]
There's a reason this feature is hidden behind "I am an advanced user (required reading)" switch. Doc section you linked is for casual users.

**Comment by gwarser** [comment]
OK, no objections to not fixing this, but I think this can be improved anyway. Advanced topics can be hidden under foldable `<details>` tag. I modified this section already in draft, and it looks messy right now. Hiding some stuff in foldable section can improve this. I really don't think we should explain what red and green means (this was mentioned only briefly deep in wiki), but people asked so many times for tooltips that a small cheatsheet will not hurt.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Quick-guide:-popup-user-interface/_compare/6721554db3447c7a4fa4ff193c1020779bd772da...7ca6a7936e717bc1889df82bf0fa7f4ff9a4064d?short_path=e180a17#diff-e180a174f8d6c69ac6372ebf4e82b30c

How it looks now?

This gif on top is only experimental.

For me that's all. You can polish it a bit if you like.
