### ISSUE TITLE
Add PakistanAdBlockList to country list settings

### ISSUE THREAD

**Issue by PakistanAdBlockList** [uBlockOrigin/uBlock-issues#8]
Prerequisites

    I verified that this is not a filter issue
        Filter issues MUST be reported at filter issue tracker, NOT here.
    I performed a cursory search of the issue tracker to avoid opening a duplicate issue
        Your issue may already be reported.
    I tried to reproduce the issue when...
        uBlock Origin is the only extension
        uBlock Origin with default lists/settings
        using a new, unmodified browser profile
    I am running the latest version of uBlock Origin
    I checked the documentation to understand that the issue I report is not a normal behavior

Description

Websites in Pakistan are trying to block or bypass AdBlockers (g00 and Admiral). I will volunteer maintain the filter list for Pakistan.

Expected behavior:

Pakistan AdBlock List should be available in uBlock Origin filter country filter list settings.
The list is available at: https://raw.githubusercontent.com/PakistanAdBlockList/list/master/list.txt
The homepage of list is at: https://github.com/PakistanAdBlockList/list
The issue tracker is at: https://github.com/PakistanAdBlockList/list/issues

Your environment

    uBlock Origin version: 1.16.0
    Browser Name and version: Firefox Stable
    Operating System and version: Win10

**Comment by uBlock-user** [comment]
How come the list is empty ?

**Comment by gorhill** [comment]
You joined GitHub an hour ago. Your list is empty. Even if it was not empty, it needs a history of being developed over a long enough period of time, and show that it's used and appreciated by users.

**Comment by uBlock-user** [comment]
Put some effort and maintain it for a loger period of time befoe you ask to be added here.
