### ISSUE TITLE
Build instructions may require update (For Firefox)

### ISSUE THREAD

**Issue by LiCybora** [uBlockOrigin/uBlock-issues#80]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The current build instructions seems to be outdated. 
If I understand correctly, the current `make-firefox.sh` is building **web extension** of Firefox since [c9b14e2](https://github.com/gorhill/uBlock/commit/c9b14e201a6e932158b47837e02963ca104ae602). The current `make-webext.sh` is for Debian package which is supposed to be shared between Firefox and Chromium since [0bf2f27](https://github.com/gorhill/uBlock/commit/0bf2f27d87614e9e6996c9ff68a43b633e52b41d) according to [README](https://github.com/gorhill/uBlock/blob/master/platform/webext/README.md). The legacy build has to switch to another branch [firefox-legacy](https://github.com/gorhill/uBlock/tree/firefox-legacy) and use the `make-firefox-legacy.sh` since [1bb12df](https://github.com/gorhill/uBlock/commit/1bb12dfec72161b6eda16299cd2a65a6e7fe3640).
Although it should be fine for building Firefox by current `make-webext.sh`, releases seems to be built from `make-firefox.sh` (distinguished by unlimited storage permission, and some other unnecessary key in manifest, and warning in browser console).

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/blob/master/dist/README.md
https://github.com/gorhill/uBlock/blob/firefox-legacy/dist/README.md

### Steps to Reproduce

1. Browse homepage and link to build instruction, or directly the link above, doesn't matter.
2. Follow the instruction fails to build legacy Firefox.
3. The web extension for Firefox different from the release (permission when install will tell without unpacking and view in deep), but this should be fine and not affect normal usage.

### Expected <del>behavior</del> building steps:
...
- Build the plugin:
    - Chromium: `./tools/make-chromium.sh`
    - Firefox webext: `./tools/make-firefox.sh all`
    - Firefox legacy: `git fetch | git checkout firefox-legacy` then `./tools/make-firefox-legacy.sh all`
...
    - Firefox: drag-and-drop `/uBlock/dist/build/uBlock0.firefox.xpi` or `/uBlock/dist/build/uBlock0.firefox-legacy.xpi` into Firefox.

### Actual <del>behavior</del> building steps:
...
- Build the plugin:
    - Chromium: `./tools/make-chromium.sh`
    - Firefox webext: `./tools/make-webext.sh all`
    - Firefox legacy: `./tools/make-firefox.sh all`
...
    - Firefox: drag-and-drop `/uBlock/dist/build/uBlock0.firefox.xpi` or `/uBlock/dist/build/uBlock0.webext.xpi` into Firefox.

### Your environment

* uBlock Origin version: 1.16.10
* Browser Name and version: Firefox
* Operating System and version: Linux

**Comment by uBlock-user** [comment]
@gwarser Can you edit the wiki ? I would have to open up a pull request instead.

**Comment by gorhill** [comment]
> Firefox webext: `./tools/make-webext.sh all`

Firefox version as the one found on AMO is `./tools/make-firefox.sh all`

**Comment by gwarser** [comment]
I can edit organization, this "readme" is in gorhill _private_ repository.

**Comment by LiCybora** [comment]
> can you confirm the suggested building steps ?
I run on my machine and can be confirmed building succcessfully. You may double check.

In simple:
 - Replace `webext` with `firefox` for building Firefox extension
 - Replace`firefox` with `firefox-legacy` for building Firefox legacy
      - And one more requirement before run build script: switching to branch `firefox-legacy` instead of master.

Also, in the installation part, the filename of releases has to be update. The README.MD in master branch has correct Firefox legacy name, but the web extension part still keep `ublock0.webext.xpi` instead of `ublock0.firefox.xpi` (or even with .signed for rc/b release). The one in `firefox-legacy` branch is however, wrong for both.

**Comment by uBlock-user** [comment]
Thanks for the info, but that question was to gwarser. I don't run a virtual machine, so I can't confirm or double check for that matter.

**Comment by gwarser** [comment]
Yes, it's OK.

**Comment by gwarser** [comment]
I'm not sure about installing in Firefox. Drag&drop not work for me. For developer build will be best to use `about:debugging` -> click on "Load Temporary Add-on". I still see "Install Add-on From File" in `about:addons`, but this probably works for signed extensions only.

**Comment by uBlock-user** [comment]
Will need to open a pull request or if gorhill himself to add it ?

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/commit/8b9dc4673566fe572be3a09b2ac9948f3da68408
https://github.com/gorhill/uBlock/commit/bab3a547ceff19a805246b388e0436dc8b8b218f

**Comment by LiCybora** [comment]
Thx, but for Firefox legacy, the [build script](https://github.com/gorhill/uBlock/blob/firefox-legacy/tools/make-firefox-legacy.sh) should be `./tools/make-firefox-legacy.sh all`

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/commit/e8e1b9eb0790c5423660a0e7b9d9fe439c0995dc
