### ISSUE TITLE
Suggestion: add Fanboy's antifont list

### ISSUE THREAD

**Issue by jones137** [uBlockOrigin/uBlock-issues#801]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It would be nice to officially include Fanboy's anti-font filter list, just like Anti-Facebook is.
https://fanboy.co.nz/filters.html

Despite only being CSS, google's fonts for example act just like tracking pixels, telling when you visited a website they are on. I think including it in uBO without having to import manually would benefit some new users.

**Comment by gorhill** [comment]
I don't see the point, there is already a no-remote-fonts switch available in the popup panel.

**Comment by jones137** [comment]
> I don't see the point, there is already a no-remote-fonts switch available in the popup panel.

Yeah but it breaks reddit's CDN fonts for example, whiile the custom list is better crafted without breakage

**Comment by gorhill** [comment]
That list will also break Reddit once I enable CNAME un-cloaking by default, it has the filter `||fastly.net^$font,3p` in it.

**Comment by jones137** [comment]
What I meant is the upvote/downvote arrows for example, so totally custom font with custom purpose, not just different look of text.

**Comment by gorhill** [comment]
Yes, those are broken by that anti-font list when `cnameAliasList` is set `*`. Just use the switch is the proper advice, it's a mere point-and-click to unbreak a site broken by missing fonts while with a list it's far more complicated to unbreak.

**Comment by jones137** [comment]
OK thanks for clarification then
