### ISSUE TITLE
Blocked items in a headless browser

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#802]
A few scripts using encrypted/obfuscated javascript, and I'm wanting to know if its possible to do this;

From a command line (using Linux here):
1. Load a selected site
2. Then output the blocked/unblocked items.

Not the same as simply outputing the source, but allowing authors to grep and automate blocking of scripts being loaded from a headless setup.

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.

**Comment by gorhill** [comment]
Do you mean a "headless browser" (which) with uBO installed in it?

**Comment by ryanbr** [comment]
Possibly in a headless chrome setup,  which we can load a site and pull the unblocked/blocked items from a site

**Comment by gorhill** [comment]
Sounds like a whole new project to be worked on by a motivated developer. I just don't have the motivation and time to take on that sort of project.
