### ISSUE TITLE
Cosmetic filtering issue with Shadow DOM/tree/root

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#803]
<details>
<summary>Details</summary>

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

1. Generic cosmetic filters don't hide nodes in Shadow DOM. Probably not injected to the page because nodes "in shadow" are not detected.
	- Related issue https://github.com/easylist/easylist/pull/4232
	- This works in ABP/AdBlock, Chrome 78 (Probably because all filters are injected?).
1. Specific filters works, but are not logged.
	- This does not work in ABP/AdBlock.

### A specific URL where the issue occurs

https://www.virustotal.com/gui/home/upload

### Steps to Reproduce

"Generic" case:
1. Add `###euConsent` to My filters
2. Open linked VirusTotal page

"Specific" case:
1. Add `virustotal.com###euConsent` to My filters
2. Open linked VirusTotal page

### Expected behavior:

Cookie notice on the bottom should be hidden with generic filter. Filter should be logged.

### Actual behavior:

Notice is hidden only by specific filter. No DOM filters are logged.

### Your environment

* uBlock Origin version: 1.23 on Chrome, 1.24.3b1 on Nightly, 1.24 on 70.0.1 Fx
* Browser Name and version:
* Operating System and version: Manjaro KDE

***

@krystian3w, it's side effect of uBO performance/memory optimizations. ABP injects all cosmetic filters unconditionally (AFAIK). uBO injects only specific filters. For generic filters, DOM is scanned and only matching ones are injected. Here Shadow DOM is interfering.

**Comment by gorhill** [comment]
Well just to be clear, uBO will never be converted to inject minimum of 20K+ CSS rules. So if specific filter is the only solution then the resolution is "by design".

**Comment by krystian3w** [comment]
So PR in `Annoyance.txt` if Fanboy Annoyance / AdGuard Annoyance reject filter with domain, because use generic without `$generichide`?

**Comment by uBlock-user** [comment]
> Add ###euConsent to My filters

That CSS selector will only be present in the DOM if you connect via EU IP, do you have one that is present for all ?

**Comment by gorhill** [comment]
I am not in a position to check myself... Is this Shadow DOM v1 or v2?

**Comment by gwarser** [comment]
Personally for me this issue by itself is (partial) solution as documentation.

This page is build on Shadow DOM so for testing you can choose any element you want.

**Comment by uBlock-user** [comment]
Yes picker cannot dig on that page either beyond `vt-virustotal-app`

**Comment by uBlock-user** [comment]
`###share` is shown in the logger if added.

**Comment by gwarser** [comment]
I don't see `#share` even in DevTools.

**Comment by gwarser** [comment]
>  Is this Shadow DOM v1 or v2?

Do you mean v0 or v1? I need to learn about it first.

**Comment by uBlock-user** [comment]
> I don't see #share even in DevTools.

![image](https://user-images.githubusercontent.com/21290713/69905990-57839800-13e2-11ea-9e8e-a81f5529791d.png)

**Comment by gorhill** [comment]
One solution I can think of is to make use of ABP's semantic, `#?#`, in which case uBO would put the cosmetic filter in the highly generic bin and thus would inject it unconditionally on each page/frame.

**Comment by gorhill** [comment]
> Do you mean "v0 or v1"?

Yes.

**Comment by gwarser** [comment]
This `g` is inside svg image, Chrome does not show this.

>make use of ABP's semantic, `#?#`

This is not a solution. Filter authors will be forced to adjust filters, does not matter if they make them specific or modify syntax in different way. Individual cases will need to be found and fixed. It will be rare/surprising now, when not many such cases exist, and eventually later when SD will become popular, all filters will need to be rewritten.

**Comment by gorhill** [comment]
I don't understand your argument. If indeed

**Comment by gwarser** [comment]
> If indeed `#euConsent` become widespread and part of Shadow DOM (maybe by mean of JS library),

:+1:, here it will work. And I even see example - content of Twitter widgets.

**Comment by llacb47** [comment]
Another site using a shadow root DOM: `https://yandex.ru/pogoda/new-york`.

**Comment by gorhill** [comment]
Issue can be reproduced using `#mainContent` selector, so no need to get a EU IP address to reproduce.

Weeks ago I have investigated a javascript-based solution and it does not work -- there is no way to `querySelector` across shadow DOM boundaries and adding code to work around this is anything but trivial.

So back then I locally added code to interpret `#?##mainContent` as _"bypass surveyor and inject unconditionally the selector"_. But I keep having second thoughts about this and the changes have been lingering in my local dev build.

**However**, today I realize that `*###mainContent` does also fix the issue with no code change (i.e. this would work immediately in current stable release), so I am wondering whether this should simply be used rather than introducing the new syntax above. We could simply define `*` as hostname to mean _"bypass surveyor and inject unconditionally"_ and revise the documentation and warn this should only be only when needed.

**Comment by uBlock-user** [comment]
Can new syntax like #?##.selector support specific hostnames ? Because filters like `*##.selector` can be added in any third-party filterlist for fixing some website that a user like me would never visit and wouldn't feel comfortable knowing the performance issue that brings at hand, so having such filters be able to target only specific hostnames would rather be preferable.

**Comment by gorhill** [comment]
> performance issue that brings at hand

Please no unfounded speculation of "performance issue", this is **not** helpful. If you want to make the case of "performance issue", this needs to be done with profiling results.

**Comment by uBlock-user** [comment]
By performance issue, I meant the filter is applied on every webpage on every website, doesn't that account for some performance cost ?

**Comment by krystian3w** [comment]
And EasyList / EasyList Cookie (https://github.com/easylist/easylist/pull/4232) will not use:

`*##ELEMENT`

for uBO only...

**Comment by gorhill** [comment]
> doesn't that account for some performance cost ?

uBO already injects over 750+ selectors unconditionally on every page with default configuration -- the "highly generic ones" -- out of a total of nearly 21,000 cosmetic filters.

The change here just allows to explicitly force such unconditional injection for _some_ filters which _must_ be generic but _can't_ be injected conditionally through the DOM surveyor.

I expect filter list authors will use the new feature intelligently, the same way the use of regex-based network filters are discouraged, yet they are not forbidden and filter list authors know that they should be used only when there is no other solution. Same approach applies here.

Also I will likely consider <https://github.com/uBlockOrigin/uBlock-issues/issues/821> to be solved by the solution implemented here.

**Comment by uBlock-user** [comment]
Still we would have some control if it was specific to a hostname instead of getting applied on every website regardless of whether the element is present in the DOM or not.

**Comment by gorhill** [comment]
> if it was specific to a hostname instead of getting applied on every website

Generic filters which apply everywhere are already supported and unconditional injection is already occurring. There is no good rational reason to worry about the change here. I will leave it at that, I can't prevent people from being unduly anxious about non-issues, I have no control over that.

**Comment by gwarser** [comment]
@uBlock-user what you are talking about? Specific filters still work.

@gorhill how about pont 2:

>Specific filters works, but are not logged. 

?

**Comment by krystian3w** [comment]
No visible in logger (on table)? No every one use dom tree debugger "`</>`".

**Comment by gorhill** [comment]
Point 2 is "wontfix" -- this would require to find all nodes with a shadow DOM (which requires traversing _all_ nodes -- there is no native function to get all shadow DOM nodes), then search independently for a match in all these nodes, along with installing a mutation observer for each of those nodes to find out changes withing the shadow DOMs. I decline to make the code more complex than it already is.

**Comment by uBlock-user** [comment]
> what you are talking about? Specific filters still work.

@gwarser It was about `*##.selector`, it can't be made specific. You can disable that filter at specific sites thats all.

**Comment by h1z1** [comment]
FWIW you can add pornhub to the list.  They have an annoying banner that cannot afaik be blocked because it uses a shadow root.

**Comment by krystian3w** [comment]
`ghide` can break:

```
@@*$ghide
`*##.selector`
```

this is good behavior?


---

in legacy try:

`@@*$generichide`
`github.com,##.selector`

**Comment by gorhill** [comment]
> this is good behavior?

Not sure. I lean toward yes. Is this an issue in a list?

**Comment by gargul2** [comment]
I've found something..
actually I've found two issues,
not sure whether they are bugs or features,

Reproduce:
1) Add `*##div:matches-css(height: 250px)`
2) Logout from github
3) Open uBO Logger
4) Go to https://github.com/join
5) Notice Captcha is hidden (thus can't create an account)
6) The responsible filter is not visible in the logger
7) Use `@@*$ghide` as per [uBO Wiki](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#specific-generic) or as per https://github.com/uBlockOrigin/uBlock-issues/issues/521 but it's not working in this case
8) What actually works is `@@*$shide` (I actually use `@@||api.funcaptcha.com^$shide`)

It's about 6) and 7+8), is it ok?

**Comment by krystian3w** [comment]
IMO possible revert https://github.com/uBlockOrigin/uAssets/commit/0d78532352342e95b59823ae765ab8879a844ebd due https://github.com/easylist/easylist/commit/d3530c02693b70eba05f177d28d985edb5c8dcd7

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8714e19b50a723d5559d86d6c21b1e76a3da4a53
