### ISSUE TITLE
Source list of entity filter with subdomain is not looked up correctly

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#805]
<details>
<summary>Details</summary>

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

</details>

### Description

Logger details view for `www.example.*##p` shows "Static filter `##p` could not be found in any of the currently enabled filter lists"

@okiehsch found it here: https://github.com/uBlockOrigin/uAssets/issues/6637#issuecomment-559887700

This started with https://github.com/gorhill/uBlock/commit/a73dd0a9f26df59cfb4b68e98d1184ac042c90ea and obviously before this commit scriptlet is not even logged.

`reEntity`, `^gmx\.\*$` does not match `www.gmx.com` in `reverselookup-worker.js`, `hostnameMatches` function.

### A specific URL where the issue occurs

- http://www.example.com/

### Steps to Reproduce

1. add `www.example.*##p` to My filters
2. open logger
3. open http://www.example.com/
3. click on `p` entry in the logger

### Expected behavior:

Filter list
My filters

### Actual behavior:

Filter list
Static filter ##p could not be found in any of the currently enabled filter lists

### Your environment

* uBlock Origin version: 1.23, 1.24.3b2
* Browser Name and version: Chrome, Firefox
* Operating System and version:

***

This seems to work:

```diff
diff --git a/src/js/reverselookup-worker.js b/src/js/reverselookup-worker.js
index eb12ccea..3042e5fc 100644
--- a/src/js/reverselookup-worker.js
+++ b/src/js/reverselookup-worker.js
@@ -141,8 +141,8 @@ const fromCosmeticFilter = function(details) {
     );
 
     let reEntity,
-        domain = details.domain,
-        pos = domain.indexOf('.');
+        domain = details.hostname,
+        pos = domain.lastIndexOf('.');
     if ( pos !== -1 ) {
         reEntity = new RegExp(
             '^' +
```

**Comment by uBlock-user** [comment]
I'm experiencing the same at `https://www.kyivpost.com/article/opinion/op-ed/sergii-leshchenko-the-true-story-of-yanukovychs-black-ledger.html` with exception filters there. Related ?


![image](https://user-images.githubusercontent.com/21290713/70118826-fa603e80-168e-11ea-9909-1391b69d4489.png)

**Comment by gwarser** [comment]
Different. I think this time reverse-lookup confuses this filter with regex...

This one from Fanboy Annoyance?

    @@/wp-content/plugins/super-socializer/js/front/social_login/*$~third-party


There is `*` at the end, and I think this was recently corrected to be removed for some reason.

**Comment by uBlock-user** [comment]
So a different issue ? 

> This one from Fanboy Annoyance?

Seems so, I can't tell. I have many stock filterlists activated.

**Comment by gwarser** [comment]
I think you have found regression from the regression fix https://github.com/gorhill/uBlock/commit/7c0294bd5f541951c45f3841cfad7dddfd52be4d

I'm not sure, but `badfilter` seems to be broken too.

**Comment by uBlock-user** [comment]
The same filter is present in Fanboy Social too...

> I'm not sure, but badfilter seems to be broken too.

because it can't locate where the filter is before it can badfilter it ? So by-design broken too ?

**Comment by gwarser** [comment]
I did not followed more in debugger, but when `*` is missing, filter is detected as regex (because of `/.../`) and re-compiled (passed to `RegExp(...)`) to "normalize" regex syntax. This causes all `/` to be escaped `\/` and that's probably why it does not match anymore.

**Comment by okiehsch** [comment]
> I'm not sure, but badfilter seems to be broken too.

`@@/wp-content/plugins/super-socializer/js/front/social_login/*$~third-party,badfilter`
works on my end.

**Comment by uBlock-user** [comment]
badfilter for `@@/wp-content\/plugins\/super-socializer\/js\/front\/social_login/$1p` won't work.

**Comment by okiehsch** [comment]
Works on my end.
![image](https://user-images.githubusercontent.com/16838044/70137381-0f889d80-168e-11ea-83fe-f7f7a9edaf65.png)

**Comment by uBlock-user** [comment]
I added the wrong one, it would be  --

`@@/wp-content/plugins/super-socializer/js/front/social_login/$1p,badfilter` doesn't get applied on my Nightly.

**Comment by gwarser** [comment]
Logger will report filter without the `*` so it will not work.

**Comment by okiehsch** [comment]
Same result on my end Firefox stable with the latest `uBO-dev`.
![image](https://user-images.githubusercontent.com/16838044/70137859-4317f780-168f-11ea-8572-4a0b1ad7ae71.png)

**Comment by gwarser** [comment]
@@/wp-content/plugins/super-socializer/js/front/social_login/*$1p
    @@/wp-content/plugins/super-socializer/js/front/social_login/$1p,badfilter

Try this. You will not know original filter is with `*` - logger does not show this.

**Comment by uBlock-user** [comment]
or just enable Fanboy Annoyance/Social and then badfilter it.

**Comment by okiehsch** [comment]
> Try this. You will not know original filter is with * - logger does not show this.

That is correct you will have to try
````
@@/wp-content/plugins/super-socializer/js/front/social_login/$1p,badfilter
@@/wp-content/plugins/super-socializer/js/front/social_login/*$1p,badfilter
````
to be certain.
