### ISSUE TITLE
forum.worldofwarships.ru bug with uBO 1.24.3b2

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uBlock-issues#806]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It only starts reproduceable from 1.24.3b2. 
Filter `||pw^$third-party,script,xmlhttprequest,domain=~adwiz.pp.ua|~hdvbplayer.tk|~live-gol.net|~softpir.com|~sportings.pw|~sportsvideoline3.pw|~videosofsport1.pw|~xn--drakulastrem-b7e.com`
from RU AdList starts to work in 1.24.3b2 (which it does not in 1.24.3b1 and earlier), forbidding requests from `ix-c1-59-51.fe.core.pw` and thus breaking certain functions (posting when logged in, display of hidden frames breaks). At the same time, in the logger's entry of this filter [there is a string "CNAME"](https://i.imgur.com/zkAaEWM.jpg), which is not found in most other filters. I believe such behaviour is related [to this commit](https://github.com/gorhill/uBlock/commit/3a564c199260).

### A specific URL where the issue occurs

`https://forum.worldofwarships.ru`

### Steps to Reproduce

1. Go to [that topic](https://forum.worldofwarships.ru/topic/134845-%D0%B8%D1%82%D0%BE%D0%B3%D0%B8-14-%D0%B3%D0%BE-%D1%80%D0%B0%D0%BD%D0%B3%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D1%81%D0%B5%D0%B7%D0%BE%D0%BD%D0%B0-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B2%D0%B7%D1%8F%D1%82%D0%B8%D1%8F-1-%D0%B3%D0%BE-%D1%80%D0%B0%D0%BD%D0%B3%D0%B0/).
2. See expanded screenshots in 1st post.

### Expected behavior:

This is frame with hidden content, it should be minimized by default [like this](https://i.imgur.com/4FsCm5N.jpg); besides, when logged in, you cannot leave a post - response form remains unavailable.

### Actual behavior:

Some functionality breaks.

### Your environment

* uBlock Origin version: 1.24.3b2
* Browser Name and version: Firefox 71 build 4 (beta-channel)
* Operating System and version: Win 7 Pro x64

**Comment by uBlock-user** [comment]
CNAME uncloaking is now enabled by default with https://github.com/gorhill/uBlock/commit/91e702cebbe52137f59a94f55e46d31f95eb98b9

Did you change `cnameIgnoreExceptions` ?

**Comment by gorhill** [comment]
This will have to be fixed by filter list maintainers -- this is a filter issue.

**Comment by TheFinalCut83** [comment]
I did; didn't help.

**Comment by gorhill** [comment]
> I did; didn't help.

What do you mean exactly? The maintainers did not want to fix the filter? If so we will do it in _"uBlock filters -- Unbreak"_.

**Comment by TheFinalCut83** [comment]
@gorhill no, it was answer to "Did you change cnameIgnoreExceptions" by @uBlock-user I'm already writing to Ru AdList topic.
