### ISSUE TITLE
Firefox 72beta 2 does not update to latest uBlock 1.24.3b3

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uBlock-issues#807]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Firefox 72beta 2 does not update to latest uBlock 1.24.3b3
[Description of the bug or feature]
https://github.com/gorhill/uBlock/releases/download/1.24.3b3/uBlock0_1.24.3b3.firefox.signed.xpi
dont work "not signed"
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [klick on https://github.com/gorhill/uBlock/releases/download/1.24.3b3/uBlock0_1.24.3b3.firefox.signed.xpi]
2. [nothing]
3. [1.24.3b2 works]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:1.24.3b2
* Browser Name and version:Firefox 72b2x64
* Operating System and version:Windows 10 1909 x64

**Comment by troysjanda** [comment]
this is also no updating in the Firefox 71 either. I also tried to update from the github and getting Firefox has prevented Firefox from installing an unverified addon error message.

**Comment by uBlock-user** [comment]
Seems this version of package is unsigned and hence getting rejected from successful installation. You can flip `xpinstall.signatures.required` to `false` if you want a workaround, or just wait for gorhill to get the signed package released instead.

**Comment by eEIi0A5L** [comment]
Firefox's browser console says signature error.
![無題](https://user-images.githubusercontent.com/30253227/70164297-439ea580-1704-11ea-977c-6e3f746fcb7c.png)

**Comment by gorhill** [comment]
Should be fixed now, I had to manually download/re-upload the package -- for some reasons it seems Mozilla's server did not serve me the proper package.
