### ISSUE TITLE
Nested "!#include" directive does not honor relative URL path

### ISSUE THREAD

**Issue by reallyuniquename** [uBlockOrigin/uBlock-issues#810]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin Legacy
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

For instance, filter list `a.txt` includes `b.txt` that includes `c.txt`. `!#include` directives in `b.txt` fail to construct correct URL path. URIs in `b.txt` are relative to `b.txt` location yet uBlock treats them as relative to `a.txt` location.

### A specific URL where the issue occurs

`https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt`

### Steps to Reproduce

1. Install uBlock Origin 1.16.4.11 (legacy)
2. Open dashboard
3. Import filter list `https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt`
4. Apply changes

### Expected behavior:

uBlock successfully fetches specified list and all its dependencies:
```
ultralist.txt: !#include filters/css_style_filters.txt
->
css_style_filters.txt: !#include css_companion_filters.txt
```
=>
```
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt
->
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt
->
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_companion_filters.txt
...
```

### Actual behavior:

uBlock fails to fetch one of the nested dependencies `css_companion_filters.txt` since it constructs incorrect URL path, `/filters/` subfolder is missing in the last URL:
```
ultralist.txt: !#include filters/css_style_filters.txt
->
css_style_filters.txt: !#include css_companion_filters.txt
```
=>
```
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt
->
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt
->
[404] https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/css_companion_filters.txt
...
```

### Your environment

* uBlock Origin version: 1.16.4.11 (legacy)
* Browser Name and version: Waterfox 2019.10 / Firefox 56
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
Fix in current https://github.com/gorhill/uBlock/commit/923c5ce5bd98a7ca50cbb2dca14213f979eaf35d

**Comment by gorhill** [comment]
> Firefox 56

Issue does not exist in current uBO, which is compatible with Firefox 55+.

**Comment by reallyuniquename** [comment]
But isn't uBlock Legacy still supported at least in maintenance mode?

Web Extensions support is quite poor and unstable in pre-quantum Firefox. Plus uBlock Legacy has some unique features that WE counterpart lacks.

Would it be possible to port those fixes on uBlock Legacy?

**Comment by gorhill** [comment]
Pull requests made and tested with care are accepted. I do not want to spend my own time on something I will never use, and if I am going to spend time on development, I rather do it on uMatrix which has not been moving forward for months now.

**Comment by JustOff** [comment]
@gorhill, could you please take a look at [this solution](https://github.com/JustOff/uBlock/commit/574cb17702a372638ddd61fcbe51a741103807c9), based on https://github.com/gorhill/uBlock/commit/923c5ce5bd98a7ca50cbb2dca14213f979eaf35d?

I'm ready to make a pull request if you allow.

**Comment by gorhill** [comment]
If you tested that the fix work I will just pull it, I just do not have the time to code review or test the fix myself.

**Comment by JustOff** [comment]
Yes, here are the logs:

```
20:10:40.542 GET XHR https://raw.githubusercontent.com/gorhill/uBlock/firefox-legacy/assets/assets.json [HTTP/1.1 200 OK 189ms]
20:10:41.248 GET XHR https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resources.txt [HTTP/1.1 200 OK 63ms]
20:10:41.838 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt [HTTP/1.1 200 OK 165ms]
20:10:42.041 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/ad_placeholders.txt [HTTP/1.1 200 OK 127ms]
20:10:42.043 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt [HTTP/1.1 200 OK 1191ms]
20:10:42.044 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/generic_filters.txt [HTTP/1.1 200 OK 210ms]
20:10:42.045 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/modal_filters.txt [HTTP/1.1 200 OK 305ms]
20:10:42.046 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/newsletter_filters.txt [HTTP/1.1 200 OK 243ms]
20:10:42.048 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/social_filters.txt [HTTP/1.1 200 OK 244ms]
20:10:43.242 GET XHR https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_companion_filters.txt [HTTP/1.1 200 OK 126ms]
```

**Comment by gorhill** [comment]
You can submit a pull request to <https://github.com/gorhill/uBlock/tree/firefox-legacy> now, this will make you a contributor and enable you to submit future pul lrequests as you wish.

**Comment by JustOff** [comment]
Thank you, however, I have already committed to uBlock repo [recently](https://github.com/gorhill/uBlock/pull/3750), but this did not make me a contributor, perhaps due to the fast-forward merge you use.

**Comment by gorhill** [comment]
The interaction limit description says:

> Users that have not previously committed to the repository’s master branch will be unable to interact with the repository.

So you need to contribute to master to become a contributor. We need to find something for you to create a pull request in master.
