### ISSUE TITLE
Immediate high virtual memory usage when installing to new Firefox profile

### ISSUE THREAD

**Issue by roxihe7880** [uBlockOrigin/uBlock-issues#811]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After installing uBlock Origin in a new Firefox profile virtual memory usage immediately goes to 26GB and Firefox renders pages slower. This is also observed when disabling then renabling the extension. It doesn't happen with 10 other popular extensions that I have.

### A specific URL where the issue occurs

https://danluu.com/

### Steps to Reproduce

1. Create a new profile `mkdir ~/new-firefox-profile`
2. Launch firefox `/usr/lib/firefox/firefox --profile ~/new-firefox-profile`
3. Install uBlock Origin from about:addons
4. Observe high virtual memory usage

### Expected behavior:

Low increase in virtual memory

### Actual behavior:

High increase in virtual memory and slower firefox rendering

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 71.0-1
* Operating System and version: archlinux with swaywm

**Comment by roxihe7880** [comment]
Screenshot of `htop`
![screenshot-20191207-043155](https://user-images.githubusercontent.com/58612372/70374713-8f8b4f00-18aa-11ea-9f55-a11b289e4c47.png)

**Comment by roxihe7880** [comment]
Thanks for creating and maintaining this extension. If you need more info I can provide it.

**Comment by uBlock-user** [comment]
Run Firefox Profiler and post the results here if you want to claim this as a uBO issue.

**Comment by roxihe7880** [comment]
Here's the Firefox Profiler capture
[Firefox 2019-12-07 04.59 profile.json.gz](https://github.com/uBlockOrigin/uBlock-issues/files/3935081/Firefox.2019-12-07.04.59.profile.json.gz)

**Comment by gorhill** [comment]
Virtual memory is just addressing space, not physical memory. Firefox reserves this addressing space when instantiating WASM modules. See <https://bugzilla.mozilla.org/show_bug.cgi?id=1552615>.

**Comment by roxihe7880** [comment]
Thanks for taking the time to reply :)

**Comment by ranolfi** [comment]
Indeed setting `disableWebAssembly` to `true` in the [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings) normalizes the WebExtensions process _vsize_.
