### ISSUE TITLE
Inline script that encrypts site content?

### ISSUE THREAD

**Issue by CapSel** [uBlockOrigin/uBlock-issues#814]
Is there a way to block it?

Usually blocking inline scripts on the page fixes issue. But on this site everything disappears. All tags names are random.

https://natemat.pl/293183,prawica-ma-swoja-grete-thunberg-kim-jest-izabella-nilsson-jarvandi

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.
