### ISSUE TITLE
popup UI does not open up when clicked on the extension icon on first click

### ISSUE THREAD

**Issue by daviehh** [uBlockOrigin/uBlock-issues#815]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On first click of the ublock icon, the menu often does not show up

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
github.com
or anywhere

### Steps to Reproduce

1. go to github.com in a new tab
2. click ublock icon
3. no menu shows up, only a tiny "box" (see attached picture)

### Expected behavior:

See the ublock menu

### Actual behavior:

no menu

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: firefox, 72.0b5 (64-bit)
* Operating System and version: macos, 10.15.1 (19B88)

<img width="304" alt="Screen Shot 2019-12-11 at 8 14 16 PM" src="https://user-images.githubusercontent.com/25255906/70674191-41cc6900-1c53-11ea-99d7-970ccd18daa3.png">

**Comment by gwarser** [comment]
Did you changed "async pan zoom" settings in about:config?

**Comment by daviehh** [comment]
"async pan zoom" is default (true), it's also sort of intermittent/not always reproducible

**Comment by uBlock-user** [comment]
Whatever changes you made to `about:config` are listed in `prefs.js` remove that file from the profile folder of Firefox and see if it happens again.

**Comment by gorhill** [comment]
The browser is responsible for embedding uBO's popup panel in the popup window, so if it does not appear in there, it's a browser issue. `apz.allow_zooming` set to `true` is known to cause this exact issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1560770>.
