### ISSUE TITLE
Tab opened via right-click google search from piknu.com, getting closed when clicking on instagram.com result

### ISSUE THREAD

**Issue by mica** [uBlockOrigin/uBlock-issues#816]
This is a strange one... 

1. Open a piknu account page, e.g: https://piknu.com/u/obviousplant

2. Highlight and right-click > search the username

3. Click instagram.com/username result, and behold as the tab is inexplicably closed

**Comment by llacb47** [comment]
Bad easylist rule is blocking me from even doing right-click -> search with google.

`/^https?:\/\/.*[&|%|+|=].*/$popup,domain=0123movies.com|123unblock.info|...|piknu.com|...`
