### ISSUE TITLE
Settings deleted, not saved after Update anymore and Functions not working.

### ISSUE THREAD

**Issue by JPRuehmann** [uBlockOrigin/uBlock-issues#817]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
If I start Thunderbird all previous Settings I made are gone, if I mde them new and restart Thunderbird tey are gone again, and some functions completely not working.
[Description of the bug or feature]
Settings not saved between restarts of Thunderbird since Update to B5
Element Deleting Mode never worked
Element Picker Mode never worked
Where are the Backups storred? Nothing to be found after restarting Thunderbird.

### A specific URL where the issue occurs
All

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
no, restart thunderbird after changing settings will trigger it.

### Steps to Reproduce

1. Change Settings
2. restart Thunderbird

### Expected behavior:
Should work a before the restart of Thunderbird.
[What you expected to happen]

### Actual behavior:
Works as newly installed (all functions disabled.
[What actually happened]

### Your environment

* uBlock Origin version: v1.24.3b5
* Browser Name and version: Thunderbird 68.3.0 (32-Bit)
* Operating System and version: Kubuntu 18.04 LTS (32Bit)

**Comment by JPRuehmann** [comment]
Sorry not my Day today.
I have found the Problem, it is the new Version 2.1.4 of Enigmail.
If I uninstall and/or reinstall 2.1.3 it works flawless again.
Thanks,

**Comment by gorhill** [comment]
> - [ ] uBlock Origin is the only extension

This is why all steps must be checked before opening an issue -- this is to avoid opening issues which are caused by other extensions.

**Comment by JPRuehmann** [comment]
sorry but I had disabled all othe AddOns and te Problem still occurs.
Should be the same.
And I don´t think that is so easy because the Developer of Enigmail says that it is not possible that his AddOn can produce that Problems.

Secondly what is with the other Problems? that had not worked anyways.

**Comment by gorhill** [comment]
> I had disabled all othe AddOns and te Problem still occurs.

I am confused, you said:

> I have found the Problem, it is the new Version 2.1.4 of Enigmail.

Meaning it was not disabled.

**Comment by gorhill** [comment]
The browser console (ctrl-shift-j) may show errors related to your issue.

**Comment by gorhill** [comment]
Well I just tried uBO 1.24.2 along with EnigMail 2.1.4 in Thunderbird 68.2.2 and all is working fine.

**Comment by gorhill** [comment]
The error message above occurs only when I launch Thunderbird. If I disable then re-enable uBO after launch, there is no error thrown, and all settings are restored. I consider this is a Thunderbird issue, for some reason `browser.storage.local` does not seem to function properly in Thunderbird at launch time.

**Comment by gorhill** [comment]
You were right, the issue occurs only when EnigMail is enabled.

**Comment by gorhill** [comment]
uBO is a pure webext, it does not use any API beyond what webext exposes. EnigMail still uses XPCOM components and as such is in a position to interfere negatively with the webext API, so the issue is most likely with EnigMail, especially that the issue started to occur with the last EnigMail update on December 13, yesterday.

**Comment by JPRuehmann** [comment]
OK.

And the:
Element Deleting Mode never worked
Element Picker Mode never worked

Thanks,

**Comment by JPRuehmann** [comment]
Would it be Possible, if there is no Way to implement it to disable the Buttons?

Thanks.

**Comment by gorhill** [comment]
These are Thunderbird issue, uBO is not fully functional on the root document in Thunderbird.

**Comment by JPRuehmann** [comment]
OK.
Now I have understand it.
Thanks again!

**Comment by gorhill** [comment]
> Last time I checked network requests originating from root documents are not dispatched to uBO

Actually this may have changed, as per uBO's logger, it seems uBO is blocking fine now. However content scripts do not appear to be injected and thus cosmetic filtering is still not available.

**Comment by pbrunschwig** [comment]
>... so the issue is most likely with Enigmail, especially that the issue started to occur with the last Enigmail update on December 13, yesterday.

Actually the error is also present with older versions of Enigmail. The fact that  JPRuehmann didn't notice it, doesn't mean it wasn't there. In fact I can reproduce the error with all Enigmail versions on TB 68.

I'm happy to fix Enigmail, but I would need to know from you guys what fails on your side. I'm not in a position to debug uBO.

**Comment by pbrunschwig** [comment]
> The error message above occurs only when I launch Thunderbird. If I disable then re-enable uBO after launch, there is no error thrown, and all settings are restored. I consider this is a Thunderbird issue, for some reason `browser.storage.local` does not seem to function properly in Thunderbird at launch time.

For a test, I modified the startup function in Enigmail such that the actual work is done asynchronously with a certain delay (like setTimeout()). Adding a delay of 200 ms, I can reproduce the error in uBO; adding a delay of 1000 ms, the error is gone. I believe therefore that this is a bug in Thunderbird. It seems that Thunderbird does a few things in parallel, and does not respect a required sequence. If a task takes longer than expected, then that's not handled properly.

I will file a bug with Thunderbird about this.

**Comment by gorhill** [comment]
The failure occurs in [`browser.storage.local`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get), when uBO tries to read user settings. I could make uBO recovers better from this unexpected error (to at least load default lists) but not being able to read back user settings through `browser.storage.local` is definitely not normal. Since you say the issue has always been there, then it's a Thunderbird issue.

**Comment by pbrunschwig** [comment]
Here is the Thunderbird bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1603950
