### ISSUE TITLE
"$elemhide" entries break the element picker, and using "$generichide" and "$specifichide" at the same time also breaks it

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#818]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`@@||supermicro.com^$elemhide` in *AdGuard Base*, which gets converted into two entries in uBO (`@@||supermicro.com^$specifichide` and `@@||supermicro.com^$generichide`), breaks the element picker on that site and makes the picker fail to show up at all.

Adding the two entries manually to *My Filters* also breaks it.

Adding `@@||supermicro.com^$specifichide,badfilter` and/or `@@||supermicro.com^$generichide,badfilter` to *My Filters* makes the picker work again.

Having now done a decent bit of research on this problem, I am aware that it's of course difficult to hide anything whatsoever when whichever lists out there insist on using `$elemhide` for a site; so in the event that it turns out to be too difficult to make the picker work under such circumstances, perhaps a warning about `$elemhide` being in effect could be added as a potential picker error message?

I believe that this report is **not** a duplicate of #731, as my explanation of the problem is much more clear-cut explained and hopefully far easier to reproduce.

### A specific URL where the issue occurs

`https://www.supermicro.com/about/sitemap/`

### Steps to Reproduce

There's multiple possible reproduction angles, so I'll write the easiest one:

1. Add `@@||supermicro.com^$elemhide` to *My Filters*.
2. Go to any `Supermicro` site page, e.g. `https://www.supermicro.com/about/sitemap/`.
3. Activate uBO's element picker mode.
4. See that the window fails to go dark, no elements are highlighted in pink, nothing happens when you click on anything, and the picker menu in the lower right fails to show up.
5. Add either `@@||supermicro.com^$elemhide,badfilter`, `@@||supermicro.com^$generichide,badfilter`, and/or `@@||supermicro.com^$specifichide,badfilter` to *My Filters*.
6. Try using the picker again, and see that it works this time around.

### Expected behavior:

The picker works like it always does.

### Actual behavior:

Picker fails to show up or to function in any conceivable way.

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Vivaldi 2.9.1705.41 64-bit
* Operating System and version: Windows 10 November 2019 Update

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/commit/23c4c80136ba4974a6444488ef8162ba75b0cb84#commitcomment-35180334

**Comment by DandelionSprout** [comment]
Ah, okay, so the matter has at least been adressed already.

It deserves mention that AdGuard Base seems to have quite a few more `$elemhide` entries than what EasyList has (Namely just above 50), and often for seemingly random sites, leading to potentially increased end-user confusion of the kind that made me write this issue report.

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3212
