### ISSUE TITLE
Means of multiple local or personal filter lists

### ISSUE THREAD

**Issue by Golutazem** [uBlockOrigin/uBlock-issues#819]
This feature request is for
support of multiple filter lists which are local or personal.
Presently, the user can have only a single list, MyList. In the event that a user wishes to maintain a separation between multiple lists, that becomes difficult. This would match features of some other ad blockers.

This feature could be implemented by allowing a user to subscribe to a local file as a filter list. Or My would allow multiple lists instead of only a single. Perhaps some code could be reused between maintaining multiple foreign lists and multiple My lists.

**Comment by gorhill** [comment]
You can already do this by simply hosting your lists somewhere; so, declined.

> some other ad blockers

Which?

**Comment by Golutazem** [comment]
Ad Block Latitude at least.
