### ISSUE TITLE
Strange behavior on mobile if dom.event.clipboardevents.enabled is false

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#820]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I copy & paste from and to My Filter with 2+ lines of code, new lines are inserted between all of original lines. If this copy is pasted to other normally functioning uBO's My Filter, line numbers are also inserted.

### A specific URL where the issue occurs

moz-extension://(uBO ID)/dashboard.html#1p-filters.html

### Steps to Reproduce

1. Create fresh Firefox profile w/ fresh uBO installed.
2. Create general.useragent.override value in about:config and set it to Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0 for example, IF you're not using real mobile version. Restart the browser.
3. Turn dom.event.clipboardevents.enabled to false.
4. Write 2+ rules to My Filter, then copy/cut & paste it.

### Expected behavior:

If I paste, the same lines should be reproduced as I cut/copied.

### Actual behavior:

Noted above.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox Mobile 68.3.0 and Desktop 71.0 only if UA is changed to mobile's one
* Operating System and version: Android 10 and Windows 10 (64 bit)

**Comment by Yuki2718** [comment]
On real mobile version, I observe some even more strange behavior:
1. pasted lines are duplicated, but all the duplicated lines are deleted with one push of backspace.
2. Using Gboard IME, SOMETIMES entered characters confuse its order; e.g. if I enter "abc" actual input becomes "bca" or such. I still don't figure the exact condition of the latter out, it may only happen on Japanese 12 key layout of Gboard despite I of course use alphanumeric input only.

**Comment by uBlock-user** [comment]
Enabling that setting tells Firefox to stop listening to ALL clipboard events(cut/copy/paste) including the ones coming the extension. uBO makes use of CodeMirror which sets up clipboard events, so this is the side effect of enbling this setting, not a uBO bug.

That's a blunt setting and shouldn't be used like this.

**Comment by Yuki2718** [comment]
Thank you for clarification. I'll open a new issue if I find the condition for another problem mentioned above.
