### ISSUE TITLE
Show all individual hostnames rather than just domain list, when clicking uBO icon

### ISSUE THREAD

**Issue by pgl** [uBlockOrigin/uBlock-issues#823]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Feature request: show all hostnames when clicking uBO icon in advanced mode, rather than just a list of hostnames.

The domains are helpful for general stats, but it would also be helpful sometimes to see all hostnames. Probably more useful for someone like me who's looking for new hostnames to check, but I think it could be of value to "advanced users" as well.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Enable "I am an advanced user" in settings
2. Click the uBO icon

### Expected behavior:

See a list of all individual hostnames resources have been loaded from.

### Actual behavior:

Only domains are shown.

![image](https://user-images.githubusercontent.com/1181139/71319650-599cbc00-24a1-11ea-8854-3fa5904ba3c9.png)

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Chrome latest
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Quick-guide:-popup-user-interface#the-overview-panel

Click "+all" in first row.

**Comment by pgl** [comment]
Oh my, all these years and I'd never noticed that. Thanks!
