### ISSUE TITLE
Add ublockorigin to thunderbird addons site

### ISSUE THREAD

**Issue by WPFilmmaker** [uBlockOrigin/uBlock-issues#824]
### Prerequisites
- [x ] I verified that this is not a filter issue
- [ x] This is not a support issue or a question
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- A search for 'thunderbird' shows 4 closed tickets none related to my issue
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
The issue could be split into two, a reminder to make ublockorigin fully compatible with thunderbird 60 and over, and a request to publish it on thunderbird addons page.

Right now ublock origin is not there, you can download the file manually from firefox addons, but if you already have it installed on FF it becomes a pain to download the file as right-clicking on it does not work. Furthermore last time I tried it there were incompatibilities with tb. 

Before TB switched to webextensions there was an old and unmaintained version of adblockplus, now it is gone too, so ublock woulkd be the only adblocker available for tb.

If you are wondering what's the point of such tool in tb, it is easy: tb is used also as rss feeder, and it is very useful to clean up the interface of the page you download as feed. Furthermore if you disable js in tb (as you should) the chances to end up with broken parts which would be nice to remove with ublock increase.

### A specific URL where the issue occurs
//

### Steps to Reproduce
Go on https://addons.thunderbird.net/en-US/thunderbird/ and search for ublock, no results.

### Expected behavior:
Ublock is on https://addons.thunderbird.net/en-US/thunderbird/ and from there it can be installed.

### Actual behavior:
Ublock is not present on https://addons.thunderbird.net/en-US/thunderbird/.

### Your environment
* uBlock Origin version: 1.24.2
* Browser Name and version: Thunderbird 68.2.2 (64-bit)
* Operating System and version: Lubuntu 18.04

**Comment by gwarser** [comment]
I don't think it will be good to add it in current state.

**Comment by WPFilmmaker** [comment]
@gwarser Yes indeed, that's why I suggested first to polish up on TB and then release it, hopefully this will be kept open til it happens? Otherwise people might just request it again.

**Comment by krystian3w** [comment]
How will he be able to filter files/text/nodes in emails, not before.

**Comment by WPFilmmaker** [comment]
@krystian3w afaik ublock only works for feed rss that are displayed as webpages not text only. I don't know if it could be used to block elements in email too.

**Comment by GETandSELECT** [comment]
> I don't think it will be good to add it in current state.

what you mean with that? Can you put a few lines about the issues?

**Comment by WPFilmmaker** [comment]
@GETandSELECT they probably mean that as it is not fully functional, people would just review it poorly, once it works fine it can be added :)

**Comment by Altonss** [comment]
Any update on bringing the ublockorigin extension to the thunderbird addons site?

**Comment by krystian3w** [comment]
IMO almost 0 change in Moz://a API to filter mail by network and generic cosmetic filters.

**Comment by Altonss** [comment]
> But uBo works if enforce open webpage as new tab.

This yes, and therefor it works also for rss. It is mentioned here in an official Thunderbird tutorial https://tilvids.com/w/sDr1H96FsdQUHVSEKQcQM3.

**Comment by gwarser** [comment]
https://addons.thunderbird.net/pl/thunderbird/addon/ublock-origin/

**Comment by iam-py-test** [comment]
Shouldn't the description note that uBo only filters the feeds (https://github.com/uBlockOrigin/uBlock-issues/issues/2652)?

**Comment by in-plaintext** [comment]
gorhill:

> uBO doesn't work on emails, just feeds.

Does uBO work within the Thunderbird's **internal web browser**? 

Using the browser is now mandatory to some degree due to [email providers such as Microsoft's Outlook  moving to "modern" authentication](https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d).
