### ISSUE TITLE
It Appears that Facebook's Pixel Is Being Proxied by Shogun/Getshogun or Shopify

### ISSUE THREAD

**Issue by ilikenwf** [uBlockOrigin/uBlock-issues#826]
I visited pedalcommander.com, and later had a facebook ad for the device.

I have EasyPrivacy and Fanboy's stuff enabled, and since I'm using container tabs I find it very disturbing that I'm seeing ads for this site when I haven't even entered any info into it anywhere.

Unfortunately, blocking the cdn, cloudfront server, and getshogun.com domains break pedal commander's site.

Whatever the case I'm very perturbed, and while I have only done a cursory inspection of the javascript, am don't think that any direct or  CNAME requests are going out from this page to Facebook.

**Comment by uBlock-user** [comment]
how is this a uBlock Origin issue ?
