### ISSUE TITLE
Configuration changes are reverted after Firefox restart

### ISSUE THREAD

**Issue by shred** [uBlockOrigin/uBlock-issues#827]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I change settings in uBlock Origin, the changes are reverted when Firefox is started the next time. I have tried it with a fresh `.mozilla` directory, and uBlock Origin as the only add-on, and could always reproduce this behavior.

### A specific URL where the issue occurs

https://www.heise.de

The issue is not URL specific, though. Other changes are reverted as well.

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

This is an example of how the issue can be reproduced:

1. Make sure expert mode is enabled in uBlock Origin
2. Open https://www.heise.de
3. Open the uBlock Origin menu, locate the cleverpush.com row on the left side, then block it globally by pressing "-" on the left column. Both colums of that row should appear in red now.
4. Make the change permanent by pressing the "padlock" button.
5. Close Firefox, make sure the process is terminated.
6. Start Firefox again
7. Open https://www.heise.de
8. Open the uBlock Origin menu and locate the cleverpush.com entry.

When testing in a fresh environment, please perform all these steps twice (e.g. by blocking a URL, then trying to unblock it again after restarting Firefox). It seems that at the first time, the configurations are saved successfully, but then Firefox falls back to these settings after every restart.

### Expected behavior:

After a restart of Firefox, cleverpush.com is still blocked, and the respective columns are still red.

### Actual behavior:

After a restart of Firefox, cleverpush.com is unblocked, the respective columns appears in grey again.

### Your environment

* uBlock Origin version: 1.24.2 (latest on addons.mozilla.org as of today)
* Browser Name and version: Firefox 71.0 (64 bit)
* Operating System and version: Fedora Linux 31

**Comment by uBlock-user** [comment]
Browse to https://firefox-storage-test.glitch.me/ and post results. You can try out few suggestions mentioned at https://old.reddit.com/r/uBlockOrigin/comments/d4zlfi/ublock_on_firefox_preventing_pages_from_loading/f0i4nss/

**Comment by shred** [comment]
Thank you for the links. After reinstalling Firefox, I couldn't reproduce the issue any more.
