### ISSUE TITLE
no update new version

### ISSUE THREAD

**Issue by lukjan32** [uBlockOrigin/uBlock-issues#828]
no update chrome and opera.

**Comment by uBlock-user** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/ea27zl/ubo_for_brave/fao0xk1/

**Comment by lukjan32** [comment]
ok, thank.

**Comment by gorhill** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/dy6cdj/ublock_origin_1240_is_out/fclewc8/
