### ISSUE TITLE
Random Domain .. Register my filter & 

### ISSUE THREAD

**Issue by oklokl** [uBlockOrigin/uBlock-issues#829]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
Q. For random domains
```
https://manamoa22.net/
https://manamoa21.net/
https://manamoa8.net/
```
manamoa(random).net
!manamoa22.net###hd_pops_3
My filter
How do I register a filter?

!manamoa???.net###hd_pops_3

And I suggest
I want to use the cloud as my personal mail.
:) Thank you.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment]
`manamoa22.net,manamoa21.net,manamoa8.net###hd_pops_3 `

like that.

**Comment by gwarser** [comment]
For example:

    net###hd_pops_3

This topic was raised recently on Reddit: https://www.reddit.com/r/uBlockOrigin/comments/ecg0kw/how_to_block_dinamically_third_domain_level/

Bunch of text under "Expected behavior" is not really good bug report / feature request.
