### ISSUE TITLE
Element-picker does not come up on some pages

### ISSUE THREAD

**Issue by UnitedMarsupials** [uBlockOrigin/uBlock-issues#83]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element-picker does not come up on some pages

### A specific URL where the issue occurs

Any of thehill.com's pages lately, for example [this one](http://thehill.com/blogs/in-the-know/393598-tom-arnold-cohen-and-i-are-teaming-up-to-take-trump-down).

### Steps to Reproduce

1. Open the page in Firefox
2. Attempt to bring up uBlock's element-picker through the menu on the tool bar
3. Attempt to bring uBlock's element-picker through the context menu

### Expected behavior:

I expected my cursor to change to "cross" so I can pick the element I want hidden

### Actual behavior:

Nothing happened.

### Your environment

* uBlock Origin version: uBlock Origin v1.16.10
* Browser Name and version: Firefox 60.0.2 (64 bit)
* Operating System and version: Windows 10

**Comment by gwarser** [comment]
Any chance you have cosmetic filtering disabled on that page? https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

**Comment by uBlock-user** [comment]
Works fine on `thehill.com`

**Comment by uBlock-user** [comment]
If you made any changes to `about:config` then undo them or undo all custom firefox settings to default and see it works again.

**Comment by UnitedMarsupials** [comment]
@gwarser , you are right! How embarrassing...

So, this has nothing to do with a particular site, just an interface-bug:

- either the element-picker should be completely disabled in the GUI, when the cosmetic filtering is disabled
- or, the element-picker should still come up to allow adding an element for blocking, even if no blocking takes place until cosmetic filtering is re-enabled

You, probably, already have an "issue" for this problem, don't you?

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/gorhill/uBlock/issues/3212
