### ISSUE TITLE
Element picker unable to pick a certain element on YT player

### ISSUE THREAD

**Issue by WPFilmmaker** [uBlockOrigin/uBlock-issues#830]
### Prerequisites
- [x ] I verified that this is not a filter issue
- [ x] This is not a support issue or a question
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
I checked and it does not seem to be duplicate of anything
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Element picker is unable to pick the square channels use and which is displayed on the player of youtube.

In most of cases the picker is able to select the square, in others it appears to be lower and it is unable to select it, you end up selecting the options gear or the video bar. Sometimes after a few attempts you find a good spot and you can block it, but often if it is in the lower position you can't block it.

I never experienced this with adblockplus, so either abp picker works better or they introduced something new.

### A specific URL where the issue occurs
https://www.youtube.com/watch?v=yyIWj6HmkDQ

### Steps to Reproduce
Go on a yt channel which has the channel logo in the shape of a square and try to select it with the picker to remove it. Note that in most of channels this works, some have a lower position (like the one i linked) and the picker does not work.

### Expected behavior:
I am able to select the object and hide it.

### Actual behavior:
The picker is unable to pick such square.

### Your environment
* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 71.0 (64-bit)
* Operating System and version: Lubuntu 18.04

**Comment by gwarser** [comment]
Works fine when video is  paused.

**Comment by gorhill** [comment]
The browser's own developer tool picker has the same issue. Given this, I will not spend time on this, especially that the workaround is simple enough.

**Comment by uBlock-user** [comment]
I don't see any squares whatsoever, blocking endscreen/annotations blocks it ???

```
||youtube.com/*/endscreen.js$script,1p
||youtube.com/*/annotations_module.js$script,1p
```

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/71519589-7fb6c780-28b8-11ea-8bc5-e69ba7234fd3.png)

**Comment by uBlock-user** [comment]
Yep, that's an annotation. Either disable it via the player's setting menu or block the javascript itself --

`||youtube.com/*/annotations_module.js$script,1p`
