### ISSUE TITLE
Exception rule doesn't work

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#831]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
From this:
https://github.com/uBlockOrigin/uAssets/issues/6748
An exception rule `@@||clients6.google.com/drive/v2internal/viewerimpressions` or anything similar doesn't work at all, the request is still blocked despite the rule in EasyList ofc doesn't have $important modifier.

### A specific URL where the issue occurs

https://drive.google.com/drive/folders/1gV6kYi-qP0lUIxtVcklMrusd8p2q9d08

### Steps to Reproduce

1. Install uBO on fresh Firefox.
2. Go to the site w/ the exception rule.
3. The request will still be blocked.

### Expected behavior:

The request should not be blocked if exception rule is made, unless $important is used in the block rule.

### Actual behavior:

Noted above.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 71.0
* Operating System and version: Windows 10 Home 1909 x64

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/18a92c968b326560c6d793e5e2a49513.png)

**Comment by Yuki2718** [comment]
For some reason the exception works now on the same Firefox profile. I've created another really fresh profile, and again the exception works. So it appears there is a rare condition that an exception doesn't immediately work (needless to say, 'Apply changes' was pushed).

**Comment by krystian3w** [comment]
@uBlock-user try activate `block CSP reports` and open:
https://drive.google.com/drive/folders/1gV6kYi-qP0lUIxtVcklMrusd8p2q9d08
and try download file.

For my block CSP generate error and extend waiting for start download.

![obraz](https://user-images.githubusercontent.com/35370833/71529033-097b8a80-28e3-11ea-885e-9d555fcf3521.png) |
--- |

---

And I would like to ask if the `CSP block` has been deactivated forcibly/forced as someone in the older version of the add-on was active?

**Comment by gorhill** [comment]
> The request won't be blocked.

That is the expected behavior if you created an exception...

> it appears there is a rare condition that an exception doesn't immediately work

Please, let's assume there is an issue if it's not demonstrated there is one. From my side, I see a report with no mention to the logger, so the best assumption is that you misdiagnose.

**Comment by Yuki2718** [comment]
> 
> 
> > The request won't be blocked.
> 
> That is the expected behavior if you created an exception...
> 
> > it appears there is a rare condition that an exception doesn't immediately work
> 
> Please, let's not assume there is an issue if it's not demonstrated there is one. From my side, I see a report with no mention to the logger, so the best assumption is that you misdiagnose.

Sorry, that was a bad typo. I believe it was not misdiagnose, but will investigate.

**Comment by Yuki2718** [comment]
I can't reproduce at least now, so close this unless it happens again. Sorry for the fuss.

**Comment by krystian3w** [comment]
I'll check with the ABP as soon as they close the wrong filter report in `uAssets`.

**Comment by uBlock-user** [comment]
> For my block CSP generate error and extend waiting for start download.

Nothing to do with CSP reports, this is a compatibility issue with Firefox. Try with Chrome and it won't happen.
