### ISSUE TITLE
In the Whitelist i miss a Button to delete items from it!! 

### ISSUE THREAD

**Issue by rogerberglen** [uBlockOrigin/uBlock-issues#837]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In the Whitelist i have made a wrong Entry! I will delete this from the Whitelist. Unfortunally i can't found a Button that i can delete Entry's from the Whitelist!!

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: Where can i found this Information?
* Browser Name and version: Avast Security Browser 77.2.2154.121 (Offizieller Build) (64-Bit)
* Operating System and version: Win7 64-Bit

**Comment by rogerberglen** [comment]
In the Whitelist a can Add Entrys! But unfortunally i can't remove Entrys from the Whitelist!!!
There is no Button or Command "Remove" Displays on the Windoiw from the Whitelist

**Comment by gorhill** [comment]
It's a text editor, just select and delete the entry(ies) you want gone, then click _"Apply changes"_.
