### ISSUE TITLE
Possible manifest correction

### ISSUE THREAD

**Issue by setyb** [uBlockOrigin/uBlock-issues#840]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The manifest.json file in uBO v1.24.2 contains a statement that _may_ be erroneous.

```
 "content_scripts": [
    {
      "all_frames": true,
      "js": [
        "/js/vapi.js",
        "/js/vapi-client.js",
        "/js/contentscript.js"
      ],
      "matches": [
        "http://*/*",
        "https://*/*",
        "file://*/*"
      ],
      "run_at": "document_start"
    },
```

According to https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Match_patterns it appears possible that `file://*/*` should actually be `file:///*`.

I'm not sure about which is best, but another prominent extension is using `file:///*` and not `file://*/*`.  See https://github.com/bitwarden/browser/blob/master/src/manifest.json

What do you think?

**Comment by uBlock-user** [comment]
> it appears possible that file://*/* should actually be file:///*.

Where does it say that ?
 
file://*/* literally means match all file URLs.

file:///* literally means match all urls **AFTER** ///

**Comment by gorhill** [comment]
The issue tracker is for _proven_ issues, not speculated one -- otherwise it's a question issue to be addressed at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/). Importing `file:` URLs work fine in Chromium.

**Comment by gwarser** [comment]
https://en.wikipedia.org/wiki/File_URI_scheme

First `*` is for hostname, `localhost` if missing. Something other than `localhost` is rarely used, so it may be hardcoded as three slashes.
