### ISSUE TITLE
Publish uBlock Origin officially on the Microsoft Edge Addons store (feature request)

### ISSUE THREAD

**Issue by superusercode** [uBlockOrigin/uBlock-issues#843]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Microsoft has opened up the [extension publication process](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension) for the new Microsoft Edge. The browser will be launching in stable within the next two weeks via an update distributed through Windows Update. Although users will be able to opt-in to sideloaded Chrome Web Store extensions, I believe Google's delay on manifest v2 using extensions (as documented in <https://github.com/ipfs-shipyard/ipfs-companion/issues/808>, especially those still using webrequest justifies looking towards other extension stores. The Edge team comes off as [supportive](https://www.reddit.com/r/IAmA/comments/c094uf/hi_reddit_were_the_team_behind_microsoft_edge_and/er34xbw?utm_source=share&utm_medium=web2x) towards adblockers from what I can tell.

**Comment by llacb47** [comment]
Nano Adblocker is already there FYI: https://microsoftedge.microsoft.com/addons/detail/epbkapkgcmdmfpogenoebpdeibmfinpf

See https://github.com/NanoAdblocker/NanoCore/issues/253

**Comment by uBlock-user** [comment]
https://microsoftedge.microsoft.com/insider-addons/detail/odfafepnkmbhccpbejgmiehpchacaeak

**Comment by superusercode** [comment]
@uBlock-user that version is on 1.23.0 and is stuck in place. It used to be even further behind back on old edge. I think if it should exist without official maintenance then it should at least have an unofficial tag or an outright name change.

**Comment by uBlock-user** [comment]
@superusercode Edge builds are pulled from Chrome Store, so whatever version is on CWS, it will be the same version on Edge store. -- https://github.com/nikrolls/uBlock-Edge/issues/130
