### ISSUE TITLE
Block script from YouTube fullscreen

### ISSUE THREAD

**Issue by FMA1986** [uBlockOrigin/uBlock-issues#844]
Hi! When I use uBlock Origin,on a YouTube fullscreen i can't block this! How to block,when uBlock Origin is gone in this issue?
![ublockyoutubefullscreen](https://user-images.githubusercontent.com/59610444/71898916-cf1fb200-315a-11ea-878f-15c1022f1888.PNG)

Here's the link from this issue: https://www.youtube.com/watch?v=ihDvD6wPFr4

**Comment by uBlock-user** [comment]
Support issues and questions are handled at /r/uBlockOrigin.
