### ISSUE TITLE
How to remove this bar to the left of uBlock Origin?

### ISSUE THREAD

**Issue by FMA1986** [uBlockOrigin/uBlock-issues#845]
![ublockapp](https://user-images.githubusercontent.com/59610444/71899518-338f4100-315c-11ea-8dbd-a2e4403d72a3.PNG)

**Comment by uBlock-user** [comment]
> Support issues and questions are handled at /r/uBlockOrigin.

**Comment by llacb47** [comment]
Click the 3rd icon below the big blue power button.
