### ISSUE TITLE
Firefox input lag in Google Docs

### ISSUE THREAD

**Issue by L33Tech** [uBlockOrigin/uBlock-issues#846]
### URL(s) where the issue occurs

`Creating a google document with uBlock - Privacy and EasyPrivacy filters on`
May only affect Firefox

### Describe the issue

Massive "input lag" (keypress/typing takes forever to appear) and with every one a blocked/redirected request is shown in the logger.
Issue is instantly resolved by disabling uBlock Origin.

### Versions
EDIT: Affects release Firefox as well.
- Browser/version: Firefox Beta
- uBlock Origin version: uBlock Origin v1.24.2

### Settings

Extra blocklists have been added but don't affect this site in logger.

### Notes

Seems to be related to https://github.com/uBlockOrigin/uAssets/pull/5997
As this is the issue that's hitting the logger. Same/similar issue seems to be present in EasyPrivacy.

Please let me know if any more information is needed.

**Comment by gwarser** [comment]
>and with every one a blocked/redirected request is shown in the logger.

What exactly you see in the logger? I see tons of `https://docs.google.com/document/u/0/d/.../bind...`  requests, and only few `.../logImpressions...` blocked.

**Comment by L33Tech** [comment]
![image](https://user-images.githubusercontent.com/36166244/72016971-c00c3300-3232-11ea-9586-7ff565458c93.png)

Every time I click around or type a character another logger entry goes through and it lags. This happens with the logger closed as well.

**Comment by gwarser** [comment]
Did you tried with only uBO / no other extensions?

Record performance profile https://profiler.firefox.com/

**Comment by gorhill** [comment]
> This happens with the logger closed as well.

Does this happen if you do not open the logger at all?

**Comment by gorhill** [comment]
> Record performance profile https://profiler.firefox.com/

Providing this profile data is the only way to validate whether this is a uBO issue.
