### ISSUE TITLE
"0" prefixes are currently not accepted as valid hosts entries

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#847]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, `0 example.org` does not block the site, whereas `::1 example.org`, `127.0.0.1 example.org` and `0.0.0.0 example.org` does.

This is believed to affect the following lists:
* https://raw.githubusercontent.com/TakoYachty/Gift-Card-Killer/master/Untrusted%20Hosts%20Blocker.txt
* https://raw.githubusercontent.com/arcetera/Minimal-Hosts-Blocker/master/etc/MinimalHostsBlocker/minimalhosts
* https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHostsCB/etc/MinimalHostsBlocker/minimalhosts
* https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

This is to a certain extent related to #800, but does not seem to me to be a duplicate of it. I'm able to get `:: example.org` to work in Nano but not in uBO, whereas `0 example.org` doesn't work in either of them.

### A specific URL where the issue occurs

Depends on the site you'd want to block. For the examples above it's `example.org`.

### Steps to Reproduce

1. Paste `0 example.org` in My Filters.
2. Visit `example.org`.
3. See that no page warnings show up, nor are the (few) on-site elements blocked.

### Expected behavior:

A page warning shows up.

### Actual behavior:

The site loads normally.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Vivaldi 2.10.1745.23 64-bit
* Operating System and version: Windows 10 November 2019 Update

**Comment by gorhill** [comment]
I had to lookup documentation to find out whether this is a valid representation; it is as per [Address representations](https://en.wikipedia.org/wiki/IPv4#Address_representations):

> When fewer than four numbers are specified in the address in dotted notation, the last value is treated as an integer of as many bytes as are required to fill out the address to four octets.
