### ISSUE TITLE
Change uses of uBlock to uBlock Origin in uBO documentation

### ISSUE THREAD

**Issue by jrw** [uBlockOrigin/uBlock-issues#849]
To avoid confusion for new users.
Starting with the about:addons page (Firefox) where I noticed mention of a "bare" uBlock.

**Comment by gorhill** [comment]
This is too much of a unspecific, generic issue -- it is will be impossible to ever close. The issue tracker should be kepy only for specific, actionable issues which can be closed.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/blob/eb7088eb40f793b2d61a45289cbf6ff0eb0c2684/dist/description/description-en.txt

That's the page he's talking about.

**Comment by gwarser** [comment]
I can append few "₀" to the "uBlock" in the wiki. I don't know what to do with "uBlock's".

Page titles must not be modified - this breaks links.

@jrw you can help, you can modify wiki pages in [draft version](https://github.com/uBlockOrigin/uBlock-issues/wiki)

**Comment by gorhill** [comment]
I prefer "uBO" to "uBlock0". We should keep fixing instances over time in an opportunistic way just as we _always_ have done, no issue needed for this.

In the end, a lot of people out there still use "uBlock" to refer to "uBlock Origin", and we have no control over this. I disagree that people visiting the "uBlock Origin" wiki are likely confused -- rather the opposite.

**Comment by jrw** [comment]
You may be right.  I just wanted to point it out since it was right in my face as literally the very first thing I noticed after installing uBO on Firefox (I went to the "Manage" page for the Add-On, and there it was, under Details).

    On Thursday, January 9, 2020, 10:19:51 AM EST, Raymond Hill <notifications@github.com> wrote:  
 
 
I prefer "uBO" to "uBlock0". We should keep fixing instances over time in an opportunistic way just as we always have done, no issue needed for this.

In the end, a lot of people out there still use "uBlock" to refer to "uBlock Origin", and we have no control over this. I disagree that people visiting the "uBlock Origin" wiki are likely confused -- rather the opposite.

**Comment by uBlock-user** [comment]
uBlock Origin is also called uBlock or uBO in short in lots of places, so nothing's wrong with that either. You can change it for the sake of argument, but to me this is acceptable.
