### ISSUE TITLE
filter list - some built-in uBo filters moved to other categories

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uBlock-issues#850]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
I was updating the filter lists, picking which one at a time to update. Then I noticed an update error, and "update now" became clickable. I don't remember if I clicked on it, or if I was about to, but the visible list of built-in uB filters suddenly only showed 5 visible items instead of 6 (I saw it happening).
Now the section contains only 5 lists instead of 7. One list has moved to "annoyances" and the other one to "Custom".
I have restarted chrome, but the problem is still there. I have not tried something else to fix it (restore backup or reset).

I have done a backup to compare with a backup done yesterday. The only differences are in "externalLists" where `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/experimental.txt` has been added, and in "selectedFilterLists" where "ublock-experimental" has disappeared, replaced by the same url.

![ubo-filter-list](https://user-images.githubusercontent.com/40043075/72107737-42c7e780-3332-11ea-9e09-9497e57a6e97.gif)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: chrome
* Operating System and version: windows 7

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/commit/0ae1e9b1fea8c1197ae09afef93b082ea1f8062b

**Comment by gwarser** [comment]
Not a bug: https://github.com/uBlockOrigin/uAssets/issues/6803

**Comment by Procyon-b** [comment]
OK, sorry for the report.
Before the bug report I did a filters' update in another profile without the same result. But did one now in a third profile, and could reproduce the behavior.

**Comment by MS-PC** [comment]
I think that "uBlock filters – Annoyances" should go back to the "Built-in" section, because if we base on the fact that "uBlock filters – Annoyances" has been moved to the "Annoyances" section, we should also move "uBlock filters – Privacy" to the "Privacy" section.

@gorhill
My suggestion would be to move "uBlock filters – Annoyances" back to the "Built-in" section, as I think it is the right section, taking into account that the other sections contain filter lists of third-parties.

**Comment by Yuki2718** [comment]
> 
> 
> I think that "uBlock filters – Annoyances" should go back to the "Built-in" section, because if we base on the fact that "uBlock filters – Annoyances" has been moved to the "Annoyances" section, we should also move "uBlock filters – Privacy" to the "Privacy" section.
> 
> @gorhill
> My suggestion would be to move "uBlock filters – Annoyances" back to the "Built-in" section, as I think it is the right section, taking into account that the other sections contain filter lists of third-parties.

I tend to agree, personally. I was a bit confused by this change.
