### ISSUE TITLE
Can't control specificity in element picker with Firefox for Android

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#851]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On PC I can easily switch selector on the Picker by holding Ctrl (usually id to class). But on mobile there's no Ctrl unless you plug keyboard on (or some IME may have Ctrl). Even worse, more often than not those alternative selector (class names) are not fully visible on mobile as seen in SS attached. As a result, I'm forced to view the page source if it works or use DOM inspector just to change selector. This inconvenience can be solved e.g. if Ctrl-click text on the Picker is clickable and after clicking it every entry is chosen w/ Ctrl by default. I guess this change meets the guideline expressed in
https://github.com/gorhill/uBlock/issues/1890#issuecomment-343737201
except for "majority of user" part, but I have no idea about e.g. javascript code.

![SS](https://user-images.githubusercontent.com/58900598/72200898-09a68900-3492-11ea-86f6-d5050390a5a8.png)

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/issues

### Steps to Reproduce

1. Launch the Picker on Firefox for Android and choose any element which has id and class as selector.
2. You can't switch the selector.

### Expected behavior:

Noted above.

### Actual behavior:

Noted above.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox for Android 68.4.1
* Operating System and version: Android 10

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by Yuki2718** [comment]
Much appreciated!
