### ISSUE TITLE
Official Website to Address Confusion over uBlock vs uBlock Origin

### ISSUE THREAD

**Issue by bhadaway** [uBlockOrigin/uBlock-issues#852]
Hi Raymond,

Thank you very much for your beautiful work on uBlock and uMatrix.

I use them; I recommend them.

Unfortunately, I, like many others, have been confused by the _other_ uBlock, resulting in linking to, installing, and recommending the wrong one a handful of times now, mainly from Googling "ublock" and of course, ultimately finding https://ublock.org/, which is the wrong one.

I know you've done your best to warn people and set the record straight:

https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org

But, it just bothers me that people, whether searching for "ublock" or even having the wherewithal to specifically search for "ublock origin" _still_ are finding the wrong one high in the SERPs.

To help lessen the confusion of this situation, I went ahead and created a simple little _unofficial_ site here as a contribution to the project:

https://ublocko.org/

And with your blessing, the _official_ one. If so, let me know, and I'll make a repo for it and give you commit access.

This way, there's a more simple, prominent, and centralized location containing important links.

Thank you!

**Comment by uBlock-user** [comment]
> And with your blessing, the official one.

That will violate  the Privacy-policy of having no home-server -- https://github.com/gorhill/uBlock/wiki/Privacy-policy

**Comment by bhadaway** [comment]
Ah, _that's_ why there's no official site. Thank you.

Okay, I've made it much more clear on my contribution site now, and hopefully it will increase visibility for the casual user coming from Google that would never even come to GitHub or otherwise get the memo about the confusion between the two uBlocks.

**Comment by mapx-** [comment]
getting support here: https://www.reddit.com/r/uBlockOrigin/

**Comment by bhadaway** [comment]
Thanks :)
