### ISSUE TITLE
"uBlock filters --- Annoyances" has been moved to the "Annoyances" section

### ISSUE THREAD

**Issue by happysurf** [uBlockOrigin/uBlock-issues#856]
Developer filters was perfect all together on top of the Filter List page in a Built-in section.

With same concept also the the Privacy list must be move in the "Privacy" section, the Resource abuse list in a new section like "Security" for example,  and so on.

This creates confusion for the user in my modest opinion.

**Comment by gorhill** [comment]
The move was decided long ago, I just executed it. That list is not selected by default, and hence out of view if someone is interested to enabled annoyance lists. In its new location, it becomes visible when someone expand the _"Annoyances"_ section. Declined.
