### ISSUE TITLE
Request: sideDragRight/Left .CSS elements should be completely blocked/removed

### ISSUE THREAD

**Issue by B3bomber** [uBlockOrigin/uBlock-issues#86]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

This will not show up in the element picker because it is hidden by default. Trying to click+drag stuff with the element picker does not allow selecting these elements to block them.
Description of the element:

#sideDragRight{
    display: none;
    position: fixed;
    height: 100%;
    width:200px;
    right: -205px;
    top:0;
    z-index: 9999999999;
    border-left: 1px #ccc solid;
    overflow: hidden;
    background-color:rgba(255,255,255,0.8);
    opacity: 0.9;
}
#sideDragLeft{
    display: none;
    position: fixed;
    height: 100%;
    width:200px;
    left: -205px;
    top:0;
    z-index: 9999999999;
    border-right: 1px #ccc solid;
    overflow: hidden;
    background-color:rgba(255,255,255,0.8);
    opacity: 0.9;
}

[Description of the bug or feature]

Many sites have this default .css shit in it. 1 example is Kongregate.com.
What it does: You probably have some experience, or heard of those who did, with that utter shit feature added since Windows 8 referred to as the Charms Bar (I'm certain there's a much better description but it's too long to post). Well, someone took it upon themselves to add a very similar feature when click+dragging anything on the web page and it just happens to come close to either left or fight of it and it pops up a bunch of shit links I have no desire to use. Browser developers have taken considerable steps to make sure users can't edit these lovely global rule .css.

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Have javascript enabled, disabling it disables the script controls allowing it to popup.
Highlight some text.
2. [Second Step]
With it highlighted, click and drag it left or right of the page/browser window.
3. [and so on...]
Gain burning desire to break things.

### Expected behavior:

[What you expected to happen]
Not a thing. I sometimes click+drag while using the scroll bar.

### Actual behavior:

[What actually happened]
Annoying popups. Me wanting to smash skulls. Lot's of research on how to get rid of it (no solution).

### Your environment

* uBlock Origin version:
uBlock Origin v1.13.8, this does not matter. It shows up with or without uBlock.
* Browser Name and version:
Tested for its existence on: Chrome 31.1.0.0 (portable), Chromium	52.0.2743.120 (Developer Build) (64-bit), Comodo IceDragon 52.0.0.4 (32-bit) (Portable Edition) [Firefox fork].
* Operating System and version:
Windows 7 x64

**Comment by uBlock-user** [comment]
If the elements don't exist, they will not appear in the element picker, your request hardly makes any sense.

**Comment by B3bomber** [comment]
Ok, I'll make a screenshot because you do not understand.

What it looks like:
https://files.catbox.moe/cghwfd.png

What it looks like when click and drag is used on left side:
https://files.catbox.moe/anqlq3.png

What it looks like when click and drag is used on right side:
https://files.catbox.moe/grtof5.png

I want that shit blocked. It should not be there but it's part of default .css that are not editable by users. Again, ublock element picker cant choose the element because it auto hides if I let go of the highlighted stuff I dragged. It has to be manually added and I do not have the first clue how.

**Comment by uBlock-user** [comment]
> It should not be there but it's part of default .css

What default .css ? Those element don't exist on this page or anywhere on github. Neither there's such csss which inserts those elements in Chromium.

Also those screenshots display you using Firefox or a fork of it instead of Chromium, The only way you could insert it on Firefox would be to insert it in userChrome.css. Did you make any changes to that file ?

**Comment by B3bomber** [comment]
I have tested for this in multiple browsers, it is present in all of them (some have no extensions). I think it might be how an ISP DNS server does their re-routing thing for bad URLs for this behavior. The thing is, I should still be able to remove/block those elements with ublock. It would be a good idea to not allow such elements to show up regardless of DNS options (I avoid my ISPs own DNS for the suggested invalid URL behavior and Google's DNS). ublock has that ability to filter this and whichever DNS is doing it is not doing so maliciously, but it is definitely annoying.

The DNS list I have is from a tool released by Gibson research center that gauges DNS performance and Google usually does not rank better than my other options. I find Google just as questionable as many others anyway. I can list them if it helps develop research into who gets annoying element injection removed.

userChrome.css only has entries in it to remove some options on the right click menu and I had to create that because none existed for it (including the sub folder that holds it).

**Comment by gwarser** [comment]
Add this to _My filters_
###sideDragRight
###sideDragLeft

If this code is injected somewhere in network, you should have modified https certificate, can you check this

![image](https://user-images.githubusercontent.com/886325/41818322-a886b5ee-77ac-11e8-9468-7ef5482c7774.png)

**Comment by gorhill** [comment]
>  I should still be able to remove/block those elements with ublock

The element picker can only pick what is visible and has a size. Use the DOM inspector if you want to see the whole DOM. Alternatively, craft the filter manually in "My filters" pane according to what you observe in the DOM.

**Comment by B3bomber** [comment]
I'll give that stuff a try. I forgot to note one important thing: I did mention this does not happen on all websites. The ones it does happen on tend to be using a CDN.

**Comment by gorhill** [comment]
> SSL cert looks the same and is valid according to digicert

So this means an extension is injecting the CSS, you need to find out which one. And from the look of it, it is a legacy extension, as it uses `resource://` assets.

**Comment by B3bomber** [comment]
I tested this on a browser with no extensions installed and it still appears. The .CSS is not always the same name.

**Comment by gorhill** [comment]
A bit of Googling says it's related to "Comodo Drag&Drop Service".

**Comment by B3bomber** [comment]
Interesting, I'll see if I somehow missed any parts of that (they do give info on removing such things). Oddly my searches did not turn up that in the results.

**Comment by uBlock-user** [comment]
Test it on the latest stable version of Chrome/Chromium, that could confirm whether the issue lies with the fork.

**Comment by B3bomber** [comment]
At this point I'm just glad it stopped after removing that folder it was in (this method they used made it so it did not show up under addons/extensions). I can run more tests later on since the folder is sitting in the recycle bin with intact files so I may be able to check the code in it. I spent a lot of time checking various sites both by highlight+drag and inspect html code with and without it reacting.

For now though I want to get some sleep.
