### ISSUE TITLE
Use "no-large-media: www.website.org false" - for sub-pages with wildcard?

### ISSUE THREAD

**Issue by Legalien** [uBlockOrigin/uBlock-issues#870]
So I use this code in uBlock in My Rules in order to disable the blocking of large media for a certain webpage:

no-large-media: www.website.org false

But I need to be able to disable that setting for a sub-page, with a wildcard. For example:

no-large-media: www.website.org/some-page.php?text=* false

Is this possible?

And if it's not, how much work would it be to edit the extension to make it possible? Would this require a huge rework on the extension, or would a few simple changes make it work?

Thanks :)

**Comment by gorhill** [comment]
> Is this possible?

No.

> Would this require a huge rework on the extension

Yes.
