### ISSUE TITLE
Fanboy's filters are not reliable

### ISSUE THREAD

**Issue by Marco-Sulla** [uBlockOrigin/uBlock-issues#871]
I just had some problems in the past with Fanboy's filters. He added to its filter a potentially useful JS plugin, only if because it could be used as annoying popup. That filter break the site I was surfing and I kindly asked Fanboy to remove the filter. It refused and I simply removed the filter on my machine.

Now I tried to see this page:
https://www.blmagazine.it/omocausto-silenzio-assordante-triangoli-rosa/?fbclid=IwAR3F17s-PpBE_54VUrdux0gEfbFfecFt9LeoiUDJftgXViLUxV-mcpW02Rk

The layout was completely messed up. Disabling the Fanboy's filters, the page is well displayed.

I know, Fanboy's filters are optional and not selected by default. But I have many other optional filters enabled that caused me no problems.

So my humble opinion is that Fanboy's filters are completely unreliable. They should not simply added as optional, they should be removed from the official list. If someone wants them back, they can anyway add them. If someone already has them enabled, they can be moved to the custom filter list.

This is my two cents. The decision is yours. Personally I don't care, since I simply disabled them now, without anymore investigate which filter caused the problem.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by ryanbr** [comment]
The specific filter `##.mvp-post-soc-wrap` from commit: https://github.com/easylist/easylist/commit/9c0c1b83645 And re-looking at the original commit, it didn't break on that site.

The site was designed around this css element, so if its hidden it'll caused breakage. It happens. We address it in the forums: https://forums.lanik.us/viewforum.php?f=64 like any other issue.  Bad mouthing an author because of a broken site isn't professional @Marco-Sulla .

**Comment by Marco-Sulla** [comment]
First of all, I do not accept critics of my professionalism from a person that has the *responsibility* to not ruin the work of the other people, and demonstrated the contrary, *two times*.

1. `mvp-post-soc-wrap` is a class used by a stylesheet of **Wordpress**. It's [used for sidebars](http://www.mvpthemes.com/jawn/documentation/#theia-sticky). Why you decided it's an "annoyance", for **all** sites?
2. the other class you removed, and you continue to remove, it's generated by Notify.js, a simple js library that generates divs as lightweight and unobtrusive popups, that disappears after a while. And I used them also at work. But you decided to filter it, again on **all** sites.

I think the quality of your "filters" can be easily checked by everyone. "Fanboy’s Annoyance​​​​​​​​" contains a huge list of global filters. If you see "AdGuard Annoyances" list, for example, the number of global filters is **1 magnitude order** lower.

So, speaking about professionalism, in my humble opinion of a 11-years programmer, you're not so much prudent to etiquette your css selectors as a "annoyance" for **every** site. I kindly suggest you to use Google, DuckDuck or the search engine you want, to **know** what are you filtering and if it's really a good idea to do it globally.

As I already said, personally I disabled all your "filters". I kindly hope that your "filters" will be removed by default from uBlock Origin, only for the good of future programmers and end-users that could have the misfortune to enable them.

**Comment by ryanbr** [comment]
If there is a website issue, report it. Like every other user. (see https://forums.lanik.us/viewforum.php?f=64 ) It's investigated and fixed accordingly. People ask for help, and provide as much as we can without issue.

Some lists (like the Annoyances List) touch more of the website than others, because functionality it does a lot. We wouldn't have filter lists if there was one false positive and the suggesting was to remove said list.

`mvp-post-soc-wrap` is a social div wrapper, which is why its blocked. 

Just a sample of sites using this, without issue.
`https://lifestylogy.com/` 
`https://www.bellanaija.com/`
`https://www.gottabemobile.com/`
`https://washingtonpress.com/`

@uBlock-user please close this

**Comment by Marco-Sulla** [comment]
> If there is a website issue, report it.

And what if the site is on localhost, as happened to me with Notify.js?

Instead of filtering only the sites that uses good classes in bad manners, you do the contrary, you whitelist the false positive. This is the ultimate prove you have no idea how a good list of filters must be created. And the fact you want to close this issue demonstrates also that you are not able to sustain the discussion, because it's evident that you're wrong, and you want to simply truncate, as you do in past with Notify.js. Well, this is **very** professional.

Close this bug, I don't care. I hope that you and your "filter list" will not waste my time again, ever.

**Comment by krystian3w** [comment]
> And what if the site is on localhost, as happened to me with Notify.js?

`@@/(127.0.0.1|localhost)/$generichide`

or whitelist domain/ip in uBO settings?

**Comment by Marco-Sulla** [comment]
@krystian3w Or I can disable all Fanboy's lists, as I did.

The two elements blocked are clearly innocuous. They are been added only because same site use them for advertising. It's like banning forks because someone have blinded someone else with a fork. Are you suggesting to have a mandatory "fork license"?

IMHO it's clear that these filters was added by Fanboy because, probably, there's much sites that used them in a bad way, so it lazily added them as global filter. So, as I said, highly unprofessional.

Take NoScript. Every time I noticed that NoScript blocked a clearly innocuous AJAX request as an XSS attacks, Maone improved its filter or added an entry in its whitelist. **THIS** is professionalism.

So, please, do not climb the mirrors. You don't want to remove this snake oil salesman? You're free to do as you want, and I'm free to remove his "lists" without the bother to check if one of it "lists" ruin my navigation, and add an useless entry in the whitelist, that no other list I activated needs.
