### ISSUE TITLE
redirect doesn't happen when the rule is suffixed with "|".

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#872]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Not sure if it's a bug, but at least not explained in wiki and I couldn't find explanation in past issues. Assume for the example URL below I wanna redirect yads.c.yimg.jp/js/yads.js to noopjs as simply blocking it broke the site on mobile. For blocking, both these 2 rules works:
`||yads.c.yimg.jp/js/yads.js`
`||yads.c.yimg.jp/js/yads.js|`
The difference is the latter allows backward matching so in some case (e.g. example.com/*/ads.js|) should be computationally more efficient. But for redirect while
`||yads.c.yimg.jp/js/yads.js$script,redirect=noopjs`
works as intended,
`||yads.c.yimg.jp/js/yads.js|$script,redirect=noopjs`
doesn't, tho blocking is done.

### A specific URL where the issue occurs

`https://map.yahoo.co.jp/`

### Steps to Reproduce

1. Go to the site with the either of redirect rule above. The request is already blocked by a generic rule in EL but it's irrelevant.
2. Observe if redirect occurs. In SS below the top is the non-suffixed rule and the second top is suffixed one.
![yahoo-chizu](https://user-images.githubusercontent.com/58900598/73151672-86cb3280-410f-11ea-81a5-eec3dab5e4d2.png)

### Expected behavior:

As both are adequate blocking rule, shouldn't redirect happen in both cases?

### Actual behavior:

Explained

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72.0.2/Brave 1.2.43
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect>:

> notice that the filter must start with `||` or `*`, otherwise no redirection directive will be created

By design, as per documentation.

**Comment by gorhill** [comment]
Never mind, I mistakenly read it as "prefixed" instead of "suffixed".
