### ISSUE TITLE
Some blocking action does not increment the uBlock Origin counter

### ISSUE THREAD

**Issue by Massedil** [uBlockOrigin/uBlock-issues#873]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The uBlock badge counter stay to 0 even if a blockage occurs.

### A specific URL where the issue occurs

https://www.cert.ssi.gouv.fr/

### Steps to Reproduce

1. Activate the "Fanboy’s Annoyance" list
2. Load https://www.cert.ssi.gouv.fr/
3. The RSS image on the top right disapears and the uBlock Origin counter stays to `uBlock Origin (0)` instead of `uBlock Origin (1)`.

The logger show 1 blocking action :
- Filtre: ##.fa-rss
- Liste de filtres: Fanboy’s Annoyance 
- Contexte: www.cert.ssi.gouv.fr
- Type: dom
- Lien: https://www.cert.ssi.gouv.fr/#

### Expected behavior:

The counter is 1 so I know that uBlock Origin has done something on the page.

### Actual behavior:

The counter is 0. So I wrongly think uBlock Origin has done nothing. I had to disable all my extension one by one to know which one removed the RSS image.

### Comments

I think I understand that the counter count the canceled network requests. 

But I have no way to easily know if the extension has done something or not. May be a color (logo ? background of the counter ?) can be changed to easily see that uBlock Origin has modified the page.

May be a double counter : 0/1 (0 network request blocked / 1 element removed).

I think, as a user, it is more important to know that the page is altered by uBlock Origin than that a network request has been blocked.

What do you think ?

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 74.0a1 (2020-01-27) (64 bits)
* Operating System and version: Windows 8.1

**Comment by gorhill** [comment]
By design for performance considerations: the badge is for blocked/modified network requests.

Elements affected by cosmetic filters are reported in the popup panel beside the no-cosmetic-filtering switch: <https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering>.

**Comment by Massedil** [comment]
> By design for performance considerations: the badge is for blocked/modified network requests.

Can it be possible to update the badge asynchronously for keeping performance consideration ? 

Just to add a quick way to make it obvious that uBlock Origin has interacted with the page or not.

> Elements affected by cosmetic filters are reported in the popup panel beside the no-cosmetic-filtering switch:

Thanks.

**Comment by uBlock-user** [comment]
Technically, cosmetic filters don't block anything, they're merely modifying style attributes of an element which is not the cause for the counter to go up.

**Comment by gorhill** [comment]
> update the badge asynchronously

It's already implemented this way in the popup panel, and yet this still has caused [performance issues](https://github.com/uBlockOrigin/uBlock-issues/issues/756), hence why now displaying the badge is also done on-demand beside being asynchronous.

**Comment by Massedil** [comment]
> Technically, cosmetic filters don't block anything

As a user perspective, in this case, something is blocked on the page because of the cosmetic filter.

> Just run the logger and you will know.

I know that I can do that, and it is doing that I finally understand what happens. But I work in computer science.

When I recommend uBlock Origin to people they don't know what is "the logger". They just know that "if there is a problem on the page" and "the uBlock Origin icon has a counter displayed" there is something blocked by uBlock Origin and there is a very big button to disable it on the page when you click on the very big button. I think it is all they know and it is often sufficient.

**Comment by uBlock-user** [comment]
> something is blocked on the page because of the cosmetic filter.

Icon badge counter from the begginng has the core purpose of showing how many network requests are blocked. Thats all.

**Comment by Massedil** [comment]
Thank you again for your answers and you time here.

> Icon badge counter from the begginng has the core purpose of showing how many network requests are blocked. Thats all.

That is why in my "Comments" section I suggest some alternatives modifications.

For me, the important point here is "Can we think about something that permit to a non technical user to know on the Ublock Origin badge (always visible by default in Firefox) that Ublock Origin as done ***something*** on the page he see ?".

**Comment by gorhill** [comment]
>  "Can we think about something that permit to a non technical user to know on the Ublock Origin badge (always visible by default in Firefox) that Ublock Origin as done something on the page he see ?"

No. Please read the whole thread I linked to above -- it's shows that such issue was covered in depth.

First, everything is done asynchronously in extensions, so forgetting for an instant that this is a trivial suggestion anyways, there is no point to advise to do so.

Because of the potential performance issues of uBO having to count the number of DOM elements affected by cosmetic filters, this was always been done on demand, i.e. when opening the popup panel.

But even then, as explained in the linked issue above, counting those affected DOM elements _each time_ the popup panel was opened became an issue in itself, hence why it's now doubly on-demand -- you have to hover over the `...` to find out the number of affected elements. This doubly-on-demand approach makes it clear there is no valid solution for having uBO shows the effect of cosmetic filters on the icon badge. No content blocker supporting cosmetic filtering does this, and uBO might be the only content blocker to _at least_ show this in its popup panel (again, via on-demand only).

**Comment by uBlock-user** [comment]
> That is why in my "Comments" section I suggest some alternatives modifications.

It's not just cosmetic filters as you think, uBO does _scriptlet injections_, _HTML filtering_, _resource redirections_, this will ultimately add up to a big number and will ultimately come at the cost of performance.

**Comment by Massedil** [comment]
> No. Please read the whole thread I linked to above

Ok, I just have read it and I better understand.

I think the most important thing for user perspective is "Has uBO done something on this page ?" not "How many elements are blocked ?".

So my first thought was that we don't need a counter, just a boolean `pageModified` that is only updated one time, on the first page modification, and never touched after.

But you answered here that this seems still too much ressource consuming : https://github.com/uBlockOrigin/uBlock-issues/issues/756#issuecomment-548061769.
