### ISSUE TITLE
DNS is queried despite blocking the site with uBlock origin

### ISSUE THREAD

**Issue by dadosch** [uBlockOrigin/uBlock-issues#874]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I visit a site which uses a tracking site like google-analytics (which is blocked by uBlock origin), still a dns request is made to it. DNS prefetching is disabled.

### A specific URL where the issue occurs
twitter.com

### Steps to Reproduce

1. go to a site with for example google-analytics integrated (which should be blocked)
2. watch DNS queries for example using wireshark, or through other ways
3. a dns query for that blocked site (google-analytics) is made

### Expected behavior:

Such a query should not be made as the page is blocked.

### Actual behavior:
Such a DNS query is made

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72.0.2
* Operating System and version: Arch Linux

**Comment by gorhill** [comment]
Unable to reproduce, and this has never been an issue, you will need to provide hard evidences:

- Did the logger shows that all requests to `google-analytics.com` were blocked by uBO?
- What did `about:networking#dnslookuptool` shows?
    - Nothing lookup to `google-analytics.com` shown in my case.
- How do you know the lookup originate from Firefox specifically and `twitter.com` specifically?
- You did not try in a new profile with only uBO + default settings/lists installed, as asked.

**Comment by dadosch** [comment]
> Unable to reproduce, and this has never been an issue with Firefox, you will need to provide hard evidences:
> 
>     * Did the logger shows that all requests to `google-analytics.com` were blocked by uBO?
Yes, it showed a red box next to google-analytics.com

>     * What does `about:networking#dns` show?
It shows an entry `www.google-analytics.com	ipv4	false	0.0.0.0 28 ` (the 0.0.0.0 is because my DNS server blocked it, this is how I found the bug.
>       * No DNS lookup to `google-analytics.com` shown on my side.
> 
>     * How do you know the lookup originates from Firefox specifically and `twitter.com` specifically?
I have no other programs open which could make a request to google-analytics, and all other tabs are closed. If I open twitter.com (and the DNS cache is expired) I can see in my system log that the ` DNSSEC validation failed for question www.google-analytics.com`, this is because my DNS server blocks it. So I know it is from Firefox and can only be from twitter.com (because this is the only page I opened, and it's reproducable for that site for me in my Firefox Profile).
>     * You did not try in a new profile with only uBO + default settings/lists installed, as asked.
I just did quickly, but I can't reproduce it there… I'll have to investigate a bit more

**Comment by uBlock-user** [comment]
> So I know it is from Firefox

If it doesn't appear in `about:networking#dns`, it's not from Firefox.

**Comment by dadosch** [comment]
Ok, I think I found the culprit: If I have https://addons.mozilla.org/de/firefox/addon/cloud-firewall/ disabled, uBlockOrigin works as excpected



> > So I know it is from Firefox
> 
> If it doesn't appear in `about:networking#dns`, it's not from Firefox.

As I wrote, it does appear in `about:networking#dns`

**Comment by uBlock-user** [comment]
>  uBlockOrigin works as excpected

one extension cannot stop another extension from making such bts network requests, uBO works as expected with or without it.
