### ISSUE TITLE
Regarding the syntax versions of Peter Lowe's List

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#875]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - (N/A) uBlock Origin is the only extension
    - (N/A) uBlock Origin with default lists/settings
    - (N/A) using a new, unmodified browser profile
- (N/A) I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I've realised that Peter Lowe's List, in-so-far as it is included in uBlock Origin and forks of it, is using the Hosts version of the list. Wouldn't it have been better to use [the adblocker-syntaxed version of it](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext) instead?

I admit that my request is heavily flavoured by some work I've done on *AdGuard Home*, a tool that would treat domains from Hosts entries very strictly (e.g. it would not cover subdomains, nor domains with differences in `www.` prefixes), while in contrast it would treat `||` entries the way normal adblockers do. This does not seem to affect uBO nearly as much, although I am admittedly not 110% expertious in uBO's treatment of Hosts entries. My findings indicate that uBO tries to convert `127.0.0.1` into `||` anyway, if the strict blocking warnings is any indicator.

The list versions' internally listed update times are the same (e.g. `# last updated:   Wed, 29 Jan 2020 16:22:55 GMT`), so there doesn't seem to be any easily noticeable update delays on the non-Hosts versions that I can easily see.

The filesize is also somewhat smaller, should it become somewhat important that end-users save bandwidth whenever possible.

### A specific URL where the issue occurs

`chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=plowe-0`

### Steps to Reproduce

1. If you're using a Chromium browser, visit chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=plowe-0
2. See that the entries use Hosts syntax, namely `127.0.0.1 example.org`.
3. Go to https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
4. See that the entries use adblocker syntax, namely `||example.org^`.

### Expected behavior:

The most ideal version of Peter Lowe's List is included in uBO, which may or may not be the adblocker-syntax version.

### Actual behavior:

The Hosts version of Peter Lowe's List is included in uBO.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Vivaldi 2.10.1745.27 64-bit
* Operating System and version: Windows 10 November 2019 Update

**Comment by uBlock-user** [comment]
That's upto Peter, @pgl

**Comment by pgl** [comment]
I've suggested this before to @gorhill, but he rightly pointed out that it's working fine as it is. You're correct @DandelionSprout, the code that imports my list turns it into ABP format anyway. I can't find the code right now, but I'm pretty sure that's what happens.

**Comment by uBlock-user** [comment]
> I've suggested this before to @gorhill, but he rightly pointed out that it's working fine as it is. 

https://github.com/gorhill/uBlock/issues/2282

that one ?

**Comment by pgl** [comment]
No, but that's effectively the same. I think it was on Twitter, or via email or something, but years ago and I can't find the specific conversation right now.

**Comment by Yuki2718** [comment]
I have once wondered about it. In my understanding (correct me if wrong!) there should be no difference in performance, as uBO compiles these lists first and, say, ||a.example.com^ will never be even considered if ||example.com^ already exsists tho they are counted as 2 rules in Filter lists. So the question is whether saving 22KB bandwidth per several days is worth switching. OTOH on my end the hosts version says last update was Thu, 30 Jan 2020 15:12:34 GMT while ABP format Wed, 29 Jan 2020 16:22:55 GMT. This diff should also be negligible as per update frequency, but Peter Low's has been also quick to include some malware/scam sites and they have been becoming short-lived.

**Comment by DandelionSprout** [comment]
>*"OTOH on my end the hosts version says last update was Thu, 30 Jan 2020 15:12:34 GMT while ABP format Wed, 29 Jan 2020 16:22:55 GMT. This diff should also be negligible as per update frequency, (…)"*

The ABP version seems to have become updated for today too now. Although, presuming the observation is correct, this would indicate that the ABP version updates on a 15-30min delay, which is honestly around 20min more than I expected it to be. So that is indeed a decently legitimate factor to consider.

>*"as uBO compiles these lists first and, say, ||a.example.com^ will never be even considered if ||example.com^ already exsists tho they are counted as 2 rules in Filter lists."*

That's however something I'd need confirmation from the uBO team on. I presume there could be maybe ½-2sec of filter sync time that could be saved on compiling if using the ABP version, but if it indeed compresses the entries this way already, that'd partially (but only partially) rule out my main factor for suggesting switching to the ABP version.

I'm most of all concerned about whether `127.0.0.1 example.com` would also cover `prefix-subdomain-not-found-elsewhere-in-the-list.example.com`, which I'd also need uBO team confirmation on because I simply don't know about it myself.

**Comment by pgl** [comment]
@DandelionSprout an entry for `example.com` in my list would cover `a.b.example.com`.

eg: I have an entry for `doubleclick.net`: https://pgl.yoyo.org/adservers/details.php?hostname=doubleclick.net

Try going to http://www.subdomain.doubleclick.net in your browser, and you should get blocked if you have my list enabled.

**Comment by DandelionSprout** [comment]
Indeed it does, now that I tested it out. So that's another important question answered.
![image](https://user-images.githubusercontent.com/22780683/73467235-57246080-4383-11ea-842d-bfeaa08e2336.png)

**Comment by krystian3w** [comment]
This is it:

> ![obraz](https://user-images.githubusercontent.com/35370833/73592692-20725580-44fd-11ea-8b3f-fbbc417f3f98.png) |
> --- |

?

**Comment by pgl** [comment]
I think I was talking to @gorhill directly, but it could've been. It's not really important.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/800#issuecomment-581028614

**Comment by linuxandria** [comment]
Personally I think _any_ amount of time converting lists unnecessarily is wasted time, and therefore adblock syntax formatted lists should always be preferable over hosts lists

**Comment by gorhill** [comment]
> Expected behavior:
> 
> The most ideal version of Peter Lowe's List is included in uBO, which may or may not be the adblocker-syntax version.

Historically, uBO's code base has been compatible with hosts file **before** being compatible with ABP's syntax.

uBO is not an "adblocker". Likely I will never see the day when everybody stop referring to uBO as an "ad blocker", I accept I will have to just keep correcting against this reductionist label.

**Comment by krystian3w** [comment]
Also IMO hosts file newer like ABP syntax to block conection.

**Comment by DandelionSprout** [comment]
When I say *adblocker-syntax*, it's almost always simply because it's the syntax that ABP built the fundament of, e.g `||` and `##`.

I myself am arguably the living embodiment of using uBO for purposes that have nothing at all to do with ads, such as e.g. phone app promotions, Steven Universe, bypassing Pinterest login prompts, widening narrow website bodies, softening fonts used by Japanese websites, etc., etc., etc.

**Comment by uBlock-user** [comment]
Having support for HOSTS file format really becomes moot, if you have to replace HOSTS file with adblock syntax list.

**Comment by gorhill** [comment]
I will decline this, this would just cause me to spend time on something that does not need fixing.
