### ISSUE TITLE
Block fonts by their font family name

### ISSUE THREAD

**Issue by svenper** [uBlockOrigin/uBlock-issues#876]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There is no way to target fonts by their names

### A specific URL where the issue occurs

https://addons.mozilla.org/en-US/firefox/

### Steps to Reproduce

1. Go to https://addons.mozilla.org/en-US/firefox/
2. Open the inspector to look for fonts to block
3. All the font URLs are unstable gibberish like `https://addons-amo.cdn.mozilla.net/af42317212d492ac0f5ffabd918b8493.woff2`

### Expected behavior:

There is a way to block these types of fonts by targeting their names "Fira Sans" in some way

### Actual behavior:

There is no such way, gibberish URLs must be used in rules

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72.0.2
* Operating System and version: Void Linux 5.4.14

**Comment by uBlock-user** [comment]
Just use `no-remote-fonts: addons.mozilla.org true` and all fonts will be blocked.

**Comment by Yuki2718** [comment]
Or
`||addons-amo.cdn.mozilla.net^$font`
or
`||addons-amo.cdn.mozilla.net/*.woff2$font`
etc. You don't need to use full URL.

**Comment by svenper** [comment]
The thing is I want to block Fira Sans everywhere. This type of rules will not make exceptions for icon fonts.

**Comment by Yuki2718** [comment]
I misunderstood. But then, uBO will need to analyze fonts for blocking, which I believe is not likely to happen in terms of performance.
