### ISSUE TITLE
Need to whitelist Microsoft Edge internal page

### ISSUE THREAD

**Issue by alexkoala** [uBlockOrigin/uBlock-issues#879]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

uBlock Origin blocks ad in Edge (Chromium) internal page. Need to add `edge-scheme` in whitelist.

`edge://` scheme

* uBlock Origin version: 1.24.4
* Browser Name and version: Microsoft Edge 79.0.309.71
* Operating System and version: macOS Catalina 10.15.3

**Comment by gorhill** [comment]
Is `edge-extension-scheme` needed as well?

**Comment by jspenguin2017** [comment]
Just `edge://` scheme. Extensions in Chromium Edge use the `chrome-extension://` scheme. 
The legacy Edge uses `edge-extension://` scheme. 

Note that the `edge://` scheme is protected, so I don't think this will make a difference. 

![image](https://user-images.githubusercontent.com/7283682/74991011-0f34ae80-5402-11ea-88b6-60308248532f.png)
