### ISSUE TITLE
Safari - Cannot disable per site with Power Button

### ISSUE THREAD

**Issue by OldGuyInTheClub** [uBlockOrigin/uBlock-issues#88]
### Prerequisites

- [ x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Safari: uBo 1.16.0; Cannot selectively disable for a site via Power Button.  uBo is turned off for all sites.  

Problem does not happen on Opera uBo 1.16.6; Clicking Power Button only disables for specific site, other sites appear with uBo enabled.

### A specific URL where the issue occurs
e.g http://www.artsjournal.com; disable blocking here and it remains disabled on other sites

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Visit site via Safari
2. Disable uBo
3. Visit another site
4. uBo remains disabled
5. Tried with other extensions disabled (e.g. Ghostery)
6. Tried on Opera 53.0 - Power Button works as expected; disable on one site, uBo reactivates on subsequent sites

### Expected behavior:

uBo remembers per site disabling

### Actual behavior:

uBo remains disabled on subsequently visited sites

### Your environment

* uBlock Origin version: 1.16.0, no newer version that I can find
* Browser Name and version: Safari 11.1.1
* Operating System and version: macos High Sierra 10.13.5

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock#safari-macos

Safari fork issues are to be posted on safari fork issue tracker.
