### ISSUE TITLE
Search Bar is partially hidden on list pages

### ISSUE THREAD

**Issue by Yaron10** [uBlockOrigin/uBlock-issues#881]
### Prerequisites

- [v] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [v] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [v] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [v] uBlock Origin is the only extension
    - [v] uBlock Origin with default lists/settings
    - [v] using a new, unmodified browser profile
- [v] I am running the latest version of uBlock Origin
- [v ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [Open the Filter Lists tab]
2. [Press the EasyList link]
3. [Paste ad_block in the search box]
4. [Press Next]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]
The Search Bar is partially hidden
![תמונה](https://user-images.githubusercontent.com/10229320/73658901-dffe0d80-469d-11ea-81d7-350043090f39.png)

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Firefox 72
* Operating System and version: Windows 7

**Comment by gorhill** [comment]
Your tab does not seem to render is it does on my side. Did you _really_ try in "new, unmodified browser profile"?

**Comment by Yaron10** [comment]
Can you please try it with Firefox RTL (e.g. Hebrew)?

**Comment by gorhill** [comment]
> Can you please try it with Firefox RTL (e.g. Hebrew)?

No issue in Hebrew.

**Comment by uBlock-user** [comment]
Disable any custom themes you installed and revert to built-in theme.

**Comment by gorhill** [comment]
> Disable any custom themes you installed and revert to built-in theme

He checked "using a new, unmodified browser profile", so this can't be the issue.

**Comment by Yaron10** [comment]
New profile:
![תמונה](https://user-images.githubusercontent.com/10229320/73662797-19864700-46a5-11ea-89ec-566bedaf2ca4.png)

**Comment by Yaron10** [comment]
Did you press `Next` after pasting the string?

**Comment by gorhill** [comment]
Ok, I can reproduce after pressing the prev/next keys, no need for RTL language.

**Comment by gorhill** [comment]
I can't seem to reproduce in Chromium, so I will put back the Firefox label.

**Comment by Yaron10** [comment]
:+1: 

Please note: the Scroll Bar is not displayed properly either (also, no changes preview).

Correct in English.
![תמונה](https://user-images.githubusercontent.com/10229320/73665338-987d7e80-46a9-11ea-918c-a63bb6fc08a5.png)

**Comment by gorhill** [comment]
I am not sure what is happening, there is a horizontal scrollbar that appears which should not be there. Adding `overflow: hidden;` to the `body` element seems to fix the issue on my side.

**Comment by Yaron10** [comment]
Interesting: scrolling the horizontal bar, the correct vertical bar is displayed (along with the wrong one).

**Comment by gorhill** [comment]
Looks like a Firefox glitch to me, there should be no scrollbars for the `body` element since the child element matches exactly the viewport (`100vw`/`100vh`), but for some reasons Firefox adds a horizontal scrollbar in `rtl` mode, which cause the viewport to no longer be high enough and as a consequence vertical scrollbar is added, leading to the issue here.

**Comment by Yaron10** [comment]
> leading to the issue here.

Do you mean the scrollbar issue only or the hidden Search Bar as well?

**Comment by gorhill** [comment]
The search bar issue. I didn't see a scrollbar issue beside spurious horizontal and vertical scrollbars being added to the `body` element.

**Comment by Yaron10** [comment]
So, there's nothing you can do on your side?

**Comment by gorhill** [comment]
I will add `overflow: hidden` to the `body` to enforce that there should be no scrollbar. Maybe this also will fix the other issue you are seeing on your side.

**Comment by Yaron10** [comment]
:+1: 
Great. Thank you.

**Comment by Yaron10** [comment]
Fixed with https://github.com/gorhill/uBlock/commit/3ef999d44b3feb2b4c300c2cea2d58e352325eb4.

Thank you.
