### ISSUE TITLE
Reverse lookup of filter fails with wildcard-leading patterns

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#882]
Originally reported at <https://github.com/gorhill/uBlock/commit/a95ef16e064a#commitcomment-37081122>.

Steps to reproduce:

- Add filter `*grayarrow.gif`
- Open logger
- Navigate to `https://news.ycombinator.com/`
- Observe `https://news.ycombinator.com/grayarrow.gif` being blocked in the logger
- Click on the filter `grayarrow.gif` in the logger
- Observe that no filter list is found for the filter -- should be "My filters"

![a](https://user-images.githubusercontent.com/585534/73659351-0f902400-4664-11ea-9618-b42e9ca5eefe.png)

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/commit/609e9a6428dbb3ab8af142b217beae437dcc7365 also fixed blocking issue:

- affecting current stable uBO 1.24.4 on Chrome 
- add filter `||*kurier.com/oplata*$all`
- paste&go `https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=2ahUKEwiH_cDXsJjoAhXpsIsKHUg0BiIQFjADegQIBRAB&url=https://jodakurier.com/oplata31%2Fingbank%2Fsms&usg=AOvVaw3D8Z7oEgiA1J7Y1l1QsF0h`

```
[rdk@on uBlock-git]$ git bisect new && ./tools/make-chromium.sh 
	609e9a6428dbb3ab8af142b217beae437dcc7365 is the first new commit
	commit 609e9a6428dbb3ab8af142b217beae437dcc7365
	Author: Raymond Hill <rhill@raymondhill.net>
	Date:   Mon Feb 3 14:09:37 2020 -0500
	
	    Remove elision of leading wildcard in some filter patterns...
```

**Comment by gwarser** [comment]
Issue with reverse lookup still not fixed in this case:

![image](https://user-images.githubusercontent.com/886325/77073940-548fd000-69f0-11ea-9a20-2db0def12a2d.png)
