### ISSUE TITLE
ublock origin disabled in firefox reader view

### ISSUE THREAD

**Issue by f4grx** [uBlockOrigin/uBlock-issues#886]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

ublock origin is not usable in firefox reader view

reader view should be free of ads

however, page at this URL manages to display an ad after the raw article:

### A specific URL where the issue occurs

https://www.lemonde.fr/international/article/2020/02/04/proces-en-destitution-de-trump-la-procedure-a-ete-expediee-sans-coup-de-theatre_6028379_3210.html

In fact, most articles on this website have this reader mode ad in the bottom.

My issue is with firefox reader mode. this mode triggers the display of a specific ad that does not show in normal mode.

Here is my whitelist, about-scheme is commented, so it should not be whitelisted
```
# about-scheme
chrome-extension-scheme
chrome-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
# wyciwyg-scheme
```

### Steps to Reproduce

1. go to https://www.lemonde.fr/international/article/2020/02/04/proces-en-destitution-de-trump-la-procedure-a-ete-expediee-sans-coup-de-theatre_6028379_3210.html
2. enable reader view mode
3. enjoy an ad in the bottom of the article

### Expected behavior:

ublock should allow me to remove this ad (eg, by allowing the element picker)

### Actual behavior:

a damn ad in reader view mode

### Your environment

* uBlock Origin version:  1.24.5b1
* Browser Name and version: firefox 72.0.2
* Operating System and version: win10 x64

I tried a filter like this but it has no effect:

www.lemonde.fr##section:has(a[href=https://www.lemonde.fr/services/])

Thank you

**Comment by gorhill** [comment]
Firefox does not allow uBO to inject content script on `about:reader` pages and does not allow to intercept network requests from `about:reader` pages.

<https://bugzilla.mozilla.org/show_bug.cgi?id=1371786>

**Comment by f4grx** [comment]
oh, okay, that sucks, because now these sites have found a place to post unblockable ads.

**Comment by f4grx** [comment]
Follow-up: This problem can be worked around with the Tranquility Reader Firefox extension.
