### ISSUE TITLE
Update from 1.24.2 to 1.24.4 fails on Firefox

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uBlock-issues#887]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Updating uBO from 1.24.2 to 1.24.4 fails on Firefox 72.0.2. Even manual install of XPI downloaded from the [addon page](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) doesn't work.

However, disabling `Run in Private Windows` option for uBO in Firefox Add-ons Manager allows a successful update.

Not found any workaround for Firefox for Android 68.4.2 yet though.

### Steps to Reproduce

1. Select `Check for updates` in Firefox Add-ons Manager.

2. If on desktop, ensure that `Run in Private Windows` option is enabled for uBO in the Add-ons Manager.

3. Click `Update` against uBO on the available updates page.

### Expected behavior:

uBO should be updated to 1.24.4.

### Actual behavior:

Nothing happens and uBO stays on 1.24.2.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72.0.2, Firefox for Android 68.4.2
* Operating System and version: Windows 10, Windows 7, Android 8.1

**Comment by uBlock-user** [comment]
Did you restart Firefox ?

**Comment by in4u** [comment]
Yes, restarted browser as well as OS.

**Comment by gorhill** [comment]
uBO is updated by Firefox, uBO has no say in when Firefox decides the new version will be activated. A workaround that I found work is to disable uBO, restart Firefox, re-enable uBO.

**Comment by in4u** [comment]
Ah, that worked for Firefox for Android.

For desktop, the `Run in Private Windows` trick had already worked. Though not sure why!
