### ISSUE TITLE
'blocking remote fonts option' blocks also fonts that exist on the same place

### ISSUE THREAD

**Issue by make-it-really-easy** [uBlockOrigin/uBlock-issues#888]
When you have turned on 'blocking remote fonts option' it blocks also fonts that exist on the same place with webpage.

Example:

Webpage really caring about your privacy 'startpage.com' has all fonts on the same place 

(
for example :

<link as="font" crossorigin="" href="/assets/fonts/afterall-serif-regular-woff2.woff2?v=86f65f36" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/afterall-serif-medium-woff2.woff2?v=f67a64c7" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-regular-woff2.woff2?v=8bcad4b1" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-semibold-woff2.woff2?v=5babd914" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="/assets/fonts/proximanova-regularitalic-woff2.woff2?v=c48fa3c3" rel="preload" type="font/woff2"/>
)

but uBlockOrigin blocks them all .

Blocking remote fonts is good for privacy but since it does not working well on uBlockOrigin it spoils webpages that really care about privacy.

Could you fix it?

**Comment by gorhill** [comment]
The wiki says _"security and privacy concerns"_, so not blocking 1st-party fonts would not address security concerns, hence why they are also blocked as 1st-party. So, by design.

**Comment by uBlock-user** [comment]
> Could you fix it?

Use `$font,3p` instead.

**Comment by gorhill** [comment]
Or since his concern was privacy, the better approach is to block all 3rd-party by default using dynamic filtering pane.

**Comment by make-it-really-easy** [comment]
For website startpage.com these fonts are local, not remote. 

You have given information how to work it around but many users wants to click the easy option. 

This option is good for privacy but when the users see that it spoils websites they just turn it off. If they would see that some of websites still looks good they would keep this option on. 

Blocking remote fonts is good for privacy - it prevents the remote server to know that your website is loaded.

But this option spoils webpages that really care about privacy and do not load fonts from remote servers.

**Comment by make-it-really-easy** [comment]
For website startpage.com these fonts are local, not remote.  You have given information how to work it around but many users wants to click the easy option.  This option is good for privacy but when the users see that it spoils
 websites they just turn it off. If they would see that some of websites
 still looks good they would keep this option on.  Blocking remote fonts is good for privacy - it prevents the remote server to know that your website is loaded.  But this option spoils webpages that really care about privacy and do not load fonts from remote servers.   Dnia 6 lutego 2020 13:54 Raymond Hill ***@***.***&gt; napisał(a):  Or since his concern was privacy, the better approach is to block all 3rd-party by default using dynamic filtering pane.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .
