### ISSUE TITLE
Description of the XUL version still points to WE releases repo

### ISSUE THREAD

**Issue by Vangelis66** [uBlockOrigin/uBlock-issues#892]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Latest **uB0 legacy**, currently at version **1.16.4.17**, has been installed in latest **Pale Moon**  stable (v**28.8.2.1**) on a Win7 SP1 64-bit host; opening the dashboard and going to the `about` tab, the `Project change log` link still directs to the main, now WE exclusive, repo: 

![PM](https://user-images.githubusercontent.com/9669492/74173175-4f45a580-4c3a-11ea-9cdf-7dac1e3bc6b7.jpg)

### A specific URL where the issue occurs

This is not a URL specific issue!

### Steps to Reproduce

1. Install the latest **uBlock Origin legacy** version on a supported browser
2. Open uB0's dashboard and shift to the `about` tab
3. Click the `Project change log` link

### Expected behaviour:

I'd expect to be directed to either 
https://github.com/gorhill/uBlock-for-firefox-legacy/compare/firefox-legacy-1.16.4.16...firefox-legacy-1.16.4.17
or
https://github.com/gorhill/uBlock-for-firefox-legacy/releases

### Actual behavior:

Redirection to 
https://github.com/gorhill/uBlock/releases

### Your environment

* uBlock Origin version: **1.16.4.17**
* Browser Name and version: **Pale Moon 28.8.2.1 32-bit**
* Operating System and version: **Win7 SP1 64-bit**

I would have liked to post this in the dedicated issue tracker of the new "legacy" repo at 
https://github.com/gorhill/uBlock-for-firefox-legacy/issues
where it's most relevant, but I was instructed against that and directed here...
By a quick look, links inside all localised description files have to be modified:
https://github.com/gorhill/uBlock-for-firefox-legacy/tree/master/dist/description

Many thanks to all the devs

**Comment by uBlock-user** [comment]
>  but I was instructed against that and directed here...

Who instructed you  and where ?

**Comment by uBlock-user** [comment]
@JustOff can you update the links ?

**Comment by gorhill** [comment]
No issue specific to uBlock for Firefox legacy should be filed here.

**Comment by uBlock-user** [comment]
@gorhill You should update the [issue-template](https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/.github/ISSUE_TEMPLATE.md) there, so as to not mislead users into posting issues here.

**Comment by gorhill** [comment]
Fixed, I removed the template file.

**Comment by Vangelis66** [comment]
> No issue specific to uBlock for Firefox legacy should be filed here.

> Who instructed you and where ?

@uBlock-user just answered that for me, many thanks 👍 

> @JustOff can you update the links ?

I guess the `aboutCode` link inside
https://github.com/gorhill/uBlock-for-firefox-legacy/blob/master/src/about.html
should also be updated to point now to 
https://github.com/gorhill/uBlock-for-firefox-legacy
Apologies for missing that in my original report... 

Many thanks again 👍

**Comment by uBlock-user** [comment]
@Vangelis66 Open the issue there with the details.
