### ISSUE TITLE
Dynamic Filter: 3rd party scrips not blocked if in cache

### ISSUE THREAD

**Issue by Zauberfisch** [uBlockOrigin/uBlock-issues#893]
**Bold text is updated/additional information from comments**

### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
In chrome & chromium it appears that not all 3rd party scripts are blocked.  
I have set 3rd party scripts to be blocked, but some 3rd party resources (eg cdnjs.cloudflare.com & ravenjs.com) are still loaded.  
In firefox uBlock behaves as expected and blocks all scripts.
**Edit: appears to effect only 3rd party scripts that are cached by chrome. Disabling cache in developer tools fixes this issue** 

##### Screenshots 
(chrome with wrong behaviour left, firefox with correct behaviour right):
Logged In
![uBlock](https://user-images.githubusercontent.com/186158/74205663-994d7c00-4c78-11ea-9dc2-8e721012b4ca.png)

Not logged in
![uBlock1](https://user-images.githubusercontent.com/186158/74205794-17aa1e00-4c79-11ea-8fd2-63ab43231cd9.png)

### A specific URL where the issue occurs
- https://www.patreon.com/
- https://www.patreon.com/home (if logged in)

### Steps to Reproduce
1. activate "I am an advanced user"
1. block all 3rd party scripts in the dynamic filters
1. **EDIT: ensure "Disable cache" is not active in chromes developer tools**
1. visit patrenon.com

### Expected behavior:
3rd party scripts should not be loaded (firefox does this correctly)

### Actual behavior:
chrome will load some 3rd party scripts 
**EDIT: the scripts loaded appear to only be scripts that are cached**

### Your environment

* uBlock Origin version: v1.24.4 (in both, firefox and chrome)
* Browser Name and version: 
    - Google Chrome: Version 80.0.3987.87 (Official Build) (64-bit)
    - Chromium: Version 80.0.3987.87 (Official Build) Arch Linux (64-bit)
    - Mozilla Firefox: 72.0.2 (64-bit)
* Operating System and version: OS: Manjaro Linux x86_64, Kernel: 5.5.2-1-MANJARO

**Comment by llacb47** [comment]
Can't reproduce this.

**Comment by Zauberfisch** [comment]
Could this be a timing thing? Having restarted my browser, I can't reproduce it anymore either

**Comment by Zauberfisch** [comment]
ok, I've done some more testing:

1. activate "I am an advanced user"
1. block all 3rd party scripts in the dynamic filters
1. visit patrenon.com **(will LOAD 3rd party scripts)**
1. restart browser
1. visit patrenon.com **(will NOT load 3rd party scripts)**
1. unblock 3rd party scripts
1. block all 3rd party scripts in the dynamic filters
1. visit patrenon.com **(will LOAD 3rd party scripts)**

**Comment by Zauberfisch** [comment]
If I disable the cache in chromes developer tools (tab network), 3rd party scripts will be blocked correctly. So without looking into it any deaper, it appears to be an issue with cache. I'm updating the issue to contain all those details

**Comment by uBlock-user** [comment]
Cached resources don't make network requests, so uBO cannot filter them. Cache needs to be overridden, so the browser will make a connection request again and uBO will be able to filter it.

**Comment by gorhill** [comment]
Press <shift> when clicking the refresh button to ensure the browser's memory-based cache is bypassed.

**Comment by Zauberfisch** [comment]
ok, fair enough. But should we perhaps document this somewhere inside the application?
Some small hint, or perhaps make the refresh button that is built into uBlock always do a full refresh that also flushes the cache?

**Comment by Rudxain** [comment]
I can't find this documented anywhere on the Wiki

**Comment by stephenhawk8054** [comment]
There are many issues related to network / service worker caches. I don't think it's practical to document everything related to it in the wiki.

**Comment by garry-ut99** [comment]
> Zauberfisch : But should we perhaps document this somewhere inside the application?
> Rudaxin: I can't find this documented anywhere on the Wiki

It's unclear what do you both mean by word "this":
- (A) that reloading with Shift + click will bypass the cache
- (B) or that "3rd party scripts might not be not blocked if in cache"


(A) is already documented since **28.02.2020** (which means quickly after the current thread has been created) at the very bottom in the spoiler "**I am an advanced user!**": 

> https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-overview-panel - : After modifying the rules, you can quickly reload the page without leaving the popup by clicking on the reload button appearing in the top-right corner. Click it with <kbd>Ctrl</kbd>, <kbd>Shift</kbd> or <kbd>Cmd</kbd> (Mac) pressed to bypass browser cache.

**Comment by Rudxain** [comment]
> I don't think it's practical to document everything related to it in the wiki.

I agree. What about adding a catch-all warning along the lines of "uBO can't block cache-hits, as this is a limitation of the browser API. Any type of resource can be cached by the browser, even across sites."

**Comment by gorhill** [comment]
> uBO can't block cache-hits

It can. It just cannot block specific cache-hits, those which short term memory-based.

**Comment by Zauberfisch** [comment]
> It's unclear what do you both mean by word "this":
> 
> (A) that reloading with Shift + click will bypass the cache
> (B) or that "3rd party scripts might not be not blocked if in cache"

I believe I ment (A), but this is a pretty old ticket.
If that's documented now/a hint visible in the GUI, my concern is satisfied.
