### ISSUE TITLE
Broad rule with || doesn't apply to subdomains when xhr/xmlhttprequest flag is present

### ISSUE THREAD

**Issue by lainverse** [uBlockOrigin/uBlock-issues#895]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Topic on reddit: `https://www.reddit.com/r/uBlockOrigin/comments/f2udsk/universal_filter_possible_for_disabling_floating/`

According to logger (and the fact that content actually appears on the page) it looks like || doesn't match www. before blocked domain name when rule have flag xhr/xmlhttprequest.
In this case following rule doesn't work:
||ultimedia.com/api/widget/$xhr
At the same time either of these two do work and block content from loading:
||www.ultimedia.com/api/widget/$xhr
||ultimedia.com/api/widget/

### A specific URL where the issue occurs

```
https://www.videogamer.com/news/a-former-starbreeze-executive-has-been-convicted-of-insider-trading
https://www.techradar.com/news/swiss-cantons-halt-use-of-new-5g-masts-due-to-health-concerns
https://www.tomsguide.com/news/emotet-wifi-worm
```

### Steps to Reproduce

1. Enable EasyList (enabled by default, contains filter ||ultimedia.com/api/widget/$xmlhttprequest)
2. Visit one of the links above and scroll page down.
3. Look for a block with video-player under article.

### Expected behavior:

There are no video "similar" to content under the article.

### Actual behavior:

Block with video "similar" to article's content is loaded under the article (and starts playing automatically, and detaches from the page when you scroll away).

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version:
    * Vivaldi 2.11.1811.33 (Stable channel) (64-bit)
    * Google Chrome 80.0.3987.100 (Official Build) (64-bit)
    * Mozilla Firefox 74.0b2 (64-bit)
* Operating System and version: Windows 10 Version 1909

**Comment by uBlock-user** [comment]
> In this case following rule doesn't work:
||ultimedia.com/api/widget/$xhr

![Capture](https://user-images.githubusercontent.com/21290713/74470518-b8404e00-4ec4-11ea-9b54-4fe6184d5b57.PNG)

**Comment by gorhill** [comment]
There are these filters in _"uBlock filters -- Unbreak"_:

    ! https://forums.lanik.us/viewtopic.php?f=64&t=43663#p150230
    ||ultimedia.com/api/widget/$xhr,badfilter
    ||ultimedia.com/api/widget/$xhr,domain=tomshardware.com

So the EasyList filter is cancelled by the `badfilter` above.

**Comment by lainverse** [comment]
Ah, I see, it's a filter issue after all. Close it then. Worth to expand that specific filter on sites in the list, though.

**Comment by lainverse** [comment]
Reported URLs into topic on lanik.us.

@gorhill I think it may worth to check disabled filters when logger is opened and mark requests unblocked by "badfilter" similar to whitelisted. Otherwise it isn't clear why request going through. Especially when filter added manually into own filters list and still doesn't work. I haven't seen any indication in the interface that it passed due to being "whitelisted".

**Comment by gorhill** [comment]
> check disabled filters when logger is opened and mark requests unblocked by "badfilter" similar to whitelisted

Not possible, those filters are not in memory since they will never be used -- they are dropped at load time. Even if they would be kept in memory, having to lookup whether there is a matching badfilter for every non-blocked requests is unthinkable performance-wise.

**Comment by lainverse** [comment]
> having to lookup whether there is a matching badfilter for every non-blocked requests is unthinkable performance-wise.

That's why I mentioned "when logger is open". I do agree that this idea would require keeping filters in memory and dynamically enable/disable them depending on logger's window state.

Less obvious and a lot less intrusive idea: display these on click on the request in the logger same as any other rules that applied. I mean as on screenshot from uBlock-user above. In such only that particular link should be matched.

**Comment by gorhill** [comment]
> That's why I mentioned "when logger is open".

That's what I had in mind when I commented.

It's one of those request where the more I think of it, the more I end up "noping". In such case I can only suggest someone else implement a working solution to make the case it can work.

**Comment by gwarser** [comment]
Can they at least be logged on parsing time? Similar to other entries about invalid/unsupported filters?

**Comment by gorhill** [comment]
I thought a while ago about logging at load time (I mentioned this somewhere else), but I decided not to because I fear the logger will be flooded with those entries -- it turns out `badfilter` ended up being used way more than I expected originally.

**Comment by gwarser** [comment]
Only check these in "My filters"?

**Comment by gorhill** [comment]
What filter list a filter belongs to is information gone by the time uBO store that filter in memory.
