### ISSUE TITLE
Ctrl-R shortcut should work while the popup is focused

### ISSUE THREAD

**Issue by tbodt** [uBlockOrigin/uBlock-issues#896]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ctrl-R on the popup should work to refresh the page.

### A specific URL where the issue occurs

https://google.com

### Steps to Reproduce

1. Click the popup
2. Press ctrl-r

### Expected behavior:

The page should refresh

### Actual behavior:

Nothing happens

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Chrome 80.0.3987.87
* Operating System and version: Debian 5.2.17

**Comment by gorhill** [comment]
Use <kbd>F5</kbd>.

**Comment by tbodt** [comment]
Not all keyboards have F5.

**Comment by llacb47** [comment]
To force refresh on MacOS, use Cmd-Shift-R.

**Comment by gorhill** [comment]
> To force refresh on MacOS, use Cmd-Shift-R.

Is this the same thing as <kbd>F5</kbd> and hence this means I don't need to do anything for this issue?
