### ISSUE TITLE
Edge (chromium) port unmaintained

### ISSUE THREAD

**Issue by RespectIsEverything** [uBlockOrigin/uBlock-issues#901]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
If supporting the Opera add-ons repository, why wouldn't the Edge Chromium add-on Store also be supported? Given that it's still Chromium, how many adjustments possibly need to be made?

Edge Chromium will quickly overtake Opera in market-share once it's pushed in the next Windows 10 release.

Nik Rolls doesn't seem to be maintaining the port with consistency.

### A specific URL where the issue occurs
https://github.com/nikrolls/uBlock-Edge

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce
Sit and wait.

### Expected behavior:
Port is maintained

[What you expected to happen]

### Actual behavior:
Port is behind 1608 commits behind master

[What actually happened]

### Your environment

* uBlock Origin version: Current
* Browser Name and version: Edge Chromium
* Operating System and version: WIndows 10

**Comment by uBlock-user** [comment]
See https://github.com/uBlockOrigin/uBlock-issues/issues/890

gorhill's response -- https://github.com/uBlockOrigin/uBlock-issues/issues/890#issuecomment-584124810
