### ISSUE TITLE
hard to select text in custom rules editor on Firefox for Android

### ISSUE THREAD

**Issue by lilydjwg** [uBlockOrigin/uBlock-issues#903]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

I couldn't try with a different profile because it's not supported by Firefox for Android and reset data is too destructive.

### Description

[Description of the bug or feature]

Long or double press on text in the editor  don't bring up the normal text selectors for the user to drag and select text. This makes removing duplicate or obsolete rules time consuming.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

moz-extension://50bb0fc3-7ec9-484a-bd17-263948178ae1/dashboard.html#1p-filters.html

### Steps to Reproduce

1. Open uBlock Origin settings
2. Edit custom static rules
3. Try to delete a lot of lines

### Expected behavior:

I could select multiple lines of rules and get them deleted quickly.

### Actual behavior:

I couldn't select a lot of text in the editor because the selectors are missing.

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Firefox for Android 68.5.0
* Operating System and version: Android 9

**Comment by gorhill** [comment]
Unable to reproduce, I was able to select the word under the double-tap.

**Comment by peace2000** [comment]
I could not do that either at first but after many tries this someway started to work better. Very strange.

**Comment by lilydjwg** [comment]
On Sun, Feb 23, 2020 at 03:55:00AM -0800, Raymond Hill wrote:
> Unable to reproduce, I was able to select the word under the double-tap.

Can you select more than one word? I can select one word by double-tap
sometimes but there is no way to expand it.

-- 
Best regards,
lilydjwg

**Comment by gorhill** [comment]
> there is no way to expand it

I can't extend it with double-tap. But I can see the selection handles after tapping and holding a word.

This is a CodeMirror-based document, and on my side I can select by double-tapping, tapping and holding, or tapping in the gutter. All the selection stuff is either handled by the browser or CodeMirror, I have no plan to add code in uBO to takeover the browser's responsibility to manage selections.

**Comment by lilydjwg** [comment]
I see your screenshot now (github doesn't send notifications for edits). It looks exactly what I wanted!  I do not see the popup either.

I tried with some other text editors online and they are the same, except that a plain textarea could work with some care. Maybe old Firefox doesn't work well with new Android. Hope Mozilla's new one works better....
