### ISSUE TITLE
Bug with the My Filters tab [android]

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#904]
sony xperia zr C5502
android 5.1.1
Build number 10.7.A.0.222
keyboard sony (native) `https://play.google.com/store/apps/details?id=com.sonyericsson.textinput.uxp`
Must-see https://imgur.com/a/930kdWq

_I decided to check the non native keyboard, I managed to delete something, but everything was still buggy_
keyboard google `https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin`
Must-see https://imgur.com/a/xwzR7wV

ps: my firefox profile is clean, newly created

**Comment by gorhill** [comment]
Unless someone care to investigate what needs to be fixed, I won't spend time on such keyboard issues, I can only attest that AnySoftKeyboard work fine on my side with current version of CodeMirror. So whoever has an issue with their installed keyboard will have to do the investigation efforts as to what is the issue and fix.

**Comment by gwarser** [comment]
@bogachenko try disabling suggestion in keyboard settings.

I think this is known issue with CodeMirror.

**Comment by bogachenko** [comment]
> 
> 
> Unless someone care to investigate what needs to be fixed, I won't spend time on such keyboard issues, I can only attest that AnySoftKeyboard works fine on my side with current version of CodeMirror. So whoever has an issue with their installed keyboard will have to do the investigation efforts as to what is the issue and the fix.

@gorhill LOL. Good answer.



> 
> 
> @bogachenko try disabling suggestion in keyboard settings.
> 
> I think this is known issue with CodeMirror.

I can now delete anything, but there is one thing, but on new lines there is a semi-infinite deletion.
Watch this video https://imgur.com/a/xrwLNVP
