### ISSUE TITLE
https://github.com/uBlockOrigin/uBlock-issues/wiki/Permissions outdated (dns permission missing)

### ISSUE THREAD

**Issue by txt-file** [uBlockOrigin/uBlock-issues#906]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

https://github.com/uBlockOrigin/uBlock-issues/wiki/Permissions does not list the ```dns``` permission which uBlock-origin requests since 1.25.0

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/wiki/Permissions

### Steps to Reproduce

1. Visit https://github.com/uBlockOrigin/uBlock-issues/wiki/Permissions
2. search for ```dns``` permission

### Expected behavior:

Find ```dns``` permission

### Actual behavior:

Did not find the ```dns``` permission.

### Your environment

* uBlock Origin version: not relevant
* Browser Name and version: not relevant
* Operating System and version: not relevant

**Comment by uBlock-user** [comment]
@gwarser

**Comment by gorhill** [comment]
Fixed: <https://github.com/gorhill/uBlock/wiki/Permissions#access-ip-address-and-hostname-information>.
