### ISSUE TITLE
glitched description button in popup-fenix on android 

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#907]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Overlapping long button names

![obraz](https://user-images.githubusercontent.com/35370833/75700069-ca3a3300-5cb1-11ea-8ada-e81569172192.png) | ![obraz](https://user-images.githubusercontent.com/35370833/75700295-1f764480-5cb2-11ea-89d3-60ae2e2b812b.png)
--- | ---
Polish glitch with 16px font | Danish glitch

~~Some CSS gone?~~

### A specific URL where the issue occurs

No

### Steps to Reproduce

A. Activate avanced options
B. Change PopupFontSize to 16pt

1. Open few times uBo popup
2. IF Fenix design start, pop-up should glitched

### Expected behavior:

- No glitched,
- Better detect Firefox 68 "ESR"?

### Actual behavior:

Often is glitched

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox 68.5.0 ("ESR")
* Operating System and version: Android 9.0 (December 2019 security patch)

**Comment by krystian3w** [comment]
OK, this is new design for Firefox 73/74 on mobile.

Maybe need reset font-size if avanced USRR changed size in old pop-up.

**Comment by kimsey0** [comment]
The page also looks glitchy in Danish without changing the font size, since the Danish word for "zapper mode": "elementdræbertilstand", is long and doesn't break into multiple lines.

![Screenshot showing overflowing lines in Firefox for Android in Danish](https://user-images.githubusercontent.com/984760/75240153-2c7fc900-57c4-11ea-8cd6-ceaedc0ba7f4.jpg)

**Comment by krystian3w** [comment]
@brampitoyo need modify translations on `crowdin`:

https://crowdin.com/project/ublock

or possible fix with CSS4 / JS library?

**Comment by gorhill** [comment]
I haven't investigated what can be done yet, please be patient, I will investigate as time allows.

**Comment by brampitoyo** [comment]
@krystian3w @gorhill One thing we may be able to do is to extend the text into the third line using hyphenation.

In this case, though, I’m worried that words will lose their meanings when hyphenated. What do you think?

**Comment by kimsey0** [comment]
In Danish, "elementdræbertilstand" can be hyphenated as "element-dræber-tilstand", and "elementvælgertilstand" can be hyphenated as "element-vælger-tilstand".

**Comment by gorhill** [comment]
Given the above comments, I suggest using soft-hyphens, i.e. hyphens that will be rendered only if the word is broken. So:

    Gå til elementdræbertilstand

Would become:

    Gå til elementdræbertil\u00ADstand

`\u00AD` is the way to insert a soft hyphen in JSON strings.

Now I don't know what is the way to enter these on <https://crowdin.com/project/ublock>.

**Comment by krystian3w** [comment]
don't remember add size for `#basicStats` so it's not wider than the vertical width of the screen.

**Comment by gorhill** [comment]
Regarding:

> Change PopupFontSize to 16pt

At some point there is a physical limit to take into account about what to expect from uBO. If the viewport is so small that changing the font size causes the sort of issue seen in your screenshots, than the solution is to not increase the font size to the point where this causes issues. A reminder that the font size is an advanced setting and modifying any advanced setting comes with this warning:

> Warning! Change these advanced settings at your own risk.

**Comment by kimsey0** [comment]
@gorhill: Thanks for handling this so quickly. Any chance you could put the hyphens as indicated in my answer above, that is, before the "tilstand" in each word?

**Comment by gorhill** [comment]
Sorry, I mistakenly added `&shy;` before `stand` instead of `tilstand`. I will fix asap. I think just the final hyphen is enough, no need for two per strings.
