### ISSUE TITLE
Question: New Permissions: Access IP addresses and hostname information - whts this?

### ISSUE THREAD

**Issue by the-j0k3r** [uBlockOrigin/uBlock-issues#908]
Basically now getting this in order to update to new version.

![Capture](https://user-images.githubusercontent.com/31389848/75249459-a5881c00-57d6-11ea-8ae8-7b01814b8391.PNG)

There's no explanation of this permission anywhere (and whats it used for inside ublock) including https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions?as=u&utm_source=inproduct commit history doesn't shed any lights,

* uBlock Origin version: Stuck at 1.24.4
* Browser Name and version: Firefox 64 bit (73.0.1)
* Operating System and version: Windows 10 1809

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/f8qnpc/ublock_origin_1250_with_cname_uncloaking_is_out/

Use reddit for such questions and support.

**Comment by the-j0k3r** [comment]
I dont have or want a reddit account. thx though.

**Comment by gorhill** [comment]
> There's no explanation of this permission anywhere

It's all in the release notes.

**Comment by uBlock-user** [comment]
> I dont have or want a reddit account

That's why I also linked GitHub.

**Comment by the-j0k3r** [comment]
It is not the first port of call, the Firefox dialog shows you a link to their website where permissions are explained, in said page theres no info about it by the exact name.

I realize this isnt a Ublock origin issue, and yes I should have looked in releases, but didnt,

Thanks again.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1617876
