### ISSUE TITLE
Add possibility to selectively enable filters

### ISSUE THREAD

**Issue by limasierra** [uBlockOrigin/uBlock-issues#91]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

At first, this is not a bug but a proposal for an enhancement :)

I use uBlock in blacklist mode, i.e. all ads are default-allowed and I only blacklist certain websites. Now, there is a filter to clean EU cookie warnings (Annoyances → Fanboy’s Cookiemonster List). However, I think it is currently impossible to use uBlock in blacklist mode for ads and still filter _all_ the annoying cookie warnings. Therefore, I propose to add the possibility of permanently enabling selected filters.

### A specific URL where the issue occurs

<http://www.thesaurus.com/>

### Steps to Reproduce

1. Enable cookie warning filter
1. Go to website with uBlock in blacklist mode (i.e. ads allowed)
1. Ads  and cookie warning show up

### Expected behavior:

uBlock should be configurable to show ads and hide cookie warning (i.e. selectively enabled filters).

### Actual behavior:

Ads  and cookie warning show up

### Your environment

* uBlock Origin version: uBlock Origin v1.16.10
* Browser Name and version: Firefox 60.0.2 (64-bit)
* Operating System and version: Arch Linux (current)

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except

Dynamic Filtering _overides_ Static filtering.

**Comment by limasierra** [comment]
That may be true, but it does not address my enhancement proposal :)

I suggest that you reconsider marking the issue as invalid and tag it as enhancement instead. A more fine-grained dynamic filter setup is a valid suggestion IMHO.

**Comment by limasierra** [comment]
Thanks for reopening!

I'll give an example in case my description was not clear: At the moment, there are two options for blacklist-mode users like me:
1. Subject site to advertisement and cookie warning filtering
2. Subject site no none of both

I suggest adding a possibility to

1. Subject site to cookie warning filtering _without_ subjecting it to advertisement filtering

As far as I understand the mechanisms of uBlock, this would require the possibility to enable filters selectively (not "all or none"). I think a common use case would be to enable cookie warning filters permanently (i.e. statically) while still being able to enable ad filters selectively on a per-site basis.

**Comment by gwarser** [comment]
Most of the cookie warning filters is cosmetic. You may leave cosmetic filtering enabled for site.

**Comment by gorhill** [comment]
There is no officially supported blacklist mode, thus I will not add huge development burden to address requests for that mode.
