### ISSUE TITLE
DNS lookup without special permissions or browser support

### ISSUE THREAD

**Issue by innovate-invent** [uBlockOrigin/uBlock-issues#910]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I am sorry if this has already been discussed elsewhere. I was reading an article about how uBlock was filtering first party trackers by doing DNS lookups. This is currently limited to firefox as it has builtin support for DNS queries. I recently had to solve a similar problem where I needed a browser to look up SRV records from a DNS. Rita from CloudFlare suggested DNS over HTTP while discussing a different issue. I was not aware of this service but apparently it is offered by CloudFlare and Google DNS servers.

`https://developers.cloudflare.com/1.1.1.1/dns-over-https/request-structure/`

Hope this helps.
Thanks for the great plugin!

**Comment by uBlock-user** [comment]
> suggested DNS over HTTP while discussing a different issue. I was not aware of this service but apparently it is offered by CloudFlare and Google DNS servers.

This was suggested, gorhill's response -- https://github.com/uBlockOrigin/uBlock-issues/issues/780#issuecomment-555954450

**Comment by gorhill** [comment]
Declined, not possible on Chromium-based browsers, I will replicate my original answer (extended) here:

> Can't this be "emulated" in Chromium by resolving the hostnames using DNS over HTTPS in JSON format?

- This would require uBO to send browsing history information to a remote server, this is anti-uBO.
- Chromium does not support asynchronous blocking webRequest.onBeforeRequest listeners, so this can't work _reliably_ when the result depends on an asynchronous operation such as a DNS lookup.
    - At most, this would be of informational value only.
- Chromium's webRequest.onBeforeRequest blocking ability is being deprecated with Manifest V3, so even without the above issues, this would be wasted development efforts.
