### ISSUE TITLE
Allow disable CNAME-uncloak hostnames in popup UI /dynamic filters only

### ISSUE THREAD

**Issue by Diego-BF** [uBlockOrigin/uBlock-issues#912]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Add an option in (advanced) settings or a toggle in the panel, like in uMatrix 1.4.1b5, to disable show the canonical names of aliased hostnames in popup UI (like until version 1.24.x), disabling CNAME-uncloak hostnames to dynamic filters but still enabling this to static filters.

If the advanced setting `cnameUncloak` already do that, I suggest that the documentation at https://github.com/gorhill/uBlock/wiki/Advanced-settings make this clear. When I read this doc I was in doubt if this option only affect the popup UI / dynamic filters or static filters too.

### A specific URL where the issue occurs

https://www.youtube.com/

### Steps to Reproduce

1. Visit any site with CNAME cloak.

### Expected behavior:

The user can disable show the canonical names of aliased hostnames in the popup UI, disabling the CNAME-uncloak hostnames to dynamic filters but not to static filters.

### Actual behavior:

There's no such option / the option that allow this isn't clearly documented.

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox 73.0.1
* Operating System and version: Arch Linux

**Comment by uBlock-user** [comment]
> When I read this doc I was in doubt if this option only affect the popup UI / dynamic filters or static filters too.

There's no such granularity as you think, when you disable cnameUncloaking via the advanced setting it's completely disabled.

**Comment by gwarser** [comment]
@Diego-BF is "Whether to enable CNAME-uncloaking feature." better?

**Comment by gorhill** [comment]
Sorry, I am going to decline this. This is the kind of feature that will lead to more feature requests and at some point there has to be a limit to the amount of code I throw at uBO and the amount of buttons I throw at the UI. The overview panel already shows all the hostnames seen by uBO, however unclear is their purpose (i.e. `x9ruh34yt8hhy34hv8.cloudfront.net`), so no point to treat canonical names any differently.

**Comment by Diego-BF** [comment]
> @Diego-BF is "Whether to enable CNAME-uncloaking feature." better?

It can be. Thanks for the sugestion.

**Comment by Diego-BF** [comment]
> Sorry, I am going to decline this. This is the kind of feature that will lead to more feature requests and at some point there has to be a limit to the amount of code I throw at uBO and the amount of buttons I throw at the UI.

I totally understand your point, thanks. Just to be clear, when I thought about this suggestion, I was thinking in something like a global rule disabling/allowing for all domains, not something by site. This is why I suggested that it could be even an advanced setting.
