### ISSUE TITLE
Activated uBlock Origin hides Privacy Badger button

### ISSUE THREAD

**Issue by GwenDragon** [uBlockOrigin/uBlock-issues#915]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After installation of uBlock Origin the extension button of Privacy Badger is invisible, only the number for trackers is visible.

### A specific URL where the issue occurs

https://de.vivaldi.net/#pk_campaign=sd&pk_kwd=community-de

### Steps to Reproduce

1. Install extension uBlock Origin
2. Install extension uBlock Origin Extra
3. Install extension Privacy Badger
4. Visit page
5. Privacy Badger button is invisible 
6. Disable uBlock Origin in Extension Manager
7. Privacy Badger button is visible now

### Expected behavior:

Privacy Badger button is visible 

### Actual behavior:

Privacy Badger button disappears 

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Chrome 80.0.3987.122 and Vivaldi 2.11.1811.44
* Operating System and version: Linux, Debian 10.3 x64 KDE 5.54 & Ubuntu 19.10 x64 GNOME 3.34.2

**Comment by uBlock-user** [comment]
Vivaldi issue, uBO cannot hide another extension's icon neither can access it.

**Comment by GwenDragon** [comment]
@uBlock-user That is not a Vivaldi issue as it happen on Chrome 80.0.3987.122 x64, to!

**Comment by gorhill** [comment]
uBO can't control the toolbar buttons beyond telling the browser which icon to use and badge color, only the browser can do so.

**Comment by gwarser** [comment]
Isn't hidden in menu?

![image](https://user-images.githubusercontent.com/886325/75556869-4a0c9700-5a3f-11ea-97d8-f3ab2139f93a.png)

Can anyone reproduce?

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/75557624-5fe18280-5a66-11ea-85e9-e403755056ee.PNG)

Working as expected in Chromium 80, so the issue with the build of Vivaldi. Open an issue at their forum.

**Comment by GwenDragon** [comment]
Cause is default6 activated 2D-Canvas in Chromium :(
chrome://flags/#disable-accelerated-2d-canvas

I will report that to crbugs site.
