### ISSUE TITLE
YouTube ADs are not getting blocked

### ISSUE THREAD

**Issue by pundoo** [uBlockOrigin/uBlock-issues#916]
Occasionally showing ads (both pre-roll and banner)

I've purged and updated all filters, also enabled _cosmetic filtering_ .. but to no avail.

Browser: Google Chrome 80.0.3987.122
OS: Windows 10

**Comment by Fizbin99** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/fas0iy/youtube_is_suddenly_showing_ads_with_ublock_on/
