### ISSUE TITLE
In Element Zapper, support Mac keyboards’ Delete key – PR; filing as issue to work around GitHub bug

### ISSUE THREAD

**Issue by roryokane** [uBlockOrigin/uBlock-issues#917]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I **already wrote a commit** that solves this issue on [a branch `fix-element-zapper-delete-key` in my fork roryokane/uBlock][my branch]. For a full description of the issue, [read the commit message](https://github.com/roryokane/uBlock/commit/96988c59be38307086a2ca953ffc6301c6def508).

I am filing this issue instead of opening a PR because whenever I [try to open a pull request for that branch](https://github.com/gorhill/uBlock/compare/master...roryokane:fix-element-zapper-delete-key?expand=1), the GitHub web interface fails with a “500 Server Error” page. It happens whether I go to the [branch page](https://github.com/roryokane/uBlock/tree/fix-element-zapper-delete-key) and [click Pull request](https://github.com/roryokane/uBlock/pull/new/fix-element-zapper-delete-key), and it happens when I go to [gorhill/uBlock Pull requests](https://github.com/gorhill/uBlock/pulls), click “[New pull request](https://github.com/gorhill/uBlock/compare)”, and choose to compare gorhill/uBlock:master with roryokane/uBlock:fix-element-zapper-delete-key.

GitHub Support told me they “added [my] report to [their] list” of reports related to 500 Server Error issues, but they didn’t say when they would get around to fixing the issue. I would prefer to merge this PR while it’s fresh in my mind rather than waiting weeks or months for GitHub to fix their bug and then creating a PR.

Can someone with commit access to [gorhill/uBlock] please **check if you are able to create a pull request** for [my branch]? GitHub support did say that “When pull request comparisons fail for certain forks, but succeed for others, this can be a result of configurations or settings altered by maintainers of the upstream, root repository.”

If maintainers too are prevented from creating a pull request due to the GitHub bug, can you please **use Git locally** to merge [my branch] into the `master` branch of [gorhill/uBlock], assuming my commit is acceptable?

[gorhill/uBlock]: https://github.com/gorhill/uBlock/
[my branch]: https://github.com/roryokane/uBlock/tree/fix-element-zapper-delete-key

### A specific URL where the issue occurs

https://github.com/gorhill/uBlock/wiki

### Steps to Reproduce

1. Enter Element Zapper mode by clicking on the extension button and the lightning icon
2. Hover over an arbitrary element and see it highlighted
3. Press the key labeled “Delete” on my Mac keyboard

### Expected behavior:

The element is deleted, and I stay in zapper mode.

### Actual behavior:

Nothing happens.

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox 73.0.1 (64-bit)
* Operating System and version: macOS 10.14.6

**Comment by gorhill** [comment]
@roryokane 

I remove the interaction limit on uBO's repo, so you should be able to make the pull request now. Once your first PR is accepted, you will be able to submit PR in the future even with the interaction limit.

**Comment by roryokane** [comment]
Thanks; I was able to create [a PR](https://github.com/gorhill/uBlock/pull/3770).
