### ISSUE TITLE
Wiki page “Element picker” suggested edit – mention Mac keyboard shortcut

### ISSUE THREAD

**Issue by roryokane** [uBlockOrigin/uBlock-issues#918]
### Prerequisites

Not applicable – this is a problem with [uBlock Origin’s documentation](https://github.com/gorhill/uBlock/wiki), not a problem with uBlock Origin itself. I can’t edit the wiki directly or make pull requests against it, so I’m creating an issue.

### Description

This is a suggested change for the wiki page [Element picker](https://github.com/gorhill/uBlock/wiki/Element-picker). It’s about the following sentence:

> Holding <kbd>Ctrl</kbd> while selecting an element will cause similar elements on the page to be also selected <sup>[1.17.5rc0+](https://github.com/gorhill/uBlock/commit/91144c4edcda0207aaf23d61ae47011515d7b8cb#diff-a65f6e6abc235a14e93548d8bf53b81eL1220)</sup>.

I suggest this change:

~~~diff
-Holding <kbd>Ctrl</kbd>
+Holding <kbd>Ctrl</kbd> (<kbd>Cmd</kbd> on Mac)
~~~

> Holding <kbd>Ctrl</kbd> (<kbd>Cmd</kbd> on Mac) while selecting an element will cause similar elements on the page to be also selected <sup>[1.17.5rc0+](https://github.com/gorhill/uBlock/commit/91144c4edcda0207aaf23d61ae47011515d7b8cb#diff-a65f6e6abc235a14e93548d8bf53b81eL1220)</sup>.

On Mac, holding <kbd>Ctrl</kbd> while clicking just causes the context menu to pop up. I had to experiment to find what alternative key this behavior was bound to. I think it would be nice to mention it directly so users don’t have to experiment.

In case it’s relevant, here is the current version of the code that checks for these keys: [`ev.ctrlKey || ev.metaKey` within `element-picker.js`](https://github.com/gorhill/uBlock/blob/ea2da021ba17e8aef52c5f9c73675a6cec9f7048/src/js/scriptlets/element-picker.js#L1155). It’s different from the code in the [commit linked in that sentence](https://github.com/gorhill/uBlock/commit/91144c4edcda0207aaf23d61ae47011515d7b8cb#diff-a65f6e6abc235a14e93548d8bf53b81eL1220), but I don’t think that link should be changed because it’s about the history of the project.

**Comment by gwarser** [comment]
You can edit wiki in this repo - it will be synchronized with official wiki in ~few days at most.

**Comment by roryokane** [comment]
Thanks for the pointer. I’ve made the edit.
