### ISSUE TITLE
Picker-window doesn't appear if images on a site is chosen, but appears for other elements.

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#923]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The title speaks all - I know sometimes the window temporary disappears, or in other case it's apparently hidden as a matter of screen layout and focus, but this is not the either case. The popup simply doesn't appear at all whatever I tried, so I can't create rules via it (tho ofc I can use the logger).

### A specific URL where the issue occurs

`http://app-flamingo.com/blog/english-study-10step/`

### Steps to Reproduce

1. Go to the site on Android - there's no problem on desktop.
2. Open the picker and select the ad images shown in SS1 below.
3. The popup doesn't appear (SS1) but if you choose any other elements it appears w/out problem (SS2).

<details>
  <summary> SS1 </summary>

![app-flamingo1 ](https://user-images.githubusercontent.com/58900598/75691729-cfb27000-5ce7-11ea-855f-3e3d2c0966ff.png)

</details>
<details>
  <summary> SS2 </summary>

![app-flamingo2 ](https://user-images.githubusercontent.com/58900598/75691740-d3de8d80-5ce7-11ea-9e46-cc4037c0804e.png)

</details>

### Expected behavior:

The popup should appear.

### Actual behavior:

Described.

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: First found on Firefox Android 68.5.0, then I installed fresh Firefox Beta 68.6 and fresh uBO with everything default and reproduced.
* Operating System and version: Android 10 with Feb. 05 security patch level.

**Comment by uBlock-user** [comment]
If I remove `srcset` attribute from the image/s via `app-flamingo.com##+js(ra, srcset, img.aligncenter)`, it starts working again.

**Comment by gorhill** [comment]
Problem is the misuse of URL object -- the element picker is feeding a wildcarded URL to `new URL(...)`.

**Comment by Yuki2718** [comment]
@uBlock-user @gorhill Confirmed the filter solved the issue. Is this means it's actually a filter issue?

**Comment by gorhill** [comment]
It's picker code issue, I need to fix the code.

**Comment by uBlock-user** [comment]
@Yuki2718 No, I merely provided a workaround.

**Comment by Yuki2718** [comment]
@gorhill @uBlock-user Okay, thank you for reply!
