### ISSUE TITLE
JPN: ABP Japanese filters (日本用フィルタ)​ blocks Facebook post editing

### ISSUE THREAD

**Issue by Ikijibiki** [uBlockOrigin/uBlock-issues#93]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I set JPN: ABP Japanese filters (日本用フィルタ)​, I am unable to open the ... menu on the right top side of any post on Facebook.

### A specific URL where the issue occurs

www.facebook.com

### Steps to Reproduce

1. Go to Facebook.com
2. Set JPN: ABP Japanese filters (日本用フィルタ)​ on uBlock and save
3. Click on ... menu near top right corner of any existing Facebook post.

### Expected behavior:

Drop-down menu appears

### Actual behavior:

Small spinning circle (waiting) appears and stays forever

### Your environment

* uBlock Origin version:  uBlock Origin v1.16.10
* Browser Name and version: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System and version: MS Windows 10 Pro version 1803, build 17134.112

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/192
