### ISSUE TITLE
New CNAME feature slows down every site

### ISSUE THREAD

**Issue by eazy2k13** [uBlockOrigin/uBlock-issues#930]
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The new CNAME uncloak feature revealed in v1.25.0 slows down every site extremly.
I'm sitting behind a Proxy, maybe this could be a problem for the uncloaking.

### A specific URL where the issue occurs

https://www.bbc.com

### Steps to Reproduce

1. Update to Version 1.25
2. Call any site e.g. bbc.com
3. wonder why this takes so long
4. set cnameUncloak false
5. load any site e.g. bb.com
6. site loads fast again

### Expected behavior:

Site gets loaded in about 1-2 seconds.

### Actual behavior:

Site gets loaded in about 8-20 seconds

### Your environment

* uBlock Origin version: v 1.25.0
* Browser Name and version: Firefox 73.0.1
* Operating System and version: Opensuse Tumbleweed but also on Windows 10

**Comment by uBlock-user** [comment]
Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.

**Comment by gwarser** [comment]
>I'm sitting behind a Proxy

Can you elaborate?
