### ISSUE TITLE
There must be a way to disable popup blocking

### ISSUE THREAD

**Issue by GrayFace** [uBlockOrigin/uBlock-issues#932]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Popup blocking filters only do harm due to (as I understand) Chrome design deficiency: all URLs opened with middle click are considered popups and thus frequently blocked. It's hard to overstate how annoying this is. They aren't that useful anyway - popups on individual sites can be blocked from uBlock interface with ease, but so far I've seen NO description of a way to disable popup blocking filters. (edit: as of writing this issue, I finally managed to do it in my filter list)
I wouldn't go as far as to suggest disabling popup blocking filters in Chrome by default, but there has to be an easy switch to disable it for all external filter lists (that is, everything except "My filters").

### A specific URL where the issue occurs

-

### Steps to Reproduce

1. Middle click a link that's targeted by any EasyList's $popup,third-party filter.

### Expected behavior:

Link opening in new tab.

### Actual behavior:

Tab gets immediately closed upon opening.

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Cent Browser Version 4.0.9.112 (Official Build) (32-bit) (portable) (Chromium 74.0.3729.169)
* Operating System and version: Win 7 64 bit

**Comment by uBlock-user** [comment]
> Tab gets immediately closed upon opening.

By design behaviour. See - https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

Don't use that popup blocker switch if you don't like that behaviour. Use a filter like  `##+js(window.open-defuser)` or report popups on uAssets.

**Comment by gorhill** [comment]
> all URLs opened with middle click are considered popups and thus frequently blocked

Actually this happens very rarely, I can't remember when I had such issue, assuming it happened at all, I can't remember.

You are not providing any specific cases where this happens. It seems to me you may have subscribed to an overzealous filter list and this is where your issue lies.

In any case, without you making the case of an issue with evidences and enough real, actual cases, it's unactionable, and even then, this would squarely be a filter issue, not a uBO issue.
