### ISSUE TITLE
Add scriptlets remove-class and alert-buster-silent

### ISSUE THREAD

**Issue by Crystal-RainSlide** [uBlockOrigin/uBlock-issues#935]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On [wikiHow](https://www.wikihow.com/), there is a class called `hasad`, and when the ad is blocked, this class causes some small issues on the appearance of the page.

!['hasad' removes the padding](https://user-images.githubusercontent.com/16851802/76162310-821a8500-6177-11ea-8346-55fb37ce9d3a.png)

Writing UserStyle or `:style` rules helps, but remove those class works once for all. So, I hope there is a `remove-class` scriptlet to deal with what `remove-attr` can't do.

`alert-buster-slient` is less important. Maybe it's `+js(alert-buster, slient)`, maybe there will be a scriptlet which can handle `alart()`, `confirm()` and `prompt()`.

### A specific URL where the issue occurs

`https://www.wikihow.com/Prevent-Coronavirus`

### Steps to Reproduce

N/A

### Expected behavior:

`hasad` can be removed by something succinct.

### Actual behavior:

Have to use this:
``` JS
// ==UserScript==
// @name              Remove class
// @namespace         RainSlide
// @icon              https://*.wikihow.com/*
// @version           1.0
// @grant             none
// @run-at            document-idle
// ==/UserScript==
document.querySelectorAll('.hasad').forEach(
  hasad => hasad.classList.remove("hasad")
);
```
### Your environment

* uBlock Origin version: v1.25.0
* Browser Name and version: Firefox 73
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
> this class causes some small issues on the appearance of the page.

What kind of issue ? I tested with my remove-class scriptlet, I see no change in appearance whatsoever.

**Comment by Crystal-RainSlide** [comment]
@uBlock-user _Tiny_ issue maybe. `#intro` has this style rule on it:
``` CSS
#intro.hasad {
	padding-bottom: 0px;
	border-bottom: 0;
}
```

Before:

![Before](https://user-images.githubusercontent.com/16851802/76169033-8e223900-61af-11ea-997f-5fccc430eaca.png)

After:
![After](https://user-images.githubusercontent.com/16851802/76169060-c3c72200-61af-11ea-8177-4c4dbe73e5ad.png)

Mainly I just can tell that, on other sites, this can be a real punch.

**Comment by uBlock-user** [comment]
Some padding appears at the bottom border ?

**Comment by gwarser** [comment]
About dialogs: did you tried [`set-constant`](https://github.com/uBlockorigin/ublock-issues/wiki/Resources-Library#set-constantjs-)?

**Comment by Crystal-RainSlide** [comment]
> 
> 
> Some padding appears at the bottom border ?
> 
> Edit: I see the border getting cut out in presence of class `.hasad` but after removal, bottom border doesn't get cut.

Does it have any border? 🤔

![CSS Rules](https://user-images.githubusercontent.com/16851802/76194934-383aa900-6222-11ea-9b34-75bf5b1650be.png)

**Comment by Crystal-RainSlide** [comment]
> 
> 
> About dialogs: did you tried [`set-constant`](https://github.com/uBlockorigin/ublock-issues/wiki/Resources-Library#set-constantjs-)?

`set-constant` only works on JavaScript properties, it can't touch HTML, HTML attributes or CSS.

**Comment by Crystal-RainSlide** [comment]
My own implementation to `remove-class` based on [`remove-attr.js`](https://github.com/gorhill/uBlock/blob/a94df7f3b27080ae2dcb3b914ace39c0c294d2f6/assets/resources/scriptlets.js#L362) and [`Element.classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList), not very tested because I don't know how do `{{1}}` `{{2}}` works, but every part I modified should behave:

``` JS
(function() {
    const token = '{{1}}';
    if ( token === '' || token === '{{1}}' ) { return; }
    const tokens = token.split(/\s*\|\s*/);
    let selector = '{{2}}';
    if ( selector === '' || selector === '{{2}}' ) {
        selector = `.${tokens.join(',.')}`;
    }
    const rmclass = function(ev) {
        if ( ev ) {
            window.removeEventListener(ev.type, rmclass, true);
        }
        try {
            const nodes = document.querySelectorAll(selector);
            for ( const node of nodes ) {
                node.classList.remove(...tokens);
            }
        } catch(ex) {
        }
    };
    if ( document.readyState === 'loading' ) {
        window.addEventListener('DOMContentLoaded', rmclass, true);
    } else {
        rmclass();
    }
})();
```
