### ISSUE TITLE
Please add a "Help" link to the element picker, pointing to the documentation page

### ISSUE THREAD

**Issue by unforgettableid** [uBlockOrigin/uBlock-issues#938]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [N/A] uBlock Origin is the only extension
    - [N/A] uBlock Origin with default lists/settings
    - [N/A] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin available in the Chrome Web Store
- [N/A] I checked the [documentation](https://github.com/gorhill/uBlock/wiki/Element-picker) to understand that the issue I report is not a normal behavior

### Enhancement request

It would be good if you could please add a blue "Help" link to the element picker.

Clicking the link would simply open [the relevant documentation page](https://github.com/gorhill/uBlock/wiki/Element-picker) in a new tab.

### Postscript

I thank you all for all the work you've put into uBO!  The extension has helped me greatly -- especially thanks to its element-hiding capabilities.

### Environment

* uBlock Origin version: 1.24.4
* Browser name and version: Chromium 79.0.3945.79 (32-bit)
* Operating system and version: Xubuntu 18.04.4 LTS (32-bit)

**Comment by gwarser** [comment]
Where you will put it? You know Element Zapper does not even have dialog window?

**Comment by unforgettableid** [comment]
I'm talking about the element picker, not the element zapper.

**Comment by uBlock-user** [comment]
There's no proper place to put it in the UI.

**Comment by unforgettableid** [comment]
I respectfully disagree.

You could put the link:
* next to the `Create` button (preferred), or
* next to the `Preview` button, or
* below the `Quit` button.

If you insist, you could even make it a `Help...` button instead of a link. But a link would be best; this would make it clear that it loads a webpage.

If you think that none of the above suggestions are acceptable, please let us know why. :)

**Comment by gorhill** [comment]
@unforgettableid I use the `?` icon to link to documentation, so I believe there is a way to add this in there. I plan to improve a bit the picker dialog, so I will look into the issue here when I do this.

**Comment by uBlock-user** [comment]
> You could put the link:

    next to the Create button (preferred), or
    next to the Preview button, or
    below the Quit button.


That would feel out of place and forced, that's why I said "proper place".

**Comment by gorhill** [comment]
Neither AdGuard nor ABP have such documentation link in there picker, so declining. There is a link to documentation in the dashboard, that is the way to go to learn more about uBO.
