### ISSUE TITLE
uBO icon in Manage Your Extensions disappears in the offline mode or when network connectivity is not available

### ISSUE THREAD

**Issue by ediowar** [uBlockOrigin/uBlock-issues#939]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[When you enter the offline mode, the uBO icon in Manage Your Extensions disappears.]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox 73.0.1 (64-bit)
* Operating System and version: Ubuntu 16.04.6 LTS

**Comment by uBlock-user** [comment]
Offline mode ? No steps to reproduce ?

**Comment by uBlock-user** [comment]
I see what you mean. The uBO icon is hosted at https://addons.cdn.mozilla.net/user-media/addon_icons/607/607454-32.png, but Firefox is not caching the extension icon when it downloads it to display in Manage Your Extensions pane.  This happens for all extensions if the pane is refreshed in offline mode or if the internet connection is not available. 

This is a Firefox issue.

**Comment by uBlock-user** [comment]
@agi90 Doesn't Firefox cache the extensions icons when it downloads it ?

**Comment by gwarser** [comment]
It's because 32px icon is not specified in manifest. It seems adding this is enough:

	  "icons": {
	    "32": "img/ublock.svg",
	    "64": "img/ublock.svg",

At least in debug mode. I'm also not sure "64" version is needed.

**Comment by uBlock-user** [comment]
@gwarser Does this fix uMatrix too ?

**Comment by gorhill** [comment]
Though [here it says](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons):

> You should supply at least a main extension icon, ideally 48x48 px in size. This is the default icon that will be used in the Add-ons Manager.

**Comment by garry-ut99** [comment]
Also :
- https://github.com/gorhill/uBlock/issues/3196
