### ISSUE TITLE
Cosmetic class filters beginning with a number getting discarded

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#940]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Class filter beginning with a number get thrown out as invalid.

From logger:

Discarded Easylist filter:
![easylist](https://user-images.githubusercontent.com/22258847/76322314-9f576c80-62b9-11ea-9291-98ca6a8e9838.png)

Test Filters added by me:
![testfilters](https://user-images.githubusercontent.com/22258847/76322385-b4340000-62b9-11ea-8303-6bfefc5c86c0.png)

### A specific URL where the issue occurs

Update Easylist or test in My Filters with `test.com##.1-abp` & `test.com##.2-abp` 

### Steps to Reproduce

1a. Update Easylist or
1b. Add test filters to My Filters `test.com##.1-abp` & `test.com##.2-abp` 
2. View invalid filter in logger

### Expected behavior:

Class Filters beginning with a number are parsed and used.

### Actual behavior:

Class filters beginning with a number get thrown out

### Your environment

* uBlock Origin version: uBlock Origin 1.25.3b1
* Browser Name and version: Firefox nightly 76.0a1 (2020-03-10) (64-bit)
* Operating System and version: Windows 10 1909 (64-bit)

**Comment by uBlock-user** [comment]
https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/167?from_comment=6#discussion-167-comment-6

**Comment by gwarser** [comment]
This is better: https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/167?from_comment=5#discussion-167-comment-5

> 
> The problem is the selector `.123tv-ads` is not valid. That filter is from EasyList:
> 
>     123tvnow.com##.123tv-ads
> 
> As per [CSS character escape sequences](https://mathiasbynens.be/notes/css-escapes):
> 
> > If the first character of an identifier is numeric, you’ll need to escape it based on its Unicode code point. For example, the code point for the character 1 is U+0031, so you would escape it as \000031 or \31 .
> > 
> > Basically, to escape any numeric character, just prefix it with \3 and append a space character ( ). Yay Unicode!
> 
> So this would work:
> 
>     123tvnow.com##.\31 23tv-ads
> 
> This needs to be fixed in EasyList.

**Comment by gwarser** [comment]
ABP "Picker" correctly escapes classes.

AdBlock for Chrome creates Attribute Selector.

Both require escaping to work.
