### ISSUE TITLE
vrn.kp.ru (CNAME)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#943]
Firefox 74.0
uBlock Origin 1.25.0
Default + RU AdList

`https://www.vrn.kp.ru/daily/27007.4/4069144/`

The filter RU AdList contains a regular expression that blocks ads on sites that use one-time adservers. As it turned out, in the case of with uBlock Origin for Firefox, sites break down due to CNAME. I am in search of an optimal solution that will prevent the breakdown of sites and will not lead to ad skipping.

**Comment by dimisa-RUAdList** [comment]
It would be better if the block CNAME itself was optional, and not an exceptions for it. But even the presence of an exception option will save from a headache in many cases. True, ABP most likely will not support this option and I will have to use a “badfilter” for the ABP-version of the RU AdList and duplicate the rule in the uBO-version of the filter, but even now they are very different.

**Comment by gorhill** [comment]
> It would be better if the block CNAME itself was optional

I disagree. Hostnames hidden behind an alias -- something decided by the server -- should not be seen any differently than a server-side decision to redirect (a 301 response for example), the only difference with a usual server-side redirect is that the CNAME-based redirect is invisible to end users. The new canonical name-uncloaking feature is to made those server-side redirects visible to end users.

Should a list maintainer use a filter such as `@@...$cname`, the excepted network requests will be shown to users and overridable as usual by dynamic filtering.

So far it seems ABP is still assessing the feature: <https://gitlab.com/eyeo/adblockplus/adblockpluschrome/-/issues/114>.

**Comment by stephenhawk8054** [comment]
I wonder if it would be possible to use `$~cname`? For example, I want to test some regex filters but don't want to include CNAME requests

```adb
/^https:\/\/[a-z]{8,}\.com\/$/$~cname,xhr,3p,method=head,match-case,from=~edu|~gov,to=com
```

However, it shows error to me.

**Comment by gwarser** [comment]
`$cname` works per document. Like `$ghide`.

**Comment by stephenhawk8054** [comment]
Oh I see
