### ISSUE TITLE
Make <noscript> refresh spoofing configurable

### ISSUE THREAD

**Issue by zsugabubus** [uBlockOrigin/uBlock-issues#944]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Site with... 
```html
<noscript>
  <meta http-equiv="refresh" content="0; URL=/enable-scripts-or-die">
</noscript>
```
...can effectively force user to disable uBlock Origin, because owing to “noscript-spoof.js” it will unconditionally done the redirection. I have not found any way to disable it.

### Expected behavior:

Maybe the behavior could be configurable to get over malicious sites.

### Actual behavior:

The redirection is done unconditionally.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72

**Comment by uBlock-user** [comment]
On Firefox you can do -- `example.com##^meta[http-equiv="refresh"]`

**Comment by zsugabubus** [comment]
I tried disabling `noscript` element, but it seems work. Thanks a lot. Guess I can close the issue.
