### ISSUE TITLE
uBlock Origin Extension will NOT INSTALL in Opera Browser ver 67.0.3575.53 

### ISSUE THREAD

**Issue by j80r59-m** [uBlockOrigin/uBlock-issues#945]
![uBlock Origin Extension will NOT INSTALL in OPera Browser ver 67 0 3575 53 Annotation 2020-03-13 152926](https://user-images.githubusercontent.com/62159736/76665176-0be59c00-6544-11ea-900e-0ad3802e400c.png)

### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs
https://addons.opera.com/en/extensions/details/ublock/
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] goto https://addons.opera.com/en/extensions/details/ublock/
2. [Second Step] attempt to install
3. [and so on...]

### Expected behavior:

[What you expected to happen]
uBlock Origin Extension should unzip & Install
### Actual behavior:

[What actually happened] refuses to unzip properly & WILL NOT Install

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version: Opera  ver. 67.0.3575.53
* Operating System and version: Win 10 Pro x32 ver., 1903 O.S. build 18362.116

**Comment by gwarser** [comment]
Clear browser cache, restart browser and try again.

**Comment by gorhill** [comment]
> refuses to unzip properly & WILL NOT Install

This is out of control of uBO, the browser is responsible for installing extension, so if there is an installation issue, it's a browser issue.

**Comment by gorhill** [comment]
By the way, I see a CCleaner dialog in your screenshot, maybe this is what is interfering with your attempt to install.
