### ISSUE TITLE
Unable to save screenshot of entire logger page in Firefox

### ISSUE THREAD

**Issue by ediowar** [uBlockOrigin/uBlock-issues#946]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [Open a tab with a logger, get a log with a size larger than the visible part of the page.]
2. [Go to Tools > Web Developer > Web Console]
3. [Type `:screenshot --fullpage` and press Enter]

### Expected behavior:

[The screenshot file of entire logger page is saved to the same folder you use as Firefox's default download location.]

### Actual behavior:

[The screenshot file of only the visible part of the logger page is saved.]

### Your environment

* uBlock Origin version: 1.25.2
* Browser Name and version: Firefox 74.0 (64-bit)
* Operating System and version: Ubuntu 16.04.6 LTS

**Comment by uBlock-user** [comment]
> The screenshot file of only the visible part of the logger page is saved.

How is a uBO issue ?

**Comment by gorhill** [comment]
> The screenshot file of only the visible part of the logger page is saved

By design the logger's DOM tree contains only visible rows, to ensure performance is kept regardless of the number of rows being preserved for logging purpose.
