### ISSUE TITLE
Popup does not show inline-script being blocked, but logger does show it blocked

### ISSUE THREAD

**Issue by mergitrack** [uBlockOrigin/uBlock-issues#948]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Popup does not show inline-script being blocked, but logger does show it blocked.

### A specific URL where the issue occurs

`https://chromereleases.googleblog.com/`

### Steps to Reproduce

1. Go to website `https://chromereleases.googleblog.com/`
2. Look at uBlock popup and and there is no minus "-" sign next to googleblog.com or chromereleases.googleblog.com
3. Look at uBlock logger and it does show "* * inline-script block" for `https://chromereleases.googleblog.com/`

### Expected behavior:

There should be a minus sign in the popup to indicate something being blocked on googleblog.com or chromereleases.googleblog.com

### Actual behavior:

Popup has no minus sign - not showing anything blocked on googleblog.com or chromereleases.googleblog.com

### Your environment

* uBlock Origin version: 1.25.2
* Browser Name and version: Firefox 74.0 (64-bit)
* Operating System and version: Windows 10 Home 1909

Default rules:
`* * 1p-script block`
`* * 3p-frame block`
`* * 3p-script block`
`* * inline-script block`

Screenshots attached.
![IL1](https://user-images.githubusercontent.com/61667868/76892738-2c219d80-6859-11ea-8149-7d70e8307a6a.png)
![IL2](https://user-images.githubusercontent.com/61667868/76892776-35126f00-6859-11ea-882e-465691e61183.png)

**Comment by gwarser** [comment]
It's more like "enhancement" / feature request.

https://github.com/uBlockOrigin/uBlock-issues/wiki/Quick-guide:-popup-user-interface#the-overview-panel

>The pluses and minuses denote **network requests** which were either allowed (not blocked) or blocked, respectively for the specific domain/hostname aside which they appear.

 + / - is about network requests, not cosmetic filtering, scriptlets, styles, inline scripts, inline fonts, HTML filters.

**Comment by uBlock-user** [comment]
I had my doubts before. That cleared up.

**Comment by uBlock-user** [comment]
> It's more like "enhancement" / feature request.

He's reporting this  as a bug, not as FR or anything. So something to address for gorhill.
