### ISSUE TITLE
menu on Safari not visible

### ISSUE THREAD

**Issue by noelo-cohelo** [uBlockOrigin/uBlock-issues#949]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

1. I did not verify that this is not a filter issue - I don't understand what uBO is and I don't have such interface as it's shown in documentation.
2. I did not check the documentation to understand that the issue I report is a normal behaviour, because it is obvious for me it is not.

The menu font in uBlock Safari icon is too bright -  I cannot see what in contains.
I wish I could attach the screenshot, but I don't see such option.

I deleted specific URL - actual behaviour sections as they don't make sense here.

### Your environment

* uBlock Origin version: I don't know how to check it; I just downloaded it from https://ublock.org
* Browser Name and version: Safari 13.0.5 (15608.5.11)
* Operating System and version: masOS Catalina 10.15.3 (19D76)

**Comment by uBlock-user** [comment]
> I just downloaded it from https://ublock.org

That's a scummy version, not affiliated with uBO whatsoever.
