### ISSUE TITLE
Allow disabling webrtc leak prevention on special sites

### ISSUE THREAD

**Issue by Esokrates** [uBlockOrigin/uBlock-issues#95]
Many WebRTC services (e.g. Discord) stop working when setting "Prevent WebRTC from leaking local IP addresses".
It would be nice when disabling uBlock for that site, it would also disable the WebRTC restriction for that site only, is that technically possible?
Or would it generally be possible to whitelist some sites?

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/3440#issuecomment-357681228

Not possible as it appears to be a global setting.

**Comment by gorhill** [comment]
This will become possible once [this issue](https://github.com/w3c/webappsec-csp/pull/287) this is solved and implemented by browser vendors.
