### ISSUE TITLE
Move Adblock Warning Removal to Annoyances section

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#951]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently the list is under Ads section of Filter lists, and too many people believe it removes obtrusive anti-adblock that locks the page until you disable your blocker while in reality the list just hides unobtrusive messages which can often be dismissed by a close button. [This](https://forums.lanik.us/viewtopic.php?f=106&t=41948) discussion illustrates the situation but I don't think I need to submit more evidences for that. The purpose of the list is exactly a part of job of various annoyances filters so I suppose to move the list to the appropriate section so that user can choose proper filter for his use.

### A specific URL where the issue occurs

No idea what URL to put

**Comment by gorhill** [comment]
Actually I have been wondering lately if I should just remote it -- I have no clue whether it accomplishes anything anymore given that now uBO's own filter lists has grown to the point where I feel _"Adblock Warning Removal"_ has become pointless.

**Comment by mapx-** [comment]
Indeed the list is (and was) from the beginning a useless one, something like an annoyance list

**Comment by Yuki2718** [comment]
In fact I took a dozen or so domains from the list and for all of them I saw no warnings with default settings, not to mention 2 were dead links. Great decision, tho I expect some user question.

**Comment by dimisa-RUAdList** [comment]
I do not agree that this filter does nothing and is useless.

Example:
http://bigpuzzle.ru/puzzle.php?pid=91149
https://myanime.online/anime/full/10645-neveroyatnye-priklyucheniya-dzhodzho-zolotoy-veter-tv-4-jojos-bizarre-adventure-golden-wind-01-iz-39.html
https://piratia.su/topic/1091-iskhodniki-servera-i-klienta-dostupny/?log=1
https://www.e-xecutive.ru/finance/novosti-ekonomiki/1991606-chto-budet-s-rublem-v-2020-godu
http://turbobit.qpython.club/

Etc...

**Comment by gorhill** [comment]
Nothing that can't be added to the current set of default filter lists -- there is no good reasons to have those filters sit in a separate filter list.

**Comment by Yuki2718** [comment]
@dimisa-RUAdList My take on for that is it may be useful for those who visit Russian sites often, as obviously many of specific rules on the list is for .ru - and the rest is mostly for .fr. Not sure how much usuful those generic rules on the list.

**Comment by dimisa-RUAdList** [comment]
@Yuki2718 
Ok, I used "include": https://hg.adblockplus.org/ruadlist/rev/bd4f964ee053

Later I will tune in more detail.

**Comment by Flashwalker** [comment]
Where is now warning remowal?

**Comment by llacb47** [comment]
Nowhere in the default list options, if you want to add it import `https://easylist-downloads.adblockplus.org/antiadblockfilters.txt` to your custom lists

**Comment by dimisa-RUAdList** [comment]
@Flashwalker 
Adblock Warning Removal is now in RU AdList.
