### ISSUE TITLE
"filters" and "annoyances" assets blocking all urls that do not start with "www."

### ISSUE THREAD

**Issue by mauricioquintela** [uBlockOrigin/uBlock-issues#955]
### URL(s) where the issue occurs

All which do not start with "www.". Easily replicable with reddit.com or gfycat.com. 

### Describe the issue

I am running QuteBrowser with the uBlockOrigin assets for adblocking. When the filters.txt or annoyances.txt filters are loaded, all urls which do not start with "www." are blocked. Unloading both of the filters fixes the issue. 

### Screenshot(s)

With either filter loaded: 
![image](https://user-images.githubusercontent.com/39190784/77227380-e249f780-6b77-11ea-9253-9dbf8c33f964.png)

With both filters unloaded:
![image](https://user-images.githubusercontent.com/39190784/77227395-f988e500-6b77-11ea-81be-a1d8f8fd9822.png)

### Versions

- Browser/version: qutebrowser v1.10.1
- uBlock Origin version: assets loaded directly from git repository (latest version, 2020/03/21)

### Settings

Only the uBlock Origin uAssets filters loaded.

**Comment by gwarser** [comment]
>8. Is there an ad blocker?
>There is a simple host-based ad blocker that takes /etc/hosts-like lists. 

https://qutebrowser.org/doc/faq.html


Obviously "filters" and "annoyances" are not host-based.
