### ISSUE TITLE
Add ability to separate subdomains from domain

### ISSUE THREAD

**Issue by Saadi2020** [uBlockOrigin/uBlock-issues#957]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Please Make it possible to separate subdomains from the domain in uBlock's My Rules panel. and Make possible to define *.domain.com to target all subdomains. 

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.25.3b6
* Browser Name and version: Firefox Nightly 76
* Operating System and version: Windows 10 Pro x64

**Comment by uBlock-user** [comment]
Already possible with the rule syntax -- https://github.com/uBlockOrigin/uBlock-issues/wiki/Dynamic-filtering:-rule-syntax#hostname-based-rules

**Comment by Saadi1988** [comment]
i want scripts of abc.com to be allowed in https://abc.com but , be blocked in all *.abc.com . is it possible?

**Comment by uBlock-user** [comment]
>  i want scripts of abc.com to be allowed in https://abc.com but , be blocked in all *.abc.com . is it possible?

Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

**Comment by gorhill** [comment]
> is it possible?

No, it's currently not possible.

**Comment by krystian3w** [comment]
IDK maybe help:

1P/3P - https://github.com/gorhill/uBlock/commit/bde3164eb445a4e74acca303ec9fa07f82ba1b1c

**Comment by krystian3w** [comment]
Test these in uBo dev:

```adb
! https://github.com/
! https://gist.github.com/
||github.githubassets.com/favicons/$image,domain=/^github.com/
```

<details open><summary>Logger output:</summary>

| | filter/rule | status | visit | | | | url |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | `*/favicons/$image,from=/^github.com/` | -- | github.com | 3 | get | image | `https://github.githubassets.com/favicons/favicon-dark.png` |
| +3 | `*/favicons/$image,from=/^github.com/` | -- | github.com | 3 | get | image | `https://github.githubassets.com/favicons/favicon-dark.svg` |
| +1 |  |  | gist.github.com | 3 | get | image | `https://github.githubassets.com/favicons/favicon-dark.png` |
| +1 |  |  | gist.github.com | 3 | get | image | `https://github.githubassets.com/favicons/favicon-dark.svg` |


</details>
