### ISSUE TITLE
Add filterlist for indonesia site

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uBlock-issues#958]
https://github.com/realodix/AdBlockID

AdBlockID |  | https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
-- | -- | --
AdBlockID+ (add-on) |  | https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus.txt

**Comment by llacb47** [comment]
https://github.com/NanoMeow/QuickReports/issues/2589#issuecomment-569455647

**Comment by uBlock-user** [comment]
> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

**Comment by prasetyodedy** [comment]
please add this list to uBo Lite 🙏
https://raw.githubusercontent.com/realodix/AdBlockID/refs/heads/main/dist/adblockid.adfl.txt
