### ISSUE TITLE
Filters Peter Lowe’s Ad and tracking server list

### ISSUE THREAD

**Issue by Icekiss69** [uBlockOrigin/uBlock-issues#960]
Hiya
would it be possible to update Peter Lowe’s Ad and tracking server list to use domain names only or 0.0.0.0 instead of 127.0.0.1? for compatibility and security reasons

dnscrypt proxy uses 127.0.0.1 and ::1
https://github.com/DNSCrypt/dnscrypt-proxy

**Comment by uBlock-user** [comment]
IP address doesn't matter in uBO, uBO will block all websites listed in the HOSTS list regardless.

**Comment by gorhill** [comment]
Why is it a "compatibility and security" issue? uBO discards the `127.0.0.1`.

**Comment by Icekiss69** [comment]
the 127.0.0.1 got mentioned here
https://www.chromestatus.com/feature/5733828735795200
