### ISSUE TITLE
Certain styling filters in 3rd-party filterlists cause reverse lookup to fail 

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#961]
### Description

As above and reported internally in teams at https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/169

### A specific URL where the issue occurs

```
https://camera.aeonax.com/#downloads
```

### Steps to Reproduce

- Subscribe to Adguard Base list or manually add `camera.aeonax.com#$?##wrapper > #predownloads:has(> .inner > #AdamWr) { height: 0px!important; }` to my Filters.

- Open the logger and in another tab browse to `https://camera.aeonax.com/#downloads`

- Click on the filter in the logger and observe reverselookup fail like this --

![Capture](https://user-images.githubusercontent.com/21290713/76645127-54ba4680-657e-11ea-9ea0-1bb1bb8f4ccd.PNG)

### Expected behavior:

Reverse lookup doesn't fail and shows the filterlist where the filter resides

### Actual behavior:

Reverse lookup fails.

### Your environment

* uBlock Origin version: 1.25.3b9
* Browser Name and version: Firefox 76
* Operating System and version: Win 10

**Comment by uBlock-user** [comment]
Another case - `https://turbobit.net/download/free/6r162lshko1c`

![Capture](https://user-images.githubusercontent.com/21290713/77633058-e5c4f080-6f74-11ea-9132-112f54a96e74.PNG)

For this one, I also can't find where this filter belongs in any of the stock lists 😕

**Comment by gwarser** [comment]
`adguard-generic_AdGuard Base.txt:turbobit.net#$?#html[-ext-has="> body"] { background: none!important; }`?

**Comment by uBlock-user** [comment]
^^^ Okay, that's the one.
