### ISSUE TITLE
uBlock origin doesn't block inline JS anymore after setting up https everywhere, until firefox restarts

### ISSUE THREAD

**Issue by calimeroteknik** [uBlockOrigin/uBlock-issues#964]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

After installing (or updating) the firefox module https everywhere, ublock origin's option "disable javascript" does not work for inline scripts.

Restarting firefox fixes the issue.

Since modules update routinely in the background, this appeared as a surprise security issue during a browsing session.

The reproduction steps below leverage the installation process to demonstrate the phenomenon.

### A specific URL where the issue occurs

https://heure.com/
(when blocking javascript, you should not see the time displaying and seconds ticking)

### Steps to Reproduce

On a brand new firefox profile:
1. install ublock origin
2. install https everywhere
(the order of steps 1 and 2 is important, the problem doesn't happen in the reverse order)
3. access ublock origin preferences, check "disable javascript"
4. click the https everywhere icon in the toolbar and enable "Encrypt All Sites Eligible"
5. access any website with inline javascript, and see it execute

### Expected behavior:

No scripts should execute when enabling ublock's option "Disable javascript".

I expect that this should remain true even if I install, change the parameters of, or update (manually or automatically) another seemingly unrelated browser add-on.

### Actual behavior:

After doing something seemingly unrelated in another browser add-on:
Inline scripts execute while uBlock origin's option "Disable javascript" is enabled.

### Your environment

* uBlock Origin version: 1.25.2
* Browser Name and version: firefox 74.0
* Operating System and version: glibc 2.31, gcc 9.3.0, binutils 2.34, linux 5.4.27, X.org server 1.20.7 with modesetting driver, openbox 3.6.1

**Comment by uBlock-user** [comment]
Duplcate of https://github.com/uBlockOrigin/uBlock-issues/issues/502

**Comment by gwarser** [comment]
> click the https everywhere icon in the toolbar and enable "Encrypt All Sites Eligible"

Should work if you turn off this option (https://github.com/ghacksuserjs/ghacks-user.js/issues/664#issuecomment-472524762)
