### ISSUE TITLE
hpHosts list is discontinued

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#971]
Info on official forum: https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003

>  We are currently restructuring hpHosts and it will no longer be updated. You could however check out our browser extension product.
>...
>we're no longer able to support that service 

Discussion: https://www.reddit.com/r/uBlockOrigin/comments/fsgy4b/hphosts_ad_and_tracking_servers_link_down/

**Comment by gallegonovato** [comment]
Good afternoon:

So I don't care if you put me on broken hpHosts?

Because I try to go to the filter page and the page doesn't exist:

https://ibb.co/M1Q5yJ5

Thank you for your help and time

A hug

**Comment by DandelionSprout** [comment]
(Copied from https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-606906103: )

Looking into the code of the Firefox version of Malwarebytes Browser Guars, it seems to me that hpHosts has been turned into internal hexadecimal code in the extension. Someone at Malwarebytes seem to really have gone extra distance to ensure that no other extensions could ever use those lists anymore... 😑

![image](https://user-images.githubusercontent.com/22780683/78080191-0397b880-73ae-11ea-8768-9dd729ac1c23.png)

**Comment by gorhill** [comment]
Closing since hpHosts has been removed form stock assets.

**Comment by THEtomaso** [comment]
@JustOff:
Could you remove it from uBO Legacy too?

**Comment by JustOff** [comment]
@THEtomaso 
Thanks, done.

**Comment by kulfoon** [comment]
Seeing that in the case of a similiar issue - an outdated version of Malware Domain List, alternatives are being proposed to replace the outdated list: https://github.com/uBlockOrigin/uBlock-issues/issues/984 , I wonder why the same doesn't happen here in the case of hpHosts list discontinued, so to keep the same logic of proposing alternatives here, there they are:
- a) https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt (https://github.com/anudeepND/blacklist/) - over 38 000 domains
- b) https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/notrack-blocklist.txt (https://gitlab.com/quidsup/notrack-blocklists/-/tree/master) - over 13 000 domains

**Comment by llacb47** [comment]
My vote is against `https://github.com/anudeepND/blacklist`, I have encountered a little too many false positives for my liking and it all depends on one person who contributed infrequently. `https://github.com/anudeepND/blacklist/graphs/contributors`

**Comment by kulfoon** [comment]
@anudeepND

**Comment by anudeepND** [comment]
@llacb47 I have been maintaining this list for 3 years and I'm willing to maintain it in the future. I aggre that sometimes legit domains gets blocked, but I will remove it if it breaks stuff and the quality of the list also depends on the feedbacks from the user (https://github.com/anudeepND/blacklist/issues?q=is%3Aissue+is%3Aclosed)

I will be happy to addres any issues regarding addition/removal of any domains :)

@kulfoon thanks for pinging

**Comment by Yuki2718** [comment]
I didn't expect the report to bring the discussion for alternatives, maybe this was because MDL is default-enabled and removing this leaves only two lists in the category. I leave the decision to uBO team and filter maintainers, but am personally against adding anything new. There have always been some people who check whatever they can choose in the stock lists, so it's best to keep the stock lists minimal.

**Comment by gwarser** [comment]
It's possible to remove it on Crowdin?

**Comment by gorhill** [comment]
Crowdin is terrible for plain text file, modifying one part invalidate everything.

I want to wholly change the now dated description, something I meant to do since a long time now. At least for now I had already removed reference to hpHosts from the English description is Chrome and AMO stores.
