### ISSUE TITLE
Use Fenix UI as default

### ISSUE THREAD

**Issue by Madis0** [uBlockOrigin/uBlock-issues#972]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The version of uBlock Origin that can be installed on the new Firefox for Android uses a [new design for the panel](https://www.reddit.com/r/firefox/comments/eyyx3t/absolutely_loving_the_new_customizable_ui_of/).

Among other things, it seems to be:

- more touch-friendly (bigger target areas, inline titles for buttons)
- more intuitive (fixes #255 for example)
- cleaner-looking (sections and buttons are clearly grouped and separated)
- supporting dark mode (according to the link above)

Therefore, I have a suggestion - what about making this the default UI for all users? The only thing it misses right now is the popups button, due to mobile browsers not having a concept of popups. But overall it would mean streamlining the development by not having to build for two UI layouts at once.

### A specific URL where the issue occurs

https://example.com/

### Steps to Reproduce

For activating the UI itself right now:
1. Use uBO v1.25+
2. Enable [Advanced user mode](https://github.com/gorhill/uBlock/wiki/Advanced-user-features)
3. On "Advanced user settings", set `uiFlavor` to `fenix`

### Expected behavior:

Use the same UI for everyone.

### Actual behavior:

The UI is only used in the Firefox Preview for Android.

### Your environment

* uBlock Origin version: v1.25.2
* Browser Name and version: Firefox 75.0b11
* Operating System and version: Manjaro 19.0.2

**Comment by uBlock-user** [comment]
Because the new UI is for Firefox Preview, once Preview makes it to stable it will be the default as per https://github.com/gorhill/uBlock/commit/760d206bd472cdc098453e02e9ddfb1bac35f74d

**Comment by gorhill** [comment]
> what about making this the default UI for all users

Declined.
