### ISSUE TITLE
redirect-rule doesn't work when blank pattern (asterisk) is omitted

### ISSUE THREAD

**Issue by lainverse** [uBlockOrigin/uBlock-issues#977]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

According to logger blocked URLs are not redirected in case redirect rule with blank pattern is present, but starts with `$` instead of `*$`. Normal blocking rules with omitted blank pattern work fine since asterisk is optional in such case. Not for redirect rules, though.

### A specific URL where the issue occurs

`https://www.reddit.com/`

### Steps to Reproduce

1. Add following two rules:
    $script,redirect-rule=noopjs,domain=reddit.com
    $script,domain=reddit.com
2. Open logger and filter it by 'noop'
3. Visit reddit.com anc check logger.
4. Change first rule to:
    *$script,redirect-rule=noopjs,domain=reddit.com
    Note extra asterisk at start.
5. Repeat 3.

### Expected behavior:

In both cases all blocked scripts redirected to noop.js and that is visible in the log.

### Actual behavior:

Only in second case (step 5) blocked scripts are redirected to noop.js and appear in the log.

### Your environment

* uBlock Origin version: 1.25.2
* Browser Name and version: Firefox 75.0b12 (64-bit)
* Operating System and version: Windows 10 18363.752

**Comment by lainverse** [comment]
Ugh, looks like missed this in the documentation. It were mentioned for normal redirect instead of redirect-rule. Not sure why is it like this, though. Why is it not optional?

**Comment by uBlock-user** [comment]
By-design. You need to add `*`.

**Comment by gorhill** [comment]
> Why is it not optional?

Just the way the feature evolved over time. I can internally map the empty pattern to `*` if that is convenient. I just wished that `*` had be the canonical way to specify "match any URL".

**Comment by szakib** [comment]
> 
> 
> By-design. You need to add `*`.
Please add this fact to the [documentation](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax). This GitHub page is the only place where this fact is written down.

**Comment by uBlock-user** [comment]
@szakib That's no longer necessary - https://github.com/gorhill/uBlock/commit/cb5437b1619ed4e84b7b1319b400f44f98df117a
