### ISSUE TITLE
cnameUncloakProxied not documented

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#978]
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

No description of advanced user setting `cnameUncloakProxied` in https://github.com/gorhill/uBlock/wiki/Advanced-settings

### A specific URL where the issue occurs
-

### Steps to Reproduce

1. Options->Settings->Gearbox next to "I am an advanced user"-> "i" icon
2. Read https://github.com/gorhill/uBlock/wiki/Advanced-settings

### Expected behavior:

All settings should be explained

### Actual behavior:

`cnameUncloakProxied` is not explained

### Your environment

* uBlock Origin version: 1.26.0
* Browser Name and version: unrelated
* Operating System and version: unrelated

**Comment by gorhill** [comment]
It will be removed in the future when the Firefox issue is fixed -- it's for development purpose only, not everything in advanced settings has to be documented.

**Comment by gorhill** [comment]
I invite whoever to contribute to the documentation instead of opening issues that documentation is lacking.

Regarding the documentation, the best contributions are those for which something is done rather than those asking for something to be done -- there are hundreds of code issues still opened here and in other projects I maintain, so someone taking on the burden of addressing documentation issues will always be better than someone asking someone else to take on more burden.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings/_compare/8f05940b72592022726ea54d504154f9c1012e86

**Comment by emanruse** [comment]
> It will be removed in the future when the Firefox issue is fixed -- it's for development purpose only, not everything in advanced settings has to be documented.

There are other settings for dev purposes but they are documented. One has no way to know what setting serves what purpose without any info whatsoever.

> I invite whoever to contribute to the documentation instead of opening issues that documentation is lacking.

One can contribute only if one is informed or is a developer. I am neither but I was looking for info. Hence the issue.

> [...] someone asking someone else to take on more burden.

This is not aimed to be a request for overloading anyone, so please don't interpret it this way. It is rather simple: there is a setting and there is no info what it does, so it is natural for a user (even an advanced one) to expect at least a little bit of info (e.g. "this is a dev setting, don't touch"). I hope you are not suggesting that besides checking for previous issues on a topic one should also explore the source code to find out how everything works before opening an issue.
