### ISSUE TITLE
Block redirects to specific URLs or patterns of URLs

### ISSUE THREAD

**Issue by TheRealCuran** [uBlockOrigin/uBlock-issues#980]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Many pages are introducing content blocking redirects to pages demanding consent to track the user and sell their data (up to the point where giving informed consent under GDPR is impossible for the user because it is not possible to track down to who the data will be sold in what form in the future, once the initial consent is given). However the actual content is still available in full under the "normal"/non-redirected URL (this can be verified by downloading the page with `wget --max-redirect=0`), it is just that you get redirected to a "consent page" by the server unless your browser sends the appropriate cookies/solves a challenge through JS, proving you allow tracking.

A new network filter option to block the redirect from occurring would stop this behaviour.

### A specific URL where the issue occurs

`https://www.zeit.de/kultur/2020-04/globalisierung-china-coronavirus-eugen-ruge`

### Steps to Reproduce

1. Disallow JavaScript, block cookies
2. Open `https://www.zeit.de/kultur/2020-04/globalisierung-china-coronavirus-eugen-ruge`
3. Observe being redirected to `https://www.zeit.de/zustimmung?url=https%3A%2F%2Fwww.zeit.de%2Fkultur%2F2020-04%2Fglobalisierung-china-coronavirus-eugen-ruge`

NOTE: Adding something like `||zeit.de/zustimmung*$document` to the local rules blocks the opening of the target page, but not the redirect to it. I want an additional option to block that redirect.

### Expected behavior:

Being able to add a rule preventing all redirects to `https://www.zeit.de/zustimmung*` and staying on `https://www.zeit.de/kultur/2020-04/globalisierung-china-coronavirus-eugen-ruge`

### Actual behavior:

Not being able to block the redirect to `https://www.zeit.de/zustimmung?url=https%3A%2F%2Fwww.zeit.de%2Fkultur%2F2020-04%2Fglobalisierung-china-coronavirus-eugen-ruge` and getting redirected.

### Your environment

* uBlock Origin version: v1.25.2
* Browser Name and version: Firefox/74.0.1
* Operating System and version: Debian GNU/Linux, testing

**Comment by uBlock-user** [comment]
Not possible, server-sided redirects cannot be blocked. They're specifically checking for cookies in the Request header and they're not finding those cookies because you're blocking cookies.

**Comment by TheRealCuran** [comment]
If `wget --max-redirect=0` solves the issue, it should be possible to implement a similar block in uBlock Origin, right? Because what the server sends back is a `Location` header. And I want that redirect initiated by the `Location` header blocked.

Though another option might also be to just be able to set a user agent for requests to certain URLs (in this particular example sending for example `wget` as the user agent makes the server stop sending the `Location` header). 🤔 Would that be easier (I'm happy to make a new ticket for that)?

**Comment by uBlock-user** [comment]
Unless we get [Navigate-To CSP Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/navigate-to), implemented,  nothing else currently is possible without allowing cookies.

**Comment by gorhill** [comment]
> If `wget --max-redirect=0` solves the issue, it should be possible to implement a similar block in uBlock Origin, right?

The browser is doing the fetch here, and as per Network pane in the dev tools, the response is [HTTP 307](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection), there is no HTML data sent, so blocking the redirect would leave you with a blank page.

**Comment by gwarser** [comment]
@TheRealCuran 

> If `wget --max-redirect=0` solves the issue,

It does not. Try:

    wget --max-redirect=0 -U 'Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0' https://www.zeit.de/kultur/2020-04/globalisierung-china-coronavirus-eugen-ruge


It's just user-agent dependent.

**Comment by gorhill** [comment]
> sending for example wget as the user agent makes the server stop sending the Location header

I decline implementing such feature in uBO for now:
- By default uBO does not circumvent such server-side mechanisms -- this would be classified as an annoyance at most
- I do not want to implement a non-trivial feature for the sake of one single case, that site could easily change to no longer serve the page if it found out its mechanism is circumvented

For now I suggest you simple use a user agent switcher:
- https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/
