### ISSUE TITLE
Adding a dynamic switch for the filtering of uncloaked requests

### ISSUE THREAD

**Issue by Aeriem** [uBlockOrigin/uBlock-issues#982]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I run uBlock Origin in **hard mode** and had to adapt my dynamic rules to the recent CNAME uncloaking feature (which is great!).
Because uBO already provides great control over requests, I wish I didn't always have to individually noop them a second time after they are uncloaked.
The current status does protect users from unknown domains hidden behind CNAMEs, and should remain the default.
What I am asking for is a way to dynamically choose between those three states, globally and locally:
- Uncloaked filtering is done using both dynamic and static engine.
- Uncloaked filtering is done using only the static engine.
- Uncloaked filtering isn't done.

This is mostly relevant for **hard mode users**, because 3rd-party requests are already completely under control in this mode.

This could be implemented using a new "Uncloaked requests" row, added under "3rd-party frames" in the dynamic filtering panel:
- When globally/locally blocked, the appropriate requests would be processed a second time using both engines after CNAME uncloaking. This is the current way.
- When noop'ed, requests would only be processed by the static engine after uncloaking.
- When allowed, requests would not be processed a second time after uncloaking.

This would allow for easier hard mode rule-making, while still statically filtering uncloaked requests.
This is also much more practical on websites where CNAMEs are used heavily.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Set uBO in hard mode.
2. Open linked URL.
3. Open uBO's dynamic filtering panel.
4. Noop `avatars0.githubusercontent.com` requests.
5. You now also have to noop `github.map.fastly.net` for the same requests to be able proceed after CNAME uncloaking.

### Expected behavior:

1. Set uBO in hard mode.
2. Set the (hypothetical) CNAME row to global noop.
3. Open linked URL.
4. Noop `avatars0.githubusercontent.com` requests.
5. The request was not filtered a second time by the dynamic engine after uncloaking, and can proceed.
6. The request was still filtered a second time by the static engine after uncloaking, and filters applied as usual.

### Actual behavior:

There is currently no way to noop, allow or block all uncloaked requests in dynamic filtering using a single global or local rule.

### Your environment

* uBlock Origin version: 1.26.0
* Browser Name and version: Mozilla Firefox 75.0
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
> statically filtering uncloaked requests without applying dynamic filtering to them.

Not possible, dynamic rules are prioritised over static filters, that's the hierarchy in uBO.

**Comment by Aeriem** [comment]
> Not possible, dynamic rules are prioritised over static filters, that's the hierarchy in uBO.

I understand that, but since we can noop requests, I was picturing a global rule that would noop requests, but only if and after they have been uncloaked. This would allow for "normal" filtering to happen as usual, and uncloaked filtering to only be static.
Hard mode obviously isn't hassle-free, but this would make it less tedious. CNAME uncloaking brought a way to counter new tracking techniques, and that's great! The only drawback is that it made this mode a lot more tiresome.

**Comment by Yuki2718** [comment]
Hard mode is such a mode that requires many more noops to be added regardless of CNAME cloaking. I wonder how many rules, in relative to the whole, need to be added by CNAME cloaking under the mode. Medium mode is not much affected - I guess I've added a dozen or so rules, which is utterly negligible (12/1200 = 1%).

**Comment by Aeriem** [comment]
In my experience, since CNAME uncloaking, I've had to set 30 to 50% more rules per website.
What's annoying about it is that most CNAMEs are used for legitimate reasons, not for tracking, making those added rules unnecessary (all of them, in my case). Also, it adds a lot more reloads to the initial "setup" of a given website, because you have to noop and reload requests for them to be uncloaked. And when CNAMEs are heavily used, you can end up noop'ing a whole domain like cloudflare.net. My issue with this is that while I don't mind receiving a website's content that's hosted by CloudFlare, I might not want to allow CloudFlare's own content with it, and individually whitelisting some of those CNAMEs can be a fool's errand.

My TL;DR was poorly worded, as I know dynamic filtering will always apply once enabled. What I meant was: given the filter lists' ability to block the bad eggs, it would be nice to be able to automatically noop uncloaked requests after the uncloaking, and before the second filtering pass. Since uncloaked requests must be noop'ed or allowed requests, or they wouldn't have been uncloaked in the first place, there wouldn't really be a privacy or security issue, and static filtering would come the rescue should a bad request slip out.

**Comment by Aeriem** [comment]
I realise I used two contradicting ideas in this issue.
In my original post, I asked for a way to bypass the dynamic filtering engine for uncloaked requests.
However, in my last comment, I asked for a global noop rule for uncloaked requests, hence using the dynamic engine.
I would assume the latter idea is the better, and would like to know if I should edit my original post.

**Comment by Aeriem** [comment]
Here's an edited screenshot which might explain the idea a bit better.
It might not be trivial to implement, and given that I don't have the technical skills to help, this whole issue is only meant as a suggestion.

On the topic of the actual benefits (for hard mode users), I have experienced such an increase in my number of rules (it doubled on frequently used websites) and time spent making them that I partly gave up.
I globally allowed some of the most redundant CNAMEs and trimmed them down to the base domain.
Even after this, I still find myself creating a lot of rules for less common, but still harmless, CNAMEs.
I'd say overall I still have 40% added rules on domains I visited since uncloaking was implemented.

Thank you for the hard work you keep putting in this extension on your own time, it is very much appreciated!

![Uncloaked requests switch](https://user-images.githubusercontent.com/45237401/82035168-74194100-969f-11ea-86c1-66c0909e08f0.png)

**Comment by Aeriem** [comment]
After some months, it feels like CNAME dynamic filtering was just a new habit to pick up. The number of added rules shouldn't have been my main point in this issue, as it is a given that it will happen when enabling hard mode. My focus was on convenience, which is not the point of this mode. I apologize for opening an issue that isn't one in the end.
During this time, I encountered more websites using CNAME cloaking to pass 3rd-party trackers as 1st-party requests. Besides, globally noop'ing uncloaked requests would not fit the whitelist approach to 3rd-party connections behind hard mode.
I would close this issue, but I don't know if you wish to keep it open.

P.S.: My confusion between "noop'ing" and "not using the dynamic filtering engine" when raising this issue was bad, sorry about it.
