### ISSUE TITLE
Youtube Recommended Videos have disappeared

### ISSUE THREAD

**Issue by teetangh** [uBlockOrigin/uBlock-issues#983]
WITH UBLOCK ORIGIN TURNED ON 
![image](https://user-images.githubusercontent.com/44238657/78979048-ada6db80-7b38-11ea-8842-fcdea51be938.png)

WITH UBLOCK ORIGIN TURNED OFF
![image](https://user-images.githubusercontent.com/44238657/78978890-53a61600-7b38-11ea-84a9-d79a17307617.png)

**Comment by SephirothSG** [comment]
Appears to be due to an entry in https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt
Disabling this filter list will resolve the issue if you don't wish to completely disable uBlock

**Comment by teetangh** [comment]
> Appears to be due to an entry in https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt
> Disabling this filter list will resolve the issue if you don't wish to completely disable uBlock

**Comment by teetangh** [comment]
> Appears to be due to an entry in https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt
> Disabling this filter list will resolve the issue if you don't wish to completely disable uBlock

I am novice user. How do you disable the filter ?

**Comment by SephirothSG** [comment]
Actually, scratch what I said above. It seems only disabling all the annoyances filters that are enabled by default will resolve this.

Open the uBlock dashboard > Filter lists and uncheck all filters under `Annoyances`
http://puu.sh/FvDQu/880b946651.png

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7212

**Comment by gorhill** [comment]
Please, respect the issue template, **do not** delete it** -- this is what the template asks you to verify before opening an invalid issue here:

```
- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at
      [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    - If disabling uBO <https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button>
      makes the issue go away, then in all likelihood this is a filter issue.
    [...]
```
