### ISSUE TITLE
Firefox indicates that the webpages download failed.

### ISSUE THREAD

**Issue by S3ndG** [uBlockOrigin/uBlock-issues#986]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I try to save a FULL webpage (with the pictures, not just the html part) with some blocked stuff inside, Firefox tells me that the download failed. Which is wrong.

### A specific URL where the issue occurs

`https://www.freenews.fr/freenews-edition-nationale-299/une-collecte-organisee-pour-fabriquer-des-visieres-de-protection-en-3d-par-nos-makers-et-pour-les-soignants`

### Steps to Reproduce

1. Go to that webpage.
2. Do Ctrl+S, select FULL webpage
3. Click on Save

### Expected behavior:

The download icon of firefox should be blue and indicates that the download succeded.

### Actual behavior:

The download icon shows an orange circle and says it failed.

### Your environment

* uBlock Origin version: 1.26.0
* Browser Name and version: firefox 75.0 64 bits
* Operating System and version: windows 10 64 bits

**Comment by gwarser** [comment]
> ### Expected behavior:
> 
> The download icon of firefox should be blue and indicates that the download succeded.

Everything what is blocked is blocked, everything allowed is allowed?

I that case it's not uBO issue, but Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1445211

**Comment by gwarser** [comment]
@gorhill, from [bug 1445211#c41](https://bugzilla.mozilla.org/show_bug.cgi?id=1445211#c41):

>We won't know the (internal equivalent of the) parentFrameId here, at least for now. It's possible the refactor in bug [1576188](https://bugzilla.mozilla.org/show_bug.cgi?id=1576188 "[Fission] Make Save Page As Fission-compatible") will help with that though.

Something specific that would help?

**Comment by gorhill** [comment]
I don't see an issue, when I disable uBO on `https://www.freenews.fr/`, _"Save As..." works without error on my side. uBO uses the `documentUrl` property when `tabId` is `-1`. I am not even sure that `parentFrameId` is really used in uBO.

**Comment by gorhill** [comment]
And to be sure, I put breakpoints in code paths where uBO cancels network requests or change response headers and none were taken when I saved the document after I disabled uBO on that site. So I can't reproduce the error reported by the user , except when I do not disable uBO.
