### ISSUE TITLE
`min-height` glitch uBO element picker

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#987]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Few sites can move element picker out of the screen with `min-height: 2650px`.

Ultrawide monitor may no help at all...

### A specific URL where the issue occurs

`https://polcovid.pl/mapa-i-statystyki/`

### Steps to Reproduce

1. Open site
2. try block any element with picker
3. element picker "pop-up" is out of screen:

   guilty:

   ```css
   iframe {
       width: 100%;
       min-height: 100vh;
       min-height: 2650px;
       border: none;
   }
   ```

### Expected behavior:

override `min-height`.

### Actual behavior:

`min-height` is not override.

> This is not `transform` / `zoom` glitch - https://github.com/uBlockOrigin/uBlock-issues/issues/419

### Your environment

* uBlock Origin version: 1.26.1b9
* Browser Name and version: Firefox 75.0
* Operating System and version: Windows 10

**Comment by krystian3w** [comment]
Workaround with cosmetic filters:

`*##iframe[id][style]:not([class]):style(min-height: auto !important;)`

**Comment by krystian3w** [comment]
maybe need add too:
```
'filter: unset',
'transfrom: unset',
```

to disable "blur" and "transformation"?

 > ![obraz](https://user-images.githubusercontent.com/35370833/79366392-69f30e00-7f4c-11ea-8578-9b9596ffe38c.png)


effect:

![obraz](https://user-images.githubusercontent.com/35370833/79366505-99097f80-7f4c-11ea-8aa3-672fd78622ea.png)

The marking of the elements was reversed by 180 degrees and the text was blurred.

I just haven't encountered such a hostile approach to make it difficult to use the picker element.

**Comment by gorhill** [comment]
On what site does this happen?

**Comment by krystian3w** [comment]
I do not know  any with this (`jsfidle` demo - no worth) but any can use this in "the future" as not to block the ads / elements manually by newbie user.

**Comment by krystian3w** [comment]
Real break wifh filter: #2075 

Still we must found real examples for rotate by CSS3.
