### ISSUE TITLE
Unable to edit Filter lists in Firefox

### ISSUE THREAD

**Issue by mattijevi** [uBlockOrigin/uBlock-issues#989]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### No Filter List in Firefox

The Filter list is gone and I cant edit it. It is causing uBlock Origin to not block anything.

When I go to the "Filter lists" tab I see the following:
[Console](https://imgur.com/mZxAF2Q) 

There are no filter lists and I cant add any.

### A specific URL where the issue occurs

[https://google.com](https://google.com) 

### Steps to Reproduce

1. Go to "Filter lists" tab in uBlock Origin preferences.

### Expected behavior:

See current filter lists and be able to edit the list

### Actual behavior:

An error in the console.

### Your environment

* uBlock Origin version: v1.26.0
* Browser Name and version: Firefox 75.0 (64-bit)
* Operating System and version: macOS Catalina 10.15.3

**Comment by gwarser** [comment]
All green here: https://firefox-storage-test.glitch.me/ ?

**Comment by mattijevi** [comment]
Thank you. That was it. Sorry for wasting your time.
