### ISSUE TITLE
Ublock origin crashes on Chrome

### ISSUE THREAD

**Issue by mozkan007** [uBlockOrigin/uBlock-issues#99]
Hi, I am using Ublock v1.16.10 and Chrome v67.0.3396.99 x64 on Windows x64. My laptop has i7 processor and 16 gb ram.

Coming to my issue, I have made a clean install for my browser and after I have installed Ublock using my backup file into Chrome, when I click to update filters button then a little time later, a chrome notification that Ublock has been crashed please click to reload appears on the right bottom side of the screen. Also while I am using Chrome, Ublock crashes and shut down nearly every 30-35 minutes. I am adding my Ublock backup file and Chrome crash (dmp) files into my issue. You can reproduce my problem using these files easily. I am not sure whether or not this problem is about Chrome or Ublock. Thanks.

[my-ublock-backup_2018-06-28_11.15.20.txt](https://github.com/uBlockOrigin/uBlock-issues/files/2144446/my-ublock-backup_2018-06-28_11.15.20.txt)

[dmp.zip](https://github.com/uBlockOrigin/uBlock-issues/files/2144447/dmp.zip)

**Comment by gwarser** [comment]
Out of memory on my 4GB system. Can you observe memory usage in Task Manager on filter update?

**Comment by mozkan007** [comment]
@gwarser  Yes I controlled from Task Manager and the value is 580 mb.

**Comment by gwarser** [comment]
Is this maximum? I see something like this:

![image](https://user-images.githubusercontent.com/886325/42025121-243aa8d4-7ac4-11e8-8241-24d585cec217.png)

Chromium crashes when RAM is exhausted. One of processes reaches ~1700MB

You must remove some filter lists from your HUGE collection.

**Comment by mozkan007** [comment]
@gwarser  Sorry I do not have so much knowledge about the working principle of softwares but as I can see from Windows Task Manager total ram usage of Chrome is 2.3 gb so as I said before I have 16 gb ram and nearly its 7 gb is free. So why do not Chrome or Ublock use this 7 gb? Or is there a way to  allocate this 7gb for Chrome?

**Comment by gwarser** [comment]
I'll wait for someone with more RAM to test this.

All is OK after importing your backup with custom filter lists stripped - 200 of them may be just too many.

**Comment by mozkan007** [comment]
@gwarser  I hope it will be found a way to solve this because it is ridiculous can not use Chrome comfortably although amount of memory this much.

**Comment by uBlock-user** [comment]
uBO cannot crash Chromium as it's only html/css/javascript, something else is causing Chromium to crash.

**Comment by mozkan007** [comment]
@uBlock-user  The problem is about ram usage of Ublock for my huge filter list according to @gwarser .

**Comment by uBlock-user** [comment]
I just tested your list on my machine, it loads successfully but starts lagging the dashboard all tabs on it and eventually the extension goes into an infinite crash loop, I had to uninstall and reinstall to stablize and break the loop, it takes about 100 megs of disk space, so from what I can see, uBO cannot handle such enormous amounts of filter lists.

For now, switch back to default settings until this matter is addressed.

**Comment by mozkan007** [comment]
@uBlock-user Thank you.

**Comment by gwarser** [comment]
This list is in wrong format and alone takes 109MB
http://osint.bambenekconsulting.com/feeds/dga-feed.txt

```
lmysitjfrlfe.com,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
ywxrfcfsfkka.net,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
obcnnlywgidc.biz,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
clbmktukthix.ru,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
pceolbajutah.org,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
dmdnijvwisfd.co.uk,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
oqfvjpiidulu.info,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
pmeioxcnqnji.com,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
prhwhfjurgia.net,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
qngjmndafygn.biz,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
sgkrmwymgdgx.ru,Domain used by Cryptolocker - Flashback DGA for 26 Jun 2018,2018-06-26,http://osint.bambenekconsulting.com/manual/cl.txt
```

**Comment by gwarser** [comment]
This one also does not looks good
https://hosts-file.net/download/HOSTS-Optimized.txt 12MB

```
127.0.0.1 -sso.anbtr.com 0-0-----------------------------------------------------------0.com 0-facebook.com 0-google.com 0.01.2.13.3.sydneypropertyinvestors.com 0.01.2.23.3.sydneypropertyinvestors.com 00-lawyer.com 000.9.009.09.ekurbani.com 000.9.019.09.ekurbani.com
127.0.0.1 0000.support 00000.support 000000-0.000webhostapp.com 0000000000-windows-block-notification.online 00001.001.xn--p1acf 000011.001.xn--p1acf 000012.001.xn--p1acf 00001alertx.info 00002alertx.info
127.0.0.1 00002alertz.info 000031.001.xn--p1acf 00004563.000webhostapp.com 00005ik.rcomhost.com 0000a-fast-proxy.de 0000pv6.rxportalhosting.com 000300.000webhostapp.com 000401.001.xn--p1acf 0004alertx.info
127.0.0.1 000601.001.xn--p1acf 000801.001.xn--p1acf 000am9r.rxportalhosting.com 000antispyware000.com 000apple000.com 000egjj.wcomhost.com 000fficemail.000webhostapp.com 000gpzz.wcomhost.com 000hejn.wcomhost.com
127.0.0.1 000hhjq.rxportalhosting.com 000host.totaocimall.com 000keca.wcomhost.com 000l26z.wcomhost.com 000l7kf.wcomhost.com 000lk3v.wcomhost.com 000ll4q.rcomhost.com 000lnd7.wcomhost.com 000scure0center0.000webhostapp.com
127.0.0.1 000secure0nline0.000webhostapp.com 000spyware000.com 000support000.com 000windows000.com 000x.club 000youtube.com 0019209939400009901100.win 001alertfound.info 001games.com
127.0.0.1 001host.net 001kanpou.com 002z2q0ezy.centade.com 003-pc.ru 004447d401c7bcd02db6fdd64d7be290.co.cc 004447d401c7bcd02db6fdd64d7be290.cz.cc 004b0bdd1.c11.ixsecure.com 005.free-counter.co.uk 0053671ce278333f8507c94b93ca687a.co.cc
127.0.0.1 0053671ce278333f8507c94b93ca687a.cz.cc 006.free-adult-counters.x-xtra.com 006.free-counter.co.uk 006001.001.xn--p1acf 00693goqsa.centade.com 007-dvd.com 007.free-counter.co.uk 007.go2cloud.org 007001.001.xn--p1acf
127.0.0.1 0075-7112-e7eb-f9b9.reporo.net 008.free-counter.co.uk 00889488394739.000webhostapp.com 0099000910290009001000.win 00antispyware00.com 00apple00.com 00apples00.com 00b0f00log00n0.000webhostapp.com 00c58006323de055d35ef57ff97f8036.co.cc
```

**Comment by uBlock-user** [comment]
Tested on Firefox Nightly, uBO doesn't crash, laggs from time to time, but no crashes. Seems this is isloated to Chromium.

**Comment by gwarser** [comment]
https://raw.githubusercontent.com/elypter/filter_processor/master/generated_filterlists/blockhead(decoy_generic_extraction).txt
https://raw.githubusercontent.com/elypter/filter_processor/master/generated_filterlists/blockhead(decoy_generic_selection).txt
wrong format
```
*.com##div[class*="nav"]:style(position: static!important)
*.com##div[id*="nav"]:style(position: static!important)
*.com##div[class*="share"]:style(position: static!important)
*.com##div[id*="share"]:style(position: static!important)
*.com##div[class*="inline"]:style(position: static!important)
*.com##div[id*="inline"]:style(position: static!important)
*.com##div[class*="social"]:style(position: static!important)
```

`domains.txt` - not sure which one - wrong format, 5MB
```
address=/000007.ru/0.0.0.0
address=/000007.ru/::
address=/000free.us/0.0.0.0
address=/000free.us/::
address=/000freexxx.com/0.0.0.0
address=/000freexxx.com/::
address=/001wen.com/0.0.0.0
address=/001wen.com/::
address=/0026645142c89aeb1.com/0.0.0.0
address=/0026645142c89aeb1.com/::
address=/003store.com/0.0.0.0
address=/003store.com/::
address=/007angels.com/0.0.0.0
address=/007angels.com/::
```
https://raw.githubusercontent.com/mat1th/Dns-add-block/master/adresses
wrong format, 3MB
```
zone "messenger.com" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "facebook.net" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "facebook.de" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "fbcdn.com" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "static.ak.fbcdn.net" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "static.ak.connect.facebook.com" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "connect.facebook.net" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "apps.facebook.com" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
zone "code.facebook.com" { type master; notify no; file "/etc/zone/master/null.zone.file";  };
```

`domains.txt` again - wrong format 1.6MB
```
		amazon.co.uk.security-check.ga	phishing	openphish.com	20171117	20160527	20160108
		autosegurancabrasil.com	phishing	openphish.com	20171117	20160527	20160108
		dadossolicitado-antendimento.sad879.mobi	phishing	openphish.com	20171117	20160527	20160108
		hitnrun.com.my	phishing	openphish.com	20171117	20160527	20160108
		maruthorvattomsrianjaneyatemple.org	phishing	openphish.com	20171117	20160527	20160108
		paypalsecure-2016.sucurecode524154241.arita.ac.tz	phishing	openphish.com	20171117	20160527	20160108
		tei.portal.crockerandwestridge.com	phishing	openphish.com	20171117	20160527	20160108
		tonyyeo.com	phishing	openphish.com	20171117	20160527	20160108
		update-apple.com.betawihosting.net	phishing	openphish.com	20171117	20160527	20160108
```


Your lists are full of trash.

**Comment by uBlock-user** [comment]
@mozkan007 Add filterlists only from https://filterlists.com/ and select those that cater to uBlock Origin's static filter format.

**Comment by mozkan007** [comment]
@uBlock-user  Ok. I will notice your information.

**Comment by gorhill** [comment]
> Your lists are full of trash.

Bottom line: garbage in, garbage out, users need to take responsibility for the filter lists they feed uBO.
