### ISSUE TITLE
Detection of malicious JavaScript

### ISSUE THREAD

**Issue by emanruse** [uBlockOrigin/uBlock-issues#991]
There are various white papers explaining ways to detect malicious JS code. One example:

https://people.cispa.io/ben.stock/papers/fass2018jast.pdf
https://github.com/Aurore54F/JaSt

Having such feature in an extension like uBO would open new possibility for blocking unwanted content and improving static filter lists.

I am not an expert on the subject of neural networks but IIUC it is also possible to create a library of particular malicious patterns and train such network to be more efficient as software versions progress.

What do you experts say?

**Comment by gwarser** [comment]
Out of uBO scope.

**Comment by uBlock-user** [comment]
Heuristic detection is out of any browser scope as WebExtensions framework doesn't support anything remotely close to this.
