### ISSUE TITLE
How to edit the My Rules/Permanent rules list

### ISSUE THREAD

**Issue by Telmesomething** [uBlockOrigin/uBlock-issues#992]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]https://www.startpage.com/do/search

### Steps to Reproduce

1. [First Step] Open Settings / My Rules
2. [Second Step] Attempt to edit, remove any of the content in the permanent rules list.
3. [and so on...]There's no way of doing this.

### Expected behavior:

There should be some way of achieving this goal.

### Actual behavior:

Unable to edit MyRules/Permanent rules list.

### Your environment

* uBlock Origin version: 1.26
* Browser Name and version: Waterfox Classic 2020.04
* Operating System and version: Windows 8.1

**Comment by gorhill** [comment]
> Attempt to edit, remove any of the content in the permanent rules list

By design. Edit temporary rules then click _Commit_ button.

**Comment by Xii-Nyth** [comment]
commit button is greyed out and pressing save delete them....

**Comment by gorhill** [comment]
> pressing save delete them

Probably because they are not [valid rules](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax).

**Comment by garry-ut99** [comment]
Which means that the question Xii-Nyth asked is a duplicate of :
- https://github.com/uBlock-LLC/uBlock/issues/1168

**Comment by gorhill** [comment]
I am going to add `cm-theme-override` to the editor to make syntax-highlighted errors more obvious.
