### ISSUE TITLE
http:// bypasses scriptlet injection from userResourcesLocation

### ISSUE THREAD

**Issue by raszpl** [uBlockOrigin/uBlock-issues#993]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

scriptlets from userResourcesLocation dont work on http:// pages despite logger showing successful injection 

### A specific URL where the issue occurs

http://example.com/

### Steps to Reproduce

userResourcesLocation set to https://gist.github.com/something containing one very simple scriptlet doing `console.log("blabla");`

my filters set to: 
```
example.com##+js(remove-attr.js, href, a)
example.com##+js(blabla)
```
first one is obviously a sanity check

going to https://example.com/ everything is ok
- Logger shows both scriptlets injected
- a element gets stripped of href attribute
- console shows "blabla"

### Expected behavior:

going to http://example.com/ 
- Logger shows both scriptlets injected
- a element gets stripped of href attribute
- console shows "blabla"

### Actual behavior:

going to http://example.com/
- Logger shows both scriptlets injected
- a element gets stripped of href attribute
- console is empty! 'blabla' scriptlet failed to execute despite being listed in Logger

### Your environment

* uBlock Origin version: 1.24.4
* Browser Name and version:  Chrome 80.0.3987.149 (Official Build) (64-bit)
* Browser Name and version:  Chrome 81.0.4044.83 (Official Build) beta (64-bit)
* Browser Name and version: Vivaldi | 3.0.1874.5 (Official Build) (64-bit), User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.114 Safari/537.36
* Operating System and version:  Windows 10

**Comment by gorhill** [comment]
Right, `https://gist.github.com/something` points to nothing and repro steps must be actually reproducible. Until proper repro steps are provided, this must be considered an invalid issue.

**Comment by gwarser** [comment]
All OK:

![image](https://user-images.githubusercontent.com/886325/79799796-5b955f80-835b-11ea-93fe-14d2af356432.png)

**Comment by raszpl** [comment]
> @gwarser 

thank you for sanity check, went over whole setup and problem was indeed between keyboard and the screen, sorry for wasting your time
