### ISSUE TITLE
Can't add *readthedocs.io to whitelist

### ISSUE THREAD

**Issue by vringar** [uBlockOrigin/uBlock-issues#997]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - I searched for wildcard and pattern and found no open bugs 
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
[As per the documentation](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site#specific-pattern) I should be able to whitelist all of `readthedocs.io`s subdomains by writing the rule `*readthedocs.io` or `*.readthedocs.io` however in both cases the `Apply changes` button gets grayed out.

### A specific URL where the issue occurs

`readthedocs.io`

### Steps to Reproduce

1. Go to Whitelist tab in the extension settings
2. Add `*example.com`
3. Try to click `Apply changes`

### Expected behavior:

That I can apply the changes

### Actual behavior:

That I couldn't apply these changes

### Your environment

* uBlock Origin version: 1.26.2
* Browser Name and version: Firefox Nightly on 77.0a1 BuildID 20200415092524
* Operating System and version: Linux 5.5.16-1-MANJARO

**Comment by gwarser** [comment]
Few lines above 

>If no `/` appears in a whitelist directive, and if the directive contains characters which are not allowed for a plain hostname, then the whitelist directive will be commented out and ignored by uBlock

**Comment by vringar** [comment]
Because I didn't think of it
Thank you, I'm just gonna go with that one then.
